### ISSUE TITLE
Container overflows vertically in AppBar only in 1.12.13

### ISSUE THREAD

**Issue by tadasss** [flutter/flutter#47058]
## Steps to Reproduce

Add an image or something bigger than the height of usable space in app bar. It doesn't matter if its within a Container, but I know previously Containers protected against these things.

The same code was working as it should before i updated to 1.12.13+hotfix.5 (from 1.9.something)

Seems to have been changed in #42936. From what I see the Jumbo item gets cut off at the top and bottom, and when i would rather have it not be jumbo and just BoxFit.contain. But that doesnt work

```bash
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter\flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Tadas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Tadas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • GM1917 • 0cd639ed • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @tadasss 
does this code represent the issue you are describing?

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
      title: FlutterLogo(size: 200),
    ),
  );
}
```
</details>

If so, how the behaviour you are expecting differs from the current one ?
thank you

**Comment by marciorr** [comment]
I have the same problem. Any fix  yet?

**Comment by micsan13br** [comment]
Same problem ... I need a fix too! :(
Are you using PreferredSize to encapsulate the AppBar ?

**Comment by marciorr** [comment]
I've tried but preferred to fix the height of the image instead of enlarging the AppBar.

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
