### ISSUE TITLE
[in_app_purchase] iOS consumable product / problem with broken purchases

### ISSUE THREAD

**Issue by Hemdoee** [flutter/flutter#47054]
Important problem with the in_app_purchase package.

When a user of my app purchase something, im storing the whole purchase object and send the data to my server. 
My server checks (via itunes api) if this purchase is valid. If its valid, my server sends a response to the app. If the response to my app is positive, im calling completePurchase (on iOS) and consumePurchase on Android. 

If my server doesnt give a positive feedback, i DONT consume or complete the purchase, as the tokens are not credited on my server for some reason. This is to prevent people from paying packs, which they never got. 

On Android it works perfectly. If the app crashs or got any other problems with communicating with my or the google servers, the user just need to reload the shop and queryPastPurchases does the trick. The whole purchase gets processed again, the app sends data to my server, my server to google and so on. At the end, the user gets his stuff credited.

On iOS, queryPastPurchases is empty. (Its a consumable product!)
So no automated restore of broken purchases like on Android.
This is a major issue and alot of customers complaining about that.

Ive checked the examples several times, it looks like queryPastPurchases should work here. 
There must be definitely a way to query past purchases to be able to check them on my server if they are valid and if yes, credit them and complete the purchase. Just like on android when you only consume it, when its definitely credited on the server. 

```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.864], locale de-DE)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Kevin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by dennis-tra** [comment]
I have the same problem and the idea on iOS is to listen for the `purchaseUpdatedStream`. According to the docs:
> If a purchase is not completed ([completePurchase] is not called on the purchase object) from the last app session. Purchase updates will happen when a new app session starts instead.

So when a call to your server fails you should receive another `PurchaseDetails` object after you restart the app. Unfortunately that's not the case for me (and others #45425). Interestingly the firebase analytics plugin seems to capture the old purchase events (also #45425).

**Comment by pawlowskim** [comment]
I was able to get previous not finished purchases when I start listener in ```main()```, but before ```runApp()```. When it was started before main, or somewhere else later on some page it didn't return previous purchases. New ones arrived correctly (even if they were not finished, I received message that it's already bought and will be restored but they came through listener).

**Comment by iapicca** [comment]
Hi @Hemdoee 
does the issue persist with the latest stable version of flutter
and [in_app_purchase](https://pub.dev/packages/in_app_purchase/versions) 0.3.1+2?
thank you

**Comment by TahaTesser** [comment]
Hi @Hemdoee 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
