### ISSUE TITLE
Export `Dart_NewWeakPersistentHandle`

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#47061]
Export `Dart_NewWeakPersistentHandle` in order for dart:ffi users to attach native resources that need finalization to execute such finalizations when the Dart object gets garbage collected.

**Comment by dcharkes** [comment]
`dart:ffi` finalizers (https://github.com/dart-lang/sdk/issues/35770) would expose these in Dart.

@derolf how would you get a Handle for the right objects if you'd want to use `Dart_NewWeakPersistentHandle` now?

**Comment by derolf** [comment]
@dcharkes I guess I need some more things. I am currently writing bindings for one of my companies SDKs (HERE Technologies). 

I already managed to solve dispatching asynchronous callbacks, everything works quite well so far. However, the biggest missing thing right now is a way to attach a native finalizer “somehow” to a Dart Object.

**Comment by virakpanha** [comment]
Check out At Smile House on Booking!  http://www.booking.com/Share-Qp38L1

**Comment by derolf** [comment]
Bump. Any update? What is so hard in exposing these functions?

**Comment by dcharkes** [comment]
We will solve this on the Dart side https://github.com/dart-lang/sdk/issues/40607.
