### ISSUE TITLE
Auto import does not work properly

### ISSUE THREAD

**Issue by wurikiji** [flutter/flutter#47065]
# Problem
![image](https://user-images.githubusercontent.com/5652744/70858315-c9fd7900-1eb4-11ea-8521-5955a2eecee3.png)
I am using VS Code (Version can be found in the `flutter doctor` below). The auto-import uses a relative path to the package for every package.

# Expected
`import 'package:flutter/material.dart';`

# Flutter Doctor

```
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.2 at /Users/wurikiji/work/flutter
    • Framework revision 4944622b5d (2 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wurikiji/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/wurikiji/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1
```

**Comment by fryette** [comment]
Same problem, how to fix it?

**Comment by wurikiji** [comment]
Somehow, it is working now while working with the abnormal auto import. I dont' know why.

**Comment by fryette** [comment]
Can it depend on flutter version?

**Comment by wurikiji** [comment]
No I didnt change anything. I dont know why.

**Comment by deep-gaurav** [comment]
A similar issue here #47124

**Comment by ShiinaManatsu** [comment]
> A similar issue here #47124

![image](https://user-images.githubusercontent.com/20186095/70970052-5f2c8780-20d8-11ea-9fe7-8cab84771c79.png)

In fact I get another problem, when wrap widget with container through VS code right click menu `Refactor`, it will import this library, and other widget do the similar.

**Comment by ShiinaManatsu** [comment]
I think you may have a try on mast channel, pretty confused with this problem.

**Comment by fryette** [comment]
Fixed by reinstalling flutter by git clone instead of using zip archive

**Comment by Ahmadre** [comment]
same, would be great if we roll back to previous state. I am on master channel like @ShiinaManatsu recommend, but still exists. Already restarted VSCode etc.

**Comment by ShiinaManatsu** [comment]
I just got this problem again, switch back to stable channel and it fixed, and it should work when switch to master channel.

**Comment by deep-gaurav** [comment]
This is not a flutter problem actually, The dart-sdk shipped with latest master has the package problem.
I confirmed this by testing it on a non flutter project with dart-sdk shipped with flutter and stable dart-sdk independently.

**Comment by alyyasser** [comment]
```
[√] Flutter (Channel dev, v1.13.5, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
    • Flutter version 1.13.5 at D:\Development\flutter
    • Framework revision 41a911099b (3 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Development\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for
      detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1
```

im having this issue too today, is there any workaround for this?

**Comment by ShiinaManatsu** [comment]
> ```
> [√] Flutter (Channel dev, v1.13.5, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
>     • Flutter version 1.13.5 at D:\Development\flutter
>     • Framework revision 41a911099b (3 days ago), 2019-12-19 13:48:02 -0800
>     • Engine revision 0f90e6546b
>     • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at D:\Development\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     X Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for
>       detailed instructions.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code, 64-bit edition (version 1.41.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.7.1
> ```
> 
> im having this issue too today, is there any workaround for this?

Try update your Android license. If that's not work, maybe we can only wait

**Comment by alyyasser** [comment]
> Try update your Android license. If that's not work, maybe we can only wait

i don't think that's the problem, because i've been leaving that license problem for few weeks (a month maybe) before and everything just fine until today (after upgrading the flutter).

**Comment by ShiinaManatsu** [comment]
Yeah this time I fix it by downgrade to 1.13.0 on master channel

**Comment by Rhywden** [comment]
The dev channel suffers from the same problem. So it's not just the master which is affected.

**Comment by ryanhoo** [comment]
@ShiinaManatsu You saved my day! 
Downgrade flutter to a previous version worked for me.

Solution step by step:

1. Run `flutter version v1.13.0` to downgrade to a specific version, in my case #47714  it's `v1.13.0`

2. Run `flutter pub upgrade` to upgrade dependencies for the project which has been affected

3. Run `flutter doctor` to check if everything is alright.

Now job is done and try the auto-import, it works! 🎉

![image](https://user-images.githubusercontent.com/1622320/71430444-cf559180-2706-11ea-902d-65513381e428.png)

**Comment by alyyasser** [comment]
it's fixed in master channel
```
[√] Flutter (Channel master, v1.13.6-pre.32, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
    • Flutter version 1.13.6-pre.32 at D:\Development\flutter
    • Framework revision ae24f18414 (5 hours ago), 2019-12-26 17:26:55 -0800
    • Engine revision 42bb7c9eea
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)
```

**Comment by ShiinaManatsu** [comment]
> it's fixed in master channel
> 
> ```
> [√] Flutter (Channel master, v1.13.6-pre.32, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
>     • Flutter version 1.13.6-pre.32 at D:\Development\flutter
>     • Framework revision ae24f18414 (5 hours ago), 2019-12-26 17:26:55 -0800
>     • Engine revision 42bb7c9eea
>     • Dart version 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)
> ```

Thanks for the mention! That's so cool!

**Comment by wurikiji** [comment]
> it's fixed in master channel
> 
> ```
> [√] Flutter (Channel master, v1.13.6-pre.32, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
>     • Flutter version 1.13.6-pre.32 at D:\Development\flutter
>     • Framework revision ae24f18414 (5 hours ago), 2019-12-26 17:26:55 -0800
>     • Engine revision 42bb7c9eea
>     • Dart version 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)
> ```

Thanks for the mention! I've tested and confirmed it. I am closing this issue.
