### ISSUE TITLE
[Atom] [OS X] The null object does not have a getter 'debuggingEnabled'.

### ISSUE THREAD

**Issue by dmitry-zaitsev** [flutter/flutter#4706]
## Steps to Reproduce

0. Start iOS Simulator
1. Create a new flutter project (via command line or Atom - it's irrelevant)
2. Press Run button in Atom.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/Dmitry/projects/flutter
    • Framework revision 6d2d495369 (2 weeks ago), engine revision a943c732d5

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /Users/Dmitry/Library/Android/sdk
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_51-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

## Logs and Crash Reports

```
Error running 'lib/main.dart'.
The null object does not have a getter 'debuggingEnabled'.

NoSuchMethodError: method not found: 'debuggingEnabled' Receiver: null Arguments: []
```

App builds and installs correctly when built via Terminal (`flutter run`). All of the above is on OS X.

**Comment by eseidelGoogle** [comment]
@devoncarew was this the same issue we were seeing with @DaveShuckerow yesterday?

**Comment by devoncarew** [comment]
I think it's a separate issue.

**Comment by dmitry-zaitsev** [comment]
OK, issue is not reproducible in master.

**Comment by pallaviashim** [comment]
This issue is there if you clone from branch "codelab".  [Firechat sample app from Codelab](https://codelabs.developers.google.com/codelabs/flutter/index.html#1) asks to clone the sdk from branch "codelab".

**Comment by eseidel** [comment]
@collinjackson is in the process of updating the codelab branch.  Right now the codelab branch is incompatible with the most recent Atom plugin.  You can work around this by installing an older version of the Atom plugin @devoncarew would know the command.

**Comment by devoncarew** [comment]
Yup, `apm install dartlang@0.6.26` from the command line will roll your atom plugin back in time ~30 days.
