### ISSUE TITLE
Can't build my flutter project after upgrading to stable version 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#47060]
Can't build my flutter project after upgrading to stable version 1.12.13+hotfix.5. I can run my app on my android device and iPhone as well as I can run on both emulator. But flutter build appbundle has an error. I need urgent help.

**flutter build appbundle**
```bash
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on
    https://goo.gl/CP92wY.
Dart snapshot generator failed with exit code -9                        
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -9
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/**********/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/**********/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 18s  
``` 

**flutter doctor -v**
```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CY)
    • Flutter version 1.12.13+hotfix.5 at /Users/**********/flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/**********/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] Connected device
    ! No devices available

```

**Comment by frgmt** [comment]
I have the same issue.. How can I solve this?

**Comment by adityastic** [comment]
https://flutter.dev/docs/development/androidx-migration

**Comment by dev-shanghai** [comment]
I am facing the same issue, I even tried running from opening in Xcode. 
Pod upgrade, Pod cache clean, nothing worked for me to run on iOS.

**Comment by JerryMatera** [comment]
Same issue here on Linux. After the upgrade the Android toolchain now has lots of errors even after doing upgrades it demanded. Projects I worked on before the upgrade are just fine

**Comment by shriharip** [comment]
facing the same issue with the upgrade to this version. It works in debug mode on simulator but on iOS it fails with white screen

**Comment by frgmt** [comment]
/here. Does it work if you use different version's flutter?
You can change it with `flutter version x.x.x`.

**Comment by iapicca** [comment]
Hi @NTMS2017 
the latest stable version of flutter uses androidx by default,
you may want to follow the link provided in your own logs and upgrade to androidx
or downgrade your flutter version as suggested by @frgmt.

@dev-shanghai @shriharip if the issue you are experiencing is with iOS
it's most likely unrelated with this one, please open a separate issue  
providing all or some of the information indicated in the template.
Thank you

**Comment by zmvx** [comment]
I solved it such,change 'cached_network_image' version to "^2.0.0-rc"

**Comment by NTMS2017** [comment]
uninstalled and install stable version. I created my app again, check the android x documentation on flutter.dev. I run all my plugin and run the basic flutter app. Once everything worked I replace the standart flutter main.dart to my app main.dart and all the other files and folders. I build agan with new version for android and iOS and update it again. Everything's works now.

**Comment by contactlockten** [comment]
fresh new project also not working 

Dart snapshot generator failed with exit code -9                        
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -9
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.

**Comment by sandeepgurram** [comment]
I got the same issue, when I changed from develop to stable flutter channel. I deleted `.pub-cache` and `bin/cache` folder and run any flutter command it will update the files again, I run `flutter clean` in my project

**Comment by hudhaifa93** [comment]
I run `flutter clean` in my project and it worked perfect.
