### ISSUE TITLE
Scroll friction does not match other Android apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4707]
I'm sure the same is true on iOS too, I can get a video for that.  I would expect users to notice this, subconsciously if nothing else.
https://youtu.be/_fdln_D1kM8

**Comment by eseidelGoogle** [comment]
This was reported on gitter just now.  I think @HansMuller mentioned he was looking at improving this for android last week.  @chinmaygarde also landed https://github.com/flutter/scroll_overlay for iOS, we could add the Android side now too.

**Comment by Hixie** [comment]
Hans measured this and got as close as reasonably possible. If it's still not good then we should get a new bug with more specific actionable ways to determine the difference.
