### ISSUE TITLE
ReorderableListview improvement needed

### ISSUE THREAD

**Issue by coolit** [flutter/flutter#47077]
When using ReorderableListview, it works fine when you reorder upwards, but when you reorder downwards, the transition isn't triggered soon enough. I guess in case of downwards reorder, the top line instead of bottom line of the object below should be used to trigger.

**Comment by iapicca** [comment]
Hi @coolit 
does this [code ](https://dartpad.dartlang.org/77dd46957eb6860f4a59354ca92dac39)represent the issue you are describing?
thank you

**Comment by coolit** [comment]
Hi @iapicca 
Could you please check out this [code](https://github.com/X-Wei/flutter_catalog/blob/master/lib/routes/lists_reorderable_ex.dart)
Thanks

**Comment by VladyslavBondarenko** [comment]
@coolit 
please follow up on https://github.com/flutter/flutter/issues/46576,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
