### ISSUE TITLE
gradle 3.5.3

### ISSUE THREAD

**Issue by darasat** [flutter/flutter#47072]
Good day guys , I updated my flutter environment to 1.12

I have the following configuration on gradle 

```gradle
ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

1. . but I tried the command flutter run --verbose I get this error

```bash
[+619883 ms] AAPT2 aapt2-3.5.3-5435860-windows Daemon #0 Failed to shutdown within timeout
[+3788 ms] java.util.concurrent.TimeoutException: AAPT2 aapt2-3.5.3-5435860-windows Daemon #0: Failed to shut down within 30 seconds. Forcing shutdown
[  +66 ms]      at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.stopProcess(Aapt2DaemonImpl.kt:224)
[        ]      at com.android.builder.internal.aapt.v2.Aapt2Daemon.shutDown(Aapt2Daemon.kt:140)
[   +1 ms]      at com.android.builder.internal.aapt.v2.Aapt2Daemon.handleError(Aapt2Daemon.kt:175)
[   +1 ms]      at com.android.builder.internal.aapt.v2.Aapt2Daemon.handleError$default(Aapt2Daemon.kt:160)
[   +1 ms]      at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:120)
[  +39 ms]      at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:175)
[ +165 ms]      at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnableKt.processResources(Aapt2ProcessResourcesRunnable.kt:80)
[  +35 ms]      at
com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$AaptSplitInvoker.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:840)
[ +155 ms]      at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$AaptSplitInvoker.run(LinkApplicationAndroidResourcesTask.kt:722)
[   +3 ms]      at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
[  +66 ms]      at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
[   +1 ms]      at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
[  +31 ms]      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
[  +30 ms]      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
[   +1 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)      
[   +1 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)      
[  +61 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[   +3 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[   +1 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[  +89 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
[  +58 ms]      at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
[   +1 ms]      at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
[   +1 ms]      at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
[   +2 ms]      at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
[  +61 ms]      at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
[   +1 ms]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ]      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
[   +1 ms]      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
[  +28 ms]      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
[   +2 ms]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[   +1 ms]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[  +45 ms]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[  +16 ms]      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[   +3 ms]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ +167 ms]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[   +2 ms]      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[  +31 ms]      at java.lang.Thread.run(Thread.java:748)
[   +1 ms] FAILURE: Build failed with an exception.
[  +50 ms] * What went wrong:
[   +9 ms] Execution failed for task ':app:processDebugResources'.
[   +1 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +1 ms]    > AAPT2 aapt2-3.5.3-5435860-windows Daemon #0: Link timed out, attempting to stop daemon.
[   +1 ms] > Task :app:processDebugResources FAILED
[        ] 78 actionable tasks: 6 executed, 72 up-to-date
[   +1 ms]      This should not happen under normal circumstances, please file an issue if it does.
[   +1 ms] * Try:
[   +8 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

what could it be?

thank you!

cheers.

**Comment by darasat** [comment]
I included in gradle file this

android.enableR8=true

and now the console shows: 


Unsuported Android Plugin version: 3.5.3.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      getGradleVersionFor (package:flutter_tools/src/android/gradle_utils.dart:203:3)
#2      getGradleVersionForAndroidPlugin (package:flutter_tools/src/android/gradle_utils.dart:150:10)
#3      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:821:7)
#4      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#15     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by iapicca** [comment]
Hi @darasat 
could you please try running
`flutter clean`
`flutter pub cache repair`
let me know if it fixes the issue
thank you

**Comment by darasat** [comment]
I am thinking that it´s a flutter framework problem

I tried to:

1. Repair pub cache
2. Migrate to android x with visual studio
3. Upgrade - Downgrade flutter framework
4. Change gradle config (3.5.3 to 3.5.2 and 3.5.0)
5. Flutter clean
6. Make another project and see what happens (with this project without plugins the framework runs, but with some third party the framework crashes)


Gradle build failed to produce an .apk file. It's likely that this file was generated under "PATH"\build, but the tool couldn'tfind it.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:827:3)
#2      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

When google will to review this? it's supossed to be the version 1.12 will be stable..

thanks for your help.

**Comment by darasat** [comment]
I fix it creating a new project and checking plugin by plugin.

**Comment by arnemolland** [comment]
Why was this closed? I'm not sure I understand what you meant by "checking plugin by plugin". Did you just avoid using the plugins causing your errors?

I'm having this exact issue at the moment. Builds fine with gradle, but fails when using the flutter tools.

**Comment by iapicca** [comment]
Hi @arnemolland 

I believe the author of the issue 
is entitled to close it anytime.

Please note that some plugins, in particular 3rd party plugins, aren't "1.12 ready"
in that case the possible solutions are:
- waiting for the plugin to be update;
- avoid using the plugin;
- downgrade Flutter.

Did you try the proposed [solution](https://github.com/flutter/flutter/issues/47072#issuecomment-566004659)? 
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by arnemolland** [comment]
Fixed by downgrading to plugin version 3.5.0 — maybe the error message should describe that the error is with the Flutter build tools, along with the latest supported Gradle + Android plugin version? At the moment it’s unclear where the error is coming from.

Found the fix by browsing the [Flutter build tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_utils.dart) source.

**Comment by medyas** [comment]
@arnemolland getting the same issue and been looking for solution for couple of days know. thank you for finding the problem

**Comment by arnemolland** [comment]
I suspect it’s more work than just bumping the version, and Gradle just had a major release (6.0) that might be a little more comprehensive to support. I might be completely wrong though, as I’m not familiar with the toolchain.

**Comment by medyas** [comment]
the plugin version 3.5.3 also supports '5.6.2' so don't think if its going to cause any damage

**Comment by arnemolland** [comment]
There's a PR open [here](https://github.com/flutter/flutter/pull/46260). Tested locally by bumping max version to 3.5.3 (and Gradle to 6.0), works perfectly fine. You can do so yourself on a fork if you need it before the PR lands.

**Comment by swaggymiller** [comment]
when i meet this, and i create a new project that meet the same problem, now i don't know how to fix it when has passed one week,(i am in china maybe firewall influnce network runs)

**Comment by kouxinhong** [comment]
if app/build.gradle code
```
  splits {
        abi {
            enable true
            reset()
            include "x86","x86_64", "armeabi-v7a","armeabi-v8a"
            universalApk true
        }
    }
```
delete it

**Comment by BorhnN** [comment]
Weirdly @kouxinhong 's comment worked in my case.

But that's probably shouldn't be the case.

And also `flutter build apk --split-per-abi` does not generate apks with version number defined in `android/app/build.gradle`

**Comment by jonahwilliams** [comment]
I'm not really sure what issue this bug is tracking. The original filled issue is an internal Gradle failure so I'm closing it.

**Comment by IDFDeveloper** [comment]
I got this solution from [here](https://stackoverflow.com/questions/55861519/upgraded-to-android-studio-3-4-aapt2internalexception-aapt2-daemon-startup-f/61156603#61156603) I hope someone will get help.
