### ISSUE TITLE
Use MotionEvent.getHistoricalX/Y to improve fling velocity estimator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4708]
@abarth says the lack of the historical information (which android provides us) causes our flings to be off.

**Comment by Hixie** [comment]
As far as I'm aware we have been doing this for a long time. That's how the estimator works; by using historical data.

**Comment by abarth** [comment]
This issue is about using https://developer.android.com/reference/android/view/MotionEvent.html#getHistoricalX(int, int)

**Comment by goderbauer** [comment]
It's not clear what using Android's API would give us over what we are already doing. We are already creating our own history in the velocity estimator. Closing this for now.
