### ISSUE TITLE
Do locale resolution in embedders

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#47087]
Internal: b/146064414

There are many internal issues/questions/confusion around how Flutter does locale resolution. While we provide a way to override our basic resolution algorithm, developers want resolution behavior *that is consistent with the underlying platform* which is very tricky to achieve with x-plat code.

I have talked to @GaryQian and @jason-simmons about this and we sketched out a plan to provide additional information from embedders on each platform to Dart code. Currently, embedders provide only the user select system locale (if exists). In addition, we propose that embedders provide:

- The list of locales that the application supports.
- The list of ordered locales that the system recommends (a strict subset of the above).

Today, #1 is specified in Dart. However, it is also duplicated in `Info.plist` file on iOS. We need to figure out a way to pass a list of supported locales to embedder at build time. This will ensure we have a single source of truth for supported locales. `pubspec` is the current proposed way.

**Comment by mehmetf** [comment]
go/flutter-embedder-localization is the internal doc

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by mehmetf** [comment]
I am tentatively marking this as critical. Our customers are rolling their own (imperfect) solutions as we speak to unblock their launches. The sooner we do this, the easier it will be to migrate them.

**Comment by GaryQian** [comment]
- [ ] Framework-side work (exposing new API, modifying algorithm)
- [ ] Engine-side work (passing the locales from platform channels to app startup, supported locales passing)
- [ ] Android embedder resolution implementation
- [ ] iOS embedder resolution implementation

**Comment by stuartmorgan** [comment]
Should I add macOS to that checklist, or was it omitted deliberately?

**Comment by mehmetf** [comment]
This should be supported for all embedders. Notes on go/flutter-embedder-localization mentions MacOS.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/17755 Includes engine side work that passes a new localization message through to dart.

**Comment by GaryQian** [comment]
Design doc: go/flutter-embedder-localization

**Comment by GaryQian** [comment]
Bring iOS supported locales in sync with android's format: https://github.com/flutter/engine/pull/18379

**Comment by GaryQian** [comment]
Send platformResolved locales from iOS Embedder: https://github.com/flutter/engine/pull/18519

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/56167 Uses a l10n.yaml file to define localization arb configs. We can consider also using this file to become the canonical place to define supported locales, and use the gen_l10n tool to generate the necessary assets for each embedder/framework.

**Comment by mehmetf** [comment]
Note that internally we don't (intend to) use #56167. Build system is different.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/18645 Passes supported locales down from Dart to embedder via the Engine and uses embedder specific API to obtain locale resolution.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/19136 Cleans up old/unused/obsolete API

**Comment by GaryQian** [comment]
Android-side locale resolution algorithm: https://github.com/flutter/engine/pull/19266

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/58482 Exposes `window.ComputePlatformResolvedLocale` which may be used in the custom locale resolution callback as an extra factor to consider.

We do not yet use the platform resolved locale in the default algorithm. This change would be breaking and it is debatable if it is even better than the current Flutter one.

**Comment by chinmaygarde** [comment]
@GaryQian Can this be closed? Are there other remaining work items?

**Comment by GaryQian** [comment]
This is done for Android and iOS. Still pending Web and Desktop, however, it is unclear if this is even applicable to those platforms, so I will close this!

I believe the current web implementation is to return null as this is not an applicable operation

**Comment by stuartmorgan** [comment]
Locale support is absolutely relevant to desktop. Comments above said that macOS was explicitly in scope, for example.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/19597 begins desktop embedder implementation

**Comment by stuartmorgan** [comment]
Per offline discussion, I misunderstood what this was covering exactly. Passing an ordered list is in scope for desktop (and not currently done), but I'm not sure if any of the desktop platforms need the custom resolution callback.

**Comment by GaryQian** [comment]
In that case, we can leave the entrypoint into desktop embedders, and if need be, implement custom resolution in the future. I'll file an issue to do so and close this one as the primary platforms that need this are done.
