### ISSUE TITLE
Unable to run 'adb' check your Android SDK

### ISSUE THREAD

**Issue by fathy22** [flutter/flutter#47084]
Unable to run 'adb' check your Android SDK installation and ANDROID_HOME environment variable

**Comment by iapicca** [comment]
Hi @fathy22 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by fathy22** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.3.9600], locale ar-EG)
    • Flutter version 1.12.13+hotfix.5 at E:\Flutter\flutter
    • Framework revision 27321ebbad (5 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Fathy Ramadan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    • Flutter plugin version 42.1.3
    • Dart plugin version 192.7761

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: C:\Users\Fathy Ramadan\AppData\Local\Android\sdk\platform-tools\adb.exe

**Comment by iapicca** [comment]
Hi @fathy22 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47037) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by fathy22** [comment]
Could you provide the link of  that issue you mentioned?

**Comment by iapicca** [comment]
@fathy22  
"issue" it's an hyperlink to this https://github.com/flutter/flutter/issues/47037

**Comment by ArunEdathadan** [comment]
Reinstalling Android Studio Solved Mine

**Comment by sumeshsheoran** [comment]
please check your adb file is missing at Android/sdk/platform-tools solution is to download new platform tools and replace with current one
