### ISSUE TITLE
"Classes" directory missing in xcode using the "plugin" template for flutter create

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#47091]
On https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-hmswift, it says:

> The iOS platform code of your plugin is located in Pods/Development Pods/hello/Classes/ in the Project Navigator.

While this folder does indeed exist in the file system, the workspace does not display it. Manually adding it via "Add Files to Pods" gets reverted after a seemingly arbitrary amount of time.

EDIT: The folder _does_ show up for some reason under

`Development Pods/<plugin_name>/../../example/ios/.symlinks/plugins/<plugin_name>/ios/Classes` (The `..` folders are actual folder names in the view)

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (1 available)

```

**Comment by chadalen** [comment]
Related issue #19601

**Comment by jmagman** [comment]
I reopened https://github.com/flutter/flutter/issues/19601, this is a duplicate, as @chadalen already noticed. 😄
