### ISSUE TITLE
inferred type is MainActivity but FlutterEngine was expected

### ISSUE THREAD

**Issue by omaralmgerbie** [flutter/flutter#47095]
when i run my app after upgrading flutter SDK i'm having this issue when i run the app on an android device 

```bash
Launching lib\main.dart on Mi 9T in debug mode...
e: D:\AndroidProjects\flutter\insta_clone\android\app\src\main\kotlin\com\example\insta_clone\MainActivity.kt: (11, 48): Type mismatch: inferred type is MainActivity but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

my `MainActivity.kt` code 

```java
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}

```

Working on `Flutter channel Stable `

**Comment by HasseneKh** [comment]
i have the same probleme

**Comment by iapicca** [comment]
Hi @omaralmgerbie 
could you please run 
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by Chad-Ortho2** [comment]
I had the same issue after performing the steps mentioned by @iapicca 

I noticed creating a new app using `flutter create` from the `stable` branch generates this `MainActivity.kt` file 

``` kotlin
package foo.bar.foo

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```
Which differs from the boilerplate in my app (same as referenced by @omaralmgerbie).  As a workaround I updated the contents of my `MainActivity.kt` to match the new scaffold.

**Comment by omaralmgerbie** [comment]
@iapicca 
not working 
New error Pops out 
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.0\android\src\main\java\io\flutter\plugins\firebase\storage\FirebaseStoragePlugin.java:60: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
>         binding.getApplicationContext(), binding.getFlutterEngine().getDartExecutor());
>                                                 ^
> 1 warning
> Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> e: D:\AndroidProjects\flutter\insta_clone\android\app\src\main\kotlin\com\example\insta_clone\MainActivity.kt: (11, 48): Type mismatch: inferred type is MainActivity but FlutterEngine was expected
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 34s
> Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

**Comment by iapicca** [comment]
Hi @omaralmgerbie 
did the solutio proposed by @Chad-Ortho2 worked for you?
thank you

**Comment by rootasjey** [comment]
Hello,
I had the same issue and the solution proposed by @Chad-Ortho2 worked for me 
(I did the steps recommended by @iapicca before).

**Comment by arnaudelub** [comment]
Hi,
i had the same issue today, replacing my MainActivity.kt with the one from @Chad-Ortho2 comment worked for me too.
Thanks

**Comment by SachinSingh812** [comment]
I would recommend visiting flutter docs once. This link
https://flutter.dev/docs/development/platform-integration/platform-channels#step-3-add-an-android-platform-specific-implementation
