### ISSUE TITLE
List<Dynamic> assignment to List<String> Fails Silently In Flutter

### ISSUE THREAD

**Issue by rhhub** [flutter/flutter#47099]
The following code hangs silently in Flutter and crashes on dartpad.
```
void main() {
  List<dynamic> listOfDynamic = ['hello'];

 // In flutter the following line indefinitely hangs silently without crashing.
  List<String> listOfString = listOfDynamic;

  print(listOfString);
}
```

Tried at https://dartpad.dartlang.org/ with crash and following error message:
`
Error: Error: TypeError: Instance of 'JSArray': type 'JSArray is not a subtype of type 'List<String>'`

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (1 available)

• No issues found!

**Comment by goderbauer** [comment]
If this is an issue it should be filed with dart: https://github.com/dart-lang/sdk
