### ISSUE TITLE
 daemon not running; starting now at tcp:5037.   error: cannot connect to daemon

### ISSUE THREAD

**Issue by akima88** [flutter/flutter#47093]
Hi guys. I started to learn (The Complete 2020 Flutter Development Bootcamp with Dart). Installed Flutter and Android Studio as well. 
Got stuck with below issue that could not solve it and can not go further:

<img width="671" alt="1" src="https://user-images.githubusercontent.com/16277383/70867809-a99fee00-1f8a-11ea-8057-5f92109af7c4.PNG">

<img width="432" alt="2" src="https://user-images.githubusercontent.com/16277383/70867817-c9cfad00-1f8a-11ea-8dd0-976afff072fb.PNG">

**Comment by akima88** [comment]
10:35 PM	* daemon not running; starting now at tcp:5037

10:35 PM	could not read ok from ADB Server

10:35 PM	* failed to start daemon

10:35 PM	error: cannot connect to daemon

10:35 PM	'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server' failed -- run manually if necessary

**Comment by james-method** [comment]
Do you have the android SDK installed correctly?

**Comment by iapicca** [comment]
Hi @akima88 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47037) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.

Also please run `flutter doctor --android-licences`
and please refrain from posting pictures if not necessary.

Thank you

**Comment by akima88** [comment]
Unable to establish a connection to adb.

Check the Event Log for possible issues.
This can happen if you have an incompatible version of adb running already,
or if localhost is pointing to the wrong address.
Try re-opening Studio after killing any existing adb daemons and verifying that your
localhost entry is pointing to 127.0.0.1 or ::1 for IPv4 or IPv6, respectively.

If this happens repeatedly, please file a bug at http://b.android.com including the following:
  1. Output of the command: 'C:\Users\******\AppData\Local\Android\Sdk\platform-tools\adb.exe devices'
  2. Your idea.log file (Help | Show Log in Explorer)
