### ISSUE TITLE
Loading local images provides high performance memory cache support, while loading network images provides memory and local secondary cache support, such as image loading provides properties MemoryCache: true, localCaahe: true, Instead of using third-party libraries.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#47098]
Loading local images provides high performance memory cache support, while loading network images provides memory and local secondary cache support, such as image loading provides properties
MemoryCache: true, localCaahe: true,
Instead of using third-party libraries.

**Comment by iapicca** [comment]
Hi @gionchat 
can you describe the issue or the proposal more in details?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
