### ISSUE TITLE
material import isn't recognized in non-nullable experiment 

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#47092]
DISCLAMER: I know that non-nullable feature is under dev and supposed to be buggy, I just want to report a (maybe solvable) problem.

<img width="815" alt="Screenshot 2019-12-15 at 22 19 35" src="https://user-images.githubusercontent.com/39897981/70867732-904a7200-1f89-11ea-8c0b-d75d87db6ab1.png">

The other packages (cupertino and widgets) are understood correctly.

## Steps to reproduce
1) create analysis_options.yaml and add - non-nullable to the enable-experiment section
2) create a stateful/-less widget
3) import 'package:flutter/material.dart'

**Comment by HansMuller** [comment]
There's quite of work to be done before Flutter can be migrated to Dart NNBD, see https://github.com/dart-lang/sdk/labels/NNBD

**Comment by darshankawar** [comment]
Hi @VadimOsovsky,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
