### ISSUE TITLE
Support for Material Design List Items

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#471]
http://www.google.com/design/spec/components/lists.html#lists-specs

For list items whose content matches one of the conventional patterns in the spec, a convenient Widget that implemented the layout would be helpful.

Single-line, two-line, and three-line lists with optional avatars and icons.

**Comment by abarth** [comment]
We have `ListItem`, which is a start along these lines.

**Comment by abarth** [comment]
We have this in general.  If there are specific other things we need, we should file more bugs.
