### ISSUE TITLE
[Web] Flutter bacame unstable after upgrading "dev v1.13.2"

### ISSUE THREAD

**Issue by KodaiTakata** [flutter/flutter#47100]
I upgraded to `dev v1.13.2`
Since then lots of things got weird. 
Buttons throw exception when only hovering it.
So I can't even press the button.
Also I was able to build in release mode before upgrade but now shows white blank page.
In debug mode, sometimes you need to build a couple of times to run because local host can't be launched. 
Even worse, local hosts which is chrome keep increasing on the Windows task bar  with the message "launching main.dart in debug mode".
Anyone having the same problem?
Thanks!

**Comment by iapicca** [comment]
Hi @KodaiTakata 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by KodaiTakata** [comment]
Sorry about that.
I switched to beta channel, run in release mode and no more those problems.
Thank you for your help!
I really appreciate.
