### ISSUE TITLE
Exception has occurred. PlatformException (PlatformException(sign_in_canceled, com.google.GIDSignIn, The user canceled the sign-in flow.))

### ISSUE THREAD

**Issue by peterkuch** [flutter/flutter#47102]
google_sign_in: ^4.1.0 , run as debug after login google dialog and user cancel app error exception with IOS. how can help?

**Comment by iapicca** [comment]
Hi @peterkuch 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by bawoodruff** [comment]
I can reproduce this with google_sign_in: 4.1.4

Exception has occurred.
PlatformException (PlatformException(sign_in_canceled, com.google.GIDSignIn, The user canceled the sign-in flow.))

```
void signInWithGoogle() async {
     final _googleSignIn = GoogleSignIn();

      try {
        final GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
        final GoogleSignInAuthentication googleSignInAuthentication =
            await googleSignInAccount.authentication;
      } catch (_) {
        print("Error!");
      }
    }
```

**Comment by bawoodruff** [comment]
```[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.15.3 at /Users/<user>/Projects/OSS/flutter
    • Framework revision 67826bdce5 (3 weeks ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.1.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.1.1.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 19A9D9C7-F2C6-43FB-AB9B-FFC7BD7866D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.122
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!```

**Comment by bawoodruff** [comment]
@VladyslavBondarenko - This issue does not reproduce with flutter run against the iOS simulator.  It appears to be an issue with Visual Studio Code and the Flutter plugin where these exceptions are not treated as "caught".
The break occurs at the line calling siginIn() if the user cancels the initial Google Login dialog (in the simplest case).
If "Uncaught Exceptions" is unchecked in Visual Studio Code then the catch() in the same above is triggered.    This may be an issue with PlatformException handling in the tool chain.

**Comment by iapicca** [comment]
Hi @peterkuch 
does the issue occur in debug or release?
could you please provide you `flutter run --verbose`?
Thank you

**Comment by bochitan** [comment]
i got same problem in VSCode with google sign in v4.2.0
Tested on iOS Simulator
