### ISSUE TITLE
Flutter webapplication (Beta) loads very slowly in IDE 

### ISSUE THREAD

**Issue by keesbroenink** [flutter/flutter#47117]
Machine: basic laptop with Windows 10 Home and SSD disk
IDE: IntelliJ Community Edition latest version
Project: Dart project
Similar to https://itnext.io/flutter-for-web-c75011a41956
The basic Flutter demo app needs 10 seconds to display on Chrome and 18 seconds on Firefox. After loading the responsiveness is fine.

Note that just serving the application (html, js etc) with a simple webserver is a different story. Performance is fine. So I guess the problem has to do with the IDE setup.

**Comment by marvinIsSacul** [comment]
after running `flutter build web` (release mode)... is your application still able to run correctly?

My fails to load to generated JavaScript files...

**Comment by keesbroenink** [comment]
For me the application works correctly

**Comment by marvinIsSacul** [comment]
may you please send me your `pubspec.yaml` file...

**Comment by keesbroenink** [comment]
name: freshui
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

**Comment by iapicca** [comment]
Hi @keesbroenink 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47106) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by keesbroenink** [comment]
Okay fine with me
