### ISSUE TITLE
Flutter Driver package not available

### ISSUE THREAD

**Issue by duncwillz** [flutter/flutter#47123]
Hello Team, kindly verify the link to flutter driver on this page, 

https://flutter.dev/docs/cookbook/testing/integration/introduction 

`could not find package flutter_driver at https://pub.dartlang.org), version solving failed.`

**Comment by iapicca** [comment]
Hi @duncwillz 
just added `flutter_driver` to a new project without issues
```yaml
dev_dependencies:
 flutter_driver:
    sdk: flutter
```
can you please provide your `flutter doctor -v`,
your `pubspec.yaml` and your `flutter packages get --verbose`?
[flutter packages get --verbose.txt](https://github.com/flutter/flutter/files/3968430/flutter.packages.get.--verbose.txt)


Thank you

**Comment by duncwillz** [comment]
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-GH)
    • Flutter version 1.12.13+hotfix.5 at /Users/duncanadjei/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/duncanadjei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 6.0 (API 23) (emulator)
    • iPhone 11 Pro             • 2B6FACDA-6862-48FB-AE2B-21AD8EA2CBD4 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
`

**Comment by iapicca** [comment]
Hi again @duncwillz 
can you please provide your `pubspec.yaml` and your `flutter packages get --verbose`?
thank you

**Comment by duncwillz** [comment]
Pub
