### ISSUE TITLE
MethodChannel in flutter 1.12

### ISSUE THREAD

**Issue by YangDingLi** [flutter/flutter#47120]
I have been use MethodChannel transfer data between the flutter and android native. 
```public MethodChannel(BinaryMessenger messenger, String name)```

I used to give it a ```io.flutter.view.FlutterView```
However, I need to use ```io.flutter.embedding.android.FlutterView``` in flutter 1.12, and I can't find a ```BinaryMessenger``` in it.

So how to use platform channel in flutter 1.12?

**Comment by YangDingLi** [comment]
https://github.com/flutter/flutter/blob/master/examples/platform_channel/android/app/src/main/java/com/example/platformchannel/MainActivity.java

**Comment by sakeyu** [comment]
@YangDingLi thanks
