### ISSUE TITLE
connectivity dependency does not build in release mode

### ISSUE THREAD

**Issue by SBNTT** [flutter/flutter#47122]
`flutter run --release`

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
``` 

sdk.dir is present in my android/local.properties

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale fr-FR)
    • Flutter version 1.12.13+hotfix.5 at /Users/sbntt/flutter
    • Framework revision 27321ebbad (5 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sbntt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sbntt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sbntt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Users/sbntt/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • ONEPLUS A6003 • a8e258a3 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @SBNTT 
could you please run 
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by SBNTT** [comment]
Hi,

Error is still there.
does the full build output helps ?

```
 flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.6/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.2+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_performance-0.3.1+4/android/src/main/java/io/flutter/plugins/firebaseperformance/FirebasePerformancePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleRelease'...                                                                                                                                                                 Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/image_jpeg-1.1.1/android/src/main/java/com/yangyxd/imagejpeg/ImageJpegPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+11/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
/Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());                   
                        ^                                                                                          
1 warning                                                                                                          
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
                                                                                                                   
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':image_jpeg:verifyReleaseResources'.                                                    
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
   > Android resource linking failed                                                                               
     /Users/sbntt/.gradle/caches/transforms-2/files-2.1/de633fab5705acbce5b6dd3356ab4c4e/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                                                                   
     /Users/sbntt/.gradle/caches/transforms-2/files-2.1/de633fab5705acbce5b6dd3356ab4c4e/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                                                                   
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 55s                                                                                             
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     178,3s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   12,4s
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s


The plugin connectivity could not be built due to the issue above.
```

**Comment by iapicca** [comment]
Thank you @SBNTT

**Comment by Icyoung** [comment]
same with you

 flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':flutter_native_image:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/icy/.gradle/caches/transforms-2/files-2.1/66ec8c9e439f1c666907245b569d6532/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /Users/icy/.gradle/caches/transforms-2/files-2.1/66ec8c9e439f1c666907245b569d6532/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 5s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       6.1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin barcode_scan...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.8s
✓ Built build/app/outputs/repo.
Building plugin bugly_crash...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.9s
✓ Built build/app/outputs/repo.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.5s


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by Icyoung** [comment]
flutter doctor                    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C46a, locale zh-Hans-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

**Comment by Icyoung** [comment]
about gradle :
gradle-5.6.2-all

'com.android.tools.build:gradle:3.5.1'

android.useAndroidX=true
android.enableJetifier=true

**Comment by asfos22** [comment]
Hey also having the same issue  in release mode:
connectivity 0.4.6+1

**Comment by krishnaaro** [comment]
> Hi,
> 
> Error is still there.
> does the full build output helps ?
> 
> ```shell
>  flutter build apk --release
> You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
> If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
>     To generate an app bundle, run:
>         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
>         Learn more on: https://developer.android.com/guide/app-bundle
>     To split the APKs per ABI, run:
>         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
>         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
> Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.6/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                    
> Note: Some input files use or override a deprecated API.                
> Note: Recompile with -Xlint:deprecation for details.                    
> Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.2+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                    
> Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_performance-0.3.1+4/android/src/main/java/io/flutter/plugins/firebaseperformance/FirebasePerformancePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                    
> Note: Some input files use or override a deprecated API.                
> Note: Recompile with -Xlint:deprecation for details.                    
> Running Gradle task 'assembleRelease'...                                                                                                                                                                 Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/image_jpeg-1.1.1/android/src/main/java/com/yangyxd/imagejpeg/ImageJpegPlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.                                                                 
> Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+11/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                                                               
> Note: /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                                                               
> /Users/sbntt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
>     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());                   
>                         ^                                                                                          
> 1 warning                                                                                                          
> Note: Some input files use or override a deprecated API.                                                           
> Note: Recompile with -Xlint:deprecation for details.                                                               
>                                                                                                                    
> FAILURE: Build failed with an exception.                                                                           
>                                                                                                                    
> * What went wrong:                                                                                                 
> Execution failed for task ':image_jpeg:verifyReleaseResources'.                                                    
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
>    > Android resource linking failed                                                                               
>      /Users/sbntt/.gradle/caches/transforms-2/files-2.1/de633fab5705acbce5b6dd3356ab4c4e/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
>                                                                                                                    
>      /Users/sbntt/.gradle/caches/transforms-2/files-2.1/de633fab5705acbce5b6dd3356ab4c4e/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
>                                                                                                                    
>                                                                                                                    
> * Try:                                                                                                             
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                                                                    
> * Get more help at https://help.gradle.org                                                                         
>                                                                                                                    
> BUILD FAILED in 2m 55s                                                                                             
> Running Gradle task 'assembleRelease'...                                                                           
> Running Gradle task 'assembleRelease'... Done                     178,3s (!)
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> Building plugin connectivity...
> Running Gradle task 'assembleAarRelease'...                             
> Running Gradle task 'assembleAarRelease'... Done                   12,4s
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'connectivity'.
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 11s
> 
> 
> The plugin connectivity could not be built due to the issue above.
> ```

for temp solution i replaced connectivity plugin with connectivity_wrapper and built release apk in native android project.....
looking for fix.

**Comment by xizhouhezai** [comment]
I have the same problem. My solution is to change the compilesdkversion 27 of android/build.gradle in the error reporting plugin to 28. And then it's solved

**Comment by SBNTT** [comment]
This does not helps for connectivity plugin as it already has  `compilesdkversion`  set to 28

**Comment by SBNTT** [comment]
Actually, this is not related to the connectivity plugin :)

**Comment by Sarthaktydy** [comment]
What is the solution for this?

**Comment by Sarthaktydy** [comment]
> Actually, this is not related to the connectivity plugin :)

Hey what is the solution for this?

**Comment by SBNTT** [comment]
@Sarthaktydy if you are in the exact same case
replace
```yaml
image_jpeg: ^1.1.1
```

by

```yaml
image_jpeg:
    git:
      url: https://github.com/yangyxd/image_jpeg
```

in your pubspec.

**Comment by Sarthaktydy** [comment]
> @Sarthaktydy if you are in the exact same case
> replace
> 
> ```yaml
> image_jpeg: ^1.1.1
> ```
> 
> by
> 
> ```yaml
> image_jpeg:
>     git:
>       url: https://github.com/yangyxd/image_jpeg
> ```
> 
> in your pubspec.

Hey I'm not using image_jpeg
here are the plugins I'm using
 ```
cupertino_icons: ^0.1.2
  device_info: "^0.2.1"
  shared_preferences: "^0.4.2"
  flutter_webview_plugin: "0.3.10+1" 
  connectivity: "0.4.5+3"
  flutter_launcher_icons: "^0.7.0"
  image_picker: "0.6.1+4"
  url_launcher: "5.4.1" 
  flutter_html_view: "^0.3.1"
  firebase_messaging: "6.0.9"
  flutter_web_browser: "0.11.0"
```
the error im getting
```
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

```
This happens when I run command
`flutter build apk
`
but `
flutter build appbundle`
works fine
but I'm not sure if I pust app.abb bundle it can break my app.

**Comment by AllinGaming** [comment]
Hey @Sarthaktydy one of those dependencies isn't set to compile SDK 28 you have to check by yourself which one. I just had a problem with keyboard_visibility, I know you don't use it but I checked it out and set to a working branch

  keyboard_visibility:
    git:
      url: https://github.com/rafalbednarczuk/flutter_keyboard_visibility

 and now it's working. I hope you find your culprit and share it with us!

**Comment by Sarthaktydy** [comment]
> Hey @Sarthaktydy one of those dependencies isn't set to compile SDK 28 you have to check by yourself which one. I just had a problem with keyboard_visibility, I know you don't use it but I checked it out and set to a working branch
> 
> keyboard_visibility:
> git:
> url: https://github.com/rafalbednarczuk/flutter_keyboard_visibility
> 
> and now it's working. I hope you find your culprit and share it with us!

Already tried checking it in plugin. Connectivity is on     compileSdkVersion 28
and also         targetSdkVersion 28. IDK what to do I'm fed up

**Comment by SBNTT** [comment]
You need to check all your dependencies to find which one has the wrong
sdkversion

Le jeu. 16 janv. 2020 à 15:58, Sarthaktydy <notifications@github.com> a
écrit :

**Comment by AllinGaming** [comment]
@Sarthaktydy Don't check connectivity, check the other dependencies as @SBNTT said. I had the same error as you had i thought the connectivity dependency was creating it but it wasn't it was another dependency that wasn't compileSdkVersion 28.

cupertino_icons: ^0.1.2
 device_info: "^0.2.1"
 shared_preferences: "^0.4.2"
 flutter_webview_plugin: "0.3.10+1" 
 connectivity: "0.4.5+3"
 flutter_launcher_icons: "^0.7.0"
 image_picker: "0.6.1+4"
 url_launcher: "5.4.1" 
 flutter_html_view: "^0.3.1"
 firebase_messaging: "6.0.9"
 flutter_web_browser: "0.11.0"

one of these isn't right. First thing I'd do is do a packages upgrade and then check all their respective git repos to see which one has the issue because you're using older versions as  shared_preferences: "^0.4.2" the current is   shared_preferences: ^0.5.6 ?

**Comment by AllinGaming** [comment]
I am pretty sure that packages upgrade will fix your problem you're probably using some outdated versions of dependencies that don't have a androidX migration

**Comment by AllinGaming** [comment]
@Sarthaktydy Upgrade all the dependencies you have to the newest version and tell me what happens

**Comment by AllinGaming** [comment]
@Sarthaktydy try putting flutter_launcher_icons: "^0.7.0" into
 dev_dependencies:
  flutter_launcher_icons: ^0.7.3

**Comment by AllinGaming** [comment]
https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/android/app/build.gradle flutter_launcher_icons has compilesdkversion 27 please put it in dev_dependencies.

**Comment by byawitz** [comment]
So, this is the final solution that works for me.
1. Try to update all your flutter dependencies. 
2. Search anywhere for the string `compilesdkversion` and be sure it has the exact value you have in your `android/app/build.gradle`

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by ghozay19** [comment]
hi i still has this problem, 
how to fix this ?

![image](https://user-images.githubusercontent.com/27909159/74318511-fef05400-4daf-11ea-9b29-7dedb610a29b.png)

**Comment by byawitz** [comment]
> So, this is the final solution that works for me.
> 
> 1. Try to update all your flutter dependencies.
> 2. Search anywhere for the string `compilesdkversion` and be sure it has the exact value you have in your `android/app/build.gradle`

try this

**Comment by devfadl** [comment]
> hi i still has this problem,
> how to fix this ?
> 
> ![image](https://user-images.githubusercontent.com/27909159/74318511-fef05400-4daf-11ea-9b29-7dedb610a29b.png)

have you solve this problem ?

**Comment by ghozay19** [comment]
> > hi i still has this problem,
> > how to fix this ?
> > ![image](https://user-images.githubusercontent.com/27909159/74318511-fef05400-4daf-11ea-9b29-7dedb610a29b.png)
> 
> have you solve this problem ?

solved after upgrading all dependencies

**Comment by tehort** [comment]
Also having the same issue, happens only on release mode.

**Comment by SBNTT** [comment]
The solution has been explained multiple times. Read carrefully guys!

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Jigneshiosdeveloper** [comment]
I have the same problem when i created **flutter build apk** .

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

 pubspec.yaml

connectivity: ^0.4.2

help me if anyone found the solution 😌

**Comment by tehort** [comment]
> 
> 
> I have the same problem when i created **flutter build apk** .
> 
>     * What went wrong:
>       A problem occurred configuring root project 'connectivity'.
> 
> 
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> pubspec.yaml
> 
> connectivity: ^0.4.2
> 
> help me if anyone found the solution 😌

verify the source code of all your plugins / dependencies and alter the sdk version to 28, if there are plugins any under that version

**Comment by ghozay19** [comment]
> > > hi i still has this problem,
> > > how to fix this ?
> > > ![image](https://user-images.githubusercontent.com/27909159/74318511-fef05400-4daf-11ea-9b29-7dedb610a29b.png)
> > 
> > 
> > have you solve this problem ?
> 
> solved after upgrading all dependencies
> 
> edited:
> 
> solved only on debug mode.
> 
> when run flutter build apk --release --target-platform=android-arm64
> 
> still have this problem

I just solved all problem, and for everyone who still has this problem,

1. please upgrade all of your dependencies.
2. open your project in android mode, sync all Gradle. please make sure all Gradle are passed successfully
in my case I have a root checker, this dependency is not in android x, even its in last update
so I must manually change to android x.
3. problem solved.

**Comment by Jigneshiosdeveloper** [comment]
@tehort Thanks a lot for your response 😀

**Comment by Zeeshan0201** [comment]
@Jigneshiosdeveloper stoll getting same issue after upgrading all packages with this command.flutter `packages upgrade`

**Comment by Lameck1** [comment]
flutter packages upgrade
----------------------------

This one has done the magic for me.

**Comment by maheshmnj** [comment]
I got the same error while building the app after added a sms package which was using compiled skd version 27, I simply upgraded its version to 28 and it worked.
related issue  https://github.com/flutter/flutter/issues/27226#issuecomment-567018039

**Comment by bulgarian-beast** [comment]
I have finally solve this error:

You have to check, one by one each versions of your dependencies in your pubspec.yaml.
During one week I got stuck bcs my version of path_provider package wasn't the latest.
