### ISSUE TITLE
[Add2App] The typed characters in a TextField are lost when backgrounding the app with focus on the TextField on Android

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#47137]
Using the new embedding API for Android to embed Flutter in an existing app, it is possible for the TextField to lose its last typed characters when backgrounding the app on Android.

The following simple Flutter module code will create a TextField.

Launch the Flutter module in the existing app
Start typing text in the field
With focus still in the field, background the app using the Home button
Come back to the app. Notice the focus is still in the field and the keyboard is hidden, but the characters disappear.

If you take focus off of the TextField before backgrounding the app, then when coming back, the characters remain.

This is related to #35054, but the fix for that bug either introduced this or revealed it.

The following is the code in the flutter module:
```
// Main app entry
void main() {
   runApp(MyApp());
}

class DefaultEmptyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: TextField(
              decoration: InputDecoration(
                  labelText: "Enter Text"
              ),
            )
        )
    );
  }
}

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      home: DefaultEmptyPage(),
    );
  }
}
```

**Comment by dannyvalentesonos** [comment]
@dnfield #35054 is fixed, but now this bug is happening. 
Thanks

**Comment by dnfield** [comment]
@iapicca this is very unlikely to require input from the Android team :)  removing the dependency label.

This _probably_ needs changes in engine or framework, possibly both.  Adding those.

**Comment by matthew-carroll** [comment]
@dnfield any idea if there is some kind of flushing logic that takes place when removing focus from a textfield that therefore wouldn't be triggered upon app backgrounding?

**Comment by dnfield** [comment]
This is reproducible for any app with the new embedding - it's not add2app specific.

**Comment by dnfield** [comment]
I have a fix for this.  Writing a test now.

**Comment by dnfield** [comment]
@matthew-carroll  - it's something like that, yes.

**Comment by voiddog** [comment]
Same problem too

**Comment by dnfield** [comment]
The fix for this introduced some other unexpected breakages.  It's going to be reverted until I can work that out.

**Comment by dnfield** [comment]
I believe I have another, safer fix for this.
