### ISSUE TITLE
flutter web: Another exception was thrown: Instance of 'minified:bw<void>'

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#47142]
Another exception was thrown: Instance of 'minified:bw<void>'
Total canvas memory use exceeds the maximum limit (384 MB)

**Comment by jonahwilliams** [comment]
> Another exception was thrown: Instance of 'minified:bw'

This is generally not the actual error thrown, but some later message. You need to provide the original error message, along with `flutter doctor -v` and some code that reproduces the issue or we won't be able to help.

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
