### ISSUE TITLE
Set bounds on google_maps_flutter GoogleMap to contain all markers

### ISSUE THREAD

**Issue by pcrady** [flutter/flutter#47146]
I am trying to get the camera position of the GoogleMap to fit all makers placed on the map. The javascript API has a map.fitBounds function. 

```   
createMarkers () {
  this.clearMarkers()
  var bounds = new window.google.maps.LatLngBounds()
  for (var i = 0; i < this.houseData.length; i++) {
    var marker = this.createMarker(this.houseData[i])
    var markerPosition = new window.google.maps.LatLng(marker.position.lat(), marker.position.lng())
    this.markers[this.houseData[i]._id] = marker
    bounds.extend(markerPosition)
  }
  this.map.fitBounds(bounds)
  this.map.panToBounds(bounds)
}
```

Is there currently any functionality in the google_maps_flutter package that supports this or are there any workarounds that achieve the same functionality? 

Thanks,

I'm pretty new at flutter so I apologize if this is a stupid question.

**Comment by albinjal** [comment]
Maybe check out [this](https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/CameraUpdate/newLatLngBounds.html) method.

**Comment by pcrady** [comment]
That worked really well Thanks.

**Comment by tehsunnliu** [comment]
Hi, the link is broken.
