### ISSUE TITLE
Put devicelab devices into airplane mode

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#47149]
This should disable the automatic OS upgrade (see [this comment][1]) which is causing both flaky test failures (https://github.com/flutter/flutter/issues/45435) and benchmark regressions (e.g., https://github.com/flutter/flutter/issues/42671).

[1]: https://github.com/flutter/flutter/issues/45641#issuecomment-559311288

**Comment by liyuqian** [comment]
CC @digiter @keyonghan @godofredoc

**Comment by digiter** [comment]
I have turned on airplane mode on all the devices today, let's see how that works.

**Comment by dnfield** [comment]
This causes the following problem:

```
Unable to verify App         A connection to the App Store is required for the first launch of "Flutter Gallery" on this iPhone. Please connect to the Internet and try again.
```

When trying to launch new apps on the phone. We should revert this change.

**Comment by digiter** [comment]
As iPhone needs the internet to verify app, I have turned on WiFi for all the iPhones. But the Android  phones still have airplane mode on.
