### ISSUE TITLE
Sentry package - send events created offline when online

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#47140]
## Use case
While using the Sentry package and sending events/exceptions you will lose data if offline. The package should save the messages until a point when the device has network again. 

This data can be critical to supporting your app in the field.

## Proposal
The Sentry package should save events/exceptions created while offline and send them when online

**Comment by bruno-garcia** [comment]
Offline caching is definitely useful but it's also required to handle hard crashes (i.e: segfault or a UncaughtExceptionHandler on Android). That's because often it's not possible to even stablish a TLS connection with Sentry before the app is gone.

Offline caching is supported by Sentry's cocoa and android SDKs already so ideally we'll do the same as the react-native Sentry SDK and simply piggy back on the native SDKs.

**Comment by MisterJimson** [comment]
@bruno-garcia I would actually prefer a pure dart implementation. Much more portable for web/desktop, like the current one is. All the app would need to provide is a path to write to.

**Comment by bruno-garcia** [comment]
There are surely many advantages of having it all written in Dart. One of the downsides is that it won't capture crashes that happen in any Java code, or native (like a segfault). Even though we hope to provide as much functionality in a pure Dart SDK, IMHO most cases will be advisable to use the hybrid one.

**Comment by MisterJimson** [comment]
Perhaps the base library can be dart based but with a native plugin library that adds specific support per platform when needed.

**Comment by bruno-garcia** [comment]
Agreed, we'll work on the Dart API too, it should still have a lot more features on its own.

**Comment by emsaints** [comment]
A problem with this hybrid approach is that it won't work on other Flutter platforms like Windows or macOS.

**Comment by bruno-garcia** [comment]
Sentry has SDKs for [macOS](https://github.com/getsentry/sentry-cocoa) and [Windows (native)](https://github.com/getsentry/sentry-native) and I assume one would want to capture also hard crashes caused by native code and that we could only do with some native SDK underneath.

**Comment by marandaneto** [comment]
We've released an alpha version of it for Android and iOS, give it a try and let us know if you find any issues :)
https://docs.sentry.io/platforms/flutter/

**Comment by bruno-garcia** [comment]
This was resolved.
The Sentry SDK for Flutter persists events to disk by default: https://docs.sentry.io/platforms/flutter/
