### ISSUE TITLE
CupertinoContextMenuAction color isn't right

### ISSUE THREAD

**Issue by KalilDev** [flutter/flutter#47150]
CupertinoContextMenuAction does not color the trailingIcon appropriately.

It is being colored with the destructiveAction unconditionally, as of now.
https://github.com/flutter/flutter/blob/c06bf6503a8b6690b2740a7101852fcc8f133057/packages/flutter/lib/src/cupertino/context_menu_action.dart#L138

## Steps to Reproduce

1. Create an CupertinoContextMenuAction with an trailingIcon and isDestructiveAction set to false.

[Dartpad](https://dartpad.dev/34fe8198644eefee9f4b543868793c6f)

**Target Platform:** All
**Target OS version/browser:** Unapplicable
**Devices:** Unapplicable

## Logs

Unapplicable

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Linking PR https://github.com/flutter/flutter/pull/47151

**Comment by justinmc** [comment]
Closing with https://github.com/flutter/flutter/pull/47151 :tada:
