### ISSUE TITLE
Allow the flutter_tool to depend package:kernel from the SDK

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#47162]
There are a number of features and cleanups that would be supported by using package:kernel, pacakage:front_end, or the incremental compiler dependencies in the flutter tool. Specifically:

- Exploration of in-process frontend_server (+ performance)
- Icon subsetting by parsing kernel files
- Injection of user provided kernel transformers into frontend_server (https://github.com/flutter/flutter/issues/36738)

Currently these are blocked by two issues:

- The flutter_tool requires all of its sources to be present when snapshotting, but the entrypoint scripts only download the Dart SDK and not any auxiliary files. We'd need to either add packages to our distribution of the Dart SDK or update the download script to include more artifacts.

- The flutter_tool transitively depends on the analyzer, through the build_runner ~~and linter~~ (https://github.com/flutter/flutter/pull/47174) packages. Since the analyzer dependency (vended from pub) and kernel packages (vended from SDK) share a dependency, we cannot depend on both without using something like dependency overrides. This could easily break anytime those shared APIs are updated.
  * build_runner dependency may be reduced with https://github.com/flutter/flutter/issues/41951

cc @zanderso 

EDIT:

the flutter tool now only depends on the analyzer through test_core (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml#L43)

**Comment by jonahwilliams** [comment]
Also FYI @dnfield

**Comment by dnfield** [comment]
Would it help any if we just vended the relevant Dart SDK packages (including analyzer) and depended on local copies in the cache directory instead of from pub?

**Comment by jonahwilliams** [comment]
No, because the build_runner packages (used currently for web support) aren't developed in the SDK. This won't be an issue once we switch to the frontend_server

**Comment by zanderso** [comment]
If/when the existing transitive dependencies on package:kernel are removed, how do we avoid reintroducing new ones?

**Comment by jonahwilliams** [comment]
We should be prevented from adding new dependencies by pub's default version solving. We will likely add the kernel, front_end packages as path dependencies. Pub will prevent depending on a package from both a path dependencies and from pub, since it can't version solve them.

**Comment by dnfield** [comment]
Do we think we can eliminate the dependency on build_runner, or just reduce it?

**Comment by jonahwilliams** [comment]
Besides the build script for the web, which could technically be moved to a separate package, we only use it for testing.

**Comment by dnfield** [comment]
Even if we moved it to a seprate package we'd still have the transitive dependency right?

I'm asking for a path forward on the icon font shaking.  I think I'm pretty close to having everything else I'd need to make that work.  One option to move forward is to (temporarily?) put the kernel parsing logic into the engine repo, building it with dart2native, and vending it to the tool to run as a subprocess.

I know this is not preferred, but it could unblock icon shaking and still allow us to eventually move it into the tool when package:kernel can be a direct dependency of the tool (and with the version that corresponds to the Dart SDK being used by the tool).

**Comment by jonahwilliams** [comment]
In this particular setup, the build_script is used as the entrypoint for a different dart vm instance, so there is no interaction.

> One option to move forward is to (temporarily?) put the kernel parsing logic into the engine repo, building it with dart2native, and vending it to the tool to run as a subprocess.

Yeah that seems like the best way forward for now, since it matches what we do with the frontend server today. I don't think you should necessarily wait for us to solve the versioning issues here, since who knows what other sorts of issues I'll run into :)

**Comment by dnfield** [comment]
Unfortunately, I think dart2native based solution(s) will be blocked until https://github.com/dart-lang/sdk/issues/39106 is resolved.

**Comment by jonahwilliams** [comment]
I would skip dart2native and just ship a kernel snapshot

**Comment by mkustermann** [comment]
> Exploration of in-process frontend_server (+ performance)

What benefit / performance improvement would you expect from this?

> Injection of user provided kernel transformers into frontend_server (#36738)

The prerequisite for this would be having a more stable kernel API, which we don't have atm and is not on the direct roadmap (afaik). @mraleph @johnniwinther

> > > Icon subsetting by parsing kernel files
> > I'm asking for a path forward on the icon font shaking. 
> One option to move forward is to (temporarily?) put the kernel parsing logic into the engine repo, 
> building it with dart2native, and vending it to the tool to run as a subprocess.

The flutter widget transformer is living in the [dart-lang/sdk](https://github.com/dart-lang/sdk) repository atm. Can't this icon shaker also live there?

> Unfortunately, I think dart2native based solution(s) will be blocked until dart-lang/sdk#39106 is resolved.

There's the option to use `dart2native --output-kind=aot`, which creates the AOT snapshot separately (instead of a self-contained executable). It can then be launched via `dartaotruntime <aot-snapshot>' (the `dartaotruntime` should already be signed).

Alternatively you can use AppJIT or kernel snapshots.

**Comment by jonahwilliams** [comment]
> What benefit / performance improvement would you expect from this?

Initially I would expect some minor performance improvements via reduction in serialization, shedding of the difficult to maintain stdin/stdout API. Longer term it would allow us to support a more exotic architecture, where an editor or IDE could propose source changes that we resolve via a hybrid memory/disk filesystem, or potentially propose edits to the kernel directly.

> The prerequisite for this would be having a more stable kernel API, which we don't have ATM and is not on the direct roadmap 

Understood - In the meantime the Icon shaker has also moved to the flutter/engine repository. I would note that the widget transformer needing to live in the dart SDK repo might indicate some layering violations that could be addressed with a stable kernel API.
