### ISSUE TITLE
"flutter create ." (for adding web support to plugin) fails on "invalid package name"

### ISSUE THREAD

**Issue by m0nac0** [flutter/flutter#47168]
## Steps to Reproduce
Run "flutter create ." in a plugin directory, where the plugin has specified a valid package name in pubspec.yaml but the folder name contains invalid characters (like '-').
In my case the plugin "mapbox_gl" is contained in a folder called "flutter-mapbox-gl" and calling "flutter create ." inside this folder (to add web support) fails.
## Logs

"flutter-mapbox-gl" is not a valid Dart package name.

From the [Pubspec format description](https://www.dartlang.org/tools/pub/pubspec.html):

**DO** use `lowercase_with_underscores` for package names.

Package names should be all lowercase, with underscores to separate words,
`just_like_this`.  Use only basic Latin letters and Arabic digits: [a-z0-9_].
Also, make sure the name is a valid Dart identifier -- that it doesn't start
with digits and isn't a reserved word.

## Flutter version
I'm running Flutter  v1.12.13+hotfix.6 on channel beta.

**Comment by m0nac0** [comment]
I've also tried to pass the plugin's actual name as `--project-name`, but although the command finishes successfully then, it doesn't do what it should (e.g. it creates a new `main.dart` file)

**Comment by zanderso** [comment]
@jonahwilliams was recently looking around here.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce this locally. Note that `flutter create .` must be run within the project directory, unlike `flutter create name`

**Comment by m0nac0** [comment]
I am running `flutter create .` in the top-level folder that contains pubspec.yaml as well as the android, example, lib etc. folders (I assume this is the project directory?). The issue seems to be that the project directory has a name that differs from the name the plugin specifies in pubspec.yaml and the project directory's name contains characters ('-' in this case) that are invalid for a plugin name.

**Comment by jonahwilliams** [comment]
Are you also providing the --project-name option?

**Comment by m0nac0** [comment]
I just tried that again. That e.g. creates a new `/lib/main.dart` , a new `/android/app` directory with a new MainActivity and 12 different new ressource/Manifest/etc. files and and also a new `/ios/Runner` directory with about 30 new files. I'm not sure about iOS but for Android this doesn't seem to be what I want, as an Android implementation of the plugin already exists at the `/android` directory.

**Comment by jonahwilliams** [comment]
I'm still not able to reproduce this issue. I suspect you are either failing to provide the project-name option correctly or running in the wrong directory.

**Comment by amit0rana** [comment]
Steps to reproduce: please use this project stub: https://github.com/londonappbrewery/magic-8-ball-flutter.git

Now to go the project folder and do 
`flutter create .`

As rightly pointed by @m0nac0 flutter keeps taking folder name as project name.

`flutter create --projec-name magic_8_ball .` works fine.
