### ISSUE TITLE
Performance test wiki

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#47171]
Currently, it's not very easy to figure out how to add a performance test to the Flutter repo. The resources are scattered around (e.g., [internal doc][1], https://flutter.dev/docs/cookbook/testing/integration/profiling, https://github.com/flutter/flutter/tree/master/dev/devicelab)

It might be nice to have a single Wiki page under https://github.com/flutter/flutter that goes over the whole process of how to add a
- frame build/raster time performance test
- memory performance test
- CPU/GPU/energy performance test
- app size performance test

[1]: https://docs.google.com/document/d/1UolaKhEWieP2DDOhFuVQOuR5e545mO2obXcHH6p40Y4/edit#bookmark=id.70t9gnas5d1j

**Comment by kf6gpe** [comment]
I'm going to give this one to the engine team as an AI, too, since @liyuqian filed it.
