### ISSUE TITLE
[Text] Allow for line height *between* lines on text. 

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#47175]
## Use case

This is the default behavior for `TextView`s on Android. The `lineHeight` param only applies [between lines](https://developer.android.com/reference/android/widget/TextView#attr_android:firstBaselineToTopHeight). This is useful, for example, when you want to increase the line height in your `TextTheme`. For multiple lines of text, this will increase the spacing between the lines of text. But, importantly, for single lines of text, they will remain unaffected. This means that if you have single line of text that is vertically aligned with a button or a switch, the text will not be affected (and appear off center). 

## Proposal

It would be nice to have API in `TextStyle` for specifying the `lineHeight` behavior. Maybe it could be an enum, something like:

```dart
enum LineHeightBehavior {
   betweenLinesOnly,
   aboveAndBelowLines,
   ...
}
```

That way on `TextStyle` I could do something like 
```dart
TextTheme(
  body1: TextStyle(
    height: 1.2,
    lineHeightBehavior: LineHeightBehavior.betweenLinesOnly,
  ),
),
```
.

**Comment by GaryQian** [comment]
A simpler parameter may just be something like:
```
Text(
  'blah',
  lineSpacingBetweenLinesOnly: true,
)
```

Of course, if there were additional enums other than these two behaviors, then an enum may make more sense. Something like this should not belong on the TextStyle though, as it is possible to have many TextStyles in a single paragraph/line/word. LibTxt and dart:ui has a concept of ParagraphStyle, which in the framework is exposed as just properties on the TextWidget itself.

**Comment by johnsonmh** [comment]
> Something like this should not belong on the TextStyle though, as it is possible to have many TextStyles in a single paragraph/line/word.

The reason I think it makes sense on `TextStyle` is that the `height` parameter is set on `TextStyle`. So to me it makes sense to keep those parameters together. It also makes it much easier to use with the existing `TextTheme` and `DefaultTextStyle` APIs if this parameter lives on `TextStyle`. 

What happens when you set multiple different `TextStyle.height` params on a single line/word ?

**Comment by GaryQian** [comment]
> What happens when you set multiple different TextStyle.height params on a single line/word ?

The line will use the maximum ascent and descent.

If it were on TextStyle, we would have to disambiguate what to do when there are multiples styles on the line, one with the first line having spacing, other with first line ignoring spacing.

**Comment by johnsonmh** [comment]
Ah, I see. Would we be able to make some sort of convenient API for declaring this behavior once per app? Something at the top of our app so that users wouldn't have to say `Text('foo', lineHeightBehavior: ...)` every time they want to use a `Text` widget?

**Comment by GaryQian** [comment]
The property can also be added in DefaultTextStyle which will allow all the Text widgets to be set at once.

**Comment by GaryQian** [comment]
The property itself can be a maskable enum where the line spacing for different parts of the paragraph can be enabled/disabled by setting bits.

For example something like this:

111 => all spacing enabled
010 => only spacing between lines
101 => only spacing above first line and below last line
011 => disable spacing above first line

**Comment by Hixie** [comment]
I hesitate to expose the 101 case unless we have a reason to support that.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/15087 Starts engine-side work

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/48346 exposes this on the framework side.

**Comment by dnfield** [comment]
Reopening until this lands in framework (and because I'm reverting engine change for now).

**Comment by GaryQian** [comment]
Oops, did not realize this was closed! Github autoclosed it :(

**Comment by kaikai4989** [comment]
Late to the game ... but I am wondering whether "height" is the right way to achieve line spacing in the first place because "height" is font-family-specific (each font defines its own ascent and descent to be multiplied by "height"), which means "height" becomes tricky when controlling line spacing if a line has two different fonts.

In this kind of situation, usually people would prefer StrutStyle to control the line height, with its "leading" support. Actually, line-spacing was called "leading" in old times, see https://en.wikipedia.org/wiki/Leading for details.

So I am wondering whether we should extend TextHeightBehavior to have similar opt-in for "leading", as it should be able to exclude the first line / last line as well.
