### ISSUE TITLE
update to lastest happen some errors

### ISSUE THREAD

**Issue by tzt1994** [flutter/flutter#47186]
today，update flutter plugin to the lastest. the applicairon is ok before update.but now is wrong.

'package:flutter/src/widgets/framework.dart': Failed assertion: line 1687 pos 14: 'children != null': is not true.

**Comment by iapicca** [comment]
Hi @tzt1994 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
