### ISSUE TITLE
`TextField.onChanged` behavior doesn't follow the docs

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#47191]
The `TextField.onChanged` docs say:

```dart
/// {@macro flutter.widgets.editableText.onChanged}
///
/// See also:
///
///  * [inputFormatters], which are called before [onChanged]
///    runs and can validate and change ("format") the input value.
///  * [onEditingComplete], [onSubmitted], [onSelectionChanged]:
///    which are more specialized input change notifications.
```

Which is basically *go look for `EditableText.onChanged`*, which in turn says:

```dart
/// {@template flutter.widgets.editableText.onChanged}
/// Called when the user initiates a change to the TextField's
/// value: when they have inserted or deleted text.
///
/// This callback doesn't run when the TextField's text is changed
/// programmatically, via the TextField's [controller].
...
```

### So, in a nutshell, changing the `TextEditingController`'s `text` should **NOT** trigger the `TextField.onChanged`, but in my case it triggers.

Here's my code, I have this inside a `StatefulWidget` in order to initiate a `TextField` with the user's email. As Firebase Auth uses a `Future` and we can't `await` inside `initState` I used `then`, which updates the `text` in a later time:

```dart
@override
  void initState() {
    super.initState();
    _auth = Provider.of<FirebaseAuth>(context, listen: false);
    _crashlytics = Provider.of<Crashlytics>(context, listen: false);

    _auth.currentUser().then((user) {
      _textController.value = TextEditingValue(
        text: user.email ?? '',
        selection: TextSelection(
          baseOffset: user.email?.length ?? 0,
          extentOffset: user.email?.length ?? 0,
        ),
        composing: TextRange.empty,
      );
      _isEmailValid = isEmailValid(user.email);
    });
  }
```

As soon as I update the `TextEditingController.value` my `TextField.onChanged` callback executes.

Not only that, but in my Android Pixel 2 AVD the callback is first called with an empty `String` then the actual email `String` and then a third time with an empty `String` again, **leaving a blank `TextField`**, defeating the purpose of all of this code. This doesn't happen on my phone, but I believe it's because my phone executes the Firebase Auth `Future` a lot quicker. I tried to simulate this with a `Future.value()` and `Future.delayed()` but couldn't reproduce it.

In any case, either the docs should be updated with the current behavior or the behavior should be fixed to match the docs.

**Comment by feinstein** [comment]
Now, if I follow the docs and do this instead:

```
_auth.currentUser().then((user) {
      _textController.value = TextEditingValue(
        text: user.email ?? '',
        selection: TextSelection(
          baseOffset: user.email?.length ?? 0,
          extentOffset: user.email?.length ?? 0,
        ),
        composing: TextRange.empty,
      );
    });

 _textController.addListener(() {
      bool isValid = isEmailValid(_textController.text);
      if (_isEmailValid != isValid) {
        setState(() { _isEmailValid = isValid; });
      }
    });
```

I get SEVERAL updates at the same time (I counted 11 updates), multiple with `_textController.text` being and empty `String` and multiple with it being the actual email, but the last one is the empty `String`. I am getting this behavior on both my phone and my Emulator, and this totally follows the docs, even on the update as it says:

> one should not also set [selection] in a separate statement. To change both the [text] and the [selection] change the controller's [value].

Which is exactly what I am doing.

With this code I can simulate the last update being an empty `String`, but its intermitent, most of the times it's not an empty `String`, but sometimes it is:

```
    Future.delayed(Duration(milliseconds: 200), ()=> 'a@a.com').then((email) {
      _textController.value = TextEditingValue(
        text: email ?? '',
        selection: TextSelection(
          baseOffset: email?.length ?? 0,
          extentOffset: email?.length ?? 0,
        ),
        composing: TextRange.empty,
      );
    });
```

**Comment by feinstein** [comment]
I fixed the intermittent behavior by surrounding the ` _textController.value` update with a `WidgetsBinding.instance.addPostFrameCallback((_)`. I think the first text updates from the first build were erasing the text update, without being able to predict this behavior, as this would be highly dependent on timing. 

But still the main issue remains, I get updates on my listener when I update the text, which goes against the docs.

**Comment by markusaksli-nc** [comment]
I can't reproduce this behavior on the latest master `1.22.0-10.0.pre.196`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.196, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.196 at C:\Development\flutter_master
    • Framework revision ea039ed3f9 (9 hours ago), 2020-09-15 17:57:04 -0400
    • Engine revision 1cabedf8ac
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var controller = TextEditingController(text: "init");

  @override
  void initState() {
    super.initState();
    setState(() {
      controller.value = TextEditingValue(
        text: "initState",
        selection: TextSelection.collapsed(offset: 0),
        composing: TextRange.empty,
      );
    });
    Timer(
      Duration(seconds: 5),
      () => setState(() => controller.value = TextEditingValue(
        text: "timer",
        selection: TextSelection.collapsed(offset: 1),
        composing: TextRange.collapsed(1),
      )),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: TextField(
            controller: controller,
            onChanged: (value) => print("onChanged($value)"),
          ),
        ),
      ),
    );
  }
}

```
</details>

Behavior seems to perfectly match

> This callback doesn't run when the TextField's text is changed programmatically, via the TextField's controller. Typically it isn't necessary to be notified of such changes, since they're initiated by the app itself.

@feinstein Could you check if you are still facing this issue and please provide a minimal reproducible code sample in that case?

**Comment by feinstein** [comment]
I also can't reproduce, but as I said before I was having a hard time reproducing it with `Future.delayed`. Since Firebase Auth changed it's API I can't simulate this again, so I think we can close this for now and if it happens again we reopen it.
