### ISSUE TITLE
Another Flutter 1.12 BUG - 

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#47190]
The webview_flutter: ^0.3.16 was working before but now it throws the exception Trying to embed a platform view but the PrerollContext does not support embedding. All the configurations are correct. Flutter 1.12 has been a real pain and extremely buggy. It is breaking a lot of code.

**Comment by iapicca** [comment]
Hi @azamsharp 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
