### ISSUE TITLE
Floating Snackbar has clipped shadow 

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#47202]
## Steps to Reproduce

1. Create app with floating snackbar, for example https://gist.github.com/perclasson/8fbb4e1fdbe171e22a052eae3a3a963d as can be displayed in [DartPad](https://dartpad.dartlang.org/8fbb4e1fdbe171e22a052eae3a3a963d)
2. See the clipped shadow for the floating snackbar.

Example screenshot:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-17 at 10 34 47](https://user-images.githubusercontent.com/1770678/70983397-f1bd2e80-20b8-11ea-899f-e85de11f8c74.png)

## Logs

*flutter doctor -v*
```
[✓] Flutter (Channel master, v1.10.1-pre.1255, on Mac OS X 10.14.6 18G103, locale en-DE)
    • Flutter version 1.10.1-pre.1255 at /Users/perc/development/flutter
    • Framework revision e863bf89fb (23 hours ago), 2019-12-16 11:59:43 +0100
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)


[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Connected device (5 available)
    • iPhone 11 Pro Max  • 787077DE-9BAA-449A-B911-80F95A3FCD2A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • iPad Pro (11-inch) • 37D79AA2-C702-4833-9823-09EB6D40EA52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • macOS              • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome             • chrome                               • web-javascript • Google Chrome 79.0.3945.79
    • Web Server         • web-server                           • web-javascript • Flutter Tools

```

**Comment by Zazo032** [comment]
I think this is related to https://github.com/flutter/flutter/issues/43716

**Comment by shihaohong** [comment]
Reopening for now since the fix was reverted

**Comment by shihaohong** [comment]
This is being blocked by internal test failures, and I'm not sure if I have a lot of time to fix them in the short term, so I'll have to stall on migrating for now.
