### ISSUE TITLE
Ios background wake up time error

### ISSUE THREAD

**Issue by fangwy** [flutter/flutter#47203]
When the app was killed by the system and opened again, there was a flash back.
FlutterObservatoryPublisher.mm(151)Could not register as server for FlutterObservatoryPublisher. Check your network settings and relaunch the application.

**Comment by iapicca** [comment]
Hi @fangwy 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by fangwy** [comment]
Hi,
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (not installed)
[✓] Connected device (1 available)


flutter run --verbose

[+1374 ms] flutter: scoket连接成功
[+4826 ms] flutter: lifeChanged AppLifecycleState.inactive
[ +455 ms] Updating files
[ +452 ms] flutter: lifeChanged AppLifecycleState.paused
[+5149 ms] DevFS: Sync finished
[        ] Syncing files to device “chaochao”的 iPhone... (completed in 13,314ms,
longer than expected)
[   +1 ms] Synced 3.2MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[  +11 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id:
_flutterView/0x104834c20, isolate: {type: @Isolate, fixedId: true, id:
isolates/2760024759416519, name: main.dart$main-2760024759416519, number:
2760024759416519}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0x104834c20.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart
(and rebuild
           state), press "R".
[   +1 ms] An Observatory debugger and profiler on “chaochao”的 iPhone is
available at:
           http://127.0.0.1:1024/SZps18kzkVs=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to
quit,
           press "q".
[+224877 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/6E597BF1-665B-41EF-B40C-
F7DFAC28D42C/tmp/xim_flutterUGzmoM/xim_flutter/)
[        ] Sending to VM service: _deleteDevFS({fsName: xim_flutter})
[ +265 ms] Ignored error while cleaning up DevFS: TimeoutException after
0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 314,732ms.

**Comment by kf6gpe** [comment]
@fangwy Does this happen with any app, or just yours? Can you provide a minimally reproducible case for us to test with?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by brooth** [comment]
**Additional information:** based on this article https://blog.csdn.net/gjm_123/article/details/103714034
this error occurs when you have a WebSocket connection open while you're app is in the background so when the system decided that this connection must be closed it sends 13 signal. If your app ignores this signal and continues to write in the socket - it fails. One workaround (thanks to the article author) - tell the system do not send this signal (or something like that), add these lines into your delegator (swift):

```swift
    override func applicationDidBecomeActive(_ application: UIApplication) {
        signal(SIGPIPE, SIG_IGN);
    }
    
    override func applicationWillEnterForeground(_ application: UIApplication) {
        signal(SIGPIPE, SIG_IGN);
    }

```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by pr-Mais** [comment]
> **Additional information:** based on this article https://blog.csdn.net/gjm_123/article/details/103714034
> this error occurs when you have a WebSocket connection open while you're app is in the background so when the system decided that this connection must be closed it sends 13 signal. If your app ignores it and continues to write to the socket - it fails. One workaround (thanks to the article author) - tell the system do not send this signal (or something like that), add these lines into your delegator (swift):
> 
> ```swift
>     override func applicationDidBecomeActive(_ application: UIApplication) {
>         signal(SIGPIPE, SIG_IGN);
>     }
>     
>     override func applicationWillEnterForeground(_ application: UIApplication) {
>         signal(SIGPIPE, SIG_IGN);
>     }
> ```

I've tried all possible solutions on GitHub to solve an issue I'm having with background fcm notifications and this was the solution that worked for me, thank you!
