### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024/eiemy-q0vh0=/

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#47204]
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024/eiemy-q0vh0=/

After upgrade to lastes Flutter version.
Flutter always show this error after install and launching.
it currently not working and i can not continue to develop at present.

## Steps to Reproduce

After upgrade to lastes Flutter version.
Flutter always show this error after install and launching.
it currently not working and i can not continue to develop at present.

```sh
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                          14.1s
 └─Compiling, linking and signing...                        10.2s
Xcode build done.                                           39.2s
Installing and launching...                                        29.2s
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1025/jFpDvAxfurw=/
```

**Target Platform:**
**Target OS version/browser:**
**Devices:**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans)
    • Flutter version 1.12.13+hotfix.5 at /Users/virs/flutter
    • Framework revision 27321ebbad (6 天前), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/virs/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • “wei zhang”的 iPhone • 029252aa59e25c34188ac565344af93858a917b1 • ios • iOS 13.1.3

! Doctor found issues in 1 category.
```

**Comment by virskor** [comment]
tried restart system, and reinstall Flutter

**Comment by virskor** [comment]
i am not using proxy or vpn

**Comment by virskor** [comment]
repeat it after switch to master channel enable macOS development.

**Comment by iapicca** [comment]
Hi @virskor 
are you experiencing this issue with `stable` or `master` channel (or both)?
Are you located in China?

**Comment by virskor** [comment]
@iapicca yes, i am in China. i found this problem still existing, and i just reopen this issue. these problem exits on both stable/master channel. Thanks

**Comment by virskor** [comment]
i just upgrade to 1.12.13(hotfix5) but this problem still trouble me.

**Comment by anisalibegic** [comment]
Having the same problem.

`Error connecting to the service protocol: failed to connect to http://127.0.0.1:50365/UGuZ7dchAl0=/
`

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale bs-Latn-BA)
    • Flutter version 1.12.13+hotfix.5 at C:\Programs\Flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Anis\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • ANE LX1 • 9WV4C19131006232 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by FroseMan97** [comment]
same. stable, Russia

**Comment by snadon** [comment]
Same, stable, Canada.

**Comment by FroseMan97** [comment]
I forgot to connect the ios application in firebase and add google json in runner)

**Comment by virskor** [comment]
It works fine when you are using flutter run --release. But using flutter run will lose connection when process to installing and launching step. And this problem seems not frequently happens on wired connection. Try to open connection via network on xcode,This problem comes to trouble. But connections works well on Xcode. And flutter run --release also work well via network connection

**Comment by clementhk** [comment]
Same, Hong Kong and Oslo.

**Comment by AlissouJunior** [comment]
Finally what can i do. Because i have same problem

**Comment by Xgamefactory** [comment]
same here on stable latest.

**Comment by zanderso** [comment]
For those experiencing this issue, please post full logs from `flutter run --verbose` in a [gist](https://gist.github.com/). Thanks!

**Comment by averyvery** [comment]
I just ran into this tonight after working with Flutter for a week. Was working on a new app and trying to run on my USB-connected iOS device, but this issue began — trying to rerun older apps (ones I'd been able to run yesterday) also failed with the same error. 

- I'm on a mac, OS version 10.15.1
- Restarting my computer doesn't seem to have an effect. 
- I've attempted to run the same app on the iOS Simulator, an Android Emulator, and a USB-connected iOS device. So far, **the USB-connected iOS device is the only one affected by this issue.**
- I haven't tried uninstalling/reinstalling Flutter yet, or switching to a different version.

I've pasted my flutter doctor and flutter run output here: https://gist.github.com/averyvery/173ac2df50449cb2356ed91165da7140

The final lines are: 

```
[+1008 ms] Forwarded port ForwardedPort HOST:1026 to DEVICE:50123
[   +5 ms] Installing and launching... (completed in 25.2s)
[   +7 ms] Connecting to service protocol: http://127.0.0.1:1026/LWSLWJ2x_Ds=/
[ +126 ms] Fail to connect to service protocol: http://127.0.0.1:1026/LWSLWJ2x_Ds=/: HttpException: , uri = http://127.0.0.1:1026/LWSLWJ2x_Ds=/ws
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1026/LWSLWJ2x_Ds=/
[   +2 ms] "flutter run" took 53,306ms.
```

**Comment by averyvery** [comment]
After some googling, I was able to resolve by going into Xcode:

- Go to Window > Devices and Simulators
- Uncheck "Connect via network"

Apologies if this is unrelated, or is a known issue. I got the solution from https://github.com/flutter/flutter/issues/13747#issuecomment-369322275

**Comment by beingentangled** [comment]
I'm having the same issue @zanderso please refer to my error here
https://gist.github.com/beingentangled/2ac66cceb429e408763c6e8b3be77631

**Comment by vysotsky** [comment]
I've got the same issue. And the weirdest thing is that downgrading is not helping at all.

**Comment by vysotsky** [comment]
Here is the log including the error:

`+1006 ms] Forwarded port ForwardedPort HOST:1024 to DEVICE:49395
[   +4 ms] Installing and launching... (completed in 25.8s)
[  +10 ms] Connecting to service protocol: http://127.0.0.1:1024/VbX8F-ZI1YQ=/
[  +46 ms] Fail to connect to service protocol: http://127.0.0.1:1024/VbX8F-ZI1YQ=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/VbX8F-ZI1YQ=/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024/VbX8F-ZI1YQ=/
[   +2 ms] "flutter run" took 66,348ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/user/Library/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

`

**Comment by jallynme** [comment]
I got this too

**Comment by Xgamefactory** [comment]
my error was disappeared after some edits. still not sure what was the fix.
you can try to edit android/build.gradle especially dowgrading your gradle version.
also i have removed preferences package from pubspec it is using old version of shared_preferences.
my versions.

 ```
classpath 'com.android.tools.build:gradle:3.3.2'
  classpath 'com.google.gms:google-services:4.3.3'
```

**Comment by ortizen** [comment]
I am having this issue, followed these proposed solutions but didn't fix the issue:

- Downgrading from SDK 29 to 28
- Flutter clean
- Use a physical device.

The weirdest thing is that if I use an IOS emulator, it works fine, the issue only affects an android device (virtual or physical)

Here is the android gist (Have the error):

- https://gist.github.com/ortizen/c8d17f85034252ecd3728393cd746665

And the IOS run (Runs OK)

- https://gist.github.com/ortizen/d08ec9ab64c0f4feeddb1e731a1cbc29

I am suing macOs Catalina 10.15.2 and Android Studio 3.5.3

**Comment by beingentangled** [comment]
How many with this problem using this package?
dependencies:
  flutter_clean_architecture: ^2.0.1

**Comment by iKK001** [comment]
Same issue here under iOS ? (iOS10.15.2) Any solution yet ?

**Comment by beingentangled** [comment]
> Same issue here under iOS ? (iOS10.15.2, Xcode11.3, Flutterv1.12.13+hotfix.5) Any solution yet ?

is it working in Android for you?

**Comment by beingentangled** [comment]
I've got a solution to my problem. 

Please check the following: 
If the app has any permissions, make sure to give it in both Android Manifest and Info.plist.
In my case, I was requesting a location at the start of the application whose permission was not defined for IOS in Info.plist which when requested at the starting will result in a crash and will not allow to connect the observatory throwing the error:

### Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024

Please make sure to give the necessary permissions in both IOS and Android. 
Thanks.

**Comment by HaoCherHong** [comment]
resolved by disabling personal hotspot on device

**Comment by DerSIlent** [comment]
I copied all my plugins to a new project and narrowed it down to flutter_facebook_plugin giving the error, once removed it started to run on device again. Hope this helps!

**Comment by ortizen** [comment]
> I copied all my plugins to a new project and narrowed it down to flutter_facebook_plugin giving the error, once removed it started to run on device again. Hope this helps!
Yeap, I tried @DerSIlent  solution to nuke facebook plug in and solve the problem.

**Comment by bastibense** [comment]
I had the same issue (iOS on iPad).For me it seems that it had to do with DNS settings (I had 8.8.8.8 set up as my DNS, overriding my router's default DHCP settings).

After setting DNS in system settings it to "Automatic" apparently solved the problem for me.

**Comment by AnoRebel** [comment]
Also had the same issue, solved it by removing the package barcode_scan

**Comment by 30in2020** [comment]
I also had the same issue, and solved it by using **FlutterActivity** instead of **FlutterFragmentActivity**.

**Comment by iKK001** [comment]
I finally found that `flutter upgrade` and a `flutter clean` did help.

**Comment by gabrielnemeth** [comment]
For me it was wrongly configured facebook login. Precisely missing string.xml and AndroidManifest.xml data:

\/android/app/src/main/res/values/strings.xml

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Your App Name here.</string>

    
    <string name="facebook_app_id">000000000000</string>

    
    <string name="fb_login_protocol_scheme">fb000000000000</string>
</resources>`

\/android/app/src/main/AndroidManifest.xml
`
<meta-data android:name="com.facebook.sdk.ApplicationId"
    android:value="@string/facebook_app_id"/>

<activity android:name="com.facebook.FacebookActivity"
    android:configChanges=
            "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
    android:label="@string/app_name" />

<activity
    android:name="com.facebook.CustomTabActivity"
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="@string/fb_login_protocol_scheme" />
    </intent-filter>
</activity>
`

**Comment by mdrideout** [comment]
I was having this issue. I uninstalled the app from my device, opened the project in xcode, ran some build cleaning thing that appeared in the yellow triangle warning area, then built the app via xcode. Then uninstalled the app from device again. Then ran via android studio and it worked.

**Comment by iKK001** [comment]
Incredible, @mdrideout, your workaround helped indeed ! The cleaning in Xcode and uninstall/install trick did help. Thank you very much.

**Comment by luckymehndiratta** [comment]
Error connecting to the service protocol: failed to connect to http://127.0.0.1:65426/FiX7i0GaT6Y=/
Same issue 
channel stable and location india

**Comment by senk** [comment]
Same here, worked once after that service protocol error, Cambodia, Stable

**Comment by ChristBKK** [comment]
> I copied all my plugins to a new project and narrowed it down to flutter_facebook_plugin giving the error, once removed it started to run on device again. Hope this helps!

this one worked. Crazy.

**Comment by GilDev** [comment]
Same problem here, using adb connected over WiFi.

**Comment by DerSIlent** [comment]
I would also like to mention that I got the same error when I had the emulator turned off. It started working again when I clicked the power button on the side of emulator.

**Comment by blasten** [comment]
I was able to reproduce this issue by using an emulator running Android 10.

**Comment by blasten** [comment]
```
[        ] Forwarded host port 61900 to device port 38717 for Observatory
[  +18 ms] Connecting to service protocol: http://127.0.0.1:61900/Zjn5H-sLOgo=/
[  +98 ms] Fail to connect to service protocol: http://127.0.0.1:61900/Zjn5H-sLOgo=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:61900/Zjn5H-sLOgo=/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:61900/Zjn5H-sLOgo=/
[   +5 ms] "flutter run" took 4,699ms.
```

**Comment by blasten** [comment]
Duplicate of https://github.com/flutter/flutter/issues/33050

**Comment by blasten** [comment]
I was able to fix the issue by updating system image to revision 8. This can be done by going to Preferences -> System Settings -> Android SDK -> SDK Platforms.

<img width="741"  src="https://user-images.githubusercontent.com/1410613/71948716-c55f7400-3185-11ea-86fa-ae3dc6d83781.png">

If you hitting this issue, it's likely that you are using an older system image and facing  https://issuetracker.google.com/issues/132325318. Please provide more details otherwise.

**Comment by blasten** [comment]
I'm closing this issue since the solution is to update the system image. Please reopen and provide more details if you experiment the same issue.

**Comment by indigothm** [comment]
> I'm closing this issue since the solution is to update the system image. Please reopen and provide more details if you experiment the same issue.

That wouldn't solve it on iOS though.

**Comment by zanderso** [comment]
@indigothm This scope of this issue has crept a bit. I think we should leave this one closed, and if folks are still seeing this, please open new separate Android and/or iOS issues. Thanks!

**Comment by DjangoOverloard** [comment]
I do have the same problem on IOS, not sure if it's related to changes in any of my plugins. However, I can run app perfectly from Xcode, with all the logs being available.

**Comment by vguardiola** [comment]
I had the same issue, I remove the flutter_facebook_login from my pubspec and the app works fine.

Regards
