### ISSUE TITLE
device_info & hotreload

### ISSUE THREAD

**Issue by blondie63** [flutter/flutter#47206]
Testing device_info plugin i've an issue during debug with VS.STUDIO and Hot Reload
This is the error:
<img width="1079" alt="fl-deviceInfo-hotreload" src="https://user-images.githubusercontent.com/1261851/70988665-8b3d0e00-20c2-11ea-9092-6d66b70bafba.png">

I'm using Flutter SDK 1.12.13+hotfix.5 , Dart 2.7.0 , Device_Info 0.4.1+4
Some Help ?

**Comment by iapicca** [comment]
Hi ... 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by blondie63** [comment]
Thanks!
