### ISSUE TITLE
App crashes on when added to existing project with error message Could not load NIB in bundle 'LaunchScreen'

### ISSUE THREAD

**Issue by Sadmansamee** [flutter/flutter#47205]
## Steps to Reproduce

1. Added Flutter Module to Existing project
2. Try to start **FlutterViewController** from a viewcontroller
3. It crashes with the message 

> 'Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/FCBA8347-38FE-4ED1-83ED-E60ED5177593/MeTonic.app> (loaded)' with name 'LaunchScreen'

**Target Platform:** iOS
**Target OS version/browser:** iOS 13
**Devices:** iPhone 7, XR

## Logs

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/2E0B47A4-5DF8-4423-A436-E1E66B6AFCAF/MeTonic.app> (loaded)' with name 'LaunchScreen''
```

```
No issues found! (ran in 2.9s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132,
    locale en-US)
    • Flutter version 1.12.13+hotfix.5 at
      /usr/local/Caskroom/flutter/1.2.1/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sadmansamee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.1.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Tonic’s iPhone (2) • 00008020-0018143C1104003A                • ios • iOS
      13.1.3
    • sadman’s iPad      • 3cf92e6646238b525672a76447116509cc8506f1 • ios • iOS
      13.2.3

• No issues found!
```

**Comment by dev-shanghai** [comment]
Can you share more details.

**Comment by Sadmansamee** [comment]
Flutter added to the existing iOS project and added with Cocoapod. and trying to open ViewContontoller with 
```
func showFlutter() {
 let flutterViewController = FlutterViewController(project: nil, nibName: nil, bundle: nil)
 present(flutterViewController, animated: true, completion: nil)
}
```

**Comment by iapicca** [comment]
Hi @Sadmansamee 
can you please provide your `flutter run --verbose`?
Thank you

**Comment by Sadmansamee** [comment]
I have added to another iOS project with [Add-to-app](https://flutter.dev/docs/development/add-to-app/ios/project-setup), so I don't think I can do that.

**Comment by iapicca** [comment]
Hi  @Sadmansamee 
my bad , can you provide the logs for the crash?
thank you

**Comment by Sadmansamee** [comment]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/2E0B47A4-5DF8-4423-A436-E1E66B6AFCAF/MeTonic.app> (loaded)' with name 'LaunchScreen''

**Comment by xster** [comment]
Perhaps something in https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L369 wasn't defensive enough. I suspect we might be able to reproduce this by deleting the launchscreen storyboard from the outer host project. 

@dnfield might have thoughts

**Comment by dnfield** [comment]
I don't suppose you get a backtrace when debugging?

**Comment by jmagman** [comment]
>  I suspect we might be able to reproduce this by deleting the launchscreen storyboard from the outer host project.

I just tried this by renaming LaunchScreen to something else, and updating UILaunchStoryboardName and it worked.  I've also embedded a module into a host app that was using UIMainStoryboardFile instead with no UILaunchStoryboardName and that also worked.

Can we get your host app Info.plist?  Did you change the name of your launch storyboard?  If so, did you update the UILaunchStoryboardName ("Launch screen interface file base name") value?https://developer.apple.com/documentation/bundleresources/information_property_list/uilaunchstoryboardname

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
