### ISSUE TITLE
Because flutter_david depends on package_info >=0.4.0+13 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by DavidMGT** [flutter/flutter#47219]
how ?

**Comment by Zazo032** [comment]
Run `flutter upgrade`

**Comment by iapicca** [comment]
Hi @DavidMGT 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
