### ISSUE TITLE
Flutter crash with platformview

### ISSUE THREAD

**Issue by PingShen** [flutter/flutter#47211]
## Steps to Reproduce
the online user crash, we did not reproduce this crash.

``bash
java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
	at android.view.View.populateVirtualStructure(View.java:8575)
	at android.view.View.populateVirtualStructure(View.java:8656)
	at android.view.View.populateVirtualStructure(View.java:8656)
	at android.view.View.populateVirtualStructure(View.java:8656)
	at android.view.View.populateVirtualStructure(View.java:8656)
	at android.view.View.onProvideVirtualStructureCompat(View.java:8074)
	at android.view.View.onProvideVirtualStructure(View.java:8055)
	at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8723)
	at android.view.View.dispatchProvideStructure(View.java:8670)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
	at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3794)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Target Platform:**Android
**Target OS version/browser:**9.0
**Devices:** HUAWEI LYA-AL00

## Logs

```
[✓] Flutter (Channel unknown, v1.5.4-hotfix.103, on Mac OS X 10.13.4 17E199,
    locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.103 at /Users/user/.flutter_sdk
    • Framework revision db82f03d3c (3 months ago), 2019-09-19 11:42:43 +0800
    • Engine revision 7b47fb4f2a
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shenzhixinmac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/shenzhixinmac/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • VOG AL00 • MQS0219926012523 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by PingShen** [comment]
just one device so far

**Comment by iapicca** [comment]
Hi @PingShen 
I understand that it is a device specific issue,
although more information are needed to make the issue reproducible;
are you experiencing the issue with the latest stable version?
Can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by PingShen** [comment]
@iapicca I see the same issue in 
https://github.com/flutter/flutter/issues/33643
https://github.com/flutter/flutter/issues/32984

And we can not reproduce this crash,just crash online


flutter doctor -v
[✓] Flutter (Channel unknown, v1.5.4-hotfix.103, on Mac OS X 10.13.4 17E199,
    locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.103 at /Users/user/.flutter_sdk
    • Framework revision db82f03d3c (3 months ago), 2019-09-19 11:42:43 +0800
    • Engine revision 7b47fb4f2a
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shenzhixinmac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/shenzhixinmac/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • VOG AL00 • MQS0219926012523 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @PingShen 
thank you for pointing out the duplicate,
I'm closing the current one, please follow up on the issue you indicated
Thank you
