### ISSUE TITLE
[Web] please add classes for widgets instead of "style" attribute - so it will be easier to catch element via automation testing tools

### ISSUE THREAD

**Issue by ZipovUA** [flutter/flutter#47217]
Hi guys.

Flutter is an interesting thing, but it's really hard to work from the QA Automation perspective with generated HTML layout as it's hard to generate locator for automation scripts which will interact with web-app as human do.

Here is an example, I can catch element by text only that's problematic as:
 - text can be changed
 - the app can have a lot of localizations in different languages - then locators should support every language representation for the current element
 - CSS selectors can not search by text

![image](https://user-images.githubusercontent.com/5374149/71007837-534cbf80-20f0-11ea-9fa5-c62946324228.png)

So the proposal is to improve Flutter2Web functionality - so when web app will be created - the system will not just generate some styles, but create classes with those styles and class name will be equal to widget name + property name - so it will be easier to find elements via selenium webdriver or similar web interaction tool

![image](https://user-images.githubusercontent.com/5374149/71009474-f56da700-20f2-11ea-93d0-dc117877d158.png)

So, in fact, it's not possible to get an element from the page if you do not know the current text or it does not have some text
![image](https://user-images.githubusercontent.com/5374149/71009664-4382aa80-20f3-11ea-85d9-558ec57dbb92.png)

**Comment by iapicca** [comment]
Hi @ZipovUA 
the changes you are proposing seems to be addressed to [flutter2web](https://pub.dev/packages/flutter2web) which is a 3rd party package, 
you may want to propose the changes to said package owner.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ZipovUA** [comment]
I am sorry, but I thought that Flutter for web has official support by flutter developers
https://flutter.dev/web

**Comment by ZipovUA** [comment]
And according to flutter2web documentation, this library is not for generating web resources for a flutter, but just for publishing generated resources on the server
![image](https://user-images.githubusercontent.com/5374149/71088816-117f5000-21a8-11ea-821b-209a45c30a00.png)

As I understand improvement that I propose to do related to part that I marked by orange collor
"flutter build web"

**Comment by iapicca** [comment]
Hi @ZipovUA 
in the previous post you referred to `flutter2web`,
if yours is a proposal for the framework itself
do you think this [issue](https://github.com/flutter/flutter/issues/46596) is compatible with yours?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
