### ISSUE TITLE
Failed to archive for submission on Xcode

### ISSUE THREAD

**Issue by johnsonyick** [flutter/flutter#47227]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/48547622/71016280-e8bb7400-212f-11ea-99f0-8e603f61a770.png)

1. having tried many times of searching stackoverflow and flutter forum, there's no similar case happened
2. ...
3. ...

**Target Platform:** iOS
**Target OS version/browser:** iOS 9.0+
**Devices:** Generic iOS Device

## Logs

```
flutter run did successfully make the app on simulator and connected iPhone XS
```

```
No issues found! (ran in 27.0s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/johnson/Downloads/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/johnson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @johnsonyick 
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by johnsonyick** [comment]
Here comes flutter run --verbose , (because it's quite large, it's attached as txt file)
[flutter-run.log](https://github.com/flutter/flutter/files/3978882/flutter-run.log)


also, attached part of my codes and pubspec.yaml
[Archive.zip](https://github.com/flutter/flutter/files/3978433/Archive.zip)

**Comment by johnsonyick** [comment]
steps i did
1. flutter run on simulator (successful)
2. flutter build ios for xcode (successful)
3. try making IPA file by Product -> Archive (failed)
4. error shown as attached at the first message

**Comment by johnsonyick** [comment]
hi There,

can anyone help on my issue?
