### ISSUE TITLE
Golden Test Failure output doesn't support golden files in nested directories

### ISSUE THREAD

**Issue by coreysprague** [flutter/flutter#47228]
Steps to Reproduce

Write a test that uses the matchesGoldenFile(fileName) assertion, and specify a filename with a nested sub-directory.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('Golden Failure Output Bug', () {
    testWidgets('blue container', (tester) async {
      await tester.pumpWidget(Container(color: Colors.blue));
      await expect(find.byType(Container), matchesGoldenFile('subdir/blue_container.png'));
    });

    testWidgets('red container', (tester) async {
      await tester.pumpWidget(Container(color: Colors.red));
      await expect(find.byType(Container), matchesGoldenFile('subdir/red_container.png'));
    });
  });
}
```

When you generate goldens, the appropriate reference images are generated. However, if the widget under test changes and the goldens fail, the failure images are inappropriately generated.

In this case, both tests will compute to the same file name and override each other:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/5420324/71016373-ed3d4980-20a9-11ea-905c-139c3865f143.png">

The issue is that the code for generating the failure file name naively assumes that the image is not in a directory. Line 156

Here is a screenshot of the debugger from my actual use case
![image](https://user-images.githubusercontent.com/5420324/71016457-080fbe00-20aa-11ea-9cbc-21e29aaf25f0.png)

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/<redacted>/Library/Code/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/<redacted>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/<redacted>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • B3D5F663-0ED7-4880-8552-4A0D186F7F50 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by Piinks** [comment]
Hey @coreysprague thanks for filing this!

The naming issue is an easy fix. Beyond that, I am curious, would you expect the `failures` directory of image diffs to be generated in the subdirectory as well?

For example:
My base directory is `tests`, which contains `tests.dart`, and I have a golden master image in `tests/goldens1`.
When comparison of `tests/goldens1/golden1.png` fails, would you expect 

- `tests/goldens1/failures`
- or
- `tests/failures`

for the location of the output? Right now the implementation assumes that golden files may be contained within many subdirectories, and therefore provides all output in one directory where the actual test is. (Aside from the naming issue of course).

**Comment by coreysprague** [comment]
Tests/Failures seems good to me, but I don’t have a strong preference either way. Thanks!

**Comment by Piinks** [comment]
Thanks for the feedback and again for bringing this to our attention! The fix should land soon.
