### ISSUE TITLE
SelectableText can't be copied on web

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#47234]
When using a `SelectableText` widget on the web, the selection is visible but is not completely functional. For example, if the user clicks `ctrl+c` the text isn't copied.

This is created as follow up on conversation here: https://github.com/flutter/flutter/issues/32246

The same issue also applies to read only text fields (see: https://github.com/flutter/flutter/issues/51184).

**Comment by devxpy** [comment]
The right click menu isn't quite right either.
Flutter text:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/19492893/72524498-122f0300-3888-11ea-812c-0d0f9df5b971.png">

HTML text:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/19492893/72524552-28d55a00-3888-11ea-96c2-8caf30a32195.png">

**Comment by kunit1** [comment]
Just wanted to also point out that the same issue exists for the canvas kit back-end.

**Comment by kunit1** [comment]
Another case that is not working is the ability to select text in a body of text that has a `\n` 
The selection will stop at the last character before the `\n`

This works in the CanvasKit backend but is broken in the html backend

**Comment by lodestar-sr** [comment]
SelectableText does not work for copying with CTRL + C in the web and Windows, Mac builds.
This is actually a general process for users to copy text with CTRL+C. 
How can I make copying texts in the SelectableText field?

**Comment by ja2375** [comment]
This feature is a must. Any updates?

**Comment by lodestar-sr** [comment]
@rvp-diconium It seems you have the solution for copying selected text in Desktop builds.
Would you prove it here, please?

**Comment by lodestar-sr** [comment]
@stuartmorgan Would you please provide the solution to copy selected text in SelectableText widget with CTRL(Mac) + C on the Desktop version builds?

**Comment by kunit1** [comment]
Let's please avoid spamming the comments on this issue. There is a [PR here](https://github.com/flutter/flutter/pull/55419) that could potentially solve this issue. Maybe @slightfoot can give us an update on the status.
