### ISSUE TITLE
Start running tests with --test-randomize-ordering-seed=random

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47233]
We should shuffle our tests.  I've encountered a number of test files that depend on state set by previous tests.  This ends up hiding bugs and/or creating unnecessary breaking changes later on when we have to fix it.

Package test takes an argument `--test-randomize-ordering-seed=random`.  For regular test runs this looks like `pub run test --test-randomize-ordering-seed=random`.  For `flutter test` we'll have to create a way to pipe in the argument.  In general, we'll want to update `dev/bots/test.dart` to use this argument by default when running tests for CI.

/cc @jonahwilliams @goderbauer @tvolkert @Hixie @yjbanov @zanderso - I would not be surprised if this surfaces various breaking changes in tool/flutter/etc.

**Comment by goderbauer** [comment]
Have you tried running it with that a couple of times just for fun to see what would be breaking?

**Comment by zanderso** [comment]
Could you clarify in the description what that flag gets passed to?

**Comment by dnfield** [comment]
The flag is passed to `package:test`.  We'll need to pipe it in for `flutter test` as well, but we could probably do it pretty easily with the tool tests.

I haven't tried running it yet.  I know for sure it would mess some things up on for Flutter until https://github.com/flutter/flutter/pull/47177 is merged.

**Comment by dnfield** [comment]
Bumping the milestone as this has turned into a large effort.

**Comment by Hixie** [comment]
I recommend using the git hash as the seed, by the way, so that reproducing the failures is easy. Otherwise we're intentionally introducing randomness which will just manifest as flakiness.

**Comment by dnfield** [comment]
The pr number might be safer since this has to be a 32 bit integer.

**Comment by Hixie** [comment]
there might not be a PR (e.g. consider a local branch). Turning a git hash into a 32bit number is easy though, just chop off all but the first 32 bits. :-)

**Comment by dnfield** [comment]
Removing assignment and milestone for this. I came pretty close to landing this at one point, but it's a pretty tough moving target to hit, since new tess kept getting added that would break randomizability constraints.

There are some ways that we should be able to do this - e.g. automatically detecting a flake related to randomization by rerunning without randomization if failure occurs, but I have some higher priority work at the moment and don't expect to be able to get to it soon.
