### ISSUE TITLE
Apple rejected: Performance - Accurate Metadata (UIRequiredDeviceCapabilities)

### ISSUE THREAD

**Issue by neumartin** [flutter/flutter#47251]
Hi!
I can't publish my app in the Apple Store.
After try any possible combination in UIRequiredDeviceCapabilities key inside Info.plist I havn't any clue what's wrong.

Apple says:

```console
Guideline 2.3 - Performance - Accurate Metadata


We were unable to install the app on iPhone and iPad￼. The UIRequiredDeviceCapabilities key in the Info.plist is set in such a way that the app will not install on an iPhone and iPad￼ .

Next Steps

To resolve this issue, please check the UIRequiredDeviceCapabilities key to verify that it contains only the attributes required for your app features or the attributes that must not be present on the device. Attributes specified by a dictionary should be set to true if they are required and false if they must not be present on the device.

Resources

Please review the Technical Q&A 1397: Understanding the UIRequiredDeviceCapabilities key for information on the UIRequiredDeviceCapabilities key.

You may also wish to review the dictionary keys table in the "Declaring the Required Device Capabilities" section of the App Programming Guide for iOS.
```

My setup configuration is:

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-AR)
    • Flutter version 1.12.13+hotfix.5 at /Users/martinneu/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1
```

**If you want to see the code, you can clone it: 
https://gitlab.com/mneu/radioparquepatricios**

Thanks!!

**Comment by jonahwilliams** [comment]
The response apple sent you already contains instructions for what you need to do, see https://forums.developer.apple.com/thread/98481

**Comment by deakjahn** [comment]
I wouldn't say the Apple response answered anything. I've just have two Flutter apps, neither uses any hardware capability whatsoever. Neither has any `UIRequiredDeviceCapabilities` in the plist at all. One accepted, one rejected with that message.

**Comment by neumartin** [comment]
I finally create a new app and manually copy my code files, and works.

**Comment by deakjahn** [comment]
I also managed in the end, but the wording was far from clear. :-) It seems that if you have restrictions on what iOS version you support, the `plist` generated by Flutter isn't necessarily and automatically correct. I only had problems with the app that supports iOS from version 11. In those cases, yes, you (may?) have to manually fix the `Info.plist`.

**Comment by octavian-h** [comment]
Hi @deakjahn what exactly do you changed in the defulat Info.plist file. I also created an app with Flutter, but there is no UIRequiredDeviceCapabilities  in Info.plist. My minimum iOS version in Podfile and Xcode is 10. Any suggestions?

**Comment by deakjahn** [comment]
Dear me, that was half a year ago, who knows any more. :-)) Let me see...

Xcode shows verbose names in the Info.plist editor, _Required device capabilities_. This is set to `armv7` in my case. Deployment info in the Runner Project window is iOS 9.0. This is OK in my case. If you need later than that, you might need different settings all right but I don't know that. I had no reason to go any higher than 9.0.

**Comment by octavian-h** [comment]
Flutter did not add `UIRequiredDeviceCapabilities` in Info.plist file, but after I added this config with `armv7` the app was accepted. What is interesting is that the second app (similar with the first but without AdMob library) was acccepted with no value for `UIRequiredDeviceCapabilities`. I hope this will help others that publish a free/paid version of the Flutter app.
