### ISSUE TITLE
[cocoon] Failed to refresh LUCI status

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#47250]
Commit [86982e](https://chromium.googlesource.com/external/github.com/flutter/flutter/+/86982e195ec9f2ac48eb7ed75c5fec8d86fd84cb) was [failed](https://ci.chromium.org/p/flutter/builders/prod/Linux/10652) on LUCI, but succeed after a [rerun](https://ci.chromium.org/p/flutter/builders/prod/Linux/10653).

Cocoon [refresh_chromebot_status](https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_chromebot_status.dart) was supposed to update the task status from failed to success, but it didn't, hence the bug.

**Comment by keyonghan** [comment]
Fixed.
