### ISSUE TITLE
Flutter Command can't run in VS Code

### ISSUE THREAD

**Issue by acmilanistie** [flutter/flutter#47268]
after updating the flutter, I cannot run commands from VS Code but when running at the command prompt can be run information please
![image](https://user-images.githubusercontent.com/26074749/71050278-59d24a00-2177-11ea-946b-dd6e4b1d03c5.png)

**Comment by phymo** [comment]
it seems you are using bash? try cmd or power shell.

**Comment by acmilanistie** [comment]
above using cmd
below using the vscode terminal

**Comment by phymo** [comment]
https://stackoverflow.com/questions/50652071/flutter-command-not-found
refer to this.
or you can change your vscode terminal from bash to cmd or powershell.

**Comment by acmilanistie** [comment]
ok i ll try

**Comment by iapicca** [comment]
Hi @acmilanistie
did you update your [path](https://flutter.dev/docs/get-started/install/windows#update-your-path)?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by Ghayyas** [comment]
@VladyslavBondarenko I'm getting same issue. Im using Ubuntu linux

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Ghayyas** [comment]
My issue is fixed, I just configure path of flutter.
