### ISSUE TITLE
xcodebuild: error: Scheme Runner is not currently configured for the build action.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#47261]
Seeing uptick in this crash:
```
ProcessException: Process exited abnormally:
xcodebuild: error: Scheme Runner is not currently configured for the build action.
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=<>/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=<>/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```
  | at RunResult.throwException | (process.dart:141 )
-- | -- | --
  | at _DefaultProcessUtils.run | (process.dart:339 )
  | at <asynchronous gap> | (async )
  | at buildXcodeProject | (mac.dart:503 )

**Comment by jmagman** [comment]
Other reports:
@dheeraj2dj https://github.com/flutter/flutter/issues/39821
@kumarpalsinh25  https://github.com/flutter/flutter/issues/39821#issuecomment-565794339

**Comment by jmagman** [comment]
@kumarpalsinh25

1. What's the output of:
```shell
/usr/bin/env xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

2. What happens when you build it from Xcode?
```shell
$ open /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/ios/Runner.xcworkspace
```
Product > Build.

**Comment by jmagman** [comment]
Also:
```shell
cd /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/ios
xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace
```

**Comment by kumarpalsinh25** [comment]
@jmagman 

1) cd /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/ios
/usr/bin/env xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

**OUTPUT**
Build settings from command line:
    ARCHS = x86_64
    BUILD_DIR = /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios
    COMPILER_INDEX_STORE_ENABLE = NO
    FLUTTER_SUPPRESS_ANALYTICS = true
    SDKROOT = iphonesimulator13.2

2) open /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/ios/Runner.xcworkspace
**OUTPUT**
- I'm able to run app from Xcode. Issue is only when I try to run app  (On iOS simulator only) from Android Studio.

3) cd /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/ios
xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -list

**OUTPUT**
Information about workspace "Runner":
    Schemes:
        abseil
        BoringSSL-GRPC
        cloud_firestore
        Firebase
        firebase_auth
        firebase_auth_web
        firebase_core
        firebase_core_web
        firebase_storage
        FirebaseAnalytics
        FirebaseAuth
        FirebaseAuthInterop
        FirebaseCore
        FirebaseCoreDiagnostics
        FirebaseCoreDiagnosticsInterop
        FirebaseFirestore
        FirebaseInstanceID
        FirebaseStorage
        Flutter
        flutter_email_sender
        FMDB
        GoogleAppMeasurement
        GoogleDataTransport
        GoogleDataTransportCCTSupport
        GoogleUtilities
        gRPC-C++
        gRPC-C++-gRPCCertificates-Cpp
        gRPC-Core
        GTMSessionFetcher
        image_picker
        leveldb-library
        nanopb
        path_provider
        Pods-Runner
        Runner
        Runner 1
        shared_preferences
        shared_preferences_macos
        shared_preferences_web
        sqflite
        url_launcher
        url_launcher_macos
        url_launcher_web

**Comment by jmagman** [comment]
@kumarpalsinh25
1. Open ios/Runner.xcworkspace, choose Runner
1. Product > Scheme > Managed Schemes
1. Select Runner > Edit...

- In the Build tab are any Targets selected? 
- Do you see this little checkmark?

<img width="1072" alt="Screen Shot 2019-12-18 at 12 33 53 PM" src="https://user-images.githubusercontent.com/682784/71121163-c7d83a80-2192-11ea-9581-682a70eecd83.png">

- Where did "Runner 1" scheme come from?  What about all the plugins ones? 
```
Runner
Runner 1
```
- Did you go into Manage Schemes and Autocreate Schemes Now?

**Comment by kumarpalsinh25** [comment]
Hello @jmagman ,

Found the solution. Actually there was an issue from Xcode Runner Configuration. There were two build profiles as **Runner** and **Runner 1**.

**Runner** profile was not configured properly and it was used by VS Code and Android Studion that why I was facing problems on running iOS build.

**Runner1** profile was as default in Xcode so that there was no problem on a running project on iOS via Xcode.

Thanks for all your help! I really appreciate your efforts!

**Comment by jmagman** [comment]
Closing.

> **Runner1** profile was as default in Xcode so that there was no problem on a running project on iOS via Xcode.

Did you add this manually?

**Comment by AAPBD** [comment]
/usr/bin/env xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    ARCHS = x86_64
    BUILD_DIR = /Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios
    COMPILER_INDEX_STORE_ENABLE = NO
    FLUTTER_SUPPRESS_ANALYTICS = true
    SDKROOT = iphonesimulator14.5

xcodebuild: error: Scheme Runner is not currently configured for the build action.



And it also gets crash into xcode. Any hints to solve it?

**Comment by jmagman** [comment]
@AAPBD in the other instances the `Runner` scheme in Xcode had been manually edited by the developer.  If you look above I asked a lot of questions to figure out the issue.  Please follow the same instructions to either figure out what's different about your project, or open a new issues with the answers to the same questions.

**Comment by jmagman** [comment]
> Xcode gets crash itself so I can't check the Scheme manage from the Xcode.

I suspect your Xcode project is corrupted in some way, but who knows why it's crashing.  Try upgrading Xcode and see if you're still seeing the crash.  This isn't really actionable until you can open the project in Xcode.

You can try recreating your project with Flutter by removing the `ios` directory, then running `flutter create .` in your project directory.  Then you can look in source control and see how your Xcode project is different from the generated one.
