### ISSUE TITLE
Card should allow declaring shadowColor

### ISSUE THREAD

**Issue by josh-burton** [flutter/flutter#47272]
## Use case

When using a Card widget, I want to customize the Material shadowColor.

## Proposal

Add a shadowColor property to the Card Widget that sets the shadowColor on the internal Material widget.

This would allow changing a Card's shadow color:

```
Card(
	color: Colors.red,
	shadowColor: Colors.blue,
)
```

**Comment by Piinks** [comment]
Closing as fixed.
