### ISSUE TITLE
Flutter atom plugin should have a one-click way to run tests

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4727]
If I have a "_test.dart" file from a Flutter project open in Atom, rather than offering to run that file in the Dart cli (as the "run" toolbar does currently), Atom should offer to run that file as a flutter test.  Specifically, `flutter test path/to/file_test.dart`.

Bonus points for an option to run with the forthcoming `--merge-coverage` option (see https://github.com/flutter/flutter/pull/4726) to make it super fast to iterate on test coverage.

/cc @devoncarew @Hixie

**Comment by devoncarew** [comment]
Looking at the help for `--merge-coverage` it says it's linux only - I'm curious why?

Also, will the `--merge-coverage` option apply to flutter project in general, or just to the flutter repo?

**Comment by abarth** [comment]
> Looking at the help for --merge-coverage it says it's linux only - I'm curious why?

The command line tool we're using to merge lcov files is a Linux utility.  We could also just write some Dart code to merge lcov files.

> Also, will the --merge-coverage option apply to flutter projects in general, or just to the flutter repo?

It's something that can be used by any Flutter project, but I wouldn't expect that many developers to interested in test coverage.  (Although I might be wrong about that.)

**Comment by devoncarew** [comment]
@cbracken, @kevmoo, does the merge code already exist in a package somewhere? Perhaps in https://pub.dartlang.org/packages/dart_coveralls?

**Comment by cbracken** [comment]
There's separate code for this internally. I'll take a look at getting this externalised as part of package:coverage.

**Comment by devoncarew** [comment]
This is landed; I'll probably iterate on the UI a bit. In any case, there's a button in the toolbar to run tests (it's visible when a test file is open). There's also a keybinding to run the current file (ctrl-option-cmd-t on the mac).

The `--merge-coverage ` option is semi-hidden for now. To enable it, open the Atom > Config file, and add `mergeCoverage: true` to the `flutter` section.

**Comment by abarth** [comment]
Thanks!

**Comment by abarth** [comment]
Sweet!  Works.

**Comment by devoncarew** [comment]
This now looks to see if there's a clear mapping from the current editor, to a test library for that file. If so, the keybinding (and button) will run tests for the associated test library. It uses a few common file naming conventions to try and find an associated test file.
