### ISSUE TITLE
LicensePage and LicenseRegistry have many duplicate entries

### ISSUE THREAD

**Issue by adamkoch** [flutter/flutter#47274]
## Steps to Reproduce
Load up Flutter Gallery (https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) and build and run. Click hamburger menu in top right -> About Flutter Gallery -> View Licenses.

This reproduces in my own application as well.

The generated licenses have many duplicate entries, for example, the "angle" library has **13 entries**. They each do have minor differences like the year or spacing but I don't think this is WAI as it makes the licenses page extremely long.

**Target Platform:** Tested on Android and iOS
**Devices:** Simulator and emulator

<img width="430" alt="Screen Shot 2019-12-18 at 2 21 21 pm" src="https://user-images.githubusercontent.com/869261/71053397-6750f980-21a2-11ea-86c3-d29ec8f9d6a8.png">

```
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88,
    locale en-AU)
    • Flutter version 1.12.13+hotfix.5 at /Users/adam/lib/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/adam/lib/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/adam/lib/android-sdk
    • Java binary at: /Applications/Android Studio
      3.5.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 579F0654-D6EB-4E6F-B6A8-B190BD324762 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```
```

**Comment by filiph** [comment]
This is happening to all Flutter apps, not just the gallery. It looks like `LicenseRegistry` isn't deduping licenses that share 99% of content but have different year ranges (e.g. in the screenshot above, there's `angle 2013-2017` and `angle 2013-2018`).

I assumed this is intentional. If not, we should de-dupe. If this is intential (e.g. legally, we need to print all license files in full, even if they are obviously duplicate), maybe it might make sense to make the issue a bit less confusing for the user. For example, it would be nice to group such licenses under one heading, instead of keeping them separate.

**Comment by Hixie** [comment]
Right, those are not duplicates, they have different dates. That said, there is effort under way to group the licenses so this will become less of an issue.

**Comment by adamkoch** [comment]
@Hixie any issue to follow around that work?

Also it's not just the dates that are different. It's sometimes the actual text or the formatting of the text as well.

FWIW, in a production app I have seen (which uses a pretty standard number of 3P libs) the license page is essentially unusable having hundreds and hundreds of pages of licenses due to the duplicates.

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/57226 (PR at https://github.com/flutter/flutter/pull/57588).
