### ISSUE TITLE
NetworkImage should evict itself from the cache if it fails to load due to a network error.

### ISSUE THREAD

**Issue by rogersxiao** [flutter/flutter#47270]
I find a bug in NetworkImage/image_cache.  if I load image when network is not available. now, my network is available,setState my widget, image will not work. look the source code,I find the bug in  framework. 
I find the code at image_cache.dart
` try {
      result = loader();
    } catch (error, stackTrace) {
      if (onError != null) {
        onError(error, stackTrace);
        return null;
      } else {
        rethrow;
      }
    }`
call loader() with sync but at _network_image_io.dart the loader() is async, If network is not available, loader() is failed, it can't not match your catch but put the error result to _pendingImages. when my network is available, I refresh my networkImage,it will return me error result from _pendingImages

![企业微信截图_b69ed4d4-1d45-4f04-804d-029ead4bcf70](https://user-images.githubusercontent.com/12211212/71060500-a1210080-21a0-11ea-9a93-c82233d540da.png)

![企业微信截图_ae161c5a-f7a0-41df-8cc7-55e6277153c0](https://user-images.githubusercontent.com/12211212/71060553-c01f9280-21a0-11ea-8af4-1f73fa53e903.png)

**Comment by iapicca** [comment]
Hi @rogersxiao 
your screenshot seems to refer to the file `image_provider.dart` lines >274 <336;
could you provide a minimal code sample to reproduce the error?
thank you

**Comment by rogersxiao** [comment]
@iapicca `              Image.network(
                      "https://image-static.segmentfault.com/176/872/1768723716-5b188ca549250_articlex"),` just use Image network can reproduce the error follow my step. step 1 : close network.  2:open app. 3: open network. 4.refresh widget.  image can't work anymore

**Comment by dnfield** [comment]
The problem is that the cache ends up with a bad entry for this. We should make the NetworkImage evict itself from the cache when there's a network failure.

**Comment by dnfield** [comment]
See also: https://github.com/flutter/flutter/issues/47378

**Comment by ds84182** [comment]
@dnfield The fix in #51398 doesn't handle SocketExceptions, so if network access is temporarily lost the image won't load.

**Comment by dnfield** [comment]
@ds84182 - it would be really helpful if you could write a failing test case for that

**Comment by dnfield** [comment]
Thanks, uploaded a new patch that covers this case.
