### ISSUE TITLE
Consider removing our dart:jni support

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4728]
Since we now have an alternative approach to dart:jni, we should probably consider removing it, to alleviate ourselves of the documentation and maintenance burden.

If we keep it, we should make sure we provide an iOS equivalent, and we should write dartdocs for it.

cc @jason-simmons

**Comment by eseidelGoogle** [comment]
I support removing it.  We can always revert/add it back.

**Comment by jason-simmons** [comment]
dart:jni does have some advantages over host messages:
  * it can call into Java code or Android APIs synchronously.  Host messages are async only.
  * it can be used in apps that are built entirely in Dart with the flutter_tools workflow.  Host apps require a Java toolchain.

**Comment by Hixie** [comment]
To clarify, I don't have an opinion about whether we should keep it or remove it. Our current situation is unstable in that it's missing an equivalent on iOS and it's missing docs (and tests?) and has minimal usage. We should either add an equivalent to iOS, add docs (and tests?), and get customers to use it, or, we should remove it. Either way is fine by me. It's just the status quo that isn't. :-)

**Comment by eseidelGoogle** [comment]
In terms of iOS, https://github.com/flutter/engine/pull/2217 was our wip dart:objc support.

**Comment by sethladd** [comment]
Looks like we have docs for dart:jni: http://docs.flutter.io/flutter/dart-jni/dart-jni-library.html

**Comment by sethladd** [comment]
What was the resolution of this issue?

**Comment by abarth** [comment]
Current status is we have docs but no iOS peer.

**Comment by sethladd** [comment]
Sounds like we decided to keep dart:jni around. Will close. Feel free to reopen if we want to reconsider.
