### ISSUE TITLE
Flutter reports corrupted archive if unzip is not installed

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#47307]
## Steps to Reproduce

On a Linux machine without the `unzip` tool installed:

1. Clone a clean copy of the flutter repo.
2. Run `flutter doctor`, triggering the download of the Dart SDK and other archives.

Expected behaviour: download completes and a friendly error message is emitted complaining about the lack of `unzip` on the path.
Actual behaviour: flutter reports a corrupted archive and exits.

While some popular distros often ship with `unzip`, it's not required by POSIX and many distros don't ship with in pre-installed. We should check for unzip and fail gracefully if it's not found.

## Logs

```shell
% flutter doctor
Downloading Dart SDK from Flutter engine 500f9cedf652cc4a4d33c94db77e258d2b10e257...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  192M  100  192M    0     0  10.0M      0  0:00:19  0:00:19 --:--:-- 10.5M
/home/chris/src/flutter/flutter/bin/internal/update_dart_sdk.sh: line 86: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

**Comment by cbracken** [comment]
Probably overall low priority, but easy fix.

**Comment by cbracken** [comment]
FWIW the same applies to the `which` command, which is often just a shell built-in, but which `flutter_tools` assumes is a binary on the path:

```
encountered exception: Invalid argument(s): Cannot find executable for which.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _PosixUtils._which (package:flutter_tools/src/base/os.dart:150:49)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:52:43)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:336:38)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:360:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
```

**Comment by christopherfujino** [comment]
@cbracken I didn't know `which` could be a shell-built in (it isn't in Bash). What shell are you using? And I just checked and you're right, `which` isn't part of the POSIX standard.

**Comment by cbracken** [comment]
`which` is a shell built-in in `zsh`, `csh`, `tcsh`, and maybe `ksh` (though I might be thinking of `whence` in `ksh`).

**Comment by christopherfujino** [comment]
WIndows version of this issue https://github.com/flutter/flutter/issues/37135

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/55315/
