### ISSUE TITLE
Autoroller commit messages do not include all commits in the description.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#47304]
An example is this attempted roll: https://github.com/flutter/flutter/pull/47283

Having an incorrect list of commits in the description leads to inaccuracies and confusion in diagnosing issues related to rolls.

The description lists the following commits:

```
2019-12-18 a-siva@users.noreply.github.com Manual roll of Dart to revision 8a4cac1ddb141d4a1e395f6e0a7d5bbf2247eb63 (flutter/engine#14542)
2019-12-18 50856934+nturgut@users.noreply.github.com Calling onConnectionClosed when the input element is blurred (flutter/engine#14484)
2019-12-17 skia-flutter-autoroll@skia.org Roll src/third_party/dart f10fa3df28a8..44da51fc720d (20 commits) (flutter/engine#14533)
2019-12-17 skia-flutter-autoroll@skia.org Roll src/third_party/skia cbeabd969bbe..3794db84e141 (8 commits) (flutter/engine#14532)
2019-12-17 garyq@google.com Rename 'test_vsync_waiters' to 'vsync_waiters_test' for consistency. (flutter/engine#14519)
2019-12-17 skia-flutter-autoroll@skia.org Roll src/third_party/skia fdb2b7d53038..cbeabd969bbe (1 commits) (flutter/engine#14530)
```

Running the command right there in the commit message manually lists the following however:

```
44f075779 Manual roll of Dart to revision 8a4cac1ddb141d4a1e395f6e0a7d5bbf2247eb63 (#14542)
07429c1c3 Revert "[fuchsia] Do not Execute paint tasks when there is no vsync (#14298)" (#14541)
fad86658d Roll src/third_party/skia 3794db84e141..190b82d67ce1 (11 commits) (#14538)
c216ba42b Calling onConnectionClosed when the input element is blurred (#14484)
3da1e11fb Roll fuchsia/sdk/core/linux-amd64 from ZHhOi... to WSlsF... (#14534)
ac42640fd Roll src/third_party/dart f10fa3df28a8..44da51fc720d (20 commits) (#14533)
86456e1ee Support timeline can enabled in release mode (#14521)
0f97a1e83 Roll src/third_party/skia cbeabd969bbe..3794db84e141 (8 commits) (#14532)
9b369ad19 Rename 'test_vsync_waiters' to 'vsync_waiters_test' for consistency. (#14519)
ad3bade1d Roll src/third_party/dart 51859cb2056c..f10fa3df28a8 (4 commits) (#14531)
9f2daad64 Fix off-by-one fromRGBO alpha value calculation (#13777)
ee92285ab Roll src/third_party/skia fdb2b7d53038..cbeabd969bbe (1 commits) (#14530)
02825aa02 Roll src/third_party/dart 2d332ee1d3f1..51859cb2056c (2 commits) (#14529)
```

In this particular case, one of the commits missing from the commit message was the cause of the failure caused by the roll.

**Comment by chingjun** [comment]
Also I found that only the commits that are all green on [luci](https://luci-milo.appspot.com/p/flutter/g/engine/console) will show up here, the ones with failing jobs are all missing.

**Comment by chinmaygarde** [comment]
Thats a very interesting observation. I only recently found that the commit messages are not generated by using the command listed in the commit message itself.

**Comment by chinmaygarde** [comment]
cc @rmistry, is there something we can do to include all commits in the description?

**Comment by rmistry** [comment]
Will ask borenet@ for advice on this.

**Comment by erock2112** [comment]
Hrm, this has to do with the way the autoroller is structured.  We operate numerous rollers, and there are several types which don't roll git commits at all.  There are some abstractions in place to allow different types of rollers to behave the same way despite these differences.  One of those is Revision, which in this case is a Git commit.  At the lowest level, RepoManager is responsible for determining the current Revision and the set of not-yet-rolled Revisions.  It also knows how to create a roll to a particular Revision.  The rest of the logic is higher up, including the strategy for choosing which Revision to roll, which can be set in the UI.  A lot of this was added in https://skia-review.googlesource.com/c/buildbot/+/255823

So, as you've discovered, the "git log" command is kind of a lie, although we do keep it in sync with the actual command used to generate the list of not-yet-rolled Revisions.  The reason that this particular roller is showing an incomplete list of Revisions is that the RepoManager is configured to filter that list by the presence of corresponding files in GCS: https://skia.googlesource.com/buildbot/+/master/autoroll/config/flutter-engine-flutter.json#39.  That prevents the roller from rolling to a Revision for which those files are not present, which is the desired effect, but it also causes any commits which are missing files in GCS to be dropped from the commit message.

There are other RepoManagers which filter out Revisions, but those do not roll Git commits and thus have no concept of a log.  The best fix is probably to have this RepoManager return the unfiltered list of Revisions but mark those which do not have corresponding files in GCS as invalid roll candidates, and then respect that when choosing a Revision to roll.

**Comment by rmistry** [comment]
> The best fix is probably to have this RepoManager return the unfiltered list of Revisions but mark those which do not have corresponding files in GCS as invalid roll candidates, and then respect that when choosing a Revision to roll.

This SGTM. (Eric mentioned he is going to look into doing this)
