### ISSUE TITLE
Flutter1.12.13+hotfix.5.In my flutter project build apk failed,but in Android project I can build apk success

### ISSUE THREAD

**Issue by lj3069** [flutter/flutter#47310]
In my flutter project build apk failed,but in Android project I can build apk success
![微信截图_20191218155751](https://user-images.githubusercontent.com/29448722/71067237-2dd2bb00-21af-11ea-8e98-e185c62c6322.png)

**Comment by gangganghao1016** [comment]
That's the same with me

**Comment by BondarenkoStas** [comment]
Hi @lj3069 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by phcaraujo** [comment]
> Hi @lj3069
> could you please run
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter clean`
> `flutter pub cache repair`
> If the issue persist please provide your updated
> `flutter doctor -v` and `flutter run --verbose`
> together with a a minimal code sample to reproduce the problem
> thank you

not work for me #47337

**Comment by rkpradeep20** [comment]
Having the same issue.

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
