### ISSUE TITLE
type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by JokerJoin** [flutter/flutter#47326]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
Hi @JokerJoin
Int cannot be converted by default to String

Code example:
`title: new Text(time ?? "Empty")`
should be
`title: new Text(time != null ? '$time' : "Empty")`
or
`title: new Text('${time ?? "Empty"}')`,

I hope this solves your problem
