### ISSUE TITLE
docs.flutter.io monitoring

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4733]
We should find out ASAP if docs.flutter.io stops serving useful data.

**Comment by Hixie** [comment]
@mit-mit @sethladd Who's the right person to add this?

**Comment by mit-mit** [comment]
I'm experimenting with monitoring of flutter.io and docs.flutter.io using StackDriver (which is now part of GCP).

**Comment by mit-mit** [comment]
Closing, the StackDriver monitoring appears to be working
