### ISSUE TITLE
ScreenShot from video_player

### ISSUE THREAD

**Issue by salime45** [flutter/flutter#47338]
Hi,

I am using this lib and the https://github.com/SachinGanesh/screenshot, but seems dont work correctly.

The generate image is always black, anyone knows how to fix this?

Thanks

**Comment by iapicca** [comment]
Hi @salime45 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by salime45** [comment]
[√] Flutter (Channel master, v1.13.3-pre.81, on Microsoft Windows [VersiÃ³n 10.0.18362.535], locale es-ES)
    • Flutter version 1.13.3-pre.81 at D:\Program Files\flutter
    • Framework revision a4858782da (24 hours ago), 2019-12-18 23:53:00 -0800
    • Engine revision 1e1f37107a
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 270966b160)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Ultra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Ultra\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Ultra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

**Comment by salime45** [comment]
I going to create a project to reproduce the problem

**Comment by iapicca** [comment]
Hi @salime45 
I apologize, I think I misunderstood the nature of the issue,
I thought that with `screenshot` you meant a literal screenshot,
not a 3rd party [plugin](https://pub.dev/packages/screenshot)
(which doesn't seem being updated in the last 7 months);
I noticed that you opened an [issue ](https://github.com/SachinGanesh/screenshot/issues/14)in that repository github; 
this is without doubt the right course of action.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by salime45** [comment]
I leave here a repo with the problem https://github.com/salime45/video_screenshot
