### ISSUE TITLE
docs upload needs to be atomic

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4734]
Right now whenever the bot uploads the docs, the site goes down. Usually it is quick enough but if it times out or whatever, the docs end up in a bad state.

**Comment by abarth** [comment]
And we need the ability to roll back.

**Comment by Hixie** [comment]
I've bumped this to the "Next" milestone because the uploads are sometimes taking long enough that our site is down for minutes at a time, several times a day.

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/4236

But yeah, working on this now :)
