### ISSUE TITLE
Android Studio 3.6 RC1 - no new Flutter Module option

### ISSUE THREAD

**Issue by bDev10** [flutter/flutter#47346]
## Steps to Reproduce

Follow steps[ in this documentation](https://flutter.dev/docs/development/add-to-app/android/project-setup). When I go to the File > New > New Module... there is no Flutter Module type (and any other Flutter module types) to choose although I have Flutter plugin for Android Studio installed.

## Platform
Windows 10 Pro 64-bit

## flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale pl-PL)
    • Flutter version 1.12.13+hotfix.5 at c:\Users\BB\AppData\Local\Android\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\BB\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\BB\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio Beta\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio Beta
    • Flutter plugin version 42.1.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Nexus 9 • HT4C9JT00640 • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by xster** [comment]
cc @stevemessick 

Please use the Flutter plugin version 42

**Comment by stevemessick** [comment]
I'd also suggest using the 3.6 version. It is almost ready for stable release; current version is RC 1.

**Comment by bDev10** [comment]
@xster Thank you! I've updated Flutter plugin to 42.2.2 and appeared two new options in new module:
- Flutter Module
- Import Flutter Module
There is no "Flutter Package" that is shown on the screenshot in the docs however (https://flutter.dev/docs/development/add-to-app/android/project-setup) but maybe docs are not actual.

I alreadey used AS 3.6 RC1, however I don't know why I got Flutter plugin 42.1.3 when tapped on install Flutter plugin instead of 42. Today I checked and there was possibility to upgrade version.

I think the issue can be closed if missing "Flutter Package" option is intentional, but if so, probably docs should be fixed.

**Comment by jmagman** [comment]
I'm on 42.1.1 and I see "Flutter Package".  Can you file an issue against [the IDE extension](https://github.com/Dart-Code/Dart-Code/issues/new)?

It seems like the "Flutter Module" option is there, though.  Thanks for the report!
Closing.
