### ISSUE TITLE
Add support for the focus traversal policy to continue outside of the current Navigator

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#47344]
## Use case

Assume that you have a Navigator with some subpages and outside the Navigator you have buttons. See the example app: https://dartpad.dartlang.org/613822e51fc800e85c0f6261273924bb

You want to be able to tab through the page to access all the buttons. That is when you have reached the last element inside of the Navigator subpage, you want to be able to access the buttons outside of it.

## Proposal

Let us have an API that let us traverse the whole page with all focus nodes reachable.

**Comment by DanTup** [comment]
Whoops, sorry - didn't expect updating my fork to close issues here 😬

**Comment by perclasson** [comment]
> Whoops, sorry - didn't expect updating my fork to close issues here 😬

I did the same mistake before! It's quite confusing that a commit message can close an issue in another repository. :)

**Comment by DanTup** [comment]
Sometimes I think it makes sense (for example sometimes I take advantage of it to close an issue in Dart-Code from Flutter if this is where the issue needed to be fixed). It does seem a bit weird from a fork though - maybe it should only happen for the upstream repos 🤷‍♂️

I wonder if I closed any other issues (I pushed a lot of changes to that repo to bring it up-to-date), or if there's a way to tell :/

**Comment by gspencergoog** [comment]
This is because there is `FocusScope` in the navigator.  Yes, it would be nice to be able to do, but the Navigator is usually surrounding all the widgets in a typical app, so this doesn't often come up. Setting the focus to another widget will allow you to escape the scope, but I suppose you need a way to know when to do that.

**Comment by guidezpl** [comment]
Closing this with respect to https://github.com/flutter/gallery/issues/1072
