### ISSUE TITLE
Change format DateTime

### ISSUE THREAD

**Issue by cristianfb1989** [flutter/flutter#47340]
How do I can change format when I assign "selectedDate" to "dateBirthdayUser"? I need that "dateBirthdayUser" show date like that '31/12/2019". Thx

```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
class _ProfileState extends State<Profile> {
  DateTime dateBirthdayUser = DateTime(1900, 01, 01, 00, 00, 00);
  DateTime selectedDate = DateTime.now();

  Future<Null> _selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
        builder: (BuildContext context, Widget child) {
        },
        locale: Locale('es'),
        context: context,
        initialDate: selectedDate,
        firstDate: DateTime(1950, 1),
        lastDate: DateTime(2100));
    if (picked != null && picked != selectedDate)
      setState(() {
        selectedDate = picked;        
        dateBirthdayUser = selectedDate;
      });
  }
```

**Comment by cbenhagen** [comment]
You do not care about the string representation at that point but will format it on output with `DateFormat`. See https://stackoverflow.com/questions/51579546/how-to-format-datetime-in-flutter for more details.

Please post such questions on stackoverflow instead of this issue tracker.

**Comment by fluttercorner** [comment]
[How to Display Current DateTime in Flutter](https://fluttercorner.com/how-to-display-current-datetime-in-flutter/)
