### ISSUE TITLE
Android Studio 3.6 RC1 - dart files not shown in Project tool window

### ISSUE THREAD

**Issue by bDev10** [flutter/flutter#47347]
## Steps to Reproduce

1. Create new Android project in Android Studio (for example using "Basic Activity" template). I used Android Studio 3.6 RC1 and version 3.5 too.
2. Integrate Flutter module into Android project [as described here, by manual integration Option B - Depend on the module’s source code](https://flutter.dev/docs/development/add-to-app/android/project-setup).
3. Project window is not showing any dart files (in "Project" and "Android" view mode). "lib" folder in flutter module is not shown too.

## flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale pl-PL)
    • Flutter version 1.12.13+hotfix.5 at c:\Users\BB\AppData\Local\Android\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\BB\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\BB\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio Beta\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio Beta
    • Flutter plugin version 42.1.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Nexus 9 • HT4C9JT00640 • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by xster** [comment]
cc @stevemessick. Do you guys have a tool to migrate issues into https://github.com/flutter/flutter-intellij/issues?

@bDev10, can you find the dart files by double tapping the shift key and searching?

**Comment by bDev10** [comment]
@xster Yesterday double tapping the shift key (and entering file name) didn't find it, but I moved it by hand from file explorer to Android Studio to edit the file and today when I double tapped shift it appeared in "Recent files" section of search window.
