### ISSUE TITLE
Allow us to specify sort order in FocusTraversalPolicy (like a SemanticsSortKey)

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#47349]
## Use case

Assume you have an app where the focus traversal policy neither works like `WidgetOrderFocusTraversalPolicy` nor `ReadingOrderTraversalPolicy`, for example something like this dartpad: https://dartpad.dartlang.org/9230e440954506acd2fae8992c15821f

We would want to be able to specify a traversal policy where we set a sort key and order to the elements, sort of like we have `SemanticsSortKey` when it comes to deciding Semantics accessibility traversal order sorting.

## Proposal

Add sort key to focus nodes to allow for custom focus traversal policy

**Comment by gspencergoog** [comment]
This was fixed by https://github.com/flutter/flutter/pull/50672
