### ISSUE TITLE
I upgraded to flutter master 1.13.3 and the color of choice chips got out of the borders

### ISSUE THREAD

**Issue by sarthak1singhal** [flutter/flutter#47350]
## Steps to Reproduce

![WhatsApp Image 2019-12-18 at 9 58 50 PM (1)](https://user-images.githubusercontent.com/22476073/71104961-b74fb080-21e2-11ea-8c61-6cc89a36b7c7.jpeg)

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by HansMuller** [comment]
CC @goderbauer

**Comment by goderbauer** [comment]
I rolled back the bad change.
