### ISSUE TITLE
Timeline events are not consistent for Flutter desktop.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#47355]
Neither Observatory nor DevTools are receiving as many timeline events as expected. I connected a Flutter Desktop app to both Observatory and DevTools, did something in the desktop app that should have drawn 100's of Flutter frames. Refreshed Observatory and witnessed trace for only a single frame. The same behavior was seen in DevTools.

**Comment by jonahwilliams** [comment]
Potentially related to https://github.com/flutter/flutter/issues/46005

**Comment by kenzieschmoll** [comment]
I should add that I was running a flutter desktop app on MacOS

**Comment by darshankawar** [comment]
Hi @kenzieschmoll 
Just checking to see if this is still a valid issue using latest Flutter version or has this been resolved ?

**Comment by kenzieschmoll** [comment]
This seems to be resolved (though the timeline recording streams needed to be enabled manually due to https://github.com/flutter/flutter/issues/70794).
