### ISSUE TITLE
flutter not finding IOS simulator

### ISSUE THREAD

**Issue by faiqmustaqeem** [flutter/flutter#47354]
ios simulator is opened but flutter not findin ios simulator and showing no devices connected

flutter doctor showing this.
Users-MacBook-Pro:~ user$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.13.6 17G65,
    locale en-PK)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.0)
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

do i need to update x code or is there any other solution possible ?

**Comment by jonahwilliams** [comment]
Your flutter doctor contains instructions on what needs to be fixed:

```
✗ Flutter requires a minimum Xcode version of 10.2.0.
Download the latest version or update via the Mac App Store.
! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
CocoaPods is used to retrieve the iOS and macOS platform side's plugin
code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade:
sudo gem install cocoapods
```
