### ISSUE TITLE
Scroll friction does not match other iOS Apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4736]
https://github.com/flutter/flutter/issues/4707 is the Android version of this.

We're somewhere in between.  iOS is way more slippy than Android and even more slippy than flutter currently.  @abarth 

https://youtu.be/11AYsuNULk8

**Comment by Hixie** [comment]
With the latest builds I think this is fixed. If it isn't I need more precise steps to reproduce. :-)
