### ISSUE TITLE
Module 'url_launcher' not found

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#47367]
I have got repeatly this error when I try Archive app in XCode. flutter run working fine.

![image](https://user-images.githubusercontent.com/17269309/71115260-d265f480-21d1-11ea-9fc2-765d3bfc5462.png)

Podfile.lock
```
PODS:
  - Flutter (1.0.0)
  - url_launcher (0.0.1):
    - Flutter
  - url_launcher_macos (0.0.1):
    - Flutter
  - url_launcher_web (0.0.1):
    - Flutter

DEPENDENCIES:
  - Flutter (from `Flutter`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)
  - url_launcher_macos (from `.symlinks/plugins/url_launcher_macos/ios`)
  - url_launcher_web (from `.symlinks/plugins/url_launcher_web/ios`)

EXTERNAL SOURCES:
  Flutter:
    :path: Flutter
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"
  url_launcher_macos:
    :path: ".symlinks/plugins/url_launcher_macos/ios"
  url_launcher_web:
    :path: ".symlinks/plugins/url_launcher_web/ios"

SPEC CHECKSUMS:
  Flutter: 0e3d915762c693b495b44d77113d4970485de6ec
  url_launcher: a1c0cc845906122c4784c542523d8cacbded5626
  url_launcher_macos: fd7894421cd39320dce5f292fc99ea9270b2a313
  url_launcher_web: e5527357f037c87560776e36436bf2b0288b965c

PODFILE CHECKSUM: 1b66dae606f75376c5f2135a8290850eeb09ae83

COCOAPODS: 1.8.4

```

**Comment by peterkuch** [comment]
flutter clean,
flutter run again
rebuild it from ios or vscode tool again.

**Comment by kleinpetr** [comment]
I tried everuthing.. rm Podfile, rm -r Pods, flutter clean, etc.. nothing helped me.

but probably I have bigger problem. when I remove url_launcher from pubspec I have got this error...

![image](https://user-images.githubusercontent.com/17269309/71161499-bf8f0680-2249-11ea-8620-a9b403d2725d.png)

**Comment by peterkuch** [comment]
Please your mine try create new Podfile after 
copy use this for latest version 
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by iapicca** [comment]
Hi @kleinpetr 
does  @peterkuch 's solution work for you?
thank you

**Comment by peterkuch** [comment]
Yes, it's work for me
my config
```
Flutter 1.13.3-pre.83 • channel master • https://github.com/flutter/flutter.git
Framework • revision 78db965642 (6 hours ago) • 2019-12-19 11:23:01 +0100
Engine • revision 0f90e6546b
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)
```
```
XCode latest version 11.3 
```
<img width="990" alt="Screen Shot 2019-12-19 at 11 36 15 PM" src="https://user-images.githubusercontent.com/14107698/71191486-197ae500-22b9-11ea-9088-c11ceeb1b2cd.png">

**Comment by jmagman** [comment]
@kleinpetr Can you confirm you have opened Runner.xcworkspace and not Runner.xcodeproj, following the instructions at https://flutter.dev/docs/deployment/ios#create-a-build-archive?  See https://github.com/flutter/flutter/issues/10770

**Comment by peterkuch** [comment]
yes confirm please open Runner.xcworkspac with xcode  because app will get local lib from pod install lib that installed. , but don't  Runner.xcodeproj 
<img width="327" alt="Screen Shot 2019-12-20 at 7 54 44 AM" src="https://user-images.githubusercontent.com/14107698/71221184-3c7bb800-22fe-11ea-9433-5056244939b0.png">

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by balajiks-dev** [comment]
Hi,
Anyone solved this issue? (Flutter)
I'm stucked this issue for 2 days.
when pod install, it shows error.
[!] No podspec found for `url_launcher` in `.symlinks/plugins/url_launcher/ios`

Path: ProjectName/ios/.symlinks/plugins/url_launcher/ios

![Screenshot 2020-02-25 at 11 15 11 AM](https://user-images.githubusercontent.com/24551909/75218461-5f27c280-57c0-11ea-885a-ff5afda89f58.png)


There is not url_launcher.podspec file.

How to create this file. Need command for this.

**Flutter Doctor Output**

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/balajisundaram/flutter 2
    • Framework revision 0b8abb4724 (13 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/balajisundaram/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Users/balajisundaram/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone • 609bf4c1882659a5f09c694e656c42b8ad5091a7 • ios • iOS 12.1.4

• No issues found!

**Comment by peterkuch** [comment]
can you try my comment above.

**Comment by balajiks-dev** [comment]
@peterkuch 
Yes peter. I tried but not works!

**Comment by peterkuch** [comment]
please open Runner.xcworkspac with xcode because app will get local lib from pod install lib that installed. , but don't Runner.xcodeproj , are you ready to open this file?

**Comment by balajiks-dev** [comment]
@peterkuch 
Yeah, I run this from Runner.xcworkspac itself. In Xcode also it showing the same error.

In pub update command also it shows the above error.

**Comment by peterkuch** [comment]
can you try:
remove all build from flutter , ios build , android build.
and that :  open project root run
pod repo update
and 
flutter clean
flutter pub get
<img width="855" alt="Screen Shot 2020-02-25 at 1 20 15 PM" src="https://user-images.githubusercontent.com/14107698/75220267-981c6300-57d1-11ea-9684-11a47bed28be.png">

**Comment by jmagman** [comment]
@balajiks-dev Sounds like your pub cache got corrupted.  Try `flutter pub cache repair `.

**Comment by lucasfzs** [comment]
@jmagman thank you !!! it works

**Comment by mariohandsome** [comment]
Step 1: delete foloder `ios` and `android`
Step2: `flutter create .`
Step 3: `flutter run`
Step 3b: (maybe you have alert: "Error: To set up CocoaPods for ARM macOS, run:  arch -x86_64 sudo gem install ffi", so run: `arch -x86_64 sudo gem install ffi`, then run agian `flutter run`

It's work to me. Mac pro M1.

**Comment by mafreud** [comment]
well I still have this problem...

**Comment by jmagman** [comment]
@mafreud This issue was closed waiting for more information from the originator.  Please open a new issue and completely fill out the template.  Include a your full `flutter run` logs with the `--verbose` flag (it's large, you'll have to attach it).
