### ISSUE TITLE
fling scrolls on iOS are wrong

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4737]
They feel really wrong.  Worse than android.  I think iOS has a bit of slip to a fling scroll where as we stick a bit too hard to the finger?  Not sure.  Also we have some sort of bug whereby we seem to cancel the current fling more aggressively than we should?

https://github.com/flutter/flutter/issues/4736 is about non-fling scrolls.

To reproduce: try scrolling in iOS settings vs. flutter gallery.  https://youtu.be/6l7H6-DTjtQ

**Comment by eseidelGoogle** [comment]
The abrupt stops or wrong-direction flings may relate to https://github.com/flutter/flutter/issues/4708

**Comment by eseidelGoogle** [comment]
FYI @Hixie (who is looking at another scrolling issue atm).

**Comment by eseidelGoogle** [comment]
I would recommend we consider this for the August milestone if we have time.  This and the lack of back gesture (https://github.com/flutter/flutter/issues/4817) are issues encountered when I hand the gallery to an iOS user.

**Comment by eseidelGoogle** [comment]
I installed your new hotness.  Definitely better.  Flings still will need some tuning, but maybe I can whip up some test apps for that.  I'll file a separate bug when I have more info, this is a huge improvement and will likely satisfy the customers-notice-in-demos problem. :)  Thanks!

**Comment by Hixie** [comment]
Yeah I think the remaining issues are mainly https://github.com/flutter/flutter/issues/4958

**Comment by eseidelGoogle** [comment]
iOS will coallese touches, you can get the individual ones with [UIEvent coalescedTouchesForTouch:] I'm told:
http://flexmonkey.blogspot.de/2015/09/advanced-touch-handling-in-ios9.html
