### ISSUE TITLE
ImageCache: Add documentation on how to setup your own ImageCache

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#47388]
It isn't very intuitive how to replace the ImageCache implementation.  We should add documentation to the docstrings in ImageCache that points to how to swap out bindings to have our own ImageCache.

cc @Hixie

**Comment by pedromassangocode** [comment]
Closing this because this was clearly fixed by https://github.com/flutter/flutter/pull/47467 and the actual [documentation of ImageCache](https://api.flutter.dev/flutter/painting/ImageCache-class.html) now contains an example of how to create a custom image cache class
