### ISSUE TITLE
"error running application on iphone", but the app was installed

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4738]
Currently, I use `flutter run --release` to install an app onto the iPhone.

My screen was locked, and I got this error:

```
^C~/Code/flutter/examples/flutter_gallery[master] $ flutter run --release
Running lib/main.dart on iPhone...
Xcode project created in /Users/sethladd/Code/flutter/examples/flutter_gallery/ios/.
Could not install ios/.generated/build/Release-iphoneos/Runner.app on ff369dfd5f4a80545a431441c1e3066f8cb8d759.
Error running application on iPhone.
```

Except, the app was installed successfully. (I'm 100% positive the app was installed :)

Looks like we're reporting a correct error (could not start the app, due to the screen locked) but misreporting the "could not install" error.

**Comment by Hixie** [comment]
Does this still happen?

**Comment by Hixie** [comment]
@sethladd Can you see if you're still seeing this?

**Comment by Hixie** [comment]
Leaving in current milestone since it presumably affects anyone developing on iOS.

**Comment by mit-mit** [comment]
I've not seen other reports of this. @sethladd do you still see this? If not, we should consider punting.

**Comment by sethladd** [comment]
Let's close, but we'll reopen if others report this.
