### ISSUE TITLE
Shrine: motion/transition of item unnecessarily includes a new top bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4739]
Check out the video of this effect in action: https://youtu.be/UPGymw2NU0s?t=1m14s

Notice how, when the item transitions up, it brings along its own top bar. This is probably not correct (we probably shouldn't be creating a new top bar and growing it up to replace the existing bar).

Instead, the item should transition up and the top bar should remain in place. No new top bar should be transitioned/created/animated up.

**Comment by sethladd** [comment]
Now that the animations have been slowed down, we can more clearly see that that we're also drawing/moving the header as well as the image itself.

We should not draw/grow/move the header bar as the image heros up into full view.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/pull/5214 may be related to this?

**Comment by sethladd** [comment]
I believe this is fixed now?

cc @HansMuller

**Comment by HansMuller** [comment]
Yes, #5214 fixed the problem.

**Comment by sethladd** [comment]
Thanks!
