### ISSUE TITLE
ParentData fixes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#474]
- [ ] ~~BoxParentData.merge()~~
- [x] MultiChildLayoutParentData.merge()
- [x] MultiChildLayoutParentData.toString()
- [x] StackParentData.toString() needs to include height/width

**Comment by abarth** [comment]
> BoxParentData.merge()

Is there anything we should actually merge here?

**Comment by Hixie** [comment]
Looks like no.

**Comment by Hixie** [comment]
Though there's a TODO in that one you might want to do.

**Comment by abarth** [comment]
Yeah, I'll do that in a separate patch.
