### ISSUE TITLE
shared_preferences

### ISSUE THREAD

**Issue by DarklyCoder** [flutter/flutter#47404]

**Comment by DarklyCoder** [comment]
(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences

**Comment by peterkuch** [comment]
Could you please pub latest version shared_preferences: ^0.5.3+4
after 
- flutter clean
- flutter run
- rebuild project from xcode , android studio , vscode too  and as well as you are using

**Comment by shyammtp** [comment]
I also do have problem with new Flutter Updated v1.12.13+hotfix.5.  `SharedPreferences.getInstance();` not working. any one please help :)

I've used in pubspec.yaml:
`shared_preferences: ^0.5.6`

**Comment by DarklyCoder** [comment]
ok, tks
