### ISSUE TITLE
android_alarm_manager no longer works in background

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47406]
1. `flutter create -a java test_bg`
2. `cd test_bg`
3. add `android_alarm_manager: any` to `pubspec.yaml`
4. add to `android/app/src/main/AndroidManifest.xml` the stuff mentioned on https://pub.dev/packages/android_alarm_manager
5. delete `test/widget_test.dart`
6. update `lib/main.dart` as follows:
```dart
import 'dart:io';
import 'dart:isolate';
import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:flutter/material.dart';

void callback() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=$isolateId function='$callback'");
}

Future<void> main() async {
  runApp(MaterialApp(home: Material(child: Center(child: OutlineButton(child: Text('QUIT'), onPressed: () => exit(0))))));
  await AndroidAlarmManager.initialize();
  await AndroidAlarmManager.periodic(const Duration(minutes: 1), 0, callback);
}
```
7. `flutter run`
8. Press the QUIT button, or, once the app is running, press Q at the console.
9. `flutter logs`
10. Wait approximately one minute.

Expected results: A `Hello world!` message with various information like the isolate ID, the time, and some representation of the callback, something like that:
```
I/flutter (18608): [2019-12-18 20:48:51.063338] Hello, world! isolate=704844194 function='Closure: () => void from Function 'callback': static.'
```

Actual results:
```
E/FlutterBackgroundExecutor(17500): Fatal: failed to find callback
```

**Comment by Hixie** [comment]
cc @mklim @bkonyi @matthew-carroll

**Comment by matthew-carroll** [comment]
@bkonyi would you mind taking a look at this? I'm guessing that it's a side effect of the recent refactor.

@Hixie can you add which device(s) you replicated this on?

**Comment by Hixie** [comment]
I see this on a Lenovo TB 8504F and a Pixel 3 XL.

**Comment by Hixie** [comment]
I'm marking this product/critical since this plugin is marked as a Flutter Favorite.

**Comment by bkonyi** [comment]
I'll get on this when I'm back in the office Wednesday.

**Comment by bkonyi** [comment]
It looks like this was a result of the refactor but it's uncovered an interesting issue which we might want to account for in the engine.

The plugin was attempting to perform the callback lookup before an instance of `FlutterEngine` was created. However, the callback cache isn't populated until `FlutterMain::Init` is called, so we querying an empty map resulting in a failed lookup. We should probably check that the cache has actually been initialized when a lookup request has been issued and then throw or assert after outputting a message stating that a `FlutterEngine` instance must be created before performing a callback lookup.

**Comment by audkar** [comment]
I thought idea with new embedding was that single engine instance always be available and reused between all visible screens and services. This plugin is still going to use separate engine?
