### ISSUE TITLE
Orientationbuilder doesn't work when use StatelessWidget

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#47405]
flutter doctor

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] Connected device (1 available)

• No issues found!

**Comment by peterkuch** [comment]
Could you please use put try to put this?
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.landscapeLeft, DeviceOrientation. landscapeRight, DeviceOrientation. portraitDown]);
  //runApp(MainTabBar());
}
