### ISSUE TITLE
Calculator, iOS: odd glyph implies a missing icon?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4741]
In the calculator, on iOS: 

![screen shot 2016-06-24 at 10 54 19 am](https://cloud.githubusercontent.com/assets/5479/16346038/119041ec-39fa-11e6-9915-3281973a1e5a.png)

Notice the "x in a box" to the right of 9. That seems out of place, and seems like a placeholder for a missing icon?

**Comment by HansMuller** [comment]
That's what happens on Android if icons are missing. Typically if `uses-material-design: true` doesn't appear in the app's flutter.yaml file.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/calculator/home.dart#L207
is the line in question, the missing glyph is u232B.  Unclear what font is in use here.

**Comment by eseidelGoogle** [comment]
It's possible that our font fallback support (do we even have that anymore?) isn't working on iOS correctly.  FYI @abarth

**Comment by Hixie** [comment]
Closing this since we're not showing this demo any more and nobody else has raised this issue.
