### ISSUE TITLE
Gallery, Contacts: iOS status bar seen when contact is scrolled up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4743]
Trying to find the appropriate behavior to emulate w.r.t. the iOS status bar and content scrolling up.

The google shopping express app on iOS scrolls the app bar and iOS status bar off the screen:

![screen shot 2016-06-24 at 11 11 24 am](https://cloud.githubusercontent.com/assets/5479/16346481/6a945682-39fc-11e6-8769-a813ed5e29c0.png)

Notice how I've scrolled the contents up which moved the app bar and status bar off the screen.

The Drive app scrolls the app bar off, but leaves behind a status bar with a shadow effect:

![screen shot 2016-06-24 at 11 12 11 am](https://cloud.githubusercontent.com/assets/5479/16346515/92d2861e-39fc-11e6-81dd-e606645f3983.png)

Here's what we're doing in the contacts:

![screen shot 2016-06-24 at 11 09 50 am](https://cloud.githubusercontent.com/assets/5479/16346442/3825fa52-39fc-11e6-982f-07c20ea5f5c9.png)

Notice how we've pushed the app bar off, but we kept the status bar contents (without a background). But because the status bar text is white, and there is no explicit background for the status bar, the user can't see the status bar text (except the battery).

Options:

A) We scroll the status bar off the screen, just like scroll the app bar off. (like Express)
B) We leave behind a status bar (like Drive).
C) Other?

FWIW the Google Play Movies app on iOS also scrolls off the status bar as the content is scrolled up.

**Comment by sethladd** [comment]
made a movie of the various scrolling + iOS status bar experiences: https://www.youtube.com/watch?v=V6zTIsQasBw&feature=youtu.be

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/4630 ?

**Comment by tvolkert** [comment]
Yeah probably a dup.  Basically we need to decide what the right behavior is and what levers we expose to the Dart layer.  We might need guidance from the Material folks?

**Comment by Hixie** [comment]
Closing as dupe
