### ISSUE TITLE
Flutter couldn't find Import package with different  import format

### ISSUE THREAD

**Issue by rvhamed** [flutter/flutter#47438]
Before updating flutter I imported packages with the following line:
```
import 'package:psgholiof/src/presentation/music_list/music_item_details.dart';
```
but after the update, I get this syntax error in many of line of code:
![Screen Shot 2019-12-19 at 12 56 49 PM 1](https://user-images.githubusercontent.com/29680697/71162570-b2c9dd00-2260-11ea-927b-6020b16c9ef8.png)

I fix this error with this step:
1- remove current import line
2-press (alt + enter) on the red line and it's imported like this:
```
import 'music_item_details.dart';
```
Note: music_item.dart and music_item_details.dart imports each other.

## Logs

```
[✓] Flutter (Channel master, v1.13.3-pre.44, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.13.3-pre.44 at /Users/home/Develop/SDK_Flutter
    • Framework revision 86982e195e (2 days ago), 2019-12-17 11:07:26 -0500
    • Engine revision bdd4e4d948
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 fe9f30c389)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/home/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

```

**Comment by gloomie** [comment]
Same thing happens to me...

**Comment by gloomie** [comment]
This may be happening because at one time the name of a folder was written with a capital first letter. A "flutter clean" solved the problem for me (do it both in master and stable channels).

**Comment by zeromaro** [comment]
I've similar issue too. Currently on `Channel master, v1.13.6-pre.16`.

Imports before:
```
import 'package:flutter/material.dart';
import 'package:package_name/models/user.dart';
```

Imports now:
```
import '../../../../flutter/packages/flutter/lib/material.dart';
import '../../models/user.dart';
```

New format imports aren't recognisable by IDE (Android Studio 3.5.3) and I need to manually rewrite them.

**Comment by rvhamed** [comment]
@gloomie Flutter clean did not solve for me

**Comment by gloomie** [comment]
Master > bug
Stable upgrade > no bug
Master > bug
Master clean, upgrade, reopen vscode > no bug

Make sure you only use lower letters for all folders before performing a
clean. Clean both stable and master and reopen vscode before run.

**Comment by gloomie** [comment]
For future readers.... Turns out that git origin(github) doesn't catch caps-to-small folder name modifications that I commited from windows vscode. Maybe this was the root of the bug....

I had to run this command: 
git config core.ignorecase false
...in terminal and then change the name of the folders (to some dummy name and then again to the small lettered one) and commit again for the origin to be updated. Together with a flutter clean.

**Comment by rvhamed** [comment]
@gloomie 
This problem is not just for my packages. this issue affects libraries, such as Material, Widget,... .
below in the image, at first line material.dart imported.
   import 'package:flutter/material.dart';
but it wants to import it again with other importing format

![Screen Shot 2020-01-06 at 11 19 42 AM](https://user-images.githubusercontent.com/29680697/71803782-ea18f600-3076-11ea-9135-6dbc7d197f9c.png)

and show this error if two class imports one package with a different format

![Screen Shot 2020-01-06 at 11 24 49 AM](https://user-images.githubusercontent.com/29680697/71803887-2cdace00-3077-11ea-9340-483d85ead5b6.png)

**Comment by DanTup** [comment]
This was fixed by https://github.com/dart-lang/sdk/issues/39848 and rolled into Flutter at 1.13.6-pre.29. Is anyone still seeing this on a newer version of `master` than that?

**Comment by rvhamed** [comment]
Thank you. I didn't see this issue. I'll tell you if I see it again.
