### ISSUE TITLE
When iOS13 turned on the auxiliary function and read the content -- the function of reading the screen, it presented a page flutter many times and then stabilized and then crashed.

### ISSUE THREAD

**Issue by zw1924** [flutter/flutter#47432]
### version
```console
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```
### stack 
![image](https://user-images.githubusercontent.com/54323514/71156978-0e559400-227c-11ea-974e-b575869c417f.png)
### demo 
https://github.com/zw1924/FlutterCrashExample
### Retrieval path
Click the yellow button again and again

**Comment by iapicca** [comment]
Hi @zw1924 
the link doesn't seem to lead to a reproducible code sample,
can you please double check?
Also can you please provide your `flutter run --verbose`?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
