### ISSUE TITLE
Flutter Maven repository should support HTTPS

### ISSUE THREAD

**Issue by GerritKopp** [flutter/flutter#47452]
The [Flutter Maven repository](http://download.flutter.io) (`download.flutter.io`) can't be accessed via HTTPS because of a certificate error (wrong host). In my opinion you should be able to download the artifacts via [HTTPS](https://download.flutter.io) for security reasons. Is the repository available via another URL or can the certificate error be fixed?

**Comment by dnfield** [comment]
@blasten @kf6gpe  - we need to fix the certificate attached to `download.flutter.io`/`download.flutter.dev`.  Looks like it's using the one for `*.storage.googleapis.com`, which triggers a bunch of warnings/errors over HTTPS.

**Comment by blasten** [comment]
+1. GCP storage only supports CNAME entries for custom domains, which doesn't allow HTTPS. 
https://cloud.google.com/storage/docs/troubleshooting#https  

If we think this is critical, then we might either need to migrate to Firebase hosting as suggested in the GCP storage doc or drop the custom domain and use https://storage.googleapis.com/download.flutter.io directly.

**Comment by dnfield** [comment]
Would the setting up a load balancer option work out for us?

I think we should probably avoid firebase hosting for this - it will become tedious as we add more and more files (AFAIK it requires a complete local copy of your static assets to compare/upload - there's no way to just say "add these new assets").

If a load balancer doesn't work, I'd vote for just using the storage.googleapis.com domain directly.  Will that have any negative impact on Chinese customers though?

**Comment by skyred** [comment]
> any negative impact on Chinese customers though

Cannot speak for the future, but currently https://storage.googleapis.com/download.flutter.io works in China.

**Comment by dnfield** [comment]
@blasten what would it take to just use `storage.googleapis` directly?

**Comment by blasten** [comment]
very easily. https://github.com/flutter/flutter/blob/449f4a6673f6d89609b078eb2b595dee62fd1c79/packages/flutter_tools/gradle/resolve_dependencies.gradle#L21 and https://github.com/flutter/flutter/blob/2042c7d589e64a19fe81e20938bf2c801ad88e22/packages/flutter_tools/gradle/flutter.gradle#L44

**Comment by jmagman** [comment]
Need to update docs as well https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar

**Comment by jmagman** [comment]
Docs and sample updated.
https://github.com/flutter/website/pull/3768
https://github.com/flutter/samples/pull/355
