### ISSUE TITLE
Disabling DraggableScrollableSheet pin

### ISSUE THREAD

**Issue by MattMe99** [flutter/flutter#47460]
Hi, I'm utilizing the DraggableScrollableSheet Widget in my app and it is working very well so far.
However, when I scroll to the bottom of the sheet and try to scroll back to the initial position with a quick swipe (not by dragging it all the way) it pins itself to his maxChildSize height and I have to scroll again to keep it going.
I was wondering if it's possible to avoid that behavior.

**Comment by ciarmoli-marco** [comment]
I have the same issue, couldn't find any workaround

**Comment by dnfield** [comment]
This is by design. Otherwise, the sheet could unexpectedly close when a user swipes quickly to the top of the list. If you look at platform native widgets they basically work this way as well.
