### ISSUE TITLE
After upgrading Android Studio, flutter run is not working

### ISSUE THREAD

**Issue by mgoral2** [flutter/flutter#47466]
I decided that today I would upgrade android studio and all of the recommended upgrades for a flutter application I am working on. After doing this, when I run the app over usb on an android device with "flutter run --verbose", I get a white screen on my phone with the following error:

```Error connecting to the service protocol: failed to connect to http://127.0.0.1:63958/aZGMSZRNaEY=/```

On the following github help page(https://github.com/flutter/flutter/issues/25112) I found the solution that seems to be working for people:

"One of the causes of this error is Android 9. In this version all Unity3D http requests stopped working. Http request are disabled by default in Android 9. In flutter I installed Android 8.1. Another solution is to tweak AndoidManifest.xml adding in application usesCleartextTraffic="true""

The problem is, I am not completely familiar with android and flutter and what would be the best thing to do. Would someone mind giving me detailed instructions on how to do this and which one of these solutions would be best? I have been using Atom IDE. Thanks!

**Comment by iapicca** [comment]
Hi @mgoral2 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by mgoral2** [comment]
Hi iapicca.  This is the first time I have used github issues so hopefully I am putting my response in the right place.  Here it is:

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012,
    locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/mg8686./Downloads/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mg8686./Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G965U • 304e4a5855503098 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by mgoral2** [comment]
I figured it out.  After running flutter pub get I got the following error:  Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

I fixed by adding this line as the first line in main()
WidgetsFlutterBinding.ensureInitialized();

Thanks everyone for your help!

**Comment by mgoral2** [comment]
Last comment is the fix

**Comment by raghunath2612** [comment]
Just go to plugins and uninstall flutter plugin and restart the ide.  Now got to plugins and reinstall the flutter plugin along with dart plugin and restart the ide.

**Comment by NaseerAttari** [comment]
Update flutter and dart plugins and restart Android Studio
