### ISSUE TITLE
[iOS scroll issue] Thread 1: EXEC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#47461]
I have this widgets in a page: ` Scaffold`-> [CustomScrollView](url) ->` [SliverToBoxAdapter(), SliverList()]` and a `GoogleMaps` widget inside of the `SliverList`. When I try to scroll the app simply crash.
It is not showing any Flutter error when I run the project via IntelliJ IDEA but when I run the iOS project I get this:
`Thread 1: EXEC_BAD_ACCESS (code=1, address=0x0)`
In the logs I just see a green text: `(lldb) `

I made a video about the issue that I've shared in the Flutter's slack group: https://flutterstudygroup.slack.com/files/UGRJZ9NG5/FRUBWHV45/vid_20191218_111058.mp4

**Target Platform:**
**Target OS version/browser: **
**Devices: iPhone 6, iPhone 6s, iPhone 11**

```console
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\src\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\src\android
    • Java binary at: C:\Users\Pedro Massango\Downloads\android-studio-ide-192.5959023-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 4.0)
    • Android Studio at C:\Users\Pedro Massango\Downloads\android-studio-ide-192.5959023-windows\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Pedro Massango\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Redmi 5 Plus • 0258ff700005 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment]
Hi @pedromassango 
can you please provide your `flutter run --verbose`
and a minimal code sample  to reproduce the problem?
Also the link you share doesn't seem to be accessible w/o a slack account.
Thank you

**Comment by dnfield** [comment]
This is probably a bug in the iOS platform view implementation - can you provide a small reproduction of this (e.g. a simple app that uses the widgets you mention above in the configuration that causes a crash, along with instructions about how to interact with the app to cause the crash)?

**Comment by pedromassango** [comment]
The link is from the Flutter Study Group on slack, I'm going to share it on Google Drive.

I don't have a Macbook at home, so I will be able to share a sample project tomorrow at my office.

**Comment by pedromassango** [comment]
@dnfield here is the video url from G Drive: https://drive.google.com/file/d/1QOnbgFu8jso9ylGJb2ENHcMacZzEtwm6/view?usp=sharing

**Comment by dnfield** [comment]
Thanks! We'll still want to just see some code that reproduces it so we can further triage/create a test case.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
