### ISSUE TITLE
v1.12.13+hotfix.5   run  flutter build apk have lost some class.

### ISSUE THREAD

**Issue by zhuxiujia** [flutter/flutter#47462]
## in my  project,flutter channel stable, v1.12.13+hotfix.5:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alipay/sdk/app/EnvUtils$EnvEnum;
        at e.b.b.a$f.b()
        at g.v.i.a.a.a()
        at kotlinx.coroutines.p0.run()
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

## in my  project,flutter channel stable, v1.9.1+hotfix.6:
without any problems。

the flutter detail:
``` 
C:\Users\mayn>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = D:\Android\Android_Studio
    X Android Studio not found at D:\Android\Android_Studio
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by janmoppel** [comment]
Hello @zhuxiujia !

Thank you for posting an issue.
Can you please provide some more information, such as:
1. `flutter doctor -v` command output;
2. Minimal steps to reproduce the issue.

**Comment by dnfield** [comment]
@blasten or @mklim does this look like a dexing/proguard issue to you?

**Comment by mklim** [comment]
Yes, it looks like a proguard issue to me. `com/alipay/sdk/app/EnvUtils$EnvEnum` was referenced somewhere in the app but at runtime it didn't actually exist anywhere in the apk so there was a crash. I'm not familiar with any changes we made around proguard directly in the latest stable but @blasten may know more.

As far as I know that's not a classpath we're using in Flutter itself anywhere. @zhuxiujia thank you for the bug report, would it be possible for you to also provide a minimal reproduction case that causes this error? [Stackoverflow has a good guide on finding one.](https://stackoverflow.com/help/minimal-reproducible-example)

If you're unable to figure out a working example, it would still be helpful here to have your `pubspec.lock` if possible. It's likely that this class is coming from a plugin indirectly and something about `v1.12` is resulting in it being stripped out of the APK when it shouldn't be.

**Comment by zhuxiujia** [comment]
> Yes, it looks like a proguard issue to me. `com/alipay/sdk/app/EnvUtils$EnvEnum` was referenced somewhere in the app but at runtime it didn't actually exist anywhere in the apk so there was a crash. I'm not familiar with any changes we made around proguard directly in the latest stable but @blasten may know more.
> 
> As far as I know that's not a classpath we're using in Flutter itself anywhere. @zhuxiujia thank you for the bug report, would it be possible for you to also provide a minimal reproduction case that causes this error? [Stackoverflow has a good guide on finding one.](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> If you're unable to figure out a working example, it would still be helpful here to have your `pubspec.lock` if possible. It's likely that this class is coming from a plugin indirectly and something about `v1.12` is resulting in it being stripped out of the APK when it shouldn't be.

Hello :
github have a  library  named  "https://github.com/OpenFlutter/tobias"
in this project   "tobias/example/lib/main.dart"

**Comment by zhuxiujia** [comment]
> Hello @zhuxiujia !
> 
> Thank you for posting an issue.
> Can you please provide some more information, such as:
> 
> 1. `flutter doctor -v` command output;
> 2. Minimal steps to reproduce the issue.

hello,
How to close dexing/proguard ？

**Comment by thanhhai08sk** [comment]
You can disable proguard for example:
` build apk  --no-shrink`

**Comment by zhuxiujia** [comment]
> You can disable proguard for example:
> ` build apk --no-shrink`

Thank you：
command `flutter  build apk --no-shrink` it work successful,
and  how to  define in  pubspec.yaml?   
every time build apk  need append --no-shrink  ?

**Comment by zhuxiujia** [comment]
> You can disable proguard for example:
> ` build apk --no-shrink`
Thank you：
in android/build.gradle
```
 buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            shrinkResources false
            zipAlignEnabled false
            minifyEnabled false
        }
```
is works.and  run  successful.

**Comment by rakib205** [comment]
@zhuxiujia you saved my ass. Thanks
