### ISSUE TITLE
Regression in analyzer_benchmark_flutter_repo_watch_maximum

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#47469]
Not sure what's up here. The first CL it occurred in was a comment rename, so that can't be it. https://github.com/flutter/flutter/pull/46660. Maybe it needs to be re-baselined?

**Comment by jason-simmons** [comment]
Tried to bisect the change in Dart analyzer performance.  Looks like it started at https://github.com/dart-lang/sdk/commit/ae3973da40237d038e3afa5fd525a1b33ee543ed

**Comment by godofredoc** [comment]
This seems like a regression in dart, removing team:infra

**Comment by kf6gpe** [comment]
This has since dropped to below basline; closing.
