### ISSUE TITLE
[devicelab] Upgrade Xcode

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#47485]
Currently most of the mac bots are using Xcode 11.0, we need to upgrade them in order to support iOS 13+.

/cc @godofredoc @keyonghan

**Comment by digiter** [comment]
The Xcode has been upgraded to 11.3 on mac1, mac5, mac8. If that works well, we can upgrade other machines. FYI, there's a working copy of Xcode 11.3 under "~/support" directory on the bridge.

**Comment by godofredoc** [comment]
All the devicelab machines are now using xcode 12.3.
