### ISSUE TITLE
Gallery: remove INTERNET permission if not needed

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4749]
Getting ready for a release, we're reviewing our permissions usage. The gallery currently uses the INTERNET permission, but we're not sure we actually need it.

If we don't need it, let's remove it.

If we require it, what is it used for?

Thanks!

**Comment by eseidelGoogle** [comment]
It used to be required to load itself off of the host back in the SkyShell days.  I suspect it's no longer needed.  That or may have just been copied from Stocks which does need it. :)

**Comment by eseidelGoogle** [comment]
Actually, it looks like the template includes it:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/android/AndroidManifest.xml.tmpl
Which is probably doesn't need to.

**Comment by HansMuller** [comment]
Someone prototyping an application that used NetworkImages might appreciate the default. Unless the failure mode makes it clear that updating the manifest file is what needs to be done (that might be complicated).

Perhaps the NetworkImage dartdoc should mention the connection to
```
   <uses-permission android:name="android.permission.INTERNET"/>
```

**Comment by HansMuller** [comment]
If the internet permission is removed the `--debug` mode observatory connection fails:
```
--------- beginning of main
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=8313, uid=10082 that is not exported from uid 10061
I/flutter : Could not start Observatory HTTP server:
I/flutter : SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
I/flutter : #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:505)
I/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1204)
I/flutter : #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
I/flutter : #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
I/flutter : #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
I/flutter : #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
I/flutter : #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
I/flutter : #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
I/flutter : #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/flutter : #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
I/flutter : #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
I/flutter : #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/i
Timed out while waiting for a debug connection.
Error running application on Nexus 5.
```

**Comment by eseidelGoogle** [comment]
We insert the debugging permission only for debug bulids already via aapt --debug-mode:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_apk.dart#L107
Unfortunately I don't see a command line to insert arbitrary permissions, as we could also take the approach of inserting internet only for debug mode.
http://manpages.org/aapt

**Comment by sethladd** [comment]
Sounds like @jason-simmons has a solution for this. We'll remove the INTERNET permission when building the deployable APK.
