### ISSUE TITLE
Add statistics about the net cost/benefit of each RepaintBoundary

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#475]
Adding repaint boundaries to your tree is magical performance dust.  During the paint walk, we can gather data about which repaint boundaries are actually saving you anything.  We should gather that data and surface it to developers somehow.

**Comment by Hixie** [comment]
What exactly is the data we should collect? I'm happy to implement it but I'm not sure what it is that would be actionable.

**Comment by abarth** [comment]
A RepaintBoundary is good if the two sides of the repaint boundary often repaint at different times.  As a rough cut, I'd take the ratio of the number of times one side or the other repaints to the number of times both side repaint together.

There's another issue to consider, which is whether to bake textures at a given boundary, but IMHO we should first focus on finding good boundaries between subtrees that often repaint independently.
