### ISSUE TITLE
dart:ui canvas.drawColor(color, BlendMode.clear) memory leak

### ISSUE THREAD

**Issue by ykmnkmi** [flutter/flutter#47513]
my current task is fill background with white color 
```dart
canvas.drawColor(const Color(0xFFFFFFFF), BlendMode.clear);
```
and i switch the blend modes src, srcOver, color & clear, they all paint a black background.
when i use BlendMode.clear my browser (Chrome & Firefox) takes up all my memory on the PC.

```
[√] Flutter (Channel master, v1.13.4-pre.12, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.0)
[√] Connected device (2 available)
```
my task solved with
```dart
canvas.drawRect(rect, Paint()..color = const Color(0xFFFFFFFF));
```

**Comment by ferhatb** [comment]
Fixed & added tests in https://github.com/flutter/engine/pull/15153 , please retry and let us know if you are fine now using master channel after next engine roll into flutter.

**Comment by ykmnkmi** [comment]
BlendMode.clear same, but faster.

**Comment by ferhatb** [comment]
Verified that BlendMode.clear throws unsupported on web exception. Deprioritized.

**Comment by pedromassangocode** [comment]
Hi @ykmnkmi 
Are you still facing this issue?

**Comment by ykmnkmi** [comment]
Hi @pedromassangocode, no.

**Comment by pedromassangocode** [comment]
Hi @... 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
