### ISSUE TITLE
lib not found for -lshared_references on xcode

### ISSUE THREAD

**Issue by AlphaBlend1975** [flutter/flutter#47520]
Dear all,

I have some problem when build flutter project form xcode.
I have create from intellij with shared_references.
but error come when build in xcode

try delete pod file and install but not work
pod version 1.8.4
xcode version 11.3
flutter  version 1.12.13
dart version 2.7.0

![Screen Shot 2562-12-20 at 16 03 48](https://user-images.githubusercontent.com/7919120/71243629-568bb980-2343-11ea-8f67-f13fa373bf74.png)

**Comment by iapicca** [comment]
Hi @AlphaBlend1975 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by AlphaBlend1975** [comment]
I am using IntelliJ macos. it can be run on iphone emulator working perfect.
but when i using xcode open runner.xcodeproj then try to build on generic device and select real device. 
it error like provided image. 
already run flutter doctor -v,  flutter run --verbose no issue. run success and build runner.app 

problem only build from xcode.
android emulator working perfect on intellij. 
shread_preferences exist in folder {project}\ios\Pods\Headers\Public\shared_preferences\shared_preferences.modulemap"

How to next step? please provide.
Thank you.
[verbose.txt](https://github.com/flutter/flutter/files/3988918/verbose.txt)

**Comment by jmagman** [comment]
Can you confirm you have Runner.xcworkspace open and NOT Runner.xcodeproj?

See https://github.com/flutter/flutter/issues/10770.

**Comment by AlphaBlend1975** [comment]
> Can you confirm you have Runner.xcworkspace open and NOT Runner.xcodeproj?
> 
> See #10770.

Wow... i am mistake.
Build from Runner.xcodeproj not Runner.xcworkspace. 
**BUT**
Open from Runner.xcworkspace setup everything from General and Build Settings to correction path
Same error . Parse Issue show "Module 'shared_preferences' not found GeneratePluginRegistration.m

**Comment by AlphaBlend1975** [comment]
> > Can you confirm you have Runner.xcworkspace open and NOT Runner.xcodeproj?
> > See #10770.
> 
> Wow... i am mistake.
> Build from Runner.xcodeproj not Runner.xcworkspace.
> **BUT**
> Open from Runner.xcworkspace setup everything from General and Build Settings to correction path
> Same error . Parse Issue show "Module 'shared_preferences' not found GeneratePluginRegistration.m

**UPDATE**

after run pod install in ios this issue  is gone.

Solution to work 

-  Open Runner.xcworkspace
-  Setup everything from General and Build Settings to correction path
-  run "pod install" in {project}/ios 

Now working perfected..
Thank you very much.

**Comment by iapicca** [comment]
Hi @AlphaBlend1975 
I'm glad that you solved the issue,
thank you for letting us know
