### ISSUE TITLE
Need Overlay missing public method to check whether OverlayState contains entry

### ISSUE THREAD

**Issue by michaeldlfx** [flutter/flutter#47532]
## Steps to Reproduce

When inserting an `OverlayEntry` into the `OverlayState` provided by the `MaterialApp`, there is no way of verifying whether the Overlay _already_ contains the `OverlayEntry` prior to doing the `Overlay.of(context).insert(entry)` call.

1. Say you have an `IconButton` in the `AppBar`, where `onTap()` inserts an `OverlayEntry`
2. The displayed `OverlayEntry` does not end up covering (being on top of, thus hiding) the AppBar. So the `IconButton` is still visible.
3. When triggering the `onTap()` of the `IconButton` once more, the following exception is thrown:

```
flutter: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 302 pos 12: '!_entries.contains(entry)': The specified entry is already present in the Overlay.
```

**Target Platform:** iOS, Android
**Target OS version/browser:** -
**Devices:** All

## Logs

```
flutter: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 302 pos 12: '!_entries.contains(entry)': The specified entry is already present in the Overlay.
```

## Suggestions

1. Handle the check internally within the `insert()`, `insertAll()` methods, which would check whether the entry is already contained within `_entries`. 
If `_entries` already contains the `entry` to be inserted, do nothing, otherwise, insert it.
This solution has the advantage of leaving the OverlayState API as is. 

2. Provide a public method to `OverlayState`, something along the lines of: 

```
containsEntry(OverlayEntry entry) {
     return _entries.contains(entry);
}
```

3. A public method which returns all entries currently contained, e.g.` getEntries()`  would also be a valuable solution:

` 
 OverlayState.getEntries().contains(entry) ` 

This would also make it possible to check whether any / which entries are contained, which would be great.

**Comment by michaeldlfx** [comment]
It is also impossible to check whether the ` OverlayState` contains _any_ entries at all.

An equivalent of ` isEmpty() `, e.g. ` containsEntries() ` , would be really valuable.

**Comment by chunhtai** [comment]
The widget that insert the overlay entry should keep track of what overlay entry it has inserted (In your case the parent of IconButton). Otherwise, it may leak overlay entry after it is disposed.

**Comment by michaeldlfx** [comment]
@chunhtai That's how I've been handling it so far, but it's messy. The overlay _is_, on a meta level, a container data structure (like arrays, lists, sets, maps,...) , in the sense that contains elements. Thus, it should have a `contains(element)` method.

The argument that you are making would imply that all lists, sets and map data structures should not have a `contains(element)` method, and that the users of said data structures would have to keep track of what elements have already been inserted. This would imply a list to keep track of a list, etc.

If your concern is that there should not be a leak, a simple method with a boolean return type, say `contains(element)`, would do the trick. 
It would also make it a simple task for the parent widget to keep track of has been inserted into the overlay, wouldn't you agree?

**Comment by Timoteohss** [comment]
It's really counterintuitive keeping track of OverlayEntries outside the scope of OverlayState.

As @michaeldlfx mentioned, I can't really see any leaks by having a simple boolean returning if an entry is already present on my overlay.

**Comment by chunhtai** [comment]
> @chunhtai That's how I've been handling it so far, but it's messy. The overlay _is_, on a meta level, a container data structure (like arrays, lists, sets, maps,...) , in the sense that it contains elements. Thus, it should have a `contains(element)` method.
> 
> The argument that you are making would imply that all lists, sets and map data structures should not have a `contains(element)` method, and that the users of said data structures would have to keep track of what elements have already been inserted. This would imply a list to keep track of a list, etc.

Knowing which elements has been inserted into array, list, map is not a requirement to use these data structure. There are in fact cases we use this data structure to figure out that for us (See all the interview questions). 

> If your concern is that there should not be a leak, a simple method with a boolean return type, say `contains(element)`, would do the trick.
> It would also make it a simple task for the parent widget to keep track of what has been inserted into the overlay, wouldn't you agree?

The problem with providing this method is it will be error-prompt for developers who do not familiar with how overlay works. It will be discouraging developers to keep track which overlay entries they have inserted because they think they can rely on this method to verify them if they want. This will be source of leaking overlay entries if developers are not actively keeping track of them.

**Comment by benPesso** [comment]
@chunhtai Adding a `contains` method will not lead to what you are describing, as it is still actively requiring the developer to make sure there isn't a matching `OverlayEntry` already in the pipeline. 

Aside from that, the code is already making this check with the assertion, so why not expose it to the developer to prevent a possible assertion failure?

**Comment by chunhtai** [comment]
I am still not convinced we should add the `contains` method. If there is any point in a widget lifecycle that you aren't sure whether the overlay entry it owns is in the overlay or not, that means there is something wrong in your app.
