### ISSUE TITLE
Flutter simple_slider installation problem

### ISSUE THREAD

**Issue by aspcsharp9** [flutter/flutter#47545]
flutter_cache_manager and cached_network_image is successfully instaled.

flutter_cache_manager: ^1.1.3 cached_network_image: ^1.1.3

When try install simple_slider: ^0.0.2 get below error

````
Because every version of simple_slider depends on cached_network_image ^0.4.1 and first_flutter_app depends on cached_network_image ^1.1.3, simple_slider is forbidden.

So, because first_flutter_app depends on simple_slider ^0.0.2, version solving failed.
pub get failed (1)`
```

**Comment by JonathanMonga** [comment]
Try to set the version of simple_slider  : any

**Comment by iapicca** [comment]
Hi @aspcsharp9 
[simple_slider](https://pub.dev/packages/simple_slider) [[github](https://github.com/eddywm/simple_slider/issues)], 
[flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) [[github](https://github.com/renefloor/flutter_cache_manager)] 
and [cached_network_image](https://pub.dev/packages/cached_network_image) [[github](https://github.com/renefloor/flutter_cached_network_image/issues)]
are 3rd party plugins, you might want to open an issue on the dedicated github.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
