### ISSUE TITLE
TextOverflow.ellipsis should have "start", "middle" and "end"

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#47543]
Currently there's just `TextOverflow.ellipsis`, which puts `...` at the end of the text. There should also have `TextOverflow.ellipsisStart` and `TextOverflow.ellipsisMiddle` as sometimes we want to show the beginning and the end of the text, or just the end, examples:

`TextOverflow.ellipsisMiddle`:

```
verylonglonglongemail@gmail.com -> verylonglo...mail@gmail.com
``` 

`TextOverflow.ellipsisStart`:

```
verylonglonglongemail@gmail.com -> ...longemail@gmail.com
``` 

Then `TextOverflow.ellipsis` could be deprecated to `TextOverflow.ellipsisEnd`.

**Comment by iapicca** [comment]
Hi @feinstein 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45336) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
