### ISSUE TITLE
flutter build ios-framework should optionally produce a Flutter.podspec instead of Flutter.frameworks

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#47548]
## Use case

Currently when generating frameworks from a Flutter module to be embedded into a host app, `flutter build ios-framework` generates Flutter.frameworks or a Flutter.xcframework, which need to be distributed to all host app developers so it can be linked and embedded in the host app.  These files are large (30+MB), and it becomes tricky to distribute, particularly if CI is involved.

These engine frameworks do not need to be generated by the module, however.  The right version of the engine used to compile the App.framework can be downloaded by each developer/CI bot at https://storage.googleapis.com/flutter_infra/flutter/<engine version>/ios*/artifacts.zip.

## Proposal

If the host app uses CocoaPods, the engine Flutter.framework can be downloaded via a generated remote `:http` podspec.  Developers would not need to copy around the 30+MB Flutter.frameworks or Flutter.xcframeworks.

**Comment by xster** [comment]
Can we add this as an option B2 to https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode?

**Comment by jmagman** [comment]
> Can we add this as an option B2 to https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode?

I created https://github.com/flutter/flutter/issues/47696, I think we should wait until it hits stable?
