### ISSUE TITLE
Flutter 1.12 is not linking to iOS device on the latest 13.3 update. 13.2 seems to be working though.

### ISSUE THREAD

**Issue by DjangoOverloard** [flutter/flutter#47541]
I've just updated my iPhone to iOS 13.3 and it seems that flutter is not syncing to it, and it stays in 'waiting for observatory port' mode. However, on my iPad with 13.2 everything seems to be working fine. So as a workaround I would suggest not to update or to find a way to rollback to previous iOS release.

**Comment by iapicca** [comment]
Hi @DjangoOverloard  
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by DjangoOverloard** [comment]
This problem seems to be connected with other issue, presumably on my hardware side. I've already resolved it by changing cables.
