### ISSUE TITLE
Dependency problem in graphql_flutter-2.1.0 

### ISSUE THREAD

**Issue by AhmedAlaa96** [flutter/flutter#47542]
Hey, everybody 
I have a problem with dependency problem in graphql_flutter-2.1.0 I was using **flutter_v1.9.1+hotfix.6**  until this morning I made `flutter upgrade`  and now have in my `stable channel`  **flutter_v1.12.13+hotfix.5**

my code was work well but now get this error :

````
/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'flutter\packages\flutter_tools\gradle\flutter.gradle' line: 801

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`
```
what should I do downgrade to **flutter_v1.9.1+hotfix.6** or do what ?

**Comment by iapicca** [comment]
Hi @AhmedAlaa96 
[graphql_flutter](https://pub.dev/packages/graphql_flutter) is a 3rd party plugin,
you may want to open an issue in the dedicated [github](https://github.com/zino-app/graphql-flutter/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
