### ISSUE TITLE
Add2App on iOS doesn't show symbolicated stack traces in Xcode when a crash occurs in Flutter in Debug builds

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#47540]
The documentation here https://github.com/flutter/flutter/wiki/Crashes suggests
```
The dSYM file for App.framework (which contains the app-specific code) can be located in the directory of your app under build/dSYMs.noindex/App.framework.dSYM for release and profile builds created with flutter build ios.
```
However, in an Add2App flutter module's .ios/Flutter/ directory, the `App.framework.dSYM` is missing.

Also, when building in debug, whenever a crash does happen in the Flutter framework, there is no useful stack trace, and I'm not sure how to get those symbols.

**Comment by dannyvalentesonos** [comment]
@dnfield  Any suggestions for this?
Thanks

**Comment by dnfield** [comment]
I think it should still show up in your `build` directory for the Flutter module.  Is it not?

**Comment by dannyvalentesonos** [comment]
Ah yes, you are right! Thanks, I hadn't noticed that.

Do you have any thoughts on the Debug case? It would be nice to get useful stack traces too in Debug so we can report crashes with good information.

**Comment by dnfield** [comment]
You should be able to load the symbols in Xcode when debugging the app. There's probably some way we can make that better, but I'm not entirely sure.  Maybe @xster or @chinmaygarde would know?

**Comment by dnfield** [comment]
Or @jmagman

**Comment by dannyvalentesonos** [comment]
Would it be possible to have a Flutter.Framework.dSYM file created? I think that would cause XCode to load it automatically.
It might help to also note that we do not use cocoapods, to that might also be something that pods would do automatically, and I'm just missing one step to generate that file?

**Comment by dannyvalentesonos** [comment]
Oh, and I'd like to mention, while we're on the topic, that for some reason, starting with Flutter 1.10 (I think), the `flutter` executable inside the artifacts/engine/ios-release/Flutter.framework is 368MB in size. Flutter 1.9 didn't have this issue. 
Once we build our app though, the app doesn't seem to increase any bigger than before, so I'm not sure what all that extra size is for, but does this need to be bugged up separately, or is it expected?

**Comment by dnfield** [comment]
Expected - see https://github.com/flutter/flutter/issues/47101

**Comment by dannyvalentesonos** [comment]
Sweet, thanks @dnfield . I have to admin I had a a moment of panic when I did first see this a few weeks ago, but once I verified our final app size didn't increase, I figured there had to be an explanation.
Thanks for linking that!

**Comment by dannyvalentesonos** [comment]
@dnfield Should we rename this bug seeing you told me where to find the dSYM file in Release builds?
This bug can remain open specifically for how to get debug information with Add2App debug builds.

**Comment by dnfield** [comment]
Sounds good to me

**Comment by dannyvalentesonos** [comment]
> I think it should still show up in your `build` directory for the Flutter module. Is it not?

@dnfield I've just updated to the latest 1.16.2 dev build, and now the App.framework.dSYM file is no longer anywhere to be found when building the Add2App module. It's not in the `build` or `.ios` directories.

This is now breaking our builds. Do you have any suggestions for this?

Thanks

**Comment by dnfield** [comment]
/cc @jonahwilliams 
Do you need these symbols to do debugging?  Jonah and I were discussing this recently and the symbols ended up getting dropped with the idea that they're not going to be all that helpful since all the lines would point to generated assembly.

**Comment by dannyvalentesonos** [comment]
Well we are just including all symbols for Flutter in Firebase crashlytics in case any crashes happen in Flutter code. If the symbols for the App framework aren't going to be useful, then I'm totally ok with dropping it.
Thanks.

**Comment by dnfield** [comment]
If you're seeing any negative impact please let us know.  It's definitely possible to get them back.

**Comment by xster** [comment]
Discussion was on https://github.com/flutter/flutter/pull/49628. But it may not be relevant for you @dannyvalentesonos. You've used Flutter.framework and App.framework interchangeably but they're following 2 different processes. Flutter.framework's dSYM are stripped by our build servers. Your local tools aren't involved. App.framework was where we removed the dSYM recently. It was generally useful for me to have the symbols from the Dart compiled binaries to use Instruments etc. But it should be very unlikely you end up seeing a crash stack inside App.framework. If you do, it means the Dart compiler produced something wrong. It's much more likely that you find a Flutter.framework crash in the engine. 

Can you clarify?

**Comment by xster** [comment]
If you really need it, remove this line https://github.com/flutter/flutter/pull/49628/files#diff-77d60a41797d03aa9a7de0c742b17ef1R140

**Comment by dannyvalentesonos** [comment]
@xster It's totally fine to not have it. I just wasn't sure if it was needed, as we were uploading it for crashlytics purposes, but if it's not important, I'm fine with that. Thanks!

**Comment by jmagman** [comment]
Let's fix the wiki text then.

**Comment by jmagman** [comment]
Done, see https://github.com/flutter/flutter/wiki/Crashes/f393b795c90b81f79c61b59bb0f6ac4a8ba92fc9.

Closing!
