### ISSUE TITLE
--local-engine on a Fuchsia target should not require a host_* engine

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47550]
Steps:

- Try to run a Flutter app on a Fuchsia device with the `--local-engine` flag, but with not corresponding host variant built
- Observe error message.

```
$ flutter run --local-engine=fuchsia_debug_arm64
No Flutter engine build found at ..../host_debug
```

This should not be required for fuchsia.

/cc @gw280 @zanderso

**Comment by jonahwilliams** [comment]
Why wouldn't it be? We use the host side engine to run the dart tooling

**Comment by dnfield** [comment]
But it's built as part of the fuchsia target

**Comment by jonahwilliams** [comment]
What is? The Dart vm build for an arm64 device can't run on the host machine

**Comment by dnfield** [comment]
It ends up in `out/fuchsia_debug_arm64/clang_x64/dart` for example.  It's the host dart.  We don't do this on other platforms.

Maybe the rule should be that if there's a dart executable next to the gen_snapshot executable, don't require host_*.

Fuchsia is an oddball here, since on the other targets we don't build host dart.

**Comment by dnfield** [comment]
compare the directory listing of `android_release_arm64/clang_x64`:
```
$ ll android_release_arm64/clang_x64/  
total 36056
drwxr-xr-x   3 dnfield  primarygroup    96B Feb  4 01:37 gen
-rwxr-xr-x   1 dnfield  primarygroup   7.6M Feb  4 01:49 gen_snapshot
-rw-r--r--  11 dnfield  primarygroup   9.9M Dec 23 10:41 icudtl.dat
drwx------   4 dnfield  primarygroup   128B Feb  4 01:37 obj
-rw-r--r--   1 dnfield  primarygroup    26K Feb  4 02:13 toolchain.ninja
```

vs Fuchsia:

```
$ ll fuchsia_debug_arm64/clang_x64                                                                                                                 ✔  5933  14:37:21
total 310424
-rwxr-xr-x   1 dnfield  primarygroup    28M Feb  5 09:52 dart
drwxr-xr-x   5 dnfield  primarygroup   160B Jan 31 22:11 dart_runner_patched_sdk
drwxr-xr-x   6 dnfield  primarygroup   192B Jan 31 22:11 flutter_patched_sdk
drwxr-xr-x   5 dnfield  primarygroup   160B Jan 31 22:11 flutter_runner_patched_sdk
-rwxr-xr-x   2 dnfield  primarygroup    33M Feb  5 09:52 flutter_tester
drwx------  14 dnfield  primarygroup   448B Jan 31 22:40 gen
-rw-r--r--   1 dnfield  primarygroup   4.4M Feb  5 09:52 gen_kernel_bytecode.dill
-rwxr-xr-x   2 dnfield  primarygroup   8.6M Feb  5 09:51 gen_snapshot
-rw-r--r--  11 dnfield  primarygroup   9.9M Dec 23 10:41 icudtl.dat
drwx------   5 dnfield  primarygroup   160B Jan 31 22:08 obj
-rw-r--r--   1 dnfield  primarygroup   1.5M Feb  5 12:23 toolchain.ninja
-rw-r--r--   1 dnfield  primarygroup   875K Feb  5 09:51 vm_outline_strong.dill
-rw-r--r--   1 dnfield  primarygroup   875K Feb  5 09:51 vm_outline_strong_stripped.dill
-rw-r--r--   1 dnfield  primarygroup   5.7M Feb  5 09:51 vm_platform_strong.dill
-rw-r--r--   1 dnfield  primarygroup    53M Feb  5 09:52 vm_platform_strong.dill.S
-rw-r--r--   1 dnfield  primarygroup    37K Feb  5 09:51 vm_platform_strong.dill.d
-rw-r--r--   1 dnfield  primarygroup   2.7M Feb  5 09:51 vm_platform_strong_stripped.dill
-rw-r--r--   1 dnfield  primarygroup    37K Feb  5 09:51 vm_platform_strong_stripped.dill.d
```

**Comment by zanderso** [comment]
I'd like to avoid adding special cases for Fuchsia to the tool in places where the other platforms we target are treated in a uniform way. If all the platforms we target no longer have the requirement that there is an adjacent `host_` build, then we can migrate the tool's engine artifact code all at once.

**Comment by dnfield** [comment]
This could be implemented without special casing Fuchsia by just checking if the `dart` executable exists next to `gen_snapshot` - but I do not regard this as an important feature or anything that should be prioritized.  I would not be upset if it got closed as won't fix - debug unopt is quick to build.

That said, it could be more problematic down the line for a developer who can't use GOMA.  But they could get around it by symlinking stuff locally.

**Comment by dnfield** [comment]
I no longer think this should be our concern. @arbreng @chaselatta feel free to re-open if I'm closing prematurely and this would be important for Fuchsia developer workflows.
