### ISSUE TITLE
Improve searchability of Dash docset

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#47553]
Flutter's Dash docset does not properly index members of top-level elements (classes, enums). 

To demonstrate, we can look at how Dash indexes `dart:core` through its native Dartdoc support. 

I bring up Dash, type `RegExp.`, and see that the class and its members are enumerated:

<img width="393" alt="Screen Shot 2019-12-20 at 2 06 54 PM" src="https://user-images.githubusercontent.com/42326/71295742-107a2a00-2332-11ea-93a6-71d1943ff787.png">

Now, the same with the Flutter docset (which also indexes `RegExp`):

<img width="398" alt="Screen Shot 2019-12-20 at 2 08 12 PM" src="https://user-images.githubusercontent.com/42326/71295781-37386080-2332-11ea-9e52-d165d52d8821.png">

No members found.

But the type is indexed, here's what we see when we remove the trailing `.`:

<img width="398" alt="Screen Shot 2019-12-20 at 2 09 52 PM" src="https://user-images.githubusercontent.com/42326/71295828-71096700-2332-11ea-84dc-df684f4ca27f.png">

Class and constructor descriptions.

We aren't seeing the members because Flutter's SQLite index is malformed. Instead of including a fully-qualified name of each member, it includes a simple identifier. 

Compare:

<img width="430" alt="Screen Shot 2019-12-20 at 2 14 45 PM" src="https://user-images.githubusercontent.com/42326/71296042-1b818a00-2333-11ea-9cf7-26b85b4865b8.png">

with Dash's native dartdoc support: 

<img width="583" alt="Screen Shot 2019-12-20 at 2 12 37 PM" src="https://user-images.githubusercontent.com/42326/71295945-ce9db380-2332-11ea-85f1-d3e884d50929.png">

------------------

I've done a bit of research into how to correct the indexes, but so far have come up short. Afaict, the Dashify tool being used to generate the index isn't sufficient to pull out the necessary information, unless we preprocess the dartdoc html to include the qualified name in a single text node or attribute.

The preprocessing step could be easy, though. The breadcrumbs and `kind-*` classes provide enough information.

Thoughts?

Related to: https://github.com/flutter/flutter/issues/9955
cc @gspencergoog

**Comment by gspencergoog** [comment]
It seems to me that it wouldn't be too hard to add an attribute that dartdoc writes out as part of each title that includes the fully-qualified path.

@jcollins-g, what do you think?

**Comment by huycozy** [comment]
@shyndman I can't find `Flutter docset` on [Dash](https://kapeli.com/dash). Not sure if it's available currently, could you check this issue again?

**Comment by gspencergoog** [comment]
@huycozy It's not available from Dash directly.  You have to add it with the feed URL:

- Stable channel Dash XML configuration URL: [api.flutter.dev/offline/flutter.xml](https://api.flutter.dev/offline/flutter.xml)
- Master channel Dash XML configuration URL: [master-api.flutter.dev/offline/flutter.xml](https://master-api.flutter.dev/offline/flutter.xml)

**Comment by huycozy** [comment]
@gspencergoog Thank you but I can't figure out how to add it. Could you be more specific? Also, I am classifying this issue (to a specific team), do you have idea on which team this issue should belong to?

**Comment by huycozy** [comment]
Re-opening the issue for further action. Also, this issue seems to belong to the infra team but I'm not sure 100%.

**Comment by Hixie** [comment]
This is where we're creating the docset: https://github.com/flutter/flutter/blob/main/dev/tools/create_api_docs.dart#L362-L363

**Comment by Hixie** [comment]
`dashing` is github.com/technosophos/dashing

**Comment by Hixie** [comment]
I have no idea how we're supposed to hold the `dashing` tool to make this work, or whether it's a bug in our holding of the tool or a bug in `dashing`.

**Comment by Hixie** [comment]
Filed https://github.com/technosophos/dashing/issues/66 upstream for now.

**Comment by Hixie** [comment]
No movement on upstream bug, let's wait until December to see what happens.

**Comment by goderbauer** [comment]
(triage): There doesn't seem to do much from our end and an upstream bug has been filed. I am closing this.
