### ISSUE TITLE
Embedder API must expose the Vulkan renderer config.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#47562]
Currently, only the software and OpenGL renderers are exposed via the Embedder API. This will need a new renderer config for both root surface rendering and custom compositor backing stores in the stable embedder API.

**Comment by safasofuoglu** [comment]
@arbreng A use case that would enable a lot of possibilities would be for the non-flutter, embedding part to be able to draw onto the same vulkan surface, below and/or above flutter. Is there an intention to enable such use case?

**Comment by arbreng** [comment]
> @arbreng A use case that would enable a lot of possibilities would be for the non-flutter, embedding part to be able to draw onto the same vulkan surface, below and/or above flutter. Is there an intention to enable such use case?

Yes, we will definitely be able to do stuff like that once the migration is complete.  Would be great for debugging.

You can try it out now if you build the fuchsia shell with the --no-legacy flag
