### ISSUE TITLE
When ListTil‘s subtitle content is too much, using TextOverflow.ellipsis is invalid #47083

### ISSUE THREAD

**Issue by icodeing** [flutter/flutter#47566]
When ListTil‘s subtitle content is too much, using TextOverflow.ellipsis is invalid #47083
---------------------------------------------------------------------------------------------------------
Sorry, after the feedback of @kf6gpe , I tried to reopen the issue #47083, but I did not have the operation button to reopen the issue, so I could only reopen an issue。

**Comment by iapicca** [comment]
Hi @icodeing 
I'm reopening you initial issue 
since it's very recent and 
no info are provided in the current one.
