### ISSUE TITLE
Isolate doesn't delete when I clicked the back button of android platfrom

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#47569]
All the flutter application doesn't delete the isolate created by user when user clicked the back button of system on the andorid platform, but the main isolate is deleted, so when I click the app to show up again, there will be three isolates now. 
can the flutter engine can delete the user isolate automatic just as the main one,  if not , I have to add listener to the back button, it is more complicated now from the app developer now.  can we set the flag when we create it?

**Comment by iapicca** [comment]
Hi @ping996 
for the isolate to be closed by the navigator
largely depends from your code,
could post  a minimal code sample?

Isolates in flutter can be simplified using [compute](https://api.flutter.dev/flutter/foundation/compute.html) 
you may want to take a look at that.

Can you also provide your `flutter doctor -v` ?
Thank you

**Comment by ping996** [comment]
I means we can get a simple way to delete the isolate when created, If I don't use the navigator,  the compute will be existed if the callback done? But I want to use the isolate as a thread to do some logic with my APP whole life, so I think I must take care of the isolate of the APP lifecycle.

C:\Users\Administrator> flutter doctor -v
[√] Flutter (Channel master, v1.13.4-pre.9, on Microsoft Windows [Version 10.0.17763.615], locale zh-CN)
    • Flutter version 1.13.4-pre.9 at C:\flutter-git\flutter
    • Framework revision e3c8ecaf7f (3 days ago), 2019-12-19 14:27:35 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.812

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.615]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by iapicca** [comment]
Hi @ping996 
does this [code ](https://gist.github.com/iapicca/b2e706814f510b769e4fe7f3f0d911d2)represent the issue you described?
thank you

**Comment by ping996** [comment]
Thanks for you kindly reply, I think your code is a best way to manage the isolate lifecycle now. I will flow your suggestion.
