### ISSUE TITLE
rev alpha channel

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4756]
It's been 19 days since we rev'd the alpha channel, and the last atom plugin can no longer launch flutter apps when used with alpha (we get a npe trying to access a debuggingEnabled field).

**Comment by Hixie** [comment]
Feel free to rev the alpha channel whenever you feel things are stable -- see https://github.com/flutter/flutter/wiki/Release-process for the steps to do it.

**Comment by abarth** [comment]
Done.
