### ISSUE TITLE
example/hello_world README.md formatting can be improved

### ISSUE THREAD

**Issue by adarshbalu** [flutter/flutter#47579]
The headings and code in the readme are not well organized and are not readable. Using the correct markdown syntax we can solve this issue.

**Comment by adarshbalu** [comment]
I have forked and made a better version of it.

**Comment by adarshbalu** [comment]
Can i do anything now ?

**Comment by kf6gpe** [comment]
Not sure if the framework team can take on the PR from @adarshbalu or not --- but we should either take this or close it as non-actionable.

**Comment by TheBiirb** [comment]
@kf6gpe Should I make a new PR with the same changes as the closed one since it was approved already?

**Comment by kf6gpe** [comment]
Sure thing! That would be great! Tag me on it and I'll review.

Thanks!!
Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>
