### ISSUE TITLE
Plugin: Key-value pair storage

### ISSUE THREAD

**Issue by bobacadodl** [flutter/flutter#4757]
Flutter should have a simple Key-value Pair storage api, similar to Android's SharedPreferences or iOS's NSUserDefaults. Saving and loading data is extremely important for applications and I shouldn't have to go through the hassle of creating, writing to, and loading a file just to save some simple key Value pairs.

**Comment by Hixie** [comment]
We are thinking of making PageStorage into a persistent storage of this kind.

**Comment by olostan** [comment]
@Hixie sometimes there is need of "cross-page" storage, and `PageStorage` is bound to some navigation point (page) if I understand it correctly. Would be nice to have some persistent global app storage, not just for page, like `LocalStorage` for web apps.

**Comment by xster** [comment]
@mit-mit, would also support including this as an out of the box plugin in the MVP. Anyone implementing any app with some sort of login (probably a large share of the market) will need this and the alternative (spinning their own) is a lot of non-trivial non-value-add code.

**Comment by eseidelGoogle** [comment]
This is a frequently requested plugin. :)  Posse just asked if we had one.

**Comment by lukef** [comment]
We have a working, pure dart concept for this if you are interested. The only thing that it doesn't cover (out of scope for us) was encryption of the values (similar to secure storage on NSUserDefaults & SharedPreferences). I would think that for that protection level you'd want to fallback to a plugin.

**Comment by eseidelGoogle** [comment]
There are other "platform-integration" aspects of sitting on top of NSUserDefaults and SharedPreferences in terms of behaving correctly with regards to preference synchronization, etc.

**Comment by xster** [comment]
Supporting some synergies with preferences cloud functions would indeed be really cool
https://developer.android.com/guide/topics/data/autobackup.html
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/UserDefaults/StoringPreferenceDatainiCloud/StoringPreferenceDatainiCloud.html

**Comment by eseidelGoogle** [comment]
We got another request for this today.  I believe we may have some SharedPreferences/NSUserDefaults code from internal Flutter customers we could share here.  I've asked @collinjackson to investigate.

**Comment by lakexyde** [comment]
Try this: https://github.com/lakexyde/flutter_localstorage. Just needed a simple way to store key-value, so I created this. 
Hope you find it helpful.

**Comment by xyzbilal** [comment]
> Try this: https://github.com/lakexyde/flutter_localstorage. Just needed a simple way to store key-value, so I created this.
> Hope you find it helpful.

looks promising. thanks for your effort
