### ISSUE TITLE
Flutter CMD keep returning `Checking Dart SDK version...` everytime

### ISSUE THREAD

**Issue by blackjyn** [flutter/flutter#47581]
I'm using Flutter SDK  stable version 
Everytime I run flutter command of any kind: `flutter doctor` ,`fluter run`, etc etc 
it always return `Checking Dart SDK version...` and Flutter wants to connect to the internet every time with
`Building flutter tool`  and  `Running pub upgrade` always run for any flutter cmd I typed.

What's wrong? This is really frustrating for even just doing simple task like that.

**Comment by enci90** [comment]
I had the same problem (on win)
I solved upgrading power shell from 4.0 --> 5.1

**Comment by riyadhuddin** [comment]
> I had the same problem (on win)
> I solved upgrading power shell from 4.0 --> 5.1

same issue

**Comment by riyadhuddin** [comment]
![image](https://user-images.githubusercontent.com/13874736/80741057-dbc97b00-8b3a-11ea-810b-5193a196b1ce.png)

**Comment by jonahwilliams** [comment]
We've fixed this with recent upgrades to the flutter batch script so that the tool correctly exits on powershell version errors.

**Comment by rameshsahydstgdn** [comment]
I am getting the same issue. My system is already having power shell 5.1.
