### ISSUE TITLE
Sailfish OS support

### ISSUE THREAD

**Issue by fiskindal** [flutter/flutter#47584]
I want to run the flutter application on sailfish operating system.

**Comment by phanirithvij** [comment]
The home page says it's fully compatible with Android applications https://sailfishos.org/
Were you not able to run an app on your OS?

**Comment by fiskindal** [comment]
What will happen to Google services Turkey does not work?
Google services may be interrupted at any time.

**Comment by fiskindal** [comment]
I'm thinking of creating an Android open source project or sailfish OS devices.

**Comment by fiskindal** [comment]
@phanirithvij  I think the sailfish operating system does not have vulcan support.
