### ISSUE TITLE
dart:ffi does not support Hot Reload/Restart

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#47588]
## Use case

When linking native C/C++ code to your Flutter app and accessing it via `dart:ffi`, the functions will not be updated by a hot reload nor a hot restart. 

## Proposal

It could be useful to have the native code recompiled on change at least when hot restarting.

### Problems

As far as I am concerned, this seems a bit harder to accomplish than regular hot restart because the C/C++ code is not compiled at runtime at all and it is e.g. handled by Gradle on Android. However, I am not an expert on this and thus I figured that there might be a possible way to integrate this functionality into Flutter.

**Comment by stuartmorgan** [comment]
Hot reload and restart are Dart VM features. Native code, such as the runner and plugins, have always required a full rebuild; FFI is in the same category.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Is there an issue proposing hot restart / hot reload for plugins?  

As I mentioned in the original comment, I am aware of the fact that all of this happens completely outside of the VM, but as far as I am concerned, "hot reload" also exists for Android native apps (https://medium.com/androiddevelopers/android-studio-project-marble-apply-changes-e3048662e8cd).

**Comment by stuartmorgan** [comment]
I'm a bit confused; your feature request specifically discussed C/C++ code, but you've linked to something describing the ability to update a specific subset of Java bytecode using Android's Java VM.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Thanks for your response.

You stated the following:

>plugins, have always required a full rebuild

Now, I am wondering:

>Is there an issue proposing hot restart / hot reload for plugins?

Hope this makes it clear to you.

**Comment by stuartmorgan** [comment]
I don't know if there is such a feature request open for plugins; I can tell you that supporting it would be not be feasible on several platforms that Flutter supports, just as it would be almost certainly be infeasible for C++ code accessed via FFI.
