### ISSUE TITLE
Focus still on Input after clicking Button

### ISSUE THREAD

**Issue by bobacadodl** [flutter/flutter#4759]
I have a view like this: https://gyazo.com/9b8d7726230884017002c6ed9818ac25

When I click the "Go" RaisedButton, the focus remains on the text input and the keyboard remains open (on both iOS and Android)

I believe this may be a bug? I would expect the keyboard to close automatically after clicking the button. I had to close it manually by calling Focus.clear in the onPressed of the button.

```
return new Block(
                padding: new EdgeInsets.only(top: kTextTabBarHeight + kToolBarHeight + statusBarHeight),
                scrollableKey: page.key,
                children: <Widget>[
                  new Form(
                    onSubmitted: _handleSubmitted,
                    child: new Block(
                      padding: const EdgeInsets.all(8.0),
                      children: <Widget>[
                        new Center(
                          child: new Text(
                            "Enter the LaundryAlert login code for your university",
                            textAlign: TextAlign.center
                          )
                        ),
                        new Input(
                          hintText: 'The LaundryAlert password for your school',
                          labelText: 'Password',
                          formField: new FormField<String>(
                            setter: (String val) { _code = val; },
                            validator: _validatePassword
                          )
                        ),
                        new RaisedButton(
                          child: new Text('Go!'),
                          onPressed: _handleSubmitted
                        )
                      ]
                    )
                  )
                ]
              );
```
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/balajisundara/Documents/flutter/flutter
    • Framework revision 9c0c0225a6 (24 hours ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/balajisundara/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 8.0, Build version 8S128d

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

**Comment by abarth** [comment]
What does the _handleSubmitted function do?  It's not in your code snippet.

**Comment by bobacadodl** [comment]
@abarth Sorry about that. Here's the function

The entire project is up at https://github.com/bobacadodl/LaundryAlert
```
  void _showInSnackBar(String value) {
   _scaffoldKey.currentState.showSnackBar(new SnackBar(
     content: new Text(value)
   ));
  }

  void _handleSubmitted() {
    print('submitted form');
    http.get("https://www.laundryalert.com/cgi-bin/${_code}/LMPage").then((response) {
      if(response.statusCode!=404) {
        if(!kRoutes.containsKey('dormlist/$_code')) {
          kRoutes['dormlist/$_code'] = (BuildContext context) => new DormList(code: _code, name: _code);
        }
        Navigator.pushNamed(context, 'dormlist/${_code}');
      }
      else {
        Focus.clear(context);
        _showInSnackBar("Error - Invalid school code! Please report this to the app authors if you believe it is an error.");
      }
    });
  }
```

**Comment by mpcomplete** [comment]
Same as https://github.com/flutter/flutter/issues/6603 .
