### ISSUE TITLE
Don't deprecated SharedPreferences.commit().

### ISSUE THREAD

**Issue by Yodesoft** [flutter/flutter#47604]
I writing a SharedPreferences plugin for my Linux project, it's based on Jsoncpp. 

Base on current version (0.5.6) of SharedPreferences, cause commit() was marked deprecated and  do nothing, i could let the Linux plugin works likes Android plugin, do a commit (wirte json strings to a file)every set.  

In my project, program needs to write items at once,  so it works as:
set a item
write to a file  <commit>
set b item
write to a file <commit>
.....
The implementation works is weird, right? Why not do a commit after all set, as:
set a item
set b item
...
write to file <commit>

So, i suggest let the implementation decide commit or not.
1. don't deprecated SharedPreferences.commit()
2. add a commit() interface for SharedPreferencesStorePlatform

After all, commit function should be works like:
`Future<bool> commit() async {`
`  return _store.commit();`
`}`

Refs:
shared_preferences-0.5.6/lib/shared_preferences.dart - Line-143
` /// Always returns true.`
`/// On iOS, synchronize is marked deprecated. On Android, we commit every     set.`
`@deprecated`
`Future<bool> commit() async => true;`

**Comment by stuartmorgan** [comment]
While I think the request here was reasonable at the time, there's been a year and a half for people to get used to not calling commit; given that, the potential for subtle bugs if it were re-introduced now is too high.

For a custom implementation where you control the client, you could always put a commit method on your platform implementation's API and use that.
