### ISSUE TITLE
I can't open my application

### ISSUE THREAD

**Issue by Bediosss-Pro** [flutter/flutter#47601]
```bash
Running "flutter pub get" in instagram_clone_marcus_ng...       
Because instagram_clone_marcus_ng depends on module from unknown source "androidX", version solving failed.
pub get failed (1)
```

**Comment by iapicca** [comment]
Hi @Bediosss-Pro  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please note that from the latest stable version `androidx` is set as default.

Thank you

**Comment by Bediosss-Pro** [comment]
Thanks, my problem is now resolved. 😉
