### ISSUE TITLE
Override this method/function

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4761]
We should be consistent about whether we say "override this function" or "override this method" in our dartdocs.

**Comment by Hixie** [comment]
I think we should use the terminology as follows:
method - a member of a class that is a non-anonymous closure
function - a callable non-anonymous closure that isn't a member of a class

By those definitions, you can only override a method.

**Comment by abarth** [comment]
SGTM.  We just need to change the docs to be consistent.

**Comment by Hixie** [comment]
We should update the style guide to mention this decision (and other similar issues of style for docs).
