### ISSUE TITLE
[iOS] Incorrect behaviour of text cursor with 3D Touch

### ISSUE THREAD

**Issue by sakyoyuto** [flutter/flutter#47610]
Text cursor movement of iOS space key 3D Touch(Long press) does not work in Japanese keyboard.
Works in English keyboard.
It used to work, but it may have been a problem since iOS13.

Below is my doctor.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88,
    locale ja-JP)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available
```

Thank you.

**Comment by sakyoyuto** [comment]
@iapicca @shihaohong @goderbauer 
I need help. Is there solution?

**Comment by shihaohong** [comment]
cc/ @justinmc @GaryQian who might know more than I do about text editing and the keyboard

**Comment by justinmc** [comment]
It seems to work for me on an iPhone 7 on iOS 13 with the default iOS Kana keyboard.  I'm on the master channel.  Are you doing anything different?

<img width="250" src="https://user-images.githubusercontent.com/389558/73977173-b4b63100-48de-11ea-8385-b856425fdddf.gif" />

**Comment by sakyoyuto** [comment]
@justinmc 
Thank you for your reply.

Apparently, such symptoms occur when Japanese is entered.
Attach the video.

![RPReplay_Final1581038029_3x](https://user-images.githubusercontent.com/45416100/73994784-1daeaf00-499a-11ea-8279-67c70ad11874.gif)

I switched to the master channel and the same problem occurs.
Below is my doctor.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.83, on Mac OS X 10.15.2 19C57, locale
    ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!
```

Thank you.

**Comment by justinmc** [comment]
I tried again and I do see some weird movement of the cursor, but I don't see the stuck cursor like in your video.  Do you get an error in the console when that happens?

<img width="250" src="https://user-images.githubusercontent.com/389558/74068667-0e872b80-49b1-11ea-9439-41d14649001c.gif" />

**Comment by sakyoyuto** [comment]
No errors are displayed on the console.

Cursor hovering and seems to freeze if you release the space key immediately. (Within 1 second)
If you keep pressing the space key, it starts to make weird movements.

Thank you.

**Comment by justinmc** [comment]
Ok got it.  I do see those same sorts of freezing cursor movements.  I think that's a bug we should fix.

**Comment by sakyoyuto** [comment]
Thank you.

**Comment by LoongZhi** [comment]
> Ok got it. I do see those same sorts of freezing cursor movements. I think that's a bug we should fix.

Is there a solution？

**Comment by kongo2002** [comment]
I don't think this is any specific to Japanese at all. For me this happens with a regular English keyboard as well. I think it happens every time you don't actually move the cursor after long-pressing.

I posted this earlier to a very similar issue since I saw that one before (including a screen recording): https://github.com/flutter/flutter/issues/54413#issuecomment-617865182

**Comment by VladyslavBondarenko** [comment]
Screen recording from https://github.com/flutter/flutter/issues/54413#issuecomment-617865182, thanks @kongo2002.

![test](https://user-images.githubusercontent.com/17024977/80072091-695f0680-854e-11ea-96b3-c23b0695f094.gif)

I can reproduce the same. It's not specific to the language.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 84c84fb249 (2 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.122
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by suztomo** [comment]
I noticed this cursor move bug behavior does not appear in release builds (good).

**Comment by kongo2002** [comment]
@suztomo are you sure about that? I originally noticed that bug on a release build, that's why it surprises me a lot.

**Comment by suztomo** [comment]
Now I’m not sure. My release build also shows the cursor bug today.

**Comment by at-toannguyen3** [comment]
Any update for this issue?
