### ISSUE TITLE
Flutter imports packages

### ISSUE THREAD

**Issue by tomosullivan8** [flutter/flutter#47612]
When I use the 'Wrap with..' function in Android Studios it imports the package although it's already been imported through `import 'package:flutter/material.dart';`.

Sometimes it also adds imports just when I press [Enter] while typing the widget type, for example when I use the `Container()` it pulls through 
`import '../../../../../flutter/packages/flutter/lib/cupertino.dart';`.

I've used flutter upgrade and flutter doctor;

Doctor summary (to see all details, run flutter doctor -v):
```console
[✓] Flutter (Channel master, v1.13.6-pre.16, on Mac OS X 10.15.1 19B88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)
• No issues found!
```

**Comment by azol** [comment]
I have the same issue (VS Code) -- weird imports: `import '../../../../..'` Tested on both: dev and master channel

**Comment by jonahwilliams** [comment]
This has been fixed and rolled into flutter. If you're on a newer dev or master and still seeing this issue, please file a new bug with `flutter doctor` attached
