### ISSUE TITLE
ERROR MESSAGE FROM FLUTTER

### ISSUE THREAD

**Issue by litcodes** [flutter/flutter#47611]
I keep getting error messages when i try to run my app. I can't also enable usb debugging. It's been enabled on my mobile device but its not reflecting on android studio.
```bash 
1:39 PM	Error running 'main.dart': Cannot run program "C:\flutter\bin\cache\dart-sdk\bin\dart.exe" (in directory "C:\Users\USER\AndroidStudioProjects\whats_live_coding"): CreateProcess error=2, The system cannot find the file specified
```

**Comment by iapicca** [comment]
Hi @litcodes  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by litcodes** [comment]
Flutter doctor -v
PS C:\flutter> flutter doctor -v
flutter : '"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an 
internal or external command,
At line:1 char:1
+ flutter doctor -v
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('"C:\flutter\bi...ternal command,:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

FLUTTER RUN --VERBOSE 
PS C:\flutter\bin> flutter run --verbose
flutter : '"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an 
internal or external command,
At line:1 char:1
+ flutter run --verbose
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('"C:\flutter\bi...ternal command,:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

PS C:\flutter\bin> cd ..

PS C:\flutter> flutter run --verbose
flutter : '"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an 
internal or external command,
At line:1 char:1
+ flutter run --verbose
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('"C:\flutter\bi...ternal command,:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

PS C:\flutter> cd ..

PS C:\> flutter run --verbose
flutter : '"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an 
internal or external command,
At line:1 char:1
+ flutter run --verbose
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('"C:\flutter\bi...ternal command,:String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

**Comment by ja2375** [comment]
Hi @litcodes 
Your dart SDK appears to be missing. Please check if the file `C:\flutter\bin\cache\dart-sdk\bin\dart.exe` exists and that you have permission to execute it.
If not, redownload Flutter from the official site.

**Comment by iapicca** [comment]
Hi @litcodes 
I believe @ja2375 is correct,
please double check your installation following the [docs](https://flutter.dev/docs/get-started/install)
thank you

**Comment by litcodes** [comment]
**Uninstall and re-installed Flutter but still having issues running the test app.** 
Launching lib\main.dart on Infinix X559 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by ja2375** [comment]
Ok, that is not the same error.
Can you please post your `flutter doctor -v` output now?
Thank you

**Comment by litcodes** [comment]
C:\Users\USER>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Infinix X559 • 02958107A8001528 • android-arm • Android 7.0 (API 24)

• No issues found!

**Comment by iapicca** [comment]
Hi @litcodes 
could you please post a minimal code sample
or the steps to reproduce the problem?
Thank you

**Comment by litcodes** [comment]
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by iapicca** [comment]
This appears to be the "hello world" app 
that comes with the installation;
can you please  run
	`flutter clean`
	`flutter pub cache repair`
and then provide your `flutter run --verbose`
thank you

**Comment by iapicca** [comment]
Hi @litcodes  
I apologize for noticing only now; 
I see there's an open [issue](https://github.com/flutter/flutter/issues/40517) addressing the case you described.

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by litcodes** [comment]
Thanks for the timely responses. I have been able to solve the problem. I had to delete a widget file in the gradle and reload the application hence the files in the gradle were re-downloaded by the application.
