### ISSUE TITLE
macOS Catalina is missing from the pre-requisites of installation

### ISSUE THREAD

**Issue by nyholku** [flutter/flutter#47613]
Some text on this page:

https://flutter.dev/docs/get-started/install/macos

implies that pre Catalina macOS would work with flutter.

At least High Sierra does not work as a platform because there is no Xcode version available that is supported by current flutter (is there any real reason for this). 

This can be resolved by hacking the version check, but the next stumbling block is the dependency of Swift 5.0. This can also be hacked and then it is possible to get the sample flutter app from above mentioned page to compile but is this a rabbit hole anyone wants to follow...

**So it would best if this dependency on Catalina is mentioned right out of the bat, would have saved hours of my life.**

Note: Upgrading Catalina is not a trivial because it leaves 32 bit apps behind, including non-subscription based PhotoShop which many developers use.

**Comment by stuartmorgan** [comment]
Xcode 11 requires Mojave, not Catalina.

The iOS setup instructions say that the latest stable version of Xcode is required; what part implied that a version of macOS that can't run that would work?

**Comment by nyholku** [comment]
This is what lead me to believe that there would not be an OS version dependence:

" For example, macOS Mojave _**(and earlier)**_ uses the Bash shell by default, so edit $HOME/.bash_profile or $HOME/.bashrc. macOS Catalina uses the Z shell by default, so "

also "Operating Systems: **_macOS (64-bit)_**" 

Not exactly wrong but prone to misinterpretation.

If it runs on Mojave and above then it would be best just explicitly say so.

**Comment by stuartmorgan** [comment]
Those are in the general sections though. There's a difference between the minimum requirements of Flutter, and the minimum requirements to target iOS. Are you unable to target Android or the web on High Sierra?

**Comment by nyholku** [comment]
Well, I guess I could target Android, have not specifically tested that.

 At this point I'm just researching and exploring flutter to see if it is worth my time. Looks very promising or I would not be here. But my point is that I took what is likely the most common path i.e.  click at the Get Started and followed the instructions to the letter and I came against the stumbling block of the latest XCode not running on my version of macOS.

I think I'm not alone so I think it would be worth pointing out the requirement of macOS version number and also that Xcode is not necessary to target Android. 

The web page and your response sort of assume that cause I'm on macOS I will be developing iOS stuff. In my case no, I do not do iOS stuff,  I'm actually developing an Android app at the moment.

None of this is a big deal, but first impressions count so improving the Getting Started would make sense to me.

**Comment by stuartmorgan** [comment]
I'm not assuming that you are developing for iOS, I'm responding to your comments about Xcode, and pointing out that they are specific to iOS. I'm just not sure how you came to the conclusion that your platform isn't supported if you aren't trying to follow the iOS setup instructions.

Similarly, the instructions don't assume that you need to follow all the platform steps. That section begins:

> Complete at least one of the platform setup steps now, to be able to build and run your first Flutter app.

So it specially says that you need to do at least one of iOS, Android, or web setup, but not necessarily all.

For the specific suggestions:

> I think I'm not alone so I think it would be worth pointing out the requirement of macOS version number

That's worth considering, but we have to weigh that against needing to update this page any time the required version of Xcode changes, and with the potential confusion of having two different versions listed (one for Flutter in general, and one for targeting iOS).

> and also that Xcode is not necessary to target Android.

That should already be the case. Could you point us to the specific section that tells you that Xcode is required outside of iOS-specific parts of the instructions?

**Comment by nyholku** [comment]
Ok, this is going nowhere fast. I don't understand why I bother to argue my case when the discussion in heading towards ditch.

You are defensive and don't want to see that people might see that page differently that how you see it. 

> That's worth considering, but we have to weigh that against needing to update this page any time the required version of Xcode changes, and with the potential confusion of having two different versions listed (one for Flutter in general, and one for targeting iOS).

Really, I've tried to keep calm and wrote several comments to above paragraph, but nothing seems to come out as being helpful for this discussion so I'll let it pass.

I  leave it to the history and audience to form their opinion the subject matter and the protagonists  in this discussion.

Thanks for playing.
