### ISSUE TITLE
WEB: Flutter Displays Red Javascript Text Before Load

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#47623]
My Flutter project displays a red dart.js javascript text during loading. 
![MaxthonSnap20191221125613](https://user-images.githubusercontent.com/19896174/71324898-670a7400-24aa-11ea-8d38-8937025ebb6b.png)
![2019-12-21_13-50-58](https://user-images.githubusercontent.com/19896174/71324902-7db0cb00-24aa-11ea-9877-33094c0f789a.gif)
Project: https://github.com/searchy2/FlutterGames
Demo: https://ssl.imfast.io/fluttergames/
HTML:
![MaxthonSnap20191221140933](https://user-images.githubusercontent.com/19896174/71324918-bb155880-24aa-11ea-815b-7738be90fe5b.png)
index.html:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>stream_games</title>
</head>
<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

## Steps to Reproduce
1. Clone project (https://github.com/searchy2/FlutterGames).
2. Run `flutter build web`.
3. Open index.html.

## Logs
```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[X] Chrome - develop for the web (Cannot find chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 3.5)
[!] VS Code, 64-bit edition (version 1.40.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

The red text seems to be the index file displaying the script. Curiously, this problem does not occur when running the empty Flutter demo (https://ssl.imfast.io/flutterwebtest/)

What is happening and how can I remove the red text?

**Comment by jonahwilliams** [comment]
Does this happen if you update your html file to match the flutter gallery?

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/web/index.html

**Comment by searchy2** [comment]
@jonahwilliams thank you so much for the suggestion! I used your example and replaced 
`<script src="main.dart.js" type="application/javascript"></script>`
with 
`<script src="main.dart.js"></script>` 
and the red text disappeared. 

`flutter build web` generates `<script src="main.dart.js" type="application/javascript"></script>` so perhaps it should leave out the type?

**Comment by jonahwilliams** [comment]
Build web is just copying whatever is in web/index.html. if that didn't come from flutter create, then there is something wrong with your html file
