### ISSUE TITLE
`flutter run` on Android ends up showing logs from previous debugging sessions on Android

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47629]
This can be worked around by running `adb logcat -c`, but I don't remember this happening in the past.  I'm not sure when it was introduced, but it may be present on stable.

See https://github.com/flutter/flutter/issues/34876#issuecomment-568302267 for more context

/cc @jonahwilliams or @blasten who might know if something changed on the tooling side here.

It's also possible this is related to Android version, as I recently started using a Q device more regularly.

**Comment by Horlahkay** [comment]
please mine is saying please review your gradle project 
what do I do ??

**Comment by dnfield** [comment]
@Horlahkay that's a different issue. Please file a new bug if there isn't an existing one covering that.

**Comment by Horlahkay** [comment]
Okay thanks
Its solve already what am experiencing now is





FAILURE: Build failed with an exception.



* Where:

Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+2\android\build.gradle' line: 22



* What went wrong:

A problem occurred evaluating root project 'shared_preferences_macos'.

> Failed to apply plugin [id 'com.android.library']

   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in C:\flutter\.pub-cache\hosted\pub.dartlang.org\s

hared_preferences_macos-0.0.1+2\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 14s

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by eliaweiss** [comment]
`cls && adb logcat -c && flutter drive --target=test_driver/app.dart --driver=test_driver/app_add10.dart`

**Comment by jmagman** [comment]
@dnfield Is this a duplicate of https://github.com/flutter/flutter/issues/46815?  You commented on that one, too.

**Comment by dnfield** [comment]
Yes, closing this one
