### ISSUE TITLE
My app won't install on device after 1.12.13.hotfix3 and hotfix5 and hotfix6

### ISSUE THREAD

**Issue by youssefhad** [flutter/flutter#47630]
My app's APK won't install on devices after 1.12 update showing the message "App not installed" and when I downgrade to 1.9 it works,

![Screenshot_20191222-224557_Package installer](https://user-images.githubusercontent.com/10350147/71327878-5db2f300-250e-11ea-9082-d26efb169222.jpg)

Android 9.0
Samsung Galaxy s8 and Huawai P30

**Comment by Mosely** [comment]
Hi @youssefhad did you fix this issue?  If so, how did you do that?  I'm having the same problem.

**Comment by youssefhad** [comment]
Hi @Mosely 
I run this command ` flutter build apk --release` on the terminal
