### ISSUE TITLE
image_picker崩溃的问题

### ISSUE THREAD

**Issue by geyifen** [flutter/flutter#47638]
> 在使用image_picker时，选择单张图片快速的点击两次时导致应用程序崩溃

When using image_picker, selecting a single image and quickly clicking twice causes the application to crash

```bash
+ (NSData *)updateMetaData:(NSDictionary *)metaData toImage:(NSData *)imageData {
、、、
  CGImageDestinationRef destination = CGImageDestinationCreateWithData(
      (__bridge CFMutableDataRef)mutableData, CGImageSourceGetType(cgImage), 1, nil);
///destination返回一个nil
、、、
}
```
```console
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/liwenfan/flutt/flutter
    • Framework revision 2d2a1ffec9 (4 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/liwenfan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

```

**Comment by iapicca** [comment]
Hi @geyifen 
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by geyifen** [comment]
您好，iapicca
下面是我们使用代码的方法：
            CupertinoActionSheetAction(
              onPressed: () async {
                Navigator.pop(context);
                File image = await ImagePicker.pickImage(source: ImageSource.gallery, maxHeight: MAX_IMAGE_SIZE, maxWidth: MAX_IMAGE_SIZE,imageQuality: 70);
                imagePickCompleter.complete(image);
              },
              child: Text('相册', style: textStyle,)
            ),
我们在弹出系统的图片选择器时，这时我们快速的点击两下就造成上面的崩溃问题了
我们使用的依赖版本是image_picker 0.6.2+1
谢谢您！

**Comment by iapicca** [comment]
thank you @geyifen

**Comment by geyifen** [comment]
hello, @iapicca 
我尝试在FLTImagePickerPlugin.m文件中加了下面一句代码，似乎可以解决快速连续点击事件
- (void)imagePickerController:(UIImagePickerController *)picker
    didFinishPickingMediaWithInfo:(NSDictionary<NSString *, id> *)info {
/// 自己尝试加的代码
  if (_imagePickerController.beingPresented) return;

  NSURL *videoURL = [info objectForKey:UIImagePickerControllerMediaURL];
  [_imagePickerController dismissViewControllerAnimated:YES completion:nil];
...
}

**Comment by geyifen** [comment]
hello, @iapicca
非常抱歉，应该把上面的
if (_imagePickerController.beingPresented) return;
替换为
if (_imagePickerController.beingDismissed) return;

**Comment by iapicca** [comment]
Hi @geyifen 
I'm glad that you fixed the issue, 
thank you for letting me know
