### ISSUE TITLE
Create performance standard and formalize test process

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#47631]
@filiph recently found that the new Flutter gallery app is quite janky in some cases. It might be nice to create a performance standard, and formalize a test process to enforce such standard, before releasing each Flutter-official app.

![Crane-jank](https://user-images.githubusercontent.com/22987568/71328325-3cc8ae80-24ca-11ea-86ea-276889923fd9.gif)

**Comment by goderbauer** [comment]
We have performance tests for this now.
