### ISSUE TITLE
 ProcessException: Process timed out: xcrun xcodebuild -showBuildSettings

### ISSUE THREAD

**Issue by rafaeloliveirafaria** [flutter/flutter#47633]
## Command
  ```
  flutter run
  ```

 ## Logs
  ProcessException: ProcessException: Process timed out:
2019-12-22 19:16:02.913 xcodebuild[18526:155321]  DTDeviceKit: deviceType from 00008020-000A1556113B002E was NULL
2019-12-22 19:16:03.054 xcodebuild[18526:155321]  DTDeviceKit: deviceType from 00008020-000A1556113B002E was NULL
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet DEVELOPMENT_TEAM=7U5W99MES9 -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/rafael/Documents/Documentos - MacBook Air de Rafael/work/flyApps/newVersion/flyvendas/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/2v/6z_mx4xj50b5wmvp82slcg9r0000gn/T/flutter_build_log_pipe.QshYgo/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
  ```
  #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:346:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:501:66)
<asynchronous suspension>
#3      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:296:50)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:430:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:334:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:555:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:522:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _runZoned (dart:async/zone.dart:1518:10)
  ```

## Flutter doctor
  ```
  [✓] Flutter (Channel master, v1.13.6-pre.16, on Mac OS X 10.15.1 19B88, locale pt-BR)
    • Flutter version 1.13.6-pre.16 at /Users/rafael/flutter
    • Framework revision fcaf9c4070 (25 hours ago), 2019-12-21 14:03:01 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rafael/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rafael/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Rafael Oliveira • 00008020-000A1556113B002E • ios • iOS 13.3

• No issues found!

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
firebase_auth
firebase_core
firebase_core_web
firebase_database

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/44265.

**Comment by techieroshan** [comment]
Is there a workaround / solution to this issue of Process timed out?

**Comment by trigjason** [comment]
upgrade 1.75

**Comment by JosueMCapita** [comment]
HI!
I am having the same problem everytime I execute `flutter run`.
Just for one project! I have another that is running with no problem!

**Comment by jmagman** [comment]
From https://github.com/flutter/flutter/issues/54722#issuecomment-614867277
> If Xcode's command line tool just isn't returning, there's not much Flutter can really do about it.
> 
> Once the following succeeds and returns in a reasonable amount of time, Flutter should be unwedged.
> 
> ```
> $ cd ios
> $ xcrun xcodebuild -project Runner.xcodeproj -scheme Runner -showBuildSettings 
> ```
> 
> You can try uninstalling and re-installing Xcode.

So for anyone hitting this, how long does `xcrun xcodebuild -project Runner.xcodeproj -scheme Runner -showBuildSettings ` take to complete?

**Comment by braysonjohn148** [comment]
> xcrun xcodebuild -project Runner.xcodeproj -scheme Runner -showBuildSettings

less than a minute.

`Build settings for action build and target Runner:
    ACTION = build
    AD_HOC_CODE_SIGNING_ALLOWED = NO
    ALTERNATE_GROUP = staff
    ALTERNATE_MODE = u+w,go-w,a+rX
    ALTERNATE_OWNER = Mac
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
    ALWAYS_SEARCH_USER_PATHS = NO`....

**Comment by jmagman** [comment]
@braysonjohn148 try running the command exactly as it's displayed in the `ProcessException: Process timed out:` message (I don't have your output so I don't know what it is). `/usr/bin/env xcrun xcodebuild -configuration Debug -quiet DEVELOPMENT_TEAM=`...

**Comment by UlyssesAlves** [comment]
Closing Xcode before running "flutter build ios --release -v > build.log" apparently has solved the timeout issue in my Mac OS Catalina.

**Comment by TinchoOlivari** [comment]
I solved it by going into xcode, changing the Deployment Target to 14.4, fixing the suggested warnings and running the app from there.

Flutter version: 1.12.13+hotfix.5
MacOS: Catalina 10.15.7
Xcode: 12.4

**Comment by alisson-bairesdev** [comment]
Running `flutter clean` and restarting the Mac did the trick for me. After restarting and opening Xcode, it prompted me to download ios device support again (it was already installed before but it prompted me to download it anyway). Started working just fine after that.


<img width="250" alt="image" src="https://github.com/flutter/flutter/assets/151851498/633275b0-f31a-47d4-95e3-bf444631a8bd">
