### ISSUE TITLE
Background isolates aren't killed when hot restarting

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47646]
`flutter run` the program below. The output will say "Main thread main" and "Isolate thread background" every three seconds. Hit `R` in the console and now you'll have two background thread messages for every main thread message.

```dart
import 'dart:async';
import 'dart:isolate';

import 'package:flutter/material.dart';

void main() {
  Isolate.spawn<void>(background, null, debugName: 'background');
  Timer.periodic(const Duration(seconds: 3), (Timer timer) {
    new TestMain();
  });
}

void background(void message) {
  Timer.periodic(const Duration(seconds: 3), (Timer timer) {
    new TestIsolate();
  });
}

class TestMain {
  TestMain() {
    debugPrint('Main thread ${Isolate.current.debugName}');
  }
}

class TestIsolate {
  TestIsolate() {
    debugPrint('Isolate thread ${Isolate.current.debugName}');
  }
}
```

cc @bkonyi @jonahwilliams @jason-simmons 

See also https://github.com/flutter/flutter/issues/20743 (hot reload doesn't update background isolates).

**Comment by jonahwilliams** [comment]
What we would need to do to solve this (from the tooling) is detect which isolates were created as a result of running main so we could send a kill signal from the tooling when restarting. I don't think we could assume that all non flutter-view isolates are safe to kill, though I can't think of any other way they could be spawned. Thoughts @bkonyi

**Comment by bkonyi** [comment]
I think killing the isolates on a hot restart sounds like the best solution, but there might be some unintended side-effects in plugin code if authors aren't careful with how they manage their state.

**Comment by jonahwilliams** [comment]
@bkonyi can you think of any examples of this, besides the android alarm manager plugin?

**Comment by bkonyi** [comment]
> @bkonyi can you think of any examples of this, besides the android alarm manager plugin?

It's hard to say, but some potential issues could include:

- Native code is waiting on a response from an isolate via a MethodChannel when the isolate is killed, which might put the plugin in a bad state.
- The plugin assumes that its background isolate is still alive after it has been killed
- The background isolate was doing some sort of modification to persistent state (e.g., writing to a file, updating a database, etc) when it was killed.

Giving this some more thought, it might be ideal to re-initialize plugins on a hot restart, although that might cause its own issues.

**Comment by jonahwilliams** [comment]
For (1) I don't think we support message channels in isolates

**Comment by bkonyi** [comment]
> For (1) I don't think we support message channels in isolates

We 100% do since that's how plugins tell a spawned background isolate to invoke a Dart callback.

**Comment by jonahwilliams** [comment]
ahh, derp. The correct thing to do would be to expose this information to plugins as well - or reinitialize them somehow

**Comment by bkonyi** [comment]
Yeah, that would be ideal. Unfortunately it would likely be difficult to get existing plugins to update just to handle hot restart. This is a tough issue given all of the execution boundaries that are being crossed and the lack of any true synchronization between them :-\.

**Comment by jonahwilliams** [comment]
A reasonably safe way to go about this might be to only perform the hot reloading of isolates, and then hide the background isolate killing behind a flag/configuration. At least we could land the feature, though I don't know how we would necessarily go about either educating users about it or updating the ecosystem.
