### ISSUE TITLE
Error ":app:transformClassesWithDexBuilderForDebug" when upgrade to new version of flutter

### ISSUE THREAD

**Issue by hoahoctro** [flutter/flutter#47645]
I upgrade flutter from v1.91. hotfix 6 by using `flutter upgrade --force`
Then i build an example "layers" - `flutter run`, it shows this message, while if i switch to 1.91, everything built ok
![image](https://user-images.githubusercontent.com/33972583/71336207-cafb6e00-2578-11ea-8eea-851dafd8309b.png)

Can anyone help ? Thanks

**Comment by janmoppel** [comment]
Hello @hoahoctro !

Thank you for posting an issue.
Can you please run the application with the `--stacktrace` option and post the logs here? Please add it as text: it is harder to debug, when it's on picture.

Also, please attach the `flutter doctor -v` command output.

**Comment by hoahoctro** [comment]
@janmoppel 

> Could not find an option named "stacktrace".

flutter doctor -v

> G:\new\new_exam>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at G:\Flutter\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\Flutter\android\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = G:\Flutter\android
    • ANDROID_SDK_ROOT = G:\Flutter\android\sdk
    • Java binary at: G:\flutter\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_232-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by hoahoctro** [comment]
any help ?

**Comment by zanderso** [comment]
Hi @hoahoctro, could you post the logs from `flutter run --verbose` ? Thanks!

**Comment by jonahwilliams** [comment]
Without more information or logs we cannot make any progress here. Because of the lack of activity, I'm closing the issue - but don't hesitate to re-file in the future.
