### ISSUE TITLE
Typo in DEPS file of flutter/engine for libwebp.

### ISSUE THREAD

**Issue by bomin-kim** [flutter/flutter#47640]
I think that flutter/engine does not have issue tracker. so I leave it here.

While I'm [setting up the engine development environment.](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) I found typo in version tag for libwebp missing **'v'**.

```
'src/third_party/libwebp':
   Var('chromium_git') + '/webm/libwebp.git' + '@' + '0.6.0',
```
https://github.com/flutter/engine/blob/master/DEPS#L407

As a result, `gclient status` show a error message like below after `gclient sync`.

```bash
$ gclient sync
> ... some thing going on...
$ gclient status
>
> src/third_party/libwebp (ERROR)
> ----------------------------------------
> [0:00:00] Started.
> 
> ________ running 'git -c core.quotePath=false diff --name-status 0.6.0' in '/path/to/flutter/engine/src/third_party/libwebp'
> 
> [0:00:00] fatal: ambiguous argument '0.6.0': unknown revision or path not in the working tree.
> [0:00:00] Use '--' to separate paths from revisions, like this:
> [0:00:00] 'git <command> [<revision>...] -- [<file>...]'
> ----------------------------------------
> Error: Command 'git -c core.quotePath=false diff --name-status 0.6.0' returned non-zero exit status 128 in /path/to/flutter/engine/src/third_party/libwebp
```

**Comment by pedromassangocode** [comment]
@dnfield can you confirm if this is a valid issue? The line mentioned is now:
https://github.com/flutter/engine/blob/6625308089e0550ed153f4bda773efa2a444bfeb/DEPS#L372

**Comment by dnfield** [comment]
I haven't seen this error before, and my checkout is able to clone libwebp fine - perhaps the OP was having issues with connectivity at the time.

OP is right that there's no tag by that name, but there is a branch by that name: https://chromium.googlesource.com/webm/libwebp/+/refs/heads/0.6.0

At any rate we're on kind of an old version of libwebp, I wonder if we should update it.. /cc @cbracken @zanderso

**Comment by dnfield** [comment]
I'm going to close this as not reproducible for now. I'll file a separate issue for rolling libwebp.
