### ISSUE TITLE
Plugin: Scheduled Notifications

### ISSUE THREAD

**Issue by bobacadodl** [flutter/flutter#4764]
Flutter should have an easy to use scheduled notification API. (UILocalNotification in iOS, AlarmManager + Notification in Android)

**Comment by mit-mit** [comment]
Note: These are similar in spirit to push notifications, but are different in that they are scheduled locally on a timer, and do not require a network connection.

Also looks like iOS is moving to https://developer.apple.com/reference/usernotifications/unnotificationrequest.

**Comment by assumptionsoup** [comment]
I've been digging through issues because I'm interested in this feature, and it looks to me like this ticket is fully encapsulated by https://github.com/flutter/flutter/issues/2731 and https://github.com/flutter/flutter/issues/6192 / the AlarmManager plugin.

**Comment by mit-mit** [comment]
@assumptionsoup, yes between those two issues, and the plugin https://pub.dartlang.org/packages/scheduled_notifications, I believe this ticket cap be closed. Thanks for the note!

**Comment by sgon00** [comment]
This issue should not be closed. Where is the iOS version? Thanks.

**Comment by mit-mit** [comment]
Hi @sgon00 we are tracking that in https://github.com/flutter/flutter/issues/6192

**Comment by sgon00** [comment]
@mit-mit ok, got it. sorry about that.
