### ISSUE TITLE
App is no installing on Samsung

### ISSUE THREAD

**Issue by naveenjoshi7777** [flutter/flutter#47656]
Hi,
I created a app and it is not installing on Samsung J3, Samsung J5 , oppo F3 plus showing `The app is not compatible with your device.`

On samsung S8, it is extracting, but not installing, please advice.

Best Regards,
Naveen

**Comment by janmoppel** [comment]
Hello @naveenjoshi7777 !

Thank you for posting an issue.
Have you tried to install the app on other devices? If yes, then did you manage to?

**Comment by naveenjoshi7777** [comment]
Hi @janmoppel ,
Thanks for your reply.
Yes, it is working on Redmi or even on some of the Samsung devices.
We are in testing face, can you advice if there is some thing related to signed APK?

**Comment by xster** [comment]
We're going to need a bit more details such as a sample APK or some reproduction steps. Or is this reproducible on all apps such as a newly created one from `flutter create`?

The Samsung J devices does seem problematic potentially in https://github.com/flutter/flutter/issues/24286. Though it sounds like you were never able to run the app in the first place.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
