### ISSUE TITLE
flutter pages mixed with native pages send and receive values and manage page stack

### ISSUE THREAD

**Issue by krmao** [flutter/flutter#47655]
Hi ，after search with all internet, I hope two features follow:

1. how to manage **page stack**(include flutter page and native page) in flutter/native hybrid App?
        _For example (N: Native, F: Flutter):
        Page opening order: Page1(N) -> Page2(F) -> Page3(F) -> Page4(N) ->Page5(F)_
2. hope the mixed pages **could send values and receive values with each other like android startActivityForResult**

what I said is about https://github.com/alibaba/flutter_boost, but the repository is too many bugs and too old about flutter versions, I hope flutter official developers can provide the official ways, thank you!

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.

**Comment by krmao** [comment]
okay, thank you for reply! 

I repost here [https://stackoverflow.com/questions/60872112/how-to-manage-page-stackinclude-flutter-page-and-native-page](https://stackoverflow.com/questions/60872112/how-to-manage-page-stackinclude-flutter-page-and-native-page)
