### ISSUE TITLE
RefreshIndicator is expensive

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#47664]
The `RefreshIndicator` is often used as a parent of a ListView. If the ListView is more complex the RefreshIndicator widget is very expensive performance-wise because the RefreshIndicator moves the child with a global key on a stack if the refresh indicator is to be shown. This causes a relayout and repaint of the whole subtree.

**Comment by christian-muertz** [comment]
I suggest to always put the child on a stack and just add the indicator if needed,

**Comment by dnfield** [comment]
The fix for this was reverted due to internal test failures.  Will try to add relevant test case(s) to repo.

**Comment by dnfield** [comment]
The internal test seems like it may have actually been at fault - I'm proposing a change to that test that will allow us to reland this.
