### ISSUE TITLE
Convert android language from kotlin to Java? (and vice versa).

### ISSUE THREAD

**Issue by AnuragVadd** [flutter/flutter#47665]
Is it possible to convert the chosen android language from kotlin to Java once a flutter app is created? I was going through a tutorial on how to implement notifications on flutter and the tutorial required me to add a few lines of code in Java, But since i chose the default language as kotlin, I am unable to go through the tutorial directly.

**Comment by jonahwilliams** [comment]
See https://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Java%20to%20Kotlin%20conversion/Task.kt
