### ISSUE TITLE
[path_provider] Support for retrieving user's downloads folder on macOS

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#47676]
Currently there is no secure way to retrieve a user's downloads directory on macOS.
The path_provider plugin needs to be extended to provide this path.

**Comment by stuartmorgan** [comment]
Per discussion [here](https://groups.google.com/forum/m/#!topic/flutter-desktop-embedding-dev/z7MytzsVQb8) I think the main question we'll need to resolve is where exactly we want to add a new API that is specific to desktop, but not a single OS.

**Comment by technolion** [comment]
I provided a PR here: https://github.com/flutter/plugins/pull/2436
It includes the platform dependent code in the path_provider sub project `path_provider_macos` which was already there. The dart is part of the main path_provider plugin and throws a `UnsupportedError` if called on iOS or Android.
