### ISSUE TITLE
can't run flutter ( java.util.zip.ZipException)

### ISSUE THREAD

**Issue by flamescell** [flutter/flutter#47678]
I'm new to flutter, and started a course on udemy. When I first run the code, I run into these errors as shown below. Could someone be kind to help figure out what is it that I'm doing wrong? Thank you so much.

![image](https://user-images.githubusercontent.com/59172686/71362996-a92ed500-25d2-11ea-812e-55ee19c25017.png)

**Comment by AdriBoy21** [comment]
Try running `flutter clean` and then try again

**Comment by flamescell** [comment]
@AdriBoy21 

I've done that and 1 error seems to be gone, but there is still an error as below. Is there anything else I'm missing? Thank you so much for your time.

![image](https://user-images.githubusercontent.com/59172686/71413754-a09bd480-268e-11ea-8d4e-19228db32248.png)

**Comment by AdriBoy21** [comment]
Are there any error messages when running `flutter doctor -v`?

**Comment by flamescell** [comment]
@AdriBoy21 
There doesn't seem to be anything wrong...
![image](https://user-images.githubusercontent.com/59172686/71413975-b067e880-268f-11ea-8712-3899adb20ed5.png)

**Comment by iapicca** [comment]
Hi @flamescell  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by flamescell** [comment]
@iapicca 
Thank you for the advice, I'm new to this. 
As I said, there seems to be no problem when I run both flutter doctor -v and flutter doctor -verbose. 


C:\Users\phaso\AndroidStudioProjects\flutter_app>flutter doctor verbose
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
Hi @flamescell  
I apologize for noticing only now; 
I see there's an open [issue](https://github.com/flutter/flutter/issues/40517) addressing the case you described.

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by flamescell** [comment]
@iapicca 
Still having a problem. This is flutter run --verbose, could you help me?

C:\Users\phaso\AndroidStudioProjects\new_app>flutter run --verbose
[  +20 ms] executing: [C:\src\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +36 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +5 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +104 ms] executing: C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +44 ms] Exit code 0 from: C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
[  +16 ms] C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +98 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +199 ms] Generating C:\Users\phaso\AndroidStudioProjects\new_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +35 ms] ro.hardware = ranchu
[  +54 ms] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +30 ms] Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[  +17 ms] executing: C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -s flutter
[   +8 ms] executing: C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +113 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\phaso\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +49 ms] Building APK
[  +27 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +7 ms] Using gradle from C:\Users\phaso\AndroidStudioProjects\new_app\android\gradlew.bat.
[  +11 ms] executing: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[ +129 ms] Exit code 0 from: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +4 ms] executing: [C:\Users\phaso\AndroidStudioProjects\new_app\android\] C:\Users\phaso\AndroidStudioProjects\new_app\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\phaso\AndroidStudioProjects\new_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86
assembleDebug
[+5627 ms] Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
[+11891 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [  +29 ms] executing: [C:\src\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] [        ] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +50 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.5-0-g27321ebba
[        ] [  +10 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[        ] [  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +94 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[        ] [  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +108 ms] Initializing file store
[        ] [  +25 ms] kernel_snapshot: Starting due to {}
[        ] [  +12 ms] C:\src\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --no-link-platform --packages C:\Users\phaso\AndroidStudioProjects\new_app\.packages --output-dill
C:\Users\phaso\AndroidStudioProjects\new_app\.dart_tool\flutter_build\a2368f31235e3edc3c165cef82c7df57\app.dill --depfile
C:\Users\phaso\AndroidStudioProjects\new_app\.dart_tool\flutter_build\a2368f31235e3edc3c165cef82c7df57\kernel_snapshot.d package:new_app/main.dart
[+6274 ms] [+6940 ms] kernel_snapshot: Complete
[+1499 ms] [+1478 ms] debug_android_application: Starting due to {}
[ +101 ms] [ +134 ms] debug_android_application: Complete
[ +298 ms] [ +270 ms] Persisting file store
[   +1 ms] [  +17 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [  +13 ms] "flutter assemble" took 9,078ms.
[ +198 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +96 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig
[   +1 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +93 ms] > Task :app:mergeDebugShaders
[   +1 ms] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[   +1 ms] > Task :app:mergeDebugAssets
[ +297 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug
[        ] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[ +697 ms] > Task :app:createDebugCompatibleScreenManifests
[ +200 ms] > Task :app:processDebugManifest
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +197 ms] > Task :app:checkDebugDuplicateClasses FAILED
[+2402 ms] > Task :app:mergeDebugResources
[   +1 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] 15 actionable tasks: 14 executed, 1 up-to-date
[        ] Execution failed for task ':app:checkDebugDuplicateClasses'.
[        ] > 2 exceptions were raised by workers:
[        ]   java.util.zip.ZipException
[        ]   java.util.zip.ZipException
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 29s
[ +508 ms] Running Gradle task 'assembleDebug'... (completed in 30.6s)
[   +7 ms] "flutter run" took 31,463ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
