### ISSUE TITLE
flutter analyze hangs with 100% CPU

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#47673]
Steps to Reproduce:
- With flutter `dev` or `master` channel on macOS
- Enable experimental macOS desktop development (`flutter config --enable-macos-desktop`)
- `git clone https://github.com/xvrh/flutter_blue_bug.git`
- `cd flutter_blue_bug/example`
- `flutter pub get`
- `flutter build ios`
- `flutter build macos`
- `flutter analyze`

A Dart process will start running with 100% CPU indefinitly.
<img width="957" alt="Screenshot 2019-12-23 at 14 04 08" src="https://user-images.githubusercontent.com/5110923/71359847-3996f680-258e-11ea-9ff4-a1af8aa7cb09.png">

This is probably due to a symlink cycle due to the flutter plugin supporting macOS and iOS at the same time.

This is also reproducible with the Dart Analysis Server in the IDE: IntelliJ, Android Studio and Visual Studio Code.

`flutter analyze --verbose` doesn't show logs during the infinite loop phase.

Several other bugs seems to point to a symlink cycle due to the a Pod file
- https://github.com/flutter/flutter/issues/18528
- https://github.com/Dart-Code/Dart-Code/issues/1114

## Flutter doctor -v:
```
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.2 19C57, locale en-BE)
    • Flutter version 1.13.5 at /Users/xavier/projects/flutter_dev
    • Framework revision 41a911099b (4 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xavier/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (2 available)
    • Xavier’s iPhone • 00008030-00012D9C0212802E • ios        • iOS 13.3
    • macOS           • macOS                     • darwin-x64 • Mac OS X 10.15.2 19C57

• No issues found!
```

**Comment by scheglov** [comment]
Cannot reproduce :-(

```
scheglov@scheglov-macbookpro2:~/dart/flutter_blue_bug/example (master)$ flutter upgrade
Upgrading Flutter from /Users/scheglov/Source/flutter...
Updating 41a911099..e768c92fb
 151 files changed, 2939 insertions(+), 1071 deletions(-)
Flutter is already up to date on channel master
Flutter 1.13.6-pre.44 • channel master • https://github.com/flutter/flutter.git
Framework • revision e768c92fbc (6 hours ago) • 2019-12-30 17:12:19 -0800
Engine • revision bdc9708d23
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

scheglov@scheglov-macbookpro2:~/dart/flutter_blue_bug/example (master)$ flutter analyze
Building flutter tool...
Running "flutter pub get" in example...                             0.5s
Analyzing example...
No issues found! (ran in 2.4s)
```

**Comment by xvrh** [comment]
@scheglov Thanks for trying to reproduce.
I think one the important reproduction step is to build the project for macOS and iOS before running the analysis.

Alternatively, I will try to add the build artifacts directly in the example git repo.

**Comment by scheglov** [comment]
Hm... I cannot build `iOS`.
I don't have any mobile device from Apple.
It seems that I have to have one, XCode is not happy: `There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it.`.

**Comment by scheglov** [comment]
One reason why `flutter analyze` might hang is a file system cycle using links.

**Comment by xvrh** [comment]
@scheglov You can try `flutter build ios --no-codesign` to build without device.

> One reason why flutter analyze might hang is a file system cycle using links.

Yes, this is most likely due to a cycle in the symlinks created by the "Pods" tool in the build phase.

Do you think is would be possible for the analyzer to detect those cycles?

Alternatively, I found that I can prevent the cycle by excluding some folders in the `analysis_options.yaml` file. 
Unfortunally, it works with the `flutter analyze` command, but does not work with the IDEs (powered by the Dart Analysis Server). 
Do you happen to known why the `exclude` clause is not working in this case?

Thanks

**Comment by TodorGinchev** [comment]
This same problem happens on Linux too (ironically it does not happen on Mac for me). Has someone happened to find a solution?
```
[✓] Flutter (Channel dev, v1.13.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.3 at /opt/flutter
    • Framework revision 4af66e335f (3 weeks ago), 2019-12-19 03:53:27 -0500
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)
```

**Comment by iapicca** [comment]
HI @xvrh 
are you experiencing the issue with the latest beta `v1.15.17`?
thank you

https://github.com/flutter/flutter/issues/53507
