### ISSUE TITLE
Allow updates to flutter default template, including new folders and files (with documentation)

### ISSUE THREAD

**Issue by mingsai** [flutter/flutter#47682]
## Use case
I want to customize my default flutter app template. Following this [advice](https://medium.com/flutter-community/flutter-changing-the-default-app-template-f3448386139f), I can see the flutter template files but there is no documentation for adding new files such as the analysis_options.yaml to the main folder. I'd also like to preset various folders including assets, src, and other subfolders to better organize my code. I can envision wanting to add other default files in the future.  

The main problem this resolves is the duplication effort required when building new projects according to organizational specifications. I have done a large search and cannot find the required documentation or know-how (other than the source listed above) on how to make the required modifications to flutter's default templates. 

Alternatives - One or more plugins exist to make adding new folders and files after a project is started but they do nothing to remediate the issue of unnecessary duplicative effort created by not allowing customized templates.

## Proposal
Adjust the flutter tool to allow one to customize the default templates or provide some documentation that allows devs to manually optimize the default files/folder structure that are to be generated by the tool. I think this is something that should come from the flutter tool because it removes the necessity of manually reconstructing the starting point for each new app. While the current default is good for beginners, most shops and devs will have their own architectural requirements and this change will help us to be more efficient.

**Comment by jonahwilliams** [comment]
We do not, in general, want to support customizations to the default flutter templates. These are meant to be as minimal as possible to get user into a working application without exposing too many features at once.

If you want to support different kinds of templates, you can always build a package outside of the flutter_tool that supports this. One such example is stagehand (https://pub.dev/packages/stagehand) which allows you to generate all kinds of project types. You could start your own template package and build off of that as an example
