### ISSUE TITLE
[macOS] add lookupKeyForAsset to FlutterPluginRegistrar

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#47681]
It is currently not possible to load assets from a plugin. This is needed for the `video_player` plugin for example.

**Comment by florent37** [comment]
I need it too for a third party package, please make it open :)

**Comment by stuartmorgan** [comment]
Patches are welcome for this; it would be easy to plumb through following the same approach as the iOS code.

**Comment by nabil6391** [comment]
@stuartmorgan I would like to have a try at this. Can you suggest me where to look for in the iOS code. Thanks

**Comment by stuartmorgan** [comment]
https://github.com/flutter/engine/search?q=lookupKeyForAsset&unscoped_q=lookupKeyForAsset

**Comment by SergeShkurko** [comment]
Can be used as a temporary solution:
```swift
#if os(iOS)
guard let path = Bundle.main.path(forResource: "Frameworks/App.framework/flutter_assets/" + name, ofType: "") else {
    return nil
}
#elseif os(macOS)
let path = Bundle.main.bundlePath + "/Contents/Frameworks/App.framework/Resources/flutter_assets/" + name;
#endif
```

**Comment by littleGnAl** [comment]
Any update on this?

**Comment by littleGnAl** [comment]
BTW, is anyone know how to look up the asset path in Windows?

**Comment by patrick-fu** [comment]
Any update on this?

**Comment by tgrushka** [comment]
I found a slightly more idiomatic way to get the resource URL on macOS (because `Data(contentsOf: ...)` requires a URL, not a path):

```swift
let filename = "FontManifest.json"
let flutterBundleId = "io.flutter.flutter.app"
let flutterAssetsDirectory = "flutter_assets"
guard let flutterBundle = Bundle(identifier: flutterBundleId) else {
    fatalError("Could not get Flutter App bundle with ID: \(flutterBundleId)")
}
guard
    let resourceURL = flutterBundle.url(forResource: filename, withExtension: nil, subdirectory: flutterAssetsDirectory)
else {
    fatalError("Could not get resource URL!")
}
```

(Bundle ID comes from `Contents/Frameworks/App.framework/Resources/Info.plist`.)
