### ISSUE TITLE
Regression in technical_debt_cost

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47687]
Ever since https://github.com/flutter/flutter/pull/47470, we have exceeded the baseline for technical_debt__cost dependencies_count, consumer_dependencies_count and technical_debt_in_dollars. 

What is the protocol for this situation? Should we re-baseline this?

**Comment by franciscojma86** [comment]
Reverting since it's causing some plugin test failures and regressions. https://github.com/flutter/flutter/pull/47698 (waiting for tests to pass)

**Comment by franciscojma86** [comment]
https://github.com/flutter/flutter/pull/47698 reverted
