### ISSUE TITLE
Regression in hot_mode_dev_cycle_win__benchmark hotReloadMillisecondsToFrameAfterChange 

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47688]
Seems to have regressed since https://github.com/flutter/flutter/pull/46090.

**Comment by franciscojma86** [comment]
Reverted to unblock roll.

**Comment by franciscojma86** [comment]
The reverted CL wasn't the culprit, but we have https://github.com/flutter/flutter/issues/47842 to track this now

**Comment by gspencergoog** [comment]
So, @franciscojma86, if the revert didn't fix the regression, am I free to land it again?

**Comment by franciscojma86** [comment]
Isn't it this https://github.com/flutter/flutter/pull/48094?  :)

**Comment by gspencergoog** [comment]
Awesome. I didn't see that one. Thanks.
