### ISSUE TITLE
[web][edge] Input cursor is visible

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#47694]
In Flutter for Web today, for text editing, when a user clicks (or taps on) an editable field, the framework sends its location and styling to the web engine. Web engine positions an invisible input element on the same location. 

on edge desktop the cursor is visible. we should add a different styling here for edge: 
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L23

**Comment by prateekgoel** [comment]
Hi, I am looking forward to making my first contribution to flutter. This issue seems like a good place to get started. Can I take this? I can work on this having some guidance.

**Comment by nturgut** [comment]
@prateekgoel sure! please go ahead and send a PR. you can add me as a reviewer. I added the label now.

Sorry for the late reply btw, I was mostly on holiday.

**Comment by nturgut** [comment]
We  need to change this class for text editing https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L23

**Comment by prateekgoel** [comment]
Thank you @nturgut. Will start working on this :)

**Comment by nturgut** [comment]
I investigated this issue for a few hours. the text caret is visible both in IE11 and EdgeHTML based edge. Yet it doesn't seem like there is a viable way of hiding the text caret in these browsers using css. 

There is one viable alternative for Flutter developers who needs to address this issue is in IE11 and EdgeHTML browsers. (even though it is not a good UI experience.):
- make the background color of the TextInputField the same color as the IE11 cursor
- Use a light text color. 

Please note that new blink based Edge does not have this issue.

Closing the issue as infeasible.
