### ISSUE TITLE
Document `flutter build ios-framework --cocoapods` flag on website

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#47696]
Once https://github.com/flutter/flutter/pull/47556 is promoted to stable, add documentation to https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode to demonstrate how to integrate Flutter.podspec.

```ruby
pod 'Flutter', :podspec => 'path/to/Flutter.podspec'
```

**Comment by xster** [comment]
I think it's fine to document with a caveat that it's in v1.13.6+. But you decide.

**Comment by jmagman** [comment]
@isacjunior added the needed documentation. Thank you!
