### ISSUE TITLE
[web] [edge(legacy)] Text editing tab doesn't work

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#47695]
On Windows on Edge, pressing tab on text editing doesn't work.

**Comment by pedromassangocode** [comment]
How can I reproduce this issue?

**Comment by nturgut** [comment]
@pedromassango you need to have a legacy edge installed on a windows machine. Then you need to have a few text fields in a row and try to jump between them using the tab key.

I don't think this is still an issue on new edge. I tested this when I had legacy edge installed. New edge is based on the same browser engine with chrome.

**Comment by yjbanov** [comment]
No plan to support old Edge any more.
