### ISSUE TITLE
"Unable to load asset" when the asset path contains a space

### ISSUE THREAD

**Issue by gaba41** [flutter/flutter#47705]
Another exception was thrown: Unable to load asset: assets/images/Event name.png

This happens only when the file name contains a space but it used to work on previous flutter versions.

I'm getting filenames dinamically from some Calendar APIs so that every event gets a unique event photo.

So:
`image: AssetImage("${"assets/images/" + widget.event.summary + ".png"}")`

It works fine when the "widget.event.summary" doesn't contain any space, but some events just have a space in it..

Also, the asset works fine sometimes...but only after an hot reload and never when the app runs from scratch, which is very odd!

Anybody got into this issue?

**Comment by jinghui70** [comment]
when I use chinese character as filename, I got the same exception

**Comment by SDxBacon** [comment]
Yes, I have the same issue on flutter SDK version 1.12.13+hotfix.5

**Comment by sunjianan9900** [comment]
Unhandled Exception: Unable to load asset: /data/user/0/milukun.flutter_app/app_flutter/font/zkHappy.ttf

But when i 'hot restart' my app , it works
it looks like not work at first time , but your user can not hot restart the app

**Comment by Kontra21** [comment]
Looks similar to issue  #42584 

Hopefully we can get some traction on this..

**Comment by jason-simmons** [comment]
This should be fixed on the Flutter master branch (see https://github.com/flutter/flutter/commit/0a9ff388bf51bab5af7a11b5ef297113f2d16b55 and https://github.com/flutter/flutter/issues/46163)

**Comment by VladyslavBondarenko** [comment]
Given the last message and mentioned issues I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by DamonChen117** [comment]
I still have this issue with version 1.12.13+hotfix.8

**Comment by VladyslavBondarenko** [comment]
@DamonChen117 
the fix isn't in the stable channel yet, but is already in beta (`v1.17.0-3.2.pre`), you can consider to switch to it
https://github.com/flutter/flutter/issues/55311#issuecomment-618399405

**Comment by tijanirf** [comment]
> Looks similar to issue #42584
> 
> Hopefully we can get some traction on this..

Yeah, still happening on version 1.12.13+hotfix.9. Is there any workaround available right now?
