### ISSUE TITLE
Android sensor will give wrong values for certain devices

### ISSUE THREAD

**Issue by drrnbrns** [flutter/flutter#47703]
## Steps to Reproduce

I believe I see a bug in the Android sensor plugin by looking at the source code (specifically [StreamHandlerImpl.java](https://github.com/flutter/plugins/blob/d30a04962a98cf08eb9f62b0b6a8c858d947da3c/packages/sensors/android/src/main/java/io/flutter/plugins/sensors/StreamHandlerImpl.java#L41)).

See [this article](https://android-developers.googleblog.com/2010/09/one-screen-turn-deserves-another.html) for background.  Different devices have different coordinate systems and an extra check must be done to compensate.  I don't see any adjustment so unless I missed something, some devices (especially tablets) will give erroneous values for accelerometer etc, I'll include source code below.

**Target Platform:** Android 
**Target OS version/browser:** Android (any version)
**Devices:** any with less common coordinate systems for the accelerometer

### Source
I had the same bug in my pure-Android app, and I'll include the relevant bits that fixed it in this gist:
[compensate for sensor differences](https://gist.github.com/drrnbrns/80a1b8307609831305851534a6d20251)

**Comment by iapicca** [comment]
Hi @drrnbrns 
I'm not sure that this is a Flutter issue

> I had the same bug in my pure-Android app...

you might want to open this issue for [Android](https://github.com/android) itself.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by drrnbrns** [comment]
Hi @iapicca it's not an Android issue.  If you look at the [linked article](https://android-developers.googleblog.com/2010/09/one-screen-turn-deserves-another.html), you'll see that it's something that all Android developers are expected to compensate for (by calling android.view.Display.getRotation() and compensating).  Android itself does not consider it a bug and will not change the way it works.

**Comment by stuartmorgan** [comment]
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).
