### ISSUE TITLE
How to register plugins and set transparent in FlutterFragment at V1.12.13

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#47710]
I'm following https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=cached-engine-activity-launch-java-tab to add flutter to app. But i found that we can't register plugins and set transparent any more.

before V1.12.13, I was register plugins and set transparent in onCreateView method, but now supper.onCreateView  return FlutterSplashView(and it's not public) and FlutterView.enableTransparentBackground is deprecated.

## Codes
```
public class MyFlutterFragment extends FlutterFragment {

    private String flutterId;
    private static final String GROUP = "Flutter";

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // it's return FlutterSplashView now
        // and enableTransparentBackground method is deprecated
        final FlutterView view = (FlutterView )super.onCreateView(inflater, container, savedInstanceState)  ;
        if (view != null) {
            view.enableTransparentBackground();
            PluginRegistry registry = view.getPluginRegistry();
            // registry my registry
            if (registry != null) {
               
            }
        }
        return view ;
    }
```
Also when i try to set transparent for FlutterActivity  by following https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=cached-engine-activity-launch-java-tab, i found that BackgroundMode is not in FlutterActivity, it's in FlutterActivityLaunchConfigs and it's not public.
```
  FlutterActivity
    .withNewEngine()
    .backgroundMode(FlutterActivity.BackgroundMode.transparent)
    .build(context)
```

## Flutter Doctor
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)  
    • Flutter version 1.12.13+hotfix.5 at D:\Flutter\flutter_source\stable
    • Framework revision 27321ebbad (13 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by GEiki** [comment]
I try to set transparent for FlutterAcitvity by flollowing

           Intent intent = FlutterActivity.withNewEngine().initialRoute('route').build(activity);
           intent.putExtra("background_mode","transparent");
           activity.startActivity(intent);

and it work for me .

**Comment by zmtzawqlp** [comment]
@GEiki  thanks ,and do you konw how to register plugins?

**Comment by GEiki** [comment]
@zmtzawqlp sorry，i don`t  know about that.

**Comment by zmtzawqlp** [comment]
is it the same as in Activity ? in configureFlutterEngine method?

**Comment by zmtzawqlp** [comment]
how to handle back physics button, now we can't get FlutterView from FlutterFragment

**Comment by xster** [comment]
Duping into https://github.com/flutter/flutter/issues/45747
