### ISSUE TITLE
 video not playing in 8.0.0

### ISSUE THREAD

**Issue by mohitjadav** [flutter/flutter#47718]
i was using an   video_player: ^0.10.2+5  plugin for play video from local storage,
isn't working in my 8.0.0  (Oreo)  rest of its working Well

**Comment by iapicca** [comment]
Hi @mohitjadav  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by mohitjadav** [comment]
@iapicca  please close the issue BY upgrading flutter its solved.
