### ISSUE TITLE
Enhancement to support default image in AssetImage constructor

### ISSUE THREAD

**Issue by C296539** [flutter/flutter#47722]
Currently the AssetImage method takes the asset name as a parameter. If this asset e.g. image is not found in the assets directory or bundle, an exception gets thrown. If the AssetImage constructor had another argument where we can specify the default image to use in case the primary image is not found, it will help in handling such situations gracefully. I understand that there are workaround to achieve this by checking for existence of a file etc. and then loading an appropriate image, but from the way I see, the method to load an image would be the best place to handle such scenarios natively.

**Comment by goderbauer** [comment]
The assets ship with your app, so if you are trying to load an image that isn't there, that sounds like a bug in the app. A fallback doesn't really make sense there, IMO.
