### ISSUE TITLE
ideviceinfo returned an error:    

### ISSUE THREAD

**Issue by MuthuHere** [flutter/flutter#47728]
I am getting  **ERROR: Could not connect to lockdownd, error code -8** when running my flutter app in android device

![image](https://user-images.githubusercontent.com/18752533/71405338-1d6b8600-2670-11ea-95df-d57edc35d6b1.png)

**Comment by iapicca** [comment]
I see you already opened an issue with the same contents,
please follow up there 
thank you
https://github.com/flutter/flutter/issues/47727
