### ISSUE TITLE
load the  font file from external

### ISSUE THREAD

**Issue by LNeway** [flutter/flutter#47739]
Can I  load the font file from the external file ?  the font file is too big to add to the apk file.

**Comment by jonahwilliams** [comment]
Yes! See the [FontLoader](https://api.flutter.dev/flutter/services/FontLoader-class.html) class. See also: https://github.com/flutter/flutter/issues/17910#issuecomment-445184463

**Comment by LNeway** [comment]
Great, Thanks for your help
