### ISSUE TITLE
[in_app_purchase] iOS SKError code is not sent to the client

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#47738]
An `in_app_purchase` error on iOS is modeled by class `SKError` which has the following required fields:

```bash
  /// Error [code](https://developer.apple.com/documentation/foundation/1448136-nserror_codes)
  /// as defined in the Cocoa Framework.
  final int code;

  /// Error
  /// [domain](https://developer.apple.com/documentation/foundation/nscocoaerrordomain?language=objc)
  /// as defined in the Cocoa Framework.
  final String domain;

  /// A map that contains more detailed information about the error.
  ///
  /// Any key of the map must be a valid [NSErrorUserInfoKey](https://developer.apple.com/documentation/foundation/nserroruserinfokey?language=objc).
  final Map<String, dynamic> userInfo;
```

When reporting an error back to the client, this class is converted into `IAPError`, but only the fields `domain` and `userInfo` are included, while the field `code` is omitted:

```dart
    purchaseUpdatedController
        .add(transactions.map((SKPaymentTransactionWrapper transaction) {
      PurchaseDetails purchaseDetails =
          PurchaseDetails.fromSKTransaction(transaction, receiptData)
            ..status = SKTransactionStatusConverter()
                .toPurchaseStatus(transaction.transactionState)
            ..error = transaction.error != null
                ? IAPError(
                    source: IAPSource.AppStore,
                    code: kPurchaseErrorCode,
                    message: transaction.error.domain,
                    details: transaction.error.userInfo,
                  )
                : null;
      return purchaseDetails;
    }).toList());
```
As a result, it is impossible to determine for example if the purchase was canceled by the user (`code = SKErrorPaymentCancelled`) or failed for another reason.

**Comment by talent-apps** [comment]
Any update?
Why is this plugin neglected? :(

**Comment by LHLL** [comment]
This is an error on the Apple side, not particular to this plugin:
https://forums.developer.apple.com/thread/128301
https://forums.developer.apple.com/thread/98763

**Comment by sowens-csd** [comment]
I don't think those linked issues are related. This issue is about getting the details of the error, not about whether the platform is passing back the right error code. 

Looks to me like the IAPError uses kPurchaseErrorCode because it is platform independent. The specific, and platform dependent, error codes are available from `purchaseDetails.skPaymentTransaction.error.code` on iOS. Still looking for the Android equivalent but it would be under the `purchaseDetails.billingClientPurchase` property. It looks to me like this is an intentional choice of the plugin designers to currently surface a platform independent error.

**Comment by LHLL** [comment]
On iOS platform `PurchaseDetails` [object](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart#L153) has a field called: `skPaymentTransaction` which has a `SKError` [object](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart#L221). Then you can access error code from this object.
