### ISSUE TITLE
It's possible to run file .html, .css, .js file in Flutter web?

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#47735]
how can i do for using  [ckeditor](https://ckeditor.com/) in flutter web?  it's possible to import some .html、.css、.js to dart and compile  ?

flutter version
```console
Flutter 1.13.1-pre.79 • channel master • git@github.com:flutter/flutter.git
Framework • revision 81aa2710d2 (2 weeks ago) • 2019-12-09 21:31:34 -0800
Engine • revision 2805da9e5d
Tools • Dart 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)
```

**Comment by yjbanov** [comment]
You can use [HtmlElementView](https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html) to put non-Flutter Web content inside a Flutter app. You might get better answers on StackOverflow.
