### ISSUE TITLE
textField widget with rtl input problem

### ISSUE THREAD

**Issue by idotalmor** [flutter/flutter#47745]
hello,
I am a flutter developer for quite some time, and I am building a flutter web page with textfield widgets for input some Hebrew text.
the problem is with the cursor.
we have 2 main issues:
when I am typing in Hebrew and press space the cursor is going to the start of the line
but the real issue is that I can't place the cursor in the right place where the user tapped.
it seems that the cursor is going to the location from the other side (mirror effect) I attached a video which present the issue which I am experiencing.

video:
https://imgur.com/VbYZq6B

**Comment by iapicca** [comment]
Hi @phoelapyae69 
the link you provided doesn't appear to work;
can you please provide your `flutter doctor -v` ?
Thank you

**Comment by idotalmor** [comment]
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.15.2 19C57, locale en-IL)
    • Flutter version 1.13.2 at /Users/idotalmor/flutter
    • Framework revision 4944622b5d (13 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/idotalmor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/idotalmor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by idotalmor** [comment]
btw - the link works fine for me please try again

**Comment by HansMuller** [comment]
shorturl.at/jrL26 - doesn't work for me either. Maybe just provide the complete link

**Comment by idotalmor** [comment]
https://imgur.com/VbYZq6B
hope this work

**Comment by HansMuller** [comment]
Thanks, that video link works.

**Comment by HansMuller** [comment]
CC @nturgut

**Comment by nturgut** [comment]
Thanks for filing the issue and the video. I'll have a look.

**Comment by mikron123** [comment]
I had to create a special widget so the deletion in RTL text input will work after you reach a space ' '.
To reproduce - set your widget Directionality to RTL, write a sentence with spaces, then try to hit backspace all the way.
It get's stuck after deleting 1 word, probably also because the cursor is getting mislocated.

**Comment by Vofchuk** [comment]
> I had to create a special widget so the deletion in RTL text input will work after you reach a space ' '.
> To reproduce - set your widget Directionality to RTL, write a sentence with spaces, then try to hit backspace all the way.
> It get's stuck after deleting 1 word, probably also because the cursor is getting mislocated.

Im having the exact same issue... any work around?

**Comment by mikron123** [comment]
Enjoy my ugly code.... (that works. also with an 'enter' detection)

`class _specialInput extends State<SpecialInput> {

  String _prevText;

  @override
  void initState() {

  }

  @override
  Widget build(BuildContext context) {
    if (widget.focusIfEmpty && widget.text == "" && widget.focusNode != null)
      widget.focusNode.requestFocus();

    widget.controller = new TextEditingController.fromValue(new TextEditingValue(text: widget.text,selection: new TextSelection.collapsed(offset: widget.text.length)));

    final inputFormatter = widget.keyboardType == TextInputType.number ? [WhitelistingTextInputFormatter.digitsOnly] : <TextInputFormatter>[];

    final txtInput = Container(child:
         TextFormField(controller: widget.controller,keyboardType: widget.keyboardType,
          style: widget.textStyle != null ? widget.textStyle : TextStyle(),maxLines: widget.maxLines,
          textDirection: AuxFuncs.isWeb ? TextDirection.rtl : TextDirection.ltr,textAlign: widget.textAlign,
          inputFormatters: inputFormatter,
          onChanged: (value){
            widget.text = value;
            //print(controller.selection.toString());
            // trying to delete but stuck
            if (_prevText == widget.text && widget.keyboardType != TextInputType.number)
              widget.text = widget.text.substring(0, widget.text.length - 2);
            _prevText = widget.text;
            widget.onChange(widget.text);
            setState(() {
            });
          },
          onFieldSubmitted: (str) {if (widget.onEnter != null) widget.onEnter(str);},
          autofocus: false,
          focusNode: widget.focusNode,
          decoration: InputDecoration(
            enabledBorder: UnderlineInputBorder(
              borderSide: BorderSide(color: widget.maxLines == 1 ? Colors.black45 : Colors.white.withOpacity(0)),
            ),
            focusedBorder: UnderlineInputBorder(
              borderSide: BorderSide(color: widget.maxLines == 1 ? Colors.black87 : Colors.white.withOpacity(0)),
               ),
            hintMaxLines: widget.maxLines,
            hintText: widget.prompt,
            hintStyle: TextStyle(color: Colors.black87.withOpacity(0.5),fontSize: 16),
            //prefixIcon: Icon(Icons.mail),
            contentPadding: EdgeInsets.all(5),
            border: UnderlineInputBorder(),
          ),
        ));
    return txtInput;
  }
}

class SpecialInput extends StatefulWidget {

  String text;
  double width;
  String prompt;
  TextAlign textAlign;
  TextStyle textStyle;
  Function onChange;
  bool focusIfEmpty;
  TextEditingController controller;
  Function onEnter;
  FocusNode focusNode;
  TextInputType keyboardType;
  int maxLines;

  @override
  _specialInput createState() => _specialInput();
  SpecialInput({this.prompt = "",this.focusNode, this.keyboardType = TextInputType.text, this.maxLines = 1, this.onEnter = null,this.width,this.textAlign = TextAlign.center, this.textStyle,this.controller,this.text = "", this.onChange, this.focusIfEmpty = false}){
    if (focusNode == null)
      this.focusNode = new FocusNode();
  }
}`

**Comment by TahaTesser** [comment]
Cursor issue 
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by Vofchuk** [comment]
Im having the problem as shown:
https://gyazo.com/a6dd2dcbe85a80a117355284285d2a29
![a6dd2dcbe85a80a117355284285d2a29](https://user-images.githubusercontent.com/48187154/81709545-9d0cbc80-947a-11ea-8d70-79ac84959932.gif)

the cursor is not on the right spot, and I can't pick a certain letter or area of the text to add something on the middle:
https://gyazo.com/5229786c95909c76346d95c184ca3633
![5229786c95909c76346d95c184ca3633](https://user-images.githubusercontent.com/48187154/81710199-3f2ca480-947b-11ea-9794-d62dcd8e208b.gif)


the code is basically this:
 (on the Text Field)
`TextFormField(
                    textDirection:
                        isHebrew ? TextDirection.rtl : TextDirection.ltr,
`

(isHebrew is a boolean that holds if the text being typed is in Hebrew)

Any idea how to fix that?
hope that now is more clear!

**Comment by mikron123** [comment]
you can set the cursor position to the opposite position every time it changes. (listen with a controller) 
so if the position is set on 1 and text length is 5, you will set it on 3 (since index starts from 0)

**Comment by kushalmahapatro** [comment]
Downgrading to v1.12.13+hotfix.9 makes everything fine. Tried with mater, dev and stable 1.17.1. The RTL issue still exists in these environments.

**Comment by mikron123** [comment]
1.12.13+hotfix.9 is stable, how is it possible it even supports web? The problem is about the web platform.

**Comment by kushalmahapatro** [comment]
> 1.12.13+hotfix.9 is stable, how is it possible it even supports web? The problem is about the web platform.

I havn't tried for web, but the same kind of problem persist in Mobile Apps. In RTL, after adding a space the cursor doesn't moves and unable to delete the characters type before adding space.

**Comment by AlaaEldeenYsr** [comment]
> after adding a space the cursor doesn't moves and unable to delete the characters type before adding space.
Any updates ? Does v1.12.13+hotfix.9 works with you ?
@kushalmahapatro

**Comment by olegshentz1** [comment]
The RTL issue still exist in v1.18.0-11.1.pre . Please fix this issue.

**Comment by kushalmahapatro** [comment]
> > after adding a space the cursor doesn't moves and unable to delete the characters type before adding space.
> 
> Any updates ? Does v1.12.13+hotfix.9 works with you ?
> @kushalmahapatro

Yes, @AlaaEldeenYsr For Mobile, its working fine in v1.12.13+hotfix.9.

**Comment by halahmadi** [comment]
I am facing the same issue with Arabic text (RTL). The cursor hangs out sometimes and doesn't delete or is placed in the wrong location. I am using Flutter 1.18.0-11.1.pre.

**Comment by iscriptology** [comment]
Same issue here, regression after 1.17 release

**Comment by tsionh** [comment]
same issue when trying to work with hebrew
new line is also broken...

**Comment by mdebbar** [comment]
RTL support in text fields isn't 100% complete on the web. This is not a regression.

For people who are talking about problems other than the original issue, please file separate issues.

**Comment by iscriptology** [comment]
@mdebbar This is not a web issue. This is an android/ios issue.

**Comment by kushalmahapatro** [comment]
@mdebbar, yeah this issues is in the new release of stable build for mobile, but in v1.12.13+hotfix.9, it works absolutely fine for mobile. This is main reason we are unable to use the new version of stable and sticking to v1.12.13+hotfix.9.

This is a serious issue as our app has been release in AppStore and Play Store and because of this there were may complaints from the user that they are unable to enter email and address and other details in arabic.

**Comment by bary249** [comment]
Any update/ETA?

**Comment by bary249** [comment]
Sharing a workaround that seems to help.

Adding the following parameters to the TextField Widget
  ```
   maxLines: null,
   textInputAction: TextInputAction.go, // In case you want the "ENTER" key to close the Keyboard
   keyboardType: TextInputType.text,
   minLines: 1,
```

**Comment by kushalmahapatro** [comment]
@bary249 Can you please help me in this, like adding textInputAction or making maxLines as null and minLines as 1 made it solved the issue.

**Comment by justinmc** [comment]
I've been unable to reproduce this on mobile, but I do see something strange with the cursor on web.  Can anyone tell me what I'm doing wrong to reproduce this on mobile?

Dartpad: https://dartpad.dartlang.org/bdae46dce5e05d5e950e335a008f12f4
![hebrew_web](https://user-images.githubusercontent.com/389558/85613940-4369e700-b60f-11ea-892b-35dcf02b3144.gif)

And here is an iPhone11 simulator running the same code:
<img height="82" src="https://user-images.githubusercontent.com/389558/85613983-4f55a900-b60f-11ea-8f24-dfdf0c7f549e.gif" />

**Comment by Vofchuk** [comment]
Hey guys, do we have any update on this one?
Its a really important and crucial bug...

**Comment by justinmc** [comment]
@Vofchuk Do you mean the cursor position on web?  Or otherwise can you show me how to reproduce this on iOS/Android?

**Comment by Vofchuk** [comment]
@justinmc, yes, i'm talking on the web...

Do you have any clue when the issue will be fixed?

**Comment by justinmc** [comment]
Got it.  I'm going to say that this issue is web-only then.  CC @nturgut 

The problem is that the cursor is in the wrong position, not fully to the right.

Dartpad: https://dartpad.dartlang.org/bdae46dce5e05d5e950e335a008f12f4
<img src="https://user-images.githubusercontent.com/389558/85613940-4369e700-b60f-11ea-892b-35dcf02b3144.gif" />

**Comment by Vofchuk** [comment]
SO do you have any clue when there will be a fix for this issue?

**Comment by justinmc** [comment]
I don't, sorry.  This is out of my usual area of expertise given that it's web only.

**Comment by ironpotter** [comment]
Hey guys. It's critical bug.  Can you please fix it?

**Comment by mdebbar** [comment]
RTL support in text fields isn't 100% complete on the web. This is not a regression.

For people who are talking about problems other than the original issue, please file separate issues.

**Comment by hashunst** [comment]
Im having the exact same issue in web...

**Comment by mikron123** [comment]
Anyone has a workaround? I understand that it would not be a priority if it's only for Jews who are roughly 15 million.. but there are also about half a billion Arabs, which use RTL. This should be a priority. 
Thank you

**Comment by EngAddow** [comment]
Any update on this I am having similar bug in mobile textfield with Arabic as I mentioned here #63042

**Comment by kushalmahapatro** [comment]
Hi @EngAddow , 

I was also having the same issue in mobile with Arabic but when I upgraded the SDK to the stable one, it's gone. Please have a look at the flutter doctor summary mentioned below: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.47.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by EngAddow** [comment]
> Hi @EngAddow ,
> 
> I was also having the same issue in mobile with Arabic but when I upgraded the SDK to the stable one, it's gone. Please have a look at the flutter doctor summary mentioned below:
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
> [✓] Android Studio (version 4.0)
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
> [✓] VS Code (version 1.47.3)
> [!] Connected device
> ! No devices available
> 
> ! Doctor found issues in 1 category.

sorry for the late response I have the latest stable and the problem exists , did you watch my video may be u have different scenario.

**Comment by EngAddow** [comment]
@mdebbar it is not just flutter web I have this issue in mobile so pls fix it thanks.

**Comment by idotalmor** [comment]
Hello guys and have a nice day,

This issue was originally classified as web issue and any other issue you are experiencing in any other platform should be in a different thread.
The way you are mixing all of these issue together just make it harder to resolve.

@EngAddow please open a different thread for your issue, you can always refer to this thread as an example for similar issue.

**Comment by EngAddow** [comment]
> Hello guys and have a nice day,
> 
> This issue was originally classified as web issue and any other issue you are experiencing in any other platform should be in a different thread.
> The way you are mixing all of these issue together just make it harder to resolve.
> 
> @EngAddow please open a different thread for your issue, you can always refer to this thread as an example for similar issue.

Hi @idotalmor  as you can see here [https://github.com/flutter/flutter/issues/63042#issue-674048257](url) I opened new issue with full description but the flutter team redirected me to this issue.

plz have look at the link I issued and try to give me a solution here or there thanks .

**Comment by mikron123** [comment]
Any workaround yet?

**Comment by nizar-khan** [comment]
Well it seems that the flutter team is not taking it seriously. I am losing my clients because of this problem

**Comment by nizar-khan** [comment]
Hello, is there any new news about this problem? Or is the problem still as it is ?

**Comment by xOldeVx** [comment]
please prioritize

**Comment by iscriptology** [comment]
Joining the requests. Please prioritize as this bug is hell to arabic and hebrew users.

**Comment by mikron123** [comment]
I'm joining as well! We've been waiting for such a long time for a very fundamental bug that would probably (guessing here) take 1 days to solve.
Arabic is the 5th most spoken language in the world. And Hebrew is nice too and has demand :)

**Comment by Vofchuk** [comment]
I'm joining also... We can't do anything on those languages if you don't do anything

**Comment by nilva-co** [comment]
Seriously, this issue needs to get fixed!
There is not much we can do...
This kind of issue remaining for so long is certainly not expected from flutter dev community

**Comment by mahmoudsalah37** [comment]
I can't work with this issue.

**Comment by kimeuysoo** [comment]
한국어도 동일한 문제를 겪고 있어.
flutter desktop 에서도 동일한 문제가 있어.
해결 방법을 찾을 수 없어.

**Comment by mohamadlounnas** [comment]
Any responses?

**Comment by nizar-khan** [comment]
No ، With every update I check the issue and unfortunately it still persists

**Comment by mohamadlounnas** [comment]
@nizar-khan @HansMuller @mdebbar @kf6gpe @ferhatb @mahmoudsalah37 
Hi guys
this issue is  may take a long time

There is an option to solved; it's not the best but better than nothing.
You need to use [CanvasKit ](https://skia.org/user/modules/canvaskit)
`flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true`
you need now to use custom font to render the Characters (Google fonts package may good idea)
I used for Arabic 
`TextField(
            style: GoogleFonts.cairo(),
            textDirection: TextDirection.rtl,
          )`
  and its work to me.
I don't know, but you may face some bugs but the text selection will work
i think this will work with other rtl languages
@kimeuysoo  try font that supports your language
![‪Application - Google Chrome‬ 2021-01-17 20-51-54](https://user-images.githubusercontent.com/22839194/104854318-40fe1000-5906-11eb-968b-8f9c2d5c0d33.gif)

**Comment by mahmoudsalah37** [comment]
Nice man

**Comment by nizar-khan** [comment]
@mohamadlounnas Thank you bro, I'll try - but it looks like it will work, anyway thank you very much for this solution

**Comment by MarcinusX** [comment]
What I've noticed is that in `text.dart` we are using `getRectsForRange` native method.
```
Float32List _getBoxesForRange(int start, int end, int boxHeightStyle, int boxWidthStyle) native 'Paragraph_getRectsForRange';
```
which later gets decoded in `_decodeTextBoxes`:
```
List<TextBox> _decodeTextBoxes(Float32List encoded) {
    final int count = encoded.length ~/ 5;
    final List<TextBox> boxes = <TextBox>[];
    int position = 0;
    for (int index = 0; index < count; index += 1) {
      boxes.add(TextBox.fromLTRBD(
        encoded[position++],
        encoded[position++],
        encoded[position++],
        encoded[position++],
        TextDirection.values[encoded[position++].toInt()],
      ));
    }
    return boxes;
  }
  ```
Observation:
When using RTL(Arabic) Locale but LTR(English) keyboard, on iOS it returns `TextDirection.ltr` which matches the keyboard but on Web it returns `TextDirection.rtl`.
By playing in the code and hardfixing `ltr` there, I was able to make web input with English keyboard and RTL locale work (it also broke the iOS implementation.
Still working on fixing RTL for Arabic keyboard.

**Comment by darshankawar** [comment]
@idotalmor 
I tried a sample code using latest master on web and was able to move the cursor as well as put spaces in it properly.  Note that I used Google Translation to get text in `Hebrew` and pasted in `TextFormField` to verify the bug.


https://user-images.githubusercontent.com/67046386/106740273-2fc03d80-6640-11eb-842f-be11415bb0f8.mov

```
body: Center(
        child: TextFormField(
          textAlign: TextAlign.right,
          textDirection: TextDirection.rtl,
          decoration: InputDecoration(
            hintText: 'Enter here'
          ),
        )
      )
```

Can you confirm if this is working as expected now using latest version ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.156 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 45508985b1 (7 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Comment by idotalmor** [comment]
moved to react on web implementation. much mature and production-ready.🤙

**Comment by darshankawar** [comment]
Closing this as not reproducible per my earlier comment https://github.com/flutter/flutter/issues/47745#issuecomment-772436670 and based on issue author's above comment.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by MarcinusX** [comment]
This is still not fully fixed.

It seems that the RTL on the web is fixed for RTL keyboards (like Arabic/Hebrew) but not for LTR ones (like English).

Here's the example on Flutter 2.0.1:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/16286046/110289092-3815ea80-7fe9-11eb-89ad-a08013db4a48.gif)
Here's the gist: [https://dartpad.dev/1e23cbb91c41d6e8f41df082295d3ccf?null_safety=true](https://dartpad.dev/1e23cbb91c41d6e8f41df082295d3ccf?null_safety=true)

Notice that the cursor is in a very weird place, ALMOST aligned to the right but not exactly (its 1, 2 chars before it).

Can we please reopen this issue? Logging in to our application using an English keyboard is the first thing users do, having the cursor in such a weird position will have a huge impact on the overall impression...

**Comment by TahaTesser** [comment]
Thanks! @MarcinusX, I can confirm the issue
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.165, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.165 at /Users/tahatesser/Code/flutter_master
    • Framework revision 698d438960 (5 hours ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>

**Comment by mikron123** [comment]
Why is there a "hidden space" character in the string the TextField produces?? It drove me nuts! 
Consider the next string produced using the Flutter Web input text:
סתם ‏משהו

It looks like it contains 8 chars, but it actually contains 9. which made the string comparison a nightmare, that hidden character doesn't go away with ' ' replacement and as it is saved in the DB it's obviously problematic

Same happens with this one:
Hello ‎World
There is another invisible character after the space.

**Comment by mdebbar** [comment]
@MarcinusX would you mind opening a new issue instead of re-opening this one? Your issue is slightly different from the one reported here (mention me on the new issue so I'm aware).

@mikron123 would you mind opening a separate issue for that with some code sample and more details? Like, is it happening on Android/iOS too? Please mention me on the new issue.

**Comment by ronytesler** [comment]
@mohamadlounnas 
I tried your solution but I still see the caret is not in the correct position:
![image](https://user-images.githubusercontent.com/9344207/112764373-e1606700-9010-11eb-894d-4422aa898e8b.png)

**Comment by hussamDana92** [comment]
i have the same issue
