### ISSUE TITLE
 textInputAction: TextInputAction.next failing to move user focus to next element 

### ISSUE THREAD

**Issue by JoeEarly** [flutter/flutter#47749]
## Description 

When I use **TextInputAction** and set it to **next**, the button does change on my simulator device however it doesn't do anything, User interaction is not moved into the next element. 

## Steps to Reproduce

1. Create TextField with textInputAction: TextInputAction.nex
2. Run in sim
3. See example here: https://www.loom.com/share/0b2caf634b864a9282993844e552c622

My project is here as I wasn't able to pull it out into a online editor for example as it need the sim. 
https://github.com/JoeEarly/time_tracker_flutter

**Target Platform:** 
All platforms. Tested in iOS  > 12.1 and Android 
**Target OS version/browser:** 
All available (Not running web yet)
**Devices:**
No hardware tests

## Flutter Doctor 

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/joeearly/Documents/Tools/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/joeearly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone Xs • 6FCC7D23-D5D1-46DD-8BA9-8F8919D8D6BB • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @JoeEarly 
you might want to look at this [example](https://medium.com/flutterpub/flutter-keyboard-actions-and-next-focus-field-3260dc4c694) from the community;
let me know if this approach solves the issue.
Thank you

**Comment by JoeEarly** [comment]
Hi @iapicca 

I do already handle the FocsuNnode using `FocusScope.of(context).requestFocus(nextFocus);`

You can see how in the follwing file at line 55

https://github.com/JoeEarly/time_tracker_flutter/blob/master/lib/app/sign_in/email_sign_in_form.dart

Thanks for your input

**Comment by JoeEarly** [comment]
It was a bug in my own code. For referance: https://stackoverflow.com/questions/59477239/textinputaction-textinputaction-next-failing-to-move-user-focus-to-next-element

**Comment by firatcetiner** [comment]
This is still an issue, in some scenarios `TextInputAction.next` works but in general, it doesn't. I don't want to manually change the focus since this should be working properly.

**Comment by iapicca** [comment]
> This is still an issue, in some scenarios `TextInputAction.next` works but in general, it doesn't. I don't want to manually change the focus of each form field element since this should be working properly.

@firatcetiner 
this issue was closed more than a year ago and not actively worked on
please file a new issue providing your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by firatcetiner** [comment]
@iapicca Thanks for the reply, I don't know how to give a reproducible code because I'm using literally the same `TextFormField` widgets on different screens and it works on only a few of them. I will try to fill a new issue of course. Thanks again.

**Comment by sanalkv** [comment]
if Textfield is an obscureText then its not moving to the next textfield. Instead its closing the keyboard. What's the solution ?
