### ISSUE TITLE
Problems after updating flutter 1.12.13 + hotfix.5

### ISSUE THREAD

**Issue by byteslaves** [flutter/flutter#47744]
After flutter 1.12.13 + hotfix.5 is updated, get access is available, but post access is not available. Regardless of the dio plugin or http plugin, the error log ‘Connection closed before full header was received, uri = http: // xxxxx’.

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13 + hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
[√] Android toolchain-develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
```

```yaml
Plugin:
   dio: ^ 3.0.7
   http: ^ 0.12.0 #latest version
```

Emulator:
Android Q
Android Pie
Android Oreo

build:
gradle-5.6.2-all
use AndroidX

**Comment by LH-Liu** [comment]
Problems after updating flutter 1.12.13 + hotfix.5
43/5000 
When I performed the command 'flutter run',I stayed on the waiting page for so long that I couldn't launch the android emulator
![image](https://user-images.githubusercontent.com/14884787/71417155-dfd22180-269e-11ea-9d49-4ded20dc9a27.png)

**Comment by byteslaves** [comment]
> Problems after updating flutter 1.12.13 + hotfix.5
> When I performed the command 'flutter run',I stayed on the waiting page for so long that I couldn't launch the android emulator。Does anybody know what the problem is？
> ![image](https://user-images.githubusercontent.com/14884787/71417155-dfd22180-269e-11ea-9d49-4ded20dc9a27.png)
> 
> This is my git bash logs：
> who@who-PC MINGW64 ~/Desktop
> $ flutter --version
> Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.g it
> Framework • revision [27321eb](https://github.com/flutter/flutter/commit/27321ebbad34b0a3fafe99fac037102196d655ff) (2 weeks ago) • 2019-12-10 18:15:01 -0800
> Engine • revision 2994f7e1e6
> Tools • Dart 2.7.0
> 
> who@who-PC MINGW64 ~/Desktop
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6. 1.7601], locale zh-CN)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.5)
> [√] VS Code (version 1.41.1)
> [√] Connected device (1 available)
> 
> • No issues found!

这可能是我大防火墙的功劳，你可以将   google() 和 jcenter() 这两个函数注释掉换成阿里云的镜像库试试

**Comment by LH-Liu** [comment]
> > Problems after updating flutter 1.12.13 + hotfix.5
> > When I performed the command 'flutter run',I stayed on the waiting page for so long that I couldn't launch the android emulator。Does anybody know what the problem is？
> > ![image](https://user-images.githubusercontent.com/14884787/71417155-dfd22180-269e-11ea-9d49-4ded20dc9a27.png)
> > This is my git bash logs：
> > who@who-PC MINGW64 ~/Desktop
> > $ flutter --version
> > Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.g it
> > Framework • revision [27321eb](https://github.com/flutter/flutter/commit/27321ebbad34b0a3fafe99fac037102196d655ff) (2 weeks ago) • 2019-12-10 18:15:01 -0800
> > Engine • revision 2994f7e1e6
> > Tools • Dart 2.7.0
> > who@who-PC MINGW64 ~/Desktop
> > $ flutter doctor
> > Doctor summary (to see all details, run flutter doctor -v):
> > [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6. 1.7601], locale zh-CN)
> > [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> > [√] Android Studio (version 3.5)
> > [√] VS Code (version 1.41.1)
> > [√] Connected device (1 available)
> > • No issues found!
> 
> 这可能是我大防火墙的功劳，你可以将 google() 和 jcenter() 这两个函数注释掉换成阿里云的镜像库试试

 原来借了我大天朝程序猿的楼  \捂脸，正在试。主要之前一直都跑的好好地，更新到这个版本后忽然不行了。。。

**Comment by iapicca** [comment]
Hi  @byteslaves  @LH-Liu 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your `flutter run --verbose`
thank you

**Comment by byteslaves** [comment]
> Hi @byteslaves @LH-Liu
> could you please run
> `flutter clean`
> `flutter pub cache repair`
> 
> If the issue persist please provide your `flutter run --verbose`
> thank you



> Hi @byteslaves @LH-Liu
> could you please run
> `flutter clean`
> `flutter pub cache repair`
> 
> If the issue persist please provide your `flutter run --verbose`
> thank you

Hello, I'm trying your method now, but the network is too slow, you need to wait for a while, I hope flutter can return to normal

**Comment by byteslaves** [comment]
@iapicca 
My problem has been solved, because of China Great Firewall, I set up a proxy in Android studio, and the open Android emulators all use a proxy network, so the post request was dropped by the proxy software. China Great Firewall is so cute, most of the problems I encountered in studying Flutter are caused by it! Thanks a lot for iapicca's help.

**Comment by LH-Liu** [comment]
> previous
> Hello, I'm trying your method now, but the network is too slow, you need to wait for a while, I hope flutter can return to normal

Yes，My problem has been solved, because of China Great Firewall。when I comment out the two functions google () and jcenter () and replace them with Alibaba Cloud's mirror library, Repeat the command "flutter clean" and "flutter run" , it has returned to normal. Thank you for your reply, and the same to @anaisbetts
