### ISSUE TITLE
Generating PDF file from app text in flutter

### ISSUE THREAD

**Issue by UmarFarooqkhan9** [flutter/flutter#47750]
For example i have a text in the body of the page on my flutter app like 'hello world' and i have a button for generating this text in pdf format and preview this pdf file also... So is there any solution for doing this in flutter.i already tried many dart packages like pdf and printing but it's not working as i need.

**Comment by JoeEarly** [comment]
Can you give us an example of what you have tried so far

**Comment by tirth-aubergine** [comment]
I've built an app like that.

GitHub - https://github.com/AubergineDevelopers/Holden

Medium - https://medium.com/aubergine-solutions/introducing-holden-a-certificate-generator-app-using-flutter-f80836baa00a

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/14259
https://github.com/flutter/flutter/issues/34221

**Comment by iapicca** [comment]
Hi @UmarFarooqkhan9 
given this [message](https://github.com/flutter/flutter/issues/17685#issuecomment-452519831)
I feel safe to close this issue.

You may want to follow up on this [issue](https://github.com/flutter/flutter/issues/14259) for future updates
Thank you
