### ISSUE TITLE
API Docs full text search

### ISSUE THREAD

**Issue by tanhenggek** [flutter/flutter#47760]
## Use case
Search bar in the API Docs helps us find the right information quickly. But, it can be improved with full text search capability. For example, if I search `CupertinoScaffold` keyword, it would be great if `CupertinoPageScaffold` is returned in the search results. 

<img width="1194" alt="Screenshot 2019-12-25 at 10 16 29 AM" src="https://user-images.githubusercontent.com/8288307/71429066-b39abd00-26ff-11ea-9221-9980d9a3cda5.png">

## Proposal
Algolia is a good tool for Open Source project documentation. It is widely used by other Open Source projects such as React, TypeScript, and Scala. 

#### References
- API Docs: https://api.flutter.dev/
- Algolia: https://www.algolia.com/for-open-source/

**Comment by godofredoc** [comment]
Obsolete.
