### ISSUE TITLE
Flutter for web in debug mode

### ISSUE THREAD

**Issue by iampopal** [flutter/flutter#47766]
Flutter for the web in debug mode not works with Bloc library. but it works in release mode.

**Comment by iapicca** [comment]
Hi @iampopal 
[bloc](https://pub.dev/packages/bloc) is undoubtedly great, but it's a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/felangel/bloc/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by iampopal** [comment]
I have already talked with [felangel ](https://github.com/felangel), he told me that this is a problem dar2js, bloc work fine.
