### ISSUE TITLE
why flutter_embedding_release.jar do not support androidx

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#47775]
![image](https://user-images.githubusercontent.com/4476322/71439828-01321c80-2736-11ea-818b-743d1b3a1d87.png)

`http://download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_release-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.jar`

`flutter_embedding_release-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.jar`

**Comment by bravekingzhang** [comment]
I have found way to convert jar to support andriodX
https://github.com/mikehardy/jetifier#usage-for-jarzipaar-files


npx jetifier-standalone -i flutter_embedding_release.jar -o flutter_embedding_release.jar

**Comment by iapicca** [comment]
Hi @bravekingzhang 
I'm glad that you solved the issue,
thank you for letting me know
