### ISSUE TITLE
Make timeline support systrace to analyze performance more effectively

### ISSUE THREAD

**Issue by yuanhuihui** [flutter/flutter#47771]
**1. Background**

Timeline can't view cpu and other related system information, which is very important for performance analysis. Especially the flutter hybrid project, you need to check platform trace and flutter trace at the same time.

**2. Issues**

Make timeline support for systrace to assist in analyzing performance issues.

- https://github.com/dart-lang/sdk/issues/39726
- https://github.com/dart-lang/sdk/issues/39757
- https://github.com/dart-lang/sdk/issues/39727

**3. Solutions**

dart-sdk repository

- support async events for systrace: https://dart-review.googlesource.com/c/sdk/+/127920
- support dart vm events for systrace: https://dart-review.googlesource.com/c/sdk/+/128200
- support sync events for systrace: https://dart-review.googlesource.com/c/sdk/+/127921

engine repository

- support API stream for systrace: https://github.com/flutter/engine/pull/14323
- timeline can be enabled in release mode: https://github.com/flutter/engine/pull/14521
- Fix missing timeline event of flutter engine's startup time: https://github.com/flutter/engine/pull/14319

flutter repository

- fix duration event of timeline summary: https://github.com/flutter/flutter/pull/47742

**4. Results**

`flutter run --trace-systrace `,  capture systrace as below:

![d8c9e40c-6e45-43e3-b643-fd925dd271d0](https://user-images.githubusercontent.com/4338041/71499013-b16c6600-2899-11ea-8f23-b28ea7c625fb.png)

After optimization. We can see the synchronous and asynchronous events of the dart and c++ layers, as below:
![8777b70c-f0d6-4f01-9413-bf11919ee184](https://user-images.githubusercontent.com/4338041/71499045-cf39cb00-2899-11ea-8993-5e3d889b44bc.png)

Later, I will further share which flutter performance issues only systrace can find the root cause in Android, and timeline is incapable. Because timeline does not capture system traces and CPU schedules, such as surfaceFlinger.

**Comment by zanderso** [comment]
All the listed sub issues and PRs are closed and landed respectively, so I am optimistically assuming that this issue can also be closed. Please feel free to re-open with updated information if this is not yet done.
