### ISSUE TITLE
Atom: Analyzer doesn't notice adding a class to an export ... show list

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4777]
I have Atom open on the entire flutter repo.

Just now I added a subclass of GridDelegate to `examples/flutter_gallery/lib/demo/shrine/shrine_home.dart`

Doing so exposed the fact that we don't currently export the GridChildPlacement class, which GridDelegate depends on. Running the app failed (as you'd expect).

Adding GridChildPlacement to `packages/flutter/lib/src/widgets/basic.dart`
```
export 'package:flutter/rendering.dart' show
    ...
    GridChildPlacement,
    ...
```
corrected the problem (the app runs OK) but the Analyzer still reports a warning in Atom:

![screenshot](https://cloud.githubusercontent.com/assets/1377460/16424036/5faca35e-3d13-11e6-9ee3-e4bf3400209c.png)

**Comment by pq** [comment]
Thanks @HansMuller!  Adding @bwilkerson FYI.

I just tried to repro this locally with TIP but couldn't.   It's possible that it's fixed (or that the issue is more nuanced).  I'll do some more digging! 

@abarth: I wonder if we should add a new Label for Analysis related issues?

**Comment by abarth** [comment]
@pq I've created "dependency: analyzer"

**Comment by HansMuller** [comment]
An important detail I left out is that I didn't edit basic.dart in Atom, I used emacs.  Sorry to have left that out.

**Comment by pq** [comment]
That's helpful.  Thanks!  This feels like the same issue we were seeing when we visited last week.  If so, fingers-crossed, @scheglov  has it licked in https://github.com/dart-lang/sdk/commit/662a461988b5097a0e7f48628e4330aaf9447b59 which should get to you tomorrow with the new dev build of the SDK.

**Comment by pq** [comment]
As of https://github.com/flutter/flutter/pull/4790 and https://github.com/flutter/flutter/pull/4793, this should be fixed.  Please reopen if the issue persists!
