### ISSUE TITLE
Flaky json-rpc errors on Chromium buildbot

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4778]
Looks like we're getting occasional json-rpc errors on Chromium's buildbot in trying to invoke [`FlutterDriver._sendCommand`](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart#L196) -- most recently seen at https://build.chromium.org/p/client.flutter/builders/Mac/builds/1298/steps/drive%20sample_app/logs/stdio

It's unclear whether or not this is Mac-specific

**Comment by Hixie** [comment]
I'm going to close this. If this is still a flake that happens then we'll catch it via our current flake collection mechanism.
