### ISSUE TITLE
palette_generator fromImageProvider block ui

### ISSUE THREAD

**Issue by liaobushi520** [flutter/flutter#47789]
when ImageProvider is NetworkImage ,fromImageProvider will block ui

**Comment by liaobushi520** [comment]
///  very serious   *****
  // return await PaletteGenerator.fromImageProvider(NetworkImage(imageURL));

  /// serious **
  ReceivePort receivePort = ReceivePort();
  await Isolate.spawn(entryPoint, receivePort.sendPort);
  SendPort sendPort = await receivePort.first;
  Uint8List bytes = await sendReceive(sendPort, imageURL);
  var image =
      (await (await ui.instantiateImageCodec(bytes)).getNextFrame()).image;
  return await PaletteGenerator.fromImage(image);

**Comment by iapicca** [comment]
Hi @liaobushi520 
does this [code](https://gist.github.com/iapicca/2a9d7b620fe4898415fa026ac15f70c8) represent the issue you are describing?
thank you
