### ISSUE TITLE
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by ffalpha** [flutter/flutter#47787]
Can someone tell me why am I getting this error?Project worked fine until this evening and suddenly I t wont work.One year of work has finished within a second .Any help ?

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Read timed out
   > Could not resolve com.google.android.gms:play-services-measurement-base:[16.5.0].
     Required by:
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement:16.5.0
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-api:16.5.0
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-sdk:16.5.0
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > Unable to load Maven meta-data from http://download.flutter.io/com/google/android/gms/play-services-measurement-base/maven-metadata.xml.
            > Could not get resource 'http://download.flutter.io/com/google/android/gms/play-services-measurement-base/maven-metadata.xml'.
               > Could not GET 'http://download.flutter.io/com/google/android/gms/play-services-measurement-base/maven-metadata.xml'.
                  > Read timed out
   > Could not resolve com.google.android.gms:play-services-measurement-impl:[16.5.0].
     Required by:
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement:16.5.0
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-api:16.5.0
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-sdk:16.5.0
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:[16.5.0].
     Required by:
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-api:16.5.0
         project :app > com.google.firebase:firebase-core:16.0.9 > com.google.firebase:firebase-analytics:16.5.0 > com.google.android.gms:play-services-measurement-sdk:16.5.0
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       106.8s
Gradle task assembleDebug failed with exit code 1

**Comment by ffalpha** [comment]
This is my pubsec.yaml file
name: you2auth
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  datetime_picker_formfield: ^0.4.3
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.0.6
  google_sign_in: ^4.0.7
  flutter_launcher_icons: ^0.7.3
  http: ^0.12.0+2
  file_picker: ^1.4.0+1
  image_picker: ^0.6.1+4
  provider: ^3.1.0
  rxdart: ^0.22.2
  font_awesome_flutter: ^8.5.0
  image_cropper: ^1.0.2
  intro_views_flutter: ^2.7.0
  geoflutterfire: ^2.0.3+6
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+15
  connectivity: ^0.4.5+2
  flutter_widget_from_html_core: ^0.2.3+3
  simple_animations: ^1.3.3
  page_transition: ^1.1.4
  bubble: ^1.1.9+1
  url_launcher: ^5.4.1
  




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter







flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/logo/logo.png
    - assets/images/on1.png
    - assets/images/bg1.png
    - assets/images/ic_launcher.png
    - assets/aa.png
    - assets/Rcenter/
    - assets/images/silver.jpg
    - assets/images/sliver2.gif
    - assets/QA/
    - assets/Onborad/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by ffalpha** [comment]
This is my dependencies 

dependencies:

  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  datetime_picker_formfield: ^0.4.3
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.0.6
  google_sign_in: ^4.0.7
  flutter_launcher_icons: ^0.7.3
  http: ^0.12.0+2
  file_picker: ^1.4.0+1
  image_picker: ^0.6.1+4
  provider: ^3.1.0
  rxdart: ^0.22.2
  font_awesome_flutter: ^8.5.0
  image_cropper: ^1.0.2
  intro_views_flutter: ^2.7.0
  geoflutterfire: ^2.0.3+6
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+15
  connectivity: ^0.4.5+2
  flutter_widget_from_html_core: ^0.2.3+3
  simple_animations: ^1.3.3
  page_transition: ^1.1.4
  bubble: ^1.1.9+1
  url_launcher: ^5.4.1

**Comment by ffalpha** [comment]
I reinstall flutter it fixed my issue. Still couldn't figure out what went wrong

**Comment by vguttmann** [comment]
What did you reinstall? The plugin or the SDK?

**Comment by bortan01** [comment]
sucede lo siguiente (al menos en mi caso)  en android\app\build.gradle, en dependencies { ...}
yo tenia 
implementation 'com.google.firebase: firebase-messaging:20.2.3', con un espacio, lo que hice fue
implementation 'com.google.firebase:firebase-messaging:20.2.3' sin nungun espacio
y todo se soluciono

**Comment by LiPingCodingGithub** [comment]
我也遇到了这样的问题，请问您已经解决了吗
