### ISSUE TITLE
[webview_flutter] ios build error FlutterMethodChannel

### ISSUE THREAD

**Issue by q1104133609** [flutter/flutter#47788]
### my error message

```bash
In file included from
    /Users/huangb/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.14/ios/Classes/JavaScriptChannelHandler.m:5:
    /Users/huangb/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.14/ios/Classes/JavaScriptChannelHandler.h:12:40: error:
    expected a type
    - (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
                                           ^
    /Users/huangb/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.14/ios/Classes/JavaScriptChannelHandler.m:8:3: error:
    unknown type name 'FlutterMethodChannel'
      FlutterMethodChannel* _methodChannel;
      ^
    /Users/huangb/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.14/ios/Classes/JavaScriptChannelHandler.m:12:40: error:
    expected a type
    - (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
                                           ^
    /Users/huangb/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.14/ios/Classes/JavaScriptChannelHandler.m:29:17: warning:
    unused variable 'arguments' [-Wunused-variable]
      NSDictionary* arguments = @{
                    ^
    1 warning and 3 errors generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is
    8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')
```

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A603, locale
    en-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/huangb/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/huangb/Library/Android/sdk
    • Android NDK at /Users/huangb/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @q1104133609 

given the error
```bash 
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is
    8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')
```
and the version of webview in use `webview_flutter-0.3.14`;

could you please
update in your `pubspec.yaml` `webview_flutter`  to `0.3.18+1`
and then run  `flutter clean` and `flutter pub cache repair`?

Let me know if  the issue persists
thank you

**Comment by dnfield** [comment]
We don't support iOS 4.3.

**Comment by aTeamSolace** [comment]
> We don't support iOS 4.3.

I'm facing this issue for the last some days when building the application iOS. My question is how to solve this now?

**Comment by dnfield** [comment]
Raise your deployment target to at least 8.0

**Comment by aTeamSolace** [comment]
@dnfield our deployment target is 9.0 but still getting the same issue 
we have already tried with flutter clean, Flutter pub get, pod install, etc. 
same code is running before but when we are going to achieve the app then this issue occurred any solution you have?

**Comment by dnfield** [comment]
You should file a new bug, including your logs and flutter version

**Comment by aTeamSolace** [comment]
> new bug

Okay

**Comment by Harshmaster** [comment]
> @dnfield our deployment target is 9.0 but still getting the same issue
> we have already tried with flutter clean, Flutter pub get, pod install, etc.
> same code is running before but when we are going to achieve the app then this issue occurred any solution you have?

Did you find the solution ? I also have the same probem.

**Comment by Harshmaster** [comment]
> > We don't support iOS 4.3.
> 
> I'm facing this issue for the last some days when building the application iOS. My question is how to solve this now?

Did you find the solution ? I also have the same probem.

**Comment by bbence84** [comment]
For those of you having this issue, I finally managed by recreating the whole iOS project of the flutter project. Steps:

0. Backup ios folder in the project folder and delete the ios folder from the project folder
1. Recreated ios project using flutter command in terminal (you have to be in the project folder): "flutter create -i swift ." (note, there's a . at the end!)
2. Run "flutter clean" in the terminal
3. Run "flutter pub get" in the terminal
4. Go to the ios folder in terminal, and run command "pod install"
5. Overwrote Info.plist from backup in Runner folder
6. Added GoogleService-Info.plist using xcode (select runner folder first) -- it's important to add it via Xcode!!!
7. Open Xcode project and change to Signing and Capabilities / specify Team
