### ISSUE TITLE
Failing to resolve issue "Android license status unknown" which pops up after running flutter doctor -v

### ISSUE THREAD

**Issue by ruchir-123** [flutter/flutter#47799]
1. Run flutter doctor -v
2. In the second category ,I am unable to resolve the error "Android licence status unknown. Try re-installing or updating your Android SDK Manager."
3. I have updated the sdk manager also but still the error persist

## Logs

C:\Users\HP\AppData\Local\Android\Sdk\tools\bin>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (8 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by srburton** [comment]
@ruchir-123 

Merry Christmas, take a look at the link below ....

https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences

**Comment by iapicca** [comment]
Hi @ruchir-123 
please run `flutter doctor --android-licenses`.

I see you are using a VERY old version of Flutter;
you may want to run also
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
let me know if the issue persists.
thank you

**Comment by VladyslavBondarenko** [comment]
Hi @ruchir-123 
Given that you haven't respond about issue persisting and thumbed up the last comment
I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
