### ISSUE TITLE
Flutter API online docs use (almost) invisible font

### ISSUE THREAD

**Issue by tatumizer** [flutter/flutter#47796]
Flutter API docs are almost invisible when viewed online at https://api.flutter.dev/.
I checked the styles: the font is Roboto, sans-serif, served from network font Roboto, weight 300.
When the same document (dart.core) is viewed on https://api.dartlang.org/, Windows selects Arial for rendering (b/c there's no network font); weight is not specified.
You can see the difference below:
![dart-api-flutter-font](https://user-images.githubusercontent.com/778217/71451041-d21ea980-273b-11ea-92c3-fe841c57b7dd.jpg)
![dart-api-normal-font](https://user-images.githubusercontent.com/778217/71451045-dba81180-273b-11ea-9ef8-7db5183028a0.jpg)

**Comment by awulkan** [comment]
Some more examples of just how thin the text is (which I initially reported [here](https://github.com/flutter/flutter/issues/47849)):

**Example 1:**
![Example1](https://i.imgur.com/iwjAfLR.png)

**Example 2:**
![Example2](https://i.imgur.com/4lHv6Z8.png)

I find it very hard to read the text.
