### ISSUE TITLE
_getSupportedEmbeddings claims kotlin file exists even when it doesn't

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47803]
In `_getSupportedEmbeddings`, if neither the Java nor the Kotlin file exists, we report an error that says the Kotlin file exists but can't be read.

You can reproduce this by trying to use the `image_saver` plugin, because its Java file is in a different directory than the package name would suggest, and so the new code just fails to handle it entirely.

(See also #47802, which is a minor bugi n the same code.)

cc @blasten

**Comment by blasten** [comment]
I will fix this issue. In the meanwhile, https://github.com/Serjlee/image_saver/pull/1 should also fix the issue.
