### ISSUE TITLE
"Couldn\'t read file $mainPluginClass even though it exists." does not print file path

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47802]
I got the following confusing error from the tool:

```
Couldn't read file Instance of 'ErrorHandlingFile' even though it exists. Please verify that this file has read permission and try again.
```

It's generated by this code:
https://github.com/flutter/flutter/blob/449f4a6673f6d89609b078eb2b595dee62fd1c79/packages/flutter_tools/lib/src/platform_plugins.dart#L112-L115

The error here is that `$mainPluginClass` should be `${mainPluginClass.path}` because `File` objects don't have a useful `toString`.

**Comment by Hixie** [comment]
cc @blasten who last touched this line

**Comment by zanderso** [comment]
Should have been fixed by https://github.com/flutter/flutter/commit/8b139a8c41b228868582c15c90514c293af3fa5d
