### ISSUE TITLE
Problems with new Android plugins APIs

### ISSUE THREAD

**Issue by RodrigoSMarques** [flutter/flutter#47801]
I am migrating a plugin by following the guidelines of the https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration link
The plugin worked on the latest stable release.
I have verified that the onAttachedToEngine method is being called twice at runtime and this is causing problems in my plugin. The variables are being restarted with each execution
I developed a little sample code and put a log script which demonstrates that the method is called twice.

Below the plugin Java code:

```dart
package br.com.rsmarques.flutter_plugin_test;

import android.app.Activity;
import android.content.Context;
import android.util.Log;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.Registrar;

/** FlutterPluginTestPlugin */
public class FlutterPluginTestPlugin implements FlutterPlugin, MethodCallHandler {
  private static final String DEBUG_NAME = "FlutterPluginTest";
  private Activity activity;
  private Context context;
  private static final String MESSAGE_CHANNEL = "flutter_plugin_test/message";

  private MethodChannel methodChannel;

  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    Log.d(DEBUG_NAME, " onAttachedToEngine");
    setupChannels(flutterPluginBinding.getFlutterEngine().getDartExecutor(), flutterPluginBinding.getApplicationContext());
  }

  // This static function is optional and equivalent to onAttachedToEngine. It supports the old
  // pre-Flutter-1.12 Android projects. You are encouraged to continue supporting
  // plugin registration via this function while apps migrate to use the new Android APIs
  // post-flutter-1.12 via https://flutter.dev/go/android-project-migration.
  //
  // It is encouraged to share logic between onAttachedToEngine and registerWith to keep
  // them functionally equivalent. Only one of onAttachedToEngine or registerWith will be called
  // depending on the user's project. onAttachedToEngine or registerWith must both be defined
  // in the same class.
  public static void registerWith(Registrar registrar) {
    Log.d(DEBUG_NAME, " registerWith");
    FlutterPluginTestPlugin plugin = new FlutterPluginTestPlugin();
    plugin.setupChannels(registrar.messenger(), registrar.context());
  }
  private void setupChannels(BinaryMessenger messenger, Context context) {
    Log.d(DEBUG_NAME, "setupChannels");
    this.context = context;
    this.activity = null;
    methodChannel = new MethodChannel(messenger, MESSAGE_CHANNEL);
    methodChannel.setMethodCallHandler(this);
  }
  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    Log.d(DEBUG_NAME, "onMethodCall" + " - " + call.method.toString());
    if (call.method.equals("getPlatformVersion")) {
      result.success("Android " + android.os.Build.VERSION.RELEASE);
    } else {
      result.notImplemented();
    }
  }

  @Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
  }
}
```
Execution Log:
```dart
12-26 03:17:07.093 10844-10844/? D/FlutterPluginTest:  onAttachedToEngine
12-26 03:17:07.093 10844-10844/? D/FlutterPluginTest: setupChannels
12-26 03:17:07.103 10844-10844/? D/FlutterPluginTest:  onAttachedToEngine
12-26 03:17:07.103 10844-10844/? D/FlutterPluginTest: setupChannels
12-26 03:17:10.633 10844-10844/br.com.rsmarques.flutter_plugin_test_example D/FlutterPluginTest: onMethodCall - getPlatformVersion
```
My environment:

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at /Users/Rodrigo/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rodrigo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • GT I9500             • 4d00bc752191211b                         • android-arm • Android 5.0.1 (API 21)
    • iPhone 6S do Rodrigo • d97e153b8fe78b995970b675ad60edfb05491bfd • ios         • iOS 13.3
    • iPhone 11 Pro Max    • DF636696-B8BC-4A02-B083-636ABF55CF54     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

**Comment by LichKing-2234** [comment]
I have the same problem, I remove this code from my MainActivity.
`GeneratedPluginRegistrant.registerWith(this)`
because flutter engine will run this function by itself

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/71460054-334e8780-27e5-11ea-86f4-6fb51ffc40ee.png)

**Comment by RodrigoSMarques** [comment]
> I have the same problem, I remove this code from my MainActivity.
> `GeneratedPluginRegistrant.registerWith(this)`
> because flutter engine will run this function by itself

It really worked.
Is the host app being generated with wrong code?

**Comment by LichKing-2234** [comment]
I think the templates code need to be change
[https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/android-java.tmpl/app/src/main/java/androidIdentifier/MainActivity.java.tmpl](url)

**Comment by LichKing-2234** [comment]
flutter plugin should not be registered twice, I think it is an ignored bug

**Comment by RodrigoSMarques** [comment]
After reading the plugin migration documentation again, I found that I had skipped a step.
The plugin initialization is working as expected now.

```dart
package io.flutter.plugins.firebasecoreexample;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.firebase.core.FirebaseCorePlugin;

public class MainActivity extends FlutterActivity {
  // You can keep this empty class or remove it. Plugins on the new embedding
  // now automatically registers plugins.
}
```

**Comment by patrick-fu** [comment]
> > I have the same problem, I remove this code from my MainActivity.
> > `GeneratedPluginRegistrant.registerWith(this)`
> > because flutter engine will run this function by itself
> 
> It really worked.
> Is the host app being generated with wrong code?

I also found this problem, version 1.12+hotfix.8 still automatically generated this line of code
