### ISSUE TITLE
dart Analyzer has stopped in vs code, prompt to restart again

### ISSUE THREAD

**Issue by rahulk8** [flutter/flutter#47821]
My analyzing takes a lot of time.
flutter Takes much time to build apk/appbundle or run a app in vs code .
version updated to : v1.12.13 hotfix.5

**Comment by marcos930807** [comment]
similar to this #46616

**Comment by BondarenkoStas** [comment]
Hi @rahulk8,
Please follow up on that issue [#46616](https://github.com/flutter/flutter/issues/46616), mentioned by @marcos930807 (thanks!)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
