### ISSUE TITLE
Ray assumes unit direction vector

### ISSUE THREAD

**Issue by DrPaulT** [flutter/flutter#47830]
I'm using vector_math-2.0.8/lib/src/vector_math_64/ray.dart for a ray-sphere intersection test, but I think the method supplied will only work correctly if the _direction component of a ray is a unit vector.

It also seems that at least one other method in the same file, at, assumes that _direction also has a magnitude of one.

There's nothing I've seen in the class or the documentation to suggest that the caller would know by convention that a unit vector is needed here, and actually to preserve the generality of the ray routines, I don't think we would require _direction to be a unit vector at the caller's end.

To fix this, we could normalise the direction vector in these two methods.  For intersectsWithSphere, I think line 57 could be changed to:

`final double s = l.dot(_direction.normalized());`

And for at, line 40 could be:

`Vector3 at(double t) => _direction.normalized().scale(t)..add(_origin);`

Does this sound like a good plan?

(Ps. just looking through the file, looks like generally the direction vector might need normalising before use eg. in copyAt.  Don't understand enough about the other intersection routines to have assessed those yet.)

**Comment by kf6gpe** [comment]
You might want to file this over at the dart-lang repository, or engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
