### ISSUE TITLE
Hard to click commit on performance dashboard

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47838]
I'm trying to figure out which Flutter commits might be causing regressions and it's pretty difficult to click on the commit link to inspect whether or not the commit might be the cause of the regression.

It could be good to perhaps make each bar tappable so that the link persists and can be clicked on.

![clicking-commit-on-performance-dashboard](https://user-images.githubusercontent.com/27032613/71486098-81559200-27c9-11ea-869c-82d9364a647e.gif)

**Comment by godofredoc** [comment]
Closing as obsolete. Performance dashboard was deprecated.
