### ISSUE TITLE
Trouble with signing in to Flutter build dashboard

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47832]
I was trying to sign into the [Flutter build dashboard](https://flutter-dashboard.appspot.com/#/build) to debug a task failure by checking the logs, but clicking on the "Sign in" button did not do anything.

I checked my other machine because I remember being signed into the dashboard, and it was. Downloading the logs from there also seemed to work. However, once I signed out, I could no longer sign back in. 

cc/ @CaseyHillers

**Comment by CaseyHillers** [comment]
Thanks for filing this!

What browser is this happening in?

Are there any errors in the console?

**Comment by shihaohong** [comment]
I don't see any errors in the console. I was on Chrome for both machines. I just tested Safari on my macOS device as well, and it's the same result.

**Comment by Piinks** [comment]
I am also experiencing this. Mac-Chrome. I have a tab that still has me logged in, but in a new tab I am stuck signed out.

**Comment by CaseyHillers** [comment]
I was able to reproduce this. It took me a few sign in, sign outs, but i'm locked out too now :)

As a work around, the old build dashboard is still live at https://flutter-dashboard.appspot.com/old_build.html. You can log in at the performance dashboard.

**Comment by shihaohong** [comment]
To add some color to the workaround if anybody needs it: 
1. Go to [Performance dashboard](https://flutter-dashboard.appspot.com/benchmarks.html)
2. Click on the "Sign In" button on the bottom left of the page
3. Go to the dashboard page you have to be in.

After using the workaround, I noticed perhaps a different bug where it might still show the "Sign In" button instead of your avatar, even though you are actually signed in. Downloading the logs seem to work, and refreshing the page a couple of times might show your avatar every now and then, and the "Sign In" button every other time.

**Comment by CaseyHillers** [comment]
@ditman do you know why this would be occurring? I have a basic version running at https://testchillers-dot-flutter-dashboard.appspot.com/#/

This version does not include the Google Analytics scripts and is running version 0.8.2+1 of google_sign_in_web.

From some initial debugging, the plugin is not making any network requests.

**Comment by ditman** [comment]
@CaseyHillers, When I look at the root Cocoon page (the one with 3 large buttons to pick which dashboard to see), it seems to work all the time? My user account is picked up Just Fine ™.

Maybe it's a race condition / setState issue in the build dashboard, where the sign in status is lost after the main Ajax requests end? 

_(This is pure speculation, I haven't even looked that code yet)_

**Comment by CaseyHillers** [comment]
@ditman I made a few fixes to the state in Cocoon to only have the Google Sign In Plugin created once, and it passes it around. This fixes some of the perceived issues.

However, I am noticing this is happening on deployed versions of the app (I cannot reproduce locally, even with network throttling):

1. `GoogleSignIn.signInSilently()` is called, updating the current signed in user to `GoogleSignInAccount:{displayName: null, email: null, id: null, photoUrl: null}`
2. Calling `GoogleSignIn.signIn()` does not open the expected sign in flow. It does not make any network requests and finishes almost immediately. Another case I have seen is that it never finishes, but still never makes a network request.

Demo: https://testchillers1-dot-flutter-dashboard.appspot.com/#/

I have added some basic debug statements that print to the console for this projects calling statements to the plugin.

The code is available at https://github.com/flutter/cocoon/blob/76b20b5df156bfa9f164e1cbe18f01edf9b10964/app_flutter/lib/service/google_authentication.dart

**Comment by ditman** [comment]
Assigning myself so I don't lose track of this :)

**Comment by ditman** [comment]
It seems that some times the `signInSilently` method never completes its promise (not even with a `null` user), and that might be causing problems down the line.

I'm having a little bit of trouble minimally reproducing the issue, but it *seems* that a soft flutter reload triggers the issue in Cocoon. 

I'll try to repro the issue in the google_sign_in plugin example so I can work on this in isolation.

**Comment by CaseyHillers** [comment]
As a workaround, I have disabled silent sign in on Cocoon. We will have to manually sign in until we can fix the silent sign in issue.

**Comment by ditman** [comment]
> As a workaround, I have disabled silent sign in on Cocoon. We will have to manually sign in until we can fix the silent sign in issue.

@CaseyHillers A Fix Is Coming. 🐺
