### ISSUE TITLE
Regression in linux_chrome_dev_mode

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47840]
`InitialStartupTime` seems to be consistently above the baseline since 18 Dec 2019. The [commit since it started](https://github.com/flutter/flutter/commit/c235998acf17206c6ce411af235faf439d9ff7b2) does not seem suspicious, but I'm also unsure how introducing implicit casts affects performance.

**Comment by jonahwilliams** [comment]
I've re-baselined this benchmark. The overall time seems to be slightly bimodal, but at any rate we'll be drastically changing the implementation here in Q1 so the particular numbers aren't that important to me
