### ISSUE TITLE
Regression in smoke_catalina_hot_mode_dev_cycle__benchmark

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47842]
`hotReloadMillisecondsToFrameAfterChange` has been consistently over the baseline since [this change to visual density](https://github.com/flutter/flutter/commit/924efae96c34cdf2f4b78f219f36419a68b0b4e8), but it has already been reverted and is very unlikely to be the culprit. 

The first spike in this benchmark occurs at [this particular engine roll](https://github.com/flutter/flutter/commit/0db029990707cf98d79d66c45802207dce768891). It didn't exceed the baseline on the commit, but the benchmark has been taken at least 80ms longer ever since.

**Comment by jonahwilliams** [comment]
Possibly caused by: https://github.com/flutter/flutter/commit/0db029990707cf98d79d66c45802207dce768891

**Comment by DaveShuckerow** [comment]
This is blocking a g3 roll.

**Comment by franciscojma86** [comment]
This benchmark runs pretty consistently on my local machine (red and green commits yield same results). I just did some runs in the device lab host and it does show different results. Will try witht other hosts to narrow down the root cause.

**Comment by franciscojma86** [comment]
I ran tests on the device lab host with different phones, and the increase was barely (or not at all) visible. @jason-simmons also ran some tests on his local machine and didn't see any deltas.

Removing the TODAY tag to unblock the roll, but might be worth trying with other devices or resetting the host to continue investigating

**Comment by franciscojma86** [comment]
Just ran the test with multiple phones. They all show a delta of ~100 ms or lower, depending on the device. This benchmark seems to be very susceptible to the environment, and it might not be worth spending a lot of time investigating this, given that hot reload hasn't been affected in other platforms. 

@liyuqian  @godofredoc  @jonahwilliams does this sound reasonable to you?

**Comment by godofredoc** [comment]
This has been passing in the last few executions
