### ISSUE TITLE
Regression in windows_chrome_dev_mode

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47843]
It seems like `SecondStartupTime` might have regressed. It's over the baseline for most of the commits since https://github.com/flutter/flutter/commit/49c784590787e4beb0dd11d47bec267a733e9291. I'm unsure why this would be the case. It fixes analysis problems with a change to the gallery introducing visual density, but both PRs have [already been reverted](https://github.com/flutter/flutter/pull/47702).

**Comment by jonahwilliams** [comment]
I've re-baselined this benchmark. The overall time seems to be slightly bimodal, but at any rate we'll be drastically changing the implementation here in Q1 so the particular numbers aren't that important to me
