### ISSUE TITLE
The hot reload seems to time out after a few minutes for a macOS app

### ISSUE THREAD

**Issue by csells** [flutter/flutter#47857]
## Steps to Reproduce

1. Start a Flutter app targeting macOS under the debugger
2. Wait a few minutes (specific time unknown)
3. Make a change
4. The change will not be replicated to the running macOS app until it has been clicked on
5. This can be seen in the Interact keynote demo -- after lying dormant for about 10 minutes, to get the change replicated to the running macOS app, it needed to be clicked on

**Target Platform:** macOS
**Target OS version/browser:** Catalina
**Devices:** n/a

## Logs

```
```

```
```

```
```
Any master version at or near the time of Interact exhibited the problem.

**Comment by iapicca** [comment]
Hi @csells 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`  while the issue manifests?
Thank you

**Comment by csells** [comment]
It was happening consistently on the Flutter Octopus machine but I've been unable to reproduce it since.
