### ISSUE TITLE
The first clicks on the button, makes sure that my application flickers. After just under 5 - 10 clicks, it all stops completely.

### ISSUE THREAD

**Issue by sulanbulu** [flutter/flutter#47852]
Hey, I started with Flutter yesterday, and today I faced some rendering problems in my application. The first clicks on the **FlatButton** is buggy, but after **5 - 10 clicks**, it has no **rendering problems**. Is it because of my code or a bug in Flutter?

```dart
class Dice extends StatefulWidget {
  @override
  _DiceState createState() => _DiceState();
}

class _DiceState extends State<Dice> {
  int diceNumber = Random().nextInt(6) + 1;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(80.0),
                child: Image.asset("images/dice$diceNumber.png"),
              ),
            ),
          ],
        ),
        Column(
          children: <Widget>[
            FlatButton(
              color: Colors.white,
              onPressed: () {
                setState(() {
                  diceNumber = Random().nextInt(6) + 1;
                });
              },
              child: Container(
                padding: EdgeInsets.symmetric(horizontal: 100, vertical: 10),
                child: Text(
                  "DICE",
                  style: TextStyle(
                      fontSize: 25,
                      color: Colors.black45,
                      fontWeight: FontWeight.bold),
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }
}
```

**Comment by janmoppel** [comment]
Hello @sulanbulu !

Thank you for posting an issue.
Can you please attach the `flutter doctor -v` command output?

Also, your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by sulanbulu** [comment]
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/sulan/Software/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sulan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/sulan/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sulan/Software/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/sulan/Software/idea-IU-193.5662.53
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0
      (API 26) (emulator)

! Doctor found issues in 1 category.`

Thanks for your help and advice.
