### ISSUE TITLE
FontWeight.w500 not work for Chinese font and device

### ISSUE THREAD

**Issue by pxc0215** [flutter/flutter#47861]
Chinese Font do not bold, when i use `fontWeight: FontWeight.w500` on some Chinese Android devices. Maybe the mobile handset supplier has changed something，but `w100  - w500` has the same effect.

![smartisan_flutter](https://user-images.githubusercontent.com/7680117/71545736-884af300-29c9-11ea-93a4-71c386018c4d.jpeg)

## Doctor
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.40.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

**Comment by janmoppel** [comment]
Hello @pxc0215 !

Thank you for posting an issue.
Can you please also attach an example that can be used to reproduce the issue?

**Comment by pxc0215** [comment]
**This is my code:**

`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Text(
              "这是 FontWeight.w100 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w100),
            ),
            Text(
              "这是 FontWeight.w200 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w200),
            ),
            Text(
              "这是 FontWeight.w300 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w300),
            ),
            Text(
              "这是 FontWeight.w400 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w400),
            ),
            Text(
              "这是 FontWeight.w500 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w500),
            ),
            Text(
              "这是 FontWeight.w600 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w600),
            ),
            Text(
              "这是 FontWeight.w700 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w700),
            ),
            Text(
              "这是 FontWeight.w800 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w800),
            ),
            Text(
              "这是 FontWeight.w900 的字号",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                  fontWeight: FontWeight.w900),
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**And，the display in my android phone is below:**
![smartisan_flutter](https://user-images.githubusercontent.com/7680117/71545736-884af300-29c9-11ea-93a4-71c386018c4d.jpeg)

As you can see, the Chinese has the same effect from w100 to w500，but the show of letters and numbers was markedly different. Why?

**Comment by pxc0215** [comment]
As above, my phone is a Chinese-made phone, maybe the mobile handset supplier has changed something，but there has the same problem on Android Virtual Device (Nexus 6), as follows.
![Screenshot_1577546477](https://user-images.githubusercontent.com/7680117/71546414-8422d380-29d1-11ea-8ca7-f8f6e680f09a.png)
How can I solve this. Very thanks!

**Comment by pxc0215** [comment]
@janmoppel Jan Moppel   Please help me

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/18150.

Flutter will search for a font on the host system that is closest to the specified font weight.  But if the system only provides one font that handles the requested characters, then Flutter and Skia will synthesize a "fake bold" version of that font to handle other font weights.

Skia does not provide multiple levels of fake bold, so the same fake bold transform will be used to handle several different Flutter font weights.

**Comment by GaryQian** [comment]
It looks like your device just simply lacks the multiple levels of bold fonts. This is sometimes the case as a full CJK font can be around 20-30mb, and keeping multiple bold/regular/light versions of the same font can take up significant storage space.

If bold is extremely important, I would recommend either setting it to a heavier weight to use the fakebold as mentioned above, or install your own font family that has true bold fonts for all the weights you want to use. Note that this would likely increase your app size by the size of the fonts.

**Comment by WeiCongcong** [comment]
So why are the character `.` and the point in character `i` with font weight 700 and 800 are rectangles on Android devices?

**Comment by GaryQian** [comment]
@WeiCongcong Can you post a screenshot of what you are seeing? The . in the `i` character is not a separate glyph and should be in sync with the body of the i.

**Comment by WeiCongcong** [comment]
> @WeiCongcong Can you post a screenshot of what you are seeing? The . in the `i` character is not a separate glyph and should be in sync with the body of the i.

I noticed the problem in the screenshots posted in this issue.
![dots](https://user-images.githubusercontent.com/5541895/88248958-8635e200-ccd5-11ea-9363-f58fe2ebc45f.png)

**Comment by LastMonopoly** [comment]
@GaryQian Is the problem solved?
