### ISSUE TITLE
Trying to create an already created platform

### ISSUE THREAD

**Issue by cn-Meepo** [flutter/flutter#47862]
It happened after updating flutter1.12, if necessary ,I can provide sound code.

## Logs
![image](https://user-images.githubusercontent.com/28797329/71498307-ce536a00-2896-11ea-9eb4-992e379d57ac.png)

## Doctor
![image](https://user-images.githubusercontent.com/28797329/71498337-f0e58300-2896-11ea-8520-fe7e37364f1e.png)

**Comment by janmoppel** [comment]
Hello @cn-Meepo !

Thank you for posting an issue.
Can you please provide some minimal example that can help to reproduce the issue? Also can you please post the same error again, but as a text, not an image.

**Comment by cn-Meepo** [comment]
Hello  @janmoppel This is my test code,[https://github.com/cn-Meepo/platform_bug](url),the errors :

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (15702):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (15702):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (15702):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (15702):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (15702):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (15702):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (15702):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (15702):      at android.os.MessageQueue.next(MessageQueue.java:332)
E/flutter (15702):      at android.os.Looper.loop(Looper.java:168)
E/flutter (15702):      at android.app.ActivityThread.main(ActivityThread.java:6878)
E/flutter (15702):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (15702):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (15702):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/flutter (15702): , null)
E/flutter (15702): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (15702): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (15702): <asynchronous suspension>
E/flutter (15702): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (15702): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (15702): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (15702): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (15702): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (15702): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (15702): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15702): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (15702): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15702): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
E/flutter (15702): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15702): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (15702): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15702): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (15702): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15702): #17     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (15702): #18     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (15702): #19     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (15702): #20     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (15702): #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (15702): #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (15702): #23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (15702): #24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
E/flutter (15702): #25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (15702): #26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (15702): #27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (15702): #28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (15702): #29     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (15702): #30     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15702): #31     _CustomZone.runGuarded (da

**Comment by VladyslavBondarenko** [comment]
Hi @cn-Meepo 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/45695
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
