### ISSUE TITLE
[web]: <It runs the Flutter Demo instead of my app>

### ISSUE THREAD

**Issue by AniketW123** [flutter/flutter#47866]
I'm running `/Users/aniket/flutter/bin/flutter run -d chrome` and it keeps running the Flutter Demo

**Comment by janmoppel** [comment]
Hello @anikwarty !

Thank you for posting an issue.
Do you run it from your application folder?

**Comment by dnfield** [comment]
Closing this since it has not had a response in >21 days.  @AniketW123 please add a response if you need this reopened.  If your issue is resolved you can disregard.
