### ISSUE TITLE
Chip: add ability to put delete icon before label OR allow elements inside chip to accept gestures

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#47867]
## Use case
I have a chip that, when tapped, changes its avatar to delete icon. I can neither make avatar tappable nor put the delete icon before the label. For now I'm stuck with having avatar after the label.
Chip is great and has a lot of useful functionality, so I wouldn't like to build my own implementation just for the icon position.

## Proposal
Add ability to put delete icon before label in chip OR allow elements inside chip to accept gestures

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by Hixie** [comment]
Generally the material library widgets are intended to support the material library's interactions. I would recommend forking the chip widget and making your own that does what you want!
