### ISSUE TITLE
Failed assertion: line 1372: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [flutter/flutter#47873]
## Steps to Reproduce
- I have a TextField in the widget tree which switches to a Text widget when tapping an adjacent button. The issue arises when the user switches the TextField to TextWidget and then back to TextField. Then this exception was kept throwing 

**Target Platform:** Android
**Target OS version/browser:** 29
**Devices:** Mi A3

## Logs
════════ (69) Exception caught by animation library ════════════════════════════════════════════════
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (70) Exception caught by animation library ════════════════════════════════════════════════
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
════════════════════════════════════════════════════════════════════════════════════════════════════
Restarted application in 1,386ms.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///home/ileaf-pc/yadhu/December/biotecnika-repo/lib/modules/profile/user_profile_screen.dart:129:48
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#77797 relayoutBoundary=up24
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
...  size: Size(257.6, 22.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#c5d3c(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#77797 relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
  size: Size(257.6, 22.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#c5d3c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///home/ileaf-pc/yadhu/December/biotecnika-repo/lib/modules/profile/user_profile_screen.dart:129:48
The following RenderObject was being processed when the exception was fired: RenderEditable#77797 relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
  size: Size(257.6, 22.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#c5d3c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#77797 relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
  size: Size(257.6, 22.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#c5d3c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///home/ileaf-pc/yadhu/December/biotecnika-repo/lib/modules/profile/user_profile_screen.dart:129:48
The following RenderObject was being processed when the exception was fired: RenderEditable#77797 relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
  size: Size(257.6, 22.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#c5d3c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#77797 relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=257.6, 0.0<=h<=30.0)
  size: Size(257.6, 22.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#c5d3c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f11f6(offset: 0.0, range: 0.0..0.0, viewport: 257.6, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#681a5, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 19.0
    weight: 700
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

**Comment by iapicca** [comment]
Hi @iLeafSolutionsPvtLtd 
I see there's an open [issue ](47790) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
