### ISSUE TITLE
如果给CupertinoActivityIndicator设置一个纯黑背景色，会导致CupertinoActivityIndicator和背景色基本一致,导致显示问题

### ISSUE THREAD

**Issue by YueMeng123** [flutter/flutter#47870]
```
            Container(
              width: double.infinity,
              height: 300,
              ///在这个颜色下基本看不见
              color: Color(0xFF3A3A3A),
              child: CupertinoActivityIndicator(
                radius: 100.0,
                animating: false,
              ),
            ),
```

![](https://user-gold-cdn.xitu.io/2019/12/27/16f46d8b96208c44?w=424&h=390&f=png&s=20644)

**Comment by YueMeng123** [comment]
Container(
              width: double.infinity,
              height: 300,
              ///在这个颜色下基本看不见
              color: Color(0xFF3A3A3A),
              child: CupertinoActivityIndicator(
                radius: 100.0,
                animating: false,
              ),
            )


![image](https://user-images.githubusercontent.com/23230746/71513075-e0073280-28d3-11ea-86de-8e4937cf04d2.png)

**Comment by LongCatIsLooong** [comment]
Close in favor of https://github.com/flutter/flutter/issues/47255.
