### ISSUE TITLE
Failed to create MD5 hash for file content when running or debug app flutter or gradle

### ISSUE THREAD

**Issue by kafkakhalis17** [flutter/flutter#47876]
`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Failed to create MD5 hash for file content.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Gradle task assembleDebug failed with exit code 1`

when I make a new flutter project and run or debug it 
this issue comes.

but when I run another project before this issue, its work to run on my phone

**Comment by BondarenkoStas** [comment]
Hi @kafkakhalis17 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kafkakhalis17** [comment]
this after I run `flutter doctor -v`

D:\Sekolah\Latihan\Flutter>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-ID)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Kafkakhalis\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Kafkakhalis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • RMX1801 • 662d080 • android-arm64 • Android 9 (API 28)

**Comment by kafkakhalis17** [comment]
and this is after I run `flutter run --verbose`

D:\Sekolah\Latihan\Flutter\newapp>flutter run --verbose
[  +25 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +55 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.5-0-g27321ebba
[   +9 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +90 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +138 ms] executing: C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] Exit code 0 from: C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           662d080                device product:RMX1801 model:RMX1801 device:RMX1801 transport_id:3
[  +19 ms] C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe -s 662d080 shell getprop
[ +256 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +218 ms] Generating D:\Sekolah\Latihan\Flutter\newapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +36 ms] ro.hardware = qcom
[ +115 ms] Launching lib\main.dart on RMX1801 in debug mode...
[  +51 ms] executing: C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe -s 662d080 shell -x logcat -v time -s flutter
[  +12 ms] executing: C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +75 ms] Android Debug Bridge version 1.0.41
           Version 29.0.4-5871666
           Installed as C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\Kafkakhalis\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +25 ms] Building APK
[  +32 ms] Running Gradle task 'assembleDebug'...
[  +16 ms] gradle.properties already sets `android.enableR8`
[  +10 ms] Using gradle from D:\Sekolah\Latihan\Flutter\newapp\android\gradlew.bat.
[  +30 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +96 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +5 ms] executing: [D:\Sekolah\Latihan\Flutter\newapp\android\] D:\Sekolah\Latihan\Flutter\newapp\android\gradlew.bat -Pverbose=true
-Ptarget=D:\Sekolah\Latihan\Flutter\newapp\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64
assembleDebug
[+2809 ms] FAILURE: Build failed with an exception.
[  +12 ms] * What went wrong:
[  +36 ms] A problem occurred configuring root project 'android'.
[   +1 ms] > Failed to create MD5 hash for file content.
[   +4 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 2s
[ +405 ms] Running Gradle task 'assembleDebug'... (completed in 3.4s)
[  +45 ms] "flutter run" took 4,611ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by kafkakhalis17** [comment]
Failed on here
[+2809 ms] FAILURE: Build failed with an exception.
[  +12 ms] * What went wrong:
[  +36 ms] A problem occurred configuring root project 'android'.
[   +1 ms] > Failed to create MD5 hash for file content.
[   +4 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 2s
[ +405 ms] Running Gradle task 'assembleDebug'... (completed in 3.4s)
[  +45 ms] "flutter run" took 4,611ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by jonahwilliams** [comment]
I don't see anything in this issue that indicates a problem with Flutter, but we likely don't have enough information to make a call.

For reference, I found https://stackoverflow.com/questions/48632019/gradle-build-error-on-windows-failed-to-create-md5-hash-for-file/48894292 which claims this can happen if you override certain configuration in your Gradle project.
