### ISSUE TITLE
flutter1.12 Splash Black screen problem

### ISSUE THREAD

**Issue by DragonYuu** [flutter/flutter#47871]
I want to create a splash screen page, but I found a problem is that when I create it, there will be a black screen problem for a while, but I see on github that the code written by others may not be the latest version and there is no splash screen Problem, but this problem occurs with the latest version. I would like to ask what is the reason for this problem.

**Comment by iapicca** [comment]
Hi @DragonYuu 
I see there's an open [issue](https://github.com/flutter/flutter/issues/20827) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by DragonYuu** [comment]
Thank you for your reply to my question. Ok, I will pay attention to it. Thank you



发自我的iPhone


------------------ Original ------------------

**Comment by carocean** [comment]
大师好，发现v1.12.13-h5版本中的例程启动都是黑屏一闪而过，这咋整，肯定是个bug啊。环境：华为android mate30
