### ISSUE TITLE
Incorrect Hero animation behavior with appBar.

### ISSUE THREAD

**Issue by evgeniy-skakun** [flutter/flutter#47885]
## Steps to Reproduce

1. Click on the image (with hero animation), which is slightly covered by appBar;
2. Click back button;
3. Notice that during reverse routing the appBar is covered by image.

**Target Platform:** Android
**Target OS version/browser:** Android 9
**Devices:** Samsung A30

## Link on video
https://drive.google.com/file/d/1oBb6J3CB6L2qJyeDN6B-ejAXrA3bxi1C/view?usp=sharing

## Flutter doctor
[✓] Flutter (Channel master, v1.13.4-pre.12, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.4-pre.12 at /home/skakun/flutter
    • Framework revision cc1c9649c4 (8 days ago), 2019-12-19 19:53:01 -0800
    • Engine revision 472197a8e9
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 8d11c1dce6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/skakun/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/skakun/Android/Sdk
    • ANDROID_SDK_ROOT = /home/skakun/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1.1-b09)
    • All Android licenses accepted.

**Comment by LongCatIsLooong** [comment]
Hi @evgeniy-skakun, thanks for reporting issue. Could you provide a minimal and self-contained example to help us reproduce the problem?

**Comment by evgeniy-skakun** [comment]
@LongCatIsLooong minimum reproduce https://github.com/evgeniy-skakun/hero-animation-app-bar

**Comment by TahaTesser** [comment]
Hi @evgeniy-skakun 
I wasn't able to reproduce this, based on your code sample, everything looks fine
Am i missing something? Are you still experiencing this issue with latest stable Flutter?
if yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
