### ISSUE TITLE
Dart analyzer keeps crashing 

### ISSUE THREAD

**Issue by saurabhguptarock** [flutter/flutter#47881]
Dart analyzer keeps crashing in flutter 1.12.13+hotfix.5(latest stable release).
i tried everything 
1. Deleted flutter/bin/cache(run flutter docter).
2.Uninstalled flutter and android studio(every single file).
but the error is still not fixed.

**Comment by marcos930807** [comment]
This is happening to several people, see this:
#47538
#46616
#47821
On Dart repo there are a few issues related too.
I had to do downgrade to 1.9.1 becouse analizer crashing is anoying.

**Comment by marcos930807** [comment]
> Dart analyzer keeps crashing in flutter 1.12.13+hotfix.5(latest stable release).
> i tried everything
> 
> 1. Deleted flutter/bin/cache(run flutter docter).
>    2.Uninstalled flutter and android studio(every single file).
>    but the error is still not fixed.

It would be good if you shared your error log and flutter doctor's output, also that you activate the intrumentation log to see if it throws something interesting at you.

**Comment by iapicca** [comment]
Hi @saurabhguptarock 
I see there's an open [issue ](46616) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
