### ISSUE TITLE
Flutter codelab does not work with master

### ISSUE THREAD

**Issue by kaiyuanw** [flutter/flutter#4789]
## Steps to Reproduce

Follow the firechat code lab.  Run pub get and you will get the error message.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/kaiyuanw/Intern/fork/flutter
    • Framework revision 63eedb7677 (26 hours ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /usr/local/google/home/kaiyuanw/Intern/Android/Sdk
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

## Logs and Crash Reports

Resolving dependencies...
Incompatible version constraints on crypto:
- firebase 0.6.5+1 depends on version ^0.9.0
- flutter 0.0.21 depends on version >=1.1.1 <3.0.0

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
@collinjackson

**Comment by collinjackson** [comment]
Firebase is currently working with the "codelab" branch of flutter. I am working on upgrading it to work with the latest.

**Comment by collinjackson** [comment]
On it! thanks

**Comment by sethladd** [comment]
We've hidden the codelab for now, waiting until we migrate over to the new Flutter services API.

Thanks for the feedback, looking forward to publishing an updated codelab.

**Comment by kroikie** [comment]
@kaiyuanw

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1019. Any further collaboration will be done there.
