### ISSUE TITLE
statusbar color

### ISSUE THREAD

**Issue by huangsir0** [flutter/flutter#47912]
``` dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
```  
the dark style overrided by  
``` dart
 AppBar(
        backgroundColor: Colors.white,
...
)
```
but what I need is SystemUiOverlayStyle.dark,How should I do?

**Comment by iapicca** [comment]
Hi @huangsir0  
can you please provide your `flutter doctor -v` 
and  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
@huangsir0 
Probably you needed to not use backgroundColor for AppBar.

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution
