### ISSUE TITLE
[web]: DevTools do not show log entries written using dart:developer.log() function

### ISSUE THREAD

**Issue by bialpio** [flutter/flutter#47913]
According to the [docs](https://flutter.dev/docs/testing/code-debugging#logging), it should be possible to use developer.log() function for application logging. The problem is that it seems that DevTools' Logging will not show messages that were written using console.debug() from a web app, and this is what is being used by developer.log() function when targeting web.

Partial output from `flutter doctor -v`:
```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.6 at <redacted>
    • Framework revision 18cd7a3601 (2 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
(...)
[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
(...)
```

**Comment by vsmenon** [comment]
@grouma - it looks `developer.log` does this:

https://github.com/dart-lang/sdk/blob/5804537b8341eeb7113c13b6b659a7fe432aed73/sdk/lib/_internal/js_dev_runtime/patch/developer_patch.dart#L52

Do we need to handle that in this switch:

https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/services/chrome_proxy_service.dart#L595

?

**Comment by grouma** [comment]
I think the issue is our filter here:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/services/chrome_proxy_service.dart#L670

This bug should be moved over to `package:dwds` and we can handle it in there.

**Comment by matanshukry** [comment]
Any updates on this?

**Comment by nshahan** [comment]
No change made as of yet, but we have been discussing updating this API in the web development compiler to avoid using `console.debug()` https://github.com/flutter/devtools/issues/3222.

The new implementation would use a callback provided by the devtools integration to communicate the messages directly.

**Comment by nshahan** [comment]
This problem has been fixed https://github.com/dart-lang/webdev/pull/2333.
