### ISSUE TITLE
Parsing using For in String jsonString = await _ChieseAsset();

### ISSUE THREAD

**Issue by daniele777** [flutter/flutter#47910]
Yo ,, during my experience of flutter i'll try to show on map marker saved into Json file..in this way i retrive only one of row 

               Future<chiese> loadChiese() async {
                await wait(5);
                 String jsonString = await _ChieseAsset();
                  final jsonResponse = json.decode(jsonString);

               for ( var i=0; i < 5; i++ ){
                print(i);
               return new chiese.fromJson(jsonResponse[i]);
               }
              }

Unfortunally var i show only 0 value and don't scan into json retrive only first value
why??? 

if i use ...

               Future<chiese> loadChiese() async {
               await wait(5);
               String jsonString = await _ChieseAsset();
               final jsonResponse = json.decode(jsonString);
               return new chiese.fromJson(jsonResponse);
                 }

Reciving error ... 
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'

Any idea??? Thanks

**Comment by jonahwilliams** [comment]
This looks like your JSON structure is not what your class is expecting (a List where you think there should be a Map), hence the type error. For support questions, I recommending taking it to a more appropriate venue, such as one of the channels at flutter.dev/community
