### ISSUE TITLE
New Flutter CLI command to create a project for one platform

### ISSUE THREAD

**Issue by ansarizafar** [flutter/flutter#47924]
When we use flutter create command to create a new project, It creates a project with all supported platforms. Flutter CLI should have an option to create a project just for one platform.
````
flutter create myapp --platform web
````
We should be able to add another platform, If we need it later on
````
flutter add android
````
This will allow us to have a clean project structure without unnecessary files and folders.

**Comment by jonahwilliams** [comment]
In the short term you can always delete the platform folders you don't want to use

**Comment by ansarizafar** [comment]
Flutter should not require android tools/sdk If I am only developing for web. Even when we upgrade flutter, it downloads android tools/sdks.

**Comment by jonahwilliams** [comment]
> Flutter should not require android tools/sdk If I am only developing for web. Even when we upgrade flutter, it downloads android tools/sdks.

To be clear - flutter does not download the full Android SDK when you upgrade. I agree though, it shouldn't need to download anything

**Comment by ansarizafar** [comment]
Is there any update on this issue? Flutter upgrade downloads so much unnecessary android related stuff specially If you are on a slow internet connection.

````
Downloading Android Maven dependencies...                         179.2s (!)
Downloading android-arm-profile/linux-x64 tools...                  6.3s
Downloading android-arm-release/linux-x64 tools...                  5.3s
Downloading android-arm64-profile/linux-x64 tools...                6.2s
Downloading android-arm64-release/linux-x64 tools...                5.4s
Downloading android-x64-profile/linux-x64 tools...                  6.5s
Downloading android-x64-release/linux-x64 tools...                  5.5s
Downloading android-x86 tools...                                   47.6s
Downloading android-x64 tools...                                   48.5s
Downloading android-arm tools...                                   22.9s
Downloading android-arm-profile tools...                           11.8s
Downloading android-arm-release tools...                            8.8s
Downloading android-arm64 tools...                                 23.8s
Downloading android-arm64-profile tools...                         12.8s
Downloading android-arm64-release tools...                          9.9s
Downloading android-x64-profile tools...                           13.3s
Downloading android-x64-release tools...                           10.5s
Downloading android-x86-jit-release tools...                       16.4s

````

**Comment by YazeedAlKhalaf** [comment]
This is a great ability to add new platforms like add web or windows or mac or linux

**Comment by ansarizafar** [comment]
@jonahwilliams @Hixie  Is there any update on this issue?

Its really hard to understand why flutter needs android tool chain when we install or upgrade flutter, If we are not developing for android. 

I am working in a remote area where internet connection is slow and unreliable and Its a pain to install and upgrade flutter.  I request Flutter team to please accept this proposal asap.
