### ISSUE TITLE
Cocoon is starting duplicate jobs for autorollers

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47929]
See https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/653 and https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/654, which were both triggered for commit 428c17b9d5a11ce10ad740fa8c53dbde1b8a66e5 on flutter/engine#14877

/cc @godofredoc @keyonghan @digiter

**Comment by godofredoc** [comment]
Closing as obsolete. Please reopen if this is still happening.
