### ISSUE TITLE
I try to deploy to app store as prod but error.

### ISSUE THREAD

**Issue by peterkuch** [flutter/flutter#47936]
How can i fixed my Flutter latest version too xcode latest version. but i guest flutter no enable bitcode , i am not sure about this point.

<img width="854" alt="Screen Shot 2019-12-29 at 2 52 19 PM" src="https://user-images.githubusercontent.com/14107698/71553971-0ef3e480-2a4b-11ea-97d1-9340c938e01c.png">
<img width="741" alt="Screen Shot 2019-12-29 at 2 53 49 PM" src="https://user-images.githubusercontent.com/14107698/71553972-0f8c7b00-2a4b-11ea-9d82-ddb151f4dedd.png">

**Comment by iapicca** [comment]
Hi @peterkuch 
can you please provide your `flutter doctor -v` 
and your `flutter build ios --verbose`?
Thank you

**Comment by peterkuch** [comment]
That ok now the problem with my internet can’t verify app connect thank.
Now I resolved it.
