### ISSUE TITLE
"Unable to load asset" when attempting to use downloaded font

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#47934]
flutter : Flutter 1.12.13+hotfix.5

if directly run , i got error:

 Unhandled Exception: Unable to load asset: /data/user/0/milukun.flutter_app/app_flutter/font/zkHappy.ttf
 
(zkHappy.ttf download from internet)

When I  Hot restart the app , it works well , and the font show well.

Flutter 1.9 is ok
Flutter 1.12.13+hotfix.5 has this issue on android (ios is ok)

`E/flutter ( 5514): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: /data/user/0/milukun.flutter_app/app_flutter/font/zkHappy.ttf
E/flutter ( 5514): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter ( 5514): <asynchronous suspension>
E/flutter ( 5514): #1      Font_Contral.getCustomFont (package:danmupic/mprovide/font_provider.dart:270:42)
E/flutter ( 5514): #2      Font_Contral.readFont (package:danmupic/mprovide/font_provider.dart:265:24)
E/flutter ( 5514): #3      Font_Contral.initFont.<anonymous closure> (package:danmupic/mprovide/font_provider.dart:133:15)
E/flutter ( 5514): <asynchronous suspension>
E/flutter ( 5514): #4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 5514): #5      Font_Contral.initFont (package:danmupic/mprovide/font_provider.dart:116:18)
E/flutter ( 5514): <asynchronous suspension>
E/flutter ( 5514): #6      _Font_localState.build.<anonymous closure> (package:danmupic/pages/widget/font_local.dart:130:54)
E/flutter ( 5514): #7      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
E/flutter ( 5514): #8      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 5514): #9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5514): #10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 5514): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 5514): #12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 5514): #13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 5514): #14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter ( 5514): #15     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 5514): #16     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 5514): #17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 5514): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 5514): #19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 5514): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)`

**Comment by jonahwilliams** [comment]
Can you share the contents of your asset manifest? (pubspec.yaml). Does this persist if you run a flutter clean?

**Comment by sunjianan9900** [comment]
> Can you share the contents of your asset manifest? (pubspec.yaml). Does this persist if you run a flutter clean?

this font not load from asset manifest,
it‘s download from my service , the path is "/data/user/0/milukun.flutter_app/app_flutter/font/zkHappy.ttf"
And i'm sure it download finish , because I check this file before .addFont()

Then I need to hot-Restart , and it works well.
if I close the app , and reopen it , it not works again.

Before hot-Restart, I can not use any font download from my service, 
after hot-Restart, I can use all downloaded font file , and if I download new font , it works well too
But when I exit app , and reopen , it not work....all font not show and come the error:
 Unhandled Exception: Unable to load asset:  xxxxxxx

**Comment by sunjianan9900** [comment]
> Can you share the contents of your asset manifest? (pubspec.yaml). Does this persist if you run a flutter clean?

this is the minium code : https://github.com/sunjianan9900/flutter_splash/blob/master/flutter_app/lib/main.dart

this is the video i record:
https://youtu.be/IjICV2t4ONY

**Comment by wwtssu** [comment]
I have the same problem
unable to load asset and can load after hot restart
but I can't hot restart when packed a release apk
so sad.

**Comment by jonahwilliams** [comment]
Based on the sample code you've provided this looks like an issue with a FontLoder and not with the flutter tool asset packaging

**Comment by NavneetKumarIndia** [comment]
Hi Guys,

**Comment by NavneetKumarIndia** [comment]
Hi Guys,

I tried a lot to resolve the issue, but I failed, but then I noticed one thing, there are two Flutter functions AssetImage and FileImage, AssetImage is working in both App fresh load as well as hot restart cases, but the image asset should be a part of App (not gallery) , similarly FIleImage is working in both App fresh load as well as hot restart cases when Images are getting loaded from Gallery,

**Comment by sunjianan9900** [comment]
> Hi Guys,
> 
> I tried a lot to resolve the issue, but I failed, but then I noticed one thing, there are two Flutter functions AssetImage and FileImage, AssetImage is working in both App fresh load as well as hot restart cases, but the image asset should be a part of App (not gallery), similarly FIleImage is working in both App fresh load as well as hot restart cases when Images are getting loaded from Gallery,
> 
> So, It will be good if you use "Image.file()" instead of "Image.asset()" when you load file from Gallery.
> 
> Navneet Kumar

thanks for your replay
but I got issue with FontLoder()

**Comment by sunjianan9900** [comment]
> I have the same problem
> unable to load asset and can load after hot restart
> but I can't hot restart when packed a release apk
> so sad.

In my case , use File to replace rootBundle.load() can ignore this issue

```
// ByteData byteData = await rootBundle.load(path);
File file = new File(path);
Uint8List bytes = file.readAsBytesSync();
ByteData byteData = ByteData.view(bytes.buffer);
return byteData
```

**Comment by NavneetKumarIndia** [comment]
**Replace** 
ByteData byteData = await rootBundle.load(path);

**WIth**
Uint8List byteData = new File(path).readAsBytesSync();;
ByteData font = ByteData.view(byteData.buffer);

**Comment by markusaksli-nc** [comment]
Hi @sunjianan9900 
Are you still facing this problem on the latest version of Flutter?
Thank you

**Comment by sunjianan9900** [comment]
> Hi @sunjianan9900
> Are you still facing this problem on the latest version of Flutter?
> Thank you

it works well , thanks
