### ISSUE TITLE
wiki needs to be updated

### ISSUE THREAD

**Issue by Zauther** [flutter/flutter#47947]
https://github.com/flutter/flutter/wiki/Compiling-the-engine

>  For MacOS, you will need older version of XCode(9.4 or below) to compile

This needs to be updated

**Comment by jmagman** [comment]
\cc @chunhtai 
Other than the casing of "XCode" what do you think needs to be changed?

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/wiki/Compiling-the-engine/01b360e3e4a39839b38a89585f3b37692de68569
