### ISSUE TITLE
Remove kotlin support from flutter project

### ISSUE THREAD

**Issue by deshario** [flutter/flutter#47945]
I accidently add kotlin support for my flutter project ... and now my app needs to use some dependencies that use higher gradle version and when i update my gradle version to 3.3.0.
It seems to be problem with kotlin.  

It says
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
> The following dependencies do not satisfy the required version:
> root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Note : kotlin was never used in my project**

So i delete kotlin from both build gradle files ... and now i cant install my iapp.
The app failed to install : Couldn’t parse error string

So my question is
 **How to remove kotlin supports completely and correctly from our flutter app ?**

**Comment by VladyslavBondarenko** [comment]
Hi @deshario 
I see there's a similar [issue](https://github.com/flutter/flutter/issues/27939), please take a look at it.
I'm closing the current one as duplicate and as this isn't an issue with flutter itself.
If you disagree or your case doesn't match to described in mentioned issue, please write in the comments, 
and I will reopen it.
Thank you
