### ISSUE TITLE
[video_controller] iOS black screen

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#47942]
Some video can't play on iOS. It shows just black screen with sound.

For example try this url to controller
https://storage.googleapis.com/bazzarro-chat-files/K/B/KBwvRx43RkdSRBZtjVXYJ9Imb_OLD_EnyfF7tlUPZCjdIbPWuuiHzIx9_JqE/Video.mp4

note: in Android is vertical fliped.. (compressed with https://pub.dev/packages/flutter_video_compress)

**Comment by VladyslavBondarenko** [comment]
Hi @kleinpetr  
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Hi @kleinpetr 
in addition to @VladyslavBondarenko kindly asked you,
please note that [flutter_video_compress](https://pub.dev/packages/flutter_video_compress) is a 3rd party plugin, if you believe that the issue might depend from said plugin
you may want to open an issue in the dedicated [github](https://github.com/rurico/flutter_video_compress/issues).

Does the following code represent the issue you are describing?

<details>
	<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
​
const String _url = 'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';
​
void main() => runApp(MyApp());
​
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}
​
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
​
class _MyHomePageState extends State<MyHomePage> {
  static VideoPlayerController _controller;
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController
      .network(_url)
        ..initialize()
          .then((_) => setState((){}),);
  }
​
  @override
  void dispose() {
    super.dispose();
    _controller?.dispose();
    _controller = null;
    print('disposing '+widget.key.toString());
  }
 
  @override
  Widget build(BuildContext context)=> Scaffold(
    body: Center(
        child: GestureDetector(
          onTap: ()=> _controller.value.isPlaying
            ? _controller.pause()
            : _controller.play(),
          child:  _controller.value.initialized
        ? AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller),
          )
        : CircularProgressIndicator(),
  ),),);
}

```

</details>

thank you

**Comment by TahaTesser** [comment]
Hi @kleinpetr 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
