### ISSUE TITLE
Flutter does not warn of the use of raw types

### ISSUE THREAD

**Issue by adcaine** [flutter/flutter#47948]
**Reproduction Steps**

1.  Write code using a generic widget, like ```StreamBuilder``` as an example.  Do not specify the generic. 

```Dart
        child: StreamBuilder(
          stream: _dateTimeStream.stream,
          initialData: DateTime.now(),
          builder: (context, snapshot) {
            DateTime dateTime = snapshot.data as DateTime;
```
where ```_dateTimeStream``` is a stream periodically returning ```DateTime``` objects.

**Expected**

The Dart language should warn that ```StreamBuilder``` is being used as a raw type; a generic usage is possible and perhaps preferable.  Dart can encourage the developer to write the code with a generic type, avoid casing ```snapshot.data```, and make the code clearer.  For example:
```Dart
        child: StreamBuilder<DateTime>(
          stream: _dateTimeStream.stream,
          initialData: DateTime.now(),
          builder: (context, snapshot) {
            DateTime dateTime = snapshot.data;
```

**Actual**

Dart does not warn that ```StreamBuilder``` is a generic type and it is possibly better to specify the return type of the Stream.

**Flutter Doctor**

```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[!] VS Code (version 1.32.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by goderbauer** [comment]
You can get this warning by enabling the always_specify_types lint in your analysis_options.yam: https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L52
