### ISSUE TITLE
[video_player] iOS controller played sound in background

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#47941]
I am using video_player like this

```
@override
  void initState() {
    _loadData();
    super.initState();
  }

  void _loadData() async {
    await _controller.initialize();
    if (_controller == null) return;

    setState(() {});
    _controller.play();

    _controller.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
```

And when I open the app, play first video, then go back, play another videos, then minimize the app waiting until 10-15s and open the app, the sound of the FIRST video is played in the background..

**Comment by VladyslavBondarenko** [comment]
Hi @kleinpetr 
To better address the issue, would be helpful
if you could provide your `flutter doctor -v` and `flutter run --verbose` and post a self contained app on github with steps to reproduce it.
Thank you

**Comment by TahaTesser** [comment]
Hi @kleinpetr
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
