### ISSUE TITLE
Dart typedef does not allow for defining complex types as simpler ones

### ISSUE THREAD

**Issue by adcaine** [flutter/flutter#47958]
## Use case

**Reproduction Steps**

Write the following ```typedef```:

```Dart
typedef MyIntArray = List<List<int>>;
```

**Expected**
The code compiles.  The developer can use the identifier ```MyIntArray``` where ever ```List<List<int>``` would be allowed.

**Actual**
The code does not compile.  It seems that ```typedef``` is used to define and name lambda expressions only:
```
typedef lambda_return_type [lambda name]([lambda parameters]);
```
Of course, I do not object to this.  It simply doesn't cover all the use cases.

## Proposal

If the ```typedef``` has an equals sign in it, then the developer may define a new *expression* for an existing type:
```Dart
typedef new_expression = existing_type;
```
Note that this usage does not define a new type.  Rather it defines another way of expressing an existing type.

**Comment by jonahwilliams** [comment]
Discussed in https://github.com/dart-lang/language/issues/65
