### ISSUE TITLE
Dart does not allow classes to be final

### ISSUE THREAD

**Issue by adcaine** [flutter/flutter#47952]
## Use Case

**Reproduction Steps**

To encourage composition over inheritance, a developer writes

```Dart
final class DisplayArray extends StatelessWidget {
  final List<Glyph> displayGlyphs;
  final int maxCharacters;
  final int rows;
  final int cols;
  final Color onColor;
  // and so on;
```
**Expected**
The code compiles.  No class can extend or implement the class.  Composition is allowed and encouraged.  Inheritance is forbidden.

**Actual**
The code does not compile.  Without the ```final``` access modifier, the class can be extended or implemented possibly breaking the class's encapsulation.  Changing the ```DisplayArray``` could potentially break classes which extend it.  So, it may become impossible to refactor the ```DisplayArray``` class without risking a break in the code elsewhere.

**Remark**
I do realize that Dart has the concept of *implied* interfaces.  If a class is allowed to be made ```final```, it simply would mean that the implied interface is unavailable.  Classes would not be able to access the implied interface, enforcing class encapsulation.

## Proposal

Dart class may be made ```final```.  A ```final class``` is a class which is not equipped with an *implied* interface.  So the class cannot be extended or implemented.   An ```abstract final class``` would not be permitted, however.  Abstract classes would be considered non-final by definition.

**Flutter Doctor**
```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[!] VS Code (version 1.32.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
I recommend filling an issue on https://github.com/dart-lang/language ( if there isn't already one ). This is not the appropriate repo to discuss enhancements to the Dart language
