### ISSUE TITLE
Problem with running flutter app

### ISSUE THREAD

**Issue by akhil-raj-git** [flutter/flutter#47957]
I just installed flutter on a new computer: iMac running the latest version of Catalina. All command-line tools and plugins are installed, however, I'm not able to fully run my code without it breaking. When I do flutter run on a newly created flutter project I get this error.

<img width="534" alt="Screen Shot 2019-12-29 at 2 19 16 PM" src="https://user-images.githubusercontent.com/42533186/71561553-414f1300-2a46-11ea-98b6-c0371b959fa5.png">

The simulator launches but shows a blank screen. Sometimes it actually shows the app. It's inconsistent though. Anyone know a fix or have the same problem?

**Comment by jonahwilliams** [comment]
Can you include the output of `flutter doctor -v`, and the verbose logs from a run? `flutter run -v`

**Comment by akhil-raj-git** [comment]
I figured it out. It was a stupid reason actually. I just had to switch to a user with admin access. I'm not sure why that worked though
