### ISSUE TITLE
[huawei] CheckException(env)

### ISSUE THREAD

**Issue by ChenMingLiu** [flutter/flutter#47966]
Model：Huawei imagination 9
operating system：android8.20
flutter_sdk ：v1.12.13+hotfix.5
webview_flutter: ^0.3.18+1

Scene: start flash back
```bash
Error code:
E/flutter (17642): [ERROR:flutter/shell/gpu/http://gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.

Add getintent(). Putextra ("enable software rendering", true) to MainActivity;
Open WebView to flash back after modification
Error code:
E/flutter (19801): [ERROR:flutter/shell/platform/android/http://platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter (19801): at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:300)
E/flutter (19801):
F/flutter (19801): [FATAL:flutter/shell/platform/android/http://platform_view_android_jni.cc(123)] Check failed: CheckException(env).
Lost connection to device.

```

**Comment by zinkLin** [comment]
same question on oppo reno
operating system：android9
flutter_sdk ：v1.12.13+hotfix.5

**Comment by iapicca** [comment]
Hi @ChenMingLiu  @zinkLin 
can you please provide  your `flutter run --verbose`
and  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Unfortunately we can't really follow-up and act on this bug without any additional information. Feel free to open a new bug if you are able to share a sample reproduction project or reproduction steps.
