### ISSUE TITLE
`flutter create` new project template should be built with gradle (like hello_services)

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4796]
Developers should be able to create a new project and immediately start editing the Java in Android Studio and Objective-C in Xcode.

This is related to and possibly blocked by #4429.

**Comment by collinjackson** [comment]
@abarth

**Comment by abarth** [comment]
This is true for iOS now.  Still need to do Android.

/cc @devoncarew

**Comment by olostan** [comment]
Currently "hello_services" project require extremely more efforts to be run (sometimes I've spend 1-2 minutes between code-change and result-on-device, however I changed couple of lines). 

If compared to "dart-only" project, it looks like completely another dev. workflow. Not in a good way.

**Comment by mit-mit** [comment]
For you @jakobr-google

**Comment by abarth** [comment]
I created a "project" to track bugs related to this issue:

https://github.com/flutter/flutter/projects/8

**Comment by lukef** [comment]
Not sure if this is helpful but I'd suggest that, even if the content of the template stays the same, there should be greater separation of concern (as opposed to everything being in 1 file). I typically use, as a minimum:

```
lib
  screens
    - main_screen.dart
  - main.dart
```

It might want to also have states separately, but that would also be a good guidance from the team as to what is the "best practice" in lieu of having one of your own.

You might be rewriting the whole thing but figured I'd mention it.

**Comment by mit-mit** [comment]
Hi @lukef, the changes tracked in this bug are more infrastructure related -- we are basically changing the fine details of how the android code is built, to enable interop scenarios where you need to be able to open the android sub-project in Android Studio to edit it's java code.

The change you are suggesting is pretty unrelated to this, so I suggest you open a new bug for it, if you don't mind!
