### ISSUE TITLE
Having problem in app statusbar hide in Flutter version 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by raaja-nithra** [flutter/flutter#47970]
## Having problem in app statusbar hide in Flutter version 1.12.13+hotfix.5

AppBar not in upper it taken a space

Before Flutter 1.9 it works perfectly how to solve this problem.
I'm used this line to hide     
SystemChrome.setEnabledSystemUIOverlays ([]);
 

![Screenshot_2020-01-01-11-32-59-866](https://user-images.githubusercontent.com/54349194/71569898-33f26100-2af8-11ea-955b-2a800ae29f77.jpeg)

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @raaja-nithra 
can you please provide your `flutter doctor -v` 
and a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by raaja-nithra** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Android Studio (version 3.5)

! Doctor found issues in 1 categories.

**Comment by goderbauer** [comment]
Please post some runnable code that showcases the problem.

**Comment by mikerockett** [comment]
Bumped into a similar issue when transferring a project from an ObjC/Java template to the new default Swift/Kotlin template. From what I can tell, all the Android configuration is the same, except for an additional unrelated configChange flag in AndroidManifest. Difference for me is that the AppBar moves up and doesn't leave room for the status bar at all. A quick slide down from the top reveals the status bar over the app bar.

Also using 1.12.13 hotfix 5, and removing the only calls to SystemChrome methods makes no difference. I believe this to be configuration related, I just don't know where.

![image](https://user-images.githubusercontent.com/4586280/72864447-b5df3f80-3cdc-11ea-80e5-8ab7413d60fa.png)

**Comment by mikerockett** [comment]
Update: Removing `<item name="android:windowFullscreen">true</item>` from styles.xml solved it on my end. Also solves the above-mentioned TextFormField issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
