### ISSUE TITLE
ClampOverscrolls needs to wait until layout before clamping

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#4797]
Currently, ClampOverscrolls clamps the scrollOffset to the min/max scrollOffset at build time. But these min/max values are calculated based on the size of the content and its container - which we don't know until we've laid out the content. We should wait until layout before clamping the scrollOffset.

A further wrinkle is LazyBlock, which needs the scrollOffset to know what to lay out, which in turn affects its size. So there's a circular dependency.

A proper algorithm would probably need to:
1. Layout at the unclamped scrollOffset to find content size.
2. Clamp scrollOffset to find new scrollOffset.
3. Layout again at new scrollOffset. Hope content size doesn't change again.

This issue surfaced in https://github.com/flutter/flutter/issues/4597 .

**Comment by HansMuller** [comment]
The ClampOverscrolls widget exists, at least in part, to enable the OverscrollIndicator to detect overscrolling in its Scrollable descendant. There's no real need for the descendant to actually overscroll, the OverscrollIndicator really only needs to know if the scrollable has reached its min or max content limit. So maybe an alternative remedy would be to inhibit overscrolling  (and the animation that goes along with it).

**Comment by sethladd** [comment]
https://github.com/flutter/flutter/issues/4597 is closed. Just checking, we are keeping this one open?

**Comment by HansMuller** [comment]
Yes because https://github.com/flutter/flutter/issues/4883

**Comment by mpcomplete** [comment]
This is no longer an issue because we clamp to INFINITY for the first frame. Maybe it could be improved further, but for now, I'm closing.
