### ISSUE TITLE
Downloaded executables cannot execute on host. - v1.7.8 on Mac OS X 10.15

### ISSUE THREAD

**Issue by prasid444** [flutter/flutter#47978]
App works fine in debug mode using flutter run  or running from xcode but when releasing Product>Archive it gives error.

## Steps to Reproduce

1. `flutter build ios --release`

**Target Platform:**
IOS
**Target OS version/browser:**
>9.0

## Logs

```
Building AOT snapshot in release mode (ios-release)...          
arch: posix_spawnp: /Applications/Development/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot: Bad CPU type in executable

Dart snapshot generator failed with exit code 1

Building App.framework for arm64...
Building AOT snapshot in release mode (ios-release)...             16.7s
Built to build/aot/.
Snapshotting (IOSArch.armv7) exited with non-zero exit code: 1
Snapshotting (IOSArch.arm64) exited with non-zero exit code: 0
cp: build/aot/App.framework: No such file or directory
error: cannot parse the debug map for 'build/aot/App.framework/App': No such file or directory
Failed to generate debug symbols (dSYM) file for build/aot/App.framework/App.



```
```

flutter doctor -v OUTPUT
[!] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Applications/Development/flutter
    • Framework revision 20e59316b8 (5 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/prasid444/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/prasid444/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```
```

**Comment by iapicca** [comment]
Hi @prasid444 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by prasid444** [comment]
> Hi @prasid444
> could you please run
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter clean`
> `flutter pub cache repair`
> If the issue persist please provide your updated
> `flutter doctor -v` and `flutter run --verbose`
> thank you

Hello @iapicca 
I could not update flutter at this moment (due to changes in new update, for which I need to update lots of my code), but will try to do this later. I am in stable channel. For now I solved it by replacing "valid architecture: arm64 armv7" to "valid architecture: arm64 " only. I hope removing armv7 will not lessen the targeted ios devices.

**Comment by iapicca** [comment]
Hi @prasid444 
I believe this issue might reside within the compatibility of
the version of flutter you are using and macos catalina
https://github.com/flutter/flutter/issues/34000

can you try with the previous stable `1.9.1`?
thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
