### ISSUE TITLE
Unsuported Android Plugin version: 3.5.3.

### ISSUE THREAD

**Issue by IreliaStark1** [flutter/flutter#47972]
Flutter 1.12.13+hotfix.5 • channel stable

When I run cmd: `flutter run --verbose`. It give me an error: `Unsuported Android Plugin version: 3.5.3`.

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      getGradleVersionFor (package:flutter_tools/src/android/gradle_utils.dart:203:3)
#2      getGradleVersionForAndroidPlugin (package:flutter_tools/src/android/gradle_utils.dart:150:10)
#3      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:821:7)
#4      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#15     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

**Comment by iapicca** [comment]
Hi @IreliaStark1 
if you recently upgrade flutter you might want to run
`flutter clean`
`flutter pub cache repair`
also keep in mind that some 3rd party plugins are not "1.12 ready".

If the issue persist please provide your updated 
`flutter doctor -v` and your **full** `flutter run --verbose`?
Thank you

**Comment by medyas** [comment]
replicate of #47072 . you can downgrade to Android Plugin version 3.5.0 as Flutter max supports is this version: 
```
  if (_isWithinVersionRange(androidPluginVersion, min: '3.4.0', max: '3.5.0')) {
    return '5.6.2';
  }
  throwToolExit('Unsuported Android Plugin version: $androidPluginVersion.');
  return '';
```

**Comment by swaggymiller** [comment]
I have trapped in this issue one week until i notice this issue,which has lead my project delay 3 days

**Comment by IreliaStark1** [comment]
> I have trapped in this issue one week until i notice this issue,which has lead my project delay 3 days

@swaggymiller Try to change your Gradle to 3.5.0. I noticed the gradle version in an example of flutter sdk is 3.5.0.

**Comment by swaggymiller** [comment]
> > I have trapped in this issue one week until i notice this issue,which has lead my project delay 3 days
> 
> @swaggymiller Try to change your Gradle to 3.5.0. I noticed the gradle version in an example of flutter sdk is 3.5.0.
Prerequisites is I am in china,maybe firewall will influnce us dowmload pom file or update gradle

**Comment by iapicca** [comment]
Hi all
does this possible [solution](https://github.com/flutter/flutter/issues/47072#issuecomment-568904891)
fix the issue?
thank you

**Comment by IreliaStark1** [comment]
> Hi all
> does this possible [solution](https://github.com/flutter/flutter/issues/47072#issuecomment-568904891)
> fix the issue?
> thank you

@iapicca I fixed the issue by changed my gradle version to 3.5.0. Thanks for your support. But there is anther issue happened in my project. I commit a new issue. #48060

**Comment by IreliaStark1** [comment]
> Prerequisites is I am in china,maybe firewall will influnce us dowmload pom file or update gradle

china too...

**Comment by swaggymiller** [comment]
> > Prerequisites is I am in china,maybe firewall will influnce us dowmload pom file or update gradle
> 
> china too...

not bad

**Comment by iapicca** [comment]
I'm glad that you fixed the issue @IreliaStark1
thank you for letting me know

**Comment by cirediew** [comment]
> replicate of #47072 . you can downgrade to Android Plugin version 3.5.0 as Flutter max supports is this version:
> 
> ```
>   if (_isWithinVersionRange(androidPluginVersion, min: '3.4.0', max: '3.5.0')) {
>     return '5.6.2';
>   }
>   throwToolExit('Unsuported Android Plugin version: $androidPluginVersion.');
>   return '';
> ```

Why not display the min and max in the error message?
