### ISSUE TITLE
Google Maps Flutter Web Integration 

### ISSUE THREAD

**Issue by onurc4kir** [flutter/flutter#47987]
Is there anyone to work for flutter google maps for web ? I searched but Some people talked about 4 month ago and after that no one say nothing ? I think it is too essential for many application and many flutter developers waiting it.

**Comment by iapicca** [comment]
Hi @onurc4kir 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/45292)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
