### ISSUE TITLE
Need Help to instal this i am facing problem at this stage please help 

### ISSUE THREAD

**Issue by ushar786** [flutter/flutter#47982]
X Android license status unknown.
      Try reinstalling or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

**Comment by Ahmadre** [comment]
just execute this inside your flutter project: ```flutter doctor --android-licenses```

**Comment by jonahwilliams** [comment]
The instructions at https://flutter.dev/setup/#android-setup should contain all of the information needed to continue here. If you've already downloaded the Android SDK, then you'll need to accept licenses using the command above
