### ISSUE TITLE
webview_flutter memory leak

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#47992]
_Originally posted by @nuptdzs in https://github.com/flutter/flutter/issues/24714#issuecomment-567408846_

> with IOS ,I use webview_flutter plugin,I repeatedly enter and exit this page .The memory will grow all the time, and in the leaks tool of Xcode, we can see that a variable is not released after exiting, as shown in the figure below, it seems that some other changes to GL cause this problem.

> ![image](https://user-images.githubusercontent.com/11865368/71161579-90e25180-2284-11ea-8667-891f10bb4b05.png)

> ![image](https://user-images.githubusercontent.com/11865368/71161597-96d83280-2284-11ea-8c51-8eb285772a4d.png)

```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)
```

> Can you try to analyze this problem, and look forward to your answer. This problem will cause our application memory to grow until it crashes, hoping to give us a solution.

@nuptdzs can you please share a minimal code sample that reproduces the issue?

cc @cyanglaz

**Comment by Doris1994** [comment]
I also encountered the same problem，See the previous solution `https://github.com/flutter/flutter/commit/93f339fb67df2934e618cfca0f9d5bd7982e4bcd` , flutter version is v1.12.13+hotfix.5.
But the problem still exists

**Comment by owenkealey** [comment]
This has been open for 7 months -- am I correct in assuming platform views in flutter have been causing memory leaks for the last seven months?

**Comment by ycv005** [comment]
Tagging all Webview team: @blasten @TahaTesser @chinmaygarde @jason-simmons Do this issue is fixed ?

**Comment by danagbemava-nc** [comment]
Hi @amirh, can you please confirm if you're still experiencing this issue on the latest flutter `stable` and `webview_flutter` version?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
