### ISSUE TITLE
"flutter logs" claims "No supported devices connected." when not run in directory with pubspec.yaml

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47996]
Steps to reproduce:
1. Plug in a device.
2. `flutter create dummy`
3. `cd dummy/lib`
4. `flutter logs`

Expected results:
Logs should start, probably not showing much unless you have a debug-mode Flutter app running already on the device.

Actual results:
```
No supported devices connected.
```

Works fine if you run it from a directory with a `pubspec.yaml`, but that command shouldn't need a Flutter package to find the devices on which logs are available.

**Comment by jonahwilliams** [comment]
The issue here is that we are incorrectly checking if the current project supports the device before filtering logs. We should be project agnostic in this command.
