### ISSUE TITLE
Z-Index problem on Matrix4

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#48005]
Hy Flutter,

now i try to writing a 3d number circle, put the problem in my case is z-index, it cann't fixed with transition Z or any thing i tried.

like in this image 👇🏻, it should be set the 01 number before the 13.
<img width="100" src="https://i.ibb.co/9NR5chf/Screenshot-2019-12-31-at-01-28-04.png" />

its a way to fix this problem?

**Comment by VladyslavBondarenko** [comment]
Hi @Kassan424kh 
To better address the issue, would be helpful
if you could post a minimal code sample to reproduce your case
Thank you

**Comment by Kassan424kh** [comment]
I fixed this problem with sorting the list of numbers after indexes that at front positioned showing.
