### ISSUE TITLE
[web]:  Can I do Server-Side Rendering using flutter web?

### ISSUE THREAD

**Issue by zwl1619** [flutter/flutter#48004]
Can I do Server-Side Rendering using flutter web?

**Comment by iapicca** [comment]
Hi @zwl1619 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47600) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
