### ISSUE TITLE
Drop Down Button

### ISSUE THREAD

**Issue by KadivetiJayaraj** [flutter/flutter#48009]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by KadivetiJayaraj** [comment]
I/flutter (22309): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22309): The following assertion was thrown building Register(dirty, dependencies: [MediaQuery], state:
I/flutter (22309): _RegisterState#84a2d(tickers: tracking 1 ticker)):
I/flutter (22309): There should be exactly one item with [DropdownButton]'s value: Select Blood group.
I/flutter (22309): Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
I/flutter (22309): 'package:flutter/src/material/dropdown.dart':
I/flutter (22309): Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
I/flutter (22309):               items.where((DropdownMenuItem<T> item) {
I/flutter (22309):                 return item.value == value;
I/flutter (22309):               }).length == 1'
I/flutter (22309): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22309): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22309): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22309):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22309): The relevant error-causing widget was:
I/flutter (22309):   Register
I/flutter (22309):   file:///Users/altaitsolutions/Desktop/Jayaraj/flutter_altaoss/lib/login_register.dart:829:70
I/flutter (22309): When the exception was thrown, this was the stack:
I/flutter (22309): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:805:15)
I/flutter (22309): #3      _RegisterState.build (package:flutter_altaoss/login_register.dart:1505:31)
I/flutter (22309): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (22309): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (22309): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #85     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (22309): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (22309): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (22309): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (22309): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (22309): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (22309): #108    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
I/flutter (22309): #109    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (22309): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #111    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:605:16)
I/flutter (22309): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #115    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (22309): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #119    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (22309): #120    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (22309): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (22309): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #126    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (22309): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (22309): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #130    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (22309): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #134    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (22309): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (22309): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (22309): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (22309): #138    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (22309): #139    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (22309): #140    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (22309): #141    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (22309): #142    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (22309): #143    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (22309): #147    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (22309): #148    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (22309): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (22309): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Register(dirty, dependencies: [MediaQuery], state: _RegisterState#84a2d(tickers: tracking 1 ticker)):
There should be exactly one item with [DropdownButton]'s value: Select Blood group. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Register file:///Users/altaitsolutions/Desktop/Jayaraj/flutter_altaoss/lib/login_register.dart:829:70
When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:805:15)
#3      _RegisterState.build (package:flutter_altaoss/login_register.dart:1505:31)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
There should be exactly one item with [DropdownButton]'s value: Select Blood group. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'
The relevant error-causing widget was: 
  Register file:///Users/altaitsolutions/Desktop/Jayaraj/flutter_altaoss/lib/login_register.dart:829:70
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by HansMuller** [comment]
Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem, and we'll look into it. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
