### ISSUE TITLE
The example called snapping_page_scroll.dart can't run.

### ISSUE THREAD

**Issue by wforskk** [flutter/flutter#48012]
I just run the example but it couldn't success and it said "type 'int' is not a subtype of type 'bool'".
I use this example.↓↓
https://pub.dev/packages/snapping_page_scroll#-readme-tab-

other detail
 - snapping_page_scroll: ^1.2.5

What is the cause?
package or me?

**Comment by iapicca** [comment]
Hi @wforskk 
you may want to open an issue in the dedicated [github](https://github.com/Hannnes1/snapping_page_scroll).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
