### ISSUE TITLE
Flutter SDK installation is not completed

### ISSUE THREAD

**Issue by Hasib74** [flutter/flutter#48019]
After updating flutter sdk it is showing that flutter sdk installation is not completed . On the other hand i have saw the flutter official sdk installation page the sdk download is showing loading then failed.

**Comment by dsourav** [comment]
i am also having the same problem

**Comment by dsourav** [comment]
**i am also having the same issue**

![Screenshot from 2020-01-01 22-32-15](https://user-images.githubusercontent.com/18255469/71643718-16371e80-2ce7-11ea-8371-320d77164bce.png)

**Comment by iapicca** [comment]
Hi @Hasib74  
the situation you are describing
might depends from temporary lack of connectivity
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
If the issue persist please provide your updated `flutter doctor -v` 
thank you

**Comment by TahaTesser** [comment]
Hi @Hasib74 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
