### ISSUE TITLE
Flutter mojo content handler should support starting isolates paused

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#4802]
The Mojo Dart content handler supports `--pause-isolates-on-start` and the standalone flutter shell [seems to](https://github.com/flutter/engine/blob/master/sky/shell/shell.cc#L135) support it too (perhaps as --start-paused). This would be extremely extremely useful for debugging.

I think it's as easy as adding a check at:
https://github.com/flutter/engine/blob/master/sky/shell/platform/mojo/main_mojo.cc#L44

Is that right? Would you take a CL?

**Comment by abarth** [comment]
Yep, that looks like the right place.  Happy to take a CL.
