### ISSUE TITLE
Android resets after using image_picker

### ISSUE THREAD

**Issue by jellyNoone** [flutter/flutter#48028]
Hi, I've noticed for some time now that my app crashes / resets when using image_picker, it didn't used to. Now I've tried the example project for the image_picker and it seemed to work fine until I noticed it recovers the lost data. 
To be fair I'm runing my app on Lenovo A6000( Lenovo A6000 • 95a131c3 • android-arm • Android 5.0.2 (API 21) ). I believe this issue is related to the default state managment of the OS. Since I haven't ran into these problems when running the app on iOS. 
I'd just like to get conformation this is the case, because in my implementation the problem isn't the image_picker but other events like launching a new window to review the Policy page... and the most important one when having to authenticate a payment method. I'm using the [stripe_payment ](https://pub.dev/packages/stripe_payment)plugin for the implementation of stripe payments, I'm woried more about handling the issue here then with images. 
When going through github I noticed the issue [#6827](https://github.com/flutter/flutter/issues/6827) I think this is related to that or more accurately is the same problem, but since I'm not sure, (I could be wrong, I've been a serious programmer for less then a year now, and regarding android/ios development I know very little, I've only had experiance working with Flutter for mobile development).
Please let me know if I've identified the problem correctly?

**Comment by iapicca** [comment]
Hi @jellyNoone  
about `image_picker`,
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` (with the crash)?
For teh 3rd party plugin [flutter_stripe_payment](https://pub.dev/packages/stripe_payment)
you may want to open an issue in the dedicated [github](https://github.com/jonasbark/flutter_stripe_payment/issues)
Thank you

**Comment by TahaTesser** [comment]
Hi @jellyNoone 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
