### ISSUE TITLE
connectivity plugin for flutter

### ISSUE THREAD

**Issue by shovael** [flutter/flutter#48033]
can you please migrate connectivity plugin to androidX?  there are so many other plugins already using androidX and I just can't use this plugin  because it's not supported

**Comment by iapicca** [comment]
Hi @shovael  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by shovael** [comment]
i believe the error i was getting was due to androidX compatibility, i found a temporary solution on this issue: https://github.com/flutter/flutter/issues/42887
