### ISSUE TITLE
flutter test doesn't work with FLUTTER_DEV

### ISSUE THREAD

**Issue by kaiyuanw** [flutter/flutter#4803]
## Steps to Reproduce

If you run "flutter test" on zsh, you got that error.  But if you run flutter under bash, it works fine.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/kaiyuanw/vanadium/release/projects/baku/deps/flutter
    • Framework revision 639532bd51 (88 minutes ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /usr/local/google/home/kaiyuanw/Intern/Android/Sdk
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
## Logs and Crash Reports

Failed to load "/path/to/myapp/test/unit_test.dart": Connection closed before test suit loaded.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
When fixing this we should make sure to add some tests to the bots that run a bunch of things under zsh. This isn't the first time we've been built by unusual shells not working.

**Comment by abarth** [comment]
Turns out the problem is FLUTTER_DEV.

**Comment by abarth** [comment]
IMHO, we should just remove FLUTTER_DEV.  We've had this problem repeatedly where it's not an exercised configuration and is broken for end-developers who stumble upon it.

**Comment by devoncarew** [comment]
I'll remove FLUTTER_DEV (I believe the specific issue in this case is a checked mode issue when running `flutter test`).

**Comment by abarth** [comment]
> I believe the specific issue in this case is a checked mode issue when running flutter test

Yes, we'll need to fix that as well.  I'm sure it's my fault, and I can take a look at fixing it.  @Hixie suggested on gitter that we run the flutter tool in checked mode all the time, which is probably a good idea as well.
