### ISSUE TITLE
flutter doctor failed to retrieve the Dart SDK

### ISSUE THREAD

**Issue by azmainadel** [flutter/flutter#48031]
## Steps to Reproduce

1. Install the Flutter SDK
2. Run `flutter doctor`

## Logs

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```
## Note
* I am not from China
* I am not using any VPN.

**Comment by sohan-bkash** [comment]
I'm also facing the same issue.

**Comment by mendax47** [comment]
me too... :3

**Comment by dsourav** [comment]
i am also having the issue can anyone have the solution

**Comment by Mamun361054** [comment]
i am aslo

**Comment by gitAbid** [comment]
Same Here :(

**Comment by azmainadel** [comment]
Hello all,
I temporarily bypassed the problem by installing the Dart SDK while connected to a VPN. 

I think `https://storage.googleapis.com/` is/was blocked in the region '_Bangladesh_'. So `flutter doctor` does not work normally.

**Comment by amani27** [comment]
Same problem here. :(

**Comment by shahparan** [comment]
Same Here :(

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/48030

**Comment by sohan-bkash** [comment]
> Hello all,
> I temporarily bypassed the problem by installing the Dart SDK while connected to a VPN.
> 
> I think `https://storage.googleapis.com/` is/was blocked in the region '_Bangladesh_'. So `flutter doctor` does not work normally.

I tried installing the Dart SDK using VPN and it worked. But it would be better to not having to use VPN.

**Comment by Sadmansamee** [comment]
facing the same

**Comment by yeahia2508** [comment]
Same problem here :(

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/48030.

**Comment by azmainadel** [comment]
As I saw in #48030, the logs said the issue had something to do with MITM attack. I did not get that output. Are these issues really the same?

**Comment by dsourav** [comment]
@azmainadel yes it's same please do read entire comments of #48030

**Comment by ittisafur** [comment]
I am getting the same error. I updated my openssl. But still, the error remains followed the `[#48030](https://github.com/flutter/flutter/issues/48030)` . By using vpn i can access storage.googleapis.com How can this be fixed ? any suggestion ?

**Comment by amani27** [comment]
> I am getting the same error. I updated my openssl. But still, the error remains followed the #48030 . By using vpn i can access storage.googleapis.com How can this be fixed ? any suggestion ?

From yesterday, there is some problem with storage.googleapis.com in Bangladesh. It's an issue with BTCL.
To overcome this issue, VPN is a workaround until the issue gets fixed. Hopefully it'll be fixed soon & there's nothing to worry about.

**Comment by meftaul** [comment]
Facing same issue from Bangladesh.

**Comment by dsourav** [comment]
is there any fix..?

**Comment by pyshawon** [comment]
USE VPN. it will be fixed. BTCL/BTRC blocked google APIs(storage.googleapis.com )
