### ISSUE TITLE
CupertinoTabBar colour does not update with brightness, for dark mode.

### ISSUE THREAD

**Issue by samir97** [flutter/flutter#48040]
My app offers dark mode, which reflects the system settings, however, the user may decide they want dark mode at all times, for this I change the theme brightness to dark. Changing the brightness to dark does not change the appearance of the CupertinoTabBar to dark, however when I turn on dark mode on my iPhone, the CupertinoTabBar does turn darker.

This bug was introduced in the new release of Flutter, as previously changing the brightness to dark, did change the appearance of the CupertinoTabBar.

## Steps to Reproduce

```
ThemeData(
        primarySwatch: Colors.blue,
        brightness: Brightness.dark
      )
```

```import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CupertinoTabBar Dark Mode',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        brightness: Brightness.dark
      ),
      home: MyHomePage(title: 'CupertinoTabBar Dark Mode'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(
          activeColor: CupertinoColors.activeBlue,
          items: [
            BottomNavigationBarItem(
                icon: Icon(Icons.info),
                title: Text('Info')),
            BottomNavigationBarItem(
                icon: Icon(Icons.help),
                title: Text('Help')),
          ],
        ),
        tabBuilder: (BuildContext context, int index) {
          return CupertinoTabView(
            builder: (BuildContext context) => Container(),
          );

        },
      ),
    );
  }
}
```

**Target Platform: iOS**
**Target OS version/browser: iOS 12**
**Devices: Simulator, iPhone XR**

![image](https://user-images.githubusercontent.com/29393146/71643812-e7ed1b00-2cb5-11ea-9de9-917327397ae3.png)

**Comment by samir97** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/Development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by LongCatIsLooong** [comment]
Thanks for reporting this issue! This sounds like a dup of https://github.com/flutter/flutter/issues/47989. Setting brightness in `ThemeData` doesn't correctly propagate to Cupertino widgets at the moment. There's a workaround: https://github.com/flutter/flutter/issues/47255#issuecomment-569333862.

**Comment by NiwuoDev** [comment]
@LongCatIsLooong even if the cupertino theme is override doesn't update the top bar, bottom tabs only bottom tabs changes.

Flutter version 1.12.13+hotfix.8
iPhone 11 13.3
![image](https://user-images.githubusercontent.com/21696326/75820554-8c4d1580-5d6a-11ea-8fab-e0140d688f33.png)

![image](https://user-images.githubusercontent.com/21696326/75820610-a850b700-5d6a-11ea-817e-e58186dddbff.png)

![image](https://user-images.githubusercontent.com/21696326/75820653-bef70e00-5d6a-11ea-98a3-44e004a0710a.png)

**Comment by LongCatIsLooong** [comment]
@NiwuoDev Are using a material app bar? Could you provide a minimal sample app that we can use to reproduce the problem?

**Comment by NiwuoDev** [comment]
@LongCatIsLooong yes I'm using material app bar, how can I share you a minimal sample?
![image](https://user-images.githubusercontent.com/21696326/75827269-42b6f780-5d77-11ea-8fef-f77ba8cc4478.png)

**Comment by LongCatIsLooong** [comment]
@NiwuoDev I think the best way would be creating a new issue. You can include a minimal code sample in that issue along with other context such as the output `flutter doctor -v`. Ideally the sample code should be distilled so you can just paste it in the issue itself.
