### ISSUE TITLE
The problem of About adding to Android

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter#48041]
- [Import flutter module by aar](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar)

 gradle kts file cannot import dependencies using `profileImplementation` method

- [Import via flutter module source code](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)

An error will be reported when the main application directory is not in the project root directory

This is settings.gradle that can successfully import flutter:

```java
include ':app'  // ProjectDir/app 
setBinding(new Binding([gradle: this]))
evaluate(new File(
  settingsDir.parentFile,  
  'my_flutter/.android/include_flutter.groovy'
))
```

But the settings.gradle I want should look like this:

```java
include ':tree:app'  // ProjectDir/tree/app
setBinding(new Binding([gradle: this]))
evaluate(new File(
  settingsDir.parentFile,  
  'my_flutter/.android/include_flutter.groovy'
))
```

**Comment by jmagman** [comment]
\cc @blasten

**Comment by blasten** [comment]
> Import flutter module by aar
 gradle kts file cannot import dependencies using profileImplementation method

@vvVenom did you follow step 4 from this list https://flutter.dev/assets/development/add-to-app/android/project-setup/build-aar-instructions-3ead7aa851afa766c7435c718755f748558c7379877a7b0b3d71597bab0ee4d7.png?

**Comment by vvVenom** [comment]
> @vvVenom did you follow step 4 from this list https://flutter.dev/assets/development/add-to-app/android/project-setup/build-aar-instructions-3ead7aa851afa766c7435c718755f748558c7379877a7b0b3d71597bab0ee4d7.png?

yes, but I use kotlin gradle dsl, there is no `profileImplementation` method

**Comment by blasten** [comment]
You can still do something like this:
```.kt
android {
    buildTypes {
        create("profile") {
             initWith(getByName("debug"))
        }
    }
}
```

**Comment by blasten** [comment]
Please reopen if this still an issue.

**Comment by vvVenom** [comment]
> You can still do something like this:
So this, how to achieve dependency
![image](https://user-images.githubusercontent.com/58068445/71761034-275b7780-2f01-11ea-9d1d-ee1917d72bee.png)
