### ISSUE TITLE
[web] add web support to gRPC package

### ISSUE THREAD

**Issue by yuhorun** [flutter/flutter#48054]
I tried to integrate gPRC into fluttr-web, but it always failed.I don't know if there is a problem with my code or gRPC can't be integrated into flutter-web.

### dependencies: 
flutter: sdk: flutter grpc: ^2.1.3 protobuf: ^1.0.1

![image](https://user-images.githubusercontent.com/45552382/71651907-2dfcba00-2d5c-11ea-81d8-a445b34bf793.png)

### Here's my server-side code:
![image](https://user-images.githubusercontent.com/45552382/71651918-5edcef00-2d5c-11ea-8331-7b0fc3fbed82.png)

### I have two questions:
The first one is whether the gRPC can be integrated into fluter-web? 
The second one is what libraries I need and whether there are any examples? 

**thank you.**

**Comment by iapicca** [comment]
Hi @yuhorun 
at the moment [grpc package](https://pub.dev/packages/grpc) supports only android and iOS
I'm taking the liberty of turning your question into a proposal
let me know if you disagree
thank you

**Comment by yuhorun** [comment]
> Hi @yuhorun
> at the moment [grpc package](https://pub.dev/packages/grpc) supports only android and iOS
> I'm taking the liberty of turning your question into a proposal
> let me know if you disagree
> thank you

ok.thank you

**Comment by yjbanov** [comment]
@sigurdm is there anything we can do here on the Flutter side, or should we move this discussion to the grpc repo?

**Comment by sigurdm** [comment]
The grpc package has an implementation of grpc-web. It can be reached with `package:grpc/grpc_web.dart`.
That means to have a program working in both mobile and web you need to do a conditional import in a file for obtaining a `GrpcChannel` object.

The reason for doing this is that grpc-web is different protocol.
But for convenience we probably want to provide a wrapper doing the conditional import.

I created a small example that seems to work: https://github.com/sigurdm/grpc_web_flutter_example

**Comment by yjbanov** [comment]
Thanks, @sigurdm! Sounds like there's nothing to do on the Flutter side. Closing.

**Comment by yuhorun** [comment]
> The grpc package has an implementation of grpc-web. It can be reached with `package:grpc/grpc_web.dart`.
> That means to have a program working in both mobile and web you need to do a conditional import in a file for obtaining a `GrpcChannel` object.
> 
> The reason for doing this is that grpc-web is different protocol.
> But for convenience we probably want to provide a wrapper doing the conditional import.
> 
> I created a small example that seems to work: https://github.com/sigurdm/grpc_web_flutter_example

Do you have to use proxies?Envoy. Why can't I just use it on golang's server?Like the one above.

**Comment by gedw99** [comment]
I think you can use the golang based grpc gateway also.

**Comment by sigurdm** [comment]
I haven't used golang's server. If it can serve other grpc-web clients it should be able to serve dart/flutter.
https://godoc.org/github.com/improbable-eng/grpc-web/go/grpcweb might help.

**Comment by winwisely99** [comment]
> I haven't used golang's server. If it can serve other grpc-web clients it should be able to serve dart/flutter.
> https://godoc.org/github.com/improbable-eng/grpc-web/go/grpcweb might help.

@sigurdm Not sure it will work with standard dart GRPC for Flutter web. 

We got it working using envoy on kubernetes. See: https://github.com/getcouragenow/packages/blob/master/maintemplate/README.md

**Comment by jscoys** [comment]
Ok so can someone tell us if the grpc flutter package is going to work in a web flutter project finally???

**Comment by jscoys** [comment]
Ok I tested and it seems that it's not possible... for now seems to be running with the grpc package on desktop/ios/android but for not on web where we've got to maintain a RESTFul API system on the side to handle requests... or use the GRPC_web package but with a proxy...

**Comment by kaushikchaubal** [comment]
> Ok I tested and it seems that it's not possible... for now seems to be running with the grpc package on desktop/ios/android but for not on web where we've got to maintain a RESTFul API system on the side to handle requests... or use the GRPC_web package but with a proxy...

I think that is consistent with what I understand going through this thread plus trying it out locally. @sigurdm has created a simple example (https://github.com/sigurdm/grpc_web_flutter_example) for your later option. @sigurdm - please shout out if our understanding is incorrect.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by JohnGalt1717** [comment]
So I'm not seeing anything that identifies how to do a conditional for the platform to create the right channel with an abstraction. It seems like right now you have to use grpc-web if you want to work with all 3.

Does anyone have a working shim that selects the right version of grpc and returns a channel that can then be shared? it seems that long term this is a must so that on platforms that support it, it uses grpc and for web it uses grpc-web for efficiency if nothing else.  And then of course throws on the stuff that isn't supported on grpc-web.

So to me this shouldn't be closed because there's still not really a cross platform package for flutter. (and of course macos, linux and windows are still pending)

**Comment by 4F2E4A2E** [comment]
>Yes - you cannot make http2 connections from a web-page. Therefore you cannot make grpc calls.

Actually all Browser have support for http2 since many years. And you can make http2 connections from the browser. 

There is just no native grpc http2 implementation out there:

> It is currently impossible to implement the HTTP/2 gRPC spec3 in the browser, as there is simply no browser API with enough fine-grained control over the requests. For example: there is no way to force the use of HTTP/2, and even if there was, raw HTTP/2 frames are inaccessible in browsers. The gRPC-Web spec starts from the point of view of the HTTP/2 spec, and then defines the differences. 


https://grpc.io/blog/state-of-grpc-web/#the-grpc-web-spec

**Comment by 50gramx** [comment]
> The grpc package has an implementation of grpc-web. It can be reached with `package:grpc/grpc_web.dart`.
> That means to have a program working in both mobile and web you need to do a conditional import in a file for obtaining a `GrpcChannel` object.
> 
> The reason for doing this is that grpc-web is different protocol.
> But for convenience we probably want to provide a wrapper doing the conditional import.
> 
> I created a small example that seems to work: https://github.com/sigurdm/grpc_web_flutter_example

@sigurdm thanks. I've been meaning to use a envoy to proxy http2 to http1. However, I also read that with some tweaking, I can make my current http2 services into http1 with google.apis in protobuf. Please shed some light if you're aware of this. Thanks.

_this is not directly related to flutter issue, but related to grpc web_

**Comment by pumano** [comment]
@50gramx you should use envoy proxy as api gateway or kubernetes ingress with envoy if you want to use grpc-web. Your flutter client request backend via http 1.1 then envoy translate that request to http/2 and then translate it to your backend microservices. Also as alternative you can use go grpc gateway between your microservices and mobile app. That gateway generate REST API gateway for flutter, but translate requests to grpc from rest. It's a bit harder (double your protobuf contracts) because same contact should be in gateway. But no need to deal with grpc-web in flutter.

**Comment by 50gramx** [comment]
> @50gramx you should use envoy proxy as api gateway or kubernetes ingress with envoy if you want to use grpc-web. Your flutter client request backend via http 1.1 then envoy translate that request to http/2 and then translate it to your backend microservices. Also as alternative you can use go grpc gateway between your microservices and mobile app. That gateway generate REST API gateway for flutter, but translate requests to grpc from rest. It's a bit harder (double your protobuf contracts) because same contact should be in gateway. But no need to deal with grpc-web in flutter.

The alternative sounds like a better plan as web clients won't be needing to have proto files, which directly compromises service security in web. I've started looking into https://github.com/grpc-ecosystem/grpc-gateway.

Thanks @pumano.

**Comment by 50gramx** [comment]
@pumano I went with the alternative option by creating a simple Django-based gateway to convert gRPC APIs (http2) to/from REST APIs. Adding this comment because, I literally
