### ISSUE TITLE
Images scaling inconsistent across devices

### ISSUE THREAD

**Issue by Sp4Rx** [flutter/flutter#48069]
## Steps to Reproduce

Flutter is rendering same image and text with different sizes on different phones. Check the screenshot below. Left: OnePlus 7, right : Redmi Note 4. Ignore the spacing, check the image and text is bigger on the right one(Redmi). I assume this issue is regarding screen density.

![image](https://i.imgur.com/8kG6lKI.jpg)

## Flutter Doctor
```
[√] Flutter (Channel unknown, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\Users\heysu\Documents\flutter
    • Framework revision 1aedbb1835 (3 months ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\heysu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\heysu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Redmi Note 4 • 46e8c6c00504 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @Sp4Rx 
I see there's an issue addressing the case you described.
Please follow up on [that issue](https://github.com/flutter/flutter/issues/21451),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Sp4Rx** [comment]
Hey @VladyslavBondarenk 
Thanks for responding. The issue you mentioned is for text scaling only. What about the image scaling?
Above all flutter takes **dp** as unit right? I don't understand why am I facing this issue

**Comment by iapicca** [comment]
Hi @Sp4Rx
could you please provide a minimal code sample?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution

**Comment by Sp4Rx** [comment]
Hey, 
Sorry for the late response.
Here is the minimum code. I copied the code from my project and removed all the redundant widgets.


```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: Colors.pink),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Stack(
            children: <Widget>[
              Container(
                height: double.infinity,
                width: double.infinity,
                child: Image.network(
                    'https://leher-media.s3.ap-south-1.amazonaws.com/ctaImages/selectChannels.png'),
              ),
              Positioned(
                bottom: 100,
                left: 0,
                right: 0,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    TextHero(),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class TextHero extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      'Hello, World!',
      style: TextStyle(
        fontFamily: 'Roboto Condensed',
        fontSize: 36.0,
        fontStyle: FontStyle.normal,
        fontWeight: FontWeight.bold,
      ),
    );
  }
}
```

In my project I have used [AdvancedNetworkImage](https://pub.dev/packages/flutter_advanced_networkimage) for image loading. But here I have used the native one.

**Comment by dnfield** [comment]
The images look like they're at the same scaling to me.

It's that your positioned widget is 100 from the bottom - which is 100 logical pixels - which is different depending on your devicePixelRatio. 

The sample you gave is different from the images - can you share updated images with the sample on your two test devices?

Can you also have the sample print out `WidgetsBinding.instance.window.physicalSize` and `WidgetsBinding.instance.window.devicePixelRatio`?

**Comment by dnfield** [comment]
I'm going to reluctantly close this issue for now - if you have additional details to add please feel free to comment here and we can reopen.

Without further details, this looks like it's all WAI to me.
