### ISSUE TITLE
Generated apk could not open and just showing App Info screen from settings

### ISSUE THREAD

**Issue by div3791** [flutter/flutter#48068]
## Steps to Reproduce

1. Generated apk by writing "flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi" command in terminal
##Output
<img width="777" alt="Screenshot 2020-01-02 at 4 24 55 PM" src="https://user-images.githubusercontent.com/55969576/71663780-88a60e00-2d7c-11ea-9f9d-a5c3211b9ce4.png">

2. installed generated apk into physical android device.
3. when I open app, it shows app info screen from settings only.

## Logs
No log generated as I was installing apk from file browser of my Nokia 8.1 device
<img width="953" alt="Screenshot 2020-01-02 at 4 17 41 PM" src="https://user-images.githubusercontent.com/55969576/71663541-a1fa8a80-2d7b-11ea-967e-9146cefaf1f9.png">

After installing apk and when I try to open, it shows below screen instead of opening my app in my Nokia 8.1 device.
![1577962323885](https://user-images.githubusercontent.com/55969576/71663675-2220f000-2d7c-11ea-80e8-d17b8532e2d5.JPEG)
 

```
```

```
```

**Comment by iapicca** [comment]
Hi @phoelapyae69 
can you please provide your `flutter doctor -v` 
and your `flutter build apk --split-per-abi --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by div3791** [comment]
Thank you for the response @iapicca 
Issue resolved by adding some progaurd rules.
