### ISSUE TITLE
adb: failed to install /Users/snow/test/AndroidStudioProjects/flutter_weather/build/app/outputs/apk/app.apk:

### ISSUE THREAD

**Issue by nanyawei** [flutter/flutter#48064]
How does it work ? Only android failed
```
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/snow/test/AndroidStudioProjects/flutter_weather/build/app/outputs/apk/app.apk:
```

flutter run

```
Launching lib/main.dart on OD103 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/snow/test/AndroidStudioProjects/flutter_weather/build/app/outputs/apk/app.apk:
Error launching application on OD103.
```

flutter doctor -v
```
snowdeMacBook-Pro:flutter_weather snow$ flutter doctor -v
[✓] Flutter (Channel master, v1.13.6-pre.44, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.13.6-pre.44 at /Users/snow/test/flutter
    • Framework revision e768c92fbc (2 days ago), 2019-12-30 17:12:19 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/snow/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/snow/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    • Device 98ecdec8 is offline.

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Hi @nanyawei 
From your `flutter doctor -v` I can see that connected device is offline.
If it's a real device, try to 
1) disconnect it
2) turn Off “USB Debugging” and turn it on
3) connect the device again

Does it help you?
Thank you

**Comment by nanyawei** [comment]
thanks, My  .bash_profile  profile configuration problem

**Comment by VladyslavBondarenko** [comment]
I'm glad that you fixed the problem, 
thank you for letting me know.
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it

**Comment by timka2106** [comment]
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install D:\Android Studio\flut proje\flutter_app\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Error launching application on POCO X2.

forgive you tell me how to solve

**Comment by AqeelTariq97** [comment]
**flutter doctor shows no issue but the error still not gone**
### error
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\ML\AndroidStudioProjects\i_am_rich\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Error launching application on Redmi 8.


adb: failed to install C:\Users\ML\AndroidStudioProjects\i_am_rich\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Error launching application on Redmi 8.

adb: failed to install C:\Users\ML\AndroidStudioProjects\i_am_rich\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Error launching application on Redmi 8.


### flutter doctor
C:\Users\ML>flutter doctor -v
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.3 at C:\src\flutter
    • Framework revision 216dee60c0 (4 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ML\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Redmi 8 (mobile) • c255a8000007 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by qahtansaid** [comment]
Maybe you have insufficent space on your android, try to delete some app or you have'nt turn usb debuggin on

**Comment by Adithyakp8** [comment]
> Error: ADB exited with exit code 1
> Performing Streamed Install
> 
> adb: failed to install D:\Android Studio\flut proje\flutter_app\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
> Error launching application on POCO X2.
> 
> forgive you tell me how to solve

allow install via usb

**Comment by BubagraJamatia2001** [comment]
> > Error: ADB exited with exit code 1
> > Performing Streamed Install
> > adb: failed to install D:\Android Studio\flut proje\flutter_app\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
> > Error launching application on POCO X2.
> > forgive you tell me how to solve
> 
> allow install via usb

yeah this one worked for me after i turned on usb debuggin
