### ISSUE TITLE
sign_in_canceled exception not getting handeled by try-catch block 

### ISSUE THREAD

**Issue by OmkarSsawant** [flutter/flutter#48078]
As per  the official documentation I implemented the try catch block but when the user cancels the sign in operation the exception is thrown that is not handled by try catch block

```
Future<void> _handleSignIn() async {
  try {
    await _googleSignIn.signIn();
  } catch (error) {
    print(error);
  }

  }

```

**Comment by VladyslavBondarenko** [comment]
Hi @OmkarSsawant 
I see there's an open issue addressing the case you described.
Please follow up on [that issue](https://github.com/flutter/flutter/issues/44431),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
