### ISSUE TITLE
flutter test fails when run under checked mode

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4807]
From https://github.com/flutter/flutter/issues/4803, `flutter test` fails with a 'Connection closed' error when the flutter tool is run in checked mode. Once this is fixed, we should consider turning on checked mode for all runs of the flutter tool (`-c`).

**Comment by abarth** [comment]
I think the problem is with the stream sink/source type parameters.

**Comment by sethladd** [comment]
We should totally run tests with checked mode! :)

**Comment by Hixie** [comment]
This is fixed now. Moving to checked mode is https://github.com/flutter/flutter/pull/7655 and is blocked on unrelated stuff.
