### ISSUE TITLE
Cannot focus TextField inside RawKeyboardListener

### ISSUE THREAD

**Issue by KammererTob** [flutter/flutter#48076]
## Steps to Reproduce

This does not work:
```
Column(
      children: <Widget> [
        MaterialButton(
          child: Text("Focus Input!"),
          onPressed: () => _emailFocusNode.requestFocus(),
        ),
        RawKeyboardListener(
          focusNode: _emailFocusNode,
          child: TextField(
            controller: _emailInputController,
          ),
        )
      ]
);
```

This works:
```
Column(
      children: <Widget> [
        MaterialButton(
          child: Text("Focus Input!"),
          onPressed: () => _emailFocusNode.requestFocus(),
        ),
        TextField(
          autofocus: false,
          focusNode: _emailFocusNode,
          controller: _emailInputController,
        ),
      ]
    );
```

We are no longer able to provide the same focusNode to both the input and the RawKeyboardListener, because this leads to the exception below.
I believe this issue was introduced here: https://github.com/flutter/flutter/commit/7775c23784fdd7890a453031e0451fbed3731247#diff-2d74aabcc309c260810a6cca572e134eR1405

**Target Platform:** Android
**Devices:** Only tested on Emulator

## Logs
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building EditableText-[LabeledGlobalKey<EditableTextState>#16376](controller: TextEditingController#87504(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))), focusNode: FocusNode#cddaa, debugLabel: (englishLike subhead 2014).merge(blackMountainView subhead), inherit: false, color: Color(0xdd000000), family: Roboto, size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, textAlign: start, keyboardType: TextInputType(name: TextInputType.text, signed: null, decimal: null), dirty, dependencies: [MediaQuery, _FocusMarker, Directionality], state: EditableTextState#13845(tickers: tracking 2 tickers)):
Tried to make a child into a parent of itself.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 747 pos 12: 'child != this'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    TextField 
lib\…\widgets\login_form.dart:38
When the exception was thrown, this was the stack
#2      FocusNode._reparent 
package:flutter/…/widgets/focus_manager.dart:747
#3      FocusAttachment.reparent 
package:flutter/…/widgets/focus_manager.dart:125
#4      EditableTextState.build 
package:flutter/…/widgets/editable_text.dart:1822
#5      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4334
#6      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4223
...
════════════════════════════════════════════════════════════════════════════════
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale de-DE)
    • Flutter version 1.12.13+hotfix.6 at C:\SDKs\flutter
    • Framework revision 18cd7a3601 (3 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:\SDKs\android
    • Java binary at: D:\Programme\JDK\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\puelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
This is working as intended. Focus nodes can only be hosted by one widget at a time, so providing the same node to two different widgets isn't allowed.  Before the referenced change, it was incorrect, but not enforced. Now it is enforced via an assert.

What is the use case that you are trying to solve that the second code snippet (the one that works) will not address?

**Comment by KammererTob** [comment]
Thanks for the answer. That makes sense. 

**Use-case:** We have a very large form with multiple inputs on multiple rows. We want to support navigating between those inputs with a hardware keyboard (mainly "Tab" and "Shift-Tab"). I am not aware that this works out of the box and i tried to use the `RawKeyboardListener` on one input to catch the Tab/Shift-Tab presses to then navigate to the next Input (wrapped by another `RawKeyboardListener`). Catching the keys is no problem, but requesting focus on the other input is impossible while it is wrapped by a `RawKeyboardListener` (which it needs to be able to navigate further)

**Comment by gspencergoog** [comment]
Actually, with the current stable release keyboard traversal with TAB and shift-TAB should be working out of the box.  If you want a specific order for your traversal, you might need to implement a custom [`FocusTraversalPolicy`](https://api.flutter.dev/flutter/widgets/FocusTraversalPolicy-class.html), but by default it uses a "reading order" traversal that should work for most needs.

The code you have above should be entirely unnecessary.

**Comment by KammererTob** [comment]
I tested this on an Android Emulator and an actual device (IPad Pro + Apple Magic Keyboard). Here are my results:

Android-Emulator (might just the emulator not handling it correctly tho):
- Tab is working, but is adding a space character to the TextEdit
- Shift-Tab is not working

IPad Pro + Apple Magic Keyboard:
- Tab not working
- Shift-Tab not working

This is the code it was tested on:
```
return Form(
    child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
            TextFormField(
                focusNode: _emailFocusNode,
                decoration: InputDecoration(labelText: 'E-Mail', filled: true, fillColor: Colors.white),
                keyboardType: TextInputType.emailAddress,
                controller: _emailInputController,
                textInputAction: TextInputAction.next,
                onFieldSubmitted: (value) {
                    _passwordFocusNode.requestFocus();
                },
            ),
            TextFormField(
                focusNode: _passwordFocusNode,
                decoration: InputDecoration(labelText: 'Password', filled: true, fillColor: Colors.white),
                obscureText: true,
                controller: _passwordInputController,
                onFieldSubmitted: (value) {
                    _submitButtonFocusNode.requestFocus();
                },
            ),
            RaisedButton(
                focusNode: _submitButtonFocusNode,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5.0)),
                color: Theme.of(context).primaryColor,
                child: Text('Login', style: TextStyle(color: Colors.white)),
                onPressed: () => _loginBloc.dispatch(LoginButtonPressed(email: _emailInputController.text, password: _passwordInputController.text)),
            ),
            Container(
                child: state is LoginLoading ? CircularProgressIndicator() : null,
            )
        ],
    )
);
```

**Comment by gspencergoog** [comment]
On the iPad Pro, this is because Flutter doesn't have hardware keyboard support on iOS (iOS doesn't provide public APIs that make it possible).

And the emulator doesn't emulate a hardware keyboard, so it's expected not to work.  Try it on a physical device with a keyboard, and it should work.

**Comment by KammererTob** [comment]
Alright. Thanks for clearing this up. 
Is there a workaround to make this work on iOS devices? The RawKeyboardListener would probably still detect the presses, even for the hardware keyboard on iOS devices, right? So my "solution" provided above is one route (even if not the prettiest one).

**Comment by gspencergoog** [comment]
No, unfortunately, it's the engine that doesn't have any iOS keyboard support, so it won't even generate any raw keyboard events.  There's just not any public API in iOS that provides keyboard events.  iOS apps can register to know when editing events happen, but not to get events about key presses in general.  See this issue for more context: https://github.com/flutter/flutter/issues/31945

**Comment by KammererTob** [comment]
Alright. Thanks you for taking the time to answer. I will close this issue.

**Comment by clicks** [comment]
Although I can't be of help with the iOS problem, I want to share my findings when changing focus and listening to Keyboard events. As the FocusNode has an onKey callback on it's own, it is possible to detect special key presses (e.g. enter or tab) and move the focus afterwards:

```
FocusNode _fieldFocus;

void initState() {
  super.initState()
 
  _fieldFocus = FocusNode(onKey: (node, RawKeyEvent event) {
    if (event is RawKeyUpEvent) {
      if (event.logicalKey == LogicalKeyboardKey.enter) {
        //do whatever you have to do
        _changeFocus(context, _fieldFocus, _nextFieldFocus);
      }
      return true;
    }
  });
}

TextFormField() {
  focusNode: _fieldFocus
}
```

**Comment by radzish** [comment]
How can I handle ESC key on TextField? Use case: I am writing autocomplete for flutter web application. And I need to close autocomplete menu when user presses ESC while typing in TextField. How can I do that?
