### ISSUE TITLE
Deprecated API on build

### ISSUE THREAD

**Issue by durduliu2009** [flutter/flutter#48074]
Hello, 
Whent I'm building app this error appear. It don't affect my  app but I'm afraid that at some point my app won't start anymore because of this.

```
Note: /home/usermon/development/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+13/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
```

Many thanks in advance

**Comment by VladyslavBondarenko** [comment]
Hi @durduliu2009 
I see there's an issue addressing the case you described.
Please follow up on [this issue](https://github.com/flutter/flutter/issues/28155).

I can make a guess that [this fix](https://github.com/apptreesoftware/flutter_barcode_reader/issues/71#issuecomment-468160208) may resolve your problem, but to better address it more detailed info required.

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.

Thank you
