### ISSUE TITLE
iTune connect error - ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by guybashan** [flutter/flutter#48085]
I am getting the following error when trying to upload to iTunesConnect:

 
`ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

I am using the following plugins:
```
intl: 0.16.0
  flutter_bloc: ^0.20.1
  equatable: ^0.1.5
  meta: ^1.1.6
  shared_preferences: ^0.5.3+4
  percent_indicator: ^2.1.1+1
  flutter_launcher_icons: ^0.7.4
  scratcher: ^1.2.1
  flushbar: ^1.9.0
  uuid: ^2.0.2
  dart_random_choice: ^0.0.2
  flutter_local_notifications: ^0.9.1
```

**Comment by jonahwilliams** [comment]
It looks like you uploaded a debug build, this contains ptrace and shouldn't be uploaded to the app store.

Ensure that you've run `flutter build ios --release` and then performed the correct archive action in Xcode
