### ISSUE TITLE
showModalBottomSheet not working

### ISSUE THREAD

**Issue by omenejoseph** [flutter/flutter#48082]
## Steps to Reproduce
1. create new flutter application with flutter command
2. create basic material app setup
3. add button with onPressed function calling showModalBottomSheet
4. create basic widget for the modal
 main dart file : https://gist.github.com/omenejoseph/91c9c749d8e992f0d08bcbcb6dff2e29

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs
Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No MediaQuery widget found.

MyApp widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was: MyApp
The ownership chain for the affected widget is: "MyApp ← [root]"

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @omenejoseph 
I believe the problem might be that in your sample
the modal has the same context of the material app,
you may want to try this [solution](https://dartpad.dartlang.org/6fc2faeb99d5f379e0a0feece70b6b65)
does this solve the issue?
thank you

**Comment by TahaTesser** [comment]
Hi @omenejoseph 
Are you still experiencing this issue?
Thank you

**Comment by Gagan5278** [comment]
https://stackoverflow.com/questions/59864150/flutter-exception-caught-by-gesture-no-mediaquery-widget-found-inside-showmodal

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
