### ISSUE TITLE
enableInteractiveSelection:false for TextFormField not working in Flutter Web (tried Chrome)

### ISSUE THREAD

**Issue by simmi9** [flutter/flutter#48099]
This works in Flutter mobile(stable).

**Comment by iapicca** [comment]
Hi @simmi9  
it seems to work on web w/ touchscreen, [sample](https://dartpad.dartlang.org/9a80cd84dc55eda0ad5e6ab0c9250698)
I believe that what you mean is to enable mouse recognition,
am I correct?
thank you

**Comment by simmi9** [comment]
Yes! I was trying to disable copy and paste for flutter web login screen on my app and I had set enableInteractiveSelection: false according to flutter help results on various forums  , however it did not work for web version of my app.
Can you help?

**Comment by yjbanov** [comment]
Can you please explain in what way it does not work? Does it have no effect? Does it throw an exception? Does the app crash?

**Comment by yjbanov** [comment]
Please also provide a stack trace, and if possible, the source code of sample app that reproduces the behavior.

**Comment by simmi9** [comment]
Below is the code, you will find a red text box when you run it on web.
To recreate the issue 1) type something in the red text box.
                                  2) try to select the text you that you just typed using the mouse.
- You will be able to copy it using right click and paste it on the notepad , this only happens in the case of flutter web but not flutter mobile/ipad(android/ios)

- Notice that the textformfield property  enableInteractiveSelection is false, this should disallow the selection of text in the textformfield, which in turn avoids copy and paste especially password text form fields. This works in case of flutter mobile/ipad(ios/android) but not in flutter web.


import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: Container(
        color:Colors.redAccent,
        child:TextFormField(
        enableInteractiveSelection: false,
          
      ),)
    ),
  );
}

**Comment by rydmike** [comment]
## Additional findings

I just struggled with this issue on Windows and Web platform where I got very frustrated when `enableInteractiveSelection` was not doing what it supposed to do. I tried for a long time to figure out why. Finally I did an issue search and found this case. Sad to see that it has been reported already in January and is still open. In any case, I took note of some additional findings in hope to facilitate its eventual fix.

1. This issue where you **can still use text selection on Web** when `enableInteractiveSelection: false` is set applies to both `TextField` and `TextFormField`.

2. This issue also applies to platform `Windows`. This was tested with Channel dev, 1.24.0-6.0.pre 1.24.0-6.0.pre. (MacOS and Linux was not tested, but they should be tested for the issue as well.)

3. On Web if you also set `readOnly: true`, you **can still select text and copy it**, but you **cannot cut or delete** it.

4. On Windows if you also set  `readOnly: true`, you can still select text and copy it with (CTRL-C), you can **also delete it with (DEL)** and CUT it with (CTRL-X) for paste elsewhere. What kind of `readOnly` field allows that?

The above observed behavior is in no way consistent with what the properties document that they should do.

## Example code

The already provided code sample works well enough for verifying these issues. Here is a slightly modified version where you can easily also the `readOnly` property to study its impact on different platforms in combination with the `enableInteractiveSelection`.


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(20),
          child: TextFormField(
            initialValue: "Abcdefgh1234",
            enableInteractiveSelection: false,
            readOnly: false,
          ),
        ),
      ),
    );
  }
}
```

For Web you can just run the above sample in DartPad here:
https://www.dartpad.dev/c3a564c9348f325a526350aea32110bf

---

cc: @mariamhas
