### ISSUE TITLE
Hot reload doesn't update static methods used in other isolates

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#48091]
Steps to reproduce:

1. `flutter create hot_reload_isolate_test`
2. Replace the `hot_reload_isolate_test/lib/main.dart` file with the following:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Material(
        child: Builder(
          builder: (BuildContext context) => Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text('FROM SAME ISOLATE'),
                onPressed: () async {
                  await showMessage(context, _test(null));
                },
              ),
              RaisedButton(
                child: Text('FROM OTHER ISOLATE'),
                onPressed: () async {
                  await showMessage(context, await compute<void, String>(_test, null));
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

Future<void> showMessage(BuildContext context, String message) {
  return showDialog(
    context: context,
    builder: (BuildContext context) => AlertDialog(
      content: Text(message),
    ),
  );
}

String _test(void argument) {
  return 'Hello';
}
```
3. Go into the `hot_reload_isolate_test` directory and `flutter run`.
4. You should get an app with two buttons, both of which cause a dialog to appear saying "HELLO".
5. Edit the file above, changing `Hello` on the penultimate line to `Goodbye`.
6. Hot reload and push the buttons again.

Expected results: Both buttons should now say "Goodbye".

Actual results: the button that spawns a different isolate still says "Hello".

cc @bkonyi

**Comment by bkonyi** [comment]
@rmacnak-google seemed to have more context as to why this is happening.

**Comment by aam** [comment]
Quick answer is that flutter tools currently only reloads ui isolate: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L287.
