### ISSUE TITLE
Regression in smoke_catalina_hot_mode_dev_cycle_ios__benchmark

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#48096]
`hotReloadMillisecondsToFrame` regressed on https://github.com/flutter/flutter/commit/e768c92fbc6cf8bf4e1814ef950a6092bbb6f658. 

It would appear it regressed in https://github.com/flutter/flutter/commit/659dc8129d4edb9166e9a0d600439d135740933f but that PR was later reverted, and back to a green state. https://github.com/flutter/flutter/commit/e768c92fbc6cf8bf4e1814ef950a6092bbb6f658 re-introduced the regression. 

@Hixie  @dnfield

**Comment by Hixie** [comment]
I would start by rebooting the bot, see if that helps. If that doesn't help, it could be some of the new dependencies, or maybe something about the compiler being sensitive to some of the minor changes made in that PR.

**Comment by DaveShuckerow** [comment]
This is blocking a g3 roll.

**Comment by franciscojma86** [comment]
The bot is having issues. @keyonghan were investigating and found a potential bug in the agent's code.    Will update once we find more info.

**Comment by franciscojma86** [comment]
Benchmark is back to green
