### ISSUE TITLE
 syntax error near unexpected token

### ISSUE THREAD

**Issue by JiLiren** [flutter/flutter#48106]
![image](https://user-images.githubusercontent.com/19288651/71705769-8fcc2b00-2e13-11ea-9973-3b15bb050f64.png)
![image](https://user-images.githubusercontent.com/19288651/71705780-96f33900-2e13-11ea-867f-2a440f172142.png)

**Comment by iapicca** [comment]
Hi @JiLiren  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by jmagman** [comment]
This may be a flutter setup issue.  What's the output of:
```
$ cd /Users/ak/company/flutter/flutter
$ git status
```
Also need `flutter doctor -v`

**Comment by JiLiren** [comment]
Flutter (Channel dev, v1.13.6, on Mac OS X 10.14.6 18G2022, locale
    zh-Hans-KH)


Launching lib/main.dart on iPhone (3） in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 268255YMV4
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...
Xcode build done.                                            5.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
: command not found
'
'
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on iPhone (3）.

**Comment by JiLiren** [comment]
It can be used normally a month ago, I found this problem yesterday, I tried various versions of flutter and the results are the same

**Comment by JiLiren** [comment]
![image](https://user-images.githubusercontent.com/19288651/71762196-6a1c5000-2eff-11ea-88bc-98aec060b28e.png)
I can run it normally on my Android phone

**Comment by iapicca** [comment]
Hi @JiLiren 
does this possible [solution ](https://github.com/flutter/flutter/issues/25411#issuecomment-447578096) fix the issue?

Please refrain from posting pictures if not necessary.

Thank you

**Comment by JiLiren** [comment]
no

**Comment by jmagman** [comment]
> This may be a flutter setup issue. What's the output of:
> 
> ```
> $ cd /Users/ak/company/flutter/flutter
> $ git status
> ```

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
