### ISSUE TITLE
How to publish Flutter apps made for Android TV on PlayStore

### ISSUE THREAD

**Issue by pharshdev** [flutter/flutter#48109]
**Note**: I already know TV isn't supported by Flutter, but I highly feel this issue could be solved using a simple workaround which I'm not aware of yet.

So, I have developed an Android TV app using Flutter and it works as expected. The problem is in publishing the app to Playstore.

I have already made the changes to AndroidManifest as stated in Android docs for TV apps but still when the app is published on playstore, it says "This app is incompatible with all of your devices." including my AndroidTV and AndroidTV emulator.

Here's my AndroidManifest: 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="me.premiumize.pmtvfire">

    <uses-permission android:name="android.permission.INTERNET" /> 
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-feature android:name="android.software.leanback"
        android:required="true" />
    <uses-feature android:name="android.hardware.touchscreen"
              android:required="false" />

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="xyz "
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="android.intent.category.LEANBACK_LAUNCHER"/>
            </intent-filter>
        </activity>
        <provider
            android:name="sk.fourq.otaupdate.OtaUpdateFileProvider"
            android:authorities="${applicationId}.ota_update_provider"
            android:exported="false"
            android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/filepaths" />
</provider>
    </application>
</manifest>`

Any help appreciated, thanks!

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/13749
https://github.com/flutter/flutter/issues/13633
https://github.com/flutter/flutter/issues/26947
https://stackoverflow.com/questions/47844928/how-to-let-flutter-apps-support-tv-device

**Comment by pharshdev** [comment]
> #13749
> #13633
> #26947
> https://stackoverflow.com/questions/47844928/how-to-let-flutter-apps-support-tv-device

@iapicca Why link me to Focus and touch operation issues/solution? 

I think I clearly mentioned that the app "works as expected" and the issue is on publishing the app to PlayStore where it says app is incompatible even though it works alright when sideloaded.

**Comment by kf6gpe** [comment]
I don't know if we have a placeholder bug for Android TV support, but I'm imagining that to fully support @pharshdev we'd want some changes on both the framework and tooling side. The specific problem they're running into strikes me as tooling, but I don't think I understand the details.

**Comment by pharshdev** [comment]
We have already successfully published the Flutter TV app on Playstore. We just needed to move `<category android:name="android.intent.category.LEANBACK_LAUNCHER"/>` above `<category android:name="android.intent.category.LAUNCHER"/>`.  Thanks anyways.

**Comment by khalilahmad0** [comment]
Hey! Can I have your email? I am building a tv app using flutter and I might need some help

**Comment by pbertsch** [comment]
@pharshdev could you provide the name of your Application ?

**Comment by pharshdev** [comment]
@pbertsch here you go https://play.google.com/store/apps/details?id=me.premiumize.pmtvplay
