### ISSUE TITLE
module 'path_provider' not found

### ISSUE THREAD

**Issue by rainmeterLotus** [flutter/flutter#48103]
`
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           12.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/wangdexin/apus/flutterSpace/tangerine_read/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'path_provider' not found
    @import path_provider;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
`
someone help??

**Comment by rainmeterLotus** [comment]
I don't know waht i did,but i solve it
i did things:
1.on android studio ,at ios catalog run :pod install 
`
rainmeterLotus@apusdeMacBook-Pro ios % pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 9 dependencies from the Podfile and 10 total pods installed.

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
`
and then I solve the 2 warning,then open xcode

**Comment by yxwandroid** [comment]
Same problem  
module 'path_provider' not found    
After executing pod  Install, it still won't work

![image](https://user-images.githubusercontent.com/9635493/94540794-77415200-0279-11eb-8669-1d35479fe83a.png)
![image](https://user-images.githubusercontent.com/9635493/94540860-8a542200-0279-11eb-96e9-e5f539777707.png)

**Comment by hamzadevc** [comment]
Yes, definitely Runner.xcworkspace instead of Runner.xcodeproj

**Comment by shalom-aviv** [comment]
Have same issue!
Run only  **Runner.xcworkspace**

**Comment by chorchannaseang** [comment]
Launching lib/main.dart on iPod touch (7th generation) in debug mode...
Running Xcode build...
Xcode build done.                                           14.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/kingman/Desktop/HLH/express-mobile-v2/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'path_provider' not found
    @import path_provider;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPod touch (7th generation).
