### ISSUE TITLE
When looking for a pubpec.yaml, tool should also look up the filesystem

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#48117]
```
Error: No pubspec.yaml file found.
```
This message should not be needed if you're running the tool from the `lib` directory, or some other subdirectory of the Flutter project. We should just notice that there's a `pubspec.yaml` in a parent directory, and silently use that directory as the working directory.

**Comment by jonahwilliams** [comment]
Is there a reasonable limit to how far we should walk? I suppose it is probably not common to have files named pubspec.yaml hanging around that don't have anything to do with dart/flutter.
