### ISSUE TITLE
TextPainter always draws white text in release or profile mode

### ISSUE THREAD

**Issue by johrpan** [flutter/flutter#48114]
This was an issue with the Flame game engine originally (see flame-engine/flame#154). I made the following example using just flutter and the issue still persists. The text gets drawn as expected (blue) in debug mode, but appears in white in profile and release mode. I don't get any warnings or errors from `flutter run --verbose --release` and `flutter doctor` isn't reporting any issues. I tested it on two different Android devices.

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class Painter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final textPainter = TextPainter(
      text: TextSpan(
        style: TextStyle(
          color: Colors.blue,
          fontSize: 24.0,
        ),
        text: 'Testus',
      ),
      textDirection: TextDirection.ltr,
    );

    textPainter.layout();

    canvas.drawRect(Rect.fromLTWH(0.0, 0.0, size.width, size.height),
        Paint()..color = Colors.orange);
    textPainter.paint(canvas, Offset(64.0, 64.0));
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomPaint(
      foregroundPainter: Painter(),
    );
  }
}

```

**Comment by johrpan** [comment]
After a lot of debugging I found out, that the problem doesn't occur when not specifying a `fontSize`. I used the following for the `paint` method:

```dart
@override
void paint(Canvas canvas, Size size) {
  canvas.drawRect(Rect.fromLTWH(0.0, 0.0, size.width, size.height),
      Paint()..color = Colors.orange);

  final textStyleWithSize = TextStyle(
    color: Colors.black,
    fontSize: 24.0,
  );

  final textStyleWithoutSize = TextStyle(
    color: Colors.black,
  );

  final uiTextStyleWithSize = textStyleWithSize.getTextStyle();
  final uiTextStyleWithoutSize = textStyleWithoutSize.getTextStyle();

  final spanWithSize = TextSpan(
    style: textStyleWithSize,
    text: 'With size',
  );

  final spanWithoutSize = TextSpan(
    style: textStyleWithoutSize,
    text: 'Without size',
  );

  final textPainterWithSize = TextPainter(
    text: spanWithSize,
    textDirection: TextDirection.ltr,
  );

  final textPainterWithoutSize = TextPainter(
    text: spanWithoutSize,
    textDirection:  TextDirection.ltr,
  );

  textPainterWithSize.layout();
  textPainterWithoutSize.layout();

  textPainterWithSize.paint(canvas, Offset(64.0, 64.0));
  textPainterWithoutSize.paint(canvas, Offset(64.0, 128.0));
}
```

Other fields like `decorationStyle` and `decorationColor` have the same effect on the output color. I think the encoding to an `Int32List` in the `dart:ui` class that is also called `TextStyle` might be flawed somehow (See `uiTextStyleWithSize` and `uiTextStyleWithoutSize`).

**Comment by johrpan** [comment]
Ok, the encoding seems to be correct. I used this code to verify (with a copied version of the encoding methd)

```dart
final empty = encodeTextStyle();
final withSize = encodeTextStyle(
  color: Colors.black,
  fontSize: 24.0,
);
final withoutSize = encodeTextStyle(
  color: Colors.black,
);

print('Bits:');
print('empty:       ${empty[0].toRadixString(2)}');
print('withSize:    ${withSize[0].toRadixString(2)}');
print('withoutSize: ${withoutSize[0].toRadixString(2)}');

print('Colors:');
print('empty:       ${empty[1].toRadixString(16)}');
print('withSize:    ${withSize[1].toUnsigned(32).toRadixString(16)}');
print('withoutSize: ${withoutSize[1].toUnsigned(32).toRadixString(16)}');
```

and it correctly prints

```
I/flutter (22585): Bits:
I/flutter (22585): empty:       0
I/flutter (22585): withSize:    10000000010
I/flutter (22585): withoutSize: 10
I/flutter (22585): Colors:
I/flutter (22585): empty:       0
I/flutter (22585): withSize:    ff000000
I/flutter (22585): withoutSize: ff000000
```

both in debug and release mode. So the error must be somewhere on the C++ side. Unfortunately I don't have a clue on how to get along there.

**Comment by iapicca** [comment]
Hi @johrpan 
can you please provide your `flutter doctor -v` ?
thank you

**Comment by johrpan** [comment]
```
 ~ ‣ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/johrpan/.flutterSdk
    • Framework revision 27321ebbad (vor 4 Wochen), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/johrpan/.androidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/johrpan/.androidSdk
    • Java binary at: /home/johrpan/.android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/johrpan/.android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by vanduong185** [comment]
I have the same problem.
In release mode, color of TextSpan works correctly when I use the following code:
```
TextPainter(
  text: TextSpan(
    style: TextStyle(
      color: Colors.blue,
    ),
    text: 'Testus',
  ),
  textDirection: TextDirection.ltr,
);
```

but when add `fontSize` property to `TextStyle`, the text color is white.
```
TextPainter(
  text: TextSpan(
    style: TextStyle(
      color: Colors.blue,
      fontSize: 24.0,        // add fontSize
    ),
    text: 'Testus',
  ),
  textDirection: TextDirection.ltr,
);
```
Thank you for your help.

**Comment by jason-simmons** [comment]
This is a Dart AOT code generation bug.  It appears to have started with these changes from several months ago:
    https://github.com/dart-lang/sdk/commit/8e4dcf48c4bb64beaf930b3f85f6e4d01b570203
    https://github.com/dart-lang/sdk/commit/dbfd00f44daf67e5f42f4d297d77be3237b8a35d

@mkustermann

**Comment by mkustermann** [comment]
Thanks for reporting the bug. We'll take a look.

**Comment by mkustermann** [comment]
Here's a standalone reproduction:
```dart
import 'dart:typed_data';

main() {
  print(foo(A(), A())[0]);
}

@pragma('vm:never-inline')
Int32List foo(A a, A b) {
  final result = Int32List(8);
  if (a != null) {
    result[0] |= 1 << 0;
    result[1] = a.value;
  }
  if (b != null) {
    result[0] |= 1 << 1;
  }
  return result;
}

class A { 
  final int value = int.parse('1');
}
```
```
% dart test.dart
3
% dart2native test.dart && ./test.exe
2
```
It seems to be a bug in our CSE pass.

**Comment by mkustermann** [comment]
The issue has been fixed and should be picked up by next rolls to flutter/engine, flutter/flutter and users.

**Comment by Karthikputchala** [comment]
In Flutter's TextPainter text color differs in debug and release.

In this Flutter project while running in the emulator and the test device the text color in shown in black but after converting the project in to an apk file then text is shown in white color. I do not understand what is wrong with the TextPainter ?

import 'package:flutter/material.dart';
import 'package:project/game_controller.dart';

class HighscoreText {
  final GameController gameController;
  TextPainter painter;
  Offset position;

  HighscoreText(this.gameController) {
    painter = TextPainter(
      textAlign: TextAlign.center,
      textDirection: TextDirection.ltr,
    );
    position = Offset.zero;
  }

  void render(Canvas c) {
    painter.paint(c, position);
  }

  void update(double t) {
    int highscore = gameController.storage.getInt('HighScore') ?? 0;
    painter.text = TextSpan(
      text: 'Highscore: $highscore',
      style: TextStyle(
          color: Colors.black, fontSize: 35.0, fontWeight: FontWeight.w500),
    );
    painter.layout();
    position = Offset(
        (gameController.screenSize.width / 2) - (painter.width / 2),
        (gameController.screenSize.height * 0.2) - (painter.height / 2));
  }
}

**Comment by mkustermann** [comment]
This particular issue was due to a bug in our AOT compiler. The bug has been fixed and rolled out. So it's very unlikely the same issue.

@Karthikputchala Would you mind filing a new issue at ?

(Also: For us to diagnose the issue we would probably need to be able to reproduce it: Is it possible for you to make a small app which reproduces it?)

**Comment by Karthikputchala** [comment]
But still I am getting this issue. Can you please suggest me what to do, to get rid of this issue and is there any similar thing like TextSpan so that I can use it.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
