### ISSUE TITLE
"Do not run this command from the root of your git clone of Flutter" shown when that's not what's happening

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#48116]
We shouldn't show the "Do not run this command from the root of your git clone of Flutter" message when you're nowhere near that directory, for example when you're in the `lib` directory of a real Flutter project, or at the root of your filesystem, or whatever.

Currently we show it anytime we can't find a `pubspec.yaml`, which is confusing. We can easily tell if you're in the root of a Flutter repo, so we should check that before showing this message.

**Comment by jonahwilliams** [comment]
We should just fix that error message.
