### ISSUE TITLE
Exception caught by gesture 

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [flutter/flutter#48124]
1. The following assertion was thrown while handling a gesture:
`type 'int' is not a subtype of type 'String' of 'other'`
2. 
 ```
ListTile(
  title: Text(S.of(context).share, textAlign: TextAlign.center),
  onTap: () {
    Navigator.of(context).pop();
    final RenderBox box = context.findRenderObject();
    Share.share(product.name,
        sharePositionOrigin:
        box.localToGlobal(Offset.zero) &
        box.size);
  }
);
```

**Comment by VladyslavBondarenko** [comment]
Hi @bhallaramdhatarwal 
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app code to reproduce it.

I tried to run your code 
<details>
 <summary>this way</summary>

```
import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHome(),
    );
  }
}

class MyHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        Card(
          child: ListTile(
              title: Text('name', textAlign: TextAlign.center),
              onTap: () {
                Navigator.pop(context);
                final RenderBox box = context.findRenderObject();
                Share.share('name',
                    sharePositionOrigin:
                    box.localToGlobal(Offset.zero) &
                    box.size);
              }
          ),
        ),
      ],
    );
  }
}
```

</details>

But I don't know what are yours `product.name` and `S.of(context).share`
Is problem there?

Thank you

**Comment by bhallaramdhatarwal** [comment]
@VladyslavBondarenko 

product.name just a string type parameter, and S.of(context).share is just local string values is share nothing else

**Comment by VladyslavBondarenko** [comment]
@bhallaramdhatarwal 
Can you modify my code sample in such way to reproduce the exception?
Thank you

**Comment by bhallaramdhatarwal** [comment]
@VladyslavBondarenko No, not really but I solve using same code and clean flutter and clean system cache 

Thank you
