### ISSUE TITLE
flutter build ios flutter embed ios project

### ISSUE THREAD

**Issue by LikeeCat** [flutter/flutter#48121]
I embedded flutter into the iOS project. Before publishing, I used flutter build ios, something is error,what should  i do. it needn't to run flutter build ios ?

It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.

**Comment by dnfield** [comment]
You should not _need_ to run `flutter build ios` successfully to add Flutter to an existing app - although it's one way to help boostrap the generation of certain files.

It seems likely that you just don't have the default signing identifier - you should try opening `.ios/Runner.xcworkspace` and seeing if you can run that after setting the identifier in Xcode.

/cc @jmagman in case I'm missing something here.

**Comment by jmagman** [comment]
Nope, shouldn't need to run `flutter build ios` in the module for add-to-app.  Once your Flutter module is embedded, you can publish the host app as you would any other iOS app:
https://developer.apple.com/app-store/submissions/
