### ISSUE TITLE
Couldn't find meta-data for provider (MethodChannel)

### ISSUE THREAD

**Issue by Savyoo** [flutter/flutter#48125]
## Steps to Reproduce

1. ... Followed the attached tutorial for packages and created a basic application for showing basic Qr data and sharing it

.
<a href="https://medium.com/flutter-community/building-flutter-qr-code-generator-scanner-and-sharing-app-703e73b228d3">Meduim tutorial</a>
2. ... Used kotlin code from the stack suggestions
<a href="https://stackoverflow.com/questions/44181343/how-do-i-share-an-image-on-ios-and-android-using-flutter">StackOverflow</a>
3. ...Getting the error: 
E/flutter (10479): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Couldn't find meta-data for provider with authority me.shopqr.share, null)

Please refer the attached files

**Target Platform:**  Andriod 10/Pie
**Devices:** Emulator as well as Device

## Files
<b>qr.dart</b>
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:flutter/services.dart';
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui';
import 'dart:io';
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';

class DisplayQR extends StatelessWidget {
  GlobalKey globalKey = new GlobalKey();
  Future<void> _captureAndSharePng() async {
    print("clicked");
    try {
      RenderRepaintBoundary boundary =
          globalKey.currentContext.findRenderObject();
      var image = await boundary.toImage();
      ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
      Uint8List pngBytes = byteData.buffer.asUint8List();
      final tempDir = await getTemporaryDirectory();
      final file = await new File('${tempDir.path}/image.png').create();
      await file.writeAsBytes(pngBytes);
      final channel =
          const MethodChannel('channel:me.shopqr.share/share');
      channel.invokeMethod('shareFile', 'image.png');
    } catch (e) {
      print(e.toString());
    }
  }

  List<String> shopDataObj = List<String>();
  DisplayQR(this.shopDataObj);
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          RepaintBoundary(
            key: globalKey,
            child: QrImage(
              data: shopDataObj.elementAt(1),
              version: QrVersions.auto,
              size: 200.0,
            ),
          ),
          Text(
            shopDataObj.elementAt(0),
            style: TextStyle(
              fontSize: 25,
            ),
          ),
          IconButton(
            icon: Icon(Icons.share),
            onPressed: () => {
              _captureAndSharePng(),
            },
          ),
        ],
      ),
    );
  }
}

<hr>

<b>android\app\src\main\kotlin\com\example\shop\MainActivity.kt</b>
package com.example.shop

import android.content.Intent
import android.os.Bundle
import androidx.core.content.FileProvider

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugin.common.MethodChannel
import java.io.File

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)

    MethodChannel(flutterView,"channel:me.shopqr.share/share").setMethodCallHandler { methodCall, _ ->
      if (methodCall.method == "shareFile") {
        shareFile(methodCall.arguments as String)
      }
    }
  }

  private fun shareFile(path:String) {
    val imageFile = File(this.applicationContext.cacheDir,path)
    val contentUri = FileProvider.getUriForFile(this,"me.shopqr.share",imageFile)

    val shareIntent = Intent()
    shareIntent.action = Intent.ACTION_SEND
    shareIntent.type="image/jpg"
    shareIntent.putExtra(Intent.EXTRA_STREAM, contentUri)
    startActivity(Intent.createChooser(shareIntent,"Compartir usando"))
  }
}

```
```

```
```

```
```

**Comment by Savyoo** [comment]
Solved the issue by updating the manifest file

**Comment by valerybodak** [comment]
@Savyoo 
Could you please clarify, what did you modify in AndroidManifest file?

**Comment by Savyoo** [comment]
> @Savyoo
> Could you please clarify, what did you modify in AndroidManifest file?

@valerybodak  If you follow the Stackoverflow link that I provided in the question you'll find the complete solution. You also need to create a new file in res/xml directory for it to work.

This is what you need to write:

**AndroidManifest.xml**

```
<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="me.albie.share"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths" />
</provider>
```

**xml/file_paths.xml**

```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <cache-path name="images" path="/"/>
</paths>
```

**Comment by Onus31** [comment]
i used this provider bus same issue again:
<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="me.albie.share"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths" />
</provider>
