### ISSUE TITLE
Make the ListTile tileWidth != leadingSize.width error assertion more informative

### ISSUE THREAD

**Issue by micimize** [flutter/flutter#48134]
I encountered the same as in #37451, and #46048, but am specifically requesting we prevent the assertion from crashing the application. I think this behavior is internally inconsistent, as it is best compared to an overflow issue like in `Column` or `Row`, and should at most render the overflow warning. 

My understanding of the scenarios where this error occurs:
* widget mounts while screen is off - mentioned in #37451
* widget mounts while parent is collapsed  and/or hidden (my use case, https://github.com/flutter/flutter/issues/46048#issuecomment-570399892)

doctor info - would be surprised if it was non-universal though:
```
Flutter 1.12.12 • channel master • https://github.com/flutter/flutter.git
Framework • revision bae92c32e5 (6 weeks ago) • 2019-11-24 22:29:28 -0800
Engine • revision b6b54fd606
Tools • Dart 2.7.0
```

**Comment by dnfield** [comment]
To clarify - assertion errors do not cause crashes by themselves, and they are stripped out of release mode.  This is indicating that there is some bug in the framework or in user code.  Removing assertions can be valid, but I suspect this assertion is correct and we are arriving at it at some time where we should be short circuiting earlier (e.g., I'm not clear why we're building the tree while the screen is off, or even what that really means).

**Comment by micimize** [comment]
@dnfield That last part is a debugging-specific scenario (https://github.com/flutter/flutter/issues/37451#issuecomment-560571213):
> on a "SM G973U1" and "SM N950U" physical device if the app is launched while the screen is in screen lock or if the screen is off.

Maybe that is a more general problem or maybe it is not an issue any longer (@jpeiffer?)

Investigating a bit more, the assertion was added in #30212 because of issues with unconstrained widgets (https://github.com/flutter/flutter/issues/17666#issuecomment-396747830).

I encountered it crashing (on launch in dev mode) because the `ListTile` was rendered initially with `< leadingSize.width` because it gets expanded into existence, which makes me think the assertion is too narrow. So maybe applying a `maxWidth` instead of a fixed size would satisfy all the constraints.

But, I've already moved away from using `ListTile` at this point, so I'm not really invested enough to go try that out atm, and don't really personally mind if this is closed 😅

**Comment by MichealReed** [comment]
@dnfield I am running into this. To provide a use case, I have a background screen that primarily drives interaction. I have created panels in the foreground that can be hidden. These need to continue to build and maintain state even though they are not visible.

**Comment by dnfield** [comment]
@MichealReed it would help if you provided a failing test case

**Comment by MichealReed** [comment]
@dnfield this will cause it:             

> Container(width:1, height: 1, child: ListTile(leading: Icon(Icons.speaker_notes))),

**Comment by dnfield** [comment]
@HansMuller @shihaohong

**Comment by shihaohong** [comment]
@MichaelRFairhurst Could you explain how you are creating the hidden panels or some more details on your use case? If you're simply hiding the ListTile by making its surrounding Container really small, there are other ways to do so without compromising the size of the widget. For example, using the Visibility widget:
```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({this.title});

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool isVisible = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Visibility(
              maintainSize: true,
              maintainAnimation: true,
              maintainState: true,
              visible: isVisible,
              child: ListTile(
                leading: Icon(Icons.speaker_notes),
                title: Text('tile widget'),
              ),
            ),
            RaisedButton(
              onPressed: () {
                setState(() {
                  isVisible = !isVisible;
                });
              },
              child: Text('Button'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by MichealReed** [comment]
Much better approach, thanks @shihaohong!

**Comment by dnfield** [comment]
Perhaps we should update the assert message on ListTile.

**Comment by MichealReed** [comment]
ListTile seems to be the only widget throwing this error, and it has already been stripped from release. Is the assert necessary at all?

**Comment by dnfield** [comment]
The assert indicates a programming error.  But it seems like it could make the error clearer (like, don't build the widget if it won't fit, or use a visibility widget around it, or something to that effect).

**Comment by micimize** [comment]
@dnfield but is there anything that's actually wrong with those usages? It looks to me like a well-intentioned attempt at library-level training wheels, which I think should be constrained to overflow indicator renders.

**Comment by shihaohong** [comment]
I guess there isn't anything "wrong" with the usage, but since ListTile was designed using a spec with [this use case in mind](https://material.io/components/lists/#specs), having the widget attempt to lay out in a smaller space could result in strange results (which was why the assert was added). 

The widgets are designed to be flexible and break out of the spec in ways that make sense, like using any widget you'd like in the leading/trailing widget instead of the sizes suggested in the spec. However, designing the widget to be flexible also makes it prone to the error seen in the original issue (and hence, the assert).

Adding overflow indicator renders might not be possible (or very difficult) because of the way ListTile has been designed. If we would like to make it "extremely flexible", then ListTile becomes no different than a Row with multiple children in it (which will then have overflow indicator renders once it exceeds its parent's constraints), in which case would be a new custom widget.

**Comment by micimize** [comment]
@shihaohong those are good points. Given that `ListTile` can be thought of as a convenience widget, linking to a guide/docs on how to "eject" from it to something custom might make more sense than making it more flexible.

**Comment by shihaohong** [comment]
That's actually precisely what I've done recently in [the ListTile API docs](https://api.flutter.dev/flutter/material/ListTile-class.html) under "The ListTile layout isn't exactly what I want." :) 

If there's any feedback or recommendations for that, I'm all ears since it is very common that a ListTile issue comes up (ie. "ListTile cannot lay out how I want it to") and in the end, building out a custom widget would have made more sense.

**Comment by micimize** [comment]
@shihaohong these are perfect! I think as long as spec-adherence assertions link to that section on error it'll be more than enough.

**Comment by shinewanna** [comment]
In my case, this is ListTile's leading problem.
Set fixed size on your leading widget.
`ListTile(leading:Container(width:60,height:60,child:yourWidget);`

**Comment by alanmfb** [comment]
I found that my problem was with the CircularProgressIndicator widget and not with the main widget. I changed the "Center" widget to a "Container (height: 20, width: 20) and it worked.
