### ISSUE TITLE
Allow RenderObjects to read the size/position of a "deep" descendant

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#48132]
Currently, RenderObjects can read the size of only their direct children.

It is not possible for a RenderObject to implement a `performLayout` that  depends on the size/position of a specific descendant _that is not a direct child_.

I'd like this to be supported (and is willing to code it myself)

## Motivation

There are two main features that I have in mind with this feature (and managed to implement, modulo manually disabling the RenderBox.size asserts):

- "Portals", a declarative way to manipulate Overlays.
  TD;DR, OverlayEntry becomes a Widget (and we have an equivalent for Overlay).

  It'd be typically used this way:
  ```dart
  Portal(
    child: SomeWidgets(
      child: PortalEntry(
        // the result of `portalBuilder` is inserted as a child of `Portal` _synchronously_.
        portalBuilder: (BuildContext context, Size portalSize, Size childSize, Offset childOffset) {
           // portalSize is the Size of the `Portal` widget
           // childSize is the size of the `child` widget (here Text)
           // childOffset is the Offset of `child` within `Portal` (so 0,0 if child is topLeft aligned)

         return MyOverlay();
        },
        child: Text('child of SomeWidget'),
      ),
    ),
  ),
  ```

 The combination of `portalSize`+ `childSize`+ `childOffset` allows aligning the overlay around the `child`.
  And if these values were to update (like if the Text is draggable), `portalBuilder` is called again with the new values. 

  I've already got this to _work_ (modulo implementing this feature request myself).

- Local "hero" animations

  Now that we have a synchronous declarative way to manipulate overlays like described before, it becomes possible to have a `Hero` implementation that works _within_ a Route, instead of only on `Navigator.push/pop`

## Problems

From my understanding, there are two things blocking this feature _today_:

- `RenderBox.size` has a bunch of asserts, one of which prevents other `RenderObjects` to read the `size` of their indirect descendants. It needs to be somehow disabled
- The parent `RenderBox` that depends on a _deep_ descendant for its layout needs to be kept in sync with layouts updates of that descendant.

## Proposed solution

IMO the most logical thing to do is to _bind_ the parent to the desired descendant, such that calling `markNeedsLayout` on the descendant calls it on the parent too.

For this, I'd go for a `void bindLayout(RenderObject)` method, that store the RenderObject in a set, such that it'd be used this way:

```dart
RenderBox someDeepDescendant;
RenderBox anotherBranch;

@override
void performLayout() {
  someDeepDescendant.bindLayout(this);
  
  size = constraints.biggest;
  anotherBranch.layout(BoxConstraints.tight(someDeepDescendant.size));
}
```

Then, on `detach` of `this`, it'd be automatically unbound from `someDeepDescandant`.

**NOTE:** 
To ensure that people don't bind two `RenderObjects` that are on two different branch, the `bind` method should have an assert that checks that the parameter is one of its ancestors.

From there, the assert on `RenderBox.size` could be updated to _not_ throw if `RenderObject.debugActiveLayout` is bound this box.
This would allow preserving the assert instead of having to remove it.

**Comment by dnfield** [comment]
The reason we make it difficult to access child data is that it is frequently something that would at best slow down and at worst completely break our layout algorithm(s).

What happens when that deep descendent decides it's sized by the parent?  What happens when an intermediate widget introduces new constraints that impact the size of the deep descendent? Why do we need to know the size of a widget to acheive animations within a route?

**Comment by rrousselGit** [comment]
> What happens when that deep descendent decides it's sized by the parent? What happens when an intermediate widget introduces new constraints that impact the size of the deep descendent? Why do we need to know the size of a widget to acheive animations within a route?

This doesn't remove the "a descendant can't read an ancestor's `size`" limitation.
So in all the described situations, there's no issue, as far as I'm aware.

The parent pass down constraints, and descendants send up their size. The behavior doesn't change. It's just extended to work where `child` is not the direct descendant.

**Comment by dnfield** [comment]
Parents pass down their constraints during layout.

Size is determined after layout.

You're trying to read the size before layout has finished.

**Comment by rrousselGit** [comment]
That's no different from the current behavior:

```dart
RenderBox someDescendant;
RenderBox anotherBranch;

@override
void performLayout() {
  someDescendant.layout(constraints, parentUseSize: true);
  
  size = someDescendant.size;
  anotherBranch.layout(BoxConstraints.tight(someDescendant.size));
}
```

**Comment by dnfield** [comment]
But why are you giving `someDescendant` the constraints of a remote ancestor?  What if some other intermediate descendant would have modified those constraints?

**Comment by rrousselGit** [comment]
There are many use-case, like tooltips or contextual menus.

They are overlays, but are aligned around a specific widget. 
So the Overlay needs to know the size and location of that widget.

It's not a problem if another widget in between modified the final size/position.

**Comment by rrousselGit** [comment]
Similarly, "local hero animations" is a very requested feature. But due to that missing feature, it's currently very difficult to implement.

It is currently **impossible** to _synchronously_ add an OverlayEntry, especially if it depends on the size of another widget.

This leads to multiple workarounds with the current `Hero` implementation (like this line: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/heroes.dart#L802)

And makes local heroes impossibles for the same reason (as delaying the rendering by a frame for local heroes leads to an ugly flash).

**Comment by dnfield** [comment]
Is your end goal here to just support animations from one render object to another?

**Comment by goderbauer** [comment]
I don't really understand why you'd want to access the size of a deep descendant. Can you give more details around what the Portal widget is supposed to do? And what kind of Hero animations that would enable that you currently can't do? In other words: Can you describe what you want to do without focusing on the mechanism to get there?

**Comment by Hixie** [comment]
This should definitely not be in the core framework, because it's very expensive (that's why the core framework doesn't have it). But it should be relatively straight-forward to make a new RenderObject descendant that does this. You'd need to set up logic similar to how RenderBox handles intrinsics and baselines.

**Comment by rrousselGit** [comment]
<example WIP, I'll post it in a few minutes  — just anwering Hixie first>

> This should definitely not be in the core framework, because it's very expensive (that's why the core framework doesn't have it). But it should be relatively straight-forward to make a new RenderObject descendant that does this. You'd need to set up logic similar to how RenderBox handles intrinsics and baselines.

I don't mind it leaving in a package, and it's not a suggestion to include these widgets in Flutter.
It's about simply _enabling_ packages to makes such thing.

I'm not an expect on RenderObjects, so I can have missed something. But I don't think the "problems" I listed can be solved as a package.

For example, to obtain the position of the deep descendant, I called `descendant.getTransformTo(parent)`.

But this is impossible to call such method inside `performLayout` without disabling some asserts on `RenderObject.size`.

**Comment by Hixie** [comment]
You wouldn't use RenderBox. RenderBox isn't set up to do this. You'd have to create a new RenderObject subclass that knows how to propagate the dirty state when the size of a descendant might change. This is very similar to the logic that RenderBox has for baseline and, especially, intrinsics. With intrinsics, in particular, when the parent asks for the intrinsic size, we keep track of that and if the size would change, we go and mark the parent as needing layout. You would need to implement that same logic, but with some mechanism to support going multiple levels. You'd also need a mechanism to handle ancestors or descendants being removed from the tree, or moved to another place in the tree, without leaving broken links everywhere, and so on.

It's a lot of work, but it's all possible to do today.

**Comment by rrousselGit** [comment]
> Portal widget is supposed to do

Replace `Overlay` entirely, with have a declarative API instead of an imperative API.
That's it, but it's a huge simplification of how to make overlays.

It's named "portal" because that's an existing feature built-in React: https://reactjs.org/docs/portals.html

Its main purpose being, it's an enabler for more feature like local heros or a contextual menu that doesn't block clicks.

Here's an example: 

![ezgif com-resize](https://user-images.githubusercontent.com/20165741/71748678-97bbb780-2e73-11ea-8bd8-3ca3f35ee030.gif)

Where the blue rectangle is supposed to be an overlay, and the white rectangle is a content that moves (typically inside a ListView).

Note that the blue card is top-left aligned with the white one. 

Such thing is very difficult and hacky to do right now. We need to use an imperative API, and fight against the widgets/renderobjects layer using post frame callback.

This leads to the effect we see on this gif, where the alignment isn't perfect, because it's delayed by a frame. So if the white card moves fast, the blue card becomes misaligned temporarily.

With portals, such thing becomes very easy:

```dart
PortalEntry(
 // aligns the top left of the white card with the bottom left of the blue card
  originAnchor: FractionalOffset.topLeft,
  entryAnchor: FractionalOffset.bottomLeft,
  portal: Card(color: Colors.blue, child: Text('overlay')),
  child: Card(
    color: Colors.white,
    child: Text('drag me'),
  ),
);
```

And the layout would also _not_ be late by a frame.

> And what kind of Hero animations that would enable that you currently can't do? 

There are quite a lot of issues requesting it. Here's one of the many use-cases:

![ezgif com-resize](https://vuejsexamples.com/content/images/2018/09/gridlayou.gif)

We can see how the grid items smoothly moves from one position to another. 
There's no push/pop involved, but it's still a Hero animation.

**Comment by ds84182** [comment]
Couldn't a "Portal" be achieved with a widget that automatically manages an OverlayEntry in addition to a CompositedTransformTarget?

**Comment by rrousselGit** [comment]
I have no idea what `CompositedTransformTarget` is. But it is impossible to insert an `OverlayEntry` inside `initState`/`didUpdateWidget` and will throw the typical "setState() or markNeedsBuild() called during build".

**Comment by rrousselGit** [comment]
Ah, I missed @Hixie's answer.
Thanks for the feedback! I'll take a look into this.

I'd like to make sure of something else first:
Assuming we're able to make a custom RenderObject as you've described to watch a descendant's size, what about its **position**?

Because I tried calling `descendant.getTransformTo(parent)`  to obtain the offset of `descendant` within `parent`. But this, too, makes some assertions fail (as some implementations of `applyPaintTransform` depends on `RenderBox.size`).

**Comment by Hixie** [comment]
Tracking position has to be done at the layer tree level (because you won't be notified when a random ancestor in a different paint boundary changes its child transform). That's what CompositedTransformFollower is for.

**Comment by rrousselGit** [comment]
> The [CompositedTransformTarget] must come earlier in the paint order than this [CompositedTransformFollower].

In that case, the target would be the descendant and the follower would be the parent. Won't that cause an issue as the parent's `paint` method is called before the descendant?

**Comment by rrousselGit** [comment]
> You wouldn't use RenderBox. RenderBox isn't set up to do this. You'd have to create a new RenderObject subclass that knows how to propagate the dirty state when the size of a descendant might change.

About this, I have some trouble understanding how that would work (even while looking at the sources of intrinsic/baseline)

But I've thought of a potential alternative.
Do you mind validating it @Hixie, so that we can close this issue?

Basically, instead of a custom `RenderObject` subclass, I'm thinking of having two `RenderBox` for the parent, such that we'd have a tree similar to:

```
              RenderPortal
           /                       \
       child                    RenderPortalTheater
          !                                  /          \
    whatever                   entry1    entry2   ...
          !
   PortalEntry
          !
      child
```


Where `RenderPortal` is nothing by a `Stack` (it doesn't depend on the descendant's size).
It is instead `RenderPortalTheater` that  depends on `PortalEntry`'s size.

Then, `PortalEntry`'s `performLayout` will pass its size to `RenderPortalTheater`, which calls `markNeedsLayout` on the theater.
And since `RenderPortalTheater` is in a different branch and later in the layout order, it will naturally update within the same frame.

This should allow `RenderPortalTheater` to always be in sync with `PortalEntry`'s without doing anything too advanced for me.

**Comment by rrousselGit** [comment]
Alright, after a lot of work I can confirm that the above architecture works.

So this feature request is no longer needed
