### ISSUE TITLE
Flutter 1.12.13+hotfix.5  when Subclasses of FlutterFragment ,it guide to implement some abstract func eg:getActivity,but it take an error when compile 

### ISSUE THREAD

**Issue by MichaelSZM** [flutter/flutter#48138]
## Steps to Reproduce

1. class TestFlutterFragment : FlutterFragment(){
    override fun getActivity(): Activity? {
        return activity
    }

    override fun getContext(): Context {
        return context
    }

    override fun getLifecycle(): android.arch.lifecycle.Lifecycle {
        return lifecycle
    }
}

2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
'getActivity' in 'FlutterFragment' is final and cannot be overridden |  


Unresolved reference: arch |  
-- | --



```

```
```

```
```

**Comment by dnfield** [comment]
You cannot override the `getActivity` method of a `Fragment`.  This is an Android thing, not specific to Flutter.

There's really no action for us to take on this bug - you can read more here: https://developer.android.com/reference/android/app/Fragment#getActivity() (notice it's declared as final).

**Comment by oth-libs** [comment]
@dnfield the issue is that it's using `android.arch.lifecycle.Lifecycle` instead of `androidx.lifecycle.Lifecycle`. I'm having the same issue and is blocking me atm

**Comment by dnfield** [comment]
@oth-libs that should habe a new bug tracking it
