### ISSUE TITLE
The use of term "platonic" is confusing

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#48137]
Internal: b/147018208

A number of docs for Flutter widgets in the API docs use the term "platonic" without defining the term, for example the Builder documentation: "A platonic widget that calls a closure to obtain its child widget."

It seems like this term is very confusing to external users, eg. https://stackoverflow.com/questions/52088889/can-someone-explain-to-me-what-the-builder-class-does-in-flutter
The term is also very confusing to me and my teammates, it took us quite some time to figure out what is meant by it.
It doesn't have any obvious connection to any dictionary definition of "platonic" that I could find, eg. https://www.merriam-webster.com/dictionary/platonic
It doesn't seem to be a term generally used in the CS or Software Engineering communities.
The only public mention I could find was in the Gitter link in one of the StackOverflow comments, https://gitter.im/flutter/flutter/archives/2017/05/02
I suspect that we invented the term internally and accidentally started using it in public documentation, overlooking that has entirely different meanings to an external audience.

Some possible solutions:

- Update the docs to explain what is meant in plain English, avoiding jargon, especially undefined jargon. For example, AnimatedBuilder, which I think is internally considered a "platonic" widget, is described as "A general-purpose widget for building animations.". Maybe the term "general-purpose" is a good replacement for platonic everywhere where platonic appears in the docs. If that sounds good, I'd be happy to prepare a PR into the public GitHub project.
- Invent some new Flutter jargon to describe the concept and define it clearly, since platonic already means something else for most English speakers.
- Remove the term "platonic" completely, eg. "A widget that calls a closure to obtain its child widget."

Thanks for taking a look at this!

List of affected docs:

https://api.flutter.dev/flutter/widgets/StatefulBuilder-class.html
https://api.flutter.dev/flutter/widgets/Builder-class.html

**Comment by dnfield** [comment]
I assumed it meant platonic in the philosophical sense of something that is an abstract idea and not meant to exist concretely :) 

But I can see how this term might be confusing to people - it's not very commonly used by most English speakers today and sounds a bit jargony.  @hixie or @abarth are in the blame for those usages and may have some ideas.

**Comment by Hixie** [comment]
The term is used with analogy to "platonic solids". Quoting Wikipedia, "they are named for the ancient Greek philosopher Plato who hypothesized in one of his dialogues, the Timaeus, that the classical elements were made of these regular solids". In the context of Flutter, they represent the simplest possible Flutter Widgets, from which one can determine how more complicated widgets should behave. For example, `Builder` rebuilds when you pass in a new closure. Therefore, `LayoutBuilder` should do the same, as should `ListView.builder`.

We should probably add a paragraph explaining this to the various places where we use the term.

**Comment by jamesderlin** [comment]
I agree that there should be a paragraph explaining it.  I also think that "platonic" (which should be capitalized in this sense) should be dropped; it's confusing.  The applicable definition is "of, relating to, or characteristic of Plato or Platonism", and I'm highly skeptical that Plato had any treatises about Flutter or about widgets.  Perhaps consider "basic", "standard", or "archetypal" instead.

**Comment by markusaksli-nc** [comment]
More discussion on this at https://github.com/flutter/flutter/pull/63584
