### ISSUE TITLE
iOS users will expect to be able to show a "share sheet"

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4814]
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIActivityViewController_Class/index.html

![simulator screen shot jul 6 2016 8 28 38 am](https://cloud.githubusercontent.com/assets/11857803/16623642/919a713e-4353-11e6-9738-060ae471b5f8.png)

One can wire up a custom HostMessage-based service, but we may also need to provide a standard service wrapper for this as well.

**Comment by sethladd** [comment]
I think we can close this in favor of https://github.com/flutter/flutter/issues/7111

**Comment by Hixie** [comment]
Closing per last comment
