### ISSUE TITLE
iOS deployment target override

### ISSUE THREAD

**Issue by trujillo138** [flutter/flutter#48148]
On the `.ios` folder you can change the deployment target to a higher version of iOS by editing the `Podile` and `Runner.xcworkspace`. However, each time you run `flutter pub get` these changes will disappear and you will once again be set to iOS 8.

Is there a way to change this behavior? For most apps it doesn't make sense supporting such an old version.

## Before running `flutter pub get`:
![PodfileBefore](https://user-images.githubusercontent.com/8731855/71744989-c313b780-2e1d-11ea-8a3a-f3149859cc2f.png)
![RunnerBefore](https://user-images.githubusercontent.com/8731855/71744990-c313b780-2e1d-11ea-8555-cba32225591c.png)

## After running `flutter pub get`:
![RunnerAfter](https://user-images.githubusercontent.com/8731855/71745027-e2124980-2e1d-11ea-9199-58a39e12d977.png)
![PodfileAfter](https://user-images.githubusercontent.com/8731855/71745030-e2aae000-2e1d-11ea-9b35-710b9259332f.png)

**Comment by jonahwilliams** [comment]
You should not be using the module project unless you are doing add2app - the .ios folder is only created to bootstrap a minimal application for local development. If you want to edit source files, the best approach would be to create a regular project instead.
