### ISSUE TITLE
The strange html response with proxy setting

### ISSUE THREAD

**Issue by starman1108** [flutter/flutter#48145]
I am testing with http proxy setting in my Android device.
Here is my http code.
```
final response = await http.post(
       url,
        headers: {"Accept": "application/json"},
        body: params);
if (response.statusCode == 200) {
      // If the call to the server was successful, parse the JSON.
      print(response.body);
      return ApiResponseModel.fromJson(json.decode(response.body));
    } else {
      // If that call was not successful, throw an error.
      throw Exception('Failed to load post');
    }
```
When proxy was set, all post request's response is as following:
`<html><body><script type="text/javascript" src="/cupid.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("5ae863e84034e1e9332548af75d013be"),b=toNumbers("20d60e68703d8825d49c5715d3f50942"),c=toNumbers("56f4ef375b38e7074f23d99d75601058");var now=new Date(),time=now.getTime();time+=3600*1000*24;now.setTime(time);document.cookie="CUPID="+toHex(slowAES.decrypt(c,2,a,b))+"; expires="+now.toUTCString()+"; path=/";location.href="http://abcd.cafe24.com/api/customer/notice?ckattempt=1";</script></body></html>`

Of course, when I remove the proxy info in my device, all requests is okay.

Does http module get the device's proxy setting?

I got the answer that is flutter's problem from dart-lang/http.
https://github.com/dart-lang/http/issues/358#issue-545048807

**Comment by dnfield** [comment]
It's al ittle hard to say from your code snippet (what is `http`?), but assuming that http is just https://pub.dev/documentation/http/latest/http/post.html, it's the same as the answer you got in dart-lang/http#358.  We use Dart for this.  Dart doesn't know about proxy settings.

Dart's http library also does not know how to follow redirects like the one your proxy is giving you there.  You need to parse that HTML yourself and figure out what cookies you want to now add to subsequent requests to abcd.cafe24.com etc.
