### ISSUE TITLE
dart engine corrupted

### ISSUE THREAD

**Issue by nur-azhar** [flutter/flutter#48156]
## Steps to Reproduce

1. ... change .bashrc to add path flutter
2. ... type flutter doctor
3. ... flutter downloads dart engine
4. ... can't download file corrupted

## Logs

/home/nur/flutter/bin/internal/update_dart_sdk.sh: line 86: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

```
```

**Comment by nur-azhar** [comment]
OS: manjaro linux

**Comment by jonahwilliams** [comment]
@nur-azhar do you have an unzip command in the linux distribution you are using?

**Comment by nur-azhar** [comment]
nah i gave up i'll stick to windows thanks
