### ISSUE TITLE
iOS users will expect Dynamic Type support

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4815]
This is the ability for the user to set the preferred font size inside "Display & Brightness" on some phones and "General > Accessibility" on others.  I'm told that many apps on the store don't support this yet, but @abarth seemed to think this would be relatively straightforward for Flutter to do.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TransitionGuide/AppearanceCustomization.html

![simulator screen shot jul 6 2016 8 31 51 am](https://cloud.githubusercontent.com/assets/11857803/16623795/136a2466-4354-11e6-8114-c0e5e745c377.png)

**Comment by collinjackson** [comment]
The link Eric posted didn't work for me, but I think this is the current way to do it: https://developer.apple.com/documentation/uikit/uiapplication/1623048-preferredcontentsizecategory

I am investigating.

**Comment by yjbanov** [comment]
I can sneak it in with my 24-hour time format option change, since I'm touching all the relevant code already. So I'll reassign this issue to myself.

**Comment by yjbanov** [comment]
Not quite. https://github.com/flutter/flutter/pull/12517 is needed.

**Comment by Hixie** [comment]
Looks like this landed.
