### ISSUE TITLE
iOS users expect clicking the status bar to scroll to the top

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4816]
Should be a relatively straightforward addition to the framework? @Hixie

**Comment by eseidelGoogle** [comment]
This and https://github.com/flutter/flutter/issues/4817 are the only two iOS-isms I've personally whitnessed users try subconciously in Flutter iOS and have them fail.  I'd definitely lobby for this by EOQ at least if not August.  This particular bug might be a very straightforward addition to AppBar, donno.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/5425
