### ISSUE TITLE
Cupertino ActionSheet wrong transparency

### ISSUE THREAD

**Issue by gmeles** [flutter/flutter#48168]
I noticed that after upgrade to > v1.10 (currently 1.12.13+hotfix.5) from 1.9.1+hotfix.6 the code below produce a different result : 

`                                  showCupertinoModalPopup(
                                    context: context,
                                    builder: (BuildContext context) => CupertinoActionSheet(
                                        title: const Text('Choose Options'),
                                        message: const Text('Your options are '),
                                        actions: <Widget>[
                                          CupertinoActionSheetAction(
                                            child: const Text('One'),
                                            onPressed: () {
                                              Navigator.pop(context, 'One');
                                            },
                                          ),
                                          CupertinoActionSheetAction(
                                            child: const Text('Two'),
                                            onPressed: () {
                                              Navigator.pop(context, 'Two');
                                            },
                                          )
                                        ],
                                        cancelButton: CupertinoActionSheetAction(
                                          child: const Text('Cancel'),
                                          isDefaultAction: true,
                                          onPressed: () {
                                            Navigator.pop(context, 'Cancel');
                                          },
                                        )),
                                  );`

On 1.9.1+hotfix.6  all CupertinoActionSheetAction's have the same transparency (I guess 0%) which is correct, but on later versions the transparency of cancelButton is 0% as before and the others have a very high transparency (maybe more that 50%)

**Comment by LongCatIsLooong** [comment]
From https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/action_sheet.dart the alpha is roughly 0.78:
```dart
// Extracted from https://developer.apple.com/design/resources/.
const Color _kBackgroundColor = CupertinoDynamicColor.withBrightness(
  color: Color(0xC7F9F9F9),
  darkColor: Color(0xC7252525),
);
```

We [follow the latest (iOS 13) OEM behavior in general](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior) and per the comments the colors were extracted from https://developer.apple.com/design/resources/, so they should be relatively close to what the native component uses. But if I remember correctly the background blur is still missing so the content in the background is more visible than it should be.

**Comment by gmeles** [comment]
Ok. But why the cancel button is different than the others. Most importantly, will it be fixed, or is there a workaround?

**Comment by gmeles** [comment]
> From https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/action_sheet.dart the alpha is roughly 0.78:
> 
> ```dart
> // Extracted from https://developer.apple.com/design/resources/.
> const Color _kBackgroundColor = CupertinoDynamicColor.withBrightness(
>   color: Color(0xC7F9F9F9),
>   darkColor: Color(0xC7252525),
> );
> ```
> 
> We [follow the latest (iOS 13) OEM behavior in general](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior) and per the comments the colors were extracted from https://developer.apple.com/design/resources/, so they should be relatively close to what the native component uses. But if I remember correctly the background blur is still missing so the content in the background is more visible than it should be.



Ok. But why the cancel button is different from the others and most importantly, is there a fix or workaround?

**Comment by LongCatIsLooong** [comment]
Here's a screenshot of a native action sheet: https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/. The cancel button is different.

If you're talking about the background blur, unfortunately I'm not aware of an existing workaround or fix.

**Comment by gmeles** [comment]
So sad. With that in mind I guess that the current Stable version is not for production yet. At least if you want to build native look for iOS apps

**Comment by LongCatIsLooong** [comment]
My memory failed me. Apparently the background blur is there:
https://github.com/flutter/flutter/blob/1613a62e85269433682ffc97653d197c50c06240/packages/flutter/lib/src/cupertino/action_sheet.dart#L208-L219

**Comment by LongCatIsLooong** [comment]
Closing this issue as it seems `CupertinoActionSheet`'s appearance is mostly on point. Feel free to reopen if you find it otherwise!

**Comment by CreativeCode** [comment]
Please consider reopening it. The issue seems to be the background is _not_ blurred when this is shown ontop of a _webview_. When ontop of a greyish webpage, the menu really becomes almost unreadable. I am using it in combination with webview_flutter package, and show options like "Open this site in Safari" in it. But the website in the background does not seem blurred at all.

**Comment by gmeles** [comment]
Please reopen

https://github.com/flutter/flutter/issues/50183

**Comment by LongCatIsLooong** [comment]
@CreativeCode @gmeles sorry for the delayed response. It seems `UIKitView` currently does not support backdrop filter: https://github.com/flutter/flutter/issues/39269.

**Comment by gmeles** [comment]
@LongCatIsLooong is this an open  issue then? Can we somehow bypass the problem ?

**Comment by gmeles** [comment]
I ended up reverting my project to v1.9.1+hotfix.6
I prefer loosing dark mode than having such ugly alerts
We cannot Design beautiful apps with current stable version at least for iOS
Please try to fix
Thanks
