### ISSUE TITLE
[Web] TextSpans should be able to have widget as child in array of children

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#48167]
Currently the only way to make certain widgets show a selector hand when a mouse is hovering above them in Flutter Web is to wrap them in a widget. However when it comes to TextSpans and using them for a Click here, all of the sudden, we need to use TextSpans for the children and we cannot use widgets. This provides a conundrum as it make it currently impossible to wrap a "Click Here" TextSpan in a SelectorHand widget in order to make it appear selectable. Please change this or provide a way to give the selector text a selector hand in order to notify users that the text can be clicked. I should also be able to do things like wrap my TextSpan in a button and use it. Theres no way to integrate a button out of a TextSpan into your text to my knowledge.

**Comment by mdebbar** [comment]
This is not a web-specific request, so removing the `platform-web` label.

cc @dkwingsmt who worked on mouse cursors.

**Comment by khari998** [comment]
If there is any way to make a TextSpan have a selector hand on Flutter web, please post suggestions here.

**Comment by khari998** [comment]
Textspans now have the ability to use a Selector cursor with the mouseCursor key

```TextSpan(
  text: 'text',
  style: style,
  mouseCursor: MaterialStateMouseCursor.clickable,
  recognizer: TapGestureRecognizer()
    ..onTap = () {
      // open link
    },
)```
