### ISSUE TITLE
Facing problem on linux installation

### ISSUE THREAD

**Issue by gagsy** [flutter/flutter#48166]
Unable to install flutter on linux for web apps

**Comment by hauketoenjes** [comment]
What do you mean by installing "flutter on linux for web apps"? Would you mind sharing a bit more information on your problem?

You can find a guide on how to install flutter on linux here:
[Flutter Getting Started](https://flutter.dev/docs/get-started/install/linux)

And you can find a guide on how to set up a web application with flutter for web here:
[Flutter Web Getting Started](https://flutter.dev/docs/get-started/web)

**Comment by iapicca** [comment]
Hi @gagsy 
do @hauketoenjes proposed steps fix your issue?
than you

**Comment by gagsy** [comment]
Thanks I installed flutter in windows 
Can you help me flutter hosting using godaddy or liquidweb

**Comment by hauketoenjes** [comment]
I think it is a bit out of context to ask for help to host a flutter web app, you should probably ask on StackOverflow or Google by yourself.
