### ISSUE TITLE
can't run my Web appliation

### ISSUE THREAD

**Issue by sufizzkl7** [flutter/flutter#48164]
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatelessWidget{
  @override
  Widget build(BuildContext context){
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.centerLeft,
            end: Alignment.centerRight,
            colors: [Color.fromRGBO(195, 0, 0, 1.0),Color.fromRGBO(155, 125, 125, 1.0)]
          )
         ),
         child: Column(
           children: <Widget>[
             NavBar()
           ],
         ),
      ),
    );
  }
}
class NavBar extends StatelessWidget{
  @override
  Widget build(BuildContext context){
    return LayoutBuilder(
      builder: (context,constraints){
        if(constraints.maxWidth>800){
          return DesktopNavbar();
        } else {
          return MobileNavbar();
        }
      }
    );
  }
}

class DesktopNavbar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Row(
        children: <Widget>[
          Text('COCULT',style:TextStyle(fontWeight:FontWeight.bold,color:Colors.white,fontSize:30)),
          Row(
            children: <Widget>[
              Text('Home',style:TextStyle(fontSize: 22,color: Colors.yellow)),
              Text('About',style:TextStyle(fontSize: 22,color: Colors.yellow)),
              Text('Contact Us',style:TextStyle(fontSize: 22,color: Colors.yellow))
            ],
          )
        ],
      ),
    );
  }
}

class MobileNavbar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
    );
  }
}

-------------------When I Tried To Run This Code I Get The Following Message------------------

C:\Users\PC -01\code\webpoject2>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Error compiling dartdevc module:webpoject2|lib/main.ddc.js              

packages/webpoject2/main.dart:43:14: Error: The method 'NavBar' isn't defined for the class 'MyHomePage'.
 - 'MyHomePage' is from 'package:webpoject2/main.dart' ('packages/webpoject2/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'NavBar'.
             NavBar()
             ^^^^^^

AssetNotFoundException: webpoject2|lib/main.ddc.js
Failed after 7.2s
Building application for the web...                                33.1s
Failed to build application for the Web.

PLEASE HELP

**Comment by hauketoenjes** [comment]
If i try your code, it works just fine, your have a  `flutter doctor`? Seems like there is an import missing or so, do you have the code in several files and copied it together for github, or is this code in one file you are trying to run?

**Comment by sufizzkl7** [comment]
Actually this code has separated file. When i i run this code in one file,it works fine.but i wanted it separately.when i'm doing that the above error message will be shown.

**Comment by dnfield** [comment]
This is an issue with your code.  Your question would be better asked on a forum like StackOverflow - this issue tracker is for Flutter bugs and feature requests.
