### ISSUE TITLE
Flutter 1.12 add to app problem

### ISSUE THREAD

**Issue by FengYuanjun** [flutter/flutter#48169]
- **If my flutter module contains multiple pages. How to use cachedEngine to route to different pages on Android.(single engine and multi pages).**

- 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/35558559/71763291-6693c380-2f15-11ea-8eb5-bd311e1243cb.png">

- 
<img width="469" alt="截屏2020-01-04下午5 07 37" src="https://user-images.githubusercontent.com/35558559/71763251-b8881980-2f14-11ea-8538-17026beff3cb.png">

- **Thinks!**

**Comment by xster** [comment]
Duping into https://github.com/flutter/flutter/issues/31185
