### ISSUE TITLE
[video_player] the landscape video is wrapped by 180 degrees

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#48177]
When is the video recorder in landscape mode but with controllers on the left side
then uploaded to datastore and then play with video_record the video is wrapped by 180 degrees.

is there some chance to fix it? 

video links: 
**ios**
https://storage.googleapis.com/bazzarro-chat-files/5/q/5qAZFd-pYC7GpYTd0Skdl4GgtmMi-x-q3M1UhPiewPav7ne6_VqF4m7-nkb7/Video.mov
**android**
https://storage.googleapis.com/bazzarro-chat-files/1/h/1hXiZvywmfTz-YIB4H7fxqKagPFX-qzrhE_xMYb8AItu5L8HkTE3SMCVmnMG/Video.mp4

**Comment by iapicca** [comment]
Hi @kleinpetr 
can you please provide your `flutter doctor -v` 
and a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @kleinpetr 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
