### ISSUE TITLE
iOS users will expect back gesture support

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4817]
iOS apps have a back gesture for navigating backwards.  It reveals the previous navigation route and can be canceled.  Also has some corresponding app-bar animations.  We'll need at least some of this on iOS in the gallery.

**Comment by eseidelGoogle** [comment]
Here is an example from the Settings app.
![img_0071](https://cloud.githubusercontent.com/assets/11857803/16625942/b7f6198e-435b-11e6-9ac7-374d21a48c6d.PNG)

**Comment by eseidelGoogle** [comment]
@chinmaygarde pointed out to me that there are a zillion nice details to this transition, including that the chevron applies a triangle-clip on the text as it moves past it.  Unclear which of those details apply to material, but we need at least to implement the gesture to start.

**Comment by sethladd** [comment]
This feature goes hand-in-hand with the new view/panel sliding in from the right. To see that in action, go to the App Store, and tap an app icon. See how the app's screen moves in from the right. And then you can swipe from the left to right to go back.

**Comment by eseidelGoogle** [comment]
Please feel free to remove, I'd recommend we consider this for August if we have time.
