### ISSUE TITLE
I am having difficulty installing Flutter Sdk and Dart Sdk

### ISSUE THREAD

**Issue by Nababkhan007** [flutter/flutter#48176]
When I am try to installing flutter sdk and dart sdk, the 2 components not downloaded.

**Comment by DanTup** [comment]
Can you explain in more detail what you're seeing, for example how are you trying to install them and are you seeing an error message?

**Comment by DanTup** [comment]
I noticed your GitHub profile says Bangladesh, so I think you may be seeing https://github.com/flutter/flutter/issues/48030. It seems like the the servers hosting Flutter components may be being blocked in Bangladesh.

**Comment by Nababkhan007** [comment]
But why the server hosting Flutter components blocked in Bangladesh. I have some important work on flutter, some trouble was happened me last day. I want to completed the installation with no hesitation. Please give me any solution. Thanks!

**Comment by DanTup** [comment]
I don't know why it's blocked, that's something you might be able to raise with your ISP. There are some possible workarounds in #48030 (for example downloading from the Chinese mirror) but it's not clear whether they work.

I'll close this issue as a dupe to avoid splitting information about this over multiple issues - please comment on that one if you try those workarounds if they do/don't work. Thanks!

**Comment by Nababkhan007** [comment]
Ok thank you! If there will still problem, then I shall comment again.

**Comment by Nababkhan007** [comment]
Thanks a lot man, everything is fine and smooth now :) love flutter <3
