### ISSUE TITLE
How to implement eraser feature for drawing app

### ISSUE THREAD

**Issue by AnsonWooBizCloud** [flutter/flutter#48170]
There is a video about creating a drawing app by flutter ([https://www.youtube.com/watch?v=yyHhloFMNNA](url)) which support to draw lines / points when user tapping on screen but I can't find a feature / way to erase what user had drawn like Android native ( like [https://stackoverflow.com/questions/25094845/implementing-an-eraser-in-an-android-drawing-app-black-trail-and-then-transpar](url)) especially for lines.

Can anybody give me some advised about it?

Thanks.

**Comment by dnfield** [comment]
This is a question more appropriate for StackOverflow, as it is not a bug report or a feature request.

See, for example, https://stackoverflow.com/questions/46241071/create-signature-area-for-mobile-app-in-dart-flutter

**Comment by harshkumarkhatri** [comment]
The link you mentioned was not the solution to the question asked.

**Comment by dnfield** [comment]
No, I was simply trying to help provide a step in the right direction. The issue was closed because it's more of a request for help or a how-to than a feature request/bug report.

**Comment by harshkumarkhatri** [comment]
Is there some feature similar to what is asked in the question? I am working on an app that needs the erase thing. It would be great if you let me know about the same. @dnfield
