### ISSUE TITLE
iOS Keyboard does not show suggestions

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4818]
iOS Keyboard shows suggestions in other apps, but does not seem to show the suggestion bar in flutter.

**Comment by tvolkert** [comment]
Side note: GBoard still does

**Comment by abarth** [comment]
There are two editing protocols we can implement.  We implement the simple one.  We need to implement the advanced one to get this functionality.

**Comment by xster** [comment]
#7460 is a dupe right?

**Comment by abarth** [comment]
It's likely the same patch will fix both issues.  Feel free to close as a dupe if that's easier for you.

**Comment by abarth** [comment]
I think we're supposed to implement UIText​Input: https://developer.apple.com/reference/uikit/uitextinput

**Comment by abarth** [comment]
Currently we only do UIKeyInput

**Comment by cbracken** [comment]
Yep; there are a dozen methods or so to override, but doesn't look too bad and also appears to fix the press-and-hold backspace and CJK (etc.) IME woes. 

Got started on this a couple weeks back but got dragged away by a string of tools issues. Hoping to get back to this later this week.

**Comment by cbracken** [comment]
Fixed by flutter/engine#3586

**Comment by skela** [comment]
This seems broken, at least to me. I'm not able to get this to work on iOS. I've added some more info in the TextField autofill for verification messages #22858 issue . Should this issue be re-opened, or should I make a new issue?

**Comment by eseidelGoogle** [comment]
Given how hold this issue is I would suggest opening a new one with reproduction steps and we'd be happy to look!
