### ISSUE TITLE
when set render mode with FlutterView.RenderMode.texture,there is no view show 

### ISSUE THREAD

**Issue by MichaelSZM** [flutter/flutter#48181]
## Steps to Reproduce

1.
```java
 ...var newFlutterFragment = FlutterFragment.withNewEngine()
                .renderMode(FlutterView.RenderMode.texture)
                .initialRoute("fragment_no_ext_args")
                .build<FlutterFragment>()
```

**Comment by MichaelSZM** [comment]
when set ender mode with surface and transparencyMode(FlutterView.TransparencyMode.opaque)
it is also no ui show

**Comment by iapicca** [comment]
Hi @MichaelSZM 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @MichaelSZM 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
