### ISSUE TITLE
I am having difficulty installing Flutter

### ISSUE THREAD

**Issue by NafizZ** [flutter/flutter#48185]
![Screenshot_1](https://user-images.githubusercontent.com/26879806/71770428-9616f000-2f56-11ea-82b9-35f9b3a86d0b.jpg)

**Comment by jonahwilliams** [comment]
We need the contents of the log: flutter_02.log in order to help, that contains the crash information

**Comment by NafizZ** [comment]
> We need the contents of the log: flutter_02.log in order to help, that contains the crash information

Thanks for your feedback. I have already fixed the problem.
