### ISSUE TITLE
Image Picker package error

### ISSUE THREAD

**Issue by xmavara** [flutter/flutter#48187]
When i add image picker package to my app and then start it i get this error:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find core.jar (androidx.core:core:1.0.1).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/androidx/core/core/1.0.1/core-1.0.1.jar

please help me!

**Comment by iapicca** [comment]
Hi @xmavara 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by TahaTesser** [comment]
Hi @xmavara 
Are you still having trouble downloading Flutter?
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
