### ISSUE TITLE
Reordarable list can be dismissable.

### ISSUE THREAD

**Issue by amitshinde110113** [flutter/flutter#48197]
## Proposal

Add new feature to Reaordarable list.
Make reorerable list dismissable. Each list item can reorderable and aslo dimissable.

**Comment by hoshinokanade** [comment]
Did you tried using [Dismissable](https://api.flutter.dev/flutter/widgets/Dismissible-class.html) with ReordarableListView?
```
ReorderableListView(
  onReorder: (int oldIndex, int newIndex) => {} // do sth,
  children: [
    Dismissable(
       key: //All children of ReorderableListView must have a key and so as Dismissable
       child: ListTile(
         // ...
       )
    )
  ]
)
```

**Comment by dnfield** [comment]
It's not entirely clear what you want to do here.  It's also not clear if @hoshinokanade solves your problem.  Can you update this with some more details?

**Comment by VladyslavBondarenko** [comment]
Closing since the issue is still without answer
@amitshinde110113 feel free to comment or create a new one
