### ISSUE TITLE
scroll down in dynamic list in Chrome

### ISSUE THREAD

**Issue by choohy** [flutter/flutter#48194]
## Steps to Reproduce

1. Load list from json
2. Display ListView widgets on screen
3. Scroll down list

**Target Platform:** Web
**Target OS version/browser:** Chrome
**Devices:** Mac

## Logs

flutter run --verbose
[  +29 ms] executing: [/Users/chooh/Documents/Flutter/flutter_sdk/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [/Users/chooh/Documents/Flutter/flutter_sdk/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a3601
[   +9 ms] executing: [/Users/chooh/Documents/Flutter/flutter_sdk/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/chooh/Documents/Flutter/flutter_sdk/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +168 ms] executing: [/Users/chooh/Documents/Flutter/flutter_sdk/flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +40 ms] executing: sw_vers -productName
[  +36 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +35 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +40 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G2022
[  +43 ms] executing: /usr/bin/xcode-select --print-path
[  +17 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +5 ms] executing: /usr/bin/xcodebuild -version
[ +348 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3
           Build version 11C29
[  +81 ms] executing: /Users/chooh/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/chooh/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +23 ms] executing: /Users/chooh/Documents/Flutter/flutter_sdk/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +90 ms] /usr/bin/xcrun simctl list --json devices
[ +162 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[ +120 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +13 ms] "flutter run" took 1,141ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/chooh/Documents/Flutter/flutter_sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

flutter analyze
Analyzing flutter_me...                                                 

   info • Unused import: 'package:flutter_me/ui/leave_balances_list.dart' • lib/navigation/leave.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_me/models/profile_model.dart' • lib/ui/edit_button.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_me/ui/profile_read.dart' • lib/ui/edit_button.dart:3:8 • unused_import
   info • Unused import: 'package:toast/toast.dart' • lib/ui/profile_read.dart:6:8 • unused_import
   info • Unused import: 'package:flutter_me/models/profile_model.dart' • lib/ui/save_button.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_me/ui/profile_read.dart' • lib/ui/save_button.dart:3:8 • unused_import

6 issues found. (ran in 2.8s)

flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G2022, locale en-AU)
    • Flutter version 1.12.13+hotfix.6 at /Users/chooh/Documents/Flutter/flutter_sdk/flutter
    • Framework revision 18cd7a3601 (3 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chooh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/chooh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8405

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by dnfield** [comment]
Please provide a minimal and complete example that reproduce this bug - perhaps in the form of a link to a GitHub repository or gist.

Right now, this bug isn't actionable - there's not enough information to reproduce what you're seeing.

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code, logs and the output of `flutter doctor -v` please.
