### ISSUE TITLE
Navigator pop not dismiss showDialog widget according to specified context

### ISSUE THREAD

**Issue by jerinho** [flutter/flutter#48198]
https://stackoverflow.com/questions/59596634/flutter-navigator-pop-not-dismiss-showdialog-widget-according-to-specified-con

**Comment by jamesblasco** [comment]
https://stackoverflow.com/a/59602513/8096916

**Comment by iapicca** [comment]
Hi @jerinho 
I believe posting the question on SO has you did is the right choice
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
