### ISSUE TITLE
Adding a simple MultiChildRenderObjectWidget should have less boilerplate

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4819]
We should create a RenderMultiChildProxyBox similar to RenderProxyBox.

**Comment by sethladd** [comment]
When we say "API Stability", do we mean "fixing this will be a breaking change" ? If not, we could consider moving this out to M3.

**Comment by abarth** [comment]
> When we say "API Stability", do we mean "fixing this will be a breaking change" ?

Yes.

**Comment by abarth** [comment]
(Or at least we think there's a good chance it might.)

**Comment by abarth** [comment]
I'm not entirely sure what we should do here, but it seems like we should be able to do it without breaking the API.

**Comment by Hixie** [comment]
I'm going to close this. We don't need to track this particular problem independently. If it becomes a real issue we'll just fix it.
