### ISSUE TITLE
Gradle task assembleDebug failed: resource android:attr/fontVariationSettings not found

### ISSUE THREAD

**Issue by hayyann** [flutter/flutter#48205]
Following is the code that I'm trying to run.

![Screenshot (1)](https://user-images.githubusercontent.com/59503740/71778943-c81b6700-2fd5-11ea-86e4-5a356cbae4ef.png)

Target Platform: Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**_Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\8785b1333ccfee40180d9ac1d1a63e1a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\hayya\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\8795c7c7149d9230db0423e079c95a4d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\hayya\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.micard\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\hayya\AndroidStudioProjects\mi_card_flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1_**

![Capture](https://user-images.githubusercontent.com/59503740/71779094-8e972b80-2fd6-11ea-9e03-fb22183f7c17.PNG)
![2](https://user-images.githubusercontent.com/59503740/71779095-9060ef00-2fd6-11ea-9afc-6c0ec87571df.PNG)

**Comment by dnfield** [comment]
It sounds like something has gone wrong with your Android project.  Can you share a github repo with a full reproducing sample?

Did you manually change things in the `android` folder?

**Comment by hayyann** [comment]
No I didn't change anything in the android folder.

The github repo I'm trying to use is https://github.com/londonappbrewery/mi_card_flutter

**Comment by hayyann** [comment]
The problem is something with github. I copied the code and pasted it into a new project and it works like a charm. What possibly could I be doing wrong so that the code is not running?

**Comment by dnfield** [comment]
It's very likely some file or files got corrupted somehow in your Android folded.  I'm going to close this as not reproducible. If you find a reproduction please feel free to add it :)
