### ISSUE TITLE
shared_preferences calls deprecated API

### ISSUE THREAD

**Issue by chinnonsantos** [flutter/flutter#48211]
When I use the [Shared preferences plugin](https://pub.dev/packages/shared_preferences)

### [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated...
```
/home/chinnonsantos/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
```
**Should I worry about this using the plugin?**

**Comment by dnfield** [comment]
This should be fine for now - but we should also update it to not use deprecated API.

**Comment by priyaswd** [comment]
I am facing same issue while build APK 
Running Gradle task 'assembleRelease'...                        
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated

    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());

                        ^

1 warning

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by dcordi** [comment]
a solution to no longer have deprecated API message with the 'shared_preferences' library.

add WidgetsFlutterBinding.ensureInitialized();  in your main.dart

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();  
.....
}
```

and replace 
`setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());`
by 
`setupChannel(binding.getBinaryMessenger(), binding.getApplicationContext());`
in
C:\flutter\pub-cache\hosted\pub.dartlang.org\shared_preferences-0.x.x\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java

It is a temporary solution while waiting for the next version ;-)
