### ISSUE TITLE
Expose ScrollController inside the ReorderableListView

### ISSUE THREAD

**Issue by exts** [flutter/flutter#48219]
## Use case

- currently there's no way to use a reorderable list view and tell us when the user is scrolling through items. the property is private [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/reorderable_list.dart#L203)
- there's a package called [speed dial](https://pub.dev/packages/flutter_speed_dial) that replaces the floating action button and accepts a parameter to hide the visibility when the user is scroll, allowing you to see a little bit more of your app in case the button is hiding visibility of data. [example of this working](https://github.com/darioielardi/flutter_speed_dial/blob/master/example/lib/main.dart)

## Proposal

- Expose the scrollController property and allow us to set a custom scroll controller so we can know when the user is scrolling items inside the reorderable list view.

**Comment by dnfield** [comment]
You can see here:  https://github.com/flutter/flutter/blob/0aed0b61a1789ed06c9fa05a6c5fcfbd398c4811/packages/flutter/lib/src/material/reorderable_list.dart#L263

That the scroll controller is re-created when dependencies change, but you have the option to override it via setting a primary scroll controller.  The way to do this is:

```dart
return PrimaryScrollController(
  scrollController: myScrollController,
  child: ReorderableListView(...),
);
```

I'm not sure why the scroll controller is not set via the constructor, but that should work as a work around for now.

**Comment by dnfield** [comment]
And if you want to open a PR to add this, it probably isn't too hard to do :)

**Comment by exts** [comment]
I'll give it a shot this week if nobody else is. Never contributed to flutter, but I may be able to manage. 🤞

**Comment by shihaohong** [comment]
This has been fixed so I'll close the issue
