### ISSUE TITLE
Add GameBoy Advance as a build target.

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#48213]
GameBoy Advance is just a placeholder for other platforms out there. Obviously, GBA support would be awesome but noone at Google will bother doing it, so I'm wondering how hard it would be to port the engine over to a new platform (like the TI-Nspire calculator, which can run C/C++ via Ndless).

Performance aside, is something like this even possible?
In a perfect world, I'd imagine this being as replacing stdlib.h with a custom one for the new processor/os in some main.cpp file and calling it a day, but that's probably far from the truth.

**Comment by ds84182** [comment]
Hi, this is certainly possible, but is not straightforward. See [this](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders) for more information. The steps for porting to a completely new platform (like a new OS) are not specified here as it is a lot more exploratory so it's hard to write a wiki page on. [But it certainly is possible!](https://twitter.com/ds84182/status/1155836275963809793)

The other thing to note is that you won't get support from the Flutter Engine team for your custom platform target. It'll be up to you to manage your own fork of the engine, alongside with patches to the Dart VM to make it all work. 

Anyways, happy hacking!

**Comment by CiriousJoker** [comment]
Very interesting, cool to see it working on a Switch :)

Given that FuchsiaOS is an existing build target built to support a wide range of devices, do you think "porting" FuchsiaOS might be easier instead?

**Comment by JohnDeved** [comment]
please, i would need this for my app

**Comment by Hixie** [comment]
There's zero chance we will port to the Game Boy Advance, our license file alone is too big to fit in the Game Boy Advance's RAM. :-)

Porting Flutter requires, among other things:
 - Porting Skia to support the GPU of the new platform.
 - Porting Dart to support compiling to the new platform's architecture in AOT and JIT mode.
 - Enabling hot reload on the new architecture.
 - Porting the tool to support the new architecture, including supporting the equivalents of "adb" and package signing and so forth.

**Comment by JohnDeved** [comment]
@Hixie thanks for clarifying.
I think despite the hurdles, GBA would still be the best target platform for flutter. Let's think about this, if we compile to a.GBA file it would be super cross-platform capable. almost every platform on earth has a working GBA emulator, we would just need to ship our code with the emulator included. Kinda like electron.js, but better because it's a Gameboy emulator. 

It's borderline genius, isn't it?
Thank you, i rest my case.

**Comment by Hixie** [comment]
As a general rule, for platforms that it would actually make sense to port to, we are certainly open to contributions. This bug itself doesn't seem actionable at this point so I'm going to close it.
