### ISSUE TITLE
LibFlutter.so not found

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#48224]
Hey,

I have created multiple apk according to different architecture for android and i have made it to production.

But in some devices i am getting crash saying libFlutter.so not found.

I have attached the screenshot as well of the crashlytics

![Screenshot_2020-01-06-08-26-33-81](https://user-images.githubusercontent.com/18116236/71792416-a914e780-305e-11ea-9293-5ecc93a8dd75.png)

**Comment by dnfield** [comment]
It sounds like you managed to ship an APK missing the right ABI for the device you're targetting.  You can inspect the APK by unzipping it.

The recommended way to ship to the store is AAB now, which should take care of this.  Have you tried `flutter build appbundle` instead?

**Comment by Faiyyaz** [comment]
I know AAB is the best way to ship now but on the deployment link (https://flutter.dev/docs/deployment/android) they are saying for now avoid using app bundle instead build apk using this command ```flutter build apk --split-per-abi``` which i have done and still getting issue.

I inspect all the three APK's generated by the ```flutter build apk --split-per-abi``` command and all the APK's contains the libFlutter.so file.

**Comment by dnfield** [comment]
The location of the libflutter.so file matters though.  What's the full directory structure look like?
/cc @blasten

**Comment by Faiyyaz** [comment]
Please see the screenshot for all 3 apks according to different ABI

<img width="1440" alt="app-x86_64-release" src="https://user-images.githubusercontent.com/18116236/71795988-b508a580-306e-11ea-8b55-79b3f00309cb.png">
<img width="1440" alt="app-arm64-v8a-release" src="https://user-images.githubusercontent.com/18116236/71795989-b508a580-306e-11ea-86d2-543f265b5194.png">
<img width="1440" alt="app-armeabi-v7a-release" src="https://user-images.githubusercontent.com/18116236/71795991-b5a13c00-306e-11ea-8379-147623203b7e.png">

**Comment by blasten** [comment]
This issue does look like  https://issuetracker.google.com/issues/147096055 again. But in this case, the OS seems to be looking for libflutter.so in the `lib/arm` directory instead of `lib/armeabi-v7a`.  I thought this issue was limited to App Bundles, I will add a note to the bug.

**Comment by jonahwilliams** [comment]
Since we've updated https://issuetracker.google.com/issues/147096055 , there is a documented work around in the comments. Theres not much more we can do here, so I'm closing the issue.

**Comment by blasten** [comment]
I updated https://issuetracker.google.com/issues/147096055 with suggested workarounds if you are building an APK. Please don't hesitate to comment on that bug if this crash is still happening after applying the workarounds, so the Android team can take a look.
