### ISSUE TITLE
AnimatedList with Dividers

### ISSUE THREAD

**Issue by couturmi** [flutter/flutter#48226]
Just as `ListView` has a `ListView.separated()` option to create a `ListView` with custom dividers, `AnimatedList` should have a similar option to space out the items.

**Comment by sanalkv** [comment]
Why this hasn't been added yet ?

**Comment by mregnauld** [comment]
A year after, and still nothing. Seriously?

**Comment by carman247** [comment]
If you can track the length of your list there's this might be a solution

```

List<Object> _myList = [];

...
initialItemCount: _myList.length
itemBuilder: (ctx, index, animation) {
  return Column(
      children: [
          YourItem();
          if(index < _myList.length - 1)
          Divider()
      ],
);
```

**Comment by Crdzbird** [comment]
This is gonna be implemented soon? 😕

**Comment by christianfrid** [comment]
When is it coming?

**Comment by K9RYM** [comment]
another lightweight solution to add a divider strip to the items:
`
return  Container(
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide(width: _dividerWidth, color: _dividerColor))
        ),
        padding: const EdgeInsets.all(_somePadding),
        child: ListTile() // or any other suitable Widget
      );
`

**Comment by K9RYM** [comment]
another lightweight solution to add a divider strip to the items:

```
return Container( 
            decoration: BoxDecoration( border: Border(bottom: BorderSide(
                                                                                            width: _dividerWidth, 
                                                                                            color: _dividerColor) ) ),
            padding: const EdgeInsets.all(_somePadding), 
            child: ListTile() // or any other suitable Widget
 );
```

**Comment by K9RYM** [comment]
another lightweight solution to add a divider strip to the items:

```
return Container( 
            decoration: BoxDecoration( border: Border(bottom: BorderSide( width: _dividerWidth,  color: _dividerColor) ) ),
            padding: const EdgeInsets.all(_somePadding), 
            child: ListTile() // or any other suitable Widget
 );
```

**Comment by DzonaTheSymbol** [comment]
Would love to see this! Please implement this flutter team! <3

**Comment by Hixie** [comment]
How should the separator builder handle the case of an item being inserted or removed?

Implementing the separatorBuilder as just an IndexedWidgetBuilder would mean the separator would suddenly appear or disappear when the child next to it started appearing or stopped disappearing, which is rather jarring.

**Comment by Peetee06** [comment]
@Hixie could we pass the animation the separator builder as well? That way developers can decide how the separators should behave. I would really like to use an AnimatedList.seperated :)

**Comment by Hixie** [comment]
Seems plausible.

If anyone would like help developing a PR for this, feel free to ping me (@Hixie) on the #hackers-new channel on Discord! See the [contributing docs](https://github.com/flutter/flutter/blob/89d46db77501abc95fbdbf091e7a3f6c4cd31ae9/CONTRIBUTING.md) for details.

**Comment by Hixie** [comment]
Thanks to @Peetee06 for fixing this one!
