### ISSUE TITLE
Add source android library to Flutter Plugin

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#48228]
I have created a plugin project in which I want to import another android module to it, but it doesn't seem to work.
Here is my structure:
```
|-my_plugin
  |-android
    |-settings.gradle
    |-build.gradle
|-mylibrary
  |-build.gradle
```
/android/settings.gradle:
```
rootProject.name = 'my_plugin'
include ':mylibrary'
project(':mylibrary').projectDir = new File(settingsDir, '../../mylibrary')
```
/android/build.gradle:
```
...
dependencies {
  implementation project(path: ':mylibrary')
}
```
When I run gradle sync, it gets the following error
```
Project with path ':mylibrary' could not be found in project ':my_plugin'.
```

It seems fine to download myLibrary as maven lib but fail to just import it as source. There is a [question](https://stackoverflow.com/questions/55475576/add-plain-android-library-to-a-flutter-plugin) raised on stackoverflow about it but no one can give an answer for it. 

Any clue?

**Comment by PandaGeek1024** [comment]
no one got any info about it?

**Comment by shyandsy** [comment]
https://github.com/flutter/flutter/issues/48716

same problem
there is no documentation about this

**Comment by shyandsy** [comment]
it has not been run when the flutter build apk
```
setting.gradle

rootProject.name = 'flutter_myplugin'
logger.error('A message which is logged at QUIET level:BBBBBB')
include ':app', ':core'
```

**Comment by JarvanMo** [comment]
please specify your plugin path in android folder. the reason can not find the lib is the path is wrong.

**Comment by shyandsy** [comment]
@JarvanMo 

not really

the reason for that is the setting.gradle for plugin wasnt included to the app project.

**Comment by JarvanMo** [comment]
@shyandsy You'd better understand why the settings.gradle was not included. That's because the gradle just search the given paths...

**Comment by jonahwilliams** [comment]
In general, this is not really a problem with flutter but more of a usability issue with Gradle. At any rate, this is in-actionable so I'm closing the issue.
