### ISSUE TITLE
flutter SDK loading failed while trying to download on windows 10

### ISSUE THREAD

**Issue by ShafiAzam** [flutter/flutter#48227]
Flutter SDK Zip file link is not loading. It shows failed. I'm tried in windows 10PC and my mobile also. I used the chrome and Mozilla browsers to download the SDK zip.

in chrome, console shows the errors:
![Screenshot_1](https://user-images.githubusercontent.com/24775825/71796838-ed5fb200-3075-11ea-8ee3-bcd69b9284d0.jpg)

the browser screen:
![Screenshot_1](https://user-images.githubusercontent.com/24775825/71796989-8393d800-3076-11ea-9ae7-7bfa63d59549.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @ShafiAzam 
You can try to use
https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.5-stable.zip
instead of
https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.5-stable.zip
link for downloading flutter.
But I'm not sure [this](https://flutter.dev/community/china) is your case
Does it help?
Thank you

**Comment by TahaTesser** [comment]
Hi @ShafiAzam 
Are you still having trouble downloading Flutter?
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you

**Comment by ShafiAzam** [comment]
No. Now I am with flutter flutter and flutter. Thanks.

**Comment by exoftcoders** [comment]
same  problem face
but flutter link is worked.... @vladyslavBondarenko...

**Comment by sanjid095** [comment]
I'm facing the same problem as well - flutter sdk download failed ...
I really don't get it... why is this happening.
But the link worked ... @VladyslavBondarenko   ....
Thanks a lot for sharing ...

![faild_flutter](https://user-images.githubusercontent.com/37638122/80271332-1bc6d300-86e1-11ea-9260-d0b222e92fd6.PNG)

**Comment by VladyslavBondarenko** [comment]
@sanjid095, @exoftcoders 
It looks like you have a firewall in your country, take a look at https://flutter.dev/community/china

**Comment by sanjid095** [comment]
@VladyslavBondarenko  - Thanks again for the info - will check out the link ...
Best Regards..

**Comment by linuxoracledev** [comment]
> Hi @ShafiAzam
> You can try to use
> https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.5-stable.zip
> instead of
> https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.5-stable.zip
> link for downloading flutter.
> But I'm not sure [this](https://flutter.dev/community/china) is your case
> Does it help?
> Thank you

can u pls tell me the link for latest version(1.17.0)

**Comment by VladyslavBondarenko** [comment]
@linuxoracledev 
https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_1.17.2-stable.zip

**Comment by linuxoracledev** [comment]
> @linuxoracledev
> https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_1.17.2-stable.zip

Thank you!
