### ISSUE TITLE
Flutter on Android crashes on startup

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4824]
Seems to be due to the new heap snapshot.

/cc @jason-simmons @mpcomplete

**Comment by eseidelGoogle** [comment]
@yjbanov Did our bots catch this, or do we need to add another configuration to catch crashes like these?

**Comment by yjbanov** [comment]
We caught [_something_](https://pantheon.corp.google.com/m/cloudstorage/b/flutter-dashboard/o/5dae820c1b7374891f41187d367d4de17424ec59/output.txt). I can't tell if it's related to heap snapshot though. Something at the native level for sure:

```
F/flutter : [FATAL:rasterizer_direct.cc(60)] Check failed: surface_. GLSurface required.
```

It looks like it doesn't happen always (only the mega_gallery test failed, everything else succeeded)

**Comment by eseidelGoogle** [comment]
@yjbanov That sounds like a separate bug.  Please file.  Looks like our attempt to allocate our gl surface is failing?

**Comment by yjbanov** [comment]
Filed https://github.com/flutter/flutter/issues/4832

**Comment by eseidelGoogle** [comment]
Given that `flutter run` has been crashing on iOS devices for 2 days, seems like we should roll back our Dart until this is fixed?

**Comment by abarth** [comment]
Fixed.
