### ISSUE TITLE
Regression on flutter_gallery_ios32__transition_perf average_frame_build_time_millis

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#48247]
`average_frame_build_time_millis`

This benchmark has been consistently above the goal, and since November, above the baseline. Should this be re-baselined?  @liyuqian @jason-simmons 

Not marking as as TODAY issue since this has been going for a long time.

**Comment by digiter** [comment]
![K2HHbxNJnsa](https://user-images.githubusercontent.com/6259181/72850629-6823f200-3c5e-11ea-98a0-6614828720e2.png)

Closing as this doesn't seem to be a problem at the moment.

**Comment by liyuqian** [comment]
This benchmark has also been significantly improved by https://github.com/flutter/flutter/commit/8eecdbe823ea09dd723a8af34c7c275e5536d728. Thank you @goderbauer !

**Comment by goderbauer** [comment]
Nice. Looks like it had a positive affect on multiple transition benchmarks: https://github.com/flutter/flutter/pull/48900#issuecomment-577297920.
