### ISSUE TITLE
[cocoon] Move agent statuses to have its own api endpoint

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#48249]
The Flutter build dashboard does not show information regarding agent statuses, and is moving agent statuses to its own page.

This would create something similar to `/api/public/get-agent-statuses`. Additionally, this would be a good opportunity to experiment with sending JSPB instead of JSON.

**Comment by CaseyHillers** [comment]
This should also sort the agents to return the failing ones first.

**Comment by CaseyHillers** [comment]
I don't think this is necessary anymore.

**Comment by Hixie** [comment]
There's a note in app_flutter/lib/agent_list.dart that says "TODO(chillers): Remove sort once backend handles sorting" and points at this issue. Does this issue being closed mean we can remove the logic to sort the agents?

**Comment by CaseyHillers** [comment]
Unfortunately not. Looks like that line was just using this issue as a reference for when it might be done.

The reason this was closed was because CommitStatuses and Agents are relevant to each other. The build dashboard should show what agent a task was run with, and the infra dashboard should know what tasks an agent is running.

Ideally, we would move this to have Tasks include an agent field for the build dashboard. The agent dashboard would include a task field in the agent. Alas, this creates a circular dependency.

**Comment by Hixie** [comment]
What's wrong with the client sorting the agents?

**Comment by CaseyHillers** [comment]
For the amount of users that dashboard gets and the size of the data, there probably isn't much to gain sorting on the backend.

One nice thing about sorting on the backend is that with the caching done on the backend, any repeat visits only require the sort to be done once. However, that is a very small issue to worry about.
