### ISSUE TITLE
Performance regressions in several benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48243]
It's unclear whether these are noise or correlated, and may just require rebaselining.

Benchmarks include:
  * flutter_gallery_ios32__transition_perf_worst_frame_rasterizer_time_millis
  * flutter_test_performance_implementation_change_elapsed_time_ms
  * hotReloadMillisecondsToFrameAfterChange  
 * smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotReloadMillisecondsToFrameAfterChange

**Comment by franciscojma86** [comment]
We now have an issue for each one:

`flutter_gallery_ios32__transition_perf_worst_frame_rasterizer_time_millis` https://github.com/flutter/flutter/issues/48248

`flutter_test_performance_implementation_change_elapsed_time_ms` https://github.com/flutter/flutter/issues/47839

`hotReloadMillisecondsToFrameAfterChange` https://github.com/flutter/flutter/issues/47842

`smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotReloadMillisecondsToFrameAfterChange` https://github.com/flutter/flutter/issues/48096

Closing this in favor of tracking on individual issues.
