### ISSUE TITLE
SliverFillViewport leaves blank space on either end

### ISSUE THREAD

**Issue by mayabyte** [flutter/flutter#48252]
SliverFillViewport, when `viewportFraction < 1.0`, [intentionally](https://github.com/flutter/flutter/blob/80ee2ff04fa2509bc59666f749b174738b65072e/packages/flutter/lib/src/widgets/sliver.dart#L1065) pads both ends of the list such that the first and last element end up in the center of the viewport when scrolled all the way in each direction, respectively. However, this padding becomes undesirable when the SliverFillViewport is part of a scrolling viewport with other elements, such as in a CustomScrollView.

Code to illustrate: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DoubleInfiniteList(),
    );
  }
}

class DoubleInfiniteList extends StatelessWidget {
  DoubleInfiniteList({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Key middle = UniqueKey();
    Widget forward = SliverFillViewport(
      key: middle,
      viewportFraction: 1/3,
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          Color c = index%2 == 0 ? Colors.white : Colors.grey;
          return Container(color: c);
        },
      ),
    );
    Widget backward = SliverFillViewport(
      viewportFraction: 1/3,
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          index = -index - 1;
          Color c = index%2 == 0 ? Colors.white : Colors.grey;
          return Container(color: c);
        },
      ),
    );
    return CustomScrollView(
      center: middle,
      slivers: [backward, forward],
    );
  }
}
```

Appearance: 
![output](https://user-images.githubusercontent.com/42569602/71838878-c2934f00-30b1-11ea-875f-b85701b71696.gif)

Tested on MacOS and iOS emulator.

**Comment by LongCatIsLooong** [comment]
Thank you for the issue and the pull request! In the meantime as a workaround, `SliverLayoutBuilder` and `SliverFixedExtentList` can be used in combination to achieve the desired effect.

**Comment by mayabyte** [comment]
Closing since https://github.com/flutter/flutter/pull/48207 was merged
