### ISSUE TITLE
Please create a plugin similar to google-sign-in but for Facebook authentication

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#48253]
It would nice to have an official supported plugin to authenticate with FaceBook. This should be similar to the "google-signin" plugin.

Currently , there is an open source "flutter_facebook_login" plugin but  has sparse support and it seem to break it every time a new flutter release is pushed.

This facebook plugin is necessary for apps that let user authenticate with various social framework.

I believe it will allow greater adoptability if it was an official 1st party plugin from the flutter team

Thanks

**Comment by GiacomoK** [comment]
Anybody else does have this necessity?

I really need to add facebook login to my app but I am not able to do that.
Somebody does have any advice?

**Comment by stuartmorgan** [comment]
Closing as out of scope; we don't general wrap third-party, non-system SDKs. This request should be directed to the SDK developer, and failing that could be implemented by the community.
