### ISSUE TITLE
Template plugin should not support platforms by default

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#48270]
Right now `flutter create -t plugin` creates a plugin that supports both Android and iOS.
https://github.com/flutter/flutter/pull/48258 proposes to make the template plugin support macOS as well. This increases the odds of plugin authors leaving their pubspec specifying that they support all these platforms while not really having meaningful implementation for all.

I think we should instead require the user to explicitly specify the platforms they want to support when creating a plugin. We should also make it easy to add new platforms to an existing plugin.

**Comment by stuartmorgan** [comment]
> #48258 proposes to make the template plugin support macOS as well

Just to clarify here, that was a mistake in the PR, not a proposal.

> Right now `flutter create -t plugin` creates a plugin that supports both Android and iOS.

Well, if you have `enable-macos-desktop` on for your Flutter installation, then it will create a plugin that supports Android, iOS, and macOS. That's true already, unrelated to the mistake in the PR above.

**Comment by jmagman** [comment]
I believe this was done in https://github.com/flutter/flutter/pull/59507.
