### ISSUE TITLE
soft keyboard not have clickable area on android q

### ISSUE THREAD

**Issue by ponytony** [flutter/flutter#48277]
## Steps to Reproduce

image:
![1578363627241](https://user-images.githubusercontent.com/22294620/71863645-70e1d780-3138-11ea-8f65-5f9dfe59700d.jpg)

**Target Platform: android q**

**Devices: sumsung **

**Input method: sumsung default input method **
**html:
```<input type="number"/>```
**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.6
    18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @ponytony 
what keyboard are you using?
Also can you please provide your ``flutter run --verbose`
and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
