### ISSUE TITLE
Local engine run on android_debug_unopt_x64 doesn't find POM

### ISSUE THREAD

**Issue by xster** [flutter/flutter#48276]
`flutter run --local-engine android_debug_unopt_x64` gives

`The file /Users/.../engine/src/out/android_debug_unopt_x64/x86_debug.pom wasn't found in the local engine out directory.`

But there's a x86_64_debug.pom file in android_debug_unopt_x64. Probably a tooling issue.

cc @blasten

**Comment by blasten** [comment]
are you attached to an x64 device? If the device supports multiple ABIs, it looks like the tool is picking up x86.

**Comment by xster** [comment]
It's an emulator. Is there a way to force x64? Can't build android_debug_unopt_x86 these days on newer versions of macOS I think.
