### ISSUE TITLE
websocket wss CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jacky-yanglei** [flutter/flutter#48285]
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate

I want to skip certificate validation.How do solve this problem？
![image](https://user-images.githubusercontent.com/17645850/71876075-dcd83600-3160-11ea-8485-155c9fb7599d.png)
![image](https://user-images.githubusercontent.com/17645850/71876087-e2ce1700-3160-11ea-9914-5c2f5a255f61.png)

**Comment by dnfield** [comment]
Please consider asking this on a forum like StackOverflow or the dev mailing list - this issue tracker is for bugs or feature requests in the Flutter SDK or first party plugins.
