### ISSUE TITLE
pinch/double tap to zoom in option in webview_flutter

### ISSUE THREAD

**Issue by FisherWL** [flutter/flutter#48283]
## Use case
zoom-in/out page/text/image in webview

## Proposal
I think pinch to zoom is built-in both  ios WKWebView and Android WebView.
but I didnot find a way to enable that in webview_flutter.
or maybe I missed something?
If the whole page is a pdf file, then on iphone, webview_flutter does letting me pinch/tap to zoom, but that's the only case I find it's working.

**Comment by FisherWL** [comment]
I ran a test on a phisical iphone and found that the webview does have pinch feature, which I couldn't perform on simulator.
but on android platform, there's not pinch zoom on neither emulator or phsical phones

**Comment by zhangzhaojun** [comment]
Hope reslove this issue!

**Comment by ISLEMNEDDAR** [comment]
This issue is not closed because of can't have the pinch to zoom in Android as said @FisherWL did you find a solution how to enable it ??

**Comment by FisherWL** [comment]
@ISLEMNEDDAR yes I find a solution. There is a PR mentioned on this page targeting this issue, [https://github.com/flutter/plugins/pull/2451](url). But this PR is not reviewed or approved, you have to do it manually.

**Comment by walsha2** [comment]
Still an open issue, but just documenting my findings here for any poor soul that is scouring the web for a fix.

I seem to have it somewhat (depends on platform) working by setting the appropriate `gestureRecognizers `:

```dart
gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
	Factory<VerticalDragGestureRecognizer>(() => VerticalDragGestureRecognizer()),
	Factory<HorizontalDragGestureRecognizer>(() => HorizontalDragGestureRecognizer()),
	Factory<ScaleGestureRecognizer>(() => ScaleGestureRecognizer()),
},
```

This enables scrolling and pinch zoom on iOS and everything works just fine.

On Android scroll works in both directions, but the I think that this PR https://github.com/flutter/plugins/pull/2451 needs to go in first before android pinch zoom will work. Not sure why it is taking so long - hopefully @NickalasB can get it pushed through soon. It contains the following required plugin source code change:

```dart
webView.getSettings().setBuiltInZoomControls(true);
```

**Comment by andyduke** [comment]
@csells Is there any progress with this issue? We are unable to release the app due to the pinch-to-zoom not working.

**Comment by csells** [comment]
@andyduke feel free to follow up with me via email: csells@google.com

**Comment by csells** [comment]
I don't believe we've made any public announcements about this particular feature request. adding @stuartmorgan in case he has any more info.

**Comment by stuartmorgan** [comment]
Fixed by https://github.com/flutter/plugins/pull/3325
