### ISSUE TITLE
App is not x86_64. Running lipo -info:, App is architecture: arm64

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter#48292]
I built my project on a real iOS device and it was working fine but when I tried to run it on the simulator it gives me the below architecture error. 

```
/bin/sh -c /Users/dhavalkansara/Library/Developer/Xcode/DerivedData/Runner-dwtuugielmxutoatpwezjbbcemuy/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh

Non-fat binary /Users/dhavalkansara/Library/Developer/Xcode/DerivedData/Runner-dwtuugielmxutoatpwezjbbcemuy/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App is not x86_64. Running lipo -info:
Non-fat file: /Users/dhavalkansara/Library/Developer/Xcode/DerivedData/Runner-dwtuugielmxutoatpwezjbbcemuy/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App is architecture: arm64
Command /bin/sh failed with exit code 1
```
Also, I have faced the same issue earlier and that time App was working fine for simulator and gave me the similar architecture error for the real device.

```
Non-fat binary /Users/rahul/Library/Developer/Xcode/DerivedData/Runner-gzhbhbitnzivkiavzqqvrwkhtzug/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/App is not arm64. Running lipo -info:
Non-fat file: /Users/rahul/Library/Developer/Xcode/DerivedData/Runner-gzhbhbitnzivkiavzqqvrwkhtzug/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/App is architecture: x86_64
Command /bin/sh failed with exit code 1
```

I tried [#25260](https://github.com/flutter/flutter/issues/25260), [#22749](https://github.com/flutter/flutter/issues/22749), and  [#23917](https://github.com/flutter/flutter/issues/23917) solutions but still facing the same issue.

Flutter Doctor:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A558d, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
[✓] Connected device (3 available)

• No issues found!
```

- Project deployement target version: **11.0**

**Current Xcode Project setting for my target:**

<img width="1011" alt="Screen Shot 2020-01-07 at 3 06 07 PM" src="https://user-images.githubusercontent.com/44993081/71885011-756db680-315f-11ea-81ed-cdcbeda5ee08.png">

**Architecture settings for Pod:**

<img width="1013" alt="Screen Shot 2020-01-07 at 3 09 08 PM" src="https://user-images.githubusercontent.com/44993081/71885134-bbc31580-315f-11ea-97f2-12a3bd0fc3b0.png">

**Comment by iapicca** [comment]
Hi @DhavalRKansara 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by DhavalRKansara** [comment]
@iapicca I have added logs for the `flutter doctor -v `but not able provide you the whole logs for `flutter run --verbose` because it contains too many lines and I am not able to copy-paste those all lines over here.

- flutter doctor -v

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.15 19A582a, locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at /Users/rahul/flutter
    • Framework revision cc949a8e8b (3 months ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rahul/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7761

[✓] Connected device (1 available)
    • iPhone 8 • 9305E1C3-4A6F-45A9-A72B-02A0507BBAD2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
```

**Comment by iapicca** [comment]
Hi again @DhavalRKansara 
it would be useful to see the logs from `flutter run --verbose`
could you please copy paste those in a `.txt` (avoid `.docx`) file and attach it to your post?
thank you

**Comment by DhavalRKansara** [comment]
Okay @iapicca 
I have attached a text file for `flutter run --verbose.`
[flutterRunVerboseLog.txt](https://github.com/flutter/flutter/files/4030869/flutterRunVerboseLog.txt)

**Comment by jmagman** [comment]
What exact command are you running?  Those logs say "Could not build the precompiled application for the device."

**Comment by DhavalRKansara** [comment]
> What exact command are you running? Those logs say "Could not build the precompiled application for the device."

I ran `Flutter run --verbose.`

**Comment by jmagman** [comment]
I don't see your original architecture not found error message in those logs.  The failures are related to duplicate GoogleUtilities symbols being found.  
```
                    In file included from /Users/dhavalkansara/Flutter Development/my-doses-new/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:18:
                    /Users/dhavalkansara/Flutter Development/my-doses-new/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/Private/GULReachabilityChecker.h:22:3: error: redefinition of enumerator 'kGULReachabilityUnknown'
                      kGULReachabilityUnknown,  ///< Have not yet checked or been notified whether host is reachable.
                      ^
                    In file included from /Users/dhavalkansara/Flutter Development/my-doses-new/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:17:
                    In file included from /Users/dhavalkansara/Flutter Development/my-doses-new/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker+Internal.h:17:
                    /Users/dhavalkansara/Flutter Development/my-doses-new/build/ios/Debug-iphoneos/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULReachabilityChecker.h:22:3: note: previous definition is here
                      kGULReachabilityUnknown,  ///< Have not yet checked or been notified whether host is reachable.
                      ^
```
Are you able to repro your original `App is not x86_64` issue with `flutter run --verbose`?

**Comment by DhavalRKansara** [comment]
I am closing this issue because I am not sure about the actual reason behind this issue. I just deleted the project and Xcode's derived data from my system and then recloned the same project again and it was working fine in both simulator and real device.

So as per my experience, I am assuming that while running the build in release mode using `flutter run --release` command  or by `changing Xcode > Edit scheme > Run > Release` there might be some changes within the default project settings and because of that I was getting "` Could not build the precompiled application for the device."` this error.

**Comment by mbeloded** [comment]
> I am closing this issue because I am not sure about the actual reason behind this issue. I just deleted the project and Xcode's derived data from my system and then recloned the same project again and it was working fine in both simulator and real device.
> 
> So as per my experience, I am assuming that while running the build in release mode using `flutter run --release` command or by `changing Xcode > Edit scheme > Run > Release` there might be some changes within the default project settings and because of that I was getting "` Could not build the precompiled application for the device."` this error.

Thank you, only this way helped to solve these horrible issues.
