### ISSUE TITLE
RefreshIndicator does not work if content does not overflow

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4829]
## Steps to Reproduce

1. Update _items in OverscrollDemoState within overscroll_demo.dart of flutter_gallery to only have 2 items. This prevents the content from overflowing.
2. flutter run
3. Components -> Overscroll
4. Attempt to trigger the refresh by scrolling up (move finger down)
5. Observe the refresh indicator does not appear.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision e0f37027ab (5 days ago), engine revision 71ce354a44

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

## Logs and Crash Reports

No useful logs/crash reports

**Comment by HansMuller** [comment]
I have a fix for this. It should be available later today.

**Comment by drewwarren** [comment]
Thanks for the fast turnaround on these issues! One regression was introduced. See #4846
