### ISSUE TITLE
Problem using Dismissible with background inside a OrientationBuilder

### ISSUE THREAD

**Issue by saidlp** [flutter/flutter#48290]
Hi!
I'm facing a kind of weird problem: some dismissible elements are not working when using a responsive design. I managed to narrow it down, and from what I found, it seems like Dismissible won't work inside an OrientationBuilder WHEN USING A BACKGROUND...
In my code below, the second Dismissible will work, but the first one with the background won't.

```dart
  @override
  Widget build(BuildContext context) {

    return Builder(
        builder: (context) => Scaffold(
            appBar: AppBar(title: Text('TEST')),

            body: OrientationBuilder(builder: (context, orientation) {
               return Column(
                children: [
                  Dismissible(
                    key: Key(DateTime.now().toString()),
                    child: Text("DISMISSIBLE 1"),
                    background: Text("background"),),
                  Dismissible(
                    key: Key(DateTime.now().toString()), 
                    child: Text("DISMISSIBLE 2")),
                ],
              );
            }),
        )
    );
  }
```

now if I do remove the OrientationBuilder, like below, both Dismissibles work like a charm...

```dart
  @override
  Widget build(BuildContext context) {

    return Builder(
        builder: (context) => Scaffold(
            appBar: AppBar(title: Text('TEST')),
            body: Column(
                children: [
                  Dismissible(
                    key: Key(DateTime.now().toString()),
                    child: Text("DISMISSIBLE 1"),
                    background: Text("background"),),
                  Dismissible(
                    key: Key(DateTime.now().toString()), 
                    child: Text("DISMISSIBLE 2")),
                ],
            )
        )
    );
  }
```

Am I missing something big? Any idea what's going on?
Best regards

**Comment by iapicca** [comment]
Hi @saidlp 
I cannot replicate the issue you are describing
[code sample](https://dartpad.dartlang.org/cdbcdaf26414bbcd1f5a1cd853296010),
maybe I'm missing something, could you please provide a full example?
thank you

**Comment by saidlp** [comment]
Hello @iapicca  !
Thank you so much for looking into it.
Here is a full example, I hope it helps replicate. The whole test app is contained in one file, main.dart.
I'm currently replicating the problem on the iPhone 11 Pro Max emulator and on my actual Android LG6, both using Android Studio. Thanks again!
main.dart:


`import 'package:flutter/material.dart';

void main() {
  runApp(TestApp());
}

class TestApp extends StatefulWidget {

  @override
  TestAppState createState() => TestAppState();
}

class TestAppState extends State<TestApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomeTestWidget(),
    );
  }
}

class HomeTestWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return Builder(
      builder: (context) => Scaffold(
        appBar: AppBar(
          title: Text('TEST'),
          actions: <Widget>[
          ]
        ),
        body: OrientationBuilder(builder: (context, orientation) {
          return Column(
            children: [
              Dismissible(
                key: Key(DateTime.now().toString()),
                child: Text("DISMISSIBLE 1"),
                background: Text("background"),),
              Dismissible(
                key: Key(DateTime.now().toString()),
                child: Text("DISMISSIBLE 2")),
            ],
          );
        }),
      )
    );
  }
}
`

**Comment by iapicca** [comment]
Hi @saidlp 
running your code it returns the error
```bash
Error: Duplicate keys found.
If multiple keyed nodes exist as children of another node, they must have unique keys.
Column(direction: vertical, mainAxisAlignment: start, crossAxisAlignment: center) has multiple children with key
```
which makes sense because both widgets has `key: Key(DateTime.now().toString()),`
moreover, try these other changes

```
class HomeTestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => 
  OrientationBuilder(                    ///
      builder: (context, orientation) => ///!!!!! PUT THE OrientationBuilder HERE
  
        Scaffold(
          body: 
          // OrientationBuilder(
          //   builder: (context, orientation) => ///!!!!! INSTEAD OF HERE
            Column( 
              children: [
                Dismissible(
                  key: Key('1'),
                  child: Text("DISMISSIBLE 1"),
                  background: Text("background"),
                ),
                Dismissible(key: Key('2'), child: Text("DISMISSIBLE 2")),
              ],
            ),
        ),
  );
}
```
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by saidlp** [comment]
Thank you @iapicca!
The duplicate key problem was due to me oversimplifying the original code ;)
It seems like moving the OrientationBuilder to its rightful place fixed my Dismissible problem.
Have a great day!
