### ISSUE TITLE
Intent Receiver leaked when running the sample project 'platform_channel'

### ISSUE THREAD

**Issue by rayworks** [flutter/flutter#48293]
> Activity com.example.platformchannel.MainActivity has leaked IntentReceiver com.example.platformchannel.MainActivity$3@dcbbce4 that was originally registered here. Ar
                            e you missing a call to unregisterReceiver()?
                         E  android.app.IntentReceiverLeaked: Activity com.example.platformchannel.MainActivity has leaked IntentReceiver com.example.platformchannel.MainActivity$3@dcbbce4 that
                            was originally registered here. Are you missing a call to unregisterReceiver()?
                         E      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
                         E      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
                         E      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1488)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1461)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
                         E      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
                         E      at com.example.platformchannel.MainActivity$1.onListen(MainActivity.java:40)
                         E      at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
                         E      at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
                         E      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
                         E      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
                         E      at android.os.MessageQueue.nativePollOnce(Native Method)
                         E      at android.os.MessageQueue.next(MessageQueue.java:326)
                         E      at android.os.Looper.loop(Looper.java:165)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6729)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

The above error will be caught if  I exit from current Activity. So in this case, should `MainActivity` do `unregisterReceiver`  explicitly？

**Comment by VladyslavBondarenko** [comment]
Hi @rayworks 

Yes, explicitly. Try to unregister your receiver in the appropriate method of your receiver class.
The complementary method pairs are
```
onCreate - onDestroy
onResume - onPause
onStart  - onStop
```
if you register the receiver in the first one then unregister it in it's ending method.

Does it help to you?
If I understood you incorrectly, please describe your case.
Thank you

**Comment by rayworks** [comment]
@VladyslavBondarenko 
Thanks, I've made a [PR](https://github.com/flutter/flutter/pull/48416) for it.

**Comment by rayworks** [comment]
Hi @VladyslavBondarenko and other direct contributors, any feedback for this PR ?
