### ISSUE TITLE
Material: Slider tick marks misaligend with thumb

### ISSUE THREAD

**Issue by berdroid** [flutter/flutter#48304]
Using large values for track height, thumb diameter and tick marks shows a misalignment of the tick marks with the thumb towards the ends of the track in Material design.

This is caused by a signly improper calculation of the tick mark centers in the `_RenderSlider.paint()` method.

**Comment by berdroid** [comment]
I have created a patch for this issue here:

[patch](https://github.com/berdroid/flutter/commit/bf7450f56ed2b5f3413c4034ba75a6167eeaf241)

**Comment by berdroid** [comment]
Created little pull request #48306

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
This is now fixed after https://github.com/flutter/flutter/pull/52663

set `useV2Slider: true`

**Comment by shanewaz-abbas** [comment]
@clocksmith How do I use this in stable?
