### ISSUE TITLE
how set bottom navigation bar color transparent like phone x?

### ISSUE THREAD

**Issue by mitesh77** [flutter/flutter#48300]
now I am running the latest stable 1.12.13+hotfix.5

I need complete fullscreen as I phone in an android flutter.

![Screenshot_20200107-201639](https://user-images.githubusercontent.com/38649435/71904922-12931400-318d-11ea-851f-93c00404f28d.png)
*******************************************************************************************
![2-1-min-1 (2)](https://user-images.githubusercontent.com/38649435/71905043-571eaf80-318d-11ea-8b1d-a47e83abf426.jpg)

it is possible in flutter?
we can show a lot of the app such as an android setting app, contacts, etc.....
![Screenshot_20200107-203849](https://user-images.githubusercontent.com/38649435/71905505-491d5e80-318e-11ea-9db5-ebdf28cb530b.png)

**Comment by dnfield** [comment]
This is a better question for StackOverflow or another forum.  This is not a bug or feature request for this repository.

As a hint, you'll want to look into safe area handling in Flutter.  Many widgets have ways of removing or respecting safe area insets.
