### ISSUE TITLE
Dropdown error

### ISSUE THREAD

**Issue by amjad07** [flutter/flutter#48310]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies: [_LocalizationsScope-[GlobalKey#1514b], _InheritedTheme, MediaQuery]):
There should be exactly one item with [DropdownButton]'s value: . 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Builder file:///E:/flutter/projects/vetapp/lib/pet_data/AddPet.dart:235:45
When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:805:15)
#3      _AddPetState.petWidget.<anonymous closure> (package:vetapp/pet_data/AddPet.dart:330:46)
#4      Builder.build (package:flutter/src/widgets/basic.dart:6757:41)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by dnfield** [comment]
This is an error in  your code - you have set multiple dropdown menu items with the same value.

**Comment by dnfield** [comment]
As for the misleading message you got, see also https://github.com/flutter/flutter/issues/18412
