### ISSUE TITLE
RefreshIndicator should animate out vertically if no refresh is triggered

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4831]
## Steps to Reproduce

Pull down to get the RefreshIndicator to show, but not enough to trigger the refresh(). Now let go. The refresh indicator animates out using scale instead of leaving the viewport from the top. This makes it unclear if the refresh occured or not.

See how gmail on android for how it should work.

**Comment by HansMuller** [comment]
I have a fix for this. It should be available later today.
