### ISSUE TITLE
i try to use .map inside column but its not working

### ISSUE THREAD

**Issue by SushanDristi** [flutter/flutter#48311]
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:hindibhajan/base/baseconnection.dart';
import 'package:hindibhajan/base/model.dart';
import 'package:hindibhajan/base/provider/comment_provider.dart';
import 'package:hindibhajan/base/utilities.dart';
import 'package:html/parser.dart' show parse;
import 'package:provider/provider.dart';

class VideoDetail extends StatefulWidget {
  final Video video;
  const VideoDetail({Key key, this.video}) : super(key: key);
  @override
  _VideoDetailState createState() => _VideoDetailState();
}

class _VideoDetailState extends State<VideoDetail> {
  @override
  Widget build(BuildContext context) {
//    final comment = Provider.of<Comment>(context, listen: false);
//    comment.fetchComment(widget.video.id);
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(70),
        child: AppBar(
          backgroundColor: Color(0xffe5bf97),
          elevation: 0.1,
          centerTitle: true,
          title: Padding(
            padding: const EdgeInsets.only(top: 19.0),
            child: Text(
              widget.video.name,
              style: TextStyle(color: Color(0xffedefef), fontSize: 30),
            ),
          ),
        ),
      ),
      body: SafeArea(
          child: Column(
            children: <Widget>[
              Flexible(
                child: ListView(
                  children: <Widget>[
                    Container(
                      height: 250,
                      width: double.infinity,
                      child: FadeInImage.assetNetwork(
                        placeholder: "assets/images/hindibhajan_icon.png",
                        image: 'https://img.youtube.com/vi/' +
                            widget.video.youtubeId +
                            '/hqdefault.jpg',
                        fit: BoxFit.fill,
                      ),
                    ),
                    VideoDetailLyrics(
                      name: widget.video.name,
                      description: widget.video.description,
                      type: widget.video.type,
                      viewCount: widget.video.viewsCount,
                      commentCount: widget.video.commentCount,
                    ),
                    CommentList(id: widget.video.id),
                  ],
                ),
              ),
            ],
          )),
    );
  }
}

class VideoDetailLyrics extends StatefulWidget {
  final String name;
  final String description;
  final String type;
  final String viewCount;
  final String commentCount;

  const VideoDetailLyrics(
      {Key key,
      this.name,
      this.description,
      this.type,
      this.viewCount,
      this.commentCount})
      : super(key: key);

  @override
  _VideoDetailLyricsState createState() => _VideoDetailLyricsState();
}

class _VideoDetailLyricsState extends State<VideoDetailLyrics> {
  bool showLyric = false;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(
            color: Color(0xffF0E68C),
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                widget.name,
                style: TextStyle(color: Colors.white, fontSize: 16),
                textAlign: TextAlign.justify,
              ),
            ),
          ),
          SizedBox(height: 30),
          Container(
            margin: const EdgeInsets.all(5.0),
            padding: const EdgeInsets.all(5.0),
            decoration:
                BoxDecoration(border: Border.all(color: Color(0xffF0E68C))),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Flexible(
                  flex: 14,
                  child: Center(
                    child: Text(
                      parse(parse(widget.description).body.text)
                          .documentElement
                          .text,
                      style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: Colors.grey),
                      textAlign: TextAlign.center,
                      maxLines: showLyric == false ? 10 : 200,
                    ),
                  ),
                ),
                Flexible(
                  flex: 2,
                  child: InkWell(
                    onTap: () {
                      showLyric = !showLyric;
                      setState(() {});
                    },
                    child: Center(
                      child: Icon(
                        showLyric == false
                            ? Icons.keyboard_arrow_down
                            : Icons.keyboard_arrow_up,
                        color: Color(0xffF0E68C),
                        size: 30,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 5.0, right: 5),
            child: Container(
              color: Color(0xffF0E68C),
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Row(
                      children: <Widget>[
                        Icon(
                          Icons.bookmark,
                          color: Colors.white,
                        ),
                        Text(
                          " " + widget.type,
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    ),
                    Row(
                      children: <Widget>[
                        Icon(
                          Icons.remove_red_eye,
                          color: Colors.white,
                        ),
                        Text(
                          " " + widget.viewCount,
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    ),
                    Row(
                      children: <Widget>[
                        Icon(
                          Icons.message,
                          color: Colors.white,
                        ),
                        Text(
                          " " + widget.commentCount ?? " ",
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    )
                  ],
                ),
              ),
            ),
          ),
          SizedBox(height: 30),
        ],
      ),
    );
  }
}

class CommentList extends StatefulWidget {
  final id;

  CommentList({Key key, this.id}) : super(key: key);

  @override
  _CommentListState createState() => _CommentListState();
}

class _CommentListState extends State<CommentList> {
  Response<String> response;
  bool isLoading = false;
  List commentRes = [];
  Dio dio = new Dio(BaseConnection.options);

  fetchComment(data, id) async {
    isLoading = true;
    response = await dio.post(
      "",
      data: {
        "action": "get_comments",
        "key": "com.videosanjal.hindibhajans-Video-$id"
      },
      options: Options(
          contentType: ContentType.parse("application/x-www-form-urlencoded"),
          headers: {
            "X-Access-Token": Utilities.HEADERS,
          }),
    );
    Map res = await Utilities.decodeJson(response.data);
    commentRes = res["data"];
    data.commentList = commentRes;
    print("this is response${data.commentList}");
    isLoading = false;
    setState(() {});
    print("this is loading ${data.isLoading}");
  }
  List data = ["ok","ok"];

  @override
  void initState() {
    final comment = Provider.of<Comment>(context, listen: false);

    fetchComment(comment, widget.id);
    // TODO: implement initState
    super.initState();
  }

  List<Widget> commentList(comment) {
    List<Widget> data = comment.map((data) => Container()).toList();
    return data;
  }

  @override
  Widget build(BuildContext context) {
    final comment = Provider.of<Comment>(context, listen: false);

    // TODO: implement build
    return isLoading != false
        ? Center(child: CircularProgressIndicator())
        : SingleChildScrollView(
            child: Column(children:
                commentList(data)));

  }
}

**Comment by jonahwilliams** [comment]
"not working" is not enough information to tell whether this is a framework or user error, though I suspect the former. For these sorts of questions, it better to reach out in a channel on flutter.dev/community
