### ISSUE TITLE
Mirror scrollPhysics in TextFormField

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#48326]
From an old PR:

> While TextField now has a scrollPhysics property to disable/customize scrolling, TextFormField does not currently expose the property.

This seems like a reasonable change. The PR that first proposed it, #36562, needed tests, and has been closed after a few months without a response. This sounds like a nice change for new contributors. :)

**Comment by mannprerak2** [comment]
Hi @Piinks 
I have added a PR #48342 (with required tests)
