### ISSUE TITLE
mega_gallery benchmark crashes with a GLSurface error

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4832]
[Full log](https://pantheon.corp.google.com/m/cloudstorage/b/flutter-dashboard/o/5dae820c1b7374891f41187d367d4de17424ec59/output.txt).

```
F/flutter : [FATAL:rasterizer_direct.cc(60)] Check failed: surface_. GLSurface required.
```

It looks like it doesn't happen always (only the mega_gallery test fails; other apps run fine)

**Comment by Hixie** [comment]
Does this still happen, and if so, do you have steps to reproduce on a local setup?

**Comment by yjbanov** [comment]
This issue is obsolete. This benchmark no longer exists.
