### ISSUE TITLE
Can I programmatically trigger a RefreshIndicator refresh?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4833]
If a refresh fails I want to show a SnackBar that lets the user "Try Again". I would love to be able to trigger the same RefreshIndicator UI when the "Try Again" action is pressed. Is there a straightforward way to accomplish this?

**Comment by HansMuller** [comment]
You could create a RefreshProgressIndicator and stack it on top of your UI, 1/4 of the way from the top. And you'd need to fade it in/out.  That's pretty painful. 

Perhaps what's needed is a nonInteractive flag for RefreshIndicator. If set, and the RefreshIndicator wasn't already running its callback, it would show the refresh progress indicator, run the refresh callback, and then dismiss the indicator.

Does that sound like what you want?

**Comment by drewwarren** [comment]
Something along those lines. Being new to flutter it's hard for me to know the best way to design the API.

Is there some way to design an API where I could access the RefreshIndicator by key and trigger the refresh?

**Comment by HansMuller** [comment]
Yes, and that's probably a better API. I will try and land a cut at such an API today.

**Comment by drewwarren** [comment]
Thanks for the quick turn around on all of these! :tada:

**Comment by softmarshmallow** [comment]
could you provide code snippet example for future developers reference?
