### ISSUE TITLE
textAlign: TextAlign.justify leaving extra space on the right in arabic text

### ISSUE THREAD

**Issue by ahmaducg** [flutter/flutter#48335]
When using the following widget, with the text, the result shows as the image
```
Text(
  StringRes.ucg_description,
  textDirection: TextDirection.rtl,
  textAlign: TextAlign.justify,
  style: TextStyle(
    fontSize: 16,
    letterSpacing: 0,
  ),                    
)
```

> "تقدم المجموعة المتحدة للاتصالات خدماتها في مجال الإنترنت وتكنولوجيا المعلومات على يد مجموعة من الخبراء والمهندسين المختصين عبر فروعها في كل من الجمهورية العربية السورية والإمارات العربية المتحدة والمملكة المتحدة بالإضافة إلى شبكة من الخوادم الخاصة والموزعة في أكثر من 28 مركز للبيانات حول العالم. وتشمل نشاطات الشركة عدة اختصاصات وهي: النطاقات والاستضافة - الاتصالات - التسويق الالكتروني - التصميم الجرافيكي والعمارة - الشبكات - الاستشارات - التطوير - منتجات ورخص برمجيات في مجال تكنولوجيا المعلومات والاتصالات";

![SmartSelect_20200107-213527](https://user-images.githubusercontent.com/45195295/71923442-b41e6380-3195-11ea-9d02-71a9b54d137b.jpg)

The text leaves a space in the alignment, and there is an extra Letter Spacing

**Comment by GaryQian** [comment]
Related/dupe of https://github.com/flutter/flutter/issues/28700 and https://github.com/flutter/flutter/issues/44449.
Will close this to work on it in the other thread. Thanks for the repro example though!
