### ISSUE TITLE
RefreshIndicator should stay visible while scrolling during refresh()

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4834]
## Steps to Reproduce

Trigger a refresh() of the RefreshIndicator and then scroll down (drag your finger up). The refresh indicator goes away even though the Future from refresh() has not complete. The indicator should stay visible: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B1PhAWhtrRTrUlM4NHN1ei1DS2s/patterns-swipetorefresh-behavior_do_xhdpi_009.webm

**Comment by HansMuller** [comment]
I have a fix for this. It should be available later today.
