### ISSUE TITLE
RefreshIndicator should prevent another refresh until the refresh() Future completes

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4835]
## Steps to Reproduce

Pull down to trigger a refresh. While the refresh is occurring pull down again and the refresh callback is executed again.  This is similar but not an exact duplicate of #4834.

**Comment by HansMuller** [comment]
This was a RefreshIndicator bug/feature but should have been fixed by https://github.com/flutter/flutter/pull/4788

I am not able to reproduce the problem with the current version of Flutter.

**Comment by drewwarren** [comment]
You are correct. The refresh does not get called again however the UI makes it appear like it does.

duplicate of #4834
