### ISSUE TITLE
How can I use a SnackBar within the same widget that declares the Scaffold?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4836]
I have a widget that declares a Scaffold and I want to use a SnackBar. Unfortunately Scaffold.of(context) returns null since I am creating the scaffold in the same build() function that context is passed to. I could work around this by extracting a widget that declares the scaffold but this is an annoyance and the Scaffold feels natural where I currently have it.

Is there a better way to handle this?

**Comment by HansMuller** [comment]
This is essentially the same issue as: https://github.com/flutter/flutter/issues/4581

Here's my two-cents:
> It would be convenient if Scaffold.of(context) would return the Scaffold contained by context if there was no Scaffold ancestor.

**Comment by drewwarren** [comment]
The workarounds suggested are reasonable. Thanks.

**Comment by Hixie** [comment]
The suggested workarounds have been mentioned in some docs. I'm going to close this for now.
