### ISSUE TITLE
[Web] Unimplemented error on extractPath method

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#48386]
I have used **extractPath** method from **PathMetric** to extract sub-paths and to draw a line, but on the web, it throws an unimplemented error. 

**Code Snippet:**
>  
    for (final PathMetric measurePath in source.computeMetrics()) {
      double distance = intialValue;
      bool draw = true;
      while (distance < measurePath.length) {
        final double length = dashArray.next;
        if (draw) {
          path.addPath(measurePath.extractPath(distance, distance + length),
              Offset.zero);
        }
        distance += length;
        draw = !draw;
      }
    }

Use the sample below to replicate the issue. 

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/dashed_line_web-1271151889 

**Steps to reproduce:**

1. Run the sample in an android device, a line with red-colored will be drawn as below.

![Screenshot_20200108-065930](https://user-images.githubusercontent.com/19346074/71957339-78c27a00-3213-11ea-8466-73f4e1140ece.png)

2. Run the sample on the web, the line will not be drawn and on the debugger window, in the chrome browser, it throws an unimplemented error.

**Comment by ferhatb** [comment]
In master now.
