### ISSUE TITLE
How to use the same font as Android system?

### ISSUE THREAD

**Issue by pxc0215** [flutter/flutter#48390]
The Android system font has changed, but flutter app's font not change along with it. How to make them consistent？

**Comment by iapicca** [comment]
Hi @pxc0215 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/48381)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
