### ISSUE TITLE
provide Flutter.framework without bitcode for v1.12.13 stable version

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#48396]
I'm trying to add flutter to existing app by following https://flutter.dev/docs/development/add-to-app.
Existing ios app can't enable bitcode due to some reason, but i found flutter engine is builded with bitcode by default.

i found we can build flutter engine by self, https://github.com/flutter/flutter/wiki/Compiling-the-engine. but it's complicated and the network is a problem that i'm come from china.

it's very important for whose app can't enable bitcode. I'm look forward to that flutter team could provide flutter engine without bitcode. thanks

**Comment by xster** [comment]
cc @dnfield

**Comment by dnfield** [comment]
We do this today to a ios-release-nobitcode path.

I'm not sure we will do it forever.  It's trivial to manually strip out the bitcode yourself (xcrun bitcode_strip -r Flutter.framework), and you don't _need_ to use bitcode even if you have a bitcode enabled framework.

I'll close this but please let me know if that isn't clear or I'm missing something.

**Comment by AlexVincent525** [comment]
Sorry but is there any further instruction or tutorial provided? We've been try this for a whole day and struggled due to our poor network condition.

**Comment by dnfield** [comment]
Which part?

**Comment by zmtzawqlp** [comment]
@dnfield  thanks, I will try it as your suggestion, and we also look forward to the nobitcode version as we are not good at ios.

**Comment by zmtzawqlp** [comment]
> Which part?

i think he means "We do this today to a ios-release-nobitcode path".

**Comment by dnfield** [comment]
You can download the non-bitcode version at:

https://storage.cloud.google.com/flutter_infra/flutter/a50f1ef56a05999bfa97a777cca14fd7a00e8454/ios-release-nobitcode/artifacts.zip

Just replace the hash with the right engine hash that you want.

**Comment by jmagman** [comment]
Note that due to Apple dropping support for bitcode, the default `ios-release` frameworks the tool downloads will be much smaller in the next release and will not contain bitcode.  `ios-release-nobitcode` will no longer be available.  https://github.com/flutter/flutter/issues/107886
