### ISSUE TITLE
Blur effect for translucent bottom nav / toolbars on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4839]
An iOS visual effect.

**Comment by eseidelGoogle** [comment]
Example from news app:
<img width="374" alt="screen shot 2016-07-28 at 2 12 35 pm" src="https://cloud.githubusercontent.com/assets/11857803/17229633/5ff4e232-54cd-11e6-9c4c-6b8f7810264c.png">

**Comment by eseidelGoogle** [comment]
@dragostis has indicated interest in wiring up some fancier visual effects in Flutter.  I'm not sure if this fits his definition of "fancy" but it might be an easy one to do if he ends up doing bottom nav bars.

**Comment by Hixie** [comment]
We technically support this now, though it's wildly untested. @sethladd Can you elaborate on exactly what you would want to see to call this done?

**Comment by sethladd** [comment]
An example in the Gallery would be sufficient. Doesn't have to be a full vignette. Thanks!

(many of our developers use the Gallery to learn how to use Flutter. Putting examples into the Gallery not only makes it easy to demo our capabilities, but also teaches folks how to use the APIs)

Thanks!

**Comment by andreabreu-me** [comment]
@Hixie Can I see some code/documentation how to do it? Thanks

**Comment by Hixie** [comment]
It's not well documented but I would start with this widget: https://docs.flutter.io/flutter/widgets/BackdropFilter-class.html

**Comment by eseidelGoogle** [comment]
I believe we have this now, but I am told it's currentl broken on physical iOS devices (works everywhere else) due to a Skia bug?  @cbracken @chinmaygarde may know more.

**Comment by cbracken** [comment]
Correct. This is done, but currently broken on physical devices. Related bug #10284.

**Comment by xster** [comment]
Closing this for now. Cupertino nav and tab bars do this by default. They're in the gallery Cupertino navigation demo. Follow up bug on the #10284 bug entry. 

Please reopen if the I misunderstood and the original feature request wasn't addressed.
