### ISSUE TITLE
How to Change Flutter repository URL in Android studio

### ISSUE THREAD

**Issue by server2245** [flutter/flutter#48419]
download.flutter.io is blocked at my company network, How can i switch the repository to something like https://dart-pub.mirrors.sjtug.sjtu.edu.cn/ ?. I am using Android Studio

**Comment by iapicca** [comment]
Hi @server2245 
are you located in China?
thank you

**Comment by TahaTesser** [comment]
Hi @server2245 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by liudonghua123** [comment]
I have the same issue, I have network issue for `download.flutter.io` or `storage.googleapis.com/download.flutter.io`, I also read the doc https://flutter.dev/community/china, but there is only `/flutter_infra` in https://storage.flutter-io.cn, `/download.flutter.io` is not mirrored.

Can we provide the https://storage.flutter-io.cn/download.flutter.io mirrored resources or combine `download.flutter.io` with `flutter_infra`?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by liudonghua123** [comment]
Now I see there are some mirrors of `download.flutter.io`, For example https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/ (https://github.com/tuna/issues/issues/789) and https://storage.flutter-io.cn/download.flutter.io .
