### ISSUE TITLE
Shaddows don't render correctly on dark backgrounds

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#48429]
I was trying to reproduce this design made on Adobe XD:

![image](https://user-images.githubusercontent.com/8120472/72004857-11182900-322b-11ea-9e39-cea8592d638b.png)

But on Flutter I get this:

![image](https://user-images.githubusercontent.com/8120472/72004908-28571680-322b-11ea-9819-da69618222a8.png)

As it can be seen, on a dark background the shadows lose its blur effect, becoming a solid color circle.

My code is just a simple `Scaffold` with a `backgroundColor: Color(0xff272727),`, containing a 

```dart
FloatingActionButton(
  onPressed: () {},
  child: Icon(Icons.star, color: Colors.white,),
  backgroundColor: Colors.purple,
),
```

>Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (4 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by VladyslavBondarenko** [comment]
Using current dev `1.20.0-2.0.pre` I can't see anymore the single-color shadow.



<img width="407" alt="Screenshot at Jul 03 13-21-52" src="https://user-images.githubusercontent.com/17024977/86460149-870bd180-bd30-11ea-8f9c-7c8b3dd0cb57.png">
<img width="392" alt="Screenshot at Jul 03 13-22-14" src="https://user-images.githubusercontent.com/17024977/86460154-88d59500-bd30-11ea-931e-56dea1875352.png">

Seems to be fixed, closing.
@feinstein please comment if I'm wrong and I'll reopen
