### ISSUE TITLE
Share package: When sharing to gmail client the subject is replaced with the body 

### ISSUE THREAD

**Issue by StephanCassel** [flutter/flutter#48436]
**iOS Only**
![image](https://user-images.githubusercontent.com/5372762/72012808-df1fba80-325c-11ea-8f9c-195bf86ccc5c.png)

**Comment by VladyslavBondarenko** [comment]
Hi @StephanCassel 
could you please provide your `flutter doctor -v` and specify your Share package version?
Thank you

**Comment by StephanCassel** [comment]
/Users/stephan/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-NO)
    • Flutter version 1.12.13+hotfix.5 at /Users/stephan/development/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2017.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • LYA L29 • LHS7N18A13001240 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by Stephan-Enoro** [comment]
Very sad that the Share ^0.6.3+5 package does not work.

**Comment by StephanCassel** [comment]
I am very sad that the share plugin does not work. I really like to include it in my app.
I wonder how other flutter developer use this package?

![image](https://user-images.githubusercontent.com/5372762/75882458-849c7800-5e21-11ea-8f8a-64df14b8a69f.png)

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-NO)
    • Flutter version 1.12.13+hotfix.8 at /Users/stephan/development/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • LYA L29            • LHS7N18A13001240                         • android-arm64 • Android 10 (API 29)
    • Stephan’s iPad pro • 9bd45e81b7366db827aba7a7ab7d56432329e4cd • ios           • iOS 13.3.1

• No issues found!

**Comment by iapicca** [comment]
Hi @StephanCassel 
could you please provide a reproducible minimal code sample?
Thank you

**Comment by StephanCassel** [comment]
Hi @iapicca,

 Share.share("This will soon be a very large body text and what happen if this text will be displayed on the subject field",
      subject: "This is a small subject",
      sharePositionOrigin: Rect.fromCenter(center: Offset(100, 100), width: 100, height: 100),);

I have tested sharing from other apps and they also place same text on subject and body.
Could the error be Chrome for iOS or iOS itself? On Android it works.

**Comment by gapspt** [comment]
The apple mail app will show the correct subject. Unfortunately the Gmail app will not. This seems to be a Gmail app bug (or missing feature), and I don't think it is possible to fix it on the Flutter side.

**Comment by StephanCassel** [comment]
@gapspt thanks 
Yes, that is the case. I have tested other apps and sharing via GMail also put the body text on the subject field.
