### ISSUE TITLE
Add background execution tests for android_alarm_manager plugin

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#48439]
https://github.com/flutter/plugins/pull/2453 fixes a regression in the android_alarm_manager where a bad ordering of calls prevented callbacks from being executed in the background. We should add tests that ensure this functionality works properly in the future so we don't regress again.

This should be possible when https://github.com/flutter/flutter/issues/38983 is resolved.

cc/ @mklim @Hixie

**Comment by Hixie** [comment]
Since https://github.com/flutter/flutter/issues/47406 is not actually resolved until it is tested, I'm propagating the customer critical labels from that issue to this one.

**Comment by collinjackson** [comment]
I think we might be able to write test for this one using the new package:espresso.

**Comment by bkonyi** [comment]
> I think we might be able to write a test for this one using the new package:espresso.

This is on my radar for next week.

**Comment by collinjackson** [comment]
Update on this, a test is now running locally for Ben and we're working on getting this onto CI.

**Comment by Hixie** [comment]
Just talked to @bkonyi and @collinjackson and Collin said he's going to finish this one. Thanks!

**Comment by collinjackson** [comment]
The issue here is that this app has both Espresso and E2E tests in the same app and they're using different incompatible bindings. Filed https://github.com/flutter/flutter/issues/51781 with potential solutions. I'm going to be working on this next.

To get this test landed, I've put it into its own example app for now.

**Comment by collinjackson** [comment]
It seems like the possibilities are 

- second example app
- land it as a manual test
- wait for #51781 first
