### ISSUE TITLE
TextField Broken last Update

### ISSUE THREAD

**Issue by michael-shields** [flutter/flutter#48441]
Upon updating 2020-01-08, found that the formatting of my apps are broken.  I have traced this back to the DEMO APP, remove all components and added 2 TextFields().  These TextFields by default normally fill the entire parent, but now they only fill 50% and aligned to left side.  I have attached screen shot of the DEMO app with the problem displayed in the attached PNG.  I believe this broke Flutter on the last update this morning.

Regards,
Michael Shields
<img width="527" alt="Flutter_TextField_Error" src="https://user-images.githubusercontent.com/35579717/72015535-ef6d7080-322f-11ea-9159-ac73b6a0fe1c.png">
[Flutter_TextField_Error.pdf]

Code Sample that produced this error.... below: (PDF)

(https://github.com/flutter/flutter/files/4037176/Flutter_TextField_Error.pdf)

Flutter: 1.13.8-pre.53
Engine: Revision f001ea29f1
Dart 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)

**Comment by michael-shields** [comment]
In an attempt to revert back, I changed to the flutter beta channel and my code worked as expected.  Out of curiosity I changed back to the flutter master channel and the error re-appeared.  Switching back to beta channel until this is resolved.

Regards,
MikeL

**Comment by michael-shields** [comment]
Below is the error log which might be of some help



[+2291 ms] ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
[   +1 ms] The following assertion was thrown while dispatching notifications for FocusNode:
[        ] Assertion failed: org-dartlang-app:///packages/flutter/src/rendering/box.dart:1687:12
[        ] hasSize
[        ] "RenderBox was not laid out: RenderEditable#30db6 NEEDS-LAYOUT NEEDS-PAINT"
[   +1 ms] Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] more information in this error message to help you determine and fix the underlying cause.
[        ] In either case, please report this assertion by filing a bug on GitHub:
[        ] https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] When the exception was thrown, this was the stack:
[        ] package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
[        ] package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
[        ] package:flutter/src/rendering/box.dart 1687:12                                        get size
[        ] package:flutter/src/widgets/editable_text.dart 1729:40                                [_updateSizeAndTransform]
[   +1 ms] package:flutter/src/widgets/editable_text.dart 1415:7                                 [_openInputConnection]
[        ] package:flutter/src/widgets/editable_text.dart 1441:7                                 [_openOrCloseInputConnectionIfNeeded]
[        ] package:flutter/src/widgets/editable_text.dart 1707:5                                 [_handleFocusChanged]
[        ] package:flutter/src/foundation/change_notifier.dart 206:23                            notifyListeners
[        ] package:flutter/src/widgets/focus_manager.dart 808:5                                  [_notify]
[        ] package:flutter/src/widgets/focus_manager.dart 1401:11                                [_applyFocusChange]
[        ] package:dart-sdk/lib/async/schedule_microtask.dart 43:11                              _microtaskLoop
[        ] package:dart-sdk/lib/async/schedule_microtask.dart 52:5                               _startMicrotaskLoop
[        ] package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15           <fn>
[        ] The FocusNode sending notification was:
[        ] FocusNode#298e1
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by ferhatb** [comment]
Thanks for stack trace @michael-shields. We should have https://github.com/flutter/engine/pull/15327 land and hopefully have engine roll into flutter shortly after to resolve this.

**Comment by michael-shields** [comment]
Thank you!  look forward to the update.

MikeL

**Comment by michael-shields** [comment]
Updated flutter to 1.13.8-pre.59 this morning and the issue still exists.  Can you re-open this until the problem is solved and confirmed?

**Comment by ferhatb** [comment]
@yjbanov : why did you reopen? The engine roll to master that fixed it was 4 days ago. Please reopen if you can repro.
