### ISSUE TITLE
Add support for time changes in android_alarm_manager

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#48440]
The alarm_manager_plugin currently has no way to update existing alarms after a device time change. See [here](https://stackoverflow.com/questions/19421616/alarmmanager-how-to-schedule-a-daily-alarm-and-deal-with-time-changes) for reference.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager`](https://pub.dev/packages/android_alarm_manager_plus).
