### ISSUE TITLE
First test to start the app

### ISSUE THREAD

**Issue by siraj83** [flutter/flutter#48450]
I/flutter (14071): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#3257e):
I/flutter (14071): If the home property is specified, the routes table cannot include an entry for "/", since it would
I/flutter (14071): be redundant.
I/flutter (14071): 'package:flutter/src/widgets/app.dart':
I/flutter (14071): Failed assertion: line 169 pos 10: 'home == null ||
I/flutter (14071):          !routes.containsKey(Navigator.defaultRouteName)'

**Comment by jonahwilliams** [comment]
>  If the home property is specified, the routes table cannot include an entry for "/", since it would

This error message indicates a bug in your application, not a bug in the flutter framework.
