### ISSUE TITLE
[shared_preferences] Document the prefix necessary for testing.

### ISSUE THREAD

**Issue by dragonfax** [flutter/flutter#48458]
You have the mock interface documented thusly.

`SharedPrefernces.setMockInitialValues (Map<String, dynamic> values);`

Which is great, but the doc doesn't mention that your keys have to begin with the prefix 'flutter.' or they won't be found by the preferences.

Also the work Preferences in your sample code above is mis-spelt.

## Use case

This is what my test code has to look like in order to pass.

```
    SharedPreferences.setMockInitialValues({ "flutter.Prod_JWT_KEY": "key1", "flutter.Prod_USER_ID": "user1" });

    // test prefs mocking
    var prefs = await SharedPreferences.getInstance();
    expect(prefs.getString("Prod_JWT_KEY"), "key1");
```

Note the prefix 'flutter.' added to the keys map.

Its fine if this prefix is needed, but it should be documented. Better yet, modify `setMockInitialValues` to add the prefix to all the keys for you.

**Comment by glazec** [comment]
I don't have this issue under Flutter (Channel master, v1.14.5-pre.39, on Microsoft Windows [Version 10.0.18363.592], locale en-US.

My code is 
```dart
    SharedPreferences.setMockInitialValues({'counter':1});
    var prefs = await SharedPreferences.getInstance();
    expect(prefs.getInt("counter"), 2);
```

**Comment by stuartmorgan** [comment]
> Better yet, modify `setMockInitialValues` to add the prefix to all the keys for you.

It does this; see https://github.com/flutter/plugins/pull/2260. Since that landed several months before this bug was filed, you were presumably testing against an old version.
