### ISSUE TITLE
Remove usage of deprecated FlutterActivity from integration tests

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#48461]
FlutterActivity was deprecated with https://github.com/flutter/engine/pull/15156 and reverted with https://github.com/flutter/engine/pull/15331.  Some integration tests are using this deprecated API, which is writing the warning to stderr, which causes a test failure.

- run_machine_concurrent_hot_reload
- run_release_test

[run_machine_concurrent_hot_reload_945f206_2.log](https://github.com/flutter/engine/files/4038212/run_machine_concurrent_hot_reload_945f206_2.log)

```
2020-01-08T15:23:22.242402: run:stderr: [+22729 ms] Note: /Users/flutter/.cocoon/flutter/dev/integration_tests/ui/android/app/src/main/java/com/yourcompany/integration_ui/MainActivity.java uses or overrides a deprecated API.2020-01-08T15:23:22.242974: 
```

Fix the integration tests, then reinstate the deprecation.

**Comment by jmagman** [comment]
\cc @xster

**Comment by xster** [comment]
@blasten I think a few more go into our repo since we did https://github.com/flutter/flutter/pull/44139, can we remove them?

**Comment by jmagman** [comment]
The following locations `import io.flutter.app.FlutterActivity` instead of `io.flutter.embedding.android.FlutterActivity`.

dev//integration_tests/android_semantics_testing/android/app/src/main/java/com/yourcompany/platforminteraction/MainActivity.java
dev//integration_tests/android_views/android/app/src/main/java/io/flutter/integration/androidviews/MainActivity.java
dev//integration_tests/external_ui/android/app/src/main/java/io/flutter/externalui/MainActivity.java
dev//integration_tests/flavors/android/app/src/main/java/com/yourcompany/flavors/MainActivity.java
dev//integration_tests/flutter_driver_screenshot_test/ios/.symlinks/plugins/device_info/example/android/app/src/main/java/io/flutter/plugins/deviceinfoexample/EmbeddingV1Activity.java
dev//integration_tests/image_loading/android/app/src/main/java/com/yourcompany/platforminteraction/MainActivity.java
dev//integration_tests/platform_interaction/android/app/src/main/java/com/yourcompany/platforminteraction/MainActivity.java
dev//integration_tests/release_smoke_test/android/app/src/main/java/com/example/release_smoke_test/MainActivity.java
dev//integration_tests/ui/android/app/src/main/java/com/yourcompany/integration_ui/MainActivity.java

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/48532

**Comment by jmagman** [comment]
Down to:

dev/integration_tests/android_views/android/app/src/main/java/io/flutter/integration/androidviews/MainActivity.java:import io.flutter.app.FlutterActivity;
dev/integration_tests/external_ui/android/app/src/main/java/io/flutter/externalui/MainActivity.java:import io.flutter.app.FlutterActivity;
dev/integration_tests/flavors/android/app/src/main/java/com/yourcompany/flavors/MainActivity.java:import io.flutter.app.FlutterActivity;
dev/integration_tests/android_semantics_testing/android/app/src/main/java/com/yourcompany/platforminteraction/MainActivity.java:import io.flutter.app.FlutterActivity;
dev/integration_tests/platform_interaction/android/app/src/main/java/com/yourcompany/platforminteraction/MainActivity.java:import io.flutter.app.FlutterActivity;

**Comment by bartekpacia** [comment]
I checked all locations from [the comment above](https://github.com/flutter/flutter/issues/48461#issuecomment-604624952) and none of them import the deprecated `io.flutter.app.FlutterActivity` anymore. From git-blame I see these imports were mostly removed in #61205 and #93566.

Therefore I'm closing this issue as done.
