### ISSUE TITLE
RefreshIndicator only activates when you start scrolling from the top of the scrollable

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4846]
## Steps to Reproduce
1. Go to the overscroll demo of flutter_gallery.
2. Scroll down a little.
3. Scroll up to the top and attempt to trigger the overscroll without lifting up your finger.
4. Observe the overscroll does not appear. This is the bug.
5. Now that you are at the top and have lifted your giner scrolling up again will trigger the overscroll.

**Comment by HansMuller** [comment]
The behavior you're seeing is intentional although I don't know if it's definitively correct.  The idea was that a separate gesture, after the view had been scrolled to the limit, was needed to request a refresh.  On Android, Google Play Newsstand appears to behave this way, GMail does not.

**Comment by drewwarren** [comment]
Gotcha. Instagram/Snapchat also allow the gesture even when not starting from the limit (although they have slightly custom UI's around it). Since we can compare this to other google apps I agree it's okay for now.

**Comment by Hixie** [comment]
I looked at this and decided we should keep this behavior, because otherwise it would trigger when you fling from the bottom, which doesn't seem to reflect user intent.
