### ISSUE TITLE
When I updated it to 1.12.13hotfix5, the ios APP package was several times larger

### ISSUE THREAD

**Issue by bianxiang** [flutter/flutter#48469]
When I updated it to 1.12.13hotfix5, the ios APP package was several times larger

**Comment by bianxiang** [comment]
When I updated it to 1.12.13hotfix5, the ios APP package was several times larger then before

**Comment by iapicca** [comment]
Hi @bianxiang 
please take a look at this [answer](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077)

Closing this issue
if you disagree please write in the comments and I will reopen it
Thank you
