### ISSUE TITLE
[image_picker 0.6.3]  crash in flutter 1.12h5

### ISSUE THREAD

**Issue by saviourdog** [flutter/flutter#48476]
[image_picker 0.6.3]  crash on flutter 1.12h5 after build apk,but debug mode.  or version 0.6.2 work great,
![image](https://user-images.githubusercontent.com/22761043/72050635-93245280-32fc-11ea-906d-f3ac2a69d866.png)

**Comment by iapicca** [comment]
Hi @saviourdog 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by saviourdog** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/cxm/environment/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cxm/environment/androidsdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/cxm/environment/androidsdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • MI 6 • 88eaff4c • android-arm64 • Android 9 (API 28)

• No issues found!



flutter run --verbose .  is  too long

my code is so sample

and I mean  app crash . when  launch,not in  run  image_picker dart code

**Comment by iapicca** [comment]
Hi @saviourdog 
if the output of `flutter run --verbose` is to long for a post
please attach it to the post in a `.txt` file 
(voiding `.docx` and other less safe formats)
thank you

**Comment by KarimMohamed2005** [comment]
https://github.com/flutter/flutter/issues/25862

**Comment by saviourdog** [comment]
> #25862

thanks a lot
