### ISSUE TITLE
Cursor cannot move inside charctors in a textfield

### ISSUE THREAD

**Issue by beiger** [flutter/flutter#48474]
I have this problem:

The cursor cannot move inside of characters when the text is English. It only can be on the left or  right side.
![微信图片_20200109161413](https://user-images.githubusercontent.com/18483100/72050228-9834d200-32fb-11ea-88f9-a3ea178fffeb.jpg)
The cursor can move inside of characters when the text is Chinese. 
![微信图片_20200109161419](https://user-images.githubusercontent.com/18483100/72050256-a84cb180-32fb-11ea-88f5-d09116e58971.jpg)

I can't find a solution to the problem。

**Comment by beiger** [comment]
This is my localizations settings:
<img width="355" alt="1578558140(1)" src="https://user-images.githubusercontent.com/18483100/72050560-6839fe80-32fc-11ea-8cef-f57bc5792a54.png">
<img width="255" alt="1578558173(1)" src="https://user-images.githubusercontent.com/18483100/72050567-6b34ef00-32fc-11ea-8f55-38e983d35ced.png">

**Comment by beiger** [comment]
I find the reason.
`  Widget build(BuildContext context) {`
   ` return MaterialApp(`
   `   title: 'Flutter Demo',`
    `  theme: ThemeData(`
    `    primarySwatch: Colors.blue,`
    `    platform: TargetPlatform.iOS,`
     ` ),`
  `   localizationsDelegates: [`
       ` S.delegate,`
  `    ],`
    ` supportedLocales: S.delegate.supportedLocales,`
   `   home: MyHomePage(title: 'Flutter Demo Home Page'),`
   ` );`
 ` }`
`}`

When I set the platform in the ThemeData, the problem occured. When I remove the platform, the problem does not exist.
Is this a bug?

**Comment by VladyslavBondarenko** [comment]
Hi @beiger 
this is because of https://github.com/flutter/flutter/issues/58638#issuecomment-642271019,
closing since this is not an issue with flutter,
if you disagree please write in the comments and I will reopen it
