### ISSUE TITLE
Finished with error: ProcessException: Permission denied

### ISSUE THREAD

**Issue by ly410726** [flutter/flutter#48478]
我在window电脑上常见的项目 在mac上安卓运行不起来 提示报错信息为
inished with error: ProcessException: Permission denied
  Command: /Users/housongtao/Desktop/svn/flutter_refreshpay/android/gradlew -v
请问怎样解决

**Comment by VladyslavBondarenko** [comment]
Hi @ly410726 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could describe steps to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @ly410726 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
