### ISSUE TITLE
How to do  flutter build apk--release  with build.gradle  in  buildTypes-debug ？

### ISSUE THREAD

**Issue by yuchuan08** [flutter/flutter#48479]
Hello，When I  do command  flutter build apk --target-platform android-arm --release，but I want Android Plugin build in debug（buildTypes debug），anyone help  me？

 @engine-flutter-autoroll

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
