### ISSUE TITLE
[proposal] image_picker - show record button

### ISSUE THREAD

**Issue by OliverNarramore** [flutter/flutter#48485]
I'd like to use camera functionality within my app. I've tried using the camera package but it's too barebones. I would like to use everything that the Image Picker Camera Source package offers, i.e., tap to focus, switch between the front and rear cameras, zoom and toggle flash.

However, the application only works with pictures not videos, but when using the image picker package, I can still see the record button. Is there a way to hide this?

**Comment by darshankawar** [comment]
@OliverNarramore 
The latest `image_picker` plugin comes with `Record` button which offers front and rear camera view, flash toggle, zoom in and out and focus features.
Does that answer your question ? Or do you have specific issue while using the record button of the plugin ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
