### ISSUE TITLE
黑屏问题（Black screen problem）

### ISSUE THREAD

**Issue by secret620** [flutter/flutter#48480]
在模拟器中不会，个人手机会出现黑屏
android 9
加了启动页，启动页到首页中间会出现屏幕出现黑色。

Not in the emulator, and your personal phone will have a black android 9 screen
Add the launch page, the launch page to the home page will appear in the middle of the screen appears black.
![q4ior-vt37j](https://user-images.githubusercontent.com/20069217/72052561-5b1f0e80-3300-11ea-8f51-48a496801354.gif)

**Comment by secret620** [comment]
![q4ior-vt37j](https://user-images.githubusercontent.com/20069217/72052749-b2bd7a00-3300-11ea-8c2e-ddb2dac16e0e.gif)

**Comment by VladyslavBondarenko** [comment]
Hi @secret620 
Is it [flutter demo app](https://gist.github.com/VladyslavBondarenko/b625e0274418ae82e29db5efd8fd3fa2) without any edits?
Could you please provide your `flutter doctor -v`  and specify on which device you can reproduce it?
Thank you

**Comment by secret620** [comment]
> Hi @secret620
> Is it [flutter demo app](https://gist.github.com/VladyslavBondarenko/b625e0274418ae82e29db5efd8fd3fa2) without any edits?
> Could you please provide your `flutter doctor -v` and specify on which device you can reproduce it?
> Thank you
-------------------



[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593

[√] Connected device (1 available)
    • ONEPLUS A6000 • 67cf2b23 • android-arm64 • Android 9 (API 28)

**Comment by secret620** [comment]
> > Hi @secret620
> > Is it [flutter demo app](https://gist.github.com/VladyslavBondarenko/b625e0274418ae82e29db5efd8fd3fa2) without any edits?
> > Could you please provide your `flutter doctor -v` and specify on which device you can reproduce it?
> > Thank you
> 
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
> • Flutter version 1.12.13+hotfix.5
> • Framework revision [27321eb](https://github.com/flutter/flutter/commit/27321ebbad34b0a3fafe99fac037102196d655ff) (4 weeks ago), 2019-12-10 18:15:01 -0800
> • Engine revision 2994f7e1e6
> • Dart version 2.7.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-29, build-tools 29.0.2
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
> • Flutter plugin version 42.1.1
> • Dart plugin version 191.8593
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2019.1)
> • Flutter plugin version 39.0.3
> • Dart plugin version 191.8593
> 
> [√] Connected device (1 available)
> • ONEPLUS A6000 • 67cf2b23 • android-arm64 • Android 9 (API 28)

demo
https://github.com/secret620/sjecf_note

**Comment by secret620** [comment]
> > > Hi @secret620
> > > Is it [flutter demo app](https://gist.github.com/VladyslavBondarenko/b625e0274418ae82e29db5efd8fd3fa2) without any edits?
> > > Could you please provide your `flutter doctor -v` and specify on which device you can reproduce it?
> > > Thank you
> > 
> > 
> > [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
> > • Flutter version 1.12.13+hotfix.5
> > • Framework revision [27321eb](https://github.com/flutter/flutter/commit/27321ebbad34b0a3fafe99fac037102196d655ff) (4 weeks ago), 2019-12-10 18:15:01 -0800
> > • Engine revision 2994f7e1e6
> > • Dart version 2.7.0
> > [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> > • Android NDK location not configured (optional; useful for native profiling support)
> > • Platform android-29, build-tools 29.0.2
> > • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> > • All Android licenses accepted.
> > [√] Android Studio (version 3.5)
> > • Flutter plugin version 42.1.1
> > • Dart plugin version 191.8593
> > • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> > [√] IntelliJ IDEA Ultimate Edition (version 2019.1)
> > • Flutter plugin version 39.0.3
> > • Dart plugin version 191.8593
> > [√] Connected device (1 available)
> > • ONEPLUS A6000 • 67cf2b23 • android-arm64 • Android 9 (API 28)
> 
> demo
> https://github.com/secret620/sjecf_note

lib Contains an mp4

**Comment by iapicca** [comment]
Hi @secret620 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/47582) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
