### ISSUE TITLE
image_picker

### ISSUE THREAD

**Issue by thousandsNight** [flutter/flutter#48493]
why my app-release.apk always crash when used image_picker

**Comment by BarthaBRW** [comment]
Could you please share error logs and/or source code? It's hard to advise without any detail.

**Comment by VladyslavBondarenko** [comment]
Hi @thousandsNight 
Yes, could you also provide your `flutter doctor -v` and specify which `image_picker` version do you use?
Thank you

**Comment by thousandsNight** [comment]
> Could you please share error logs and/or source code? It's hard to advise without any detail.

when i add image_picker(...0.6.2,0.6.3) in the pubspec.yaml, then run 'flutter build apk', and install the release-app.apk to my phone or simulator, but always crash. i could't  see any error logs,because the apk is release apk.
and when i get the apk form 'flutter run --release',  it's ok.

**Comment by BarthaBRW** [comment]
You should run it in your IDE to see logs instead of just building the prod version blindly.

**Comment by VladyslavBondarenko** [comment]
@thousandsNight 
To better address your issue provide please also `flutter run --verbose`
Thank you
