### ISSUE TITLE
[Web]: Some commit after (v1.13.7) introduces web issue that affects some widget sizes

### ISSUE THREAD

**Issue by egorbelibov** [flutter/flutter#48498]
I noticed the issue when I upgraded flutter this morning and toggled **Chrome's Device Toolbar**.

Some widget sizes (only on mobile (I think)) are completely off from what they should be. The weird thing is that it only happens for some of the widgets. 

**i.e.**: The following button has a fixed width, but behaves differently on each version

- (**Latest Commit**) - Flutter engine: **46adf73d5128269ed75572368eb720117d771ca8**

![not_working](https://drive.google.com/uc?export=view&id=1c1jc3R9P-C5kikZ1CMvK58yccA6Ip2UN)

- (**v1.13.7**) - Flutter engine:  **eb139936eb2c17694aba3fd922adfe8a85c5e8df**

![working](https://drive.google.com/uc?export=view&id=1mPKP3cBZultvdWyV_9tS_iUmMECX0kAQ)

**Target Platform:** Web
**Target OS version/browser:** Version 79.0.3945.88
**Devices:** Mac

**Comment by VladyslavBondarenko** [comment]
Hi @egorbelibov 
To better address this issue could you provide a code sample (to specify which widgets behaves incorrectly)?
Thank you

**Comment by egorbelibov** [comment]
@VladyslavBondarenko
Yes, of course.

Also, I think I found out what's causing it. 
Looks like this happens whenever a **borderRadius** is added to any widget.

### Runnable Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            TroublesomeContainer(),
          ],
        ),
      ),
    );
  }
}

/// ISSUE present in this container.
class TroublesomeContainer extends StatelessWidget {
  Widget build(BuildContext context) {
    return _renderButton(context);
  }

  Widget _renderButton(BuildContext context) {
    return Container(
      height: 50,
      width: 300,
      decoration: BoxDecoration(
        color: Color(0xFF000000),
        // ISSUE seems like it's caused by `borderRadius` param (any border radius value)
        borderRadius: BorderRadius.all(Radius.circular(5)),
      ),
    );
  }
}

``` 

### Screenshots
- When you add any `borderRadius` to `Container` this is what you get:

![image](https://drive.google.com/uc?export=view&id=1OwdymmO48AH_BJr7w8l1mHLPNDZI4Laf)
 
- And when you take it out:

![image](https://drive.google.com/uc?export=view&id=1TD7E8tT9UvFo3Om9BiNhKsSt-irb130Y)

It's **very weird** 🧐

**Comment by ferhatb** [comment]
Issue is fixed in https://github.com/flutter/engine/pull/15327. Will be available as soon as new engine rolls into flutter master.
