### ISSUE TITLE
Flutter web don't work well on my MacBook device?

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#48492]
Hy everybody,

at yesterday I could have a Problem with my Flutter web, all Projects I have would be smaller scalled after starting it on WEB only, same Projects works fine on my another Devices like "PCs and Phones", I renstalled my Flutter and Dart sdks, put it still doesn't working here.

Does anyone know how that could be fixed?

**Comment by egorbelibov** [comment]
Same issue as: #48498
As a temporary workaround you can switch to version (`v1.13.7`) or channel `dev`.

**Comment by VladyslavBondarenko** [comment]
Hi @Kassan424kh 
Could you provide your `flutter doctor -v` and minimal code sample to represent your issue?
Thank you

**Comment by Kassan424kh** [comment]
thank you @egorbelibov, it work's now, but why?

**Comment by VladyslavBondarenko** [comment]
@Kassan424kh which version of Flutter did you use when facing this issue?

**Comment by VladyslavBondarenko** [comment]
Thanks @egorbelibov 

@Kassan424kh 
https://github.com/flutter/flutter/issues/48498#issuecomment-572648984

**Comment by Kassan424kh** [comment]
Iused the last of master @VladyslavBondarenko
