### ISSUE TITLE
I'm getting "dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true" while setting the state using setState({});  

### ISSUE THREAD

**Issue by Ramsharma1234** [flutter/flutter#48497]
## Steps to Reproduce

The relevant error-causing widget was: 
  TextFormField-[LabeledGlobalKey<FormState>#58211] file:///C:/Users/app_name/lib/views/login/LoginFragment.dart:10:19
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#d89cc relayoutBoundary=up30
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=379.4, 0.0<=h<=Infinity)
...  size: Size(379.4, 19.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#413c5(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#5a2eb(offset: 0.0, range: 0.0..0.0, viewport: 379.4, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#fdb41, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (((englishLike subhead 2014).merge(blackMountainView subhead)).copyWith).copyWith
    inherit: false
    color: Color(0xdd000000)
    family: Lato_regular
    familyFallback: Lato
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "email"
RenderObject: RenderEditable#d89cc relayoutBoundary=up30
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=379.4, 0.0<=h<=Infinity)
  size: Size(379.4, 19.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#413c5(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#5a2eb(offset: 0.0, range: 0.0..0.0, viewport: 379.4, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#fdb41, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (((englishLike subhead 2014).merge(blackMountainView subhead)).copyWith).copyWith
    inherit: false
    color: Color(0xdd000000)
    family: Lato_regular
    familyFallback: Lato
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by VladyslavBondarenko** [comment]
Hi @Ramsharma1234 
Could you please provide minimal code sample to reproduce your case?
Thank you

Possibly related to [#25396](https://github.com/flutter/flutter/issues/25396)

**Comment by Ramsharma1234** [comment]
Hi @VladyslavBondarenko ,
Thank you for your answer.

I'm using TextFormField, I'm hitting an API and if the credentials are wrong then I'm setting up the state again. Structure of this is as follows:
------------------------------------------------------------
 _TextFormField(
                    key: _passwordFormKey,
                    autovalidate: true,
                    controller: _passwordTextEditingController,
                    obscureText: true,
                    decoration: InputDecoration(
                      errorMaxLines: 3,
                      labelText: AppStrings.LOGIN_USER_PASSWORD_HINT,
                    ),
                    validator: (value) => LoginFormValidators.passwordValidators(value),
                  ),_
------------------------------------------------------------
I'm using two textformfield , the last one is causing error and if i remove second then the first one is causing the same. 
Also, password text disappears and then back after focus.

Please let me know if you need further information.

**Comment by Ramsharma1234** [comment]
Ok, was able to solve it by adding the following at the start of the button's onpressed:

 FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
This removes focus from the last TextFormField being edited and dismisses the keyboard. Would expect this to happen automatically when tapping a button, but apparently...
