### ISSUE TITLE
Flutter with Android Studio, flutter not working except on https

### ISSUE THREAD

**Issue by zionnite** [flutter/flutter#48494]
guess your day is going on well!

Just Formatted my system from windows 8 to windows 10 and i want to quickly dive into flutter, so i start using it, i then download android studio.

I got Git downloaded, Flutter downloaded (and i add the path of the flutter sdk to the user path), I downloaded Android studio and then install flutter and dart plugin.

Everything is working fine, run flutter --version, flutter doctor and it work well.

The Challenge Once i click on the run or debug button in android studio, i do get these error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > dl.google.com
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > jcenter.bintray.com
   > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > dl.google.com
      > Could not resolve io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > jcenter.bintray.com
   > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > download.flutter.io
      > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > dl.google.com
      > Could not resolve io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
               > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

For hours, i tried different approach, i still get the above errors, so i decided to browse the following domain which are present in the error 1) gradle.org 2) flutter.io

behold it was not working, i got This page isn’t working {domain name} didn’t send any data.

But when i add the https:// to the above domain name, it work right in the browser

My Question Now is

How do i add https:// to flutter properties or plugin in android

**Comment by VladyslavBondarenko** [comment]
Hi @zionnite 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated `flutter doctor -v`
Thank you

**Comment by zionnite** [comment]
Thanks, am on that now, let me do as you instructed

**Comment by zionnite** [comment]
Issue still Persist, here is the `flutter doctor -v`

C:\Users\zionnite\AndroidStudioProjects\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\zionnite\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.40.0)
    • VS Code at C:\Users\zionnite\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.

**Comment by zionnite** [comment]
Yes Yes Yes and Yes!

After the long hours spent trying to make things work on android studio with flutter, these below were the things i did and honestly i don't even know which one made it work.

I got some answer from github https://github.com/flutter/flutter/issues/48494 and i downloaded all the android sdk version (ALL) and i restart my system and try it again voila, Flutter Program ran on my emulator.

**Comment by iapicca** [comment]
Hi @zionnite 
I'm glad that you solved the issue
from your doctor I see that the licence is still pending,
don't forget to run `flutter doctor --android-licenses`

given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by JAYAMURUGANJ** [comment]
C:\Users\webde\AndroidStudioProjects\flutter_app>flutter clean

C:\Users\webde\AndroidStudioProjects\flutter_app>flutter run
Launching lib\main.dart on LND AL30 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/arm64_v8a_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
   > Could not resolve io.flutter:x86_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:x86_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
   > Could not resolve io.flutter:x86_64_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect
      > Could not resolve io.flutter:x86_64_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
            > Could not GET 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom'.
               > Connect to download.flutter.io:80 [download.flutter.io/172.217.166.16] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        49.4s
Gradle task assembleDebug failed with exit code 1

C:\Users\webde\AndroidStudioProjects\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (8 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\webde\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • LND AL30 • KFC3Y18521012207 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by lizhuoyuan** [comment]
same issue

**Comment by kokocooler2020** [comment]
Yes, i  solved this issue by command: 'flutter pub cache repair'.
