### ISSUE TITLE
[image_picker][ios] image path is change after update application version 

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#48507]
## Steps to Reproduce
I checked in iPhone(iOS) emulator.

1. use image picker  
```
ImagePicker.pickImage(source: ImageSource.gallery).then((_image){
  print(_image.path);
});
```
2. select image and check image.path
2. add number version in pubspec.yaml ( 1.0.0 -> 1.0.1 )
3. select same image in 2. and check image.path

in my emulator the image path has being changed like this
- before update : /Users/user/Library/Developer/CoreSimulator/Devices/2AAAB012-FACF-4F29-A28D-285ABEAA4FFB/data/Containers/Data/Application/06BF15C9-34F8-4C9B-8EFD-6755B37335DA/tmp/image_picker_130E95AA-86A7-4909-8B3D-A2719704A259-48298-000015C757019416.jpg
- after update : /Users/user/Library/Developer/CoreSimulator/Devices/2AAAB012-FACF-4F29-A28D-285ABEAA4FFB/data/Containers/Data/Application/40EBCCD5-602A-4EA2-AECE-FCAD888DA506/tmp/image_picker_70EF6C82-4A03-45EC-9663-7AAAB6B7B5ED-49406-000016007D01DDC1.jpg

In my application, I save image path to database and show it by list view.
But when I update my application, the path has been changed, so I can't read the same Image.

I think image path is always same ( because android is same ).

Target Platform:
iOS

Target OS version/browser:
iOS 13.3

Devices:
iPhone 11 Pro Max

## Logs

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale ja-JP)
  • Flutter version 1.12.13+hotfix.5 at /Users/user/Desktop/development/flutter
  • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
  • Engine revision 2994f7e1e6
  • Dart version 2.7.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
  • Android SDK at /Users/user/Library/Android/sdk
  • Android NDK location not configured (optional; useful for native profiling support)
  • Platform android-29, build-tools 29.0.2
  • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
  • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 11.3, Build version 11C29
  • CocoaPods version 1.8.4
[✓] Android Studio (version 3.5)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin version 42.1.1
  • Dart plugin version 191.8593
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
[!] Connected device
  ! No devices available
```

**Comment by hatano0x06** [comment]
I think this issue is similar problem
https://github.com/flutter/flutter/issues/23957

**Comment by hatano0x06** [comment]
I resolve myself that using relation path

**Comment by uzumaki258** [comment]
I faced it, Could you please post your solution? I need your help.
Thanks @hatano0x06

**Comment by hatano0x06** [comment]
@uzumaki258 
ok

if you can see the file path in other version, your can now how does it change

previous version file path 
```
path after get image: /private/var/mobile/Containers/Data/Application/6FC924DB-4D50-420F-AE26-389C37A3F63F/tmp/image_picker_6990DBDB-EB4D-489F-B5E8-A5C1A8CAA003-3521-00000391FF88C78F.jpg
getApplicationDocumentsDirectory path: /var/mobile/Containers/Data/Application/6FC924DB-4D50-420F-AE26-389C37A3F63F/Documents
```

current version file path 
```
path after get image : /private/var/mobile/Containers/Data/Application/47EF6330-6C6A-4ECE-82D1-DB2FDCF53EE7/tmp/image_picker_11DC60E6-C1B8-42A4-BA27-3A9BB715BA2E-3528-000003939D6B1DD1.jpg
getApplicationDocumentsDirectory path : /var/mobile/Containers/Data/Application/47EF6330-6C6A-4ECE-82D1-DB2FDCF53EE7/Documents
```

your can see the hash code in image path will change, if you change version.
So, the good way is save the lastast image path split by "/" ( `image_picker_11DC60E6-C1B8-42A4-BA27-3A9BB715BA2E-3528-000003939D6B1DD1.jpg`).
And if you read, create the path from `getApplicationDocumentsDirectory` ( be careful your have to replace some words) and connect the path your save it.

**Comment by uzumaki258** [comment]
> private/var/mobile

Understood, thank you so much
