### ISSUE TITLE
[web]: device not found 

### ISSUE THREAD

**Issue by DSXtreme** [flutter/flutter#48502]
while checking " flutter run -d chrome" android studio showing "No devices found with name or id matching 'chrome' ". while chrome is runnign.

**Comment by egorbelibov** [comment]
Hi @DSXtreme
Can you provide the output of `flutter doctor -v' so that we can have a better context of your issue.
Thank you.

**Comment by VladyslavBondarenko** [comment]
Hi @DSXtreme 
web support [is available only for beta channel](https://flutter.dev/web)
If you use stable or master, please run
`flutter channel beta`
`flutter upgrade`
is it your case?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
