### ISSUE TITLE
Flutter app doesn't update the running code. 

### ISSUE THREAD

**Issue by Yosiwealth** [flutter/flutter#48505]
Hi, please forgive me if I don't use the right terms and words to explain my problem. I'm still a beginner. Thanks. 

I noticed that whenever I make edits to my app code base and run it from android studio after it launches on my connected device, it perfectly adds the newly updated features to the app, so I disconnect my phone from my laptop. But immediately I press the back key on my device(close the app) and launch the app again using the app icon from the phones launcher, it doesn't load with the updated codes anymore, it loads the previous code before the recent update. 

Please what could be wrong, I'm still a beginner with flutter, I'm lost.

**Comment by jonahwilliams** [comment]
Development time changes with hot reload does not modify the underlying APK, it's only stored in memory. In fact, it couldn't change the APK since it must be signed in order to be opened on the phone, and tampering with it would trip the phones security checks
