### ISSUE TITLE
Enable Firebase Crashlytics at runtime

### ISSUE THREAD

**Issue by lschmierer** [flutter/flutter#48523]
## Use case
To be compliant with European privacy laws, we are required to get user consent before transmitting data to Crashlytics.
We want to use Crashlytics as described at https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#enable_opt-in_reporting

This is, however, not possible with the Flutter library at the moment, as `Fabric` is always initialised as soon as the plugin is attached to the engine.

## Proposal
A possible fix would be to wait for the first `MethodCall` to be received by the plugin and initialise`Fabric` after that.
That way a library user can take care to not make any calls to Crashlytics before user consent is given.

**Comment by VladyslavBondarenko** [comment]
Hi @lschmierer 
Your proposal is related to firebase_crashlytics plugin of FlutterFire
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't related to Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
