### ISSUE TITLE
TextField Broken

### ISSUE THREAD

**Issue by michael-shields** [flutter/flutter#48525]
Reported first yesterday on #48441, was quickly assigned and a fix was applied for a ratio on some component in the framework.  Waited for the next release but the issue still exists.  Since first reporting I noticed similar issues from others reporting differently but they look very similar to this issue.  Since this was reported yesterday and subsequently closed, I have resubmitted another report.

-- B R O K E N    T E X T B O X   --

This can be reproduced using the flutter channer master, create a demo project.  Remove the demo counter and replace with a few TextFields() Widgets.  The TextFields will only populate the left 50% of the screen.  

Regards,
Michael Shields

**Comment by yjbanov** [comment]
I'll reopen the original issue. It provides better context.
