### ISSUE TITLE
ChangeNotifier possible unecessary O(N²) complexity

### ISSUE THREAD

**Issue by nythrox** [flutter/flutter#48530]
The change notifier class has a method called notify listeners, this method loops through its listeners and checks to see if the current listener is in the list it's iterating.
This check is redundant and increases the complexity of O (N²) when it could be O (N).
```
   final List<VoidCallback> localListeners = List<VoidCallback>.from(_listeners);
   for (VoidCallback listener in localListeners) {
       if (_listeners.contains(listener))
           listener();
       }
   }
```
The only advantage I believe it brings is that if (in a subscription function) you want to remove another subscription that is before your current subscription in the list, and the removal (canceling of the function) must be immediate and not in the next iteration.
Depending on this functionality is not only unreliable (it relies on the order of subscribers in the list) but it also causes an extra level of complexity O (N²).
I cannot see where this would be used consistently or if it is used at all.

The line causing the problem is `if (_listeners.contains(listener))` (wich is redundant)

```
  void notifyListeners() {
    assert(_debugAssertNotDisposed());
    if (_listeners != null) {
      final List<VoidCallback> localListeners = List<VoidCallback>.from(_listeners);
      for (VoidCallback listener in localListeners) {
        try {
          if (_listeners.contains(listener))
            listener();
        } catch (exception, stack) {
          FlutterError.reportError(FlutterErrorDetails(
            exception: exception,
            stack: stack,
            library: 'foundation library',
            context: ErrorDescription('while dispatching notifications for $runtimeType'),
            informationCollector: () sync* {
              yield DiagnosticsProperty<ChangeNotifier>(
                'The $runtimeType sending notification was',
                this,
                style: DiagnosticsTreeStyle.errorProperty,
              );
            },
          ));
        }
      }
    }
  }
}
```

The fix would simply be removing the `if (_listeners.contains(listener))` check.

**Comment by goderbauer** [comment]
> The only advantage I believe it brings is that if (in a subscription function) you want to remove another subscription that is before your current subscription in the list, and the removal (canceling of the function) must be immediate and not in the next iteration.

This is exactly why we do this and can't remove the complexity.
