### ISSUE TITLE
Multiple commands produce 

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#48537]
Hello!
My project doesn't compile. Giving the following error:
```
Multiple commands produce '/Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-gmpuxtbievpzbtdwjdegzggrhaav/Build/Products/Debug-denox-iphoneos/.app':
1) Target 'Runner' has link command with output '/Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-gmpuxtbievpzbtdwjdegzggrhaav/Build/Products/Debug-denox-iphoneos/.app'
2) Target 'Runner' has create directory command with output '/Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-gmpuxtbievpzbtdwjdegzggrhaav/Build/Products/Debug-denox-iphoneos/.app'
```

- Please, notice that the error is different from https://github.com/flutter/flutter/issues/20685. 
- My project is using the New Build System instead of the Legacy one.
- The problem seem related to the second warning `Target 'Runner' has create directory command with output` but I have no idea what this is.

Can someone give me some help?

**Comment by shinayser** [comment]
I found the solution:

The problem was on my Runner: it was like this:
![image](https://user-images.githubusercontent.com/1146982/72112419-510b0900-331c-11ea-92cf-650664a3b725.png)

I changed to:
![image](https://user-images.githubusercontent.com/1146982/72112447-63854280-331c-11ea-8035-bc558523df6e.png)

**Comment by Rohan-Khanna** [comment]
I'm still having problem

**Comment by Rohan-Khanna** [comment]
![Screenshot 2020-02-28 at 11 43 31 PM](https://user-images.githubusercontent.com/37894450/75574411-3df6f880-5a84-11ea-84f8-4e0637b26a96.png)

It's like this.

**Comment by shinayser** [comment]
In my app I have multiple flavors and schemes, perhaps that really doesn't work for you.

**Comment by guilherme-v** [comment]
In my case, for some reason, Xcode was generating a Product called just `.app` instead of `Runner.app`.

I had to update the `Product name` settings to `Runner` in `Target->Runner->Build Settings->Search for "Product Name"`.
