### ISSUE TITLE
ListView documentation error

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#48533]
The `ListView` docs say:

```dart
///    Using [AutomaticKeepAlive] widgets (inserted by default when
///    [addAutomaticKeepAlives] is true). Instead of unconditionally caching the
///    child element subtree when scrolling off-screen like [KeepAlive],
///    [AutomaticKeepAlive] can let whether to cache the subtree be determined
///    by descendant logic in the subtree.
```

`[AutomaticKeepAlive] can let whether` this sounds weird, maybe there's a `know` missing? Like `cant let know  whether`?

**Comment by VladyslavBondarenko** [comment]
For me it make sense as it is without changing

**Comment by dnfield** [comment]
It's a dangling participle.  Should probably just be something like `[KeepAlive] widgets unconditionally cache the child element subtree when scrolling off-screen.  [AutomaticKeepAlive] widgets allow descendents in the subtree determine whether to cache the subtree.`

If you'd like to open a PR for this it would be welcome.

**Comment by feinstein** [comment]
I just opened it, I chose to just add `know`, as this won't interfere with the rest of the surrounding text.
