### ISSUE TITLE
App terminates immediately on iOS emulator

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#4854]
## Steps to Reproduce

I recently ran flutter upgrade, and my Flutter app runs as expected on an android tablet, but terminates early on the iOS emulator. If I put breakpoints at the beginning of my code, they are never reached-- it appears none of the code is being executed.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 9c0c0225a6 (2 weeks ago), engine revision bb9865538b
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.31

## Logs and Crash Reports

Running lib/main.dart on iPhone 6 Plus...
Xcode project created in /Users/emshack/vanadium/experimental/users/emshack/EmGen/ios/.
CoreSimulatorBridge: Requesting installation of file:///Users/emshack/vanadium/experimental/users/emshack/EmGen/ios/.generated/build/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.testApp";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/emshack/Library/Developer/CoreSimulator/Devices/7AF4AC42-54BC-4134-8069-D5B4EE60297E/data";
	}
syslogd: ASL Sender Statistics
installd: 0x700000094000 -[MIClientConnection _doBackgroundInstallationForPath:withOptions:completion:]: Install of "/Users/emshack/vanadium/experimental/users/emshack/EmGen/ios/.generated/build/Release-iphonesimulator/Runner.app" type Developer (LSInstallType = (null)) requested by CoreSimulatorBridge (pid 2385)
installd: 0x700000094000 -[MIInstaller _extractPackageWithError:]: Did not construct delta; doing full copy for installation.
installd: 0x700000094000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=com.yourcompany.testApp; Version=1, ShortVersion=1.0>
installd: 0x700000094000 -[MIContainer makeContainerLiveReplacingContainer:reason:withError:]: Made container live for com.yourcompany.testApp at /Users/emshack/Library/Developer/CoreSimulator/Devices/7AF4AC42-54BC-4134-8069-D5B4EE60297E/data/Containers/Data/Application/07A5DA0B-1B01-49A8-91AC-A542DEADE31C
installd: 0x700000094000 -[MIContainer makeContainerLiveReplacingContainer:reason:withError:]: Made container live for com.yourcompany.testApp at /Users/emshack/Library/Developer/CoreSimulator/Devices/7AF4AC42-54BC-4134-8069-D5B4EE60297E/data/Containers/Bundle/Application/21FEE06A-ADE1-4FD5-9A48-E23271E5092D
installd: 0x700000094000 -[MIInstaller performInstallationWithError:]: Install Successful; Staging: 0.09s; Waiting: 0.00s; Preflight/Patch: 0.00s, Verifying: 0.00s; Overall: 0.12s
SpringBoard: Installed apps did change.
	Added: {(
	    "com.yourcompany.testApp"
	)}
	Removed: {(
	)}
	Modified: {(
	)}
SpringBoard: throwing out icon because it isn't visible in the model : node=<SBApplicationIcon: 0x7fce08e90c60; nodeID: "com.apple.camera"> com.apple.camera
containermanagerd: 0x700000117000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
lsd: LaunchServices:(called by PID 2385) Identifiers file does not exist, creating file.
containermanagerd: 0x700000117000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
CoreSimulatorBridge: Requesting launch of com.yourcompany.testApp with options: {
	    arguments =     (
	        "--flx=/Users/emshack/vanadium/experimental/users/emshack/EmGen/build/app.flx",
	        "--dart-main=/Users/emshack/vanadium/experimental/users/emshack/EmGen/lib/main.dart",
	        "--packages=/Users/emshack/vanadium/experimental/users/emshack/EmGen/.packages",
	        "--enable-checked-mode",
	        "--start-paused",
	        "--observatory-port=8106"
	    );
	    environment =     {
	    };
	}
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[3581]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[3581]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[3581]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[3581]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[3581]
assertion failed: 15F34 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
Observatory listening on http://127.0.0.1:8106
Application running.
Application finished.

**Comment by abarth** [comment]
I'm seeing this issue locally and am investigating.  For me it happens intermittently.  If I run the app again, sometimes it works.

**Comment by emshack** [comment]
For me it seems to happen every time I run the app.

**Comment by abarth** [comment]
I think i have a fix for this.  I'm going to vet it a bit more before marking this bug closed.

**Comment by abarth** [comment]
Fixed.
