### ISSUE TITLE
How to exit flutter app on ios？

### ISSUE THREAD

**Issue by evansherry** [flutter/flutter#48545]
I tried to use SystemNavigator.pop () to exit the application and return to the desktop.
This works well on android, but not on ios. Can you tell me why?

Related part of the code
```
void back(){
    if(Navigator.canPop(_context)){
      Navigator.pop(_context);
    }else{
      SystemNavigator.pop();
    }
  }
```

flutter-doctor
```
[✓] Flutter (Channel master, v1.13.0, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.4)
```

**Comment by jonahwilliams** [comment]
See https://stackoverflow.com/questions/355168/proper-way-to-exit-iphone-application

"On the iPhone there is no concept of quitting an app. The only action that should cause an app to quit is touching the Home button on the phone, and that's not something developers have access to."

**Comment by evansherry** [comment]
I need to return to the native from the flutter page. Can I only implement MethodChannel by myself?
