### ISSUE TITLE
SliverChildBuilderDelegate should have a separatorBuilder as well

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#48543]
The `SliverChildBuilderDelegate` should match the `ListView.separated` interface, providing the same functionalities as a `ListView` would have.

**Comment by dnfield** [comment]
I'm not entirely sure I agree :)

ListView is a higher level widget, and convenience methods/constructors like `ListView.separated` make sense.  `SliverChildBuilderDelegate` is a bit of a lower level widget. We definitely want to encourage usage of it, but providing and supporting conveniences around it expands the API surface that has to be supported and tested, and it's not like it's all that hard to just feed the delegate a builder that adds separators.

Perhaps a package would be a good option for this? i.e. a Dart package that helped provide conveniences for `SliverChildBuilderDelegate`.

**Comment by dnfield** [comment]
(or even just provided an `IndexedWidgetBuilder` that adds separators every so many elements)

**Comment by feinstein** [comment]
You have a very good point, it's just that I was forced to use a `SliverChildBuilderDelegate`, instead of a `ListView`, just because I wanted more Material Design functionalities on my list (like lifting the App Bar when the list scrolls). And thus I got a more complicated, lower level, API.

Thus, I wished it could be simpler and more user friendly, as if we want just a bit more integration, then we can't use a `ListView` anymore and it's a bit frustrating being trapped between those 2 options. But it's not the end of the world either.

**Comment by goderbauer** [comment]
I am going to close this one with the explanation given in https://github.com/flutter/flutter/issues/48543#issuecomment-572865981.

**Comment by omidraha** [comment]
Related link: [Here](https://stackoverflow.com/a/58176779)
