### ISSUE TITLE
Crash when deleting emoji from TextField. 

### ISSUE THREAD

**Issue by ryanknauer** [flutter/flutter#48544]
## Steps to Reproduce

1. Copy paste any emoji (e.g. 👍) into a TextField
2. Click right arrow key
3. Click delete

Device: Linux (on physical device)
Application: Flutter Desktop App - Google Internal (contact me if more info needed). 

## Logs
The below log is from the Right Arrow click, not the delete click. This is not from the crash itself, but likely causing it:

flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: invalid text selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity:
flutter: TextAffinity.downstream, isDirectional: false)
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:202:7)
flutter: #1      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1588:23)
flutter: #2      RenderEditable._handleSelectionChange (package:flutter/src/rendering/editable.dart:421:7)
flutter: #3      RenderEditable._handleMovement (package:flutter/src/rendering/editable.dart:688:5)
flutter: #4      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:495:7)
flutter: #5      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:528:17)
flutter: #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
flutter: #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
flutter: #12     _invoke3 (dart:ui/hooks.dart:302:10)
flutter: #13     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

Notes: 
The problem seems to be that right arrow key events are incrementing the TextSelection of the text view beyond the length of the string itself. The TextSelection value will keep increase as the right arrow is clicked. This only occurs when there is an emoji pasted in the TextView.

**Comment by VladyslavBondarenko** [comment]
Hi @ryanknauer 
Could you please provide your `flutter doctor -v`?
Thank you

**Comment by ryanknauer** [comment]
[✓] Flutter (Channel google3, vnull, on Linux, locale en_US.UTF-8)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision a3bbdfb23a (6 days ago), 2020-01-03T00:00:00.000
    • Engine revision eb139936eb
    • Dart version 2f57602411

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform Stable, build-tools Stable
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_181-google-v7-272050736-272050736)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

[✓] Google3 (on linux)
    • KVM enabled

! Doctor found issues in 1 category.

**Comment by dnfield** [comment]
I was initially expecting this to be a problem in the text input plugin like we've seen in iOS - we'd let the backing store's cursor position land in the middle of a multi-byte character and then create an invalid UTF-8 string and die.  I think this is actually a bit different - could be a framework bug.

@gspencergoog or @GaryQian might know better.

**Comment by stuartmorgan** [comment]
This is part of #30662. Currently the GLFW text input is extremely minimal; we just did enough to get ASCII working.
