### ISSUE TITLE
[firebase_database] Add web support to plugin

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#48542]
We should add web support to `firebase_database`.

**Comment by ayushs136** [comment]
can you please elaborate the issue?

**Comment by ditman** [comment]
@ayushs136 check the "Flutter Web Plugins" for more details.

**Comment by awazgyawali** [comment]
I have started the process to introduce the support. Is there any guideline or blog post to outline the exact steps that I need to follow.

**Comment by ditman** [comment]
@awazgyawali Thanks!! 

I don't think there's anything written right now, but the rough steps are:

* Extract the common interface used by the plugin to a common package.
  * This also contains the "Method Channel" implementation used by the mobile versions of the plugin.
* Refactor the mobile plugin to use the Method Channel implementation that you created in the step above.
* Add Web support by implementing the same interface in the first step.

You can refer to:

* This PR: https://github.com/FirebaseExtended/flutterfire/pull/1670 (cloud_firestore)
* This other PR: https://github.com/FirebaseExtended/flutterfire/pull/1826 (cloud_functions)
* This doc about the "federated" architecture in general: https://flutter.dev/go/federated-plugins

**Comment by ditman** [comment]
@awazgyawali a new article about how to write plugins with federation has been published by @hterkelsen just now!

You can read it here:
* https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6

Let us know if you need some help to continue with the federation work you've started!

**Comment by awazgyawali** [comment]
Hi @ditman. Thanks for updating this thread with the article. A month back I started the work and have done about 60% of the task but I was not able to make simple decisions as there was no guidelines to continue. As there is a blog now, ill come back to the work I left and try to finish it. I will let you know if I have any questions to make.

**Comment by ditman** [comment]
@awazgyawali thanks!! Also please do check out the other plugins that have been already migrated to web. cloud_firestore had many changes in the last month that might serve as inspiration!

**Comment by namchuai** [comment]
It would be nice if you guys can share the progress of the work :). Thank you for your effort!

**Comment by kormemis** [comment]
is there any updates about web plugin for firebase_database ?

**Comment by YohanWadia** [comment]
Hi guys. I just want to add to some other requests about Firebase RealTime for the Web.... That it would be nice to know the progress... or some kinda way to track the on going updates that you guys are working on.  thanks for all the great work!

**Comment by awazgyawali** [comment]
Hi @ditman  Can you check this comment. https://github.com/FirebaseExtended/flutterfire/pull/1835#issuecomment-625860492

**Comment by ditman** [comment]
@awazgyawali apologies, I missed that notification! Thanks for the effort, I've commented in the PR with next steps. Ping me if I didn't make sense.

**Comment by atreeon** [comment]
Hi, what sort of timeframe are you expecting to complete this by? A month, end of the year, next year?  Thanks!

**Comment by snj07** [comment]
@ditman Could you please let us know when can we expect [this](https://github.com/FirebaseExtended/flutterfire/pull/1835) to be merged?

**Comment by cyanglaz** [comment]
@kroikie Should we move this to the flutterfire repo?

**Comment by YohanWadia** [comment]
Hi guys... just wanted to know how are things looking for our WEB support? Hadn't heard anything for long so thought i would ask

**Comment by ditman** [comment]
Apologies for the radio silence on this issue, here's the latest update from [the PR](https://github.com/FirebaseExtended/flutterfire/pull/1835) linked above:

> @Salakar commented [on Nov. 11th](https://github.com/FirebaseExtended/flutterfire/pull/1835#issuecomment-725438950):
>
>> @Salakar I don't see any status report for Realtime Database on the Flutterfire road map issue #2582. Has the refactor for Realtime database been ditched?
>
> Not ditched, shifted to early next year, as mentioned on the Roadmap we're looping back to polish off the web implementation on all the plugins we reworked for native, so Web is definitely still getting attention.

**Comment by YohanWadia** [comment]
@ditman ... thanks I appreciate the reply. Just wanted to also put in a word- that the RealTimeDb is ALSO, actually used by so many non software programming guys like.. engineers, IOT specialist, security system implementers etc etc... these non programming guys dont follow up with things like Repos, Git, PR threads etc etc... I guess that may be the reason the RealTimeDb priority has been kept to the least from all the Firebase plugins. BUT i would like you and the gang to reconsider this because the RealTimeDb is possibly one of the most used Firebase tools. Especially for its efficiency. Its guys like us who are programmers might jump to Firestore... But still the high transaction work case scenario only works well with the RealTimeDb. Thanks, its just a gentle request to keep this in mind, that the RealTimeDb shouldnt be on least priority :-)

**Comment by YohanWadia** [comment]
Hi guys, any updates? Any news? We're all still eagerly awaiting this. No stress, but if someone could let us know some info... Any info infact :-)

**Comment by geekydiamond** [comment]
Hiya, I'm writing a Flutter book for a major publisher and am including a section on Firebase. I'd like to say in the book that the Firebase plugins support the three main channels of ios, Android and Web.
Would be great to get a status update on realtime db plugin migration. If the update is going to be in the next few months then that's very different to the update being a year or more away.

**Comment by DarshakVasoya** [comment]
@ditman... I am waiting for firebase_database plugin, My whole startup is stuck due to it. I humble request to you to make it complete as soon as possible.  Thank You...

**Comment by kormemis** [comment]
the main roadmap issue is locked to ask anything. the realtime database topic is not even on the list. does anyone inform us about the process. whole project is depend this support :(

**Comment by YohanWadia** [comment]
@kormemis ... I've been following up for close to a year.... And I really wished people understood that the realtime database should be as important as anything else. But I wish I knew what exactly is stalling this? I know too many devs/clients are waiting for this. @ditman ... any info would be appreciated. thanks.

**Comment by shah-xad** [comment]
I have to write 2 different codes every time for phone and web using two different packages [`firebase_database`](https://pub.dev/packages/firebase_database) (Phone) and [`firebase`](https://pub.dev/packages/firebase) (Web) and it's been more than 1 year I am waiting for this issue to be resolved.

**Comment by Toma4205** [comment]
@Salakar @ditman Hi guys,
Is there any update about this issue?
Flutter 2.0 was released and I was wondering if it changes anything with the original roadmap?

(waiting for this plugin for more than a year now ...)

Thanks a lot.

**Comment by ditman** [comment]
My priorities shifted slightly to other plugins and the web engine for the last few months, and haven't had time to look into firebase_database. However, it's not forgotten!

See, for example: https://github.com/FirebaseExtended/flutterfire/pull/2852#issuecomment-823690273

It'll happen!

**Comment by YohanWadia** [comment]
@ditman @Salakar ... thanks for hearing our plea! ;-)
I really request you guys to consider pushing it higher on the Flutter+Firebase priorities only because there are too many developers/engineers whose projects are stuck due to this... Believe me, thats more than the quantity of guys who are following up. I am not alone when I voice my concern of the Realtime Database being relegated to almost a last spot in making our FlutterFire plugins truly multiplatform(including web).
Seriously, Thanks again, We appreciate all you guys are packing into this - but please consider the RealTime DataBase as an equal that needs more hands on deck, incase you guys are over burdened. thanks again! And will await any good news of the build succeeding!

**Comment by deepak786** [comment]
waiting for web support.....

**Comment by geekydiamond** [comment]
Hey guys, trying to plan our business priorities for the next year, and many are predicated on moving some key apps to the web. Currently this plugin is the only blocker to that plan, so it's making it very hard to know whether we should invest in a React offering, move to another Firebase plugin, or wait in hope. Any rough guidance on dates would be very much appreciated.

**Comment by jameslester2004** [comment]
Agree with the comment above. This is our only blocker from releasing a web app. I really appreciate all the work that people put into these plugins, but its a little disheartening this has been dropped. I would be happy to donate to get it moving. I sense there is a lot of demand and others willing to do the same. Thanks

**Comment by YohanWadia** [comment]
@jameslester2004 ... the real disheartening part is that the professionals who guide our development believe in a fallacy that, **"The Realtime Firebase Db is of least importance"** . Whats also disheartening is that we dont have a single shred of information of whats the real status. Im quite taken aback by the way it has been handled. Especially from the choice of it being relegated to the least bit of importance... to ... a delayed time line.... to... pausing it due to null safety for other packages... etc etc.
 And now its just a void. All the other packages had constant updates and they kept everyone in the loop. I really hope they can just get this over and done with cause honestly most of my clients have lost interest.

**Comment by awazgyawali** [comment]
I was the author of this [PR](https://github.com/FirebaseExtended/flutterfire/pull/1835), which was trying to bring the web support on the plugin. 

Bad luck to us that the PR came in the times when the flutterfire plugin was going on a very massive refactoring process. Core team didn't have the time to merge or even review the PR.

However as per [this](https://github.com/FirebaseExtended/flutterfire/pull/1835#issuecomment-827475385) comment, seems the team is now open to receive PR's on this topic.

I'll try to find some time and start getting into it again. Also, If anybody is interested to contribute, please let me know. Let get this one done!!!!!

**Comment by Rothanan** [comment]
Hey, I'm in desperate need of this for web, unfortunately I do not have the skills to contribute to the project. Any ETA?

**Comment by geekydiamond** [comment]
> I was the author of this [PR](https://github.com/FirebaseExtended/flutterfire/pull/1835), which was trying to bring the web support on the plugin.
> 
> Bad luck to us that the PR came in the times when the flutterfire plugin was going on a very massive refactoring process. Core team didn't have the time to merge or even review the PR.
> 
> However as per [this](https://github.com/FirebaseExtended/flutterfire/pull/1835#issuecomment-827475385) comment, seems the team is now open to receive PR's on this topic.
> 
> I'll try to find some time and start getting into it again. Also, If anybody is interested to contribute, please let me know. Let get this one done!!!!!

If you take the lead, I'm happy to (try to) help where I can...

**Comment by kormemis** [comment]
I will pay 1000 $ worth bitcoin who will publish firebase realtime database web PR without any bug !! consider this

**Comment by deepak786** [comment]
I have created a separated package firebase_database_platform_interface and submitted the pull request https://github.com/FirebaseExtended/flutterfire/pull/6668

**Comment by jameslester2004** [comment]
How did it go @deepak786 ? Really appreciate you taking the time to do this.

**Comment by deepak786** [comment]
@jameslester2004 according to the comment https://github.com/FirebaseExtended/flutterfire/pull/1835#issuecomment-827475385, the team is looking for the PR which will improve the integration test first.

Then they will proceed further to have separated intercom_flutter_platform_interface.

I have submitted the pull request which will separate the intercom_flutter_platform_interface.

So I will try to improve the integration tests.

**Comment by deepak786** [comment]
Another PR https://github.com/FirebaseExtended/flutterfire/pull/6868 submitted to improve the integration tests.

1. PR https://github.com/FirebaseExtended/flutterfire/pull/6868 (to improve the integration tests)
2. PR https://github.com/FirebaseExtended/flutterfire/pull/6668 (to create a separate platform interface)

**Comment by jameslester2004** [comment]
Great job Deepak. Really appreciate your efforts!

**Comment by deepak786** [comment]
Yay, both the PRs are merged.

Now I can proceed with the web implementation.

if anyone wants to buy me a coffee, please don't hesitate.

<a href="https://www.buymeacoffee.com/deepakdroid" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" width="150px"></a>

**Comment by MrBirb** [comment]
@TahaTesser Should this be closed and let the flutterfire team handle this?

**Comment by deepak786** [comment]
PR https://github.com/FirebaseExtended/flutterfire/pull/6952 is merged also. The web support to the real-time database will be released soon.

**Comment by ditman** [comment]
Thanks for the super hard work @deepak786! You've helped a ton of fellow flutter users with this wonderful contribution!!

**Comment by YohanWadia** [comment]
@deepak786 Thanks a million. You're a legend! ;-)

**Comment by kormemis** [comment]
> Yay, both the PRs are merged.
> 
> Now I can proceed with the web implementation.
> 
> if anyone wants to buy me a coffee, please don't hesitate.
> 
> [<img alt="Buy Me A Coffee" width="150px" src="https://camo.githubusercontent.com/28aae05a0fba45679e8e27d90609601e249b64a5fe30dfef05495de4f4e318d4/68747470733a2f2f63646e2e6275796d6561636f666665652e636f6d2f627574746f6e732f76322f64656661756c742d79656c6c6f772e706e67">](https://www.buymeacoffee.com/deepakdroid)

hello I need your mail address, cannot reach you, could you please share your e-mail or how can I reach you
thanks.

**Comment by deepak786** [comment]
@kormemis you can reach me at er.deepakgoyal786@gmail.com
