### ISSUE TITLE
Can I make the arrow display of Android and IOS consistent

### ISSUE THREAD

**Issue by chenxin04187** [flutter/flutter#48555]
Can I make the arrow display of Android and IOS consistent

**Comment by dnfield** [comment]
This question would be better suited for StackOverflow. It is not a bug in the framework or a feature request.

If you do ask it over there, please provide a minimal and complete reproduction of the case, along with what arrow exactly you're trying to make consistent :)

**Comment by chenxin04187** [comment]
thank you so much!
