### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel plugins.flutter.io/connectivity)

### ISSUE THREAD

**Issue by gianalmada** [flutter/flutter#48551]
i have error like this : 
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel plugins.flutter.io/connectivity)

anyone know how to solve this ??

**Comment by dnfield** [comment]
You forgot to add the connectivity plugin, or you may have modified/corrupted your generated plugin registry file.

Update your pubspec yaml and check if you've modified any files in your android or ios folders.

I'm going to close this - it would be more approrpiate as a stackoverflow question.

**Comment by gianalmada** [comment]
i already add connectivity plugin on my pubspec.yaml
![image](https://user-images.githubusercontent.com/42395245/73901673-1ae28a00-48c6-11ea-9635-fd2c720505a4.png)
and still getting this error:
E/flutter ( 4789): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel plugins.flutter.io/connectivity)
E/flutter ( 4789): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 4789): <asynchronous suspension>
E/flutter ( 4789): #1      Connectivity.checkConnectivity (package:connectivity/connectivity.dart:73:47)
E/flutter ( 4789): <asynchronous suspension>
E/flutter ( 4789): #2      _HomePageState._checkInternetConnectivity (package:tebemarket_shop/Pages/homePage.dart:537:39)
E/flutter ( 4789): <asynchronous suspension>
E/flutter ( 4789): #3      _HomePageState.initState (package:tebemarket_shop/Pages/homePage.dart:561:5)
E/flutter ( 4789): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 4789): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4789): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4789): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4789): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4789): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 4789): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4789): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4789): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4789): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4789): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4789): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4789): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4789): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 4789): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 4789): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4789): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4789): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4789): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 4789): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4789): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4789): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4789): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4789): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4789): #44     ComponentEl

error connectivity is from this line :
![image](https://user-images.githubusercontent.com/42395245/73901739-46657480-48c6-11ea-8637-fa5ba5ebd8a7.png)

and i never modified this package, but still get this error no matter what version of this plugin that i use. i hope you can open this issue again, thank you. sorry for my bad english.

**Comment by threetins** [comment]
I have the same problem. It happens when I do a hot restart.
E/flutter (27017): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method changeSettings on channel lyokone/location)

Do you have a solution yet?
