### ISSUE TITLE
Remove private default parameters.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#48565]
There are several constructors in the Flutter SDK with private defaults.

I'm working on a visual Widget builder that is scraping the Flutter SDK and needs to have access to every default value. Due to several defaults being private I'm not able to use those widgets without unnecessary edge-case handling.

- `_DefaultHeroTag` at material/floating_action_button.dart
- `_defaultHeroTag` (_HeroTag) at cupertino/nav_bar.dart.
- `ForcePressGestureRecognizer._inverseLerp` at gestures/force_press.dart used by ForcePressGestureRecognizer for interpolation
- `_kDefaultSemanticIndexCallback` at widgets/sliver.dart used by SliverChildBuilderDelegate & SliverChildListDelegate & SliverChildListDelegate.fixed for semanticIndexCallback

I see two possible solutions:

1: making each default public.
2: hiding the default so that a `null` would make the widget take on the default.

Edit:
- Rephrased to exclude defaults that can be evaluated to constants in a trivial way and 2 more private defaults added.

**Comment by LongCatIsLooong** [comment]
Could you elaborate on what kind of edge cases you have to deal with because of private default values? 

Relaying @HansMuller's answer, we prefer not to make them public because we don't want them to be part of the public api. It's possible to get the default value by constructing a widget with the parameter omitted, and read the parameter from the corresponding getter. Does that solve your problem?

**Comment by modulovalue** [comment]
_Because most private defaults are compile-time constants made out of public values I've managed to extract their actual value and this issue is no longer about them._

However, there are two places where that isn't possible.


`_DefaultHeroTag at material/floating_action_button.dart`
and
`_defaultHeroTag (_HeroTag) at cupertino/nav_bar.dart`

---

> Could you elaborate on what kind of edge cases you have to deal with because of private default values?

Please take a look at this snippet:
```dart
// pseudocode
class FloatingActionButtonConstruction extends Constructable<Widget> {
  List<Parameter> allParameters = [
    Parameter("key", null),
    ...
    Parameter("heroTag", _DefaultHeroTag()) // private default therefore no identity element available
  ]

  @override
  Widget construct() {
    return FloatingActionButton(
      key: allParameters[0].value,
      ...
      heroTag: allParameters[x].value,
    );
  }
}
```
There is no value that would make FloatingActionButton use the default `heroTag`.



> It's possible to get the default value by constructing a widget with the parameter omitted, and read the parameter from the corresponding getter.

This is the kind of band-aid that I'd like to avoid. Doing that for a few widgets manually might be ok, but I'd like to have a **robust** solution that would make **all** current (and future) Widgets in the Flutter SDK constructable the way I've sketched out above.
This solution starts to become fragile when "_constructing a widget with the parameter omitted_" isn't possible due to unknown required parameters.

> we prefer not to make them public because we don't want them to be part of the public api.

I understand that, but I think there's an argument to be made that using private values for default parameters doesn't make them fully hidden from the user either. If a user wanted for a widget to use a custom value OR the default, they'd have to use a workaround instead of just specifying the default explicitly.


```dart
return FloatingActionButton(
  heroTag: myHeroTag ?? defaultHeroTag, // what is the defaultHeroTag?
);

// Would need to become:
if (myHeroTag != null) {
  return FloatingActionButton(
    heroTag: myHeroTag,
  );
} else {
  return FloatingActionButton();
}

// In contrast to specifying the default explicitly:
CupertinoButton(
  minSize: myValue ?? kMinInteractiveDimensionCupertino,
);

// Or having an implicit default value
CupertinoButton(
  color: myColor,
);
```

**Comment by modulovalue** [comment]
I'm closing this issue as stale
