### ISSUE TITLE
Need an example which makes a phone call

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4856]
@chinmaygarde says that it should be possible via URLLauncher and using a tel:// url, however one customer tried and was not able to get it to work.  We should just provide an example. :)

**Comment by chinmaygarde** [comment]
Did the person try using it on a device? `tel:` URLs don't work on the simulator.

**Comment by chinmaygarde** [comment]
The system also logs why the URL launch failed. In any case, will cook up an example.

**Comment by franklinharper** [comment]
I confirm that  on Android `UrlLauncher.launch('tel:${contact.phone}');` works perfectly.

Thanks Flutter team.

**Comment by Hixie** [comment]
Please make sure `contact.phone` is a phone number before doing that, so that you're not susceptible to an injection attack. :-)

**Comment by franklinharper** [comment]
Thanks for pointing that out!

**Comment by guidezpl** [comment]
Closing as this falls slightly out of scope of the gallery, and https://pub.dev/packages/url_launcher has an example
