### ISSUE TITLE
getFlutterEngine() in FlutterPluginBinding has been deprecated

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/flutter#48570]
`SharedPreferencesPlugin.java` :25 Error:

```
C:\Users\mahdi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: 

warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
```

**Comment by VladyslavBondarenko** [comment]
Hi @MahdiPishguy 
I see there's an [issue](https://github.com/flutter/flutter/issues/44569) addressing the case you described.
https://github.com/flutter/flutter/issues/44070#issuecomment-549947493
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by miroslave-ivan** [comment]
I have same errors with you.
me too
who can help me?
hope good answer.
