### ISSUE TITLE
Tap to home cards regressed from 35 FPS to 17 FPS

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48577]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=43802.

cc @iskakaushik

**Comment by Hixie** [comment]
We're not actively working on this; we understand this is being looked at by Skia/Fuchsia.

**Comment by freiling** [comment]
Just out of curiosity, is there any plan for a generalized solution for avoiding mid-frame shader compilation in Flutter? I understand this probably hits platforms with limited compute resources the hardest, but I would imagine that this is a source of frame drops on every platform that GPU accelerates Skia. We just want to make sure our work to resolve this issue in this narrow case dovetails with any effort to solve it generally. Is this something Flutter team already has a plan for or are we in uncharted territory?

**Comment by kf6gpe** [comment]
cc @liyuqian for @freiling's specific question. He's got some plans he's working on that he can share.

**Comment by liyuqian** [comment]
Thanks @kf6gpe for tagging me! Just replied there.

**Comment by cbracken** [comment]
For triage, this is currently assigned to the Fuchsia folks.

**Comment by Hixie** [comment]
I'm going to close this for now. The long term solution is tracked at https://github.com/flutter/flutter/issues/50613.
