### ISSUE TITLE
Open new page using PageRouteBuilder 

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#48571]
I know we can use below code to navigate to a new page

`Navigator.pushNamed(context, ABC.ROUTE);`

But is it possible to do the same way using PageRouteBuilder?

```
 Navigator.of(context).push(PageRouteBuilder(
                    settings: RouteSettings(name: ABC.ROUTE),
                    opaque: false,
                    pageBuilder: (BuildContext context, _, __) {
                    return ABC();
                    }
                  ));
```

**ABC**

```
class ABC extends StatefulWidget {
  static const ROUTE = '/abc';

  @override
  State<StatefulWidget> createState() => _ABCState();
}

class _ABCState extends State<ABC> {
 
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _abcBloc = Provider.of<ABCBloc>(context);
  }

  @override
  void initState() {
    super.initState();
  }

```

**Error**

> Error: Could not find the correct Provider<ABCBloc> above this ABC Widget
> 
> To fix, please:
> 
>   * Ensure the Provider<ABCBloc> is an ancestor to this ABC Widget
>   * Provide types to Provider<ABCBloc>
>   * Provide types to Consumer<ABCBloc>
>   * Provide types to Provider.of<ABCBloc>()
>   * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
>   * Ensure the correct `context` is being used.

**Comment by VladyslavBondarenko** [comment]
Hi @tony123S 
If you want to use PageRouteBuilder, here is [documentation ](https://flutter.dev/docs/cookbook/animation/page-route-animation)
But if you don't need to animate your route transition, you can simply use [MaterialPageRoute]([documentation])
Does it answers your question?

**Comment by tony123S** [comment]
Hi @VladyslavBondarenko  I actually came from this https://github.com/flutter/flutter/issues/11655#issuecomment-553489463

Stack rebuild when a new page is pushed.I try to add `opaque: false` in `MaterialPageRoute`, but get **The named parameter 'opaque' isn't defined.**

**Comment by jonahwilliams** [comment]
This style of question is better suited for StackOverflow or other support forums. For specific places where you could reach out for help, see flutter.dev/community .

**Comment by tony123S** [comment]
@jonahwilliams  Do you know how to pull from https://github.com/flutter/flutter/pull/44731#issue-340026045 ? 

Sorry I quite new to github.
