### ISSUE TITLE
Add a way for plugins to respond to hot restarts

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#48586]
Plugins sometimes need to reset some state when the engine is hot restarted, e.g the video player needs to clear open videos on a hot restart.
There is no hook for that right now, and plugins end up working around in approximate and fragile ways, e.g: 

https://github.com/flutter/plugins/blob/7af9a1a385fe632d5a8b7b698d8b29e2e997326a/packages/video_player/video_player/lib/video_player.dart#L12

As it is the platform-side code that needs to restart, we can probably just expose some hook through the plugins API. We are currently exposing this to the embeddings through the  OnPreEngineRestart hook.

**Comment by jonahwilliams** [comment]
Isn't this the same as https://github.com/flutter/flutter/issues/10437 ?

**Comment by amirh** [comment]
It is, forgot about it, thanks.

Duplicate of #10437
