### ISSUE TITLE
Best way to access Activity for plugins migrated to android v2 embedding

### ISSUE THREAD

**Issue by zhenqiu1101** [flutter/flutter#48599]
I'm working on the first party plugins migration and have talked with @mehmetf.

When migrating the plugins that need Activity, an activity reference is held in the plugin class instead of the v1 registrar. To make it backward compatible, activity is gotten in the registerWith() for v1. Below are two examples, 
 [LocalAuthPlugin](https://github.com/flutter/plugins/blob/master/packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java)
[FirebaseAnalyticsPlugin](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java)

However, the activity may not be available if the plugin is registered in the background (on application created). Also the activity may get detached and a new activity may be attached later which causes the activity refers to a staled object. 

One possible way to fix this is to keep a registrar object in the plugin class for v1 and access activity (textures as well) lazily. We also need a separate Activity reference for v2. But this leads to complicated code whenever accessing the activity, like 

_registrar != null ? registrar.activity() : activity_v2._

I'm opening this issue to get suggestions of how to fix this. Our first party plugins also have the same problem.

**Comment by mehmetf** [comment]
@matthew-carroll @xster FYI

**Comment by matthew-carroll** [comment]
Hi @zhenqiu1101. In the case of the v2 embedding, `registerWith()` should never be called. In v2, the no-arg constructor for the plugin is invoked, and then the plugin's lifecycle methods are invoked at the appropriate time. Therefore, obtaining a reference to `Activity`s as they come and go should be trivial. Here is where that logic begins in the local_auth plugin:
https://github.com/flutter/plugins/blame/master/packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java#L180

With regard to v1, that embedding was intended to be used within a single `Activity` such that if Flutter is running, so is the `Activity`, and if the `Activity` is running, so is Flutter. Background processing was not a capability that was considered during the original engineering phase. In fact, the ability to orchestrate background processing, and deploy Flutter tactically, were 2 of the major goals of the v2 embedding.

Does this explanation help with your work? If not, can you describe specific moments in your plugin's code where you're unsure of how to proceed?

Thanks.

[Edit: we just spoke offline, but I'm posting this response in case it helps others. @zhenqiu1101 would you mind closing this ticket if you believe you have a good path forward?]

**Comment by zhenqiu1101** [comment]
Thanks for the explanation. It's very clear!

**Comment by KThen** [comment]
I'm glad I found this guide. But perhaps it is best to write a better documentation on how to get the Activity for v2 embedding.

For that, we not just have to implement Activity aware, but has to make sure to not call setMethodCallHandler inside onAttachedToEngine. We have to get a reference to channel, and then only call  setMethodCallHandler inside onAttachedToActivity.

In my case, if I call setMethodCallHandler inside onAttachedToEngine, then onAttachedToActivity will never be called.
