### ISSUE TITLE
using visual studio code and the hot reload not always work

### ISSUE THREAD

**Issue by BothOfUsTogether2** [flutter/flutter#48609]
hello,
i will keep it short, the hot reload often not update and requires to run: flutter clean, and run that again. i have done it more than 4 times since 3 days ago.
this usually happen when i don't touch the emulator or IDE and then come back to change something andit showing me something old.
seldom that this issue happens when i write code.

**Comment by dnfield** [comment]
I'm not sure how to reproduce this issue.

Does this happen with _any_ application, or just one you're working on?  Are the steps to just leave it running for a few days and come back?

Is this an issue when you use the flutter tool CLI, or only VSCode?

**Comment by BothOfUsTogether2** [comment]
I'm working with one. Steps is to code then wait 8 minutes and code and see if UI updated.
I'm not sure if this happens to me only. I didn't experience the flutter CLI so only VSCode.
host: debian 9

**Comment by dnfield** [comment]
This might be better suited for the dart-code repo...  @DanTup

**Comment by DanTup** [comment]
@BothOfUsTogether2 when this happens, do you see a "Reloaded x libraries in x ms" messages in the Debug Console? Can you give an example of a change you made when you see this? There are [some types](https://flutter.dev/docs/development/tools/hot-reload#recent-ui-change-is-excluded) [of changes](https://flutter.dev/docs/development/tools/hot-reload#limitations) that won't hot reload.

And how are you hot reloading from VS Code? Are you using hot-reload-on-save, clicking the lightning bolt icon on the debug toolbar, or running the **Flutter: Hot Reload** command from the palette?
