### ISSUE TITLE
[in_app_purchase] Runtime exception in debug build, deprecation/unsafe warnings in release build

### ISSUE THREAD

**Issue by washed** [flutter/flutter#48603]
I have an issue with the in_app_purchase plugin for flutter. When I try to run my app in debug mode, i get the following exception when calling `InAppPurchaseConnection.instance.isAvailable()`

```
_AssertionError ('package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart': Failed assertion: line 101 pos 12:    '_enablePendingPurchases': enablePendingPurchases() must be called before calling startConnection)
```

When I try to build release, I get these warnings during build:

```
Note: C:\Projects\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_purchase-0.3.0\android\src\main\java\io\flutter\plugins\inapppurchase\InAppPurchasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Projects\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_purchase-0.3.0\android\src\main\java\io\flutter\plugins\inapppurchase\MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

## Steps to Reproduce

1. Depend on `in_app_purchase: ^0.3.0`
2. Try to init the instance:
   ```
   InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;
   available = await _iap.isAvailable();  // <- This throws the exception:
   ```
3. ```
   _AssertionError ('package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart': Failed assertion: line 101 pos 12:    '_enablePendingPurchases': enablePendingPurchases() must be called before calling startConnection)
   ```

Target Platform: Android; emulator as well as physical device.

## Logs

This is the relevant part i get when running with `flutter run --verbose`:

```
[+36843 ms] E/flutter ( 7948): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
'package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart': Failed assertion: line 101 pos 12: '_enablePendingPurchases': enablePendingPurchases() must be
called before calling startConnection
[   +2 ms] E/flutter ( 7948): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
[   +5 ms] E/flutter ( 7948): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
[   +1 ms] E/flutter ( 7948): #2      BillingClient.startConnection (package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart:101:12)
[   +4 ms] E/flutter ( 7948): #3      GooglePlayConnection._connect (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:190:21)
[   +1 ms] E/flutter ( 7948): #4      new GooglePlayConnection._ (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:30:20)
[ +191 ms] E/flutter ( 7948): #5      GooglePlayConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:185:38)
[  +22 ms] E/flutter ( 7948): #6      GooglePlayConnection.instance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:35:47)
[   +1 ms] E/flutter ( 7948): #7      InAppPurchaseConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:260:40)
[   +1 ms] E/flutter ( 7948): #8      InAppPurchaseConnection.instance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:251:50)
```

## `flutter analyze`

Just some info about unused imports I haven't cleaned up.

## `flutter doctor -v`

```

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale de-DE)
• Flutter version 1.12.13+hotfix.5 at C:\Projects\flutter
• Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
• Engine revision 2994f7e1e6
• Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:\Users\Marc\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
• All Android licenses accepted.

[√] Android Studio (version 3.5)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 42.1.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
• VS Code at C:\Users\Marc\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.7.1

[√] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

Any help is greatly appreciated!

**Comment by hlta** [comment]
You have to call InAppPurchaseConnection.enablePendingPurchases(); when starting the app
like this https://github.com/flutter/plugins/blob/fb86d52d76d3f0e79b3f679bb3d0db35de4d55cd/packages/in_app_purchase/example/lib/main.dart#L15

**Comment by dnfield** [comment]
Is the assertion yo'ure getting not clear?  as @hita suggests it's telling you what method you need to call first.

The deprecation warnings should be fixed, but are likely not serious.

**Comment by washed** [comment]
Thank you both for you help, sorry for being so dense. Calling `enablePendingPurchases()` first indeed fixes the issue.

Understood about the deprecation warnings.

I have a suggestion for improving the documentation in this area:
The "Getting Started" section here (https://pub.dev/packages/in_app_purchase) doesn't mention `enablePendingPurchases()` at all, so I assumed the assertion was about an error internal to the library (it also talks about calling `enablePendingPurchases()` before calling `startConnection`, which I never called directly, so I was a bit confused).

I suppose this is due to the recent switch to the new billing API and the docs just haven't caught up yet. I couldn't find anything regarding this behaviour, I suppose I should have looked more at the examples like @hlta linked above.

Thank you all!
