### ISSUE TITLE
How to detect adult content with flutter

### ISSUE THREAD

**Issue by nmnclk** [flutter/flutter#48604]
Im creating a sossial madia app. Users can share photo and text. Its greate but i need to detect adult content and block user.

Do you heve any idea.
How i can detect adult content with flutter?
İs there another way to solve this problem?

**Comment by BothOfUsTogether2** [comment]
hello,

try asking in one of the community https://flutter.dev/community
i recommend slack: https://flutter.dev/community

**Comment by jonahwilliams** [comment]
I agree with @BothOfUsTogether2  , this is not a bug in flutter or an actionable feature request, so it is better suited to one of the above forums

**Comment by nmnclk** [comment]
sorry i deleting
