### ISSUE TITLE
为什么要关闭我的问题?

### ISSUE THREAD

**Issue by MuZiLee** [flutter/flutter#48617]
![image](https://user-images.githubusercontent.com/7467318/72196932-e3afc300-3456-11ea-8a78-ed24d3a2a6dc.png)

**Comment by MuZiLee** [comment]
@huage2580 我一句英文都没有写,你的中文不行怪谷歌翻译不出来,我也服了.
我估计问题被关闭也是你举报的.

**Comment by MuZiLee** [comment]
@iapicca  另外,我的问题都没有解决,刚发上来,为什么要关闭我的问题

**Comment by MuZiLee** [comment]
@iapicca  如果我问题的问题太弱智,也请你告诉我问题的解决办法. 因为我用中文写就关闭?

**Comment by Zheaoli** [comment]
真的是睿智
维护者已经说了，有个类似的 issue 和你的情况类似，为了避免重复 issue 先暂时关闭，如果你觉得不一样在原 issue 下面说明后会 reopen

下次先看看怎么使用 issue 再来提 issue ，英文看不懂的话可以 Google 翻译成中文再看

**Comment by Zheaoli** [comment]
@iapicca please close this issue, this a spam

**Comment by dnfield** [comment]
Please do not file issues asking why issues were closed.  You can always comment on the original closed issue if needed, or file a new issue if you have a new problem.

Also, posting in languages other than English makes it harder for most of this community to assist you.  That becomes doubly true when you post _screenshots_ in a language other than English, where we can't even use a automated translation services to figure out what's going on :)

**Comment by iapicca** [comment]
Hi @MuZiLee please check this [answer](https://github.com/flutter/flutter/issues/48697#issuecomment-573541598)
thank you
