### ISSUE TITLE
[url_launcher] Add new url-schemes to url_launcher

### ISSUE THREAD

**Issue by zxl777** [flutter/flutter#48619]
url-schemes is minecraft://
uri = minecraft://?addExternalServer=V86TEST|v3618.v86.co:3618
I use swift, on the same device, this URL can be called successfully.
Can you add this minecraft:// to url_launche?

```
let url = "minecraft://?addExternalServer=\(serverTitle)|\(serverName):\(serverPort)".urlEncoded()
UIApplication.shared.open(URL(string: url)!, options: [:], completionHandler: nil)

extension String {
	func urlEncoded() -> String {
		let encodeUrlString = self.addingPercentEncoding(withAllowedCharacters:
			.urlQueryAllowed)
		return encodeUrlString ?? ""
	}
	
	func urlDecoded() -> String {
		return self.removingPercentEncoding ?? ""
	}
}
```

**Comment by AngusPei** [comment]
Same expectation

**Comment by stuartmorgan** [comment]
`url_launcher` doesn't whitelist schemes, it hands them off to the OS. If you are having terrible launching a URL that the system supports, please file an issue with details.
