### ISSUE TITLE
video_player in ios show first picture of video

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#48625]
if we only initialize VideoPlayerController, there will be black screen while it show the first frame in android;
I hope it will act the same as android;

**Comment by saigkl** [comment]
Share your code to help other to know what's happening.

**Comment by wanjm** [comment]
just use the code in video_player page https://pub.dev/packages/video_player#-readme-tab- 
thought there is comments which tells to ensure the first frame,  but in fact, it is black in ipad; while it shows the first frame in android; which is what I am asking for;

```
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }
```

**Comment by iapicca** [comment]
Hi @wanjm 
does this [code](https://gist.github.com/iapicca/6f04249f85038411670a8d62e3924a25) represent the issue you are describing?

can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by wanjm** [comment]
yes, the  exactly the same code just changed the url of mp4; anyway it shows first frame in android but black in ipad;
used to be in beta of 1.12.13hotfix6, just upgrade to 1.13.6, still the same;
```
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.13.6 at /opt/google/flutter
    • Framework revision 659dc8129d (2 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/google/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • ANDROID_SDK_ROOT = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • iPad (7)   • 0df605426d41ca3f270a13970baea2f355597d2a • ios            • iOS 13.1.3
    • Chrome     • chrome                                   • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

**Comment by wanjm** [comment]
result of  flutter run --verbose   is attached as it so big;

[a.txt](https://github.com/flutter/flutter/files/4068812/a.txt)

**Comment by wownsdl13** [comment]
same here only in iOS. any updates??

**Comment by ollydixon** [comment]
Seeing the same issue.

**Comment by ollydixon** [comment]
The issue for me was that it was behind an opacity.

So this is broken
```
Opacity(
            opacity: 0.2,
            child: Video..
```

**Comment by febg11** [comment]
If I try to seekTo After the video is initialised then the video (also behind an opacity that is set to 0) just seems to disappear. The second i touch the screen it is shown again..... This is only happening on iOS and not android, its really frustrating and I have spent ages trying to fix it

**Comment by febg11** [comment]
Any updates on this?

**Comment by febg11** [comment]
anything? I need an opacity over my video.

**Comment by C0deZLee** [comment]
Same problem. No fix for a whole year?

**Comment by maheshmnj** [comment]
Hi @wanjm,
There's similar open issue #41156 describing this case, please follow-up in it for further updates as it has been prioritized already. So closing this issue as a duplicate of #41156.
 
If you think this is not the case feel free to write back with relevant details.
