### ISSUE TITLE
New BuildContext.parent property to access widget parent

### ISSUE THREAD

**Issue by remoteportal** [flutter/flutter#48624]
I don't understand Flutter architecture very well, but reading some StackOverflow questions and answers it doesn't seem to be an easy way for child widgets to communicate directly to the state of parent widgets.

## Use case

There are many situations where child widgets need to read/write parent state.

## Proposal

Perhaps add a context.parent property?

**Comment by jonahwilliams** [comment]
Widgets intentionally do not have a reference to their parent. If you find that a child needs to access parent properties, it would be more idiomatic to either pass the data down directly or to pass callbacks (for example, onTap in material buttons).
