### ISSUE TITLE
[web]: can't use web libraries in web plugin

### ISSUE THREAD

**Issue by ryanheise** [flutter/flutter#48639]
The [Flutter Web FAQ](https://flutter.dev/docs/development/platform-integration/web) links to [this guide](https://medium.com/flutter/how-to-write-a-flutter-web-plugin-5e26c689ea1) on how to create a Flutter web plugin, but after following this guide, I am unable to import web plugins. The linter gives `avoid_web_libraries_in_flutter` when importing `dart:html` and I'm getting `uri_does_not_exist` when importing `dart:web_audio`.

According to [this page](https://dart-lang.github.io/linter/lints/avoid_web_libraries_in_flutter.html), web library access is allowed in plugin packages that declare `web` as a supported context.

Here is my `pubspec.yaml`

```yaml
name: projectname
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MyPlugin
        fileName: myplugin.dart
```

I am not sure if putting that `web:` section in there did the trick of declaring web as a supported context.

As per the referenced guide above, the project was created with `flutter create projectname` because there is not yet a template for creating flutter web projects, and I added the various additional declarations to my `pubspec` as per the guide.

The output of `flutter doctor -v` is:

```
flutter doctor -v                                                                                git:master
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.12.13+hotfix.6 at /home/ryan/opt/flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ryan/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/ryan/opt/android-sdk
    • Java binary at: /home/ryan/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.5)
    • Android Studio at /home/ryan/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by ryanheise** [comment]
I can reproduce this with the official `url_launcher` package developed by the Flutter team.

1. Clone the https://github.com/flutter/plugins/ project.
2. cd packages/url_launcher/url_launcher_web
3. run flutter pub get
4. open lib/url_launcher_web.dart in editor
5. The linter highlights the import 'dart:html' line with avoid_web_libraries_in_flutter
6. Adding the import 'dart:web_audio' gives uri_does_not_exist

**Comment by hterkelsen** [comment]
I can't reproduce the problem locally (I am able to edit `url_launcher_web` without analysis warnings). Can you see if the problem persists after doing `flutter pub global activate linter`?

**Comment by ryanheise** [comment]
Yes, the problem still persists after doing that.

**Comment by hterkelsen** [comment]
What editor are you using to edit your Flutter code? Is it configured to use the Flutter Dart SDK? Also just to verify you have the latest `linter` can you please paste the results of `flutter pub global list | grep linter`? Mine is `linter 0.1.109` and I'm not seeing the error with the `dart:html` import.

**Comment by ryanheise** [comment]
My linter version is also 0.1.109.

```
$ flutter pub global list | grep linter                                                                      
linter 0.1.109
```

I upgraded it using `flutter pub global activate linter` as per your earlier comment. I'm using Vim with the analysis server which I launch with:

```
/home/ryan/opt/flutter/bin/cache/dart-sdk/bin/dart /home/ryan/opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
```

But I have also tried it with visual studio code with the flutter extension and I get the same error.

Another data point is that the same error will show up in pana on the live pub.dev site. See for example:

[https://pub.dev/packages/soundpool#-analysis-tab-](https://pub.dev/packages/soundpool#-analysis-tab-)

```dart
line 5 col 8: Target of URI doesn't exist: 'dart:web_audio'.
```

**Comment by ryanheise** [comment]
Note that if I create a project with `stagehand web-simple`, then these web imports become available, but I cannot use them from within a Flutter project.

**Comment by hterkelsen** [comment]
OK. It looks like the issue with `dart:web_audio` is that `dart:html`, `dart:js`, and `dart:js_util` are the only Dart Web SDK libraries that are in the Analyzer SDK for flutter https://github.com/flutter/engine/pull/12435

(Side note: are you no longer seeing a warning about the `dart:html` import?)

What do you think about adding the other web libraries in the Analyzer SDK @devoncarew @jonahwilliams ?

@ryanheise as a workaround you can use [`package:js`](https://pub.dev/packages/js) in your plugin to wrap the Web Audio API.

**Comment by devoncarew** [comment]
> What do you think about adding the other web libraries in the Analyzer SDK @devoncarew @jonahwilliams ?

My suspicion is that we should avoiding adding any more dart: web libraries to the flutter sdk, and instead prefer that those capabilities be accessed via new JS inter-op.

cc @vsmenon @natebosch

**Comment by jonahwilliams** [comment]
What we've done so far is very much a stopgap. I think the next steps are the various Flutter & Dart teams need to formalize a decision here for the long-term

**Comment by natebosch** [comment]
I think we are blocked from disallowing `dart:html` by https://github.com/dart-lang/sdk/issues/39753

**Comment by ryanheise** [comment]
> (Side note: are you no longer seeing a warning about the `dart:html` import?)

I'm still getting the warning for 'dart:html'. I am curious, though, how you're not getting the warning since I would like to use whatever configuration you're using to alleviate the problem. 

> @ryanheise as a workaround you can use [`package:js`](https://pub.dev/packages/js) in your plugin to wrap the Web Audio API.

Since there are Flutter Web plugins published on pub.dev today that actually work using `dart.html` and `dart:web_audio`, wouldn't it be possible to still use these dependencies today? I'm not sure if that would mean just ignoring the linter and foregoing code complete features, and then maybe it would still build well. But if you're not getting any linter warnings on `url_launcher_web`, is there any identifiable difference in your working configuration that I could try out before building my own version of `web_audio`, or any manual patch I can apply to the Flutter build tools as a workaround?

**Comment by hterkelsen** [comment]
@ryanheise I actually have pretty much the same setup as you: I use vim with [`vim-lsc`](https://github.com/natebosch/vim-lsc) and [`vim-lsc-dart`](https://github.com/natebosch/vim-lsc-dart) with the Flutter SDK set to be my default Dart SDK.

I think the reason I wasn't seeing the lint on the `dart:html` import is that in the `flutter/plugins` repo, the `avoid_web_libraries_in_flutter` lint isn't enabled. When I enabled it, I started seeing the lint warning.

To me, it looks like there is a [bug in the `avoid_web_libraries_in_flutter` lint](https://github.com/dart-lang/linter/blob/master/lib/src/rules/avoid_web_libraries_in_flutter.dart#L91) because it is supposed to allow `dart:html` imports in Flutter web plugin projects, but it is checking for:

```yaml
flutter:
  plugin:
    web:
```

in your pubspec, while the correct declaration is:

```yaml
flutter:
  plugin:
    platforms:
      web:
```

I'll file an issue with `linter` to get this fixed.

> wouldn't it be possible to still use these dependencies today?

Yes, while the analyzer/linter are conservative about which Dart SDK libraries you can use, when you actually build and run for web your app has access to all of the web libraries (including `dart:web_audio`) so it will build and run correctly. However, if I was in your position I would still prefer to use `package:js` for the Web Audio APIs rather than `dart:web_audio` because support for web libraries besides `dart:html`, `dart:js`, and `dart:js_util` may be removed.

**Comment by hterkelsen** [comment]
The linter bug has been fixed. If you would like to use web libraries other that `dart:html`, `dart:js`, and `dart:js_util` in Flutter for web, please file another issue just for that so other users who want to use them can find it.

**Comment by ryanheise** [comment]
I've just opened #49849
