### ISSUE TITLE
[web] how to support search text from browser

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#48635]
I guess it's a feature request ?  
Or I miss some widget to do this ?

## Steps to Reproduce

1. Include a list of `Text('some text')` in a widget.
2. After run with `flutter run -d chrome`, it will display in chrome.
3. I try to search the text by chrome's search tool, but not work.

<img width="768" alt="Screen Shot 2020-01-11 at 11 14 55 PM" src="https://user-images.githubusercontent.com/6405390/72206451-1397ae80-34c9-11ea-812b-b4f477e10751.png">

**Target Platform:  Chrome**
**Target OS version/browser:  Chrome 79.0.3945.88 (Official Build) (64-bit)**  
**Devices: Chrome**

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-CN)
    • Flutter version 1.12.13+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by VladyslavBondarenko** [comment]
Hi @jerryzhoujw ,
Hardly it's related to the fact I'm doing it on Windows instead of Mac, but I cannot reproduce your case.
Could you post a code sample?
Thank you

**Comment by jerryzhoujw** [comment]
hi，there’s the example project https://github.com/jerryzhoujw/flutter_web_app_example

**Comment by VladyslavBondarenko** [comment]
Still with the same version of Chrome and Flutter SDK I can't reproduce it on Windows

**Comment by kenthinson** [comment]
I can't repoduct it on my Mac. 

@jerryzhoujw If you try upgrading chrome and using master does it work like mine?

Chrome Version 79.0.3945.117 (Official Build) (64-bit)
```
[✓] Flutter (Channel master, v1.13.9-pre.70, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.9-pre.70 at /Users/kent/Developer/flutter
    • Framework revision ef62092b9b (8 hours ago), 2020-01-13 14:30:37 -0800
    • Engine revision 73d2fb374c
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 32ce9c7872)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jerryzhoujw** [comment]
Strange, I can't reproduce it now. @kenthinson.

**Comment by thetrav** [comment]
I just had an issue that looked like this, however what was happening, is that I was searching for some text in a list built dynamically by List.builder

The element hadn't been constructed yet and therefore was not amenable to browser search.

**Comment by maceip** [comment]
this issue is happening for me right now with flutter web on chrome

<details><summary>flutter doctor -v output</summary>
<p>
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.15.17 at /Users/ryan/Downloads/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 3.6.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.6.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

</p>
</details>



<img width="1032" alt="Screen Shot 2020-03-28 at 8 18 06 PM" src="https://user-images.githubusercontent.com/804368/77839408-46009180-7131-11ea-81da-a8ef640d4c8a.png">


```dart
return ListView.builder(
                  
                  padding: EdgeInsets.all(8.0),
                  itemCount: snapshot.data.documents.length,
                  itemBuilder: (BuildContext context, int index) {
                    DocumentSnapshot document = snapshot.data.documents[index];
                    Map<String, dynamic> task = document.data;
                    return Card(
                      child: ListTile(
                        title: Text(task['name']),
                        subtitle: Text(task['details']),
                        isThreeLine: false,
                        leading: Column( 
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Container(
                              width: 60.0,
                              height: 24.0,
                              decoration: BoxDecoration(
                                color: appColor.colorSecondary,
                                shape: BoxShape.rectangle,
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Center(
                                child: Text(
                                    DateFormat.jm().format(DateTime.parse(task['utc'].toDate().toString())),
                                  style: TextStyle(color: Colors.white),
                                ),
                              ),
                            ),
                            SizedBox(height: 4.0),
                            SizedBox(height: 15, width: 80,
                              child:
                                  Text(
                                    task['geo'],
                                    textAlign: TextAlign.center,
                                    overflow: TextOverflow.ellipsis,
                                    style: TextStyle(fontSize: 12.0),
                                  ),
                            )
                          ],
                        ),
```

**Comment by VladyslavBondarenko** [comment]
Thank you @maceip 
I was trying to make your code sample as minimal as possible to leave reproducing of this search bug and I came to interesting conclusion and opened new issue about it https://github.com/flutter/flutter/issues/53585

**Comment by maceip** [comment]
> Thank you @maceip
> I was trying to make your code sample as minimal as possible to leave reproducing of this search bug and I came to interesting conclusion and opened new issue about it #53585

wow great catch, thanks
