### ISSUE TITLE
ConnectionState always waiting in StreamBuilder

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#48633]
I using Bloc pattern in my flutter project. In MainPage, I will add `List<HashMap<int,ABC>>` into list.

```
 var list = List<HashMap<int, ABC>>();
 var hashMap = HashMap<int, ABC>();
 var groupedList =
        groupBy(listOfAbc, (ABC item) => item.id);  // group by id

     for (var key in groupedList.keys) {
          for (var value in groupedList[key]) {
            if ((value.notification_type == "abc")) {
              setState(() {
                hashMap[key] = value;
                list.add(hashMap);
                _abcBloc.abcSink.add(list);
              });
            }
          }
        }
```
After that I will display the stream in pageB.

  ```
 return StreamBuilder<List<HashMap<int, ABC>>>(
             stream: _abcBloc.abcStream,
             builder: (context, snapshotData) {
             switch (snapshotData.connectionState) {
             case ConnectionState.active:
             return Text(snapshotData.data.toString());
             break;

            case ConnectionState.waiting:
            return Text("Waiting");
            break;

           default:
           return Text("error");
          }
      });

```
If the list is not equal to zero, I can see `Text(snapshotData.data.toString())` display on UI. But if the list is zero, the UI is displayed waiting. How can I fix it? Why it is always in `ConnectionState.waiting`  if there are nothing add into `sink` ?

**Bloc**

```
 final _abc = BehaviorSubject<List<HashMap<int, ABC>>>();
 get abcSink => _abc.sink;
 get abcStream => _abc.stream;
```

**Comment by iapicca** [comment]
Hi @tony123S 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample
that does not involve 3rd party packages
Thank you

**Comment by iampawan** [comment]
Yes that's an issue with me too on Flutter Dev v1.15.2

**Comment by iapicca** [comment]
Hi @iampawan 
can you please provideyour `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @tony123S 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
