### ISSUE TITLE
[web] Discuss: what's the best way to open a detail.

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#48636]
I can write the things as just pages of widgets.
But I would expect better way, since I think it's a normal case in web. 

## Steps to Reproduce

1. Include a list of  content with `IconButton()` in a widget.
2. After run with `flutter run -d chrome`, it will display in chrome.
3. I try to click each button in list to open the detail.

### Expected 2 possible result:
1. Open the detail part in the list part area.
2. Or open the detail with a new tab, but better to share the menu & top part.
     I don't think this is the same case of https://github.com/flutter/flutter/issues/33126.

I can implement to open the detail page combine with menu & top part, but I don't like this way for web.

<img width="666" alt="Screen Shot 2020-01-11 at 11 51 24 PM" src="https://user-images.githubusercontent.com/6405390/72206839-5fe4ed80-34cd-11ea-987f-ee2862c368eb.png">

**Target Platform:  Chrome**
**Target OS version/browser:  Chrome 79.0.3945.88 (Official Build) (64-bit)**  
**Devices: Chrome**

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-CN)
    • Flutter version 1.12.13+hotfix.6 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by jonahwilliams** [comment]
@jerryzhoujw are you talking about opening a new tab/page? Or something like a modal/popup dialog?

**Comment by jerryzhoujw** [comment]
Hi @jonahwilliams 

yes, open in net tab is one way I think good.

Or if it can easy open part of the page to new content would be good too.   

_Because current PageRoute thing will open hole page. which cause shared menu & web top need be in all pages, I don't like it because actually the menu & web top are just navigation function here._

**Comment by jerryzhoujw** [comment]
En,  for open in new tab,  I think I should display a `link`  instead of `button`
 what would be the `Relative URL` in this case, maybe related to universal link things.

For replace part of web content with new content, and actor like open new page in that area,
  I think maybe model/popup dialog would satisfy the case.

**Comment by yjbanov** [comment]
This sounds like a good question for StackOverflow, where you can get better recommendations. It's not something we can fix in Flutter.
