### ISSUE TITLE
[web] BoxShadow is cut off

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#48637]
BoxShadow is cut off on web. Works fine on iOS and Android.

![Bildschirmfoto 2020-01-11 um 17 53 18](https://user-images.githubusercontent.com/38528004/72207656-68bccb80-349b-11ea-8634-fcc67a233c50.png)

## Steps to Reproduce

1. Create new Flutter Web Project
2. Add this code:
```
    return Scaffold(
      body: Padding(
        padding: EdgeInsets.all(16),
        child: Container(
          padding: EdgeInsets.all(16),
          width: MediaQuery.of(context).size.width,
          height: 150,
          decoration: BoxDecoration(
            color: MyColors.backgroundColor1(brightness),
            borderRadius: BorderRadius.all(Radius.circular(10)),
            boxShadow: <BoxShadow>[
              BoxShadow(
                color: Colors.black.withOpacity(0.3),
                blurRadius: 20,
                offset: Offset(2, 3),
              ),
            ],
          ),
        ),
      ),
    );
```

**Target Platform:** Web
**Target OS version/browser:** Chrome version 79.0.3945.117
**Devices:**

## Logs

No Error displayed

**Comment by yjbanov** [comment]
Yes, it's the same as https://github.com/flutter/flutter/issues/32215.
