### ISSUE TITLE
$ANDROID_HOME is required to be an absolute path.

### ISSUE THREAD

**Issue by blemelin** [flutter/flutter#48649]
The ```ANDROID_HOME``` environment variable is required to be an absolute path.

For example :
```bash
#~/.bashrc
export ANDROID_HOME="~/.android-sdk"
```

Running ```flutter doctor``` :
```
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = ~/.android-sdk
      but Android SDK not found at this location.
```

Using an absolute path :
```bash
#~/.bashrc
export ANDROID_HOME="/home/username/.android-sdk"
```

Running ```flutter doctor``` :
```
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/username/.android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/username/.android-sdk
    • ANDROID_SDK_ROOT = ~/.android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
```

* **Version** : Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale fr_CA.UTF-8)
* **OS** : Debian based

*PS : Does this issue follow the contributing guidelines ? Also, didn't find anything useful when searching in existing issues, so I'm posting a new one. Sorry if this is nothing new.*

**Comment by jonahwilliams** [comment]
> PS : Does this issue follow the contributing guidelines ? Also, didn't find anything useful when searching in existing issues, so I'm posting a new one. Sorry if this is nothing new.

FWIW this is great issue submission, thank you for including all of the relevant details too

**Comment by christopherfujino** [comment]
@blemelin I imagine a lot of other command line tools will break if you use `~` for paths in environment variables--`~` is technically a bash expansion (https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html), and command-line tools generally run without a shell parser. Safer would be to use `export ANDROID_HOME="$HOME/.android-sdk"`.

**Comment by blemelin** [comment]
Oh you're right! Completely forgot about that. Just tried it using the `$HOME` variable, and it works as expected.
