### ISSUE TITLE
Flutter Video Player Unable To Play Long video File of About 11 hrs duration. 

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#48656]
I tried playing an mp4 video file, which is a common format supported by this player. Its able to play videos that are not too long. But I have a video which is 11 hrs long. Its unable to load or play that file.
I have other videos too which are 18 hrs long and 21 hrs long, and it won't play either. 

When i was working on xamarin platform, i used to used libvlc (vlc media player)  and that used to play videos of any duration and any format on both ios and android. But now moving here to flutter platform i am facing issues regaring playing long video files and also many formats are not supported like segmented mp4, and other formats wont load. 

How to solve that issue ?

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by premingiet** [comment]
```cmd
Microsoft Windows [Version 10.0.18363.535]
po\flutter_ffmpeg_pipe>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

G:\GitHub\Flutter-Pipe-Repo\flutter_ffmpeg_pipe>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • E • G350RT058157000F • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by maheshmnj** [comment]
> I tried playing an mp4 video file, which is a common format supported by this player. Its able to play videos that are not too long. But I have a video which is 11 hrs long. Its unable to load or play that file.
> I have other videos too which are 18 hrs long and 21 hrs long, and it won't play either.
> 
> When i was working on xamarin platform, i used to used libvlc (vlc media player) and that used to play videos of any duration and any format on both ios and android. But now moving here to flutter platform i am facing issues regaring playing long video files and also many formats are not supported like segmented mp4, and other formats wont load.
> 
> How to solve that issue ?

Hi @premingiet ,
Thanks for filing the issue are you facing this issue while playing video from network, asset or file?
could you please upgrade to latest stable version of the flutter and use  ```video_player: ^2.1.6``` plugin and confirm the issue.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
