### ISSUE TITLE
Shared render_task & platform_task runner description 

### ISSUE THREAD

**Issue by pchampio** [flutter/flutter#48651]
I'm developing an alternative embedder (go-flutter) and we stumble across https://github.com/flutter/flutter/issues/17579. (Crash under sendIndexedMeshToGpu when resizing macOS embedder).

In order to fix this issue, I had to use a thread configuration where the platform and render task runners are the same (https://github.com/flutter/engine/pull/13300).

After implementing this thread config into go-flutter, users reported errors (https://github.com/go-flutter-desktop/go-flutter/issues/326). It seems that sharing the platform and render task runners creates an GLFW issue.

@chinmaygarde @stuartmorgan do you have inside on why this is happening? 
The errors comes from GLFW been unable to `make context current`.

**Comment by stuartmorgan** [comment]
I've never tried that configuration, so I don't have any particular insight here. Have you tried debugging into GFLW to see what the failure is specifically?

**Comment by chinmaygarde** [comment]
Can you clarify the following?

* Does this happen on all platforms consistently?
* When the error happens, what message does the `glfwSetErrorCallback` handler print?
* Can you confirm that the task runner set as the render task runner runs all tasks on the same underlying OS thread? I am assuming it does but want make sure as I am not familiar with the Go runtime and how it interacts with the underlying OS threads.

**Comment by pchampio** [comment]
Thanks for your response, I'll take some time in the next week to properly answer the questions.

**Comment by TahaTesser** [comment]
Hi @pchampio 

Could you please provide the information asked by this [comment](https://github.com/flutter/flutter/issues/48651#issuecomment-573887706)

Thank you

**Comment by pchampio** [comment]
I'm very sorry for been late on the answer.
This task is on the top of my todo-list. Once I have more time, I'll provide the information asked.

If you want to to clean the issue backlog, we can close this issue for now.

**Comment by TahaTesser** [comment]
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
