### ISSUE TITLE
automaticallyAdjustsScrollIndicatorInsets is not defined in webview_flutter

### ISSUE THREAD

**Issue by pakbachelors** [flutter/flutter#48664]
Hi everyone, i'm facing this issue while build application for the simulator, this issue came when i added this package "webview_flutter: ^0.3.19+4".  

Xcode's output:
↳
    /Users/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.19+4/ios/Classes/FlutterWebView.m:83:29: error: property 'automaticallyAdjustsScrollIndicatorInsets' not found on object of type 'UIScrollView *'
            _webView.scrollView.automaticallyAdjustsScrollIndicatorInsets = NO;
                                ^
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by cedricgrothues** [comment]
You could try running `flutter pub cache repair`, if that doesn't  work, please attach the `flutter doctor` output

**Comment by pakbachelors** [comment]
> flutter pub cache repair

Thank you for reply, i tried it before. and again tried but same problem and also i delete the "flutter" folder and again rezip it. but same problem.
This is flutter doctor Results:

/Users/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mirzashafique/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone X • 5A0138EA-A912-4701-8E71-0E1EFC9D2963 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
Process finished with exit code 0

**Comment by jonahwilliams** [comment]
It looks like that property was only added in iOS 13:

https://developer.apple.com/documentation/uikit/uiscrollview/3198043-automaticallyadjustsscrollindica?language=objc

That would likely mean your SDK is too old, though it seems like the plugin itself should have some sort of guard for this

**Comment by pakbachelors** [comment]
> It looks like that property was only added in iOS 13:
> 
> https://developer.apple.com/documentation/uikit/uiscrollview/3198043-automaticallyadjustsscrollindica?language=objc
> 
> That would likely mean your SDK is too old, though it seems like the plugin itself should have some sort of guard for this

Thank you for suggestion, my background is android, i don't know about iOS, so could you please tell me how we can add this property?

**Comment by dreampowder** [comment]
@pakbachelors 
@VladyslavBondarenko 
This happens when your XCode does not support ios13. 
The plugin has codes from ios13 but older xcode versions does not recognize these commands and naturally throws an error. 

It can be fixed by downloading the latest xcode version.

**Comment by dannycortesv** [comment]
I have the same issue using https://github.com/daohoangson/flutter_widget_from_html, any solution?

**Comment by dreampowder** [comment]
@dannycortesv install the latest version of xcode

**Comment by dannycortesv** [comment]
@dreampowder  i can't due i have macOs High Sierra...

**Comment by pakbachelors** [comment]
> @pakbachelors
> @VladyslavBondarenko
> This happens when your XCode does not support ios13.
> The plugin has codes from ios13 but older xcode versions does not recognize these commands and naturally throws an error.
> 
> It can be fixed by downloading the latest xcode version.

Thank you so much, This solutions works for me.

**Comment by rchavik** [comment]
Is there a workaround for those unable to upgrade xcode?

**Comment by dreampowder** [comment]
> Is there a workaround for those unable to upgrade xcode?

i don't think it is possible, the relevant code refers to an ios13 code, and xcode has to recognize it ini order to compile. 

the only way you can do is creating a fork without the ios13 code, or reverting back to an older version of this library

**Comment by FullstackJack** [comment]
I just verified that last known good version of webview_flutter with High Sierra is 0.3.19+3. Terrible that this means we loose updates to the library for iOS 12 and below. I sure hope Catalina is finally ready and not breaking tons of apps.
