### ISSUE TITLE
it crashed when  getting Platform and running on chrome

### ISSUE THREAD

**Issue by xty19** [flutter/flutter#48662]
I want my application running on ios android and chrome.
but some pub doesnt support web. So I have to get platform to fix the problem.
Like I use fluttertoast. It runs good on ios and android ,but it doesnt support web.
So I write the code to judge the platform,just below
```
var platform=Platform
```
crash log is
```
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:271:18
!state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:271)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (pointer_binding.dart:465)
    at pointer_binding.dart:411
    at pointer_binding.dart:390
    at HTMLElement.<anonymous> (pointer_binding.dart:195)
```
but it crash when running on chrome.so would you please fix it,thanks.

**Comment by jonahwilliams** [comment]
You need to check `kIsWeb` (from foundation.dart) to determine if you on the web. See also: https://github.com/flutter/flutter/issues/39998

The error you've posted is unrelated to this crash however
