### ISSUE TITLE
Android launch page

### ISSUE THREAD

**Issue by MuZiLee** [flutter/flutter#48666]
When I start and run my flitter, whether it's a newly created project or an old one, the Android screen appears black
The style.xml file is configured. When the app program starts, launch_background.png will load normally, but it will enter the black screen about 1-2 seconds after loading. In the black screen, the status bar is the same as launch_background.png. After entering the black screen, it will be a waiting process. It will enter the first startup page I wrote about 4-6 seconds. The reason for this is that I updated 1.12++
I used version 1.10++ before. Do I need to downgrade to the original version?

**Comment by iapicca** [comment]
Hi @MuZiLee  
I see there's an open [issue](https://github.com/flutter/flutter/issues/47582) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

https://github.com/flutter/flutter/issues/48552
