### ISSUE TITLE
Incorrect grammar in MediaQuery class docs

### ISSUE THREAD

**Issue by sudo-kaizen** [flutter/flutter#48660]
The Flutter [MediaQuery class documentation](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html) states in its second paragraph _For example, to **learn** the size of the current media.._.

This could have been caused by translation from another language. Although this seems to be a minor thing, English speakers will actually understand it better as  _For example, to **know** the size of the current media.._

**Comment by jonahwilliams** [comment]
I don't believe the grammar is incorrect in this case. "To learn" implies some work or acquisition which is comparable to accessing a getter

**Comment by jonahwilliams** [comment]
Closing because this is not an actionable issue currently
