### ISSUE TITLE
Blank Screen Before First Screen #Android

### ISSUE THREAD

**Issue by irufano** [flutter/flutter#48667]
There are blank screen before first screen in flutter app android version but on iOS work well.

## Steps to Reproduce

Im using flutter SDK 1.12.13 + hotfix.5 .

before it, I use flutter SDK 1.9.1 + hotfix.6 is no blank screen before first screen.

please help what should I do ?

**Comment by MuZiLee** [comment]
I have also encountered similar problems, and there is no solution at present

**Comment by MuZiLee** [comment]
https://github.com/flutter/flutter/issues/48666
My question

**Comment by iapicca** [comment]
Hi @irufano 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47582) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by carocean** [comment]
根本就没解决，现在出现在h7版本，就这都关闭了问题，哎，回去吃饭去

**Comment by iapicca** [comment]
Hi @carocean 
I didn't say it has been solved,
but I'm inviting to follow up on the issue I've linked above.
Thank you

**Comment by carocean** [comment]
I see(我着了）, Thank you（多谢），isty(我着了多谢）
Happy! 春节快乐！



在 2020-02-06 16:17:58，"Francecsco Iapicca" <notifications@github.com> 写道：

Hi @carocean
I didn't say it has been solved,
but I'm inviting to follow up on the issue I've linked above.
Thank you
