### ISSUE TITLE
"flutter.buildMode = debug" doesn't work

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#4866]

**Comment by abarth** [comment]
Are you running in debug mode?

**Comment by tain335** [comment]
Yes, I set 'flutter.buildMode=debbug', and I can use 'flutter refresh' commad to update the code.But I set debugPaintSizeEnabled,it is not work.

**Comment by jason-simmons** [comment]
This is working for me on a current build

**Comment by tain335** [comment]
I use alpha branch and have updated the code.
I clean my project first in Android Studio.
1. I have set local.properties buildMode=debug, and my app run debug mode. but "assert(() { my code... })", there my code didn't run.
2. I set "debugPaintSizeEnabled = true" , it didn't show widget's border and padding.
3.remote debugger not work too.
I do all as the document says, but I think my app didn't run on checked mode.

**Comment by tain335** [comment]
my local.properties
<img width="488" alt="3a5ebb0b-ac9d-44b0-92cb-42c1600dfc18" src="https://cloud.githubusercontent.com/assets/5304597/17628673/19074388-60e9-11e6-9d7a-0b2230c00858.png">
mycode
<img width="548" alt="3c8cd50c-e52b-4447-bd17-9fb1c22eeaff" src="https://cloud.githubusercontent.com/assets/5304597/17628769/85e5b9bc-60e9-11e6-99f7-a5c4fcb44aae.png">
my app log. it didn't run assert...
<img width="600" alt="60dde676-d742-4229-86a4-eb8baf394737" src="https://cloud.githubusercontent.com/assets/5304597/17628859/e8cb916e-60e9-11e6-8842-08aeef2c6280.png">
flutter doctor:
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/paul/flutter-workspace/flutter
    • Framework revision 529c25caa8 (16 hours ago), engine revision 1493032690

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.0.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.0.1, Build version 7A1001
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.28

**Comment by tain335** [comment]
@jason-simmons can tell me what is wrong

**Comment by Hixie** [comment]
Looks like the problem is that we're not ending up in debug mode.

I don't know what local.properties is, but maybe @devoncarew can help us here.

**Comment by abarth** [comment]
Sorry, @tvolkert saw something similar to this one today.

**Comment by devoncarew** [comment]
From looking at this, we are writing the build mode into the `android/local.properties` file (`flutter run --debug` / `flutter run --release`. And when I put a print in `android/buildSrc/src/main/groovy/FlutterPlugin.groovy`, we are pulling the right mode out of the file. So I think we're building it in the right more.

@tain335, how are you starting the app? Perhaps we're not passing the `--checked` flag in somewhere

**Comment by tvolkert** [comment]
@tain335 my patch just fixed the variant of this that I was seeing.  It's possible you were seeing the same error.  Once I roll that engine patch into this repo, give it another shot and see if it's fixed for you.

**Comment by tain335** [comment]
I just update the code. but it is still not work for me. I check the engine.version is f8d80c4617ea659ad47ee8afac498227c72aa031, is it right?

**Comment by tvolkert** [comment]
I *just* updated the engine version to `46e06cd91ac2550212e61b26d8b8325bd1b68cfa`, which has my fix. Try again now.

**Comment by tain335** [comment]
@tvolkert  I have try again, but nothing change...

**Comment by Hixie** [comment]
It seems nobody from the team can reproduce this. I'm not sure what we can do here.

**Comment by jakobr-google** [comment]
@tain335 is your project based on the hello-services example, or a plain `flutter create` ?

@mravn-google saw something similar recently, where profiling wasn't enabled in a profile build of hello-services. I believe the reason was that ExampleActivity didn't pass the runtime args to FlutterMain.

**Comment by eseidelGoogle** [comment]
@jakobr-google recently completely re-wrote our build support for hello_services.  I would expect this to be fixed?

Closing for now, please re-open if you're still having trouble!
