### ISSUE TITLE
showModalBottomSheet not respecting safearea with android:windowTranslucentNavigation

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#48677]
I set my main window to 
      <item name="android:windowTranslucentNavigation">true</item>
to get translucent appBar.  If I turn this off, it works fine.  

Everything seems to work fine except for showModalBottomSheet which will be positioned too low and behind the system navigation bar.

latest flutter, all packages on latest versions.

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/steve/google/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/steve/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/steve/google/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/steve/google/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by sgehrman** [comment]
![image](https://user-images.githubusercontent.com/287137/72220138-70638b00-3502-11ea-86a5-9eac1f3013ee.png)

**Comment by VladyslavBondarenko** [comment]
Hi @sgehrman 
You can manually receive height of this navigation via `MediaQuery.of(context).viewInsets.bottom` and use it for adding needed padding/margin

<details>
 <summary>This is my code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Modal bottom sheet'),
      ),
      body: SafeArea(
        child: Center(
          child: RaisedButton(
            child: const Text('SHOW BOTTOM SHEET'),
            onPressed: () {
              showModalBottomSheet<void>(context: context, builder: (BuildContext context) {
                return Container(
                margin: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
                  child: Padding(
                    padding: const EdgeInsets.all(32.0),
                    child: Text('This is the modal bottom sheet. Slide down to dismiss.',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Theme.of(context).accentColor,
                        fontSize: 24.0,
                      ),
                    ),
                  ),
                );
              });
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by sgehrman** [comment]
PopupMenuButton has a similar problem:
![image](https://user-images.githubusercontent.com/287137/72857408-619f7580-3c72-11ea-8404-4d3a6e8189be.png)

**Comment by MalteMagnussen** [comment]
Having this issue as well. 
Not sure how I'd get safeArea on this, so the top isn't hitting the status bar. 
I tried wrapping various things, such as the BottomModalSheet itself, in SafeArea, but no luck. 
![image](https://user-images.githubusercontent.com/11192971/89910070-11790800-dbf0-11ea-8a6e-438ac1d5bec8.png)

**Comment by ThiagoFontes** [comment]
If you create a new MaterialApp you'll be able to use SafeArea again, so far it was the only way I was able to

Working example for me with modal bottomsheets:

```dart
showModalBottomSheet<void>(
      isScrollControlled: true,
      context: context,
      MaterialApp(
            key: _navigationKey,
            onGenerateRoute: _.onGenerateRoute,
            navigatorObservers: [_ObserverBottomSheets<T>()],
      ),
);
```
