### ISSUE TITLE
Is there idea FlutterView(Android) intercept the 'back' keydown?  

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#4867]

**Comment by abarth** [comment]
You'll want to add something like this to your activity:

```java
    @Override
    public void onBackPressed() {
        if (flutterView != null) {
            flutterView.popRoute();
            return;
        }
        super.onBackPressed();
    }
```

**Comment by tain335** [comment]
But if FlutterView has no any route can pop, and the app should exit(in my usecase), is there a way to check the route can pop?

**Comment by abarth** [comment]
If you try to pop a route and the view doesn't have a route that it can pop, it will end the current activity:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L166

**Comment by tain335** [comment]
OH, it is clear in my case.And if I want to do other thing(not pop a route) just make a toast or make a dialog in FlutterView, how can do it?

**Comment by Hixie** [comment]
You can add a WidgetsBindingObserver that listens to `didPopRoute`, and returns true.
