### ISSUE TITLE
Move `compute` method to dart sdk

### ISSUE THREAD

**Issue by nioncode** [flutter/flutter#48673]
I followed https://flutter.dev/docs/cookbook/networking/background-parsing to parse json network responses to dart objects in a separate isolate to avoid ui jank, i.e. I now use [compute()](https://api.flutter.dev/flutter/foundation/compute.html) to spawn an isolate which parses the data after it has been received from the network. So far, so good.

However, the network call and parsing should be part of a library that is pure dart without dependencies to the flutter sdk. Thus, my proposal would be to move the `compute` method into the dart sdk instead of providing it in the flutter sdk so that pure dart libraries also have access to it.

Are there other dependencies to the flutter sdk that the `compute` method currently has that would make this difficult?

In the meantime, how can I replace the `compute` method with a pure dart method?
Should I use [IsolateRunner.run](https://pub.dev/documentation/isolate/latest/isolate.isolate_runner/IsolateRunner/run.html) from the [isolate](https://pub.dev/packages/isolate) package? Are there disadvantages when using `IsolateRunner.run` instead of `compute` in flutter?

**Comment by jonahwilliams** [comment]
> However, the network call and parsing should be part of a library that is pure dart without dependencies to the flutter sdk

If you want to discuss additions to the dart-sdk, it would be better to raise an issue on https://github.com/dart-lang/sdk. The flutter team, to note, is perfectly happy with the functionality as is.
