### ISSUE TITLE
Type 'String' is not a subtype of 'int' of 'index' 

### ISSUE THREAD

**Issue by xcaluca** [flutter/flutter#48688]
I'm new on Flutter and i found this issue in my code. I search a lot and i can't find a way to solve this.

> `import 'dart:async';
> import 'dart:convert';
> import 'dart:core';
> import 'dart:io';
> 
> import 'package:flutter/material.dart';
> import 'package:path_provider/path_provider.dart';
> 
> void main(){
>   runApp(MaterialApp(
>     home: Home(),
>   ));
> }
> 
> class Home extends StatefulWidget {
>   @override
>   _HomeState createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
> 
>   List _toDoList = ["Daniel"];
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Lista de Tarefas"),
>         backgroundColor: Colors.blueAccent,
>         centerTitle: true,
>       ),
>       body: Column(
>         children: <Widget>[
>           Container(
>             padding: EdgeInsets.fromLTRB(17.0, 1.0, 7.0, 1.0),
>             child: Row(
>               children: <Widget>[
>                 Expanded(
>                   child: TextField(
>                     decoration: InputDecoration(
>                         labelText: "Nova Tarefa",
>                         labelStyle: TextStyle(color: Colors.blueAccent)
>                     ),
>                   ),
>                 ),
>                 RaisedButton(
>                   color: Colors.blueAccent,
>                   child: Text("ADD"),
>                   textColor: Colors.white,
>                   onPressed: (){},
>                 )
>               ],
>             ),
>           ),
>           Expanded(
>             child: ListView.builder(
>               padding: EdgeInsets.only(top: 10.0),
>                 itemCount: _toDoList.length,
>                 itemBuilder: (context, index){
>                   return CheckboxListTile(
>                     title: Text(_toDoList[index]["title"]),
>                     value: _toDoList[index]["ok"],
>                     secondary: CircleAvatar(
>                       child: Icon(_toDoList[index]["ok"] ?
>                         Icons.check : Icons.error),
>                     ),
>                   );
>                 }),
>           )
>       ],
>       )
>     );
>   }
> 
>   Future<File> _getFile() async {
>     final directory = await getApplicationDocumentsDirectory();
>     return File("${directory.path}/data.json");
>   }
> 
>   Future<File> _saveData() async{
>     String data = json.encode(_toDoList);
>     final file = await _getFile();
>     return file.writeAsString(data);
>   }
> 
>   Future<String> _readData() async {
>     try {
>       final file = await _getFile();
> 
>       return file.readAsString();
>     }catch (e) {
>       return null;
>   }
>   }
> 
> }`

**Comment by xcaluca** [comment]
import 'dart:async';
import 'dart:convert';
import 'dart:core';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main(){
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {

  List _toDoList = ["Daniel"];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Lista de Tarefas"),
        backgroundColor: Colors.blueAccent,
        centerTitle: true,
      ),
      body: Column(
        children: <Widget>[
          Container(
            padding: EdgeInsets.fromLTRB(17.0, 1.0, 7.0, 1.0),
            child: Row(
              children: <Widget>[
                Expanded(
                  child: TextField(
                    decoration: InputDecoration(
                        labelText: "Nova Tarefa",
                        labelStyle: TextStyle(color: Colors.blueAccent)
                    ),
                  ),
                ),
                RaisedButton(
                  color: Colors.blueAccent,
                  child: Text("ADD"),
                  textColor: Colors.white,
                  onPressed: (){},
                )
              ],
            ),
          ),
          Expanded(
            child: ListView.builder(
              padding: EdgeInsets.only(top: 10.0),
                itemCount: _toDoList.length,
                itemBuilder: (context, index){
                  return CheckboxListTile(
                    title: Text(_toDoList[index]["title"]),
                    value: _toDoList[index]["ok"],
                    secondary: CircleAvatar(
                      child: Icon(_toDoList[index]["ok"] ?
                        Icons.check : Icons.error),
                    ),
                  );
                }),
          )
      ],
      )
    );
  }

  Future<File> _getFile() async {
    final directory = await getApplicationDocumentsDirectory();
    return File("${directory.path}/data.json");
  }

  Future<File> _saveData() async{
    String data = json.encode(_toDoList);
    final file = await _getFile();
    return file.writeAsString(data);
  }

  Future<String> _readData() async {
    try {
      final file = await _getFile();

      return file.readAsString();
    }catch (e) {
      return null;
  }
  }

}

**Comment by jonahwilliams** [comment]
This sort of question is better suited for one of the communities in https://flutter.dev/community or a website like stackoverflow - because this is not a bug in the tooling, framework, engine, or plugins.
