### ISSUE TITLE
CupertinoTableView (UITableView)

### ISSUE THREAD

**Issue by Tridie2000** [flutter/flutter#48686]
## Use case

I want to create a settings page in my app that looks like a grouped UITableView. I'm building an app that looks like a native iOS app so I need a widget that looks exactly like a UITableView. 

## Proposal

Like all the other Cupertino widgets, there should be a CupertinoTableView that looks like a UITableView. 

![1eb44f8d-1907-4949-9208-f2fb7f3ffd1b](https://user-images.githubusercontent.com/24608795/72224993-8f086700-3580-11ea-8a26-8642e4f8ac89.png)

If you implement this don't forget the inset-grouped style. 

![firstSnapshot](https://user-images.githubusercontent.com/24608795/72225017-c9720400-3580-11ea-9e2b-d599a0fa0435.png)

This should be added to the Cupertino widgets catalogue.

**Comment by xster** [comment]
Merging into #19228
