### ISSUE TITLE
ClipOval masking is off on iOS (all browsers), macOS (Safari) and Windows (Edge) - Flutter Web

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#48683]
There are some issues with the mask applied in a ClipOval widget like:

```
double avatarSize = 200.0;
String avatarPath = 'path/to/some/image';
Uint8List _avatar;

ClipOval( 
  child: Container(
    color: Colors.black26, 
    child: FlatButton( 
      padding: EdgeInsets.all(0.0),
      onPressed: () async {
        //await some action like selecting new avatar
      }, 
      child: (this._avatar == null)?
      (avatarPath!=null)? 
        FadeInImage.assetNetwork(
          width: avatarSize,
          height: avatarSize,
          image: avatarPath,
          placeholder: 'images/transparent.png',
          fit: BoxFit.cover,
        ):
        Icon(Icons.add_a_photo, size: avatarSize,): 
      Image.memory(_avatar, width: avatarSize, height: avatarSize, fit: BoxFit.cover),
    ),
  ),
);
```
This is how it is correctly rendered on macOS Chrome:
https://adobe.ly/30eBVdo

This is how it looks on macOS (Safari - latest version) and iOS (Safari/Chrome - latest versions):
https://adobe.ly/3a2PAJm

This is how it looks on Microsoft Edge latest version -  44.18362.449.0 (it seems that the masking is not applied/working at all with Microsoft Edge):
https://adobe.ly/2TnLA09

Info about Flutter:
```
Flutter 1.13.9-pre.59 • channel master • https://github.com/flutter/flutter.git
Framework • revision ab36346af6 (22 hours ago) • 2020-01-11 14:20:05 -0500
Engine • revision 3d37d39d95
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 395daaa3ec)
```

**Comment by Constans** [comment]
This **doesn't happen** on this simpler widget:

```
ClipOval(
  child: Container(
    color: Colors.black26, 
      child: FadeInImage.assetNetwork(
      width: 200,
      height: 200,
      image: 'https://flutter.dev/assets/404/dash_nest-c64796b59b65042a2b40fae5764c13b7477a592db79eaf04c86298dcb75b78ea.png',
      placeholder: 'https://flutter.dev/assets/404/dash_nest-c64796b59b65042a2b40fae5764c13b7477a592db79eaf04c86298dcb75b78ea.png',
      fit: BoxFit.cover,
    ),
  ),
),
```

I'm sorry about the complicated example, I just pulled it out of a WIP project and removed sensitive data.

I'll try to get on to this and to provide an example that can be isolated. There are a lot more things happening in the project I experience the issue, though the described rendering issue is also seen in multiple places where ClipOval is used.

Tested on:

```
Flutter 1.13.9-pre.79 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9eb9ea0ffa (5 hours ago) • 2020-01-13 21:30:42 -0800
Engine • revision 0235a50843
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)
```

**Comment by ferhatb** [comment]
Update: @Constans thank you, we were able to repro issue. We found 2 problems, Safari handles -webkit-clip-path on a div element without size differently and ends up completely clipping item (image disappears), this is easy to resolve. 

The second issue is around zoom and how svg clip paths are not correctly adjusted. We are working on a fix that will make this consistent across browsers and zoom levels. There is a much easier fix to this by using clip-path: circle but we want to make sure it works in the generalized Path case, after that we will add optimization.

**Comment by Constans** [comment]
@ferhatb, I'm glad you could to reproduce the issue.

I tried on some separate use cases and it worked fine in isolation outside my test project, that's why I was afraid it would be harder to reproduce on your side.

I've tracked some other bugs on xOS though I'll retest against the latest version before submitting.

I'm seeing many good changes on all sides. 
The app weight is increasing slowly, but I'm sure there are plans for that like the possibility of separating the core web VM and cache it to be reusable among all Flutter web apps (or other solutions).

Good luck and good work so far!

**Comment by Constans** [comment]
@ferhatb , now it is not rendering the ClipOval images at all and the cards are all rendered with sharp corners (as on Microsoft Edge). 
Before they were rounded.

Flutter info bellow:
```
Flutter is already up to date on channel master
Flutter 1.14.2-pre.39 • channel master • https://github.com/flutter/flutter.git
Framework • revision c61e55ad6b (44 minutes ago) • 2020-01-17 10:58:01 -0800
Engine • revision 8df1757d35
Tools • Dart 2.8.0 (build 2.8.0-dev.3.0 f1df196ddf)
```

**Comment by ferhatb** [comment]
@Constans engine has not rolled into flutter master yet, are you running using --local-engine?. https://github.com/flutter/flutter/commits/master

**Comment by Constans** [comment]
Ah, sorry. I just made a master upgrade and tested. 

I'll recheck to confirm after the roll-out.

Thank you!

**Comment by Constans** [comment]
@ferhatb, I couldn't wait and tested before the full roll-out and it works like a charm.

There is still a weird reload on macOS Safari, that I reported in another issue and possible to get the unrounded cards in if it is still present after the full roll-out. 

Congrats and good luck!

**Comment by BirjuVachhani** [comment]
Have this ever been fixed? I'm still facing it!
