### ISSUE TITLE
Flutter and Dart Plugin not installed

### ISSUE THREAD

**Issue by ZaroonRashid** [flutter/flutter#48685]
Hi, i need some help ... i am using Android Studio 3.5.3 on widows 8.1 for flutter ... i have installed plugin and set path of Flutter SDK ... but flutter doctor says flutter and dart plugin are not installed ... i tried every solution but it is still showing plugins not installed ...

**Comment by jonahwilliams** [comment]
@ZaroonRashid you need to actually fill out the issue template that is provided. Without knowing your flutter doctor output and repro steps we will be unable to help you

**Comment by VladyslavBondarenko** [comment]
@ZaroonRashid 
I hope you've solved the issue.
Closing as additional information were not provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
