### ISSUE TITLE
be more lenient about the android SDK layout

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4868]
Some android SDKs have slightly non-standard layouts. In particular, the platforms/ directory
has subdirectories named android_\* instead of the usual android-*. We should support this style SDK.

**Comment by Hixie** [comment]
How does this manifest? What SDKs are these?

**Comment by Hixie** [comment]
@devoncarew Can you elaborate on this? Is this obsolete now that we've migrated to gradle?

**Comment by devoncarew** [comment]
I don't remember the context for this bug. I think we're good to close it; if it's a real issue, it'll re-open.
