### ISSUE TITLE
What command does the android studio IDE use to build?

### ISSUE THREAD

**Issue by srburton** [flutter/flutter#48682]
What command does the android studio IDE use to build?

![Screenshot_11](https://user-images.githubusercontent.com/15394508/72224018-2e633500-3554-11ea-84d5-4e7f484182ab.png)

My doubt is because when I use `flutter build apk -v`, there are errors that make it impossible to generate the application, but when I click this button of android studio it works perfectly, here comes my question what is the command used by him?

**Comment by dnfield** [comment]
This would be a question better suited for StackOverflow - it is not a bug or feature request for any of the repositories covered by this tracker.

It's very likely that this is using something like `flutter run` though.
