### ISSUE TITLE
CameraPlugin isTakingPicture always true

### ISSUE THREAD

**Issue by vodemn** [flutter/flutter#48687]
## Steps to Reproduce

1. Navigate to https://pub.dev/packages/camera#-example-tab-.
2. And run the example application
3. Take a picture multiple times

**Expected results:** aking picture on tap

**Actual results:**  Unable to take a picture, because controller.value.isTakingPicture is always true

**Comment by VladyslavBondarenko** [comment]
Hi @vodemn 
Could you please provide your `flutter doctor -v`?
Thank you

**Comment by vodemn** [comment]
> Hi @vodemn
> Could you please provide your `flutter doctor -v`?
> Thank you

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vadim\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\vadim\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\vadim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
