### ISSUE TITLE
BorderRadius.circular() should be const

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#48690]
See border_radius.dart

Why isn't circular const?  Seems like it should be.

/// Creates a border radius where all radii are [Radius.circular(radius)].
  BorderRadius.circular(double radius) : this.all(
    Radius.circular(radius),
  );

I'm on latest flutter/latest packages.

**Comment by jonahwilliams** [comment]
Border radius circular cannot be const because it relies on the construction of a Radius object in the constructor. In theory, yes it would be possible to extend Dart's const capabilities to support some subset of expressions/constructors as const. This is not possible today though.
