### ISSUE TITLE
path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by vinodlee** [flutter/flutter#48698]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
![image](https://user-images.githubusercontent.com/22536559/72237832-d5ea7100-3601-11ea-8730-f26afe3f1066.png)

**Comment by VladyslavBondarenko** [comment]
Hi @vinodlee 
I see there's an open issue addressing the case you described.
Please follow up on that issue [#47833](https://github.com/flutter/flutter/issues/47833), or [#47816](https://github.com/flutter/flutter/issues/47816)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
