### ISSUE TITLE
make sure that we're running the correct adb

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4870]
At a codelab, a user had a problem with multiple copies of ADB installed. The one in the path was different from the one in the android SDK flutter found (the two adbs were not compatible). We should ensure that we always run the adb from the android SDK.

**Comment by Hixie** [comment]
@devoncarew  Which one is the "correct" one?

**Comment by devoncarew** [comment]
This may or may not still be a thing, but this issue is about running the `adb` instance from the located android sdk, instead of one which may be on their path (which might not be the same adb instance or version).

**Comment by Hixie** [comment]
I believe we always use the one from the indicated SDK. Does that mean this bug should be closed?

**Comment by devoncarew** [comment]
Yup - I'll close it.
