### ISSUE TITLE
[maps] devicepixelratio property of ImageConfiguration doesn't work on Android.

### ISSUE THREAD

**Issue by swapnilshah09** [flutter/flutter#48703]
I am using google maps custom marker icon for my application. The devicepixelratio property of ImageConfiguration works fine to scale the image in iOS but it is not working in Android.

I tried using the size property as well but it is not working. It seems that ImageConfiguration() is not working in Android.

```dart
       pinLocationIcon = await BitmapDescriptor.fromAssetImage(
        ImageConfiguration(
            devicePixelRatio: 30,
       ),
       'assets/destination_map_marker.png');

```

First screenshot is of iOS device and second is of Android

![image](https://user-images.githubusercontent.com/26348200/72238975-768e6000-3605-11ea-91bf-5edc5d8309f1.png)

![image](https://user-images.githubusercontent.com/26348200/72239015-96be1f00-3605-11ea-87d9-81ae45795555.png)

**Comment by iapicca** [comment]
Hi @swapnilshah09 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample?
Thank you

**Comment by swapnilshah09** [comment]
Output for flutter doctor -v:
swapnil@Swapnils-MacBook-Pro dev % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/swapnil/Documents/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/swapnil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 75323064-48F0-4C66-B14B-76A52B06BD16 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

Code snippet for marker formation:
Map<String, Marker> _markers = {};
  String selectedMarker = 'selectedMarker';
  LocationManager.LocationData currentLocation;
  String currentAddress;
  BitmapDescriptor pinLocationIcon;
  LatLng centerPosition;
  bool permission = true;
static CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(30.0, 35.0),
    zoom: 14.4746,
  );

  void _getLocation() async {
    var currentLocation = await Geolocator()
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
    centerPosition = LatLng(currentLocation.latitude, currentLocation.longitude);

    setState(() {
      _markers.clear();
       var marker = Marker(
          draggable: true,
          markerId: MarkerId("curr_loc"),
          position: centerPosition,
          infoWindow: InfoWindow(title: 'curr_loc'),
          icon: pinLocationIcon,
          onDragEnd: _onCameraMove,
//         consumeTapEvents: true
        );
      _markers[selectedMarker] = marker;
    });
  }

  void setCustomMapPin() async {
    pinLocationIcon = await BitmapDescriptor.fromAssetImage(
        ImageConfiguration(
            devicePixelRatio: 30,
        ),
        'assets/destination_map_marker.png');
  }

@override
  void initState() {
    setCustomMapPin();
    _getLocation();
    super.initState();
  }

void _onMapCreated(GoogleMapController controller) async {
    mapController = controller;
    final center = await getUserLocation();
    mapController.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(
        target: center == null ? LatLng(0, 0) : center, zoom: 15.0)));
  }

  Future<LatLng> getUserLocation() async {
    final location = LocationManager.Location();
    try {
        currentLocation = await location.getLocation();
        final lat = currentLocation.latitude;
        final lng = currentLocation.longitude;
        var coordinates = new Coordinates(currentLocation.latitude, currentLocation.longitude);
        var address = await Geocoder.local.findAddressesFromCoordinates(coordinates).catchError((onError) => print(onError));
        currentAddress =
        "${address.first.featureName}, ${address.first.addressLine}";
        _addressFieldController.text = currentAddress;

        final center = LatLng(lat, lng);
        return center;
    } on Exception {
      currentLocation = null;
      return null;
    }
  }

Expanded(
                                child: Stack(
                                  children: <Widget>[
                                    GoogleMap(
                                      onMapCreated: _onMapCreated,
                                      initialCameraPosition: _kGooglePlex,
                                      myLocationButtonEnabled: false,
                                      markers: Set<Marker>.of(_markers.values),
                                      zoomGesturesEnabled: true,
                                      onTap: mapOnTap,
                                      scrollGesturesEnabled: true,
                                    ),
                                  ],
                                ),
                              )

**Comment by maicolstracci** [comment]
I am experiencing the same error. I haven't tried with iOS but with Android it's not scaling at all.
Have you found a solution/workaround?

flutter doctor -v below
`[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Versione 10.0.18363.592], locale it-IT)
    • Flutter version 1.12.13+hotfix.6 at C:\Users\Maicol\Documents\Flutter\flutter
    • Framework revision 18cd7a3601 (7 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Maicol\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • SM A520F   • 5200d661ee9b94c3 • android-arm64  • Android 8.0.0 (API 26) (emulator)
    • Chrome     • chrome           • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
`

**Comment by jaykon-w** [comment]
I have the same problem here

**Comment by sj1914** [comment]
I have the same problem!

**Comment by swapnilshah09** [comment]
Suddenly it has stopped working for iOS as well.

**Comment by ErliSoares** [comment]
I have the same problem, this error gets in the way :(

**Comment by cg021** [comment]
The devicePixelRatio property only works on Android if the assets directory contains subdirectories named according to their desired dpi mappings. ImageConfiguration decides which image to use by selecting the file whose name equals the assetName string passed into fromAssetImage, located in the subdirectory with the closest numeric value to the devicePixelRatio. Example:
```
/assets
  /1.0x
    /image.png
  /2.0x
    /image.png
```
Here is a test call that loads an asset as a custom marker according to its dpi:
```
ImageConfiguration config = ImageConfiguration(devicePixelRatio:3);
BitmapDescriptor.fromAssetImage(config, 'assets/image.png')
    .then((marker) {
          setState(() {
               customMarker = marker;
          });
     });
```
[Documentation](https://flutter.dev/docs/development/ui/assets-and-images#declaring-resolution-aware-image-assets)

**Comment by blasten** [comment]
It sounds like `devicePixelRatio` has different behavior on iOS and Android.  @cg021 were you able to repro the issue without using the maps plugin?

**Comment by cg021** [comment]
No, I haven't been able to. I've only had this issue when I didn't create subdirectories in the assets folder. It's similar to [#39691](https://github.com/flutter/flutter/issues/39691) and [#24865](https://github.com/flutter/flutter/issues/24865).

**Comment by blasten** [comment]
@cyanglaz do you know anything about it?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
