### ISSUE TITLE
  video_player: ^0.10.5+1  Network video loads slowly

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#48712]
Hello, when I play a web video here, the web video loads slowly. I want to know if this plugin is pre-loaded or is it all loaded before it starts playing? Can play while loading

**Comment by iapicca** [comment]
Hi @Tumbler0809 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample?
Thank you

**Comment by Tumbler0809** [comment]
C:\Users\Orion\AndroidStudioProjects\mobile_client_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (8 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Orion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Orion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Orion\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • MI 8 • fb21bfb6 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
@Tumbler0809 
is https://github.com/flutter/flutter/issues/44722 similar to your case?

**Comment by Tumbler0809** [comment]
No, my video can play normally, but the network video takes too long to load, can I play it while buffering instead of buffering the entire video at one time?

**Comment by iapicca** [comment]
Hi @Tumbler0809 
there's already a request for the feature you are describing
Please follow up on that [issue](https://github.com/flutter/flutter/issues/40931),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
