### ISSUE TITLE
How to add plain Android library to a Flutter plugin

### ISSUE THREAD

**Issue by rainmeterLotus** [flutter/flutter#48716]
I have created a module with File->New Module->Android Library inside my Flutter plugin's android project. And now I have a structure like below:
`|-my_plugin
  |-android
    |-settings.gradle
    |-build.gradle
    |-mylibrary
      |-build.gradle`

/android/settings.gradle:
`rootProject.name = 'my_plugin'
include ':mylibrary'`

/android/build.gradle:
`...
dependencies {
  implementation project(':mylibrary')
}`

When I build example plugin project (which is automatically created by Flutter CLI) with flutter build apk or flutter run, I get this error:
`Project with path ':mylibrary' could not be found in project ':my_plugin'.`

Any suggestions?

**Comment by VladyslavBondarenko** [comment]
Hi @rainmeterLotus 
Have you already checked Flutter documentation about [Developing packages & plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages)?
Thank you

**Comment by rainmeterLotus** [comment]
> Hi @rainmeterLotus
> Have you already checked Flutter documentation about [Developing packages & plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages)?
> Thank you

thank your reponse!I read it many times
but you may don't know what I mean.

> |-my_plugin
  |-android
    |-settings.gradle
    |-build.gradle
    |-mylibrary
      |-build.gradle

it's mean ,my plugin for android,the android dependence other module!
not the third party，exemple :jar or maven url. at settings.gradle file,no like this:

> compileOnly files('libs/flutter.jar')
  implementation 'com.squareup.okhttp3:okhttp:3.10.0'

but ,I want for this:

> api project(": mylibrary")

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.

**Comment by shyandsy** [comment]
same problem
there is no documentation about this

@rainmeterLotus have you found answer for this?

**Comment by shyandsy** [comment]
it has not been run when the flutter build apk
```
setting.gradle

rootProject.name = 'flutter_myplugin'
logger.error('A message which is logged at QUIET level:BBBBBB')
include ':app', ':core'
```
