### ISSUE TITLE
MediaQuery.of has sideffects in build().  Keyboard shows and hides quickly clicking on TextField.

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#48714]
I'm calling MediaQuery.of during build() of my widget and it's having some negative side effects  

calling this...

```
static bool isDarkMode(context) {
    return MediaQuery.of(context).platformBrightness == Brightness.dark;
  }
```

I have an editor with lots of TextFormField.  If I click on some of the text fields, the keyboard comes up and then dismisses right away and the text field is not in focus. 

MediaQuery.of calls dependOnInheritedWidgetOfExactType which I'm assuming is the call responsible for this problem.  I'm guessing it's causing a rebuild of the parent view and somehow messing up the focus on my TextField.  

Anything I can do to work around this?  Do I need keys on all my text fields so thing will get rebuilt and restored correctly?  I'll give that a shot.

**Comment by HansMuller** [comment]
Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem, and we'll look into it.

**Comment by TahaTesser** [comment]
Hi @sgehrman 
Are you still experiencing this issue with latest dev?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by shkim** [comment]
I had the same problem, and static helped: https://github.com/flutter/flutter/issues/20042
