### ISSUE TITLE
[proposal] [triage] create new "p: third party"

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#48721]
Hi all,
I feel that could be useful to add a label that helps
to better identify and catalogs,
regardless the issue being destined to be closed or not,
issues related to 3rd party plugins.

Doing so could be also useful 
for possible future analysis of the ecosystem.

In first instance I propose to add the label:
`p: third party` which is quite self explanatory.

Secondarily, 
if doesn't make the label list too crowded
might make sense to create also:
- `p: community` for plugins that belongs to [fluttercommunity](https://github.com/fluttercommunity/community)
- `p: favorites` for plugins that belongs to the [Flutter Favorite program](https://flutter.dev/docs/development/packages-and-plugins/favorites)

Thank you for reading

**Comment by iapicca** [comment]
Plugin `p: third party` created
I leave the issue open for future references, changes and implementation

**Comment by dnfield** [comment]
Labels are cheap, just make them when we need them :)

Going to close this - I don't think there's any further action to take here.
