### ISSUE TITLE
GestureArenaMember of WebView is not added

### ISSUE THREAD

**Issue by tzufitltaboola** [flutter/flutter#48720]
### **Background:**
I have two scrollable elements that I want them to work synchronously:
on top: A listView.
on bottom: A webView that its height is the screen height and scrollable (if the webView is more than the screen height, the app crashes).

### **What I’m trying to accomplish:**
At first, only the listView is scrollable, when finishing scrolling the listView, the scroll of the webView becomes enabled, and when the user continues to scroll, the scroll is inside of the webView and not the listView.

### **What I have done:**

1. Use CustomScrollView and added to the Slivers:
    a. SliverList for the listView
    b. SliverToBoxAdapter for the webView.
2. Listening to the scroll of the CustomScrollView. When getting to the end of the scroll, enabling the webView scroll.
3. Listening to the scroll of the webView, when the webView is scrolled to top, disabling the webView scroll.
4. To enable and disable the scroll of the webView I implemented a custom OneSequenceGestureRecognizer:
I added to it a flag ‘scrollEnabled’ and override this function:
`
@override
void handleEvent(PointerEvent event) {
    if (scrollEnabled) {
        resolve(GestureDisposition.accepted); // WebView internal will win
    }
}
`
5. To Allow gesture debugging I added- ‘debugPrintGestureArenaDiagnostics = true;’
Now in different stages of the scroll, I can see the following logs:
    a. When I start scrolling the CustomScrollView and my finger is on the list view:
        ❙ ★ Opening new gesture arena.
        ❙ Adding: VerticalDragGestureRecognizer#7463f(start behavior: start)
        ❙ Closing with 1 member.
        ❙ Default winner: VerticalDragGestureRecognizer#7463f(start behavior: start)
     b. When I’m scrolling the CustomScrollView and my finger is on the webView:
        ❙ ★ Opening new gesture arena.
        ❙ Adding: Instance of '_CombiningGestureArenaMember'
        ❙ Adding: VerticalDragGestureRecognizer#7463f(start behavior: start)
        ❙ Closing with 2 members.
     c. When I get to the end of the scroll of the customScrollView and i'm try to continue to scroll and my finger is on the webView:
        ❙ ★ Opening new gesture arena.
        ❙ Adding: VerticalDragGestureRecognizer#7463f(start behavior: start)
        ❙ Closing with 1 member.
        ❙ Default winner: VerticalDragGestureRecognizer#7463f(start behavior: start)
     d. When I get to the end of the scroll, remove my finger and wait, and then try to continue to scroll:
        ❙ ★ Opening new gesture arena.
        ❙ Adding: Instance of '_CombiningGestureArenaMember'
        ❙ Adding: VerticalDragGestureRecognizer#7463f(start behavior: start)
        ❙ Closing with 2 members.
        ❙ Accepting: Instance of '_CombiningGestureArenaMember'
        ❙ Self-declared winner: Instance of '_CombiningGestureArenaMember'

### **The problem:**
The problem is at 5.c.- I’m missing the '_CombiningGestureArenaMember'. Even though my finger is on the webView, the member is not added to the arena. Only if I remove my finger and wait for a sec and try to scroll again down, the member is added. 

If the member is not added, my function ‘handleEvent’  in the custom OneSequenceGestureRecognizer class is not called and I can’t enable the scroll of the webView.

So in order to switch the scroll from the ListView to the WebView, I need to wait when I get to the end of the scroll of the CustomScrollView, and I can’t scroll smoothly.

**Comment by VladyslavBondarenko** [comment]
Hi @tzufitltaboola 
Could you please provide a code sample? Then it'll be easier to address your issue
Thank you

**Comment by tzufitltaboola** [comment]
@VladyslavBondarenko Thank you for responding, I will add a code sample.
Just wanted to add this happens **only in iOS** and not on android.

**Comment by tzufitltaboola** [comment]
class ListViewScreen extends StatefulWidget {

  Set<Factory<OneSequenceGestureRecognizer>> _savedFactoryRecognizers = Set<Factory<OneSequenceGestureRecognizer>>();
  WebViewGestureRecognizer _vertical;

  ScrollController _scrollController;

  ListViewScreen(String publisher, String pageUrl, String pageType, String placement, String mode);

  @override
  _ListViewScreenState createState() => _ListViewScreenState();
}

class _ListViewScreenState extends State<ListViewScreen> {

  @override
  void initState() {
    super.initState();

    widget._vertical = WebViewGestureRecognizer();
    widget._vertical.scrollEnabled = false;

    widget._savedFactoryRecognizers = [
      Factory<WebViewGestureRecognizer>(
            () => widget._vertical,
      )
    ].toSet();

    widget._scrollController = ScrollController();
    widget._scrollController.addListener(scrollListener);
  }

  scrollListener() {
    if (widget._scrollController.offset >=widget._scrollController.position.maxScrollExtent &&
        !widget._scrollController.position.outOfRange) {
      print("reach the bottom");
      setState(() {
        widget._vertical.scrollEnabled = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      controller: widget._scrollController,
      slivers: <Widget>[
        SliverList(
            delegate: new SliverChildListDelegate(_buildList(20))
        ),
        SliverToBoxAdapter(
          child: ConstrainedBox(
            constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height),
            child: WebView(
                initialUrl: "https://en.wikipedia.org/wiki/Main_Page",
                gestureRecognizers: widget._savedFactoryRecognizers
            ),
          )
        ),
      ],
    );
  }

  List _buildList(int count) {
    List<Widget> listItems = List();

    for (int i = 0; i < count; i++) {
      listItems.add(new Padding(padding: new EdgeInsets.all(20.0),
          child: new Text(
              "Item ${i.toString()}",
              style: new TextStyle(fontSize: 25.0)
          )
      ));
    }

    return listItems;
  }
}



class WebViewGestureRecognizer extends OneSequenceGestureRecognizer {

  bool scrollEnabled = false;

  WebViewGestureRecognizer();

  /// This is the only event that we managed to switch scrolling to web content
  @override
  void addPointer(PointerEvent event) {
    startTrackingPointer(event.pointer); //Allow handleEvent() to handle the logic.
  }

  @override
  String get debugDescription => 'customPan';

  @override
  void didStopTrackingLastPointer(int pointer) {}

  @override
  void handleEvent(PointerEvent event) {
    if (event is PointerMoveEvent) {
      if (scrollEnabled) {
        resolve(GestureDisposition.accepted); // WebView internal will win
      } else {
        stopTrackingPointer(event.pointer); // Native external will win
      }
    }
  }
}

**Comment by darshankawar** [comment]
Hi @tzufitltaboola, can you please confirm if you are still experiencing this issue on latest Flutter and `webview_flutter` plugin ?

**Comment by markusaksli-nc** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
