### ISSUE TITLE
Confusing that --debug builds have Release in their path?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4872]
```
%flutter build ios --debug                                                                                                                [/src/game]
Building io.flutter.spaceblast for device (ios)...   9.8s
Built ios/build/Release-iphoneos/Runner.app.
```

**Comment by abarth** [comment]
We should move the build outputs into the `build` directory, which will resolve this issue.

**Comment by Hixie** [comment]
Is this resolved now?

**Comment by sethladd** [comment]
Not blocking early adopters and M2, moving out.

**Comment by Hixie** [comment]
I'm going to close this since I've not seen anyone even mention it, let alone be confused by it. I think we resolved this a while ago.
