### ISSUE TITLE
Enable stripped AOT snapshots via tool feature

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#48726]
Enabling a stripped AOT snapshot with `--strip --dwarf-stack-traces --save-debugging-info=something.so.debug` will reduce the code size, at the cost of requiring a second file to map stack traces.

**Comment by jonahwilliams** [comment]
This is currently blocked by the Dart SDK needing a library to symbolicate the stack traces produced by stripped binaries.

**Comment by mkustermann** [comment]
[package:native_stack_traces](https://pub.dev/packages/native_stack_traces) is now available on pub.

**Comment by jonahwilliams** [comment]
Currently working on this

**Comment by Hixie** [comment]
cc @zoeyfan can you check with customer:hand and customer:headline that this bug is one they need? (i.e. that it is critical?) We copied the labels from the bug it came from.

**Comment by zoeyfan** [comment]
@Hixie I think so. This work is a part of the overall effort in reducing code size.
