### ISSUE TITLE
Image.network should provide the downloaded image bytes

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#48734]
`Image.network` should have a way to pass the complete downloaded image bytes, so we can use it ourselves, like saving it to a file, or manipulate it.

**Comment by goderbauer** [comment]
You can already download the bytes however you want and then show it on screen with `Image.fromBytes`.

**Comment by feinstein** [comment]
I know, but it's useful to have it also at `Image.network`. Imagine someone who made an app using `Image.network`, now he needs to persist the image, if `Image.network` gives him the image, it's a simple change, if it doesn't, it's a whole different logic and refactoring.
