### ISSUE TITLE
`isRepaintBoundary => true` causes `Object has been disposed.` on `Canvas.restore`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#48737]
## Steps to Reproduce

In the following, the "parent" will be `RenderPARENT` and the child will be `RenderCHILD`  (see exception).

* Set up a `MultiChildRenderObjectWidget`.

* Lay out and paint the children properly in a `RenderBox`. The `paint` method of this parent render object looks like this:

```dart
canvas.save();
// .. some canvas operations
canvas.restore();

defaultPaint(); // essentially
```

* Mark the child render objects (those of the widgets passed to the `MultiChildRenderObjectWidget`) as a repaint boundary:

```dart
@override
bool get isRepaintBoundary => true;
```

* Call `Canvas.restore` in the child render object's `paint` method.

When I set up the children as repaint boundaries, I always get the following exception:
<details>

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following message was thrown during paint():
Object has been disposed.

The relevant error-causing widget was:
  CHILD

When the exception was thrown, this was the stack:
#0      Canvas.restore (dart:ui/painting.dart:3445:41)
#1      RenderCHILD.paint (package:local)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
#5      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
#7      RenderPARENT.paint.<anonymous closure> (package:local)
```

</details>

---

```
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5,, locale en-US)
    • Flutter version 1.12.13+hotfix.5
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

I also tried it on `master` from today (`23a3d1014faffa3d1a87104f1b4c90f95daa1ce7`) and I have the exact same issue.

**Comment by dnfield** [comment]
I suspect there's something wrong with the way you're calling `canvas.restore`.  Can you please add a full reproduction?

**Comment by creativecreatorormaybenot** [comment]
@dnfield I realized I am calling [`PaintingContext.pushTransform`](https://api.flutter.dev/flutter/rendering/PaintingContext/pushTransform.html) in `paint` and I just found out that it seems like this is modifying the `layer`, which I am not allowed to do, right?

I will investigate if removing it solves the issue.

**Comment by dnfield** [comment]
Right, you cannot modify the layer if you declare yourself a repaint boundary:

```
  /// Whether this render object repaints separately from its parent.
  ///
  /// Override this in subclasses to indicate that instances of your class ought
  /// to repaint independently. For example, render objects that repaint
  /// frequently might want to repaint themselves without requiring their parent
  /// to repaint.
  ///
  /// If this getter returns true, the [paintBounds] are applied to this object
  /// and all descendants. The framework automatically creates an [OffsetLayer]
  /// and assigns it to the [layer] field. Render objects that declare
  /// themselves as repaint boundaries must not replace the layer created by
  /// the framework.
  ///
  /// Warning: This getter must not change value over the lifetime of this object.
```

**Comment by creativecreatorormaybenot** [comment]
@dnfield Yes, I did not realize `pushTransform` did this. I now use `Canvas.transform` directly and it works...
