### ISSUE TITLE
Cancelled jobs on LUCI show as failed in GitHub checks

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#48748]
When LUCI capacity is maxed out, jobs will be cancelled and rescheduled. This comes back as a failed check, and redirects to a cancel job in LUCI.

I personally manually retried the job, which unnecessarily added to the queue. LUCI automatically queues it to the job queue for when the next available machine is available.

I propose we change LUCI to instead return a pending icon for this case instead of the big red X for the GitHub checks so contributors do not think they have to take any action.

**Comment by CaseyHillers** [comment]
\cc @godofredoc

**Comment by CaseyHillers** [comment]
Update: It looks like when a job now gets assigned for that PR, it will update to the pending status. However, jobs waiting in queue are still marked as failing with a red X.

**Comment by godofredoc** [comment]
The behavior for pending status was changed. Now the tasks will get the status set to pending immediately after they get triggered.
