### ISSUE TITLE
`flutter run --debug` on iOS device shows me old logs

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4874]
Even for bugs I've already fixed, which is confusing.  We must not be clearing the logs correctly?

@devoncarew

**Comment by Hixie** [comment]
Punting to m4 since this isn't on the current priority list.

**Comment by jonahwilliams** [comment]
This was fixed by way of losing the ability to see logs directly on iOS. The logs gleaned from the dart observatory should be up to date.

**Comment by dfmiller** [comment]
This is happening on Android as well.

**Comment by brianegan** [comment]
Seems to be happening to me again as well -- tried Android but not iOS. Agreed it's a bit confusing!

**Comment by amugofjava** [comment]
This has started happening to me as well on Android - since upgrading to 1.12 stable. If I restart the device/emulator the logs are cleared, but begin to build up again with every run. It's incredibly confusing.
