### ISSUE TITLE
Missing crash information

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#48745]
After update to latest vs code and flutter version I dont receive crash information

════════ Exception caught by gesture ═══════════════════════════════════════════
The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator

Before update I saw callstack and filename and linenumber where crash happened. Now I see text above without helpful information

**Comment by dnfield** [comment]
Can you please share a project that reproduces this issue, and the output of `flutter doctor -v`?

**Comment by alex9153** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale ru-RU)
    • Flutter version 1.12.13+hotfix.5 at /Users/aleks/Documents/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aleks/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/aleks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • ZB602KL                   • J6AXB7654974VZ8 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554   • android-x86   • Android 10 (API 29) (emulator)

• No issues found!

**Comment by dnfield** [comment]
We still need a reproduction for this.  Can you add one?

**Comment by goderbauer** [comment]
Closing this due to lack of response.
