### ISSUE TITLE
Remove --fast-start command line flag

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#48762]
When the feature was off by default, the command line flag was the only way to enable it. If on by default works out, there is no reason to leave the flag there and it can be removed.

**Comment by zanderso** [comment]
@jonahwilliams Is there still a chance that this could be turned on by default?

**Comment by jonahwilliams** [comment]
Yes, though there is a bit more work to do. The last known major blocker is getting android alarm manager to accept hot restarts https://github.com/flutter/flutter/issues/52146.
