### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(photo_access_denied, The user did not allow photo access., null)

### ISSUE THREAD

**Issue by evanezcent** [flutter/flutter#48779]
Does anyone know, how to solve this proble, I am using image picker version 0.6.3

**Comment by dnfield** [comment]
The user decided to not give your app access to photos. You can try to handle this exception and inform the user that this disables some functionality in the app.

This is not a bug in the framework though or a feature request - it would be better asked on a site like StackOverflow.com
