### ISSUE TITLE
Configure devicelab Windows machines to run FDE desktop applications

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#48787]
These machines will require a recent-ish version of Visual Studio (see also: https://github.com/flutter/flutter/issues/48782). Set up should ideally be automated, but if necessary we could configure a single machine for now and restrict with capabilities.

**Comment by godofredoc** [comment]
We currently have only two windows machines I think we are ok with setting up both of them

**Comment by godofredoc** [comment]
\cc @yusufm

**Comment by stuartmorgan** [comment]
I think this is probably obsoleted by https://github.com/flutter/flutter/issues/54295

**Comment by godofredoc** [comment]
Awesome, thanks for the update.
