### ISSUE TITLE
local_auth UI problems : Red color mixed with green on fingerprints UI during authorisation.

### ISSUE THREAD

**Issue by sohitEngg** [flutter/flutter#48781]
I've implemented the local_auth in my current application which is working fine on every device except **One plus 5** where I am facing a weird UI issue. Fingerprints works successfully but display shows a mixture of red and green instead of only green. 

I have attached a screenshot for the reference. Please let me know if this is a known issue or there is a fix for this. Thanks in advance.

More Details: 
local_auth : ^0.6.1
Phone: One plus 5
Android Version: 9

<img width="378" alt="Screenshot 2020-01-14 at 10 32 37 AM" src="https://user-images.githubusercontent.com/28650662/72316067-eb6fa180-36ba-11ea-8728-9c751d083579.png">

**Comment by iapicca** [comment]
Hi @sohitEngg 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by sohitEngg** [comment]
Thanks for your prompt reply.

Here is my flutter doctor report:

Stock15840:<proj_name> <user-name>$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
This UI comes from the OS, so is beyond the control of the plugin.

If you are seeing different behavior when compared to a non-Flutter app on the same device, please let me know and we can debug that, but I would assume it would be the same.
