### ISSUE TITLE
When get exception, using web view with other widgets

### ISSUE THREAD

**Issue by Nyamkhuub** [flutter/flutter#48780]
Hello developers!
If I delete my web view, my code working is fine. But If I am using web veiw, I got some exception.
Here is my exception:
> E/MethodChannel#flutter_webview_plugin(20163): Failed to handle method call
> E/MethodChannel#flutter_webview_plugin(20163): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

Here's my code:
```
Swiper(
            itemHeight: MediaQuery.of(context).size.height*0.8,
            itemWidth: MediaQuery.of(context).size.width*0.8,
            itemCount: vocabularies.length,
            layout: SwiperLayout.TINDER,
            itemBuilder: (BuildContext context, int index) {
              DocumentSnapshot data = vocabularies.elementAt(index);
              var audioUrl = vUrl + data.data['audio'];
              return Material(
                  elevation: 4,
                  borderRadius: BorderRadius.all(Radius.circular(6)),
                  child: Container(
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.all(Radius.circular(6)),
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          Container(
                            height: 50.0,
                            child: WebviewScaffold(
                              url: audioUrl,
                            ),
                          ),
                         other stuffs...
```
Help me!

**Comment by iapicca** [comment]
Hi @Nyamkhuub 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` and 
a reproducible minimal code sample?
Thank you

**Comment by Nyamkhuub** [comment]
Dear @iapicca 
Thanks a lot, I am beginner. When I use second command of yours, app doesn't have any trouble.

**Comment by Nyamkhuub** [comment]
It doesn't solve!
My fault, but still I have a problem. Here is my exception
This exception got when I am trying to add web view into swiper item.
My using packages:
-swipe_stack: ^1.0.0
-flutter_webview_plugin: ^0.3.10+1
```
java.lang.IllegalStateException: The specified child
already has a parent. You must call removeView() on the child's parent first.
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addViewInner(ViewGroup.java:4656)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addView(ViewGroup.java:4497)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addView(ViewGroup.java:4469)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.policy.PhoneWindow.addContentView(PhoneWindow.java:496)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.app.Activity.addContentView(Activity.java:2601)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.flutter_webview_plugin.FlutterWebviewPlugin.openUrl(FlutterWebviewPlugin.java:143)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.flutter_webview_plugin.FlutterWebviewPlugin.onMethodCall(FlutterWebviewPlugin.java:53)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[  +15 ms] E/MethodChannel#flutter_webview_plugin(17202):       at android.os.MessageQueue.nativePollOnce(Native
Method)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.os.MessageQueue.next(MessageQueue.java:323)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at android.os.Looper.loop(Looper.java:136)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.app.ActivityThread.main(ActivityThread.java:6682)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
[        ] E/MethodChannel#flutter_webview_plugin(17202): Failed to handle method call
[        ] E/MethodChannel#flutter_webview_plugin(17202): java.lang.IllegalStateException: The specified child
already has a parent. You must call removeView() on the child's parent first.
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addViewInner(ViewGroup.java:4656)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addView(ViewGroup.java:4497)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.view.ViewGroup.addView(ViewGroup.java:4469)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.policy.PhoneWindow.addContentView(PhoneWindow.java:496)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.app.Activity.addContentView(Activity.java:2601)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.flutter_webview_plugin.FlutterWebviewPlugin.openUrl(FlutterWebviewPlugin.java:143)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.flutter_webview_plugin.FlutterWebviewPlugin.onMethodCall(FlutterWebviewPlugin.java:53)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at android.os.MessageQueue.nativePollOnce(Native
Method)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.os.MessageQueue.next(MessageQueue.java:323)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at android.os.Looper.loop(Looper.java:136)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
android.app.ActivityThread.main(ActivityThread.java:6682)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
[        ] E/MethodChannel#flutter_webview_plugin(17202):       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
[   +5 ms] E/flutter (17202): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(error, The specified child already has a parent. You must call removeView() on the child's
parent first., null)
```

**Comment by iapicca** [comment]
Hi @Nyamkhuub 

If you believe the issue depends from the 3rd party packages
[swipe_stack](https://pub.dev/packages/swipe_stack) [[github](https://github.com/gmetekorkmaz/SwipeStack/issues)] and [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) [[github](https://github.com/fluttercommunity/flutter_webview_plugin/issues)]
you may want to consider opening an issue in the dedicate github,
if you believe the issue is within flutter itself 
please provide your `flutter doctor -v` 
and a **reproducible** minimal code sample (without 3rd party plugins)
Thank you

**Comment by avinash-tripathi** [comment]
I also got the same kind of error. 
Infact i removed my webview code then also somehow flutter remind the previous one.

E/flutter ( 6053): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, The specified child already has a parent. You must call removeView() on the child's parent first., null)     
E/flutter ( 6053): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6053): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 6053): <asynchronous suspension>
E/flutter ( 6053): #2      FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:225:20)
E/flutter ( 6053): #3      _WebviewScaffoldState.build.<anonymous closure> (package:flutter_webview_plugin/src/webview_scaffold.dart:156:30)      
E/flutter ( 6053): #4      _WebviewPlaceholderRender.notifyRect (package:flutter_webview_plugin/src/webview_scaffold.dart:246:7)
E/flutter ( 6053): #5      _WebviewPlaceholderRender.paint (package:flutter_webview_plugin/src/webview_scaffold.dart:256:7)
E/flutter ( 6053): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
E/flutter ( 6053): #9      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:396:5)
E/flutter ( 6053): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
E/flutter ( 6053): #13     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:530:11)
E/flutter ( 6053): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
E/flutter ( 6053): #17     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
E/flutter ( 6053): #18     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1755:15)
E/flutter ( 6053): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #21     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
E/flutter ( 6053): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
E/flutter ( 6053): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #26     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
E/flutter ( 6053): #27     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
E/flutter ( 6053): #28     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
E/flutter ( 6053): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
E/flutter ( 6053): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
E/flutter ( 6053): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #33     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:640:17)
E/flutter ( 6053): #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #36     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:275:15)
E/flutter ( 6053): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
E/flutter ( 6053): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 6053): #39     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:531:17)
E/flutter ( 6053): #40     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
E/flutter ( 6053): #41     PaintingContext.pushClipRect (package:flut
E/chromium( 6053): [ERROR:gl_surface_egl.cc(342)] eglChooseConfig failed 
with error EGL_SUCCESS
I/VideoCapabilities( 6053): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 6053): HW encoder for video/avc is not available on 
this device.
D/NetworkSecurityConfig( 6053): No Network Security Config specified, using platform default
I/kirananet.debu( 6053): NativeAlloc concurrent copying GC freed 23109(1061KB) AllocSpace objects, 2(104KB) LOS objects, 49% free, 1861KB/3723KB, 
paused 926us total 120.813ms
D/EGL_emulation( 6053): eglCreateContext: 0xb3d5e5c0: maj 2 min 0 rcv 2
D/EGL_emulation( 6053): eglMakeCurrent: 0xb3d5e5c0: ver 2 0 (tinfo 0xb45542a0)
W/kirananet.debu( 6053): Long monitor contention with owner TaskSchedulerFo (6780) at org.chromium.net.AndroidCertVerifyResult org.chromium.net.X509Util.a(byte[][], java.lang.String, java.lang.String)(PG:112) waiters=0 
in void org.chromium.net.X509Util.a() for 299ms
I/kirananet.debu( 6053): Background young concurrent copying GC freed 45422(1761KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 2006KB/3723KB, paused 4.200ms total 167.387ms
