### ISSUE TITLE
Configure devicelab linux machines to run FDE desktop applications

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#48786]
The requirements for Linux FDE are fairly mild, some recent-ish version of Make, clang, and some GLFW libraries. It might even just work (tm).

**Comment by stuartmorgan** [comment]
> and some GLFW libraries

Nope, GLFW is statically built into the engine library these days, so it's even simpler.

**Comment by godofredoc** [comment]
\cc @gspencergoog this is related to linux VMs not being able to run desktop applications.

**Comment by godofredoc** [comment]
The new ubuntu images should cover this scenario, please reopen if it still does not work.
