### ISSUE TITLE
red breakpoints appear but not working in debug mode

### ISSUE THREAD

**Issue by Tabarek** [flutter/flutter#48789]
every time I want to debug my flutter project 
the debugger does not stop on the breakpoints like there are no breakpoints 
even so the uncached exception and all exceptions bottoms in the debugger are working 

my 

> launch.json

 file

    {
        "version": "0.2.0",
        "configurations": [{
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": [
                "--debug",
                "dev"
            ],
        }]
    }

I tried the default launch.json configurations but it's didn't work 

    {
            "version": "0.2.0",
        "configurations": [
            {
                "name": "Flutter",
                "request": "launch",
                "type": "dart"
            }
        ]
    }

**Comment by iapicca** [comment]
Hi @Tabarek 
I suspect you are referring to a VS Code plugin issue
if so please the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter);
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/Dart-Code/Dart-Code/issues)


Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by DanTup** [comment]
@Tabarek can you reproduce this in a project you can share?

**Comment by escamoteur** [comment]
Also does this happen in all projects?

**Comment by Tabarek** [comment]
@escamoteur no only in my released project

**Comment by Tabarek** [comment]
@DanTup this happens only in my released project, in the other projects (which are not published) it works well

**Comment by iapicca** [comment]
Hi @Tabarek 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` while debugging your project
and if possible a reproducible minimal code sample.
Thank you

**Comment by DanTup** [comment]
@Tabarek can you easily try in Android Studio or DevTools to see if they breakpoints work there? If using DevTools you'll want to run the app from the terminal (with `flutter run`) and also DevTools from the terminal (`pub global activate devtools && pub global run devtools`) (there are debugging instructions for DevTools [here](https://flutter.dev/docs/development/tools/devtools/debugger)).

**Comment by darshankawar** [comment]
Considering the age of the issue and lack of activity, I am going ahead and closing this as stale.

@Tabarek  If you are still experiencing this issue using latest stable version, please open a new issue using template so that we can address it.
If anybody disagrees, please write in comments and I'll reopen it.
