### ISSUE TITLE
'Adding a Flutter screen to an Android app'  How to specify initialRoute with cache engine

### ISSUE THREAD

**Issue by Vadaski** [flutter/flutter#48791]
Page URL: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-flutter-screen.md

I read this article and found that when I use newEngine I can specify Flutter's initialRoute like this.
``` java
myButton.addOnClickListener(new OnClickListener() {
  @Override
  public void onClick(View v) {
    startActivity(
      FlutterActivity
        .withNewEngine()
        .initialRoute("/my_route")
        .build(currentActivity)
      );
  }
});
```
But when using cacheEngine, I didn’t find such methods. So can we use both cacheEngine and initialRoute？

**Comment by xster** [comment]
@matthew-carroll can we add some clarifications to the website?

I know the API isn't ideal right now. Maybe we can just put a workaround in a tip box for now since whether we document it or not, this will be a recurring question.

**Comment by matthew-carroll** [comment]
To answer the questions in this thread...

> So can we use both cacheEngine and initialRoute？

When configuring a `FlutterActivity` or `FlutterFragment` to use a cached `FlutterEngine`, no, you cannot specify an initial route. An initial route only makes sense if it's configured *before* starting a `FlutterEngine`. A cached engine, by definition, is a `FlutterEngine` that is already started. Therefore, the concept of an initial route does not make sense.

If you have a requirement that is not covered by a new engine or a cached engine, please let us know what use-cases you're dealing with and we can see if it makes sense to extend the API.

> so we should open a new flutter page with new engine everytime?

Not necessarily. If you want to configure an initial route using the API for `FlutterActivity` or `FlutterFragment`, then yes, you need to use a new `FlutterEngine`. However, you don't need to use those APIs to set an initial route. If you look at the instructions for creating a cached `FlutterEngine` here (https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-3-optional-use-a-cached-flutterengine) then just before you invoke `executeDartEntrypoint()` you can invoke:

```
flutterEngine.getNavigationChannel().setInitialRoute('my/route');
```

@xster I'll add instructions to the website guide for setting an initial route when creating a cached engine. I'm not sure where it would be appropriate to add comments in code - we can't really comment on a method that doesn't exist. Also, you mentioned the API isn't ideal. I think this part of the API makes sense. What kind of API do you think would be preferable?

**Comment by zmtzawqlp** [comment]
@matthew-carroll  thanks for your reply, but i want to make things clear.
nativeA page=>flutterA page =>nativeB page=>flutterB page
is there any way that initial flutterA and flutterB with one cache engine? every new engine means more memory usage. This is what i want to konw , thanks.

**Comment by matthew-carroll** [comment]
@zmtzawqlp you can definitely use the same `FlutterEngine` across subsequent pages as you described. But "initial route" will only set the very first route that a given `FlutterEngine` loads.

It sounds like what you want is to change the route of a `FlutterEngine` between pages. This is absolutely possible, but it currently requires that you implement that behavior yourself using method channels. The Flutter team intends to eventually provide built-in support for your use-case, but we're still collecting customer requirements to determine what that answer should look like.

In your case, you'll want to setup a method channel that does the following:

* On the Java side, set up the channel so that you can send route names from Java to Dart
* On the Dart side, whenever your channel receives a route name from Java, instruct your `Navigator` widget to switch to the given route.

Does that make sense?

**Comment by zmtzawqlp** [comment]
@matthew-carroll  yes, I got your point, FlutterA and FlutterB will in the same page stack, but it's difficult to control both native page stack and flutter page stack. Thank you very much for clarification, I'm look forward to that Flutter team will provide official way.

**Comment by Vadaski** [comment]
> @zmtzawqlp you can definitely use the same `FlutterEngine` across subsequent pages as you described. But "initial route" will only set the very first route that a given `FlutterEngine` loads.
> 
> It sounds like what you want is to change the route of a `FlutterEngine` between pages. This is absolutely possible, but it currently requires that you implement that behavior yourself using method channels. The Flutter team intends to eventually provide built-in support for your use-case, but we're still collecting customer requirements to determine what that answer should look like.
> 
> In your case, you'll want to setup a method channel that does the following:
> 
> * On the Java side, set up the channel so that you can send route names from Java to Dart
> * On the Dart side, whenever your channel receives a route name from Java, instruct your `Navigator` widget to switch to the given route.
> 
> Does that make sense?

Yes, It looks similar to the previous solution, Flutter Boost also uses this method, it should be feasible, thank you for your reply!

**Comment by matthew-carroll** [comment]
Based on conversation in this thread, and @xster's comment near the top, I think the only actionable change is to add some info to Flutter's guides about using initial routes with cached engines. I added docs for that case here:

https://github.com/flutter/website/pull/3551

The new initial route info can be found in the following guides:

https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen

https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment

I'm going to close this issue.
