### ISSUE TITLE
Verify text from TextSpan widget using flutter_driver

### ISSUE THREAD

**Issue by longk15t** [flutter/flutter#48797]
This could be related to https://github.com/flutter/flutter/issues/16013 but I tried the last solution
`await driver.waitFor(find.text("my string"));`
and it doesn't work for TextSpan widget.

Please provide a solution.

**Comment by Xavjer** [comment]
#48809 should resolve this issue. I did not include TextSpan directly, but you can search the RichText of it. Hope this will work for you

**Comment by longk15t** [comment]
@Xavjer you are Xavjer and a savior

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/48809 is merged, closing.

**Comment by hainguyen168** [comment]
hi @longk15t , 

I still meet this issue like yours with latest flutter driver version. Could you share how did you resolve this?

**Comment by Xavjer** [comment]
@hainguyen168 Which branch are you using? This is currently in master, dev and beta, but not in stable yet.

If you are not on stable, then please give a sample code which does not work for you and I can check it

**Comment by hainguyen168** [comment]
Thanks @Xavjer ,
I tried the master channel and got it works.
