### ISSUE TITLE
Problem in running flutter web page or web application

### ISSUE THREAD

**Issue by DANIELDANEE** [flutter/flutter#48808]
HERE IS THE CODES CONTAINING THE ERRORS DISPLAY UNDER THE TERMINAL IN VISUAL STUDIO CODED

 flutter packages pub global run webdev serve
```bash
webdev could not run for this project.
You must have a dependency on `build_runner` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_runner: >=1.6.2 <2.0.0
You must have a dependency on `build_web_compilers` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_web_compilers: >=1.2.0 <3.0.0
You have a dependency on `cupertino_icons` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter_test` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78
```

**Comment by iapicca** [comment]
Hi @DANIELDANEE 
can you please provide your `flutter doctor -v` 
and your `flutter run -d chrome--verbose` ^ `flutter build web --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
