### ISSUE TITLE
How To Fix NoSuchMethodError: The getter 'genderCode' was called on null ??

### ISSUE THREAD

**Issue by rakafajar** [flutter/flutter#48801]
I'm making a few searches ... but a little compilation of doing that search ... there is a message NoSuchMethodError: The getter 'genderCode' is called null.

> [√] Flutter (Channel unknown, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18363.535], locale en-ID)
>     • Flutter version 1.9.1+hotfix.4 at C:\Android Flutter\flutter
>     • Framework revision cc949a8e8b (4 months ago), 2019-09-27 15:04:59 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\rakaf\AppData\Local\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = C:\Users\rakaf\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code (version 1.41.1)
>     • VS Code at C:\Users\rakaf\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.7.1
> 
> [√] Connected device (1 available)
>     • G011A • 127.0.0.1:21503 • android-x86 • Android 5.1.1 (API 22)

> Error Message : 
I/flutter ( 2218): NoSuchMethodError: The getter 'genderCode' was called on null.
I/flutter ( 2218): Receiver: null
I/flutter ( 2218): Tried calling: genderCode

```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:huntstreet/model/product/filter.dart';
import 'package:rxdart/rxdart.dart';

import '../../../model/product/product.dart';
import '../../../model/product/product_list.dart';
import '../../../service/api_service.dart';
import '../../../service/repository.dart';
import 'bloc.dart';

class ProductListBloc extends Bloc<ProductListEvent, ProductListState> {
  Repository _repository = Repository();
  Filter currentFilter;

  @override
  ProductListState get initialState => ProductListInitial();

  @override
  Stream<ProductListState> transformEvents(
    Stream<ProductListEvent> events,
    Stream<ProductListState> Function(ProductListEvent event) next,
  ) {
    return super.transformEvents(
      (events as Observable<ProductListEvent>).debounceTime(
        Duration(
          milliseconds: 250,
        ),
      ),
      next,
    );
  }

  @override
  Stream<ProductListState> mapEventToState(ProductListEvent event) async* {
    ProductListState currentState = state;
    bool _isReachedMax = !_hasReachedMax(currentState);
    if (event is GetNewArrivalProductList) {
      yield* _mapGetNewArrivalProductList();
    } else if (event is GetSaleProductList) {
      yield* _mapGetSaleProductList();
    } else if (event is GetProductListByFilter) {
      yield* _mapGetProductListByFilter(event, currentState);
    }
  }

  bool _hasReachedMax(ProductListState state) {
    return state is SearchProductByFilter && state.hasReachedMax;
  }

  Stream<ProductListState> _mapGetNewArrivalProductList() async* {
    yield ProductListLoading();
    try {
      List<Product> newArrival = await _repository.fetchProducts(
        showProduct: ShowProduct.newArrival,
      );
      yield ProductListLoaded(
        product: newArrival,
      );
    } catch (e) {
      ProductListError(
        message: "$e",
      );
    }
  }

  Stream<ProductListState> _mapGetSaleProductList() async* {
    yield ProductListLoading();
    try {
      List<Product> sale = await _repository.fetchProducts(
        showProduct: ShowProduct.sale,
      );
      yield ProductListLoaded(
        product: sale,
      );
    } catch (e) {
      ProductListError(
        message: "$e",
      );
    }
  }

  Stream<ProductListState> _mapGetProductListByFilter(
      GetProductListByFilter event, ProductListState currentState) async* {
    try {
      if (currentState is ProductListInitial) {
        Filter filter = Filter(
          query: event?.query ?? "",
          show: event?.show ?? "24",
          genderCode: event?.genderCode ?? "",
          designerCodes: event?.designerCodes ?? "",
          colorCode: event?.colorCode ?? "",
          categoryCode: event?.categoryCode ?? "",
          page: event?.page ?? "",
          conditionIds: event.conditionIds ?? "",
          sizeIds: event.sizeIds ?? "",
          priceMax: event?.priceMax ?? "",
          priceMin: event?.priceMin ?? "",
          productTypeCode: event?.productTypeCode ?? "",
          productTypeDetailIds: event?.productTypeDetailIds ?? "",
        );
        print(filter.genderCode);
        print(filter.categoryCode);
        yield ProductListLoading();
        ProductList productList;
        currentFilter = filter;
        try {
          productList = await _repository.fetchListBySearch(
            filter: filter,
          );
          print('berhasil list raka list muncul semua');
        } catch (e) {
          print(e);
        }
        if (productList.data.products.isEmpty) {
          yield ProductListEmpty();
        } else {
          yield ProductListLoading();
          yield SearchProductByFilter(
            productsList: productList,
            hasReachedMax: false,
            filter: filter,
            product: productList.data.products,
          );
        }
      }
      if (currentState is SearchProductByFilter) {
        print('apakah ini null raka 2? ${event.productTypeCode}');
        print('Ini Gender apa ayo ? ${event.genderCode}');
        print('ini Category Masuk apa engga ? ${event.categoryCode}');
        print('ini page berapa ? ${event.page}');
        print('ini Show brp ? ${event.show}');

        Filter filter = Filter(
          query: event.query ?? "",
          show: event.show ?? "24",
          genderCode: currentState.filter.genderCode.isNotEmpty
              ? currentState.filter.genderCode
              : event.genderCode ?? "",
          designerCodes:
              event.designerCodes ?? currentState.filter.designerCodes,
          colorCode: event.colorCode ?? currentState.filter.colorCode,
          categoryCode: currentState.filter.categoryCode.isNotEmpty
              ? currentState.filter.categoryCode
              : event.categoryCode ?? "",
          page: event.page ?? "1",
          conditionIds: event.conditionIds ?? currentState.filter.conditionIds,
          sizeIds: event.sizeIds ?? currentState.filter.sizeIds,
          priceMax: event.priceMax ?? currentState.filter.priceMax,
          priceMin: event.priceMin ?? currentState.filter.priceMin,
          productTypeCode:
              event.productTypeCode ?? currentState.filter.productTypeCode,
          productTypeDetailIds: event.productTypeDetailIds ??
              currentState.filter.productTypeDetailIds,
        );

        print(filter.toString());
        print(currentState.filter.toString());
        print(isFilterEmpty(filter));
        if (!isNewFilter(
          filter: filter,
          currentFilter: currentState.filter,
        )) {
          yield ProductListLoading();
          ProductList productList;
          currentFilter = filter;
          try {
            productList = await _repository.fetchListBySearch(
              filter: filter,
            );
            print('berhasil list raka list di filter muncul');
          } catch (e) {
            print(e);
          }
          print(productList.data.products.isEmpty);
          if (productList.data.products.isEmpty) {
            yield ProductListEmpty();
          } else {
            yield SearchProductByFilter(
              productsList: productList,
              hasReachedMax: false,
              filter: filter,
              product: productList.data.products,
            );
          }
        } else {
          try {
            print('masuk searchproductbyfilter');
            ProductList productList = await _repository.fetchListBySearch(
              filter: Filter(
                query: currentState.filter.query,
                page: "${currentState.productsList.data.meta.currentPage + 1}",
                genderCode: currentState.filter.genderCode,
                categoryCode: currentState.filter.categoryCode,
                show: "24",
                sizeIds: currentState.filter.sizeIds,
                designerCodes: currentState.filter.designerCodes ?? "",
                colorCode: currentState.filter.colorCode ?? "",
                conditionIds: currentState.filter.conditionIds ?? "",
                priceMax: currentState.filter.priceMax ?? "",
                priceMin: currentState.filter.priceMin ?? "",
                productTypeCode: currentState.filter.productTypeCode ?? "",
                productTypeDetailIds:
                    currentState.filter.productTypeDetailIds ?? "",
              ),
            );
            print(productList.data.products.isEmpty);
            yield productList.data.products.isEmpty
                ? currentState.copyWith(
                    hasReachedMax: true, product: currentState.product)
                : SearchProductByFilter(
                    productsList: productList,
                    filter: currentState.filter,
                    hasReachedMax: false,
                    product: currentState.product + productList.data.products,
                  );
          } catch (e) {
            print(e);
          }
        }
      }
    } catch (e) {
      print(e);
      ProductListError(
        message: "$e",
      );
    }
  }

  bool isNewFilter({Filter filter, Filter currentFilter}) {
    return filter.query == currentFilter.query &&
        filter.productTypeCode == currentFilter.productTypeCode &&
        filter.categoryCode == currentFilter.categoryCode &&
        filter.productTypeDetailIds == currentFilter.productTypeDetailIds &&
        filter.priceMin == currentFilter.priceMin &&
        filter.priceMax == currentFilter.priceMax &&
        filter.sizeIds == currentFilter.sizeIds &&
        filter.colorCode == currentFilter.colorCode &&
        filter.genderCode == currentFilter.genderCode &&
        filter.designerCodes == currentFilter.designerCodes;
  }

  bool isFilterEmpty(Filter filter) {
    return filter.query.isEmpty &&
        filter.productTypeCode.isEmpty &&
        filter.categoryCode.isEmpty &&
        filter.productTypeDetailIds.isEmpty &&
        filter.priceMin.isEmpty &&
        filter.priceMax.isEmpty &&
        filter.sizeIds.isEmpty &&
        filter.colorCode.isEmpty &&
        filter.genderCode.isEmpty &&
        filter.designerCodes.isEmpty;
  }
}

enum SelectFilter {
  byGender,
  byCategory,
}
```

**Comment by Zazo032** [comment]
You may use null safe operators to access properties on objects that can be `null`. It would be really useful if you could provide the exact line that is throwing that error. To quickly fix it, you could change, for example:
```dart
  print(filter.genderCode);
```
to:
```dart
  print(filter?.genderCode ?? '');
```
More info:
https://dart.dev/guides/language/language-tour#classes
https://medium.com/@thinkdigitalsoftware/null-aware-operators-in-dart-53ffb8ae80bb

**Comment by rakafajar** [comment]
> You may use null safe operators to access properties on objects that can be `null`. It would be really useful if you could provide the exact line that is throwing that error. To quickly fix it, you could change, for example:
> 
> ```dart
>   print(filter.genderCode);
> ```
> 
> to:
> 
> ```dart
>   print(filter?.genderCode ?? '');
> ```
> 
> More info:
> https://dart.dev/guides/language/language-tour#classes
> https://medium.com/@thinkdigitalsoftware/null-aware-operators-in-dart-53ffb8ae80bb

the advice you gave didn't work properly ... but it was approved that my code like this can be printed ('What gender is this? $ {event.genderCode}');

![Annotation 2020-01-14 210418](https://user-images.githubusercontent.com/29575965/72350673-7b403a80-3711-11ea-8bea-e8971dc80d40.png)

**Comment by Zazo032** [comment]
That was just an example, could you provide which line was throwing the error? Also, the output of `flutter doctor -v`.

**Comment by rakafajar** [comment]
> I'm making a few searches ... but a little compilation of doing that search ... there is a message NoSuchMethodError: The getter 'genderCode' is called null.
> 
> > [√] Flutter (Channel unknown, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18363.535], locale en-ID)
> > • Flutter version 1.9.1+hotfix.4 at C:\Android Flutter\flutter
> > • Framework revision [cc949a8](https://github.com/flutter/flutter/commit/cc949a8e8b9cf394b9290a8e80f87af3e207dce5) (4 months ago), 2019-09-27 15:04:59 -0700
> > • Engine revision b863200c37
> > • Dart version 2.5.0
> > [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> > • Android SDK at C:\Users\rakaf\AppData\Local\Android\Sdk
> > • Android NDK location not configured (optional; useful for native profiling support)
> > • Platform android-29, build-tools 29.0.2
> > • ANDROID_HOME = C:\Users\rakaf\AppData\Local\Android\Sdk
> > • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> > • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> > • All Android licenses accepted.
> > [√] Android Studio (version 3.5)
> > • Android Studio at C:\Program Files\Android\Android Studio
> > • Flutter plugin version 42.1.1
> > • Dart plugin version 191.8593
> > • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> > [√] VS Code (version 1.41.1)
> > • VS Code at C:\Users\rakaf\AppData\Local\Programs\Microsoft VS Code
> > • Flutter extension version 3.7.1
> > [√] Connected device (1 available)
> > • G011A • 127.0.0.1:21503 • android-x86 • Android 5.1.1 (API 22)
> 
> > Error Message :
> > I/flutter ( 2218): NoSuchMethodError: The getter 'genderCode' was called on null.
> > I/flutter ( 2218): Receiver: null
> > I/flutter ( 2218): Tried calling: genderCode
> 
> ```
> import 'dart:async';
> 
> import 'package:bloc/bloc.dart';
> import 'package:huntstreet/model/product/filter.dart';
> import 'package:rxdart/rxdart.dart';
> 
> import '../../../model/product/product.dart';
> import '../../../model/product/product_list.dart';
> import '../../../service/api_service.dart';
> import '../../../service/repository.dart';
> import 'bloc.dart';
> 
> class ProductListBloc extends Bloc<ProductListEvent, ProductListState> {
>   Repository _repository = Repository();
>   Filter currentFilter;
> 
>   @override
>   ProductListState get initialState => ProductListInitial();
> 
>   @override
>   Stream<ProductListState> transformEvents(
>     Stream<ProductListEvent> events,
>     Stream<ProductListState> Function(ProductListEvent event) next,
>   ) {
>     return super.transformEvents(
>       (events as Observable<ProductListEvent>).debounceTime(
>         Duration(
>           milliseconds: 250,
>         ),
>       ),
>       next,
>     );
>   }
> 
>   @override
>   Stream<ProductListState> mapEventToState(ProductListEvent event) async* {
>     ProductListState currentState = state;
>     bool _isReachedMax = !_hasReachedMax(currentState);
>     if (event is GetNewArrivalProductList) {
>       yield* _mapGetNewArrivalProductList();
>     } else if (event is GetSaleProductList) {
>       yield* _mapGetSaleProductList();
>     } else if (event is GetProductListByFilter) {
>       yield* _mapGetProductListByFilter(event, currentState);
>     }
>   }
> 
>   bool _hasReachedMax(ProductListState state) {
>     return state is SearchProductByFilter && state.hasReachedMax;
>   }
> 
>   Stream<ProductListState> _mapGetNewArrivalProductList() async* {
>     yield ProductListLoading();
>     try {
>       List<Product> newArrival = await _repository.fetchProducts(
>         showProduct: ShowProduct.newArrival,
>       );
>       yield ProductListLoaded(
>         product: newArrival,
>       );
>     } catch (e) {
>       ProductListError(
>         message: "$e",
>       );
>     }
>   }
> 
>   Stream<ProductListState> _mapGetSaleProductList() async* {
>     yield ProductListLoading();
>     try {
>       List<Product> sale = await _repository.fetchProducts(
>         showProduct: ShowProduct.sale,
>       );
>       yield ProductListLoaded(
>         product: sale,
>       );
>     } catch (e) {
>       ProductListError(
>         message: "$e",
>       );
>     }
>   }
> 
>   Stream<ProductListState> _mapGetProductListByFilter(
>       GetProductListByFilter event, ProductListState currentState) async* {
>     try {
>       if (currentState is ProductListInitial) {
>         Filter filter = Filter(
>           query: event?.query ?? "",
>           show: event?.show ?? "24",
>           genderCode: event?.genderCode ?? "",
>           designerCodes: event?.designerCodes ?? "",
>           colorCode: event?.colorCode ?? "",
>           categoryCode: event?.categoryCode ?? "",
>           page: event?.page ?? "",
>           conditionIds: event.conditionIds ?? "",
>           sizeIds: event.sizeIds ?? "",
>           priceMax: event?.priceMax ?? "",
>           priceMin: event?.priceMin ?? "",
>           productTypeCode: event?.productTypeCode ?? "",
>           productTypeDetailIds: event?.productTypeDetailIds ?? "",
>         );
>         print(filter.genderCode);
>         print(filter.categoryCode);
>         yield ProductListLoading();
>         ProductList productList;
>         currentFilter = filter;
>         try {
>           productList = await _repository.fetchListBySearch(
>             filter: filter,
>           );
>           print('berhasil list raka list muncul semua');
>         } catch (e) {
>           print(e);
>         }
>         if (productList.data.products.isEmpty) {
>           yield ProductListEmpty();
>         } else {
>           yield ProductListLoading();
>           yield SearchProductByFilter(
>             productsList: productList,
>             hasReachedMax: false,
>             filter: filter,
>             product: productList.data.products,
>           );
>         }
>       }
>       if (currentState is SearchProductByFilter) {
>         print('apakah ini null raka 2? ${event.productTypeCode}');
>         print('Ini Gender apa ayo ? ${event.genderCode}');
>         print('ini Category Masuk apa engga ? ${event.categoryCode}');
>         print('ini page berapa ? ${event.page}');
>         print('ini Show brp ? ${event.show}');
> 
>         Filter filter = Filter(
>           query: event.query ?? "",
>           show: event.show ?? "24",
>           genderCode: currentState.filter.genderCode.isNotEmpty
>               ? currentState.filter.genderCode
>               : event.genderCode ?? "",
>           designerCodes:
>               event.designerCodes ?? currentState.filter.designerCodes,
>           colorCode: event.colorCode ?? currentState.filter.colorCode,
>           categoryCode: currentState.filter.categoryCode.isNotEmpty
>               ? currentState.filter.categoryCode
>               : event.categoryCode ?? "",
>           page: event.page ?? "1",
>           conditionIds: event.conditionIds ?? currentState.filter.conditionIds,
>           sizeIds: event.sizeIds ?? currentState.filter.sizeIds,
>           priceMax: event.priceMax ?? currentState.filter.priceMax,
>           priceMin: event.priceMin ?? currentState.filter.priceMin,
>           productTypeCode:
>               event.productTypeCode ?? currentState.filter.productTypeCode,
>           productTypeDetailIds: event.productTypeDetailIds ??
>               currentState.filter.productTypeDetailIds,
>         );
> 
>         print(filter.toString());
>         print(currentState.filter.toString());
>         print(isFilterEmpty(filter));
>         if (!isNewFilter(
>           filter: filter,
>           currentFilter: currentState.filter,
>         )) {
>           yield ProductListLoading();
>           ProductList productList;
>           currentFilter = filter;
>           try {
>             productList = await _repository.fetchListBySearch(
>               filter: filter,
>             );
>             print('berhasil list raka list di filter muncul');
>           } catch (e) {
>             print(e);
>           }
>           print(productList.data.products.isEmpty);
>           if (productList.data.products.isEmpty) {
>             yield ProductListEmpty();
>           } else {
>             yield SearchProductByFilter(
>               productsList: productList,
>               hasReachedMax: false,
>               filter: filter,
>               product: productList.data.products,
>             );
>           }
>         } else {
>           try {
>             print('masuk searchproductbyfilter');
>             ProductList productList = await _repository.fetchListBySearch(
>               filter: Filter(
>                 query: currentState.filter.query,
>                 page: "${currentState.productsList.data.meta.currentPage + 1}",
>                 genderCode: currentState.filter.genderCode,
>                 categoryCode: currentState.filter.categoryCode,
>                 show: "24",
>                 sizeIds: currentState.filter.sizeIds,
>                 designerCodes: currentState.filter.designerCodes ?? "",
>                 colorCode: currentState.filter.colorCode ?? "",
>                 conditionIds: currentState.filter.conditionIds ?? "",
>                 priceMax: currentState.filter.priceMax ?? "",
>                 priceMin: currentState.filter.priceMin ?? "",
>                 productTypeCode: currentState.filter.productTypeCode ?? "",
>                 productTypeDetailIds:
>                     currentState.filter.productTypeDetailIds ?? "",
>               ),
>             );
>             print(productList.data.products.isEmpty);
>             yield productList.data.products.isEmpty
>                 ? currentState.copyWith(
>                     hasReachedMax: true, product: currentState.product)
>                 : SearchProductByFilter(
>                     productsList: productList,
>                     filter: currentState.filter,
>                     hasReachedMax: false,
>                     product: currentState.product + productList.data.products,
>                   );
>           } catch (e) {
>             print(e);
>           }
>         }
>       }
>     } catch (e) {
>       print(e);
>       ProductListError(
>         message: "$e",
>       );
>     }
>   }
> 
>   bool isNewFilter({Filter filter, Filter currentFilter}) {
>     return filter.query == currentFilter.query &&
>         filter.productTypeCode == currentFilter.productTypeCode &&
>         filter.categoryCode == currentFilter.categoryCode &&
>         filter.productTypeDetailIds == currentFilter.productTypeDetailIds &&
>         filter.priceMin == currentFilter.priceMin &&
>         filter.priceMax == currentFilter.priceMax &&
>         filter.sizeIds == currentFilter.sizeIds &&
>         filter.colorCode == currentFilter.colorCode &&
>         filter.genderCode == currentFilter.genderCode &&
>         filter.designerCodes == currentFilter.designerCodes;
>   }
> 
>   bool isFilterEmpty(Filter filter) {
>     return filter.query.isEmpty &&
>         filter.productTypeCode.isEmpty &&
>         filter.categoryCode.isEmpty &&
>         filter.productTypeDetailIds.isEmpty &&
>         filter.priceMin.isEmpty &&
>         filter.priceMax.isEmpty &&
>         filter.sizeIds.isEmpty &&
>         filter.colorCode.isEmpty &&
>         filter.genderCode.isEmpty &&
>         filter.designerCodes.isEmpty;
>   }
> }
> 
> enum SelectFilter {
>   byGender,
>   byCategory,
> }
> ```


![image](https://user-images.githubusercontent.com/29575965/72351184-716b0700-3712-11ea-92b2-5bb40b57104e.png)

data is read in the console, but when you want to try the filter again the error message appears again

![image](https://user-images.githubusercontent.com/29575965/72351287-a4ad9600-3712-11ea-9b02-03ac3bc85d80.png)

**Comment by Zazo032** [comment]
As you have many try/catch blocks, could you identify which one of them is catching the error? Also, after identifying it, remove the try/catch so it throws the full error, including which line is throwing it.

**Comment by rakafajar** [comment]
> As you have many try/catch blocks, could you identify which one of them is catching the error? Also, after identifying it, remove the try/catch so it throws the full error, including which line is throwing it.

can you give a little example ?, I'm a little confused because this is the result of collaboration with my friend and I don't really understand BloC

**Comment by Zazo032** [comment]
You have many bode blocks (not BLoC) like this:
```dart
try {
  // Code
} catch (e) {
  print(e);
}
```
The error you are seeing in your console is being printed by one of those `print(e);` inside a `catch` code block. You will need to identify which one is printing that error, so you can identify which `try` code block is causing the error.

**Comment by rakafajar** [comment]
> You have many bode blocks (not BLoC) like this:
> 
> ```dart
> try {
>   // Code
> } catch (e) {
>   print(e);
> }
> ```
> 
> The error you are seeing in your console is being printed by one of those `print(e);` inside a `catch` code block. You will need to identify which one is printing that error, so you can identify which `try` code block is causing the error.


like this?
![image](https://user-images.githubusercontent.com/29575965/72353527-cc066200-3716-11ea-8497-e7e48a4028ba.png)

**Comment by rakafajar** [comment]
> You have many bode blocks (not BLoC) like this:
> 
> ```dart
> try {
>   // Code
> } catch (e) {
>   print(e);
> }
> ```
> 
> The error you are seeing in your console is being printed by one of those `print(e);` inside a `catch` code block. You will need to identify which one is printing that error, so you can identify which `try` code block is causing the error.

> I/flutter (26002): sdsdsdas null
> I/flutter (26002): berhasil list raka list di filter muncul
> I/flutter (26002): false
> I/flutter (26002): sdsds
> I/flutter (26002): bags
> I/flutter (26002): ini detail 1
> I/flutter (26002): ini detail 2
> I/flutter (26002): ini detail 5
> I/flutter (26002): bags
> I/flutter (26002): men
> I/flutter (26002): true
> I/flutter (26002):  
> I/flutter (26002): 24
> I/flutter (26002):
> I/flutter (26002): men
> I/flutter (26002): bags
> I/flutter (26002):
> I/flutter (26002):  
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002): 24
> I/flutter (26002):  
> I/flutter (26002): men
> I/flutter (26002): bags
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002):
> I/flutter (26002): false
> I/flutter (26002): masuk searchproductbyfilter raka ini
> I/flutter (26002): {"data":{"meta":{"total":9,"last_page":1,"per_page":"24","current_page":2},"products":[],"count_by_designer":{"list":{"2":1,"15":1,"54":1,"135":1,"188":3,"264":1,"468":1},"key":"410c33d36ef37d71990d23072a89656c"}}}
> I/flutter (26002): sdsdsdas null
> I/flutter (26002): true
> I/flutter (26002): sdsds
> I/flutter (26002): bags
> I/flutter (26002): ini detail 1
> I/flutter (26002): ini detail 2
> I/flutter (26002): ini detail 3
> I/flutter (26002): ini detail 5
> I/flutter (26002): bags
> I/flutter (26002): NoSuchMethodError: The getter 'genderCode' was called on null.
> I/flutter (26002): Receiver: null
> I/flutter (26002): Tried calling: genderCode

**Comment by dnfield** [comment]
1. Look at the full stack trace.  One of the frames near the top should point you to a line in your code that has code like `foo.genderCode`.
2. Make sure to null check `foo` before callling `foo.genderCode`.

Your code has several places where you do things like `print(foo.genderCode)`, or `blah = event.genderCode`.  The problem is that `foo` or `event` are null when this is called, causing an exception.  You can either do `foo?.genderCode` or `if (foo == null) { // logic to handle null } else { print(foo.genderCode); }`

**Comment by dnfield** [comment]
And for future reference -this tracker is for bugs with Flutter.  Questions like this would be better posed on a site like StackOverflow.
