### ISSUE TITLE
TabBarView  PageScrollPhysics animation is too long times

### ISSUE THREAD

**Issue by sky126** [flutter/flutter#48807]
sliding horizontally as long animation times affect other pointer gestures. such as TabBarView has a ListView inside, when sliding horizontally and then sliding up and down the ListView for a short time gap will not respond to vertical gestures. How to write code, help me.

**Comment by VladyslavBondarenko** [comment]
@sky126 
please follow up on https://github.com/flutter/flutter/issues/38357, https://github.com/flutter/flutter/issues/55103, https://github.com/flutter/flutter/issues/55625.
I'm closing the current one as duplicate
