### ISSUE TITLE
Sending http request before runApp throws non-useful error from MojoClient._initNetworkService

### ISSUE THREAD

**Issue by amarsten** [flutter/flutter#4881]
## Steps to Reproduce

Attempted to send an http request in main() before runApp() had been called. 
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/amarsten/Documents/workspace/deeplocal/visitor/flutter
    • Framework revision 9c0c0225a6 (2 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/amarsten/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
## Logs and Crash Reports

E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : The null object does not have a method 'connectToApplicationService'.
E/flutter : 
E/flutter : NoSuchMethodError: method not found: 'connectToApplicationService'
E/flutter : Receiver: null
E/flutter : Arguments: ["mojo:authenticated_network_service", Closure: (ServiceConnector, String, [String]) => NetworkServiceProxy from Function 'connectToService': static.]
E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/flutter : #2      MojoClient._initNetworkService (package:flutter/src/http/mojo_client.dart:218)
E/flutter : #3      MojoClient.networkService (package:flutter/src/http/mojo_client.dart:222)
E/flutter : #4      MojoClient.networkService (package:flutter/src/http/mojo_client.dart:222)
E/flutter : #5      MojoClient._send (package:flutter/src/http/mojo_client.dart:181)
E/flutter : #6      MojoClient.get (package:flutter/src/http/mojo_client.dart:32)
E/flutter : #7      get.<anonymous closure> (package:flutter/src/http/http.dart:31)
E/flutter : #8      _withClient (package:flutter/src/http/http.dart:165)
E/flutter : #9      get (package:flutter/src/http/http.dart:31)
E/flutter : #10     loadData (/Users/amarsten/Documents/workspace/deeplocal/visitor/visitorApp/lib/main.dart:12)
E/flutter : #11     main (/Users/amarsten/Documents/workspace/deeplocal/visitor/visitorApp/lib/main.dart:19)
E/flutter : #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
E/flutter : #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Please attach any relevent logs or crash reports.

**Comment by eseidelGoogle** [comment]
mojo_client.dart could check for shell == null and print a more helpful message:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/http/mojo_client.dart#L217

Or perhaps we should teach the shell getter/global to do so.

**Comment by collinjackson** [comment]
@qchong ran into this same issue trying to use the path service.

I think we should just teach the shell getter/global to call runApp if it hasn't been run already.

**Comment by Hixie** [comment]
She `shell` getter is at a layer that doesn't know what binding you want, so it can't create the binding for you.

**Comment by collinjackson** [comment]
It should probably throw an exception rather than returning null, then

**Comment by Hixie** [comment]
Yup, that's what this bug is about. :-)

It needs to do the whole FlutterDetails dance to get a pretty message with lots of instructions on what to do.

**Comment by Hixie** [comment]
moot
