### ISSUE TITLE
Apple: Storyboard for Launch Screen starting April 2020

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#48815]
Tracking bug for the requirements laid out in https://developer.apple.com/news/?id=01132020b:

> "Apps should look great on all models of iPhone and iPad, regardless of display size or aspect ratio... starting April 2020, apps submitted to the App Store must use an Xcode storyboard to provide the app’s launch screen and must have an interface that supports any display size."

By default, the Flutter `create` command creates an iOS runner with support for iPhone and iPad. In addition, it creates a `LaunchScreen.storyboard` that can be customized for a unique splash screen. 

One package that automates the native storyboard creation is [flutter_native_splash](https://pub.dev/packages/flutter_native_splash).

**Comment by tvolkert** [comment]
https://stackoverflow.com/questions/56578186/wwdc-2019-ios13-april-2020-requirement

I think we're covered here - we already use storyboards for our launch screen.

@jmagman

**Comment by jmagman** [comment]
It also works with split-screens.

I created https://github.com/flutter/flutter/issues/48838 since supporting multiple windows is "strongly encouraged" though it doesn't seem required for the April 2020 cutoff.

Closing.
