### ISSUE TITLE
Possible regression in microbenchmark_ios_MatrixUtils_persp_transformPoint_iteration

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48816]
First jump after a patch of green was at https://github.com/flutter/flutter/pull/48538. I'm skeptical of this, think it more likely to be https://github.com/flutter/flutter/pull/48598.

**Comment by jonahwilliams** [comment]
Note the history of the benchmark is fairly red:

https://screenshot.googleplex.com/YX1paaQJQct

Still, we should get to the bottom of this

**Comment by jonahwilliams** [comment]
@flar , since you wrote this benchmark would you take a look and see if this is expected? If so, please rebaseline or ACK in this issue so we can continue the roll

**Comment by flar** [comment]
It has had a number of changes over time that look as if they happen right after a Dart roll. It's a microbenchmark on a very small piece of Dart code so I'm guessing that recent work on Dart features like NNBD might be introducing subtle changes in the way the code compiles. I can take a look at the recent changes that have bumped it up to consistently red over the past week, but the tolerance on the benchmark seems to be pretty small compared to the noise. It may be worth increasing the execution count on the benchmark to absorb the noise better and to figure if the baselines are too tight as well.

**Comment by flar** [comment]
I'm going to remove the TODAY tag since I don't think these figures are enough to warrant a hold on rolling. In particular, most of these benchmarks are to verify that our original gains of around 5x on these operations don't regress. These recent variations are showing minor perturbations in Dart execution rather than a broken algorithm...

**Comment by jonahwilliams** [comment]
Good to know, thanks for taking a look

**Comment by liyuqian** [comment]
@flar : do you have any future plan on this issue? If not, maybe we could close this issue and rebaseline the benchmark as nothing seems to be broken.

**Comment by flar** [comment]
These benchmarks don't seem to exist any more. I don't remember archiving them, but they shouldn't have been archived.

**Comment by flar** [comment]
They've already been rebaselined. This can be closed.
