### ISSUE TITLE
Pull request Ignoring

### ISSUE THREAD

**Issue by otopba** [flutter/flutter#48814]
Hello!
Why flutter  team ignoring PR inside plugins project?
I understand that you are very busy and I am grateful to you for your work. But could you watch the PRs more often?
My team and I actively use flutter in the development of our product. But a long merge greatly complicates the development. It is necessary to merge master and resolve conflicts. A sufficiently large number of request pools have already accumulated. Please pay attention to them. One of them is already half a year. Thank you

https://github.com/flutter/plugins/pull/1721
https://github.com/flutter/plugins/pull/2406
https://github.com/flutter/plugins/pull/2429
https://github.com/flutter/plugins/pull/2449
https://github.com/flutter/plugins/pull/2421
https://github.com/flutter/plugins/pull/2077
https://github.com/flutter/plugins/pull/1809

**Comment by amirh** [comment]
First, thank you for all the contributions, really!

I'm sorry that review takes so long, we are trying to take code reviews seriously and as such each review takes time. We try to allocate our time (including reviewing code) according to the item's priority.

Will you be interested in working towards becoming co-owners of the video player and google maps plugins and help with reviews? If so I'd suggest we work towards that by having you each pick 3 pending PRs for one of the pending plugins and review them (even if the result of the review is: this PR should be closed it's helping), this will turn reviewing your PRs into a higher priority (as by reviewing them we get 3x PRs reviewed and earn a team member).

Let me know if you're interested and if so lets set up some plan for making you a [contributor](https://github.com/flutter/flutter/wiki/Contributor-access).

**Comment by otopba** [comment]
Hey @amirh . Thanks for the quick response.
This is a wonderful offer. Yes, I want to become a contributor.

Is it possible to make my teammate @sanekyy a contributor too?

**Comment by amirh** [comment]
Great!

@sanekyy I suggest you'd review: 
 - https://github.com/flutter/plugins/pull/2433
 - https://github.com/flutter/plugins/pull/2302
 - https://github.com/flutter/plugins/pull/2064

@otopba I suggest you'd review:
- https://github.com/flutter/plugins/pull/2121
- https://github.com/flutter/plugins/pull/1661
- https://github.com/flutter/plugins/pull/2406 (not sure whether you already reviewed it)

Note that I picked these PRs semi randomly, I haven't reviewed them, and can't even say whether they should be accepted or rejected right now.

Please let me know when you're done with a review (LGTM/should be closed), and I'll make sure I or another contributor goes over the review. If you're uncertain about something feel free to consult with the other contributors on Discord (hackers-ecoystem). Hopefully quickly enough we can make you contributors.

FYI @cyanglaz (maps) @mklim (who I believe is looking at some in-flight video player PRs) and @collinjackson (general PR triage)

**Comment by mklim** [comment]
Thank you and welcome! In case you're not aware already, [information about the team chat is on the wiki](https://github.com/flutter/flutter/wiki/Chat).

**Comment by otopba** [comment]
Nice. Thank you =)

**Comment by collinjackson** [comment]
Welcome! And thanks in advance for your help.

**Comment by sanekyy** [comment]
Hello @amirh.

We reviewed given PRs and wrote remarks, suggestions and hints and  now we are waiting for replyes and changes from PRs owners. 
Some PRs owners can respond slowly. So in order not to waste time, can you or other contributers start to review our PRs?
We will continue review given PRs as soon as owners repsond and also we can help with review of others PRs in plugins repository.

**Comment by sanekyy** [comment]
Hello @amirh, @mklim and @collinjackson.

I checked all 6 PRs again. Authors of four PRs out of six are inactive for more than a month. One out of six is my PR and is up to date. And last one is active.

What we should do with inactive PRs? And what next?

**Comment by stuartmorgan** [comment]
Since this discussion is quite old, and doesn't really make sense as an issue (in that it's not tracking a feature request or bug report), I'm going to close it.

The general issue of PRs not being reviewed is definitely on our radar. We're currently working on overhauling the triage of that queue so that PRs aren't going without responses for long periods of time, as well as exploring ways of balancing the overall workload to be able to improve review throughput. Anyone interested in getting more involved should join the [Discord server](https://github.com/flutter/flutter/wiki/Chat), as that's a better place for this kind of general discussion.
