### ISSUE TITLE
gen_l10n tool does not gracefully handle missing message translations in non-template arb files

### ISSUE THREAD

**Issue by garry-jeromson** [flutter/flutter#48822]
When using the gen_l10n.dart tool to generate message files from ARB files, messages with placeholders are prefixed with `r'` in generated code, meaning that their placeholder arguments are not expanded when calling the string getter from the UI.

For example, take the following ARB content:

```json
{
  "translate": "Translate from {source} to {target}",
  "@translate": {
    "placeholders": {
      "source": {
        "description": "source locale name",
        "example": "en_US"
      },
      "target": {
        "description": "target locale name",
        "example": "ja_JP"
      }
    }
  }
}
```

The generated dart code for the message is:

```dart
String translate(Object source, Object target) {
    return Intl.message(
      r'Translate from $source to $target',
      locale: _localeName,
      name: 'translate',
      args: <Object>[source, target]
    );
  }
```

That `r'`prefix means that the fetched string for the call

```dart
AppLocalizations.of(context).translate("English", "Japanese")
```

 is `"Translate from $source to $target"` rather than `"Translate from English to Japanese"` as it should be.

I'd attempt to fix it myself but it's not obvious how at first glance to someone unfamiliar with the code, and I don't want to step on ongoing changes from #47008.

**Comment by shihaohong** [comment]
I just tested it with the following app and it seems to work:
### main.dart
```dart
import 'package:flutter/material.dart';

import 'l10n/app_localizations.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Center(
        child: Text(
          AppLocalizations.of(context).translate('English', 'Japanese'),
          style: Theme.of(context).textTheme.display1,
        ),
      ),
    );
  }
}
```

### Arb files:
```
{
  "translate": "Translate from {source} to {target}",
  "@translate": {
    "placeholders": {
      "source": {
        "description": "source locale name",
        "example": "en_US"
      },
      "target": {
        "description": "target locale name",
        "example": "ja_JP"
      }
    }
  }
}
```
app_es.arb
```
{
  "translate": "traducir del {source} al {target}"
}
```

**Comment by shihaohong** [comment]
I've seen this happen before when a supported language does not have the translation. For instance, **when running this app with a device that prefers Spanish**, I get:
![image](https://user-images.githubusercontent.com/27032613/72385912-4910e780-36d5-11ea-9223-c12b6d96fb4a.png)
 
### in main.dart
```dart
// In your app
Center(
  child: Text(
    AppLocalizations.of(context).otherWord('text here') 
  ),
),
```

### app_en.arb
```
{
  "translate": "Translate from {source} to {target}",
  "@translate": {
    "placeholders": {
      "source": {
        "description": "source locale name",
        "example": "en_US"
      },
      "target": {
        "description": "target locale name",
        "example": "ja_JP"
      }
    }
  },
  "otherWord": "Some other word with a {placeholder}",
  "@otherWord": {
    "description": "Some other word description",
    "placeholders": {
      "placeholder": {
        "description": "some placeholder text"
      }
    }
  }
}{
  "translate": "Translate from {source} to {target}",
  "@translate": {
    "placeholders": {
      "source": {
        "description": "source locale name",
        "example": "en_US"
      },
      "target": {
        "description": "target locale name",
        "example": "ja_JP"
      }
    }
  },
  "otherWord": "Some other word with a {placeholder}",
  "@otherWord": {
    "description": "Some other word description",
    "placeholders": {
      "placeholder": {
        "description": "some placeholder text"
      }
    }
  }
}
```
### app_es.arb
``` 
{
  "translate": "traducir del {source} al {target}"
}
```

However, when I run this **when the device prefers English**:
![image](https://user-images.githubusercontent.com/27032613/72385885-3e565280-36d5-11ea-8e2a-e184a2fa9008.png)

**Comment by shihaohong** [comment]
I'm assigning @HansMuller to this issue since I'll be on vacation starting the end of this week until early February and I'm unsure if I'll be able to get to this before I leave.

**Comment by shihaohong** [comment]
@HansMuller and I did a little more digging and discovered that the first argument of `Intl.message`:
```dart
String translate(Object source, Object target) {
    return Intl.message(
      r'Translate from $source to $target', // this line
      locale: _localeName,
      name: 'translate',
      args: <Object>[source, target]
    );
  }
```
is simply the fallback message in the event that the message does not exist in the locale that you are using. Per the `intl` package's [docs](https://pub.dev/packages/intl): "A function with an Intl.message call can be run in the program before any translation has been done, and will just return the message string."

This means that on the gen_l10n side of things, we will need to fix the interpolation of this argument, since it will be the message string that is used as the fallback message string.
