### ISSUE TITLE
Error thrown before runApp() makes SIGINT throw an error in flutter_tool

### ISSUE THREAD

**Issue by amarsten** [flutter/flutter#4882]
## Steps to Reproduce

Call undefined method before runApp(). Once the app has crashed try to use Ctrl-c to quit flutter tool.
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/amarsten/Documents/workspace/deeplocal/visitor/flutter
    • Framework revision 9c0c0225a6 (2 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/amarsten/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
## Logs and Crash Reports

```
Exception from flutter run: JSON-RPC error -32601 (method not found): Method not found
package:json_rpc_2/src/client.dart 96                             Client.sendRequest
package:json_rpc_2/src/peer.dart 69                               Peer.sendRequest
package:flutter_tools/src/observatory.dart 219                    Observatory.flutterExit
package:flutter_tools/src/run.dart 381                            RunAndStayResident._stopApp
package:flutter_tools/src/run.dart 265                            RunAndStayResident._run.<async>.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/zone.dart 732                                          _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 334                                   _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 591                                   _DelayedData.perform
dart:async/stream_impl.dart 707                                   _StreamImplEvents.handleNext
dart:async/stream_impl.dart 667                                   _PendingEvents.schedule.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 946                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallback
dart:async/stream_impl.dart 143                                   _BufferingStreamSubscription.onData
dart:async/stream_impl.dart 116                                   _BufferingStreamSubscription._BufferingStreamSubscription
dart:async/stream_controller.dart 848                             _ControllerSubscription._ControllerSubscription
dart:async/broadcast_stream_controller.dart 31                    _BroadcastSubscription._BroadcastSubscription
dart:async/broadcast_stream_controller.dart 219                   _BroadcastStreamController._subscribe
dart:async/stream_controller.dart 827                             _ControllerStream._createSubscription
dart:async/stream_impl.dart 470                                   _StreamImpl.listen
package:flutter_tools/src/run.dart 262                            RunAndStayResident._run.<async>
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/future_impl.dart 131                                   _FutureListener.handleValue
dart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                   _Future._propagateToListeners
dart:async/future_impl.dart 467                                   _Future._complete
dart:async/future_impl.dart 52                                    _SyncCompleter.complete
package:flutter_tools/src/observatory.dart 35                     Observatory.connect.<async>
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/future_impl.dart 131                                   _FutureListener.handleValue
dart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                   _Future._propagateToListeners
dart:async/future_impl.dart 342                                   _Future._addListener.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper
package:flutter_tools/src/run.dart                                RunAndStayResident._run
package:flutter_tools/src/run.dart 67                             RunAndStayResident.run.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 1301                                         runZoned
package:flutter_tools/src/run.dart 66                             RunAndStayResident.run
package:flutter_tools/src/commands/run.dart 135                   RunCommand.runInProject.<async>
dart:async/future.dart 144                                        Future.Future.microtask.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 946                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 861                                          _CustomZone.registerCallback
dart:async/zone.dart 749                                          _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                            scheduleMicrotask
dart:async/future.dart 142                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       RunCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 172         FlutterCommand._run.<async>
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/future_impl.dart 131                                   _FutureListener.handleValue
dart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                   _Future._propagateToListeners
dart:async/future_impl.dart 467                                   _Future._complete
dart:async/future_impl.dart 52                                    _SyncCompleter.complete
package:flutter_tools/src/cache.dart 169                          Cache.updateAll.<async>
dart:async/future.dart 144                                        Future.Future.microtask.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 946                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 103         FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async/future.dart 168                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 182  FlutterCommandRunner.runCommand.<async>
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/future_impl.dart 131                                   _FutureListener.handleValue
dart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                   _Future._propagateToListeners
dart:async/future_impl.dart 467                                   _Future._complete
dart:async/future_impl.dart 52                                    _SyncCompleter.complete
package:flutter_tools/src/cache.dart 65                           Cache.lock.<async>
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 958                                          _rootRunUnary
dart:async/zone.dart 837                                          _CustomZone.runUnary
dart:async/future_impl.dart 131                                   _FutureListener.handleValue
dart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                   _Future._propagateToListeners
dart:async/future_impl.dart 477                                   _Future._completeWithValue
dart:async/future_impl.dart 528                                   _Future._asyncComplete.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async/future.dart 168                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 123  FlutterCommandRunner.run
package:flutter_tools/executable.dart 88                          main.<async>.<fn>.<async>
dart:async/future.dart 144                                        Future.Future.microtask.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 946                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 724                                          _CustomZone.runGuarded
dart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 861                                          _CustomZone.registerCallback
dart:async/zone.dart 749                                          _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                            scheduleMicrotask
dart:async/future.dart 142                                        Future.Future.microtask
package:flutter_tools/executable.dart                             main.<async>.<fn>
package:stack_trace/src/chain.dart 87                             Chain.capture.<fn>
dart:async/zone.dart 950                                          _rootRun
dart:async/zone.dart 826                                          _CustomZone.run
dart:async/zone.dart 1303                                         runZoned
package:stack_trace/src/chain.dart 85                             Chain.capture
package:flutter_tools/executable.dart 82                          main.<async>
dart:async/future.dart 144                                        Future.Future.microtask.<fn>
dart:async/schedule_microtask.dart 41                             _microtaskLoop
dart:async/schedule_microtask.dart 50                             _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage
```

ckage:flutter_tools/src/run.dart 67                             RunAndStayResident.run.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 1301                                         runZonedpackage:flutter_tools/src/run.dart 66                             RunAndStayResident.runpackage:flutter_tools/src/commands/run.dart 135                   RunCommand.runInProject.<async>dart:async/future.dart 144                                        Future.Future.microtask.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 946                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>dart:async/schedule_microtask.dart 41                             _microtaskLoopdart:async/schedule_microtask.dart 50                             _startMicrotaskLoopdart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallbackdart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage===== asynchronous gap ===========================dart:async/zone.dart 861                                          _CustomZone.registerCallbackdart:async/zone.dart 749                                          _CustomZone.bindCallbackdart:async/schedule_microtask.dart 148                            scheduleMicrotaskdart:async/future.dart 142                                        Future.Future.microtaskpackage:flutter_tools/src/commands/run.dart                       RunCommand.runInProjectpackage:flutter_tools/src/runner/flutter_command.dart 172         FlutterCommand._run.<async>dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>dart:async/zone.dart 958                                          _rootRunUnarydart:async/zone.dart 837                                          _CustomZone.runUnarydart:async/future_impl.dart 131                                   _FutureListener.handleValuedart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallbackdart:async/future_impl.dart 667                                   _Future._propagateToListenersdart:async/future_impl.dart 467                                   _Future._completedart:async/future_impl.dart 52                                    _SyncCompleter.completepackage:flutter_tools/src/cache.dart 169                          Cache.updateAll.<async>dart:async/future.dart 144                                        Future.Future.microtask.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 946                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>dart:async/schedule_microtask.dart 41                             _microtaskLoopdart:async/schedule_microtask.dart 50                             _startMicrotaskLoopdart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallbackdart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage===== asynchronous gap ===========================dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallbackdart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelperpackage:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._runpackage:flutter_tools/src/runner/flutter_command.dart 103         FlutterCommand.runpackage:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>dart:async/future.dart 168                                        Future.Future.syncpackage:args/command_runner.dart 129                              CommandRunner.runCommandpackage:flutter_tools/src/runner/flutter_command_runner.dart 182  FlutterCommandRunner.runCommand.<async>dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>dart:async/zone.dart 958                                          _rootRunUnarydart:async/zone.dart 837                                          _CustomZone.runUnarydart:async/future_impl.dart 131                                   _FutureListener.handleValuedart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallbackdart:async/future_impl.dart 667                                   _Future._propagateToListenersdart:async/future_impl.dart 467                                   _Future._completedart:async/future_impl.dart 52                                    _SyncCompleter.completepackage:flutter_tools/src/cache.dart 65                           Cache.lock.<async>dart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelper.<fn>package:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 135         StackZoneSpecification.registerUnaryCallback.<fn>dart:async/zone.dart 958                                          _rootRunUnarydart:async/zone.dart 837                                          _CustomZone.runUnarydart:async/future_impl.dart 131                                   _FutureListener.handleValuedart:async/future_impl.dart 637                                   _Future._propagateToListeners.handleValueCallbackdart:async/future_impl.dart 667                                   _Future._propagateToListenersdart:async/future_impl.dart 477                                   _Future._completeWithValuedart:async/future_impl.dart 528                                   _Future._asyncComplete.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>dart:async/schedule_microtask.dart 41                             _microtaskLoopdart:async/schedule_microtask.dart 50                             _startMicrotaskLoopdart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallbackdart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage===== asynchronous gap ===========================dart:async/zone.dart 873                                          _CustomZone.registerUnaryCallbackdart:async-patch/async_patch.dart 27                              _asyncThenWrapperHelperpackage:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommandpackage:args/command_runner.dart 103                              CommandRunner.run.<fn>dart:async/future.dart 168                                        Future.Future.syncpackage:args/command_runner.dart 103                              CommandRunner.runpackage:flutter_tools/src/runner/flutter_command_runner.dart 123  FlutterCommandRunner.runpackage:flutter_tools/executable.dart 88                          main.<async>.<fn>.<async>dart:async/future.dart 144                                        Future.Future.microtask.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 946                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>package:stack_trace/src/stack_zone_specification.dart 206         StackZoneSpecification._runpackage:stack_trace/src/stack_zone_specification.dart 125         StackZoneSpecification.registerCallback.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 724                                          _CustomZone.runGuardeddart:async/zone.dart 751                                          _CustomZone.bindCallback.<fn>dart:async/schedule_microtask.dart 41                             _microtaskLoopdart:async/schedule_microtask.dart 50                             _startMicrotaskLoopdart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallbackdart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage===== asynchronous gap ===========================dart:async/zone.dart 861                                          _CustomZone.registerCallbackdart:async/zone.dart 749                                          _CustomZone.bindCallbackdart:async/schedule_microtask.dart 148                            scheduleMicrotaskdart:async/future.dart 142                                        Future.Future.microtaskpackage:flutter_tools/executable.dart                             main.<async>.<fn>package:stack_trace/src/chain.dart 87                             Chain.capture.<fn>dart:async/zone.dart 950                                          _rootRundart:async/zone.dart 826                                          _CustomZone.rundart:async/zone.dart 1303                                         runZonedpackage:stack_trace/src/chain.dart 85                             Chain.capturepackage:flutter_tools/executable.dart 82                          main.<async>dart:async/future.dart 144                                        Future.Future.microtask.<fn>dart:async/schedule_microtask.dart 41                             _microtaskLoopdart:async/schedule_microtask.dart 50                             _startMicrotaskLoopdart:isolate-patch/isolate_patch.dart 96                          _runPendingImmediateCallbackdart:isolate-patch/isolate_patch.dart 149                         _RawReceivePortImpl._handleMessage

```
```

**Comment by eseidelGoogle** [comment]
This looks like a case which somehow skips the normal flutter_tools crash/log dumping @devoncarew

**Comment by Hixie** [comment]
I think this particular crash might be fixed. We should verify.

**Comment by Hixie** [comment]
We now say:
```
Error -32601 received from application: Method not found
Application finished.
```
...with no stack. It's not ideal, but there's other bugs covering making this prettier. The crash itself is gone.
