### ISSUE TITLE
"Unknown operating system. Cannot install Dart SDK" on Windows on Mac (via Bootcamp)

### ISSUE THREAD

**Issue by KANCybernet** [flutter/flutter#48848]
Was having some issues with an application i was building, thought it was version issue so i tried upgrading flutter. Somehow i began getting errors i couldn't trace.. had to even download a new flutter kit to no avail..

When i run flutter doctor from the terminal, i get errors like:
Error: unknown operating system (Meanwhile i use windows on mac)

Or

Error: unable to create dart snapshot for flutter tool (If i run flutter doctor on command prompt)

Or

Error: Unable to pub-upgrade

If i delete cache file and try to run flutter doctor from the terminal, i get error like this:

Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
Unknown operating system. Cannot install Dart SDK.

. Please help

**Comment by jonahwilliams** [comment]
By Windows on mac, you something like boot camp?

**Comment by KANCybernet** [comment]
Yes.. I use windows on Mac, installed from Mac using boot camp.. I have been running flutter successfully on my PC for months now, until i tried to upgrade recently.

**Comment by jonahwilliams** [comment]
When you originally downloaded flutter, did you use download the windows or macOS version? Does it work if you download new sources off of flutter.dev instead of using `flutter upgrade`?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by nande1** [comment]
> Was having some issues with an application i was building, thought it was version issue so i tried upgrading flutter. Somehow i began getting errors i couldn't trace.. had to even download a new flutter kit to no avail..
> 
> When i run flutter doctor from the terminal, i get errors like:
> Error: unknown operating system (Meanwhile i use windows on mac)
> 
> Or
> 
> Error: unable to create dart snapshot for flutter tool (If i run flutter doctor on command prompt)
> 
> Or
> 
> Error: Unable to pub-upgrade
> 
> If i delete cache file and try to run flutter doctor from the terminal, i get error like this:
> 
> Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
> Unknown operating system. Cannot install Dart SDK.
> 
> . Please help

same isuue !!!!

**Comment by nande1** [comment]
> Was having some issues with an application i was building, thought it was version issue so i tried upgrading flutter. Somehow i began getting errors i couldn't trace.. had to even download a new flutter kit to no avail..
> 
> When i run flutter doctor from the terminal, i get errors like:
> Error: unknown operating system (Meanwhile i use windows on mac)
> 
> Or
> 
> Error: unable to create dart snapshot for flutter tool (If i run flutter doctor on command prompt)
> 
> Or
> 
> Error: Unable to pub-upgrade
> 
> If i delete cache file and try to run flutter doctor from the terminal, i get error like this:
> 
> Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
> Unknown operating system. Cannot install Dart SDK.
> 
> . Please help

same isuue !!!!

**Comment by Quantika14** [comment]
I'm experiencing exactly the same issue, but using Windows directly. No boot camp use, no macOS, etc. 

I've been working with flutter in the same PC and OS for a long time. I just did `flutter upgrade` and get the error:
`Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
Unknown operating system. Cannot install Dart SDK.`

**Comment by christopherfujino** [comment]
> I'm experiencing exactly the same issue, but using Windows directly. No boot camp use, no macOS, etc.
> 
> I've been working with flutter in the same PC and OS for a long time. I just did `flutter upgrade` and get the error:
> `Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408... Unknown operating system. Cannot install Dart SDK.`

@Quantika14 I think that is slightly different than this issue. If you open a new issue with `flutter doctor -v` and the logs from `flutter upgrade -v` and @ me, I will gladly take a look!

**Comment by jazz7381** [comment]
> I'm experiencing exactly the same issue, but using Windows directly. N

run terminal as administrator solve my problem

**Comment by yuniorlaureano** [comment]
Ese error me sucedió, y la forma de solucionarlo fue descargando el zip de flutter directamente, y no clonandolo desde git.
