### ISSUE TITLE
Flutter Custom Video Player Doesn't respect Parent Container Width and Height 

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#48854]
I have added a VideoPlayer and added it as a child of a Container Widget. Now when video loads, that video player sizes itself based on the video file aspect ratio and doesn't stay within parent container.

__I tried with *SizedBox* and *FittedBox* widgets too but same issue__

Here is a [github test repo](https://github.com/premingiet/Flutter_Video_Test) i made to reproduce the issue

Press the __Load Asset Video__ button to see the issue.
I have used Android device to test it

**Comment by iapicca** [comment]
Hi @premingiet 
I see [here](https://github.com/premingiet/Flutter_Video_Test/blob/master/fvc/lib/Widget/WidgetVideo.dart) that you are using
the third party plugin [flutter_ijkplayer](https://pub.dev/packages/flutter_ijkplayer), you may want to open an issue in the dedicated [github](https://github.com/CaiJingLong/flutter_ijkplayer/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by n-santamaria** [comment]
Hello @iapicca,
I've faced the similar issue with video_controller plugin.

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_widgets/flutter_widgets.dart';
import 'package:video_player/video_player.dart';

class VideoPlayerScreen extends StatefulWidget {

  final String videoUrl;

  VideoPlayerScreen({@required this.videoUrl, Key key}) : super(key: key);

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {

  VideoPlayerController _controller;
  Future<void> _initializeVideoPlayerFuture;
  bool _volumeUp = true;
  var _scaffoldKey = new GlobalKey<ScaffoldState>();
  var a;

  @override
  void initState() {
    // Create and store the VideoPlayerController. The VideoPlayerController
    // offers several different constructors to play videos from assets, files,
    // or the internet.
    _controller = VideoPlayerController.network(
      widget.videoUrl
    );

    // Initialize the controller and store the Future for later use.
    _initializeVideoPlayerFuture = _controller.initialize();

    _controller.addListener(checkIfVideoFinished);

    super.initState();
  }

  void checkIfVideoFinished() {
    if(_controller.value.position == _controller.value.duration) {
      _controller.removeListener(checkIfVideoFinished);
      setState(() {
        _controller.pause();
      });
    }
  }

  @override
  void dispose() {
    // Ensure disposing of the VideoPlayerController to free up resources.
    _controller.removeListener(checkIfVideoFinished);
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return VisibilityDetector(
      key: _scaffoldKey,
      onVisibilityChanged: (VisibilityInfo info) {
        if(info.visibleFraction < 1.0) {
          if(_controller.value.isPlaying) {
            if(this.mounted) {
              setState(() {
              _controller.pause();
              });
            }
          }
        }
        // debugPrint( widget.videoUrl + "\n ${info.visibleFraction} of my widget is visible");
      },
      child: Stack(
        children: <Widget>[
          FutureBuilder(
            future: _initializeVideoPlayerFuture,
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.done) {
                // If the VideoPlayerController has finished initialization, use
                // the data it provides to limit the aspect ratio of the video.
                return Align(
                  alignment: Alignment.center,
                  child: AspectRatio(
                    aspectRatio: 4/3,
                    child: VideoPlayer(_controller),
                  ),
                );
              } else {
                // If the VideoPlayerController is still initializing, show a
                // loading spinner.
                return Center(child: CircularProgressIndicator());
              }
            },
          ),
          Align(
            alignment: Alignment.bottomRight,
            child: Container(
              color: Colors.black87.withOpacity(0.3),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  IconButton(
                    icon: Icon(_controller.value.isPlaying ? Icons.pause : Icons.play_arrow,),
                    color: Colors.white,
                    onPressed: () {
                      if (_controller.value.isPlaying) {
                        setState(() {
                          _controller.pause();
                        });
                        _controller.removeListener(checkIfVideoFinished);
                      } else {
                        setState(() {
                          _controller.play();
                        });
                        _controller.addListener(checkIfVideoFinished);
                      }
                    },
                  ),
                  IconButton(
                    icon: Icon(_volumeUp ? Icons.volume_up : Icons.volume_off,),
                    color: Colors.white,
                    onPressed: () {
                      setState(() {
                        if (_volumeUp) {
                          _controller.setVolume(0.0);
                          _volumeUp = false;
                        } else {
                          _controller.setVolume(1.0);
                          _volumeUp = true;
                        }
                      });
                    },
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}


![video_player](https://user-images.githubusercontent.com/61319375/75038485-76bf2c80-54dc-11ea-86e8-a29c986d2eae.jpeg)

**Comment by iapicca** [comment]
Hi @n-santamaria 
could you (or anyone with the same problem)
please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by n-santamaria** [comment]
Hello @iapicca 
I've created a new issue.

Best Regards,
Neville Santamaria
