### ISSUE TITLE
How to set the cursor color in SearchDelegate

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#48857]
There is currently no way to set the cursor color within the text field of the search delegate.

**Comment by neokree** [comment]
I also found this to be an issue, in our app we want to have a white cursor in the AppBar, but we can only set it to be the primaryColor of the app at this time. 

A way to set it like it was done for the label [here](https://github.com/flutter/flutter/pull/30388) would be really helpful

**Comment by LeonardoEmili** [comment]
The easiest way to do it would be to pass the color as an extra argument _cursorColor_. Simply create your own class from SearchDelegate and pass the color to the constructor like this:

`CustomSearchDelegate({Color cursorColor})
      : super(
          cursorColor: cursorColor
        );`

then, add _cursorColor_ as property of the class _SearchDelegate_ and finally use it when building the widget:

`
cursorColor: widget.delegate.cursorColor
`.

Hope this helps.

**Comment by LeonardoEmili** [comment]
> There is currently no way to set the cursor color within the text field of the search delegate.

I have created a [pull request](https://github.com/flutter/flutter/pull/54686) with the feature you were looking at.

**Comment by chitgoks** [comment]
I forgot about this issue and i have no idea which version it got fixed if you override the theme. but this is how i did it now

```
@override
  ThemeData appBarTheme(BuildContext context) {
    assert(context != null);
    final ThemeData theme = Theme.of(context);
    assert(theme != null);
    return theme.copyWith(
      inputDecorationTheme: InputDecorationTheme(hintStyle: TextStyle(color: theme.primaryTextTheme.headline.color)),
      textTheme: theme.textTheme.copyWith(
        headline: theme.textTheme.headline.copyWith(color: theme.primaryTextTheme.headline.color),
        title: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.bold,
          fontSize: 18,
        ),
      )
    );
  }
```

The TextStyle color is what fixed this. But true, this should not be the case, a way to set the text color should be the correct way.

**Comment by LeonardoEmili** [comment]
> I forgot about this issue and i have no idea which version it got fixed if you override the theme. but this is how i did it now
> 
> ```
> @override
>   ThemeData appBarTheme(BuildContext context) {
>     assert(context != null);
>     final ThemeData theme = Theme.of(context);
>     assert(theme != null);
>     return theme.copyWith(
>       inputDecorationTheme: InputDecorationTheme(hintStyle: TextStyle(color: theme.primaryTextTheme.headline.color)),
>       textTheme: theme.textTheme.copyWith(
>         headline: theme.textTheme.headline.copyWith(color: theme.primaryTextTheme.headline.color),
>         title: TextStyle(
>           color: Colors.white,
>           fontWeight: FontWeight.bold,
>           fontSize: 18,
>         ),
>       )
>     );
>   }
> ```
> 
> The TextStyle color is what fixed this. But true, this should not be the case, a way to set the text color should be the correct way.

That's a clean solution, I think it should be used until a proper way to customize the SearchDelegate is provided or the PR is accepted.

**Comment by iapicca** [comment]
related to https://github.com/flutter/flutter/issues/45498

**Comment by markusaksli-nc** [comment]
Closing as the related PR has been closed and author was able to resolve this.

**Comment by fede1295** [comment]
@chitgoks @LeonardoEmili this solution working for you? When i set title attribute the IDE tells this: 
" 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8.. "
And if i set the properties for headline6 this not fix the cursorColor..

**Comment by LeonardoEmili** [comment]
@fede1295 Yes, when I tried it was working fine but as for now, I am not aware of a proper solution for this problem has been introduced. I have been working on a PR that involves a solution to this issue but I am not sure when I will be able to add these changes. If that is not working now I suggest you search among the issues if someone did advance a proper way to do this, and if you find it, please tag this issue to let developers know that someone solved it.

**Comment by chitgoks** [comment]
if i remember, yes the property name was changed but it still worked when i was working on it.

**Comment by markusaksli-nc** [comment]
You can continue the discussion on the open issue https://github.com/flutter/flutter/issues/45498 regarding this problem. Even if you don't plan to work on this you can thumbs up the mentioned issue or add to the discussion there to bring more attention to it.

**Comment by fede1295** [comment]
Yes i've already written on the issue [#45498](https://github.com/flutter/flutter/issues/45498) await a solution...
