### ISSUE TITLE
Flutter Gallery doesn't launch on device

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4886]
It also has the wrong name `flutter_gallery`.  Presumably it hasn't been updated after the iOS project changes from @abarth.

FYI @tvolkert @chinmaygarde

**Comment by eseidelGoogle** [comment]
I'm trying:
```
flutter build ios --release
flutter install
```

And then clicking on the resulting `flutter_gallery` binary.  It just flashes black and then sends me back to the home screen.

**Comment by eseidelGoogle** [comment]
The `flutter run` logs are just

```
vm-service: Isolate creation error: (null)
[INFO:FlutterDynamicServiceLoader.mm(129)] Could not find the service definitions manifest. No custom services will be available.
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
[INFO:FlutterDynamicServiceLoader.mm(129)] Could not find the service definitions manifest. No custom services will be available.
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
```
repeated 4 times.  I assume the 4 times is due to https://github.com/flutter/flutter/issues/4874

**Comment by abarth** [comment]
I can reproduce this issue.

**Comment by sethladd** [comment]
I'm able to run the gallery, from master branch, onto my iPhone 6S. Maybe this was fixed?

**Comment by sethladd** [comment]
I'm going to close, since it's been working for a while. Please reopen if you experience this issue.
