### ISSUE TITLE
Setting Grond Overlay  | google_maps_flutter

### ISSUE THREAD

**Issue by sipao** [flutter/flutter#48869]
Is there way to setting ground overlay in google_maps_flutter plugin?

Example:
http://www.ryecemetery.com.au/locate.html

**Comment by iapicca** [comment]
Hi @sipao 
I see there's an open [issue](https://github.com/flutter/flutter/issues/26479) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
