### ISSUE TITLE
help！

### ISSUE THREAD

**Issue by xiaolangshou** [flutter/flutter#48860]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Vanethos** [comment]
Could you provide us more information about the issue?

What were the steps taken to reproduce the bug?

What is the platform?

Do you have a minimal working example to replicate the issue?

Are there any logs you can show us?

**Comment by dnfield** [comment]
It looks like you might have forgotten to fill out the issue template.  Please feel free to comment here if you have details to add, or just open a new bug with the relevant details.
