### ISSUE TITLE
RSA encryption and decryption signature problem

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#48862]
With Flutter, the funcation cannot be implementation , public key encryption and private decryption, private key encryption and public decryption, private key signature and public key verification. RSA format: PKCS1 PKCS5.

**Comment by Vanethos** [comment]
You may refer to the following library: [PointyCastle](https://pub.dev/packages/pointycastle)

Please use [StackOverflow](https://stackoverflow.com/) to ask how to use the library.

If you think this is a core functionality in Dart, please file a new issue for a feature request in the [Dart-lang](https://github.com/dart-lang/sdk) github page
