### ISSUE TITLE
add isValid method to FormState

### ISSUE THREAD

**Issue by tjonganthony** [flutter/flutter#48874]
## Use case
`FormState.validate` causes all field to be validated even though the field has never been touched. There are cases when I want to only check whether the current form is valid without triggering UI changes on all the field.

For example:
I have a `Form` with 15 `FormField` and a submit button. I want to enable/disable the submit button based on whether there's a field that is notValid.
so I added `onChanged: _updateSubmitButton()` and `_updateSubmitButton()` will use the value from `formKey.currentState.validate()` to determine whether to enable or disable the submit button.

This will cause changing field 1 to make all the 15 fields to be validated and maybe show error just in order for me to disable the submit button.

## Proposal

Add an `isValid()` method to `FormState` that will check whether all the field is valid.
This will also require `isValid()` to be added to `FormFieldState` in order not to rely on `FormFieldState.validate()` which will cause the error text to appear.

**Comment by goderbauer** [comment]
It seems questionable to disable the submit button without telling users what's wrong. How would they learn what field they need to fix to enable the submit button?

**Comment by HansMuller** [comment]
I agree with https://github.com/flutter/flutter/issues/48874#issuecomment-577319572. Although the proposed API doesn't seem unreasonable, it doesn't really fit with the way the Form classes were intended to work. I suppose in this case, Flutter is unusually "opinionated" about  how the classes are intended to be used: the user typically causes a FormState.validate() by pressing a submit button, and that point any invalid fields are highlighted.

**Comment by tjonganthony** [comment]
There are several issues with Form that is also discussed in #48155 where I also mention about the usual flow how we should use Form(`Form.validate()` is called when user press submit button instead).
With the ongoing discussion there, I feel more need to add the `isValid` method.
