### ISSUE TITLE
CircleAvatar Widget Bug on Showing Circle Image

### ISSUE THREAD

**Issue by nothisway** [flutter/flutter#48870]
I want to make circle image avatar widget with this code :  
```dart
     Center(
          child: CircleAvatar(
            radius: 100,
            backgroundImage: NetworkImage(
              'https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg? 
               auto=compress&cs=tinysrgb&dpr=1&w=500',
            ),
          ),
        )
```
but the result shown up  like this. This issue only occurs on **Android Devices**

<img width="447" alt="Screen Shot 2020-01-15 at 11 48 11" src="https://user-images.githubusercontent.com/32806640/72411754-3d3d2800-379e-11ea-9bc5-098dc1c362ff.png">
 

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!
```

`flutter run —verbose`
```
      [  +33 ms] executing: [/Applications/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Applications/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +37 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321eb
[  +15 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Applications/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +106 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] stable
[  +20 ms] executing: sw_vers -productName
[  +57 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +32 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 10.15
[        ] executing: sw_vers -buildVersion
[  +33 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19A583
[  +56 ms] executing: /usr/bin/xcode-select --print-path
[  +11 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[+1126 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.1
           Build version 11A1027
[  +83 ms] executing: /Applications/android-sdk-macosx/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Applications/android-sdk-macosx/platform-tools/adb devices -l
[   +1 ms] List of devices attached
           192.168.59.101:5555    device product:vbox86p model:Google device:vbox86p transport_id:2
[  +53 ms] executing: /Applications/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +119 ms] /usr/bin/xcrun simctl list --json devices
[ +212 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +7 ms] /Applications/android-sdk-macosx/platform-tools/adb -s 192.168.59.101:5555 shell getprop
[  +51 ms] ro.hardware = vbox86
[        ] ro.build.characteristics = nosdcard
[  +10 ms] Google        • 192.168.59.101:5555                  • android-x86 • Android 8.0.0 (API 26)
[   +2 ms] iPhone 8 Plus • 3595CC9D-818D-4375-8344-9AE23C1C9FEF • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
[  +29 ms] "flutter run" took 1,946ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

     Analyzing testcircle...                                                 
No issues found! (ran in 5.5s)
```
` flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-ID)
    • Flutter version 1.12.13+hotfix.5 at /Applications/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Applications/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Applications/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Google        • 192.168.59.101:5555                  • android-x86 • Android 8.0.0 (API 26)
    • iPhone 8 Plus • 3595CC9D-818D-4375-8344-9AE23C1C9FEF • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @nothisway 
does this [code](https://dartpad.dartlang.org/265dc081437050e14ba1f5e7269d2a42) represent the issue you are describing?
Are you experiencing this issue on physical device as well?
thank you

**Comment by nothisway** [comment]
> Hi @nothisway
> does this [code](https://dartpad.dartlang.org/265dc081437050e14ba1f5e7269d2a42) represent the issue you are describing?
> Are you experiencing this issue on physical device as well?
> thank you

thank you very much for your response, 

yes your code represent my issue.
when i ran  it on physical device. the image doesn't appear at all. just the blue circle color.
the code works perfect on ios simulator / ios devices

**Comment by goderbauer** [comment]
Is this specific to this image? Or do other images show the same problem?

**Comment by dnfield** [comment]
I'm not able to reproduce this.  I tried this code on a Pixel 2 emulator.

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MediaQuery(
    data: MediaQueryData.fromWindow(window),
    child: Center(
        child: CircleAvatar(
      radius: 100,
      backgroundImage: NetworkImage(
        'https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      ),
    ))));
```

And it looks fine.

**Comment by nothisway** [comment]
> Is this specific to this image? Or do other images show the same problem?

every Image i put into backgroundImage inside CircleAvatar

**Comment by nothisway** [comment]
> I'm not able to reproduce this. I tried this code on a Pixel 2 emulator.
> 
> ```dart
> import 'dart:ui';
> 
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MediaQuery(
>     data: MediaQueryData.fromWindow(window),
>     child: Center(
>         child: CircleAvatar(
>       radius: 100,
>       backgroundImage: NetworkImage(
>         'https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
>       ),
>     ))));
> ```
> 
> And it looks fine.

i'm sorry your code still reproduce the bug on me. do you have the same flutter version with me ?
in previous version everything just work fine

**Comment by nothisway** [comment]
i don't what happen, but this bug solved, i just try to hot restart my app again. and it fixed.

this is the run console log from my IDEA : 

Performing hot restart...                                               
Restarted application in 1,817ms.
E/flutter ( 2570): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: operation failed
E/flutter ( 2570): #0      ShaderWarmUp.execute (package:flutter/src/painting/shader_warm_up.dart:90:5)
E/flutter ( 2570): <asynchronous suspension>
E/flutter ( 2570): #1      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:25:20)
E/flutter ( 2570): #2      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
E/flutter ( 2570): #3      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
E/flutter ( 2570): #4      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
E/flutter ( 2570): #5      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
E/flutter ( 2570): #6      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #7      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 2570): #14     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
E/flutter ( 2570): #15     runApp (package:flutter/src/widgets/binding.dart:868:25)
E/flutter ( 2570): #16     main (package:bug/main.dart:5:16)
E/flutter ( 2570): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 2570): #18     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 2570): #19     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 2570): #20     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 2570): #21     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 2570): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 2570): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 2570): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 2570): 

thanks everybody

**Comment by nothisway** [comment]
i'm sorry I found new trigger to reproduce this issue @dnfield .

if i add  appbar inside Scaffold. this issue reproduced.

please try this code : 

Widget build(BuildContext context){
    return Scaffold(
      appBar: AppBar(title: Text(
        'Test Circle Avatar'
      ),),
      body: Center(
        child: CircleAvatar(
          radius: 50,
          backgroundImage: _imageProvider,
        ),
      ),
    );
  }

**Comment by nothisway** [comment]
something similar happend with RoundedRectangleBorder.

<img width="397" alt="Screen Shot 2020-01-16 at 11 57 13" src="https://user-images.githubusercontent.com/32806640/72494840-af257800-3857-11ea-82c5-bdfed592c47c.png">

`shape: RoundedRectangleBorder(
          side: new BorderSide(color: FormatColor.darkBlue(), width: 1),
          borderRadius: BorderRadius.all(Radius.circular(5))
        ),`

**Comment by dnfield** [comment]
I don't get this on stable either.

Does this bug happen if you completely delete the app from the device and reinstall?  I'm wondering if you somehow got a corrupt/bad shader in the cache and it's getting reused.

**Comment by nothisway** [comment]
Hurray. it's fixed!  
i just add 
`      extendBodyBehindAppBar: true,
`
inside Scaffold attribute. Thank you so much mate. 
sorry for the problem
