### ISSUE TITLE
`flutter run` shows old logs before the application actually starts

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4887]
```
Application running.
Type "h" or F1 for help and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
vm-service: Isolate creation error: (null)
```

We show old logs long before the "Application running." log above.  This is very confusing.

Maybe this will be fixed by just fixing #4874

**Comment by Hixie** [comment]
I don't understand how this is different from #4874. Please reopen if it is distinct.
