### ISSUE TITLE
[video_player_web] Passing an Event as a PlatformException

### ISSUE THREAD

**Issue by sma** [flutter/flutter#48884]
I'm trying to use `video_player_web` 0.1.1+1 as a drop in replacement for `video_player` 0.10.5+1 by adding both to my pubspec dependencies.

I get a crash, though, because [this listener](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/lib/video_player_web.dart#L148) passes something of type `Event` (see below) via the `error` variable to [this method](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/lib/video_player.dart#L272) which then tries to cast that object into a `PlatformException` and fails.

I think, the first callback should look like this instead and pass the [MediaError](https://developer.mozilla.org/en-US/docs/Web/API/MediaError)'s error code and error message instead:

```dart
videoElement.onError.listen((dynamic _) {
  eventController.addError(PlatformException(
    code: '${videoElement.error.code}',
    message: videoElement.error.message,
});
```

I'm getting `MEDIA_ERR_SRC_NOT_SUPPORTED`, so it seems, but this isn't relevant for this bug report.

```console
$ flutter doctor -v
[✓] Flutter (Channel master, v1.13.10-pre.65, on Mac OS X 10.14.6 18G103, locale de-DE)
    • Flutter version 1.13.10-pre.65 at /Users/sma/Work/flutter
    • Framework revision 5d37de2685 (vor 7 Stunden), 2020-01-15 01:23:02 -0500
    • Engine revision bc41ab5139
    • Dart version 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available)
•
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.14.6
      18G103
    • Chrome            • chrome                               • web-javascript • Google Chrome
      81.0.4021.2 dev
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

**Comment by iapicca** [comment]
Hi @sma 
can you please provide your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by sma** [comment]
I'd hoped for the type error being obvious, but here you go…

```
dependencies:
  flutter:
    sdk: flutter
  video_player: 0.10.5+1
  video_player_web: 0.1.1+1
```

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BugPage(),
    );
  }
}

class BugPage extends StatefulWidget {
  @override
  _BugPageState createState() => _BugPageState();
}

class _BugPageState extends State<BugPage> {
  // a random video stream that isn't support by Chrome
  // so it causes a `MediaError` on the `VideoElement`
  final _controller = VideoPlayerController.network(
      'http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8');

  @override
  void initState() {
    super.initState();
    _controller.addListener(() => print(_controller.value));
    _controller.initialize().then((_) => _controller.play());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          // this stops because the Flutter web runtime crashes
          CircularProgressIndicator(),
          // this causes the crash
          Container(
            width: 320,
            height: 240,
            color: Colors.blue,
            child: VideoPlayer(_controller),
          ),
        ],
      ),
    );
  }
}
```

This should work on iOS but cause a `MEDIA_ERR_SRC_NOT_SUPPORTED` error on the web. You may have to open the Chrome Dev Tools to see the exception raised by the runtime:

```
errors.dart:147 Uncaught (in promise) Error: Expected a value of type 'PlatformException', but got one of type 'Event$'
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.castError (errors.dart:45)
    at Object.cast [as as] (operations.dart:426)
    at Function.check_C [as _check] (classes.dart:522)
    at errorListener (video_player.dart:272)
    at _RootZone.runUnaryGuarded (zone.dart:1316)
    at sendError (stream_impl.dart:361)
    at _ControllerSubscription.new.[_sendError] (stream_impl.dart:376)
    at async._DelayedError.new.perform (stream_impl.dart:605)
    at _StreamImplEvents.new.handleNext (stream_impl.dart:710)
    at async._AsyncCallbackEntry.new.callback (stream_impl.dart:670)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168
```

And last but not least...

```
$ flutter run --verbose -d chrome
[  +26 ms] executing: [/Users/sma/Work/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5d37de2685b8fcc151f61e121289c3dcbaee4623
[        ] executing: [/Users/sma/Work/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.9-65-g5d37de268
[   +6 ms] executing: [/Users/sma/Work/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/sma/Work/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] executing: [/Users/sma/Work/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +7 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G103
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] executing: /Users/sma/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/sma/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +26 ms] executing: /Users/sma/Work/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +55 ms] executing: /usr/bin/xcode-select --print-path
[  +21 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Users/sma/Downloads/Xcode_11.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +116 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.1
           Build version 11A1027
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +304 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] Found plugin video_player at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5+1/
[   +6 ms] Found plugin video_player_web at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.1+1/
[  +51 ms] Found plugin video_player at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5+1/
[   +2 ms] Found plugin video_player_web at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.1+1/
[  +44 ms] Generating
/private/tmp/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +147 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[ +177 ms] Found plugin video_player at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5+1/
[   +3 ms] Found plugin video_player_web at
/Users/sma/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.1+1/
[+7681 ms] Starting daemon...
[ +166 ms] Initializing inputs
[  +13 ms] Reading cached asset graph...
[ +182 ms] Reading cached asset graph completed, took 179ms

[ +196 ms] Checking for updates since last build...
[ +554 ms] Checking for updates since last build completed, took 554ms

[  +10 ms] Initializing inputs
[   +2 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 179ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 554ms
[ +813 ms] About to build [web]...
[   +4 ms] Running build...
[ +192 ms] Running build completed, took 86ms

[   +1 ms] Caching finalized dependency graph...
[   +9 ms] Caching finalized dependency graph completed, took 135ms

[   +6 ms] Succeeded after 230ms with 0 outputs (0 actions)

[  +11 ms] Building application for the web... (completed in 10,0s)
[        ] Attempting to connect to browser instance..
[+3542 ms] Debug service listening on ws://127.0.0.1:52704/QwyN0X-AO9c=

[ +307 ms]       Failed to load asset at path:
packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                          Status code: 404

                          Headers:
                          {
                      "date": "Thu, 16 Jan 2020 10:03:49 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                          Content:
                          Not Found}

[  +29 ms] Attempting to connect to browser instance.. (completed in 3,9s)
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
```

**Comment by iapicca** [comment]
Thank you @sma

**Comment by ditman** [comment]
I'll take a look at this one. Thanks for reporting!

**Comment by 1N50MN14** [comment]
Encountering exactly the same issue as I was trying to figure out why the `initialize` future is not catching any errors, figured it's related.

Exactly the same error output as @sma - to reproduce simply point to a non existing network data source it's easily breakable.

**Comment by ditman** [comment]
Thanks for the repro instructions @1N50MN14 !

**Comment by ditman** [comment]
(Will work on this tomorrow)

**Comment by 1N50MN14** [comment]
@ditman Thank you very much for working on this, looked at the commit I just have two questions if I may:
1. I understand for web `initialize` doesn't need to be a Future but that would be make it inconsistent with its native counterpart (and the rest of the API), an exception might occur there as well..

2. Thank you very much for this:
```dart
eventController.addError(PlatformException(
    code: _kErrorValueToErrorName[error.code],
    message: error.message != '' ? error.message : _kDefaultErrorMessage,
    details: _kErrorValueToErrorDescription[error.code],
));
```
Apologies if I'm missing on something here but how do I catch that in userland? at the moment stream listener seem to relay `VideoPlayeValue` only and completely ignores `VideoEvent`.

Thank you

**Comment by ditman** [comment]
@1N50MN14 if I've understood the code correctly, I see two cases:

* If the video hasn't been initialized, the Future returned from the initialize() method will get rejected ([here](https://github.com/flutter/plugins/blob/ddf17eead1decee33fc5ab09fc73ef89bf2d98a8/packages/video_player/video_player/lib/video_player.dart#L275)), or 
* During playback, the videoplayer will eventually enter an "erroneous" state ([here](https://github.com/flutter/plugins/blob/ddf17eead1decee33fc5ab09fc73ef89bf2d98a8/packages/video_player/video_player/lib/video_player.dart#L272)).

From userland: 
* You can detect the first case if the call to initialize throws (if you await), or the Future it returns gets rejected. You'd check for it around [here, I think](https://github.com/flutter/plugins/blob/ddf17eead1decee33fc5ab09fc73ef89bf2d98a8/packages/video_player/video_player/example/lib/main.dart#L491), 
* The "playback" errors, you can addListener to the VideoPlayerController that's driving your player, and check if the video hasError, like [here](https://github.com/flutter/plugins/blob/ddf17eead1decee33fc5ab09fc73ef89bf2d98a8/packages/video_player/video_player/example/lib/main.dart#L202-L206).

Regarding the initialize() failing... Can you suggest some code that breaks the initialization of the video player? If there's a repro case, we can test+fix it.

**Comment by ditman** [comment]
(@1N50MN14 also feel free to leave your comments in the PR itself, do you have enough permissions to do that? I tried to set you and @sma as reviewers, but I couldn't 🤨)

**Comment by 1N50MN14** [comment]
Thanks for the feedback @ditman 

At the moment, given the following:
```dart
final controller = VideoPlayerController.network('https://doesnot.exist/dummy.m4v');

controller.addListener(()=>print(controller.value));

try { await controller.initialize(); } catch(e) { print(e); }
```
At the moment what happens is:
1. The `initialize` future won't catch the exception, `controller.value` has an `errorDescription` value of `null` and the property `hasError` does not exist.

2. Otherwise, when there's an error, only `hasError` and `errorDescription` without the media error code itself, which makes it hard to know how deal with the error. For example, given error code `MEDIA_ERR_NETWORK`, we could check for connectivity and retry again. 

3. Currently, controller.value does not return `initialized` for some reason, and a corresponding `VideoEventType.completed` is also missing as well.

4. What I was trying to imply in my previous comment earlier, is that `controller.listen` should instead listen to video events (`VideoEvent`) where `error` is an enum value that belong to `VideoEventType` instead of a combining everything into "VideoPlayerValue".  

Even better, expose `onCanPlay` and `onError`, 'onDuration' and 'onEnd'... 

For now, adding an error code to controller.value would do... I'm checking for duration & size to as a workaround determine whether the video has been initialized or not, and comparing position to duration to detect when video playback has been completed.

I hope this helps.. thanks again

**Comment by 1N50MN14** [comment]
@ditman Sorry one more thing `autoplay` is always set to `false` here:
https://github.com/flutter/plugins/blob/bd0b5cfeb07d82d98b0bb4f9af62ed7d2e786aa1/packages/video_player/video_player_web/lib/video_player_web.dart#L156

But this is not necessarily accurate, browsers do allow auto play if the `muted` property is true...

**Comment by ditman** [comment]
@1N50MN14 about autoplay, do you need `autoplay` when you can just call .play after initializing?

At least it seems that's what's [done in tests](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/test/video_player_web_test.dart#L79-L83).

About the other changes in the interface, let me push this fix first and then we can take a look (maybe in a separate ticket?). We also need to ensure that the events and lifecycle work similarly across all platforms.

**Comment by 1N50MN14** [comment]
@ditman This is what I currently do (play right after initialization) yet somehow Chrome still deems it as "autoplay" unless `muted` is turned on, setting volume to zero did the trick for me, but I'm not sure if this works across all browsers.

Yup creating a separate ticket sounds like a good idea, thank you very much again for looking into all of this.

**Comment by ditman** [comment]
Published:

* [video_player 0.10.5+3](https://pub.dev/packages/video_player/versions/0.10.5+3)
* [video_player_web 0.1.2](https://pub.dev/packages/video_player_web/versions/0.1.2)

**Comment by ditman** [comment]
@1N50MN14 I did a quick test, and the trick seems to work as well on Firefox Linux (68.4.1esr)

**Comment by 1N50MN14** [comment]
@ditman Your PR works like a charm! I'm both able to catch `initialize` errors as well as obtain the PlatformException error code! Perfect! Thank you!!

**Comment by ditman** [comment]
Thanks for confirming this improves things, @1N50MN14!!

**Comment by 1N50MN14** [comment]
@ditman Seems that playback doesn't work on iOS Safari... for now I'm unable to determine whether the error is related to this issue or if it's something else I'm on Linux myself, reporting here in FYI.

I'm going to break my wallet for a white box with a fruit logo on it (as this issue is in production) then I'll submit a detailed log, alternatively open new issue if it's not related to this one. 

In the meantime if you happen to have an iPhone, and few spare minutes, then you'll be able to check it out, a simple page with a network video controller should do the trick...

Many thanks once again

**Comment by ditman** [comment]
@1N50MN14 does it fail with all videos? maybe it's an unsupported codec issue?

**Comment by ditman** [comment]
(PS, I do have an iPhone, I'll try to repro this tomorrow)

**Comment by 1N50MN14** [comment]
@ditman I'm strictly relying on H264 encoded (m4v) files... there are three videos on the page that play depending on the user's scroll position, one of which only contains audio.. 

Here's a temporary url (expires in 10 minutes) where you can check it: https://www.temporary-url.com/3F687E

**Comment by ditman** [comment]
@1N50MN14 I took a quick look, and I can repro the issue both in my device and an emulator. 

I inspected the webapp and there's no errors in the console, but the video appears to be downloading from the network (at least a few megs of each video are).

So maybe we're swallowing too many errors, I'll try to setup a minimal repro case and see what's up. 

I understand it may not be optimal to serve those assets from your frontend server and not a CDN, but just to narrow things down only to "network" videos: have you tried this with videos as Assets of your flutter app?

**Comment by 1N50MN14** [comment]
@ditman Oh I apologies this one is my bad I had console debug logging auto turned off... I just force enabled it and updated the page, now console logs all events (`initialize`, `play`, `pause`, `dispose`, `buffering`) as well as errors, for all videos, each with human readable name if you don't mind trying again...

Very curious to see what errors it'll catch, if any... if that doesn't work then I'll place them on the same server and let flutter load the assets..

Thank you

**Comment by ditman** [comment]
Nope, can't see anything meaningful. This is all I see after scrolling the page up and down a little bit (just the disposal of the off-screen videos)

![Screen Shot 2020-01-30 at 1 45 45 PM](https://user-images.githubusercontent.com/1255594/73493084-e2dbc400-4366-11ea-82da-e3f4d977b3e2.png)

**Comment by 1N50MN14** [comment]
So weird, it's completely ignoring `initialize`... going to log all commands as well as controller values, one sec please

**Comment by 1N50MN14** [comment]
@ditman Ok now I'm logging controller values as well as controller commands (they're state checked and throttled, if you see multiple `pause` logs for example).. crossing my fingers this will show something more meaningful..

If not then I'll deploy a single page with a single video, and a variation of that from assets..

**Comment by ditman** [comment]
Nope, still nothing interesting being logged. I think this needs a reduced repro case, and a ticket of its own. BTW: clicking on the "unmute" button doesn't do anything (it doesn't change the icon to "mute" either)

![Screen Shot 2020-01-30 at 2 09 18 PM](https://user-images.githubusercontent.com/1255594/73494867-3b609080-436a-11ea-8418-3b382685b0f6.png)

**Comment by 1N50MN14** [comment]
@ditman Yeah it's basically ignoring all commands.. I just noticed there's one open issues about iOS Safari, the user didn't seem to provide any logs either... Ok then I'll will reproduce this separately, attach a gist or even a whole repo and open a separate ticket.. so strange because it works flawlessly otherwise. Thank so much for spending your time on it...

**Comment by ditman** [comment]
Thanks for all your help!

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by ditman** [comment]
Thanks @iapicca! I'm locking this conversation so people *must* go and create a new issue :P (anyway, this hasn't had any activity in the last week, so it's probably solved solved)
