### ISSUE TITLE
How to Fix (flutter run, lauching error on Real Device) (flutter 1.12.13+hotfix.6)

### ISSUE THREAD

**Issue by M001T** [flutter/flutter#48883]
If you tried to run your app on its actual device, you noticed a launch error.

This is because version 1.12.13+hotfix.6 has some bugs

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.18363.535], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

Return immediately to 1.12.13+hotfix.5

with this command on your console: `flutter version 1.12.13+hotfix.5`

Hope this helps <3

**Comment by iapicca** [comment]
Hi @M001T 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by M001T** [comment]
> Hi @M001T
> can you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> and if possible a reproducible minimal code sample.
> Thank you

Like this ?

**Comment by iapicca** [comment]
Hi again @M001T 
I don't see any info provide in your last reply

**Comment by M001T** [comment]
> Hi again @M001T
> I don't see any info provide in your last reply

Did it look good in a good format now?

**Comment by iapicca** [comment]
@M001T 
in your initial post you seem to describe an undisclosed error 
that occurs running your flutter app in `flutter channel beta`
without being reproducible this issue is not workable;

please provide a reproducible minimal code sample
and your `flutter run --verbose` showing the aforementioned error
thank you
