### ISSUE TITLE
[proposal] expose InputDecorator default icon color

### ISSUE THREAD

**Issue by anotherglitchinthematrix** [flutter/flutter#48882]
For now, it's not possible to set the default color of the icon on the InputDecoration when the TextFormField doesn't have the focus. It just returns a predefined constant according to the brightness of the Theme. 

Some changes might be added due to make it possible to define the color scheme based on the input's state.

https://github.com/flutter/flutter/blob/5d37de2685b8fcc151f61e121289c3dcbaee4623/packages/flutter/lib/src/material/input_decorator.dart#L2003-L2015

**Comment by md-weber** [comment]
I would like to take this PR and fix the issue.

**Comment by md-weber** [comment]
I thought about it to make also the iconColor for Disabled and for Hover dynamic via the constructor, what do you think?

```
if (!decoration.enabled && !isFocused)
  return decoration.iconDisabledColor ?? themeData.disabledColor;

if(isHovering && decoration.iconHoverColor != null)
  return decoration.iconHoverColor;
```

At the current PR, I focused on the default Color but could update it with the other colours, too.

**Comment by anotherglitchinthematrix** [comment]
It seems like a good solution for me, I was thinking about having something like a InputDecoratorSet pseudo class to let us define multiple InputDecorators according to state of the input. This class will help to override the defined default style
of the input with the current state's InputDecoration and any value isn't set will be fallthorugh the default definition, but having n instances of InputDecoration for each state is not the best looking thing.

```dart
/// Instead of having an InputDecoration.
TextFormField(
  decoration: InputDecoration(),
);
```

```dart
/// Define an InputDecorationSet.
TextFormField(
  decoration: InputDecorationSet(
    default: InputDecoration(),
    hover: InputDecoration(),
    focus: InputDecoration(),
    active: InputDecoration(),
    disabled:InputDecoration(),
  ),
);
```

**Comment by md-weber** [comment]
I think your solution could be a good option but would lead to a lot of changes inside of the InputDecoration. Because there are already a lot of fields that contain information about the different status. I felt more about a lightweight solution where we add a new class for the IconColors. 

```
TextFormField(
decoration: InputDecoration(
  iconColors: IconColors(
    default: Colors.green,
    hover: Colors.red,
    focus: Colors.blue,
    disabled: Colors.grey,
    active: Colors.purple,
  )
)
```

The different colours could be null and would fallback to default colour, or if iconColors is not set there could be a defaultIconColour in the InputDecoration, like for example in Container if the BoxDecoration is established it is not allowed to have the colour property.

```
TextFormField(
  decoration: InputDecoration(
   defaultIconColor: Colors.blue,
  )
)
```
@darrenaustin is at the moment also assigned to my PR, so it would be great to hear his feedback, too.

**Comment by awhitford** [comment]
What about controlling the input color, when it does not have focus, for the _whole_ `InputDecoration`?  (This includes the icon, label, and underline.) Being able to control the icon color distinctively is a bonus, but one could always specify a `color` property for the `Icon`.  We need to be able to specify the input decoration color when it does not have focus.

And what about the [InputDecorationTheme](https://api.flutter.dev/flutter/material/InputDecorationTheme-class.html)?  I am interested in specifying a global default color scheme, so presumably that would be done by updating [ThemeData.inputDecorationTheme](https://api.flutter.dev/flutter/material/ThemeData/inputDecorationTheme.html).

Finally, my big complaint with Flutter theming is lack of documentation.  It would be great to see some documentation added that explains which color settings are controlling which components.  For example, to control the _focus color_, it is the Theme's `primaryColor`.

**Comment by bleroux** [comment]
Closing because this was fixed in https://github.com/flutter/flutter/pull/91762 which added several properties to configuration the InputDecoration icon colors.
