### ISSUE TITLE
[web] locale / onLocaleChanged not implemented

### ISSUE THREAD

**Issue by slightfoot** [flutter/flutter#48886]
Locale support has not yet been implemented for Flutter Web.. as can be seen here in this comment:
> `// TODO(flutter_web): Get the real locale from the browser.` 
> https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/window.dart#L705

Creating this ticket to identify the issue and to comment on the work being done.

A bit of R&D has been done and has identified the non-web method is as follows. [Window::UpdateLocales](https://github.com/flutter/engine/blob/e96c740410b18ae8e06ebcaab051e3c649b175c3/lib/ui/window/window.cc#L218) invokes a VM entry-point [_updateLocales](https://github.com/flutter/engine/blob/132d38cd222a9e9009d969defbdde658ad3079af/lib/ui/hooks.dart#L79) with the list of locales supported into groups of 4.. for example: `ko-Kore-KR, ko-Kore, ko-KR, ko`. The locale-sets are supplied in a priority order. The first being the current selected one. The `_updateLocales` dart function converts this list into dart:ui Locale objects sets them privately to be accessed in a read-only manner by the application and then invokes `window.onLocaleChanged` to notify the application of the change of locale.

Current implementation linked in PR uses the [langaugechange](https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event) event and the [window.navigator.languages](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) to achieve the same effect.

```
# flutter --version
Flutter 1.13.9 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d291de086c (6 days ago) • 2020-01-09 10:25:58 -0800
Engine • revision f001ea29f1
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)
```

**Comment by slightfoot** [comment]
@jonahwilliams I am bringing you in on this as you are the original author of the comment above. I have thown together a quick patch in the attached PR. It has not been tested at-all! and has no tests cases.

I would like to get your initial review, and some instructions on how to run it locally without recompiling the engine. I assume the dart code is accessed directly through build.. but I am not sure.

You'll also notice I have created a EventStreamProvider for `languagechange` which is a factory for event streams from JS. This is because the Window class in dart:html does not have a factory for `onLanguageChange`. I wonder if this should be added there instead.. but I wonder if you can follow this up with someone from the dart team, or bring them in on this PR.

**Comment by jonahwilliams** [comment]
> I would like to get your initial review, and some instructions on how to run it locally without recompiling the engine. I assume the dart code is accessed directly through build.. but I am not sure.

in FLUTTER_ROOT/bin/cache/flutter_web_sdk/lib are the source files for the `_engine` and `ui` libraries. If you modify them here are then build a profile/release (not a debug!) build, then you should be able to see whatever changes you've made

As far as tests go, I think @mdebbar or @yjbanov will have a better idea at this point. I'm not sure if it is possible to change the locale in JavaScript, but you might just check that the subscription gets created properly
