### ISSUE TITLE
Is it possible to get video frame by frame using video_player?

### ISSUE THREAD

**Issue by Paranormaly** [flutter/flutter#48889]
Is there any way to get video frame by frame using video_player?
The purpose of this feature is for ( Object detection using TF ) for video
This feature is working perfectly on Camera using (CameraController.startImageStream) but how can achieve that in video player?

Thanks

**Comment by dnfield** [comment]
This is a question better for StackOverflow or the like.

However, I'm pretty sure the video player plugin does not support this API, and it's unlikely that the plugin would accept such a feature request (/cc @amirh or @collinjackson).  You could probably write your own plugin for it though using existing libraries for your current platform(s).

**Comment by tomasdev** [comment]
Writing our own plugin means splitting the logic for Android and iOS, which sort of defeats Flutter (even though there are plenty of wins by just keeping at least the front-end in a single place)

But I do believe at the time being it's simply easier to build your own channels for communicating with AVFoundation and ffmpeg.
