### ISSUE TITLE
Include pods in main target (Runner) and not in WatchKit extension iOS.

### ISSUE THREAD

**Issue by anil-sookshum** [flutter/flutter#48880]
Platform: iOS 

I added a WatchKit extension to my existing flutter app by adding a new target but it contains all the pod frameworks that were included for the main Target and the build fails with the following error : 

![Screenshot 2020-01-15 at 3 50 14 PM](https://user-images.githubusercontent.com/44391555/72429688-8f8a4300-37b6-11ea-97b4-e1266806a853.png)

The WatchKit extension project doesn't need any frameworks that are defined for the main target, but I can't get the app to work after altering my Podfile. Is there is any way in Flutter to exclude the existing target pods to the other target?

The Watchkit extension is working fine with an empty or new project if there is no pod defined.

**Comment by iapicca** [comment]
Hi @anil-sookshum 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by VladyslavBondarenko** [comment]
@anil-sookshum 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Comment by nasserghiasi** [comment]
I have the same problem, What happened in pods. The apple watch doesn't have some dependencies and doesn't need  flutter frameworks
