### ISSUE TITLE
Add a Web test agent for flutter/engine with devicePixelRatio > 1

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#48898]
All our Web engine tests currently run with devicePixelRatio == 1.0. However, we have code that uses `window.devicePixelRatio`. We should have a test agent that runs all engine tests with devicePixelRatio > 1.0 (3.5. is typical for modern phones).

**Comment by digiter** [comment]
Triage: could you elaborate on this? Is it about adding a newer phone?

**Comment by yjbanov** [comment]
No, it could simply be a desktop Chrome configured to test with a higher DPR. Could be a LUCI shard. I just don't know how to use LUCI.
