### ISSUE TITLE
Misleading text in IconButton class description

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#4889]
In the class description for [IconButton](http://docs.flutter.io/flutter/material/IconButton-class.html), it says:

"If the onPressed callback is not specified or null, then the button will be disabled, will not react to touch."

However, the constructor description further below that text indicates that `onPressed` is actually a required parameter, which is confusing.

Suggest removing the words "...is not specified..." from the class description.

**Comment by abarth** [comment]
`@required` is just advisory.  It's entirely possible to call the function without that parameter.  I guess we can skip documenting what it does in that case.

**Comment by sethladd** [comment]
Ah, so the "fail on hints" is just a configuration for Flutter itself. (not a configuration/option that we're mandating for users...)

FWIW, something labeled `@required` doesn't sound like it's advisory. Required sounds, well, required. :)

**Comment by Hixie** [comment]
Yeah in this case we should omit the text that says what happens if it's not specified. It's actually still well-defined since the docs are unambiguous that if the required argument is omitted, it defaults to null.

**Comment by Hixie** [comment]
This was resolved recently.
