### ISSUE TITLE
Flutter Date Picker the getter 'year' was called on null

### ISSUE THREAD

**Issue by niravandroid** [flutter/flutter#48890]
![WhatsApp Image 2020-01-11 at 5 26 36 PM](https://user-images.githubusercontent.com/13154828/72449105-228aa380-37de-11ea-9491-214a55e3e5ab.jpeg)

I am just displaying date picker. It working fine in most of the devices. i.e Poco F1, Nexus 5.
But in some devices I am getting above error.

**Comment by Zazo032** [comment]
Could you provide the output of `flutter doctor -v`? Also, if possible, a gist of the code needed to replicate the issue. In which devices are you seeing this error?

**Comment by niravandroid** [comment]
@Zazo032 

[√] Flutter (Channel beta, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at Z:\Work\Flutter_Workspace\Flutter_SDK\flutter
    • Framework revision 2d2a1ffec9 (4 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at Z:\Work\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: Z:\Work\android-studio-ide-171.4408382-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at Z:\Work\android-studio-ide-171.4408382-windows\android-studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Code  I have used:**
 ```
Future<Null> selectFromDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
        context: context,
        initialDate:
            _selectedFromDate == null ? DateTime.now() : _selectedFromDate,
        firstDate: DateTime.now().subtract(Duration(days: 365)),
        lastDate: new DateTime.now());
    if (picked != null && picked != _selectedFromDate)
      setState(() {
        _selectedFromDate = picked;
        _selectedToDate = DateTime.now();
      });
  }
```

**Phone Details:**

![WhatsApp Image 2020-01-15 at 10 44 24 AM](https://user-images.githubusercontent.com/13154828/72449905-721d9f00-37df-11ea-945a-c2f2b0867ba9.jpeg)

**Comment by Zazo032** [comment]
Could you try using a newer version of Flutter to see if it's still happening? You can do that by running `flutter upgrade`, or `flutter channel master` + `flutter upgrade`. Also, you could try using breakpoints to see the line that is causing the error.

**Comment by niravandroid** [comment]
> 
> 
> Could you try using a newer version of Flutter to see if it's still happening? You can do that by running `flutter upgrade`, or `flutter channel master` + `flutter upgrade`. Also, you could try using breakpoints to see the line that is causing the error.

Okay Let me try with newer version. I will update here.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by niravandroid** [comment]
> 
> 
> Could you try using a newer version of Flutter to see if it's still happening? You can do that by running `flutter upgrade`, or `flutter channel master` + `flutter upgrade`. Also, you could try using breakpoints to see the line that is causing the error.

I have tried above steps but it displaying blank white screen.
output of flutter doctor -v after upgrading flutter
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at Z:\Work\Flutter_Workspace\Flutter_SDK\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at Z:\Work\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: Z:\Work\android-studio-ide-171.4408382-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at Z:\Work\android-studio-ide-171.4408382-windows\android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • POCO F1 • 4cf042b9 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by darrenaustin** [comment]
Thanks for the report and the code snippet. I don't see anything that would cause the kind of error you are seeing.  Can you give us the full stack trace of the exception (usually can be found in the logcat output when the error occurs)?

While the snippet looks fine, can you distill a simple self-contained app that reproduces this error? This will help us reproduce this problem.

**Comment by niravandroid** [comment]
> > Could you try using a newer version of Flutter to see if it's still happening? You can do that by running `flutter upgrade`, or `flutter channel master` + `flutter upgrade`. Also, you could try using breakpoints to see the line that is causing the error.
> 
> Okay Let me try with newer version. I will update here.

After upgrading flutter channel to master issue is solved. Thanks.
