### ISSUE TITLE
flutter tools should point to github issues

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#489]
It's really cool that we prompt our users to file a bug. We're currently pointing to http://flutter.io but it's probably better to point to https://github.com/flutter/flutter/issues/new

Thanks!

See https://github.com/flutter/flutter/blob/fd6bc856a7e0830512f2699140fff4724427b021/packages/flutter_tools/lib/src/device.dart#L563

**Comment by eseidelGoogle** [comment]
It's possible to edit the code directly from the website, as I just did. :)

https://github.com/flutter/flutter/pull/491

**Comment by sethladd** [comment]
Good point!

Also, thanks for the fix!
