### ISSUE TITLE
Document EditableText minLines better

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#48907]
The documentation for [`EditableText.minLines`](https://api.flutter.dev/flutter/widgets/EditableText/minLines.html) can be better described like [`EditableText.maxLines`](https://api.flutter.dev/flutter/widgets/EditableText/maxLines.html). 

cc/ @E1adi

**Comment by harshitjain007** [comment]
Is anyone working on this ? Otherwise I am happy to pick it up?

**Comment by arafaysaleem** [comment]
I'd like to work on this issue @shihaohong
