### ISSUE TITLE
Uncaught TypeError: Cannot read property '_match' of undefined

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#48909]
## Steps to Reproduce

Run a Flutter Web app that throws any exception using `--profile` or `--release`.

**Expected results:** 

The exception and stack trace should be printed to the console.

**Actual results:** 

```
main.dart.js:10219 Uncaught TypeError: Cannot read property '_match' of undefined
    at Object.StackFrame_fromStackTraceLine (main.dart.js:10219)
    at Object.FlutterError_defaultStackFilter (main.dart.js:19622)
    at Object.DiagnosticsStackTrace$ (main.dart.js:19658)
    at FlutterErrorDetails.debugFillProperties$1 (main.dart.js:43449)
    at _FlutterErrorDetailsNode.get$builder (main.dart.js:44766)
    at _FlutterErrorDetailsNode.get$builder (main.dart.js:43522)
    at _FlutterErrorDetailsNode.getProperties$0 (main.dart.js:44781)
    at TextTreeRenderer.render$4$parentConfiguration$prefixLineOne$prefixOtherLines (main.dart.js:44167)
    at TextTreeRenderer.render$1 (main.dart.js:44290)
    at Object.FlutterError_dumpErrorToConsole (main.dart.js:19610)
```

It looks like the format of dart2js StackTraces differs from DDC, so we are failing to match and throwing here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/stack_frame.dart#L85

In my example app, the line it is trying to match is `TypeError: Cannot perform Construct on a detached ArrayBuffer`.

We should fix StackTrace parsing for release mode.

**Comment by dnfield** [comment]
This is related to code I recently added.

That stack trace line looks really unhelpful.  It doesn't even look like part of a stack trace line.  Can we fix upstream instead?

**Comment by vsmenon** [comment]
> /cc @vsmenon Can we make DDC stacktraces consistent with dart2js?

Are you really asking for DDC to match the above?  What's the DDC trace you're getting for the above?

@sigmundch

**Comment by sigmundch** [comment]
> Can we make DDC stacktraces consistent with dart2js?

DDC goes to great length to translate stack traces as if they were in Dart code. I personally want to move away from that and keep them as JavaScript and do the translation separately (and we also have a request in the opposite direction to make VM and ddc stack traces more similar: https://github.com/dart-lang/sdk/issues/40117)

Let's follow up on a doc to gather some requirements here. I'm not sure we can make them 100% aligned, but it would be good to understand your needs and see how we can reduce the friction here.

**Comment by vsmenon** [comment]
@yjbanov @hterkelsen - converging the formats won't be something we'll able to do near term (i.e., this q) - see upstream bug.  Do you want to still keep this open?

**Comment by dnfield** [comment]
We should probably implement a work around in the framework for this for now then.

**Comment by vsmenon** [comment]
It's possible `package:stack_trace` can help here if it's not being used.

Removing the dart dep in favor of the upstream issue / longer term fix.

**Comment by yjbanov** [comment]
I'm going to look at it. It's causing a lot of noise in issue reports.
