### ISSUE TITLE
Application gets slower with hover events [web]

### ISSUE THREAD

**Issue by NicolasDionB** [flutter/flutter#48911]
## Details
I'm having performance issues with my Flutter web application. I have an app layout where I have a few buttons in a top bar (see screenshot). When clicking on the microphone button, I activate the user's microphone and start monitoring the audio input level. The level is displayed on the button itself, updated using a `BlocBuilder` so not everything is rebuilt when the level change, only the level widget itself.

While the microphone is active and displaying the level, the fps of the rendering gets down to as low as 25 on my computer (which was 60 when before starting the animation). I also noticed that I get the same behavior just overing a button (without the running animation, that is).

I though I did something wrong in my app so I tried with the new project app (the simple counter) and as it turns out, I have the same behavior hovering the button. I monitored the repainting by activating the "Repaint Rainbow" option in the DevTools. You will see that the whole page gets repaint when hovering the button.

I think this is a major performance issue. I noticed that displaying a dialog while the animation is playing, it doesn't get repainted as the rest of the widgets do.

Any idea? I tried using Flutter 1.13.9 and the latest master, which is 1.13.10-pre.54 when writing this.

**Target Platform: Windows 10**
**Target OS version/browser: Chrome 79.0.3945.117 64 bits**

![Clipboard - 15 janvier 2020 13_51](https://user-images.githubusercontent.com/25512495/72464463-4e3c6800-37a3-11ea-98c0-6b3f7dad10bf.png)

![image](https://user-images.githubusercontent.com/25512495/72464527-71671780-37a3-11ea-85eb-f23cf9cd1c5a.png)

## Flutter Doctor
```
[√] Flutter (Channel master, v1.13.10-pre.54, on Microsoft Windows [version 10.0.18362.535], locale fr-CA)
    • Flutter version 1.13.10-pre.54 at D:\_utils\Flutter
    • Framework revision d5b0b3c8d1 (23 hours ago), 2020-01-14 12:38:53 -0800
    • Engine revision fd269f60bf
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.8
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by iapicca** [comment]
Hi @NicolasDionB 
can you please provide a reproducible minimal code sample.
Thank you

**Comment by NicolasDionB** [comment]
@iapicca Sure! In fact, as I said, you can just create a new app with the command `flutter create myapp`. With this demo app, activate the "Repaint Rainbow" option in the DevTools and just hover and leave the the button with your cursor multiple times. You will that the whole stage gets repainted everytime. The same happened to me in my app with hovers but also when rebuilding a small widget with a `BlocBuilder`. In fact it's happening every time a widget is (re)built in my app, no just that one. It looks to me as if some optimisations are missing but... So the sample code is as follows (I removed all comments to make it shorter):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by iapicca** [comment]
Thank you @NicolasDionB

**Comment by dkwingsmt** [comment]
I'm guessing the optimization you're looking for is `RepaintBoundary`. Simply put, if there is a part of the widget tree that changes frequently and independently of the other part of the screen, wrap that part in a `RepaintBoundary`, and the repaint of the area within the boundary will not affect that outside of it. Needless to say, having too many such boundaries also negatively affects performance (which starts being noticeable at 50~100 on Web), so add boundaries wisely and sparingly, but in your case, since the microphone level changes constantly, I'd suggest trying wrap that part in a boundary. If this helps, then it's not really related to MouseRegion (as you've mentioned), but a general case for all widgets, and there is also a brief explanation that I've made in https://github.com/flutter/flutter/issues/49298 for reference.

**Comment by NicolasDionB** [comment]
@dkwingsmt This sound interesting. I did some testing and at first I didn't see any change but after experimenting a little, I found that I get results when I place my `CustomPaint` directly under the `RepaintBoundary` and not wrapping my whole widget in it. My `BlocBuilder` might change something for that matter. So it works better now. Thanks for the enlightenment about the painting process in Flutter, really helped. So as I understand it, it is normal that all parent elements get repainted as long as they are on the same painting "layer".

With isolating my animations, I was able to stay at 50-55fps even when both animations are playing, which is great (I was falling to about 25 before). I will keep all this in mind for future development.

Even in the demo app (counter), I was able to isolate the `FloatingActionButton` in a `RepaintBoundary` widget and thus the hover effect wasn't triggering the whole stage repaint. Only thing is the tooltip which is displayed at top-most level I guess and I had to remove it to get the isolation to work. 

Wouldn't it be possible to improve this repaint behavior as you generally don't want everything to get repainted when you rebuild a single widget, no?

Thanks again!

**Comment by dkwingsmt** [comment]
Glad it helps! Layering is part of the optimizations of Flutter, because it is how the underlying rendering engine (skia) works. Making every widget paint independently is the same as making every widget a different layer, which as I said will unavoidably negatively impact performance. :)

**Comment by dkwingsmt** [comment]
Closing since it is working as intended.
