### ISSUE TITLE
Make documentation page content searchable with CTRL-F

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#48924]
## Use case

I want to find a `ListView` widget function to scroll a widget into view.  I went to [Listview](https://api.flutter.dev/flutter/widgets/ListView-class.html) and pressed CMD-F in my browser to search in the page.  Then I typed 'scroll'.  The browser is showing me results in the CLASSES panel on the left, of which there are many.  I clicked many times trying to reach the results for 'scroll' in the `ListView` docs and finally didn't find what I was looking for.  I searched for 'show' and repeated the whole process again.  This is wasting time.
![Screen Shot 2020-01-15 at 15 23 28](https://user-images.githubusercontent.com/520739/72480137-45e82b00-37ab-11ea-986e-6d44839e9fec.png)

## Proposal

Make the browser's search-in-page function show results in the page before results in the CLASSES list.  Or move the CLASSES list to a separate page.

**Comment by dnfield** [comment]
We might need dartdoc to change to make this work.  

Do you think you could open a bug at https://github.com/dart-lang/dartdoc for this?  That's what we use to generate our docs.

**Comment by dnfield** [comment]
I'm going to close this here in the mean time.  Please let me know if anything isn't clear on where to actually file this bug :)

**Comment by dnfield** [comment]
I went ahead and filed https://github.com/dart-lang/dartdoc/issues/2131
