### ISSUE TITLE
Changing Gallery's item.dart line 48 (GalleryItem title) is not visible after hot reload

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4892]
* Start the iOS simulator
* Start the gallery with `flutter run --reload-sources`
* Open item.dart from the gallery
* Go down to line 48, or where you see the `title: 'Pesto',` line
* Change the text, e.g. by adding `!!`
* Go to the flutter tool console
* Type `r`

Expected:

* The gallery running in the simulator updates with the new title in the homescreen

Actual:

* No visible change

Note: if I force quit the flutter tool, which kills the app running in the simulator, and then restart the app, I see the change to the title in the app on the simulator.

Note: if I change home.dart's title on line 106, and then trigger a hot reload, then I'm able to see the new title appear immediately. Something weird about the GalleryItem title.

**Comment by sethladd** [comment]
cc @johnmccutchan @Hixie (if there's something the framework is doing that would prevent the reload from triggering?) @devoncarew

**Comment by devoncarew** [comment]
We send the `ext.flutter.reassemble` command after a successful reload sources (https://github.com/flutter/flutter/blob/ec752d813d08de2d7f66f1a4b39db1e78c245971/packages/flutter_tools/lib/src/ios/simulators.dart#L599). That _should_ rebuild the UI.

**Comment by johnmccutchan** [comment]
@sethladd You changed some code expressed inside a list (kAllGalleryItems) this list is already constructed so we won't ever run the new code.

**Comment by johnmccutchan** [comment]
@sethladd You could use Observatory / debugger to change the title of a `GalleryItem` inside `kAllGalleryItems` and then trigger a reassemble.

**Comment by sethladd** [comment]
Ah, thanks. I didn't realize this was a final list. Hm, this scenario will take some thinking. I would expect if I change text that is rendered to the UI, that the refresh would pick that up. I wonder if we need to put the framework into an "aggressive reload" mode?

**Comment by eseidelGoogle** [comment]
Should flutter tools or the DartVM warn in this case?

**Comment by sethladd** [comment]
Was just brainstorming that :)  Some ideas bounced around:

* leverage the fact that we have a functional framework, and put top-level fields behind functions
* add features to reloading to include reinitialization of top-level fields like this (not sure when we'd trigger that...)
* add a "reload coverage" like a "code coverage", but show via tools which paths were reloaded (and maybe why?) and/or which objects were re-new'ed from the last build
* other ideas here
