### ISSUE TITLE
How can I un-install Flutter completely and properly from my Mac?

### ISSUE THREAD

**Issue by Pedram-1** [flutter/flutter#48933]
## Question

I have run into an issue and have to un-install Flutter completely from my Mac; however, I cannot find any documentation that can assist me with that. Is there a way to properly un-install Flutter? 

## Logs

```
```

```
```

**Comment by dnfield** [comment]
```bash
rm -rf ~/.flutter*
rm -rf /path/to/flutter/directory
# Only do this if you have no other dart projects you care about. 
rm -rf ~/.pub-cache
rm -rf ~/.dart
rm -rf ~/.dartServer
```
