### ISSUE TITLE
Can't connect to Observatory from Atom

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4894]
Can't connect to Observatory from Atom. `flutter run` seems to work pretty well, though. Any ideas how to debug this?

```
Running lib/main.dart on Nexus 10...
--------- beginning of main
Observatory listening on http://127.0.0.1:37706
Diagnostic server listening on http://127.0.0.1:46488
Unable to connect to the Observatory at port 37706.
Application running.
```

**Comment by devoncarew** [comment]
I can reproduce this - I'm seeing:

```
WebSocket connection to 'ws://localhost:8102/ws' failed: Error during WebSocket handshake: Unexpected response code: 200
```

in the devtools log. This is likely a regression from the observatory protocol / origin port changes.

**Comment by eseidelGoogle** [comment]
Oh, we assumed it was just @dragostis's machine.  Thanks!

**Comment by devoncarew** [comment]
@johnmccutchan, I see this from the observatory web UI as well (`index.html.polymer.bootstrap.dart.js:15633 WebSocket connection to 'ws://localhost:8104/ws' failed: Error during WebSocket handshake: Unexpected response code: 200`). We're able to connect to the server protocol from dart:io websockets, but not from dart:html ones. This is with the latest engine runtime.

**Comment by johnmccutchan** [comment]
I have a fix about to land in the VM and then I will roll it into engine.

**Comment by eseidelGoogle** [comment]
Is this an area we should be trying to test?  Either in the vm, or flutter_tools or with some sort of integrated atom setup?  (FYI @yjbanov)

**Comment by johnmccutchan** [comment]
@eseidelGoogle This would be good to test but it is a bit involved:

- Service protocol is bound to port X on the device and port Y on the host (X != Y)
- A test running inside a browser on the host that attempts to connect to the service protocol over websocket on port Y.

**Comment by yjbanov** [comment]
I don't see anything specific to Atom. Our on-device tests should catch this easily.
