### ISSUE TITLE
Function cant set my local variable

### ISSUE THREAD

**Issue by abuanwar072** [flutter/flutter#48941]
`import 'package:flutter/material.dart';

class AddTaskScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String taskName;

    final double screenWidth = MediaQuery.of(context).size.width;
    final double screenHeight = MediaQuery.of(context).size.height;
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      height: screenHeight * 0.5,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(screenWidth * 0.05),
          topRight: Radius.circular(screenWidth * 0.05),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(
            'Add Task',
            textAlign: TextAlign.center,
            style: Theme.of(context)
                .textTheme
                .display1
                .copyWith(color: Colors.lightBlueAccent),
          ),
          TextField(
            autofocus: true,
            textAlign: TextAlign.center,
            onChanged: (newText) {
              taskName = newText;
            },
          ),
          SizedBox(height: screenHeight * 0.01),
          FlatButton(
            color: Colors.lightBlueAccent,
            onPressed: () {
              print(taskName);
            },
            child: Text(
              "Add",
              style: Theme.of(context).textTheme.button,
            ),
          ),
        ],
      ),
    );
  }
}
`
After press the "Add" button the 'taskName' show null. But if i print the taksName inside TextField is show the inputs.

**Comment by dnfield** [comment]
This would be a better question for a site like StackOverflow.  If you do post it there, please include a minimal and complete verifiable example - this post may not qualify for that.
