### ISSUE TITLE
Simulator link breaking from android studio after app run 

### ISSUE THREAD

**Issue by Anubhav01** [flutter/flutter#48949]
Simulator stops debugging mode after app run due to that simulator is working but not able to print or debug

**Comment by iapicca** [comment]
Hi @Anubhav01 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` ?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
