### ISSUE TITLE
Occasionally shows an abnormality after installation on a VIVO phone and requires reinstallation to resolve

### ISSUE THREAD

**Issue by ozyl** [flutter/flutter#48952]
[picture](https://s2.ax1x.com/2020/01/16/lvgDXQ.md.jpg)

This problem is currently only found on VIVO phones (test machine: VIVO Z5x; Android 9; Funtouch OS_9);
There is no problem on v1.9.1 + hotfix.6, but the images in this version seem to have a memory leak problem, so I want to upgrade the new version, and found this new error on v1.12.13 + hotfix.5 and v1.14.0 versions . please help me;

Doctor summary (to see all details, run flutter doctor -v):
```console
[√] Flutter (Channel dev, v1.14.0, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```

**Comment by iapicca** [comment]
Hi @ozyl 
can you please provide your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by ozyl** [comment]
Sorry, I have returned to v1.9.1 + hotfix.6 version, this should have nothing to do with my code, it is normal on other phones. And debug mode is normal on VIVO Z5x devices. Even occasionally in the Release version. Seems to be related to the installation mechanism of VIVO OS? I have discovered the issues that I am focusing on. The purpose of upgrading the version is to solve it.# 42492

**Comment by ozyl** [comment]
For some reason I upgraded to the latest master channel again, but I couldn't provide 'flutter run --verbose', because this problem only appeared in release packag. The problem was only showing some image.network widgets. I only found on VIVO Z5x This problem may occur in other VIVO models, but I do n’t have other VIVO equipment. You can use VIVO mobile phone to make a release packag, please help me solve this problem, thank you!

**Comment by ozyl** [comment]
Version Info
```
flutter --version
```
Flutter 1.14.1-pre.10 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5d37de2685 (4 days ago) • 2020-01-15 01:23:02 -0500
Engine • revision bc41ab5139
Tools • Dart 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)

**Comment by iapicca** [comment]
Hi @ozyl 
can you please provide your `flutter run --release --verbose`
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by wind-hx** [comment]
<img width="140" alt="企业微信截图_55274666-4713-4c73-a57b-6f2fa6794049" src="https://user-images.githubusercontent.com/17685971/85241552-bb4cdb80-b46e-11ea-9d24-54733d0b2672.png">

@ozyl Has the problem been solved?

**Comment by wind-hx** [comment]
I also encountered a similar problem

**Comment by ozyl** [comment]
> <img alt="企业微信截图_55274666-4713-4c73-a57b-6f2fa6794049" width="140" src="https://user-images.githubusercontent.com/17685971/85241552-bb4cdb80-b46e-11ea-9d24-54733d0b2672.png">
> 
> @ozyl问题解决了吗？

我不了解是什么引起的。目前的处理方案是OV手机app内重启。
