### ISSUE TITLE
Non-obvious error message from Atom plugin when missing device

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4896]
This is low priority, but should be easy to fix.

<img width="470" alt="screen shot 2016-07-12 at 12 25 25 pm" src="https://cloud.githubusercontent.com/assets/11857803/16780500/c759d4a4-482b-11e6-9231-d8f65bc1aebd.png">

To reproduce, hit command-r in Atom with no devices connected or simulators running.

**Comment by devoncarew** [comment]
fixed here: https://github.com/dart-atom/dartlang/pull/1066
