### ISSUE TITLE
Access to own ViewRef for Flutter on Fuschia

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48969]
Several Scenic APIs will be requiring the use of ViewRefs to refer to Views, but there is currently no way in flutter to gain access to the ViewRef of your own View since it's being created for you by the flutter engine. There needs to be some way to get it.

https://b.corp.google.com/issues/146347247.

**Comment by iskakaushik** [comment]
fixed by https://github.com/flutter/engine/pull/15958
