### ISSUE TITLE
[web]: <web no longer working>

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#48966]
<details>
	<summary>logs</summary>

```bash
DescrC:\Users\bened\Desktop\bmcr_crea_clock>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...                                10,5s
Attempting to connect to browser instance..                         8,6s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

�  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:55713/GssH6Lymv-8=
Thursday January 16
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/j
s_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/shader.dart 51:5                           createPaintStyle
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/bitmap_canvas.dart 265:45                  [_applyPaint]
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/bitmap_canvas.dart 508:5                   drawCircle
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/surface/recording_canvas.dart 899:11       apply
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/surface/recording_canvas.dart 78:18        apply
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/surface/picture.dart 253:35                paintCallback
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/surface/surface.dart 71:14                 commitScene
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_eng
ine/engine/surface/scene_builder.dart 520:5           build
package:flutter/src/rendering/layer.dart 801:35
buildScene
package:flutter/src/rendering/view.dart 230:36
compositeFrame
package:flutter/src/rendering/binding.dart 405:18
drawFrame
package:flutter/src/widgets/binding.dart 797:13
drawFrame
package:flutter/src/rendering/binding.dart 283:5
[_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1108:15
[_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1047:9
handleDrawFrame
package:flutter/src/scheduler/binding.dart 856:7
<fn>
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/j
s_dev_runtime/private/isolate_helper.dart 50:19       internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: UnimplementedError
Another exception was thrown: UnimplementedError
Another exception was thrown: UnimplementedError
Another exception was thrown: UnimplementedError
ibe your issue and include the command you're running, flutter_web version, browser version
```

</details>

**Comment by iapicca** [comment]
Hi @benedicte69 
can you please provide your `flutter doctor -v` ,
your `flutter run -d chrome --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by benedicte69** [comment]
I will as soon as possible, meaning not before next week...

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., janv. 17, 2020 à 7:35, Francecsco Iapicca<notifications@github.com> a écrit :   
Hi @benedicte69
can you please provide your flutter doctor -v ,
your flutter run -d chrome --verbose
and if possible a reproducible minimal code sample.
Thank you

**Comment by benedicte69** [comment]
At least I answer,

Here is a flutter doctor -v

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
flutter doctor verbose

GitHub Gist: instantly share code, notes, and snippets.
 |

 |

 |




Here is a  -d chrome --verbose

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
-d chrome --verbose

GitHub Gist: instantly share code, notes, and snippets.
 |

 |

 |




Concerning this part, I am noticing that the GMT time is not accurate
Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.
                 Status code: 404
                 Headers:                 {             "date": "Wed, 22 Jan 2020 01:10:16 GMT",  it is on my computer 02:10 but may be it does not matter             "content-length": "9",             "x-frame-options": "SAMEORIGIN",             "content-type": "text/plain; charset=utf-8",             "x-xss-protection": "1; mode=block",             "x-content-type-options": "nosniff",             "server": "dart:io with Shelf",             "via": "1.1 shelf_proxy"           }

That day as far as I remember I just added colours in a file and used them instead of material one and I separated /*Text(
  '$hour : $minute : $second',
),*/in a RichText


Thank you for your patience


    Le vendredi 17 janvier 2020 à 07:35:39 UTC+1, Francecsco Iapicca <notifications@github.com> a écrit :  
 
 
Hi @benedicte69
can you please provide your flutter doctor -v ,
your flutter run -d chrome --verbose
and if possible a reproducible minimal code sample.
Thank you

**Comment by nturgut** [comment]
As a temporary solution can you try using:

flutter run -d web-server

/cc @jonahwilliams

**Comment by benedicte69** [comment]
flutter run -d web-server     gives a blank page

    Le vendredi 24 janvier 2020 à 00:17:16 UTC+1, Nurhan Turgut <notifications@github.com> a écrit :  
 
 
As a temporary solution can you try using:

flutter run -d web-server

/cc @jonahwilliams

**Comment by benedicte69** [comment]
however in the chrome console, if that can help,  this message is repeated:
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'js_primitives.dart:32 Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'



    Le mercredi 29 janvier 2020 à 00:03:56 UTC+1, Benedicte <notifications@github.com> a écrit :  
 
 
 flutter run -d web-server     gives a blank page

 Le vendredi 24 janvier 2020 à 00:17:16 UTC+1, Nurhan Turgut <notifications@github.com> a écrit : 
 
 
As a temporary solution can you try using:

flutter run -d web-server

/cc @jonahwilliams

**Comment by benedicte69** [comment]
Apparently something to do with this part of the http://localhost:57234/packages/build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_primitives.dart
// Inside browser or nodejs.  if (JS<bool>('!', r'typeof console == "object"') &&      JS<bool>('!', r'typeof console.log != "undefined"')) {    JS('void', r'console.log(#)', string);    return;  }

When do you think it is going to be sorted out?

    Le mercredi 29 janvier 2020 à 00:38:56 UTC+1, Benedicte <notifications@github.com> a écrit :  
 
  however in the chrome console, if that can help,  this message is repeated:
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'js_primitives.dart:32 Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'



 Le mercredi 29 janvier 2020 à 00:03:56 UTC+1, Benedicte <notifications@github.com> a écrit : 
 
 
 flutter run -d web-server     gives a blank page

 Le vendredi 24 janvier 2020 à 00:17:16 UTC+1, Nurhan Turgut <notifications@github.com> a écrit : 
 
 
As a temporary solution can you try using:

flutter run -d web-server

/cc @jonahwilliams

**Comment by benedicte69** [comment]
Moreover, any attempt to load something from .pub-cache has got  a status code of 404
Could not load content for  xxxxxx      .pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/wrappers.dart : HTTP status code: 404

    Le jeudi 30 janvier 2020 à 04:32:37 UTC+1, Benedicte <notifications@github.com> a écrit :  
 
   Apparently something to do with this part of the http://localhost:57234/packages/build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_primitives.dart
// Inside browser or nodejs.  if (JS<bool>('!', r'typeof console == "object"') &&      JS<bool>('!', r'typeof console.log != "undefined"')) {    JS('void', r'console.log(#)', string);    return;  }

When do you think it is going to be sorted out?

 Le mercredi 29 janvier 2020 à 00:38:56 UTC+1, Benedicte <notifications@github.com> a écrit : 
 
 however in the chrome console, if that can help,  this message is repeated:
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'js_primitives.dart:32 Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1159:14js_primitives.dart:32 Another exception was thrown: NoSuchMethodError: invalid member on null: 'doesFitBounds'



 Le mercredi 29 janvier 2020 à 00:03:56 UTC+1, Benedicte <notifications@github.com> a écrit : 
 
 
 flutter run -d web-server     gives a blank page

 Le vendredi 24 janvier 2020 à 00:17:16 UTC+1, Nurhan Turgut <notifications@github.com> a écrit : 
 
 
As a temporary solution can you try using:

flutter run -d web-server

/cc @jonahwilliams

**Comment by benedicte69** [comment]
Thanks for attempting to help, if that can help: 
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: http://localhost:58479/packages/build_web_compilers/src/dev_compiler_stack_trace/stack_trace_mapper.dart.js
Source Map URL: stack_trace_mapper.dart.js.map

[console-export-2020-1-31_1-0-38.txt](https://github.com/flutter/flutter/files/4136853/console-export-2020-1-31_1-0-38.txt) from Mozilla

Now I think I am going on with my learning as for me it is still difficult to understand how debugging works in Flutter and still do not know what in my code suddenly stopped the web.
I hope you will find a solution, it is very convenient and so great to check the responsiveness of our app in chrome as it would be an ordeal to download hundreds of devices in the emulator.
Hope expert will sort that out all this mess, on my side, I am a little lost :) with my basic knowledge but very happy when our problem are taken in considerations even if very often they are related to your awkward code :) 
Thanks

**Comment by benedicte69** [comment]
oh I have forgotten I could catch some sort of RenderView, somewhere it mentions a FloatingActionButtonTransition, strange I do not have any floating action button
_FloatingActionButtonTransition ←╎                                 MediaQuery ←LayoutId-[<_ScaffoldSlot.floatingActionButton>] ←╎                                 CustomMultiChildLayout ← AnimatedBuilder ←

    Le vendredi 31 janvier 2020 à 01:17:53 UTC+1, Benedicte <notifications@github.com> a écrit :  
 
 
Thanks for attempting to help, if that can help:
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: http://localhost:58479/packages/build_web_compilers/src/dev_compiler_stack_trace/stack_trace_mapper.dart.js
Source Map URL: stack_trace_mapper.dart.js.map

console-export-2020-1-31_1-0-38.txt from Mozilla

Now I think I am going on with my learning as for me it is still difficult to understand how debugging works in Flutter and still do not know what in my code suddenly stopped the web.
I hope you will find a solution, it is very convenient and so great to check the responsiveness of our app in chrome as it would be an ordeal to download hundreds of devices in the emulator.
Hope expert will sort that out all this mess, on my side, I am a little lost :) with my basic knowledge but very happy when our problem are taken in considerations even if very often they are related to your awkward code :)
Thanks

**Comment by benedicte69** [comment]
PHOTO OF THE GUILT:
![0101](https://user-images.githubusercontent.com/19499129/73620893-2ae33b00-4634-11ea-9192-cf53d525da5d.JPG)
here a screenshot of the minuscule virus, believe me, I do not have any floating action button in my Widgets but there is one in the Render Tree with a clear ID:

└LayoutId-[<_ScaffoldSlot.floatingActionButton>](id: _ScaffoldSlot.floatingActionButton)

**How can I get rid of him, that is the question? How did he enter the render view, that is quite worrying?**

DESCRIPTION OF THE GUILT: 
![0205](https://user-images.githubusercontent.com/19499129/73621533-bd84d980-4636-11ea-96f3-783d1a7f9916.JPG)

**Comment by benedicte69** [comment]
@iapicca 
flutter run -d chrome with SafeArea
[CASE 02  d chrome.txt](https://github.com/flutter/flutter/files/4154179/CASE.02.d.chrome.txt)
flutter run --verbose with SafeArea
[CASE 02 --verbose.txt](https://github.com/flutter/flutter/files/4154200/CASE.02.--verbose.txt)
Thanls for your help

**Comment by mdebbar** [comment]
@benedicte69 could you share the Dart code you are trying to run?

**Comment by benedicte69** [comment]
Thanks. Unfortunately, it is not possible, despite its boilerplates it is a private code under licence. flutter run -d chrome seems to be working in all my other app excepted suddenly in this one on January 16. That is a pity, I would have liked to improve the responsiveness of it too experiment further and my fetich tool for that is chrome. That's lifeNow I am cleaning my computer from A to Z... The best thing I can do when things start going wrong...
    Le mercredi 5 février 2020 à 21:39:52 UTC+1, Mouad Debbar <notifications@github.com> a écrit :  
 
 
@benedicte69 could you share the Dart code you are trying to run?

**Comment by jonahwilliams** [comment]
Without a way to reproduce the issue on our end there is nothing for us to do here. I'm closing the issue for now, but feel free to re-open if you can provide a [minimal reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)
