### ISSUE TITLE
Flutter run hangs on "Running XCode build"

### ISSUE THREAD

**Issue by aryan9600** [flutter/flutter#48963]
I am unable to build for iOS.
`flutter run --debug` always hangs on "Running XCode build".

This is the last output when I ran `flutter --verbose run --debug`

```bash
[   +6 ms] Running Xcode build...
[        ] executing: [/Users/aryan/Projects/open_con/ios/] /usr/bin/env xcrun xcodebuild
-configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme
Runner BUILD_DIR=/Users/aryan/Projects/open_con/build/ios -sdk iphoneos
ONLY_ACTIVE_ARCH=YES ARCHS=arm64
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/vj/3bhykqjd2dz6cg8yqxr5y3rh0000gp/T/flutter_build_l
og_pipe.K5fv11/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true
COMPILER_INDEX_STORE_ENABLE=NO
```
It seems to get stuck at this step.

**Comment by aryan9600** [comment]
Output of `flutter -v doctor`:

` [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/aryan/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/aryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/aryan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category. `

**Comment by aryan9600** [comment]
Output of `flutter -v doctor`

`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/aryan/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/aryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/aryan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by iapicca** [comment]
Hi @aryan9600  
can you please provide your full `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by aryan9600** [comment]
Packages in `pubsec.yaml`:
 ` firebase_auth: ^0.15.3+1
    provider: ^4.0.1
    google_sign_in: ^4.1.1
    cloud_firestore: ^0.13.0+1
    shared_preferences: ^0.5.6
`
The output of `flutter run -v` is rather large. 

This is the last error which I could figure out means something. Then I just got a huge number of stack callback errors I think.


` In file included from /Users/aryan/Projects/open_con/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m:19:
                      /Users/aryan/Projects/open_con/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.h:38:1: error: expected ','
                      API_UNAVAILABLE(macCatalyst)
                      ^
                      In module 'Foundation' imported from /Users/aryan/Projects/open_con/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.h:19:
                      In module 'CoreFoundation' imported from
                      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/F
                      oundation.h:6:
                      In module 'Darwin' imported from
                      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Heade
                      rs/CoreFoundation.h:16:
                      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/os/availability.h:93:171: note: expanded
                      from macro 'API_UNAVAILABLE'
                          #define API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS__,__API_UNAVAILABLE6, __API_UNAVAILABLE5,
                          __API_UNAVAILABLE4,__API_UNAVAILABLE3,__API_UNAVAILABLE2,__API_UNAVAILABLE1, 0)(__VA_ARGS__)
                                                                                                                                                                                                ^
                      1 error generated.


                      ** BUILD FAILED **


                      The following build commands failed:
                      	CompileC
                      	/Users/aryan/Library/Developer/Xcode/DerivedData/Runner-andtzcuefroucxbihgttlapwkdmh/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AppAuth.build/Objec
                      	ts-normal/arm64/OIDExternalUserAgentIOSCustomBrowser.o /Users/aryan/Projects/open_con/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m
                      	normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
                      (1 failure)
[+5213 ms] Running Xcode build... (completed in 1,54,160ms, longer than expected)
[   +1 ms] Xcode build done.                                           154.2s
`

Another interesting thing is that, `flutter run` works perfectly if my app doesn't have these dependencies. I have already configured the firebase requirements three different times, so I dont think I made an error while doing that. Any help would be greatly appreciated in debugging this.

**Comment by iapicca** [comment]
Hi @aryan9600 
could you please run
```console
pod deintegrate
flutter clean
flutter pub cache repair
flutter pub get
Pod install
Pod repo update
rm iOS/Podfile 
```
if the issue persist, could you please attach 
a `.txt` file with your `flutter run --verbose`
thank you

**Comment by aryan9600** [comment]
I tried these steps, but it unfortuantely didn't help.
[error.txt](https://github.com/flutter/flutter/files/4087324/error.txt)

**Comment by synapp009** [comment]
Having the same issue.
[error.txt](https://github.com/flutter/flutter/files/4097401/error.txt)

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.12.13+hotfix.5 at /Users/michaelberger/development/flutter
    • Framework revision 27321ebbad (vor 6 Wochen), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michaelberger/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 9ED807EB-5D04-46ED-B807-11B9E9424FC0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)

! Doctor found issues in 1 category.```

**Comment by synapp009** [comment]
> Having the same issue.
> [error.txt](https://github.com/flutter/flutter/files/4097401/error.txt)
> 
> ```
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale de-DE)
>     • Flutter version 1.12.13+hotfix.5 at /Users/michaelberger/development/flutter
>     • Framework revision 27321ebbad (vor 6 Wochen), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/michaelberger/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.1, Build version 11A1027
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3.1)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [✓] VS Code (version 1.41.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.7.1
> 
> [✓] Connected device (1 available)
>     • iPhone 11 Pro Max • 9ED807EB-5D04-46ED-B807-11B9E9424FC0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1
>       (simulator)
> 
> ! Doctor found issues in 1 category.```
> ```

It changed minimum global platform at the Podfile to platform :ios, '9.0'. No it works

**Comment by jmagman** [comment]
If your plugins are referencing macCatalyst, then you need a newer version of Xcode.
https://github.com/openid/AppAuth-iOS/issues/489.

@synapp009 your logs don't reference `API_UNAVAILABLE(macCatalyst)`.  Can you file a new issue, filling out the template and including any errors you see in `flutter run -d <> -v`

**Comment by synapp009** [comment]
@jmagman had a different issue. Sorry

**Comment by RockNav24** [comment]
**I have the same issue. 
Has anyone figured a way to fix the issue?**

`[  +14 ms] Running Xcode build...
[  +20 ms] executing: [/Users/navodsanthana/AndroidStudioProjects/flash-chat-flutter/ios/] /usr/bin/env xcrun xcodebuild
-configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner
BUILD_DIR=/Users/navodsanthana/AndroidStudioProjects/flash-chat-flutter/build/ios -sdk iphonesimulator -arch x86_64
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/9_/0bt_4fkx6b3c117b__3dg0280000gn/T/flutter_tools.05FMSK/flutter_build_log_pipe.fnajhb/pipe_to
_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO`

**Comment by jmagman** [comment]
@RockNav24 See https://github.com/flutter/flutter/issues/47633.  This issue is closed.

**Comment by martintan** [comment]
It stopped hanging for me when I had Xcode with my Flutter project opened.

**Comment by mshenawy22** [comment]
same problem for me , any help?

**Comment by mshenawy22** [comment]
I know this seems weird , but for me it seems a firebase issue caused by that I didn't include the google plist file as It was my first time to compile for ios

**Comment by phil10xs** [comment]
This

> I know this seems weird , but for me it seems a firebase issue caused by that I didn't include the google plist file from firebase console as It was my first time to compile for ios

This seems familiar with me too. But what do you mean by google plist file

**Comment by phil10xs** [comment]
> I am unable to build for iOS.
> `flutter run --debug` always hangs on "Running XCode build".
> 
> This is the last output when I ran `flutter --verbose run --debug`
> 
> ```shell
> [   +6 ms] Running Xcode build...
> [        ] executing: [/Users/aryan/Projects/open_con/ios/] /usr/bin/env xcrun xcodebuild
> -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme
> Runner BUILD_DIR=/Users/aryan/Projects/open_con/build/ios -sdk iphoneos
> ONLY_ACTIVE_ARCH=YES ARCHS=arm64
> SCRIPT_OUTPUT_STREAM_FILE=/var/folders/vj/3bhykqjd2dz6cg8yqxr5y3rh0000gp/T/flutter_build_l
> og_pipe.K5fv11/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true
> COMPILER_INDEX_STORE_ENABLE=NO
> ```
> 
> It seems to get stuck at this step.

I have this same issue please has it been fixed??

**Comment by JasonHarambe** [comment]
Had the same issue. The first build seem to be slower on my side 586s but the second build is significantly faster 59.0s
I am on dev channel (flutter channel dev). Try changing to dev channel and see if it makes a difference

**Comment by MikePendo** [comment]
I have the same issue (as @RockNav24 ) _flutter run v_ get stuck on the following lines:
```
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/tn/44xg6n4d4533cjnk1t0df3bh0000gp/T/flutter_tools.gLybpU/flutter_build_log_pipe.0D14tO/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true
COMPILER_INDEX_STORE_ENABLE=NO

```
I did flutter clean  and upgrade (1.22) 
Any suggestions what can be done?

**Comment by jmagman** [comment]
If you are seeing something similar to this, can you file a new issue, filling out the template and include the output of `flutter run -d <> -v`?  It is very unlikely you are seeing the same `API_UNAVAILABLE(macCatalyst)` issue as reported.

**Comment by MikePendo** [comment]
@jmagman my bad (I think) its just take around 20 mins to build that the reason I thought it stuck. so I build it via Xcode and saw the build process.
