### ISSUE TITLE
QUESTION: OS Errors List and Error Codes Location

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#48967]
Where can I find a list of OS Errors and their Error Codes?

Here are some OS Errors reported to Sentry:

`SocketException: Failed host lookup: 'api.website.com' (OS Error: nodename nor servname provided, or not known, errno = 8)`

`SocketException: Failed host lookup: 'api.website.com' (OS Error: No address associated with hostname, errno = 7)`

`SocketException: OS Error: Bad file descriptor, errno = 9, address = api.website.com, port = 63224`

`SocketException: OS Error: Operation timed out, errno = 60, address = api.website.com, port = 55883`

`SocketException: OS Error: Connection reset by peer, errno = 54, address = sentry.io, port = 61971`

The above OS Errors all have an error code. I've looked through the Flutter source and also the engine repo but was unable to find those error codes. Is there a list of these OS errors in the source and if so, where is it?

Thanks for taking a look!

**Comment by bruno-garcia** [comment]
These error codes are from the operating system and Flutter is just relaying the info it got from it.

Here's for example the header file from Linux:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h

Microsoft has some docs too:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-constants

**Comment by searchy2** [comment]
Thank you so much @bruno-garcia, this is exactly what I was looking for. The reason I couldn't find the error codes anywhere in Flutter or Dart was because they were never there! 0.o
