### ISSUE TITLE
iOS simulator spamming console

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4897]
```
[INFO:accessibility_bridge.mm(305)] UpdateSemanticsTree
[INFO:accessibility_bridge.mm(305)] UpdateSemanticsTree
[INFO:accessibility_bridge.mm(305)] UpdateSemanticsTree
[INFO:accessibility_bridge.mm(305)] UpdateSemanticsTree
```

I doubt that's intentional?  @tvolkert

**Comment by eseidelGoogle** [comment]
Looks like this was already resolved in https://github.com/flutter/engine/commit/469d954a83dca4fdfb216b3c38b73c6a534bbb76, but we're just waiting for an engine roll.

**Comment by abarth** [comment]
I thought I did an engine roll that included this.
