### ISSUE TITLE
CupertinoApp Dark theme attribute

### ISSUE THREAD

**Issue by Tridie2000** [flutter/flutter#48978]
## Use case

I'm writing an app that uses CupertinoApp on iOS and MaterialApp on Android. With MaterialApp there is a theme and darkTheme attribute. But CupertinoApp only has one theme attribute. Because of this I'm unable to add a dark theme to my app using Flutter. 

## Proposal

What I'm proposing is that CupertinoApp gets a darkTheme attribute so we can add our dark theme CupertinoThemeData to it.

**Comment by PhilBelanger42** [comment]
More specifically, WHY hasn't this already been implemented?  

Also, are there any work-arounds for this rather than forcible detecting the current theme, creating multiple new classes, and changing themes dynamically at runitime based on the current theme of iOS?

**Comment by xster** [comment]
Merging to #48222
