### ISSUE TITLE
Text selection cursor does not understand scrolling

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4898]
Example code:
https://gist.github.com/eseidelGoogle/bc15918be8ff1f473ddb4e755699fdfd

I used a null InputValue, which might be confusing things?

Click on the Input and then scroll, note how the cursor doesn't stay stuck to the input value.

![flutter_01](https://cloud.githubusercontent.com/assets/11857803/16781244/26de8750-482f-11e6-9501-4f0f73906fe8.png)

@mpcomplete

**Comment by mpcomplete** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/3861 .
