### ISSUE TITLE
Typed Maps - like interfaces in TypeScript

### ISSUE THREAD

**Issue by KoTTi97** [flutter/flutter#48989]
I would love to see typed Maps in Dart/Flutter like it is possible in TypeScript.

TypeScript example:

```TypeScript
interface IPerson {
    name: string;
    age: number;
    height?: number;
}

const person: IPerson = {
    name: "Max",
    age: 26
}
```

I wish Dart/Flutter would support something like that so i do not have to create a class for it. It could look something like this:

```Dart
interface IPerson {
  String name;
  int age;
  height? double;
}

Map<IPerson> person = {
  name: "Max",
  age: 26,
} 
```

**Comment by jonahwilliams** [comment]
This sort of language level feature request would be better suited for github.com/dart-lang/language/issues

**Comment by KoTTi97** [comment]
Reposted as @jonahwilliams mentioned: https://github.com/dart-lang/language/issues/783
