### ISSUE TITLE
Unexplained MojoInternalError when making a read request

### ISSUE THREAD

**Issue by amarsten** [flutter/flutter#4900]
## Steps to Reproduce

Not entirely sure. If you run an app with an http.read() enough times it should pop up.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/amarsten/Documents/workspace/deeplocal/visitor/flutter
    • Framework revision 9c0c0225a6 (3 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/amarsten/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

## Logs and Crash Reports

══╡ EXCEPTION CAUGHT BY NETWORKING HTTP LIBRARY ╞═══════════════════════════════════════════════════
I/flutter : The following MojoInternalError object was thrown while sending bytes to the Mojo network library:
I/flutter : MojoInternalError: Failed to register the MojoHandle.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      MojoEventSubscription.MojoEventSubscription (package:mojo/src/event_subscription.dart:31)
I/flutter : #1      DataPipeDrainer.DataPipeDrainer (package:mojo/src/drain_data.dart:15)
I/flutter : #2      DataPipeDrainer.drainHandle (package:mojo/src/drain_data.dart:67)
I/flutter : #3      MojoClient._send.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/http/mojo_client.dart:186)
I/flutter : (elided 3 frames from package dart:async)
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : Exception: Request to http://10.0.1.149:3000 failed with status 500.
E/flutter : #0      MojoClient._checkResponseSuccess (package:flutter/src/http/mojo_client.dart:214)
E/flutter : #1      MojoClient.read.<anonymous closure> (package:flutter/src/http/mojo_client.dart:109)
E/flutter : #2      _RootZone.runUnary (dart:async/zone.dart:1204)
E/flutter : #3      _FutureListener.handleValue (dart:async/future_impl.dart:131)
E/flutter : #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
E/flutter : #5      _Future._propagateToListeners (dart:async/future_impl.dart:667)
E/flutter : #6      _Future._completeWithValue (dart:async/future_impl.dart:477)
E/flutter : #7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
E/flutter : #8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

**Comment by eseidelGoogle** [comment]
FYI @abarth @zanderso

**Comment by Hixie** [comment]
This happens to me all the time when using --hot launching the gallery.

**Comment by abarth** [comment]
This might happen if the network connection is interrupted.  We might not be handling that error properly.

**Comment by Hixie** [comment]
@johnmccutchan: fyi since this might affect the --hot rollout.

**Comment by Hixie** [comment]
I'm addressing this. For --hot, it's just that we're taking the root handle twice. For the general case, it's probably normal network issues but we're not handling them well so I'm adding lots of error handling.

**Comment by Hixie** [comment]
I've got a PR that adds lots of error handling. Once that lands I'm going to close this bug. Please don't hesitate to open a new bug if you see problems again (they'll hopefully have more useful error messages in the future).

**Comment by Hixie** [comment]
I'm going to close this bug because we now have better error handling which should help track down the real issue. If you see this again, please file a new bug with the new stack and hopefully it will have more information to help us track down the real issue.
