### ISSUE TITLE
Commit e768c92 caused a minor regression in gpu_percentage benchmarks

### ISSUE THREAD

**Issue by flar** [flutter/flutter#49003]
If you look at the benchmarks that measure gpu_percentage on the Flutter dashboard, they all took about a 10% hit after this commit.

https://github.com/flutter/flutter/commit/e768c92fbc6cf8bf4e1814ef950a6092bbb6f658

**Comment by flar** [comment]
It looks like the commit included a number of changes to the code that the bots use. @Hixie ?

**Comment by kf6gpe** [comment]
@Hixie @flar What are next steps here? My inclination is to rebaseline.

**Comment by flar** [comment]
The GPU percentage utility has since been disabled due to an incompatibility with Xcode 11 (see https://github.com/flutter/flutter/issues/45435).

**Comment by kf6gpe** [comment]
Based on your last comment, @flar, I'm thinking we close this as unactionable at this point?

**Comment by flar** [comment]
@liyuqian Would the figures even be comparable if we develop an alternate mechanism as per https://github.com/flutter/flutter/issues/45435?

**Comment by liyuqian** [comment]
@flar : if the new measurement tool also measures the same CPU/GPU percentage from Instruments, then I think it would be comparable. It's not guaranteed, but let's aim for that. In the worst case, any measurement that can give us a clear signal before and after your improvement would still be helpful, and we'll just rebaseline the target or create a new benchmark.

**Comment by kf6gpe** [comment]
@flar, did you end up deciding if the new measurement is the same as before? If not, I think I'm fine with rebaselining here.

**Comment by flar** [comment]
You can track the new measurement mechanism and what is expected of it in https://github.com/flutter/engine/pull/18087

**Comment by chinmaygarde** [comment]
Triage: This issue looks unactionable and parked. There is discussion in linked issues. Closing. Feel free to reopen in case this is not the case.
