### ISSUE TITLE
App might crash on startup in release mode (v1.13.9, 1.14.0 - v1.14.1)

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#49008]
In certain situations, the app might crash on startup (before any widget is built or rendered) only in release mode. It affects v1.13.9, 1.14.0 - v1.14.1, regardless of device.

Found by Google internal app https://b.corp.google.com/issues/147838390

**Comment by sergicastellsague** [comment]
@dkwingsmt That link is not public. Is there any way we can see it?

**Comment by dkwingsmt** [comment]
@sergicastellsague That link is only meant for reference and record, so that the github issue list is the single source of truth. If you encountered a similar issue as described, you’re welcome to add details here.

**Comment by Zazo032** [comment]
Is this fixed by https://github.com/flutter/flutter/pull/49086?

**Comment by aam** [comment]
This was fixed by revert https://dart-review.googlesource.com/c/sdk/+/132168 that landed in flutter/engine, that landed in flutter/flutter.

https://github.com/dart-lang/sdk/commit/e2aadc7a075da3b52957c93dc39d3b7fc86a5d1b is a reland of the revert(with the fix).
