### ISSUE TITLE
Add Icons.person_subtract

### ISSUE THREAD

**Issue by tedhenry100** [flutter/flutter#49014]
In a social app, following and unfollowing are both primary actions. Flutter has `Icons.person_add` but doesn't have `Icons.person_subtract`. Adding a `Icons.person_subtract` icon would be useful.

**Comment by HansMuller** [comment]
Updating the Material icons is a longstanding issue. See for example:
https://github.com/flutter/flutter/issues/18384#issuecomment-536049222
