### ISSUE TITLE
Gesture detector scale and pan should work together

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#49025]
## Use case

Currently in ```GestureDetector``` we are unable to use pan and scale together since pan is super of scale, but in reality pan happens when there is one finger on a component and scaling happens when there are multiple fingers. So i don't know why such issue should happens.

Our use case is that we have containers in stack which we want to pan & zoom & rotate using gestures.

## Proposal

The gesture detector should be able to call pan related functions on one finger movement and should call scale related function when there is more than on finger movement.

**Comment by Faiyyaz** [comment]
Also i have another finding that in iOS environment onPanUpdate is also call one more time when we leave/end pan

**Comment by yati989** [comment]
> Also i have another finding that in iOS environment onPanUpdate is also call one more time when we leave/end pan

Did you find any workaround for your use case? It seems like it is still not possible to use both simultaneously! I want to create a drawing canvas that wants scale gestures (for zooming, panning and rotating) and pan gestures (for drawing) to work simultaneously together. Please help!

**Comment by Faiyyaz** [comment]
No its not possible to use both that's why i asked them to help me!

**Comment by volskaya** [comment]
This is a huge blocker. Literally can't have a scale gesture in a scrollview, since its pan will always win the gesture arena.

While the gestures are still fighting, scaling with 2 pointers should win over 1 pointer pan.

**Comment by wanjm** [comment]
any one follow this? many people ask for it;

**Comment by MandarinSmell** [comment]
I'm making my own widget, so I need both scaling and panning gestures at the same time. I won't complain that Scaling is superset of Panning gesture... if I can distinguish if users are touching screen with 2 fingers or 1 finger. Even though Flutter says scaling is super set of panning, but there is no way to distinguish if user is trying to scaling or panning. I've never developed iOS, but there are codes which tell how many fingers are on the screen in Android for sure.

So I suggest that Flutter must have codes which tells how many fingers on the screen, so developers can know number of fingers on the screen, then we will be able to performing both panning and scaling by checking number of fingers. If number of fingers tells 1, then perform panning by using focalPoint or localFocalPoint. If number of fingers tells 2 or higher, then perform scaling by using scale/horizontalScale/verticalScale factor.

This may cause conflict when users put 2 fingers at first, and suddenly release only 1 finger, so Flutter must update number of fingers too when onScaleUpdate is called, then developers will handle rest of it.

**Comment by taodo2291** [comment]
> but there is no way to distinguish if user is trying to scaling or panning

As I have known we can use the Listener widget for the listens pointer event, then bases on the pointer id to detect how many fingers are touching the screen.

checkout  the package [gesture_x_detector](https://pub.dev/packages/gesture_x_detector) for more detail.
we can listen to both scale and pan events.

Anyways, it is better if the Gesture detector can support scale and pan together, so we don't need to build our own custom gesture detector.

**Comment by dancamdev** [comment]
This is a huge flaw in the GestureDetector Widget IMO. The one mentioned is a common use case, and I don't expect two extremely different gestures to collide because one is a superset of the othe. 

On top of that, the message isn't clear and onScaleUpdate being used for dragging results in bad naming.

We should strive for having both working at the same time without colliding, handling two different gestures.

**Comment by xu-baolin** [comment]
Hi, everyone,
#73474 This PR will expand the detail parameter of the scale gesture so that developers can get the number of tracking fingers when the event be triggered. I think this can meet the purpose.

**Comment by xu-baolin** [comment]
Scale is a superset so that you can put one finger down, pan, then without lifting that finger put a second down and switch to zooming.
See Also https://github.com/flutter/flutter/issues/49025#issuecomment-756594897

I will close this issue as solved.
Feel free to leave comments to request a reopen or file a new issue if it does not meet your purpose.
