### ISSUE TITLE
bug while flutter run

### ISSUE THREAD

**Issue by eko-prog** [flutter/flutter#49022]
<details>
	<summary>logs</summary>

```bash
C:\Users\owner\AndroidStudioProjects\scan\bug\android\app\src\debug\AndroidManifest.xml Error:

        uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:shared_pre
ferences] C:\Users\owner\AndroidStudioProjects\scan\bug\build\shared_preferences\intermediates\libra
ry_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16

        Suggestion: use a compatible library with a minSdk of at most 16,

                or increase this project's minSdk version to at least 19,

                or use tools:overrideLibrary="io.flutter.plugins.sharedpreferences" to force usage (
may lead to runtime failures)



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in l
ibrary [:shared_preferences] C:\Users\owner\AndroidStudioProjects\scan\bug\build\shared_preferences\
intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not avai
lable in 16

        Suggestion: use a compatible library with a minSdk of at most 16,

                or increase this project's minSdk version to at least 19,

                or use tools:overrideLibrary="io.flutter.plugins.sharedpreferences" to force usage (
may lead to runtime failures)



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 28s
Running Gradle task 'assembleDebug'...                             30.0s
Gradle task assembleDebug failed with exit code 1
```

</details>

**Comment by eko-prog** [comment]
C:\Users\owner\AndroidStudioProjects\scan\bug\android\app\src\debug\AndroidManifest.xml Error:

        uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:shared_pre
ferences] C:\Users\owner\AndroidStudioProjects\scan\bug\build\shared_preferences\intermediates\libra
ry_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16

        Suggestion: use a compatible library with a minSdk of at most 16,

                or increase this project's minSdk version to at least 19,

                or use tools:overrideLibrary="io.flutter.plugins.sharedpreferences" to force usage (
may lead to runtime failures)



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in l
ibrary [:shared_preferences] C:\Users\owner\AndroidStudioProjects\scan\bug\build\shared_preferences\
intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not avai
lable in 16

        Suggestion: use a compatible library with a minSdk of at most 16,

                or increase this project's minSdk version to at least 19,

                or use tools:overrideLibrary="io.flutter.plugins.sharedpreferences" to force usage (
may lead to runtime failures)



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 28s
Running Gradle task 'assembleDebug'...                             30.0s
Gradle task assembleDebug failed with exit code 1

**Comment by julianbraasch** [comment]
It seems like one of your dependencies (either direct or transitive) has its minSdkVersion set to 19. Which version of the ```SharedPreferences``` plugin are you using?

**Comment by iapicca** [comment]
Hi @eko-prog 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by eko-prog** [comment]
flutter doctor -v  is ok
flutter run is ok
but on device display bug berhenti with button exit

C:\Users\owner\AndroidStudioProjects\scan\bug>flutter run
Using hardware rendering with device SM A520F. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on SM A520F in debug mode...
Running Gradle task 'assembleDebug'...                              7.0s
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity( 7676): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 7676): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 7676): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this Fl
utterFragment.
D/FlutterActivityAndFragmentDelegate( 7676): Attaching FlutterEngine to the Activity that owns this Fragment.
Syncing files to device SM A520F...                              8,452ms (!)

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
q Quit (terminate the application on the device).
An Observatory debugger and profiler on SM A520F is available at: http://127.0.0.1:50075/mDFRRBD6WHo=/

now i am found next trobble

**Comment by eko-prog** [comment]
C:\Users\owner\AndroidStudioProjects\scan\bug>flutter doctor -v
[√] Flutter (Channel master, v1.14.1-pre.26, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.14.1-pre.26 at C:\src\flutter
    • Framework revision 6006c23757 (16 hours ago), 2020-01-16 07:21:25 -0800
    • Engine revision 8c855dba98
    • Dart version 2.8.0 (build 2.8.0-dev.2.0 862d5012ae)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\owner\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM A520F • 52100ca3fa0c34c5 • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by eko-prog** [comment]
yesterday not matter, but after i update android studio, is bug for me ! 
thank you

**Comment by eko-prog** [comment]
solved: i am try open with Android studio,  generate sign bundle on gradle build release, completed successfully, and now running on my device, but on terminal not running
