### ISSUE TITLE
When imagefilter.blur of backdropfilter on IOS device is on the platform view widget, the blur effect fails. Android device is normal

### ISSUE THREAD

**Issue by hjc22** [flutter/flutter#49021]
When Imagefilter.blur of Backdropfilter on IOS device is on the platform view widget, the blur effect fails. Android device is normal

**Comment by hjc22** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

**Comment by iapicca** [comment]
Hi @hjc22  
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
then in your app folder
`flutter clean`

If the issue persist please provide
 your updated `flutter doctor -v`,
your `flutter run --verbose`
and a minimal code sample to reproduce the problem
thank you

**Comment by ykaito21** [comment]
I also faced this issue too, maybe related to #24167

**Comment by iapicca** [comment]
Hi @hjc22 
I believe @ykaito21  is correct.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
