### ISSUE TITLE
Gallery: "Demos" title appears under the app bar on startup

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4902]
I just upgraded Flutter master and built a release version of the app. This is on a Nexus 5X.

![screenshot_20160712-152023](https://cloud.githubusercontent.com/assets/5479/16785705/5ad24550-4844-11e6-87d1-cb1a31512e47.png)

**Comment by HansMuller** [comment]
I've seen this as well however it only seems to happen the first time the gallery app is run. I'm guessing that the MediaQuery that effectively returns the status bar's height is failing.

**Comment by sethladd** [comment]
Thanks for taking a look.

@Hixie any ideas regarding MediaQuery ?

**Comment by sethladd** [comment]
This appears to be fixed. Thanks!

**Comment by sethladd** [comment]
Sorry, acted too soon. Bug on Android 5X, but working on iPhone 6S.

**Comment by sethladd** [comment]
Seems fixed on my 5X.

**Comment by michaeldesu** [comment]
I'm brand new to flutter, and just built & ran the demo (via flutter create myapp) and tried it on my Android device (Sony xperia tx), and noticed the header material is appearing underneath the status bar.

See screenshot:

![image](https://cloud.githubusercontent.com/assets/11791450/21677616/a36b72c8-d386-11e6-8a09-2f777a4150a1.png)

Here are my doctor details:

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/michael/flutter
    • Framework revision c613a85c0f (9 hours ago),
    • Engine revision 2f32e8054d
    • Tools Dart version 1.21.0

[✓] Connected devices
    • LT29i • CB5A1MKWRV • android-arm • Android 4.3 (API 18)

I guess this is similar to issue #4518.

Thanks.

**Comment by eseidelGoogle** [comment]
Same issue as https://github.com/flutter/flutter/issues/6586 I think.

**Comment by michaeldesu** [comment]
@eseidelGoogle : yes you're right, thanks alot for adding to a future fix list.

**Comment by kirbyfan64** [comment]
FWIW the core problem here (of the status bar overlapping the app) is *only fixed if you use an `AppBar`*. If you omit the `appBar` argument to `Scaffold`, the application will be covered by the status bar.

Workaround: Use this as the value for the `appBar` argument:

```dart
class NonexistentAppBar extends AppBar {
  NonexistentAppBar({Key key, this.padding=0.0}): super(
    key: key,
    backgroundColor: Colors.transparent,
    elevation: 0.0,
  );

  double padding;

  @override
  Size get preferredSize => new Size.fromHeight(padding);
}
```
