### ISSUE TITLE
Remove # from url in flutter web

### ISSUE THREAD

**Issue by gagsy** [flutter/flutter#49026]
Hi ,

Can is it possible a per now to remove # from url in flutter web ??

**Comment by iapicca** [comment]
Hi @gagsy 
I see there's an open [issue](https://github.com/flutter/flutter/issues/33245) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by noaman813** [comment]
what's the solution for this issue @iapicca

**Comment by iapicca** [comment]
@noaman813 
flutter [now](https://github.com/flutter/flutter/issues/33245#issuecomment-705095853) supports custom url strategies
here is how to implement it https://github.com/flutter/flutter/issues/33245#issuecomment-705095853
