### ISSUE TITLE
During use, the app is suddenly covered with a white translucent mask.

### ISSUE THREAD

**Issue by Andylove1314** [flutter/flutter#49023]
During use, the app is suddenly covered with a white translucent mask.
[screenshot](https://user-images.githubusercontent.com/6230034/72588504-7f4ba280-3933-11ea-831b-37e2e30b52cf.png)

thank you！

**Comment by Andylove1314** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/fengkun/Library/Android/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fengkun/Library/Android/sdk
    • Android NDK at /Users/fengkun/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

**Comment by julianbraasch** [comment]
I've only seen this before when showing a dialog where the content exceeds the maximum boundaries. Is this in debug or release mode? Is there any output in the log?

**Comment by Andylove1314** [comment]
> I've only seen this before when showing a dialog where the content exceeds the maximum boundaries. Is this in debug or release mode? Is there any output in the log?

I haven't encountered this problem with the simulator. Currently, this problem is only found in the release version, and it is really a mobile phone！

**Comment by iapicca** [comment]
Hi @Andylove1314  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by Andylove1314** [comment]
> flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/fengkun/Library/Android/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fengkun/Library/Android/sdk
    • Android NDK at /Users/fengkun/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

Thank you

**Comment by iapicca** [comment]
Hi again @Andylove1314 
can you please provide your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you for providing your `flutter doctor -v`

**Comment by Andylove1314** [comment]
> Hi again @Andylove1314
> can you please provide your `flutter run --verbose`
> and a reproducible minimal code sample.
> Thank you for providing your `flutter doctor -v`

I do n’t know when this bug appeared, or where it caused it, so I do n’t know how to provide you with the specific code, sorry！

flutter run --verbose：
There are too many logs, so it is not convenient to paste them out. Thanks again for your help

**Comment by iapicca** [comment]
Hi @Andylove1314 
for the issue to be workable need to be reproducible.

If you cannot provide a reproducible minimal code sample
please provide the steps to reproduce the issue;

also if you cannot paste your `flutter run --verbose` 
please copy in a `.txt` file and attach it to a post.

Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
