### ISSUE TITLE
Callback with bracket triggered automatically on build

### ISSUE THREAD

**Issue by moustaphachadly** [flutter/flutter#49036]
When we reference a callback, for example:
```
_onClicked() {
  print('clicked !');
}
// ...
RaisedButton(
  onPressed: _onClicked(),
),
```
the method `_onClicked()` is run automatically on build method.

This happens because of the bracket, the reference isn't well assigned.
The problem is that there is no warning and it's hard to debug.

**Comment by iapicca** [comment]
Hi @moustaphachadly 
can you please provide your `flutter doctor -v` ?
Thank you

**Comment by iapicca** [comment]
Hi @moustaphachadly 
you may want to add "void" as shown below

```dart
void _onClicked() { // <= add 'void' 
  print('clicked !');
}
```
does this solution solve the issue?
thank you

**Comment by Zazo032** [comment]
Also, calling it like this:
```dart
RaisedButton(
  onPressed: () => _onClicked(),
),
```

**Comment by jonahwilliams** [comment]
You're not referencing the callback, you're invoking it. See https://github.com/flutter/flutter/issues/49036#issuecomment-575593137

**Comment by moustaphachadly** [comment]
> Hi @moustaphachadly
> you may want to add "void" as shown below
> 
> ```dart
> void _onClicked() { // <= add 'void' 
>   print('clicked !');
> }
> ```
> 
> does this solution solve the issue?
> thank you

Yeah it works, as well as @Zazo032's answer. Thank you.

But why does the button not warning for this ? In my app I spent a lot of time to figure out what were going wrong before I created this issue.
