### ISSUE TITLE
Adding color property to a FlatButton with CircleBorder shape causes onPressed to not be triggered on web

### ISSUE THREAD

**Issue by umutseven92** [flutter/flutter#49034]
_onPressed_ is not triggered in FlatButton (or RaisedButton) with a _CircleBorder_ shape when _color_ property is set on Flutter Web. It works as expected if the _color_ property is deleted, _CircleBorder_ is changed to _RoundedRectangleShape_, or if the button is increased in size (to something like 100 x 100). 

This problem does not occur on mobile.

## Steps to Reproduce

1) Use example file:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: FlatButton(
            textColor: Colors.red,
            highlightColor: Colors.black,
            splashColor: Colors.green,
            color: Colors.white60, // <-- this breaks onPressed
            shape: CircleBorder(
              side: BorderSide(color: Colors.red)
            ),
            onPressed: _incrementCounter,
            child: Text(_counter.toString()),
          ),
        ),
      ),
    );
  }
}

```
2) Press button in middle.

**Expected results:** 
_onPressed_ should be called.

**Actual results:** 
_onPressed_ is not triggered.

<details>
  <summary>Logs</summary>

```
Analyzing circleborder...                                               
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @umutseven92 
your code seems to work
<iframe style="width:400px;height:400px;" src="https://dartpad.dev/embed-inline.html?id=c9091a08a9ad7e06ce808da63e6323b3&split=80&theme=dark></iframe>
can you please provide your `flutter doctor -v` _
Thank you

**Comment by umutseven92** [comment]
Hello @iapicca, my doctor output is in the original comment under Logs.

**Comment by iapicca** [comment]
My apologize,  I didn't see it

**Comment by umutseven92** [comment]
@iapicca No problem. I cannot get it working in the dartpad link you've sent me either; the button only triggers if pressed on the bottom right corner.

**Comment by ferhatb** [comment]
Note: Reproduced on zoom level > 100% on Chrome. Clicking towards left top outside circle is triggering onPressed. Basically at any zoom level path.contains is failing. Likely same bug as https://github.com/flutter/flutter/issues/44470

**Comment by ferhatb** [comment]
Fixed in https://github.com/flutter/engine/pull/15743.
