### ISSUE TITLE
flutter/engine doesn't build with default build instructions.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4903]
@abarth @jamesr 

Building flutter/engine does not seem to work by following [CONTRIBUTING.md](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md).

```
Command: python /usr/local/google/home/dtiselice/Workspace/engine/src/build/android/gyp/find.py ../../third_party/android_tools/sdk/extras/google/google_play_services/libproject/google-play-services_lib/res
Returned 1.
stderr:

../../third_party/android_tools/sdk/extras/google/google_play_services/libproject/google-play-services_lib/res does not exist
```

This is probably because although `tools/android/download_android_tools.py` *does* extract the missing files, `build/install-build-deps-android.sh` seems to delete it. The current solution is to remove `third_party` and execute `tools/android/download_android_tools.py` after running `build/install-build-deps-android.sh`.

@jason-simmons 

> the problem specifically seems to be the build/install-android-sdks.sh script.  it's upgrading the version of Google Play services in third_party/android_tools to something that doesn't match our build files

**Comment by jason-simmons** [comment]
Version 31 of the Play Services package in the Android SDK removed some files that build/config/android/config.gni is looking for

Does Mojo or Chromium have an updated version of android/config.gni that we could downintegrate?

As a workaround, try running build/install-build-deps-android.sh with the --skip-sdk-packages flag

**Comment by jason-simmons** [comment]
This should be fixed now
