### ISSUE TITLE
Native widget receives taps it shouldn't receive

### ISSUE THREAD

**Issue by sma** [flutter/flutter#49040]
A map widget inside a scaffold with an app bar (without app bar there is no problem) which is inside a stack that overlays a smallish button above the map will wrongly receive taps to that button – but only if that tap triggers a navigation. If the button is very large and you tap in the center of the button, everything is okay. If it doesn't trigger a navigation, everything is fine, too.

The problem occurs on iOS. I haven't checked Android.

I also haven't checked whether this happens with other platform widgets – it was difficult enough to find the conditions of when it occurs – but my guess is yes.

## Steps to Reproduce

Use `google_map_flutter` in version 0.5.21+15 as dependency for the following application:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Bug()));

class Bug extends StatefulWidget {
  @override
  _BugState createState() => _BugState();
}

class _BugState extends State<Bug> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('there must be an app bar w/title')),
      body: Stack(
        alignment: Alignment.center,
        children: <Widget>[
          GoogleMap(
            initialCameraPosition: CameraPosition(target: LatLng(54.3, 10.1), zoom: 10.0),
            onTap: (position) {
              print('tapped on map: $position');
            },
          ),
          Positioned(
            bottom: 32,
            width: 56,
            height: 56,
            child: FlatButton(
              shape: CircleBorder(),
              color: Colors.pink,
              onPressed: () {
                print('this should not trigger the map');
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => Scaffold(backgroundColor: Colors.purple),
                  ),
                );
              },
              child: Icon(Icons.adb, color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }
}
````

Tapping on the map shows a position.

Tapping on the button (more towards the button's edge than to the center)  should navigate to a purple screen and should *not* trigger also the map's callback which shoes a position. But it does.

<details>
  <summary>Logs</summary>

```
Rachelles-MBP:~ rachelle$ flutter doctor -v
[✓] Flutter (Channel master, v1.13.9-pre.24, on Mac OS X 10.15.2 19C57, locale
    de-DE)
    • Flutter version 1.13.9-pre.24 at /Users/rachelle/Work/flutter
    • Framework revision fabf4e3d0d (vor 9 Tagen), 2020-01-08 15:28:02 -0800
    • Engine revision 46adf73d51
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rachelle/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @sma 
You can try https://github.com/flutter/flutter/issues/20798#issuecomment-414157564

**Comment by iapicca** [comment]
Hi @sma 
does the proposed [solution](https://github.com/flutter/flutter/issues/49040#issuecomment-575607912) work for you?
Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
