### ISSUE TITLE
After stop `flutter channel` when it's downloading Dart SDK, `flutter doctor -v` never work.

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#49050]
## Steps to Reproduce

1. change flutter channel
2. `flutter channel`, and I stop it by `ctr + z` when it's downloading `Dart SDK`
```sh
[me]@[computer name] [some any folder path]> flutter channel
Downloading Dart SDK from Flutter engine 85a8ac4255a8a7b79976ddec66a743abedc4709f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Job 3, 'flutter channel' has stopped
```
3, `flutter doctor  -v` not working, just stuck there.

**Expected results:** hope flutter environment become ok after run some flutter cmd in this case.

**Actual results:**  `flutter doctor  -v` not working, just stuck there.

`flutter analyze`
```
[nothing output]
```

`flutter doctor -v`
```
[nothing output]
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @jerryzhoujw 
I would advice you to download SDK anew

**Comment by jerryzhoujw** [comment]
how

**Comment by jerryzhoujw** [comment]
by the way,  I think change channels need download sdk not an good idea if need switch channel from beta & stable because need to develop both for stable & web in current stage.

So, if the dart sdk also cache in local like flutter sdk would be nice.

**Comment by jerryzhoujw** [comment]
Hi @VladyslavBondarenko 

Should I delete 

- `flutter/bin/cache/artifacts` or 
- `flutter/bin/cache/engine.stamp` or 

to trigger the download SDK anew ?

**Comment by VladyslavBondarenko** [comment]
@jerryzhoujw 
You can try delete only mentioned by you. I tried to delete everything from cache folder and this my `flutter doctor` is hanging on `Running pub upgrade...`

Above I meant delete your Flutter folder completely and [download SDK anew](https://flutter.dev/docs/get-started/install) - it is always a solution)

**Comment by jerryzhoujw** [comment]
I wait for an hour, and it's still no progress, so I delete whole `flutter/bin/cache ` folder.
And it's start downloading now.

> flutter doctor -v

```sh
Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  200M    0 1294k    0     0  18610      0  3:08:29  0:01:11  3:07:18 16072
```

**Comment by VladyslavBondarenko** [comment]
Cool!
@jerryzhoujw may I close the issue?

**Comment by jerryzhoujw** [comment]
So the solution of this issue is:

1. delete folder in your sdk path `flutter/bin/cache`
2. run `flutter doctor -v` again will trigger downloading  Dart SDK

PS: if your network is slow because in china.

Do things bellow maybe speed up your the download speed(for me it's speed up 3x) for changing channel:

1. export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
2. change flutter channel, for example `flutter channel stable`
3. run `flutter doctor -v`

**Comment by jerryzhoujw** [comment]
Sure. Thank you @VladyslavBondarenko

**Comment by jerryzhoujw** [comment]
Related to [#2055](https://github.com/flutter/flutter/issues/2055)

**Comment by rahmanrezaee** [comment]
this show this message 
`
 BITS Transfer
    This is a file transfer that uses the Background Intelligent Transfer Service (BITS).
    [                                                                                                            ]

    Transferring
`
