### ISSUE TITLE
Flutter Logo Link is no longer valid in flutter/flutter/README.md

### ISSUE THREAD

**Issue by egorbelibov** [flutter/flutter#49059]
🙃The following image no longer exits: https://flutter.dev/assets/flutter-lockup-4cb0ee072ab312e59784d9fbf4fb7ad42688a7fdaea1270ccf6bbf4f34b7e03f.svg

**Comment by Zazo032** [comment]
Fixed by https://github.com/flutter/flutter/pull/49056

**Comment by egorbelibov** [comment]
@Zazo032 Actually, it doesn't, the image size is incorrect 🙃 (it's too big)
It should have a height of **37 pixels** and the previous image was a **.svg**

**Comment by Zazo032** [comment]
That's true, it's too big: https://github.com/dvska/flutter/blob/patch-2/README.md

**Comment by egorbelibov** [comment]
The **official flutter resources** can be found here: https://drive.google.com/drive/folders/1KXNtO9My2AMpDOF9A9Y_4aj4_BcgmDDT

**Comment by egorbelibov** [comment]
Kind of fixed in: #49078
