### ISSUE TITLE
Unexpected Input highlight in stocks example

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#4905]
In the stocks example, clicking the search icon and then clicking on the Input field thickens and highlights the underline in purple to indicate that it is selected. However, after pressing enter and dismissing the keyboard, this highlight remains. Is this intentional, or is this a bug? I would expect it to go back to its original visual state, to indicate that it is no longer selected. Changing the autofocus property of the search bar to false appears to make no difference.

**Comment by eseidelGoogle** [comment]
@mpcomplete may know.

**Comment by mpcomplete** [comment]
This is even more obnoxious lately. You can't even dismiss the keyboard anymore. Changing the milestone.

**Comment by sethladd** [comment]
I couldn't repro this, but I might be looking for the wrong thing.

Can we repro this in the gallery or with a smaller test case?

Optimistically closing, but if it's still happening, we can reopen.

**Comment by collinjackson** [comment]
I think maybe the issue you're dealing is that submitting an input field doesn't cause it to lose focus. To de-focus an input field, you can call Focus.clear(context). This will cause it to lose the purple underline.

Here's an example that does that: https://gist.github.com/collinjackson/df9b6f9708eaf95017deedd0ad1df7ff
