### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotRestartMillisecondsToFrame regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49063]
Looks like it started at https://github.com/flutter/flutter/pull/48460, or maybe https://github.com/flutter/flutter/pull/48915. I'm skeptical of both, however. Maybe the baseline was too low to begin with?

**Comment by goderbauer** [comment]
One of the suspects (#48460) got recently reverted, but then the agent went down that's producing data for this benchmark. Ergo, we don't know yet if that revert fixed things.

**Comment by goderbauer** [comment]
After talking to cbracken we decided to ignore this issue for the current roll.

**Comment by goderbauer** [comment]
The benchmark dropped back down after the revert. Closing.
