### ISSUE TITLE
Fail the github auto-merge bot if any check other than the tree check fails

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#49061]
The auto-merge bot was added in https://github.com/flutter/flutter/issues/44007.

As discovered in https://github.com/flutter/engine/pull/15696, the auto-merge bot does not merge if any check fails and keeps waiting for it to go green. This logic works only for the tree checks ("luci-engine" in engine repo and "flutter-build" in flutter repo) but not for other checks because they will never go green once they fail (eg: Linux Fuchsia).

Could the bot please drop the "waiting for tree to go green" label if it detects that a check other than the tree checks failed? That would also signal to the bot that it no longer needs to look at that PR till that label is re-added.

**Comment by rmistry** [comment]
@dnfield

**Comment by dnfield** [comment]
Currently deploying the fix for this to appengine.

**Comment by rmistry** [comment]
Thanks! Will test this out soon.
