### ISSUE TITLE
Failed assertion: line 4774 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by abcnow** [flutter/flutter#49066]
With the latest update every time that I ran my app and I try to login..(My input box field changes color when it is active). it is giving me this error:

```bash
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4774 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
MaterialApp 
lib/main.dart:37
```

```bash
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                           51.8s
flutter: Julia Gordon
flutter: [Instance of 'RoleModel', Instance of 'RoleModel', Instance of 'RoleModel']
flutter: _focusNode_0 Has focus: true
flutter: isFocused_t0 is: true
flutter: _focusNode_1 Has focus: true
flutter: isFocused_t1 is: true
flutter: _focusNode_0 Has focus: false
flutter: isFocused_t0 is: false


════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building InputDecorator(decoration: InputDecoration(labelText: "Email", hintText: "Your Email", hintMaxLines: "1", contentPadding: EdgeInsets.all(20.0), suffixIcon: Icon(IconData(U+0E0BE), color: Color(0xff8db0ff)), fillColor: Color(0xff1a60fe), border: _NoInputBorder(), alignLabelWithHint: false), baseStyle: TextStyle(inherit: true, color: Color(0xdd000000)), isFocused: false, isEmpty: false, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#41b85], Directionality, MediaQuery], state: _InputDecoratorState#cc993(tickers: tracking 2 tickers)):
'package:flutter/src/services/text_input.dart': Failed assertion: line 846 pos 12: 'attached': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

he relevant error-causing widget was
    TextFormField 
lib/…/login/login.dart:97
When the exception was thrown, this was the stack
#2      TextInputConnection.setStyle 
package:flutter/…/services/text_input.dart:846
#3      EditableTextState.didUpdateWidget 
package:flutter/…/widgets/editable_text.dart:1175
#4      StatefulElement.update 
package:flutter/…/widgets/framework.dart:4469
#5      Element.updateChild 
package:flutter/…/widgets/framework.dart:3052
#6      SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5525
...
════════════════════════════════════════════════════════════════════════════════


════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4774 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
    MaterialApp 
lib/main.dart:37
════════════════════════════════════════════════════════════════════════════════
```

```console
PS /Users/ac/Downloads/appnow-myapp_app-abcc98b85f40 2> flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 1.5s
Downloading android-arm-release/darwin-x64 tools...                 1.0s
Downloading android-arm64-profile/darwin-x64 tools...               1.1s
Downloading android-arm64-release/darwin-x64 tools...               1.0s
Downloading android-x64-profile/darwin-x64 tools...                 1.1s
Downloading android-x64-release/darwin-x64 tools...                 1.0s
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.6 at /Users/ac/Documents/www/flutter
    • Framework revision 659dc8129d (3 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 38.1.3
    • Dart plugin version 191.8348

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] VS Code (version 1.37.0)
    • VS Code at /Users/ac/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 40FD77D8-9028-4169-A926-8C3AB371A3E3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome
      79.0.3945.117
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

```bash
PS /Users/ac/Downloads/appnow-myapp_app-abcc98b85f40 2> flutter run --verbose
[  +22 ms] executing: [/Users/ac/Documents/www/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 659dc8129d4edb9166e9a0d600439d135740933f
[        ] executing: [/Users/ac/Documents/www/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.6-0-g659dc8129
[   +7 ms] executing: [/Users/ac/Documents/www/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/ac/Documents/www/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +43 ms] executing: [/Users/ac/Documents/www/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +4 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +21 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] executing: /Users/ac/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/ac/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +12 ms] executing: /Users/ac/Documents/www/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +46 ms] executing: /usr/bin/xcode-select --print-path
[   +5 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[ +247 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 11.3.1
           Build version 11C504
[   +2 ms] /usr/bin/xcrun simctl list --json devices
[ +119 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +42 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] No supported devices connected.
[   +8 ms] "flutter run" took 644ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:328:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:522:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:512:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:333:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:227:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/ac/Documents/www/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by iapicca** [comment]
Hi @abcnow 
```
[  +46 ms] No supported devices connected.
[   +8 ms] "flutter run" took 644ms.
```
can you please run `flutter run --verbose` selecting a device and
share a reproducible minimal code sample.
Thank you

**Comment by abcnow** [comment]
Hi iapicca: I have attached here the code that is reproduced with the "flutter run --verbose"..  thanks for looking into this!
---
[flutter run verbose. txt.txt](https://github.com/flutter/flutter/files/4088402/flutter.run.verbose.txt.txt)

**Comment by iapicca** [comment]
Hi @abcnow 
```bash
#61     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
[        ] flutter: "Email", hintText: "Your Email", hintMaxLines: "1", contentPadding:
EdgeInsets.all(20.0),
[        ] flutter: suffixIcon: Icon(IconData(U+0E0BE), color: Color(0xff8db0ff)), fillColor:
Color(0xff1a60fe), border:
[        ] flutter: _NoInputBorder(), alignLabelWithHint: false), baseStyle: TextStyle(inherit: true,
color:
[        ] flutter: Color(0xdd000000)), isFocused: false, isEmpty: false, dependencies:
[_InheritedTheme,
[        ] flutter: _LocalizationsScope-[GlobalKey#aad7c], Directionality, MediaQuery], state:
[        ] flutter: _InputDecoratorState#3071a(tickers: tracking 2 tickers)):
[        ] flutter: 'package:flutter/src/services/text_input.dart': Failed assertion: line 745 pos
12: 'attached': is
[        ] flutter: not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should
provide substantially
[        ] flutter: more information in this error message to help you determine and fix the
underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   TextFormField
```
would be useful if you could share a reproducible minimal code sample.
Thank you

**Comment by abcnow** [comment]
@iapicca everything was working fine until the latest update from google...

class LoginPage extends StatefulWidget {
  @override
  LoginPageState createState() => LoginPageState();
}

class LoginPageState extends State<LoginPage> {
  final _formKey = GlobalKey<FormState>();
  final _scaffoldKey = GlobalKey<ScaffoldState>();
  String _email, _password;
  FocusNode _focusNode_0 = new FocusNode();
  FocusNode _focusNode_1 = new FocusNode();

  var _obscure = true;
  var _isSubmitting = false;
  var _isFocused_t0 = false;
  var _isFocused_t1 = false;

  Widget _registerType() {
    return Padding(
      padding: const EdgeInsets.only(
        top: 50.0,
      ),
      child: new Row(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.only(left: 25.0),
            child: GestureDetector(
              onTap: () {
                Navigator.pushNamed(context, '/clientlogin');
              },
              child: new Text(
                'Login',
                style: new TextStyle(
                    fontWeight: FontWeight.w400,
                    fontSize: 30,
                    color: Colors.black),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 60.0),
            child: GestureDetector(
              onTap: () {
                Navigator.pushNamed(context, '/clientregister');
              },
              child: new Text(
                'Join Now',
                style: new TextStyle(
                    fontWeight: FontWeight.w400,
                    fontSize: 30,
                    color: Color.fromRGBO(195, 197, 223, 1)),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _showForm() {
    final deviceOrientation = MediaQuery.of(context).orientation;
    final userInfo = Provider.of<UserProvider>(context);
    final roleInfo = Provider.of<RoleProvider>(context);

    return Padding(
      padding: const EdgeInsets.only(top: 70.0),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.only(top: 30.0),
              child: Container(
                width: MediaQuery.of(context).size.width / 1.2,
                decoration: new BoxDecoration(color: Colors.white, boxShadow: [
                  new BoxShadow(
                      color: _isFocused_t0 == true
                          ? Color.fromRGBO(0, 79, 255, 1)
                          : Colors.black26,
                      blurRadius: 20.0,
                      offset: Offset(0, 1),
                      spreadRadius: -5.0)
                ]),
                child: TextFormField(
                  keyboardType: TextInputType.emailAddress,
                  focusNode: _focusNode_0,
                  validator: (val) => !val.contains('@') || !val.contains('.')
                      ? 'Invalid Email'
                      : null,
                  onSaved: (val) => _email = val,
                  style: TextStyle(
                      color: _isFocused_t0 == true
                          ? Colors.white
                          : Colors.black87),
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    contentPadding:
                        EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
                    labelText: 'Email',
                    labelStyle: TextStyle(
                        color: _isFocused_t0 == true
                            ? Color.fromRGBO(141, 176, 255, 1)
                            : Colors.black87),
                    hintText: 'Your Email',
                    hintStyle:
                        TextStyle(color: Color.fromRGBO(141, 176, 255, 1)),
                    filled: _isFocused_t0,
                    fillColor: Color.fromRGBO(26, 96, 254, 1),
                    suffixIcon: Icon(
                      Icons.email,
                      color: Color.fromRGBO(141, 176, 255, 1),
                    ),
                  ),
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 30.0),
              child: Container(
                width: MediaQuery.of(context).size.width / 1.2,
                decoration: new BoxDecoration(color: Colors.white, boxShadow: [
                  new BoxShadow(
                      color: _isFocused_t1 == true
                          ? Color.fromRGBO(0, 79, 255, 1)
                          : Colors.black26,
                      blurRadius: 20.0,
                      offset: Offset(0, 1),
                      spreadRadius: -5.0)
                ]),
                child: TextFormField(
                  focusNode: _focusNode_1,
                  validator: (val) =>
                      val.length < 5 ? 'Password too short' : null,
                  onSaved: (val) => _password = val,
                  style: TextStyle(
                      color: _isFocused_t1 == true
                          ? Colors.white
                          : Colors.black87),
                  obscureText: _obscure,
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    contentPadding:
                        EdgeInsets.symmetric(horizontal: 20.0, vertical: 20.0),
                    labelText: 'Password',
                    labelStyle: TextStyle(
                        color: _isFocused_t1 == true
                            ? Color.fromRGBO(141, 176, 255, 1)
                            : Colors.black87),
                    hintText: 'Enter password',
                    hintStyle:
                        TextStyle(color: Color.fromRGBO(141, 176, 255, 1)),
                    filled: _isFocused_t1,
                    fillColor: Color.fromRGBO(26, 96, 254, 1),
                    suffixIcon: IconButton(
                      icon: _obscure
                          ? Icon(
                              Icons.visibility_off,
                              color: Color.fromRGBO(141, 176, 255, 1),
                            )
                          : Icon(
                              Icons.visibility,
                              color: Color.fromRGBO(141, 176, 255, 1),
                            ),
                      onPressed: () {
                        setState(() {
                          _obscure = !_obscure;
                        });
                      },
                    ),
                  ),
                ),
              ),
            ),
            Padding(
              padding: EdgeInsets.only(
                  top: deviceOrientation == Orientation.portrait
                      ? MediaQuery.of(context).size.height / 15
                      : MediaQuery.of(context).size.width / 15),
              child: FutureBuilder(
                  initialData: 'Loading User',
                  future:
                  userInfo.user == null ? userInfo.loadUser() : null,
                  builder: (context, snap) {
                    if (snap.hasData == true && userInfo.user != null) {
                      return FutureBuilder(
                          initialData: 'Loading Role',
                          future:
                          roleInfo.roles.isEmpty == true ? roleInfo.loadRoles() : null,
                          builder: (context, snap) {
                            if (snap.hasData == true && roleInfo.roles.isEmpty != true) {
                              return new Center(
                                child: _isSubmitting == true
                                    ? CircularProgressIndicator(
                                  valueColor: AlwaysStoppedAnimation(
                                    Color.fromRGBO(0, 79, 255, 1),
                                  ),
                                )
                                    : buildSubmitButton(context, () async {
                                  final form = _formKey.currentState;
                                  if (form.validate()) {
                                    form.save();
                                    print('$_email');
                                    if ((_email.toString() == "client@gmail.com" ||
                                        _email.toString() ==
                                            "company@gmail.com") &&
                                        _password.toString() == "pass") {
                                      setState(() => _isSubmitting = true);
                                      Future.delayed(Duration(seconds: 1), () {
                                        if (_email.toString() == "client@gmail.com") {
                                          userInfo.user.setRole = roleInfo.roles[2];
                                        }
                                        if (_email.toString() ==
                                            "company@gmail.com" ) {
                                          userInfo.user.setRole = roleInfo.roles[1];
                                        }
                                        setState(() => _isSubmitting = false);
                                        _showSuccessSnack();
                                        print(userInfo.user.getRole.getName);
                                        Future.delayed(Duration(seconds: 1), () {
                                          _redirectUser();
                                        });
                                      });

                                      /*var code =  await userInfo.userLogin(_email, _password);
                          if(code == 200){
                            setState(() => _isSubmitting = false);
                            _showSuccessSnack();
                            Future.delayed(Duration(seconds: 1, milliseconds: 50), () {
                              _redirectUser();
                            });
                          }

                      */
                                    }
                                  } else {
                                    setState(() => _isSubmitting = false);
                                    _showErrorSnack('Login Error');
                                  }
                                },
                                    Color.fromRGBO(0, 79, 255, 1),
                                    Color.fromRGBO(0, 79, 255, 1),
                                    Color.fromRGBO(0, 79, 255, 1),
                                    'LOGIN'),
                              );
                            } else {
                              return new Container();
                            }
                          });
                    } else {
                      return new Container();
                    }
                  }),
            ),
          ],
        ),
      ),
    );
  }

**Comment by TahaTesser** [comment]
Hi @abcnow 
Are you still experiencing this issue with latest `stable`?
if yes, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample **without using third party packages**
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
