### ISSUE TITLE
Unit-test GpuThreadMerger.LeaseExtension may hang

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49064]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=44238. Test temporarily disabled.

cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Re-enabling the test is already being traced [here](https://github.com/flutter/flutter/issues/49007). There is nothing more to do to unblock Fuchsia.
