### ISSUE TITLE
Google Maps Flutter does not respond click when inside a Column

### ISSUE THREAD

**Issue by igordiniz445** [flutter/flutter#49060]
When I set a few widgets inside a Column, and the last one is a map with a fixed size, making the screen scrollabe, the map dosen't respond my clicks moving the map to any side. It's like I'm trying to scroll the screen, and the touch never reach the map. Is there any way to fix this ?

![image](https://user-images.githubusercontent.com/33721072/72624706-29bcc900-3926-11ea-8e13-7385a4ceec31.png)

![image](https://user-images.githubusercontent.com/33721072/72624766-478a2e00-3926-11ea-9a30-4a9a9ac6a89d.png)

**Comment by igordiniz445** [comment]
PS.: I'm using google_maps_flutter 0.5.21+15

**Comment by VladyslavBondarenko** [comment]
@igordiniz445 
Does [this solution](https://stackoverflow.com/questions/54280541/google-map-in-flutter-not-responding-to-touch-events) help to you?

**Comment by igordiniz445** [comment]
> @igordiniz445
> Does [this solution](https://stackoverflow.com/questions/54280541/google-map-in-flutter-not-responding-to-touch-events) help to you?

Totally, didn't find that topic ! Thank you so much !
