### ISSUE TITLE
Remove `WidgetTester.pumpWidgetLegacy()`

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#49077]
The implementation of `WidgetTester.pumpWidget` was changed in https://github.com/flutter/flutter/pull/48922 and the old implementation was moved to `WidgetTester.pumpWidgetLegacy`.

There are a few tests in `packages/flutter/test/material/text_field_test.dart` that are still using `pumpWidgetLegacy` because they fail with `pumpWidget`. We need to investigate the failures and move them to `pumpWidget`.

**Comment by pedromassangocode** [comment]
I didn't found any reference of `pumpWidgetLegacy` on the file mentioned. Is this still a valid issue?

https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/text_field_test.dart

**Comment by markusaksli-nc** [comment]
Closing since there doesn't seem to be anything left in the codebase that uses `pumpWidgetLegacy`
