### ISSUE TITLE
Consider removing FlutterAppDelegate

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4907]
Right now FlutterAppDelegate is only used by examples/benchmarks, and potentially some older clients. We generate a boilerplate iOS AppDelegate when running flutter create so it's easier for users to add SDKs to their project.

Having an empty delegate helper class does simplify the examples a bit, but at the cost of having the project structure of examples not match flutter create. We may want to remove this class and just put the empty app delegate into the examples.

**Comment by Hixie** [comment]
Is this done now? I heard rumours about it being done.

**Comment by eseidelGoogle** [comment]
@cbracken deprecated it and plans to remove it in a week iirc.  There is a bug on it.

**Comment by cbracken** [comment]
Deletion bug is #7683.
