### ISSUE TITLE
[in_app_purchase] Android: purchaseDetails.pendingCompletePurchase is always false

### ISSUE THREAD

**Issue by loomp** [flutter/flutter#49083]
## Steps to Reproduce

Affected platform: Android

Accordingly to the changelog of 0.30.0 `purchaseDetails.pendingCompletePurchase` shall return true if purchase state is `purchased` and purchase `isAcknowledged` is `false`.

However, `purchaseDetails.pendingCompletePurchase` is always `false`, even for purchases which  "isAcknowledged" is `false`.

This leads to a major issue when relying on `pendingCompletePurchase` purchases are not correctly recognized and more likely `_connection.completePurchase(purchaseDetails)` is not executed.

**Expected results:**

 `purchaseDetails.pendingCompletePurchase` is `true` when `isAcknowledged` is `false`

**Actual results:**

 `purchaseDetails.pendingCompletePurchase` is `false`

**Comment by d0bry** [comment]
Yes, using the following logic leads to purchases being refunded after 3 days:

```
if (purchaseDetails.pendingCompletePurchase)
    InAppPurchaseConnection.instance.completePurchase(purchaseDetails);
```

Note that this is suggested in in_app_purchase examples.

Fortunately, I've noticed the first refund :)
The workaround is to skip the condition (GooglePlayConnection.completePurchase checks if the purchase isAcknowledged anyway).

I can see there has been some related discussion in flutter/plugins/pull/2287.

**Comment by d0bry** [comment]
Looked into it a bit more and apparently something is missing in `PurchaseDetails.fromPurchase`:
- `_pendingCompletePurchase` is not set
- `status` setter would make it always true for `PurchaseStatus.purchased`, but is not called (`_status` is set directly)
- `isAcknowledged` is not taken into account

**Comment by kinex** [comment]
I think there is same issue with iOS (`PurchaseDetails.fromSKTransaction` sets `_status` and not `status`).

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/2504 is merged. The issue should be fixed. I'm closing the issue

**Comment by kazyamof** [comment]
> 
> 
> I think there is same issue with iOS (`PurchaseDetails.fromSKTransaction` sets `_status` and not `status`). My workaround with minimal code changes:
> 
> ```dart
> purchaseDetails.status = purchaseDetails.status; // <= workaround to #49083
> if (purchaseDetails.pendingCompletePurchase) {
>   await _connection.completePurchase(purchaseDetails);
> }
> ```
> 
> ```
> 
> ```

In my case, even when I do call completePurchase, purchaseDetails.pendingCompletePurchase continues to be true.
