### ISSUE TITLE
how to fix E/flutter (15862): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element when push data to firebase in flutter?

### ISSUE THREAD

**Issue by AbdallahR99** [flutter/flutter#49089]
i trying to send data to firebase i did every thing 
this my code

my code

the modal
```
import 'package:firebase_database/firebase_database.dart';

class Student {
  String _id;
  String _name;
  String _age;
  String _city;
  String _department;
  String _description;
  Student(this._id, this._name, this._age, this._city, this._department, this._description);

  Student.map(dynamic obj) {
    this._id = obj['id'];
    this._name = obj['name'];
    this._age = obj['age'];
    this._city = obj['city'];
    this._department = obj['department'];
    this._description = obj['_description'];
  }
  String get id => _id;
  String get name => _name;
  String get age => _age;
  String get city => _city;
  String get department => _department;
  String get description => _description;

  Student.fromSnapShot(DataSnapshot snapshot){
    _id = snapshot.value['id'];
    _name = snapshot.value['name'];
    _age = snapshot.value['age'];
    _city = snapshot.value['city'];
    _department = snapshot.value['department'];
    _description = snapshot.value['_description'];
  }
}
```
and

```
final studentRef = FirebaseDatabase.instance.reference().child('student');
....
class ListViewStudentState extends State<ListViewStudent> {
List<Student> _students;
  StreamSubscription<Event> _onStudentAddedSub;
}
 StreamSubscription<Event> _onStudentChangedSub;
  @override
  void initState() {
    _students = List();
    _onStudentAddedSub = studentRef.onChildAdded.listen(_onStudentAdded);
    _onStudentChangedSub = studentRef.onChildChanged.listen(_onStudentChanged);

    super.initState();
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    _onStudentAddedSub.cancel();
    _onStudentChangedSub.cancel();
  }

...
void _onStudentAdded(Event event) {
    setState(() {
      _students.add(Student.fromSnapShot(event.snapshot));
    });
  }
 void createNewStudent(BuildContext context) async{
    await Navigator.push(context, MaterialPageRoute(builder: (context)=> StudentScreen(Student('', '', '', '', '', ''))));

  }
....
}
```
and the StudentScreen widget code:
```
class StudentScreen extends StatefulWidget {
  final Student student;
  StudentScreen(this.student);

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return StudenScreenState();
  }

}

class StudenScreenState extends State<StudentScreen> {
  TextEditingController _nameController;
  TextEditingController _ageController;
  TextEditingController _cityController;
  TextEditingController _deptController;
  TextEditingController _noteController;

  @override
  void initState() {
    _nameController = TextEditingController(text: widget.student.name);
    _ageController = TextEditingController(text: widget.student.age);
    _cityController = TextEditingController(text: widget.student.city);
    _deptController = TextEditingController(text: widget.student.department);
    _noteController = TextEditingController(text: widget.student.description);
    super.initState();
  }
....
FlatButton(
onPressed:(){
 if(widget.student.id != null){
 studentRef.child(widget.student.id).set({
 'name': _nameController.text,
 'age': _ageController.text,
 'city': _cityController.text,
 'department': _deptController.text,
 '_description': _noteController.text,

 }).then((_){
 Navigator.pop(context);
  });
}else {
 studentRef.push().set({
 'name': _nameController.text,
 'age': _ageController.text,
 'city': _cityController.text,
 'department': _deptController.text,
 '_description': _noteController.text,
 }).then((_){
  Navigator.pop(context);
 });
 }
},
 child: (widget.student.id != null)? Text('Update'): Text('Add'),
...
}
```
it's gives me this error when try to push the data to firebase
> E/flutter (15862): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element
E/flutter (15862): #0      ListMixin.singleWhere (dart:collection/list.dart:185:5)
E/flutter (15862): #1      ListViewStudentState._onStudentChanged (package:flutter_app/ui/listview_student.dart:82:37)

It's just app for test and learning about student 
there the StudentList widget for show list of the student and StudentScreen for Add or Edit student
so it must doing push if i pressed on this Flatbutton but it's gives the error above when i do it,
i don't know what i must to do
i searched for long time about the problem and i didn't found anything

and it's gives this error too when run the app

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
E/flutter (15862): #0      new Student.fromSnapShot (package:flutter_app/_modal/student.dart:28:25)
E/flutter (15862): #1      ListViewStudentState._onStudentAdded.<anonymous closure> (package:flutter_app/ui/listview_student.dart:78:29)
E/flutter (15862): #2      State.setState (package:flutter/src/widgets/framework.dart:1148:30)
E/flutter (15862): #3      ListViewStudentState._onStudentAdded (package:flutter_app/ui/listview_student.dart:77:5)

can help please!

**Comment by VladyslavBondarenko** [comment]
Hi @AbdallahR99 
There is this exception in the last your log `type 'String' is not a subtype of type 'int' of 'index'`.
It may that here `'age': _ageController.text` you cannot set age with String.
Does it help if you replace it with `'age': int.parse(_ageController.text)`?
Or pay attention to the mentioned exception where it could be thrown (string numbers are useless for me without complete code).
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Shree-hari** [comment]
I am getting same kind of error but with some more errors added

> E/flutter (15292): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'int' is not a subtype of type 'double'
> E/flutter (15292): #0      Products.fetchAndSetProducts (package:shoppersstop/providers/products.dart:89:7)
> E/flutter (15292): <asynchronous suspension>
> E/flutter (15292): #1      _ProductsOverviewScreenState.didChangeDependencies (package:shoppersstop/screens/products_overview_screen.dart:41:38)
> E/flutter (15292): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4665:12)
> E/flutter (15292): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
> E/flutter (15292): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
> E/flutter (15292): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
> E/flutter (15292): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
> E/flutter (15292): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
> E/flutter (15292): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
> E/flutter (15292): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
> E/flutter (15292): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
> E/flutter (15292): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
> E/flutter (15292): #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
> E/flutter (15292): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
> E/flutter (15292): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
> E/flutter (15292): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
> E/flutter (15292): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
> E/flutter (15292): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
> E/flutter (15292): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
> E/flutter (15292): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
> E/flutter (15292): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
> E/flutter (15292): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
> E/flutter (15292): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
> E/flutter (15292): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
> E/flutter (15292): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
> E/flutter (15292): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> E/flutter (15292): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> E/flutter (15292): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
> E/flutter (15292): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
> E/flutter (15292): #45     Compon
> 
> W/Gralloc3(15292): mapper 3.x is not supported
