### ISSUE TITLE
Flutter development workflow: conventional commits

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#49091]
The case is quite simple: https://www.conventionalcommits.org/en/v1.0.0/

- There are some public GitHub repositories (like [ESLint](https://github.com/eslint/eslint/commits/master)) using conventional commits workflow, personally I like it too. 
- I see many people using `feat`, `chore`, `bug` prefixes for their commit messages on GitHub.
- There are some tools which allow to validate commit messages against conventional commits standard and tools to generate change log.

What do you think about following this formal specification for `git` commit messages for Flutter repository?

**Comment by dnfield** [comment]
I'm not quite sure how we could enforce this.  And without a lint for it I doubt people would follow it with any consistency.

We also don't use semver, but do try to track breaking changes in a different way.

**Comment by roman-petrov** [comment]
Actually, there is some [Tooling for Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#tooling-for-conventional-commits) and I think some tools can be integrated with Flutter repository to enforce conventional commits.

This is just a my proposal to improve Flutter workflow. This proposal is not a blocker in any matter so please decide if you find conventional commits useful and like to use for Flutter workflow or just close this issue.

**Comment by zigang93** [comment]
Really need this to enforce.. can't find any conventional commit setup like husky + commitlint + standard version at node.js
with those conventional commit, I also able to manage my change-log file

**Comment by Hixie** [comment]
I'm going to close this issue. If someone on the team wants to argue for this process change, we should start from a design doc and discuss it in the Discord.
