### ISSUE TITLE
Drawer widget bug!?

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#4910]
I use FlutterView in my app, and it has a drawer widget. I use the method:
 public void onBackPressed() {
        if(flutterView != null) {
            flutterView.popRoute();
        }
   }
When I touch 'back' button, the drawer close, but it cannot  open again.

**Comment by abarth** [comment]
It's correct that the drawer closes when the back button is pressed.  Why you say "it cannot open again", can you explain a bit more about what you mean?  What sequence of things do you do and what do you observe?

**Comment by tain335** [comment]
"It's correct that the drawer closes when the back button is pressed", yes it does. But after it closed, I pressed the left-top icon(and right slide gesture not work too) the drawer cannot open.

**Comment by tain335** [comment]
I think it should add a "onBackPressed" callback(like android), it could be more easy to controll the behaviour(not just pop a route).Because many android app, when touch "back" button, just make a toast tips: "touch again you will exist the app".

**Comment by Hixie** [comment]
Do you get any exceptions in the logs if you do this in debug mode?

**Comment by tain335** [comment]
no exceptions in the logs
