### ISSUE TITLE
Resolve files of :classpath in flutter 1.12.13+hotfix.5 with gradle 3.5.0 issue

### ISSUE THREAD

**Issue by abdulmuaz97** [flutter/flutter#49113]
Hey everyone, I'm seriously having a very bad issue this time with the new **Flutter** update.
the thing is have installed:

**1- Android Studio 3.5.3 (latest)
2- Flutter 1.12.13+hotfix.5 (latest)**

the Gradle I have is **gradle-5.6.2-all**

and created new Flutter project
in my **build.gradle** the code is:

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

```

and all I get is keep downloading these -_-

```
> root project > Resolve files of :classpath > protobuf-java-3.4.0.jar > 302 KB/1.32 MB downloaded                            esolve files of :classpath > builder
> root project > Resolve files of :classpath > bundletool-0.9.0.jar > 1.26 MB/5.01 MB downloaded  
> root project > Resolve files of :classpath > protos-26.5.0.jar > 708 KB/3.27 MB downloaded      
> root project > Resolve files of :classpath > builder-3.5.0.jar > 797 KB/7.80 MB downloaded
```

I've already tried everything... any solutions??

**Comment by iapicca** [comment]
Hi @abdulmuaz97 
when does this  download take place?
Can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
