### ISSUE TITLE
Retrieve Document content from Firebase in Flutter

### ISSUE THREAD

**Issue by leaf-ridesharing** [flutter/flutter#49112]
I'm trying to retrieve user data from a Firebase Collection. 

This is what it looks like:
[![Firebase][1]][1]

  [1]: https://i.stack.imgur.com/ZQVza.png

This is the method I wrote to get the data:

   ``` 
  static String getUserData(creatorId, keyword) {
    var documentName = Firestore.instance
        .collection('users')
        .document(creatorId)
        .get()
        .then((DocumentSnapshot) {
      String data = (DocumentSnapshot.data['$keyword'].toString());
      return data;
    });
  }

```

The method only returns null. If I print the String in the Method it works. How can I return the String?

Help would be greatly appreciated. 

Cheers Paul

**Comment by dnfield** [comment]
This would be a better question for a site like StackOverflow -this tracker is for bugs and feature requests in Flutter.
