### ISSUE TITLE
this post in stackoverflow can read it and get solution

### ISSUE THREAD

**Issue by Ayoubdesigner101** [flutter/flutter#49111]
https://stackoverflow.com/questions/59801344/read-or-retrieve-list-of-data-from-subcollection-in-firebase-using-flutter

I using firebase to save my data and use flutter (dart) to access this data Now. I have collection have the name (Customer_payment_details) I put random unique ID like this (tZ9d9cYeUvXKm1easHtr) and in this ID I have Sub Collection (Payment_info) in this subcollection have a unique ID (....etc) in this id have many values I wont to read this data as List

**Comment by iapicca** [comment]
Hi @Ayoubdesigner101 
This platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources and asking questions like this.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
