### ISSUE TITLE
[web]: Generate favicon for web builds

### ISSUE THREAD

**Issue by budius** [flutter/flutter#49114]
We builds are missing favicon

Currently the way to get a flutter web page to show favicon is manually.
- open some online favicon generator
- upload the same icon from the project
- download the favicon
- add the meta to the index.html header

As part of a 'flutter build web' it should be automatically exported from the app icon

**Comment by jonahwilliams** [comment]
There are many possible app icons that the favicon could be generated from. We could instead update the template to include a default favicon so it is more obvious that it is needed/where to put it?

**Comment by budius** [comment]
@jonahwilliams do you mean similar to how is done on the `ios` and `android` folders in the project?
- android/app/src/main/res/mipmap-xxxx
- ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-xxxxx
- web/favicon/icons-xxxx

That sounds logical to me =)  !

(although it also seems like there should be a tool (it could be 3rd party-tool) to generate ALL of those based off 1 high quality icon, but that is talk for a different project)

**Comment by jonahwilliams** [comment]
@budius yes exactly. I don't think it would be worth it to create a generic favicon generator specifically for flutter, since many others already exist.

**Comment by emmett-deen** [comment]
@jonahwilliams this might be a nice addition to the flutter_launcher_icons package though
