### ISSUE TITLE
Spaces not registering in input

### ISSUE THREAD

**Issue by amarsten** [flutter/flutter#4911]
## Steps to Reproduce

Try typing a space into an input field. Was able to reproduce in flutter_gallery as well as my own code.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/amarsten/Documents/workspace/deeplocal/visitor/flutter
    • Framework revision 9c0c0225a6 (3 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/amarsten/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

## Logs and Crash Reports

No crash or logs

**Comment by eseidelGoogle** [comment]
Thanks!  CC @mpcomplete

**Comment by sethladd** [comment]
Confirmed on my iOS. A double-tap of the spacebar will insert a wide space. A single tap does not insert a space. However, if I type a character immediately after a space, I see the space appear and then my characters.

**Comment by mpcomplete** [comment]
This is an engine bug. The space is there, but the cursor is positioned before it. Here is the code that calculates the cursor offset, from TextPainter:

  Offset _getOffsetFromUpstream(int offset, Rect caretPrototype) {
    List<ui.TextBox> boxes = _paragraph.getBoxesForRange(offset - 1, offset);
    if (boxes.isEmpty)
      return null;
    ui.TextBox box = boxes[0];
    double caretEnd = box.end;
    print('upstream boxes ($offset): $caretEnd from $boxes'); // I added this
    double dx = box.direction == TextDirection.rtl ? caretEnd : caretEnd - caretPrototype.width;
    return new Offset(dx, 0.0);
  }

Output after typing 3 characters:
I/flutter : upstream boxes (3): 26.0 from [TextBox.fromLTRBD(18.0, 0.0, 26.0, 19.0, TextDirection.ltr)]

Output after typing a space after that:
I/flutter : upstream boxes (4): 26.0 from [TextBox.fromLTRBD(26.0, 0.0, 26.0, 19.0, TextDirection.ltr), TextBox.fromLTRBD(26.0, 0.0, 31.0, 19.0, TextDirection.ltr)]

The first box is empty, and looks wrong. I'll have to dig deeper.
