### ISSUE TITLE
flutter release apk  : NoSuchMethodError when configuring getDartEntrypointFunctionName

### ISSUE THREAD

**Issue by heshiqi** [flutter/flutter#49124]
I am use the flutter sdk: 1.12.13+hotfix.5  

I override the "getDartEntrypointFunctionName" method and retrun "attention",but it doesn't work in the release apk

    import android.os.Bundle;
    import io.flutter.embedding.android.FlutterActivity;
    public class BaseFlutterActivity extends FlutterActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
        }

        @Override
        public String getDartEntrypointFunctionName() {
            return "attention";
        }
    }

main.dart  

    import 'dart:io';
    import 'package:flutter/material.dart';

    void attention() => runApp(AttentionPage());

**Comment by jason-simmons** [comment]
You'll need to apply a `@pragma('vm:entry-point')` annotation to the `attention` function.  This will ensure that it can be invoked as an entry point in profile or release mode.

See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md

**Comment by zanderso** [comment]
@heshiqi Did @jason-simmons' suggestion help?

**Comment by jonahwilliams** [comment]
Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.

**Comment by heshiqi** [comment]
> Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.

Sorry, I haven't logged in for a long time. In your way, the problem has been solved. Thank you

**Comment by heshiqi** [comment]
> You'll need to apply a `@pragma('vm:entry-point')` annotation to the `attention` function. This will ensure that it can be invoked as an entry point in profile or release mode.
> 
> See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md

In your way, the problem has been solved。

**Comment by heshiqi** [comment]
> You'll need to apply a `@pragma('vm:entry-point')` annotation to the `attention` function. This will ensure that it can be invoked as an entry point in profile or release mode.
> 
> See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md



> Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.

Sorry, I haven't logged in for a long time. In your way, the problem has been solved. Thank you.
