### ISSUE TITLE
Flutter : Several variant outputs are configured to use the same file name

### ISSUE THREAD

**Issue by vivekebiit** [flutter/flutter#49121]
I am just trying to run the first app and this is what happens:

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Several variant outputs are configured to use the same file name "resources-debug.ap_", filters : MAIN:MAIN

**Comment by vivekebiit** [comment]
Got resolved using `flutter clean`

**Comment by jonahwilliams** [comment]
Sounds like this issue was resolved. Please file a new bug if that is not the case

**Comment by hiranthaR** [comment]
worked

**Comment by bene-we** [comment]
I encountered the same issue on my first application, is `flutter clean` initially needed and can be added to the [docs](https://flutter.dev/docs/get-started/test-drive) or is it a bug?

**Comment by buka4rill** [comment]
How do I solve this issue with React Native please??
