### ISSUE TITLE
 Error: 'ImageFilterEngineLayer' isn't a type.

### ISSUE THREAD

**Issue by ghozimahdi** [flutter/flutter#49120]
**I get this error when the flutter is increased**

`Compiler message:
/C:/Program%20Files/flutter/packages/flutter/lib/src/rendering/layer.dart:1580:36: Error: 'ImageFilterEngineLayer' isn't a type.
      oldLayer: _engineLayer as ui.ImageFilterEngineLayer,
                                   ^^^^^^^^^^^^^^^^^^^^^^
/C:/Program%20Files/flutter/packages/flutter/lib/src/rendering/layer.dart:1578:27: Error: The method 'pushImageFilter' isn't defined for the class 'SceneBuilder'.
 - 'SceneBuilder' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'pushImageFilter'.
    engineLayer = builder.pushImageFilter(
                          ^^^^^^^^^^^^^^^
`

**Comment by dnfield** [comment]
This can happen if your local engine artifacts are out of sync - can you try removing your `$FLUTTER_ROOT/bin/cache` and trying again?

**Comment by P30000** [comment]
same...here, this flutter is a paint in a** I am scared to update/upgrade to avoid any error
