### ISSUE TITLE
Be able to chain ParentDataWidgets which refer to the same parent widget.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4912]
I'd expect to be able to do this but it's currently not supported (throws an exception when you do it).

**Comment by Hixie** [comment]
Specifically, this is asking for the ability to have multiple ParentDataWidget objects for a single kind of ParentData. For example, say you had a render object whose children could have their colour and size set independently in the parent data slot, and you wanted to be able to set these fields independently when putting your widgets together.

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
This was implemented in https://github.com/flutter/flutter/pull/48541.
