### ISSUE TITLE
Positive input exceeds the limit of integer 100001100001011110100110

### ISSUE THREAD

**Issue by ghozimahdi** [flutter/flutter#49134]
**how to solve this problem, does flutter not have typedata Long?**

`Positive input exceeds the limit of integer 100001100001011110100110`

**Comment by jonahwilliams** [comment]
It's not clear where this error message is coming from or what version of flutter you're on (flutter doctor -v), please fill out more of the issue template, including reproduction steps.

Dart integers are 64 bit, for larger numbers you probably want to use a BigInt: https://api.dart.dev/stable/2.5.1/dart-core/BigInt-class.html - but this number is not quite that big.

**Comment by ghozimahdi** [comment]
Thank @jonahwilliams that solved my problem

**Comment by 1ka** [comment]
Appreciate this is closed, but I see this with `int.parse('011234567890123456789012345')`
