### ISSUE TITLE
iOS: Can flutter release build be built using xcode or something else than "flutter build ios"?

### ISSUE THREAD

**Issue by matte5031** [flutter/flutter#49139]
Does anyone know if flutter release build can be built using xcode only? Unfortunately my mac is to old for upgrading to the latest xcode 10.2, When trying to build with flutter build ios I get "Found "Xcode 10.1, Build version 10B61". Xcode 10.2 or greater is required to develop for iOS.
Encountered error while building for device." 

I've tried to build the app using xcode and it succeeds, however I get this message from apple after failed upload: 

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Any help or input is highly appreciated, thanks!

**Comment by jonahwilliams** [comment]
> Does anyone know if flutter release build can be built using xcode only

Xcode is required to  build a flutter release build.

If you're receiving that message from apple, it means that you did not actually build a release build for iOS. To do so, ensure that you've run `flutter build ios --release` (release is the default) and then selected the correct archive action in xcode. For full instructions, see https://flutter.dev/docs/deployment/ios

**Comment by matte5031** [comment]
That's the thing though. I can't run flutter build ios --release because it complains the my xcode is to old, and I can't upgrade xcode because my mac is to old so. Do I need to buy a new mac or can I do what flutter build ios --release does in some other way?

**Comment by jonahwilliams** [comment]
There's not really much you can do to work around the minimum versions. Apple themselves are imposing a minimum supported SDK version for new applications, and I believe by March or April of this year you'll need to be on Xcode 11.

As an alternative you might try a service like https://blog.codemagic.io/how-to-develop-and-distribute-ios-apps-without-mac-with-flutter-codemagic/

**Comment by matte5031** [comment]
Okay thanks for the info. Just wanted to know if it was possible or not. I guess I'll just have to go and give apple more money, no complaints ofc :)

**Comment by jonahwilliams** [comment]
If it were possible I would definitely find a way to support it in flutter

**Comment by matte5031** [comment]
Ye I get it, thanks for the help anyways!

**Comment by stickypages** [comment]
@matte5031 I have an old MacBook Pro, I upgraded it by doing a hackintosh, and was able to get Catalina on this laptop to get Xcode, and so far so good. check out DosDude1.com
Might save you some cash.

**Comment by matte5031** [comment]
@stickypages Thanks for reaching out. It's fine I've managed to upgrade to catalina a few months ago aswell so it's all working fine now!

**Comment by stickypages** [comment]
Code on!
