### ISSUE TITLE
Flutter for Web is significantly slower in master than versions of 1.10.16 and before.

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [flutter/flutter#49132]
The same code compiled for the web is much slower on the current master than in version 1.10.16 and below. Sample:

Version 1.10.16: http://beta.mugalon.com/
Master: http://beta.mugalon.com/fluttermaster/

Anything that involves any kind of nontrivial animation will get super slower (< 10 FPS on mid-end mobile devices) and somewhat slow on mid-end desktop machines (20-30FPS) on the current master.

With version 1.10.16 things are fine, beeing above 30 FPS even on mid to low-end mobile devices and close to 60FPS on desktop. 

```console
Flutter 1.14.2-pre.51 • channel master • https://github.com/flutter/flutter.git
Framework • revision ec1044a877 (34 hours ago) • 2020-01-17 19:19:33 -0800
Engine • revision ecc74c966d
Tools • Dart 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)
```

**Comment by iapicca** [comment]
Hi @TobiasHeidingsfeld 
would you be able to provide a minimal sample code to reproduce the issue?
thank you
 
possibly related to https://github.com/flutter/flutter/issues/48911

**Comment by iapicca** [comment]
Hi @TobiasHeidingsfeld 
would you be able to provide a minimal sample code to reproduce the issue?
thank you
 
possibly related to https://github.com/flutter/flutter/issues/48911

**Comment by TobiasHeidingsfeld** [comment]
@iapicca For me it seems more related to animations and images/containers that are moving

In my game for instant the "Lucky Wheel" gets super sluggish in the flutter master on low level devices and slowish on good devices. It Basically is just the following:
`RotationTransition(
              turns: Tween(begin: 0.0, end: 2.0).animate(_controller),
              child: Stack(children: <Widget>[
                Image.asset("assets/test.png"),
                Transform(
                              transform: Matrix4.identity()..rotateZ(2 * pi / 8 * (i)),
                              origin: Offset(s(-85), s(30)),
                              child: Text("some text, maybe with a container around it"))
              ]))`

Once you start the _controller performance should go down. Hope this helps

**Comment by wickedman1976** [comment]
I have noticed that using the webview_plugin on android is considerably slower than on iOS. To such an extent that I have had to use my own plugin to make it work and invoke it on android as its own activity. 

To recreate this try testing a native app on android with a webview against the performance of webviews in a blank flutter project. As per example. 

It seems that when you scroll events are being fired off which make the performance juddery.

**Comment by ferhatb** [comment]
@TobiasHeidingsfeld , several optimizations landed in master. Please retry using v1.14.5-pre.39 or later. Could you also please try wrapping the frequently updated/animated area in RepaintBoundary(child: to see if it helps by smaller updates.

**Comment by TobiasHeidingsfeld** [comment]
@ferhatb Some good improvements! Some areas still feel a little slower than 1.10.16 but some feel a little faster. 

RepaintBoundary seems to help a lot with something like a Spin Wheel, which remains super slow without RepaintBoundary  but work ok with RepaintBoundary  on old devices (ok in 1.10.16 even without RepaintBoundary). 

Should RepaintBoundary also be used on iOS/Android for frequently updated/animated Widgets?
If something is moving inside a Stack should the whole stack be inside the RepaintBoundary oder just the Positioned Widget have a RepaintBoundary father?<

Thank you for the good work

**Comment by TobiasHeidingsfeld** [comment]
@ferhatb Sadly also some elements that are Positioned are displaced again as.This is independent of browser zoom settings, have not tracked done exactly how and why, but the new master remains unusable for web and I have to stay on 1.10.16
