### ISSUE TITLE
Add a confirmation dialog for dumping the rendering tree to console

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#49143]
## Use case
Every other time I do a hot restart for Flutter web it happens that I hit the **T** key by mistake, which is next to the **R** key on the keyboards with US layout.
For complex projects, it take a while to dump everything and keeps me waiting.
I can choose to restart the project, but it takes time to restart it.

This happens just to the **Dump rendering tree to the console.** triggered by **T**, but it can happen with other console-invader commands.

## Proposal
One solution would be to add a confirmation dialog **Y/n** and every key except **Y** to be considered no.

**Comment by marvinqu** [comment]
I think add a confirmation dialog Y/N would add unnecessary complexity. Every Time hot reload, you have to press Y. I preferred to customize the "Dump rendering tree to the console" to another key map.

**Comment by Constans** [comment]
Anything just to avoid this time-consuming operation being triggered by accident.

**Comment by AkshataJ96** [comment]
I would like to work on this! @zanderso

**Comment by Constans** [comment]
Almost 1 year later and still pressed T twice by mistake on a large project. Had to wait several minutes each time. Am I the only one doing this? :)

**Comment by Hixie** [comment]
A confirmation prompt seems suboptimal, but what would be better would be to make it interruptible in some manner (in particular, hitting R should stop the dump and just do a hot restart).
