### ISSUE TITLE
i rebuilded a project that i had mistake,then the error tips never disappear

### ISSUE THREAD

**Issue by gap1994** [flutter/flutter#49147]
it happended when i programmed a mistake, then i wanna rebuilded to fixed it, but failed.
i donnot know where the mistake files in my disk.
please help me.
thank you!
now, i found the solution that i changed my android emulator and it was fixed.
so flutter would saved my mistake in emulator though i had changed my code.

![image](https://user-images.githubusercontent.com/9198081/72692894-56145780-3b69-11ea-82bc-770f4b66c087.png)
![image](https://user-images.githubusercontent.com/9198081/72692923-76dcad00-3b69-11ea-9510-48cb33357101.png)

```
Analyzing flutter_demo...
No issues found! (ran in 4.4s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Hi @gap1994 
Are these logs present when you back to your first emulator?
Does `flutter clean` command help you?
Thank you

**Comment by gap1994** [comment]
thank you very much!i had restarted my first emulator to fix it.
