### ISSUE TITLE
multiple colors for same widget types using ThemeData

### ISSUE THREAD

**Issue by AnuragVadd** [flutter/flutter#49154]
## Use case

I was exploring implementing themes in flutter. After going through multiple tutorials and articles, I still have not found a way to implement different colors for the same widget type (such as Text, FloatingActionButton, etc.). For example = here is a application which uses light and dark theme - 
(I have been trying to recreate the implemented themes in this application but I am getting stuck on how to give multiple colors to same widget types)
dark theme -

![dark theme](https://user-images.githubusercontent.com/38868279/72702227-e8235c80-3b77-11ea-8e2c-73765983ccd0.PNG)

light theme - 

![light theme](https://user-images.githubusercontent.com/38868279/72702235-eeb1d400-3b77-11ea-9f83-a036f9ca59af.PNG)

When the dark theme is toggled, there are certain texts which have white color and there are other texts which have red color. and FABs which which have red and white color backgrounds.

When the light theme is toggled, there are texts with both black and red color present throughout the application (and FABs). 

(Credits to https://uppertodo.com/ for the images)

## Proposal

Implement ways to add multiple colors to same widget types or improve documentation if this feature exists already.

Something similar to https://api.flutter.dev/flutter/material/TextTheme-class.html  but allowing the user to select the widget type and color for that specific widget

something similar to the way TextTheme can be defined -

![style_typography_styles_scale](https://user-images.githubusercontent.com/38868279/72703443-97adfe00-3b7b-11ea-840e-82e7340a594e.png)

**Comment by HansMuller** [comment]
We're just starting a project focused on updating Flutter's theme system: flutter.dev/go/material-theme-system-updates. Part of that is ensuring that all of the material components have a corresponding theme (some components have a theme already). Component themes, like https://api.flutter.dev/flutter/material/ToggleButtonsThemeData-class.html, make it possible to override the visuals of just one component type. I think that's what you're after, albeit for _all_ component types?

**Comment by AnuragVadd** [comment]
> make it possible to override the visuals of just one component type

yes, Essentially, if the user selects a theme choice (dark, light, custom) there should be a choice to change the theme color for the same widget, allowing the developer to choose which of the same widget types across the application should be assigned which theme color
