### ISSUE TITLE
Adding unnecessary permission in AndroidManifest.xml after build  

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#49161]
Hey, I'm building the app and I don't need "WRITE_EXTERNAL_STORAGE" permission and flutter adds it default to build's AndroidManifest.xml file
so I found a solution and try using it
Solution: -
Adding this to AndroidManifest.xml
`    <uses-permission tools:node="remove" android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
`
OR 
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove""/>
`
The error I'm getting: -
* What went wrong:                                                      
Execution failed for task ':app:generateReleaseBuildConfig'.            
`> org.xml.sax.SAXParseException; systemId: file:/Users/apple/Desktop/Project/comp/android/app/src/main/AndroidManifest.xml; lineNumber: 15; columnNumber: 100; The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.
`

**Comment by VladyslavBondarenko** [comment]
Hi @Sarthaktydy 
Does [this ](https://stackoverflow.com/questions/55334431/facing-below-error-toolsnode-associated-with-an-element-type-uses-permission)help you?
Thank you

**Comment by Sarthaktydy** [comment]
> Hi @Sarthaktydy
> Does [this ](https://stackoverflow.com/questions/55334431/facing-below-error-toolsnode-associated-with-an-element-type-uses-permission)help you?
> Thank you

HEY, thanks It worked. I saw that post but IDK how I missed the Solution. Anyway, Thank you alot.
