### ISSUE TITLE
RefreshIndicator used with ListView ( physics: BouncingScrollPhysics () ) not shown (not available) when content is smaller than the viewPort

### ISSUE THREAD

**Issue by omishah** [flutter/flutter#49169]
## Steps to Reproduce

I have a ``RefreshIndicator``,  there's a ``ListView`` inside. When the content of the ``ListView`` doesn't exceed the viewPort, (which means it's not scrollable yet), ``RefreshIndicator`` isn't available (not shown) when used with ``BouncingScrollPhysics()`` physics.

**Run the app and delete items by clicking/tapping on them;  just keep 2-3 texts and try refreshing, it won't work.**

``RefreshIndicator`` works when physics is not specified or with ``AlwaysScrollableScrollPhysics()``. 

> I can't continue with using ``AlwaysScrollableScrollPhysics()`` physics as I want to maintain the same bouncy effect as shown in iOS.

**Source code to reproduce the problem:**

```
import 'package:flutter/material.dart';

void main() => runApp(Demo());

class Demo extends StatefulWidget {
  @override
  _DemoState createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  List<Widget>
      demoText; // to store a list of random text widgets to show the issue

  @override
  void initState() {
    _setTheDemoTextWidgets();
    super.initState();
  }

  void _setTheDemoTextWidgets() {
    // setting a few text widgets to the variable
    demoText = [
      Text('1. We are what we believe we are!'),
      Text('2. Those who have courage and faith shall never perish in misery'),
      Text('3. It takes courage to grow up and become who you really are'),
      Text('4. We are what we believe we are!'),
      Text('5. Those who have courage and faith shall never perish in misery'),
      Text('6. It takes courage to grow up and become who you really are'),
      Text('7. We are what we believe we are!'),
      Text('8. Those who have courage and faith shall never perish in misery'),
      Text('9. It takes courage to grow up and become who you really are'),
      Text('10. We are what we believe we are!'),
      Text('11. Those who have courage and faith shall never perish in misery'),
      Text('12. It takes courage to grow up and become who you really are'),
      Text('13. We are what we believe we are!'),
      Text('14. Those who have courage and faith shall never perish in misery'),
      Text('15. It takes courage to grow up and become who you really are'),
    ];
  }

  Future<void> _refreshData() async {
    setState(() {
      demoText = null; // assign null to the variable on refresh
    });
    _setTheDemoTextWidgets(); // again assign random text widgets to the variable
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Color(0xfff5f5f5),
        appBar: AppBar(
          title: Text('Demo'),
        ),
        body: RefreshIndicator(
          onRefresh: () => _refreshData(),
          child: ListView.builder(
              padding: EdgeInsets.all(20),
              physics:
                  BouncingScrollPhysics(), // if physics set to AlwaysScrollableScrollPhysics() then it works but issue with the BouncingScrollPhysics()
              itemCount: demoText.length,
              itemBuilder: (context, i) => InkWell(
                    onTap: () => setState(() {
                      demoText.removeAt(i); // remove the item on click
                    }),
                    child: Container(
                        margin: EdgeInsets.only(bottom: 15),
                        color: Colors.white,
                        padding: EdgeInsets.all(10),
                        child: demoText[i]),
                  )),
        ));
  }
}
```

**Expected results:**
``RefreshIndicator`` should show when the list is scrolled down from the top ( on refresh).

**Actual results:**
``RefreshIndicator`` isn't shown (not available) at all when the ``ListView`` content is smaller than the viewport (screen height).

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/omishah/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/omishah/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • ASUS X00RD • JAAAGF05F456RHG • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```
</details>

**Comment by VladyslavBondarenko** [comment]
Hi @omishah 
You can try https://github.com/flutter/flutter/issues/15197#issuecomment-463304917

Related to https://github.com/flutter/flutter/issues/15197

**Comment by omishah** [comment]
> Hi @omishah
> You can try [#15197 (comment)](https://github.com/flutter/flutter/issues/15197#issuecomment-463304917)
> 
> Related to #15197

I will use this little hack for now.

**Comment by TahaTesser** [comment]
Hi @omishah 
This is working as expected, in order to trigger overscroll effect, content has to overflow the viewport
Check [BouncingScrollPhysics class](https://api.flutter.dev/flutter/widgets/BouncingScrollPhysics-class.html)

> BouncingScrollPhysics by itself will not create an overscroll effect if the contents of the scroll view do not extend beyond the size of the viewport. To create the overscroll and bounce effect regardless of the length of your scroll view, combine with AlwaysScrollableScrollPhysics.


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by omishah** [comment]
> Hi @omishah 
> 
> This is working as expected, in order to trigger overscroll effect, content has to overflow the viewport
> 
> Check [BouncingScrollPhysics class](https://api.flutter.dev/flutter/widgets/BouncingScrollPhysics-class.html)
> 
> 
> 
> > BouncingScrollPhysics by itself will not create an overscroll effect if the contents of the scroll view do not extend beyond the size of the viewport. To create the overscroll and bounce effect regardless of the length of your scroll view, combine with AlwaysScrollableScrollPhysics.
> 
> 
> 
> 
> 
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> 
> Thank you
> 
> 

The issue wasn't all about overscroll effect, it was about refresh indicator not being shown when content length is less than the screen size.

**Comment by TahaTesser** [comment]
@omishah 
refresh indicator won't show unless you overscroll, which doesn't happen when content s not overflowing viewport when using `BouncingScrollPhysics`

**Comment by mohammadne** [comment]
is there any way to have  `BouncingScrollPhysics` effect for that ?
