### ISSUE TITLE
android ignores flutter flavors(entrypoints)

### ISSUE THREAD

**Issue by mohammadshrahi** [flutter/flutter#49167]
Hello, I'm trying to use flutter flavors and android flavors, and everything works fine when I run the project from VSCODE,but the problem is when I'm trying to make release or run the debug app from android folder, APK ignores flutter entrypoints(flavors), somehow android always looking for lib/main.dart,
the only solution I have now is to change target variable within flutter.gradle for every release. 
specify a target for every flavor inside the app gradle it's will be a good solution for this issue

**Comment by iapicca** [comment]
Hi @mohammadshrahi 
what command are you running?
 (example) `flutter build appbundle --flavor production lib/main_production.dart` ?
thank you

**Comment by mohammadshrahi** [comment]
@ianloic actually I'm generating release from android studio ide, build-> generate signed bundle/apk

**Comment by mohammadshrahi** [comment]
> Hi @mohammadshrahi
> what command are you running?
> (example) `flutter build appbundle --flavor production lib/main_production.dart` ?
> thank you

trying to generate release from this command also not working

> Target android_aot_release_android-x64 failed: Invalid argument(s): Cannot find executable for /Users/macbook/Desktop/sdks/flutter/bin/cache/artifacts/engine/android-x64-release/darwin-x64/gen_snapshot.
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/macbook/Desktop/sdks/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildEnsRelease'.         
> Process 'command '/Users/macbook/Desktop/sdks/flutter/bin/flutter'' finished with non-zero exit value 1

**Comment by jonahwilliams** [comment]
Can you include the output of `flutter doctor -v`?

If you remove the tools cache and redownload - does the issue go away: `rm -rf FLUTTER_ROOT/bin/cache/` and then `flutter precache`

**Comment by mohammadshrahi** [comment]
Hello @jonahwilliams  @iapicca 
after updating flutter, I try it one more time from a terminal using this:
`flutter build appbundle --flavor production lib/main_production.dart `
and it's work fine now , I think you should close this issue
thanks for supporting

**Comment by jonahwilliams** [comment]
Cool
