### ISSUE TITLE
Some pickers are not focusable when using a keyboard

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#49182]
@goderbauer
@gspencergoog
@lorenzOliveto

- CupertinoTimerPicker and CupertinoPicker are not focusable with a keyboard
- Material time picker (https://api.flutter.dev/flutter/material/showTimePicker.html) doesn’t seem to be usable with a keyboard

**Comment by gspencergoog** [comment]
cc @darrenaustin

**Comment by darrenaustin** [comment]
We might want to split this into separate bugs, as there are four different pickers involved here.

The Cupertino pickers will be hard to fix until we get general keyboard support for macOS. I'll let @gspencergoog address this as he has more knowledge about what needs to be done here.

For the Material date picker, the calendar grid is the main thing part that is not keyboard focusable. We can probably just add inkwells for each of the date entries. However, as we have a complete redesign of this picker coming in with the new date range picker, it might be better to just hold off on this until we replace the existing UI.

For the Material time picker it is not clear what we should do for the keyboard navigation here, as the dials don't have an obvious keyboard traversal. I will submit a YAQS design question for this and see if we can get some UI design help here.

**Comment by Hixie** [comment]
@gmoraja Can you please file separate bugs for each picker you would like updated?

**Comment by gmoraja** [comment]
@Hixie I created the following issues:

**Material date picker is not focusable with a keyboard**
https://github.com/flutter/flutter/issues/49809

**Material time picker is not focusable with a keyboard**
https://github.com/flutter/flutter/issues/49810

**Cupertino pickers are not focusable with a keyboard**
https://github.com/flutter/flutter/issues/49811

**Comment by goderbauer** [comment]
I am closing this issue since we now have sub-issues tracking all the work necessary.
