### ISSUE TITLE
google_maps_flutter curved polylines are not working in iOS

### ISSUE THREAD

**Issue by boominadhaprakash** [flutter/flutter#49189]
### Steps to Reproduce:

**Problem:**

I am facing the issue with GoogleMap plugin and the problem is only on iOS devices. I am trying to draw a curved PolyLine, which is working in Android. But not working for iOS devices/simulator

**Replicate:**

Create a polyline as below. In Android the output is curved polyline. In iOS it's straight line.
```
var originLatLng = LatLng(33.1369, -101.4661);
var destinationLatLng = LatLng(-9.4235, 160.0529);
Polyline(
          polylineId: PolylineId(
              'uniqueid'),
          geodesic: true,
          points: [originLatLng, destinationLatLng],
          width: 3,
          color: Theme.of(context).primaryColor,
        )
```

**Request:**

Please let us know if you can replicate this issue.

**Evidence:**

![issue_android](https://user-images.githubusercontent.com/16302912/72784609-444eb500-3c3a-11ea-93c8-36cb1d5a9936.png)

![issue_iPad](https://user-images.githubusercontent.com/16302912/72784661-5e889300-3c3a-11ea-96c3-575dcf287a36.png)

**Comment by kattaliraees** [comment]
@ditman this can be closed now

**Comment by ditman** [comment]
@boominadhaprakash : @kattaliraees added geodesic support to polylines in iOS (`google_maps_flutter: ^0.5.31` [link](https://pub.dev/packages/google_maps_flutter/changelog#0531))! You might want to give this another shot!

I'm closing the issue, but feel free to reopen if needed!
