### ISSUE TITLE
Specify device name in Android Studio run window tabs instead of default "main.dart"

### ISSUE THREAD

**Issue by rodstafford** [flutter/flutter#49180]
This is not a bug but it would very nice if the tabs in the run window would indicate which device they belong to when you have multiple devices connected (multiple tabs).  

## Use case

Currently every tab is labeled "main.dart" (attached screenshot).  You can scroll through each tabbed window to get to the top to figure out which device belongs to which tab but when there are multiple tabs there is confusion and you can unintentionally restart or shutdown the wrong device.

## Proposal

It would be very helpful if the tabs were labeled by default to correspond with the device, or give the user the option of renaming the tabs.  
![Screen Shot Android Studio Run Window](https://user-images.githubusercontent.com/6014335/72746464-2886d880-3b80-11ea-9898-456f74bd6465.png)

**Comment by iapicca** [comment]
Hi @rodstafford  
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Comment by jtmuller5** [comment]
Link to the relevant issue: [https://github.com/flutter/flutter-intellij/issues/4420](https://github.com/flutter/flutter-intellij/issues/4420)
