### ISSUE TITLE
[web]: <underline with Hebrew> 

### ISSUE THREAD

**Issue by danielreuven** [flutter/flutter#49194]
Describe your issue and include the command you're running, flutter_web version, browser version

Channel beta, v1.12.13+hotfix.6 flutter  on Microsoft Windows [Version 10.0.18362.295]

if the letter is 'ע' is outside from underline

**Comment by danielreuven** [comment]
https://dartpad.dev/dbe7445a57e5478c39682168ff22313a

**Comment by VladyslavBondarenko** [comment]
@danielreuven 
Is it what you see?
![image](https://user-images.githubusercontent.com/17024977/72798565-0e1a3100-3c4c-11ea-8609-99bf7fb39965.png)
What is wrong here?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
