### ISSUE TITLE
SliverPadding doesn't update precedingScrollExtent

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#49195]
The constraints passed by `RenderSliverEdgeInsetsPadding` to its child don't have `precedingScrollExtent` updated to include the `beforePadding`.

Silly example that shows the problem, trying to show exactly three boxes on the screen with some padding at the top:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Buzz());
}

class Buzz extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverPadding(
          padding: EdgeInsets.all(32),
          sliver: SliverGrid(
            gridDelegate: BuzzDelegate(),
            delegate: SliverChildBuilderDelegate(
              (context, i) => Container(color: Colors.red, alignment: Alignment.center, child: Placeholder()),
              childCount: 6
            ),
          ),
        ),
      ],
    );
  }
}

class BuzzDelegate extends SliverGridDelegate {
  @override
  SliverGridLayout getLayout(SliverConstraints constraints) {
    final mainAxisStride = (constraints.viewportMainAxisExtent - constraints.precedingScrollExtent) / 3;
    return SliverGridRegularTileLayout(
      mainAxisStride: mainAxisStride,
      childMainAxisExtent: mainAxisStride,
      crossAxisCount: 1,
      childCrossAxisExtent: constraints.crossAxisExtent,
      crossAxisStride: constraints.crossAxisExtent,
      reverseCrossAxis: false,
    );
  }

  @override
  bool shouldRelayout(SliverGridDelegate oldDelegate) => true;
}
```

Result:
![Screenshot 2020-01-23 at 11 11 02](https://user-images.githubusercontent.com/4456832/72975578-59118100-3dd1-11ea-951d-96166f479d0e.png)

Observe that the third box is partially cut of, while I expect it to just fit on the screen.

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.12.13+hotfix.5 at .../dev/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by VladyslavBondarenko** [comment]
Hi @spkersten 
Could you provide a code sample to reproduce the issue?
Thankk you

**Comment by spkersten** [comment]
@VladyslavBondarenko I've added an example to the original post, but you can actually in `RenderSliverEdgeInsetsPadding.performLayout` that it doesn't modify `precedingScrollExtent` with the padding.

**Comment by PK2702** [comment]
> The constraints passed by `RenderSliverEdgeInsetsPadding` to its child don't have `precedingScrollExtent` updated to include the `beforePadding`.
> 
> Silly example that shows the problem, trying to show exactly three boxes on the screen with some padding at the top:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/rendering.dart';
> import 'package:flutter/widgets.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => MaterialApp(home: Buzz());
> }
> 
> class Buzz extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return CustomScrollView(
>       slivers: [
>         SliverPadding(
>           padding: EdgeInsets.all(32),
>           sliver: SliverGrid(
>             gridDelegate: BuzzDelegate(),
>             delegate: SliverChildBuilderDelegate(
>               (context, i) => Container(color: Colors.red, alignment: Alignment.center, child: Placeholder()),
>               childCount: 6
>             ),
>           ),
>         ),
>       ],
>     );
>   }
> }
> 
> class BuzzDelegate extends SliverGridDelegate {
>   @override
>   SliverGridLayout getLayout(SliverConstraints constraints) {
>     final mainAxisStride = (constraints.viewportMainAxisExtent - constraints.precedingScrollExtent) / 3;
>     return SliverGridRegularTileLayout(
>       mainAxisStride: mainAxisStride,
>       childMainAxisExtent: mainAxisStride,
>       crossAxisCount: 1,
>       childCrossAxisExtent: constraints.crossAxisExtent,
>       crossAxisStride: constraints.crossAxisExtent,
>       reverseCrossAxis: false,
>     );
>   }
> 
>   @override
>   bool shouldRelayout(SliverGridDelegate oldDelegate) => true;
> }
> ```
> 
> Result:
> ![Screenshot 2020-01-23 at 11 11 02](https://user-images.githubusercontent.com/4456832/72975578-59118100-3dd1-11ea-951d-96166f479d0e.png)
> 
> Observe that the third box is partially cut of, while I expect it to just fit on the screen.
> 
> ```
> [✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-NL)
>     • Flutter version 1.12.13+hotfix.5 at .../dev/flutter
>     • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> ```

**Comment by Piinks** [comment]
Hey @spkersten, good to 'see' you! #49433 should fix this. Thanks for finding it! :)
