### ISSUE TITLE
Can't build apk after deleting pubspec.lock

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#49204]
I had a git conflict issue with pubspec.lock, so I did the following:

1. Deleted pubspec.lock
2. Deleted .pub-cache
3. Ran `flutter clean`
4. Ran `packages get`

But now I get the following error when running `flutter build apk --release`:

`[   +1 ms] /Users/rudeboy/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.2.0/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperPlugin.java:78: error:
cannot find symbol
[   +3 ms]     onAttachedToEngine(binding.getBinaryMessenger());
[        ]                               ^
[        ]   symbol:   method getBinaryMessenger()
[        ]   location: variable binding of type FlutterPluginBinding
[        ] 1 error`

What would be the best way to repair this problem?

**Comment by iapicca** [comment]
Hi @guit4eva 
can you please provide your `flutter doctor -v` ,
your "current" `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
