### ISSUE TITLE
HeroController._updateQuest calling Hero.of with a null context

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#4920]
Ran the leafy app on Android and pressed the back button.  Saw this exception:

@Hixie 

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The null object does not have a method 'visitChildElements'.
NoSuchMethodError: method not found: 'visitChildElements'
Receiver: null
Arguments: [Closure: (Element) => void]
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart)
#2      Hero.of (package:flutter/src/widgets/heroes.dart)
#3      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart)
#4      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart)
#5      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart)
#6      _beginFrame (file:///ssd2/sky/flutter/bin/cache/pkg/sky_engine/dart_ui/hooks.dart)

════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by HansMuller** [comment]
This code path doesn't exist anymore, see https://github.com/flutter/flutter/pull/8112
