### ISSUE TITLE
[webview_flutter] Load HTML from String

### ISSUE THREAD

**Issue by JasMich** [flutter/flutter#49203]
In my applications I often have the problem that I want to display HTML from a String. This is impossible with 'clean' code: What I do is creating an HTTP-server using dart, returning the String I pass by a URL parameter. This is inefficient and moreover impossible on Web-Platform.

**That's why I propose to support displaying HTML from a String natively using `webview_flutter`.**

## Use case

In many cases, developers may need to display HTML from a String but unfortunately this is currently not possible using `webview_flutter`. Use cases might be:

 * a badly designed API returning "formatted" text as HTML
 * accessing JavaScript rendering features (e.g. LaTeX, MarkDown)
 * display any random HTML occurring in the jungle of your application's code

## Proposal

Integrate something like:
```dart
WebView.fromHTMLString(myHTMLString);
```
This could be done using Android's
```Java
webview.loadDataWithBaseURL("", data, "text/html", "UTF-8", "");
```
, iOS's
```Swift
let webView2 = WKWebView()
webView2.loadHTMLString("<html><body><p>MyHTML</p></body></html>", baseURL: nil)
```
and JavaScript's
```JavaScript
myIframe.src = "data:text/html;charset=utf-8," + escape(html);
```
.

## Appendix

I know, there are 3rd party plugins trying to offer this but they use RegEx to get the HTML tags and replace them with Flutter's native ones. They don't allow CSS or advances tags.

**Comment by Aulig** [comment]
You can use
`controller.loadUrl(Uri.dataFromString(html, mimeType: 'text/html', encoding: utf8).toString());`

with controller being your webviewcontroller.

**Comment by JasMich** [comment]
Thank you so much. I didn't find this anywhere.
Does this work on all platforms? E.g. Web, Desktop or only on iOS and Android.

**Comment by Aulig** [comment]
I'm not sure about that, I just found it on stackoverflow a while ago. It works on android for sure and iOS too i think.

**Comment by JasMich** [comment]
Okay, I will let you know when I got results on Web or Desktop.

**Comment by JasMich** [comment]
As `webview_flutter` does not support the web platform, `controller.loadUrl(Uri.dataFromString("your html", mimeType: 'text/html', encoding: utf8).toString());` won't work. 

But using `HtmlElementView` you can easily create HTML-elements within your Flutter code.

What may cause problems is that you cannot offer an implementation for the web and mobile platforms within one file due to library incompatibility. You can work around this by using conditional imports:
```dart
import 'katex_flutter_stub.dart'
    // ignore: uri_does_not_exist
    if (dart.library.io) 'katex_flutter_mobile.dart'
    // ignore: uri_does_not_exist
    if (dart.library.html) 'katex_flutter_web.dart';
```
You can find a working example in my `katex_flutter` package: https://gitlab.com/testapp-system/katex_flutter or https://pub.dev/packages/katex_flutter .

**Comment by Aulig** [comment]
Happy to hear you got it to work!
