### ISSUE TITLE
Right way to reference all plugins license

### ISSUE THREAD

**Issue by giudon010** [flutter/flutter#49201]
Hello,
I noticed that when I create an APK with Flutter, a file named LICENSE is created under: my.apk\assets\flutter_assets.

So I'm wondering, to properly comply with all the licenses of the plugins used within my App, if you could refer to this file directly, and maybe make it readable directly within the App, or perhaps downloadable.

What do you think about it?

Thank you in advance

**Comment by jonahwilliams** [comment]
The license can be loaded in the app like any other flutter asset. It can also be loaded from the services layer using https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html
