### ISSUE TITLE
PlatformView's callbacks aren't called

### ISSUE THREAD

**Issue by askarsyzdykov** [flutter/flutter#49205]
I created camera_view plugin via `PlatformView`, and when I'm using it in a sample app (in the plugin's module), all callbacks are called by system when app goes to background and goes back.
But when I added my plugin into a target app PlatformView's callbacks aren't called anymore.

I created demo repo https://github.com/askarsyzdykov/flutter_platform_view_bug

## Steps to Reproduce

1. Install an app by link above
2. Grant camera permissions in the app settings (I don't handle it)
3. Restart the app

**Expected results:** 
onFlutterViewAttached, onFlutterViewDetached, dispose are called

**Actual results:** 
onFlutterViewAttached, onFlutterViewDetached, dispose are not called

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel unknown, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-RU)
    • Flutter version 1.13.6 at /Users/askarsyzdykov/Development/flutter
    • Framework revision 659dc8129d (3 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/askarsyzdykov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Mi A1 • 2bb52c379805 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment]
Hi @askarsyzdykov 
Can you please point to code and logs that would  produce`onFlutterViewAttached, onFlutterViewDetached, dispose of are called` and please simplify your code in your project, it is nested inside another package, you can just create one app, add platform code directly into the Android folder 

Can you please provide your `flutter doctor -v` your `flutter run --verbose` 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
