### ISSUE TITLE
GestureDetector doesn't work correctly after rotate

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#49210]
## Steps to Reproduce

1. Add a ```Positioned``` widget inside ```Stack```
2. Inside the ```Positioned``` widget give  ```GestureDetector``` as child & give its child ```transform.rotate``` widget
3. The Gestures doesn't work after rotate

**Expected results:** 

After rotate gesture should work perfectly.

**Actual results:** 

Gesture only works on previous x & y position.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/faiyyazkhatri/StudioProjects/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/faiyyazkhatri/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/faiyyazkhatri/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/faiyyazkhatri/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • RMX1801 • a3a5c450 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
[Code to reproduce](https://dartpad.dev/4339301a9f71d365d5b66afb9216ee97)

**Comment by premingiet** [comment]
Is there any solution available yet for this ?
When i try to rotate the widget and then try to move around, it moves into different direction
Here is dartpad link of the code
https://dartpad.dev/49638ff48eca93d38e035a599721b2b0

**Comment by casualcoder404** [comment]
I'm also facing the same problem.
I tried using InkWell, MaterialButton, GestureDetector but none of them is working.

**Comment by iapicca** [comment]
Hi @Faiyyaz 
I see there's an open [issue](https://github.com/flutter/flutter/issues/27587) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
