### ISSUE TITLE
Need an easy way to find leaking animations in running app (not in test)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4921]
It's easy to end up leaking animations but not easy to catch them.
https://github.com/flutter/flutter/issues/4918#issuecomment-232770246

We have debugAssertNoTransientCallbacks which we use in flutter_test to catch animation leaks, but if you don't happen to have a flutter_test of your widget there isn't a way to catch leaked animations.

@jason-simmons and I just tried collecting to an app with a known leak via Observatory and calling debugAssertNoTransientCallbacks while the isolate was paused and it didn't seem to print anything.  Regardless, we should make this less easy to get wrong or more easy to fix if you do.

**Comment by Hixie** [comment]
Can you post an application demonstrating the problem you want to catch? I don't fully understand what you mean but if you have an example I maybe can come up with something.

**Comment by Hixie** [comment]
@eseidelGoogle I'm going to close this per my last comment but feel free to reopen if you can add additional details. Thanks!
