### ISSUE TITLE
how to add arabic language in TTS or speech to text , not support in flutter ??

### ISSUE THREAD

**Issue by husseinalkoosh** [flutter/flutter#49218]

**Comment by VladyslavBondarenko** [comment]
Hi @husseinalkoosh 
As I unerstand you are using third party plugin [flutter_tts](https://pub.dev/packages/flutter_tts)
I would advice to ask your question in [the plugin's github](https://github.com/dlutton/flutter_tts/issues)
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
