### ISSUE TITLE
Code generation documentation, Github vs flutter.dev

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#49217]
I am a little bit confused about the ideal way to bring in libraries that rely on code generation to Flutter projects. It seems that the docs could use a bit of improvement.

[Code-generation-in-Flutter](https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter) on the Github wiki explains how to setup code gen only by editing pubspec.yaml.

[flutter.dev docs on JSON](https://flutter.dev/docs/development/data-and-backend/json) explains that you use CLI commands to generate code.

Neither of these 2 pages reference each other or speak about each other's guidance on code gen.

`json_serializable` and `built_value` are some of the most used libraries that rely on code gen, so I expect [flutter.dev docs on JSON](https://flutter.dev/docs/development/data-and-backend/json) to be highly trafficed.

Questions I expect devs will have.
* Can I setup `json_serializable` and `built_value` like the Github Wiki says? Or must I follow the flutter.dev docs?
* Is one approach better than than the other?
* Can all code generation libraries be used in both ways?

**Comment by jonahwilliams** [comment]
The flutter.dev documentation is the official source. The flutter wiki contains numerous experimental features (see the heading that one is under), one of which is code gen in flutter.
