### ISSUE TITLE
error is popping up when i change my app to dark mode 

### ISSUE THREAD

**Issue by evolvingkid** [flutter/flutter#49219]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building InputDecorator(decoration: InputDecoration(labelText: "Email", hintMaxLines: "1", alignLabelWithHint: false), isFocused: false, isEmpty: true, dependencies: [_LocalizationsScope-[GlobalKey#01e63], Directionality, _InheritedTheme, MediaQuery], state: _InputDecoratorState#182c9(tickers: tracking 2 tickers)):
'package:flutter/src/services/text_input.dart': Failed assertion: line 745 pos 12: 'attached': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    TextFormField 
lib\screens\siginin_screen.dart:144
When the exception was thrown, this was the stack
#2      TextInputConnection.setStyle 
package:flutter/…/services/text_input.dart:745
#3      EditableTextState.didUpdateWidget 
package:flutter/…/widgets/editable_text.dart:1162
#4      StatefulElement.update 
package:flutter/…/widgets/framework.dart:4396
#5      Element.updateChild 
package:flutter/…/widgets/framework.dart:2977
#6      SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5452
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99527 pixels on the bottom.
The relevant error-causing widget was
    Column 
lib\screens\siginin_screen.dart:107
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/services/text_input.dart': Failed assertion: line 745 pos 12: 'attached': is not true.
The relevant error-causing widget was

**Comment by HansMuller** [comment]
Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem, and we'll look into it.

**Comment by rougerepublic23** [comment]
> Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem, and we'll look into it.

λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for
      detailed instructions.
[√] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by rougerepublic23** [comment]
> Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem, and we'll look into it.
This is the Place the error is poping up
        Form(
                        key: _form,
                        child: SingleChildScrollView(
                          child: Column(
                            children: <Widget>[
                              Container(
                                decoration: myBoxDecoration(),
                                padding: EdgeInsets.all(10),
                                child: TextFormField(
                                    cursorColor: Theme.of(context)
                                        .colorScheme
                                        .secondaryVariant,
                                    decoration: emailnputDecoration(),
                                    keyboardType: TextInputType.emailAddress,
                                    textInputAction: TextInputAction.next,
                                    onFieldSubmitted: (_) {
                                      FocusScope.of(context)
                                          .requestFocus(_passwordFocusNode);
                                    },
                                    onSaved: (val) {
                                      _initValues = {
                                        'email': val,
                                        'password': _initValues['password'],
                                      };
                                    }),
                              ),
                              Container(
                                margin: EdgeInsets.only(
                                  top: 20,
                                ),
                                decoration: myBoxDecoration(),
                                padding: EdgeInsets.all(10),
                                child: TextFormField(
                                    decoration: InputDecoration(
                                        labelText: 'Password',
                                        labelStyle: new TextStyle(
                                            color: Color.fromRGBO(
                                                242, 56, 105, 1))),
                                    obscureText: true,
                                    focusNode: _passwordFocusNode,
                                    onSaved: (val) {
                                      _initValues = {
                                        'email': _initValues['email'],
                                        'password': val,
                                      };
                                    }),
                              ),
                              SizedBox(
                                height: 30,
                              ),
                              if (_isLoading)
                                CircularProgressIndicator(
                                  backgroundColor:
                                      Color.fromRGBO(242, 56, 105, 1),
                                )
                              else
                                FlatButton(
                                  color: Color.fromRGBO(242, 56, 105, 1),
                                  child: Container(
                                    margin: EdgeInsets.symmetric(vertical: 20),
                                    width: double.infinity,
                                    child: Text(
                                      'Sign In',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        fontSize: 18,
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  onPressed: _saveForm,
                                )
                            ],
                          ),
                        ),
                      ),

**Comment by VladyslavBondarenko** [comment]
Hi @evolvingkid 
does the issue persist? could you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by evolvingkid** [comment]
No, In flutter 1.17.3 update that issue is resolved
