### ISSUE TITLE
Implement displayRefreshRate service extension for MacOS

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#49222]
This service extension should return the target refresh rate for the device (e.g. 60, 90, 120). Calling this service extension for MacOS currently returns 0.0, and we are defaulting to 60 FPS for the parts of our tools that use this data (IntelliJ performance window, DevTools timeline). 

An implementation for this would be similar to flutter/engine@4c4c999 or flutter/engine@2bd75ae

**Comment by stuartmorgan** [comment]
> An implementation for this would be similar to flutter/engine@4c4c999 or flutter/engine@2bd75ae

Those implementations use engine internals directly, which the desktop embeddings don't do. There would need to be a way to get this information that's exposed via the embedder API if there isn't one already.
