### ISSUE TITLE
`flutter precache -a` downloads a duplicate dart-sdk (at least on Darwin)

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49226]
Steps:

- blow away `bin/cache`
- run any flutter command other than `flutter precache -a`, e.g. `flutter doctor`
- `find bin/cache -name dart` produces one result: `bin/cache/dart-sdk/bin/dart`
- run `flutter precache -a`

```
find bin/cache -name dart
bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart
bin/cache/artifacts/engine/linux-x64/dart-sdk/bin/dart
bin/cache/dart-sdk/bin/dart
```

I suspect we don't want those extra dart-sdk packages

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
See: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/precache.dart#L17

It does specifically call out that it is for all _host_ platforms

**Comment by dnfield** [comment]
Ahhhhh.  So this is intended behavior then.  Ok.  My assumption was that it just grabbed all artifacts that would otherwise get lazily added instead of waiting for the user to run a command that needed them.

I guess we can close this in that case.
