### ISSUE TITLE
LUCI recipe changes need presubmits or checklists.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#49236]
Currently, all LUCI recipe changes are speculative. Breaking changes to the recipe are only discovered after the updated recipe is used by all bots (usually on a not entirely obvious commit). After the breaking change has been identified (hopefully by the author who is vigilant for such breaking changes), the tree is stuck in a red state till another patch is manually pushed. [While there is a playbook for testing recipe changes on specific bots](https://docs.google.com/document/d/1tT8C5z1-e1Z7U3WJO2Mk7Afyn7gUqFLAIy-jZkHAewo/edit#heading=h.r3w1q2jfozg6), there is none for testing the same across all bots.

[Tree closures due to this issue](https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/3568) are hard to discover, take a long time to patch (manually) and have severe knock on effect for multiple teams. There ought to be a presubmit or playbook for testing recipe changes before they are committed.

**Comment by chinmaygarde** [comment]
cc @dnfield, @digiter for thoughts.

**Comment by chinmaygarde** [comment]
cc @godofredoc

**Comment by dnfield** [comment]
We should be able to test across all bots today.

My recent encounter with this was because I failed to test uploads,or in any way the files o wanted would exist for uploading.

**Comment by godofredoc** [comment]
Fuchsia has a recipe tests module which detects changes in recipes or modules and then triggers all the relevant builders in presubmit. We should be able to leverage that functionality but a prerequisite will be to move our recipes to its own repo.

**Comment by chinmaygarde** [comment]
> We should be able to test across all bots today.

Cool. Can we amend the go/flutter-luci document to detail this and maybe add a one click script that does this locally.

> My recent encounter with this was because I failed to test uploads

We could have a staging bucket for testing (opted into by the testing script on the host) this whose contents we clear on a regular basis.

> Fuchsia has a recipe tests module which detects changes in recipes or modules and then triggers all the relevant builders in presubmit

Definitely a worthwhile improvement. Do they have a presubmit like workflow for making sure the recipe changes are sound?

**Comment by godofredoc** [comment]
This is complete, will start removing the experimental percentage.
