### ISSUE TITLE
Engine does not switch to devfs for loading fonts during hot reload/restart

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#49230]
Currently when hot reloading, applications can correctly load new assets in the application. Fonts are also copied to the devfs by the same logic, but adding a font does not allow it to be used until the entire application is restarted. 

When running an application and adding a font, neither hot reloading nor hot restarting allows it to be used.

When running application and removing it a font, it can still be used after hot reload or hot restart.

My guess is that the fonts are being read only from the original application bundle and not the updated devfs directory.

**Comment by jonahwilliams** [comment]
FYI @GaryQian in case you know how this works...

**Comment by InMatrix** [comment]
Just to add some context here, in our Q4 user survey, participants reported that hot reload not reflecting font and other asset changes was not the behavior they would expect.

**Comment by InMatrix** [comment]
This issue has just been reported by @jorgecoca that students in the the App Brewery training on Flutter had "confusion around why changing images on the assets folder does not translate to changes when doing Hot Reload on the app."

**Comment by jonahwilliams** [comment]
We support assets during hot reload, just not fonts. If users are not seeing assets update that is something else

**Comment by InMatrix** [comment]
@jorgecoca Could you point us to an example in the training that involves changing images?

**Comment by InMatrix** [comment]
I confirmed that changing images worked with hot reload for me. It's likely to be some other issue getting conflated with hot reload.

**Comment by fzyzcjy** [comment]
👀 after 2 years...

**Comment by jonahwilliams** [comment]
@fzyzcjy its not really respectful to make comments like these on old issues, aside from the fact that everyone subscribed to this just got a notification from you.

**Comment by fzyzcjy** [comment]
@jonahwilliams Sorry for that. I just wanted to know the current status, since this feature is critical when developing our custom icon fonts and want to see how changed icon font affects UI without a full recompile and restart

**Comment by jonahwilliams** [comment]
ask and you shall receive
