### ISSUE TITLE
Canvas.drawShadow Transformed Incorrectly

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#49233]
![Screen capture](https://s5.gifyu.com/images/issue0631c59df4728d8c.gif)

As you can see, the shadow as the top is weirdly flipped while the canvas is *transformed*. You can see how it is supposed to look like [here](https://creativecreatorormaybenot.github.io/clock/#/). I do not draw the shadow at all while transforming as a workaround - the idea is that the weird lines are gone.

## Steps to Reproduce

The canvas is transformed [here](https://github.com/creativecreatorormaybenot/clock/blob/cd561c82fea2e473a4b30d231531917039b298cc/canvas_clock/lib/composition/composited.dart#L379):

<details>
<summary>pushTransform</summary>

```dart
context.pushTransform(
  needsCompositing,
  offset,
  Matrix4.identity()
    ..translate(size.width / 2, size.height)
    ..multiply(Matrix4.identity()..setEntry(3, 2, 1.7e-3))
    ..translate(-size.width / 2, -size.height)
    ..translate(size.width / 2, size.height)
    ..multiply(Matrix4.rotationX(-pi / 2 * (1 - spinUpAnimation.value)))
    ..translate(-size.width / 2, -size.height),
  _paintChildren,
);
```

</details>

And the shadow is [drawn here](https://github.com/creativecreatorormaybenot/clock/blob/cd561c82fea2e473a4b30d231531917039b298cc/canvas_clock/lib/components/style/slide.dart#L362):

<details>
<summary>drawShadow</summary>

```dart
canvas.drawShadow(
  Path.from(travelPath)
    ..addPath(startPath, Offset.zero)
    ..addPath(endPath, Offset.zero),
  _shadowColor,
  size.height / 99,
  false,
);
```

</details>

This issue only happens **in native** for me (tested Android). On Flutter web, the shadow is transformed correctly (even without the condition from the link).

<details>
<summary>Flutter doctor</summary>

```
[√] Flutter (Channel master, v1.14.2-pre.51, locale en-US)
    • Flutter version 1.14.2-pre.51
    • Framework revision ec1044a877 (3 days ago), 2020-01-17 19:19:33 -0800
    • Engine revision ecc74c966d
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)
```

It occurs on stable as well.

</details>

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
