### ISSUE TITLE
LUCI infra flake while attempting to upload artifacts to CIPD.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#49240]
The specific [build that failed was 2193](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/2193) on the `Upload Fuchsia Debug Symbols for arm64` phase. The error message [in the logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8890673346177108736/+/steps/Upload_Fuchsia_Debug_Symbols_for_arm64/0/stdout) was `timeout while waiting for CAS service to finalize the upload`. Previous logs indicate that CIPD was mostly functioning correctly and it was just killed on a particularly long verification step (I could be wrong though). I could not find any timeouts specified in the upload script however. It is unclear where the timeout was specified.

**Comment by chinmaygarde** [comment]
cc @dnfield, @godofredoc, @digiter.

**Comment by godofredoc** [comment]
How big are those binaries? CIPD tries to zip the content when uploading and the process can be very slow specially if the size of the binaries is increasing over time.

**Comment by chinmaygarde** [comment]
The [last instance of that zipped artifact](https://chrome-infra-packages.appspot.com/p/flutter/fuchsia-debug-symbols-x64/+/OeF8mFeVQzEXvJNoOCVD_Xyvn-1j4gGglwqACQpb6qoC) was 737M. This will, in all likelihood, increase over time. So we should find and address the timeout soon.

**Comment by dnfield** [comment]
Pinging the LUCI chat about this.

**Comment by chinmaygarde** [comment]
`cipd help create` says  `-verification-timeout` is defaulted to 5 mins. I'm going to bump it up to 10.

**Comment by chinmaygarde** [comment]
Nevermind. @dnfield noticed that successive runs complete in ~1m. So the server was just hung. We need to retry.
