### ISSUE TITLE
setState() doesn't trigger build()

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#49245]
I have a rather complicated widget, but it's general functionality is easy to explain. It starts to listen to a `Stream` in `initState()` and when the `Stream` emits a new value, it calls `setState()`. I know I could use a `StreamBuilder`, but this way I can wait for a `Future` to complete and then call `setState()`, whereas with `StreamBuilder` I need to return a new `Widget` synchronously.

AFAIK every call to `setState()` should trigger a `build()`, but when I go to InteliJ IDEA and click to Debug, sometimes the first time this `Steam` emits a value, `setState()` is called, but `build()` isn't. I checked `mounted` and it's `true`.

The docs don't say anything about the possibility of calling `setState()` and `build()` doesn't getting called right afterwards. Is this a bug on `setState()` or are the docs missing something? 

My Flutter version:

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (6 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by tekno0ryder** [comment]
Hi feinstein,
Can you post sample code of the problem?
You can use FutureBuilder inside your stream builder though

**Comment by feinstein** [comment]
Yeah, I know, it's just the code is so much simpler in the way it is right now.

I don't know if I will be able to shrink it down and reproduce it, it's kinda tedious to trigger it, as it needs a full build and install, and still is random. I could send you the file by e-mail though, is this OK?

**Comment by tekno0ryder** [comment]
No problem, check the following sample, tried to listen to a stream and calling setState after doing a Future and it seems to work correctly

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int current = 0;

  @override
  void initState() {
    super.initState();
    streamListener();
  }

  Stream<int> _myStream() async* {
    for (var i = 0; i < 20; i++) {
      await Future.delayed(Duration(milliseconds: 1000));
      yield i;
    }
  }

  void streamListener() {
    _myStream().listen((onData) async {
      await Future.delayed(Duration(milliseconds: 500));
      current = onData;
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    print("Rebuild...");

    return Scaffold(
      appBar: AppBar(
        title: Text("Streams"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              "Value $current",
              style: TextStyle(fontSize: 24),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by VladyslavBondarenko** [comment]
Hi @feinstein 
is the issue actual?
could you edit the code above to provide a minimal complete reproducible code sample?

**Comment by feinstein** [comment]
Hi @VladyslavBondarenko, unfortunately this error is very hard to test as it's very intermittent and only happens after a new build and install, so testing it is tedious and slow, I will try to trigger it again this week and let you know.

**Comment by pedromassangocode** [comment]
Hi @feinstein 
Once you have time please share the repro code.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
