### ISSUE TITLE
decodeImageFromList and decodeImageFromPixels returns Error: [object Event] at Object.createErrorWithStack

### ISSUE THREAD

**Issue by obshksw** [flutter/flutter#49244]
So I'm taking a screenshot of a VideoElement like this:
```
CanvasElement canvas = CanvasElement(width: _videoElement.videoWidth, height: _videoElement.videoHeight);
canvas.context2D.drawImage(_videoElement, 0, 0);
ImageData imgData = canvas.context2D.getImageData(0, 0, canvas.width, canvas.height);
```

Then show it like this:

```
_pauseCanvas = CanvasElement(width: _videoElement.videoWidth, height: _videoElement.videoHeight); 
_pauseCanvas.context2D.putImageData(imgData, 0, 0);
```

That part works perfectly.

The problem is that I'd prefer to use an Image widget instead of a CanvasElement to reuse some parts of the code on native, but decodeImageFromList don't take a Uint8ClampedList which is what I have from the ImageData and when I use:
`imgData.data.buffer.asUint8List()` or `Uint8List.fromList(imgData.data)`
I get that error:
```
Event {isTrusted: true, Symbol(_jsError): Error: [object Event]
    at Object.createErrorWithStack (http://localhost:57523/packages/build_web…, type: "error", target: img, currentTarget: img, …}
```
It's possible that I don't do the right thing, but I don't have an error that helps me to find what I'm doing wrong. Also tried `decodeImageFromPixels` but I get similar results. 

```
Flutter (Channel unknown, v1.13.9, on Microsoft Windows [Version 10.0.17763.973], locale en-US)
    • Flutter version 1.13.9 at C:\dev\flutter\flutter
    • Framework revision d291de086c (12 days ago), 2020-01-09 10:25:58 -0800
    • Engine revision f001ea29f1
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)
```

Thanks for the help!

**Comment by iapicca** [comment]
Hi @obshksw 
on what platform are you experiencing the issue? ( iOS, Android, web, all)
thank you

**Comment by obshksw** [comment]
@iapicca 
On web !

**Comment by obshksw** [comment]
I found an example that should be working but it still crashes:

```
int kImageDimension = 1024;
        int seed = 0xDEADBEEF;
        int xorshift32(int x) {
          x ^= x << 13;
          x ^= x >> 17;
          x ^= x << 5;
          return x;
        }

        Int32List pixels = Int32List(kImageDimension * kImageDimension);
        for (int i = 0; i < pixels.length; i++) {
          seed = pixels[i] = xorshift32(seed);
        }
        decodeImageFromPixels(pixels.buffer.asUint8List(), kImageDimension, kImageDimension, PixelFormat.rgba8888, (dynamic image) {
        });
```

![image](https://user-images.githubusercontent.com/45799810/72909269-bbe91680-3d04-11ea-9a1a-a7f0f760675f.png)

**Comment by KalilDev** [comment]
decodeImageFromPixels on web works by creating an HtmlBlobCodec from _instantiateImageCodec which transforms the Uint8List into an html.Blob.

This HtmlBlobCodec, stored in codecFuture (inside the decodeImageFromPixels closure), when made available, is then used by calling getNextFrame(), which returns a ui.FrameInfo. getNextFrame creates an ImageElement, sets its src to the blob and then decodes using decode(), then, the resulting HtmlImage is used to complete the future, going back to decodeImageFromPixels for the last step.

The image (which is the ImageElement used to decode the bytedata) is then used to callback the ImageDecoderCallback. BUT, before all this can happen, calling decode() on the ImageElement fails, and even when trying the onLoad fallback it still fails, throwing the error we are facing. This seems odd at first, but when inspected makes total sense, afterall, an ImageElement cannot decode raw pixel data.

The decodeImageFromPixels is, after digging into all this, an unimplemented feature on flutter web. One workaround (for me and you) would be to use an BMP instead while it still is unimplemented, but this should be addressed.

**Comment by KalilDev** [comment]
The simplified version of what is happening under the hood: https://dartpad.dartlang.org/0fe2401e448d72166713428f8d05be4e . I think this issue should be tagged as platform-web & engine.

**Comment by obshksw** [comment]
Thanks for investigating! :)

**Comment by dnfield** [comment]
We should make this throw an unimplemented error in the mean time.

**Comment by dnfield** [comment]
For `decodeImageFromPixels`, this works by generating a BMP and then decoding that:

```dart
  final ByteData bmpData = ByteData(width * height);
  // 'BM' header
  bmpData.setUint8(0x00, 0x42);
  bmpData.setUint8(0x01, 0x4D);
  // Size of data
  bmpData.setUint32(0x02, 0x36 + (width * height), Endian.little);
  // Offset where pixel array begins
  bmpData.setUint32(0x0A, 0x36, Endian.little);
  // Bytes in DIB header
  bmpData.setUint32(0x0E, 0x28, Endian.little);
  // width
  bmpData.setUint32(0x12, width, Endian.little);
  // height
  bmpData.setUint32(0x16, height, Endian.little);
  // Color panes
  bmpData.setUint16(0x1A, 0x01, Endian.little);
  // bpp
  bmpData.setUint16(0x1C, 0x01, Endian.little);
  // no compression
  bmpData.setUint32(0x1E, 0x00, Endian.little);
  // raw bitmap data size
  bmpData.setUint32(0x22, width * height, Endian.little);
  // print DPI width
  bmpData.setUint32(0x26, width, Endian.little);
  // print DPI height
  bmpData.setUint32(0x2A, height, Endian.little);
  // colors in the palette
  bmpData.setUint32(0x2E, 0x00, Endian.little);
  // important colors
  bmpData.setUint32(0x32, 0x00, Endian.little);
  // rest of data is zeroed as black pixels.

  final ui.Codec codec = await ui.instantiateImageCodec(
    bmpData.buffer.asUint8List(),
  );
  final ui.FrameInfo frameInfo = await codec.getNextFrame();
  if (cache) {
    _cache[hashValues(width, height)] = frameInfo.image;
  }
  return frameInfo.image;
```

Assumes a 1bpp image with no special color palette handling. This could probably be expanded to support the same functionality as what's expected for the pixel formats with a little more work.

**Comment by dnfield** [comment]
From what I can tell, `decodeImageFromList` works. What's the failing case for it?
