### ISSUE TITLE
Add to App: App on launch is showing invalid content until reloaded from VSCode

### ISSUE THREAD

**Issue by prasadpamidi** [flutter/flutter#49268]
Hi, 

I am trying to integrate flutter into an existing application manually as mentioned [here](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode).

I am noticing a weird issue, where when I launch the app from XCode, it shows default flutter counter view template and i can only get the proper ui show up by reloading it from vscode. This is not happening, if i setup flutter into the app through cocoapods option.

Is there something else that needs to be done for option 2, that's not mentioned in the document?

I also noticed, after the app is launched from xcode and then if I do hot reload by saving changes in vscode without clicking refresh/reload, the app crashes in XCode.

**Comment by prasadpamidi** [comment]
flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/npamidi/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/npamidi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/npamidi/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/npamidi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 • 157A9915-7F97-4131-9FBE-01A7CAFB6125 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

• No issues found!

**Comment by jmagman** [comment]
I wasn't able to reproduce this.  I created a module, copied https://github.com/flutter/flutter/tree/master/examples/flutter_gallery dart files and pubspec.yaml (except the `module:` section), embedded all the frameworks into an existing host app I have, and was able to launch the gallery from a host app button.  No default counter app.

Can we get more reproduction steps?
1. "i can only get the proper ui show up by reloading it from vscode" How are you doing this, exactly?
2. Do you have a [custom entrypoint](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#dart-entrypoint)?
3. Can you attach your host app "*.xcodeproj/project.pbxproj" (I'm mostly interested in the PBXCopyFilesBuildPhase and PBXFileReference sections, if you need to redact anything)?
4. What's the output of:
```
cd <Flutter module directory> && grep -riI "You have pushed the button this many times:" .
```

**Comment by prasadpamidi** [comment]
Hey @jmagman ,
 
Please take a look at my responses to each of your questions.. 

> I wasn't able to reproduce this. I created a module, copied https://github.com/flutter/flutter/tree/master/examples/flutter_gallery dart files and pubspec.yaml (except the `module:` section), embedded all the frameworks into an existing host app I have, and was able to launch the gallery from a host app button. No default counter app.

The problem is, if u make any changes to the flutter ui code after it was launched the first time and launch the app again directly from XCode, it will still show the old ui until u restart flutter from command line or using VSCode(SHIFT+COMMAND+F5).. I am still new to flutter, dart and vscode eco system, not sure what happens underneath.. 

> 1. "i can only get the proper ui show up by reloading it from vscode" How are you doing this, exactly?

I attached flutter debugger to the simulator.. after the app is loaded via XCode, I am running VSCode(SHIFT+COMMAND+F5)

> 2. Do you have a [custom entrypoint](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#dart-entrypoint)?

No.

> 3. Can you attach your host app "*.xcodeproj/project.pbxproj" (I'm mostly interested in the PBXCopyFilesBuildPhase and PBXFileReference sections, if you need to redact anything)?

[FlutterTest.xcodeproj.zip](https://github.com/flutter/flutter/files/4100571/FlutterTest.xcodeproj.zip)

> 4. What's the output of:
> 
> ```
> cd <Flutter module directory> && grep -riI "You have pushed the button this many times:" .
> ```

I doesn't find anything

**Comment by prasadpamidi** [comment]
Its happening with test apps too and other members on my team are having similar issue.. it always shows the ui that is run the first time for all the subsequent runs..

**Comment by jmagman** [comment]
### The actual reported issue
[The docs say:](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode)
> You must run flutter build ios-framework every time you make code changes in your Flutter module.

"flutter build ios-framework" is not really intended to be used to test incremental changes (the CocoaPods variant is), the idea is that you're satisfied with the Flutter module, and now you'd like to embed it in your app to test and then publish.  This can be ideal for teams where the Flutter devs are operating separately from a larger existing host app, or the module is a totally separate like just the settings panes.

To make incremental changes you would live in the module and run `flutter run` or run `.ios/Runner.xcworkspace` from Xcode, and hotreload etc should work as expected.  Note: any changes you make to that Xcode project will be overwritten, it's just a little wrapper to test your module.

**Does that make sense?  Am I understanding your issue correctly?**

#### Side-note
```
		6E3972E523D9084000B63997 /* Flutter.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Flutter.framework; path = data_platform/Flutter/Debug/Flutter.framework; sourceTree = "<group>"; };
		6E3972E623D9084000B63997 /* App.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = App.framework; path = data_platform/Flutter/Debug/App.framework; sourceTree = "<group>"; };
```
It looks like you are embedding the Debug version of Flutter and the App frameworks.  Don't forget to swap these to Release before you publish or you're going to hit archive and App Store rejections.  See the tip at the bottom of the doc for how to avoid that:

> Tip: To embed the Debug version of the Flutter frameworks in your Debug build configuration and the Release version in your Release configuration, in your MyApp.xcodeproj/project.pbxproj, try replacing path = Flutter/Release/example.framework; with path = "Flutter/$(CONFIGURATION)/example.framework"; for all added frameworks. (Note the added ".)
> 
> You must also add $(PROJECT_DIR)/Flutter/$(CONFIGURATION) to the Framework Search Paths (FRAMEWORK_SEARCH_PATHS) build setting.

So in your case, that would be:
```
		6E3972E523D9084000B63997 /* Flutter.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Flutter.framework; path = "data_platform/Flutter/$(CONFIGURATION)/Flutter.framework"; sourceTree = "<group>"; };
		6E3972E623D9084000B63997 /* App.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = App.framework; path = "data_platform/Flutter/$(CONFIGURATION)/App.framework"; sourceTree = "<group>"; };
```
and in your Framework Search Paths, add `data_platform/Flutter/$(CONFIGURATION)`.
It's unfortunate the project.pbxproj needs to be edited by hand, there's no way to do this in the UI.  Make sure you're using source control in case something gets corrupted and you need to revert.

**Comment by prasadpamidi** [comment]
@jmagman thanks for the detailed information. Running `flutter build ios-framework` indeed pulled in the latest changes .. the cocoapods option seem to be working much better..

I understand the intention behind using flutter modules in the existing apps.. But, wondering if that is realistically possible to build a fully executable flutter module without testing incrementally in the native app. At least, for our use case we were trying to make the flutter module use existing native infrastructure(networking, caching etc) and I assume many apps who want to use flutter in existing apps might also want the flutter modules to use native services while slowly transition to using flutter for everything... 

I've moved to using Cocoapods and that seems to have resolved the problem.

The framework search path, yes I am aware of using the release versions of the framework.. I just create a test app to be able to share the project file here...

**Comment by jmagman** [comment]
> @jmagman thanks for the detailed information. Running `flutter build ios-framework` indeed pulled in the latest changes .. the cocoapods option seem to be working much better..

👍

The CocoaPods path will probably work better for most use cases.   `flutter build ios-framework` is probably best for teams that can't have everyone on the team install Flutter in their dev environment, for one reason or another.  You can picture large apps with subteams where maybe only one corner of the app is Flutter and is developed by one or two teams, and you don't want to require every developer outside those teams to have Flutter and CocoaPods set up.

> At least, for our use case we were trying to make the flutter module use existing native infrastructure(networking, caching etc) and I assume many apps who want to use flutter in existing apps might also want the flutter modules to use native services while slowly transition to using flutter for everything...

Have you explored moving your native code into a local Flutter plugin that the module depends on?  Then you can incrementally test the native code in your module using the `flutter` tools.
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
