### ISSUE TITLE
Asset documentation should have a simple intro.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4927]
The documentation for assets should be clear and more to the point, with details about usage coming up later. For example, [Specifying assets](https://flutter.io/assets-and-images/#specifying-assets) speaks about assets and paths inside the `flutter.yaml` before talking about the assets folder.

A simpler way might be:

> We usually use the `assets` folder for assets. You need to specify them inside the `flutter.yaml`:

Also, we should probably have a very simple example of how to use an image asset closer to the top of the document.

**Comment by eseidelGoogle** [comment]
@qchong is most informed about our high-level docs.  I'm not sure if he authored the assets doc in particular.

**Comment by HansMuller** [comment]
> Also, we should probably have a very simple example of how to use an image asset closer to the top of the document.

I agree. For common questions like this one (how to do I incorporate an image in my app) a brief example is probably all that most developers will need.

**Comment by Hixie** [comment]
I believe this is mostly done now.
