### ISSUE TITLE
cloud_firestore and firebase_messaging

### ISSUE THREAD

**Issue by Bharavi26** [flutter/flutter#49288]
I added these two dependencies **cloud_firestore** and **firebase_messaging**, because of some conflits in cloud_firestore i am not receiving notification in device if i remove cloud_firestore  then notification work, i tried lots of things for this but not perfact solution found.

> `
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
>     • Flutter version 1.12.13+hotfix.5 at /Users/harishvekariya/flutter
>     • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/harishvekariya/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/harishvekariya/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C504
>     • CocoaPods version 1.9.0.beta.2
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> [✓] Connected device (1 available)
>     •  iPhone • ---------- • ios • iOS 13.3
> • No issues found!
> Process finished with exit code 0
> 
>  `

**Comment by VladyslavBondarenko** [comment]
Hi @Bharavi26 
Do you use the last versions of plugins?
Do you receive logs about some conflicts?

**Comment by Bharavi26** [comment]
Hello @VladyslavBondarenko sir,
thank you for replay.

-> yes i am using latest version
-> no i am not getting log in ios.
     It's working perfactly in Android but not working in Ios

**Comment by VladyslavBondarenko** [comment]
@Bharavi26 
I would advice you to open an issue in the [firebase_messaging github](https://github.com/FirebaseExtended/flutterfire/issues) with tagging current one

**Comment by Bharavi26** [comment]
ok @VladyslavBondarenko , i added issue in  firebase_messaging also..
[https://github.com/FirebaseExtended/flutterfire/issues/1865](url)

**Comment by Bharavi26** [comment]
anyone catch same issue?

**Comment by govindbhardwaj** [comment]
@Bharavi26 Have you added your APN in firebase console? In my case that was the case.

**Comment by iapicca** [comment]
Hi @Bharavi26 and @govindbhardwaj 
I recommend to follow up on the issue linked [above](https://github.com/flutter/flutter/issues/49288#issuecomment-577983594)
since this isn't a problem w/ flutter itself this issue will remain close.

Thank you for understanding
