### ISSUE TITLE
connectivity package does not work in  iOS

### ISSUE THREAD

**Issue by ashraful29** [flutter/flutter#49291]
It works well in  Android. But in iOS when i set flight mode first time then it  responds. but after that changing network connection it does not respond anymore. It like StreamSubscription listen only once in iOS . Flutter Doctor return no issue.

[✓] Flutter (Channel master, v1.14.2-pre.51, on Mac OS X 10.15.2 19C57, locale en-BD)
    • Flutter version 1.14.2-pre.51 at /Users/ashrafulislam/Downloads/flutter
    • Framework revision ec1044a877 (4 days ago), 2020-01-17 19:19:33 -0800
    • Engine revision ecc74c966d
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)

 
```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ashrafulislam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
```
And my code where i use the package..
```
@override
  initState() {
    super.initState();
    bloc = Provider.of<V>(context, listen: false);
    WidgetsBinding.instance.addObserver(this);
    _connectionChangeStream = Connectivity().onConnectivityChanged.listen(connectionChanged);
  }
```

**Comment by japborst** [comment]
Having the same issue here.

**Comment by johnsogg** [comment]
I am seeing similar behavior in the iOS simulator. The stream is notified when connectivity goes from wifi to none, but the stream is NOT notified when it goes from none to wifi. Same symptom as @ashraful29, it seems like the subscription only receives the 'none' event (no network). If I start the app with my computer's network turned off, it gets the 'none' event, but no 'wifi' event.

However, the same code running on physical iOS and Android devices seems to work as expected.

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
