### ISSUE TITLE
material_app_ios__compile_debug_full_compile_millis regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49299]
Should be investigated. Looks like a possible candidate for rebaslining.

https://github.com/flutter/flutter/pull/48994 is where it started, but that's a doc fix so I don't believe that. https://github.com/flutter/flutter/commit/e340c19905fd2eca86be3c429bf659963ed9d6f0 looks a little more likely.

**Comment by jonahwilliams** [comment]
I'll eat my shoe if doing hostname resolution for web builds regressed the compile time of an iOS material app.

**Comment by jonahwilliams** [comment]
![2020-01-22](https://user-images.githubusercontent.com/8975114/72924997-cefce600-3d06-11ea-8e90-b8e574836c44.png)

it's not clear from the history that this was a regression. It could be a gradual, decline in the machine or the performance

**Comment by cbracken** [comment]
I've removed the today label this is a ~1% fluctuation in value compared to baseline and it's been fluttering back and forth between below and above for a long time now. If we want to reduce compile times, I bet we can get better than 1% with an afternoon of effort.
