### ISSUE TITLE
[device_info] Android serial number

### ISSUE THREAD

**Issue by iformas** [flutter/flutter#49296]
Is there a plan to support android serial number?

https://developer.android.com/reference/android/os/Build.html#getSerial()
https://developer.android.com/reference/android/os/Build.html#SERIAL
https://gist.github.com/flawyte/efd23dd520fc2320f94ba003b9aabfce

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
