### ISSUE TITLE
The flutter_gallery app stutters during transitions.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4931]
In the Pesto and Shrine parts of the app, the transitions stutter when opening some of the items. This might be because of the larger numbers of items in the list, but it's just a hunch right now.

**Comment by sethladd** [comment]
If you can grab a screenshot of the "performance overlay", that would help. Also, attaching a trace is very useful. Let me know if you need help with those. Thanks!

**Comment by dragostis** [comment]
![screenshot_20160715-123011](https://cloud.githubusercontent.com/assets/4136413/16886355/997e233c-4a88-11e6-897c-81dc9be5d05f.png)
![screenshot_20160715-122952](https://cloud.githubusercontent.com/assets/4136413/16886356/9cf24c5a-4a88-11e6-9629-3dabb2000b93.png)

**Comment by dragostis** [comment]
Here's a trace too:
[dart-timeline-2016-6-15 (1).json.zip](https://github.com/flutter/flutter/files/366745/dart-timeline-2016-6-15.1.json.zip)

**Comment by sethladd** [comment]
Thanks!

I can confirm the stutters on Android M, Nexus 5X. First launch of Pesto has visible stutters.

**Comment by sethladd** [comment]
In case it helps, here's a trace from a 5X, Android M, scoped to just the initial launch of the Pesto app from Gallery (built from `flutter run --profile`). This should more or less the same as what @dragostis attached above.

[dart-timeline-2016-6-15.json.zip](https://github.com/flutter/flutter/files/366808/dart-timeline-2016-6-15.json.zip)

**Comment by sethladd** [comment]
https://github.com/flutter/flutter/issues/5045 is probably a more specific version of this. I think we have other more specific issues, all related to this general issue.

I think there are a few issues inside this overall issue. I'm inclined to close this and refer to real specific issues. Definitely appreciate you creating this issue and uploading the traces!
