### ISSUE TITLE
After quitting an app, "flutter attach" command leaves a "log stream" process running

### ISSUE THREAD

**Issue by weixfeng** [flutter/flutter#49314]
Repro Steps:
1) launch an iOS simulator ("iPhone X" in my case) on Mac
2) open a terminal window and then run the "flutter attach" command
3) launch a Flutter app on your iOS simulator
4) wait until the Flutter observatory port info shows up in the terminal window from Step 2
5) press "q" to quit the connection as suggested in the terminal window
6) after the Flutter connection is terminated, open the "Activity Monitor"

[Result]
A "script" process created by the "flutter attach" command is left behind.  The "flutter attach" command fails for me once I repeat Steps 2-5.

[Comment]
This only repros with a simulator.  I can't repro with a physical Android device.

**Comment by VladyslavBondarenko** [comment]
Hi @weixfeng 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by weixfeng** [comment]
Sure... Here is my output:

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.6 at /Users/wei.feng/sdk/1.12.13+hotfix.6-beta
    • Framework revision 18cd7a3601 (6 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wei.feng/Library/Android/sdk
    • Android NDK at /Users/wei.feng/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/wei.feng/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/wei.feng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone X • 0DDF4B41-4E38-4B7F-BDD2-02FCC385B076 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 3 categories.

**Comment by jmagman** [comment]
Is it a dart process?  What is the leftover process name?
In Activity Monitor, there's a PID column.  Can you plug that PID into the following command and tell us the output?
```
ps -ef <PID>
```
You'll see a "PPID" column from that command.  Can you then plugin it into the same command?
```
ps -ef <PPID>
```

**Comment by weixfeng** [comment]
Yes, there is also a "dart" process.  The leftover process name is "script".

Here is the output from "ps -ef <PID>":

  UID   PID  PPID   C STIME   TTY           TIME CMD
1481431703 33864     1   0  2:12PM ttys000    0:00.03 /usr/bin/script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "0DDF4B41-4E38-4B7F-BDD2-02FCC385B076"

And here is the output from "ps -ef <PPID>" (In my case above, it is "ps -ef 1"):

  UID   PID  PPID   C STIME   TTY           TIME CMD
    0     1     0   0 Sun06PM ??        20:27.90 /sbin/launchd

**Comment by jmagman** [comment]
Interesting, I would have expected that `log` to have been killed:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L728-L731

**Comment by weixfeng** [comment]
Looks like this has been fixed with Flutter 1.18.3-dev.3.0-dev!

**Comment by jmagman** [comment]
Thanks for the update!  Not sure what did it in 1.18.3-dev.3.0, but I definitely expect this to be better as of https://github.com/flutter/flutter/pull/54154 on master.  Closing.
