### ISSUE TITLE
image_picker: error on android when taking second picture

### ISSUE THREAD

**Issue by marco2250** [flutter/flutter#49313]
![image](https://user-images.githubusercontent.com/2913138/72931173-279aa600-3d3c-11ea-8754-e95a58e6dbd7.png)

**Comment by VladyslavBondarenko** [comment]
Hi @marco2250 
Please next time post logs from your console and do it in text form.
Do you face the issue after running `flutter clean`?
If it is so, provide your `flutter doctor -v` together with a minimal code sample to reproduce the problem, and specify what version of image_picker do you use
Thank you

Possibly related to https://github.com/flutter/flutter/issues/28550

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
