### ISSUE TITLE
Web flake: failed to connect to chrome debug port

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49324]
https://cirrus-ci.com/task/5281875627343872?command=main#L1491:

```
[        ] Caching finalized dependency graph...
[  +21 ms] Caching finalized dependency graph completed, took 703ms
[  +15 ms] Succeeded after 1m 20s with 218 outputs (180 actions)
00:00 +0: compiling /tmp/flutter sdk/packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart                                                                                                [+1729 ms] Serving tests at http://localhost:39847/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A39847%2F0&debug=false
00:00 +0 -1: compiling /tmp/flutter sdk/packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [E]                                                                                         
  Failed to load "/tmp/flutter sdk/packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart":
  Unable to connect to Chrome debug port: 40305
   SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 50820
  package:flutter_tools/src/base/common.dart 27:3               throwToolExit
  package:flutter_tools/src/web/chrome.dart 194:9               ChromeLauncher._connect
  ===== asynchronous gap ===========================
  dart:async/future.dart 276:45                                 new Future.error
  package:test_core/src/runner/loader.dart 230:24               Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
```

**Comment by nturgut** [comment]
Hi Dan,

Is this failure observed in other places, is there a place for checking duplicate failures?

**Comment by dnfield** [comment]
This si the place to deduplicate failures to :)

**Comment by dnfield** [comment]
This is a flake - it doesn't happen all the time, but if we see it we should keep track of it here - should help us know how often it's happening, what shard(s) it's happening on, if it's getting more or less frequent, etc.

**Comment by yjbanov** [comment]
@jonahwilliams another indicator that we're not watching browser process' exitCode?

**Comment by jonahwilliams** [comment]
We do wait for it, but it doesn't look like we're doing anything useful:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/chrome.dart#L149

Instead, this code can be updated to check if we've exited prematurely and toolExit

**Comment by hterkelsen** [comment]
Closing this since it's very outdated. This task no longer exists, and a similar (and more up-to-date) issue has been reported here: https://github.com/flutter/flutter/issues/83452
