### ISSUE TITLE
Gallery: name of app launcher on iOS is flutter_gallery, should be Flutter Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4932]
I just ran `flutter run --release` onto my iPhone, and `flutter_gallery` was installed. Can we change this to `Flutter Gallery` ?

**Comment by HansMuller** [comment]
I assume that's coming from `examples/flutter_gallery/ios/Runner/Info.plist`. I'll change it.

**Comment by eseidelGoogle** [comment]
Yeah, this was fallout from moving where Info.plist was stored as part of
@abarth's iOS project updates.  I suspect we just need to move the existing
Info.plist into Runner/

**Comment by sethladd** [comment]
Thanks for the quick analysis!

**Comment by patelkrunal78** [comment]
The Flutter documentation points out where you can change the display name of your application for both Android and iOS. This may be what you are looking for:

Preparing an Android App for Release
Preparing an iOS App for Release
For Android

It seems you have already found this in the AndroidManifest.xml as the application entry.

Review the default App Manifest file AndroidManifest.xml located in /android/app/src/main/ and verify the values are correct, especially:

application: Edit the application tag to reflect the final name of the app.

Find More Here
