### ISSUE TITLE
Flutter's overscroll glow is more jagged than native glow

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4933]
Not sure if this is something we can control, but here's what I see (on Android M, 5X):

Android:

![flutter_01](https://cloud.githubusercontent.com/assets/5479/16888023/715675d0-4a92-11e6-8b15-0ec243c6f4e3.png)

Flutter:

![flutter_02](https://cloud.githubusercontent.com/assets/5479/16888027/75bffdda-4a92-11e6-95fa-37f8fea27d18.png)

Side-by-side (flutter on the right)

![screen shot 2016-07-15 at 1 46 21 pm](https://cloud.githubusercontent.com/assets/5479/16888046/8e83e5de-4a92-11e6-81ab-1c737f95a375.png)

**Comment by eseidelGoogle** [comment]
I suspect it's just a question of antialiasing.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/overscroll_indicator.dart#L69
is the line.  Just add ..isAntialiased == True to fix.

**Comment by sethladd** [comment]
cc @HansMuller thoughts?

**Comment by abarth** [comment]
We should be antialiasing by default.

**Comment by HansMuller** [comment]
The code is just drawing a single quadratic bezier curve. I also thought  antialiasing was on by default. WIll try toggling isAntialiased.

FWIW, Android appears to explicitly turn on antialising when drawing the "glow":
https://github.com/android/platform_frameworks_base/blob/4535e11fb7010f2b104d3f8b3954407b9f330e0f/core/java/android/widget/EdgeEffect.java#L119

**Comment by HansMuller** [comment]
Quadratic beziers render the same jagged way, independent of the antialiasing setting.

Cubic beziers render more smoothly.

![cubic](https://cloud.githubusercontent.com/assets/1377460/16925107/864aecea-4cd7-11e6-8a5f-9c2173a1e8ea.png)

**Comment by sethladd** [comment]
Oooh... that looks smooooooth.

**Comment by Hixie** [comment]
Please file a bug to track the fact that some curves don't look smooth even with AA turned on.
