### ISSUE TITLE
Memory leak issue with StreamProvider and Class instances

### ISSUE THREAD

**Issue by beljand** [flutter/flutter#49337]
I'm using `Provider` with `MultiProvider` basically on all my views. 

I use `StreamProvider` which returns a `List` of Models (Class instances), which are created while listening to a `Firebase` subscription (deserialization).

I've noticed a steady memory increase while navigating do different routes. Turns out that those Models are still inside the heap (according to DevTools). Even when forcing GC, they are not removed from the heap. As far as I can tell those Models are not used by any widget after navigating to a different View, also `maintainState` is set to `false`.

```

// view Model

BehaviorSubject<List<LightningGroupModel>> _lgStream = BehaviorSubject();

void startStreamLgs() {
        _db
        .collection('projects')
        .document(_project_id)
        .collection('lightning_groups')
        .where('DELETED', isEqualTo: false)
        .snapshots()
        .listen(_addLgsToStream);
  }

  void _addLgsToStream(QuerySnapshot snap) {
    var lgs = _getLgsFromSnap(snap);
    _lgStream.add(lgs);
  }

  List<LightningGroupModel> _getLgsFromSnap(QuerySnapshot snap) {
    var lgList = List<LightningGroupModel>();
    var docs = snap.documentChanges;

    if(docs.length > 0) {
      for(var doc in docs) {
        lgList.add(LightningGroupModel.fromMap(doc.document));
      }
    }
    return lgList;
  }


// consumer View

MultiProvider: [ 
StreamProvider<List<LightningGroupModel>>(
          create: (_) =>
              _projectViewModel.lgStream
        ),
]

```

What am I missing here?

**Comment by chinmaygarde** [comment]
Is there a reduced test case for this? If not, I would suggest using the `Dominator (TreeView)` in the Allocations profile using the observatory to figure out where the references are coming from.

**Comment by darshankawar** [comment]
@beljand 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, please provide a minimal reproducible code sample along with `flutter doctor -v` that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
