### ISSUE TITLE
List addAll throw error :Unhandled Exception: Concurrent modification during iteration:

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#49339]
Initially I have value in `stream`. Is it impossible to add list into stream again ?

``` @override
  List<dynamic> userImage(File images) {
    if (images != null) {
      capturedImagesList.add(images.path);  // add selected image to List
      capturedImagesList.addAll(_bloc.urlImageStream.value);  // add the server image to list
       _bloc.urlImageSink.add(capturedImagesList);  // add all images to list
    }
    return null;
  }

```

**Error**

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Concurrent modification during iteration: Instance(length:3) of '_GrowableList'. E/flutter (32313): #0 List.addAll (dart:core-patch/growable_array.dart:187:11)

I have asked at SO,but no reply.

https://stackoverflow.com/questions/59865627/list-addall-throw-error-unhandled-exception-concurrent-modification-during-ite

**Comment by VladyslavBondarenko** [comment]
Hi @tony123S 
You may consider to better open an issue in [dart github](https://github.com/dart-lang/sdk/issues)

**Comment by mraleph** [comment]
The exception indicates that there is a problem with your code - you are iterating a list (e.g. via addAll) and simultaneously modifying it. Most likely `capturedImagesList` and `_bloc.urlImageStream.value` is the same list.
