### ISSUE TITLE
[web]: Native swipe gestures in browser broken to refresh and go back

### ISSUE THREAD

**Issue by plusmobileapps** [flutter/flutter#49340]
I noticed while I was developing on flutter web that the Mac two finger swipe gesture to go back in the chrome browser was not working. After looking at the [sample flutter gallery](https://flutter.github.io/samples/#/), I noticed that this gesture was not working as well. Then I opened up the gallery on my iPhone to discover that the swipe down to refresh gesture was not working in the browser. Curious what is going on with the native web browser hooks that is there for every other site and not for flutters? Or is this something flutter doesn't support currently?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)
```
Chrome Version: 79.0.3945.117

**Comment by VladyslavBondarenko** [comment]
Hi @plusmobileapps 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/23604
You can thumb it up, maybe comment with your case if you think necessary
I'm closing the current one.
If you disagree please write in the comments
and I will reopen it.
Thank you
