### ISSUE TITLE
'UrlLauncherPlugin.h' flie not found

### ISSUE THREAD

**Issue by SPMXithing** [flutter/flutter#49344]
Maybe someone else has this issue at this moment. I have started to experience this issue a few days ago while trying to run my app in Xcode to simulate it on the iPhone. I thought I had solved it by removing the plugin and installing it again but today it is happening again. 
<img width="1503" alt="Screenshot 2020-01-23 at 12 56 14" src="https://user-images.githubusercontent.com/58042613/72982616-c1fff580-3ddf-11ea-98ed-78a7505df39c.png">

The only thing I did before this started to happen was this follow this instructions after Android studio was complaining:

Warning: Podfile is out of date. This can cause a mismatched version of Flutter to be embedded in your app, which  may result in App Store submission rejection or crashes.If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.

**Comment by VladyslavBondarenko** [comment]
Hi @SPMXithing 
Dublicate of https://github.com/flutter/flutter/issues/27893
Does https://github.com/flutter/flutter/issues/16049#issuecomment-382629492 help you?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
