### ISSUE TITLE
On web the Clipboard.setData future never completes

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#49349]
## Steps to Reproduce

1. On the master channel, create a web app with the following widgets: https://gist.github.com/perclasson/6863d899fbdbe670358da9b5c779c824
2. Copy text to keyboard. It works but no snackbar shows on up on Web/Chrome because the future `Clipboard.setData` never completes (it still copies to the clipboard). With the timeout added of 1 seconds, it shows that it times out. On the iOS simulator it works as expected.

## Flutter doctor
```
[✓] Flutter (Channel master, v1.10.1-pre.1697, on Mac OS X 10.15.2 19C57, locale en-DE)
    • Flutter version 1.10.1-pre.1697 at /Users/perc/development/flutter
    • Framework revision a1fa1a3d26 (15 hours ago), 2020-01-22 14:58:46 -0800
    • Engine revision 83a64b7233
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/perc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 81158E5C-C27D-49D1-9FD9-55EE1011FEBF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.130
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

## Related issues
https://github.com/flutter/flutter/issues/46020

**Comment by nturgut** [comment]
I'll have a look thanks for filing the issue.

**Comment by nturgut** [comment]
Just to make sure, the content is copied to the clipboard. However the future is not complete, right?

**Comment by perclasson** [comment]
@nturgut Thanks for looking into it. That is correct, it copies to the clipboard but the future never completes.

**Comment by echomartha** [comment]
hello @perclasson , i;ve already saw your code to added timeout , but when i try it cant

**Comment by echomartha** [comment]
`clipBoard(String url) async {
    await Clipboard.setData(ClipboardData(text: url))
        .then(
          (dynamic result) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Success')),
          ),
        )
        .catchError(
          (Object error) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Error $error')),
          ),
        );
  }`

**Comment by echomartha** [comment]
> clipBoard(String url) async {
    await Clipboard.setData(ClipboardData(text: url))
        .then(
          (dynamic result) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Success')),
          ),
        )
        .catchError(
          (Object error) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Error $error')),
          ),
        );
  }
