### ISSUE TITLE
Document how to get a trace

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4934]
@dragostis and I couldn't find simple docs on how to capture a trace, using Flutter and Observatory.

It's straightforward, once you know how to do it. I think we can add a few documented steps to https://flutter.io/debugging/

**Comment by eseidelGoogle** [comment]
The observatory timeline exposes tracing, there also used to be a `flutter trace` command which could be used to start/stop tracing it may still work.

**Comment by sethladd** [comment]
cc @qchong

**Comment by eseidelGoogle** [comment]
This also likely relates some to https://github.com/flutter/flutter/issues/5550.

**Comment by Hixie** [comment]
cc @chinmaygarde who mentioned writing a document about performance

**Comment by Hixie** [comment]
We definitely need to document how to take a trace, how to use the trace viewer, how to interpret the results...

**Comment by eseidelGoogle** [comment]
We really need to solve this. :(  If for no other reason than to have it written down for all the many folks joining the Flutter team.  @chinmaygarde @cbracken @Hixie any of you want to take a stab?  Even something quick and short and in a doc or wiki? :)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2067](https://github.com/flutter/website/issues/2067) via [**ZenHub**](https://www.zenhub.com/)
