### ISSUE TITLE
Space key doesn't work after cursor movement using space button on iphone8

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#49350]
## Steps to Reproduce
env : iphone8 ios13.3 work at emulate

1. input multiline text in textField( like """aaaaaa\n\nbbbbb"""
2. then long press spacebutton 
3. move to a line without characters
4. press space ( does't work)
5. press other key ( space is appear )

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale ja-JP)
  • Flutter version 1.12.13+hotfix.5 at /Users/user/Desktop/development/flutter
  • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
  • Engine revision 2994f7e1e6
  • Dart version 2.7.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
  • Android SDK at /Users/user/Library/Android/sdk
  • Android NDK location not configured (optional; useful for native profiling support)
  • Platform android-29, build-tools 29.0.2
  • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
  • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 11.3, Build version 11C29
  • CocoaPods version 1.8.4
[✓] Android Studio (version 3.5)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin version 42.1.1
  • Dart plugin version 191.8593
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
[!] Connected device
  ! No devices available
```

I paste gif here
![spacebug](https://user-images.githubusercontent.com/7422251/72993372-9e1cce00-3e38-11ea-83dc-ded28ae41ceb.gif)

I think there lot of input bug on iphone8.
from my users, they report order of the characters is changed
I wish to check other point too.

**Comment by hatano0x06** [comment]
I think this problem cause all device before iphone8

**Comment by VladyslavBondarenko** [comment]
@hatano0x06 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/50033
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
