### ISSUE TITLE
[elided] Crash signature "dart::SpawnIsolateTask::Run-5726ab5f" on [elided version]

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49358]
https://b.corp.google.com/issues/147798920. 

Original hypothesis was related to regular reboot housekeeping, now not sure --- see comments on the Google bug above. Conversation to occur there, please.

cc @chinmaygarde , who was given the issue at Google.

**Comment by chinmaygarde** [comment]
@kf6gpe I am on the Fuchsia chaselist issue ATM. I'll let you know when I start investigating this.

**Comment by jason-simmons** [comment]
@chinmaygarde Does `DartIsolate::PrepareForRunningFromPrecompiledCode` need to check for a null child isolate preparer before calling `SetChildIsolatePreparer`?

Similar to what `PrepareForRunningFromKernel` is doing here:
https://github.com/flutter/engine/blob/master/runtime/dart_isolate.cc#L380
