### ISSUE TITLE
SkiaGpuObjectTest::ObjectResetBeforeDestructor if flaky on Fuchsia.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#49367]
The build that this test flaked on was https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/2230. Logs for the failing test are at https://chromium-swarm.appspot.com/task?id=49eb25af7dea7710. Recommend disabling the flaky test on Fuchsia till the issue is resolved.

cc @gw280 @iskakaushik

**Comment by gw280** [comment]
cc @arbreng

**Comment by chinmaygarde** [comment]
I don't believe this has flaked in the past few days. But, since we are now being more aggressive about tracking/tackling flakes, we should disable this test ASAP and investigate soon. This ended up blocking autorollers.

**Comment by arbreng** [comment]
This hasn't flaked for a long period of time.  Closing as obsolete for now
