### ISSUE TITLE
Flutter upgrade command failing because its trying to use an old proxy

### ISSUE THREAD

**Issue by tapiwamaguwu** [flutter/flutter#49362]
When I first downloaded flutter I was using a proxy over a wired LAN network at my school. Now When Im at home where I use WIFI without a proxy I get the following error when I try to run the :

```
_Invoke-WebRequest : The remote name could not be resolved: 'proxy.uz.ac.zw'
At C:\src\flutter\bin\internal\update_dart_sdk.ps1:68 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand_
```
'proxy.uz.ac.zw' is the proxy from school. Please help me out im stuck i want to start Flutter web development but I cant until i update my flutter

**Comment by TahaTesser** [comment]
Hi @tapiwamaguwu 
Is this still an issue for you?  We haven't seen such bug reports and I am not sure how I can reproduce it

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
