### ISSUE TITLE
[Windows] Path handling does not support UTF-8 properly

### ISSUE THREAD

**Issue by Tokenyet** [flutter/flutter#49372]
After testing a bunch of C method, I found out there is something strange in the [flutter engine source code](https://github.com/flutter/engine/blob/46adf73d5128269ed75572368eb720117d771ca8/shell/platform/embedder/embedder.cc#L665)

```
  std::string icu_data_path;
  if (SAFE_ACCESS(args, icu_data_path, nullptr) != nullptr) {
    icu_data_path = SAFE_ACCESS(args, icu_data_path, nullptr);
  }
...
  settings.icu_data_path = icu_data_path;
  settings.assets_path = args->assets_path;
```

According to `icu_data_path`, why does `assets_path`not need to use `SAFE_ACCESS`? This is the wired thing I found, becuase `icu_data_path` seems to work with Chinese, but `assets_path` not.

I think the code for `assets_path` should be the same as `icu_data_path`:
```
  std::string assets_path ;
  if (SAFE_ACCESS(args, assets_path , nullptr) != nullptr) {
    assets_path = SAFE_ACCESS(args, assets_path , nullptr);
  }
...
  settings.assets_path = assets_path ;
```
I can't pretty sure this is the error, but after testing every single function with legal Chinese path, this is the only possibility different code. If this is not a legal issue, feel free to close 😢

**Comment by stuartmorgan** [comment]
> [Windows] Chinese path bug cause Not running in AOT mode

We don't have AOT support implemented for the Windows embedding yet, so I'm confused as to what the title is referring to.

> why does assets_pathnot need to use SAFE_ACCESS?

Because there is no version of that struct that didn't contain `asset_path`, so the macro to validate struct size first isn't necessary. I don't understand what relationship you think there is between struct size validation and language.

> becuase icu_data_path seems to work with Chinese

I'm not sure how you are determining what does and does not work. IIRC bad ICU data paths aren't immediately fatal, so my guess is that your test is not accurate as to whether you've constructed the path correctly.

Can you provide the specific code you are using to populate the asset path? I think the most likely explanation here is that you have an encoding problem in the way you are populating the struct.

**Comment by dnfield** [comment]
Is the issue here that your local file path has Chinese characters in it?

**Comment by Tokenyet** [comment]
Sorry for mess description, It's a bit hard to talk about this issue, but I'll try my best! Here is the original issue on [https://github.com/go-flutter-desktop/go-flutter/issues/341](https://github.com/go-flutter-desktop/go-flutter/issues/341).

According to pchampio 's comment, There is no issue on Linux with the Chinese path, like: "Project\To\reproducable\path測試\kernel_blob.bin", But there is a issue when I use `D:\Project\FlutterPlayground\reproducable\path測試\kernel_blob.bin` in the go-flutter. 

So I traced the code from [go-flutter-code](https://github.com/go-flutter-desktop/go-flutter/blob/ef6b553dadcace83ce35a0651ea0cbeb3b2a08af/application.go#L169-L186) to  [flutter/engine code](https://github.com/flutter/engine/blob/46adf73d5128269ed75572368eb720117d771ca8/shell/platform/embedder/embedder.cc#L669-L680), and tried to log every possible encoding problem from **go-flutter** first, and then also tested the related function that related to the possibilty to log `Not running in AOT mode but could not resolve the kernel binary.`.

The first thing I did, I logged the [code](https://github.com/go-flutter-desktop/go-flutter/blob/6244ff9f95e73375aeaeeaa52054da77977dc9dd/embedder/embedder.go#L85-L130) before sent path to flutter engine.
```
func (flu *FlutterEngine) Run(userData unsafe.Pointer, vmArgs []string) Result {

	for range vmArgs {
		if vmArgs[0] == "" {
			vmArgs = vmArgs[1:]
		}
	}
	vmArgs = append([]string{"go-flutter"}, vmArgs...)

	if C.FlutterEngineRunsAOTCompiledDartCode() {
		path, err := filepath.Abs(filepath.Join(filepath.Dir(os.Args[0]), "libapp.so"))
		if err != nil {
			fmt.Printf("Failed to resolve AOT snapshot file: %v\n", err)
			os.Exit(1)
		}
		if _, err := os.Stat(path); os.IsNotExist(err) {
			fmt.Printf("Failed to find AOT snapshot file in %s: %v", path, err)
			os.Exit(1)
		}
		vmArgs = append(vmArgs, "--aot-shared-library-name="+path)
	}

	cVMArgs := C.malloc(C.size_t(len(vmArgs)) * C.size_t(unsafe.Sizeof(uintptr(0))))

	a := (*[1<<30 - 1]*C.char)(cVMArgs)

	for idx, substring := range vmArgs {
		a[idx] = C.CString(substring)
	}

	args := C.FlutterProjectArgs{
		assets_path:       C.CString(flu.AssetsPath),
		icu_data_path:     C.CString(flu.IcuDataPath),
		command_line_argv: (**C.char)(cVMArgs),
		command_line_argc: C.int(len(vmArgs)),
	}
        /* This is the log */
        fmt.Printf("%s\n", flu.IcuDataPath)
	fmt.Printf("%v\n", C.GoString(C.CString(flu.AssetsPath)))
	fmt.Printf("%v\n", args)
        /* This is the log */

	args.struct_size = C.size_t(unsafe.Sizeof(args))

	res := C.runFlutter(userData, &flu.Engine, &args)
	if flu.Engine == nil {
		return ResultInvalidArguments
	}

	return (Result)(res)
}
```

The code returned:
```
D:\Project\FlutterPlayground\flutter_playground_fix_中文\go\build\outputs\windows\icudtl.dat
embedder.cc (674): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary.D:/Project/FlutterPlayground/flutter_playground_fix_中文/go/build/outputs/windows/flutter_assets

{0 0x2ebea90 <nil> <nil> 0x2ebeb00 2 0x2eb8280 <nil> <nil> 0 <nil> 0 <nil> 0 <nil> 0 <nil> <nil> <nil> <nil> false <nil> <nil> 
<nil> false <nil>}
go-flutter: engine.Run() returned result code 2 (invalid arguments)
```

This let me focus the point on [flutter/engine](https://github.com/flutter/engine/blob/46adf73d5128269ed75572368eb720117d771ca8/shell/platform/embedder/embedder.cc#L669-L680)

```
  settings.icu_data_path = icu_data_path;
  settings.assets_path = args->assets_path;
  settings.leak_vm = !SAFE_ACCESS(args, shutdown_dart_vm_when_done, false);
  settings.old_gen_heap_size = SAFE_ACCESS(args, dart_old_gen_heap_size, -1);

  if (!flutter::DartVM::IsRunningPrecompiledCode()) {
    // Verify the assets path contains Dart 2 kernel assets.
    const std::string kApplicationKernelSnapshotFileName = "kernel_blob.bin";
    std::string application_kernel_path = fml::paths::JoinPaths(
        {settings.assets_path, kApplicationKernelSnapshotFileName});
    if (!fml::IsFile(application_kernel_path)) {
      return LOG_EMBEDDER_ERROR(
          kInvalidArguments,
          "Not running in AOT mode but could not resolve the kernel binary.");
    }
    settings.application_kernel_asset = kApplicationKernelSnapshotFileName;
  }
```

After testing [isFile](https://github.com/flutter/engine/blob/72e167e47d96312a95e2bc4d799ef5c9a9d45ba4/fml/platform/win/file_win.cc#L261-L266) and [flm::paths::JoinPaths](https://github.com/flutter/engine/blob/70a1106b509ea3f34febca59967ed7a76c05ce33/fml/paths.cc#L14-L30) with Chinese path (my example in attachment), but pass the test I wrote, the only thing I could observe the difference is `SAFE_ACCESS`.
[reproducable.zip](https://github.com/flutter/flutter/files/4108407/reproducable.zip).

That's all I tried, and this issue is surely existed, but I can't really point out where's wrong, Sorry 😞 
Look back for the issue, The [original issue](https://github.com/go-flutter-desktop/go-flutter/issues/341) is to find why the exectuable (I mean the whole related with .exe) cannot be put on non-English path on **Windows**, or It might crash with the error `Not running in AOT mode but could not resolve the kernel binary.`

**Comment by Tokenyet** [comment]
I made reproducable to UTF-8, and It seems to show the bug! Here is the gif:

![2020-01-25 01-18-30](https://user-images.githubusercontent.com/6420527/73089334-f921f400-3f10-11ea-99f8-27cbe58ccfc4.gif)

[reproducable.zip](https://github.com/flutter/flutter/files/4109736/reproducable.zip)

**Comment by dnfield** [comment]
Sounds like our bug is that we're not properly handling UTF-8 in paths.

**Comment by dnfield** [comment]
@Tokenyet - I can't seem to open the zip.  It'd be really nice if you could just paste the body of your testcase into a comment here.

**Comment by Tokenyet** [comment]
@dnfield , um.. I would paste whole file, and thanks for changing the right title 😄 
```
#include <iostream>
#include <stdio.h>
#include <sstream>
#include <sys/stat.h>
#include <string>
#include <utility>

using namespace std;
//#define S_ISREG(m) (((m)&S_IFMT) == S_IFREG)

bool IsFile(const std::string& path) {
  struct stat buf;
  if (stat(path.c_str(), &buf) != 0)
    return false;
  return S_ISREG(buf.st_mode);
}

std::string JoinPaths(std::initializer_list<std::string> components) {
  std::stringstream stream;
  size_t i = 0;
  const size_t size = components.size();
  for (const auto& component : components) {
    i++;
    stream << component;
    if (i != size) {
#if OS_WIN
      stream << "\\";
#else   // OS_WIN
      stream << "/";
#endif  // OS_WIN
    }
  }
  return stream.str();
}

int main()
{
  cout<<"Hello World\n";
  const std::string fullPath = std::string("D:/Project/FlutterPlayground/reproducable/pathA/kernel_blob.bin");
  const std::string relativePath = std::string("pathA/kernel_blob.bin");
  const std::string chinesePath = std::string("path中文/kernel_blob.bin");
  if(IsFile(fullPath))
    cout << "FullPath" << "True\n";
  else
    cout << "FullPath" <<"False\n";
  if(IsFile(relativePath))
    cout << "RelativePath" << "True\n";
  else
    cout << "RelativePath" <<"False\n";
  if(IsFile(chinesePath))
    cout << "ChinesePath" << "True\n";
  else
    cout << "ChinesePath" <<"False\n";
  
  cout << JoinPaths({"D:\\Project\\FlutterPlayground\\flutter_playground_fix_中文", "kernel_blob.bin"});
  cout << "\n";
  cout << "\n";
  cout << "\n";
  cout << "Print Directly, D:\\Project\\FlutterPlayground\\flutter_playground_fix_中文" << "\n";
  return 0;
}
```

**Comment by stuartmorgan** [comment]
The posix compatibility calls like `stat` may well take a machine-configuration-specific encoding rather than UTF-8. We should probably change `IsFile` to convert to UTF-16 and use a wide-string based API like some other parts of that file.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/engine/pull/16105 fixes running the FDE Windows runner in paths with unicode characters in my local testing, and adds a unit test that ensures that unicode is handled. I would expect go-flutter-desktop to be fixed as well, but haven't tested.

I believe there's still an edge case issue that's unresolvable under the current API though. Win32 file API documentation indicates that paths aren't normalized in any way, and are just treated as opaque wchar sequences. Since we're doing a UTF-16->UTF-8->UTF-16 transformation, we could potentially hit cases where the starting and ending UTF-16 values aren't the same. Fixing that would require changing the embedder API (e.g., adding an optional wide version of any path argument which is preferred if present). We can probably wait on that to see if it actually comes up in practice though.
