### ISSUE TITLE
Failures due to hotfix patches make the LUCI tree red with no obvious way for sherrifs to debug the failure.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#49381]
When [LUCI jobs on hot-fix branches fail](https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/3725), the UI is updated to indicate that a specific builder is red and the tree is closed. However, no failing jobs are listed on the console.
<img width="1407" alt="Screen Shot 2020-01-23 at 2 30 08 PM" src="https://user-images.githubusercontent.com/44085/73030877-6c334980-3def-11ea-9b89-af99bc4bddec.png">
However, having the tree closed makes it so that no auto-rollers may proceed. The sheriffs for these rollers have very little ability to debug and fix issues because the tree is actually fine. It is also not clear how to put the tree back into the green state. Should commits be manually pushed?

Due to the severe knock on effects of tree closures, hot-fix failures should not close the tree on an unrelated branch. In the short term, some guidance/warning about the potential for tree closures due to this would be great as it would prevent a fair amount of confusion.

**Comment by chinmaygarde** [comment]
cc @tvolkert @dnfield @godofredoc

**Comment by dnfield** [comment]
We should make dedicated hotfix builders.  They should be set up to watch the hotfix branches.  It would also resolve the need to manually run jobs.

**Comment by godofredoc** [comment]
@digiter please take a look I think this is just configurations and filtering of the results
