### ISSUE TITLE
Support EventChannel C++ plugin API

### ISSUE THREAD

**Issue by Kurun-pan** [flutter/flutter#49398]
## Use case

EventChannel C++ plugin API is needed to support Linux, Windows and Embedded platform.

## Proposal

Implement EventChannel C++ plugin API. I think it's not a difficult task just to implement it. I know it depends on priority.

**Comment by stuartmorgan** [comment]
> and Embedded

What is this referring to? Linux and Windows are the only platforms I'm aware of using the C++ plugin API.

**Comment by Kurun-pan** [comment]
Yes, for example, raspberry pie.

In principle, If there are C++ plugin APIs, Flutter can work on various devices in principle. I have no further intentions. Flutter Engine supports ARM CPU and I understand that it runs on Raspberry Pi with Linux.

But, whether it is officially supported is a different topics. I fully understand that.  Please disregard embedded.

**Comment by stuartmorgan** [comment]
> If there are C++ plugin APIs, Flutter can work on various devices in principle.

Assuming someone wrote embeddings for those devices, and chose to write them to be API-compatible with plugin portions of the Windows and Linux C embedding API. The C++ plugin code interacts with the embedding APIs, not the engine directly, and so will not automatically work with an arbitrary custom engine embedder.

**Comment by Kurun-pan** [comment]
Yes, I understand. 
For example, MethodChannel already implemented, my understanding is as follows. It's an overview.
<img width="1107" alt="スクリーンショット 2020-01-27 20 59 09" src="https://user-images.githubusercontent.com/38722979/73173084-df1e2680-4147-11ea-9158-2cad2729dd32.png">

It is necessary to build Flutter Engine and client_wrapper etc for ARM CPU and link those with graphics library, but if it can be done, it will run on Raspberry Pi with Linux. Of course, if I want to run a flutter application, I need built flutter assets.

Let’s return to the main subject.

I am trying to implement EventChannel API. I will send a pull-request when implemented, so I would like you to review it.

**Comment by Sunbreak** [comment]
@Kurun-pan any progress?

**Comment by Kurun-pan** [comment]
@Sunbreak 
Sorry, I'll implement this weekend. Want immediately?

**Comment by Sunbreak** [comment]
> @Sunbreak
> Sorry, I'll implement this weekend. Want immediately?

Looking forward to it :)

**Comment by Kurun-pan** [comment]
@Sunbreak 
Okay, thanks.
I'll implement and test it as soon as possible and send a pull request.

**Comment by Kurun-pan** [comment]
I completed the implementation and testing, so I made a pull request.
