### ISSUE TITLE
MediaQueryData orientation missing?

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#4940]
MediaQueryData no longer includes orientation information (the size, devicePixelRatio and padding is still there) and rotating the phone does not trigger new builds.  It stopped working for me after updating to latest alpha (I think).

vinteresting@vinteresting-VirtualBox:~$ flutter devices
1 connected device:

LG LS980 • LGLS9809524a5db • android-arm

Android version 5.0.2

## Flutter Doctor

vinteresting@vinteresting-VirtualBox:~$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/vinteresting/dev/github/flutter
    • Framework revision 9c0c0225a6 (3 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/vinteresting/dev/android-sdk-linux
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.32

**Comment by abarth** [comment]
> MediaQueryData no longer includes orientation information

https://docs.flutter.io/flutter/widgets/MediaQueryData/orientation.html

Does that field return null somehow?  The implementation looks like it should always produce an answer:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/media_query.dart#L59

> Framework revision 9c0c022 (3 weeks ago)

Is the issue fixed on master?  If so we should update the alpha branch.

**Comment by cooler-king** [comment]
It's always returning portrait because the size values do not change no matter how I rotate the phone.

(But the orientation getter does return a value - my mistake.)

**Comment by cooler-king** [comment]
**GAH**.  Somehow the auto-rotate got turned off in my phone settings.  Not a flutter issue.

Nothing to see here.
