### ISSUE TITLE
Add doctor check to verify that the required hosts are reachable

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#49403]
It would be useful for some users to know if the tool can reach the hosts that are required to fetch artifacts.

This can be surfaced as a Flutter doctor check.

For context:
* https://github.com/flutter/flutter/issues/22470
* https://github.com/flutter/flutter/issues/30597

**Comment by TanujChaniyari07** [comment]
@blasten I love to fix this, please guide me

**Comment by MrBirb** [comment]
@blasten #95386 was recently merged. Do you think this issue can be closed?

**Comment by PixelToast** [comment]
Closing as it looks like this was fixed by #95386
