### ISSUE TITLE
 Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = URL API, port = 42294

### ISSUE THREAD

**Issue by muhichsan67** [flutter/flutter#49416]
##  Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = URL API, port = 42294

I'm recieve this error while trying to access it with this code
![flutter_auth](https://user-images.githubusercontent.com/22463312/73054605-6c9a1600-3ebd-11ea-8560-7714887a91a8.png)

I've try the url using postman and work perfectly, did i write it correctly? cause i'm not sure about placing authorization basic auth code

```
```

</details>

**Comment by dnfield** [comment]
This would be a better question for StackOverflow - in particular, with a complete minimal and reproducible example, and ideally the text of your reproduction rather than a screenshot of it.

It does seem strange that you are trying to post to ""....
