### ISSUE TITLE
Remove uploading of API docs to cloud storage

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4941]
We're now producing API doc sets from Travis, when merging to master, and then uploading to Firebase Static Hosting.

We can remove the call to the docs.sh script from the chromium buildbot scripts. We can also consider deleting the cloud storage bucket used to hold the old API docs.

**Comment by sethladd** [comment]
Unfortunately, I don't think I can change the scripts used for the chromium build bots, so someone else is going to have to help there :)

**Comment by abarth** [comment]
I can take this on.

**Comment by abarth** [comment]
https://codereview.chromium.org/2177983003

**Comment by sethladd** [comment]
Thanks! I noticed that docs.sh still had some upload instructions in it. I'll take those out as part of https://github.com/flutter/flutter/issues/5174
