### ISSUE TITLE
[android] support android 12L

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#49411]
Hi,
several [dual screen](https://blogs.windows.com/windowsdeveloper/2020/01/22/announcing-dual-screen-preview-sdks-and-microsoft-365-developer-day/) and [foldable screen](https://developer.android.com/guide/topics/ui/foldables) devices,
like smartphone, tablet and laptop are entering the market
in my opinion support for said feature should be taken in consideration.
Thank you for reading

**Comment by dnfield** [comment]
Could you clarify what you want to have taken into consideration?

AFAIK Flutter should work on a dual/foldable screen device (in fact, I'm sure I've seen Flutter apps running on foldable screen devices). But depending on which features you might want to take special advantage of could make a diffference.

**Comment by iapicca** [comment]
@dnfield since Android is going to support fdable screens would be nice to change the app's behavior "onScreenFolded" / "onscreen Unfolded", I can guess as now the app would probably rebuild according to the new screen size, but would be great to have control over that, essentially similar behaviors for device with 2 screens are "flipped" or "open" although I'm not sure Android that.
Maybe all of this might be handled w/ "onDeviceScreenSizeIncrease/Decrease".

**Comment by dnfield** [comment]
We could probably come close with media query updates.  Do you know if android has an API for this?

**Comment by iapicca** [comment]
@dnfield  I'd look into it

**Comment by iapicca** [comment]
Quick update
there's a potential [emulator](https://docs.microsoft.com/en-us/dual-screen/android/use-emulator?tabs=windows) for multi screen!

[samsung galaxy z](https://media.wired.com/photos/5e4345d6f7018900080a0e4d/master/w_1600%2Cc_limit/Gear-Samsung-Galaxy-Flip-Z-SOURCE-Alicia-Cocchi.jpg)'s [laptop mode](https://technewsdirectory.com/wp-content/uploads/2020/02/best-samsung-galaxy-z-flip-deals-pre-order-deals-218x150.jpg) is quite smart 
and I guess it will likely picked up from some android API

**Comment by iapicca** [comment]
Here is the [link](https://devblogs.microsoft.com/surface-duo/get-started-with-flutter-on-surface-duo/) to  Microsoft tutorial to build flutter apps for `surface duo`

**Comment by GroovinChip** [comment]
Is there any progress on this, @iapicca? I've been experimenting with optimizing Flutter apps for the Surface Duo and I'm currently working on showing Dialogs on only one screen when an app is spanned across both screens. My implementation is to wrap my dialog in a Stack and use a Positioned to move it around, but since MediaQuery does not seem to recognize the seam (hinge, gap, whatever you want to call it - 'seam' is Microsoft's word), I have to use a specific double value to place the dialog. This requires a lot of fine-tuning to get the placement just right, especially if the content in the dialog is wider than the default width.

**Comment by MisterJimson** [comment]
I can also investigate if there is anything I can do to help with dialogs in `multi_screen_layout`

**Comment by iapicca** [comment]
@GroovinChip 
I opened this issue as a "generic" request for support for dual screen,
but I haven't worked on it since then;
the behavior you are [pointing out](https://github.com/flutter/flutter/issues/49411#issuecomment-687176017) seems specific and reproducible
I'd open a specific issue for that, just my 2 cents.

tagging @TahaTesser for visibility

**Comment by GroovinChip** [comment]
Fair enough, thank you

**Comment by GeekySingh** [comment]
> We could probably come close with media query updates. Do you know if android has an API for this?

Android has officially introduced [WindowManager](https://developer.android.com/jetpack/androidx/releases/window) library under Android Jetpack umbrella to support new form factors.

**Comment by rlee1990** [comment]
Will flutter support this down the line?

**Comment by aoatmon** [comment]
this could be renamed "add support for [android 12L](https://developer.android.com/about/versions/12/12L)"

**Comment by iapicca** [comment]
the issue should probably be addressed as "support[ android 12L](https://developer.android.com/about/versions/12/12L/summary)"

[android 12L hands on](https://youtu.be/f84npavbpok)

**Comment by darshankawar** [comment]
@iapicca Thanks. Done.

**Comment by blasten** [comment]
@andreidiaconu is working on this feature. There are some PRs still in progress.

**Comment by Piinks** [comment]
I think this issue can be resolved now, thanks to @andreidiaconu! 🎉 
Are there any outstanding features here that have not been implemented?

**Comment by aoatmon** [comment]
> I think this issue can be resolved now, thanks to @andreidiaconu! 🎉
> Are there any outstanding features here that have not been implemented?

Hi @Piinks 
it would be nice to have some documentation on how to implement these new features

**Comment by andreidiaconu** [comment]
I agree and have planned for a new entry on flutter.dev dedicated to
foldables.

**Comment by Piinks** [comment]
Silly bot. 😜

**Comment by goderbauer** [comment]
I am going to close this on since it is kind of a catch-all bug. Please file individual bugs for specific features/doc requests.
