### ISSUE TITLE
Flutter with SunMi printer

### ISSUE THREAD

**Issue by joven1987** [flutter/flutter#49413]
Hi, I am trying to use this framework to communicate with SunMi mobile printer. I want to invoke the printer using AIDL as one of the ways to communicate with the printer but i don't know how and where to place the AIDL files in flutter or is it even possible to use flutter in my case. I need to know if it is possible to communicate with the printer using its AIDL. I hope you can answer me very soon for I am opting to use flutter or android studio with java for my application. 

Thank you.

**Comment by dnfield** [comment]
This would be a better question for a site like StackOverflow.  

As a hint, it sounds like you'd want to create a plugin for communicating with the Printer.  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

**Comment by projected5000** [comment]
Did you integrated SunMi printer using flutter?
