### ISSUE TITLE
Flutter Cache issues

### ISSUE THREAD

**Issue by DBSumation** [flutter/flutter#49424]
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Android SDK built for x86...
I/flutter ( 5434): {"GLDI":{"stats":{"week52change":0.061916,"week52high":9.49,"week52low":8.31,"marketcap":null,"employees":null,"day200MovingAvg":8.94,"day50MovingAvg":8.96,"float":null,"avg10Volume":13496.6,"avg30Volume":14667.57,"ttmEPS":null,"ttmDividendRate":null,"companyName":"Credit Suisse X-Links Gold Shares Covered Call ETN","sharesOutstanding":0,"maxChangePercent":-0.5471,"year5ChangePercent":-0.2734,"year2ChangePercent":-0.012,"year1ChangePercent":0.0619,"ytdChangePercent":0.0011,"month6ChangePercent":0.0156,"month3ChangePercent":-0.0011,"month1ChangePercent":0.0168,"day30ChangePercent":0.0283,"day5ChangePercent":0,"nextDividendDate":null,"dividendYield":null,"nextEarningsDate":null,"exDividendDate":null,"peRatio":null,"beta":-0.19418934698709966},"quote":{"symbol":"GLDI","companyName":"Credit Suisse X-Links Gold Shares Covered Call ETN","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":9.09,"latestSource":"Close","la
I/flutter ( 5434): 71

Flutter doctor:
===========

> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

• No issues found!
![image](https://user-images.githubusercontent.com/37802537/73070625-bd3e4e80-3e7e-11ea-8bfc-5b2acd07e34f.png)

Seems like a cache issue, 2 stocks quotes are showing up when they were removed from the URL:

![image](https://user-images.githubusercontent.com/37802537/73070846-5a00ec00-3e7f-11ea-8e79-5f43de01ba87.png)

API url:
  await client.get('https://cloud.iexapis.com/stable/stock/market/batch?symbols=**SPFF,CNPF,ICOL,PGX,MORL,EMLC,GYLD,IPFF,SMB,YDIV,YYY,PEY,PGF,SNLN,DVHL,AUNZ,MDIV,PHB,PFXF,FPE,TIPX,MLN,SDIV,SIPE,SEMF,EMAG,IEMF,EU,BSCM,LEMF,BSCL,BSCK,BSCJ,BSCI,DSU

Would you happen to know why is this occurring ?  I have deleted "GLDI" and 

![image](https://user-images.githubusercontent.com/37802537/73071587-2626c600-3e81-11ea-890a-f3ff5dd31b97.png)

**Comment by DBSumation** [comment]
If I retrieve the URL I see the correct output in the browser. 
![image](https://user-images.githubusercontent.com/37802537/73072994-5b80e300-3e84-11ea-904d-81b5e2d316a1.png)

**Comment by VladyslavBondarenko** [comment]
Hi @DBSumation 
Did you do hot reload after changing your code?

**Comment by DBSumation** [comment]
> Hi @DBSumation
> Did you do hot reload after changing your code?
> (I'm simply wondering how described case could be possible)

stop, reloaded, restart computer, this has been happening for a couple of weeks, updates are made in the computer and IDE is update.

**Comment by DBSumation** [comment]
So far:
=====

1. - Tools / Android / AVD Manager
2. - Select the device to clear cache
3. - Click on the small arrow at the right
4. - Wipe data
=========
select 'File > Invalidate Caches / Restart' and then click the 'Invalidate and Restart' button.
=========
No luck, same issue.

**Comment by DBSumation** [comment]
I had to create a new project and paste the code. 
![image](https://user-images.githubusercontent.com/37802537/73123326-ecc38880-3f5c-11ea-92a1-78a371201d4a.png)

> 
Initializing hot reload...
Syncing files to device iPhone 11 Pro Max...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building PhotosList(dirty, state: _PhotosListState#cbbdb):
'package:flutter/src/material/data_table.dart': Failed assertion: line 282 pos 15: '!rows.any((DataRow row) => row.cells.length != columns.length)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  PhotosList file:///Users/ed/AndroidStudioProjects/flutter_dividends/lib/main.dart:80:17
When the exception was thrown, this was the stack: 
#2      new DataTable (package:flutter/src/material/data_table.dart:282:15)
#3      _PhotosListState.bodyData (package:flutter_dividends/main.dart:110:24)
#4      _PhotosListState.build (package:flutter_dividends/main.dart:106:12)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 586 libraries in 224ms.
flutter: {"ICOL":{"stats":{"week52change":0.08166499999999999,"week52high":14.25,"week52low":11.87,"marketcap":null,"employees":null,"day200MovingAvg":13.05,"day50MovingAvg":13.39,"float":null,"avg10Volume":9782.2,"avg30Volume":8943.3,"ttmEPS":null,"ttmDividendRate":0.4209,"companyName":"iShares MSCI Colombia ETF","sharesOutstanding":0,"maxChangePercent":-0.4417,"year5ChangePercent":-0.2258,"year2ChangePercent":-0.1671,"year1ChangePercent":0.081665,"ytdChangePercent":-0.034579,"month6ChangePercent":0.009309,"month3ChangePercent":0.020008,"month1ChangePercent":-0.028058,"day30ChangePercent":0.025038,"day5ChangePercent":-0.018882,"nextDividendDate":"2020-06-15","dividendYield":0.031154700222057734,"nextEarningsDate":null,"exDividendDate":"2019-12-30","peRatio":null,"beta":0.9014084993472731},"quote":{"symbol":"ICOL","companyName":"iShares MSCI Colombia ETF","primaryExchange":"NYSE Arca","calculationPrice":"close","open":13.38,"openTime":1579876200116,"close":13.51,"closeTime":1579899600083,"high"<…>
flutter: 71

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/material/data_table.dart': Failed assertion: line 282 pos 15: '!rows.any((DataRow row) => row.cells.length != columns.length)': is not true.
The relevant error-causing widget was: 
  PhotosList file:///Users/ed/AndroidStudioProjects/flutter_dividends/lib/main.dart:80:17
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by mraleph** [comment]
@DBSumation Have you tried running `flutter clean` in the old project? Did that resolve the issue?

**Comment by DBSumation** [comment]
Tried that.
Same issue :( 

flutter_app ed$ flutter clean
Cleaning Xcode workspace...                                         6.3s
EDs-MacBook-Pro:flutter_app ed$ flutter clean
Cleaning Xcode workspace...                                         5.3s
Deleting build...                                                  137ms
Deleting .dart_tool...                                               1ms
EDs-MacBook-Pro:flutter_app ed$
