### ISSUE TITLE
flutter_driver: Change locale of device/app at runtime

### ISSUE THREAD

**Issue by GarimaVats** [flutter/flutter#49425]
Hi All,

Can you please share code to change language device/app using flutter driver at run time.

Regards
Garima

**Comment by GarimaVats** [comment]
Any suggested solution?

**Comment by liupan163** [comment]
same question

**Comment by dnfield** [comment]
We're not really entertaining new feature requests for flutter_driver at this point. There are other ways to work around this, dependng on what you need and what platform you have to do it for.  For what it's worth, in your application itself you can probably just override the locale as part of the test. Or, if you're willing ot use Firebase testlab and package:integration_test, there are options to set the locale there as well: https://firebase.google.com/docs/test-lab/android/command-line

This specific question would be better asked on StackOverflow.
