### ISSUE TITLE
FlareActor is not visible on web with master channel

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#49429]
## Steps to Reproduce

1. Create an app, from the following repo and branch `example_for_testing_web_issue` (is also reproducible with other examples, for example `checkbox`): https://github.com/perclasson/Flare-Flutter/tree/example_for_testing_web_issue/example/simple
2. Run the app with Flutter for Web with the Flutter master channel
3. The Flutter flare actor does not show up.

It works fine on the beta channel for web, and also master for iOS or any other platform. That is why I am creating this issue on flutter/flutter **rather than the Flare repository**.

## Possible issue causing the regression
From running `git bisect` it seems like this issue was introduced in an the engine roll:
https://github.com/flutter/flutter/commit/846dce92ffb1012fd6e4b362d089021eb729cc1a

From looking at the PRs submitted in the roll, I suspect that this is related to either:
https://github.com/flutter/engine/pull/15153

Possibly also:
https://github.com/flutter/engine/pull/15160

## Flutter doctor
```
[✓] Flutter (Channel master, v1.14.4-pre.45, on Mac OS X 10.15.2 19C57, locale en-DE)
    • Flutter version 1.14.4-pre.45 at /Users/perc/development/flutter
    • Framework revision 92cbaa3efe (12 hours ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available)
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.130
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

## Related issue
https://github.com/material-components/material-components-flutter-gallery/issues/528

**Comment by jason-simmons** [comment]
Confirmed that the Flare example app works if https://github.com/flutter/engine/commit/27a221d6d07a7d87a90157d9593649aee76e76b4 is reverted

@ferhatb

**Comment by ferhatb** [comment]
Update: we reproduced and fixed issue. Adding regression tests. Fix should land shortly.

**Comment by ferhatb** [comment]
Rolled into flutter master channel.
