### ISSUE TITLE
path_provider 1.5.1 uses depricated api

### ISSUE THREAD

**Issue by dmcduck** [flutter/flutter#49423]
I just started getting the following when running my project using path_provider:

Note: C:\LocalEXE\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/36014

@dmcduck 
Are you experiencing the problem after https://github.com/flutter/flutter/issues/36014#issuecomment-524959958 ?

**Comment by dmcduck** [comment]
I am brand new to flutter development and only started using this last
week.  I'm using Sqflite.

**Comment by VladyslavBondarenko** [comment]
@dmcduck 
I mean do you have the problem after you change `minSdkVersion` to 23 in your `android/app/build.gradle` file?
Or what the version do you have now?

**Comment by dmcduck** [comment]
Changing the minSdkVersion did make that error go away.  Thank you.
