### ISSUE TITLE
How check display on phone is Amoled?

### ISSUE THREAD

**Issue by rovecode** [flutter/flutter#49427]
How check display on phone is Amoled?

**Comment by ingective** [comment]
I need this, I think, like many for a dark topic, because **amoled** has a very **good black color**, which can’t be said about the **ips** matrix and therefore I need this

**Comment by gaaclarke** [comment]
You should just author a plugin to give you that information.  Here is documentation on how to do that: https://flutter.dev/docs/development/packages-and-plugins/developing-packages
