### ISSUE TITLE
Android overscroll indicator is causing a reload/repaint

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#4944]
## Steps to Reproduce
1. Use Block to render a scrollable page.
2. The first time top or bottom is reached, observe that the content is reloaded.
3. Second and subsequent times the overscroll indicator is shown correctly.

Problem does not occur if we manually switch off the overscroll indicator (or switch to the iOS bounce indicator).
## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Framework revision 9c0c0225a6 (3 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-123992248-123972143)

**Comment by mehmetf** [comment]
@eseidelGoogle This is the issue we saw when we were debugging the card performance problem.

**Comment by eseidelGoogle** [comment]
@Hixie @HansMuller.  Seems like one of many bugs in our current overscroll behavior.

**Comment by mehmetf** [comment]
I have not seen this happen for a while. It seems that it has been fixed.
