### ISSUE TITLE
Implement Material NavigationRail

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#49453]
The [material.io guidelines](https://material.io/components/navigation-rail/) recently published a Navigator Rail component and for Flutter it says "Planned". Is there any further information for when this will be implemented? I'm working on my own locally in the mean time but it would be great for more information.

**Comment by dnfield** [comment]
I've slightly modified the title to phrase this as a feature request rather than a question :)

Someone more active in the Material area might know about plans for this.

**Comment by clocksmith** [comment]
This is coming soon. Probably within the next 1-2 weeks

**Comment by Reprevise** [comment]
Will there be an expanded form, kind of like a sidebar for web and tablet displays (essentially a drawer that's always out)?

**Comment by clocksmith** [comment]
No, the expanded form can be accomplished with a navigation drawer. There is a section on it here: https://material.io/components/navigation-rail/#behavior

**Comment by Reprevise** [comment]
Sure but with a drawer you need to press a button for it to open and then it closes. I'm talking about a sidebar like sites like Gmail has. That cannot be accomplished with a navigation rail? Or atleast with the Scaffold widget?

**Comment by perclasson** [comment]
@Reprevise That can be achieved with having a Row of Drawer and Scaffold. See the starter study inside of Gallery:
https://github.com/flutter/samples/blob/master/gallery/gallery/lib/studies/starter/home.dart#L58

**Comment by Reprevise** [comment]
@perclasson Hm, doesnt seem that elegant but it gets the job done. I'm trying to create a system like the Reply Material case study where it collapses and that's why I was interested in the Navigation Rail.

**Comment by clocksmith** [comment]
This looks like something we should investigate further. Could you please open a separate feature request for transitioning between the rail and the drawer (like in Reply)? Let's leave this issue for the existence of the Navigation Rail

**Comment by preconception** [comment]
https://pub.dev/packages/navigation_rail

**Comment by jesusrp98** [comment]
@clocksmith I dont get why implement another 'navigation item', in this case called `NavigationRailDestination`, when using the already existing `BottomNavigationBarItem` was far easier for all of us.

Maybe creating a single class called `NavigationItem`, which would feature the best properties from both classes.

**Comment by clocksmith** [comment]
@jesusrp98 I agree with you that they should be the same name. This name was chosen, however, in order to match the semantics of https://material.io/components/navigation-rail#anatomy , and without making a breaking change.

**Comment by jesusrp98** [comment]
@clocksmith Yeah, I know. But it would be nice to make the `NavigationRailDestination` and the `BottomNavigationBarItem` compatible, in oder to facilitate the build of responsive apps. Maybe make them extend a base 'Navigation Item', since both have similar properties.

You can see the problem [here](https://github.com/flutter/samples/blob/master/experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart). You can't reuse your navigation items for `BottomNavigationBar` and `NavigationRail`.
