### ISSUE TITLE
Fix flaky CountdownLatch.canWait test on Fuchsia and re-enable.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49457]
Latest example is https://chromium-swarm.appspot.com/task?id=49f28f15a2137210 but I've seen it before in the last couple days.

@gw280 @iskakaushik @chinmaygarde

**Comment by chinmaygarde** [comment]
The test has been disabled for now.

**Comment by chinmaygarde** [comment]
We should probably revert the disable PR and try again. This synchornization utility is using bog standard libcxx stuff.

**Comment by zanderso** [comment]
Flaky issue triage: @dnfield is planning to open a PR to re-enable. /cc @arbreng
