### ISSUE TITLE
Provide the required ssh config needed to drive flutter driver test on Fuchsia

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#49466]
To run flutter driver tests on Fuchsia we need to wither have the `FUCHSIA_BUILD_DIR` or `FUCHSIA_SSH_CONFIG` file. Since we only have access to the SDK, we can not really have the build directory. Hence the need for tooling to generate the ssh_config file. An example is:

Inputs:
1. location to the private key.
2. path to the generated config file.

Output:

Generate a file like:

```
Host *
  CheckHostIP no
  StrictHostKeyChecking no
  ForwardAgent no
  ForwardX11 no
  GSSAPIDelegateCredentials no
  UserKnownHostsFile /dev/null
  User fuchsia
  IdentitiesOnly yes
  IdentityFile <path/to/.ssh/pkey>
  ControlPersist yes
  ControlMaster auto
  ControlPath /tmp/fuchsia--%r@%h:%p
  ConnectTimeout 10
  ServerAliveInterval 1
  ServerAliveCountMax 10
  LogLevel ERROR
```

**Comment by iskakaushik** [comment]
cc: @blasten

**Comment by godofredoc** [comment]
If this is to enable the tests in luci the test beds are already provisioned with the private key and fuchsia_ctl can generate the authorized_keys at paving time.

**Comment by godofredoc** [comment]
This is already done in the runner script.
