### ISSUE TITLE
Firebase Messaging

### ISSUE THREAD

**Issue by mahes-waran** [flutter/flutter#49477]
Hi,
   I want sequence of messages + cascading under 1 name same as whatsApp.I have used Flutter 1.12.13+hotfix.5 channel stable and firebase_messaging: ^6.0.9.please help me.
![notifications](https://user-images.githubusercontent.com/38493896/73120513-01bc0e00-3f95-11ea-94a8-417f3000441b.PNG)

**Comment by VladyslavBondarenko** [comment]
Hi @mahes-waran 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/FirebaseExtended/flutterfire/issues/1736
I'm closing the current one as duplicate and not an issue with Flutter itself
If you disagree please write in the comments and I will reopen it.
Thank you
