### ISSUE TITLE
Certain values for Card margin cause incorrect render boundaries for other widgets within the card

### ISSUE THREAD

**Issue by mhstoller** [flutter/flutter#49489]
## Steps to Reproduce

Setting a Card widget's margin property may result in incorrect boundaries for other elements within the card (seemingly by 1 pixel length). Using the code below if you uncomment the margin for the card element the rendering of the LinearGradient widget is off by ~ one pixel (ie. it does not cover the white image entirely). It can also occur at the bottom of the image as well but I was unable to reliably reproduce that. This occurs with certain margin values, not all of them (the Card widget's default value of 4.0 does not cause a rendering issue).

The rendering issue occurs at the intersection of the Card's red color, the white image and the black gradient. I've added a second image that highlights the area I'm referring to using a yellow rectangle. It's quite difficult to see in the screenshots, easier to see on a physical device.

**Expected results:** 
![image](https://user-images.githubusercontent.com/36415486/73127914-8018b000-3f95-11ea-9c92-5d8f8607e114.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/36415486/73127918-8870eb00-3f95-11ea-9a05-e27c92edc1d4.png)

![image](https://user-images.githubusercontent.com/36415486/73127980-6166e900-3f96-11ea-9612-a9a52c70b50d.png)

**Demo Code**
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            Card(
              color: Colors.red,
              clipBehavior: Clip.antiAlias,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
              elevation: 0,
              // margin: EdgeInsets.fromLTRB(3, 4, 4, 0),
              child: Padding(
                padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                child: AspectRatio(
                  aspectRatio: 1.51,
                  child: Padding(
                    padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                    child: ClipRRect(
                      clipBehavior: Clip.antiAlias,
                      borderRadius: BorderRadius.circular(10),
                      child: Stack(
                        children: <Widget>[
                          Image(
                              image: NetworkImage(
                                  'https://www.publicdomainpictures.net/download-picture.php?id=28763&check=40d0c7d2a335794339b3a2023655e58f')),
                          Align(
                            alignment: Alignment.bottomCenter,
                            child: Container(
                              height: 150,
                              width: double.infinity,
                              decoration: BoxDecoration(
                                gradient: LinearGradient(
                                  begin: Alignment.topCenter,
                                  end: Alignment.bottomCenter,
                                  colors: [
                                    Color.fromRGBO(0, 0, 0, 0.7),
                                    Colors.black
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
```

```
flutter analyze
Analyzing pagebuilder_bug...                                            
No issues found! (ran in 1.8s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/max/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/max/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/max/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.3)
    • Android Studio at /home/max/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • ONEPLUS A6003 • cfb9d38d • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
Hi @mhstoller,
I am unable to replicate this issue on latest dev channel. Tested the demo code on Samsung S10 (OS 10) and on Android 8 devices, but didn't see the margins being rendered incorrectly. 

![49489_1](https://user-images.githubusercontent.com/67046386/86914895-ae9ed780-c13e-11ea-9531-04452f9e32f0.png)
![49489](https://user-images.githubusercontent.com/67046386/86914903-b0689b00-c13e-11ea-9dd7-e3609b1de6e9.png)

Can you please confirm if you still experience this issue on latest Flutter channel (eg : dev) ?

**Comment by mhstoller** [comment]
Yes the problem still occurs on Flutter 1.20.0-7.1.pre dev channel. When you uncomment the margin in the code the photo is 1 pixel left of the opacity overlay on my device (OnePlus 6).

If you change the card's margin to also have a right-hand margin of 3 as well `EdgeInsets.fromLTRB(3, 4, 3, 0)`, the image extends 1 pixel past the opacity overlay on the right as well.

**Comment by exaby73** [comment]
After adding the margin to the Card, I wasn't able to notice what you described.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/50555895/176436401-dcf789ed-ff1b-4011-81c7-ea553a382284.png">

I am closing this issue as fixed. Please comment if you disagree.
