### ISSUE TITLE
App start failed，FlutterEnginePluginRegistry: Attempted to register plugin

### ISSUE THREAD

**Issue by sqixin** [flutter/flutter#49481]
FlutterEnginePluginRegistry( 8192): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@f186fe1) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@8846106).
Report the above error, causing the project to fail to start

**Comment by kleberandrade** [comment]
I have the same problem after updating

**Comment by sqixin** [comment]
> I have the same problem after updating

I just updated the version, and then I couldn't start it. I don't know how to solve it now

**Comment by PeterHdd** [comment]
https://stackoverflow.com/questions/59908998/flutterenginepluginregistry-problem-to-register-plugin-firebase-in-flutter-app/59911050#59911050
