### ISSUE TITLE
Fluter Web- Hero animations are not respecting image size

### ISSUE THREAD

**Issue by athulantonynp** [flutter/flutter#49496]
Hero animations on flutter web is not respecting the size of image. When animation ends, the image is skewed or jumped to low size automatically.

Here is the minimal code snippet to reporduce the bug

`
```
import 'package:flutter/material.dart';

void main() => runApp(HeroApp());

class HeroApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Transition Demo',
      home: MainScreen(),
    );
  }
}

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        child: Hero(
          tag: 'imageHero',
          child: Image.network(
            'https://cdn.dribbble.com/users/1588659/screenshots/6212871/uplabs_1x.png',
            fit: BoxFit.fill,
          ),
        ),
        onTap: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) {
            return DetailScreen();
          }));
        },
      ),
    );
  }
}

class DetailScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        child: Center(
          child: Hero(
            tag: 'imageHero',
            child: Image.network(
              'https://cdn.dribbble.com/users/1588659/screenshots/6212871/uplabs_2x.png',
              fit: BoxFit.fill,
            ),
          ),
        ),
        onTap: () {
          Navigator.pop(context);
        },
      ),
    );
  }
}
```
`

And here is my ```flutter doctor -v```  log

```
[✓] Flutter (Channel beta, v1.13.6, on Linux, locale en_IN)
    • Flutter version 1.13.6 at /home/athul/flutter
    • Framework revision 659dc8129d (4 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    • Android SDK at /home/athul/Android/Sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/athul/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.5)
    • Android Studio at /home/athul/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

[](https://gifyu.com/image/qkRol)

**Comment by athulantonynp** [comment]
Any update on this issue?

**Comment by Malet** [comment]
@athulantonynp have you tried setting the `width` and `height` on the `Image`? I'm hitting the same issue with Image.memory - it works smoothly when the dimensions are fixed.

**Comment by athulantonynp** [comment]
How can I determine the width and height of the image loaded from network @Malet  It is unpredictable in my case.

**Comment by Malet** [comment]
From the `Image.network` docs:

> Either the [width] and [height] arguments should be specified, or the widget should be placed in a context that sets tight layout constraints. Otherwise, the image dimensions will change as the image is loaded, which will result in ugly layout changes.

The dimensions of the image are not known until the image is loaded, so there are a few options here:

1. Preload the image before displaying the hero animation - this will likely mean showing a spinner or some indication that the full image is loading the background, before triggering the navigation change.
2. Use the original 1x image as the placeholder, this will match the aspect ratio, and it'll just pop in at a higher resolution once loading is finished.
3. Clip the images to a fixed aspect ratio - and use something like `BoxFit.cover` or `BoxFit.contain` for the `fit:` parameter of your image.

**Comment by pedromassangocode** [comment]
Hi @athulantonynp 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`?
Would be great if you provide any visual image of the actual vs expected result.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
