### ISSUE TITLE
Not able to open database using sembast in flutter WEB

### ISSUE THREAD

**Issue by VarmaTech** [flutter/flutter#49494]
Please let me know what mistake i am making 

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.2-pre.54, on Mac OS X 10.15.2 19C57, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!`

**Comment by jonahwilliams** [comment]
Please file an issue on the sembast repo instead of flutter
