### ISSUE TITLE
method decodeImageFromList from dart:ui do crash when runned inside an isolate

### ISSUE THREAD

**Issue by mtiziano** [flutter/flutter#49510]
I have to manimulate multiple images as same time in flutter.
I'm trying to call the static function as **isolate**, but throws:

> Exception has occurred. NoSuchMethodError (NoSuchMethodError: The method 'instantiateImageCodec' was called on null.
> Receiver: null
> Tried calling: instantiateImageCodec(ExternalTypedData))
> 

    

      ....              

      func(filePath); // ✔ WORKS 

      compute(func, filePath); // ❌ CRASH

      static func(filePath) async {
          print('2----');
          print(PaintingBinding);
          print(PaintingBinding.instance); // <-- NULL IN ISOLATE
          Uint8List lst = File(filePath).readAsBytesSync();
          print('>> $lst');
          ui.Image image = await decodeImageFromList(lst); // <-- CRASH IN ISOLATE
          print('ok $image');
      }

      ....

<details>
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Versione 10.0.17763.973], locale it-IT)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
</details>

**Comment by dnfield** [comment]
This is expected.  You cannot run any dart:ui functions in separate isolates.
