### ISSUE TITLE
'crumb' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GangaPradeep** [flutter/flutter#49514]
## Steps to Reproduce

1. ...While creating a flutter project in Android Studio
2. ...While accessing flutter through Command Prompt
3. ...

## Logs

```
flutter doctor
```

```
'crumb' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
```

**Comment by VladyslavBondarenko** [comment]
Hi @GangaPradeep 
Add path to 'crumb' to the PATH environment variable

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by Shaikaslam340** [comment]
where do i can find the crumb location

**Comment by rajkamalnehul** [comment]
how to add path to crumb?

**Comment by Av3nger123** [comment]
Can you explain the whole process
