### ISSUE TITLE
Invalid extra padding appears on Arabic/Persian text in flutter

### ISSUE THREAD

**Issue by erfanegtfi** [flutter/flutter#49517]
Hi, when I use Arabic/Persian words in my text I see Invalid extra padding in my text,
Extra Padding has shown in image (blue background)

    `  Container(
              width: 100,
              color: Color(0x77ffffff),
              child: Column(
                mainAxisSize: MainAxisSize.max,
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Container(
                    color: Colors.blue,
                    child: Text(
                      "تجربه مصاحبه",
                      style: TextStyle(color: Colors.white, backgroundColor: Colors.cyan),
                    ),
                  ),
                  Text(
                    statistics.totalInterview.toString(),
                    style: TextStyle(color: Colors.white, fontSize: 16),
                  ),
                ],
              )),`

![Capture](https://user-images.githubusercontent.com/12550602/73141604-1b477d80-409b-11ea-8e28-603d750c5b83.PNG)

**Comment by dnfield** [comment]
Seems to be a result of displaying it in ltr direction instead of rtl - for example, if you do 

```dart
 Container(
          width: 100,
          color: Color(0x77ffffff),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Container(
                color: Colors.blue,
                child: Text(
                  "تجربه مصاحبه",
textDirection: TextDirection.rtl,
                  style: TextStyle(color: Colors.white, backgroundColor: Colors.cyan),
                ),
              ),
              Text(
                statistics.totalInterview.toString(),
                style: TextStyle(color: Colors.white, fontSize: 16),
              ),
            ],
          )),
```

the padding goes away.

**Comment by erfanegtfi** [comment]
Thank you, it works.
