### ISSUE TITLE
Image Cropping 

### ISSUE THREAD

**Issue by haroonkhan9426** [flutter/flutter#49528]
## Use case
There should also be an option to crop the image visually like the user selects a window and then fits it on the part of image he want to be cropped.

**Comment by dnfield** [comment]
Is there some reason to not use `package:image`? https://pub.dev/documentation/image/latest/image/copyCrop.html

**Comment by MichaelSowah** [comment]
I have used this in couple of my projects https://pub.dev/packages/image_crop and its turn out quite great and works well. there are others like this https://pub.dev/packages/simple_image_crop, https://pub.dev/packages/crop, https://pub.dev/packages/image_crop_widget, https://pub.dev/packages/flutter_native_image, https://pub.dev/packages/flutter_image_crop_plugin

**Comment by dnfield** [comment]
Given the availability of multiple packages for this, I'm not sure there's a need to support this in the framework.

Please feel free to ping the issue if there's something I'm missing.

**Comment by Herophes** [comment]
Hello can sombody help me please..

 I use package:image if I create an image all works fine. But if I use the copycrop function I get this Exception:
`
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following _Exception was thrown while resolving an image:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4304:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
#2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:714:18)
#4      MemoryImage.load (package:flutter/src/painting/image_provider.dart:706:14)
...
Image provider: MemoryImage(_Uint8ArrayView#61875, scale: 1.0)
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#63719(), devicePixelRatio: 4.0, locale: de_DE, textDirection: TextDirection.ltr, platform: android)
Image key: MemoryImage(_Uint8ArrayView#61875, scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
`

This is what I do:
`
    var tempStore = await ImagePicker.pickImage(source: ImageSource.camera);

    
    // Image Test

    List bytelist = tempStore.readAsBytesSync();

    image = dartImage.Image.fromBytes(100, 100, bytelist);

    cropImage = dartImage.copyCrop(dartImage.Image.from(image), 1, 0, 60, 60);
`

`
    Expanded(
                child: Container(

                    child: cropImage != null? Image.memory(cropImage.getBytes()) : Text('No Image'),
                  ),
              ),
`
