### ISSUE TITLE
══ Exception caught by widgets library ═══════════════════════════════════════════════════════ The following assertion was thrown building Movies(dirty, dependencies: [MediaQuery], state: _MoviesState#b0a5a): A non-null String must be provided to a Text widget. 'package:flutter/src/widgets/text.dart': Failed assertion: line 283 pos 4: 'data != null'

### ISSUE THREAD

**Issue by parag851** [flutter/flutter#49525]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @parag851 
Take a look at https://github.com/flutter/flutter/issues/40214#issuecomment-530587931
Closing, as duplicate and not an issue with Flutter itself
Thank you
