### ISSUE TITLE
Iphone X somehow is limiting frames ?

### ISSUE THREAD

**Issue by superhumang** [flutter/flutter#49532]
Hello guys, 
my issue is that iphone x seems to be limiting frames beyond 30!
is this purposely done? or is this a issue ?
all this limiting is demo-ed while navigating to screens
Please help 

thank you

<img width="1633" alt="Screenshot 2020-01-27 at 4 10 03 PM" src="https://user-images.githubusercontent.com/54345401/73168302-95214a80-411f-11ea-8b35-589b7b26839e.png">
<img width="627" alt="Screenshot 2020-01-27 at 4 08 38 PM" src="https://user-images.githubusercontent.com/54345401/73168303-95214a80-411f-11ea-985d-0e2b041558dd.png">

Doctor summary (to see all details, run flutter doctor -v):
⣽flutte[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)

**Comment by iapicca** [comment]
Hi @superhumang 
upgrade you version of flutter and
provide your updated `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you
