### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by 1950465971** [flutter/flutter#49548]
https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/pubspec.yaml
（https://raw.githubusercontent.com）这个路径找不到了，是改成其他地址了吗？

**Comment by VladyslavBondarenko** [comment]
Hi @1950465971 
May be [this](https://github.com/flutter/website/blob/master/examples/layout/lakes/interactive/pubspec.yaml) is what you are looking for
If you've found this broken link on some flutter resource, then provide link to it and I'll reopen the issue. We'll fix it, if we have access to it.
Thank you
