### ISSUE TITLE
TextField cursor skips spaces when pressing backspace

### ISSUE THREAD

**Issue by armeaux** [flutter/flutter#49550]
## Steps to Reproduce

Hi, I encountered a problem while writing a note taking app. For this app I used a CupertinoTextField to allow user input. To use more customised features _I edited the editable_text.dart file_. Everything worked fine, but after while I found a problem while pressing on backspace.

After pressing backspace several times I found out that the cursor skips spaces and positions itself before the space (that still exists). If backspace is tapped again, nothing changes and the cursor stays at the same place. (removing the space that was after it in the first place). 

When I noticed this I did some debugging, but I could not fix the problem. I changed the CupertinoTextField to TextField to see if anything changed - with no result. 

Afterwards I decided to revert the flutter files that I changed by running flutter upgrade (not sure if this was right), but after being unlucky again I just decided to download flutter again and replacing the flutter folder containing these packages. 

Again, I created a completely new flutter app, and I expected this behaviour to stop. It didn't 

I included a gif below which shows the problem.

![Uploading ezgif-7-6280801cc1b8.gif…]()

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/armeaux/Documents/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/armeaux/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Armin’s iPhone • 00008020-000A4CDE0241002E • ios • iOS 13.3
```

</details>

**Comment by armeaux** [comment]
![ezgif-7-6280801cc1b8](https://user-images.githubusercontent.com/24753532/73191025-2516c280-4127-11ea-988a-bf72d68c49f6.gif)

The GIF didnt upload the first time so here it is

**Comment by armeaux** [comment]
![ezgif-7-6a41e8f43540](https://user-images.githubusercontent.com/24753532/73191245-7626b680-4127-11ea-8e2e-f3f4c3602ecd.gif)

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/50033

**Comment by TahaTesser** [comment]
Hi @armeaux 
Are you still experiencing this issue latest stable?
if yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by hTopology** [comment]
I have the same issue
