### ISSUE TITLE
Use ❮ rather than ← on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4955]
Use ❮ rather than ← for the back button icon, when on iOS

**Comment by Hixie** [comment]
This is not a muscle memory issue, are we still sure we want to do it?

**Comment by sethladd** [comment]
Our users will want the ability to swap icons here. Not sure how easy that is today?

**Comment by sethladd** [comment]
Confirmed with designers that we should use the iOS-friendly back icon, when the app is running on iOS. We have access to this designer-approved icon internally, and we can use it in Flutter.

**Comment by cbracken** [comment]
Fixed by #6182
