### ISSUE TITLE
IOS Error generated

### ISSUE THREAD

**Issue by greatbaedee** [flutter/flutter#49556]
[screenshot](https://user-images.githubusercontent.com/11525976/73196625-89209300-40f5-11ea-8521-eacf8b9400d9.png
)
[screenshot](https://user-images.githubusercontent.com/11525976/73195195-0dbde200-40f3-11ea-8b59-e8e249307520.png)

Hey ya'll, how are ya'll doing? 
I made an app that runs smooth on android. I tested it on Iphones and it seems to work smoothly. The problem is whenever I tried to upload it to TestFlight so that other people can test the app, I kept getting error generated code. "path_provider", "sqflite", and "url_launcher". I don't use "path_provider" and "sqflite". I have run flutter doctor, flutter clean, pod repo update and pod install, and flutter package get to try to resolve this issue. I have created new apps thinking maybe its my codes and change my mac thinking that may resolve the issue, but nothing seems to be working.

Please I have been having this issue for about 3 weeks now any help is greatly accepted.

**Comment by iapicca** [comment]
Hi @greatbaedee  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by greatbaedee** [comment]
I have found a solution, thanks.

**Comment by iapicca** [comment]
Hi @greatbaedee 
I'm glad to hear that
thank you for letting me know
