### ISSUE TITLE
Setup `google_maps_flutter_utils` plugin.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#49566]
Set up a `google_maps_flutter_utils` with a minimum usable feature.

The plugin is a wrapper of https://github.com/googlemaps/google-maps-ios-utils and https://github.com/googlemaps/android-maps-utils

The plugin depends on `google_maps_flutter`.

In future, this plugin should support all features in https://github.com/googlemaps/google-maps-ios-utils and https://github.com/googlemaps/android-maps-utils

This issue is merely to track the effort of setting up the plugin. The effort of adding features should be tracked in different issues.

**Comment by KohlsAdrian** [comment]
3 of the main classes I have rewritten to dart, I wish it could help
https://pub.dev/packages/google_maps_utils

**Comment by cyanglaz** [comment]
Un-assign myself from this issue as I don't have cycle to actively working on it.

**Comment by alphabetek** [comment]
If I am not mistaken this issue is blocking at less one [open issue](https://github.com/flutter/plugins/pull/1480) related to google maps clustering feature.

**Comment by cyanglaz** [comment]
close as dup https://github.com/flutter/flutter/issues/49566, which has better description.

**Comment by renefloor** [comment]
> close as dup #49566, which has better description.

@cyanglaz You actually linked this issue, so that creates a loop :D
Did you mean #24689?

**Comment by cyanglaz** [comment]
> > close as dup #49566, which has better description.
> 
> @cyanglaz You actually linked this issue, so that creates a loop :D
> Did you mean #24689?

Thanks for pointing it out, I updated the original comment to the actual issue.
