### ISSUE TITLE
Kotlin Multiplatform

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#49564]
## Use case

Share some of the native code on Android/iOS using Kotlin Multiplatform.

## Proposal

flutter should be able to share the native code of the app on Android/iOS. That would flutter keep in line with "write once run everywhere".

**Comment by stuartmorgan** [comment]
Can you elaborate on what it is exactly you are proposing? What is currently preventing you from using Kotlin to implement parts of whatever native code you need? What specifically are you suggesting Flutter do to address that?

**Comment by jld3103** [comment]
I'd like to have a template or some sort of integration.
