### ISSUE TITLE
Default to San Francisco font for iOS 9

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4956]
iOS 9 introduced "San Francisco" font.

https://developer.apple.com/fonts/

**Comment by eseidelGoogle** [comment]
Sounds like a question for the Material Design team.

**Comment by sethladd** [comment]
Yup, on a doc with them.

**Comment by Hixie** [comment]
This is not a muscle memory issue, are we still sure we want to do it?

**Comment by sethladd** [comment]
Users will want an easy way to choose the system font. This is especially useful when the OS changes the default system font. Not sure how easy this is today? Maybe we just need to document how to opt-into the system font? Would they have to manually include the San Francisco font into their app?

**Comment by eseidelGoogle** [comment]
I don't know the licensing terms of San Francisco to know if they could include it or not.  However they can change the text in their root https://docs.flutter.io/flutter/material/TextTheme-class.html.  The question of this bug is if the Framework should automatically do that for them on iOS.

**Comment by sethladd** [comment]
Sorry, not clear how a developers would say "use the system font" in Flutter?

**Comment by sethladd** [comment]
Confirmed with designers that we should help developers default to San Francisco font when the app is running on iOS 9+.

**Comment by eseidelGoogle** [comment]
Is our ability to solve this affected by https://github.com/flutter/flutter/commit/b38ff603382aff69ab20205ee8c8fe11987825c9?

**Comment by abarth** [comment]
We continue to be able to resolve this issue regardless of b38ff60.  If you want this done earlier, you should move it to an earlier milestone.

**Comment by cbracken** [comment]
Fixed by #6634. We now use San Francisco on iOS 9 and up.

**Comment by eseidelGoogle** [comment]
Curious: What happens on iOS 8?  And do we always bundle Roboto into the .flx (even for iOS)?

**Comment by sethladd** [comment]
Hopefully we default to whatever the system font is? Unless otherwise explicitly configured.

**Comment by cbracken** [comment]
On iOS 8 we fallback to the platform default, which (IIRC) is Helvetica Neue. We do still bundle Roboto, but we no longer need to. I'll file a bug and take a look at making it non-default on iOS. I believe we've already got a separate config option for it flutter.yaml, it's just defaulted to the use-material default.

**Comment by sethladd** [comment]
Thanks Chris!

**Comment by lukepighetti** [comment]
I'm running Flutter on iOS 11.4 and it's not using San Fransisco. I have not specified a font. How do I resolve this?

**Comment by cbracken** [comment]
@lukepighetti you shouldn't need to specify a font to get San Francisco on iOS 9 or later. Which font are you seeing in its place?

**Comment by lukepighetti** [comment]
Hello, I was mistaken about the font. It appears to be using SF.

**Comment by cbracken** [comment]
@lukepighetti thanks for confirming!
