### ISSUE TITLE
Deprecate and replace build aot

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#49562]
Currently `flutter build aot` is designed with a large number of configurations to support integration into the iOS and Android build scripts. Now that this dependency is being removed, it will no longer be used by anything within the flutter tree.

In the future, I would like it to be available for arbitrary 3rd party embedders to use, though that will require some significant refactoring.

In the meantime, I propose we delete the existing functionality and leave a placeholder.

cc @zanderso

**Comment by zanderso** [comment]
Can you link any issues here for work on removing `flutter build aot` from the iOS and Android build scripts?

**Comment by jonahwilliams** [comment]
iOS was moved to assemble in https://github.com/flutter/flutter/pull/49224
Android was moved to assemble in https://github.com/flutter/flutter/pull/43282

Android was later refactored into 100% assemble via https://github.com/flutter/flutter/pull/44534/files

**Comment by jmagman** [comment]
Once b/172093077 is resolved `flutter build aot` can be removed.

**Comment by jmagman** [comment]
Golem no longer uses `flutter build aot`.

**Comment by rrousselGit** [comment]
:wave:

Now that `flutter build aot` was removed, what is the alternative solution?

**Comment by Levi-Lesches** [comment]
I'm not sure what you were using this feature for but I think the point is that you no longer need it. 
Android: `flutter build apk`
iOS: `flutter build ios`
web: `flutter build web`

Were you using it in another context?

**Comment by rrousselGit** [comment]
https://github.com/FirebaseExtended/flutterfire used it as a mean to test that the examples compile as a CI step.   
`flutter build apk` works but is significantly slower

**Comment by passsy** [comment]
I also used it on CI to verify the dart code is compiling regardless on which platform it gets executed. I replaced it with `flutter build web` when supported because it builds the fastest. Still slower than `oat`.

Are the dart compilation errors I'm getting from `apk` and `web` 100% identical? (I think so because of the CFE)

**Comment by pigking12345** [comment]
Please update this doc: https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode
`build aot` is still used in it.

**Comment by jmagman** [comment]
@pigking12345 I created https://github.com/flutter/flutter/issues/79320.  Generally no one monitors closed issues.  Thanks for noticing it!
