### ISSUE TITLE
Black screen when running flutter in mojo after engine update

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#4957]
## Steps to Reproduce

Running a flutter app through mojo. After applying (flutter/flutter@aff8e30) I get a black screen.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

Black screen flutter:
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/mikejurka/code/sysui/src/third_party/flutter
    • Framework revision 94d1104429 (3 days ago), engine revision 2d6510295c

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mikejurka/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.29

Version that works ok:
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/mikejurka/code/sysui/src/third_party/flutter
    • Framework revision d33da2fadd (5 days ago), engine revision a21868833e

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mikejurka/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.29

## Logs and Crash Reports

No logs that point to any issues

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mikejurka** [comment]
Tried the latest version of the engine, still seeing a black screen:
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/mikejurka/code/sysui/src/third_party/flutter
    • Framework revision ebc7e4b7ec (18 hours ago), engine revision 3291edef41

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mikejurka/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.29




Reverting to the version of flutter using engine revision a21868833e still works ok.

**Comment by pylaligand** [comment]
What's the status of this issue?

**Comment by mikejurka** [comment]
I'm still seeing a black screen when running flutter on mojo.

[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/mikejurka/code/sysui/src/third_party/flutter
    • Framework revision 82b7fc0d95 (14 hours ago), engine revision 6320dd9077

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mikejurka/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.29

**Comment by mikejurka** [comment]
I tested on both linux and android.

On Android, you see a black screen.
On Linux, you see the window frame but nothing painted inside of it.

In the error logs, I'm seeing:
"[0802/112125:WARNING:platform_view.cc(141)] WARNING: Could not setup an OpenGL context on the resource loader."

Reverting flutter (Framework revision d33da2f (5 days ago), engine revision a21868833e) works normally

**Comment by chinmaygarde** [comment]
The warning is part of the patches that added asynchronous texture loading. Even in case of failure to setup the background texture loading context, texture loading should fallback to loading synchronously. I am testing again.

**Comment by mikejurka** [comment]
Ok, I think that warning is a red herring. We were getting the black screen even before seeing that message.

This regression was introduced in:
https://github.com/flutter/engine/commit/fe69b034c0ff5ee41b874c241fb02412b67e9195

Seems like lots of stuff about setting / changing context changed in that CL e.g. there were changes to sky/shell/platform/mojo/platform_view_mojo.cc and sky/shell/gpu/direct/ganesh_canvas.cc, among others. Not sure what exactly caused the issue, but it's pretty clear to me that the regression surfaced in that CL.

I can definitely show repro steps if you don't have them.

**Comment by abarth** [comment]
Sounds like we messed up the Mozart configuration when we changed the GL startup sequence.  @chinmaygarde Do you want to look at this regression or should I take a look?

**Comment by chinmaygarde** [comment]
@abarth Can you take a look please. I have verified that none of the rasterizer direct paths should affect the Mozart configurations.
