### ISSUE TITLE
Make FakePlatformWebView public

### ISSUE THREAD

**Issue by shouichi** [flutter/flutter#49584]
## Use case

When we want to unit test widgets using webview, we need fake webview. There is `FakePlatformWebView` class (and related classes) in the `flutter_webview`'s test package and we currently copied those classes for testing.

## Proposal

Adding something like `flutter_webview_testing` package and providing `FakePlatformWebView` and related classes.

**Comment by ashutoshgngwr** [comment]
Literally, copy-pasting classes as we speak. These classes should be publically available in a separate package.

**Comment by stuartmorgan** [comment]
If the fake were public, then any change to the fake's behavior would require a breaking change to the plugin; that would make it much harder to add and maintain tests.

For test fakes, maintaining your own copy that meets your specific test needs is the best option.
