### ISSUE TITLE
Scrolling "settling" after finger lift

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4958]
Check out the video here: https://www.youtube.com/watch?v=d0kZ5DJ58Nk&feature=youtu.be

Here, in the gallery, I'm gentling scrolling about 0.75 inches up or down (no fling) and then lifting my finger as perpendicularly as possible.

Expect: no further movement after I lift my finger.

Actual: Slight "settling" after I lift my finger.

**Comment by sethladd** [comment]
I'm seeing this on iOS. Testing on Android.

**Comment by eseidelGoogle** [comment]
FYI @Hixie (who is looking at another scrolling issue atm).

**Comment by Hixie** [comment]
I definitely see this. I would guess it's the same problem as the reversing fling (where you go fast in one direction but it goes the other way mysteriously).

My guess is that iOS gives us a different amount of data and we need a different velocity estimator.

**Comment by sethladd** [comment]
I still experience this on the home screen of the Gallery on iOS. Non-Flutter apps don't seem to have this level of sensitivity.

**Comment by eseidelGoogle** [comment]
This is very easy to see/test with Chinmay's demo btw.

**Comment by sethladd** [comment]
Still happening on latest build for iOS (maybe Android but I don't have that device with me)

See this video: https://youtu.be/NPWXOHHsFKY?t=21s

This breaks my muscle memory, because when I lift a finger after scrolling the list, I expect the scroll not to go backwards. :)

**Comment by sethladd** [comment]
cc @dragostis @HansMuller

**Comment by Hixie** [comment]
@HansMuller was this one of the things you worked on?

**Comment by sethladd** [comment]
I've been testing landscape today, and this is happening a lot. Makes testing hard, because when I lift my finger, the UI scrolls/moves backward. I have to be extremely careful when lifting my finger.

**Comment by Hixie** [comment]
iOS only?

**Comment by sethladd** [comment]
Android, too. Happy to shoot videos if that helps.

**Comment by Hixie** [comment]
Oh, interesting. If it happens on both platforms it's easier to debug, and is probably just a matter of increasing our constant which prevents this kind of thing.

**Comment by sethladd** [comment]
I can repro this on iOS simulator, so I'm less convinced that it's my finger creating subtle micro-scrolls on a device.

On the simulator:

Go to homescreen of gallery
Click mouse.
Drag up (or down, doesn't seem to matter)
Let go of mouse click.

Sometimes, not always, when the mouse button is released, the app will move on its own in the opposite direction of the mouse movement. (Move the mouse down, let go of button, the app will scroll up, and visa versa.) Not every time, but enough times where it's repro'able.

Hope that helps!

**Comment by Hixie** [comment]
That's so weird. We should instrument the velocity code and see what it's doing in these cases.

**Comment by elmcrest** [comment]
same for me on my iPhone 6S plus with current `master` branch, no "fling" scrolling at all. neither home screen or any other "scrollable".

```bash
$ git describe --tags
v0.0.20-alpha-3450-g0975d04
```

**Comment by sethladd** [comment]
Thanks for the feedback! Luckily, we can repro this in the simulator, which hopefully makes it easier to debug and fix.

**Comment by sethladd** [comment]
cc @cbracken

**Comment by sethladd** [comment]
Confirmed I make this happen on the Gallery on a Moto G4

**Comment by sethladd** [comment]
Still happening on iOS, with a fresh build. Scrolling up and down on the gallery home screen, nearly every time I lift my finger, the screen keeps moving, sometimes in the opposite direction.

@Hixie is the scrolling refactor intended to also fix this?

**Comment by Hixie** [comment]
no. I believe this is related to the velocity estimator.

**Comment by eseidelGoogle** [comment]
This might relate to an Android-specific report we just got from customer: leafy https://github.com/flutter/flutter/issues/7251

**Comment by Hixie** [comment]
Is this still an issue? I overheard someone saying recently that this was related to one of our constants being too low maybe? cc @HansMuller @abarth

**Comment by sethladd** [comment]
This still happens. Happy to show you tomorrow.

**Comment by xster** [comment]
Putting this in 2 for now. It's pretty important before we announce more widely but it's worth looking at API stability for the moment.

**Comment by HansMuller** [comment]
Seth and I just verified that this is still a problem on iOS.  It doesn't occur on Android.

**Comment by sethladd** [comment]
Very cool!

**Comment by sethladd** [comment]
Still happening on iOS.

**Comment by sethladd** [comment]
@xster have you been looking at this?

**Comment by xster** [comment]
@sethladd it's #12181 that we saw together last time was it?

**Comment by sethladd** [comment]
Ah, thanks! That's the one.
