### ISSUE TITLE
Incorrect semantic information for SliverAppBar

### ISSUE THREAD

**Issue by yuwen-yan** [flutter/flutter#49582]
Internal: b/148246052

With current implementation, we will set header to `true` for flexibleSpace if `title == null && flexibleSpace != null`
https://github.com/flutter/flutter/blob/bc5c46438ac6bac63bb872586c3edb84f4242384/packages/flutter/lib/src/material/app_bar.dart#L766

I think we should not make this assumption, and let developer decide which widget is header, for example:
```
SliverAppBar(
        title: null,
        ...
        flexibleSpace: FlexibleSpaceBar(
          background: Stack(
            fit: StackFit.expand,
            children: [
              Image(...),
              Semantics(
                header: true,
                child: AutoSizeText(
                  ''Title',
                ),
              ),
            ],
          ),
        ),
      ),
```
In this case we will have two header, and no way to remove the header label that added by the framework. of course, we can workaround by setting title with empty widget `const Text('')` or `const SizedBox.shrink()` , but I think we should also fix it on framework side.

**Comment by yuwen-yan** [comment]
kindly ping

**Comment by mehmetf** [comment]
@goderbauer as FYI.

I agree with you on this but my gut feeling is that it would be difficult to do this in a non-breaking way. There are many clients which rely on this behavior. It was filed as an issue: https://github.com/flutter/flutter/issues/16393.

One fix here would be to search the widget tree and only wrap with Semantics if there's no other header-enabled Semantics widget underneath. This is an expensive operation and makes the code complex.

**Comment by goderbauer** [comment]
This was implemented after feedback from an a11y review. If we would not do it, most developers would forget to mark something as a header making the experience for many a11y users much worse. I could see us providing a way to turn off the header semantics, but I don't think we should change the defaults.

**Comment by yuwen-yan** [comment]
thanks  mehmetf@ goderbauer@ !

`providing a way to turn off the header semantics` sgtm, do we plan to do it recently,  or I can pick up this task.
