### ISSUE TITLE
i18n Resource .arb file changes are not being shown on iOS simulator

### ISSUE THREAD

**Issue by dpedrinha** [flutter/flutter#49599]
I'm working on an app that was working fine a few days ago before I updated Flutter (Flutter (Channel master, v1.14.5-pre.35, on Mac OS X 10.15.2 19C57).
Now if I change strings on the .arb files they are not being shown on the app even if I uninstall the app on the device, do a `flutter clean` and `flutter run` again.
I haven't tried on a real device or Android yet.

## Steps to Reproduce

1. Open a resource .arb file, edit any string and save.
2. flutter clean -> flutter run
3. wait for the app to open on the simulator

**Expected results:** 
Strings should have changed.
**Actual results:** 
Strings didn't change.
<details>
  <summary>Logs</summary>

```
```

```
Analyzing myapp...                                     

   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The
          modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/main.dart:58:15 •
          deprecated_member_use
   info • Unused import: 'dart:io' • lib/views/passwordless_login_page.dart:7:8 • unused_import

2 issues found. (ran in 7.6s)
```

```
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
[✓] Flutter (Channel master, v1.14.5-pre.35, on Mac OS X 10.15.2 19C57, locale pt-BR)
    • Flutter version 1.14.5-pre.35 at /Users/daniel/dev/flutter
    • Framework revision 4fbb85e0c2 (2 days ago), 2020-01-25 15:34:37 -0500
    • Engine revision 6fa1fcda8f
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 74586F85-2090-49B9-AF45-CB397977B400 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by dpedrinha** [comment]
I confirmed it is not generating the generated.i18n file.
On Windows Android Studio it`s working and generating the file.

Here`s the flutter doctor from Android Studio on Windows.

`[√] Flutter (Channel master, v1.14.5-pre.39, on Microsoft Windows [Version 10.0.17763.973], locale pt-BR)
    • Flutter version 1.14.5-pre.39 at D:\DEV\flutter
    • Framework revision 477686ae17 (2 days ago), 2020-01-26 21:09:37 -0500
    • Engine revision 004cbdf066
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\dpedr\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.41.1)
    • VS Code at C:\Users\dpedr\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
`

**Comment by shihaohong** [comment]
After updating the arb file, what workflow are you currently using to generate your localizations delegates and Dart message files? Are you using the `intl` package to regenerate your localizations delegates and Dart message files, or something else?

**Comment by dpedrinha** [comment]
I just save the arb file.
I'm using the default Flutter i18n plugin.

**Comment by shihaohong** [comment]
Hmm, I'm not sure this is an issue with `flutter/flutter`. From what you're saying, it seems like it might be an issue with the i18n plugin you're using for your IDE. The Flutter team doesn't support any i18n IDE plugins officially as far as I know. Could you please check to see which specific plugin you're using and share it here?

**Comment by dpedrinha** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/L92XZww/i18n.png" alt="i18n" border="0"></a>

**Comment by dpedrinha** [comment]
Oh wow, now I just realized. That's why it's not working on Visual Studio Code.
My bad guys, sorry. I'll close it.

**Comment by shihaohong** [comment]
Yeah, that seems to be a plugin maintained by a 3rd party. 

No worries at all! Thanks for responding to my queries so quickly so we could figure out what's wrong :)
