### ISSUE TITLE
how we doing screen on/off during Proximity sensor on/off

### ISSUE THREAD

**Issue by parthdomadiay23** [flutter/flutter#49608]
How are we doing Screen on/off During proximity sensor on/off? in flutter android and ios app?

**Comment by SPlus91** [comment]
Is there a possibility to force the screen to stay on when the proximity sensors detects something?

**Comment by stuartmorgan** [comment]
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).
