### ISSUE TITLE
iOS FontWeight bold is not displayed

### ISSUE THREAD

**Issue by pamir72** [flutter/flutter#49600]
**After update Flutter to 1.14.5 font with bold weight (w500, w600...) is not displayed on iOS**

[✓] Flutter (Channel dev, v1.14.5, on Mac OS X 10.15.2 19C57, locale ru-RU)
    • Flutter version 1.14.5 at /Users/pavelmiheev/Flutter
    • Framework revision 92cbaa3efe (4 days ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pavelmiheev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 2937AD00-CFF7-419F-B596-A76D014C9819 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

To get issue run any application

**Comment by iapicca** [comment]
Hi @pamir72 
I see there's an open [issue](https://github.com/flutter/flutter/issues/49492) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
