### ISSUE TITLE
Update UI without use setState()

### ISSUE THREAD

**Issue by MohammadeMBi** [flutter/flutter#49610]
Hello,
How can I update my UI without using setState() function?
 I have a one WebView and a CircularProgressIndicator widget.
 When i use setState() in webviews onPageFinished function, url reloaded in infinite loop.

**Comment by VladyslavBondarenko** [comment]
Hi @MohammadeMBi 
I answered to you here https://github.com/flutter/flutter/issues/49540#issuecomment-579236629
I think you don't need to avoid using setState()
Closing current issue
If you disagree please write in the comments and I will reopen it. 
Thank you
