### ISSUE TITLE
Playstore, Shared Prefs, file is stores in appbundle

### ISSUE THREAD

**Issue by Marco-Bronner** [flutter/flutter#49615]
#Steps to Reproduce

I find it difficult to reproduce as this is more of a behaviour I would not expect. Obviously this is the definition of a bug but this is different.
I will skip most of the logging as this may be some konfiguration I just overread.

This is what happens:
When I upload my appbundle to the playstore and download afterwards the app from my page the newly downloaded apk includes a shared_preferences file. My app uses this file to store not only settings but also user informations here. I uploaded another Version of my app with alot of debug log and managed to confirm this fact as I was able to output a user ID which is from a test account I deleted. 
I thought shared_prefs would be individual for each device.

When I start the app via android studio the shared_prefs file is not present so I downloaded buildtool which was described as the tool that the playstore uses to build apks from the appbundle. But even with this tool no shared_prefs file seems to be delivered only when downloading the app from the playstore.

Is there some configuration in playstore I am missing or something else you may now, please let me know. 
As of any version questions: I have installed the latest stable version for every plugin/flutter

**Comment by Zazo032** [comment]
This is probably because your phone backed up that shared preferences file into your Google account, so if you download that app using the same Google account that has the back up, you will also download that file. If you want to erase it, you have to erase your app's data.

This is not related to Flutter.

**Comment by VladyslavBondarenko** [comment]
Thanks @Zazo032 !
Yes, @Marco-Bronner , does erasing your app's data in your phone settings solve the problem?

**Comment by Marco-Bronner** [comment]
Hello @Zazo032 
Thanks for your reply. This "problem" not only occurs on my phone but on multiple devices, even phones that never had the app installed before.
When I erase the local data from the app, uninstall and install again from playstore the shared-prefs file is also recreated. This makes me thinking it is somehow saved in playstore or in the appbundle I am not sure.
For all "users" or testers it is the same content in the file in the file, but I do not find these strings in my codebase (the string I am talking about is a auto generated user id which is stored in the shared-prefs file), so it is not added from my code by mistake.

(It would be great if I could disable backup files for my app completely as there is no code callback function to cleanup local storage when the app gets uninstalled.)

**Comment by stuartmorgan** [comment]
The plugin simply writes data to the Android app-private preferences store. If you have an instance where you believe that data is syncing in way you do not expect, you'll need to file and Android bug.
