### ISSUE TITLE
During hot reload English characters are not being registered after inputting Arabic character

### ISSUE THREAD

**Issue by almodoen** [flutter/flutter#49621]
when we run flutter using the command line in visual studio code or another code editor , we need to press (R for restart or r for hot-reload or q or etc...) , there is a small problem ..

my keyboard are English & Arabic , when i press r to make hot-reload and i am using the arabic language it do nothing and when i change the language to english after i pressed the arabic letter it do nothing too , because the console has received my arabic letter , and don't understand my english letter after it ...

i have to press CTRL+C to terminate the debug session and re-run the flutter run --verbose again ..

so , please make the console reject any Char or letter if flutter is in run mode and only accept the known chars or letters like (R,r,q,etc..) ..

i hope you understand :)

**Comment by jmagman** [comment]
I tried this on my Mac and the English characters registered after the Arabic ones.  Someone might need to try to reproduce on Windows.

**Comment by almodoen** [comment]
also when i press CTRL+C .. it request a confirmation like this: Terminate batch job (Y/N)?

if i press any other letter/Char .. it re-request the confirmation (and this is good :+1:)

the problem: if i press (N) it exit and terminate the session too ..

so fix it , if we press n/N just back to the default mode (that make us use R,r,q,etc ..)

thanks to all.

**Comment by exaby73** [comment]
Since this issue is not reproducible, I am closing this as fixed. If you disagree, please comment and we can reopen it. Thank you
