### ISSUE TITLE
fontWeight: FontWeight.bold` and `fontWeight: FontWeight.w700` are not work on latest master when using '.SF Pro Display' font family.

### ISSUE THREAD

**Issue by gliese667c** [flutter/flutter#49624]
## Steps to Reproduce

1. `fontWeight: FontWeight.bold` and `fontWeight: FontWeight.w700` are not work on latest master when using '.SF Pro Display' font family on iOS physical device and simulator.

**Expected results:**  Bold

**Actual results:**  Not Bold

**Comment by pamir72** [comment]
#49492

**Comment by VladyslavBondarenko** [comment]
Thanks @pamir72 ,
@gliese667c
Please follow up on https://github.com/flutter/flutter/issues/49492
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
