### ISSUE TITLE
Run custom script on launch.json

### ISSUE THREAD

**Issue by cytryn** [flutter/flutter#49633]
## Use case

The issue I currently have is that I wanna setup the correct Firebase Google-Services files for iOS and Android to locally test different environments. I have 3 different Firebase projects for that so I have 3 different files for iOS and 3 for Android.

Instead of changing the files on a copy paste basis it would be nice to have an option to run a command like `flutter run --env dev` or `flutter run --end prod` that would run specific scripts for each environment.

In my case the script in question looks like:
```
cat <<EOT > ios/Runner/GoogleService-Info.plist
(my .plist content here)
EOT

cat <<EOT > android/app/google-services.json
(my .json content here)
EOT
```

## Proposal

I would suggest that something could be added to the `launch.json` file under the `configurations` array.

```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "pre-build-script": "my-custom-prescript.sh"
        }
    ] 
```

## Current solution

For now I am doing the other way around, I created a script that runs the setup I need and then runs `flutter run` command.
But I don't think thats maintainable in the long run with new devs joining the team.

**Comment by VladyslavBondarenko** [comment]
Hi @cytryn 
I see there's an issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/26638
Also https://github.com/flutter/flutter/issues/18377#issuecomment-415799474 is some another workaround
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by cytryn** [comment]
Thanks @VladyslavBondarenko for clarifying! I will follow up on the other issues.
