### ISSUE TITLE
[Devicelab] microbenchmarks_ios timeout on iOS 13

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#49635]
I have recently observed several cases where microbenchmarks_ios timeout on iOS 13 devices, while it passes on iOS 12 devices. Not sure if this is a known issue.

Here's a sample log.
```
020-01-28T10:51:10.636647: [   +1 ms] h Repeat this help message.
2020-01-28T10:51:10.636891: [        ] q Quit (terminate the application on the device).
2020-01-28T10:51:10.636951: [        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:1024/7VmJyFJ-px8=/
2020-01-28T11:18:16.517932: Task timed out in framework.dart after 0:30:00.000000.
Cleaning up after task...
2020-01-28T11:18:17.529238: Force-quitting process:
command : /Users/flutter/.cocoon/flutter/bin/flutter run -v --profile -d 0f13aa3f7f48d3fa92ab08691369138b0a4b7153 lib/geometry/matrix_utils_transform_bench.dart
  started : 2020-01-28 10:50:40.025416
  pid     : 89095
2020-01-28T11:18:17.532867: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: -15
2020-01-28T11:18:17.535870: Task failed: flutter run failed: exit code=-15

```

/cc @liyuqian @dnfield

**Comment by dnfield** [comment]
Does it reproduce locally on an iOS 13 device?

If so, can we try getting more output from Xcode?

**Comment by digiter** [comment]
One problem found: in `dev/benchmarks/microbenchmarks`, run `../../../bin/flutter run --profile lib/geometry/matrix_utils_transform_bench.dart`, although the application launched on the phone, the main function never executes. It just hangs.

```
$ ../../../bin/flutter run --profile lib/geometry/matrix_utils_transform_bench.dart 
Launching lib/geometry/matrix_utils_transform_bench.dart on iPhone in profile mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
Running Xcode build...                                                  
 ├─Building Dart code...                                    11.1s
 ├─Assembling Flutter resources...                           1.1s
 └─Compiling, linking and signing...                         2.4s
Xcode build done.                                           16.3s
Installing and launching...                                        18.2s

Flutter run key commands.
h Repeat this help message.
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:1026/Jbi87vqto3s=/

```

**Comment by digiter** [comment]
@dnfield Yes, it reproduces on an iOS 13 device, see above comment. I don't see more output from Xcode, it seems the application just hangs before running the main function. /cc @Hixie

**Comment by dnfield** [comment]
Hmm.

I think it's actually running but we're just missing the logs.  There's an issue with iOS 13 where connecting to the observatory takes long enough that we miss initial early logs.  /cc @christopherfujino @jmagman - any ideas on that?

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/44717 ?
https://github.com/flutter/flutter/issues/44718#issuecomment-553189119

**Comment by keyonghan** [comment]
@digiter please check the phone in devicelab. I think we hit similar issues during Christmas holiday week: https://github.com/flutter/flutter/issues/47149#issuecomment-570451440
It caused the task hang on ios 13 devices.

**Comment by digiter** [comment]
@keyonghan That's not the cause, I have turned on WiFi before this issue.

**Comment by godofredoc** [comment]
To remove flakiness on this test we are limiting the test to not run on catalina and do not use 13.3 devices

**Comment by godofredoc** [comment]
Closing as obsolete, we are moving in to 14.3/4 in a couple of weeks.
