### ISSUE TITLE
Transition between rail and drawer

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#49643]
## Use case

We need to be able to get the drawer out of the way and minimize it to a rail like how Gmail and many other apps do.

Extremely useful for web and monstrous tablets like the iPad Pro for that little extra screen space you'd get.

## Proposal

With the incoming Navigation Rail component (#49453), it would be great to be able to transfer between Drawer and Navigation Rail like in the [Reply Material Study](https://material.io/design/material-studies/reply.html#product-architecture).

![slide-out](https://user-images.githubusercontent.com/25782944/73306250-d5e59600-41e9-11ea-9292-4c5dfe33ee59.gif)

**Comment by clocksmith** [comment]
This is now possible with https://github.com/flutter/flutter/pull/49574. However, the extended state is not referred to as a drawer, which is a different component.
