### ISSUE TITLE
[web]: text is blurry depending on browser window size.

### ISSUE THREAD

**Issue by peterlauri** [flutter/flutter#49642]
This is basically the starter kit. Texts becomes blurry in different window sizes. Trying to resize, and it gets sharp, and then blurry again. Screenshot is Chrome Dev Tools with iPhone X.

Using normal window, and then resizing it slowly shows the change in resolution.

![image](https://user-images.githubusercontent.com/3514945/73306414-d8191600-4224-11ea-974a-329a73e810f0.png)

**Comment by jonahwilliams** [comment]
If you're on an older version (beta), then this was likely fixed the same as https://github.com/flutter/flutter/issues/32274

**Comment by peterlauri** [comment]
I did run flutter upgrade just now, and no updates on the beta channel.

There is a screen recording that can be found here that shows the problem: https://drive.google.com/file/d/1L_YeLx8yYgr-TP2haTZBjsCeok_8KvnQ/view?usp=sharing 

```
➜  flutter_poc git:(scorecard) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by peterlauri** [comment]
Commit c51059f84 is not yet in beta as it looks like...

**Comment by jonahwilliams** [comment]
Yes, this is the same issue. It is fixed on dev/master channels but we haven't done another beta release yet. Closing
