### ISSUE TITLE
[luci] flutter engine builds timing out

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#49646]
There is no clear indication why engine builds are timing out, we need to start the Flutter LUCI playbook to provide instructions on how to debug those issues.

https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/3249

This was actually caused by a timeout of one hour after triggering the tasks and the tasks having to wait ~50 minutes in the queue.

**Comment by godofredoc** [comment]
We need to create dashboards for task queue time in luci infra and add more capacity if needed.

**Comment by godofredoc** [comment]
@stuartmorgan FYI

**Comment by dnfield** [comment]
It seems very wrong that we're taking that long to schedule a build.

Can we just add more bots?

**Comment by godofredoc** [comment]
We added 10 more linux bots, we were on the limits because for linux we are using 1 + 4 extra drones.

I've been monitoring the tasks and they are back to less than 15 mins queue time in the worst case scenario.

**Comment by godofredoc** [comment]
CL for increasing collect timeout is now submitted
