### ISSUE TITLE
CupertinoAlertDialog allows empty actions

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#49660]
`CupertinoAlertDialog` should not allow a dialog with no actions to be created. 

An attempt has been made to disallow this with an assert:
https://github.com/flutter/flutter/blob/7f134d860d05e9deb2b965962637bdab12db414c/packages/flutter/lib/src/cupertino/dialog.dart#L134

but the `actions` parameter is initialized to a blank list:
https://github.com/flutter/flutter/blob/7f134d860d05e9deb2b965962637bdab12db414c/packages/flutter/lib/src/cupertino/dialog.dart#L129

The result is a dialog that cannot be dismissed:
![image](https://user-images.githubusercontent.com/2319867/73320862-958c1500-41f5-11ea-9cea-e05c5285cf94.png)

**Comment by alfredobs97** [comment]
this could be fixed if not initialize the action or if list assert check is not empty?

**Comment by hasnentai** [comment]
@xster I would like to work on this issue....can I?

**Comment by xster** [comment]
@hasnentai certainly, happy to take your pull request

**Comment by hasnentai** [comment]
@xster `CupertinoAlertDialog()` class does not contain any `@required` parameter and using default constructor leads to showing up the only backdrop as shown in the below image. Will be a good idea to add `@required ` for actions and content
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-13 at 01 16 09](https://user-images.githubusercontent.com/26821037/87255227-7da80500-c4a6-11ea-8960-0519a46f9390.png)
?

**Comment by hasnentai** [comment]
@xster Native behavior of IOS is showing "OK" by Default if no action is null.
I guess it will be a good idea to implement the same

**Comment by hasnentai** [comment]
@xster I have made PR.
This is my first PR so I might not be up to date.
Please review the PR :)

**Comment by LongCatIsLooong** [comment]
I think this is intended? Here's a screenshot of what `UIAlertController(title: "title", message: "message", preferredStyle: .alert)` looks like:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-29 at 14 31 08](https://user-images.githubusercontent.com/31859944/88855842-5476bc80-d1a8-11ea-87b9-f3458babc46b.png)
\cc @hasnentai

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
