### ISSUE TITLE
Error 105 received from application: Isolate must be runnable

### ISSUE THREAD

**Issue by Ramsharma1234** [flutter/flutter#49676]
Hi, 

I tried installing my app and it crashed with this error.
I'm working with **Android**
Here are my _flutter doctor_ logs:
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 64-bit edition (version 1.27.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by Ramsharma1234** [comment]
@ianloic

**Comment by iapicca** [comment]
Hi @Ramsharma1234   
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by Ramsharma1234** [comment]
_flutter doctor -v_ :

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android-studio\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android-studio\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Nexus 5X • 01aaa266186247a8 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

**Comment by Ramsharma1234** [comment]
To Reproduce : Just run the app and it is crashing at launch

**Comment by Ramsharma1234** [comment]
@zoechi

**Comment by iapicca** [comment]
Hi again @Ramsharma1234 
thanks for your doctor, did you downgrade version (`hotfix 7` vs `hotfix 5`)
could you please post your logs attaching it with a `.txt` file
thank you

**Comment by Ramsharma1234** [comment]
Hi @iapicca ,
 I resolved it. There was an issue that there were two splash screens.
Thanks for the help.

**Comment by AndrsDev** [comment]
@Ramsharma1234 How did you fix it? I'm still having this error

**Comment by AndrsDev** [comment]
Thank God git exists. I reviewed diff in commits and noticed when changed to flutter channel master,` ios/Runner.xcodeproj/project.pbxproj` got modified. I deleted all it's contents and replaced it with an old functional version. **Now bug is fixed.** 

It was a headache
