### ISSUE TITLE
CheckboxListTile add contentPadding

### ISSUE THREAD

**Issue by andres-jordan-iddeon** [flutter/flutter#49688]
## Use case

In the same way as in ListTile there is the contentPadding property to adjust the property of the internal padding add it in CheckBoxListTile.

## Proposal

Add the contentPadding property in CheckBoxListTile.

**Comment by awhitford** [comment]
I have a scenario where the [default padding](https://api.flutter.dev/flutter/material/ListTile/contentPadding.html) is too much and it causes my text to unnecessarily wrap.  If I had control over the `contentPadding`, this would be a trivial fix.

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue. We can expose the `contentPadding` property from the `ListTile` used in `CheckBoxListTile`.

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR, looking forward to reviews :)
