### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE

### ISSUE THREAD

**Issue by Xia000** [flutter/flutter#49682]
I/flutter ( 8560): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 8560): The following assertion was thrown while handling a gesture:
I/flutter ( 8560): 'package:firebase_auth/src/firebase_auth.dart': Failed assertion: line 174 pos 12: 'email != null':
I/flutter ( 8560): is not true.
I/flutter ( 8560):
I/flutter ( 8560): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8560): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8560): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8560):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8560):
I/flutter ( 8560): When the exception was thrown, this was the stack:

**Comment by Xia000** [comment]
how to fix it?

**Comment by VladyslavBondarenko** [comment]
Hi @Xia000 
Log tells that email shouldn't be null,
I know in log this repository was mentioned, but you better consider to create issue in the plugin's repository https://github.com/FirebaseExtended/flutterfire/issues with providing your `flutter doctor -v`
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
