### ISSUE TITLE
Error after updating flutter to recent stable version

### ISSUE THREAD

**Issue by gianalmada** [flutter/flutter#49683]
after updating my flutter stable version, when i run the project, i get this error :
'Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\...\build, but the tool couldn't find it.'. 
do anyone know how to fix this problem ?? sorry for my bad english. thanks

**Comment by VladyslavBondarenko** [comment]
Hi @gianalmada 
I see there's an issue addressing the case you described.
Please follow up https://github.com/flutter/flutter/issues/44796
Try different workarounds from there
You can also try solution from https://github.com/flutter/flutter/issues/45346#issuecomment-569254804
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by gianalmada** [comment]
oke thanks for your response, i will try your rekomendation
