### ISSUE TITLE
Selecting a text input after a number input does not switch the keyboard to text

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4970]
- Open the gallery
- Tap "text fields"
- Tap into the Phone Number
- Notice how the number keyboard pops up (yay!)
- Type some numbers
- Tap into the Name field

Expected:
- The keyboard switches to a text input mode

Actual:
- The keyboard stays in number input mode

Note: this behavior is only on iOS. On my Nexus 5X, I see the keyboard mode switching as I tap between input fields.

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by eseidelGoogle** [comment]
I just ran into this today in the Text input demo in the Gallery on iOS.  Click on the phone number field and then click on a text field and feel sad. :/

**Comment by eseidelGoogle** [comment]
customer: leafy reported this to me today when playing with the gallery.  They are adding a bunch of text fields in the next version of their app, but I don't yet know if they'll hit this.  Regardless we probably need to move this to sooner rather than later. :)

**Comment by cbracken** [comment]
Fixed by flutter/engine#3400
