### ISSUE TITLE
CustomPaint does not respect isComplex/willChange if painters are null

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#49700]
# Background and reproduction

One of our customer wants to use `CustomPaint` to trigger `RasterCache` by setting `isComplex = true, willChange = false` as below:
```
import 'package:flutter/material.dart';

class CostlyToRasterize extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(color: Colors.blue);
}

void main() => runApp(
      MaterialApp(
        title: 'RootView',
        checkerboardRasterCacheImages: true,
        home: PageView.builder(
          itemBuilder: (BuildContext _, int index) {
            return CustomPaint(
              isComplex: true,
              willChange: false,
              child: CostlyToRasterize(),
            );
          },
        ),
      ),
    );
```
(A more realistic app is available in [this gist](https://gist.github.com/liyuqian/8699bf9300ed2c749b4e69710ee43ef4).)

However, the `isComplex` isn't sent to engine and the raster cache isn't triggered as expected.

# Cause and solution

The root cause is the following snippet of code (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/custom_paint.dart#L571)
```
    if (_painter != null) {
      _paintWithPainter(context.canvas, offset, _painter);
      _setRasterCacheHints(context);
    }
```
which ignores the raster cache hints if painter is null.

To fix this, we could do either of the following:
1. Update our API doc to specify that raster cache hints are ignored if painters aren't provided. Hence the user needs to provide at least a dummy painter to trigger the raster cache hints.
2. Change our code to always `_setRasterCacheHints` no matter whether painter exists.

CC @Hixie and @goderbauer for suggestions about which solution should be adopted.

@ignatz: for the time being, you should be able to trigger the raster cache by providing a dummy painter like the following
```
import 'package:flutter/material.dart';

class CostlyToRasterize extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(color: Colors.blue);
}

void main() => runApp(
      MaterialApp(
        title: 'RootView',
        checkerboardRasterCacheImages: true,
        home: PageView.builder(
          itemBuilder: (BuildContext _, int index) {
            return CustomPaint(
              painter: EmptyPainter(),
              isComplex: true,
              willChange: false,
              child: CostlyToRasterize(),
            );
          },
        ),
      ),
    );

class EmptyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {}

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```

# Related issues

I also filed https://bugs.chromium.org/p/skia/issues/detail?id=9835 which hopes Skia to count gradient as complex by default.

**Comment by Hixie** [comment]
I don't mind setting the hints even if the painter is null.

**Comment by flar** [comment]
I believe that was by intent. The CustomPaint is about adding some rendering around a child. The properties are about what it does.

In looking for a way to wrap a widget with something that tells us that the child is complex and we should cache it, the code snippet is using CustomPaint for a purpose for which it is not intended and the implementation doesn't do what they are looking for because that wasn't its intended purpose.

This feels a bit like "my wrench has a flat area that can be used to hit nails with, but it is off center which makes it ineffective in transferring the momentum, so can you add mass to my wrench to balance its flat area for when I use it as a hammer?"

**Comment by liyuqian** [comment]
@Hixie : do you mind if we don't change the behavior, but just update the API doc to specify that null painters will ignore hints? Maybe we can also add an assert if hints are set while painters are null (which makes it a breaking change).

**Comment by Hixie** [comment]
I guess that's fine too. (What tests does it break?)

**Comment by liyuqian** [comment]
@Hixie : no existing tests inside `flutter/flutter/packages/flutter` are broken. I'll add the assert and send out the breaking change announcement.
