### ISSUE TITLE
Figure out how to use dg shadows performantly

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49705]
https://b.corp.google.com/issues/137954772.

cc @cbracken, to whom the internal issue is assigned.

**Comment by shyndman** [comment]
dg?

**Comment by cbracken** [comment]
Assigned to Skia team internally.

**Comment by Hixie** [comment]
@shyndman This is basically just a placeholder to remind us to help a team at Google with shadows. It's possible we should turn this into some documentation on the Web site though? Or in API docs?

**Comment by shyndman** [comment]
Ah, cool. Thanks for the info.

**Comment by cbracken** [comment]
The performance work here is on the internal team's plate, but we should document the implications of using Material elevation (which makes use of the relatively more performant `SkShadowUtils::DrawShadow`) as opposed to a decoration with gaussian blur.

Removing the TODAY label as the customer is unblocked.

**Comment by goderbauer** [comment]
Synced with @cbracken even with the change in priority there's no action to be taken on our side.

**Comment by liyuqian** [comment]
The internal issue has noted that `SkShadowUtils::DrawShadow` isn't much faster than simple blur. Maybe a raster cache solution such as https://github.com/flutter/flutter/issues/51515 will help more.

**Comment by goderbauer** [comment]
Closing since this is not an issue on the Flutter side.
