### ISSUE TITLE
Dashboard for Engine Sheriff Rolls

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#49711]
As a companion to being on sheriff duty for rolls, it would be nice to have one definitive place to keep track of all the responsibilities of the sheriff.

Some similar work has been done to by @jmagman here: https://flutter-dashboard.appspot.com/repository.html#/

I mentioned this to @CaseyHillers who has done similar work, mentioning my concern about hooking into Fuchsia.  He said that this may overlap with some of his other work and is willing to provide guidance.

The dashboard should show the following info:
 - Skia -> Engine roll status (last success, current status, link for more info)
 - Engine -> Flutter roll status (last success, current status, link for more info)
 - Flutter Framework Tree -> (last time green, current status, link for more info)
 - Flutter + Dart -> Fuchsia (last success, current status, link for more info)
 - name of current person on rotation.

Bonus:
 - Something that hints towards a performance regression in the benchmarks
 - Statistics on roll (ex running average of success vs failure)

More Info:
https://docs.google.com/document/d/1n4wkZSFSciGnq_tKHGaaVxp1Jamav2Wgmt6v_IOAoVI/edit#heading=h.c3sox5buba7o (Google internal)

**Comment by iskakaushik** [comment]
There are a couple of other things that this should track too:

### Fuchsia SDK/Toochain -> Flutter Engine roll status:

1. https://autoroll.skia.org/r/fuchsia-linux-sdk-flutter-engine?tab=status
2. https://autoroll.skia.org/r/fuchsia-linux-toolchain-flutter-engine?tab=status
3. https://autoroll.skia.org/r/fuchsia-mac-sdk-flutter-engine?tab=status
4. https://autoroll.skia.org/r/fuchsia-mac-toolchain-flutter-engine?tab=status

**Comment by CaseyHillers** [comment]
Looks like `https://autoroll.skia.org/r/{roller-name}/json/status` can be queried to get information, and returns the information from the past 10 rolls too.

Skia auto rollers have support for pub sub, so we should be able to just add that to the Cocoon GCP project.

**Comment by jmagman** [comment]
@CaseyHillers Don't reinvent the wheel, check out what's already on the dashboard:
https://github.com/flutter/cocoon/blob/17dda0d7bfa89ae83c2d1f15c64ce90272dc7876/app/lib/repository/models/skia_autoroll.dart#L35

Sounds like @gaaclarke wants that info plus g3 rolls in a less made-for-TV format, and now that Flutter for web is being used in multiple places, consider re-using or refactoring the existing models.

**Comment by gaaclarke** [comment]
https://github.com/gaaclarke/engine_sheriff Forked code from cocoon to make app/web flutter project.

**Comment by CaseyHillers** [comment]
Here's a quick demo I put together that can just be done in a spreadsheet. This was thrown together on my work account so it's only visible internally right now. Working on having the same features Aaron has.

https://docs.google.com/spreadsheets/d/1dp5ZzFsL-WtfgrMSMyd1Gca5ZgHYFS8ZXnuE-nNA770/edit?usp=sharing

**Comment by godofredoc** [comment]
@keyonghan maybe a good onboarding project for @nehalvpatel?

**Comment by keyonghan** [comment]
@gaaclarke @iskakaushik Is this still needed considering current engine sheriff workflow? I know different alerts have been setup, including rollers, perf regression, build failures, etc.
