### ISSUE TITLE
Flutter app fails to launch on Android emulator without gpu

### ISSUE THREAD

**Issue by kaiyuanw** [flutter/flutter#4972]
## Steps to Reproduce

Create an emulator and launch it by
$ emulator -avd name
Then run a sample flutter app by
$ flutter run -d id
and you will see the crash.

However, if gpu is available and turned on by
$ emulator -avd name -gpu on
it will work.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

## Logs and Crash Reports

Please attach any relevent logs or crash reports.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by sethladd** [comment]
How common is it to run the emulator without a GPU? Is that a normal thing?

**Comment by kaiyuanw** [comment]
That's a normal thing if you want to have integration testing on popular CI systems like Travis.  Cloud testing does not provide gpu and require the emulator to be headless.

**Comment by sethladd** [comment]
Great, thanks for the info. Makes sense.

cc @yjbanov for the cloud testing comment.

**Comment by yjbanov** [comment]
I'm investigating the option to run Flutter tests on existing cloud mobile testing solutions, such as [Firebase Test Lab](https://firebase.google.com/docs/test-lab/). To support testing in deviceless headless environments is not planned at the moment.

**Comment by eseidelGoogle** [comment]
@abarth and I discussed this offline.  It's reasonable to have us not crash when no GPU is found and simply log and disable raster.  That's what this bug is about.

**Comment by eseidelGoogle** [comment]
@jason-simmons Would you be willing to add the LOG(ERROR) and early return to:
https://github.com/flutter/engine/blob/fe69b034c0ff5ee41b874c241fb02412b67e9195/sky/shell/gpu/direct/ganesh_canvas.cc#L32
to make the no-GPU case not crash?  It's possible that's not quite the right location to disable rasterizing, @abarth would know.
