### ISSUE TITLE
[google_maps_flutter]provide builder class for LatLngBounds

### ISSUE THREAD

**Issue by RafaO** [flutter/flutter#49728]
I think it would be nice to have a way to enable the creation of a LatLngBounds object from a list of LatLng instances. That would make possible to get an area that includes all those instances of the LatLng points which could be used to present that area for example.

PR: https://github.com/flutter/plugins/pull/981

**Comment by stuartmorgan** [comment]
Given that this has only accumulated three votes in the last two years, and doesn't have to be implemented in the plugin, I'm going to go ahead and close this. I would encourage anyone interested in sharing an implementation of this to do so via a separate package.
