### ISSUE TITLE
Flutter works fine on iOS devices and Android emulators

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4973]
Our FAQ (and possibly other places in the website) say otherwise.

@qchong @sethladd

**Comment by sethladd** [comment]
Thanks for the note!

**Comment by qchong** [comment]
@chinmaygarde Can you please provide the instructions for how external developers can create and use their own provisioning profiles, since this is a prereq for running Flutter apps on iOS devices?

**Comment by sethladd** [comment]
We could update our FAQ before we fully document the provisioning profiles.
