### ISSUE TITLE
Wire up font subsetting for all platforms

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49730]
The tool has new assets to subset icon fonts, and new functionality is being added to the assets build target to use these tools to remove unneded icons from fonts.

Each platform needs to be wired in to use this - some are easy and will be done in the same pull request that adds functionality to the assets target, but others are blocked or in flux at the moment. 

- [x] iOS (blocked by making iOS use assemble completely - https://github.com/flutter/flutter/pull/49842) (fixed in #50224)
- [x] Android (#49737)
- [x] macOS (#49737)
- [x] Linux
- [x] Windows
~~[ ] Fuchsia~~
- [x] Web (does not emit a kernel file at present)

**Comment by jonahwilliams** [comment]
This is done for windows now by way of windows AOT support. Removing fuchsia from the list since we don't yet know how we will build fuchsia.

**Comment by jonahwilliams** [comment]
Err, that is "we should" remove fuchsia from the list.

**Comment by dnfield** [comment]
Don't we already build for Fucshia?  e.g. flutter run with a Fuchsia device attached?

**Comment by jonahwilliams** [comment]
there is no "distribution" of fuchsia applications though, so it doesn't really make sense to wire up release only features yet

**Comment by dnfield** [comment]
Ahhh ok, that makes sense.

**Comment by jonahwilliams** [comment]
This is completed, by way of AOT support for Linux
