### ISSUE TITLE
Skia Gold service access from LUCI

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#49749]
We currently set a `GOLD_SERVICE_ACCOUNT` env variable on Cirrus, which is used to authorize access to the Gold service in case a golden image is update.

I heard LUCI has access to this service, but I'm not sure if auth is done in a similar fashion or if we need to change the code to account for this environment. 

cc @Piinks

**Comment by Piinks** [comment]
The `goldctl` tool can authorize without a service account from the Luci environment. We can probably just add a `luciAuth` method to the `SkiaClient` class in addition to the existing `auth` method that uses the service account.

IIRC, `goldctl auth --work-dir $workDir --luci-env`

fyi @kjlubick :)

**Comment by kjlubick** [comment]
Yep, although I think it's just `--luci`, instead of `--luci-env`. We read the credentials out of the LUCI_CONTEXT environment variable when this is set

**Comment by Piinks** [comment]
See #49815 which will add a method to the skia client to authorize using luci. :)

**Comment by blasten** [comment]
@kjlubick Do you have an example call within an existing recipe on LUCI?

**Comment by kjlubick** [comment]
https://github.com/google/skia-buildbot/blob/bcd52175909b0200ef5f2635ddff50685d70c4b0/golden/puppeteer-tests/upload-screenshots-to-gold.py#L88
