### ISSUE TITLE
Flutter Build Dashboard - Cirrus shows as red when tasks are still running

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#49747]
I have noticed that the cirrus job shows as red in the dashboard and acts as a tree blocker even when cirrus is still running tasks.

I am not sure if this is only true for runs that have been rerun, or just in general.

cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I currently see on the dashboard cirrus tasks marked as in progress and the tree being marked green. ![image of build dashboard with in progress cirrus tasks being marked green](https://user-images.githubusercontent.com/2148558/73408463-28d65080-42b1-11ea-82bb-b508665c43e6.png)

Any task that has to be rerun should close the tree (see https://github.com/flutter/flutter/issues/45735) until passes successfully.

This may be an issue with the cirrus updating task statuses, and is either on the cirrus side or cocoon side.

@keyonghan can you take a look?

**Comment by GaryQian** [comment]
Yeah, this red+running state does not happen immediately, but I saw it when a bunch of commits stack together and have run for a while.

**Comment by CaseyHillers** [comment]
I am not familiar with the Cirrus API, so I do not know if we can check if there is a rerun.

In the current logic, https://github.com/flutter/cocoon/blob/17dda0d7bfa89ae83c2d1f15c64ce90272dc7876/app_dart/lib/src/request_handlers/refresh_cirrus_status.dart#L66-L70

we can swap the current order of the two else if blocks so in progress is above failed. However, we need to add a block of logic to check if this task is rerunning to ensure the tree closes on that case.

**Comment by GaryQian** [comment]
Ok, it does seem to be when a cirrus test is rerun.

**Comment by GaryQian** [comment]
cc @fkorotkov may be able to assist with cirrus API?

**Comment by fkorotkov** [comment]
I had an impressions that `cocoon` is not using Cirrus API and instead uses GitHub Check API to be more generic and not depend on Cirrus API. This is what code snippet by @CaseyHillers shows.

On the other hand it might be an issue related to a [UI bug I saw](https://github.community/t5/GitHub-API-Development-and/Actions-and-Check-Runs-are-not-updated-upon-a-re-run/m-p/44167#M3910). I did not check if it's a UI bug or API responses are also not updated.

Do you have some logging that can help to serialize all the events and API responses to see what is lagging/misbehaving?

**Comment by CaseyHillers** [comment]
I am going to close this since there is a duplicate being worked on. https://github.com/flutter/flutter/issues/49817
