### ISSUE TITLE
Black screen between White splash screen and the first screen

### ISSUE THREAD

**Issue by grinder15** [flutter/flutter#49754]
I have the same problem https://github.com/flutter/flutter/issues/20827 but in android.

## Steps to Reproduce

1. create brand new flutter project
2. flutter run

Debug console:
Launching lib\main.dart on vivo 1723 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.

flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.535], locale en-PH)
    • Flutter version 1.12.13+hotfix.7 at C:\src\flutter
    • Framework revision 9f5ff2306b (3 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Jerome\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Jerome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • vivo 1723 • 20dbe0ee • android-arm64 • Android 9 (API 28)

**Comment by iapicca** [comment]
Hi @grinder15 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47582) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
