### ISSUE TITLE
Disable dart:io networking in sky_shell

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4975]
sky_shell is intended only for unittesting.  We should consider removing networking support from dart:io, similar to how network_service is not available. @abarth

**Comment by Hixie** [comment]
If we want to do this we should do it soon, otherwise people might start depending on it.

**Comment by Hixie** [comment]
I propose to close this as WONTFIX.

**Comment by eseidelGoogle** [comment]
I have no objections.  I believe I was just transcribing the wishes of you or @abarth at the time. :)
