### ISSUE TITLE
onPressed error

### ISSUE THREAD

**Issue by yexiaodong** [flutter/flutter#49761]
------------code-----------------
import 'package:flutter/material.dart';
import '../../pages/cookbook/navigation_back_params_detail.dart';

class GoButtonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      //onPressed: _onPressed(context),//error
      onPressed: (){ _onPressed(context); },
      child: Text('open new page'),
    );
  }

  _onPressed(context) async{
    final result = await Navigator.push(
        context,
        new MaterialPageRoute(builder: (context) => CookbookNavigationBackParamsDetailPage())
    );

    Scaffold.of(context).showSnackBar(new SnackBar(content: new Text("$result")));
  }
}

-----------------------
why "onPressed: _onPressed(context)"  is error?

**Comment by Dellybro** [comment]
onPressed takes a function as a parameter, you are invoking the function when you call it like the following 
```
_onPressed(context)
```
 when you send .a function declaration such as
```
 () { _onPressed(context) } 
```
you are passing the definition of a function to the handler which then runs the function upon the button getting pressed.

**Comment by yexiaodong** [comment]
Thanks
