### ISSUE TITLE
Steps for getting the license text file from the engine to the store

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4977]
(This is a subissue of https://github.com/flutter/flutter/issues/109.)

- [x] Create a script that collects all the licenses for the engine. @Hixie is doing this.
- [x] Check in the file at `//engine/src/sky/packages/sky_engine/LICENSE` @Hixie is doing this.
- [x] Update the engine build bot script to upload this file to Google storage along with the engine binaries. @Hixie is doing this. Putting the file into the sky_engine package gets this for us for free.
- [x] Update the framework script to pull this file down along with the engine. @Hixie is doing this. Moot if the file is just in the sky_engine package.
- [x] Update the flutter tool to collect licenses for each pub package.
- [x] Update the flutter tool to take the collection of licenses for each pub package and concatenate it to the collection of licenses for the engine.
- [x] Update the flutter tool to take the concatenated list and put it in the assets of the generated app when building an app (compressed - bz2 compression seemed the most effective when I was testing it). @Hixie is doing this.
- [x] Update the framework to read this file, decompress it, and use it on the licenses screen.

**Comment by Hixie** [comment]
The format for the license file (relevant when generating the combined pub package license file and when concatenating the two) is U+000A (`\n`) newline-separated sequences of UTF-8 text, separated by lines of 80 `-` characters.

**Comment by eseidelGoogle** [comment]
In terms of uploading from the engine, I suspect we can include the license file in package:sky_engine:
https://github.com/flutter/engine/blob/master/sky/packages/sky_engine/BUILD.gn

**Comment by Hixie** [comment]
The framework side of this is https://github.com/flutter/flutter/pull/4984
