### ISSUE TITLE
please add full screen support for html components like videos, youtube videos inside webview flutter plugin

### ISSUE THREAD

**Issue by Bidhanrai** [flutter/flutter#49777]

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/45464

**Comment by iapicca** [comment]
Hi @Bidhanrai 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45464) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
