### ISSUE TITLE
Application is not displaying full screen in I Pad Pro 9.7 Inch

### ISSUE THREAD

**Issue by satishsoni777** [flutter/flutter#49773]
![IMG_0396](https://user-images.githubusercontent.com/25905068/73432111-06533e80-4368-11ea-8aa6-5729fa7519ee.PNG)

**Comment by satishsoni777** [comment]
![IMG_0396](https://user-images.githubusercontent.com/25905068/73432111-06533e80-4368-11ea-8aa6-5729fa7519ee.PNG)

**Comment by iapicca** [comment]
Hi @satishsoni777 
can you please provide your `flutter doctor -v` ,
and a reproducible minimal code sample.
Thank you

**Comment by satishsoni777** [comment]
@iapicca 
thanks for your quick reply, I fixed, this issue.
