### ISSUE TITLE
Draggable widget blocks scroll gesture

### ISSUE THREAD

**Issue by andreddie81** [flutter/flutter#49770]
## Steps to Reproduce

With the following code:

```
Positioned(
          top: 250,
          left: 30,
          child: Container(
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: initialState.map((f) => LongPressDraggable(
                  child: f,
                  feedback: Transform.scale(scale: 0.4, child: f),
                  childWhenDragging: Container(),
                )).toList(),
              ),
            ),
          ),
        ),
```

The Draggable effect works perfect, however, there is no Scroll gesture recognized. Tried using `Draggable` instead of `LongPressDraggable` and use `affinity` property, still no scroll.

Fixes? Suggestions?.

## Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by goderbauer** [comment]
When do you expect the scroll gesture to happen? Do you want to drag and scroll? Or are you saying that you can't scroll the view even if you're not dragging?

**Comment by andreddie81** [comment]
well the idea was, since i am using the LongPressDraggable, that onlongpress, it activates the drag effect, which happens, however, onswipe the scroll should happen since the list is placed in a SingleChildScrollView....am i too wrong?

**Comment by VladyslavBondarenko** [comment]
Hi @andreddie81 
You issue seems to be related to https://github.com/flutter/flutter/issues/35036.

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Widget> initialState = List.generate(
    10,
    (index) => Container(
      margin: EdgeInsets.all(10),
      decoration: BoxDecoration(
        border: Border.all(),
        color: Colors.red,
      ),
      height: 100,
      width: 100,
    ),
  );

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Stack(
          children: [
            Positioned(
              left: 30,
              right: 0,
              child: Container(
                child: SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: initialState
                        .map((f) => LongPressDraggable(
                              child: f,
                              feedback: Transform.scale(scale: 0.4, child: f),
                              childWhenDragging: Container(),
                            ))
                        .toList(),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

Does it solve your problem? https://github.com/flutter/flutter/issues/36584#issuecomment-621100173

**Comment by andreddie81** [comment]
sorry cant answer, we had to drop it due to a lack of solution.

**Comment by VladyslavBondarenko** [comment]
@andreddie81 
closing since the SingleChildScrollView was not scrollable because it was positioned with not set boundaries in a stack and not because draggable widget blocks scroll gesture.
If you disagree, please write in the comments and I will reopen it
