### ISSUE TITLE
Placing an empty container in Column changes its effect

### ISSUE THREAD

**Issue by mattr1221** [flutter/flutter#49776]
I am not sure if this is an issue, if not, please close it. But this is certainly not what I expected. It seems like the expected behavior of column is to only take up the cross-axis width of its children. Yet, placing an empty container inside of it expands it all the way on the cross-axis.

```
    return Scaffold(
      extendBodyBehindAppBar: true,
      body: SafeArea(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Container(),
          Text('yup'),
        ],
      )),
    );
```

If you take out the empty container, `Column` has the width of the `Text` widget and does not take the maximum width of the screen, so it's not centered against the entire width of the screen. With the empty `Container`, however, it expands and does become centered against the entire width of the screen. 

This seems like an unexpected behavior because we often return empty `Containers` when we need to render something conditionally, and in this case, it would alter the layout.

**Comment by shyndman** [comment]
From the documentation for `Container`:

> Containers with no children try to be as big as possible unless the incoming constraints are unbounded, in which case they try to be as small as possible. Containers with children size themselves to their children. The width, height, and constraints arguments to the constructor override this.

https://api.flutter.dev/flutter/widgets/Container-class.html

You might want to try `SizedBox`. Its default behavior is to be as small as possible.

**Comment by goderbauer** [comment]
As pointed out in the previous comment this is working as expected.
