### ISSUE TITLE
Improve documentation: Should I be able to use an Input outside a Form?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4978]
I am attempting to use an Input without a form. https://docs.flutter.io/flutter/material/Input-class.html says it must have a `Material` ancestor but does not mention requiring a `Form` ancestor.

I have tried two approaches; using `formField` and using `value [InputValue]`. Neither worked, the text inputs render but you can't type into them. Nothing out of the ordinary is logged.

I have only tried this against the iOS simulator.

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision ebc7e4b7ec (2 days ago), engine revision 3291edef41

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

**Comment by eseidelGoogle** [comment]
@mpcomplete would know.

**Comment by mpcomplete** [comment]
You don't need a `Form` ancestor. `Form` is optional, and manages the `InputValue`s for you. `formField` is for use with `Form`-descended `Input`s.

I'd guess you are missing an `onChanged` handler. See https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_home.dart#L315 for an example of how this works.

We could use better docs around this.

**Comment by drewwarren** [comment]
Using `value` + `onChanged` without `Form` worked. Thanks!

**Comment by mpcomplete** [comment]
Duping against https://github.com/flutter/flutter/issues/7017
