### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by DeVil2O** [flutter/flutter#49791]
After upgrading the flutter repository this error shows for every project created. 
After typing "flutter run" this error shows: 
![Screenshot from 2020-01-30 20-13-05](https://user-images.githubusercontent.com/38765776/73459840-8b0c7f80-439d-11ea-827a-6568ab61ff20.png)

How to solve this ?

**Comment by VladyslavBondarenko** [comment]
Hi @DeVil2O 
can you please provide your `flutter doctor -v`?
And please don't post screenshots of text, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by VladyslavBondarenko** [comment]
@DeVil2O 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
