### ISSUE TITLE
dependOnInheritedWidgetOfExactType should throw if used inside didUpdateWidget

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#49795]
Currently, we can call `dependOnInheritedWidgetOfExactType` inside `didUpdateWidget`, but we _cannot_ call it inside `initState`

This is inconsistent. Both life-cycles are not called again when the dependency updates, so there's no real reason to throw inside `initState` but not inside `didUpdateWidget`

The request is fairly straightforward: throw the same exception thrown is trying to call `dependOnInheritedWidgetOfExactType` inside `initState`, but with `didUpdateWidget` instead

**Comment by rrousselGit** [comment]
I've just tested – this breaks quite a lot of tests.

It seems like many `Something.of(context)` methods would need an extra `listen` flag to make this migration

**Comment by dnfield** [comment]
`initState` is called from `mount` _before_ `rebuild` (so no builds have happened yet, and you don't know where you are in the tree).

`didUpdateWidget` is called from `update`, which happens _after_ at least one build, and _before_ didChangeDependencies (now)/build.

In particular, didUpdateWidget may have changed some configuration on the widget that means you now want to change what you're subscribed to or how you're subscribed.

Am I missing something here?

**Comment by rrousselGit** [comment]
> initState is called from mount before rebuild (so no builds have happened yet, and you don't know where you are in the tree).

What do you mean by "you don't know where you are in the tree"?
Because we can use the other methods that navigate in the tree.

The main reason is, `didUpdateWidget` suffers from the same drawback as the one mentioned in the exception thrown if used inside `initState`:

> When an inherited widget changes, for example, if the value of Theme.of() changes, 
            its dependent widgets are rebuilt. If the dependent widget\'s reference to the inherited widget is in a constructor or an initState() method, 
            then the rebuilt dependent widget will not reflect the changes in the inherited widget.

**Comment by dnfield** [comment]
In initState, the context isn't valid for checking ancestors yet. In didUpdateWidget, it is.

**Comment by rrousselGit** [comment]
>In initState, the context isn't valid for checking ancestors yet.

I may be wrong, but I'm pretty sure it is valid.
It's descendants that you can't access. But accessing ancestors doesn't cause any issue.

After all, we can call `getElementForInheritedWidgetOfExactType` or the `find*` methods, or even `visitAncestorElements` freely.


It is only the `dependOn*` variants that are disabled, because it doesn't make sense to subscribe to an object in a life-cycle that will never be called again when that object changes.

**Comment by Hixie** [comment]
The reason you can't _inherit_ from initState is that we used to allow it and people would look up the inherited value in initState and not set up their didChangeDependencies to handle the case of the inherited value changing. Now that you have to use didChangeDependencies it's much harder to get that wrong.

The same problem doesn't seem to apply to the non-inheriting case, where the whole point is that you aren't looking it up to depend on it (e.g. an inherited widget with a logger so you can send one log message, you don't get if the logger later changes).

**Comment by pedromassangocode** [comment]
Hi @rrousselGit 
Is this still a valid issue? 
Based on the comments above it is unclear if this is still valid or not.

Cc: @Hixie to better decide what actions to take on this.

**Comment by rrousselGit** [comment]
It's still valid. But I don't really have a strong attachement to this issue

**Comment by pedromassangocode** [comment]
Will leave the triage label until we are clear about that to do with this.

**Comment by Hixie** [comment]
As far as I can tell this is working as intended. I'm not sure I understand the problem, in the light of my comment from Feb 6th.

**Comment by rrousselGit** [comment]
It may be a case of "as expected" vs "desired". 

The way I see it is, even if intended, it is inconsistent to not allow dependOn inside initState but allow it inside didUpdateWidget


But i don't have a strong attachement to this issue. Feel free to close it if you disagree

**Comment by Hixie** [comment]
We can't allow it in initState. We used to, but it caused bugs because people wouldn't call it again in didChangeDependencies.
We need to allow it in didUpdateWidget, because people might need it there, e.g. if their widget's features depend on both configuration and ambient state. It's not dangerous (like it is with initState) to allow that because they'd need to use didChangeDependencies the first time anyway, so they'll be registered correctly.
