### ISSUE TITLE
torch when the camera_ml_vision throws an error

### ISSUE THREAD

**Issue by MarcelEdward** [flutter/flutter#49792]
When I try to use a torch when the flutter_camera_ml_vision is scanning then I get an error:

Torch Failed : CAMERA_IN_USE (4): setTorchMode:1914: Torch for camera "0" is not available due to an existing camera user

I need the flash/torch functionality cause sometimes we want scan something in the shadow

With https://pub.dev/packages/torch and https://pub.dev/packages/flutter_camera_ml_vision

**Comment by VladyslavBondarenko** [comment]
Hi @MarcelEdward 
You are referring to 3rd party plugins,
you might want to consider to contact the torch plugin author (but I see the plugin haven't updated already one year), or to create an issue in the [flutter_camera_ml_vision github](https://github.com/rushio-consulting/flutter_camera_ml_vision/issues)

Also please follow on https://github.com/flutter/flutter/issues/19845

Closing as 3rd party and duplicate
if you disagree please write in the comments and I will reopen it.
Thank you
