### ISSUE TITLE
Row RTL

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4980]
Currently, `Row` only support `MainAxisAlignment.end` which doesn't reverse the children `List`. To do RTL easier, it would be nice to have a way to organize a `Row` from right to left which would come in handy when implementing RTL support.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/issues/2598 is the umbrella bug for RTL.  The idea is to have an inherited widget that sets the direction and then have widgets understand how to react to that.  You'd then use "MainAxisAlignment.start" as usual, but "start" will be on the right side in RTL.

**Comment by Hixie** [comment]
This will be fixed along with https://github.com/flutter/flutter/issues/5089 (Column RTL).

**Comment by Hixie** [comment]
See design in #5089.

**Comment by Hixie** [comment]
Landed.

**Comment by tahadekmak** [comment]
textDirection: TextDirection.rtl,
