### ISSUE TITLE
can't run flutter for iOS from terminal (login error)

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#49803]
I am able to run Flutter from Xcode (Product -> Run), but when I try use `flutter run --release` from terminal, I get the following error:

> Xcode's output:
> ↳
>     note: Using new build system
>     note: Planning build
>     note: Constructing build description
>     error: The operation couldn’t be completed. Unable to log in with account
>     'my@email.com'. The login details for account 'my@email.com'
>     were rejected. (in target 'Runner' from project 'Runner')
>     error: No profiles for 'my@email.com' were found: Xcode couldn't find any
>     iOS App Development provisioning profiles matching 'my@email.com'. (in
>     target 'Runner' from project 'Runner')

The email in question does indeed have a development profile, which is currently is use with Xcode.

It used to work fine, not sure what has changed. Still running v1.9.1+hotfix.6. No errors with `flutter doctor`.

**Comment by dylan-moore** [comment]
Try opening XCode and setting yourself as the development team in the project.

**Comment by iapicca** [comment]
Hi @guit4eva 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by guit4eva** [comment]
Setting **Code Signing Identity** in **Build Settings** to iOS developer was the answer. It was set to "Apple development"
