### ISSUE TITLE
Error: Error when reading 'bin/main.dart'. (That happened when I had 2 projects in the same workspace)

### ISSUE THREAD

**Issue by bl4ckck** [flutter/flutter#49806]
When I press F5 and there are 2 project folders in my workspace, launch.json is automatically created in my other project, not in my flutter project. Is this my own fault or what? I don't really understand about this. Thanks.
![Screenshot_2020-01-31_00-30-20](https://user-images.githubusercontent.com/25675947/73475902-3f3ae580-435f-11ea-9cdb-39bcda4f65c1.png)

**Comment by iapicca** [comment]
Hi @bl4ckck 
following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/Dart-Code/Dart-Code/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you
