### ISSUE TITLE
Unable to disable one drawer's drag gesture while keeping the other enabled

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#49804]
There is currently no way to set two different drawer edge widths, since they are both defined by a single `Scaffold.drawerEdgeDragWidth` property. This came up in https://github.com/flutter/flutter/issues/31127 since a user would like to be able to disable one drawer from opening via swiping and while keeping the other enabled.

There could be two separate properties to set both drawer edge drag widths to different values. However, I think that it is unlikely that a user would actually want to have separate drag widths for each drawer. Instead, perhaps we could have a parameter that disables one of the drawers, or both, from opening via a drag gesture.

**Comment by perclasson** [comment]
I'll add the two arguments `Scaffold.drawerEnableDragGesture` and `Scaffold.endDrawerEnableDragGesture` to support this. They will in turn pass the argument to the `DrawerController.enableDragGesture`.
