### ISSUE TITLE
Cocoon isn't checking Cirrus correctly

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49817]
[11:43 AM]dnfield:We have two places where we check cirrus status
[11:43 AM]dnfield:Both of them are using the conclusion field, which is not correct in the case of reruns
[11:43 AM]dnfield:I plan to update both of them later today to actually check the jobs
[11:43 AM]dnfield:Which seem more reliable

Specifically - we can't trust the `conclusion` field on the `checkSuite` field, we have to ask for the jobs and iterate through them and see their status.

**Comment by dnfield** [comment]
I'm not sure how to fix this.

The checks API seems to sometimes just erroneously report things here.  It could be a graphQL issue, or it could just be an underlying problem with check runs...

**Comment by dnfield** [comment]
For example, on flutter/engine@94cc2aa82a51e4b93b95d8f38ea106f0360325c3 - the v3 check-run API gives different results than the graphQL query that should have the same data

**Comment by dnfield** [comment]
I fixed the waiting-for-green part, not sure about the other one at this point - will need more data.

**Comment by godofredoc** [comment]
Closing as complete. Please reopen if there are still missing parts.
