### ISSUE TITLE
Request to remove  "This app is only meant to be run under the Flutter debugger"

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#49822]
I'd like to remove this or change it to a warning. Sometimes I want to run an app I'm debugging without having to attach it to a debugger first. Now, I have to compile in release mode all the time. Is there a reason for this change?

**Comment by jonahwilliams** [comment]
This change was only on by default from last Friday to Monday afternoon. What version ate you running on?

**Comment by Zazo032** [comment]
Also, you can run it using `flutter run --no-fast-start`

**Comment by ThinkDigitalSoftware** [comment]
This was compiled while I was on master.
@Zazo032, OK, thank you, I guess I'll have to add that to my IDE. Although I wish we could get the best of both worlds....

**Comment by jonahwilliams** [comment]
You don't need to turn it off manually, it's off by default now so you can just update. If you want to use it now you need to specifically add `--fast-start` to launch arguments.

**Comment by ThinkDigitalSoftware** [comment]
OK, thanks. I assume this gets announced when it becomes stable?

**Comment by jonahwilliams** [comment]
It will likely stay off by default for the time being, and isn't really documented yet. I'll add a wiki article in the next few days. The TLDR is it tries to make `flutter run` start up faster on Android in cases where dart code or assets are invalidated
