### ISSUE TITLE
Enable access Golden File comparator on LUCI

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#49837]
This is currently a no-op on LUCI since https://github.com/flutter/flutter/blob/master/packages/flutter_goldens/lib/flutter_goldens.dart#L244 returns false on LUCI.

cc @Piinks 
Related to #49749

**Comment by blasten** [comment]
@Piinks is this issue fixed by https://github.com/flutter/flutter/pull/49815? Is there any test running on LUCI that verifies the fix?

**Comment by Piinks** [comment]
> @Piinks is this issue fixed by #49815? Is there any test running on LUCI that verifies the fix?

Yup!
All pre and post submit luci builds are using Gold for flutter/flutter.

**Comment by blasten** [comment]
fantastic. Thanks @Piinks !
