### ISSUE TITLE
Can't run `flutter run -d chrome test/foo_test.dart`

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#49838]
From DevTools, I run this:

```
$ flutter run -d chrome test/flutter/table_test.dart                  
Launching test/flutter/table_test.dart on Chrome in debug mode...
Configuring `build_web_compilers:entrypoint` in target `devtools_app:devtools_app` but this is not a known Builder
Building application for the web...                                15.0s
Attempting to connect to browser instance...   
```

And nothing happens.  Chrome starts and the logs show this error

```
main.dart.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

I suspect that the tool needs to adjust the index.html file opened in Chrome to run the test script.

---Doctor---
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.27, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)
```

**Comment by yjbanov** [comment]
@jonahwilliams Is this something we want to support in tools?

@DaveShuckerow What's the use-case for this feature?

**Comment by jonahwilliams** [comment]
This works for mobile devices so it would be nice if it worked for the web. It will never work with the build_runner configuration though, so probably also blocked by the new compiler

**Comment by natebosch** [comment]
> It will never work with the build_runner configuration though

If were OK with having it still compile more than it needs to I don't see any reason that you can't support _running_ a single test file.

**Comment by jonahwilliams** [comment]
I should have phrased this as "it won't work with the build runner configuration we have today". We could invest time into fixing this, but i'm hopeful it will be much simpler with the newer tools

**Comment by jonahwilliams** [comment]
With a minor tweak, this now works in #50365 . There are some asserts being thrown in the console we'll need to check, but otherwise the results reported seem to be correct (though they stay in the browser console)

**Comment by jonahwilliams** [comment]
This is broken again, because dwds cannot handle a file URI as the entrypoint

**Comment by yjbanov** [comment]
Sounds like we should add an integration test next time we fix it.

**Comment by jonahwilliams** [comment]
This is now fixed again and properly tested
