### ISSUE TITLE
After paving, few of the devices are not responding to touch

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49840]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=45044. 

cc @cbracken @iskakaushik @gw280

**Comment by kf6gpe** [comment]
Assigning to @gw280 as @iskakaushik has indicated that he's working on it.

**Comment by cbracken** [comment]
According to @gw280 this was found to not be a Flutter issue. Closing this tracking issue.
