### ISSUE TITLE
Failure to run a Flutter driver test on device macos

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#49841]
```dart
$ flutter drive -d macos test_driver/integration/integration_app.dart
Starting application: test_driver/integration/integration.dart
Building macOS application...                                           
flutter: Observatory listening on http://127.0.0.1:58735/YV4E465E-T0=/
flutter: DevTools version 0.1.14-dev.2.
../../../flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../../../flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../../flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../../flutter/packages/flutter/lib/src/material/chip_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
Stopping application instance.
Driver tests failed: 254
```

---Doctor---
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.27, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)
```

Test code:
integration_app.dart:
```
import 'package:devtools_app/main.dart' as devtools_app;

import 'package:flutter_driver/driver_extension.dart' as flutter_driver;

void main() {
  flutter_driver.enableFlutterDriverExtension();
  devtools_app.main();
}

```

integration_app_test.dart:
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Whole app', () {
    FlutterDriver driver;
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });
    tearDownAll(() async {
      if (driver != null) await driver.close();
    });

    test('loads', () async {
      expect(await driver.getText(find.text('Connect')), 'Connect');
    });
  });
}
```

This is part of an effort to write integration tests for the devtools Flutter app

**Comment by gspencergoog** [comment]
The plugins run macOS integration tests using Flutter driver, and succeeding, so there's likely some kind of setup issue here (although I have no idea what it is).

**Comment by bambula4000** [comment]
Hi! I use the same command as on window. So if I want run my test on windows or macOS i use "flutter driver --target=test_driver/confirmation_screen/confirmation.dart" and it's works fine on both of operation systems.

Also I use next code before writing test cases, to make successfully connection with simulator, app and IDE

void main() {
  group('market_data_elemets_screen', () {
    StreamSubscription _streamSubscription;
    FlutterDriver driver;
    Confirmation confirmation = Confirmation();
    setUpAll(() async {
      driver = await FlutterDriver.connect();
      var vm = await driver.serviceClient.getVM();

      for (final isolateRef in vm.isolates) {
        final isolate = await isolateRef.load();
        if (isolate.isPaused) {
          isolate.resume();
        }
      }

      if (_streamSubscription == null) {
        _streamSubscription = driver.serviceClient.onIsolateRunnable.asBroadcastStream().listen((isolateRef) async {
          final isolate = await isolateRef.load();
          if (isolate.isPaused) {
            isolate.resume();
          }
        });
      }
    });

    tearDownAll(() async {
      if (driver != null) {
        await driver.close();
      }
    _streamSubscription.cancel();
    });
    test('check_flutter_driver_health', () async {
      Health health = await driver.checkHealth();
      expect(health.status, HealthStatus.ok);
    });
  });
} 

Good luck!

**Comment by iskakaushik** [comment]
@DaveShuckerow given that CI tests that exercise Flutter driver are able to run, I'm thinking that this might be a red-herring. Feel free to re-open if this continues to happen.
