### ISSUE TITLE
Attempting to pre-fill a TextEditingController with content doesn't work on the web

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#49859]
Attempting to pre-fill a TextEditingController, either through the constructor:

```dart
final _editingController = TextEditingController(text: 'some content');
```

Or via a setting during `initState`:

```dart
_editingController.text = '{ "foo" : 42 }';
```

Does not result in content being shown in either a `EditableText` or a `TextField`. This is in contrast to both iOS and macOS.

**Comment by mdebbar** [comment]
@domesticmouse could you share a code snippet that demonstrates the issue? I tried using `TextEditingController` with a regular material `TextField` and it worked fine.

Also, do you see any errors in the console?

**Comment by domesticmouse** [comment]
Pinged you a repro case in email and in chat.

**Comment by mdebbar** [comment]
I confirmed this is caused by the presence of `autofocus:true`. Duplicate of https://github.com/flutter/flutter/issues/47235.
