### ISSUE TITLE
Difficult to tell what version of Dart is used by Flutter Engine

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4986]
I tried `flutter --version` and `flutter doctor` and neither printed the version of Dart that we're using.

Can we show:
- version of Dart SDK that we download and use from our tools

In either `flutter --version` or `flutter doctor` ?

Thanks!

**Comment by Hixie** [comment]
The versions are all pinned by the current Flutter repo version. Can you
elaborate on why the specific versions of Dart would be helpful? (I mean,
we could also give the versions of all the pub packages the flutter tool
uses and third-party packages that the engine was compiled with, but again,
those are all pinned by the framework repo version.)

**Comment by sethladd** [comment]
I was trying to file a bug on the Dart SDK, and I wanted to give them the version of Dart that I was using (through Flutter).

**Comment by Hixie** [comment]
Ah, yeah, that's fair enough.

**Comment by pq** [comment]
Currently I see:
```
[~/src/flutter] (master) $ flutter --version
Flutter on channel master (from git@github.com:pq/flutter.git)
Framework revision 07ba37976c (33 hours ago); engine revision 9c6fc0fb1e
```

How about if we tack on the dart SDK version info from `bin/cache/dart-sdk.version`?  IOW, something like:
```
[~/src/flutter] (master) $ flutter --version
Flutter on channel master (from git@github.com:pq/flutter.git)
Framework revision 07ba37976c (33 hours ago); engine revision 9c6fc0fb1e; dart SDK 1.18.0-dev.4.4
```
?

**Comment by pq** [comment]
@sethladd, @Hixie : how does the above proposal sit with you?

Something like:

```
[~/src/flutter] (master) $ flutter --version
Flutter on channel master (from git@github.com:pq/flutter.git)
Framework revision 07ba37976c (33 hours ago); engine revision 9c6fc0fb1e; dart SDK 1.18.0-dev.4.4

```

**Comment by Hixie** [comment]
That would address the "version of Dart SDK that we download and use from our tools" part of @sethladd's original comment. I'd probably put the Dart SDK on a third line, but other than that, it SGTM.

It doesn't address the other part of Seth's original request though.

**Comment by sethladd** [comment]
I'd move the Dart SDK version down to its own line.

Good start. Thank you!

**Comment by pq** [comment]
As a matter of record, sample output now looks like:

```
[~/src/git/clones/flutter] (sdk_version) $ flutter --version
Flutter on channel sdk_version (from git@github.com:pq/flutter.git)
Framework revision e8223e25f0 (3 hours ago); engine revision 607d379c23
Dart version 1.19.0-dev.5.0 (Wed Aug 10 09:29:58 2016) on "macos_x64"
```

**Comment by sethladd** [comment]
Hm, we have two "Darts" going on. The SDK we use to run utils on the command line, and we embed a Dart into our engine.

How can we make it clear that the Dart version you are showing here is for the SDK that drives our tools, and makes room for you to also add a line that tells the user which version of Dart is in their engine?

**Comment by pq** [comment]
Good point.

I guess we could do something like:

```Framework Dart version 1.19.0-dev.5.0; engine Dart version 1.18.1```

Having said that, there's currently no easy way (that I know of) to get the embedded Dart version from within a flutter repo checkout.   Outside flutter, I guess we could work backwards from the engine revision and figure it out from the `dart_revision` specified in [DEPS](https://github.com/flutter/engine/blob/master/DEPS)?  That's clumsy though...

cc @Hixie or @devoncarew

**Comment by pq** [comment]
Taking a similar tack we can also derive the Dart version from the framework revision (this time looking at the corresponding `bin/cache.dart-sdk.version` in the `flutter_tools` git tree).  

I guess it comes down to ergonomics...

**Comment by sethladd** [comment]
> Having said that, there's currently no easy way (that I know of) to get the embedded Dart version from within a flutter repo checkout.

We can ask for a metadata file to be added to the project, from the engine.

Meanwhile, I'd suggest:

`Flutter tools using Dart version 1.19.0-dev.5.0; Flutter engine using Dart version 1.18.1`

**Comment by pq** [comment]
Cool.  Until we have the metadata file, I don't see a way to get the```Flutter engine using Dart version 1.18.1``` bit though.  Should we just leave it out for now?  Would you open an issue on the engine to add this file?

**Comment by Hixie** [comment]
The best way to find out what version the engine uses is to run some Dart
code on the test shell and see what it finds. That way you know it's right.
:-)

**Comment by sethladd** [comment]
You can leave the second part out for now. Thanks!

**Comment by pq** [comment]
Sounds good.  Will you open an issue to track the engine metadata ask?

**Comment by pq** [comment]
We've got the Dart version used by tools in as of 803fbec51b6560d1f54a14fa45134a1ba6270f05.  Once https://github.com/flutter/flutter/issues/5355 is implemented, I'll add the engine details.

**Comment by Hixie** [comment]
Closing; the only remaining issue is in #5355.
