### ISSUE TITLE
Old logs displayed when running Flutter app

### ISSUE THREAD

**Issue by andreddie81** [flutter/flutter#49864]
Not sure if this is a Flutter bug or Android Studio bug...but it indeed started happening when updated Flutter so....

The problem is that, when running a Flutter app, old logs (prints, exceptions, etc) from previous executions appear while the app has not even been pushed into the device.

That creates a huge confusion when debugging and is so annoying.

This even happens when, while running one Flutter app in one window, if I run another Flutter app on another window, logs from the previous app on the other window (prints, exceptions, etc) show up on this second window, which is even more confusing and annoying.

**--- Flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!
**--- Android Studio: 3.5.3**

**NOTE**: feel free to remove or let me know if that bug does not belong here.

**Comment by VladyslavBondarenko** [comment]
Hi @andreddie81 
I see there's an open issue addressing this.
Please follow up on https://github.com/flutter/flutter/issues/46815 (or another one https://github.com/flutter/flutter/issues/47329)
I'm closing the current one as duplicate
Thank you
