### ISSUE TITLE
Please provide more information about in future flutter framework 

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#49875]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:**  I wanna see where i did  errors  in my code 

**Actual results:**  But i see assertions which dont provide full information where i did errors in my code 

<details>
  <summary>Logs</summary>

```A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 286 pos 10: 'data != null'
```

</details>

**Comment by Zazo032** [comment]
That error message could be better, it probably means you're passing a `null` value to a `Text` widget.

**Comment by Zazo032** [comment]
Could you provide the output of `flutter doctor -v`? This should be fixed in newer versions of the framework: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text.dart#L299

Try to run `flutter upgrade` and that should provide a better error message for that error.

**Comment by II11II** [comment]
Sorry it was problem with IDE
