### ISSUE TITLE
[flutter web] TextFormField scroll bar not work

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#49870]
edit text is scroll by up and down keyboard well but when drag scrollbar
not work like this gif:

![ezgif-7-efbfa62673fb](https://user-images.githubusercontent.com/31797198/73529197-f5b1cf80-441e-11ea-9b28-710ceef692e5.gif)

```
TextFormField(
                keyboardType: TextInputType.multiline,
                maxLines: 5,
                minLines: 1,
                controller: _tecContext,
                validator: (String v) {
                  String value = v.trim();
                  if (value.isEmpty) return 'Empty field!';
                  return null;
                },
                decoration: InputDecoration(
                  labelText: 'Context',
                  labelStyle: TextStyle(
                    color: colorLabelText,
                  ),
                  hintText: '',
                  hintStyle: TextStyle(
                    color: colorHintText,
                  ),
                ),
              ),
```

**Comment by deandreamatias** [comment]
Hi,
can you provide your `flutter doctor -v` please ?

**Comment by mahmoudsalah37** [comment]
> flutter doctor -v

[√] Flutter (Channel beta, v1.13.6, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 1.13.6 at C:\flutter\flutter
    • Framework revision 659dc8129d (5 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @mahmoudsalah37 
can you please provide a reproducible minimal code sample.
Thank you

**Comment by mahmoudsalah37** [comment]
> Hi @mahmoudsalah37
> can you please provide a reproducible minimal code sample.
> Thank you
[file.zip](https://github.com/flutter/flutter/files/4142284/tests.zip)

**Comment by mdebbar** [comment]
Scrolling inside text fields isn't currently supported in Flutter web. Here's the issue we are using to track this feature request: https://github.com/flutter/flutter/issues/41630

**Comment by mahmoudsalah37** [comment]
> Scrolling inside text fields isn't currently supported in Flutter web. Here's the issue we are using to track this feature request: #41630

please hurry up to solve it
