### ISSUE TITLE
Card flickers, when user taps on any content

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49889]
https://b.corp.google.com/issues/148504495.

cc @chinmaygarde who's been commenting on the Google issue.

**Comment by cbracken** [comment]
Closing as dupe of #50011.

**Comment by chinmaygarde** [comment]
@cbracken I don't believe this is related to https://github.com/flutter/flutter/issues/50011. These platforms use entirely different subsystems and the fencing+retained surfaces hypothesis that is a plausible explanation for that issue cannot be relevant here as that technique is Fuchsia specific.

**Comment by chinmaygarde** [comment]
Update: This cannot be reproduced in the test harness. I am going to verify that custom compositor integration is not susceptible to the order in which the external view embedder returns canvases for embedder managed render targets.

Currently my primary focus.

**Comment by chinmaygarde** [comment]
Closing as this cannot be reproduced. Will open again if a reproducible reduced test case is provided.
