### ISSUE TITLE
Observatory port closed when iOS device goes to sleep

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4988]
If possible, it would be really helpful to keep the Observatory port open even if the iOS device goes to sleep.

There doesn't seem to be a way to re-establish an Observatory connection after the device goes to sleep. Which means, if I spend a few minutes exploring Observatory's Web UI, and my iOS device goes to sleep, I need to rebuild (`flutter run --profile`), get a new port number, and start my profiling all over.

Thanks for any help here! :)

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@chinmaygarde Any idea why iOS is shutting down the port?

**Comment by Hixie** [comment]
Is this still an issue?

**Comment by Hixie** [comment]
I assume this is still an issue, and it's therefore likely to be seen by many users on iOS, so I'm leaving it in the current milestone.

**Comment by Hixie** [comment]
Punting to next milestone since this isn't a blocker for new users, it can be worked around.

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/9351 will partly alleviate this but we can't keep the port open indefinitely using available iOS APIs.
