### ISSUE TITLE
Native android logs are not showing up on mac

### ISSUE THREAD

**Issue by MichelMelhem** [flutter/flutter#49885]
Hello,

**Description :**
I recently switched to a mac and I'm facing  a very annoying issue with logging. All the logs that are coming-out  native flutter plugins, in my case android ones are just not showing up in my console at all. This bug is causing me problems as i couldn't see errors coming from my native libs at all. I already checked and i'm running my app in debug mode so the issue is not coming from there.

**Behavior :**
My logs are not displayed.

**Code :**
For making logs in android i'm using :
```Log.d("firstString", "secondString");```
from the ``` android.util.Log;``` lib, i also tried the flutter one and  it did not changed anything

Even in the verboose logs i'm not able to see the logs.

**Flutter Doctor**

```
michel@iMac-de-Michel smartwork % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-FR)
    • Flutter version 1.12.13+hotfix.7 at /Users/michel/developement/flutter
    • Framework revision 9f5ff2306b (4 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/michel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Users/michel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/michel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • SM T865 • R52MB19YTCW • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

Thank you

**Comment by kf6gpe** [comment]
This sounds very much like a problem with Android Studio, rather than with Flutter --- have you confirmed that you're getting log messages from a non-Flutter application?

**Comment by MichelMelhem** [comment]
I'm running vs Code

**Comment by MichelMelhem** [comment]
I can confirm that my logs are showing up using a non flutter app so the problem is flutter related,
This is my test :
![Screenshot 2020-01-31 at 17 45 50](https://user-images.githubusercontent.com/25546627/73557671-eac46280-4451-11ea-997a-8d60cdef16c8.png)

**Comment by MichelMelhem** [comment]
Is there a way to get some help on that as it has been nearly 20 days i opened this issue and i still have no updates on it.
It really annoye me as i'm not able to see errors on my native apps ...
Thank you
