### ISSUE TITLE
flutter_test_performance_interface_change_elapsed_time regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49893]
Looks like around https://github.com/flutter/flutter/pull/49873 or maybe

**Comment by jason-simmons** [comment]
Did a bisect and saw that this was correlated with https://github.com/dart-lang/sdk/commit/62835950d1f4f6f387f01598aac50f9eff7a0429

@mkustermann

**Comment by jason-simmons** [comment]
Looks like that Dart SDK change also caused a regression in the Flutter analyzer_benchmark

**Comment by mkustermann** [comment]
This was due to an incorrect condition: [cl/134164](https://dart-review.googlesource.com/c/sdk/+/134164) should fix this performance issue.

**Comment by mkustermann** [comment]
@jason-simmons Could you confirm that the fix got rid of the regression after auto-roller rolls through to flutter/engine, flutter/flutter?

**Comment by kf6gpe** [comment]
Dropping TODAY label as we believe we have a fix in flight and don't want to block the roll.

**Comment by jason-simmons** [comment]
The affected benchmarks are now green.
