### ISSUE TITLE
GestureDetector with empty Container as a child is not tappable 

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#49919]
onTapDown responds in
```
GestureDetector(
  onTapDown: (tdd) => print('TD2'),
),
```
but not in

```
GestureDetector(
  onTapDown: (tdd) => print('TD2'),
  child: Container(),
),
```

Responds again in

```
GestureDetector(
  onTapDown: (tdd) => print('TD2'),
  child: Container(decoration: BoxDecoration(),),
),
```

**Comment by tarobins** [comment]
[✓] Flutter (Channel unknown, v1.14.7-pre.78, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.5)
[!] Android Studio (version 3.4)
    ✗ Unable to find bundled Java version.
[!] IntelliJ IDEA Community Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

! Doctor found issues in 4 categories.

**Comment by nhat108** [comment]
I think you should set height and width for Container!

**Comment by Arunnaidu3470** [comment]
@tarobins 

if the container doesn't have a child it will not render anything.
so you can pass some height and width arguments.

`GestureDetector(
  onTapDown: (tdd) => print('TD2'),
  child: Container(
            height:100, 
            width:100),
),`

**Comment by tarobins** [comment]
I'm not sure size is an issue here.  In [this example](https://github.com/tarobins/gestures/blob/three/lib/main.dart), I set up each of the above gesture detectors to each take up 1/3rd of the screen.  Two of them respond to clicks and one does not.  Even if the empty container does not render, I would expect its parent GestureDetector to still be clickable as it is still on screen and taking up space.

**Comment by dkwingsmt** [comment]
This is an expected behavior. Containers can only be hit if they have any color or decoration (this is a little badly documented), and `GestureDetector` with the default option will only be hit if it doesn't have a child or its child is hit. If you would like to make sure the entire `GestureDetector` to be hittable, the best way would be to set `GestureDetector.behavior` to `translucent` or `opaque`, depending on whether you want the widgets behind it (on the screen) to be hit or not.

**Comment by iapicca** [comment]
Hi @dkwingsmt 
I see the pr has landed adding in the doc
```dart
/// By default, containers return false for all hit tests. If the [color]
/// property is specified, the hit testing is handled by [ColoredBox], which
/// always returns true. If the [decoration] or [foregroundDecoration] properties
/// are specified, hit testing is handled by [Decoration.hitTest].
///
```
is this issue meant to be open?
Thank you

**Comment by dkwingsmt** [comment]
Yes, that doc was added for this issue.

Feel free to reopen if there are anything else unclear.
