### ISSUE TITLE
Gold flake: user does not have permission to list objects

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49917]
```
02:51 +1116 ~1: /tmp/flutter sdk/packages/flutter/test/material/radio_test.dart: Radio ink ripple is displayed correctly                                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test material.radio.ink_ripple.png failed for
a reason unrelated to pixel comparison.

Debug information for Gold:
stdout: Given image with hash 2887f99f7ebb5fda0580e7a4afa32f21 for test material.radio.ink_ripple
Expectation for test: 2887f99f7ebb5fda0580e7a4afa32f21 (positive)
Expectation for test: e0700bcc1503b6e84be54f433dea6ae9 (positive)

stderr: ERROR: logging before flag.Parse: I0131 21:03:52.169569    7736 exec.go:221] exec.go:221
Executing 'gsutil cp /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7708/packages/flutter/test/material/temp/dm.json
gs://skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json'
(where gsutil is /usr/bin/gsutil)
Error running command: ''Error uploading JSON file to GCS path
skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json:
running gsutil. Got output
AccessDeniedException: 403 527266040592-compute@developer.gserviceaccount.com does not have
storage.objects.list access to skia-gold-flutter.

: Command exited with exit status 1: gsutil cp /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7708/packages/flutter/test/material/temp/dm.json
gs://skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json.
At gcs.go:101 gcs.go:77 gcs.go:66 goldclient.go:422 goldclient.go:346 errgroup.go:57
asm_amd64.s:1357. At goldclient.go:423 goldclient.go:346 errgroup.go:57 asm_amd64.s:1357''

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:371:9)
<asynchronous suspension>
#1      _AuthorizedFlutterPreSubmitComparator.compare (package:flutter_goldens/flutter_goldens.dart:374:23)
<asynchronous suspension>
#2      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:82:57)
<asynchronous suspension>
#3      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:924:22)
#6      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:922:26)
#7      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#9      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:52:28)
#10     _expect (package:test_api/src/frontend/expect.dart:116:26)
#11     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#12     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#13     main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/material/radio_test.dart:281:11)
#26     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#28     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 31 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

02:51 +1116 ~1 -1: /tmp/flutter sdk/packages/flutter/test/material/popup_menu_test.dart: PopupMenu positioning                                                                                         
02:51 +1116 ~1 -1: /tmp/flutter sdk/packages/flutter/test/material/radio_test.dart: Radio ink ripple is displayed correctly [E]                                                                        
  Test failed. See exception logs above.
  The test description was: Radio ink ripple is displayed correctly
  ```

https://cirrus-ci.com/task/6530858593026048

/cc @Piinks

**Comment by Piinks** [comment]
cc/ @kjlubick
It looks like it is trying to authenticate with an unknown service account (`527266040592-compute@developer.gserviceaccount.com`?). I don't know why it would be doing this. Could Cirrus be providing the wrong service account?

I saw this the other day on #49334. It did not reproduce on that PR or any other.

**Comment by dnfield** [comment]
This was my PR, so it should have had access to whatever encrypted credentials we have.

**Comment by shihaohong** [comment]
This seems to be happening on my most recent PR as well: https://github.com/flutter/flutter/pull/49913

**Comment by Piinks** [comment]
Yeah, it would say 'ENCRYPTED' if it were a permissions issue, but that service account is not the one associated with Gold. I have no idea where it came from or why it is trying to authenticate with that account. 🤔

**Comment by dnfield** [comment]
https://api.cirrus-ci.com/v1/task/5558371025682432/logs/main.log seems similar

**Comment by kjlubick** [comment]
527266040592-compute might be a default service-account for the project with # 527266040592. Perhaps the logic that loads in the service account to Cirrus needs examination?

For debugging, maybe print out the hash of the service account file and compare good runs to bad runs?

**Comment by dnfield** [comment]
@kjlubick these runs generally succeed on a second try.  Cirrus is always giving us the same account. Could this be a quota issue?

**Comment by kjlubick** [comment]
Hang on, I see the error message says goldctl is using gsutil (which is probably using the wrong service account). gsutil is *not* meant for production usage. Please check that you are properly calling goldctl auth and specifying a service account every time. Otherwise, goldctl falls back to using gsutil.

**Comment by Piinks** [comment]
cc/ @fkorotkov in case this may be a Cirrus issue.

Here's what I can tell thus far
- This so far has only been reported on one shard - `framework_tests-libraries-linux`
- This is happening with the `_AuthorizedFlutterPreSubmitComparator`, which is only used when the service account is available from Cirrus.
- The service account comes from an encrypted environment variable on Cirrus called `GOLD_SERVICE_ACCOUNT`
  - If the service account variable exists, but is empty, it would throw during `auth`.
  - If the service account is still encrypted due to user permissions, it would use the `_UnauthorizedFlutterPresubmitComparator` (used for empty auth, does not run tryjobs)
- As reported by @dnfield, re-running the test shard does not reproduce the issue and it works as expected.
- These flakes have all happened after adding a tryjob. Other calls (auth and init) aren't throwing before that point like I would expect if there was an auth issue, __see call flow below__.
- Furthermore, this does not appear to happen on __every__ tryjob that is executing on that shard. Some tryjobs succeed in executing, while only a few are flaking. 
  - In some reports only one tryjob flakes, while in others as many as 7 flake.

---

First, `auth` is called
 - Will throw for empty service account

```goldctl auth --service-account serviceAccount.json --work-dir $workDirectory```

- Will throw if non-zero exit code returns from auth
- Based on logs, this all appears successful ✅ 

--- 

Then `imgtest init` for tryjob
- Will throw if there are any null arguments provided for this process

```
goldctl imgtest init
--instance flutter 
--work-dir $workDirectory
--commit $commitHash
--keys-file $keys
--failure-file $failures
--passfail
--crs github
--cis cirrus
--jobid $cirrusTaskID
--patchset_id $commitHash
```

- Will throw for non-zero exit code from imgtest init
- Based on logs, this all appears successful ✅ 

---

Finally `imgtest add` to add the tryjob

```
goldctl imgtest add
--work-dir $workDirectory
--test-name $testName
--png-file $goldenFile
```

- Will throw for non-exit code, which is where this is happening. ☠️ 

---

I'll see about adding more logging here if it can be helpful to further diagnose. 🤒  Let me know what ya'll think about where along this path I can get more helpful information.

**Comment by fkorotkov** [comment]
@Piinks where is `goldctl auth` called? And where are sources for `goldctl`?

**Comment by Piinks** [comment]
The golden file comparator is instantiated and authorized at the launch of each individual test file. 
https://github.com/flutter/flutter/blob/e10df3c1a65f9d7db3fc5340cffef966f7bd40a6/packages/flutter_tools/lib/src/test/flutter_platform.dart#L214

https://github.com/flutter/flutter/blob/068fa84c5bb28382853a0506395158afa30f3cc6/packages/flutter/test/flutter_test_config.dart#L5

When testing the flutter repository, there is a special test configuration used to pick the comparator.
https://github.com/flutter/flutter/blob/e10df3c1a65f9d7db3fc5340cffef966f7bd40a6/packages/flutter_goldens/lib/flutter_goldens.dart#L29

The `_Authorized...comparator` is chosen based on info from Cirrus:
https://github.com/flutter/flutter/blob/e10df3c1a65f9d7db3fc5340cffef966f7bd40a6/packages/flutter_goldens/lib/flutter_goldens.dart#L313

and makes a single auth call:
https://github.com/flutter/flutter/blob/e10df3c1a65f9d7db3fc5340cffef966f7bd40a6/packages/flutter_goldens/lib/flutter_goldens.dart#L315

Although that all seems to work fine. The right comparator is chosen, `auth` returns ok, the flake happens later.

---



> And where are sources for `goldctl`?

Let me know if [this documentation/repo](https://github.com/google/skia-buildbot/blob/master/golden/docs/README.md) is what you are looking for. :)

**Comment by Piinks** [comment]
Looks like this happened on the `framework_tests-libraries-linux` and `framework_tests-widgets-linux` shards yesterday on this PR: https://github.com/flutter/flutter/pull/49956

I've amended my summary above to reflect this is so far isolated to just linux shards.

Here are the tasks: 
https://api.cirrus-ci.com/v1/task/5715289652330496/logs/main.log
https://api.cirrus-ci.com/v1/task/6277457535827968/logs/main.log

It looks like only one tryjob flaked on each one out of ~165. I've restarted the tasks to see if it happens again.

**Comment by Piinks** [comment]
> Looks like this happened on the `framework_tests-libraries-linux` and `framework_tests-widgets-linux` shards yesterday on this PR: #49956
> 
> I've amended my summary above to reflect that this is so far isolated to just linux shards.
> 
> Here are the tasks:
> https://api.cirrus-ci.com/v1/task/5715289652330496/logs/main.log
> https://api.cirrus-ci.com/v1/task/6277457535827968/logs/main.log
> 
> It looks like only one tryjob flaked on each one out of ~165. I've restarted the tasks to see if it happens again.

Re-running flaked again on both shards.
https://cirrus-ci.com/task/4927277523795968 - 17 tryjobs flaked
https://cirrus-ci.com/task/5735103208882176 - 2 tryjobs flaked

**Comment by fkorotkov** [comment]
I don't see if there were any issue on Cirrus Backend side to decrypt environment variables. As far as I can see there are no logs upon a successful auth, aren't there? Is there something in logs indicates that the authorization was called before executing the tests.

At the moment I'm investigating how `527266040592` credentials could leak to the container. Cirrus uses this read-only credentials to pull the pre-cached docker images that were built from `Dockerfile`s.

**Comment by dnfield** [comment]
I think this could probably happen if `gsutil` is configured on the container to use that account, and Skia gold is falling back to `gsutil` instead of using its internal methods.

**Comment by Piinks** [comment]
I can add some logging for successful `auth` to validate. 

The SkiaGoldClient is instantiated and authorized before the comparator is even instantiated, and the comparator runs the tests, so I think it's all happening in the right order.
Results are still making their way on to https://flutter-gold.skia.org/changelists, only a few tests here and there are flaking.

**Comment by Piinks** [comment]
Checked against a new commit on #49956 without re-running, the flaked tests do not appear on the dashboard. We weren't sure after having re-run so many times. Still appears restricted to linux.

**Comment by goderbauer** [comment]
Happened here: https://cirrus-ci.com/task/6241023529582592

**Comment by christopherfujino** [comment]
> I think this could probably happen if `gsutil` is configured on the container to use that account, and Skia gold is falling back to `gsutil` instead of using its internal methods.

> At the moment I'm investigating how 527266040592 credentials could leak to the container. Cirrus uses this read-only credentials to pull the pre-cached docker images that were built from Dockerfiles.

This could be related to the fact that we're now installing goldctl during the docker build https://github.com/flutter/flutter/pull/46640/files#diff-15c707847b64b38efeb0f42d867a013dR139

**Comment by Piinks** [comment]
Could the goldctl version in the docker build need to be updated? Mac and windows aren't experiencing this flake, and they have the latest version of goldctl.

**Comment by Piinks** [comment]
Here as well: https://cirrus-ci.com/task/6238517198061568

**Comment by dnfield** [comment]
If we're concerned about this, perhaps we should revert https://github.com/flutter/flutter/pull/46640 and see if it helps get rid of the flakiness. If it does, we'll want to figure out some retry logic for when depot_tools or goldctl download fails.

**Comment by Piinks** [comment]
Thus far it looks like reverting #46640 has fixed this, I'm going to continue to monitor.

**Comment by dnfield** [comment]
There's at least one report of this flake happening after the revert, but it's not super clear to me yet what happened there.  Let's keep an eye on it today - if it's still happening we should revert the revert.

**Comment by Piinks** [comment]
Do you have a PR/task/log we can see where it is still happening?

**Comment by a14n** [comment]
https://cirrus-ci.com/task/6059363425058816?command=main#L1268

**Comment by christopherfujino** [comment]
Another instance https://cirrus-ci.com/task/5085804800245760?command=main#L927

**Comment by Piinks** [comment]
Is it possible some reoccurrences could be from branches that need to be updated?

**Comment by christopherfujino** [comment]
@Piinks: I just checked, and both are post-revert :/

**Comment by Piinks** [comment]
From this log: https://api.cirrus-ci.com/v1/task/6064140468879360/logs/main.log

It looks like this is happening when `auth_opt.json` (created by goldctl during auth) already exists. The SkiaClient checks to see if it is already there so it won't re-authenticate if unnecessary.

```dart
// in SkiaClient.auth
Skia Client is already authorized.
auth_opt.json: 
{
  "Luci":false,
  "ServiceAccount":"",
  "GSUtil":true
}
```

However, this does not happen every time, as there are other cases where everything seems to be ok:

```dart
// in SkiaClient.auth
Skia Client is already authorized.                                                                                                    
{
  "Luci":false,
  "ServiceAccount":"/tmp/flutter sdk/bin/cache/pkg/skia_goldens3735/packages/flutter/test/widgets/serviceAccount.json",
  "GSUtil":false
}
```

The `GOLD_SERVICE_ACCOUNT` seems to also be ok, confirmed the service account is present with the right information in every test (checked client_email).

**Comment by Piinks** [comment]
I think I know what this is now. 🎉 

To solve #46687, #47551 added the empty auth option for `goldctl` so we could use the `check` feature. When using empty auth, no tryjobs are run/nothing is done that actually requires authentication.
I'm guessing that empty auth would create an auth_opt.json file like the first mentioned above where `GSUtil:true`

These files are all created in randomly generated directories to maintain thread safety.

If they are being cached, which I think they are (the 🐞 ), then future test runs that randomly choose the same directory that need to be authenticated don't because they see that the file is there and assume it's already set up, and therefore end up using gsutil.

**Comment by kjlubick** [comment]
Yep, that sounds like it would be it - I guess the solution is to clean up the temporary Gold folder after you are done?
