### ISSUE TITLE
Initial load of Shrine has long frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4991]
Built from `flutter run --profile` for my iPhone 6S.

Tap "Shrine" from the main gallery home.

![screen shot 2016-07-21 at 12 52 55 pm](https://cloud.githubusercontent.com/assets/5479/17036682/2f35bad0-4f42-11e6-80b1-4b1ca272883b.png)
[shrine-initial-load.json.zip](https://github.com/flutter/flutter/files/376845/shrine-initial-load.json.zip)

**Comment by HansMuller** [comment]
Loading and caching the app's ~20 product images might account for the long frame.

You could try collecting the same data after replacing the Image with a Container here:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/shrine/shrine_home.dart#L276

**Comment by eseidelGoogle** [comment]
This may be related to https://github.com/flutter/flutter/issues/3805, but we'd need to ask someone who knows more.

**Comment by chinmaygarde** [comment]
Is this still an issue? I dont see any decodes on the IO thread during the wait. So #3805 should not have affect this.

**Comment by sethladd** [comment]
Yes, I'm still seeing this on a 5X. Screenshot coming...

**Comment by sethladd** [comment]
The first initial load of Shrine on a Nexus 5 is still showing a few spikes.

The second load of Shrine is very smooth.

Something is happening on the first load, that isn't happening on the second load.

**Comment by dragostis** [comment]
I looked at this with @eseidelGoogle, @HansMuller and @Hixie. Here's a trace of what's happening. The big culprit appears to be the fact that `CustomGrid` isn't lazy.

[trace](https://github.com/flutter/flutter/files/433203/dart-timeline-2016-7-23.json.zip)

Here's the diff for the timeline events:

```
   @protected
   Element inflateWidget(Widget newWidget, dynamic newSlot) {
-    assert(newWidget != null);
-    Key key = newWidget.key;
-    if (key is GlobalKey) {
-      Element newChild = _retakeInactiveElement(key, newWidget);
-      if (newChild != null) {
-        assert(newChild._parent == null);
-        assert(() { _debugCheckForCycles(newChild); return true; });
-        newChild._activateWithParent(this, newSlot);
-        Element updatedChild = updateChild(newChild, newWidget, newSlot);
-        assert(newChild == updatedChild);
-        return updatedChild;
+    return Timeline.timeSync("Element.inflateWidget(${newWidget.runtimeType})", () {
+      assert(newWidget != null);
+      Key key = newWidget.key;
+      if (key is GlobalKey) {
+        Element newChild = _retakeInactiveElement(key, newWidget);
+        if (newChild != null) {
+          assert(newChild._parent == null);
+          assert(() { _debugCheckForCycles(newChild); return true; });
+          newChild._activateWithParent(this, newSlot);
+          Element updatedChild = updateChild(newChild, newWidget, newSlot);
+          assert(newChild == updatedChild);
+          return updatedChild;
+        }
       }
-    }
-    Element newChild = newWidget.createElement();
-    assert(() { _debugCheckForCycles(newChild); return true; });
-    newChild.mount(this, newSlot);
-    assert(newChild._debugLifecycleState == _ElementLifecycle.active);
-    return newChild;
+      Element newChild = newWidget.createElement();
+      assert(() { _debugCheckForCycles(newChild); return true; });
+      newChild.mount(this, newSlot);
+      assert(newChild._debugLifecycleState == _ElementLifecycle.active);
+      return newChild;
+    });
   }
```

This most likely depends on #5288.

**Comment by sethladd** [comment]
Thanks for the analysis!

**Comment by dragostis** [comment]
@sethladd This would definitely lower the huge build time. (around 100ms on my device) Most likely this will make layout faster as well.

**Comment by sethladd** [comment]
We see this more obviously on Android (5X)

**Comment by Hixie** [comment]
This might get resolved a little by the scrolling refactor, since it'll make this lazy.

**Comment by ScottPierce** [comment]
@Hixie I assumed this issue is related to this one: https://github.com/flutter/flutter/issues/6920

When @abarth was having me grab some benchmarks, he seemed surprised that the app was spending so much time in Paragraph_layout

**Comment by sethladd** [comment]
Reported on Reddit: https://www.reddit.com/r/androiddev/comments/5o8v0g/anyone_using_dart_with_flutter_how_is_it/ddja6uw/

**Comment by chinmaygarde** [comment]
This should be fixed by https://github.com/flutter/engine/pull/3682. Please reopen if it is still an issue.
