### ISSUE TITLE
Inconsistency in tap behaviour of nested GestureDetectors

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#49921]
tapping on 

```
GestureDetector(
  onTapDown: (details) => print('outer tap down'),
  onTapUp: (details) => print('outer tap down'),
  onTap: () => print('outer tap'),
  child: GestureDetector(
    onTapDown: (details) => print('inner tap down'),
    onTapUp: (details) => print('inner tap up'),
    onTap: () => print('inner tap'),
    child: Container(
      decoration: BoxDecoration(),
    ),
  ),
),
```

prints

```
[+1899 ms] I/flutter ( 6248): inner tap down
[   +2 ms] I/flutter ( 6248): outer tap down
[  +37 ms] I/flutter ( 6248): inner tap up
[        ] I/flutter ( 6248): inner tap
```

but 

```
GestureDetector(
  onTapDown: (details) => print('outer tap down'),
  onTapUp: (details) => print('outer tap down'),
  onTap: () => print('outer tap'),
  child: GestureDetector(
    onTapDown: (details) => print('inner tap down'),
    onTapUp: (details) => print('inner tap up'),
    onTap: () => print('inner tap'),
  ),
),
```

prints 

```
[ +979 ms] I/flutter ( 6248): inner tap down
[ +128 ms] I/flutter ( 6248): inner tap up
[        ] I/flutter ( 6248): inner tap
```

**Comment by tarobins** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.14.7-pre.78, on Linux, locale en_US.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.5)
[!] Android Studio (version 3.4)
    ✗ Unable to find bundled Java version.
[!] IntelliJ IDEA Community Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

**Comment by tarobins** [comment]
I'm not actually sure what the output from the above should be.

**Comment by tarobins** [comment]
Probably some relation to https://github.com/flutter/flutter/issues/49921

**Comment by tarobins** [comment]
probably some relation to https://github.com/flutter/flutter/issues/49919

**Comment by dnfield** [comment]
I'm not sure about the first case, but the second case follows the docs:

> If this widget has a child, it defers to that child for its sizing behavior. If it does not have a child, it grows to fit the parent instead.

https://api.flutter.dev/flutter/widgets/GestureDetector-class.html

**Comment by tarobins** [comment]
I'm not sure widget size is an issue here.  Even if the sizes of all the widgets are the same, the behaviour when you click on them is different.  In [this example](https://github.com/tarobins/gestures/blob/master/lib/main.dart), I setup a scenario where all of the widgets above take up half the screen, but if you tap on the top or bottom half of the screen you get different output.

**Comment by tarobins** [comment]
from discord re why in the first example there is only a "tap down" for the outer gesture detector and not and "tap up" or "tap"

> tap down fires immediately
> tap up and tap fire when the gesture wins
> only one gesture can win

**Comment by tarobins** [comment]
As for the behaviour of the second case, deferToChild could be involved.   (mostly a note for myself for later)

**Comment by iapicca** [comment]
Hi @tarobins 
a PR related to this [issue](https://github.com/flutter/flutter/issues/49919)
seems to clarify the expected behaviour of `Container`'s  tap behaviour.
Does this solve the issue for you?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
