### ISSUE TITLE
Unable to run "pub upgrade"

### ISSUE THREAD

**Issue by thomasgauvin** [flutter/flutter#49924]
## Steps to Reproduce

1. Install flutter
2. Try to run flutter doctor --verbose
3. Get stuck at "Running pub upgrade..."

## Logs

```
flutter --verbose
Building flutter tool...
Running pub upgrade...
```

```
```

```
```

**Comment by dnfield** [comment]
It looks like you may have run `flutter --verbose` rather than `flutter doctor --verbose`.

Can you try again?

**Comment by VladyslavBondarenko** [comment]
Closing since already long time without an answer
