### ISSUE TITLE
[google_maps_flutter] Poor performance rendering polylines

### ISSUE THREAD

**Issue by zacps** [flutter/flutter#49930]
## Details

**Target Platform:** Android
**Target OS version/browser:** Platform 29
**Devices:** OnePlus 6

<details><summary><code>flutter doctor -v</code></summary>
<p>

```
[√] Flutter (Channel master, v1.14.7-pre.58, on Microsoft Windows [Version 10.0.18362.592], locale en-NZ)
    • Flutter version 1.14.7-pre.58 at C:\tools\flutter
    • Framework revision 83d4d63a71 (19 hours ago), 2020-01-30 18:10:36 -0800
    • Engine revision e5209202fb
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Zac\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1
[√] Connected device (1 available)
    • ONEPLUS A6000 • a21aff4f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</p>
</details>

Polylines (and other shapes) have to be serialized to json while rendering. This is done per-point and  can be extremely slow.

Profile build:

![image](https://user-images.githubusercontent.com/9827696/73587746-56770000-4524-11ea-9981-8aea9a0d3ee0.png)

As you can see a huge amount of time is taken up in `_toJson`.

I wrote a simple patch that caches the json representation of `Polyline`s based on their ID using a singleton map. This reduced the frametime back to reasonable levels:

![image](https://user-images.githubusercontent.com/9827696/73587698-d2247d00-4523-11ea-8ff4-37a82f2da44a.png)

<details><summary>Patch</summary>
<p>

```diff
diff --cc packages/google_maps_flutter/lib/src/polyline.dart
index 0d7684fb,0d7684fb..6f0b3d14
--- a/packages/google_maps_flutter/lib/src/polyline.dart
+++ b/packages/google_maps_flutter/lib/src/polyline.dart
@@@ -251,11 -251,11 +251,34 @@@ Map<PolylineId, Polyline> _keyByPolylin
            polyline.polylineId, polyline.clone())));
  }
  
++class _PolylineCache {
++  _PolylineCache._internal();
++
++  static final _PolylineCache _singleton = _PolylineCache._internal();
++  static final Map<PolylineId, dynamic> _map = Map();
++
++  factory _PolylineCache() {
++    return _singleton;
++  }
++
++  dynamic operator [](PolylineId id) => _map[id];
++  void operator []=(PolylineId id, dynamic v) => _map[id] = v;
++
++  bool containsKey(PolylineId id) => _map.containsKey(id);
++}
++
  List<Map<String, dynamic>> _serializePolylineSet(Set<Polyline> polylines) {
    if (polylines == null) {
      return null;
    }
++  final cache = new _PolylineCache();
++
    return polylines
--      .map<Map<String, dynamic>>((Polyline p) => p._toJson())
++      .map<Map<String, dynamic>>((Polyline p) {
++        if (!cache.containsKey(p.polylineId)) {
++          cache[p.polylineId] = p._toJson();
++        }
++        return cache[p.polylineId];
++      })
        .toList();
  }
```
</p></details>

This will need to be edited to store the cache per `GoogleMap` instance as `PolylineId` is only unique per map. My implementation also has no upper size bound.

It may also be worth using a third party cache library, of which there are a few available.
It's also almost certainly worth doing this for polygons.

**Comment by iapicca** [comment]
Hi @zacps 
if you wish to submit a pr please take a look to this [docs](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md#developing-for-flutter)
thank you

**Comment by zacps** [comment]
It's unlikely I'll have the time to refine this into a good state for the foreseeable future.

**Comment by Mkohm** [comment]
How many points did you render before it started having poor performance?

**Comment by zacps** [comment]
I was rendering a large number of points, I don't have a precise number at the moment. Regardless this should ideally be fixed by switching to a binary serializer for points/polylines/... as json serialization is incredibly slow in flutter.

**Comment by iapicca** [comment]
@zacps 
from your last message seems that you solved the issue, is this the case?
tagging @TahaTesser for visibility

**Comment by zacps** [comment]
I ended up removing the view that drew large numbers of poly-lines. The patch I provided does work as a workaround, but again the optimal solution is to move away from JSON serialization in the render loop entirely.

**Comment by darshankawar** [comment]
@zacps 
Since this issue is more than a year old and the plugin has gone through lot of updates, I suggest to try your use case using [latest](https://pub.dev/packages/google_maps_flutter/install) plugin version and see if you still get similar performance or that has improved.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
