### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses and Execution failed for task ':app:mergeDebugJavaResource' exceptions 

### ISSUE THREAD

**Issue by hakemkadem** [flutter/flutter#49938]
I installed all packages and based on flutter official document. Everything seemed fine and ready to be ran, as well as the android emulator is launched successfully until making the F5(run or debug) in visual studio code, I got a wired exceptions just like below:

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.util.zip.ZipException


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Zip file smaller than EOCD size: C:\Users\Hakim\.gradle\caches\modules-2\files-2.1\io.flutter\x86_64_debug\1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119\1ae520cbbf7e14af867232784194366b3d1c3f34\x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Can any one help to overcome this problem?

**Comment by cherlow** [comment]
After running  flutter run in my app i get the following error  

**_NOTE: all solutions in the related problem don't work for me_**
```
 FAILURE: Build failed with an exception.
[  +50 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[   +1 ms] > 1 exception was raised by workers:
[   +1 ms]   java.util.zip.ZipException

```

**Here is the full output of flutter run -v**

```
[  +40 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +102 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +56 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +119 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +161 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +30 ms] Exit code 0 from: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +32 ms] C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +111 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +232 ms] Generating F:\flutter\gallery\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = ranchu
[  +77 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +27 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +24 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -s flutter
[  +10 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +66 ms] Android Debug Bridge version 1.0.41
           Version 29.0.4-5871666
           Installed as C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +8 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +40 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[   +8 ms] gradle.properties already sets `android.enableR8`
[  +15 ms] Using gradle from F:\flutter\gallery\android\gradlew.bat.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +222 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +13 ms] executing: [F:\flutter\gallery\android\] F:\flutter\gallery\android\gradlew.bat -Pverbose=true
-Ptarget=F:\flutter\gallery\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[+5501 ms] > Task :app:compileFlutterBuildDebug
[  +40 ms] [  +40 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [ +171 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [   +3 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[  +11 ms] [        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +18 ms] [ +112 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] [        ] v1.12.13+hotfix.7-0-g9f5ff2306
[   +1 ms] [  +52 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] [ +124 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +5 ms] [        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +73 ms] [  +75 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] [        ] https://github.com/flutter/flutter.git
[ +196 ms] [ +156 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +11 ms] [  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[  +85 ms] [  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +158 ms] [ +189 ms] Initializing file store
[   +3 ms] [  +28 ms] Done initializing file store
[+2198 ms] [+2126 ms] Skipping target: kernel_snapshot
[   +3 ms] [  +89 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +296 ms] [ +231 ms] debug_android_application: Complete
[   +3 ms] [  +30 ms] Persisting file store
[   +3 ms] [  +27 ms] Done persisting file store
[   +1 ms] [   +5 ms] build succeeded.
[  +91 ms] [  +35 ms] "flutter assemble" took 2,899ms.
[  +99 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +4 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[  +19 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +71 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +4 ms] > Task :app:cleanMergeDebugAssets
[   +2 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +89 ms] > Task :app:mergeDebugAssets
[ +302 ms] > Task :app:copyFlutterAssetsDebug
[   +5 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +190 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +10 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +102 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +101 ms] > Task :app:checkDebugDuplicateClasses FAILED
[  +71 ms] FAILURE: Build failed with an exception.
[  +50 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[   +1 ms] > 1 exception was raised by workers:
[   +1 ms]   java.util.zip.ZipException
[   +4 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +5 ms] BUILD FAILED in 9s
[   +4 ms] 14 actionable tasks: 5 executed, 9 up-to-date
[ +374 ms] Running Gradle task 'assembleDebug'... (completed in 10.6s)
[  +11 ms] "flutter run" took 11,631ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
**flutter doctor -v output**
```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (5 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\M.U.S.E.M.B.I\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by SanchezQb** [comment]
I think it's the version of flutter that is problematic. Is there a way to downgrade?
<img width="630" alt="Screenshot 2020-02-01 at 20 47 32" src="https://user-images.githubusercontent.com/15196879/73598125-4b2bd080-4534-11ea-8ae2-d3328687a2b4.png">

**Comment by cherlow** [comment]
you can manually downgrade by downloading a previous stable release of the
platform you are using from
https://flutter.dev/docs/development/tools/sdk/releases and extracting it
to the location where you initially had flutter installed

As for me the location is c:\flutter

let me know if it works after downgrading

**Comment by SanchezQb** [comment]
Downgrading worked. I ran `flutter version` to list versions and then ran `flutter version v1.12.13+hotfix.6` to switch to a previous version.

**Comment by hakemkadem** [comment]
I solved the two above problems as following:
First problem  (:app:checkDebugDuplicateClasses)
solution was: Through android studio
File > Invalidate Caches/Restart... 

Second problem (:app:mergeDebugJavaResource)

The solution was:
Due to the generated build file path exceeds the windows max path length of 255 characters. 
Only trying to use short names to make sure the project path is not too long, solved the problem.

This is the path in my machine: 
C:\Users\Hakim.gradle\caches\modules-2\files-2.1\io.flutter\x86_64_debug\1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119\1ae520cbbf7e14af867232784194366b3d1c3f34\x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.jar

You can follow find the path in your machine and change the long file name to short one.

**Comment by hakemkadem** [comment]
I solved the two above problems as following:
First problem (:app:checkDebugDuplicateClasses)
solution was: Through android studio
File > Invalidate Caches/Restart...

Second problem (:app:mergeDebugJavaResource)

The solution was:
Due to the generated build file path exceeds the windows max path length of 255 characters.
Only trying to use short names to make sure the project path is not too long, solved the problem.

This is the path in my machine:
C:\Users\Hakim.gradle\caches\modules-2\files-2.1\io.flutter\x86_64_debug\1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119\1ae520cbbf7e14af867232784194366b3d1c3f34\x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.jar

You can follow find the path in your machine and change the long file name to short one.

**Comment by rodrigoalien** [comment]
After several hours trying to solve this problem, only worked when i downgrading. The last version, v1.12.13+hotfix.7, not worked for me.

**Comment by SanchezQb** [comment]
> I solved the two above problems as following:
> First problem (:app:checkDebugDuplicateClasses)
> solution was: Through android studio
> File > Invalidate Caches/Restart...
> 
> Second problem (:app:mergeDebugJavaResource)
> 
> The solution was:
> Due to the generated build file path exceeds the windows max path length of 255 characters.
> Only trying to use short names to make sure the project path is not too long, solved the problem.
> 
> This is the path in my machine:
> C:\Users\Hakim.gradle\caches\modules-2\files-2.1\io.flutter\x86_64_debug\1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119\1ae520cbbf7e14af867232784194366b3d1c3f34\x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.jar
> 
> You can find the path in your machine and change the long file name to short one.

For the second problem, is it still the same if you're on Mac?

**Comment by iapicca** [comment]
Hi @hakemkadem 
I'm glad that you found a solution to the problem.

@cherlow  you have an [issue open](https://github.com/flutter/flutter/issues/49935) for your case,
please follow up there

@rodrigoalien and @SanchezQb 
this issue seems to be solved

I'd recommend to try running
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please 
open a dedicated issue 
providing your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem.

thank you

**Comment by salemalem** [comment]
All was working. But this happened.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@3b4cea0e' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@b63ba1' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by salemalem** [comment]
> 
> 
> All was working. But this happened.
> 
> FAILURE: Build completed with 2 failures.
> ## 1: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:mergeDebugJavaResource'.
> 
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > File 'com.android.builder.files.ZipCentralDirectory@3b4cea0e' was deleted, but previous version not found in cache
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 2: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:mergeDebugNativeLibs'.
> 
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > File 'com.android.builder.files.ZipCentralDirectory@b63ba1' was deleted, but previous version not found in cache
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
>     * Get more help at https://help.gradle.org
> 
> 
> BUILD FAILED in 36s
> Finished with error: Gradle task assembleDebug failed with exit code 1

What I can do?

**Comment by iapicca** [comment]
Hi @hakemkadem 
please follow the indication listed [here](https://github.com/flutter/flutter/issues/49938#issuecomment-581267519)
if the problem persist 
please open an issue with the info required above
thank you

**Comment by IlyaBlokh** [comment]
I had same problem
After run 

> flutter doctor

 I got message:
```
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
```

> flutter doctor --android-licenses 

helped

**Comment by joetex** [comment]
I discovered this issue as well.  

What I found, was that there were over 10 dart.exe processes locking some of the "build" folder's jar files.  I used Microsoft Process Explorer, to highlight the applications locking those jar's, which highlighted LOTS of cmd.exe -> conhost.exe, dart.exe processes.  

I killed each process, and I was able to safely run `flutter clean` and launch the app.

I use VSCode, and I assume its launching new dart processes when my app crashes, or I stop and start?  In any case, this is most-likely an issue with VSCode Extension for Flutter, which appears to be leaking dart.exe processes, causing the error OP is receiving.

**Comment by ahmednasir** [comment]
I also found this issue. Here's what I did to solve it:

1. `flutter clean`
2. `flutter upgrade`

And then I was able to run the app successfully.

**Comment by abhidiwakar** [comment]
I faced the same issue. Here's what I did:
1. Deleted the build directory.
2. Run `flutter clean`

After this, I was able to run the app.

**Comment by hadsluks** [comment]
> I solved the two above problems as following:
> First problem (:app:checkDebugDuplicateClasses)
> solution was: Through android studio
> File > Invalidate Caches/Restart...
> 
> Second problem (:app:mergeDebugJavaResource)
> 
> The solution was:
> Due to the generated build file path exceeds the windows max path length of 255 characters.
> Only trying to use short names to make sure the project path is not too long, solved the problem.
> 
> This is the path in my machine:
> C:\Users\Hakim.gradle\caches\modules-2\files-2.1\io.flutter\x86_64_debug\1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119\1ae520cbbf7e14af867232784194366b3d1c3f34\x86_64_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.jar
> 
> You can find the path in your machine and change the long file name to short one.

Reducing the path name worked for me too..Thanks

**Comment by yazinsai** [comment]
Solution for me was the highest upvoted answer here: https://stackoverflow.com/a/60492942/2022751

```
// android/app/build.gradle
...
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Add this line 👇 
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
}
```
