### ISSUE TITLE
Add explicit wrappers for "pub get" and "pub upgrade"

### ISSUE THREAD

**Issue by nex3** [flutter/flutter#4994]
Flutter currently runs `pub get` implicitly as part of other commands (for example `flutter run`), but there's now way for a user to explicitly run only `pub get` within a Flutter context. Today that's not a big deal, since they can run `pub get` outside of Flutter, but when pub adds support for Flutter SDK constraints (dart-lang/pub#1432) and Flutter packages from the `sdk` source (dart-lang/pub#1431) it won't work. Pub will need to be run from within the `flutter` executable in order to know where to find the Flutter SDK, so if a user wants to add a new dependency or upgrade their dependencies, they'll need a way to do so from within Flutter.

I propose adding explicit `flutter get` and `flutter upgrade` commands that essentially just wrap `pub get` and `pub upgrade`, respectively. As long as they set the `FLUTTER_ROOT` environment variable, pub will be able to find Flutter and everything will work nicely.

**Comment by eseidelGoogle** [comment]
`flutter upgrade` exists today, but also does some other things.  `flutter update-packges` is a hidden command just for the flutter repo.  @devoncarew would know more.

**Comment by nex3** [comment]
A possible alternative would be to add a `flutter pub` command that literally just runs pub commands within the context of Flutter.

**Comment by devoncarew** [comment]
Wrapping pub in some way makes sense to me.

Currently `flutter upgrade` both upgrades the versions of the packages you're using and moves your project forward to the latest version of flutter. I think it'd be useful to separate these two things out into separate commands.

**Comment by eseidelGoogle** [comment]
For context, @abarth once suggested we consider a virtual-env like solution in https://github.com/flutter/flutter/issues/3865#issuecomment-218644446 which might be useful here.  Presumably flutter developers will want flutter's dart on their command line?  Then again, that also may just be a separate issue.

**Comment by danrubel** [comment]
I suggest we follow [`brew`'s lead](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md) on this one...
`flutter update` = update to the latest version of flutter
`flutter upgrade` = upgrade your packages (runs `pub upgrade`)

**Comment by sethladd** [comment]
I've never liked brew's behavior :) I constantly forget to say `update` before I run `upgrade`.

An `upgrade` should imply `update`.

**Comment by danrubel** [comment]
@sethladd 
How about `flutter upgrade` continues to function as it does today, and we add
`flutter upgrade packages` (no hyphen) to upgrade just packages, and
`flutter upgrade sdk` to upgrade the flutter sdk without the packages.

**Comment by sethladd** [comment]
@danrubel that works for me, thanks.  (where "sdk" means flutter)

@johnmccutchan thoughts?

**Comment by danrubel** [comment]
@sethladd We could also add `flutter get packages` = `pub get`, although I envision `flutter upgrade packages` being used much more often.

**Comment by sethladd** [comment]
`flutter get packages` sgtm, it balances nicely with `flutter upgrade packages`.

Thanks!

**Comment by johnmccutchan** [comment]
We could group them:

```flutter packages upgrade```
```flutter packages get```
```flutter sdk upgrade```

But the `flutter` command line tool typically starts with a verb, so, 

```flutter get packages```
```flutter upgrade packages```
```flutter upgrade sdk```

SGTM.

**Comment by sethladd** [comment]
When this lands, please also update https://flutter.io/upgrading/ which is at https://github.com/flutter/website/blob/master/upgrading.md  (sending a PR from the github editor UI is fine :)

Thanks!

**Comment by danrubel** [comment]
@johnmccutchan suggested grouping them by "packages" and @devoncarew suggested the same over VC, so for now I'm going to leave `flutter upgrade` as it is and just implement

`flutter packages upgrade` ---> pub upgrade
`flutter packages get`---> pub get

along with updating docs as per @sethladd suggestion above.
