### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by zhangxiongwen** [flutter/flutter#49943]
1.   $ flutter create Flutter-01  
2.   $ flutter run
Here is the wrong information:

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                          11.1s
 └─Compiling, linking and signing...                         0.6s
Xcode build done.                                           13.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:580:3: error: unknown type name
    'dispatch_source_t'; did you mean 'dispatch_once_t'?
                    dispatch_source_t CM_NONNULL timerSource )
                    ^
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:41:18:
    note: 'dispatch_once_t' declared here
    typedef intptr_t dispatch_once_t;
                     ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:580:21: error: nullability specifier '_Nonnull'
    cannot be applied to non-pointer type 'dispatch_once_t' (aka 'long')
                    dispatch_source_t CM_NONNULL timerSource )
                                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:12:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMBase.h:262:20: note: expanded from macro 'CM_NONNULL'
    #define CM_NONNULL __nonnull
                       ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    <built-in>:333:19: note: expanded from here
    #define __nonnull _Nonnull
                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:596:3: error: unknown type name
    'dispatch_source_t'; did you mean 'dispatch_once_t'?
                    dispatch_source_t CM_NONNULL timerSource )
                    ^
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:41:18:
    note: 'dispatch_once_t' declared here
    typedef intptr_t dispatch_once_t;
                     ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:596:21: error: nullability specifier '_Nonnull'
    cannot be applied to non-pointer type 'dispatch_once_t' (aka 'long')
                    dispatch_source_t CM_NONNULL timerSource )
                                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:12:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMBase.h:262:20: note: expanded from macro 'CM_NONNULL'
    #define CM_NONNULL __nonnull
                       ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    <built-in>:333:19: note: expanded from here
    #define __nonnull _Nonnull
                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:621:3: error: unknown type name
    'dispatch_source_t'; did you mean 'dispatch_once_t'?
                    dispatch_source_t CM_NONNULL timerSource,
                    ^
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:41:18:
    note: 'dispatch_once_t' declared here
    typedef intptr_t dispatch_once_t;
                     ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:621:21: error: nullability specifier '_Nonnull'
    cannot be applied to non-pointer type 'dispatch_once_t' (aka 'long')
                    dispatch_source_t CM_NONNULL timerSource,
                                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:12:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMBase.h:262:20: note: expanded from macro 'CM_NONNULL'
    #define CM_NONNULL __nonnull
                       ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    <built-in>:333:19: note: expanded from here
    #define __nonnull _Nonnull
                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:640:3: error: unknown type name
    'dispatch_source_t'; did you mean 'dispatch_once_t'?
                    dispatch_source_t CM_NONNULL timerSource )
                    ^
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:41:18:
    note: 'dispatch_once_t' declared here
    typedef intptr_t dispatch_once_t;
                     ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:23:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMSync.h:640:21: error: nullability specifier '_Nonnull'
    cannot be applied to non-pointer type 'dispatch_once_t' (aka 'long')
                    dispatch_source_t CM_NONNULL timerSource )
                                      ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CoreMedia.h:12:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreMedia
    .framework/Headers/CMBase.h:262:20: note: expanded from macro 'CM_NONNULL'
    #define CM_NONNULL __nonnull
                       ^
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    While building module 'CoreMedia' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:
    <built-in>:333:19: note: expanded from here
    #define __nonnull _Nonnull
                      ^
    8 errors generated.
    While building module 'Flutter' imported from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:
    In file included from <module-includes>:1:
    In file included from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/Flutter.h:54:
    In file included from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterAppDelegate.h:11:
    In file included from
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterPlugin.h:15:
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Flutter/Flutte
    r.framework/Headers/FlutterTexture.h:8:9: fatal error: could not build
    module 'CoreMedia'
    #import <CoreMedia/CoreMedia.h>
     ~~~~~~~^
    9 errors generated.
    /Users/admin-zxw/Desktop/flutterpro/Flutter-01/flutterpro/ios/Runner/main.m:
    1:9: fatal error: could not build module 'Flutter'
    #import <Flutter/Flutter.h>
     ~~~~~~~^
    10 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.


$ flutter doctor -v


[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.7 at /Users/admin-zxw/Flutter/flutter
    • Framework revision 9f5ff2306b (5 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin-zxw/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • DA2DD8DF-FB0F-49AC-9501-C6118D3AA099 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

**Comment by zhangxiongwen** [comment]
How can I solve it?  thank you!!!

**Comment by zhangxiongwen** [comment]
Reinstalling xcode solves this problem！

**Comment by iapicca** [comment]
Hi @zhangxiongwen 
I'm glad to hear that you solved the issue
thank you for letting me know
