### ISSUE TITLE
Ink.image keeps cache of the image somewhere else

### ISSUE THREAD

**Issue by BabkenM** [flutter/flutter#49944]
I don't know why, but it seems that Ink.image keeps cache some where else, because I tried every thing but nothing works.

**This is my code example, sorry for so little part of code, cannot give more:**
```
Widget _avatar(String url) {
    return CircleAvatar(
      backgroundColor: Colors.transparent,
      radius: 100,
      child: Material(
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(100))
        ),
        color: Colors.transparent,
        child: Ink.image(
          image: _getAvatar(url),
          width: _width/2,
          height: _width/2,
          fit: BoxFit.cover,
          child: InkWell(
            onTap: (){
              _chooseImage();
            },
          ),
        ),
      ),
    );
  }

ImageProvider _getAvatar(String url) {
    if (_image == null && url != null) {
      return CachedNetworkImageProvider(url, scale: 1);
    } else if(_image != null){
      return FileImage(_image);
    } else {
      return AssetImage('${assetsImagePath}no_image.png');
    }
  }

void _chooseImage() async{
     await ImagePicker.pickImage(
            source: ImageSource.gallery,
            imageQuality: 50,
            maxHeight: 250,
            maxWidth: 250).then((imageFile) {
        setState(() {
            _image = imageFile;
        });
    });
}
```

**I used this packages:**

- flutter_cache_manager: 1.1.3
- image_picker: 0.6.3+1
- cached_network_image: 2.0.0
- path_provider 1.6.0

**I tried several things such as:**
1)
```
DefaultCacheManger manager = new DefaultCacheManager();
manager.emptyCache();
```

2)
```
final Directory tempDir = await getTemporaryDirectory();
final Directory libCacheDir = new Directory("${tempDir.path}/libCachedImageData");
await libCacheDir.delete();
```

3)
```
Future<void> _deleteCacheDir() async {
    final cacheDir = await getTemporaryDirectory();

    if (cacheDir.existsSync()) {
      cacheDir.deleteSync(recursive: true);
    }
  }

  Future<void> _deleteAppDir() async {
    final appDir = await getApplicationSupportDirectory();

    if(appDir.existsSync()){
      appDir.deleteSync(recursive: true);
    }
  }
```

4)
```
DefaultCacheManger manager = new DefaultCacheManager();
await manager.removeFile(url);
```
This all clearing cache, I checked several times and There is no cache, but, some how, the Ink.image keeps it. 
When Im removing the `Ink.image` everything works correctly. But any way, I can't say in 100% that this is `Ink.image` fault, it can be `CachedNetworkImageProvider` also.

**This is my flutter doctor -v:**

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.973], locale ru-RU)
    • Flutter version 1.12.13+hotfix.5 at A:\src\flutter
    • Framework revision 27321ebbad (8 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bmura\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: A:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at A:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Please tell me if I need to add or change some thing. Also if you need more info about this issue, please ask.**

**Comment by iapicca** [comment]
Hi @BabkenM 
[cached_network_image](https://pub.dev/packages/cached_network_image) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/renefloor/flutter_cached_network_image/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by BabkenM** [comment]
Sorry. I didn't think of that.
I opened an issue on [cached_network_image.](https://github.com/renefloor/flutter_cached_network_image/issues)
This is the [issue](https://github.com/renefloor/flutter_cached_network_image/issues/331)
