### ISSUE TITLE
Videos recorded on Android do not play on Iphone / Ipad

### ISSUE THREAD

**Issue by juppdes** [flutter/flutter#49945]
Videos recorded with the camera plugin on android devices do not run on iphones / ipads with the video_player plugin, nor directly in the browser.  Tested with IOS 13.

flutter doctor -v output

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17134.1], locale pt-BR)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (5 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jupp\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Jupp\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Jupp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Jupp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @juppdes 
Do you mean not video_camera (there isn't such on pub.dev) but camera plugin, right?

**Comment by juppdes** [comment]
Hi @VladyslavBondarenko.. sorry.. i wanted to refer to the camera plugin in case of video recording and the video_player plugin in playback (not video_camera).

**Comment by ariefwijaya** [comment]
> Hi @VladyslavBondarenko.. sorry.. i wanted to refer to the camera plugin in case of video recording and the video_player plugin in playback (not video_camera). I fixed the issue.

Could you share how you fix the issue ?

**Comment by maheshmnj** [comment]
Hi @juppdes, could you please provide a minimal reproducible code.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
