### ISSUE TITLE
Can not run Flutter app on Android 

### ISSUE THREAD

**Issue by NLe1** [flutter/flutter#49959]
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/Users/nhanle/Documents/flutter/my_app/android/build.gradle' line: 26
                                                                        
* What went wrong:                                                      
A problem occurred evaluating root project 'android'.                   
> A problem occurred configuring project ':app'.                        
   > Could not open proj remapped class cache for 4ewgkljtn39cvri1vhdz3a2ai (/Users/nhanle/.gradle/caches/5.6.2/scripts-remapped/build_4get2hse7s5oi0lr1vsgkcahy/4ewgkljtn39cvri1vhdz3a2ai/proj016c9397e71a56ec48c54a2e61383932).
      > Could not open proj generic class cache for build file '/Users/nhanle/Documents/flutter/my_app/android/app/build.gradle' (/Users/nhanle/.gradle/caches/5.6.2/scripts/4ewgkljtn39cvri1vhdz3a2ai/proj/proj016c9397e71a56ec48c54a2e61383932).
         > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 755ms

**Comment by dnfield** [comment]
It seems like a gradle issue - can you try to clean your project (`flutter clean`) and run again?

This seems like something that could happen if you somehow upgraded gradle between runs, or if gradle somehow left you in a bad state after the last attempt.

**Comment by NLe1** [comment]
@dnfield  I ran flutter clean, flutter upgrade and flutter doctor but seems like nothing has changed, I have not upgraded any gradle version before.

**Comment by NLe1** [comment]
this is my android/build.gradle

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by jonahwilliams** [comment]
See also: https://stackoverflow.com/questions/32900912/bug-exception-in-phase-semantic-analysis

And also: https://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies/13567793#13567793

Since this is a system wide cache it would not be safe for flutter to clean it unfortunately.

**Comment by NLe1** [comment]
Hi @jonahwilliams your solutions worked, it is unfortunate, like you said, that flutter can not clean the cache build itself.
