### ISSUE TITLE
WillPopScope assumes immediate disposal on route change

### ISSUE THREAD

**Issue by micimize** [flutter/flutter#49952]
On the `master` channel, I'm getting the error when navigating away from a page with a `Form` (and thus a `WillPopScope`) with `Navigator.maybePop(context)`, when the `Form` is not unmounted before route disposal:
```
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 59 pos 12: '_route == ModalRoute.of(context)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    Form-[LabeledGlobalKey<FormState>#4274e] 
lib/task/edit_task_page.dart:92
When the exception was thrown, this was the stack
#2      _WillPopScopeState.didUpdateWidget 
package:flutter/…/widgets/will_pop_scope.dart:59
#3      StatefulElement.update 
package:flutter/…/widgets/framework.dart:4571
#4      Element.updateChild 
package:flutter/…/widgets/framework.dart:3141
#5      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4412
#6      Element.rebuild 
package:flutter/…/widgets/framework.dart:4116
...
```

I believe this is because I am not using the typical flutter navigation animations and am instead using in-place animations along with a non-animating custom route:
```dart
class NoAnimationMaterialPageRoute<T> extends MaterialPageRoute<T> {
  NoAnimationMaterialPageRoute({
    @required WidgetBuilder builder,
    RouteSettings settings,
    bool maintainState = true,
    bool fullscreenDialog = false,
  }) : super(
          builder: builder,
          maintainState: maintainState,
          settings: settings,
          fullscreenDialog: fullscreenDialog,
        );

  @override
  Widget buildTransitions(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return child;
  }

  @override
  Duration get transitionDuration => const Duration(milliseconds: 0);
}
```

This is admittedly a bit of a niche/hackish use-case, but I think it would also apply to a form nested in a `Hero`

<details>
<summary><code>flutter doctor -v</code></summary>

```
[✓] Flutter (Channel master, v1.14.7-pre.69, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.14.7-pre.69 at /Users/mjr/flutter
    • Framework revision 1eb5bb653c (24 hours ago), 2020-01-31 12:14:08 -0800
    • Engine revision 804dca62a1
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mjr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Michael’s iPhone • 00008020-000858D10281002E • ios • iOS 13.1.3
```

</details>

**Comment by micimize** [comment]
working around with the following for now:
```dart
class PopIssueWorkaroundState extends State<PopIssueWorkaround> {

  final _formKey = GlobalKey<FormState>();

  // workaround for https://github.com/flutter/flutter/issues/49952
  ModalRoute _mountRoute;

  @override
  void didChangeDependencies() {
    _mountRoute ??= ModalRoute.of(context);
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    _formKey.currentState?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final formKey = _mountRoute == ModalRoute.of(context)
        ? _formKey
        : Key('hack-to-dispose-of-will-pop-callback');
    return Form( key: formKey, ...);
  }
}
```

I think one potential solution here would be to simply not wrap `_FormScope` in a `WillPopScope` if there is no `onWillPop` provided to `Form` in it's `build`, making the coupling optional
```diff
  @override
  Widget build(BuildContext context) {
    if (widget.autovalidate)
      _validate();
-   return WillPopScope(
-     onWillPop: widget.onWillPop,
-     child: _FormScope(
-       formState: this,
-       generation: _generation,
-       child: widget.child,
-     ),
-   );
+   final scope = _FormScope(
+     formState: this,
+     generation: _generation,
+     child: widget.child,
+   );
+   return widget.onWillPop != null
+       ? WillPopScope(
+           onWillPop: widget.onWillPop,
+           child: scope,
+         )
+       : scope;
  }
```

**Comment by micimize** [comment]
@chunhtai here you go https://gist.github.com/micimize/62bdb23c610dbe89a858e0fec70fce18

I was right about it applying to `Hero(child: Form())` so I used that for reproduction.

**Comment by Jairolaya12x** [comment]
Any solution? I have the same problem with flutter in the 1.17.1 release

**Comment by thakurkartik1901** [comment]
I also have the same problem in the 1.17.1 release

**Comment by chunhtai** [comment]
Please use the thumb up to but the priority

**Comment by ialameh** [comment]
having same issue

**Comment by lyf571321556** [comment]
having same issue

**Comment by SweetSourPeter** [comment]
same issue here

**Comment by ziyadfarhan296** [comment]
Same issue here as well.

**Comment by Puddstarr** [comment]
I have the same issue. The  workaround supplied by @micimize didnt work.
The new error was :
type 'ValueKey<String>' is not a subtype of type 'GlobalKey<FormState>'
To make the workaround work i used:
`    _formKey = _mountRoute == ModalRoute.of(context)
    ? _formKey
    : new GlobalKey<FormState>();`

instead of 
`    final formKey = _mountRoute == ModalRoute.of(context)
        ? _formKey
        : Key('hack-to-dispose-of-will-pop-callback');`

**Comment by brunodmn** [comment]
Same here, I have a form on a popup. When I close the popup and press the button to open it again really quick it crashes. This popup has animation.
 If I remove formKey UI runs smooth.

**Comment by ziyadfarhan296** [comment]
Yes, I have figured out as well that formKey is not stable. I have a form where you can submit something and it uses formKey, however, sometimes when I open this page it works perfectly fine, and sometimes I open this page, and then there is a modal.formKey issue - something like that, so sometimes it works and sometimes it doesn't. Quite unstable. I think that is the reason for most issues.

**Comment by nyelnizy** [comment]
Same issue, any solution ??

**Comment by eli1stark** [comment]
Same issue, please fix this

**Comment by Shvet** [comment]
More than year has passed any solution?

**Comment by GeorgePagounis** [comment]
I have the same problem when using a hero widget and a formKey on second page. My solution is to first put Form then Hero and then wrap a Material  `Scaffold(
        body: Form(
          key: formKey,
          child: Hero(
            tag: '${eta.dmy}${eta.index}',
            child: Material(`

**Comment by micimize** [comment]
@abarth may have thoughts based on https://github.com/flutter/flutter/pull/8311#discussion_r102334270.

I'm wondering if this assert could be moved to `dependenciesChanged` if the point is to ensure the existence of the `_route`. Or perhaps the will pop callback can be wrapped to disarm the assert, i.e.
```dart
class _WillPopScopeState extends State<WillPopScope> {
  ModalRoute<dynamic> _route;
  bool popping = false;
  //...
  void didUpdateWidget(WillPopScope oldWidget) {
    // disarm assert if there is no callback to set popping
    // or we're popping off
    assert(widget.onWillPop == null || popping || _route == ModalRoute.of(context));
    // ...
      if (widget.onWillPop != null)
        _route.addScopedWillPopCallback((){
          popping = onWillPop();
          return popping; 
        });
  }
  // ...
}
```

**Comment by wwwqyhme** [comment]
maybe when dialog completed should be called after content tree fully disposed ...

**Comment by hangyujin** [comment]
I can't reproduce this issue with the code example in https://gist.github.com/micimize/62bdb23c610dbe89a858e0fec70fce18 or the code example in #63565
