### ISSUE TITLE
[androidx-migration] No need to refactor plugins? How to refactor my "app" only?

### ISSUE THREAD

**Issue by kbrmimbyl** [flutter/flutter#49969]
I'm trying to migrate my flutter app with dozens of third-party plugins.

As suggested in the official docs (https://flutter.dev/docs/development/androidx-migration), I choose Refactor->Migrate to AndroidX, and this is what I see:

![Screenshot from 2020-02-02 16-15-01](https://user-images.githubusercontent.com/15169779/73607082-c8f4e800-45d7-11ea-9c77-382ecbd18d1a.png)

Clearly, it's going to refactor even the plugins (that's the "Usage in Import 43 usages") by modifying files in $HOME/.pub-cache. It doesn't matter whether I right click on the app folder in the left sidebar and say Refactor, or whether I choose the Refactor option from the top menu.

Editing plugin code is a problem because my production code points to the plugins in $HOME/.pub-cache. I can't afford changes to the production environment.

Also, looks like there's no need to refactor plugins. Here's what the official migration doc says (link above):

> The Flutter tool uses Jetifier to automatically migrate Flutter plugins using the Support Library to AndroidX, so you can use the same plugins even if they haven’t been migrated to AndroidX yet.

Two simple questions:

1. Am I right in thinking that only my "app" needs to be refactored, not the plugins?
2. If yes, how do I refactor only my "app"?

Any help will be greatly appreciated. I've been patiently waiting, learning and postponing migration to AndroidX for a year now (because nothing has worked till now), but now the time has come to move to AndroidX... please help!

In case it helps: I'm using Flutter 1.7.8, Gradle Version 4.10.2, Android Gradle Plugin version 3.2.1. I don't have the courage to change any of these for now :-)

**Comment by iapicca** [comment]
HI @kbrmimbyl 
for information on [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) and it's features 
you may reference to the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

You mentioned that you are using an old version of flutter `v1.7.8`
please note that `androidx` is default from the latest stable version `v1.12.13`;
moreover some 3rd party plugins might not be "androidx ready".

If you decide to upgrade you flutter version I recommend to run
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`

If you are experiencing any issue
please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by kbrmimbyl** [comment]
Hey thanks for pitching in @iapicca. I don't want to upgrade flutter. I just want to upgrade my app to AndroidX. I'm not sure why you want to reproduce my problem, because there isn't any problem:-)

I'm trying to understand what the "Do Refactor" button will do. Will it edit plugin code in $HOME/.pub-cache? If yes, is there a way of preventing that from happening?

**Comment by iapicca** [comment]
Hi @kbrmimbyl 
I'm glad to here that you are not encountering a problem with Flutter,
for Android Studio's Flutter plugin related issue
please refer to the link I've provided above.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
