### ISSUE TITLE
problem in android manifest file  

### ISSUE THREAD

**Issue by priyanshu2018** [flutter/flutter#49965]
<img width="488" alt="Capture" src="https://user-images.githubusercontent.com/47901875/73606234-47e52300-45ce-11ea-8d8c-947f9ca99c0a.PNG">
<img width="446" alt="Capture1" src="https://user-images.githubusercontent.com/47901875/73606235-49aee680-45ce-11ea-9963-221dbccc6e9b.PNG">

**Comment by priyanshu2018** [comment]
here is my flutter doctor
<img width="626" alt="Capture2" src="https://user-images.githubusercontent.com/47901875/73606269-a01c2500-45ce-11ea-87f7-7cd58cdc0af3.PNG">

**Comment by dnfield** [comment]
This is not an actionable bug - it's not clear what the problem is.  Please consider adding some more information about the error you are seeing and a minimal reproduction.
