### ISSUE TITLE
Flutter multi - threading 

### ISSUE THREAD

**Issue by Iampato** [flutter/flutter#49963]
## Use case

Please improve in Isolates or just find a new way of threading in dart

I problem we(team) are experiencing at work  are firebase FCM since we are building a realtime app
I donot want to write kotlin(platform methods/channels) so as to make the notifications realtime even when the app goes into the background

## Proposal

Just invest more on isolates or came up with a new a way of running dart in the background and even when the app is in the background (like for my use case above)

**Comment by dnfield** [comment]
This is not an actionable bug in its current state.

If you could provide some sample code that is t working or is underperforming we could consider reopening.
