### ISSUE TITLE
scheduleBuildFor exception in Pesto Favorites

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#4996]
Run Gallery, select Pesto, and select the Favorites option in the menu

Results in this exception:

07-21 16:05:33.426 26529 26559 I flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
07-21 16:05:33.449 26529 26559 I flutter : The following assertion was thrown building Theme(ThemeData(Brightness.light Color(0xff009688)
07-21 16:05:33.449 26529 26559 I flutter : etc...)):
07-21 16:05:33.469 26529 26559 I flutter : scheduleBuildFor() called for a widget for which a build was already scheduled.

**Comment by Hixie** [comment]
Wow we need to make that error message clearer.

**Comment by Hixie** [comment]
(just leave the bug open, I'll get to it eventually if nobody else does)
