### ISSUE TITLE
Not able to Run Test

### ISSUE THREAD

**Issue by mustafa-almulla** [flutter/flutter#49976]
When trying to run a test I get the following error: Could not find a file named "pubspec.yaml" in "/Users/<user>/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-1.0.3".

However, when running the application I don't get any issue.

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`.

**Comment by mustafa-almulla** [comment]
Please find the output of the command 

[✓] Flutter (Channel master, v1.14.7-pre.83, on Mac OS X 10.15.2 19C57, locale en-SA)
    • Flutter version 1.14.7-pre.83 at /Users/mustafa/Development/flutter
    • Framework revision e10df3c1a6 (3 days ago), 2020-02-01 11:23:01 +0800
    • Engine revision e625e174c5
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mustafa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/mustafa/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6137316/Android Studio 4.0
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/mustafa/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6137316/Android Studio 4.0
      Preview.app/Contents
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Users/mustafa/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.70
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @mustafa-almulla 
could you please provide your 
`flutter test --verbose <YOUR TEST>`
thank you

**Comment by mustafa-almulla** [comment]
> Hi @mustafa-almulla
> could you please provide your
> `flutter test --verbose <YOUR TEST>`
> thank you

Hi @iapicca 

Please see the output as you requested

[  +26 ms] executing: [/Users/mustafa/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e10df3c1a65f9d7db3fc5340cffef966f7bd40a6
[        ] executing: [/Users/mustafa/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-83-ge10df3c1a
[   +7 ms] executing: [/Users/mustafa/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/mustafa/Development/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +47 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +66 ms] running test package with arguments: [-r, compact, --concurrency=6, --test-randomize-ordering-seed=0, --,
/Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart]
00:00 +0: loading /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart                                    [ +163 ms] test 0: starting test /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart
[  +20 ms] test 0: starting shell process
[   +5 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/Shared/Projects/ideeclub/ideeclub
[   +4 ms] Compiler will use the following file as its incremental dill file:
/var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart
[  +14 ms] /Users/mustafa/Development/flutter/bin/cache/dart-sdk/bin/dart
/Users/mustafa/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/mustafa/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
-Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48/output.dill --packages
/Users/Shared/Projects/ideeclub/ideeclub/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-clo
sure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill
/Users/Shared/Projects/ideeclub/ideeclub/build/testfile.dill.track.dill
[  +14 ms] <- compile /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart
00:01 +0: loading /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart                                    [+1352 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart took 1382ms
[   +1 ms] /Users/mustafa/Development/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory
--enable-checked-mode --verify-entry-points --enable-software-rendering --skia-deterministic-rendering
--enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/Shared/Projects/ideeclub/ideeclub/.packages
/var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart.dill
[   +1 ms] Using this directory for fonts configuration:
/var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_fonts.O8i5T9
[   +5 ms] test 0: awaiting initial result for pid 38248
[ +546 ms] test 0: process with pid 38248 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 38248
00:02 +0 -1: Creating Store [E]                                                                                             
  type 'List<Product>' is not a subtype of type 'ListBuilder<Product>' in type cast
  package:ideeclub/src/store/module/store_module.dart 20:30    StoreModule.createStore.<fn>
  package:ideeclub/src/store/models/store_model.g.dart 242:33  StoreBuilder.update
  package:ideeclub/src/store/models/store_model.g.dart 109:28  new _$Store
  package:ideeclub/src/store/module/store_module.dart 15:14    StoreModule.createStore
  test/store_module_test.dart 16:17                            main.<fn>
  
[ +168 ms] test 0: process with pid 38248 no longer needed by test harness
[        ] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[   +8 ms] test 0: deleting temporary directory
[   +2 ms] test 0: shutting down test harness socket server
[   +2 ms] test 0: finished
00:02 +0 -1: Some tests failed.                                                                                             
[  +11 ms] Deleting /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48...
[   +2 ms] killing pid 38244
[  +25 ms] Deleting /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_fonts.O8i5T9...
[   +4 ms] test package returned with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:271:7)
<asynchronous suspension>
#2      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#3      _rootRun (dart:async/zone.dart:1126:13)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _runZoned (dart:async/zone.dart:1518:10)
#6      runZoned (dart:async/zone.dart:1465:12)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#8      FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:847:20)
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#10     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1465:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#19     new Future.sync (dart:async/future.dart:224:31)
#20     CommandRunner.run (package:args/command_runner.dart:112:14)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1502:12)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _runZoned (dart:async/zone.dart:1518:10)
#32     runZoned (dart:async/zone.dart:1465:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#34     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#35     run (package:flutter_tools/runner.dart:51:10)
#36     main (package:flutter_tools/executable.dart:65:9)
#37     main (file:///Users/mustafa/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



[  +21 ms] executing: [/Users/mustafa/Development/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57

**Comment by phillwiggins** [comment]
Hey, any luck with this? I'm seeing the same issue.

**Comment by phillwiggins** [comment]
I managed to remove the dependency of _fe_analyzer to be hit with

Could not find a file named "pubspec.yaml" in "/Users/username/.pub-cache/hosted/pub.dartlang.org/archive-2.0.11".

Struggling to run tests at all here.

**Comment by mustafa-almulla** [comment]
> > Hi @mustafa-almulla
> > could you please provide your
> > `flutter test --verbose <YOUR TEST>`
> > thank you
> 
> Hi @iapicca
> 
> Please see the output as you requested
> 
> [ +26 ms] executing: [/Users/mustafa/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [ +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [ ] [e10df3c](https://github.com/flutter/flutter/commit/e10df3c1a65f9d7db3fc5340cffef966f7bd40a6)
> [ ] executing: [/Users/mustafa/Development/flutter/] git describe --match v*._._ --first-parent --long --tags
> [ +16 ms] Exit code 0 from: git describe --match v*._._ --first-parent --long --tags
> [ ] v1.14.6-83-ge10df3c1a
> [ +7 ms] executing: [/Users/mustafa/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [ +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [ ] origin/master
> [ ] executing: [/Users/mustafa/Development/flutter/] git ls-remote --get-url origin
> [ +5 ms] Exit code 0 from: git ls-remote --get-url origin
> [ ] https://github.com/flutter/flutter.git
> [ +47 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
> [ ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
> [ ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [ ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
> [ ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [ ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
> [ +66 ms] running test package with arguments: [-r, compact, --concurrency=6, --test-randomize-ordering-seed=0, --,
> /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart]
> 00:00 +0: loading /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart [ +163 ms] test 0: starting test /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart
> [ +20 ms] test 0: starting shell process
> [ +5 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/Shared/Projects/ideeclub/ideeclub
> [ +4 ms] Compiler will use the following file as its incremental dill file:
> /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48/output.dill
> [ ] Listening to compiler controller...
> [ +2 ms] Compiling /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart
> [ +14 ms] /Users/mustafa/Development/flutter/bin/cache/dart-sdk/bin/dart
> /Users/mustafa/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
> /Users/mustafa/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
> -Ddart.developer.causal_async_stacks=true --output-dill
> /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48/output.dill --packages
> /Users/Shared/Projects/ideeclub/ideeclub/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
> --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-clo
> sure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill
> /Users/Shared/Projects/ideeclub/ideeclub/build/testfile.dill.track.dill
> [ +14 ms] <- compile /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart
> 00:01 +0: loading /Users/Shared/Projects/ideeclub/ideeclub/./test/store_module_test.dart [+1352 ms] <- accept
> [ ] <- reset
> [ ] Compiling /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart took 1382ms
> [ +1 ms] /Users/mustafa/Development/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory
> --enable-checked-mode --verify-entry-points --enable-software-rendering --skia-deterministic-rendering
> --enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/Shared/Projects/ideeclub/ideeclub/.packages
> /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_listener.NRRac5/listener.dart.dill
> [ +1 ms] Using this directory for fonts configuration:
> /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_fonts.O8i5T9
> [ +5 ms] test 0: awaiting initial result for pid 38248
> [ +546 ms] test 0: process with pid 38248 connected to test harness
> [ +1 ms] test 0: awaiting test result for pid 38248
> 00:02 +0 -1: Creating Store [E]
> type 'List' is not a subtype of type 'ListBuilder' in type cast
> package:ideeclub/src/store/module/store_module.dart 20:30 StoreModule.createStore.
> package:ideeclub/src/store/models/store_model.g.dart 242:33 StoreBuilder.update
> package:ideeclub/src/store/models/store_model.g.dart 109:28 new _$Store
> package:ideeclub/src/store/module/store_module.dart 15:14 StoreModule.createStore
> test/store_module_test.dart 16:17 main.
> 
> [ +168 ms] test 0: process with pid 38248 no longer needed by test harness
> [ ] test 0: cleaning up...
> [ ] test 0: ensuring end-of-process for shell
> [ +8 ms] test 0: deleting temporary directory
> [ +2 ms] test 0: shutting down test harness socket server
> [ +2 ms] test 0: finished
> 00:02 +0 -1: Some tests failed.
> [ +11 ms] Deleting /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_compiler.I4Fg48...
> [ +2 ms] killing pid 38244
> [ +25 ms] Deleting /var/folders/4g/_rp6hmlj773fp87kl20gjq9w0000gn/T/flutter_test_fonts.O8i5T9...
> [ +4 ms] test package returned with exit code 1
> 
> #0 throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
> #1 TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:271:7)
> 
> #2 AppContext.run. (package:flutter_tools/src/base/context.dart:150:29)
> #3 _rootRun (dart:async/zone.dart:1126:13)
> #4 _CustomZone.run (dart:async/zone.dart:1023:19)
> #5 _runZoned (dart:async/zone.dart:1518:10)
> #6 runZoned (dart:async/zone.dart:1465:12)
> #7 AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #8 FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:847:20)
> #9 CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> #10 FlutterCommandRunner.runCommand.
> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
> 
> #11 AppContext.run. (package:flutter_tools/src/base/context.dart:150:29)
> #12 _rootRun (dart:async/zone.dart:1126:13)
> #13 _CustomZone.run (dart:async/zone.dart:1023:19)
> #14 _runZoned (dart:async/zone.dart:1518:10)
> #15 runZoned (dart:async/zone.dart:1465:12)
> #16 AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #17 FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
> #18 CommandRunner.run. (package:args/command_runner.dart:112:25)
> #19 new Future.sync (dart:async/future.dart:224:31)
> #20 CommandRunner.run (package:args/command_runner.dart:112:14)
> #21 FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
> #22 run.. (package:flutter_tools/runner.dart:64:22)
> #23 _rootRun (dart:async/zone.dart:1126:13)
> #24 _CustomZone.run (dart:async/zone.dart:1023:19)
> #25 _runZoned (dart:async/zone.dart:1518:10)
> #26 runZoned (dart:async/zone.dart:1502:12)
> #27 run. (package:flutter_tools/runner.dart:62:18)
> 
> #28 AppContext.run. (package:flutter_tools/src/base/context.dart:150:29)
> #29 _rootRun (dart:async/zone.dart:1126:13)
> #30 _CustomZone.run (dart:async/zone.dart:1023:19)
> #31 _runZoned (dart:async/zone.dart:1518:10)
> #32 runZoned (dart:async/zone.dart:1465:12)
> #33 AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #34 runInContext (package:flutter_tools/src/context_runner.dart:64:24)
> #35 run (package:flutter_tools/runner.dart:51:10)
> #36 main (package:flutter_tools/executable.dart:65:9)
> #37 main (file:///Users/mustafa/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> #38 _startIsolate. (dart:isolate-patch/isolate_patch.dart:299:32)
> #39 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> 
> [ +21 ms] executing: [/Users/mustafa/Development/flutter/] git rev-parse --abbrev-ref HEAD
> [ +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [ ] master
> [ +4 ms] executing: sw_vers -productName
> [ +13 ms] Exit code 0 from: sw_vers -productName
> [ ] Mac OS X
> [ ] executing: sw_vers -productVersion
> [ +13 ms] Exit code 0 from: sw_vers -productVersion
> [ ] 10.15.2
> [ ] executing: sw_vers -buildVersion
> [ +13 ms] Exit code 0 from: sw_vers -buildVersion
> [ ] 19C57

any update, is there anything else you need

**Comment by markusaksli-nc** [comment]
@mustafa-almulla @phillwiggins 
Are you still facing this issue on the latest version of flutter? The logs posted here actually don't contain the failure.
Thank you

**Comment by mustafa-almulla** [comment]
It seem to be ok now
