### ISSUE TITLE
Cannot create a new web project in flutter

### ISSUE THREAD

**Issue by shnkreddy98** [flutter/flutter#49977]
I have installed visual studio code with flutter plugin, SDK and everything according to the docs but i'm unable to start a project using the VScode IDE.. There is no option to create a new web project new project.. My main need is to build a website which may be converted to an app later.. Any solution for this problem .. Also i'm open for suggestions.. Is flutter good for the work i needed to be done ?

**Comment by jonahwilliams** [comment]
See the documentation at https://flutter.dev/docs/get-started/web

There is no "web project" option distinct from a regular flutter project - all flutter projects (on at least) are capable for being deployed as either a mobile or web application
