### ISSUE TITLE
TextField Cut/Copy/Paste popup menu doesn't wrap.

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#49971]
When using the Material TextField, I ran into an issue with cut/copy/paste.
The menu shows up, but it gets clipped at the end instead of wrapping to a newline.
This results in a yellow/black overflow box.

I encountered this on a Pixel 2 (running on Android 10) where the language was Dutch. The language / device seems in itself irrelevant to the issue, but picking a device with a smaller screen + a more verbose language might help with reproducing. As an example this doesn't occur with English since the menu gets enough space for 'Cut/Copy/Paste' but for the Dutch 'Knippen/Kopiëren/Plakken/AllesSelecteren' it doesn't.

Secondly the English menu seems to get 3 options, but the Dutch one gets 4?
This could be a separate issue I think.

It looks similar to #47365 but that is related to clipping the actual text of the menu, not the menu not getting enough space to display altogether.

![Screenshot_1580644543](https://user-images.githubusercontent.com/23480364/73607974-419a7b00-45bd-11ea-9883-90a4b396f44c.png)

## Steps to Reproduce

- start device / emulator
- set the device language to the one that needs to be tested(It surely occurs on Dutch)
- run an app with the widget below
- type some text first
- open the text menu for cut/copy/paste

FYI: you'll have to add extra locales to the widget,
if it needs to be tested on different languages. 

```
  MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate],
      supportedLocales: <Locale>[
        Locale("en", ""),
        Locale("nl", ""),
      ],
      home: Scaffold(
          appBar: AppBar( title: Text("TextField cut copy paste")),
          body: Center( child: TextFormField())
      )
  )
```

**Expected results:**
The menu gets shown properly without clipping problems

**Actual results:** 
The menu gets clipped with a yellow/black overflow box.

## Flutter doctor output

[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale nl-BE)
    • Flutter version 1.12.13+hotfix.7 at E:\Flutter\flutter
    • Framework revision 9f5ff2306b (6 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Android\AndroidStudio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at E:\Program Files (x86)\IntelliJ\IntelliJ IDEA Community Edition 2018.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by meghna-me** [comment]
I am facing the same issue even in default english US locale - the cut copy menu is overflowing renderflex.

**Comment by deandreamatias** [comment]
This bug exists and is tracked here #35826 . There have a discussion about this and possible solutions  (#49391).
Please close this problem if it is duplicated.

**Comment by justinmc** [comment]
Yeah thanks, I'll close this as it should be fixed soon in https://github.com/flutter/flutter/pull/49391.

Regarding the Dutch menu getting an extra item, @navaronbracke can you confirm this?  Make sure you're not selecting all the input in the field, if so "Select All" won't display.  If this is still a problem, then please open a separate issue.  I'd be interested to take a look at what's going on.
