### ISSUE TITLE
flutter build linux not giving runnable file for linux

### ISSUE THREAD

**Issue by msarkrish** [flutter/flutter#49997]
flutter build linux not giving runnable file like apk for linux
![Screenshot from 2020-02-03 17-44-29](https://user-images.githubusercontent.com/45334931/73652418-eb0c6a00-46ac-11ea-8b7a-df037936f9d5.png)

**Comment by VladyslavBondarenko** [comment]
Hi @msarkrish 
Please follow up on https://github.com/flutter/flutter/issues/38478 (as it is said in your log)
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by msarkrish** [comment]
Hi @VladyslavBondarenko then i have 2 questions 1). i can't install my desktop application in other system?  2). i can run my desktop application only in my system only.

**Comment by VladyslavBondarenko** [comment]
@msarkrish 
I'm not sure about this, I've not used flutter for desktop (and currently using only windows on my laptop)
Please see https://flutter.dev/community for resources and asking questions like these

**Comment by msarkrish** [comment]
@VladyslavBondarenko ok brother, in windows whether flutter desktop give runnable file for windows platform with flutter build windows?

**Comment by VladyslavBondarenko** [comment]
@msarkrish 
For now AFAIK only debug mode is provided for windows. To run my .exe application on another computer I need to copy the entire 'Runner' folder, which includes the .exe file together with all necessary assets

**Comment by jonahwilliams** [comment]
Debug mode also works for Linux, see https://github.com/flutter/flutter/wiki/Desktop-shells

The executable is in a subdirectory.
