### ISSUE TITLE
Enable Copy-toolbar for all widgets

### ISSUE THREAD

**Issue by MrAlek** [flutter/flutter#49996]
# Use case

On iOS it is a common pattern to be able to long-press content in various form and bring up the same Edit Menu as you get in text fields for copying & other actions.

![IMG_40CAC5CF2B14-1](https://user-images.githubusercontent.com/1496135/73646914-b54e8d80-467a-11ea-8809-804275a5d59b.jpeg)

# Proposal

I'm proposing the extraction of the current `CupertinoTextSelectionToolbar` and `_TextSelectionToolbar` into a `showEditMenu` function, working just like `showMenu` for popup menus.

**Comment by justinmc** [comment]
Good point.  You might be able to do this now by overriding CupertinoTextSelectionMenu, but it wouldn't be easy.   And you can use SelectableText to copy text, but it's not the same nice experience like this.

**Comment by justinmc** [comment]
We should also make sure that this works for images.

**Comment by MrAlek** [comment]
For images I think it makes more sense to use `CupertinoContextMenu`, like in iMessage. But definitely. If a general solution is found for all widgets, it should work for images too.

**Comment by justinmc** [comment]
You're right, I guess I was thinking of Android.  I just played around with long pressing images in iOS and every app I tried opened a CupertinoContextMenu.

**Comment by justinmc** [comment]
This will be possible with https://github.com/flutter/flutter/issues/49996.
