### ISSUE TITLE
Sky runtime for OS X

### ISSUE THREAD

**Issue by justinfagnani** [flutter/flutter#5]
I know Android is the only supported platform for now, so this is just to track the issue and get notified if things change.

**Comment by abarth** [comment]
You can build the engine for OS X and it basically works.  We probably won't polish it up as a product, however.

**Comment by justinfagnani** [comment]
Ever? For development it would be great to not have to use the phone all the time. Also, for desktop apps, like those that would be done in Electron today, Flutter could be quite nice.

**Comment by abarth** [comment]
Forever is a long time.  I think it's fair to say that we're focused on mobile first.  Once we've happy with where we are on mobile, we'll probably be interested in polishing up the desktop side.
