### ISSUE TITLE
Running `flutter upgrade` seems to error

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#500]
I'm on the alpha branch, and when I run `flutter upgrade` inside of my clone of the flutter repo, I get:

```
~/Code/flutter[alpha] $ flutter upgrade
No pubspec.yaml file found. This command should be run from the root of a project.
```

The last commit I have is `afaedbf21d47d6d16020365ae2f05e5200cc6a6f` from Fri Nov 13

**Comment by sethladd** [comment]
I ran `git pull` and then `flutter upgrade` and then I got:

```
~/Code/flutter[alpha] $ flutter upgrade
Updating flutter tool...
Resolving dependencies... 
Got dependencies!
No pubspec.yaml file found. This command should be run from the root of a project.
```

Is this normal?

**Comment by abarth** [comment]
Yes, `flutter upgrade` is intended to be run from the root of a Flutter project instead of in the flutter.git repo.
