### ISSUE TITLE
flutter create template creates configureFlutter engine in MainActivity - leading to plugins registered twice

### ISSUE THREAD

**Issue by jameshp** [flutter/flutter#50004]
Creating a new project with flutter create the main activity has code to configure the flutter engine.
e.g. 
```java
public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```
This shouldn't be there. And was suggested as fix here: https://github.com/flutter/flutter/issues/47801#issuecomment-568975233 

Further in the plugin migration documentation the main entry explains it to remove this code. 
On the other hand there is a link on https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration to https://flutter.dev/go/android-project-migration (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration) which shows it described in the opposite way (keeping the code above).

Flutter Version used: 1.12.13+hotfix.7

**Comment by nemoryoliver** [comment]
The docs are confusing.

Docs here says to remove the registration of plugins: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

On the other hand it says to add it: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by PandaGeek1024** [comment]
Yeah, this is quite confusing. Would appreciate if someone can clean this up.

**Comment by xster** [comment]
This is a problem indeed. We need to make sure repeated calls to GeneratedPluginRegistrant doesn't produce side-effects and remove the unnecessary `configureFlutterEngine` override in the project create template.

**Comment by xster** [comment]
The wiki discrepancy is very confusing too. The right instruction should be to not manually register. Corrected https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects.

**Comment by xster** [comment]
The double registration problem has been fixed since on master in https://github.com/flutter/engine/blob/d640569b6fb23bc5af735c7ff6c3b2b36f3e29c4/shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java#L117. If you sync to v1.14.6 which is available on dev and beta branches, plugins shouldn't double register anymore.
