### ISSUE TITLE
 Running "flutter pub get" in flutter_app...                      Because flutter_app depends on flutter_web_ui any which doesn't exist (could not find package flutter_web_ui at https://pub.dartlang.org), version solving failed.

### ISSUE THREAD

**Issue by DBSumation** [flutter/flutter#50005]
Error:
![image](https://user-images.githubusercontent.com/37802537/73660699-b37acf00-4666-11ea-8978-af0d219da729.png)

```
Running "flutter pub get" in flutter_app...                     
Because flutter_app depends on flutter_web_ui any which doesn't exist (could not find package flutter_web_ui at https://pub.dartlang.org), version solving failed.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Because flutter_app depends on flutter_web_ui any which doesn't exist (could not find package flutter_web_ui at https://pub.dartlang.org), version solving failed.

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

Because flutter_app depends on flutter_web_ui any which doesn't exist (could not find package flutter_web_ui at https://pub.dartlang.org), version solving failed.

pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
```
> 

      Flutter Web:

        version: 1.0.0+1

        environment:
          sdk: ">=2.1.0 <3.0.0"

        dependencies:
          flutter:
            sdk: flutter
          http: any
          flutter_web: any
          flutter_web_ui: any
          provider: any

          # The following adds the Cupertino Icons font to your application.
          # Use with the CupertinoIcons class for iOS style icons.
          cupertino_icons: ^0.1.2

        dev_dependencies:

        build_runner: ^1.4.0
        build_web_compilers: ^2.0.0
        pedantic: ^1.0.0

        dependency_overrides:
        flutter_web:
          git:
          url: https://github.com/flutter/flutter_web
          path: packages/flutter_web
        flutter_web_ui:
          git:
          url: https://github.com/flutter/flutter_web
          path: packages/flutter_web_ui

        # For information on the generic Dart part of this file, see the
        # following page: https://dart.dev/tools/pub/pubspec

        # The following section is specific to Flutter.
        flutter:

          # The following line ensures that the Material Icons font is
          # included with your application, so that you can use the icons in
          # the material Icons class.
          uses-material-design: true

Flutter  Doctor:
"Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13, on Mac OS X 10.15.3 19D76, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
"

**Comment by VladyslavBondarenko** [comment]
Hi @DBSumation 
Try to edit your dependency_overrides as in [migration guide](https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md) to
```
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

Does it help?

I'm not sure why do you need to use [flutter_web](https://github.com/flutter/flutter_web) when you can use it [standart Flutter SDK on beta channel](https://flutter.dev/docs/get-started/web)

**Comment by jonahwilliams** [comment]
flutter_web the package is deprecated since the web backend has been merged with flutter For documentation on how to use Flutter for web, see flutter.dev/web

**Comment by DBSumation** [comment]
Thanks!! Problem solved. 

> Hi @DBSumation
> Try to edit your dependency_overrides as in [migration guide](https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md) to
> 
> ```
> dependency_overrides:
>   flutter_web:
>     git:
>       url: https://github.com/flutter/flutter_web
>       path: packages/flutter_web
>   flutter_web_ui:
>     git:
>       url: https://github.com/flutter/flutter_web
>       path: packages/flutter_web_ui
> ```
> 
> Does it help?
> 
> I'm not sure why do you need to use [flutter_web](https://github.com/flutter/flutter_web) when you can use it [standart Flutter SDK on beta channel](https://flutter.dev/docs/get-started/web)

Thanks for the insight working now! #FlutterLove #flutterAddict #flutterweb

**Comment by shyamkawale** [comment]
PS C:\Users\HP\flutter_code\webproj> flutter pub get
Because webproj depends on flutter_web from git which depends on flutter_web_ui any, flutter_web_ui from hosted is required.
So, because webproj depends on flutter_web_ui from git, version solving failed.
Running "flutter pub get" in webproj...
pub get failed (1; So, because webproj depends on flutter_web_ui from git, version solving failed.)

**Comment by shyamkawale** [comment]
> Hi @DBSumation
> Try to edit your dependency_overrides as in [migration guide](https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md) to
> 
> ```
> dependency_overrides:
>   flutter_web:
>     git:
>       url: https://github.com/flutter/flutter_web
>       path: packages/flutter_web
>   flutter_web_ui:
>     git:
>       url: https://github.com/flutter/flutter_web
>       path: packages/flutter_web_ui
> ```
> 
> Does it help?
> 
> I'm not sure why do you need to use [flutter_web](https://github.com/flutter/flutter_web) when you can use it [standart Flutter SDK on beta channel](https://flutter.dev/docs/get-started/web)

I am getting this error:

PS C:\Users\HP\flutter_code\webproj> flutter pub get
Because webproj depends on flutter_web from git which depends on flutter_web_ui any, flutter_web_ui from hosted is required.
So, because webproj depends on flutter_web_ui from git, version solving failed.
Running "flutter pub get" in webproj...
pub get failed (1; So, because webproj depends on flutter_web_ui from git, version solving failed.)
