### ISSUE TITLE
flutter-web-sdk is not precached

### ISSUE THREAD

**Issue by tezine** [flutter/flutter#50008]
Hi,
I'm trying to use flutter (beta channel), but I'm behind a Corporate Proxy outside China. 
Whenever I execute the command `flutter build web`, I get the following errors:
```
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/flutter-web-sdk-windows-x64.zip
```
flutter --version prints the following: 
```
Flutter 1.13.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 659dc8129d (5 weeks ago) • 2019-12-30 09:24:47 -0800
Engine • revision bdc9708d23
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
```
Flutter doctor prints ok for everything. 
There are several similar issues posted here, but I found no solutions yet, although they were closed for some reason. 18262, 22502. 
Any ideas on how to contour this issue? It makes it impossible to use it inside the company.

**Comment by VladyslavBondarenko** [comment]
Hi @tezine 
Does it help if you [set proxy server environment variable](https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall)

**Comment by tezine** [comment]
Hi @VladyslavBondarenko! I already tried to set the proxy variable, but it didn't help with this issue. :-(

**Comment by iapicca** [comment]
Hi @tezine 
does this [solution](https://github.com/flutter/flutter/issues/48030#issuecomment-570683856) work for you?
( same solution [here](https://github.com/flutter/flutter/issues/22502#issuecomment-425887170)
thank you

**Comment by tezine** [comment]
Hello @iapicca , unfortunately these solutions don't work. Even if I download the entire sdk from beta channel, when I set `flutter config --enable-web` and execute `flutter build web`, it will attempt to download the web sdk, which fails to download with the message above.

**Comment by gattytto** [comment]
building a docker image that comes with web enabled and device for web sdk precached is not possible because of this?

**Comment by darshankawar** [comment]
@tezine 
Considering the age of the issue, is there a way for you to confirm if this behavior still occurs using latest stable version of framework ?
