### ISSUE TITLE
Tearing of textures

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50011]
This is tracking https://b.corp.google.com/issues/147510322 specifically (see also https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=44141).

----

Similar issue with separate cause:
https://b.corp.google.com/issues/148504495.

cc @iskakaushik @chinmaygarde

**Comment by chinmaygarde** [comment]
@cbracken As [explained here](https://github.com/flutter/flutter/issues/49889#issuecomment-581573765), the two issues are unrelated (till I can prove otherwise). I suggest we find someone else to investigate this in parallel so as not to stall progress here.

**Comment by cbracken** [comment]
@chinmaygarde Thanks for updating! Will un-de-dupe.

**Comment by Hixie** [comment]
Sounds like @iskakaushik is working on this. Thanks!

**Comment by iskakaushik** [comment]
fixed by https://github.com/flutter/engine/pull/16548
