### ISSUE TITLE
flutter_gallery__back_button_memory_diff-median regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50015]
First recent jump at https://github.com/flutter/flutter/pull/49406. Previous jump at https://github.com/flutter/flutter/pull/49847 looks a little more likely to me.

**Comment by kf6gpe** [comment]
Spoke to @jason-simmons who is investigating, and agrees that this is likely correct behavior and needs to be rebaselined if his investigations don't turn anything up. Dropping the TODAY label.

**Comment by jason-simmons** [comment]
Took a look at recent changes but didn't find anything with a noticeable effect on memory usage.  This benchmark is noisy and is primarily intended to detect resources that are being leaked each time the app is suspended and resumed.  That doesn't appear to be happening - if I increase the number of suspend/resume cycles the process' memory consumption does not continue to increase.

I'll go ahead and rebaseline the benchmark.
