### ISSUE TITLE
flutter_test_performance_implementation_change_elapsed_time_ms & flutter_test_performance_interface_change_elapsed_time_ms regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50016]
Looks like it started in https://github.com/flutter/flutter/pull/49835 or https://github.com/flutter/flutter/pull/49873.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/49893

**Comment by Hixie** [comment]
Closing as dupe of #49893.
