### ISSUE TITLE
analyzer_benchmark_flutter_repo_batch_maximum & analyzer_benchmark_flutter_repo_watch_maximum regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50013]
Looks like it started occurring at https://github.com/flutter/flutter/pull/49873, or perhaps https://github.com/flutter/flutter/pull/49835 (it dropped again after this roll).

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/49893

**Comment by kf6gpe** [comment]
I'm betting that this is also due to the same culprit in https://github.com/flutter/flutter/issues/49893.

**Comment by kf6gpe** [comment]
Dropping TODAY label as we believe we have a fix in flight and don't want to block the roll.

**Comment by liyuqian** [comment]
Shall we close this as https://github.com/flutter/flutter/issues/49893 is now closed?

**Comment by kf6gpe** [comment]
Sounds good to me. Closing.
