### ISSUE TITLE
Possible analysis bug: dart:ui alias not recognized (or bad project structure?)

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#50018]
Original bug: https://github.com/dart-lang/pub-dev/issues/3266 (reported by @JasMich on [`package:katex_flutter`](https://pub.dev/packages/katex_flutter)). 

Flutter version: `1.12.13+hotfix.5` on pub.dev, `1.14.7-pre.83` used by the developer.

The [source code](https://gitlab.com/testapp-system/katex_flutter/blob/master/lib/katex_flutter_web.dart) is using `import 'dart:ui' as ui;` on line 4.

Analyzing it with `flutter analyze` or `[path-to-flutter-sdk]/bin/cache/dart-sdk/bin/dartanalyzer lib/` yields the following error: `The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix. • lib/katex_flutter_web.dart:21:8 • undefined_prefixed_name`

The [source code on line 21](https://gitlab.com/testapp-system/katex_flutter/blob/master/lib/katex_flutter_web.dart#L21) looks good to me. Is this a bug in the analyzer, or is this a package layout issue, where the web plugin needs to be placed elsewhere?

**Comment by JasMich** [comment]
I agree. Using the `ui.platformViewRegistry` method never caused any issues in my applications.

**Comment by TahaTesser** [comment]
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/41563
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser This is a different issue - this one is about the analyzer when running `flutter analyze`.
