### ISSUE TITLE
basic_material_app_ios__compile_debug_full_compile_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50014]
Big spike at https://github.com/flutter/flutter/pull/49835, which I don't believe, but I think it may need to be rebaselined; after that it dropped and it's been hovering around the baseline for a while now.

**Comment by zanderso** [comment]
Agree that this needs to be rebaselined. We can track improving ios build times e.g. here: https://github.com/flutter/flutter/issues/49866

**Comment by Hixie** [comment]
Looks like it just got slowly worse over time. We should see if we can find some wins to reduce it, but in the meantime we'll attribute this to just "we're adding code, code takes time".
