### ISSUE TITLE
hot_mode_dev_cycle_macos_target__benchmark_hotReloadMillisecondsToFrameAfterChange regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50019]
It's frequently spiky, but seems to tick up consistently after https://github.com/flutter/flutter/pull/49873.

**Comment by Hixie** [comment]
A bunch of hot reload numbers got worse recently:
![Screen Shot 2020-02-03 at 13 47 57](https://user-images.githubusercontent.com/551196/73693851-d5d31380-468b-11ea-901e-9696107e6947.png)

**Comment by Hixie** [comment]
Closing as being covered by https://github.com/flutter/flutter/issues/49892.
