### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotRestartMillisecondsToFrame regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50021]
This one's been up and down for a while, but consistently after https://github.com/flutter/flutter/pull/49004, which can't be the actual culprit. https://github.com/flutter/flutter/pull/49654 looks more likely.

![benchmark](https://user-images.githubusercontent.com/1435716/73674475-73ffb300-4665-11ea-994b-258219ab1e01.png)

cc @christopherfujino

**Comment by kf6gpe** [comment]
![benchmark-2](https://user-images.githubusercontent.com/1435716/73674598-b88b4e80-4665-11ea-9518-c25aa43aa035.png)

**Comment by zanderso** [comment]
We probably have to keep https://github.com/flutter/flutter/pull/49654, so if it is the cause, I think we have to rebaseline.

**Comment by christopherfujino** [comment]
Could this be infra-related? The second image @kf6gpe posted looks pretty noisy.

**Comment by Hixie** [comment]
It also regressed on non-catalina: https://github.com/flutter/flutter/issues/50019

**Comment by Hixie** [comment]
Hot reload has regressed across the board but this is hot restart which only regressed on Catalina, it seems.

**Comment by zanderso** [comment]
The benchmark has dropped back down into the green. @Hixie what is the procedure here when the benchmark looks bimodal?

**Comment by kf6gpe** [comment]
Dropping TODAY issue at present as this is green and appears bimodal.

**Comment by liyuqian** [comment]
It has regressed again since https://github.com/flutter/flutter/commit/1d4667bb3835079276246e8695ea12b657b4493f. This does not seem to be the typical bimodal case where the benchmark is like independent coin tosses. Here, the slow benchmark will stick for a period of time, and then disappear. Hence I'd suspect that this is related to some latent condition in our device lab. CC @godofredoc

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/45112
