### ISSUE TITLE
Shrine: text for shop name (and avatar) is clipped on iPod Touch

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5002]
On my iPod Touch, the shop name (and avatar) is clipped.

See below in screenshot, at the bottom of the cards.

![img_0005](https://cloud.githubusercontent.com/assets/5479/17068437/cf11d4ee-5005-11e6-90ea-eebe2efda1cc.PNG)

**Comment by eseidelGoogle** [comment]
@HansMuller is Mr. Shrine.
