### ISSUE TITLE
[google_maps_flutter] How to correctly store the API key and use both on iOS and Android

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter#50026]
I am using `google_maps_flutter` and before pushing my project to the repo, also if it is private, I was asking myself how to store the API key.
My app haven't any type of authentication, it will become a free app and initially I won't profile users. 
The problem is that I need to set the API key for both Android and iOS platforms specific files. 
Can it be an idea to pass it as GoogleMap constructor? 
Something like:

```dart
return GoogleMap(
        apiKey: 'myApiKey'
        ......);
```
In this case we can simply store in a file/asset. This strategy can be overcome by hackers that make app reverse engineering but it seems better than simply push the key visible in the repo.

**Comment by humazed** [comment]
The key should be restricted from the developer console to your app only so if someone got it he can't use it.

**Comment by enricobenedos** [comment]
hi @humazed, thank you for your precisation. I think you are talking about this:
![image](https://user-images.githubusercontent.com/12233746/73725790-711cc500-472e-11ea-9376-3e1080793188.png)
Surely I will provide to set the restrictions for my app!
Anyway I think that my suggestion should be evaluated because if someone clone the app id, he can use my key at least during develop. 
Mine is only a best practice proposal, also the key used for signing APKs is useless without the play console credentials to publish the bundle in the store.
But google does not recommend to push it to your repo.

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
