### ISSUE TITLE
Named routes disappear after refreshing

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#50027]
Refreshing the page replaces the initial route in the URL bar.

### Steps to reproduce:

1. Run the example app in Chrome
2. click the button
3. Refresh the browser
4. Observe that the /page2 in the URL bar goes away.

<details><summary>Example app</summary>
<p>

```python
import 'package:flutter/material.dart';

void main() {
  runApp(DeepLinkingApp());
}

class DeepLinkingApp extends StatefulWidget {
  @override
  _DeepLinkingAppState createState() => _DeepLinkingAppState();
}

class _DeepLinkingAppState extends State<DeepLinkingApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => Page1(),
        '/page2': (context) => Page2(),
      },
      initialRoute: '/',
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.of(context).pushNamed('/page2');
          },
          child: Text('Go to Page 2'),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('Page 2'),
      ),
    );
  }
}

```

</p>
</details>

![routing](https://user-images.githubusercontent.com/1145719/74054313-a4f82480-4992-11ea-8718-c402f4f5e3f6.gif)

**Comment by R01NDev** [comment]
Having the same issue, we need an urgent fix please. Can't directly link to routes right now since this issue will occur.

**Comment by yjbanov** [comment]
You don't have a "settings" route in your routes list, so we default to the root route.

**Comment by johnpryan** [comment]
sorry that should have said "page2" - I've updated the GIF to explain

**Comment by yjbanov** [comment]
Ok, that does look like a bug to me.

/cc @mdebbar

**Comment by mdebbar** [comment]
I looked into this. It turns out it started happening after a [Navigator refactor](https://github.com/flutter/flutter/pull/44930) on the framework side. The change caused the platform messages to be sent in the reverse order.

/cc @chunhtai

**Comment by windrunner414** [comment]
I met once named route disappeared after pushNamed and all the push after it will not change the url.But I can't reproduce it, only once.
