### ISSUE TITLE
Enable FML File unittests on Fuchsia.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50031]

**Comment by chinmaygarde** [comment]
cc @gw280. Adding an issue for a TODO(<username>) you added in the [FML build rules](https://github.com/flutter/engine/blob/f9c45276a057116eaeb54d07218a34b00253eb4b/fml/BUILD.gn#L245).

**Comment by gw280** [comment]
Closing as a dupe of https://github.com/flutter/flutter/issues/57709
