### ISSUE TITLE
When adding to a previous line in a multi-line text field, the cursor doesn't advance and empty spaces are not showing

### ISSUE THREAD

**Issue by hkndzdr** [flutter/flutter#50033]
This bug was fixed with v1.12.13 + hotfix.5.  But the bug started again with v1.12.13 + hotfix.7.

![textfieldbug](https://user-images.githubusercontent.com/34459880/73688234-aac4e000-46dc-11ea-86dd-db53dab60398.gif)

**Comment by iapicca** [comment]
Hi @hkndzdr 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45841) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by jason-simmons** [comment]
This bug was fixed by https://github.com/flutter/flutter/commit/6b66d794360bb7d3ff7bf2f6dfbcbd58516c3f20.  But it was reintroduced when that change was reverted (https://github.com/flutter/flutter/commit/d345a3b303ce041846ff895eb49a104bef133c4b).

@GaryQian any updates on this?

**Comment by hkndzdr** [comment]
> This bug was fixed by [6b66d79](https://github.com/flutter/flutter/commit/6b66d794360bb7d3ff7bf2f6dfbcbd58516c3f20). But it was reintroduced when that change was reverted ([d345a3b](https://github.com/flutter/flutter/commit/d345a3b303ce041846ff895eb49a104bef133c4b)).
> 
> @GaryQian any updates on this?

The bug still continues with v1.12.13+hotfix.8

**Comment by goderbauer** [comment]
@GaryQian did you ever reland that reverted change? Do you have plans to do so?

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/40095

**Comment by justinmc** [comment]
Also related to https://github.com/flutter/flutter/issues/30975.

**Comment by justinmc** [comment]
Is this working now that https://github.com/flutter/flutter/issues/40095 is closed?

**Comment by VladyslavBondarenko** [comment]
Yes, just tried with Android 9 device, it still occurs with stable `1.17.5`, but doesn't with current beta `1.19.0-4.3.pre` and master `1.20.0-8.0.pre.75`. Closing as fixed
