### ISSUE TITLE
[web]: Can't copy Text | blurry showDialog()

### ISSUE THREAD

**Issue by iLePix** [flutter/flutter#50048]
Texts on websites programmed in flutter and dart arent copyable (even if text is inside an SelectableText Widget)

showDialog() is blurred if inside an ClipRRect

Thanks for your great Framework | Hope this issues will be fixed soon

**Comment by mdebbar** [comment]
The first issue (unable to copy SelectableText content) is already filed here: https://github.com/flutter/flutter/issues/47234.

**Comment by yjbanov** [comment]
The blurry text issue has been fixed as of https://github.com/flutter/engine/pull/15649. Can you please try the master channel, and if the issue persists, feel free to reopen.
