### ISSUE TITLE
[tool_crash] type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#50042]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ... if I run the app without a SafeArea, I have a HttpException
2. ... if  I run the app with a SafeArea, other problems occur: cf https://github.com/flutter/flutter/issues/48966 
3. ... All those problems did not exist when the web was in the dev-channel, problems started around the 16 January

## Logs
_TypeError: type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'
```
#0      _invokeErrorHandler (dart:async/async_error.dart:18:23)
#1      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:288:9)
#2      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _CustomZone.runBinaryGuarded (dart:async/zone.dart:941:7)
#6      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#7      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
#8      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
#9      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:139:11)
#10     _addErrorWithReplacement (dart:async/stream_pipe.dart:190:8)
#11     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:293:11)
#12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
#13     _rootRunBinary (dart:async/zone.dart:1146:38)
#14     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#15     _CustomZone.runBinaryGuarded (dart:async/zone.dart:941:7)
#16     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#17     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
#18     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
#19     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:777:19)
```
```
[✓] Flutter (Channel dev, v1.14.6, on Microsoft Windows [version 10.0.18363.592], locale fr-FR)
    • Flutter version 1.14.6 at C:\Users\bened\Desktop\devmob\devfluttersdk\fsdk\flutter
    • Framework revision fabeb2a16f (6 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\bened\Desktop\devmob\devastudiosdk\assdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\bened\Desktop\devmob\devastudiosdk\assdk
    • Java binary at: C:\Users\bened\Desktop\devmob\devastudio\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Users\bened\Desktop\devmob\devastudio\as
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by iapicca** [comment]
Hi @benedicte69 
relative to the case `1`
can you please provide your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
For the case `2` please follow up on the linked issue.
Thank you

**Comment by benedicte69** [comment]
CASE 01 without SafeArea

today the behaviour has been different, the result looked similar than in CASE 02 with SafeArea
So I invaleded cach, clean and so on ...

INFORMATION CASE 01 without SafeArea
**first result** of flutter run -d chrome has been:
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for
example due to a firewall.

**second result** of flutter run -d chrome:
then I rerun flutter run -d chrome and the result was similar than  CASE 02

CASE 01 without SafeArea  **flutter run -d chrome**: 
[CASE01 errors.txt](https://github.com/flutter/flutter/files/4154055/CASE01.errors.txt)

CASE 01 without SafeArea  **flutter run --verbose**: 
[CASE01 flutter verbose.txt](https://github.com/flutter/flutter/files/4153953/CASE01.flutter.verbose.txt)

**Comment by iapicca** [comment]
Hi @benedicte69 
thanks for the logs
can you provide a reproducible minimal code sample?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by kardotinambunan12** [comment]
hello i have a problem in this section
when i post data on flutter ._"TypeError: type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'" .  how to solve the problem . thanks

**Comment by kardotinambunan12** [comment]
and my flutter run --verbose

C:\Users\TOG\Documents\android>flutter run --verbose
[  +45 ms] executing: [C:\Users\TOG\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +77 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\Users\TOG\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +52 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +9 ms] executing: [C:\Users\TOG\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\TOG\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\Users\TOG\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +158 ms] executing: C:\Users\TOG\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +47 ms] Exit code 0 from: C:\Users\TOG\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           Z5PBU4AMVGUC5DBA       device product:1601 model:vivo_1601 device:1601 transport_id:6
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:3
[  +22 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +9 ms] C:\Users\TOG\AppData\Local\Android\sdk\platform-tools\adb.exe -s Z5PBU4AMVGUC5DBA shell getprop
[ +138 ms] ro.hardware = mt6755
[        ] ro.build.characteristics = overseas
[   +2 ms] C:\Users\TOG\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +64 ms] ro.hardware = ranchu
[   +2 ms] vivo 1601                 • Z5PBU4AMVGUC5DBA • android-arm64 • Android 6.0 (API 23)
[  +13 ms] Android SDK built for x86 • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)
[  +12 ms] "flutter run" took 518ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Users/TOG/Downloads/flutter_windows_v1.12.13+hotfix.8-stable/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by acheronian** [comment]
+1

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
