### ISSUE TITLE
Gallery, Buttons: Scrollable Dropdown has lots of white padding at top

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5004]
On my iPod Touch. I opened Gallery, then tapped Buttons, then tapped Dropdown, and then tapped into Scrollable dropdown.

See below, notice how there is a lot of white padding at the top of the dropdown display.

Also, looks like we're not showing the full intended list?

![img_0008](https://cloud.githubusercontent.com/assets/5479/17068695/538936e4-5007-11e6-8f12-1aab31d822b6.PNG)

**Comment by sethladd** [comment]
Ah, this is scrollable. Once I scroll the list contents, the issue corrects itself. The above screenshot is the initial display.

**Comment by mpcomplete** [comment]
I can't repro this anymore. Looks like something fixed it.
