### ISSUE TITLE
androidx-migration

### ISSUE THREAD

**Issue by PedroPinto23** [flutter/flutter#50063]
I’m having issues migrating to AndroidX

**Comment by julianbraasch** [comment]
What exactly is the problem you're facing? Did you follow the [migration guide](https://flutter.dev/docs/development/androidx-migration)?

**Comment by PedroPinto23** [comment]
Yes, I did the Refactor of the android file and migrate to androidx but I'm still stuck in the same issue
![image](https://user-images.githubusercontent.com/44075417/73797098-d7850000-478d-11ea-87b9-e7c9b0b6454e.png)

**Comment by PedroPinto23** [comment]
Seems like the trouble is with the firestore plugin but, I tried lot of versions and still nothing

**Comment by VladyslavBondarenko** [comment]
Hi @PedroPinto23 
Are you using the last version of cloud_firestore plugin?
Does https://github.com/FirebaseExtended/flutterfire/issues/1401#issuecomment-554699228 help?

**Comment by PedroPinto23** [comment]
Thanks! It Worked adding the multDexEnabled true and '  implementation "androidx.multidex:multidex:2.0.0" ' in the dependencies
