### ISSUE TITLE
remove interpolateColorsInPremul flag in dart:ui after migration

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#50070]
A new flag is going to be added to support https://github.com/flutter/flutter/issues/48534 and https://github.com/flutter/flutter/issues/48674 as a soft break.  Once the migration is complete for internal clients, we should remove the flag.  Filing this bug for cleanup.  

Steps:

- [ ] Add the flag as deprecated, defaulted to the current implementation (https://github.com/flutter/engine/pull/16353)
- [ ] Roll this to internal customers.
- [ ] Enable this flag as true internally, fix all golden test failures.
- [ ] Default the flag to true externally (the real breaking change).
- [ ] Roll flag defaulted to true to internal customers.
- [ ] Remove setters internally.
- [ ] Remove flag externally.

**Comment by dnfield** [comment]
I need to find a reviewer for my patch. In the mean time, moving this to goals.

**Comment by jonahwilliams** [comment]
This patch didn't land (though the linked issues are real)
