### ISSUE TITLE
iOS Device - F5 Debugging stuck on 'Installing and Launching'

### ISSUE THREAD

**Issue by danielgchap** [flutter/flutter#50076]
Hey all,
I'm using Visual Studio code. 
This app used to be fine with me hitting F5 for debug on my physical device (iPhone X, 13.3). 

Now out of nowhere, it installs, but just sits on the splash screen stuck on 'Installing and Launching'. It works fine through XCode.

I'm trying to utilize the DevTools through a debug session in Visual Studio because I'm seeing massive Memory issues. But this is extremely frustrating and getting me rather disappointed in Flutter after a year of building this app. 

Yes I have tried restarting, turning off wifi, deleting app, restart phone. Everything. 

Here is my flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/danielc/Desktop/Learn/flutter
    • Framework revision 9f5ff2306b (8 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danielc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone (2)        • 00008020-000A116C2ED2002E            • ios • iOS 13.3
    • iPhone 11 Pro Max • 83782B19-204A-400E-BB2F-58752163B32B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

I'd really appreciate any input. 

Thanks

**Comment by iapicca** [comment]
Hi @danielgchap 
I see you have this issue open
https://github.com/flutter/flutter/issues/50077
please follow up there
thank you
