### ISSUE TITLE
Gallery, Date Picker: missing frames inside CPU

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5008]
On my iPod Touch:
- open gallery
- tap into Date picker
- tap "select date"

Notice how there's a spike in the CPU whenever we display the date picker. All the CPU spikes in the below screenshot are from the display of the picker.

![img_0010](https://cloud.githubusercontent.com/assets/5479/17069159/f78569fa-5009-11e6-82a2-9dad0c9f4143.PNG)

**Comment by Hixie** [comment]
This bug is 4 years old and the code has changed a lot since then. It may well still be missing frames but we should track this more holistically at this point.
