### ISSUE TITLE
Flutter UI Test - supporting of tearDown to do driver.close() in the end of each test

### ISSUE THREAD

**Issue by yihsuan-chen-s** [flutter/flutter#50099]
Hi
  We're trying to adopt `driver.close()` at the end of each tests, but it seems that there isn't any `tearDown` supported in Flutter integration testing.

Here's what we trying to do
1. Run Test 1
    - setUp: Launch App
    - test: Testing
    - tearDown: Terminate App
1. Run Test 2
    - setUp: Launch App
    - test: Testing
    - tearDown: Terminate App

``` javascript
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Login / Logout Test', () {
    FlutterDriver driver;

    // setUp of each test
    setUp(() async {
      driver = await FlutterDriver.connect();
    });

    test('TestLogin', () async {
        // testing
    });

    test('TestLogout', () async {
        // testing
    });

    // tearDown of each test
    tearDown(() async {
      await driver.close();
    });
  });
}
```
These code is not working now.
Is there any way to do these things in Flutter integration testing?

FYR,
  likes the concept of [writing-tests-annotations](https://junit.org/junit5/docs/current/user-guide/#writing-tests-annotations) (`@BeforeEach`, `@AfterEach`, `@BeforeAll`, `@AfterAll`) in Junit5.

Thanks

**Comment by hainguyen168** [comment]
flutter driver connect and close method just manages connection between app and test code, it cannot close or open the app. There's a guid to manage this thing [here](https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54)
Hope this help

**Comment by goderbauer** [comment]
I am pretty sure that tearDown works as expected and we haven't heard any reports that say otherwise. I am going to close this.
