### ISSUE TITLE
compile time showing error

### ISSUE THREAD

**Issue by jatin-code** [flutter/flutter#50093]
Compiler message:
/E:/flutter/packages/flutter/lib/src/material/colors.dart:198:3: Error: Expected '{' before this.
  static const Color transparent = Color(0x00000000);
  ^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        18.5s
Gradle task assembleDebug failed with exit code 1

**Comment by VladyslavBondarenko** [comment]
Hi @jatin-code 
You can try to reinstall Flutter
https://github.com/flutter/flutter/issues/23908#issuecomment-435599077
Does it help?

**Comment by jatin-code** [comment]
Thanxx @VladyslavBondarenko.
