### ISSUE TITLE
GL_OUT_OF_MEMORY on Nexus 5 in the camera example

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#501]
Running the camera example (https://github.com/domokit/mojo/tree/master/examples/dart/camera_video) on Nexus 5 causes
```
[ERROR:texture_manager.cc(1708)] [GroupMarkerNotSet(crbug.com/242999)!:5404C1A1]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: 
[ERROR:gles2_cmd_decoder.cc(6546)] [GroupMarkerNotSet(crbug.com/242999)!:5404C1A1]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

This does not happen on Nexus 10 or OnePlus.
I have manually verified that the CanvasImage object's destructor is being called.

@jason-simmons @abarth @gauthamt

**Comment by abarth** [comment]
This demo is pretty out of date.  I'm not sure there's anything actionable here.
