### ISSUE TITLE
ScrollController doesn't work when ListView is not full screen

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#50107]
-------------------code----------------------------------------------------------------

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  final List<String> entries = <String>['A', 'B', 'C'];
  final List<int> colorCodes = <int>[600, 500, 100];
  ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(() {
      if (_scrollController.position.pixels ==
          _scrollController.position.maxScrollExtent) {
        print("drop down");
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
            padding: const EdgeInsets.all(0),
            physics: AlwaysScrollableScrollPhysics(),
            controller: _scrollController,
            itemCount: entries.length,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                height: 50,
                color: Colors.amber[colorCodes[index]],
                child: Center(child: Text('Entry ${entries[index]}')),
              );
            }),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _scrollController.dispose();
  }
}
```

**Comment by Tumbler0809** [comment]
The log is not printed

**Comment by Tumbler0809** [comment]
C:\Users\Orion\Desktop\SC\flutter-test-master\test_flutter>flutter  doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.0)
[√] Connected device (1 available)

• No issues found!

**Comment by Tumbler0809** [comment]
C:\Users\Orion\AndroidStudioProjects\mobile_client_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (8 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Orion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Orion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Orion\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • MI 8 • fb21bfb6 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
Hi @Tumbler0809 
By 'ScrollController doesn't work' do you mean that you expected to have listener called even on the scroll attempt? not only on actual scrolling?

**Comment by Tumbler0809** [comment]
When my finger swipes up on the list view, I also need to trigger a scroll listener

**Comment by Tumbler0809** [comment]
Yes, what you described is correct

**Comment by Tumbler0809** [comment]
A page displays 3 pieces of data at a time, and the 3 pieces of data cannot fill the screen. The user slides up, hoping to load more, so the scroll monitoring needs to be triggered.

**Comment by goderbauer** [comment]
The ScrollController only notifies its listeners when the scroll offset changes. In your example it looks like the ListView can't actually scroll because it doesn't have enough content to be scrollable. Therefore, the ScrollController doesn't call its listeners when you attempt to scroll it. So, this is working as intended.

You could try using `BouncingScrollPhysics` which will make the ListView bounce when you scroll it.

**Comment by kaciula** [comment]
@Tumbler0809 Hi. Did you manage to find a way to detect scrolling even when the list does not fill the screen? This is important for pagination.

**Comment by pumuckelo** [comment]
yes, I also need this for pagination

**Comment by sahmirzali** [comment]
@Tumbler0809 did you find any solution?
