### ISSUE TITLE
Saffold does not resizes when app switch to background if keyboard was open

### ISSUE THREAD

**Issue by daveoncode** [flutter/flutter#50109]
As I'm asking on Stackoverflow (https://stackoverflow.com/questions/60055903/flutter-issue-when-app-switch-to-background-if-keyboard-was-open):

When the app is moved to the background (onPause event in Android), if the keyboard was opened the view did not redraw itself as it normally does when the user dismiss the keyboard.

**Comment by salihgueler** [comment]
Does Scaffold resize, when you enter the app again?

**Comment by VladyslavBondarenko** [comment]
But this behavior is common for any android apps, not only flutter-based

**Comment by salihgueler** [comment]
I didn't say the opposite 😄I was just trying to understand if it doesn't repaint at all when it restarts as well.

**Comment by daveoncode** [comment]
well... shame on me, I've just tried with other apps like whatsapp and telegram and, yep... it's the default behavior (even tough I don't like it) ... anyways. it's not a Flutter issue... I'm closing this discussion, forgive me :)
