### ISSUE TITLE
Unable to disable allowImplicitScrolling for existing scroll physics

### ISSUE THREAD

**Issue by armandsLa** [flutter/flutter#50106]
I was unable to set `allowImplicitScrolling` in `AlwaysScrollableScrollPhysics` subclass to false. Text fields were still automatically scrolled into the view when focus was set. However, when I copied entire `AlwaysScrollableScrollPhysics` implementation and changed `allowImplicitScrolling` to true it worked. 

Not working:
```
class CustomScrollPhysics extends AlwaysScrollableScrollPhysics {
	
  @override
  bool get allowImplicitScrolling => false;

}
```

Working:
```
class CustomScrollPhysics extends ScrollPhysics {

  /// Creates scroll physics that always lets the user scroll.
  const CustomiOSScrollPhysics({ ScrollPhysics parent }) : super(parent: parent);

  @override
  CustomiOSScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomiOSScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  bool shouldAcceptUserOffset(ScrollMetrics position) => true;

  @override
  bool get allowImplicitScrolling => false;

}
```

**Comment by iapicca** [comment]
Hi @armandsLa 
can you please provide your `flutter doctor -v`
Thank you

**Comment by goderbauer** [comment]
Can you provide some runnable code that shows that this doesn't work?

**Comment by armandsLa** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G3020, locale en-GB)
    • Flutter version 1.12.13+hotfix.7 at /Users/armands/flutter
    • Framework revision 9f5ff2306b (10 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/armands/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode 11.2.1 GM.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • iPhone 11 Pro • 055B3060-3F61-4CF0-9E49-6EA428CFF626     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @armandsLa 
as for @goderbauer 's request, 
could you please provide a reproducible minimal code sample?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by miyoyo** [comment]
@iapicca Here's a small reproduction example:
[Interactive example on dartpad, click on the middle to unfocus, click on the focus FAB to focus.](https://dartpad.dev/2ccfa05f325883ab560a01f509dbb259)

**Comment by miyoyo** [comment]
Apparently, implementing ScrollPhysics and ApplyTo directly are the solution to prevent this behavior
```dart
class BrokenImplicitScrollPhysics extends ScrollPhysics {
  /// Creates scroll physics that does not let the user scroll.
  const BrokenImplicitScrollPhysics({ ScrollPhysics parent }) : super(parent: parent);

  @override
  BrokenImplicitScrollPhysics applyTo(ScrollPhysics ancestor) {
    return BrokenImplicitScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  bool get allowImplicitScrolling => false;
}
```
