### ISSUE TITLE
How to run Flutter Official Samples in Visual Studio Code

### ISSUE THREAD

**Issue by markwen** [flutter/flutter#50100]
Hi,

I am new to Flutter, and want to run the Flutter Official Samples (https://flutter.github.io/samples/#/) in Visual Studio Code, but didn't prevail. For example, I managed to copy paste the banner codes into VS code, but it shows error in the second import statement:

import 'package:flutter/material.dart'; 
import 'package:gallery/l10n/gallery_localizations.dart';

I even tried to copy paste the whole gallery directory from the github samples to the .pub-cache, but still cannot compile the codes properly.

Does anyone know how to solve my problem?

Really appreciate.

**Comment by VladyslavBondarenko** [comment]
Hi @markwen 
I would advise you to use samples from https://github.com/flutter/samples/blob/master/INDEX.md

**Comment by markwen** [comment]
> Hi @markwen
> I would advise you to use samples from https://github.com/flutter/samples/blob/master/INDEX.md

Hi VladyslavBondarenko,

I knew this link, and had already downloaded all the files before. After opening some of the folders in VS code, I was able to run it somehow, but the compiler complains that there are lots of deprecated APIs used in the codes.

Thanks very much for the tip.

Cheers,
mark
