### ISSUE TITLE
PaginatedDataTable footer can't handle narrow tables

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5011]
On my iPod Touch.
- Open gallery
- Tap into Data Tables
- Scroll down to display the bottom of the table

Notice in the screenshot below, we don't have left padding for "Rows per page" at the bottom.

![img_0012](https://cloud.githubusercontent.com/assets/5479/17069672/c0f9d3f0-500c-11e6-9744-1615e5df4810.PNG)

Notice in the screenshot below there is too much top padding once we've opened the dropdown list:

![img_0013](https://cloud.githubusercontent.com/assets/5479/17069679/c7fab796-500c-11e6-8984-d2e1a08b862f.PNG)

**Comment by sethladd** [comment]
cc  @Hixie not sure if this is a framework thing?

**Comment by Hixie** [comment]
Yeah this is a framework thing.

The first one is a bug with the build function of the PageableDataList.

The bug with the second one is that we don't show a scroll bar when it comes up (there are items, they're just below the "10").

**Comment by sethladd** [comment]
Thanks for the analysis.

**Comment by eseidelGoogle** [comment]
Data tables were built for a specific customer, who does not need them on an urgent timeline.  If this is blocking the gallery launch, we could hide these for the time being?

**Comment by sethladd** [comment]
All things being equal, this is not a critical feature for the Gallery 1.0. It's a very nice to have.
