### ISSUE TITLE
Inkwell widget's onHover doesn't respond unless the onTap property is set

### ISSUE THREAD

**Issue by Abhilash-Chandran** [flutter/flutter#50116]
The `Inkwell` widget doesn't respond for `onHover` events unless the `onTap` property is set. A minimal reproducible  example is as shown below. This issue is showing up in dartpad as well.

Here is a live version of the [dartpad](https://dartpad.dartlang.org/cd263849836a615820f7a627bd5e249c)

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {  
  @override
  Widget build(BuildContext context) {
    return GridView.count(
      crossAxisCount: 3,      
      children: <Widget>[ImageHover(),ImageHover(),ImageHover(),ImageHover(),ImageHover(),ImageHover(),ImageHover(),],
    );
  }
}

class ImageHover extends StatefulWidget {
  @override
  _ImageHoverState createState() => _ImageHoverState();
}

class _ImageHoverState extends State<ImageHover> {
  double elevation = 4.0;
  double scale = 1.0;
  Offset translate = Offset(0,0);
  @override
  Widget build(context) {
    return InkWell(      
      onTap: (){}, // Commenting this makes onHover to not work.
      onHover: (value){
        print(value);
        if(value){
          setState((){
            elevation = 20.0;     
            scale = 2.0;
            translate = Offset(20,20);
          });
        }else{
          setState((){
            elevation = 4.0; 
            scale = 1.0;
            translate = Offset(0,0);
          });
        }
      },
      child: Transform.translate(
        offset: translate ,        
        child: Transform.scale(
          scale: scale,
          child: Material(        
            elevation: elevation,        
            child: Image.network(           
                'https://i.ytimg.com/vi/acm9dCI5_dc/maxresdefault.jpg',              
            ),
          ),
        ),
      ),
    );
  }
}
```

***Flutter Doctor Summary***

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.14.7-pre.83, on Microsoft Windows [Version 10.0.17134.1246], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (2 available)

• No issues found!

**Comment by dkwingsmt** [comment]
Thanks for the issue! 

Just to confirm with @gspencergoog, this behavior _is_ unintended, right? (to the contrary of https://github.com/flutter/flutter/pull/49041#event-2958030929)

**Comment by gspencergoog** [comment]
No, this behavior is actually as intended.  When `onTap` is not defined, the widget is disabled, and disabled widgets aren't supposed to respond to hover. If you wish to enable the widget, but do nothing when tapped, then do what you did in the example above: define an empty callback for `onTap`.
