### ISSUE TITLE
Gallery, Dialogs: tapping "cancel" from "confirmation" displays a toast

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5012]
On my iPod Touch:

* open gallery
* tap Dialogs
* tap CONFIRMATION
* change the time
* tap CANCEL

Expected:

* The pop-up disappears
* Nothing else :)

Actual:

* The pop-up disappears
* A toast from the bottom appears and says "you selected 3:30"

Not sure that we should show a confirmation toast when the user chooses "cancel".

**Comment by sethladd** [comment]
@HansMuller is this default behavior or something we added? I couldn't find a mention of when the confirmation toast should appear, but maybe I missed it?

**Comment by HansMuller** [comment]
It's just the demo unconditionally doing that. Should be an easy fix.
