### ISSUE TITLE
DeviceInfoPlugin on iOS does not return userInterfaceIdiom

### ISSUE THREAD

**Issue by jwise** [flutter/flutter#50123]
## Use case

My application would like to know whether it should behave like a phone or a tablet.  iOS offers a direct clue to this, rather than having to use screen size or device detection heuristics: `[UIDevice userInterfaceIdiom]`.  `DeviceInfoPlugin` supports some other properties of `UIDevice`, but not this one.

## Proposal

`DeviceInfoPlugin`'s `IosDeviceInfo` should be extended with a `userInterfaceIdiom` enum that corresponds to the ObjC enum `UIUserInterfaceIdiom`.

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
