### ISSUE TITLE
Flutter engine -> framework autoroller doesn't account for Fuchsia build failures

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#50131]
Commit: https://chromium.googlesource.com/external/github.com/flutter/engine/+/f44f50f3c58785807936b12b8ed6bec42a135f84

Failure: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/2370

Successful autoroll: https://github.com/flutter/flutter/pull/50113

This shouldn't be successful because the `fuchsia.stamp` file isn't successfully uploaded for that commit.

cc: @dnfield , @rmistry

**Comment by rmistry** [comment]
I'm not sure what happened there. But I need to update that roller to use dnfield@'s merge bot, which should not run into issues like this. I'll do it later today.

**Comment by rmistry** [comment]
Ok, switched the roller to use the mergebot. The autoroller will no longer try to figure out if everything passed and do the merging.

**Comment by iskakaushik** [comment]
awesome, thanks @rmistry !
