### ISSUE TITLE
Gallery: Tapping inside of "Scrolling lists" triggers frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5013]
Open Gallery, turn on "performance overlay", tap List. Then, tap onto any of the items.

Expected:

* no new frames are pushed

Actual:

* new frames are posted, even though nothing visibly happens on the screen

Not sure this is a big deal or not, but do we want to create new frames when nothing visibly happens?

**Comment by HansMuller** [comment]
This does seem like a bug.

Tapping a Scrollable generates an implicit press-drag-release gesture. Even though the gesture will not cause the scrollOffset to change it does cause start and end ScrollNotifications to be dispatched. 

The OverscrollIndicator responds to those notifications however they don't seem to trigger a setState() (they don't cause the OverscrollIndicator to paint).

Scrollable does quite a bit of work when the velocity reported by the DragEnd event is < kPixelScrollTolerance.velocity. It probably should just short-circuit ... 

... Having added the short-circuit we do generate fewer frames but a few still remain.

Will sort this out next week.
