### ISSUE TITLE
GOMA setup on Windows on LUCI is flaky and causes tree closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50130]
Thread with goma-users in https://groups.google.com/a/google.com/g/goma-users/c/H0mhodybg-4

**Comment by iskakaushik** [comment]
We are seeing this happen again. Here are more links:
1. https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/5167
2. https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/5154
3. https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/5125

**Comment by cbracken** [comment]
And more:
1. https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/5215
2. https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/5216

**Comment by Hixie** [comment]
What action should we take to resolve this?

**Comment by chinmaygarde** [comment]
Unclear. This hasn't happened in the last 200 runs and the Goma version in the latest versions is newer than in the original reports. I am going to close this for now. We can re-open and re-investigate if this happens again I suppose 🤷
