### ISSUE TITLE
Material design component: mobile date input picker

### ISSUE THREAD

**Issue by opringle** [flutter/flutter#50133]
## Use case

When a user needs to input a date in the distance past or future (such as a birth date), the material design guidelines recommend using a mobile date input picker. The `showDatePicker()` method in flutter does not support this type of picker.

![image](https://user-images.githubusercontent.com/22196222/73784762-eb5b4280-474a-11ea-8dbe-7d422177e0ab.png)

I cannot find a flutter library implementing this.

## Proposal

Add a material widget implementing the mobile date input picker show in the material design guidelines: https://material.io/components/pickers/#mobile-pickers.

**Comment by HansMuller** [comment]
cc @darrenaustin

**Comment by Hixie** [comment]
@darrenaustin I assigned this to you since it's what you're working on.

**Comment by ilechcod** [comment]
Please what's the exact status of this? The old date picker widget is still showing on my current flutter version. How can I help?

**Comment by ilechcod** [comment]
Pls is this available yet? And on what flutter version?
