### ISSUE TITLE
Feature request: Expose native platform APIs

### ISSUE THREAD

**Issue by ansarizafar** [flutter/flutter#50169]
Flutter should consider exposing native platform APIs like Native script https://www.nativescript.org/native-api-access. This will allow developers to access native platform features without needing a plugin.

**Comment by iapicca** [comment]
Hi @ansarizafar 
isn't [platform-channels](https://flutter.dev/docs/development/platform-integration/platform-channels) sufficient for your needs? 
What would you like to have changed and how you suggest to achieve that?
thank you

**Comment by ansarizafar** [comment]
> isn't platform-channels sufficient for your needs?

No its not. Nativescript allow developers to access native platform APIs without requiring to write any code in java, Kotlin or Swift. https://www.nativescript.org/native-api-access

**Comment by iapicca** [comment]
HI again @ansarizafar 
could you please describe how is achievable
w/o platform channel or plugins?
Thank you

**Comment by Zazo032** [comment]
My guess is he wants the Flutter framework to have built-in methods to access some native APIs, but there's already a long list of (official) [plugins](https://github.com/flutter/plugins) that achieve this, so not really sure if there are some missing native APIs that would be interesting to have a specific plugin for.

**Comment by ansarizafar** [comment]
We need to dig into how Nativescript provides 0-day support for Android and iOS device APIs from javascript without requiring to write wrappers/plugins to expose native functionality. 

If Nativescript can do this then Flutter should also be able to provide access to native device apis from Dart without any plugin.

**Comment by iapicca** [comment]
Hi @ansarizafar 
I believe there's a bit of confusion around how flutter works.

Nativescript relies on controversial `bridge`
which has an undeniable negative impact on several elements
and makes other features easier to obtain,

Flutter runs on the metal and this grants several advantages
with the trade-off of writing native code linked to the `platform channel`
or using a plugin that does that for you.

Implying that Nativescript "does it better" it's a legitimate personal opinion,
but requiring Flutter to work the same way is not actable;

the same way it wouldn't be if I'd ask "Nativescript should not use a bridge like Flutter",
how?

May I ask you what native API you have problem to access to?
I believe the available plugins are quite comprehensive.
Thank you

**Comment by ansarizafar** [comment]
I am not familiar with the internals of both Nativescript or Flutter. It seems easier for the developers to get 0-day support for Android and iOS device APIs from Dart without writing a plugin but If it is not possible in Flutter world then its Ok.

**Comment by iapicca** [comment]
Hi @ansarizafar 
for now I'm closing this issue as not workable.

if you don't find a pre-existing first party plugin 
that allows you to access a native api 
please don't hesitate to comment here
or opening a specific issue.
Thank you
