### ISSUE TITLE
Provision devicelab hardware for Web benchmarks

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#50164]
We need machines that are able to execute the following successfully:

```
cd dev/devicelab
CALIBRATED=true ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t bin/tasks/web_benchmarks_canvaskit.dart
```

Specs:

- 2 agents
- Linux
- Laptop-grade 2-4 core i5 with built-in Iris Graphics
- If a discrete GPU is used, something low-end

/cc @godofredoc

**Comment by godofredoc** [comment]
Can you please take a look at the following data and let me know if it looks correct?

Task result:
{
  "success": true,
  "data": {
    "bench_card_infinite_scroll.canvaskit.averageDrawFrameDuration": 3630.0,
    "bench_card_infinite_scroll.canvaskit.drawFrameDurationNoise": 0.20535775767690362,
    "draw_rect.canvaskit.averageDrawFrameDuration": 10047.0,
    "draw_rect.canvaskit.drawFrameDurationNoise": 0.03941708407567515,
    "text_out_of_picture_bounds.canvaskit.averageDrawFrameDuration": 4916.0,
    "text_out_of_picture_bounds.canvaskit.drawFrameDurationNoise": 0.03579845933080272,
    "bench_simple_lazy_text_scroll.canvaskit.averageDrawFrameDuration": 10321.0,
    "bench_simple_lazy_text_scroll.canvaskit.drawFrameDurationNoise": 0.049125278555648855,
    "build_material_checkbox.canvaskit.averageDrawFrameDuration": 15411.0,
    "build_material_checkbox.canvaskit.drawFrameDurationNoise": 0.0893637632145183
  },
  "benchmarkScoreKeys": [
    "bench_card_infinite_scroll.canvaskit.averageDrawFrameDuration",
    "draw_rect.canvaskit.averageDrawFrameDuration",
    "text_out_of_picture_bounds.canvaskit.averageDrawFrameDuration",
    "bench_simple_lazy_text_scroll.canvaskit.averageDrawFrameDuration",
    "build_material_checkbox.canvaskit.averageDrawFrameDuration"
  ]
}

**Comment by yjbanov** [comment]
Thanks for making the progress on the new hardware! There are no correct or wrong numbers. They depend on the hardware. We are mostly looking for predictability and baselines.

What are the specs for these machines?

**Comment by godofredoc** [comment]
It is actually the same vm I just enabled a x11 server wrapper. The specs are:

CPU: Intel Broadwell
16 vCPUs
60 GB memory
100G hard disk

**Comment by yjbanov** [comment]
So the litmus test is to run the benchmarks without the `--headless` Chrome option. A couple of ways we can test it:

- SSH to the new machine and run benchmarks manually.
- Mark benchmarks as flaky, remove the `--headless` option and see what happens.

Is `linux-vm` routed to this new configuration?

**Comment by digiter** [comment]
My understanding of the next steps are:
- [ ] Creating a devicelab linux VM on GCE with Nvidia Tesla k80 GPU (the lowest spec on GCP).
- [ ] SSH into the machine, clone flutter/flutter repo and run this command
```
cd dev/devicelab
CALIBRATED=true ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t bin/tasks/web_benchmarks_canvaskit.dart
``` 

Is that correct? How do we verify the second step works without `--headless`? @yjbanov

**Comment by godofredoc** [comment]
to be able to run the test without headless we need to install and configure x-server.

**Comment by digiter** [comment]
From Yegor: "This is about changing the linux-vm devicelab agent so it can run the benchmarks with real graphics. Currently we run in headless mode, so our graphics-related numbers are bogus."

**Comment by godofredoc** [comment]
The current ubuntu VMs support are ready for this type of testing.
