### ISSUE TITLE
The following error throws everytime app runs on emulator. I tried to create new project and also tried to update the version of packages and it still showing error.

### ISSUE THREAD

**Issue by ThitSarNyanLynn** [flutter/flutter#50176]
Running Gradle task 'assembleDebug'...
Note: C:\Users\asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\camera-0.5.7+3\android\src\main\java\io\flutter\plugins\camera\CameraPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\permission_handler-4.2.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionHandlerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: C:\Users\asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\video_player-0.10.6\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.

**Comment by iapicca** [comment]
Hi @ThitSarNyanLynn 
please take a look to this [answer](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ThitSarNyanLynn** [comment]
Hello @iapicca ,
I already tried that from that link before posting on this.
I also tried by upgrading Flutter plugin and also android studio.
And it doesn't work and keep showing error like I posted.

**Comment by iapicca** [comment]
Hi @ThitSarNyanLynn 
a `warning` is not an `error`
and as stated in the answer `this was deliberate and temporary.`
for the moment please just ignore the warnings
thank you
