### ISSUE TITLE
runZoned onError doesn't catch errors after last flutter upgrade

### ISSUE THREAD

**Issue by Nik-Alex** [flutter/flutter#50188]
After the last flutter upgrade my app cannot catch errors in runZoned onError method.
I see error stack trace in the AndroidStudio logcat, but don't see my logs from runZoned onError and because of that I cannot track those errors with Crashlytics and Sentry.

`runZoned<Future<void>>(() async {
    runApp(App());
  }, onError: (error, stackTrace) async {
    print('ERROR: ZONED');
    print('${error.toString()}\n${stackTrace.toString()}');
  });`

**Test error:**
` onPressed: () {
              Future<void>(() {
                final List<int> list = <int>[];
                print(list[100]);
              });
            },`

**Flutter Doctor:**
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (9 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Nik\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

**Comment by mateusfsilva** [comment]
Hi,

We have a similar problem in our project. Did you find a solution? Why did you close the issue?

**Comment by Nik-Alex** [comment]
Hi,
I closed it, because it's not an issue. I just
misunderstood WidgetsFlutterBinding.ensureInitialized(); which we should in
main after the last flutter updates.
I should move it to runZoned to catch errors.
Like this:

чт, 6 февр. 2020 г. в 22:42, Mateus Gustavo de Freitas e Silva <
notifications@github.com>:

**Comment by Nik-Alex** [comment]
I closed the issue, because I misunderstood how to use
WidgetsFlutterBinding.ensureInitialized() which we need to add after
the last flutter update.

In my case I used in the outside of runZoned scope and had to move it
to the inside of the runZoned.

runZoned<Future<void>>(() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(App());
}, onError: (error, stackTrace) async {
  print('\n${error.toString()}\n${stackTrace.toString()}');
});


чт, 6 февр. 2020 г. в 22:42, Mateus Gustavo de Freitas e Silva <
notifications@github.com>:

**Comment by varpa89** [comment]
@mateusfsilva I found these issues
https://github.com/flutter/flutter/issues/47447
https://github.com/flutter/flutter/issues/44407
