### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by fokin-young** [flutter/flutter#50181]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':flutter:compileRsRelease'.                  
> Cannot expand ZIP '/Users/young/Documents/StudioProjects/market-flutter/.android/Flutter/build/intermediates/compile_only_not_namespaced_r_class_jar/release/generateReleaseRFile/R.jar' as it does not exist.

**Comment by VladyslavBondarenko** [comment]
Hi @fokin-young 
Can you please provide your `flutter doctor -v` 
And what the command do you run?
Thank you

**Comment by fokin-young** [comment]
[✓] Flutter (Channel unknown, v1.12.13, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.12.13 at /Users/young/Documents/flutter
    • Framework revision cf37c2cd07 (3 months ago), 2019-11-25 12:04:30 -0800
    • Engine revision b6b54fd606
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/young/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/young/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by TahaTesser** [comment]
Hi @fokin-young 
Can you please provide `flutter build apk --verbose`?
Thank you

**Comment by nightfallsad** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':flutter:compileRsRelease'.
> 
> > Cannot expand ZIP '/Users/young/Documents/StudioProjects/market-flutter/.android/Flutter/build/intermediates/compile_only_not_namespaced_r_class_jar/release/generateReleaseRFile/R.jar' as it does not exist.

Use com.kezong:fat-aar?If the answer is yes,you can upgrade the 'fat-arr' plugin version to 1.2.6 to resolve this issue.

**Comment by nysin** [comment]
@nightfallsad
your answer resolved my question! thx

**Comment by nysin** [comment]
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task ':flutter:compileRsRelease'.
> > 
> > > Cannot expand ZIP '/Users/young/Documents/StudioProjects/market-flutter/.android/Flutter/build/intermediates/compile_only_not_namespaced_r_class_jar/release/generateReleaseRFile/R.jar' as it does not exist.
> 
> Use com.kezong:fat-aar?If the answer is yes,you can upgrade the 'fat-arr' plugin version to 1.2.6 to resolve this issue.

upgrade fat-aar version it's ok .thx!
