### ISSUE TITLE
Add curved polyline to google map

### ISSUE THREAD

**Issue by ankit007im** [flutter/flutter#50189]
I am try to make polyline more curved. I have tried
 `_polyline.add(Polyline(
      polylineId: PolylineId("Line 1"),
      visible: true,
      points: [_new,_news],
      color: Colors.blue,
      width: 2,
      geodesic: true,
    ));`
but the line look straight.

**Comment by VladyslavBondarenko** [comment]
Hi @ankit007im 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/49189
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
