### ISSUE TITLE
firebase messaging subscribe to topic not working on iOS

### ISSUE THREAD

**Issue by prabh045** [flutter/flutter#50185]
inside main file in init after subscribing to push notifications successfully

_firebaseMessaging.getToken().then((onValue) {
      Indicator.fcmToken = onValue;
      **print("FCM TOKEN IS ${Indicator.fcmToken}")**;
      _firebaseMessaging.subscribeToTopic("Football").then((onValue) {
        print("Topic Subscribed Successfully");
      }).catchError((onError) {
        print("error subscribing to topic ${onError.toString()}");
      });
    }).catchError((onError) {
      print("Error in fcm token ${onError.toString()}");
    });
  }

FCM Token gets print on console but after that nothing. no error , no topic subscribed.
Tried writing in native code with messaging.messaging() but that also dont run.
Tried writing somewhere randomly in app but still no success 
Token also does not appear on firebase console

Output of flutter doctor -v 

[✓] Flutter (Channel master, v1.12.17-pre.38, on Mac OS X 10.14.5 18F132, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

**Comment by VladyslavBondarenko** [comment]
Hi @prabh045 
Please open the issue in the [plugin's github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by prabh045** [comment]
i have opened it there too  but i dont think the problem is in plugin too. Some where my ios project is messed up i suppose. You should reopen it may be some one knows something. May be i need to add something to xcode which i need to know about.
