### ISSUE TITLE
Gallery, Scrollable tabs: tab body and tab header settling at different times

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5018]
This is more of a feature request (enhancement) than a bug. I think.

Open the gallery, then Scrollable tabs. Swipe back and forth.

Notice that the tab body settles into place before the tab header settles into place.

Here's the slow-mo version of the animations: https://youtu.be/t9nmTPy8zlw

Regular speed: https://youtu.be/N_0e6Emvy2g

Regular speed, but sloooowly swiping: https://youtu.be/M3tMUTvx4vo

Notice how in the above video, the tab body and the underline movements are synced, but the tab header movement is not synced. It pops into place.

We might want to consider synchronizing the movement of the underline, tab body, and tab header, such that all three land in their final place at the same time. And, as the finger swipes back and forth, all three are moving together.

Here's a video of Play Newstand. Notice how the underline, tab body, and tab header all end at the same time: https://youtu.be/xxYafHZ_GVY

**Comment by HansMuller** [comment]
This doesn't appear to be an issue anymore.
