### ISSUE TITLE
Why it's not `AppLifecycleState.paused` when a PageRoute been pushed in to stack.

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#50182]
When I call `.push` a new route to current page.

The current page's state not become `AppLifecycleState.paused`.

I know there's needs for update the previous route's title on back button.

But I think the title can be calculate when a route event(`push` or `pop` and so on) happened which is a just a moment. 

I would expect the most of the time for the route in stack which is not on the top most be the state of `AppLifecycleState.paused`.

**Comment by iapicca** [comment]
HI @jerryzhoujw 
I like your question,
I'll try to come back to you w/ an answer soon
thank you

**Comment by goderbauer** [comment]
The `AppLifecycleState` is the state of your entire application as a whole as seen by the operating system. When you push a new Route, your application is running and visible to the user, which means its `AppLifecycleState` is `resumed`. See also the documentation for the different state values: https://master-api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html

**Comment by jerryzhoujw** [comment]
Hi @goderbauer , Thank you.  so it's `Application level` state.
