### ISSUE TITLE
app can't compile on my mac because dependencies aren't install for xcode build

### ISSUE THREAD

**Issue by julienthueux** [flutter/flutter#50190]
Hello everyone,

I have a problem with my application, I can't compile it.

> Launching lib/main.dart on 5€ le wifi in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: 2D2PNSCJ93
> Running pod install...
> Running Xcode build...
> Xcode build done.                                           20,0s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     2020-02-05 14:51:29.989 xcodebuild[37196:111057] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7f8cfdeb0c00), 5€ le wifi, iPhone, 13.3 (17C54), 00008030-001E4D503ED0802E> == Underlying device preparation errors ==
>     2020-02-05 14:51:29.989 xcodebuild[37196:111057] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7f8cfdeb0c00), 5€ le wifi, iPhone, 13.3 (17C54), 00008030-001E4D503ED0802E> -- Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.
>     Domain: com.apple.platform.iphoneos
>     Code: 5
>     Failure Reason: allowsSecureServices: 1. isConnected: 0. Platform: <DVTPlatform:0x7f8cfb71fc30:'com.apple.platform.iphoneos':<DVTFilePath:0x7f8cfb71fbb0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>. DTDKDeviceIdentifierIsIDID: 0
>     --
>     2020-02-05 14:51:29.989 xcodebuild[37196:111057] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7f8cfdeb0c00), 5€ le wifi, iPhone, 13.3 (17C54), 00008030-001E4D503ED0802E> == END: Underlying device preparation errors ==
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     /Users/julienthueux/Epitech/dev_area_2019/area_mobile/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'webview_flutter' not found
>     @import webview_flutter;
>      ~~~~~~~^~~~~~~~~~~~~~~
>     1 error generated.
>     error: the following command failed with exit code 1 but produced no further output
>     CompileC /Users/julienthueux/Library/Developer/Xcode/DerivedData/Runner-cxeqmcngnwmuovbkknctbglnpvpg/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o /Users/julienthueux/Epitech/dev_area_2019/area_mobile/ios/Runner/GeneratedPluginRegistrant.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>     note: Using new build system
>     note: Planning build
>     note: Constructing build description
> 
> Could not build the precompiled application for the device.
> 
> It appears that your application still contains the default signing identifier.
> Try replacing 'com.example' with your signing id in Xcode:
>   open ios/Runner.xcworkspace
> 
> Error launching application on 5€ le wifi.

("5€ le wifi" is my phone)

when I run "flutter doctor" I have no error:

<img width="682" alt="Capture d’écran 2020-02-05 à 14 58 22" src="https://user-images.githubusercontent.com/40702245/73848195-f637d500-4827-11ea-9462-e4ec4028e3f9.png">

When I run "pod install" in the IOS directory, no dependencies are install. I think that "flutter pub get" don't install dependencies in Cocoapod ...

> pod install
> Analyzing dependencies
> Downloading dependencies
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
> 
> [!] The Podfile does not contain any dependencies.
> 
> [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

If somebody have already see this problem can you tell me how to adjust it.
Thanks in advance and have a good day =).

**Comment by VladyslavBondarenko** [comment]
Hi @julienthueux 
Next time please don't post screenshots of text, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

have you run `flutter pub get` after adding dependency into your `pubspec.yaml`?

**Comment by julienthueux** [comment]
Hi @VladyslavBondarenko,

Yes I run "flutter get pub" after adding dependency into `pubspec.yaml`

**Comment by VladyslavBondarenko** [comment]
@julienthueux 
Related to https://github.com/flutter/flutter/issues/10770
Try https://github.com/flutter/flutter/issues/41033#issuecomment-534604875
Does it solve the error?

**Comment by julienthueux** [comment]
@VladyslavBondarenko I try but nothing works good, I think the problem it's when I run 'flutter gut pub', nothing is written in the PodFile, so when I try to run 'Pod install' nothing happen and the dependency aren't install... but how to resolve this problem ? good question. I try to reinstall flutter, I try dev branch, I try to reinstall Cocoapod but nothing works ... Help :'(

**Comment by jmagman** [comment]
Can you attach your pubspec.yaml?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
