### ISSUE TITLE
Gallery, Time picker: Missing AM/PM selector?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5019]
(was testing on an iPod Touch)

Does our time picker allow a user to pick AM or PM? If so, we can add that to our time picker in the gallery?

Thanks!

**Comment by abarth** [comment]
It should be there.  Maybe you can't see it because your screen is narrow?

**Comment by HansMuller** [comment]
It looks like we've developed a layout problem in TimePicker. I'll fix it today.

Screenshot on Android in debug mode:

![screenshot](https://cloud.githubusercontent.com/assets/1377460/17107804/ac5bf8b6-5245-11e6-8400-67ba130829b1.png)

**Comment by sethladd** [comment]
> Maybe you can't see it because your screen is narrow?

It's possible. I was testing on an iPod Touch.

**Comment by sethladd** [comment]
Thanks!
