### ISSUE TITLE
ModalRoute.of(context).settings returns RouteSettings("null", null) when using onGenerateRoute

### ISSUE THREAD

**Issue by royibernthal** [flutter/flutter#50192]
I'm trying to extract RouteSettings inside of a route's didChangeDependencies() using ModalRoute.of(context).settings.

When I'm passing the routes argument to MaterialApp, everything works as expected.

However, when instead of routes I'm passing onGenerateRoute to MaterialApp and creating the route myself there, ModalRoute.of(context).settings suddenly returns RouteSettings("null", null).

Is this an expected behavior? Am I possibly overriding the default route generation method which is also responsible for keeping ModelRoute up to date?

One guess I have is the context is no longer the route's context, so ModalRoute.of(context) for that context won't be valid anymore. If so, how can I make the route's widget's context remain the route's context?

Here's the method I'm passing to MaterialApp's onGenerateRoute:

```
Route<dynamic> generateRoute(RouteSettings settings) {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        //some custom code

        return _data[settings.name](context);
      }
    );
  }
```

Here's a gist of how _data looks like:

```
Map<String, Widget Function(BuildContext context)> _data = {
    home: (BuildContext context) => InitScreen(),
    init_profile: (BuildContext context) => InitProfileScreen()
}
```

**Comment by VladyslavBondarenko** [comment]
<details>
 <summary>Related code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

const String home = 'home';
const String init_profile = 'init_profile';

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Map<String, Widget Function(BuildContext context)> _data = {
    home: (BuildContext context) => InitScreen(),
    init_profile: (BuildContext context) => InitProfileScreen()
  };

  Route<dynamic> generateRoute(RouteSettings settings) {
    return MaterialPageRoute(builder: (BuildContext context) {
      print(ModalRoute.of(context).settings);
      return _data[settings.name](context);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: home,
      onGenerateRoute: generateRoute,
    );
  }
}

class InitScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.pushNamed(context, init_profile);
        },
      ),
      body: Center(child: Text('InitScreen')),
    );
  }
}

class InitProfileScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.pushNamed(context, home);
        },
      ),
      body: Center(child: Text('home')),
    );
  }
}
```

</details>

@royibernthal but I'm not sure how exactly do you use `didChangeDependencies()`

**Comment by royibernthal** [comment]
@VladyslavBondarenko The navigation itself works and the settings in generateRoute are correct, however if you try to call ModalRoute.of(context).settings in a stateful widget's state's didChangeDependencies, you'll get RouteSettings("null", null).

I'm using didChangeDependencies instead of initState in this case since context is not available during the initState phase.


```
bool _initialized = false;

@override
void didChangeDependencies() {
	if (!_initialized) {
	  log( ModalRoute.of(context).settings ); //RouteSettings("null", null)
	  
	  //some custom code
	  
	  _initialized = true;
	}

	super.didChangeDependencies();
}
```

**Comment by karmazinkd** [comment]
I can confirm this, the same issue here. 

Moreover, even in the widget's `build()` method (not only in initState or didChangeDependencies)  `ModalRoute.of(context).settings.name` gives **null**.

Even though in the `onGenerateRoute: (settings)` callback the `settings.name` is present.

**Comment by karmazinkd** [comment]
As a workaround, you can use `routes:` instead of `onGeneratedRoute:`

```
MaterialApp(
  routes: {
    ExtractArgumentsScreen.routeName: (context) => ExtractArgumentsScreen(),
  },
);
```

in this case, calling `ModalRoute.of(context).settings` will give you the valid settings object with the name and arguments (if you added them).

**Comment by royibernthal** [comment]
> As a workaround, you can use `routes:` instead of `onGeneratedRoute:`
> 
> ```
> MaterialApp(
>   routes: {
>     ExtractArgumentsScreen.routeName: (context) => ExtractArgumentsScreen(),
>   },
> );
> ```
> 
> in this case, calling `ModalRoute.of(context).settings` will give you the valid settings object with the name and arguments (if you added them).

Indeed, as I specified in the main issue - routes work.
However, the problem is that a different builder function must be passed for every route.
My goal in the first place is to run the same custom code for each generated route without code duplication, thus I'm using generateRoute instead.

**Comment by yassinesabri** [comment]
I am facing the same issue, whenever I call `ModalRoute.of(context).settings.name` I get null.

Does anyone have any workaround to solve this and keep using onGenerateRoute ?

Thanks

**Comment by IGR777** [comment]
@royibernthal I believe you should pass RouteSettings to your MaterialPageRoute:
```
Route<dynamic> generateRoute(RouteSettings settings) {
    return MaterialPageRoute(
      settings: settings,
      builder: (BuildContext context) {
        //some custom code

        return _data[settings.name](context);
      }
    );
  }
```

**Comment by royibernthal** [comment]
> @royibernthal I believe you should pass RouteSettings to your MaterialPageRoute:
> 
> ```
> Route<dynamic> generateRoute(RouteSettings settings) {
>     return MaterialPageRoute(
>       settings: settings,
>       builder: (BuildContext context) {
>         //some custom code
> 
>         return _data[settings.name](context);
>       }
>     );
>   }
> ```

Oh, I didn't notice that argument. Thanks :)

**Comment by RadheshyamSingh** [comment]
I was also facing same issue. I was getting RouteSettings("null", null), whenever i was calling ```ModalRoute.of(context).settings.name```. I did one change, pass settings to the  MaterialPageRoute and now it's working fine for me. 

```
Route<dynamic> generateRoute(RouteSettings settings) {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        //some custom code
        return _data[settings.name](context);
      },
      settings: settings
    );
  }
```

**Comment by anandrikka** [comment]
@IGR777 Thanks it's working, so easy to miss documentation.

**Comment by GaneshvrBhat** [comment]
Can someone help me understand what am I doing wrong? so that upon using ModalRoute.of(context).settings.name, I always get route as '/', which is the initial route.

`class RouteGenerator {
  static String _routeName;
  static String get routeName => _routeName;

static Route<dynamic> generateRoute(RouteSettings settings) {
Map<String, Widget Function(BuildContext context)> _data = {
      '/': (BuildContext context) => SplashScreen(),
      '/loginPage': (BuildContext context) => LoginPage(),
      '/homePage': (BuildContext context) => HomePage(),
      '/otpPage': (BuildContext context) => OtpPage(data: args)
    };

    return MaterialPageRoute(
        settings: settings,
        builder: (BuildContext buildContext) {
          return _data[settings.name](buildContext);
        });
}
}`

` print("Route from RouteGenerator variable:\t ${RouteGenerator.routeName}");
      var route = ModalRoute.of(context);
      if (route != null) {
        print("Route from ModalRoute:\t ${route.settings.name}");
      }`

Logs: 
I/flutter ( 8632): Route from RouteGenerator variable:	 /otpPage
I/flutter ( 8632): Route from ModalRoute:	 /
I/flutter ( 8632): Route from RouteGenerator variable:	 /homePage
I/flutter ( 8632): Route from ModalRoute:	 /
