### ISSUE TITLE
AssertionError in Flutter rendering pipeline during navigation

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#502]
In checked mode, navigating around a Flutter app (via app-code-based navigation or the back button) yields the following assertion error:

android: I/flutter : -- EXCEPTION IN SCHEDULER CALLBACK --
android: I/flutter : 'packages/flutter/src/rendering/object.dart': Failed assertion: line 374: '_renderObject != null' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      Painter.detach (packages/flutter/src/rendering/object.dart:374)
android: I/flutter : #2      ScrollbarPainter.detach (packages/flutter/src/material/scrollbar_painter.dart:78)
android: I/flutter : #3      RenderBlockViewport.overlayPainter= (packages/flutter/src/rendering/block.dart:311)
android: I/flutter : #4      _HomogeneousViewportElement.unmount (packages/flutter/src/widgets/homogeneous_viewport.dart:84)
android: I/flutter : #5      _InactiveElements._unmount (packages/flutter/src/widgets/framework.dart:476)
android: I/flutter : #6      _InactiveElements._unmount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:480)
android: I/flutter : #7      OneChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1557)
android: I/flutter : #8      _InactiveElements._unmount (packages/flutter/src/widgets/framework.dart:478)
android: I/flutter : #9      _InactiveElements._unmount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:480)
android: I/flutter : #10     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1090)
android: I/flutter : #11     _InactiveElem

**Comment by Hixie** [comment]
Need a minimised test case to be able to do much here.

**Comment by abarth** [comment]
How can we reproduce this issue?

**Comment by abarth** [comment]
Please re-open this bug if you have more specific steps for how to reproduce the issue.
