### ISSUE TITLE
Add a unit-test harness for scripts used by infra.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50207]
We are moving more of the infra logic into bespoke scripts that reside within the Engine itself. However, these scripts are not unit-tested, sometimes rely on environment variables that are only specified on bots, and are usually platform specific. This leads to hard to debug issues such as this one concerning [build ID capture for symbol generation](https://github.com/flutter/engine/pull/16397).

We need to have a unified, cross-platform test harness for all scripts used by infra.

**Comment by chinmaygarde** [comment]
cc @dnfield @iskakaushik

**Comment by godofredoc** [comment]
What would be the action items for this? ask everyone to write tests for infra scripts? how can we enforce it?

**Comment by chinmaygarde** [comment]
Having a test harness at all would be a start. Adding tests for existing scripts would come next. Right now, these scripts are somewhat haphazardly scattered throughout the codebase.

**Comment by Aarush-Acharya** [comment]
@godofredoc can i take this up, if its available?

**Comment by godofredoc** [comment]
Hi @Aarush-Acharya, sure please go ahead. Let me know if you need more details.

**Comment by jonahwilliams** [comment]
Closing as obsolete
