### ISSUE TITLE
Allow requesting additional scopes via the google_sign_in plugin

### ISSUE THREAD

**Issue by emerssso** [flutter/flutter#50208]
## Use case

The GoogleSignIn APIs for [Android](https://developers.google.com/identity/sign-in/android/additional-scopes), [iOS](https://developers.google.com/identity/sign-in/ios/additional-scopes), and [Web](https://developers.google.com/identity/sign-in/web/incremental-auth) all provide a mechanism to request additional scopes after sign-in. It would be helpful for the google_sign_in plugin to also provide a mechanism to check granted scopes and grant new scopes (i.e. optional scopes or scopes for new features).

## Proposal

Offer two new APIs on `GoogleSignIn`:
`Future<bool> hasGrantedScope(String scope);` Which indicates if `scope` has already been granted by `currentUser`.
`Future<bool> requestScope(String scope);` Which requests `scope` be granted by the `currentUser`.

**Comment by emerssso** [comment]
I'll try to put together a PR which adds these to the plugin, just wanted to start a conversation about the proposal first.

**Comment by emerssso** [comment]
Feature is available on pub now.

**Comment by BoonJunTan** [comment]
Hey can I check if this is implemented and if there is a documentation for this as I couldn't find it anywhere online.
