### ISSUE TITLE
Easy way to disable slow mode banner for screenshots?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5021]
It's very common to try and take a screenshot from the iOS simulator.

Right now the best way to do that is to figure out that:
https://docs.flutter.io/flutter/material/MaterialApp/debugShowCheckedModeBanner.html
exists and then edit your source code and flutter run again.

Maybe we should make `flutter screenshot` just turn off the banner before taking the screenshot?  Or give a --no-banner argument to flutter run?

Probably not important enough to solve in the near term, but I keep seeing people confused by this.

**Comment by eseidelGoogle** [comment]
@Hixie if I were to wire this up, would you prefer that I add a service protocol extension to toggle this with `flutter screenshot` (I'm not sure how flutter screenshot would find the observatory port), or that I add a --no-banner option?  Or something else?

**Comment by Hixie** [comment]
If `flutter screenshot` could temporarily toggle it that would be best.

**Comment by svantepolk** [comment]
Using flutter to take a screenshot while connected to the iOS simulator seems to produce an image which is not the correct resolution for the required App Store screenshots. I had to manually disable the banner as described in the original post, and use the simulator's screenshot functionality.
