### ISSUE TITLE
update_dart_sdk.sh does not handle spaces in paths well

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#5022]
We see:

```
usage: dirname path
```

from `update_dart_sdk.sh`.

https://github.com/flutter/flutter/blob/master/bin/cache/update_dart_sdk.sh#L8

**Comment by eseidelGoogle** [comment]
If we fix this and want to not break it again we'll want to change our bots to have a space in their path: https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/flutter/flutter.py  This is a very common problem for tools in a unix-like environment to not handle spaces well. :/

**Comment by Hixie** [comment]
@bkonyi This may be relevant to your current interests.

**Comment by christopherfujino** [comment]
Fixed in https://github.com/flutter/flutter/pull/8014
