### ISSUE TITLE
Sliver*List (Extend, Prototype and others) with different main axis.

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#50222]
## Use case
I'm trying to have nested list with different scrollDirection inside customScrollView or NestedScrollView.

I known that we can use SliverToBoxAdapter and then wrap the listview as the child but it's not really convenient and requires a lot of boilerplates and also if you don't known the height of your item, it's even more complicated.

## Proposal
Provide a scrollDirection parameter to the silver*list widgets or a widget that allow to change the main axis of a child of type sliver*list widget.

**Comment by Piinks** [comment]
> Provide a scrollDirection parameter to the silverlist widgets

Hi @bitsydarel, the scroll direction is provided to the SliverList in the SliverConstraints. Can you share more about your use case and what is not working? Some sample code would be very helpful in identifying what we can do here to help. Thanks!
