### ISSUE TITLE
macOS navigator.MediaDevices.getUserMedia error:  Permission denied by system NotAllowedError

### ISSUE THREAD

**Issue by pouledodue** [flutter/flutter#50230]
In a "normal" Chrome window, I can go to this url : https://webrtc.github.io/samples/src/content/getusermedia/audio/
and the microphone access will work.

However, on Chrome windows opened with `flutter run -d chrome`, the microphone access gives an error. It's annoying when the Flutter app I'm coding needs access to the microphone.

## Steps to Reproduce

```
flutter channel beta
flutter upgrade
flutter config --enable-web
flutter create myapp
cd myapp
flutter run -d chrome
```

Chrome opens...

now copy this url in Chrome that just opened:

https://webrtc.github.io/samples/src/content/getusermedia/audio/

Once loaded, open the Developer Console

**Expected results:** 

 expected in the console:
`Using audio device: Par défaut - Internal Microphone (Built-in)`
or something like that says the microphone is in use

**Actual results:** 

in console I see error:
`navigator.MediaDevices.getUserMedia error:  Permission denied by system NotAllowedError`

**doctor:**

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale fr-FR)
    • Flutter version 1.14.6 at /Users/poule/.flutter_sdk/flutter
    • Framework revision fabeb2a16f (8 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/poule/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/poule/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode1131.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools
```

And yes, in my macOS Prefs > Privacy, the Chrome checkbox is checked

**Comment by VladyslavBondarenko** [comment]
Probably this is related to the Chrome only on Mac OS, because on Windows I have the same behavior as in "normal" Chrome - asking permission for using microphone, and I can see the mentioned error only if I block it

**Comment by yjbanov** [comment]
This doesn't look like something we can fix in Flutter. This is purely a browser issue. Might I suggest searching StackOverflow?

**Comment by pouledodue** [comment]
I found the fix, it's the Terminal or iTerm if use iTerm that must be allowed Microphone and Camera access, because Chrome is started by Flutter from the Terminal I guess
