### ISSUE TITLE
IP acquisition of Fuchsia LUCI workers is flaky.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50246]
This leads to [errors like this](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/2406). Suggest retries or trying one of the other healthy idle bots (of which there were several).

**Comment by godofredoc** [comment]
Sometimes the paving process fails immediately when there are many paving processes running in the same machine. This can be fixed with adding some retries to the paving process.
