### ISSUE TITLE
AmberCtlException internal error causes flakes on Fuchsia LUCI workers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50249]
An example of one such exception [is here](https://chromium-swarm.appspot.com/task?id=4a301d72a7620710).

The specific issue is
```
AmberCtlException, cause: "amberctl get_up -n flutter_aot_runner failed, aborting.", underlying exception: OperationResult{failure, info: "Update failed with error fetch: Resolve status: ErrInternal, retrying...
Update failed with error fetch: Resolve status: ErrInternal, retrying...
Update failed with error fetch: Resolve status: ErrInternal, retrying...
", error: "2020/02/05 21:39:29 error getting an update: fetch: Resolve status: ErrInternal

```

**Comment by godofredoc** [comment]
I'd recommend to try to find an owner for this on the fuchsia side. This error is happening because the amberctl is not able to serve the content of flutter_aot_runner

**Comment by godofredoc** [comment]
Several teams are getting the same problem and fuchsia team is helping to triage. We need to collect verbose logs from the pm server and syslog to identify where the problems are.

Some pointers:

* pm web server may be sending truncated packages
* pm server may have crashed and not available anymore.

**Comment by godofredoc** [comment]
Actually this is because amber_ctl initializes and empty repository that only have access to the packages included in the test far file. To fix this we actually need to serve the packages coming with the core image in addition to the far file.
