### ISSUE TITLE
WeakPtrTest.CopyConstruction flaked on Fuchsia.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50247]
This specific failing [instance is here](https://chromium-swarm.appspot.com/task?id=4a306a3dd45b3b10). This one is a particular head scratcher as there are opportunities for deadlocks (in fact, there are no secondary threads at all) and the output from gtest does not show any tripped assertions. There is also no trace of the idle timeout worker thread killing the harness. It may indicate that the test runner is not giving us complete logs from failed test runs.

**Comment by godofredoc** [comment]
I think this is a test problem, removing infra.

**Comment by chinmaygarde** [comment]
We haven't seen this in many months. And I am not sure how this could happen as the test is so simple. Closing as inactionable.
