### ISSUE TITLE
Print the backtrace explicitly when assertions are tripped in all unit-test harnesses.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#50244]
The process dying without a backtrace makes fixing [issues like this](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8889257668455233520/+/steps/Host_Tests_for_host_profile/0/stdout) hard to diagnose. [A previous attempt](https://github.com/flutter/engine/pull/11431) of this endeavor was abandoned and must be revived and carried to completion.

**Comment by godofredoc** [comment]
Test related, removing infra.
