### ISSUE TITLE
in_app_purchase not retrieving past purchases when redeemed using promo codes on iOS

### ISSUE THREAD

**Issue by nemoryoliver** [flutter/flutter#50256]
#50071  Steps to Reproduce
Using the latest **in_app_purchase 0.3.0+2** 
My app and IAPs are already approved in the apple app store since February 4

1. Redeem a promo code successfully via App Store (IAP or Subscription)
2. Then query past purchases in your app

**Expected results:** 
Expecting to see/retrieve the redeemed in-app-purchase to be included in the past purchases when queried

**Actual results:** 
The empty array of past purchases

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-PH)
    • Flutter version 1.13.6 at /Users/nemoryoliver/Development/flutter
    • Framework revision 659dc8129d (5 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nemoryoliver/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (4 available)
    • BBD100 2      • 1164448822                               • android-arm64  • Android
      8.1.0 (API 27)
    • Oliver's iPad • caedeff388555a61b1d1f579d9f3cf3b2c17c42e • ios            • iOS
      12.4.4
    • Chrome        • chrome                                   • web-javascript • Google
      Chrome 79.0.3945.130
    • Web Server    • web-server                               • web-javascript • Flutter
      Tools

• No issues found!

</details>

**Comment by gaaclarke** [comment]
Can you write up a tiny example that will demonstrate the problem?  Is the promo unlocking then after you uninstall and reinstall it isn't showing up?  Did you try using `restoreTransactions`?

**Comment by TahaTesser** [comment]
Hi @nemoryoliver 
Please take a look a this [comment](https://github.com/flutter/flutter/issues/50256#issuecomment-585476886) above and please provide the details asked
Thank you

**Comment by TahaTesser** [comment]
Hi @nemoryoliver 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
