### ISSUE TITLE
[google maps] Which API Key should we get for Google Maps Flutter plugin?

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#50265]
On the Google Maps Flutter project page  https://pub.dev/packages/google_maps_flutter it mentions to get an API Key. Which one?
![image](https://user-images.githubusercontent.com/283347/73927862-7581e300-48d2-11ea-95c8-eb59e334432a.png)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by VladyslavBondarenko** [comment]
@giorgio79 
'Maps SDK for Android' or 'Maps SDK for iOS' if you need simply map for mobile.
https://medium.com/flutter/google-maps-and-flutter-cfb330f9a245 may be useful
