### ISSUE TITLE
saving data to file, but  getApplicationDocumentsDirectory() provide different values on IOS  when the app is removed from background and relaunched, so that data are lost, is there any turnaround ? or do I have to use other way to save local data ?

### ISSUE THREAD

**Issue by jfboisvieux** [flutter/flutter#50267]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Closing current issue since you opened a new https://github.com/flutter/flutter/issues/50267
