### ISSUE TITLE
Issue from website page 入门: 在macOS上搭建Flutter开发环境 (Getting Started: Setting Up the Flutter Development Environment on macOS)

### ISSUE THREAD

**Issue by coderMyy** [flutter/flutter#50260]
Failed to retrieve the Dart SDK from: https://storage.flutter-io.cn/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/dart-sdk-darwin-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
请问这是怎么回事 (What is going on?)

**Comment by VladyslavBondarenko** [comment]
Hi @coderMyy 
Do you see the error after [configuring to use a mirror site](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)?

**Comment by VladyslavBondarenko** [comment]
@coderMyy 
I hope you've solved this, 
Closing since long time without an answer
