### ISSUE TITLE
Chrome window is too big on start

### ISSUE THREAD

**Issue by Dibitybopty** [flutter/flutter#50278]
Whenever I run Flutter in Chrome from VSCode the window spans across both my monitors. I know it's not a massive issue but it's a little annoying having to keep resizing and positioning it.

Is there any way to change the size before it starts up?

**Comment by Zazo032** [comment]
This happens when the monitor configuration has 2 or more, if there's only one it's sized correctly. Maybe it's getting a bigger size because the monitor layout is bigger?

cc/ @stuartmorgan

**Comment by stuartmorgan** [comment]
@Zazo032 Why did you CC me? It's not clear to me what you're looking for from me here.

**Comment by jonahwilliams** [comment]
What version are you on? If you resize the window and leave it for a while, the preference should eventually be saved. Are you always force-quitting?

**Comment by Dibitybopty** [comment]
I'm on the latest version (Channel beta, v1.14.6). I've left the window open for hours and it will still open on my 2nd monitor and span across to my main. It even starts half-way down the screen so I have to lift the window up each time.

I've quit multiple different ways too. Was hoping there was some file I could edit that stores the position.

**Comment by jonahwilliams** [comment]
This was fixed with https://github.com/flutter/flutter/commit/3422540bc43d72d499750d9fae971d6ad4cd9e7d which is in v1.15.1 

This will likely be on the next beta, and currently works on dev and master

**Comment by jonahwilliams** [comment]
In the future please include the output of `flutter doctor -v` since this contains the exact version of the framework/engine you are using.
