### ISSUE TITLE
Option to keep navigation drawer always open

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#50276]
In flutter web would be very convenient in some cases to have the drawer fixed open, so you can interact with other content in the page and it stays open.
Many websites have this behavior. Such as youtube, gmail, google news, etc.

![Immagine](https://user-images.githubusercontent.com/34270884/73952689-90b71780-48ff-11ea-9abe-d38dd79240f3.png)

**Comment by yjbanov** [comment]
Removing the web label because this is a general feature request for all big screens.

/cc @HansMuller

**Comment by inceptusp** [comment]
I am starting to develop a web app and this function would be excellent to have...

**Comment by danieramiz** [comment]
Any update on this one?

**Comment by ahmedmgh67** [comment]
Any updates here?

**Comment by amadeu01** [comment]
It would be awesome. Also, it follows the material design guideline for the web.

**Comment by RegisSaffi** [comment]
Any update regarding this?

**Comment by dentra** [comment]
We need gmail-like look and behavior for drawer in web apps. Please give us any estimation for this feature.

**Comment by lukas-h** [comment]
Any updates on "standard" and "bottom" drawers? https://material.io/components/navigation-drawer

**Comment by TheOneWithTheBraid** [comment]
You can get an implementation of a working responsive drawer scaffold here: https://gitlab.com/testapp-system/testapp-flutter/-/blob/mobile/lib/drawer.dart#L219

**Comment by Alkanores** [comment]
Any update?

**Comment by michaldev** [comment]
This will be useful.

**Comment by dchristo978** [comment]
Hope the devs prioritize this feature

**Comment by sanjay070783** [comment]
It would be awesome feature for web applications. Any update on this?

**Comment by gehad-ahmed-mohamed** [comment]
Any updates for this feature ?

**Comment by swdevbali** [comment]
Opting this!

**Comment by Levi-Lesches** [comment]
One workaround I use is having a `Row` for `Scaffold.body`, and then making the first widget a `Drawer`, and the second the actual body. By not including it in the `Scaffold`, the `AppBar` doesn't take control of the `Drawer`. 

So something like this: 
```dart
class FullScreenPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: Text("Big screen web app")),
    body: Row(
      children: [
        Drawer(/* Menu items here */),
        Placeholder(/* Normal body here */),
      ]
    )
  );
} 
```

**Comment by swdevbali** [comment]
Right! Thank you.
It works!

**Comment by adadion** [comment]
> One workaround I use is having a `Row` for `Scaffold.body`, and then making the first widget a `Drawer`, and the second the actual body. By not including it in the `Scaffold`, the `AppBar` doesn't take control of the `Drawer`.
> 
> So something like this:
> 
> ```dart
> class FullScreenPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Scaffold(
>     appBar: AppBar(title: Text("Big screen web app")),
>     body: Row(
>       children: [
>         Drawer(/* Menu items here */),
>         Placeholder(/* Normal body here */),
>       ]
>     )
>   );
> } 
> ```

The thing is, with this approach, you will lose back navigation from the appbar :(

**Comment by michaelbushe** [comment]
@Levi-Lesches' solution works for the question and for web/Android, but to follow the guidelines on iOS you need to remove the AppBar - what iOS calls a Split View.  It's the way iOS Mail app looks like on iPad.  
https://developer.apple.com/design/human-interface-guidelines/ios/views/split-views/

**Comment by SaremS** [comment]
Is there already an out-of-box solution available or is @Levi-Lesches' example the go-to workaround for now?

**Comment by Levi-Lesches** [comment]
There are a few packages on pub.dev, such as [`adaptive_navigation`](https://pub.dev/packages/adaptive_navigation) (by the Material team) and [`adaptive_scaffold`](https://pub.dev/packages/adaptive_scaffold), but I personally found that neither fit the feel or functionality of my app, so I built my own version (more complex than my comment above). It's certainly not impossible and allows you to have greater control than those packages can give you.

**Comment by devaronius** [comment]
Any updates for this feature?

**Comment by aidan-mundy** [comment]
This is a pretty critical item for meeting the Material Design standards while building multi-platform apps. It would be nice to see something implemented soon

**Comment by copypasteearth** [comment]
im actually looking for the same thing, does anyone know how to do this?

**Comment by Levi-Lesches** [comment]
See my [comment](https://github.com/flutter/flutter/issues/50276#issuecomment-759863660) above, which is basically keeping the `Drawer` in your Scaffold's body instead of in the designated `Scaffold.drawer` field.

**Comment by nidegen** [comment]
Maybe some may be happy with a navigation rail instead: https://api.flutter.dev/flutter/material/NavigationRail-class.html

**Comment by SithumDilanga** [comment]
> Maybe some may be happy with a navigation rail instead: https://api.flutter.dev/flutter/material/NavigationRail-class.html

Thats a good option

**Comment by darrenaustin** [comment]
Adding this to the Scaffold API would be complicated as it would mean moving the drawer into the content area. It would be better to have the application manage this itself. In addition, as pointed out above, we now have the Navigation Rail widget which can do this automatically and keeps the layout of the content area in control of the app (it also appears to be the direction that the Material Design spec is promoting). 

Given that options, I am going to close this issue.

**Comment by bradyt** [comment]
For future GitHub comments, please consider reducing usage of pronouns "this" and "it", for those of us less familiar with the problem space.

Specific examples:

> do this automatically

> it also appears to be the direction that the Material Design spec is promoting

Those pronouns compound my confusion as to the precise relevance of Navigation Bar in a thread about Navigation Drawer. I don't understand the problem space enough to construct a clarifying question. I'm not asking for clarification now. It's just a suggestion to avoid pronouns in the future.
