### ISSUE TITLE
dart-sdk\bin\dart.exe File dissapears!

### ISSUE THREAD

**Issue by tigrenok00** [flutter/flutter#50273]
Since this morning, every flutter command results in the following:
`'"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,`
including flutter doctor.
The dart.exe file is not present at this path.
The PATH variable for flutter dir is correct. I was working on the stable branch the whole time.
The only solution was to reinstall flutter (clone to a new git) and update the path to its new dir, then I switched to the stable branch and everything was working , including build an apk.
However, a couple of hours later this happened again! dart.exe file is no longer there.
What could be the cause of it and what could I provide to check this issue?
Thanks

**Comment by tigrenok00** [comment]
It sound similar to this issue, however, no answers there as well
https://github.com/flutter/flutter/issues/24592

**Comment by zanderso** [comment]
Hi @tigrenok00, thanks for filing this issue. Before it stops working, could you collect and share the output of `flutter doctor -v`?

Also, if you can share the sequence of commands you ran just before `dart.exe` disappeared that could be a useful clue as well. Thanks!

**Comment by tigrenok00** [comment]
Hi, this is the output after reinstalling flutter. I will continue working and will update with the latest commands when it will stop working again.

Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The
repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: C:\flutter2\flutter
  previous reference  : C:\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the      
expected version (run 'flutter --version' to see which flutter is on your path).


[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale he-IL)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter2\flutter
    • Framework revision 9f5ff2306b (13 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at C:\Users\Maria\AppData\Local\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = C:\Users\Maria\AppData\Local\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by tigrenok00** [comment]
Hi,
this happened again, my last working flutter command was "flutter build apk" (succesfull), after that again the dart.exe file is gone.
`'"C:\flutter2\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,
operable program or batch file.

`

**Comment by tigrenok00** [comment]
This is the content of the folder now:

![image](https://user-images.githubusercontent.com/23075641/74125212-4bd00100-4bdd-11ea-87f7-33bf7807a51f.png)

**Comment by tigrenok00** [comment]
Hi, I can confirm that this issue happens on the **v1.12.13+hotfix.7** version only, after building apk for a project with AndroidX incompatibilities.

This is the end of the build ouput:
`Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      64.4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'... `

It does not proceed to build the different repo but ends immediately. After that, the dart.exe file is gone.

It works fine on version **v1.12.13+hotfix.5**. Here is the build output when in works (and flutter and dart remain alive after that).
`
Running Gradle task 'assembleRelease'...                        
Running Gradle task 'assembleRelease'... Done                     149.4s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   11.2s
√ Built build\app\outputs\repo.
Building plugin evigance_img_registration...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    9.6s
√ Built build\app\outputs\repo.
Building plugin geolocator...
Running Gradle task 'assembleAarRelease'... Done                   13.3s
√ Built build\app\outputs\repo.
Building plugin google_api_availability...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   27.5s
√ Built build\app\outputs\repo.
Building plugin location_permissions...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    8.5s
√ Built build\app\outputs\repo.
Building plugin path_provider...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   10.5s
√ Built build\app\outputs\repo.
Removed unused resources: Binary resource data reduced from 791KB to 620KB: Removed 21%
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'... Done                     123.6s (!)
√ Built build\app\outputs\apk\release\app-release.apk (102.4MB).
`

**Comment by blasten** [comment]
@tigrenok00 it looks like some program running on your computer renamed `dart.exe` as `dart.exe.000`.  Do you have an antivirus or some other type of software that could be watching the code that is executed?

**Comment by tigrenok00** [comment]
@blasten 
Hi, I checked antivirus logs and you were right!
How do I fix this behavior? It is  Trend Micro Office Scan.
Please not this does not happen in hotfix5 version. Only with latest one.
Thanks!

**Comment by tigrenok00** [comment]
https://github.com/dart-lang/sdk/issues/36897

**Comment by blasten** [comment]
I'm not familiar with 'Trend Micro Office Scan', but if there's an option to whitelist a program, you can whitelist `dart.exe`.  I don't think this issue is only present on a specific version of Flutter, but it might be exacerbated by a specific one.

**Comment by juarejunjoseph** [comment]
Hello guys! can I have a copy of dart.exe in your file so that I can try to paste it on my directory. Thanks for your help in advance :)

**Comment by vasuvansia** [comment]
https://drive.google.com/open?id=1kXKc0uSh1_rE-QgAchiIVhDf7OeXUyKp

**Comment by zanderso** [comment]
I'm sure nothing malicious was intended , but I'd rather not normalize the practice of requesting and providing binaries from potentially untrusted sources here.

**Comment by huycozy** [comment]
Hi @tigrenok00, can you confirm you still facing this issue on the latest version of Flutter stable `3.0.5`?

> I'm not familiar with 'Trend Micro Office Scan', but if there's an option to whitelist a program, you can whitelist dart.exe. 

Also, did you try this workaround?

**Comment by huycozy** [comment]
Hi @tigrenok00, can you confirm you are still facing this issue on the latest version of Flutter stable `3.0.5`?

> I'm not familiar with 'Trend Micro Office Scan', but if there's an option to whitelist a program, you can whitelist dart.exe. 

Also, did you try this workaround?

**Comment by GaryQian** [comment]
This seem to be a third party antivirus bug, please report this to 'Trend Micro Office Scan', and whitelist dart in the meantime!
