### ISSUE TITLE
Deliver ICU via dynamic delivery on Android API 21+

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#50277]
Might require https://github.com/flutter/flutter/issues/22102

See https://developer.android.com/guide/app-bundle/dynamic-delivery

We could also probably come up with a way to do this for iOS.

We should be able to split ICU so that it only contains individual locales in it, and then only ship those to users with those locales on their system.  This could reduce base APK size.

/cc @xster @goderbauer @jason-simmons @blasten @matthew-carroll

**Comment by blasten** [comment]
@dnfield how much saving do you estimate this feature will have?

**Comment by blasten** [comment]
Also related to: https://github.com/flutter/website/issues/2215

**Comment by dnfield** [comment]
I don't have hard numbers.  @goderbauer has a doc with the sizes of various locales - it ranges from 50kb to 100kb per locale.  We've also trimmed out some locales to save size, which we could presumably add back under a scheme like this.

I'm also not sure that dynamic delivery is the _best_ way to achieve this, since it's very specific to Android. It may be better to come up with a more generic solution in which there is some storage bucket you can opt in to using that has the ICU data, and Flutter knows how to use it.

**Comment by blasten** [comment]
Are these locales shipped with the Framework, or are they defined by the app developer, or both?

**Comment by dnfield** [comment]
They're part of ICU, shipped in the image

**Comment by dnfield** [comment]
I'm going to close this. I don't think this is the best approach. 

We probably want to support dynamic loading for other reasons, but I'm going to file a different bug for ICU.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/50292
