### ISSUE TITLE
androidx-migration 

### ISSUE THREAD

**Issue by kristinacapistrano** [flutter/flutter#50281]
after choosing to migrate to androidx, I simply get "no usages found in the project"

**Comment by VladyslavBondarenko** [comment]
Hi @kristinacapistrano 
do you have 
```
android.useAndroidX=true
android.enableJetifier=true
```
in your `/android/gradle.properties`?

**Comment by kristinacapistrano** [comment]
yes

**Comment by VladyslavBondarenko** [comment]
@kristinacapistrano 
Does this workaround https://github.com/flutter/flutter/issues/44906#issuecomment-554924730 work for you?

**Comment by kristinacapistrano** [comment]
that didn't work, but something else did. it's fixed ! thank you!

**Comment by L-HommeSage** [comment]
Hi @kristinacapistrano what was your solution ? I'm stuck with the same problem.

**Comment by badees99** [comment]
@kristinacapistrano share the solution with the rest of us ? 
what is wrong with you mate ?
