### ISSUE TITLE
flutter_web benchmarks need baselines

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50280]
Until they're baselined, we shouldn't use them in the daily sweep to look for regressions. I'm not filing this as a TODAY issue, because it's impossible for me to know whether we've got issues here or not.

See the stuff towards the bottom of:

![benchmarks needing baselines](https://user-images.githubusercontent.com/1435716/73962556-84ad6480-48c3-11ea-87e5-bd7070a0574c.png)

**Comment by jonahwilliams** [comment]
@yjbanov

**Comment by yjbanov** [comment]
Done.
