### ISSUE TITLE
Support AOT unit-tests on Fuchsia

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#50285]
Dart doesn't implement `Dart_LoadELF` on Fuchsia (see https://github.com/dart-lang/sdk/blob/master/runtime/bin/elf_loader.h#L39), so we need to implement this using `Dart_LoadELF_Fd`

cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Let's just make this issue track to overarching goal of supporting AOT unit-tests on Fuchsia.

**Comment by arbreng** [comment]
Closed in favor of https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=91005

**Comment by zijiehe-google-com** [comment]
@rmacnak-google implemented this feature in dart/sdk, and it's now rolled into flutter. I will reenable the aot tests in flutter.
