### ISSUE TITLE
Bad error message to class constructor when 

### ISSUE THREAD

**Issue by LCostaN** [flutter/flutter#50283]
When using both `this.varName` and `class() : initVar = initVar` initializers with a non-constant value, it shows some weird error message.

This is a small issue and it requires doing 2 or 3 wrong things, but I felt like making a record of this.

```dart
class Test {
  List<int> example;

  Test({this.example}) : example ??= List();
}
```

> Expected an assignment after the field name.
> To initialize a field, use the syntax 'name = value'. dart(missing_assignment_in_initializer)
> '' isn't a field in the enclosing class.
> Try correcting the name to match an existing field, or defining a field named ''. dart(initializer_for_non_existent_field)

**Comment by jonahwilliams** [comment]
Issues of these type are better filled at github.com/dart-lang/sdk

**Comment by VladyslavBondarenko** [comment]
@LCostaN ,
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
