### ISSUE TITLE
document `--enable-web`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#50287]
In order to work with cocoon you need to run `flutter config --enable-web` but that isn't documented in the readme.

**Comment by digiter** [comment]
Triage: is this still an issue?

**Comment by gaaclarke** [comment]
@digiter According to our own documentation on web development, yes: https://flutter.dev/docs/get-started/web

There hasn't been a change to the cocoon documentation either.

**Comment by exaby73** [comment]
Hello @gaaclarke, is this still an issue now that web has gone stable?

**Comment by gaaclarke** [comment]
> Hello @gaaclarke, is this still an issue now that web has gone stable?

Nope.
