### ISSUE TITLE
Android engine should be built with frame pointers in profile mode

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#5028]
Running the engine with the Dart VM flag --profile-vm, which enables collecting profile samples in native code, leads to crashes.

@jason-simmons @johnmccutchan

**Comment by johnmccutchan** [comment]
This could be an optional GN argument:

"--profile=vm"

**Comment by Hixie** [comment]
@jason-simmons, @rmacnak-google, is this still an issue?

**Comment by Hixie** [comment]
Closing this per @a-siva
