### ISSUE TITLE
Issue from website page : Getting started: experience

### ISSUE THREAD

**Issue by xiaoyy1994** [flutter/flutter#50288]
![TIM截图20200207033358](https://user-images.githubusercontent.com/57230761/73971874-b32a4e80-495a-11ea-87d5-8bd0df9b69e4.png)

> 有大佬知道as新建flutter项目，报这个乱码吗？

Does anybody know as new flutter project, report this garbled?

**Comment by xiaoyy1994** [comment]
![TIM截图20200207033520](https://user-images.githubusercontent.com/57230761/73971966-e076fc80-495a-11ea-8480-e1446dc242a5.png)
这个乱码

**Comment by iapicca** [comment]
Hi @xiaoyy1994 
could you please describe the issue more in detail,
what difficulties are you encountering with your `getting started` experience?
Thank you

**Comment by VladyslavBondarenko** [comment]
@xiaoyy1994 
I hope you've solved the issue.
Closing as additional information isn't provided
