### ISSUE TITLE
Switch cirrus status calculation from Github check-runs to Cirrus API 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#50293]
See also https://cirrus-ci.org/api/

The Check-Runs API does not contain any information about restarted tasks. Therefore if a task fails, is interrupted, or killed the build immediately goes red until the restarted task completes. In practice this has lead to the build being red the vast majority of the time.

**Comment by fkorotkov** [comment]
You can run something like:

```console
curl -X POST --data \
'{
  "query": "query BuildBySHAQuery($owner: String!, $name: String!, $SHA: String) { searchBuilds(repositoryOwner: $owner, repositoryName: $name, SHA: $SHA) { id latestGroupTasks { id status } } }",
  "variables": {
    "owner": "flutter",
    "name": "flutter",
    "SHA": "d94ff4bdbec7f1141d16cf97d3ceed485c9a1d36"
  }
}' \
https://api.cirrus-ci.com/graphql | python -m json.tool
```

**Comment by fkorotkov** [comment]
To get all the latest tasks. It's the same query that is used on a Builds Details page of Cirrus. So if a task will be restarted there you'll see it in the response.

**Comment by keyonghan** [comment]
Looking into this.

**Comment by jonahwilliams** [comment]
Thank you @keyonghan and @fkorotkov

**Comment by keyonghan** [comment]
/api/refresh-cirrus-status has been changed to Cirrus API. We further need to update that in `waiting for tree to go green logic`.

**Comment by keyonghan** [comment]
Added to `waiting for tree to go green logic`: https://github.com/flutter/cocoon/pull/650.
Closing this issue as fixed. 
Please help reopen if you find any related issues.
