### ISSUE TITLE
Remove idevice_id, idevicename, ideviceinfo, ideviceinstaller from `libimobiledevice` cache package

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#50299]
After https://github.com/flutter/flutter/pull/50248 lands, the tool will no longer need the `idevice_id` and `ideviceinfo` binaries (and `idevicename` is already unused). Removing them from the pre-built package will mean removing the entries [here](https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/flutter/ios-usb-dependencies.py#66), updating the [mirrored repos](https://flutter-mirrors.googlesource.com/?format=HTML) (either with a trivial change, or better bringing them up to date with upstream), and rolling the new versions to the framework via the version files in flutter/bin/internal.

**Comment by jmagman** [comment]
idevicename is also gone with https://github.com/flutter/flutter/pull/50084.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/50248 is merged!

**Comment by christopherfujino** [comment]
ideviceinstaller is also gone

**Comment by cbracken** [comment]
Woohoo!

**Comment by zanderso** [comment]
@christopherfujino What's the status of this issue? What work is there left to do?

**Comment by jmagman** [comment]
Recipe moved to https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/ios-usb-dependencies.py#58.  

> What's the status of this issue?

I don't think any of the work in the description has been done.

> What work is there left to do?

All of it!

**Comment by christopherfujino** [comment]
@zanderso thanks for the reminder, i'm deep in the LUCI config weeds fixing this https://github.com/flutter/flutter/issues/59506, so I'll do this while i'm at it.
