### ISSUE TITLE
Tool GitHub crash template failing: Unable to generate crash report due to secondary error: NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []("package")

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50300]
Reported at https://github.com/flutter/flutter/issues/49843:

```
Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("package")
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by jmagman** [comment]
I'm guessing:
https://github.com/flutter/flutter/blob/e6e14b0dd2257741930252b00f405a4ddc14b80a/packages/flutter_tools/lib/src/flutter_manifest.dart#L164

**Comment by jmagman** [comment]
@DaveShuckerow I know this isn't directly what you were reporting in https://github.com/flutter/flutter/issues/49843, but can you paste in the `platforms` section of your pubspec.yaml?

**Comment by DaveShuckerow** [comment]
@jma

> @DaveShuckerow I know this isn't directly what you were reporting in #49843, but can you paste in the `platforms` section of your pubspec.yaml?

https://github.com/flutter/devtools/blob/master/packages/devtools_app/pubspec.yaml#L140

**Comment by jmagman** [comment]
Thanks, will be fixed by https://github.com/flutter/flutter/pull/50304.
