### ISSUE TITLE
macOS 10.15.3 “gen_snapshot” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by blhtacwa** [flutter/flutter#50317]
## Steps to Reproduce

1.  Open iTerm2 
2. enter command flutter doctor -v
3. dialog pops up saying “gen_snapshot” cannot be opened because the developer cannot be verified. choices are cancel or move to trash
4. choose cancel next another dialog box, “idevice_id” cannot be opened because the developer cannot be verified.

## Logs

```
```

!] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/bruce/development/flutter
    • Framework revision 9f5ff2306b (11 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bruce/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

using command flutter run --verbose 

I get :

[  +18 ms] executing: [/Users/bruce/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/Users/bruce/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[  +11 ms] executing: [/Users/bruce/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/bruce/development/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [/Users/bruce/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +38 ms] "flutter run" took 98ms.

**Comment by jonahwilliams** [comment]
This issue is tracked in https://github.com/flutter/flutter/issues/50066

**Comment by 3ace** [comment]
this happens again in dev channel version 1.16.1.

I've tried downgrading to 1.16.0 and it's working fine

**Comment by cjmcqueen** [comment]
A quick work around for this is to open System Preferences > Security & Privacy and look for a notice on the screen to allow "gen_snapshot" to "run anyway". Then, run `flutter doctor` again
