### ISSUE TITLE
Text field cannot line feed with some input methods

### ISSUE THREAD

**Issue by woodstream** [flutter/flutter#50328]
When using Chinese input methods, the text field cannot line feed，but English input methods can work.

1. use a TextFormFiled widget:
```
TextFormField(
       maxLines: 5,
       keyboardType: TextInputType.multiline,
       textInputAction: TextInputAction.newline
)
```
2. Keyboard use Chinese input methods, press the newline key, it can't work.
3. Keyboard use English input methods, press the newline key, work well.

**Comment by vstyler96** [comment]
I have the same problem, but in spanish, I tried many ways, but I will try to find the problem

**Comment by woodstream** [comment]
> I have the same problem, but in spanish, I tried many ways, but I will try to find the problem

Looking forward to your good news。

**Comment by Dorbmon** [comment]
Add:When your keyboard use local input mehods,it works well on web on mobile phone.

**Comment by justinmc** [comment]
I was able to reproduce this with an Android emulator and a Chinese keyboard.  I'll try to figure out what caused this.

**Comment by justinmc** [comment]
@gspencergoog Your PR https://github.com/flutter/engine/pull/15568 seems to have caused this bug.  If I comment out [this else if](https://github.com/flutter/engine/pull/15568/files#diff-5c59fd4090b7664033f0eb9383d2dd14R209), then the bug disappears.

Do you know what a solution would be that would fix this bug while still allowing the hardware keyboard enter to work?

**Comment by gspencergoog** [comment]
Sorry, I don't know of one. What is different about the other input methods? Are they acting like a single-line field or something? If we can find a difference in the way they present the key codes or the input configuration, then we can probably figure out a solution.

**Comment by Dorbmon** [comment]
@gspencergoog You can install a Chinese keyboard or other language's keyboard to have a try.

**Comment by shingohu** [comment]
> @gspencergoog You can install a Chinese keyboard or other language's keyboard to have a try.

Try the stable Sdk

**Comment by Dorbmon** [comment]
@shingohu Stable sdk works well.
So how can we solve this proble?

**Comment by woodstream** [comment]
@gspencergoog 
If you have time, may you try to solve this problem? Many people such as Chinese、Spanish、koreans etc are waiting for it. Thank you very much.

**Comment by justinmc** [comment]
@gspencergoog I just tagged you for review on https://github.com/flutter/engine/pull/16560.  That seems to fix the issue here, but can you let me know how I can make sure that your hardware keyboard stuff still works?

**Comment by Dorbmon** [comment]
@justinmc When will this pull request be merged into master?

**Comment by justinmc** [comment]
I'm currently struggling with some test failures, but I hope to merge it into master this week if I can figure that out 👍
