### ISSUE TITLE
BLoC arch error

### ISSUE THREAD

**Issue by vashisth00** [flutter/flutter#50326]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
![Screenshot from 2020-02-07 10-57-36](https://user-images.githubusercontent.com/29851545/74003416-8e54cc00-4998-11ea-9b0c-500b56018538.png)

**Comment by iapicca** [comment]
Hi @vashisth00 
from your screenshot seems like you are experiencing an issue
with the 3rd party plugin [bloc](https://pub.dev/packages/bloc)
you may want to open an issue in the dedicated [github](https://github.com/felangel/bloc/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
