### ISSUE TITLE
Flutter Released APK Crashw while open  Android Activity 

### ISSUE THREAD

**Issue by niravrmc28** [flutter/flutter#50323]
In my app I am opening android activity through channel. It It was working fine in release mode and in debug mode. after updating flutter and dark in release mode when I press button, app is crashing and showing log as below.

![Screenshot_2020-02-07-13-38-59-029_com miui bugreport](https://user-images.githubusercontent.com/47964454/74013219-f663dc00-49b1-11ea-8a10-8ef9352f6b1e.jpg)

**Flutter Doctor Log:**

[✓] Flutter (Channel master, v1.14.7-pre.98, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.14.7-pre.98 at /Users/rmc/AndroidStudioProjects/flutter
    • Framework revision 0c5ae7d656 (3 days ago), 2020-02-03 20:43:02 -0800
    • Engine revision 810b9b91e2
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 c8ed304e97)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rmc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/rmc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Users/rmc/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

**Comment by VladyslavBondarenko** [comment]
Hi @niravrmc28 
What flutter version did you have before update?

**Comment by niravrmc28** [comment]
> Hi @niravrmc28
> What flutter version did you have before update?

Channel master, v1.13

**Comment by chinmaygarde** [comment]
Unfortunately, there isn't much to go off of here. We'd need a reduced test case, crash logs, etc..
