### ISSUE TITLE
realm with flutter not working anyone please help me with demo code 

### ISSUE THREAD

**Issue by manishydv** [flutter/flutter#50331]
Hi,
I new on flutter.try authentication user application show as below attachment.
and I stack with realm DB implementation with flutter (no document for flutter+realm).

I used this link - "https://github.com/mogol/flutter_realm "for reference to connect the realm DB.

if some give short "DEMO CODE" user registration data save on realm data.

I'm trying to resolve this from the last 5 days.
![icon](https://user-images.githubusercontent.com/51132893/74025272-9711c600-49c9-11ea-8425-a55229d1dafb.png)

thank in advance

**Comment by iapicca** [comment]
HI @manishydv 
I quite sure realm doesn't support dart [[realm issue](https://github.com/realm/realm-object-server/issues/55)], if you are experiencing issues w/ the 3rd party plugin [flutter_realm](https://pub.dev/packages/flutter_realm) you may want to open an issue in the dedicated [github](https://github.com/mogol/flutter_realm/issues);

if you get stack Flutter certainly doesn't lack of noSQL db [[hive](https://pub.dev/packages/hive), [sembast](https://pub.dev/packages/sembast) etc...]

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
