### ISSUE TITLE
hot_mode_dev_cycle_macos_target__benchmark_hotReloadMillisecondsToFrameAfterChange & related benchmark regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50339]
Difficult to tell exactly where.

![benchmarks](https://user-images.githubusercontent.com/1435716/74044168-7c1a6400-497f-11ea-9b69-6d6acc6f3e1e.png)

![benchmarks-2](https://user-images.githubusercontent.com/1435716/74044287-b126b680-497f-11ea-937c-fe91baaa89d5.png)

**Comment by cbracken** [comment]
It looks like this may have started somewhere around https://github.com/flutter/flutter/commit/58811028a4896222ff85acec842d664f878fefe9

It's a pretty small bump, but enough to push us over the line more often than not.

/cc @jonahwilliams for thoughts.

**Comment by flar** [comment]
Yes, most of the benchmarks show a slight bump around that time frame. One, though, shows a big bump to red around the same time and then a big jump back to green around 2/3.

**Comment by jonahwilliams** [comment]
Some of these benchmarks are unfortunately bimodial - but there is definitely a jump here. I don't think we should revert the feature, since it is a fairly common complain about Flutter. I'll look at whether I can mitigate the performance impact locally. Otherwise we can make a call on Monday to either revert or rebaseline

**Comment by cbracken** [comment]
I tend to agree. If you haven't found a means to mitigate the hit for this, let's discuss before EOD today. I tend to agree that the benefit outweighs the cost here.

**Comment by jonahwilliams** [comment]
I landed what should be a small mitigation, I'll check the benchmarks in a bit after they run. I will say that if we've only regressed macOS I don't think it is as big a deal since the hot reload times there are already quite fast.

**Comment by jonahwilliams** [comment]
We could also revet just to verify the commit

**Comment by jonahwilliams** [comment]
Looks like there was a separate regression around the same time which is making it difficult to diagnose anything, potentially caused by https://github.com/flutter/flutter/commit/902064277265daced4a79bcdaae157a310cc13c8?

**Comment by cbracken** [comment]
@jonahwilliams can you link to the mitigation patch here for reference?

**Comment by jonahwilliams** [comment]
Its here: https://github.com/flutter/flutter/pull/50394

I didn't dig more into it since the benchmarks went haywire due to a system dialog. Lets chat about it tomorrow

**Comment by jonahwilliams** [comment]
I'm going to rebaseline the macOS benchmarks. These are already quite fast, the regression in question  ~10 ms

**Comment by jonahwilliams** [comment]
Spoke offlne with @cbracken about the benchmark numbers. Due to the small size + noise + useful feature, we decided to rebaseline
