### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AnandaRauf** [flutter/flutter#50342]
I found a bug when building apk android.

**Comment by TahaTesser** [comment]
Hi @AnandaRauf 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by VladyslavBondarenko** [comment]
@AnandaRauf 
I hope you've solved the issue.
Closing as additional information isn't provided.
