### ISSUE TITLE
Create ListTileThemeData for material theme

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#50351]
Add the properties `leadingGap` and `trailingGap` to control these critical properties which are not implemented on the base widget. (`leadingGap` is currently the most critical). 

Also add `contentPadding` to the new theme data which is already implemented.

<img width="414" alt="Screen Shot 2020-02-07 at 1 14 50 PM" src="https://user-images.githubusercontent.com/666539/74054445-14c6d900-49ac-11ea-8c06-9b21c244ec70.png">

**Comment by HansMuller** [comment]
Why not just create an app-specific list item widget that does the right thing?

**Comment by lukepighetti** [comment]
Because the current implementation of ListTile is so close to making stakeholders happy and it will improve options for all Flutter users.

**Comment by Piinks** [comment]
(Triage) It looks like since this issue was filed we added a lot of properties to ListTile and ListTileThemeData, has contentPadding resolved this issue?
