### ISSUE TITLE
incorrect mentions intl example link and unimplemented r 'z' nor 'v' patterns in intl

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#50359]
1. Link broken
https://api.flutter.dev/flutter/intl/intl-library.html
> There is also a simple example application that can be found in the example/basic directory.

2. False information
https://api.flutter.dev/flutter/intl/DateFormat-class.html
The DateFormat  class does not support neither 'z' nor 'v' patterns
https://github.com/dart-lang/intl/issues/74

**Comment by VladyslavBondarenko** [comment]
about 2:
documentation in intl source code is edited with https://github.com/dart-lang/intl/issues/264

**Comment by duzenko** [comment]
> 
> 
> about 2:
> documentation in intl source code is edited with [dart-lang/intl#264](https://github.com/dart-lang/intl/issues/264)

I'm pretty sure that the web page at `https://api.flutter.dev/flutter/intl/DateFormat-class.html` is a Flutter domain, not `intl`'s

**Comment by jamesderlin** [comment]
> > about 2:
> > documentation in intl source code is edited with [dart-lang/intl#264](https://github.com/dart-lang/intl/issues/264)
> 
> I'm pretty sure that the web page at `https://api.flutter.dev/flutter/intl/DateFormat-class.html` is a Flutter domain, not `intl`'s

The documentation on the Flutter website for `intl` is inherited from `package:intl`.  The Flutter documentation will be updated automatically when it pulls in the new version of `package:intl`.

**Comment by jamesderlin** [comment]
https://api.flutter.dev/flutter/intl/intl-library.html seems to be working now, so I don't think there's any point to keeping this issue open, other than to consume a newer version of `package:intl`. (Unfortunately, the documentation fix hasn't been published to `pub.dev` yet, but everything will work itself out naturally when `package:intl` and Flutter are updated for NNBD.)

**Comment by duzenko** [comment]
> 
> 
> https://api.flutter.dev/flutter/intl/intl-library.html seems to be working now, so I don't think there's any point to keeping this issue open, other than to consume a newer version of `package:intl`. (Unfortunately, the documentation fix hasn't been published to `pub.dev` yet, but everything will work itself out naturally when `package:intl` and Flutter are updated for NNBD.)

Both original points still valid
The link is still broken
The info in docs still false
I'm very unhappy with @flutter blindly closing tickets without fixing anything

**Comment by jamesderlin** [comment]
My apologies, I misunderstood your first comment.  Your first point is *not* that https://api.flutter.dev/flutter/intl/intl-library.html doesn't work, it's that it refers to an `example/basic` directory that doesn't exist.  As noted, the `intl` documentation on the Flutter website [is completely inherited from `package:intl`](https://api.flutter.dev/flutter/intl/intl-library.html). (However, `example/basic` does not exist in `package:intl` either. That's https://github.com/dart-lang/intl/issues/212, which also was mistakenly closed.  I will try to get that reopened and fixed.)

As previously mentioned, your second point is already covered by https://github.com/dart-lang/intl/issues/264.  It's expected that that fix is not visible in the generated API docs yet.  It will become visible when `package:intl` publishes a new version for NNBD and when Flutter consumes the new version.

There is not really any Flutter-specific fix to be done here, unless you'd like to reopen and repurpose this issue to be about consuming a newer version of `package:intl`.

**Comment by duzenko** [comment]
@jamesderlin 
>> There is not really any Flutter-specific fix to be done here
You can delete the false content from flutter.dev and link to the intl site instead.
There are other obvious solutions too, but they require a little skill and will, which I'm afraid I can't expect applied to this issue.

**Comment by jamesderlin** [comment]
> You can delete the false content from flutter.dev and link to the intl site instead.

That's a fair request.  Feel free to reopen this to be about that (or to file a new issue).

> I do wonder though, how much time you guys have spent writing all these comments finger pointing to intl and how much time it would have actually taken to just edit the web page in question.

The API docs are generated from source code.  [I personally fixed your second point in the `package:intl` source](https://github.com/dart-lang/intl/commit/fdfc6bf5887b3163ca6f0687a765ed13bf0c7b13).  That the fix has not been published yet is a policy decision to reduce version churn, particularly since there have been breaking changes to `package:intl`'s `master` branch and since there are expected to be additional breaking changes expected in the near future for NNBD.

I already am in the middle of fixing `package:intl` to remove the non-existent references to the example.

**Comment by duzenko** [comment]
> That's a fair request. Feel free to reopen this to be about that (or to file a new issue).

Sadly you don't allow users to reopen tickets

**Comment by goderbauer** [comment]
If this issue still exist, it needs to be fixed in the intl repository: https://github.com/dart-lang/intl. Please file issues over there.
