### ISSUE TITLE
Add unused imports linter to engine presubmit

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#50353]
These are frequently caught by internal infra during rolls. We should run an unused imports linter in the engine as part of android presubmit.

**Comment by mklim** [comment]
I think I'm going to close this as a dupe of flutter/flutter#19031.

**Comment by mklim** [comment]
Actually my mistake, this is really a duplicate of #42534. Just using `google-java-format` would remove unused imports. I think the linter issue I mentioned earlier should be closed.
