### ISSUE TITLE
Re-enable ShellTest.WaitForFirstFrameTimeout on Fuchsia

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#50360]
This was disabled due to flakes.

**Comment by goderbauer** [comment]
(triage) @gw280 Can you please assign this bug to somebody who is working on it or remove it from the march milestone. All bugs in milestones with a month should be assigned to people actively working on it.

**Comment by gw280** [comment]
Oh, I already fixed this :)

**Comment by gw280** [comment]
This was fixed in https://github.com/flutter/engine/pull/16718
