### ISSUE TITLE
flutter build ios-framework --cocoapods crashes: "NoSuchMethodError: The method 'getLicenseFile' was called on null.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50364]
https://github.com/flutter/flutter/issues/50205#issuecomment-583519983

> I try to run with flutter version: v1.14.6 in channel beta but I receive this error:
> 
> ```
> [✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G2022, locale en-BR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.41.1)
> [✓] Connected device (1 available)
> ```
> 
> ```
> flutter build ios-framework --cocoapods
> ```
> 
> ```
> Building frameworks for com.example.app in debug mode...
>  ├─Creating Flutter.podspec...                                       2ms
> 
> Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'getLicenseFile' was called on null.
> Receiver: null
> Tried calling: getLicenseFile()".
> ```

**Comment by xinghunMeng** [comment]
+1

**Comment by jmagman** [comment]
@xinghunMeng This was fixed with in 1.15.3.  You can try it on the [dev channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#dev).

**Comment by xinghunMeng** [comment]
Dev was successful, but the results were inconsistent with the official documentation.
this locality
![image](https://user-images.githubusercontent.com/12692214/75652481-1f684b80-5c96-11ea-8df7-3ec0ae92c6c6.png)
official documentation，There is no FlutterPluginRegistrant.framework
![image](https://user-images.githubusercontent.com/12692214/75652456-0f506c00-5c96-11ea-8ad4-ffdb417c2d46.png)

**Comment by jmagman** [comment]
@xinghunMeng You don't have any plugins so you don't have and don't need a FlutterPluginRegistrant.framework.  I will update the docs to make this more obvious.

**Comment by xinghunMeng** [comment]
@jmagman 👍
