### ISSUE TITLE
Upgrade mac-10 to Xcode 11 or higher

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50378]
Minimum version of Xcode was [bumped to 11](https://github.com/flutter/flutter/pull/50371).  mac-10 is currently disabled and is running Xcode 10.2 to accommodate various perf tests.  [Those gauge tests are now off.](https://github.com/flutter/flutter/pull/50367).

**Comment by jmagman** [comment]
\cc @godofredoc

**Comment by godofredoc** [comment]
This is already done. All the devicelab machines are now running xcode 12.3
