### ISSUE TITLE
When virtual keyboard is dismissed, app doesn't reclaim empty space (on mobile browsers)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#50382]
## Steps to Reproduce

1. Run `flutter create viewport_bug`.
2. Update `lib/main.dart` file with the following code:
<details>
    <summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  void _onCreateReviewPressed(BuildContext context) {
    showDialog<dynamic>(
      context: context,
      builder: (_) => AlertDialog(
        title: Text('3. Finally, click to blur here'),
        content: TextField(
          decoration:
              InputDecoration.collapsed(hintText: '2. Click to focus'),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _onCreateReviewPressed(context),
      ),
      body: Text('1. Click the FAB ⤵'),
    );
  }
}
```

</details>

3. Run the **web app** in a way that you can visit with a mobile browser like Android Chrome or Safari on iOS.
4. Follow the instructions on the app:

**Click the FAB**, this renders a Dialog:

| iOS  Safari    | Android Chrome |
| ----------- | ----------- |
| ![Dialog on iOS](https://user-images.githubusercontent.com/1255594/74074974-6039b100-49c5-11ea-9763-4310c15c0081.png)  | ![Dialog on Android](https://user-images.githubusercontent.com/1255594/74074981-6af44600-49c5-11ea-9681-3537b2082a0a.png) |

**Focus the TextField**, so virtual keyboard shows up

| iOS  Safari    | Android Chrome |
| ----------- | ----------- |
| ![Screen Shot 2020-02-07 at 3 19 51 PM](https://user-images.githubusercontent.com/1255594/74075022-9f680200-49c5-11ea-9c4f-1f692de67f21.png))  | ![Screen Shot 2020-02-07 at 3 18 08 PM](https://user-images.githubusercontent.com/1255594/74075030-a68f1000-49c5-11ea-892c-adc4a8a49cf4.png) |

**Blur the TextField**, by clicking anywhere outside, so virtual keyboard goes away

## Expected results: 

When the Input is blurred, I'd expect the App to recover the whole height of the screen, the FAB to return to the bottom right corner, etc...

| iOS  Safari    | Android Chrome |
| ----------- | ----------- |
| ![Expected on iOS](https://user-images.githubusercontent.com/1255594/74074833-cd007b80-49c4-11ea-89ab-ff2d310266c7.png)  | ![Screen Shot 2020-02-07 at 3 17 46 PM](https://user-images.githubusercontent.com/1255594/74074863-e5709600-49c4-11ea-8102-5c4b4a578a43.png) |

## Actual results:

The app doesn't reclaim the space that was taken by the keyboard when it opened, and it won't fill the screen anymore. Rotating the screen doesn't help.

| iOS  Safari    | Android Chrome |
| ----------- | ----------- |
| ![Expected on iOS](https://user-images.githubusercontent.com/1255594/74074676-08e71100-49c4-11ea-9b0a-71b1b80b3e1d.png)  | ![Screen Shot 2020-02-07 at 3 17 46 PM](https://user-images.githubusercontent.com/1255594/74074688-14d2d300-49c4-11ea-8923-400b74d38011.png) |

<details>
  <summary>Logs</summary>

```
(No errors in Console)
```

```
dit@dit:~/github/viewport_bug$ flutter analyze
Analyzing viewport_bug...                                               
No issues found! (ran in 2.5s)

```

```
dit@dit:~/github/viewport_bug$ flutter doctor -v
[✓] Flutter (Channel master, v1.12.16-pre.790, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.16-pre.790 at /usr/local/google/home/dit/github/flutter
    • Framework revision 082ae838bd (53 minutes ago), 2020-02-07 15:28:45 -0800
    • Engine revision 580503c359
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /usr/local/google/home/dit/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.87
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by nturgut** [comment]
I will have a look at it soon. I am not adding it to the text-editing project cause it looks like issue happens with every viewport change (keyboard or no keyboard).

Thanks for all the details! :)

**Comment by ditman** [comment]
Yep, you're right. Rotation also affects this same app.

**Comment by hemanthrajv** [comment]
The same happens when  resizing windows on chrome console. 

Did some debugging and found out that, the callbacks `didChangeDependecies`. and `didChangeMetrics` are being called properly. But provides old `MediaQuery` rather the latest.

Try:

```dart
void _print(){
  print(MediaQuery.of(context));
}

@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _print();
    Future.delayed(Duration(seconds: 1), _print);
  }
```

The first call gives old value and the delayed one latest.

**Comment by nturgut** [comment]
@hemanthrajv thanks for providing details. Yes, we are expecting this one to effect any type of change which will trigger [viewport resize](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport/resize_event). Keyboard, inspection tools, rotation for a mobile device.

**Comment by alextekartik** [comment]
Is there any known workaround? I'm unfocusing a text numeric field and getting this issue on Android (blank space). I tried a 1s delay and call setState without success. Any suggestion?

**Comment by yolofy** [comment]
I'm having this problem when using an FAB on a scaffold and changing the device orientation. When the FAB is not present, orientation changes work fine.

**Comment by yolofy** [comment]
I found this piece of code, it's webkit only but I guess the blink engine has the same issues.
https://github.com/flutter/flutter_web/blob/c04fb502b842859de07e36954a9390465a5426c0/packages/flutter_web_ui/lib/src/engine/dom_renderer.dart#L397

This is why I copied the concept to my own code as a workaround until this is fixed in the framework.

```
class MapPageState extends State<MapPage> with WidgetsBindingObserver{
  ...
   @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  num widthHtml = 0.0;
  num heightHtml = 0.0;
  num widthUi = 0.0;
  num heightUi = 0.0;

  @override void didChangeMetrics() {
    widthHtml = html.window.outerWidth;
    heightHtml = html.window.outerHeight;
    widthUi = ui.window.physicalSize.width;
    heightUi = ui.window.physicalSize.height;
    ensureTimerStarted();
  }

  Timer checkTimer;

  void ensureTimerStarted() {
    if (checkTimer != null && checkTimer.isActive)
      return;

    checkTimer = Timer.periodic(Duration(milliseconds: 1), (timer) {
      bool isWrongSize = (widthUi - widthHtml).abs() > 2 || (heightUi - heightHtml).abs() > 2;
      if (isWrongSize)
        ui.window.onMetricsChanged();

      if (!isWrongSize || timer.tick > 1000)
        timer.cancel();
    });
  }
  ...
}
```

**Comment by ferhatb** [comment]
@ditman : Fixed an issue around reporting old metrics, please retry :)

**Comment by ditman** [comment]
I'll rebuild my app and retry ASAP. Thanks @ferhatb!

**Comment by ditman** [comment]
@ferhatb this is much better than before, but there are still cases where the metrics are stale. You can reproduce the issue easily (even in desktop browsers) by the window rapidly. Some times, the last resize will not happen (and there will be some white space where there should be app).

In mobile this may happen when rotating the screen. Some times it'll leave an empty space when going from landscape to portrait.

I'll cut another ticket for the window resizing issue ASAP.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by ditman** [comment]
@pedromassangocode sure, sounds good to me!

**Comment by pedromassangocode** [comment]
Thanks for confirming.
