### ISSUE TITLE
Write test to verify Flutter.framework and built with the minimum allowed version of clang

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50387]
Detect issues related to the LUCI builder upgrading Xcode (and therefore clang) beyond the minimum version allowed by the tool.

Flutter.framework must be built with a version equal to or less than the version used by developers.
See example at https://github.com/flutter/flutter/issues/49787.

Check Flutter.framework/Info.plist ClangVersion parses to be equal to the one shipped with the minimum Xcode version.

**Comment by xster** [comment]
Where would you put this test? In the engine post submit LUCI tests?

**Comment by jmagman** [comment]
I was thinking a Cirrus integration test in flutter/flutter that checks the Info.plist version of the downloaded artifacts against the tool's minimum version.  The test should stay in lockstep with  `kXcodeRequiredVersionMajor`/`kXcodeRequiredVersionMinor`.

**Comment by xster** [comment]
Oh the constants already exist in the framework? Breaking during the engine roll sounds ok then. I don't expect it to happen often.

**Comment by jmagman** [comment]
Decided to write the test in the engine.

**Comment by jmagman** [comment]
No longer needed not that bitcode has been removed https://github.com/flutter/flutter/issues/107887
Closing.
