### ISSUE TITLE
Change capability to mac/iphonexs for tiles_scroll_perf_iphonexs__timeline_summary

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#50383]
Currently devicelab is using iphone6, and capability has been updated to `mac/ios` for test `tiles_scroll_perf_iphonexs__timeline_summary`.

We need to change the capability to `mac/iphonexs` when available.

**Comment by digiter** [comment]
Does this one actually require iphonexs? @liyuqian

**Comment by liyuqian** [comment]
There's no compatibility requirement for iPhone Xs but we'd like to have some consistent performance metrics for iPhone Xs, since we had some iPhone Xs performance issues before.

**Comment by godofredoc** [comment]
This test has been running on 6s for several months. Ideally we would like to remove as much as possible the one off test beds to simplify scaling and maintenance.

**Comment by liyuqian** [comment]
If that's the case, maybe we should just remove the iphonexs task as tiles_scroll__perf_ios is already covering the same test on iPhone 6s. Our original intention was to broaden our test coverage on more types of devices. We can revisit that goal when our device lab is more scalable with multiple types of devices. For now, maybe removing the test is the best option to not block the infra team on scaling up more number of devices.
