### ISSUE TITLE
sdk version

### ISSUE THREAD

**Issue by srudra623** [flutter/flutter#50408]
[flutterlogin-master] flutter packages get
Running "flutter pub get" in flutterlogin-master...             
The current Dart SDK version is 2.7.0.

Because flutteruiapp depends on font_awesome_flutter >=4.7.1 <8.0.0 which requires SDK version <2.0.0, version solving failed.
pub get failed (1; Because flutteruiapp depends on font_awesome_flutter >=4.7.1 <8.0.0 which requires SDK version <2.0.0, version solving failed.)
exit code 1

**Comment by VladyslavBondarenko** [comment]
Hi @srudra623 
This the log tells you that with your current Dart SDK version you need to use `font_awesome_flutter` >=4.7.1 <8.0.0. 
For higher version of `font_awesome_flutter` you need a higher version of Dart SDK, which you can have when you update your Flutter SDK
Closing, as this is an issue of versions, not an issue with Flutter itself
if you disagree please write in the comments and I will reopen it
Thank you
