### ISSUE TITLE
Change the type of the ScrollableState.fling() scrollVeclocity parameter to Velocity

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#5040]
Velocity parameters with implicit units can lead to confusion and mistakes.

In ScrollableState's calls to fling(): instead of eagerly converting Velocity to a scalar we could add a Velocity.along(Axis) method and pass a Velocity to ScrollableState.fling().

In places that don't have an Axis, like the ScrollSimulation class, or AnimationController.fling(), ScrollBehavior.createSnapScrollSimulation(), ScrollBehavior.createScrollSimulation(), we could use a new scalar velocity class 'Speed' that had explicit units.

See https://github.com/flutter/flutter/pull/5038#discussion_r72169536

**Comment by abarth** [comment]
There's no fling anymore.
