### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by AnandaRauf** [flutter/flutter#50404]
Hi, i'm Ananda Rauf from Indonesia, can i requesting new feature be like Xamarin, drag and drop button,text, and other form.

Thanks.

Regards me.

**Comment by VladyslavBondarenko** [comment]
Hi @AnandaRauf 
https://api.flutter.dev/flutter/widgets/Draggable-class.html
Isn't it what you are looking for?
You can find tutorials with using Draggable for example on Medium
If no, please create a new issue and specify precisely what functional you are requesting, and try to investigate isn't it already implemented
Thank you
