### ISSUE TITLE
Flutter tool / Dart crash in AsmIntrinsifier::Type_equality(????)

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#50416]
## Steps to Reproduce

**OS: MacOS Catalina 10.15.3 (19D76)**

<img width="889" alt="Bildschirmfoto 2020-02-08 um 18 14 27" src="https://user-images.githubusercontent.com/18512224/74089414-48375f80-4aa1-11ea-81ed-8d30280db57d.png">

<img width="888" alt="Bildschirmfoto 2020-02-08 um 18 22 19" src="https://user-images.githubusercontent.com/18512224/74089419-51c0c780-4aa1-11ea-996f-b0d4d599552a.png">

**Expected results:**
I can use ```flutter``` commands without crash

**Actual results:**
On every ```flutter ...``` call it's broken everywhere (tested: Term, iTerm2, VSCode)

LOGS NOT POSSIBLE

Edit: Of course I also switched into my flutter bin folder and tried to execute flutter, but same results.

Info: I didn't changed anything! Last night I could use flutter as always!

**Comment by Ahmadre** [comment]
Ok, it's solved after I restarted my Mac...sorry for that 🙈

**Comment by jonahwilliams** [comment]
I don't think we should close this issue, it looks like a real crash in dart.

**Comment by jonahwilliams** [comment]
@Ahmadre did you save the logs? Your screenshot is hard to read and a bit cut-off

**Comment by Ahmadre** [comment]
@jonahwilliams sadly not. I didn't saved the logs. But I try to reproduce the bug. It happen after my Mac went to screensaver mode for about 30 min. After I unlocked my mac with my VSCode opened, that happened. 

I will post the logs when I was able to.

Best regards :)

**Comment by jonahwilliams** [comment]
I'm going to mark this as "waiting for customer response" so that it gets closed if we can't get any more information on it. I'll bring it up with Dart folks on Monday separately

**Comment by Ahmadre** [comment]
@jonahwilliams Update: I tried to reproduce it, but I wasn't able to do so. I don't know why actually that happen...
