### ISSUE TITLE
Gallery, Pesto: missing frames when shrinking a recipe

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5042]
On my Nexus 5X, built with profile mode, it looks like we're missing frames when the user taps the back icon after viewing a recipe.

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17149362/d1199c5a-531f-11e6-8796-7363d9a2bdd5.png)

Then, here's the performance overlay when the transition is complete:

![screen shot 2016-07-26 at 11 01 13 am](https://cloud.githubusercontent.com/assets/5479/17149478/50fd2bd0-5320-11e6-8baf-6d91ff16a818.png)

Here's a trace:

![screen shot 2016-07-26 at 10 59 55 am](https://cloud.githubusercontent.com/assets/5479/17149430/1747e25e-5320-11e6-8e27-f157b15735db.png)

File:

[pesto-recipe-back.json.zip](https://github.com/flutter/flutter/files/384450/pesto-recipe-back.json.zip)

**Comment by abarth** [comment]
```
diff --git a/src/gpu/gl/builders/GrGLProgramBuilder.cpp b/src/gpu/gl/builders/GrGLProgramBuilder.cpp
index c6422ca..b7be309 100644
--- a/src/gpu/gl/builders/GrGLProgramBuilder.cpp
+++ b/src/gpu/gl/builders/GrGLProgramBuilder.cpp
@@ -95,6 +95,8 @@ bool GrGLProgramBuilder::compileAndAttachShaders(GrGLSLShaderBuilder& shader,
 }
 
 GrGLProgram* GrGLProgramBuilder::finalize() {
+    TRACE_EVENT0("skia", "GrGLProgramBuilder::finalize");
+
     // verify we can get a program id
     GrGLuint programID;
     GL_CALL_RET(programID, CreateProgram());
```

**Comment by chinmaygarde** [comment]
![screen shot 2016-08-02 at 2 46 30 pm](https://cloud.githubusercontent.com/assets/44085/17346524/ed99409c-58bf-11e6-9025-1a9377dd53c7.png)

@abarth: I am not seeing the same massive spikes in SkCanvas::flush. For the most part, they seem to be in line with the size of the SkPicture being drawn.

**Comment by abarth** [comment]
Maybe it's something specific to my device.

**Comment by chinmaygarde** [comment]
> Maybe it's something specific to my device.

Perhaps. It is also a lot better on iOS but we still lose some frames. I am now investigating if its the opacity layer causing the creation of an offscreen rendertarget and the extra work needed to be done by the switches causing us to lose frames.

**Comment by abarth** [comment]
We might want to reorganize how //flow draws layers to draw the off-screen targets ahead of time instead of switching back and forth.  Skia used to have a layer hoister that did this for us, but they appear to have removed it recently.

**Comment by sethladd** [comment]
Tested on a Nexus 5. Notice the Down seems to be missing a lot of frames.

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17818775/d39734d2-65f9-11e6-8b47-13c5df647a16.png)

**Comment by sethladd** [comment]
We've hidden Pesto.
