### ISSUE TITLE
Material clipBehavior on Image.network with borderRadius.circular is inconsistent

### ISSUE THREAD

**Issue by mrerhuo** [flutter/flutter#50427]
![image](https://user-images.githubusercontent.com/9547741/74096768-11fbed80-4b3e-11ea-892b-cd7fb578546c.png)

**Comment by TahaTesser** [comment]
Hi @mrerhuo 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
 Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by iapicca** [comment]
HI @mrerhuo  (sorry for overlapping @TahaTesser )
it works on web ([code](https://dartpad.dev/5a98bbc6911cdca1377308f27f8bbb52)), but on my device looks like[this](https://user-images.githubusercontent.com/45637986/74148260-b6993080-4c0d-11ea-8bf9-d4a8d0a0e70e.png)
thank you for reporting it

**Comment by HansMuller** [comment]
Set the Material's clipBehavior https://api.flutter.dev/flutter/material/Material/clipBehavior.html ?

**Comment by TahaTesser** [comment]
Hi @mrerhuo 
Try this 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: HomePage(),
      );
}

class HomePage extends StatelessWidget {
  static const String _imageUrl =
      'https://flutter.dev/assets/homepage/carousel/slide_2-bg-ec22a39fb182cb26ec8fb88b30064bc08707d4e87b0e7415c2f077c20d3e6102.jpg';

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Material(
              elevation: 10.0,
              borderRadius: BorderRadius.circular(20.0),
              clipBehavior: Clip.antiAlias,
              child: Image.network(_imageUrl),
            ),
          ),
        ),
      );
}
```
![flutter_01](https://user-images.githubusercontent.com/48603081/74445119-e2314a80-4e9b-11ea-9f17-0a7d0beea06f.png)

**Comment by mrerhuo** [comment]
@TahaTesser thinks you!

**Comment by mrerhuo** [comment]
but i think web and ios android code and view show mast be identical！！
