### ISSUE TITLE
AlarmManager still can't access other plugins on Flutter >= 1.12

### ISSUE THREAD

**Issue by Kaktusbaum** [flutter/flutter#50421]
## Steps to Reproduce

1. Use AlarmManager with another Plugin on Flutter >= 1.12

**Expected results:** 

According to the [plugin page of the AlarmManager](https://pub.dev/packages/android_alarm_manager), you can use the plugin without calling `AlarmService.setPluginRegistrant` on Flutter >= 1.12. I am using Flutter 1.14.6 and the AlarmManager still can't access other plugins.

**Actual results:** 

The AlarmManager works, but I get this error, when the AlarmManager tries to access another plugin:
`020-02-09 01:02:50.993 2592-2618/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method vibrate on channel vibration)`

<details>
  <summary>Logs</summary>

Here is my MainActivity.kt. I am also using the [Google Wear OS Plugin for Flutter](https://pub.dev/packages/wear). The `AmbientMode.attachAmbientSupport(this)`requires the `GeneratedPluginRegistrant.registerWith(this)`. 

**MainActivity.kt**
```
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant
import androidx.wear.ambient.AmbientMode

import com.mjohnsullivan.flutterwear.wear.FlutterAmbientCallback
import com.mjohnsullivan.flutterwear.wear.getChannel

class MainActivity : FlutterActivity(), AmbientMode.AmbientCallbackProvider {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
        // Wire up the activity for ambient callbacks
        AmbientMode.attachAmbientSupport(this)
    }

    override fun getAmbientCallback(): AmbientMode.AmbientCallback {
        return FlutterAmbientCallback(getChannel(flutterView))
    }
}
```

**flutter doctor --verbose**
```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G2022, locale en-DE)
    • Flutter version 1.14.6 at /Users/xxxxxx/development/tools/flutter
    • Framework revision fabeb2a16f (11 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxxxxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Fossil Sport • 192.168.2.108:5555 • android-arm • Android 9 (API 28)

• No issues found!
Process finished with exit code 0
```

</details>

**Comment by iapicca** [comment]
Hi @Kaktusbaum 
can you confirm that you are followed the upgrade for the [new Android Plugins API ](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration#upgrade-steps)?
if possible could you please provide a reproducible minimal code sample.
Thank you

**Comment by Kaktusbaum** [comment]
Yes, that was the problem. It wasn't clear, that you have to do those steps. 

My MainActivity.kt should look like this

```
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

```
The AlarmManager plugin site says, it's enough to do a flutter upgrade. 
> This can be resolved by running flutter upgrade to upgrade to the latest Flutter version.
But apparently it's not.
