### ISSUE TITLE
Provide platform agnostic method OR official guidance in documentation for securely storing fixed API keys

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#50423]
(I see that #20735 touches on this, but I don't think the solution suggested there really helps.)

I often see packages on https://pub.dev/flutter that provide access to various services, and the READMEs for those packages always hardcode the API keys in their respective tutorial code. I'm sure the tutorials do not mean to indicate that this is good practice, and are meant to be merely instructional. However, I haven't found a good method for abstracting those keys out so that they are not found if an app they are used in is decompiled. Now, the risk level for many of these keys being exposed is probably low, but it still seems like bad practice and I want to avoid it.

So far, I've approached the problem in the following ways:
1. **Store the keys in a gitignored file.** This seems like a perfect solution on the surface, but I realized that when the app is built, that file will get packaged in, and decompilation will reveal those keys.
2. **Firebase Remote Config.** This also seems like a good option, but when dealing with packages that need to wrap the `MaterialApp` or that need to be instantiated before `runApp()`, or that need to be instantiated before the `MaterialApp` is returned, this requires retrieving the remote keys right away, and that can cause null issues for a second or two. (see https://github.com/GroovinChip/SoloSocial/issues/33)

It seems to me that perhaps the way to go is to provide some pre-coded native code and platform channels that get generated with a Flutter project that address this in a general fashion. Perhaps it can be a flag for `flutter create`.

Alternatively, if this issue isn't deemed as so important, perhaps there could be something added to the Flutter cookbook on how to address these issues.

**Comment by GroovinChip** [comment]
I've been told there's no real way to secure API keys. That's really disappointing. Closing.

**Comment by awhitford** [comment]
You may be interested in this topic:  https://stackoverflow.com/questions/60385672/how-to-use-firebase-remote-config-in-appdelegate-swift

I too am seeking _clear guidance_ on what to do for production.  I find it ridiculous that the documentation (like [this](https://pub.dev/packages/google_maps_flutter#ios)) is apparently _"not appropriate for production"_, but nobody can clarify what _is_ appropriate for production.
