### ISSUE TITLE
type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by RitikRD** [flutter/flutter#50439]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by aneeshjose** [comment]
I don't this this is a framework issue.
Could you please elaborate the issue with a sample code snippet or some descriptions?
Or try using `.toString()` method to convert it to `String` type or `int.parse(stringVariable)` to convert `String` to int
