### ISSUE TITLE
How to load list of data from  the json file.

### ISSUE THREAD

**Issue by Ashbuhrz** [flutter/flutter#50434]
my JSON URL =[https://www.mocky.io/v2/5dfccffc310000efc8d2c1ad](url)

       `body: Container(
        child: Center(
          child: FutureBuilder(
            future:
                DefaultAssetBundle.of(context).loadString('assets/data.json'),
            builder: (context, snapshot) {
              if (!snapshot.hasData) {
                return CircularProgressIndicator();
              }
              var myData = json.decode(snapshot.data);
              return ListView.builder(
                itemBuilder: (BuildContext context, int index) {
                  return Card(
                      child: ListTile(
                    title: Text(myData[index]['table_menu_list'][index]
                        ['category_dishes'][index]['dish_name']),
                  ));
                },
                itemCount: myData == null ? 0 : myData.length,
              );
            },
          ),
        ),
      ),`

I have to get the text of all dish name from the JSON file as a listtile

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
