### ISSUE TITLE
Flutter for Web - Wrong localhost address url http://[::1]:8080/#/

### ISSUE THREAD

**Issue by z-dmitri** [flutter/flutter#50435]
## Steps to Reproduce

0. flutter channel beta + flutter upgrade
1. Run any Flutter for Web application

**Expected results:** 
Chrome Web browser URL address is: 
http://localhost:8080/#/

**Actual results:** 
Chrome Web browser URL address is: 
http://[::1]:8080/#/

**Details**
With "[::1]" address instead of "localhost" it is not possible to use return Url's for testing application on localhost

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/49625
