### ISSUE TITLE
I updated the version of the flutter now I'm having problems

### ISSUE THREAD

**Issue by juchannel** [flutter/flutter#50433]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
     Required by:                                                       
         project :app                                                   
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not parse POM http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom
            > O conteúdo não é permitido no prólogo.                    
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not parse POM http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom
            > O conteúdo não é permitido no prólogo.                    
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.
         > Could not parse POM http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom
            > O conteúdo não é permitido no prólogo.                    
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 12s

**Comment by jonahwilliams** [comment]
Are you able to download `http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119/flutter_embedding_debug-1.0.0-a67792536ca236a971d0efbcfd7af4efb8f6c119.pom` yourself? This might be a network connectivity error

**Comment by sunheihei** [comment]
I had the same problem, did you solve it now?

**Comment by Presheda** [comment]
For anyone still stuck, the link below might help

https://github.com/flutter/flutter/issues/39729
