### ISSUE TITLE
[web]: Flutter for web scrolling is very poor

### ISSUE THREAD

**Issue by IRFAN-GujjAR** [flutter/flutter#50443]
I have noticed a very poor scolling performance in flutter web. I hope the flutter team will fix this.

**Comment by TahaTesser** [comment]
Hi @IRFAN-GujjAR 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jodinathan** [comment]
well, you can take a look at the flutter gallery shrine example: https://flutter.github.io/samples/#/

at least for me is very slow for a small image list

**Comment by Piinks** [comment]
Thanks for your contribution. This appears to be a duplicate of #42987. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue.
