### ISSUE TITLE
WEB: External JS Lib Unable to find element created with HtmlElementView

### ISSUE THREAD

**Issue by MateusAmin** [flutter/flutter#50452]
I am embedding an external video which requires an iframe and external JS dependency. This is common practice among content sites. I suppose to allow for their ads and metrics. 

The external lib fails to find the element. It is doing a lookup based on id: document.getElementById(t)

Related issue: https://github.com/flutter/flutter/issues/40080

If I reach out to the maintainers of the lib is there a generic query that will extend the id lookup to the shadow dom?

## Steps to Reproduce

I will come back and do this later. Problem is well understood but I imagine it would convenient to have a test case.

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.15.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.2 at /home/mea/development/flutter
    • Framework revision d94ff4bdbe (3 days ago), 2020-02-06 13:19:46 -0800
    • Engine revision f34bc65bee
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/mea/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.5)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by muhleder** [comment]
@MateusAmin Couldn't you load the external js as a  ScriptElement inside the registerViewFactory callback?

**Comment by jonaird** [comment]
You can get shadow dom roots via `document.getElementsByTagName('flt-platform-view')`
and search a shadow dom with `elem.shadowRoot.querySelector('#id')`

**Comment by MateusAmin** [comment]
@muhleder @jonaird Thank you for the input. Will look into your suggestions and report back.

**Comment by AngusPei** [comment]
same issue 
[ External JS Lib](https://krpano.com/docu/html/?version=1174#syntax)

```javascript
<script src="embedpano.js"></script>
<div id="pano" style="width:600px; height:400px;"></div>
<script>
  embedpano({swf:"krpano.swf", xml:"pano.xml", target:"pano"});
</script>
```
**<div id="pano" id="pano"/>**

**Comment by AngusPei** [comment]
temporary measure
Hot Reload div lose
```dart
// ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory('someViewType', (int viewId) {
    final wrapper = DivElement()
      ..style.width = '100%'
      ..style.height = '100%';

    /// FIX:
    /// https://github.com/flutter/flutter/issues/40080
    /// https://github.com/flutter/flutter/issues/50452
    /// document.getElementsByTagName('flt-platform-view')[0].shadowRoot.getElementById('plotly_div_id_')
    final script = ScriptElement();
    script.appendText(
        'embedpano({swf:"viewer/krpano.swf", xml:"viewer/krpano.xml", target:"pano", html5:"auto", mobilescale:1.0, passQueryParameters:true});');

//    final div = DivElement()
//      ..id = 'pano'

    var div = (querySelector('#pano') as DivElement)
      ..contentEditable = 'true'
      ..style.width = '100%'
      ..style.backgroundColor = 'red'
      ..style.height = '100%';

    div.append(script);
    wrapper.append(div);
    return wrapper;
  });
```

**Comment by phamnhuvu-dev** [comment]
I am also facing this issue when using with Brightcove for flutter web

**Comment by BennyKirschner** [comment]
Hi, I don't want to sound impatient but any ETA on the fix for this issue?

**Comment by ditman** [comment]
I need to land a bugfix for google maps, and triage a couple of iframe-related issues first, but this is something I want to work on next. I'm not assigning a milestone yet because I can't make promises, but I'd like to work on this (and hopefully be done) in December.

**Comment by ditman** [comment]
This is next for me; after taking a look, we might end up migrating all the HtmlElementViews to web component `slots`, so all the views will be accessible to scripts.

This might require rendering the whole flutter scene as a shadowDOM, instead of just the platform views, but any fix will for sure happen after the holiday break!

**Comment by ditman** [comment]
The Design Doc for this change is under active review, here's the latest draft:

* [Using `slot` to embed web Platform Views](https://docs.google.com/document/d/1U6aCSuzQsFpOP8_OseL-fwl2-MC2bxJAsgt2R_-sC30)

Feel free to add comments there!

(Apologies for the URL, I'll publish the google doc to flutter.dev as soon as flutter/website starts accepting PRs again! )

**Comment by creativecreatorormaybenot** [comment]
Thanks for the doc! @ditman 

I added a comment: https://docs.google.com/document/d/1U6aCSuzQsFpOP8_OseL-fwl2-MC2bxJAsgt2R_-sC30/edit?disco=AAAALndU7nQ
Hope that it is helpful :)

**Comment by creativecreatorormaybenot** [comment]
Note that this is **already solved** in CanvasKit 🎉   
Specifically, CanvasKit does not use shadow DOM, which means that this is not an issue in CanvasKit 🚀 

I added some further info / a JW Player example to https://github.com/flutter/flutter/issues/65157#issuecomment-810652729. Do not that I did not include any of the JS bridging etc., but you should be able to figure that out / it is not related to the issues.

---

As far as I understand, [**slots**](https://github.com/flutter/flutter/issues/50452#issuecomment-790176492) will then also solve it for the HTML renderer and the slots implementation would also be consistent between both CanvasKit and HTML, which is nice :)

**Comment by ditman** [comment]
Wow, this issue fell through the cracks!

If you're using flutter web `beta` or newer, custom HtmlElementViews should render with slots regardless of the rendering backend (html or canvaskit).

Also, the injected elements now belong in the normal DOM of the `flt-glass-pane` element, and are not hidden behind a ShadowDOM.

I'm closing this as fixed, please do let me know if you're still having trouble accessing DOM from 3rd party scripts after you get slots rendering!

I'm going to close this as fixed.
