### ISSUE TITLE
Migrate Fuchsia to Embedder API

### ISSUE THREAD

**Issue by arbreng** [flutter/flutter#50450]
This will help fix a great many code-cleanliness and performance issues, and remove all of the Fuchsia-specific code from the codebase

**Comment by kf6gpe** [comment]
Triage update: this work is ongoing.

**Comment by safasofuoglu** [comment]
Does this depend on #47562?

**Comment by arbreng** [comment]
Yes, for production usage it does although we can use software for development

**Comment by kf6gpe** [comment]
This is done as part of the migration to the new embedder & runner.
