### ISSUE TITLE
The OnTap event triggered with slight delay when the onDoubleTap event enabled in gesture detector

### ISSUE THREAD

**Issue by ArunSivaR** [flutter/flutter#50458]
Hi Team,

In flutter gesture detector the onTap event triggers with slight delay when the onDoubleTap event enabled in the gesture detector, and on further analyze we found that the delay to recognize that the double tap event, and flutter has a constant value of 300ms in the kDoubleTapTimeout property, and in our case reducing the timeout will be more efficient, can you please give support to reduce the the timeout duration in gesture detector, or suggest any other way to reduce the delay.

Kindly find the attached sample to reproduce the issue:
1. Run the sample
2. Tap on the tap here text
3. The Text changes as Single Tap completed with a significant delay
4. Now, command the double tap event in sample and restart the sample
5. We didn't feel any delay on that.

[flutter_app_gesture.zip](https://github.com/flutter/flutter/files/4179283/flutter_app_gesture.zip)

Regards,
Arun Siva R

**Comment by TahaTesser** [comment]
Hi @ArunSivaR 
can you please provide your `flutter doctor -v` ?
Thank you

**Comment by ArunSivaR** [comment]
Hi @TahaTesser 

The flutter docter -v details werer following by:
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17763.973], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\src\flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi Note 5 • 289a2c7e0005 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

Regards,
Arun Siva R

**Comment by ManuelRohrauer** [comment]
@ArunSivaR I've written a pub package where you can set the `doubleTapTimeout `via property. The package uses an `InkWell `where the onDoubleTap algorithm is programmed manually. If you don't want the InkWell splash effect, simply insert a Container with a color as parent.

https://pub.dev/packages/inkwell_splash
Feel free you check it, there is also an interactive example where you can alter the `doubleTapTimeout`

**Comment by atereshkov** [comment]
@ManuelRohrauer that's very useful. Thank you!

**Comment by iapicca** [comment]
Hi @ArunSivaR 
I see there's an [issue](https://github.com/flutter/flutter/issues/42817#issuecomment-621917358
) addressing the case you described.

Moreover the described behaviour seems to be intended.

Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
