### ISSUE TITLE
converting Chinese string to bytes and back is inconsistent

### ISSUE THREAD

**Issue by tianhaoz95** [flutter/flutter#50453]
## Steps to Reproduce

1. write a unit test:

```dart
String msg = '中文的也应该可以';
expect(String.fromCharCodes(Uint8List.fromList(msg.codeUnits)), msg);
```

2. run the test with `flutter test`

3. see the error:

```bash
Expected: '中文的也应该可以'
    Actual: '-
              _åïå'
     Which: is different.
            Expected: 中文的也应该可以
              Actual: -
                       _åïå
                      ^
             Differ at offset 0
```

**Expected results:** it should be the same string as before and the test should pass

**Actual results:** it became random char list

**Comment by jonahwilliams** [comment]
Hi @tianhaoz95, what you actually want to use is a Uint16List, not a Uint8List. 

If you look at the documentation for [String.codeUnits](https://api.flutter.dev/flutter/dart-core/String/codeUnits.html), you'll see that it returns a UTF-16 representation. In your snippet the Uint8List will end up truncating the characters incorrectly - though it may work for strings where all the codePoints are small enough

**Comment by jonahwilliams** [comment]
Also: if you want a UTF-8 representation, there is utf8 codec in `dart:convert`. The following should work as expected:

```
String msg = '中文的也应该可以';
expect(String.fromCharCodes(Uint8List.fromList(utf8.encode(msg))), msg);

```

**Comment by VladyslavBondarenko** [comment]
Thanks @jonahwilliams! 
@tianhaoz95 this should solve your problem, closing the issue
if you disagree please write in the comments and I will reopen it
Thank you
