### ISSUE TITLE
Gallery, Pesto: missing frames when hero'ing up a recipe in Pesto

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5045]
On a Nexus 5X, built with --profile. This is a specific issue just for "hero up in Pesto".

Open Gallery, tap Pesto, tap a recipe image:

![screen shot 2016-07-26 at 11 31 23 am](https://cloud.githubusercontent.com/assets/5479/17150498/8d47bfc0-5324-11e6-93db-317708556c76.png)

[pesto-recipe-hero-up.json.zip](https://github.com/flutter/flutter/files/384509/pesto-recipe-hero-up.json.zip)

**Comment by abarth** [comment]
From the trace, it looks like there are two issues:

1. We're rebuilding the world twice at the beginning (instead of once)
2. The first draw picture call is taking a long time.  In other traces, that's been because of image uploading (i.e., #3805)

**Comment by sethladd** [comment]
Testing on a Nexus 5:

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17818760/be16005c-65f9-11e6-8a5e-b558065b3ae7.png)

**Comment by sethladd** [comment]
We've hidden Pesto.

**Comment by ScottPierce** [comment]
@sethladd Why close this though? Isn't the fact that pesto lags, and it's a pretty simple app sample something that points to a performance issue with flutter that needs to be addressed?

**Comment by sethladd** [comment]
Good question. Because I'm pretty sure it's not specific to Pesto and we're rather look at code we are shipping.
