### ISSUE TITLE
Unable to connect to localhost from flutter application to access cloud functions

### ISSUE THREAD

**Issue by mgoral2** [flutter/flutter#50451]
Hi.  I am unable to access my cloud functions served at http://localhost:5000/mtai-63f52/us-central1/api1 from my flutter application.  I have been trying for several days.  When I deploy to firebase and access at https://us-central1-mtai-63f52.cloudfunctions.net/api1/helloworld it works fine.  The get request code I am running is here:

```dart
Future<void> loginPost() async {
                    //var resp = await http.post( url, body: json, headers: headers);
                    var resp = await http.get(url);
                    print("Hi Hello How Are You ${resp.statusCode}");
                    print("Body: ${resp.body}");
                  }
                  loginPost();
```

here is my flutter doctor.  Can someone please help?  I am connecting on a mac over usb but I also have both devices connected to the same wifi.  Thanks!

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G2022,
    locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/mg8686./Downloads/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mg8686./Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G965U • 304e4a5855503098 • android-arm64 • Android 9 (API 28)
```

**Comment by aneeshjose** [comment]
This may be an issue with the emulator configurations you are using. 
Have a look at this thread: https://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator

**Comment by VladyslavBondarenko** [comment]
Thanks @anaisbetts !
@mgoral2 does it work with using `10.0.2.2` instead of `localhost`?

**Comment by mgoral2** [comment]
Hi @VladyslavBondarenko.  It just times out when I do that. Here is what I used:  'http://10.0.2.2:5000/mtai-63f52/us-central1/api1/helloworld'

**Comment by VladyslavBondarenko** [comment]
@mgoral2
I didn't pay attention that you are using the real device. 
Using `10.0.2.2` instead of `localhost` or `127.0.0.1` make sense when you are using emulator.
But It's expected that you can't connect to the `localhost` being not in the same network.

You can share hotspot from your desktop, connect mobile to it and use your IP in this network (most probable `192.168.137.1`) instead of `localhost`. Or find another variant.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by steelx** [comment]
> 
> 
> @mgoral2
> I didn't pay attention that you are using the real device.
> Using `10.0.2.2` instead of `localhost` or `127.0.0.1` make sense when you are using emulator.
> But It's expected that you can't connect to the `localhost` being not in the same network.
> 
> You can share hotspot from your desktop, connect mobile to it and use your IP in this network (most probable `192.168.137.1`) instead of `localhost`. Or find another variant.
> 
> Closing, as this isn't an issue with Flutter itself,
> if you disagree please write in the comments and I will reopen it
> Thank you

its not able to connect to anything
