### ISSUE TITLE
hot_mode_dev_cycle__benchmark_hotReloadMillisecondsToFrameAfterChange shows bimodal regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50474]
Difficult to pin down actual point of regression. (Regession point shows commits not related to hot reload). Two issues with this benchmark:
* It's obviously bimodal.
* It's gone over baseline somewhere around https://github.com/flutter/flutter/pull/49799.

This also affects hot_mode_dev_cycle_macos_target__benchmark_hotReloadMillisecondsToFrameAfterChange and hot_mode_dev_cycle_win__benchmark_hotReloadMillisecondsToFrameAfterChange

**Comment by cbracken** [comment]
We did some investigation and reviewed the ~10 commits on either side of the start of the red. No engine rolls included anything that should affect this (mostly skia commits, a change to the licenses golden file, web changes). Given how small the regression is and that it only affects the first frame after hot-reload in dev mode, I'm rebaselining.
