### ISSUE TITLE
Dark mode on web

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#50471]
Dark mode on web would be really useful.
Querying it using `MediaQuery.of(context).platformBrightness` could use code like this:
```javascript
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    // dark mode
}
```

**Comment by jonahwilliams** [comment]
The web does support dart mode though

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/engine/pull/12335

**Comment by VladyslavBondarenko** [comment]
@jld3103 
Closing the issue
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by jld3103** [comment]
Ah I see. Thanks

**Comment by jld3103** [comment]
It works like expected, but sometimes it doesn't work and the app uses the light theme. I'll try to find a pattern
