### ISSUE TITLE
not full sample - provider_shopper

### ISSUE THREAD

**Issue by Andrysky** [flutter/flutter#50478]
## Use case

not correct samples / not full samples provider_shopper

## Proposal
on 
https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro
https://github.com/flutter/samples/tree/master/provider_shopper
we see gif with "login page"
and with 
![image](https://user-images.githubusercontent.com/5894390/74174109-7012f880-4c44-11ea-8d46-c5791d40b6ac.png)
MyLoginScreen node

but https://github.com/flutter/samples/tree/master/provider_shopper/lib/screens not contain ~MyLoginScreen.dart

**Comment by markusaksli-nc** [comment]
Closing since this was fixed with https://github.com/flutter/samples/pull/339
