### ISSUE TITLE
Run clang-tidy on presubmits for engine

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#50486]
We end up catching these on internal rolls, but it'd be nice to catch them earlier.

I made a quick attempt at this and it requires setting up some pointers to the compile_commands.json as well as possibly feeding it some path info that I seem to be missing locally.

/cc @chinmaygarde @flar

**Comment by gaaclarke** [comment]
Here is what Dart is doing: https://github.com/dart-lang/sdk/blob/master/runtime/tools/run_clang_tidy.dart

It looks like they've just hardcoded in the build flags instead of getting them from ninja.

**Comment by dnfield** [comment]
We're doing this now.
