### ISSUE TITLE
[devicelab] VM agents running out of space

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#50482]
For some tests we are using VMs with 10G of hard disk space. After running tasks for a couple of weeks the VM runs out of space. To prevent this from happening we need to create a recovery step to delete the following folders:

.gradle
.pub_cache
.dartServer

**Comment by gspencergoog** [comment]
You should also probably delete `/home/flutter/.cocoon/flutter/bin/cache` too, and run `apt-get clean` to clean out the apt cache.

Is it also possible to just restart the VM from a clean image every now and then?

**Comment by dnfield** [comment]
Why are we taking up this much space?

Is this impacting users negatively?  I'm particularly suspicious of what's going on in .dartServer during revs of the SDK.  Not sure who the right person to loop in on that from the SDK team though.. maybe @stereotype441 ?

**Comment by gspencergoog** [comment]
The `.dartServer` dir had about 1.5G of stuff in it when I cleaned it up.

**Comment by dnfield** [comment]
My local copy is currently 1.1G.  I end up manually cleaning it up every few days at this point.

**Comment by dnfield** [comment]
It may just be the csae that the VMs need more disk space....  10G isn't a ton of space for an Android SDK, a gradle cache, the Flutter binaries, the dart analysis cache, and pub....

**Comment by dnfield** [comment]
I'm pretty sure we just need more space.  Consider this:

```
1.4G	$HOME/.dartServer
2.1G	$HOME/.pub-cache
823M	$HOME/.gradle
13G     $HOME/Android/Sdk
```

I have more SDK components installed than the devicelab probably does, but that is expected to grow over time as we bump things like target SDK/compile SDK values - and we don't really clean it up or expect the Flutter tool to clean it up.

**Comment by gspencergoog** [comment]
I agree, I'd at least double it to 20G.  Not that we shouldn't clean things up too, but then we wouldn't need to be as aggressive about it (I don't think these things grow unbounded, for the most part).

**Comment by dnfield** [comment]
.dartServer shouldn't, but the other three will continue to grow if they're not cleaned periodically as we roll to newer versions of packages/dependencies.

**Comment by godofredoc** [comment]
Health checks were added to cleanup cache directories.
