### ISSUE TITLE
Gallery, Shrine: Hero up of item has long frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5049]
On my Nexus 5X, built with profile. Open Gallery, tap into Shrine, tap an item image.

Trace:

![screen shot 2016-07-26 at 12 48 34 pm](https://cloud.githubusercontent.com/assets/5479/17153038/6a271a8a-532f-11e6-9431-e18989450413.png)

Trace file:

[shrine-hero-up.json.zip](https://github.com/flutter/flutter/files/384651/shrine-hero-up.json.zip)

**Comment by sethladd** [comment]
Might be the same root issue as another bug, but filing to so we have a good picture of each transition we want to smoothify.

**Comment by sethladd** [comment]
FWIW this effect is pronounced on 5X. The iPhone 6S seems to drive these frames with more ease.

**Comment by HansMuller** [comment]
This aspect of the demo is much less of a problem now.
See https://github.com/flutter/engine/pull/2911
