### ISSUE TITLE
Diagnosticable should be made into a mixin

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#50498]
Since `Diagnosticable` and classes that implement `DiagnosticableMixin` aren't the same type, code can't compare the type of an object with `Diagnosticable` to find out if it should call `toDiagnosticsNode` or not. See https://github.com/flutter/flutter/issues/49647 for more details.

In https://github.com/flutter/flutter/pull/49726, I fixed all the instances of this in Flutter where this happens by adding `implements Diagnosticable` to all of the mixin classes, but I still need to fix some instances of it in Google internal code before removing `Diagnosticable` entirely in favor of `DiagnosticableMixin`

**Comment by gspencergoog** [comment]
The plan now is to remove `DiagnosticableMixin` eventually, and just keep the mixin `Diagnosticable`, effectively converting the abstract class `Diagnosticable` into a mixin.

`DiagnosticableMixin` can't be removed until the mixin version of `Diagnosticable` is available in the stable branch, since some plugins that currently use `DiagnosticableMixin` want to be compatible with both stable and master.

**Comment by Hixie** [comment]
I believe this has now been in a stable release.

**Comment by gspencergoog** [comment]
Yes, this is already on my list to do.
