### ISSUE TITLE
Test framework should report when taps, flings don't hit the element

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#505]
I keep having the problem where I try to tap an element in a test, only to find after much debugging that the reason it's not working is that the node isn't actually getting tapped, usually because it's off-screen (though it could also just not be hit by the hit testing).

**Comment by cbracken** [comment]
Ran into this today with #7977. An alternative to this would be to allow tapping offscreen elements (perhaps optionally behind a boolean parameter to `tap`) -- the behaviour being tested may be orthogonal to the issue of whether something is expected to be on-screen or not.
