### ISSUE TITLE
PageView with viewportFraction < 1 snaps back on the last page

### ISSUE THREAD

**Issue by tsinis** [flutter/flutter#50505]
Hey!
Pageview with viewportFraction <1, wraped in NotificationListener still does not working properly on Flutter versions newer than 1.9.1, **when changing orientation**. It's snaps back on the last page and pages are not centred. Buggy on both Android and iOS. Also tested in actual stable, beta, dev and master branches.

Here is the short video:
https://youtu.be/XNPMiRO6hCA

Here is simple example:
https://gist.github.com/tsinis/4733f4a147e7e02686cf9913846ec7c4

Similar to:
https://stackoverflow.com/questions/59312394/pageview-with-viewportfraction-1-snaps-back-on-the-last-page

Please take a look, thanks!

**Comment by LongCatIsLooong** [comment]
Hi @tsinis thank you for reporting the issue! 

Could you elaborate on what "snaps back on the last page" means? Is the page view snapping to the second last page when it is supposed to snap to the last page (doesn't seem to be the case in the video)? When I tried I was able to land on the last page in landscape mode, and after rotating my phone to portrait mode the page view stayed at the last page (although a bit off-center).

**Comment by tsinis** [comment]
> 
> 
> Hi @tsinis thank you for reporting the issue!
> 
> Could you elaborate on what "snaps back on the last page" means? Is the page view snapping to the second last page when it is supposed to snap to the last page (doesn't seem to be the case in the video)? When I tried I was able to land on the last page in landscape mode, and after rotating my phone to portrait mode the page view stayed at the last page (although a bit off-center).

Hi @LongCatIsLooong 

Thank you for response! On Android, a slightly different behavior — the position of last card is fixed there, but then it’s almost impossible to return the penultimate card. In any case, the cards are not centered.
You can see on video what I'm talking about, start code in portrait mode, rotate device to landscape: cards are not centered and last one cannot fix it's position.
![bug](https://user-images.githubusercontent.com/52065414/74216955-468ab900-4ca6-11ea-896e-a5bfbc943bd0.gif)
