### ISSUE TITLE
clip-path does not work on Firefox

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#50508]
## Steps to Reproduce

Run the "Shrine" demo app in Firefox.

**Expected results:**

![clip-path-chrome](https://user-images.githubusercontent.com/211513/74194319-e21c1b00-4c0d-11ea-9521-e6fd243bfbd6.png)

**Actual results:**

![clip-path-firefox](https://user-images.githubusercontent.com/211513/74194340-e7796580-4c0d-11ea-869e-1b9d33cb03c7.png)

The `clip-path` we use in that button has no effect.

I checked our commit history back to https://github.com/flutter/engine/commit/f30ff4fcbf1984859066393ce2f755297b71d3d5, and the problem can be seen there. So it's unclear if path clipping ever worked in Firefox.

/cc @ferhatb

**Comment by yjbanov** [comment]
See https://github.com/flutter/flutter/issues/32215#issuecomment-591706633

Thanks @ds84182 for providing [the link](https://css-tricks.com/using-box-shadows-and-clip-path-together/)! We'll definitely check it out when we get to this issue.

**Comment by TahaTesser** [comment]
This seems to be working now on the latest `master`
<img width="712" alt="Screenshot 2020-11-10 at 8 02 50 PM" src="https://user-images.githubusercontent.com/48603081/98687470-c659c700-238f-11eb-9a6f-17d69a9d0bc8.png">

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.179, on Mac OS X 10.15.7 19H15
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.179 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a90880a8c3 (2 hours ago), 2020-11-10 05:02:56 -0800
    • Engine revision e50ac2c552
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS
      X 10.15.7 19H15 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.183

• No issues found!
```

</details>

Closing as fixed,  If you disagree, please write in the comments and I will reopen it.
Thank you
