### ISSUE TITLE
Close the status bar, the page will shake

### ISSUE THREAD

**Issue by SpanishOnion** [flutter/flutter#50518]
```dart
  Widget build(BuildContext context) {
    return Align(
      child: GestureDetector(
          onTap: () {
            _showStatusBar = !_showStatusBar;
            _showStatusBar
                ? SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values)
                : SystemChrome.setEnabledSystemUIOverlays([]);
          },
          child: Container(
            width: 500,
            height: 500,
            color: Colors.blue,
          )
      )
    );
```

![system](https://user-images.githubusercontent.com/27147542/74199699-dbd67f00-4c9f-11ea-9b52-7108abe2e042.gif)

**Comment by cgestes** [comment]
I can observe the same. It doesn't look easy to fix..

**Comment by pedromassangocode** [comment]
Hi @SpanishOnion 
Are you still facing this issue? Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by cgestes** [comment]
The bug is still there.

Had to play with android native code to avoid it.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by TahaTesser** [comment]
@cgestes 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
