### ISSUE TITLE
systrace unreachable before DartVM::Create 

### ISSUE THREAD

**Issue by pangzhen** [flutter/flutter#50526]
DartVM::Create calls Dart_SetVMFlags to init systrace ,  the systrace unreachable before inited, such as 
TRACE_EVENT0("flutter", "dart::bin::BootstrapDartIo");  
has no recorded

both android and linux OS, systrace depends on system provided,  so it should be inited earlier, but the TimelineEvent depends on OSThread, is there a little conflict ?

**Comment by dnfield** [comment]
Tracing on iOS always goes through Dart.

On Android it goes through Dart by default, but you can use the  `--trace-systrace` flag to make it use system tracing and then it should work as you are hoping for.

Let me know if there's something misisng here...

**Comment by pangzhen** [comment]
> Tracing on iOS always goes through Dart's observatory.
> 
> On Android it goes through Dart by default, but you can use the `--trace-systrace` flag to make it use system tracing and then it should work as you are hoping for.
> 
> Let me know if there's something misisng here...

search on systrace.html, the first record is TRACE_EVENT0("flutter", "Shell::CreateWithSnapshots"); , the earlier one TRACE_EVENT0("flutter", "Shell::Create"); is missing , both in the file flutter.cc , because of the systrace has been inited on auto vm = DartVMRef::Create(settings); , the missing record has been called before initiation

[systrace.zip](https://github.com/flutter/flutter/files/4202128/systrace.zip)

@dnfield

**Comment by dnfield** [comment]
That trace call is racy then, right?  Depending on how long the DartVM takes to initialize, and depdning on whether it's already been initialized for your process, that trace may or may not fire. This is expected behavior.  Even if you enable system tracing I believe we still go through the Dart VM.

Leaving this close on the understanding that this is WAI - /cc @chinmaygarde @jason-simmons @rmacnak-google to check my math here.

**Comment by dnfield** [comment]
Basically, we can't actually write trace events right now without a Dart VM, and we don't want to check or wait for Dart VM initialization to start tracing.
