### ISSUE TITLE
Hide data tables from Gallery (for now)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5053]
In an effort to pair down the gallery and ready it for launch, we'd like to hide the data tables. There's a few things we want to do to the tables before we launch them.

**Comment by HansMuller** [comment]
Don't forget to update demoTitles in /examples/flutter_gallery/test_driver/transitions_perf_test.dart

**Comment by ian** [comment]
Shit I forgot





On Tue, Jul 26, 2016 11:30 PM, Hans Muller notifications@github.com wrote:
@ian - Don't forget to update demoTitles in
/examples/flutter_gallery/test_driver/transitions_perf_test.dart
