### ISSUE TITLE
For Windows 10 OS. FileSystemException: FileSystemException: Cannot create file, path = 'F:\FlutterTest\sampleapps\android\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by abusayedcse** [flutter/flutter#50539]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by dnfield** [comment]
Does your user account have access to those files without requiring administrative priviledges?

**Comment by jonahwilliams** [comment]
Duplicate of https://github.com/flutter/flutter/issues/50880
