### ISSUE TITLE
[TextField] Pressed enter and no new line generated (Chinese Input Method)

### ISSUE THREAD

**Issue by AlexVincent525** [flutter/flutter#50547]
## Steps to Reproduce

1. Add `TextField` to some page.
2. Press `Enter` with any Chinese input method.
3. Nothing happened, no new lines.

**Expected results:** New lines were generated after pressed `Enter`.

**Actual results:** No new line generated.

**Screenshot for action**
![image](https://user-images.githubusercontent.com/15884415/74221361-ee2ada00-4cec-11ea-8591-360cb44a7e74.png)

![image](https://user-images.githubusercontent.com/15884415/74221347-e3704500-4cec-11ea-8a66-1e7fb21d0e96.png)

When switch to english type mode, the `Enter` behave normally.
I'm using sogou input method, which can be downloaded from here: [DOWNLOAD](http://quality-cdn.shouji.sogou.com/wapdl/android/apk/SogouInput_android_v10.3_sweb.apk) 
I'm running `1.14.6` from dev channel, but I think it must be the same at beta channel. So I think this bug should fired before it released as stable.

flutter doctor

```
[✓] Flutter (Channel dev, v1.14.6, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)
```

**Comment by Dorbmon** [comment]
It is the same proble as this issue:#50328

**Comment by Dorbmon** [comment]
You can switch to stable channel to avoid this proble as a temporary way.

**Comment by AlexVincent525** [comment]
@Dorbmon Thanks, just to make sure this will be fixed before stable released.
