### ISSUE TITLE
deprecation api FlutterPluginBinding??getFlutterEngine()???

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#50541]
Launching lib/main_dev.dart on JKM AL00a in debug mode...
Running Gradle task 'assembleDebug'...
?: ???????????????? API?
?: ??????, ??? -Xlint:deprecation ?????
/Users/liuyanfeng/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.6+1/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: ??: [deprecation] FlutterPluginBinding??getFlutterEngine()???
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 ???

╭   l   6.39G   100%    192.168.1.213    14:21  11.02.20 
╰ flutter doctor -v
[✓] Flutter (Channel master, v1.14.5, on Mac OS X 10.15.2 19C57, locale
    zh-Hans-CN)
    • Flutter version 1.14.5 at /Users/liuyanfeng/Library/flutter
    • Framework revision 92cbaa3efe (3 weeks ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/liuyanfeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/liuyanfeng/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

**Comment by iapicca** [comment]
Hi @lyf571321556 
I'm not 100% sure to understand this issue,
if you are concerned about the `deprecation api warning`
please see this [answer](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493).

Does this solve the issue?
If doesn't could you please provide more details.
Thank you
