### ISSUE TITLE
[triage] update no-response bot message

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#50549]
Hi all,
the current [no-response bot](https://github.com/apps/no-response) message is

> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

I propose to add

> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.

with the purpose of discourage users that believe they have similar problem
from commenting on the closed issue and opening a new one
that can be triaged properly.

Thank you for the attention

**Comment by godofredoc** [comment]
@Hixie should we update the no-response message?

**Comment by Hixie** [comment]
SGTM
