### ISSUE TITLE
Changing applications with keys pressed results in stuck keys on macOS

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#50553]
# Steps to Reproduce

1. Download [this flutter sample project](https://www.netno.org/examples/tab_breaks_after_native_dialog.zip)
2. Run on macOS `flutter run -d macos`
3. Verify that tab traversal is working by navigating through the form by pressing TAB
4. navigate to the _open file chooser_ button and invoke it by pressing space on the keyboard
5. Close the file chooser dialog with _cancel_
-> Afterwards tab traversal no longer works

Note: When invoking the file chooser by clicking on the button with the mouse, tab traversal is unaffected.

**Expected results:** Tab traversal must work after opening external dialogs with the keyboard

**Actual results:** Tab traversal stops working after opening external dialogs with the keyboard

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by technolion** [comment]
cc @gspencergoog, @stuartmorgan

**Comment by stuartmorgan** [comment]
The file chooser dialog is opening on keydown, not keyup, so I strongly suspect that my initial guess that this was a stuck key is correct (i.e., that Flutter believes the spacebar is still down due to the dialog receiving the keyup). I haven't debugged into the framework to verify though.

**Comment by gspencergoog** [comment]
Yes, that seems likely.

**Comment by krisgiesing** [comment]
Possibly the same code is involved as this issue I just logged: https://github.com/flutter/flutter/issues/51080

If RawKeyboard is not getting the keyUp for the space bar, then yes, Flutter will continue to believe the space bar is down.

**Comment by technolion** [comment]
> Possibly the same code is involved as this issue I just logged: #51080
> 
> If RawKeyboard is not getting the keyUp for the space bar, then yes, Flutter will continue to believe the space bar is down.

Nope, this bug can still be reproduced with v1.15.4-pre.241 (channel master), where your PR is merged.

**Comment by krisgiesing** [comment]
The PR for #51080 addressed that specific case, but the general issue of Flutter thinking keys are down when they aren't is not fully addressed. I made a comment here that I think highlights the problem that is at the root of this bug: https://github.com/flutter/flutter/pull/51095#discussion_r382255296

**Comment by stuartmorgan** [comment]
I'm going to make this a more generic bug, since we are slowly accumulating very specific variants of it, when they are all fundamentally the same problem and should be tracked in one place.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.359, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.359 at C:\Code\flutter_master
    • Framework revision db6e2d8aa5 (2 hours ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by dkwingsmt** [comment]
This problem should have been resolved by https://github.com/flutter/flutter/pull/80756.
