### ISSUE TITLE
Invalid character in test result output

### ISSUE THREAD

**Issue by pvegh** [flutter/flutter#50550]
When a test logs something, it generates a character in the result, which is then converted to junit format via the "tojunit" tool from the flutter docs , but this character is breaking the junit result parser in gitlab ci.

The problematic character is: \u001b

Snippet from the output of "flutter test --machine":"

{"testID":15,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":2799}
{"testID":14,"messageType":"print","message":"\u001b[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────\u001b[0m","type":"print","time":2811}

Is there a way to get rid of these color and special markers when using --machine? In that case they are probably not relevant at all.

**Comment by pvegh** [comment]
I fixed my particular problem by removing the problematic character with:
flutter test --machine | sed 's/\\u001b//g'

**Comment by TahaTesser** [comment]
Hi @pvegh 
Closing as stated `fixed` by the reporter. If the problem persists, please create a new issue and provide the information required in the template.
Thank you

**Comment by pvegh** [comment]
Stupid robot. It's NOT fixed. I fixed it with a workaround. Reopen issue

**Comment by jonahwilliams** [comment]
This seems like a bug with the junit parser and not flutter

**Comment by pvegh** [comment]
What if I add that any xml validator says the document is invalid, because of this character?
Are all of them wrong and flutter is correct adding an unnecessary character to the report?

**Comment by jonahwilliams** [comment]
flutter test does not output xml

**Comment by pvegh** [comment]
Well, this report is getting tiresome...
The character IS generated by Flutter.

flutter test --machine --no-color | grep 001b
{"testID":15,"messageType":"print","message":"\u001b[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────\u001b[0m","type":"print","time":2595}
