### ISSUE TITLE
Multiline block layout widget (Wrap)

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5055]
The current Flutter flex layout does not allow for handling overflow of child widgets.

There are some situations where you would want the widgets to flow the next line (wrap) instead of being cut off.

In the HTML Flexbox world, this would be the value for  _flex-wrap_.

Example:

![screen shot 2016-07-26 at 1 34 57 pm](https://cloud.githubusercontent.com/assets/3635416/17154406/c73822ae-5335-11e6-94c2-ea5c12a8fdf3.png)

9:45pm should flow to the next line instead of being cut off.

**Comment by dvdwasibi** [comment]
@Hixie Bump :)

**Comment by Hixie** [comment]
I think we should implement this as a new layout algorithm with the following features:

* It has a list of children.
* It has an axis.
* It only works in main-axis unbounded environments.
* For each child, during layout, it lays the child out with loose main-axis constraints with the incoming max main axis constraint and with unbounded vertical constraints.
* In the cross axis, children are aligned according to a cross axis alignment.
* In the main axis, children are laid out one after the other in a given direction (ltr/ttb or rtl/btt). Each time one doesn't fit, a new line is started. Lines are stacked adjacent to each other and are as high as needed to accommodate that line's children with the given cross-axis alignment.
* Children can have, in their parent data, an explicit minwidth specified. If the remaining space isn't sufficient for that minwidth, a new line is started. If a child has a minwidth, the child is given tight constraints of the remaining space on whatever line they're on.

**Comment by Hixie** [comment]
(The latter bullet point is intended to handle the "text field after a bunch of chips" use case)

**Comment by Hixie** [comment]
The main axis is the reading axis, horizontal for the screenshot above. The cross axis is the axis in which the children wrap, the axis in which new lines are placed.

**Comment by Hixie** [comment]
I believe @abarth did this.

**Comment by abarth** [comment]
Yes.

**Comment by sandangel** [comment]
hi everyone, is this feature ready yet and how the code will look like?

**Comment by zoechi** [comment]
@sandangel I guess this is about https://docs.flutter.io/flutter/widgets/Wrap-class.html

**Comment by WiRight** [comment]
I dont sure, but you wanna used a `Wrap` widget? See it in [official flutter channel](https://www.youtube.com/watch?v=z5iw2SeFx2M). Maybe it will be help you
