### ISSUE TITLE
 NoSuchMethodError: The method 'call' was called on null. Receiver: null Tried calling: call(Instance of 'DateTime')

### ISSUE THREAD

**Issue by RandersonThallys** [flutter/flutter#50559]
Estou enfrentando esse erro não fatal no flutter, ja pesquisei mas não achei nada que pode-se solucioná-lo.

[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale pt-BR)
    • Flutter version 1.12.13+hotfix.7 at C:\src\flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\randerson.nascimento\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\randerson.nascimento\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

#ERRO
Non-fatal Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'DateTime')
0  ???                            0x0 (Ausente) (dart:core)
1  ???                            0x0 _onDayLongPressed + 764 (flutter_calendar_carousel.dart:764)
2  ???                            0x0 renderDay.<fn> + 457 (flutter_calendar_carousel.dart:457)
3  ???                            0x0 invokeCallback + 182 (recognizer.dart:182)
4  ???                            0x0 _checkLongPressStart + 304 (long_press.dart:304)
5  ???                            0x0 didExceedDeadline + 253 (long_press.dart:253)
6  ???                            0x0 didExceedDeadlineWithEvent + 519 (recognizer.dart:519)
7  ???                            0x0 addAllowedPointer.<fn> + 446 (recognizer.dart:446)

**Comment by TahaTesser** [comment]
Hi @RandersonThallys 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by RandersonThallys** [comment]
#code

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_calendar_carousel/classes/event_list.dart';
import 'package:flutter_calendar_carousel/classes/event.dart';
import 'package:flutter_calendar_carousel/flutter_calendar_carousel.dart';
import 'package:scoped_model/scoped_model.dart';
import 'package:vets/data/repository.dart';
import 'package:vets/models/app_model.dart';
import 'package:vets/models/appointment.dart';
import 'package:vets/views/vet/agenda/index.dart';
import 'package:vets/views/vet/widgets/vet_menu_drawer/index.dart';
import 'package:vets/views/vet/widgets/vet_app_bar/index.dart';
import 'package:vets/views/vet/widgets/vet_bottom_navigation_bar/index.dart';

class VetAgendaPage extends StatefulWidget {
  VetAgendaPage();

  @override
  _VetAgendaPageState createState() {
    return new _VetAgendaPageState();
  }
}

class _VetAgendaPageState extends State<VetAgendaPage> {
  EventList<Event> _markedDateMap = EventList<Event>();

  @override
  void initState() {
    super.initState();
  }

  void getCalendarEventList() async {}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: VetAppBar(pageTitle: 'Agenda'),
      backgroundColor: Colors.white,
      endDrawer: VetMenuDrawer(),
      bottomNavigationBar: AppBottomNavigationBar(),
      body: ScopedModelDescendant<AppModel>(
        builder: (context, child, model) => StreamBuilder(
              stream: Repository.get().getAllActiveAppointments(model.vetUser.uid,true),
              builder: (context, snapshot) => snapshot.hasData
                  ? _buildBody(context, model, snapshot.data)
                  : LinearProgressIndicator(),
            ),
      ),
    );
  }

  bool _isPast(DateTime t){
    final now = new DateTime.now();

    return t.month < now.month || (t.isBefore(now) && t.day < now.day);
  }

  _buildBody(BuildContext context, AppModel model, QuerySnapshot snapshot) {
    _markedDateMap.clear();
    final daysPast = Theme.of(context).textTheme.body1.copyWith(color: Color.fromARGB(255, 210, 210, 210,));

    snapshot.documents.forEach((data) {
      Appointment appointment = Appointment.fromSnapshot(data);
      if(_isPast(appointment.startTime)){
        return; //Ignorando marcação roxa (de dia com consulta) para dia que já passou
      }
      _markedDateMap.add(
          DateTime(appointment.startTime.year, appointment.startTime.month,
              appointment.startTime.day),
          Event(
            date: appointment.startTime,
            title: '',
            icon: Positioned(
              child: IconButton(
                icon: Icon(Icons.add),
                onPressed: null,
              ),
            ),
          ));
    });

    return CalendarCarousel<Event>(
      height: 400,
      locale: 'pt_br',
      weekFormat: false,
      customGridViewPhysics: NeverScrollableScrollPhysics(),
      headerTextStyle: Theme.of(context)
          .textTheme
          .title
          .copyWith(color: Theme.of(context).primaryColor),
      showHeaderButton: true,
      iconColor: Theme.of(context).primaryColor,
      todayButtonColor: Theme.of(context).primaryColor,
      todayBorderColor: Theme.of(context).primaryColor,
      todayTextStyle:
          Theme.of(context).textTheme.body1.copyWith(color: Colors.white, fontWeight: FontWeight.w600 ),
      weekdayTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Theme.of(context).primaryColor, fontWeight: FontWeight.w600),
      weekendTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Theme.of(context).primaryColor,fontWeight: FontWeight.w600),
      daysTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Colors.black,fontWeight: FontWeight.w600 ),
      prevDaysTextStyle: Theme.of(context).textTheme.body1.copyWith(),
      markedDateIconOffset: 20,
      markedDateIconMargin: 0,
      markedDateShowIcon: true,
      markedDateMoreShowTotal: true,
      markedDateIconMaxShown: 0,
      showOnlyCurrentMonthDate: true,
      markedDatesMap: _markedDateMap,
      customDayBuilder: (   /// you can provide your own build function to make custom day containers
          bool isSelectable,
          int index,
          bool isSelectedDay,
          bool isToday,
          bool isPrevMonthDay,
          TextStyle textStyle,
          bool isNextMonthDay,
          bool isThisMonthDay,
          DateTime day,
          )
      {
        /// If you return null, [CalendarCarousel] will build container for current [day] with default function.
        /// This way you can build custom containers for specific days only, leaving rest as default.

        if (_isPast(day)) {
          return Center(
            child: Text(
              day.day.toString(),
              style: daysPast,
            )
          );
        } else {
          return null;
        }
      },
      markedDateMoreCustomDecoration: BoxDecoration(
        shape: BoxShape.circle,
        color: Theme.of(context).accentColor,
      ),
      markedDateMoreCustomTextStyle: Theme.of(context)
          .textTheme
          .caption
          .copyWith(color: Theme.of(context).accentColor),
      onDayPressed: (DateTime date, List<Event> events) {

        //if(date.month != now.month){ //Quando o calendário está no mês de X, e o vet clica num dia do mês X-1 ou X+1, não deve abrir as consultas do dia, e sim mudar o mês do calendário
        //  return;
        //}

        if(!_isPast(date)) {
          Navigator.of(context).push(
            new MaterialPageRoute(
              builder: (context) => new VetAgendaDayPage(date),
            ),
          );
        }
      },
    );
  }
}

**Comment by RandersonThallys** [comment]
Flutter run --verbose
[verbose.txt](https://github.com/flutter/flutter/files/4186300/verbose.txt)

**Comment by RandersonThallys** [comment]
> #código
> 
> import 'pacote: cloud_firestore / cloud_firestore.dart';
> import 'pacote: flutter / material.dart';
> import 'pacote: flutter_calendar_carousel / classes / event_list.dart';
> import 'pacote: flutter_calendar_carousel / classes / event.dart';
> import 'pacote: flutter_calendar_carousel / flutter_calendar_carousel.dart';
> import 'pacote: scoped_model / scoped_model.dart';
> import 'pacote: veterinários / dados / repositório.dart';
> import 'pacote: veterinários / modelos / app_model.dart';
> import 'pacote: veterinários / modelos / compromisso.dart';
> import 'pacote: vets / views / vet / agenda / index.dart';
> import 'pacote: vets / views / vet / widgets / vet_menu_drawer / index.dart';
> import 'package:
> import 'pacote: vets / views / vet / widgets / vet_bottom_navigation_bar / index.dart';
> 
> classe VetAgendaPage estende StatefulWidget {
> VetAgendaPage ();
> 
> @override
> _VetAgendaPageState createState () {
> retorna novo _VetAgendaPageState ();
> }
> }
> 
> classe _VetAgendaPageState estende State {
> EventList _markedDateMap = EventList ();
> 
> @override
> void initState () {
> super.initState ();
> }
> 
> void getCalendarEventList () async {}
> 
> @override Compilação de
> widget (contexto BuildContext) {
> return Scaffold (
> appBar: VetAppBar (pageTitle: 'Agenda'),
> backgroundColor: Colors.white,
> endDrawer: VetMenuDrawer (),
> bottomNavigationBar: AppBottomNavigationBar (),
> body: ScopedModelDescendant (
> builder: (context, filho, modelo) => StreamBuilder (
> stream: Repository.get (). getAllActiveAppointments (model.vetUser.uid, true),
> construtor: (context, snapshot) => snapshot.hasData
> ? _buildBody (contexto, modelo, snapshot.data)
> : LinearProgressIndicator (),
> ),
> ),
> );
> }
> 
> bool _isPast (DateTime t) {
> final agora = new DateTime.now ();
> 
> ```
> return t.month < now.month || (t.isBefore(now) && t.day < now.day);
> ```
> 
> }
> 
> _buildBody (contexto BuildContext, modelo AppModel, instantâneo QuerySnapshot) {
> _markedDateMap.clear ();
> last daysPast = Theme.of (context) .textTheme.body1.copyWith (color: Color.fromARGB (255, 210, 210, 210,));
> 
> ```
> snapshot.documents.forEach((data) {
>   Appointment appointment = Appointment.fromSnapshot(data);
>   if(_isPast(appointment.startTime)){
>     return; //Ignorando marcação roxa (de dia com consulta) para dia que já passou
>   }
>   _markedDateMap.add(
>       DateTime(appointment.startTime.year, appointment.startTime.month,
>           appointment.startTime.day),
>       Event(
>         date: appointment.startTime,
>         title: '',
>         icon: Positioned(
>           child: IconButton(
>             icon: Icon(Icons.add),
>             onPressed: null,
>           ),
>         ),
>       ));
> });
> 
> return CalendarCarousel<Event>(
>   height: 400,
>   locale: 'pt_br',
>   weekFormat: false,
>   customGridViewPhysics: NeverScrollableScrollPhysics(),
>   headerTextStyle: Theme.of(context)
>       .textTheme
>       .title
>       .copyWith(color: Theme.of(context).primaryColor),
>   showHeaderButton: true,
>   iconColor: Theme.of(context).primaryColor,
>   todayButtonColor: Theme.of(context).primaryColor,
>   todayBorderColor: Theme.of(context).primaryColor,
>   todayTextStyle:
>       Theme.of(context).textTheme.body1.copyWith(color: Colors.white, fontWeight: FontWeight.w600 ),
>   weekdayTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Theme.of(context).primaryColor, fontWeight: FontWeight.w600),
>   weekendTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Theme.of(context).primaryColor,fontWeight: FontWeight.w600),
>   daysTextStyle: Theme.of(context).textTheme.body1.copyWith(color: Colors.black,fontWeight: FontWeight.w600 ),
>   prevDaysTextStyle: Theme.of(context).textTheme.body1.copyWith(),
>   markedDateIconOffset: 20,
>   markedDateIconMargin: 0,
>   markedDateShowIcon: true,
>   markedDateMoreShowTotal: true,
>   markedDateIconMaxShown: 0,
>   showOnlyCurrentMonthDate: true,
>   markedDatesMap: _markedDateMap,
>   customDayBuilder: (   /// you can provide your own build function to make custom day containers
>       bool isSelectable,
>       int index,
>       bool isSelectedDay,
>       bool isToday,
>       bool isPrevMonthDay,
>       TextStyle textStyle,
>       bool isNextMonthDay,
>       bool isThisMonthDay,
>       DateTime day,
>       )
>   {
>     /// If you return null, [CalendarCarousel] will build container for current [day] with default function.
>     /// This way you can build custom containers for specific days only, leaving rest as default.
> 
>     if (_isPast(day)) {
>       return Center(
>         child: Text(
>           day.day.toString(),
>           style: daysPast,
>         )
>       );
>     } else {
>       return null;
>     }
>   },
>   markedDateMoreCustomDecoration: BoxDecoration(
>     shape: BoxShape.circle,
>     color: Theme.of(context).accentColor,
>   ),
>   markedDateMoreCustomTextStyle: Theme.of(context)
>       .textTheme
>       .caption
>       .copyWith(color: Theme.of(context).accentColor),
>   onDayPressed: (DateTime date, List<Event> events) {
> 
>     //if(date.month != now.month){ //Quando o calendário está no mês de X, e o vet clica num dia do mês X-1 ou X+1, não deve abrir as consultas do dia, e sim mudar o mês do calendário
>     //  return;
>     //}
> 
>     if(!_isPast(date)) {
>       Navigator.of(context).push(
>         new MaterialPageRoute(
>           builder: (context) => new VetAgendaDayPage(date),
>         ),
>       );
>     }
>   },
> );
> ```
> 
> }
> }

@TahaTesser

**Comment by RandersonThallys** [comment]
> [Execução de](https://github.com/flutter/flutter/files/4186300/verbose.txt) vibração --verbose
> [verbose.txt](https://github.com/flutter/flutter/files/4186300/verbose.txt)

@TahaTesser

**Comment by TahaTesser** [comment]
Hi @RandersonThallys  
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem. Not a full production app
Thank you

**Comment by RandersonThallys** [comment]
@TahaTesser ja postei o code!

**Comment by VladyslavBondarenko** [comment]
Hi @RandersonThallys 
As I understand the error is caused in the [flutter_calendar_carousel](https://github.com/dooboolab/flutter_calendar_carousel) plugin

> 0 ??? 0x0 (Ausente) (dart:core)
> 1 ??? 0x0 _onDayLongPressed + 764 (flutter_calendar_carousel.dart:764)

Consider to open the issue in the [plugin's github](https://github.com/dooboolab/flutter_calendar_carousel).

Closing current one,
if you disagree and the this is an issue with Flutter itself, please write in the comments and I will reopen it.
Thank you

**Comment by RandersonThallys** [comment]
Atualizei minha versão pessoal vou ficar observando, e caso o erro persista eu abro chamando no github do plug-in!
