### ISSUE TITLE
`flutter version` gets confused on master with some configurations of Git history

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#50577]
Sometimes, a PR has to have its git history rewritten because the tool starts reporting some older version of Flutter with a very high `.pre` number.  See for example https://github.com/flutter/flutter/pull/45035

The work around for this is to:

```
git fetch upstream
git reset --soft upstream/master
git commit -m 'rewrite history!'
git push -f
```

Or something like that.  This gets the version output back to normal on CI.

Ideally, the tool would be able to handle this situation.  I'm not as familiar with its version logic though - @jonahwilliams maybe?

/cc @Piinks

**Comment by Piinks** [comment]
I've seen this on a couple of different PRs now that were from older branches. Here is another one: https://github.com/flutter/flutter/pull/42100#issuecomment-575726958

**Comment by dnfield** [comment]
We might not have to fix this globally if it's not possible, but we should at least see if we can fix it for the analysis script on the bots.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/42100#issuecomment-575731637

```
 The current Flutter SDK version is 1.10.7-pre.130.

    | 

    | Because flutter_gallery depends on video_player_web >=0.1.1 which requires Flutter SDK version >=1.12.8 <2.0.0, version solving failed.
```

> It should be saying the current flutter SDK version is 1.14.x-pre.something, not 1.10.7-pre.130.

**Comment by Piinks** [comment]
Here is a more recent occurrence: https://cirrus-ci.com/task/5901078327721984 from #44888

**Comment by christopherfujino** [comment]
this looks like https://github.com/flutter/flutter/issues/15529

**Comment by dnfield** [comment]
Agreed - I'll close this as a dupe of that one since it has a better repro case.
