### ISSUE TITLE
On using webView to load a url using initialurl property there seems to be some error?

### ISSUE THREAD

**Issue by Chaitanyaha** [flutter/flutter#50572]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** /EGL_emulation(11137): eglCreateContext: 0xe9c2c900: maj 3 min 0 
rcv 3
D/EGL_emulation(11137): eglMakeCurrent: 0xe9c2c900: ver 3 0 (tinfo 0xce3d5540)
D/eglCodecCommon(11137): setVertexArrayObject: set vao to 1 (1) 0 
0
D/eglCodecCommon(11137): setVertexArrayObject: set vao to 2 (2) 0 
0
D/eglCodecCommon(11137): setVertexArrayObject: set vao to 1 (1) 0 
0
D/eglCodecCommon(11137): setVertexArrayObject: set vao to 2 (2) 0 
0
D/eglCodecCommon(11137): setVertexArrayObject: set vao to 1 (1) 0 
0 

<details>

  <summary>Logs</summary>

```
```

```
```

```
Scaffold(
      appBar: AppBar(title: Text('${article.title}')),
      body: SafeArea(
        child: WebView(initialUrl: article.title),
      ),
    );
```

</details>

**Comment by TahaTesser** [comment]
Hi @Chaitanyaha 
`initialUrl` seems to work just fine [Gist](https://gist.github.com/TahaTesser/a4d04149da4f54670e19b2ecb59db0ae)
Are you sure you're giving proper url to `initialUrl` and your snippet says `article.title`.
Please make sure its an url 
Thank you

**Comment by Chaitanyaha** [comment]
Yes I just updated to '${article.title}'

ThankYou.

**Comment by TahaTesser** [comment]
Hi @Chaitanyaha 
Closing this issue as this isn't an issue with Flutter Itself. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
