### ISSUE TITLE
Non-fatal Exception: java.lang.Exception NoSuchMethodError: The method 'call' was called on null. Receiver: null Tried calling: call() Alert._getCloseButton.<fn>

### ISSUE THREAD

**Issue by RandersonThallys** [flutter/flutter#50576]
Estou enfrentando esse erro não fatal no flutter, ja pesquisei mas não achei nada que pode-se solucioná-lo.

[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale pt-BR)
• Flutter version 1.12.13+hotfix.7 at C:\src\flutter
• Framework revision 9f5ff23 (2 weeks ago), 2020-01-26 22:38:26 -0800
• Engine revision a67792536c
• Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\randerson.nascimento\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
• All Android licenses accepted.

[√] Android Studio (version 3.5)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 43.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
• VS Code at C:\Users\randerson.nascimento\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.8.1

#ERRO
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
       at Alert._getCloseButton.<fn>(_getCloseButton.java:166)
       at _InkResponseState._handleTap(_InkResponseState.java:706)
       at _InkResponseState.build.<fn>(build.java:789)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:182)
       at TapGestureRecognizer.handleTapUp(TapGestureRecognizer.java:486)
       at BaseTapGestureRecognizer._checkUp(BaseTapGestureRecognizer.java:282)
       at BaseTapGestureRecognizer.handlePrimaryPointer(BaseTapGestureRecognizer.java:199)
       at PrimaryPointerGestureRecognizer.handleEvent(PrimaryPointerGestureRecognizer.java:467)
       at PointerRouter._dispatch(PointerRouter.java:76)
       at PointerRouter._dispatchEventToRoutes.<fn>(_dispatchEventToRoutes.java:117)
       at PointerRouter._dispatchEventToRoutes(PointerRouter.java:115)
       at PointerRouter.route(PointerRouter.java:101)
       at GestureBinding.handleEvent(GestureBinding.java:218)
       at GestureBinding.dispatchEvent(GestureBinding.java:198)
       at GestureBinding._handlePointerEvent(GestureBinding.java:156)
       at GestureBinding._flushPointerEventQueue(GestureBinding.java:102)
       at GestureBinding._handlePointerDataPacket(GestureBinding.java:86)
[verbose.txt](https://github.com/flutter/flutter/files/4187203/verbose.txt)

**Comment by TahaTesser** [comment]
Hi @RandersonThallys 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by RandersonThallys** [comment]
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:vets/routes.dart';
import 'package:vets/services/auth.dart';

alert(context, String msg, {Function onOk, AlertType alertType}) {
  Alert(
    context: context,
    type: alertType ?? AlertType.error,
    title: "Alerta",
    style: AlertStyle(titleStyle: TextStyle(fontFamily: 'ClanPro')),
    desc: msg,
    buttons: [
      DialogButton(
        radius:  BorderRadius.all(Radius.zero),
        child: Text(
          "Ok",
          style: TextStyle(color: Colors.white, fontSize: 20, fontFamily: 'ClanPro'),
        ),
        onPressed: () {
          Navigator.pop(context);
          if(onOk!=null)
            onOk();
        },
        width: 120,
        color: Theme.of(context).primaryColor,
      )
    ],
  ).show();
}

yesNoAlert(context, String msg, Function onConfirm, {AlertType alertType, String confirmButton, bool isPet=false}) {
  Alert(
    context: context,
    type: alertType ?? AlertType.error,
    title: "Tem certeza?",
    style: AlertStyle(titleStyle: TextStyle(fontFamily: 'ClanPro')),
    desc: msg,
    buttons: [
      DialogButton(
        radius:  BorderRadius.all(Radius.zero),
        child: Text(
          "Cancelar",
          style: TextStyle(color: Colors.white, fontSize: 20, fontFamily: 'ClanPro'),
        ),
        onPressed: () {
          Navigator.pop(context);
        },
        width: 120,
        color: isPet ? Theme.of(context).accentColor : Theme.of(context).primaryColor,
      ),
      DialogButton(
        radius:  BorderRadius.all(Radius.zero),
        child: Text(
          confirmButton ?? "Confirmar",
          style: TextStyle(color: Colors.white, fontSize: 20, fontFamily: 'ClanPro'),
        ),
        onPressed: () {
          Navigator.pop(context);
          onConfirm();
        },
        width: 120,
        color: isPet ? Theme.of(context).accentColor : Theme.of(context).primaryColor,
      )
    ],
  ).show();
}

insertPasswordAndLogin(context, String email, VoidCallback onContinue, {VoidCallback onClose}) {
  final controller = TextEditingController();
  Alert(
    context: context,
    type: AlertType.info,
    title: "Insira sua senha",
    closeFunction: onClose ?? (){},
    style: AlertStyle(titleStyle: TextStyle(fontFamily: 'ClanPro')),
    desc: 'Por favor, insira sua senha para alterar seu e-mail',
    content: WillPopScope(
        onWillPop: () async{
          if(onClose!=null) onClose();
          return true;
        },
        child : Container(
          child: TextField(controller: controller, obscureText: true, style: TextStyle(fontSize: 20),),
          margin: EdgeInsets.all(20),
        ),
    ),
    buttons: [
      DialogButton(
        radius:  BorderRadius.all(Radius.zero),
        child: Text(
          "Continuar",
          style: TextStyle(color: Colors.white, fontSize: 20, fontFamily: 'ClanPro'),
        ),
        onPressed: () async {
          try {
            await Auth().signInWithEmailAndPassword(email, controller.text);
            Navigator.of(context, rootNavigator: true).pop();
            if (onContinue != null)
              onContinue();
          }catch(e){
            final err = e.toString();
            if(err.contains('ERROR_WRONG_PASSWORD')){
              alert(context,  'Senha incorreta');
              return;
            }if(err.contains('ERROR_USER_NOT_FOUND')){
              throw 'Email informado por parâmetro do método incorreto!';
            }
            throw 'Erro não tratado em insertPasswordAndLogin: '+err;
          }
        },
        width: 120,
        color: Theme.of(context).primaryColor,
      )
    ],
  ).show();
}

/*alertLoginAfterEmailChanged(context, String newEmail, Auth _auth){
  alert(context, 'Só falta um passo, realize login com seu novo e-mail para que ele seja alterado\n'+newEmail, onOk: (){
    _auth.signOut();
    Navigator.of(context).pushReplacementNamed(Routes.signIn);
  }, alertType:  AlertType.warning);
}*/

@TahaTesser

**Comment by VladyslavBondarenko** [comment]
Hi @RandersonThallys 
I managed to reproduce it, when pressing close button in the right-top corner,
You can create an issue in the [rflutter_alert's github](https://github.com/RatelHub/rflutter_alert/issues)

As a workaround I would simply not use it.
My minimal reproducible code with already inserted style to hide the button

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'drawVertices Example Issue',
      home: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: MaterialButton(
              child: Text('button'),
              onPressed: () => alert(context, 'alert'),
            ),
          ),
        ),
      ),
    );
  }

  alert(context, String msg, {Function onOk, AlertType alertType}) {
    Alert(
      context: context,
      type: alertType ?? AlertType.error,
      title: "Alerta",
      desc: msg,
      style: AlertStyle(
        isCloseButton: false,
      ),
      buttons: [
        DialogButton(
          radius: BorderRadius.all(Radius.zero),
          child: Text("Ok"),
          onPressed: () {
            Navigator.pop(context);
            if (onOk != null) onOk();
          },
          width: 120,
        )
      ],
    ).show();
  }
}
```

</details>

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by RandersonThallys** [comment]
Vlw, vou verificar essa possibilidade com o pessoal, caso contrario vou abrir um chamado no flutter_alert, mas agradeço! 
@VladyslavBondarenko
