### ISSUE TITLE
picture_cache_perf__timeline_summary worst_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50570]
First starts around https://github.com/flutter/flutter/pull/50363, then drops:

![benchmark](https://user-images.githubusercontent.com/1435716/74253480-fca0d380-4ca3-11ea-901c-79328c5e5bfb.png)

**Comment by jason-simmons** [comment]
I've been unable to reproduce this on my development setup.

**Comment by Hixie** [comment]
Looking at the benchmark, it's possible it's sort of bimodal and we've crossed a threshold?
![Screen Shot 2020-02-11 at 16 06 21](https://user-images.githubusercontent.com/551196/74291040-81addc00-4ce8-11ea-9128-357fe8f8f400.png)

**Comment by Hixie** [comment]
@jason-simmons What device were you trying it on? Maybe it's Moto G4 specific?

**Comment by jason-simmons** [comment]
I tried a Moto G4 and a Nexus 5X.  Using various recent framework versions I saw `worst_frame_rasterizer_time_millis` values consistently within the 11-19ms range.  Whereas the dashboard is now often showing resutls in the 30-40ms range.

The `99th_percentile_frame_rasterizer_time_millis` and `90th_percentile_frame_rasterizer_time_millis` metrics are not showing any change on the dashboard.  So that implies that this is due to some sort of one time setup cost.

But I don't know why the dashboard results only sometimes showed a >30ms value or why that started happening on most runs within the last few days.

**Comment by liyuqian** [comment]
Could this be caused by infra? Like certain mac/android bots are always fast or slow. CC @digiter @godofredoc to see if we can reproduce the slow time consistently in the device lab.

**Comment by kf6gpe** [comment]
Just a public heads-up that we're still looking at whether infra's the culprit; query sent to @digiter & @godofredoc today.

**Comment by digiter** [comment]
The test runs were distributed among 6 mac/android testbeds, and it's hard to identify the green runs on dashboards. We could try to manually reproduce it on each of the mac/android testbed though.

**Comment by godofredoc** [comment]
I'd suggest to run on a single mac multiple times to validate the metric is consistent. If it fails consistently then reboot phone and machine and try again.

**Comment by kf6gpe** [comment]
@digiter Any luck rerunning on a single mac multiple times? We're still seeing what looks to be a bona fide regression:
![Screen Shot 2020-03-30 at 2 34 04 PM](https://user-images.githubusercontent.com/1435716/77964221-90018880-7293-11ea-8cf0-20a1e55090e2.png)

**Comment by digiter** [comment]
Here're ten runs on mac17, so it's flaky on a single machine.

```
"worst_frame_rasterizer_time_millis": 33.007,
"worst_frame_rasterizer_time_millis": 34.007,
"worst_frame_rasterizer_time_millis": 14.353,
"worst_frame_rasterizer_time_millis": 36.401,
"worst_frame_rasterizer_time_millis": 26.342,
"worst_frame_rasterizer_time_millis": 74.295,
"worst_frame_rasterizer_time_millis": 16.599,
"worst_frame_rasterizer_time_millis": 65.518,
"worst_frame_rasterizer_time_millis": 84.373,
"worst_frame_rasterizer_time_millis": 13.768,
```

**Comment by liyuqian** [comment]
@digiter : can we temporarily take mac17 down from the device lab so maybe @jason-simmons can ssh into it and bisect?

**Comment by digiter** [comment]
Yes. The instructions is at go/flutter-devicelab. Please ping me or the infra oncall if there's any questions.

**Comment by pcsosinski** [comment]
what's the status here?

**Comment by liyuqian** [comment]
Just synced with @jason-simmons offline. He's now bisecting it on mac17. @pcsosinski : do you have any specific reason to concern about this regression, or is it a general check on performance regressions?

**Comment by pcsosinski** [comment]
i was just doing the morning sweep.   seems like this has been red for a while and just wanted to figure out if we are going to fix it

**Comment by jason-simmons** [comment]
I did a series of runs with various framework/engine versions on mac17 in the devicelab.  There were only a few results with `worst_frame_rasterizer_time_millis` above 30ms, and there was no consistent pattern.

c88320458ea86da379aec43dcd24057ad1d79652 (1/15)
`16.114, 18.132, 17.946, 17.125, 20.184`

ef74572e764f53e7f63bfa9a5824f63209610f6d (2/7 - around where the change started on the dashboard)
`11.481, 15.356, 13.337, 16.958, 16.056`

c388a26131aef1afbd7d56743ecade9d2e8c8ee4 (2/10)
`16.531, 12.547, 18.426, 13.986, 17.652`

57b93c790f0cdb99a1177c17ff90b54dddd8ee97 (2/12)
`16.105, 15.301, 14.13, 15.772, 15.721`

6ecb0521399c3148aaac513921cd51a3e17e56a9 (2/14)
`34.247, 15.151, 20.113, 17.137, 18.265`

686d16342071b6bb5ee480232e4d1482768008fc (3/2)
`19.322, 16.772, 13.427, 13.908, 14.128`

7e97ca60779e8dc12d047a0b54486989ae84d43a (4/1)
`11.378, 13.421, 18.488, 15.758, 16.972`

35edbe3d9d3308b31b4c4329cae8ebe22352a6ac (4/24)
`34.864, 33.302, 19.346, 16.767, 14.425`

**Comment by kf6gpe** [comment]
I have no rational explanation for this, but it looks like it may have improved recently, reading through the missing benchmark entries --- will keep an eye on them through next week's triage and see where it ends up.

![Screen Shot 2020-05-11 at 2 38 39 PM](https://user-images.githubusercontent.com/1435716/81614617-29dd4a80-9395-11ea-9ff7-13d182cddcb8.png)

**Comment by kf6gpe** [comment]
It's back mostly in the red: 
![Screen Shot 2020-05-18 at 8 55 49 AM](https://user-images.githubusercontent.com/1435716/82233812-67862a00-98e5-11ea-8b2a-8b9021edb493.png)

**Comment by chinmaygarde** [comment]
Triage: Checking again, it seems that a few of the recent runs seem to be green again. The bi-modality of the results makes me unconvinced this is a regression. I am not sure how to account for that in the UI or if we even consider this behavior to be problematic. Assigning P6 to this issue for now but feel free to revise it up and I'll pick this up in the next round.

**Comment by kf6gpe** [comment]
We're back to consistently red again (except for a few missing points). I'm inclined to say that this is a candidate for just re-benchmarking at this point if we don't think the behavior is problematic.

![Screen Shot 2020-06-15 at 2 41 39 PM](https://user-images.githubusercontent.com/1435716/84709040-6cef8800-af16-11ea-94ba-ea9d975e4f91.png)

@liyuqian what do you think?

**Comment by liyuqian** [comment]
I rebaselined the benchmark so it will be easier to check the dashboard and find future regressions (it's now green, and a new red would signal a new regression where we shall file another issue).

For this issue, I think we should still keep it open because either our code, or some changes in our devicelab made the benchmark number worse. We should still figure out why, but it probably doesn't have a high priority as Chinmay suggested.

**Comment by kf6gpe** [comment]
This is trending towards being mostly red again; bumping priority.

**Comment by chinmaygarde** [comment]
This still looks bimodal. I suggest re-baselining.

**Comment by chinmaygarde** [comment]
cc @flar

**Comment by chinmaygarde** [comment]
This seems to have been resolved.

**Comment by flar** [comment]
How is this resolved? It was briefly less red a few days ago, but it is still just as choppy as it has been for months and it is much worse than it was back in February overall...

<img width="999" alt="Screen Shot 2020-08-31 at 11 56 59 AM" src="https://user-images.githubusercontent.com/50503328/91756134-1c84df80-eb81-11ea-8f0e-d78a20ffc7be.png">
