### ISSUE TITLE
Benchmark end to end Hot Refresh time

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5057]
We're finishing up Hot Refresh workflow. We'd like to add an end-to-end benchmark, displayed on our dashboard, that measures the cycle. We have quarterly goals w.r.t. cycle time, and we'd like to ensure we don't regress.

I think of measuring hot reload something like:

* Developer hits 'r' in Flutter tools, to signal they want to reload.
* Frame is drawn on the device (android and ios).

The total time between when the developer signals they want a reload, and when they can see the effect of that change on the device.

We can assume:

* the APK has been built and uploaded to the device
* the initial set of source has been sent to the device
* the app is up and running on the device
* the app is running in checked/debug/development mode

**Comment by sethladd** [comment]
cc @johnmccutchan @yjbanov

**Comment by Hixie** [comment]
When measuring this, we need to make sure we measure the time until the next actual frame, and not the time til the next paint, because part of reassembling the app is to trigger a preemptive paint that doesn't actually update the display.

**Comment by johnmccutchan** [comment]
@yjbanov Can the benchmarking harness differentiate between the preemptive paint and an actual frame?

**Comment by yjbanov** [comment]
There is no benchmarking harness in the traditional sense. A Flutter benchmark today is simply an integration test that runs in `--profile` mode and extracts the timeline when it's done. Depending on what is being measured an appropriate script is used to analyze the contents of the timeline and report metrics. To measure hot reload I imagine we could emit custom events into the timeline and write a script that extracts the metrics from it.

**Comment by johnmccutchan** [comment]
This is blocked on https://github.com/flutter/flutter/issues/5245

**Comment by johnmccutchan** [comment]
Status update- we are running the benchmark on the bots. But I'm waiting on @yjbanov to get the graphs up on the display.

**Comment by sethladd** [comment]
Thanks for the update! Assigning over to @yjbanov

**Comment by yjbanov** [comment]
Fixed.

<img width="460" alt="screen shot 2016-09-28 at 6 12 29 pm" src="https://cloud.githubusercontent.com/assets/211513/18937663/27490b10-85a7-11e6-9780-de4cc4b54b71.png">
