### ISSUE TITLE
HomeKit Delegate APIs not working inside iOS flutter plugin

### ISSUE THREAD

**Issue by Sathish-Kotturu** [flutter/flutter#50573]
I am developing a flutter plugin for accessing Apple HomeKit features inside my flutter app. The following project and code setup is done for iOS project inside flutter folder:

**Project setup:** 1. Enabled HomeKit in Capabilities 2. Added Privacy – HomeKit Usage Description Key in Info.plist

**Code Setup inside plugin**: 1. Created instance of HMHomeManager 2. Set the HMHomeManager delegate 3. Implemented delegate methods

Also, cross verified the access to HomeKit for my flutter app in the Settings.

**Issue 1**: For the same set up, a native iOS application is running fine and `homeManagerDidUpdateHomes` delegate method is getting called immediately after accessing HomeKit Database which is properly providing Home information. But, in flutter plugin, delegate method is not getting called and always home count is Zero.

**Issue2**: I have written code to add new HomeKit Home inside iOS plugin and tried calling the method from flutter UI. Strangely the code inside `addHome(withName: )` block is not executing but Home is getting created inside HomeKit database. This is confirmed by running Apple ‘Home’ app. In this case also, `homeManager(didAdd home: )` delegate method is not called.

**Version details**: Xcode: 11.2, swift 4.2 Flutter: 1.14.6, Dart: 2.8.0

Does any other set up is required in flutter plugin to set HomeKit Delegate?

As an alternative approach, also tried using cupertino_ffi_generated 0.1.1 (https://pub.dev/packages/cupertino_ffi_generated) which is a recent package from flutter for accessing Apple APIs. (Even though it is directly mentioned: “**Most Flutter developers should not use this package**. It's almost always a better idea to write a Flutter plugin than use this package.” ). But, flutter throwing an error ‘Target of URI doesn't exist:’

**Version details**: Flutter: 1.14.6, Dart: 2.8.0

**Comment by goderbauer** [comment]
Unfortunately we're not able to provide support for individual questions on our issue tracker, but asking on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) is likely to get answers much more quickly. The community support scales far better than the development team does, and several Flutter committers keep an eye out for questions when they've got time as well. We encourage you to read about StackOverflow's guide on [writing a good question](https://stackoverflow.com/help/minimal-reproducible-example).
