### ISSUE TITLE
How do I listen to backspace/ delete key (from the on screen keyboard) on an empty TextField?

### ISSUE THREAD

**Issue by sanifhimani** [flutter/flutter#50587]
I have a textfield and I want to know if the user presses the delete button on his keyboard (on screen not raw or external). I tried using onChanged property and it works fine when there's already some text in it. But when the textfield's empty with no text, how do I detect if delete or backspace is pressed?

Thank you.

**Comment by slightfoot** [comment]
I have needed this feature on at least 3 separate occasions.

**Comment by hongeSunCoder** [comment]
also needs that

**Comment by ayush221b** [comment]
I need this too. Is there any update on this?

**Comment by sanifhimani** [comment]
No update yet.

**Comment by a43mrk** [comment]
I need this too ha!

**Comment by pedromassangocode** [comment]
Hi @sanifhimani 
I see there's an open issue (https://github.com/flutter/flutter/issues/14809) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by hyouuu** [comment]
I found a way to check on backspace event - need to specify platform to check for keyCode and this example is for Android. Hope it helps someone.

```
RawKeyboardListener(
  child: TextField(controller: co, ...),
  focusNode: FocusNode(),
  onKey: (RawKeyEvent event) {
    if (event.data is RawKeyEventDataAndroid) {
      final data = event.data as RawKeyEventDataAndroid;
      if (data.keyCode == 67 && co.text.isEmpty) {
        onBackspaceOnEmpty();
      }
    }
  },
)
```
