### ISSUE TITLE
A way to bring a minimized flutter app to foreground

### ISSUE THREAD

**Issue by mhdabiri** [flutter/flutter#50588]
how can I Navigate to a new screen and popup application from background service when app is invisible ?

I know how easy it is to navigate from one route to another in Flutter. We just need to do push and pop but Want to bring my app foreground based on server data i'm running background job for updating user location, Read the documentation but nothing explains how to bring Flutter app to foreground even if mobile screen is off or my flutter app is in background :)?

i dont have any way for long time ...

**Comment by VladyslavBondarenko** [comment]
Dublicate of https://github.com/flutter/flutter/issues/43478

I'm not sure is it possible, but you can generate a push notification to tell the user to bring the application to foreground

**Comment by goderbauer** [comment]
Closing as duplicate per previous comment.
