### ISSUE TITLE
Remove chrome platform from `flutter test`

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#50594]
Early in the web support phase, I added support for directly testing in a chrome browser for a simulated test environment. This may have proved useful in helping the web bootstrap, but long-term it does not present a very compelling test environment. Since it doesn't actually perform rendering/painting it only really tests the interface between the engine and framework. Compared to actual integration tests on real browsers, it is of limited use for ensuring correctness. In addition, these tests are highly flaky on CI due to in part to the orchestration complexity.

Unfortunately it also adds a lot of dependencies to the flutter tool. This was acceptable since we needed them anyway for `flutter run`. When we move to the frontend_server, many of these dependencies are no longer needed though. Notably, the build_runner dependency is one of two transitive mirrors dependencies that prevents an AOT built tool

I propose that in the short-term, we remove support for `flutter test --platform=chrome` from the tool into a special purpose command in `dev/bots/`. This would still be usable for the framework CI, but would no longer be accessible for the tool.

@nturgut @yjbanov @zanderso 

EDIT:

@yjbanov @Piinks, are there any implications for web goldens?

@mehmetf @chingjun, is this code used in google3 at all?

**Comment by collinjackson** [comment]
SGTM

@ditman yes, I think this removal doesn't interfere with the short-term roadmap for web plugin integration testing since we are using `flutter run` or `flutter drive` to launch those tests.

In the long term I'd like to see something like `flutter test -d chrome` ... debuggable integration testing on real devices. Here's a related issue for that: https://github.com/flutter/flutter/issues/29401

**Comment by jonahwilliams** [comment]
Thanks @collinjackson and @ditman !

**Comment by nturgut** [comment]
All fine with new web engine integration testing. Thanks for notifying!

**Comment by chingjun** [comment]
The `package:flutter_tools` part of it is not being used internally, but the support in `package:flutter_test` is. I assume that the changes you proposed does not affect `package:flutter_test`. If so then removing that shouldn't affect our internal tests.

**Comment by jonahwilliams** [comment]
This would preserve all of the flutter_test changes

**Comment by Piinks** [comment]
As I understand it, I don't think this would impact golden file testing. IIRC, web goldens have been pretty flaky and most of them are still disabled, @chingjun might be able to speak more on that. If we need to make a change as a result of this, it might be for the better. :)

**Comment by ditman** [comment]
QQ I just found myself doing `fluter test --platform chrome` to run [these tests](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_web/test/write_batch_web_test.dart#L5); 

What kind of changes will we have to do to those tests to run them after this gets merged?

**Comment by yjbanov** [comment]
SGTM. @ditman since these tests are run only by Flutter contributors we can add this functionality to `felt` (or a new tool so one doesn't need to have a checkout of the engine repo).

**Comment by ditman** [comment]
OK, I'll keep an eye to the required changes to migrate the tests ASAP (or add instructions). Thanks!

**Comment by collinjackson** [comment]
After looking more closely at this, https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_web/test/write_batch_web_test.dart#L5 is a plugins unit test and it would be good to have a way to keep that working for non-Flutter contributors.

**Comment by yjbanov** [comment]
@collinjackson just pointed out that the test you linked to is not a Flutter framework test. So I was wrong. Flutter contributors are not the only ones using it. So we need to be more careful about this change.

**Comment by jonahwilliams** [comment]
I certainly wouldn't _just_ remove it, we would end up with a deprecation period or at worst a shell redirect to dev. That said, we need to be transparent about the level of support for this command - I don't anticipate doing any further work on it in 2020, and there are a large number of issues with it

**Comment by jonahwilliams** [comment]
There is _another_ option here, which would be to rewrite the command to use the frontend_server instead of build_runner, which would alleviate the flutter_tools dependency issue. it doesn't change the support issue, nor the tools' current priorities.

I could advise on the design and code review, if someone else wanted to take up the implementation work.

**Comment by yjbanov** [comment]
Optimistically putting it in the near-term milestone, but feel free to adjust.
