### ISSUE TITLE
RawKeyboardListener not receiving RawKeyDownEvent from WidgetTester.sendKeyEvent

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#50598]
I am writing a flutter widget test for a widget that contains a RawKeyboardEventListener.

The listener does not receive a RawKeyDownEvent event on:
`await tester.sendKeyDownEvent(LogicalKeyboardKey.keyW);`

The listener receives a RawKeyUpEvent but not a RawKeyDownEvent on:
`await tester.sendKeyEvent(LogicalKeyboardKey.keyW);`

The listener is WAI and receives a RawKeyUpEvent on:
`await tester.sendKeyUpEvent(LogicalKeyboardKey.keyW);`

**Comment by kenzieschmoll** [comment]
This issue was resolved by calling `await tester.pumpAndSettle()` after `focusNode.requestFocus()`.

**Comment by GaneshSingaravelu** [comment]
Hi Kenzieschmoll,
I am also facing the same problem. Can you please share your code for RawKeyDownEvent
