### ISSUE TITLE
flutter application crash with no error in log when receive push notification FCM

### ISSUE THREAD

**Issue by whochetansuthar** [flutter/flutter#50592]
my application crash when it get cloud notification from FCM, only i did is print the firebase message data on console for debut but it crash the app when receives the  notification without any error in log console
my dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+3
  url_launcher: ^5.4.1
  line_icons: ^0.2.0
  photo_view: ^0.9.1
  cached_network_image: ^2.0.0
  connectivity: ^0.4.6+2
  firebase_messaging: ^6.0.9
  #firebase_core: ^0.4.0
  flutter_full_pdf_viewer: ^1.0.6
  #firebase_auth: ^0.11.1+6
  #cloud_firestore: ^0.12.5

my code in main.dart

import 'package:flutter/material.dart';
import 'home.dart';
import 'Components/connection.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
FirebaseMessaging firebaseMessaging = new FirebaseMessaging();

void main() {
       runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  
  @override
  void initState() {
    super.initState();
     firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) async {
          print("onMessage: $message");
        },
        onLaunch: (Map<String, dynamic> message) async {
          print("onLaunch: $message");
        },
        onResume: (Map<String, dynamic> message) async {
          print("onResume: $message");
        },
      );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        fontFamily: 'Raleway',
      ),
      home: Home(),
    );
  }
}

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.10586], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.42.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

Dependency in build.gradle

classpath 'com.google.gms:google-services:4.3.3'

In android/app/build.gradle
apply plugin: 'com.google.gms.google-services'

i also added intent filter in androidManifest.xml
tried flutter clean and uninstalling application.
i did all step correctly don't  know why its crashing.
please help

**Comment by VladyslavBondarenko** [comment]
Hi @whochetansuthar 
Please open the issue in the [FlutterFire github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
