### ISSUE TITLE
Extension method appears to be broken on new projects

### ISSUE THREAD

**Issue by wilburt** [flutter/flutter#50608]
For some reason, extension methods refused to work on a new Flutter project I created.

**extensions.dart**
```
extension MyBuildContext on BuildContext {
  TextTheme get textTheme => Theme.of(this).textTheme;
  ButtonThemeData get buttonTheme => Theme.of(this).buttonTheme;
}
```
--------

**another_file.dart**
```
import 'package:blah/blah/extensions.dart';
...
@override
  Widget build(BuildContext context) {
    return Text(
      title,
      style: context.textTheme.subtitle2,
    );
  }
```
`textTheme` from  line `style: context.textTheme.subtitle2` is underlined with this error: 

> The getter 'textTheme' isn't defined for the type 'BuildContext'.

However, if I copy the extension methods from  **extensions.dart** to **another_file.dart**, it works with no error.

Additionally, if I copy the same files to an older project, it works with no error too.

------

**Flutter Doctor**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v1.15.0, on Mac OS X 10.15.3 19D76, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)
> [!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.41.1)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
>

**Comment by TahaTesser** [comment]
Hi @wilburt

**Comment by TahaTesser** [comment]
Hi @wilburt 
Can you please confirm you have min sdk set `>=2.6.0`
```
environment:
  sdk: ">=2.6.0 <3.0.0"
```
Thank you

**Comment by wilburt** [comment]
I already did that. As a matter of fact, I even tried:

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

**Comment by TahaTesser** [comment]
Hi @wilburt 
Can you please check your import 
I have tested as follows, seems to work fine
```
import 'package:flutter/material.dart';
import 'blah/blah/extensions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text(
              'TEXT',
              style: context.textTheme.subtitle2,
            ),
          ),
        ),
      ),
    );
  }
}
```
Thank you

**Comment by wilburt** [comment]
I mistakenly created two **extension.dart**  files in two separate directories and I was busy importing the wrong one 🤦🏽‍♂️

Thanks for pointing me in the right direction.

**Comment by ayRatul** [comment]
I can confirm the behaviour is still there. It's only doing it in libraries/plugins. So importing a local .dart file doesn't trigger the behaviour, but using a library that uses named extensions gives the message "The getter...  isn't defined for the type ...".

Here is my flutter version: However with previous versions is the same. 

- Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [VersiÃ³n 10.0.18362.239], locale es-ES)
