### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/videos/vid.mp4, null)

### ISSUE THREAD

**Issue by samuelezedi** [flutter/flutter#50601]
Hello guys, I have been battling with this all day and can't seem to get through. Please anyone with a solution

```PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/videos/vid.mp4, null).

Please help me out
VideoPlayerController _videoPlayerController;
  Future<void> futureController;
  var videoFile = "assets/videos/vid.mp4";

  @override
  void initState() {
    _videoPlayerController = VideoPlayerController.asset(videoFile);
    futureController = _videoPlayerController.initialize();
    _videoPlayerController.setLooping(true);
    _videoPlayerController.setVolume(1.0);
    super.initState();
  }

**Comment by samweldi** [comment]
VideoPlayerController _videoPlayerController;
   Future<void> futureController;
   var videoFile = "assets/videos/vid.mp4";

   @override
    void initState() {
    _videoPlayerController = VideoPlayerController.asset(videoFile);
    futureController = _videoPlayerController.initialize();
     _videoPlayerController.setLooping(true);
     _videoPlayerController.setVolume(1.0);
     super.initState();
   }

**Comment by VladyslavBondarenko** [comment]
Hi @samweldi 
The error says that can't find needed asset.
Have you added assets to your `pubspec.yaml`, get packages anew and rerun your app?

**Comment by samweldi** [comment]
yes I have added it

**Comment by samweldi** [comment]
assets:
    - assets/images/cover_2.jpg
    - assets/images/fansalone_fav.png
    - assets/images/fansalone_logo.png
    - assets/images/default_user.png
    - assets/images/default_cover.png
    - assets/images/logo_main.png
    - assets/images/logo_main_fav.png
    - assets/images/logo.jpg
    - assets/videos/vid.mp4


thats it, properly added

**Comment by VladyslavBondarenko** [comment]
@samweldi 
I don't have any problem with it. 
Have you run `flutter pub get` after changing `pubspec.yaml`?
Have you run your app anew after getting the assets?
Does the file exist `assets/videos/vid.mp4`?

**Comment by Silerqin** [comment]
Did you solve the error?

**Comment by PabloG6** [comment]
Having the same issue, except i'm recording the video right now.

**Comment by samuelezedi** [comment]
I solved the issue, All I had to do was restart the app

**Comment by PabloG6** [comment]
> I solved the issue, All I had to do was restart the app
Didn't fix my problem. I restarted the app and uninstalled and reinstalled the app. The problem persists

**Comment by darshankawar** [comment]
Hi @samuelezedi,
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it.
Thank you

@PabloG6, I'd suggest to file a new issue for the problem you are facing with all required information (flutter doctor -v, flutter run --verbose, pubspec.yaml) since the issue may not be the same (per your comment you were trying to record a video)

**Comment by spideyduulr** [comment]
> > I solved the issue, All I had to do was restart the app
> 
> Didn't fix my problem. I restarted the app and uninstalled and reinstalled the app. The problem persists

This is not a valid fix. I still have this issue happening randomly while using the app. But I cannot tell exactly why is it happening.

**Comment by spideyduulr** [comment]
E/flutter (25498): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [320, 568, -1.0], [-1, -1]), null)

**Comment by darshankawar** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by khanna007** [comment]
@darshankawar  I am facing this problem . I am using VideoPlayerController.network which gives me this error
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream., null)

In my case the video is coming from s3 

As i noticed that if there is direct url for the video it will run but if there is something medium for url then it will show this error
Please any one help me in this issue

**Comment by Amerr** [comment]
@khanna007 What do you mean by `something medium for the url`.

**Comment by khanna007** [comment]
@Amerr it means that my video is stored in s3 and i want to show my video so s3 is my medium .
So i solved this error 
Future<String> load_path_video() async {
    loading = true;
    final Directory extDir = await getApplicationDocumentsDirectory();

    setState(() {
      dirPath = '${widget.videoResponse}';
      
      loading = false;
    });
  }
call load_path_video(); initsate

NetworkPlayerLifeCycle(
                          '$dirPath', 
                          (BuildContext context,
                                  VideoPlayerController controller) =>
                              AspectRatioVideo(controller)),

**Comment by Amerr** [comment]
I am facing the same issue since my video is served also from s3

**Comment by khanna007** [comment]
@Amerr  use the above code it will run

**Comment by MohamadOsama17** [comment]
@khanna007  can you explain more please?
