### ISSUE TITLE
flutter upgrade makes a misstake at build_value package! 

### ISSUE THREAD

**Issue by YugeCse** [flutter/flutter#50615]
flutter upgrade
Building flutter tool...
Running pub upgrade...
Because flutter_tools depends on built_value 7.0.9 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

I use the dev channel,   after I execute the command "flutter upgrade".

**Comment by huhuang03** [comment]
Same error. command `flutter pub upgrade -v`, cause

```
Building flutter tool...
Because flutter_tools depends on built_value 7.0.9 which doesn't match any versions, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by kobewang** [comment]
Same problem .use dev channel in china after  command :flutter upgrade

**Comment by jmagman** [comment]
https://pub.flutter-io.cn is maintained by GDG China.  I would contact them about any mirroring issues.  
\cc @chenglu

Closing, there's no work to do in the Flutter repo here.

**Comment by chenglu** [comment]
Fixed, thanks!
