### ISSUE TITLE
Natively support a date range picker

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#50618]
## Use case

Date pickers are great, but sometimes users need to pick a _range_ of dates spanning days, weeks, months, or even years. 

It avoids having to use two fields like so:

![Screenshot from 2020-02-11 20-55-58](https://user-images.githubusercontent.com/25782944/74296121-f98ffc80-4d10-11ea-97ae-850a881e7b9a.png)
(_Yes I know it's the same date! It's just to show the two fields._)

Why would you use _two_ fields when you could use just _one_?

## Proposal

There's packages for date range pickers (https://pub.dev/packages/date_range_picker, https://pub.dev/packages/flutter_date_pickers) but it's not *official* and it's a part of the [material design specifications](https://material.io/components/pickers/#anatomy). Android has this functionality so should Flutter. This should be natively supported in Flutter and as far as I can tell, it isn't.

![](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1579302979877%2Fassets%2F13hURY0XomgSTbPkhzifBGMVVQGz8V7--%2Fpicker-elements-range.png)
(Source: [Pickers](https://material.io/components/pickers/#anatomy))

**Comment by TahaTesser** [comment]
Hi @Reprevise 
Closing this issue as there is already duplicate [#50133](https://github.com/flutter/flutter/issues/50133) 
Thank you for contribution

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by Reprevise** [comment]
Related PR: https://github.com/flutter/flutter/pull/50546
