### ISSUE TITLE
Shared Preferences plugin has deprecated code usage

### ISSUE THREAD

**Issue by behnamsattar** [flutter/flutter#50619]
Here is the warning I receive when building for Android on latest version of SharedPreferences plugin (0.5.6+1) to date.

```
warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
```

**Comment by TahaTesser** [comment]
Hi @behnamsattar 
As this is related to [#44569](https://github.com/flutter/flutter/issues/44569)
This isn't an error and just "deliberate and temporary." warning

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by behnamsattar** [comment]
@TahaTesser Thanks for the link, it all make sense now.
