### ISSUE TITLE
[fuchsia] Rework Vulkan surface pool and retained surfaces on Fuchsia

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#50617]
Currently the logic is more involved than it needs to be and leads to problems like: https://github.com/flutter/flutter/issues/50011

**Comment by iskakaushik** [comment]
Un-assigning myself as this is no longer a priority given the potential embedder api migration.

**Comment by arbreng** [comment]
Closing this as the retained surfaces are getting in the way of the embedder migration, so I'm going to remove them as dead code
