### ISSUE TITLE
TextField: cursor constantly jumps to start when typing

### ISSUE THREAD

**Issue by ValeriusGC** [flutter/flutter#50627]
After last Flutter updating i got trouble with TextField:
cursor constantly jumps to start when typing.
When degrading to v.14.0 - all is OK.
```
- OS: Ubuntu 18.04
- Dart VM version: 2.7.1 (Unknown timestamp) on "linux_x64"
- flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.15.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment]
Could be related to [#50563](https://github.com/flutter/flutter/issues/50563)

**Comment by HansMuller** [comment]
It would help if you could provide a small self-contained app that demonstrates the problem, and let us know if #50563 (per https://github.com/flutter/flutter/issues/50627#issuecomment-585077116) demos the problem you're seeing.  Thanks!

**Comment by ValeriusGC** [comment]
Hi there.
This morning i returned on `stable` to emulate error and i see the issue is fixed with last hotfix. 
Anyway i could not reproduce it neither on emulator nor on device.

**Comment by justinmc** [comment]
Sounds like this can be closed, but let me know if this comes up again!
