### ISSUE TITLE
Type 'CupertinoPageRoute<dynamic>' should be 'CupertinoPageRoute<bool>' to implement expected type 'Route<bool>'

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#50629]
```dart
Route<T> onGenerateRoute<T>(RouteSettings settings) {
    return CupertinoPageRoute<T>(
        settings: settings,
        builder: (BuildContext context) => Container();
    );
}
```
If set this onGenerateRoute in MaterialApp/WidgetsApp, can't use `Navigator.of(context).pushNamed<bool>('xxx');` 
because onGenerateRoute return a CupertinoPageRoute\<dynamic\>. I think this issue caused by WidgetsApp _onGenerateRoute function, it return Route\<dynamic\> and make the T is dynamic

**Comment by TahaTesser** [comment]
Hi @windrunner414 
Please look at this comment for the reason 'CupertinoPageRoute<dynamic>' is dynamic and not 'CupertinoPageRoute<bool>'   [stackoverflow comment](https://stackoverflow.com/questions/54931283/named-route-navigation-error-type-materialpageroutedynamic-is-not-a-subtype#comment103788529_54931719)
Let us know if this clears your doubt.
Thank you

**Comment by windrunner414** [comment]
@TahaTesser it's not my issue. I set onGenerateRoute and use generics.

**Comment by windrunner414** [comment]
@HansMuller I think it's not about cupertino.
In fact, I'm confused about why WidgetsApp._onGenerateRoute return Route\<dynamic\> not Route\<T\>, it causes the onGenerateRoute I set can't use generic

**Comment by chunhtai** [comment]
mini repo
```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
void main() {
  runApp(MyApp());
}

Route<T> onGenerateRoute<T>(RouteSettings settings) {
  return CupertinoPageRoute<T>(
    settings: settings,
    builder: (BuildContext context) => Container()
  );
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,
      ),
      onGenerateRoute: onGenerateRoute,
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      Navigator.of(context).pushNamed<bool>('xxx');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by chunhtai** [comment]
A workaround will be use 
```dart
Navigator.of(context).pushNamed<dynamic>('xxx');
```

**Comment by chunhtai** [comment]
I found that interesting that we allow
```dart
final dynamic d = false;
final bool c = d as bool;
```
but we don't allow
```dart
class A<T> {
  A();
}
class B<C> extends A<C> {
}

final B<dynamic> b = B<dynamic>();
final A<bool> a = b as A<bool>;
```

**Comment by windrunner414** [comment]
@chunhtai yes, I use (await Navigator.of(context).pushNamed('xxx')) as bool

**Comment by AlexVincent525** [comment]
> I found that interesting that we allow
> 
> ```dart
> final dynamic d = false;
> final bool c = d as bool;
> ```
> 
> but we don't allow
> 
> ```dart
> class A<T> {
>   A();
> }
> class B<C> extends A<C> {
> }
> 
> final B<dynamic> b = B<dynamic>();
> final A<bool> a = b as A<bool>;
> ```

And this is another wordaround.

```Dart
T asT<T>(
  value, {
  T defaultValue
}) {
  if (value is T) {
    return value;
  }
  return defaultValue;
}
```

**Comment by goderbauer** [comment]
In the mini-repro the issue goes away when the onGenerateRoute implementation is replaced with:

```dart
Route onGenerateRoute(RouteSettings settings) {
  if (settings.name == 'xxx') {
    return CupertinoPageRoute<bool>(
        settings: settings,
        builder: (BuildContext context) => Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              Navigator.of(context).pop(true);
            },
          )
        )
    );
  }
  throw 'Not a valid route';
}
```

(notice the typing of CupertinoPageRoute). This seems reasonable to me: If you expect that pushing route `xxx` returns a bool, well, then onGenerateRoute should return a Route that's correctly typed with that.

**Comment by AlexVincent525** [comment]
(Currently not working, will be AFK for 1 or 2 days.)

**Comment by AlexV525** [comment]
Based on the discussion in #53390, we don't have a recent plan to update the `onGenerateRoute` to respect the generic type. So closing as it won't be fixed.
