### ISSUE TITLE
Application is working in Debug mode but not in release mode

### ISSUE THREAD

**Issue by itsmebrp** [flutter/flutter#50625]
I am using package:http/http.dart package to fetch the data. I get the data in debug mode but not in release mode.

Future<List<Product>> _mostSoldProduct() async {
    var apiUrl =
    "www.mostsoldproducts.com/products.json";
    var product = await http.get(apiUrl);
    var jsonData = json.decode(product.body);

    List<Product> listof = [];
    for (var i in jsonData) {
      Product pro = Product(
          int.parse(i["p_id"]),
          i["p_name"],
          0,
          double.parse(i["p_cutprice"]),
          double.parse(i["p_sprice"]),
          i["p_mainimage"],
          i["p_shortintro"],
          i["p_remarks"],
          );
      listof.add(pro);
    }
    return listof;
  }

**Comment by TahaTesser** [comment]
Hi @itsmebrp 
Can you please confirm you have Internet permission if you're testing on Android? 
If not please add Internet permission in your Android Manifest [Solution](https://stackoverflow.com/a/2378619)
Thank you

**Comment by Migue28** [comment]
Add in your android/app/src/main/AndroidManifest.xml

...
<uses-permission android:name="android.permission.INTERNET" />
...

**Comment by itsmebrp** [comment]
Thank you problem is now solved.
