### ISSUE TITLE
Flutter slider with custom increment/decrement value

### ISSUE THREAD

**Issue by serpentarius-hollow** [flutter/flutter#50621]
## Use case

I have a slider for adjusting the price of product, ex: slider with min value `43855048` and max value `127300000` and I need to the slider to be able to increase/decrease with increment of `100000`. This is giving me trouble because there's no option in slider to do that. If I use `divisions` then the value of `divisions` would be `= (127300000 - 43855048) / 100000` which is a float type.

## Proposal

My proposal is to add the ability to increase/decrease the slider value with custom value

**Comment by InvincibleZeal** [comment]
Can't you do something like 

```dart
double min = 43855048;
double max = 127300000;

Slider(
  value: _value,
  min: min,
  max: max,
  divisions: (max - min) ~/ 100000,
  onChanged: (value) {
    setState(() => _value = value);
  },
)
```

The `~/` divides and truncates the fractional part.

**Comment by serpentarius-hollow** [comment]
No, that's not what I want. 

I want it to be uniformed, eg:
43,855,048 >> increment 1,000,000 >> 44,855,048 >> increment 1,000,000 >> 45,855,048 

Your solution is just rounding the division to make the number whole.

Here's what I *think* it should do when it increases:

`if (val <= (max - 1000000)) {
        val = val + 1000000;
      } else if ((max - 1000000) < val && val <= max) {
        val = max;
      }`
