### ISSUE TITLE
fontWeight is ignored on iOS

### ISSUE THREAD

**Issue by m-j-g** [flutter/flutter#50637]
Using the default font, changing the font weight has no change on iOS.  FontWeight.w100 is the same as FontWeight.w900 .  Works fine on Android.  Seems that an old bug has been reintroduced:
https://github.com/flutter/flutter/issues/16853

**Comment by m-j-g** [comment]
duplicate https://github.com/flutter/flutter/issues/49492

**Comment by AEYOU** [comment]
I had the same problem. No changes from w100 to w900 can be observed on iOS.
