### ISSUE TITLE
no object passed  when an event occur in any flutter widget 

### ISSUE THREAD

**Issue by lionviskame** [flutter/flutter#50634]
i have noticed  that there is  no object (widget in current state) passed when an event occur in any flutter widget .
if we take this example 
```dart
class _FavoriteWidgetState extends State<FavoriteWidget> {
  // ···
  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          padding: EdgeInsets.all(0),
          child: IconButton(
            icon: (_isFavorited ? Icon(Icons.star) : Icon(Icons.star_border)),
            color: Colors.red[500],
           onPressed: (){//some work}
          ),
        ),
        SizedBox(
          width: 18,
          child: Container(
            child: Text('$_favoriteCount'),
          ),
        ),
      ],
    );
  }
}
```
**we** notice "onPressed" within "IconButton" widget doesn't have a function  signature that allow the object(widget in the current state) to be passed as argument like java(native android app) or c#(winforms) did  , that would be hell for dynamic widget generation or some generic logic. it would be very nice if you take this as a new feature or fix . thx

**Comment by goderbauer** [comment]
Not sure why you need it, but you could just call another function from the onPressed handler and pass it the current widget state (`this`):

```dart
        Container(
          padding: EdgeInsets.all(0),
          child: IconButton(
            icon: (_isFavorited ? Icon(Icons.star) : Icon(Icons.star_border)),
            color: Colors.red[500],
           onPressed: (){
             yourFunction(this); // <--
           }
          ),
        ),
```

Does that work for you? What more would you need? And for what use case?

**Comment by lionviskame** [comment]
thx for the response , i try that but the "this" return the parent object of "Container "which is in our case
_FavoriteWidgetState ;

**Comment by goderbauer** [comment]
You can pass whatever you want in there. It doesn't have to be `this`.

Also, why do you need this? What is the use case?

**Comment by lionviskame** [comment]
> You can pass whatever you want in there. It doesn't have to be `this`.
the problem is not `this `, what i realy want is some thing similar to this:
 ```
onPressed: (IconButton object){
             //some code
           }
```



> why do you need this? What is the use case?
this example is not my case i just copy it from flutter documentation for demonstration
my case is  the folowing 
```
Container(
          padding: EdgeInsets.all(32),
         child:  Column(
        children: <Widget>[
          for (Category i in allCategories )
         SwitchListTile(
           key: Key(i.id.toString()),
          activeColor: Colors.amber,
           activeTrackColor: Colors.red,
           inactiveTrackColor: Colors.blueAccent,
           title: Text(i.titre,style: TextStyle(color: Colors.white),),
          value: _value,
          onChanged:(bool value){
            // some code
          },
           ),
        ],
      ),
    )
```
i generate a dynamic widget list base on a object List (allCategories), and each widget in the widget List has a key which i need it to do my logic in the onChanged method , what i want is some thing similar to this .

```
onChanged:(SwitchListTile value){
            // some code
          },
```

**Comment by zggoogle** [comment]
Thanks for your question lionviskame , I have the same problem ..

**Comment by goderbauer** [comment]
I am going to close this as there are ways around this as described in my previous comments.
