### ISSUE TITLE
[web] app crashes after hitting url directly in browser

### ISSUE THREAD

**Issue by imnikhilp** [flutter/flutter#50639]
## Steps to Reproduce

1. Add two named routes to app using "routes" property of MaterialApp class.
2. Add two button to each widget.on click of button navigate between screens
3. Navigation works with button click but if you hit url directly in browser or refresh the page then app crashed.It will not work with bookmarked pages.

```
**Exception**
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/product"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

** Code **

```
// my app widget
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo!!!',
      home: Home(),
      routes: {'home': (_) => Home(), 'product': (_) => Product()},
    );
  }
}

// product widget

class Product extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: <Widget>[
          Text('Product'),
          FlatButton(
              onPressed: () {
                Navigator.pushNamed(
                  context,
                  'home',
                );
              },
              child: Text('click'))
        ],
      ),
    );
  }
}

// home widget
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: <Widget>[
          Text('Home'),
          FlatButton(
              onPressed: () {
                Navigator.pushNamed(
                  context,
                  'product',
                );
              },
              child: Text('click'))
        ],
      ),
    );
  }
}
```

**Comment by yjbanov** [comment]
I think it's because the framework expects a slash in your route name, e.g. "/product", but in your `routes` configuration you don't includes slashes. Having said that, perhaps we should handle this better, so I'll schedule this for a review in the near term.

**Comment by imnikhilp** [comment]
@yjbanov with route name "/product", it works.

**Comment by mdebbar** [comment]
@imnikhilp I'm planning to look into this today. There are 2 areas that might be causing this issue:

1. The web engine prepends "/" to the path in some cases.
2. The flutter Navigator slices the initial route name using slashes, and I need to check if that logic works or not when there's no leading slash.

**Comment by thasmin** [comment]
I am getting this error except I do have a slash in front of my route name.
```
      routes: {
        "/": (context) => HomePage(),
        "/teams": (context) => HomePage(),
      },
```

This error occurs when the web browser is refreshed when on the /teams page. Adding routes for "teams" and "//teams" doesn't help.
```
Could not navigate to initial route.
The requested route name was: "/teams"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

**Comment by thasmin** [comment]
@mdebbar Were you able to find the problem? Let me know how I can help.

**Comment by flutterdev-vinit** [comment]
Any updates.
