### ISSUE TITLE
[STEPPER] Need to custom margin on vertical stepper

### ISSUE THREAD

**Issue by QuentinSc** [flutter/flutter#50635]
Hello Flutter Team,

I realy need this mini evolution to make beautifuler app

## Proposal
Widget : Stepper
Proposal : be able to custom the margin for vertical stepper

In `stepper.dart`, the margin is hard set.
channel beta, line 552
```
            margin: const EdgeInsetsDirectional.only(
              start: 60.0,
              end: 24.0,
              bottom: 24.0,
```
 We need to be able to send our custom margin.
It seems  very simple with an additional parameter for the widget

Thank you flutter

**Comment by maschad** [comment]
I could look into this
