### ISSUE TITLE
iOS keyboard does not reset TextInputType when selecting different TextFormField.

### ISSUE THREAD

**Issue by Zoki92** [flutter/flutter#50633]
Hello.
I've got an issue with the keyboard on iOS. Whenever I am selecting a different form field the keyboard keeps the previous input state. What I mean by this is that if my last input on the previous field was a number, whenever I click on another field the keyboard stays with the same number input, whilst on Android it resets. I've got specified keyboardType as TextInputType.text on all the fields, got 3 in this case.

I also tried onFieldSubmitted, where I unfocus() the current field focus, and request the next one, in this case it works alright as supposed and resets the keyboard. 

I've been testing this on an iPhone 7 Plus
Software Version 13.3.1

```
import 'package:flutter/material.dart';

class FormView extends StatefulWidget {
  @override
  _FormViewState createState() => _FormViewState();
}

class _FormViewState extends State<FormView> {
  final _formKey = GlobalKey<FormState>();
  FocusNode firstNode = FocusNode();
  FocusNode secondNode = FocusNode();
  FocusNode thirdNode = FocusNode();
  @override
  Widget build(BuildContext context) {
    return Form(
    key: _formKey,
    child: Column(
      children: <Widget>[
        TextFormField(
          focusNode: firstNode,
          keyboardType: TextInputType.text,
        ),
        TextFormField(
          focusNode: secondNode,
          keyboardType: TextInputType.text,
        ),
        TextFormField(
          focusNode: thirdNode,
          keyboardType: TextInputType.text,
        ),
      ],
    ),
  );
}
}
```

**Comment by VladyslavBondarenko** [comment]
Checked with flutter master 1.15.21-pre.36 and iOS 13.3 simulator - it works, keyboard resets.
Seems to be fixed, closing.
@Zoki92 If you disagree or if it persists on real devices, please write in the comments and I will reopen it.
Thank you
