### ISSUE TITLE
How to connect with flutter with client FTP

### ISSUE THREAD

**Issue by jasteeman** [flutter/flutter#50649]
I am new using flutter and I am trying to connect to an FTP service. I was currently testing the ssh flutter package. Although for SSH it connects me well but for FTP I did not succeed. The mistake that constantly throws me is:

Unhandled Exception: PlatformException (connection_failure, java.net.ConnectException: Connection refused, null).

Thank you in advance for your help.

**Comment by cedricgrothues** [comment]
Have a look at [this plugin](https://pub.dev/packages/ftpclient)... That might solve your problem.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
