### ISSUE TITLE
Document changes in hotfixes

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#50665]
It would be nice to know what's included in those hotfix releases. For example v1.12.13+hotfix.8 was released recently, but at least I have not found any information what is included in that hotfix release. There has been the same problem with earlier hotfix releases.

There are now open questions like should I install the hotfix asap and rebuild and republish my production app to improve its stability? Or are there just other fixes not effecting my app.

I have also noticed many times that some specific issue in Flutter (important to me) has already been fixed (issue has been closed), but it has been impossible or at least very difficult to find out if the fix is already available in the latest stable/beta build. Many issues happen only on users' devices so I cannot even try it myself.

Maybe you can already find all this information by spending few hours with git logs etc. but my point is to make this easier.

**Comment by timsneath** [comment]
This is a very insightful piece of feedback, @kinex. We can do more here and we'll build this into the next stable release.

We've created this document in response to this issue: does this help?
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by kinex** [comment]
Thank you very much, that document is exactly what I expected!
