### ISSUE TITLE
google_maps_flutter:The plugin `flutter_plugin_android_lifecycle` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment

### ISSUE THREAD

**Issue by HappyGhostz** [flutter/flutter#50687]
When I add google_maps_flutter: 0.5.22+3 to the pubspec.yaml file, I got this exception.
```
Running "flutter pub get" in flutter_pax...                         2.1s
The plugin `flutter_plugin_android_lifecycle` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0
```

pubspec.yaml  set:

`
version: 1.0.1+1
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.12.13+hotfix.5
`

flutter doctor -v
```
flutter_new doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en)
    • Flutter version 1.12.13+hotfix.5 at /Users/xxx/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @HappyGhostz 
What version of `flutter_plugin_android_lifecycle` do you use?

**Comment by HappyGhostz** [comment]
It is google_maps_flutter that has a dependency on this flutter_plugin_android_lifecycle
[google_maps_flutter](https://pub.dev/packages/google_maps_flutter)

**Comment by HappyGhostz** [comment]
Hi @VladyslavBondarenko , I want to ask if there are any upgrade plans for `flutter_plugin_android_lifecycle`, thank you very much!

**Comment by VladyslavBondarenko** [comment]
@HappyGhostz 
Do you have the error 
when using the newest version of google_maps_flutter 0.5.23+1?
when adding directly flutter_plugin_android_lifecycle 1.0.5 without google_maps_flutter?

I don't have the error (tried with the same flutter version)

**Comment by HappyGhostz** [comment]
Hi @VladyslavBondarenko  
Yes, this is still the exception, whether you use flutter_plugin_android_lifecycle 1.0.5 alone or use the latest version of google_maps_flutter(0.5.23+1).
I will try to find other solutions or other reasons, thank you very much.

**Comment by HappyGhostz** [comment]
this `flutter_plugin_android_lifecycleIs `not adapted to the v2 api, this is my flutter environment,
```
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.12.13+hotfix.5
```

**Comment by HappyGhostz** [comment]
hi, @VladyslavBondarenko   Sorry to call you again, I am adding the following information, this flutter project is to be embedded into the existing android project. This Android project has been moved to androidx.

**Comment by II11II** [comment]
i have the same problem

**Comment by HappyGhostz** [comment]
I did a test, as long as the flutter project is integrated into the existing Androidx project, then the flutter project depends on google_maps_flutter, this will happen

**Comment by HappyGhostz** [comment]
Duplicate of [#47153](https://github.com/flutter/flutter/issues/47153)
