### ISSUE TITLE
Engine roll https://github.com/flutter/flutter/pull/50399 caused a benchmark instability

### ISSUE THREAD

**Issue by flar** [flutter/flutter#50689]
Running the `flutter_gallery_ios32__transition_perf` benchmark on recent builds I started seeing a crash before the benchmark completed:

```
[flutter_gallery_ios32__transition_perf] [STDOUT] stdout: > Animated images@Media
[flutter_gallery_ios32__transition_perf] [STDOUT] stdout: 
[flutter_gallery_ios32__transition_perf] [STDOUT] stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[flutter_gallery_ios32__transition_perf] [STDOUT] stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[flutter_gallery_ios32__transition_perf] [STDOUT] stderr: VMServiceFlutterDriver: tap message is taking a long time to complete...
```

The crash doesn't always happen at the same place in the benchmark, but during the Animated images section is common and most of them are late in the benchmark.

The oldest framework commit that I've been able to reproduce the problem on is https://github.com/flutter/flutter/commit/c388a26131aef1afbd7d56743ecade9d2e8c8ee4 (the engine roll https://github.com/flutter/flutter/pull/50399) and the benchmark is stable on the immediately preceding commit (https://github.com/flutter/flutter/commit/67826bdce54505760fe83b7ead70bdb5af6fe9f2) which is also v1.15.3 as it happens.

**Comment by jmagman** [comment]
Failures and re-runs almost every commit...
<img width="52" alt="Screen Shot 2020-03-26 at 1 03 07 PM" src="https://user-images.githubusercontent.com/682784/77691448-25cea800-6f62-11ea-8e3f-39e058f9345a.png">

Should we turn it off for now?

**Comment by jmagman** [comment]
@liyuqian did you try to fix this while ago with https://github.com/flutter/flutter/pull/36089?  Can you check what regressed?

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/36268.

**Comment by jmagman** [comment]
Actually if I read https://github.com/flutter/flutter/issues/36268 it looks like those are just printed warnings and probably not related to the timeout.  
@flar is this issue just tracking the warning?  Or is it tracking the flakiness of flutter_gallery_ios32__transition_perf?

**Comment by liyuqian** [comment]
@jmagman : PR https://github.com/flutter/flutter/pull/36089 also tries to restore the connection which fixes the timeout. Maybe someone should figure out where the connection is unexpectedly closed and call `await _restorePeerConnectionIfNeeded();` to restore the connection.

**Comment by flar** [comment]
I filed the issue because the benchmark was crashing and not producing output. That was the main issue. The warnings are not just an inconvenience, they mean that the app disappeared out from under the benchmark framework.

**Comment by jmagman** [comment]
Adding TODAY for this flake.  I'm happy to create a new issue to just track the constant devicelab failures if it's determined it's different than @flar's original report and bisect work.

**Comment by flar** [comment]
If you look at the history of the benchmark runs on the dashboard, they got much much better soon after I filed this issue and only recently started having trouble again. As such, I'm not sure that the issues we see TODAY are related to the issues I filed the bug on.

To be clear, it does appear to be flaky right now, it's just that it may be unrelated in cause to the original problem.

**Comment by flar** [comment]
At the time I filed this issue the loss of connection always happened in the last stage at the audio/video transitions. Looking at some recent logs from the devicelab it is recently happening in a number of stages during the benchmark run.

**Comment by jmagman** [comment]
Transferring TODAY to https://github.com/flutter/flutter/issues/53431, sounds like the original benchmark issue based on @flar's bisects may be resolved.
