### ISSUE TITLE
Update fuchsia devices zedboot to 0.7.22

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#50703]
Paving is failing on fuchsia devices because a new version is available:

[31mWARNING: Bootserver version '0.7.22' != remote Zedboot version '0.7.21'. Paving may fail.[0m
2020-02-13 02:29:47 [bootserver.exe.linux-x64] Proceeding with nodename ocean-bats-wick-snub
2020-02-13 02:29:47 [bootserver.exe.linux-x64] Transfer starts
	100%...
2020-02-13 02:29:47 [bootserver.exe.linux-x64] Expected target to be [x64], but found target is [pc]

**Comment by iqbal-asif** [comment]
Has the update happened ? Should this issue be closed ?

**Comment by godofredoc** [comment]
Turns out this was not a problem with infrastructure, but a problem how flutter is using the fuchsia sdk.

The first problem was that zedboot was updated from 0.7.21 which required a manual update of the zedboot to 0.7.22 using the latest code version from 02/13. This didn't fix the problem because a change was submitted to require board name "x64" instead of "pc".

It took us 48 hours to start looking at the correct place and fix the problem by updating flutter engine to the latest version of the sdk. This problem could it be prevented with a more clear communication from fuchsia sdk team notifying everyone using the sdk should update devices to the latest zedboot and the latest fuchsia sdk after the board name was changed.
