### ISSUE TITLE
Gallery, Pesto: FAB is green during transition, then pops to Red

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5070]
Turn on "animate slowly" and you'll see this.

Open gallery, tap into pesto, tap on a recipe.

Notice how the Favorite FAB is green during the transition, then switches to Red.

**Comment by sethladd** [comment]
We might want to do this sooner than later. In landscape, because the transition lasts longer (the fab travels farther), it's much more evident that the fab starts green and then pops to red at the end of the transition.

**Comment by abarth** [comment]
Fixed by https://github.com/flutter/flutter/pull/5182

**Comment by sethladd** [comment]
Thanks :)
