### ISSUE TITLE
[Web] [CanvasKit] Too many active WebGL contexts

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#50719]
Creating many `HtmlElementView` is not currently possible because it will throw the following error:
`Too many active WebGL contexts. Oldest context will be lost.`

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    ui.platformViewRegistry
        .registerViewFactory('xyz', (int viewId) => SpanElement());
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: GridView.count(
        crossAxisCount: 3,
        children: List.generate(
          20,
          (i) => Container(
            color: i.isEven ? Colors.blue : Colors.white,
            child: HtmlElementView(
              viewType: 'xyz',
            ),
          ),
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel master, v1.15.4-pre.51, on Mac OS X 10.15.3 19D76, locale en-CH)
    • Flutter version 1.15.4-pre.51 at /Users/ben/flutter
    • Framework revision dc636069fc (6 hours ago), 2020-02-12 22:22:49 -0800
    • Engine revision e0ebaea590
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.100
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by hterkelsen** [comment]
I think CanvasKit needs to expose [`releaseResourcesAndAbandonContext()`](https://api.skia.org/classGrContext.html#a8bb755add42101c03016108f50eb97a6) on `GrContext` so we can clean up old contexts.

Unfortunately, however, it looks like most browsers only allow a maximum of 8 or 16 WebGL contexts to be active at once, but we need to make a WebGL context for every platform view on the screen because we might need to paint on top of the platform view. We can implement an optimization which gets rid of overlays that are never painted into, but it will still be possible to write example apps that have more than 16 active WebGL contexts...

**Comment by cbenhagen** [comment]
Fixing https://github.com/flutter/flutter/issues/50721 by cleaning up old contexts would be great already. I don't have a need for more than 8 `HtmlElementView` currently. But if we can find a way to fail gracefully that would be great.

**Comment by yjbanov** [comment]
I think it's reasonable to start losing painting correctness past a certain number of contexts. Even if we can spawn arbitrary number of contexts at some point it will just start slowing everything down.

**Proposal**: have a max limit on number of GL contexts. Past that number, all platform views appear on top of subsequent paint operations. We ask that users do not create too many platform views interleaving canvas paint operations.

WDYT?

**Comment by hterkelsen** [comment]
Another thing we can try is to have a single offscreen canvas the size of the screen, so only one WebGL context, and for each overlay canvas we just do ctx.drawImage and copy in the contents of the offscreen canvas

**Comment by yjbanov** [comment]
This should be fixed by https://github.com/flutter/engine/pull/19341
