### ISSUE TITLE
ReorderableListView inside SliverList throw an error

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#50718]
I have a SliverList with SliverChildBuilderDelegate and a custom Widget with a key.

I have ReorderableListView inside my SliverList but I get this exception:
I have a SliverList with SliverChildBuilderDelegate and a custom Widget with a key.

I have ReorderableListView inside my SliverList but I get this exception:

Flutter error caught by Crashlytics plugin:
```
I/flutter ( 6806): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6806): The following assertion was thrown during performLayout():
I/flutter ( 6806): BoxConstraints forces an infinite height.
I/flutter ( 6806): These invalid constraints were provided to _RenderLayoutBuilder's layout() function by the following
I/flutter ( 6806): function, which probably computed the invalid constraints in question:
I/flutter ( 6806):   RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 6806): The offending constraints were:
I/flutter ( 6806):   BoxConstraints(w=320.0, h=Infinity)
I/flutter ( 6806): 
I/flutter ( 6806): The relevant error-causing widget was:
I/flutter ( 6806):   ReorderableListView...
```
How can fix that?

I have to add 3-4 Reordable horizontal list within a listview/column

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by klaszlo8207** [comment]
@TahaTesser now it is working, fix was:

SizedBox(
          child: ReorderableListView(children: workoutWidgets, scrollDirection: Axis.horizontal, onReorder: _onReorder),
          width: ScreenUtils.width,
          height: 120,
        )

(add inside a size widget)

But the ordering not working anymore :)

**Comment by klaszlo8207** [comment]
When I want to drag and drop the widget all others widget in the horizontal list disappear, then say:

RangeError (index): Invalid value: Not in range 0..2, inclusive: 3

But my list size is only 2 :)

**Comment by klaszlo8207** [comment]
ReorderableListView working with horizontal mode or not? Thanks

**Comment by klaszlo8207** [comment]
Sorry it was my mistakes, now it is working :) 

The mistake was this line

if (newIndex > oldIndex) newIndex -= 1;
