### ISSUE TITLE
ListView scrolls automatically if TextFormField value is set using controller

### ISSUE THREAD

**Issue by liri2006** [flutter/flutter#50713]
Continuation of https://github.com/flutter/flutter/issues/44905

## Steps to Reproduce

Showcase of the issue - https://dartpad.dev/eda0ecfb01900b926b873c4992dd8cde.

1. Run the app.
2. Tap Go to Home Page.

**Expected results:** TextFormField value is set but ListView is not scrolled.

**Actual results:** ListView is scrolled bottom to reveal the TextFormField even it is not focused.

<details>
 
```
```

[√] Flutter (Channel beta, v1.13.6, on Microsoft Windows [Version 10.0.17763.973], locale en-US)
    • Flutter version 1.13.6 at C:\flutter
    • Framework revision 659dc8129d (6 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\amunk\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.0)
    • VS Code at C:\Users\amunk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Actually, it's scrolling when the value is set using `addPostFrameCallback`

I mean
```
_textEditingController.text = 'hello';
```
itself doesn't invoke scrolling, when this does
```
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _textEditingController.text = 'hello';
    });
```

**Comment by liri2006** [comment]
@VladyslavBondarenko Thanx for spotting, that was a wrong iteration of an example (was playing a lot with this one). I've updated it to actually use StreamBuilder as title says.

**Comment by tegarkurniawan** [comment]
same issue

**Comment by VladimirCourse** [comment]
Also having the same issue with SingleChildScrollView

**Comment by jam33** [comment]
same issue here.  i'm filling in multiple TextField(s) via ajax which is called from initState() using something like:

```
setState(() {
fieldValueController1.text = ajaxResults[0]['value1'];
fieldValueController2.text = ajaxResults[0]['value2'];
      });
```

When the "page" (route) loads, it scrolls the page down about a quarter of an inch automatically.

If i leave the whole build layout the same, but simply comment out the ajax call from initState() so that the values of the TextField are never set, the "scroll down" does not occur and the page loads at the top as expected.

Setting the TextField text via it's controller causes the scroll down to occur.  The more fields that are set, the bigger the (unwanted) scroll down affect is.  in other words, setting 1 TextField via ajax scrolls down less than setting 4 TextField values which scrolls down more.

**Comment by jam33** [comment]
> @VladyslavBondarenko Thanx for spotting, that was a wrong iteration of an example (was playing a lot with this one). I've updated it to actually use StreamBuilder as title says.

i agree.  i am **not** using addPostFrameCallback and i am still experiencing the scroll down issue when setting value via TextEditingController.text mechanism.

**Comment by vasilich6107** [comment]
On

` Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale en-UA)`

This code leads to autoscroll

```
_controller
      ..text = value ?? ''
      ..selection = TextSelection.collapsed(offset: _controller.text.length);
```

**Comment by vasilich6107** [comment]
@VladyslavBondarenko 

Reproduction - https://github.com/artflutter/flutter_issue_50713

Video
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6721286/80397233-81bc8180-88be-11ea-8d3a-7b51384734a8.gif)

**Comment by kuhnroyal** [comment]
I have the problem even with disabled `TextField`s. As a workaround setting `showCursor: false` seems to work.

**Comment by ControlAdad** [comment]
`showCursor` trick works, but I need the cursor!

**Comment by fabiosassu-sysdata** [comment]
I am experiencing the same issue.

**Comment by vasilich6107** [comment]
Still an issue for 1.19 and 1.20 version

**Comment by vasilich6107** [comment]
The potential fix is adding additional check 'hasFocus' to this line
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/editable.dart#L2144

so it will change from
`if (_selection.isCollapsed && _showCursor.value && cursorColor != null)`

to
`if (_selection.isCollapsed && hasFocus && _showCursor.value && cursorColor != null)`

**Comment by mehmetf** [comment]
Internal customers are asking for this as well. There's a big discoverability problem here. How would I know, as a user, that a non visible input is changing? Therefore, we would like to get UX guidance. It would be up to the Material UX team to decide whether changing but non-focused inputs can be hidden from user.

**Comment by liri2006** [comment]
@mehmetf In this case it is up to the developer to be in charge of the UX. There is an easy way to set focus (thus scroll to and make input visible) if there is such a need, but there are often times when you just want to populate the form with values from backend on view load without scrolling anything. Hence the issue.

**Comment by mehmetf** [comment]
If you want to populate form values on view load, you should do that before the form even shows otherwise you are racing with user input (what if your backend takes 10 seconds to load the data and user has already input some of it?). Another (poorer) way of doing that is to start with a disabled form and enable it after the values are populated.

To that end: https://github.com/flutter/flutter/issues/50713#issuecomment-626722474 is a real bug IMO. Populating disabled values should not scroll anything.

**Comment by vasilich6107** [comment]
@mehmetf I would appreciate this autoscroll behavior could be easily disabled by some flag)

**Comment by DennisMuchiri** [comment]
> 
> 
> I have the problem even with disabled `TextField`s. As a workaround setting `showCursor: false` seems to work.

This seems to be the only resolution at the moment

**Comment by pedromassangocode** [comment]
Still valid on latest master channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 9248fda410 (13 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro Max (mobile)  • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
pedromassango@MacBook-Pro-de-MacBook ~ % flutter doctor    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
[✓] VS Code (version 1.48.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
</details>

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by AntoineMarcel** [comment]
I found a temp solution, you can wrap your TextField into a Focus and only when user has focus on the text field we set showCursor to true.

```
                  bool showCursor = false;

                  Focus(
                  onFocusChange: (focus) => setState(() => showCursor = focus),
                  child: TextFormField(
                      controller: controller,
                      maxLines: widget.maxLines,
                      autofocus: widget.autofocus,
                      showCursor: showCursor,
```

**Comment by gloryluu** [comment]
Same issue

**Comment by RaymondZY** [comment]
> I found a temp solution, you can wrap your TextField into a Focus and only when user has focus on the text field we set showCursor to true.
> 
> ```
>                   bool showCursor = false;
> 
>                   Focus(
>                   onFocusChange: (focus) => setState(() => showCursor = focus),
>                   child: TextFormField(
>                       controller: controller,
>                       maxLines: widget.maxLines,
>                       autofocus: widget.autofocus,
>                       showCursor: showCursor,
> ```

This works for me. Brilliant trick.

**Comment by jangruenwaldt** [comment]
Even easier, if you have a focusNode for the textfield:

`TextField(                 
                    showCursor: focusNode.hasFocus,
                    focusNode: focusNode,
)`

**Comment by osamaasifoak** [comment]
I was facing the same issue every time when I set my textController value my ListView Scrolls down and stops on TextFormField,
I tried a lot of things to come over this issue but finally, I came up with this problem by initializing a new TextEditingController every time, when the value changed.
textEditingController.text =  new TextEditingController(text: "New Value");
Hope it will work for all of you.

**Comment by venkatd** [comment]
We are having the same issue here. Flutter decides to scroll on our behalf when we don't want it to. Please consider allowing us to opt out of this behavior for a TextField.

**Comment by Lawrene16** [comment]
> i had wrapped the whole widget inside visibility and then i use to make it visible after setting the text in textfield. i still do the same till date

This works like charm. Thanks a lot friend!!

**Comment by tverra** [comment]
I'm using a form that contains a `intl_phone_number_input` text field that does an internal async validation of the inputted phone number, and he validation doesn't happen until the form is visible. The widget also doesn't have the showCursor parameter. This problem has really set me back on my little task of auto-filling the phone number from local storage. 
The only solution I've come up with is adding a callback from the parent widget which enables scrolling on the list when the validation is finished. It's not a long task, not long enough for the user to start filling out the form field before it's loaded. Even if I had the values in memory (which the shared preferences really are at this point anyway), I wouldn't be able to fill in the values using BLOC and stream builders without the form auto-scrolling away from the autofocused text field at the top of the form. 
I would argue that this is a bug, and it's breaking our app.

**Comment by KnucklesEQ** [comment]
I've had the same issue (using Flutter stable 1.22.6). Thanks for the workarounds guys.

I wish to comment two points:

1) The issue is not only in ListView, it also happens if you are using a Column or a Row inside a SingleChildScrollView.
2) One of the workarounds is to put 'showCursor: false' in the TextField, but in this case, when the user taps on the widget and the keyboard appears on the screen, you won't have the auto-scroll and your TextField will be hide by it. So, you have to use the solutions provided by @AntoineMarcel or @jangruenwaldt

**Comment by LongCatIsLooong** [comment]
With https://github.com/flutter/flutter/pull/75604 the text field will no longer attempt to reveal its caret when the text change is made programmatically (but still does so when the user changes the text).

**Comment by ninjaprodev** [comment]
I've tried to update the controller itself, i.e. something like
 ``` 
setState(() {
 controller = TextEditingController(text: "I am a text to be set programmatically");
});
 ```
 and it works fine for me.

**Comment by vasilich6107** [comment]
Hello stranger)

Please note that this fix does not present in `2.0.4`
But present in ` 2.1.0-13.0.pre.479`

**Comment by TahaTesser** [comment]
@vasilich6107 
If it is a regression, please file a new issue and tag me

**Comment by vasilich6107** [comment]
No, it's just a note for those one who will be searching for the version in which this bug is fixed.
May be my message was not clear.

I meant that this bug still exist in `2.0.4`
But in `2.1.0-13.0.pre.479` everything is ok
