### ISSUE TITLE
Gallery, Pesto: Nothing in favorites, FAB does nothing

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5071]
In Gallery, Pesto, I can tap to add a recipe to my favorites, but then when I go into Favorites, I see a blank page. There is an Edit FAB, which responds to touches and has a ripple, but it does nothing.

A couple of options come to mind:

* Make favoriting work. Add tests, ensure formatting works, etc.
* Take the Favorites feature out. Remove from side drawer. Make the Favorite heart FAB not respond to touches (so as not to give the impression that it's a working feature).

**Comment by dragostis** [comment]
Closed in #5722.
