### ISSUE TITLE
[Android] Missing all notifications when building a release apk

### ISSUE THREAD

**Issue by Eimji** [flutter/flutter#50726]
Hello

I have just noticed that when building a release apk with flutter build apk --release --split-per-abi, my application doesn't display any notification (created with the package https://pub.dev/packages/flutter_local_notifications, but also when writing directly in native language kotlin using NotificationCompat.Builder). BUT when I deploy my application with flutter run --release, notifications come back and work great! Do you have any idea to solve the issue? 

Notifications on my application worked before the Flutter version 1.14.6 (I think, not sure). The issue is on the dev and beta channels. 
My flutter doctor:
```
[✓] Flutter (Channel dev, v1.15.3, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.15.3 at /home/patrick/DATA/Github/flutter
    • Framework revision 67826bdce5 (il y a 3 jours), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/patrick/DATA/Applications/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/patrick/DATA/Applications/Android/Sdk
    • Java binary at: /home/patrick/DATA/Applications/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/patrick/DATA/Applications/Android/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • SM A505FN                 • R58M43JWX9M   • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!

```

**Comment by Eimji** [comment]
I found the solution
To get notifications worked, we  need to add shrinkResources false in the build.gradle. This means there is a problem with removing unused code performe by gradle ?

**Comment by Eimji** [comment]
Hello,
To provide you with more details, when build an apk for release, by default (if you don't specify anything in your gradle file), minifyEnabled and shrinkResources are set to true (https://developer.android.com/studio/build/shrink-code). 
The issue is that the image files in the folder res/drawable are wrongly removed (with shrinkResource is true). And because my icons for notification messages are in this drawable folder, local notifications don't work anymore!!! So here is a fix : no need to modify the gradle file (I can still use minifyEnabled and shrinkResources with proguard), just add a keep.xml file in your res folder (for example res/raw) with this content : 
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*" />
```

**Comment by jonahwilliams** [comment]
If you're having issues with proguard you can always build with `--no-shrink`, though this is not recommended if you can instead configure your app correctly. Sounds like you found the fix to your issue, closing.

**Comment by adnanjpg** [comment]
I am also having this problem 

<details><summary>flutter doctor</summary>

``` 

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-TR)
    • Flutter version 1.22.4 at /Users/adnanfahed/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/adnanfahed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 7c0edb93134cbbf0493eb34ada73e295cffa68cf • ios • iOS 14.2


```
</details>

I would like also to note that due to problems with the [shared_preferences](https://pub.dev/packages/shared_preferences) package, i build my release with the following command : "flutter build appbundle --no-shrink"
