### ISSUE TITLE
[web]: <Failed to establish connection with the application instance in Chrome. This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due to a     firewall.>

### ISSUE THREAD

**Issue by Tek-hp** [flutter/flutter#50724]
Describe your issue and include the command you're running, flutter_web version, browser version

**Comment by TahaTesser** [comment]
Hi @Tek-hp 
Closing this as duplicate [#49482](https://github.com/flutter/flutter/issues/49482)
Thank you

**Comment by mayankhardiya** [comment]
A

> Hi @Tek-hp
> Closing this as duplicate [#49482](https://github.com/flutter/flutter/issues/49482)
> Thank you

After closing duplicate. when i run my project it will occurs again and again. is there any permanent solution ???
