### ISSUE TITLE
Broken AVD system path. Check your ANDROID_SDK_ROOT value

### ISSUE THREAD

**Issue by MathSqr2** [flutter/flutter#50738]
`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter emulators --launch Pixel-test

## exception

ProcessException: ProcessException: Process exited abnormally:
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [C:\Android\SDK]!
  Command: C:\Android\SDK\emulator\emulator.exe -avd Pixel-test

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      AndroidEmulator.launch (package:flutter_tools/src/android/android_emulator.dart:52:52)
#3      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:74:31)
<asynchronous suspension>
#4      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale pt-PT)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\flutter
    [32m•[39m Framework revision 0b8abb4724 (2 days ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Android\SDK
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m ANDROID_HOME = C:\Android\SDK
    [32m•[39m ANDROID_SDK_ROOT = C:\Android\SDK
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 43.0.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m VS Code (version 1.42.0)
    [32m•[39m VS Code at C:\Users\AfonsoGuimarães\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```
`

I'm getting this error even having the variables ANDROID_HOME and ANDROID_SDK_ROOT set.

**Comment by TahaTesser** [comment]
Hi @MathSqr2 
1. Please follow this [Solution](https://github.com/flutter/flutter/issues/24988#issuecomment-550167001)
2. run `flutter emulators` and choose the emulator you want
3. run `flutter emulators --launch <emualtor name>`

Thank you

**Comment by MathSqr2** [comment]
Hi @TahaTesser , thanks for responding. The error that I previously pointed out appeared when I did what you asked, but for the sake of it I ran again. The output is has it follows:

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter emulators --launch Pixel_2_API_29

## exception

ProcessException: ProcessException: Process exited abnormally:
PANIC: Cannot find AVD system path. Please define ANDROID_SDK_ROOT
  Command: C:\Android\Sdk\emulator\emulator.exe -avd Pixel_2_API_29

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      AndroidEmulator.launch (package:flutter_tools/src/android/android_emulator.dart:52:52)
#3      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:74:31)
<asynchronous suspension>
#4      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale pt-PT)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\flutter
    [32m•[39m Framework revision 0b8abb4724 (3 days ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m ANDROID_HOME = C:\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 43.0.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m VS Code (version 1.42.0)
    [32m•[39m VS Code at C:\Users\AfonsoGuimarães\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```
`
I have both ANDROID_HOME and ANDROID_SDK_ROOT set to the same folder C:\Android\Sdk

**Comment by zgegonline** [comment]
I had the exact same issue as you, the problem is that you .android folder is located in a path with non-ascii characters ("C:\Users\AfonsoGuimarães"), I think. You need to move it.
In order to do that : 
 - close all terminals and software related to android
 - you have to move the .android folder located in your user directory in another directory, let's say to "C:\Android\"
 - open C:\Android\.android\avd and edit the ini file(s) to set the correct path that you juste changed
 - Open the windows environment variables settings and edit or set a new variable if you don't have it : 
           name : "ANDROID_SDK_HOME" value : "C:\Android" (not .android !!)
 - Now it should work
I have no others environement variable set (no ANDROID_HOME or ANDROID_SDK_ROOT) and it works for me

I found the solution here : https://developercommunity.visualstudio.com/content/problem/1005744/panic-cannot-find-avd-system-path-please-define-an.html

**Comment by lealiz** [comment]
> I had the exact same issue as you, the problem is that you .android folder is located in a path with non-ascii characters ("C:\Users\AfonsoGuimarães"), I think. You need to move it. In order to do that :
> 
> * close all terminals and software related to android
> * you have to move the .android folder located in your user directory in another directory, let's say to "C:\Android"
> * open C:\Android\.android\avd and edit the ini file(s) to set the correct path that you juste changed
> * Open the windows environment variables settings and edit or set a new variable if you don't have it :
>   name : "ANDROID_SDK_HOME" value : "C:\Android" (not .android !!)
> * Now it should work
> 
> I found the solution here : https://developercommunity.visualstudio.com/content/problem/1005744/panic-cannot-find-avd-system-path-please-define-an.html

> I had the exact same issue as you, the problem is that you .android folder is located in a path with non-ascii characters ("C:\Users\AfonsoGuimarães"), I think. You need to move it. In order to do that :
> 
> * close all terminals and software related to android
> * you have to move the .android folder located in your user directory in another directory, let's say to "C:\Android"
> * open C:\Android\.android\avd and edit the ini file(s) to set the correct path that you juste changed
> * Open the windows environment variables settings and edit or set a new variable if you don't have it :
>   name : "ANDROID_SDK_HOME" value : "C:\Android" (not .android !!)
> * Now it should work
> 
> I found the solution here : https://developercommunity.visualstudio.com/content/problem/1005744/panic-cannot-find-avd-system-path-please-define-an.html

Hi...
I know it's been almost two years since this solution, but i just wanted to say thank you for this.
I was trying to solve this on my computer all day long, looking for answers everywhere. Now it's almost 10pm and I've just found your answer and finally solved my non-ascii problem.
Again... thank you! :)

**Comment by exaby73** [comment]
Hello @MathSqr2. Can you confirm if this is still an issue?

**Comment by exaby73** [comment]
Since I was not able to reproduce this issue, I am closing it as fixed. If you can still reproduce this issue, please comment and we can reopen it. Thank you

**Comment by exaby73** [comment]
Hello @KedwithGod. Can you post your `flutter doctor -v` output as well as the error logs?
