### ISSUE TITLE
Gallery, Pesto: White space between app bar and recipe list after going back

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5073]
To repro, open Gallery, tap pesto, tap a recipe, tap the back button on Android.

Here's what we see:

![screen shot 2016-07-27 at 9 45 56 am](https://cloud.githubusercontent.com/assets/5479/17184023/fe6cde5a-53de-11e6-886f-6f1e9ff47216.png)

**Comment by mpcomplete** [comment]
I believe this was fixed by https://github.com/flutter/flutter/pull/5151 . It no longer repros.
