### ISSUE TITLE
tool_coverage-linux fails with "Signaled to exit!"

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#50737]
Sample build run: https://cirrus-ci.com/task/6308404167704576?command=main#L1047

This has kept the tree closed for 17 hours as of this writing.

/cc @jonahwilliams @zanderso

**Comment by yjbanov** [comment]
@a-siva Has there been a change in line coverage in the Dart VM? Is there anything we should do on the Flutter side to make coverage work again?

**Comment by jonahwilliams** [comment]
I'm going to see if the OOM is tickled by how we're running coverage

**Comment by jason-simmons** [comment]
This should be fixed now (see https://github.com/dart-lang/sdk/commit/fcf88fe6faa0b7a63a690a716f914b5400657c2a)
