### ISSUE TITLE
 Crash on routing back in release mode

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#50745]
We are seeing a crash in release mode that we are not seeing in development mode.

We have a page we go to and do a search and save.  On the routing back it crashes.  Sometimes it doesn't crash.

The crash is the entire app dying.

Stack trace and more internal details in b/149399743

**Comment by dnfield** [comment]
https://dart-review.googlesource.com/c/sdk/+/134204

**Comment by alexmarkov** [comment]
Revert CL: https://dart-review.googlesource.com/c/sdk/+/135794

**Comment by dnfield** [comment]
Fixed by https://github.com/flutter/flutter/pull/50803

**Comment by dnfield** [comment]
Spoke too soon, it hasn't rolled yet.
