### ISSUE TITLE
Add package support to  FadeInImage.assetNetwork()

### ISSUE THREAD

**Issue by AndrsDev** [flutter/flutter#50741]
## Use case
I have a package that has it's own assets. I want to pass the desired package on something like this:
```
     FadeInImage.assetNetwork(
          placeholder: 'assets/placeholder.png',
          placeholderPackage: 'custom_package',
          image: 'imageurl',
          fit: BoxFit.cover,
     )
```

## Proposal

Add optional parameter `placeholderPackage `to widget constructor.

**Comment by dnfield** [comment]
I'm not strongly opposed to this, but I question whether it's the right direction.  For example, you can easily do:

```dart
FadeInImage(
  placeholder: AssetImage('assets/placeholder.png, package: 'custom_package')),
  image: NetworkImage(imageUrl),
  fit: BoxFit.cover,
)
```

Without any framework changes - and the more we pipe through arguments to these convenience constructors, the harder they'll become to understand.

**Comment by AndrsDev** [comment]
@dnfield Thank you a lot, this workaround is perfect! I was searching for something like this but I couldn't figure it out! Feel free to close this issue if you want 🔥
