### ISSUE TITLE
Expose setting to embedders to limit max rasterizations per frame

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#50742]
In `raster_cache.h` we hard-code a maximum of 3 picture raster caches per frame in order to reduce jank. Given that different hardware and software stacks have different tolerances for caching, we should expose a mechanism for tuning this parameter that can be used by power-users.

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
