### ISSUE TITLE
Problem loading code during first run

### ISSUE THREAD

**Issue by mezueceejay** [flutter/flutter#50747]
I create a new flutter app in Visual Studio Code, firstly, there are default codes in main.dart, and I ran it normally in my Android phone. I deleted the codes in the main.dart and ran a command line Flutter run. However, when the app had finished building the template is always shown, the content didn't change any until I run a hot restart

**Comment by jonahwilliams** [comment]
@mezueceejay do you have a space ' ' in a directory name? There was a bug in handling this that was very recently fixed

**Comment by mezueceejay** [comment]
@jonahwilliams I do not have a space in my directory but I think I found a fix... I just ran flutter clean and it seems to be working at the moment

**Comment by jonahwilliams** [comment]
Ideally that wouldn't be required at all.  Good that it is resolved though
