### ISSUE TITLE
Re-enable coverage shard for flutter_tools

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#50755]
We're going to disable the coverage shard until we can determine the cause and fix for the increased memory usage. While the coverage shard previously took less than 12G of memory, it is currently (as of e0ebaea59071b35a44dbe1e0830ee15fb7563486) using more than 173 G.

We might try using `pub run test --coverage` to shed the custom test runner as a potential source of failures. This is blocked by https://github.com/dart-lang/sdk/issues/40627

**Comment by jonahwilliams** [comment]
@zanderso

**Comment by zanderso** [comment]
We decided not to disable the coverage shard.
