### ISSUE TITLE
[web][edge] unskip Edge text editing tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#50769]
Some methods in text_editing_test.dart are skipped in Edge. We should either skip them or change them to work in in Edge. (note: there is a chance that the browser has a bug for the tests methods use case)

**Comment by pedromassangocode** [comment]
I can't find the file mentioned above, does it was moved for another file or renamed?

**Comment by yjbanov** [comment]
No plan to support old Edge any more.
