### ISSUE TITLE
Dark Mode isn't recognized by CupertinoActionSheet

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#50767]
The `CupertinoActionSheet` widget should recognize when the device is in dark mode, and adjust its colors accordingly. I think this worked correctly in 1.13.6 but no longer works in 1.14.6. Here is a complete example to reproduce the issue. Put the device in dark mode and click the floating action button:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('CupertinoActionSheet Demo'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showCupertinoModalPopup(
            context: context,
            builder: (context) {
              return CupertinoActionSheet(
                actions: [
                  CupertinoActionSheetAction(
                    onPressed: () {
                      print('hello');
                    },
                    child: Text(
                      'Test',
                    ),
                  ),
                ],
              );
            },
          );
        },
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

```
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.14.6 at /Users/maxlapides/flutter
    • Framework revision fabeb2a16f (2 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • 012909B1-9EAB-408C-9365-1106B036E97B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by LongCatIsLooong** [comment]
I believe it is a bug fix. Since you are using `MaterialApp`, you need to give it a dark theme (with `brightness` set to `Brightness.dark`) so both Material widgets and Cupertino widgets in the app change color when dark mode is turned on/off. 
The behavior is introduced in https://github.com/flutter/flutter/pull/47249, to keep the brightness of Material widgets and Cupertino widgets in the same app consistent.

More context: https://github.com/flutter/flutter/issues/47255.

**Comment by maxlapides** [comment]
Okay cool, I see that this works:

```dart
MaterialApp(
  theme: ThemeData(
    brightness: Brightness.dark,
  ),
),
```

But I'm a little confused. Why would I want to set the theme to "dark" when I actually want it to be dynamic based on the operating system setting?

**Comment by LongCatIsLooong** [comment]
It is more common to have something like this for a `MaterialApp` that supports dark mode:
```dart
MaterialApp(
  theme: ...,
  darkTheme: ...,
  themeMode: ThemeMode.system, // The default, usually omitted.
)
```
This way the app changes theme based on the os brightness setting. 

If you don't specify a `CupertinoTheme` in a `MaterialApp`, `MaterialTheme` will derive one for you. Since generally you don't want your material widgets and cupertino widgets to be in different brightness, the derived `CupertinoTheme` will have the same brightness as the `MaterialTheme`.

**Comment by maxlapides** [comment]
Ah, that makes so much more sense! Okay I think I get it now. Thanks for all the information!

**Comment by tiklup11** [comment]
Hey @LongCatIsLooong  I am experiencing similar issue but my app only contains Cupertino Widgets,please take a look at this image [https://i.stack.imgur.com/gL3C5.jpg](url)  
![ss_01](https://user-images.githubusercontent.com/57872422/100186383-e2bb3f00-2f0b-11eb-8e9f-7e275bbc4c46.jpg)



`   @override
Widget build (BuildContext context) {
    return CupertinoApp(
        theme: CupertinoThemeData(
        brightness: Brightness.light,)
    home: MyApp()
)`

**Comment by LongCatIsLooong** [comment]
@tiklup11 most likely the action sheet is not looking at the correct `BuildContext` because it lives on a separate `Overlay` entry. You should be able to find out what `BuildContext` the action sheet is using to resolve colors using the devtool, in the widget inspector.

**Comment by tiklup11** [comment]
@LongCatIsLooong you just got a huge fan. Thanks a ton man.
