### ISSUE TITLE
[video_player] iOS: clean up the display link when the engine is deleted

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#50761]
Issue https://github.com/flutter/flutter/issues/44256 introduced the problem where iOS plugins were not handling cleanup for the add-to-app case.  That issue was resolved when the iOS plugin API was expanded to support that type of cleanup.

The problem which originally lead to that issue was with the _video_player_ plugin though.  So, we should now update video_player to take advantage of the new cleanup API.

cc @zoeyfan @talisk

**Comment by zoeyfan** [comment]
Thanks!

**Comment by talisk** [comment]
LGTM, thanks.
