### ISSUE TITLE
I'm getting this error from AnimationController & Tween and I'm not sure what is wrong...

### ISSUE THREAD

**Issue by NoctisShadowzel** [flutter/flutter#50762]
Here is related codes;
[related_code](https://gist.github.com/NoctisShadowzel/be2c5c316b9cd9470f9bea35f23f82b6)
[calling_parent](https://gist.github.com/NoctisShadowzel/9d1021022b27f851ba4968656182ca8e)

I'm trying to make a background where points on screen move diagonally.

How ever I got this error message: 
[output.txt](https://gist.github.com/NoctisShadowzel/a9e1e8d76813999441ccd2d036cdb92d)

`flutter analyze`
```
Analyzing dreawey...
No issues found! (ran in 2.1s)
```

`flutter doctor -v`
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version
    10.0.17763.973], locale tr-TR)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\noctisshadowzel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at
      C:\Users\noctisshadowzel\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\183.4284
      .148
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.39.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM A105F • RZ8M614H4AT • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by BassamxMednini** [comment]
> I/flutter ( 2059): The following assertion was thrown while notifying listeners for AnimationController:
> I/flutter ( 2059): type 'double' is not a subtype of type 'int'

I'm not pretty sure, but change the line 62 from `double multiplier...` to `int multiplier...`

**Comment by NoctisShadowzel** [comment]
I changed it from `int` to `double`; because I was getting a similiar output with something like
```
toDouble() was called on null
```

**Comment by TahaTesser** [comment]
This could be related [#24983](https://github.com/flutter/flutter/issues/24983)

**Comment by NoctisShadowzel** [comment]
If you think addressing related parts from **issue #24983** will help solving this issue;
First, I'm not sure if it is **directly** related to `Tween<T>` in this issue, because I'm animating it, as a `Tween<int>` and directly using it as an index. If, at this point, some problem causing this, this must be related to framework.
Secondly, as explained in #24983, my program doesn't show a _red screen_ like framework normally does, either. I get a static layout, _with a significant problem_, and my logs continuously print exceptions.
_Significant problem is_, in my code, I use space under the **System Navigation Bar** and it is transparent. When I just draw points, it is painting under Nav. Bar too; but when I try to animate it and exceptions start, there is a gap under Nav. Bar, nothing is painted there.

To go even further, I writed 3 other implementations for; _drawing points on a canvas with given coordinates as a `List<Offset>` using `Canvas.drawPoints(...)`. All of them crashed somehow, with different errors. I'm not sure this will help or make the issue more complex, if it does make issue complex please let me know; but I think there may be some problem related to parts which help creating _explicit animations_.

Thank you for taking time.

**Comment by goderbauer** [comment]
Can you please post a minimal and runnable example that we can run to reproduce the problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
