### ISSUE TITLE
How can I customize the value of timeout with WebSocket?

### ISSUE THREAD

**Issue by leyan95** [flutter/flutter#50777]
Hi
    I ran into some problems during the development process.
    Here's the demand: 
        'Let the user customize the server address in some way, selecting a `wsurl ` address that is available when the user logs in.'
    So in order to reduce the wait time when the user first logs in, I want to know How can I customize the value of timeout with WebSocket.

with regards,
leyan95

**Comment by TahaTesser** [comment]
Hi @leyan95 
Issue you're describing probably belongs to [Dart-Lang/web_socket_channel](https://github.com/dart-lang/web_socket_channel)
Please raise your issue there and meanwhile this possible [Solution](https://github.com/dart-lang/web_socket_channel/issues/61#issuecomment-585564273) might help you 
Related issues [#22](https://github.com/dart-lang/web_socket_channel/issues/22) [#61](https://github.com/dart-lang/web_socket_channel/issues/61)
Closing as this isn't an issue with Flutter itself
Thank you

**Comment by leyan95** [comment]
Thanks👍
