### ISSUE TITLE
[web][edge] unskip Edge text related tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#50771]
Couple of tests are skipped for text/paragraph in Edge in the following files. We should either skip them or change them to work in in Edge. (note: there is a chance that the browser has a bug for the tests methods use case):

text_test
paragraph_test.dart

**Comment by pedromassangocode** [comment]
Still valid today, we have a lot of tests skipped for Browsers in the file mentioned above.

https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/paragraph_test.dart

**Comment by yjbanov** [comment]
No plans to support old Edge any more. I'm removing the skips for new Edge.
