### ISSUE TITLE
Outdated Text Selection UI

### ISSUE THREAD

**Issue by Myles-Trevino** [flutter/flutter#50781]
## Steps to Reproduce
This can be reproduced by creating a TextField in a MaterialApp.

**Expected results:**
In most other apps in Android 9 and 10, the text selection menu looks like this:

<img alt="" Height="512" src="https://user-images.githubusercontent.com/11729491/74501720-ff284680-4eb8-11ea-8a66-175ef2e6244d.png">

**Actual results:**
However in Flutter apps, the menu looks like this:

<img alt="" Height="512" src="https://user-images.githubusercontent.com/11729491/74501708-f9cafc00-4eb8-11ea-9bba-68ceca866559.png">

Additionally, when sliding the text selection cursor around in Android 9 and 10, a magnifying rectangle appears. In Flutter, no magnifier appears as mentioned in #17617 These two problems make text fields feel out of date and non-native when using the two most current versions of Android.

**Comment by justinmc** [comment]
@Myles-Trevino This was fixed and should look correct now, see https://github.com/flutter/flutter/pull/59115.

However, the magnifying glass is still not implemented.  We'll track that in https://github.com/flutter/flutter/issues/17617.
