### ISSUE TITLE
Update dependencies in flutter_localizations module

### ISSUE THREAD

**Issue by kasimr-oxc** [flutter/flutter#50782]
## Use case

Current flutter SDK:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/kasim/flutter
    • Framework revision 0b8abb4724 (2 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
```

I'm getting following message in `packages get` command.
```
Because <my-app> depends on flutter_localizations any from sdk which depends on intl 0.16.0, intl 0.16.0 is required.
So, because <my-app> depends on intl ^0.16.1, version solving failed.
```

## Proposal

Please update `intl` from `0.16.0` to `0.16.1` in `flutter_localizations` module.

**Comment by VladyslavBondarenko** [comment]
Hi @kasimr-oxc 
It was changed in [this commit](https://github.com/flutter/flutter/commit/f65f7f0118361654038f59d1e4885f0b3e46e8da#diff-353961416eaa56f8805733ca0bfbe976), for master channel intl 0.16.1 is already used
