### ISSUE TITLE
[web] AlertDialog does not display content

### ISSUE THREAD

**Issue by aragonet** [flutter/flutter#50788]
The content of a simple AlertDialog is not visible on the web.
If the content text is long and the screen is small, some part of the text is visible, but if the screen is bigger no content is visible. (Captures below)
If the content text is short it is never visible.

On an Android device the content is correctly displayed.

## Steps to Reproduce

```
AlertDialog(
      title: Text('Bug Showing AlertDialog content'),
      content: Text(
          'This is not a really long text but long enough to demonstrate the miss behaviour on web'),
      actions: <Widget>[
        FlatButton(
          child: Text('No'),
          onPressed: () {},
        ),
        FlatButton(
          child: Text('Yes'),
          onPressed: () {},
        ),
      ],
    );
```

**Expected results:**
![image](https://user-images.githubusercontent.com/20858599/74518206-ad60da00-4f13-11ea-89a4-794fdbf4f826.png)

**Actual results:**
![image](https://user-images.githubusercontent.com/20858599/74517835-20b61c00-4f13-11ea-90dc-39e1778fe498.png)

![image](https://user-images.githubusercontent.com/20858599/74517800-0ed47900-4f13-11ea-8518-4c665bcaaf49.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale es_ES.utf8)
    • Flutter version 1.14.6 at /flutter
    • Framework revision fabeb2a16f (2 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /development/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.100
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @aragonet 
This issue is not reproducible on `betal channel`
Here is the gist `https://dartpad.dev/edf300df8e8c3ac39c089af705092ce3`
Please feel free to edit the gist and provide details if you still experiencing this issue

![Annotation 2020-02-14 152449](https://user-images.githubusercontent.com/48603081/74520854-62a88780-4f3e-11ea-87b3-8acd5e1a7c44.png)

Thank you
