### ISSUE TITLE
lots of console logs that I can't understand (asked on stackoverflow, no answers yet)

### ISSUE THREAD

**Issue by jjoek** [flutter/flutter#50794]
I just upgraded flutter and right after the upgrade I am getting quite a bunch of logs in the console, which don't make sense to me, tried to surf the internet for such sort of errors but apparently there don't seem to be any traces of these kind of errors: For a start, you guys can help me in trying to understand these and how to go about this because it is getting to be quite hard to debug: I must also mention though that the they don't stop the app from running:

    I/HwPhoneWindow(25343): updateLayoutParamsColor false mSpecialSet=true, mForcedNavigationBarColor=true, navigationBarColor=ff6451fe, mNavBarShow=true, mIsFloating=false
    I/HwPhoneWindow(25343): updateLayoutParamsColor false mSpecialSet=true, mForcedNavigationBarColor=true, navigationBarColor=ff6451fe, mNavBarShow=true, mIsFloating=false 
    V/InputMethodManager(25343): Reporting focus gain, without startInput
    V/InputMethodManager(25343): Reporting focus gain, without startInput

Similarly whenever I get the following when I touch anywhere on the screen:

    W/HiTouch_PressGestureDetector(25343): Touch pointer move a lot. The moving distance of X is:2.0, limit is:51The moving distance of Y is:69.0, limit is:51

    Below log also just appears am currently not sure of what is triggering this yet:
    W/InputMethodManager(25343): startInputReason = 8
    W/IInputConnectionWrapper(25343): getExtractedText on inactive InputConnection
    W/IInputConnectionWrapper(25343): getTextBeforeCursor on inactive InputConnection
    W/IInputConnectionWrapper(25343): requestCursorAnchorInfo on inactive InputConnection
    D/ZrHung.AppEyeUiProbe(25343): stop checker.
    W/libEGL  (25343): EGLNativeWindowType 0x755f41b010 disconnect failed
    D/ViewRootImpl[MainActivity](25343): surface should not be released
    D/FlutterView(25343): Detaching from a FlutterEngine: 
    io.flutter.embedding.engine.FlutterEngine@486f178
    W/InputMethodManager(25343): startInputReason = 3
    W/IInputConnectionWrapper(25343): getExtractedText on inactive InputConnection
    W/IInputConnectionWrapper(25343): getTextBeforeCursor on inactive InputConnection
    W/IInputConnectionWrapper(25343): requestCursorAnchorInfo on inactive InputConnection
    W/libEGL  (25343): EGLNativeWindowType 0x75660d7010 disconnect failed
    V/ActivityThread(25343): Handle window ActivityRecord{d450bd5 token=android.os.BinderProxy@c9b5ecf{com.example.cmed/com.example.cmed.MainActivity}} visibility: false
    D/ZrHung.AppEyeUiProbe(25343): Current Activity:false
    D/ZrHung.AppEyeUiProbe(25343): not watching, wait.
    E/        (25343): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]

https://stackoverflow.com/questions/60221016/flutter-upgrade-issue-with-lots-of-un-understandable-logs-no-harm-though

**Comment by VladyslavBondarenko** [comment]
Hi @jjoek 
could you provide you `flutter doctor -v`?

**Comment by jjoek** [comment]
@VladyslavBondarenko check it out below: thanks

`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/jjoek/dev/flutter
    • Framework revision 0b8abb4724 (3 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jjoek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • JKM LX1 • DEF4C19A09002052 • android-arm64 • Android 9 (API 28)

• No issues found!`

**Comment by zigang93** [comment]
#50628 because of this issue.. 
I already downgrade to hotfix.7
run `flutter version 1.12.13+hotfix.7`
I think flutter should make change log on each version release.. on this pages. https://flutter.dev/docs/development/tools/sdk/releases

**Comment by VladyslavBondarenko** [comment]
@jjoek 
Please follow on https://github.com/flutter/flutter/issues/50808
Closing current as duplicate
