### ISSUE TITLE
Navigator.pushReplacement(                   context,                   MaterialPageRoute(settings: RouteSettings(name: "mainfeed")),                 );

### ISSUE THREAD

**Issue by SnakeGeneral** [flutter/flutter#50796]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @SnakeGeneral 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you
