### ISSUE TITLE
Is there any plan to add real-time viewing of SQLite database data in Open DevTools?

### ISSUE THREAD

**Issue by pruidong** [flutter/flutter#50792]
Is there any plan to add real-time viewing of SQLite database data in Open DevTools?

I currently use IntelliJ IDEA + Android system simulator (Android 8.0 / API: 26). In Flutter I used SQflite to access the SQLite database (but this library does not support visual viewing of data in the SQLite database).

At the same time, the Database function that comes with IntelliJ IDEA cannot access the SQLite database debugged by Flutter (when adding a connection, you cannot choose the package name, you can only choose the Android emulator).

![0202020202020202020202020202](https://user-images.githubusercontent.com/13309008/74531461-a8c61100-4f67-11ea-86c0-580b590c8d26.png)

Hope to provide a function that can view the data in SQLite database in real time in IntelliJ IDEA, or other similar solutions, thank you for your help!

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.657], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

请问有计划在Open DevTools中,增加实时查看SQLite数据库数据的功能吗?

我目前使用IntelliJ IDEA+Android系统模拟器(Android 8.0/API:26).在Flutter中我使用了SQflite访问SQLite数据库(但这个库不支持可视化查看SQLite数据库中的数据).

同时IntelliJ IDEA自带的Database功能也无法访问Flutter调试的SQLite数据库(在增加连接的时候,无法选择包名,只能选择Android模拟器).

希望能提供一个可以在IntelliJ IDEA中实时查看SQLite数据库中数据的功能,或其他类似的解决办法,谢谢您的帮助!

**Comment by TahaTesser** [comment]
Hi @pruidong 
Could this help you [#45679 flutter_sqflite_manager](https://pub.dev/packages/flutter_sqflite_manager)

**Comment by pruidong** [comment]
Thanks, I found an IDEA plugin that can be used to achieve my needs. This plugin is: SQLHelper: https://plugins.jetbrains.com/plugin/8329-sqlhelper


谢谢,我找到一个可以用的IDEA插件,可以实现我的需求.这个插件是:SQLHelper: https://plugins.jetbrains.com/plugin/8329-sqlhelper
