### ISSUE TITLE
android studio cannot create flutter project  (version 3.5.3)

### ISSUE THREAD

**Issue by leoche1984** [flutter/flutter#50802]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter application. --org com3.example --ios-language objc --android-language java flutter2

## exception

FileSystemException: FileSystemException: Creation failed, path = 'C:\flutterdemo\flutter2\android\app\src\main\java\com3' (OS Error: 目录名称无效。
, errno = 267)

**Comment by VladyslavBondarenko** [comment]
Hi @leoche1984 
Change your package name `com3.example` on `com.example` or some another variant, `com3` seems to be not valid

**Comment by VladyslavBondarenko** [comment]
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you
