### ISSUE TITLE
Conditional imports not working on web in debug mode [web]

### ISSUE THREAD

**Issue by muhleder** [flutter/flutter#50801]
Since this commit
https://github.com/flutter/flutter/commit/18f38cd45bee65931c28433c2071d48570b62b1b
conditional imports are not working on web in debug mode.

```
import 'none.dart'
if (dart.library.io) 'io.dart'
if (dart.library.html) 'web.dart';
```

Instead of web.dart being imported, io.dart is imported instead.

This is running any app with `flutter run -d chrome`. Release mode still works `flutter run -d chrome --release`

Spotted in hive https://github.com/hivedb/hive/pull/223 and bisected with a minimal app to find the breaking commit in flutter.

**Comment by muhleder** [comment]
Flutter doctor output

Marks-MacBook-Pro:demo mark$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.15.4-pre.68, on Mac OS X 10.14.6 18G103, locale en-GB)
• Flutter version 1.15.4-pre.68 at /opt/flutter
• Framework revision 85ab331c82 (4 hours ago), 2020-02-14 10:41:23 +0100
• Engine revision 0e8ed2715a
• Dart version 2.8.0 (build 2.8.0-dev.8.0 5244d99a5d)

**Comment by jakemac53** [comment]
This should be resolved with https://dart-review.googlesource.com/c/sdk/+/136411

**Comment by yjbanov** [comment]
We should have a test for this.
