### ISSUE TITLE
[web][safari] launching safari via applescript

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#50809]
The method we were using for launching Safari from [dart-sdk/test](https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/runner/browser/safari.dart) is not working in automated tests environments since it brings a pop-up for redirect file.

We replaced this method by using "open" application built into MacOS: https://github.com/flutter/engine/pull/16590

On the other hand this method does not close Safari. A better solution would be using applescript to launch safari.

**Comment by yjbanov** [comment]
Leaving a copy of a comment I made on https://github.com/flutter/engine/pull/16590:

> The `Browser` class expects that the process object returned from this function is the browser process, or at least some proxy of it. However, this would return the `open` process that quits immediately. I have a feeling this will become a thorn in future evolution of the `Browser` class. For example, this will prevent us from being able to implement logic that watches the health of the browser process, such as premature termination ([examples](https://github.com/flutter/flutter/search?q=prematurely&unscoped_q=prematurely)).
>
> Having said that, I don't have an immediate solution to this, other than what we talked about offline, i.e. use WebDriver to control launching of browsers. If I'm reading the w3c spec correctly, Selenium is not necessary to use it (see [WebDriver Protocol](https://w3c.github.io/webdriver/#protocol)). So please, treat this comment as non-blocking. I'll file a separate issue for us to investigate a WebDriver solution.

**Comment by nturgut** [comment]
We decided not go from this route. closing the issue.
