### ISSUE TITLE
Flutter Website (flutter.dev) on Safari

### ISSUE THREAD

**Issue by jdcoding01** [flutter/flutter#50805]
Steps to reproduce:

Honestly I just opened flutter.dev on Safari, macOS Catalina, MacBook Pro 2019.

This happened:
<img width="1440" alt="Screen Shot 2020-02-14 at 12 53 43 PM" src="https://user-images.githubusercontent.com/22108716/74551678-fae84180-4f29-11ea-9d71-f54a0e22dbfd.png">

I reloaded the website, closed and re-opened website as well as closed and re-opened browser.

**Comment by timsneath** [comment]
In general, it looks like the two fonts we use (Material Icons and Google Sans) weren't successfully loaded when you opened the page (see my screenshot for comparison). I was unable to reproduce your issue; it may be transient? 

![image](https://user-images.githubusercontent.com/2319867/74556970-f9ac1a00-4f13-11ea-93af-4703622828b7.png)

**Comment by jdcoding01** [comment]
Most likely, just re-tried right now and I was unable to reproduce it as well. Might have been an issue with the network at the office or something.
