### ISSUE TITLE
[web] Smoothen build/paint during window resize

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#50814]
Deep widget trees can cause high build times that lead to jank during resize. Build a throttler in place where # of frames rebuild/painted is reduced by a rootElement transform.

**Comment by esDotDev** [comment]
fwiw, this is also an issue for all desktop platforms.

**Comment by lironiz** [comment]
is there a solution to this issue? orientation change in my app has a lot of jank too.

**Comment by esDotDev** [comment]
fwiw, the approach seen on apps like Slack and Chrome, is fairly simple / effective:
1. The app is always pinned top-left, no gap is allowed to exist along the top, or left sides.
2. The app resize is debounced, at around 2-3fps.
3. The background of the window, matches the background of the app, minimizing visibility of delayed re-size

**Comment by lironiz** [comment]
what do you mean by "pinned top-left"? how is that achieved?

**Comment by esDotDev** [comment]
Just grab the corner of your chrome browser and aggressively drag it around, you'll see what I mean. No gap is ever shown on the left or top, all 'empty' regions are on the right/bottom. From our testing with desktop a few months back, it was common to se black regions appear along the top/left sides when resisizing, which looks really poor.

**Comment by davidmartos96** [comment]
@esDotDev  Is it possible to paint the background while resizing to a different color other than black on Flutter desktop? I'm trying to do that to smooth a bit the result. My desktop app has white background and the black while resizing is very shocking.

**Comment by esDotDev** [comment]
Not that I know, but agreed, it would be a great addition.

**Comment by esDotDev** [comment]
Web seems to be working really nicely in the latest versions. 

Windows, while now being top-left aligned, still has some bounce going on: 
https://user-images.githubusercontent.com/736973/110253243-7c03e380-7f46-11eb-9a1a-4c27e649a772.mp4

**Comment by esDotDev** [comment]
There seems to be a rather large performance delta between macos and windows here. 

Using profile mode, and an extremely simple view:
MacOS: 10ms frame times (capped at 60fps, with plenty of room to spare)
![image](https://user-images.githubusercontent.com/736973/111666202-1bdc2f80-87d9-11eb-8dd0-7a6b861cc70b.png)

Windows: 30ms frame times, 
![image](https://user-images.githubusercontent.com/736973/111666339-3d3d1b80-87d9-11eb-9390-8ddacb39425a.png)
https://user-images.githubusercontent.com/736973/111666443-580f9000-87d9-11eb-8dfa-52fa871ef479.mp4

This is a very simple view, if we go to more complex views we can see the fps down to 15-20fps on resize.

**Comment by esDotDev** [comment]
There is a related issue here: https://github.com/bitsdojo/bitsdojo_window/issues/39

**Comment by ferhatb** [comment]
@esDotDev thx for pointing to issue. Need to check window resize events we are tracking and why they are causing this on specifically on Windows.

**Comment by rockingdice** [comment]
Thumb this up. Resizing windows should be handled better.

**Comment by yjbanov** [comment]
I'm going to close this. Doing this out-of-the-box is probably not a good idea as the effect of stretching is not expected default behavior. Another reason is that installing a root transform during window resize is something that can be done at the framework level. This doesn't look like a job for the engine. Can be a widget in the framework on in a pub package.
