### ISSUE TITLE
`flutter analyze` error because of analyzer state leftover from a different flutter revision

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#50811]
Running `flutter analyze --flutter-repo` locally on master 18984101d9e3f865303fa5efb15515844181ea27, I get:

```
~/git/flutter$ flutter analyze --flutter-repo
Analyzing 3 directories...

   info • Unnecessary cast • dev/integration_tests/codegen/lib/main.dart:48:17 • unnecessary_cast

1 issue found. (ran in 9.2s)
```

This commit passed on cirrus https://cirrus-ci.com/task/4524909334364160

**Comment by christopherfujino** [comment]
running `git clean -xffd` in the repo fixed it.

**Comment by christopherfujino** [comment]
I think this is actually https://github.com/dart-lang/sdk/issues/39792

**Comment by jmagman** [comment]
Just hit this, reopening for Flutter infra workarounds to clean... something... before running the analyzer.

**Comment by christopherfujino** [comment]
> Just hit this on a devicelab machine, reopening for Flutter infra workarounds to clean... something... before running the analyzer.
> [analyzer_benchmark_a14ac4e_2.log](https://github.com/flutter/flutter/files/4300377/analyzer_benchmark_a14ac4e_2.log)

I remember I looked into this, and I think the issue is the `.dart_tool/` directories left laying round the repo, which are all `.gitignore`'d.

**Comment by digiter** [comment]
What's needed from the infra team?

**Comment by christopherfujino** [comment]
Ensure there aren't analyzer flakes in the devicelab. My guess as to why this is happened is that there isn't a `git clean -xffd` that happens between devicelab runs, as there is in cirrus: https://github.com/flutter/flutter/blob/289deef8c5374f2ece9a6f4db82694e44e1ce113/.cirrus.yml#L86

**Comment by zanderso** [comment]
Related: https://github.com/flutter/flutter/issues/52375

**Comment by christopherfujino** [comment]
> @christopherfujino Is this still an issue?

¯\_(ツ)_/¯

I'll close this since there hasn't been activity on it in close to a year.
