### ISSUE TITLE
Change language of "Retake" and  "Tirar Novamente"  (ImagePicker plugin)

### ISSUE THREAD

**Issue by matheust3** [flutter/flutter#50827]
[Image](https://i.stack.imgur.com/GNFbR.jpg)

How to use the device language?

**Comment by VladyslavBondarenko** [comment]
Hi @matheust3 
What version of ImagePicker do you use? Is it iOS or android app?

This is what I see with the last version 0.6.3+1 with android

![image](https://user-images.githubusercontent.com/17024977/74636666-227d1b00-5171-11ea-8c91-daedef39326d.png)

**Comment by matheust3** [comment]
ok, I'm not having the problem anymore
