### ISSUE TITLE
[web][edge] unskip Edge dom_renderer tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#50828]
Couple of methods are skipped for dom_renderer_test.dart for Edge

We should either skip them or change them to work in in Edge. (note: there is a chance that the browser has a bug for the tests methods use case)

**Comment by LongCatIsLooong** [comment]
New skip introduced in https://github.com/flutter/engine/pull/28494: This test currently does not work on most browsers except for firefox:

https://github.com/flutter/engine/blob/6ed3e0a32dec557f00583a2af3f8aa026a08e15d/lib/web_ui/test/dom_renderer_test.dart#L173-L193

`getComputedStyle('::placeholder').opacity` seems to only return the correct value on Firefox.

**Comment by yjbanov** [comment]
No plans to support old Edge.
