### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by Juanqui303** [flutter/flutter#50824]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
![Screenshot](https://user-images.githubusercontent.com/61044944/74519908-e51d5100-4f16-11ea-97aa-2c02cce5fe6f.png)
As it says in the screenshot, I have reinstalled several times using different ways to install the IDE of the web "https://developer.android.com/studio/#downloads" that supposedly includes the SDK mentioned. After that, I noticed that, in the second step of the installation, at the "select components to install" doesn't appear the "Android SDK" as appears in the first video of "https://developer.android.com/studio/install". So I tried to install manually a couple of times the SDK using different ways. The last way was replacing the content of "C:\Users\juanq\AppData\Local\Android\sdk" with the content of the "sdk-tools-windows-4333796.zip" of "https://developer.android.com/studio/#downloads".
Once said all that, I would thank you if you tell me a way to install the SDK so the "flutter doctor" recognizes the Android license, because my boss is pressing me to do a Project using Flutter.
![Screenshot](https://user-images.githubusercontent.com/61044944/74519805-b901d000-4f16-11ea-8265-fc5dfa73c257.png)

**Comment by zanderso** [comment]
"Android license status unknown" can happen when the license check program fails to run. I've seen this happen when `JAVA_HOME` (or some other Java-related environment variable) is set to something that confuses the tool. Any environment variables like this should be unset, or set to values in the Android SDK.

Another thing is that powershell is probably better supported right now than cmd.exe.

**Comment by Juanqui303** [comment]
@zanderso JAVA_HOME seems to have a right value... which variable is set to a wrong value?
![image](https://user-images.githubusercontent.com/61044944/74563337-dbbed380-4f6c-11ea-8dff-c9a0790cc7e7.png)

**Comment by zanderso** [comment]
@Juanqui303 were you able to resolve this on your own? If so, could you report back on how you did it? If not, let's keep the issue open.

**Comment by Juanqui303** [comment]
@zanderso, problem of the license solved. I explained the solution before closing.
