### ISSUE TITLE
Modularize plugin_tools test to allow local testing

### ISSUE THREAD

**Issue by xster** [flutter/flutter#50830]
https://github.com/flutter/plugin_tools/blob/master/lib/src/firebase_test_lab_command.dart combines test traversal, building and running. But it would be nice to break out testing so that we can check compatibility against OEM, OS on local devices directly.

**Comment by stuartmorgan** [comment]
There are alternate plugin tooling commands that allow running tests locally now, which I believe resolves the use case here.
