### ISSUE TITLE
Gallery, Pesto: scrolling up and down quickly can lead to white space/missing card

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5083]
On the Gallery, Pesto app: scroll up and down in the recipe list. Move fairly quickly. Stop with a recipe card below the app bar, with enough space where you would see some of the card above. (if you scroll up and down slowly, you won't see white space when you stop.)

expected: See the card above, peaking out from the app bar.

![screen shot 2016-07-27 at 11 07 56 am](https://cloud.githubusercontent.com/assets/5479/17186499/63f78ff8-53ea-11e6-8fc0-164e9f9ee29d.png)

actual: White space:

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17186371/c433bd70-53e9-11e6-972b-7518aafdbf7f.png)

**Comment by HansMuller** [comment]
Fixed by #5963
