### ISSUE TITLE
Gallery: Consider moving the Source Code button below the app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5084]
A design review suggested that buttons in the app bar do a consistent thing across the app. The gallery has a "view source code" button, which shows up sometimes, and shows different source code when tapped.

A couple of options:
- Add more source code across the app, making the feature more universal.
- Remove the source code button for v1 of the gallery (can bring back later if we turn the app into more of an educational tool).
- Move the source code button somewhere else, off of the app bar.

**Comment by Hixie** [comment]
Given that this isn't currently on our radar, we're unlikely to ever do it unless it comes up as a higher priority during review. I'm going to close this until that happens.
