### ISSUE TITLE
RawKeyboardListener conflict with TextField when they exist on a same page, soft keyboard conflict with external keyboard

### ISSUE THREAD

**Issue by JiweiMaster** [flutter/flutter#50854]
first, my flutter environment is ok, because i can develop flutter application normally,
flutter sdk version
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (5 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
However,
when I use RawKeyboardListener to listen  external hardware keyboard input like this:

```
return MaterialApp(
      title: "dasd",
      home: Scaffold(
        appBar: AppBar(title: Text("qweqwe"),actions: <Widget>[
          IconButton(icon: Icon(Icons.add),onPressed: (){
            controller.text = "";
            setState(() {
            });
          },)
        ],),
        body: RawKeyboardListener(
            focusNode: focusNode,
            onKey: (RawKeyEvent event){
              if(event is RawKeyDownEvent && event.data is RawKeyEventDataAndroid){
                print(event.data.logicalKey);
                if(event.data.logicalKey.keyLabel != null){
                  inputStr = inputStr + event.data.logicalKey.keyLabel;
                }
                if(event.data.logicalKey.keyLabel == null && event.data.logicalKey.debugName == "Enter"){
                  //输入完成
                  print(inputStr.toUpperCase());
                  inputStr = "";
                }
              }
            },
            child: Column(
              children: <Widget>[
                TextField(
                  controller: controller,
                ),
              ],
            ),
        ),
      ),
    );
```
My App have two methods to input data,
A: soft keyboard
B: external hardware keyboard
the RawKeyboardListener date will be disordered after I use soft keyboard to input data
if I don't use soft keyboard to input, the RawKeyboardListener widget will be worked

maybe the soft keyboard input will affected the RawKeyboardListener working

thanks for your help

**Comment by JiweiMaster** [comment]
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

class MyAppState extends State<MyApp>{
  FocusNode focusNode = new FocusNode();
  TextEditingController controller = new TextEditingController();

  String inputStr = "";
  @override
  void initState() {
    super.initState();
    FocusScope.of(context).requestFocus(focusNode);
  }

  @override
  Widget build(BuildContext context) {
    FocusScope.of(context).requestFocus(focusNode);
    return MaterialApp(
      title: "dasd",
      home: Scaffold(
        appBar: AppBar(title: Text("qweqwe"),actions: <Widget>[
          IconButton(icon: Icon(Icons.add),onPressed: (){
            controller.text = "";
            setState(() {
            });
          },)
        ],),
        body: RawKeyboardListener(
            focusNode: focusNode,
            onKey: (RawKeyEvent event){
              if(event is RawKeyDownEvent && event.data is RawKeyEventDataAndroid){
                print(event.data.logicalKey);
                if(event.data.logicalKey.keyLabel != null){
                  inputStr = inputStr + event.data.logicalKey.keyLabel;
                }
                if(event.data.logicalKey.keyLabel == null && event.data.logicalKey.debugName == "Enter"){
                  //输入完成
                  print(inputStr.toUpperCase());
                  inputStr = "";
                }
              }
            },
            child: Column(
              children: <Widget>[
                TextField(
                  controller: controller,
                ),
              ],
            ),
        ),
      ),
    );
  }

}

**Comment by VladyslavBondarenko** [comment]
Hi @JiweiMaster 
Can you explain with example what do you mean by this?
> RawKeyboardListener data will be disordered after I use soft keyboard to input data

Is it possible to reproduce your case with android emulator and laptop keyboard?

**Comment by JiweiMaster** [comment]
In my App, I need to read data from a Barcode-Scanning-Gun(Barcode-Scanning-Gun is usually  used in SuperMarket to pay money, it can transform barcode to numbers ), the gun can connect with phone by bluetooth, so it can be regarded as a bluetootn keyboard,.
Then I created a TexField in flutter Application, the TextField can acquire data from the Barcode -Scanning-Gun outputs and soft keyboard provided by mobile OS in the same time. After I used the android soft keyboard to acquire data, then data from Barcode-Scanning-Gun outputs will be  disordered .
I think it is difficult to reproduce the case in android emulator,
maybe using  a entity mobile and a Bluetootn Barcode scanning gun( or Bluetooth keyboard  or common keyboard wich can connected with mobile by USB )  can reproduce  this case, Thanks for your helping

**Comment by TahaTesser** [comment]
Hi @JiweiMaster 
Using your code sample on android with soft keyboard and external keywords correctly works on latest `dev` channel


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  FocusNode focusNode = new FocusNode();
  TextEditingController controller = new TextEditingController();

  String inputStr = "";
  @override
  void initState() {
    super.initState();
    FocusScope.of(context).requestFocus(focusNode);
  }

  @override
  Widget build(BuildContext context) {
    FocusScope.of(context).requestFocus(focusNode);
    return MaterialApp(
      title: "dasd",
      home: Scaffold(
        appBar: AppBar(
          title: Text("qweqwe"),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () {
                controller.text = "";
                setState(() {});
              },
            )
          ],
        ),
        body: RawKeyboardListener(
          focusNode: focusNode,
          onKey: (RawKeyEvent event) {
            if (event is RawKeyDownEvent &&
                event.data is RawKeyEventDataAndroid) {
              print(event.data.logicalKey);
              if (event.data.logicalKey.keyLabel != null) {
                inputStr = inputStr + event.data.logicalKey.keyLabel;
                print(inputStr);
              }
              if (event.data.logicalKey.keyLabel == null &&
                  event.data.logicalKey.debugName == "Enter") {
                //输入完成
                print(inputStr.toUpperCase());
                inputStr = "";
              }
            }
          },
          child: Column(
            children: <Widget>[
              TextField(
                controller: controller,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (9 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
