### ISSUE TITLE
IOS release size is too large after upgrading Flutter to 1.12.13+hotfix.7, I don't release appstore

### ISSUE THREAD

**Issue by libleo** [flutter/flutter#50850]
Relation to https://github.com/flutter/flutter/issues/49855

My app don't release App Store

My customer request size in 80MB

how can I reduce bitcode part?

**Comment by vaidehee** [comment]
yes I too faced this issue,
but as Filiph suggested, I created the profile app using 
flutter build ios —profile,
And it works fine,
So during Development, use this command to build an ipa.

**Comment by libleo** [comment]
Thank you very much

Do you know how to build module with Profile
I use 
```
flutter create -t module my_flutter
```
create app, build in Xcode-build, not use flutter command

**Comment by libleo** [comment]
I found solution, add new Configuration name "Profile"

**Comment by iapicca** [comment]
Hi @libleo 
I'm glad to hear that you solved the issue
thank you for letting me know

**Comment by iapicca** [comment]
from https://github.com/flutter/flutter/issues/50914

> Relation to https://github.com/flutter/flutter/issues/50850
> 
> I use Profile Configure build, but can not get crash detail
> https://console.cloud.google.com/storage/browser/flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/
> this link file ios-profile has no symbol,  I can't get crash detail.
> 
> but I found this nobitcode version in that. I want to know how to release with nobitcode version

**Comment by iapicca** [comment]
Hi @libleo 
please take a look to this [docs](https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app) 
also this [answer](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077) might be relevant to you

**Comment by libleo** [comment]
Thank you.
My build environment is different.
A remote mac build with xcode-build, not stripped bitcode part.

I try to modify cache script add "ios-release-nobitcode" 

this worked, hope can help other people like me

file is "flutter/packages/flutter_tools/lib/src/cache.dart"

diff content
```
diff --git a/packages/flutter_tools/lib/src/cache.dart b/packages/flutter_tools/lib/src/cache.dart
index 5e1950b56..ba5a12fd5 100644
--- a/packages/flutter_tools/lib/src/cache.dart
+++ b/packages/flutter_tools/lib/src/cache.dart
@@ -958,7 +958,7 @@ class IOSEngineArtifacts extends EngineCachedArtifact {
   @override
   List<String> getLicenseDirs() {
     if (cache.includeAllPlatforms || platform.isMacOS) {
-      return const <String>['ios', 'ios-profile', 'ios-release'];
+      return const <String>['ios', 'ios-profile', 'ios-release', 'ios-release-nobitcode'];
     }
     return const <String>[];
   }
@@ -1317,6 +1317,7 @@ const List<List<String>> _iosBinaryDirs = <List<String>>[
   <String>['ios', 'ios/artifacts.zip'],
   <String>['ios-profile', 'ios-profile/artifacts.zip'],
   <String>['ios-release', 'ios-release/artifacts.zip'],
+  <String>['ios-release-nobitcode', 'ios-release-nobitcode/artifacts.zip'],
 ];
 
 const List<List<String>> _androidBinaryDirs = <List<String>>[
```

**Comment by libleo** [comment]
close

**Comment by yuhaocan** [comment]
> add new Configuration name "Profile"

add new Configuration to where

**Comment by libleo** [comment]
https://www.jianshu.com/p/51a2bbe877aa

**Comment by everythingok001** [comment]
> ios-release-nobitcode



> Thank you.
> My build environment is different.
> A remote mac build with xcode-build, not stripped bitcode part.
> 
> I try to modify cache script add "ios-release-nobitcode"
> 
> this worked, hope can help other people like me
> 
> file is "flutter/packages/flutter_tools/lib/src/cache.dart"
> 
> diff content
> 
> ```
> diff --git a/packages/flutter_tools/lib/src/cache.dart b/packages/flutter_tools/lib/src/cache.dart
> index 5e1950b56..ba5a12fd5 100644
> --- a/packages/flutter_tools/lib/src/cache.dart
> +++ b/packages/flutter_tools/lib/src/cache.dart
> @@ -958,7 +958,7 @@ class IOSEngineArtifacts extends EngineCachedArtifact {
>    @override
>    List<String> getLicenseDirs() {
>      if (cache.includeAllPlatforms || platform.isMacOS) {
> -      return const <String>['ios', 'ios-profile', 'ios-release'];
> +      return const <String>['ios', 'ios-profile', 'ios-release', 'ios-release-nobitcode'];
>      }
>      return const <String>[];
>    }
> @@ -1317,6 +1317,7 @@ const List<List<String>> _iosBinaryDirs = <List<String>>[
>    <String>['ios', 'ios/artifacts.zip'],
>    <String>['ios-profile', 'ios-profile/artifacts.zip'],
>    <String>['ios-release', 'ios-release/artifacts.zip'],
> +  <String>['ios-release-nobitcode', 'ios-release-nobitcode/artifacts.zip'],
>  ];
>  
>  const List<List<String>> _androidBinaryDirs = <List<String>>[
> ```

It doesn’t work after I changed it, but when I use flutter build ios --profile there will be compression

**Comment by jmagman** [comment]
Note that due to Apple dropping support for bitcode, the default `ios-release` frameworks the tool downloads will be much smaller in the next release and will not contain bitcode.  `ios-release-nobitcode` will no longer be available.  https://github.com/flutter/flutter/issues/107886
