### ISSUE TITLE
Gallery, Pesto: White space after tapping Home in pesto drawer

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5086]
Open gallery, tap pesto, open drawer, tap home.

Expected: drawer transitions out and user is looking at a list of recipes (just like on initial load).

Actual: White space between app bar and recipe:

![screen shot 2016-07-27 at 11 41 51 am](https://cloud.githubusercontent.com/assets/5479/17187677/219563ec-53ef-11e6-8fb5-ae848e1d4292.png)

**Comment by HansMuller** [comment]
This may be a case of padding around the viewport instead of within it.
