### ISSUE TITLE
Problem build apk

### ISSUE THREAD

**Issue by daniele777** [flutter/flutter#50864]
Hi guys .... All running ok in Emulator but when i try to build apk to android store ... !!!! Surprice !!! :( 

```bash
C:\flutter\bin\flutter.bat --no-color build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        


FAILURE: Build failed with an exception.



* What went wrong:

Could not determine the dependencies of task ':app:lintVitalRelease'.

> Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.

   > Could not find androidx.test:runner:1.2.1.

     Required by:

         project :app

   > Could not find androidx.test.espresso:espresso-core:3.2.1.

     Required by:

         project :app



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 5s
Running Gradle task 'assembleRelease'...                            6,6s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...                        3ms
√ `android\settings_aar.gradle` created successfully.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...                     
The plugin cloud_firestore could not be built due to the issue above.
```

And now ????? Helppp

**Comment by as-Tony-Stark** [comment]
did you migrated your project for AndroidX if not then see [this](https://flutter.dev/docs/development/androidx-migration)

**Comment by VladyslavBondarenko** [comment]
@daniele777 did migrating help you?

**Comment by daniele777** [comment]
When i cretaed project i already flag androidx ... dosen't work ? Unfortunally now i can't try .to migrate .i'm away from my pc ...but .... Possibile i'll ti click signed apk ?

**Comment by iapicca** [comment]
Hi @daniele777 
can you please provide your `flutter doctor -v` , 
your `flutter build apk --verbose`,
and your `pubspec.yaml` 
Thank you

**Comment by daniele777** [comment]
**ok... flutter doctor v..**
` Microsoft Windows [Versione 10.0.18363.657]
(c) 2019 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\Daniel_tech\Documents\csf_2020\csf2020>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Versione 10.0.18363.657], locale it-IT)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (7 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Android\Sdk
    • ANDROID_SDK_ROOT = E:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Daniel_tech\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
 `
pubspec.yaml

name: csf_2020
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.10+2
  google_maps_flutter: ^0.5.21+12
  geolocator: ^5.1.5
  rxdart: ^0.22.6
  rflutter_alert: ^1.0.2
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.3+1
  firebase_admob: ^0.9.0+10

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter-icon.png
    - assets/destination.png
    - assets/fontana.png
    - assets/superpoi.png
    - assets/userlocation.png
    - assets/googlelogo.png
    - assets/image.png
    - assets/google_logo.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


[  +37 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +39 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +12 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +77 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +178 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\
[  +48 ms] Found plugin firebase_admob at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.0+10\
[  +12 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.4\
[  +17 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[  +11 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+2\
[  +17 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +39 ms] Found plugin geolocator at C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-5.2.1\
[   +7 ms] Found plugin google_api_availability at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.2\
[   +8 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+17\
[   +9 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.1.1\
[  +16 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.3\
[  +41 ms] Found plugin location_permissions at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location_permissions-2.0.4+1\
[ +253 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\
[  +11 ms] Found plugin firebase_admob at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.0+10\
[   +4 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.4\
[   +6 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+2\
[   +4 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +8 ms] Found plugin geolocator at C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-5.2.1\
[   +2 ms] Found plugin google_api_availability at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.2\
[   +1 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+17\
[  +34 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.1.1\
[   +5 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.3\
[   +5 ms] Found plugin location_permissions at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location_permissions-2.0.4+1\
[ +334 ms] Generating C:\Users\Daniel_tech\Documents\csf_2020\csf2020\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +102 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[   +1 ms] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +39 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[  +15 ms] Using gradle from C:\Users\Daniel_tech\Documents\csf_2020\csf2020\android\gradlew.bat.
[  +13 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +141 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +3 ms] executing: [C:\Users\Daniel_tech\Documents\csf_2020\csf2020\android\] C:\Users\Daniel_tech\Documents\csf_2020\csf2020\android\gradlew.bat -Pverbose=true
-Ptarget=lib\main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[+6460 ms] Starting a Gradle Daemon, 1 busy and 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
[+48586 ms] FAILURE: Build failed with an exception.
[   +7 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app:lintVitalRelease'.
[   +1 ms] > Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.
[   +1 ms]    > Could not find androidx.test:runner:1.2.1.
[   +8 ms]      Required by:
[        ]          project :app
[   +1 ms]    > Could not find androidx.test.espresso:espresso-core:3.2.1.
[        ]      Required by:
[        ]          project :app
[   +3 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 54s
[ +457 ms] Running Gradle task 'assembleRelease'... (completed in 55,7s)
[   +3 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +8 ms] Building plugin cloud_firestore...
[  +20 ms] Running Gradle task 'assembleAarRelease'...
[   +7 ms] "flutter apk" took 57.136ms.
The plugin cloud_firestore could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


Thanks....

**Comment by daniele777** [comment]
i already have androidx... this is my gradle.properties..

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

**Comment by VladyslavBondarenko** [comment]
Hi @daniele777 
Could you try with the latest version of cloud_firestore 0.13.2+1?

**Comment by daniele777** [comment]
Solved changing 

androidTestImplementation 'androidx.test:runner:1.2.1'
 androidTestImplementation **'androidx.test.espresso:espresso-core:3.2.1'**

with !!!!

androidTestImplementation 'androidx.test:runner:1.3.0-alpha03'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha03'

**Comment by aburcheri** [comment]
I added this and it works for me:
`Open your build.gradle file and add the code below under android:

android {

lintOptions { checkReleaseBuilds false }`
