### ISSUE TITLE
Center title of appbar vertically and horizontally

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#50874]
## Use case

I'm creating a custom app bar with a size of 100 and I need to be able to vertically align the text since it looks off without the vertical alignment. Would also be great if the leading was centered too.

I've tried wrapping the title in a `Container` and setting the top margin to 50 (half the size of the appbar) but the text just gets cut off.

![weird appbar](https://user-images.githubusercontent.com/25782944/74593676-be851600-4ffb-11ea-917d-4b204478a3d8.png)

## Proposal

The `centerTitle` property of `AppBar` should center the `title` vertically as well as horizontally (or you could make a separate property like `centerTitleVertically`).

Example:
![good appbar](https://user-images.githubusercontent.com/25782944/74593673-b5944480-4ffb-11ea-8794-fef8263b9472.png)

**Comment by hauketoenjes** [comment]
In the material guidelines of AppBar ([Material Guidelines](https://material.io/components/app-bars-top/#specs)) which the flutter AppBar implements it should have a height of 56. If you dont want to use the official guideline-conform AppBar you can just implement your own AppBar since the `appBar` property in the scaffold widget is just a PreferredSize widget. 

You could do something like this:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AppBar Test',
      home: Scaffold(
        appBar: PreferredSize(
          preferredSize: Size.fromHeight(100),
          child: Stack(
            fit: StackFit.expand,
            children: <Widget>[
              Container(
                color: Colors.blue,
              ),
              Center(
                child: Text("AppBar"),
              ),
              Positioned.fill(
                child: Align(
                  alignment: Alignment.centerLeft,
                  child: IconButton(
                    icon: Icon(Icons.menu),
                    onPressed: () {},
                  ),
                ),
              ),
            ],
          ),
        ),
        body: Center(
          child: Text("App Bar Test"),
        ),
      ),
    );
  }
}
```

**Comment by Reprevise** [comment]
Thank you, that works for now.
