### ISSUE TITLE
[path_provider] Deprecated API error. Is that ok ?

### ISSUE THREAD

**Issue by MartinCCota** [flutter/flutter#50870]
Hi, I'm using Path Provider 1.6.0 in my APP and I get the following error:

`Note: D:\Other Apps\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

Do I need to update something or is it normal and ok to use the plugin with this msg ?

Thanks.

**Comment by hauketoenjes** [comment]
Package specific questions should be asked in the packages repository ([`path_provider` repo](https://github.com/flutter/plugins))

The path_provider package uses a native android implementation as far as i know. So it could be the case, that they use a deprecated api and will probably change it soon.

**Comment by MopheusDG** [comment]
Hi @hauketoenjes, thanks for your answer. I tried to open an issue on the repository you mention but there's no Issues on the repo, only pull requests. Any idea how to ask for assistance on those repos ? This issue has being hunting me for almost 2 months, they updated the plugin and it's still there, maybe I have something setup wrong, that's why I was trying to get in contact with the provider ppl.

Thanks again, Martin.

**Comment by Reprevise** [comment]
Hi! You don't have anything to worry about, I get the error too. As you see, it says "Note", not "Error". It happens with a lot of packages like `device_info` and others. As @hauketoenjes said, they use native code as it's a plugin. It's up to them to change the deprecated API out, not on you as you didn't do anything wrong.

**Comment by hauketoenjes** [comment]
Yeah, just dont worry about these things, just keep developing your app (btw, i overread the issue line at their [docs](https://github.com/flutter/plugins#issuess)) So you asked at the right repositoy :)

**Comment by MopheusDG** [comment]
Oh ok, thanks fir the info ! Everything was working fine but as I'm getting close to publish didn't want to leave it to chance.

Thanks @hauketoenjes

**Comment by TahaTesser** [comment]
Hi @MartinCCota 
It's totally fine as [#50870 Comment](https://github.com/flutter/flutter/issues/50870#issuecomment-586757016) says 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
Thank you for your contribution
