### ISSUE TITLE
After the last update of flutter to v1.12.13 + hotfix.8, printing in the console tab disappeared

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#50873]
After the last update of flutter to **v1.12.13 + hotfix.8**, printing in the console tab disappeared. Here is what appears on the console:

```
Launching lib/main.dart on LG V520 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.

```
I.e. intermediate printing of data by the dart's **_print_** statement has disappeared. This complicates the debugging process. Can you prompt me what to do?

```
Flutter doctor:

/home/micrcx/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IL)
    • Flutter version 1.12.13+hotfix.8 at /home/micrcx/flutter
    • Framework revision 0b8abb4724 (2 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/micrcx/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/micrcx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/micrcx/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/micrcx/idea-IC-191.6707.61
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • LG V520 • LGV5203c426e47 • android-arm • Android 7.0 (API 24)

• No issues found!
Process finished with exit code 0

```

**Comment by micrcx** [comment]
I noticed that this strange error appears on devices with version 7 of the android (LG G5). On devices with android 9 (Xiaomi M2) or 5 (Samsung Edge) there are no problems, all ok.

**Comment by TahaTesser** [comment]
Hi @micrcx 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
