### ISSUE TITLE
ECG API

### ISSUE THREAD

**Issue by aster94** [flutter/flutter#50888]
## Use case

Smartwatches (SW) with built-in electrocardiogram (ECG or EKG) are appearing always more often on our wrists and probably in a few years all watches would have basic ECG recording abilities. The interest for such abilities is increasing (for example: https://www.ahajournals.org/doi/10.1161/CIRCEP.118.006834)

## Proposal

Flutter should be able to expose a common API to read ECG data from different brand of SW. This could be developed as a packages/plugins.

From [wikipedia](https://en.wikipedia.org/wiki/Smartwatch#Operating_systems) these are the OS we could find on our watches (as of 16/02/2020):
- Wear OS
- watchOS
- Tizen
- AsteroidOS
- Sailfish OS
- Ubuntu Touch

_Not all the OS needs to be supported, but at least supporting wear OS would be mandatory._

If this feature request would be accepted at the beginning some simple function could be written, like:
```
import 'package:ecg/ecg.dart';

var heart_rate = await (ecg().getHR());
```
Also, in a further step we would need to discuss about which ECG file format to use, because there are [many](https://www.researchgate.net/publication/51840764_A_Review_on_Digital_ECG_Formats_and_the_Relationships_Between_Them).
I am a doctor and i have some programming skills, i would be happy to contribute with advices, feasibility, code.

**Comment by goderbauer** [comment]
This sounds like a great package that the open source community could write and maintain. I don't think the Flutter team will take this on, though.

**Comment by aster94** [comment]
@goderbauer would you mind to give some hint about how this should be achieved?
is flutter able to take ecg data from smartwatches or does it need to communicate with an app that runs on the background in the watch?
