### ISSUE TITLE
D/FlutterActivityAndFragmentDelegate( 7926): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.

### ISSUE THREAD

**Issue by bhavneet0812** [flutter/flutter#50882]
I don't know why is this happening but due to this the app is starting with a black screen.

Below is the debug console log

```
Launching lib/main.dart on HD1901 in debug mode...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/FlutterActivity( 7926): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 7926): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 7926): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 7926): Attaching FlutterEngine to the Activity that owns this Fragment.
W/FlutterView( 7926): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView( 7926): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
D/FlutterView( 7926): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@da259
D/FlutterActivityAndFragmentDelegate( 7926): Executing Dart entrypoint: main, and sending initial route: /
```

**Comment by TahaTesser** [comment]
Hi  @bhavneet0812 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpfulif you could post a minimal code sample to reproduce the problem
Thank you

**Comment by bhavneet0812** [comment]
flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/bhavneetsingh/Development/flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bhavneetsingh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] VS Code (version 1.41.1)
    • VS Code at /Users/bhavneetsingh/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • Lenovo K33a42 • ca4bd028                             • android-arm   • Android 6.0.1 (API 23)
    • HD1901        • f216efe6                             • android-arm64 • Android 10 (API 29)
    • iPhone 5s     • 5D0A0073-57DB-4F05-814B-3FFC06194B66 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
    • iPhone X      • F8E5D567-1190-488B-ADB2-AFBF983300F3 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

• No issues found!

flutter run --verbose

[  +27 ms] executing: [/Users/bhavneetsingh/Development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +46 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/bhavneetsingh/Development/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb4724
[   +8 ms] executing: [/Users/bhavneetsingh/Development/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/bhavneetsingh/Development/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/Users/bhavneetsingh/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +28 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +207 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3.1
           Build version 11C504
[  +73 ms] executing: /Users/bhavneetsingh/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/bhavneetsingh/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ca4bd028               device usb:337641472X product:karate model:Lenovo_K33a42 device:K33a42
           transport_id:6
           f216efe6               device usb:336592896X product:OnePlus7T model:HD1901 device:OnePlus7T
           transport_id:7
[  +22 ms] executing:
/Users/bhavneetsingh/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +55 ms] /usr/bin/xcrun simctl list --json devices
[ +147 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use
'-d all' to
                    act on all devices.
[   +4 ms] /Users/bhavneetsingh/Library/Android/sdk/platform-tools/adb -s ca4bd028 shell getprop
[  +77 ms] ro.hardware = qcom
[   +2 ms] /Users/bhavneetsingh/Library/Android/sdk/platform-tools/adb -s f216efe6 shell getprop
[  +82 ms] ro.hardware = qcom
[   +5 ms] Lenovo K33a42 • ca4bd028                             • android-arm   • Android 6.0.1 (API 23)
[   +2 ms] HD1901        • f216efe6                             • android-arm64 • Android 10 (API 29)
[        ] iPhone 5s     • 5D0A0073-57DB-4F05-814B-3FFC06194B66 • ios           •
           com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
[        ] iPhone X      • F8E5D567-1190-488B-ADB2-AFBF983300F3 • ios           •
           com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
[  +13 ms] "flutter run" took 808ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main
(file:///Users/bhavneetsingh/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Sample Code

This is occurring even in the stater project.

**Comment by VladyslavBondarenko** [comment]
Hi @bhavneet0812 
Is your case the same as https://github.com/flutter/flutter/issues/47024?
Do you experience this with android?
Have you tried to launch in release mode?

**Comment by bhavneet0812** [comment]
> Hi @bhavneet0812
> Is your case the same as #47024?
> Do you experience this with android?
> Have you tried to launch in release mode?

You are right.
It's not happening in the release mode.

**Comment by ramtinq** [comment]
This does not happen in the release mode but neither did it happen in the debug mode just a few days ago. I even tried opening old backups of my project and these exact same error are showing up in the Android Studio's console!

Anyone any suggestions about what might have happened?
is this an error at all?!

**Comment by fayaz07** [comment]
Even it fails in release mod

```
$ flutter run --release
Launching lib/main.dart on SM J600G in release mode...
Note: /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      72.9s
✓ Built build/app/outputs/apk/release/app-release.apk (9.5MB).
Installing build/app/outputs/apk/app.apk...                        21.6s

To quit, press "q".
W/FlutterEngine( 6696): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@88c32aa) but could not find and invoke the GeneratedPluginRegistrant.
```

**Comment by netodeolino** [comment]
Probably this is proxy problems. Follow these instructions!

https://stackoverflow.com/questions/60466163/d-flutteractivityandfragmentdelegate29168-no-preferred-flutterengine-was-prov/61331375#61331375

**Comment by ravi0508-dev** [comment]
I have the same issue but it solves after i use:
`flutter clean`
and then restart the project.
This solves my problem.

**Comment by ravipatel0508** [comment]
I have the same issue but it solves after i use:
`flutter clean`
and then restart the project.
This solves my problem.
