### ISSUE TITLE
Error on Dart 2.7: type '_File' is not a subtype of type 'File'

### ISSUE THREAD

**Issue by wally1985** [flutter/flutter#50891]
Hi, 

I'm getting an error:
type '_File' is not a subtype of type 'File'

A couple of days, it worked, tho.

Thanks!

**Comment by as-Tony-Stark** [comment]
can you share the block of code in which you're getting error?

**Comment by wally1985** [comment]
sure:
![image](https://user-images.githubusercontent.com/18695388/74608633-2c583d00-50e3-11ea-8806-9d985da3fdf5.png)

here is the pubspec:
![image](https://user-images.githubusercontent.com/18695388/74608644-4134d080-50e3-11ea-9fe4-aacdd0856241.png)

As I said, it worked a couple of days before. Flutter updated. so... I guess there is the reason.
What I already found ist this:
![image](https://user-images.githubusercontent.com/18695388/74608663-73463280-50e3-11ea-9cfc-9cfefa9f9f9e.png)

![image](https://user-images.githubusercontent.com/18695388/74608673-81944e80-50e3-11ea-83d5-4436d50696d5.png)

But I don't now how to handle, and if there is anything I can do.

Thanks!!

**Comment by wally1985** [comment]
I found, that it's something with in dependence of these packages:
  path: ^1.6.4
  path_provider: ^1.6.0
  file: ^5.1.0

when i remove them, it workes

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by kepuza** [comment]
you can do it like that 

```
import 'dart:io' as io;

io.File _imageFile;
```
