### ISSUE TITLE
incremental flutter build bundle

### ISSUE THREAD

**Issue by dvc94ch** [flutter/flutter#50893]
`flutter build bundle` takes relatively long even if nothing has changed. This is the main way `flutter-rs` and `go-flutter` interface with flutter. The alternative is I try to detect when `flutter build bundle` needs to be called in `cargo-flutter`.

**Comment by jonahwilliams** [comment]
build bundle is already incremental, though changing certain configurations like the target file can force it to rebuild from scratch. If you want to do your own detection, you can use the `--depfile` argument to get all of the dependencies and outputs -though the tool uses this information too.


How are you using build_bundle? how long is a relatively long time? What version of flutter are you on?

**Comment by dvc94ch** [comment]
Three seconds seems pretty long, opinions may differ :)
```sh
> rm -rf build
> time flutter build bundle
2.72user 0.67system 0:02.87elapsed 118%CPU (0avgtext+0avgdata 486708maxresident)k
0inputs+61224outputs (0major+206667minor)pagefaults 0swaps
> time flutter build bundle
2.60user 0.63system 0:02.85elapsed 113%CPU (0avgtext+0avgdata 483552maxresident)k
0inputs+344outputs (0major+200927minor)pagefaults 0swaps
> flutter --version
Flutter 1.14.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (3 weeks ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

**Comment by jonahwilliams** [comment]
If you don't want to run it all, I suggest using the depfile to track inputs. 3 seconds is long, but its about as well as we can do with JIT warmup + checking file hashes

**Comment by dvc94ch** [comment]
>  If you don't want to run it all, I suggest using the depfile to track inputs. 3 seconds is long, but its about as well as we can do with JIT warmup + checking file hashes

most build systems check timestamps for this reason

**Comment by jonahwilliams** [comment]
We use timestamps during flutter run, but they are not reliable enough cross-platform for the build commands.

**Comment by jonahwilliams** [comment]
FWIW, both Gradle and Bazel/Blaze use file hashes. Xcode uses timestamps and I'll never see the end of problems caused by this
