### ISSUE TITLE
Column RTL

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#5089]
Leafy has this problem where a column contains a header with elevation and a scrollable area defined by a block:

``` dart
   return new Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          new Material(
              elevation: 2,
              child: new Padding(
                  padding:
                      const EdgeInsets.only(left: 8.0, right: 8.0, bottom: 4.0),
                  child: new HeaderWidget())),
          new Flexible(child: new Block(
              padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
              children: buildCards()))
        ]);
```

The contents of the block ends up obscuring the shadow because cards are painted after the header. There should be a way for us to specify paint order to avoid this.

**Comment by abarth** [comment]
We talked about integrating this with RTL support.  Essentially you'd put the column in BottomToTop mode, which means you'd specific the bottom child first and it would paint first, but it would end up at the bottom visually.

**Comment by Hixie** [comment]
This will be fixed along with https://github.com/flutter/flutter/issues/4980 (Row RTL).

**Comment by Hixie** [comment]
Flex needs a textDirection and a fooDirection (where foo is something like "flow" or "block" but not those).
When the axis is vertical, textDirection affects the cross axis and fooDirection the main axis.
When the axis is horizontal, textDirection affects the main axis and fooDirection the cross axis.

**Comment by Hixie** [comment]
fooDirection would be an enum with two values, `down` and `up`.

**Comment by Hixie** [comment]
I called it `verticalDirection`.

**Comment by Hixie** [comment]
Landed.
