### ISSUE TITLE
Localizations.override gives NullPointerException

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#50906]
# Expected behavior:

- When using `Localizations.override`, I can override the current `locale` and `delegates` to show different localizations for a specific widget

# Current behavior

- When calling the new delegate via `OtherLocalizations.of(context).textIntroFirstPageTitle`, we get a NPE:

```
I/flutter ( 8229): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8229): The following NoSuchMethodError was thrown building OtherLocalized(dirty, dependencies:
I/flutter ( 8229): [_LocalizationsScope-[GlobalKey#d5124]]):
I/flutter ( 8229): The getter 'textIntroFirstPageTitle' was called on null.
I/flutter ( 8229): Receiver: null
I/flutter ( 8229): Tried calling: textIntroFirstPageTitle
I/flutter ( 8229): 
I/flutter ( 8229): The relevant error-causing widget was:
I/flutter ( 8229):   OtherLocalized
I/flutter ( 8229):   file:///Users/goncalopalma/FlutterProjects/tests/localizations_error/lib/main.dart:42:56
```
Example of a widget with the `Localizations.override` widget:

```dart
class OtherLocalized extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Localizations.override(
      context: context,
      locale: Locale("it"),
      delegates: [
        OtherLocalizationsDelegate(),
      ],
      child: Center(
        child: Text(
          OtherLocalizations.of(context).textIntroFirstPageTitle,
        ),
      ),
    );
  }
}
```

# Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G3020, locale en-PT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (4 available)

• No issues found!
```

Also tested in `Stable` channel

## Full working repo:
For a full working repo, please go to: https://github.com/Vanethos/localizations_error

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @Vanethos, thank you for filing an issue! Is this assuming that `OtherLocalizationsDelegate` is not included as a delegate in the widget tree above this widget? If that's the case, could you try wrapping `OtherLocalized`'s children in a `Builder` widget, since accessing `context` the way the example does will not see `OtherLocalizationsDelegate`, since it looks at the BuildContext above the widget.

**Comment by Vanethos** [comment]
Huh, very very interesting, I didn't know about that `Builder` widget "trick"

It is a very clever solution and it does solve my problem! That way it'll have the correct context, didn't thought of that!

Thanks @shihaohong 🙏
