### ISSUE TITLE
Provide signals for software rendering fallback

### ISSUE THREAD

**Issue by xster** [flutter/flutter#50900]
@liyuqian [says](https://github.com/flutter/flutter/issues/37155#issuecomment-586741351) that software rendering is well supported. This is also being done by developers. See https://github.com/flutter/flutter/issues/47804#issuecomment-569026175. 

@liyuqian or @jason-simmons, can you confirm the support matrix for emulator/device X hardware/software rendering?

If so, we definitely shouldn't let the fallback be done opaquely. Provide signals to the developer that software is used for debugging and analytics purposes. 

At least print this signal to the console. Also, we can add a callback to Android and iOS FlutterEngine for rendering mode used.  We could also show a debug/slow mode style banner that says software rendering if in debug build.

**Comment by chinmaygarde** [comment]
Software rendering should not be used on devices. The memory use/churn and battery consumption when using the software backend in massive. Moreover, engine features like inline texture composition are unavailable when using the software backend. I don't think @liyuqian was suggesting that folks use the software backend in production. Just that it is used on emulators where the specific downsides I just mentioned are not a concern. Using the software backend on emulators just allows use to sidestep a whole lot of bugs in the emulator as it tries to use the host GPU for rendering. If folks are somehow forcing software rendering unassisted (that is not using the tools) launches, it is an unsupported production workflow.

If folks are using software rendering, I suggest adding a clear and emphatic warning detailing all the downsides I just mentioned.

**Comment by Hixie** [comment]
what is the action desired for this issue?

**Comment by chinmaygarde** [comment]
We are moving towards not supporting softare rendering at all on mobile targets (even for emulators). And target that do support software rendering will do using Angle/SwiftShader. I'm closing this as obsolete.
