### ISSUE TITLE
Update sample app from `flutter create` to use new Flutter icons

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5090]
We have a new color scheme and logo assets, and we're ready to update the sample app created from `flutter create`, which creates launcher icons.

Assets are in a Google Drive folder, but we plan to license and make available via github.

**Comment by sethladd** [comment]
OK, we're ready to do this. Grab the assets from https://github.com/flutter/identity-assets

**Comment by eseidelGoogle** [comment]
@HansMuller and I updated the flutter gallery's icons.  Someone can just copy those into the create template.
