### ISSUE TITLE
How to use Flutter 1.12.13 iOS Framework nobitcode version

### ISSUE THREAD

**Issue by libleo** [flutter/flutter#50914]
Relation to https://github.com/flutter/flutter/issues/50850

I use Profile Configure build, but can not get crash detail
https://console.cloud.google.com/storage/browser/flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/
this link file ios-profile has no symbol,  I can't get crash detail.

but I found this nobitcode version in that. I want to know how to release with nobitcode version

@iapicca

**Comment by iapicca** [comment]
Hi @libleo 
I closed the issue you linked because
I interpreted your message as successful resolution.
Let's follow on the original issue (reopened)
Thank you
