### ISSUE TITLE
Gallery, Persistent bottom sheet: FAB doesn't do anything

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5092]
Open Gallery, tap into persistent bottom sheet, and notice the FAB there.
- In Dark theme, the button is still Red. Should it change color?
- Tapping the FAB does nothing. No ripple.

Do we keep the FAB? If so, why? It might make sense to remove it, unless we are showing how a FAB can move up in the presence of a persistent bottom sheet. If we keep it, can it ripple?

**Comment by HansMuller** [comment]
> unless we are showing how a FAB can move up in the presence of a persistent bottom sheet

Yes, that's why it's there.

**Comment by sethladd** [comment]
Can we make it ripple on touch?

**Comment by HansMuller** [comment]
Not sure what ripple effect you're referring to?

**Comment by Hixie** [comment]
the splash on the FAB, i assume.

The FAB should have a default action of popping up a snack bar saying it does nothing, or some such.

**Comment by sethladd** [comment]
Apologies. I meant "splash" when I said "ripple".

**Comment by Hixie** [comment]
It ripples and shows a dialog now.
