### ISSUE TITLE
[google_sign_in] on flutter web not popping up

### ISSUE THREAD

**Issue by SteinFluss** [flutter/flutter#50922]
## Goal
I try to implement a signIn with Google in Flutter Web. I use [GoogleSignn 4.1.1](https://pub.dev/packages/google_sign_in) and [Firebase Auth 0.15.4](https://pub.dev/packages/firebase_auth). I do not get any error message. It just does not pop up. 
## What I did
 - I registered the web app in Firebase (Added Dependencies) and even added the ```<meta>``` Tag with the `google-signin-client_id`
 - The Firebase Auth with Google works when I run it on Android
 - **I also ran the [Example App](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example) from GoogleSignIn in Web. It also does not pop up.**

### This is my Login Code (Works on Android) (it does not output "alreadyLoggedIn" btw)
```
    final FirebaseAuth _auth = FirebaseAuth.instance;
    FirebaseUser user = await _auth.currentUser();
    if (user != null) {
      log.d('alreadyLoggedIn');
    } else {
      final GoogleSignIn _googleSignIn = GoogleSignIn(clientId: Constants.GOOGLE_SIGN_IN_CLIENT_ID);
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      await _auth.signInWithCredential(credential);
      user = await _auth.currentUser();
      assert(user.email != null);
      assert(user.displayName != null);
      assert(!user.isAnonymous);
      assert(await user.getIdToken() != null);
    }
    return user;
    }
```

#### Here is output of flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.6 at /home/user/bin/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/user/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.6015.39
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by TahaTesser** [comment]
Hi @SteinFluss  
Could you please provide `flutter run --verbose` and try to log in? 
Thank you

**Comment by SteinFluss** [comment]
Sure, here it is:

flutter run -d chrome --verbose
[  +17 ms] executing: [/home/user/bin/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/home/user/bin/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +4 ms] executing: [/home/user/bin/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/user/bin/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +24 ms] executing: [/home/user/bin/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +16 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: /home/user/Android/Sdk/platform-tools/adb devices -l
[   +3 ms] Exit code 0 from: /home/user/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Found plugin cloud_firestore at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +4 ms] Found plugin cloud_firestore_web at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+3/
[   +8 ms] Found plugin firebase_auth at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +1 ms] Found plugin firebase_auth_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +1 ms] Found plugin firebase_core at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +1 ms] Found plugin firebase_core_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_messaging at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.8/
[  +17 ms] Found plugin flutter_local_notifications at /home/user/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.1.6/
[  +22 ms] Found plugin google_sign_in at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/
[   +1 ms] Found plugin google_sign_in_web at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/
[   +3 ms] Found plugin in_app_purchase at /home/user/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.1/
[  +13 ms] Found plugin rate_my_app at /home/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.1/
[   +1 ms] Found plugin share at /home/user/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+5/
[        ] Found plugin shared_preferences at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[        ] Found plugin shared_preferences_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[   +1 ms] Found plugin shared_preferences_web at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +8 ms] Found plugin url_launcher at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[        ] Found plugin url_launcher_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[        ] Found plugin url_launcher_web at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[  +99 ms] Found plugin cloud_firestore at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +1 ms] Found plugin cloud_firestore_web at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+3/
[   +5 ms] Found plugin firebase_auth at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +1 ms] Found plugin firebase_auth_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[        ] Found plugin firebase_core_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_messaging at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.8/
[   +5 ms] Found plugin flutter_local_notifications at /home/user/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.1.6/
[   +5 ms] Found plugin google_sign_in at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/
[        ] Found plugin google_sign_in_web at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/
[   +2 ms] Found plugin in_app_purchase at /home/user/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.1/
[   +7 ms] Found plugin rate_my_app at /home/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.1/
[        ] Found plugin share at /home/user/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+5/
[        ] Found plugin shared_preferences at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[        ] Found plugin shared_preferences_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[        ] Found plugin shared_preferences_web at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +4 ms] Found plugin url_launcher at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[        ] Found plugin url_launcher_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[        ] Found plugin url_launcher_web at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[  +82 ms] Generating /home/user/prog/todo_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +58 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[ +233 ms] Found plugin cloud_firestore at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[        ] Found plugin cloud_firestore_web at /home/user/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+3/
[   +2 ms] Found plugin firebase_auth at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[        ] Found plugin firebase_auth_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[        ] Found plugin firebase_core_web at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_messaging at /home/user/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.8/
[   +2 ms] Found plugin flutter_local_notifications at /home/user/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.1.6/
[   +2 ms] Found plugin google_sign_in at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/
[        ] Found plugin google_sign_in_web at /home/user/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/
[   +1 ms] Found plugin in_app_purchase at /home/user/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.1/
[   +5 ms] Found plugin rate_my_app at /home/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.1/
[        ] Found plugin share at /home/user/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+5/
[        ] Found plugin shared_preferences at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[        ] Found plugin shared_preferences_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[        ] Found plugin shared_preferences_web at /home/user/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +4 ms] Found plugin url_launcher at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[        ] Found plugin url_launcher_macos at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[        ] Found plugin url_launcher_web at /home/user/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[+5733 ms] Starting daemon...
[ +140 ms] Initializing inputs
[   +7 ms] Reading cached asset graph...
[ +291 ms] Reading cached asset graph completed, took 289ms

[ +213 ms] Checking for updates since last build...
[+1476 ms] Checking for updates since last build completed, took 1.5s

[   +6 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 289ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 1.5s
[+1121 ms] About to build [web]...
[   +2 ms] Running build...
[+1031 ms] 1.0s elapsed, 2/5 actions completed.
[+1056 ms] 2.1s elapsed, 4/5 actions completed.
[ +879 ms] Running build completed, took 2.8s

[        ] Caching finalized dependency graph...
[   +5 ms] Caching finalized dependency graph completed, took 155ms

[   +5 ms] Succeeded after 3.0s with 8 outputs (6 actions)

[   +7 ms] Building application for the web... (completed in 12.2s)
[        ] Attempting to connect to browser instance..
[+3490 ms] Debug service listening on ws://127.0.0.1:36247/TNMnd9klJOI=

[ +411 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                          Status code: 404

                          Headers:
                          {
                      "date": "Mon, 17 Feb 2020 14:22:09 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                          Content:
                          Not Found}

[  +42 ms] Attempting to connect to browser instance.. (completed in 3.9s)
[        ] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +4 ms] Debug service listening on ws://127.0.0.1:36247/TNMnd9klJOI=

**Comment by TahaTesser** [comment]
Hi @SteinFluss 
Did you add firebase config in your `web/index.html`
```
<body>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
  <your firebase config here>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
```
Thank you

**Comment by SteinFluss** [comment]
web/index.html looks like this:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="google-signin-client_id"
          content=""/>
    <title>Listly</title>
    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/7.8.2/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.8.2/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.8.2/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.8.2/firebase-analytics.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.8.2/firebase-messaging.js"></script>

    <script>
        // Your web app's Firebase configuration
        var firebaseConfig = {
            apiKey:
            authDomain: 
            databaseURL: 
            projectId: 
            storageBucket: 
            messagingSenderId: 
            appId: 
            measurementId: 
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
        // firebase.analytics();
    </script>
    <script src="main.dart.js" type="application/javascript"></script>
</head>
<body>
</body>
</html>
```
I just removed the private fields

**Comment by SteinFluss** [comment]
Also as i wrote, I tried to run the [example App](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example) in chrome and it did not work either.

**Comment by vasilich6107** [comment]
Hi, I have a successful experience with google sign in. Do you have any errors in your console?

Also please look on this ticket https://github.com/flutter/flutter/issues/49539 may be it will be helpful.

**Comment by SteinFluss** [comment]
Thanks a lot for your help. I still could not make it work.
- I looked at the ticket and tried to run it with:`flutter run -d chrome --web-hostname localhost --web-port 8080`
- I set up the google console part like so: https://imgur.com/a/wFzZCVk
- It still does not work and does not log any errors in the console

**Comment by SteinFluss** [comment]
It turns out, I somehow did not correctly copy the client is. Works now. Thanks for all the help! I will close this now.
