### ISSUE TITLE
Can't find Icon in widget_tester: Ternary operator bug?

### ISSUE THREAD

**Issue by BassamxMednini** [flutter/flutter#50939]
I'm not sure if this is a bug or something wrong in my application.  I have a AppBar(), which includes two Icons:

    bool someVariable = false;

    return Scaffold(
      appBar: AppBar(
        title: Text("Title"),
        actions: !someVariable? <Widget>[
          IconButton(icon: Icon(Icons.add_circle),
            onPressed: () { },
            color: Color.fromRGBO(191, 192, 197, 1.0),
            highlightColor: Colors.transparent,
          ),
          IconButton(icon: Icon(Icons.more_vert),
            onPressed: () { },
            color: Color.fromRGBO(191, 192, 197, 1.0),
            highlightColor: Colors.transparent,
            key: Key("secondKey"),
          ),
        ] : null),
    );

I'm using the ternary operator to hide the icons if `someVariable` is **true**. However in my _widget_test.dart_ I just want fo find the icon with `.byKey`:

    testWidgets('Find second Icon', (WidgetTester tester) async {
      await tester.pumpWidget(MaterialApp(home: HomePage()));
      var icon = find.byKey(Key("secondKey"));
      expect(icon, findsOneWidget);
    });

Unfortunately it doesn't work. I get the error:

> The following TestFailure object was thrown running a test:
>   Expected: exactly one matching node in the widget tree
>   Actual: _KeyFinder:<zero widgets with key [<'moreButtonOpenActionSheet'>] (ignoring offstage
> widgets)>
>    Which: means none were found but one was expected

The weird thing: when I remove `someVariable` from the `action:` tree, it works. I have absolutely no idea what happen here. I'm really confused. Isn't possible to find the icon with `someVariable`? Did I forgot something or is this maybe a bug?

**Comment by Reprevise** [comment]
Please add the output of `flutter doctor -v` and I couldn't reproduce the error.

**Comment by BassamxMednini** [comment]
Thanks for your response. It seems I didn't understand everything about Widget Tests. I thought the variable `someVariable` built automatically when I use `await tester.pumpWidget(MaterialApp(home: HomePage()));`. I mean, it is already declared and initialized in `HomePage()`.

So, I need to built `someVariable` in _widget_tester.dart_ too, right?

**Comment by Reprevise** [comment]
Yes, do you get the error when `someVariable` is set to false?

**Comment by BassamxMednini** [comment]
I found a solution for my case. My goal was to test the `onTap()` function and then navigate to an other Route etc. I thought Widget Testing was the correct way, but it wasn't. Integration testing, that's what I really need. So, thank you very much for your help, everything is fine.
