### ISSUE TITLE
Can't run my app on iOs. (Works on android)

### ISSUE THREAD

**Issue by Kobreizhyashi** [flutter/flutter#50937]
Hi, 

I've a problem that I couldn't find the solution on Google. When I try to run my app on a ios emulator throught android studio : 

`    error: /Users/michael_scott/Documents/workspace/world_best_boss_app/ios/ios: No such file or directory (in target 'Runner' from project 'Runner')
`
I don't understand why, because I don't remember I opened Xcode ever on my laptop (only for install) ^^

if someone is facing the same issue.. please leave a comment :-) 

Regards, 
Kill

**Comment by julianbraasch** [comment]
There should only be one ```ios``` directory inside your Flutter project. Try removing the second ```ios``` subfolder.

**Comment by TahaTesser** [comment]
Hi @Kobreizhyashi 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
