### ISSUE TITLE
GoogleMaps: Add option for animation duration

### ISSUE THREAD

**Issue by carlowenig** [flutter/flutter#50933]
## Use case

I would like to be able to set the animation duration of the `animateCamera` call on `GoogleMapController`. Currently it is very slow on Android devices, which harms the app user experience in my case.
Using the Android SDK it is possible to define an animation duration parameter in the `animateCamera` method. (See: [GoogleMap.animateCamera](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#animateCamera(com.google.android.gms.maps.CameraUpdate,%20int,%20com.google.android.gms.maps.GoogleMap.CancelableCallback)))

## Proposal

I propose to add an optional named parameter `duration` to `GoogleMapController.animateCamera`.

**Comment by VladyslavBondarenko** [comment]
Hi @carlowenig 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/39810,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
