### ISSUE TITLE
update_dart_sdk.ps1 not digitally signed

### ISSUE THREAD

**Issue by psiva2019** [flutter/flutter#50934]
```
```

& : File C:\Users\UserID\Desktop\Learning\flutter\bin\internal\update_dart_sdk.ps1 cannot be loaded. The file
C:\Users\UserID\Desktop\Learning\flutter\bin\internal\update_dart_sdk.ps1 is not digitally signed. You cannot run
this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:100
+ ... sdk.ps1'; & 'C:\Users\UserID\Desktop\Learning\flutter/bin/internal/u ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
```

**Comment by VladyslavBondarenko** [comment]
Hi @psiva2019 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/39692
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
