### ISSUE TITLE
Flutter suitable for building web applications?

### ISSUE THREAD

**Issue by LarsHenning98** [flutter/flutter#50932]
I am currently developing an app, but it has to interact with a website. I am really still a complete beginner in programming and have to learn more about the subject. But hopefully you can help me!

I read that with Flutter I can not only develop apps for iOS and Android, but also web applications.
How well does it work? Can I build a web application from the data set for the apps 1: 1 or should I prepare myself to have to build the web application differently?

**Comment by LarsHenning98** [comment]
I am currently developing an app, but it has to interact with a website. I am really still a complete beginner in programming and have to learn more about the subject. But hopefully you can help me!

I read that with Flutter I can not only develop apps for iOS and Android, but also web applications.
How well does it work? Can I build a web application from the data set for the apps 1: 1 or should I prepare myself to have to build the web application differently?

**Comment by Reprevise** [comment]
I've only made one application for the web with Flutter and to be honest, it's not bad. You do need to think about responsiveness for mobile, tablets, and desktops but you can use the `LayoutBuilder` for things like that and build screens for different files using screen breakpoints. There's also the [responsive_builder](https://pub.dev/packages/responsive_builder) package which makes it even easier. Obviously you wouldn't need to update your data models and back-end stuff, just the UI. Flutter's goal is to make a framework that uses *almost* the exact same codebase for desktop, web, and mobile applications and I think it accomplishes that very well (I haven't tried desktop yet).

In my experience, web apps aren't that bad, you can't select everything on the page (I think you need to use a specific widget for selectable text) and the text is a bit blurry (might be a bug or something that I'm doing). Overall, it's really cool and for me, better than React & React Native for what it was trying to do in comparison to Flutter.

**Comment by jonahwilliams** [comment]
The issue tracker really isn't for these sorts of open ended questions. I would recommend looking on a community site at flutter.dev/community for places to discuss topics like these
