### ISSUE TITLE
GoogleMaps: Detect if camera move was started by user

### ISSUE THREAD

**Issue by carlowenig** [flutter/flutter#50931]
Hi there,

I'd like to detect if a camera move was started by the user by dragging the map.
Is there any implementation of this or any trick I could use to detect it?

I tied wrapping the `GoogleMap` widget inside a `GestureDetector`, but this does not seem to work, because the GestureDetector consumes the events, so they will not be propageted to the map widget.

As I have seen, there exists such a feature in the Android Maps SDK when using the `onCameraMoveStarted` callback. It contains a `reason` parameter which is `REASON_GESTURE` if the map was moved by a user gesture. If there's no other way, I would propose to add this feature.

Thanks!

**Comment by Pilaba** [comment]
Wrap the map in a **Listener** widget

```
        Listener(
            onPointerDown: (e) {
              print("USER IS DRAGGING");
              print(e);
            },
            child: GoogleMap(
              compassEnabled: false,
              myLocationButtonEnabled: false,
              myLocationEnabled: true,
              mapToolbarEnabled: false,
              rotateGesturesEnabled: true,
              minMaxZoomPreference: MinMaxZoomPreference.unbounded,
              mapType: MapType.normal,
              initialCameraPosition: CameraPosition( target: LatLng(19.2869271, -103.7435041), zoom: 14.4746 ),
            ),
        ),
```

**Comment by carlowenig** [comment]
Works perfectly, thanks!
