### ISSUE TITLE
The scrollview tutorial in the docs might be incorrect

### ISSUE THREAD

**Issue by anoobishnoob** [flutter/flutter#50947]
## Steps to Reproduce

1. Run this code 
```
// Copyright 2018 The Flutter team. All rights 



// Use of this source code is governed by a BSD-style license that can be`
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'dart:io';

import 'package:flutter/foundation.dart';
//import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
    if (kReleaseMode)
      exit(1);
  };
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        Text('Row One'),
        Text('Row Two'),
        Text('Row Three'),
        Text('Row Four'),
      ],
    );
  }
}
```

2. just copy and paste this into your flutter project, and get a red screen of death on your pixel phone 

**Expected results:** 
_The creation of a scrollview like in this example _ 

> https://flutter.dev/docs/get-started/flutter-for/android-devs#what-is-the-equivalent-of-a-scrollview

**Actual results:** 

<details>
  <summary>Logs</summary>
What I think the problem is 
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5568 pos 12: 'child == _child': is not true.

Full log
I/flutter (13183): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13183): The following assertion was thrown building Listener:
I/flutter (13183): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 223 pos 10: 'textDirection
I/flutter (13183): != null': is not true.
I/flutter (13183): 
I/flutter (13183): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13183): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13183): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13183):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13183): 
I/flutter (13183): The relevant error-causing widget was:
I/flutter (13183):   ListView file:///C:/Users/sqandil/AndroidStudioProjects/handapp/lib/main.dart:24:12
I/flutter (13183): 
I/flutter (13183): When the exception was thrown, this was the stack:
I/flutter (13183): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:223:10)
I/flutter (13183): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:134:16)
I/flutter (13183): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:145:58)
I/flutter (13183): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5159:28)
I/flutter (13183): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5680:11)
I/flutter (13183): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:196:11)
I/flutter (13183): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter (13183): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter (13183): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter (13183): #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4487:11)
I/flutter (13183): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4349:16)
I/flutter (13183): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter (13183): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter (13183): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter (13183): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter (13183): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter (13183): #94     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1054:16)
I/flutter (13183): #95     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1025:5)
I/flutter (13183): #96     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:17)
I/flutter (13183): #97     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2512:19)
I/flutter (13183): #98     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:967:13)
I/flutter (13183): #99     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:848:7)
I/flutter (13183): #100    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:830:7)
I/flutter (13183): #109    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter (13183): #110    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter (13183): #111    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
I/flutter (13183): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (13183): 
I/flutter (13183): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Listener:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5568 pos 12: 'child == _child': is not true.

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @anoobishnoob

Your code sample is incomplete, 

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
    if (kReleaseMode) exit(1);
  };
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: ListView(
          children: <Widget>[
            Text('Row One'),
            Text('Row Two'),
            Text('Row Three'),
            Text('Row Four'),
          ],
        ),
      ),
    );
  }
}
```

**Comment by anoobishnoob** [comment]
Thanks @TahaTesser for noticing the error
