### ISSUE TITLE
android using flutter and vscode as editor

### ISSUE THREAD

**Issue by Kipkosgeitim** [flutter/flutter#50952]
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tim/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/tim/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses.
this is what i get after running flutter doctor

**Comment by julianbraasch** [comment]
So what's the problem? Just run ```flutter doctor --android-licenses```, press ```Y``` a bunch of times and you are good to go.

**Comment by Kipkosgeitim** [comment]
it has worked by downgrading..
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.1-all.zip
from 5.6.2.
at the gradle directory

**Comment by Kipkosgeitim** [comment]
thanks you
