### ISSUE TITLE
No podspec found for `image_gallery` in `.symlinks/plugins/image_gallery/ios`.This plugin works fine in Android but it is giving error in ios.Basically I want to fetch all the images from gallery.

### ISSUE THREAD

**Issue by ubaidsuhail** [flutter/flutter#50955]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @ubaidsuhail 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you
