### ISSUE TITLE
I'm getting this issue.help me how to fix this.[program] flutter create --ios-language swift --android-language kotlin . Waiting for another flutter command to release the startup lock...  Sending crash report to Google. Crash report sent (report ID: 679f956be12c18ff) Oops; flutter has exited unexpectedly. Crash report written to C:\flutterProjects\first\program\flutter_01.log; please let us know at https://github.com/flutter/flutter/issues. exit code 1

### ISSUE THREAD

**Issue by MaidaFarooqi9** [flutter/flutter#50956]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @MaidaFarooqi9 

Another flutter command is running and restart your computer 
run the command `flutter create --ios-language swift --android-language kotlin`

Thank you

**Comment by VladyslavBondarenko** [comment]
@MaidaFarooqi9 check please https://github.com/flutter/flutter/issues/17422#issuecomment-435553976 or another solutions from the issue
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
