### ISSUE TITLE
flutter can't run on ios13.3&13.4

### ISSUE THREAD

**Issue by lyj0309** [flutter/flutter#50951]
+ 1.i try to run my app in my ipad pro10.5 with ios13.3.1 use "run app" but it's keep in "Installing and launching...  ",in my ipad ,there is a app.when i tap it,it just out.
 Then i use xcode to run ,but

<img width="860" alt="截屏2020-02-18下午1 13 30" src="https://user-images.githubusercontent.com/50474995/74705933-790d5680-5250-11ea-9ed7-dae6ef43a496.png">

just white screen.
i try to use "flutter run -v"
this is out

[  +58 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +181 ms] ------ Debug phase ------
[        ] Starting debug of 3c00b5490ce1a2513ad2e91425c6d9cf67b3b728 (J208AP, iPad Pro (10.5"), iphoneos, arm64) a.k.a. 'lyj’s iPad' connected through USB...
[ +874 ms] [  0%] Looking up developer disk image
[ +337 ms] [ 90%] Mounting developer disk image
[   +9 ms] [ 95%] Developer disk image already mounted
[ +419 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +360 ms] (lldb) command source -s 0 '/tmp/0E9F96E4-F94D-4A84-9B01-E25F1839B278/fruitstrap-lldb-prep-cmds-3c00b5490ce1a2513ad2e91425c6d9cf67b3b728'
[        ] Executing commands in '/tmp/0E9F96E4-F94D-4A84-9B01-E25F1839B278/fruitstrap-lldb-prep-cmds-3c00b5490ce1a2513ad2e91425c6d9cf67b3b728'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/lyj/Library/Developer/Xcode/iOS DeviceSupport/13.4 (17E5223h)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/lyj/Library/Developer/Xcode/iOS DeviceSupport/13.4 (17E5223h)/Symbols"
[        ] (lldb)     target create "/Users/lyj/AndroidStudioProjects/flutter_app2/dppedia_app/bug/build/ios/iphoneos/Runner.app"
[+3618 ms] Current executable set to '/Users/lyj/AndroidStudioProjects/flutter_app2/dppedia_app/bug/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/0F4651B8-8D30-40E0-A731-346335D77511/Runner.app"
[ +299 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:57909"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/lyj/Library/Developer/Xcode/iOS DeviceSupport/13.4 (17E5223h)/Symbols/usr" /System "/Users/lyj/Library/Developer/Xcode/iOS
DeviceSupport/13.4 (17E5223h)/Symbols/System" "/private/var/containers/Bundle/Application/0F4651B8-8D30-40E0-A731-346335D77511"
"/Users/lyj/AndroidStudioProjects/flutter_app2/dppedia_app/bug/build/ios/iphoneos" "/var/containers/Bundle/Application/0F4651B8-8D30-40E0-A731-346335D77511"
"/Users/lyj/AndroidStudioProjects/flutter_app2/dppedia_app/bug/build/ios/iphoneos" /Developer "/Users/lyj/Library/Developer/Xcode/iOS DeviceSupport/13.4 (17E5223h)/Symbols/Developer"
[  +17 ms] (lldb)     command script import "/tmp/0E9F96E4-F94D-4A84-9B01-E25F1839B278/fruitstrap_3c00b5490ce1a2513ad2e91425c6d9cf67b3b728.py"
[   +4 ms] (lldb)     command script add -f fruitstrap_3c00b5490ce1a2513ad2e91425c6d9cf67b3b728.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_3c00b5490ce1a2513ad2e91425c6d9cf67b3b728.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_3c00b5490ce1a2513ad2e91425c6d9cf67b3b728.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_3c00b5490ce1a2513ad2e91425c6d9cf67b3b728.safequit_command safequit
[        ] (lldb)     connect
[  +33 ms] (lldb)     run
[ +130 ms] success
[        ] (lldb)     safequit
[ +111 ms] Process 1422 detached
[  +53 ms] Application launched on the device. Waiting for observatory port.
[   +4 ms] Checking for advertised Dart observatories...
[+5022 ms] No pointer records found.
[   +2 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.

 + 2.this is `flutter analyze`
➜  bug flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 1.8s)

+3. this is `flutter doctor -v`
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/lyj/flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lyj/Documents/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/lyj/Documents/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • lyj’s iPad • 3c00b5490ce1a2513ad2e91425c6d9cf67b3b728 • ios • iOS 13.4

and i fond some one have same question too see [this](https://github.com/flutter/flutter/issues/16507#issuecomment-587131848)

**Comment by lyj0309** [comment]
by the way ,i can run on ios simulator&android simulator&my android phone,and my computer is Hackintosh

**Comment by lyj0309** [comment]
ohhhhh...i fond same question on https://github.com/flutter/flutter/issues/49504 it's looks like the question is apple,hope it can fix quickly

**Comment by ivanwhm** [comment]
Yeah! In the iOS 13.4 Beta 3 everything is working again!

**Comment by MonsterOfCode** [comment]
> Yeah! In the iOS 13.4 Beta 3 everything is working again!

How did you do the update ?

**Comment by kakyoism** [comment]
My iPhone 6s stopped working after upgrading to iOS 13.4 yesterday.
Neither `flutter doctor` nor `flutter devices` shows the connected device. Meanwhile the other iPhone 7 running iOS 13.3.1 works fine.

**Comment by OscarZhou** [comment]
It works for me to update my IOS to 13.4

**Comment by kakyoism** [comment]
> My iPhone 6s stopped working after upgrading to iOS 13.4 yesterday.
> Neither `flutter doctor` nor `flutter devices` shows the connected device. Meanwhile the other iPhone 7 running iOS 13.3.1 works fine.

It was due to missing DeviceSupport in my Xcode. Had to download the image from a community repo: https://github.com/iGhibli/iOS-DeviceSupport
