### ISSUE TITLE
Some problems with add2app using preheat engine

### ISSUE THREAD

**Issue by evansherry** [flutter/flutter#50953]
I added a flutter module to the existing app and started the flutter engine in a warm-up way. I have some problems and need help.

1. The flutter plug-in home page will be started by warming up the engine. At this time MediaQuery.of (_context) .size returns null, which causes an exception where the page uses size. Is there any way to avoid this problem?

2. The launch flutter page did not execute dispose after the FlutterActivity was destroyed, and re-entered the page did not execute initState, which caused the task of this page to not be destroyed.

**Comment by TahaTesser** [comment]
Hi @evansherry 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by evansherry** [comment]
`flutter doctor -v`
[✓] Flutter (Channel master, v1.14.6, on Mac OS X 10.14.6 18G103, locale
    zh-Hans-CN)
    • Flutter version 1.14.6 at /Users/xx/code/Flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)

**Comment by evansherry** [comment]
@TahaTesser  I listened to didChangeAppLifecycleState callback. When FlutterActivity is destroyed, didChangeAppLifecycleState will be executed. At this time, state == AppLifecycleState.detached and Navigator.pop (context) is executed. There is no life cycle callback for state.

**Comment by xster** [comment]
> The flutter plug-in home page will be started by warming up the engine. At this time MediaQuery.of (_context) .size returns null, which causes an exception where the page uses size. Is there any way to avoid this problem?
> 
> The launch flutter page did not execute dispose after the FlutterActivity was destroyed, and re-entered the page did not execute initState, which caused the task of this page to not be destroyed.

Use WidgetsBindingObserver to listen to AppLifecycleState != detached. 

The host being destroyed does not guarantee dispose being called in every State object currently if that's what you meant https://github.com/flutter/flutter/issues/19358. 

If you kept your instance of the FlutterEngine, then all your elements and widget states were all still there all along. Again, use AppLifecycleState == detached to get that signal.

**Comment by evansherry** [comment]
In any case, the FlutterActivity finish means that the Flutter app / flutter plugin is dead. Even if I need to save the flutter engine, it should be recycled, so it is necessary to call State.dispose.

**Comment by xster** [comment]
> In any case, the FlutterActivity finish means that the Flutter app / flutter plugin is dead

That's actually not the case. Your entire widget tree is still live in the FlutterEngine even when you disconnect the FlutterActivity from the FlutterEngine.
