### ISSUE TITLE
Wrong quotation mark input in TextField on iOS.

### ISSUE THREAD

**Issue by Henrik-glt** [flutter/flutter#50969]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Create a simple page with a single TextField (see details below for code)
3. Click/focus the TextField
4. Make sure that you have Norwegian keyboard available on your iOS device and make sure that the selected keyboard is the Norwegian one.
5. Click the "123" button in the bottom left corner of the keyboard.
6. Click the " key.

**Expected results:** 
Expected " character to be entered in the textfield.

**Actual results:** 
A region based (Norwegian) quotation mark is entered («).
This is wrong since the " key was pressed.
The same thing happens with English keyboard, but then the character ” is entered, which is the "region based" quotation mark for English keyboard.
The correct character is entered if you long-press the quotation mark button and then click ".

This all works just fine on Android.

<details>

Se attached images for step-by-step instructions and result.

The widget being used:

```
import 'package:flutter/material.dart';

class TextInputBugExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            decoration: BoxDecoration(
              color: Color(0x4FFFFFFF),
              borderRadius: BorderRadius.circular(16),
            ),
            child: TextField(
              keyboardType: TextInputType.text,
              textAlignVertical: TextAlignVertical.top,
              maxLines: 1,
              autocorrect: false,
              decoration: InputDecoration(
                filled: false,
                hintMaxLines: 1,
                hintStyle: TextStyle(
                  fontSize: 17,
                  fontStyle: FontStyle.normal,
                  color: Colors.grey,
                ),
                hintText: "Input here",
                border: InputBorder.none,
              ),
              style: TextStyle(
                fontSize: 17,
                fontStyle: FontStyle.normal,
                color: Colors.black,
              ),
              textAlign: TextAlign.left,
              onChanged: (text) {
                print("Entered text: $text");
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

  <summary>Logs</summary>

Flutter doctor result:

[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76,
    locale en-NO)
    • Flutter version 1.12.13+hotfix.7 at
      /Users/----/Documents/Development/FLUTTER_SDK/flutter
    • Framework revision 9f5ff2306b (3 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/----/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • BAD1986D-D762-4F48-A73F-9B2F632D989C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

Step by step screenshots:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-18 at 15 34 29](https://user-images.githubusercontent.com/61195282/74745752-9ba96a80-5264-11ea-98c8-ed73b34588d4.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-18 at 15 34 39](https://user-images.githubusercontent.com/61195282/74745757-9ea45b00-5264-11ea-8039-d329509e2a73.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-18 at 15 34 57](https://user-images.githubusercontent.com/61195282/74745760-9f3cf180-5264-11ea-87b1-a8ac290c0ff3.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-18 at 15 34 59](https://user-images.githubusercontent.com/61195282/74745763-9fd58800-5264-11ea-8b02-09d9aa78958e.png)

</details>

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
This seems to be the same behavior as native iOS apps as well.  @Henrik-glt can you confirm whether that's true?  If so, we should probably just keep this consistent with native.

**Comment by Henrik-glt** [comment]
@justinmc Tried iOS note app now and you are absolutely right. Would be nice to be able to disable this though. When entering obscured text (password), this can cause some confusion.
But I guess that goes under feature request?
Sorry to bother you with a wrongly submitted bug report.

**Comment by justinmc** [comment]
No worries, thanks for submitting!  I've marked this as a feature request.  I agree that a way to disable it could be nice, especially for password fields.  I think let's leave this issue open for now and see if attracts any attention from other people who want this feature, or anyone who wants to submit a PR.

**Comment by LongCatIsLooong** [comment]
@justinmc I tried this on an iOS simulator (with a native app), it seems turning smart quotes off disables the behavior.

**Comment by justinmc** [comment]
Ah good catch!  So you should be able to disable this behavior using the [smartQuotesType](https://master-api.flutter.dev/flutter/material/TextField/smartQuotesType.html) property.

I think we can go ahead and close this then, since it's already configurable.  @Henrik-glt let me know if that doesn't work for you and I'll reopen, though.

**Comment by Henrik-glt** [comment]
@LongCatIsLooong @justinmc  Great! Thanks! :)
