### ISSUE TITLE
Skia PathMask cache leaks memory

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50972]
https://b.corp.google.com/issues/149684076

cc @cbracken

**Comment by chinmaygarde** [comment]
Fixes pending in https://skia-review.googlesource.com/c/skia/+/272654/.

**Comment by cbracken** [comment]
The patch has now landed upstream in Skia.

**Comment by cbracken** [comment]
PR is out to roll to the engine: https://github.com/flutter/engine/pull/16773

**Comment by cbracken** [comment]
This rolled to the framework in https://github.com/flutter/flutter/pull/51391.

**Comment by cbracken** [comment]
Closing to match internal status.
