### ISSUE TITLE
 [!] No podspec found for `image_gallery` in `.symlinks/plugins/image_gallery/ios`

### ISSUE THREAD

**Issue by ubaidsuhail** [flutter/flutter#50983]
Error:
 [!] No podspec found for `image_gallery` in `.symlinks/plugins/image_gallery/ios`
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error running pod install
Error launching application on iPhone 8.

**Comment by ubaidsuhail** [comment]
Plugin Name:
image_gallery: ^0.1.0

Code:
List allImageTemp;
    allImageTemp = await FlutterGallaryPlugin.getAllImages;

**Comment by ubaidsuhail** [comment]
octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by VladyslavBondarenko** [comment]
Hi @ubaidsuhail 
Please check this solution https://github.com/flutter-devs/image_gallery/issues/1#issuecomment-519719234
If you still have the problem, consider to open an issue in the [image_gallery github](https://github.com/flutter-devs/image_gallery/issues)
Closing, as this isn't an issue with Flutter itself, but with the third party plugin,
if you disagree please write in the comments and I will reopen it
Thank you
