### ISSUE TITLE
iOS, Gallery, Pesto: drag down should not exceed image height for recipe view

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5098]
Bust out your iOS device, and then open gallery, tap into gallery, tap on a recipe. Then, drag down.

Expected: the drag to stop at the height of the image and the recipe text does not go below the image.

Actual: the drag continues far below the image, leaving a white space between the recipe text and the image.

**Comment by HansMuller** [comment]
SInce we don't want the platform-specific scrolling behavior here, we could just add a ClampOverscrolls widget
