### ISSUE TITLE
Divider widget can't set width.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51009]
Divider widget can't set width.

**Comment by panjalasanthosh** [comment]
Yes, Divider cant set width 
set with 
Divider(
indent:10
height:10,
color:Colors.red,
)

**Comment by TahaTesser** [comment]
Hi @gionchat 
Does resolve your issue?  [Divider Thickness Dartpad Example](https://dartpad.dev/4e09594fc3e51e5da8cd990d054b21de)

![image](https://user-images.githubusercontent.com/48603081/74813404-54ca7c00-531b-11ea-9c5f-84eb8d08b902.png)

Thank you

**Comment by fleepgeek** [comment]
Wrap your Divider with something like a `SizedBox` and give it your desired width like so:

```dart
SizedBox(
    width: 300,
    height: 20,
    child: Divider(
        height: 1,
        thickness: 20,
    ),
),
```

Tried the above code on DartPad and it worked

**Comment by gionchat** [comment]
VerticalDivider   widget   can set width.

**Comment by gionchat** [comment]
VerticalDivider widget can set width.
