### ISSUE TITLE
Do we need the causal_async_stack define?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#51001]
Currently flutter passed a define for dart.developer.causal_async_stacks in debug mode. The google3 runner doesn't do this:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/compile.dart#L316

does this disable/enable causal_async_stacks? Or is a separate flag required as a dart argument.

@mkustermann @chingjun

**Comment by mkustermann** [comment]
We'll clean this up. Once we've explicitly opted in all users (we're in the process of doing this gradually), we'll make it the default in the VM and eventually remove the flags and the old mechanism. When we do that we'll also remove this `-Ddart.developer.causal_async_stacks=` flag, which should be unnecessary once we're done.

**Comment by jonahwilliams** [comment]
@mkustermann did I see a change for this land in the engine recently?

**Comment by mkustermann** [comment]
> @mkustermann did I see a change for this land in the engine recently?

Just today I've merged https://github.com/flutter/engine/pull/19270 which makes lazy async stacks enabled by-default in JIT Mode (it's already default in AOT mode). We'll enable it on all of our custom embedders, one at a time. If no issues show up, we'll switch it on by-default in the VM and remove the legacy flags.

Then we can remove this `-Ddart.developer.causal_async_stacks=` as well (it's unused after https://github.com/flutter/engine/pull/19270, but let's keep it until the causal async stack support is completely gone).

**Comment by mkustermann** [comment]
@cskau-g has now enabled lazy async stacks everywhere and causal async stacks got removed. There is therefore no need to use this `-Ddart.developer.causal_async_stacks` in any mode anymore.

**Comment by mkustermann** [comment]
@jonahwilliams All related uses of this `-Ddart....` define have no effect and can safely be removed.
