### ISSUE TITLE
Please reconsider the documentation for in-app-purchase plugin.

### ISSUE THREAD

**Issue by AvatarDevs** [flutter/flutter#51013]
the documentation is incredibly unclear. It's not clear where a callback should go when a purchase is completed, or how to test purchases. please re-write the readme for the package to include a more complete and beginning-to-end guide as this is a huge point of frustration for many people.

**Comment by stuartmorgan** [comment]
There's been a significant overhaul of the documentation, including a code lab, so I'm closing this as resolved. If you have issues with the updated docs, please file a new issue with specifics.
