### ISSUE TITLE
[web] release build not running

### ISSUE THREAD

**Issue by SteinFluss** [flutter/flutter#51033]
I get an error when I try to run flutter web in release mode (both local and hosted with firebase). It works in debug mode.
```
Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_helper.dart
```
- I do not get any outputs other then the error above from the browser console.

**Comment by TahaTesser** [comment]
Duplicate of [#49500](https://github.com/flutter/flutter/issues/49500) [#issuecomment](https://github.com/flutter/flutter/issues/49500#issuecomment-587828746)
