### ISSUE TITLE
Get Address using Latitude and Longitude 

### ISSUE THREAD

**Issue by PrakashNaidu2662** [flutter/flutter#51034]
It will be nice if the feature implemented in this plugin. i.e conversion of latLng to address. So that we can avoid using so many plugins.

Example:

> LatLng(13.00064608385679, 77.66582395881414) to 114, Nagavaara, Bangalore- 5600XX 

Something like this.

Thanks :)

**Comment by TahaTesser** [comment]
Hi @PrakashNaidu2662 
Please explain in detail which plugin you referring to.
Thank you

**Comment by VladyslavBondarenko** [comment]
@PrakashNaidu2662 
Closing since long without an answer.
Please explain more precisely your proposal and I will reopen it.
Thank you
