### ISSUE TITLE
[flutter build apk ] FAILED

### ISSUE THREAD

**Issue by yjouyang** [flutter/flutter#51035]
Here is the error msg:

```
A problem occurred evaluating root project
'flutter_plugin_android_lifecycle'.
           > Failed to apply plugin [id 'com.android.library']
              > Minimum supported Gradle version is 5.4.1.
```

I have no idea how this dependency appear in my project and it seems that this plugin indeed uses a quit old version of gradle, which is 4.10.2

flutter version: 1.12.13+hotfix.8

**Comment by yjouyang** [comment]
I figure out that `flutter_plugin_android_lifecycle` is introduced by `image_picker`

**Comment by TahaTesser** [comment]
Duplicate of [#50867](https://github.com/flutter/flutter/issues/50867)
