### ISSUE TITLE
i have problem  in install flutter on mac

### ISSUE THREAD

**Issue by El-sayed-mahmoud** [flutter/flutter#51043]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for 7yvt6la2007dno98lt3rzbguf (/Users/elsayed/.gradle/caches/5.6.2/scripts-remapped/settings_32pu0it0553japlissecus3z/7yvt6la2007dno98lt3rzbguf/settings8410a2d21ed2f87c8a0398566330ee52).
> Could not open settings generic class cache for settings file '/Users/elsayed/AndroidStudioProjects/flutter_app/android/settings.gradle' (/Users/elsayed/.gradle/caches/5.6.2/scripts/7yvt6la2007dno98lt3rzbguf/settings/settings8410a2d21ed2f87c8a0398566330ee52).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by El-sayed-mahmoud** [comment]
Problem installing flutter and i didn't find a solution please help

**Comment by TahaTesser** [comment]
Hi @El-sayed-mahmoud 
Please try this possible [Solution](https://github.com/flutter/flutter/issues/47043#issuecomment-568781690)
Thank you

**Comment by VladyslavBondarenko** [comment]
Hi @El-sayed-mahmoud 
I hope you've solved the issue, closing it.
If this is not so please write in the comments and I will reopen it.
Thank you
