### ISSUE TITLE
URL for dart:ui frames in stack traces is no longer "dart:ui"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5105]
e.g.:
```
I/flutter : #46     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/hooks.dart:48)
```

**Comment by sethladd** [comment]
where would this fix appear? Do we need help from the Dart team?

**Comment by Hixie** [comment]
@jason-simmons Any idea what's causing this? I seem to recall you talked about this at some point.

**Comment by jason-simmons** [comment]
In AOT builds, the stack trace URL is taken from the URL argument passed to Dart_LoadSource() in gen_snapshot.

The association from "dart:ui" to the file path of the dart_ui package is provided through gen_snapshot's --url_mapping flag.  AFAIK gen_snapshot doesn't offer a way to map the paths back to the "dart:ui" package name.

IMHO it's useful to have the exact path captured by gen_snapshot in the stack traces for debugging purposes.

**Comment by Hixie** [comment]
For our purposes sure, but for the purposes of people using Flutter as a platform, `dart:ui` would be much more comprehensible than `file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/hooks.dart`. Is there same way we can use one for local debug builds and another for the builds we ship?

**Comment by eseidelGoogle** [comment]
FYI @rmacnak-google

**Comment by cbracken** [comment]
This has been fixed since at least Aug 2018.
