### ISSUE TITLE
picture_cache_perf__timeline_summary regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51052]
Pretty clear regression after https://github.com/flutter/flutter/pull/50363.

![benchmark](https://user-images.githubusercontent.com/1435716/74857526-a4e41700-52f8-11ea-84c2-cf66edc38876.png)

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/50570

**Comment by dnfield** [comment]
This looks like it may have improved after https://github.com/flutter/flutter/pull/51071

**Comment by dnfield** [comment]
Can we close this as a dupe of #50570?

**Comment by kf6gpe** [comment]
Let's do that. Thanks, Dan!
