### ISSUE TITLE
analyzer_benchmark_flutter_repo_batch_maximum regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51051]
Kind of noisy, but gets worse after this revert.   https://github.com/flutter/flutter/pull/50840

![benchmark](https://user-images.githubusercontent.com/1435716/74857308-56cf1380-52f8-11ea-848b-9d49352f6232.png)

It's mostly a little over the baseline --- maybe it's a candidate to rebaseline?

**Comment by dnfield** [comment]
Tihs appears to have re-stabilized with the Dart revert in https://github.com/flutter/flutter/pull/51071

Tracking the upstream dart issue with https://github.com/flutter/flutter/pull/51071
