### ISSUE TITLE
[engine] The Windows Web Builder is slow

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51059]
Successful builds are taking about an hour on it.

In particular, it seems to spend a bunch of time linking executables it never uses, such as unit test related executables that it doesn't run.

Unfortunately, it also seems to spend a bunch of time  building the full Dart SDK.  this seems like something we could potentially reuse from Dart's CIPD uploads somewhere, if they upload agressively enough.

/cc @jonahwilliams @godofredoc @yjbanov

**Comment by yjbanov** [comment]
This will take manual effort to fix. Our infra doesn't know how to build only what's necessary.

**Comment by yjbanov** [comment]
@dnfield would it help if we made Windows builder post-submit only? How much pain is it causing?

**Comment by dnfield** [comment]
The impact is mainly felt on time to roll, particularly when trying to get a patch/revert from the engine to google3.  Ideally, the post submits shouldn't take much more than 15-20 minutes.  More than 30 minutes is really tough, especially if anything ends up flaking.

**Comment by godofredoc** [comment]
Closing this bug as the original concern was addressed and the build is now <30 min in average. We will be doing more work on speeding up builds on Q2 2021.
