### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotReloadMillisecondsToFrame & moke_catalina_hot_mode_dev_cycle_ios__benchmark_hotReloadMillisecondsToFrameAfterChange regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51053]
Very clear jump at https://github.com/flutter/flutter/pull/50047, but I have a hard time understanding why that's affecting catalina peformance. Maybe a lab issue?

![benchmark](https://user-images.githubusercontent.com/1435716/74857800-1328d980-52f9-11ea-9042-169dad5f50f2.png)

**Comment by dnfield** [comment]
This has gone green again after https://github.com/flutter/flutter/commit/d8a2169741dd691ac9185d98ca56cb00ed731d70- but I suspect it was actually the engine roll before it that helped and we just have some mixed up bars in our dashboard.  Going to close, we can reopen if it's going red again.
