### ISSUE TITLE
3p tests should not fail on deprecation warnings

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51062]
/cc @hixie 

customer testing should be allowed to pass even if it is using deprecated API.

**Comment by dnfield** [comment]
I'm starting to wonder if we should ban customers from adding tests that do analysis at all.

I'm not clear on what analysis would catch as an error that we would care about (as opposed to say, a compilation error or test failure).

**Comment by Hixie** [comment]
Why would we want to ban deprecation warnings? Deprecation isn't supposed to be a way to get away with making a breaking change without having to write a migration guide and help people migrate. On the contrary.

**Comment by dnfield** [comment]
But sometimes part of the migration involves deprecating a method as a "soft" break.  My understanding is that we consider adding `@Deprecated` to be a soft breaking change.

**Comment by dnfield** [comment]
Our policy also specifically excludes Dart, but Dart can add `@Deprecated` as part of an engine roll causing this to fail. Or a third party package can add `@Deprecated`, if the pubspec is not pinned to a specific dependency.

**Comment by Hixie** [comment]
> But sometimes part of the migration involves deprecating a method as a "soft" break. My understanding is that we consider adding `@Deprecated` to be a soft breaking change.

This wasn't my intention. I've cleared up the text in the policy a little to try to avoid this confusion.

> Our policy also specifically excludes Dart, but Dart can add `@Deprecated` as part of an engine roll causing this to fail. Or a third party package can add `@Deprecated`, if the pubspec is not pinned to a specific dependency.

Deprecation is just one of many things that our dependencies could do that would introduce breaks. It's not special in that regard.

**Comment by dnfield** [comment]
https://flutter.dev/docs/resources/compatibility#deprecation-policy still reads as:

> We will, on occasion, deprecate certain APIs rather than outright break them overnight. Deprecations are not considered breaking changes, though the eventual removal of the deprecated feature could be (if it breaks any of the submitted tests).

**Comment by dnfield** [comment]
And my reading of https://github.com/flutter/flutter/wiki/Tree-hygiene#5-document-the-change-including-clear-documentation-for-migrating-code-with-samples-and-clear-rationales-for-each-change indicates that we should use deprecations to facilitate soft breakages, without a requirement to update contributed tests for those, but perhaps I'm missing something.

**Comment by Hixie** [comment]
Yeah, the compatibility policy on the Web site is definitely out of step with the other documentation. I'll see about fixing that.

**Comment by goderbauer** [comment]
I believe this has been fixed now that we require the following [1]:

> The tests must pass even if there are analysis 'info' level issues in the code. Generally, this means that if the test performs static analysis, it does so ignoring info level items (i.e., flutter analyze --no-fatal-infos).


[1] https://github.com/flutter/tests#adding-more-tests
