### ISSUE TITLE
Request to roll new Dart into Engine to get a fix to Observatory

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5106]
I'm told that https://github.com/dart-lang/sdk/commit/cb468c2c47d5cbf1d8d5f6cea2d56c102513f86f fixes Observatory's UI for us. Until we update, Observatory won't open for Flutter apps.

**Comment by pq** [comment]
A dev build with this fix should be ready next Wednesday AM.  Can we wait that long or should we weigh the costs of backing up to a previous SDK build?

**Comment by eseidelGoogle** [comment]
I don't think it's a good idea to have Observatory broken for all (master-developed) Flutter apps for a week.  Lets either roll to an intermediate Dart now or revert. :)  I don't have strong opinions either way.

**Comment by pq** [comment]
Sounds good.  Revert PR up for review here https://github.com/flutter/flutter/pull/5109.

**Comment by johnmccutchan** [comment]
Observatory is built from the Dart runtime tree and not the SDK. I don't think you need to revert to fix Observatory.

**Comment by pq** [comment]
Thanks @johnmccutchan!  I misunderstood.  Closing out my PR and leaving it to @sethladd to find the right person to update the engine DEPS.  Sorry for the confusion!

**Comment by sethladd** [comment]
We're good to go. Observatory works again. Thanks all!
