### ISSUE TITLE
Generated iOS package is too large

### ISSUE THREAD

**Issue by arcticfox1919** [flutter/flutter#51068]
I use the `flutter build ios --release` command to package iOS, but it's too big

```
 bruceying@bogon  ~/WorkSpace/fluttecode/riko/build/ios/iphoneos/Payload/Runner.app/Frameworks  ls -lh
total 0
drwxr-xr-x  6 bruceying  staff   192B Feb 20 02:55 App.framework
drwxr-xr-x  6 bruceying  staff   192B Feb 20 02:55 Flutter.framework
drwxr-xr-x  6 bruceying  staff   192B Feb 20 02:55 WebRTC.framework
 bruceying@bogon  ~/WorkSpace/fluttecode/riko/build/ios/iphoneos/Payload/Runner.app/Frameworks  cd Flutter.framework
 bruceying@bogon  ~/WorkSpace/fluttecode/riko/build/ios/iphoneos/Payload/Runner.app/Frameworks/Flutter.framework  ls -lh
total 672136
-rw-r--r--  1 bruceying  staff   327M Feb 20 02:55 Flutter
-rw-r--r--  1 bruceying  staff   955B Feb 20 02:55 Info.plist
drwxr-xr-x  3 bruceying  staff    96B Feb 20 02:55 _CodeSignature
-rw-r--r--  1 bruceying  staff   881K Feb 20 02:55 icudtl.dat
 bruceying@bogon  ~/WorkSpace/fluttecode/riko/build/ios/iphoneos/Payload/Runner.app/Frameworks/Flutter.framework  lipo -info Flutter
Architectures in the fat file: Flutter are: armv7 arm64
```

The Flutter library contains armv7 and arm64, but it has 327M，or are there any weight-loss tips?

My environment：

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.42.0-insider)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

**Comment by christopherfujino** [comment]
@arcticfox1919 there's a doc on the website regarding how to actually measure the size of your app (the size on disk is actually larger than it will be when downloaded onto an iOS device, see link for more context): https://flutter.dev/docs/perf/app-size#ios. Hope that helps!
