### ISSUE TITLE
Fuchsia engine builders have slowed down

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51070]
In particular, the debug symbol process takes a combined ~16 minutes.  It would be nice if we could somehow parallelize that.

/cc @gw280 @iskakaushik @godofredoc

**Comment by dnfield** [comment]
One thought is to move the creation of the archives (which takes a large part of the time) up ahead of the `collect` on the test build, at least for the ones we can create on that bot - and then to have the creation of the other symbols happen on their various builders and added to the isolated output of each drone.

**Comment by godofredoc** [comment]
Obsolete
