### ISSUE TITLE
Web developers would like an easy onboard to Flutter, and map their knowledge to Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5107]
Folks with a Web background are often confused as to when to use our Block vs. Column vs. Row vs whatever.

(We've had similar questions from folks coming from an Android or iOS background too.)  Would be nice to have a document which does some minimal mental mapping for these developers.

FYI @Hixie @qchong

**Comment by sethladd** [comment]
Yay! This is live: https://flutter.io/web-analogs/
