### ISSUE TITLE
GridView inside AnimatedCrossFade throws Exception

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#51077]
I have a `GridView` inside an `AnimatedCrossFade`, and I get this error:

>The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.
>
>Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.
>
>If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.

I don't want to use `shrinkWrap` as this cuts my widget's elevation shadows and `BouncingScrollPhysics` as per #51078. Things are working fine, but I still get the exception.

Is this something that's missing from the docs or is `AnimatedCrossFade` not compatible with `GridView`?

Here's a sample code that triggers the issue:

```dart
class MyScreen extends StatefulWidget {
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  @override
  Widget build(BuildContext context) {
    return Theme(
      data: Theme.of(context).copyWith(primaryColorBrightness: Brightness.dark),
      child: Scaffold(
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            MediaQuery.removePadding(
              context: context,
              removeBottom: true,
              child: AppBar(
                elevation: 10,
                backgroundColor: Theme.of(context).canvasColor,
                automaticallyImplyLeading: false,
                flexibleSpace: Container(height: 300, color: Colors.blue,),
              ),
            ),
            Expanded(
              child: FutureBuilder<void>(
                future: Future.delayed(Duration(seconds: 15)),
                builder: (context, snapshot) {
                  return AnimatedCrossFade(
                    duration: Duration(milliseconds: 300),
                    crossFadeState:
                    snapshot.connectionState != ConnectionState.done
                        ? CrossFadeState.showFirst
                        : CrossFadeState.showSecond,
                    firstChild: GridView.count(
                          crossAxisCount: 3,
                          physics: BouncingScrollPhysics(),
                          padding: EdgeInsets.all(12),
                          crossAxisSpacing: 12,
                          mainAxisSpacing: 12,
                          children: <Widget>[
                            for (int i = 0; i < 20; ++i)
                              Loading(),
                          ],
                          shrinkWrap: true,
                    ),
                      secondChild: GridView.count(
                        crossAxisCount: 3,
                        physics: BouncingScrollPhysics(),
                        padding: EdgeInsets.all(12),
                        crossAxisSpacing: 12,
                        mainAxisSpacing: 12,
                        children: <Widget>[
                          for (int i = 0; i < 5; ++i)
                            Loading(),
                        ],
                        shrinkWrap: true,
                      ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Loading extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      elevation: 8,
      clipBehavior: Clip.antiAlias,
      child: AspectRatio(
        aspectRatio: 1,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              width: 70,
              height: 70,
              color: Colors.white30,
            ),
            SizedBox(height: 4),
            Container(
              width: 70,
              height: 15,
              color: Colors.white30,
            ),
          ],
        ),
      ),
    );
  }
}
```

Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (8 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by darshankawar** [comment]
Hi @feinstein,
I tried your code on latest Stable (1.20.2) and didn't see the exception when the screen launched.

<details>
<summary>log</summary>

```
Syncing files to device SM A260G...
Restarted application in 2,455ms.
I/FIAM.Headless(21416): went foreground
D/mali_winsys(21416): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(21416): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
I/FIAM.Headless(21416): Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless(21416): Recoverable exception while reading cache: /data/user/0/com.example.hello_world/files/fiam_impressions_store_file (No such file or directory)
E/BpSurfaceComposerClient(21416): Failed to transact (-1)
E/BpSurfaceComposerClient(21416): Failed to transact (-1)
I/FIAM.Headless(21416): Fetching campaigns from service.
W/DynamiteModule(21416): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(21416): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(21416): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/FIAM.Headless(21416): Service fetch error: PERMISSION_DENIED: Firebase In-App Messaging API has not been used in project 613586627532 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseinappmessaging.googleapis.com/overview?project=613586627532 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
I/zygote  (21416): Do full code cache collection, code=125KB, data=112KB
I/zygote  (21416): After code cache collection, code=105KB, data=70KB
D/mali_winsys(21416): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
W/mali_winsys(21416): native_window_api_disconnect failed: -19
W/libEGL  (21416): EGLNativeWindowType 0xd237d008 disconnect failed
W/libEGL  (21416): EGLNativeWindowType 0xd2366808 disconnect failed
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

Can you try on latest stable or master and see if you still experience the issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by feinstein** [comment]
@darshankawar sorry, I forgot to take a look at this.

The error still persists, the code sample I gave was with `shrinkWrap: true`, set it to false and you will see the error.

Also, if `shrinkWrap: true` you can't scroll with a bouncing effect in both directions, just from the bottom, not the top. Whereas with `shrinkWrap: fase` `BouncingScrollPhysics` works in both directions, but we get an exception on the console, even though everything seems to be working.

**Comment by pedromassangocode** [comment]
Hi @feinstein 
Based on the docs of [shrinkWrap](https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html):

> If the scroll view does not shrink wrap, then the scroll view will expand to the maximum allowed size in the scrollDirection. If the scroll view has unbounded constraints in the scrollDirection, then shrinkWrap must be true.

You have now two options:
 - Wrap your GridView inside of a widget with constraints
 - Set shrinkWrap to true

For the cases you mention in https://github.com/flutter/flutter/issues/51077#issuecomment-693758026 Please file a new issue for this and completely fill out the template. We don't track more than one problem in a GitHub issue as they may be duplicates of different existing issues, or may need different teams to look at them.

Closing as working as expected.
Thank you

**Comment by feinstein** [comment]
This issue is about how there's an exception, even though the screen is just fine.

Theres another issue already about the bouncing only working in one direction.

**Comment by pedromassangocode** [comment]
> This issue is about how there's an exception, even though the screen is just fine.
> 
> Theres another issue already about the bouncing only working in one direction: #51078.

As far as I know assertions does not stop the process and since the docs are clear about the usage of the property I'm not sure can be done to fix this. Am I missing something?

**Comment by feinstein** [comment]
No, that's OK, you are right, the docs explain the issue and the assertion, it's OK to close it, the real problem is #51078, which breaks functionality.
