### ISSUE TITLE
Run Flutter web driver test without starting application first

### ISSUE THREAD

**Issue by angjieli** [flutter/flutter#51083]
## Use case
Currently, running `flutter drive` command against web devices would require developer to run `flutter run` to start the application first. This is not consistent with other platforms.

## Proposal
Allow developers to run `flutter drive` on web devices directly.

**Comment by yjbanov** [comment]
Assigned to @angjieli and February milestone since there's a PR already.

**Comment by angjieli** [comment]
Fixed in #51084
