### ISSUE TITLE
RawKeyboard.keysPressed can get out of sync

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#51080]
In raw_keyboard.dart, line 518, RawKeyboard detects key up messages and removes the relevant logical key from its internal set of keys that are pressed.

However, the logical key value is affected by which modifiers are down, and modifiers may be in a different state than they were when the key was added.

So this sequence works:

```
keydown(left shift)
keydown(a)
keyup(a)
keyup(left shift)
```

but this doesn't:

```
keydown(left shift)
keydown(a)
keyup(left shift)
keyup(a)
```

in the latter sequence the upper case A is left in the pressed-key set forever.

**Comment by krisgiesing** [comment]
@gspencergoog logging the issue we discussed offline

**Comment by chunhtai** [comment]
Looks like @gspencergoog has fixed this, closing this issue
