### ISSUE TITLE
CupertinoContextMenu with delete feature giving memory leaks

### ISSUE THREAD

**Issue by jeremyimmanuel** [flutter/flutter#51099]
## Dependencies
1. [Hive](https://pub.dev/packages/hive)

## Steps to Reproduce
1. Make a ValueListenableBuilder with Hive plugin
2. Within that builder, return a GridView with tiles
3. Make sure the children of the GridView is a `CupertinoContextMenu`; I made the TileWidget a stateless widget
4. Add a `delete` method to the `CupertinoContextMenu`

## Logic
My logic is after opening the context menu, user wants to delete the item by clicking the delete option. So what I did was:
1. Pop the CupertinoContextMenu
2. Delete item
3. UI updates because ValueListenableBuilder listens to the Hive database

**Expected results:** 
So it did work on the front-end side. However, it gave me an error.

![CupertinoContextMenu_deleteItem](https://user-images.githubusercontent.com/35509768/74901867-0e940d80-5359-11ea-8e38-38b86bd4f466.gif)

## Code 
```
@override
  Widget build(BuildContext context) {
    return CupertinoContextMenu(
      previewBuilder: (context, animation, widget) {
        return ClipRRect(
          borderRadius: BorderRadius.circular(35 * animation.value),
          child: Container(
            color: cat.color,
            child: Center(
              child: Text(
                cat.name,
                style: Theme.of(context).textTheme.body1.copyWith(
                      color: cat.luminance > 0.5 ? Colors.black : Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 60 * animation.value,
                    ),
              ),
            ),
          ),
        );
      },
      actions: <Widget>[
        // Edit
        CupertinoContextMenuAction(
          child: const Text('Edit'),
          trailingIcon: CupertinoIcons.pencil,
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        // Delete
        CupertinoContextMenuAction(
          child: const Text(
            'Delete',
            style: TextStyle(color: CupertinoColors.destructiveRed),
          ),
          trailingIcon: CupertinoIcons.delete,
          onPressed: () {
            Navigator.pop(context);
            // _showDeleteWarning(context);
            _deleteCategory(context);     
          },
        ),
      ],
      child: _buildTile(context),
    );
  }
```

### Below is the error log
<details>
  <summary>Logs</summary>
════════ Exception caught by animation library ════════════════
The following assertion was thrown while notifying status listeners for ProxyAnimation:
setState() called after dispose(): _CupertinoContextMenuState#a9837(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1112
#1      State.setState 
package:flutter/…/widgets/framework.dart:1147
#2      _CupertinoContextMenuState._routeAnimationStatusListener 
package:flutter/…/cupertino/context_menu.dart:337
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners 
package:flutter/…/animation/listener_helpers.dart:193
#4      AnimationLocalStatusListenersMixin.notifyStatusListeners 
package:flutter/…/animation/listener_helpers.dart:193
...
The ProxyAnimation notifying status listeners was: AnimationController#a0d06(⏮ 0.000; paused; DISPOSED; for _ContextMenuRoute<void>)➩ProxyAnimation
</details>

It says that it's calling setState after it's disposed but the log doesn't tell which line of code from my source code is causing this. I'm using a stateless widget for this particular Widget, so I have no dispose method, and the only place I see an animation is within a builder param `previewBuilder` in the `CupertinoContextMenu` widget. 

Can anyone explain what's happening and how to solve this memory leak?
Thank you!

**Comment by TahaTesser** [comment]
Hi @jeremyimmanuel 
can you please provide your `flutter doctor -v` and `flutter run --verbose` with action in your app? 
Thank you

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/Norbert515/flutter_villains/issues/8

**Comment by RRAVITEJA** [comment]
i ran into the same issue,
From CupertinoContextMenuAction, when we press delete action the logic in onPressed is deleting the parent of the  from CupertinoContextMenu,  now when we pop  the context to remove, CupertinoContextMenu the animator has a timer in it to perform the animation but parent is being delete in this time
the way to fix this is right click on CupertinoContextMenu goto definition, which opens up the context_menu.dart  from your flutter SDK (flutter/packages/flutter/lib/src/cupertino/context_menu.dart)
on line add the below if statement in line 340 `if (mounted)` 
we are just guarding the setState as below
`    if (mounted) {
      setState(() {
        _childHidden = false;
      });
    }`
this solved the issue for me.

it would be helpful if flutter provide some kind of future for the CupertinoContextMenu, so that we can perform our actions which updates the parent widget, in the future completion

**Comment by jeremyimmanuel** [comment]
I solved it with a workaround (So it's not technically fixing the problem)

So after popping the `CupertinoContextMenu` widget, I put in a delete confirmation `alertDialog` first and then delete it. The alert dialog has to be awaited so that it was for the user to confirm it. Since my plans were to implement a delete warning anyway, this works for me. 

I appreciate the help from everyone though!

## CupertinoContextMenuAction
```
CupertinoContextMenuAction(
        child: const Text(
          'Delete',
          style: TextStyle(color: CupertinoColors.destructiveRed),
        ),
        trailingIcon: CupertinoIcons.delete,
        onPressed: () async {
          Navigator.of(context).pop();
          await _deleteCategory(context);
        },
      ),
```

## _deleteCategory
```
Future<void> _deleteCategory(BuildContext context) async {
    bool confirm = await _showDeleteWarning(context);
    if (!confirm) return;

    // Delete all tasks under that category
    final taskBox = Hive.box(Task.boxName);
    final tbArr = taskBox.values.toList();
    final kArr = [];

    for (var i = 0; i < tbArr.length; i++) {
      final task = tbArr[i] as Task;
      if (task.taskCategory.name == this.cat.name) kArr.add(taskBox.keyAt(i));
    }
    taskBox.deleteAll(kArr);

    // Delete that category
    final catBox = Hive.box(Category.boxName);
    catBox.delete(cat.name.toLowerCase());
  }
```

## _showDeleteWarning
```
Future<bool> _showDeleteWarning(BuildContext context) async {
    return await showDialog(
      context: context,
      builder: (context) {
        if (Platform.isIOS) {
          return CupertinoAlertDialog(
            title: Text(
              'Delete ${cat.name}?',
            ),
            content: Text(
              'Deleting a category will also delete all tasks under that category.',
            ),
            actions: <Widget>[
              CupertinoDialogAction(
                child: Text('Cancel'),
                onPressed: () => Navigator.of(context).pop(false),
              ),
              CupertinoDialogAction(
                child: Text(
                  'Delete',
                  style: TextStyle(
                    color: CupertinoColors.destructiveRed,
                  ),
                ),
                onPressed: () => Navigator.of(context).pop(true),
              ),
            ],
          );
```

**Comment by ziqq** [comment]
I have this same problem when i try to delete photo inner context menu
