### ISSUE TITLE
webview_flutter onReceivedSslError 

### ISSUE THREAD

**Issue by guqh** [flutter/flutter#51093]
![image](https://user-images.githubusercontent.com/17330238/74895982-06c28080-53ce-11ea-99f5-b0d1a0fb2868.png)

这个onReceivedSslError 在 flutter 的怎么实现？

**Comment by guqh** [comment]
@iskakaushik @gw280

**Comment by VladyslavBondarenko** [comment]
Related PR https://github.com/flutter/plugins/pull/2285

**Comment by VladyslavBondarenko** [comment]
Closing since no response provided for long time.
@guqh if you disagree please write in the comments and I will reopen it.
Thank you
