### ISSUE TITLE
The image path in the assets package cannot be completed automatically, so the coding efficiency is very low.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51092]
The image path in the assets package cannot be completed automatically, so the coding efficiency is very low.

**Comment by VladyslavBondarenko** [comment]
Hi @gionchat 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter-intellij/issues/2580
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
