### ISSUE TITLE
Error when I launch command 'flutter'

### ISSUE THREAD

**Issue by max21** [flutter/flutter#511]
Hi,

When I try to launch the command 'flutter' or 'flutter start' I have this error : 

/bin/flutter: ligne 20: pub : commande introuvable

Any idea ?
Ty

**Comment by sethladd** [comment]
Can you try to see if `pub` is in your path? e.g. please run `which pub` or `pub --version`

**Comment by max21** [comment]
Hi,

pub is not in my path

**Comment by max21** [comment]
So I
