### ISSUE TITLE
iOS build failed by camera plugin

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#51103]
use **camera: ^0.5.7+3**

Failed to build iOS app
Error output from Xcode build:

```
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/praveenbhati/smartlist/smartlist/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'camera' not found
    @import camera;
     ~~~~~~~^~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

**Flutter doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G84, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
Hi @VNAPNIC 
can you please provide your `flutter build ios --verbose` ?
I see that `v0.5.7+4` has been recently released (literally yesterday),
would you mind to try if the situation changes with the latest?
Thank you

**Comment by VladyslavBondarenko** [comment]
@VNAPNIC 
I hope you solved the problem, closing the issue.
If it's not so, please write in the comments and I will reopen it.
Thank you
