### ISSUE TITLE
flutter-web beta v1.14.6 freeze on iPhone

### ISSUE THREAD

**Issue by tony-za** [flutter/flutter#51100]
I build flutter-web by using channel beta v1.14.6. It work OK on chrome on Windows10. But after run 'flutter build web' and put it to web server, then run it on iPhone , app is freeze. Then I switch channel beta back to v1.13.6, app is OK not freeze. Please fix this problem on v1.14.6.

**Comment by yjbanov** [comment]
Does this still happen on the master channel?

**Comment by VladyslavBondarenko** [comment]
@tony-za 
I hope it was fixed. Closing.
Please write in the comments if it's not so, and I will reopen it.
Thank you
