### ISSUE TITLE
flutter run --profile always rebuilds the snapshot

### ISSUE THREAD

**Issue by fsc8000** [flutter/flutter#5112]
Running an app using flutter run repeatedly without changing anything between runs rebuilds the APK (including the snapshot) each time. Ideally the APK/snapshot would only be rebuilt if one of the source files changed since the last build.

e.g. I used the stocks example benchmark, running it 10 times in a row for measurement

```
flutter run --profile -t lib/stocks/layout_bench.dart
```

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by eseidelGoogle** [comment]
Likely a bug in our dependency tracking.  I'm presuming this was Android since you mention APKs.

**Comment by Hixie** [comment]
dupe of https://github.com/flutter/flutter/issues/7673
