### ISSUE TITLE
No devices found with name or id matching 'chrome'

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#51123]
Hi, I run `flutter run -d chrome`, after having switched from the stable to master channel as shown in https://github.com/flutter/flutter/issues/41031, and I still get the issue above.

**Comment by VladyslavBondarenko** [comment]
@andesappal 
have you run after switching `flutter config --enable-web`?

**Comment by andesappal** [comment]
Thank you, Vladyslav!
