### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by henriquezanfa** [flutter/flutter#51125]
When trying to run [Fetch data from the internet](https://flutter.dev/docs/cookbook/networking/fetch-data ) (same code) I receive 

> Access to XMLHttpRequest at 'https://jsonplaceholder.typicode.com/todos/1' from origin 'http://[::1]:60612' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
That's my chrome:

![image](https://user-images.githubusercontent.com/36772896/74949823-04b3ee00-53dd-11ea-8ed7-d141d43a3f23.png)

I don't know where to go since I'm not the owner of the API and can't add "Access-Control-Allow-Origin : my_url" to it.

I'm currently using http ^0.12.0+4

**Comment by VladyslavBondarenko** [comment]
@henriquezanfa 
Thank you for pointing out on this, it is an issue from the server side of the specific api, which is not suitable now as an example
try http plugin with other api's, it works as intended

**Comment by jonahwilliams** [comment]
CORS is not something that is limited by flutter, it is a general security mechanism built into the web. If you're running a flutter application on the web, you must only make http requests to the same domain, or other domains which you have previously configured CORS for.

For more information, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
