### ISSUE TITLE
Provide option for Flutter driver to create machine-readable output

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51135]
This came up in a chat with @helinanever and @martinjeret at Nevercode, who indicated that this would be useful for some of their clients in building E2E CI/CD/test solutions.

**Comment by jmagman** [comment]
Subset of https://github.com/flutter/flutter/issues/14134.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/50449.

**Comment by NanYeYe** [comment]
@kf6gpe @jmagman 
Is here have solution now?

**Comment by dnfield** [comment]
This may not be necessary if you can use package:e2e instead.

**Comment by ened** [comment]
> This may not be necessary if you can use package:e2e instead.

@dnfield Is this functionality (machine readable output) already available in e2e (integration_test) packages? I can not find it, yet.

**Comment by dnfield** [comment]
No, but it should be possible.

I'm actually not sure why the machine reporter can't be used with package:flutter_driver though. /cc @jiahaog who might know

**Comment by jiahaog** [comment]
Currently `flutter drive` does not use the reporting mechanism from `package:test`, and the host script is executed just like any other dart script. This also means that [`-rexpanded` argument](https://github.com/flutter/flutter/blob/8f5d0371afeffa533e4efcbaf7f2394af4811af9/packages/flutter_tools/lib/src/drive/drive_service.dart#L240) that is passed by default doesn't do anything.

I put together https://github.com/flutter/flutter/pull/73017 as a quick hack to show the pieces that are needed for this.

Then something like 

```dart
flutter drive --driver=test_driver/driver.dart  --target=lib/main.dart --test-arguments='--reporter=json'
```

Could work, or we could provide something like `--machine` to `flutter drive` to avoid leaking the package:test abstraction

**Comment by rrousselGit** [comment]
Hello!

This is something that I would like to work on.
Is adding a `flutter drive --reporter=json` reasonable? Assuming this would work by relaying the flag to `test`

**Comment by cheuk0324** [comment]
Do we have an update on this feature?

**Comment by matanlurey** [comment]
It turns out this feature accidentally is supported, so I am going to document it.

Making this more first-class (and the default) is more work that I'll track elsewhere:

https://github.com/flutter/flutter/issues/152409
