### ISSUE TITLE
Add grade wrapper to default .gitignore

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51137]
In talking with @helinanever and @martinjeret, one of the things they see their clients see is having issues with the gradle wrapper becoming stale as Flutter gets updated --- by adding it to .gitignore and updating on the fly, this shouldn't be an issue, I think.

**Comment by helinanever** [comment]
On the contrary, we were interested in having gradlew and gradle-wrapper.jar out of gitignore to respect the specified versions during CI builds. Apparently, these files are not included in gitignore by default anymore, so we're happy with as things are now. Sorry about the noise. Closing the issue.
