### ISSUE TITLE
Flutter Tools should do some basic caching with the Frontend Server and Flutter Web

### ISSUE THREAD

**Issue by grouma** [flutter/flutter#51141]
The initial page load can be quite slow given the number of files produced by the Frontend Server. Flutter Tools does not request for caching and therefore follow up up refreshes are just as slow.

**Comment by grouma** [comment]
cc @jonahwilliams @ferhatb

**Comment by jonahwilliams** [comment]
Related: https://github.com/flutter/flutter/issues/50616

Are you talking about successive invocations of the tool?

**Comment by jakemac53** [comment]
This is for browser refreshes - it doesn't appear that the server is using etags or any other caching mechanism

**Comment by grouma** [comment]
No. I'm talking about refreshing the application in the browser. If I don't make a change, I would expect the resources to be cached by Chrome and the second refresh should be much faster.

**Comment by jonahwilliams** [comment]
Ahh, yes that we can do. In theory I could use the same technique I would for the manifest file - where each resource has an id associated with the hashcode of the underlying buffer

**Comment by jakemac53** [comment]
Ya it would make sense to use etags and the exact same hashes as the digest file uses for those.

**Comment by jakemac53** [comment]
Just as a side note the ideal here is actually to use cache busting uris to avoid the round trips for each resource - however its somewhat difficult to do that with require.js.

**Comment by jonahwilliams** [comment]
Basic idea here: https://github.com/flutter/flutter/pull/51143 .

If its hard to do with require js, then we should probably switch to legacy/ddc

**Comment by jakemac53** [comment]
> If its hard to do with require js, then we should probably switch to legacy/ddc

Yes we likely should do that - but later :). There are other reasons to make that switch as well.
