### ISSUE TITLE
Choppy scrolling of ListView on some newer Android devices 

### ISSUE THREAD

**Issue by hicnar** [flutter/flutter#51153]
There is still significant performance issue when it comes to scrolling contents of a ListView.
I have probably tried most of workarounds suggested (like using ListView.builder, AlwaysScrollableScrollPhysics, CustomScrollView etc) but nothing seems to work.

In the test app I created older Android devices significantly outperform newer devices. This is not just my opinion, it can be read in comments other flutter devs left under issues describing similar problems.

I have created a video comparing performance of the same app running on Google Pixel C tablet (late 2015) and Samsung Galaxy S9 (early 2018) where S9 despite of higher specs is vastly outperformed by Pixel C. Here's the url https://youtu.be/nIYUDi4oVjM

Surprisingly, I have discovered that the performance on Galaxy S9 is RADICALLY IMPROVED if a key on a keyboard paired with the device is pressed and held while the test is run - details in the video.

The code I ran can be found below. It is in a .txt file since github does not support uploading .dart files, and the file is of significant size (due to the size of the generated data the ListView is populated with for the tests) [main.txt](https://github.com/flutter/flutter/files/4233681/main.txt)

Finally, below is what flutter doctor spits out on my dev machine

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/my-home-directory/Development/Tools/flutter-1.12.13+hotfix-8-stable
    • Framework revision 0b8abb4724 (9 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/my-home-directory/Development/Tools/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/my-home-directory/Development/Tools/Android/Sdk
    • Java binary at: /home/my-home-directory/Development/Tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/my-home-directory/Development/Tools/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/my-home-directory/Development/Tools/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.6015.53
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G960F • 243104843b0d7ece • android-arm64 • Android 10 (API 29)
```

**Comment by KlausJokinen** [comment]
Choppy scrolling with Flutter has been an ongoing issue, but at least this time we have something to work with 👍

**Comment by chinmaygarde** [comment]
CC @GaryQian @jason-simmons I believe this is related to the typography subsystem in layout. This issue does seem to have a reduced test case. Can we add the same to the host benchmarks to see if there some pathology?

**Comment by azeemgujjar** [comment]
This is the major bug in flutter, a very clear performance mirror as compared to react-native.
Flutter vertical scrolling specially with images have jerking issues.

here is an example app on playstore (Flutter demo: CINEMA) you can download and test, but that i am sure its flutter bug because all similar apps or with long list views this happens.

More examples in flutter official app: Flutter Gallery

Flutter Gallery -> (Crane A personalized travel app) -> vertical scroll listview in bottom (Jerk is clearly visible)

Flutter Gallery -> (Rally A personalized finance app) -> Login -> vertical scroll it (choppy scrolling Jerks)

Above examples are not debug all are on production playstore, on stackoverflow this is under discussion but everyone is doing just tricks which is not appropriate way to develop an production grade application.

**Comment by TahaTesser** [comment]
Hi @hicnar 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by hicnar** [comment]
@TahaTesser
 
Thank you for your reply. I have just run the tests using the latest flutter 1.20.4 stable and I confirm that the choppy scrolling problem still remains. 

Following is the requested flutter doctor -v listing: 

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.4 at /Users/khycnar/Development/flutter_1.20.4
    • Framework revision fba99f6cf9 (3 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/khycnar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM G960F (mobile) • 243104843b0d7ece • android-arm64 • Android 10 (API 29)

and here is the requested log: [flutter_run_verbose.log](https://github.com/flutter/flutter/files/5241683/flutter_run_verbose.log)

I used exactly the same unchanged minimal complete reproducible code that is included in my original message (see above - main.txt)

Hope this helps!

**Comment by TahaTesser** [comment]
I can't reproduce on a realme device

**Code Sample**

[main.zip](https://github.com/flutter/flutter/files/5245389/main.zip)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.251 at C:\Code\flutter_master
    • Framework revision d26268bb9e (12 hours ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by hicnar** [comment]
@TahaTesser As I mentioned in the original post, the problem does not manifest itself on all Android devices. My Pixel C tablet from 2015 works just fine, but S9 phone from early 2018 I am using really struggles. If that helps, I may try to create at some point another short video showing the problem when the tests are run on my S9 with the latest stable Flutter release. Let me know if you think of any other data/info that would be useful to pinpoint this.

**Comment by darshankawar** [comment]
@hicnar Revisiting this issue, I used Samsung S10+ device to run a demo listview app which scrolls smoothly with latest stable version. Can you check at your end if you are still facing the originally reported issue using latest stable ?
