### ISSUE TITLE
setting windowFullscreen to true will cause the Scaffold to behave abnormally

### ISSUE THREAD

**Issue by Daniate** [flutter/flutter#51165]
When I add `<item name="android:windowFullscreen">true</item>` in the LaunchTheme style, the Scaffold's body **can not** be resized to avoid overlapping the keyboard.

After removing `<item name="android:windowFullscreen">true</item>`, the keyboard will not obscure the TextField.

```
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:windowFullscreen">true</item>
    </style>
</resources>
```

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("title"),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: Container(
              child: ListView.builder(
                shrinkWrap: true,
                reverse: true,
                itemBuilder: (context, index) {
                  return TextField(
                    decoration: InputDecoration(
                      hintText: index.toString(),
                    ),
                  );
                },
                itemCount: 15,
              ),
            ),
          ),
          TextField(
            decoration: InputDecoration(
              hintText: "input something",
            ),
          )
        ],
      ),
    );
  }
```

**Comment by TahaTesser** [comment]
Hi @Daniate  
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Thank you

**Comment by Daniate** [comment]
Hi @TahaTesser 

the result:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/daniate/Applications/flutter
    • Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/daniate/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = ~/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (2 available)
    • TA 1041 • C1NGA2E7A2005531                         • android-arm64 • Android 9 (API 28)
    • iPhone  • ccdc2745fe2f45af649ba60408a9605275a7eb83 • ios           • iOS 10.3.3

• No issues found!
```

**Comment by SCVec** [comment]
I've got the same issue. 

`<item name="android:windowFullscreen">true</item> `

in styles.xml prevents the scaffold from resizing when using a keyboard.

**Comment by darshankawar** [comment]
Hi @Daniate,
I tried your code sample on latest Stable (1.20.2) by updating `LaunchTheme` style in `styles.xml` and noticed that the scaffold's body correctly resizes after keyboard opens.

[51165.mp4.zip](https://github.com/flutter/flutter/files/5123435/51165.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

Can you try on latest stable to see if it works for you now ?
Thanks.

**Comment by DanielTyukov** [comment]
I have the same problem. Has anyone found a way to fix it???

**Comment by deep01code** [comment]
same issue

**Comment by deep01code** [comment]
please if anyone have a solution share it ... PLEASE

**Comment by deep01code** [comment]
this issue not in ios, only some android devices

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Kitti-pop** [comment]
<img width="548" alt="ภาพหน้าจอ 2563-11-21 เวลา 21 40 52" src="https://user-images.githubusercontent.com/54874488/99894676-c83d5780-2cb8-11eb-8690-8667eae850d6.png">
<img width="312" alt="ภาพหน้าจอ 2563-11-21 เวลา 21 40 57" src="https://user-images.githubusercontent.com/54874488/99894680-cb384800-2cb8-11eb-95b2-ad1f33f74dbf.png">

i've got the same issues too when set
` <item name="android:windowFullscreen">true</item>`
the `MediaQuery.of(context).viewInsets.bottom` always return 0 

Here is my `flutter doctor -v`

```
[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale th-TH)
    • Flutter version 1.22.1 at /Users/Ouu/documents/Coding/flutter`
    • Framework revision f30b7f4db9 (6 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Ouu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM N920C (mobile)      • 011711ebf1801301                     • android-arm64  • Android 7.0 (API 24)
    • iPhone 8 Plus (mobile) • FD5B6919-6CC9-45BC-ACFA-1DD557AA33C9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by mattsp** [comment]
A solution is available because i have the same issue ?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by avioli** [comment]
@TahaTesser Why open a new issue? Everyone open a brand new issue for the same thing?

Testing on Android emulator and real hardware.

Started happening after `flutter_native_splash` added that item to `styles.xml` under the `NormalTheme` style.

<details>
<summary><code>flutter doctor -v</code></summary>

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.14.6 18G6032 darwin-x64, locale en-AU)
    • Flutter version 1.22.4 at /Users/avioli/dev/fvm/versions/stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/avioli/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
</details>

**Comment by TahaTesser** [comment]
@avioli 
This issue is closed,  please file a new issue
