### ISSUE TITLE
[device_info]The same application, in two computer development environments (including after packaging). Different Android ID obtained

### ISSUE THREAD

**Issue by yuefeng007** [flutter/flutter#51163]
[device_info: ^0.4.1+1]

The same application, in two computer development environments (including after packaging). Different Android ID obtained

Even in different development environments
I want to get a unique device ID

`  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
                AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
                print(androidInfo.androidId);`.

**Comment by TahaTesser** [comment]
Hi @yuefeng007 
`androidId property` includes device  + user and app signing, that  is different each on each environment.  [Reference](https://pub.dev/documentation/device_info/latest/device_info/AndroidDeviceInfo/androidId.html)
Closing as this isn't an issue with `device_info`
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by yuefeng007** [comment]
In order to ensure that the user's Android remains unchanged. Can I only pack APK with the same computer?
