### ISSUE TITLE
the plugin cannot resolve gradle module dependencies when the apk is building

### ISSUE THREAD

**Issue by shyandsy** [flutter/flutter#51175]
the setting.gradle inside the plugin\android folder has not been run when apk is building

so the it shows the error message like dependencies cannot be resolved in plugin

the example project in the plugin was fince because I imported the module into example app

**Comment by TahaTesser** [comment]
Hi @shyandsy 
can you please provide your `flutter doctor -v` and `flutter build apk--verbose`? 
Thank you

**Comment by shyandsy** [comment]
### flutter doctor -v shows below

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\AndroidSdk
    • ANDROID_SDK_ROOT = C:\AndroidSdk
    • Java binary at: D:\Program Files\Android\android-studio-4\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.
```


### the plugin\android\build gradle use imported gradle project core
```
dependencies {
    ........
 
    api project(path: ':core')
}

```
and the error message shows below when i build apk

Project with path ':core' could not be found in project ':flutter_myplugin'.

**Comment by shyandsy** [comment]
refer to 
> https://github.com/flutter/flutter/issues/48228
> https://github.com/flutter/flutter/issues/48716

**Comment by shyandsy** [comment]
the problem has been solve by a tricky method

include the plugin imported gradle porject in app\android\setting.gradle, and specific the path of the module

its dirty but it works

**Comment by jonahwilliams** [comment]
Sounds like this issue has been resolved? In general, this is not really a problem with flutter but more of a usability issue with Gradle. At any rate, this is in-actionable so I'm closing the issue.

**Comment by mhdshah** [comment]
> the problem has been solved by a tricky method
> 
> include the plugin imported Gradle project in app\android\setting.gradle, and specify the path of the module
> 
> its dirty but it works

Pls could share the detailed steps which you followed?
