### ISSUE TITLE
 How to get the widget in the current route

### ISSUE THREAD

**Issue by SnowLittleStone** [flutter/flutter#51171]
When integrating push messages, when a message comes, click the notification message to jump to the page. I need to judge whether the current route needs to be loaded. If so, update the page directly. If not, load a new page, which can prevent the page from reloading and data synchronization

**Comment by TahaTesser** [comment]
Hi @SnowLittleStone 
Please try possible these [Solution](https://stackoverflow.com/a/52569224)
Let us know if this resolves your issue
Thank you

**Comment by SnowLittleStone** [comment]
@TahaTesser 
That solution is simply to delete the specified route. Whether there is a way to get the widget object currently displayed built by materialpageroute, so that it is easy to judge and update the object

**Comment by chunhtai** [comment]
I am still a bit confused at the use case you described, can you provide an small code example that describe the use case?

**Comment by SnowLittleStone** [comment]
When I integrate push, when there is a push message coming, I use the notification method to notify app to receive the message and pass the parameters. In the method of monitoring the notification, I need to obtain the currently displayed widget object, and determine whether the current widget object is specified according to the parameters returned by the notification. If so, then update the current widget. If not, push the widget

void main() { runApp(Application()); }

class Application extends StatefulWidget {
  @override
  _ApplicationState createState() => _ApplicationState();
}

class _ApplicationState extends State<Application> {

  @override
  void initState() {
    super.initState();
    
    //notification method
    //notification are sent elsewhere
    eventBus.on<PushEvent>().listen((event) {
        if (event.type == 1) {
            //Here I need to get the currently displayed widget, If it is TestPage1, I directly call the TestPage1 update method. If it is not TestPage1, I directly push TestPage1. How to implement getCurrentPageWidget() method ?
            if (getCurrentPageWidget() is TestPage1) {
                TestPage1 testPage1 = getCurrentPageWidget() as TestPage1;
                testPage1.update();
            } else {
                Navigator.of(globalContext).push(MaterialPageRoute(builder: (context) => TestPage1()) );
            }
            
        }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hello World',
      home: TestPage(),
    );
  }
}

**Comment by chunhtai** [comment]
@SnowLittleStone There is no easy to do this until Navigator 2.0 is in place https://github.com/flutter/flutter/issues/45938. You will be able to change the current route name.
For example if the route name for TestPage1 is /testpage1
you will be able to do something like this
```dart
eventBus.on<PushEvent>().listen((event) {
        if (event.type == 1) {
              Router.setRouteName('/testpage1')
        }
            
 
    });
```
If the current route name is not /testpage1 it will replace the current route with the TestPage1, otherwise it will call [changedInternalState](https://master-api.flutter.dev/flutter/widgets/Route/changedInternalState.html) where you can override this method to update the widget as you like.

If you really want to get this working now, the only way i can think of will be using something like this...
```dart
eventBus.on<PushEvent>().listen((event) {
       final bool seenTestPage1 = false;
       bool predicate(Route<dynamic> route) {
          if(route.isTestPage1) {
             seenTestPage1 = true
          }
          return seenTestPage1 || route. isFirst;
       }
        if (event.type == 1) {
            Navigator.of(globalContext).popUntil(predicate);
            if (!seenTestPage1) {
                 Navigator.of(globalContext).push(TestPage1);
            }
        }
    });
```
as you see, this will pop some routes on top until it found the testpage1 and you will have to find a wait to check if a route is TestPage1(maybe uses RouteSettings?). I do not recommend this solution because we do not promise how popUntil uses the predicate. It just so happens to work with our current implementation.

Let me know you have questions.

**Comment by SnowLittleStone** [comment]
I used an alternative method. I used the navigatorobservers of materialapp, and then added a queue to store the router in the inherited subclass. In the process of using, I got the queue of the router. For the time being, I can only solve whether the current router is testpage1. If so, I will pop it and then push testpage1. If not, I will directly push testpage1. I'm looking forward to when navigator 2.0 can be used

**Comment by pedromassangocode** [comment]
Hi @SnowLittleStone 
Does navigator 2.0  satisfy your use-case?

Since [Navigator 2.0](https://github.com/flutter/flutter/issues/45938#issuecomment-675030323) is out now, can we close this issue?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
