### ISSUE TITLE
url_launcher 5.4.2 causes pod install to fail

### ISSUE THREAD

**Issue by Gintasz** [flutter/flutter#51182]
#48306 Steps to Reproduce

My app builds fine without url_launcher 5.4.2, but when I include it as dependency in my project, I get this error during pod install
```
Mac-MacBook-Pro:ios gintas$ pod install

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/gintas/AppProjects/lifetrens/lifetrens/ios/Podfile:41
 #  -------------------------------------------
 #  
 >    copied_flutter_dir = File.join(__dir__, 'Flutter')
 #    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
 #  -------------------------------------------
Mac-MacBook-Pro:ios gintas$ 
```

I'm trying it on a basic new project without any additional dependencies included.

Flutter 1.15.3 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 67826bdce5 (10 days ago) • 2020-02-10 14:59:32 -0800
Engine • revision 6158f03ef5
Tools • Dart 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

**Comment by jmagman** [comment]
I just created a new project on v1.15.3 , added `url_launcher: 5.4.2` to my pubspec, and then ran `flutter build ios` just fine.  I was able to run `pod install` from the `ios` directory successfully as well.

Can we get more thorough reproduction steps?

**Comment by Gintasz** [comment]
@jmagman could you please attach this new project in which compilation is ok? In case it's an environmental issue, what should I check? I already tried uninstalling and reinstall cocoapods with no change. on this

**Comment by jmagman** [comment]
I suspect it's your Ruby version--`__dir__` shouldn't be nil.
What the output of:
```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by Gintasz** [comment]
@jmagman thanks for the hint!
I updated ruby, then had to reinstall cocoapods, it seems to compile fine now. This is the approximate list of commands that helped, in case someone finds this page on google:
```
curl -L https://get.rvm.io | bash -s stable
rvm pkg install openssl
rvm install 2.6.3 --with-openssl-dir=$rvm_path/usr
brew tap raggi/ale
brew install openssl-osx-ca
gem update --system
brew uninstall cocoapods
rm '/usr/local/bin/pod'
brew link --overwrite cocoapods
```
