### ISSUE TITLE
[Web] multi line TextField clicking doesn't show cursor on expected position

### ISSUE THREAD

**Issue by ericorruption** [flutter/flutter#51183]
## Steps to Reproduce

1. Navigate to the reduced test case: https://dartpad.dev/6d729c433faf1fb1907eb6843bf86934
2. Click on the last line of the text field.

**Expected results:** 
Clicking on the last line of the text field would show the cursor on that exact location.

**Actual results:** 
The cursor is shown at the right position horizontally, but always on the first line. You can only navigate lines with the keyboard.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.14.6 at /Users/ericquanz/Library/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ericquanz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPad Air (3rd generation) • E81D7D27-8B54-46BD-9B39-0B606E6AEB19 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome                    • chrome                               • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server                           • web-javascript • Flutter Tools
```

</details>

**Comment by ericorruption** [comment]
Gif showing the incorrect behavior:
![64hi3WhGlo](https://user-images.githubusercontent.com/2374654/75021798-44d6a780-5495-11ea-9d7f-9c119c25395d.gif)

**Comment by VladyslavBondarenko** [comment]
@ericorruption please include `flutter doctor -v` into your issues, it helps to know with what flutter version are you experiencing this

**Comment by ericorruption** [comment]
@VladyslavBondarenko updated issue with that. I thought it wasn't necessary seeing it is reproducible in dartpad.

**Comment by mdebbar** [comment]
Could you please try the instructions in https://github.com/flutter/flutter/issues/33523 in the "**How to enable**" section? Please let me know if that works or not.

**Comment by ericorruption** [comment]
@mdebbar nope, still doesn't work (using flutter beta 1.14.6) :(

**Comment by mdebbar** [comment]
Ah, of course. The fix hasn't reached the beta channel yet. To get the latest fixes, you can try using the master channel.

**Comment by ericorruption** [comment]
Ok, I can confirm that #33523  works with version 1.15.4-pre.219 from master. Thanks for the help!
Do you have any idea of when this fix would be available in beta and stable? @mdebbar

**Comment by mdebbar** [comment]
I'm glad it's working for you!

> Do you have any idea of when this fix would be available in beta and stable?

The release process of various channels is documented in this wiki page: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
