### ISSUE TITLE
bool.fromEnvironment can only be used as a const constructor

### ISSUE THREAD

**Issue by grundid** [flutter/flutter#51186]
The following code generates an error with "Unsupported operation : bool.fromEnvironment can only be used as a const constructor" on Flutter for the web. On Android and iOS this works without issues.

```dart
  print("dart.vm.product: ${bool.fromEnvironment("dart.vm.product")}");
```

Current workaround is to rewrite this as:
```dart
  const vmProduct = bool.fromEnvironment("dart.vm.product");
  print("dart.vm.product: $vmProduct");
```

**Comment by grundid** [comment]
The compiled JS code looks like this btw:

```javascript
core.print("dart.vm.product: " + dart.str(core.bool.fromEnvironment("dart.vm.product")));
```

**Comment by yjbanov** [comment]
This is because browsers do not have access to system environment properties. `fromEnvironment` constructor can only be accessed during compilation and therefore they are constant as far as Dart code is concerned.

**Comment by vsmenon** [comment]
BTW, this should also be the same with mobile in production (aot) mode.
