### ISSUE TITLE
[Web] cannot copy text from readOnly TextField

### ISSUE THREAD

**Issue by ericorruption** [flutter/flutter#51184]
## Steps to Reproduce

1. Navigate to the reduced test case: https://dartpad.dev/3ce20c83ed6f1738d3989c543a4ab2e8.
2. Select some text from the text field.
3. Try to copy it.

**Expected results:** 
Text should be on clipboard / context menu should show the option to copy.

**Actual results:** 
Nothing happens.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @ericorruption 
`Ctrl + C` does copy the text. Which browser you're using? 
Can you copy text from keyboard?
Thank you

**Comment by ericorruption** [comment]
The last line is another problem. I'm unable to copy from the top line.

**Comment by mdebbar** [comment]
The underlying issue is the same as https://github.com/flutter/flutter/issues/47234 so I'll close this as a duplicate.
