### ISSUE TITLE
alarm manger is not working if mobile power saving mode is on in app kill

### ISSUE THREAD

**Issue by manojkumawat003** [flutter/flutter#51194]
alarm manger is not working if mobile power saving mode is on, when app is not in background.
If i disable power saving mode then it works good.

**Comment by TahaTesser** [comment]
Hi @manojkumawat003 
Hi ... can you please provide your `flutter doctor -v`?
Thank you

**Comment by markusaksli-nc** [comment]
Hi @manojkumawat003 
This issue no longer seems reproducible on the latest master `1.20.0-8.0.pre.125` with the latest [android_alarm_manager 0.4.5+11](https://pub.dev/packages/android_alarm_manager/versions/0.4.5+11). Tested on Android 9 (API 28) SM G950F and Android 11 (API 30) emulator.

[Sample code](https://pub.dev/packages/android_alarm_manager/example)

Can you confirm if the issue persists and provide a minimal reproducible code sample with your case?
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
