### ISSUE TITLE
SOLVED - Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by r0ly4udi** [flutter/flutter#51195]
please help me a new bie flutter....
when done install, i running but this error :
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:225)
at java.util.zip.ZipFile.(ZipFile.java:155)
at java.util.zip.ZipFile.(ZipFile.java:169)
at org.gradle.wrapper.Install.unzip(Install.java:214)
at org.gradle.wrapper.Install.access$600(Install.java:27)
at org.gradle.wrapper.Install$1.call(Install.java:74)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:225)
at java.util.zip.ZipFile.(ZipFile.java:155)
at java.util.zip.ZipFile.(ZipFile.java:169)
at org.gradle.wrapper.Install.unzip(Install.java:214)
at org.gradle.wrapper.Install.access$600(Install.java:27)
at org.gradle.wrapper.Install$1.call(Install.java:74)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by TahaTesser** [comment]
Hi @r0ly4udi 
Could you try possible [Solution](https://github.com/flutter/flutter/issues/40517#issuecomment-569887047)?
Thank you

**Comment by r0ly4udi** [comment]
I tried but it doesn't work

**Comment by r0ly4udi** [comment]
> Hi @r0ly4udi
> Could you try possible [Solution](https://github.com/flutter/flutter/issues/40517#issuecomment-569887047)?
> Thank you

because I checked through the flutter doctor there were no problems, therefore it made me confused

**Comment by VladyslavBondarenko** [comment]
@r0ly4udi 
you can try https://github.com/flutter/flutter/issues/13645#issuecomment-362311838 or  https://github.com/flutter/flutter/issues/13645#issuecomment-587455792

**Comment by r0ly4udi** [comment]
> @r0ly4udi
> you can try [#13645 (comment)](https://github.com/flutter/flutter/issues/13645#issuecomment-362311838) or [#13645 (comment)](https://github.com/flutter/flutter/issues/13645#issuecomment-587455792)

I have read the article, but the problem is I do not know the location of the gradle that must be replaced. Even though I have downloaded gradle 6.2 Can you show me, gradle position?

**Comment by r0ly4udi** [comment]
in my app flutter, gradle location : 
C:\appfluter\flutter_baru\android\gradle\wrapper
no dists. I confused, how?

**Comment by TahaTesser** [comment]
Hi @r0ly4udi 
Go to flutter_app>android> and delete `gradle` folder, delete `gradlew` files and  run the app again using `flutter run`

**Comment by r0ly4udi** [comment]
> Hi @r0ly4udi
> Go to flutter_app>android> and delete `gradle` folder, delete `gradlew` files and run the app again using `flutter run`

the gradle directory was deleted and I running flutter run, 
show this error : 
Using hardware rendering with device Android SDK built for x86. If you get graphics
artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         0.9s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)       
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         0.9s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1

**Comment by r0ly4udi** [comment]
this problem has been solved. So what I downloaded is the gradle in our flutter app, then extarct it in C: \ Users \ yourpc \ .gradle \ wrapper \ dists \ gradle-5.6.2-all
Then run your flutter app again. And make sure your internet connection is good. May be useful

**Comment by lappiahnuamah** [comment]
Please I just encountered the same problem just now but I have check the gradle wrappera and the DistributionUrls is the same as the : distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip.
When I ran the flutter doctor -v all is right except for the licenses for the android that's not right`
![problem1](https://user-images.githubusercontent.com/44087770/75831380-46fd0800-5dab-11ea-9a72-94c395b7088a.png)

2. 
![problem2](https://user-images.githubusercontent.com/44087770/75831400-58461480-5dab-11ea-9958-3cd6df8f3d14.png)

3.
![problem3](https://user-images.githubusercontent.com/44087770/75831417-6005b900-5dab-11ea-8969-7ea83b563d2b.png)


`

**Comment by lappiahnuamah** [comment]
or better still the raw code....

:\Users\OLIVIA>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\OLIVIA\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\OLIVIA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.


:\Users\OLIVIA>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\OLIVIA\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\OLIVIA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

C:\Users\OLIVIA>flutter run --verbose
[  +17 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +176 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +129 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +18 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +135 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[ +118 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +178 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +135 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +119 ms] "flutter run" took 248ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:690:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:285:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by TahaTesser** [comment]
Hi @lappiahnuamah 
Can you please try this [solution](https://github.com/flutter/flutter/issues/51195#issuecomment-591247333)?
Thank you

**Comment by chris097** [comment]
Hi @lappiahnuamah
Goto SKD manager > sdk tools > uncheck hide obselete packages > check android sdk tools (obsolete) > click apply
after downloading > run flutter doctor -v
it solved mine

**Comment by ricardogobbo** [comment]
I just ran `flutter upgrade` and `flutter clean` and it solved this issue in my case.

**Comment by sunsj1** [comment]
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.4s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         1.6s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1

**Comment by Hashim-ibn-ali** [comment]
Try replacing the file

- first go to C:\Users\hash\.gradle\wrapper\dists\

- then delete all gradle file. replace the gradle that you can download it from here [(https://services.gradle.org/distributions/`)]

**Comment by TahaTesser** [comment]
Could everyone still having this issue, check this [comment](https://github.com/flutter/flutter/issues/54712#issuecomment-614337346)

**Comment by JalalMadhaji** [comment]
gradle zip file was not downloaded successfully in C:\Users\<User-account>\.gradle\wrapper\dists

so delete the gradle file(the uncompleted gradle version) .. then let it download it again by running flutter run

in my case flutter tries to download gradle-5.6.2-all which include the zip file inside

**Comment by TreeStrepek** [comment]
Delete gradle folders under C:\Users<User-account>.gradle\wrapper\dists.  Reopen ANDROID directory project in Android Studio.  Let the Gradle setup.  It may take 5-10 minutes. 
Be patient

**Comment by shakthi-cheeniabs** [comment]
.grade/wrapper/dist will be a hidden file and there will be several such folders in project,android folder and your home

Find the folder and delete the corrupted file and run it

**Comment by avinashk369** [comment]
better update the distributionUrl url to the latest one or the one you have with other flutter project in gradle_arapper.properties file.
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by Sandeep-peddi** [comment]
There must be error while downloading Graddle File. Check the following code in the gradle/wrapper/gradle-wrapper.properties

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-6.6.1-all.zip

In my case there is a additional '\' after 'https' and the number was older version, But correcting it worked for me. U can refer the below website to know the latest available version of file type "all.zip" and Update the number or whole link properly and as it is around 130 mb. you need to have an active internet connection and wait for a while by pressing Run once. There is no need to worry until u see any red lines.

https://services.gradle.org/distributions/ 
![Gradle_Download_Error](https://user-images.githubusercontent.com/70323980/91632890-a7d76700-ea01-11ea-8e96-358a1da62d38.jpg)

**Comment by ArshlanSiddique** [comment]
> Please I just encountered the same problem just now but I have check the gradle wrappera and the DistributionUrls is the same as the : distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip.
> When I ran the flutter doctor -v all is right except for the licenses for the android that's not right`
> ![problem1](https://user-images.githubusercontent.com/44087770/75831380-46fd0800-5dab-11ea-9a72-94c395b7088a.png)
> 
> 
> ![problem2](https://user-images.githubusercontent.com/44087770/75831400-58461480-5dab-11ea-9958-3cd6df8f3d14.png)
> 
> 
> ![problem3](https://user-images.githubusercontent.com/44087770/75831417-6005b900-5dab-11ea-8969-7ea83b563d2b.png)
> 
> `

did your problem solve or not?

**Comment by Deosaur-coder** [comment]
> this problem has been solved. So what I downloaded is the gradle in our flutter app, then extarct it in C: \ Users \ yourpc \ .gradle \ wrapper \ dists \ gradle-5.6.2-all
> Then run your flutter app again. And make sure your internet connection is good. May be useful


but how to do this,can u explain little more clear

**Comment by FelicianoFhel** [comment]
> this problem has been solved. So what I downloaded is the gradle in our flutter app, then extarct it in C: \ Users \ yourpc \ .gradle \ wrapper \ dists \ gradle-5.6.2-all
> Then run your flutter app again. And make sure your internet connection is good. May be useful

Is the graddle is zip ?

**Comment by Sandeep-peddi** [comment]
yes go to https://services.gradle.org/distributions/ and download the
gradle-<latest version>-all.zip file, usually the the one having more space

**Comment by Hamza405** [comment]
it is simple just go to gradle-wrapper.properties in android folder and in distributionUrl gradle-5.6.2 make it gradle-5.6.1 should be work

**Comment by webgraphics8** [comment]
> please help me a new bie flutter....
> when done install, i running but this error :
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:225)
> at java.util.zip.ZipFile.(ZipFile.java:155)
> at java.util.zip.ZipFile.(ZipFile.java:169)
> at org.gradle.wrapper.Install.unzip(Install.java:214)
> at org.gradle.wrapper.Install.access$600(Install.java:27)
> at org.gradle.wrapper.Install$1.call(Install.java:74)
> at org.gradle.wrapper.Install$1.call(Install.java:48)
> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> at org.gradle.wrapper.Install.createDist(Install.java:48)
> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> [!] Gradle threw an error while trying to update itself. Retrying the update...
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:225)
> at java.util.zip.ZipFile.(ZipFile.java:155)
> at java.util.zip.ZipFile.(ZipFile.java:169)
> at org.gradle.wrapper.Install.unzip(Install.java:214)
> at org.gradle.wrapper.Install.access$600(Install.java:27)
> at org.gradle.wrapper.Install$1.call(Install.java:74)
> at org.gradle.wrapper.Install$1.call(Install.java:48)
> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> at org.gradle.wrapper.Install.createDist(Install.java:48)
> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> [!] Gradle threw an error while trying to update itself. Retrying the update...
> Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)





---------------------------------------------------------------------

Browse to the official Gradle Distributions webpage and check what is the latest version of gradle all.zip file, for example (at the time of writing) gradle-6.7-all.zip and copy the address

Go to your Flutter project drop down,

drop down android>gradle>wrapper

Select gradle-wrapper-properties

Paste the URL you copied earlier. For example,

distributionurl=https://services.gradle.org/distributions/gradle-6.7-all.zip

**Comment by lonewarrior18** [comment]
> this problem has been solved. So what I downloaded is the gradle in our flutter app, then extarct it in C: \ Users \ yourpc \ .gradle \ wrapper \ dists \ gradle-5.6.2-all
> Then run your flutter app again. And make sure your internet connection is good. May be useful

its not working in linux

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 1delcab** [comment]
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

The issue as shown here is Android status unknown

**Comment by AliEasy** [comment]
First go to `gradle.wrapper.properties` and check gradle version (E.G `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` is `6.7`)

Then go to `C:\Users\current_user\.gradle\wrapper\dists` and delete the folder named the the same as gradle version(`6.7` in above example)

And build project (`flutter run`) again

**Comment by bukunmialuko** [comment]
Using finder, while showing hidden files, delete the gradle folder in :

users/{your-username}/.gradle/dists/{gradle-folder}

In your flutter project run : flutter run 

Note: Make sure you have a good internet connection.
