### ISSUE TITLE
[web & desktop] Hide all characters in a TextField, when obscureText is true

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#51218]
## Problem
In Flutter Web the last character of a TextField is visible, when obscureText = true. This should not be the case. Specially when your screen is shared with a beamer, etc. everybody can see your password.

Example:
![image](https://user-images.githubusercontent.com/24459435/75061223-8f314600-54e0-11ea-8ba2-f52b8d5dc595.png)

## How it should be
Every website hides all characters in a password field.

**Comment by yjbanov** [comment]
@HansMuller @goderbauer I removed the web flag because this is a general desktop problem. On desktop password fields generally do not show letters.

**Comment by AndroidNils** [comment]
This feature is now available ✌️

**Comment by MertDuman** [comment]
> This feature is now available ✌️

So how you achieve it?

**Comment by AndroidNils** [comment]
@MertDuman You can have a look at my PR: https://github.com/flutter/flutter/pull/56794 :)
