### ISSUE TITLE
Support Dart tool from path instead of using Flutter tool forwarders

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#51213]
Historical reasons for the split:

* We have slightly different flags and naming conventions
* We don't have the same SDK

Drawbacks of current approach:

* Increased maintenance burden for the flutter tool
* Increased confusion caused by the Flutter/Dart ecosystem having different tool (`flutter packages get` versus `pub get`)

Benefits of current approach:

* Users only need to add a single tool to the path
* Tool can adjust UX for certain commands, like test, which are highly custom.

Open questions:

* Can we add `dart` to the path automatically?
* Could we ensure a happy path for `test` versus `flutter test`? That is, make sure the user calls the right one.

Not obvious what the best approach is. For some subset of the dart tool like migrate and pub, I would rather not have wrappers at all.

Caveats:

* Instead of adding flutter/bin/cache/dart-sdk/bin to the PATH, we might want to bounce through a script in flutter/bin first, in order to trigger a dart-sdk version check. Without this check, the dart version in the cache may either be missing or otherwise become stale through interaction with either git/upgrade/downgrade commands.

* What is the deprecation period for flutter tool forwarding commands?

**Comment by jmagman** [comment]
`flutter pub publish` gives hooks for additional Flutter-specific linting and error checks, though we aren't actually doing anything with that opportunity now.

**Comment by jonahwilliams** [comment]
One additional caveat - instead of adding `flutter/bin/cache/dart-sdk/bin` to the PATH, we might want to bounce through a script in `flutter/bin` first, in order to trigger a dart-sdk version check. Without this check, the dart version in the cache may either be missing or otherwise become stale through interaction with either git/upgrade/downgrade commands.

**Comment by DanTup** [comment]
In my experience, setting `PATH` in a way that applies system-wide is a bit of a minefield. For example launching VS Code from the Dock on macOS won't pick up paths exported in terminal startup scripts. Adding to `flutter/bin` might be more reliable (the user may have already set this folder up in a way that works globally).

Doing this could confuse people that have both SDKs though. I always have latest stable Dart SDK in my `PATH` (for `dart`), so I wouldn't expect running `dart` to use Flutter's version (I'm usually on `master`). This can easily be handled by ordering things in `PATH`, people might just need to be aware of it.

Out of interest, what will happen to the pub-cache that ships in Flutter's zip in this case? Today people that used the zip have some slightly confusing behaviour where `pub global list` and `flutter packages list` will give different things (they have their own stores), whereas users with a `git clone` do not. If a `pub` wrapper is added in Flutter that also uses the custom location, `pub global list` could then return two different things depending on whether it hit the Flutter wrapper or not (which could cause more confusion).

**Comment by jonahwilliams** [comment]
Ooff, good point about the pub cache - I'm not sure yet

**Comment by jonahwilliams** [comment]
This is done!
