### ISSUE TITLE
I have problems to test my application from the phone

### ISSUE THREAD

**Issue by EduardEddy** [flutter/flutter#51226]
I am doing developments in visual studio code in ubuntu, and I could do the tests with the phone connected to the laptop the app was created in my phone and I could try after a moment to another I am not sure that it was updated if flutter, ubuntu, visual code, and I could no longer do tests from the phone, I run flutter doctor and he always tells me that there is no device detected :-(
I want to continue testing from the phone directly, since the emulator makes my laptop go a little slower

**Comment by TahaTesser** [comment]
Hi @EduardEddy 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by EduardEddy** [comment]
flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale es_CO.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/eduard/development/flutter
    • Framework revision cc949a8e8b (hace 5 meses), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/eduard/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

============ **and the other command** ===============================

flutter run --verbose
[  +18 ms] executing: [/home/eduard/development/flutter/] git log -n 1
--pretty=format:%H                               [  +35 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] cc949a8e8b9cf394b9290a8e80f87af3e207dce5
[        ] executing: [/home/eduard/development/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[   +8 ms] Exit code 0 from: git describe --match v*.*.*
--first-parent --long --tags
[        ] v1.9.1+hotfix.4-0-gcc949a8e8b
[  +10 ms] executing: [/home/eduard/development/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[        ] origin/stable
[        ] executing: [/home/eduard/development/flutter/] git
ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [/home/eduard/development/flutter/] git
rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +102 ms] executing: /home/eduard/Android/Sdk/platform-tools/adb
devices -l
[  +12 ms] Exit code 0 from:
/home/eduard/Android/Sdk/platform-tools/adb devices -l
[   +1 ms] List of devices attached
[  +17 ms] No supported devices connected.
[   +9 ms] "flutter run" took 152ms.

#0      throwToolExit
(package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:281:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run
(package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand
(package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run
(package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure>
(package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run
(package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext
(package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main
(file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter
_tools.dart:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by VladyslavBondarenko** [comment]
@EduardEddy 
do you have enabled usb debugging on your phone?
does it persist after this workaround? https://github.com/flutter/flutter/issues/27175#issuecomment-533930857

**Comment by VladyslavBondarenko** [comment]
@EduardEddy 
I hope you've solved the problem, closing the issue.
if you disagree please write in the comments and I will reopen it.
Thank you
