### ISSUE TITLE
Material tab bar should not have horizontal padding

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#5122]
Using material app and adding a tab bar to AppBar results in this:

![image](https://cloud.githubusercontent.com/assets/6687929/17227075/5f69c302-54c1-11e6-8e9c-00600066fb99.png)

Note the padding on the left

Looking at material design specs: https://material.google.com/components/tabs.html, there's no such padding.

**Comment by mehmetf** [comment]
This is a big deal for teams who want to add custom widgets to appbar bottom. The background color of the app bar bleeds because of padding and results in this:

![image](https://cloud.githubusercontent.com/assets/6687929/17227151/c6de7ab4-54c1-11e6-83ae-568fc1c99d55.png)

**Comment by abarth** [comment]
@HansMuller

**Comment by HansMuller** [comment]
The appBar is adding the padding:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app_bar.dart#L333

It definitely shouldn't be padding the bottom widget; will fix.

**Comment by jigarfumakiya** [comment]
Is there anyway to remove horizontal padding in tabbar?

**Comment by Nuke-101** [comment]
> Is there anyway to remove horizontal padding in TabBar?
I think removing label padding would work , it fixed my issue try it -
labelPadding: EdgeInsets.all(0),

**Comment by omidraha** [comment]
Is it possible to having Tab bar label without any padding?
It's not working:
```dart
 labelPadding: EdgeInsets.all(0),
```
