### ISSUE TITLE
The Skia engine autoroller is out of sync with the files we need

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51239]
More context in https://github.com/flutter/flutter/pull/51224

See https://skia.googlesource.com/buildbot/+/master/autoroll/config/flutter-engine-flutter.json#37

We need to update that file to have more of the files we care about in it, so that if one builder fails that doesn't upload the files in there now, we don't let the roller use the bad commit.

**Comment by dnfield** [comment]
According to @rmistry it should be possible to update the rollers to instead check LUCI status, but not clear when that change could be made at this point.  The hard part of this for us is gathering all the files we care about, which is spread out across the recipe and possibly the tool - and then finding some way to make sure we dont' keep falling out of sync.

**Comment by rmistry** [comment]
> According to @rmistry it should be possible to update the rollers to instead check LUCI status, but not clear when that change could be made at this point. The hard part of this for us is gathering all the files we care about, which is spread out across the recipe and possibly the tool - and then finding some way to make sure we dont' keep falling out of sync.

This is correct.

The other option I suggested was if it was possible (it might not be) to create a service that checks the luci status for you, and writes it to a single Google storage location for the roller to check.
That way the roller could use the same code as it does now, and you do not have to wait till I eventually get to writing a the new luci repo manager in the roller code.

**Comment by godofredoc** [comment]
Obsolete
