### ISSUE TITLE
Flutter cannot track more than one observatory port for iOS devices

### ISSUE THREAD

**Issue by kaiyuanw** [flutter/flutter#5123]
## Steps to Reproduce

Plug in two iPhone on your MacBook.  Run flutter app on both iPhone and you will see that one of the device lose the observatory port.
## Flutter Doctor

Normal.
## Logs and Crash Reports

https://gist.github.com/kaiyuanw/09408e985dffce9b94df00d775a2a3dd

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Does this still happen?

**Comment by zoechi** [comment]
I assume this issue is stale. Please let us know if you're still seeing this problem.
