### ISSUE TITLE
flutter analyze command should remove 'unused_catch_clause'

### ISSUE THREAD

**Issue by safield** [flutter/flutter#51245]
I have received the following error from the flutter analyze command...

```
The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/framework/server.dart:65:38 •
          unused_catch_clause
```
Catch clause are for executing a block of code when a specific exception is thrown, regardless if anything is done with said exception. I might want to catch an exception and return a specific error enum. This is correct and proper code.

**Comment by darshankawar** [comment]
Hi @safield,
Is this still an issue ?
If so, can you provide latest `flutter doctor -v` and a minimal code sample that shows the message ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
