### ISSUE TITLE
java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)

### ISSUE THREAD

**Issue by ithour** [flutter/flutter#51242]
![图片](https://user-images.githubusercontent.com/18640117/75085195-9187b480-5561-11ea-91bc-5d8aee38e6c8.png)
webview_flutter: ^0.3.19+8
flutter version:
Flutter 1.12.13+hotfix.7-pre.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (10 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by TahaTesser** [comment]
Hi @ithour 
Which device you running this on?
Thank you

**Comment by TahaTesser** [comment]
Hi @ithour 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ghostgzt** [comment]
huawei dub-al00 crash!

**Comment by yxwandroid** [comment]
I encountered the same problem with huawei phones
My environment
![image](https://user-images.githubusercontent.com/9635493/79085134-eb3e7b00-7d69-11ea-8aeb-9f62ce25c537.png)

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
