### ISSUE TITLE
having problem  with synchtonisation in order migrating to androidx

### ISSUE THREAD

**Issue by Gunkev** [flutter/flutter#51256]
![Screenshot from 2020-02-22 10-54-03](https://user-images.githubusercontent.com/36812576/75090608-cc3f1c00-5564-11ea-8b10-417b2a42e5cf.png)
![Screenshot from 2020-02-22 10-52-31](https://user-images.githubusercontent.com/36812576/75090612-d3662a00-5564-11ea-90ea-faab043fe990.png)

i have started a new project in flutter, i add a new dart package and when i run I'm getting some nasty errors with androidx compatibility i when over to the flutter dev documentation and started following the steps but at i certain level, i don;t know whether my project synchronised with gradle file but i when over to click the button sync project with gradle files but the button was not there as indicated by the documentation

**Comment by Gunkev** [comment]
> ![Screenshot from 2020-02-22 10-54-03](https://user-images.githubusercontent.com/36812576/75090608-cc3f1c00-5564-11ea-8b10-417b2a42e5cf.png)
> ![Screenshot from 2020-02-22 10-52-31](https://user-images.githubusercontent.com/36812576/75090612-d3662a00-5564-11ea-90ea-faab043fe990.png)
> 
> i have started a new project in flutter, i add a new dart package and when i run I'm getting some nasty errors with androidx compatibility i when over to the flutter dev documentation and started following the steps but at i certain level, i don;t know whether my project synchronised with gradle file but i when over to click the button sync project with gradle files but the button was not there as indicated by the documentation

i solve that by adding 
`subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.core' &&
                        !details.requested.name.contains('androidx')) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }

in my android/build.gradle file and i added 

android.useAndroidX=true
android.enableJetifier=true 

in android/gradle.properties

**Comment by Gunkev** [comment]
> ![Screenshot from 2020-02-22 10-54-03](https://user-images.githubusercontent.com/36812576/75090608-cc3f1c00-5564-11ea-8b10-417b2a42e5cf.png)
> ![Screenshot from 2020-02-22 10-52-31](https://user-images.githubusercontent.com/36812576/75090612-d3662a00-5564-11ea-90ea-faab043fe990.png)
> 
> i have started a new project in flutter, i add a new dart package and when i run I'm getting some nasty errors with androidx compatibility i when over to the flutter dev documentation and started following the steps but at i certain level, i don;t know whether my project synchronised with gradle file but i when over to click the button sync project with gradle files but the button was not there as indicated by the documentation

thk God i found a solution to it.
First of all i updated flutter to have the latest version.
I when to the project android/build.grade and added the following under buildscript after dependencies
![Screenshot from 2020-02-22 14-45-58](https://user-images.githubusercontent.com/36812576/75093537-d708a980-5582-11ea-8f51-f0458a0697e5.png)

in my android/gradle.properties file and i added
![Screenshot from 2020-02-22 14-47-08](https://user-images.githubusercontent.com/36812576/75093544-e0921180-5582-11ea-9c30-9ab19bfc16c1.png)

**Comment by TahaTesser** [comment]
Hi @Gunkev 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by Gunkev** [comment]
Hello,
It's okay closing.
Thank informing me.
Gunkev

Le lun. 24 févr. 2020 à 11:22, Taha Tesser <notifications@github.com> a
écrit :
