### ISSUE TITLE
after upgrading flutter

### ISSUE THREAD

**Issue by sanskar2999** [flutter/flutter#51255]
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.3.1/lib/src/chips_input.dart:42:8: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,        
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

 class ChipsInputState<T> extends State<ChipsInput<T>>
       ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:658:8: Context: 'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        31.9s
Gradle task assembleDebug failed with exit code 1

**Comment by throwpedro** [comment]
I end up with a Gradle task assembleDebug failed with exit code 1 as well
on a completely new install of flutter and a new project.

**Comment by jonahwilliams** [comment]
You picked up a minor breaking change in the SDK, so you'll need to update the flutter_chips_input package to a later version
