### ISSUE TITLE
Emulator won't work on a saved flutter project

### ISSUE THREAD

**Issue by chicken-biryani** [flutter/flutter#51265]
After coming back to  a saved flutter project (on android studio ) the emulator won't work on making changes...basically no changes are taking place after saving the project on Androidstudio

**Comment by msal4** [comment]
Could you please elaborate?

**Comment by chicken-biryani** [comment]
Yes, 
I have tried to update simple text widget and I still see the old text, It seems like the app state was saved at some point and every time when I run the project I see that state
The android device emulator won't update on making changes. The hot reload, hot restart etc is not enabled . 
Every time i want to make some changes i have to start a new project and copy paste the code of the already saved project

**Comment by msal4** [comment]
How about if you run `flutter clean` and rerun the project?
