### ISSUE TITLE
error occur due to image_picker package

### ISSUE THREAD

**Issue by MuhammadAsif-coder** [flutter/flutter#51261]
when i install image_picker package my app return error and app runs if i didnot install this package
![SharedScreenshot](https://user-images.githubusercontent.com/56240820/75093385-03e29f80-5536-11ea-8683-194d6a8e56be.jpg)

**Comment by TahaTesser** [comment]
Hi @MuhammadAsif-coder 
You don't need to provide that package manually to run `image_picker`
Check out this [image_picker_sample](https://github.com/TahaTesser/image_picker_sample)
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Thank you

**Comment by TahaTesser** [comment]
Hi @MuhammadAsif-coder 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
