### ISSUE TITLE
Scaffold does not fully support AppBarBehavior.under or scroll

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#5126]
Currently, the client is required to set padding to the body of a scaffold if the AppBarBehavior is not fixed. This is cumbersome. Here's the code from flutter's gallery:

``` dart
    // The first item in the list just exists to occupy the space behind
    // the flexible app bar. As it's scrolled out of the way, the app bar's
    // height will shrink.
    final double statusBarHeight = (MediaQuery.of(context)?.padding ?? EdgeInsets.zero).top;
    _listItems.add(new SizedBox(height: _kFlexibleSpaceMaxHeight + statusBarHeight));
```

where _listitems is used to build a Block of contents for the body.

Scaffold should do this automatically for clients so that the same body can be used whether toolbar is fixed or not.

**Comment by HansMuller** [comment]
I agree with you about this being cumbersome and not the sort of thing that app developer should have to bother with.

Once #4430 lands we should be able to address this problem.

**Comment by mehmetf** [comment]
We need to be able to collapse appbar properly by the time we release to users EOQ1.

**Comment by HansMuller** [comment]
By "properly" are you referring to the original description of the issue:

> Scaffold should do this automatically for clients so that the same body can be used whether toolbar is fixed or not.

or something else?

**Comment by mehmetf** [comment]
I am referring to the original description, yes. "Proper" means by just using the available API and w/o augmenting the body of the app.

**Comment by HansMuller** [comment]
OK, thanks for clarifying that. Supporting for handling flexible app bars in this way is part of "the great scrollable refactor" - https://github.com/flutter/flutter/issues/5288. It's being worked on now.

**Comment by mehmetf** [comment]
Could we please have an update on this? Thanks!

**Comment by abarth** [comment]
This should be ready for you to use now.  We've updated the contacts demo to show how this works now:

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/contacts_demo.dart

Basically, you use a `CustomScrollView` in the `body` attribute of your `Scaffold` and you put a `SliverAppBar` and a `SliverList` into the `CustomScrollView`.  The `SliverAppBar` has some properties about which behavior you want (e.g., pinned, floating):

https://docs.flutter.io/flutter/material/SliverAppBar-class.html

We haven't fully written all the docs yet.  If it's not clear what to do from that example, @Hixie or I can drop by your desk and help you out.

**Comment by jiajiabingcheng** [comment]
Hi abarth,

Is that possible to have title and bottom bar with different behaviors? Say I would like our title in AliverAppBar floating and the bottom bar pined. 

Thanks!

**Comment by abarth** [comment]
Please file a new bug for that feature request and cc @Hixie

**Comment by mehmetf** [comment]
I am closing this issue since the only remaining problem is for us to use the new widgets.
