### ISSUE TITLE
flutter command wait a lot of time before start

### ISSUE THREAD

**Issue by Ali1Ammar** [flutter/flutter#51264]
flutter command wait a lot of time before start execute
it is happed with all flutter command :
- flutter
- flutter clean
- flutter pub get
- flutter package ...
- flutter doctor
- ....
it take a time don't do any things just wait 
time from a few second to very long time like a half hour and more 
after that start running or I press Ctrl + C to stop.
what i try to do
- run killall dart
- close any editor and ide
- restart computer
- delete lock file

it is doen't show any error or messege just wait a random time then run normal

i dont think it is internet problem becuse it is cause with all command like flutter clean

![fluttererror](https://user-images.githubusercontent.com/18378766/75095139-0f1fe480-55a3-11ea-975a-9998c212dbc0.png)

![flutterdoctor](https://user-images.githubusercontent.com/18378766/75095448-d7ff0280-55a5-11ea-924e-f0261dccceda.png)

my system : linux manjaro
version : master 1.15.4

**Comment by Ali1Ammar** [comment]
It is run normal when turn off wifi 
but why (flutter clean)  or (flutter packages pub run build_runner build) need wifi 
and my internet not very bad to take 30 minute 
I still think it is not internet speed problem

**Comment by jonahwilliams** [comment]
If you're running on master channel, you'll need to download new dependencies every time you upgrade. If you need offline functionality, its recommend that you use the stable downloads from the website or a mirror, as these contain all dependencies prepackaged
