### ISSUE TITLE
how can i use python or java code into my existing flutter app?

### ISSUE THREAD

**Issue by sherrysidd68** [flutter/flutter#51262]

**Comment by msal4** [comment]
You could use [Platform Channels](https://flutter.dev/docs/development/platform-integration/platform-channels) to write native code in Java/Kotlin for android and Swift/Objective C for iOS.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
