### ISSUE TITLE
After the configuration command "flutter config --enable-web" was performed on the Mac OS system, Chrome was not found using the "flutter devices" command.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51279]
lijunerdeMacBook-Pro:~ juner$ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
lijunerdeMacBook-Pro:~ juner$ flutter config --enbale-web
Could not find an option named "enbale-web".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.
lijunerdeMacBook-Pro:~ juner$ flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
lijunerdeMacBook-Pro:~ juner$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to
diagnose potential issues, or visit https://flutter.dev/setup/ for
troubleshooting tips.
lijunerdeMacBook-Pro:~ juner$ flutter emulators
2 available emulators:

Android_Accelerated_Oreo • Android Accelerated Oreo •       • android
apple_ios_simulator      • iOS Simulator            • Apple • ios

To run an emulator, run 'flutter emulators --launch <emulator id>'.
To create a new emulator, run 'flutter emulators --create [--name xyz]'.

You can find more information on managing emulators at the links below:
  https://developer.android.com/studio/run/managing-avds
  https://developer.android.com/studio/command-line/avdmanager
lijunerdeMacBook-Pro:~ juner$ ls
AndroidStudioProjects		bin
Applications			demo
Desktop				flutter
Documents			flutter_project
Downloads			fonts
Flutter Fly.svg			github
Helen				go
IdeaProjects			iCloud 云盘（归档）
Library				image
Movies				oschina
Music				python
Pictures			shell
Postman				sunloginclient.pid
Public				system_img
PycharmProjects			tensorflow
VirtualBox VMs			test.txt
lijunerdeMacBook-Pro:~ juner$ nkdir web
-bash: nkdir: command not found
lijunerdeMacBook-Pro:~ juner$ 
lijunerdeMacBook-Pro:~ juner$ mkdir web
lijunerdeMacBook-Pro:~ juner$ ls
AndroidStudioProjects		demo
Applications			flutter
Desktop				flutter_project
Documents			fonts
Downloads			github
Flutter Fly.svg			go
Helen				iCloud 云盘（归档）
IdeaProjects			image
Library				oschina
Movies				python
Music				shell
Pictures			sunloginclient.pid
Postman				system_img
Public				tensorflow
PycharmProjects			test.txt
VirtualBox VMs			web
bin
lijunerdeMacBook-Pro:~ juner$ cd web/
lijunerdeMacBook-Pro:web juner$ flutetr create web_test
-bash: flutetr: command not found
lijunerdeMacBook-Pro:web juner$ flutter create web_test
Creating project web_test... androidx: true
  web_test/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  web_test/ios/Runner/Info.plist (created)
  web_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  web_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  (created)
  web_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.p
  ng (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.p
  ng (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  (created)
  web_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  (created)
  web_test/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  web_test/ios/Runner/Base.lproj/Main.storyboard (created)
  web_test/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  (created)
  web_test/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  web_test/ios/Flutter/Debug.xcconfig (created)
  web_test/ios/Flutter/Release.xcconfig (created)
  web_test/ios/Flutter/AppFrameworkInfo.plist (created)
  web_test/ios/.gitignore (created)
  web_test/test/widget_test.dart (created)
  web_test/web_test.iml (created)
  web_test/.gitignore (created)
  web_test/.metadata (created)
  web_test/android/app/src/profile/AndroidManifest.xml (created)
  web_test/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  web_test/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  web_test/android/app/src/main/res/drawable/launch_background.xml (created)
  web_test/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  web_test/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  web_test/android/app/src/main/res/values/styles.xml (created)
  web_test/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  web_test/android/app/src/main/AndroidManifest.xml (created)
  web_test/android/app/src/debug/AndroidManifest.xml (created)
  web_test/android/gradle/wrapper/gradle-wrapper.properties (created)
  web_test/android/gradle.properties (created)
  web_test/android/.gitignore (created)
  web_test/android/settings.gradle (created)
  web_test/android/app/build.gradle (created)
  web_test/android/app/src/main/kotlin/com/example/web_test/MainActivity.kt
  (created)
  web_test/android/build.gradle (created)
  web_test/android/web_test_android.iml (created)
  web_test/pubspec.yaml (created)
  web_test/README.md (created)
  web_test/ios/Runner/Runner-Bridging-Header.h (created)
  web_test/ios/Runner/AppDelegate.swift (created)
  web_test/ios/Runner.xcodeproj/project.pbxproj (created)
  web_test/lib/main.dart (created)
  web_test/.idea/runConfigurations/main_dart.xml (created)
  web_test/.idea/libraries/Flutter_for_Android.xml (created)
  web_test/.idea/libraries/Dart_SDK.xml (created)
  web_test/.idea/libraries/KotlinJavaRuntime.xml (created)
  web_test/.idea/modules.xml (created)
  web_test/.idea/workspace.xml (created)
Running "flutter pub get" in web_test...                            1.8s
Wrote 68 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, v1.12.13+hotfix.5, on Mac OS X
    10.15.3 19D76, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices: is partially installed;
    more components are available. (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS: is partially installed; more components
    are available. (Xcode 11.3.1)
[✓] Android Studio: is fully installed. (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition: is fully installed. (version 2019.2.2)
[!] Connected device: is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd web_test
  $ flutter run

Your application code is in web_test/lib/main.dart.

lijunerdeMacBook-Pro:web juner$ ls
web_test
lijunerdeMacBook-Pro:web juner$ cd web_test/
lijunerdeMacBook-Pro:web_test juner$ ls
README.md	ios		pubspec.lock	test
android		lib		pubspec.yaml	web_test.iml
lijunerdeMacBook-Pro:web_test juner$ flutter create .
Recreating project ....
Wrote 3 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, v1.12.13+hotfix.5, on Mac OS X
    10.15.3 19D76, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices: is partially installed;
    more components are available. (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS: is partially installed; more components
    are available. (Xcode 11.3.1)
[✓] Android Studio: is fully installed. (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition: is fully installed. (version 2019.2.2)
[!] Connected device: is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

lijunerdeMacBook-Pro:web_test juner$ ls
README.md	ios		pubspec.lock	test
android		lib		pubspec.yaml	web_test.iml
lijunerdeMacBook-Pro:web_test juner$

**Comment by Amar-patel214** [comment]
how to disable web app from my flutter project?
