### ISSUE TITLE
Hide status bar on iOS when drawer is open

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5127]
Uber app and Inbox app appear to do this.  (Uber's animates offscreen which is nicer.)

**Comment by Hixie** [comment]
@chinmaygarde Any idea how apps control where the system UI paints? Can we do this given that we just have the one GL context?

**Comment by chinmaygarde** [comment]
The [SetEnabledSystemUIOverlays](https://github.com/flutter/engine/blob/master/services/platform/system_chrome.mojom#L110) call will allow you to hide the top status bar. It is already wired up at the platform layer.

**Comment by Hixie** [comment]
My previous comment is incorrect. Inbox is just hiding it suddenly when opening the drawer.

We can easily do that too, as @chinmaygarde says. However, I would posit that this is non-native behavior. None of the stock apps do this for any of their UI. I think we'd be better off not hiding it.

I'm going to close this bug. Feel free to reopen if you disagree...
