### ISSUE TITLE
[in_app_purchase] How to check for refunds on android ?

### ISSUE THREAD

**Issue by Ephenodrom** [flutter/flutter#51296]
Hello folks,

I am currently writing an app with flutter that will have in app products to buy. Everything is ready and I tested the whole purchase process. But there is still one problem I can't find a solution for :

Scenario : 
Someone downloads the app and tries out the feature. Now he upgrades to the PRO version by bying the corresponding in app product. A few days later, the customer is having some problems with the app and want to have the money back. I create a refund in the play console.

Now the problem is, that the **queryPastPurchases** still fetches the purchase. I waited a few days ( around 7 days ) and no changes. Also the **PurchaseStatus** does not seem to have the status **refunded**.

How would I check if a purchase was refunded ?

I use the following version of the in_app_purchase plugin  :
```yaml
in_app_purchase: ^0.3.0+3
```

**Comment by TahaTesser** [comment]
Duplicate of [#51296](https://github.com/flutter/flutter/issues/51296)

**Comment by Ephenodrom** [comment]
Please reopen, due to the linked issue is the same as this one ...

**Comment by Ephenodrom** [comment]
@Tomucha 
How would I revoke a purchase ? There is only a "refund" button in the Play Console interface. Also the documentation at https://support.google.com/googleplay/android-developer/answer/2741495?hl=en does not list a "revoked" status.

The documentation only mentions "revoke" for subscriptions. But I only offer a one time purchase to upgrade to the "PRO" version of the app.

**Comment by Tomucha** [comment]
"Revoke" checkbox is part of "refund" dialog.

**Comment by Ephenodrom** [comment]
@Tomucha 
Thanks for the good information. Now I am trying to revoke a purchase after I refunded it via the UI. There is no way to revoke it via the UI after I refunded it without checking the checkbox. Currently I am trying to revoke it via API but I can't get the OAUTH thing working.

```json
{
    "error": {
        "errors": [
            {
                "domain": "androidpublisher",
                "reason": "projectNotLinked",
                "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."
            }
        ],
        "code": 403,
        "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."
    }
}
```

Is the API accessible via API Key or something like that ?

**Comment by Tomucha** [comment]
Sorry, I don't have any experience with that. Even the "revoke" suggestion was just a lucky guess :-)

**Comment by TheWCKD** [comment]
I have encountered the same issue, nor refund or (pending->denied) features work.

**Comment by Ephenodrom** [comment]
@Tomucha 
Still the same problem. I created a new app and added a new in app product. I ordered the product and after that, closed the app and refunded the purchase. I also clicked the checkbox for "revoke". Afer the refund is done, I started the app again and I am still receiving the pruchase with status purchased. 

Will now wait a few hours / days to check again. Maybe there is some caching.

**Comment by Ephenodrom** [comment]
@Tomucha after around 24 hours the queryPastPurchases did not return any purchases any more after refunding and revoking. So this seems to work now! Thanks for the advice.

@TheWCKD i am not sure if this information helps you to fix your problem. I will close this issue.

**Comment by Ephenodrom** [comment]
As @Tomucha had the right hint. This issue can now be closed.
