### ISSUE TITLE
Google Maps: iOS frame rate constantly at 30fps

### ISSUE THREAD

**Issue by carlowenig** [flutter/flutter#51297]
Hi there,
I am noticing a low frame rate when using the `GoogleMap` Widget on iOS (no problems on Android). I've tested the performance in profile mode and noticed very sluggish animations & page transitions when exiting the page that contains the map widget. DevTools show that the frame rate caps at 30fps if the Widget is present on the current page.
Is this a known issue & is there a fix?

Thanks!

**Comment by TahaTesser** [comment]
Hi @carlowenig 
can you please provide your `flutter doctor -v` and `flutter run --profile --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by carlowenig** [comment]
Thanks for the response.
I fixed it now. It seemed to be an issue with a FadeTransition-Widget on the same page, not with the GoogleMap-Widget.
