### ISSUE TITLE
Global widget can't access setState method

### ISSUE THREAD

**Issue by JheiKrauzer0613** [flutter/flutter#51291]
I'm trying to create a show/hide password using a TextFormField but I can't access the setState method if the TextFormField were declared outside of the class. Here's what I did:

- I have a StatefulWidget class named **FormLogin**.
- Inside **FormLogin**, I have 2 layout widgets named **frmLoginPortraitView** and **frmLoginLandScapeView**.
 - Both **frmLoginPortraitView** and **frmLoginLandScapeView** were seperated widgets.
- Outside of **FormLogin**, I created a global TextFormField named **txtPassword**.
 - Inside **txtPassword**, I put an **onPressed**() method, inside of it is the **setState**() method.
- An error "**setState isn't defined**" is showing whenever I put the **setState** method in **txtPassword** which is a **global** widget.

 I need to set the **txtPassword** global since I was calling it on both **frmLoginPortraitView** and **frmLoginPortraitView** every time user changing device orientation. 

![aaa](https://user-images.githubusercontent.com/60071291/75117537-2e0a9d80-56ad-11ea-927f-1bf1396f91f6.png)

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
