### ISSUE TITLE
Can you still publish apps for iOS 13.3.1 ?

### ISSUE THREAD

**Issue by jeremyimmanuel** [flutter/flutter#51295]
This problem is regarding the recent iOS 13.3.1 update that doesn't let people install Flutter Apps on their physical device running iOS 13.3.1. You can check #49504 for further details.

**My question is can we still publish apps to customers running iOS 13.3.1? Thank you!**

**Comment by stuartmorgan** [comment]
This was already answered in the issue you referenced; see https://github.com/flutter/flutter/issues/49504#issuecomment-581554697
