### ISSUE TITLE
Animations package hides widget, but widget is still accessible

### ISSUE THREAD

**Issue by bergamin** [flutter/flutter#51300]
I'm trying to use Fade for hiding or showing a FAB button with an animation, but after it is hidden it is still accessible.

It is possible to notice this in the Fade example. Add an action to the `onPressed` of the example FAB and tap HIDE FAB button. Then, tap the region where the FAB was. The action will still happen.

![](https://media.giphy.com/media/kDAsz9BsMXwyDzMpKw/giphy.gif)

**Comment by dnfield** [comment]
The FadeScaleTransition should probably make it clearer that you probably want to drop the widget from the tree when it fades to 0.

In general, I think we should at the least add an assertion around hit testing for widgets like this where they check if the opacity is 0, and if so assert with a suggestion that you're using the wrong kind of widget to do hit testing without drawing anything.  See https://github.com/flutter/flutter/issues/51000#issuecomment-587980377

/cc @goderbauer @shihaohong

**Comment by dnfield** [comment]
You should be able to work around this today, btw, by just dropping the widget yourself in cases where the animation controller's value has hit zero.

**Comment by bergamin** [comment]
I'm new to flutter. Before finding the animations package, I was hiding my fab using Visibility widget. Is it possible to set the visibility based on that? Like, checking the alpha for deciding the visibility or something in these lines. This would make the Visibility widget trigger at the right moment in the animation.

**Comment by dnfield** [comment]
Yeah, something like this should work:

```dart
      floatingActionButton: AnimatedBuilder(
        animation: _controller,
        builder: (BuildContext context, Widget child) {
          return FadeScaleTransition(
            animation: _controller,
            child: child,
          );
        },
        child: Visibility(
          visible: _controller.value > 0.0,
          child: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {},
          ),
        ),
      ),
```

**Comment by goderbauer** [comment]
We should update the examples in the example app to actually do this correctly.

**Comment by shihaohong** [comment]
I can fix the example app! I'll probably create a separate issue to improve the sample docs with:
- Short code samples (if possible, for cases like the one above)
- Links to the Material motion system article that is now published

**Comment by bergamin** [comment]
@dnfield thanks! That's what I was thinking about. I'll try that.

**Comment by bergamin** [comment]
It seems Visibility alone won't be able to solve this. It looks like it is testing the controller's value for visibility before the animation even starts, which makes it flash into existence and disappear through the animation but still accessible or invisible when it should be shown.

Inverting the test to == 0 will show and hide when intended, but the hiding animation is hidden by visibility being triggered before we actually need it to. It will have the same behaviour of using _showFab here.

Looking at the Visibility documentation, I found IgnorePointer, which is what I'm going to use for now. It works pretty well:

```dart
      floatingActionButton: AnimatedBuilder(
        animation: _controller,
        builder: (BuildContext context, Widget child) {
          return FadeScaleTransition(
            animation: _controller,
            child: child,
          );
        },
        child: IgnorePointer(
          ignoring: !_showFab,
          child: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () { },
          ),
        ),
      ),
```

**Comment by dnfield** [comment]
What about if you still use the `Visibility` widget, but set `visible` to `_showFab`?

The problem with using just IgnorePointer is that it will still build the child widget, which may be non-trivial.  For a FAB it's probably not that big of a deal, but depending on what your actual widget is it could make a big difference, particularly if your actual widget animates/pumps frames on every tick.

**Comment by bergamin** [comment]
Yes, not ideal, but it's going to be it for now.

If I use `_showFab` in `Visibility`, it does work, but the hiding animation isn't shown because `Visibility` is hiding the FAB before the animation starts.

**Comment by dnfield** [comment]
Ahh ok, there should be some way to fix that but sounds good.

**Comment by shihaohong** [comment]
@bergamin Could you try using `AnimationController.status == AnimationStatus.dismissed` as well?

**Comment by bergamin** [comment]
@shihaohong you mean in `Visibility`? It doesn't show the FAB.

I put a `Toast` in the show/hide button to check what values are being read at that time (which I believe is the same time Visibility is being triggered) and it shows status as `AnimationStatus.forward` and `AnimationStatus.reverse`

**Comment by bergamin** [comment]
I tried the opposite, testing != dismissed and the animations are shown correctly, but the FAB is still accessible and on hitting it, the toast would show status as dismissed. I believe these status that require the animation to end before triggering Visibility won't work this way. Unless there is a way to delay Visibility or make it keep testing until we get to the desired animation stage
