### ISSUE TITLE
When will this commit come to flutter ???

### ISSUE THREAD

**Issue by Dorbmon** [flutter/flutter#51317]
https://github.com/flutter/engine/pull/16560
This fixes a bug whick is very important to me.I wanna know when will it come to flutter?I am almost crazy.

**Comment by TahaTesser** [comment]
Hi @Dorbmon 
This PR mentioned the fix you're describing [#51316](https://github.com/flutter/flutter/pull/51316)
I believe it should be available to you soon
Thank you
