### ISSUE TITLE
The search function on the API site is inefficient

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#51325]
(transferred from /flutter/website)

Consider the situation where you want to search `setState` on api.flutter.dev

Logically, it should bring `State.setState` as the first result, since this is the only class that implements the method.
The others just inherit from it.

The reality is different:

<img width="488" alt="Screenshot 2020-02-21 at 14 42 23" src="https://user-images.githubusercontent.com/20165741/75043692-609f7500-54b8-11ea-9d0c-f3f3ee74b956.png">

The search result is polluted by all the stateful widgets in the framework.
In the end, we don't even see `State.setState` because there are too many results.

**Comment by TahaTesser** [comment]
Adding `team` since it's about website search functionality itself

**Comment by darshankawar** [comment]
Going by an example of searching `setState`, the search atleast now shows up the option in the list:

![Screen Shot 2020-08-25 at 4 39 16 PM](https://user-images.githubusercontent.com/67046386/91167473-a5b79480-e6f1-11ea-8501-5d4359f8efbd.png)

If we search for other state methods (eg: initState, didUpdateWidget), it shows up properly:

![Screen Shot 2020-08-25 at 4 39 28 PM](https://user-images.githubusercontent.com/67046386/91167561-c7188080-e6f1-11ea-837c-6b2b669eb042.png)
![Screen Shot 2020-08-25 at 4 39 40 PM](https://user-images.githubusercontent.com/67046386/91167566-c849ad80-e6f1-11ea-8ea2-890a78f22763.png)

but, searching for `dispose` still doesn't show up proper result:

![Screen Shot 2020-08-25 at 4 39 57 PM](https://user-images.githubusercontent.com/67046386/91167640-ec0cf380-e6f1-11ea-98a5-6c47f87e5b39.png)

**Comment by goderbauer** [comment]
This is an issue with dart docs and should be filed here: https://github.com/dart-lang/dartdoc
