### ISSUE TITLE
Issue while google sign-in after APK release

### ISSUE THREAD

**Issue by AhsanHameed97** [flutter/flutter#51320]
## Steps to Reproduce

1. ...I m unable to perform google sign-in after i made apk release on local level not through google play. 
2. ...I check all the settings . These are all fine for me.
3. ...Another help material?

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @AhsanHameed97 
Please add `SHA-1` key to your Firebase console [stackoverflow](https://stackoverflow.com/a/39144864)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by AhsanHameed97** [comment]
https://github.com/TahaTesser

> Hi @AhsanHameed97
> Please add `SHA-1` key to your Firebase console [stackoverflow](https://stackoverflow.com/a/39144864)
> Closing, as this isn't an issue with Flutter itself,
> if you disagree please write in the comments and I will reopen it
> Thank you

@TahaTesser  bro i did everything. but the problem is i didnt upload on google play i just want to use release apk to show the client

**Comment by TahaTesser** [comment]
Hi @AhsanHameed97 
can you please provide your `flutter doctor -v` and `flutter run --release --verbose` while signing in the app? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by AhsanHameed97** [comment]
> Hi @AhsanHameed97
> can you please provide your `flutter doctor -v` and `flutter run --release --verbose` while signing in the app?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

@TahaTesser 
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_database-3.1.1\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.      
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.      
Note: Recompile with -Xlint:unchecked for details.
C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+2\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\share-0.6.3+5\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\video_player-0.10.8+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\webview_media-0.1.1+3\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


____________________________
Warning: there were 45 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15m 22s
Running Gradle task 'assembleRelease'...                        
Running Gradle task 'assembleRelease'... Done                     930.1s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin app_settings...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   43.1s
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\app_settings-3.0.0+1\android\build.gradle' line: 24
* What went wrong:
A problem occurred evaluating root project 'app_settings'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in C:\Users\sabah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\app_settings-3.0.0+1\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s


The plugin app_settings could not be built due to the issue above.



I m facing this issue

**Comment by VladyslavBondarenko** [comment]
@AhsanHameed97 
As it told you in logs try https://github.com/flutter/flutter/issues/42082#issuecomment-564252848
does it help?

**Comment by AhsanHameed97** [comment]
> @AhsanHameed97
> As it told you in logs try [#42082 (comment)](https://github.com/flutter/flutter/issues/42082#issuecomment-564252848)
> does it help?

@VladyslavBondarenko 
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl = https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
here is my gradle wrapper file.

**Comment by iapicca** [comment]
Hi @AhsanHameed97 
your logs suggest that the version 4.6 is still in use

```bash
Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in 
```
did you try cleaning your project?
Thank you

**Comment by AhsanHameed97** [comment]
> Hi @AhsanHameed97
> your logs suggest that the version 4.6 is still in use
> 
> ```shell
> Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in 
> ```
> 
> did you try cleaning your project?
> Thank you

@iapicca 
Yes i do by using flutter clean

**Comment by iapicca** [comment]
Hi again @AhsanHameed97 
your [logs](https://github.com/flutter/flutter/issues/51320#issuecomment-590313946) above suggest a complex app rather than an `hello_world` app.,
could you please provide the `flutter run --verbose` 
and the `pubspec.yaml` relative to the newly created app?

Also, if you are using [firebase_auth](https://pub.dev/packages/firebase_auth)
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

thank you

**Comment by iapicca** [comment]
Hi again @AhsanHameed97 
I suspect the gradle version being affected by other plugins 
(example [webview_media](https://pub.dev/packages/webview_media)) present in your app.

Could you please try to reproduce the issue in a new project without other plugins
and provide the relative `flutter run --verbose` and `pubspec.yaml`?
thank you

**Comment by TahaTesser** [comment]
Hi @AhsanHameed97 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by AhsanHameed97** [comment]
I have done this issue you can close this issue..Thanks alot

**Comment by TahaTesser** [comment]
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. Thank you
