### ISSUE TITLE
What to do when "Error occurred: ApplicationVerificationFailed"?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5132]
I'm sure I don't have my developer profile configured correctly.  But would be nice if there was a bit more guidance from the tool as to what to do next:

```
%flutter build ios --release
Building com.yourcompany.flutterGallery for device (ios-release)...  42.5s
Built ios/build/Release-iphoneos/Runner.app.
%flutter install
Installing com.yourcompany.flutterGallery to Eric's iPhone...
Uploading Runner.app package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - InstallingEmbeddedProfile (30%)
 - VerifyingApplication (40%)
 - Error occurred: ApplicationVerificationFailed
```

```
%flutter run
Running lib/main.dart on Eric's iPhone...
2016-07-29 09:23:42.079 ios-deploy[95467:3006740] [ !! ] Error 0xe8008015: ‡
                                                                            ®tˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install ios/build/Release-iphoneos/Runner.app on 245efaebda74df40169418839fff2a8368bcaae5.
Error running application on Eric's iPhone.
```

**Comment by eseidelGoogle** [comment]
The correct choice here is probably to direct people to open "ios/Runner.xcodeproj" directly and try to run from there.

For example, when I do:
<img width="459" alt="screen shot 2016-07-29 at 9 26 36 am" src="https://cloud.githubusercontent.com/assets/11857803/17255560/a0e8dc70-556e-11e6-8a90-3fa46a40b3c2.png">

**Comment by eseidelGoogle** [comment]
Even after I walk through Apple's "fix provisioning" wizard, there are other issues:
<img width="451" alt="screen shot 2016-07-29 at 9 28 38 am" src="https://cloud.githubusercontent.com/assets/11857803/17255629/e9d131bc-556e-11e6-8e8d-22c1d14536d9.png">

**Comment by eseidelGoogle** [comment]
The wizard attempted to make these changes: https://gist.github.com/eseidelGoogle/fbda1b182269e50bf17c00d56ebd1700
Unclear if we should be checking in the iOS projects?

**Comment by sethladd** [comment]
Should our tools be reporting errors like this? Might be useful to know how often it happens in the wild. If we're failing, let's learn how often.

(I checked our measurements, and we don't seem to be capturing this error in our analytics.)

**Comment by Hixie** [comment]
@eseidelGoogle Does this still happen for you?

**Comment by eseidelGoogle** [comment]
I've not seen this in a while, but I can imagine how one might get into this.  FYI @xster, cbracken.  happy to close and wait for something more actionable.
