### ISSUE TITLE
Gallery, Pesto, Landscape: don't allow a recipe to scroll up to expose background image

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5133]
On iOS, open gallery, go landscape, open pesto, tap recipe.

Then, scroll up. Notice how you can pull the recipe up and expose the image in the background, below and under the recipe.

We should stop the scroll such that the recipe is never pulled up farther than the bottom of the screen.

**Comment by eseidelGoogle** [comment]
Should we punt this from August in lieu of disabling Landscape? https://github.com/flutter/flutter/issues/5146

**Comment by eseidelGoogle** [comment]
Removing this from August, feel free to re-add if you disagree.

**Comment by sethladd** [comment]
This no longer happens.
