### ISSUE TITLE
Gallery, Shrine, Landscape: home layout doesn't show text

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5134]
On iOS, open gallery, tap into shrine, go landscape.

Notice how the text for "beautiful little teapot" is "below the fold". We should move the text up so that it's visible in landscape.

Also, it looks like there's too much padding between the price in the upper right and the teapot. But maybe that will look better once the text is visible.

![39d58a21-2399-49f9-8cac-94db4c2491d7](https://cloud.githubusercontent.com/assets/5479/17256025/7c8a74c2-5570-11e6-830a-a6a49d11b957.PNG)

**Comment by sethladd** [comment]
Confirmed still an issue on iPhone 6, Nexus 5, and Nexus 6P

**Comment by eseidelGoogle** [comment]
Confirmed just now still true in 3a43fc88b66b042c612c04c3e2b8445ba1b27546

**Comment by eseidelGoogle** [comment]
This is probably a very easy fix.  We had this same bug reported several times since it's so obvious.
