### ISSUE TITLE
Deep linking should work on Desktop

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#51350]
For desktop (and web in particular), it should be possible to deep-link to a particular navigation route.  On Web, reloading the page should take you to the deep-link route that you were already looking at.

This will probably require registration of the app with a system service on macOS and Windows so that the app will get launched as a result of a particular URL being visited (for example, in the same way that the App Store gets launched from a browser).

**Comment by ds84182** [comment]
On Windows, this is accomplished by adding a registry key for your Uri scheme, while on MacOS it's something you add to your plist. Of course on Linux it depends on whether the system uses xdg-open.

The main complication is uninstalling the handler on Windows.

**Comment by dnfield** [comment]
We should not add the handler automatically on Windows.  That's the job of an application installer/uninstaller.  Windows installer creators even provide friendly ways to make that happen.

**Comment by dnfield** [comment]
In general, the framework/engine should not touch the Windows registry :)  Of course if someone made a plugin and some rouge app decided to do it that's their decision.

**Comment by gspencergoog** [comment]
Well, but at least for the web case, it's expected to be part of the core offering: if you are on a particular route, reloading the page should keep you on that route, and you shouldn't need to use a plugin to make it work.  It would seem to make sense to me to provide a common mechanism for this rather than to make a bespoke one for each platform.

**Comment by dnfield** [comment]
There are two parts to this issue: having flutter respond to uri launch requests properly, and setting up the native platform to recognize the launch requests as belonging to the Flutter app.

For a web app that's already all set.  For a Windows desktop app, we would need to make sure we grab the launch arguments from main or from the app domain and then forward them.  Setting the registry to make it automatic as @ds84182  was mentioning is a separate step, that's what I'm saying an installer should do.

**Comment by gspencergoog** [comment]
Yeah, good point, there are two things here.

On Android and iOS, the platform setup is configured as part of the Flutter package creation (e.g. AndroidManifest.xml, etc), so what you're saying makes sense, although it does mean that the experience is different on mobile and desktop: on mobile it's included in the regular flow of development, and unless we had some integration with the installer, won't be included on desktop.

Would you be OK with including it as part of the `flutter create` template on desktop platforms, as we do on mobile?

As for the forwarding of the args, I think that is related to a larger issue about passing command line args in general to the app (Filed https://github.com/flutter/flutter/issues/51425).

**Comment by dnfield** [comment]
Are we including an installer for `flutter create` apps on Windows?

I tried digging a bit - it's been a while since I worked on Windows Installers.  WiX has some stuff that can automatically handle adding/removing this stuff  from the registry for you.  There was also a newer version of installation MS was recommending when I last worked on this that made it super easy to do this (you could drop down a box in a dialog in Visual Studio and tell it what scheme you wanted to use).  If we're doing that I think it makes a lot of sense, similar to how we handle generating the AndroidManifest.xml.  If we're not, I don't know where the right place to do it would be.

**Comment by gspencergoog** [comment]
Hmm.  No, we're not planning that at the moment, and I see what you mean.  Android and iOS include the ability to create a native "installer" (apk/ipa), and Windows/macOS/Linux don't, because there isn't just one kind of installer on each platform, as much as they'd like there to be.

**Comment by stuartmorgan** [comment]
What exactly is being proposed here that's part of Flutter itself? I thought that deep linking for mobile was a separate plugin.

**Comment by esDotDev** [comment]
There needs to be some ability to ingest launch parameters on Desktop, and ideally it is the same implementation used on Web for allowing us to deep link there. Slack / Dischord have this behavior for example, click a link in browser, app will open to a specific page,

Something like:
<a href="myapp://param">Open app</a>
https://github.com/oikonomopo/electron-deep-linking-mac-win

Additionally, it would be nice to support command args directly on the EXEs
"myflutterapp.exe param1"

**Comment by stuartmorgan** [comment]
> There needs to be some ability to ingest launch parameters on Desktop, and ideally it is the same implementation used on Web for allowing us to deep link there (which sounds like it will be the Router api).
> 
> As a multi-platform developer, I simply want a consistent api for parsing and routing launch args, be that from web builds, or desktop. It's largely irrelevant to me where these args came from.

This doesn't answer my question. As far as I know the process for doing this in Flutter on iOS and Android is a plugin (and not a flutter/plugins plugin, so not something whose feature requests would be tracked here). I don't see any reason that plugin couldn't implement macOS support today, using the standard macOS process for registering handlers plus whatever logic that plugin does to provide a coherent API to Dart.

Put differently: can someone point me to existing code in a Flutter-owned repository that implements the deep linking support being proposed here on iOS or Android?

> Additionally, it would be nice to support command args directly on the EXEs
> "myflutterapp.exe param"

That's #32986

**Comment by esDotDev** [comment]
That's fair, I guess my thoughts were that the paradigm on desktop is more similar to web, than it is the mobile platforms, and you are handling it on web so just seems logical that we would have common API we can use for this task. 

Especially considering that waiting for someone to add support for all 3 desktop platforms to the plugin, will likely get much less traction than the Android/IOS. That package also hasn't been updated in over a year as, which highlights one of the issues with relying on plugins too much, if the author goes MIA, it blocks all progress.

For comparison, if I'm building a .NET desktop app, I just define my deep links in the manifest, and I will receive the payload in my main.  
https://blogs.windows.com/windowsdeveloper/2016/10/14/web-to-app-linking-with-appurihandlers/

It would be nice to have some consistency here across all the various platforms imo.

**Comment by stuartmorgan** [comment]
> the paradigm on desktop is more similar to web

I really don't see how.

As for whether or not the developer of a specific package will add desktop support: a) that's a generic ecosystem concern (there existing plugins which exist only for iOS or Android too; it's not specific to desktop) and b) the federated plugin structure explicitly helps address that problem.

The argument that the Flutter team must implement all possible desktop functionality because the ecosystem won't do it is a self-fulfilling prophesy. It's also not at all scalable (which is an important reason to have a plugin ecosystem in the first place).

**Comment by stuartmorgan** [comment]
@gspencergoog Could you clarify what functionality, specifically, you think we need on desktop here to be on par with mobile, per my initial comment above?

**Comment by gspencergoog** [comment]
I think your point about it being a plugin is a valid one.  We might want to offer a 1P version of that plugin for web, since it's such an expected piece of functionality there, but that's probably something for the web team to decide.

For Desktop, I think the main thing here to enable a plugin to be built would be a way to pass (ideally generic) command line arguments.

**Comment by esDotDev** [comment]
> I really don't see how.

It seems as though the new 'universal links' that mobile uses these days, are significantly more complicated than your traditional desktop link, which is just a string payload. But I haven't implemented this in years. 

I don't think this is arguing to implement 'every' feature, it's asking for feature parity with one that you are already effectively implementing on web. I mean you can make that argument in the opposite direction, and implement virtually nothing in the framework, it's all just a subjective decision as to what is core and what is not. 

Yes the plugin support is a generic issue, but my point was that this is an especially tricky case as it requires support for 3 platforms, and the userbase is currently quite low.

**Comment by stuartmorgan** [comment]
Since that's already tracked in another bug, I'm going to go ahead and close this then. If someone wants to propose having deep linking as framework functionality or a 1P plugin on all platforms, that should be a new request that can be considered as a whole, but I don't think we should treat desktop differently than mobile here.

**Comment by Nealsoni00** [comment]
@ds84182 question about adding a registry key on windows -- 

>
> On Windows, this is accomplished by adding a registry key for your Uri scheme
> 

If you don't mind me asking, how do you add a registry key for the URI scheme? Additionally how would you get the data back from the app being triggered. Ex: say you register for schema `myapp://` and you want to get the data from the web browser redirecting to `myapp://callback?idToken=xxxxxxx`
