### ISSUE TITLE
[fuchsia] Add support in Flutter engine for runtime tuning of fields for optimal performance

### ISSUE THREAD

**Issue by farchond** [flutter/flutter#51357]
## Use case

This is a proposal to configure certain SessionConnection parameters at runtime by loading them from a file. The purpose is to enable the Fuchsia team to fine tune values for specific product configurations to maximize performance gains on different hardware. The dynamic approach would ensure that Flutter+Fuchsia would perform optimally on all target hardware. 

## Proposal

We are proposing two changes in tandem: one outside of flutter/engine and one in it:
- Add a config.json file containing certain values that Flutter would read. This would be wherever the product code that uses Flutter is stored, and could be open or closed source.
- A change in flutter/engine code that would read from this config.json file and if it exists, modify relevant values. If the config.json file does not exist, or more generally if certain fields we expect are undefined, then there would be no change in behavior, i.e. we would use the default values specified in the code. This would be the case for Fuchsia builds for a new or unsupported product.

In our case, we want to modify the `fml::TimeDelta vsync_offset` field which was introduced in `vsync_waiter.h` as a way to control how when, in relation to vsync, Flutter wakes up to start producing the next frame. This approach would also scale well if and when we introduce more fields we want to be able to change.

### Prior Art

This proposal is based on what Chrome is doing for its similar use cases. Here, web_runner reads from a config.json file to decide whether Vulkan is enabled: https://fuchsia-review.googlesource.com/c/topaz/+/364933. The config.json file is added in a closed source repository.

**Comment by arbreng** [comment]
https://github.com/flutter/engine/pull/18006 fixed this
