### ISSUE TITLE
RenderBox was not laid out: RenderEditable#d3366 NEEDS-LAYOUT NEEDS-PAINT

### ISSUE THREAD

**Issue by reinaldobrazpereira** [flutter/flutter#51354]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by dnfield** [comment]
This issue is not actionable in its current state.  Please feel free to ping this bug again if you can add a minimal reproduction leading to this error.

If you just clicked submit before you finished editing the bug, please edit the relevant information into the bug and add a reply here so we can re-open it.

**Comment by Xgamefactory** [comment]
without further information this error message not clear for developers maybe flutter team should add additional information

`RenderBox was not laid out: RenderViewport#a3ddb NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE`
```

/flutter ( 4298): 'package:flutter/src/rendering/box.dart':
I/flutter ( 4298): Failed assertion: line 1694 pos 12: 'hasSize'
I/flutter ( 4298): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
I/flutter ( 4298): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
I/flutter ( 4298): #2      RenderBox.size 
package:flutter/…/rendering/box.dart:1694
I/flutter ( 4298): #3      RenderViewport.performLayout 
package:flutter/…/rendering/viewport.dart:1338
I/flutter ( 4298): #4      RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1630
I/flutter ( 4298): #5      PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:887
I/flutter ( 4298): #6      RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:402
I/flutter ( 4298): #7      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:884
I/flutter ( 4298): #8      RendererBinding._handlePersistentFrameCallback 
p
```

**Comment by dnfield** [comment]
This is almost always either a bug in the framework or a bug in some custom render object. If you're seeing it and have reproducible steps, please file an issue with them.
