### ISSUE TITLE
Gallery, Shrine, Landscape: Lots of whitespace between teapot and items below

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5135]
On iOS. Open gallery, tap into shrine, go landscape, scroll down a bit.

Notice lots of whitespace:

![a2951eea-ffe0-49e7-97d6-35f41b3e3ad9](https://cloud.githubusercontent.com/assets/5479/17256006/66527c90-5570-11e6-8084-8dd44cb829e5.PNG)

**Comment by eseidelGoogle** [comment]
Yup.  Still true as of 3a43fc88b66b042c612c04c3e2b8445ba1b27546.  It's due to the text getting pushed down in https://github.com/flutter/flutter/issues/5134.
