### ISSUE TITLE
Response is null

### ISSUE THREAD

**Issue by irakli1990** [flutter/flutter#51358]
what is wrong with this code? i'm trying do TDD flutter application and stuck here.

```


abstract class AdviceRemoteDataSource {
  /// Calls the endpoint.
  ///
  /// Throws a [ServerException] for all error codes.
  Future<http.Response> getRemoteAdvice();
}

class AdviceRemoteDataSourceImpl implements AdviceRemoteDataSource {
  final http.Client client;

  AdviceRemoteDataSourceImpl({@required this.client});
  Future<http.Response> getRemoteAdvice() async {
    final response = await client.get(URL);
    if (response.statusCode == 200) {
      return response;
    } else {
      throw ServerException();
    }
  }
}

````

![image](https://user-images.githubusercontent.com/26899911/75186998-63fd5f80-5749-11ea-9ce9-8e35ea02f3ef.png)

![image](https://user-images.githubusercontent.com/26899911/75187260-01589380-574a-11ea-8836-6609177b2bbb.png)

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
