### ISSUE TITLE
Measure usage of Hot Reload

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5136]
We can measure how often Hot Reload is used, how long it takes, and if it succeeded or not.

Some ideas:
- ping when `r` is used by user, measure how long the reload took, and report "yes, reload finished" or "no, reload did not finish" (we'd like to know how often a user tries a reload, but can't reload due to something prohibiting it like a source change that isn't reloadable, so we can learn if users are making source changes that aren't reloadable)
- ping when `R` is used. Similar to above.
- report when a crash happens in the `r` or `R` code, from within the flutter tool or framework itself. This can answer "was the crash the fault of flutter?" Not sure if this is possible, but we'd like to know how stable this new feature is.

Can we measure a useful time from the reload process?

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
I am ready to wire this up but I am unfamiliar with usage and analytics enough to know what I should report (and specifically *how* to report it).

**Comment by eseidelGoogle** [comment]
@devoncarew would know.  We use package:usage last I knew.

**Comment by johnmccutchan** [comment]
@devoncarew Should I report using `sendCommand` or `sendEvent` or maybe `startTimer`. I have some other metadata that I would like to report with events as well. Any tips here are appreciated.

**Comment by devoncarew** [comment]
There's an art to it. A lot of it depends how you want to pull the data out on the reporting side.

We've been using the commands to indicate parts of the app the user is in - so the `run` (flutter run) command or the `analyze` (flutter analyze) command. I think for this case we'd want to map a reload action to an event, and probably double report it as well as a timer, so that we get some (aggregated) elapsed time numbers.

**Comment by eseidelGoogle** [comment]
I'm pretty sure we're doing this now, no?  @johnmccutchan

**Comment by eseidelGoogle** [comment]
Speculatively closing.  Please re-open if I'm mistaken.

**Comment by sethladd** [comment]
We do this now! :)
