### ISSUE TITLE
Building apps with closed source dependencies

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#51362]
## Use case

A start-up has patented a cunning new way of compressing data and has developed a Flutter package that implements it.

They want to sell copies of this library to Flutter app developers who value this capability. They don't want to release the source code publicly (to pub.dev), because they consider the contents to include proprietary information. They realise reverse engineering can eventually unpick everything, but they would still prefer to ship a closed-source library.

## Proposal

1. Flutter to add support for building against AOT-compiled Dart code. Perhaps this would be a new dependency source type (e.g. "native")?

```
dependencies:
  transmogrify:
    native: /Users/me/transmogrify.bin
```

2. Flutter to add support for building closed-source packages for distribution. This might be a variant of the flutter build commands, which outputs the compiled library (and any associated metadata).

**Comment by dnfield** [comment]
For part 2, you should be able to use the `flutter build aar` and `flutter build ios-framework` commands already.

For part 1, we would need some help from the Dart team, and I have some serious doubts about the viability of such a request - AFAIK the Dart compiler for the VM assumes it has access to source code, and doing this would defeat several important features like tree shaking.

I would suggest that if you have a proprietary feature you want to ship, the correct way to do so is to write it in some non-Dart language and then use platform channels or dart:ffi to talk to it.

**Comment by dmjones** [comment]
Good advice, I'll close this issue as it doesn't seem sensible to consider it further.
