### ISSUE TITLE
LayoutBuilder's builder param should be required

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#51363]
RE:https://github.com/flutter/flutter/blob/0b8abb4724/packages/flutter/lib/src/widgets/layout_builder.dart#L203
Seeing as a `LayoutBuilder` with no child widget is useless, i proposed that the param should be required.

**Comment by dnfield** [comment]
This seems like a pretty simple oversight - the ctor linked passes through to another ctor that _does_ mark the parameter as `@required` and have the expected assertion.  @ThinkDigitalSoftware would you be willing to make a PR for this?  It should be pretty simple.

**Comment by ThinkDigitalSoftware** [comment]
I would, except I'm afraid of tests I may need to complete... Had to do tests for a doocumentation change....

On Feb 24, 2020 10:59 PM, Dan Field <notifications@github.com> wrote:

This seems like a pretty simple oversight - the ctor linked passes through to another ctor that does mark the parameter as @required and have the expected assertion. @ThinkDigitalSoftware<https://github.com/ThinkDigitalSoftware> would you be willing to make a PR for this? It should be pretty simple.

**Comment by dnfield** [comment]
To be completely fair, the change you last made touched snippet/sample code, which is code in documentation, which we do test.  Normally for a doc only change we don't require that :)

I'd be inclined to think this change would not require a test on its own.  We might want some kind of lint if possible to check for these things on the Dart end, but I don't think that would be a pre-req to landing this change.  @Hixie may have a better idea.  I filed an issue to track creating a lint for this.

Worst case scenario, you'd want to add a test that asserts the constructor throws if you fail to specify the parameter.  It would look something like this:

```
test('Constructor throws when missing parameter', () {
  expect(LayoutBuilder(builder: null), throwsAssertionError);
});
```

**Comment by dnfield** [comment]
Although that test would pass today, since the super constructor would throw the assertion as well.  I don't think we can write ameaningful test for this short of writing a special lint for it, and I don't think that should block landing the fix.

You could do something really silly like having the code sitting in a file you try to analyze and asserting the linter gives you an error for it, but that would be pretty silly and more a test of the analyzer than of the framework.

**Comment by ThinkDigitalSoftware** [comment]
To be honest, I may never get around to doing it if it's more than simply adding the @required annotation

On Feb 25, 2020 12:05 AM, Dan Field <notifications@github.com> wrote:

Although that test would pass today, since the super constructor would throw the assertion as well. I don't think we can write ameaningful test for this short of writing a special lint for it, and I don't think that should block landing the fix.

You could do something really silly like having the code sitting in a file you try to analyze and asserting the linter gives you an error for it, but that would be pretty silly and more a test of the analyzer than of the framework.

**Comment by Hixie** [comment]
Is there problem just that it's not listed as required in the documentation, it is it that the analyzer doesn't complain?

**Comment by dnfield** [comment]
The analyzer won't complain because we forgot the annotation on the subclass, which ends up hiding it on the base class.  I didn't check docs.

**Comment by dnfield** [comment]
When null safety comes through we will have to fix this anyway.

**Comment by Hixie** [comment]
Analyzer behaviour is definitely testable. :-)

**Comment by maschad** [comment]
How would I go about testing the analyzer behaviour @Hixie ?
