### ISSUE TITLE
Android 11 Issues and Features

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#51365]
Since Android 11's [developer preview has been released](https://developer.android.com/preview), we should track features and potential issues that we would need to cover in Flutter. I'll start to do some research into what we might have to implement, but feel free to comment here if there's any features catches anybody's attention! 

List of Android 11 features: https://developer.android.com/preview/features
Android 11 timeline: https://developer.android.com/preview/overview

Features:
- [Waterfall inset API support](https://developer.android.com/reference/android/view/DisplayCutout#getWaterfallInsets()) - Might come in the form of an Android plugin for `DisplayCutout` or exposing the insets directly in the framework. https://github.com/flutter/flutter/issues/52674

The goal is to have this issue be the compilation of necessary features and issues that users face. When a new issue or feature request surfaces related to Android 11, we then create a new, separate issue and add it to this list.

**Comment by dnfield** [comment]
I've removed the `dependency: android` which indicates either a potential bug in Android or a need for more help from the Android team directly, and added platform-android.

We may want to create a label specifically for Android 11 to track these.

**Comment by xxygrr** [comment]
Are [Wireless debuging](https://developer.android.com/preview/features#wireless-adb) and [ADB incremental APK intallation](https://developer.android.com/preview/features#incremental) be working out of the box? Hot reload experience whould be awesome with them. 

PD: Please let me know if this comment should not be here, I'll immediately remove it. I'm just super exited with this feature.

**Comment by MrCreeper1008** [comment]
Will support for the new `WindowInsets` api be coming to Flutter as well? I especially need it to animate keyboard entrance.

**Comment by sidrao2006** [comment]
Android 11 has a stable release now with new APIs. 
What about flutter integrations with those APIs?

**Comment by GaryQian** [comment]
> Will support for the new `WindowInsets` api be coming to Flutter as well? I especially need it to animate keyboard entrance.

Both windowinsets API  https://github.com/flutter/engine/pull/20921 and keyboard animation https://github.com/flutter/engine/pull/20843 were added in the 1.22 Release

**Comment by chinmaygarde** [comment]
This seems like an old umbrella bug. The only issue linked has already been closed.
