### ISSUE TITLE
[animations] Make OpenContainer work with named routes

### ISSUE THREAD

**Issue by kuhnroyal** [flutter/flutter#51399]
## Use case

I want to implement OpenContainer for existing named routes. We use named routes to track the users path through the app with `NavigatorObserver`. Using anonymous routes makes this hard.

## Proposal

Don't hide `_OpenContainerRoute` and provide something like a `OpenContainerRouteArguments` instance in the `OpenContainerBuilder` to manually navigate.

**Comment by georgeherby** [comment]
I have just a created a PR on the packages repo for adding RouteSettings to OpenContainer. I think this should do what you want :)

**Comment by kuhnroyal** [comment]
Not exactly, I am looking for a built in way to use this in `onGenerateRoute`.

**Comment by AndroidNils** [comment]
This ticket is important to support iOS swipe back gesture and to get a pop result from a route.

**Comment by jamesdixon** [comment]
Also running into a need for this. 

Scenario is that we push a new screen using `OpenContainer` and from within container, I have an action that triggers a bottom.  Choosing a specific option in that bottom sheet triggers an alert dialog. If the user taps "save" in that alert dialog, I need to close both the dialog and the bottom sheet. I attempted to use `popUntil(ModalRoute.withName('routeName')` but because it wasn't pushed as a named route, it's throwing an error.

**Comment by softronaut** [comment]
I'm also waiting for this. For commercial/professional app, it's almost a must... I attempted to mimic Navigation.pop behaviour but, that iOS dragging from left behavior is whole another thing to implement.

**Comment by srombs** [comment]
I would also love to have this ability. I am running into the same problem as @AndroidNils

**Comment by Pomis** [comment]
Can't use OpenContainer in production because of lack of this feature.

**Comment by asidt** [comment]
I also would like to have this possibility.

**Comment by shashkiranr** [comment]
any update on this. This is a requirement.

**Comment by shashkiranr** [comment]
I found a workaround to use on onGenerateRoute for OpenContainer. I am sure there is a better way to do this. 

1. Copy the OpenContainer file code into your own. 
2. Change the **_OpenContainerRoute** to **OpenContainerRoute**
3. Change the  OpenContainerRoute `ModalRoute<void>` to `PageRoute<void>`
4. Add the following final variable to class **OpenContainer** and in its constructor
`  final String openBuilderRouteName;`
5. Comment  `await Navigator.of(context, rootNavigator: widget.useRootNavigator).push(MyOpenContainerRoute(...))` in **Future<void> openContainer()** and add ` await Navigator.of(context).pushNamed(widget.openBuilderRouteName, arguments: {
      'closedColor': widget.closedColor,
      'openColor': widget.openColor,
      'closedElevation': widget.closedElevation,
      'openElevation': widget.openElevation,
      'closedShape': widget.closedShape,
      'openShape': widget.openShape,
      'closedBuilder': widget.closedBuilder,
      'openBuilder': widget.openBuilder,
      'hideableKey': _hideableKey,
      'closedBuilderKey': _closedBuilderKey,
      'transitionDuration': widget.transitionDuration,
      'transitionType': widget.transitionType,
    });`
6. In your _onGenerateRoute_ method use the **OpenContainerRoute** from the step 2 to load the route `final dynamic arguments = route.arguments as Map;
      return OpenContainerRoute(
        closedColor: arguments['closedColor'],
        openColor: arguments['openColor'],
        closedElevation: arguments['closedElevation'],
        openElevation: arguments['openElevation'],
        closedShape: arguments['closedShape'],
        openShape: arguments['openShape'],
        closedBuilder: arguments['closedBuilder'],
        openBuilder: arguments['openBuilder'],
        hideableKey: arguments['hideableKey'],
        closedBuilderKey: arguments['closedBuilderKey'],
        transitionDuration: arguments['transitionDuration'],
        transitionType: arguments['transitionType'],
      );`

**Note**: This is just a workaround. I am sure the actual solution is much simpler when it is available.

**Comment by britannio** [comment]
https://github.com/flutter/packages/pull/240 should have fixed this issue.

**Comment by doppio** [comment]
Thank you for the fix @britannio! 👍👍

**Comment by ffriande** [comment]
> [flutter/packages#240](https://github.com/flutter/packages/pull/240) should have fixed this issue.

Hey! This does seem to solve the issue, but how to use it? Shouldn't it already be available in animations: 1.1.2 ?

**Comment by britannio** [comment]
> > [flutter/packages#240](https://github.com/flutter/packages/pull/240) should have fixed this issue.
> 
> Hey! This does seem to solve the issue, but how to use it? Shouldn't it already be available in animations: 1.1.2 ?

It's available in the nullsafety release of this package.

**Comment by Vorkytaka** [comment]
Is there any examples how to use `OpenContainer` with named-navigation?
How to handle it in `MaterialApp.onGenerateRoute` or `MaterialApp.routes`?

**Comment by wmla419** [comment]
> > > [flutter/packages#240](https://github.com/flutter/packages/pull/240) should have fixed this issue.
> > 
> > 
> > Hey! This does seem to solve the issue, but how to use it? Shouldn't it already be available in animations: 1.1.2 ?
> 
> It's available in the nullsafety release of this package.

Can you provide an example of how to use the function?

**Comment by JarroVGIT** [comment]
> [flutter/packages#240](https://github.com/flutter/packages/pull/240) should have fixed this issue.

Hi Britanio, I have tried to use this feature but I cannot seem to figure it out. The openBuilder parameter still is required and is used to navigate to the next page. Even though I have a named route in my RouteSettings object that I pass to the routeSettings parameter. 

Would it be possible to provide us with a quick snippet of how this should work?

Many thanks in advance!

**Comment by britannio** [comment]
> is

Yes, specifying `routeSettings` doesn't defer open builder to an existing named route but it does allow the route name to be picked up with a `NavigatorObserver` provided to `MaterialApp` which I believe is what this issue is tracking.

**Comment by ValentinVignal** [comment]
Should this issue be closed since https://github.com/flutter/packages/pull/240 is merged?
