### ISSUE TITLE
TableBorder wrongfully drawing vertical border (only on iOS)

### ISSUE THREAD

**Issue by WasserEsser** [flutter/flutter#51408]
Repository can be cloned from here: https://github.com/WasserEsser/table_border_example

![image](https://user-images.githubusercontent.com/14238527/75258393-acb72600-57e6-11ea-9763-51541a087d52.png)

As you can see in the above screenshot, the table is drawing a vertical border between column cells, despite of TableBorder having no arguments (therefore falling back to BorderSide.none). It's very subtle in the example above and you might have to zoom in to see the issue clearly. Here is another screenshot where it's a lot clearer:

![image](https://user-images.githubusercontent.com/14238527/75259326-213e9480-57e8-11ea-908d-fd43631acdb9.png)

This issue only appears on iOS Simulators and devices.

**Comment by WasserEsser** [comment]
To clarify, the horizontal bottom border in the second screenshot is intentional and uses a box decoration on a container.

**Comment by b1acKr0se** [comment]
@WasserEsser Why did you close this issue? I'm having the same problem as well.
