### ISSUE TITLE
Error: shared_preferences_platform_interface-1.0.3/pubspec.yaml: Missing the required “name” field

### ISSUE THREAD

**Issue by chinkysight** [flutter/flutter#51403]
Having an issue with **`shared_preferences: ^0.5.6+2`** when I run` flutter pub get` it's giving me this exception: 

```
pub get failed (65; Error on line 1, column 1 of
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+2/pubspec.yaml: Missing the required
"name" field.)
```

**Comment by VladyslavBondarenko** [comment]
Hi @chinkysight 
Could you provide your `flutter doctor -v`?

**Comment by chinkysight** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/chinkysight/Downloads/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/chinkysight/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Redmi Note 4X • 34a774b00804 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
@chinkysight 
do you see the same error after running `flutter pub cache repair`?

**Comment by chinkysight** [comment]
I am getting the same error after performing `flutter pub cache repair` : 

Resetting Git repository for assets_for_android_views 0.1.0...
Error on line 1, column 1 of ../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_platform_interface-1.0.3/pubspec.yaml: Missing the required "name" field.
pub finished with exit code 65

**Comment by godsoul** [comment]
I am reinstall flutter and android studio，solved this problem，thnx

**Comment by chinkysight** [comment]
It's crazy I had downgraded the package version to `^0.5.6` but still, i am getting issue like this one: 

```
pub get failed (65; Error on line 1, column 1 of
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+2/pubspec.yaml: Missing the required
"name" field.)
```
It's talking about the `shared_preferences-0.5.6+2` even tho I am using the `^0.5.6`

**Comment by mhmdanas** [comment]
@chinkysight don't you want `0.5.6` instead of `^0.5.6`? `^0.5.6` is equivalent to `>=0.5.6 <0.5.7`. See [here](https://dart.dev/tools/pub/dependencies#caret-syntax) for more information.

**Comment by VladyslavBondarenko** [comment]
@chinkysight is it still an issue for you?

**Comment by chinkysight** [comment]
Same issue on using `shared_preferences: 0.5.6`

```
Error on line 1, column 1 of ../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_platform_interface-1.0.3/pubspec.yaml: Missing the required "name" field.
pub get failed (65; Error on line 1, column 1 of ../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_platform_interface-1.0.3/pubspec.yaml: Missing the required "name" field.)
exit code 65
```

**Comment by chinkysight** [comment]
This one helped me: https://stackoverflow.com/questions/61201286/error-shared-preferences-platform-interface-1-0-3-pubspec-yaml-missing-the-req
