### ISSUE TITLE
java.io.IOException: Permission Denied

### ISSUE THREAD

**Issue by r4v3r23** [flutter/flutter#51415]
project: https://code.samourai.io/r4v3r23/sentinel-x

built & installed apk and bundled tor fails to connect.

`adb logcat` from device:

> java.io.IOException:` Cannot run program "/data/user/0/com.invertedx.sentinelx/app_torfiles/tor.so" (in directory "/data/user/0/com.invertedx.sentinelx/app_torfiles"): error=13, Permission denied

`flutter doctor` shows no issues:

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.5)

**Comment by TahaTesser** [comment]
Hi @r4v3r23 
Running your project successfully builds an APK for me but this issue could be related to [#50880](https://github.com/flutter/flutter/issues/50880) [#44041](https://github.com/flutter/flutter/issues/44041)

Thank you

**Comment by r4v3r23** [comment]
@TahaTesser have you tried connecting to tor on the app? 

the error im getting is from adb logcat on the device when I try to connect to tor

**Comment by TahaTesser** [comment]
Hi @r4v3r23 
Issue you're describing with Tor isn't related to Flutter. 
Since you're using native Tor module
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by r4v3r23** [comment]
@TahaTesser the apk is building fine but tor doesnt have permissions. this isnt a flutter issue in the build?

**Comment by TahaTesser** [comment]
@r4v3r23 
It's not the building issue, Tor module is Android native in your code and it has nothing to do with Flutter
