### ISSUE TITLE
Add option to control app from android_alam_manager

### ISSUE THREAD

**Issue by geisterfurz007** [flutter/flutter#51413]
## Use case

I am developing a simple alarm clock app which should show a certain screen when the alam plays so you can turn it off. Using the little hack in #30555 I was able to get the app to wake up the device and play music already but I am having trouble getting the app to change the screen (obviously; with the callback of the android_alarm_manager running in an isolate). With `Isolate.current.controlPort` I have the ability to send messages *somewhere* but apparently no chance of catching those messages in the running app to manipulate it.

I looked around for options on how to get access to the main isolate, tried using `runApp` (similar to #32617) in an attempt to get access to a new running app I could do my shenanigans in which failed once again due to the isolate issue.

## Proposal

I am not sure in how feasible this is but I thought of something like a general / unified stream getting the data from the ReceiverPorts of the alarms created.

Using something like `AndroidAlarmManager.callbackMessageStream.listen()` on the app side would then allow reacting to message created in the callback through `Isolate.current.controlPort.send()`.

**Comment by automatensalat** [comment]
I've been scratching my head to this problem for some time now and I'm glad you bring this up. I'd be grateful for any solutions or updates to this.

**Comment by geisterfurz007** [comment]
Heyo! Currently I am using a rather ugly polling mechanism for my usecase. I drop specific files into a directory when the alarm goes off (for example a file called `1.alarm` when the alarm with the callback id 1 runs) and in the app I run a loop checking for `*.alarm` files in the main function (or optionally as life cycle listener when the app resumes). When such a file is found, I am then running the changes in the app and remove the file once I am done.
Same thing works the other way around (for example when you play a custom music file from the alarm callback), create a `id.disable` file or something like that, poll for that in the callback, stop the player (or do something else for your usecase) and delete the file.

However I sincerely hope that there will be an official API for this because this does not feel very good and creates a bit of boilerplate just for creating and looking up those files.

**Comment by automatensalat** [comment]
Well ok, this does not sound like a solution we should strive for. I'm starting to doubt if a solution would be meaningful at all - since the alarm callbacks are also supposed to be called when the app ends, what does it mean to have a main isolate then? Unfortunately I don't know enough about dart and isolates at this point to provide some meaningful input but I'll try to read up on this and come up with something.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager`](https://pub.dev/packages/android_alarm_manager_plus).
