### ISSUE TITLE
The Flutter app always restart when opened in the most recent application

### ISSUE THREAD

**Issue by laksithakumara** [flutter/flutter#51416]
Flutter app always restarts when opening from the recent app. flutter shows black colour background.

**Comment by VladyslavBondarenko** [comment]
@laksithakumara can you see this black screen only in debug mode? not in release?

**Comment by laksithakumara** [comment]
it does not happen flutter version number 1.12.13+hotfix.7. I just tested a few version of flutter and few open source projects. All open source project have this issue. Can be solved if use 1.12.13+hotfix.7

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/47024#issuecomment-566142519

Tested, it appears only in debug mode on android emulator, but not on real device and not in release mode (for 1.12.13+hotfix.7 and hotfix.8 as well).
(haven't rested with iOS)

Closing as it seems to be not an issue
if you disagree or you face with this with another environment please write in the comments and I will reopen it.
Thank you

**Comment by helloarshakhere** [comment]
my app get  restarted when i minimise and on using image picker to upload photo
