### ISSUE TITLE
[web] Support custom Canvas Kit URL

### ISSUE THREAD

**Issue by Mravuri96** [flutter/flutter#51424]
## Steps to Reproduce

1. Run `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --csp --tree-shake-icons`.
2. Deploy website to a sub domain

## Issue
1. On AOT Builds, the first load of the website is fine. Subsequent refreshes of the website is failing to fetch `canvaskit.wasm`, causing the website to go blank.

## Error
![Screen Shot 2020-02-25 at 10 07 04 AM](https://user-images.githubusercontent.com/28457922/75275739-ce4de880-57b9-11ea-8758-d03d8d3ae003.png)

## Demo
1. Navigate to [subdomain](http://flyx.maheshwarravuri.com/)
2. perform a simple refresh on the website

## Temporary solution
Empty Cache and hard refresh fixes this issue

## Flutter doctor
```
✓] Flutter (Channel master, v1.15.4-pre.155, on Mac OS X 10.15.4 19E234g, locale en-US)
    • Flutter version 1.15.4-pre.155 at /Users/mahesh/Development/flutter
    • Framework revision 2078cc4d5f (13 hours ago), 2020-02-25 01:02:26 -0500
    • Engine revision 888a62cf22
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 4.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E234g
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @Mravuri96 
what flutter version do you use?

**Comment by Mravuri96** [comment]
> Hi @Mravuri96
> what flutter version do you use?

v1.15.4-pre.155

**Comment by yzg-github** [comment]
hi@yjbanov here i have two question:
1.i want to build a flutter web app within canvaskit,then i set --dart-define=FLUTTER_WEB_USE_SKIA=true but it seems not work. how can i make sure the value --dart-define=FLUTTER_WEB_USE_SKIA=true has worked?
2.how can i build a flutter web app within local canvaskit? i can't find any article about how to use local canvaskit?could you tell me the setps about using local canvaskit in a flutter web app? 
thanks

**Comment by VladyslavBondarenko** [comment]
@yzg-github I'm linking your question here https://github.com/flutter/flutter/issues/61610
