### ISSUE TITLE
Gallery, landscape, date picker: Picker is scrollable on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5142]
On iOS, open gallery, go landscape, tap into date picker, then scroll down inside the picker.

Notice how you can pull the picker down and expose the white background:

![4a73c605-1c7b-41b6-8c94-c4b3759aa370](https://cloud.githubusercontent.com/assets/5479/17257577/9133db32-5577-11e6-8454-22032e954563.PNG)

**Comment by sethladd** [comment]
Might be related (the effect on Android): https://github.com/flutter/flutter/issues/6057

**Comment by abarth** [comment]
Yes, this is fixed now.  You'll still be able to scroll the calendar, but the overscroll will appear below the title.
