### ISSUE TITLE
Flutter desktop keyboard number pad sending actions and numbers

### ISSUE THREAD

**Issue by a344254** [flutter/flutter#51431]
I cloned the [flutter-desktop-embedding](https://github.com/google/flutter-desktop-embedding) repository then added a textfield to the scaffold, and noticed that when entering numbers via the number pad on a desktop keyboard, it's sending the numbers along with the functions of the keys. For example, the 4 key sends a left arrow function, then types the letter 4. The 6 key sends a right arrow function, then the number 6. The 1 key sends the "end" function to go to the end of the line, then enters the number 1. If I use the number keys above the qwerty portion of the keyboard, the numbers function normally.

This is running on Windows 10, with either a physical or on-screen keyboard
```
[√] Flutter (Channel master, v1.15.4-pre.155, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[!] Proxy Configuration
! NO_PROXY is not set
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by stuartmorgan** [comment]
/cc @gspencergoog @franciscojma86 

We'll want to test this after the rewrite and see if it's fixed, or if there's something happening at a different layer that the rewrite doesn't fix.

**Comment by askareija** [comment]
is turning on/off num lock make difference?

**Comment by a344254** [comment]
@askareija with num lock off, the action keys behave as expected (arrow left, right, etc).  With num lock on, you get the action AND the number

**Comment by a344254** [comment]
@stuartmorgan  do you have an ETA on the rewrite that might fix it?

**Comment by stuartmorgan** [comment]
No, but you can follow #44918 for updates.

**Comment by franciscojma86** [comment]
This migh't been fixed by https://github.com/flutter/flutter/issues/37710 @a344254 can you please confirm?

**Comment by stuartmorgan** [comment]
@a344254 Is this still happening? (I don't currently have access to a non-laptop Windows machine to test.)

**Comment by a344254** [comment]
Hi Stuart – I’ve been away from the office since Covid hit, but once I’m back I’ll test this out and see if it’s fixed. Thanks


Kevin McKee
Application Development Architect
Goodyear Canada Inc.
388 Goodyear Rd, Napanee, ON  K7R 3L2
phone.613.354.7850
krmckee@goodyear.com

**Comment by a344254** [comment]
Hi Stuart.  This appears to have fixed the keyboard issue.  Thanks!


Kevin McKee
Application Development Architect
Goodyear Canada Inc.
388 Goodyear Rd, Napanee, ON  K7R 3L2
phone.613.354.7850
krmckee@goodyear.com

From: Kevin McKee <krmckee@goodyear.com>
Date: Friday, June 12, 2020 at 7:22 AM
To: flutter/flutter <reply@reply.github.com>, flutter/flutter <flutter@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [EXT] Re: [flutter/flutter] Flutter desktop keyboard number pad sending actions and numbers (#51431)

Hi Stuart – I’ve been away from the office since Covid hit, but once I’m back I’ll test this out and see if it’s fixed. Thanks


Kevin McKee
Application Development Architect
Goodyear Canada Inc.
388 Goodyear Rd, Napanee, ON  K7R 3L2
phone.613.354.7850
krmckee@goodyear.com

**Comment by stuartmorgan** [comment]
Great, thanks for following up! Closing as fixed.
