### ISSUE TITLE
Write a real Visual Studio solution file parser

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#51430]
https://github.com/flutter/flutter/pull/51246 adds code that can modify a `.sln` file to add/remove plugin project references. That code is fairly ugly though; it does line-by-line regex parsing, with a small amount of manual state tracking to know where it is in the file when necessary.

If we keep that approach to Windows plugin handling, we should look into replacing that with an actual `.sln` parser that would let us build a structural representation, modify it in a clear declarative way, then write it out again. We'd need to be careful to make sure it would not corrupt/lose parts of the file we don't understand (e.g., we could potentially make it default to processing the contents of project/global sections by just storing each line, and only breaking those down into tokens for the specific sections whose contents we care about and know we can describe).

**Comment by kriti45** [comment]
Hey! can you guide me how to get started with this issue?

**Comment by stuartmorgan** [comment]
This code no longer exists after the transition to CMake.
