### ISSUE TITLE
Flutter docset directory structure error?

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#51446]
I build the docset and import it into the Zeal, but got the following error.

![image](https://user-images.githubusercontent.com/2276718/75308016-3c60e100-5888-11ea-82fb-c556d308e394.png)

In my case, I have to remove the files in doc directory to the up level directory.
```
mv C:\Users\Liu.D.H\AppData\Local\Zeal\Zeal\docsets\flutter.docset\Contents\Resources\Documents\doc\* C:\Users\Liu.D.H\AppData\Local\Zeal\Zeal\docsets\flutter.docset\Contents\Resources\Documents\
rm -rf C:\Users\Liu.D.H\AppData\Local\Zeal\Zeal\docsets\flutter.docset\Contents\Resources\Documents\doc
```

## Steps to Reproduce

1. build the docset described on https://github.com/flutter/flutter/issues/51203
2. import the docset in Zeal

**Comment by markusaksli-nc** [comment]
Hi @liudonghua123 
Did I understand correctly that you solved the issue? Is this also the case on the latest master?
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
