### ISSUE TITLE
Gallery, Landscape, Animation: circles and squares are clipped or off screen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5145]
On iOS, open gallery, go landscape, tap into Animations.

Notice how the circle is clipped and one of the rectangles is off screen.

![210ddae4-7ac1-4303-bd3e-98efb1d5ae86](https://cloud.githubusercontent.com/assets/5479/17257733/47df4646-5578-11e6-858f-1ceb20300a54.PNG)

![1dbe96d1-69c2-4499-a6ba-bbf7039b730a](https://cloud.githubusercontent.com/assets/5479/17257736/4af78316-5578-11e6-8e17-2685487e992f.PNG)

**Comment by sethladd** [comment]
On landscape, we now see both boxes. However, only on the iPhone do we see the complete lower red box. On the nexus 5 and 6p, the red box's bottom border is not visible.

User testing shows that this UI is hard/very-hard for evaluators to use. Consider re-thinking this UI to make it easier for the developer to play with this example.

**Comment by eseidelGoogle** [comment]
iirc we removed this animation demo.
