### ISSUE TITLE
[animations] - callback (or similar) when user navigates back to closedBuilder

### ISSUE THREAD

**Issue by ben04** [flutter/flutter#51458]
**I'm using the new animations package.**

## Use case
The user opens the second page, enters information which, after navigating back to the first page, must be available on this first page.

## Old way
So far, without the animations package, I just put a 'await' before the `Navigator.push()` and could call the method, which should be executed when the user navigates back, after that statement.
```
await Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => DetailView()),
    );
loadData();
```

## Proposal / Question?
How is that possible with the animations package? The `Navigator.push()` method is called within a void method, so I can't wait for that. I haven't found any other way to do that so far.

**Comment by esDotDev** [comment]
Also would be nice to somehow get the pop results as well.

**Comment by goderbauer** [comment]
The action callback supplied to the closedContainer builder could return the Future from Navigator.push:

https://github.com/flutter/packages/blob/c1a2bf88dfd6c2667c50cdfba690279c480a57a6/packages/animations/lib/src/open_container.dart#L224

This should be an easy change.
