### ISSUE TITLE
When new project is created in flutter scaffold is so much big that it does not fit my single screen while on dual monitor.

### ISSUE THREAD

**Issue by mitulgautam** [flutter/flutter#51451]
![Screenshot (12)](https://user-images.githubusercontent.com/25982094/75314841-edff1280-5886-11ea-96d6-fe947c6125d3.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Zazo032** [comment]
Could you paste the output of `flutter doctor -v`? I think this may be fixed in `master` channel via https://github.com/flutter/flutter/pull/51346. You can try that by running:

1. `flutter channel master`
2. `flutter upgrade`

**Comment by jonahwilliams** [comment]
@Zazo032  is right, this is probably fixed by #51346 . Tentatively closing but please reopen if this becomes a problem
