### ISSUE TITLE
quick_actions not showing icon in production app

### ISSUE THREAD

**Issue by topex-psy** [flutter/flutter#51455]
I use quick_actions (https://pub.dev/packages/quick_actions) package for my Android app. It works fine in debug mode. However, in release mode, the app shortcuts doesn't show the drawable icons instead shows the black-colored box.

Debug Version | Release Version (from Play Store)
:-------------------------:|:--------------------------:
![](https://user-images.githubusercontent.com/14989865/75320470-55c25700-58a1-11ea-84b1-69fea3fcfec9.jpg) | ![](https://user-images.githubusercontent.com/14989865/75320525-768aac80-58a1-11ea-9ded-0ebf74526371.jpg)

I have included my PNGs files in all following folders:

- /android/app/src/main/res/drawable/
- /android/app/src/main/res/mipmap-*/

`quick_actions: ^0.4.0+2`

```
@override
  void initState() {
    super.initState();

    final quickActions = QuickActions();
    quickActions.initialize((String shortcutType) {
      switch (shortcutType) {
        case 'catat_pemasukan':
        case 'catat_pengeluaran':
        case 'catat_transaksi':
          if (shortcutType == 'catat_pengeluaran') {
            initData = {'tipeTransaksi': TipeTransaksi.KREDIT};
          } else {
            initData = {'tipeTransaksi': TipeTransaksi.DEBIT};
          }
          _catatItem('manual');
          break;
        case 'catat_rencana':
          _catatRencana();
          break;
        case 'pindai_struk':
          _catatItem('ai');
          break;
      }
    });

    quickActions.setShortcutItems(<ShortcutItem>[
      ShortcutItem(
        type: 'catat_transaksi',
        localizedTitle: 'Catat Transaksi',
        icon: 'ic_pen',
      ),
      ShortcutItem(
        type: 'catat_rencana',
        localizedTitle: 'Catat Rencana',
        icon: 'ic_calendar'
      ),
      ShortcutItem(
        type: 'pindai_struk',
        localizedTitle: 'Pindai Struk',
        icon: 'ic_shutter',
      ),
    ]);
  }
```

`flutter doctor -v` result:

```
[√] Flutter (Channel master, v1.15.4-pre.140, on Microsoft Windows [Version 10.0.18362.657], locale en-ID)
    • Flutter version 1.15.4-pre.140 at G:\Android\Flutter\flutter
    • Framework revision 1d4667bb38 (2 days ago), 2020-02-24 08:56:02 +0530
    • Engine revision f2f8c342be
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 0f141be8bd)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: G:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at G:\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

Where am I wrong? How to solve this? Answers appreciated.

**Comment by VladyslavBondarenko** [comment]
Hi @topex-psy 
could you provide your `flutter doctor -v`?

**Comment by topex-psy** [comment]
@VladyslavBondarenko I have updated my post and provided the `flutter doctor -v` result.

**Comment by topex-psy** [comment]
I just found the workaround yesterday. This issue happen because the drawable resources thought as unused thus they're purged when building into production app.

Create `\android\app\src\main\res\drawable\quick_actions.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@drawable/ic_calendar" />
    <item android:drawable="@drawable/ic_pen" />
    <item android:drawable="@drawable/ic_price_tag" />
    <item android:drawable="@drawable/ic_shutter" />

</layer-list>
```

Edit `\android\app\src\main\res\values\styles.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    ...
    <style name="QuickActions">
        <item name="android:windowBackground">@drawable/quick_actions</item>
    </style>
</resources>
```

I'll left this issue open until the plugin updated and have more feasible solution.

**Comment by edwin-alvarez** [comment]
have you try to use actions in IOS, I notice the selected action is not getting set

**Comment by topex-psy** [comment]
> have you try to use actions in IOS, I notice the selected action is not getting set

I haven't tried in iOS

**Comment by jeanmatthieud** [comment]
Another quick fix is to create a "res/raw/keep.xml" file, with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@mipmap/filetokeep"/>
```
and replace "filetokeep" by the name of your ressource file.

[Source](https://stackoverflow.com/a/45782594)

**Comment by renefloor** [comment]
> Another quick fix is to create a `res/raw/keep.xml` file, with the following content:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources xmlns:tools="http://schemas.android.com/tools"
>     tools:keep="@mipmap/filetokeep"/>
> ```
> 
> and replace "filetokeep" by the name of your ressource file.
> 
> [Source](https://stackoverflow.com/a/45782594)

If it is still an issue, maybe we should add this to the readme.

**Comment by ghenry** [comment]
Still happening on 2.2. I'll do what is suggested here.

**Comment by dev1-beecept** [comment]
> Another quick fix is to create a `res/raw/keep.xml` file, with the following content:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources xmlns:tools="http://schemas.android.com/tools"
>     tools:keep="@mipmap/filetokeep"/>
> ```
> 
> and replace "filetokeep" by the name of your ressource file.
> 
> [Source](https://stackoverflow.com/a/45782594)

This was working fine. Thank you.

**Comment by dev1-beecept** [comment]
> have you try to use actions in IOS, I notice the selected action is not getting set

Same issue fencing in iOS.

**Comment by vjk10** [comment]
Updated the keep.xml file and created Drawables. But still facing the issue. When running flutter release it works fine. But when uploading an app bundle with no shrink to the play store and using the app from there, the icons are greyed out

![Screenshot_20220915-153042.png](https://user-images.githubusercontent.com/41936318/190375897-b167bb98-9235-4321-bb02-992ab91d99ad.png)
