### ISSUE TITLE
Disable landscape mode in Gallery for v1

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5146]
Otherwise we have a ton of landscape bugs to fix, e.g. #5143 #5141 #5131 #5144 #5142 #5140 #5139 #5134 #4899

We had to do something similar for the Game v1.  Thoughts @HansMuller?

**Comment by HansMuller** [comment]
There isn't time to get all of the landscape layouts sorted by August, so disabling landscape mode sounds like a good idea.

How do we disable landscape mode?

**Comment by eseidelGoogle** [comment]
Editing Info.plist and AndroidManifest.xml.  I believe the key is UISupportedInterfaceOrientations in Info.plist (there are Checkboxes for editing such from within XCode) and http://stackoverflow.com/questions/582185/android-disable-landscape-mode in Android.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/5210
