### ISSUE TITLE
prefix Icon default Color

### ISSUE THREAD

**Issue by RNSuthar** [flutter/flutter#51469]
prefixIcon icon not changeable using material color that's used static color from InputDecorationTheme class.

 Brightness.light => Colors.black45
 and if
 Brightness dark =>  Colors.white70
and if null => default Icon color

used this -

```
  Color _getDefaultIconColor(ThemeData themeData) {
    if (!decoration.enabled)
      return themeData.disabledColor;

    switch (themeData.brightness) {
      case Brightness.dark:
        return Colors.white70;
      case Brightness.light:
        return Colors.black45;
      default:
        return themeData.iconTheme.color;
    }
  }
```

**Comment by VladyslavBondarenko** [comment]
Hi @RNSuthar 

Does this code represent your case?
https://dartpad.dev/6dc2f8fe70676c587b2aa7712ff63033

if you haven't set brightness for theme, it is light by default, this is why you can't reach the `return themeData.iconTheme.color;` statement

Why do you need to have additional case of unset brightness except of light and dark?

**Comment by VladyslavBondarenko** [comment]
@RNSuthar 
I hope you've resolved your problem.
Closing since long time without an answer.
If you disagree please write in the comments and I will reopen it.
Thank you
