### ISSUE TITLE
Gallery Drawer header should be pretty

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5147]
Right now it just says "Flutter gallery" (not even the right caps) and no images.  @dragostis made a fancier drawer header.  Maybe we can show the Flutter logo here a least?

**Comment by Hixie** [comment]
I'll have a Decoration that can draw the logo without an asset soon, in case that helps.

**Comment by HansMuller** [comment]
I will decorate the draw header with Ian's logo and some properly capitalized titles ASAP
