### ISSUE TITLE
[web] Windows bots with GPUs on LUCI

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#51483]
The current bots we are using on LUCI does not have GPU. 

In order to do screenshot smoke testing we certainly need bots with GPU. 

We have problems connecting to Edge on Windows. We also believe it is related to the same root cause. https://github.com/flutter/flutter/issues/51427

Unfortunately Edge does not have a headless mode we can use for the existing bots.

**Comment by digiter** [comment]
Sorry that I don't know how to proceed here. Is there a way confirm the problem? For example, could you run the commands on a Windows GCE instance to see whether you can connect to Edge?

**Comment by digiter** [comment]
I created a temporary windows instance under GCP flutter-dashboard project, Nurhan is verifying whether the tests can run on it.

We probably need to customize the VM image that are currently using in fuchsia-infra. Maybe that needs to be "Windows Server with Desktop Experience".

**Comment by godofredoc** [comment]
@nturgut @digiter any updates on what image changes are required to support edge?

**Comment by nturgut** [comment]
Hi Godofredo, sorry I wasn't able to confirm it yet. Currently I need to connect to a remote which connects to another remote in order to do coding/testing on the Windows bot. 

I will let you know when I have a confirmation.

**Comment by nturgut** [comment]
Closing as duplicate: https://github.com/flutter/flutter/issues/53615
