### ISSUE TITLE
flutter_gallery_ios32__transition_perf regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#51488]
![image](https://user-images.githubusercontent.com/22987568/75374994-1cc6ba00-5882-11ea-837c-e479fe0b145d.png)

See also https://github.com/flutter/flutter/issues/48248#issuecomment-591546567

https://github.com/flutter/flutter/commit/69080e07e6bb178332bf546cf83054a85b91b2fe seems to be the culprit.

**Comment by liyuqian** [comment]
@ferhatb @yjbanov : is this a known performance trade-off for other critical improvements? If not, we may want to revert it, and investigate what happens.

**Comment by ferhatb** [comment]
Reverting

**Comment by liyuqian** [comment]
Thank you @ferhatb for the quick fix!
