### ISSUE TITLE
mustache dependency is un-maintained, not compatible with an AOT build

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#51486]
The mustache package dependency has not been receptive to changes to update for Dart 2, including removing of mirrors for dart2js. Now with the ability to AOT build the tool, we are also blocked by this dependency still using mirrors.

I've created a fork of the mustache template package which no longer includes all mirrors usage and has been updated with pedantic fixes for dart 2. https://pub.dev/packages/mustache_template

In order to update the flutter_tool to use this package, we need to ensure it is available in google3 first

fyi @natebosch @jakemac53

**Comment by natebosch** [comment]
Can we consider fixing some API issues in the package before the migration? What would be the best place to collect change suggestions? As issue on the repo?

**Comment by jonahwilliams** [comment]
It looks like some of the current usages of mustache require mirrors, this primarily supports the ability to look up class properties: 

https://github.com/xxgreg/mustache/blob/144195ce781a1763eefd4765d137fc667835240b/lib/src/renderer.dart#L242

Removing this functionality, or migrating it to generated code is likely a breaking change. There was a separate attempt with the package:mustache_reflectable, but that of course pulls along another large dependency. We attempted to reach out to the original package maintainer a few times, most recently https://github.com/xxgreg/mustache/issues/39#issuecomment-488407572

Unfortunately it looks like at least some of the usage in google3, so it can't be removed.

**Comment by jakemac53** [comment]
It looked like they were open to a PR to separate it into two entrypoints (a mirrors one and not)?

That seems like a reasonable path, although I don't know how entwined the mirrors support is with the rest of the library.

**Comment by maks** [comment]
@jonahwilliams apologies for commenting on this closed issue but https://pub.dev/packages/mustache_template has issues disabled so I can't ask there about what your plans are regarding external use and maintaince of that package?
