### ISSUE TITLE
Imports for data types.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5148]
It would be nice to have a `import 'whatnot' show ClassImInterestedIn` for each data types in our docs. Right now, it's not always so easy to figure what you need to import.

**Comment by abarth** [comment]
dartdoc has this information.  We should be able to generate it automatically.  /cc @devoncarew 

It's currently displayed in the header.  For example, "Flutter > material > AppBar" on https://docs.flutter.io/flutter/material/AppBar-class.html .  But it's not obvious from that what import statement to type.

**Comment by eseidelGoogle** [comment]
This seems like a bug which could/should be moved to dartdoc and closed?

**Comment by eseidelGoogle** [comment]
This is https://github.com/dart-lang/dartdoc/issues/1251.
