### ISSUE TITLE
JSON Decoder

### ISSUE THREAD

**Issue by calderonnavasj** [flutter/flutter#51494]
I have a problem trying to get a json file located on Github.

My code:

import 'dart:convert';

import 'package:jobber/src/core/services/location_service.dart';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart';

class JobsProvider {
  JobsProvider() {
    _getInstance();
  }

  SharedPreferences _prefsInstance;

  final _client = Client();
  final _baseUrl = 'https://raw.githubusercontent.com/calderonnavasj/reflexiones/master';

  Future<List<dynamic>> positionsFromLocation(UserLocation location) async {
    Response response;
    if (location != null) {
      final lat = Uri.encodeComponent(location.latitude.toString());
      final long = Uri.encodeComponent(location.longitude.toString());
      response = await _client.get(
        '$_baseUrl/positions.json?lat=$lat&long=$long',
      );
    } else {
      response = await _client.get('$_baseUrl/positions.json');
    }
    return _handleResponse(response);
  }

  Future<List<dynamic>> positions() async {
    final Response response = await _client.get('$_baseUrl/positions.json');
    return _handleResponse(response);
  }

  Future<List<dynamic>> savedPositions() async {
    if (_prefsInstance == null) await _getInstance();
    final savedPositions = _prefsInstance.getStringList('savedPositions') ?? [];
    final List<dynamic> positions = savedPositions.map((data) {
      try {
        return json.decode(data);
      } catch (e) {
        return null;
      }
    }).toList()
      ..removeWhere((position) => position == null);
    return positions;
  }

  Future<Map<String, dynamic>> positionFromId(String id) async {
    final saved = await savedPositions();
    final match = saved.firstWhere(
      (position) => position['id'] == id,
      orElse: () => null,
    );
    if (match != null) {
      return match;
    } else {
      final response = await _client.get(
        '$_baseUrl/positions/$id.json?markdown=true',
      );
      return _handleResponse(response, error: 'Failed to get position');
    }
  }

  dynamic _handleResponse(Response response, {String error}) {
    if (response.statusCode == 200) {
      return json.decode(response.body);
    } else {
      throw error ?? 'Failed to get positions';
    }
  }

  Future<void> _getInstance() async {
    final prefs = await SharedPreferences.getInstance();
    _prefsInstance = prefs;
  }
}

My error: 

E/flutter (16100): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Failed to get position
E/flutter (16100): #0      JobsProvider._handleResponse (package:jobber/src/core/resources/jobs_provider.dart:71:7)
E/flutter (16100): #1      JobsProvider.positionFromId (package:jobber/src/core/resources/jobs_provider.dart:63:14)
E/flutter (16100): <asynchronous suspension>
E/flutter (16100): #2      Position.getPosition (package:jobber/src/core/models/position.dart:56:42)
E/flutter (16100): #3      new Position.fromId (package:jobber/src/core/models/position.dart:21:5)
E/flutter (16100): #4      PositionDetails.build.<anonymous closure> (package:jobber/src/ui/screens/position_details.dart:21:32)
E/flutter (16100): #5      BuilderStateDelegate.initDelegate (package:provider/src/delegate_widget.dart:249:14)
E/flutter (16100): #6      _ListenableDelegateMixin.initDelegate (package:provider/src/listenable_provider.dart:168:11)
E/flutter (16100): #7      _DelegateWidgetState._initDelegate (package:provider/src/delegate_widget.dart:118:21)
E/flutter (16100): #8      _DelegateWidgetState.initState (package:provider/src/delegate_widget.dart:110:5)
E/flutter (16100): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (16100): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (16100): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (16100): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (16100): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (16100): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (16100): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (16100): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (16100): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (16100): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (16100): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (16100): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (16100): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (16100): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (16100): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (16100): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (16100): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (16100): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (16100): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (16100): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (16100): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (16100): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (16100): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (16100): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (16100): #45     Element.inflateWidget (pa

But when I change the link of the var:

  final _baseUrl = 'https://raw.githubusercontent.com/calderonnavasj/reflexiones/master';

To:

  final _baseUrl = 'https://jobs.github.com';

It's function!

Someone help me please!

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
