### ISSUE TITLE
IOS Build fails on launch (AppAuth)

### ISSUE THREAD

**Issue by abaker2010** [flutter/flutter#51492]
Hey everyone, so I am having an issue with build my application on ios physical devices. I can build for ios emulators just fine but then application crashes on boot. I used xCode to get the the report for the error. It seems that it is failing due to the `AppAuth` library not being able to be loaded. When I try to run the application on an iPhone from android studios the application never makes it pass this in the console:

```
Running pod install...
Running Xcode build...
Xcode build done.                                           87.4s
Installing and launching...

*it never connects to the system, loads a white screen then instantly fails*
```

<pre>
dyld: Library not loaded: @rpath/AppAuth.framework/AppAuth
  Referenced from: /private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: code signature invalid for '/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth'

	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: stat() failed with errno=25
	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: code signature invalid for '/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth'

	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: stat() failed with errno=1
	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: code signature invalid for '/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth'

	/private/var/containers/Bundle/Application/98709DA0-4705-4C3A-B666-72E601F33685/Runner.app/Frameworks/AppAuth.framework/AppAuth: stat() failed with errno=1
</pre>

<details close>
<summary>0__abort_with_payload</summary>
<br>
<img width="902" alt="Screen Shot 2020-02-26 at 12 44 00 PM" src="https://user-images.githubusercontent.com/7686813/75381379-e2ffae80-5895-11ea-92d1-16025013ee74.png">
</details>

<details close>
<summary>6_dyld_start</summary>
<br>
<img width="902" alt="Screen Shot 2020-02-26 at 12 44 44 PM" src="https://user-images.githubusercontent.com/7686813/75381534-22c69600-5896-11ea-9b1d-d2ecf660a350.png">
</details>

Here is my flutter doctor output 

<details close>
<summary>flutter -v doctor</summary>
<br>
<pre>
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/zedo/MyTownDevTools/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zedo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone • 00008030-001C6C991ED8802E • ios • iOS 13.3.1

• No issues found!
</pre>
</details>

Packages in the pubspec 

<details close>
<summary>pubspec.yaml</summary>
<br>
<pre>
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  share: ^0.6.3+5
  simple_animations: ^1.3.6
  avatar_glow:
  http:
  flutter_launcher_icons: ^0.7.4
  photo_view: ^0.9.2
  connectivity: ^0.4.6+2
  google_sign_in: ^4.1.1
  url_launcher: ^5.4.1
  flutter_google_places: ^0.2.4
  flutter_facebook_login: ^3.0.0
  firebase_database: ^3.1.1
  flutter_datetime_picker: ^1.3.4
  flutter_icons: ^1.0.0+1
  provider: ^4.1.0-dev
  cached_network_image: ^2.0.0-rc
  path: ^1.6.4
  flutter_credit_card: ^0.1.3
  intl: ^0.16.1
  tuple: ^1.0.3
</pre>
</details>

AppAuth version being used from the Podfile.lock: ```AppAuth (1.3.0)```

Any help on this issue would be  very appreciated I have been trying to figure this issue out for a while now. 

Thank you

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/49693
But I'm not sure is it the same

@abaker2010 follow on https://github.com/flutter/flutter/issues/49504

**Comment by abaker2010** [comment]
@VladyslavBondarenko thank you for the reply and the post on the issue. Sorry I didn't see that there was another issue posted about this, you are right jmagman's issue seems to be exactly what I'm experiencing.
