### ISSUE TITLE
 investigate flutter_runner_scenic_tests crash on LUCI

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51499]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=47081.

**Comment by digiter** [comment]
Triage: what should we do about it? @godofredoc

**Comment by godofredoc** [comment]
There are two parts for this:

Infra
------
* Timeout the gunit test execution.
* Pave the fuchsia devices with the fuchsia infra keys
* Start collecting syslogs.

Flutter + Fuchsia Teams
-------
To look at the cause of the crash using syslog.

**Comment by kf6gpe** [comment]
Fixed upstream.
