### ISSUE TITLE
Support ability to programmatically remove a snackbar before it times out or have the consecutive snackbar pushes close the previous ones immediately

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#515]
I have the following situation which I believe ability to programmatically remove a snackbar is useful. If this is not against the material design guidelines, we should consider supporting it.

Essentially I need to show a "permanent/long running" snackbar when an action is triggered (e.g. "Starting foo...") and remove it when the action completes or fails and show another snackbar. (e.g. "Foo started...", "Foo failed - DETAILS")

@Hixie @TheBosZ

**Comment by Hixie** [comment]
Done.

I still haven't added persistent snackbars, please file a new bug if you want that. I don't really understand how to make those work with later queued non-persistent ones.
