### ISSUE TITLE
`flutter screenshot` does not work for iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5150]
```
% flutter screenshot
Screenshot not supported for flutter_ipod_touch.
```

libimobiledevice supposedly supports this.  `flutter doctor` even knows if users have installed it.  I suspect the fix here is mostly in fixing this error message to say that it's required, and the small amount of plumbing to call whatever the right command line in that package is.

**Comment by eseidelGoogle** [comment]
Here is a demo which seems to work:
https://github.com/eseidelGoogle/flutter/commit/237797af776df8359c2ecb74c03868ec52b7a757

**Comment by eseidelGoogle** [comment]
@Hixie just made screenshot fancier.  Still an easy fix, but low priority.

**Comment by Hixie** [comment]
IMHO platform parity should be a priority before we attempt to attract high levels of attention.

**Comment by xster** [comment]
Upping this. Hit me a bunch of times already and users are going to need this to make screenshots for the store.

**Comment by eseidelGoogle** [comment]
Hopefully the patch I posted above is still working.  Just really needed someone to chaperone it through who was actually an active engineer on the project. :)

**Comment by xster** [comment]
Yes sir. Will shamelessly rip

**Comment by xster** [comment]
idevicescreenshot is only for physical devices.
Will swap the existing simulator code for https://developer.apple.com/library/content/documentation/IDEs/Conceptual/iOS_Simulator_Guide/InteractingwiththeiOSSimulator/InteractingwiththeiOSSimulator.html and support it for xcode 8.2+ only. The current applescript doesn't work very well.
