### ISSUE TITLE
ffi connot use staticlib func, but swift file could

### ISSUE THREAD

**Issue by Tonyce** [flutter/flutter#51509]
## Steps to Reproduce

I want to use flutter develop a new App, and with some static lib write with Rust. But now i have the trouble: Rust static lib func conn't be used by flutter with ffi. But after i call the func in SwiftNativeHelloPlugin.swfit, the func could be visible. 

How can i fix this problem ? 

```
final int Function(int x, int y) nativeSum = nativeAddLib
    .lookup<NativeFunction<Int32 Function(Int32 a, Int32 b)>>("sum")
    .asFunction();
```

```
public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "native_hello", binaryMessenger: registrar.messenger())
    let instance = SwiftNativeHelloPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)
    // sum(1,2) 
  }
```
dart ffi will be work if i enable sum .

**Comment by dcharkes** [comment]
What does the c function look like? Maybe you forgot to export it with `extern "C"`? (I presume that calling something from Swift will prompt XCode to automatically mark the C symbol as `extern "C"` for you.)

Please follow the steps from https://flutter.dev/docs/development/platform-integration/c-interop which describes in detail how to build a Flutter app with your own C++ source code and FFI bindings in it.

If you have more trouble, please post a link to a reproduction.

**Comment by Tonyce** [comment]
thanks for your reply. i will show you what i worked:
1. I create a new rust lib with the code
```
#[no_mangle]
pub extern "C" fn sum(x: i32, y: i32) -> i32 {
    x + y
}
```
i build the lib，and i can load the lib with dart
```
main() {
  var path = './target/debug/librusty_primitives.so';
  if (Platform.isMacOS) path = './target/debug/librusty_primitives.dylib';

  final dylib = DynamicLibrary.open(path);

  final sumPointer = dylib.lookup<NativeFunction<sum_func>>('sum');
  final sum = sumPointer.asFunction<Sum>();
  print('3 + 5 = ${sum(3, 5)}');
}
```
2. therefore，i thought i could use Flutter(awsome UI) with Rust (awsome IO) build Android and iOS App. so i began. 

3. i created a flutter plugin project, and the add librusty_primitives.a into ios/libs and edit podspec with
```
s.ios.vendored_library = 'libs/librusty_primitives.a'
```
the i edit lib/native_sum.dart and example/lib/main.dart follow the doc https://flutter.dev/docs/development/platform-integration/c-interop .

4. i run the example, but with the error: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, sum): symbol not found)

5. i thought may be i loss the header file, so i add rusty_primitives.h into ios/Classes , but still with Failed to lookup symbol (dlsym(RTLD_DEFAULT, sum): symbol not found).

6. i thougth i could call func in swift file at least, so i add this code into SwiftNativeHiPlugin.swift
```
public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    result("iOS " + UIDevice.current.systemVersion)
    sum(1,2)
  }
```
and then, i run flutter run. it works.

7. if i comment sum(1,2) in swift, the symbol not found error again

so what's the problem and how i can i fix the problem

**Comment by dcharkes** [comment]
> i build the lib

If you build the lib outside of XCode, then XCode does not set up the linking correctly. So the whole lib might not be linked in your final app binary.

> To create a Flutter plugin that includes Dart source code, but distribute the C/C++ library in binary form, use the following instructions:
> 
> 1. In your plugin project, open ios/<myproject>.podspec.
> 2. Add a vendored_frameworks field. See the CocoaPods example.

https://flutter.dev/docs/development/platform-integration/c-interop#closed-source-third-party-library

**Comment by Tonyce** [comment]
The lib must be linked , because I could call the func in swift file. 

it will be worked if I call the func in swift file, error again with `sum(1,2)` delete.

the differece is i use the static lib with vendored_library in ios/.podspec, other than vendored_frameworks.
