### ISSUE TITLE
microbenchmarks_ios_combineSemanticsInfoList_iteration regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51501]
Looking at the history, it's been gradually climbing while noisy, but it now seems like it's above baseline more often than not.

![combineSemanticsInfoList_iteration](https://user-images.githubusercontent.com/1435716/75386246-31ad4880-5896-11ea-964f-1b800913c2a3.png)

**Comment by goderbauer** [comment]
I think this benchmark is just noisy. Most of the recent runs today are below the threshold again. And the (not-noisy at all) Android benchmark hasn't changed at all over time. I'm just going to close this one.
