### ISSUE TITLE
[macOS] - macOS desktop deletes the work direction in a textfield

### ISSUE THREAD

**Issue by rodydavis** [flutter/flutter#51511]
Link to flutter engine possible issue: https://github.com/flutter/engine/blob/8af3b1b4da63d560ff54abdedbaa376044555bdc/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L182

Simple test: 

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField();
  }
}

```

Run flutter create to test on macOS and web.

It works correctly on iOS, web but not macOS.

Enter data into the text field an press the delete key.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/pull/49760 regressed this; backspace and delete are not the same, and shouldn't be treated as such.
