### ISSUE TITLE
Flutter run shows error after flutter upgrade.

### ISSUE THREAD

**Issue by saurabhpetkar** [flutter/flutter#51512]
Working on a project, I have just upgraded my flutter SDK using "flutter upgrade", but now some of the plugins are creating issues which I am not able to understand. its shared_preferences i guess.

after I run my project I get this error.
`Launching lib/main.dart on Redmi Note 7 Pro in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.analytics-library:crash:26.5.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0
      > Could not resolve com.android.tools.analytics-library:crash:26.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.5.0/crash-26.5.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.5.0/crash-26.5.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > androidx.databinding:databinding-compiler-common:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
      > Could not resolve com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build:builder-test-api:3.5.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:gradle-api:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0
      > Could not resolve com.android.tools.build:builder-test-api:3.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.5.0/builder-test-api-3.5.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.5.0/builder-test-api-3.5.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:sdklib:26.5.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.lint:lint-gradle-api:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:manifest-merger:26.5.0
      > Could not resolve com.android.tools:sdklib:26.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:common:26.5.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:manifest-merger:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.ddms:ddmlib:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.analytics-library:tracker:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0 > com.android.tools.analytics-library:shared:26.5.0
      > Could not resolve com.android.tools:common:26.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/common/26.5.0/common-26.5.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/common/26.5.0/common-26.5.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:annotations:26.5.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0 > androidx.databinding:databinding-compiler-common:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:builder-model:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.analytics-library:tracker:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0 > com.android.tools.analytics-library:shared:26.5.0
      > Could not resolve com.android.tools:annotations:26.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.5.0/annotations-26.5.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.5.0/annotations-26.5.0.pom'.
               > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin shared_preferences...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'shared_preferences'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.analytics-library:shared:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.analytics-library:tracker:26.4.0
      > Could not resolve com.android.tools.analytics-library:shared:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.4.0/shared-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.4.0/shared-26.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.analytics-library:crash:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
      > Could not resolve com.android.tools.analytics-library:crash:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.4.0/crash-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.4.0/crash-26.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.lint:lint-gradle-api:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
      > Could not resolve com.android.tools.lint:lint-gradle-api:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.4.0/lint-gradle-api-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.4.0/lint-gradle-api-26.4.0.pom'.
               > Connection reset
   > Could not resolve androidx.databinding:databinding-compiler-common:3.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
      > Could not resolve androidx.databinding:databinding-compiler-common:3.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.4.0/databinding-compiler-common-3.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.4.0/databinding-compiler-common-3.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
      > Could not resolve com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build:builder-test-api:3.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:gradle-api:3.4.0
      > Could not resolve com.android.tools.build:builder-test-api:3.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.4.0/builder-test-api-3.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.4.0/builder-test-api-3.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:sdklib:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.build:manifest-merger:26.4.0
      > Could not resolve com.android.tools:sdklib:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.4.0/sdklib-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.4.0/sdklib-26.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:sdk-common:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.build:manifest-merger:26.4.0
      > Could not resolve com.android.tools:sdk-common:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.4.0/sdk-common-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.4.0/sdk-common-26.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools:common:26.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.build:manifest-merger:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.ddms:ddmlib:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.analytics-library:tracker:26.4.0
      > Could not resolve com.android.tools:common:26.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/common/26.4.0/common-26.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/common/26.4.0/common-26.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build:apkzlib:3.4.0.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
      > Could not resolve com.android.tools.build:apkzlib:3.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.4.0/apkzlib-3.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.4.0/apkzlib-3.4.0.pom'.
               > Connection reset
   > Could not resolve com.android.tools.build:aapt2-proto:0.3.1.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:bundletool:0.7.2
      > Could not resolve com.android.tools.build:aapt2-proto:0.3.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.pom'.
               > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

Finished with error: The plugin shared_preferences could not be built due to the issue above.
`

these are my pubspec.yaml file plugins:
`cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.6+2
  rxdart: '^0.21.0'
  http: ^0.12.0+2`

my flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by jonahwilliams** [comment]
@saurabhpetkar this looks to be a network error downloading dependencies for the upgraded project. 


```
> Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.pom'.
> Connection reset
```

Are you able to download resources like the above in a browser? Do you have an internet connection, or are you behind a firewall that is blocking this? You'll need to resolve this before you're able to build. Though this isn't really a bug with flutter so I'm closing the issue
