### ISSUE TITLE
Allow PhysicalShapeLayer raster cache on non-Fuchsia platforms

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#51515]
This would improve the performance of `ListView` with material list items like `Card`. See https://github.com/flutter/flutter/issues/35592#issuecomment-586497856 for an example. Specifically, the shadows of the `PhysicalShapeLayer` could be costly to rasterize.

This issue would be a sub-issue of https://github.com/flutter/flutter/issues/23535

We might need to either
1. expose a flag to let developers specify whether to raster cache so we won't blow the memory by raster caching all `PhysicalShapeLayer`.
2. set a threshold similar to picture raster cache so we only start caching when the same layer gets rasterized multiple times.

Hence, we should not only write performance tests for the speed, but also for memory.

**Comment by liyuqian** [comment]
CC @dnfield @flar who have worked on related issues.

**Comment by dnfield** [comment]
I am not sure about this anymore, but doesn't Scenic do something special with physical shape layers? Is that compatbile with raster caching on our end?

**Comment by liyuqian** [comment]
Scenic now has a switch to not do something special with the `PhysicalShapeLayer`. Previously, it doesn't have such a switch and it's always doing something special.

In case that it's doing something special, Flutter always enables layer raster cache for `PhysicalShapeLayer` because scenic is going to create a separate surface for `PhysicalShapeLayer` anyway, so preserving such surface as the raster cache has no extra memory cost.

If scenic turns on the switch to not do something special, then the raster cache of normal Flutter would kick in (if we're to implement it).

**Comment by dnfield** [comment]
Ahh cool, thanks.  I don't think I know enough about the raster cache beyond that to have a meaningful opinion here - but why would we be concerned about the physical shape layer dominating it?

**Comment by dnfield** [comment]
Talked offline - it sounds like we should opt for the second option, which is basically how the picture raster cache works, and for which we don't think we have any memory issues currently.  My question about dominating was coming from the incorrect idea that we'd somehow be evicting picture layers by doing this.
