### ISSUE TITLE
How to buy subscription upgrade

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#51535]
In Android, subscription can be upgrade or downgrade using [setOldSku](https://developer.android.com/google/play/billing/billing_subscriptions.html#Allow-upgrade) method. Is that API expose in in_app_purchase plugin?

**Comment by rahulraj64** [comment]
Not yet. Duplicate of https://github.com/flutter/flutter/issues/32395

**Comment by VladyslavBondarenko** [comment]
Duplicate of https://github.com/flutter/flutter/issues/32395
