### ISSUE TITLE
flutter build apk error

### ISSUE THREAD

**Issue by jasteeman** [flutter/flutter#51536]
Hi.
I am implementing an application in flutter. But I have problems generating the flutter build apk. Although debug already generates the application. When generating the final app does not connect me to the internet. I already added the permissions on the androidManifest, but I'm still unsuccessful

**Comment by TahaTesser** [comment]
Hi @jasteeman 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jasteeman** [comment]
Hi @TahaTesser 

flutter build apk --verbose
[  +47 ms] executing: [D:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +94 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +12 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[   +1 ms] executing: [D:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +111 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +31 ms] v1.12.13+hotfix.7-0-g9f5ff2306
[  +12 ms] executing: [D:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +121 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +24 ms] origin/stable
[   +1 ms] executing: [D:\flutter\] git ls-remote --get-url origin
[ +104 ms] Exit code 0 from: git ls-remote --get-url origin
[  +27 ms] https://github.com/flutter/flutter.git
[ +186 ms] executing: [D:\flutter\] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +27 ms] stable
[ +175 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +56 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +62 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +247 ms] Found plugin barcode_scan at D:\flutter\.pub-cache\hosted\pub.dartlang.org\barcode_scan-2.0.1\
[ +197 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.1\
[  +74 ms] Found plugin ssh at D:\flutter\.pub-cache\hosted\pub.dartlang.org\ssh-0.0.5\
[ +185 ms] Found plugin barcode_scan at D:\flutter\.pub-cache\hosted\pub.dartlang.org\barcode_scan-2.0.1\
[  +39 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.1\
[  +73 ms] Found plugin ssh at D:\flutter\.pub-cache\hosted\pub.dartlang.org\ssh-0.0.5\
[ +142 ms] Generating
C:\xampp2\htdocs\nube4-appMovil\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +138 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[   +2 ms] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to
reduce the APK
           size.
[   +2 ms]     To generate an app bundle, run:
[   +1 ms]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[   +2 ms]         Learn more on: https://developer.android.com/guide/app-bundle
[   +1 ms]     To split the APKs per ABI, run:
[   +1 ms]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[  +91 ms]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +46 ms] Running Gradle task 'assembleRelease'...
[  +70 ms] gradle.properties already sets `android.enableR8`
[   +8 ms] Using gradle from C:\xampp2\htdocs\nube4-appMovil\android\gradlew.bat.
[ +107 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +265 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +98 ms] executing: [C:\xampp2\htdocs\nube4-appMovil\android\] C:\xampp2\htdocs\nube4-appMovil\android\gradlew.bat
-Pverbose=true -Ptarget=lib\main.dart -Ptrack-widget-creation=true -Pshrink=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[+3799 ms] > Task :app:compileFlutterBuildRelease UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildRelease UP-TO-DATE
[ +137 ms] > Task :app:preBuild UP-TO-DATE
[  +13 ms] > Task :app:extractProguardFiles UP-TO-DATE
[ +112 ms] > Task :app:preReleaseBuild UP-TO-DATE
[   +1 ms] > Task :barcode_scan:preBuild UP-TO-DATE
[   +1 ms] > Task :barcode_scan:preReleaseBuild UP-TO-DATE
[   +1 ms] > Task :barcode_scan:compileReleaseAidl NO-SOURCE
[   +1 ms] > Task :path_provider:preBuild UP-TO-DATE
[   +6 ms] > Task :path_provider:preReleaseBuild UP-TO-DATE
[  +78 ms] > Task :ssh:preBuild UP-TO-DATE
[   +1 ms] > Task :ssh:preReleaseBuild UP-TO-DATE
[   +4 ms] > Task :path_provider:compileReleaseAidl NO-SOURCE
[  +85 ms] > Task :ssh:compileReleaseAidl NO-SOURCE
[   +1 ms] > Task :app:compileReleaseAidl NO-SOURCE
[   +1 ms] > Task :barcode_scan:packageReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :path_provider:packageReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :ssh:packageReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :app:compileReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :app:checkReleaseManifest UP-TO-DATE
[   +1 ms] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeReleaseAssets
[   +1 ms] > Task :app:mergeReleaseShaders UP-TO-DATE
[  +84 ms] > Task :app:compileReleaseShaders UP-TO-DATE
[  +75 ms] > Task :app:generateReleaseAssets UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseShaders UP-TO-DATE
[   +1 ms] > Task :barcode_scan:compileReleaseShaders UP-TO-DATE
[   +1 ms] > Task :barcode_scan:generateReleaseAssets UP-TO-DATE
[ +117 ms] > Task :barcode_scan:packageReleaseAssets UP-TO-DATE
[   +4 ms] > Task :path_provider:mergeReleaseShaders UP-TO-DATE
[  +78 ms] > Task :path_provider:compileReleaseShaders UP-TO-DATE
[   +1 ms] > Task :path_provider:generateReleaseAssets UP-TO-DATE
[   +2 ms] > Task :path_provider:packageReleaseAssets UP-TO-DATE
[  +81 ms] > Task :ssh:mergeReleaseShaders UP-TO-DATE
[  +93 ms] > Task :ssh:compileReleaseShaders UP-TO-DATE
[   +1 ms] > Task :ssh:generateReleaseAssets UP-TO-DATE
[   +1 ms] > Task :ssh:packageReleaseAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeReleaseAssets
[   +1 ms] > Task :app:copyFlutterAssetsRelease
[  +99 ms] > Task :app:mainApkListPersistenceRelease UP-TO-DATE
[   +1 ms] > Task :app:generateReleaseResValues UP-TO-DATE
[   +2 ms] > Task :app:generateReleaseResources UP-TO-DATE
[  +98 ms] > Task :barcode_scan:generateReleaseResValues UP-TO-DATE
[ +166 ms] > Task :barcode_scan:compileReleaseRenderscript NO-SOURCE
[   +3 ms] > Task :barcode_scan:generateReleaseResources UP-TO-DATE
[   +1 ms] > Task :barcode_scan:packageReleaseResources UP-TO-DATE
[ +128 ms] > Task :path_provider:generateReleaseResValues UP-TO-DATE
[   +2 ms] > Task :path_provider:compileReleaseRenderscript NO-SOURCE
[ +157 ms] > Task :path_provider:generateReleaseResources UP-TO-DATE
[  +86 ms] > Task :path_provider:packageReleaseResources UP-TO-DATE
[ +111 ms] > Task :ssh:generateReleaseResValues UP-TO-DATE
[  +75 ms] > Task :ssh:compileReleaseRenderscript NO-SOURCE
[ +175 ms] > Task :ssh:generateReleaseResources UP-TO-DATE
[  +87 ms] > Task :ssh:packageReleaseResources UP-TO-DATE
[   +2 ms] > Task :app:mergeReleaseResources UP-TO-DATE
[ +135 ms] > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[ +127 ms] > Task :barcode_scan:checkReleaseManifest UP-TO-DATE
[ +123 ms] > Task :barcode_scan:processReleaseManifest UP-TO-DATE
[ +174 ms] > Task :path_provider:checkReleaseManifest UP-TO-DATE
[ +221 ms] > Task :path_provider:processReleaseManifest UP-TO-DATE
[  +68 ms] > Task :ssh:checkReleaseManifest UP-TO-DATE
[ +126 ms] > Task :ssh:processReleaseManifest UP-TO-DATE
[ +177 ms] > Task :app:processReleaseManifest UP-TO-DATE
[ +218 ms] > Task :barcode_scan:parseReleaseLibraryResources UP-TO-DATE
[  +88 ms] > Task :barcode_scan:generateReleaseRFile UP-TO-DATE
[  +77 ms] > Task :path_provider:parseReleaseLibraryResources UP-TO-DATE
[   +1 ms] > Task :path_provider:generateReleaseRFile UP-TO-DATE
[   +1 ms] > Task :ssh:parseReleaseLibraryResources UP-TO-DATE
[   +1 ms] > Task :ssh:generateReleaseRFile UP-TO-DATE
[ +168 ms] > Task :app:processReleaseResources UP-TO-DATE
[  +79 ms] > Task :barcode_scan:generateReleaseBuildConfig UP-TO-DATE
[   +3 ms] > Task :path_provider:generateReleaseBuildConfig UP-TO-DATE
[  +94 ms] > Task :barcode_scan:compileReleaseKotlin UP-TO-DATE
[   +1 ms] > Task :barcode_scan:javaPreCompileRelease UP-TO-DATE
[   +1 ms] > Task :barcode_scan:compileReleaseJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :barcode_scan:bundleLibCompileRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:javaPreCompileRelease UP-TO-DATE
[   +2 ms] > Task :path_provider:compileReleaseJavaWithJavac UP-TO-DATE
[ +168 ms] > Task :path_provider:bundleLibCompileRelease UP-TO-DATE
[   +1 ms] > Task :ssh:generateReleaseBuildConfig UP-TO-DATE
[   +1 ms] > Task :ssh:javaPreCompileRelease UP-TO-DATE
[   +1 ms] > Task :ssh:compileReleaseJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :ssh:bundleLibCompileRelease UP-TO-DATE
[   +1 ms] > Task :app:compileReleaseKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileRelease UP-TO-DATE
[   +1 ms] > Task :app:compileReleaseJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileReleaseSources UP-TO-DATE
[   +1 ms] > Task :app:prepareLintJar UP-TO-DATE
[   +1 ms] > Task :barcode_scan:prepareLintJarForPublish UP-TO-DATE
[   +1 ms] > Task :path_provider:prepareLintJarForPublish UP-TO-DATE
[  +83 ms] > Task :ssh:prepareLintJarForPublish UP-TO-DATE
[  +81 ms] > Task :app:lintVitalRelease
[   +1 ms] > Task :app:validateSigningRelease UP-TO-DATE
[  +74 ms] > Task :app:signingConfigWriterRelease UP-TO-DATE
[   +1 ms] > Task :app:mergeReleaseJniLibFolders UP-TO-DATE
[   +1 ms] > Task :barcode_scan:processReleaseJavaRes NO-SOURCE
[   +1 ms] > Task :barcode_scan:bundleLibResRelease UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseJniLibFolders UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseNativeLibs UP-TO-DATE
[   +1 ms] > Task :barcode_scan:stripReleaseDebugSymbols UP-TO-DATE
[   +1 ms] > Task :barcode_scan:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
[ +110 ms] > Task :path_provider:processReleaseJavaRes NO-SOURCE
[  +84 ms] > Task :path_provider:bundleLibResRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseJniLibFolders UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseNativeLibs UP-TO-DATE
[   +1 ms] > Task :path_provider:stripReleaseDebugSymbols UP-TO-DATE
[   +1 ms] > Task :path_provider:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
[   +1 ms] > Task :ssh:processReleaseJavaRes NO-SOURCE
[  +85 ms] > Task :ssh:bundleLibResRelease UP-TO-DATE
[   +1 ms] > Task :ssh:mergeReleaseJniLibFolders UP-TO-DATE
[   +2 ms] > Task :ssh:mergeReleaseNativeLibs UP-TO-DATE
[   +1 ms] > Task :ssh:stripReleaseDebugSymbols UP-TO-DATE
[   +1 ms] > Task :ssh:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
[   +1 ms] > Task :app:mergeReleaseNativeLibs UP-TO-DATE
[   +1 ms] > Task :app:stripReleaseDebugSymbols UP-TO-DATE
[   +1 ms] Compatible side by side NDK version was not found.
[   +1 ms] > Task :app:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :app:processReleaseJavaRes NO-SOURCE
[   +1 ms] > Task :app:mergeReleaseJavaResource UP-TO-DATE
[  +87 ms] > Task :barcode_scan:bundleLibRuntimeRelease UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :path_provider:bundleLibRuntimeRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :ssh:bundleLibRuntimeRelease UP-TO-DATE
[   +1 ms] > Task :ssh:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :ssh:mergeReleaseConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :app:transformClassesAndResourcesWithR8ForRelease UP-TO-DATE
[   +2 ms] > Task :app:transformClassesAndDexWithShrinkResForRelease UP-TO-DATE
[ +171 ms] > Task :app:packageRelease UP-TO-DATE
[   +1 ms] > Task :app:assembleRelease
[   +1 ms] > Task :barcode_scan:extractReleaseAnnotations UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseJavaResource UP-TO-DATE
[   +1 ms] > Task :barcode_scan:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[   +1 ms] > Task :barcode_scan:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
[   +1 ms] > Task :barcode_scan:bundleReleaseAar UP-TO-DATE
[   +1 ms] > Task :barcode_scan:compileReleaseSources UP-TO-DATE
[   +1 ms] > Task :path_provider:extractReleaseAnnotations UP-TO-DATE
[   +1 ms] > Task :barcode_scan:mergeReleaseResources UP-TO-DATE
[  +97 ms] > Task :barcode_scan:verifyReleaseResources UP-TO-DATE
[   +1 ms] > Task :barcode_scan:assembleRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseJavaResource UP-TO-DATE
[  +89 ms] > Task :path_provider:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
[   +1 ms] > Task :path_provider:bundleReleaseAar UP-TO-DATE
[        ] > Task :path_provider:compileReleaseSources UP-TO-DATE
[   +1 ms] > Task :ssh:extractReleaseAnnotations UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeReleaseResources UP-TO-DATE
[   +1 ms] > Task :path_provider:verifyReleaseResources UP-TO-DATE
[   +1 ms] > Task :path_provider:assembleRelease UP-TO-DATE
[   +1 ms] > Task :ssh:mergeReleaseJavaResource UP-TO-DATE
[   +2 ms] > Task :ssh:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[  +89 ms] > Task :ssh:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
[   +1 ms] > Task :ssh:bundleReleaseAar UP-TO-DATE
[        ] > Task :ssh:compileReleaseSources UP-TO-DATE
[   +1 ms] > Task :ssh:mergeReleaseResources UP-TO-DATE
[        ] > Task :ssh:verifyReleaseResources UP-TO-DATE
[        ] > Task :ssh:assembleRelease UP-TO-DATE
[        ] BUILD SUCCESSFUL in 7s
[        ] 119 actionable tasks: 4 executed, 115 up-to-date
[  +18 ms] Running Gradle task 'assembleRelease'... (completed in 9,7s)
[ +108 ms] calculateSha: LocalDirectory: 'C:\xampp2\htdocs\nube4-appMovil\build\app\outputs\apk'/app.apk
[  +78 ms] calculateSha: reading file took 36us
[ +469 ms] calculateSha: computing sha took 425us
[  +20 ms] √ Built build\app\outputs\apk\release\app-release.apk (17.0MB).
[  +87 ms] "flutter apk" took 12.226ms.


This using flutter build apk -v and my config in flutter using flutter doctor -v is:


[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [VersiÃ³n 10.0.18362.657], locale es-AR)
    • Flutter version 1.12.13+hotfix.7 at D:\flutter
    • Framework revision 9f5ff2306b (5 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\JAS\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\JAS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • LG M250 • LGM250BI99FI4HZ5TC • android-arm • Android 7.0 (API 24)

**Comment by jasteeman** [comment]
@TahaTesser 
If I install the application using debug it works perfectly. I have problems exporting to app flutter.

**Comment by jonahwilliams** [comment]
See https://stackoverflow.com/questions/55603979/why-flutter-application-cant-connect-to-internet-when-install-app-release-apk for more information.

You might have added the internet permission to the wrong manifest

**Comment by jasteeman** [comment]
Hi @jonahwilliams . 
I already verified that tutorial and I have added permissions for camera and internet in android/app/src/main/AndroidManifest.xml. The client will connect by ftps service using the plugin https://pub.dev/packages/ssh

**Comment by iapicca** [comment]
Hi @jasteeman 
I see that you already opened an [issue](https://github.com/shaqian/flutter_ssh/issues/32) for the 3rd party plugin [ssh](https://pub.dev/packages/ssh)
could you please provide the output of `flutter run --release --verbose`
while attempting to reproduce the error.
Thank you

**Comment by TahaTesser** [comment]
Hi @jasteeman 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
