### ISSUE TITLE
[packages] Should run CI with the Stable branch as well

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#51540]
At the moment https://github.com/flutter/packages only runs format, test, and analyze on the `master` branch, which can render the packages unusable in the `stable` branch.

Ideally, the tests should run on both branches.

See also: https://github.com/flutter/packages/pull/108

**Comment by stuartmorgan** [comment]
I recently did some alignment work between flutter/packages and flutter/plugins, and part of that was enabling tests on stable in addition to master, so this is resolved.
