### ISSUE TITLE
Documentation of Switch.activeColor ambiguous

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#51542]
UPDATE

When using `Switch.adaptive()` constructor, users can be led to believe by the documentation of the `activeColor` property that the behavior also applies to iOS, which it doesn't (see @TahaTesser 's responses below).

(original text):

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] Connected device (1 available)
```

Modifying `toggleableActiveColor` for the app does not affect the color on iOS when using `Switch.adaptive`. Setting `activeColor` for the individual widget works as expected.

**Comment by TahaTesser** [comment]
Hi @Lootwig 
`ThemeData.toggleableActiveColor` is material theme property hence won't apply to `CupertinoSwitch `

According to source 
```
  /// The color to use when this switch is on.
  ///
  /// Defaults to [CupertinoColors.systemGreen] when null and ignores
  /// the [CupertinoTheme] in accordance to native iOS behavior.
```

Thank you

**Comment by Lootwig** [comment]
Hi @TahaTesser 

Hmmm.. the Switch.adaptive constructor resides inside the regular `Switch` class and shares its doc:

```
  /// The color to use when this switch is on.
  ///
  /// Defaults to [ThemeData.toggleableActiveColor].
  final Color activeColor;
```

Since this is the doc the user sees when jumping into the source via the Switch.adaptive constructor, wouldn't it make sense to add some sort of clarification here?

**Comment by TahaTesser** [comment]
Hi @Lootwig 
`Switch` and `Switch.adaptive` is a material widget while `CupertinoSwitch` is a cupertino widget
Hence they both have different theming system. 

Material Widgets uses `ThemeData` and Cupertino Widget uses `CupertinoThemeData`

Links:
[https://api.flutter.dev/flutter/material/Switch/Switch.adaptive.html](https://api.flutter.dev/flutter/material/Switch/Switch.adaptive.html) 
[https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html](https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html)

**Comment by Lootwig** [comment]
If this was meant to be an answer to my question as to whether additional clarification might be helpful, then sorry but I don't get it. Could you be more obvious if you agree or disagree and why? Are you implying that what you wrote in your last response is self-explanatory for a user of the adaptive switch?

**Comment by TahaTesser** [comment]
Hi @Lootwig 
I don't disagree about clarification but i am just responding to the main issue `ThemeData.toggleableActiveColor not applied to CupertinoSwitch`

**Comment by Lootwig** [comment]
@TahaTesser I've updated the issue to better reflect what led me to create it in the first place.

**Comment by DanielEdrisian** [comment]
Closing since the adaptive constructor indicates `activeColor` is ignored.
