### ISSUE TITLE
Want flutter build support multiple .so file

### ISSUE THREAD

**Issue by nimengbo** [flutter/flutter#51548]
## Use case

For example , In my application , I have three plugins a,b,c,   as three SDK 

## Proposal

 I wanna build a.so, b.so, c.so ,  Compile separately like android aar , And we can load any .so file as our needs

**Comment by jonahwilliams** [comment]
This is not something that is supported by gen_snapshot today

**Comment by nimengbo** [comment]
> This is not something that is supported by gen_snapshot today

Will plan for this feature ?

**Comment by nimengbo** [comment]
> This is not something

How to use it? by paramters for flutter build command ?

**Comment by Hixie** [comment]
Can you elaborate on your use case? What exactly are you trying to do, how would you expect this to work, etc?
