### ISSUE TITLE
Make FakePlatformGoogleMap public

### ISSUE THREAD

**Issue by shouichi** [flutter/flutter#51546]
## Use case

When we want to unit test widgets using google maps, we need fake maps. There is `FakePlatformGoogleMap` class (and related classes) in the google_maps_flutter's test package but it is not exported.

## Proposal

Adding something like `google_maps_flutter_testing` package and providing `FakePlatformGoogleMap` and related classes.

**Comment by stuartmorgan** [comment]
Closing as out of scope; what behavior a test fake needs is test-specific, so this would need to be very configurable, which would create a significant maintenance burden.

In general, tests should maintain their own fakes/makes.
