### ISSUE TITLE
App crashes on iOS while processing large size images

### ISSUE THREAD

**Issue by piyushrathodIn** [flutter/flutter#51552]
I am creating a PDF file with captured images but processing those images and converting them to PDF (using pdf 1.5.0 plugin) leads to app crash. Is there any efficient approach to create PDF file via images without such issues?

**Comment by TahaTesser** [comment]
Hi @piyushrathodIn 
I'm not sure if what you are describing is an issue with Flutter itself or if you are asking for assistance within your code.
For issue related to the 3rd party plugin [pdf](https://pub.dev/packages/pdf) you may want to open an issue in the dedicated [github](https://github.com/DavBfr/dart_pdf/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
