### ISSUE TITLE
Add isCancelled to Timer class

### ISSUE THREAD

**Issue by fryette** [flutter/flutter#51559]
I would like to ask you to add `isCancelled` property to `Timer` class. 
For now if timer cancelled callback still alive and you have no chance to detect it. 

Code:

```
void someOneCanExecuteThisMethod(){
      //notify that we start loading
      stateNotifier.add(Loaded(model));
    _timer?.cancel();
    _timer = Timer(const Duration(milliseconds: 200), () async {
      final timerRef = _timer;
      //here we have looong request
      final model = await _loadModel();
      //here need to check, is timer was cancelled
      if (!timerRef.isCancelled) {
        stateNotifier.add(Loaded(model));
      }
    });
}
```

workaround:
```
class AdvancedTimer {
  AdvancedTimer(Duration duration, void Function() callback) {
    _timer = Timer(duration, callback);
  }

  Timer _timer;
  bool isCancelled = false;

  void cancel() {
    isCancelled = true;
    _timer.cancel();
  }
}
```

but it would be nice to have this feature in flutter SDK, because other languages also contain possibility to prevent execution of method(cancel Task, throw cancellation error during call and other)

**Comment by VladyslavBondarenko** [comment]
Hi @fryette 
Since Timer class is from the dart:async library, consider please open the issue in the [dart-lang github](https://github.com/dart-lang/sdk/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you
