### ISSUE TITLE
Private const visible in docs.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5155]
[`_emptyWidgetList`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L705) is visible in the [docs](https://docs.flutter.io/flutter/widgets/BlockBody/BlockBody.html).

Since we should have some default behavior when a `Widget` takes a `List<Widget>` as a `children` parameter, we should probably either use `const <Widget>[]` or make this `const` public.

**Comment by goderbauer** [comment]
Seems like this problem is fixed. Closing the issue.
