### ISSUE TITLE
New regression in flutter_gallery_ios32__transition_perf_90th_percentile_frame_build_time_millis and flutter_gallery_ios32__transition_perf_90th_percentile_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51574]
Very clear regression at https://github.com/flutter/flutter/pull/51418, although I'm not sure why. This looked like an improvement.
![Screenshot 2020-02-27 at 09 09 13](https://user-images.githubusercontent.com/1435716/75467680-e00dc800-5940-11ea-8b82-2200644cbc2c.png)

**Comment by kf6gpe** [comment]
flutter_gallery_ios32__transition_perf_99th_percentile_frame_rasterizer_time_millis also looks affected by this.

**Comment by jonahwilliams** [comment]
This change was already reverted: https://github.com/flutter/flutter/pull/51489

Its likely a device specific issue

**Comment by goderbauer** [comment]
Adding "team: infra" since this may look like a problem with the bot running the test (mac11).

**Comment by keyonghan** [comment]
There is a 'No Sim Card Installed' window poppoed up in mac 11's phone. Have closed that and wait for further monitoring.

**Comment by goderbauer** [comment]
@ferhatb If dismissing that dialog fixes the performance regression you may want to consider reverting the revert in #51489 again.

**Comment by jonahwilliams** [comment]
Looks like the benchmarks have gone back down, but aren't green yet. Did we re-baseline after #51489?

**Comment by flar** [comment]
90% rasterizer time looks like the same baseline that was working for it before https://github.com/flutter/flutter/pull/45130
The rest appear green.

**Comment by flar** [comment]
My vote is close this issue...

**Comment by goderbauer** [comment]
Closing since the regression this bug is talking about has been resolved.
