### ISSUE TITLE
Regression in 90th_percentile_frame_rasterizer_time_millis.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51576]
I missed this --- looks like since this revert: 16.6 ms90th_percentile_frame_rasterizer_time_millis
. Are we going to re-land something?

**Comment by tvolkert** [comment]
There are many different benchmarks with the ["90th_percentile_frame_rasterizer_time_millis" benchmark score key](https://github.com/flutter/flutter/blob/1d3fcfd6ca7e83c6c7d134fc99deb015839b0389/dev/devicelab/lib/tasks/perf_tests.dart#L263) - it's not clear from this bug which one regressed.

However, I've re-opened https://github.com/flutter/flutter/issues/49300, which has two particularly bad regressions in this score key (for the "flutter_gallery_ios*__transition_perf" benchmarks)
