### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type '() => void'

### ISSUE THREAD

**Issue by Pedroadlcruz** [flutter/flutter#51588]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
https://stackoverflow.com/questions/57902284/type-futuredynamic-is-not-a-subtype-of-type-void
