### ISSUE TITLE
Update flutter_test dependencies

### ISSUE THREAD

**Issue by VladyslavBondarenko** [flutter/flutter#51582]
**Proposal**

[Flutter_test](https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml) depends on `xml: 3.5.0` (current master channel).
An android-embedding-v2 project is hanging on build with using `xml: 3.5.0`, when adding this dependency to `pubspec.yaml`.

The last version `xml: 3.7.0` is working with both android-embedding-v2 and v1.
But I can use it only without `flutter_test`, which requires `xml:3.5.0`.

(If xml depencency will be updated to 3.7.0, petitparser needs to be updated as well to the last 3.0.0)

Correct me please if this is a bad idea, because I don't know how can this influence to the flutter_test itself and didn't find why it wasn't done before

Related issue https://github.com/flutter/flutter/issues/51549

**Comment by topilski** [comment]
Morning, is it so hard, to change numbers in deps? now xml 4.1.0

**Comment by VladyslavBondarenko** [comment]
Dev channel doesn't depend on `xml`. Closing as fixed
https://github.com/flutter/flutter/commit/efdce3cf728c96d47e216120512595e8d9a3022b#diff-6db519d06b539bb165a44ad589217e9eL49
if you disagree please write in the comments and I will reopen it
