### ISSUE TITLE
Travis sometimes doesn't run plugin_tools tests

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#51585]
Not sure why, but Travis signed off on flutter/plugin_tools#88 without actually running the tests. 

I fixed the issues in https://github.com/flutter/plugin_tools/pull/92, which also had the same issue (fixed by force pushing the last commit).

I think it might be a race condition when pushing several commits in quick succession while the tests are running.

We might want to consider switching to Cirrus.

**Comment by stuartmorgan** [comment]
Closing as obsolete since we're no longer on Travis.
