### ISSUE TITLE
Give more control to raster cache

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#51592]
Currently, the developer doesn't have much control over Flutter's raster cache mechanism (picture raster cache or layer raster cache).

Having more control could improve the performance: https://github.com/flutter/flutter/issues/32662, https://github.com/flutter/flutter/issues/51515 .

More importantly, not having the control could bring correctness or quality issues as revealed by https://github.com/flutter/flutter/issues/49928.

My preliminary thought is to put more control into `CustomPaint` and `RepaintBoundary` widget, so the developer can choose to enforce raster cache or disable raster cache. Semantically, that means to explicitly state whether a widget subtree needs to (1) first draw to an off-screen layer, and then composite back to the screen, or (2) directly draw to the screen without any grouping. Those two options could mean different results as it's similar to how `Opacity` widget has a different semantics than just giving a transparent paint to every widget directly.

In some cases, grouping/raster-cache/saveLayer or not doesn't change the semantics. Only in those cases, should Flutter freely choose raster cache or not based on its performance heuristics.

**Comment by liyuqian** [comment]
CC @flar @jason-simmons @chinmaygarde @cbracken @Hixie

**Comment by chinmaygarde** [comment]
While fine tuning of the raster cache can lead to performance improvements, the misuse of the raster cache can lead to runaway device memory use. The cases you highlighted ought to be able to detected and handled by the engine (with more information from the framework perhaps) without needing the developer to have to configure the cache. I am also not sure if we will be able to provide enough information to the deveoper to make optimum caching decisions. And, if we can, why can't we affect raster cache behavior directly in the engine?

I am not completely against this idea, just that the potential downsides are quite severe.

**Comment by liyuqian** [comment]
Yes, I agree that memory is big risk here and we should still try to optimize performance automatically without too much developer interventions.

The control here then seems to be more for the correctness issue. Group the draw into an offscreen or not could mean different rendering results, and that's what we shall enable developers to choose.

**Comment by fzyzcjy** [comment]
Hi, I wonder whether the `toPictureSync` will solve this problem?

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
