### ISSUE TITLE
Flutter image.network (get data from json) work in web but not in mobile 

### ISSUE THREAD

**Issue by BasharAlayan** [flutter/flutter#51603]
hi,

when i use image.network (get data from json) work in web but not in mobile
the error is:

════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.
When the exception was thrown, this was the stack
#0      _futurize  (dart:ui/painting.dart:4397:5)
#1      instantiateImageCodec  (dart:ui/painting.dart:1718:10)
#2      PaintingBinding.instantiateImageCodec 
package:flutter/…/painting/binding.dart:88
#3      NetworkImage._loadAsync 
package:flutter/…/painting/_network_image_io.dart:104
<asynchronous suspension>
...
Image provider: NetworkImage("https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg", scale: 1.0)
Image key: NetworkImage("https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════

**Comment by jonahwilliams** [comment]
That is an SVG, not an image. FTY @hterkelsen , maybe this works by accident on the web

**Comment by BasharAlayan** [comment]
ok, it's working now
Thanks
