### ISSUE TITLE
A problem occurred configuring root project 'android'.

### ISSUE THREAD

**Issue by shunyue1320** [flutter/flutter#51604]
My mistake：
```
* Error running Gradle:
ProcessException: Process "C:\Users\shunyue\mydemo\flutter_app\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
```

My solution：
modification android\build.gradle
```
buildscript {
    repositories {
        google()
        mavenCentral()   //add
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()   //add
        jcenter()
    }
}
```

**Comment by jonahwilliams** [comment]
This is a problem that could be caused by lacking access to the google or jcenter mirrors. It sounds like you solved the issue though?

**Comment by shunyue1320** [comment]
> This is a problem that could be caused by lacking access to the google or jcenter mirrors. It sounds like you solved the issue though?

yes,  That's how I solved it

**Comment by jonahwilliams** [comment]
Coolio. In general there isn't really much we can do about this. If the issue is solved I'm going to close the bug.

**Comment by Howarduan** [comment]
I have met the same problem, and my gradle script is:
repositories {
        google()
        jcenter()
        mavenLocal()
    }
and I change it to:
repositories {
        google()
        jcenter()
        mavenLocal()
        mavenCentral()
    }
but the errors still exist.
唉

**Comment by Adamsay93a** [comment]
Hello Shunyue1230, please how did you modify your android/build.gradle as you stated up there. I'm new to coding and even flutter, I'm experiencing the same problem but I don't know how to go about your solution.

**Comment by shunyue1320** [comment]
@Adamsay93a  answer is above ↑
 Between `google()` and   `jcenter()`  add to  `mavenCentral()`

I don’t know if it’s useful now, and it’s been a long time！

**Comment by shunyue1320** [comment]
@Adamsay93a 
If it is because `gradle-x.x-all.zip` download failed
Go to the [gradle-x.x-all.zip](https://services.gradle.org/distributions/) to download
Copy to your folder after downloading: `C:\Users\yourUserName\.gradle\wrapper\dists\gradle-x.x-all\xxxxxx\` in window

Download the version here：
![image](https://user-images.githubusercontent.com/47295879/100295067-96333a80-2fc3-11eb-9f68-42db23665811.png)

**Comment by TheGuysWhoCode** [comment]
> Hello Shunyue1230, please how did you modify your android/build.gradle as you stated up there. I'm new to coding and even flutter, I'm experiencing the same problem but I don't know how to go about your solution.

For me I solved that issue by downloading gradle and extracting it in the root folder of android studio. and add it to the system variables path and go in android studio > settings > Build, Exception, Deployment. and point it to the folder where you extracted you gradle.  Download gradle from here https://services.gradle.org/distributions/
