### ISSUE TITLE
Cannot flutter run on iPad Mini, armv7f is unsupported

### ISSUE THREAD

**Issue by izzabellerina** [flutter/flutter#51619]
Hello Everyone ,I'm a new flutter .I have some problem that my device are low or something and then I've just changed the architecture from standard to armv7f . when I've run my project with Xcode, the program threw error :  

```
error: unknown target triple 'unknown-apple-ios9.3.0', please use -triple or -arch
Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

```

Does anyone know How to fix it . Thank you in advance.
My device is iPad mini . ios9.3.6

**Comment by iapicca** [comment]
Hi @izzabellerina 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
Thank you

**Comment by izzabellerina** [comment]
> Hi @izzabellerina
> can you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> Thank you
`
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Target 'Pods-Runner' of project 'Pods' was rejected as an implicit dependency for 'Pods_Runner.framework' because its architectures 'armv7 arm64' didn't contain all required architectures 'arm64 armv7f'
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    warning: no rule to process file '/Users/armotesomboonkaew/Downloads/flutter_blue-master 2/example/ios/File.swift' of type sourcecode.swift for architecture armv7f
    error: unknown target triple 'unknown-apple-ios9.3.0', please use -triple or -arch
    Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Could not build the precompiled application for the device.

Error launching application on @mote500iPadMini1stGen.`

**Comment by izzabellerina** [comment]
@iapicca Sorry to respond you slow and late.
this is my flutter doctor -v
`[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-TH)
    • Flutter version 1.14.6 at /Users/armotesomboonkaew/flutter/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/armotesomboonkaew/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.4, Build version 11N123k
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • @mote500iPadMini1stGen • 7e260d8b3956e35fe20400b14ef03a2ab4376008 • ios • iOS 9.3.6

• No issues found!
`

**Comment by izzabellerina** [comment]
@iapicca 
this is my flutter run -verbose
[  +45 ms] executing: [/Users/armotesomboonkaew/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/armotesomboonkaew/flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[  +16 ms] executing: [/Users/armotesomboonkaew/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/armotesomboonkaew/flutter/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +83 ms] executing: [/Users/armotesomboonkaew/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +11 ms] executing: sw_vers -productName
[  +29 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +24 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +29 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] executing: /Users/armotesomboonkaew/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/armotesomboonkaew/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +31 ms] executing: /Users/armotesomboonkaew/flutter/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +521 ms] executing: /usr/bin/xcode-select --print-path
[  +18 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode-beta.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +311 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.4
           Build version 11N123k
[   +6 ms] /usr/bin/xcrun simctl list --json devices
[ +244 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] "flutter run" took 1,433ms.
Target file "lib/main.dart" not found.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:739:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:320:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:619:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/armotesomboonkaew/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by izzabellerina** [comment]
@iapicca 
and finally this is run build whole error.
Running Xcode build...
Xcode build done.                                           10.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Target 'Pods-Runner' of project 'Pods' was rejected as an implicit dependency for 'Pods_Runner.framework' because its architectures 'armv7 arm64' didn't contain all required architectures 'arm64 armv7f'
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    warning: no rule to process file '/Users/armotesomboonkaew/Downloads/flutter_blue-master 2/example/ios/File.swift' of type sourcecode.swift for architecture armv7f
    error: unknown target triple 'unknown-apple-ios9.3.0', please use -triple or -arch
    Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Could not build the precompiled application for the device.

Error launching application on @mote500iPadMini1stGen.

**Comment by izzabellerina** [comment]
@iapicca and my whole expanded dependencies for letting you know. Maybe some of dependencies are  problem instead.

`dependencies:
  flutter:
    sdk: flutter
  hex: ^0.1.2
  sqflite: ^1.2.0
  path_provider: ^1.6.0
  intl: ^0.16.0
  shared_preferences: ^0.5.6
  grouped_buttons: ^1.0.4
  flutter_time_picker_spinner: ^1.0.6
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
  permission: ^0.1.5
  flutter_svg: ^0.15.0
  easy_localization: ^1.4.0
  screenshot: ^0.1.1
  mp_chart: ^0.1.2
  flutter_share: ^1.0.2+1
  time_formatter: ^1.0.0+5
  flutter_launcher_icons: ^0.7.4
  fragment: ^0.3.1
  share_it: ^0.5.1+3
  mqtt_client: ^5.5.1
  barcode_scan: ^2.0.1
  bot_toast: ^2.3.0
  connectivity: ^0.4.8+2`

**Comment by izzabellerina** [comment]
@iapicca and the lastly finally error when I run project from XCODE from Runner.xcworkspace file . and This is I got a problem


error: unknown target triple 'unknown-apple-ios9.3.0', please use -triple or -arch
Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by jmagman** [comment]
iPad Mini architecture is armv7f.  Huh.

**Comment by jmagman** [comment]
What do you mean by "I've just changed the architecture from standard to armv7f"?

**Comment by jmagman** [comment]
Possibly fixed by https://github.com/flutter/flutter/pull/52021#issuecomment-595368764 in v1.15.18.  Can you try on [master or dev](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) channels?

**Comment by izzabellerina** [comment]
> What do you mean by "I've just changed the architecture from standard to armv7f"?

normally , the architecture  is ARCHS_STANDARD  and arm64, and then I cannot run my project to IPad mini. The Xcode threw the error that can compile with  armv7f  and then I changed . After that they threw a new error is Flutter:IOS error: unknown target triple 'unknown-apple-ios9.3.0' 


Thank you very much  for your reply.

**Comment by jmagman** [comment]
Gotcha.   Can you see if it's fixed on [master or dev](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
