### ISSUE TITLE
I want to implement swipe or drag and drop to move the tiles in number puzzle

### ISSUE THREAD

**Issue by shainshayusuf** [flutter/flutter#51612]
![puzzle](https://user-images.githubusercontent.com/55499261/75511171-52e77380-5a13-11ea-8531-e659c48dcdb9.png)

main.dart
import "package:flutter/material.dart";
import 'dart:math';
import 'package:number_puzzle/shake_view.dart';

void main() {
  runApp(MaterialApp(
    home: NumberPuzzle(),
    debugShowCheckedModeBanner: false,
  ));
}
class NumberPuzzle extends StatefulWidget {
  @override
  NumberPuzzleState createState() => NumberPuzzleState();
}
class NumberPuzzleState extends State<NumberPuzzle> with SingleTickerProviderStateMixin{

  List<int> numbers = [1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15, 0];
  List<int> rand = [];
  int max = 16;
  int counter=0;
  ShakeController _shakeController;

  @override
  void initState() {
    _shakeController = ShakeController(vsync: this);
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    randomList();

    return Scaffold(
      body: Stack(
        children: <Widget>[
          Center(
            child: Container(
              width: 510,
              height: 550,

              child: GridView.count(
                crossAxisCount: 4,
                crossAxisSpacing: 5,
                mainAxisSpacing: 5,
                children: <Widget>[
                  for (var i = 0; i < rand.length; i++)
                    tiles(rand[i])

                ],
              ),
            ),
          ),
          Align(
            alignment: Alignment(0.0, 0.7),
            child: Container(
              width: 250,
              height: 100,
              child: RaisedButton(
                color: Colors.indigo,
                onPressed: () {
                  rand.clear();

                  setState(() {
                    randomList();
                    counter=0;
                  });
                },
                child: Text(
                  "Click to Shuffle!",
                  style: TextStyle(fontSize: 30),
                ),
              ),
            ),
          ),
          Align(
            alignment: Alignment(0.0,0.8),
            child: Container(
              child: Text('$counter Moves ${reamainingTiles()} Tiles Matched',style: TextStyle(fontSize: 30),),
            ),
          ),

        ],
      ),
    );
  }
  Widget tiles(int i) {
    bool isZero = i == 0;
    return GestureDetector(
      onTap: (){
        movePosition(i);
        _shakeController.shake();
      },

      child: ShakeView(
       controller: _shakeController,
        child: Container(

          width: 125,
          height: 100,
          margin: EdgeInsets.all(5.0),
          decoration: BoxDecoration(

            color: isZero ? Colors.white : Color(0xff000080),
            border: Border.all(width: 2.0),
          ),
          child: Center(
            child: Text(
              '$i',
              style: TextStyle(color: Colors.white, fontSize: 25),
            ),
          ),
        ),

      ),
    );

  }
  void randomList() {          //To Create a Random List
    Random rnd = new Random();
    int num = rnd.nextInt(max);
    if (rand.length == numbers.length) {
      return;
    }
    if (rand.contains(num)) {
      randomList();
    } else {
      rand.add(num);
    }
    if (rand.length < numbers.length) {
      randomList();
    }

  }
  void movePosition(int i) {    //To  move the Clicked Position
    int clickPosition=rand.indexOf(i);
    int zeroPosition=rand.indexOf(0);
    if(((clickPosition+4 )== zeroPosition) ||((clickPosition-4 )== zeroPosition)||((clickPosition+1 )== zeroPosition)||((clickPosition-1 )== zeroPosition) )
    {

      setState(() {
        rand[clickPosition]=0;
        rand[zeroPosition]=i;
        counter++;
      });
      print("Moved $i ");
    }
    if(check())
    {
      //Text("You Won",style: TextStyle(fontSize: 40,color: Colors.black),);
      won();
      showDialog(context: context,
          builder: (context)=>won(),barrierDismissible: false
      );
    }
  }
  bool check() {
    int temp=0;
    for(var i=0;i<numbers.length;i++)
    {
      if(rand[i] == numbers[i])
        temp++;
    }
    bool checkWon=temp == numbers.length?true:false;
    return checkWon;

  }

  Widget won() {
    return AlertDialog(
      title: Text("You Won"),
      content: Text('Play Again?'),
      actions: <Widget>[
        FlatButton(
          child:Text('Yes'),
          onPressed: ()
          {
            rand.clear();
            setState(() {
              randomList();
            });
            Navigator.of(context).pop();
          },
        ),
        FlatButton(
          child: Text("No"),
          onPressed: () {
            Navigator.of(context).pop();
          },
        )
      ],

    );
  }

 int checkDraggable(int i) {

   int clickPosition=rand.indexOf(i);
   int zeroPosition=rand.indexOf(0);
   if(((clickPosition+4 )== zeroPosition) ||((clickPosition-4 )== zeroPosition)||((clickPosition+1 )== zeroPosition)||((clickPosition-1 )== zeroPosition) )
   {
     return 1;
   }
   else{
     return 0;
   }
   }

  @override
  void dispose() {
    _shakeController.dispose();
    super.dispose();
  }

  int reamainingTiles()
  {
    var num=0;
    for(var i=0;i<rand.length;i++)
      {
        if(rand[i] == numbers[i])
          {
            num++;
          }
      }
    return num;
  }

 }

shake_view.dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart';

class ShakeView extends StatelessWidget {
  final Widget child;
  final ShakeController controller;
  final Animation _anim;

  ShakeView({@required this.child, @required this.controller})
      : _anim = Tween<double>(begin: 50, end: 120).animate(controller);

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation: controller,
        child: child,
        builder: (context, child) => Transform(
              child: child,
              transform: Matrix4.translation(_shake(_anim.value)),
            ));
  }

  Vector3 _shake(double progress) {
    double offset = sin(progress * pi * 10.0);
    return Vector3(offset * 15,0.0 , 0.0);
  }
}

class ShakeController extends AnimationController {
  ShakeController(
      {@required TickerProvider vsync,
      Duration duration = const Duration(milliseconds: 200)})
      : super(vsync: vsync, duration: duration);

  shake() async {
    if (status == AnimationStatus.completed) {
      await this.reverse();
    } else {
      await this.forward();
    }
  }
}

I implemented onTap() function using Gesture Detector to move the tiles to uncolored position and Now I want implement swipe or drag and drop to implement in the my number puzzle game

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
