### ISSUE TITLE
flutter create should use a recent minimum version

### ISSUE THREAD

**Issue by vogella** [flutter/flutter#51622]
if I create a new flutter program with flutter create I expect a relative recent version as minimum. Currently I get:

environment:
sdk: ">=2.1.0 <3.0.0"

I suggest to upgrade to at least 2.7 to use interesting features.

environment:
sdk: ">=2.7.0 <3.0.0"

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/32150#issuecomment-489726511
> For apps IMHO it makes more sense not to have any constraints here, because the developer's choice of SDK comes before the developer uses the `pubspec.yaml` for anything.

Closing.
