### ISSUE TITLE
Look into making _BottomSheetSuspendedCurve public

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#51627]
This curve is used with bottom sheets to allow linear finger dragging and non-linear enter/exit animations.

- Look into making this public
- Adding useful examples
- Find instances where it would be useful, not just for bottom sheets, and retrofit existing code

The PR that adds this curve: #51122

**Comment by VladyslavBondarenko** [comment]
Hi @guidezpl 
should the issue be closed since PR is merged?

**Comment by jamesblasco** [comment]
I am using this also inside a package for a Cupertino Bottom Sheet. 
https://github.com/jamesblasco/modal_bottom_sheet


It would be nice to have it public

**Comment by bdlukaa** [comment]
This would be very helpful!

**Comment by guidezpl** [comment]
Un-assigning since I don't have the time right now. However, the first two tasks should be a relatively straightforward. Feel free to add me as reviewer.
