### ISSUE TITLE
"Log for Attempt #x" takes me to irrelevant log page

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#51639]
## Steps to Reproduce

I was looking at the devicelab `cull_opacity_perf__timeline_summary` test failure on Android today:

![cull_opacity_test_fail](https://user-images.githubusercontent.com/211513/75566998-989d3f80-5a05-11ea-9a06-21573fa879c4.png)

When I click on either `Log for Attempt #1` or `Log for Attempt #2` it takes me to [this logs page](https://pantheon.corp.google.com/logs/viewer?project=flutter-dashboard&resource=global&minLogLevel=0&expandAll=false&interval=NO_LIMIT&dateRangeUnbound=backwardInTime&timestamp=2020-02-28T16:38:58.244000000Z&customFacets=&limitCustomFacetWidth=true). Unfortunately, nothing in the logs seems to have to do with the test in question (notice that the logs are from some iOS test, while I'm looking at an Android test):

![cull_opacity_log](https://user-images.githubusercontent.com/211513/75567222-fe89c700-5a05-11ea-890d-267f6262b691.png)

/cc @CaseyHillers @godofredoc

**Comment by digiter** [comment]
Triage: we'd remove the stack driver logging.

**Comment by godofredoc** [comment]
Obsolete: with luci those logs redirect to the individual task.
