### ISSUE TITLE
error no known class method after xcode update

### ISSUE THREAD

**Issue by mobilemindtec** [flutter/flutter#51633]
Hi,

After updating xcode to version 11.3.1 (11C504) I am having problems using FBSDKCoreKit. The detail is that if executed by Xcode it works perfectly, but when executed by InteliJ or using `flutter fun` the compilation error is displayed.

```
Xcode build done.       
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Volumes/Data/sources/repositories/meuestylo/app/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppE
    vents/Internal/RestrictiveDataFilter/FBSDKAddressFilterManager.m:59:60: error: no known class method
    for selector 'JSONStringForObject:error:invalidObjectHandler:'
        NSString *addressParamsJSONString = [FBSDKBasicUtility JSONStringForObject:addressParams
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Volumes/Data/sources/repositories/meuestylo/app/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppE
    vents/Internal/RestrictiveDataFilter/FBSDKAddressFilterManager.m:62:24: error: no known class method
    for selector 'dictionary:setObject:forKey:'
        [FBSDKBasicUtility dictionary:params setObject:addressParamsJSONString
        forKey:@"_onDeviceParams"];
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
```

Before Xcode update everything worked perfectly. Flutter doctor summary:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale pt-BR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Thanks!

**Comment by iapicca** [comment]
Hi @mobilemindtec 
can you please provide your full `flutter run --verbose`?

If you believe the issue depends from  [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
you may want to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)
Thank you

**Comment by mobilemindtec** [comment]
Hi @iapicca,

The error also happens on the console, so I believe it is not just related to InteliJ.

Follows the output of the command `flutter run --verbose`

https://raw.githubusercontent.com/mobilemindtec/temp-files/master/flutter-facebook-error-compile-28022020.log

Thank you

**Comment by iapicca** [comment]
Hi again @mobilemindtec 
thanks for the logs 
and for clarifying that is not intellij related

**Comment by mobilemindtec** [comment]
Hi, you can use this project to test if you want.

https://github.com/mobilemindtec/flutter-facebook

**Comment by jmagman** [comment]
I checked out your project and `flutter run` your example project with no issues.  Can you `flutter clean` to clean your Xcode workspace and try again?

**Comment by jmagman** [comment]
If this is happening on an Xcode update, I would file an issue against https://github.com/facebook/facebook-ios-sdk

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by mobilemindtec** [comment]
Hi,

After run `flutter clean` the error is gone! Thanks
