### ISSUE TITLE
Camera Plugin doesn't dispose the controller by .dispose()

### ISSUE THREAD

**Issue by onadoroz** [flutter/flutter#51630]
I trying manually dispose camera controller, but it seems it's stills initialized. Can you somebody comment on this?

 camera: 0.5.7+4

```
  Future controllerDispose(context) async {
    try {
      await cameraScanController.dispose().whenComplete(() {printLog ("Dispose done. controllerStatus is: ${cameraScanController.value.isInitialized} ");});
    } catch (e) {
      printLog("Dispose conttroller Error: $e");
    }
  }
```

>>>
[codeScanCam_Screen.dart] Dispose done. controllerStatus is: true

**Comment by VladyslavBondarenko** [comment]
<details>
 <summary>complete code sample</summary>

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(MaterialApp(home: CameraApp()));
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras[0], ResolutionPreset.medium);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return Column(
      children: <Widget>[
        AspectRatio(
          aspectRatio: 1 / 1,
          child: CameraPreview(controller),
        ),
        MaterialButton(
          child: Text(
            'dispose button',
            style: TextStyle(color: Colors.white),
          ),
          onPressed: () async {
            try {
              await controller.dispose().whenComplete(() {
                print(
                    "Dispose done. controllerStatus is: ${controller.value.isInitialized}");
              });
            } catch (e) {
              print("Dispose conttroller Error: $e");
            }
          },
        )
      ],
    );
  }
}
```

</details>

**Comment by Sempakonka** [comment]
Hi @onadoroz 

It is correct that in the current version of the plugin when you call the `dispose` method and call `Controller.value.isInitialized` it returns true. 

I think by changing the plugin slightly there could be a fix for this.
I could make a PR and add `value = CameraValue.uninitialized();`   to the `dispose` method.
It would look like this:

```
Future<void> dispose() async {
 if (_isDisposed) {
   return;
 }

 _isDisposed = true;
 value = CameraValue.uninitialized();
 super.dispose();
 if (_creatingCompleter != null) {
   await _creatingCompleter.future;
   await _channel.invokeMethod<void>(
     'dispose',
     <String, dynamic>{'textureId': _textureId},
   );
   await _eventSubscription?.cancel();
 }
}

```
But to make sure this is a correct approach maybe @bparrishMines could give his thoughts about this.

**Comment by bparrishMines** [comment]
I think it might be better to expose the `_isDisposed` flag with a public accessor. I think the word uninitialized implies that the `CameraController` was never initialized which isn't true in this case.

**Comment by onadoroz** [comment]
> Hi @onadoroz
> 
> It is correct that in the current version of the plugin when you call the `dispose` method and call `Controller.value.isInitialized` it returns true, thus there is currently no way of knowing when the camera is disposed after being initialized.
> 
> I think by changing the plugin slightly there could be a improvement for this.
> I could make a PR and add `value = CameraValue.uninitialized();` to the `dispose` method.
> It would look like this:
> 
> ```
> Future<void> dispose() async {
>  if (_isDisposed) {
>    return;
>  }
> 
>  _isDisposed = true;
>  value = CameraValue.uninitialized();
>  super.dispose();
>  if (_creatingCompleter != null) {
>    await _creatingCompleter.future;
>    await _channel.invokeMethod<void>(
>      'dispose',
>      <String, dynamic>{'textureId': _textureId},
>    );
>    await _eventSubscription?.cancel();
>  }
> }
> ```
> 
> But to make sure this is a correct approach maybe @bparrishMines could give his thoughts about this.

Hi @Sempakonka,
correct. Just checked on version 0.5.8+8  ([√] Flutter (Channel stable, 1.22.0, ) and it still reproducible:

  Future controllerDispose(context) async {
    try {
      await cameraScanController.dispose().whenComplete(() {
        printLog(
            "Dispose done. controllerStatus is: ${cameraScanController.value.isInitialized} ");
      });
    } catch (e) {
      printLog("Dispose controller Error: $e");
    }
  }

>> [CodeScan_Services.dart] Dispose done. controllerStatus is: true
