### ISSUE TITLE
exceptions exiting google_sign_in(mojo) and similar plugins

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5163]
## Steps to Reproduce

I am using a .gyp based build so it's not easy to post repro steps. I imagine if you fixed the google_sign_in mojo branch example to run against flutter/master you would be able to recreate the issue. Chinmay has some screenshots from a couple weeks ago with the exception stack in Xcode.

The exception occurs after signing in on google_sign_in, or just clicking "Done" in google_sign_in before signing in.

This is on the iOS simulator. I have not attempted to reproduce on hardware yet.
## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 2b3099c814 (4 hours ago), engine revision c4b2e675b1

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```
## Logs and Crash Reports

`gpu_thread(6): EXC_BAD_ACCESS (code=EXC_i386_GPFLT)`

```
libobjc.A.dylib`objc_msgSend_stret:
    0x1052b5e00 <+0>:   testq  %rsi, %rsi
    0x1052b5e03 <+3>:   jle    0x1052b5e60               ; <+96>
    0x1052b5e05 <+5>:   movq   (%rsi), %r11
    0x1052b5e08 <+8>:   movq   %rdx, %r10
->  0x1052b5e0b <+11>:  andl   0x18(%r11), %r10d
    0x1052b5e0f <+15>:  shlq   $0x4, %r10
    0x1052b5e13 <+19>:  addq   0x10(%r11), %r10
    0x1052b5e17 <+23>:  cmpq   (%r10), %rdx
    0x1052b5e1a <+26>:  jne    0x1052b5e23               ; <+35>
    0x1052b5e1c <+28>:  testq  %r10, %r10
    0x1052b5e1f <+31>:  jmpq   *0x8(%r10)
    0x1052b5e23 <+35>:  cmpq   $0x1, (%r10)
    0x1052b5e27 <+39>:  jbe    0x1052b5e39               ; <+57>
    0x1052b5e29 <+41>:  addq   $0x10, %r10
    0x1052b5e2d <+45>:  cmpq   (%r10), %rdx
    0x1052b5e30 <+48>:  jne    0x1052b5e23               ; <+35>
    0x1052b5e32 <+50>:  testq  %r10, %r10
    0x1052b5e35 <+53>:  jmpq   *0x8(%r10)
    0x1052b5e39 <+57>:  jb     0x1052b5e7a               ; <+122>
    0x1052b5e3b <+59>:  movq   0x8(%r10), %r10
    0x1052b5e3f <+63>:  jmp    0x1052b5e4b               ; <+75>
```

**Comment by eseidelGoogle** [comment]
Please add the `flutter --version` if possible.  This crash is in the gpu_thread, @jason-simmons recently fixed some lifetime issues with our handling of Skia and it's possible this was from a bad engine revision.  @chinmaygarde also made a bunch of changes to our skia code.  If you email one of us the full crash log we might be able to better help debug.

**Comment by drewwarren** [comment]
The version information is in flutter doctor. I sent Chinmay screenshots of the exception as it appears in Xcode. How do I get the "full crash log"?

**Comment by eseidelGoogle** [comment]
Oh, my bad, sorry.   command-/ inside the iOS simulator will open up Console.app which displays logs.  There should be a "User Diagnostic Report" or if you command-click on the system.log in the title bar you can select the parent folder of the system.log for that simulator which contains many other log folders including one for crash logs.

<img width="413" alt="screen shot 2016-07-29 at 7 50 11 pm" src="https://cloud.githubusercontent.com/assets/11857803/17267731/b4aba59c-55c5-11e6-8e6f-eefc5197d080.png">

There is probably a simpler way, but given that I was unable to read the version out of your `flutter doctor` output, maybe I should research other ways later. :)

**Comment by drewwarren** [comment]
I set a marker in system.log before clicking "Done" in the google sign in flow which triggers the exception. Here is the output in that period.

```
 Marker - Aug 1, 2016, 11:49:24 AM
Aug  1 11:49:20 drewwarren-macbookpro searchd[91076]: tcp_connection_tls_session_error_callback_imp 7 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Aug  1 11:49:26 drewwarren-macbookpro assertiond[91016]: assertion failed: 15G31 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Aug  1 11:49:26 --- last message repeated 3 times ---
Aug  1 11:49:26 drewwarren-macbookpro backboardd[91013]: CoreAnimation: updates deferred for too long
Aug  1 11:49:27 drewwarren-macbookpro assertiond[91016]: assertion failed: 15G31 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
```

A screenshot of the exception in Xcode can be found at: https://screenshot.googleplex.com/8KbVMKfXmNM

**Comment by eseidelGoogle** [comment]
I think this can be closed?
