### ISSUE TITLE
RouteSettings.isInitialRoute has been removed but is still included in the documentation

### ISSUE THREAD

**Issue by dfmiller** [flutter/flutter#51649]
A recent update (https://github.com/flutter/flutter/pull/51435) has removed the isInitialRoute parameter from RouteSettings but it is still in the documentation (https://api.flutter.dev/flutter/widgets/RouteSettings-class.html) with no mention of the deprecation.

This update breaks at least one plugin (https://github.com/brianegan/chewie)

**Comment by slightfoot** [comment]
It's in the master API docs.
https://master-api.flutter.dev/flutter/widgets/RouteSettings-class.html

**Comment by chunhtai** [comment]
the change hasn't propagate to stable yet. Once it does, the api doc will get updated. I will close this issue as there is no actionable item, feel free to reopen if you think otherwise

**Comment by coolnalu** [comment]
What is it replaced with?

**Comment by chunhtai** [comment]
You can look into [onGenerateInitialRoutes](https://master-api.flutter.dev/flutter/material/MaterialApp/onGenerateInitialRoutes.html)

Please see https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring for more detail
