### ISSUE TITLE
analyzer_benchmark flutter_repo_batch_maximum regression; rebaseline?

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51641]
Looks like it's nudged upwards since https://github.com/flutter/flutter/pull/51518. I don't think that's the culprit, though.

Is this a candidate for rebaselining?

![analyzer](https://user-images.githubusercontent.com/1435716/75568571-5e816d00-5a08-11ea-9deb-b76d69abcc59.png)

**Comment by tvolkert** [comment]
I rebaselined.
