### ISSUE TITLE
[web] Multiline text field text is not selectable by mouse beyond line 1

### ISSUE THREAD

**Issue by yzxben** [flutter/flutter#51640]
## Steps to Reproduce

1. Create a multiline text field, e.g.`TextField(maxLines: 20)`
2. Enter long text that spans multiple lines
3. With a mouse, try to select any text on line 2 or after.

**Expected results:**

Text is selectable, on any line.

**Actual results:**

The text cursor stays in line 1. Although it does move to the right column, it doesn't move to the correct line.

- OS: MacOS
- Browser: Chrome 80.0.3987.122
- Dart 2.7.1, latest Flutter

**Comment by VladyslavBondarenko** [comment]
In multiline text field I can't move text cursor by mouse at all. If I move text cursor by keyboard, then mouse click at any position moves text cursor to the first position. Double click at any position leads to selecting the first line only.

OS: Windows 10
Chrome: 80.0.3987.116
Current master (1.15.4-pre.220)

**Comment by mdebbar** [comment]
This is currently broken in flutter web. However, it is fixed if you enable the new, experimental text layout implementation (https://github.com/flutter/flutter/issues/33523). In that issue, you'll find a description on how to enable it.
