### ISSUE TITLE
Ensure 'zip' is installed on devicelab mac and linux machines

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#51654]
zip is used by the Flutter tool when downloading and expanding artifacts. Previously the errors hit when zip doesn't exist were swallowed, but going forward we would like to avoid swallowing this sort of error:

https://github.com/flutter/flutter/issues/8742

/cc @godofredoc

**Comment by zanderso** [comment]
For further background, the use of `zip -T` to verify zip files is to avoid `unzip` failing with a partially extracted tree, which can be difficult to recover from.

I will update the website docs.

**Comment by zanderso** [comment]
https://github.com/flutter/website/pull/3749
https://github.com/flutter/website/pull/3748

**Comment by digiter** [comment]
What is the next step on this? What is needed from infra side?

**Comment by godofredoc** [comment]
We need to install zip on all the device lab mac and linux machines and update the provisioning scripts to include it on new test beds.

**Comment by digiter** [comment]
All mac and linux hosts have zip installed now. Provision change is waiting for review.

**Comment by zanderso** [comment]
Thanks!

**Comment by digiter** [comment]
Done updating the linux VMs, provision change at http://tqr/185683.
