### ISSUE TITLE
flutter-doctor IntelliJ IDEA Community Edition plugins not installed

### ISSUE THREAD

**Issue by royibernthal** [flutter/flutter#51664]
I'm using Android Studio.
I'm running flutter-doctor in my project and I'm getting the following output:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```

It says both the flutter and dart plugins are not installed, however when I go to File -> Settings -> Plugins, I can clearly see that both of them are installed, up-to-date and enabled.

What am I missing?

**Comment by JosepBove** [comment]
Maybe I am wrong but I think that you are working using Android Studio which is okay. Nonetheless, you have installed IntelliJ IDEA without the flutter and the dart plugins but that shouldn’t be an issue if you are working from Android Studio.

**Comment by royibernthal** [comment]
> Maybe I am wrong but I think that you are working using Android Studio which is okay. Nonetheless, you have installed IntelliJ IDEA without the flutter and the dart plugins but that shouldn’t be an issue if you are working from Android Studio.

Yup exactly, makes sense. Thanks :)
