### ISSUE TITLE
Document Padding and Container's padding

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5166]
From user feedback: "Why use the Padding class and constructor when I can just use the Container class which includes everything?"

Answer: "There isn't really any difference between the two. If you supply a "padding" argument to Container it just makes a Padding widget for you."

We could add this note to the docs for Container and Padding, to help clarify for the next user (assuming we keep the Padding class around and accessible to users).

**Comment by eseidelGoogle** [comment]
I feel like I overheard @Sfshaza and @Hixie discussing this, maybe this is already documented?
