### ISSUE TITLE
Rename Flexible to Expand and Fit

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5169]
We've received feedback from new users that our Flex implementation is kinda-but-not-really the Flexbox they know and love from the web. This can cause a bit of friction as they learn how our Flex is and is not Flexbox.

We can consider renaming Flex to help avoid users drawing parallels and miss-set expectations. One idea was the rename to Linear.

Presumably this would be a breaking change and if we do this, we can email our users, etc.

**Comment by sethladd** [comment]
cc @Hixie @abarth to make a call here...

**Comment by Hixie** [comment]
sgtm

**Comment by abarth** [comment]
We'll need a new name for `Flexible` as well.

**Comment by Hixie** [comment]
Yeah that's the main thing that's been blocking me from doing this.
See also https://github.com/flutter/flutter/issues/4189.

**Comment by abarth** [comment]
`Linear` would conflict with the linear `Curve`.

**Comment by sethladd** [comment]
Was this the right issue to close, in response to https://github.com/flutter/flutter/commit/c621ec82a05361836b71f0245589f3f81a513d07 ?

**Comment by abarth** [comment]
Nope, sorry.

**Comment by Hixie** [comment]
Yeah I don't think "Linear" is a good name either.

I'm not too worried about the name Flex. I think it's fine to keep that name; it's mostly buried anyway. It's Flexible that I think we should primarily rename.

**Comment by Hixie** [comment]
Ideas from brainstorming: split it into two widgets, "Expand" and "Fit"?

**Comment by sethladd** [comment]
cc @dvdwasibi

**Comment by abarth** [comment]
Expanded is a go.  Not sure about Fit...

**Comment by abarth** [comment]
Cleaning up clients now.

**Comment by sethladd** [comment]
Thanks!
