### ISSUE TITLE
when i run "Flutter build apk" it creates an old code apk, but when i run "Flutter run" its working with new code only.. 

### ISSUE THREAD

**Issue by lokeshpaladugula** [flutter/flutter#51694]
i even tried  Flutter clean .. Flutter build apk.. but still it builds old version of code only..

**Comment by liodali** [comment]
did you run  flutter clean ?

**Comment by lokeshpaladugula** [comment]
> did you run flutter clean ?
 yes i did bro

**Comment by jonahwilliams** [comment]
@lokeshpaladugula you need to fill out more of the issue template. For starters, what version of flutter are you on? Then how are you determining that other APK isn't updating?

**Comment by lokeshpaladugula** [comment]
> @lokeshpaladugula you need to fill out more of the issue template. For starters, what version of flutter are you on? Then how are you determining that other APK isn't updating?

```
flutter --version
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

the apk only runs for the first login page but not moving to the next page .. this is how i checked at begging of the app.. but it has many pages and many functions.. but still it runs the first page only.. but when i use "flutter run" it is working fine bro

**Comment by jonahwilliams** [comment]
> the apk only runs for the first login page but not moving to the next page

Can you provide more details here? I'd like to help but its not possible for me to figure out what is wrong from your description of the problem.

>  but not moving to the next page

What does this mean?

**Comment by lokeshpaladugula** [comment]
ok bro.. im sorry..
im  new to flutter 

actually my app's main screen is a login screen and at begin i tried to  build apk to my app which contains only login page and when i press login button it shows alert box..
and later i modified many things and finally created a e-commerce app and now i tried to build apk file again ..
but still it building the apk which contains only login page

but when i run the app in debug mode it is working fine..

**Comment by TahaTesser** [comment]
Hi @lokeshpaladugula 
can you please execute `flutter run --verbose` and try to login in your app and then copy and paste the logs here in the comment? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by lokeshpaladugula** [comment]
im sorry guys.. there is no problem.. i found my mistake..

thanks for responding

**Comment by hautran90** [comment]
I have same problem, please help me fix it @lokeshpaladugula

**Comment by hafidzizzudin** [comment]
> im sorry guys.. there is no problem.. i found my mistake..
> 
> thanks for responding

hi would you like to share your solution? I encountered the same problem. @lokeshpaladugula
