### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Vuyisile619** [flutter/flutter#51690]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

Hey guys i just opened a new flutter project. I have not messed around with anything but i keep getting this error every time i run the app.Flutter doctor throws no erros the problem i have is when i run the app.This is the output code

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #3: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #4: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #7: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #2: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #5: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #6: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12m 46s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kisjinn** [comment]
looks similar to #24645 and #37848

**Comment by Vuyisile619** [comment]
> looks similar to #24645 and #37848

Non of these solved the issue for me. The errors i get are different from the ones they have please help how do i fix this.. I have been stuck here for days now

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/48443
@Vuyisile619
Could you provide your `flutter doctor -v`?

**Comment by Vuyisile619** [comment]
> Similar to #48443
> @Vuyisile619
> Could you provide your `flutter doctor -v`?

Hey Vlad this is it.And i have to mention, flutter commands do not work on my cmd they only work when i open my cmd as administrator. Is that normal?

C:\WINDOWS\system32>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.657], locale en-ZA)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter\flutter\flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Vuyisile Van Dave\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Windows\System32>

**Comment by Vuyisile619** [comment]
> Similar to #48443
> @Vuyisile619
> Could you provide your `flutter doctor -v`?

Hie there are you still there? I am waiting for your response

**Comment by harshithmohan** [comment]
I don't know know if it's the correct way but I changed
`https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`
to
`https\://services.gradle.org/distributions/gradle-5.6.3-all.zip`
in `gradle/wrapper/gradle-wrapper.properties` and it started working

**Comment by jonahwilliams** [comment]
This is likely an issue with that particular version of Gradle. Upgrading/downgrading like in https://github.com/flutter/flutter/issues/51690#issuecomment-603988891 is likely the only solution
