### ISSUE TITLE
Where to save static library for iOS with FFI

### ISSUE THREAD

**Issue by hyousef-rusty** [flutter/flutter#51695]
I testing native lib use with flutter, I was able to figure out that in Android, native libs are required to be saved at `android/app/src/main/jniLibs/X folder`, where X is architecture name
And in the `Gradle Build`, you need to add this directory `main.jniLibs.srcDirs = ['src/main/jniLibs']` to the source set, so that the source set become:
```
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.jniLibs.srcDirs = ['src/main/jniLibs']
    }
```

Trying to test it now with iOS, so I added it to the frameworks and libraries using `Xcode -> Runner -> Targets: Runner -> General -> Frameworks, Libraries and Embedded Content` and added the `libnative.a` file there. but at running the flutter app, I got the below error:

```bash
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           14.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ld: library not found for -lnative
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

**Comment by iapicca** [comment]
Hi @hyousef-rusty 
for a static library the [doc](https://flutter.dev/docs/development/platform-integration/c-interop#step-2-add-cc-sources) states

> You add the sources to the ios folder, because CocoaPods doesn’t allow including sources above the podspec file, but Gradle allows you to point to the ios folder. 
It’s not required to use the same sources for both iOS and Android; you may, of course, add Android-specific sources to the android folder and modify CMakeLists.txt appropriately.

Is it this your case?
Thank you

**Comment by anondev32** [comment]
The docs are unclear. Is it the ios folder of the plugin or the example / target app?
And how do we tell xcode that it has to link the file?

**Comment by TahaTesser** [comment]
Hi @hyousef-rusty 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
