### ISSUE TITLE
Could not create an instance of type org.gradle.invocation.DefaultGradle in "Flutter run"

### ISSUE THREAD

**Issue by xjhofernandes** [flutter/flutter#51702]
When I try to run the flutter, these errors appear:

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Could not create an instance of type org.gradle.invocation.DefaultGradle.
> org/gradle/caching/internal/packaging/BuildCacheEntryPacker
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more >log output. Run with --scan to get full insights.
>
>* Get more help at https://help.gradle.org

I tried reinstalling java, Android Studio and Flutter. But the error persists.

My Flutter doctor: 
>Doctor summary (to see all details, run flutter doctor -v):
>[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [versÃ£o 10.0.17763.1039], >locale pt-BR)
>
>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>[√] Android Studio (version 3.6)
>[√] VS Code (version 1.42.1)
>[√] Connected device (1 available)
>
>• No issues found!

Can anyone help-me? Thanks!

**Comment by xjhofernandes** [comment]
I fixed! Just removing the .gradle folder in  **C:\"your_user"\.gradle**. 
Haha 😄

**Comment by fatihcc** [comment]
> I fixed! Just removing the .gradle folder in **C:\"your_user"\.gradle**.
> Haha 😄

foler 1,75 gb are you shore for deelte??
