### ISSUE TITLE
Is it possible to have multiple channels in same computer

### ISSUE THREAD

**Issue by greedyRoach** [flutter/flutter#51705]
I have two projects, one web and one mobile, each project needs a different channel.
the question is: do i need to constantly change between channels (and upgrade flutter) to use flutter as i want or is possible to keep different flutter channels per project in the same computer?

**Comment by jonahwilliams** [comment]
Nothing is stopping you from setting up multiple SDKs and using an alias to refer to each one. This isn't really a big with flutter so I'm closing the issue, though if you have more questions it would be best to reach out on one of the community sites at flutter.dev/community

**Comment by sunaarun** [comment]
> Nothing is stopping you from setting up multiple SDKs and using an alias to refer to each one. This isn't really a big with flutter so I'm closing the issue, though if you have more questions it would be best to reach out on one of the community sites at flutter.dev/community

@jonahwilliams  , can you tell how to do that please , what do you mean with alias? 
please can you give me more explanation
