### ISSUE TITLE
Flutter Camera example video thumbnail crashes after successfully capturing the first video 

### ISSUE THREAD

**Issue by 55ahmedsalah** [flutter/flutter#51708]
[Example Link](https://github.com/flutter/plugins/tree/master/packages/camera)

**Comment by VladyslavBondarenko** [comment]
Hi @55ahmedsalah 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose` (repeat the crash with verbose)?

**Comment by 55ahmedsalah** [comment]
@VladyslavBondarenko 
I managed to solve this by moving `await videoController?.dispose();` [on line 428](https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart#L428) to the `dispose()` method
