### ISSUE TITLE
Flutter widget test - open and tap value in DropDownButton, not working as expected

### ISSUE THREAD

**Issue by phasee** [flutter/flutter#51707]
Created a sample app for the issue, which can be found here: https://github.com/phasee/flutter_dropdown_test_selection_issue

I am trying to test the value passed to a model from a dropdownbutton, and the WidgetTester does not seem to tap the item correctly.

I have a model which I am mocking using mockito. When a value is chosen from the dropdownbutton, that value should be passed to the model.updateSelection method. I cannot verify this method is called during the test.

Is this a bug? Or am I misunderstanding how dropdownbuttons behave?

**Comment by TahaTesser** [comment]
Hi @phasee 

For issue related to the this package [mockito ](https://pub.dev/packages/mockito) you may want to open an issue in the dedicated [github](https://github.com/dart-lang/mockito/issues).

Thank you
