### ISSUE TITLE
Cannot use mockito in widget tests

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5170]
## Steps to Reproduce

- import [mockito](https://pub.dartlang.org/packages/mockito) in a [flutter widget test](https://flutter.io/testing/#widget-testing).
- run `flutter test tests/test_with_mockito.dart`
- Observe `[ERROR:dart_library_loader.cc(303)] Error Loading package:mockito/mockito.dart 'package:mockito/mockito.dart': error: line 3 pos 1: import of dart:mirrors with --enable-mirrors=false`.

## Use case

We want to verify our widget interacts correctly with an instance of a file reading/writing class it takes as a constructor parameter. To do this in tests we want to create a mock instance of the file manipulating class using mockito.

**Comment by Hixie** [comment]
https://github.com/fibulwinter/dart-mockito/issues/27

It looks like mockito's use of mirrors is incidental. It seems to be primarily used in spy(), which isn't used internally and isn't required to use the mockito API. The only other use is in a toString method.

Worst case, we could just create our own version of mockito. It's a pretty trivial library at its core.

**Comment by eseidelGoogle** [comment]
@drewwarren one short-term fix would be to fork mockito locally and remove dart:mirrors calls.  There are codegen-based ways to do much of what dart:mirrors does which we could wire up.

As you know, we avoid dart:mirrors in production builds to keep binary sizes down and execution speed fast.  We certainly could enable mirrors in flutter tests, but that would create further difference between testing and production environments.

**Comment by Hixie** [comment]
@drewwarren looks like the mockito folk are going to make a variant without mirrors for you. See the aforementioned bug for details.

**Comment by drewwarren** [comment]
Awesome. Thanks for coordinating this Ian.

**Comment by Hixie** [comment]
My understanding is that this is now fixed. Please reopen if not.

**Comment by jaumard** [comment]
Hey I'm having this issue on a normal test, I'm trying `class MockNavigatorState extends Mock implements NavigatorState {}` but getting `error: 'Mock.toString' ('() → String') isn't a valid override of 'Diagnosticable.toString' ('({minLevel: DiagnosticLevel}) → String'). (invalid_override at [kiwi_mobile] test/common/fcm/fcm_text_manager_test.dart:12)`

**Comment by adesugbaa** [comment]
@jaumard Hi. Were you able to get the mock navigator tests working? I am having same issues.
