### ISSUE TITLE
simple way to customize the keyboard globally on all text fields (ex: add a close button)

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#51727]
## Use case

at app root widget, add global customization actions for all text fields

**Comment by renanyoy** [comment]
maybe with some cases depending of keyboard type (ex: number, phone, email, text, etc..)
will make a lightweight plugin, not heavy as hell like the current one

**Comment by justinmc** [comment]
@renanyoy Are you thinking of changing the keyboard buttons themselves, or adding something drawn by Flutter that sits on top of the keyboard?
