### ISSUE TITLE
Sir i want to create a folder in SD card like WhatsApp using path_provider

### ISSUE THREAD

**Issue by Kalyanb447-github** [flutter/flutter#51728]
Sir i want to create a folder in SD card like WhatsApp
but its not createing 
its creating on android/data/com.demo/files
i need SDcard/demo

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
