### ISSUE TITLE
OutlineInputBorder defining border color does not work.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51729]
OutlineInputBorder defining border color does not work.
`        TextField(
                    decoration: InputDecoration(
                        hintText: "enter email",
                      fillColor: Colors.white24,
                      filled: true,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(30),
                        borderSide: BorderSide(
                          color: Colors.white,
                          style: BorderStyle.solid
                        )
                      )
                    ),
                  ),`

**Comment by TahaTesser** [comment]
Hi @gionchat 
You need to implement `focusedBorder` for border when `TextField`  [Stackoverflow Reference](https://stackoverflow.com/a/54143761)

### Try this sample code
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
            decoration: InputDecoration(
          hintText: "enter email",
          fillColor: Colors.white24,
          filled: true,
          focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(30),
              borderSide: BorderSide(
                  color: Colors.blue, style: BorderStyle.solid, width: 4)),
          enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(30),
              borderSide: BorderSide(
                  color: Colors.white, style: BorderStyle.solid, width: 4)),
        )),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
`OutlineInputBorder` seems to work fine 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
 Thank you

**Comment by anmol500** [comment]
So is border property in OutlineInputBorder is of no use??? @TahaTesser

**Comment by NikolaT0mic** [comment]
I have the same problem i don´t think it makes sense to have a border property when it does not affect the textfield and you have to specifiy a border for every case for the textfield. @anmol500 
Is there any way to specify the border decoration for every case? @TahaTesser
