### ISSUE TITLE
Newwer version of android sdk is required

### ISSUE THREAD

**Issue by mukkulsingh** [flutter/flutter#51726]
flutter doctor --android-licenses gives the output as 
A newer version of the Android SDK is required. To update, run:

I installed all the sdk available from sdk manager in android studio.
still the error is same.
and while i type flutter run the application does run but the behaviour is not normal. i guess the application is running the previous code

**Comment by JosepBove** [comment]
Probably a duplicated of #28504

**Comment by iapicca** [comment]
Hi @mukkulsingh 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by mukkulsingh** [comment]
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.17763.805], locale en-IN)
    • Flutter version 1.14.6 at C:\flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\KD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\KD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @mukkulsingh 
could you please describe how this issue is different from the one linked?
Thank you
