### ISSUE TITLE
Can not find TargetPlatform.web

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#51723]
if(debugDefaultTargetPlatformOverride == TargetPlatform.android){

    }else if(debugDefaultTargetPlatformOverride == TargetPlatform.iOS){

    }else if(debugDefaultTargetPlatformOverride == TargetPlatform.){

    }

Can not find TargetPlatform.web

**Comment by jonahwilliams** [comment]
The web is not a TargetPlatform. You could be running on Android on the web, or on iOS for example.
