### ISSUE TITLE
Flutter android build failed 

### ISSUE THREAD

**Issue by Mohaziz93** [flutter/flutter#51733]
Getting this error

> Launching lib\main.dart on JKM LX1 in debug mode...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find com.android.tools.build:gradle:3.5.0.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom
>        - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.jar
>        - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom
>        - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.jar
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 8s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                         9.9s
> Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
Hi @Mohaziz93 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @Mohaziz93 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
