### ISSUE TITLE
Document "How to create a widget with a custom RenderObject"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5173]
From a user:

A “creating a custom widget” section in basic Flutter layout documentation would be helpful, as the setup for a new Custom Widget requires a lot of knowledge up front:
- Just the RenderBox performLayout() method has several important duties that aren’t reflected in its args or a return value
  - Loop through all the children via a linked list starting with “firstChild”
  - Execute each child RenderBox’s layout functions
  - Set the RenderBox’s size
  - Position each child RenderBox

**Comment by Hixie** [comment]
Some of this is documented now in the RenderBox and RenderObject API docs. Maybe we should add more to the RenderObjectWidget API docs too?

**Comment by xster** [comment]
The RenderBox doc was pretty useful. I think a page like https://flutter.io/tutorials/layout/ that walks through a hypothetical exercise would be nice too.

**Comment by goderbauer** [comment]
@zoechi Should this be moved to the website repo? Most people I've talked to expect this to be a tutorial on the website. The API docs already have a lot of information on this, but most people want some kind of a codelab on this.

**Comment by zoechi** [comment]
I copied it to https://github.com/flutter/website/issues/2122 and am going to close here.
Just reopen if you think there is still api-doc work to do as well.
