### ISSUE TITLE
flutter build ios-framework --cocoapods,There is no FlutterPluginRegistrant.framework

### ISSUE THREAD

**Issue by xinghunMeng** [flutter/flutter#51736]
[flutter] flutter doctor -v
[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.15.3 at /Users/wunan/Documents/sankuai/flutter
    • Framework revision 67826bdce5 (3 weeks ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

after run flutter build ios-framework --cocoapods,the result
![image](https://user-images.githubusercontent.com/12692214/75624941-4a9a5e80-5bf4-11ea-8f59-882daa9bdf2f.png)
but official website show
![image](https://user-images.githubusercontent.com/12692214/75624954-66056980-5bf4-11ea-97c7-6ee92a7a816c.png)
how to solve？thanks

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/51113
@xinghunMeng do you have Flutter plugins in your module?

**Comment by xinghunMeng** [comment]
No

**Comment by xinghunMeng** [comment]
#51113，I know why，thank you， @VladyslavBondarenko
