### ISSUE TITLE
in_app_purchase 0.3.1+1 purchaseResponse.pastPurchases does not return non consumable

### ISSUE THREAD

**Issue by adlucio87** [flutter/flutter#51738]
Hi,

I'm having problem using in_app_purchase plugin.

I'm testing my Android app, i have tow products on google play store, one consumable and one non consumable.
I can retrive all products and their prices correctly.
I can olso buy both product and see it in play store.

The problem occure using this method:
```
`final QueryPurchaseDetailsResponse purchaseResponse =  await _connection.queryPastPurchases();

final List<PurchaseDetails> verifiedPurchases = [];
 
for (PurchaseDetails purchase in purchaseResponse.pastPurchases) {
      if (await _verifyPurchase(purchase)) {
        verifiedPurchases.add(purchase);
      }
}`
```
It return just past consumable purchase till tey are active, never return the non consumable one.

Let me know if you need more data.

Thanks,
Andrea

**Comment by henreke** [comment]
Hello @adlucio87  do you can retrieve subscriptions on your app? My app returns the consumable products but does not return the subscriptions products. If you could help me i will appreciate.
Thank you.

**Comment by adlucio87** [comment]
Hi Henreke,
I sudgest you using this example:
https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/example/lib
consumable_store.dart

Almost evrithing works great and return all type of products.

**Comment by henreke** [comment]
> Hi Henreke,
> I sudgest you using this example:
> https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/example/lib
> consumable_store.dart
> 
> Almost evrithing works great and return all type of products.

Hello thanks for your help. I already put this exemple inside my app but it returns just the consumable itens, the two subscription itens does not returns

**Comment by adlucio87** [comment]
just for clarify consumable and purchase are the same product on google play.
Consumable means that it will be consumed in a defined time period or use.
Non consumable are product that you buy and is yours forever.

Last help... ;) Are you sure your subrscription/consumable is active?
This line of code must return all products, i test it and it is working:
const List<String> _kProductIds = <String>[ 'yourconsumableid1',  'yournonconsumabelid2'];
ProductDetailsResponse productDetailResponse = await _connection.queryProductDetails(_kProductIds.toSet());
If you still have the problem i sudgest you to open an other issue attaching all data.

**Comment by henreke** [comment]
Hello, I solved the problem, I just sended an updated apk to the alfa channel on play console and it worked. Thanks for your help.

**Comment by matthew-carroll** [comment]
@adlucio87 is this problem still occurring?

**Comment by adlucio87** [comment]
Hi @matthew-carroll i don't think it works, my app was in production. At end I'have used other plugin Flutter_inapp_purchase.

**Comment by matthew-carroll** [comment]
@adlucio87 do you happen to have simple reproduction steps? I'm able to query past purchases on iOS with sandbox testing.

If you don't have a reproduction case, should we close this ticket?

**Comment by adlucio87** [comment]
Sorry but know i didn't have a reproduction case. If in future i will use it again i will send you feedbak. Thanks
