### ISSUE TITLE
Flutter driver - ant new features ?

### ISSUE THREAD

**Issue by ShlomoNus** [flutter/flutter#51735]
I am new to flutter, a specially to flutter drivers. As far I can see, new features are added all the time, but where is the track of it?

**Comment by jonahwilliams** [comment]
The issue tracker is for bugs and feature requests, not general discussion like this. You can see what is being worked on by looking at https://github.com/flutter/flutter/wiki/Issue-hygiene#milestones and https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed
