### ISSUE TITLE
Failed to download the Android dependencies on flutter precache

### ISSUE THREAD

**Issue by mukkulsingh** [flutter/flutter#51742]
I tried uninstalling android studio it didn't worked.
Flutter precache isn't below i am attaching output for flutter commands

C:\Users\DELL\AndroidStudioProjects\flutter_app>flutter precache
Failed to download the Android dependencies
Downloading Android Maven dependencies...                           0.4s

C:\Users\DELL\AndroidStudioProjects\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at E:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by TahaTesser** [comment]
Hi @mukkulsingh 
Can you please provide `flutter precache --verbose`?

You might wanna resolve this too "X Android license status unknown." [Comment](https://github.com/flutter/flutter/issues/51712#issuecomment-593379700)
Thank you

**Comment by mukkulsingh** [comment]
Sorry....I don't have access to that device now.
