### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ighidan** [flutter/flutter#51740]
Hello,

I have a requirement for an existing app but I'm not sure how to proceed.

1- My client wants to be able to send notifications from the API to the app.
2- Notifications can be sent to all or to specific users only.
3- Notifications should show even if the app is closed.

The backend is built with PHP and MySQL.

I know about Firebase Push Notifications but I'm not sure it fulfills this requirement.

Any ideas? Thanks

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by ighidan** [comment]
> Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

Thank you
