### ISSUE TITLE
Running flutter build appbundle for Android on Windows gives error

### ISSUE THREAD

**Issue by royabhijit** [flutter/flutter#51745]
On running flutter build appbundle in the project directory, I get the below error.

Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by
this package. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: C:\flutter
  previous reference  : C:\flutter_sdk\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are

running the expected version (run 'flutter --version' to see which flutter is on your path).

Running Gradle task 'bundleRelease'...
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by t
his package. The repository from which the 'flutter' tool is currently executing will be used instead.

  running Flutter tool: C:\flutter

  previous reference  : C:\flutter_sdk\flutter

This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are
 running the expected version (run 'flutter --version' to see which flutter is on your path).

Compiler message:

/C:/flutter_sdk/flutter/packages/flutter/lib/src/rendering/layer.dart:1580:36: Error: 'ImageFilterEngineLayer' isn't a t
ype.

      oldLayer: _engineLayer as ui.ImageFilterEngineLayer,

                                   ^^^^^^^^^^^^^^^^^^^^^^

/C:/flutter_sdk/flutter/packages/flutter/lib/src/rendering/layer.dart:1578:27: Error: The method 'pushImageFilter' isn't
 defined for the class 'SceneBuilder'.

 - 'SceneBuilder' is from 'dart:ui'.

Try correcting the name to the name of an existing method, or defining a method named 'pushImageFilter'.

    engineLayer = builder.pushImageFilter(

                          ^^^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.

FAILURE: Build failed with an exception.

* Where:

Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:

Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Running Gradle task 'bundleRelease'...                             18.9s
Gradle task bundleRelease failed with exit code 1

I tried flutter upgrade but still getting error. Please help me in resolving the above errors.

**Comment by TahaTesser** [comment]
Hi @royabhijit 
Please try 'flutter clean` and then build again if it doesn't work
can you please provide your `flutter doctor -v` and `flutter build appbundle --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by royabhijit** [comment]
Surprisingly it worked today... I ran ```flutter clean``` then ```flutter build appbundle``` and I was able to generate the app-release.aab file. While yesterday I ran ```flutter clean``` and tried it didn't work... If I still need to post flutter doctor -v and flutter build appbundle --verbose` output, please let me know I will share.... Thank you

**Comment by TahaTesser** [comment]
Hi @royabhijit 
Given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by malminawi** [comment]
Hi @royabhijit 
I am facing the same issue, i tried flutter clean and tried again, nothing changed.
Please advise me how to solve it.

Thanks a lot!!

**Comment by malminawi** [comment]
Hi @TahaTesser 
I am facing the same issue, i tried flutter clean and tried again, nothing changed.
Please advise me how to solve it.

Thanks a lot!!

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
