### ISSUE TITLE
Align is cheating!

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5175]
Align's alignment parameter is overloaded.  It means different things depending on whether heightFactor and/or widthFactor is set.

If feels like Align is actually multiple Widgets in one due to this.  I humbly suggest a separation of concerns should take place and Align's behaviour be split into possibly multiple widgets.

If you disagree, feel free to close.  I just wanted to have my displeasure on the record ;).

**Comment by apwilson** [comment]
Maybe the new Widget could be called ChildSizedContainer or something.

**Comment by eseidelGoogle** [comment]
Does this need consideration for api stability?  Marking speculatively, please remove as appropriate.

**Comment by Hixie** [comment]
I think we should close this. I disagree with the premise of the issue; alignment doesn't change meaning based on the other properties. Those properties only affect the size of the box.
