### ISSUE TITLE
Wrapping different providers in main.dart

### ISSUE THREAD

**Issue by Nitesh-Kanyal** [flutter/flutter#51759]
How to wrap multiple providers in main.dart file. wrapping Providers(Bloc provider, Localization provider) which one to place inner or outer.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
