### ISSUE TITLE
shared_preferences 0.5.6+2 fail to build on Android Studio 3.6.1

### ISSUE THREAD

**Issue by pahoel** [flutter/flutter#51760]
Build error related to shared_preferences_macos:
"A problem occurred evaluating root project 'shared_preferences_macos'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 5.1.1. If using the gradle wrapper, try editing the distributionUrl in C:\Users\Per-Arne Hoel\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip"

**Comment by JosepBove** [comment]
Hi @pahoel 
From the log path you have to open gradle-wrapper.properties file and update version to 5.4.1 from 5.1.1 in distributionUrl variable and save the file.

**Comment by TahaTesser** [comment]
Hi @pahoel 
Please try possible [solution](https://github.com/flutter/flutter/issues/42082#issuecomment-564252848)
Thank you

**Comment by pahoel** [comment]
> Hi @pahoel
> From the log path you have to open gradle-wrapper.properties file and update version to 5.4.1 from 5.1.1 in distributionUrl variable and save the file.

My existing gradle-wrapper.properties:
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by TahaTesser** [comment]
Hi @pahoel 
Please try `flutter pub cache repair`, `flutter clean` and then `flutter pub get` 
Thank you

**Comment by pahoel** [comment]
> Hi @pahoel
> Please try possible [solution](https://github.com/flutter/flutter/issues/42082#issuecomment-564252848)
> Thank you

Hi @TahaTesser 

Thanks for the provided link!

I found this solution:
"flutter.pub-cache\hosted\pub.flutter-io.cn\url_launcher_web-0.1.0+2\android\gradle\wrapper\gradle-wrapper.properties."
But I don't find this file. I only have one gradle-wrapper.properties file( android/gradle/wrapper directory), and it has the  distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by pahoel** [comment]
> Hi @pahoel
> Please try `flutter pub cache repair`, `flutter clean` and then `flutter pub get`
> Thank you

Hi @TahaTesser 

I'm sorry, but this did not work...

**Comment by TahaTesser** [comment]
Hi @pahoel 
Can you change the project build gradle?
your_app>android>bui.d.gradle 
`classpath 'com.android.tools.build:gradle:3.5.0'`
Thank you

**Comment by pahoel** [comment]
> 'com.android.tools.build:gradle:3.5.0'

Hi again,

and many thanks for your efforts tio help me!
classpath 'com.android.tools.build:gradle:3.5.0' is the existing dependency:

dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }

**Comment by pahoel** [comment]
Possible leads:
"The built failed likely due to AndroidX incompatibilities in a plugin."
"* What went wrong:
A problem occurred evaluating root project 'shared_preferences_macos'."

Is it possible that the error originates in the plugin itself?

**Comment by TahaTesser** [comment]
Hi @pahoel 
Is your project has AndroidX enabled?

**Comment by pahoel** [comment]
> Hi @pahoel
> Is your project has AndroidX enabled?

Hi again.

I don't remember if I did enable ActiveX when I started the project. How can I find out(I didn't find it in the Settings...)?

**Comment by TahaTesser** [comment]
Hi @pahoel 
Go to your_app>androi>gradle.properties

Check if it contains 
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```
Thank you

**Comment by pahoel** [comment]
Hi

Yes.
This is the content:
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

**Comment by pahoel** [comment]
Hi

Still trying - but little luck :-|

Now I have tried to change all 5.1.1 references in gradle-wrapper.properties in the plugin to **5.4.1**. 
The result is that I no longer get the same error, insted the build fails due to:
* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [com.android.support:support-annotations:28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Is this a new error or is it caused by the same  root error?

**Comment by TahaTesser** [comment]
Hi @pahoel 
I recommend you remove `shared_preferences_macos` and only use [shared_preferences](https://pub.dev/packages/shared_preferences)

Changelog from older version -> `shared_preferences 0.5.5`
```
0.5.5 #
Support macos by default.
```

You can use latest `shared_preferences 0.5.6+2` on MacOS for sure

### Code Sample
```
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SharedPreferences Demo',
      home: SharedPreferencesDemo(),
    );
  }
}

class SharedPreferencesDemo extends StatefulWidget {
  SharedPreferencesDemo({Key key}) : super(key: key);

  @override
  SharedPreferencesDemoState createState() => SharedPreferencesDemoState();
}

class SharedPreferencesDemoState extends State<SharedPreferencesDemo> {
  Future<SharedPreferences> _prefs = SharedPreferences.getInstance();
  Future<int> _counter;

  Future<void> _incrementCounter() async {
    final SharedPreferences prefs = await _prefs;
    final int counter = (prefs.getInt('counter') ?? 0) + 1;

    setState(() {
      _counter = prefs.setInt("counter", counter).then((bool success) {
        return counter;
      });
    });
  }

  @override
  void initState() {
    super.initState();
    _counter = _prefs.then((SharedPreferences prefs) {
      return (prefs.getInt('counter') ?? 0);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("SharedPreferences Demo"),
      ),
      body: Center(
          child: FutureBuilder<int>(
              future: _counter,
              builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
                switch (snapshot.connectionState) {
                  case ConnectionState.waiting:
                    return const CircularProgressIndicator();
                  default:
                    if (snapshot.hasError) {
                      return Text('Error: ${snapshot.error}');
                    } else {
                      return Text(
                        'Button tapped ${snapshot.data} time${snapshot.data == 1 ? '' : 's'}.\n\n'
                        'This should persist across restarts.',
                      );
                    }
                }
              })),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
This works on new project without any errors

### Preview 

![Screenshot_1583158980](https://user-images.githubusercontent.com/48603081/75684769-6f0f3d00-5cbf-11ea-94d6-15350802317a.png)

Try it in new project and then test it your existing project.

Thank you

**Comment by pahoel** [comment]
Hi

I have used shared_preferences in this project for quite some time - and it has worked flawlessly until the latest upgrade of Android Studio.

My pubspec.yaml dependies:
dependencies:
  flutter:
    sdk: flutter
  location: ^2.5.1
  soundpool: ^1.0.1
  sms: ^0.2.0
  shared_preferences: ^0.5.6

**Comment by TahaTesser** [comment]
Hi @pahoel 
Try this  possible [solution](https://github.com/flutter/flutter/issues/48264#issuecomment-584311032) and do `flutter run` again

**Comment by pahoel** [comment]
Hi again.

I deleted all content in the .gradle directory and ran flutter run.
Then I got no errors connected to the shared_preferences plugin. Insted the build failed because of:

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [com.android.support:support-annotations:28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'location'.

It's been a long day.

**Comment by TahaTesser** [comment]
Hi @pahoel 
I think you should try in a new project on machine and see it works and then copy same configuration into new setup

**Comment by pahoel** [comment]
Hi  @TahaTesser 

I did it the other way around: Startet a new project and copied the pubspec.yaml dependencies and all .dart files from the old project into the new. Looks like it's working...

Thanks for all help!

**Comment by TahaTesser** [comment]
Hi @pahoel 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by mofada** [comment]
same issues

**Comment by mofada** [comment]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_macos-0.0.1+6\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'shared_preferences_macos'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 5.1.1. If using the gradle wrapper, try editing the distributionUrl in D:\flutter\.pub-cache\hosted\pub.flutter-io.cn
\shared_preferences_macos-0.0.1+6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin shared_preferences_macos could not be built due to the issue above.

```

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/75851632-22457680-5e25-11ea-8cb8-877b39516597.png)

**Comment by mofada** [comment]
## flutter doctor -v
```
[√] Flutter (Channel master, v1.15.4-pre.255, on Microsoft Windows [Version 10.0.18362.657], locale zh-CN)
    • Flutter version 1.15.4-pre.255 at D:\flutter
    • Framework revision 7f6f08add7 (24 hours ago), 2020-03-03 01:20:25 -0500
    • Engine revision 6991dd981b
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 ca3ad264a6)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\JetBrains\apps\AndroidStudio\ch-0\193.6220182\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[!] Android Studio (version 3.5)
    • Android Studio at D:\Android\android-studio 3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\android-studio canary
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 4.0)
    • Android Studio at D:\JetBrains\apps\AndroidStudio\ch-0\193.6220182
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (5 available)
    • Pixel 3 XL • 8BAY0W6W8    • android-arm64  • Android 10 (API 29)
    • Redmi 4X   • c1f5972a7d74 • android-arm64  • Android 7.1.2 (API 25)
    • Windows    • Windows      • windows-x64    • Microsoft Windows [Version 10.0.18362.657]
    • Chrome     • chrome       • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server   • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

**Comment by agordeev** [comment]
I'm getting the same issue. Starting a new project and copy everything into it is definitely not an option.

**Comment by stuartmorgan** [comment]
Current versions of Flutter ignore platforms without Android folders, and the stub has been removed from that plugin, so closing as obsolete.
