### ISSUE TITLE
How to test failed assertion in Flutter test

### ISSUE THREAD

**Issue by Vadaski** [flutter/flutter#51761]
Hi, I encountered a problem while writing Flutter tests. I want to test that my assert statement fails and cover this line of code, but I didn't find a suitable solution.

I am test following code:
``` dart
  static ContainerManagerState of(BuildContext context) {
    final ContainerManagerState manager =
        context.ancestorStateOfType(const TypeMatcher<ContainerManagerState>());
    assert(manager != null, 'not in flutter boost');
    return manager;
  }
```
I want to test it when manager is null, and it should throw something like  `Failed assertion: line 57 pos 12: 'manager != null'` to me, and write some test code cover it.

I'v try this code below, but it will break the test.

```
expect(BoostContainerManager.of(builderContext), isAssertionError);
```

**Comment by goderbauer** [comment]
> I'v try this code below, but it will break the test.

How does the test break? Try `throwsAssertionError`: https://master-api.flutter.dev/flutter/flutter_test/throwsAssertionError.html

Also, these kind of questions are best asked on stackoverflow or other community forums.

**Comment by Vadaski** [comment]
It works! Thank you very much.

**Comment by connectpritam** [comment]
Unit code, that I want to test:
```
imports ...
class TextHolder extends StatelessWidget{
  const TextHolder({
    Key key,
    @required this.text
    }) : assert (text != null),
          super(key: Key);
  @override
  Widget build(BuildContext context) {
    return Text(text);
  }
}
```
And when I write my test code:
```
imports ...
void main(){
test('Assert Null check', (){
   // tried this
    expect(WrenchButton(text: null), throwsAssertionError);
   // also this 
    final Matcher throwsAssertionError = throwsA(isA<AssertionError>());
    expect(WrenchButton(text: null), throwsAssertionError);
});
}
```
Not able to perform a `Failed assertion` test using flutter_test package. When I run the test code, I get an error something like this in console:
`Failed assertion: line 8 pos 16: 'text != null': is not true.`

What I am looking for:
1. My test case should fail, if someone removes the `@required` annotation from my unit code.
2. My test case should fail, if someone sends `null` value to `text` property
