### ISSUE TITLE
animated_placeholder_perf regressions at #51689

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51776]
Clear signal at https://github.com/flutter/flutter/pull/51689. 
![Screenshot 2020-03-02 at 08 24 11](https://user-images.githubusercontent.com/1435716/75695635-3dff2000-5c5f-11ea-8aef-0b36c3b2c748.png)

Also affects `animated_placeholder_perf_average_frame_build_time_millis`, `average_frame_rasterizer_time_millis`, `99th_percentile_frame_build_time_millis`, `99th_percentile_frame_build_time_millis`, 
`worst_frame_build_time_millis`, `worst_frame_rasterizer_time_millis`, `90th_percentile_frame_rasterizer_time_millis`, 

Perhaps f`lutter_test_performance_implementation_change_elapsed_time_ms` as well.

**Comment by tvolkert** [comment]
This affects all animated_placeholder_perf benchmarks.

**Comment by tvolkert** [comment]
This was only two engine rolls ago - I'm gonna pause the engine auto-roller

**Comment by tvolkert** [comment]
FYI @cbracken the auto-roller is currently paused.  I'm gonna revert the offending engine roll

**Comment by cbracken** [comment]
@chinmaygarde and @liyuqian have been assigned to bisect this. Right now that roll is almost entirely skia rolls but https://github.com/flutter/engine/pull/16545 is in there which is a distinct possibility.

**Comment by cbracken** [comment]
@tvolkert just to be clear you're reverting both the offending roll and the one after it I assume?

**Comment by tvolkert** [comment]
@cbracken yes

**Comment by tvolkert** [comment]
The revert has landed, so removing the TODAY label to unblock dev roll.  Adding customer:blocker label to make sure this remains high priority until we turn back on auto-rolls.

**Comment by tvolkert** [comment]
Looks like this same engine roll also caused flutter_gallery__transition_perf to regress.

![dYqWqruyUxP](https://user-images.githubusercontent.com/15253456/75707115-321d5900-5c73-11ea-8d6f-fc67d24972ba.png)

**Comment by cbracken** [comment]
Reassigned to myself so I remember to check that the revert in #16889 landed.

**Comment by cbracken** [comment]
This has been reverted.

**Comment by tvolkert** [comment]
This was fixed by the revert, but then immediately re-introduced by https://github.com/flutter/flutter/pull/51792

**Comment by tvolkert** [comment]
![a0yvc11HHcV](https://user-images.githubusercontent.com/15253456/75733971-893f2000-5cab-11ea-93a2-2078c20f185e.png)

**Comment by cbracken** [comment]
Fixed in https://github.com/flutter/flutter/pull/51813
