### ISSUE TITLE
Load gif animation multiple times, not play from the first frame

### ISSUE THREAD

**Issue by peasfarmer** [flutter/flutter#51775]
## description

1. load a gif file like this: AssetImage("xx.gif")
2.this time the gif play start from the first frame
3.the widget disposed, and load again, this time the gif don't start from the first frame.

This problem is more obvious when using gif on  banner swiper

## my analysis
I had read the flutter code about image load, I guess it is maybe caused by flutter cached the codec of the image, and the codec object include current frame information.

and i solve this problem by call codec.getNextFrame() proper times, set the current frame point to the last frame.But this is not too stable, because codec does not export an interface for get the current potion.

## I hope
I want to start from the first frame every time I play a gif

```
flutter --version
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by dnfield** [comment]
When you are loading the gif the second time, you're getting a cached version.  Sounds like we need to somehow make sure to give you frame one when you pull it from the cache.

**Comment by darshankawar** [comment]
Hi @peasfarmer,
Can you confirm if you still experience this issue on latest Stable version (1.20.2) ?
Thanks.

**Comment by peasfarmer** [comment]
@darshankawar 
Thank you for solving this problem, I will test this problem in these two days.

**Comment by peasfarmer** [comment]
Unfortunately, I found that it didn’t work. I have upgraded to 1.20.2 and wrote a demo. The demo loads a Swiper, There are 5 gifs in the swiper,each gif counts down from 25, first frame is show 25. In the first round, they all start from 25, but when the second round started it was wrong.and i print log found the gif widget had call dispose.

I don’t know if my test method is wrong, I look forward to your reply



<img width="527" alt="version" src="https://user-images.githubusercontent.com/9895798/91326543-0a104c00-e7f7-11ea-8759-44ba09c680a4.png">

[Screenrecord.mp4.zip](https://github.com/flutter/flutter/files/5130980/1598456819089053.mp4.zip)

[flutter_gif.zip](https://github.com/flutter/flutter/files/5130986/flutter_gif.zip)

**Comment by dnfield** [comment]
I'm going to close this as WAI.

You can avoid caching this image when you dispose as follows:

```dart
  AssetImage image;

  @override
  void initState() {
    super.initState();
    image = AssetImage(widget.asset);
    print('${widget.asset} initState');
  }

  @override
  void dispose() {
    print('${widget.asset} dispose');
    image.evict();
    super.dispose();
  }
```

And then use the `image` property instead of creating a new `AssetImage` in each build.

**Comment by peasfarmer** [comment]
@dnfield 

think you,this problem solved.
