### ISSUE TITLE
backdrop_filter_perf_ios__timeline_summary 90th_percentile_frame_rasterizer_time_millis  is bimodal

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#51786]
![g4HD18g31sz](https://user-images.githubusercontent.com/15253456/75705993-51b38200-5c71-11ea-8adc-b2c1c9470d8e.png)

@godofredoc are the poorly performing metrics tied to a particular host?

**Comment by digiter** [comment]
Triage: looks good now.
