### ISSUE TITLE
Feature request: specify a flexible width column for DataTable

### ISSUE THREAD

**Issue by shaynekellyii** [flutter/flutter#51799]
## Use case

Currently, the `DataTable` column widths aren't flexible unless you only have one column that contains only text:

```dart
if (dataColumnIndex == _onlyTextColumn) {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth(flex: 1.0);
} else {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth();
}
```

It would be nice to be able to specify a column of your choice to have flexible width.

## Proposal

Add a field like `flexibleColumnIndex` to `DataTable` that can be used to set the `IntrinsicColumnWidth` `flex` to 1.0 if the field is non-null.

I can put in a PR for this if this makes sense.

**Comment by lamnhan066** [comment]
Hi @Hixie, I would like to know your opinion on my idea for this problem. It works as expected on my side but I don't know how possible it is and if it has any side effects.

Create a new type:
```dart
typedef DataColumnWidthBuilder = TableColumnWidth? Function(int columnIndex);
```

Add a new parameter  to the `DataTable`:
```dart
DataTable({
  // ...
  this.columnWidthBuilder,
  // ...
});

// ...
final DataColumnWidthBuilder? columnWidthBuilder;
// ...
```

Modify this code from:

https://github.com/flutter/flutter/blob/572b1d7b0840508dd8f5e5c267748d7cceafae4e/packages/flutter/lib/src/material/data_table.dart#L1125-L1129

To:

```dart
final TableColumnWidth? tableColumnWidth = columnWidthBuilder?.call(displayColumnIndex);
if (tableColumnWidth != null) {
  tableColumns[displayColumnIndex] = tableColumnWidth;
} else {
  if (dataColumnIndex == _onlyTextColumn) {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth(flex: 1.0);
  } else {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth();
  }
}
```

Then we can use it like this to make it flexible for columns 0 and 1:

```dart
Table(
  columnWidthBuilder: (columnIndex) {
    if (columnIndex == 0 || columnIndex =- 1) {
      return const IntrinsicColumnWidth(flex: 1);
    }
    return null;
  },
  // ...
)

**Comment by Hixie** [comment]
At a glance I would probably make a custom ColumnWidth subclass rather than adding an API to DataTable et al. That minimizes the additional API surface internally, which minimizes the risk of introducing bugs. (Builders can be really tricky to get right because the semantics of when a builder should rebuild are not exactly obvious.)

**Comment by lamnhan066** [comment]
Hi @Hixie 

I don't know if I understand your idea correctly, but I have a new idea. Instead of adding a new API to the DataTable, I added a `columnWidth` to DataColumn so we can easily create a DataColumn subclass.

At first, I will add a `columnWidth` to DataColumn with a default `null` value to keep the old behavior.

```dart
@immutable
class DataColumn {
  /// Creates the configuration for a column of a [DataTable].
  const DataColumn({
    required this.label,
    this.columnWidth,
    this.tooltip,
    this.numeric = false,
    this.onSort,
    this.mouseCursor,
    this.headingRowAlignment,
  });

  // ...

  final TableColumnWidth? columnWidth;
}
```

Then, I modify the code to accept the new configuration from:
https://github.com/flutter/flutter/blob/572b1d7b0840508dd8f5e5c267748d7cceafae4e/packages/flutter/lib/src/material/data_table.dart#L1125-L1129

To:
```dart
if (column.columnWidth != null) {
  tableColumns[displayColumnIndex] = column.columnWidth!;
} else {
  if (dataColumnIndex == _onlyTextColumn) {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth(flex: 1.0);
  } else {
    tableColumns[displayColumnIndex] = const IntrinsicColumnWidth();
  }
}
```

So we can add a custom DataColumn like:

```dart
class FlexDataColumn extends DataColumn {
  const FlexDataColumn({
    required super.label,
    this.flex = 1.0,
    super.tooltip,
    super.numeric = false,
    super.onSort,
    super.mouseCursor,
    super.headingRowAlignment,
  });

  final double flex;

  @override
  TableColumnWidth? get columnWidth => FlexColumnWidth(flex);
}

class IntrinsicDataColumn extends DataColumn {
  const IntrinsicDataColumn({
    required super.label,
    this.flex,
    super.tooltip,
    super.numeric = false,
    super.onSort,
    super.mouseCursor,
    super.headingRowAlignment,
  });

  final double? flex;

  @override
  TableColumnWidth? get columnWidth => IntrinsicColumnWidth(flex: flex);
}
```

**Comment by Hixie** [comment]
Is there a reason we can't implement this by literally creating a `ColumnWidth` subclass?

**Comment by Hixie** [comment]
Sorry, by `ColumnWidth` I meant `TableColumnWidth`: https://main-api.flutter.dev/flutter/rendering/TableColumnWidth-class.html

**Comment by Hixie** [comment]
(It's possible I don't understand what you're trying to do.)

**Comment by lamnhan066** [comment]
If we use the `Table`, we can set the `TableColumnWidth` by using the `columnWidths` parameter. But in the `DataTable`, those parameter is taken by this:
https://github.com/flutter/flutter/blob/572b1d7b0840508dd8f5e5c267748d7cceafae4e/packages/flutter/lib/src/material/data_table.dart#L1183
This:
https://github.com/flutter/flutter/blob/572b1d7b0840508dd8f5e5c267748d7cceafae4e/packages/flutter/lib/src/material/data_table.dart#L1036
And this:
https://github.com/flutter/flutter/blob/572b1d7b0840508dd8f5e5c267748d7cceafae4e/packages/flutter/lib/src/material/data_table.dart#L1125-L1129
So we cannot modify the `columnWidths` without changing the code in the `DataTable`. Is there anything that I missed in the code to resolve this issue without changing it?

**Comment by Hixie** [comment]
Oh, I see. Thanks for the explanation, that makes more sense to me now. :-)

Should we just allow DataTable to be given the columnWidths directly, and have that override the default that it generates?

**Comment by lamnhan066** [comment]
I think we shouldn’t overwrite the `columnWidths` because we have a checkbox column that will be inserted into the Table if the `showCheckboxColumn` is true. So it becomes harder to control how the column width is implemented to avoid conflict between the new and the old DataTable.

Besides that, we already had the `DataColumn` to configure the columns, so we can configure the `columnWidth` easier if it’s here.

**Comment by Hixie** [comment]
I see, I better understand where you're coming from now.

Have you looked at adding a field on DataColumn that takes a TableColumnWidth, and then making the DataTable code use that if provided, and if not, falling back to what it currently does?

**Comment by lamnhan066** [comment]
@Hixie yes, that’s the flows I added.

**Comment by lamnhan066** [comment]
@Hixie 

The `FlexDataColumn` and `IntrinsicDataColumn` are optional subclasses. Those subclasses are extended from the `DataColumn`, which has the defaults `columnWidth = FlexColumnWidth()` and `columnWidth => IntrinsicColumnWidth()`. 

So instead of using:

```dart
DataTable(
  columns: [
    DataColumn(
      columnWidth: FlexDataColumn(3.0),
    ),
  ],
)
```

We can use:

```dart
DataTable(
  columns: [
    FlexDataColumn(flex: 3.0),
  ],
)
```

**Comment by Hixie** [comment]
That seems like a very minor advantage given the additional complexity it introduces (anyone searching for "DataColumn" will now also find these other classes and have to figure out how they work together before they can understand the API).

**Comment by lamnhan066** [comment]
Should I open a PR for it without implementing those subclasses?

**Comment by Hixie** [comment]
Worth a try!
