### ISSUE TITLE
Better ES localization for Material and Cupertino

### ISSUE THREAD

**Issue by JosepBove** [flutter/flutter#51794]
There are some improvements that can be applied to both cupertino and material localizations.

#### Cupertino improvements 

Changes that should be done in all the files starting as cupertino_es:

- `datePickerDateOrder` field should be changed from `mdy` to `dmy`

Changes that should be done only in cupertino_es.arb:

-  `selectAllButtonLabel` field should be changed from `Seleccionar todo` to `Seleccionar todos` 
-  `anteMeridiemAbbreviation` from `A.M` to `a.m`
-  `postMeridiemAbbreviation` from `P.M` to `p.m` 

#### Material improvements 

Changes that should be done in all the files starting as material_es:

- `remainingTextFieldCharacterCountZero` field should be changed from `TBD` to `No quedan caracteres`

Observation:

All the files have the exact field order but US, 419 and AR files are messy

cc/ @shihaohong

**Comment by shihaohong** [comment]
Great! I'll submit these change recommendations later this week and update here as I get more information. 

Please don't hesitate to check in if I fail to update here periodically -- There is no way to subscribe to whether or not the change was approved, so I'll need to be more proactive than usual to check in on the requests.

**Comment by shihaohong** [comment]
I just filed a request for all of the above. Oddly enough, the `datePickerDateOrder` seems to be appearing correctly on the system, but hasn't been updated in the `flutter/flutter` `es.arb` file yet. I'll  refresh the ARB files once the rest of the changes have been reviewed by the translators, and hopefully everything mentioned will be fixed. 

Thanks again for the help and recommendations!

**Comment by shihaohong** [comment]
Some of the translations have already been approved. I noticed some minor errors with the translations that were made (`a. m.` instead of `a.m.`) so I made another fix request. Once those are resolved, I'll likely do a translation dump of the latest material/cupertino translations.

**Comment by shihaohong** [comment]
I learned that `a. m.` is more correct in `es` :) Submitted a PR!
