### ISSUE TITLE
[Devicelab DIRT] Be able to recover remotely/automatically

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#51802]
We'd like to recover the devicelab remotely/automatically after an incident (e.g. power outage) or a problem with the device (e.g. system upgrade dialog).

- [x] Auto reboot Linux bots after a power outage.
- [x] Auto reboot Mac bots after a power outage.
- [x] Auto reboot Windows bots after a power outage.
- [x] Take a screenshot of an Android phone remotely.
- [x] Take a screenshot of an iPhone phone remotely.
- [x] Reboot an Android phone remotely.
- [x] Reboot an iPhone phone remotely.
- [x] Find out the IP address of a bot after rebooting.

**Comment by digiter** [comment]
How to record iPhone screen: https://www.cnet.com/how-to/how-to-record-your-iphones-screen-and-audio-using-a-mac/

**Comment by digiter** [comment]
Power settings of the NUC to auto reboot: **BIOS -> Power -> Secondary Power Settings -> After Power Failure = Power On**.

**Comment by digiter** [comment]
To take screenshots, I have tried running `adb exec-out screencap -p > screen.png` on Android testbeds, here're the results:
* Linux: [works](https://user-images.githubusercontent.com/6259181/76903528-6c821b00-685b-11ea-9ee7-254eaf827035.png)
* Mac: [failed](https://user-images.githubusercontent.com/6259181/76903665-ac490280-685b-11ea-9082-70239a25d9c0.png)
* Windows: cannot open the saved screen.png file.

/cc @godofredoc

**Comment by digiter** [comment]
Another command to take a screenshot of an iPhone: `idevicescreenshot`

**Comment by digiter** [comment]
Dismiss system dialog: clone the repo of https://github.com/digiter/infra-dialog then run the XCUITest in it.

**Comment by godofredoc** [comment]
Great news! a few questions:

Can we move the files to the cocoon project?
How long does it take to run?
Is it possible to integrate it as a health check?

**Comment by godofredoc** [comment]
By the way this is the command I've been using for detecting the active IPs:

fping -g 192.168.42.0/32 2>/dev/null | grep 'is alive' | awk '{print $1}'

**Comment by digiter** [comment]
1. Yes, it can be checked into cocoon, it would be nice if we could reduce boiler plates.
2. A few seconds.
3. I'm asking that in https://github.com/flutter/flutter/issues/54792

**Comment by digiter** [comment]
I have updated the devicelab playbook.
