### ISSUE TITLE
Support branching for flutter repo

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#51807]
To support Flutter to be a branch based build, test and release process, both cocoon backend and frontend need to be updated.

Backend will support branch property in `commit` model, and also support branch matching to pre-defined regular expressions.

Following backend changes

- [x] basic support (https://github.com/flutter/cocoon/pull/658)
- [x] list commits based on branches, and update indexes for checklists to use the the branch (https://github.com/flutter/cocoon/pull/668)
- [x] Use both branch and SHA for commit Key (https://github.com/flutter/cocoon/pull/684)
- [x] create /api/branches to return available branches (https://github.com/flutter/cocoon/pull/682)
- [x] calculate tree status based on branches (https://github.com/flutter/cocoon/pull/679)
- [x] calculate cirrus task status based on branches (https://github.com/flutter/cocoon/pull/688)
- [x] update reserve-task API to pick tasks regardless of branch (https://github.com/flutter/cocoon/pull/695)
- [x] push build status to github for all branches (https://github.com/flutter/cocoon/pull/702)
- [ ] push gold status to github for all branches (requires support from Gold for branching)
- [x] refresh chromebot status for all branches (https://github.com/flutter/cocoon/pull/720)

Following frontend changes - Build page
- [X] query branches from backend (https://github.com/flutter/cocoon/pull/686)
- [X] update build state to track branches (https://github.com/flutter/cocoon/pull/693)
- [X] pass build state branches to cocoon server for fetching commit statuses (https://github.com/flutter/cocoon/pull/693)
- [X] update branches method in flutter build state to change branch (https://github.com/flutter/cocoon/pull/700)
- [X] add dropdown to build dashboard to interacting with the branches on build state (https://github.com/flutter/cocoon/pull/700)

Following frontend changes - performance page
- [x] update `Branch` property in entity `TimeseriesValue`
- [x] add branch support on dashboard (https://github.com/flutter/cocoon/pull/751)
- [x] add branch when querying historical data (https://github.com/flutter/cocoon/pull/752)
- [x] append prior `master` data to release branch for benchmark dashboard (https://github.com/flutter/cocoon/pull/753)

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/658 focuses on the backend part.

**Comment by christopherfujino** [comment]
Linking here https://github.com/flutter/flutter/issues/51884

**Comment by keyonghan** [comment]
- [ ] list commits based on branches

 is done via https://github.com/flutter/cocoon/pull/668

**Comment by keyonghan** [comment]
@CaseyHillers I have finished parts of the backend. do you mind implementing the frontend part? please let me know if you need anything or find any problems.

**Comment by CaseyHillers** [comment]
@keyonghan this still requires a call that can return the current branches to the frontend.

Such as calling `/api/public/get-branches` would return a json version of `List<String>` like `["master", "stable", "beta", "dev", "v0.0.1"]` etc so the frontend can show these branches.

**Comment by Piinks** [comment]
I've added mention of Gold and branching above, I'll also open and link an individual issue around branching support for goldens.

**Comment by CaseyHillers** [comment]
I've updated the frontend changes with the specific steps left to get branching supported.

**Comment by keyonghan** [comment]
Marking this as solved.
