### ISSUE TITLE
iOS apps on OpenGL can sometimes get blocked while rendering frames

### ISSUE THREAD

**Issue by flar** [flutter/flutter#51809]
Normally the engine wakes up every hardware frame cycle and asks the dart code to make a new scene and then hands the scene off to a GPU thread to rasterize and then waits for the next vsync to do the cycle again.

Sometimes, when the engine goes to rasterize the scene, it will get blocked in an OpenGL call and won't resume work until the next vsync happens - putting the rendering behind by a frame. Usually this results in the same thing happening to the next frame, over and over so the app will then always be an extra frame behind.

This is likely due to overusing some iOS frame-related resource, but we haven't been able to find a simple way to avoid that. It doesn't seem to happen if an app is quietly doing an animation, but any system noise can trigger the symptom which will persist until some other external influence knocks the frame pumping loop out of it again.

**Comment by liyuqian** [comment]
FYI, https://github.com/flutter/engine/pull/16175 is the change that would reveal this problem.

**Comment by chinmaygarde** [comment]
From our conversations, I understood that this was a pathology in the OpenGL driver that should not be an issue now that we have switched to Metal. If am not sure this happen on older iOS devices where Apple does not emulate OpenGL with Metal under the hood. Assigning P6  for triage.

**Comment by jonahwilliams** [comment]
No more OpenGL on iOS!
