### ISSUE TITLE
Flutter doctor links to an obsolete URL

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#51815]
```
  ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
```
Unfortunately
`https://flutter.dev/setup/#android-setup` doesn't contain an android-setup section anymore.

**Comment by Dmitry-Borodin** [comment]
https://flutter.dev/setup/#android-setup redirects to https://flutter.dev/docs/get-started/install#android-setup and looks shorter. 
Do we want to update url to avoid redirection?

**Comment by jacob314** [comment]
The redirection is ok. My concern is that the webpage doesn't seem like it actually has an `#android-setup` instruction.

**Comment by Dmitry-Borodin** [comment]
@jacob314 after selecting operation system I do see setup instructions. Are there other pages, explaining setup better?

**Comment by jacob314** [comment]
After you select your OS, the `#android-setup` query fragment gets lost and you have to scroll down to find that section.
It would be great if Flutter tool added the platform which it knows when generating platform specific documentation urls.
`https://flutter.dev/docs/get-started/install/linux#android-setup`
