### ISSUE TITLE
Flutter Web mouseover hover effect causes unexpected boxes to appear over content.

### ISSUE THREAD

**Issue by aawhitfield** [flutter/flutter#51819]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
The layout as expected.
**Actual results:** 
Dark colored boxes that appeared when the mouse hovered over different regions of the screen (e.g., the toggle switches or the navigation tabs).
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
<img width="720" alt="example 1" src="https://user-images.githubusercontent.com/7103590/75741630-096f8080-5cc0-11ea-852a-12c29d779df1.PNG">
<img width="318" alt="example 2" src="https://user-images.githubusercontent.com/7103590/75741632-0b394400-5cc0-11ea-8f1e-a0db2e10c7b8.PNG">

**Comment by TahaTesser** [comment]
Hi @aawhitfield 
Can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @aawhitfield 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
