### ISSUE TITLE
Inconsistent AppBar color naming

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#51820]
The `AppBar` has a property called `backgroundColor`, but the `AppBarTheme` only has `color`, they appear to be the same as `backgroundColor` docs point out that it would be `AppBarTheme.color` if `backgroundColor` is null. 

I suggest that `AppBarTheme.color` be renamed to `AppBarTheme.backgroundColor` for the sake of consistency.

**Comment by dfmiller** [comment]
How about Card.color, PopupMenuButton.color, FlatButton.color, OutlineButton.color, RaisedButton.color etc?

**Comment by feinstein** [comment]
IMHO if there's just one color in the `Widget`, than `color` is sufficient, but it there are more, then we need `backgroundColor`, `foregroundColor` and their specific themes should reflect the same naming.
