### ISSUE TITLE
flutter pub global run webdev build 

### ISSUE THREAD

**Issue by afunnyrainman** [flutter/flutter#51835]
When I run “flutter pub global run webdev build ”  pub finished with exit code 1 
Dart file web/main.dart compiled to JavaScript: web/main.dart.js
[INFO] Running build completed, took 35.2s
[INFO] Caching finalized dependency graph completed, took 257ms
[SEVERE] Unable to create merged directory at build.
Choose a different directory or delete the contents of that directory.
[SEVERE] FailureType: 73
[SEVERE] Unable to create merged directory for build.
[SEVERE] Failed after 35.5s
pub finished with exit code 1

**Comment by TahaTesser** [comment]
Duplicate of [#47534](https://github.com/flutter/flutter/issues/47534)

**Comment by afunnyrainman** [comment]
what!

**Comment by afunnyrainman** [comment]
for Mac computer

**Comment by TahaTesser** [comment]
Hi @afunnyrainman 
Can you please explain in details what issue you're facing?
Are you trying to build for Web or Mac?
Please follow this  [guide](https://flutter.dev/desktop#build) for Mac
Please follow this [guide](https://flutter.dev/docs/get-started/web#build) for Web

If this doesn't resolves your issue, can you please provide your `flutter doctor -v` ?
Thank you

**Comment by afunnyrainman** [comment]
flutter-web项目debug可以运行，但是发布的时候出现此错误，使用的flutter pub global run webdev build命令，for Mac

**Comment by afunnyrainman** [comment]
Debugging of the flitter web project can be run, but this error occurs when publishing. Use the flitter pub global run webdev build command for Mac

**Comment by afunnyrainman** [comment]
![image](https://user-images.githubusercontent.com/22904462/75769522-49e30300-5d81-11ea-861f-7bad377217e9.png)

**Comment by TahaTesser** [comment]
Hi @afunnyrainman 
Please don't execute `flutter pub global run webdev build` 
Execute `flutter build web --verbose` for building for web 
can you please copy and paste your `flutter doctor -v` & ` `flutter build web --verbose` logs? 
Thank you

**Comment by afunnyrainman** [comment]
run  "flutter build web --verbose"?

**Comment by afunnyrainman** [comment]
localhost:flutter_app_web2 dengxiaoqing$ flutter build web --verbose
[  +29 ms] executing: [/Users/dengxiaoqing/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/dengxiaoqing/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +21 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.14.6-0-gfabeb2a16f
[  +10 ms] executing: [/Users/dengxiaoqing/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/dengxiaoqing/flutter/] git ls-remote --get-url
origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] executing: [/Users/dengxiaoqing/flutter/] git rev-parse --abbrev-ref
HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +6 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.5
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18F132
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +8 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[ +366 ms] Generating
/Users/dengxiaoqing/AndroidStudioProjects/flutter_app_web2/android/app/src/main/
java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +74 ms] "flutter web" took 581ms.
"build web" is not currently supported.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      BuildWebCommand.runCommand
(package:flutter_tools/src/commands/build_web.dart:54:7)
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:638:18)
#3      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:75:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#7      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by afunnyrainman** [comment]
localhost:flutter_app_web2 dengxiaoqing$ flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.14.6 at /Users/dengxiaoqing/flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dengxiaoqing/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio3.1.2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio3.0.1.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio3.1.2.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • BAC AL00 • B7EDU17829001366 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
localhost:flutter_app_web2 dengxiaoqing$

**Comment by TahaTesser** [comment]
Hi @afunnyrainman 
You need to enable web 
1. Execute `flutter config --enable-web`
2. Execute `flutter create .` to add web support in your existing app
3. Execute `flutter build web --verbose`

**Comment by afunnyrainman** [comment]
You have executed the fluent config -- enable Web, and you can run it in chrome

**Comment by afunnyrainman** [comment]
Thank you. The generation is successful, but the HTML opening is blank

**Comment by afunnyrainman** [comment]
build->web->index.html

**Comment by TahaTesser** [comment]
@afunnyrainman 
You need to host your build on GitHub pages, Codemagic or Firebase Hosting or anywhere else whnr you can host web application

**Comment by afunnyrainman** [comment]
thank you
