### ISSUE TITLE
[iOS] RawKeyboard isn't working

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#51843]
I would like to handle hardware keyboard events to manipulate UI, but RawKeyboard isn't working on iOS
Even gamepad controls isn't passed to it, but I've solved it with plugin
As of regular keyboard, I can't find a way to override keyCommands of FlutterViewController

**Comment by rostopira** [comment]
Oh well, I've wrote Objective-C extension, it works
```objc
@interface FlutterViewController (Keyboard)
-(NSArray<UIKeyCommand*>*) keyCommands;
@end

@implementation FlutterViewController (Keyboard)

-(NSArray<UIKeyCommand *>*) keyCommands {
    return @[[UIKeyCommand keyCommandWithInput:UIKeyInputUpArrow modifierFlags:0 action:@selector(sendUp)]];
};

-(void) sendUp {
    NSLog(@"UP");
}

@end
```

**Comment by neckaros** [comment]
> Oh well, I've wrote Objective-C extension, it works
> 
> ```objc
> @interface FlutterViewController (Keyboard)
> -(NSArray<UIKeyCommand*>*) keyCommands;
> @end
> 
> @implementation FlutterViewController (Keyboard)
> 
> -(NSArray<UIKeyCommand *>*) keyCommands {
>     return @[[UIKeyCommand keyCommandWithInput:UIKeyInputUpArrow modifierFlags:0 action:@selector(sendUp)]];
> };
> 
> -(void) sendUp {
>     NSLog(@"UP");
> }
> 
> @end
> ```
Interesting
How did you override flutterviewcontroller in your app?

**Comment by rostopira** [comment]
@neckaros not worth discovering objective-c) You can do the same with Swift extension like
This is working due to the fact, that every function and methods are virtual in Obj-C and Swift

**Comment by GaryQian** [comment]
cc @gspencergoog Would you know what might be going on here?

**Comment by gspencergoog** [comment]
Yes: we don't support iOS raw keyboard events yet. However, luckily, we have a helpful Flutter community: someone has recently implemented this, and I'm about to commit it.

See https://github.com/flutter/engine/pull/20972 and https://github.com/flutter/flutter/pull/65193.

It will only work for iOS 13.4 and later, since before that Apple didn't have any public API surface for receiving hardware key events (which is why we didn't support them).

**Comment by catalin-costea** [comment]
Hello, any news on the  iOS raw keyboard events support? I've seen some merge on master but on stable channel is still not working. Thank you.

**Comment by ddikman** [comment]
Anything that can be made to move this into stable?

**Comment by derrikf-spindance** [comment]
Has there been any movement on this?

**Comment by jmagman** [comment]
It looks like this should be working now per @gspencergoog's old comment, at least on > iOS 13.4 https://github.com/flutter/flutter/pull/65193.  If anyone is still seeing issues with raw keyboard events, please file a new issue and completely fill out the template with reproducible steps so we can take a look.  Thanks!
