### ISSUE TITLE
Previous and current flutter projects stopped working

### ISSUE THREAD

**Issue by michaelodafe** [flutter/flutter#51848]
Hello, Please I started Flutter September last year and took a big break and on my return all my flutter projects were showing me only one format of error and that was in the android folder.. The android build gradle file
the below screenshot contains what the error is (highlighted in red)

Please help me with a fix
![Screenshot (143)](https://user-images.githubusercontent.com/53467770/75783313-ab46aa00-5d60-11ea-9f32-91a653a51578.png)

**Comment by TahaTesser** [comment]
Hi @michaelodafe 
This is common for old projects

1. Execute `flutter pub cache repair`
2. Execute `flutter clean` 
3. Execute `flutter pub get`

Run your project, if the problem still exist
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 


Thank you

**Comment by michaelodafe** [comment]
Hello TahaTesser
I did the 3 executions and the problem still exist.

**The bellow is my flutter doctor**

C:\android\flutterprojects\magic-8-ball-flutter-master>flutter doctor -v
[√] Flutter (Channel stable, v1.7.8, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
    • Flutter version 1.7.8 at C:\android\flutter
    • Framework revision d51fd86cdb (9 months ago), 2019-06-21 22:31:55 -0400
    • Engine revision d004bcd4d6
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Michael Odafe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**And the below is my the verbose**
C:\android\flutterprojects\magic-8-ball-flutter-master>flutter run --verbose
[  +37 ms] executing: [C:\android\flutter\] git log -n 1 --pretty=format:%H
[ +104 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] d51fd86cdb486192e187ccdf6f02cb2a38273d8d
[        ] executing: [C:\android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +62 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.7.8-0-gd51fd86cd
[  +17 ms] executing: [C:\android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\android\flutter\] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [C:\android\flutter\] git rev-parse --abbrev-ref HEAD
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +286 ms] executing: C:\android\Sdk\platform-tools\adb.exe devices -l
[  +34 ms] Exit code 0 from: C:\android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[   +8 ms] No connected devices.
[  +11 ms] "flutter run" took 330ms.
[   +1 ms] "flutter run" took 330ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:284:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:462:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///C:/android/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by TahaTesser** [comment]
Hi @michaelodafe 

Can you please run it after connecting a device or emulator?

I noticed you have no devices attached
```
[ ] List of devices attached
[ +8 ms] No connected devices.
```
Thank you

**Comment by VladyslavBondarenko** [comment]
@michaelodafe 
I hope it solved the issue, closing.
Comment please it it's not so and I'll reopen
