### ISSUE TITLE
Default new flutter app template on Lenovo Chromebook S340 causes crash "signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)"

### ISSUE THREAD

**Issue by jamesncl** [flutter/flutter#51852]
Hi, I can't run ANY flutter app on a Lenovo Chromebook S340 in release mode.

I'm using:

- flutter v1.12.13+hotfix.8 (stable)
- the Lenovo Chromebook is running ChromeOS 79.0.3945.123 (official build) (64-bit) and Android 9 (R79-12607.82.0 release-keys)

I've tried having the Chromebook in developer mode and copying an APK to the device, and without developer mode and installing via the Google Play Store (internal test ring), and get the same crash. I've tried Powerwashing the Chromebook. I've updated ChromeOS to the latest version. I've tried putting Android Play Store into developer mode. I'm using the latest Android Studio and latest versions of Dart and Flutter plugins.

Steps to reproduce (developer mode):

- Using Android Studio new project wizard, create a new Flutter Application
- `flutter build apk --release`
- Copy APK to the Chromebook
- Install and attempt to run - it will crash immediately

Alternative steps to reproduce (non-developer mode):

- Using Android Studio new project wizard, create a new Flutter Application
- `flutter build appbundle`
- Deploy to Play Store
- Install from Play Store
- Attempt to run - it will crash immediately

The crash only occurs when the build is for release - a debug build does NOT cause the crash.

I can't figure out how to get any kind of crash dump out of Google Play, so the only clue I've managed to get is by clicking on the 'Feedback' button on the crash dialog, and manually viewing the System Logs in the crash log attachments. I can't event copy-and-paste, so I've hand-copied the following:

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
ABI: 'x86_64'
Cause: null pointer dereference
… some memory addresses
backtrace:
#00 pc 00000000000000059f0 /data/app/example.com-OcwNnnTfRbuxoDNpE4yPhq==/ split_config.x86_64.apk (offset 0x30000)
```

If more detailed error report would be useful, please let me know how I can get the dump off the Chromebook - I've tried sending the crash report via the Feedback dialog, but nothing shows up in my Play Console under Android Vitals -> Crashes.

There are similar issues, but none exactly the same - and because a SIGSEGV can have numerous causes which are very hard to trace, I thought I should open a separate issue.

Related issues:
[#31942 Flutter crashes when pressing the Escape key on a Lenovo Yoga Chromebook](https://github.com/flutter/flutter/issues/31942) - this is a different model of Chromebook and the app seems to startup okay - in my case, the app doesn't even start
[#31424 Flutter on Chromebook crash: i965_dri.so](https://github.com/flutter/flutter/issues/31424) Very similar but the backtrace is different
[#13924](https://github.com/flutter/flutter/issues/13924) [#13925](https://github.com/flutter/flutter/issues/13925) and [#13926
](https://github.com/flutter/flutter/issues/13926) but both are closed because they weren't reproducible (this is reproducible)

If someone else has a Lenovo Chromebook S340 can you please try reproducing this, so I know it isn't just me - it's driving me absolutely nuts, and it's completely blocked my work. I need this to work for a customer who has this model of Chromebook, and I can't force them to put theirs into developer mode to run debug builds. I don't have any other chromebooks to try. Please help!

```
flutter doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at D:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\james\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available
```

**Comment by jamesncl** [comment]
I've just tried a brand new project and still getting this crash. I've tried changing the signing keys, targeting different versions of android, using `--no-shrink` on build, nothing seems to help. I did manage to get the tombstone file but it's too big to post in this comment. Here's the first few lines:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/octopus/octopus_cheets:9/R79-12607.82.0/6113486:user/release-keys'
Revision: '0'
ABI: 'x86_64'
pid: 5601, tid: 5617, name: 1.ui  >>> com.testlenovocrash.hcp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    rax 0000789446a07071  rbx 0000000000000001  rcx 0000789455d51800  rdx 0000789455d50698
    r8  0000000000000000  r9  0000789455d51878  r10 0000789445a00169  r11 0000000000000009
    r12 0000789455d50728  r13 0000789447d9f7b0  r14 0000789455d51878  r15 0000789447da28c8
    rdi 0000789455d507d8  rsi 0000789455d50728
    rbp 00007894474dda88  rsp 00007894474dd988  rip 0000789446dad9f0

backtrace:
    #00 pc 00000000000059f0  /data/app/com.testlenovocrash.hcp-EcuFGRNp3U-EzxQKjTzgBw==/split_config.x86_64.apk (offset 0x3000)

stack:
         00007894474dd908  000078945c28fc00  [anon:libc_malloc]
         00007894474dd910  fffffffffffffffc
         00007894474dd918  000078945c133a88  [anon:libc_malloc]
         00007894474dd920  0000000000000004
         00007894474dd928  00007894dcf982f5  /system/lib64/libc.so (je_arena_tcache_fill_small+613)
         00007894474dd930  000078945c133a88  [anon:libc_malloc]
         00007894474dd938  000078945c28fc00  [anon:libc_malloc]
         00007894474dd940  0000000000000150
         00007894474dd948  00007894dcffbf08  [anon:.bss]
         00007894474dd950  000078945c2906d0  [anon:libc_malloc]
         00007894474dd958  00007894474ddb38  <anonymous:00007894473e3000>
         00007894474dd960  00007894dcffbf00  [anon:.bss]
         00007894474dd968  000078945c0ed868  [anon:libc_malloc]
         00007894474dd970  000078945c133a80  [anon:libc_malloc]
         00007894474dd978  0000000000000002
         00007894474dd980  00007894474dd9d0  <anonymous:00007894473e3000>
    #00  00007894474dd988  0000789446a07071  <anonymous:0000789446a00000>
         00007894474dd990  0000000000000003
         00007894474dd998  0000789446a05b71  <anonymous:0000789446a00000>
         00007894474dd9a0  0000789455d51800  [anon:libc_malloc]
         00007894474dd9a8  0000789455d50728  [anon:libc_malloc]
         00007894474dd9b0  0000789455d507d8  [anon:libc_malloc]
         00007894474dd9b8  0000789455d50728  [anon:libc_malloc]
         00007894474dd9c0  0000789447d9f7b0  /data/app/com.testlenovocrash.hcp-EcuFGRNp3U-EzxQKjTzgBw==/split_config.x86_64.apk
         00007894474dd9c8  0000789446dad940  /data/app/com.testlenovocrash.hcp-EcuFGRNp3U-EzxQKjTzgBw==/split_config.x86_64.apk
         00007894474dd9d0  0000789447da28c8  /data/app/com.testlenovocrash.hcp-EcuFGRNp3U-EzxQKjTzgBw==/split_config.x86_64.apk
         00007894474dd9d8  d8bfc0c2ce63c0c2
         00007894474dd9e0  c2c0ce6bb1d7c057
         00007894474dd9e8  cf07c0c2c0ce72c0
         00007894474dd9f0  c0c2c0cf17c0c2c0
         00007894474dd9f8  0000000000004000
         00007894474dda00  0000000000004000
```

**Comment by jamesncl** [comment]
I've also just tried the exact same apps on an HP Chromebook 14 and there is no crash, so this seems to be specific to the Lenovo S340.

**Comment by darshankawar** [comment]
@jamesncl 
Is this still a valid issue using latest Flutter version or has this been resolved ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
