### ISSUE TITLE
`flutter run` should not install or leave the app behind

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5185]
The actual user issue: `flutter run` can leave a version of the app on the device. That version may or may not be the same version that was last launched/run. Users get confused about what version is on the device. This confusion issue will compound once hot reload becomes more common.

To avoid confusion about which version of the app is left on the device, we discussed changing the behavior of `flutter run`. Instead of installing and launching, we believe `flutter run` should only launch/run on the device.

After `flutter run`, if the user quits the app, no launcher icon remains.

If a user wants to install the app, they can use `flutter install`.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by sethladd** [comment]
Just ran into this today. :/ Can chalk this up to user error, but I was surprised in a meeting to find that when I tapped the Flutter icon, that I got the "flutter debug" white screen.

Definitely up to the user (i.e. _me_) to remember to do a `flutter install`. In the meantime, ideally we're not leaving an app launcher icon on the device from `flutter run`.

Thanks!

**Comment by eseidelGoogle** [comment]
Can this not be closed?  We could make `flutter run` clean up/remove the app on exit, but that seems of pretty minimal import.  Both Android Studio and Xcode leave the apps around last I knew?

**Comment by Hixie** [comment]
`flutter run` shouldn't install an icon into the app list in the first place.

**Comment by mit-mit** [comment]
If we don't install an icon in the app list, how does the user delete the app?

**Comment by Hixie** [comment]
From settings > apps.

**Comment by Hixie** [comment]
I'm going to close this. It's not clear what the solution is. It's not unusual for other systems to do this too (though we're particularly egregious with long hot reload sessions). If anyone has a concrete idea of what to do, please file a separate bug (or PR!).
