### ISSUE TITLE
Flutter app fails on iOS 10.3 iPhone5 simulator

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#51858]
Hey there,
I have my app running just well on `Fluter 1.9.1+hotfix.6` and I decided to move it to `Flutter 1.12.13+hotfix.8`.
I have build it and release it w/o any issues for Android. 
When I move to iOS, I successfully tested for iOS 13.3, however, I discovered an issue for iOS 10.3.
This is the error I have got in the console output:

> 	    PackageType = Developer;
> 	    SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot";
> 	    SimulatorUserPath = "/Users/angel/Library/Developer/CoreSimulator/Devices/72DAB833-425C-4F6D-B78E-D0EFC2F602E3/data";
> 	}
> 	state->old_bundle: /Users/angel/Library/Developer/CoreSimulator/Devices/72DAB833-425C-4F6D-B78E-D0EFC2F602E3/data/Containers/Bundle/Application/34260913-89FC-41BC-916E-B131D4053E23/Runner.app
> 	state->new_bundle: /Users/angel/Projects/biorhythms/build/ios/iphonesimulator/Runner.app
> 	state->dst_bundle: /Users/angel/Library/Developer/CoreSimulator/Devices/72DAB833-425C-4F6D-B78E-D0EFC2F602E3/data/Library/Caches/com.apple.mobile.installd.staging/temp.yV94kQ/extracted/Payload//Runner.app, binaryDiff flag: FALSE
> 		dst_ipa: /Users/angel/Library/Developer/CoreSimulator/Devices/72DAB833-425C-4F6D-B78E-D0EFC2F602E3/data/Library/Caches/com.apple.mobile.installd.staging/temp.yV94kQ/extracted
> 	    CFBundleIdentifier = "net.sensortronic.biorhythms";
> 	    PackageType = Developer;
> 	    SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot";
> 	    SimulatorUserPath = "/Users/angel/Library/Developer/CoreSimulator/Devices/72DAB833-425C-4F6D-B78E-D0EFC2F602E3/data";
> 	})
> 	    arguments =     (
> 	        "--enable-dart-profiling",
> 	        "--enable-checked-mode",
> 	        "--verify-entry-points",
> 	        "--start-paused",
> 	        "--observatory-port=0"
> 	    );
> 	    environment =     {
> 	    };
> 	}
> 		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
> 		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
> 		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
> 		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
> 	Simulator booted at: 2020-03-03 15:55:38 +0000
> 	Current time: 2020-03-03 16:02:46 +0000
> 	Within boot leeway: NO
> Mar  3 18:02:46 Angels-Mac com.apple.CoreSimulator.SimDevice.72DAB833-425C-4F6D-B78E-D0EFC2F602E3[7430] (UIKitApplication:net.sensortronic.biorhythms[0xf36e][7451][9359]): Program specified by service does not contain one of the requested architectures:
> 	    description = "The request to open "net.sensortronic.biorhythms" failed.";
> 	    failureReason = "The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.";
> 	    underlyingError = <NSError: 0x7b6143b0; domain: FBSOpenApplicationErrorDomain; code: 1 (Unspecified)> {
> 	        description = "The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)";
> 	    };
> 	}
> ProcessException: Process exited abnormally:
> net.sensortronic.biorhythms: -1
> 
> An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> The request to open "net.sensortronic.biorhythms" failed.
> The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
> Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
> 	The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
>   Command: /usr/bin/xcrun simctl launch 72DAB833-425C-4F6D-B78E-D0EFC2F602E3 net.sensortronic.biorhythms --enable-dart-profiling --enable-checked-mode --verify-entry-points --start-paused --observatory-port=0
> Error launching application on iPhone 5.
> Exited (sigterm)

and this is my `flutter doctor -v` output:

> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G1012, locale en-GB)
>     • Flutter version 1.12.13+hotfix.8 at /Users/angel/development/flutter
>     • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C504
>     • CocoaPods version 1.8.4
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
> 
> [✓] VS Code (version 1.42.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.8.1
> 
> [✓] Connected device (1 available)
>     • iPhone 5 • 72DAB833-425C-4F6D-B78E-D0EFC2F602E3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)
> 
> ! Doctor found issues in 2 categories.
>

**Comment by VladyslavBondarenko** [comment]
Hi @angel1st 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/48788,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
