### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark hotReloadMillisecondsToFrame and hotReloadMillisecondsToFrameAfterChange regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51861]
Looks like it started with https://github.com/flutter/flutter/pull/51693. hotReloadMillisecondsToFrame began its regression a little earlier, at https://github.com/flutter/flutter/pull/51602, which seems unlikely.

![Screenshot 2020-03-03 at 08 28 18](https://user-images.githubusercontent.com/1435716/75796769-fba21580-5d28-11ea-8c6d-92989a61c27d.png)

**Comment by digiter** [comment]
FYI, I restarted mac12 with attached device today, see if that helps.

**Comment by shihaohong** [comment]
I'm going to try and merge an innocuous documentation fix https://github.com/flutter/flutter/pull/51871 and see if the benchmarks return to normal after that

**Comment by shihaohong** [comment]
![image](https://user-images.githubusercontent.com/27032613/75811525-6e1eef80-5d41-11ea-9816-506f75e8aae2.png)

One of the benchmarks has returned back to normal after restarting the device and landing a doc fix change to test, whereas the other one is much closer to the value it was prior to the spike, although still above the benchmark.

**Comment by cbracken** [comment]
Two more commits down the road:
![image](https://user-images.githubusercontent.com/351029/75816997-0e2d4680-5d4b-11ea-8aa1-ac7ae6c67852.png)
Looks like the `hotReloadMillisecondsToFrame` benchmark returned to previous levels, `hotReloadMillisecondsToFrameAfterChange` has improved a little, but still not back to green.

**Comment by cbracken** [comment]
Assigning to @shihaohong (either for the fix or for triage to the appropriate person.

**Comment by shihaohong** [comment]
3 commits down and it's back to green, baseline levels (I hovered over the green lines, somehow the second-to-last one is showing up second-to-last even though it has a later timestamp):

![image](https://user-images.githubusercontent.com/27032613/75817450-f3a79d00-5d4b-11ea-98e3-2dc1da891957.png)

@cbracken Any ideas on what we do in this case? I'm not entirely sure what the protocol for this is

**Comment by shihaohong** [comment]
![image](https://user-images.githubusercontent.com/27032613/75825289-e7c2d780-5d59-11ea-91e9-fa3db75c054c.png)

I decided to wait on a few more commits and it seems the benchmark has stabilized. I'll close the issue.
