### ISSUE TITLE
web_benchmarks_canvaskit_draw_rect.canvaskit.averageDrawFrameDuration may have regressed; is noisy

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51862]
Most clearly around https://github.com/flutter/flutter/pull/51602, which really doesn't seem to be the issue.

![Screenshot 2020-03-03 at 08 31 33](https://user-images.githubusercontent.com/1435716/75797159-97cc1c80-5d29-11ea-9e5b-609558b35abe.png)

I'm applying the TODAY label as it's our rubric, but if others don't agree that it should block rolls, I'm fine dropping the label.

**Comment by ferhatb** [comment]
back to normal watching, will keep open but removing TODAY.

**Comment by yjbanov** [comment]
Retriaged the issue. We do plan to address the noise in the benchmarks. It's somewhat a P2 this quarter though.

**Comment by yjbanov** [comment]
We've reduce the noise a lot lately (although we'll never be down to zero). I'll consider this fixed.
