### ISSUE TITLE
error building flutter apk with thumbnails and share 

### ISSUE THREAD

**Issue by Basheer20** [flutter/flutter#51869]
hi, after i upgrade flutter sdk  and  I am trying to release my flutter apk , i got this error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':thumbnails:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\basheer\.gradle\caches\transforms-2\files-2.1\a599ce8153ae5fd666987fb0e6bf53a6\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\basheer\.gradle\caches\transforms-2\files-2.1\a599ce8153ae5fd666987fb0e6bf53a6\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan 
to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':share:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\basheer\.gradle\caches\transforms-2\files-2.1\a599ce8153ae5fd666987fb0e6bf53a6\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\basheer\.gradle\caches\transforms-2\files-2.1\a599ce8153ae5fd666987fb0e6bf53a6\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan 
to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 16s

flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed       
      instructions.
[!] Android Studio (not installed)
[√] VS Code (version 1.42.1)
[!] Connected device
    ! No devices available

! 

i tried 
flutter clean 
flutter pub cash repair 
but they didnt work

can you help guys?
Thanks😘

**Comment by ggichure** [comment]
i found a possible solution an issue check it out. here https://github.com/flutter/flutter/issues/32595#issuecomment-491639786

**Comment by TahaTesser** [comment]
Hi @Basheer20 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you

**Comment by dheeraj2dj** [comment]
am having the same issue. Any luck on how to resolve this? I have observed this happening only on Redmi Note 8 pro as of now. Working fine on Samsung though.
