### ISSUE TITLE
"Isolate creation error: (null)" when building --release for Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5186]
Using the latest master, trying to build for Android from my Mac:

```
^C~/Code/flutter/examples/flutter_gallery[master] $ flutter run --release
Building APK in release mode (android-arm-release)...      
Warning: signing the APK using the debug keystore.
Built build/app.apk (31.8MB).
Running lib/main.dart on Nexus 5X...
--------- beginning of main
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
E/DartVM  : vm-service: Isolate creation error: (null)
```

FWIW the app startup seemingly normal.

**Comment by sethladd** [comment]
cc @a-siva

**Comment by johnmccutchan** [comment]
In release mode this message should not be displayed. We expect no service isolate.

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
We shouldn't even try to start the service isolate in these case.

**Comment by eseidelGoogle** [comment]
Just some code which needs a DART_PRODUCT_MODE guard presumably?

**Comment by johnmccutchan** [comment]
@rmacnak-google We try and start it because the standalone VM needs the service isolate in PRODUCT mode. My CL silences the error unless --trace-service is specified.

**Comment by sethladd** [comment]
Cool, thanks for the quick fix!
