### ISSUE TITLE
After upgrading my flutter SDK to the latest release am getting an error when running my app.

### ISSUE THREAD

**Issue by austinevick** [flutter/flutter#51867]
![ERwphsNX0AAMyI8](https://user-images.githubusercontent.com/51150248/75803090-22d70200-5d7e-11ea-9f86-3641735d4946.png)

**Comment by TahaTesser** [comment]
Hi @austinevick 
Could you please try this possible [solution](https://github.com/flutter/flutter/issues/39729#issuecomment-587667967)

Related to [#47452](https://github.com/flutter/flutter/issues/47452)
Thank you

**Comment by VladyslavBondarenko** [comment]
@austinevick 
I hope you solved the problem, 
closing since long time without a response.
comment please if it's not so and I will reopen the issue
Thank you
