### ISSUE TITLE
The getter was called on null

### ISSUE THREAD

**Issue by AmineAssali** [flutter/flutter#51878]
Hello every one , 

I want to display user data in a profile page , i retreive data from my localstorage ..
The problem is that the widget got build before receiving the profile data

any help ?
Thanks in advance.

![Screenshot_1583267328](https://user-images.githubusercontent.com/27303877/75816720-02b33d00-5d96-11ea-88c5-77e9a7e64744.png)

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
