### ISSUE TITLE
[webview_flutter] Allow to preload content into an off-screen webview

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#51875]
Internal bug: b/150442972

In customer:dream, we use webview_flutter to display web content in our application. We also like to animate the webview position on the screen and running into bad performance when two processes happen concurrently:  loading content into the webview (work on the Chromium side) and animating the webview positioning (building and rendering Flutter frames). The slowness mainly stems from elevated total CPU load.  That's b/146374961.

We managed to address the issue on CastOS platform by not using webview_flutter plugin and using platform APIs directly to create an off-screen Chromium renderer, load content into it while it is invisible and before running the Flutter animation (thus not showing visible glitches to the user). Then once Chromium reports the webview to be fully loaded we animate it onto the screen. That work happened within: b/149214004 and specifically cl/295589945.

Now the issue with our solution is that it only works on CastOS, but not on Android and this causes that a) on Android we don't reap the performance benefits (albeit expected to be smaller than on CastOS) and b) the preloading facility leaks to the application code (so each webview user needs to check whether they can or cannot preload content).

So here I am requesting a similar facility to pre-create an off-screen webview and preload content into it, but supported natively by webview_flutter.

I can imagine that a user would be able to create a WebViewController directly without rendering any widgets to create an offscreen webview. Then a user would be able to bind (pass) an existing controller instance to the WebView widget when the user wants to actually display it.

I don't know 100%, but I suspect that on Android one can call `new WebView()`, not add it as a child to any View and expect it to be usable to load content. This would allow the new API to be implemented on Android. Judging by StackOverflow there is a way to do something like this on iOS too, albeit uglier.

**Comment by mehmetf** [comment]
@amirh FYI

**Comment by tonyclickspace** [comment]
Same issue here, different implementation - we have a digital signage app that loads several webviews and swaps between them.
We'd like the ability to preload a WebView without having to add it to the Widget tree. Wrapping the webview in an Offstage or Visibility widget prevents the WebView from loading as well (as does a Transform with scale zero). Our terrible workaround is to size it down to a 1x1px and set opacity to zero.

**Comment by EitanSchwartz** [comment]
OP wrote: "I don't know 100%, but I suspect that on Android one can call new WebView(), not add it as a child to any View and expect it to be usable to load content.". Yes indeed, our current Android & iOS solutions preload content on our WebViews without any coupling to View hierarchy or rendering. [In this issue](https://github.com/flutter/flutter/issues/64402) I described the focal point of the whole problem as I understand it. I'll try to re-stress it here:

- You can only call loadUrl() from the WebViewController of the WebView.
- You only get the relevant WebViewController from the WebView's onWebViewCreated(controller) callback.
- I found that onWebViewCreated(controller) is only called after Flutter calls the Widget's build() method.

**Comment by enetor** [comment]
Internal bug 150442972 has been closed.

**Comment by jiahaog** [comment]
Internal bug 150442972 has been closed.

**Comment by lidongze91** [comment]
Internal bug 150442972 has been closed.

**Comment by mehmetf** [comment]
Internal bug 150442972 has been closed.

**Comment by mehmetf** [comment]
Internal bug 150442972 has been closed.

**Comment by chingjun** [comment]
Internal bug 150442972 has been closed.

**Comment by jiahaog** [comment]
This is no longer needed internally.

**Comment by jmgeffroy** [comment]
Hi @darshankawar, I have added a comment to [my other issue](https://github.com/flutter/flutter/issues/97483) since it might be slightly different.  In my case, it works on Android when using Virtual Displays. 
*For the other readers/contributors here*: in our case (an e-book reading app SDK), our webviews are placed inside a [PreloadPageView](https://pub.dev/packages/preload_page_view). We observe a correct behavior on Android when using Virtual Displays. The problem appears with Hybrid Composition. With HC, only the visible webview is loaded, the other ones are created but empty, never attached.

**Comment by krishaajtak** [comment]
Any workaround or solution to this?

**Comment by stuartmorgan** [comment]
This is supported in version 4; the native webview is bound to the control rather than a widget, so it doesn't have to be in the widget tree to be used.
