### ISSUE TITLE
Viewing licenses in Gallery has a long pause while going full view

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5187]
Tested on my iPhone, just built from master.

Open gallery, open drawer, tap into "about flutter", tap "view licenses".

Notice how there is a quick beginning to the transition, where you start to see the Licenses view start to appear from the background and start to fade in, and then a long pause, and then the license view screen quickly fully appears.

Video of the effect here: https://youtu.be/gBqj-xLiiek

Turn the time down to 0.25 and you can definitely see the effect:

![screen shot 2016-08-02 at 2 08 02 pm](https://cloud.githubusercontent.com/assets/5479/17345372/8bf68610-58ba-11e6-8ee9-78e191f5dd63.png)

Notice the beginning of the Licenses view appearing.

**Comment by sethladd** [comment]
cc @Hixie

**Comment by eseidelGoogle** [comment]
Might this be improved by @Hixie's fancy scrolling refactor?

**Comment by Hixie** [comment]
Probably not but we should fix it.

**Comment by Hixie** [comment]
This definitely still happens.

**Comment by Hixie** [comment]
Some work on this in https://github.com/flutter/flutter/pull/14160.

**Comment by Hixie** [comment]
The work in #14160 has reduced this to a single problem: reading a large string asset from a bundle is a blocking expensive operation.

**Comment by sethladd** [comment]
Thanks for the update!

**Comment by Hixie** [comment]
Ah, looks like the expensive part of reading the asset is actually the UTF-8 decoding. I can fix that in the framework too...

**Comment by sethladd** [comment]
For those following along, partially made possible by the new `compute` function: https://master-docs-flutter-io.firebaseapp.com/flutter/foundation/compute.html
