### ISSUE TITLE
[e2e] Use real textInput channels and http bindings instead of mocks

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#51885]
E2EWidgetsFlutterBinding is for now inherits mock text chanllel and http bindings from TestWidgetsFlutterBinding.

https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/binding.dart#L262

This issue is not blocking to web integration tests since test authors can use these 2 lines to clear the mocks:
SystemChannels.textInput.setMockMethodCallHandler(null);
 HttpOverrides.global = MyHttpOverrides();

On the other hand these changes are good to have before we enable e2e to a wider range of tests.

**Comment by dnfield** [comment]
I think, more generally, we should probably have the E2E bindings set _no_ mocks on the handlers. WDYT?

**Comment by dnfield** [comment]
One other item to address with this is overriding the Navigation channel, although that's non-web only.

**Comment by dnfield** [comment]
Related: https://github.com/flutter/flutter/issues/47180
