### ISSUE TITLE
Branching experiment made the Flutter build tree red

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#51884]
## What happened
1. Commit [1ba4f1f](https://github.com/flutter/flutter/commit/1ba4f1f509202f3d2ec16f053edcbe2df6b7107e) lands on master.
2. Cirrus triggers a [master branch build of commit 1ba4f1f](https://cirrus-ci.com/build/5707666349621248) which eventually goes green.
3. Test branch [v0.0.1](https://github.com/flutter/flutter/tree/v0.0.1) gets pushed to flutter/flutter with no new commits and HEAD at 1ba4f1f.
4. Cirrus triggers a [v0.0.1 branch build of commit 1ba4f1f](https://cirrus-ci.com/build/5756766147313664), which fails on (among other tests) [verify_binaries_codesigned-macos](https://cirrus-ci.com/task/5110280506048512), because this commit was never published to dev and thus never codesigned. Because [Flutter macOS engine binaries are not codesigned on master](https://github.com/flutter/flutter/issues/44372), this does not run if a PR is attempting to merge into master of if a commit is on master. Thus, the test ran on v0.0.1 branch, and failed.
5. The build dashboard queries the cirrus status for commit 1ba4f1f and pulls the status for the v0.0.1 branch build (which failed) rather than the build for master (which passed). ![build-dashboard-red-screenshot](https://user-images.githubusercontent.com/7856010/75820367-12f4f900-5d51-11ea-81dd-bbceca37cb78.png)

## Proposed solutions
1. Until engine binaries are codesigned on master, the `verify_binaries_codesigned-macos` cirrus test `only_if` logic should be updated to only run on branches that are expected to be codesigned (@christopherfujino can do this once release branch naming is solidified).
1. The flutter dashboard should not query cirrus jobs based solely on the commit revision hash, but also on the branch.

**Comment by godofredoc** [comment]
For 2) 
We need to pass the branch to the refresh_cirrus_handler:
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_cirrus_status.dart#L52

And modify the query to use the branch:
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_cirrus_status_queries.dart#L5

**Comment by tvolkert** [comment]
> `verify_binaries_codesigned-macos` cirrus test `only_if` logic should be updated to only run on branches that are expected to be codesigned

Yep.  This should only ever be `dev`, `beta`, and `stable`, since the release branches will be works in progress until they're tagged, and the corresponding non-release branch HEAD is updated.

**Comment by christopherfujino** [comment]
Another example of this occurred on March 10, when:

1. Commit https://github.com/flutter/flutter/commit/60d0fef17ae60b88cb52e6158bda2d91b600299c landed on master
1. Said commit was branched off of to form branch `flutter-0.0-candidate.1`
1. This triggered a new Cirrus job on commit 60d0fef, for the candidate branch
1. A new commit was pushed to the candidate branch, causing the previous Cirrus job to be canceled
1. The build dashboard picked up the wrong Cirrus job (the `flutter-0.0-candidate.1` branch version which was canceled) and made the tree red.

**Comment by keyonghan** [comment]
Does it trigger a new cirrus run on the commit whenever a new branch is created based on the commit where it is branched off? @christopherfujino @fkorotkov  @godofredoc 
If yes, that means we will have the same commit sha for both branches, and this will happen every time we create a new branch. Is this correct?

In this case, how is the record saved in the cirrus side? Are there two records for the two branches, or the second one will override the first? From https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L452, it seems to be the latter case? @fkorotkov

**Comment by fkorotkov** [comment]
There will be two builds for different branches with the same SHA. GraphQL will return both of the builds in that case.

**Comment by keyonghan** [comment]
Thank you @fkorotkov 
In this case, we need to have the ability to save duplicated commits with same SHA but different branches in datastore.
However, current `Checklist` is using only SHA as the key.
Created issue https://github.com/flutter/flutter/issues/52443 to track.

**Comment by keyonghan** [comment]
This issue should be resolved considering https://github.com/flutter/cocoon/pull/679, https://github.com/flutter/cocoon/pull/684, and https://github.com/flutter/cocoon/pull/688. Closing it now. Please feel free to reopen if it persists.

**Comment by christopherfujino** [comment]
Thanks @keyonghan!
