### ISSUE TITLE
Samsung keyboard composing region duplication on subset of devices

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#51893]
Extracted/continued from https://github.com/flutter/flutter/issues/31512

When typing, hiding and reshowing the keyboard and typing punctuation like `.` can cause the composing region to duplicate.

The original issue linked above impacted most Samsung devices. Since then, changes have landed that workaround the issue for most devices (https://github.com/flutter/engine/pull/16547 and https://github.com/flutter/engine/pull/15701). These workarounds have been confirmed to work on most devices.

However, it seems that a much smaller subset of devices are still seeing this bug even with the workaround, some with additional minor regressions in the form of the first letter sometimes repeating.

Devices confirmed to still exhibit the bug:

- Galaxy Tab A 10.1" SM-T510

Devices that may have the bug in some form:

- Galaxy S8 (based off [report](https://github.com/flutter/flutter/issues/31512#issuecomment-588175086) by @exptk3)
- J6+
- S9
- S9+

We have been in contact with Samsung to work on resolving this. See b/150639528

Please continue to report any specific models that are still experiencing the bug!

**Comment by MichelMelhem** [comment]
Hello,
I'm running a Samsung Tab S6 (SM T865) and i'm still running into text duplication issues. This issue occur to me when i'm trying to write down an email. Bellow you will be able to see a gif of the actual behavior : 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25546627/76145901-58d1fa00-608e-11ea-865f-a9c6c7e056d2.gif)


This issue is really problematic as it is impossible to production deploy any app as samsung devices are very popular.
Flutter doctor Output :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.19-pre.9, on Mac OS X 10.15.3 19D76, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

Thank you and i hope we will find a fix soon

**Comment by MichelMelhem** [comment]
@GaryQian

**Comment by escamoteur** [comment]
The Samsung Fold has the Problem too.

**Comment by MichelMelhem** [comment]
As a partial workaround just install Gboard on yoiry device and the problem will be fixed as the issue is just coming from the keyboard and not the os itself

**Comment by GaryQian** [comment]
@MichelMelhem Unfortunately, "installing a different keyboard" is not a solution to this. The problem in itself is that Samsung keyboards specifically are not working, and switching keyboards doesn't solve the problem for anyone other than one single end user. Thanks for the additional reports! Will be useful in continued work tackling this problem!

**Comment by zwells** [comment]
I can confirm still happening on Galaxy Tab A (SM-T380) with Flutter version 1.12.13+hotfix.8

**Comment by wkhaksar** [comment]
I can confirm still happening on J6 with Flutter version 1.12.13+hotfix.8

**Comment by TykanN** [comment]
Samsung S9, S9+ has same problem. I tested it on device.
Flutter version is 1.15.19-pre33

**Comment by leecommamichael** [comment]
I reproduced this with Samsung Galaxy S8 on Flutter Stable: 1.12.13+hotfix.8

**Comment by MichelMelhem** [comment]
Is there any update on the way to fix this issue ???

**Comment by sohe1l** [comment]
Facing similar issue on GalaxyS10e android 10.
- It seems that it happens more often while typing email.

**Comment by GaryQian** [comment]
I have landed https://github.com/flutter/engine/pull/17426 which seems to fix many of the bugs on my test devices. It would be great if others could confirm that this also fixes bugs for them.

Please try the change on master channel after it has rolled into the engine (it has not yet, I will update this comment when the change does roll in and is ready for testing).

**Comment by sohe1l** [comment]
I just tried and it is fixed for me. Thank you!
Is it safe to switch to master channel for an app in production?

**Comment by GaryQian** [comment]
We don't recommend it as there may be major bugs that we still have not caught, but every few days we roll to dev channel, which is still not recommended, but quite a bit safer than master. However, the final decision is still up to you to determine how important certain bugfixes are to include and which channel to use. As a rule of thumb, we try our best to keep master channel usable, and that succeeds a lot of the time, but there is no guarantee.

**Comment by sohe1l** [comment]
@GaryQian Thank you!

**Comment by exptk3** [comment]
[ Test divice : Galaxy s8 ]
[ Test sdk : Flutter Master Channel ]

*** Problems found in the last test
1. Time delay of the keyboard up and down
2. abnormal display of the keyboard even after the app is closed (on device home screen)
3. word duplication input
4. input line can not be changed during keyboard input

*** I tested it on the same device (Galaxy s8) as in the last bug report.
—> This time, during the test, the above problems were confirmed.
—> Results of test
3, 4 : resolved.
1,2 : not resolved.

The duplicate input problem, which was a major problem, did not appear, but the time delay occurred when the keyboard was hidden or visible.
It seems that there is no delay time at the beginning of input, but if it is more than 3 ~ 4 lines of text input, the longer the sentence, the longer the delay time.
--> The delay time increases by more than 10 seconds, the performance is difficult to use in a real app.

I hope you reproduce the above bugs on your Galaxy s8 device.

================================================

*** Log when Keyboard up
…
W/IInputConnectionWrapper(27651): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27651): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27651): getExtractedText on inactive InputConnection
So many times
…

*** Log when Keyboard down

D/ViewRootImpl@b02d8a6[MainActivity](27651): ViewPostIme pointer 0
D/ViewRootImpl@b02d8a6[MainActivity](27651): ViewPostIme pointer 1
D/InputMethodManager(27651): HSIFW - flag : 0 Pid : 27651

==================================================

Thank you.

**Comment by GaryQian** [comment]
I will close this for now, if anyone still sees this bug, please let me know and we can reopen this!

Thanks everyone for the patience given for this quite longstanding issue and the assistance provided in resolving it!

**Comment by dannyvalentesonos** [comment]
@GaryQian Thanks for all the hard work on this. Do you plan on looking into the 2 remaining issues @exptk3 mentioned in their post above? Is there a separate bug logged for that?

Thanks

**Comment by TykanN** [comment]
@GaryQian Great work! As mentioned by @dannyvalentesonos, there are two remaining issues.

Especially, I also confirmed "Time delay of the keyboard up and down" issue.
I tested more than 5 devices, It happened on only Galaxy Note 10, not Galaxy 9&9plus, iPhone X etc.
so I don't know whether it is flutter issue or device issue.

**Comment by GaryQian** [comment]
I'll go ahead and open a separate issue if one doesn't already exist. Those symptoms seem separate from the primary problems tracked in this bug.

**Comment by njovy** [comment]
@TykanN "Time delay of the keyboard up and down" issue happens on Galaxy 9 Plus as well. 
@GaryQian I am using 1.15.17 and the keyboard is almost not usuable in production due to delay. This issue never happened on 1.12.8.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/issues/54310 Is the new bug I filed for the remaining issues mentioned
