### ISSUE TITLE
[in_app_purchase] README should include instructions of calling `completePurchase`.

### ISSUE THREAD

**Issue by Yunhoo-Kim** [flutter/flutter#51902]
After upgrade in_app_purchase package 0.2.0 to 0.3.1, all Non consumable products are refunded after three days.
So I search why purchases are refunded.
And finally I got solution.

In Document of in_app_purchase, We should call completePurchase only iOS after purchased non consumable product.
But 0.3.1+1 completePurchase said, 

/// Warning! Failure to call this method and get a successful response within 3 days of the purchase will result a refund on Android.
  /// The [consumePurchase] acts as an implicit [completePurchase] on Android.

If you don't call completePurchase on android purchase, All of that are refunded after three day....

Flutter team have to write this warning on README!!!

**Comment by coolnalu** [comment]
Thanks, @VladyslavBondarenko. 

Unfortunately, I only found this issue after losing a few hundred bucks in revenue and dozens of paying users.

**Comment by shovelmn12** [comment]
Hey i have some issues with that as well.
For now i am calling completePurchase on iOS and consumePurchase on Android.
Should i call completePurchase on both ?
I am a bit lost with it can someone please explain?

**Comment by coolnalu** [comment]
@shovelmn12 calling completePurchase solved it for me

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/2739 added more documentation on `completePurchase`, it also added the `warning` to README. 
Closing the issue.

**Comment by JayM96** [comment]
@coolnalu Can you confirm that inapppurchase for subscription for completing a purchase requires completePurchase for ios and consumePurchase for android methods to call?

Or just completePurchase method will work for both android and ios?

**Comment by coolnalu** [comment]
@JayM96 in my case, my products were subscriptions and non-consumables, so `completePurchase` worked for both android and ios. 

I don't have a consumable product so I don't use consumePurchase - I imagine it's needed for consumable products.
