### ISSUE TITLE
Custome Live Stream UI

### ISSUE THREAD

**Issue by dwikresno** [flutter/flutter#51906]
to call stream from flutter i'm use invokeMethod('stream',antoherparam), but after i call that function it's only open new page and that's default page from flutter and i can't custom that page, can you make some documentation to custom that page?

![carbon](https://user-images.githubusercontent.com/16210858/75842139-2613d180-5e02-11ea-98e2-c2b47cef2840.png)

![Screenshot_2020-03-03-16-33-23-405_com example livevideo 1](https://user-images.githubusercontent.com/16210858/75841578-a89b9180-5e00-11ea-8728-8d381e155d71.jpg)

**Comment by TahaTesser** [comment]
Hi @dwikresno 
I'm not sure if what you are describing is an issue with Flutter itself or if you are asking for assistance within your code.
For issue related to the 3rd party plugin [flutter_rtmp_publisher ](https://pub.dev/packages/flutter_rtmp_publisher) you may want to open an issue in the dedicated [https://github.com/PonnamKarthik/FlutterRtmpPlublisher/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by dwikresno** [comment]
I know, but that plugin only call one original function from flutter it self, and even i can use that function without that plugin. cause when i trace that function (invokeMethode) redirecting me to original file of flutter (platform_channel.dart)
