### ISSUE TITLE
picture can't  load why?

### ISSUE THREAD

**Issue by szhlliuchao** [flutter/flutter#51909]
I found that flutter can't load this picture, I think it might be too big, is this a flutter bug?

Picture address:
https://4zlinkimg.oss-cn-beijing.aliyuncs.com//mifanimg/sxmallimg/productImg/1551944175ug6j4os22pld844ua8f3g

My code:

 return Container(
                  child: Image.network(
                    "https://4zlinkimg.oss-cn-beijing.aliyuncs.com//mifanimg/sxmallimg/productImg/1551944175ug6j4os22pld844ua8f3g",
                    fit: BoxFit.fill,
                  ),
                  padding: EdgeInsets.only(left: 0, right: 0, bottom: 10),
                );

I need you help, thank you !!!

**Comment by TahaTesser** [comment]
Hi @szhlliuchao 

Check out this [DartPad Code Sample](https://dartpad.dev/6b675fd7ef04c6b681c4cc10fb8572aa)

Picture loads fine.
Thank you

**Comment by Remote-version-git** [comment]
really? you make sure that is this not your network problem?
![image](https://user-images.githubusercontent.com/43395809/75879151-d7902280-5e55-11ea-8d90-05216f3c8c1a.png)
it have no problem to realize for me.

**Comment by szhlliuchao** [comment]
I update my flutter to newest version ,the problem is fixed, thank you!!!!
