### ISSUE TITLE
Shared preference losses its value once the app has been destroyed 

### ISSUE THREAD

**Issue by jackryan9013** [flutter/flutter#51911]
I've got issue in shared preference values. once i set value in sp and if i am in same screen/same app its gets value, but once i destroy the app and again check its value the value is getting null from sp.

earlier this was working fine and perfectly, but suddenly it behaves like this.

i am using this version of sp

shared_preferences: ^0.5.6+2

please check this review.

**Comment by TahaTesser** [comment]
Hi @jackryan9013 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@jackryan9013 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
