### ISSUE TITLE
const constructor for BorderRadius.circular

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#5191]
## Steps to Reproduce

Updating some code to use the latest flutter. Running into some problems because of the change that added BorderRadius (https://github.com/flutter/flutter/commit/f3444fcf2865babedacb5c86df63dae05d743831)

I use a `const BoxDecoration` constructor with a `borderRadius` argument, but when I pass `borderRadius: new BorderRadius.circular` I get an analyzer error, since I should be using only constant expressions.

Can we add a `const BorderRadius.circular` constructor? Or is there another suggested workaround?

**Comment by dragostis** [comment]
This is related to [dart/26971](https://github.com/dart-lang/sdk/issues/26971). Unfortunately, the `BorderRadius.circular` constructor cannot be `const` right now. An alternative would be to use `new BoxDecoration` instead of `const BoxDecoration` or to use `const BorderRadius.all(const Radius.circular(someValue))`.

**Comment by mikejurka** [comment]
ok, thanks. that workaround is sufficient for me, but i'll let you decide whether to keep this open since it's something that might be nice to clean up in the API when dart/26971 is fixed.

**Comment by sethladd** [comment]
https://github.com/dart-lang/sdk/issues/26971 was closed. We might want to close this issue?

**Comment by Hixie** [comment]
https://github.com/dart-lang/sdk/issues/20962 is the relevant sdk bug (still open).

**Comment by eseidelGoogle** [comment]
Should I ask the Dart team about the other bug?  Seems pretty low priority.

**Comment by Hixie** [comment]
You should check that it's on our list, but I think it is. In any case, this affects all kinds of stuff in the framework and yes, we can close this bug.

**Comment by kosiara** [comment]
I wanted to have a `BottomNavigationBarItem` with a Card inside of it (per client request) which initially was:

```
         BottomNavigationBarItem(
            icon: Card(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(5.0),
              ),
              child: Icon(Icons.calendar_today_outlined, size: 27),
            ),
            label: '',
          )
```
(`Error: Cannot invoke a non-'const' constructor where a const expression is expected`)

in the end I replaced that with:

```
         BottomNavigationBarItem(
            icon: Card(
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(5.0))
              ),
              child: Icon(Icons.calendar_today_outlined, size: 27),
            ),
            label: '',
          )
```
