### ISSUE TITLE
Image uploading to rest Api , working on emulator but not working on physical device :(

### ISSUE THREAD

**Issue by techieasif** [flutter/flutter#51913]
```
static Future<bool> insertBillDetails(
      {@required String userId,
      @required String shopId,
      @required File photo,
        @required String shopAddress,
      @required String shopName,
      @required String qrCodeId}) async {
    try {
      print("Image Path Got on Controller : $photo");
      Uri url = Uri.parse(ApiUrls.insertBillDetails);
      var sendRequest = http.MultipartRequest("POST", url);
      sendRequest.fields['Userid'] = userId;
      sendRequest.fields['shopid'] = shopId;
      sendRequest.fields['shopname'] = shopName;
      sendRequest.fields['Qrcodeid'] = qrCodeId;
  var pic = await http.MultipartFile.fromPath("image", photo.path,
          contentType: new MediaType(
            'image',
            'jpg',
          ));
      sendRequest.files.add(pic);
      http.StreamedResponse response = await sendRequest.send();
      final finalResp = await http.Response.fromStream(response);
    return true;
    } on SocketException {
      print("No Internet while uploading bill");
      return false;
    } catch (e) {
      print("ERROR ON UPLOADING BILL : $e");
      return false;
    }
  }
```
----------------------------------
❯ **flutter doctor -v**
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/user/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**working on emulator as expected but not working on physical device.
i have tried with dio library too, but same issue.**

**Comment by JosepBove** [comment]
Hi @techieasif 
Could you add the code between the code tags and not in the bold ones? It would make it more readable and you would get more help.
Thanks!

**Comment by techieasif** [comment]
@JosepBove  Thanks! , now it is more readable.

**Comment by JosepBove** [comment]
Is the device running the exactly same android version of the emulator? If not, could you send in what physical device are you testing it?

**Comment by techieasif** [comment]
I have tested on android 9, with more than 3 devices i.e realme, xiaomi, samsung and honor devices 
and emulator also using android  9 , pixel 3.

**Comment by JosepBove** [comment]
Are you catching an error or it just doesn’t work?

**Comment by techieasif** [comment]
weird thing, it is working sometimes and sometimes not.
not giving any error , just not working.

**Comment by techieasif** [comment]
if you need i can put server api function also?

**Comment by JosepBove** [comment]
The point of it is that I don’t see any issue with the flutter code so if it works sometimes and then sometimes not It could be something related with the state management or the API itself.

**Comment by techieasif** [comment]
just inserting data with image to server , not managing any state for this.
api is working as expected every time(tested using postman).
and Flutter code is working as expected using emulator.

don't know where things are breaking.

here the api code -> **Laravel** 
```
public function insertbill(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'Userid' => 'required',
            'shopid' => 'required',
            //'bills' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'shopname' => 'required',
            'address'   =>'required',
            'Qrcodeid' => 'required',
        ]);


        if ($validator->fails()) {
            $response['msg'] = $validator->errors();
            $response['status'] = 0;

            return  response()->json($response);
        }
        
       if ($request->hasFile('image')) {  //check the file present or not
            $file=$request->file('image');
            $extension=$file->getClientOriginalExtension();
            $filename='resources/assets/images/bills_image/'.time().'.'.$extension;
           // $file->move(public_path('/images'));
            $file->move('resources/assets/images/bills_image/', $filename);

            $data['image']=$filename;
           
        }
        $date_added	= date('y-m-d h:i:s');
      $user['user']=DB::table('bills')->insert([
          'Userid' => $request->Userid,			
            'shopid' =>    $request->shopid,
       'address' => $request->address,
        'image' => $data['image'],
        
        'shopname' => $request->shopname,
        'Qrcodeid' => $request->Qrcodeid,
        'Created_at' => $date_added]);

        
        

       // $this->sendSms('91'.$request->phone,$otp_message);
     
         
        $response['output']=$user;
        $response['msg'] = "Successfully Created";
        $response['status'] = 1;
       // $response['token'] = 'Bearer ' . $user->createToken('AppName')->accessToken;

        return  response()->json($response);
    }
```

**Comment by JosepBove** [comment]
It look goods to me too, let’s see if someone can help you because right now I don’t have a clue of what can be causing this.

**Comment by techieasif** [comment]
@JosepBove  thanks for you valuable time.
let's see I am having luck or not .

**Comment by TahaTesser** [comment]
Hi @techieasif 
Can you execute `flutter run --verbose` and try to upload the image using physical device then  if it fails, copy the  run verbose logs and comment it here
Thank you

**Comment by techieasif** [comment]
```
[+10217 ms] I/flutter (29413): Data send to Api :
[        ] I/flutter (29413): name Alex, 
[        ] I/flutter (29413):  gender Male ,
[        ] I/flutter (29413):  add: world, universe , 
[        ] I/flutter (29413):  dob : Mar 4, 2020 , 
[        ] I/flutter (29413):  fax: 123 
[        ] I/flutter (29413):  phone 1234567890 
[        ] I/flutter (29413):  email: a@a.com 
[        ] I/flutter (29413):  User Photo Path :
/storage/emulated/0/Android/data/com.example.chlobazaarnew/files/Pictures/924138f5-619d-4dde-92b3-2fdf513e2b3e2788430551953362763.jpg
[  +88 ms] E/AccessibilityBridge(29413): VirtualView node must not be the root node.
[+10515 ms] I/flutter (29413): Response From UserUpdate APi :->> Instance of 'StreamedResponse'
[  +30 ms] I/flutter (29413): Decode Data : Instance of 'JsonCodec'
[   +1 ms] I/flutter (29413): RESSSSSSPONSE : {output: {customers_id: 1, customers_gender: M, customers_firstname: Alex, customers_lastname: null,
customers_dob: Mar 4, 2020, email: a@a.com, user_name: z, customers_default_address_id: world, universe, customers_telephone: 1234567890, customers_fax:
123, customers_newsletter: null, isActive: 1, fb_id: null, google_id: null, customers_picture:
http://mydomain.com/resources/assets/images/user_profile, cashback_id: 1, refer_code: null, referfrnd_code: null, created_at: null,
updated_at: null, is_seen: 1}, msg: successfully update, code: 10001}
[ +108 ms] E/AccessibilityBridge(29413): VirtualView node must not be the root node.
[ +503 ms] I/chatty  (29413): uid=10267(com.example.chlobazaarnew) identical 7 lines
[        ] E/AccessibilityBridge(29413): VirtualView node must not be the root node.
```
**As user photo path showing at variable :- image path,
In response I'm not getting image back , see: customers_picture (only server directory path) and image is not uploaded to server.**

@TahaTesser

**Comment by TahaTesser** [comment]
Hi @techieasif 
Can you print status code from send request? 
```  
http.StreamedResponse response = await sendRequest.send();
final finalResp = await http.Response.fromStream(response);
print(response.statusCode.toString);
```
Thank you

**Comment by techieasif** [comment]
Thankyou ! @JosepBove   and @TahaTesser 

The issue has been resolved.

```
apiData.files.add(await http.MultipartFile.fromPath(
        'customers_picture',
        userPhoto.path,
//        filename: filename,
//        contentType: new MediaType(
//          'image',
//          'jpg',
//        ),
      ));
```

**ContentType was creating issue. I just Commented content Type , now it is working as expected.
this article helped:**
_https://dev.to/carminezacc/advanced-flutter-networking-part-1-uploading-a-file-to-a-rest-api-from-flutter-using-a-multi-part-form-data-post-request-2ekm_

**Comment by asadamatic** [comment]
I had a similar issue, where my app my working fine on one android device running android 8 (real device) and didn't work on android 9 (real device) and this answer from stackvoerflow worked fine ALLHAMDULILLLAH :)
