### ISSUE TITLE
SliverChildBuilderDelegate doesn't implement SliverChildDelegate.estimatedChildCount correctly

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#51929]
`SliverChildDelegate.estimatedChildCount` documentation states:

> This must return a precise number once [build] has returned null.

However, `SliverChildBuilderDelegate`'s `estimatedChildCount` always returns its `childCount` property, which is optional and thus might be `null` even after `build` has returned `null`.

**Comment by goderbauer** [comment]
Does this actually cause any issues in practice? Maybe our documentation is just wrong?

**Comment by spkersten** [comment]
@goderbauer I have some code that relies on it here: https://github.com/flutter/flutter/issues/28056#issuecomment-594551886
I wanted to create a wrapper for `SliverChildDelegate` that adds a child to the end of the list (if there is an end).

**Comment by darshankawar** [comment]
Hi @spkersten,
Is this still an issue ? The issue you linked seemed to have been closed as fixed along with the original linked [issue](https://github.com/flutter/flutter/issues/64006).
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
