### ISSUE TITLE
closeButton should be able to set onPressed as backButton

### ISSUE THREAD

**Issue by imzyy** [flutter/flutter#51924]
## Use case

In our application we want to display a close icon in AppBar with customized behavior.
backButton has onPressed parameter in initializer to enable override of default navigator pop behavior. closeButton should also be able to set it.

## Proposal

Add onPressed field to closeButton initializer.
See https://github.com/flutter/flutter/pull/51925

**Comment by Remote-version-git** [comment]
you should be attach your code because I can't direct find problem.
