### ISSUE TITLE
Support resizing web tab as a result of dragging to new window

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#51939]
## Steps to Reproduce

1. Run a Flutter app on Chrome (e.g.  https://flutter.github.io/samples/#/) 
2. Resize the window to make it smaller. Notice that the UI adjusts
3. Drag the tab outside the current window 

Notice that the UI hasn't adjusted to the new (larger) window size

<img width="1434" alt="Screenshot 2020-03-04 at 16 22 07" src="https://user-images.githubusercontent.com/6655696/75894406-74da5f00-5e34-11ea-90a4-2f3d75091d07.png">

4. Drag the tab back to the original (smaller) window

Notice that UI has adjusted to the previous window's larger size instead of the current window size and thus content is cutoff.

<img width="859" alt="Screenshot 2020-03-04 at 16 24 38" src="https://user-images.githubusercontent.com/6655696/75894640-d1d61500-5e34-11ea-9a31-2498e8dc2d54.png">

## Related Issue
https://github.com/flutter/flutter/issues/50382

**Comment by tpm5183** [comment]
This sounds like it has more to do with Flutter's optimization for web then actually an issue. From the looks of it, there are lots of widgets that need to be re-rendered when size changes.

**Comment by ferhatb** [comment]
@guidezpl , we recently fixed an issue around resizing (https://github.com/flutter/engine/pull/16822) , can you please try with latest master to make sure issue is resolved.

**Comment by guidezpl** [comment]
Looks good, thanks!
