### ISSUE TITLE
Web: Pageview with dynamic content in Listview or SingleChildScrollView with Column

### ISSUE THREAD

**Issue by 10686142** [flutter/flutter#51937]
## The Problem

My app uses a PageView.builder to display a vertical scrollable Listview's with dynamic content, kind of like a UIPageviewController for iOS or a ViewPager in Android.

Displaying the same content Natively on iOS or Android both works as expected, but on web if I scroll down when the ListView's content is scrollable, it first displays a lot of extra whitespace. This extra whitespace dissappears however, when I navigate to the next page and back.

## My research

* I googled around and did see this issue from a while back that looks similar to mine, the only difference is that it does work natively for me: https://github.com/flutter/flutter/issues/29749

* I have also set the 'shrinkWrap' property to true, but this didn't help.

* I also tried different solutions, like using a SingleChieldScrollView with a Column instead, but this had the same results.

## Results

**Expected results:** 
![Alt Text](https://media.giphy.com/media/Rk99CHgrryMcItIbk1/giphy.gif)
_This is the native iOS version_

**Actual results:** 
![Alt Text](https://media.giphy.com/media/lTeSSuIvI9w8j34GTo/giphy.gif)
_This is the web version_

## Other info
The ListView uses the [flutter_html](https://github.com/Sub6Resources/flutter_html) widget for one of the List items, the rest are all regular Flutter widgets. That plugin formats inputted html into corresponding Flutter widgets. 

![Screenshot 2020-03-04 at 16 08 10](https://user-images.githubusercontent.com/23178404/75893186-b79b3780-5e32-11ea-8c80-7345d74c3b3f.png)
_This is the pageView tree_

![Screenshot 2020-03-04 at 16 04 33](https://user-images.githubusercontent.com/23178404/75892740-1c09c700-5e32-11ea-8622-9b35781fd8af.png)
_This is the tree of the widgets being created by the flutter_html plugin inside the ListView_

## My thoughts on the problem 
At first I thought this had to be because of the flutter_html plugin, but seeing the other issue that people had with dynamic content inside a PageView's Listview and that this only happens on Flutter web (which still is in Beta i believe), made me think this could be a bug for Flutter web.

Thanks in advance for any help:)

**Comment by yjbanov** [comment]
The other issue does actually happen in native Flutter, so I think this is something else. Do you know if the content that disappears is the HTML content from the `flutter_html` plugin? What happens if you replace that content with some basic Flutter widgets, such as text and buttons?

**Comment by 10686142** [comment]
Apologies for my late response, I was on vacation.

Well I'll contact the developer of the flutter_html plugin for their take on the problem, since this doesn't happen when I am using a text widget and the Flutter bug was on the native platform;)

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
