### ISSUE TITLE
How can I get the purchase status in in_app_purchase?

### ISSUE THREAD

**Issue by scg94** [flutter/flutter#51949]
Hi, everyone,

The problem I currently have is that I want to obtain the status of the purchase of a product through Google Play, since I want to save it in a database, however, when I do the action, regardless of whether I buy or reject I get 'true' as output.

## Steps to Reproduce

1. Buy product from the app, registered on Google Play.
2. Finalize purchase.

**Expected results:**
I would like to obtain the result of the purchase, and then store the history of this purchase in the Database.

**Actual results:**
I click on buy or cancel, and the result is true, so I can't get the purchase status to know if the user bought it or not and save it in the database.

```
/// Purchase a product
  Future<Null> _buyProduct(ProductDetails prod) async{
    //print(prod.title);
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: prod);
    //_iap.buyNonConsumable(purchaseParam: purchaseParam);
    var x = await _iap.buyConsumable(purchaseParam: purchaseParam, autoConsume: false);
    //print("HOSOSOS $x");
    setState(() {
      text1 = "RESPUESTA: $x";
    });
  }
```

I hope someone can help me. 
Redards.

**Comment by agordeev** [comment]
`buyConsumable` returns Future<bool>, which indicates whether the request was sent successfully or not:

```
  /// This method does return whether or not the purchase request was initially
  /// sent succesfully.
```

`true` returned doesn't mean the product was bought. You need to listen for updates on `purchaseUpdatedStream`:

```
  /// This method does not return the result of the purchase. Instead, after
  /// triggering this method, purchase updates will be sent to
  /// [purchaseUpdatedStream]. You should [Stream.listen] to
  /// [purchaseUpdatedStream] to get [PurchaseDetails] objects in different
  /// [PurchaseDetails.status] and update your UI accordingly. When the
  /// [PurchaseDetails.status] is [PurchaseStatus.purchased] or
  /// [PurchaseStatus.error], you should deliver the content or handle the
  /// error, then call [completePurchase] to finish the purchasing process.
```

**Comment by matthew-carroll** [comment]
This issue looks to be just a misunderstanding of the API. Should we close this ticket?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
