### ISSUE TITLE
CupertinoTextField doesn't look the same in real device

### ISSUE THREAD

**Issue by rafael-trevisan** [flutter/flutter#51959]
Hi all,

I've just started with Flutter here and got some CupertineTextField different on the simulator and in the real device.

Simulator:
![image](https://user-images.githubusercontent.com/17282530/75919956-557f0a00-5e13-11ea-88b8-2ca8c3ddc4e6.png)

Real Device:
![image](https://user-images.githubusercontent.com/17282530/75920000-66c81680-5e13-11ea-9230-59714240f608.png)

Am I doing something wrong already? :)

**Comment by mazzonem** [comment]
Looks like your device is in dark mode (see system bar color at the top). Have a look at the theming capabilities of Flutter to adapt your colours based on the light/dark mode.

**Comment by rafael-trevisan** [comment]
Thanks. It was the dark theme indeed.
