### ISSUE TITLE
Remove usages of deprecated members from package:package_config in flutter_tools

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#51951]
As of `1.9.0`, support for the `.packages` has been deprecated in `package:package_config`. `flutter_tools` will need to be migrated to utilize the new JSON format.

@pq do you happen to have any migration instructions for this?

**Comment by jonahwilliams** [comment]
I think we move to package_resolver, like in https://dart-review.googlesource.com/c/sdk/+/138322

**Comment by pq** [comment]
The PR @jonahwilliams linked looks right to me.  Ping me if you hit any snags?

**Comment by zanderso** [comment]
By when should this migration be done? What Dart SDK version or release date will no longer support .packages? /cc @mit-mit

**Comment by jonahwilliams** [comment]
Actually @pq I do have a question on this - what should we be passing to the frontend_server/dart2js and other tools? 

By default, today we only deal with `.packages`, so we pass the path for this to these tools. But if the tooling resolves to the package_config.json file instead, nothing is surfaced to indicate this. We'd keep passing .packages, which might work provided that all of the tools we depend on are using package_config too?

Though it would be nice if package_config exposed some information on what file it resolved to

**Comment by pq** [comment]
Thanks for the ping.  To be honest I'm not really sure.  A while back I chatted w/ @stereotype441 about this; maybe Paul knows?

**Comment by mit-mit** [comment]
> What Dart SDK version or release date will no longer support .packages?

We havn't decided that yet. But probably 1-2 quarters after the first stable release that ships with the new format.
