### ISSUE TITLE
Auto-merging is setting Flutter GitHub Bot as the author

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#51967]
Recently, commits auto-merged by the "waiting for tree to go green" trigger have "Flutter GitHub Bot" set as the commit author.  The author should be the original PR author to give credit and to make `git blame` useful. 

First seen in https://github.com/flutter/flutter/commit/57c6721cd54b6747ef3444cfc6d06d4c33e310ea.
Also:
https://github.com/flutter/flutter/commit/d0c435733878a55a04d38545673e29e5d76c6a4c
https://github.com/flutter/flutter/commit/e22ceb0c7a4b4262f298c2c6e4c854124b1f0987
https://github.com/flutter/flutter/commit/a703c75896193597c2de932930ef981477f747c8

**Comment by jmagman** [comment]
See https://developer.github.com/v4/mutation/mergepullrequest/

**Comment by dnfield** [comment]
It's not clear to me from the docs how to fix this.

**Comment by dnfield** [comment]
I'll try to take a look at whether the v3 rest API gives us different options

**Comment by dnfield** [comment]
Looks like this is https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/m-p/48797#M10688

**Comment by dnfield** [comment]
https://twitter.com/natfriedman/status/1235613840659767298?s=20 GitHub is saying this should be fixed soon.

**Comment by dnfield** [comment]
According to GitHub, this should be resolved now.  Closing.

**Comment by dnfield** [comment]
e.g. https://github.com/flutter/flutter/commit/ed94c9d856c8de67f183d8ac18b06f61f5405219 was merged by the bot but has the right attribution
