### ISSUE TITLE
Platform.version is incomplete

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#5196]
The standalone Dart VM, Platform.version gives a string like

1.19.0-edge.d3070afbb7b46702bf0139895d1565df1292497e (Tue Aug  2 15:21:42 2016) on "linux_x64"

but in Flutter I only get

1.19.0-edge (Tue Aug  2 16:00:19 2016) on "ios_dbc"

which is not complete enough to tell what version of the VM is being used.  This same different appears in the version string reported through Observatory.

**Comment by chinmaygarde** [comment]
I bet its the version_cc generation not being correct since we use the dart/runtime BUILD.gn indirectly.

**Comment by chinmaygarde** [comment]
@rmacnak-google: https://codereview.chromium.org/2206953004
