### ISSUE TITLE
ImageFiltered with matrix filter clips its output

### ISSUE THREAD

**Issue by flar** [flutter/flutter#51978]
The following code puts up a widget and rotates it using 2 different methods - a `Transform` widget and an `ImageFiltered` widget with an `ImageFilter.matrix` filter.

The two behave very similarly, but the output of the `ImageFiltered` widget is clipped to the original bounds of the transformed child.

Gist: https://gist.github.com/flar/da94ae35e8b86184b404000dfda68313

**Comment by TahaTesser** [comment]
Hi @flar
In your gist, I couldn't find the code for ImageFiltered.
Can you please update the gist with complete example?
Thank you

**Comment by flar** [comment]
ImageFiltered is a built-in widget.

**Comment by liyuqian** [comment]
@TahaTesser : FYI, `ImageFIltered` is in https://master-api.flutter.dev/ but not in https://api.flutter.dev/ yet.

**Comment by flar** [comment]
Fixed by https://github.com/flutter/engine/pull/16960

**Comment by flar** [comment]
Fixed by https://github.com/flutter/engine/pull/16960

**Comment by flar** [comment]
The first fix in https://github.com/flutter/engine/pull/16960 failed because it was rendering the children with the wrong bounds for their savelayer.
