### ISSUE TITLE
EditableText.textInputAction has unintended effect with multiline textfields (macOS)

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#51974]
Hi there,

I'm attempting to build a multiline textfield that submits on enter (and inserts newline on a shift+enter), but it appears that newline insertion is hard-coded in the embedder's `FlutterTextInputPlugin.insertNewLine` method for `EditableText`s of type `TextInputType.multiline`.

The reason I believe this to be a bug is because `TextInputAction` appears to be designed to inform the behavior of an enter press, not the type of the `EditableText`, and the widget already defaults to setting the action to `TextInputAction.newline` if the widget's `maxLines > 1`.

I've found that it's possible to work around this issue by changing the `EditableText`'s input type to `text`, which suppresses the newline insertion on the engine side, but thought that it was probably worth reporting.

@gspencergoog

**Comment by justinmc** [comment]
I know there was a PR to add this functionality a few months ago.  Are you using a version that's new enough to have this? https://github.com/flutter/engine/pull/15568

**Comment by pedromassangocode** [comment]
Hi @shyndman 
Are you still facing this issue? If yes please share your `flutter doctor -v` a minimal reproducible sample code and share the steps to reproduce the issue.
Thank you

**Comment by shyndman** [comment]
I'll take a look and report back @pedromassango. Thanks!

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
