### ISSUE TITLE
saveLayer with ColorFilter/ImageFilter disables raster cache 

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#51975]
This issue was originated from b/144705335

If saveLayer is called with ColorFilter/ImageFilter, Skia will not compute `SkPicture`'s cull rect and just use the provided cull rect. See [1] and [2].

Flutter's default cull rect is super large and the picture raster cache would fail with such large size. See [3].

Moreover, Flutter' layer raster cache would also fail because it uses its leaf-node PictureLayer's size to determine the upper layer's size.

The result is that Flutter's performance is poor whenever there's a saveLayer with ColorFilter/ImageFilter because our picture raster cache acceleration is disabled.

[1]:  https://github.com/google/skia/blob/cb50b117e3caa9ae0904fe92648f48d623e86151/src/core/SkRecordDraw.cpp#L295
[2]: https://github.com/google/skia/blob/cb50b117e3caa9ae0904fe92648f48d623e86151/src/core/SkRecordDraw.cpp#L306
[3]: https://github.com/flutter/engine/blob/d20f6d7bd336b7bb5e02a0193815db0583a06876/lib/ui/painting.dart#L3382

**Comment by fredlee12345678** [comment]
@liyuqian do you have plan to enable the raster cache for saveLayer in Skia or engine layer?

**Comment by liyuqian** [comment]
It's not planned for this quarter as we're currently focusing on the memory performance and infrastructures. We'll try to see if we can find some resources to tackle it in Q4. Meanwhile, please feel encouraged to send us a PR to fix it if you're interested. I'm very happy to review :)

[1]: https://github.com/flutter/flutter/issues/assigned/liyuqian

**Comment by fredlee12345678** [comment]
@liyuqian I notice that you and flar have a solution for saveLayer, here is code: https://gist.github.com/flar/efe8f4aadeb41f587a8d86a07c483fe4. 

`final RenderRepaintBoundary renderBackground = _snapshotKey.currentContext.findRenderObject();
    final ui.Image image = await renderBackground.toImage(
      pixelRatio: WidgetsBinding.instance.window.devicePixelRatio,
    );`

toImage will call Picture::RasterizeToImage, in this function:


fml::TaskRunner::RunNowOrPostTask(
      **_raster_task_runner_**,
      [ui_task_runner, snapshot_delegate, picture, picture_bounds, ui_task] {
        sk_sp<SkImage> raster_image =
            snapshot_delegate->MakeRasterSnapshot(picture, picture_bounds);
        fml::TaskRunner::RunNowOrPostTask(
            ui_task_runner,
            [ui_task, raster_image]() { ui_task(raster_image); });
      });


 my question is that why engine must make rester snapshot at raster task runner not io task runner? I think it may block raster task runner.

**Comment by liyuqian** [comment]
@fredlee12345678 : Yes, blocking the raster task runner is bad and we should move it to the IO thread. It's currently on the raster thread instead of the IO thread probably because of some resource sharing and ownership issues similar to https://github.com/flutter/flutter/issues/16644

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
