### ISSUE TITLE
"gclient sync" fails in flutter repo due to duplicate key

### ISSUE THREAD

**Issue by stereotype441** [flutter/flutter#51982]
I'm trying to follow the instructions in https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment and when I try to do "gclient sync" I get the error message "ValueError: duplicate key in dictionary: src/third_party/dart/pkg/analysis_server/language_model (file '/usr/local/google/home/paulberry/flutter/engine/src/flutter/DEPS', line 511)".

It looks like the good folks at depot_tools added a rule to prohibit duplicate DEPS entries today (https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2088422) so flutter's DEPS file is now broken.

**Comment by jason-simmons** [comment]
The build should be fixed now.

**Comment by mikerreed** [comment]
Just tried 'gclient sync' on a brand new directory, and got the same error: duplicate key in dictionary ...

**Comment by mikerreed** [comment]
n/m -- my fork of flutter/engine was out of date
