### ISSUE TITLE
Remove enableR8=true from gradle.properties

### ISSUE THREAD

**Issue by pvegh** [flutter/flutter#52005]
Android Studio 3.6 shows a warning now that this flag is deprecated. And R8 is default now anyway.
So I removed it in my project.
Currently the gradle build from the Flutter SDK adds it back every time assembleDebug is executed (e.g. the Run app from AS).
So now we must choose either to revert this automatic change every time, or to see the warning every time in AS.
It should be just removed from gradle in Flutter, not forcing it back anymore.

Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by VladyslavBondarenko** [comment]
Yes, these logs are absent when I run without `android.enableR8=true`

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by azol** [comment]
The same for me on Flutter 1.21.0-7.0.pre • channel dev
Revert this automatically added "android.enableR8=true" is quite annoying

**Comment by tensor5** [comment]
Same problem here: `flutter run` keeps re-adding `android.enableR8=true`. Check [these lines](https://github.com/flutter/flutter/blob/1.22.0-12.3.pre/packages/flutter_tools/lib/src/android/gradle_utils.dart#L81-L88).

This issue should be reopened.

**Comment by micodev** [comment]
same here 
```
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (3 weeks ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

**Comment by jesper372** [comment]
Ditto.

**Comment by 0biWanKenobi** [comment]
Same. Come on guys, let's fix this 👍
