### ISSUE TITLE
Implement r-tree to query rects without relying on SkBBoxHierarchy records

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#52000]
Once https://github.com/flutter/engine/pull/16923 is merged, we should figure out how to decouple the implementation of this RTree from Skia. This means that the engine should be responsible for populating the RTree directly. That is without relaying on BBH insert calls, which are implementation detail of Skia.

**Comment by chinmaygarde** [comment]
> This will be an opportunity to fully rewrite the rtree, so it's better documented and follows the engine's code style guide.

This should happen regardless of the ask in this issue. Lets file another bug to track this.

**Comment by flar** [comment]
Obsolete as of https://github.com/flutter/engine/pull/38429
