### ISSUE TITLE
Why my android studio show file SDK in HTML???? Below is file container.dart :(((

### ISSUE THREAD

**Issue by Gitminh9201** [flutter/flutter#52001]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, user-scalable=no">
  <meta name="description" content="API docs for the wxww constant from the Float32x4 class, for the Dart programming language.">
  <title>wxww constant - Float32x4 class - dart:typed_data library - Dart API</title>
  
  <base href="../..">

  <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:500,400i,400,300|Source+Sans+Pro:400,300,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="static-assets/github.css">
  <link rel="stylesheet" href="static-assets/styles.css">
  <link rel="icon" href="static-assets/favicon.png">
  
</head>

<body>

<div id="overlay-under-drawer"></div>

<header id="title">
  <button id="sidenav-left-toggle" type="button">&nbsp;</button>
  <ol class="breadcrumbs gt-separated dark hidden-xs">
    <li><a href="index.html">move_to_background</a></li>
    <li><a href="dart-typed_data/dart-typed_data-library.html">dart:typed_data</a></li>
    <li><a href="dart-typed_data/Float32x4-class.html">Float32x4</a></li>
    <li class="self-crumb">wxww constant</li>
  </ol>
  <div class="self-name">wxww</div>
  <form class="search navbar-right" role="search">
    <input type="text" id="search-box" autocomplete="off" disabled class="form-control typeahead" placeholder="Loading search...">
  </form>
</header>

<main>

  <div id="dartdoc-sidebar-left" class="col-xs-6 col-sm-3 col-md-2 sidebar sidebar-offcanvas-left">
    <header id="header-search-sidebar" class="hidden-l">
      <form class="search-sidebar" role="search">
        <input type="text" id="search-sidebar" autocomplete="off" disabled class="form-control typeahead" placeholder="Loading search...">
      </form>
    </header>
    
    <ol class="breadcrumbs gt-separated dark hidden-l" id="sidebar-nav">
      <li><a href="index.html">move_to_background</a></li>
      <li><a href="dart-typed_data/dart-typed_data-library.html">dart:typed_data</a></li>
      <li><a href="dart-typed_data/Float32x4-class.html">Float32x4</a></li>
      <li class="self-crumb">wxww constant</li>
    </ol>
    
    <h5>Float32x4 class</h5>
    <ol>
      <li class="section-title"><a href="dart-typed_data/Float32x4-class.html#constructors">Constructors</a></li>
      <li><a href="dart-typed_data/Float32x4/Float32x4.html">Float32x4</a></li>
      <li><a href="dart-typed_data/Float32x4/Float32x4.fromFloat64x2.html">fromFloat64x2</a></li>
      <li><a href="dart-typed_data/Float32x4/Float32x4.fromInt32x4Bits.html">fromInt32x4Bits</a></li>
      <li><a href="dart-typed_data/Float32x4/Float32x4.splat.html">splat</a></li>
      <li><a href="dart-typed_data/Float32x4/Float32x4.zero.html">zero</a></li>
    
      <li class="section-title">
        <a href="dart-typed_data/Float32x4-class.html#instance-properties">Properties</a>
      </li>
      <li><a href="dart-typed_data/Float32x4/signMask.html">signMask</a></li>
      <li><a href="dart-typed_data/Float32x4/w.html">w</a></li>
      <li><a href="dart-typed_data/Float32x4/x.html">x</a></li>
      <li><a href="dart-typed_data/Float32x4/y.html">y</a></li>
      <li><a href="dart-typed_data/Float32x4/z.html">z</a></li>
      <li class="inherited"><a href="dart-core/Object/hashCode.html">hashCode</a></li>
      <li class="inherited"><a href="dart-core/Object/runtimeType.html">runtimeType</a></li>
    
      <li class="section-title"><a href="dart-typed_data/Float32x4-class.html#instance-methods">Methods</a></li>
      <li><a href="dart-typed_data/Float32x4/abs.html">abs</a></li>
      <li><a href="dart-typed_data/Float32x4/clamp.html">clamp</a></li>
      <li><a href="dart-typed_data/Float32x4/equal.html">equal</a></li>
      <li><a href="dart-typed_data/Float32x4/greaterThan.html">greaterThan</a></li>
      <li><a href="dart-typed_data/Float32x4/greaterThanOrEqual.html">greaterThanOrEqual</a></li>
      <li><a href="dart-typed_data/Float32x4/lessThan.html">lessThan</a></li>
      <li><a href="dart-typed_data/Float32x4/lessThanOrEqual.html">lessThanOrEqual</a></li>
      <li><a href="dart-typed_data/Float32x4/max.html">max</a></li>
      <li><a href="dart-typed_data/Float32x4/min.html">min</a></li>
      <li><a href="dart-typed_data/Float32x4/notEqual.html">notEqual</a></li>
      <li><a href="dart-typed_data/Float32x4/reciprocal.html">reciprocal</a></li>
      <li><a href="dart-typed_data/Float32x4/reciprocalSqrt.html">reciprocalSqrt</a></li>
      <li><a href="dart-typed_data/Float32x4/scale.html">scale</a></li>
      <li><a href="dart-typed_data/Float32x4/shuffle.html">shuffle</a></li>
      <li><a href="dart-typed_data/Float32x4/shuffleMix.html">shuffleMix</a></li>
      <li><a href="dart-typed_data/Float32x4/sqrt.html">sqrt</a></li>
      <li><a href="dart-typed_data/Float32x4/withW.html">withW</a></li>
      <li><a href="dart-typed_data/Float32x4/withX.html">withX</a></li>
      <li><a href="dart-typed_data/Float32x4/withY.html">withY</a></li>
      <li><a href="dart-typed_data/Float32x4/withZ.html">withZ</a></li>
      <li class="inherited"><a href="dart-core/Object/noSuchMethod.html">noSuchMethod</a></li>
      <li class="inherited"><a href="dart-core/Object/toString.html">toString</a></li>.....

**Comment by TahaTesser** [comment]
Hi @Gitminh9201 
Your links are broken and please explain in detail what issue you're facing?
Thank you

**Comment by VladyslavBondarenko** [comment]
@Gitminh9201 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
