### ISSUE TITLE
Failed to download the Android dependencies on flutter precache

### ISSUE THREAD

**Issue by crypto-maria** [flutter/flutter#52007]
**I tried flutter precache**
```
apple@MacBook-Pro ~ % flutter precache
Failed to download the Android dependencies                             
Downloading Android Maven dependencies...                           2.6s
```
**This is flutter precache verbose**
```
apple@MacBook-Pro ~ % flutter precache --verbose
[  +15 ms] executing: [/Users/apple/Documents/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/apple/Documents/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +7 ms] executing: [/Users/apple/Documents/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/apple/Documents/flutter/] git ls-remote --get-url
origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/Users/apple/Documents/flutter/] git rev-parse
--abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +74 ms] Downloading Android Maven dependencies...
[ +139 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android
Studio.app/Contents/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$A
PP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:
$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$AP
P_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVM
Version":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass
":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.6
","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.p
ath":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An
application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.3
6.6241897","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An
application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleType
IconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBund
leTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitc
hing":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHigh
ResolutionCapable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDes
cription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio"
,"NSLocationUsageDescription":"An application in Android Studio requests access
to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTy
peRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],
"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"pu
blic.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVe
rsion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android
Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio
requests access to the user's Downloads
folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio
requests access to files on a network volume.","CFBundleGetInfoString":"Android
Studio 3.6, build AI-192.7142.36.36.6241897. Copyright JetBrains s.r.o., (c)
2000-2020","NSRemovableVolumesUsageDescription":"An application in Android
Studio requests access to files on a removable volume."}
[   +8 ms] executing: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +73 ms] Exit code 0 from: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +3 ms] executing:
/var/folders/gx/zh3t46pd4075xmwjrct4bnz80000gn/T/flutter_gradle_wrapper.XotgPw/g
radlew -b
/Users/apple/Documents/flutter/packages/flutter_tools/gradle/resolve_dependencie
s.gradle --project-cache-dir
/var/folders/gx/zh3t46pd4075xmwjrct4bnz80000gn/T/flutter_gradle_wrapper.XotgPw
resolveDependencies
[+2316 ms] 
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project 'gradle'.
                    > Could not read build file
                    '/Users/apple/Documents/flutter/packages/flutter_tools/gradl
                    e/resolve_dependencies.gradle' as it does not exist.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run
                    with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 528ms
[   +1 ms] Failed to download the Android dependencies
[  +11 ms] Downloading Android Maven dependencies... (completed in 2.6s)
[  +12 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +6 ms] "flutter precache" took 2,727ms.
```

**Comment by VladyslavBondarenko** [comment]
@crypto-maria 
Don't you have indeed this file `/Users/apple/Documents/flutter/packages/flutter_tools/gradle/resolve_dependencies.gradle`?
Can you see the same error after reinstalling flutter sdk?

**Comment by crypto-maria** [comment]
Yes, I do have the file in there. Nonetheless, the very same error I face.

**Comment by VladyslavBondarenko** [comment]
Could you provide your `flutter doctor -v`?

**Comment by crypto-maria** [comment]
this is, my flutter precache is failing too even if I used `sudo`

**Result for `fluter precache`**

`apple@MacBook-Pro ~ % flutter precache`
`Failed to download the Android dependencies                             
Downloading Android Maven dependencies...                           2.9s`

**Result for `sudo fluter precache`**

`apple@MacBook-Pro ~ % sudo flutter precache`
`Password:`
   `Woah! You appear to be trying to run flutter as root.`
   `We strongly recommend running the flutter tool without superuser privileges.`
  `/`
`📎`
`Downloading Android Maven dependencies...     `                          
`Failed to download the Android dependencies    `                 
`Downloading Android Maven dependencies...                         666.2s (!)`

**Result for `fluter doctor -v`**

`apple@MacBook-Pro ~ % flutter doctor -v`
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)`
    `• Flutter version 1.12.13+hotfix.8 at /Users/apple/Documents/flutter`
    `• Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800`
    `• Engine revision e1e6ced81d`
    `• Dart version 2.8.0 (build 2.8.0-dev.11.0)`

 
`[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)`
    `• Android SDK at /Users/apple/Library/Android/sdk`
    `• Android NDK location not configured (optional; useful for native profiling support)`
    `• Platform android-29, build-tools 29.0.2`
    `• Java binary at: /Applications/Android`
      `Studio.app/Contents/jre/jdk/Contents/Home/bin/java`
    `• Java version OpenJDK Runtime Environment (build`
      `1.8.0_212-release-1586-b4-5784211)`
    `• All Android licenses accepted.`

`[✗] Xcode - develop for iOS and macOS`
   ` ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.`
      `Download at: https://developer.apple.com/xcode/download/`
      `Or install Xcode via the App Store.`
      `Once installed, run:`
      `  sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`
    `    sudo xcodebuild -runFirstLaunch`
  `  ✗ CocoaPods installed but not working.`
        `You appear to have CocoaPods installed but it is not working.`
        `This can happen if the version of Ruby that CocoaPods was installed with `
         `is different from the one being used to invoke it.`
        `This can usually be fixed by re-installing CocoaPods. For more info, see`
        `https://github.com/flutter/flutter/issues/14293.`
      `To re-install CocoaPods, run:`
      `  sudo gem install cocoapods`

`[✓] Android Studio (version 3.6)`
    `• Android Studio at /Applications/Android Studio.app/Contents`
    `• Flutter plugin version 44.0.2`
    `• Dart plugin version 192.7761`
    `• Java version OpenJDK Runtime Environment (build`
      `1.8.0_212-release-1586-b4-5784211)`

`[✓] VS Code (version 1.42.1)`
    `• VS Code at /Applications/Visual Studio Code.app/Contents`
    `• Flutter extension version 3.8.1`

`[✓] Connected device (1 available)`
    `• Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1`
      `(API 25) (emulator)`

`! Doctor found issues in 1 category.`

**Comment by crypto-maria** [comment]
anything? or any solution?

**Comment by orangejx** [comment]
> Could you provide your `flutter doctor -v`?

my result for ```flutter precache --verbose ```
```
[  +16 ms] executing: [/Users/ora/Projects/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/ora/Projects/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +9 ms] executing: [/Users/ora/Projects/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/ora/Projects/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [/Users/ora/Projects/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +10 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +22 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +23 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[ +120 ms] Downloading Android Maven dependencies...
[ +299 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/phpmyadmin/tmp/twig/' (OS Error: Permission denied, errno = 13)
[  +98 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/test/' (OS Error: Permission denied, errno = 13)
[   +2 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/phpmyadmin/' (OS Error: Permission denied, errno = 13)
[   +1 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/20181006/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/shiyanshi/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/mysql/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/performance_schema/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/test2/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path =
'/Applications/XAMPP/xamppfiles/var/mysql/zvuldrill/' (OS Error: Permission denied, errno = 13)
[+2120 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +14 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP
_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/C
ontents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Con
tents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.6","idea.executable":"stu
dio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An
application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.36.6392135","CFBundleDevelopmentRegion":"Englis
h","NSCameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"
All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}]
,"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCa
pable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDescription":"An application in Android Studio requests
access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application
in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace
","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-cat
egory.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An
application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An
application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An
application in Android Studio requests access to files on a network volume.","CFBundleGetInfoString":"Android Studio 3.6,
build AI-192.7142.36.36.6392135. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An
application in Android Studio requests access to files on a removable volume."}
[  +10 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +92 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +5 ms] executing: /var/folders/z7/cbchvrk51rbdshknvn76csbc0000gn/T/flutter_gradle_wrapper.msehCB/gradlew -b
/Users/ora/Projects/flutter/packages/flutter_tools/gradle/resolve_dependencies.gradle --project-cache-dir
/var/folders/z7/cbchvrk51rbdshknvn76csbc0000gn/T/flutter_gradle_wrapper.msehCB resolveDependencies
[ +656 ms] Downloading https://services.gradle.org/distributions/gradle-5.6.2-all.zip


                    Exception in thread "main" java.net.SocketException: Unexpected end of file from server
                    	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
                    	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
                    	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2055)
                    	at
                    	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.
                    	java:183)
                    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
                    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
                    	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
                    	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
                    	at org.gradle.wrapper.Download.download(Download.java:44)
                    	at org.gradle.wrapper.Install$1.call(Install.java:61)
                    	at org.gradle.wrapper.Install$1.call(Install.java:48)
                    	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
                    	at org.gradle.wrapper.Install.createDist(Install.java:48)
                    	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
                    	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[   +3 ms] Failed to download the Android dependencies
[  +14 ms] Downloading Android Maven dependencies... (completed in 3.3s)
[   +9 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] "flutter precache" took 3,567ms.
```

**Comment by jlustigman** [comment]
Hi 

I am having the same problem.

I am on mac os 10.15.4

Thank you for your help

**Comment by jlustigman** [comment]
Mac-mini:deevelopment joellustigman$ flutter precache --verbose
[   +9 ms] executing: [/Users/joellustigman/deevelopment/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [/Users/joellustigman/deevelopment/flutter/] git tag
--contains HEAD
[ +238 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[   +6 ms] executing: [/Users/joellustigman/deevelopment/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/joellustigman/deevelopment/flutter/] git ls-remote
--get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +36 ms] Unable to locate an Android SDK.
[  +20 ms] executing: [/Users/joellustigman/deevelopment/flutter/] git rev-parse
--abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[  +51 ms]
/Users/joellustigman/deevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gra
dle/wrapper/gradle-wrapper.jar mode: 33188 rw-r--r--.
[   +1 ms]
/Users/joellustigman/deevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gra
dlew mode: 33261 rwxr-xr-x.
[        ]
/var/folders/tq/0scr7t0j4x163t54w_r60z080000gn/T/flutter_gradle_wrapper.DlwXiL/g
radlew mode: 33188 rw-r--r--.
[        ] Trying to give execute permission to
/var/folders/tq/0scr7t0j4x163t54w_r60z080000gn/T/flutter_gradle_wrapper.DlwXiL/g
radlew.
[   +4 ms]
/Users/joellustigman/deevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gra
dlew.bat mode: 33188 rw-r--r--.
[   +2 ms] Downloading Android Maven dependencies...
[ +188 ms] executing:
/var/folders/tq/0scr7t0j4x163t54w_r60z080000gn/T/flutter_gradle_wrapper.DlwXiL/g
radlew -b
/Users/joellustigman/deevelopment/flutter/packages/flutter_tools/gradle/resolve_
dependencies.gradle --project-cache-dir
/var/folders/tq/0scr7t0j4x163t54w_r60z080000gn/T/flutter_gradle_wrapper.DlwXiL
resolveDependencies
[ +619 ms]
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project 'gradle'.
                    > Could not open proj remapped class cache for
                    eru83v3y883j4k3etynauifrj
                    (/Users/joellustigman/.gradle/caches/5.6.2/scripts-remapped/
                    resolve_dependencies_3go621vq2bnor8lscg8q3z670/eru83v3y883j4
                    k3etynauifrj/proj40e7ec637808a9c747559d26950b1d9b).
                       > Could not open proj generic class cache for build file
                       '/Users/joellustigman/deevelopment/flutter/packages/flutt
                       er_tools/gradle/resolve_dependencies.gradle'
                       (/Users/joellustigman/.gradle/caches/5.6.2/scripts/eru83v
                       3y883j4k3etynauifrj/proj/proj40e7ec637808a9c747559d26950b
                       1d9b).
                          > BUG! exception in phase 'semantic analysis' in
                          source unit '_BuildScript_' Unsupported class file
                          major version 57

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run
                    with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 423ms
[   +2 ms] Failed to download the Android dependencies
[   +8 ms] Downloading Android Maven dependencies... (completed in 0.8s)
[   +7 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +5 ms] "flutter precache" took 954ms.

**Comment by crypto-maria** [comment]
> Hi
> 
> I am having the same problem.
> 
> I am on mac os 10.15.4
> 
> Thank you for your help

give the permissions to `zsh` as new terminal seems to be more strict in third party downloads. 
after giving proper permissions, the problem should be gone.

let me know if that persists.

Regards.

**Comment by matsp** [comment]
@crypto-maria Can you explain that with different words? :+1:

**Comment by crypto-maria** [comment]
In other words, the is in MacBook's update where replaced `bash` terminal with `zsh`. The main reason was to secure their operating system, zsh is do not allow any third party download from to its library where flutter preached is downloaded. Now if you want to download it, you have to give permission to zsh to download it.

> Here, only using `sudo` will not work 

Instead you have to change permission to all specific folder that needs public access.

Because i think that flutter get installed public so the admin have to give 777 permision to all the folders where flutter downloads the precahe. Thats how i solved the problem.

Let me know if you have me to explain anything, i will be happy to help.

Thanks

**Comment by crypto-maria** [comment]
> @crypto-maria Can you explain that with different words? 👍

**Comment by riodw** [comment]
I am having the same problem.

I am on mac os 10.14.6

**Comment by crypto-maria** [comment]
> I am having the same problem.
> 
> I am on mac os 10.14.6

See the aolve thatvi have mentioned while closing the issue

**Comment by vineet8588** [comment]
I had a similar problem on my Ubuntu 20.04. I just deleted the .gradle folder in my home directory and ran 'flutter precache' again to solve it. Worth giving it a shot I think.

**Comment by riodw** [comment]
> give the permissions to `zsh`

How do you do that? (I just updated to macOS 10.15.4 don't know how that works)

**Comment by maganap** [comment]
I was getting gradle errors as well, until I read here:  https://github.com/flutter/flutter/issues/53043
I had to install "JDK 1.8 not latest".

Reading here:
https://www.oracle.com/java/technologies/javase-downloads.html
There's SDK 14, 11 and 8...   That's when I noticed I was installing SDK14 (the latest) instead of SDK 8 (which leads to 1.8 as explained in the other thread):

https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

I guess this'll bring other issues latter but at least that's how I was able to run `flutter precache`

**Comment by pleabargain** [comment]
follwwing instructions here:
https://flutter.dev/docs/get-started/install/linux#run-flutter-doctor
I ran flutter precache and got error
<pre>Downloading Material fonts...                                       0.6s
Downloading Gradle Wrapper...                                       0.1s
<font color="#CC0000">Failed to download the Android dependencies</font>                             
</pre>

**Comment by aaroncemery** [comment]
I'm not sure if others are still having this issue, but for me i needed to install Android Studio. Once i did that all Android Maven dependencies downloaded fine.

**Comment by ronopolis** [comment]
> give the permissions to `zsh` as new terminal seems to be more strict in third party downloads.
> after giving proper permissions, the problem should be gone.

The reason people are still having issues is your answer is correct, but isn't helpful. Unless you now which directories to chmod 777, your answer is no help.

**Comment by daixianceng** [comment]
> > give the permissions to `zsh` as new terminal seems to be more strict in third party downloads.
> > after giving proper permissions, the problem should be gone.
> 
> The reason people are still having issues is your answer is correct, but isn't helpful. Unless you now which directories to chmod 777, your answer is no help.

try `chmod -R 777 flutter/bin/`

**Comment by clichedmoog** [comment]
I've installed java and after that re run ```flutter precache``` without any failed messages.
