### ISSUE TITLE
Tap target on upper-left menu icon is smaller than 48dp

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5201]
We see lots of missed taps on iOS when trying to open the drawer from the menu icon in the app bar. We've reached the "more than anecdotal" stage for this issue.

**Comment by eseidelGoogle** [comment]
This is probably easier to fix, but adding the back gesture (https://github.com/flutter/flutter/issues/4817) might also reduce how often users hit this.

**Comment by sethladd** [comment]
We'll need both. But it's painful to watch a user tap repeatedly to access our menu.

**Comment by Hixie** [comment]
There's a debug flag you can enable to show hit targets, which might help us determine what's up here.

**Comment by sethladd** [comment]
One way to compare: open the News app from iOS, which also has a back chevron in the upper left. Then, tap on the wifi signal in the status bar. In the news app, it triggers the back action. In the flutter gallery, it doesn't trigger the back action.

**Comment by Hixie** [comment]
I can fix this in the framework, but it needs https://github.com/flutter/flutter/issues/5446 first.

**Comment by Hixie** [comment]
(note that our behaviour on Android and iOS is the same here. I don't understand why this is causing more problems on iOS.)

**Comment by sethladd** [comment]
Testing Gallery on 5X, we are definitely missing taps here.

**Comment by dragostis** [comment]
@sethladd This is just a small regression that @HansMuller has a fix for. It is not related to the issue on iOS.

Last time I checked, we weren't getting pointer events at all here. Still need to check.

**Comment by sethladd** [comment]
Cool, glad to hear this isn't related, and that we have a fix!

**Comment by sethladd** [comment]
We'd like to turn our attention to releasing gallery for iOS. I presume this is something we'll want to do in the near-term? If not, we can move out of this milestone.

**Comment by Hixie** [comment]
I think @HansMuller fixed this, no?

**Comment by sethladd** [comment]
Hi @HansMuller were you working on this? I seem to remember some work on tap targets recently.

**Comment by HansMuller** [comment]
I haven't addressed this specific issue recently. However there's a similar issue that's not platform specific: https://github.com/flutter/flutter/issues/3280

I was going to try and resolve #3280 by effectively extending the left toolbar button's gesture detector to the left edge of the screen. It's not clear if that will address this issue as well. Both platforms should really behave the same way vis the app bar buttons.

**Comment by eseidelGoogle** [comment]
@cbracken or @xster can you evaluate if you believe this needs to be a milestone 1 issue?

**Comment by eseidelGoogle** [comment]
Oh, sorry, I misread.  I thought this was iOS specific.  Sounds like this is entirely a framework thing that Hans may have fixed, but we need to verify.

**Comment by xster** [comment]
Not platform specific. I just tested a bit. It's sometimes a bit annoying but it's not that bad. Putting it in 2 for now but will take a timeboxed look today to see if it's an easy fix.

**Comment by xster** [comment]
Chatted offline with @abarth. The decision to use finger center touch detection was deliberate.

Looking at the widget tree:
![flutter_03](https://cloud.githubusercontent.com/assets/156888/23086587/b59b1a58-f522-11e6-8720-021d997f0517.png)

The RawGestureDetector is painted purple in this case. There's a bit missing on the left which we'll fix. But otherwise the existing box is accurate to the pixel in terms of responding to touch according to Android's 'show touches' developer options. 

The easy non-philosophically involved fix here is just to make sure that the button is properly 48dp in both actual size and hit box size as recommended by material (it's currently 40x56 for some reason). Otherwise, we won't change how touch handling works.

**Comment by xster** [comment]
Just to document the numbers, seems like all our buttons on the app bar are 40dp wide. 
![flutter_05](https://cloud.githubusercontent.com/assets/156888/23087623/8b52a7fe-f52a-11e6-8da6-d0d4295ea096.png)

There wasn't anything specific here
https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size

So I'll just remove the padding on the leading side, make the leading button 56x56, reduce the padding on the trailing side to 4dp and make the action buttons 48x56

**Comment by eseidelGoogle** [comment]
What magic did you use to draw all those fancy things in the status bar?

**Comment by xster** [comment]
It's just stuff in the Android [Developer options](https://cloud.githubusercontent.com/assets/156888/23088158/bb7f356a-f52e-11e6-89ce-6776e2efe3d8.png)
