### ISSUE TITLE
DropdownMenuItem has two yellow underlines

### ISSUE THREAD

**Issue by donnkii** [flutter/flutter#52018]
## Steps to Reproduce

1. Use DropdownMenuItem

**Expected results:** Normal clean text

**Actual results:** Text with two yellow underlines
 
**Similar issue:** https://github.com/flutter/flutter/issues/12548

![Screenshot_20200305-165821](https://user-images.githubusercontent.com/58042472/75999950-3cee1d00-5f03-11ea-9163-6049daf8d23f.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @donnkii 
can you please provide your `flutter doctor -v` and minimal code sample to reproduce the problem?
Thank you

**Comment by donnkii** [comment]
### flutter doctor -v

[✓] Flutter (Channel master, v1.15.10-pre.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.10-pre.4 at /home/donat/Development/flutter_linux_v1.9.1+hotfix.6-stable/flutter
    • Framework revision c2ae654ddf (25 hours ago), 2020-03-05 08:03:26 +0100
    • Engine revision 7df0a6e35e
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 8e5354dccb)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/donat/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • ONEPLUS A6013 • fef8f0bc   • android-arm64  • Android 10 (API 29)
    • Linux         • Linux      • linux-x64      • Linux
    • Chrome        • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server    • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.


### **Sample code**
```
import 'package:flutter/material.dart';


class SettingsView extends StatefulWidget {
  @override
  _SettingsViewState createState() => _SettingsViewState();
}

class _SettingsViewState extends State<SettingsView> {
  String value = '5';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xff2C3748),
      appBar: AppBar(
        title: Text('Settings', key: Key('settingsHeader')),
      ),
      body: Padding(
        padding: const EdgeInsets.only(top: 24.0),
        child: Column(children: <Widget>[
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Flexible(
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                      'How many recent time entries would you like to see: ',
                      style: TextStyle(color: Colors.white, fontSize: 16)),
                ),
              ),
              Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Theme(
                    data: Theme.of(context).copyWith(
                      canvasColor: Color(0xff2C3748),
                    ),
                    child: DropdownButton<String>(
                      value: value,
                      icon: Icon(
                        Icons.arrow_drop_down,
                        color: Colors.white,
                      ),
                      iconSize: 16,
                      elevation: 16,
                      style: TextStyle(color: Colors.white, fontSize: 16),
                      underline: Container(
                        height: 1.5,
                        color: Colors.white,
                      ),
                      onChanged: (String newValue) {
                        setState(() {
                          value = newValue;
                        });
                      },
                      items: <String>[
                        '1',
                        '2',
                        '3',
                        '4',
                        '5',
                        '6',
                        '7',
                        '8',
                        '9',
                        '10'
                      ].map<DropdownMenuItem<String>>((String value) {
                        return DropdownMenuItem<String>(
                          value: value.toString(),
                          child: Text(value.toString()),
                        );
                      }).toList(),
                    ),
                  ))
            ],
          ),
        ]),
      ),
    );
  }
}

**Comment by VladyslavBondarenko** [comment]
Thanks @donnkii,

<details>
 <summary>A bit shorter, but still representative code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: SettingsView()));

class SettingsView extends StatefulWidget {
  @override
  _SettingsViewState createState() => _SettingsViewState();
}

class _SettingsViewState extends State<SettingsView> {
  String value = '5';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xff2C3748),
      appBar: AppBar(
        title: Text('Settings', key: Key('settingsHeader')),
      ),
      body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Theme(
            data: Theme.of(context).copyWith(
              canvasColor: Color(0xff2C3748),
            ),
            child: DropdownButton<String>(
              value: value,
              style: TextStyle(color: Colors.white, fontSize: 16), //no underlines when you comment this line
              onChanged: (String newValue) {
                setState(() {
                  value = newValue;
                });
              },
              items: <String>[
                '1',
                '2',
                '3',
                '4',
                '5',
                '6',
                '7',
                '8',
                '9',
                '10'
              ].map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value.toString(),
                  child: Text(value.toString()),
                );
              }).toList(),
            ),
          )),
    );
  }
}
```

</details>

Yes, isn't reproduced on stable v1.12.13+hotfix.8 and dartpad

**Comment by johnsonmh** [comment]
I just bisected, and found this as the culprit: https://github.com/flutter/flutter/pull/51517

I believe that after https://github.com/flutter/flutter/pull/51517, the text style being passed into `DropdownButton` is being merged with the `_errorTextStyle` in [MaterialApp](https://github.com/flutter/flutter/blob/91b0bcf1a8a192e8135a9289310d81deba5824ec/packages/flutter/lib/src/material/app.dart#L26).

@GaryQian

**Comment by erdemyerebasmaz** [comment]
When can we expect this change to be reflected to **beta** channel?

![image](https://user-images.githubusercontent.com/4012752/77010150-4d2ddf80-697a-11ea-8ffe-99c6378c2d3a.png)

**Comment by Kav47** [comment]
This issue still exists on Flutter "beta":  v1.15.17  Ref: 2294d75. Upgrading to "dev" channel solves this issue (Channel dev, v1.16.1)
