### ISSUE TITLE
showDialog should allow a navigatorKey to be passed in

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#52015]
`ShowDialog` should allow a `navigatorKey` to be passed in as a parameter for situations where the widget is above the Naivgator.

**Comment by TahaTesser** [comment]
Hi @jimmyff 
If I'm not mistaken `showDialog` needs `MaterialLocalizations`, which gets added implicitly by the MaterialApp widget. [reference](https://stackoverflow.com/a/56275856)

Maybe for this reason this is not possible 
Thank you

**Comment by chunhtai** [comment]
May I know what is the use case you are trying to solve?

**Comment by jimmyff** [comment]
Hey @chunhtai I'm using the `builder` parameter in `MaterialApp` which returns a `Scaffold` with `body: child` - this way I can have a persistent bottom panel in my app whilst keep routing working. I need a persistnent bottom panel as my app allows users to watch videos as they continue to browse the rest of the app. I wanted to show a dialog from the scaffold / drawer in the app however I couldn't hence this ticket. 

It feels like many of the flutter widgets such as dialogs, drop downbuttons ([see issue](https://github.com/flutter/flutter/issues/52016#issuecomment-595298125)) etc don't work becuase they need to accept a `navigatorKey` for routing or they are reliant on MaterialLocalizations. However thisis the only way to achieve the functionality I need to my knowledge. My app is available in the [play store](https://play.google.com/store/apps/details?id=app.eurovision.mobile) if you want to see my use-case.

**Comment by chunhtai** [comment]
hi @jimmyff see my comment in https://github.com/flutter/flutter/issues/52016#issuecomment-595298125

**Comment by jimmyff** [comment]
@chunhtai thanks for the feedback on the other ticket.

Another related quick question: How do you suggest doing a one time dialog on app start? The logical place would be on initState of a main widget like the app, but the problem is the context isn't available at this point. I've seen some solutions using awaiting delayed futures but this seems a bit hacky and might not be very robust, is there a recommended way to do this?

Thanks

**Comment by chunhtai** [comment]
@jimmyff This is a stackoverflow question. I cannot give a recommendation over which way is better. you have reference to context in State class, however it might not fully initialize during initstate. One way to do it will be scheduling a post frame call back to show the dialog to make sure it was initialized and laid out.

**Comment by chunhtai** [comment]
I will close this issue. Let me know if there is anything else i have not addressed
