### ISSUE TITLE
[web] Text with TextAlign.justify not work on iPhone

### ISSUE THREAD

**Issue by andrea689** [flutter/flutter#52019]
When I use:

```dart
Text(
  'my long text',
  textAlign: TextAlign.justify,
),
```

In the Mac Chrome and Safari working fine and also in Android Chrome, but not in the Safari and in Chrome for iOS.

I have investigated and I found that the problem is caused by `white-space: pre-wrap;` that not work with `text-align: justify;`.

**Comment by pedromassangocode** [comment]
Hi @andrea689 
Are you still having this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and the expected vs actual results?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by rithviknishad** [comment]
Having the same issue.

<details>
<summary>

`flutter doctor -v`
</summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_IN)
    • Flutter version 2.2.1 at /home/coffeelake/development/flutter
    • Framework revision 02c026b03c (7 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/coffeelake/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Steps to reproduce:**

```dart
Text(
    _paragraph,
    textAlign: TextAlign.justify,
),
```

**My Observations:**

 - `flutter build web` (default web rednerer)
 Works fine on desktop browser
 `TextAlign.justify` not effective on mobile browsers.
 
- `flutter build web --web-renderer canvaskit`
Works fine on both mobile and desktop.

- `flutter build web --web-renderer html`
`TextAlign.justify` not effective on both desktop and mobile browser.

 - flutter run -d chrome
`TextAlign.justify` not effective.


</details>

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
