### ISSUE TITLE
Nested Scrollable in the same direction: Defer the scroll to the outer Scrollable when the inner Scrollable reaches the end

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#52010]
## Use case

The use-case is described in https://stackoverflow.com/questions/60543962/nesting-pageview-change-the-outer-pageview-when-the-inner-pageview-reaches-the

Consider a [PageView] usage where we have one [PageView] inside another one:

```dart
PageView(
  children: [
    Container(color: Colors.red),
    Column(
      children: [
        Text('Title'),
        PageView(
          children: [
            Container(color: Colors.green),
            Container(color: Colors.yellow),
          ],
        ),
      ],
    )
  ],
);
```

Such architecture will allow us to transition between the outer [PageView] to the inner [PageView]. But once we reached the inner [PageView] we can't get out anymore.

Here's a gif showcasing it:

[![enter image description here][1]][1]

In such architecture, we can't "merge" both [PageView]s into one, because the inner [PageView] doesn't fill the screen

  [1]: https://i.stack.imgur.com/eMYHQ.gif

[PageView]: https://api.flutter.dev/flutter/widgets/PageView-class.html

## Proposal

When a `Scrollable` reaches the end of its viewport and has an ancestor `Scrollable`, instead of a glow/overscroll it should defer the drag gesture to the ancestor `Scrollable`

**Comment by 327100395** [comment]
https://github.com/lwlizhe/flutter_tiktok/

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/50946

**Comment by ashok020** [comment]
Same i tried today .. let me know if u found any solution.

**Comment by TN888** [comment]
I finally solved this problem, but with ListView inside PageView.
I think they are the same thing.
here's the solution posted on SO:
https://stackoverflow.com/questions/67515358/how-to-put-listview-inside-pageview-and-scroll-both-of-them-vertically/67515359#67515359

**Comment by Piinks** [comment]
(Triage) I recently came across a few dupes of this issue. #50946 has the most upvotes, so I am going to close this and the rest to redirect there. For reference they are:
- #54827
- #50946
- #83279
- #81648 

Please follow #50946 for this issue. Thank you!
