### ISSUE TITLE
flutter doctor / vs2019 not successs

### ISSUE THREAD

**Issue by hist008** [flutter/flutter#52011]
[√] Flutter (Channel master, v1.15.10-pre.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.15.10-pre.4 at D:\flutter
    • Framework revision c2ae654ddf (5 hours ago), 2020-03-05 08:03:26 +0100
    • Engine revision 7df0a6e35e
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 8e5354dccb)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\SDK\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = E:\SDK\android-sdk-windows
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.5)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29806.167
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2019.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Chrome     • chrome     • web-javascript • Google Chrome 73.0.3683.103
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @hist008 
Please explain in detail what's the issue you're facing?
Thank you
