### ISSUE TITLE
Left Aligned ViewPort in Page View

### ISSUE THREAD

**Issue by vivekkannavenus** [flutter/flutter#52014]
## How it works
PageView widget looks cool but when we set viewportFraction, the view gets center aligned.

**If viewportFraction sets**
```
PageView(
   viewportFraction: 0.8
)
```
[Center-Aligned view port](https://i.stack.imgur.com/qRaLO.jpg)

## How I expect
But what I need is the view to start with left-aligned like how playstore dashboard works.

There should be some _gravity_ attribute and based on the value, 
the view has to start with the respective position.

[Left-Aligned view port](https://user-images.githubusercontent.com/60136315/75988599-d8898880-5f17-11ea-9a40-ca42b84f3ab7.png)
The above screenshot has taken from the Google Play Store.

I've also posted a query in StackOverflow
https://stackoverflow.com/questions/60547319/flutter-how-to-left-align-view-port-in-pageview

**Comment by VladyslavBondarenko** [comment]
Hi @vivekkannavenus 
Among similar I found only this https://stackoverflow.com/questions/56871898/align-a-flutter-pageview-to-the-screen-left
There is [gist](https://gist.github.com/rolurq/5db4c0cb7db66cf8f5a59396faeec7fa) in the solution, where I can change align by editing value in the line `final portion = (position.extentInside - itemDimension) / 2;`
But this is another case, not about `PageController` with `viewportFraction`

**Comment by vivekkannavenus** [comment]
@VladyslavBondarenko Thanks for referring the mere same stuff.
It works but has some stability issues like this code doesn't work effectively when page view items dynamically changing.

**Comment by yousifk** [comment]
It is helpful to add this feature.

**Comment by payam-zahedi** [comment]
Hi @VladyslavBondarenko , I want to create PR for this issue. I check out the source code and I saw there is a SliverFillViewport widget that maybe we can wrap it with align. do you have any idea about how can I solve this?

**Comment by spareblock** [comment]
Any update on this?

**Comment by ScottMacDougall** [comment]
Would love to see this addressed.

**Comment by PaulVinSoft249** [comment]
I have a solution for this... Would be happy to share... PR

**Comment by PaulVinSoft249** [comment]
![Uploading ezgif-2-67bd8fd1188f.gif…]()

**Comment by PaulVinSoft249** [comment]
![ezgif-2-67bd8fd1188f](https://user-images.githubusercontent.com/60345890/95621939-71622280-0a6a-11eb-81f6-fa75ce20d9b2.gif)

**Comment by dariel11** [comment]
> I have a solution for this... Would be happy to share... PR

Can you share the solution for alignin pagebuilder to the left?

**Comment by dariel11** [comment]
> I have a solution for this... Would be happy to share... PR

@PaulVinSoft249  Can you share the solution for alignin pageview to the left side?

**Comment by hello-paulvin** [comment]
@dariel11 
Yes bro,
I will be write a PR for this. But anyway I can share it.

**Comment by hello-paulvin** [comment]
https://gist.github.com/hello-paulvin/0aa8b6389e3aeb345fa1f3f246d9ab69#file-gistfile1-txt

You can open that and check it out :)

**Comment by divid3d** [comment]
> https://gist.github.com/hello-paulvin/0aa8b6389e3aeb345fa1f3f246d9ab69#file-gistfile1-txt
> 
> You can open that and check it out :)

Is there option to align to the left last item same as previous?

**Comment by harrisonturton** [comment]
This feature is important for making it possible to creating apps with a dynamic number of tabs.

We cannot use `TabBarView` and `TabController`, and various StackOverflowAn

**Comment by uzuki-P** [comment]
Any update on this?

**Comment by daixianceng** [comment]
`padEnds`还不能用啊

**Comment by srikanth-vm** [comment]
padEnds on which widget ? I don't see that option on page view.
