### ISSUE TITLE
android emulator not responding in android studio for flutter 

### ISSUE THREAD

**Issue by rjaftab786** [flutter/flutter#52026]
so many times my emulator , not responding , after so many attempts i finally use genymotion instead...
my cpu is ryzen 5 1600 , running windows 10.. please work on android studio ..

**Comment by VladyslavBondarenko** [comment]
Hi @rjaftab786 
Closing, as this doesn't seem to be an issue with Flutter,
if you disagree please write in the comments and I will reopen it
thank you
