### ISSUE TITLE
Gallery, Pesto: Bar of white pops into place after recipe finishes transition

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5202]
On Nexus 5X. Open Gallery, tap into Pesto. Tap a recipe. Notice how the recipe transitions into full screen.

Then, notice how, after the image and the recipe text finish transitioning, there's a white bar that pops into place, right above the recipe title.

Here's a video of the effect: https://www.youtube.com/watch?v=VC6spk7P6Xg&feature=youtu.be

**Comment by abarth** [comment]
This is regression I caused when I rejiggered the animation to go faster.
