### ISSUE TITLE
Option to auto save Flutter form

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#52027]
I noticed popular apps do not have a save button on forms, but somehow autosave once the user stops typing or navigates away. Would be nice, if Flutter would support such an option for forms.
https://flutter.dev/docs/cookbook/forms/validation

**Comment by giorgio79** [comment]
Hmm interesting thought. I was approaching it more from a Firebase integration perspective. If Flutter could provide sane auto saving out of the box that does not inundate Firebase with requests it would be great

**Comment by dnfield** [comment]
That would probably be something to ask for in the firebase plugin

**Comment by MunaimNaeem** [comment]
Hi,
My name is munaim. I want to make an flutter App which pick the number from newly arrive messages from unknown number or call from unknown number, and save that number into my phone contact list.
Thanks
Regards: Munaim
