### ISSUE TITLE
Gallery, Pesto: FAB has square shadow while transitioning up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5203]
Please see this movie, from my Nexus 5X: https://youtu.be/VC6spk7P6Xg

Notice how the FAB, while transitioning up, has a square shadow around it. It doesn't have the square the entire transition, but starting at second 3 of the transition.

**Comment by abarth** [comment]
This is a bug in Skia.  We ask skia what the bounding box of the fab is and it reports a size that goes out some number of standard deviations into the shadow but not sufficiently far to avoid this artifact.

**Comment by sethladd** [comment]
Thanks for the quick diagnosis. It's hard to notice at full speed, so probably not a high priority right now. If we know the Skia bug, we can link it here.

**Comment by abarth** [comment]
I don't think I've filed it against skia yet.  We should probably make a reduced test case for them.

**Comment by joeblew99** [comment]
@sethladd 
The video is an awesome way of documenting issues. 
How did you do the video screen capture ?

**Comment by eseidelGoogle** [comment]
Personally I use:
```
adb screenrecord /data/demo.mp4
adb pull /data/demo.mp4
```
Then send it to YouTube and file bug. :)  https://github.com/flutter/flutter/issues/3496 is on file about making that easier (and iOS enabled).

**Comment by sethladd** [comment]
What @eseidelGoogle said :)

**Comment by joeblew99** [comment]
@eseidel nice thanks

**Comment by sethladd** [comment]
This came up in a review from our material design team.

**Comment by eseidelGoogle** [comment]
Considering for M2 since this showed up in UX review.

**Comment by sethladd** [comment]
I'm not sure this is Pesto specific, so it might show an issue in our framework/engine. If so, M2 feels right.

**Comment by sethladd** [comment]
hi @chinmaygarde ! Do we think this is addressed?  (just doing a little cleanup)

**Comment by eseidelGoogle** [comment]
@chinmaygarde any update?  Is this the same as the other raster cache/shadow flash bug?

**Comment by chinmaygarde** [comment]
This is a duplicate of the raster cache issue being tracked here in [Flutter](https://github.com/flutter/flutter/issues/5231) and here in [Skia](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c9).

**Comment by eseidelGoogle** [comment]
@chinmaygarde This is fixed now, right?

**Comment by eseidelGoogle** [comment]
@chinmaygarde this is fixed, correct?

**Comment by chinmaygarde** [comment]
As mentioned earlier, the underlying issue was the same as that in https://github.com/flutter/flutter/issues/5231. However, in recent versions of the gallery, the raster cache does not seem to be considering this FAB for caching (maybe because the picture layer boundary was introduced at a higher level). So yes, this is "fixed". But the correct fix is the one applied for https://github.com/flutter/flutter/issues/5231.
