### ISSUE TITLE
Text Size isn't corresponding to Logical pixels

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#52038]
The `fontSize` docs say `The size of glyphs (in logical pixels) to use when painting the text.`

But I think there's something more here that's missing, here's a simple test:

```dart
Row(
  children: <Widget>[
    Text('TESTÇg', style: TextStyle(fontSize: 16),),
    Container(height: 16, width: 100, color: Colors.black,),
    Container(height: 100, width: 100, color: Colors.orange,),
  ],
)
```

The orange `Container` is to get the the `Row` boundaries out of the way.

The Black `Container` has a `height` of 16 logic pixels, same as the `fontSize` but its shorter than the `Text`. The `g` represents letters that get to the bottom of the `Text`, the `Á` the ones that get to the top, so clearly the `Text` is bigger than 16 logic pixels:

![image](https://user-images.githubusercontent.com/8120472/76020309-f0561200-5f01-11ea-8d4e-0fc41a0cda01.png)

![image](https://user-images.githubusercontent.com/8120472/76020563-6a869680-5f02-11ea-91bf-85c7a059d4da.png)

I know typography isn't simple, I don't think there's anything wrong with the `Text` itself, but I think the docs aren't right. I found this because I wanted to make a `Container` the same size as a `Text`, but they didn't match and the docs didn't help me.

**Comment by blackmakerblm** [comment]
I am facing the same issue I have a text widget and the fontsize is 20 i even added textScaleFactor =1.0 but the logical pixel is far more than 20 and it's overlowing the container

**Comment by feinstein** [comment]
Give the fist post a 👍🏻 so the Flutter team can prioritize it.

**Comment by blackmakerblm** [comment]
this works for me try it: define the **height** of your text and give it value 1 click here for more infohttps://api.flutter.dev/flutter/painting/TextStyle/height.html

**Comment by suryarajat** [comment]
> this works for me try it: define the **height** of your text and give it value 1 click here for more info https://api.flutter.dev/flutter/painting/TextStyle/height.html

Thanks. Worked for me.
