### ISSUE TITLE
Considering Color.fromRGBA instead of fromARGB

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5205]
Feedback from a developer familiar with the web. They noticed that Flutter uses "ARGB" (for example, https://docs.flutter.io/flutter/rendering/Color/Color.fromARGB.html) but the web uses "RGBA" (for example, in CSS).

To more easily leverage the color converters out there, and existing docs around color and the web, Flutter could consider thinking in "RGBA" instead of "ARGB".

(not sure if there was a reason we went with ARGB?)

**Comment by sethladd** [comment]
cc @Hixie

**Comment by abarth** [comment]
Is the "instead" part important or would Color.fromRGBA in addition to Color.fromARGB be acceptable?

> not sure if there was a reason we went with ARGB?

It's how Skia prefers to pack the bits.

**Comment by a14n** [comment]
Having two really close names (`fromRGBA` and `fromARGB`) with the same types for parameters could be error prone IMHO.

**Comment by Hixie** [comment]
CSS doesn't have a way to provide ARGB as a single hex code, does it? Just `rgba(.., .., .., ...)`.

In which case we could have `const Color(0xAARRGGBB)` and `new Color.fromRGBA(rr, gg, bb, aa)`, where the former is significantly preferred but the latter is available when you need to switch from CSS to Flutter.

**Comment by eseidelGoogle** [comment]
The same developer also commented that our handling of Alpha as a byte instead of a float felt odd coming from a CSS background.  So fromRGBA might need to be (byte, byte, byte, float) to feel like CSS.

**Comment by Hixie** [comment]
Agreed.

**Comment by abarth** [comment]
We're inconsistent about where we use a byte or a float.  We should make sure we're consistent.  (Typically we call the float "opacity" and the byte "alpha" but I'm not sure how consistent we are about that.)

**Comment by Hixie** [comment]
I think we should use that convention in general but in this specific case I think we should still call it fromRGBA (not fromRGBO or fromRgbAndOpacity) because then it matches CSS, which is the point.

The documentation for that method should only refer to the fourth argument as the "opacity" though.

**Comment by Hixie** [comment]
(Looking at this with fresh eyes, I must admit that I'm not sure I feel as strongly about my last comment as I did when I wrote it. Maybe Color.fromRGBO is the way to go, for internal consistency.)

**Comment by abarth** [comment]
@Hixie says `Color.fromRGBO` is the one true name.

**Comment by abarth** [comment]
Not sure how to get from opacity (which is a double) to the internal representation (which is an int) as a const expression...
