### ISSUE TITLE
Apropos error when building from .xcodeproj instead of .xcworkspace

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#52059]
Users sometimes accidentally build their project from the .xcodproj instead of the .xcworkspace which will result in linker errors if they are using plugins.

Ideally, instead of getting linker errors, we could print out an error that the project should be built from the .xcworkspace instead.

Example issue: https://github.com/flutter/flutter/issues/51992

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/10770.
