### ISSUE TITLE
Azure bot detector is slowing down flutter tool startup by at least a second

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#52065]
`flutter run` takes a very long time. It wasn't always like this, but I just upgraded to the latest `master` (sorry I don't know the previous revision I was using), and how it is super-slow. Like 2 minutes slow. I'm sure it was on the order of 10 seconds before.

Even `flutter help` is very slow:

```
$ time flutter help
Manage your Flutter app development.
...
real	0m5.503s
user	0m0.616s
sys	0m0.195s
```

## Steps to Reproduce

1. Run `time flutter help`.
2. It shouldn't take over 5 seconds!

I 50% suspect it is the shitty ESET Antivirus I have on this Mac. Unfortunately I don't have access to disable it.

<details>
  <summary>Logs</summary>

Unfortunately `flutter help --verbose` does not show anything, and the huge pause for `flutter run` seems to be before the first output of the logs, i.e. the line that says +28 ms here actually appears about a minute after I run the command:

```
$ flutter run --verbose
[  +28 ms] executing: [/Users/me/local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
```

```
[✓] Flutter (Channel master, v1.15.12-pre.8, on Mac OS X 10.14.4 18E226, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)
```

</details>

**Comment by jonahwilliams** [comment]
Perhaps you could try a few different things to help us narrow down the issue. Assuming `FLUTTER_ROOT` is where the SDK is located:

Run the tool from source bypassing the startup script:

`time FLUTTER_ROOT/bin/cache/dart-sdk/bin/dart FLUTTER_ROOT/pacakges/flutter_tools/bin/flutter_tool.dart help`

Run the tool from the snapsnot bypassing the startup script:

`time FLUTTER_ROOT/bin/cache/dart-sdk/bin/dart FLUTTER_ROOT/bin/cache/flutter_tools.snapshot help`

**Comment by Timmmm** [comment]
```
$ time bin/cache/dart-sdk/bin/dart packages/flutter_tools/bin/flutter_tools.dart help
Manage your Flutter app development.
...
real	1m24.479s
user	0m12.144s
sys	0m1.200s

$ time bin/cache/dart-sdk/bin/dart bin/cache/flutter_tools.snapshot help
Manage your Flutter app development.
...
real	1m15.707s
user	0m0.587s
sys	0m0.180s
```

Ouch! Note the time taken is highly variable so I don't think this is doing anything different to when it took 5 seconds.

I tried some more things:

* `time bin/cache/dart-sdk/bin/dart --help`: 0.02s.
* `time bin/cache/dart-sdk/bin/dart hello_world.dart`: 0.2s
* Run under `lldb`, but it immediately says `process exited with status -1`.
* Attach to running process, but `lldb` says `error: attach failed: Error 1` (apparently something to do with Apple's security stuff).
* Use `dtruss`, but I have System Integrity Protection enabled so it doesn't work (not sure if I have access to disable it - haven't tried yet).
* Tried Instruments' filesystem activity monitor - didn't show any file accesses at all. Or maybe it just didn't work.
* Tried System Trace - couldn't figure out how to make it only show one process, even if you only record one process...

:-( Are there any more logging options for `dart`?

**Comment by toda-bps** [comment]
I have the same problem, and I found that the flutter command was **executed quickly when I was offline**.

@jonahwilliams  Does the flutter command do any dns lookup?

I feel this problem is similar to the problem solved by `UseDNS=no` in sshd, for example.

**Comment by jonahwilliams** [comment]
I can repro this difference.

`time flutter` for me is 1.5 seconds when connected to internet, 0.5 seconds when offline.

**Comment by jonahwilliams** [comment]
The issue is the azure bot detector as implemented is blocking the tool startup. I can remove the measurable difference with the following tool diff:

```
diff --git a/packages/flutter_tools/lib/src/base/bot_detector.dart b/packages/flutter_tools/lib/src/base/bot_detector.dart
index cb206ae00..b895be212 100644
--- a/packages/flutter_tools/lib/src/base/bot_detector.dart
+++ b/packages/flutter_tools/lib/src/base/bot_detector.dart
@@ -19,7 +19,7 @@ class BotDetector {
     );
 
   final Platform _platform;
-  final AzureDetector _azureDetector;
+  final AzureDetector _azureDetector; // ignore: unused_field
 
   bool _isRunningOnBot;
 
@@ -68,10 +68,13 @@ class BotDetector {
       || _platform.environment.containsKey('SWARMING_TASK_ID')
 
       // Property when running on borg.
-      || _platform.environment.containsKey('BORG_ALLOC_DIR')
+      || _platform.environment.containsKey('BORG_ALLOC_DIR');
       // Property when running on Azure.
-      || await _azureDetector.isRunningOnAzure;
+      // || await _azureDetector.isRunningOnAzure;
   }
 }
```

This regression didn't show up in our devicelab since we register those as bots, so we never hit it. This seems to be overhead added to each flutter command, for example flutter test without the above diff:

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ time flutter test
00:01 +1: All tests passed!                                                                                                                     

real	0m3.671s
user	0m2.547s
sys	0m0.695s
```


and with the diff (no bot detector)

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ time flutter test
00:01 +1: All tests passed!                                                                                                                     

real	0m2.656s
user	0m2.514s
sys	0m0.708s
```

**Comment by jonahwilliams** [comment]
While the overall connection timeout is set to a second, the http client must separately resolve the  service url, which probably involves a separate DNS query that isn't a part of the request timeout. So you were totally right @toda-bps
