### ISSUE TITLE
Update null branch property with 'master' for Checklist in datastore 

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#52066]
With recent updates of cocoon to support Flutter branching, we have a newly added property `Branch` for `Checklist` in datastore.

New incoming entries will have branch info, while old data has `null`. It would be consistent to update all old entries to have value `master` replacing `null`.

The above operation will help build index for those old data as well. (some context: we have created a new composite index, which doesn't cover old data)

**Comment by digiter** [comment]
Triage: it's done.
