### ISSUE TITLE
Update animation docs to explain when you should dispose animations

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5206]
Looking at the flutter source code this seems to be done in [some places](https://github.com/flutter/flutter/blob/3cbb20d176c950effb7d1479661fbe87c8e8ef91/packages/flutter/lib/src/material/toggleable.dart#L201) but [not others](https://github.com/flutter/flutter/blob/b006ca556d7e44c7aafda3a6b5a4637e1000def6/examples/layers/widgets/spinning_square.dart). The [animations page](https://flutter.io/animations/) makes no mention of dispose.

**Comment by abarth** [comment]
Usually, yes.  Typically one object will be responsible for an animation controller.  For example, it will start it under various circumstances.  That object should stop the animation controller in dispose.  The spinning_square.dart example should do that but is currently a bad example.

**Comment by abarth** [comment]
We should also update the animations page with this information.

**Comment by Hixie** [comment]
Best practice is that any object with a `dispose` method should, in its `dispose` method, call the `dispose` method of all the objects it owns that also have `dispose` methods. In general, always call `dispose` on an object with such a method if you are done with that object.

**Comment by eseidelGoogle** [comment]
FYI @LarkAscending (just in case a new animation page is being considered, not suggesting any higher priority).

**Comment by goderbauer** [comment]
This is called out pretty clearly in the docs now: https://github.com/flutter/flutter/blob/84aa29ce639492ad183ac972cf325b0e180c1d26/packages/flutter/lib/src/animation/animation_controller.dart#L108-L113
