### ISSUE TITLE
The method 'call' was called on null. Using GestureDetector

### ISSUE THREAD

**Issue by Hinal1108** [flutter/flutter#52087]
══╡ EXCEPTION CAUGHT BY GESTURE╞══════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack:
I/flutter (25590): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53)
I/flutter (25590): #1      ........
I/flutter (25590): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
I/flutter (25590): #3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
I/flutter (25590): #4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264)
I/flutter (25590): #5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236)
I/flutter (25590): #6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
I/flutter (25590): #7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222)
I/flutter (25590): #8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
I/flutter (25590): #9      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
I/flutter (25590): #10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
I/flutter (25590): #11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
I/flutter (25590): #15     _invoke1 (dart:ui/hooks.dart:274)
I/flutter (25590): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:183)

I/flutter (25590): (elided 3 frames from package dart:async)
I/flutter (25590): Handler: "onTap"
I/flutter (25590): Recognizer:
I/flutter (25590):   <optimized out>#b7931

**Comment by TahaTesser** [comment]
Hi @Hinal1108 

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

Thank you

**Comment by Hinal1108** [comment]
flutter doctor -v

<img width="810" alt="Screenshot 2020-03-07 at 9 40 40 AM" src="https://user-images.githubusercontent.com/39479261/76136460-c6aeff00-6057-11ea-82e3-d355fb4a2d92.png">

flutter run --verbose

<img width="871" alt="Screenshot 2020-03-07 at 9 44 12 AM" src="https://user-images.githubusercontent.com/39479261/76136497-4210b080-6058-11ea-8fde-6c222005b3d6.png">

**Comment by TahaTesser** [comment]
Hi @Hinal1108 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @Hinal1108 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
