### ISSUE TITLE
While using Flutter for web, the view is not loading in Iframe of any other frame such as vue

### ISSUE THREAD

**Issue by yogesh-xseed** [flutter/flutter#52086]
## Use case
When you want to use the build of flutter for web inside an iframe 

## Proposal
When you want to to pass data between parent app to an iframe we can do in other simple html but when it comes to Flutter for web it is not working and the Widget itself is not getting loaded in any other iframe only the index.html part is Loading. If this feature is enable then it would really help developer who want to pass data from one big application of different framework to the another big project of flutter. Some might suggest to pass via API but it will have authentication issue.

**Comment by TahaTesser** [comment]
Hi @yogesh-xseed 

Does this [comment](https://github.com/flutter/flutter/issues/32329#issuecomment-527728480) solves this issue?

Related to [#32329](https://github.com/flutter/flutter/issues/32329)

Thank you

**Comment by yogesh-xseed** [comment]
I could solve the issue using  js package of dart.

**Comment by yogesh-xseed** [comment]
But it has an issue that i have to build the project every time i make changes As it serves in web-socket.

**Comment by TahaTesser** [comment]
Hi @yogesh-xseed 

Since ti's a dark package, you can raise your issue on their [github](https://github.com/dart-lang/sdk/issues)

Thank you
