### ISSUE TITLE
RenderRepaintBoundary can not capture scenes like camera preview or AR views

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#52082]
RenderRepaintBoundary can not capture scenes like camera preview or AR views, can fix it?

**Comment by TahaTesser** [comment]
Duplicate of [#18989](https://github.com/flutter/flutter/issues/18989)

**Comment by qiuguian** [comment]
no way to fix it?  just tell me the duplicate issue?

**Comment by TahaTesser** [comment]
Hi @qiuguian 

Please follow up the mentioned issue 

Thank you
