### ISSUE TITLE
Flutter drive tests suddenly stop working when I try to tap a widget its happening only with that widget

### ISSUE THREAD

**Issue by endritgojani** [flutter/flutter#52099]
Logs:

Shell: Running scenario: TEST # ./test_driver/features/BMS.feature:4
Shell:    √ And Test Home Page # ./test_driver/features/BMS.feature:6 took 2094ms
Shell: PASSED: Scenario TEST # ./test_driver/features/BMS.feature:4
Shell: 1 scenario (1 passed)
Shell: 1 step (1 passed)
Shell: 0:00:02.318000
Shell: Terminating Flutter app under test
Shell: [warning] FlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005

**Comment by TahaTesser** [comment]
Hi @endritgojani 

an you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

Thank you

**Comment by endritgojani** [comment]
@TahaTesser 

I found needs to put sleep after action

example:

```
 await _driver.tap(buildingItem);
 sleep(const Duration(seconds: 1));
```
