### ISSUE TITLE
FlutterFragemnt  extends Fragment(depends support-v4) problems

### ISSUE THREAD

**Issue by szhlliuchao** [flutter/flutter#52097]
![888](https://user-images.githubusercontent.com/16315711/76073961-768f5880-5fd5-11ea-85be-463061d79c7b.png)

**Comment by szhlliuchao** [comment]
my project use androidX

**Comment by szhlliuchao** [comment]
flutter_embedding_debug-1.0.0  use support library that is support-v4

**Comment by szhlliuchao** [comment]
my flutter:
![7777](https://user-images.githubusercontent.com/16315711/76075197-8871fb00-5fd7-11ea-9188-6cdef3d1f76c.png)

my android studio:
![6666](https://user-images.githubusercontent.com/16315711/76075265-a8a1ba00-5fd7-11ea-94f4-4c702ecb5867.png)

**Comment by TahaTesser** [comment]
Hi @szhlliuchao 

Could you please take a look this possible [solution](https://github.com/flutter/flutter/issues/29819#issuecomment-476382343)

Thank you

**Comment by szhlliuchao** [comment]
I use the latest version of flutter and my project already supports AndroidX . Why is there such a problem? Why is this happening? please tell me the reason. Is there a reason why I use the old version of the library, the old version of the library does not support androidX? If a partner knows, please answer the question for me, thank you very much. Finally, I want to know what causes this problem and how to solve it?

**Comment by TahaTesser** [comment]
Hi @szhlliuchao 
Could you please provide your `flutter run --verbose`? 
To better address the issue, would be helpful if you could post a self contained app on github
or the steps to reproduce it.
 Thank you

**Comment by MorningGu** [comment]
I had the same problem. flutter_embedding_debug-1.0.0 use support library that is support-v4,but my project use androidx,my flutter is 1.12.13+hotfix.8

**Comment by szhlliuchao** [comment]
你好，这个问题不会影响到编译，不要使用fragment形式接入flutter的view，建议使用flutterView的方式，这样就不报错了，可以正常编译打包，不存在任何问题！
如果还有问题欢迎加我微信共同探讨！微信号：liuchaobuaa




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MorningGu"<notifications@github.com&gt;; 
发送时间: 2020年3月28日(星期六) 下午4:30
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "刘超"<1203503422@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] FlutterFragemnt  extends Fragment(depends support-v4) problems (#52097)





 
I had the same problem. flutter_embedding_debug-1.0.0 use support library that is support-v4,but my project use androidx,my flutter is 1.12.13+hotfix.8

**Comment by iapicca** [comment]
Hi @szhlliuchao 
I'm not sure from your last message if the issue has been resolved,
if this is not the case please follow the indication provided [above](https://github.com/flutter/flutter/issues/52097#issuecomment-596459415)
thank you

**Comment by qxmmxi** [comment]
I had the same problem. .flutter_embedding_debug-1.0.0 use support library that is support-v4,but my project use androidx. 

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Applications/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xixiaona/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xixiaona/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you

**Comment by lhhuu** [comment]
I Have a problem when inject with koin(by inject()) by FlutterFragmentActivity, Please help me

**Comment by lhhuu** [comment]
When I use FlutterActivity ,my extendsion class  get red line 
I think this probem relate to android x
import android.arch.lifecycle.Lifecycle;
import android.arch.lifecycle.LifecycleOwner;
import android.arch.lifecycle.LifecycleRegistry;

**Comment by MorningGu** [comment]
> When I use FlutterActivity ,my extendsion class get red line
> I think this probem relate to android x
> import android.arch.lifecycle.Lifecycle;
> import android.arch.lifecycle.LifecycleOwner;
> import android.arch.lifecycle.LifecycleRegistry;

You can update flutter version to 1.17.0. Today,i update my flutter  from 1.12.13-hotfix9 to 1.17.0. This problem is be solved in this versioin.
