### ISSUE TITLE
Option to disable CupertinoSegmentedControl

### ISSUE THREAD

**Issue by erf** [flutter/flutter#52105]
## Use case

I was not able to disable the `CupertinoSegmentedControl` in a case where i did not want the user to edit some data.

I could perhaps use the `AbsorbPointer` widget, but i still would like the style to change when it's disabled and not only disable input.

## Proposal

I would like to either have an `enabled` option on `CupertinoSegmentedControl`, which when false it can't be pressed and it will be displayed as disabled, e.g. "grayed out". 

Another option would perhaps to have it disabled when `onValueChanged ` is `null`.

**Comment by erf** [comment]
For iOS you have:
```
https://developer.apple.com/documentation/uikit/uisegmentedcontrol/1618567-setenabled
```

**Comment by LongCatIsLooong** [comment]
Semirelated: https://github.com/flutter/flutter/issues/43826

**Comment by dattran-pt19** [comment]
I found this way to resolve issue, you need to use a _selectedIndex to depend when you apply change index, my code below
`class AppSegmentedButton extends StatefulWidget {
  AppSegmentedButton(
      {super.key,
      required this.data,
      this.size = AppButtonSize.small,
      required this.selectedIndex,
      this.disableIndex,
      this.onChangeValue})
      : assert(data.isNotEmpty, "Danh sách không được rỗng");

  final AppButtonSize size;
  final List<AppSegmentedData> data;
  final ValueNotifier<int> selectedIndex;
  final ValueChanged<int>? onChangeValue;
  final int? disableIndex;

  @override
  State<StatefulWidget> createState() => _AppSegmentedButtonState();
}

class _AppSegmentedButtonState extends State<AppSegmentedButton> {
  late int _selectedIndex = widget.selectedIndex.value;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: widget.selectedIndex,
      builder: (_, child) => CupertinoSlidingSegmentedControl<int>(
        backgroundColor: AppColors().background,
        thumbColor: Colors.white,
        groupValue: widget.selectedIndex.value,
        onValueChanged: (value) {
          if (value != null) {
            widget.selectedIndex.value = value;
            if (value != widget.disableIndex) {
              _selectedIndex = value;
            } else {
              widget.selectedIndex.value = _selectedIndex;
            }

          }
        },
        children: {
          for (var v in widget.data.asMap().entries)
            v.key: Container(
                height: widget.size.height,
                alignment: Alignment.center,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children:
                      getListData(v.value, _selectedIndex == v.key, true),
                ))
        },
      ),
    );
  }
}`

**Comment by JMApps** [comment]
Use IgnorePointer

**Comment by huycozy** [comment]
Adding demo for UISegmentedControl on iOS native. Based on its [setEnabled](https://developer.apple.com/documentation/uikit/uisegmentedcontrol/1618567-setenabled) method, it's possible to enable separate segments by index.


![Screen Recording 2024-08-03 at 01 38 52](https://github.com/user-attachments/assets/5698b2eb-8cae-4316-b50c-c4013fbf372e)

@LongCatIsLooong I see this issue is a part of https://github.com/flutter/flutter/issues/43826. So it means https://github.com/flutter/flutter/issues/43826 will only implement for `isMomentary`, right?
