### ISSUE TITLE
[web] Application cannot access .env

### ISSUE THREAD

**Issue by sashvoncurtis** [flutter/flutter#52100]
Hi,

Flutter web application needs access to the servers' .env.
The application is being served 'statically' from build/.
Dart IO is not supported for web and throws a platform._environment exception.

Any workarounds?

**Comment by brightest-dazes** [comment]
Am I the only one who notices information is limited or filtered. To keep people from maximum potential.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by sashvoncurtis** [comment]
This is an enquiry into using JWT with Flutter Web.

I have developed a JWT solution (will want to make an open source library for others to use) for my application (flutter web).

My solution has been to create a config.json that holds the secret to issue a new Jwt token. The config.json is not committed to source control, but is found under assets in the pubspec.yaml in order to use it in the app.
The token is stored in browser local storage as usual.

The main issue is whether or not the config.json is discoverable from the browser (i.e exposing the secret token, would allow bad actors to login to other user accounts), using CMD + P in Chrome Dev Tools I could not find the config.json but can see all of the raw Dart source code from my app (another minor issue). 

Concerns
Is or could the config.json be found in the app either by sucking the site, or in dev tools or via some arbitrary url exposing public assets?
What would be a better way of using assets in a flutter app so that they are not exposed from the get go?

Errata
Happy to provide source code or answer any questions.
Flutter Web is Beta, I think its best to catch these kinds of issues as early as possible. It would also give me peace of mind that another future release wouldn't effect this implementation.
