### ISSUE TITLE
InkWell doesn't work well in AnimatedContainer.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5211]
If you have an `AnimatedContainer` with an `InkWell`, the splashes will not have interpolated clipping rectangles, which leads to unpleasantly cut circles when the `AnimatedContainer` grows.

You can reproduce this by handing an `InkWell` with growing `AnimatedContainer` inside.

```dart
new InkWell(
  child: new AnimatedContainer(
    height: someGrowingFunction(),
    duration: ...
  )
)
```

Some leads to the issues are: this [notice](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/ink_well.dart#L77), this [line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/material.dart#L648), and this [method](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L1343).

**Comment by Hixie** [comment]
This is a [documented limitation of `Material`](https://docs.flutter.io/flutter/material/Material-class.html):

> If the layout changes (e.g. because there's a list on the paper, and it's been scrolled), a LayoutChangedNotification must be dispatched at the relevant subtree. (This in particular means that Transitions should not be placed inside Material.) Otherwise, in-progress ink features (e.g., ink splashes and ink highlights) won't move to account for the new layout.

We should probably make sure `InkWell` also says this.

**Comment by shihaohong** [comment]
Adding sample to replicate behavior:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: ClippedInkWell());
  }
}

class ClippedInkWell extends StatefulWidget {
  ClippedInkWell({Key key}) : super(key: key);

  @override
  _ClippedInkWellState createState() => _ClippedInkWellState();
}

class _ClippedInkWellState extends State<ClippedInkWell> {
  double sideLength = 50;

  void changeHeight() {
    setState(() {
      sideLength == 50
        ? sideLength = 100
        : sideLength = 50;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Ink(
              color: Colors.yellow,
              child: InkWell(
                onTap: changeHeight,
                child: new AnimatedContainer(
                  height: sideLength,
                  width: sideLength,
                  duration: Duration(seconds: 2),
                  curve: Curves.easeIn,
                )
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
