### ISSUE TITLE
No logs on Android

### ISSUE THREAD

**Issue by ndarilek** [flutter/flutter#52118]
```bash
$ flutter doctor summary -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/nolan/opt/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/nolan/opt/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/nolan/opt/android
    • Java binary at: /home/nolan/.asdf/installs/java/adopt-openjdk-8u232-b09_openj9-0.17.0_large-heap/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_232-b09)
    • All Android licenses accepted.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
[✓] Connected device (1 available)
    • BV8000Pro • 9DBMS4Q8LVEI7DHY • android-arm64 • Android 7.0 (API 24)
! Doctor found issues in 1 category.
```

I don't use Android Studio, so no problems are relevant.

I used to get lots of debug logging in response to `flutter run`. Additionally, `print` statements used to output to my console. Now, none of that works. Here is the output of `flutter run` on a brand new app created with `flutter create hello`:

```bash
Launching lib/main.dart on BV8000Pro in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.9s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
```

ANd that's it. No debug logs on screen touch/redraw. No `print` output. I used to be able to force hot reloads, but that doesn't seem to work either.

I can't think of a specific change I've made to my Flutter installation recently, other than `flutter upgrade`. I did recently start using VSCode, but it isn't even running now. What you're seeing is directly from `flutter run` on the Linux console. The app is also running, and to the best of my knowledge, my pre-existing Flutter apps work fine. They just refuse to log anything, or to accept commands on the `flutter run` instance.

**Comment by JonathanVegasP** [comment]
i'm with the same problem with one device, but i've tried with another device and it worked fine. Try another device for debug logs.

**Comment by ndarilek** [comment]
Unfortunately I just have the one device. I'd really like to figure out 
what may have happened here.

**Comment by iapicca** [comment]
Hi @ndarilek 
can you please provide 
your `flutter run --verbose` 
while running some the "hello world app"
adding a simple print statement
```dart
  Widget build(BuildContext context) {
print('hey');
    return Scaffold(
```
Thank you

**Comment by TahaTesser** [comment]
Hi @ndarilek 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
