### ISSUE TITLE
textfield_perf__timeline_summary benchmarks all regressed / need baselining

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52122]
Dashboard went from no metrics to read at commit https://github.com/flutter/flutter/pull/51938.

**Comment by kf6gpe** [comment]
Dropping TODAY label, but we still need benchmarks here.

**Comment by chinmaygarde** [comment]
The benchmarks look fine to me now and this issue is old. I am closing this.
![image](https://user-images.githubusercontent.com/44085/84611290-3d873f80-ae72-11ea-8670-5f834b99e64d.png)
