### ISSUE TITLE
appbar title is overflowing appbar buttons

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5212]
## Steps to Reproduce

Update buttons_demo.dart to use
```
return new TabbedComponentDemoScaffold(
      title: 'Buttons:WWWWWWWWWWWWWWWWWWW',
      demos: demos
    );
```
then run against an iPhone 5S on the iOS simulator.

<img width="432" alt="screen shot 2016-08-03 at 6 07 00 pm" src="https://cloud.githubusercontent.com/assets/85351/17387073/39beffbc-59a5-11e6-987d-4af7a5605e17.png">

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision a1fa7c94e3 (71 minutes ago), engine revision 1f03d60a27

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

**Comment by abarth** [comment]
Yeah, the trick is we want the text to be centered regardless of the size of the buttons on the left and right.  We just need to tech up to a custom layout here.

**Comment by eseidelGoogle** [comment]
So the bug here is specific to iOS when we center.  The elipsis is kicking in, but it's not constraining the size of the text to fit inside the available area.  Thoughts @Hixie or @HansMuller?

customer: fast is hitting this as sometimes they put their customer names (which can be long) in the title.  Not a critical issue, but something they'd like to be able to fix in their next release around EOQ Q3.

**Comment by eseidelGoogle** [comment]
You'll also notice that this is hitting https://github.com/flutter/flutter/issues/4478 (which is a lesser issue), but kinda odd that we fade the text (which is nice) but not the elipsis.

**Comment by sethladd** [comment]
EOQ is coming up fast. :)
