### ISSUE TITLE
When I use flutter run on Android Studio,Hang on Resolving dependencies.

### ISSUE THREAD

**Issue by 1Zyx2018** [flutter/flutter#52127]
My Android Studio is 3.5.3,Gradle is 5.4.1,flutter is v1.9.1+hotfix.6-stable

Normally it work;

But if I add dependencies such as sqflite , path_provider, shared_preferences and after I get these packages;Then,When I flutter run.Hang on Resolving dependencies.......

Sometimes,I can get this message

```bash
**ERROR AND WARNING**

> * Error running Gradle:
> ProcessException: Process "D: \ASfi le \demo \android\gradlew.bat" exited abnormally:
> Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details 
> Configure project :ap
> WARNING: API ' variant . getMergeAssets()' is obsolete and has been replaced with ' variant . getMergeAssetsProvider( ) ' .
> It will be removed at the end of 2019 .
> For more information, see https:/ /d.android.com/r/ tools/ task -configuration- avoidance .
> To determine what is calling variant . getMergeAssets(
> ( )，use -Pandroid. debug . obsoleteApi=true on th
> he command line to display more information .
> WARNING: API ' variantOutput . getProcessResources( )' is obsolete and has been replaced with ' variantOutput . getProcessResourcesProvider( )' .
> It will be removed at the end of 2019 .
> For more information, see https:/ /d.android.com/r/ tools/ task -configuration- avoidance .
> To determine what is calling vari antOutput . getProcessResources( ), use - Pandroid. debug . obsoleteApi=true on the command line to display more
> information .
> Command: D: \ASfile demo \android\gradlew. bat app : properties
> Finished with error: Please review your Gradle project setup in the android/ folder .
```

So,It is 3/7/2020 now and I tried update my AS to 3.6.1 and all plugins.But it didn't work;

**Comment by 1Zyx2018** [comment]
Oh,and my flutter doctor 

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.657], locale zh-CN)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.5)
> [√] Connected device (1 available)
> 
> • No issues found!

**Comment by 1Zyx2018** [comment]
Ok...After A night with sleeping.I think I solve it.

It's just becaue my internet.I'm in china so I have to change my build.gradle file,then run gradle sync.But,my packages' build.gradle aren't changed.

When I find gradle is syncing for a long time to download a file form the old source.I goto 

> flutter\.pub-cache\hosted\pub.flutter-io.cn
and replace the package's build.gradle to 

> repositories {
>         maven {
>             url 'https://maven.aliyun.com/repository/google'
>         }
>         maven {
>             url 'https://maven.aliyun.com/repository/public'
>         }
>         maven {
>             url 'https://maven.aliyun.com/repository/jcenter'
>         }
>     }

then,it work.

So,I think if your internet is ok.You won't have this problem。

Now,the solution is not the best.I think I have to edit all my packages' build.gradle.

**Comment by iapicca** [comment]
Hi @1Zyx2018 
I'm glad that you solved the issue,
please note that the current stable is `1.12.13+hotfix.8`,
you may want to run
`flutter upgrade --force`
`pub cache repair`
and `flutter clean` on your existing projects;

to use flutter repo from china please follow this [link](https://flutter.dev/community/china)
thank you

**Comment by mindjaydeep** [comment]
`flutter pub cache repair`
and `flutter clean`

solved my issue. thank you for saving my time
