### ISSUE TITLE
[Discussion] A way for a package to define it's test requirements and how to run them

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#52134]
As Flutter's testing solutions evolve, there is currently no canonical way to determine the commands that the package considers are part of its "CI suite", and their environmental requirements.

This is somewhat of a challenge for initiatives like https://github.com/flutter/flutter/issues/52115#issuecomment-595946634 and flutter/tests (which currently maintains a [set of commands per package](https://github.com/flutter/tests/blob/35775fd77b7d142b11b3a760bd8804825c9f00db/registry/template.test#L122)).

It would be useful to allow some formal way for a package to specify how to run each of it's tests/suites (`flutter test`, `flutter analyze`, `flutter drive`, `cd example; flutter drive`?), and the environmental requirements for each test (e.g a specific iOS simulator, a firebase testlab account).

cc @collinjackson

**Comment by JosepBove** [comment]
To be honest that would be so cool! I think that this will be necessary in some moment
