### ISSUE TITLE
E2E tests not getting expected TTS values

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52137]
https://b.corp.google.com/issues/150902962. Looks like premature truncation of trace data from the logs.

cc @iskakaushik @gw280

**Comment by goderbauer** [comment]
Currently assigned to somebody in Google. No action required from Flutter at this point.

**Comment by kf6gpe** [comment]
Still being worked by Googlers. No action required from Flutter team at this point.

**Comment by kf6gpe** [comment]
Still being worked by Googlers; escalated at Google to a P0, so if we're asked for help, we'll need to jump on it. No immediate action for the Flutter team, though.

**Comment by kf6gpe** [comment]
Fix rolled through Google's source code repository and believe fixed. Leaving open until upstream issue closes.

**Comment by kf6gpe** [comment]
Upstream issue is marked as fixed; closing.
