### ISSUE TITLE
--fast-start mode does not work with Android AlarmService

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52146]
For example, when running https://github.com/seamonkeysocial/rainbowmonkey/

```
I/FlutterBackgroundExecutor(15933): Starting AlarmService...
I/AndroidAlarmManagerPlugin(15933): onAttachedToEngine
E/flutter (15933): [ERROR:flutter/shell/common/shell.cc(202)] Dart Error: Dart_LookupLibrary: library 'package:android_alarm_manager/android_alarm_manager.dart' not found.
E/flutter (15933): [ERROR:flutter/runtime/dart_isolate.cc(467)] Could not resolve main entrypoint function.
E/flutter (15933): [ERROR:flutter/shell/common/engine.cc(214)] Could not run the isolate.
E/flutter (15933): [ERROR:flutter/shell/common/engine.cc(139)] Engine not prepare and launch isolate.
E/flutter (15933): [ERROR:flutter/shell/common/shell.cc(464)] Could not launch engine with configuration.
```

This is because hot restart does not currently work with background isolates, so the APK is created without the right code to start the background service and then can't be brought into a state where the background service works correctly.

See also: https://github.com/flutter/flutter/issues/47646

**Comment by exaby73** [comment]
Since this argument has been removed (see https://github.com/flutter/flutter/issues/48762#issuecomment-1199205620), I am closing this issue. If you disagree, please comment and we can re-open it. Thank you
