### ISSUE TITLE
Rewrite SkRtree 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#52142]
Once  flutter/engine#16923 is merged, we will take ownership of https://github.com/google/skia/blob/master/src/core/SkRTree.h.  This means, we should rewrite it, so it's better documented and follows the engine coding style guide.

Related issue: https://github.com/flutter/flutter/issues/52000

cc @chinmaygarde

**Comment by flar** [comment]
Obsolete as of https://github.com/flutter/engine/pull/38429
