### ISSUE TITLE
RTL support for Drawer

### ISSUE THREAD

**Issue by hahnr** [flutter/flutter#5215]
Currently the Drawer does not support RTL languages.
An RTL drawer should expand from the right instead of the left side.

**Comment by eseidelGoogle** [comment]
This is a part of https://github.com/flutter/flutter/issues/2598.  We have some RTL text support, but little RTL support in our widget layouts yet.

**Comment by joeblew99** [comment]
me too. Dont forget about chinese users :)

**Comment by eseidelGoogle** [comment]
I believe we're moving RTL to M4 for now.  It's ship-blocking but not beta-blocking.
