### ISSUE TITLE
SURVEY FOR FLUTTER DEVELOPERS AND THE SATISFACTION WITH THE FRAMEWORK AND ITS 3RD PARTY LIBRARIES

### ISSUE THREAD

**Issue by tobillion19** [flutter/flutter#52157]
My name is Tobi Michael Aroyehun and I am currently pursuing MSc in software development at the University of Limerick, Ireland. I am currently doing a research for my final thesis on the study of the flutter development framework and its 3rd party libraries. I am writing this to get feedback via a 10minutes survey from flutter developer on the current state of this framework with more emphasis on working with 3rd party libraries.
If you're interested in supporting this course,the URL link is below and as stated earlier it will only take 10 minutes. Thank you all for assistance.
Best Regards, Tobi.
https://docs.google.com/forms/d/e/1FAIpQLSdS1_WdjPIJslTY4xc4wWGZTamY1wyBGMaZLyDy16hvqZe7Mg/viewform?usp=sf_link

**Comment by stuartmorgan** [comment]
See flutter.dev/community for places you may want to post this. The issue tracker is for bug reports and feature requests.
