### ISSUE TITLE
[Crash] Configuration change crashes application- DeadObjectException

### ISSUE THREAD

**Issue by hahnr** [flutter/flutter#5216]
1) Start flutter app.
2) Change system language.
3) Return to flutter app from recents.
=> Crash

Showing Android SDK built for x86 64 logs:
--------- beginning of crash
W/ActivityManager:   Force finishing activity com.yourcompany.TestApp/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager:  at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager:  at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager:  at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager:  at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager:  at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager:  at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager:  at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
W/ActivityManager:  at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
W/ActivityManager:  at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
W/ActivityManager:  at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
W/ActivityManager:  at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
W/ActivityManager:  at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by eseidelGoogle** [comment]
This is only the java side of the crash, there is likely also a Dart or C++ crash to go along with this.  Based on those instructions, should be easy to reproduce though.

FYI @jason-simmons

**Comment by eseidelGoogle** [comment]
Could you also include your `flutter version` or `flutter doctor` output?  Looks like this is running in a x86 Android device or simulator, correct?

**Comment by hahnr** [comment]
> [✓] Flutter (on Mac OS, channel alpha)
>     • Flutter at /Users/hahnr/Flutter/flutter
>     • Framework revision e42be3c363 (2 weeks ago), engine revision 3291edef41
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
>     • Android SDK at /Users/hahnr/android-sdk-macosx/
>     • Platform android-23, build-tools 23.0.2
>     • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
>     • XCode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 7.3.1, Build version 7D1014
> 
> [✓] Atom - a lightweight development environment for Flutter
>     • flutter plugin version 0.2.4
>     • dartlang plugin version 0.6.33

x86 Android emulator

**Comment by eseidelGoogle** [comment]
If this can be confirmed, it's ship-blocking, M4.

**Comment by jason-simmons** [comment]
I'm unable to reproduce this on the current engine
