### ISSUE TITLE
flutter --version hangs

### ISSUE THREAD

**Issue by erf** [flutter/flutter#52161]
## Steps to Reproduce

Running `flutter --version` takes a long time ( around 1 min 20 secs ).

On the latest dev channel v1.15.18, on macOS Catalina

## Logs

Running `flutter --version --verbose`  also hangs

Running `flutter doctor -v` also hangs

Internet works ( streaming movies etc ).

**Comment by iapicca** [comment]
Hi @erf 
can you please provide the logs of your `flutter doctor -v` , 
and your `flutter --version --verbose`
Thank you

**Comment by erf** [comment]
@iapicca both commands finished, but it took quite a long time ~1 minute

```
~ % flutter doctor -v
[✓] Flutter (Channel dev, v1.15.18, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.15.18 at /Users/erlend/flutter
    • Framework revision 9437639590 (3 days ago), 2020-03-06 10:24:23 -0800
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/erlend/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.3 19D76

• No issues found!
```

```
~ % flutter --version --verbose
[  +13 ms] executing: [/Users/erlend/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9437639590adaa91e3df31cd9ce85133e401cd51
[   +2 ms] executing: [/Users/erlend/flutter/] git fetch https://github.com/flutter/flutter.git
--tags
[+2754 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[   +3 ms] From https://github.com/flutter/flutter
            * branch                HEAD       -> FETCH_HEAD
[   +4 ms] executing: [/Users/erlend/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.18-0-g943763959
[   +7 ms] executing: [/Users/erlend/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/erlend/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/Users/erlend/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +2 ms] executing: [/Users/erlend/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%ar
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 3 days ago
[  +16 ms] Flutter 1.15.18 • channel dev • https://github.com/flutter/flutter.git
           Framework • revision 9437639590 (3 days ago) • 2020-03-06 10:24:23 -0800
           Engine • revision 5aff311948
           Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

**Comment by erf** [comment]
```
~ % time flutter --version
Flutter 1.15.18 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 9437639590 (3 days ago) • 2020-03-06 10:24:23 -0800
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
flutter --version  0.65s user 0.28s system 1% cpu 1:20.03 total
~ %
```

**Comment by jmagman** [comment]
It's taking awhile fetching the tags.
What's the output of:
```
$ cd <flutter-sdk-location>
$ time git fetch https://github.com/flutter/flutter.git --tags
```

**Comment by erf** [comment]
```
~/flutter % time git fetch https://github.com/flutter/flutter.git --tags
From https://github.com/flutter/flutter
 * branch                HEAD       -> FETCH_HEAD
git fetch https://github.com/flutter/flutter.git --tags  0.13s user 0.12s system 3% cpu 6.242 total

```

**Comment by jmagman** [comment]
6 seconds to run a `git fetch` of the tags is pretty slow, but it's not hanging forever.  Hmmm...
Would be interesting to see the `--verbose` output when it's hanging and never completes and you have to eventually cancel it.

**Comment by dnfield** [comment]
I'd wonder what it took when the tags were stale...  If you have to fetch months worth of tags it may take a while

**Comment by erf** [comment]
@jmagman maybe it does "complete", it just takes a long time. I can change the initial text for the issue. Is there some other commands i should try and time?

**Comment by dnfield** [comment]
I did the following:

- Download the latest stable Flutter zip for my platform
- Unpack it
- In that directory:
- `du -sh .git` -> 86mb
- `git fetch https://github.com/flutter/flutter.git --tags`
- `dh -sh .git` -> 92mb

I imagine this would be more if I wasn't grabbing the latest hotfix bundle.  So if I grab the v1.0.0 bundle, I got the following:

before: 46mb .git
after: 99mb .git

I suspect this will just be slow for first time usage, particularly on a slow internet connection or a lower powered machine that has not fetched tags in a long time. Subsequent runs should be much faster.  It looks like you're seeing that @erf, if I'm following the issue correctly - subseequent runs are back down into the seconds range rather than 1+ minute.

**Comment by christopherfujino** [comment]
It seems like this is slow because `git fetch --tags` ALSO does a `git fetch` of all commits. https://stackoverflow.com/questions/1204190/does-git-fetch-tags-include-git-fetch

**Comment by dnfield** [comment]
Hmm.  That makes sense.  I tried the suggested command to fetch _only_ the tags, but still ended up downloading about 50mb of new data compared to stable: `git fetch https://github.com/flutter/flutter.git 'refs/tags/*:refs/tags/*'`

**Comment by christopherfujino** [comment]
I wonder, can we change the logic to only do the `git fetch --tags` if we are **not** currently on a tag? Since, if we're already on a tag, we presumably already know the exact version, right?

**Comment by christopherfujino** [comment]
Or easier, only do the `git fetch --tags` if we're on master, because presumably any other channel we should be on a tag, right?

**Comment by dnfield** [comment]
I think rather than master it should probably be `!stable && !beta && !dev`.

**Comment by christopherfujino** [comment]
Makes sense, although technically I think (currently) if you're not on one of the 4 known channels we default to `unknown` version.

**Comment by dnfield** [comment]
Right - and that's the case where this causes pain for people the most, because they're working on some random branch or a pull request branch, and the version is all out of whack and analysis fails.

**Comment by beiger** [comment]
How to solve this problem? 
![1585124996(1)](https://user-images.githubusercontent.com/18483100/77516824-fcf0d900-6eb5-11ea-942c-5cfc00f05ee3.png)
flutter --version takes more than 3 minutes.
But when I use the commit HEAD~13, it is fast, only seconds.

**Comment by erf** [comment]
`flutter --version` seem fast now so i'll close this.
