### ISSUE TITLE
A gradual tooling migration to package:vm_service

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52179]
Currently the flutter_tool is still using the homemade vmservice.dart library for most interactions. While this library is working well enough to stay functional for some time, it has some problems:

  - it doesn't have good test coverage besides unrelated integration testing.
  - It isn't developed alongside the VM service APIs.
  - Some additional API design issues that play into the above, which makes meaningful unit tests difficult to write with this library.

Thus there is some long-term risk of breakages caused by it falling out of sync with the implementation, and some additional risk imposed because changes to untested code are risky. 

To mitigate this risk, the tooling should migrate to the official package:vm_service which is maintained by the dart team. To reduce the risk of the migration, we must do so gradually. We can take advantage of some oft ignored features in Dart:

### Bootstrap

`FlutterVmService` will implement `VmService` and a `noSuchMethodForwarder`. Any members that conflict are renamed on the `FlutterVmService`. On connection `FlutterVmService` will also create a `VmService` instance which is stored as a private member.

### Update Process

In as small of a scope as reasonably possible, we'll move the old API usage to the new API. Some of these changes might still be quite large, as the interfaces are quite different. For example, migrating the stream API:

before:
```
  Future<Stream<ServiceEvent>> get onDebugEvent => onEvent('Debug');
  Future<Stream<ServiceEvent>> get onExtensionEvent => onEvent('Extension');
  Future<Stream<ServiceEvent>> get onIsolateEvent => onEvent('Isolate');
  Future<Stream<ServiceEvent>> get onTimelineEvent => onEvent('Timeline');
  Future<Stream<ServiceEvent>> get onStdoutEvent => onEvent('Stdout');

  Future<Stream<ServiceEvent>> onEvent(String streamId) async {
    await _streamListen(streamId);
    return _getEventController(streamId).stream;
  }
```

after:

```
  @override
  Stream<vm_service.Event> get onDebugEvent => onEvent('Debug');

  @override
  Stream<vm_service.Event> get onExtensionEvent => onEvent('Extension');

  @override
  Stream<vm_service.Event> get onIsolateEvent => onEvent('Isolate');

  @override
  Stream<vm_service.Event> get onTimelineEvent => onEvent('Timeline');

  @override
  Stream<vm_service.Event> get onStdoutEvent => onEvent('Stdout'); // WriteEvent

  @override
  Stream<vm_service.Event> onEvent(String streamId) {
    return _delegateService.onEvent(streamId);
  }
```

updated code
```
@@ -507,13 +507,10 @@ class IOSDeviceLogReader extends DeviceLogReader {
     if (device.majorSdkVersion < _minimumUniversalLoggingSdkVersion) {
       return;
     }
-    // The VM service will not publish logging events unless the debug stream is being listened to.
-    // onDebugEvent listens to this stream as a side effect.
-    unawaited(connectedVmService.onDebugEvent);
-    _loggingSubscriptions.add((await connectedVmService.onStdoutEvent).listen((ServiceEvent event) {
-      final String logMessage = event.message;
-      if (logMessage.isNotEmpty) {
-        _linesController.add(logMessage);
+    _loggingSubscriptions.add(connectedVmService.onStdoutEvent.listen((vm_service.Event event) {
+      final String message = utf8.decode(base64.decode(event.bytes)).trim();
+      if (message.isNotEmpty) {
+        _linesController.add(message);
       }
     }));
```

### Exit condition

Once all interactions are done through implemented `VmService` apis, the delegate service implementation can be returned in-place of the old `FlutterVmService` API.

Supersedes https://github.com/flutter/flutter/issues/31688

This does not address flutter_driver, which will likely need to be a large client migration. The process there will be necessarily different.

**Comment by dnfield** [comment]
If VMService 3+ is available for us now, we could also update the tracing tests to use that instead of the home spun version in that test.

**Comment by jonahwilliams** [comment]
The first part has landed. The next step is to gradually shrink the existing implementation by increasing the amount of delegation to the package:vm_service classes.
