### ISSUE TITLE
AppBar Title Font Incorrect -- Not Using ThemeData TextTheme Title

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#52185]
## Steps to Reproduce

1. Create a fresh project using `flutter create`
2. Add [google_fonts](https://pub.dev/packages/google_fonts) dependency to `pubspec.yaml`
3. Edit `lib/main.dart`:
  i. import the Google Fonts package:
      `import 'package:google_fonts/google_fonts.dart';`
  ii. Add the `textTheme` to the `ThemeData` as described [here](https://pub.dev/packages/google_fonts#getting-started):
      `textTheme: GoogleFonts.nunitoSansTextTheme(Theme.of(context).textTheme),`
  iii. Modify the `HomePage` `title` to append `(JKL)`  -- this help illustrate the bug
      `home: MyHomePage(title: 'Flutter Demo Home Page (JKL)'),`
  iv. Tweak the `HomePage` `build` function to also display `(JKL)`  with the same `TextStyle`:
```dart
            Text(
              'You have pushed the button this many times:\n(JKL)',
              style: Theme.of(context).textTheme.title,
            ),
```

**Expected results:** 

Look closely at the `(JKL)` between the `AppBar` `title` and the body text -- they are supposed to be same font, but they are not.  The K is very distinctive, and so is the J.  The body text is definitely _Nunito Sans_, as expected.  However, the App Bar Title is not Nunito Sans -- you can tell by the J and K looking very different.

**Actual results:** 

Take a good look at the **JKL** in the _App Bar Title_ vs the _Body Text_:
<img width="319" alt="app_bar_font_bug" src="https://user-images.githubusercontent.com/123887/76157487-2cce6d00-60be-11ea-9e7b-3eb18b44af52.png">
You can see that the J and K look very different -- but they should be using the same font and text style.  
The body text is definitely _Nunito Sans_, as expected.  However, the App Bar Title is not Nunito Sans.

<details>
  <summary>Logs</summary>

```
(The run log was too long -- it exceeded the 65536 limit of GitHub, so please refer to the attached log file.)
```

```
Analyzing app_bar_font_bug...                                           
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/anthony/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPhone 11 Pro Max     • 31A40F19-7F5F-4F08-8CB1-16E88FC6CBD5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPad (7th generation) • 8E75541F-B3F2-4D06-BD6F-EABB6FF2199C • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by awhitford** [comment]
Attached is the `flutter run --verbose` log: [run_verbose.log](https://github.com/flutter/flutter/files/4302906/run_verbose.log)

**Comment by RoyARG02** [comment]
The textStyle of `title` used in `Appbar` is defined as:
```
TextStyle centerStyle = widget.textTheme?.title
      ?? appBarTheme.textTheme?.title
      ?? theme.primaryTextTheme.title;
```
So, in increasing order of preference, the textStyle depends on:
**`ThemeData.primaryTextTheme.title < ThemeData.appBarTheme.textTheme.title < AppBar.textTheme.title`**

You have to specify the custom TextStyle(or TextTheme) in any of these parameters to see the effect you want.

**Comment by awhitford** [comment]
@RoyARG02 Thanks for the clarification.  I don't know where this is documented; I thought I had read that it was using the _Text Theme Title_.  I adjusted my test app to also specify `primaryTextTheme`, and now the _AppBar Title_ is using the correct font. 🎉 

Part of my confusion is due to the fact that my real code is using the [ThemeData.from](https://api.flutter.dev/flutter/material/ThemeData/ThemeData.from.html) constructor, and that does not give me an option to specify multiple Text Themes.

I would also expect that if `primaryTextTheme` was not specified, then it would logically default to `textTheme`.

Luckily, there is the [`copyWith`](https://api.flutter.dev/flutter/material/ThemeData/copyWith.html) method so that I can add the `primaryTextTheme`.  Of course, now I have the right font, but not the right color -- it went from white to black.  😕 

Thanks for the tip!

**Comment by awhitford** [comment]
I figured out the font color issue.

**Comment by RoyARG02** [comment]
Consider closing this if your issue is solved.

**Comment by TahaTesser** [comment]
Hi @awhitford 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
