### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version'

### ISSUE THREAD

**Issue by sagarkhurana00786** [flutter/flutter#52188]
Showing this error when running a flutter app for android

FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[  +99 ms] Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
[        ] > More than one file was found with OS independent path 'META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version'
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 35s

**Comment by TahaTesser** [comment]
Hi @sagarkhurana00786  
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @sagarkhurana00786 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
