### ISSUE TITLE
Could not resolve com.android.tools.build:gradle:4.5.1

### ISSUE THREAD

**Issue by LuckyYaYaChen** [flutter/flutter#52195]
Hello, everyone. I'm not familiar with the Android environment ,and I first learned about flutter. When I started the project, I encountered the following problems and need your help~~~
![image](https://user-images.githubusercontent.com/16660657/76163734-b72cd480-6183-11ea-8512-aea73e899008.png)
![image](https://user-images.githubusercontent.com/16660657/76163749-d297df80-6183-11ea-8cfd-458728347222.png)

**Comment by baddri** [comment]
Check this issue #22470

try to add **MavenCentral()** to <your_app>\android\build.gradle
```gradle
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}
```

**Comment by LuckyYaYaChen** [comment]
> Check this issue #22470
> 
> try to add **MavenCentral()** to <your_app>\android\build.gradle
> 
> ```groovy-gradle
> buildscript {
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.2.0'
>     }
> }
> ```

Thank you very much, but my problem still hasn't been solved. I later upgraded the version of Andriod Studio. Now I report the following error. I can't understand it at all. Moreover, the display of fluent doctor-v is all normal. Asking for help!!!
![image](https://user-images.githubusercontent.com/16660657/76698605-fb6a2880-66df-11ea-9b36-e66569b24b46.png)
![image](https://user-images.githubusercontent.com/16660657/76698608-058c2700-66e0-11ea-82e1-21250f821266.png)

**Comment by iapicca** [comment]
Hi @LuckyYaYaChen 
you are getting the error when creating a new project, is that correct?

Could  you please provide your full `flutter doctor -v` 
and your `flutter create test --verbose`

Please refrain from posting pictures if not necessary.
Thank you

**Comment by ynajimi** [comment]
Allo @LuckyYaYaChen 

Try to **Delete** ".idea" and "gradle" Folders and reopen your project and add google() to your build.gradle
as shown in this image : 
![Could not resolve com_android_tools_buildgradle4_5_1 png](https://user-images.githubusercontent.com/57614396/77563585-d6bc4080-6e97-11ea-852e-fbead7123956.png)
