### ISSUE TITLE
characters are missing when entering accents

### ISSUE THREAD

**Issue by linhlc07091990** [flutter/flutter#52191]
characters are missing when entering accents in TextFormField. Please support about this. Thanks

**Comment by linhlc07091990** [comment]
my version flutter
$ flutter doctor -v
[√] Flutter (Channel master, v1.15.19-pre.13, on Microsoft Windows [Version 10.0.18363.657], locale vi-VN)
    • Flutter version 1.15.19-pre.13 at D:\Flutter\flutter
    • Framework revision e2331d2b03 (83 minutes ago), 2020-03-08 06:11:01 -0400
    • Engine revision 162199452e
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by dnfield** [comment]
Could you please share some code that reproduces this issues and the steps to take to reproduce it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
