### ISSUE TITLE
tester.tap should throw an exception if element is not visible

### ISSUE THREAD

**Issue by IoanaAlexandru** [flutter/flutter#52192]
## Use case

After spending two days to figure out why my widget tests weren't working even though manual testing worked just fine, I figured out that the screen size of the (virtual) test device was smaller than the one on the (physical) device I was testing it manually on, so the things I was trying to tap weren't visible without scrolling.

I needed to add the following call:
```dart
await tester.ensureVisibile(button);
```

## Proposal
I know that `tester.tap` throws an exception if the finder fails, but I think it should also throw one if the finder finds something that is not visible (and therefore not tappable).

**Comment by endritgojani** [comment]
any page or widget that can be responsive you can use scroll in every direction to make the whole page visible

` await _driver.scroll("SerializableFinde", 0, -1000, Duration(milliseconds: 500));`

**Comment by dnfield** [comment]
Something can be invisible and still be tappable - for example, a button with an `Opacity` widget whose opacity is set to 0 is still tappable :)  We're discussing adding an assertion for that in https://github.com/flutter/flutter/issues/51000

It would really help if you provided a sample test case that currently passes but you would expect to fail.

**Comment by dnfield** [comment]
(Or, if the issue is that a test case that currently fails in an unhelpful way and would be more helpful if it failed differently, having that test case would be good too.)

**Comment by IoanaAlexandru** [comment]
As I mentioned in the issue, my test case was just a button that was near the bottom of the page. It was visible on most test devices but not on a very small screen (which automated testing was being done on), and it took me a very long time to figure out that even though I was technically calling `tester.tap(button)`, the `onTap` action wasn't actually firing and I couldn't figure out why.

It would be helpful if `tester.tap` would at least show a warning message 'Hey, you're trying to tap something that isn't visible, are you sure this is what you want to do? You could call `ensureVisible` to make sure what you're trying to tap is scrolled into view.' or something of the sort.

**Comment by dnfield** [comment]
An actual code sample is important here to know if the button was still in tree and still showing as hittable.

**Comment by dnfield** [comment]
If you're able to add a reproduction I'll be happy to reopen this.
