### ISSUE TITLE
How to hide header of DataTable

### ISSUE THREAD

**Issue by ndphuong** [flutter/flutter#52200]
I want to hide columns header of DataTable widget
Already try `headingRowHeight: 0` but not work

**Comment by iapicca** [comment]
Hi @ndphuong 
I believe is possible to "hide" a column programmatically with set state
[sample](https://gist.github.com/iapicca/befde1dbd958033dfb2ed53dcccf69e3) 
the sample doesn't "hide" a specific column to hide, but I believe gives the idea .
