### ISSUE TITLE
ExpansionTile backgroundColor does not apply when collapsed

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#52213]
## Steps to Reproduce

1. Create a fresh project using `flutter create`
2. Edit `lib/main.dart`
  i. Specify a `backgroundColor` for the `Scaffold`:
     `backgroundColor: Colors.yellow[50],`
  ii. Add an `ExpansionTile` to the `HomePage` build function `children`:
```dart
            ExpansionTile(
              backgroundColor: Color(0xFF666666), // This is a gray color
              leading: const Icon(Icons.bug_report),
              title: const Text('Expansion Tile Title Here'),
              initiallyExpanded: true,
              children: [
                Placeholder(),
              ],
            )
```

**Expected results:** 

I would expect that the `backgroundColor`, if specified, would apply whether the tile is expanded or collapsed.

**Actual results:** 

The ExpansionTile's `backgroundColor` only applies when then tile is expanded.  When collapsed, the `leading`, `title`, and `trailing` are painted on the background.  This is particularly problematic when the background is an image, or a color than does not contrast well with the text, making it difficult to read.

<img width="410" alt="Screen Shot 2020-03-08 at 4 10 53 PM" src="https://user-images.githubusercontent.com/123887/76172909-846ce700-6157-11ea-983a-ec66f44ac7cd.png">
<img width="410" alt="Screen Shot 2020-03-08 at 4 11 16 PM" src="https://user-images.githubusercontent.com/123887/76172915-8cc52200-6157-11ea-8c46-d1b472d36713.png">

<details>
  <summary>Logs</summary>

```
(This file is too long to attach and does not look relevant.)
```

```
Analyzing expansion_tile_bug...                                           
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/anthony/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPhone 11 Pro Max     • 31A40F19-7F5F-4F08-8CB1-16E88FC6CBD5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPad (7th generation) • 8E75541F-B3F2-4D06-BD6F-EABB6FF2199C • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by awhitford** [comment]
My workaround is to wrap the `ExpansionTile` in a `Container` that specifies a `color`.  I'm unclear on how to control the styling between _expanded_ and _collapsed_ mode.

If the behavior of `backgroundColor` is expected, then perhaps this is just a documentation issue.

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue but I have a question. The `backgroundColor` is not applied when the tile is collapsed because it uses a `ColorTween` to animate between null and `backgroundColor` to create a fading effect. So, are we looking forward to providing this feature?

If yes, then I have two proposals. 

1. To remove the `ColorTween` and simply pass the `widget.backgroundColor` to the Container. This will remove the fade effect and collapse will also have a background color.
2. To deprecate the `backgroundColor` and have two different properties, i) `collapseBackgroundColor` ii) `expandedBackgroundColor`, and animate between both the values. Users can pass null if they don't want color and it will create a fade effect.

**Comment by AyushBherwani1998** [comment]
@shihaohong gentle ping, if this got lost in inbox.

**Comment by shihaohong** [comment]
@AyushBherwani1998 Another approach that is similar to your 2nd suggestion that wouldn't be breaking is to introduce a new parameter called `collapseBackgroundColor` and just have the tween animate between `backgroundColor` and `collapsedBackgroundColor`. What do you think?

**Comment by AyushBherwani1998** [comment]
@shihaohong Makes sense to me, I'll change the docs for `backgroundColor` to make it more relevant.

**Comment by dashanan13** [comment]
Not sure if the property in updated.
https://api.flutter.dev/flutter/material/ExpansionTile-class.html
