### ISSUE TITLE
webview crashes beyond a certain height

### ISSUE THREAD

**Issue by ripple-xaz** [flutter/flutter#52215]
To show rich text，html cannot load style，webview crashes beyond a certain height

**Comment by dnfield** [comment]
Can you please share a minimal reproduction of this, as well as the version of the plugin and the output of `flutter doctor -v`?

**Comment by TahaTesser** [comment]
Hi @ripple-xaz 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
