### ISSUE TITLE
Render to Texture widget from C/C++ & graphic API directly with ffi 

### ISSUE THREAD

**Issue by axilesoft** [flutter/flutter#52229]
Can we get Texture Widget‘s native (OpenGL?) texture with dart:ffi?
Or can we bind a Texture class to a native ffi Pointer of texture (OpenGL/Vulkan) created by user using C/C++?

Then we can use Vulkan / OpenGL to render to Texture directly from C/C++.

**Comment by dcharkes** [comment]
I do not know what it would entail to expose flutter widget internals though dart:ffi (cc @mkustermann @mraleph).

**Comment by axilesoft** [comment]
Or can can bind a Texture class to a native ffi Pointer of texture (OpenGL/Vulkan) created by user using C/C++?

**Comment by mkustermann** [comment]
The `dart:ffi` is restricted to deal with simple C-types (integers, floats, pointers, structs-by-value soon coming).  If your C/C++ code obtains a pointer/handle/... to a texture you could use it in the Dart <-> C interaction.

The flutter engine team might be able to answer whether it's possible to obtain a pointer/handle/.. to a texture (and if so, how). @chinmaygarde

**Comment by chinmaygarde** [comment]
The texture widget is a reference to a handle that is provided by the platform and bound and used on the render thread. Even if the native handle to that texture were available via `dart:ffi`, you would not be able to use it on the thread the Dart isolate was running on. It should be possible to expose that handle but I am not sure what the point would be.

Also, Flutter would like to remain rendering API agnostic. OpenGL is only used on some platforms and on some backends, having just the native texture handle is not sufficient on all backends.

**Comment by darshankawar** [comment]
Hi @axilesoft,
Does above comment answer your question ? Do you think this issue still need to be kept open or can be closed ?
Thanks.
