### ISSUE TITLE
error ed\pub.dartlang.org\simple_connectivity-0.1.1

### ISSUE THREAD

**Issue by sabaya99** [flutter/flutter#52224]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Engmghase\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\simple_connectivity-0.1.1\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\Engmghase\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+2\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
D:\AndroidFutterProjects\rea_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: error: constructor ConnectivityPlugin in class ConnectivityPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
                                   ^
  required: Registrar
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

**Comment by TahaTesser** [comment]
Hi @sabaya99 

Please execute `flutter clean` then `flutter pub get` and try running the app

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @sabaya99 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
