### ISSUE TITLE
I can not add the   antl: ^0.15.7 into the dependencies

### ISSUE THREAD

**Issue by Alkahirah** [flutter/flutter#52225]
Hi, I am new in flutter I want to use the Sqflite in my new app when I wanted to add the antl in my dependencies I couldn't and show the message: "Because new_flutter_app depends on antl any which doesn't exist"

**Comment by TahaTesser** [comment]
Hi @Alkahirah 

Do you mean [intl ](https://pub.dev/packages/intl#-readme-tab-)?

Adding this causes no dependency conflicts 

```
  intl: ^0.16.1
  sqflite: ^1.2.2
```

Thank you

**Comment by Alkahirah** [comment]
Thanks a lot

‫في الاثنين، 9 مارس 2020 في 11:55 ص تمت كتابة ما يلي بواسطة ‪Taha Tesser‬‏
<‪notifications@github.com‬‏>:‬
