### ISSUE TITLE
../../third_party/dart/runtime/vm/object.cc: 2329: error: Out of memory. E/DartVM (23010): version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "android_ia32" E/DartVM (23010): thread=24864, isolate=_spawn(0xca377000)

### ISSUE THREAD

**Issue by ThalapathySiva** [flutter/flutter#52237]
./../third_party/dart/runtime/vm/object.cc: 2329: error: Out of memory.
E/DartVM (23010): version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "android_ia32"
E/DartVM (23010): thread=24864, isolate=_spawn(0xca377000)

End of DumpStackTrace
E/Dart (23010): ../../third_party/dart/runtime/vm/object.cc: 2329: error: Out of memory.
E/DartVM (23010): Aborting re-entrant request for stack trace.
F/libc (23010): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24746 (Thread-2), pid 23010 (lsedin.pulsedin)
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-03-09 17:57:54+0530
Lost connection to device.

I am getting this on while debugging the application works fine in release mode.

**Comment by mkustermann** [comment]
Can you say more about your program? What hardware do you run this on (e.g. how much RAM does it have)? Are you using isolates? What is the application doing?

Generally speaking, without a reproduction it's very hard to help here.

/cc @rmacnak-google

**Comment by ThalapathySiva** [comment]
I have tested it both emulator(Google Pixel 3 4 gb RAM) and physical device (Oppo Mobile 2 gb RAM).
I am not supposed to reveal, what exactly the app doing, our app is kinda social media application, we using dio for interaction with server.

**Comment by dineufeld** [comment]
@ThalapathySiva Did you found a solution? I am facing exact the same issue and it appeared sudently. Flutter doctors is not reporting any problems.

**Comment by ThalapathySiva** [comment]
@dineufeld  No i havent found a solution its happening only in flutter run on below 4GB Ram devices

**Comment by iapicca** [comment]
Hi @ThalapathySiva 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
