### ISSUE TITLE
Connect to company network

### ISSUE THREAD

**Issue by YashwanthDonthoju** [flutter/flutter#52238]
I am able to access  webapi after installing Self signed certificate provided by Company network team.  How do i use the Self signed certificate and access the WebAPI inside flutter? 
here is the sample i used but no luck. 
---------------------------------------------------

main() async {   
  await addSelfSignedCertificate();
  runApp(Login());
    
 }
 

  addSelfSignedCertificate() async {
  WidgetsFlutterBinding.ensureInitialized();
  ByteData data = await rootBundle.load('assets/Certificates/certificate.pem');  
  SecurityContext context = SecurityContext.defaultContext;
  context.setTrustedCertificatesBytes(data.buffer.asUint8List());
    
}

**Comment by TahaTesser** [comment]
Hi @YashwanthDonthoju 
Please take a look at this possible [solution](https://stackoverflow.com/a/54110360)
Are you providing `context` of SecurityContext to your HttpClient?
Thank you

**Comment by YashwanthDonthoju** [comment]
Hi @TahaTesser,

I am using  NTLMClient to access, am able to access webapi With VPN But not without VPN.
------------


static Future<Map<String, dynamic>> getAPIData(var url) async {
    NTLMClient client = new NTLMClient(
      username: "username",
      password: "password",
    );
    final response = await client.get(url);
    if (response.statusCode != 200) return null; 

    return json.decode(response.body);
  }

**Comment by TahaTesser** [comment]
Hi @YashwanthDonthoju 

For issue related to the 3rd party plugin [ntlm ](https://pub.dev/packages/ntlm) you may want to open an issue in the dedicated [github](https://github.com/mrbbot/ntlm/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
