### ISSUE TITLE
ArgumentError: Invalid argument(s): Cannot find executable for zip.

### ISSUE THREAD

**Issue by rkmax** [flutter/flutter#52241]
#31059  Steps to Reproduce

1. From Android Studio Welcome window try "Start a new Flutter Project"
2. Pick Flutter Application
3. The Fill details: project name, description, location
4. left all marked as default and hit finist

## Logs

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description TodoApp description --org com.bixlabs --project-name todo_app todo_app

## exception

ArgumentError: Invalid argument(s): Cannot find executable for zip.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.exitsHappySync (package:flutter_tools/src/base/process.dart:541:30)
#3      _PosixUtils.verifyZip (package:flutter_tools/src/base/os.dart:226:19)
#4      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:595:20)
#5      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:628:26)
#6      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:594:12)
#7      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:615:12)
#8      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:743:13)
#9      CachedArtifact.update (package:flutter_tools/src/cache.dart:550:11)
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:428:24)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:685:27)
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:608:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:598:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1465:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#30     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#32     new Future.sync (dart:async/future.dart:224:31)
#33     CommandRunner.run (package:args/command_runner.dart:112:14)
#34     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#35     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _runZoned (dart:async/zone.dart:1518:10)
#39     runZoned (dart:async/zone.dart:1502:12)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#41     run.<anonymous closure> (package:flutter_tools/runner.dart)
#42     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:18)
<asynchronous suspension>
#43     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#45     _rootRun (dart:async/zone.dart:1126:13)
#46     _CustomZone.run (dart:async/zone.dart:1023:19)
#47     _runZoned (dart:async/zone.dart:1518:10)
#48     runZoned (dart:async/zone.dart:1465:12)
#49     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#50     runInContext (package:flutter_tools/src/context_runner.dart:72:24)
#51     run (package:flutter_tools/runner.dart:50:10)
<asynchronous suspension>
#52     main (package:flutter_tools/executable.dart:69:9)
#53     main (file:///opt/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#54     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.15.19-pre.15, on Linux, locale C)
    • Flutter version 1.15.19-pre.15 at /opt/flutter
    • Framework revision 714d579839 (21 hours ago), 2020-03-08 15:06:02 -0400
    • Engine revision a10f555733
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/rkmax/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6241897/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6241897
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```


## `flutter doctor -v`

```
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for zip.".
A crash report has been written to /home/rkmax/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JvzT1

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JvowG

```

I'm using flutter master because issue with Linux 5.5 Kernel

**Comment by rkmax** [comment]
It was really weird I have not install zip package before on my system and work flawlessly and now I have to do it. after installing start working again. I'll left the issue open to let it know that is necessary to add that dependency in some way

**Comment by jmagman** [comment]
`zip` is listed as a system requirement https://flutter.dev/docs/get-started/install/linux#system-requirements
But the tool could give a better error when those dependencies aren't found.

**Comment by christopherfujino** [comment]
@jmagman agreed, I think the action point here should be tool exit with instructions to install `zip`.

**Comment by christopherfujino** [comment]
This has been fixed on the master channel by simple not using `zip` https://github.com/flutter/flutter/pull/52331.
