### ISSUE TITLE
Padding inside Table

### ISSUE THREAD

**Issue by egprojects** [flutter/flutter#52248]
## Use case

There's no way to add spacing between `TableRow`s. You can't just wrap `TableRow`s with `Padding` because it will lead to additional padding to the top and bottom of `Table`.

## Proposal

It'd be great if you'll add a `rowSpacing` property to the `Table` class.

**Comment by chinmoy12c** [comment]
I guess this issue should be closed now as a result of discussion in #63322.

**Comment by Abhishek01039** [comment]
@goderbauer 
can we close this issue?
