### ISSUE TITLE
flutter pub upgrade stuck almost 10 hours

### ISSUE THREAD

**Issue by Cheemer** [flutter/flutter#52246]
```
c:\google>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 981c03631ea51c3fbf5c9e4f13db48d1829c3190...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
```

i have try it 2-3 times each hour....suck....

**Comment by VladyslavBondarenko** [comment]
Hi @Cheemer 
Is it the same if you try after reinstalling flutter sdk?

**Comment by Cheemer** [comment]
yes, i had reinstalled the sdk three times.

**Comment by Cheemer** [comment]
i figure out this problem, because some ip was blocked, like 172.217.160.83 and 215.58.200.243.
