### ISSUE TITLE
hot_mode_dev_cycle_win__benchmark hotReloadMillisecondsToFrameAfterChange needs rebaseining...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52247]
Looks like it's been in the red pretty much since its introduction. I'm not treating it as a TODAY bug for that reason.

![Screenshot 2020-03-09 at 09 38 12](https://user-images.githubusercontent.com/1435716/76236324-c181b980-61e9-11ea-95ee-cd6e98c4344d.png)

**Comment by jonahwilliams** [comment]
Where did the rest of the data go?

**Comment by jmagman** [comment]
This was [introduced in 2017](https://github.com/flutter/flutter/pull/8827), as @jonahwilliams says, where did all the data go?

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/issues/52692 has been fixed. We now have all the historical data:
![image](https://user-images.githubusercontent.com/54558023/77809043-37d84580-704b-11ea-8d2c-1aba94d32d2b.png)

**Comment by tvolkert** [comment]
Rebaselined.
