### ISSUE TITLE
DUT response to touch is very slow

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52256]
https://buganizer.corp.google.com/issues/150860723

cc @dkwingsmt and @iskakaushik. Conversation on the Google bug.

**Comment by goderbauer** [comment]
@dkwingsmt The internal issue was assigned to you, so I also assigned this mirror issue to you.

**Comment by goderbauer** [comment]
@dkwingsmt Can you please assign a conservative milestone to this bus? Thanks.

**Comment by dkwingsmt** [comment]
@goderbauer I would like to, but I'm waiting for the response for the question I asked in the thread. For now I don't have any way to reproduce it.

**Comment by dkwingsmt** [comment]
I did find a bug during investigation, which will be fixed by https://github.com/flutter/flutter/pull/52450. I'm unsure if it's the cause for this issue, and I'll update the internal ticket for confirmation once the fix is rolled in.

**Comment by Hixie** [comment]
We believe this is closed.
