### ISSUE TITLE
Overlapping Text with iOS version

### ISSUE THREAD

**Issue by Parker-Bergen** [flutter/flutter#52260]
I am having the same issue as #44800 . The android version looks fine, but on iOS the text is overlapping (This applies for devices on iOS 10.3.4 and 13.4). This also happens when the text needs to wrap, and instead of going down to a line below, it will stay on the same level and overlap. I have temporarily used sized boxes to fix the spacing. I have tried the steps to clear the possible flutter corruption, but it did nothing to solve the issue. Please let me know any extra information that I can provide to help solve the issue.

**Expected results:** On android

![Screenshot_1583784798](https://user-images.githubusercontent.com/15371159/76253998-afb80a80-6219-11ea-9f57-36e06b363f64.png)
![Screenshot_1583784878](https://user-images.githubusercontent.com/15371159/76254005-b2b2fb00-6219-11ea-974b-283e77dcaaf8.png)

**Actual results:** On iOS
![IMG_1304](https://user-images.githubusercontent.com/15371159/76253793-5059fa80-6219-11ea-94a3-bb44d9bf9926.PNG)
![IMG_1303](https://user-images.githubusercontent.com/15371159/76253794-50f29100-6219-11ea-81b2-795864f773b5.PNG)

**Flutter Doctor Output**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/abelardotorres/development/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/abelardotorres/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • iPhone                    • 6b802eae53dfd92ab965761528be550e9123c041 • ios         • iOS 10.3.4

! Doctor found issues in 1 category.

```

**Comment by VladyslavBondarenko** [comment]
Hi @Parker-Bergen,

<details>
 <summary>With the code from mentioned issue</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Icon(Icons.star, size: 50),
          Container(width: 100, height: 100, color: Colors.red),
          Icon(Icons.star, size: 50),
          Icon(Icons.star, size: 50),
          Text("Hello"),
          Text("Hello 123"),
          Text("Hello cat"),
        ],
      ),
    );
  }
}
```

</details>

do you have text overlapped?

If no, can you provide minimal reproducible code sample?
Can it be reproduced with simulator? (I checked v1.12.13+hotfix.8 with iOS 13.3 and it's fine)
Thank you

**Comment by Parker-Bergen** [comment]
I have used the provided code block and was not able to get the same issue as I have shown above. I will try and get a minimal reproducible version. I have been using both an iphone 5 with iOS 10.3.4 and an iphone X with 13.4. I have also just checked and my issue can be also shown on the iOS simulator (I was using an iPhone 11 Pro Max with 13.3). I will get back to you as soon as I can reproduce it in a separate project.

**Comment by Parker-Bergen** [comment]
@VladyslavBondarenko So I figured out the issue. It doesn't seem to be a flutter structure itself but rather a font issue. We are using an font called Avenir and when we use the FontWeight.bold it causes the text to overlap. Not sure if its because we didn't specify the font weight in the pubspec.yaml. Below I have linked what I had before I added font weights. Is the only way to refer to the font weights as FontWeight.w{weight in the pubspec} rather than FontWeight.bold?
<img width="630" alt="Screen Shot 2020-03-10 at 8 05 23 AM" src="https://user-images.githubusercontent.com/15371159/76315626-0b7ca500-62a7-11ea-9fe7-00cdee36cedd.PNG">

**Comment by VladyslavBondarenko** [comment]
@Parker-Bergen 
Using v1.12.13+hotfix.8 with iOS 13.3 (simulator), 

<details>
 <summary>such fonts in pubspec.yaml</summary>

```
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/Avenir-Medium.ttf
        - asset: assets/Avenir-Black.ttf
          weight: 700
        - asset: assets/Avenir-Heavy.ttf
        - asset: assets/Avenir-Light.ttf
```

</details>

<details>
 <summary>and that code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          "Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 Hello 123 ",
          style: TextStyle(fontFamily: 'Avenir', fontWeight: FontWeight.bold),
        ),
      ),
    );
  }
}
```

</details>

I can see expected result.

Can you provide minimal reproducible code sample for your case?

**Comment by Parker-Bergen** [comment]
I have tried the supplied code with the fonts and it does not seem to produce the same results as in the project I was heavily working in. I will continue to do some testing to try to find at what point it breaks.

**Comment by TahaTesser** [comment]
Hi @Parker-Bergen 
if you're still experiencing this problem, please create a new issue and provide the information required in
the template.
Thank you
