### ISSUE TITLE
Using an OverscrollIndicator doesn't let you reverse direction immediately

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5226]
On Android, if you overdrag then, while the glow is showing, switch direction, you immediately scroll, as if the actual scroll offset had never gone beyond the end.

In Flutter, when using an OverscrollIndicator, you can't see that the scroll offset is going off the edge, but it is, and so you can keep scrolling in that direction and it'll make it take longer and longer to scroll back the other way.

**Comment by eseidelGoogle** [comment]
This came up in discussion the other day. Not sure if it was from UX review or not.

**Comment by abarth** [comment]
Fixed.
