### ISSUE TITLE
Implement dartPluginClass support for plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#52267]
The federated plugin design [describes having a dartPluginClass](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit#heading=h.xox07196p8c9) for each platform, allowing the registration of Dart plugin implementation details on a per-platform basis. Currently actually doing that is only possible on Web (AFAICT).

This is currently blocking implementation of `path_provider` and `shared_preferences` on Linux, where there's no need to use anything but pure Dart, because there's no way to bind the implementation to the interface package. (This is would also be very useful in conjunction with FFI; e.g., the Windows `path_provider` implementation could easily be Dart + FFI to a couple of system calls, significantly reducing the amount of code involved.)

Greg and I looked at this a little bit at the end of last week. Adding the auto-generation of a Dart registrant is simple, but we got stuck on actually injecting the call to that registrant in a way that doesn't break existing functionality (in particular, passing an arbitrary start point to the embedder API). I'm not sure if there was already a plan/design in place to address that.

/cc @amirh

**Comment by stuartmorgan** [comment]
/cc @gspencergoog as well.

(I've added the desktop platform labels because I know we'll want it there, but presumably we'll want this on iOS and Android too).

**Comment by amirh** [comment]
I was discussing this with @jonahwilliams awhile ago, one alternative we were considering was to generate a main function that wraps the app's main (and also invokes plugin activation), and use the generated main as the entry point.

Also note that there's some more discussion on how to bake this codegen in the tool in [this follow-up doc](https://docs.google.com/document/d/1G_K5vTMWD6CBD-0DDWhpAwkcCRKqmPH1wxlXu5FfRhk/edit#).

One thing I'd like to bring up for consideration again (tomorrow's meeting is a good chance) is whether to trade ease of use of unendorsed plugins with infra simplicity (by making it the app-facing package's responsibility to activate endorsed implementations).

**Comment by stuartmorgan** [comment]
> one alternative we were considering was to generate a main function that wraps the app's main (and also invokes plugin activation), and use the generated main as the entry point.

How? I considered that, but couldn't see how that would work in practice. Taking macOS as a concrete example, if my native code [passes any non-default entryPoint when starting the engine](https://github.com/flutter/engine/blob/e3c5f4827d17e82887b66469cf0d13ecc1cd5d3e/shell/platform/darwin/macos/framework/Headers/FlutterEngine.h#L63) how would we wrap it? The generated Dart wrapper needs to know what entry point to call into, but the tooling doesn't know what the native code is going to pass.

**Comment by amirh** [comment]
I didn't realize we let embeddings set the entry point.  🤔
@jonahwilliams are we doing something like that for web? do we allow a custom entry point there?

I guess if we want to keep going up this mountain we may propose VM support for an additional entry point. Though I'd really love a simpler solution.

[Just brainstorming] I'm not familiar with the VM bindings, do you know if it's possible for the engine to initiate invocation of a Dart method after runnning the initial entry point? (if that is possible I can imagine us adding code in widgets binding initialization to wait for the engine to indicate that plugins have been activated, and the engine will indicate that after invoking the generated registrant)

**Comment by jonahwilliams** [comment]
> are we doing something like that for web

No, the web doesn't really have an embedding so its not configurable.

**Comment by stuartmorgan** [comment]
@chinmaygarde and/or @jason-simmons Do you know offhand the answer to the question above about whether we are able to invoke arbitrary Dart code from the embedding? I.e., could the native embedding code start up the engine, then immediately call some known function?

**Comment by stuartmorgan** [comment]
> there's no way to bind the implementation to the interface package

Capturing from various discussions, the short-term solution to this problem is to directly register the dart-only implementation from the front-end package ([example](https://github.com/flutter/plugins/blob/fc6bd9834c7881d076086abaa7b74c9d317fb2bc/packages/path_provider/path_provider/lib/path_provider.dart#L34)).

This has the downside that it requires an override option for registering a different implementation, meaning that for instance tests that want to use a mock must explicitly disable the platform registration ([example](https://github.com/flutter/plugins/blob/fc6bd9834c7881d076086abaa7b74c9d317fb2bc/packages/path_provider/path_provider/lib/path_provider.dart#L15)).

**Comment by mehmetf** [comment]
>  the short-term solution to this problem is to directly register the dart-only implementation from the front-end package

As this creates a code-level dependency between front-end and platform specific implementation, it causes other issues in g3. (Added customer: google)

We need to implement what's proposed here internally since codegen/build systems are completely different in g3 (b/158287477) Please do keep us posted if a different solution is agreed upon.

**Comment by stuartmorgan** [comment]
> > the short-term solution to this problem is to directly register the dart-only implementation from the front-end package
> 
> As this creates a code-level dependency between front-end and platform specific implementation, it causes other issues in g3. (Added customer: google)

And in pub.dev analysis, it turns out, as described in https://github.com/dart-lang/pub-dev/issues/3680. That was an unforeseen side-effect of the workaround.

**Comment by amirh** [comment]
> @chinmaygarde and/or @jason-simmons Do you know offhand the answer to the question above about whether we are able to invoke arbitrary Dart code from the embedding? I.e., could the native embedding code start up the engine, then immediately call some known function?

***I don't really know what I'm talking about, please tell me why this breaks:***

**Naive proposal:**

After creating the isolate but before launching the main entry point (I guess just before [this line](https://github.com/flutter/engine/blob/1ef10b240e28574f03c37205d4c17189fb0f9293/shell/common/engine.cc#L224)?), call [Dart_InvokeClosure](https://github.com/dart-lang/sdk/blob/f7d1c55a1919354e8c54486144f428a71b2f6bab/runtime/include/dart_api.h#L2602) to first run the generated Dart registrant (potentially leaving an uncompleted Future to prevent termination) and then go on to invoke the main entry point.

Is calling 2 `Dart_Invoke`s on the same isolate supported? will it do what we want here?

@jason-simmons do you have an idea?

**Comment by blasten** [comment]
I'm not an expert, but your proposal sounds doable. The user main function seems to be called in https://github.com/flutter/engine/blob/5a2bf6aa4ceb29fe24a25027a3b3fc4ce2ad27be/lib/ui/hooks.dart#L224 from https://github.com/flutter/engine/blob/c700479db5d5a7638e4151b0e50fc2aef770d1b8/runtime/dart_isolate.cc#L487.

@amirh

**Comment by jason-simmons** [comment]
Yes - the engine can invoke other Dart methods before invoking the main entry point.  For example, `RuntimeController::FlushRuntimeStateToIsolate` does this to prepopulate state from the host embedding before the framework launches.

**Comment by blasten** [comment]
To summarize the design:  the Flutter tool  codegens a `plugin_registrant.dart` file based on `pubspec.yaml` metadata.  
For example, if `path_provider_linux` is a Dart only plugin:

```dart
import 'dart:io';

import 'package:path_provider_linux/path_provider_linux.dart';

Future<void> register() {
  if (Platform.isLinux) {
     await PathProviderLinux.register();
    // ...
  } else if (..) {
     ...
  }
}
```

Is this correct?

**Comment by amirh** [comment]
@blasten yes I think that will be the general idea, there's a little more in depth discussion here: https://docs.google.com/document/d/1G_K5vTMWD6CBD-0DDWhpAwkcCRKqmPH1wxlXu5FfRhk/edit#heading=h.dpq29kojl6x5

**Comment by jonahwilliams** [comment]
If you generate  a file that is disconnected from the rest of the application, how will the compilers know how to include it in the compiled dill?

**Comment by blasten** [comment]
@jonahwilliams can the tool inject it or would it get tree shaked?

**Comment by jonahwilliams** [comment]
it won't even get read by the compiler if it is not reachable via the normal import graph

**Comment by jonahwilliams** [comment]
Perhaps you could compile it separately into its own dill, and ... somehow combine that with whatever the app compilation produces? I don't know if that is strictly possible today.

**Comment by chingjun** [comment]
Sorry if I missed the previous discussions, if we're generating a different dill file for each platform, why don't we generate a wrapper file that wraps main instead?

Or if we're concerned that user might use arbitrary entry point method, how about generating a wrapper file that re-exports `main` from the script_file, and add a `register` method in that file that is marked `@pragma('vm:entry-point')`?

**Comment by stuartmorgan** [comment]
> Sorry if I missed the previous discussions, if we're generating a different dill file for each platform, why don't we generate a wrapper file that wraps main instead?

See https://github.com/flutter/flutter/issues/52267#issuecomment-596815403

> Or if we're concerned that user might use arbitrary entry point method, how about generating a wrapper file that re-exports `main` from the script_file, and add a `register` method in that file that is marked `@pragma('vm:entry-point')`?

Can you elaborate on this? It's not clear to me how we can generated a wrapper file when the tooling doesn't know what needs to be wrapped.

**Comment by chingjun** [comment]
When the kernel compiler is called, it is given a `mainPath` (usually `lib/main.dart`). We could generate a wrapper file like so:

```
export 'main.dart';

@pragma('vm:entry-point')
void registerPlugins() {
  // Register the plugins here
}
```

Then we do what is discussed above, the engine will call `registerPlugins` before calling the real entry-point method that the user specifies.

The dill file compiled from the wrapper we created should contain both the `registerPlugins` method and the rest of the app code.

**Comment by jonahwilliams** [comment]
If we could generate a new main (like we do on the web), we would not need any of these other features.

The entry-point configuration I think is only used by background activity plugins - in fact, dart programs are required to have a `main()`, but we would need to re-export everything though that lib and I'm not 100% sure it would work

**Comment by jonahwilliams** [comment]
actually, we could just wrap every top level function in a new function with the same name, and add plugin init to each one.

**Comment by blasten** [comment]
How bad would it be if we just ask developers to manually call the plugin registrant from `main()`?   Newer Flutter projects can call the registrant by default.

**Comment by jonahwilliams** [comment]
I don't think it would be that bad - provided that we always generated it and checked it in. That would essentially follow the same pattern that the plugin registrants follow for platform code today

**Comment by stuartmorgan** [comment]
> When the kernel compiler is called, it is given a `mainPath` (usually `lib/main.dart`).

Presumably this is just a default entry point though. See the link in my earlier comment; I don't see how that API can possibly exist as a runtime API if the compiler `mainPath` is definitive.

**Comment by blasten** [comment]
On Android and iOS, `registerWith` is justified because the native side might need to set up method channels, and/or register platform view factories.   As a result, I had a few questions:

If a plugin is entirely written in Dart, what is the use case for a static method `registerWith`? 
Can FFI initialization occur when a plugin interface method is called? 

@amirh, @stuartmorgan

**Comment by stuartmorgan** [comment]
> If a plugin is entirely written in Dart, what is the use case for a static method `registerWith`?

Capturing from chat, the critical use case is registering itself as the implementation of the platform interface in a federated plugin.

**Comment by blasten** [comment]
@stuartmorgan I heard there are a few desktop apps in g3. In this case, we would need to get g3 support before migrating the existing plugins.

@chingjun who is the best person to take a look at this feature (b/158287477 for reference)?

**Comment by chingjun** [comment]
There are very few desktop apps in g3, and I don't think any of them use plugins currently.

Will this be required for other platforms?

**Comment by blasten** [comment]
Only desktop at the moment, but I don't see why it couldn't be extended to other platforms. (note that web already has a plugin registry, which is separate from the implementation for Desktop).

**Comment by stuartmorgan** [comment]
Dart-only desktop plugins are currently stubbed out due to issues caused by the manual registration workaround (https://github.com/flutter/flutter/issues/52267#issuecomment-639566850). So there shouldn't be any google3 blockers to migrating, just work in the future to use them.

**Comment by blasten** [comment]
This is supported by the Flutter tool on the master channel.

**Comment by creativecreatorormaybenot** [comment]
@blasten Do you have a commit for it? I would love to know when this reaches stable in order to resolve issues like https://github.com/creativecreatorormaybenot/wakelock/issues/102 properly :)

**Comment by creativecreatorormaybenot** [comment]
I think I found the commit myself (https://github.com/flutter/flutter/commit/b7d4806243a4e906bf061f79a0e314ba28111aa6).

If I am correct, this feature will be available starting Flutter `v2.1.0-10.0`.

**Comment by stuartmorgan** [comment]
Re-opening since this was reverted.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Will it be merged again or did you decide against the feature?

**Comment by stuartmorgan** [comment]
It was reverted due to unexpected side-effect regressions; the goal is to fix them in an updated iteration.

**Comment by stuartmorgan** [comment]
Adding iOS and Android labels; there have been a few cases where it's come up that we would want this functionality there as well.

**Comment by stuartmorgan** [comment]
Leaving open for mobile.

**Comment by xster** [comment]
Since there weren't much additional discussions after the register plugin entrypoint wrapping the real entrypoint proposal, I'm assuming that's rough direction? Is there a doc with more details on the proposal? 

It's not too clear to me who calls that entrypoint. The embedding has ways of specifying an entrypoint when running the engine so it's a runtime problem rather than a compile time problem. How do we, at that point, switch out the real entrypoint the user called and wrap this plugin registration call around it?

**Comment by stuartmorgan** [comment]
> Is there a doc with more details on the proposal?

@blasten Is there a doc for what you implemented?

> It's not too clear to me who calls that entrypoint. The embedding has ways of specifying an entrypoint when running the engine so it's a runtime problem rather than a compile time problem. How do we, at that point, switch out the real entrypoint the user called and wrap this plugin registration call around it?

I wasn't involved in the reviews; I assumed that problem had been resolved since it was explicitly discussed several times above. As I've tried to extend it to mobile though, and found that it breaks `flutter test`, it seems to me like that may not actually be the case.

**Comment by blasten** [comment]
There's no doc about the implementation by itself, but I can summarize it:

The engine (C++) calls the Dart plugin registrant: https://github.com/flutter/flutter/pull/87991/files#diff-68361f6fc9aafa5fa7de042eec4603dd4f321eb783a00edd57780ef78c1094bbR709.  The only requirement is to define a top-level `_PluginRegistrant` class with a static method `register()`. Each should have `@pragma('vm:entry-point')`.

Wrapping `main.dart` was required because the Dart compiler had no other way to import a generated file from an arbitrary package that isn't imported by the app's dependency tree.

`flutter test` should work fine. @stuartmorgan please file an issue with repro steps if that isn't the case.  `flutter test` should set the set dart entrypoint anyways.

I'm aware that the Android embedding allows to use an arbitrary entrypoint string. I think this is supported, although not tested.  Since the engine only expects `_PluginRegistrant`; it doesn't really matter if it's defined in main.dart or foo.dart, it only matters that it's defined. @xster

**Comment by stuartmorgan** [comment]
> `flutter test` should work fine. @stuartmorgan please file an issue with repro steps if that isn't the case.

It doesn't, as I said here: https://github.com/flutter/flutter/pull/87991#issuecomment-900412165. See also
https://github.com/flutter/flutter/issues/88632
and
https://github.com/flutter/flutter/issues/88794

**Comment by blasten** [comment]
I see, sorry. 

The fix seems to be to regenerate the generated entrypoint [here](https://github.com/flutter/flutter/blob/ec3bd9edc4d2998661fa444ec1084963288e0c8c/packages/flutter_tools/lib/src/test/test_compiler.dart#L146)  using [generateMainDartWithPluginRegistrant](https://github.com/flutter/flutter/blob/ec3bd9edc4d2998661fa444ec1084963288e0c8c/packages/flutter_tools/lib/src/build_system/targets/dart_plugin_registrant.dart#L52).
 
I thought `flutter test` used the build system used elsewhere, but it doesn't seem like.

**Comment by stuartmorgan** [comment]
> The fix seems to be to regenerate the generated entrypoint [here](https://github.com/flutter/flutter/blob/ec3bd9edc4d2998661fa444ec1084963288e0c8c/packages/flutter_tools/lib/src/test/test_compiler.dart#L146) using [generateMainDartWithPluginRegistrant](https://github.com/flutter/flutter/blob/ec3bd9edc4d2998661fa444ec1084963288e0c8c/packages/flutter_tools/lib/src/build_system/targets/dart_plugin_registrant.dart#L52).

Thanks, I'll take a look at that. I hadn't had time yet to try to trace through everything to figure out where `flutter test` builds were happening.

The part that I'm still confused about though is: why is `flutter test` capable of overriding the original main, but not of overriding the wrapper main in `generated_main.dart`? Shouldn't that work the same way it used to? (And what is that way?)

**Comment by stuartmorgan** [comment]
That does appear to work, but I'd like to make sure I understand
a) why we need it, and
b) if we should be generating `generated_main.dart` somewhere else, because having it be a persistent file that points to a temp file that doesn't outlive the `flutter test` run seems very questionable.

**Comment by blasten** [comment]
Discussed offline. The fix is https://github.com/flutter/flutter/pull/90288
