### ISSUE TITLE
shell_benchmarks failed to run in the release mode

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#52263]
See https://cirrus-ci.com/task/6348658408947712 for an example.

**Comment by liyuqian** [comment]
@chinmaygarde @gaaclarke : do I need ` --full-dart-sdk` in `./flutter/tools/gn` in order to run `shell_benchmarks`? That's the only difference I can tell from our debug and release build, and the debug build can run `shell_benchmarks`. I'm having trouble `ssh` into my desktop so I'm unable to test it now. I can try it tomorrow if there's no quick answer on your mind.

**Comment by chinmaygarde** [comment]
No. You never need `--full-dart-sdk`. Are you able the run the benchmark runner locally. It may not be setup for running in release in that it doesn't setup AOT snapshots.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/17051.
