### ISSUE TITLE
tiles_scroll_perf_iphonexs__timeline_summary 90th_percentile_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#52275]
Since https://github.com/flutter/flutter/commit/91b0bcf1a8a192e8135a9289310d81deba5824ec, the graph looks like the following:

<img width="265" alt="Screen Shot 2020-03-09 at 4 28 51 PM" src="https://user-images.githubusercontent.com/22987568/76265936-1857b500-6223-11ea-91e8-46ca5225b69b.png">

**Comment by liyuqian** [comment]
@GaryQian : can you reproduce this regression locally? Also CC @digiter to see if this is an infra issue as I don't see a similar regression on iOS (iPhone 6s) version of our benchmark.

**Comment by liyuqian** [comment]
CC @kf6gpe for visibility.

**Comment by renyou** [comment]
91b0bcf is reverted, and this metric dropped back.
