### ISSUE TITLE
Unhidden errors following avoid_catches_without_on_clauses lint

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#52272]
In order to address https://github.com/flutter/flutter/issues/8742, several attempts were made to only catch `Exception`s. However, because of https://github.com/dart-lang/sdk/issues/40934 this causes a regression where we no longer handle `OSError`s.

1. Originally landed in https://github.com/flutter/flutter/pull/51440 (pre-1.15.4, but not published)
1. Reverted in https://github.com/flutter/flutter/pull/51539 (pre-1.15.4)
1. Re-landed in https://github.com/flutter/flutter/pull/51567 (pre-1.15.4, not published)
1. Reverted in https://github.com/flutter/flutter/pull/51616 (pre-1.15.4)
1. Re-landed in https://github.com/flutter/flutter/pull/51774 (pre-1.15.5, not published)
1. Reverted in https://github.com/flutter/flutter/pull/51960 (pre-1.15.5)
1. Re-landed in https://github.com/flutter/flutter/pull/52021 (published in 1.15.18, not reverted yet)

**Comment by christopherfujino** [comment]
I removed the "TODAY" label as this is already on dev.

**Comment by zanderso** [comment]
We've landed fixes for many of these uncovered crashers today. It's looking like the `OSError` issue may take some time to resolve. Since that doesn't affect many users, I will leave the lint in place, and handle `OSError` in the small number of places where it is coming from.

**Comment by christopherfujino** [comment]
I linked [bad builds](https://github.com/flutter/flutter/wiki/Bad-Builds) to this issue, marked as from v1.15.18 - present. What should be the point at which the build is considered good again? @zanderso

**Comment by zanderso** [comment]
We should see the crash rate drop below our usual objective on a dev/ release. Then w.r.t. this issue, that dev release would be good.

**Comment by zanderso** [comment]
fyi @jonahwilliams

**Comment by zanderso** [comment]
We should keep an eye on 1.15.20 to see if it is within tolerance.

**Comment by zanderso** [comment]
dev/1.15.20 crash rate is back under control
