### ISSUE TITLE
OverscrollIndictator doesn't follow finger as you move back and forth while it's showing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5227]

**Comment by eseidelGoogle** [comment]
I'm not sure what this means.  I've definitely seen @HansMuller's fancy new indicator distort (like android does) when I move my finger left/right.  Presumably you mean something else?

**Comment by HansMuller** [comment]
The implementation hides the glow as soon as it detects a reverse scroll which can make it hard to wiggle the glow from side to side.

We should probably add a small reverse scroll threshold.

**Comment by Hixie** [comment]
Never mind, this is actually just a dupe of https://github.com/flutter/flutter/issues/5226.
