### ISSUE TITLE
Android: $runtimeType is minified with release mode

### ISSUE THREAD

**Issue by shinsenter** [flutter/flutter#52278]
## Steps to Reproduce

1. Store any class' name by using `$runtimeType` variable
2. Run application on Android with `--release` flag

**Expected results:** The class name

**Actual results:** 3-character code

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
Are you using dart obfuscation?

**Comment by shinsenter** [comment]
@jonahwilliams 
Yes I did obfuscation. 
It ($runtimeType) works fine on iOS. I want to track some instance from log but couldn't view the right class names.

**Comment by jonahwilliams** [comment]
Unfortunately this feature is not well documented. The caveats are noted here:

https://github.com/dart-lang/sdk/issues/30524#issuecomment-324905442

If `$runtimeType` is working on iOS that means to code was not obfuscated.
