### ISSUE TITLE
Darwin plugin linter issues: fails but returns success exit code, does nothing, or hangs

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#52289]
I noticed several issues with the plugin linter script:

https://github.com/flutter/plugins/blob/master/script/lint_darwin_plugins.sh

This script is used by FlutterFire as well:

https://github.com/FirebaseExtended/flutterfire/blob/master/script/lint_darwin_plugins.sh

1. In pre submit checks, script is printing errors on the command line but the exit code is 0: https://cirrus-ci.com/task/5104699145715712
1. The script doesn't do anything on post submit. Probably it should run on all plugins: https://cirrus-ci.com/task/5521154811101184
1. The script seems to be hanging on this PR. See test results for https://github.com/FirebaseExtended/flutterfire/pull/2099 here:
https://cirrus-ci.com/task/6400550270926848

Finally, we should probably make this be --verbose instead of --silent so that the reason for failures will be visible in the Cirrus logs.

FYI @jmagman

**Comment by jmagman** [comment]
I was never able to fix https://github.com/flutter/plugins/pull/2346#issuecomment-571812132
```
Archive:  Flutter.framework.ZIP
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
) during validation.
```

@collinjackson Could someone on your team take that PR over?

**Comment by jmagman** [comment]
> 1. In pre submit checks, script is printing errors on the command line but the exit code is 0: https://cirrus-ci.com/task/5104699145715712

Done with https://github.com/flutter/plugins/pull/2346.

> 2. The script doesn't do anything on post submit. Probably it should run on all plugins: https://cirrus-ci.com/task/5521154811101184

Done. https://cirrus-ci.com/task/5203278988312576?command=main#L3

> 3. The script seems to be hanging on this PR. See test results for [FirebaseExtended/flutterfire#2099](https://github.com/FirebaseExtended/flutterfire/pull/2099) here:
>    https://cirrus-ci.com/task/6400550270926848
> 
> Finally, we should probably make this be --verbose instead of --silent so that the reason for failures will be visible in the Cirrus logs.

Done with https://github.com/flutter/plugins/pull/2346.

> This script is used by FlutterFire as well

Created https://github.com/FirebaseExtended/flutterfire/issues/2405 to track that repo migrating to flutter_plugin_tools.
