### ISSUE TITLE
Ability to debug flutter code when using "add-to-app" functionality by including "aar" file in the native android app

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#52296]
Right now , when we build the flutter aar file and include it in the native app. there are times when what used to work separately in flutter doesn't work when included in the native app.

At some point it becomes highly essential to have the ability to debug flutter code when using the add-to-app functionality and running the native app.

**Comment by jmagman** [comment]
@xster Do we have any docs for this?

**Comment by xster** [comment]
Not too clear what the question is. Is https://flutter.dev/docs/development/add-to-app/debugging what you're looking for?

**Comment by nateshmbhat** [comment]
Yes this is exactly what I was referring. Thank you

**Comment by xster** [comment]
Can you let us know where you looked for documentation initially? It could help make sure we put documentation at the most intuitive places.

**Comment by nateshmbhat** [comment]
I think it would be better to change the title of the doc page here. On the first glance it just looks like a normal flutter debugging guide unless u read it furthur inside.

**Comment by nateshmbhat** [comment]
I may have come across this page but would have left thinking they're just talking about how to do debugging.

**Comment by xster** [comment]
Did you mean via SEO or did you browse through the navigation bar on the left?

**Comment by nateshmbhat** [comment]
Via SEO

**Comment by xster** [comment]
How about "Debugging your add-to-app module"?

**Comment by nateshmbhat** [comment]
The title's kind of unclear if u stumble upon that page from Google
