### ISSUE TITLE
Add Virtual dom support for dom manipulation in flutter-web or make it as performant as Angular

### ISSUE THREAD

**Issue by rajneeshraghav** [flutter/flutter#52295]
Flutter is really helpful for creating Cross-Platform apps, Dom manipulation seems much slower in flutter then React/Angular. Adding Virtual dom support can really boost Dom manipulation performance.

**Comment by ferhatb** [comment]
Hi @rajneeshraghav , Flutter framework only partially rerenders its graph so for the build part of 
the build/layout/paint cycle, best suggestion is to setState at granular level. When you call setState it will mark everything up to the highest repaint boundary (see RepaintBoundary widget). 

On the paint side of things, thank you for raising issue, when you paint the exact same Picture at the leaf level we have some optimizations but there is still a lot of ongoing work on our side to make things faster.

The most helpful thing for our team is to get snippets of real code, showing us where we have bottlenecks to optimize.

If you have some sample scenario with small repro case, please reopen issue with code. Closing this for now. Thank you for feedback!
