### ISSUE TITLE
Flutter Icon in Drawer header does not respect Dark theme

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5229]
I don't think this is a huge deal, but probably the text should turn white?
![simulator screen shot aug 4 2016 2 28 29 pm](https://cloud.githubusercontent.com/assets/11857803/17418926/cb628920-5a4f-11e6-8d54-b1d7daa064da.png)

**Comment by HansMuller** [comment]
Doesn't look good; will fix.

**Comment by Hixie** [comment]
done
