### ISSUE TITLE
Request to specify Flutter's libs in _embedder.yaml

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#523]
Now that we have an _embedder.yaml file (https://github.com/flutter/flutter/pull/516) we can specify our embedder-provided libraries. This is a request to specify `embedder_libs` in Flutter's _embedder.yaml

(Once that is in, we can look at ensuring dartdoc can read those files, so we can auto-generate docs)

**Comment by abarth** [comment]
Is there an example I can cargo-cult?

**Comment by Hixie** [comment]
What does this do?

**Comment by sethladd** [comment]
This allows a package (such as flutter) to teach the analyzer about dart: libraries. Also, it enables a package to say "ignore whatever Core Dart SDK dart: libraries you think you know about. instead, use my definition of dart: libraries".

This attempts to solve the problem of flutter providing an embedding of Dart and a set of dart: libraries, which are NOT the same dart: libraries the developer might have installed on their PATH. Then enables a developer to sit in Atom and code complete against dart: libraries that are running inside their Flutter app.

cc @johnmccutchan

**Comment by Hixie** [comment]
@abarth see https://github.com/dart-lang/sdk/issues/25011

**Comment by sethladd** [comment]
Here's an example:

```
embedder_libs:
  "dart:foobar": "../sdk_ext/entry.dart"
```

For Flutter, we'll want to list _all_ dart: libraries (both the custom libs and the core libs like collection, core, and io)

Now that we're generating docs:

@keertip @pq  does dartdoc respect embedder_libs ?

**Comment by pq** [comment]
>  does dartdoc respect embedder_libs ?

I'm guessing not but will defer to Keerti...  (Needless to say, happy to help teach it to.)

**Comment by sethladd** [comment]
@johnmccutchan would it make more sense to put the embedder_libs into sky_engine's _embedder.yaml? That appears to be what actually reflects the embedder and what provides the dart: libs (and the dart:ui libs)

**Comment by keertip** [comment]
@sethladd, will have to add logic to dartdoc to recognize embedded libraries.

**Comment by johnmccutchan** [comment]
@sethladd Yes, the engine should own the _embedder.yaml file.

**Comment by sethladd** [comment]
Thanks. I went to go add it myself, but then I ran into BUILD.gn files in the engine and then I figured, I better like @abarth or @johnmccutchan do this one.

**Comment by pq** [comment]
FWIW we're migrating the key from `embedder_libs` to `embedded_libs` for reasons discussed in this change:

https://codereview.chromium.org/1643023002/

**Comment by pq** [comment]
Bumping over to @abarth since we're ready to test a sky engine with "real life" embedded libs.

**Comment by pq** [comment]
Added separate issue to track build changes: https://github.com/flutter/flutter/issues/1712

**Comment by sethladd** [comment]
I think @johnmccutchan did this, and we're just waiting for a roll?

**Comment by abarth** [comment]
The change was reverted in https://github.com/flutter/engine/pull/2432 because it didn't work for some reason.

**Comment by johnmccutchan** [comment]
Yeah, I will be relanding later today and updating the binary version of the Dart SDK being used.
