### ISSUE TITLE
Flutter rethrow is not working in a cascade try and catch

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#52305]
I have the following function.  What is does is call the api and send the relevant information. Then if there is error code like 401 etc. Then I try to process the json message. Thus if it fails I do a try and catch. Eg. this is throw throw UnknownError('$code. Server error: Error in first catch'); but then it caught by the this outer try catch. The problem it stops there and complains exception occurred. How to overcome this issue of rethrow not working ?
```
catch (exception) {
		
			if(exception.toString().contains('SocketException')) {
				 throw UnknownError('Network error: check connection');
			} else { 
        print("About to send unknownError ready");
        if(exception is UnknownError){
          rethrow;
        }
```
```
static dynamic post(String url, String authToken, Map body ) async {
		var uri = host + '/api1/'+ url;
    print("uri is :"+uri);
   
    var fullToken = 'Bearer $authToken';
  
		try {

			final response = await http.post(
				uri,
        headers: {
					'Authorization': fullToken,
          'content-type': 'application/json'
				},
				body: json.encode(body)
			);

			final code = response.statusCode;
      
			var errorCatch = "";
      
      if(code==401 || code>=500 || code>=400){

        try {
            var x = json.decode(response.body) as Map<String, dynamic>;          
            try {
              var message = "";
              final responseJson = json.decode(response.body);

              if (responseJson != null) {
                message = responseJson['message'];
                if(code==401){
                  throw AuthError('$code Auth Error: '+message);
                }
                else if(code>=500){

                  throw UnknownError('$code. Server error: '+message);
                }
                else if(code>=400){

                  throw Error4xx(' $code Wrong request : '+message);
                }
              }
            }catch(err){
              errorCatch='$code. Server error: Error in first catch';
              print("couldn't extract err message from ${body??'null'}");
              throw UnknownError('$code. Server error: Error in second catch');
              //'$code. Server error: ';
            }
        }catch(err){
              errorCatch='$code. Server error: Error in first catch';
              print("couldn't extract err message from ${body??'null'}");
              throw UnknownError('$code. Server error: Error in first catch');
        }

      }
      
      return response.body;
      

		} 
   
    catch (exception) {
		
			if(exception.toString().contains('SocketException')) {
				 throw UnknownError('Network error: check connection');
			} else { 
        print("About to send unknownError ready");
        if(exception is UnknownError){
          rethrow;
        }
			}
		}
	}
```

**Comment by TahaTesser** [comment]
Hi @newbieflutter  
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by newbieflutter** [comment]
Hi Taha,
             Here is the results.

flutter doctor -v
[✓] Flutter (Channel dev, v1.15.18, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.15.18 at /usr/local/flutter
    • Framework revision 9437639590 (4 days ago), 2020-03-06 10:24:23 -0800
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shaisingh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
 The build results is very long. Should I attached as a file?

**Comment by TahaTesser** [comment]
Hi @newbieflutter 
Since this is more of a Dart issue than Flutter issue
Please raise your raise on their [github](https://github.com/dart-lang/sdk/issues)
Thank you

**Comment by newbieflutter** [comment]
Hi Taha,
              Ok will do it there. Thank you.
