### ISSUE TITLE
Flutter License screen shows wrong logo

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5230]
It shows the background for the appbar, not the logo.  Presumably we meant the Logo?

This is pretty low priority, but worth noting down.

@Hixie 

![simulator screen shot aug 4 2016 2 29 31 pm](https://cloud.githubusercontent.com/assets/11857803/17418961/f7bdf266-5a4f-11e6-931e-a5f1c7d53f4f.png)

**Comment by sethladd** [comment]
I think this is fixed?

**Comment by HansMuller** [comment]
Done.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/18009682/378716a2-6b62-11e6-8332-38b082f279c4.png)
