### ISSUE TITLE
app crashes after hitting 【url with params 】directly in browser

### ISSUE THREAD

**Issue by Panda210** [flutter/flutter#52313]
1、Add two named routes to app using "routes" property of MaterialApp class.
2、Add two button to each widget.on click of button navigate between screens
3、Navigation works with button click but if you hit url【with params】 directly in browser or refresh the page then app crashed.It will not work with bookmarked pages.
4、If you hit url without params directly in browser then app success.

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ═════
The following message was thrown:
 Could not navigate to initial route.
The requested route name was: "/insurance_detail?productCode='P002'"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
════════════════════════════════════════

** Code **
*** MyApp****
`class MyApp extends StatelessWidget {
  final Store<AppState> store = new Store<AppState>(
    appReducer,
    initialState: AppState.initState(),
    middleware: [loggingMiddleware, thunkMiddleware],
  );
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return StoreProvider<AppState>(
      store: store,
      child: StoreBuilder<AppState>(
        builder: (context, store) {
          print('store:${store.state}');
          return MaterialApp(
            title: AppText.appTitle,
            theme: ThemeData(
              primaryColor: Color(AppStyle.color_white),
            ),
            home: RootPage(),
            routes: AppRoutes.genAllRoutes(),
            onGenerateRoute: (settings){
              AppRoutes.parseRouteSetting(settings);
            },
          );
        },
      ),
    );
  }
}`

***** AppRoutes******
`class AppRoutes {
  static genAllRoutes() {
    Map<String, WidgetBuilder> map = {
      RootPage.routerName: (context) {
        return RootPage();
      },
      InsuranceDetailPage.routerName: (context) {
        return InsuranceDetailPage();
      },
    };
    return map;
  }

  // Flutter[onGenerateRoute] - 对url进行解析，就能变相实现参数传递。
  static Route<dynamic> parseRouteSetting(RouteSettings settings) {
    Uri uri = Uri.parse(settings.name);
    String route = uri.path;
    print('##### route:${route},###settings.name:${settings.name}');

    Map<String, String> params = uri.queryParameters;
    print('### params:${params}');
    if (route.isNotEmpty && null != params) {
      if (route.startsWith(InsuranceDetailPage.routerName)) {
        settings = settings.copyWith(
          name: InsuranceDetailPage.routerName,
          arguments: Product.fromJson(params),
        );
        print('### settings:${settings}');
        return MaterialPageRoute(
          builder: (context) {
            return InsuranceDetailPage(
              product: Product.fromJson(params),
            );
          },
          settings: settings,
        );
      }
    } else {
      return MaterialPageRoute(
        builder: (context) {
          return RootPage();
        },
        settings: settings,
      );
    }
  }
}`

***** RootPage *******
`class RootPage extends StatefulWidget {
  static final String routerName = "/home";

  @override
  _RootPageState createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  @override
  Widget build(BuildContext context) {
    /// 屏幕适配标准化设置
    ScreenUtil.init(
      context,
      width: 750,
      height: 1334,
      allowFontScaling: true,
    );

    return StoreBuilder<AppState>(
      builder: (context, store) {
        return Scaffold(
          body: Container(
            child: GestureDetector(
              child: Text('保险详情页面'),
              onTap: () {
                Navigator.pushNamed(
                  context,
                  InsuranceDetailPage.routerName,
                  arguments: Product(
                    productCode: 'P001'
                  ),
                );
              },
            ),
          ),
        );
      },
    );
  }
}`

*****  InsuranceDetailPage *****
`class InsuranceDetailPage extends StatefulWidget {
  static final String routerName = "/insurance_detail";

  Product product;

  InsuranceDetailPage({
    this.product,
  });

  @override
  _InsuranceDetailPageState createState() => _InsuranceDetailPageState();
}

class _InsuranceDetailPageState extends State<InsuranceDetailPage> {
  // 轮播图片列表
  List<String> bannerImageList = [];

  @override
  Widget build(BuildContext context) {
    final Product product = ModalRoute.of(context).settings.arguments;
    if(null != product){
      print('### product:${product.toJson()}');
    }
    return StoreBuilder<AppState>(
      builder: (context, store) {
        return Scaffold(
          backgroundColor: Color(AppStyle.color_grey_f0),
          body: NestedScrollView(
            headerSliverBuilder: headerSliverWidgetList,
            body: ListView(
              children: <Widget>[],
            ),
          ),
        );
      },
    );
  }

  /// 顶部轮播图
  List<Widget> headerSliverWidgetList(
      BuildContext context, bool innerBoxIsScrolled) {
    return [
      SliverAppBar(
        // 标题居中
        centerTitle: true,
        // 展开高度
        expandedHeight: 300.0,
        // 不随着滑动隐藏标题
        floating: false,
        // 固定在顶部
        pinned: true,
        flexibleSpace: FlexibleSpaceBar(
          centerTitle: true,
          title: CompImageSwiper(
            imageList: bannerImageList,
            aspectRatio: 2 / 1,
          ),
          titlePadding: EdgeInsets.all(0),
        ),
      ),
    ];
  }

}`

**Comment by TahaTesser** [comment]
Hi @Panda210 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem  **not production app**
Thank you

**Comment by Panda210** [comment]
@TahaTesser 
Already find the reason of the problem. when refactor the code, forget return a route in function **onGenerateRoute** . 
Thank you very much.
