### ISSUE TITLE
Documentation broken link to fast_linear_to_slow_ease_in.mp4

### ISSUE THREAD

**Issue by md-weber** [flutter/flutter#52316]
In Curves.dart there is a broken Link to a specific video.
https://flutter.github.io/assets-for-api-docs/assets/animation/fast_linear_to_slow_ease_in.mp4

```dart
  /// A curve that is very steep and linear at the beginning, but quickly flattens out
  /// and very slowly eases in.
  ///
  /// By default is the curve used to animate pages on iOS back to their original
  /// position if a swipe gesture is ended midway through a swipe.
  ///
  /// {@animation 464 192 https://flutter.github.io/assets-for-api-docs/assets/animation/fast_linear_to_slow_ease_in.mp4}
  static const Cubic fastLinearToSlowEaseIn = Cubic(0.18, 1.0, 0.04, 1.0);
```

**Comment by Zazo032** [comment]
The valid url is https://github.com/flutter/assets-for-api-docs/blob/master/assets/animation/curve_fast_linear_to_slow_ease_out.mp4

**Comment by JosepBove** [comment]
Not really. The valid url should be:
https://flutter.github.io/assets-for-api-docs/assets/animation/curve_fast_linear_to_slow_ease_out.mp4

**Comment by JosepBove** [comment]
There is also an error at

`  /// A cubic animation curve that starts linearly and ends slowly.
  ///
  /// A symmetric animation to [easeInToLinear].
  ///
  /// {@animation 464 192 https://flutter.github.io/assets-for-api-docs/assets/animation/linear_to_ease_out.mp4}
  static const Cubic linearToEaseOut = Cubic(0.35, 0.91, 0.33, 0.97);`

**Comment by pedromassango** [comment]
@JosepBove I tested and it is working fine. I thing this can be closed now

**Comment by JosepBove** [comment]
Yeah this should be closed

**Comment by pedromassango** [comment]
Cc @TahaTesser

**Comment by TahaTesser** [comment]
Thanks @pedromassango 
Closing based on [confirmation](https://github.com/flutter/flutter/issues/52316#issuecomment-631685099)
