### ISSUE TITLE
i try to run flutter doctor to prepare create my new flutter project but, i see that

### ISSUE THREAD

**Issue by 7oka** [flutter/flutter#52314]
flutter doctor
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices
    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual,
      while gradle downloads the missing components. This functionality will
      only work if the licenses in the licenses folder in ANDROID_HOME are
      valid.
      If the Android SDK has been installed to another location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will
      not work without the currently missing SDK components.
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by TahaTesser** [comment]
Hi @7oka 
Please take a look at this [Stackoverflow](https://stackoverflow.com/a/49762939) solution
Thank you

**Comment by 7oka** [comment]
i think internet connection issue ? 
Warning: java.net.UnknownHostException: dl.google.com                           
Warning: File /home/wahrani/.android/repositories.cfg could not be loaded.      
All SDK package licenses accepted.======] 100% Computing updates...

**Comment by 7oka** [comment]
what  that ?!
Warning: File /{userName}/.android/repositories.cfg could not be loaded.      
All SDK package licenses accepted.======] 100% Computing updates...

**Comment by TahaTesser** [comment]
Hi @7oka 

This is is your ` /{userName}/.android` not a  Flutter issue
Please delete the `.android` and restart your PC and try again

**Comment by 7oka** [comment]
problem still not solved what can i do please

**Comment by TahaTesser** [comment]
Hi @7oka 
Since you're using Linux, please check possible [solution](https://askubuntu.com/a/890304)
Thank you

**Comment by 7oka** [comment]
you think  problem in my  OS ?
i using linux since i learning  odoo erp
i think to solve this issue being to reinstalling android  SDK, i don't know!

**Comment by iapicca** [comment]
Hi @7oka 
I think you are in the right direction, the problem is most likely your `android sdk`
rather than flutter, since your `android studio` version is obsolete
I think we can kill 2 birds with 1 stone:
try uninstalling your  AS and reinstall it from the scratch;
if the issue persist please provide your updated `flutter doctor -v`
(the issue might have changes)
Thank you

**Comment by 7oka** [comment]
thanks a lot your instructions were helpful, issue solved
