### ISSUE TITLE
Drawer shadow flashes when drawer appears

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5231]
[✓] Flutter (on Linux, channel master)
    • Flutter at /src/flutter
    • Framework revision 92d0445a8f (43 minutes ago), engine revision 603b0701a6

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/eseidel/Android/Sdk
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.22

See video
https://youtu.be/sK7XSPdNzHo

**Comment by eseidelGoogle** [comment]
@abarth says this is the same root bug as https://github.com/flutter/flutter/issues/5203 and is a bug in Skia that the returned bounds rect for shadows is wrong.  We need to make a reduced test case and file.

**Comment by eseidelGoogle** [comment]
@chinmaygarde can you take on the task of making a reduction for Skia?  I want to make sure that we get this on Skia's radar ASAP as I've had at least one person point this out to me when demoing flutter gallery to them.

**Comment by chinmaygarde** [comment]
Sorry it took so long for this one. Went on a wild goose chase looking in Skia and the framework. Its the raster cache not accounting for the shadow. Skia is fine.

**Comment by chinmaygarde** [comment]
We aren't suggesting that the `cullRect` of the `SkPicture` should include any extensions introduced to shapes as a result of the filters applied on the paints that were used at the time of the draw of said shapes on the canvas are we? Seems like a pretty invasive change.

**Comment by eseidelGoogle** [comment]
@chinmaygarde I don't know.  That's an @abarth question.  Does your raster cache fix resolve https://github.com/flutter/flutter/issues/5203 as well?

**Comment by chinmaygarde** [comment]
Well, so far, there is no raster cache fix. But the issue is in there. https://github.com/flutter/flutter/issues/5203 is also related to the raster cache but its a different issue where the results of to a texture  subsequently rendering that texture to the surface vs rendering directly to the window surface (or parent picture) is resulting in rendering artifacts.

**Comment by sethladd** [comment]
FWIW the shadow flash happens when going into or out of a component demo, too.

**Comment by abarth** [comment]
> We aren't suggesting that the cullRect of the SkPicture should include any extensions introduced to shapes as a result of the filters applied on the paints that were used at the time of the draw of said shapes on the canvas are we? Seems like a pretty invasive change.

There's code in Skia that knows how much filters outset the bounds of the geometry they're filtering.  I thought that was wired up to the cull rect, but maybe it comes out somewhere else?  If the cull rect doesn't take the filter outsets into account, then it can incorrectly cull pictures that actually would intersect a clip rect due to filter outsets.

**Comment by eseidelGoogle** [comment]
@chinmaygarde did you decide if this was a Skia issue or not?

**Comment by eseidelGoogle** [comment]
@chinmaygarde tells me he's tried various fixes, including to the framework and will update the bug shortly.

**Comment by eseidelGoogle** [comment]
Any updates @chinmaygarde?

**Comment by eseidelGoogle** [comment]
@abarth can you take driving this?  I believe @chinmaygarde has a partially completed investigation.

**Comment by abarth** [comment]
Sorry, can't take this on at the moment.

**Comment by chinmaygarde** [comment]
The notes from the last time I investigated this issue:
* The `RasterCache` uses the `cullRect` (and the CTM) of the `SkPicture` to decide the size of the offscreen image in which to snapshot the contents of the picture.
* The `cullRect` does not reflect the bounds of what has been recorded into the picture, i.e the `draw*` operations on the canvas. The origin of the `cullRect` returned is always `{0, 0}`
  * Thus, the `cullRect` may be affected by not only shadows or other filters, but also by custom paint operations drawing to coordinates less than 0 on either axis.
* When the `PictureLayer` decides to perform an `SkImage` substitution of a cached `SkPicture`, it does not know the size of the canvas that was used to create that picture and its offset relative to that picture's `cullRect` origin (which is `{0, 0}`).
* Lacking this information, the PictureLayer draws the `SkImage` just like it would an `SkPicture`. But the origin offsets have not been accounted for.

I am sure I have missed a few things. Will continue investigating this. Just an update.

**Comment by abarth** [comment]
Maybe we need a different API from skia to compute the bounding box of what we recorded into the picture.  We should record the pictures it RTrees, which compute bounding boxes.

**Comment by chinmaygarde** [comment]
> There's code in Skia that knows how much filters outset the bounds of the geometry they're filtering. I thought that was wired up to the cull rect, but maybe it comes out somewhere else?

It is definitely **not** wired up to the cull rect. Is there some other call you can recall that does this? For non-filter related contents that exceed the bounding box, I have successfully wired up the calls into blink::Canvas to keep track of the bounding box. Since we have this extra information, I am able to apply the correct size and offset in the raster cache. This still does not help in the case of the filter however. So it only solves part of the problem.

**Comment by chinmaygarde** [comment]
> This still does not help in the case of the filter however.

Hold on, I have the paint. I can maybe use `getFillPath` to calculate this extra offset and join it with the rest. Trying.

**Comment by chinmaygarde** [comment]
Huzzah! That worked. Cleaning up.

![screen shot 2016-11-14 at 2 01 36 pm](https://cloud.githubusercontent.com/assets/44085/20284660/eaa427b2-aa72-11e6-978b-7e757c64253f.png)

**Comment by chinmaygarde** [comment]
This can be fixed by keeping track of the bounding box and offset on each call to the blink::Canvas API. An example of one such approach is implemented in https://github.com/flutter/engine/pull/3224. However, the suggestion is to implement this API (or some version thereof) in Skia. A ticket for the same is filed in Skia at https://bugs.chromium.org/p/skia/issues/detail?id=5974. Till that ticket is resolved or we decide to land the complete version of https://github.com/flutter/engine/pull/3224, I am blocked on this.

**Comment by eseidelGoogle** [comment]
@chinmaygarde looks like the Skia bug is waiting for feedback from you?

**Comment by eseidelGoogle** [comment]
We had another dev ask about this in gitter just now.  Just checked the Skia bug again just now, looks like it's still waiting for feedback from @chinmaygarde

**Comment by aleki** [comment]
Can I get an ETA on this?

**Comment by sethladd** [comment]
Any updates on this one?

**Comment by chinmaygarde** [comment]
I have been prototyping a fix based on [this comment](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c6) in the linked ticket. Was busy with Vulkan on Fuchsia for the past few weeks so was not able to wrap it up. But I am done with Vulkan for now. Will give you another update when I make progress here.

**Comment by sethladd** [comment]
Confirmed this is still happening on a Nexus 5 with a release build from today.

**Comment by eseidelGoogle** [comment]
@chinmaygarde is there any status update?  Should you still own this?

**Comment by chinmaygarde** [comment]
I am following up on this. I think I should still own this. If someone else does want to take over however, I have prepared a reduced test case in Skia Fiddle that better explains the problem we are seeing in Flutter and the desired behavior we are looking for. The Fiddle is available at https://fiddle.skia.org/c/d3fde342e23b38e35da0759c2ebef573

**Comment by chinmaygarde** [comment]
Some updates from Skia: The API suggested by Skia in [this Fiddle](https://fiddle.skia.org/c/2481faab76b560547a5b98c0be31cc37) requires workarounds for the issues mentioned in [this comment on the ticket](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c9). We have also identified a few failing cases [specific to some pictures](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c15) in Flutter. Some patches fixing [infinite recursion on SkRect::MakeLargest](https://chromium.googlesource.com/skia/+/1dd161c833927d61d436fed68a80b07e44c65226) have landed. But the `kDraws == 1` (mentioned in a comment in the linked Fiddle) and the Flutter specific failure still need to be addressed. From our Skia sync, I understand that Mike is currently working on fixing the rest of the issues.

**Comment by chinmaygarde** [comment]
Update: Mike Klein is working on tracking bounds when a `SkMiniPicture` is rendered as part of the drawing operations.

**Comment by chinmaygarde** [comment]
Update: A patch was posted in Skia that added support for tracking of SkMiniPicture components. After attempting a Skia roll, it was found that while a lot of the previously failing cases were fixed, some `drawTextBlob` and `drawPath` calls were still failing to update the `cullRect`. The failing cases have been added to the [Skia issue tracker here](https://bugs.chromium.org/p/skia/issues/detail?id=5974#c18).

**Comment by eseidelGoogle** [comment]
Progress continues.  Almost done.  Blocked on more fixes from skia.

**Comment by eseidelGoogle** [comment]
Any status updates @chinmaygarde?

**Comment by chinmaygarde** [comment]
Paths and text blobs still don't report their cull rects correctly. Waiting for fixes for the same. Will update this ticket when those changes land.

**Comment by abarth** [comment]
@eseidelGoogle @chinmaygarde I thought this bug was fixed?  @pylaligand seems to have just run into it again.

**Comment by chinmaygarde** [comment]
This issue has been fixed. I should have closed this ticket a while ago.
