### ISSUE TITLE
AppBar Hero Transition could crossfade 

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5232]
https://youtu.be/KbyuPMZ-9_A

@abarth says we should fix this, but to do so would require re-writing the Hero system (which has to happen for other reasons).  Just noting down one example of where being able to fade/animate-color would be nice.
```
[✓] Flutter (on Linux, channel master)
    • Flutter at /src/flutter
    • Framework revision 92d0445a8f (43 minutes ago), engine revision 603b0701a6

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/eseidel/Android/Sdk
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.22
```

**Comment by eseidelGoogle** [comment]
Ignore the text size pop during the animation.  Adam is already fixing that in a separate PR.

**Comment by sethladd** [comment]
This could help address (or completely address)

* [ ] https://github.com/flutter/flutter/issues/5364
* [ ] https://github.com/flutter/flutter/issues/5351
* [ ] https://github.com/flutter/flutter/issues/5350

@HansMuller is that assessment accurate?

**Comment by HansMuller** [comment]
Yes, I think that's the complete list of issues that are directly related to cross-fading the appbar hero transition.

**Comment by zoechi** [comment]
Is here still something to do?

**Comment by guidezpl** [comment]
Closing as obsolete
