### ISSUE TITLE
Mac Web Engine broken after new LUCI capacity installed

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#52327]
https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/601

/cc @godofredoc @nturgut @digiter

**Comment by godofredoc** [comment]
Revert in progress https://chrome-internal-review.git.corp.google.com/c/infradata/config/+/2744257

**Comment by godofredoc** [comment]
Changes have propagated and tests should pass now. Removing the today label.

**Comment by digiter** [comment]
@yjbanov Hi Yegor, do you have any advice on how to fix the machines? The error message was 
```
  LSOpenURLsWithRole() failed for the application /Applications/Safari.app with error -610 for the URL http://localhost:50029/1cNQ2vEe%2FNKTmUFEozLHMEDqxmmq%2BQfa/packages/web_engine_tester/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A50029%2F1cNQ2vEe%252FNKTmUFEozLHMEDqxmmq%252BQfa%2F0&debug=false.
```

**Comment by yjbanov** [comment]
Found this: https://apple.stackexchange.com/questions/233992/crontab-task-lsopenurlswithrole-failed-with-error-600-for-the-file 

Perhaps the issue is that the processes are launched without a normal desktop user session?

**Comment by nturgut** [comment]
Looks like infra is working again after the rollback Mac tests are green: https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/638?reload=30

**Comment by nturgut** [comment]
> @yjbanov Hi Yegor, do you have any advice on how to fix the machines? The error message was
> 
> ```
>   LSOpenURLsWithRole() failed for the application /Applications/Safari.app with error -610 for the URL http://localhost:50029/1cNQ2vEe%2FNKTmUFEozLHMEDqxmmq%2BQfa/packages/web_engine_tester/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A50029%2F1cNQ2vEe%252FNKTmUFEozLHMEDqxmmq%252BQfa%2F0&debug=false.
> ```
> 
> /cc @nturgut
A few ideas:
- We can try to access the machine remotely and make sure we can run "open Safari url ...."
- We can test a PR using led, next time before adding the new capacities

Let me know if I can help with anything

**Comment by digiter** [comment]
The process is launched under the user `swarming`, which I believe doesn't have a desktop session. This is likely the cause.

```
flutter-try-mac-1:~ flutter$ sudo su swarming
Password:
bash-3.2$ whoami
swarming
bash-3.2$ open /Applications/Safari.app/
LSOpenURLsWithRole() failed with error -54 for the file /Applications/Safari.app.
```

**Comment by godofredoc** [comment]
Do we have remote access to set the auto login?

**Comment by digiter** [comment]
Yes. After enabling auto login, reboot, "Diagnostics & Usage" dialog, "iCloud" dialog then we got a successful web engine try build: https://chromium-swarm.appspot.com/task?id=4adf2d73e1c8f610

**Comment by godofredoc** [comment]
Great! can we run led tasks using all the new machines to be sure and sending an update on the email to reenable them tomorrow?

**Comment by nturgut** [comment]
thanks a lot @digiter! I'm glad to hear auto login worked. Please update the issue once the changes are in. We can also keep track how tests are doing and let you know :)

**Comment by digiter** [comment]
@godofredoc I'm working on that, it takes a while to manually config and test all 10 machines. I will send an email later.

**Comment by yjbanov** [comment]
Sounds like the immediate issue is resolved.

**Comment by digiter** [comment]
That's correct, and we are going to adjust the capacity again today.

**Comment by digiter** [comment]
The new capacity has been working for a while.
