### ISSUE TITLE
Getting the error message Invalid plugin specification. and Invalid "macos" plugin specification. on mac flutter 1.10.0

### ISSUE THREAD

**Issue by charles-s-franca** [flutter/flutter#52322]
I downloaded my project and tried to run but I'm getting this error after flutter run.

Invalid plugin specification.
Invalid "macos" plugin specification.

**Comment by VladyslavBondarenko** [comment]
Hi @charles-s-franca 
Do you have that error with a new project (created with `flutter create bug`)?
Note that current stable flutter version is `v1.12.13+hotfix.8`, you can try switch to it.
Provide please your `flutter doctor -v`

**Comment by charles-s-franca** [comment]
Unfortunately, I can't upgrade my project version. I'm using version 1.10.0.

I deleted everything including flutter, reinstalled and changed to the stable channel and now it seems to be working again.

You can close this issue for now and I'll reopen if I have some other issue thank you.

**Comment by Gengpp** [comment]
flutter doctor -v

[✓] Flutter (Channel unknown, v1.10.14, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.10.14 at /Users/jackman/development/flutter
    • Framework revision 1946fc4da0 (5 months ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

➜  FlutterModule git:(8.5.0) flutter pub get
Running "flutter pub get" in FlutterModule...                       0.5s
Invalid plugin specification.
Invalid "macos" plugin specification.
➜  FlutterModule git:(8.5.0)


how to deal it ?
