### ISSUE TITLE
Writing JSON files to the file system

### ISSUE THREAD

**Issue by timo-martin-mueller** [flutter/flutter#52336]
How can I write a JSON file to the file system?

This is the code that throws an error:

```
  Future<String> get getFilePath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  Future<File> get getFile async {
    final path = await getFilePath;
    return File('$path/assets/data/subjects.json');
  }

  Future<File> _saveSubjects() async {
    final file = await getFile;
    String jsonString = '';
    for (var subject in subjects) {
      jsonString += jsonEncode(subject.toJSON());
    }
    return file.writeAsString(jsonString);
  }
```

the error message reads: `[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/timo/Library/Developer/CoreSimulator/Devices/6AC21414-CA4D-4909-94C2-BE0085D6C967/data/Containers/Data/Application/A591B091-4CEE-4F53-8364-F3E770AA7DC2/Documents/assets/data/subjects.json' (OS Error: No such file or directory, errno = 2)`

Thank you.

**Comment by jonahwilliams** [comment]
You need to `file.create(recursive: true)` if the parent directory doesn't exist

**Comment by timo-martin-mueller** [comment]
the directory exists. I want to take the file and rewrite it.

**Comment by jonahwilliams** [comment]
The parent directory does not exist, which is why you're getting `(OS Error: No such file or directory, errno = 2)`

**Comment by timo-martin-mueller** [comment]
could you tell me where I have to add it?
