### ISSUE TITLE
Mac Web Engine to run only on Web directories

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#52330]
Cirrus has this check to run the framework integration tests only after specific directories are changed: https://github.com/flutter/engine/blob/master/.cirrus.yml#L4

Can we add this change to the Mac Recipe?

I also think this is a very good addition to the API we discussed yesterday @godofredoc @yjbanov (The API the recipe will be calling for build, test-run. We can also add a call recipe asks the list of directories the bot will consider)

**Comment by yjbanov** [comment]
Fuchsia infra has built something like this on top of GN. Perhaps we can learn from them. The Cirrus approach is manual and error-prone.

**Comment by yjbanov** [comment]
Not relevant any more after all e2e tests moved to flutter/flutter
