### ISSUE TITLE
codelab RandomWordsState code snippet doesn't match the canonical solution

### ISSUE THREAD

**Issue by ryanmcginnis** [flutter/flutter#52341]
affected page: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5

## Steps to Reproduce

[codelab](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5) says:
```dart
class RandomWordsState extends State<RandomWords> {
  // Add the next two lines.
  final List<WordPair> _suggestions = <WordPair>[];
  final TextStyle _biggerFont = const TextStyle(fontSize: 18); 
  ...
}
```

[solution](https://github.com/flutter/codelabs/blob/b3293b5bb0c0187bdbe8112f7759f4d75f4c040a/startup_namer/step4_infinite_list/lib/main.dart#L22) says:
```dart
class RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[];
  final _biggerFont = const TextStyle(fontSize: 18.0);
```

**Expected results:**
codelab and canonical solution would be the same.

**Actual results:** 
codelab and solution are different, which makes it difficult to understand which is the "correct" code (even though both run).

**Comment by domesticmouse** [comment]
Updated codelab text publication in process
