### ISSUE TITLE
Investigate enabling Metal on iOS simulators above version 13.0.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#52358]
Metal is supported on iOS simulator versions above that level. However, it is not clear if the support is added via host passthrough or emulation. OpenGL emulation was found to be slower than just using the Skia software renderer directly. The same restrictions may apply to Metal as well if it is emulated on simulators. OTOH, if its just host passthrough, Metal on emulators should be a nice bump in rendering performance.

**Comment by dnfield** [comment]
From what I can tell it requires Catalina

**Comment by chinmaygarde** [comment]
Attempting to query the device on the simulator and laptop reveals "Apple iOS simulator GPU" vs "AMD Radeon Pro 460". There may still be some form of passthrough. I am not sure about the performance. Will tackle this after Metal on iOS devices is done for now.

**Comment by chinmaygarde** [comment]
Seems according to guidance in https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator?language=objc.

**Comment by dnfield** [comment]
Yes, and from that doc:

> Instead, Simulator translates any calls you make and directs them to the selected GPU on the host Mac.

**Comment by chinmaygarde** [comment]
Yeah. I saw that. Its pretty exciting. Though, to be honest, most of the work necessary to support this will be in Skia. I'm setting up a call with some Skia folks to discuss unrelated Metal stuff next week. Will bring this up to see how much of an effort this will be.

**Comment by chinmaygarde** [comment]
Support for Metal in the simulators should be enabled in Skia after https://skia-review.googlesource.com/c/skia/+/282270. I'll gather guidance form the Skia folks of how this will be maintained moving forward. But excitingly, it did not seem very involved. Flutter engine should now be able to switch to Metal in `metal_api_selection.mm` based on simulator version. We should get a few perf numbers first before switching everyone to Metal. There is also the question of how Catalina simulators will be disambiguated at runtime.

**Comment by Kavantix** [comment]
From my testing, the impact on simulator performance seems to be huge.
Even the unoptimized engine build feels smoother and uses less resources.

Also, when using metal, plugins like `video_player` work in the simulator.

**Comment by chinmaygarde** [comment]
Sounds good. I have submitted the Skia patch blocking your draft PR. Let's land this thing and make the switch.

**Comment by diegoveloper** [comment]
any news about this? I'm not sure why Flutter apps are running ok on iOS simulators without notch (iPhone 7/8/SE), after I try the app iPhone XR/11/11 Pro Max the animations/transitions look slow than normal. (native apps on Simulator run fine).

**Comment by dnfield** [comment]
This has landed in the engine and should be available in the SDK soon. We can leave this open until it rolls in.

**Comment by dnfield** [comment]
Available in SDK as of https://github.com/flutter/flutter/pull/67705
