### ISSUE TITLE
Material Icon font needs to be bundled automatically on some platforms.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#52360]
For platforms other than Android and web, the `MaterialIcons-Regular.ttf` file is rarely available on the host.

Since we also have [font subsetting code](https://github.com/flutter/flutter/pull/49737), it makes sense to automatically bundle a subset font containing only used icons when building apps.

**Comment by jonahwilliams** [comment]
Isn't this what `uses-material-design` does?

**Comment by gspencergoog** [comment]
If that is what it is for, then I'm pretty sure it doesn't work on Linux.

**Comment by jonahwilliams** [comment]
Does the asset bundle of a linux build end up with a MaterialIcons font in it? You should be able to find it somewhere in the build directory.

If so, then its likely an engine bug. If not, its a tool bug

**Comment by dnfield** [comment]
The font definitely gets bundled by the tool on the platforms where it's currently working.

**Comment by stuartmorgan** [comment]
I'll look into what the current state is on Windows and Linux.

**Comment by stuartmorgan** [comment]
Yep, it's bundled on Linux. And now that I think about it, the default app (the counter) uses `Icons.add` and it works just fine on Linux.

@gspencergoog Are we sure the app that led to this bug being filed actually set `uses-material-design`? I think we need a repro case here.

**Comment by gspencergoog** [comment]
No, I'm not sure: I never saw the code myself: @csells do you have the code?

**Comment by csells** [comment]
Correct -- the app that wasn't showing the Material icons didn't have the `uses-material-design` property set to `true` in the `pubspec.yaml`. Adding that line fixed the problem.
