### ISSUE TITLE
Missing public member api docs in template

### ISSUE THREAD

**Issue by fingeg** [flutter/flutter#52368]
In my project the dart analyzer always shows an document all public members warning for the `lib/generated_plugin_registrant` file.

The best way would be to add an `// ignore: public_member_api_docs` to the [plugin](https://github.com/flutter/flutter/blob/53dce17b35353f795faa6e0509c6fa321a378a32/packages/flutter_tools/lib/src/plugins.dart#L761) file.

**Comment by dnfield** [comment]
We could also document the public members in there. But ignoring would be fine.  If you want to open a PR to do that it should be pretty simple.

**Comment by fingeg** [comment]
I created the PR with the new ignore line
