### ISSUE TITLE
Include a search option on the build dashboard

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#52370]
https://flutter-dashboard.appspot.com/#/build

While triaging flakes, we wanted to look up a particular test to see if it had been flaky recently. The dashboard only shows the test name on hover, so it took a while to track down the one we were looking for.

It would be nice if there was a search bar that made it easier to find, like the benchmarks page.

**Comment by Piinks** [comment]
fyi @goderbauer :)

**Comment by liyuqian** [comment]
As we're adding more and more devicelab tests, I think this search/filter option would be very very useful.

**Comment by Piinks** [comment]
There is a proposal for this: https://github.com/flutter/cocoon/pull/948
