### ISSUE TITLE
Firebase realtime equalTo

### ISSUE THREAD

**Issue by BasharAlayan** [flutter/flutter#52377]
Hello 
i have a problem when i want to get a specific data form firebase realtime so i used the function equalTo(...) for return the data that i want, but i all the cases this return a query which containe the first element in my firebase

the code :

![Capture](https://user-images.githubusercontent.com/45371809/76375056-2bfb3c80-6345-11ea-9cdd-9a990defd1c2.PNG)

![Capture](https://user-images.githubusercontent.com/45371809/76374966-ea6a9180-6344-11ea-94a0-1698eb3e0155.PNG)

**Comment by dnfield** [comment]
This would be more appropriate in https://github.com/FirebaseExtended/flutterfire

**Comment by BasharAlayan** [comment]
thank you that help me a lot
