### ISSUE TITLE
blank screen,but can response click action

### ISSUE THREAD

**Issue by tcking** [flutter/flutter#52383]
We are using Flutter in our production,some customers send us the  issue that the page is blank,but the blank page is able to click and response click action，we have a video from a customer.
[video of blank flutter page](https://v.youku.com/v_show/id_XNDU4Mjc0NzQzNg==.html)
[video of normal](https://v.youku.com/v_show/id_XNDU4Mjc2NjQ2OA==.html)

the flutter page activity code:

``` kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val flutterView = Flutter.createView(this, lifecycle, routeHistoryPage)
        flutterView.setZOrderOnTop(true)
        flutterView.holder.setFormat(PixelFormat.TRANSLUCENT)
        setContentView(flutterView)
    }
```

our dart code is like this:

``` dart



class OrderHistoryApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((d){
      print("tflutter_page_show"); //this log is print when screen is blank
    });
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      localizationsDelegates: [
        StringLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: SUPPORT_LANGUAGE,
      home: OrderHistoryPage(),
    );
  }
}


```
this iusse is report more then 10 times with different devices and we can't reproduce this problem in with our devices.

**Comment by zw1924** [comment]
Mark

**Comment by TahaTesser** [comment]
Hi @tcking 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by tcking** [comment]
> Hi @tcking
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

@TahaTesser Thanks for your  reply, this issue only occur on customer's devices with release  app，it is difficult to ask our customer service run this cmd on customer device，and unfortunately we also can't  reproduce the problem。what kand of problem may cause this issue？can some one give some  suggest so we can try to reproduce the problem

**Comment by mcxinyu** [comment]
I also encountered this problem, but I added flutter to an existing app.
Flutter is added to an existing app in aar way. How do I provide more information?

**Comment by zw1924** [comment]
Please add  [EAGLContext setCurrentContext:null];  to env change

**Comment by nmondal** [comment]
![Screenshot 2020-03-26 at 1 18 45 PM](https://user-images.githubusercontent.com/1222935/77622548-7a732280-6f64-11ea-8fa7-6d34f7666f49.png)
Same problem here.

**Comment by darshankawar** [comment]
@tcking 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue still persists, is it possible to get a reproducible code sample that shows the issue in non-prod environment ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
