### ISSUE TITLE
Text Widget does not change color when dark mode is enabled.

### ISSUE THREAD

**Issue by VictorUvarov** [flutter/flutter#52381]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: CupertinoPageScaffold(
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text('Text'),
              TextWidget(),
            ],
          ),
        ),
      ),
    );
  }
}

class TextWidget extends StatelessWidget {
  const TextWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Text('Text Widget');
  }
}
```
3. Switch to dark mode on phone settings

**Expected results:** 
In a MaterialApp the text turns white by default, this should be the same for CupertinoApps.
**Actual results:** 
Text remains the same default black color.

**Comment by aqwert** [comment]
https://github.com/flutter/flutter/issues/48401 seems like the same issue. Not sure that the solution is ideal IMO

**Comment by TahaTesser** [comment]
Duplicate  of [#48438](https://github.com/flutter/flutter/issues/48438)
