### ISSUE TITLE
== opearators for List is broken.

### ISSUE THREAD

**Issue by FabrizioG2000** [flutter/flutter#52400]
When calling `[true, false] == [true, false]` yields ` false`, so as members of the equality were different, which isn't the case.

this is the Flutter doctor:
[√] Flutter (Channel master, v1.15.20-pre.20, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.15.20-pre.20 at E:\ActualPC\Flutter\flutter
    • Framework revision 4049889d9e (9 hours ago), 2020-03-10 20:05:41 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\------\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by Zazo032** [comment]
Does this [solution](https://stackoverflow.com/a/22333042) work for you?

**Comment by VladyslavBondarenko** [comment]
Thanks  @Zazo032 ,
@FabrizioG2000 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
