### ISSUE TITLE
ChangeNotifier should get method removeListeners()

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#52404]
## Use case
The [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) allows for removing listeners by providing exactly the reference to the added listeners.

This makes it a little complicated, if one would simply remove all listeners, for instance within `dispose()` when leaving a view.

I had to write this much code to add and remove listeners to/from the view when entering/leaving the view:

```
  //current up- and downloads
  List<Transfer> _transfers;

  //map of added listeners
  //objects of type Transfer have a field 'info' that is a ValueNotifier (extends ChangeNotifier)
  Map<Transfer, Function> listeners = {};

  @override
  void initState() {
    super.initState();
    _transfers = transferService.getCurrentTransfers();
    _transfers.forEach((t) {
      _registerListener(t);
    });
  }

  @override
  void dispose() {
    listeners.entries.forEach((element) {
      element.key.info.removeListener(element.value);
    });
    super.dispose();
  }

  void _registerListener(Transfer t) {
    Function f = () => () {
      //code that runs when ChangeNotifier fires
    };
    listeners.addEntries([MapEntry(t,f)]);
    t.info.addListener(f);
  }
```

## Proposal

If `ChangeNotifier` had a `removeListeners()` function, that simply removes all previously added listeners, people would not need to keep track of the added listeners to be able to remove them all.

Unfortunately it's not an option to extend `ValueNotifier` or `ChangeNotifier` since the `_listeners` field is private there.

**Comment by goderbauer** [comment]
You can just call dispose on a ValueListener or ChangeNotifier. That removes all its listeners and disposes the object.

Adding a method that just removes all listeners unquestioned seems dangerous if you don't own the object. Somebody else may have added a listener and doesn't expect it to get removed.

I don't think we should do this. The code you have to write to enable this isn't that complicated and you could easily encapsulate it in a separate class.

**Comment by technolion** [comment]
> You can just call dispose on a ValueListener or ChangeNotifier. That removes all its listeners and disposes the object.
No, @goderbauer  unfortunately that's not the possible. I tried it. When calling `dispose()` on a `ValueNotifier` before leaving the view the following exception occurs:

`Exception has occurred.
DioError (DioError [DioErrorType.DEFAULT]: A ValueNotifier<TransferInfo> was used after being disposed.
Once you have called dispose() on a ValueNotifier<TransferInfo>, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:106:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:112:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:201:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)`

This is probably due to the fact, that `dispose()` on the `ChangeNotifier` just nulls the list of _listeners:
```
 /// Discards any resources used by the object. After this is called, the
  /// object is not in a usable state and should be discarded (calls to
  /// [addListener] and [removeListener] will throw after the object is
  /// disposed).
  ///
  /// This method should only be called by the object's owner.
  @mustCallSuper
  void dispose() {
    assert(_debugAssertNotDisposed());
    _listeners = null;
  } 
```

By the way, this method's description tells me, that I cannot use it, if there is still a `ValueNotifier` in the wild..

So, would it be an option to change `ChangeNotifier`'s `dispose()` method like as follows?

```
  @mustCallSuper
  void dispose() {
    assert(_debugAssertNotDisposed());
    _listeners.forEach((element) {
      _listeners.remove(element)
    })
  }
```

**Comment by technolion** [comment]
Since I put some work into reporting this issue and offering a solution, could you please at least comment @goderbauer?

**Comment by goderbauer** [comment]
I don't think dispose needs to be changed. The whole point of dispose is to disable the object so it can no longer be used. The thing that registers a listener is responsible for removing it. I don't see what's wrong with writing the code to just remove all listeners.
