### ISSUE TITLE
[Linux] localeResolutionCallback returns null

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#52403]
On master channel `localeResolutionCallback` on Linux returns null.
```
MaterialApp(
           localeResolutionCallback: (locale, supportedLocales) {
                return locale;
           },
...
);
```
I have `en_US` locale on my Linux:
```
[✓] Flutter (Channel master, v1.15.19, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (4 available)
```

**Comment by VladyslavBondarenko** [comment]
Hi @aliyazdi75 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/45343,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
