### ISSUE TITLE
flutter build ios-framework doesn't contain FlutterPluginRegistrant.framework and plugins.framework

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#52402]
## Steps to Reproduce

1. when I use command flutter build ios-framework to build ios framework in my module
no error.
output:├─Populating Flutter.framework...                                 177ms
 ├─Add placeholder App.framework for debug...                      213ms
 ├─Assembling Flutter resources for App.framework...                1.9s
Running pod install...                                             10.0s
 ├─Building plugins...                                             37.5s
 └─Moving to build/ios/framework/Debug                              0.3s

I can't find the FlutterPluginRegistrant.framework and my all pugins framework. actually, I have some plugins

flutter doctor:flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

**Expected results:** 
├── Debug/
    │   ├── Flutter.podspec
    │   ├── App.framework
    │   ├── FlutterPluginRegistrant.framework
    │   └── my_plugins.framework 
    ├── Profile/
    │   ├── Flutter.podspec
    │   ├── App.framework
    │   ├── FlutterPluginRegistrant.framework
    │   └── my_plugins.framework
    └── Release/
        ├── Flutter.podspec
        ├── App.framework
        ├── FlutterPluginRegistrant.framework
        └── my_plugins.framework

**Actual results:** 
![image](https://user-images.githubusercontent.com/5379447/76417196-657c8800-63d7-11ea-9a3b-4f3ff07fcd13.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @qylshy ,
> actually, I have some plugins 

by this you mean that https://github.com/flutter/flutter/issues/50364 isn't your case, right?

**Comment by qylshy** [comment]
> Hi @qylshy ,
> 
> > actually, I have some plugins
> 
> by this you mean that #50364 isn't your case, right?

right！ I have 7 plugins，eg sqflite and so on

**Comment by jmagman** [comment]
Can you attach your pubspec.yaml?

**Comment by qylshy** [comment]
> Can you attach your pubspec.yaml?

I modify my Podfile，
Comment the use_frameworks!
# use_frameworks!  is this may affect？

**Comment by jmagman** [comment]
@qylshy `use_framework!` in your hosted Podfile is fine.  Can you attach your Flutter module's pubspec.yaml?

**Comment by qylshy** [comment]
> @qylshy `use_framework!` in your hosted Podfile is fine. Can you attach your Flutter module's pubspec.yaml?

sorry，pubspec.yaml contain private pub，and  the problem has been located， when modify the podfile  delete use_frameworks!  line it‘s not ok，  when I keep the podfile as original it’s ok。 it can generate the plugins framework

**Comment by jmagman** [comment]
@qylshy Sorry, I'm not following.  Are you saying added `use_frameworks!` to your app's Podfile, or to the Flutter module?  The Flutter module's at `.ios/Podfile` [already uses `use_frameworks!`](https://github.com/flutter/flutter/blob/e491544588e8d34fdf31d5f840b4649850ef167a/packages/flutter_tools/templates/module/ios/host_app_ephemeral_cocoapods/Podfile.copy.tmpl#L6).  And your app's (the hosted, existing app)'s Podfile shouldn't matter at all for `flutter build ios-framework` since that command doesn't know anything about your app.

**Comment by qylshy** [comment]
> @qylshy Sorry, I'm not following. Are you saying added `use_frameworks!` to your app's Podfile, or to the Flutter module? The Flutter module's at `.ios/Podfile` [already uses `use_frameworks!`](https://github.com/flutter/flutter/blob/e491544588e8d34fdf31d5f840b4649850ef167a/packages/flutter_tools/templates/module/ios/host_app_ephemeral_cocoapods/Podfile.copy.tmpl#L6). And your app's (the hosted, existing app)'s Podfile shouldn't matter at all for `flutter build ios-framework` since that command doesn't know anything about your app.

I means My Flutter Module at .ios/Podfile  has been removed the use_framework!.
![image](https://user-images.githubusercontent.com/5379447/76940670-a4f62780-6935-11ea-9b78-c42a76d561aa.png)

**Comment by jmagman** [comment]
Ah, I see.  You commented out `use_frameworks!` in your Podfile and then it didn't generate the plugin frameworks.  That's expected.  See https://github.com/flutter/flutter/pull/40927.
Closing, the generated template is doing the right thing.
