### ISSUE TITLE
animated_placeholder_perf missed_frame_rasterizer_budget_count and animated_placeholder_perf worst_frame_rasterizer_time_millis regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52414]
Looks like at https://github.com/flutter/flutter/pull/52354. That's a tool PR, though, so I'm not sure why it's the case, unless the tool pulling the stats has problems.

At any rate, this benchmark historically has been very noisy and difficult to find regressions with.

**Comment by jmagman** [comment]
Those benchmarks look all over the place, probably not caused by https://github.com/flutter/flutter/pull/52354?
\cc @zanderso just in case.

Infra team, any insight?  Are these devices in a bad state?
\cc @godofredoc

**Comment by zanderso** [comment]
What's the target's platform for those benchmarks? If not iOS, then the fallback discovery code changed by https://github.com/flutter/flutter/pull/52354 wouldn't even run.

**Comment by godofredoc** [comment]
This is running on linux test beds. Seems like we are getting bad values from multiple machines:

flutter-devicelab-linux-3
flutter-devicelab-linux-4
Flutter-devicelab-linux-5

**Comment by godofredoc** [comment]
Checking missed_frame_rasterizer_budget_count in linux-5 I got:

Iteration 1: 86
Iteration 2: 87
Iteration 3: 106
Iteration 4: 79
Iteration 5: 85

**Comment by godofredoc** [comment]
Rebooting phone and machine didn't help. I think this is a real issue

**Comment by jonahwilliams** [comment]
I can't look at historical data, but have these benchmarks always had such a wide variance? There might be a slight regression somewhere but practically we'll be unable to tell culprit PRs

**Comment by jmagman** [comment]
Let's have the engine team look at it based on the test that's failing, since we're unable to pin this to a tool regression.

**Comment by jmagman** [comment]
\cc @dnfield @liyuqian

**Comment by liyuqian** [comment]
The worst frame time seems to be back to normal. I've archived the missed frame benchmark as we've replaced it with 90th/99th percentile time (https://github.com/flutter/flutter/issues/18727). I created https://github.com/flutter/flutter/issues/52554 to track the removal of missed frame from perf test framework so our dashboard doesn't have to archive it for every new test.
