### ISSUE TITLE
[triage] Github references on issue when it wasn't supposed to be a mention

### ISSUE THREAD

**Issue by VladyslavBondarenko** [flutter/flutter#52418]
Example:
https://github.com/flutter/flutter/issues/138 has a lot of  references.
Most of them are simply line number from logs, and `#138` considered as reference
```
I/flutter ( 7653): #138 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
```
This is true even when the log is inside of code symbols (like here https://github.com/flutter/flutter/issues/51922)

This behaviour could be avoided with using repository name in front of the issue number for links (as when you are referencing on the issue from another repo), but I'm not sure is it possible to change.

Probably it's a known issue

**Comment by stuartmorgan** [comment]
> This is true even when the log is inside of code symbols (like here #51922)

I've never seen it happen for things inside a code block. In the example you link to there the reporter did not use a code block, creating the bogus link, and then someone edited it later.

> This behaviour could be avoided with using repository name in front of the issue number for links (as when you are referencing on the issue from another repo), but I'm not sure is it possible to change.

I assume you're suggesting requiring that and not allowing bare # linking? That's [not how GitHub works](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls)

Closing as we have no ability to change GitHub's core autolinking behavior.
