### ISSUE TITLE
Creating FlutterViewController using FlutterEngine causes channel communication issues

### ISSUE THREAD

**Issue by SarielTang** [flutter/flutter#52417]
I use the FlutterViewController with anonymous flutterEngine directly under the iOS system, and can use multiple channels to communicate normally.
However, when the FlutterEngine is created in advance to optimize the first startup, this FlutterViewController specifies this Engine, and only one of my channels can be used normally, I don't know what happened

**Comment by VladyslavBondarenko** [comment]
Hi @SarielTang 
Could you provide your `flutter doctor -v`?

**Comment by SarielTang** [comment]
![image](https://user-images.githubusercontent.com/12050371/76493187-023d3500-646d-11ea-99ee-e5f5d563e67c.png)
@VladyslavBondarenko

**Comment by jmagman** [comment]
\cc @xster

**Comment by xster** [comment]
@SarielTang can share some reproduction steps or sample code for us to follow? We're unaware of this issue but conceptually, there shouldn't be a difference. Make sure to register your channel with the right instance of the flutter engine.

**Comment by SarielTang** [comment]
@xster ![image](https://user-images.githubusercontent.com/12050371/76581946-f5255200-650f-11ea-8cb3-053e905cb118.png)
![image](https://user-images.githubusercontent.com/12050371/76581966-02424100-6510-11ea-8197-a0ab3c9103f1.png)
this is my code in iOS。
![image](https://user-images.githubusercontent.com/12050371/76582041-27cf4a80-6510-11ea-933c-78d0c90a48ee.png)
![image](https://user-images.githubusercontent.com/12050371/76582128-5e0cca00-6510-11ea-9e17-7f3146e16d5f.png)
![image](https://user-images.githubusercontent.com/12050371/76582181-80064c80-6510-11ea-9346-69ee3d970731.png)
and this is my code in flutter。
The ‘native_common_channel’ channel can be used normally every time, but the ‘native_network_channel’ channel. When I initialize it on the iOS side, the specified Engine will be invalid.

**Comment by SarielTang** [comment]
When I use Engine to initialize FlutterViewController, this channel will fail.

**Comment by xster** [comment]
"When I initialize it on the iOS side, the specified Engine will be invalid." what does this mean exactly? Is there any specific error that appears?

Also cc @gaaclarke

**Comment by SarielTang** [comment]
I used the translation software directly, and the translation was a bit problematic, so I reorganized the language and spoke a bit later.  I mean，when I use Engine to initialize FlutterViewController, this channel will fail.

**Comment by SarielTang** [comment]
@xster Sorry, the translation software I used before has some problems with translation. What I mean is that when I use flutterEngine to warm up, my 'native_common_channel' will fail.

**Comment by SarielTang** [comment]
@gaaclarke @xster Is there anything else I need to provide?

**Comment by gaaclarke** [comment]
> only one of my channels can be used normally

What does it look like when the other channels doesn't work?

> binaryMessenger: voteVC

If you look at this line you have a warning that are ignoring, `voteVC` is not a binary messenger.  I recommend adding `-Werror` in you objective-c code.  This warning shouldn't be breaking you, but you might have other warnings.

---

I browsed the code and I don't see anything wrong immediately, but I also don't have a clear idea about what the error is.  I recommend creating a minimal reproduction for this error so we can execute it and see all the code =)

**Comment by SarielTang** [comment]
@gaaclarke 
I wrote a demo and found that it can be used normally. It may be caused by some configuration in the previous iOS project. I will study it again.
