### ISSUE TITLE
Text capitalization on non-platform (non-default) keyboards

### ISSUE THREAD

**Issue by Sandrichka22** [flutter/flutter#52416]
There is a prop that can configure the text capitalization in Flutter: 

https://api.flutter.dev/flutter/material/TextField/textCapitalization.html

but it only works for the platform keyboard. Is it planned to have an implementation that will work on non-platform keyboards?

**Comment by justinmc** [comment]
On Android textCapitalization sets these flags: https://github.com/flutter/engine/blob/06c8a2909e4205d2e845fb948f364521229add51/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L183
And on iOS it sets UITextAutocapitalizationType: https://github.com/flutter/engine/blob/06c8a2909e4205d2e845fb948f364521229add51/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L36

Do you know what else it would need to do to support the third part keyboard that you want?

**Comment by Sandrichka22** [comment]
I see.. In my opinion, for Android at least, this is all that needs to be done.. I tried looking for alternative approaches for 3rd party keyboards, but did not find anything specific... Maybe it depends on the keyboard's implementation itself and there is nothing that can be done... If someone has some other ideas, feel free to share

**Comment by markusaksli-nc** [comment]
Closing this issue for now since this does work for most third-party keyboards and we would need more information on how to support third-party keyboards with unorthodox handling of this property. 

If you can point out a specific keyboard that doesn't auto-capitalize on latest Flutter, let us know and we can re-open.
