### ISSUE TITLE
After soft keyboard disappears, app window doesn't resize on full height (flutter web)

### ISSUE THREAD

**Issue by NaikSoftware** [flutter/flutter#52423]
App has text fields and buttons on screen. Window wrapped in material Scaffold. If I click on text field, soft keywords is shown. After that I click on button, that call builtin date picker, and keyboard dissapears, but sometimes window holds old size. Looks like resize event not called for the app. 
![Screenshot_20200311-182622](https://user-images.githubusercontent.com/4218994/76441360-f481a400-63c7-11ea-9cbf-3b92c2295e45.png)

The similar bugs happens also on the desktop during resize browser window. Sometimes app window holds irrelevant size.

Expected behaviour: app window must always occupy entire available space.

Flutter version: last version in beta channel.

Reprodused on many devices (chrome). I tried call unfucus on fucus scope on button click, but its doesn't take any effect.

**Comment by VladyslavBondarenko** [comment]
Hi @NaikSoftware 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/50382
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
