### ISSUE TITLE
Apply retry logic to existing cocoon backend

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#52427]
Retry logic is being implemented: 
https://github.com/flutter/cocoon/pull/683

It would be good to apply it to all other existing APIs which are suitable. Some examples:
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/append_log.dart#L64
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/push_build_status_to_github.dart#L92
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/reserve_task.dart#L69
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_github_commits.dart#L286

**Comment by CaseyHillers** [comment]
The cache service also has this retry logic implemented too

**Comment by godofredoc** [comment]
Fixed with: 
Update remaining handlers to use service/datastore https://github.com/flutter/cocoon/pull/737.
Refactor handlers to use service/datastore https://github.com/flutter/cocoon/pull/736. 
Refactor reserve_task handler to use datastore https://github.com/flutter/cocoon/pull/732.
