### ISSUE TITLE
ListTile should have the option to center the Leading Widget

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#52439]
`ListTile` automatically chooses if the `leading` widget will be centered, or at a fixed distance from the top. This decision was made by interpreting the Material Design Specs, this is the snippet for its `RenderBox`:

```dart
   // This attempts to implement the redlines for the vertical position of the
   // leading and trailing icons on the spec page:
   //   https://material.io/design/components/lists.html#specs
   // The interpretation for these red lines is as follows:
    //  - For large tiles (> 72dp), both leading and trailing controls should be
    //    a fixed distance from top. As per guidelines this is set to 16dp.
    //  - For smaller tiles, trailing should always be centered. Leading can be
    //    centered or closer to the top. It should never be further than 16dp
    //    to the top.
    double leadingY;
    double trailingY;
    if (tileHeight > 72.0) {
      leadingY = 16.0;
      trailingY = 16.0;
    } else {
      leadingY = math.min((tileHeight - leadingSize.height) / 2.0, 16.0);
      trailingY = (tileHeight - trailingSize.height) / 2.0;
    }
```

But the specs at https://material.io/design/components/lists.html#specs don't have anything that can be interpreted as if the height of the widget influences if the `leading` should be centered or not. There are examples of centered and not centered for the same height.

I propose that `ListTile` have an additional property, `shouldCenterLeading` that overrides this calculations and fixes the `leading` widget as a centered widget, despite any calculations.

![image](https://user-images.githubusercontent.com/8120472/76467808-3d862800-63c9-11ea-9227-ac9b807d2fe6.png)

**Comment by LuisMiguelSS** [comment]
Any update on this?

**Comment by oravecz** [comment]
I would propose that this feature request is extended to support Align widget wrapping the Leading widget to have more control over the position of the icon (or checkbox in the case of CheckboxListTile) in the Leading Area.

**Comment by TahaTesser** [comment]
This is now possible using the `titleAlignment` property, for instance use `titleAlignment: ListTileTitleAlignment.center` in the `ListTileThemeData`. This will override the automatic leading position. behavior.

```dart
   body: Center(
          child: ListTileTheme(
            data: const ListTileThemeData(
              titleAlignment: ListTileTitleAlignment.center,
              contentPadding: EdgeInsets.zero, // For demonstration.
              minVerticalPadding: 0, // For demonstration.
            ),
            child: CheckboxListTile(
              title: const Text(
                  'lorem ipsum dolor sit atem lorem ipsum dolor sit atem lorem ipsum dolor sit atem lorem ipsum dolor sit atem lorem ipsum dolor sit atem lorem ipsum dolor sit atem lorem ipsum dolor sit atem'),
              value: false,
              controlAffinity: ListTileControlAffinity.leading,
              onChanged: (bool? value) {},
            ),
          ),
        ),
```

![Screenshot 2024-03-18 at 17 46 07](https://github.com/flutter/flutter/assets/48603081/6016aeb0-7146-43d6-b398-4231770b8e96)



See https://api.flutter.dev/flutter/material/ListTile/titleAlignment.html for more details
