### ISSUE TITLE
Use both SHA and branch as commit key in datastore

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#52443]
This is a track down issue following: https://github.com/flutter/flutter/issues/51884

SHA only as commit key is not suffice for saving records with same SHA but different branches. Latter record with a different branch name will override existing one which has the same SHA.

**Comment by godofredoc** [comment]
Can we use a composite key here? sha + branch?

**Comment by keyonghan** [comment]
That's what I plan to do:-)
