### ISSUE TITLE
Unable to launch the application on the mobile : 

### ISSUE THREAD

**Issue by lontchianicet** [flutter/flutter#52441]
Build failed since the latest upgrade.

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:88:7: Error: The type 'Diagnosticable' can't be used as supertype.
class PictureStream extends Diagnosticable {
      ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:192:16: Error: The type 'Diagnosticable' can't be used as supertype.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:88:7: Error: The type 'Diagnosticable' can't be used as supertype.
class PictureStream extends Diagnosticable {
      ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:192:16: Error: The type 'Diagnosticable' can't be used as supertype.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.1/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 840

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
Exception: Gradle task assembleDebug failed with exit code 1

Here is the doctor output:

[√] Flutter (Channel master, v1.15.21-pre.3, on Microsoft Windows [version 10.0.18362.657], locale fr-CH)
    • Flutter version 1.15.21-pre.3 at C:\flutter
    • Framework revision 5e74b004b8 (3 hours ago), 2020-03-11 12:48:50 -0700
    • Engine revision 6d8611d0bd
    • Dart version 2.8.0 (build 2.8.0-dev.13.0 37530145ff)

**Comment by Botary** [comment]
It's because of Convert Diagnosticable to a mixin [#51495](https://github.com/flutter/flutter/pull/51495), The plugin that you use extends Diagnosticable abstract class that became a mixin

**Comment by jonahwilliams** [comment]
FYI this should be fixed in a newer version of flutter_svg, see https://pub.dev/packages/flutter_svg#0172

**Comment by jonahwilliams** [comment]
Closing, because this isn't a bug with the framework

**Comment by aldinlapinig** [comment]
I am experiencing this exact same issue now. How did you fix this, lontchianicet? Above solutions didn't work.

**Comment by rajkiran-AST** [comment]
> I am experiencing this exact same issue now. How did you fix this, lontchianicet? Above solutions didn't work.

just upgrade your svg_flutter in pubspec.yaml

**Comment by lontchianicet** [comment]
@aldinlapinig 
Yes the above solution works. Just upgrade your flutter_svg as @rajkiran-AST said
