### ISSUE TITLE
CanvasKit crash after interacting with the flutter web version of dart devtools for a bit.

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#52447]
Repro steps.
`pub global activate devtools 0.2.4-dev.1`
Interact with the timeline or inspector for a bit on a macbook pro. Eventually devtools will hang and you will see an error like the following in the chrome devtools console.
<img width="574" alt="Screen Shot 2020-03-11 at 4 58 50 PM" src="https://user-images.githubusercontent.com/1226812/76474750-d01ecb00-63b9-11ea-9fc3-dfd288229b0d.png">

**Comment by jacob314** [comment]
Fyi @hterkelsen

**Comment by mariamhas** [comment]
@hterkelsen is this issue related to/resolved with your latest canvaskit version update?

**Comment by mariamhas** [comment]
confirmed problem fixed with #56938; closing issue
