### ISSUE TITLE
Engine v1.12.13-hotfixes has bug when using AddToApp

### ISSUE THREAD

**Issue by xujim** [flutter/flutter#52455]
hi, I found engine v1.12.13-hotfixes is not ok with the add to app. When I pushed multiple FlutterViewController and pop back, the app will crash due to accessing the nulled surface in  Rasterizer::Setup. Here is my mini example to reproduce the problem: https://github.com/xujim/testaccessibility

## The steps to reproduce the crash
Here is my add to app example to reproduce the crash bug:
https://github.com/xujim/testaccessibility
With this example installed, you just need to "Open Flutter Page", and again and again, then pop back the VC, finally, it crashed.

## The Root Cause Analysis
It is caused by the sequence of Setup and Teardown of Rasterizer in the addToApps circumstance.
In the addToApps, we need to push and pop multiple VC, it will lead to setup and teardown of surface more than one time. And the setup and teardown tasks are queued by GPU thread. 
However, note that the surface is held by on Engine, and the underlying memory is shared by the tasks(setup and teardown task) in the GPU thread queue. This will cause a situation, that a setup task need to access surface which has just been teardown in the last teardown task. Just as following diagram:
![image](https://user-images.githubusercontent.com/3032016/76485503-9f8d6e80-6457-11ea-997b-e2ec8282672f.png)

Change the Rasterizer::Setup function this way can avoid the crash, even though it might be not the best fix:
![image](https://user-images.githubusercontent.com/3032016/76486336-0f045d80-645a-11ea-940d-b8740e9c9765.png)

### My Flutter Version
```
 testaccessibility git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel v1.12.13-hotfixes, v1.12.13+hotfix.8, on Mac OS X 10.14.6
    18G95, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at
      /Users/yujie/Desktop/FlutterWork/flutter_Github
    • Framework revision 0b8abb4724 (4 周前), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
```

**Comment by xujim** [comment]
@xster please take a look

**Comment by kangwang1988** [comment]
CC @dnfield

**Comment by xster** [comment]
@gaaclarke can you take a look?

**Comment by dnfield** [comment]
Does this bug still exist on master?

**Comment by xujim** [comment]
I am afraid it still exist

**Comment by dnfield** [comment]
Hm.  Both the Android and the iOS embedding believe they can return nullptr in `CreateRenderingSurface` if they have no surface to work with, which can happen if they get that call without having a view to work with (or, before having a view to work with).

That should only be valid if there really is no View to work with. But in this case, there should be.

I haven't traced this all the way through, but it seems like we might not be calling `NotifyCreated` properly in this case - it also seems like we should _not_ try to setup the rasterizer if there is in fact no surface to work with.

/cc @chinmaygarde @amirh @cyanglaz 

@gaaclarke probably has more recent context on this than I do as well but those people might be interested in the platform view/rasterizer aspects.

**Comment by gaaclarke** [comment]
stacktrace:
```
#0	0x00000001092346e8 in flutter::Rasterizer::Setup(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >) at /Users/aaclarke/dev/engine/src/flutter/shell/common/rasterizer.cc:69
#1	0x0000000109254b4a in flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8::operator()() at /Users/aaclarke/dev/engine/src/flutter/shell/common/shell.cc:609
#2	0x0000000109248ed1 in auto fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>::operator()<>() const at /Users/aaclarke/dev/engine/src/flutter/fml/make_copyable.h:24
#3	0x000000010927a10d in decltype(std::__1::forward<fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>&>(fp)()) std::__1::__invoke<fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>&>(fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/type_traits:4350
#4	0x000000010927a0bd in void std::__1::__invoke_void_return_wrapper<void>::__call<fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>&>(fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/__functional_base:349
#5	0x0000000109279261 in std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>, std::__1::allocator<fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8> >, void ()>::operator()() at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1572
#6	0x00000001090eb595 in std::__1::function<void ()>::operator()() const at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1923
#7	0x00000001090ff483 in fml::MessageLoopImpl::FlushTasks(fml::FlushType) at /Users/aaclarke/dev/engine/src/flutter/fml/message_loop_impl.cc:127
#8	0x00000001090ff36a in fml::MessageLoopImpl::RunExpiredTasksNow() at /Users/aaclarke/dev/engine/src/flutter/fml/message_loop_impl.cc:137
#9	0x0000000109112885 in fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) at /Users/aaclarke/dev/engine/src/flutter/fml/platform/darwin/message_loop_darwin.mm:75
```

**Comment by gaaclarke** [comment]
The following assert can fail because `platform_view->CreateRenderingSurface()` is returning null (as dan pointed out)
```diff
--- a/shell/common/platform_view.cc
+++ b/shell/common/platform_view.cc
@@ -74,6 +74,7 @@ void PlatformView::NotifyCreated() {
         latch.Signal();
       });
   latch.Wait();
+  assert(surface);
   delegate_.OnPlatformViewCreated(std::move(surface));
 }
```

Here is the code where PlatformViewIOS [returns nullptr](https://github.com/flutter/engine/blob/1aaf1698826c9a1fad3799a2214f6bdae13d8e0e/shell/platform/darwin/ios/platform_view_ios.mm#L105):
```objc
std::unique_ptr<Surface> PlatformViewIOS::CreateRenderingSurface() {
  FML_DCHECK(task_runners_.GetGPUTaskRunner()->RunsTasksOnCurrentThread());
  std::lock_guard<std::mutex> guard(ios_surface_mutex_);
  if (!ios_surface_) {
    FML_DLOG(INFO) << "Could not CreateRenderingSurface, this PlatformViewIOS "
                      "has no ViewController.";
    return nullptr;
  }
  return ios_surface_->CreateGPUSurface();
}
```

callstack:
```
#4	0x0000000102d30cac in flutter::PlatformView::NotifyCreated() at /Users/aaclarke/dev/engine/src/flutter/shell/common/platform_view.cc:77
#5	0x0000000102b78cd9 in ::-[FlutterViewController surfaceUpdated:](BOOL) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:544
#6	0x0000000102b791a8 in ::-[FlutterViewController viewWillAppear:](BOOL) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:580
```

If you put a breakpoint on `PlatformViewIOS::SetOwnerViewController` you'll see this if you push twice, then hit back twice:
```
(lldb) p this
(flutter::PlatformViewIOS *) $4 = 0x00007fdd73d1ed50
(lldb) po owner_controller.ptr_
<FlutterViewController: 0x7fdd74850800>

(lldb) c
Process 40705 resuming
2020-03-12 09:50:07.218508-0700 Runner[40705:16759644] flutter: Observatory listening on http://127.0.0.1:60959/K4uqwl6Dp7Y=/
(lldb) p this
(flutter::PlatformViewIOS *) $6 = 0x00007fdd73d1ed50
(lldb) po owner_controller.ptr_
<FlutterViewController: 0x7fdd7486d600>

(lldb) c
Process 40705 resuming
(lldb) p this
(flutter::PlatformViewIOS *) $8 = 0x00007fdd73d1ed50
(lldb) po owner_controller.ptr_
<FlutterViewController: 0x7fdd7402e800>

(lldb) c
Process 40705 resuming
(lldb) p this
(flutter::PlatformViewIOS *) $10 = 0x00007fdd73d1ed50
(lldb) po owner_controller.ptr_
 nil
Assertion failed: (surface), function NotifyCreated, file ../../flutter/shell/common/platform_view.cc, line 77.
(lldb) p this
(flutter::PlatformViewIOS *) $12 = 0x00007fdd73d1ed50
```

So this means the FlutterViewController for the PlatformView is getting set to nil just before it is getting shown on screen and `viewWillAppear:` is getting called on the FlutterViewController (0x7fdd74850800).

**Comment by gaaclarke** [comment]
```diff
--- a/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
+++ b/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
@@ -570,6 +570,8 @@ static void sendFakeTouchEvent(FlutterEngine* engine,
 
 - (void)viewWillAppear:(BOOL)animated {
   TRACE_EVENT0("flutter", "viewWillAppear");
+  fml::WeakPtr<flutter::PlatformViewIOS> weakPlatformView = [_engine.get() platformView];
+  assert(weakPlatformView->GetOwnerViewController());
 
   // Send platform settings to Flutter, e.g., platform brightness.
   [self onUserSettingsChanged:nil];
```

The following assert will trip before the crash happens.  This seems to be a problem with presenting a FlutterViewController that has been previously covered up, like in the case of a UINavigationController stack pop.

**Comment by gaaclarke** [comment]
Ok, I've looked at the code that reproduces this more closely.  `testaccessibility` is sharing an engine between multiple live FlutterViewControllers.  I'd say this isn't a supported flow.  I'm not even sure it makes sense.  I can make it not crash, but I don't think this is a flow we really want to support.  We plan on releasing better guidance around multiple view controllers / engines.

The following change fixes the crash:
```
--- a/ios/Runner/AppDelegate.m
+++ b/ios/Runner/AppDelegate.m
@@ -54,7 +54,11 @@
     }else if([@"openPage" isEqualToString:call.method]){
 //        FlutterViewController *oldVC = (FlutterViewController *)self.flutterEngine.viewController;
 //        ((void(*)(id, SEL, BOOL))objc_msgSend)(oldVC, NSSelectorFromString(@"surfaceUpdated:"), NO);
-        FlutterViewController *vc = [[FlutterViewController alloc]initWithEngine:self.flutterEngine nibName:nil bundle:nil];
+        FlutterEngine* engine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil];
+        [engine runWithEntrypoint:nil];
+        [self.class registerWithRegistrar:[engine registrarForPlugin:@"testaccessibility"]];
+        [GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];
+        FlutterViewController *vc = [[FlutterViewController alloc]initWithEngine:engine nibName:nil bundle:nil];
         UINavigationController *nav = (id)self.window.rootViewController;
         [nav pushViewController:vc animated:YES];
     }else{
```

**Comment by gaaclarke** [comment]
For the record, here is the patch that can make this not crash (but it behaves in a weird way because of the shared engine still):
```
--- a/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
+++ b/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
@@ -570,6 +570,12 @@ static void sendFakeTouchEvent(FlutterEngine* engine,
 
 - (void)viewWillAppear:(BOOL)animated {
   TRACE_EVENT0("flutter", "viewWillAppear");
+  // If we are presenting a previously viewed FlutterViewController, setup the platform
+  // view again.
+  fml::WeakPtr<flutter::PlatformViewIOS> weakPlatformView = [_engine.get() platformView];
+  if (!weakPlatformView->GetOwnerViewController()) {
+    weakPlatformView->SetOwnerViewController([self getWeakPtr]);
+  }
 
   // Send platform settings to Flutter, e.g., platform brightness.
   [self onUserSettingsChanged:nil];
```

**Comment by xster** [comment]
@xujim @kangwang1988, was there a reason why flutter_boost needed to have multiple FlutterViewControllers attached to the same FlutterEngine at the same time rather than detaching the bottom one first before attaching the top one?  

Also, please add a flutter_boost test to our testing repository at https://github.com/flutter/tests which runs with each framework PR. This way, we'll make sure we don't break you guys via something in the engine like this (or even by naming another widget Action). 

See https://cs.opensource.google/flutter/engine/+/master:testing/scenario_app/ios/Scenarios/ScenariosTests for examples of driving tests from the platform side.

**Comment by xujim** [comment]
@gaaclarke @xster Thanks, currently, concerns on the memory consumption, flutter boost create only one engine and have multiple view controller attach it **in turn**。However, they are **NOT** attached to same engine at the same time. It is in turn, that is mean, we only attach the top VC to engine, and the previous VC(covered up) will be detached as soon as the new one is set as OwnerViewController to engine.
I think it is reasonable way, because, Flutter VC is just a kind of UI representation layer, and Engine is data layer managing the flutter data, we can use multiple representation layers for one data layer.
Furthermore, sharing engine for VCs can help them share data like message handling, etc

**Comment by foxsofter** [comment]
[fix_crash](https://github.com/foxsofter/testaccessibility/tree/fix_crash)

**Comment by xster** [comment]
@xujim what you're describing sounds reasonable to me. Does it work if you manually set the engine.viewController to nil or to the top vc before the bottom vc gets covered? Seems like that's what https://github.com/xujim/testaccessibility/compare/master...foxsofter:fix_crash?expand=1#diff-a6425004106bb459a3f91283fe144fd2 is doing right? 

This bug is essentially asking us to make `initWithEngine` more ergonomic by having the FlutterViewController remove the previous FlutterViewController from the engine automatically?

**Comment by xster** [comment]
Posterity: from chatting with @gaaclarke documentation and ergonomics around this may all end up bundled in the https://github.com/flutter/flutter/issues/37644 work as well.

**Comment by foxsofter** [comment]
I wrote an Add-to-app plugin [thrio](https://github.com/hellobike/thrio) that is probably the most complete solution currently.

**Comment by xujim** [comment]
@xster , thanks, fix_crash works for my example, but it needs to hook the UINavigationController, which is not so nice. I finally figured out a workaround, which is better for me——try not call surfaceUpdated:NO for my FlutterViewController. This way, we can make sure the flutter engine holding an ios_surface_ until it is reset by SetOwnerViewController as soon as another FlutterVC is attached to FlutterEngine.

**Comment by xujim** [comment]
The cons of my solution is that need to override the viewDidDisappear of FlutterViewController, which will lose the TRACE_EVENT0:
```objc
//in this way, we can call FlutterViewController's parent in FLBFlutterViewContainer
@interface FlutterViewController (bridgeToviewDidDisappear)
- (void)flushOngoingTouches;
- (void)override_viewDidDisappear:(BOOL)animated;
@end

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wincomplete-implementation"
@implementation FlutterViewController (bridgeToviewDidDisappear)
- (void)bridge_viewDidDisappear:(BOOL)animated{
//    TRACE_EVENT0("flutter", "viewDidDisappear");
    [self flushOngoingTouches];
    [super viewDidDisappear:animated];
}
@end

//my VC inherited from FlutterViewController
@implementation FLBFlutterViewContainer 
- (void)viewDidDisappear:(BOOL)animated
{
    [BoostMessageChannel didDisappearPageContainer:^(NSNumber *result) {}
                                                pageName:_name
                                                  params:_params
                                                uniqueId:self.uniqueIDString];

    if (FLUTTER_VC.beingPresented || self.beingDismissed /*|| ![self.uniqueIDString isEqualToString:[(FLBFlutterViewContainer*)FLUTTER_VC uniqueIDString]]*/)
    {
        [FLUTTER_APP resume];
        [(FLBFlutterViewContainer*)FLUTTER_VC surfaceUpdated:YES];
    }

    //call super's super implementation
    [self bridge_viewDidDisappear:animated];
}
@end 

```
