### ISSUE TITLE
Framework should send a 'FirstFrame' service protocol event

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#5245]
Framework should send a 'FirstFrame' service protocol event. 

If the application has been reassembled this should be sent when the first real frame is painted.
If the application has been spawned this should be sent when the first frame is painted.

@Hixie

**Comment by eseidelGoogle** [comment]
Currently we do some analysis of the trace when computing time-to-first-frame for benchmarks.  It's possible that code should use this event, depending on when this is sent.  FYI @yjbanov

**Comment by yjbanov** [comment]
We currently only post an event when we build the very first frame when the app starts. We should add this too.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L216 is where we send the event currently.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L240 is where that object gets told to reassemble.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/binding.dart#L165 is where we start the fake frame.

To fix this bug we need to reset _needToReportFirstFrame to true and then call preventThisFrameFromBeingReportedAsFirstFrame in the reassembleApplication function of WidgetsBinding.
