### ISSUE TITLE
Flutter widget showing empty page when using addContentView from android activity

### ISSUE THREAD

**Issue by bitfield66** [flutter/flutter#52463]
i am adding flutter to existing android app.

I have created new flutter module from android studio and included that module in my existing android app.

I’m using addContentView() to add flutter view to my activity.

After launching activity the screen shows blank. View is not showing up

Appreciate your help!!

**Comment by TahaTesser** [comment]
Hi @bitfield66 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by bitfield66** [comment]
Solved this changing my module name to "app"

**Comment by TahaTesser** [comment]
Hi @bitfield66 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you
