### ISSUE TITLE
flutter_test dependency problem

### ISSUE THREAD

**Issue by pvegh** [flutter/flutter#52465]
I'm getting an error after updating `test`:
```
Because every version of flutter_test from sdk depends on test_api 0.2.11 and test >=1.13.0 depends on test_api 0.2.15, flutter_test from sdk is incompatible with test >=1.13.0.
```

Relevant lines and changes:
```
-  test: ^1.5.3
+  test: ^1.14.2
```
and:
```
   flutter_test:
     sdk: flutter
```

**Comment by VladyslavBondarenko** [comment]
Related issues
https://github.com/flutter/flutter/issues/52458
https://github.com/flutter/flutter/issues/51582

**Comment by VladyslavBondarenko** [comment]
Fixed, https://github.com/flutter/flutter/blob/stable/packages/flutter_test/pubspec.yaml depends on test_api: 0.2.15
