### ISSUE TITLE
Flutter Doctor should indicate if `adb` not found while trying to discover devices

### ISSUE THREAD

**Issue by oodavid** [flutter/flutter#52464]
Running `flutter doctor -v` showed "No devices available" but "adb not in PATH" would have been a better error since that was the issue.

Adding `C:/..../platform-tools` to the environment path fixed the issue.

Thought it worth noting that flutter doctor could highlight PATH issues too.

**Comment by jmagman** [comment]
When the tool can't find the `adb` path I see:
```
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/magder/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
```
Are you suggesting there should be a better error message about making sure it's on your path?  I don't see why it would be necessary to highlight in the devices section, necessarily.  That output is shared with `flutter devices` and if `adb` isn't found it may just be that you aren't doing Android development and don't need it (so it shouldn't be an error per se).

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
