### ISSUE TITLE
[in_app_purchase] serverVerificationData for iOS/AppStore

### ISSUE THREAD

**Issue by michaldev** [flutter/flutter#52469]
Hi.
I've used official plugin for payments. I would like to implement auto-renewal subscriptions. In android implementation it is very easy. Problem is in iOS. serverVerificationData isn't a payment token (as in android payment). I must valid it before sending to server and I must decode it. Decoding by base64 return bytes. It is probably ASN1. I am trying to get to payment token from it by plugin asn1lib. My attemps are failed. 
How can I get payment token from iOS?

**Comment by rahulraj64** [comment]
I am also planning to do the same. According to [this](https://pub.dev/documentation/in_app_purchase/latest/in_app_purchase/PurchaseVerificationData/serverVerificationData.html) documentation, in iOS, this is a base64 encoded string. I can successfully be able to validate it by Apple's server-side Apis following  [this](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html) documentation. ("Send the Receipt Data to the App Store" section)

POST Request: https://sandbox.itunes.apple.com/verifyReceipt (testing)
JSON Body: {
	"receipt-data": "MIIXKwYJKoZIhvcN...............+WQv1g==",
	"password": "e8...........50fc"
}

You should get the validated response back. But I haven't checked to decode it locally.

**Comment by michaldev** [comment]
In my opinion, it works a bit differently.
The "Subscription Status URL" is set in the appstoreconnect panel. The appstore store sends a request to my server with a payment identifier, which I have to compare with that received from the application.
Unfortunately, I don't know how to get this ID from the "in_app_purchase" library. After decoding with base64 I get an incomprehensible string, which after interpretation ASN1 does not return anything meaningful.
