### ISSUE TITLE
microbenchmarks rrect_contains_iteration regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52473]
First occurs at https://github.com/flutter/flutter/pull/51495, but the big jump is at https://github.com/flutter/flutter/pull/52366.

![Screenshot 2020-03-12 at 07 49 03](https://user-images.githubusercontent.com/1435716/76533875-f97d3c80-6435-11ea-8ecd-ac7f1fd9d89a.png)

**Comment by gspencergoog** [comment]
To me, it looks like the initial jump is the engine roll at #52431.

My `Diagnosticable` change is within the noise for this test and it improves code size by 1.3% without triggering any other benchmarks. I'd like to keep it.

**Comment by kf6gpe** [comment]
I'd buy that. Adding the engine team, dropping the framework team.

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/2a8127dbfad894d511cd1ccd866697f3ff6469bd

@rmacnak-google

**Comment by rmacnak-google** [comment]
In the window of time the benchmark measures, I observe one scavenge before the change and one scavenge and the beginning of marking after the change. This is a minor change in when the GC happens. The heap size in this benchmark is much smaller (~2MB) than I've seen in any real Flutter application (6MB+), which is expected to move the GC sooner relative to a larger heap.
