### ISSUE TITLE
[Native] Splash Screen Blink When Screen Is Turned Back On After Turning Off 

### ISSUE THREAD

**Issue by YusufAbdelaziz** [flutter/flutter#52471]
## Steps to Reproduce

1. Run `flutter create bug

[bug.zip](https://github.com/flutter/flutter/files/4324609/bug.zip)

`.
2. Update the files as follows: ... 
3. ... 

1 - Run the app and you can see that there's a blue splash screen added natively.
2 - Turn off the screen of your device using the power button and turn it on again.
3 - You'll see a blue screen flashing due to the added splash screen in case your phone got no notch, or if you got a phone with a notch, you'll see that the notch is only flashing.

<details>
  <summary>Logs</summary>

[ +59 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +145 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +4 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[ +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +125 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[ +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[ +21 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +113 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ +1 ms] origin/stable
[ +1 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +136 ms] Exit code 0 from: git ls-remote --get-url origin
[ +3 ms] https://github.com/flutter/flutter.git
[ +218 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +112 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ +2 ms] stable
[ +277 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +65 ms] Exit code 0 from: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +1 ms] List of devices attached
73QDU16901001073 device product:FRD-L09 model:FRD_L09 device:HWFRD transport_id:14
[ +40 ms] C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell getprop
[ +163 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +16 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +451 ms] Generating C:\Users\yusse\Documents\Flutter\testing\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +96 ms] ro.hardware = hi3650
[ +2 ms] ro.build.characteristics = default
[ +159 ms] Launching lib\main.dart on FRD L09 in debug mode...
[ +25 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\build-tools\29.0.1\aapt dump xmltree C:\Users\yusse\Documents\Flutter\testing\build\app\outputs\apk\app.apk
AndroidManifest.xml
[ +80 ms] Exit code 0 from: C:\Users\yusse\AppData\Local\Android\sdk\build-tools\29.0.1\aapt dump xmltree C:\Users\yusse\Documents\Flutter\testing\build\app\outputs\apk\app.apk
AndroidManifest.xml
[ +11 ms] N: android=http://schemas.android.com/apk/res/android
E: manifest (line=2)
A: android:versionCode(0x0101021b)=(type 0x10)0x1
A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
A: package="com.example.testing" (Raw: "com.example.testing")
A: platformBuildVersionCode=(type 0x10)0x1c
A: platformBuildVersionName=(type 0x10)0x9
E: uses-sdk (line=7)
A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
E: uses-permission (line=14)
A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
E: application (line=22)
A: android:label(0x01010001)="testing" (Raw: "testing")
A: android:icon(0x01010002)=@0x7f080000
A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
E: activity (line=28)
A: android:theme(0x01010000)=@0x7f0a0000
A: android:name(0x01010003)="com.example.testing.MainActivity" (Raw: "com.example.testing.MainActivity")
A: android:launchMode(0x0101001d)=(type 0x10)0x1
A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
E: intent-filter (line=35)
E: action (line=36)
A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
E: category (line=38)
A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
E: meta-data (line=45)
A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
A: android:value(0x01010024)=(type 0x10)0x2
[ +22 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell -x logcat -v time -t 1
[ +134 ms] Exit code 0 from: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell -x logcat -v time -t 1
[ +2 ms] int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main
03-12 16:20:56.978 I/TrafficMonitor( 1206):
count:745,rx_sum:21,tx_sum:23,rxBytes:24291,during_ms:2002,rx_speed:12133.366633366635,tx_speed:640.3596403596405,rto:0.9130434782608695
[ +17 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +4 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 logcat -v time -T 03-12 16:20:56.978
[ +87 ms] Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe
[ +9 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +234 ms] Building APK
[ +78 ms] Running Gradle task 'assembleDebug'...
[ +7 ms] gradle.properties already sets `android.enableR8`
[ +14 ms] Using gradle from C:\Users\yusse\Documents\Flutter\testing\android\gradlew.bat.
[ +117 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +264 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +1 ms] openjdk version "1.8.0_212-release"
OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[ +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +186 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +1 ms] openjdk version "1.8.0_212-release"
OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[ +7 ms] executing: [C:\Users\yusse\Documents\Flutter\testing\android\] C:\Users\yusse\Documents\Flutter\testing\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\yusse\Documents\Flutter\testing\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+4510 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[ +4 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[ +1 ms] > Task :app:preBuild UP-TO-DATE
[ +3 ms] > Task :app:preDebugBuild UP-TO-DATE
[ +5 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +9 ms] > Task :app:checkDebugManifest UP-TO-DATE
[ +2 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[ +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +124 ms] > Task :app:cleanMergeDebugAssets
[ +6 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[ +2 ms] > Task :app:compileDebugShaders UP-TO-DATE
[ +2 ms] > Task :app:generateDebugAssets UP-TO-DATE
[ +3 ms] > Task :app:mergeDebugAssets
[ +549 ms] > Task :app:copyFlutterAssetsDebug
[ +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[ +98 ms] > Task :app:generateDebugResValues UP-TO-DATE
[ +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +3 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +96 ms] > Task :app:processDebugResources UP-TO-DATE
[ +4 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[ +2 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[ +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[ +115 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +30 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +8 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +30 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[ +99 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[ +4 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[ +5 ms] > Task :app:mergeDexDebug UP-TO-DATE
[ +5 ms] > Task :app:validateSigningDebug UP-TO-DATE
[ +2 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[ +94 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[ +2 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[ +2 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[ +1 ms] Compatible side by side NDK version was not found.
[ +2 ms] > Task :app:packageDebug UP-TO-DATE
[ +3 ms] > Task :app:assembleDebug UP-TO-DATE
[ +1 ms] BUILD SUCCESSFUL in 5s
[ +1 ms] 30 actionable tasks: 3 executed, 27 up-to-date
[ +533 ms] Running Gradle task 'assembleDebug'... (completed in 7.0s)
[ +135 ms] calculateSha: LocalDirectory: 'C:\Users\yusse\Documents\Flutter\testing\build\app\outputs\apk'/app.apk
[ +177 ms] calculateSha: reading file took 172us
[+1105 ms] calculateSha: computing sha took 1102us
[ +21 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[ +11 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\build-tools\29.0.1\aapt dump xmltree C:\Users\yusse\Documents\Flutter\testing\build\app\outputs\apk\app.apk
AndroidManifest.xml
[ +52 ms] Exit code 0 from: C:\Users\yusse\AppData\Local\Android\sdk\build-tools\29.0.1\aapt dump xmltree C:\Users\yusse\Documents\Flutter\testing\build\app\outputs\apk\app.apk
AndroidManifest.xml
[ +3 ms] N: android=http://schemas.android.com/apk/res/android
E: manifest (line=2)
A: android:versionCode(0x0101021b)=(type 0x10)0x1
A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
A: package="com.example.testing" (Raw: "com.example.testing")
A: platformBuildVersionCode=(type 0x10)0x1c
A: platformBuildVersionName=(type 0x10)0x9
E: uses-sdk (line=7)
A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
E: uses-permission (line=14)
A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
E: application (line=22)
A: android:label(0x01010001)="testing" (Raw: "testing")
A: android:icon(0x01010002)=@0x7f080000
A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
E: activity (line=28)
A: android:theme(0x01010000)=@0x7f0a0000
A: android:name(0x01010003)="com.example.testing.MainActivity" (Raw: "com.example.testing.MainActivity")
A: android:launchMode(0x0101001d)=(type 0x10)0x1
A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
E: intent-filter (line=35)
E: action (line=36)
A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
E: category (line=38)
A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
E: meta-data (line=45)
A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
A: android:value(0x01010024)=(type 0x10)0x2
[ +5 ms] Stopping app 'app.apk' on FRD L09.
[ +4 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell am force-stop com.example.testing
[ +680 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell pm list packages com.example.testing
[ +449 ms] package:com.example.testing
[ +7 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell cat /data/local/tmp/sky.com.example.testing.sha1
[ +75 ms] af248c507ff9fec3689d22837653504b9b37a98e
[ +2 ms] Latest build already installed.
[ +1 ms] FRD L09 startApp
[ +5 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.testing/com.example.testing.MainActivity
[ +437 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.testing/.MainActivity (has extras) }
[ +2 ms] Waiting for observatory port to be available...
[ +426 ms] Observatory URL on device: http://127.0.0.1:56005/Gpp3O9rU_D8=/
[ +9 ms] executing: C:\Users\yusse\AppData\Local\Android\sdk\platform-tools\adb.exe -s 73QDU16901001073 forward tcp:0 tcp:56005
[ +83 ms] 65349
[ +1 ms] Forwarded host port 65349 to device port 56005 for Observatory
[ +20 ms] Connecting to service protocol: http://127.0.0.1:65349/Gpp3O9rU_D8=/
[ +285 ms] Successfully connected to service protocol: http://127.0.0.1:65349/Gpp3O9rU_D8=/
[ +7 ms] Sending to VM service: getVM({})
[ +13 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Unknown, operatingSystem: android, targetCPU: arm64, version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on
"android_arm64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 4570, startTime: 1584022...
[ +13 ms] Sending to VM service: getIsolate({isolateId: isolates/253648401209019})
[ +7 ms] Sending to VM service: _flutter.listViews({})
[ +59 ms] Result: {type: Isolate, id: isolates/253648401209019, name: main, number: 253648401209019, _originNumber: 253648401209019, startTime: 1584022868581, _heaps: {new: {type:
HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: 0...
[ +28 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7bf0735d20, isolate: {type: @Isolate, fixedId: true, id: isolates/253648401209019, name:
main.dart$main-253648401209019, number: 253648401209019}}]}
[ +16 ms] DevFS: Creating new filesystem on the device (null)
[ +2 ms] Sending to VM service: _createDevFS({fsName: testing})
[ +38 ms] Result: {type: FileSystem, name: testing, uri: file:///data/user/0/com.example.testing/code_cache/testingNXAUAV/testing/}
[ +2 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.testing/code_cache/testingNXAUAV/testing/)
[ +4 ms] Updating assets
[ +231 ms] Syncing files to device FRD L09...
[ +5 ms] Scanning asset files
[ +7 ms] <- reset
[ +1 ms] Compiling dart to kernel with 0 updated files
[ +25 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\yusse\AppData\Local\Temp\flutter_tool.accdd287-646c-11ea-a128-7cb0c2f42a8f\app.dill --packages C:\Users\yusse\Documents\Flutter\testing\.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[ +17 ms] <- compile package:testing/main.dart

Analyzing testing...
No issues found! (ran in 50.7s)

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.719], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\yusse\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.5731
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • FRD L09 • 73QDU16901001073 • android-arm64 • Android 7.0 (API 24)

</details>

**Comment by TahaTesser** [comment]
Hi @YusufIslamAnwar 
Are you sure you provided right sample code?
i can't don't see nay splash screen

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by YusufIslamAnwar** [comment]
Hi @TahaTesser, thanks for your response and I apologize for being late.

 1- You can just create a dummy project from File --> New Flutter project, then choose the first choice.
 2- Add native screen using this [plugin ](https://pub.dev/packages/flutter_native_splash) or you can go to Android --> src --> main --> res, here you can add a color.xml file and define any color,
then go to res --> drawable --> launch_background.xml, then change this line 
`<item android:drawable="@android:color/white" />`
to 
`<item android:drawable="@color:name_of_color/>`

3- Run the app. After running the app, turn the screen off and turn it on while the app is running using the power button, you'll see there's a flashing screen with the color you have chosen.
--------------------------------------------------------------------------------------------------------------
The plugin and the previous way are doing the same thing. Here are the steps to use the plugin :

1 -  Go to pubc.yaml, add : 
`dev_dependencies:
  flutter_native_splash: ^0.1.9`

2 - Create flutter_native_splash.yaml file which is located in your root project folder where pubc.yaml exists.

3 - In this file add this : 
`flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"`

or you can declare any color you like.

4 - Run this command --> flutter pub pub run flutter_native_splash:create.

5- Run the app, then turn off the screen while the app is running and turn it on after that, you'll see a flashing screen.

**Comment by TahaTesser** [comment]
Hi @YusufIslamAnwar 

For issue related to the 3rd party plugin [flutter_native_splash](https://pub.dev/packages/flutter_native_splash#-readme-tab-) you may want to open an issue in the dedicated [github](https://github.com/henriquearthur/flutter_native_splash/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by YusufIslamAnwar** [comment]
Hi @TahaTesser 

This is not a third-party plugin issue, I said you can do it natively without any plugins as I first explained or use the plugin to make the same native steps you do manually, both of them will have the same issue.

**Comment by TahaTesser** [comment]
Hi @YusufIslamAnwar 
Issue does reproduce without using any plugin, my bad 
Please make sure not to mention 3rd party packages to avoid confusion between framework issues vs 3rd party issues
Thank you for contribution

**Comment by YusufIslamAnwar** [comment]
I apologize for the confusion, I hope someone might have a solution to this issue.

**Comment by leetomlee123** [comment]
why i am in empty project i can see black splash ,i am not setting any ,just empty project ,confusion it.
![image](https://user-images.githubusercontent.com/19498940/76818470-9d088b80-6840-11ea-9216-d500ad12dc51.png)

**Comment by TahaTesser** [comment]
I can reproduce the issue using Realme 6, with a punch hole notch when adding native screen

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/holo_purple" />

    <!-- You can insert your own image assets here -->
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </item>
</layer-list>

```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.108, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.108 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 995aa138cd (9 hours ago), 2020-12-08 09:18:02 +0530
    • Engine revision b0d31ae166
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by exaby73** [comment]
I can no longer reproduce this issue. Therefore, I will close it. Thank you
