### ISSUE TITLE
TextField keyboardType number still allows user to input text

### ISSUE THREAD

**Issue by psbankar** [flutter/flutter#52484]
Flutter doctor output
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13, on Microsoft Windows [Version 10.0.18363.719], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```

Flutter code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            keyboardType: TextInputType.number,
          ),
        ),
      ),
    );
  }
}
```

Expected result: Only number keyboard should be available
Actual result: User can toggle between alphabet keyboard and input letters as well

Keyboard used: Swiftkey Keyboard

**Comment by GaspardMerten** [comment]
Well, that's how Swiftkey works I suppose, you should add a listener to your TextEditingController to remove any none-numerical characters!

**Comment by iapicca** [comment]
Hi @psbankar 
I believe this [code](https://dartpad.dev/7a9cdf176b2e36cb19e12e558962f086) solves the issue you are describing;
closing the issue, 
if you disagree please write in the comment
and I will reopen it.
Thank you
