### ISSUE TITLE
WebGL context not destroyed on window resize leading to high memory usage [canvasKit] [web]

### ISSUE THREAD

**Issue by muhleder** [flutter/flutter#52485]
Running the sample app on Chrome under OSX with canvasKit, I'm seeing very large memory increases to the Google Chrome Helper (GPU) process. Viewing the process in OSX activity monitor. My screen size is 1920x1080 and my graphics card is an integrated Intel HD620.

Google Chrome Helper (GPU)  starts out at about 300Mb and goes up and down between 300-400Mb whilst interacting with the app by clicking the increment button.

However, if I resize the window, memory of this process jumps to over 1Gb immediately and remains around that level whilst interacting with the app.

Further cycles of window resizing and interacting increase the process memory usage by just under 1Gb on each cycle.

Memory usage seems to stabilize at around 3Gb if I have the app at half screen size, around 4-5Gb if I maximise the browser window, and can fall to around 2Gb if I make the browser window as narrow as possible (~400px)

Specific steps to reproduce.

```
flutter create example
cd example
flutter run -d chrome --release --dart-define FLUTTER_WEB_USE_SKIA=true
```
Then interact with the app and resize window as described above.

flutter doctor -v output

```
Marks-MacBook-Pro:example mark$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.15.21-pre.18, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.15.21-pre.18 at /opt/flutter
    • Framework revision 02769001d3 (41 minutes ago), 2020-03-12 10:53:23 -0700
    • Engine revision 2844d4480b
    • Dart version 2.8.0 (build 2.8.0-dev.13.0 17eec5bcde)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mark/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by muhleder** [comment]
When the window resizes a new Skia SkSurface is created in Surface._createOrUpdateSurfaces since the size differs. 

https://github.com/flutter/engine/blob/4196207ee70e1f35557441ba65fa11d14e3a47f0/lib/web_ui/lib/src/engine/compositor/surface.dart

The previous SkSurface has the dispose() method called, which runs _surface.callMethod('dispose'); on the actual canvasKit skSurface js object, but in canvasKit itself, this does not destroy the WebGl context.

The function in canvasKit which is called by _surface.callMethod('dispose') is here https://github.com/google/skia/blob/d7e0131c7edccfcc777f5d0defee4aa8b2d53ddf/modules/canvaskit/cpu.js#L71 and it claims to clean up the underlying memory, but since this is the cpu.js file I believe this is only for surfaces which are cpu backed rather than gpu backed.

The surfaces that the canvasKit implementation in flutter creates come from this line in gpu.js https://github.com/google/skia/blob/d7e0131c7edccfcc777f5d0defee4aa8b2d53ddf/modules/canvaskit/gpu.js#L40

The WebGL context is created and handled by Emscripten, and Skia/canvasKit only receives an integer handle for the WebGL context, never the context itself so it has no way of cleaning the context up.

The integer handle is stored in the dart SkSurface object in the flutter engine https://github.com/flutter/engine/blob/4196207ee70e1f35557441ba65fa11d14e3a47f0/lib/web_ui/lib/src/engine/compositor/surface.dart#L149

The Emscripten API does provide a method to destroy a WebGL context if given the integer handle and that is what we need to use to destroy the context when we're done with it.

API reference
https://emscripten.org/docs/api_reference/html5.h.html#c.emscripten_webgl_destroy_context

Actual js function
https://github.com/emscripten-core/emscripten/blob/630883b8ed64ecbce72ce21cc4cb2bb4f4c063bb/src/library_webgl.js#L901

**Comment by muhleder** [comment]
This commit adds an interface to canvasKit which will allow us to remove WebGL contexts from the engine. https://github.com/muhleder/skia/commit/46ec734a457f73ccee9ec5eef4b6336557bc80b2

**Comment by muhleder** [comment]
And this commit in the engine uses the new method to delete the WebGL context when the surface is disposed. https://github.com/muhleder/engine/commit/0612ab6485b03e5c17c7c4f4ab55dce7a918ef68

Note, I've also included a change to the canvasKitBaseUrl here so that I can use the custom build of canvasKit.

**Comment by muhleder** [comment]
Actually, whilst the above canvasKit changes work with a very simple app (a single empty Container), they do not seem to work when the app actually paints anything onto it's canvas.

It appears that canvasKit also needs this commit to destroy the WebGL context and free up the GPU memory. https://github.com/muhleder/skia/commit/a368ea077550d7b3c5607d616ff5fdfbd67eca0e

**Comment by muhleder** [comment]
Some relevant discussion on a similar issue with WebGL contexts here https://github.com/mrdoob/three.js/pull/17588

**Comment by CoreyDotCom** [comment]
@muhleder... we are running into similar/related issues with CanvasKit and Surface reconstruction on Safari...namely you can't just recreate a surface, Safari will fail to render to that canvas from then on out and quite quickly run out of memory.  See fiddle here - https://jsfiddle.skia.org/canvaskit/95ca2078e6b89830b47984a3f406724948a5f3e781b8b9444a8a00127e7f5770 ... when run in Safari it dies on 200th frame (when I invoke the surface recreation).  

Do you know if your fixes here would resolve this?

**Comment by muhleder** [comment]
@CoreyDotCom From a quick glance, I think so. At the moment canvasKit doesn't provide a way to dispose of WebGl contexts. So my two commits to skia/canvaskit here https://github.com/muhleder/skia/commits/master would be required to give canvasKit a way to dispose of them, and then in your code you would have to call that method when you recreate(?) the surface.

**Comment by muhleder** [comment]
@CoreyDotCom You can try deleting the contexts manually before you start compiling your own copy of canvasKit. 

https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context/loseContext

canvasKit uses webgl2 if it can but I think safari doesn't support that so `var gl = canvas.getContext('webgl');` should work to access the context from the canvas element.

**Comment by CoreyDotCom** [comment]
Thanks @muhleder but this did not seem to do the trick. Something else must be going on.

**Comment by yjbanov** [comment]
This is fixed now.
