### ISSUE TITLE
Scrolling in Shrine item pages is only 30pfs on a Nexus 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5249]
![flutter_06](https://cloud.githubusercontent.com/assets/11857803/17442973/14dc74a6-5aed-11e6-8634-bfec4743c4ce.png)

That screenshot is in a release build:

```
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision 4fe80830ca (8 minutes ago); engine revision 24511c9265
```

![screenshot from 2016-08-05 09 18 21](https://cloud.githubusercontent.com/assets/11857803/17443086/977b65fc-5aed-11e6-8c76-04c5cfc744a7.png)

[dart-timeline-2016-7-5.json.zip](https://github.com/flutter/flutter/files/404165/dart-timeline-2016-7-5.json.zip)

FYI @chinmaygarde

**Comment by eseidelGoogle** [comment]
Scrolls beautifully on my iPhone 6s.

**Comment by eseidelGoogle** [comment]
@HansMuller worked around this using https://github.com/flutter/flutter/commit/4a8dbb0e134218d29f5e5ce72fed1e785697d295

**Comment by chinmaygarde** [comment]
Should we close this ticket then?

**Comment by eseidelGoogle** [comment]
@chinmaygarde my understanding from chat with @abarth was you felt something was still wrong here?  I'm happy to close this and wait to see something like it come up again?

**Comment by HansMuller** [comment]
We had to add a shadow (changed the cards' elevation from 0 to 1) to the grid items to get the corresponding raster's cached. That shouldn't have been necessary; still needs to be fixed.

**Comment by cbracken** [comment]
This issue should now be resolved - if we see a future regression we should open a new issue.
