### ISSUE TITLE
Read Info From google basketball table

### ISSUE THREAD

**Issue by grajwan1906** [flutter/flutter#52509]
I want to read data from this table:
https://www.google.com/search?rlz=1C1SQJL_iwIL872IL872&sxsrf=ALeKk00iwYf9N7H-cnrIAOh69GUKhPK5gQ%3A1584054268512&ei=_L9qXu70HuyI1fAPwpe72Ac&q=liga+leumit+basketball&oq=liga+leumit+basketball&gs_l=psy-ab.3..0i203i70i253j0i203j0i22i30l3.814.3259..3410...0.2..0.192.1680.0j10......0....1..gws-wiz.......0i71j0.GEUV4xKm93Q&ved=0ahUKEwju4ur_hZboAhVsRBUIHcLLDnsQ4dUDCAs&uact=5#sie=lg;/g/11fn23g3k3;3;/m/05q65y5;st;fp;1;;

Or this table:
http://ibasketball.co.il/league/4039/standings

To my flutter application.
How can I do this?

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
