### ISSUE TITLE
FlatButton doesn't show button color unless OnPress is defined.

### ISSUE THREAD

**Issue by robertflesch** [flutter/flutter#52504]
When using a FlatButton, the button color does not register unless there is an OnPressed method defined. The first button displays correctly, but when the OnPressed definition is removed, the button color does not show up. (Edited for clarity)
```

import 'package:flutter/material.dart';

class TestPage extends StatelessWidget {
  TestPage();

  @override
  Widget build(BuildContext context) {
    var key = GlobalKey<ScaffoldState>();
    return Scaffold(
      key: key,
      body: Column(
          children: [
            FlatButton(
              color: Colors.red,
              textColor: Colors.white,
              onPressed: () {
                /*...*/
              },
              child: Text(
                'CREATE SOMETHING?',
                style: TextStyle(fontSize: 30),
              ),),
            FlatButton(
              color: Colors.red,
              textColor: Colors.white,
              child: Text(
                'CREATE SOMETHING?',
                style: TextStyle(fontSize: 30),
              ),),
          ])
    );
  }
}
```

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.719], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] Connected device (1 available)

Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by TahaTesser** [comment]
Hi @robertflesch 

When on `onPressed` isn't provided, button is disabled
If you want provide custom button color and text color for disabled button, check out the code sample below 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var key = GlobalKey<ScaffoldState>();
    return Scaffold(
        key: key,
        body: Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            FlatButton(
              color: Colors.red,
              textColor: Colors.white,
              onPressed: () {
                /*...*/
              },
              child: Text(
                'CREATE SOMETHING?',
                style: TextStyle(fontSize: 30),
              ),
            ),
            FlatButton(
              onPressed: null,
              color: Colors.red,
              textColor: Colors.white,
              disabledColor: Colors.red,
              disabledTextColor: Colors.white,
              child: Text(
                'CREATE SOMETHING?',
                style: TextStyle(fontSize: 30),
              ),
            ),
          ]),
        ));
  }
}

```


Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by robertflesch** [comment]
I noticed today that I get a warning in Dart Analysis
warning: The parameter 'onPressed' is required. . (missing_required_param at [purified] lib\temp\test_page.dart:23). Maybe that is how all errors of this type are reported. Just not obvious as I think it should be. 
Should be a compile error, rather that an analysis warning.
