### ISSUE TITLE
Remove old commit key check for refresh-github-commits

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#52503]
To solve https://github.com/flutter/flutter/issues/52443, we consider updating `commit` Key with both branch and SHA info.

To make existing logic continue work fluently, we consider checking both new Key and the old Key: avoiding inserting repeated commits in datastore. So the dashboard will remain clean.

This issue it to track to remove old Key check when app runs stable for a while.

**Comment by CaseyHillers** [comment]
Is there a plan to migrate the old keys to the new format? Otherwise were creating technical debt where we might no longer have access to them.

**Comment by keyonghan** [comment]
This shall not affect access to old data.
When accessing data, we query recent records order by time. Then iterate each of them and obtain their keys. With keys (no matter it is of old format or new format), we can track down to find their tasks.

For the sake of safety, it is good to migrate old ones to new format. Updated this issue to include that part.
