### ISSUE TITLE
Flickering issue on child updating when scrolling horizontal as well in vertical - Virtualization Concept

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [flutter/flutter#52517]
## Details
Hi Team, 
     I encountered a big issue**(Flickering)** and struggling to release a product because of this. I am developing a custom control with Virtualization concept in flutters like listview and so others. I have written the custom view from the reference https://flutter.dev/docs/resources/rendering.  

The flickering issue occurs when updating the child with a different "runtimetype". I have attached the small production sample on column re-using with virtualization please refer to the sample and attached videos. flickering didn't happen when updating the child with the same runtime type.

1.  Run the sample and scroll horizontally as much fast or as much slow, the scrolling get junk when updating the child with different runtimetype on that time view get flickering and also it will cause when updating the child with vertical scrolling too but in my sample, I have only provided with horizontal scrolling 

2.  I have attached the sample, please refer to it.

3.  I. have ensured in flutter channel master in profile mode, in that also am facing an issue 

4. In the main cause, 
Vertical Scrolling case: when scroll down is fine and we towards scroll up is junking
Horizontal scrolling case: when we scroll to right is working fine and we scroll towards left its junking
    
## Release Mode
Mi A1 cover video 
[20200312_214334.mp4.zip](https://github.com/flutter/flutter/files/4327682/20200312_214334.mp4.zip) 
Mac: 
[Release Mode.mov.zip](https://github.com/flutter/flutter/files/4327710/Release.Mode.mov.zip)

## Profile Mode
Is not good  but somewhat better 
Mi A1 cover video 
[20200312_214644.mp4.zip](https://github.com/flutter/flutter/files/4327720/20200312_214644.mp4.zip)
Mac CPU and GPU
[Profile Mode.zip](https://github.com/flutter/flutter/files/4327721/Profile.Mode.zip)

Sample Link: https://drive.google.com/open?id=1B28MkYxgSg9wRa9wc2T3B1rKLxlso8Lj 

**Target Platform:** Android , iOS , Web
**Target OS version/browser:** Safari, 
**Devices:**
Android:  Mi A1, Samsung S8 
iOS: iPhone 7
Browser: Safari, Chrome

## Flutter Doctor View

![Screen Shot 2020-03-12 at 10 45 27 PM](https://user-images.githubusercontent.com/45868997/76585575-b63dcf00-6504-11ea-9dad-acfa0808980f.png)

**Comment by BalasubramaniSundaram** [comment]
Hi Team, 
    Any update on this? 

Regards, 
Balasubramani Sundaram.

**Comment by kf6gpe** [comment]
Calling @HansMuller 's attention to this in case someone on the framework team has time to look at it.

**Comment by BalasubramaniSundaram** [comment]
Hi Team,
Any update on this?

Regards,
Balasubramani Sundaram.

**Comment by goderbauer** [comment]
Hey @BalasubramaniSundaram, it would help us in debugging this if you would post a very minimal and runnable code example that showcases the issue.

**Comment by BalasubramaniSundaram** [comment]
Hi @goderbauer,  
    I have almost provided a simple sample, from my production but I will try to provide the minimal and runnable code.
The provided sample is not runnable state I have double ensured and provided the sample.

**Comment by kf6gpe** [comment]
@BalasubramaniSundaram Were you ever able to get a running minimal reproducible case? Thanks for your work!

**Comment by BalasubramaniSundaram** [comment]
Hi @kf6gpe, 
    I will provide the sample within couple of days.

**Comment by kf6gpe** [comment]
@BalasubramaniSundaram I'm going to close this as there's no word from you as to whether or not you got a minimal reproducible case. Please feel free to re-open if you do. Thanks for your contributions to the community!
