### ISSUE TITLE
Make the number of overlay UIViews configurable.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#52510]
Unobstructed platform views can create up to 2 UIViews, however it might be desired to configure this value from a plugin.

See https://github.com/flutter/engine/pull/17049 for context.

**Comment by cyanglaz** [comment]
The android implementation only allows 1 overlay per PlatformView. I think iOS should just match the android behavior and only allowing 1 overlay. I don't think there is any benefit having more than 1 overlay, and it reduces the performance.

**Comment by jonahwilliams** [comment]
We're not going to make it configurable, instead it will be limited to 1
