### ISSUE TITLE
Call onPageChanged after first page shown in PageView

### ISSUE THREAD

**Issue by petermichaux** [flutter/flutter#52520]
I have a `PageView` inside a `Scaffold`. I want to adjust `persistentFooterButtons` depending on which page is showing. This would be seamless if `onPageChanged` is called after the first page is shown. As it stands, it is not fun to deal with all the nuances of the problem. For example, if my initial page integer is out of range, the page controller will automatically adjust. I cannot leverage that nice feature so have to handle the out of range stuff myself. That's just one example issue.

I agree with #19249 which is closed. Especially the example at the end about analytics.

**Comment by Piinks** [comment]
Hi @petermichaux can you provide some sample code? Do you not know the index of the first page that is going to be shown?
