### ISSUE TITLE
Broken link on TextTheme docs

### ISSUE THREAD

**Issue by erdemyerebasmaz** [flutter/flutter#52529]
https://github.com/flutter/flutter/blob/0b8abb4724aa590dd0f429683339b1e045a1594d/packages/flutter/lib/src/material/text_theme.dart#L21
The ')' character is interpreted as part of the link, which routes you to https://material.io/design/typography%29 which returns 404 - Page Not Found error.

_Although I'm not sure on what is your syntax is for links._ 
Suggestion:
`(<https://material.io/design/typography/>)`

**Comment by TahaTesser** [comment]
Hi @erdemyerebasmaz 

Clicking on the link with ctrl  launches the page correctly

![image](https://user-images.githubusercontent.com/48603081/76604786-60cde600-6535-11ea-801e-8c64892d67db.png)

![image](https://user-images.githubusercontent.com/48603081/76604821-6e836b80-6535-11ea-98a5-e13fd9dd9425.png)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it Thank you
