### ISSUE TITLE
i was working on hero animation then iam. not able to fix the following error

### ISSUE THREAD

**Issue by Rakshith202** [flutter/flutter#52525]
<
import 'package:companyproject/bottomNavigationBar.dart';
import 'package:flutter/cupertino.dart';
import 'dart:async';
import 'details.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height:MediaQuery.of(context).size.height-185.0,
        decoration: BoxDecoration(
          color: Colors.white,
        ),
        child: ListView(
          primary:false,
          padding: EdgeInsets.only(left: 25.0,right: 20.0),
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(top:45.0),
              child: Container(
                height:MediaQuery.of(context).size.height-300.0,
                child: ListView(
                  children: <Widget>[
                    _buildFoodItem('assets/img1.jpg', "place1", "amount1"),
                    SizedBox(height: 20),
                    _buildFoodItem('assets/img2.jpg', "place2", "amount2"),
                    SizedBox(height: 20),
                    _buildFoodItem('assets/img3.jpg', "place3", "amount3")
                  ],
                ),
              ),
            )
          ],
              
        ),
      ),
    );
  }

  Widget _buildFoodItem(String imgPath,String foodName,String price)
  {
    return Padding(
      padding: EdgeInsets.only(left: 10.0,right: 10.0,top: 10.0),
      child: InkWell(
        onTap: (){
          Navigator.of(context).push(MaterialPageRoute(
            builder: (context) =>DetailsPage(heroTag: imgPath)
          ));
        },
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            Container(
              child: Row(
                children: <Widget>[
                  Hero(
                    tag: imgPath,
                      child:Image(
                        image:AssetImage(imgPath),
                        fit:BoxFit.cover,
                        height: 75.0,
                        width: 75.0,
                      ),
                  ),
                  SizedBox(width: 20.0),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        foodName,
                        style: TextStyle(
                          fontSize: 17.0,
                          fontWeight:FontWeight.bold
                        ),
                      ),
                      Text(
                        price,
                        style:TextStyle(
                          fontSize: 15.0,
                          color: Colors.grey
                        )
                      )
                    ],
                  )
                ],
              ),
            ),
            IconButton(
              icon: Icon(Icons.arrow_right),
              color: Colors.black,
              onPressed: (){

              },
            )
          ],
        ),
      ),
    );
  }
}
>

<
import 'package:companyproject/bottomNavigationBar.dart';
import 'package:companyproject/ragistrationform.dart';
import 'package:flutter/material.dart';
import 'package:companyproject/Content.dart';
import 'package:companyproject/loginpage.dart';
void main() => runApp(MaterialApp(
  title: 'Flutter login demo',
  theme: ThemeData(
    primarySwatch: Colors.blue,
  ),
  home: HomePage(),

));
>
<
import 'package:flutter/material.dart';
import 'package:companyproject/Content.dart';
class DetailsPage extends StatefulWidget {
  final heroTag;
  final foodName;
  final foodPrice;

  DetailsPage({this.heroTag,this.foodName,this.foodPrice});
  @override
  _DetailsPageState createState() => _DetailsPageState();
}

class _DetailsPageState extends State<DetailsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body:ListView(
        children: <Widget>[
          Stack(
            children: <Widget>[
              Container(
                height:MediaQuery.of(context).size.height-82.0,
                width:MediaQuery.of(context).size.width,
                color: Colors.transparent,
              ),
              Positioned(
                top:75.0,
                child:Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(45.0),
                      topRight: Radius.circular(45.0),

                    ),
                        color:Colors.white,
                  ) ,
                  height:MediaQuery.of(context).size.height,
                  width:MediaQuery.of(context).size.width,
                )
              ),
              Positioned(
                top:30.0,
                left:(MediaQuery.of(context).size.width/2)-100,
                child: Hero(
                  tag:widget.heroTag,
                  child:Container(
                    decoration: BoxDecoration(
                      image:DecorationImage(
                        image:AssetImage(widget.heroTag),
                        fit:BoxFit.cover
                      )
                    ),
                    height: 200.0,
                    width: 200.0,
                  )
                ),
              ),

              Positioned(
                top:30.0,
                left:(MediaQuery.of(context).size.width/2)-100,
                child: Hero(
                    tag:widget.foodPrice,
                    child:Text(
                      widget.foodPrice
                    ),
                ),
              ),

            ],
          ),

        ],
      )
    );
  }
}
>

<
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,891ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building DetailsPage(dirty, dependencies: [MediaQuery], state: _DetailsPageState#5d9fc):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
>

**Comment by TahaTesser** [comment]
Hi @Rakshith202 

You forgot to provide `foodName` and `price` for Details Page here

```
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => Details(
                  heroTag: imgPath, foodName: foodName, foodPrice: price)));
```

### Working Code Sample

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      title: 'Flutter login demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    ));

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: MediaQuery.of(context).size.height - 185.0,
        decoration: BoxDecoration(
          color: Colors.white,
        ),
        child: ListView(
          primary: false,
          padding: EdgeInsets.only(left: 25.0, right: 20.0),
          children: [
            Padding(
              padding: EdgeInsets.only(top: 45.0),
              child: Container(
                height: MediaQuery.of(context).size.height - 300.0,
                child: ListView(
                  children: [
                    _buildFoodItem(
                        'https://i.imgur.com/C5xknx8.png', "place1", "amount1"),
                    SizedBox(height: 20),
                    _buildFoodItem(
                        'https://i.imgur.com/TCaPwCy.jpg', "place2", "amount2"),
                    SizedBox(height: 20),
                    _buildFoodItem(
                        'https://i.imgur.com/u441e75.png', "place3", "amount3")
                  ],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildFoodItem(String imgPath, String foodName, String price) {
    return Padding(
      padding: EdgeInsets.only(left: 10.0, right: 10.0, top: 10.0),
      child: InkWell(
        onTap: () {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => Details(
                  heroTag: imgPath, foodName: foodName, foodPrice: price)));
        },
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(
              child: Row(
                children: [
                  Hero(
                    tag: imgPath,
                    child: Image(
                      image: NetworkImage(imgPath),
                      fit: BoxFit.cover,
                      height: 75.0,
                      width: 75.0,
                    ),
                  ),
                  SizedBox(width: 20.0),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        foodName,
                        style: TextStyle(
                            fontSize: 17.0, fontWeight: FontWeight.bold),
                      ),
                      Text(price,
                          style: TextStyle(fontSize: 15.0, color: Colors.grey))
                    ],
                  )
                ],
              ),
            ),
            IconButton(
              icon: Icon(Icons.arrow_right),
              color: Colors.black,
              onPressed: () {},
            )
          ],
        ),
      ),
    );
  }
}

class Details extends StatefulWidget {
  final heroTag;
  final foodName;
  final foodPrice;

  const Details({Key key, this.heroTag, this.foodName, this.foodPrice})
      : super(key: key);

  @override
  _DetailsState createState() => _DetailsState();
}

class _DetailsState extends State<Details> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView(
      children: [
        Stack(
          children: [
            Container(
              height: MediaQuery.of(context).size.height - 82.0,
              width: MediaQuery.of(context).size.width,
              color: Colors.transparent,
            ),
            Positioned(
                top: 75.0,
                child: Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(45.0),
                      topRight: Radius.circular(45.0),
                    ),
                    color: Colors.white,
                  ),
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                )),
            Positioned(
              top: 30.0,
              left: (MediaQuery.of(context).size.width / 2) - 100,
              child: Hero(
                  tag: widget.heroTag,
                  child: Container(
                    decoration: BoxDecoration(
                        image: DecorationImage(
                            image: NetworkImage(widget.heroTag),
                            fit: BoxFit.cover)),
                    height: 200.0,
                    width: 200.0,
                  )),
            ),
            Positioned(
              top: 30.0,
              left: (MediaQuery.of(context).size.width / 2) - 100,
              child: Hero(
                tag: widget.foodPrice,
                child: Text(widget.foodPrice),
              ),
            ),
          ],
        ),
      ],
    ));
  }
}

```

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by Rakshith202** [comment]
Thank you
