### ISSUE TITLE
How to call intent method from java using flutter

### ISSUE THREAD

**Issue by neelayak** [flutter/flutter#52531]
So I am trying to make my app auto-start I know how I can do it in java but I don't know how to do it using flutter as I know we have to go native as we may have to do it for both android and ios I tried on the similar way how we get the battery detail app in flutter but in my app, I have to call an intent which is not working [how to make app autostart](https://stackoverflow.com/questions/49473230/android-how-to-enable-autostart-option-programmatically-in-xiaomi-devices/56335831#56335831) any guidance will be helpful.

https://stackoverflow.com/questions/60648026/how-to-call-intent-method-from-java-using-flutter

**Comment by TahaTesser** [comment]
Hi @neelayak 
Does this answer your question? [android_intent](https://pub.dev/packages/android_intent)
Thank you

**Comment by neelayak** [comment]
No as in the flutter we can do the basic stuff related to intent whereas here i have to use 
`String manufacturer = android.os.Build.MANUFACTURER;
try {
      Intent intent = new Intent();
      if ("xiaomi".equalsIgnoreCase(manufacturer)) {
                intent.setComponent(new ComponentName("com.miui.securitycenter", "com.miui.permcenter.autostart.AutoStartManagementActivity"));
      } else if ("oppo".equalsIgnoreCase(manufacturer)) {
                intent.setComponent(new ComponentName("com.coloros.safecenter", "com.coloros.safecenter.permission.startup.StartupAppListActivity"));
      } else if ("vivo".equalsIgnoreCase(manufacturer)) {
                intent.setComponent(new ComponentName("com.vivo.permissionmanager", "com.vivo.permissionmanager.activity.BgStartUpManagerActivity"));
      } else if ("Letv".equalsIgnoreCase(manufacturer)) {
                intent.setComponent(new ComponentName("com.letv.android.letvsafe", "com.letv.android.letvsafe.AutobootManageActivity"));
      } else if ("Honor".equalsIgnoreCase(manufacturer)) {
                intent.setComponent(new ComponentName("com.huawei.systemmanager", "com.huawei.systemmanager.optimize.process.ProtectActivity"));
      }

      List<ResolveInfo> list = getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
      if (list.size() > 0) {
                startActivity(intent);
      }

} catch (Exception e) {
      e.printStackTrace();
}` like this

**Comment by TahaTesser** [comment]
Hi @neelayak 
You can call your code using [platform-channels](https://flutter.dev/docs/development/platform-integration/platform-channels)

**Comment by neelayak** [comment]
I tried the following battery app and tried to call the following intent but i was not even able to call the gallery intent actully

**Comment by sanjeevbaria** [comment]
@neelayak have you found any solution??

**Comment by neelayak** [comment]
Ya I found a tutorial in which I have to use method channel

**Comment by sanjeevbaria** [comment]
@neelayak please share with me

**Comment by sanjeevbaria** [comment]
please share auto start code my project is stuck beacuse of this.

**Comment by stuartmorgan** [comment]
Closing as `android_intent` is deprecated in favor of [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).
