### ISSUE TITLE
Try using double.p everywhere

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5253]

**Comment by Hixie** [comment]
I poked at this today.

Here are some observations:

* I'm pretty sure we have a bug in our text layout algorithm (on the C++ side) that's actually the root cause of many of the unexpected line wrapping problems we've been seeing. Specifically, laying out a paragraph at its intrinsic width does not result in the same layout as led to that intrinsic width. https://github.com/flutter/flutter/issues/5852

* We would need a `.p` equivalent of `ceil`, for those cases where you want to clamp the value to the right bit range but make sure that the new value is not smaller than the incoming value. This is critical in text layout, where we get back a very precise width, and if we ever lay out with a smaller width we'll have line wrapping.

* We would definitely need analyzer support to know where we should be calling `.p`. It's simply impractical to do this by hand. I think at a minimum we would need a new type that the analyzer treats as separate from "double" (even if they're synonyms in the compiler), so that it can tell us when we are about to use a double for layout, or when we are multiplying or dividing values that use this type, and thus need to call `.p`. I'm not sure even that would necessarily be enough though.

* Other than the text issue above which may be a red herring, we don't actually have any current known issues that are affected by this. (The other main issue we had recently got refactored out of existence, and I'm not aware of any other issues currently.)

**Comment by sethladd** [comment]
cc @floitschG

**Comment by sethladd** [comment]
Sounds like we did this. Thanks @Hixie !

**Comment by eseidelGoogle** [comment]
@Hixie based on this feedback, I've communicated to @a-siva that we're OK with the VM removing double.p. Please scream if that's not the case.

**Comment by Hixie** [comment]
SGTM, until we fix #5852 we can't really evaluate what we need. `double.p` was very useful in making me discover that bug, so, there's that at least. :-)
