### ISSUE TITLE
[web]: Debug compilation error

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#52541]
I run the debug configuration and get the error:

AssetNotFoundException: project|main_web_entrypoint.ddc.js
Failed to build application for the web

All works fine and than it happens occasionally.
Flutter version 1.13.6, Google Chrome 80.0.3987.132

**Comment by TahaTesser** [comment]
Hi @bambinoua 
can you please provide your `flutter doctor -v` and `flutter build web --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by bambinoua** [comment]
The problem was happend when I run **debug mode**. The result building web is ok.
P.S. It is stange but the problem has been fixed some how. Sorry for inconvinience.
