### ISSUE TITLE
image_picker is dependent on rootViewController

### ISSUE THREAD

**Issue by Jorgezz** [flutter/flutter#52546]
In image_picker flutter plugin, registerWithRegistrar method init FLTImagePickerPlugin instance with a 
rootViewController, but some projects maybe not initialize app's rootViewController, I suggest the plugin 
use `[UIApplication sharedApplication].delegate.window.rootViewController` directly, then the issue can be avoid.

```
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
  FlutterMethodChannel *channel =
      [FlutterMethodChannel methodChannelWithName:@"plugins.flutter.io/image_picker"
                                  binaryMessenger:[registrar messenger]];
  UIViewController *viewController =
      [UIApplication sharedApplication].delegate.window.rootViewController;
  FLTImagePickerPlugin *instance =
      [[FLTImagePickerPlugin alloc] initWithViewController:viewController];
  [registrar addMethodCallDelegate:instance channel:channel];
}

- (void)showCamera {
  [[UIApplication sharedApplication].delegate.window.rootViewController presentViewController:_imagePickerController animated:YES completion:nil];
}

- (void)showPhotoLibrary {
  // No need to check if SourceType is available. It always is.
  _imagePickerController.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
  [[UIApplication sharedApplication].delegate.window.rootViewController presentViewController:_imagePickerController animated:YES completion:nil];
}

```

**Comment by Jorgezz** [comment]
thanks for your attention to this issue. It' s really appreciated for new version improve the issue.

**Comment by darshankawar** [comment]
@Jorgezz 
With the `image_picker` plugin gone through many changes (bug fixes, new features) since you logged this issue, can you confirm if your issue is still valid or has been resolved ?

https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
