### ISSUE TITLE
Allow setting prefix in shared preference - for migrating from old app that did not use flutter

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [flutter/flutter#52544]
## Use case

I have an app (based on Xamarin, but I that's not importing) that I am migrating to flutter.

The App uses share preferences (NSUserDefaults (on iOS) and SharedPreferences (on Android)) to store some user configuration data.

It would be very nice, if these settings are not lost when migrating to flutter.

But they are (at least in my tests), and I think that is because flutter uses the 'flutter.' prefix for any preferences one stores.
 
## Proposal

Add an option to the shared preference plugin to change the ".flutter" prefix to something else (or even make it empty).

This could be simply done by making the `_prefix` memeber non-const and adding a static function to change it.

**Comment by moldstadt** [comment]
I would also be interested in a feature like this. Possibly just expose functionality to read from named shared preference files on Android, without adding any ".flutter" prefix, as discussed here: https://github.com/flutter/plugins/pull/2040#discussion_r351904092

**Comment by meshwara** [comment]
Any update or release of this feature ? I'm facing same problem that my new app (created using flutter) cannot read old native data

**Comment by zed-0xff** [comment]
+1 here

**Comment by TheoLassonder** [comment]
+1

**Comment by IshankDev** [comment]
Hey checkout this package may be this will help into migration from old app - 
https://pub.dev/packages/native_shared_preferences

**Comment by Ashutosh-Kumar-coder** [comment]
i  am switching a app to Flutter from android java. in java i use sharedPreferences and store the username and pasword is two different key. Now i want, when user get next flutter update on playstore then he does not relogin the app. And new app get fetch data from old preference and login automatically.

**Comment by flutter-clutter** [comment]
All of the provided solutions here don't cover the following issues:
- When you have spread the relevant shared preferences in your native Android app across multiple resource files. Because in the native_shared_preference plugin, you can only set one (by specifying the string resource flutter_shared_pref_name).
- Does not work for iOS at all

I have raised this topic on SO: https://stackoverflow.com/questions/62148055/read-shared-preferences-in-flutter-app-that-were-previously-stored-in-a-native-a but no satisfying answer so far.

**Comment by ponderMuse** [comment]
Our Flutter app (developed for mobile and web) is using `shared_preferences` package to store user preferences. When testing the app on web we are seeing that the user preferences are being stored in the browser's Local Storage area where each key is being prepended with `flutter.` as described in this issue thread.

I can see there is a roadmap currently in place to update `shared_preferences` API to allow apps to specify a prefix other than `flutter.` when storing local preferences and that these updates have now been implemented and even passed first triage? 

Are there any time estimates as to when this update to the API is likely to be available in pub.dev? We are in particular interested in removing the `flutter.` prefix in browser local storage keys purely from an aesthetic point of view as we need to document the use of these keys in our site's **Cookie Policy** page and we are looking to avoid having to document these local storage keys with `flutter.` prefixed on them as this would just add unnecessary confusion to those "special cases" reading through the details in our Cookie Policy page.

Cheers,
PM

**Comment by stuartmorgan** [comment]
> and that these updates have now been implemented

I'm not sure where you are seeing that; none of what I described above has been implemented.

> Are there any time estimates as to when this update to the API is likely to be available in pub.dev?

We use a continuous release system for our plugins, so it would be available on pub.dev as soon is the work was completed, reviewed, and landed. Anyone interested in causing that to happen on a specific timeframe is encouraged to submit PRs following the plan described above.

**Comment by ponderMuse** [comment]
@stuartmorgan Ah, ok. Thanks for quick reply. I assumed "passed first triage" being another way of saying "passed first trial or test" or something along those lines. English is not my first language so... my bad.

**Comment by TheManuz** [comment]
Important addition: to migrate from native **NSUserDefaults** (on iOS), another parameter needed is the [`suiteName`](https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename).

I cannot migrate old iOS values because this feature is missing.

**Comment by stuartmorgan** [comment]
@TheManuz Please file a new issue; that's a different feature that would need a different implementation.
