### ISSUE TITLE
When extracting Widget, give option to put it inside new file

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#52545]
## Use case

When extracting a Widget inside the Flutter Outliner, it currently just puts it inside the same file. This takes away some time when you have to create a new file, cut and paste the code into it and import the proper packages. 

## Proposal

It would be nice to save time to offer a checkbox wether or not a new file should be created, and if it is marked, just handle this automatically.

**Comment by jmagman** [comment]
@DanTup Should this move to Dart-Code or is this something else? https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/flutter/flutter_outline_view.ts

**Comment by DanTup** [comment]
The Extract Widget refactor is [implemented in the analyzer](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/refactoring/extract_widget.dart) so https://github.com/dart-lang/sdk is the right place for this (it may need some work in the VS Code extension later, but it can't be fully implemented there without support in the analyzer).

**Comment by jlubeck** [comment]
Should I recreated it there? Or is there a way to move issues around? (sorry, I don't maintain any repo's myself, so I don't know if those tools exists)

**Comment by DanTup** [comment]
GitHub does have a way to move them, but I think it only works within the same organisation (there is also the move bot, but the issues it creates have it as the author of all the comments so it's not perfect). So manually opening it and copy/pasting the contents may be easiest.

**Comment by jlubeck** [comment]
Alright, will do that. Thanks!
