### ISSUE TITLE
Dart HTTP PUT VS POST in REST requests: The PUT verb does not work

### ISSUE THREAD

**Issue by michelemazzei** [flutter/flutter#52551]
I'm writing a client REST in Flutter/Dart that should manage some data from a REST Server (Java server). The client works fine if compiled for Android , no problem at all. But when it is compiled for Chrome ( Javascript ) there are many problems, like this: when I try to make an HTTP PUT request the client seems to take an unknown error without sending the request to the server.

The strange thing is that this problem is only on the verb PUT, the verb POST works fine (but I stil not tried with PATCH/ DELETE). So it seems a bug on the internal http library when used the verb PUT instead of POST. http: 0.10.0

Here the code:

```
 void _sendRequest() async {
       try {
          print('Send Request : ');
          //   String url = "http://10.0.2.2:8080/v2/account";
          String url = "http://localhost:8080/v2/account";
          Map<String, String> headers = new HashMap();
          headers['Accept'] = 'application/json';
          headers['Content-type'] = 'application/json';

          Http.Response response = await Http.put(url,
              headers: headers,
              body: jsonEncode({
              "description": "string",
              "id": 25,
              "name": "11112",
              "password": "seesfs"
           }),
           encoding: Encoding.getByName('utf-8'));

          print('Response status: ${response.statusCode}');
          print('Response body: ${response.body}');
       }catch(error) {
         print("${error?.toString()}");
       }
      }
```
As you can see, I use the localhost address when I use the web client, and 10.0.2.2 when I use the android VM. The same code works when compiled with android and does not when javascript. Any idea? Do you have encountered the same problem?

Here follows the sample test project:

```
name: accounts_client_http description: A new Flutter project.

version: 1.0.0+1

environment: sdk: ">=2.1.0 <3.0.0"

dependencies: http:^0.12.0+4 flutter: sdk: flutter

dev_dependencies: flutter_test: sdk: flutter

flutter: uses-material-design: true
```

Here follows the flutter doctor

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale it_IT.UTF-8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.43.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jonahwilliams** [comment]
You cannot send requests to a localhost+port from the web, that violates web security policies. Instead just use `/v2/account`

**Comment by michelemazzei** [comment]
Hi, the server and the client have not the same origin.
The server is a java based server, thus I think "v2/account/ would  not work.
In any case it is not a security issue.
The server can accept CORS.

Anyway, the error message is :
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:46443/5MG8ohHyem4=
Send Request :
XMLHttpRequest error.

while the android version is ok.
I have no other info about the error.
It seems that the server does not exist, but it is not true.

**Comment by jonahwilliams** [comment]
You'll need to look in the chrome console/network tab for more information then

**Comment by michelemazzei** [comment]
Thank you @jonahwilliams  ! 
it hadn't occurred to me!
The problem is now solved!
In fact the problem was : 
```
Send Request : 
2browser_client.dart:87 PUT http://localhost:8080/v2/account 403
send @ browser_client.dart:87
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:140
handleValueCallback @ future_impl.dart:682
_propagateToListeners @ future_impl.dart:711
[_completeWithValue] @ future_impl.dart:526
(anonymous) @ future_impl.dart:556
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ schedule_microtask.dart:139
[_tryToResolveArena] @ arena.dart:231
[_resolve] @ arena.dart:215
resolve @ arena.dart:52
resolve @ recognizer.dart:255
resolve @ long_press.dart:352
handlePrimaryPointer @ long_press.dart:274
handleEvent @ recognizer.dart:470
[_dispatch] @ pointer_router.dart:76
(anonymous) @ pointer_router.dart:117
forEach @ linked_hash_map.dart:23
[_dispatchEventToRoutes] @ pointer_router.dart:115
route @ pointer_router.dart:101
handleEvent @ binding.dart:218
dispatchEvent @ binding.dart:198
[_handlePointerEvent] @ binding.dart:156
[_flushPointerEventQueue] @ binding.dart:102
[_handlePointerDataPacket] @ binding.dart:86
[_onPointerData] @ pointer_binding.dart:129
(anonymous) @ pointer_binding.dart:465
(anonymous) @ pointer_binding.dart:430
(anonymous) @ pointer_binding.dart:195
:36429/#/:1 Access to XMLHttpRequest at 'http://localhost:8080/v2/account' from origin 'http://[::1]:36429' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
js_primitives.dart:32 XMLHttpRequest error.

```
So, the problem was, again, the CORS mapping!
The problem is solved in this way: in the server side I added the method allowed:

```
    @Configuration
    public class WebConfig implements WebMvcConfigurer {

        @Override
        public void addCorsMappings(CorsRegistry registry) {
            registry.addMapping("/**").allowedMethods("PUT", "GET", "POST", "PATCH");
        }
    }

```

Finally, this issue is related to:
[cors-issue-occures-only-when-put](https://stackoverflow.com/questions/40835531/cors-issue-occurs-only-when-put)

The problem is that the Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
as described here:

[cors-issue-occurs-only-when-put](https://stackoverflow.com/questions/40835531/cors-issue-occurs-only-when-put)

Thank you!
