### ISSUE TITLE
how to get Uint8List or File  from ImageProvider

### ISSUE THREAD

**Issue by yemenpoint** [flutter/flutter#52566]
I want to get ImageProvider as File 
Can i get Help

Image img = Image.asset("assets/usa.png");
    ImageProvider imageProvider = img.image;

    Uint8List list = imageProvider .....
    File file = imageProvider .....

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
