### ISSUE TITLE
Can't run demos on iOS devices off-the-shelf and no guidance on how to fix it

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5256]
$ git clone https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Counting objects: 57650, done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 57650 (delta 52), reused 0 (delta 0), pack-reused 57516
Receiving objects: 100% (57650/57650), 20.08 MiB | 4.29 MiB/s, done.
Resolving deltas: 100% (40760/40760), done.
Checking connectivity... done.
$ flutter doctor
Downloading Dart SDK 1.19.0-dev.0.0...
###### ################################################################## 100.0%

Building flutter tool...
Downloading Material fonts...                        0.5s
Downloading package sky_engine...                    0.2s
Downloading package sky_services...                  0.1s
Downloading engine artifacts android-arm...          4.3s
Downloading engine artifacts android-arm-profile...  3.2s
Downloading engine artifacts android-arm-release...  2.7s
Downloading engine artifacts android-x64...          2.3s
Downloading engine artifacts android-x86...          2.2s
Downloading engine artifacts ios...                  1.9s
Downloading engine artifacts ios-profile...          1.8s
Downloading engine artifacts ios-release...          1.7s
Downloading darwin-x64 tools...                      2.0s
Downloading android-arm-profile/darwin-x64 tools...  1.0s
Downloading android-arm-release/darwin-x64 tools...  0.4s

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and basic    ║
  ║ crash reports to Google in order to help Google contribute improvements to ║
  ║ Flutter over time. See Google's privacy policy:                            ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics reporting.        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/ianh/dev/flutter
    • Framework revision ea7d5bf291 (13 minutes ago), engine revision 24511c9265

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/ianh/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.1
    • dartlang plugin version 0.6.8

$ cd flutter/examples/flutter_gallery
$ flutter run
Running 'pub get' in flutter_gallery...              16.5s
Running lib/main.dart on iPod touch...
2016-08-05 11:09:29.037 ios-deploy[7279:41527] [ !! ] Error 0xe8008015: ·ÃW}ˇˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install ios/build/Release-iphoneos/Runner.app on bad2cf647626bc00d1864fb5202d98910167229a.
Error running application on iPod touch.
$

```
```

**Comment by eseidelGoogle** [comment]
There are lots of issues around provisioning which we don't handle well in our iOS tooling yet, I suspect you're hitting one of them.  The workaround is to open up `ios/Runner.xcodeproj` in XCode and hit run and let it walk you through fixing things.  We're going to need to have someone look at this holistically, including bringing parity between our available iOS and Android `flutter` commands. :/

**Comment by Hixie** [comment]
At a minimum we should catch the error and point to a troubleshooting page on apple.com or just say to run "ios/Runner.xcodeproj" and try to get that to work first.

**Comment by xster** [comment]
Is this another permutation of #7879?

**Comment by eseidelGoogle** [comment]
Yes, I think so.
