### ISSUE TITLE
Camera plugin on iOS is not thread-safe and susceptible to data races and crashes.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#52578]
The camera plugin dispatches all method call handling to [a dispatch queue](https://github.com/flutter/plugins/blob/ad6fd0d0408bfd3a2f0d422f77015c789cb6bd95/packages/camera/ios/Classes/CameraPlugin.m#L797). However, one the operations that may happen on the dispatch queue is [to register a camera texture with the engine](https://github.com/flutter/plugins/blob/ad6fd0d0408bfd3a2f0d422f77015c789cb6bd95/packages/camera/ios/Classes/CameraPlugin.m#L847). This operation is only safe on the platform thread (the UIKit main thread). Data races arising from this may cause instability in the engine as it manages its internal texture registry or crashes if a registration is in progress when the engine is shutting down.

**Comment by jslattery26** [comment]
![errorerror](https://user-images.githubusercontent.com/44002583/110983787-34ab9780-8338-11eb-8ab8-5635fb049064.png)

Having a crash here which I believe is related. Waiting for a fix

**Comment by stuartmorgan** [comment]
Aren't all of the replies (calls to `result`) from that queue also unsafe?

**Comment by stuartmorgan** [comment]
> Aren't all of the replies (calls to `result`) from that queue also unsafe?

Confirmed on chat, the answer is yes. The whole plugin implementation is incorrect.

**Comment by hellohuanlin** [comment]
Update: we wrote up [a formal proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#) to improve the thread model for iOS camera plugin. This proposal includes the engine API issue discussed here, as well as other threading related issues.

**Comment by hellohuanlin** [comment]
This is resolved by [this PR](https://github.com/flutter/plugins/pull/4661)
I created [this issue](https://github.com/flutter/flutter/issues/96429) to track all threading related issues.
