### ISSUE TITLE
Textfield labels are misaligned on Android R/11

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#52581]
In Flutter Gallery running on preview Android R, the textfields with labels such as `$` are misaligned with the rest of the text that is typed.

**Comment by xster** [comment]
@GaryQian can you assign a milestone for this?

**Comment by Hixie** [comment]
(clearing assignment since this has been in the overdue milestone for a month)

**Comment by GaryQian** [comment]
This seems to be resolved on release versions of R.
