### ISSUE TITLE
Firebase isEmailVerified boolean issue!

### ISSUE THREAD

**Issue by blaze021** [flutter/flutter#52597]
I'm building an application for login in which I'm using Wrapper class to distinguish logged in user and not signed up user.

App works fine when I dont use the isEmailVerified boolean value but when I use it always routes me the sign up page

Here is my sign_in code:

import 'package:cy_rush/Animation/FadeAnimation.dart';
import 'package:cy_rush/screens/authenticate/register.dart';
import 'package:cy_rush/screens/home/home.dart';
import 'package:cy_rush/services/auth.dart';
import 'package:cy_rush/shared/constants.dart';
import 'package:cy_rush/shared/loading.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class SignIn extends StatefulWidget {
  final Function toggleView;

  SignIn({this.toggleView});

  @override
  _SignInState createState() => _SignInState();
}

class _SignInState extends State<SignIn> {
  final AuthService _auth = AuthService();
  final _formKey = GlobalKey<FormState>();
  String error = '';
  bool loading = false;

  // text field state
  String email = '';
  String password = '';

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.of(context).size.width;
    final height = MediaQuery.of(context).size.height;
    return loading
        ? Loading()
        : Scaffold(
      resizeToAvoidBottomInset:
      false, // to avoid ugly overflow of typing area.
      backgroundColor: Colors.white,
      body: Builder(builder :(context) {
        return SingleChildScrollView(
          child: SafeArea(
            top: false,
            bottom: true,
            left: true,
            right: true,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Container(
                  height: 250,
                  child: Stack(
                    children: <Widget>[
                      Positioned(
                        top: -40,
                        height: 250,
                        width: width,
                        child: FadeAnimation(
                            1,
                            Container(
                              decoration: BoxDecoration(
                                  image: DecorationImage(
                                      image:
                                      AssetImage('assets/background.png'),
                                      fit: BoxFit.fill)),
                            )),
                      ),
                      Positioned(
                        top: -20,
                        right: -10,
                        height: 248,
                        width: width + 20,
                        child: FadeAnimation(
                            1.3,
                            Container(
                              decoration: BoxDecoration(
                                  image: DecorationImage(
                                      image: AssetImage(
                                          'assets/background_log.png'),
                                      fit: BoxFit.fill)),
                            )),
                      )
                    ],
                  ),
                ),
                Padding(
                  padding: EdgeInsets.symmetric(horizontal: 40),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      FadeAnimation(
                          1.5,
                          Text(
                            "Login",
                            style: TextStyle(
                                color: Color.fromRGBO(49, 39, 79, 1),
                                fontWeight: FontWeight.bold,
                                fontSize: 30),
                          )),
                      SizedBox(
                        height: 15,
                      ),
                      FadeAnimation(
                          1.7,
                          Container(
                            decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(10),
                                color: Colors.white,
                                boxShadow: [
                                  BoxShadow(
                                    color: Color.fromRGBO(196, 135, 198, .3),
                                    blurRadius: 20,
                                    offset: Offset(0, 10),
                                  )
                                ]),
                            child: Column(
                              children: <Widget>[
                                Container(
                                  padding: EdgeInsets.all(10),
                                  decoration: BoxDecoration(
                                      border: Border(
                                          bottom: BorderSide(
                                              color: Colors.grey[200]))),
                                  child: Form(
                                    key: _formKey,
                                    child: TextFormField(
                                      decoration:
                                      textInputDecoration.copyWith(
                                          hintText: 'email',
                                          labelText: 'Email',
                                          labelStyle:
                                          TextStyle(fontSize: 20)),
                                      validator: (val) => val.isEmpty
                                          ? 'Enter an email'
                                          : null,
                                      onChanged: (val) {
                                        setState(() => email = val);
                                      },
                                    ),
                                  ),
                                ),
                                Container(
                                  padding: EdgeInsets.all(10),
                                  child: Form(
                                    child: TextFormField(
                                      obscureText: true,
                                      decoration:
                                      textInputDecoration.copyWith(
                                          hintText: 'password',
                                          labelText: 'Password'),
                                      validator: (val) => val.length < 6
                                          ? 'Enter a password 6+ chars long'
                                          : null,
                                      onChanged: (val) {
                                        setState(() => password = val);
                                      },
                                    ),
                                  ),
                                )
                              ],
                            ),
                          )),
                      SizedBox(
                        height: 20,
                      ),
                      FadeAnimation(
                          1.7,
                          Center(
                              child: Text(
                                "Forgot Password?",
                                style: TextStyle(
                                    color: Color.fromRGBO(196, 135, 198, 1)),
                              ))),
                      SizedBox(
                        height: 30,
                      ),
                      FadeAnimation(
                          1.9,
                          Container(
                            height: 50,
                            child: Center(
                              child: RaisedButton(
                                  padding: EdgeInsets.symmetric(
                                      horizontal: 70, vertical: 15),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(50),
                                  ),
                                  color: Colors.pink[400],
                                  child: Text(
                                    'Sign In',
                                    style: TextStyle(color: Colors.white),
                                  ),
                                  onPressed: () async {
                                    if(_formKey.currentState.validate()){
                                      setState(() => loading = true);
                                      dynamic result = await _auth.signInWithEmailAndPassword(email, password);
                                      if(result == null) {
                                        setState(() {
                                          loading = false;
                                          error = 'Could not sign in with those credentials';
                                        });
                                      }
                                      else{
                                       setState(() {
                                         loading = false;
                                       });
                                       Navigator.pushReplacement(context,
                                           MaterialPageRoute(
                                               builder: (context) => Home()));
                                      }
                                    }
                                    /*

                                    else {
                                      //const snackBar = SnackBar(
                                      //                                            content: Text('Verify your email first'));
                                      // Find the Scaffold in the widget tree and use it to show a SnackBar.
                                      SnackBar mySnackBar = SnackBar(
                                        content:
                                        Text('Verify your email first'),
                                      );
                                      Scaffold.of(context).showSnackBar(mySnackBar);
                                    }
                                     */
                                  }),
                            ),
                          )),
                      SizedBox(
                        height: 30,
                      ),
                      FadeAnimation(
                          2,
                          Center(
                              child: GestureDetector(
                                  onTap: () async {
                                    Navigator.pushReplacement(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                Register()));
                                  },
                                  child: Text(
                                    "Create Account",
                                    style: TextStyle(
                                        color:
                                        Color.fromRGBO(49, 39, 79, .6)),
                                  )))),
                    ],
                  ),
                )
              ],
            ),
          ),
        );
      }),
    );
  }
}

Here is the my wrapper class:

import 'package:cy_rush/models/user.dart';
import 'package:cy_rush/screens/authenticate/authenticate.dart';
import 'package:cy_rush/screens/home/home.dart';
import 'package:cy_rush/shared/loading.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class Wrapper extends StatelessWidget {
var result;
bool flag = false  ;
  @override
  Widget build(BuildContext context) {
    final user = Provider.of<User>(context);

    checkIsVerified();
    bool check = flag;
    if (user != null && check ) {
      return Home();
    } else {
      return Authenticate();
    }
  }
  checkIsVerified() async{
    final _firebaseAuth = FirebaseAuth.instance;
    FirebaseUser firebaseUser = await _firebaseAuth.currentUser();
    await firebaseUser.reload();
    firebaseUser = await _firebaseAuth.currentUser();
    flag = firebaseUser.isEmailVerified;
  }
}

I'm a genuine noob at flutter so please help me out

**Comment by blaze021** [comment]
Also this is my auth_file:



import 'package:cy_rush/models/user.dart';

import 'package:cy_rush/services/database.dart';
import 'package:firebase_auth/firebase_auth.dart';


class AuthService {

  final FirebaseAuth _auth = FirebaseAuth.instance;

  // create user obj based on firebase user
  User _userFromFirebaseUser(FirebaseUser user) {
    return user != null ? User(uid: user.uid) : null;
  }

  // auth change user stream
  Stream<User> get user {
    return _auth.onAuthStateChanged
    //.map((FirebaseUser user) => _userFromFirebaseUser(user));
        .map(_userFromFirebaseUser);
  }

  // sign in anon
  Future signInAnon() async {
    try {
      AuthResult result = await _auth.signInAnonymously();
      FirebaseUser user = result.user;
      return _userFromFirebaseUser(user);
    } catch (e) {
      print(e.toString());
      return null;
    }
  }

  // sign in with email and password
  Future signInWithEmailAndPassword(String email, String password) async {
    try {
      AuthResult result = await _auth.signInWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      return user;
    } catch (error) {
      print(error.toString());
      return null;
    }
  }

  // register with email and password
  Future registerWithEmailAndPassword(String email, String password) async {
    try {
      AuthResult result = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      // create a new document for the user with the uid
      await DatabaseService(uid: user.uid).updateUserData('0','new crew member', 100);
      return _userFromFirebaseUser(user);
    } catch (error) {
      print(error.toString());
      return null;
    }
  }

  // sign out
  Future signOut() async {
    try {
      return await _auth.signOut();
    } catch (error) {
      print(error.toString());
      return null;
    }
  }

}

**Comment by blaze021** [comment]
## And this is the main.dart in which i have used the StreamProvider:

import 'package:cy_rush/screens/wrapper.dart';
import 'package:cy_rush/services/auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:cy_rush/models/user.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return StreamProvider<User>.value(
      value: AuthService().user,
      child: MaterialApp(
        home: Wrapper(),
      ),
    );
  }
}

**Comment by cmkweber** [comment]
Be sure to call [sendEmailVerification](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseUser/sendEmailVerification.html) after registering so the user can verify by email.

Additionally, you may way to always signOut before signing into another account so previous values are reset properly - I have filed a bug for this [here](https://github.com/FirebaseExtended/flutterfire/issues/288).

**Comment by blaze021** [comment]
> Be sure to call [sendEmailVerification](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseUser/sendEmailVerification.html) after registering so the user can verify by email.

I did in my register file but its still not giving me the current value of isEmailVerified.

####Here is the register file:

import 'package:cy_rush/Animation/FadeAnimation.dart';
import 'package:cy_rush/screens/authenticate/sign_in.dart';
import 'package:cy_rush/services/auth.dart';
import 'package:cy_rush/shared/constants.dart';
import 'package:cy_rush/shared/loading.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class Register extends StatefulWidget {
  final Function toggleView;

  Register({this.toggleView});

  @override
  _RegisterState createState() => _RegisterState();
}

class _RegisterState extends State<Register> {
  final AuthService _auth = AuthService();
  final _formKey = GlobalKey<FormState>();
  String error = '';
  bool loading = false;

  // text field state
  String email = '';
  String password = '';

  @override
  Widget build(BuildContext context) {
    return loading
        ? Loading()
        : Scaffold(
            backgroundColor: Colors.white,
            body: SingleChildScrollView(
              child: Container(
                child: Column(
                  children: <Widget>[
                    Container(
                      height: 300,
                      decoration: BoxDecoration(
                          image: DecorationImage(
                              image: AssetImage('assets/reg_back_new.png'),
                              fit: BoxFit.fill)),
                      child: Stack(
                        children: <Widget>[
                          Positioned(
                            left: 30,
                            width: 80,
                            height: 200,
                            child: FadeAnimation(
                                1,
                                Container(
                                  decoration: BoxDecoration(
                                      image: DecorationImage(
                                          image: AssetImage(
                                              'assets/light-1.png'))),
                                )),
                          ),
                          Positioned(
                            left: 140,
                            width: 80,
                            height: 160,
                            child: FadeAnimation(
                                1.3,
                                Container(
                                  decoration: BoxDecoration(
                                      image: DecorationImage(
                                          image: AssetImage(
                                              'assets/light-2.png'))),
                                )),
                          ),
                          Positioned(
                            child: FadeAnimation(
                                1.6,
                                Container(
                                  margin: EdgeInsets.only(top: 200),
                                  child: Center(
                                    child: Text(
                                      "Sign Up",
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 60,
                                        fontFamily: 'Pijamas',
                                      ),
                                    ),
                                  ),
                                )),
                          )
                        ],
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.symmetric(horizontal: 30),
                      child: Column(
                        children: <Widget>[
                          FadeAnimation(
                              1.8,
                              Container(
                                padding: EdgeInsets.all(5),
                                decoration: BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: BorderRadius.circular(10),
                                    boxShadow: [
                                      BoxShadow(
                                          color:
                                              Color.fromRGBO(143, 148, 251, .2),
                                          blurRadius: 20.0,
                                          offset: Offset(0, 10))
                                    ]),
                                child: Column(
                                  children: <Widget>[
                                    Container(
                                      padding: EdgeInsets.all(10),
                                      decoration: BoxDecoration(
                                          border: Border(
                                              bottom: BorderSide(
                                                  color: Colors.grey[200]))),
                                      child: Form(
                                        key: _formKey,
                                        child: TextFormField(
                                          decoration:
                                              textInputDecoration.copyWith(
                                                  hintText: 'email',
                                                  labelText: 'Email',
                                                  labelStyle:
                                                      TextStyle(fontSize: 20)),
                                          validator: (val) => val.isEmpty
                                              ? 'Enter an email'
                                              : null,
                                          onChanged: (val) {
                                            setState(() => email = val);
                                          },
                                        ),
                                      ),
                                    ),
                                    Container(
                                      padding: EdgeInsets.all(10),
                                      child: Form(
                                        child: TextFormField(
                                          obscureText: true,
                                          decoration:
                                              textInputDecoration.copyWith(
                                                  hintText: 'password',
                                                  labelText: 'Password'),
                                          validator: (val) => val.length < 6
                                              ? 'Enter a password 6+ chars long'
                                              : null,
                                          onChanged: (val) {
                                            setState(() => password = val);
                                          },
                                        ),
                                      ),
                                    )
                                  ],
                                ),
                              )),
                          SizedBox(
                            height: 20,
                          ),

                          SizedBox(
                            height: 35,
                          ),
                          FadeAnimation(
                              1.9,
                              Container(
                                height: 50,
                                child: Center(
                                  child: RaisedButton(
                                      padding: EdgeInsets.symmetric(
                                          horizontal: 70, vertical: 15),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(50),
                                      ),
                                      color: Colors.pink[400],
                                      child: Text(
                                        'Sign Up',
                                        style: TextStyle(color: Colors.white),
                                      ),
                                      onPressed: () async {
                                        if (_formKey.currentState.validate()) {
                                          setState(() => loading = true);
                                          dynamic result = await _auth
                                              .registerWithEmailAndPassword(
                                                  email, password);
                                          FirebaseUser user = await FirebaseAuth
                                              .instance
                                              .currentUser();
                                          user.sendEmailVerification();
                                          Navigator.pushReplacement(
                                              context,
                                              MaterialPageRoute(
                                                  builder: (context) =>
                                                      SignIn()));
                                          if (result == null) {
                                            setState(() {
                                              loading = false;
                                              error =
                                                  'Please supply a valid email';
                                            });
                                          }
                                        }
                                      }),
                                ),
                              )),
                          SizedBox(
                            height: 35,
                          ),
                          FadeAnimation(
                            1.5,
                            GestureDetector(
                              onTap: () async {
                                Navigator.pushReplacement(
                                    context,
                                    MaterialPageRoute(
                                        builder: (context) =>
                                            SignIn()));
                              },
                              child: Text("Already Signed Up?",
                                  style: TextStyle(
                                    fontFamily: 'Pijamas',
                                    fontSize: 30,
                                    color: Colors.black,
                                  )),
                            ),
                          ),
                        ],
                      ),
                    )
                  ],
                ),
              ),
            ));
  }
}

**Comment by blaze021** [comment]
The future returned by the async task of isEmailVerified is not converted to boolean, so that I can use that value to determinine where to open home() or Authenticate() widgets in the wrapper widget.

**Comment by VladyslavBondarenko** [comment]
Hi @blaze021 
please open the issue in the [FlutterFire github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
