### ISSUE TITLE
BottomNavigationBar elevation not works.

### ISSUE THREAD

**Issue by bahaedini** [flutter/flutter#52591]
version: 1.12.13+hotfix.8 \

It does not work on my project.

Also, I test it with The sample App in Flutter API.

here:
https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html
not works!
So, I add  `elevation: 5.0,` and not works again.

```
      bottomNavigationBar: BottomNavigationBar(
        elevation: 5.0,
        items: const <BottomNavigationBarItem>[
```

**Comment by anirudh-jwala** [comment]
It's working fine and as expected on my app

**Comment by iapicca** [comment]
Hi @bahaedini 
does this [code](https://dartpad.dev/45c79d8dd149b0eeb37a62791da4474f represent the issue you are describing?
Thank you

**Comment by bahaedini** [comment]
Thanks for the answers.
But Not works. I test it on a real device and the android emulator (Nexus 5x API 23 ).

But I found a solution. I change my code to this:

```
bottomNavigationBar: Container(
          decoration: BoxDecoration(
            boxShadow: [
              BoxShadow(
                color: Colors.black45,
                 blurRadius:5.0
              ),
            ],
          ),
          child: new BottomNavigationBar(
```

hope help someone else.

**Comment by iapicca** [comment]
Hi @bahaedini
I'm glad that you fixed the issue,
thank you for letting me know
