### ISSUE TITLE
Flutter not building after upgrading to 1.12.13+hotfix.8

### ISSUE THREAD

**Issue by viandmarket25** [flutter/flutter#52596]
After upgrading my project to version 1.12.13, running "flutter clean",updating Androidx, I cant get to build my project anymore
Output:

BUILD FAILED in 16m 5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       997.1s (!)
Gradle task assembleDebug failed with exit code 1

--verbose result:
PS C:\Users\potential\AndroidStudioProjects\yoapp> flutter run --verbose
[  +61 ms] executing: [C:\Users\potential\Android\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +309 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\Users\potential\Android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +268 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +27 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +17 ms] executing: [C:\Users\potential\Android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +277 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Users\potential\Android\flutter\] git ls-remote --get-url origin
[ +205 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +648 ms] executing: [C:\Users\potential\Android\flutter\] git rev-parse --abbrev-ref HEAD
[ +478 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +890 ms] executing: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +98 ms] Exit code 0 from: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           0123456789ABCDEF       device product:full_pri6735_66c_m0 model:4G device:pri6735_66c_m0 transport_id:3
[  +36 ms] C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell getprop
[ +401 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +52 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +108 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1643 ms] Generating
C:\Users\potential\AndroidStudioProjects\yoapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +341 ms] ro.hardware = mt6735
[   +1 ms] ro.build.characteristics = default
[ +318 ms] Launching lib\main.dart on 4G in debug mode...
[  +44 ms] executing: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell -x logcat -v
time -t 1
[ +148 ms] Exit code 0 from: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell -x logcat-v time -t 1
[   +7 ms] --------- beginning of main
           03-14 15:49:55.536 I/libPerfService( 1018): perfGetLastBoostPid 1659
[  +16 ms] executing: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +13 ms] executing: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF logcat -v time -T
03-14 15:49:55.536
[ +228 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +17 ms] executing: C:\Users\potential\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +276 ms] Building APK
[  +83 ms] Running Gradle task 'assembleDebug'...
[  +76 ms] gradle.properties already sets `android.enableR8`
[  +38 ms] Using gradle from C:\Users\potential\AndroidStudioProjects\yoapp\android\gradlew.bat.
[  +92 ms] executing: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[+1528 ms] Exit code 0 from: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
           OpenJDK 64-Bit Server VM (build 25.152-b06, mixed mode)
[  +10 ms] executing: [C:\Users\potential\AndroidStudioProjects\yoapp\android\]
C:\Users\potential\AndroidStudioProjects\yoapp\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\potential\AndroidStudioProjects\yoapp\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+2145 ms] Welcome to Gradle 5.6.2!
[   +3 ms] Here are the highlights of this release:
[  +11 ms]  - Incremental Groovy compilation
[   +2 ms]  - Groovy compile avoidance
[  +39 ms]  - Test fixtures for Java projects
[ +191 ms]  - Manage plugin versions via settings script
[  +53 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html

**Comment by jonahwilliams** [comment]
Are these the full logs? It is just sort of ends - we can't tell what the error is.

**Comment by JoeCodeswell** [comment]
VS code **New flutter project** Fails to build.
I am using vscode with Flutter 3.8.1 extension
I did:
1. Ctrl+Shift+P   Flutter: New Project 
  - Project name: jpods_fl
  - Project location: C:\1d\FlutterDartPjs\jpods_flPj
RESULT 
``` text
VSCODE NOTICE 
Your Flutter project is ready! Connect a device and press F5 to start running.

OUTPUT TAB
Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in .\lib\main.dart. SM

exit code 0
```

2. I connected my device and ran the NEW project. 
RESULT "Exception: Gradle task assembleDebug failed with exit code 1"
Here is the terminal listing
``` cmd
C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl> flutter run
No supported devices connected.

C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl> rem hooked up SM-T320 in normal way

C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl> rem result:  VSCODE  status bar SM T320 (android-arm)

C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl> flutter run
Launching lib\main.dart on SM T320 in debug mode...
Running Gradle task 'assembleDebug'...                                  

Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* What went wrong:
Running Gradle task 'assembleDebug'...
Execution failed for task ':app:compileFlutterBuildDebug'.      
Running Gradle task 'assembleDebug'...
> A problem occurred starting process 'command 'C:\flutter\bin\flutter.bat''
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Try:
Running Gradle task 'assembleDebug'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
BUILD FAILED in 5m 2s
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                       305.0s (!)
Exception: Gradle task assembleDebug failed with exit code 1

C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl>flutter --version
Flutter 1.15.22-pre.24 • channel @u • unknown source
Framework • revision aba0e2dc8f (16 hours ago) • 2020-03-13 23:21:03 -0400
Engine • revision e48761e5bb
Tools • Dart 2.8.0 (build 2.8.0-dev.14.0 c3a0bb086a)

C:\1d\FlutterDartPjs\jpods_flPj\jpods_fl>
```

Please let me know if I can give you any more info.
Thanks.
Love and peace,
Joe Dorocak aka Joe Codeswell

**Comment by JoeCodeswell** [comment]
Hi folks. Please tell me why [my comment](https://github.com/flutter/flutter/issues/52596#issuecomment-599127815) was marked as spam?
Thanks.
Love and peace,
Joe Dorocak aka Joe Codeswell

**Comment by Raddah** [comment]
Sam issue presented on mac os: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020,
    locale en-SA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
[✓] VS Code (version 1.43.0)
[✓] Connected device (3 available)

• No issues found!
