### ISSUE TITLE
why the need for android studio?

### ISSUE THREAD

**Issue by aster94** [flutter/flutter#52603]
If someone wish to use VSCode which is the need to bring in the installation the whole Android Studio?

Can the necessary tools (android toolchain, emulator [others??]) be installed in a indipendent way?

**Comment by jonahwilliams** [comment]
Android studio makes it fairly easy to download the necessary android tooling. You could also try manually downloading the sdk and command line tools : https://stackoverflow.com/questions/37505709/how-do-i-download-the-android-sdk-without-downloading-android-studio

**Comment by aster94** [comment]
@jonahwilliams could you tell us which are the tools needed?

- android SDK (commandlinetools)
- java 

any other? maybe the emulator?

**Comment by jonahwilliams** [comment]
flutter doctor will complain if you don't have all of the right dependencies

See: https://flutter.dev/docs/get-started/install/macos#install-android-studio

- Android SDK
- Android SDK Command-line Tools
- Android SDK Build-Tools
- Android SDK Platform Tools

**Comment by aster94** [comment]
seems like that some of them are not downloadable as stand alone, that's a pity
