### ISSUE TITLE
[web]: Http Request has no body

### ISSUE THREAD

**Issue by herrytco** [flutter/flutter#52604]
I am trying to send a http request using the http plugin on version ^0.12.0+4 (the latest one). 

```
http.Response response = await http.post(
    http://localhost:8085,
    body: jsonEncode({"test": "test"}),
    headers: {
      "accept": "application/json",
      "content-type": "application/json"
    },
);
```

I have a SpringBoot backend running which stated, that the request body is empty. Debug attempts with Postman worked fine.

EDIT: i tried the Dio package as well with the same result.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
