### ISSUE TITLE
"Failed host lookup" error

### ISSUE THREAD

**Issue by mohisham** [flutter/flutter#52608]
I have a flutter application that connects to a server that I host on AWS.  

Most of the time the app works fine with no issues.  Once in a while, however, the app will try to make a connection to the server and fail:

> E/flutter (18823): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Failed host lookup: 'my-host-name.com' (OS Error: No address associated with hostname, errno = 7)
> E/flutter (18823): #0      IOClient.send (package:http/src/io_client.dart:33:24)
> E/flutter (18823): <asynchronous suspension>
> E/flutter (18823): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
> E/flutter (18823): #2      BaseClient.get (package:http/src/base_client.dart:35:7)
> E/flutter (18823): #3      RefDataService.getAllCategories (package:service/refDataService.dart:131:45)

Then a little while later (could be a few minutes or a few hours), it'll start working again.  

I have googled the issue quite extensively and yes, I do have `<uses-permission android:name="android.permission.INTERNET" />` in AndroidManifest.xml.  I was wondering if someone could help me pinpoint where this issue could be, maybe it's a DNS issue?

Here's the `flutter doctor` logs:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CA)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)
> [!] IntelliJ IDEA Community Edition (version 2019.1.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
> [✓] VS Code (version 1.37.1)
> [✓] Connected device (2 available)
> 
> ! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @mohisham 
Make sure you execute `flutter clean` and have stable internet connection to device/emulator. If it's emulator, close the emulator and restart it.

Test your host outside of the code and make sure it's accessible and try again 
Looks at this related issue [#27883](https://github.com/flutter/flutter/issues/27883)
Most often it is permission, typo or unstable connection 

Thank you

**Comment by mohisham** [comment]
Actually it turned out to be a DNS issue as I suspected.  There was some misconfiguration on Route53 and once I resolved that the app works fine.
