### ISSUE TITLE
[Feature] Support macOS in url_launcher

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#52610]
## Proposal
Add support for launching urls on macOS.

In my case, the code
```dart
 Process.run('open', [url]);
```
worked just fine.

**Comment by stuartmorgan** [comment]
macOS support was added to url_launcher last year.

**Comment by ThinkDigitalSoftware** [comment]
Thanks. I must be on drugs. I'll take a look at it later
