### ISSUE TITLE
verify phone number error flutter iOS

### ISSUE THREAD

**Issue by amee13bit** [flutter/flutter#52618]
otp was working fine..but recently after flutter updates its showing verify phone number error
otp in android works but in ios its showing verify phone number error

flutter doctor

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.43.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @amee13bit 
[otp](pub.dev/packages/otp) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/Daegalus/dart-otp/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
