### ISSUE TITLE
issue in flutter share packages in IOS iPad Pro 

### ISSUE THREAD

**Issue by TheGhostDevlopper** [flutter/flutter#52627]
I have this issue when I run share with  Share.share("hello world"); that work fine with iPhone and android but not with iPad Pro 
I have this message : 

   "<ShareData: 0x600003f78b00>"
)
	Probably at least one of the constraints in the following list is one you don't want.
	Try this:
		(1) look at each constraint and try to figure out which you don't expect;
		(2) find the code that added the unwanted constraint or constraints and fix it.
(
    "<NSLayoutConstraint:0x600001d456d0 LPLinkView:0x7fd60de5a540.leading == UILayoutGuide:0x60000072c1c0'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600001d437a0 H:[LPLinkView:0x7fd60de5a540]-(59)-|   (active, names: '|':_UIActivityContentTitleView:0x7fd60de0db20 )>",
    "<NSLayoutConstraint:0x600001d44460 H:|-(0)-[_UIActivityContentTitleView:0x7fd60de0db20]   (active, names: '|':_UINavigationBarContentView:0x7fd6108dc400 )>",
    "<NSLayoutConstraint:0x600001d44500 _UIActivityContentTitleView:0x7fd60de0db20.trailing == _UINavigationBarContentView:0x7fd6108dc400.trailing   (active)>",
    "<NSLayoutConstraint:0x600001d78fa0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x7fd6108dc400.width == 0   (active)>",
    "<NSLayoutConstraint:0x600001d457c0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x60000072c1c0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x7fd60de0db20 )>"
)
Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x600001d456d0 LPLinkView:0x7fd60de5a540.leading == UILayoutGuide:0x60000072c1c0'UIViewLayoutMarginsGuide'.leading   (active)>
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

flutter Doctor : 
[✓] Flutter (Channel master, v1.15.3-pre.37, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.15.3-pre.37 at /Users/macbook/flutter
    • Framework revision 6dc3bfaa98 (5 weeks ago), 2020-02-07 18:28:02 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (3rd generation) • AA149D37-EB32-4E26-A21B-AB54FBB48B34 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome                                • chrome                               • web-javascript • Google Chrome 76.0.3809.132
    • Web Server                            • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by enricobenedos** [comment]
Duplicated of #47220, please close it. A workaround is available [here](https://github.com/flutter/flutter/issues/44962#issuecomment-554932650)

**Comment by iapicca** [comment]
Hi @TheGhostDevlopper 
as @enricobenedos pointed out there's an open [issue](https://github.com/flutter/flutter/issues/47220) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
