### ISSUE TITLE
Build Error : Finished with error: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Ugocode** [flutter/flutter#52624]
Please I have this issue and I don't know what to do 

When i try to run the default count app for flutter I get this error message: 

```bash
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c)
      > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/x86_64_debug-1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c.jar'.
         > Premature end of Content-Length delimited message body (expected: 10307141; received: 2057

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by Ugocode** [comment]
@iapicca 
So this is what I get when I run flutter -v 

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.719], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Ugoboss\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Ugoboss\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by Ugocode** [comment]
Hi again @iapicca
when I did flutter run -v 
I got: 

[  +32 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +99 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +71 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[   +7 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +117 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +149 ms] executing: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe devices -l
[  +52 ms] Exit code 0 from: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator
           device:generic_x86_arm transport_id:1
[  +31 ms] C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +105 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +317 ms] Generating
C:\Users\Ugoboss\Desktop\flutterApp\second_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegi
strant.java
[  +66 ms] ro.hardware = ranchu
[  +66 ms] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +32 ms] Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[  +22 ms] executing: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[ +115 ms] Exit code 0 from: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -t 1
[   +2 ms] --------- beginning of main
           03-15 13:00:31.000 I/GnssLocationProvider( 1909): WakeLock released by
           handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@811faf8)
[  +11 ms] executing: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe version
[   +2 ms] executing: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe -s emulator-5554 logcat -v time -T
03-15 13:00:31.000
[ +145 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.6-6198805
                    Installed as C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\Ugoboss\Android\SDK\platform-tools\adb.exe start-server
[  +84 ms] Building APK
[  +31 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[  +12 ms] Using gradle from C:\Users\Ugoboss\Desktop\flutterApp\second_app\android\gradlew.bat.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +312 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +6 ms] executing: [C:\Users\Ugoboss\Desktop\flutterApp\second_app\android\]
C:\Users\Ugoboss\Desktop\flutterApp\second_app\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\Ugoboss\Desktop\flutterApp\second_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+4396 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +5 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +3 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[  +18 ms] > Task :app:checkDebugManifest UP-TO-DATE
[  +70 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +173 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[ +159 ms] > Task :app:cleanMergeDebugAssets
[  +63 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +2 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[ +298 ms] > Task :app:mergeDebugAssets
[ +699 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +104 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +8 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +106 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +3 ms] > Task :app:processDebugResources UP-TO-DATE
[ +102 ms] > Task :app:compileDebugKotlin FAILED
[ +175 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileDebugKotlin'.
[   +1 ms] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
[   +1 ms]    > Could not download x86_64_debug.jar
(io.flutter:x86_64_debug:1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c)
[   +2 ms]       > Could not get resource
'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/x86_64_debug
-1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c.jar'.
[   +3 ms]          > Premature end of Content-Length delimited message body (expected: 10307141; received:
2057
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 6s
[   +1 ms] 16 actionable tasks: 4 executed, 12 up-to-date
[+2141 ms] Running Gradle task 'assembleDebug'... (completed in 8.9s)
[  +13 ms] "flutter run" took 10,293ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by Ugocode** [comment]
Please any help here Please its still giving me this issues i have even reinstalled my flutter and Android studio?

**Comment by iapicca** [comment]
Hi @Ugocode 
thank you for providing your logs 
can you please provide also 
your `flutter doctor -v` ,
and if possible a reproducible minimal code sample.
Thanks again

**Comment by Ugocode** [comment]
OMG After so much stress I found the solution all I had to do was to use a better network. switched off my WIFI and reboot it! boom it worked !. It was simply a network issue. I got insight from @jonahwilliams
