### ISSUE TITLE
Solution Proposal for showing or not the `errorText` in the `TextFormField`

### ISSUE THREAD

**Issue by psygo** [flutter/flutter#52634]
## Use case

It would be nice to have a `TextFormField` that didn't show the error messages below when trying to do validation. For example, in my design, I chose to show the error messages interactively on the `labelText`. 

Having no option of disabling the `errorText` can really be annoying when trying to deal with the spacing of the fields. You will either have to create an extra-padded `TextFormField` and let the `errorText` be always `' '`, or live with the abrupt transition of when the error message appears and the spacing changes.

This has appeared in complaints before:

- [StackOverflow &mdash; Flutter increase height of TextFormField](https://stackoverflow.com/q/50523006/4756173)
- Issue #15400 &mdash; TextField height changes if the errorText shows

## Proposal

I don't have a good solution for the abrupt transition when the `errorText` appears. Maybe showing it with some sort of `AnimatedContainer` would be a good option. (One solution that goes along those lines is [this one](https://medium.com/@mjpublicuser/flutter-challenge-animated-text-form-field-884dff3140f0)).

However, when it comes to showing or not the `errorText`, I have a suggestion &mdash; also featured in [this SO answer](https://stackoverflow.com/a/60695612/4756173) &mdash; that would change only 2 lines of the [source's `TextFormField`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart):

1. Add another parameter to the `TextFormField`'s constructor (below [this line](https://github.com/flutter/flutter/blob/1ca4815035e6aa14831d8148062c732be3a458c4/packages/flutter/lib/src/material/text_form_field.dart#L175)), say, `errorTextPresent`:
    ```dart
    // `true` is the current implicit default, i.e., showing the `errorText`
    bool errorTextPresent = true 
    ```
1. Change the decoration's initialization of the internal `TextField` to feature the new option.
    1. From:
        https://github.com/flutter/flutter/blob/1ca4815035e6aa14831d8148062c732be3a458c4/packages/flutter/lib/src/material/text_form_field.dart#L220
    1. To:
        ```dart
        decoration: effectiveDecoration.copyWith(
            errorText: errorTextPresent ? field.errorText : null)
        ```
1. You can now call `TextFormField` with a new option when you wish to disable the `errorText`:
    ```dart
    TextFormFieldWithErrorTextOption(
      errorTextPresent: false, // `false` will disable the `errorText`
      ...
    ),
    ```

Strictly speaking, this issue should probably have been a PR. But I chose it to be an issue because I didn't really know how the Flutter team would have liked to proceed.

**Comment by justinmc** [comment]
How does this proposal solve the problem of a jarring height change when the error text appears?  Do you just want the field to turn red but never show error text?

**Comment by psygo** [comment]
> How does this proposal solve the problem of a jarring height change when the error text appears?

I'm not sure if I'm missing something from the question, but my solution simply disables the `errorText`, so there wouldn't be any height change altogether.

>  Do you just want the field to turn red but never show error text?

My complete solution for fixing the height change has more to it than simply disabling the `errorText` below the field, but that's a solid step and a nice option to have anyway. My final design would feature the `labelText` changing to show the error &mdash; this could be a future nice feature of `TextFormField` in my opinion, i.e., where to show the `errorText` &mdash;; this way there would be no height change. Of course, I would have plenty of redundant design elements to still show the user the meaning of the field when the `labelText` has changed to an error message.

A simple sample &mdash; in this case, the `labelText` would be `password` initially &mdash;:

![image](https://user-images.githubusercontent.com/11823725/77161089-9881e400-6a87-11ea-8701-11673f3f37ec.png)

**Comment by justinmc** [comment]
Ok got it.  Could you post a minimal app that shows the problem if you have time?  It would be helpful to see a full example.  I wasn't even thinking of bordered text fields at first.

**Comment by psygo** [comment]
I've been working on a project/package for authentication with Flutter ([flutter_firebase_auth_benchmark](https://github.com/psygo/flutter_firebase_auth_benchmark)) in the last 2 weeks. The image I shared above is from it. You can check out my implementation of what I suggested in it.

The widget with the mentioned features is the [`AuthTextFormField`](https://github.com/psygo/flutter_firebase_auth_benchmark/blob/master/lib/widgets/login/auth_textformfield.dart), which returns my modified version of the `TextFormField`, which I called [`TextFormFieldWithErrorTextOption`](https://github.com/psygo/flutter_firebase_auth_benchmark/blob/master/lib/widgets/utils/text_form_field_without_errortext.dart) for the moment.

The project is a way for me to learn more about Flutter and Dart, besides serving a great entrypoint for later apps, since authentication is so ubiquitous. 

With respect to the project's architecture, I would say I encountered quite some problems which would change my approach completely if I were to start it over again. You can find out more about the problems in the README.

**Comment by justinmc** [comment]
Thanks for the explanation and for taking the time to write out all that feedback in the README.

For the record, another solution to this problem is to return an empty string from `validator` and then set the height of the error to zero:

```dart
TextFormField(
  decoration: const InputDecoration(
    errorStyle: TextStyle(height: 0),
  ),
  validator: (value) => value.isEmpty ? '' : null,
),
```

That's not really an ideal solution, though.  We might need to make some bigger changes to Flutter's form validation, there was another PR recently with some good discussion about this (https://github.com/flutter/flutter/pull/48155).  I hesitate to add new parameters like `errorTextPresent` since it's already pretty complicated, though it definitely would make this use case a lot cleaner.

**Comment by psygo** [comment]
> there was another PR recently with some good discussion about this (#48155)

Really interesting PR indeed.

<hr>

There are plenty of other solutions for this problem, I guess. I'm not a huge fan of the one you mentioned, though, because you seem to be turning the validator's usefulness down.

Another solution I was thinking about lately was to put this boolean inside `InputDecoration` instead, since showing or not the error feels more like a decoration choice than functionality itself, and it might make things easier to understand for the user.

<hr>

Quite frankly, as a Flutter user, I'm not very satisfied with the `TextFormField`'s design overall, specially the error text placement. There are so many modern designs which are so much more appealing. These should be very easy to implement, I think; we should not have to rework dozens of things. Take a look at [this one](https://medium.com/@mjpublicuser/flutter-challenge-animated-text-form-field-884dff3140f0) for example, it even features animations, which is something some of the basic Flutter widgets already do have.

On a sidenote, if there is interest in reworking the `TextFormField`, I would really suggest adding yet another parameter &mdash; to `InputDecoration` probably &mdash; for how many characters it takes before the ellipsis character appears on the `labelText`. I have created an issue about this: #53166. The solution to it seems to be buried deep down in some of the core renderers, but I'm not sure about it.

**Comment by justinmc** [comment]
Flutter's Material library needs to follow the Material spec (see "Error text" in the [Material docs](https://material.io/components/text-fields/#anatomy)).  However, we should make it easy for developers to customize our widgets.  Sometimes it is kind of like Material/Cupertino or nothing.

I'll take a look at the ellipsis issue.

**Comment by PollyGlot** [comment]
It would be nice to see some updates on this issue/proposal as I am also currently working with the task where I don't show an error text bellow the textField's

**Comment by justinmc** [comment]
A [PR](https://github.com/flutter/flutter/pull/59766) was recently merged that introduces the [autovalidateMode](https://master-api.flutter.dev/flutter/widgets/FormField/autovalidateMode.html) property to form fields.  Would that solve the problem here?

**Comment by markusaksli-nc** [comment]
Closing due to timeout.

Let us know if there is anything still to be done here.

**Comment by homelyng** [comment]
> Closing due to timeout.
> 
> Let us know if there is anything still to be done here.

Everything still needs to be done here @markusaksli-nc 

This is still a problem for many flutter ui developers.

also see https://github.com/flutter/flutter/issues/54104#issuecomment-803554424

**Comment by markusaksli-nc** [comment]
So the `autovalidateMode` property didn't solve this?

**Comment by vidklopcic** [comment]
I've been dealing with this issue for more than two years now. It's simply unacceptable that we still don't have any normal solution for this. I've seen and used everything from OverflowBox to manual borderStyle changes...

Setting `height: 0` and returning empty error message worked for a while, but it doesn't on the latest master anymore.

**Comment by naveenyadav15** [comment]
> Thanks for the explanation and for taking the time to write out all that feedback in the README.
> 
> For the record, another solution to this problem is to return an empty string from `validator` and then set the height of the error to zero:
> 
> ```dart
> TextFormField(
>   decoration: const InputDecoration(
>     errorStyle: TextStyle(height: 0),
>   ),
>   validator: (value) => value.isEmpty ? '' : null,
> ),
> ```
> 
> That's not really an ideal solution, though. We might need to make some bigger changes to Flutter's form validation, there was another PR recently with some good discussion about this (#48155). I hesitate to add new parameters like `errorTextPresent` since it's already pretty complicated, though it definitely would make this use case a lot cleaner.

By using this method the error is showing on top of the TextFormField.
