### ISSUE TITLE
Engine v1.12.13-hotfixes will be crashing when I using on iOS13.3 iPhone 11 pro

### ISSUE THREAD

**Issue by SiTianyu** [flutter/flutter#52633]
On v1.12.13-hotfixes, iOS13.3 iPhone 11 pro. when I am using share to share an article. And when I want to exit the share screen, after clicking the dim black color on the top, the app will be crash.

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   Foundation                          0x00007fff257694dd +[NSProxy init] + 0
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
*** First throw call stack:
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   Flutter                             0x0000000104554171 -[FlutterAppDelegate touchesBegan:withEvent:] + 93
	6   UIKitCore                           0x00007fff480bf863 forwardTouchMethod + 340
	7   UIKitCore                           0x00007fff480bf6fe -[UIResponder touchesBegan:withEvent:] + 49
```
I think it's taken by the new method named `handleStatusBarTouches` in the lastest version when I using UIActivityViewController to share.

**Comment by iapicca** [comment]
Hi @SiTianyu 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by SiTianyu** [comment]
@iapicca Thank you for ur quick response. I think this issue is caused by another third part plugin. So I will close this issue now. Thank you very much.
