### ISSUE TITLE
How to get widget local position of it's parent widget in Flutter

### ISSUE THREAD

**Issue by gifhary** [flutter/flutter#52630]
I have a `Zoom` widget that has `CustomPaint` with `GridView.builder `in it. There are multiple `GridTile` inside `GridView` according to nested List variable. The `GridTile` will show an icon if the String in List is empty and show network image if not empty. I want to get the image Offset when tapped according to Container `x` and `y` above `GridView`. So the Offset value will never changed even if the Container is zoomed in, out or dragged on the same Image widget tapped.

```
List<List<String>> _gridState = [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', 'a', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', 'a', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
      ];
```

The `GridView.builder`'s `x` and `y` count based on nested `List` above as the guide.

```
Zoom(
     doubleTapZoom: false,
     backgroundColor: Colors.white,
     width: 2250,
     height: 3000,
     initZoom: 0.3,
     zoomSensibility: 3,
     child: CustomPaint(
     painter: LinePainter(paths: _path),
     child: Container(
        child: Center(
           child: GridView.builder(
               gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: _gridState.length,),
               itemBuilder: _buildGridItem,
               itemCount: _gridState.length * _gridState[0].length,
               scrollDirection: Axis.horizontal,
              ),
      ),
    ),
  ),
),
```

Build `GridTile` according to nested list value. Display icon if the String is empty and image if not empty.

```
Widget _buildGridItem(BuildContext context, int index) {
    int gridStateLength = _gridState.length;
    int x, y = 0;
    x = (index % gridStateLength);
    y = (index / gridStateLength).floor();

    GlobalKey imageGK = new GlobalKey();

    return GridTile(
      child: Container(
        child: DottedBorder(
          dashPattern: [10, 20],
          strokeWidth: 10,
          color: Color.fromRGBO(184, 184, 184, 0.6),
          child: Center(
              child: _gridState[x][y].isEmpty
                  ? Icon(
                        Icons.add_circle_outline,
                        size: 100,
                        color: Theme.themeData.accentColor,
                      )
                  : GestureDetector(
                      key: imageGK,
                      onTap: () {
                         //current method to get the offset
                         RenderBox _box = imageGK.currentContext.findRenderObject();
                         Offset offset = _box.localToGlobal(Offset.zero);
                         print("offset ontap: $offset");

                         //with above function, the result is not the correct position
                         //and inconsistent whenever the `Container` is zoomed in,
                         //out or dragged. Sometime the value is negative.
                      },
                      child: Image.network(_imageURL, fit: BoxFit.cover),),
        ),
      ),
    );
  }
```

I've tried `globalToLocal` method, the result is same. Also tried using details provided by `onTapDown` in `GestureDetector`, it returns local `Offset` inside the image so the line drawn at the top left corner of the `Container`.

I want to draw line between `GridTile` that has an image in it with `CustomPainter`. The line will be drawn on the `Container` widget, so the offset must follow `Container` pixel, not screen pixel. With the current method, the result for left image is `Offset(0.7, 306.4)` and right `Offset(206.7, 306.4)`, the line should stick to the image.

![Screenshot_2020-03-15-17-43-17](https://user-images.githubusercontent.com/43630682/76704432-f030f000-6713-11ea-8cb2-76e0ab7b1832.png)

**Comment by Azmighaleb** [comment]
I get same issue 
Did find any solution?

**Comment by iapicca** [comment]
Hi @gifhary 
are you still experiencing the issue with the latest stable (or above)?
if so could you please provide your updated `flutter doctor -v`
and a minimal **runnable** reproducible code sample (not a snippet from production code).
Thank you

**Comment by gifhary** [comment]
Hello @iapicca 
It wasn't an issue with Flutter, something like a tricky situation which Flutter did not provided, so i did solve the problem by getting global position of a widget, then convert to local position of a target widget.

````
      RenderBox child = childKey.currentContext.findRenderObject();
      Offset childOffset = child.localToGlobal(Offset.zero);
      //convert
      RenderBox parent =
          parentKey.currentContext.findRenderObject();
      Offset childRelativeToParent = parent.globalToLocal(childOffset);
````
