### ISSUE TITLE
Flutter engine disk footprint analysis

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#52647]
Recently, developers from our team are trying to analyze the flutter engine size and check if we can do reduce the size as we have many already existing sdks in our native applications.

However, when analyzing the footprint for engine sha(e1e6ced81d029258d449bdec2ba3cddca9c2ca0c) corresponding to flutter 1.12.13+hotfix.8 found two questions about the footprint data.
https://storage.googleapis.com/flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/android-arm-release/sizes/index.html

a. In the size html, it reports a summary of 4.31MB，however, I noticed that the libflutter.so located in armeabi_v7a_release-1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c.jar has a size of 6MB.
What's the difference between those two numbers?

b. In the size html, there is also a report for src/out directory,
![image](https://user-images.githubusercontent.com/817851/76720018-8b5ab180-6776-11ea-8bf8-68dab6a09742.png)
Why?  From my understanding, there is no source code for src/out directory, so it is unreasonable to have a size for this directory.

@chinmaygarde  
CC @liyuqian

**Comment by liyuqian** [comment]
Also CC @goderbauer and @dnfield . My first reaction of 4.31MB vs 6MB is that the difference might be caused by compression.

**Comment by goderbauer** [comment]
The tree map shows uncompressed sizes, so you should be comparing it to the uncompressed size of the `.so` file.

**Comment by goderbauer** [comment]
`src/out` contains a helper file `ld-temp.o` that generated during (or to enable) link-time-optimization (LTO). Since parts of that file are linked into the final binary, the `src/out` directory shows up in the tree map.

**Comment by dnfield** [comment]
@goderbauer - the uncompressed size _is_ 6mb - https://storage.googleapis.com/flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/android-arm-release/artifacts.zip is about 3.8mb, unzipping it produces flutter.jar, unzipping that shows you a 6mb libflutter.so

**Comment by goderbauer** [comment]
I see, my comment was in response to https://github.com/flutter/flutter/issues/52647#issuecomment-599691578 where it was speculated that this may be due to compression :) 

Does the ICU data show up in the treemap? Don't we inline that into the binary now-a-days? Maybe that's the difference?

**Comment by chinmaygarde** [comment]
While the HTML size report is great for getting a high-level picture of the size of the various engine components, it’s not very accurate and easily confused. I would not consider it useful for asking precise questions about binary size. Instead, consider using `bloaty`, `readelf`, and `nm` for the most accurate information. Bloaty is particularly useful as well for comparing the binary sizes of two versions of the same binary and attribute the differences to symbols or translation units (see an [example of the diff generation here](https://github.com/flutter/engine/pull/17080#issue-386418809)).

In any case, for the engine version you are investigating, I could gather the following information:

Engine Artifact: gs://flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/android-arm-release/artifacts.zip
Symbolicated Engine Artifact: gs://flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/android-arm-release/symbols.zip

Since you primarily care about the disk size and not the VM size, you need the symbolicated engine separately (debug info will mess up the disk size summaries if you use the symbolicated binary directly). A dump of sizes attributed to translation units is as follows:

```
$ bloaty --debug-file symbols/libflutter.so -s file -n 20 -C full -d compileunits libflutter.so
     VM SIZE                                                               FILE SIZE
 --------------                                                         --------------
  50.9%  2.93Mi [1331 Others]                                            2.92Mi  50.8%
  15.0%   882Ki [section .data]                                           882Ki  15.0%
  11.7%   687Ki [section .rodata]                                         687Ki  11.7%
   3.6%   212Ki [section .rel.dyn]                                        212Ki   3.6%
   2.8%   166Ki ../../third_party/dart/runtime/vm/object.cc               166Ki   2.8%
   2.0%   119Ki [section .ARM.exidx]                                      119Ki   2.0%
   1.7%   102Ki [section .data.rel.ro]                                    102Ki   1.8%
   1.6%  95.9Ki ../../third_party/dart/runtime/bin/io_service.cc         95.9Ki   1.6%
   1.6%  92.6Ki ../../third_party/boringssl/src/crypto/fipsmodule/bcm.c  92.0Ki   1.6%
   1.4%  84.4Ki ../../third_party/dart/runtime/vm/dart_api_impl.cc       84.4Ki   1.4%
   0.9%  53.0Ki ../../third_party/dart/runtime/vm/regexp.cc              53.0Ki   0.9%
   0.9%  52.3Ki [section .text]                                          52.3Ki   0.9%
   0.8%  49.0Ki ../../third_party/skia/src/sksl/SkSLIRGenerator.cpp      49.0Ki   0.8%
   0.7%  42.7Ki ../../third_party/libcxx/src/locale.cpp                  41.6Ki   0.7%
   0.7%  40.7Ki ../../third_party/boringssl/src/crypto/obj/obj.c         40.7Ki   0.7%
   0.6%  36.8Ki ../../third_party/dart/runtime/vm/clustered_snapshot.cc  36.8Ki   0.6%
   0.6%  36.1Ki ../../third_party/freetype2/src/truetype/truetype.c      36.1Ki   0.6%
   0.6%  35.6Ki ../../third_party/skia/src/core/SkOpts.cpp               35.6Ki   0.6%
   0.6%  35.2Ki ../../third_party/dart/runtime/vm/runtime_entry.cc       35.2Ki   0.6%
   0.6%  35.0Ki ../../third_party/expat/files/lib/xmltok.c               35.0Ki   0.6%
   0.6%  34.4Ki ../../third_party/freetype2/src/autofit/autofit.c        34.4Ki   0.6%
 100.0%  5.76Mi TOTAL                                                    5.74Mi 100.0%
```

5.74Mi matches perfectly with the size on disk (Finder on macOS says 6MB which is 1-Mbyte blocks) so we are starting with a good baseline. You may increase the count to be as large as you want to get a more complete picture. I am only listing the top 20.

From this summary, you can also see that the stuff from the `out` directory you noticed earlier is absent. Do note however that the Flutter Engine may put generated artifacts in the `out` directory and if these artifacts end up adding entries to the `.text` segment, you will see these attributed to locations in the `out` directory. So, while stuff from the `out` directory is currently not expected to be present in the summary, this may change in the future. But, at least now you will be able to tell which generated file added to the `.text` segment.

The next step is to identify what’s in the other segments. A dump of the sections in Bloaty is as follows:
```
$ bloaty --debug-file symbols/libflutter.so -s file -n 20 -C full -d sections libflutter.so
     VM SIZE                     FILE SIZE
 --------------               --------------
  62.4%  3.59Mi .text          3.59Mi  62.5%
  15.0%   883Ki .data           883Ki  15.0%
  13.6%   801Ki .rodata         801Ki  13.6%
   3.6%   212Ki .rel.dyn        212Ki   3.6%
   2.5%   148Ki .data.rel.ro    148Ki   2.5%
   2.0%   119Ki .ARM.exidx      119Ki   2.0%
   0.1%  6.78Ki .ARM.extab     6.78Ki   0.1%
   0.1%  6.50Ki .dynsym        6.50Ki   0.1%
   0.1%  5.14Ki .dynstr        5.14Ki   0.1%
   0.1%  4.75Ki .plt           4.75Ki   0.1%
   0.1%  3.26Ki .hash          3.26Ki   0.1%
   0.0%  2.36Ki .rel.plt       2.36Ki   0.0%
   0.0%       0 [Unmapped]     1.95Ki   0.0%
   0.0%     340 [ELF Headers]  1.39Ki   0.0%
   0.0%  1.19Ki .got.plt       1.19Ki   0.0%
   0.3%  18.9Ki [11 Others]       834   0.0%
   0.0%     832 .gnu.version      832   0.0%
   0.0%     536 .got              536   0.0%
   0.0%  1.98Ki [LOAD [RW]]       440   0.0%
   0.0%       0 .comment          320   0.0%
   0.0%     256 .dynamic          256   0.0%
 100.0%  5.76Mi TOTAL          5.74Mi 100.0%

```

The `.data` segment looks interesting at 15% of disk size. This is initialized static data. It also looks large enough to cover the ICU data that is packaged in the dynamic library. Let’s confirm. 

First, figure out the pointer to the ICU data from the dynamic symbol table.

```
$ readelf -s libflutter.so | grep icudtl
   413: 004bb000     0 NOTYPE  GLOBAL DEFAULT   16 _binary_icudtl_dat_start
   414: 000dc2b0     0 NOTYPE  GLOBAL DEFAULT  ABS _binary_icudtl_dat_size
```

Turns out 0x004bb000 is right at the start of the .data segment range of 0x4bb000 - 0x597e4c (904780 bytes) which you can find using `readelf -t`.

Hope these techniques help you answer questions about binary size. None of this is Flutter specific BTW and should work for all binaries under consideration.

**Comment by chinmaygarde** [comment]
Generating a Flame Graph from the Bloaty representation in quite straightforward. I generated one for the engine you are looking. It is [available here](https://public.chinmaygarde.com/flutter/flame/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/flame.html). It is more accurate the one you linked to. But really, for answering questions about what is in the specific segments, you'll have to resort to the techniques I outlined earlier.

**Comment by kangwang1988** [comment]
Thank you guys for detailed explanation.

As the [wiki](https://storage.googleapis.com/flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/android-arm-release/sizes/index.html) seems confusing,
do you think it's necessary to update the wiki?

@chinmaygarde

**Comment by dnfield** [comment]
@chinmaygarde  can you share how you generated the flame graph?  What command(s)?

**Comment by kangwang1988** [comment]
@chinmaygarde 
Besides, which is the debug-info file for Flutter.framework/Flutter located in src/out/ios_release/Flutter.framework/Flutter?

**Comment by chinmaygarde** [comment]
> As the wiki seems confusing, do you think it's necessary to update the wiki?

That link points to the size analysis document. Can you link the Wiki article please?

> can you share how you generated the flame graph? What command(s)?

I documented the commands in this internal article go/flutter-engine-size-viz. But there isn't anything sensitive in it. Its just a few lines of Ruby to transform the CSV to the flamegraph.

> Besides, which is the debug-info file for Flutter.framework/Flutter located in src/out/ios_release/Flutter.framework/Flutter?

The iOS binaries are not stripped. So the debug info is in the file itself. However, that file is also a fat binary (armv7, aarch64 and x86_64 for simulators). So, to get a gauge of the disk size on iOS, I would thin that fat mach binary to just a specific architecture to mimic the thinning done at the App store, then strip the binary. The thin unstripped binary is the debug file and the thin stripped binary is what users will have on their phones.

**Comment by kangwang1988** [comment]
> The iOS binaries are not stripped. So the debug info is in the file itself. However, that file is also a fat binary (armv7, aarch64 and x86_64 for simulators). So, to get a gauge of the disk size on iOS, I would thin that fat mach binary to just a specific architecture to mimic the thinning done at the App store, then strip the binary. The thin unstripped binary is the debug file and the thin stripped binary is what users will have on their phones.

Actually, I'm using bloaty to analyze Flutter.framework for custom compiled single-arch Flutter.framework.
However, I got this error:
```shell
kylewong@KyleWongdeMacBook-Pro src % cd /Users/kylewong/Codes/Flutter/alibaba-flutter/StableV1.12.13/engine/src/out/ios_release 
kylewong@KyleWongdeMacBook-Pro ios_release % bloaty --debug-file Flutter.framework/Flutter  -s file -n 100 -C full -d compileunits Flutter.framework/Flutter
bloaty: missing debug info
kylewong@KyleWongdeMacBook-Pro ios_release % pwd
/Users/kylewong/Codes/Flutter/alibaba-flutter/StableV1.12.13/engine/src/out/ios_release
kylewong@KyleWongdeMacBook-Pro ios_release % lipo -info Flutter.framework/Flutter 
Non-fat file: Flutter.framework/Flutter is architecture: arm64
```

> That link points to the size analysis document. Can you link the Wiki article please?
Sorry for mislinking. I've updated the comment and the wiki link i'm referring, see: https://github.com/flutter/flutter/wiki/Engine-disk-footprint

**Comment by chinmaygarde** [comment]
For an iOS engine that you build locally, you need to create a `.dSYM` package manually for the debug symbols:

```
dsymutil -o Flutter.framework.dSYM Flutter.framework/Flutter
```

Then, use the file in `.dSYM` package as the debug file to Bloaty:

```
$ bloaty --debug-file Flutter.framework.dSYM/Contents/Resources/DWARF/Flutter -d compileunits Flutter.framework/Flutter 
     VM SIZE                                                               FILE SIZE
 --------------                                                         --------------
  57.5%  6.28Mi [1241 Others]                                            6.27Mi  57.5%
  23.9%  2.61Mi [__LINKEDIT]                                             2.60Mi  23.9%
   2.5%   278Ki [__TEXT,__cstring]                                        278Ki   2.5%
   2.3%   258Ki ../../third_party/dart/runtime/vm/object.cc               257Ki   2.3%
   1.4%   157Ki ../../third_party/boringssl/src/crypto/fipsmodule/bcm.c   157Ki   1.4%
   1.2%   135Ki ../../flutter/shell/common/shell.cc                       135Ki   1.2%
   1.2%   132Ki ../../third_party/icu/source/common/uchar.cpp             132Ki   1.2%
   1.0%   111Ki ../../third_party/dart/runtime/vm/dart_api_impl.cc        111Ki   1.0%
   0.9%   105Ki ../../third_party/harfbuzz/src/hb-ot-layout.cc            105Ki   0.9%
   0.9%  98.8Ki ../../third_party/skia/src/sksl/SkSLIRGenerator.cpp      98.8Ki   0.9%
   0.8%  87.9Ki [__TEXT,__objc_methtype]                                 87.9Ki   0.8%
   0.7%  82.6Ki ../../third_party/dart/runtime/bin/io_service.cc         82.6Ki   0.7%
   0.7%  80.6Ki ../../third_party/skia/src/core/SkOpts.cpp               80.6Ki   0.7%
   0.7%  80.4Ki ../../third_party/harfbuzz/src/hb-aat-layout.cc          80.4Ki   0.7%
   0.7%  80.2Ki ../../third_party/dart/runtime/vm/bootstrap_natives.cc   80.2Ki   0.7%
   0.7%  79.2Ki ../../third_party/dart/runtime/vm/regexp.cc              79.2Ki   0.7%
   0.7%  73.1Ki ../../third_party/dart/runtime/vm/clustered_snapshot.cc  73.1Ki   0.7%
   0.5%  60.5Ki ../../third_party/harfbuzz/src/hb-ot-font.cc             60.5Ki   0.5%
   0.5%  59.2Ki ../../third_party/dart/runtime/vm/runtime_entry.cc       57.0Ki   0.5%
   0.5%  58.4Ki ../../third_party/skia/src/sksl/SkSLCompiler.cpp         58.4Ki   0.5%
   0.5%  57.8Ki ../../third_party/dart/runtime/vm/isolate.cc             57.8Ki   0.5%
 100.0%  10.9Mi TOTAL                                                    10.9Mi 100.0%
```

BTW, for a released iOS engine, the .dSYM files are available on the cloud buckets already at:
gs://flutter_infra/flutter/e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/ios-release/Flutter.dSYM.zip

**Comment by kangwang1988** [comment]
As I think this issue has give us a detailed description about how to do engine disk footprint analysis, closing this issue now.
