### ISSUE TITLE
Drop-down filter through a list of cards widget (feature request)

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#52650]
Hi, with that same search bar through the list, I'd also like to use drop-down preset filters for the same list. Could there be a widget for those drop-down filters?

**Comment by andesappal** [comment]
I'm thinking the parent could be a sliver widget

**Comment by Piinks** [comment]
I am closing this since it is not clear what is needed in this outdated issue. Since this issue was added, several new widgets like SearchBar have been added that seem to suite the stated need.
