### ISSUE TITLE
On web platforms, I want to receive a key event via RawKeyboardListener

### ISSUE THREAD

**Issue by cjng96** [flutter/flutter#52656]
## Use case

I need to receive a key event to customize some action on edit control.
**On web platform, a key event does not occur. :(**
(It's working well with RawKeyListener on Android platform)

I need RawKeyListener on EditableText for the following use-case,
1. Support short-cut key on edit control for several case
(1) Popup dialog for recommanded text list,
(2) Reset to default text status,
(3) Change input dialog layout(normal user or expert user)
2. I want to implement powerful rich editor based on flutter. so I need text editing service and keyEvent from Engine.

## Proposal

After some investigating, I found it's intented operation by the engine's pull-reqest #13699.

I think it's better that **the engine send the key event and the key event is ignored on editable.dart / RenderEdtiable / _handleKeyEvent function like following,**

```dart
    final bool isWeb = keyEvent.data is RawKeyEventDataWeb;
    if (isWeb) {
      // On web platforms, The key should be ignored because the cursor has already moved
      return;
    }
```

It solves original https://github.com/flutter/flutter/issues/44133 issue and I can receive key events on the Web, such as Android platform.

I modified engine and flutter code and it's working well now as expected.(RawKeyListener with EditableText is working well and duplicated keyboard action on input conttol on web doesn't occur)

I am going to make two pull-requests for it. :)

1. flutter engine / keyboard.dart
  [No ignore key event on input control on web platform](https://github.com/flutter/engine/pull/17242)

2. flutter / editable.dart
  [Ignore keyEvent from Web.](https://github.com/flutter/flutter/pull/52661)

**Comment by mdebbar** [comment]
Framework and engine PRs were merged (https://github.com/flutter/flutter/pull/52661 and https://github.com/flutter/engine/pull/17242).
