### ISSUE TITLE
Text painter layout cost more time when text content is longer  Even if there is no difference in display

### ISSUE THREAD

**Issue by sanlittt** [flutter/flutter#52651]
@liyuqian 

Hi,

I did a test and the code is as follows，strLong takes 2 to 3 times longer than strShort

    import 'package:flutter/material.dart';
    import 'package:flutter/widgets.dart';
    
    class DXTestScroll extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
    
        List<Widget> children = List();
    //    String strLong = 'OPPO R9s手机 全网通手机 oppo手机  \nR9s  金  高通 处理器 版本6.1\n95新以上 无磕碰 无ID 无账号 插卡既用 电池耐用 双卡双待 支持双开\n功能全正常使用  高清拍照 屏幕灵敏 肉感指纹 一触即用\n支持 移动 联通 电信 全4G   全网通\n运行4G 内存6...OPPO R9s手机 全网通手机 oppo手机  \nR9s  金  高通 处理器 版本6.1\n95新以上 无磕碰 无ID 无账号 插卡既用 电池耐用 双卡双待 支持双开\n功能全正常使用  高清拍照 屏幕灵敏 肉感指纹 一触即用\n支持 移动 联通 电信 全4G   全网通\n运行4G 内存6...';
        String strShort = 'OPPO R9s手机 全网通手机';
        for (int i=0;i<100;i++) {
          Widget abc = Text(strShort, maxLines: 1,);
          children.add(abc);
        }
    
        Widget list = GridView(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                childAspectRatio: 2
            ),
            children:children
        );
    
        return new Scaffold(
            appBar: new AppBar(title: new Text("长列表文本测试"),),
            body: list
        );
      }
    }

But their display is the same，as shown below
![](https://img.alicdn.com/tfs/TB1iZ4Zyrj1gK0jSZFOXXc7GpXa-250-542.png)

The time statistics test is as follows
(flutter/packages/flutter/lib/src/painting/text_painter.dart)

    static int totalTime = 0;
    static int totalCount = 0;
    void layout({ double minWidth = 0.0, double maxWidth = double.infinity }) {
        .....
        DateTime start = new DateTime.now();
        _paragraph.layout(ui.ParagraphConstraints(width: maxWidth));
        int costTime = DateTime.now().difference(start).inMicroseconds;
        totalTime += costTime;
        totalCount += 1;
        print('totalTime:$totalTime...totalCount:$totalCount');
    
        if (minWidth != maxWidth) {
          final double newWidth = maxIntrinsicWidth.clamp(minWidth, maxWidth);
          if (newWidth != width) {
            _paragraph.layout(ui.ParagraphConstraints(width: newWidth));
          }
        }
        _inlinePlaceholderBoxes = _paragraph.getBoxesForPlaceholders();
      }

Do you have any Suggestions for optimization?

flutter doctor -v

    [✓] Flutter (Channel v1.12.13hotfix6, v1.12.13+hotfix.6, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
        • Flutter version 1.12.13+hotfix.6 at /Users/sanli/Documents/WCode/fwn_idlefish/flutter
        • Framework revision 18cd7a3601 (3 months ago), 2019-12-11 06:35:39 -0800
        • Engine revision 2994f7e1e6
        • Dart version 2.7.0
    
     
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
        • Android SDK at /Users/sanli/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-29, build-tools 29.0.0
        • ANDROID_HOME = /Users/sanli/Library/Android/sdk
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
        • All Android licenses accepted.
    
    [!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 11.3.1, Build version 11C504
        ! Unknown CocoaPods version installed.
            Flutter is unable to determine the installed CocoaPods's version.
            Ensure that the output of 'pod --version' contains only digits and . to be recognized by Flutter.
          To upgrade:
            sudo gem install cocoapods
    
    [✓] Android Studio (version 3.6)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 43.0.2
        • Dart plugin version 192.7761
        • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by liyuqian** [comment]
Thank you @hamiao123 for reporting the issue and providing a minimal repro app! CC @GaryQian @jason-simmons for this text layout performance issue. Any idea whether the new Skia layout library would help? We might want to add this to our perf test suite so we'll have a concrete benchmark number on Moto G4, and continuously track the performance improvement/regression. (Gary recently added one in https://github.com/flutter/flutter/pull/46720 and https://github.com/flutter/flutter/pull/51788.)

**Comment by jason-simmons** [comment]
In this app, both `strLong` and `strShort` are being laid out with a paragraph style that specifies `maxLines: 1`, and both layouts yield the same line of glyphs.  But some additional work is done for `strLong`:

* `ParagraphTxt::ComputeLineBreaks` is processing line breaks on all the text in `strLong`.  Libtxt could save time here by stopping once the paragraph style's `max_lines` is reached.

* `ParagraphTxt::Layout` is doing extra work to handle a ghost run.  On a Moto G4 in portrait mode the available width results in the first line ending after the space and before "oppo".   Libtxt creates a ghost run to represent the whitespace character at the end of the line, and laying out this run consumes more time.  `strShort` has no trailing whitespace and does not need a ghost run.

**Comment by hamiao123** [comment]
@jason-simmons  
Thanks
what can I do to improve performance in this case， or  need to wait for your optimization

**Comment by jason-simmons** [comment]
Most of the time difference between `strLong` and `strShort` is spent doing line breaking.

`strLong` contains `\n` newline characters, but it is being laid out with `maxLines: 1`.  Layout will be faster if the app only passes the text before the first newline to the `Text` widget.

**Comment by TahaTesser** [comment]
Hi @sanlittt 
Using your code sample on the latest `master`, I can't spot a difference in performance or time to load font

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: DXTestScroll(),
    );
  }
}

// class Home extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Material App Bar'),
//       ),
//       body: Center(
//         child: Container(
//           child: Text('Hello World'),
//         ),
//       ),
//       floatingActionButton: FloatingActionButton(
//         child: Icon(Icons.add),
//         onPressed: () {},
//       ),
//     );
//   }
// }

class DXTestScroll extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<Widget> children = List();
    String strLong =
        'OPPO R9s手机 全网通手机 oppo手机  \nR9s  金  高通 处理器 版本6.1\n95新以上 无磕碰 无ID 无账号 插卡既用 电池耐用 双卡双待 支持双开\n功能全正常使用  高清拍照 屏幕灵敏 肉感指纹 一触即用\n支持 移动 联通 电信 全4G   全网通\n运行4G 内存6...OPPO R9s手机 全网通手机 oppo手机  \nR9s  金  高通 处理器 版本6.1\n95新以上 无磕碰 无ID 无账号 插卡既用 电池耐用 双卡双待 支持双开\n功能全正常使用  高清拍照 屏幕灵敏 肉感指纹 一触即用\n支持 移动 联通 电信 全4G   全网通\n运行4G 内存6...';
    // String strShort = 'OPPO R9s手机 全网通手机';
    for (int i = 0; i < 100; i++) {
      Widget abc = Text(
        strLong,
        maxLines: 1,
      );
      children.add(abc);
    }

    Widget list = GridView(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2, childAspectRatio: 2),
        children: children);

    return new Scaffold(
        appBar: new AppBar(
          title: new Text("长列表文本测试"),
        ),
        body: list);
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.359, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.359 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision db6e2d8aa5 (3 hours ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details> 

Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
