### ISSUE TITLE
Google sigin is not working in the codemagic Apk

### ISSUE THREAD

**Issue by vijay14887** [flutter/flutter#52652]
I developed the app in a flutter. Google sign-in is part of the app. But the problem is in while creating the apk using **"flutter build apk"** at that time google sign-in is working. While creating the apk using **"code magic"** at that time google sign-in is not working. I don't know where is the problem. Kindly help me to fix this issue. Thanks in Advance...

**Comment by iapicca** [comment]
Hi @vijay14887 
could you please provide the logs from your codemagic build
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
