### ISSUE TITLE
Because dio_cookie_manager 1.0.0 requires SDK version >2.4.0 <3.0.0 and no versions of dio_cookie_manager match >1.0.0 <2.0.0, dio_cookie_manager ^1.0.0 is forbidden.

### ISSUE THREAD

**Issue by xintianyou** [flutter/flutter#52664]

**Comment by iapicca** [comment]
Hi @xintianyou 
[dio](https://pub.dev/packages/dio) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/flutterchina/dio/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
