### ISSUE TITLE
Android 11: Waterfall inset API support

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#52674]
Android will be providing a [new API](https://developer.android.com/reference/android/view/DisplayCutout#getWaterfallInsets()) that returns the inset information for devices with [waterfall displays](https://www.pocket-lint.com/phones/news/149407-waterfall-display-explained-which-phones-curved-edges). 

# Proposal:
Support the `DisplayCutout.getWaterfallInsets` API either in the form of a plugin for Android's DisplayCutout class APIs, or exposing the particular API in the framework.

**Comment by GaryQian** [comment]
Resolved in https://github.com/flutter/engine/pull/20921
