### ISSUE TITLE
Flutter Service Worker not working with Github pages

### ISSUE THREAD

**Issue by Adrieldf** [flutter/flutter#52675]
I have created a app with flutter web and enabled git hub pages with it.
(here is the link: https://github.com/Adrieldf/allthewidgets)
The gh-pages is the branch containing the web app.
This is the error message:

> A bad HTTP response code (404) was received when fetching the script.
>Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://adrieldf.github.io/') with script ('https://adrieldf.github.io/flutter_service_worker.js'): A bad HTTP response code (404) was received when fetching the script.

It only happens on the github pages website, while running locally it works as expected.

**Comment by jonahwilliams** [comment]
Did you upload the build/web directory? It doesn't look like flutter_service_worker.js was actually uploaded to github.

**Comment by Adrieldf** [comment]
I'm using the default git ignore for Flutter and the web folder it is on root of master branch

**Comment by jonahwilliams** [comment]
Are you using the folder that is output as a result of `flutter build web`? See flutter.dev/web for more information

**Comment by Adrieldf** [comment]
Yes, I have a action that it is triggered for every commit and runs these commands:

> flutter config --enable-web
> flutter pub get
> flutter build web --release
> cd build/web
> git init 
> git config --global user.email adriel.idf@gmail.com
> git config --global user.name Adrieldf
> git status
> git remote add origin https://${{secrets.commit_secret}}@github.com/Adrieldf/allthewidgets.git
> git checkout -b gh-pages
> git add --all
> git commit -m "update"
> git push origin gh-pages -f

So that the branch "ph-pages" only haves the build/web folder to load the website on Github Pages..

But if I run the application via Visual Studio Code the website starts normally.

**Comment by jonahwilliams** [comment]
If you're literally get 404s, it means the file likely wasn't updated. Can you share the repo that is being served on github pages?

**Comment by Adrieldf** [comment]
Yes, here is the link https://github.com/Adrieldf/allthewidgets/tree/gh-pages?files=1

**Comment by jonahwilliams** [comment]
Ahh, okay - this was probably https://github.com/flutter/flutter/issues/50580. This might be fixed on master, but you do need to slightly update or regenerate index.html so that there are no leading `/` on the resource paths

**Comment by Adrieldf** [comment]
Thank you. I've deleted that script tag that was referencing the service worker and then the problem was with flutter.dart.js so I've checked on git ignore and it was ignoring *.dart.js, just removing that and everything went back to normal.
