### ISSUE TITLE
Copy Image

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#52678]
It should be possible to copy an image in Flutter.  On native Android and iOS, it's possible to long-press an image and then "Copy Image", but I don't believe this is possible in Flutter.

<img width="250" src="https://user-images.githubusercontent.com/389558/76784793-80e9e900-6771-11ea-8f81-16a47a817f8e.PNG" />

**Comment by EliasDeuss** [comment]
@justinmc There is a package that lasts you do this. https://pub.dev/packages/image_gallery_saver

**Comment by justinmc** [comment]
@EliasDeuss Thanks for that, I wasn't aware!

I think I'll go ahead and close this issue.  It seems possible to implement this feature using the package, even if it's not built in.  If anyone thinks there's something we should build into the framework, feel free to post.
