### ISSUE TITLE
[google_sign_in] has order-dependent test

### ISSUE THREAD

**Issue by enetor** [flutter/flutter#52689]
Internal bug: b/151523341

In google_sign_in_platform_interface_test, "GoogleSignInPlatform.MethodChannelGoogleSignIn is the default instance" fails consistently when the test cases are run in a particular order.

**Comment by stuartmorgan** [comment]
We probably have this issues throughout the plugins; I'll audit all of them. We should be able to grab the default instance before running the tests, and have the test check that stashed instance.
