### ISSUE TITLE
framework stack trace/frame tests don't cover web release/debug mode

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52685]
Specifically, since `flutter test -p chrome` still uses build runner, the actual stack frames someone will see when using `flutter run` is different.

Finally, these tests do not currently cover profile/release mode

**Comment by jonahwilliams** [comment]
More concretely, the frontend_server outputs paths such as:

`packages/flutter/foo.dart`.

While test outputs paths with a package scheme already.

`packages:flutter/foo.dart`

**Comment by grouma** [comment]
What's preventing from migrating the tests over to Frontend Server?

**Comment by grouma** [comment]
@jonahwilliams is this still an issue with the move to the Frontend Server?

**Comment by AAverin** [comment]
I am getting this exception, I think it might be coming when trying to send report to  Crashlytics
```
Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 115 pos 12: 'match != null': Expected  to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
```
