### ISSUE TITLE
Integrate a logging service with Cocoon's flutter app

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#52697]
Currently issues with Cocoon's frontend have to be manually reported, and there is no way of monitoring deployment issues on the frontend side. We should integrate a logging service that can be used to let us know if there are issues with new deployments automatically.

There are print statements throughout the codebase that could be swapped to use something similar to firebase's logging that integrate with the existing GCP infrastructure.

**Comment by CaseyHillers** [comment]
Just to copy over from the PR review comments:
print statements were done due to
(1) the short time frame of the original release of the Flutter build dashboard (4 months)
(2) monitoring not being a high priority of the initial implementation

**Comment by godofredoc** [comment]
@CaseyHillers obsolete?

**Comment by CaseyHillers** [comment]
Marking obsolete. The frontend has a robust test suite which has helped reduce the need for monitoring.

**Comment by CaseyHillers** [comment]
Reopening. We've recently installed the app on Android TVs and are noticing it occasionally crash after a few days. Adding crashlytics will help us figure out where the bug is.
