### ISSUE TITLE
Remove --debugger-module-names flag from frontend_server/tool once all tooling is updated

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52693]
Currently this is switching how module names are computed. Once https://github.com/flutter/flutter/pull/51004 lands this can be made the default.

**Comment by annagrin** [comment]
Note: this will  be done as the cleanup step for fixing https://github.com/flutter/flutter/issues/106727 (https://github.com/dart-lang/webdev/issues/1692)

**Comment by jonahwilliams** [comment]
This was done
