### ISSUE TITLE
flutter-dashboard.appspot.com/benchmarks now only have 10 days of data

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#52692]
We used to have several months of performance metrics to help us triage performance regressions. Now (03/16/2020) we can only see 10 days of data on https://flutter-dashboard.appspot.com/benchmarks.html

Marking it TODAY as it impacts team's capability to respond to performance regressions which are TODAY issues by default.

**Comment by liyuqian** [comment]
CC @godofredoc @CaseyHillers

**Comment by CaseyHillers** [comment]
\cc @keyonghan rolled out recent Datastore changes that may have caused this.

**Comment by keyonghan** [comment]
Will take a look.
