### ISSUE TITLE
Flutter Gold will need to support branching

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#52700]
Currently Gold does not support branching.
This could potentially lead to issues like
- master/realease-branch-x being out of sync with one another
- golden files not being checked in from a hotfix change applied to release branch
- multiple sources of correct golden files stemming from different branches

This will also affect the flutter/cocoon based `flutter-gold` check that all framework tests rely on in pre-submit tests. Individual golden file tests will not fail in test shards anymore, so without the `flutter-gold` check the golden file tests are basically ignored.

**Comment by digiter** [comment]
Triage: what are the remaining tasks?

**Comment by Piinks** [comment]
The latest update was that for now, we won't mind if a release branch gets out of sync with master. This will not block work on release branches, the bot will just complain a bit on release-branch PRs to let you know the branches are out of sync on goldens.

Gold does not currently support branching, so next steps would be dependent on the Gold team. cc/ @kjlubick

I don't think we've had branches get out of sync yet, so AFAIK this is not urgent in any sense given the current experience.

**Comment by Piinks** [comment]
Also, just to clarify, I set up the bot to recognize this case, so any messaging is in context.

**Comment by Piinks** [comment]
@christopherfujino did we decide this was not needed since release branches come off master? If so we can close this.

**Comment by christopherfujino** [comment]
> @christopherfujino did we decide this was not needed since release branches come off master? If so we can close this.

Yes, this seems to be completely covered. Thanks!
