### ISSUE TITLE
CustomPaint docs need clarification on Size

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#52707]
The `CustomPaint` docs say that `CustomPaint` will size itself regarding its `child` or its `size`, but it also says that the default `size` is `Size.zero`.

I can use `CustomPaint` inside a `Stack` and get the full size of the `Stack` without any `child`. So I think `CustomPaint` when set to `Size.zero` will size itself to the parents boundaries instead? I am not sure, I just know that the behavior I am seeing doesn't follow the docs.

**Comment by goderbauer** [comment]
https://master-api.flutter.dev/flutter/widgets/CustomPaint-class.html

We should clarify this.

**Comment by Chinmay-KB** [comment]
> Still valid since the docs where not updated since this bug was filed and still confused.
> 
> <img alt="Screen Shot 2020-09-03 at 13 59 24" width="923" src="https://user-images.githubusercontent.com/67424416/92117937-bcdf3c00-eded-11ea-8970-4e90cf1676a4.png">

Is it clear if it is a bug or this is how it is supposed to work and the docs should be updated?

**Comment by pedromassangocode** [comment]
This is a documentation issue.

**Comment by danagbemava-nc** [comment]
![Screenshot 2023-03-07 at 11 34 44](https://user-images.githubusercontent.com/88313112/223410862-e6c410ac-5eab-4a09-a4cd-b2b42d326238.png)

https://master-api.flutter.dev/flutter/widgets/CustomPaint-class.html

Looks like the docs have not been updated yet. 

Updating labels
