### ISSUE TITLE
Icons.airplanemode_active isn't symetric 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#52713]
I have an eye for detail, if something is out of place it screams to me :sweat_smile:, `Icons.airplanemode_active` isn't symetric:

![image](https://user-images.githubusercontent.com/8120472/76816710-b2010280-67df-11ea-9a0d-81c4b6f89b72.png)

As can be seen, `Icons.airplanemode_active` is a bit to the left, thus any line placed on its center appears to be on its right. This can be confirmed by the distances of the wing tips to the box enclosing the icon:

![image](https://user-images.githubusercontent.com/8120472/76816861-1754f380-67e0-11ea-9fa0-a8432ec6834b.png)

**Comment by dnfield** [comment]
@willlarche

**Comment by willlarche** [comment]
I'll forward this to the icon artists but they won't comment here so I'm going to close the ticket.

**Comment by feinstein** [comment]
Ok but then how will we track the deployment of the fix?

**Comment by willlarche** [comment]
If they write back that they intend to change it and communicate when we can expect that to happen, then I'll reopen the ticket. But we don't like to keep tickets open that are not actionable. And if they aren't willing to change the art or if they don't communicate back at all, it's not actionable. That's the most likely scenario here so I'm going to keep it closed until I hear back from them.

**Comment by feinstein** [comment]
Ok, thanks Will.

**Comment by willlarche** [comment]
Nevermind! Good news. They said they already corrected the master. Does the icon in material.io/icons look different than this one?

**Comment by feinstein** [comment]
Wow that was fast hahah I was 99% certain it would be ignored :D

Let me confirm it to you...

**Comment by feinstein** [comment]
The SVG icon at https://material.io/resources/icons/?search=airplanemode_active&icon=airplanemode_active&style=baseline looks perfect under Adobe XD, but I checked it against the "old" SVG icon in my mockup and they look the same, so I can't see any changes. 

I have to add that this happens not only for `Icons.airplanemode_active` but also for `Icons.local_airport` and probably all the other icons that have this same image.

**Comment by HansMuller** [comment]
Thanks for submitting this issue, we appreciate the attention to detail!

**Comment by TahaTesser** [comment]
<img width="234" alt="Screenshot 2020-07-08 at 5 31 04 PM" src="https://user-images.githubusercontent.com/48603081/86916177-d4c57700-c140-11ea-8e8b-72c0d24f072e.png">


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (4 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (3 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by willlarche** [comment]
We're working on rolling in the next version of icons. It's slightly delayed because of an issue on the art side. I'll let you know when to test this again.
