### ISSUE TITLE
Why some widget don't have a const constructor, like Container, GestureDetector, Row ?

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#52710]
I have find #35859 and it's PR #35860,

I didn't see any reason why not have const for `Container`, `GestureDetector`,  `Stack`, `Row` and so on.

**Comment by jerryzhoujw** [comment]
Looks like lots of super are not const. change them seems need do lots of work.

**Comment by dnfield** [comment]
We try to add const constructors wherever we can.  Some classes don't have them because there are asserts or calculations done in initializers that aren't compatible with const.

**Comment by dnfield** [comment]
For example, in `Container` we call methods on some of the parameters that do debug assertions, which are seen as more valuable than having a const ctor, and unfortunately are not compatible with a const constructor.
