### ISSUE TITLE
Debug error

### ISSUE THREAD

**Issue by Psyche47** [flutter/flutter#52724]
Launching lib\main.dart on POCOPHONE F1 in debug mode...

```bash
FAILURE: Build failed with an exception.
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by Psyche47** [comment]
**Output of Flutter doctor -v**
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Windows, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\sdk-windows\tools\bin
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Borshon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • POCOPHONE F1 • 192.168.0.100:5555 • android-arm64 • Android 10 (API 29)

**Comment by TahaTesser** [comment]
Hi @Psyche47 
Take a look at this possible [solution](https://github.com/flutter/flutter/issues/41350#issuecomment-570743749)
Thank you

**Comment by Psyche47** [comment]
> Hi @Psyche47
> Take a look at this possible [solution](https://github.com/flutter/flutter/issues/41350#issuecomment-570743749)
> Thank you

Not working.

**Comment by TahaTesser** [comment]
Hi @Psyche47 
Please execute `flutter clean` from root of your project and provide `flutter run --verbose`?
Thank you

**Comment by Psyche47** [comment]
> Hi @Psyche47
> Please execute `flutter clean` from root of your project and provide `flutter run --verbose`?
> Thank you

[  +76 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +147 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +82 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +17 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +75 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +185 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +984 ms] executing: C:\sdk-windows\platform-tools\adb.exe devices -l
[+1342 ms] Exit code 0 from: C:\sdk-windows\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[        ] * daemon not running; starting now at tcp:5037
           * daemon started successfully
[  +28 ms] No supported devices connected.
[  +33 ms] "flutter run" took 2,451ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by TahaTesser** [comment]
Hi @Psyche47 
Make sure you're connected to a device or emulator
```
* daemon started successfully
[ +28 ms] No supported devices connected.
[ +33 ms] "flutter run" took 2,451ms.`
```
Thank you

**Comment by Psyche47** [comment]
> Hi @Psyche47
> Make sure you're connected to a device or emulator
> 
> ```
> * daemon started successfully
> [ +28 ms] No supported devices connected.
> [ +33 ms] "flutter run" took 2,451ms.`
> ```
> 
> Thank you

I have connected my device and ran flutter run -verbose

[  +78 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +173 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +35 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +3 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +87 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +24 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +77 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[ +445 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[+1044 ms] executing: C:\sdk-windows\platform-tools\adb.exe devices -l
[  +46 ms] Exit code 0 from: C:\sdk-windows\platform-tools\adb.exe devices -l
[   +4 ms] List of devices attached
           f2428337               device product:beryllium model:POCOPHONE_F1 device:beryllium transport_id:3
[  +49 ms] C:\sdk-windows\platform-tools\adb.exe -s f2428337 shell getprop
[ +196 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +92 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1655 ms] Generating F:\new_project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +158 ms] ro.hardware = qcom
[ +800 ms] Launching lib\main.dart on POCOPHONE F1 in debug mode...
[  +57 ms] executing: C:\sdk-windows\platform-tools\adb.exe -s f2428337 shell -x logcat -v time -t 1
[ +277 ms] Exit code 0 from: C:\sdk-windows\platform-tools\adb.exe -s f2428337 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           03-20 21:47:25.786 I/MiuiNetworkPolicy( 2022): isMLEnabled state:7,uid:10081,connect:DISCONNECTED
[  +28 ms] executing: C:\sdk-windows\platform-tools\adb.exe version
[   +6 ms] executing: C:\sdk-windows\platform-tools\adb.exe -s f2428337 logcat -v time -T 03-20 21:47:25.786
[  +82 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\sdk-windows\platform-tools\adb.exe
[  +12 ms] executing: C:\sdk-windows\platform-tools\adb.exe start-server
[  +44 ms] Building APK
[  +76 ms] Running Gradle task 'assembleDebug'...
[  +12 ms] gradle.properties already sets `android.enableR8`
[  +15 ms] Using gradle from F:\new_project\android\gradlew.bat.
[  +38 ms] executing: [F:\new_project\android\] F:\new_project\android\gradlew.bat -Pverbose=true
-Ptarget=F:\new_project\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+25751 ms] Welcome to Gradle 5.6.2!
[  +91 ms] Here are the highlights of this release:
[   +4 ms]  - Incremental Groovy compilation
[   +2 ms]  - Groovy compile avoidance
[   +2 ms]  - Test fixtures for Java projects
[   +5 ms]  - Manage plugin versions via settings script
[   +2 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+22103 ms] Starting a Gradle Daemon, 1 busy and 1 incompatible Daemons could not be reused, use --status for details
[+173717 ms] > Task :app:compileFlutterBuildDebug
[   +8 ms] [ +123 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +450 ms] [ +533 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] [        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +2 ms] [   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +90 ms] [ +132 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +95 ms] [  +41 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +99 ms] [ +184 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +98 ms] [ +111 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[ +297 ms] [ +269 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +100 ms] [  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +97 ms] [ +116 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] [  +43 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +373 ms] [ +358 ms] Initializing file store
[ +300 ms] [ +283 ms] kernel_snapshot: Starting due to {}
[ +300 ms] [ +295 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
F:\new_project\.packages --output-dill F:\new_project\.dart_tool\flutter_build\50846e866415dae971c98524788f77f8\app.dill
--depfile F:\new_project\.dart_tool\flutter_build\50846e866415dae971c98524788f77f8\kernel_snapshot.d
package:new_project/main.dart
[+50502 ms] [+50556 ms] kernel_snapshot: Complete
[+5996 ms] [+5945 ms] debug_android_application: Starting due to {}
[+6299 ms] [+6303 ms] debug_android_application: Complete
[+1100 ms] [+1123 ms] Persisting file store
[ +100 ms] [ +145 ms] Done persisting file store
[  +99 ms] [  +12 ms] build succeeded.
[ +100 ms] [ +116 ms] "flutter assemble" took 65,340ms.
[+1500 ms] > Task :app:compileFlutterBuildDebug FAILED
[+2904 ms] FAILURE: Build failed with an exception.
[  +12 ms] * Where:
[   +2 ms] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
[   +2 ms] * What went wrong:
[   +7 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[   +2 ms] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +3 ms] * Try:
[  +10 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +8 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 4m 49s
[  +42 ms] 1 actionable task: 1 executed
[+4617 ms] Running Gradle task 'assembleDebug'... (completed in 297.4s, longer than expected)
[  +81 ms] "flutter run" took 302,337ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by Psyche47** [comment]
Bump!

**Comment by jonahwilliams** [comment]
Hi @Psyche47 , try running the following command from your app's `android` directory:
```
gradlew.bat --stacktrace -Pverbose=true
-Ptarget=F:\new_project\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
```

**Comment by jonahwilliams** [comment]
That should give the full Gradle stacktrace output
