### ISSUE TITLE
how to stop these overwhelming message D/eglCodecCommon(10813): setVertexArrayObject: set vao to 7 (7) 32 53

### ISSUE THREAD

**Issue by jpainam** [flutter/flutter#52723]
flutter --version
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (5 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```
How to stop these messages when i run my application on debug mode It's overwhelming and hide my own message and any error
```
D/eglCodecCommon(10813): setVertexArrayObject: set vao to 7 (7) 32 53
```

**Comment by chinmaygarde** [comment]
Those messages are not from Flutter.

**Comment by erperejildo** [comment]
> Those messages are not from Flutter.

where is that from? I get the same messages in a new project

**Comment by jpainam** [comment]
@chinmaygarde you didn't answer the question and your message doesn't help in any ways.

**Comment by chinmaygarde** [comment]
Flutter logs to syslog. So do other applications (including system services) running on the device. My comment was alluding to the fact this particular log was not introduced by the Flutter engine or the framework. Because of this, this isn't actionable.
