### ISSUE TITLE
Exception: Source directory "/Users/my_projects/project_name/build/ios/Release-iphoneos/Runner.app" does not exist, nothing to copy

### ISSUE THREAD

**Issue by dev-shanghai** [flutter/flutter#52721]
## Command
```
flutter build ios --release --no-codesign -t lib/main_1.dart --flavor client1
[flutter_02.log](https://github.com/flutter/flutter/files/4342091/flutter_02.log)

```

## Steps to Reproduce
1. Open terminal and type `flutter pub get`
2. CD ios/ and type `pod install`
3. Type this in lib/ folder `flutter build ios --release --no-codesign -t lib/main_1.dart --flavo`r client1
4. It generates this problem for me in VS Code, although from Xcode I can run debug and publish all the respective flavors of our app.
5. This command `flutter run -d cc13d74b13a24c0023247c602a49a44444e373 -t lib/main_1.dart` successfully launches the app on iPhone device. 

NOTE: The following configuration in launch.json of the VS code also fails to install app on the iPhone device. 

```
 {
            "name": "Flutter Client1 iOS",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release",
            "program": "lib/main_1.dart",
            "args": [
                "--flavor",
                "client1"
            ]
  },
```

## Logs
_Exception: Exception: Source directory "/Users/my_apps/project_name/build/ios/Release-iphoneos/Runner.app" does not exist, nothing to copy
```
#0      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:70:7)
#1      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:554:15)
<asynchronous suspension>
#2      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:637:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel master, v1.14.2, on Mac OS X 10.15.3 19D76, locale en-AE)
    • Flutter version 1.14.2 at /Users/development/flutter
    • Framework revision ec1044a877 (8 weeks ago), 2020-01-17 19:19:33 -0800
    • Engine revision ecc74c966d
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/innovent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/innovent/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • WT FR323 7 • 190804b3                                 • android-arm64 • Android 7.0 (API 24)
    • iPhone     • cc13d74b13a24c0023247c602a49ab915b40e373 • ios           • iOS 12.4.5

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
connectivity-0.4.6+1
custom_horizontal_calendar-0.1.3
device_info-0.4.1+4
devicelocale-0.2.1
firebase_messaging-6.0.9
flutter_local_notifications-0.8.4+3
flutter_statusbarcolor-0.2.3
fluttertoast-3.1.3
geolocator-5.1.5
google_api_availability-2.0.1
google_maps_flutter-0.5.21+15
image_cropper-1.1.1
image_picker-0.6.2+3
location-2.3.5
location_permissions-2.0.3
package_info-0.4.0+13
path_provider-1.5.1
shared_preferences-0.5.6
shared_preferences_macos-0.0.1+3
shared_preferences_web-0.1.2+2
sqflite-1.2.0
stripe_payment-1.0.6
url_launcher-5.4.1
url_launcher_macos-0.0.1+2
url_launcher_web-0.1.0+2

**Comment by dev-shanghai** [comment]
[flutter_02.log](https://github.com/flutter/flutter/files/4342126/flutter_02.log)

**Comment by dev-shanghai** [comment]
When you initially build `--release` it miserably fails. This is actually stopping me to implement fast-lane. 

`flutter run --debug` and flutter run --release` both works fine. 
`flutter build ios --release`  or even `flutter build ios --debug` fails with unexpected errors. 


**RESULT:**
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building ae.abudhabi.wathiq.parent for device (ios-release)...
Running pod install...                                              7.5s
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                    64.0s
 ├─Generating dSYM file...                                   0.3s
 ├─Stripping debug symbols...                                0.1s
 ├─Assembling Flutter resources...                           4.0s
 └─Compiling, linking and signing...                         9.8s
Xcode build done.                                           144.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


 6 warnings generated.
    Non-fat binary /Users/ass/Desktop/project_name/build/ios/Release-iphoneos/Runner.app/Frameworks/protobuf.framework/protobuf is
    not armv7. Running lipo -info:
    Non-fat file: /Users/ass/Desktop/project_name/build/ios/Release-iphoneos/Runner.app/Frameworks/protobuf.framework/protobuf is
    architecture: arm64
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by jmagman** [comment]
What files are in /Users/my_apps/project_name/build/ios/Release-iphoneos/?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
