### ISSUE TITLE
microbenchmarks traverseIterableList_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52735]
Around this engine roll.  https://github.com/flutter/flutter/pull/52438, or perhaps earlier, note rise at beginning of clipping:

![Screen Shot 2020-03-17 at 7 55 35 AM](https://user-images.githubusercontent.com/1435716/76868861-b8fe3400-6824-11ea-83e5-577bf3759e57.png)

**Comment by jason-simmons** [comment]
This changed due to https://github.com/dart-lang/sdk/commit/2a8127dbfad894d511cd1ccd866697f3ff6469bd.  Similar to another microbenchmark (https://github.com/flutter/flutter/issues/52473)

The benchmark should be rebaselined.

**Comment by kf6gpe** [comment]
Rebaselined. Closing.
