### ISSUE TITLE
Exception stack traceback truncation unhelpful and unproductive for solving problems

### ISSUE THREAD

**Issue by remoteportal** [flutter/flutter#52732]
Please don't truncate stack traceback for exceptions!

I've spent an entire day looking through Flutter source code trying to figure out how to NOT truncate the trace back (to no avail). 

## Steps to Reproduce

I'm NOT looking for you to solve my specific problem.
I'm *am* asking you STOP HINDERING ME from solving the problem myself!

Looking below, if you didn't cut-off the trace back, I'd instantly be able to see the root cause.
The unnecessary truncation is causing a 60 second problem to be nearly an unsolvable problem because you are hiding the info that Flutter developers need.

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
setState() or markNeedsBuild() called when widget tree was locked.

This _ModalScope<dynamic> widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#6d889]
  state: _ModalScopeState<dynamic>#a176a
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3901:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3911:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1168:14)
#3      _ModalScopeState._routeSetState (package:flutter/src/widgets/routes.dart:664:5)
#4      ModalRoute.setState (package:flutter/src/widgets/routes.dart:784:30)
...
```

```
*** flutter doctor -v

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at E:\Src\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pete\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Mi 9T                     • 844fb80a      • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by dnfield** [comment]
I don't think that has made it to stable yet. Plus it would have said how many frames it elided.

@remoteportal can you share code that causes a stack trace that gets truncated like this?

**Comment by darshankawar** [comment]
Hi @remoteportal,
Can you please confirm if you still experience this issue on latest Stable (1.20.2) ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by PixelToast** [comment]
This was bugging me for awhile, the culprit is that stack traces are sometimes presented as `DiagnosticsStackTrace`, which is subject to subtree truncation since each line is its own property.
