### ISSUE TITLE
CanvasKit saveLayer(null, paint) fails

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#52745]
This is fixed by https://skia-review.googlesource.com/c/skia/+/277399 - when that eventually rolls through to the engine, we'll have to update the callsite so that we do `canvas.saveLayer(paint)` if the rect is null.

/cc @hterkelsen @yjbanov 
/cc @kjlubick fyi

**Comment by qaisarhayat12** [comment]
Nice https://htwpk.blogspot.com/2020/04/dirilish-ertughral.html?m=1
