### ISSUE TITLE
Stabilize Linux embedding/runner boundary

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#52749]
There is preliminary support for `flutter create` for Linux, but it's explicitly unstable. We need to make firm decisions on the embedding API and the build system/tool interaction so that we can declare it stable (meaning we expect that the output of `flutter create` will continue working with future versions of Flutter, rather than need to be recreated frequently) and remove the warnings and checks related to the current instability.

Blockers (this will be a living list):
- [x] #30729
- [x] #52744
- [x] #52751

**Comment by robert-ancell** [comment]
The only potential breaking changes I can see at the moment are related to multi-window support. Specifically `fl_plugin_registrar_get_view()` might become deprecated in the future as we have multiple views to control. It can probably be set to return the "primary" view using the new API or `nullptr` if no views are available. We can mark it as deprecated so it generates compile warnings and potentially remove at a release milestone.

The template is also likely to change regarding multiple views, which would require developers to update this.

**Comment by stuartmorgan** [comment]
Yes, multi-window is going to be a significant change for all the desktop platforms; that's one we definitely aren't going to be able to do before alpha.

One question I had was about Wayland; will that detection be internal to the framework, or will we need to update any public API to allow picking which mode to use?

**Comment by robert-ancell** [comment]
> One question I had was about Wayland; will that detection be internal to the framework, or will we need to update any public API to allow picking which mode to use?

That should be all internal, though we may want to expose which backend is active to the client? I can't think of any particular use for that, other than to make use of some Wayland specific plugin.

**Comment by stuartmorgan** [comment]
Since that's just an addition, it sounds like we're in good shape. If the audit looked good to you, I'm happy to close this. I'm not aware of anything at the build level that I think needs a breaking change either (I'd like to move some CMake files into the engine, but that would be an 'only applies to new apps' change rather than a 'breaks existing apps' change.)
