### ISSUE TITLE
GTK: Provide high-level plugin APIs

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#52744]
The GTK embedding is using a GObject-based interface, rather than the simple-C-plus-C++-wrapper approach of the GLFW (and current Windows) embedding. That means that we will likely need to re-implement the plugin registrar, message channel, method channel, etc. using GObject rather than C++ for the new Linux embedding in order to have a coherent API.

We can wait until the GTK embedding is a bit further along to decide, but I expect that's what we'll end up wanting to do.

**Comment by stuartmorgan** [comment]
Retitling to track having the API in general, either via a new GObject API or by wiring up the existing C++ wrappers.

**Comment by robert-ancell** [comment]
I estimate this is about 3 days work.

**Comment by stuartmorgan** [comment]
Other than event channel, which isn't a blocker, this is done.
