### ISSUE TITLE
Update documentation when we make --delete-tostring-package-uri defaulted for certain modes

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#52759]
https://github.com/flutter/engine/pull/17068 will add a new option to the frontend compiler to let us remove toString options, along with an annotation to mark a method as keep even if we applied the flag.

We should update the docs on the annotation if and when we make this option on by default for, e.g. release or profile modes, to reflect when it's on.

/cc @zanderso @jonahwilliams

**Comment by pedromassangocode** [comment]
Can you confirm where to verify if the docs were updated already or not?

**Comment by dnfield** [comment]
I'm not sure we ever turned this on by default. @jonahwilliams do you know?

**Comment by dnfield** [comment]
Relevant docs to update are here: https://github.com/flutter/engine/blob/d85cb10707a29dae9a437a1cf6bfa2e28860d3f7/lib/ui/annotations.dart#L11

If we didn't turn this on by default, then we can probably close this. This option is used by some customers, but AFAICT they have to pass it in themselves via some special flags when building the app.

**Comment by jonahwilliams** [comment]
We don't have this on by default. Before we do this, we'd need to provide it as an opt-in and gather feedback - otherwise users might be surprised.

**Comment by dnfield** [comment]
It's currently possible to opt-in with the --extra-front-end-options flag I believe. It's just cumbersome to use. We have some customers internally at Google using it though.

I'm inclined to leave it as is for now, unless we get more demand for it.
