### ISSUE TITLE
ListView Shift + Scroll behaves differently between mouse wheel and track pad

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#52767]
For context, I created a custom ListView for which you can pass in a PointerSignalEvent handler (see https://github.com/flutter/flutter/issues/35723).

In my handler, I have custom behavior for Shift + Scroll. On a laptop trackpad (Mac), shift + scroll is WAI and executes the behavior I specified in the handler.

However, with a physical mouse wheel, shift + scroll does not execute the behavior in my handler, and instead scrolls the list horizontally.

Mouse wheel scroll and trackpad scroll should be treated the same way as far as the user is concerned.

As a related issue, we cannot differentiate between scroll devices (track pad or mouse wheel) by the meta data in the PointerScrollEvent (see https://github.com/flutter/flutter/issues/52762).

**Comment by kenzieschmoll** [comment]
@stuartmorgan

**Comment by stuartmorgan** [comment]
This is an OS-level behavior, and WAI. Shift+scroll wheel means "scroll horizontally" on macOS, and macOS applications receive horizontal scroll events when that happens. This is not the case for trackpads because if you want to scroll horizontally on a trackpad, you just move horizontally.

> Mouse wheel scroll and trackpad scroll should be treated the same way as far as the user is concerned.

Try your steps in any other application on macOS; you'll see the same behavior. Breaking platform expectations on what shift+different scroll input devices would be very undesirable.

**Comment by kenzieschmoll** [comment]
I see. Is it also WAI for shift+scroll to scroll horizontally on the web? I see the same behavior there.

**Comment by kenzieschmoll** [comment]
commented on https://github.com/flutter/flutter/issues/52762, but I can get around this if I can access metadata telling whether the event was from trackpad or from mouse wheel.

For more context, I am implementing scroll-to-zoom behavior in the DevTools timeline. Scrolling vertically (track pad or mouse wheel) will zoom the chart in and out (similar to the Chrome DevTools timeline). Shift + scroll will vertically scroll the chart up and down. This works great on a track pad, but many users will be using an external mouse with a mouse wheel, so we need this functionality to work for both.

**Comment by stuartmorgan** [comment]
> Is it also WAI for shift+scroll to scroll horizontally on the web?

I don't know which kind of scroll you mean here, so I'm not sure how to answer.

> I can get around this

What I'm saying is that "getting around this" as you are describing it means breaking fundamental platform behaviors; I strongly encourage you not to think of that as a desirable outcome, and instead rethink how you're designing this UX.

> if I can access metadata telling whether the event was from trackpad or from mouse wheel

What if it's a mouse that can send horizontal scroll events (which exist)? What if it's neither, and the scroll event is coming from some other device like a USB knob or a stylus with a scrolling affordance?

**Comment by kenzieschmoll** [comment]
>> Is it also WAI for shift+scroll to scroll horizontally on the web?

> I don't know which kind of scroll you mean here, so I'm not sure how to answer.

I mean mouse wheel shift + scroll.

> What I'm saying is that "getting around this" as you are describing it means breaking fundamental platform behaviors; I strongly encourage you not to think of that as a desirable outcome, and instead rethink how you're designing this UX.

Generally, I would agree. However, I think developer tools can at times have their own UX "norms" that may not always play by the general rules of a "typical" UI. @jacob314 @cobblest @InMatrix for thoughts.

> What if it's a mouse that can send horizontal scroll events (which exist)? What if it's neither, and the scroll event is coming from some other device like a USB knob or a stylus with a scrolling affordance?

A mouse that can send horizontal scroll events would still have type 'mouse'. An "other" device could have type 'other' or 'unknown' or similar. As long as we cover the core two use cases 'mouse' and 'trackpad' accurately, that would cover most users.

**Comment by stuartmorgan** [comment]
> > > Is it also WAI for shift+scroll to scroll horizontally on the web?
> 
> > I don't know which kind of scroll you mean here, so I'm not sure how to answer.
> 
> I mean mouse wheel shift + scroll.

Then on macOS, yes. Again, this isn't an application behavior, it's an OS behavior; a browser will receive a horizontal scroll event from the OS just like any other application.

**Comment by stuartmorgan** [comment]
> However, I think developer tools can at times have their own UX "norms" that may not always play by the general rules of a "typical" UI.

I would agree in some cases, but we're talking about input device behavior, not more abstract UX. Let me try to rephrase my concern; in the original issue description you said:

> Mouse wheel scroll and trackpad scroll should be treated the same way as far as the user is concerned.

I agree completely. But the behavior you describing wanting is, from my perspective, for horizontal scrolling with a mouse wheel (which is what holding down shift while using a mouse wheel *means*, at the toolkit level) to behave differently than scrolling horizontally with a trackpad.

**Comment by kenzieschmoll** [comment]
>  the behavior you describing wanting is, from my perspective, for horizontal scrolling with a mouse wheel (which is what holding down shift while using a mouse wheel means, at the toolkit level) to behave **differently** than scrolling horizontally with a trackpad.

Just the opposite - I want shift+mouse_wheel_scroll to behave the **same** as shift+track_pad_scroll for a specific graph in DevTools.

So if I can get data about the type of device emitting the scroll (track pad or mouse), I could write some logic like this:
```
if (isShiftPressed && isMouseWheelEvent && isScrollHorizontal) {
  // Invert the offset and manually scroll vertically (like we do for shift + verticalScroll on a trackpad.
}
```

This does get a little tricky because a user could actually be doing a shift + horizontal scroll from the mouse wheel. We could either
a) ignore this case as scrolling horizontally with a mouse wheel without shift would produce the desired results (regular horizontal scroll). OR
b) request further information (if possible) to see whether or not the scrolling offset was overridden by OS logic (e.g. flipping the offset of a shift + vertical scroll to be a horizontal delta)

**Comment by stuartmorgan** [comment]
> Just the opposite - I want shift+mouse_wheel_scroll to behave the **same** as shift+track_pad_scroll for a specific graph in DevTools.

I understand that you see it that way. I don't at all, and I think many users would have the same viewpoint on this that I do and would find it confusing.

> So if I can get data about the type of device emitting the scroll

Even if we provided this information for desktop (which I'm still not in favor of), how do you plan to handle this for Flutter for Web? As far as I know only the abstraction ('the user scrolled horizontally') not the raw input details ('the mechanical process by which they scrolled horizontally involved a mouse and the shift key') is provided to the browser at all.

**Comment by kenzieschmoll** [comment]
> only the abstraction ('the user scrolled horizontally') not the raw input details ('the mechanical process by which they scrolled horizontally involved a mouse and the shift key') is provided to the browser at all.

Good to know. Then if the information is not available, sounds like getting the type of device emitting the scroll wouldn't be an option for Flutter Web.

Talked to @jacob314 a bit offline. It sounds like we may want to use a different modifier key than shift. `option` / `alt` seems like a better option than shift.

**Comment by kenzieschmoll** [comment]
Going to close this issue then since it seems that the difference between shift + mouse_wheel_scroll and shift + track_pad_scroll is intentional. Thanks for the thoughtful discussion @stuartmorgan!
