### ISSUE TITLE
PointerDeviceKind should differentiate between mouse and trackpad (laptop)

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#52762]
For PointerScrollEvent handling, delta values can vary greatly between a two finger trackpad scroll and a physical mouse wheel scroll. It would be nice if `PointerSignalEvent.kind` differentiated between these two types of scrolls.

**Comment by stuartmorgan** [comment]
Can you elaborate on why you want to distinguish based on the source rather than the deltas? There are, for instance, mice that send trackpad-like high-resolution scroll events, so exposing this seems likely to cause people to do the wrong thing in their application code.

**Comment by kenzieschmoll** [comment]
Understandable. Aside from the delta's I would also like to have this information to manipulate the behavior of shift+scroll (see https://github.com/flutter/flutter/issues/52767).

**Comment by stuartmorgan** [comment]
Closing based on discussion in the other issue linked above.
