### ISSUE TITLE
Application Name not showing up into recents app panel, weird artifacts going on with the strings

### ISSUE THREAD

**Issue by TheWCKD** [flutter/flutter#52779]
Hello,

I'm encountering an issue after building by release apk in Flutter. The app name won't show up into recents app panel like it does for any other app, it just seems like it's null or empty (check my app vs Chrome in the screenshots below). Here's the proof below. I have also the bug of the notifications not showing the icon I setup, but instead they show up a red square icon. The builds were working fine before I upgraded to latest flutter master release, but I also reverted to the stable channel and I'm encountering the same issue. Since the last update I've also encountered some weird artifacts with all the strings in the app.

![image](https://user-images.githubusercontent.com/37099416/76914418-eac5d800-68c2-11ea-9414-21b418556a26.png)
![image](https://user-images.githubusercontent.com/37099416/76914421-ed283200-68c2-11ea-9368-19a78d7ddf26.png)

I'm currently using this version of Flutter and encountering the issue:
Flutter (Channel master, v1.15.23-pre.24, on Microsoft Windows [Version 10.0.18362.720], locale en-US)

Any help is appreciated, thanks!

**Comment by TahaTesser** [comment]
Hi @TheWCKD 

I wasn't able to reproduce this on 

### flutter doctor -v

```
[√] Flutter (Channel master, v1.15.22-pre.24, on Microsoft Windows [Version 10.0.19041.153], locale en-US)
    • Flutter version 1.15.22-pre.24 at C:\Code\flutter_master
    • Framework revision aba0e2dc8f (4 days ago), 2020-03-13 23:21:03 -0400
    • Engine revision e48761e5bb
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 c3a0bb086a)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Code\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome           • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

![Screenshot_20200318-144111_One UI Home](https://user-images.githubusercontent.com/48603081/76944205-9f451580-6926-11ea-9cd6-91a024a2d371.png)

**Comment by TheWCKD** [comment]
@TahaTesser That's not the latest master, check my version it's an increment of yours.

**Comment by TahaTesser** [comment]
Hi @TheWCKD 
My bad, i confused my version with your version earlier but trying on `Flutter (Channel master, v1.15.23-pre.27` also doesn't seem to reproduce the issue. **updated the comment above with screenshot**

**Comment by TheWCKD** [comment]
@TahaTesser Then I don't know what may have been causing these issues for me. 😔 Do you have any recommendations or at least similar issues so that I can took a look at them?

**Comment by TahaTesser** [comment]
Hi @TheWCKD 
Do you give `title` property in your `MaterialApp`?
Take a look at this [comment](https://github.com/flutter/flutter/issues/30161#issuecomment-477905997)
Thank you

**Comment by TheWCKD** [comment]
> Hi @TheWCKD
> Do you give `title` property in your `MaterialApp`?
> Take a look at this [comment](https://github.com/flutter/flutter/issues/30161#issuecomment-477905997)
> Thank you

Thank you, that seems to work fixing the app name issue, but now I have managed to get the artifact issue appear again, I don't know how and why it does appear, but here's the screenshots.
Have you ever encountered this type of issue ever?

![image](https://user-images.githubusercontent.com/37099416/76953939-3191ed00-6918-11ea-8ead-1765061a1e22.png)
![image](https://user-images.githubusercontent.com/37099416/76953956-36ef3780-6918-11ea-8651-17704d54d812.png)

And also it seems like when I run flutter build --release the notification icon issue won't appear, but if I run flutter build to build the fat apk then install it on my device it reapears like you can see in the screenshots below. Any help? Thanks a lot!

![image](https://user-images.githubusercontent.com/37099416/76954190-a1a07300-6918-11ea-85ed-32b8de624b97.png)
![image](https://user-images.githubusercontent.com/37099416/76954214-aa914480-6918-11ea-9aaf-6ce8bf7fb114.png)

**Comment by TahaTesser** [comment]
Hi @TheWCKD 
As "artifact issue" isn't related to this opened, i am gonna close this one 
Please create a new issue and provide necessary details
Thank you
