### ISSUE TITLE
[pigeon] Add pigeon-using sample to samples repository

### ISSUE THREAD

**Issue by xster** [flutter/flutter#52777]
Create usage examples of data passing with data classes using pigeon in https://github.com/flutter/samples/tree/master/add_to_app. 

We should also add Kotlin/Swift code to check nullable ergonomics. 

cc @gaaclarke @RedBrogdon

**Comment by pedromassangocode** [comment]
Hi @xster 
This seems to be fixed by https://github.com/flutter/samples/pull/698? Pigeon package is being used by the [books example](https://github.com/flutter/samples/tree/master/add_to_app/books/flutter_module_books).

Can you please confirm? 
Thank you

**Comment by RedBrogdon** [comment]
There's a Flutter module and an Android sample, but no iOS sample. Not sure if this issue is meant to cover iOS as well.

**Comment by gaaclarke** [comment]
Yes, we should have an iOS example, too.  The only iOS sample we have is for plugins and was banished from the samples repo (https://github.com/gaaclarke/pigeon_plugin_example)  I can look into implementing the books example for iOS, I should have time now.
