### ISSUE TITLE
My preference become null after i try to hot restart or reopening an app

### ISSUE THREAD

**Issue by gianalmada** [flutter/flutter#52783]
is it normal for shared preference reset the value after i try to hot restart or reopening an app ? because my preference become null after i do that.

Thank you.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by gianalmada** [comment]
> 
> 
> Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

oke thank you
