### ISSUE TITLE
When I used flutter_webview plugin on Android platform, Longpress gesture will cause lags.

### ISSUE THREAD

**Issue by TPQuietBro** [flutter/flutter#52786]
## Steps to Reproduce
1. Run app and finish loading url on Android device.
2. Long press  and slide a bit distance.
3. Release your finger ,then slide again.
4. Lags happened.

In source file 'webview_android.dart', after deleting code 'onLongPress: () {}' lags would be fixed.

class AndroidWebView implements WebViewPlatform {
  @override
  Widget build({
    BuildContext context,
    CreationParams creationParams,
    @required WebViewPlatformCallbacksHandler webViewPlatformCallbacksHandler,
    @required WebViewDSBridgeCallbacksHandler dsBridgeCallbacksHandler,
    WebViewPlatformCreatedCallback onWebViewPlatformCreated,
    Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers,
  }) {
    assert(webViewPlatformCallbacksHandler != null);
    return GestureDetector(
      // We prevent text selection by intercepting the long press event.
      // This is a temporary stop gap due to issues with text selection on Android:
      // https://github.com/flutter/flutter/issues/24585 - the text selection
      // dialog is not responding to touch events.
      // https://github.com/flutter/flutter/issues/24584 - the text selection
      // handles are not showing.
      // TODO(amirh): remove this when the issues above are fixed.
      // onLongPress: () {},
      excludeFromSemantics: true,
      child: AndroidView(
        viewType: 'plugins.flutter.io/webview',
        onPlatformViewCreated: (int id) {
          if (onWebViewPlatformCreated == null) {
            return;
          }
          onWebViewPlatformCreated(MethodChannelWebViewPlatform(
              id, webViewPlatformCallbacksHandler,dsBridgeCallbacksHandler));
        },
        gestureRecognizers: gestureRecognizers,
        // WebView content is not affected by the Android view's layout direction,
        // we explicitly set it here so that the widget doesn't require an ambient
        // directionality.
        layoutDirection: TextDirection.rtl,
        creationParams:
            MethodChannelWebViewPlatform.creationParamsToMap(creationParams),
        creationParamsCodec: const StandardMessageCodec(),
      ),
    );
  }

  @override
  Future<bool> clearCookies() => MethodChannelWebViewPlatform.clearCookies();
}

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G3020,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by darshankawar** [comment]
Hi @TPQuietBro, Can you share a minimal reproducible code along with a video or gif that shows the issue ?

**Comment by Linsixu** [comment]
> Hi @TPQuietBro, Can you share a minimal reproducible code along with a video or gif that shows the issue ?
![question](https://user-images.githubusercontent.com/13515773/85940007-77fddb80-b94c-11ea-9054-e485a71641c3.gif)

**Comment by TPQuietBro** [comment]
Hi darshankawar,please refer the gif. 
Thanks

**Comment by darshankawar** [comment]
Thanks @TPQuietBro for the gif. 
I tried to replicate this on latest Flutter `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter` plugin but didn't see any lag.
I tested on Samsung A2Core (8.1) device.

[52786.mp4.zip](https://github.com/flutter/flutter/files/4868961/52786.mp4.zip)

Which device do you see this issue on ? Can you try it on some other device too to see if this is device specific issue ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
