### ISSUE TITLE
[1.9.1-hotfix 6]Attempt to invoke virtual method 'io.flutter.app.FlutterPluginRegistry io.flutter.view.FlutterNativeView.getPluginRegistry()' on a null object reference  io.flutter.view.FlutterView.checkInputConnectionProxy(FlutterView.java:435)

### ISSUE THREAD

**Issue by moonljt521** [flutter/flutter#52787]
This is a crash in bugly:

Attempt to invoke virtual method 'io.flutter.app.FlutterPluginRegistry io.flutter.view.FlutterNativeView.getPluginRegistry()' on a null object reference
io.flutter.view.FlutterView.checkInputConnectionProxy(FlutterView.java:435)

the device detail:

OS : Android 5.1.1,level 22

ROM: Oppo/COLOROS

CPU : arm64-v8a

My flutter version is :
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.3)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment]
Hi @moonljt521 
Please take a look at this [comment](https://github.com/flutter/flutter/issues/14423#issuecomment-377675275)
Thank you

**Comment by TahaTesser** [comment]
Hi @moonljt521 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
