### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by maheshchukka** [flutter/flutter#52795]
[flutter_01.log](https://github.com/flutter/flutter/files/4347445/flutter_01.log)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
This bug has long since been fixed, NB the version you are on was released in July of last year

**Comment by maheshchukka** [comment]
Thanks  @jonahwilliams
