### ISSUE TITLE
Running "flutter pub get" in flutter_abctime... (This is taking an unexpectedly long time.

### ISSUE THREAD

**Issue by seenyea** [flutter/flutter#52796]
## Steps to Reproduce

1. flutter create test2
  see more in logs block
  Running "flutter pub get" in test2...                                   
(Thi(Thi(This i(Thi(This is taking an unexpectedly long time.)

**I have been waiting for it a long time**

## Logs
Creating project test2... androidx: true
  test2/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  test2/ios/Runner/Info.plist (created)
  test2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  (created)
  test2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  (created)
  test2/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  test2/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  test2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  (created)
 test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  (created)
  test2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  (created)
  test2/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  test2/ios/Runner/Base.lproj/Main.storyboard (created)
  test2/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  (created)
test2/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  test2/ios/Flutter/Debug.xcconfig (created)
  test2/ios/Flutter/Release.xcconfig (created)
  test2/ios/Flutter/AppFrameworkInfo.plist (created)
  test2/ios/.gitignore (created)
  test2/test/widget_test.dart (created)
  test2/test2.iml (created)
  test2/.gitignore (created)
  test2/.metadata (created)
  test2/android/app/src/profile/AndroidManifest.xml (created)
  test2/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  test2/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  test2/android/app/src/main/res/drawable/launch_background.xml (created)
  test2/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  test2/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  test2/android/app/src/main/res/values/styles.xml (created)
  test2/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  test2/android/app/src/main/AndroidManifest.xml (created)
  test2/android/app/src/debug/AndroidManifest.xml (created)
  test2/android/gradle/wrapper/gradle-wrapper.properties (created)
  test2/android/gradle.properties (created)
  test2/android/.gitignore (created)
  test2/android/settings.gradle (created)
  test2/android/app/build.gradle (created)
  test2/android/app/src/main/kotlin/com/example/test2/MainActivity.kt (created)
  test2/android/build.gradle (created)
  test2/android/test2_android.iml (created)
  test2/pubspec.yaml (created)
  test2/README.md (created)
  test2/ios/Runner/Runner-Bridging-Header.h (created)
  test2/ios/Runner/AppDelegate.swift (created)
  test2/ios/Runner.xcodeproj/project.pbxproj (created)
  test2/lib/main.dart (created)
  test2/.idea/runConfigurations/main_dart.xml (created)
  test2/.idea/libraries/Flutter_for_Android.xml (created)
  test2/.idea/libraries/Dart_SDK.xml (created)
  test2/.idea/libraries/KotlinJavaRuntime.xml (created)
  test2/.idea/modules.xml (created)
  test2/.idea/workspace.xml (created)
Running "flutter pub get" in test2...                                   
(Thi(Thi(This i(Thi(This is taking an unexpectedly long time.)       

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @seenyea 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by seenyea** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/baobao/Desktop/app/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/baobao/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-R, build-tools 28.0.3
    • ANDROID_HOME = /Users/baobao/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by seenyea** [comment]
By the way, here are my .bash_profile:
export PUB_HOSTED_URL=https://dart-pub.mirrors.sjtug.sjtu.edu.cn/
export FLUTTER_STORAGE_BASE_URL=https://mirrors.sjtug.sjtu.edu.cn/
export ANDROID_HOME=/Users/baobao/Library/Android/sdk/
export PATH=/Users/baobao/Library/Android/sdk/platform-tools:/Users/baobao/Library/Android/sdk/tools:/usr/local/bin:/usr/local/sbin:/Users/baobao/Desktop/app/flutter/bin:$PATH

**Comment by TahaTesser** [comment]
H @seenyea 
Did you setup [Using Flutter in China
](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)
Thank you

**Comment by seenyea** [comment]
It's ok now.
It seems no device to connected cause the problem, but I'm not sure.

**Comment by TahaTesser** [comment]
Hi @seenyea 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
