### ISSUE TITLE
OverscrollIndicator grows suddenly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5279]
On Android, if you fling into an overscroll indicator, it grows then goes away at the same rate. Ours instantly appears fully glowing and then fades away.

**Comment by eseidelGoogle** [comment]
Ours is different.  The settings one seems to have a little bit of a lag before it appears, vs. ours which appears to be kinda stuck-to (drawn on?) the scrolling material, where as the Android Settings one appears to be a separate animation which had a bit of elastic/lag before it does its grow thing.

The Settings overscroll also seems larger and has a different grow/shrink curve.

**Comment by abarth** [comment]
Fixed.
