### ISSUE TITLE
I am using Flutter Freshchat plugin that works fine in android but gives error in ios.

### ISSUE THREAD

**Issue by ubaidsuhail** [flutter/flutter#52794]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ubaidsuhail** [comment]
Error:
0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c70e49 -[NSException raise] + 9
	3   flutter_freshchat                   0x000000010650a772 -[FCTheme setThemeWithName:] + 529
	4   flutter_freshchat                   0x000000010650adf2 -[FCTheme fetchThemeValueForKey:] + 127
	5   flutter_freshchat                   0x000000010650d397 -[FCTheme sdkFont] + 38
	6   flutter_freshchat                   0x000000010650a497 -[FCTheme init] + 100
	7   flutter_freshchat                   0x000000010650a40d __25+[FCTheme sharedInstance]_block_invoke + 38
	8   libdispatch.dylib                   0x00007fff5223f<…>

**Comment by ubaidsuhail** [comment]
Flutter Doctor:
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment]
Hi @ubaidsuhail 
For issue related to the 3rd party plugin [flutter_freshchat ](https://pub.dev/packages/flutter_freshchat#-readme-tab-) you may want to open an issue in the dedicated [github](https://github.com/fayeed/flutter_freshchat/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
