### ISSUE TITLE
Flutter - AdColony with Mediation integration fails

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#52809]
Hi there,
I would like to integrate AdColony with Mediation to my Flutter project. So far, I use AdMob and everything works just fine. I found [Google Android AdColony integration guide](https://developers.google.com/admob/android/mediation/adcolony) and already created AdColony account and ad unit.
The issue, I have is integration on Flutter's side.
I have added to my `app/build.gradle` file following lines:

```
repositories {
    jcenter()

    maven {
        url  "https://adcolony.bintray.com/AdColony"
    }
}

dependencies {
    .....
    implementation 'com.google.firebase:firebase-core:17.2.3'
    implementation 'com.google.ads.mediation:adcolony:4.1.3.1'
    implementation 'com.google.ads.mediation:facebook:5.7.0.0'
}

```

Now, if I build a release using `flutter build apk --target="lib/config/main_production.dart" --flavor=production --split-per-abi`, my `v7` apk cannot be installed on device, while `arm64` installs and runs just fine.
I took a look inside `v7` apk via **Build > Analyse APK...** on Android Studio and I found that `v7.apk AndoirdManifest.xml` is not correct and it has nothing to do with my `AndroidManifest.xml` file. It seems as it was copied by **AdColony** somehow. Here it is:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.iab.omid.library.adcolony"
    android:versionCode="1"
    android:versionName="1.3.0" >

    <uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="27" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

</manifest>

```

In my `arm64.apk` however, `AndroidManifest.xml` looks ok, so the issue is on with `v7.apk`.

What might cause this issue and how I can fix it?

**Comment by dasebasto** [comment]
> So far, I use AdMob and everything works just fine.

Are you currently showing AdMob ads in a production app?
Are you satisfied with the stability and revenue?

The number of AdMob related issues here is a bit frightening.

**Comment by stuartmorgan** [comment]
> It seems as it was copied by **AdColony** somehow.

Based on this, it doesn't sound like this is a Flutter bug; if something you've added to your build is making it build incorrectly, it doesn't seem like there's anything that could be done about that from the Flutter side.
