### ISSUE TITLE
ERROR at dynamically parsed input that //build/toolchain/gcc_toolchain.gni:6:20 loaded :1:2: This is not a valid number. 1.9471311569213867

### ISSUE THREAD

**Issue by krishnakeshan** [flutter/flutter#52801]
I'm trying to use the **gn** tool (in the engine/src/flutter/tools directory) to prepare build files using the following command:

`./flutter/tools/gn --android --unoptimized`

However, I first get errors about invalid syntax for print statements in the **gn** tool script. I assume these scripts are to be executed with Python2 but are getting executed with Python3 instead hence the error.  I converted the print statements to the Python3 syntax but then I'm met with this error:

```
Generating GN files in: out/android_debug_unopt
ERROR at dynamically parsed input that //build/toolchain/gcc_toolchain.gni:6:20 loaded :1:2: This is not a valid number.
1.9471311569213867
-^
See //build/toolchain/android/BUILD.gn:9:1: whence it was imported.
import("//build/toolchain/gcc_toolchain.gni")
^-------------------------------------------
See //BUILD.gn:6:1: which caused the file to be included.
group("default") {
^-----------------
```

For context: I'm following the instructions at [Compiling the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine)

**Comment by krishnakeshan** [comment]
anyone resolutions?

**Comment by chinmaygarde** [comment]
What platform are you on? Can you work around this by getting rid of `concurrent_links = exec_script("get_concurrent_links.py", [], "value")` in `gcc_toolchain.gni:6`. I don't think that flag is used anymore and seems to have been initially added to figure out how many concurrent link jobs the build system could do. For whatever reason, that number seems to be 1.9... on your host.

**Comment by chinmaygarde** [comment]
Ok, I can confirm that this variable was not necessary. I removed its use in https://github.com/flutter/buildroot/pull/351 and you can do the same to unblock yourself. Let me know if you are stuck anywhere else.

**Comment by krishnakeshan** [comment]
@chinmaygarde 

> Ok, I can confirm that this variable was not necessary. I removed its use in [flutter/buildroot#351](https://github.com/flutter/buildroot/pull/351) and you can do the same to unblock yourself. Let me know if you are stuck anywhere else.

yes the issue goes away by removing that call. However newer issues come up owing to invalid Python3 statements in various scripts and tools. Have created an issue here #53002
