### ISSUE TITLE
Support --enable-experiment in the tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52819]
The semantics of this should match other Dart tooling, and forward as necessary to the analyzer, cfe, gen_snapshot, et cetera.

Technically this flag is already there, it just needs to be expanded a bit in scope

**Comment by mit-mit** [comment]
For background on this flag, see https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md

**Comment by jonahwilliams** [comment]
@mit-mit  I'm still waiting on a complete list of tools that need this flag

**Comment by mit-mit** [comment]
I believe the current list is:

1. `dart`
1. `dart2js`
1. `dartanalyzer`
1. `dartdoc`
1. `dartdevc`
1. `gen_snapshot`
1. front-end server

These should also have the flag passed, but they are not supported yet
1. `pub`: https://github.com/dart-lang/sdk/issues/41355
1. `dartfmt`: https://github.com/dart-lang/sdk/issues/41354

**Comment by jonahwilliams** [comment]
All of the above tools now receive enable-experiment from `flutter run`, `flutter build apk/ios/macos/windows` (not linux yet) and `flutter analyze`.

dart2js does not yet get these flags since it crashes: https://github.com/dart-lang/sdk/issues/41491

pub does not yet get these flags since I'm waiting on support.

flutter test still needs enable-experiment

**Comment by mit-mit** [comment]
This is awesome, thanks Jonah! I'll push a bit on the Dart side.

**Comment by jonahwilliams** [comment]
flutter test is now supported as well

**Comment by jonahwilliams** [comment]
flutter test is supported but fails due to null safety warnings. flutter build web works now that the unfork is complete

**Comment by pcsosinski** [comment]
is dart2js the only work left here?

**Comment by jonahwilliams** [comment]
`dart2js` works now:

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter build web
Target dart2js failed: Exception: lib/main.dart:9:7:                    
Error: This requires the 'non-nullable' language feature to be enabled.
String? x;
      ^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                              3.9s
Exception: Failed to compile application for the Web.
jonahwilliams-macbookpro2:hello_world jonahwilliams$ 
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter build web --enable-experiment=non-nullable
Compiling lib/main.dart for the Web...                             10.7s
jonahwilliams-macbookpro2:hello_world jonahwilliams$ 
```

IIRC pub still does not accept this experiment.

**Comment by mit-mit** [comment]
Great! Pub support is being worked on; there is a draft PR, so hopefully will be there soon

**Comment by mit-mit** [comment]
@jonahwilliams support in put has now landed in Dart master (as of https://github.com/dart-lang/sdk/commit/64b761b31b82188d35f9c84b1ee4af48258cc384)

**Comment by pcsosinski** [comment]
any update here Jonah?

**Comment by jonahwilliams** [comment]
This is done for everything besides pub

**Comment by jonahwilliams** [comment]
actually since we pass through args to most forwarding pub commands, there isn't any work to do here. I did not add the experiment to flutter pub get since it doesn't seem to do anything. Please reopen if that is not the case!

**Comment by mit-mit** [comment]
Thanks for all the work on this @jonahwilliams!

For pub, the main use case is `pub run test`, but that should be available to flutter devs as `dart pub run test` so I think we're covered too.
