### ISSUE TITLE
Swipe buck IOS issue

### ISSUE THREAD

**Issue by romawizard** [flutter/flutter#52810]
In my application I use Navigator from MaterialApp along with nested Navigator. Home Screen has BottomNavigationBar with 5 tabs each of which has its own Navigator. Moreover, there are several screens that pushed from MaterialApp Navigator. After swipe back on IOS from screen that pushed from MaterialApp Navigator the keyboard doesn't appearance if user tab to TextField Widget, and none of the TextField Widget can't get Focus. Only reopen application fix this behavior until user made swipe back in root Navigator again. There is no such trouble if user made swipe back in Nested Navigator
![Снимок экрана 2020-03-18 в 1 56 15 ПП](https://user-images.githubusercontent.com/31043679/76958383-4bcfc900-6920-11ea-8130-7270def4ca72.png)

**Comment by TahaTesser** [comment]
Hi @romawizard 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by romawizard** [comment]
> Hi @romawizard
> To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Home screen looks like this 

class _TabPages extends StatelessWidget {
  final ValueNotifier<int> notifier;
  final List<Widget> tabs;

  _TabPages({City city, this.notifier}) : tabs = _buildTabs(city: city);

  static List<Widget> _buildTabs({City city}) {
    return <Widget>[
      Navigator(
        onGenerateRoute: (RouteSettings settings) =>
            CupertinoPageRoute(
                builder: (BuildContext context) =>
                    QATab(
                      currentActiveCity: city,
                    )),
        key: ValueKey('QATab' + city?.name ?? 'city'),
      ),
      Navigator(
        onGenerateRoute: (RouteSettings settings) =>
            CupertinoPageRoute(
                builder: (BuildContext context) => PollTab(city)),
        key: ValueKey('PollTab' + city?.name ?? 'city'),
      ),
      Navigator(
        onGenerateRoute: (RouteSettings settings) =>
            CupertinoPageRoute(
                builder: (BuildContext context) => TriviaTab(city)),
        key: ValueKey('TriviaTab' + city?.name ?? 'city'),
      ),
      Navigator(
        onGenerateRoute: (RouteSettings settings) =>
            CupertinoPageRoute(
              builder: (BuildContext context) => TipsTab(city),),
        key: ValueKey('TipsTab' + city?.name ?? 'city'),
      ),
      ConciergeTAb()
    ];
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<int>(
      valueListenable: notifier,
      builder: (BuildContext context, value, Widget child) {
        return IndexedStack(
          index: value,
          children: tabs,
        );
      },
    );
  }
}
 And  Main looks like 

class MyApp extends StatelessWidget {
  final navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      localizationsDelegates: [
        AppLocalizationsDelegate(),
        FallbackCupertinoLocalisationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      supportedLocales: [Locale("en"), Locale("zh")],
      localeResolutionCallback: (locale, supportedLocales) {
        if (locale == null) {
          return supportedLocales.first;
        }
        Injector.instance.inject([
          ApiModule(locale, navigatorKey),
          AuthModule(),
          PollModule(),
          QaModule(),
          TriviaModule(),
          TipsModule(),
          RepositoryModule(),
          UserModule()
        ]);
        for (var supportedLocale in supportedLocales) {
          if (supportedLocale.languageCode == locale?.languageCode ||
              supportedLocale.countryCode == locale?.countryCode) {
            return supportedLocale;
          }
        }
        return supportedLocales.first;
      },
      builder: (_context, navigator) {
        return Theme(
          data: _appTheme(_context),
          child: navigator,
        );
      },
      home: SplashScreen(),
    );
  }

**Comment by romawizard** [comment]
Here is my Home screen full code https://gist.github.com/romawizard/7d4c3b807a5dccf2dccac2189b152c3b

**Comment by TahaTesser** [comment]
Hi @romawizard 
The sample code you provided isn't minimal, it has lot of missing code for `BaseScreen`, `Bloc` etc
Please provided a  minimal code sample to reproduce the problem that focuses on the issue
Thank you

**Comment by TahaTesser** [comment]
Hi @romawizard 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
