### ISSUE TITLE
Allow access to default controller for TextField

### ISSUE THREAD

**Issue by techfan101** [flutter/flutter#52811]
## Use case

By default, if a controller (`TextEditingController`) is not provided when instantiating a `TextField`, a default controller is created.  Unfortunately, this default controller is then not accessible to developers.  This effectively prevents developers from adding listeners to these `TextField` instances.

## Proposal

Please consider a small change to the widget and its associated state class.   I propose that the default controller could be created in the constructor of the `TextField`, instead of creating it in the associated state.

To retain its read-only nature, this would probably involve changing the "controller" member to a get-only property with a private backing field.  Then, in the constructor, implementing something like:  `_controller = controller ?? TextEditingController()`

In this way, developers could always rely on a controller being available for a `TextField`.  Additionally, they could access it identically regardless of whether its a consumer-provided controller or the default controller.

**Comment by chunhtai** [comment]
If developers care about the controller, they should provide it when creating TextField. Is there any use case that they cannot do so? I am not convinced we should expose this if there is no strong use case. The TextField API is already quite complex.

**Comment by techfan101** [comment]
I've already worked around it, but my particular use case was developing a library class/widget that allowed for the consumer to pass a child `TextField`.  I needed to detect changes to the text for that child.  Unfortunately, if the consumer fails to provide a controller, I have no ability to listen for these changes, since the default controller is unavailable.

The workaround I settled for was to throw an `ArgumentError` when the `TextField` does not have an explicit controller.  That said, it really does seem that a public instance field like "controller" should be valid whether that controller is explicit or defaulted.

**Comment by chunhtai** [comment]
Does this work for you? https://api.flutter.dev/flutter/material/TextField/onChanged.html

**Comment by techfan101** [comment]
The `onChanged` method is specified when the `TextField` is instantiated and is final thereafter.   

Since this (previously created) `TextField` is passed to my library class as a parameter, I have no ability to specify an `onChanged` method at that point.  I'm stuck with whatever the consumer (not me) of the library class passes to me.

This is the reason I chose the `controller` (instead of `onChanged`) in the first place.  A controller allows you to add or remove listeners at any point (even after instantiation).  Its kind of its whole purpose in life.

Regrettably, without access to the default controller, all I can do at that point is complain to the caller (by throwing an `ArgumentError`).

**Comment by justinmc** [comment]
I guess I don't see why we *shouldn't* provide access to the controller...  I'm wondering if anyone else is in need of this.

**Comment by chunhtai** [comment]
The original proposal is to initialize the TextEditingController in the widget, that is dangerous and will make TextField non const. The only option will be exposing the TextFieldState entirely. Either way might have a big impact on how we would maintain the textfield widget going forward. Have you though about taking a list of parameters instead of an entire textfield widget?

**Comment by techfan101** [comment]
Apologies, this reply will be a bit long, since it will probably be my last.  Thank you for your time and consideration.

I'm afraid I've simply run out of time to continue pursuing this issue.  Its not for lack of interest.

I continue to believe that, if a property like "controller" is exposed to the public, consumers of it should not be required to worry over the minutiae of whether the controller is explicit or defaulted.

So onto the reply...

I considered requiring consumers of my library class to pass all of the options (parameters) for the text field instead of simply creating one themselves.  I also considered deriving from TextField and requiring consumers of my library class to use that derived class.  I rejected these options for two reasons.

First, each would makes more work for consumers of my class.  This kind of defeats the purpose of creating a convenience library class in the first place :)

Second, there are a large number of options for text field (41 by my count).  Its not a huge deal to replicate all of them today.  However, I would also be required to try to keep them in synch as the options for TextField inevitably evolve in the future.

While I don't love it, complaining to my consumers (via an ArgumentError) remains a safer/friendlier approach than trying to replicate all of the parameters for TextField.

As wrote my explanation, an alternate feature suggestion occurred to me.  Given the large (and growing) number of options, you may want to consider a separation of concerns.  Move the options into a TextFieldOptions class, create a constructor that accepts this parameter, and make this the preferred constructor for future use of TextField.

While this is a less than ideal solution for me, it does have advantages.  It would significantly reduce the work for anyone who wants to create classes derived from TextField.  And, in all honesty, I might have made a different design choice if these concerns were separated.

Anyhow, best of luck with whatever resolution you ultimately decide upon for this issue.  Thanks again for your time and consideration.

**Comment by chunhtai** [comment]
@techfan101 Sorry if this frustrates you. I actually couldn't find a clean way to expose a default controller, but maybe @justinmc might have a better idea.

Here is my reasoning.
First of all, exposing the controller in TextFieldState will not work for your use case. The TextField state might not exist when you try to access it from its parent.

Exposing controller at widget level might work for your case, but such API might be dangerous. A widget can create multiple elements during the life time of the app, using this API might be error prompted if a developer does not have enough knowledge on how it flutter work under the hood. We tend not to expose such API.

I hope this makes sense.

**Comment by techfan101** [comment]
@chunhtai  No apologies required.  I really appreciate your time.  I do understand your concerns and agree with many of them...just not all of them :)

Perhaps, the separation of I concerns I suggested, TextFieldOptions from TextField, might be a more architecturally safe option?

While I would prefer access to the controller, this separation would allow a future-proof means of sharing options for the creation of text fields (in library classes) and also simplify development of classes derived from TexfField.

**Comment by chunhtai** [comment]
@techfan101 That will be a big breaking change for everyone uses a Textfield and is diverting from all other widgets in flutter. If we start from scratch, this might be an approach we can consider.

I think the better approach will be using this https://github.com/dart-lang/sdk/issues/16253. This will require dart team support, however.

I will close this issue for now. Feel free to reopen if you have further question. Thank you

**Comment by techfan101** [comment]
Not sure I understand either why any breaking change would be involved (providing you leave the pre-existing constructor in place) or how the referenced suggestion is in any way applicable to the problem raised in this issue.  That said, I don't see how further discussion is helpful either.  Please do leave this issue closed.
