### ISSUE TITLE
flutter channel beta, git: error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by seenyea** [flutter/flutter#52820]
## Steps to Reproduce

1. flutter channel beta
## Logs
Switching to flutter channel 'beta'...
git: error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
git: fatal: the remote end hung up unexpectedly
git: fatal: early EOF
git: fatal: index-pack failed
Switching channels failed with error code 12

### git global config lists
user.name=my name
user.email=my email
http.postbuffer=1048576000
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true

```
```

```
```

**Comment by jonahwilliams** [comment]
This is a network error in git. If you'd like to run an upgrade make sure you're connected to the internet
