### ISSUE TITLE
StreamBuilder's stream property is not currently marked @required in Flutter 1.15.23-pre.6

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#52824]
I can't think of an instance when this widget is useful without having a Stream provided.     

> Flutter 1.15.23-pre.6 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 028b7dced1 (29 hours ago) • 2020-03-16 11:33:00 -0700
> Engine • revision a9d49a0f6e
> Tools • Dart 2.8.0 (build 2.8.0-dev.14.0 d2950737b8)

**Comment by goderbauer** [comment]
Closing as per comment here: https://github.com/flutter/flutter/pull/52851#issuecomment-601909749

**Comment by ThinkDigitalSoftware** [comment]
Thanks!
