### ISSUE TITLE
Flutter video player Unable to connect to : (url)

### ISSUE THREAD

**Issue by sajjademad** [flutter/flutter#52831]
Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to : (url)

 I'm running the app on an android emulator.  
NOTE : this issue happens when the internet is slow (but the video still runs after few seconds in the browser so it's not that slow)

**Comment by VladyslavBondarenko** [comment]
Hi @sajjademad 
Are you trying to load video with http link? 
It may be the case that you can use only https

**Comment by sajjademad** [comment]
> Hi @sajjademad
> Are you trying to load video with http link?
> It may be the case that you can use only https

Thank you so much @VladyslavBondarenko , I tried an https link and it works just fine , so now I just have to make my server secure with SSL right ?
