### ISSUE TITLE
_ControllerStream' is not a subtype of type '() => void

### ISSUE THREAD

**Issue by GLopesRio** [flutter/flutter#52835]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Inicio(dirty, state: _InicioState#1cb5f):
type '_ControllerStream<dynamic>' is not a subtype of type '() => void'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Inicio file:///C:/desenv/flut/web_services/lib/main.dart:5:9
When the exception was thrown, this was the stack: 
#0      _InicioState.build (package:webservices/home.dart:32:37)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
...

**Comment by jonahwilliams** [comment]
> #0 _InicioState.build (package:webservices/home.dart:32:37)

This is a bug in your code. Please do not open self help issues on the issue tracker
