### ISSUE TITLE
[tools] Upgrading platforms command

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#52837]
## Use case

After Flutter Team made changes to the platform folders, till 2 years of programming I had to delete the platform folders (android/, ios/) sometimes to be up to date on my project. This "backuping" and "reimporting" my configs/files/firebase-configs.json into the new generated platform folders (by executing `flutter create .`) creates a lot of preparation and prework to update to the latest flutter version.

The actual `flutter create --overwrite .` works but it swipes all my configs in my platform folders and doesn't detect my changes.

## Proposal

It would be great if we developers have commands like:
  - `flutter upgrade platforms` (upgrades all platforms folders)
  - `flutter upgrade platform [android/ios/macos/windows/linux/web]`

or something with the create command like:
  - `flutter create . --upgrade-platforms`
  - `flutter create . --upgrade-platforms=[android/ios/macos/windows/linux/web]`

With these commands for example it would be easier and save a lot of time by not just upgrading flutter version itself but also upgrading the platforms on a new flutter version.

Thanks a lot Flutter team and stay healthy! I don't expect any answer till the corona pandemy now.

**Comment by jonahwilliams** [comment]
I think the requested featues are well captured in https://github.com/flutter/flutter/issues/40460 . It would be more productive to add any specific context to this issue, and ensure that it gets upvoted to help prioritize

**Comment by Ahmadre** [comment]
Thx @jonahwilliams then I'll close this one
