### ISSUE TITLE
`flutter run` and `flutter devices` fails with error about FUCHSIA_SSH_CONFIG

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#52849]
On macOS:

```
 dnfield@dnfield-macbookpro $ flutter run
Building flutter tool...
Cannot interact with device. No ssh config.
Try setting FUCHSIA_SSH_CONFIG or FUCHSIA_BUILD_DIR.
```

This started recently.  I'm not sure why.  If I modify `fuchsia_sdk.dart` to always return false from `isFuchsiaSupportedPlatform` it goes away.

/cc @gw280 @iskakaushik @jonahwilliams @zanderso

**Comment by dnfield** [comment]
I have no Fuchsia devices attached to my machine, but I do have an iOS device attached.

**Comment by dnfield** [comment]
I might have figured this out.

**Comment by dnfield** [comment]
The root cause of this is having a Fuchsia device on the same WLAN as myself, even though it's not configured for debugging with Flutter.

**Comment by jmagman** [comment]
@zanderso [says](https://github.com/flutter/flutter/pull/52761#pullrequestreview-376395324):
> Oh, man, we need to get the Fuchsia support guarded by a `flutter config` `Feature` rather than gating on the presence of the Fuchsia SDK.

**Comment by dnfield** [comment]
Yes - I'll file another issue for that.
