### ISSUE TITLE
Flutter run --hot --control-pipe depends on mkfifo on posix systems

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#5284]
This shouldn't be an issue because mkfifo is installed on every posix system but we might want to document this dependency explicitly.

**Comment by Hixie** [comment]
We should put this in the same place we say that you have to have git and mkdir and so on.

**Comment by eseidelGoogle** [comment]
I don't see --control-pipe as an option even with `flutter run --help -v`.  Maybe it's a super-secret option?

Speculatively closing as n/a. Please feel free to re-open if I'm mistaken.
