### ISSUE TITLE
Text widget word break problem

### ISSUE THREAD

**Issue by taz1208** [flutter/flutter#52869]
If I have very long text.
Text automatic newline automatically
For example
String is
`'aaaaaaaaaa abbbbbbbbb'`
and one line max 
`'aaaaaaaaaa abbbbb' `
then I expcted like this
case1:
```
'aaaaaaaaaa abbbbb
bbbbb'
```
but flutter Text widget show like this
case2:
```
'aaaaaaaaaa 
abbbbbbbbbb'
```
It seems that space basis... 

Who can I get case1?

**Comment by justinmc** [comment]
Are you looking for something like [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) in CSS?

**Comment by justinmc** [comment]
It seems that nothing like word-break exists in Flutter right now, but you can use zero width space characters to allow breaking in the middle of words.  Here's an example: https://dartpad.dartlang.org/509aefb354ece65f5b9e25ec95ef38bf

**Comment by VladyslavBondarenko** [comment]
Hi @taz1208 
please follow up on https://github.com/flutter/flutter/issues/61081,
closing current issue
