### ISSUE TITLE
flutter build ios-framework --cocoapods should be enabled on master

### ISSUE THREAD

**Issue by xster** [flutter/flutter#52867]
`--cocoapods is only supported on the dev, beta, or stable channels. Detected version is 1.15.23-pre.15`

**Comment by xster** [comment]
Also, should we use features.dart for these things? 

cc @jmagman

**Comment by jmagman** [comment]
Unfortunately it can't be enabled on master, the generated podspec is pointing to the published artifacts in storage.googleapis.com.

**Comment by xster** [comment]
noob question but that sounds like it could be ok could it? Since we have engine artifacts for each framework artifact('s reference to the engine artifact). Local engines will never work but we can just document that.

**Comment by jmagman** [comment]
If I recall mostly the issue I was hitting was coercing the master versions into a semantic version.  The version must always increase on every engine binary, or CocoaPods won't try to download it.  I wish the engine had its own version per roll...

```ruby
s.version = '1.13.400' # 1.13.4
```
[Comment](https://github.com/flutter/flutter/blob/f65421aaca381f55bee97dd0e0292b553aeaffb7/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L241) in the code:
```
// Podspecs use semantic versioning, which don't support hotfixes.
// Fake out a semantic version with major.minor.(patch * 100) + hotfix.
// A real increasing version is required to prompt CocoaPods to fetch
// new artifacts when the source URL changes.
final int minorHotfixVersion = gitTagVersion.z * 10
```

If you have suggestions I'd love to make this work on master, testing would be easier.

**Comment by xster** [comment]
Ah it specifically has to be a semantic version and not just a string? It's indeed tricky then.

**Comment by jmagman** [comment]
I added a `--force` flag in https://github.com/flutter/flutter/pull/50370 for testing.

**Comment by xster** [comment]
Sounds like we can't do this. Closing.
