### ISSUE TITLE
On web, I would like a better API for interacting with the query string

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#52866]
The current approach locks us into using named routes, and the root navigator to manage the query string, but this is not ideal for use cases that do not rely on navigator to change pages.

For example, a tab-bar app that is using an IndexedStack to manage it's children.

It would be nice if there was just a simple un-opinionated API we could tie into, and then manage the routes parsing ourselves. This could boil down to 3 hooks on Window:

```
String route = Window.getRoute() //Allow us to get initial route on start up, or parse additional params at any time 
Window.setRoute("/foo/bar") //Allow us to set route when we change 'pages' internally
Window.onRouteChanged(String) = _handleRouteChanged; //Allow us to respond to back btn
```

**Comment by mdebbar** [comment]
One thing that may help with your case is `onGenerateRoute`. It's a field on `Navigator`, `MaterialApp` and `WidgetsApp`. That callback will invoked every time the route has changed, and you can generate whatever `Route` you want based on the given `RouteSettings` (which contains the route name).

For an example that uses this approach to parse and handle query params, please take a look at [this repo](https://github.com/mdebbar/flutter_query_params/blob/master/lib/main.dart).

cc @chunhtai

**Comment by esDotDev** [comment]
But what if I never want to change the navigator? Consider a desktop style app like this:
![image](https://user-images.githubusercontent.com/736973/77189237-de957280-6a9c-11ea-9260-3ec0d7b546e9.png)

MainNavigator basically never changes, it just handles fullscreen dialogs. I would still like to allow deeplinking into my actual content area.

If we're given a simple API this is trivial to handle on the code side, I can easily parse some string, and decide which view to start on. It's actually much more flexible than hard-coding into Navigator, because it allows me to initialize my app, fetch any data I need, and _then_ deeplink into the page I need.

What is much harder than the above, is understanding how Navigator works internally, I quickly get lost in a sea of sub-classes and components, and completely confused about how it actually works. Would be nice if we could just tell MaterialApp, "hands off" the page routes please, I'm totally capable of handling them.

**Comment by mdebbar** [comment]
> Would be nice if we could just tell MaterialApp, "hands off" the page routes please.

You can do this by passing a `builder` callback to your `MaterialApp`. See [docs](https://api.flutter.dev/flutter/material/MaterialApp/builder.html) for details.

But I still think you should use a `Navigator`. I agree it's complicated and has a lot of bells and whistles, but you don't have to understand all of them in order to use the `Navigator`. If you look at the code example I linked, all you need to know is `MaterialApp` and the `onGenerateRoute` property.

**Comment by chunhtai** [comment]
You have to create your own Navigator for deep linking with current API. You can use MaterialApp.onGenerateInitialRoute to parse the url and create the main page. From there, you can pass the sub route name to the main page. There should be a navigator built somewhere in the main page that takes the sub route name and starts from there.

This process is cumbersome, we are currently in the progress of improving it. See [Navigator 2.0](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#heading=h.l6kdsrb6j9id) and [Router](https://docs.google.com/document/d/1QodTFmwVr1yk8dyQvoqkeILxvm92oikB1bVhHTtp6R4/edit)

**Comment by esDotDev** [comment]
Yes, I can currently deep-link reasonably well with the current api, because as you say I can parse the initial route. But then you hit a complete wall, because as I navigate my sub-navigator (in this case I actually use a IndexedStack), there is no way for me to write back to the query string. 

That means, despite being able to deep-link once, this feature is useless, as I can not generate any links in the first place. 

I've read the discussion on Navigator 2.0, it's tough to follow. I would really hope you guys will aproach it from an api-first way. Design general purpose API surface, and then you can build on to of those to create whatever specific implementation you want to bake into MaterialApp. I believe this is a vastly better approach than trying to force us into using a top level MaterialApp to change pages, which is simply too-opinionated and suffers from tunnel-vision in the design spec.

**Comment by chunhtai** [comment]
If you don't want to use the navigator, you can use builder as @mdebbar suggested in https://github.com/flutter/flutter/issues/52866#issuecomment-601826761. Using this, you can build the app without the build in navigator (by discarding the child) However, you will have to manage all the harness between the os event and how to response to those events.

As you mentioned, the current Navigator cannot solve all the use case in web. That is why we are trying to improve it.

**Comment by esDotDev** [comment]
> I agree it's complicated and has a lot of bells and whistles, but you don't have to understand all of them in order to use the `Navigator`. If you look at the code example I linked, all you need to know is `MaterialApp` and the `onGenerateRoute` property.

This is only true if you know already intimately know how Navigator works. Otherwise, the second you go off the beaten path, you're into 4000 lines of MaterialApp/App/Navigator/NavigatorObserver hell. 

For example, your linked repo looks great. How do I do that exactly same thing, but with a persistent application chrome? Because this has not been considered, the answer involves many hoops or is just plain impossible. This points to a flaw in the design thinking, and a focus on too specific of an implementation.

Please consider a couple of points:
1. Coupling an apps ability to use Overlay and Dialog's, to it's ability to read/write query strings is bizzare and nonsensical on it's face, these are very discrete areas of responsibility that have no excuse to be intertwined like this.

2. All platforms, including mobile and desktop, support deeplinking, this is usually in the form of some args that come into main(), why can't we just support this classic paradigm as an unopinionated starting point? An app developer using Flutter, does not want to implement 3 different methods of deeplink support, turning the entire thing into a giant hard-to-debug mess.

3. The query string on web is really just a bookmark string for the users current location in the app, it's _just_ a string. It should not take thousands of lines of code to come up with an elaborate system to manage this, that is only ever going to make sense on Web anyways. Just let us write to it ourselves and the community will come up with better solutions anyways.

**Comment by esDotDev** [comment]
> You have to create your own Navigator for deep linking with current API. You can use MaterialApp.onGenerateInitialRoute to parse the url and create the main page. From there, you can pass the sub route name to the main page. There should be a navigator built somewhere in the main page that takes the sub route name and starts from there.

But of course I do want to use the Navigator, otherwise all my Dialogs and Overlays will break. I just don't want to use any names routes, or have Navigator putting it's hands all over the querystring, actively blocking me from managing it myself.

**Comment by esDotDev** [comment]
Sorry to go on, just wanted to clarify with the upcoming Navigator 2.0 API.

Would it support a simple "Tab App", that has 3 views, and just wants to open on a specific index. It doesn't use Routes at all, it uses IndexedStack and an index property.

Would the new API support:
1. Extracting the tabIndex from querystring, and passing it into my main view on start
2. As I navigate tabs, the query string is updated to _?tabIndex=x_

A route is never pushed in this scenario. 

Would this be supported with the new API?

**Comment by esDotDev** [comment]
Seems something like unity's GetCommandLine args would be a nice, cross platform approach to parsing launch args:  https ://docs.unity3d.com/560/Documentation/Manual/CommandLineArguments.html

And then its just a matter of providing a web specific API for setting the query string.

Then as long as you treat query string as "app arguments" you end up with a clean multiplatfotm API that is easy to understand, and can be used to fit any imaginable use case.

Environment.appArgs
Environment.setAppArgs (web only, no-op elsewhere)
Environment.onAppArgsChanged (web only, no-op elsewhere)

Please make this happen, it is so much simpler and more versatile than the route you guys are currently planning. The community will quickly use those core API to come up with frameworks on top of it.

**Comment by chunhtai** [comment]
See flutter.dev/go/router-and-widgetsapp-integration, this design doc outlines how to use the new api and what opinionated classes we provide to make it easier.

Using your example, you can achieve that with following code. (Note, the exact detail might be a bit different since we have not yet finalized the design. The structure will approximately be the same.)

```dart
class MyParser extends RouteNameParser<StringRouteData> {
    @override
    StringRouteData parse(String routeName) {
        // Do nothing, the widget will handle the route parsing.
        return StringRouteData(routeName);
    }
}

class StringRouteData extends RouteData{
    StringRouteData(this.currentRouteName);

    @override
    String currentRouteName;
}

class MyRouterDelegate extends RouterDelegate<StringRouteData> {
    StringRouteData parsedResult; // This should contains the output from MyParser

    @override
    Widget build(BuildContext context){
         // In most case, this should build a navigator. For this case, we just build the widget.
         return SimpleTabApp(parsedResult.currentRouteName);
    }
}

MaterialApp.router(
    routeNameParser: MyParser(),
    routerDelegate: MyRouterDelegate(),
    // other MaterialApp settings,
    ....
)

```

The query parameter will be part of the route name, this means you will have to manually parse them.
We will provide some opinionated parsers that takes care of the route parameters and query parameters. For more detail and latest update, please refer to the design document.

I Hope this make sense.

**Comment by esDotDev** [comment]
Interesting, how would I handle writing to the querystring when changing tabs since I'm never pushing any routes?

**Comment by chunhtai** [comment]
we will provide API to change the route name, something like `Router.of(context).setAbsoluteRouteName(newRouteName) and Router.of(context).setRelativeRouteName(newRouteName)`. The route name will go through the parser and triggers a rebuild on router delegate.

**Comment by esDotDev** [comment]
Perfect, ok that works. And will you consider tying this into launch args for desktop applications as well?

**Comment by chunhtai** [comment]
deep linking discussion on desktop can be found here https://github.com/flutter/flutter/issues/51350

I think launch args is a different approach, and i don't know if we currently supports it. feel free to file a feature request against desktop

**Comment by esDotDev** [comment]
Ok thanks for the discussion and explanations.
