### ISSUE TITLE
Service worker doesn't use relative paths for resources

### ISSUE THREAD

**Issue by yolofy** [flutter/flutter#52876]
Service worker doesn't use relative paths for resources which leads to errors when not hosting in root url.

Actual generated code (flutter_service_worker.js)
```
"use strict";
const CACHE_NAME = "flutter-app-cache";
const RESOURCES = {
  "/android-icon-192x192.png": "49448b03300f72d76e33839c3dd1b39b",
  "/android-icon-36x36.png": "4fcfd635ca4f6dd26834ee9af550f204",
  "/index.html": "bd50bf332d3cd506787d70f714c65242",
...
```

Expected generated code (flutter_service_worker.js)
```
"use strict";
const CACHE_NAME = "flutter-app-cache";
const RESOURCES = {
  "android-icon-192x192.png": "49448b03300f72d76e33839c3dd1b39b",
  "android-icon-36x36.png": "4fcfd635ca4f6dd26834ee9af550f204",
  "index.html": "bd50bf332d3cd506787d70f714c65242",
...
```

Should be solved by trimming leading slashes while generating the urls:
https://github.com/flutter/flutter/blob/a7011c48177327430b5eecd5f85cea115524b229/packages/flutter_tools/lib/src/build_system/targets/web.dart#L351

**Comment by jonahwilliams** [comment]
Fixed with https://github.com/flutter/flutter/pull/52606
