### ISSUE TITLE
PageView dismiss frames

### ISSUE THREAD

**Issue by dansunhappy** [flutter/flutter#52875]
**Devices:** iPhone x max &  iOS 13.3.1 &  profile mode
PageView dismiss frames
## Logs
`Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
`

```
import 'package:flutter/material.dart';

void main() async {
  runApp(MaterialApp(
    home: Scaffold(
      body: Screen(),
    ),
  ));
}

class Screen extends StatefulWidget {
  @override
  _ScreenState createState() => _ScreenState();
}

class _ScreenState extends State<Screen> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {
          return Container(
              color: Colors.yellow,
              alignment: Alignment.center,
              child: Container(
                width: 50.0,
                height: 50.0,
                color: Colors.blue,
                child: Text('aa'),
              ));
        },
      ),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/12166990/77050757-2f598c80-6a05-11ea-9aed-66c13d8ee8c2.png)

```
```

**Comment by pedromassangocode** [comment]
Hi @dansunhappy 
Are you facing this issue with the latest `stable` version of Flutter? If yes please provide your `flutter doctor -v`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
