### ISSUE TITLE
Because pub global activate depends on webserve any which doesn't exist (could not find package webserve at https://pub.dartlang.org), version solving failed.[web]: <describe issue here>

### ISSUE THREAD

**Issue by Emred360** [flutter/flutter#52882]
Describe your issue and include the command you're running, flutter_web version, browser version

**Comment by TahaTesser** [comment]
Hi @Emred360 
If you're trying to run Flutter on web 
Please follow this [Create a new project with web support
](https://flutter.dev/docs/get-started/web) guide
Thank you
