### ISSUE TITLE
microbenchmarks  combineSemanticsInfoSyncStar_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52888]
![Screen Shot 2020-03-19 at 9 22 22 AM](https://user-images.githubusercontent.com/1435716/77089527-2b0c7f80-69c3-11ea-92ae-9ec709353537.png)

Difficult to tell a culprit. I'm also not sure if this is engine or framework related.

**Comment by jason-simmons** [comment]
This benchmark is somewhat noisy, but it looks like its results changed around the time that https://github.com/dart-lang/sdk/commit/2a8127dbfad894d511cd1ccd866697f3ff6469bd landed (which affected several other microbenchmarks).

I would go ahead with a rebaseline.

**Comment by kf6gpe** [comment]
Rebaselined.
