### ISSUE TITLE
Text container have extra space

### ISSUE THREAD

**Issue by Filaind** [flutter/flutter#52880]
We have issues with text container. 
In specific text, container not contain real text size.

![photo_2020-03-19_15-10-42](https://user-images.githubusercontent.com/27895981/77066794-d84bbb80-69f4-11ea-9049-dff25d2a0b2e.jpg)

**Comment by TahaTesser** [comment]
Hi @Filaind 
That's just new line cuz that whole text couldn't fit into one line.

You can reduce your text width by wrapping in a container

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            width: 125,
            child: Text(
              'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ',
            ),
          ),
        ),
      ),
    );
  }
}
```

Thankk you

**Comment by TahaTesser** [comment]
Hi @Filaind 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have anymore information for us; we will reopen it right away!
Thanks for your contribution.
