### ISSUE TITLE
Error: ADB exited with exit code 1

### ISSUE THREAD

**Issue by Vuyisile619** [flutter/flutter#52887]
Hey guys. when i try running a flutter project i get this error from my cmd

```
C:\AndroidStudioProjects\flutterapp\test_project>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                       433,3s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
cmd: Can't find service: activity
Installing build\app\outputs\apk\app.apk...                         0,7s
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\AndroidStudioProjects\flutterapp\test_project\build\app\outputs\apk\app.apk: cmd: Can't find
service: package
Error launching application on AOSP on IA Emulator.
```

Please help what could be the problem

**Comment by VladyslavBondarenko** [comment]
Hi @Vuyisile619 
Do workarounds from https://github.com/flutter/flutter/issues/34001 help you?

**Comment by VladyslavBondarenko** [comment]
https://github.com/flutter/flutter/issues/34001#issuecomment-601388656

@Vuyisile619  let's keep conversation in your issue.

Could you provide your `flutter doctor -v` and `flutter run --verbose`?

**Comment by Vuyisile619** [comment]
Hi @VladyslavBondarenko  here are the logs

C:\WINDOWS\system32>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-ZA)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter\flutter\flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Vuyisile Van Dave\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!


C:\AndroidStudioProjects\flutterapp\test_project>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                       433,3s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
cmd: Can't find service: activity
Installing build\app\outputs\apk\app.apk...                         0,7s
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\AndroidStudioProjects\flutterapp\test_project\build\app\outputs\apk\app.apk: cmd: Can't find
service: package
Error launching application on AOSP on IA Emulator.

**Comment by iapicca** [comment]
Hi @Vuyisile619 
is this the same issue of https://github.com/flutter/flutter/issues/51690?
Thank you

**Comment by Vuyisile619** [comment]
@iapicca it kind of is in the sense that this was when i was running it on android studio but now i try running on vscode but unlike android studio, vscode doesnt read any of the flutter commands

**Comment by VladyslavBondarenko** [comment]
Possibly related to https://github.com/flutter/flutter/issues/11533

**Comment by royrojas** [comment]
Here the solution http://www.dotnetcr.com/flutter-error-adb-exited-with-exit-code-1/

**Comment by Fernando-Braulio** [comment]
I went through the same problem, but as I was emulating on a physical device the problem was the USB cable, I changed the cable and solved it.

**Comment by Vuyisile619** [comment]
> I went through the same problem, but as I was emulating on a physical device the problem was the USB cable, I changed the cable and solved it.

hey thanks for the response but I have given up on android studio all that hassle is unnecessary I use visual studio code with a google emulator called vysor. was surprised how simple the process is if you get rid of android studio as a whole

**Comment by qahtansaid** [comment]
Maybe you have insufficent space on your android, try to delete some app or you have'nt turn usb debuggin on

**Comment by veerendra0607** [comment]
this type of problem facing in flutter emulator what i do guys .....
.....
....

Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install E:\app\health_app\build\app\outputs\flutter-apk\app.apk: 
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:406)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2415)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
	at com.
Error launching application on Android SDK built for x86 64.

**Comment by ashwanisng** [comment]
I face the same problem.

- If you are using android studio and running your app in an emulator then follow this

- [x]  https://www.dotnetcr.com/flutter-error-adb-exited-with-exit-code-1/

-  If you are using vs code and running your app on a physical device then  

- [x]  make sure you have enough storage in your physical device.

**Comment by iapicca** [comment]
tagging @TahaTesser  for visibility

**Comment by edocabhi** [comment]
It's strange that this issue still persists. I remember spending lot of hours trying to make it work. Then I started using the **canary** version of Android Studio and never had the issue. Just checked with the stable version again to see if it's fixed but still have the issue there. In Summary: **Use Android Studio Canary Version**

**Comment by pro100svitlo** [comment]
`flutter clean` helped to me 😉

**Comment by md-siam** [comment]
Settings -> Additional Settings -> Developer options ->

At the bottom Turn off "**MIUI optimization**" and Restart

**Comment by theomkale** [comment]
Reducing the minSdkVersion helped me.

**Comment by RahmatFarahmand** [comment]
PS C:\Users\Rahmatullah\FlutterProject\flutter_application_1> flutter run
Launching lib\main.dart on Google in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        76.9s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...              1,534ms
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\Rahmatullah\FlutterProject\flutter_application_1\build\app\outputs\flutter-apk\app.apk: 
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Failed to prepare session dir: /data/app/vmdl1993675904.tmp
        at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
        at com.android.server.pm.PackageInstallerService.openSession(PackageInstallerService.java:614)
        at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(PackageManagerShellCommand.java:1412)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:209)
Error launching application on Google.

**Comment by JoaquinHoffmann** [comment]
In my case the error went away when I removed `flutter_launcher_name` dependency (which I added trying to use a launcher name with capitals)

**Comment by Michellejacob001** [comment]
In my case, it was due to Insufficient Storage on my device. 

Hope it helps :).

**Comment by archenroot** [comment]
@theomkale  > Reducing the minSdkVersion helped me.
Reducing to what number?

I am using Nexus_10_API_30 avd with 10GB internal custom space adb emulator, I tried:
- AVD manager wipe data
- flutter clean
- delete lock files, eg. rm ~/.android/avd/Nexus_10_API_30.avd/*.lock command as suggested here https://stackoverflow.com/questions/66022494/flutter2-cant-find-service-package-android-studio-windows10?noredirect=1&lq=1

no help...

**Comment by exaby73** [comment]
Hello @Vuyisile619. Is this issue still reproducible?
