### ISSUE TITLE
HTTP headers key converted to lowercase ,need help?

### ISSUE THREAD

**Issue by MiriDevAndro** [flutter/flutter#52884]
HttpClient or http.get() is converting headers to lowercase .
I need fix in lib sdk or whatever...

**Comment by TahaTesser** [comment]
Related to [#33501](https://github.com/dart-lang/sdk/issues/33501)
This [comment](https://github.com/dart-lang/sdk/issues/33501#issuecomment-588749404) says it's landed
You would have to try the landed version to to use this feature
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by MiriDevAndro** [comment]
@TahaTesser  landed version  of what ? flutter sdk or dart sdk or what .
i have modify dart sdk lib related #33501 but i there is no path like sdk_nnbd/lib/_http/http.dart in my sdk . Should i use old flutter sdk version ?

**Comment by TahaTesser** [comment]
Hi @MiriDevAndro 
Can you please try it on latest master channel of Flutter?

**Comment by MiriDevAndro** [comment]
version 
Flutter 1.16.1-pre.34 • channel master • https://github.com/flutter/flutter.git
Framework • revision e6b0f5f238 (13 hours ago) • 2020-03-18 21:56:02 -0400
Engine • revision 216c420a2c
Tools • Dart 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

again there is no folder like sdk_nnbd but i have see this sdk that have that folder should i download this https://dart.googlesource.com/sdk/+/b2b7337ad4b05b3197cde407dab98a444e291c2f
