### ISSUE TITLE
Android NDK location not configured (optional; useful for native profiling support)

### ISSUE THREAD

**Issue by rubankrish** [flutter/flutter#52881]
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Anantharuban\AppData\Local\Android\Sdk
    • **Android NDK location not configured (optional; useful for native profiling support)**
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Anantharuban\AppData\Local\Android\Sdk\
    • ANDROID_SDK_ROOT = C:\Users\Anantharuban\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\Anantharuban\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

I am struggling with this error please someone help.

**### Android NDK location not configured (optional; useful for native profiling support)**

**Comment by giga10** [comment]
It's NOT an error. You're good to go.

**Comment by TahaTesser** [comment]
Hi @rubankrish 
This isn't an issue, it's just optional 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it Thank you
