### ISSUE TITLE
Flutter geofencing package issue

### ISSUE THREAD

**Issue by devUsama** [flutter/flutter#52885]
**On build Flutter geofencing package giving these errors related to **GeofencingService** and **IsolateHolderService** files of package**

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (11, 31): Unresolved reference: JobIntentService

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (28, 46): Unresolved reference: JobIntentService

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (48, 59): Type inference failed. Expected type mismatch: inferred type is Class<GeofencingService> but Intent was expected

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (48, 65): Too many arguments for @JvmStatic public final fun enqueueWork(context: Context, work: Intent): Unit defined in io.flutter.plugins.geofencing.GeofencingService.Companion

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (48, 73): Too many arguments for @JvmStatic public final fun enqueueWork(context: Context, work: Intent): Unit defined in io.flutter.plugins.geofencing.GeofencingService.Companion

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (113, 5): 'onCreate' overrides nothing

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (114, 15): Unresolved reference: onCreate

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (115, 32): Type mismatch: inferred type is GeofencingService but Context was expected

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/GeofencingService.kt: (118, 5): 'onHandleWork' overrides nothing

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/IsolateHolderService.kt: (14, 31): Unresolved reference: NotificationCompat

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/IsolateHolderService.kt: (48, 28): Unresolved reference: NotificationCompat

flutter/.pub-cache/hosted/pub.dartlang.org/geofencing-0.0.1/android/src/main/kotlin/io/flutter/plugins/geofencing/IsolateHolderService.kt: (52, 30): Unresolved reference: NotificationCompat

**Comment by devUsama** [comment]
**flutter doctor -v result**
![Screenshot 2020-03-19 at 6 37 47 PM](https://user-images.githubusercontent.com/57903749/77073347-f9baa080-6a10-11ea-993d-86d3080dfe1b.png)

**Comment by VladyslavBondarenko** [comment]
Hi @devUsama 
Consider to contact the plugin's author,
Note that [geofencing](https://pub.dev/packages/geofencing) hasn't update already for 10 months
Closing, as it seems to be an issue with the 3rd party plugin,
if you disagree and believe it's an issue with Flutter itself, please write in the comments and I will reopen it
Thank you
