### ISSUE TITLE
Web-only pieces of dart:ui cause analysis errors

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#52899]
There are some memebers in the web-only "version" of dart:ui that are not found in the mobile version of dart:ui:

* `webOnlyInstantiateImageCodecFromUrl`
* `webOnlySetPluginHandler`
* `debugEmulateFlutterTesterEnvironment`

These cause the following static analysis errors:

```none
  error: The function 'webOnlyInstantiateImageCodecFromUrl' isn't defined - packages/flutter/lib/src/painting/_network_image_web.dart:64:15 - undefined_function
  error: The function 'webOnlySetPluginHandler' isn't defined - packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:8 - undefined_function
  error: The name 'debugEmulateFlutterTesterEnvironment' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix - packages/flutter_web_plugins/test/plugin_event_channel_test.dart:16:6 - undefined_prefixed_name
  error: The name 'debugEmulateFlutterTesterEnvironment' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix - packages/flutter_web_plugins/test/plugin_registry_test.dart:33:6 â€¢ undefined_prefixed_name
```

To satisfy CI, these errors are ignored inline, e.g.

https://github.com/flutter/flutter/blob/9391e480b2cbf0905dc2630f383e562e1f05ef67/packages/flutter_web_plugins/test/plugin_event_channel_test.dart#L16

The Dart Analyzer will stop allowing issues with severity _error_ to be ignore (see https://github.com/dart-lang/sdk/issues/27218).

To me it seems that, aside from static analysis, this is awkward code that exists in one version of a library but not another. I spoke to @yjbanov at length about this and we thought of a few solutions:

1. Define these members in the mobile version of dart:ui, and declare them to `throw UnsupportedError`, and don't document them.
2. Define these members in a new library, something like `dart:web_ui`.

**Comment by jonahwilliams** [comment]
There is a `3`, which is to only allow access to these members through JS-interop:

engine setup
```
html.window['debugEmulateFlutterTesterEnvironment']= allowInterop(...)
```

framework setup
```
html.window['debugEmulateFlutterTesterEnvironment'](true);
```

1. Isn't great, since many of the APIs seem transitional and dart:ui is very difficult to change.
2. is a worse version of 1. IMO

**Comment by yjbanov** [comment]
@jonahwilliams ' solution actually looks pretty good. Let's go with that.

**Comment by srawlins** [comment]
SGTM! Thanks @yjbanov and @jonahwilliams . Are clients using these functions? Does this require a breaking change announcement?

**Comment by jonahwilliams** [comment]
No one should be using this functionality besides the SDK and possibly some google3 generated code. If they are doing so with an `ignore: missing` you have my permission to break them.

At any rate, to shakes these dependencies out I would recommend a 3 stage process:

1. Add the JS-interop based APIs with a fallback to the existing functionality if they are not set.

2. Update flutter/flutter and google3 code to use the new APIs after the engine rolls.

3. Remove the old apis from flutter/engine

**Comment by srawlins** [comment]
What about `platformViewRegistry`? https://github.com/flutter/flutter/issues/41563

It looks like this one _should_ be declared in both the mobile and the web versions of `dart:ui`? Users _should_ be able to use this attribute.

**Comment by yjbanov** [comment]
@hterkelsen is now actively working on this.

**Comment by deakjahn** [comment]
@srawlins Yes. Very emphatically, yes (especially to `webOnlyInstantiateImageCodecFromUrl`).

If and when CanvasKit becomes fully mature and becomes the default (or, at least, equivalent is status to DomCanvas), don't even think about removing the workarounds that are our only chance to navigate with the many bugs in the Web canvas support (yes, especially with decoding bitmaps, problems with `HtmlCodec` and others). Right now, these tricks are that keep us afloat. :-)

**Comment by Hixie** [comment]
(removing assignment since this has been without updates and marked overdue for over a month)

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by Hixie** [comment]
We could add these to dart:ui (and document them as only being meaningful on the web port). That doesn't seem too bad. It would solve one major problem with the current situation which is that they aren't documented.

Putting them in a dedicated web-specific dart: library seems reasonable as well. We do that for many other similar features (dart:html, dart:fidl, etc).

I'm not sure I understand the third proposal.

**Comment by lrhn** [comment]
Having different APIs for the *same library* between platforms is not something Dart is designed to support.
If you need different APIs, you import different libraries (e.g., using configurable imports).
So, putting the API in question into a different library would be the right thing to do.

There is no way (or intent to add a way) to support compiling code containing unresolved identifiers, even if their use is guarded by some run-time check which ensures that they won't actually be reached. The only kind of abstraction over static resolution of names is configurable imports, and the name still needs to be present in all the configurations.

**Comment by Hixie** [comment]
These APIs are not used in code that is run in multiple environments. They're used in e.g. the code that is imported using configurable imports, or in extremely low-level auto-generated code that is inserted into the application at build time based on which platform is being targeted.

**Comment by renefloor** [comment]
Is there any plan to fix this?
CachedNetworkImage loads images the same as NetworkImage on the web. However, due to this issue the analyzer gives an error because the package would use a function that doesn't exist.
https://pub.dev/packages/cached_network_image/score

I don't care too much about the score, but it also makes the package less visible and devs might think it is not maintained or doesn't work on the latest Flutter version.

I'm thinking of removing web support and direct devs to use NetworkImage on web, but that shouldn't be needed. In the widget I can easily do the switch myself (`if(kIsWeb) NetworkImage()`) but for the ImageProvider it is not so easy to return NetworkImage when devs ask for a CachedNetworkImagePovider.

**Comment by renefloor** [comment]
The failing analyzer is also giving me the issue that pub.dev doesn't indicate the CachedNetworkImage as migrated to null safety. So every week I get somebody asking for a null safety migration. I am really considering dropping web support for CachedNetworkImage because of this issue.

**Comment by deakjahn** [comment]
@renefloor Please, don't consider it. :-))

Where is the problem actually? Only for you in development? Because I use 3.0.0 in my app, both on mobile and app, without problems. Actually, I still use an extra parameter marked FIXME and I don't know whether it's still needed but this is probably unrelated. Apart from that, I can't see any problems.

      provider = CachedNetworkImageProvider(
        info.thumbnail!,
        imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet, //FIXME remove imageRenderMethodForWeb
      );

**Comment by renefloor** [comment]
@deakjahn don't be afraid, I'll try some other alternatives first. I don't really have any issues with it, but the fact that pub.dev marks the package as unidentified gives me more and more questions. Some think the package is not maintained, some think it is not null safe (I'm not sure if it breaks sound null safety actually). 

But let's not discuss CachedNetworkImage specifically here, this topic is about the fact that the use of very valid Flutter API's cause analysis errors and break the pub.dev listing.

I'm willing to help with solving this issue, but I don't have the feeling that there is an agreement in the direction of the solution.

**Comment by deakjahn** [comment]
OK, I'm starting to see the whole picture. Just to the general side of the question then. I think you're not yet a federated plugin, are you? Because if you're not, I have a strong suspicion that this is part of the problem (if not the problem itself). I have a few federated ones myself, using very web-specific parts in the web plugin and I don't remember any similar issues.

**Comment by renefloor** [comment]
@deakjahn that's correct. That is something I'm looking at at the moment (at least putting the web version in a separate package). Federated is made for plugins that have platform specific code (for example kotlin for Android, swift for iOS or dart/js for web), but in this case it is slightly different as all code is Flutter code. I should just be able to do a platform dependent import like this: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart#L14-L15. 

Federation makes it possible for third parties to write their own platform implementation for not supported platforms, but written code (in this case dart code) should not throw analyzer issues. When I separate the plugin in a new package the cached_network_image will be fine in pub.dev, but the cached_network_image_web will have the same analyzer error.

**Comment by deakjahn** [comment]
Yes, federated does make it possible for others to co-operate but you can still write all subplugins yourself. :-) What I would say it does in this situation is to provide drop-in support for more than one plugin. Simply that on the web, you actually get a _different_ plugin than on mobile, while you don't have to modify your references in the pubspec where to call it.

The point is that I _do_ have conditional imports in my app, just like this, without errors. I can't really tell whether this would perfectly apply to you, of course. Still, my usage is somewhat different, I do the full stub approach. If we could follow this in your issue queue, I could point you to some code I have up here. Maybe this is something you already tried and dismissed but maybe not.
