### ISSUE TITLE
build ios-frameworks should call assemble API directly instead of going through AotBuilder

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#52897]
After https://github.com/flutter/flutter/pull/52896, The AotBuilder is only an indirection around the assemble APIs. These should be used directly, to make it easier to deprecate and remove flutter build aot.

**Comment by jonahwilliams** [comment]
fyi @jmagman

**Comment by jmagman** [comment]
@jonahwilliams can this be closed with https://github.com/flutter/flutter/pull/53853?

**Comment by jonahwilliams** [comment]
I could file a separate issue for _bundleBuilder.build
