### ISSUE TITLE
Flutter plugins: Camera image stream spends a lot of memory

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#52907]
flutter channel: stable
code:
```dart
 Future<void> startImageStream() async =>
      await _cameraController.startImageStream(_imagesInput.sink.add);
```
<img width="374" alt="Screenshot 2020-03-20 at 00 27 31" src="https://user-images.githubusercontent.com/42138594/77116913-09061200-6a42-11ea-85ad-f1d406f56054.png">

**Comment by iapicca** [comment]
Hi @Renesanse 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml`
or if possible a reproducible minimal code sample.
Thank you
