### ISSUE TITLE
[shared_preferences_web] not setting value and returning key with prefix

### ISSUE THREAD

**Issue by GustavoContreiras** [flutter/flutter#52932]
```
SharedPreferencesPlugin().getAll()
.then((Map<String, Object> sharedPreferences) {
  sharedPreferences.forEach((key, value) {
    print('[PUCOverflow] [initState] ' + key + ' - ' + value.toString());
  });
});
```

This returns keys as "flutter.KEY_TEXT"

And `SharedPreferencesPlugin().setValue("String", "key", "test");` is not working.

To set new values to the shared preferences on web I have to import the original shared_preferences and use `SharedPreferences.getInstance().then((value) => value.setString(SIGNED_EMAIL, email));`

**Comment by iapicca** [comment]
Hi @GustavoContreiras 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @GustavoContreiras 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
