### ISSUE TITLE
Lifecycle callback related to route change?

### ISSUE THREAD

**Issue by crizant** [flutter/flutter#52944]
Hi, my application is using web socket to receive some data, and I want to achieve the following:

The registration and unregistration of data streams is done by sending events to the socket. Only 1 connection is allowed for a single user.

Page A is registered to some streams, when I `push` any new routes, I need to unregister from those streams.

Then Page B comes in, and register other streams.

When Page B is popped, Page A is back and re-register to its streams.

The order of register and unregister is very important.

I tried writing the logic of unregistration in the `dispose` method of Page B, then put a callback of button in Page A like:

```dart
FlatButton(
  onTap: () async {
    _unregisterFromStreams();

    await Navigator.of(context).push(/* Page B*/);

    _registerFromStreams();
  }
)
```

But the `_registerFromStreams()` of Page A executes before the `_unregisterFromStreams()`
 of Page B. Also if I do `Navigator.of(context).pushReplacement()` in Page B, the future gets resolved.

Since the order of register and unregister is critical in my application, this doesn't work.

Is it possible to run a callback before a route is pushed and after a route is popped? Or is it possible to get the `widget` in `NavigatorObserver`?

I looked at `RouteAware` but it is not suitable, since I may have Page A>Page B>Page C, I don't want the `_registerFromStreams()` of Page A to be executed when I popped Page C and go back to Page B.

Any help is appreciated!

**Comment by chunhtai** [comment]
This question should be asked in stackoverflow.

>Or is it possible to get the widget in NavigatorObserver?

Which widget are you referring to?

>I looked at RouteAware but it is not suitable, since I may have Page A>Page B>Page C, I don't want the _registerFromStreams() of Page A to be executed when I popped Page C and go back to Page B.

_registerFromStreams should not be triggered when popped page C in this case if you use didPopNext on page A.

It seems like RouteAware or NavigatorObserver should work in your use case

**Comment by crizant** [comment]
Thanks, I will give it a try on Monday.

**Comment by crizant** [comment]
`RouteAware` and `RouteObserver` did the job, thanks.
