### ISSUE TITLE
Failed assertion: line 22 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by andrehen27** [flutter/flutter#52941]
class CustomCircleAvatar extends StatefulWidget {
  final Image myImage;

  final String initials;

  CustomCircleAvatar({this.myImage, this.initials});

  @override
  _CustomCircleAvatarState createState() => new _CustomCircleAvatarState();
}

class _CustomCircleAvatarState extends State<CustomCircleAvatar> {
  bool _checkLoading = true;

  @override
  void initState() {
    super.initState();
    widget.myImage.image.resolve(new ImageConfiguration()).addListener(
        ImageStreamListener((ImageInfo info, bool synchronousCall) {
      if (mounted) {
        setState(() {
          _checkLoading = false;
        });
      }
    }));
  }

  @override
  Widget build(BuildContext context) {
    return _checkLoading == true
        ? new CircleAvatar(
            child: new Text(
            widget.initials,
            style: TextStyle(fontSize: 60),
          ))
        : new CircleAvatar(
            backgroundImage: widget.myImage.image,
          );
  }
}

Positioned _profilePhoto(BuildContext context) {
    return Positioned(
      bottom: -70,
      child: Container(
        width: 150.0,
        height: 150.0,
        padding: EdgeInsets.all(3.0),
        decoration: BoxDecoration(color: Colors.white, shape: BoxShape.circle),
        child: CustomCircleAvatar(
          myImage: Image.network(sellerPicture),
          initials: '$sellerName'.substring(0, 1).toUpperCase(),
        ),
      ),
    );
  }

**Comment by TahaTesser** [comment]
Hi @andrehen27 
This just missing url error. Please make sure you're `sellerPicture` link to your `Image.network`
Thank you

**Comment by andrehen27** [comment]
Hello , thanks for the response , Actually i've print the sellerPicture URL and the URL Printed in terminal .
Also the Image show too from URL but the i got error message from flutter

**Comment by TahaTesser** [comment]
Hi @andrehen27 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem which includes values `myImage` and `initials`
Thank you

**Comment by andrehen27** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-ID)
    • Flutter version 1.12.13+hotfix.8 at /Users/andrehendrawan/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andrehendrawan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/andrehendrawan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by andrehen27** [comment]
import 'package:flutter/material.dart';
import 'package:ican/Screens/loginScreen.dart';
import 'package:ican/sqlite/seller.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ProfileScreen extends StatefulWidget {
  @override
  _ProfileScreenState createState() => _ProfileScreenState();
}

class CustomCircleAvatar extends StatefulWidget {
  final Image myImage;

  final String initials;

  CustomCircleAvatar({this.myImage, this.initials});

  @override
  _CustomCircleAvatarState createState() => new _CustomCircleAvatarState();
}

class _CustomCircleAvatarState extends State<CustomCircleAvatar> {
  bool _checkLoading = true;

  @override
  void initState() {
    super.initState();
    widget.myImage.image.resolve(new ImageConfiguration()).addListener(
        ImageStreamListener((ImageInfo info, bool synchronousCall) {
      if (mounted) {
        setState(() {
          _checkLoading = false;
        });
      }
    }));
  }

  @override
  Widget build(BuildContext context) {
    return _checkLoading == true
        ? new CircleAvatar(
            child: new Text(
            widget.initials,
            style: TextStyle(fontSize: 60),
          ))
        : new CircleAvatar(
            backgroundImage: widget.myImage.image,
          );
  }
}

class _ProfileScreenState extends State<ProfileScreen> {
  String sellerName;
  String sellerOrg;
  String sellerArea;
  String sellerPicture;

  @override
  void initState() {
    super.initState();
    _loadSellerName();
    _loadSellerOrg();
    _loadSellerArea();
    _loadSellerPictureUrl();
  }

  _loadSellerName() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      sellerName = (prefs.getString('sellerName') ?? '');
      return sellerName;
    });
  }

  _loadSellerOrg() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      sellerOrg = (prefs.getString('sellerOrg') ?? '');
      return sellerOrg;
    });
  }

  _loadSellerArea() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      sellerArea = (prefs.getString('sellerArea') ?? '');
      return sellerArea;
    });
  }

  _loadSellerPictureUrl() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      sellerPicture = (prefs.getString('sellerPicture') ?? '');
      return sellerPicture;
    });
  }

  Widget build(BuildContext context) {
    print('$sellerPicture');
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back,
            color: Colors.white,
          ),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        elevation: 0.0,
        actions: <Widget>[
          InkWell(
            child: Container(
              margin: EdgeInsets.symmetric(horizontal: 10.0),
              child: Center(
                child: Text(
                  "Logout",
                  style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 18),
                ),
              ),
            ),
            onTap: () async {
              SharedPreferences prefs = await SharedPreferences.getInstance();
              prefs.remove('value');
              Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(
                      builder: (BuildContext context) => LoginPage()),
                  ModalRoute.withName("/HomePage"));
            },
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Stack(
              alignment: AlignmentDirectional.topCenter,
              overflow: Overflow.visible,
              children: <Widget>[
                _backBgCover(),
                _profilePhoto(context),
              ],
            ),
            SizedBox(
              height: 80.0,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Text('$sellerName'.toUpperCase()),
                Text('$sellerArea'.toUpperCase()),
                Text('$sellerOrg'.toUpperCase()),
              ],
            ),
            Container(
              margin: EdgeInsets.symmetric(horizontal: 20.0),
              child: Divider(
                height: 20,
                thickness: 1.5,
                color: Colors.lightGreen,
              ),
            ),
            Card(
              margin: EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
              child: ListTile(
                leading: Icon(
                  Icons.person,
                  color: Colors.lightGreen,
                ),
                title: Text(
                  "Personal Detail",
                  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.lightGreen,
                      fontSize: 20.0),
                ),
                trailing: IconButton(
                  icon: Icon(
                    Icons.keyboard_arrow_right,
                    color: Colors.lightGreen,
                  ),
                ),
              ),
            ),
            Card(
              margin: EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
              child: ListTile(
                leading: Icon(
                  Icons.edit,
                  color: Colors.lightGreen,
                ),
                title: Text(
                  "Update Profile",
                  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.lightGreen,
                      fontSize: 20.0),
                ),
                trailing: IconButton(
                  icon: Icon(
                    Icons.keyboard_arrow_right,
                    color: Colors.lightGreen,
                  ),
                ),
              ),
            ),
            Card(
              margin: EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
              child: ListTile(
                leading: Icon(
                  Icons.lock,
                  color: Colors.lightGreen,
                ),
                title: Text(
                  "Change Password",
                  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.lightGreen,
                      fontSize: 20.0),
                ),
                trailing: IconButton(
                  icon: Icon(
                    Icons.keyboard_arrow_right,
                    color: Colors.lightGreen,
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }

  Container _backBgCover() {
    return Container(
      height: 150.0,
      decoration: BoxDecoration(
        color: Colors.lightGreen,
      ),
    );
  }

  Positioned _profilePhoto(BuildContext context) {
    return Positioned(
      bottom: -70,
      child: Container(
        width: 150.0,
        height: 150.0,
        padding: EdgeInsets.all(3.0),
        decoration: BoxDecoration(color: Colors.white, shape: BoxShape.circle),
        child: CustomCircleAvatar(
          myImage: Image.network(sellerPicture),
          initials: '$sellerName'.substring(0, 1).toUpperCase(),
        ),
      ),
    );
  }
}

This is my whole page code

**Comment by andrehen27** [comment]
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="flutter.sellerOrg">BISI</string>
    <long name="flutter.value" value="1" />
    <string name="flutter.sellerId">BS-1234</string>
    <string name="flutter.sellerPicture">https://media-exp1.licdn.com/dms/image/C4E03AQEo669D2BcLJw/profile-displayphoto-shrink_200_200/0?e=1586390400&amp;v=beta&amp;t=VbyXdfUwSSaU8HFakjH5VSuHhHGzYluVrOjOynyrdq4</string>
    <string name="flutter.user">budi1234</string>
    <string name="flutter.sellerPhone">+62 878213164</string>
    <string name="flutter.pass">12341234</string>
    <string name="flutter.sellerName">Budi </string>
    <string name="flutter.sellerArea">JAWA TIMUR</string>
</map>

this is my sharedPreferences where sellerPicture URL from.

**Comment by TahaTesser** [comment]
hi @andrehen27 
` <string name="flutter.sellerPicture">https://media-exp1.licdn.com/dms/image/C4E03AQEo669D2BcLJw/profile-displayphoto-shrink_200_200/0?e=1586390400&amp;v=beta&amp;t=VbyXdfUwSSaU8HFakjH5VSuHhHGzYluVrOjOynyrdq4</string>`

here sellerPicture string  isn't a proper link for image url

**Comment by andrehen27** [comment]
hmm sorry i just a beginner , can you tell me what should i do next ?  Thank you very much

**Comment by TahaTesser** [comment]
Hi @andrehen27 
Just make sure your link is properly loading image in a browser and provide that link to your image url

**Comment by andrehen27** [comment]
the link is properly loading image in browser , and in my emulator the image has shown too but flutter give me this error feedback , will it become problem in future?

**Comment by TahaTesser** [comment]
hi @andrehen27 
Just make sure you don't provide null to your image url.
You can ty providing a placeholder image while `sellerPicture` isn't available 
Thank you
