### ISSUE TITLE
ld: library not found for -lscreen

### ISSUE THREAD

**Issue by ekahoggy** [flutter/flutter#52948]
I Have an Error when im running flutter on IOS
Here Is My Error.
Please Help me to fix this
Thank's.

> Ld /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Bolong.app/Bolong normal x86_64 (in target 'Bolong' from project 'Bolong')
>     cd /Users/landa/Flutter/bolong/ios
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios8.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/AppAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/BoringSSL-GRPC -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FMDB -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseCore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseCoreDiagnostics -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseDatabase -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseDynamicLinks -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseFirestore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseInstallations -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseInstanceID -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseMessaging -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GTMAppAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleDataTransport -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleDataTransportCCTSupport -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleUtilities -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/PromisesObjC -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Protobuf -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Reachability -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/abseil -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/cloud_firestore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/connectivity -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_auth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_core -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_database -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_dynamic_links -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_messaging -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/gRPC-C++ -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/gRPC-Core -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/google_sign_in -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/launch_review -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/leveldb-library -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/nanopb -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/open_appstore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/path_provider -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/share -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/shared_preferences -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/sqflite -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/url_launcher -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/video_player -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/wakelock -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/webview_flutter -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/AppAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/BoringSSL-GRPC -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FMDB -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseCore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseCoreDiagnostics -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseDatabase -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseDynamicLinks -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseFirestore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseInstallations -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseInstanceID -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/FirebaseMessaging -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GTMAppAuth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleDataTransport -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleDataTransportCCTSupport -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/GoogleUtilities -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/PromisesObjC -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Protobuf -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Reachability -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/abseil -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/cloud_firestore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/connectivity -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_auth -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_core -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_database -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_dynamic_links -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/firebase_messaging -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/gRPC-C++ -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/gRPC-Core -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/google_sign_in -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/launch_review -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/leveldb-library -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/nanopb -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/open_appstore -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/path_provider -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/share -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/shared_preferences -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/sqflite -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/url_launcher -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/video_player -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/wakelock -L/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/webview_flutter -L/Users/landa/Flutter/bolong/ios/Flutter -F/Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator -F/Users/landa/Flutter/bolong/ios/Pods/../Flutter -F/Users/landa/Flutter/bolong/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/landa/Flutter/bolong/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/landa/Flutter/bolong/ios/Pods/GoogleSignIn/Frameworks -F/Users/landa/Flutter/bolong/ios/Pods/../Flutter -F/Users/landa/Flutter/bolong/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/landa/Flutter/bolong/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/landa/Flutter/bolong/ios/Pods/GoogleSignIn/Frameworks -F/Users/landa/Flutter/bolong/ios/Flutter -filelist /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Intermediates.noindex/Bolong.build/Debug-iphonesimulator/Bolong.build/Objects-normal/x86_64/Bolong.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -object_path_lto -Xlinker /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Intermediates.noindex/Bolong.build/Debug-iphonesimulator/Bolong.build/Objects-normal/x86_64/Bolong_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Intermediates.noindex/Bolong.build/Debug-iphonesimulator/Bolong.build/Objects-normal/x86_64/Bolong.swiftmodule -ObjC -lAppAuth -lBoringSSL-GRPC -lFMDB -lFirebaseAuth -lFirebaseCore -lFirebaseCoreDiagnostics -lFirebaseDatabase -lFirebaseDynamicLinks -lFirebaseFirestore -lFirebaseInstallations -lFirebaseInstanceID -lFirebaseMessaging -lGTMAppAuth -lGTMSessionFetcher -lGoogleDataTransport -lGoogleDataTransportCCTSupport -lGoogleUtilities -lPromisesObjC -lProtobuf -lReachability -labseil -lc++ -lcloud_firestore -lconnectivity -lfirebase_auth -lfirebase_core -lfirebase_database -lfirebase_dynamic_links -lfirebase_messaging -lgRPC-C++ -lgRPC-Core -lgoogle_sign_in -licucore -llaunch_review -lleveldb-library -lnanopb -lopen_appstore -lpath_provider -lshare -lshared_preferences -lsqflite -lsqlite3 -lurl_launcher -lvideo_player -lwakelock -lwebview_flutter -lz -framework AssetsLibrary -framework CFNetwork -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework FIRAnalyticsConnector -framework FirebaseAnalytics -framework Flutter -framework Foundation -framework GoogleAppMeasurement -framework GoogleSignIn -framework LocalAuthentication -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework AuthenticationServices -weak_framework UserNotifications -weak_framework WebKit -ObjC -lBoringSSL-GRPC -lAppAuth -lFMDB -lFirebaseAuth -lFirebaseCore -lFirebaseCoreDiagnostics -lFirebaseDatabase -lFirebaseDynamicLinks -lFirebaseFirestore -lFirebaseInstallations -lFirebaseInstanceID -lFirebaseMessaging -lGTMAppAuth -lGTMSessionFetcher -lGoogleDataTransport -lGoogleDataTransportCCTSupport -lGoogleUtilities -lPromisesObjC -lProtobuf -lReachability -labseil -lc++ -lcloud_firestore -lconnectivity -lfirebase_auth -lfirebase_core -lfirebase_database -lfirebase_dynamic_links -lfirebase_messaging -lgRPC-C++ -lgRPC-Core -lgoogle_sign_in -licucore -llaunch_review -lleveldb-library -lnanopb -lopen_appstore -lpath_provider -lscreen -lshare -lshared_preferences -lsqflite -lsqlite3 -lurl_launcher -lvideo_player -lwebview_flutter -lz -framework AssetsLibrary -framework CFNetwork -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework FIRAnalyticsConnector -framework FirebaseAnalytics -framework Flutter -framework Foundation -framework GoogleAppMeasurement -framework GoogleSignIn -framework LocalAuthentication -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework AuthenticationServices -weak_framework UserNotifications -weak_framework WebKit -ObjC -lAppAuth -lBoringSSL-GRPC -lFMDB -lFirebaseAuth -lFirebaseCore -lFirebaseCoreDiagnostics -lFirebaseDatabase -lFirebaseDynamicLinks -lFirebaseFirestore -lFirebaseInstallations -lFirebaseInstanceID -lFirebaseMessaging -lGTMAppAuth -lGTMSessionFetcher -lGoogleDataTransport -lGoogleDataTransportCCTSupport -lGoogleUtilities -lPromisesObjC -lProtobuf -lReachability -labseil -lc++ -lcloud_firestore -lconnectivity -lfirebase_auth -lfirebase_core -lfirebase_database -lfirebase_dynamic_links -lfirebase_messaging -lgRPC-C++ -lgRPC-Core -lgoogle_sign_in -licucore -llaunch_review -lleveldb-library -lnanopb -lopen_appstore -lpath_provider -lshare -lshared_preferences -lsqflite -lsqlite3 -lurl_launcher -lvideo_player -lwakelock -lwebview_flutter -lz -framework AssetsLibrary -framework CFNetwork -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework FIRAnalyticsConnector -framework FirebaseAnalytics -framework Flutter -framework Foundation -framework GoogleAppMeasurement -framework GoogleSignIn -framework LocalAuthentication -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework AuthenticationServices -weak_framework UserNotifications -weak_framework WebKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Intermediates.noindex/Bolong.build/Debug-iphonesimulator/Bolong.build/Bolong.app-Simulated.xcent -framework Flutter -framework App -lPods-Bolong -Xlinker -dependency_info -Xlinker /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Intermediates.noindex/Bolong.build/Debug-iphonesimulator/Bolong.build/Objects-normal/x86_64/Bolong_dependency_info.dat -o /Users/landa/Library/Developer/Xcode/DerivedData/Runner-epdztkvgqobgbvcqhckajnlinjwz/Build/Products/Debug-iphonesimulator/Bolong.app/Bolong
> 
> ld: library not found for -lscreen
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by VladyslavBondarenko** [comment]
Hi @ekahoggy 
could you provide your `flutter doctor -v`?
isn't this your case https://github.com/flutter/flutter/issues/20530#issuecomment-497944297?

**Comment by ekahoggy** [comment]
> Hi @ekahoggy
> could you provide your `flutter doctor -v`?
> isn't this your case [#20530 (comment)](https://github.com/flutter/flutter/issues/20530#issuecomment-497944297)?

thanks...
but i'm already fix it yesterday.

<img width="987" alt="Screen Shot 2020-03-21 at 09 38 36" src="https://user-images.githubusercontent.com/12228588/77217821-e8c87700-6b57-11ea-952b-e3e8f3e64499.png">

i removed 'Other Linked' -> l-screen
