### ISSUE TITLE
flutter run takes forever 

### ISSUE THREAD

**Issue by joydeep2899** [flutter/flutter#52942]
## Steps to Reproduce

1. flutter run 
2. ...
3. ...

## Logs

```
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/joydeep/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/joydeep/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/joydeep/Android/Sdk
    • Java binary at: /home/joydeep/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/joydeep/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • RMX1851 • 383e36e2 • android-arm64 • Android 10 (API 29)

**Comment by joydeep2899** [comment]
Launching lib/main.dart on RMX1851 in debug mode...
Running Gradle task 'assembleDebug'...                                 ⣻

**Comment by VladyslavBondarenko** [comment]
Hi @joydeep2899 
what Linux version do you use?
can it be your case https://github.com/flutter/flutter/issues/50507?

**Comment by joydeep2899** [comment]
It's Ubuntu 19.10

**Comment by VladyslavBondarenko** [comment]
@joydeep2899 
What kernel version do you have? 
Are you experiencing this if you try master channel?

**Comment by joydeep2899** [comment]
My issue got resolved turns out Gradle wasn't updated which was causing the issue
