### ISSUE TITLE
Execution failed for task ':shared_preferences_macos:javaPreCompileDebug'.

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#52954]
When I execute flutter upgrade --force command to update flutter, I run the flutter program again and I get the following error,

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared_preferences_macos:javaPreCompileDebug'.
> Could not resolve all files for configuration ':shared_preferences_macos:debugCompileClasspath'.
   > Could not download flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter_embedding_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter_embedding_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.112] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 4s
Exception: Gradle task assembleDebug failed with exit code 1

flutter doctor -v

[√] Flutter (Channel master, v1.16.2-pre.25, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)
    • Flutter version 1.16.2-pre.25 at E:\flutter\flutter
    • Framework revision ec8448d0a3 (9 hours ago), 2020-03-20 01:46:03 -0400
    • Engine revision fd60ddf751
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 5b21a43c55)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\haibo\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\haibo\AppData\Local\Android\Sdk
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @haibowen 
Are you sure using `shared_preferences` and not `shared_preferences_macos`?
Thank you

**Comment by haibowen** [comment]
> 嗨@haibowen
> 你肯定用`shared_preferences`不`shared_preferences_macos`？
> 谢谢

Ok because it was the shared_preferences that have been used before, but after upgrading flutter upgrade, the compiler reports this error, which is very strange

**Comment by haibowen** [comment]
> > 嗨@haibowen
> > 你肯定用`shared_preferences`不`shared_preferences_macos`？
> > 谢谢
> 
> Ok because it was the shared_preferences that have been used before, but after upgrading flutter upgrade, the compiler reports this error, which is very strange

~~~~
Thanks, I executed gradlew clean in the android directory and then switched flutter to stable after running it without any problems
