### ISSUE TITLE
Facebook Ads Widget for Android and iOS

### ISSUE THREAD

**Issue by johnmollaghan** [flutter/flutter#52950]
## Proposal

Create a widget for showing Native Facebook Ads (banners, native and interstitial) on both Android and iOS. Similar to what is there for Admob but just for Native Facebook Ads (not via Admob mediation)

**Comment by stuartmorgan** [comment]
Closing as out of scope; we don't general wrap third-party, non-system SDKs. This request should be directed to the SDK developer, and failing that could be implemented by the community.
