### ISSUE TITLE
Devicelab stopped running all linux-vm tests (March 20, 2020)

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#52957]
![linux-vm-down](https://user-images.githubusercontent.com/211513/77178805-d6313d80-6a84-11ea-8977-c17eca18c82b.png)

Affected tests:

- dartdocs
- web_benchmarks_canvaskit
- web_benchmarks_html
- technical_debt__cost

/cc @godofredoc @digiter

**Comment by keyonghan** [comment]
All VM are back online to work well. Closing the issue.

**Comment by yjbanov** [comment]
Thanks for the fast response!

**Comment by godofredoc** [comment]
We'll need a fix, sending PR
