### ISSUE TITLE
Flutter 1.12 app crashes on iPhone 4S (iOS 9.3.6) device

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#52962]
Hi there,
I have an app which recently I have updated to Flutter 1.12. Once I have pushed the release to Apple Store, I have reported crash from one of my users - they have iPhone 4S (iOS 9.3.6) device.
Prior that when my app was built with **Flutter v1.9.1+hotfix.6** I have no such issues. 
Here is my `flutter doctor -v` output:

> 
> [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
>     • Flutter version 1.12.13+hotfix.8 at d:\DevTools\flutter
>     • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at D:\DevTools\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_SDK_ROOT = D:\DevTools\Android\Sdk
>     • Java binary at: D:\DevTools\android-studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at D:\DevTools\android-studio
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 

I realize the feedback I am giving you guyes is limited, however, since I have no such hardware in possession and in general I have no much of experience with iOS devices, I would appreciate any advice how to proceed on this topic. 
Thanks!

**Comment by iapicca** [comment]
Hi @angel1st 
can you please provide the crash logs you are receiving;

ideally I'd for `flutter run --release --verbose`,
but if I understand correctly you don not have the possibility 
of testing you app on a physical iPhone 4s, therefore
even if not a comprehensive representation of the situation 
could you provide your `flutter run --verbose` (on a iOS 9.3.6)
your `flutter build ios --verbose` and your `pubspec.yaml`
Thank you

**Comment by angel1st** [comment]
Hey @iapicca and thanks for answering. I can provide 2 out of 3 from the required deliverables, since I have no iOS 9.3.6 device on my end.
Here they are:
[flutter build ios --verbose output](https://github.com/flutter/flutter/files/4368548/biorhythms-build-2020-03-23.log)
[pubspec.yaml zip](https://github.com/flutter/flutter/files/4368557/pubspec.zip)

One note though - the very same app has been successfully built with **Flutter v1.9.1+hotfix.6**. Once, I moved to **Flutter 1.12**, I have had the complain.

**Comment by iapicca** [comment]
thank you for the logs @angel1st

**Comment by angel1st** [comment]
Hey @iapicca, any chances for an issue update sooner rather than latter?

**Comment by angel1st** [comment]
@iapicca - any news on this one. At least a feedback the team is working on it?

**Comment by iapicca** [comment]
Hi @angel1st 
are you still experiencing the issue with the latest stable (or above)?
If so could you please provide your `flutter doctor -v`
and your `crash logs`
Thank you

**Comment by angel1st** [comment]
@iapicca - let me check and see if the end customer is still available. I release an updated app today and hopefully will get the customer on board in the next few days.

**Comment by angel1st** [comment]
@iapicca - I have compiled and released my app with Flutter 1.17.1. Unfortunately, the user reported, she still has the very same issue on her iOS 4s phone.
Below is my `flutter doctor -v` output:

> [✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.17.1 at /Users/angel/development/flutter
    • Framework revision f7a6a7906b (8 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

> [✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

> [!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

> [✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

> [!] Connected device
    ! No devices available

**Comment by chinmaygarde** [comment]
Without a stack trace or a reduced test case, there isn't much progress the team can make on this.

**Comment by angel1st** [comment]
@chinmaygarde - if you have a look [at the issue's initial discussion](https://github.com/flutter/flutter/issues/52962#issuecomment-602503867) you would understand I cannot send you a stack trace due to specific limitations. 
I can however refer to [another case](https://github.com/flutter/flutter/issues/35838) where the Flutter team was resourceful enough to find a specific device and test on its own end. I can provide iOS binary upon request.
I understand this is probably an edge case, however, if you state Flutter supports certain devices and OSes, you as a team should stand behind your statement.

**Comment by chinmaygarde** [comment]
In the linked issue, there was a reduced test case. Something that only used Flutter APIs with all the extraneous dependencies removed. If there is an issue in such a reduced test case, that is a good starting point for an investigation. Unfortunately, having just the binary is not sufficient for an investigation.

An observation: The `pubspec.yaml` you linked contains numerous dependencies as well. Without a backtrace or any logs, it is hard to tell where the issue originated.

Closing this as in-actionable. Please re-open if you are able to provide more information. Thanks.
