### ISSUE TITLE
I run my app in web platform and I received this errors, my app cannot run on web.

### ISSUE THREAD

**Issue by vinhtrong** [flutter/flutter#52963]
main.dart.js:8 GET http://localhost:51533/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ main.dart.js:8
main.dart.js:17 GET http://localhost:51533/flutter/bin/cache/dart-sdk/lib/dev_compiler/kernel/amd/require.js net::ERR_ABORTED 404 (Not Found)

**Comment by mo-ah-dawood** [comment]
same here

**Comment by iapicca** [comment]
Hi @vinhtrong @mo-ah-dawood 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by vinhtrong** [comment]
this below that what I received by flutter doctor -v
`[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.15.17 at C:\flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\TrongNQ\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\TrongNQ\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.40.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome              • chrome        • web-javascript • Google Chrome 80.0.3987.149
    • Web Server          • web-server    • web-javascript • Flutter Tools

• No issues found!`

**Comment by vinhtrong** [comment]
And I ran my application by following these command:
`flutter create myapp`
`cd myapp`
`flutter run -d Chrome --verbose`

[  +66 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +169 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[   +1 ms] executing: [C:\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+6765 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[   +2 ms] From https://github.com/flutter/flutter
            * branch                HEAD       -> FETCH_HEAD
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +111 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.15.17-0-g2294d75bf
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +83 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +86 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +209 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +94 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +85 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] executing: C:\Users\TrongNQ\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +45 ms] Exit code 0 from: C:\Users\TrongNQ\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
[  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +389 ms] Generating E:\working\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +156 ms] Launching lib\main.dart on Chrome in debug mode...
[ +127 ms] Serving DevTools at http://127.0.0.1:64398

[  +11 ms] Updating assets
[ +180 ms] Syncing files to device Chrome...
[  +94 ms] Generating E:\working\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +65 ms] <- reset
[  +18 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\TrongNQ\AppData\Local\Temp\flutter_tool.87400e1a-6cd8-11ea-b5f7-bd94b3db1563\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages E:\working\myapp\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\TrongNQ\AppData\Local\Temp\flutter_tools.87400e1b-6cd8-11ea-b5f7-bd94b3db1563 --filesystem-scheme org-dartlang-app --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +46 ms] <- compile org-dartlang-app:///web_entrypoint.dart
[+29672 ms] Syncing files to device Chrome... (completed in 29,879ms, longer than expected)
[+87367 ms] Synced 20.7MB.
[   +1 ms] <- accept
[ +438 ms] [CHROME]:
[   +5 ms] [CHROME]:DevTools listening on ws://127.0.0.1:64520/devtools/browser/831bffa0-b59b-4e70-80e5-0e6d1650f43d

**Comment by vinhtrong** [comment]
![image](https://user-images.githubusercontent.com/6815363/77292811-97fd7d80-6d13-11ea-9ab6-9c91aff0e851.png)

**Comment by mo-ah-dawood** [comment]
solved in master channel

**Comment by vinhtrong** [comment]
> solved in master channel in this PR
> [1.15.19](https://github.com/flutter/flutter/releases/tag/v1.15.19)

It's solved in my project. Thanks a lot.

**Comment by HawkarShwany** [comment]
> 
> 
> > solved in master channel in this PR
> > [1.15.19](https://github.com/flutter/flutter/releases/tag/v1.15.19)
> 
> It's solved in my project. Thanks a lot.

I have similar issue. did you change the SDK version to 1.15.19 to solve it? I can't change it to that version. Is there another solution?

**Comment by mo-ah-dawood** [comment]
> > > solved in master channel in this PR
> > > [1.15.19](https://github.com/flutter/flutter/releases/tag/v1.15.19)
> > 
> > 
> > It's solved in my project. Thanks a lot.
> 
> I have similar issue. did you change the SDK version to 1.15.19 to solve it? I can't change it to that version. Is there another solution?

you have to change the channel to master 
This version is not in not puplished in beta or stable channel
