### ISSUE TITLE
dialog_test.dart "Pressed button changes appearance and dividers disappear" broken on the Web

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#52960]
I enabled `dialog_test.dart` on the Web, but had to skip the test titled "Pressed button changes appearance and dividers disappear" as it fails a paint expectation. I couldn't figure out at a glance what's wrong. Leaving this issue to investigate in the future.

All other tests in `dialog_test.dart` are passing.

**Comment by pedromassangocode** [comment]
Still valid since the test is question is being skipped for web on latest `master` channel.

https://github.com/flutter/flutter/blob/a8281e31afa9dddfa0764f59128c3a2360c48f49/packages/flutter/test/cupertino/dialog_test.dart#L808-L919

**Comment by darrenaustin** [comment]
This appears to have been fixed. I reenabled the test with #87538, and everything appears to be working fine.
