### ISSUE TITLE
Move cursor to the begin of TextFormField when lose focus

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#52988]
Please check this url in stackoverflow

Move cursor to the begin of TextFormField when lose focus
https://stackoverflow.com/questions/54709572/move-cursor-to-the-begin-of-textformfield-when-lose-focus

His solution is working but this should not be the case. i dont have any use of a TextEditingController and would rather use the initialValue property. However, the behavior that the textfield does not move the cursor back to offset = 0 if it loses focus is not possible. not unless a workaround can be applied to that stackoverflow post.

Also, that solution will only apply for onFieldSubmitted. one has to listen to all other events just to cater to this small feature.

I hope this can be considered. I believe this is a normal feature.

**Comment by iapicca** [comment]
Hi @chitgoks 
I can reproduce the issue you are describing with this [code](https://dartpad.dev/427e68dd12bdc42566204fbb65e904a5)
thank you for reporting this


opposite of https://github.com/flutter/flutter/issues/11416

**Comment by TahaTesser** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (3 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by gspencergoog** [comment]
This isn't correct behavior for a text field: the current cursor position should be retained when focus is regained. If you want this behavior, you should use a TextEditingController.
