### ISSUE TITLE
speed up the travis bot

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#5299]
Our travis bot has slowed down - it now generates the docs for docs.flutter.io. We should split this off into a separate bot so the main one stays fast.

**Comment by sethladd** [comment]
Good idea. Can we trigger the doc generation/upload only if Travis is otherwise green?

**Comment by devoncarew** [comment]
Yeah, it should be possible to do something like only upload docs if the repo analyzes cleanly. Or we could do something like only upload docs from pushes to the `alpha` branch.

**Comment by sethladd** [comment]
@abarth suggested we upload docs on master, but if we're pushing alpha into internal, and telling our external users to use alpha, then uploading docs on alpha merges sgtm

**Comment by sethladd** [comment]
We should do this. But I'm going to close to help keep the tracker clean. Please reopen if someone wants to do this.
