### ISSUE TITLE
Inner shadow for BoxShadow

### ISSUE THREAD

**Issue by AcnoSaga** [flutter/flutter#52999]
Can we have an inset property on BoxShadow similar to CSS to have the effect of an inner shadow ?

**Comment by shallx** [comment]
Badly need this feature. I hope devs see this issue

**Comment by deepak-penaganti** [comment]
> This should be resolved by #84733

New PR #86504 should resolve this

**Comment by AlexanderFarkas** [comment]
Any updates on this?

**Comment by victorsanni** [comment]
This should be closed as a duplicate of https://github.com/flutter/flutter/issues/18636.
