### ISSUE TITLE
no pubspec.yaml found

### ISSUE THREAD

**Issue by Alkahirah** [flutter/flutter#52997]
Hi everyone 
I'm using flutter so I found good UI in Github I wanted to open it in my android studio via File>New>Project from version control>Git
then I did Get dependencies

It worked for the first time but when I tried to open another UI from Github but showed Error 'no pubspec.yaml found'

but when I saw the project files I found the pubspec.yaml
![Ashampoo_Snap_2020 03 21_09h55m05s_001_](https://user-images.githubusercontent.com/34009670/77221466-0c40f100-6b5b-11ea-9402-1df2f97c894f.png)

**Comment by iapicca** [comment]
HI @Alkahirah 
can you please provide your `flutter doctor -v` ,
your `flutter pub get --verbose`
Thank you

**Comment by TahaTesser** [comment]
Hi @Alkahirah 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
