### ISSUE TITLE
[Add2App]ios ui freeze

### ISSUE THREAD

**Issue by nongjuanfeng** [flutter/flutter#52992]
<img width="663" alt="截屏2020-03-21上午10 29 51" src="https://user-images.githubusercontent.com/56825407/77217647-f3d2d580-6b5e-11ea-805e-242af9935b54.png">

<img width="523" alt="截屏2020-03-21上午10 29 35" src="https://user-images.githubusercontent.com/56825407/77217678-35fc1700-6b5f-11ea-9e94-48a520f2b242.png">
<img width="993" alt="截屏2020-03-20下午8 36 03" src="https://user-images.githubusercontent.com/56825407/77217696-56c46c80-6b5f-11ea-981a-574491e7c648.png">

**Comment by iapicca** [comment]
Hi @nongjuanfeng 
could you please provide your `flutter attach --verbose` 
and your `pubspec.yaml`.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by TahaTesser** [comment]
Hi @nongjuanfeng 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
