### ISSUE TITLE
`flutter start` doesn't give good error messages when it can't find main.dart

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#53]
When I try to `flutter start` any of the example programs `widgets`, `fitness` or `rendering` I get an error like the following:

Downloading Sky Snapshot from the cloud, one moment please...
Downloading Sky Shell from the cloud, one moment please...
[1108/213053:FATAL:loader.cc(21)] Check failed: base::ReadFileToString(path, &source). /home/dmta/flutter/flutter/examples/rendering/./lib/main.dart

The other examples I have tried worked fine.

**Comment by abarth** [comment]
There isn't a "lib/main.dart" in the rendering examples.  Instead, you need to use the `-t` option to specify which one you want to run:

```
$ flutter start -t render_grid.dart
```

Assuming that works for you, we should improve the error message you get so that it's obvious what's happening.

**Comment by DavidMihola** [comment]
Yes, now that you say it, it makes sense. But reading the error message I originally thought that something must be wrong with the `ReadFileToString` function... I wouldn't have thought of a missing file...

**Comment by abarth** [comment]
Yeah, we should improve the messages in two ways:

- [ ] The `flutter` command should check whether the target exists and print a useful message if it doesn't.
- [ ] When the snapshotter gets into trouble, it should print sensible messages instead of acting like it crashed unexpectedly.
