### ISSUE TITLE
"flutter doctor" command not working and it says "Operation not supported"

### ISSUE THREAD

**Issue by githubkonyravi** [flutter/flutter#53004]
I am trying to install and setup flutter in my mac OS Mojave v10.14.6.

After unzipping the flutter sdk and setting path variable, i am trying to run flutter doctor command. But, it throws the below error.

```
shlock: link(/Volumes/MyData/Training/Flutter_SDK/flutter/bin/cache/shlock10893, /Volumes/MyData/Training/Flutter_SDK/flutter/bin/cache/.upgrade_lock): Operation not supported
shlock: link(/Volumes/MyData/Training/Flutter_SDK/flutter/bin/cache/shlock10895, /Volumes/MyData/Training/Flutter_SDK/flutter/bin/cache/.upgrade_lock): Operation not supported
```
Any idea what is happening here? Did i miss anything?  Below is flutter version i downloaded.

flutter_macos_v1.12.13+hotfix.8-stable.zip

Did not find any solution in google search and so, i am raising this issue. Appreciate any quick help in this.

**Comment by VladyslavBondarenko** [comment]
Hi @githubkonyravi 
there is probably lack of permissions, does it help if you move flutter somewhere in your user directory?

**Comment by VladyslavBondarenko** [comment]
Possibly related to https://github.com/flutter/flutter/issues/53016

**Comment by rekire** [comment]
Might be helpful as workaround: https://github.com/flutter/flutter/issues/53016#issuecomment-605791594

**Comment by TahaTesser** [comment]
Hi @githubkonyravi 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
