### ISSUE TITLE
Golden image tests are flaky

### ISSUE THREAD

**Issue by nioncode** [flutter/flutter#53009]
I have the following (reduced) test code, which has a widget test and a widget test :
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class LoginPage extends StatefulWidget {
  @override
  LoginPageState createState() => LoginPageState();
}

class LoginPageState extends State<LoginPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: Image(
          width: 100,
          height: 100,
          image: AssetImage('assets/asset-icon.png'),
        ),
      ),
    );
  }
}

void main() {
  testWidgets('flaky', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(home: LoginPage()));
    // expect something, not important here
  });

  testWidgets('Golden test', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(home: LoginPage()));
    await expectLater(
        find.byType(LoginPage), matchesGoldenFile('LoginPage_golden.png'));
  });
}
```

When running the tests with `flutter test`, everything works fine, i.e. both tests pass.
When running the tests with `flutter test --plain-name "Golden test" test/LoginPage_test.dart`, the golden image test breaks, because the image is not rendered in the test widget, but it is present in the golden image.

I understand that the golden test was wrong from the beginning and should have precached the image (as shown in https://github.com/flutter/flutter/issues/38997), i.e the following makes the golden test pass even if run as a single test:
```dart
  testWidgets('Golden test2', (WidgetTester tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(MaterialApp(home: LoginPage()));
      var element = find.byType(Image).evaluate().first;
      Image widget = element.widget;
      await precacheImage(widget.image, element);
      await tester.pumpAndSettle();
    });
    await expectLater(
        find.byType(LoginPage), matchesGoldenFile('LoginPage_golden.png'));
  });
```

However, shouldn't the test also fail when running with `flutter test`? Currently, the tests are not completely independet of each other, which could introduce other weird issues that are hard to debug. Maybe the image cache is shared between all tests and this is the reason for this? Is this by design or should all state be cleaned between tests? Is there any documentation about which state is shared across individual tests?

Used flutter version:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US)
    • Flutter version 1.12.13+hotfix.8 at /opt/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/developer/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/developer/android-sdk
    • ANDROID_SDK_ROOT = /home/developer/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by dnfield** [comment]
Yes, the image cache is shared between the two tests.

If you reversed the order of the original tests, I would expect the first one to always fail - it seems like you just were lucky (unlucky? :) that the first test took long enough to run that the image finished loading for the second test.

I'm going to close this, as you seem to have figured out the right way to do this (use tester.runAsync).  You might have even better luck with just doing `tester.runAsync` to precache the image(s) you actually want to use in the test.  Unfortunately, golden testing tests with images is difficult.

**Comment by nioncode** [comment]
@dnfield thanks for clarifying. Is there any documentation about which state is shared across tests and what to watch out for (like the shared image cache)?

**Comment by dnfield** [comment]
Any global state in flutter will be shared across tests in the same file, u less it is reset.  I don't think we have much documentation around that, but things like the bindings, image cache, and system channels come to mind.
