### ISSUE TITLE
Release version is shipping with a debug page

### ISSUE THREAD

**Issue by Mikkelet** [flutter/flutter#53006]
Hey guys, I just wanted to share something odd: we're developing our app, and when my colleage tries to login with facebook, it fails, and flutter is now in debug mode. This screenshot is from an official release in the app store:

https://i.imgur.com/LbkDkLE.png

It happens when his facebook login attempt fails, but I'm not sure if it correlated. I can expand if requested

**Comment by iapicca** [comment]
Hi @Mikkelet 
can you please provide your `flutter doctor -v` 
and your `flutter run --release --verbose` 
Thank you

**Comment by TahaTesser** [comment]
Hi @Mikkelet 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
