### ISSUE TITLE
Dart analyzer crashes randomly on Emulator or real device

### ISSUE THREAD

**Issue by dodancs** [flutter/flutter#53014]
## Steps to Reproduce

1. Create an app - a basic one will suffice
2. Run it in debugging mode in VSCode
3. Do nothing (like do normal stuff, write code, use autocomplete, etc.) and the error pops up

__The Dart Analyzer has terminted__

This error essentially kills everything Dart related, so you cannot use autocomplete, syntax checking, anything. There is a popup that allows you to show logs or restart it.

![Error dialog](http://puu.sh/Fndlk/e8b724115c.png)

## Logs

Dart log:
```
[12:12:15] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\dodancs\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\dodancs\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users\d…
```

Flutter doctor log:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale sk-SK)
    • Flutter version 1.12.13+hotfix.8 at C:\Programs\Flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\dodancs\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\dodancs\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ONEPLUS A6000 • a243106e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @dodancs 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, 
your `flutter run --verbose`.

Are you experiencing the issue only with VS Code or with Android Studio as well?
Thank you

**Comment by pedromassangocode** [comment]
Hi @dodancs 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, 
your `flutter run --verbose`.

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
