### ISSUE TITLE
flutter format seems to work wrongly on Windows

### ISSUE THREAD

**Issue by Tokenyet** [flutter/flutter#53018]
#### Description ####
Recently, I added a pre-commit in git-hook to format the code with `flutter format`, but the result seems to be conflict with the `indent-multi-line-argument-and-parameter-lists-by-2-characters` in [flutter's style guild](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#indent-multi-line-argument-and-parameter-lists-by-2-characters)

![image](https://user-images.githubusercontent.com/6420527/77231608-19032a80-6bd7-11ea-9af1-176f6fbf13c7.png)

Here is the result, that I ran before and after,  2-characters are changed to 4-character by `flutter format`

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.592], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Is that what configuration in vscode need to be config? or I miss something else 😕 

The pre-commit I used.
```
#!/bin/sh
exec flutter format lib/ test/
```

**Comment by jonahwilliams** [comment]
Confusingly `flutter format` is just a wrapper around `dartfmt`. The flutter style guide is for hand formatted files in the repo, and not something that developers using flutter need to follow (though they certainly can!)

**Comment by Tokenyet** [comment]
@jonahwilliams , Oh! Sorry for this issue, I just thought `flutter format` should follow the guide, that's my fault 😆 Thanks for your help.

**Comment by jonahwilliams** [comment]
No worries!
