### ISSUE TITLE
flutter doctor crashes with iOS simulator

### ISSUE THREAD

**Issue by sloisel** [flutter/flutter#53019]
Hi,
flutter doctor has instructed me to file an issue here because it crashed. This happens only when I'm trying to use the simulator with `open -a Simulator`. I can run on my ipad just fine. Here is what it prints:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by VladyslavBondarenko** [comment]
Hi @sloisel 
error code -17 means LOCKDOWN_E_PASSWORD_PROTECTED https://github.com/flutter/flutter/issues/49375

**Comment by sloisel** [comment]
Thanks for the information. Just to be clear, I am available if you need anything more from me. I submitted this bug report because I was instructed to do so by flutter doctor, but this is not affecting me right now; when I press the run button in Android Studio, it fires up the simulator and runs it. I don't know why flutter doctor is crashing.

**Comment by jmagman** [comment]
Hm I'm not sure why this would only happen with a simulator open.  In any case it won't crash and would give a better error as of https://github.com/flutter/flutter/pull/49854.

If you are still able to reproduce, can we get the output of `flutter doctor -vv` (note the extra `v`)?

**Comment by sloisel** [comment]
Sorry, I can't repro anymore. :(

I tried again and now I get `[✓] Connected device (1 available)` so `flutter doctor` does not crash.

**Comment by jmagman** [comment]
I'm going to close since I think this will manifest differently as of https://github.com/flutter/flutter/pull/49854.  If you see this again and are able to reproduce, please reopen with the results from `flutter doctor -vv`.  Thanks for filing this!
