### ISSUE TITLE
Provide a way for a webview to report an error in the onPageFinished callback

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#53023]
See b/151727643.

**Comment by mehmetf** [comment]
@amirh

**Comment by tvolkert** [comment]
@bparrishMines this is one of four webview issues marked as critical.  How's your bandwidth for being able to look at these?

**Comment by bparrishMines** [comment]
@tvolkert I'm working on this one now and I assigned it to myself.

**Comment by bparrishMines** [comment]
After looking for error reporting in the `Webview` implementation of each platform I found Android uses [onReceivedError](https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20android.webkit.WebResourceRequest,%20android.webkit.WebResourceError)) in its `WebviewClient` and iOS uses [webView:didFailNavigation:withError:](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455623-webview?language=objc) and [webView:didFailProvisionalNavigation:withError:](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455637-webview?language=objc) in its `WKNavigationDelegate`. 

To follow the style of `onPageFinished`, I think we should create a separate callback called `onReceivedError` that passes an error data class. (e.g. 
```typedef void ReceivedErrorCallback(WeviewError error);```
