### ISSUE TITLE
Video player does not work on android 7.1.1 - video_player

### ISSUE THREAD

**Issue by wilfredonoyola** [flutter/flutter#53028]
Hi!

I tested the video player with my android 7.1.1 got this problem with decode video. While with others devices this works fine.

I found some behaviors:
Android 7.1.1: First time: I open the view with a video player, this did not work! for second time I open the view with a video player this works fine. for third time is not display the video.

Error
`PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1]), null)`

Let me know your thoughts

**Comment by VladyslavBondarenko** [comment]
Hi @wilfredonoyola 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose` and perform actions that lead to the exception?

**Comment by TahaTesser** [comment]
Hi @wilfredonoyola 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
