### ISSUE TITLE
Items can't be clicked as their swipe animation finalizes

### ISSUE THREAD

**Issue by JPhilipp** [flutter/flutter#53021]
Not quite sure where to post this -- I've seen several otherwise greatly designed Flutter apps where a given clickable widget, like when swipe-scrolled sideways, can't be clicked as it finalizes its animation. For instance, this happens with the Reflectly story day widgets. As the animation is usally easing out (i.e. its near-final animation state is almost still), this can lead to certain micro-issues like the user having to click twice to open something without properly understanding why; one can also not navigate the app as intuitively fast as one wants to, but always has to wait for the animation to settle in.

So I guess my question is, is this a native issue with Flutter, or perhaps something not native but easy to run into given common Flutter coding patterns? And if so, could it be optimized? Or is this simply a result of the app using a non-suggested implementation pattern? Thanks!

**Comment by nt4f04uNd** [comment]
i guess this issue is about for example TabBarView - if you drag it, it is quite slow to settle back, and in this time, if user taps inside a tab, it will be treated as cancelled tap

i don't think "examples" and "documentation" labels are valid

cc @HansMuller

**Comment by Piinks** [comment]
I am going to de-dupe this with [#42588](https://github.com/flutter/flutter/issues/42588) to consolidate. Please follow that issue for updates, thank you!
