### ISSUE TITLE
Problema flutter doctor

### ISSUE THREAD

**Issue by andradefaker** [flutter/flutter#53025]
Ao executar o comando 'flutter doctor' através do prompt, aparece a mensagem abaixo.
(When executing the command 'flutter doctor' through the prompt, the message below appears.)
-
Doctor summary (to see all details, run flutter doctor -v):

Sending crash report to Google.
Crash report sent (report ID: 5664f4eed0a5d22f)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\Windows\System32>

**Comment by VladyslavBondarenko** [comment]
Hi @andradefaker 
could you attach that file `C:\Windows\System32\flutter_12.log`?

**Comment by TahaTesser** [comment]
Hi @andradefaker 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
