### ISSUE TITLE
dropdown menu items style unexpected behavior in version 1.15.17

### ISSUE THREAD

**Issue by zvikarp** [flutter/flutter#53026]
all was cool until upgrading my flutter (to new beta version). a dropdown with a color style started to behave weirdly.

here is my code:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

const List<String> items = <String>[
  'one',
  'two',
  'three',
];
String item = items[0];

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: DropdownButton<String>(
          value: item,
          style: TextStyle(color: Colors.red),
          items: items
              .map((String item) => DropdownMenuItem<String>(
                    value: item,
                    child: Text(item),
                  ))
              .toList(),
          onChanged: (String newItem) {},
        ),
      ),
    );
  }
}
``` 

the items in the dropdown have the color specified in the `TextStyle` but that is about it, when i remove that line the dropdown behaves as normal, see the diffs:
![image](https://user-images.githubusercontent.com/13397207/77236004-362dfe00-6bc3-11ea-8ccf-01fd450db13e.png)
![image](https://user-images.githubusercontent.com/13397207/77236013-4514b080-6bc3-11ea-8ea8-22cece5b0762.png)

i have run flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-IL)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.43.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

it doesn't happen in dartpad.

i solved it on my machine by changing [this line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown.dart#L1131) to: `TextStyle get _textStyle => Theme.of(context).textTheme.subtitle1.merge(widget.style);` (and although it seems to make seance, i can not explain why it worked in version 1.14.6 and now it doesn't, i looked at all commit to flutter and couldn't find what is causing this bug).  

it this something i should open a pr on, or maybe already fixed it newer releases?

**Comment by VladyslavBondarenko** [comment]
Hi @zvikarp 
I can't reproduce it with `beta v1.15.17` and your code.
Similar to https://github.com/flutter/flutter/issues/52018, but I can't reproduce it in `beta v1.15.17` with code from there as well.
Could you check is it fixed with dev channel?

**Comment by zvikarp** [comment]
hey, sorry for the late response.
i see from #52018 that the issue is solved in the dev channel, my bad not seeing that issue before opening this one.
