### ISSUE TITLE
List error

### ISSUE THREAD

**Issue by sandlib** [flutter/flutter#53039]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
type 'List<dynamic>' is not a subtype of type 'List<NewPage>' of 'function result'

**Comment by Abhishek01039** [comment]
Can you share some more information as well as the output of flutter doctor -v

**Comment by sandlib** [comment]
Issue solved By wrapping it with the required widget.

**Comment by Abhishek01039** [comment]
Then close the issue
