### ISSUE TITLE
DateTime.add() is wrong.

### ISSUE THREAD

**Issue by nhatnd9504** [flutter/flutter#53033]
## Steps to Reproduce

DateTime.add  is wrong!
1. `DateTime currentDate = DateTime.now(); //currentDate = "2020-03-20 00:15:27.582632"`
2. `DateTime date = currentDate.add(Duration(days: -13))` 
     output: date = "2020-03-09 00:15:27.582632"
3. `DateTime date1 = currentDate.add(Duration(days: -14))` 
     output: date1 = "2020-03-07 00:15:27.582632"

-13 and -14 => duration = 1.
but output date and date1 have duration = 2

**Expected results:** currentDate.add(Duration(days: -14)) => output: "2020-03-08"

**Actual results:** currentDate.add(Duration(days: -14)) => output: "2020-03-07"

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
@nhatnd9504 
Could you provide your `flutter doctor -v`?

**Comment by orestesgaolin** [comment]
Are you sure @nhatnd9504 that this really occurs? I just tested this in DartPad and the dates are correct. 
https://dartpad.dartlang.org/0e55ac2280d755efc991c4ec3bb40b42

**Comment by TahaTesser** [comment]
Hi @nhatnd9504 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
