### ISSUE TITLE
Norwegian code (no) translations are missing

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#53036]
Internal: b/150470184

There are no `_no` files here https://github.com/flutter/flutter/tree/master/packages/flutter_localizations/lib/src/l10n. It seems like we are not generating strings for Norwegian. 'no' is the Google-canonical language code for Norwegian.

**Comment by Hixie** [comment]
We support Bokmål as the standard code `nb`. We don't support Nynorsk (`nn`).
Are you asking for Nynorsk translations? Or?
There's not really a language code `no`.

**Comment by mehmetf** [comment]
It would be Bokmål. I think the keyword here was `Google-canonical`. When Google says `no`, they mean `nb`.

Would you be comfortable having Flutter localization delegates to use this alternative code as well and map it to `nb` or do you prefer this to be google3 specific?

**Comment by HansMuller** [comment]
The `deprecated Android/Java locales are modernized` test in packages/flutter_localizations/test/override_test.dart verifies that we map some obsolete locale names to their modern equivalents, but it doesn't cover `no` (which we supported a few years ago - https://github.com/flutter/flutter/pull/17788).  It looks like `no` isn't "Google-canonical" is a Java issue - http://www.localeplanet.com/java/no-NO/index.html. So perhaps we should automatically convert `no` to `nb`.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by HansMuller** [comment]
It looks like we've been incorrectly leaving out the 'no' (Norsk) locale, see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Even though Google's translations for 'nb' and 'no' are typically identical, it should be a supported locale per https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

**Comment by shihaohong** [comment]
Based on my current understanding, `nb`, `no`, and `nn` are distinct locales according to [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). It seems like the [original transition from `no` to `nb`](https://github.com/flutter/flutter/pull/17788) was necessary because Android devices use recognize `nb` and not `no`. 

However, as @HansMuller has pointed out, Google's translations for `nb` and `no` are essentially identical. 

We could solve this problem by adding logic to generate `nb` localization delegates off of `_no.arb` when `_nb.arb` is not present. This would allow us to handle `nb` for Android devices, as well as correctly pulling down the `_no.arb` files without having to do the manual change from `_no.arb` to `_nb.arb`.

**Comment by Hixie** [comment]
I don't have a strong opinion here. If we want to support no and nb as synonyms that works for me.

**Comment by shihaohong** [comment]
I'm going to share some relevant context from discussing with the i18n experts:
```
For Android `no` is never used.

Before Android N there was no way for a user to select `nn`, only `nb`
Starting with Android N one can select `nb` and / or `nn`.

There are no fallbacks or aliases, they behave as different languages 
(but no can never be selected in user settings)
...
In general no is not recommended, as it is ambiguous.
IANA lists it as a macrolanguage, with nb and nn as "members"

If one has to do a "naive" mapping then it might map no == nb
A better mapping might interpret no as "some kind of Norwegian", so it might 
match both (giving priority to nb if both exist)
LanguageMatcher is does "the better mapping", but it is not used in Android.
```

```
So in theory no could be used to indicate Norwegian in any form, eg. spoken or 
written as nb or written as nn.

In practice Bokmål is the preferred written form for 90% of the population of 
Norway, so for a lot of people and for a lot of software the language codes no 
and nb are simply taken to mean exactly the same thing.
```

My intention is to have `no` and `nb` be synonyms for now, since Android only recognizes `nb` vs `nn`.
