### ISSUE TITLE
Convert String to Color?

### ISSUE THREAD

**Issue by BasharAlayan** [flutter/flutter#53031]
My database has colors saved as a String like `"black"` and so I'm basically looking for a function like this: `Color.FromName("black")`

How can I convert to Color in this situation?

**Comment by Abhishek01039** [comment]
Color newColor = new Color(value);

**Comment by BasharAlayan** [comment]
it's not working because Color( ) accept only the type Int
`Color(int)`

**Comment by Abhishek01039** [comment]
you should do type-casting.

**Comment by BasharAlayan** [comment]
Actually, I wrote a code that maps Strings to Colors
`Map<String,Color>`

**Comment by br4dd** [comment]
Nice @BasharAlayan. I've fixed my problem.
