### ISSUE TITLE
CanvasKit in debug mode has trouble when specifying the font family

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#53035]
Run this in a CanvasKit debug mode app:

```
    ParagraphBuilder builder = ParagraphBuilder(ParagraphStyle())
      ..pushStyle(TextStyle(fontFamily: 'Courier New'))
      ..pushText('any');
    final Paragraph paragraph = builder.build()
      ..layout(ParagraphConstraints(width: 100));
```

At some point I saw exceptions related to this in my widgets, but now I'm having trouble reproducing that.  The crash in main happens consistently though.  

Also, the font family does not get respected in canvaskit, exceptions or not.

/cc @yjbanov @hterkelsen

**Comment by deakjahn** [comment]
@dnfield Pray tell me, how do you run CanvasKit in debug? I've recently stumbled upon this promising solution when looking for solutions to the original canvas' limitations but never saw how to run it in debug, only in release...

**Comment by dnfield** [comment]
On recent versions of flutter, you can press k on the console to toggle CanvasKit

**Comment by deakjahn** [comment]
Indeed. That's a well kept secret. Any chance of launching it from the IDE? I prefer to work from there, not the command line, and these console keys are not available there (Android Studio, if it makes any difference).

**Comment by jonahwilliams** [comment]
We could probably just detect the define and specify the right version when running

**Comment by deakjahn** [comment]
If it can be done in the app itself, I wouldn't even need a define...

**Comment by yjbanov** [comment]
There have been improvements in the font manager for CanvasKit recently. This should work now. I'll close but please feel free to reopen if it doesn't.
