### ISSUE TITLE
Can i run flutter app without installing Virtual Devices ?

### ISSUE THREAD

**Issue by aamadmin** [flutter/flutter#53042]
I have some issues installing HAXM installer since its not supported in my present system, can i use physical device to run flutter app ?  i have connected my phone with developer option enabled but V S Code is not listing devices to debug me firstapp code. Flutter doctor not showing device.

Can anyone help in this case ? 

[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\scr\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\UserName\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\UserName\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
exit code 0

**Comment by Abhishek01039** [comment]
Just connect your real device.

**Comment by aamadmin** [comment]
> Just connect your real device.

Hi Abhishek, I have connected to physical device and device dont show up.

**Comment by abhi9045** [comment]
Make sure you turn the usb debugging on your phone. Then, it will probably work.

**Comment by aamadmin** [comment]
Hi, Thanks, I have done USB debugging enabled on my device still device not listing in VSCode.

**Comment by aamadmin** [comment]
This error in virtual device 
![Virual_device](https://user-images.githubusercontent.com/29162178/77248268-3d97ea80-6c49-11ea-9ecb-e3fcc4bf5653.png)


No listed device
![nodev](https://user-images.githubusercontent.com/29162178/77248286-556f6e80-6c49-11ea-8f74-fd4e5840d916.png)

**Comment by abhi9045** [comment]
Also turn on install via USB option. This will help.

**Comment by aamadmin** [comment]
> install via USB option

Yes this is done already..

**Comment by abhi9045** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/39383758/77248418-38459a80-6c5f-11ea-9aa9-504fc6f82d30.png)

In VSCODE i think it doesn't show the option to select just run it.

**Comment by aamadmin** [comment]
This error shown, it wont debug..

![err](https://user-images.githubusercontent.com/29162178/77248488-cebb9100-6c4a-11ea-9740-e586c48238c5.png)

**Comment by abhi9045** [comment]
Now, just unplug and plug usb and also check the usb.🤣

**Comment by aamadmin** [comment]
> Now, just unplug and plug usb and also check the usb.

this i have done several times!

**Comment by abhi9045** [comment]
Which device do you have?

**Comment by aamadmin** [comment]
> Which device do you have?

Samsung S8

**Comment by abhi9045** [comment]
Have you set the path of flutter?

**Comment by aamadmin** [comment]
> Have you set the path of flutter?

Yes you can see n flutter doctor reply! all set..

**Comment by abhi9045** [comment]
Have you tried google usb driver?
link: [](https://developer.android.com/studio/run/win-usb)

**Comment by aamadmin** [comment]
> Have you tried google usb driver?
> link:[ https://developer.android.com/studio/run/win-usb](url)

Yes that's been installed, already.

**Comment by aamadmin** [comment]
> Have you tried google usb driver?
> link:[ https://developer.android.com/studio/run/win-usb](url)

Hey Hey Hey!! Thank you so much!!! The issue is **Samsung USB Driver** is not installed.. ! and now i installed from official website!! you saved my day!! thanks a lot for the alert!!

**Comment by abhi9045** [comment]
Thank you, its your perseverance.

**Comment by TahaTesser** [comment]
Hi @aamadmin 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
