### ISSUE TITLE
On macOS Catalina run 'flutter': zsh: permission denied: flutter

### ISSUE THREAD

**Issue by Charles1198** [flutter/flutter#53048]
I installed flutter follow steps on [入门: 在macOS上搭建Flutter开发环境](https://flutterchina.club/setup-macos/)，

My ~/.zshrc:
```
export PATH=/Users/yuejijia/development/flutter/bin:$PATH
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```

then I run 'flutter':
```
yuejijia@yuejideMacBook-Pro ~ % flutter
zsh: permission denied: flutter
yuejijia@yuejideMacBook-Pro ~ % sudo flutter
Password:
sudo: flutter: command not found
```

I find this [issue](https://github.com/flutter/flutter/issues/43082) is similar with mine, but it is not work.

I will be greatly appreciated if someone point out my mistakes! Thanks!

**Comment by yangchunboy** [comment]
@Charles1198 how did you solve it?
