### ISSUE TITLE
Multiline TextField cursor is misplaced when regain focus & textAlign is end, right, or center

### ISSUE THREAD

**Issue by alimahdiyar** [flutter/flutter#53057]
flutter cursor isn't placed correctly when tapping TextField as show in the following gif:

![flutterissue](https://user-images.githubusercontent.com/34129327/77256547-a48ac300-6c8c-11ea-8298-0f531a4a3c95.gif)

## Steps to Reproduce

create a simple app containing a Multiline TextField widget with TextAlign center or right and type several lines.
I created with a simple main.dart file as follows:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Center(child: Text('input test'))),
      body: Center(
        child: TextField(
          textAlign: TextAlign.right,
          minLines: 3,
          keyboardType: TextInputType.multiline,
          maxLines: null,
        ),
      ),
    );
  }
}
```
**flutter doctor result**
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/alideb/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/alideb/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/alideb/Android/Sdk
    • Java binary at: /home/alideb/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/alideb/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

• No issues found!

**Comment by alimahdiyar** [comment]
I figured out that the problem is related to TextAlign not Direction
![image](https://user-images.githubusercontent.com/34129327/78424453-dcc5d480-7682-11ea-9206-7ce26d905308.png)

**Comment by dvird** [comment]
Having the same issue
please guys its basic and important functionality

**Comment by alimahdiyar** [comment]
> Having the same issue
> please guys its basic and important functionality.
> Guys, it's supercritical. I'm on production.
> this kind of bugs really damages the trust of people to use flutter, let's fix it :) @digiter @jmagman

I Already have a hotfix for it. @dvird 
Goto your flutter sdk folder and change this file: packages/flutter/lib/src/painting/text_painter.dart
```
  Rect _getRectFromUpstream(int offset, Rect caretPrototype) {
...
      double dx = box.direction == TextDirection.rtl ? caretEnd - caretPrototype.width : caretEnd;
      if(
        (flattenedText.length == offset && offset > 0 && flattenedText[offset - 1] == '\n') ||
        (flattenedText.length > offset && flattenedText[offset] == '\n')
      ){
        dx = _paragraph.width - dx;
      }
...
  }
```

```
  Rect _getRectFromDownstream(int offset, Rect caretPrototype) {
...
      double dx = box.direction == TextDirection.rtl ? caretStart - caretPrototype.width : caretStart;
      if(
        (flattenedText.length == offset && offset > 0 && flattenedText[offset - 1] == '\n') ||
        (flattenedText.length > offset && flattenedText[offset] == '\n')
      ){
        dx = _paragraph.width - dx;
      }
...
  }
```

It is not a perfect solution but fixed problem for now :)

**Comment by jmagman** [comment]
@alimahdiyar We accept pull requests, if you're [interested in contributing](https://github.com/flutter/flutter/wiki/Tree-hygiene).

**Comment by alimahdiyar** [comment]
> @alimahdiyar We accept pull requests, if you're [interested in contributing](https://github.com/flutter/flutter/wiki/Tree-hygiene).

I am interested for sure. But I'm working on a more clear solution and also I'm busy now with another PR on the engine that is mentioned above my last comment

**Comment by dvird** [comment]
Hi, thanks and I already solve it. but I care from the community I also don't have to pull a clear solution right now but asking someone to do that because problems of textfield/text or other basic widgets its really critical for the trust of the people.

**Comment by alimahdiyar** [comment]
> Hi, thanks and I already solve it. but I care from the community I also don't have time to pull a clear solution right now but asking someone to do that because problems of textfield/text or other basic widgets its really critical for the trust of the people.
> 
> one question @alimhdiyar
> not getting why we "_getRectFromUpstream" i think the problems is only on down

That was for another time. now I figured out that _getRectFromDownstream is enough and edited my comment.
Can you please post your solution?

**Comment by dvird** [comment]
hi same as you have updated.. but without regarding to textalign because for me i dont need now ltr support

**Comment by alimahdiyar** [comment]
hi
I made a pull request in the engine for fixing this. @dvird @jmagman
flutter/engine#17665
