### ISSUE TITLE
Won't install package

### ISSUE THREAD

**Issue by dhust** [flutter/flutter#53062]
If I use `google_sign_in: 4.2.0` in my pubspec.yaml file and get the package, nothing happens. But if I use `google_sign_in: 4.1.0` then it imports correctly. Tried it in a blank Flutter Project.

These types of things seem to be happening with most of the recent google and firebase packages. It just happened with `google_sign_in_platform_interface` too. Unless all of these depend on the others being the most recent version.

**Comment by iapicca** [comment]
Hi @dhust 
can you please provide your `flutter doctor -v` , 
your `flutter pub get --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @dhust 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
