### ISSUE TITLE
Option to correctly clip BackgroundImage in CircleAvatar

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5306]
It would be very useful to be able to clip the _BackgroundImage_ for a _CircleAvatar_.
This could be set as a parameter so that "pre-clipped" images don't need to be processes.

**Comment by brianegan** [comment]
+1 for my side.

This is only one man's opinion, but I used the CircularAvatar with a background image, and was surprised that it wasn't clipped. Took me a bit longer to figure out the right way to do it, which actually was pretty good to know anyhow :)

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by abarth** [comment]
At the least, we should improve the documentation to suggest: 

1. Using BoxShape.circle
2. Using ClipOval

We could also add a parameter to insert a ClipOval for you, but that might lead people to use that pattern instead of the more efficient BoxShape.circle.

**Comment by brianegan** [comment]
Glad I put this in here! I was using `ClipOval`, but I'll check out `BoxShape.circle` as well. Thanks for the help.

**Comment by sethladd** [comment]
A little birdie hinted: `new ClipOval(child: new Image(...))`
