### ISSUE TITLE
Refactor transaction management to be consistent between various rendering backends.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#53069]
Currently, depending on the use of platform views and the client rendering API (OpenGL and Metal), the submission of drawable in coordination with Quartz transactions is highly confusing and has edge cases that depend on the presence of existing implicit transactions on the transaction stack. This makes the entire subsystem hard to reason about and must be refactored for consistency.

**Comment by jmagman** [comment]
When the OpenGL backend is removed can this be closed? Or is there still useful refactoring to track? https://github.com/flutter/flutter/issues/103929

**Comment by chinmaygarde** [comment]
> When the OpenGL backend is removed can this be closed?

Yes.

**Comment by jmagman** [comment]
Closing.
