### ISSUE TITLE
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by moataz-mohamed194** [flutter/flutter#53071]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @moataz-mohamed194 
can you please provide your `flutter doctor -v` and if this error happening on running the app please provide `flutter run --verbose` or if you're building apk and getting this error please provide 'flutter build apk --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by moataz-mohamed194** [comment]
No issues found! , That error see when I add "file_picker" to pubspec.yaml

**Comment by TahaTesser** [comment]
Hi @moataz-mohamed194 

For issue related to the 3rd party plugin [file_picker](https://pub.dev/packages/file_picker) you may want to open an issue in the dedicated [github](https://github.com/miguelpruivo/flutter_file_picker/issues).

if you disagree please write in the comments and I will reopen it 
Thank you
