### ISSUE TITLE
Tooltip docs are incomplete

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#53072]
The `Tooltip` docs say:

>Wrap the button in a Tooltip widget to show a label when the widget long pressed (or when the user takes some other appropriate action).

The `(or when the user takes some other appropriate action)` implies we could choose other actions to show the `Tooltip`, or that at least they are already built-in, but the docs don't mention any other ways to show the `Tooltip` neither how to reconfigure it's default behavior, like changing "long-press" to "on tap".

The only hint I could get to the explanation of this sentence is in the `waitDuration` description where it says the `Tooltip` will also be shown on a pointer hover.

So are the docs incomplete or the `Tooltip` should have additional functionality?

**Comment by Alnaggar94** [comment]
@feinstein @TahaTesser - Could anyone help me I want the tooltip to work "on tap" not by "long-press"

**Comment by feinstein** [comment]
Currently you can't.

**Comment by CubixPro** [comment]
Can we close this issue?

**Comment by feinstein** [comment]
@TahaTesser what does the "good first contribution" label means?

**Comment by TahaTesser** [comment]
@feinstein 
This label encourages first-time contributors to fix an issue, especially those who feel daunted by the idea of creating PR for  Flutter itself, I would think fixing tooltip docs would qualify

**Comment by feinstein** [comment]
Understood.

The problem here is knowing the intent of the text, is the text wrong or is the implementation wrong? And the only ones who know are the devs of the Tooltip.

Sometimes I open issues like this, where the docs and the implementation conflict. We can't know if the docs should be fixed to match the code, or the code should be fixed to match the docs. But a lot of times the beginners jump to fix the docs, and if the reviewers aren't careful, we can make a bug become the official implementation.

**Comment by TahaTesser** [comment]
@feinstein 
I agree

CC @HansMuller since he approved this https://github.com/flutter/flutter/pull/65250 and can shed some light on this issue 
Thank you

**Comment by CubixPro** [comment]
@feinstein I see your point, I thought since the documentation has been over this issue could be closed.

**Comment by HansMuller** [comment]
#66250 rewrote the bit of text in question so I'm going to close this issue. If the new text (below) is still confusing, please open a new issue.

```dart
/// Tooltips provide text labels which help explain the function of a button or
/// other user interface action. Wrap the button in a [Tooltip] widget and provide
/// a message which will be shown when the widget is long pressed.
```

**Comment by feinstein** [comment]
Not confusing at all, just making sure we have the intended behavior on the docs and not a possible deviation by a bug.
