### ISSUE TITLE
[web]: http get response null on web and working on android and iOS 

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#53075]
```dart
Future<http.Response> fetchAlbum() {
  String url = 'http://api.plos.org/search?q=title:DNA';
  return http.get(url);
}
```

Frame is not available 
it return nothing
butt when I run this on android and IOS it work fine

**Comment by iapicca** [comment]
Hi @abdulrehmananwar 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by pouledodue** [comment]
any error in Chrome console? like CORS or other

**Comment by donmani0307** [comment]
I have same issue.  When I execute below code in flutter web, it return nothing.
But in flutter iOS, works well

...
RaisedButton(
child: Text('RaisedButton', style: TextStyle(fontSize: 24)),
onPressed: () async{
http.Response response = await http.get('https://m.naver.com/include/grid/panel_DATA.shtml');
dom.Document document = parser.parse(response.body);
List<dom.Element> keywordElements = document.querySelectorAll('.cd_list .cd_item');
List<Map<String, dynamic>> keywords = [];
for (var element in keywordElements) {
dom.Element link = element.querySelector('a');
dom.Element rank = element.querySelector('.cd_num');
dom.Element title = element.querySelector('.cd_tit');
keywords.add({
'rank': rank.text,
'title': title.text,
'url': link.attributes['href']
});
}
print(keywords);
},
), 
...

**Comment by iapicca** [comment]
Hi @donmani0307 
I'm not sure if the case you are describing match the current issue,
since appears to involve dom manipulation,
I'd recommend to open a separate issue
with your `flutter doctor -v` , 
your `flutter run --verbose` 
and especially a reproducible minimal code sample.
Thank you

**Comment by abdulrehmananwar** [comment]
My issue resolved i was using asp.net rest api and it return xml formated data when i have changed rest api response from xml to json fromat its working quite fine on web

Sent from Yahoo Mail on Android 
 
  On Wed, 25 Mar 2020 at 14:40, Francecsco Iapicca<notifications@github.com> wrote:   


Hi @donmani0307
I'm not sure if the case you are describing match the current issue,
since appears to involve dom manipulation,
I'd recommend to open a separate issue
with your flutter doctor -v ,
your flutter run --verbose
and especially a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Hi @abdulrehmananwar 
I'm glad to hear that you solved the issue
Thank you for letting me know
