### ISSUE TITLE
Support for communication between native code and native web view running a flutter's web app

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#53079]
Android allows specifying a Javascript interface to act as a bridge between the webview and Android code. Similarly, iOS provides the UiWebView stringByEvaluatingJavaScriptFromString method that allows communicating with the underlying webview.

But the issue is that once we build the flutter web app and say we include it as part of a web view in android , Then whenever communication needs to take place , there is some amount of code that we should write in both android side and javascript side manually.

Since editing javascript code generated from flutter web app build is impractical , we need a way to establish a communication channel on flutter side which will talk to the native side using the same type of javascript bridge above. This will be something similar to the method channels when using the flutter app on the native side directly.

So how would we inject or add our custom javascript code from inside flutter so that it will be added during compiling the js file ?

**Comment by TahaTesser** [comment]
Hi @nateshmbhat 
Please take a look at this [solution](https://stackoverflow.com/a/13845699)  for calling js code from your dart  code.

You can also use [HtmlElementView](https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html)  to "Embeds an HTML element in the Widget hierarchy in Flutter Web."

Thank you

**Comment by nateshmbhat** [comment]
I am trying to implement it through the package:js , will update here once I test it out.

**Comment by nateshmbhat** [comment]
Here's what i'm doing :

This is my dart code :
```

@JS()
library t;

import "package:js/js.dart";

@JS("getHomeName")
external String getHostName();

```

I added this script before the main.dart.js script in the index.html : 

```

  <script>
    function getHostName(){
      return "HOST NAME from javascript" ;
    }
  </script>
```

And i access this getHostName function from some other dart file like so : 

```
import 'my_js_interface_thing' ; 
print("Got hostname : ${getHostName()}") ;
```

But I get the following error : 

`Another exception was thrown: NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.getHomeName'
`

I presume this has something to do with how I am accessing the `getHostName` function from dart ? 
Unfortunately the `package:js` docs doesn't specify or give any code example regarding using the interface methods from within dart.

**Comment by nateshmbhat** [comment]
also in release mode. i get the error mentioned in #47880

**Comment by TahaTesser** [comment]
Hi @nateshmbhat 
Please move your js in your separate file with name ` main.dart.js` 
Update your `index.html` as follows  [ref](https://stackoverflow.com/a/57244054) 

if it doesn't solve your js package issue, please raise your issue on their [github](https://github.com/dart-lang/sdk/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by nateshmbhat** [comment]
The `main.dart.js` file is the one generated from the flutter build isn't it ? It doesn't make sense to add my custom code with the file having the same `main.dart.js` name .

**Comment by nateshmbhat** [comment]
I have put an SO question here regarding this : https://stackoverflow.com/questions/60832658/flutter-web-tried-to-call-a-non-function-such-as-null-dart-global-myfunction

**Comment by TahaTesser** [comment]
Hi @nateshmbhat 
Raise your `js` package here (https://github.com/dart-lang/sdk/issues)
Thank you

**Comment by nateshmbhat** [comment]
Turned out i was using :
@JS("getHomeName")

instead of 
@JS("getHostName")

My bad :D .
