### ISSUE TITLE
Last Android 10 update, there is a problem with share image

### ISSUE THREAD

**Issue by ysnklcky** [flutter/flutter#53081]
Hello, I am testing my fluttter application with my android 10 device.  I try to share an image from network image. But in android 10 devices can not share image into instagram feed. But i can share into instagram story.. whats the difference ? 

If anyone test this case in Android 10..

I am using below code

`void onShareImage(String url) async {
  var request = await HttpClient().getUrl(Uri.parse(url));
  var response = await request.close();
  Uint8List bytes = await consolidateHttpClientResponseBytes(response);
  await Share.file('myImage', 'myImage.jpg', bytes, 'image/jpg');
}`

**Comment by ysnklcky** [comment]
This share method works with well at all social networks. But instagram feed and messenger story can not share image..

**Comment by TahaTesser** [comment]
Hi @ysnklcky 
For issue related to the 3rd party plugin [esys_flutter_share](https://pub.dev/packages/esys_flutter_share) you may want to open an issue in the dedicated [github](https://github.com/esysberlin/esys-flutter-share/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
