### ISSUE TITLE
Only 25% fetched remote repository. How to fetch 100

### ISSUE THREAD

**Issue by ShineSalt** [flutter/flutter#53089]
**flutter doctor --android-licenses --verbose**
[=========                              ] 25% Fetch remote repository...
All SDK package licenses accepted.======] 100% Computing updates...
![image](https://user-images.githubusercontent.com/45146002/77312605-693ed180-6d2a-11ea-936f-bf7ef28974c1.png)

**Comment by iapicca** [comment]
Hi @ShineSalt 
could you please provide your `flutter doctor -v` 
thank you

**Comment by ShineSalt** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at D:\2019\Flutter\flutter
    • Framework revision 9f5ff2306b (8 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\sunuw\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\sunuw\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by ShineSalt** [comment]
> Hi @ShineSalt
> could you please provide your `flutter doctor -v`
> 
> Please refrain from posting pictures if not necessary.
> thank you

Sure I will not post pictures.

**Comment by iapicca** [comment]
Hi again @ShineSalt 
your doctor looks fine, 
just run `flutter upgrade` to be sure
(if you don't get exceptions no need for the output)
let me know how it goes
Thank you

**Comment by ShineSalt** [comment]
Upgrading Flutter from D:\2019\Flutter\flutter...
From https://github.com/flutter/flutter
   9f5ff2306..0b8abb472  stable                  -> origin/stable
 * [new branch]          annotator-tree          -> origin/annotator-tree
   659dc8129..2294d75bf  beta                    -> origin/beta
   5e1000cd8..e6b0f5f23  dev                     -> origin/dev
 * [new branch]          ds84182-patch-1         -> origin/ds84182-patch-1
 * [new branch]          flutter-0.0-candidate.1 -> origin/flutter-0.0-candidate.1
   477686ae1..8c0b43bda  master                  -> origin/master
 * [new branch]          pub-version-mismatch    -> origin/pub-version-mismatch
 * [new branch]          remove-implements-function -> origin/remove-implements-function
 * [new branch]          revert-49760-editable   -> origin/revert-49760-editable
 * [new branch]          revert-49815-luciAuth   -> origin/revert-49815-luciAuth
 * [new branch]          revert-49848-alert-dialog-scrollable -> origin/revert-49848-alert-dialog-scrollable
 * [new branch]          revert-50775-dialog_padding -> origin/revert-50775-dialog_padding
 * [new branch]          revert-51418-perf1      -> origin/revert-51418-perf1
 * [new branch]          revert-51517-thbfix     -> origin/revert-51517-thbfix
 * [new branch]          revert-51886-revert-49848-alert-dialog-scrollable -> origin/revert-51886-revert-49848-alert-dialog-scrollable
 * [new branch]          revert-52055-formatter  -> origin/revert-52055-formatter
 * [new branch]          revert-52505-android_device_cleanup -> origin/revert-52505-android_device_cleanup
 * [new branch]          revert-52542-android_device_cleanup -> origin/revert-52542-android_device_cleanup
 * [new branch]          sjindel.type            -> origin/sjindel.type
 * [new branch]          v0.0.1                  -> origin/v0.0.1
   9f5ff2306..0b8abb472  v1.12.13-hotfixes       -> origin/v1.12.13-hotfixes
 * [new tag]             v1.12.13+hotfix.8       -> v1.12.13+hotfix.8
 * [new tag]             v1.14.5                 -> v1.14.5
 * [new tag]             v1.15.17                -> v1.15.17
 * [new tag]             v1.16.1                 -> v1.16.1
 * [new tag]             flutter-0.0-candidate.1 -> flutter-0.0-candidate.1
 * [new tag]             v1.14.6                 -> v1.14.6
 * [new tag]             v1.15.0                 -> v1.15.0                                                              * [new tag]             v1.15.1                 -> v1.15.1                                                              * [new tag]             v1.15.10                -> v1.15.10                                                             * [new tag]             v1.15.11                -> v1.15.11                                                             * [new tag]             v1.15.12                -> v1.15.12                                                             * [new tag]             v1.15.13                -> v1.15.13                                                             * [new tag]             v1.15.14                -> v1.15.14                                                             * [new tag]             v1.15.15                -> v1.15.15
 * [new tag]             v1.15.16                -> v1.15.16
 * [new tag]             v1.15.18                -> v1.15.18
 * [new tag]             v1.15.19                -> v1.15.19
 * [new tag]             v1.15.2                 -> v1.15.2
 * [new tag]             v1.15.20                -> v1.15.20
 * [new tag]             v1.15.21                -> v1.15.21
 * [new tag]             v1.15.22                -> v1.15.22
 * [new tag]             v1.15.3                 -> v1.15.3
 * [new tag]             v1.15.4                 -> v1.15.4
 * [new tag]             v1.15.5                 -> v1.15.5
 * [new tag]             v1.15.6                 -> v1.15.6
 * [new tag]             v1.15.7                 -> v1.15.7
 * [new tag]             v1.15.8                 -> v1.15.8
 * [new tag]             v1.15.9                 -> v1.15.9
 * [new tag]             v1.16.0                 -> v1.16.0
Updating cf37c2cd0..0b8abb472
 46 files changed, 940 insertions(+), 434 deletions(-)
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e1e6ced81d029258d449bdec2ba3cddca9c2ca0c...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...

Upgrading engine...
Downloading Android Maven dependencies...                         111.7s
Downloading android-arm-profile/windows-x64 tools...                0.9s
Downloading android-arm-release/windows-x64 tools...                0.8s
Downloading android-arm64-profile/windows-x64 tools...              0.9s
Downloading android-arm64-release/windows-x64 tools...              0.8s
Downloading android-x64-profile/windows-x64 tools...                0.8s
Downloading android-x64-release/windows-x64 tools...                0.8s
Downloading android-x86 tools...                                    6.2s
Downloading android-x64 tools...                                    5.4s
Downloading android-arm tools...                                    2.8s
Downloading android-arm-profile tools...                            1.9s
Downloading android-arm-release tools...                            1.8s
Downloading android-arm64 tools...                                  2.9s
Downloading android-arm64-profile tools...                          1.9s
Downloading android-arm64-release tools...                          1.6s
Downloading android-x64-profile tools...                            2.1s
Downloading android-x64-release tools...                            1.7s
Downloading android-x86-jit-release tools...                        2.1s
Downloading package sky_engine...                                   0.7s
Downloading common tools...                                         2.6s
Downloading common tools...                                         2.6s
Downloading windows-x64 tools...                                    6.9s

Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (6 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ╚════════════════════════════════════════════════════════════════════════════╝


C:\Users\sunuw>
C:\Users\sunuw>flutter run
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

**Comment by iapicca** [comment]
Hi @ShineSalt 
could you use flutter run --verbose in your app folder
thank you

**Comment by TahaTesser** [comment]
Hi @ShineSalt 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
