### ISSUE TITLE
Text disappear while typing on Samsung keyboard

### ISSUE THREAD

**Issue by CasperPas** [flutter/flutter#53086]
## Steps to Reproduce
1. Create a simple project with a text input widget (TextField or TextFormField).
2. Use a Samsung device.
3. Choose Input method: Samsung Keyboard.
4. Select language: Vietnamese (I haven't test all other languages yet, but Vietnamese 100% "works").
5. Checkout Flutter repo to 1 of these commits:
```
* 6ecb05213 ======> BAD
* c268b6c3d ======> GOOD
* 18984101d ======> GOOD
* d1185337c ======> GOOD
```

First, I figured out it works with v1.15.3 and the bug shows on v1.15.4, then I tried to check the commits between those versions ("binary check") and found out that the bug started to show on commit **6ecb05213**
There might something changed in Flutter's engine that caused the problem.

**Actual results:** 
![ezgif com-optimize](https://user-images.githubusercontent.com/330295/77310124-5cbd7780-6d30-11ea-9a16-e264404ce769.gif)

**Comment by goderbauer** [comment]
/cc @GaryQian Another Samsung keyboard bug :) 

In the engine roll referenced as the culprit this commit looks suspiciously related: https://github.com/flutter/engine/pull/16547.

**Comment by tvolkert** [comment]
@CasperPas thanks for the bisect!  That would mean this  bug first appears in `v1.15.4`.  I'll mark the affected range as [bad](https://github.com/flutter/flutter/wiki/Bad-Builds).

**Comment by GaryQian** [comment]
flutter/engine#17391 is the revert for this.

**Comment by Hixie** [comment]
Does that fix https://github.com/flutter/flutter/issues/53052 too?

**Comment by tvolkert** [comment]
Closing since the revert has landed.
