### ISSUE TITLE
Several platform_views_scroll_perf__timeline_summary need baselines

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53099]
![Screen Shot 2020-03-23 at 8 28 13 AM](https://user-images.githubusercontent.com/1435716/77333163-438cda80-6ce0-11ea-8882-adbfde459046.png)

cc @liyuqian

**Comment by liyuqian** [comment]
@blasten : it seems that you're the author of those benchmarks. Can you please baseline them if they look good? Please let me know if you have some troubles baselining them. I'm aware that the baseline UI isn't very user-friendly.

**Comment by blasten** [comment]
@liyuqian sounds good. I rebased a few ones, but I wanted to get enough data first to rebase the remaining ones.

**Comment by blasten** [comment]
This is fixed now
