### ISSUE TITLE
Change usages of fromEnvironment to handle breaking change SDK #40678

### ISSUE THREAD

**Issue by eernstg** [flutter/flutter#53092]
A breaking change in the semantics of Dart and its core libraries is described in SDK issue [40678](https://github.com/dart-lang/sdk/issues/40678): The default values of the named parameter `defaultValue` of the constant constructors `int.fromEnvironment` and `String.fromEnvironment` are changed from null to `0` and `""`, respectively.

The Flutter framework should be updated such that it will continue to work when that breaking change is landed.

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/pull/53093 has ben submitted. Can this be closed or is there more work to do?

**Comment by eernstg** [comment]
Can be closed!
