### ISSUE TITLE
Building Flutter assets on virtual system takes a long time

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53098]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=48828.

cc @liamappelbe @iskakaushik

**Comment by liamappelbe** [comment]
Seems like some sort of issue to do with sockets on Cloudtop. @ZichangG, can you take a look?

**Comment by kf6gpe** [comment]
@zanderso, @ZichangG noted on the linked Dart bug that he couildn't repro this with just a standard Dart socket. Would you mind asking one of the Flutter tools folks to have a look, please, and see if it's Flutter-specific?

**Comment by zanderso** [comment]
Ideally, the tool would be able to block `fuchsia_asset_builder.dart` from trying to touch the network at all.

The `BotDetector` at the top of `runInContext` can hit the network:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_asset_builder.dart#L33

although it should be timing out very quickly. One quick thing to try for @pylaligand would be to run with the environment variable BOT set to 'true'.

If that's not it, I will have to punt to @jonahwilliams and @christopherfujino to investigate whether the `buildAssets` call here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_asset_builder.dart#L60

could be hitting the network.

**Comment by zanderso** [comment]
If the network access is coming from `Cache`, some options are dropping a no-op `Cache` into the context, or (possibly easier) giving `Cache` a no-op `Net` that fails right away if touched.

**Comment by jonahwilliams** [comment]
From the bug, its stuck on `[pid 74484] connect(11, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("169.254.169.254")}, 16) = -1 EINPROGRESS (Operation now in progress)` which is the address for the Azure metadata service.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/bot_detector.dart#L99 sets a timeout on that for 250ms.  It seems like it's either not a connection timeout, or that there's some bug in Dart's connection timeout logic for this case.

**Comment by zanderso** [comment]
I asked @pylaligand for the full tail of the strace on the bug to help narrow down the possibilities.

**Comment by zanderso** [comment]
This is mitigated downstream, so I'm removing the customer critical label.

**Comment by jonahwilliams** [comment]
If we're taking more than time than the connection timeout, we should consider wrapping the entire procedure in a .timeout block

**Comment by zanderso** [comment]
The additional logs indicate that a connection is established. In particular, the `HttpClient` sets `TCP_NODELAY` when it gets a socket:
```
[pid 74484] setsockopt(11, SOL_TCP, TCP_NODELAY, [1], 4) = 0
```
There's no other way (in the HttpClient API) to set a timeout, so I think @jonahwilliams is correct that we should wrap the whole thing in a `.timeout()`.
