### ISSUE TITLE
Cannot create module with swift and kotlin

### ISSUE THREAD

**Issue by WingCH** [flutter/flutter#53091]
According to [Integrate a Flutter module into your iOS project - Create a Flutter module](https://flutter.dev/docs/development/add-to-app/ios/project-setup#create-a-flutter-module)

Create a Flutter module, this will create flutter module project with **Objective-C** and **Java**
```
flutter create --template module my_flutter1
```
<img width="1711" alt="Xnip2020-03-23_21-15-42" src="https://user-images.githubusercontent.com/19588517/77320522-b4b5a780-6d4b-11ea-8469-8617122d32a4.png">

But i want to have a  flutter module project with **swift** and **kotlin**, so i write this
```
flutter create --template module -i swift -a kotlin my_flutter2
```
there no any error message, but the project still use **Objective-C** and **Java**

<img width="1740" alt="Xnip2020-03-23_21-20-41" src="https://user-images.githubusercontent.com/19588517/77320793-28f04b00-6d4c-11ea-9e5f-3a5991415428.png">

Is it not supported swift and kotlin? But I found the official website: [Adding a Flutter screen to an iOS app](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#start-a-flutterengine-and-flutterviewcontroller), there tech how to setup in **Objective-C** and  **Swift**.

**Comment by WingCH** [comment]
```
flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale zh-Hant-HK)
    • Flutter version 1.12.13+hotfix.8 at /usr/local/bin/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wingch/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/wingch/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
Swift isn't supported for modules, see https://github.com/flutter/flutter/issues/23955.  I don't see one tracking kotlin?  @xster 

The tool should fail validating `-t module -i swift -a kotlin` instead of just silently creating an Objective-C app.

**Comment by xster** [comment]
This is a documentation bug from our side. You can't choose the language of your module because it's just gradle/xcode bootstrapping. There's no platform code in your module. It sounds rather like you have feedback on https://github.com/flutter/flutter/issues/32989 right @WingCH. Please give us some more details.

**Comment by jmagman** [comment]
In the meantime, the tool should probably fail with those language flags in conjunction with the module template.

**Comment by jmagman** [comment]
I'll do this once https://github.com/flutter/flutter/pull/53118/files#diff-8a8a53d543b7ff5f5272529314aa7156L30 is merged to avoid conflicting with that PR.

**Comment by xster** [comment]
Thanks @jmagman. @WingCH let us know if that's right or if there are genuine needs to add code in the module (generally if you're trying to ship a Flutter-using platform module rather than a Flutter module, wrap the Flutter module with another platform module where you add platform code for modularity).

**Comment by darshankawar** [comment]
@WingCH 
Can you provide your feedback per https://github.com/flutter/flutter/issues/53091#issuecomment-603448121 and https://github.com/flutter/flutter/issues/53091#issuecomment-603455019 ?
