### ISSUE TITLE
ShoppingList example in tutorial doesn't compile

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#531]
In the Flutter tutorial at http://flutter.io/tutorial/, this line:
```
    itemBuilder: (BuildContext context, Product product) {
```
needs to say this:
```
    itemBuilder: (BuildContext context, Product product, int index) {
```

**Comment by abarth** [comment]
I believe this is fixed.  Can you refresh the page?

**Comment by abarth** [comment]
Please re-open if you still think this is an issue.
