### ISSUE TITLE
platform_views_scroll_perf__timeline_summary 90th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53102]
Lost history means we can't see when it was green.

![Screen Shot 2020-03-23 at 8 28 13 AM](https://user-images.githubusercontent.com/1435716/77333330-7fc03b00-6ce0-11ea-8ebd-9946858f05da.png)

Might just need a proper baseline.

**Comment by jason-simmons** [comment]
This benchmark was introduced 5 days ago.  I don't think a baseline was ever established.

@blasten

**Comment by kf6gpe** [comment]
Dropping `TODAY` until we assign a baseline, then.

**Comment by blasten** [comment]
This is fixed now
