### ISSUE TITLE
flutter create uses directory name rather than package name to check name validity

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#53106]
I tried to add web support to an existing mobile app. The name of the app in the `pubspec.yaml` is a valid package name. However, the _directory_ that contains the package (which is derived from a git repository name) contains a dash "-" in the name. Running `flutter create .` in the package results in:

```
"xxxxx-xxxxxx" is not a valid Dart package name.

See https://dart.dev/tools/pub/pubspec#name for more information.
```

/cc @jonahwilliams

**Comment by Zazo032** [comment]
This same issue happened to us with a directory like com.xxxxxxxxxx.app, the workaround I did was to rename the folder and delete the wrongly generated files in android/ and ios/.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/blob/685e9d1e47d80bd3bd22d97e1774fa264930434c/packages/flutter_tools/lib/src/commands/create.dart#L392

**Comment by jonahwilliams** [comment]
You need to pass `--project-name` like @jmagman says above. Is this not working?

**Comment by yjbanov** [comment]
It probably does, but it doesn't make sense to have to pass this option when adding web support to an existing project. The project name is right there in the `pubspec.yaml` file.

**Comment by yjbanov** [comment]
The other issue is that the error message is misleading. While it technically correctly states that `"xxxxx-xxxxxx" is not a valid Dart package name.`, it implies that "xxxxx-xxxxxx" is being used as a package name, which is wrong.

**Comment by AseemWangoo** [comment]
Can you try this

flutter create --project-name=xyz .

**Comment by esDotDev** [comment]
Can we just have the run command just use the name as defined in .yaml or the module name?

I'm guessing a grand total of 0 people want to use the folder name as the name for their actual project. Especially as names change, and folders tend not to.

**Comment by vineetjk** [comment]
just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

**Comment by sai-kiran-the-programmer** [comment]
I have faced the same issue and when I removed capitals from the name it worked for me as @vineetjk  said

**Comment by damafeez** [comment]
Just had the same issue, mine was with hyphens.

**Comment by mirxtrem-apps** [comment]
first check your package name in android y app bundle id in iOS and should be similar, then go to pubspec.yaml and check the name of app and compare with name of main folder. if your folder has name MY-AWESOME-APP but the name in pubspec.yaml is my-app will not work flutter create . that works for me.

**Comment by mrhmamun** [comment]
> just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

same i clone a project from github, project name was package name something abc.bcdef.abc-cde I just changed the project name to abc and run flutter create . and it works!

**Comment by Marflage** [comment]
> 
> 
> Can you try this
> 
> flutter create --project-name=xyz .

Thank you so much. This worked!

**Comment by samflab** [comment]
Following all the above steps did not work. My directory was of the form "Abcc" I ran this command on terminal, it worked:
`flutter create abc`
We all faced this issue due to our naming conventions.

**Comment by hiashutoshsingh** [comment]
> just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

This worked!
Just changes the name of the folder in small caps.

**Comment by jeeali** [comment]
Change the project's folder name in the small letter as @hiashutoshsingh said ✅

**Comment by LifeofDan-EL** [comment]
> just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

Had same issue, this worked for me.

**Comment by bg15407** [comment]
I had a folder name flutter-magic and when flutter create . is executed the above error is thrown. so as discussed i changed my folder to fluttermagic and run the command again and it worked.

**Comment by kedar2594** [comment]
> just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

This solution by vineetjk, solved my issue. Thanks vineetjk

**Comment by francocores** [comment]
in my case the project folder contained "example-app" and get the error "example-app" is not a valid Dart package name.", the solution for this is rename folder app for "example" and run "flutter create ."

**Comment by Hamza3620** [comment]
Got the same issue and I just changed my directory name from "My-Project-Directory" to "my-project-directory" and still didn't work. Then I replaced "-" with "_" and it worked. 

1. Rename the directory to this format: all small letters and separated by underscores.
Example: my_project_directory
2. flutter create .

and you're done!

**Comment by esDotDev** [comment]
The solution is not to rename the folder, the entire issue is about it using the folder name when it shouldn't be.

The problem here is that `--project-name` is not actually specified when you just use `create .`  It fallsback to trying to use the folder as the name, in lieu of you providing an explicit one.

Better behavior would be to use the name defined in the pub-spec, then fallback to folder name if no pub-spec exists.

**Comment by irajeshh** [comment]
Had same problem when adding `Windows` support to existing project.
Renaming the folder from `AlphaTest` to `alphatest` solved the issue.

**Comment by ninetynin** [comment]
> Can you try this
> 
> flutter create --project-name=xyz .

This worked for me

**Comment by jmagman** [comment]
It is indeed bug, which is why this issue is open.

**Comment by sayhicoelho** [comment]
Why can't I use hyphens in the project name?

**Comment by thealidev** [comment]
Easyest Way  
`Simply Create New Blank Project And Move "web" Folder To Your Project`

**Comment by martinezinsua** [comment]
> just now i faced the same issue after cloning a repository from github and i found out that after cloning the repository the file name was having capital letters that is not supported by dart, so i just renamed the folder and tried the command `flutter create .` and it worked.. i hope this helps to people facing the same problem as mine.

Thank you very much!!

**Comment by YawarOsman** [comment]
IDK if you fixed it or not, but i had the exact the issue so i just rename my project name from "admin-panel" to "adminpanel" without any space and then the `flutter create .` worked perfectly

**Comment by sagarshende23** [comment]
> IDK if you fixed it or not, but i had the exact the issue so i just rename my project name from "admin-panel" to "adminpanel" without any space and then the `flutter create .` worked perfectly

Thank you So Much Bro... Working :-)

**Comment by navaronbracke** [comment]
I just ran into this as well, seems like this bug had been in the tool for a while...

I agree with the points above, we should be using the pubspec name as fallback instead.
I'll take a look at figuring out a test and fix for the underlying tool bug.
