### ISSUE TITLE
Add support for --sksl-shader-warmup to package sksl files into flutter_assets

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#53115]
These sksl files should be in a well known directory so that they can be read by the engine.

For https://github.com/flutter/flutter/issues/32170

**Comment by liyuqian** [comment]
@jonahwilliams : https://github.com/flutter/flutter/issues/53117 has landed and the engine will read SkSLs from the `sksl` subdirectory in the root asset directory.

**Comment by jonahwilliams** [comment]
Awesome! Is there a logging level I can run with to verify that they get loaded correctly?

**Comment by liyuqian** [comment]
Yes, the `INFO` level (which is enabled by `--verbose-system-logs`) would show logs.
