### ISSUE TITLE
No Usages Found in the Project.. Migration to Android X

### ISSUE THREAD

**Issue by AdiNile** [flutter/flutter#53128]
I have Android Studio 3.6.1 and i am have issues while migrating to Android X. 
this is what is written
No Usages Found in the Project

I've also installed flutter and dart plugins

**Comment by TahaTesser** [comment]
Hi @AdiNile 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by AdiNile** [comment]
Here's my flutter doctor -v
' ' '

C:\Users\A.bhattacarya\Documents\workspace\pics>flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.15.17 at C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\A.bhattacarya\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\A.bhattacarya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found! 

' ' '


Well I do not understand as to what code sample to paste to reproduce the problem.. Its directly coming.

Thank you so much for helping me out

Here's the flutter run --verbose
 ' 

> C:\Users\A.bhattacarya\Documents\workspace\pics>flutter run --verbose
> [  +62 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [ +119 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +6 ms] 2294d75bfa8d067ba90230c0fc2268f3636d7584
> [   +3 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git fetch https://github.com/flutter/flutter.git --tags
> [+26593 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
> [   +5 ms] From https://github.com/flutter/flutter
>             * branch                  HEAD       -> FETCH_HEAD
> [   +5 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git describe --match v*.*.* --first-parent --long --tags
> [ +196 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
> [   +5 ms] v1.15.17-0-g2294d75bfa
> [  +17 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [ +109 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [   +6 ms] origin/beta
> [   +5 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git ls-remote --get-url origin
> [ +101 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +7 ms] https://github.com/flutter/flutter.git
> [ +261 ms] executing: [C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter/] git rev-parse --abbrev-ref HEAD
> [  +94 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [   +4 ms] beta
> [ +113 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [  +15 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [  +16 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +88 ms] executing: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [  +56 ms] Exit code 0 from: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [   +4 ms] List of devices attached
>            emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
> [  +29 ms] C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
> [ +149 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [  +21 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +7 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +551 ms] Generating C:\Users\A.bhattacarya\Documents\workspace\pics\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
> [  +69 ms] ro.hardware = ranchu
> [  +50 ms] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
> [  +69 ms] Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> [  +28 ms] C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter\bin\cache\dart-sdk\bin\dart.exe
> C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
> C:\Users\A.bhattacarya\Documents\flutter_windows_v0.5.1-beta\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
> -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\A56AC~1.BHA\AppData\Local\Temp\flutter_tool.b444727e-6dc5-11ea-90bd-e4aaeaa04222\app.dill --packages
> C:\Users\A.bhattacarya\Documents\workspace\pics\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
> --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
> --track-widget-creation --filesystem-scheme org-dartlang-root
> [  +63 ms] executing: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
> [ +134 ms] Exit code 0 from: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
> [   +5 ms] --------- beginning of main
>            03-24 17:20:50.392 I/GnssLocationProvider( 1935): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
>            com.android.server.location.GnssLocationProvider$SvStatusInfo@e4d867e)
> [  +26 ms] executing: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe version
> [   +9 ms] executing: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 logcat -v time -T 03-24 17:20:50.392
> [  +25 ms] <- compile package:pics/main.dart
> [  +83 ms] Android Debug Bridge version 1.0.41
>            Version 29.0.6-6198805
>            Installed as C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe
> [  +18 ms] executing: C:\Users\A.bhattacarya\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
> [ +103 ms] Building APK
> [  +49 ms] Running Gradle task 'assembleDebug'...
> [  +10 ms] gradle.properties already sets `android.enableR8`
> [  +76 ms] Using gradle from C:\Users\A.bhattacarya\Documents\workspace\pics\android\gradlew.bat.
> [   +4 ms] C:\Users\A.bhattacarya\Documents\workspace\pics\android\gradlew.bat mode: 33279 rwxrwxrwx.
> [  +29 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [ +229 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [   +6 ms] openjdk version "1.8.0_212-release"
>            OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>            OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
> [  +12 ms] executing: [C:\Users\A.bhattacarya\Documents\workspace\pics\android/] C:\Users\A.bhattacarya\Documents\workspace\pics\android\gradlew.bat -Pverbose=true
> -Ptarget-platform=android-x86 -Ptarget=C:\Users\A.bhattacarya\Documents\workspace\pics\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
> assembleDebug
> [+6799 ms] Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> [+18175 ms] FAILURE: Build failed with an exception.
> [  +17 ms] * What went wrong:
> [   +9 ms] A problem occurred configuring root project 'android'.
> [   +6 ms] > Could not resolve all files for configuration ':classpath'.
> [   +6 ms]    > Could not find com.android.tools.build:gradle:3..
> [   +6 ms]      Searched in the following locations:
> [   +7 ms]          https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3./gradle-3..pom
> [   +2 ms]          https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3./gradle-3..jar
> [   +9 ms]          https://jcenter.bintray.com/com/android/tools/build/gradle/3./gradle-3..pom
> [   +2 ms]          https://jcenter.bintray.com/com/android/tools/build/gradle/3./gradle-3..jar
> [   +3 ms]      Required by:
> [   +2 ms]          project :
> [   +7 ms] * Try:
> [   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> [   +2 ms] * Get more help at https://help.gradle.org
> [   +5 ms] BUILD FAILED in 24s
> [ +573 ms] Running Gradle task 'assembleDebug'... (completed in 26.0s)
> [  +17 ms] Exception: Gradle task assembleDebug failed with exit code 1
> [   +5 ms] "flutter run" took 28,017ms.
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
> #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)
> <asynchronous suspension>
> #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
> #3      _rootRunUnary (dart:async/zone.dart:1134:38)
> #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> #5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
> #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> #7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> #8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
> #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
> #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
> #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
> #12     _rootRunUnary (dart:async/zone.dart:1134:38)
> #13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> #14     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
> #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> #16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> #17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
> #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
> #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
> #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
> #21     _rootRunUnary (dart:async/zone.dart:1134:38)
> #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> #23     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
> #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
> #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
> #28     _rootRun (dart:async/zone.dart:1126:13)
> #29     _CustomZone.run (dart:async/zone.dart:1023:19)
> #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
> #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
> #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
> #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
> #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
> #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

' 
 I dont know what code sample to post as I'm directly getting the problem


thank you so much for helping me out

**Comment by TahaTesser** [comment]
Hi @AdiNile 

Did you try `flutter clean`?
Is this a new project os existing project?
Could you please share `build.gradle` from Android folder

Thank you

**Comment by AdiNile** [comment]
Hey 
As you told I tried flutter clean, right now. What should I  do now?...


This pics is a new project, I didnot work on it yet.


Here is my build.gradle -

` 
 
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`

**Comment by TahaTesser** [comment]
Hi @AdiNile 
if it's a new project, why do you have modified `build.gradle`?


i just created new project with support java in beta as just as yours
Here is my `build.gradle`
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

flutter doctor -v
```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.15.17 at /Users/tahatesser/Code/flutter_beta
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

Please update your `build.gradle`
```
        classpath 'com.android.tools.build:gradle:3.5.0'

```

and `flutter clean then pleas provide your `flutter run --verbose`
Thank you

**Comment by TahaTesser** [comment]
Hi @AdiNile 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
