### ISSUE TITLE
Convert blob objects 

### ISSUE THREAD

**Issue by AmrGharieb** [flutter/flutter#53127]
hi guys i develop a new article app and use C# with firebase as a backend for database

i user th following code to convert the rtichtext.text to byte array 

     byte[] result;
            using (MemoryStream ms = new MemoryStream())
            {
                txt_article.SaveDocument(ms, DevExpress.XtraRichEdit.DocumentFormat.Rtf);
                result = ms.ToArray();
            }

and saved successfully to fire base as blob now in flutter i want to retrieve the blob convert it to formatted text and then assign to any widget to show the text

note:- the text contain pictures , formatted texts like any news app

thanks

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
