### ISSUE TITLE
Dart and Engine rolls ignore web test failures

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#53124]
Dart roll merges even in the presence of web test failures.

This happens both in flutter/engine and flutter/flutter.

Here's an example of flutter/flutter roll that went in but shouldn't have: https://github.com/flutter/flutter/pull/52974 (rolled back in https://github.com/flutter/flutter/pull/53100).

Here's an example of flutter/engine roll that went in but shouldn't have: https://github.com/flutter/engine/pull/17241 (rolled back in https://github.com/flutter/engine/pull/17243, but then rolled in anyway later in https://github.com/flutter/engine/pull/17244)

/cc @godofredoc @bkonyi

**Comment by aam** [comment]
cc @rmistry

**Comment by rmistry** [comment]
The github rollers do not merge anymore, they rely on the mergebot "fluttergithubbot" to determine when tests pass and to do the merging.
@dnfield

**Comment by dnfield** [comment]
@keyonghan changed these so they should have been looking directly at the Cirrus API.  He has the most context at this point.

**Comment by keyonghan** [comment]
Looking.

**Comment by keyonghan** [comment]
The culprit is https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart#L272

It uses default branch `master`, whereas the branch name for a PR before it merges is following `pull/number`.

Working on a fix.

**Comment by keyonghan** [comment]
Submitted and merged the changes. The new deployment seems to be loading the build dashboard for a super long time. Waiting for @CaseyHillers to see if any rollback/change needed before I switched the traffic to the latest version.

So reopen the issue since the change is not in production yet.

**Comment by keyonghan** [comment]
@Hixie has been working hard to fix the dashboard regression: https://github.com/flutter/cocoon/pull/716

Will update once available.

**Comment by keyonghan** [comment]
Reverted PR 707: https://github.com/flutter/cocoon/pull/718, and redeployed app engine. It should pick latest fixt. Marking as closed. Please reopen if any issue.
