### ISSUE TITLE
Running pub upgrade... The system cannot find the path specified.

### ISSUE THREAD

**Issue by magalhaesulisses** [flutter/flutter#53135]
## Steps to Reproduce

1. Installed the lastest version of Flutter SDK (by GIT)
2. Changed the PATH for Flutter 
3. Git version comes with the bin/cache folder empty
4. So i tried **flutter doctor**
5. If I manually download a Dart-sdk and place into flutter/bin/cache it will pass, but, when i'll try to run the project by: **flutter run -d chrome** it will says that there are different snapshots.
5. Also, already try to change channels to run my application it eventually will say that the snapchats are different;
6. Even if i download the lastest dart-sdk version from choco. and upgrade it afterwards, (and include the PATH) will say that the snapshots are different.

## Logs

Tried using PowerShell, and vsCode terminal.
Using Win 8.1
![image](https://user-images.githubusercontent.com/45711014/77372190-e3c81b00-6d43-11ea-876d-8a4a8716e238.png)

```
## Flutter Doctor
 PS C:\Users\Ulisses> flutter doctor
Checking Dart SDK version...
Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? 

```

**Comment by VladyslavBondarenko** [comment]
Hi @magalhaesulisses 
why do you need manually download Dart-sdk?
doesn't it start download when running `flutter doctor` for the first time?

**Comment by magalhaesulisses** [comment]
@VladyslavBondarenko, when i clone from git, the bin/cache folder comes empty

**Comment by VladyslavBondarenko** [comment]
@magalhaesulisses 
it should be so, once you run `flutter doctor` or `flutter upgrade` everything needed will be downloaded into cache

**Comment by magalhaesulisses** [comment]
Then i got this message:
## Flutter Doctor
 PS C:\Users\Ulisses> flutter doctor
Checking Dart SDK version...
Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)?

**Comment by VladyslavBondarenko** [comment]
Related issue https://github.com/flutter/flutter/issues/15101

**Comment by magalhaesulisses** [comment]
Read issue #15101, there is no solution there :T

**Comment by jmagman** [comment]
That error is coming from `pub` not Flutter.

Can we get the output of `flutter doctor -vv` (note the extra v)?

**Comment by magalhaesulisses** [comment]
Sure:
PowerShell 7.0.0
PS C:\src\flutter> flutter doctor -vv
Checking Dart SDK version...
Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
[  +75 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1082 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +249 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +48 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +220 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +124 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +365 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +157 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +274 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +45 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +149 ms] Doctor summary (to see all details, run flutter doctor -v):
[  +46 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1998 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +98 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[ +130 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 6 weeks ago
[ +139 ms] executing: C:\src\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot
[ +304 ms] Exit code 255 from: C:\src\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot
[   +1 ms] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>

           Common options:
           --help
             Display this message (add --verbose for information about all VM options).
           --version
             Print the VM version.

           To create a core snapshot:
           --snapshot_kind=core
           --vm_snapshot_data=<output-file>
           --isolate_snapshot_data=<output-file>
           <dart-kernel-file>

           To create an AOT application snapshot as assembly suitable for compilation
           as a static or dynamic library:
           --snapshot_kind=app-aot-assembly
           --assembly=<output-file>
           [--obfuscate]
           [--save-obfuscation-map=<map-filename>]
           <dart-kernel-file>

           To create an AOT application snapshot as an ELF shared library:
           --snapshot_kind=app-aot-elf
           --elf=<output-file>
           [--strip]
           [--obfuscate]
           [--save-obfuscation-map=<map-filename>]
           <dart-kernel-file>

           AOT snapshots can be obfuscated: that is all identifiers will be renamed
           during compilation. This mode is enabled with --obfuscate flag. Mapping
           between original and obfuscated names can be serialized as a JSON array
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524
           for implementation details and limitations of the obfuscation pass.
[  +24 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +211 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +7 ms] java -version
[ +595 ms] executing: C:\Users\Ulisses\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +376 ms] Exit code 0 from: C:\Users\Ulisses\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
[   +8 ms] [âˆš] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.3.9600], locale pt-BR)
[  +20 ms] executing: C:\Users\Ulisses\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +543 ms] List of devices attached
[  +52 ms] executing: C:\Users\Ulisses\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
[+18120 ms] [ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[   +2 ms] [ÔêÜ] Android Studio (version 3.6)
[   +1 ms] [ÔêÜ] VS Code (version 1.43.1)
[   +1 ms] [!] Connected device
[   +1 ms]     ! No devices available
[        ] ! Doctor found issues in 1 category.
[  +32 ms] "flutter doctor" took 23.360ms.
PS C:\src\flutter>

**Comment by jmagman** [comment]
Hm that output didn't include "The system cannot find the path specified."

**Comment by magalhaesulisses** [comment]
Ran flutter doctor, now the sdk files are in the bin/cache. 
But, when i tried to create a net flutter wep app got this:
![image](https://user-images.githubusercontent.com/45711014/77582058-87890680-6ebd-11ea-9ef5-4e7a22ee56c5.png)

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/53135

**Comment by ChildishGiant** [comment]
I ran out of space while performing a `flutter upgrade` and now keep getting this. I've checked and re-entered my path variable and keep getting it.

```
PS C:\Users\allie> flutter
Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 5 seconds, press CTRL+C to quit ...
```

**Comment by VladyslavBondarenko** [comment]
@ChildishGiant what PowerShell version do you have? what flutter version?

**Comment by ChildishGiant** [comment]
Just cloned the stable branch so by the looks of things 1.17.5. PowerShell 5.1.18362.752

**Comment by VladyslavBondarenko** [comment]
@ChildishGiant could you provide your `flutter doctor -vv`?

**Comment by ChildishGiant** [comment]
Sorry, I've since reinstalled and made sure to have enough room on my drive when upgrading.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/1021a52f138b3de0a1bca86323a195ea643f3d2f
