### ISSUE TITLE
[Desktop][Windows] When editing a TextField, Ctrl+a or Cmd+a should select all text.

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#53133]
On Windows, when within a text field, ctrl+a or cmd+a should select all text. Currently it displays a box character.

**Comment by TahaTesser** [comment]
Hi @esDotDev 
It's already possible to select all text in a TextField using Ctrl+a or Cmd+a
Please checkout this [dartpad](https://dartpad.dev/d06a29fda16031c216f30e45f0cd6c86)

if you're still experiencing this issue 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by esDotDev** [comment]
Thanks for testing, I'm on the latest master and just confirmed that it is happening with Windows only, my Web builds do not show this behavior.

I can also not tab-out of the field on Windows, but I can on Web.

**Comment by TahaTesser** [comment]
Hi @esDotDev 
Just the sample code above on MaOS desktop app and it does work fine 
Thank you for your contribution

**Comment by stuartmorgan** [comment]
This is fixed; likely the same issue as https://github.com/flutter/flutter/issues/54879.
