### ISSUE TITLE
Update semantics of the "waiting for tree to go green" tag to be similar to auto-submit.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#53138]
Most uses of the ["waiting for tree to go green"](https://github.com/flutter/engine/labels/waiting%20for%20tree%20to%20go%20green) tag in the engine repository recently have been for pull-requests where the author intends for the patch to land when the presubmit passes, and a review is successful. In a majority of the cases, the tree is already green. This works out well if a review is left before the presubmits finish. In that case, the patch lands and there is nothing more to do for the author (except maybe to cleanup their branch). However, if the presubmit finishes before a review is left, the tag is removed automatically and the author has to manually land the patch (the ignominy I know).

The suggestion is to change the semantics of the tag to be that of an auto-submit on passing all prerequisites. This should automate more cases of the patch submission and lessen the number of viable patches in the pull request queue.

On a related note, I feel a bit bad that the tag is called what it is. Granted, we have done a rubbish job of keeping the tree green. But, it's infinitely better now.  Lets call it "Auto-Submit" or something when the semantics are updated.

**Comment by chinmaygarde** [comment]
cc @dnfield

**Comment by godofredoc** [comment]
Done!
