### ISSUE TITLE
Container BoxDecoration Shape does not clip BackgroundImage

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5313]
If you set a shape to a Container's BoxDecoration, that shape will not clip the BackgroundImage (if set).

It does, however, clip the BackgroundColor for the BoxDecoration.

It probably makes the most sense for the BoxDecoration shape to clip the BackgroundImage if it clips the BackgroundColor already.

**Comment by eseidelGoogle** [comment]
I feel like @HansMuller looked at this at one point?

Would be nice if we had some simple sample code/repro here.

**Comment by Hixie** [comment]
Is this still broken? It should work fine...

I'll take a look at whether this still happens.

**Comment by Hixie** [comment]
If this is not fixed, it's not a current milestone priority. But I'll verify if it's fixed.

**Comment by Hixie** [comment]
seems to work fine to me.
