### ISSUE TITLE
Share plugin causes the ios build to fail.

### ISSUE THREAD

**Issue by spiderion** [flutter/flutter#53131]
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           21.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/ionolaru/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+6/ios/Classes/FLTSharePlugin.m:54:8: error: use of undeclared identifier 'FlutterMethodChannel'
          [FlutterMethodChannel methodChannelWithName:PLATFORM_CHANNEL
           ^
    /Users/ionolaru/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+6/ios/Classes/FLTSharePlugin.m:57:4: error: use of undeclared identifier 'shareChannel'
      [shareChannel setMethodCallHandler:^(FlutterMethodCall *call, FlutterResult result) {
       ^
    /Users/ionolaru/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+6/ios/Classes/FLTSharePlugin.m:50:17: error: class 'FLTSharePlugin' defined without specifying a base class [-Werror,-Wobjc-root-class]
    @implementation FLTSharePlugin
                    ^
    /Users/ionolaru/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+6/ios/Classes/FLTSharePlugin.m:50:31: note: add a super class to fix this problem
    @implementation FLTSharePlugin
                                  ^
                                   : NSObject 
    1 warning and 6 errors generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

**Comment by spiderion** [comment]
Looks like the issue comes when the share: ^0.6.3+6 is used
Once removed the build works fine.

**Comment by VladyslavBondarenko** [comment]
Hi @spiderion 
could you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
does it happen when using this example only https://pub.dev/packages/share#-example-tab-?

**Comment by spiderion** [comment]
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
ionolarus-MBP:StudioProjects ionolaru$ flutter doctor -v
[✓] Flutter (Channel master, v1.16.3-pre.6, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.16.3-pre.6 at /Users/ionolaru/flutter
    • Framework revision 2a8e7b7bf1 (22 hours ago), 2020-03-23 13:36:01 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ionolaru/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 1E5C522E-E949-4089-ADA8-E74913F80949 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.149
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by spiderion** [comment]
it happens when using this example only https://pub.dev/packages/share#-example-tab-?
Yes,
If I remove it then it works fine.

**Comment by spiderion** [comment]
Workaround: 
Use share_extend 1.1.3 plugin

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
