### ISSUE TITLE
my device is offline

### ISSUE THREAD

**Issue by mariamalbarghouti** [flutter/flutter#53136]
my device is connect to my pc ,ican send and receive a message from and to my pc.
BUT on android studio or on visual studio code there is NO device appears .
when i type in cmd "flutter device"
the message is gonna be "the device afhe323 is offline"!
"I Make My Device Debugging Mode"
can you help me ,please?

**Comment by TahaTesser** [comment]
Hi @mariamalbarghouti 
can you please provide your `flutter doctor -v` with device connected to your PC?
Thank you

**Comment by mariamalbarghouti** [comment]
hi @TahaTesser 
i appreciate your help,the problem was "my cable when i changed it the problem solved".
after 4 days searching for a solution.
thanks

**Comment by TahaTesser** [comment]
Hi @mariamalbarghouti 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you

**Comment by mariamalbarghouti** [comment]
@TahaTesser i'm agree :)
