### ISSUE TITLE
[new_feature] Desktop date pickers for easier picking of a date with single click 

### ISSUE THREAD

**Issue by stud0r** [flutter/flutter#53132]
The usage of the current DatePicker is not very efficient regarding usability, as it requires always two clicks:
- select date
- close

It would therefore be very helpful to provide a possibility to close the showDatePicker if a day is selected. In my perspective this is also in line with the Design Guidance of Material Design for Desktop pickers:
- https://material.io/components/pickers/#desktop-pickers

**Comment by HansMuller** [comment]
We're in the midst of updating the DatePicker to match the current material spec. The first big change landed just yesterday: https://github.com/flutter/flutter/pull/50546

Supporting the desktop guidelines is part of the plan!

CC @darrenaustin

**Comment by darrenaustin** [comment]
As Hans mentioned, we are working on adding the desktop support but if you need something before then, you might want to take a look at using the `CalendarDatePicker` class that was exposed as part of the [recent update](https://github.com/flutter/flutter/pull/50546) to the date picker. It provides just the calendar grid and year selector which you could hook up to anything you like.

**Comment by gspencergoog** [comment]
Now that the date picker has been updated, this should be a lot easier.
