### ISSUE TITLE
`GitHubTemplateCreator` potentially leaks information to GitHub

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#53140]
The `flutter` tool has a `GitHubTemplateCreator` class that it uses to create a git.io shortened URL that searches GitHub for an error message.

The error message could potentially contain sensitive information (e.g. a `FileSystemException` will contain the path to the offending file).  Constructing a git.io shortened URL will save the original URL (with the embedded error message) to GitHub, and there does not seem to be any way to remove it.

**Comment by jmagman** [comment]
\cc @zanderso

**Comment by jamesderlin** [comment]
Getting rid of `GitHubTemplateCreator` would be a shame, so if we agree that this is a problem, then possible ways to address this would be:

* Use only the exception's `runtimeType` instead of its full error message.
* Interactively ask the user if they want to search for existing issues and show a preview of what information will be sent.

**Comment by jmagman** [comment]
For context, here's what it looks like without shortening.
<img width="1127" alt="69377704-af433600-0c61-11ea-8f2e-e3d7b5af9db4" src="https://user-images.githubusercontent.com/682784/77566085-6525c780-6e82-11ea-9ae2-f1c73fbe7128.png">

**Comment by jmagman** [comment]
Note to self: also look at analytics collection flag.

**Comment by jmagman** [comment]
"Similar issues" link and the error message is now sanitized.  Still need to clean up paths and device names in doctor output.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/96250 `ValidationMessage` can now include an optional `piiStrippedMessage` string which will not be used for local crash logs, but will be used for GitHub template generation. All doctor validation messages still need to be audited.
/cc @Hixie

**Comment by jmagman** [comment]
Well the GitHub link shortener has been sunset https://github.com/flutter/flutter/issues/99572.  We can either replace it with a Google-owned one (goo.gl is long-dead I don't know if there's a replacement) or live with the long URLs.
