### ISSUE TITLE
it has a error with the network method

### ISSUE THREAD

**Issue by xzqbetter** [flutter/flutter#53156]
when play with a net url, it catches the error:

Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4

**Comment by TahaTesser** [comment]
Hi @xzqbetter 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by xzqbetter** [comment]
@TahaTesser 
my code is same as the sample

> code

![20200325131229](https://user-images.githubusercontent.com/48462828/77504092-59de9600-6e9a-11ea-90d2-b4fbd20c2795.jpg)
![20200325131246](https://user-images.githubusercontent.com/48462828/77504137-809ccc80-6e9a-11ea-98c8-070befb321c5.jpg)

> flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/xzq/Develop/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xzq/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

> flutter run --verbose

the `flutter run --verbose` is so long, so I didn't copy it

**Comment by iapicca** [comment]
Hi @xzqbetter 
does this [code](https://gist.github.com/iapicca/6f04249f85038411670a8d62e3924a25) represent the issue you are describing?

Could you please attach your `flutter run --verbose` as txt file
 
Please refrain from posting pictures if not necessary.
Thank you

**Comment by xzqbetter** [comment]
@iapicca 
Thank you
I have solved the issue, it seems the VideoPlayer Plugin does not support `https`, I replace a `http` url, and it works perfectly

**Comment by TahaTesser** [comment]
Hi @xzqbetter 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
