### ISSUE TITLE
flutter web ：： How to call the flutter method through JS

### ISSUE THREAD

**Issue by lws1314** [flutter/flutter#53152]
In the development of flutter web, JS is needed to call the flutter method!
How to achieve？

**Comment by TahaTesser** [comment]
Hi @lws1314 
Please check this [answer](https://stackoverflow.com/a/13845699)
You can use [js](https://pub.dev/packages/js) package 
Please let us know if this answers your question
Thank you

**Comment by TahaTesser** [comment]
Hi @lws1314 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
