### ISSUE TITLE
Error Message when running AVD in Android Studio

### ISSUE THREAD

**Issue by pydudu** [flutter/flutter#53158]
When I run the AVD in Android Studio I get this error message:

```
13:29	Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: C:\Users\WenJ\.android\emulator-grpc.cer security will be disabled.
```

I've found many different solutions online and I've tried a few of them, but they didn't work. The Android SDK is up to date and I accepted all the licenses. When I run flutter doctor it says that there are no problems. When I run it I get this:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```

Does anybody know what the problem is and how it can be solved?

**Comment by VladyslavBondarenko** [comment]
I'm not sure that the issue with AVD is related to flutter itself.
Similar to https://github.com/flutter/flutter/issues/52057.

**Comment by pydudu** [comment]
To run the app I need to have a device connected. This means that when I run the app, I can see the warning.

**Comment by jmagman** [comment]
This is an AVD issue, not Flutter.  Please see https://developer.android.com/studio/report-bugs.
Closing.
