### ISSUE TITLE
Describe how to listen for page updates in TabBar and TabBarView when using DefaultTabController

### ISSUE THREAD

**Issue by jayvhaile** [flutter/flutter#53155]
## Use case

When trying to listen for page changes in a TabBarView, the available option is to pass a controller to it and then listen to the controller for changes. This causes two problems
1:- You cannot use DefaultTabController widget, which leads to more unnecessary code
2:- Listening for TabController for page changes does not update fast enough, it updates at least half a second after the page changes
## Proposal
The Solution is since TabBarView uses PageView, and PageView has a callback called onPageChanged, you could expose that callback on TabBarView class, which solves both problems, 
1: No need to create TabController object, one can still use DefaultTabController
2: The onPageChanged callback updates fast, as soon as the page changes

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue, we can simply add a ValueChanged callback in `TabBarView` and during `PageView.onChanged` we can access the tab number and send the callback.

**Comment by AyushBherwani1998** [comment]
@shihaohong passing `ValueChanged<int>` typedef in `onPageChanged` works as intended. But when a user uses `TabBar` to change the tabs, it's triggered multiple times, which is as intended since it uses `PageController.animateToPage` instead of `PageController.jump`. So, if the user is at the 0th Tab and clicks on the 2nd Tab, the `onPageChanged` will be triggered 2 times.

To overcome, I'm thinking to send a callback from 
https://github.com/flutter/flutter/blob/5f21edf8b66e31a39133177319414395cc5b5f48/packages/flutter/lib/src/material/tabs.dart#L1301

and from 
https://github.com/flutter/flutter/blob/5f21edf8b66e31a39133177319414395cc5b5f48/packages/flutter/lib/src/material/tabs.dart#L1261

WDYT?

**Comment by shihaohong** [comment]
@AyushBherwani1998 Does it trigger one time at index 0 and the second time at index 2? I think it might be worth considering whether we can improve the implementation, since it feels like this is something a user would not expect to happen and would lead to a subsequent issue filed. 

Maybe @jayvhaile could chime in on what they would expect and their thoughts on this callback's behavior as well, given what Ayush's findings.

**Comment by shihaohong** [comment]
Another thing to consider is whether or not it might be confusing to have both a tab bar controller, as well as an onPageChanged callback. We should try to be as explicit as possible to the user with what each should be used for.

**Comment by AyushBherwani1998** [comment]
> 
> 
> @AyushBherwani1998 Does it trigger one time at index 0 and the second time at index 2?

What I meant was, if you are 0th page, and then if you use `PageController.animateToPage` to go to the 2nd page, the `onPageChanged` will be called twice.  It will animate to 2nd Page through 1st Page. Hence the `onPageChanged` is trigger twice.

This behaviour is observed when a user uses `TabBar` to change the tab.

**Comment by shihaohong** [comment]
@AyushBherwani1998 Ahh I see, so it triggers for page 1, and then page 2? Another intricacy with the TabBarView/TabBar is that even though it triggers for the 1st page, it actually shows the 0th page, so that's something to consider as well.

**Comment by AyushBherwani1998** [comment]
Looking at the implementation, I found a way to avoid this behaviour. 
So, we can have one callback from [`_handleTabControllerAnimationTick`](https://github.com/flutter/flutter/blob/bbb95e5787db0780d5fe1abbe023fe771137d325/packages/flutter/lib/src/material/tabs.dart#L1259) where we get the latest index from `TabController` to handle the tap from `TabBar` and another callback from https://github.com/flutter/flutter/blob/bbb95e5787db0780d5fe1abbe023fe771137d325/packages/flutter/lib/src/material/tabs.dart#L1327 inside `_handleScrollNotification`.

To avoid multiple callbacks for the same page, we can have a variable like `PageView` https://github.com/flutter/flutter/blob/f4d26a3b858180148a9b392defaccffe99fd3487/packages/flutter/lib/src/widgets/page_view.dart#L812

I tried to implement this for a demo app, and it works fine. WDYT about this solution?

**Comment by shihaohong** [comment]
As long as there are tests that describe and prove that the intended behavior works, I think that sounds good. Just make sure that there is a test case for each common use case for the API that we are creating.

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR. I'm not sure which other tests I should include since not using the `onTabChanged` is already handled by the other tests. Looking forward to your reviews about the implementation and test.

**Comment by chunhtai** [comment]
I am not convinced that we should expose this callback. you can listens to the defaulttabcontroller using this way

```
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Builder(
          builder: (BuildContext context) {
            final TabController controller = DefaultTabController.of(context);
            controller.addListener(() {
              if (!controller.indexIsChanging)
                print(controller.index);
            });
            return Scaffold(
              appBar: AppBar(
                bottom: TabBar(
                  tabs: [
                    Tab(icon: Icon(Icons.directions_car)),
                    Tab(icon: Icon(Icons.directions_transit)),
                    Tab(icon: Icon(Icons.directions_bike)),
                  ],
                ),
                title: Text('Tabs Demo'),
              ),
              body: TabBarView(
                children: [
                  Icon(Icons.directions_car),
                  Icon(Icons.directions_transit),
                  Icon(Icons.directions_bike),
                ],
              ),
            );
          }
        )
      ),
    );
  }
}
```

I didn't see a second delay that you mention. We do have inconsistency of the animations between tab bar and page view (basically tab bar move faster then page view, and page view does not follow the animation duration as tab controller). https://github.com/flutter/flutter/issues/55625
Maybe that is why you feel the delay?

**Comment by AyushBherwani1998** [comment]
The point of exposing the callback was to reduce the boilerplate code for users, but it completely makes sense to avoid it since the framework already has a way to achieve the desired result.

**Comment by shihaohong** [comment]
I agree with @chunhtai, if there's a way to already achieve this effect, we should just use it (and encourage it), since adding the new API could be confusing to users, which was one of my original concerns.

@AyushBherwani1998 Maybe we can repurpose your PR to instead describe API documentation that points users to how to achieve this outcome.

**Comment by AyushBherwani1998** [comment]
@shihaohong Happy to contribute in any way. Are we looking forward to having an example for this or just normal documentation?

**Comment by fluttercorner** [comment]
[How to Create TabBar in Flutter Complete Guide To Make TabBar](https://fluttercorner.com/how-to-create-tabbar-in-flutter-complete-guide-to-make-tabbar/)
