### ISSUE TITLE
Plugin with android fragment code do not work

### ISSUE THREAD

**Issue by dolpheen** [flutter/flutter#53159]
Hi!

I have a video player Android SDK that uses android fragments for embedding in app.
Tried different ways to wrap it in plugin with AndroidView but no results - can not use fragment transaction in plugin, do not know how to get view IF for replace operation.

Have anybody experience  with android fragment in plugins?

**Comment by dolpheen** [comment]
Escalated to 
https://stackoverflow.com/questions/60839201/android-fragments-in-flutter-plugin

**Comment by sivaperumal644** [comment]
Hi @dolpheen , Can you give me any idea on how you resolved this. I am facing a similar kind of situation. And the stackoverflow link you commented throws page not found.

**Comment by dolpheen** [comment]
> Hi @dolpheen , Can you give me any idea on how you resolved this. I am facing a similar kind of situation. And the stackoverflow link you commented throws page not found.

Did not managed to resolved issue. Asked developers of plugin update their API to support 'Android Surface'
