### ISSUE TITLE
Support WindowProc delegation in plugin API

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53168]
There are cases where plugin functionality requires changing the behavior of the WindowProc of the top-level HWND and/or the Flutter HWND. Examples:
- https://github.com/google/flutter-desktop-embedding/issues/483
- https://github.com/google/flutter-desktop-embedding/issues/636

We should allow plugins to register as delegates of the top-level WindowProc (if the app chooses to provide it; for add-to-app this would not always make sense, so we should be clear that it is not required to work) and the Flutter WindowProc (if we keep an HWND-based approach at that level).

**Comment by stuartmorgan** [comment]
Adding to the preview milestone since I want to make sure we can add this without causing API breaks; it will be a useful test case for that.

**Comment by stuartmorgan** [comment]
Since the only use case I'm aware of for delegating the view-level WindowProc (cursors) is now handled by the framework, I'm going to scope this to just top-level window delegation. If anyone needs view-level delegation, please let me know (it should be easy to add later).

**Comment by SahajRana** [comment]
Hi @stuartmorgan, I was wondering if you could help me to understand how can we implement WindowProc in the plugin. As I couldn't find any reference/example for the implementation.

**Comment by stuartmorgan** [comment]
The [`window_size` plugin](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/windows/window_size_plugin.cpp) is an example of using this API.

**Comment by SahajRana** [comment]
@stuartmorgan, I made the changes as per the example, but I'm not sure how to call WindowProc (HandleWindowProc method). Let's say for "WM_MOUSEMOVE".

**Comment by stuartmorgan** [comment]
> I'm not sure how to call WindowProc (HandleWindowProc method).

You don't. You register it as a delegate method, as demonstrated in the plugin I linked to, and as explained in the API comment for `RegisterTopLevelWindowProcDelegate`.

If you need help figuring out how to accomplish some specific goal using the API, that would be a question for a resource like StackOverflow or Discord.
