### ISSUE TITLE
channel beta slow in recognizing devices after recent upgrade  

### ISSUE THREAD

**Issue by what2003** [flutter/flutter#53165]
channel beta get very slow in recognizing devices after recent  upgrade. I tried channel dev and stable, all fine.
no issue with flutter doctor. I use VScode.

**Comment by TahaTesser** [comment]
Hi @what2003 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by what2003** [comment]
sorry, did not think you response so fast!
here is my  flutter doctor -v, (channel dev now, I guess it doesn't matter)
╰─$ flutter doctor -v
[✓] Flutter (Channel dev, v1.16.1, on Mac OS X 10.15.2 19C57, locale zh-Hans)
    • Flutter version 1.16.1 at /Users/zhangtang/flutter
    • Framework revision e6b0f5f238 (10 days ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhangtang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • 吴杰的 iPhone7 • eed6e3b2d815420621d441672707634130e89e16 • ios            • iOS 12.1
    • Chrome      • chrome                                   • web-javascript • Google Chrome 80.0.3987.149
    • Web Server  • web-server                               • web-javascript • Flutter Tools

• No issues found!

**Comment by TahaTesser** [comment]
Hi @what2003 
You said channel beta but you provided `flutter doctor -v` for dev channel 

I've tested using beta and channel in VSC and device connects in less 6 seconds
but on dev channel, it's taking 12-16 seconds

Did you mean dev channel? or you're only experiencing this on beta channel?
Thank you

**Comment by what2003** [comment]
Sorry,false alarm,  it is working this time!
I switch back to channel beta, as you see in screenshot no device found even though flutter doctor -v shows my phone already connected. Restart Daemon, it is working this time! Last few times it was just nothing happened. False alarm, sorry for your trouble! Thank you for the response!
![image](https://user-images.githubusercontent.com/10448102/78065103-59c42600-73c5-11ea-9f35-446925e8cce0.png)

**Comment by what2003** [comment]
I tried several times again, it is varies each time.
There must be some issues in it, I think. But since I was only one brought it up, maybe it is not the big problem,,, for now.

**Comment by TahaTesser** [comment]
Hi @what2003 
In my testings also, it varies too

given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
