### ISSUE TITLE
No console output for Windows when run from Visual Studio

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53169]
When running under the VS debugger, I'm getting a console window, but nothing shows up in it:
- No observatory log line, so I can't get the observatory URL to attach to
- No Flutter exceptions

In theory there's code in the runner that is supposed to handle this (which is why the console window opens in the first place), but it's not working for me (and I'm not sure if it ever actually worked).

**Comment by stuartmorgan** [comment]
I dug into this a bit. When we create a console we need to freopen stdout/stderr not only in the runner, but in the engine--I believe because we are using static CRT linking.

Adding it in the runner is easy since we already know when we are creating the console. The engine side will need a bit more logic since we need to know when we should be doing it; I believe the Chromium output redirection code will be useful model in getting that right.

**Comment by deekay42** [comment]
As a temporary workaround to show all output, replace this line in main.cpp
```
int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
   _In_ wchar_t* command_line, _In_ int show_command) {
```
with 
`int main() {`
and remove
```
if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
       ::AllocConsole();
```
