### ISSUE TITLE
Proposal: `softWrap` Property for the `TextFormField` `labelText`

### ISSUE THREAD

**Issue by psygo** [flutter/flutter#53166]
## Use case

> This was originally posted on StackOverflow. Check it out [here](https://stackoverflow.com/q/60804205/4756173).

To avoid height changes when receiving error messages, I decided to show the error messages on the `labelText`. However, the `labelText` only allows for short error messages, even though there is still space for many more characters.

```dart
TextFormField(
  ...
  decoration: InputDecoration(
    labelText: 'min 8 characters allowed',
  ),
),
```

![image](https://user-images.githubusercontent.com/11823725/77440795-778efb00-6dc7-11ea-9fc3-0f87829ade54.png)

## Proposal

I wish there were a way of controlling the amount of characters shown before everything gets replaced by the ellipsis (`…` or `Unicode 2026`) character.

This could be achieved through a `softWrap` property, similar to what's on the `TextField`. We wouldn't be able to control how many characters are shown, but at least we could explore the full width of the `labelText`.

The closest I've been able to get to know where the ellipsis is put in is [this line](https://github.com/flutter/flutter/blob/fed6ce17f8e17b1e6e8e2f84229e48af458c80af/packages/flutter/lib/src/painting/text_painter.dart#L272), inside the `TextPainter` class. I've checked out plenty of other related files, but with no success<sup>1</sup>.

<hr>

<sup><sup>1</sup> This should be related to `TextStyle`, shouldn't it?</sup>

**Comment by justinmc** [comment]
The ellipsis behavior in Flutter is a bit weird, see https://github.com/flutter/flutter/issues/18761.  Is that the same problem you're seeing in the label here?  I worry that a new parameter might not fix this without fixing that generic ellipsis issue first.

**Comment by psygo** [comment]
The workaround mentioned created by @marcglasberg is basically what I wanted to do indeed, though I haven't tested it yet and would like it to be more generic.

**Comment by justinmc** [comment]
Sounds good.  I'll prioritize https://github.com/flutter/flutter/issues/18761 and revisit this when that one gets fixed.  I hope that workaround helps you out in the meantime.

**Comment by psygo** [comment]
By the way, how did you find that issue? Was it only by Googling it? Was it by experience with the repo only or do you guys at Google have a more specialized tool for search inside repos?

**Comment by justinmc** [comment]
No special tool, I just remembered seeing it before, and I had written it down as an issue that I'd like to get fixed.  The only search tip I have is to use the labels if it clearly should be related to one of them.  There are tons of issues to narrow down, but most of them do have labels now at least.

**Comment by olfek** [comment]
I need the `Text` widget `softWrap` property for `TextField`, find it hard to believe that something so simple but important is missing.

**Comment by justinmc** [comment]
I'm going to close this since there is a workaround mentioned above, and it hasn't received much attention in the last few years. If anyone still thinks we should implement something like this, please comment and I can reopen, or open a new issue.
