### ISSUE TITLE
App reloading on Navigator.push using AuthenticationBloc

### ISSUE THREAD

**Issue by Addeuz** [flutter/flutter#53171]
Hello, I have followed this authentication tutorial using blocs: https://bloclibrary.dev/#/flutterlogintutorial, and everything worked perfectly. Except that I hade to change in på main.dart from just return the page I want to go to if I login successfully to pushing to the widget page with this:
```
WidgetsBinding.instance.addPostFrameCallback((_) {
    print("Authenticated");
    Navigator.of(context).push(
        MaterialPageRoute(
             builder: (context) => TodaysPage(),
         ),
     );
});
// return TodaysPage();
```
I did this because the app didn't change view to the TodaysPage view after signing in. Only after "refreshing" the simulator from VS Code debugging tool. So I know that the bloc states changes fine.

And this solution has worked perfectly for a month give or take. And I use this way of navigating in my app a lot. I first used `Navigator.pushNamed(...)` but then the authentication blocs context wouldn't carry over so I couldn't log out if I changed routes after logging in. However that is not my problem right now.

When I started up my simulator today and ran the app the app behaved very strange. This is what happens when I log in (SORRY FOR BIG IMAGE):
![Skärminspelning-2020-03-24-kl -16 48 47](https://user-images.githubusercontent.com/12641358/77447973-9950a800-6df0-11ea-8301-de64c591f2c1.gif)

It seems to me like the navigator pushes over and over.

My code works fine (except that I have to refresh every time I log in) if I go with the `return` statement instead of `Navigator.of(context).push.....`

If I look at my debug console I see this:
![image](https://user-images.githubusercontent.com/12641358/77448782-7ecafe80-6df1-11ea-9171-d12d29ed48d1.png)

And this is the code for handling the authentication state:
```
if (authState is AuthenticationAuthenticated) {
    print("Authenticated");
    WidgetsBinding.instance.addPostFrameCallback((_) {
        Navigator.of(context).push(
            MaterialPageRoute(
                builder: (context) => TodaysPage(),
            ),
        );
    });
    // return TodaysPage();
}
if (authState is AuthenticationUnauthenticated) {
     print("LoginPage loading");
     return LoginPage(userRepository: userRepository);
}
if (authState is AuthenticationLoading) {
     return CircularProgressIndicator();
}

print("SplashPage");
return SplashPage();
```

I have tried other ways of using the `Navigator` but they all give the same result..

This bug is super frustrating since it was working last week when I worked on the app.. And I was almost done with it and was going to show it to my client..

<details>
  <summary>flutter doctor -v gives this:</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale sv-SE)
    • Flutter version 1.12.13+hotfix.8 at /Users/andreas/Library/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andreas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/andreas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 84A08DAE-713B-4A10-94C7-51CCCCF3FF1C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
