### ISSUE TITLE
it's a nightmare to make flutter work on mac, i give up using that language

### ISSUE THREAD

**Issue by daniloaqui** [flutter/flutter#53175]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by fabiancrx** [comment]
Any tangible reason or context about how can you be helped or just ranting in a repo with 7k problems just to make the maintainers work harder?

**Comment by stuartmorgan** [comment]
Closing as there is no actionable information here. If you have specific feedback, please file a new issue with details.
