### ISSUE TITLE
--fast-start is not working in combination with --no-hot

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#53173]
As in the title, I'm trying to create a target in my `Makefile` that looks like that:

```bash
run-fast:
  flutter run -d $(DEVICE_ID) --fast-start --target=test_driver/journeys/attend.dart --host-vmservice-port $(VM_PORT) --disable-service-auth-codes --no-hot
```
Doing so makes my app to get stuck with the splash screen that says:
> this app is only meant to be run under the Flutter debugger

Which is not the case while running the app directly in the console without using `make`

Basically looking at the log that `flutter run` produces in both cases, the first one is missing the 
> Syncing files to device Android SDK built for x86.. 

There is something that I'm missing here?

My `flutter doctor -v` output:

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.15.17 at /Users/nerder/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nerder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[!] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by jonahwilliams** [comment]
--fast-start builds an application bundle that doesn't contain your app sources or assets, then hot restarts your application into the bundle. This can be faster since it allows native build tools to skip subsequent rebuilds of the APK/IPA when only dart source is invalidated.

**Comment by nerder** [comment]
> --fast-start builds an application bundle that doesn't contain your app sources or assets, then hot restarts your application into the bundle. This can be faster since it allows native build tools to skip subsequent rebuilds of the APK/IPA when only dart source is invalidated.

Thank you @jonahwilliams  for the fast reply and explanation, this clarifies a lot but still don't think it will solve my issue since everything seems to work fine while running the command from the shell directly, but not performing the hot reload when running as a `make` command.

Plus since you are saying that is `fast-start` do hot restart the app after the initial build of the lightweight mock app, the fact that in my command I'm using `no-hot` might have an impact? Since what I'm looking for here is startup performance, is actually `no-hot` might have any performance benefit whatsoever?

**Comment by jonahwilliams** [comment]
I don't really know what exactly you're trying to accomplish, but the --fast-start command is not meant to be used for this. If you want, you could build the APK/IPA independently and then use `--use-application-binary=path/to/app/.apk` to launch without building

**Comment by nerder** [comment]
I just double check and yes! Actually `--fast-start` and `--no-hot` are not compatible for the same reason you are saying!

I think tho that this should at least expressed in the `--help` or even crash with an error that explains it.

**Comment by nerder** [comment]
> I don't really know what exactly you're trying to accomplish, but the --fast-start command is not meant to be used for this. If you want, you could build the APK/IPA independently and then use --use-application-binary=path/to/app/.apk to launch without building

This will not work for my use case since I would like to initially build my app before running the e2e tests, I'm trying to speed this up a little bit while developing instead of using the `flutter driver` which takes way to long. 

Also, I saw that `--fast-start` is going to become the default option is the combination with `--no-hot` might cause problems?

**Comment by jonahwilliams** [comment]
Yeah, passing --no-hot and --fast-start should exit.

**Comment by nerder** [comment]
Is this relevant anymore?

**Comment by exaby73** [comment]
Hello @nerder. Since `--fast-start` was removed in a previous version of Flutter, this issue doesn't seem relevant anymore. Closing as fixed. If you disagree, please comment and we can re-open it. Thank you
