### ISSUE TITLE
[web] use the same version of chrome in both unit tests and integration tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#53179]
In the current engine tests, the unit tests are downloading and running a given chrome version.

On the other hand the integration tests are using the system chrome. We should use same chrome for both of them. 

In order to do this:

- [x]  Flutter drive be started with chrome executable
- [x]  Felt code should be changed to use the same Chrome.
- [x] (for LUCI) Recipe load CIPD packages for Chrome/ChromeDriver for same version
- [ ]  (for local) Web installers should be used to download the chrome.

**Comment by nturgut** [comment]
Reopening I accidentally closed this issue.

**Comment by yjbanov** [comment]
This was done as part of moving all e2e tests to flutter/flutter.
