### ISSUE TITLE
Enable the usage of  --delete-tostring-package-uri in the flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#53174]
These are extra frontend options that need to be passed to the frontend server invocation as a multi option, such as `--delete-tostring-package-uri=dart:ui` and `--delete-tostring-package-uri=package:flutter`.

We could make these options the default in the future without changing the behavior here, or expose delete-tostring directly, though users might have trouble configuring it.

**Comment by jonahwilliams** [comment]
FYI @dnfield for more thoughts

**Comment by dnfield** [comment]
We could start with just exposing the `--extra-front-end-options` parameter to more of the tool, so that advanced users could opt into this.  We shouldn't make it too easy to do just yet, because we'd really like to see some more testing of it first.

@chingjun FYI
