### ISSUE TITLE
[pigeon] support docstrings for generated code 

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#53191]
It would be nice if the docstrings on the pigeon file were transferred to the generated code.

One problem is that dart docstring idioms don't match those for objc or java.

**Comment by xster** [comment]
@GaryQian this one seems an isolated additive feature. We could do a go-nogo test quickly by checking whether the comments are accessible via reflection on the dart file.

**Comment by xster** [comment]
seo: doc documentation dartdoc javadoc

**Comment by stuartmorgan** [comment]
This was fixed.
