### ISSUE TITLE
Please add Scaffold to the Widgets page

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#532]
The Scaffold class is used frequently in the example code, so I propose that it be added to the Widget Gallery at http://flutter.io/widgets/.

**Comment by abarth** [comment]
Yeah, the widget gallery needs a ton of work.  /cc @sethladd

**Comment by Hixie** [comment]
I think we should do this as part of https://github.com/flutter/flutter/issues/1433

**Comment by sethladd** [comment]
Agreed. I'm going to close this in favor of #1433
