### ISSUE TITLE
Image Picker - Error Piking Image "PlatformException(already_active, Image picker is already active, null)"

### ISSUE THREAD

**Issue by zoulu123** [flutter/flutter#53216]
I have the problem,first run in android device,give the permission and can not open ,but when i kill the process ,it can open

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/zoulu/tool/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zoulu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/zoulu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1
```

**Comment by iapicca** [comment]
Hi @zoulu123 
can you please provide your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by zoulu123** [comment]
[flutter run --verbose--info.txt](https://github.com/flutter/flutter/files/4384923/flutter.run.--verbose--info.txt)


[pubspec_yaml.txt](https://github.com/flutter/flutter/files/4384933/pubspec_yaml.txt)

**Comment by iapicca** [comment]
Hi @zoulu123 
I see that your verbose stops with the app launching,
could you please provide the logs representative of the error
Thank you

**Comment by zoulu123** [comment]
It's so strange，i do nothing ,It's good for me，It's good just like bad at first！I don't known
what happened
[run_log.txt](https://github.com/flutter/flutter/files/4391848/run_log.txt)

**Comment by kw2019ltd** [comment]
hi same issue for me iam using

Non-fatal Exception: java.lang.Exception: PlatformException(already_active, Image picker is already active, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:569)
       at MethodChannel._invokeMethod(platform_channel.dart:156)
       at ImagePicker.pickImage(image_picker.dart:56)
       at ScanWidgetState._getImage(scan_widget.dart:107)

**Comment by iapicca** [comment]
Hi @zoulu123 
does the issue persists with the latest stable version of flutter
and the latest version of the plugin?
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kw2019ltd** [comment]
same issue Non-fatal Exception: java.lang.Exception: PlatformException(already_active, Image picker is already active, null)

**Comment by SergeiEensalu** [comment]
The same issue: 
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity

and PlatformException(already_active, Image picker is already active, null)

**Comment by iscriptology** [comment]
Hey Guys. I had the same problem. Took me an hour to figure this out. In my case I extended `FlutterActivity` in order to implement a `MethodChannel` and I had an override for `onActivityResult`. 
Problem was I forgot to call `super.onActivityResult(requestCode, resultCode, data)` after my custom handling so the plugin and therefore the dart code didn't handle the result.

Hope it helps someone.

**Comment by bagazi** [comment]
iscriptology   U are right! Helps a lot for me! Thanks!

**Comment by bssam1996** [comment]
@iscriptology How did you do that ? Am having the same issue in release mode and I can't solve it.

**Comment by KClassmate** [comment]
[集成boost后所有第三方image选择图片库都无法使用 #263](https://github.com/alibaba/flutter_boost/issues/263)

**Comment by maerlynflagg** [comment]
i get this issue currently on Google Pixel 3, Android 11 device.  same app version on Huawai P30 Pro or Android Emulator on a Windows System all is fine. not issue detected.

**Comment by dnesbala** [comment]
If this problem occurs during debug mode, then your USB might have been connected as only "USB Drive" rather you have to give access to "Files" as shown in the picture below.
![image](https://user-images.githubusercontent.com/33943740/111122377-1511aa80-8596-11eb-8640-85a7b79a6822.png)

**Comment by mtuan0111** [comment]
Anyway, I have the same issue when using Image Picker.

I have solved the trouble, it needs to provide permission to access the camera and storage memory on the **release** mode.

- On Android: 

Add `src/main/AndroidManifest.xml:` inside the manifest tag

` <uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
    

- On IOS: 

Add `Info.plist`
`<key>NSPhotoLibraryUsageDescription</key>
<string>Allow access to photo library</string>

<key>NSCameraUsageDescription</key>
<string>Allow access to camera to capture photos</string>`

Good luck, hope it will be useful!
