### ISSUE TITLE
[web] [Internet Explorer] TextField hide text went out of Focus

### ISSUE THREAD

**Issue by nttd-jieyangxu** [flutter/flutter#53218]
i use the lastest version 1.16.1 for flutter web

**Steps** 
1. Run the deployed webApplication in IE
2. In TextField input text 
3. click anywhere out of the TextField
4. click on the TextField
5. text disappearing
6.click [space] in the keyborad 
7.disappeared text is appearing

Run the deployed webApplication in chrome ,issue do not happen

**Comment by nttd-jieyangxu** [comment]
Captured image for step3~7。
![textfield_step3](https://user-images.githubusercontent.com/62096778/77500597-77a6fd80-6e90-11ea-95a3-ac885d28ebd7.png)
![textfield_step4and5](https://user-images.githubusercontent.com/62096778/77500599-78d82a80-6e90-11ea-84fc-7f06e43a7663.png)
![textfield_step6and7](https://user-images.githubusercontent.com/62096778/77500600-7970c100-6e90-11ea-9fd6-b23273eb2d19.png)

**Comment by nttd-jieyangxu** [comment]
Captured image for step3~7。
![textfield_step3](https://user-images.githubusercontent.com/62096778/77500672-b89f1200-6e90-11ea-877e-d5ab1cca3fad.png)
![textfield_step4and5](https://user-images.githubusercontent.com/62096778/77500677-b9d03f00-6e90-11ea-8ec2-f8252221d253.png)
![textfield_step6and7](https://user-images.githubusercontent.com/62096778/77500678-b9d03f00-6e90-11ea-9ec9-c9971163496a.png)

**Comment by nttd-kudouyus** [comment]
We also tried v1.16.2 but still have the same problem.

`flutter doctor` is shown below:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.14.5 18F2058, locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by nttd-kudouyus** [comment]
@iapicca 
TextField hide text when ~~out of Focus~~ → re-focus on it (step3~7)

**Comment by iapicca** [comment]
to reproduce please open this [link](https://masterflutter.codemagic.app/) on internet explorer
(thank you @TahaTesser for publishing the static website)

@nttd-jieyangxu 
the situation appears to be  exactly the one you described
thank you for reporting the issue

**Comment by nturgut** [comment]
Thanks for filing the issue.

**Comment by nttd-kudouyus** [comment]
@iapicca Thank you for sharing the link! I was able to see the same problem at the link.
We hope it will be resolved.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.21.0-6.0.pre.17` with Internet Explorer `Version: 11.959.18362.0`.
Does not reproduce with Microsoft Edge, Chrome or Firefox.
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.17, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.17 at C:\Development\flutter_master
    • Framework revision e64fe11542 (9 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by yjbanov** [comment]
IE11 is no longer supported
