### ISSUE TITLE
Need hook into when signInSilently completes

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5322]
_From @drewwarren on June 3, 2016 2:27_

Currently our "Sign in" page is displayed for ~1 second before signInSilently succeeds. I'd love to show a loading indicator during this time but I don't see a way to hook into this. I only want to show the sign in page if signInSilently cannot sign the user in.

_Copied from original issue: flutter/google_sign_in#12_

**Comment by sethladd** [comment]
_From @collinjackson on June 16, 2016 20:6_

I am working on supporting this for the next iteration of the API. Thanks!

**Comment by sethladd** [comment]
_From @eseidelGoogle on July 6, 2016 17:17_

Drew asked about this and https://github.com/flutter/google_sign_in/issues/10 today in our meeting.  Presumably this is part of the HostMessages update you have in progress?

**Comment by sethladd** [comment]
_From @collinjackson on July 6, 2016 17:22_

Yes, this is fixed in the v2 branch. signInSilently returns a Future that you can wait on to get the result.

**Comment by collinjackson** [comment]
This is fixed in the latest google_sign_in.
