### ISSUE TITLE
Need hook into delay after clicking "Allow" and onCurrentUserChanged firing

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5323]
_From @drewwarren on June 3, 2016 2:22_

Currently after clicking allow the previous UI is displayed for ~1 second before onCurrentUserChanged fires. This makes the user questions if "Allow" even worked during that 1 second and is undesired. I would love to be able to display a loading indicator during this time.

I can't simply switch to a loading indicator when calling signIn because if the user clicks deny I have no way of hooking into "Deny" to switch away from said loading indicator.

_Copied from original issue: flutter/google_sign_in#10_

**Comment by sethladd** [comment]
_From @collinjackson on June 16, 2016 20:6_

I am working on supporting this for the next iteration of the API. Thanks!

**Comment by collinjackson** [comment]
This is fixed in the latest google_sign_in.

**Comment by sethladd** [comment]
Cool, thanks for the update!
