### ISSUE TITLE
NOT ABLE TO ACCESS THE MASTER BRANCH , NEITHER THE BETA BRANCH

### ISSUE THREAD

**Issue by aditya-singh20** [flutter/flutter#53231]
git: fatal: 'origin/beta' is not a commit and a branch 'beta' cannot be created from it
Switching channels failed with error code 128.
git: fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
Switching channels failed with error code 128.

**Comment by TahaTesser** [comment]
Hi @aditya-singh20 

can you please provide your `flutter doctor -v`?

Could you please try running 
```
 flutter channel master
 flutter upgrade --force
```
Thank you

**Comment by aditya-singh20** [comment]
PS C:\flutter> flutter doctor -v
[√] Flutter (Channel unknown, v0.0.0-unknown, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)
    • Flutter version 0.0.0-unknown at C:\flutter
    • Framework revision e40f78c15e (3 hours ago), 2020-03-25 13:48:06 +0530
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Vijay Singh\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\Vijay Singh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

here it is !!!

**Comment by aditya-singh20** [comment]
@TahaTesser

**Comment by aditya-singh20** [comment]
PS C:\flutter> flutter channel master
Switching to flutter channel 'master'...
git: fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
Switching channels failed with error code 128.
PS C:\flutter> flutter upgrade --force
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin https://github.com/flutter/flutter' in   
C:\flutter

This is what it gives all time

**Comment by iapicca** [comment]
Hi @aditya-singh20 
please try to run the command hinted in the error
`Run 'git remote add origin https://github.com/flutter/flutter' in  C:\flutter`
let me know if the issue persists
Thank you

**Comment by aditya-singh20** [comment]
@iapicca  Thank you sir,
Got the perfect solution to the problem.

**Comment by djgupta** [comment]
I faced the same issue, the depth parameter was the problem. Remove that and channelling is smooth.
git clone https://github.com/flutter/flutter.git -b stable **--depth 1**

**Comment by smithki** [comment]
FWIW, I was able to fix by adding the [`--no-single-branch`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---no-single-branch) flag, which gave me better performance than removing the `--depth` flag, so my full cloning command looked like this:

```bash
git clone https://github.com/flutter/flutter.git -b stable --depth 1 --no-single-branch
```

**Comment by shubhamhackz** [comment]
> git remote add origin https://github.com/flutter/flutter'

Perfect Solution.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
