### ISSUE TITLE
Need an option to show Cupertino modal with transparent modal barrier

### ISSUE THREAD

**Issue by AndreiBelokopytov** [flutter/flutter#53239]
## Use case

I am working on iOS app and I want to show a Picker component inside a popover using the following code:
```
showCupertinoModalPopup(
  context: context,
  builder: (BuildContext context) {
    return Container(
      height: 160,
      child: CupertinoPicker(
        itemExtent: 32,
        children: currencies
            .map((currency) => Center(
                  child: Text(currency),
                ))
            .toList(),
        onSelectedItemChanged: (int value) {},
      ),
    );
  });
```
Comparing my result with an example from Human Interface Guidelines ( https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/) I mentioned that my component displays a shadow overlay over the page's content while the example does not.
It would be nice to rid of that overlay to make a Cupertino picker looks closer to a native when it placed inside a modal.

## Proposal

`showCupertinoModalPopup` should provide an option to manage the barrier color. For example:
```
Future<T> showCupertinoModalPopup<T>({
  @required BuildContext context,
  @required WidgetBuilder builder,
  bool useBarrierColor = true,
  ImageFilter filter,
  bool useRootNavigator = true,
}) {
  assert(useRootNavigator != null);
  return Navigator.of(context, rootNavigator: useRootNavigator).push(
    _CupertinoModalPopupRoute<T>(
      barrierColor: useBarrierColor
          ? CupertinoDynamicColor.resolve(_kModalBarrierColor, context)
          : null,
      barrierLabel: 'Dismiss',
      builder: builder,
      filter: filter,
    ),
  );
}
```
when `useBarrierColor` is false the modal barrier becomes transparent which is useful when displaying CupertinoPicker. Since `useBarrierColor` is true by default this change wouldn't break the current widget API.

**Comment by xster** [comment]
Yes, adding an overridable color for the barrier is a reasonable change. Feel free to send us a PR :)

**Comment by kavu** [comment]
@xster Hi! I submitted a PR with this change, I hope it can help and is good enough.

**Comment by willlockwood** [comment]
@DanielEdrisian it looks like this can be closed, no? Do you have the ability to do that?
