### ISSUE TITLE
After $ flutter run -d chrome its showing error.

### ISSUE THREAD

**Issue by aditya-singh20** [flutter/flutter#53247]
I viewed similar issues on Github and tried $flutter clean also $flutter pub cache repair 
but still after $flutter run -d chrome it shows 

Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example  
due to a firewall.

is their something like firewall settings in chrome.

**Comment by VladyslavBondarenko** [comment]
Hi @aditya-singh20 
Please follow up on https://github.com/flutter/flutter/issues/49482
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by aditya-singh20** [comment]
@VladyslavBondarenko 
Sir, i tried the solution mentioned there and did flutter clean and flutter pub cache repair but the problem continues
