### ISSUE TITLE
AnimationController.repeat duration should be documented

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#53255]
Looking at the documentation there is nothing documented about what `duration` does.

https://api.flutter.dev/flutter/animation/AnimationController/repeat.html

This makes it harder to use and developers have to guess, google elsewhere or look at the source code for AnimationController.repeat directly.

**Comment by VisheshAtWork** [comment]
@VladyslavBondarenko  I would like to get assigned to this issue.

**Comment by VladyslavBondarenko** [comment]
@VisheshAtWork 
you can open a PR and mention the issue there
