### ISSUE TITLE
webview_flutter  cannot get full cookie? 

### ISSUE THREAD

**Issue by jarwin123** [flutter/flutter#53257]
Hi all:
     i get cookie throuht webview_flutter, but the cookie is not complete, 
     `await controller.evaluateJavascript('document.cookie');`
    so have some other way get full cookie?

**Comment by VladyslavBondarenko** [comment]
Hi @jarwin123 
Please follow up on https://github.com/flutter/flutter/issues/27795 and thumb it up,
see also https://flutter.dev/community for resources and asking questions,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by jarwin123** [comment]
@VladyslavBondarenko  my question is not same #27795， The point of my question is getting cookie  incomplete,  Much less than fetching  cookies with a browser， so reopen it ， thanks

**Comment by erickok** [comment]
@VladyslavBondarenko yes this is a duplicate. It is normal that `document.cookie` doesn't give all cookies and the linked dup ticket even mentions httpOnly cookies - whcih are the ones that are missing when using `document.cookie`.

**Comment by VladyslavBondarenko** [comment]
Thanks @erickok
