### ISSUE TITLE
most of the cards in the <elided application> have some weird garbled text

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53263]
https://b.corp.google.com/issues/152100618

**Comment by kf6gpe** [comment]
Googler hasn't been able to reproduce due to setup / configuration problems while sheltering-in-place. Perhaps escalate to @cbracken, who may have a similar setup and can try?

**Comment by kf6gpe** [comment]
gentle ping to @cbracken and @chinmaygarde; is there an update here?

**Comment by chinmaygarde** [comment]
No update since I would not reproduce it in the test harness. I also don't expect to make progress reproducing this on device till I get back to the office.

**Comment by kf6gpe** [comment]
Direction from upstream filer is for us to review some linked bugs on the upstream request.

**Comment by kf6gpe** [comment]
@chinmaygarde, did you have any luck with the linked bugs on the upstream request yet?

**Comment by Hixie** [comment]
I'm going to close this. The upstream bug was sent back to the customer for a repro.
