### ISSUE TITLE
AnimationController should have the ability to repeat n times

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#53262]
## Use case

AnimationController should provide a simple way to repeat n times, currently, this is not possible from what we could find.
This is the nearest and simplest solution: https://stackoverflow.com/questions/59462290/repeating-animations-specific-times-e-g-20-times-by-flutter/59463013#59463013

If an animation should repeat n times, it should do the animation and then jump back to `0` (or `1` for reverse) and do the animation again. Until it reached `1` (or `0` for reverse) n times and then stop there and send a `completion` event in the status listener.

## Proposal

```dart
controller = AnimationController(
  vsync: this,
  duration: const Duration(seconds: 2),
)
..repeat(times: 3)
..addStatusListener((status) {
    if (status == AnimationStatus.completed) {
      print("Has repeated 3 times. Execution took 6 seconds.");
    }
});
```

**Comment by Nico04** [comment]
The issue with the [stackoverflow implementation](https://stackoverflow.com/questions/59462290/repeating-animations-specific-times-e-g-20-times-by-flutter/59463013#59463013) is that if you call stop() or reset() before timeout, the onTimeout callback is still executed, which can cause weird behaviour if animation is started again before that timeout.
I've noticed that the repeat() future never complete, is that a Flutter bug ?

**Comment by angelhdz** [comment]
Has this been implemented?

**Comment by IchordeDionysos** [comment]
No, but should be easily implementable in this file:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/animation/animation_controller.dart

By counting/calculating the number of loops in the `_RepeatableAnimationSimulation` :)

**Comment by aliasgar4558** [comment]
Raised PR for this as a feature.
