### ISSUE TITLE
Support macOS Version lower than Mojave?

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter#53274]
`Flutter requires a minimum Xcode version of 11.0.0.`

Why not support high sierra?Is there any difficulty to support it.Maybe it will be supported in the future?

**Comment by jonahwilliams** [comment]
> Starting April, 2020, all apps submitted to the App Store will need to be built with Xcode 11. Xcode 11 requires macOS Mojave 10.14. 3 or later. You need Xcode 6 (or newer) or Application Loader 3 (or newer).

See https://developer.apple.com/app-store/submissions/

**Comment by entonio** [comment]
Developing an app and submitting it to the App Store are very different things.
