### ISSUE TITLE
Allow bypassing host filtering on downloaded artifacts

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53272]
Currently, `flutter precache` won't download artifacts that it can't possibly use on the current host system, regardless of flags passed. We need a way to bypass that (see b/141472232 for context).

@jonahwilliams Should I just add a hidden flag to precache that disables the filter?

/cc @mehmetf

**Comment by jonahwilliams** [comment]
Yes - you can use the existing --all flag, this already exists to pull in host artifacts specifically for the roll script IIRC.

**Comment by stuartmorgan** [comment]
Okay, will do. I was hesitant about existing flags since I know we've had various bugs/discussions about how precache should work and how the flags should interact (although I guess that's an equally good reason for not adding another one!)

**Comment by stuartmorgan** [comment]
Oh I see, `--all-platforms` is already supposed to do exactly this. Maybe this is the same issue as https://github.com/flutter/flutter/issues/37827 then? I'll keep digging.

**Comment by jonahwilliams** [comment]
Ahh right, it is called `--all-platforms`. 

What you're running into is code like: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L862

The EngineCachedArtifact classes need to be updated to be aware of this flag

**Comment by stuartmorgan** [comment]
Okay, that was a trivial change since it was already partially plumbed through.

With that fix, I still need to pass `--all-platforms --macos`; is that the behavior we want, or should `--all-platforms` imply the other platform flags?

**Comment by mehmetf** [comment]
I would prefer the latter. In fact, I am not sure why we have `--all` and `--all-platforms`

**Comment by stuartmorgan** [comment]
> In fact, I am not sure why we have --all and --all-platforms

We don't; what Jonah called `--all` above is actually `--all-platforms`. It's just that it appears that what it does is disable filtering (once I fix the desktop checks) but doesn't actually put all the desktop platforms into the set.

**Comment by stuartmorgan** [comment]
Changing `all-platforms` to enable everything by default intersects somewhat with https://github.com/flutter/flutter/issues/37184, so I'm not sure if changing it right now is actually a good idea. This code is already complex, and it may make more sense to pass an extra flag until that issue is resolved instead of adding another special case.

**Comment by stuartmorgan** [comment]
Okay, I have a targeted change that will make `--all-platforms` actually get **everything**. However, in my cases that includes a bunch of fuchsia binaries which added about a minute and a half to the `precache` step. Longer term, that will also mean a bunch of Windows and Linux binaries (three variants of each) that the script probably won't be using.

@mehmetf Is your preference that `--all-platforms` get every possible artifact, with no possibility of limiting it to just the ones you actually want (vs. the current behavior of turning off host filtering, but still requiring you to say which things you do and don't want)? If the flag is for the roller, it's presumably your call.

**Comment by stuartmorgan** [comment]
@mehmetf Ping on the question above; once it's resolved I can move forward with the patch and unblock the changes to the roller.

**Comment by mehmetf** [comment]
Sorry, I missed the last comment.

We should only do implicit filtering if an explicit platform flag is not passed. I was thinking the following:

`--all-platforms`: Gets all platforms
`--ios`: Gets iOS
`--mac`: Gets Mac
`--linux`: ....
etc.

None of these should implicitly filter artifacts to avoid surprises. If the user does not specify these (which is the common case for upstream usage), then we can try to be intelligent.

**Comment by stuartmorgan** [comment]
@jonahwilliams Are you okay with that behavioral change, given that it affects more than just the `--all-platforms` flag? It seems like it's in line with https://github.com/flutter/flutter/issues/37184 so I assume probably yes, but I'd like to be sure before reworking it.

**Comment by jonahwilliams** [comment]
Yes, that sounds like a good change. Its a much softer breaking change than my original proposed `flutter precache` with no platforms downloads nothing, and gets us closer to the behavior we'd like long term

**Comment by stuartmorgan** [comment]
PR posted. Two subtleties:
- The disabling of implicit filtering applies *only* to the artifacts specified by command line flags, rather than all implicit filtering being disabled if any arguments are provided. This was necessary to avoid some bad behaviors around universal artifacts with platform variants. (E.g., `--all-platforms` may want every platform's font subsetting artifacts, but `precache --macos` shouldn't suddenly get all of those variants too).
- Feature flags are still honored no matter what arguments you pass. So `precache --macos` will give you macOS desktop artifacts only if `flutter config --enable-macos-desktop` has been set. (Arguably we should hide the flags corresponding to features that aren't enabled, but that's potentially breaking, so I left that for later decision/implementation if anyone feels strongly about it.)

**Comment by jonahwilliams** [comment]
Thanks for fixing this @stuartmorgan !
