### ISSUE TITLE
Visualize expensive widgets/layers, e.g. opacity

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#53277]
Opacity is expensive.  Sometimes a developer might be using it without realizing it or needing it, and benefit from avoiding it or using some alternative. 

It's possible on a particular screen (for ap articular frame) to debug dump the widget/render/layer trees and look for Opacity related widgets/renderobjects/layers (and similar for other expensive graphics operations like image filters and backdrop filters).

It would be helpful to have some way to visualize this at runtime, so that developers can more easily see which graphical elements on the screen are costing the most for a particular screen.

/cc @dreveman @liyuqian @flar

**Comment by HansMuller** [comment]
Maybe the "performance" section of the Opacity widget's API doc could be more informative.

**Comment by dnfield** [comment]
The docs already say:

```
/// For values of opacity other than 0.0 and 1.0, this class is relatively
/// expensive because it requires painting the child into an intermediate
/// buffer. For the value 0.0, the child is simply not painted at all. For the
/// value 1.0, the child is painted immediately without an intermediate buffer.
```

Although they're not called out in a specific performance section.

**Comment by dnfield** [comment]
There are also some examples of how to use faster paths like a semi-transparent container or painting an image with transparency in there.

**Comment by liyuqian** [comment]
Is there an easy way to count how many modules are compiled with Oz, Os, and O3 while we're doing this transitioning? I'd like to also apply such counting to Flutter engine.

**Comment by Liuzhiyang94** [comment]
What make me confused is the difference between `RenderAnimatedOpacity` and `RenderOpacity`.

`RenderAnimatedOpacity` listen `Animation<double> opacity` changed, but in these two `RenderObject` the value set of `_opacity` and the `paint` method are same.

Does that meams `RenderAnimatedOpacity` just provder a simple way the perform the animation ,and actually its cost more gpu resource than `RenderOpacity` ?

**Comment by flar** [comment]
> The docs already say:
> 
> ```
> /// For values of opacity other than 0.0 and 1.0, this class is relatively
> /// expensive because it requires painting the child into an intermediate
> /// buffer. For the value 0.0, the child is simply not painted at all. For the
> /// value 1.0, the child is painted immediately without an intermediate buffer.
> ```
> 
> Although they're not called out in a specific performance section.

Actually, that will change with https://github.com/flutter/flutter/pull/61994

The behavior changes when a save layer comes and goes so special-casing 1.0 means that there is a discontinuity in some cases when an animation starts and the opacity goes from 1.0 to 0.9999. I'll note in the PR to update this section of the Opacity widget docs.

0.0 will still be special cased and dropped out of the tree because that behavior is consistent with the limit of opacity approaching 0.0.
