### ISSUE TITLE
Flutter keyboard does not handle delete-key key-repeat

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5328]
When you hold down the delete key in an iOS keyboard it initially deletes one character, then after a delay starts repeatedly deleting characters, and then after a while more starts deleting whole words on repeat.  It may even eventually go faster.  When you hold down the delete key in a text field in Flutter it doesn't seem to have this behavior.

This may be a very similar root cause to https://github.com/flutter/flutter/issues/4818.  I have not yet tested on Android, presumably we may have a similar bug there.

![img_0257](https://cloud.githubusercontent.com/assets/11857803/17572961/22e74576-5f0c-11e6-937e-70d3722419bb.png)

**Comment by cbracken** [comment]
Fixed by flutter/engine#3586
