### ISSUE TITLE
Raster cache's integral translation snapping is broken

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#53288]
We tried to snap the picture layer and its raster cache's translation/offset to integer points for both performance and quality considerations. (See [this line of code][1].)

However, we made a mistake: the fractional scale of `SkMatrix` will be applied to the picture's original offset. So if it has a non-zero original offset, say an integral x translation of 3, and the matrix has a fractional x scale of 1.5, they would result in final x translation of 4.5. Please check the unit test added in https://github.com/flutter/engine/pull/17278 for a concrete example.

Since we've never run into performance or quality issues while we did this wrong, I felt that maybe we can just remove the integer snapping logic. It will also solve https://github.com/flutter/flutter/issues/41654. Note that we previously still drew the raster cache with integral offsets because we're using a rounded-out `SkIRect` to determine the location of the raster cache.

[1]: https://github.com/flutter/engine/blob/dd102bf228af2199c5a6b8e099b15cbbdc0621fa/flow/layers/picture_layer.cc#L30

**Comment by liyuqian** [comment]
Thanks you @jason-simmons for writing the unit test to surface the issue!

@LongCatIsLooong : turning off integer snapping will resolve your issue #41654

@drwulf : I initially added that integer snapping because I heard from you that Android only has integral scrolling offsets. Do you know if there's any big problem is I just render the raster cache as if the offset is always (0, 0), and then later draw such raster cache image with arbitrary fractional offsets?

**Comment by liyuqian** [comment]
Talks with @drWulf offline and here's the comment
> you can draw with fractional offsets just fine, but as your mentioned it does has some performance implications. I think often trying to snap to pixel boundaries results in "jumpy/janky" text as it sometimes appears to pop between pixel values. it isn't very noticeable on hdpi devices, but for lower res it can be pretty obvious

**Comment by flar** [comment]
> However, we made a mistake: the translation in SkMatrix is before applying its scale factors. So an integral x translation of 3 and a fractional x scale of 1.5 would result in final x translation of 4.5.

Where does this come from? That violates the protocols for every transform implementation I've ever written, used, or seen.

And it does not match what the code does in `SkMatrix::Affine_vpts`:
```
            dst->set(src->fX * sx + src->fY * kx + tx,
                     src->fX * ky + src->fY * sy + ty);
```
That code does not apply the scale or skew values to the transform values...?

**Comment by liyuqian** [comment]
@flar : you're right, the scale isn't applied to the translation in the matrix (`tx`), it's applied to the original translation/offset (`src->fX * sx`). Anyway, our snapping is still problematic as the final `x` can be fractional even if we forced `tx` to be integral. I'll update the issue description.

**Comment by flar** [comment]
> @flar : you're right, the scale isn't applied to the translation in the matrix (`tx`), it's applied to the original translation/offset (`src->fX * sx`). Anyway, our snapping is still problematic as the final `x` can be fractional even if we forced `tx` to be integral. I'll update the issue description.

I'm not sure what you mean by "the final `x`"? The point of snapping the matrix to an integral transform is not so that any given 'x' is an integer, but so that we ignore the sub-pixel translation of the transform and cache a single version of the picture or layer for any transform that differs only by translation. Without that code, if there is a translation animation going on then we will recache the picture or layer for every frame of the animation.

**Comment by flar** [comment]
Note that the caching code already ignores the whole part of the translation when it does its work. If an app draws the same picture or layer at 5, 5 and 10, 10 - the same cached result will be used.

if you remove the integer snapping then if we draw the layer at 5.2, 5.2 and then at 5.4, 5.4 (or even smaller differences which can happen during a moving animation) then it will have to be re-cached.

**Comment by liyuqian** [comment]
Such re-cache is avoided by https://github.com/flutter/engine/pull/17712/files#diff-f4d3a0d54ee4a1dc4f68020696cd28c4R18

Basically, we're still drawing the raster cache with integral offsets, and ignoring the fractional translation for the matrix in the raster cache key. We'll no longer modify the matrix as it won't guarantee integral offsets. Only the final rect round-out guarantees that...

**Comment by flar** [comment]
Ah, I think I see what is happening. The title of this issue is that the raster cache's integer snapping is broken and the fix is to remove the integer snapping, but those aren't really apples to apples.

We are keeping the inherent integer snapping in the cache by virtue of those lines in the cache key constructor, but we are removing all of the snapping logic from the layers themselves. I support that move (and coincidentally I had the same thought recently when I was working on opacity_layer's use of the cache...)

**Comment by liyuqian** [comment]
Reopen due to the revert.

**Comment by liyuqian** [comment]
Actually, having a fractional scale factor and a fractional final offset is Ok. Both [RasterCacheResult::draw][1] and [Rasterize][2] uses `RasterCache::GetDeviceBounds` to round out the fractional rects. As long as the scale factor and the picture is the same, such rounded-out bounds should be the same.

The unit test triggered the assert because it's calling `SkCanvas::translate` with an integral offset, and forget to update the `ctm`. (See [this line of code](https://github.com/flutter/engine/blob/8abd9e2cac14ff8f40fac588945844d27b49bd82/flow/raster_cache_unittests.cc#L152).) One might think such update is unnecessary for an integral offset. But `SkCanvas::translate` is doing `preTranslate` to the matrix instead of `postTranslate` (see [this line][3]). So the fractional scale of `SkMatrix` will be applied to the translation offset. If there's an integral x translation of 3, and the matrix has a fractional x scale of 1.5, they would result in final x translation of 4.5. See https://github.com/flutter/engine/pull/17790 for how it can be fixed.

Therefore, our integral snapping seems to be working as intended for now.

[1]: https://github.com/flutter/engine/blob/88e454bf1c5463d23b79bf284dc030faea39f919/flow/raster_cache.cc#L28
[2]: https://github.com/flutter/engine/blob/88e454bf1c5463d23b79bf284dc030faea39f919/flow/raster_cache.cc#L97
[3]: https://github.com/google/skia/blob/36a3e014e10850ff692e5fd65e8e4d0354505916/src/core/SkCanvas.cpp#L1451
