### ISSUE TITLE
[cocoon] Simplify tests by sharing common codes in a util_test file

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#53280]
Some examples: `branch_stream` function exist in multiple files, such as https://github.com/flutter/cocoon/blob/master/app_dart/test/request_handlers/refresh_cirrus_status_test.dart#L39

Also `MockGitHub` class (https://github.com/flutter/cocoon/blob/master/app_dart/test/request_handlers/refresh_cirrus_status_test.dart#L233), etc.

**Comment by godofredoc** [comment]
I believe we can deprecate that API

**Comment by keyonghan** [comment]
This is obsolete.
