### ISSUE TITLE
[Image Picker] Image picker public API should avoid using static methods.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#53283]
The image picker plugin's public APIs are all static methods for some historical reasons. 
In my opinion, it is worth to make the breaking change, to update the plugin to use to instance methods for a long term solution, which can make the plugin easier to mock and test.
Could potentially be a 1.0.0 change?

**Comment by amirh** [comment]
Sounds reasonable, can we make this a 2 step change, first add the new API while keeping the old one and marking it deprecated, and then after enough of the ecosystem migrating making the breaking change for removing the deprecated API

**Comment by ditman** [comment]
This is the return type that I think would be better than `String` so we can support the plugin in web, without dart:io:

```
class PickedFile {
    final String path;
    final Uint8List _bytes;

    String readAsStringSync();
    Uint8List readAsBytesSync();
    Stream<List<int>> openRead();

    PickedFile({this.path, this.bytes});
}
```

It's just a read-only file container that can be initialized either by just the path (mobile) or the path + bytes (web), and then it can be used to read back the bytes (as string, as binary, or as a Stream for larger files) and the path.

This way the "old" programs have a very easy migration path (they just need to pick a file and get its `.path` to preserve the old behavior, but newer apps can start to use the read methods.

**Comment by ditman** [comment]
Note: it seems [Android 11's scoped storage changes](https://developer.android.com/preview/privacy/storage) might affect the return type of the plugin. @cyanglaz, do you think the class I proposed above is going to be valid, or do we need to revisit this after the scoped storage issues are fixed?

**Comment by ditman** [comment]
Android 11 is solved, moving forward with this.

**Comment by ditman** [comment]
The PR I linked above makes the Image Picker API not use static methods, and adds the `PickedFile` data type. The main difference with the original design is that the read methods are now `async`, so they can be implemented in web efficiently.

**Comment by ditman** [comment]
I've published a PR with a new API for the image_picker: using the new return type proposed above:

https://github.com/flutter/plugins/pull/2791

I have an upcoming review (dependent on the one above) that will make the core plugin *not* have a static API, and instead require users to create a plugin instance.

(I also have a web version which was my original goal ;) )

**Comment by ditman** [comment]
The new API has been released and published. Closing.
