### ISSUE TITLE
Add scrollController.calculateExtents() so we can force a list to re-calculate it's extents

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#53305]
There is currently no way to indicate to the ScrollController, that it's content is stale, and that it should re-calculate it's extents.

This is necessary as I'm building a scrollbar, that relies on maxExtents to control a list. When the contents of the list change, maxExtents does not update, until a scrollEvent has been triggered. 

You can hack around this, by using antimateTo, and  moving it like 1px, but if the list is too short, this does not work since the list can not be scrolled. 

**Can you provide an API on ScrollController for triggering this calculation?**

**Comment by alejandroaap** [comment]
Is it in the roadmap to solve this problem? I have the same problem and the user experience has been seriously affected.

**Comment by Piinks** [comment]
ScrollController likely would not be the best place to do this, in fact it may cause issues given a scroll controller can have multiple positions attached.

> When the contents of the list change, maxExtents does not update, until a scrollEvent has been triggered.

Have you tried using a ScrollMetricsNotification? This is the case it will notify for.

**Comment by Piinks** [comment]
Alternatively, you can also override SliverChildDelegate.estimateMaxScrollOffset.
