### ISSUE TITLE
auto-assign bot should not assign WIP PRs

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#53316]
auto-assign seems to ignore the "work in progress (WIP)" label and still assigns PRs. It should not do that.

**Comment by jmagman** [comment]
https://github.com/flutter/engine/blob/master/.github/auto_assign.yml

**Comment by yjbanov** [comment]
Thanks for the links! So is it a matter of adding "WIP" to the list of `skipKeywords`? Will it unskip after the label is removed?

**Comment by jmagman** [comment]
No idea, I had never heard of that bot before you told us about it!  I don't know what they mean by "keyword" in that doc. Will that skip a code review with the description "This wipes out the cache"? 🤷‍♀

**Comment by jmagman** [comment]
Looks like @gaaclarke added it.

**Comment by yjbanov** [comment]
I have not experienced this issue and/or is hasn't been problematic, so I'm closing it.
