### ISSUE TITLE
Error 105 received from application: Isolate must be runnable

### ISSUE THREAD

**Issue by dingzuhua** [flutter/flutter#53323]
Well, my project had been running normally on flutter 1.9.1, and then yesterday I upgraded flutter to 1.12.13, and the project was stuck on the startup page. After recompiling, I reported this error:
Error 105 received from application: Isolate must be runnable
Hot reload received invalid response: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///Users/dingzuhua/Library/Developer/CoreSimulator/Devices/96BAA6ED-DFF3-4399-8D77-CD0273638570/data/Containers/Data/Application/0781332F-60AD-4B1A-B9C2-6E6EB4DC4AAB/tmp/ecareDGhvDh/ecare/lib/main.dart.incremental.dill, packagesUri: file:///Users/dingzuhua/Library/Developer/CoreSimulator/Devices/96BAA6ED-DFF3-4399-8D77-CD0273638570/data/Containers/Data/Application/0781332F-60AD-4B1A-B9C2-6E6EB4DC4AAB/tmp/ecareDGhvDh/ecare/.packages, isolateId: isolates/1272176079571631}}, details: Isolate must be runnable before this request is made.}}

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected device (1 available)

**Comment by dingzuhua** [comment]
Restart, and this will be reported:
Error 105 received from application: Isolate must be runnable
Restarted application in 6,823ms.
[VERBOSE-2:shell.cc(199)] Dart Error: Unhandled exception:
NoSuchMethodError: No top-level getter '' declared.
Receiver: top-level
Tried calling:
#0      NoSuchMethodError._throwNew  (dart:core-patch/errors_patch.dart:202:5)
[VERBOSE-2:dart_isolate.cc(461)] Could not resolve main entrypoint function.
[VERBOSE-2:engine.cc(205)] Could not run the isolate.
[VERBOSE-2:engine.cc(137)] Engine not prepare and launch isolate.
Error -32000 received from application: Could not run configuration in engine.

**Comment by dingzuhua** [comment]
The code has not changed since the flutter upgrade

**Comment by dingzuhua** [comment]
I also tried flutter clean and then restitched run, and the results were the same

**Comment by dingzuhua** [comment]
is ios,object-c

**Comment by TahaTesser** [comment]
Hi @dingzuhua 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you
