### ISSUE TITLE
Flutter error: "Downloaded executables cannot execute on host."

### ISSUE THREAD

**Issue by xyz970** [flutter/flutter#53328]
![Screenshot from 2020-03-27 12-11-37](https://user-images.githubusercontent.com/53963692/77612591-1f88fd80-6f5b-11ea-9793-3eb6312b1ae8.png)

My flutter doctor show this error.. that error tell me to install lib32stdc++6.. I search in synaptic package manager.. And i need know what version are need to install.. Please help me..
Sorry for my bad english

**Comment by TahaTesser** [comment]
Hi @xyz970 
If i am not mistaken, you can supply run this command and you're good to go [from this comment](https://github.com/flutter/flutter/issues/6207#issuecomment-251703828)
`sudo apt-get install lib32stdc++6`
Thank you

**Comment by xyz970** [comment]
![Screenshot from 2020-03-27 20-03-32](https://user-images.githubusercontent.com/53963692/77649509-90043e80-6f9c-11ea-8e54-75e7d5023bcd.png)

still cannot detect them... Please help

**Comment by TahaTesser** [comment]
Hi @xyz970 
Have you tried restarting your computer?
Thank you

**Comment by xyz970** [comment]
> Hi @xyz970
> Have you tried restarting your computer?
> Thank you

I have... and still like that

**Comment by jonahwilliams** [comment]
Removing from tools designation since this is a documentation issue

**Comment by xyz970** [comment]
the problem is solved now thanks for help everyone^_^
