### ISSUE TITLE
Flutter Android App hangs, while typing dot(.) in TextField

### ISSUE THREAD

**Issue by venkata-subbarao** [flutter/flutter#53325]
I have a very simple Flutter App for Android with following class. App hangs, as soon as I type a dot character followed by text in the TextField.

e.g.: venkata.

    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);
    
      final String title;
    
      @override
      _MyHomePageState createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
      TextEditingController emailIdController = TextEditingController();
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextField(
                autofocus: false,
                keyboardType: TextInputType.emailAddress,
                decoration: InputDecoration(
                  prefixIcon: Icon(Icons.email),
                  hintText: "Email Address",
                  labelText: 'Email Address',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(50),
                  )),
                controller: emailIdController,
              ),
            )
          )
        );
      }
    }

I am using Samsung m10s Mobile with latest firmware. It is running Android version 9.0. For other installed Apps on this Mobile, this kind of issue is not seen. So, I am thinking that some issue in TextField usage or issue in Flutter SDK.

Here is the Flutter version info

    Flutter 1.15.22-pre.32 • channel master • https://github.com/flutter/flutter.git
    Framework • revision fd8b65e1bd (10 days ago) • 2020-03-15 23:26:01 -0400
    Engine • revision 3e02f3bec9
    Tools • Dart 2.8.0 (build 2.8.0-dev.14.0 eff5548a68)

The VS Code terminal starts printing errors continuously. Pasted below first few lines of errors. 

    D/ViewRootImpl@eb77dbe[MainActivity]( 1753): ViewPostIme pointer 0
    D/ViewRootImpl@eb77dbe[MainActivity]( 1753): ViewPostIme pointer 1
    D/InputMethodManager( 1753): SSI - flag : 0 Pid : 1753 view : com.example.sample
    D/InputMethodManager( 1753): prepareNavigationBarInfo() DecorView@5e90c72[MainActivity]
    D/InputMethodManager( 1753): getNavigationBarColor() -855310

Switching to stable channel has solved the issue.

**Comment by TahaTesser** [comment]
Hi @venkata-subbarao 
I wasn't able to reproduce your issue on Samsung device

### flutter doctor -v
```
[✓] Flutter (Channel master, v1.16.3-pre.43, on Mac OS X 10.15.4 19E266, locale
    en-GB)
    • Flutter version 1.16.3-pre.43 at /Users/taha/Code/flutter_master
    • Framework revision 86389be66e (12 hours ago), 2020-03-25 13:27:10 -0700
    • Engine revision dd102bf228
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 62f84880ef)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

Could you please test it again on latest master and provide your `flutter run --verbose`
Thank you

**Comment by venkata-subbarao** [comment]
Vladyslav, Issue is fixed in latest master.
