### ISSUE TITLE
Stack trace for a failed flutter drive test overflows my bash history

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#5332]
I can't see what actually caused the test to fail.

**Comment by abarth** [comment]
Can you email us the stack?  We have some code to trim down the stacks and having an example would help us see what else needs to be trimmed.

/cc @Hixie

**Comment by abarth** [comment]
Looks like `flutter drive` is missing the stack elider.  The stack has lots of `dart:async/zone.dart`

**Comment by Hixie** [comment]
This is a @yjbanov thing, I think. We should probably move it to using the foundation/assertions.dart APIs for handling errors.

**Comment by yjbanov** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/4261
