### ISSUE TITLE
felt test leaks chromedriver; pollutes console output

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#53320]
I just ran `felt test test/text/measurement_test.dart` and noticed garbage printed to my console long after I ran that command. Example:

```
$ [1585109052.063][SEVERE]: Timed out receiving message from renderer: 0.100
[1585109072.779][SEVERE]: Timed out receiving message from renderer: 0.100
```

I checked my list of processes and found the `chromedriver` process still running. I suspect that's the source of the extra logging.

My engine checkout is currently synced to https://github.com/flutter/engine/commit/04182cde5db00114e55300ae0196a87b24ba1d7e

## Second problem

Aside from the fact that I see dangling chromedriver processes, I actually did not expect chromedriver to be involved at all, since I'm not running an integration test in this case.

/cc @nturgut

**Comment by yjbanov** [comment]
Ok, I see how the second problem happens. `felt test` ignores the fact that I'm asking it to run a single test at all. Here's the full log:

```
felt test test/text/measurement_test.dart 
INFO: chrome version in use Google Chrome 80.0.3987.132 

downloading file from https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
INFO: Driver started
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Running "flutter pub get" in regular_integration_tests...           0.4s
INFO: In project Directory: '/home/yjbanov/code/flutter/engine/src/flutter/e2etests/web/regular_integration_tests' 2 tests to run.
Starting application: test_driver/image_loading_e2e.dart
Launching test_driver/image_loading_e2e.dart on Web Server in profile mode...
Compiling test_driver/image_loading_e2e.dart for the Web...        16.5s
test_driver/image_loading_e2e.dart is being served at http://localhost:38267
Application finished.
Waiting for connection from Dart debug extension at http://localhost:38267
[1585185149.096][SEVERE]: Timed out receiving message from renderer: 0.100
Stopping application instance.
Starting application: test_driver/text_editing_e2e.dart
Launching test_driver/text_editing_e2e.dart on Web Server in profile mode...
Compiling test_driver/text_editing_e2e.dart for the Web...         17.6s
test_driver/text_editing_e2e.dart is being served at http://localhost:36575
Application finished.
Waiting for connection from Dart debug extension at http://localhost:36575
[1585185170.062][SEVERE]: Timed out receiving message from renderer: 0.100
result pass
Stopping application instance.
INFO: 2 tests run. 2 passed and 0 failed.
```

Notice that even though I'm asking it to run only `test/text/measurement_test.dart`, it still runs `test_driver/image_loading_e2e.dart`, etc.

**Comment by nturgut** [comment]
I think both problems are the same. The chromedriver shouldn't have started.

BTW, since we are only closing the opened processes when the tests are finished, if you stop the tests it won't cleanup temporary files or it won't close child processes.

**Comment by nturgut** [comment]
Ah I was wrong, I wasn't cleaning up chrome driver if the tests exits with an error. All fixes and more are included in PR: https://github.com/flutter/engine/pull/17339
