### ISSUE TITLE
flutter module run error with   "enable-android-embedding-v2": false

### ISSUE THREAD

**Issue by bineanzhou** [flutter/flutter#53333]
flutter config --no-enable-android-embedding-v2

flutter-samples/add_to_app/flutter_module_using_plugin/.android/Flutter/src/main/java/io/flutter/facade/Flutter.java:98: 错误: 不兼容的类型: FlutterPluginRegistry无法转换为FlutterEngine
        GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());

**Comment by VladyslavBondarenko** [comment]
Hi @bineanzhou 
did you follow https://flutter.dev/docs/development/androidx-migration#add-to-app?
does https://github.com/flutter/flutter/issues/50457#issuecomment-584198839 help you?
could you attach your `flutter doctor -v`?

**Comment by WangPeng5247** [comment]
I also encountered this problem, I used android studio to create a new project and it runs normally, then File-> New Module-> Flutter Module After creating the module, it is displayed directly
![2841585217144_ pic](https://user-images.githubusercontent.com/10292799/77634845-9be80480-6f8c-11ea-9e38-45110d92d544.jpg)
![2851585217162_ pic](https://user-images.githubusercontent.com/10292799/77634848-9db1c800-6f8c-11ea-88d7-fb0328dd9e27.jpg)
![2861585217285_ pic_hd](https://user-images.githubusercontent.com/10292799/77634947-c1750e00-6f8c-11ea-9b8f-bf5b8102c0a0.jpg)

**Comment by VladyslavBondarenko** [comment]
@WangPeng5247 
Please don't post screenshots of text, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it

**Comment by bineanzhou** [comment]
The plugin `qad` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0

**I need V1 embedding**

**Comment by bineanzhou** [comment]
```
✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/zhoubin/work/flutter/sdk/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


```

**Comment by bineanzhou** [comment]
AndroidEmbeddingVersion getEmbeddingVersion() {
    if (isModule) {
      // A module type's Android project is used in add-to-app scenarios and
      // only supports the V2 embedding.
      return AndroidEmbeddingVersion.v2;
    }
。。。


flutter sdk Why do you do this

**Comment by bineanzhou** [comment]
// A module type's Android project is used in add-to-app scenarios and
// only supports the V2 embedding.

why???

**Comment by jmagman** [comment]
@blasten you want to address this question?  Might be worth a sentence in the documentation.

**Comment by blasten** [comment]
This check was added in https://github.com/flutter/flutter/pull/44499 by @xster who can provide a bit more context on why this was needed.

**Comment by xster** [comment]
@bineanzhou we might need some more details on what you're asking specifically. 

Though as general context, the older experimental add-to-app process is no longer publicly supported and also not part of the flutter tool in v1.12. 

There are 2 possible scenarios you're in:

If you're using Flutter version <1.12, it doesn't support neither the v2 Android engine APIs nor v2 plugins. So if you were using the experimental add-to-app process from the wiki from before v1.12, you can continue to run your project as before. 

If you're using Flutter version >1.12, then:

If you're using a full-Flutter app, you can either use the v1 Android engine with v1 plugins or use a v2 Android engine with v1 or v2 plugins. 

If you're using add-to-app (which I think is your case), you can only use v2 Android engine with v1 or v2 plugins. v1 Android engine (including `io/flutter/facade/Flutter.java`) is not part of Flutter v1.12 and is not supported. See [flutter.dev/go/android-project-migration](flutter.dev/go/android-project-migration) if you had an experimental add-to-app project to upgrade to Flutter v1.12. 

If you can't migrate for any reason, you should continue to use v1.9.

**Comment by jmagman** [comment]
Thanks for the answer, @xster.
Closing.
