### ISSUE TITLE
flutter http

### ISSUE THREAD

**Issue by kardotinambunan12** [flutter/flutter#53330]
I want to ask "can you give me something when I experience errors like the following? thank you

type(httpexception=>null is not a subtype of type dynamic => dynamic

**Comment by TahaTesser** [comment]
Hi @kardotinambunan12 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @kardotinambunan12 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
