### ISSUE TITLE
flutter libraries

### ISSUE THREAD

**Issue by bardoun7894** [flutter/flutter#53332]
yesterday  i have problem in sharedPreferences  problem build and i think is the only problem 
but i have some problems in other libraries is it a issue of flutter after updating xcode  thanks 
this  is the screenshot !
![2020-03-26](https://user-images.githubusercontent.com/16933477/77620701-3b7ca700-6f3b-11ea-9aeb-427a7d1b522b.png)

**Comment by TahaTesser** [comment]
Hi @bardoun7894 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @bardoun7894 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
