### ISSUE TITLE
flutter running flutter doctor after Linux configuration shows Channel stable, v0.0.0-unknown, on Linux, locale en_US.UTF-8

### ISSUE THREAD

**Issue by kingkadienm** [flutter/flutter#53339]
The version I downloaded on the flutter official website is https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.9.1+hotfix.2-stable.tar.xz and then deployed to linux After configuring the environment variables, After running flutter doctor
`[yun@179-104 root]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v0.0.0-unknown, on Linux, locale zh_CN.UTF-8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
[yun@179-104 root]$`

**Comment by VladyslavBondarenko** [comment]
Hi @kingkadienm 
Can you see the same if you try to delete flutter, unzip it and run `flutter doctor` again?
Why are you using `v1.9.1+hotfix.2`? note that current stable version is `v1.12.13+hotfix.8`
You can also try to repair it with git https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by TahaTesser** [comment]
Hi @kingkadienm 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
