### ISSUE TITLE
resolution-aware image assets Is not Working

### ISSUE THREAD

**Issue by majdjlassi** [flutter/flutter#53346]
I'am facing a trouble when i try to display icons for example `Image.asset("assets/icons/ic_privacy.png")` is always picking the icon from 1.0x/ directory 

Any help please! thanks in advance.

**flutter doctor**
![image](https://user-images.githubusercontent.com/19283930/77643947-8826a900-6f60-11ea-996e-984cdbadff46.png)
**assets directory hierarchy :**
![image](https://user-images.githubusercontent.com/19283930/77644020-ab515880-6f60-11ea-8589-7f76cd6da35d.png)
**pubspec.yaml :**
![image](https://user-images.githubusercontent.com/19283930/77644052-bb693800-6f60-11ea-93fa-dd460575588c.png)

**Comment by VladyslavBondarenko** [comment]
Hi @majdjlassi 
with what devices do you test?
When I run with Android emulator 1440x2880 560dpi I have 3.0x image, with Android tablet emulator 800x1280 mdpi I have original image (with stable v1.12.13+hotfix.8).

And please refrain from posting screenshots of text, if not necessary, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by TahaTesser** [comment]
Hi @majdjlassi 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
