### ISSUE TITLE
[web]: Divider() is not showing up.

### ISSUE THREAD

**Issue by kechankrisna** [flutter/flutter#53347]
Divider() is not showing up in flutter for web, I tested in Lisview, ListView.separated, Column and alone, all tests are failed.

**Comment by VladyslavBondarenko** [comment]
Hi @kechankrisna 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/46339,
Comment there more detailed about your case if it's different.
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
