### ISSUE TITLE
[web][crash] Getting error in javascript to parse arguments sent during Navigation.push [ Converting object to an encodable object failed:  ]

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#53348]
When I try to push a new route with some complex arguments object , i get error only when running as a web app . On running it as a normal app , it works fine. :/ 

```
NavigationService.instance.pushNamed(
      "/myRoute",
      arguments: OtpScreenArgs(
        mobileNumber: mobile,
        categoryId: 23,
        onValidated: (
            {@required String sessionToken,
            @required String validationToken}) async {
          FlutterLogger.instance.d(
              'Validating OTP :  Vendor input =  ${user.toString()} , sessionToken = $sessionToken , validation token = $validationToken');
          CreditScoreNativeBridge.instance
              .initCartReview(
              validationToken: validationToken,
              sessionToken: sessionToken,
              vendorInput: user)
              .then((e) {
              NavigationService.instance.popNativeAware();
          });
        },
      ),
    );
```

This is the error i get when the above statement executes : 

```
dart_sdk.js:5355 Uncaught (in promise) Error: Converting object to an encodable object failed: Instance of 'OtpScreenArgs'
    at Object.throw_ [as throw] (dart_sdk.js:4070)
    at convert._JsonStringStringifier.new.writeObject (dart_sdk.js:49453)
    at Function.printOn (dart_sdk.js:49685)
    at Function.stringify (dart_sdk.js:49675)
    at JsonEncoder.convert (dart_sdk.js:49108)
    at JsonCodec.encode (dart_sdk.js:49053)
    at app.WidgetsApp.new.generateRoute (core_router.dart:23)
    at app._WidgetsAppState.new.[_onGenerateRoute] (app.dart:999)
    at navigator$.NavigatorState.new.[_routeNamed] (navigator.dart:2169)
    at navigator$.NavigatorState.new.pushNamed (navigator.dart:2221)
    at pushNamed (navigation_service.dart:30)
    at pushNamed.next (<anonymous>)
    at runBody (dart_sdk.js:41566)
    at Object._async [as async] (dart_sdk.js:41594)
    at navigation_service.NavigationService.__.pushNamed (navigation_service.dart:22)
    at form_submitter.LandingFormSubmitter.new.submitForm (form_submitter.dart:47)
    at ink_well.InkWell.new.<anonymous> (landing_screen_form.dart:153)
    at _InkResponseState.new.[_handleTap] (ink_well.dart:779)
    at ink_well.dart:862
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:182)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:486)
    at tap.TapGestureRecognizer.new.[_checkUp] (tap.dart:264)
    at tap.TapGestureRecognizer.new.acceptGesture (tap.dart:236)
    at arena.GestureArenaManager.new.sweep (arena.dart:156)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:222)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:198)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (binding.dart:156)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:102)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:86)
    at _engine.PointerBinding.__.[_onPointerData] (dart_sdk.js:142635)
    at dart_sdk.js:142972
    at dart_sdk.js:142937
    at HTMLElement.<anonymous> (dart_sdk.js:142715)
```

This is my NavigationService class : 

```
class NavigationService {
  static final GlobalKey<NavigatorState> _navigatorKey =new GlobalKey<NavigatorState>();

  NavigationService._();

  static NavigationService _instance;

  static NavigationService get instance {
    if (_instance == null) {
      _instance = NavigationService._();
    }
    return _instance;
  }

  static GlobalKey<NavigatorState> get navigatorKey => _navigatorKey;

  Future<void> pushNamed(String routeName,
      {dynamic arguments, bool fromNative = false}) async {
    NucleiNavigator.instance.push(routeName, fromNative: fromNative);
    if (_navigatorKey.currentState == null) {
      WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
        _navigatorKey.currentState.pushNamed(routeName, arguments: arguments);
      });
    } else {
      await _navigatorKey.currentState.pushNamed(
          routeName, arguments: arguments);
    }
  }
}
```

**Comment by VladyslavBondarenko** [comment]
Hi @nateshmbhat 
could you provide your `flutter doctor -v`?

**Comment by nateshmbhat** [comment]
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.15.17 at /Users/nateshmbhat/Apps/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nateshmbhat/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • GM1901     • 192.168.0.107:5555 • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome             • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server         • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by VladyslavBondarenko** [comment]
@nateshmbhat 
Also, to better address the issue, would be helpful
if you could post a complete minimal code sample to reproduce the problem
Thank you

**Comment by nateshmbhat** [comment]
Ok here it is : 

```
void submitForm(VendorInput user) {
    trimAllFields(user);
    String mobile = user.inputFields
        .where((field) => field.id == FieldId.MOBILE)
        .toList()
        .first
        .inputValue;

    NavigationService.instance.pushNamed(
      CoreRoutes.otp,
      arguments: OtpScreenArgs(
        mobileNumber: mobile,
        categoryId: 23,
        onValidated: ({@required String sessionToken, @required String validationToken}) async {
          FlutterLogger.instance.d(
              'Validating OTP :  Vendor input =  ${user.toString()} , sessionToken = $sessionToken , validation token = $validationToken');
          CreditScoreNativeBridge.instance
              .initCartReview(
              validationToken: validationToken,
              sessionToken: sessionToken,
              vendorInput: user)
              .then((e) {
              NavigationService.instance.popNativeAware();
          });
        },
      ),
    );
  }
```

This is the OtpScreenArgs class : 

```
class OtpScreenArgs {
  final String mobileNumber;
  final int categoryId;

  final Function(
      {@required String sessionToken,
      @required String validationToken}) onValidated;

  OtpScreenArgs(
      {@required this.mobileNumber,
      @required this.categoryId,
      @required this.onValidated});
}
```

Now , here's the NavigationService code that actually pushes the Route :

```
class NavigationService {
  static final GlobalKey<NavigatorState> _navigatorKey =
  new GlobalKey<NavigatorState>();

  NavigationService._();

  static NavigationService _instance;

  static NavigationService get instance {
    if (_instance == null) {
      _instance = NavigationService._();
    }
    return _instance;
  }

  static GlobalKey<NavigatorState> get navigatorKey => _navigatorKey;

  Future<void> pushNamed(String routeName,
      {dynamic arguments, bool fromNative = false}) async {
    NucleiNavigator.instance.push(routeName, fromNative: fromNative);
    if (_navigatorKey.currentState == null) {
      WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
        _navigatorKey.currentState.pushNamed(routeName, arguments: arguments);
      });
    } else {
      await _navigatorKey.currentState.pushNamed(
          routeName, arguments: arguments);
    }
  }
}

```

**Comment by nateshmbhat** [comment]
The error occurs when sending the arguments object to the NavigationService.push method.

**Comment by nateshmbhat** [comment]
@VladyslavBondarenko is it not appropriate for `severe:crash` label ? . This is a crashing error which fails to push the new screen.

**Comment by mdebbar** [comment]
@nateshmbhat there are still missing pieces in the code you provided. The stack trace refers to `WidgetsApp.onGenerateRoute`. Could you share what you are passing as `onGenerateRoute` callback to `WidgetsApp`?

It looks like somewhere in the code you are trying to json-encode an `OtpScreenArgs` instance, and that's throwing an exception. I'm still puzzled to why this is only failing on web. It should be failing in native too.

**Comment by nateshmbhat** [comment]
Aaaaaahhhh , I see why this might be happening : I am doing a `json.encode` on the settings.arguments which might be causing the issue. But why doesn't it happen only in the web app ? 🤔 

My `generateRoute` method looks like this : 

static Route<dynamic> generateRoute(RouteSettings settings) {

    FlutterLogger.instance.d("Got Route : ${settings.name} , args : ${json.encode(settings.arguments)}");

    switch (settings.name) {
      case CoreRoutes.baseLoading :
        FlutterLogger.instance.i("Opening Base Loading Screen");
        return PageRouteBuilder(
          pageBuilder: (context, animation, secondaryAnimation) =>
              BaseLoadingScreen(),
          transitionsBuilder: (context, animation, secondaryAnimation, child) {
            return child;
          },
        );

      case CoreRoutes.otp:
        var data = settings.arguments as OtpScreenArgs;
        return MaterialPageRoute(
          builder: (_) => NetworkAwareWidget(
            onConnection: OtpScreen(
              categoryId: data.categoryId,
              mobileNumber: data.mobileNumber,
              onValidated: data.onValidated,
            ),
          ),
        );
    }
  }

**Comment by nateshmbhat** [comment]
That was indeed the issue : removing the json.encode fixed the issue.

**Comment by nateshmbhat** [comment]
Thanks for your suggestion :D

**Comment by nateshmbhat** [comment]
But please do intestigate about why its giving error in only web.
