### ISSUE TITLE
animated_placeholder_perf average_frame_rasterizer_time_millis slowly climbing

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53352]
It's difficult to pinpoint a commit; the actual red bars correspond to things in tooling which shouldn't have an impact.

![Screen Shot 2020-03-26 at 8 39 13 AM](https://user-images.githubusercontent.com/1435716/77665737-4e907680-6f3d-11ea-8157-03e5ea6291a7.png)

Not filing this as a TODAY issue, because it's still usually within bounds.

cc @liyuqian

**Comment by liyuqian** [comment]
Also CC the author of that benchmark @dnfield . A `git bisect` which tests a single commit version many times in every bisection step might be needed if it's unclear which commit causes the regression.

**Comment by dnfield** [comment]
It looks like it's just noisy to me.  Probably fine to rebaseline.

**Comment by kf6gpe** [comment]
Thanks! Rebaselined.
