### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by r4v3r23** [flutter/flutter#53355]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Android Studio (version 3.6)

--------------

flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
/home/USER/Android/Sdk/tools/bin/sdkmanager --update

--------------

I have searched this issue all through github & other sites and still running into this issue. I reinstalled Android Studio & flutter, manually downloaded Tools from Android site but still get an out-of-date error. Flutter is nonstop issues

**Comment by sandy9808** [comment]
yes same problem this flutter is shit..

**Comment by VladyslavBondarenko** [comment]
Hi @r4v3r23 
Please follow up on https://github.com/flutter/flutter/issues/51712,
see https://github.com/flutter/flutter/issues/51712#issuecomment-600394582
I'm closing the current one as duplicate.
If this didn't resolve the problem please write in the comments and I will reopen it.
Thank you

**Comment by r4v3r23** [comment]
> Hi @r4v3r23
> Please follow up on #51712,
> see [#51712 (comment)](https://github.com/flutter/flutter/issues/51712#issuecomment-600394582)
> I'm closing the current one as duplicate.
> If this didn't resolve the problem please write in the comments and I will reopen it.
> Thank you

what version can i upgrade to with a fix?
