### ISSUE TITLE
The `flutter version` command should be deprecated

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#53364]
This command doesn't have the UX users would expect, can lead the user to get into an unexpected git state, and is difficult to implement. It should be deprecated.

Please link any related issues here.

**Comment by NicolasDionB** [comment]
I'm not sure I agree. We are developping our app using the web version, which is not yet available in the stable version. We then have to switch channel on beta or master. From one version to the other, there are often differences, sometimes breaking changes.

If we can't specify which version we want, it's getting harder to maintain. In such a scenario, the CI could potentially get a more recent version than the one we tested on. It's really hard to maintain a working flow with good quality if we can't use a specific version.

If it's not the actual `flutter version` command, there has to remain a way to use a specific version.

**Comment by obshksw** [comment]
To add to this, it also happened in the past that the Continuous Integration build just failed at a later stage when not specifying a specific SDK version, right before release. 

Nothing better than an example, so here's what happened:

I was working locally on flutter 1.14.3 ( not sure which version it was, but let's say it was this :) ).

Then I finish my work and update the build on the CI for the QA, but at that time the CI builds on 1.4.4 because there was an SDK update since then, which still works but not exactly the same version I have tested my stuff in.

Then the QA approves, now I update the build on staging to prepare for release and now there's a new version 1.4.5 out, but that one breaks one of the dependencies. So now my CI and build is broken, so I have to reupdate everything from the start with a different version for the breaking dependency and go through all the steps again before release. That's unviable.

If there's a better way to do this, I'm all ears though! Because I have no idea how I could achieve this without using `flutter version X`.

**Comment by christopherfujino** [comment]
> If we can't specify which version we want, it's getting harder to maintain. In such a scenario, the CI could potentially get a more recent version than the one we tested on.

This is a fair point, about being able check out a specific version on ci.

As for actual day to day use, I will say that long-term we should have a more robust system of release distribution and local version management. In the short term, versions can be navigated directly using git, either `git checkout 1.17.0` (which is what `flutter version 1.17.0` does, but has the drawback of leaving the HEAD detached from its release branch) or `git reset --hard 1.17.0` (which would leave the user on the current branch, but will fail if the tag isn't on the current branch).

**Comment by lesnitsky** [comment]
seems like some efforts have been already invested, since I can see `The "version" command is deprecated and will be removed in a future version of Flutter.` message. Since this is a "destructive" action, what's a proposed alternative?

**Comment by christopherfujino** [comment]
> seems like some efforts have been already invested, since I can see `The "version" command is deprecated and will be removed in a future version of Flutter.` message. Since this is a "destructive" action, what's a proposed alternative?

To (for example) use version 1.17.0, do either:
- `git checkout 1.17.0` (which is what `flutter version` does today, but will leave you in a detached head state and on an unknown branch/channel)
- `git reset --hard 1.17.0` (which will preserve the current branch, but will fail if the tag does not exist on the current branch).

**Comment by rockgecko-development** [comment]
I had the same issue as @obshksw today. Broken CI after flutter 1.20 went to stable yesterday.
I updated my CI install script to use `flutter version v1.17.5`, which is what the developer docs say to do here: https://flutter.dev/docs/development/tools/sdk/upgrading#selecting-a-specific-version

Install script:
```
git clone -b stable https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH

flutter channel stable
flutter version v1.17.5

flutter doctor
```

This works, resolves my issue. But I see the deprecation warning (which led me here). And then I see:
>If you are using the command to return to a previously installed SDK version consider using the "flutter downgrade" command instead.
I'm pretty `flutter downgrade` won't work on this CI environment, as no previous version was ever installed (it's usually a clean VM each time, I'm using appcenter fyi)

**Comment by christopherfujino** [comment]
> I had the same issue as @obshksw today. Broken CI after flutter 1.20 went to stable yesterday.
> I updated my CI install script to use `flutter version v1.17.5`, which is what the developer docs say to do here: https://flutter.dev/docs/development/tools/sdk/upgrading#selecting-a-specific-version
> 
> Install script:
> 
> ```
> git clone -b stable https://github.com/flutter/flutter.git
> export PATH=`pwd`/flutter/bin:$PATH
> 
> flutter channel stable
> flutter version v1.17.5
> 
> flutter doctor
> ```
> 
> This works, resolves my issue. But I see the deprecation warning (which led me here). And then I see:
> 
> > If you are using the command to return to a previously installed SDK version consider using the "flutter downgrade" command instead.
> 
> I'm pretty sure `flutter downgrade` won't work on this CI environment, as no previous version was ever installed (it's usually a clean VM each time, I'm using appcenter fyi).
> If `flutter version` command is removed, please provide an equivalent replacement command (and update the developer docs to mention the new command, and also the `flutter downgrade` command).
> 
> Perhaps I can change my install script to download only the specific tag I want:
> 
> ```
> git clone --depth 1 --branch 1.17.5 https://github.com/flutter/flutter.git
> export PATH=`pwd`/flutter/bin:$PATH
> flutter doctor
> ```
> 
> and relying only on `flutter doctor` to build the tools
> 
> Update: this seems to work fine, it does mention "Channel unknown" in the doctor output, but otherwise all good (using `flutter version` also results in "Channel unknown" anyway). It's probably faster than downloading the entire history for the whole repo too. Perhaps this should be the recommended approach for CI environments?

Note that doing shallow clones may break certain functionality (it used to break version resolution, though I think you'll be all right if you're exactly on a tag). However, TIL you can pass `--branch` a tag. I agree that we should update the documentation to recommend `--branch <tag>` on CI.

**Comment by mnexo** [comment]
I can only second the above requests for re-introducing `flutter version x.y.z` or at least providing an easy replacement.

We have a CI setup with the same build runner maintaining several systems, and it's a life saver to be able to easily switch between versions of the build tool chain, so we don't break CI for the other projects when we update one.

Having to perform loads of path extraction and git magic seems like a big step back.

**Comment by christopherfujino** [comment]
> I can only second the above requests for re-introducing `flutter version x.y.z` or at least providing an easy replacement.
> 
> We have a CI setup with the same build runner maintaining several systems, and it's a life saver to be able to easily switch between versions of the build tool chain, so we don't break CI for the other projects when we update one.
> 
> Having to perform loads of path extraction and git magic seems like a big step back.

No path extraction required, doing `git checkout x.y.z` should be sufficient on CI.

**Comment by christopherfujino** [comment]
Closing this issue as `flutter version` has been removed.

**Comment by illia-romanenko** [comment]
Using `git checkout` only possible in the Flutter folder - so while `flutter version` worked from any folder switching to `git checkout` will be more complicated as we'll have to find where Flutter is installed first (imagine CI, docker images, etc...). Before our dev instructions were very simple now they are more complicated and require more steps.

This decision to remove `flutter version` seems to be made without broader discussion and too quickly.

Tagging for visibility: @csells, @timsneath, @mariamhas

**Comment by christopherfujino** [comment]
> Using `git checkout` only possible in the Flutter folder - so while `flutter version` worked from any folder switching to `git checkout` will be more complicated as we'll have to find where Flutter is installed first (imagine CI, docker images, etc...). Before our dev instructions were very simple now they are more complicated and require more steps.

On CI/Docker images, `flutter version` would only work if you added to the flutter checkout to the your path first, right? So presumably you already know where it is.

**Comment by illia-romanenko** [comment]
When using docker, users start with the parent image (https://docs.docker.com/glossary/#parent-image) - in that case, all installation complexity along with flutter installation location is hidden, so using `flutter version` is easier in such cases.

**Comment by christopherfujino** [comment]
> When using docker, users start with the parent image (https://docs.docker.com/glossary/#parent-image) - in that case, all installation complexity along with flutter installation location is hidden, so using `flutter version` is easier in such cases.

That's a good point. In that case, you can do this: `(cd $(which flutter | xargs dirname) && git checkout $VERSION)`

**Comment by mnexo** [comment]
Sorry to sound like a broken record here, but it seems odd to me that you would find the above path-extract-git-checkout command a desirable UX for the end-users, who may not even know (or care) that the Flutter CLI tool uses git on the inside.

If the `(cd $(which flutter | xargs dirname) && git checkout $VERSION)` doesn't cause the problems mentioned in the [original description](https://github.com/flutter/flutter/issues/53364#issue-588648807) of why you are removing `flutter version`, then why not simply implement `flutter version` this way and leave git as a hidden implementation detail?
