### ISSUE TITLE
[flutter_tools] try_merge_upstream script should fail if there were upstream cirrus config changes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#53366]
If there were upstream updates to our cirrus config, we probably shouldn't bother running CI with the old config as it's a waste of resources and probably a waste of time for the engineer, who may end up troubleshooting a bug that's already been solved.

Currently blocked until https://github.com/flutter/flutter/pull/52840 lands.

**Comment by godofredoc** [comment]
Obsolete.
