### ISSUE TITLE
Getting errSecInternalComponent from codesign

### ISSUE THREAD

**Issue by tiabc** [flutter/flutter#53362]
Hi,

I'm trying to run a Flutter app on my iPhone using https://flutter.dev/docs/get-started/install/macos as a guide and getting an error: `errSecInternalComponent`. I've surfed all the Internet, tried locking and unlocking keychains, restarting xcode and the mac and nothing helps.

Full logs: https://gist.github.com/tiabc/09046ca003e8f6055454a167c474ee74

MacOS Catalina Version 10.15.3.
XCode Version 11.3.1.
Flutter dev channel (though changing a channel doesn't help).

```% flutter doctor
Downloading android-arm-profile/darwin-x64 tools...                 1.6s
Downloading android-arm-release/darwin-x64 tools...                 6.8s
Downloading android-arm64-profile/darwin-x64 tools...               1.5s
Downloading android-arm64-release/darwin-x64 tools...               1.1s
Downloading android-x64-profile/darwin-x64 tools...                 1.6s
Downloading android-x64-release/darwin-x64 tools...                 1.3s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.3 19D76, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)
```

Does it have anything to do with Flutter or the os? Anyway, I've spent the last 3 hours trying to fix this one way or another and what I got is that the error comes from this command:
```codesign --force --verbose --sign 1449BE6B6FDFBA26AE35FBCB4F98114A4737E5B3 --
/Users/tiabc/apps/my_app/build/ios/Debug-iphoneos/Runner.app/Frameworks/App.framework/App
               /Users/tiabc/apps/my_app/build/ios/Debug-iphoneos/Runner.app/Frameworks/App.framework/App: errSecInternalComponent
```
However, I haven't succeded solving it.

Any ideas? Do you need anything else to dig into the issue?

**Comment by jonahwilliams** [comment]
Maybe https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen can help?

This does not really seem flutter related

**Comment by tiabc** [comment]
Thank you for the attempt. No, I've tried everything there on the Internet including your link.
I'll close this as it seems unrelated to flutter.
