### ISSUE TITLE
Please add a date to the output of `flutter --version`

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5336]
I'm trying to ask our users to try a few feature. I'm trying to describe to them how they can check if they have a version of Flutter that includes the feature. I don't really have a user-friendly way to say "check if your flutter version is at version X or newer".

If we put the date of the last commit from their local flutter repo, then I could say "Check if your version of flutter is at or newer than YYYY-MM-DD"

Could we add the date of the last commit to the output of `flutter --version` ?

For example:

```
~/Code/flutter/examples/flutter_gallery[master] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision ec0f880032 (2 hours ago); engine revision 607d379c23
Last commit on framework: YYYY-MM-DD HH:MM:SS
```

(Of course, once we have a version numbering scheme, we can use that. Until then, a date probably works.)

**Comment by sethladd** [comment]
cc @pq @devoncarew

**Comment by pq** [comment]
@sethladd : as per a conversation with Devon, how about just replacing the "2 hours ago" with the actual date?  In that case the above example becomes:
```
~/Code/flutter/examples/flutter_gallery[master] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision ec0f880032 (2016-08-11 10:01:53); engine revision 607d379c23
````

**Comment by sethladd** [comment]
Yup, works for me. Thanks!

**Comment by Hixie** [comment]
I'd very much like to keep the "2 hours ago" thing. I don't mind if we also add a date.

The relative time is useful because when you're self-evaluating your status, it helps if you see "oh, I'm merely hours behind" vs "oh my, I'm months behind". A date doesn't give you the same visceral reaction.

**Comment by pq** [comment]
@Hixie : NP.  We can do both.  In that case, how about @sethladd 's original proposed format:
```
~/Code/flutter/examples/flutter_gallery[master] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision ec0f880032 (2 hours ago); engine revision 607d379c23
Last commit on framework: 2016-08-11 10:01:53
```

**Comment by Hixie** [comment]
Seem sfine. Don't forget the Dart SDK version will be there too.

**Comment by pq** [comment]
With Dart SDK version we've got:

```
[~/src/git/clones/flutter] (master) $ flutter --version
Flutter on channel master (from git@github.com:pq/flutter.git)
Framework revision 529c25caa8 (18 hours ago); engine revision 1493032690
Last commit on framework: 2016-08-11 16:51:46
Flutter tools using Dart version 1.19.0-dev.5.0
```
