### ISSUE TITLE
LUCI try jobs for release branches should use correct builder/recipes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#53371]
Here is an example of an engine hotfix PR: https://github.com/flutter/engine/pull/17306. It passed on Cirrus because the cirrus config is checked in to the PR, but [failed on LUCI pre-submit](https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/5552?) because the master builders were used, which used the latest version of the recipe, which had drifted since stable was cut.

We have hotfix builders that trigger based on a regex of the git refs https://github.com/flutter/infra/blob/master/config/main.star#L20, but when running presubmit, the ref is of the form "refs/pull/17306/head", i.e. it looks like any other PR against master and used the prod builder. Ideally, we should trigger the hotfix builder for PRs made against a hotfix branch (not sure if this is possible).

We should probably update the PR request handler in cocoon to specify the base_ref.

Action items:

- [x] Refactor `BRANCHES` dictionary in `main.star` to be an external JSON file `release_branches.json` and update relevant documentation. [done](https://github.com/flutter/infra/pull/335).
- [ ] Have cocoon read `release_branches.json`. We need to think about how this will be refreshed. It would be nice if there were some way to trigger cocoon manually to re-fetch it, so that when I update flutter/infra I don't have to wait for a cron job.
- [ ] Update [`github_webhook.dart`](https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/github_webhook.dart) to test each incoming PR's `"base"` (branch) against the current beta and stable release branches from `release_branches.json`.
- [ ] Replace [`//cocoon/app_dart/dev/branches.txt`](https://github.com/flutter/cocoon/blob/master/app_dart/dev/branches.txt) with `testing-ref` data from `release_branches.json`. Only stable and beta need to be considered.

**Comment by godofredoc** [comment]
@digiter would you mind taking a look?

**Comment by digiter** [comment]
Chris will remove hotfix builders once 1.12.13 is no longer stable.

**Comment by christopherfujino** [comment]
> Chris will remove hotfix builders once 1.12.13 is no longer stable.

@digiter However, the issue will still remain that beta/stable pre-submit PRs will use the prod try (master) builders for pre-submit, and are thus likely to be red as they use the wrong recipe version.

**Comment by nturgut** [comment]
We encountered this issue in `flutter-1.20-candidate.7` ex [PR](https://github.com/flutter/engine/pull/20068).

I think a solution will be using github APIs, such as: https://api.github.com/repos/flutter/engine/pulls/20068 This returns JSON. Base object's label has the correct branch name for the PR.

@christopherfujino suggested adding it to cocoon.

**Comment by godofredoc** [comment]
Cocoon already knows the branch but we don't have branch recipe configurations in the cocoon config file. After @keyonghan moves the config files to the repository under test then it will be easier to add per branch configs although it won't be the ideal configuration yet.

**Comment by christopherfujino** [comment]
FYI @keyonghan I created 4 action items. I'll land the first one this week since it blocks the rest, and then when either of us have extra cycles we can try to fill out the rest.

**Comment by christopherfujino** [comment]
So it turns out reading a JSON file from a `lucicfg` file (i.e. `main.star`) is non-trivial, as it provides a `to_json()` built-in function [API ref](https://github.com/luci/luci-go/tree/master/lucicfg/doc#to_json-to_json), but not a `from_json()`.

**Comment by godofredoc** [comment]
This can be done with minimal effort in the following way:

* Recipes repository is branched out along with engine and framework.
* Recipes bundler is configured to create bundles for main and release branches
* [buildbucket class](https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/model/luci/buildbucket.dart;l=381) is extended to support exe property, e.g '{"exe": {"cipdPackage": "","cipdVersion": ""}}'
* The scheduler propagates the target branch all the way from the webhook to the ScheduleBuild request.

**Comment by godofredoc** [comment]
Here is the CL for the second step:
https://flutter-review.googlesource.com/c/infra/+/21660/2/config/recipes_config.star

\cc @CaseyHillers

**Comment by CaseyHillers** [comment]
This is a much more elegant solution than I had in mind!
