### ISSUE TITLE
please review the following issue

### ISSUE THREAD

**Issue by sandy9808** [flutter/flutter#53370]
This is the following link to the issue i am having problem in:
https://github.com/flutter/flutter/issues/47071

**Comment by sandy9808** [comment]
you can Provide solution either in this issue or https://github.com/flutter/flutter/issues/47071

**Comment by jonahwilliams** [comment]
Hi @sandy9808,

If there is already an issue filled for a bug, there is no need to file a new one. It actually makes it harder for us to do our jobs if there are many duplicates, since we cannot easily tell how severe an issue is
