### ISSUE TITLE
AsyncSnapshot should have stackTrace

### ISSUE THREAD

**Issue by marcelgarus** [flutter/flutter#53384]
##  Use case

Dart's `Stream`s are really powerful. One feature of them is that they can contain `StackTrace`s.
By calling `stream.onError((error, stackTrace) { … })` developers can retrieve `StackTrace`s along with the errors.

`AsyncSnapshot`s, which are `Flutter`'s representation of the status of a `Stream` or a `Future` at a specific point in time, don't have the option to contain a `StackTrace` though.

That means, developers have to use ugly workarounds like the following to retrieve the `StackTrace`:

```dart
class ErrorAndStackTrace {
  ErrorAndStackTrace({@required this.error, this.stackTrace});
  final dynamic error;
  final StackTrace stackTrace;
}

...

StreamBuilder<T>(
  stream: someStream.onError((error, stackTrace) {
    throw ErrorAndStackTrace(error: error, stackTrace: stackTrace);
  }),
  builder: (context, snapshot) {
    if (snapshot.hasError) {
      final errorAndStackTrace = snapshot.error as ErrorAndStackTrace;
      final error = errorAndStackTrace.error;
      final stackTrace = errorAndStackTrace.stackTrace;
      …
    }
  },
);
```

## Proposal

I think it would be really great if `AsyncSnapshot` could also contain a `stackTrace` field, which can optionally contain a `StackTrace` if (and only if) the `error` is non-null. Then, `FutureBuilder` and `StreamBuilder` could both populate the field whenever possible.

**Comment by iapicca** [comment]
Hi @marcelgarus 
I believe your proposal is legitimate, 
but I'm not sure if it belongs to flutter or [dart](https://github.com/dart-lang/sdk/issues) itself
in the doubt I'll keep the issue open for the time being
thank you for your contribution

**Comment by marcelgarus** [comment]
Hmm. `AsyncSnapshot` is defined [in the Flutter repo](https://github.com/flutter/flutter/blob/c8efcb632bc853780f78ddb793d0ff49e12b76a7/packages/flutter/lib/src/widgets/async.dart#L197), so I'm pretty sure it's Flutter-specific.

**Comment by HerrNiklasRaab** [comment]
Ohh man this really bothers me, it's like driving a car while looking through the back window. Just wanted to add the error message. This is what I get when an Exception in a Stream used by a Streambuilder throws:

![image](https://user-images.githubusercontent.com/28401593/80119099-8bc24580-8589-11ea-8300-697ec300e5bb.png)

So big upvote on this one!

**Comment by creativecreatorormaybenot** [comment]
This is such high benefit and so trivial to implement. I am thinking about contributing this feature, however, I have the feeling that code review will bite me because testing it is propably a pain (given that `AsyncSnapshot` is used so much).

---

The fact that nobody has even started a PR makes me want to do this now 🤔

**Comment by iapicca** [comment]
tagging @TahaTesser for visibility
I agree with @creativecreatorormaybenot 's statement above

**Comment by creativecreatorormaybenot** [comment]
I am working on a PR for this 👍

**Comment by creativecreatorormaybenot** [comment]
My PR (#69507) has been merged into `master` 🎉

`AsyncSnapshot` has a `stackTrace` property now - so you can use `snapshot.stackTrace` if the snapshot has an error 😃
