### ISSUE TITLE
[flutter web] I can't set that <link rel="shortcut icon" href="/static/img/favicon.png" />

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53386]
[flutter web] I can't set that <link rel="shortcut icon" href="/static/img/favicon.png" />

**Comment by iapicca** [comment]
Hi @gionchat 
can you please provide your `flutter doctor -v` , 
your `flutter run  -d chrome --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by gionchat** [comment]
> 
> 
> Hi @gionchat
> can you please provide your `flutter doctor -v` ,
> your `flutter run -d chrome --verbose`
> and a reproducible minimal code sample.
> Thank you

![图片](https://user-images.githubusercontent.com/58280808/77813202-aec01d80-70e1-11ea-9764-4d1a63100cf6.png)
[  +29 ms] executing: [C:\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +64 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [C:\Android\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +6 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\Android\flutter/] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref HEAD
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] Exit code 0 from: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +24 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +233 ms] Generating C:\Users\Administrator\Desktop\Project\flutter_study\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +131 ms] Launching lib\main.dart on Chrome in debug mode...
[        ] Building application for the web...
[+9508 ms] Starting daemon...
[ +190 ms] Initializing inputs
[  +18 ms] Reading cached asset graph...
[ +233 ms] Reading cached asset graph completed, took 228ms

[ +376 ms] Checking for updates since last build...
[ +666 ms] Checking for updates since last build completed, took 666ms

[  +11 ms] Initializing inputs
[   +4 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 228ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 666ms
[+1127 ms] About to build [web]...
[   +4 ms] Running build...
[ +217 ms] Running build completed, took 118ms

[   +2 ms] Caching finalized dependency graph...
[   +8 ms] Caching finalized dependency graph completed, took 135ms

[   +4 ms] Succeeded after 262ms with 0 outputs (0 actions)

[  +11 ms] Building application for the web... (completed in 12.4s)
[        ] Attempting to connect to browser instance..
[+11898 ms] Debug service listening on ws://127.0.0.1:8290/7f5TypSN85E=

[ +374 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                 Status code: 404

                 Headers:
                 {
             "date": "Sat, 28 Mar 2020 02:45:01 GMT",
             "content-length": "9",
             "x-frame-options": "SAMEORIGIN",
             "content-type": "text/plain; charset=utf-8",
             "x-xss-protection": "1; mode=block",
             "x-content-type-options": "nosniff",
             "server": "dart:io with Shelf",
             "via": "1.1 shelf_proxy"
           }

                 Content:
                 Not Found}

[  +31 ms] Attempting to connect to browser instance.. (completed in 12.3s)
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[   +9 ms] Debug service listening on ws://127.0.0.1:8290/7f5TypSN85E=
My code：
`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Study'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

What i want？ Like this
![图片](https://user-images.githubusercontent.com/58280808/77813248-3312a080-70e2-11ea-8fd4-09c0fc94c9f4.png)

**Comment by VladyslavBondarenko** [comment]
@gionchat 
To have that favicon, place `favicon.ico` file to the `web` directory.
Or this way as you do (link tag in the html file), but use `.ico` file-extension.
This should solve your problem, closing.
Comment please if it doesn't and I'll reopen the issue
Thank you
