### ISSUE TITLE
Unable to install on Pixel 2 API 28 and above

### ISSUE THREAD

**Issue by aldwnesx** [flutter/flutter#53382]
I am getting `java.lang.UnsatisfiedLinkError` 

I have tried countless solution but couldn't get it to work.

I tried adding:

       ` ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`

but when uploading to playstore it shows that I need to add support for both 32 and 64 bit

**Comment by jonahwilliams** [comment]
You need to remove `x86` from the ABI filters, since flutter does not support 32bit x86

**Comment by aldwnesx** [comment]
If I remove that means it won’t be able to run on pixel 2 right? What do I do?

**Comment by jonahwilliams** [comment]
The pixel phones (and the vast majority of android devices) are arm or arm64.

**Comment by aldwnesx** [comment]
I removed x86 and ran flutter build appbundle

but doesn't work

**Comment by aldwnesx** [comment]
"You can't roll out this release because it doesn't allow any existing users to upgrade to the newly added APKs."

At first, I published appbundle and it worked fine. But because i could not run it on pixel 2, I added the code (   ` ndk.abiFilters 'armeabi-v7a','arm64-v8a',), and generated different APKs. I uploaded those APKs and published to store.

However now I want to try again with appbundle and I got that error

**Comment by aldwnesx** [comment]
The apk versions at 4009,2009,1009 but the generated appbundle is only version 9. Does this mean in pubspec I'm supposed to increase it to above 4009? It makes no sense to me.. what should I do? Previouly appbundle is 8. After I run the command to split APK it became 4009 2009 1009 

@jonahwilliams

**Comment by iapicca** [comment]
Hi @aldwnesx 
can you please provide your `flutter doctor -v` 
and your `flutter build appbundle --verbose` 
Thank you

**Comment by aldwnesx** [comment]
> Hi @aldwnesx
> can you please provide your `flutter doctor -v`
> and your `flutter build appbundle --verbose`
> Thank you

Hi, the app bundle issue has been fixed.

But issue of being unable to find the app on the playstore still persists on pixel 2 running api 29 on emulator.

What is the proper step to support them?

**Comment by iapicca** [comment]
Hi @aldwnesx 
I'm not sure that the issue you are experiencing is due to "lack of support"
for a give architecture

**Comment by aldwnesx** [comment]
What does that mean?

I am building for Pixel 2 API 28 but it doesn't show up on Playstore after i add 

     ndk {
        abiFilters "armeabi-v7a", "arm64-v8a"
    }

and android.useDeprecatedNdk=true


@iapicca 

Previously if I don't add these config it shows up on the playstore but crashes

**Comment by aldwnesx** [comment]
Could you tell me generally, how do you build an appbundle that supports majority of the devices? What kind of configuration?

I am not sure what I'm doing wrong..

**Comment by iapicca** [comment]
HI again @aldwnesx 
I apologise for the confusion
I mean that at first glance the issue doesn't seem to be caused 
by your configuration  according to this [comment](https://github.com/flutter/flutter/issues/53382#issuecomment-604767260)
Thank you

**Comment by aldwnesx** [comment]
> HI again @aldwnesx
> I apologise for the confusion
> I mean that at first glance the issue doesn't seem to be caused
> by your configuration according to this [comment](https://github.com/flutter/flutter/issues/53382#issuecomment-604767260)
> Thank you

Can you refer to https://github.com/flutter/flutter/issues/53411 ? I don't why know why it's closed..it is when I build using flutter

**Comment by jonahwilliams** [comment]
Yes, you need to increase the build number when switching between APK and appbundle. This is not a flutter specific issue, please read: https://stackoverflow.com/questions/47214125/google-play-store-release-issue

**Comment by aldwnesx** [comment]
> Yes, you need to increase the build number when switching between APK and appbundle. This is not a flutter specific issue, please read: https://stackoverflow.com/questions/47214125/google-play-store-release-issue

That's not the issue...the issue is

java.lang.UnsatisfiedLinkError (couldn't find “libflutter.so”)
