### ISSUE TITLE
Please wrap the dartfmt command from flutter command

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5338]
In order to reduce occasions where a user runs the wrong version of a utility, I think we can (and should) wrap utilities provided by the Dart SDK with our own `flutter` command.

For example, I would like our users to try formatting. The instructions to ensure they are using the _right_ version of the formatter are fairly complicated, complete with a bunch of "check this path" and "check this version".

Instead, I would like to say, "Run `flutter format foo.dart`" and have the flutter command use `dartfmt` that we bundle.

(we might want to do this for pub, too, but that's probably a different issue)

**Comment by sethladd** [comment]
cc @danrubel something you might be interested in helping with?

It's possible to work around this, but it requires digging into the bin/cache/blah/blah directory of your flutter clone. We've turned on formatting checks on the website, which means our friendly tech writers are now forced to format the samples. So, if we can make it as easy as `flutter format ...` that would be a win.

Thanks!

**Comment by danrubel** [comment]
Happy to tackle this next.
