### ISSUE TITLE
[tool_crash] Invalid argument(s): A directory corresponding to fileSystemPath "/home/havoc/dev/mobile/flutter2/.pub-cache/hosted/pub.dartlang.org/devtools-0.1.15/build" could not be found

### ISSUE THREAD

**Issue by Prn-Ice** [flutter/flutter#53380]
## Command
```console
flutter run -d chrome
```

## Steps to Reproduce
1. Download beta flutter SDK
2. Move to channel stable
3. Rename flutter folder to flutter2
4. Move back to beta
5. Enable web support
6. Rename flutter folder to the original

## Logs
`ArgumentError: Invalid argument(s): A directory corresponding to fileSystemPath "/home/havoc/dev/mobile/flutter2/.pub-cache/hosted/pub.dartlang.org/devtools-0.1.15/build" could not be found`
```bash
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:32:24)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.17 at /home/havoc/dev/mobile/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/havoc/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at:
      /home/havoc/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.624
      1897/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at
      /home/havoc/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.624
      1897
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at
      /home/havoc/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/193.6494.35
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • itel W5504 • 041331494K008900 • android-arm    • Android 8.1.0 (API 27)
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Version**: 1.4.0
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by Prn-Ice** [comment]
I think I should just redownload beta SDK and never rename again, but I would like to know if there's another option. This all started as an experiment as to whether I could have both beta and stable versions locally.

**Comment by iapicca** [comment]
HI @Prn-Ice 
I'm not sure of the purpose if the steps you provided

> - Download beta flutter SDK
> - Move to channel stable
> - Rename flutter folder to flutter2
> - Move back to beta
> - Enable web support
> - Rename flutter folder to the original

if your goal is to use several version of flutter at the same time
I recommend you to follow this [article](https://medium.com/@sarbagyastha/using-two-or-more-different-versions-of-flutter-in-single-machine-484293c2a7ff)
I can tell you first hand it works flawlessly on both linux and mac

```console
 nevercode@Nevercodes-Air  ~  flutter doctor                                                                                                                ✔  755  09:27:27
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-EE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code
[✓] Connected device (1 available)

• No issues found!
 nevercode@Nevercodes-Air  ~  flutter_beta doctor                                                                                                           ✔  756  09:27:42
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-EE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code
[✓] Connected device (3 available)

• No issues found!
 nevercode@Nevercodes-Air  ~  flutter_dev doctor                                                                                                            ✔  757  09:28:02
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.4 19E266, locale en-EE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code
[✓] Connected device (3 available)

• No issues found!
 nevercode@Nevercodes-Air  ~  flutter_master doctor                                                                                                         ✔  758  09:28:23
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.2-pre.41, on Mac OS X 10.15.4 19E266, locale en-EE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code
[✓] Connected device (3 available)

• No issues found!
 nevercode@Nevercodes-Air  ~                                                                                                                                ✔  759  09:28:44 
```

is that the case?
thank you

**Comment by Prn-Ice** [comment]
> HI @Prn-Ice
> I'm not sure of the purpose if the steps you provided
> 
> > * Download beta flutter SDK
> > * Move to channel stable
> > * Rename flutter folder to flutter2
> > * Move back to beta
> > * Enable web support
> > * Rename flutter folder to the original
> 
> if your goal is to use several version of flutter at the same time
> I recommend you to follow this [article](https://medium.com/@sarbagyastha/using-two-or-more-different-versions-of-flutter-in-single-machine-484293c2a7ff)
> I can tell you first hand it works flawlessly on both linux and mac
> 
> ```
>  nevercode@Nevercodes-Air  ~  flutter doctor                                                                                                                ✔  755  09:27:27
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-EE)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.6)
> [✓] VS Code
> [✓] Connected device (1 available)
> 
> • No issues found!
>  nevercode@Nevercodes-Air  ~  flutter_beta doctor                                                                                                           ✔  756  09:27:42
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-EE)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] VS Code
> [✓] Connected device (3 available)
> 
> • No issues found!
>  nevercode@Nevercodes-Air  ~  flutter_dev doctor                                                                                                            ✔  757  09:28:02
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.4 19E266, locale en-EE)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] VS Code
> [✓] Connected device (3 available)
> 
> • No issues found!
>  nevercode@Nevercodes-Air  ~  flutter_master doctor                                                                                                         ✔  758  09:28:23
>   ╔════════════════════════════════════════════════════════════════════════════╗
>   ║ A new version of Flutter is available!                                     ║
>   ║                                                                            ║
>   ║ To update to the latest version, run "flutter upgrade".                    ║
>   ╚════════════════════════════════════════════════════════════════════════════╝
> 
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.16.2-pre.41, on Mac OS X 10.15.4 19E266, locale en-EE)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] VS Code
> [✓] Connected device (3 available)
> 
> • No issues found!
>  nevercode@Nevercodes-Air  ~                                                                                                                                ✔  759  09:28:44 
> ```
> 
> is that the case?
> thank you

Thanks for the link, I'll use that. I created the issue to see if my current flutter sdk could be fixed cause right now I can't build for web with it. I'll be closing the issue now.
