### ISSUE TITLE
iOS build failing with 'cannot invoke initializer for type 'WebSocket' with an argument list of type '(url: URL)'

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#53396]
I am getting below error while trying to build for iOS:

```bash
 === BUILD TARGET video_call OF PROJECT Pods WITH CONFIGURATION Debug ===
     /Users/deeptibelsare/Documents/QuickCarl/qc_flutter_messaging/ios/Classes/SwiftQcMessagingPlugin.swift:190:16: error: cannot invoke initializer for type 'WebSocket' with an argument list of type '(url: URL)'
                     let socket = WebSocket(url: URL(string: SwiftQcMessagingPlugin.socketUrl)!)
```

Whereas, app is building properly on Android.

**Flutter Doctor:**

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/deeptibelsare/Documents/Flutter-sdk/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max         • BBC1F461-DD1E-4149-94DE-BFB7A8DFAA65 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

Appreciate any help in resolving this issue.

**Comment by iapicca** [comment]
Hi @DK15 
can you please provide your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by DK15** [comment]
@iapicca  here's flutter run --verbose output:

> [  +40 ms] executing: [/Users/deeptibelsare/Documents/Flutter-sdk/flutter/] git
> -c log.showSignature=false log -n 1 --pretty=format:%H
> [  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
> --pretty=format:%H
> [        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
> [        ] executing: [/Users/deeptibelsare/Documents/Flutter-sdk/flutter/] git
> describe --match v*.*.* --first-parent --long --tags
> [  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
> --tags
> [        ] v1.12.13+hotfix.8-0-g0b8abb472
> [  +10 ms] executing: [/Users/deeptibelsare/Documents/Flutter-sdk/flutter/] git
> rev-parse --abbrev-ref --symbolic @{u}
> [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/stable
> [        ] executing: [/Users/deeptibelsare/Documents/Flutter-sdk/flutter/] git
> ls-remote --get-url origin
> [  +15 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [  +80 ms] executing: [/Users/deeptibelsare/Documents/Flutter-sdk/flutter/] git
> rev-parse --abbrev-ref HEAD
> [  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] stable
> [  +10 ms] executing: sw_vers -productName
> [  +29 ms] Exit code 0 from: sw_vers -productName
> [        ] Mac OS X
> [        ] executing: sw_vers -productVersion
> [  +22 ms] Exit code 0 from: sw_vers -productVersion
> [        ] 10.15.2
> [        ] executing: sw_vers -buildVersion
> [  +26 ms] Exit code 0 from: sw_vers -buildVersion
> [        ] 19C57
> [  +41 ms] executing: /usr/bin/xcode-select --print-path
> [  +14 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
> [        ] /Applications/Xcode.app/Contents/Developer
> [   +1 ms] executing: /usr/bin/xcodebuild -version
> [+1253 ms] Exit code 0 from: /usr/bin/xcodebuild -version
> [   +2 ms] Xcode 11.3
>            Build version 11C29
> [  +77 ms] executing:
> /Users/deeptibelsare/Library/Android/sdk/platform-tools/adb devices -l
> [   +8 ms] Exit code 0 from:
> /Users/deeptibelsare/Library/Android/sdk/platform-tools/adb devices -l
> [        ] List of devices attached
> [  +19 ms] executing:
> /Users/deeptibelsare/Documents/Flutter-sdk/flutter/bin/cache/artifacts/libimobil
> edevice/idevice_id -h
> [  +98 ms] /usr/bin/xcrun simctl list --json devices
> [ +164 ms] No supported devices connected.
> [  +13 ms] "flutter run" took 1,807ms.
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
> #1      RunCommand.validateCommand
> (package:flutter_tools/src/commands/run.dart:289:7)
> <asynchronous suspension>
> #2      FlutterCommand.verifyThenRunCommand
> (package:flutter_tools/src/runner/flutter_command.dart:590:11)
> #3      FlutterCommand.run.<anonymous closure>
> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
> <asynchronous suspension>
> #4      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:146:29)
> #5      _rootRun (dart:async/zone.dart:1126:13)
> #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> #7      _runZoned (dart:async/zone.dart:1518:10)
> #8      runZoned (dart:async/zone.dart:1465:12)
> #9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
> #10     FlutterCommand.run
> (package:flutter_tools/src/runner/flutter_command.dart:505:20)
> #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> #12     FlutterCommandRunner.runCommand.<anonymous closure>
> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
> <asynchronous suspension>
> #13     AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:146:29)
> #14     _rootRun (dart:async/zone.dart:1126:13)
> #15     _CustomZone.run (dart:async/zone.dart:1023:19)
> #16     _runZoned (dart:async/zone.dart:1518:10)
> #17     runZoned (dart:async/zone.dart:1465:12)
> #18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
> #19     FlutterCommandRunner.runCommand
> (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
> #20     CommandRunner.run.<anonymous closure>
> (package:args/command_runner.dart:112:25)
> #21     new Future.sync (dart:async/future.dart:224:31)
> #22     CommandRunner.run (package:args/command_runner.dart:112:14)
> #23     FlutterCommandRunner.run
> (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
> #24     run.<anonymous closure>.<anonymous closure>
> (package:flutter_tools/runner.dart:63:22)
> #25     _rootRun (dart:async/zone.dart:1126:13)
> #26     _CustomZone.run (dart:async/zone.dart:1023:19)
> #27     _runZoned (dart:async/zone.dart:1518:10)
> #28     runZoned (dart:async/zone.dart:1502:12)
> #29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
> <asynchronous suspension>
> #30     AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:146:29)
> #31     _rootRun (dart:async/zone.dart:1126:13)
> #32     _CustomZone.run (dart:async/zone.dart:1023:19)
> #33     _runZoned (dart:async/zone.dart:1518:10)
> #34     runZoned (dart:async/zone.dart:1465:12)
> #35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
> #36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
> #37     run (package:flutter_tools/runner.dart:50:10)
> #38     main (package:flutter_tools/executable.dart:65:9)
> #39     main
> (file:///Users/deeptibelsare/Documents/Flutter-sdk/flutter/packages/flutter_tool
> s/bin/flutter_tools.dart:8:3)
> #40     _startIsolate.<anonymous closure>
> (dart:isolate-patch/isolate_patch.dart:305:32)
> #41     _RawReceivePortImpl._handleMessage
> (dart:isolate-patch/isolate_patch.dart:174:12)
> 

**pubspec.yaml:**

> name: qc_flutter_pro
> description: QuickCarl Pro
> 
> # This is only used for iOS builds. For Android build, we set these
> # values in the app/build.gradle file
> version: 0.6.2+10
> 
> environment:
>   sdk: ">=2.1.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   intl: ^0.16.0
>   shared_preferences: ^0.5.6+2
>   flutter_web_browser: ^0.11.0
>   flutter_webview_plugin: ^0.3.5
> 
>   # Making REST requests
>   http: ^0.12.0
> 
>   #Firebase authentication plugin
>   firebase_auth: ^0.8.0+1
> 
>   firebase_storage: ^2.0.0
>   firebase_analytics: ^2.0.0
>   firebase_database: ^2.0.2
>   firebase_remote_config: ^0.1.0
>   firebase_dynamic_links: ^0.5.0
> 
>   # get info about installed apps
>   flutter_appavailability: ^0.0.21
> 
>   # retrieve and store images in local cache
>   cached_network_image: ^2.0.0
> 
>   # See: https://pub.dartlang.org/packages/image_picker
>   # for iOS specific installation instructions
>   image_picker: ^0.6.1
> 
>   # The following adds the Cupertino Icons font to your application.
>   # Use with the CupertinoIcons class for iOS style icons.
>   cupertino_icons: ^0.1.2
> 
>   fluttertoast: ^3.0.1
> 
>   uuid: ^2.0.2
> 
>   url_launcher: ^5.4.2
> 
>   share: ^0.6.0+1
> 
>   flutter_linkify: 1.0.3
> 
>   package_info: ^0.4.0+3
> 
>   flutter_sms: ^1.1.0
> 
>   qc_messaging:
>     path: ../qc_flutter_messaging
> 
>   video_call:
>     path: ../video_call
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   flutter_driver:
>     sdk: flutter
>   test: ^1.5.1
>   flutter_launcher_icons: ^0.7.0
> 
> flutter_icons:
>   android: false
>   ios: true
>   image_path_android: "assets/icons/qc_pro_icon_android.png"
>   image_path_ios: "assets/icons/qc_pro_icon_ios.jpg"
>   adaptive_icon_background: "#ffffff"
> 
> flutter:
>     uses-material-design: true
>     assets:
>      - assets/
>      - assets/configs/
>      - assets/share/
>      - assets/ftux/

**Comment by iapicca** [comment]
Hi @DK15 
I see the logs stop because there's no device
```bash
[ +164 ms] No supported devices connected.
[  +13 ms] "flutter run" took 1,807ms.
```
could you please provide the flutter run -verbose 
with a device attached, and representative of the issue.

Also reconnecting to the first post I see in your yaml

```yaml
 qc_messaging:
    path: ../qc_flutter_messaging 
```

the issues seems to be caused by `qc_messaging`
I cannot find in pub.dev, is it a third party plugin?

Thank you
