### ISSUE TITLE
How to use custom icons in Stepper

### ISSUE THREAD

**Issue by zyllus17** [flutter/flutter#53397]
I was trying to create the Google Maps Route UI in flutter. I tried to use `Stepper` to create it like the one in the image below.
<tr>
    <td><img src="https://user-images.githubusercontent.com/50977126/77727005-5294c500-701f-11ea-8b55-9349a7f88e08.jpeg" width=270 height=650></td>
</tr>
But the Stepper widget doesn't let me use other icons except the five icons provided in `state: StepState`. I want to use my custom icons but I can't figure out how to use it.

**Comment by thedejifab** [comment]
@zyllus17 if there were to be a way to define custom IconData for each of the states, would that meet your needs?

**Comment by zyllus17** [comment]
@thedejifab Yes that would have helped but I found two other ways to achieve the UI.

1. I can use the timeline package to get the UI
https://pub.dev/packages/timeline_list

2. I can use my own custom paint to achieve what I need. I managed to complete my UI with custom paint.
I am leaving the link to the repository if anyone might need the UI.
https://github.com/zyllus17/Google-Maps-Route-UI
## Screenshots

  <table>
    <tr>
      <td><p align="center">Route UI</p></td>
    </tr>
    <tr>
        <p align="center">
        <td><img src="https://user-images.githubusercontent.com/50977126/78035426-b6ecb700-7386-11ea-936b-2c1d5a450147.png" width=300 height=550></td>
        </p>
    </tr>
  </table>
