### ISSUE TITLE
When app is in OneDrive directory "flutter pub get" returns Error: No pubspec.yaml file found.

### ISSUE THREAD

**Issue by ajith007** [flutter/flutter#53392]
I keep running into this error -
**Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.**

I got stuck earlier with the same error and so I created new project by running 'flutter create testapp'. I was able run the default App in Chrome using 'flutter run -d chrome'. Then I updated pubspec.yaml to include few images that I added to the assets/images folder. The hot reload didn't pick the changes, so had to exit the App and then ran 'flutter pub get' as below and I'm stuck again! 
![image](https://user-images.githubusercontent.com/1762945/77722957-13358c80-6fbd-11ea-872e-9b287bf75439.png)

I'm on Windows 10 Pro. Here's the results of some flutter commands that could be useful.
![image](https://user-images.githubusercontent.com/1762945/77723306-154c1b00-6fbe-11ea-99f5-676892a33e0d.png)

![image](https://user-images.githubusercontent.com/1762945/77723370-43c9f600-6fbe-11ea-9e53-63cc81bfe443.png)

![image](https://user-images.githubusercontent.com/1762945/77723492-9a373480-6fbe-11ea-9c95-17c57244f490.png)

I tried deleting the old flutter folder, installed it fresh on to a new folder, updated the PATH, restarted the machine etc .. but no luck! 

I'm using VSCode. 

Let me know if you need any additional info to troubleshoot .... I'm not able to explore Flutter beyond the first few steps ..... kindly assist!

**Comment by ajith007** [comment]
I tried reverting the pubspec.yaml changes to comment the assets as shown below but its still throwing the same error when I try to run ..
![image](https://user-images.githubusercontent.com/1762945/77724097-1aaa6500-6fc0-11ea-8b87-d0dbff6d9f10.png)

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/52997.
@ajith007 could you provide your `flutter pub get --verbose`?

**Comment by ajith007** [comment]
@VladyslavBondarenko , thank you for the response. 
here's the info requested - 
PS C:\Users\ramakrisa\OneDrive\AjithLabs\flutterapps\testapp> flutter pub get --verbose
[  +13 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +80 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[   +1 ms] executing: [C:\tools\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+1653 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[   +2 ms] From https://github.com/flutter/flutter
            * branch                HEAD       -> FETCH_HEAD
[        ] executing: [C:\tools\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +77 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.17-0-g2294d75bf
[   +6 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +59 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +65 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +12 ms] "flutter get" took 169ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:791:11)
#1      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:691:11)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:609:33)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:599:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     run.<anonymous closure> (package:flutter_tools/runner.dart)
#32     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:18)
<asynchronous suspension>
#33     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1465:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#40     runInContext (package:flutter_tools/src/context_runner.dart:72:24)
#41     run (package:flutter_tools/runner.dart:50:10)
<asynchronous suspension>
#42     main (package:flutter_tools/executable.dart:69:9)
#43     main (file:///C:/tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

PS C:\Users\ramakrisa\OneDrive\AjithLabs\flutterapps\testapp>

**Comment by jmagman** [comment]
Did you run `flutter config --enable-web`?
https://flutter.dev/docs/get-started/web#set-up

**Comment by ajith007** [comment]
@jmagman , i just did that but didn't help.
![image](https://user-images.githubusercontent.com/1762945/77799621-3014a300-7043-11ea-9478-373503a3ac37.png)

after restarting VSCode - 
![image](https://user-images.githubusercontent.com/1762945/77799719-5c302400-7043-11ea-9568-140eae92d248.png)

**Comment by jmagman** [comment]
> Then I updated pubspec.yaml to include few images that I added to the assets/images folder. 

Can you attach your pubspec.yaml?

**Comment by ajith007** [comment]
@jmagman , here you go ... renamed the file so that I could attach it here ..
[pubspec_yaml.txt](https://github.com/flutter/flutter/files/4396164/pubspec_yaml.txt)

**Comment by jonahwilliams** [comment]
I'm going to guess that Flutter or Dart is having trouble finding the file since its hosted in a OneDrive folder, and these don't work quite like normal filesystems.

Can you reproduce this issue for a project that is created on a "regular" directory?

**Comment by jmagman** [comment]
pubspec looks fine, though it doesn't match the "Then I updated pubspec.yaml to include few images that I added to the assets/images folder. " description since the assets are commented out.  @jonahwilliams OnDrive guess is more likely.

**Comment by ajith007** [comment]
Yayy! It worked fine when I moved it out of OneDrive folder. 
So while in OneDrive, it works fine until you touch pubspec.yaml. Anyways, all good now!

Thank you so much @jonahwilliams  & @jmagman ! I'll close the issue.

**Comment by jmagman** [comment]
I wonder if there's any way for the tool to detect this state and give a better error message.

**Comment by jonahwilliams** [comment]
The first thing to do would be to see if normal dart:io file operations work in a one drive directory. If not, then we need to file a bug with the dart team.

I don't really want to add logic to the tool like `if pubspec missing and cwd.contains("OneDrive"))` but i guess we could if there were no other options

**Comment by jonahwilliams** [comment]
I guess I can do this on my PC tonight

**Comment by jonahwilliams** [comment]
I'm able to normally create an app in a OneDriver folder. My current guess is that in the case where the artifacts aren't downloaded on the local device, its possible that the dart:io operations don't tickle whatever behavior is necessary to pull them down.

**Comment by jonahwilliams** [comment]
Oh, TIL this is actually called SkyDrive on my PC?

**Comment by jonahwilliams** [comment]
Or maybe those are different...

**Comment by jonahwilliams** [comment]
OneDrive doesn't let me sign in locally, un-assigning for now.

@ajith007 in your project in OneDrive, can you verify in the explorer or OneDrive app that the files are downloaded locally? In my OneDrive folder I can "see" several folders that are available online that otherwise aren't downloaded fully, though I can't repro your crash

**Comment by ajith007** [comment]
here you go @jonahwilliams  ... yes, the OneDrive folders and files are very much available locally. 
![image](https://user-images.githubusercontent.com/1762945/77814622-a1267b80-7080-11ea-8af2-c461e2578f8e.png)

**Comment by jonahwilliams** [comment]
Super weird! Oh well, I'll keep trying to get this to repro locally

**Comment by ajith007** [comment]
pls lmk if you need any help ...

**Comment by huycozy** [comment]
Hi @ajith007, I can not reproduce the issue on the latest `stable` and `master` channels.
The project worked fine on OneDrive folder.

<details>
<summary>Demo</summary>

| stable | master |
| --------------- | --------------- |
<img width="500" src="https://user-images.githubusercontent.com/104349824/182598660-baa5e138-df70-415f-ac83-150b74464aff.PNG"> | <img width="500" src="https://user-images.githubusercontent.com/104349824/182599549-e52c64ae-4cf9-4a1f-a9d0-457a530fbf52.PNG">

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 3.0.5 at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.69.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[√] Flutter (Channel master, 3.1.0-0.0.pre.2057, on Microsoft Windows [Version 10.0.19043.1826], locale en-US)
    • Flutter version 3.1.0-0.0.pre.2057 on channel master at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a880c4ed35 (in the future), 2022-08-03 04:29:18 -0400
    • Engine revision 05228ad454
    • Dart version 2.19.0 (build 2.19.0-59.0.dev)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

Could you please confirm if you are still facing this issue on the latest version of flutter stable or master?
Thank you!
