### ISSUE TITLE
LazyBlock flinging stutters if it hits a boundary exactly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5339]
There's several bugs being demonstrated by this test:
https://github.com/Hixie/flutter/blob/9ee03481b8a8d041d5b7c86ab8923913fdcf3f8f/packages/flutter/test/widget/lazy_block_fling_test.dart

**Comment by Hixie** [comment]
I should check to see if this still happens.

**Comment by Hixie** [comment]
It does still happen.

**Comment by csells** [comment]
@Hixie can you provide the steps to reproduce and your expected behavior?

**Comment by Hixie** [comment]
The steps to reproduce are "remove the `skip: true` on the test" and the expected behaviour is "the test passes".
