### ISSUE TITLE
Re-enable tests on Fuchsia that relied on fml::WriteAtomically

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#53399]
An example of this failure [is here](https://chromium-swarm.appspot.com/task?id=4b3184279ec5af10&w=true). This must be re-enabled once the Fuchsia issue is addressed. The Fuchsia bots were also in quarantine till recently and the last three builds have failed consistently. So it may be that `fml::WriteAtomically` has not been wired up on Fuchsia or is accessing a directory that is not setup correctly in the test harness. In that case, this may not be a flake. In any case, this issue tracks re-enabling that test.

- [ ] OnServiceProtocolGetSkSLsWorks re-enabled
- [ ] CanLoadSkSLsFromAsset re-enabled
- [ ] CanRemoveOldPersistentCache re-enabled.

**Comment by liyuqian** [comment]
The `fml::WriteAtomically` is also affecting `CanLoadSkSLsFromAsset` test. Adding that as a checklist item to this issue.
