### ISSUE TITLE
run 'flutter doctor' report 'Android SDK file not found: adb.'

### ISSUE THREAD

**Issue by leo193** [flutter/flutter#53391]
## Steps to Reproduce

1.Install Android Studio
2.run `flutter doctor`

## Logs
```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android SDK file not found: adb.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[!] Connected device
    ! No devices available
```
I don't know how to solve this error, has anyone encountered such a situation?My flutter version is v1.12.13+hotfix.8,Android Studio‘s version is 3.6.1

**Comment by iapicca** [comment]
Hi @leo193 
can you please provide your `flutter doctor -v` , 
Thank you

possibly related to https://github.com/flutter/flutter/issues/51712

**Comment by snowfighting** [comment]
I also encountered the same problem.

**Logs**:
` ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F2058, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/songxuejiao/Documents/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/songxuejiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/songxuejiao/Library/Android/sdk
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

**Comment by snowfighting** [comment]
I also encountered the same problem.

**Logs:**
`
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F2058, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/songxuejiao/Documents/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/songxuejiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/songxuejiao/Library/Android/sdk
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
`

**Comment by TahaTesser** [comment]
Hi @leo193 

1. Go to platform-tools folder in your Android SDK, make sure adb files aren't nested into another folder.  If nested,  move all files to top platform-tools folder. **Platform-tool folder shouldn't nested and it should adb inside it**

2. Install SDK tools from your SDK manager (if hidden, **uncheck Hide Obsolete Packages**)

3. Execute `flutter doctor    --android-licenses` and accept the licenses

4. Execute `flutter doctor -v`, it should show `[✓]` in Android ToolChain 

Thank you

**Comment by leo193** [comment]
@ TahaTesser  
Thank you. The problem is solved.The problem is that there are subdirectories under the platform tools directory, which is also called platform tools.Put all the contents of subdirectories at the top level to solve the error
