### ISSUE TITLE
App crash when new FlutterViewController

### ISSUE THREAD

**Issue by 709213219** [flutter/flutter#53406]
App crash when new FlutterViewController。
FlutterViewController *vc = [FlutterViewController new];

<img width="957" alt="1" src="https://user-images.githubusercontent.com/10647771/77743085-81785e80-7052-11ea-8bd1-5d5b699d60b9.png">

**Comment by VladyslavBondarenko** [comment]
Hi @709213219 
could you provide your `flutter doctor -v` and the crash log?

**Comment by 709213219** [comment]
@VladyslavBondarenko 
[✓] Flutter (Channel dev, v1.15.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.15.9 at /Users/linbiao/development/flutter
    • Framework revision cc52a903a8 (3 weeks ago), 2020-03-04 18:59:18 -0800
    • Engine revision 810727bf3f
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 57462f9ca5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/linbiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/linbiao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • HUAWEI • eeceeeb6235966bb0fe450389e82c5c0786d1d88 • ios • iOS 13.3

• No issues found!
➜  ~ flutter doctor -v
[✓] Flutter (Channel dev, v1.15.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.15.9 at /Users/linbiao/development/flutter
    • Framework revision cc52a903a8 (3 weeks ago), 2020-03-04 18:59:18 -0800
    • Engine revision 810727bf3f
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 57462f9ca5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/linbiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/linbiao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • HUAWEI • eeceeeb6235966bb0fe450389e82c5c0786d1d88 • ios • iOS 13.3

• No issues found!

**Comment by 709213219** [comment]
@VladyslavBondarenko 
[✓] Flutter (Channel dev, v1.15.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.15.9 at /Users/linbiao/development/flutter
    • Framework revision cc52a903a8 (3 weeks ago), 2020-03-04 18:59:18 -0800
    • Engine revision 810727bf3f
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 57462f9ca5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/linbiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/linbiao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by VladyslavBondarenko** [comment]
@709213219 
Could you provide crash log?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
