### ISSUE TITLE
Custom icon fonts tree shaking

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#53400]
## Use case

I'm using [Font Awesome package](https://pub.dev/packages/font_awesome_flutter) and quick logs at verbose release build clearly shows, that MaterialIcons is tree-shaked, but Font Awesome doesn't.

## Proposal

Could there be some option to enable tree shaking of non flutter icons fonts?

**Comment by VladyslavBondarenko** [comment]
Hi @rostopira 
It's currently in work, please take a look at this post https://www.reddit.com/r/FlutterDev/comments/f4h3l9/tree_shake_icon_fonts_since_v1151/
https://github.com/flutter/flutter/pull/49737

Closing this proposal,
if you disagree please write in the comments and I will reopen it
Thank you
