### ISSUE TITLE
url_launcher - POST method

### ISSUE THREAD

**Issue by yerzhant** [flutter/flutter#53419]
Is it possible to send a POST request using url_launcher plugin?

**Comment by jonahwilliams** [comment]
The url_launcher is opening/launching URLs and not for posting data.

**Comment by yerzhant** [comment]
@jonahwilliams  Thanks for reply.

There's a payments provider. They have an app, which, I guess, is using _Deep links_ or _Android App Links_ (https://developer.android.com/training/app-links). When I post a form from my site in Android Google Chrome then pops up a toast/snack bar asking me to choose where to open the link: Google Chrome or their app.

Do you know what else plugin can I use to open a url with post method?

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by yerzhant** [comment]
Ok, thanks.
