### ISSUE TITLE
Generate dartdoc pages for Google-specific widgets

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53418]
https://b.corp.google.com/issues/64898300.

cc @mehmetf.

**Comment by mehmetf** [comment]
This is not an OSS issue.

**Comment by kf6gpe** [comment]
It's not, but without a Github issue, it clutters the Flutter Google3 daily
issue triage, which is why I filed it here.


Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>
