### ISSUE TITLE
Without any codding error it occurred 

### ISSUE THREAD

**Issue by Mehrbod2002** [flutter/flutter#53417]
Hello , I receive this error code many times in my flutter application which made for user register 
and this code occurred for State of register code form but there is not and codding errors

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building RegisterForma(dirty, state: _RegisterFormState#2abc3):
type '(String) => void' is not a subtype of type '(String) => String'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  RegisterForma file:///C:/Users/Mehrbod/Desktop/flutter_app1/chatmap/chatmap/lib/main.dart:67:20
When the exception was thrown, this was the stack: 
#0      _RegisterFormState.build (package:chatmap/main.dart:216:24)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by kawal7415** [comment]
@Mehrbod2002 Can you tell us how to reproduce this error ?

**Comment by VladyslavBondarenko** [comment]
@Mehrbod2002 
could you please a [minimal complete code sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the error? and your `flutter doctor -v`

**Comment by Mehrbod2002** [comment]
> 
> 
> @Mehrbod2002
> could you please a [minimal complete code sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the error? and your `flutter doctor -v`



> 
> 
> @Mehrbod2002 Can you tell us how to reproduce this error ?
I made two classes . first one is user sign up with firebase and store in firestore it works correctly but in another class which i made for use  profile i want to get out user name and all fields from by this code :
`class userprofile1 extends StatelessWidget {
 Future<String> inputData() async {
   FirebaseUser user = await FirebaseAuth.instance.currentUser();
   var userid = user.uid.toString();
   Firestore.instance.collection("users").document('$userid').snapshots();
 }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("ChatMap"),
      ),
      body: FutureBuilder<String>(
      future: inputData(),
    builder: (BuildContext context, AsyncSnapshot snapshot)
    {if (snapshot.hasData) {
      new Text("Done");
    }
    else {
      return CircularProgressIndicator();
    }
    }
    ),
      drawer: Drawer(),
    );
  }
}`
but it shows else condition ,,, do you know how can i write this code ?
i used stream and future already .
thanks

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
