### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoade

### ISSUE THREAD

**Issue by aldwnesx** [flutter/flutter#53411]
Hi, I am using this package:

https://pub.dev/packages/flutter_vpn
As told, I have to put the following 
In build.gradle :

 ```
 ndk {
                    if (project.hasProperty('target-platform')) {
                        if (project.property('target-platform') == 'android-arm,android-arm64')
                            abiFilters 'armeabi-v7a', 'arm64-v8a'
                        else if (project.property('target-platform') == 'android-arm')
                            abiFilters 'armeabi-v7a'
                        else if (project.property('target-platform') == 'android-arm64')
                            abiFilters 'arm64-v8a'
                    }
                }

```
However when installing on devices like  pixel 2 , i open it and it crashes. 
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoade`

I googled and solutions suggest to add the following in build.gradle: (https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d)

 ndk {
        abiFilters "armeabi-v7a", "arm64-v8a"
    } 

The problem is now after generating the appbundle to playstore, it is no longer avaialble for pixel 2. It says not supported.

Are there any solution I can build appbundle and it works without crashing?

**Comment by jonahwilliams** [comment]
Perhaps you should reach out to the flutter_vpn package. Flutter on its own does not require abiFilters

**Comment by aldwnesx** [comment]
> Perhaps you should reach out to the flutter_vpn package. Flutter on its own does not require abiFilters

but the error is:

java.lang.UnsatisfiedLinkError (couldn't find “libflutter.so”)

**Comment by jonahwilliams** [comment]
Because you've added new configuration to your gradle build that is causing it to exclude `libflutter.so`. Remove this configuration and it will work correctly, as it does for (nearly) everyone else

**Comment by aldwnesx** [comment]
> Because you've added new configuration to your gradle build that is causing it to exclude `libflutter.so`. Remove this configuration and it will work correctly, as it does for (nearly) everyone else

If I remove and use the default config, it sitll crashes on the device...
