### ISSUE TITLE
package_info readme file is wrong: dependency constraint single quote

### ISSUE THREAD

**Issue by camillo777** [flutter/flutter#53413]
Hello, just to note that in the package readme on github and pub the dependency constraint to allow a smoother ecosystem migration uses single quote instead of double quotes:

WRONG
package_info: '>=0.4.0+16 <2.0.0'

CORRECT
package_info: ">=0.4.0+16 <2.0.0"

**Comment by alfredobs97** [comment]
In which file do you read this?

**Comment by camillo777** [comment]
Hello!
For example here:

https://pub.dev/packages/package_info

**Comment by Roshan13046** [comment]
I would like to close this issue with my PR.

**Comment by stuartmorgan** [comment]
I'm not sure where you saw that `'` was wrong; both versions are supported. See https://dart.dev/tools/pub/dependencies.
