### ISSUE TITLE
TypeAheadFormField itemBuilder items list not showing on any kind of MediaQuery.of(context)

### ISSUE THREAD

**Issue by asheshpaul** [flutter/flutter#53416]

**Comment by asheshpaul** [comment]
Widget build(BuildContext context) {
var orientation = MediaQuery.of(context).orientation;

return Scaffold(
  body: Form(
    child: (orientation == Orientation.portrait)
        ? _buildPortraitLayout()
        : _buildLandscapeLayout(),
  ),
);

I am trying this MediaQuery.....

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
