### ISSUE TITLE
Flutter WEB Only, Not possible to display Numeric Keyboard With Decimal

### ISSUE THREAD

**Issue by devfaheem** [flutter/flutter#53421]
Hi All

Only With Flutter WEB Project . This works fine on IOS Native and ANDROID Native

**TextFormField** with **keyboardType: TextInputType.numberWithOptions(decimal: true)**
 
Will not show Period or Comma on numeric keyboard on safari browser Iphone 6s

**Comment by iapicca** [comment]
Hi @devfaheem 
can you please provide your `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you

**Comment by devfaheem** [comment]
I am using the code below 

Also  please find the flutter doctor -v details below

TextFormField(
                    keyboardType: TextInputType.numberWithOptions(decimal: true),
                      initialValue: activityDetail.tsoInPlaceSpeed != null
                          ? activityDetail.tsoInPlaceSpeed.toString()
                          : "",
                      validator: (val) {
                        if (double.tryParse(val) == null) {
                          return "please enter a number";
                        }
                        return null;
                      },
                      onSaved: (val) {
                        activityDetail.tsoInPlaceSpeed = double.parse(val);
                      },
                      style: TextStyle(fontSize: 20)),


[√] Flutter (Channel dev, v1.16.1, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
    • Flutter version 1.16.1 at C:\flutter
    • Framework revision e6b0f5f238 (3 weeks ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rules\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\rules\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\rules\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by iapicca** [comment]
Hi @devfaheem 
to open the web app on your iphone I'm assuming you deployed a static website, correct?
would you mind sharing the link
Thank you

**Comment by treeder** [comment]
Same problem here. Works fine on an Android phone, but no decimal on Safari on iPhone.

**Comment by Freundschaft** [comment]
I can also confirm that the problem exists for safari on iphone in flutter web (beta)

**Comment by TahaTesser** [comment]
Hi @devfaheem @Freundschaft 
Are you still experiencing this issue, I see decimal on both platforms 

![Image from iOS](https://user-images.githubusercontent.com/48603081/91460403-6467e600-e8a5-11ea-964c-818e3c36732d.png)
![Screenshot_2020-08-27-20-23-10-98](https://user-images.githubusercontent.com/48603081/91460412-6631a980-e8a5-11ea-83d8-f8ca1b425347.jpg)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appTitle = 'Form Validation Demo';

    return MaterialApp(
      title: appTitle,
      home: Scaffold(
        appBar: AppBar(
          title: Text(appTitle),
        ),
        body: MyCustomForm(),
      ),
    );
  }
}

// Create a Form widget.
class MyCustomForm extends StatefulWidget {
  @override
  MyCustomFormState createState() {
    return MyCustomFormState();
  }
}

// Create a corresponding State class.
// This class holds data related to the form.
class MyCustomFormState extends State<MyCustomForm> {
  // Create a global key that uniquely identifies the Form widget
  // and allows validation of the form.
  //
  // Note: This is a GlobalKey<FormState>,
  // not a GlobalKey<MyCustomFormState>.
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    // Build a Form widget using the _formKey created above.
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          TextFormField(
            keyboardType: TextInputType.numberWithOptions(decimal: true),
            validator: (value) {
              if (value.isEmpty) {
                return 'Please enter some text';
              }
              return null;
            },
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 16.0),
            child: RaisedButton(
              onPressed: () {
                // Validate returns true if the form is valid, or false
                // otherwise.
                if (_formKey.currentState.validate()) {
                  // If the form is valid, display a Snackbar.
                  Scaffold.of(context)
                      .showSnackBar(SnackBar(content: Text('Processing Data')));
                }
              },
              child: Text('Submit'),
            ),
          ),
        ],
      ),
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.93, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-2.0.pre.93 at /Users/tahatesser/Code/flutter_master
    • Framework revision f35a8b7470 (9 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
