### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_localizations/flutter_localizations.dart'

### ISSUE THREAD

**Issue by RedasP** [flutter/flutter#53439]
## Steps to Reproduce

1. Create a new Flutter project using Android Studio 3.6.1
2. Add the following to the dependencies key in pubspec.yaml
```
flutter_localizations:
    sdk: flutter
```
3. Try to add the import to main.dart
`import 'package:flutter_localizations/flutter_localizations.dart';`

I expect the import to be successful and the app to build in the newly created project

I get compile time error on the import 
`Target of URI doesn't exist: 'package:flutter_localizations/flutter_localizations.dart'`
And `Undefined name:` errors on
```
MaterialApp(
      localizationsDelegates: [
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ]
```

Here are the details of my Android Studio

```
Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, io.flutter
```

<details>
  <summary>Logs</summary>

```
flutter analyze
```

  error - Target of URI doesn't exist: 'package:flutter_localizations/flutter_localizations.dart' - lib\main.dart:2:8 - uri_does_not_exist
  error - Undefined name 'GlobalWidgetsLocalizations' - lib\main.dart:12:9 - undefined_identifier
  error - Undefined name 'GlobalMaterialLocalizations' - lib\main.dart:13:9 - undefined_identifier
  error - Target of URI doesn't exist: 'package:watchman/main.dart' - test\widget_test.dart:11:8 - uri_does_not_exist
  error - The function 'MyApp' isn't defined - test\widget_test.dart:16:29 - undefined_function

```
flutter doctor -v
```

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17134.1365], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.40.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

</details>

**Comment by jonahwilliams** [comment]
This is most likely caused by either a typo in the pubspec or failing to run `flutter packages get`.

**Comment by RedasP** [comment]
I've followed https://flutter.dev/docs/development/accessibility-and-localization/internationalization, I'm sure that there's no typo and I've run `flutter packages get` multiple times

What's weird for me that I do these simple steps for a newly created project and it's failing to build.

**Comment by RedasP** [comment]
Found the cause of this. Don't know how or why, but when creating the new project, my default Android Studio's Flutter project location was chosen as a path into the existing Flutter project and it have created the new project as a subfolder to the existing one.
