### ISSUE TITLE
Gallery: AppBar transition into Tabs screen has red region

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#5344]
If you select the Tabs page in Gallery, the AppBar will expand to include headers for Left and Right tabs.  The expansion animation shows a red overflow region in the space where the tab headers will appear.

**Comment by abarth** [comment]
The red region is only in debug builds, so we probably don't need this for August.

**Comment by abarth** [comment]
I wonder if we should just remove these red overflow indicators.  In this situation, it's not really a bug.  It's intended.  /cc @Hixie

**Comment by sethladd** [comment]
Ah, thanks for clarifying.

Maybe another color instead of red for the cases where it's not a bug, but just feedback to the developer? Yellow perhaps?

**Comment by abarth** [comment]
When we added this indicator, we thought it would represent a bug.  I'm not sure it's actually been useful to anyone.  IMHO we should remove it rather than pick a new color.

**Comment by sethladd** [comment]
sgtm

**Comment by HansMuller** [comment]
I hope we don't unconditionally remove the debug-mode overflow indicators, I've often found them useful.

In this case you could interpret the red as an indication that the appbar should be wrapped in an overflowbox/clip since during the hero transition its size will temporarily be smaller than its intrinsic size.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/2387 is the bug regarding improving the overflow indicator.

**Comment by abarth** [comment]
> should be wrapped in an overflowbox/clip

I tried that, but it doesn't work because the app bar is expecting to get its height from above.  If you let it overflow, it doesn't know how tall to be.

**Comment by eseidelGoogle** [comment]
Is this still a bug we should track?  It still happens:

![tabs red mov](https://cloud.githubusercontent.com/assets/11857803/22601659/b3aa92ac-e9f4-11e6-9e49-32fa38f920ad.gif)

**Comment by HansMuller** [comment]
I think we should continue to track this. Either the new app  bar or the new heroes support (or both) should eliminate the problem.  And when they do.

**Comment by HansMuller** [comment]
This bug no longer occurs and the appbar/hero code paths involved don't exist anymore.
