### ISSUE TITLE
Multiple Navigators: When pushing a new route on a separate navigator textfield loses focus

### ISSUE THREAD

**Issue by hpoul** [flutter/flutter#53441]
## Steps to Reproduce

I have a Master/Detail view on a tablet/desktop app where i display two Navigators side by side. When the user is searching in the Master View (ie. text field is focused) it loses focus if i push another route into the second (detail) navigator.

I have created a simple example: https://dartpad.dartlang.org/aa423731de97aef1160c8b9b812ad1c9
setting the focus in the text field and typing a key will blur the text field.

```
              child: TextField(
                onChanged: (newValue) {
                  _navigatorKey.currentState.pushAndRemoveUntil(
                      MaterialPageRoute(builder: (_) => PageWithTextField()),
                      (route) => false);
                },
```

**Expected results:** Right (detail) navigator navigates to the new page, Focus remains in the text field on the left side.

**Actual results:** TextField loses focus, user cannot keep typing.

As far as I understand it, having multiple Navigators is perfectly fine? I am not 100% sure if it is supported behavior to have two navigators side by side?
Is there some way to push a route without losing focus on the textfield?

**Comment by iapicca** [comment]
Hi @hpoul 
I don't think there's anything wrong with multiple navigators,
but for my understanding losing focus has to be expected;
I'd interpret your issue more as feature request rather than a bug
if you agree with that.
Thank you

**Comment by hpoul** [comment]
@iapicca ok sure.. although I personally did not expect it, since the route i'm pushing does not contain any input elements with `autofocus = true`, so i did not expect that it would change the focus. But I guess I can understand why it's happening looking at the code..
thanks for taking a look.

**Comment by caseycrogers** [comment]
Chiming in, I'm facing this issue in my app and it's mind blowingly annoying. This behavior needs to be configurable. I have a textfield that updates a navigator as text is entered. Because navigator keeps stealing focus, this means that the keyboard keeps disappearing while the user is trying to type.

This needs to be configurable. eg add the following parameter to navigator: `bool takeFocus = true`.

@hpoul  did you ever find a work around to stop navigator from stealing focus?

**Comment by hpoul** [comment]
> did you ever find a work around to stop navigator from stealing focus?

@caseycrogers yeah, I've got a custom page route which simply force the focus back into the text field a frame after the push happened https://github.com/authpass/authpass/blob/6a019bb6bfeb4b990dc6d31f92d80f6b7d624f4d/authpass/lib/ui/screens/main_app_scaffold.dart#L61 ... Works surprisingly well.. to the point that I forgot that there is a workaround in place 😅

**Comment by caseycrogers** [comment]
> > did you ever find a work around to stop navigator from stealing focus?
> 
> @caseycrogers yeah, I've got a custom page route which simply force the focus back into the text field after the push happened https://github.com/authpass/authpass/blob/6a019bb6bfeb4b990dc6d31f92d80f6b7d624f4d/authpass/lib/ui/screens/main_app_scaffold.dart#L61 ... Works surprisingly well.. to the point that I forgot that there is a workaround in place 😅

Inspired by your workaround, I created the following which is a little bit simpler and may be more desirable in some cases (it prevents the route from ever taking focus instead of letting it take focus and then stealing focus back):
```dart
  @override
  TickerFuture didPush() {
    navigator!.focusScopeNode.canRequestFocus = false;
    final ret = super.didPush();
    // Could have a race condition because ret is just waiting on ticker future,
    // NOT waiting on it's callback on top of ticker future.
    // This code assumes that callbacks are called in FIFO order, this may not
    // be a valid assumption.
    ret.whenComplete(() {
      navigator!.focusScopeNode.canRequestFocus = true;
    }); // focusNode.requestFocus());
    return ret;
  }

  @override
  void didAdd() {
    navigator!.focusScopeNode.canRequestFocus = false;
    super.didAdd();
    // This probably has a race condition with `TransitionRoute.didAdd`. I don't
    // think there's a way around it because the former is waiting on an 
    // internal future that I have no access to.
    TickerFuture.complete().then((value) {
      return navigator!.focusScopeNode.canRequestFocus = true;
    });
  }```

If the Flutter team won't take my PR I guess we'll just have to live with the workarounds. That said I really don't trust them. They set off my race condition spidey sense.
