### ISSUE TITLE
Flutter appbundle not available in playstore

### ISSUE THREAD

**Issue by aldwnesx** [flutter/flutter#53459]
in defaultConfig, I added

```
 ndk {
        abiFilters 'armeabi-v7a','arm64-v8a'
     }

```

And then i run build appbundle.  After uploading to playstore, I cannot install it on my pixel 2 device. It says it does not support this device.
Why is this so?

**Comment by canewsin** [comment]
while producing appbundle you don't need to specify 
```
 ndk {
        abiFilters 'armeabi-v7a','arm64-v8a'
     }
```
you can remove this and try.

**Comment by aldwnesx** [comment]
> while producing appbundle you don't need to specify
> 
> ```
>  ndk {
>         abiFilters 'armeabi-v7a','arm64-v8a'
>      }
> ```
> 
> you can remove this and try.

Yeah I tried without specifying anything and it keeps crashing too...

**Comment by canewsin** [comment]
there is recent issue with app bundle try with `--no-shrink` option while producing.
`flutter build appbundle --no-shrink`

**Comment by aldwnesx** [comment]
> there is recent issue with app bundle try with `--no-shrink` option while producing.
> `flutter build appbundle --no-shrink`

Just tried it again.. keeps crashing..  I do not understand why.
On the same device I can install via debug version and works fine. When use release version it just crashes...


I tried with no shrink etc same issue, same error..

Could it be this library I am using?

https://github.com/X-dea/Flutter-VPN  

It specifies to use :

I tried with and without same issues

ndk {
                    if (project.hasProperty('target-platform')) {
                        if (project.property('target-platform') == 'android-arm,android-arm64')
                            abiFilters 'armeabi-v7a', 'arm64-v8a'
                        else if (project.property('target-platform') == 'android-arm')
                            abiFilters 'armeabi-v7a'
                        else if (project.property('target-platform') == 'android-arm64')
                            abiFilters 'arm64-v8a'
                    }
                }

**Comment by canewsin** [comment]
remove ndk tag and include those binaries manually

**Comment by aldwnesx** [comment]
> remove ndk tag and include those binaries manually

Thanks, can you point me in the direction for me to start? I don't know how to do that

**Comment by canewsin** [comment]
i think lib already doing, what I say for manually, just remove 
```
ndk {
        abiFilters 'armeabi-v7a','arm64-v8a'
     }
```

from build.gradle and try
`flutter build appbundle --no-shrink`

**Comment by canewsin** [comment]
provide crash log here, we cannot help without that furthur.

**Comment by iapicca** [comment]
Hi @aldwnesx 
is this the same situation described in these issues?
https://github.com/flutter/flutter/issues/53382#issuecomment-605381520
https://github.com/flutter/flutter/issues/53411#issuecomment-605385160
did you try following the suggested SO [question](https://stackoverflow.com/questions/47214125/google-play-store-release-issue)?
Thank you

**Comment by canewsin** [comment]
```
# TODO : Once Binaries are compiled with new NDK than NDK 21 RC1 
# we can remove below uncompressed property
# https://stackoverflow.com/a/55969995
android.bundle.enableUncompressedNativeLibs=false
```
could try adding it to gradle.properties and try
@aldwnesx

**Comment by aldwnesx** [comment]
> ```
> # TODO : Once Binaries are compiled with new NDK than NDK 21 RC1 
> # we can remove below uncompressed property
> # https://stackoverflow.com/a/55969995
> android.bundle.enableUncompressedNativeLibs=false
> ```
> 
> could try adding it to gradle.properties and try
> @aldwnesx

tried that crashing again...

I found out something:

if I run the release version (published to playstore internal test) on emulator, it gives that error and crash;
If I run it on actual pixel device,it doesn't crash but something isn't working.


Not sure why

**Comment by canewsin** [comment]
so, now it's available to pixel devices. see the Android Studio crash log and post here.

**Comment by aldwnesx** [comment]
im running from visual studio how do I get the log?

**Comment by aldwnesx** [comment]
i see someone has this issue recnetly also..


https://github.com/flutter/flutter/issues/53474

**Comment by canewsin** [comment]
try 
> adb logcat 

and open app, after app crash copy logcat and post it some where.

**Comment by iapicca** [comment]
Hi @aldwnesx 
did you try following the link reported [above](https://github.com/flutter/flutter/issues/53459#issuecomment-605834096)?
You may also provide the logs following @canewsin indications.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
