### ISSUE TITLE
Going to the AD by mistake when clicking on the navigation item

### ISSUE THREAD

**Issue by khalednatour** [flutter/flutter#53452]
Hi, I am facing issue on flutter app, going to the AD by mistake when clicking on the navigation item, Has anyone facing this problem? What is the best way to solve the problem?

video: https://drive.google.com/file/d/1KlsOpBnmUjFeCXxjGEX2L0rWFF5KhjQ1/view?usp=sharing

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
