### ISSUE TITLE
Scenario App Unit Tests run with a previous engine build

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#53455]
For some reason, `Scenario App Unit Tests` run with a previous engine build. For example, I added new tests, but they failed in the first run https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/4571. However, they passed in the second run https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/4572. 

Engine recipe: https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/flutter/engine.py#1122

cc @cyanglaz @gaaclarke

**Comment by digiter** [comment]
How do you know it was running with a previous engine build?

**Comment by blasten** [comment]
If you add a new test that relies on new API, the test will fail like the API wasn't there.
