### ISSUE TITLE
Soft keyboard doesn't appear on iPad when a mouse is connected

### ISSUE THREAD

**Issue by xster** [flutter/flutter#53453]
on iPadOS 13.4, if an USB mouse is connected, focusing on textfields don't bring up soft keyboards. Disconnect and tap again, soft keyboard appears.

**Comment by Kavantix** [comment]
Did you enable the software keyboard (and assistive touch) under the assistive touch accessibility menu?

**Comment by darshankawar** [comment]
Hello @xster 
I used wireless mouse to tap in textfield running in ipad 15.3 OS version, with which the soft keyboard opened properly.
Can you check if the reported behavior still persists at your end ?
