### ISSUE TITLE
Flutter tool should recommend `flutter upgrade` when that would fix issues

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#5346]
```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/mehmetf/flutter/flutter
    • Framework revision 7a9fe01cb9 (3 days ago), engine revision dedab3e6e7
```
From atom:

```
flutter run lib/main.dart (debug) • app/
Running lib/main.dart on Nexus 5...
--------- beginning of system
E/flutter : [ERROR:dart_error.cc(17)] Wrong script snapshot version, expected 'a00846c0d769e2b1b7b71e6f5039bbda' found 'a251fdac8f24f6596148a19e2d511fb6'
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : No top-level getter 'main' declared.
E/flutter : 
E/flutter : NoSuchMethodError: method not found: 'main'
E/flutter : Receiver: top-level
E/flutter : Arguments: [...]
E/flutter : #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:178)
E/flutter : #1      _getMainClosure (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/natives.dart:38)
```

On command line I get something completely different:

```
Thu Aug 11(11:27)|app$ flutter run
Running 'pub get' in app...                              
The pubspec for quiver 0.22.0 from path has version 0.23.0-dev.
```

and that's it.

**Comment by sethladd** [comment]
Thanks for the report!

I just changed to alpha branch, created a new app, and ran it on my 5X. It worked. So, I wonder if this is an issue that appears when you're trying to upgrade an existing app?

**Comment by sethladd** [comment]
@devoncarew is there something we can do to print more from `flutter run` in the case where apparently something isn't happy with versions? (Not sure how to repro this :(

**Comment by sethladd** [comment]
@mehmetf is it possible to share your pubspec.yaml for your project (in email if that works)

**Comment by abarth** [comment]
We should catch "Wrong script snapshot version" errors and recommend `flutter upgrade` as the solution.

**Comment by mehmetf** [comment]
+1 This could be extended to various pub errors as well.

**Comment by eseidelGoogle** [comment]
My understanding is we now run `pub get` as part of `flutter run`?  But there is likely still work we could do under this bug.

**Comment by Hixie** [comment]
I don't understand how we would know when to recommend `flutter upgrade`. Can you elaborate?

**Comment by zoechi** [comment]
`flutter doctor` now prints a big hint when a newer version is available at the current channel.

**Comment by jonahwilliams** [comment]
We now provide hints in flutter doctor when new versions are available. The incorrect snapshot error is a result of bugs in our build system, which are tracked here: https://github.com/flutter/flutter/issues/16604
