### ISSUE TITLE
Flutter video_player pub freezes since >16 flutter channels

### ISSUE THREAD

**Issue by janosdupai** [flutter/flutter#53463]
I use the video_player pub, and everything worked fine, but since the latest flutter upgrade, sometimes the video does not start, or stops during playback.

Sometimes it starts, but when I push the app in background, and open again, it is also freezing.

Another weird thing: if the app freezes, and I push the app to background and reactivate, it will work again smoothly...

When I changed back the channel to "beta", everything works fine. But at 'master', 'stable', 'dev' channels causes this weird error.

```console
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale hu-HU)
• Flutter version 1.15.17 at /Users/janosdupai/Developer/flutter
• Framework revision 2294d75 (2 weeks ago), 2020-03-07 00:28:38 +0900
• Engine revision 5aff311948
• Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/janosdupai/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 28.0.3
• ANDROID_HOME = /Users/janosdupai/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.3.1, Build version 11C504
• CocoaPods version 1.8.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 44.0.2
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
• MATCHmeeting • 00008020-0002242E1A29002E • ios • iOS 13.1.2
• iPhone 11 Pro Max • D441D7C8-ACB0-47BC-8CF6-A4A245BF352A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
• Chrome • chrome • web-javascript • Google Chrome 80.0.3987.149
• Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @janosdupai 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by janosdupai** [comment]
Hi @iapicca !
Thank you for your answer:

my pubspec.yaml:

> environment:
>   sdk: ">=2.1.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^0.1.2
>   fit_kit: ^1.1.1
>   http: ^0.12.0+2
>   provider: ^4.0.4
>   intl: 0.15.7
>   shared_preferences: ^0.5.3+4
>   flutter_sparkline: ^0.1.0
>   flutter_circular_slider: ^2.5.0
>   firebase_messaging: ^6.0.9
>   pie_chart: ^1.2.0
>   permission: ^0.1.3
>   percent_indicator: ^2.1.1+1
>   vibration: 1.2.4
>   image_picker: ^0.6.1+8
>   flutter_svg: ^0.17.3+1
>   audioplayers: ^0.14.2
>   video_player: ^0.10.8+1
>   sqflite: ^0.12.2+1
>   dio: any
>   path_provider: 1.6.5
>   wakelock: ^0.1.3+3
>   in_app_purchase: ^0.3.1+2
>   flutter_inapp_purchase: ^2.1.3
>   camera: ^0.5.7+4
>   flutter_ffmpeg: ^0.2.10
>   flare_flutter: ^1.5.4
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 

Sample of my video player:

At initalization I call thiis function and I start a Timer function:

  

> void startVideo()async {
>     var dir = await getApplicationDocumentsDirectory();
>     String p = "file.mp4";
>     _controller = VideoPlayerController.network(
>       'https://www.myvideos.com/videodrills/${widget.file}',
>     );
>     _initializeVideoPlayerFuture = _controller.initialize();
> 
>     _controller.setVolume(0);
>     _controller.setLooping(true);
>     _controller.play();
> 
>     if(!mounted){return;}
>   }

The timer part:

 

>  void startTimer(){
>     timer = Timer.periodic(Duration(seconds: 1), (Timer t) => updateTime());
>   }
> 
>   void updateTime(){
>     setState(() {
>       timeRemainging = _controller.value.duration.inSeconds - _controller.value.position.inSeconds;
>     });
>     if((blackedTime + 2) < _controller.value.position.inSeconds){
>       setState(() {
>         opa = 0;
>         blackedTime = -2;
>       });
>     }
>     try {
>       setState(() {
>         if(_controller.value != null){
>           time = _getTimeStringFromDouble(timeRemainging);
>         } else {
>           time = _getTimeStringFromDouble(0);
>         }
>         playing = _controller.value.isPlaying;
>       });
>     }catch(e){
>       print(e);
>     }
>   }

Container which contains the player.

> Container(
>               width: MediaQuery.of(context).size.width,
>               height: MediaQuery.of(context).size.height,
>               child: Transform.rotate(
>                 angle: !on? 0 : pi / 2,
>                 child: FutureBuilder(
>                   future: _initializeVideoPlayerFuture,
>                   builder: (context, snapshot) {
>                     if (snapshot.connectionState == ConnectionState.done) {
>                       // If the VideoPlayerController has finished initialization, use
>                       // the data it provides to limit the aspect ratio of the video.
>                       return AspectRatio(
>                         aspectRatio: _controller.value.aspectRatio,
>                         // Use the VideoPlayer widget to display the video.
>                         child: VideoPlayer(_controller),
>                       );
>                     } else {
>                       // If the VideoPlayerController is still initializing, show a
>                       // loading spinner.
>                       return Center(child: CircularProgressIndicator());
>                     }
>                   },
>                 ),
>               ),
>             )

**Comment by kaich** [comment]
I have the same problem for ios.

**Comment by TahaTesser** [comment]
Hi @janosdupai 

Code Sample snippets you provided are not complete
Running the official code sample, reproduces no issues

### Code Sample
```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.4 19E266, locale
    en-GB)
    • Flutter version 1.16.4-pre.33 at /Users/taha/Code/flutter_dev
    • Framework revision aee9e94c21 (2 days ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by ollydixon** [comment]
@iapicca also seeing this. On Android the video player has awful performance and freezes all the time.
