### ISSUE TITLE
Can you provide some components that satisfy the mimicry design?

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53473]
Can you provide some components that satisfy the mimicry design?
Like this:
![图片](https://user-images.githubusercontent.com/58280808/77818795-6f5cf580-7110-11ea-9873-73b285ce370d.png)

**Comment by canewsin** [comment]
try clay_containers library

**Comment by canewsin** [comment]
for further questions ask it on stackoverflow.

**Comment by gionchat** [comment]
> 
> 
> try clay_containers library

Thanks!
