### ISSUE TITLE
flutter android app crash after adding google-services.json and google-services plugin 4.3.3

### ISSUE THREAD

**Issue by Himanshu1986R** [flutter/flutter#53475]
in my flutter app 
we add `google-services.json` and `google-services` plugin 4.3.3 in my app .
```gradle
classpath 'com.android.tools.build:gradle:3.5.0'
kotlin_version = '1.3.50'
classpath 'com.google.gms:google-services:4.3.3'
```

and `firebase_crashlytics: ^0.1.3+3`

**Comment by iapicca** [comment]
Hi @Himanshu1986R 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
