### ISSUE TITLE
Flutter: new project doesn't exist in VS Code

### ISSUE THREAD

**Issue by lotfikadd** [flutter/flutter#53479]
I just downloaded latest version of VS Code and setup all the required packages for VS Code. and try to create my first web app not I can't able to found ### Flutter: New Web Project.
when i pressed Ctrl+Shift+P .its doesn't exist  
 Any one get same issue or can give help ? How can i fix it?

**Comment by iapicca** [comment]
Hi @lotfikadd 
could you please provide your `flutter doctor -v`,
also could you run as test `flutter create test_app --verbose`
Thank you

**Comment by lotfikadd** [comment]
hello @iapicca 
thanks so much for clarified this .

i understood that flutter team merge between flutter app and flutter web,
here is what they claims 'below'
 
This repository is no longer maintained.
As of September 10, 2019, Flutter for web development has fully moved to https://github.com/flutter/flutter. To build web apps using Flutter use the standard Flutter SDK.

**Comment by iapicca** [comment]
Hi @lotfikadd 
your statement is correct 
` Flutter for web development has fully moved to https://github.com/flutter/flutter. To build web apps using Flutter use the standard Flutter SDK.`
if you are still experiencing the issue could you follow the indication [above](https://github.com/flutter/flutter/issues/53479#issuecomment-605910028) end provide the output
thank you
