### ISSUE TITLE
[in_app_purchase] A purchase ends with error: "Cannot connect to iTunes Store" when user presses Cancel button

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#53488]
When the user presses Cancel button, the `purchaseUpdatedStream` gets a purchase with error: `{NSLocalizedDescription: Cannot connect to iTunes Store}`. I assume it shouldn't cause an error?

**Comment by VladyslavBondarenko** [comment]
Hi @agordeev 
are you using the last version `0.3.1+2`, right?

**Comment by agordeev** [comment]
@VladyslavBondarenko sorry, forgot to mention that. Yes, the version I'm using is `0.3.1+2`

**Comment by DavidKuennen** [comment]
Having the same problem and using `0.3.3`

**Comment by polym0rph** [comment]
I think it is the same issue as: #47738

**Comment by LHLL** [comment]
This is an error on the Apple side, not particular to this plugin:
https://forums.developer.apple.com/thread/128301
https://forums.developer.apple.com/thread/98763

**Comment by BeMacized** [comment]
I cannot seem to reproduce this issue anymore on `0.5.2`. An error is still published on the stream, but with `NSLocalizedFailureReason=Payment sheet cancelled`, which seems to me like the desired behaviour. 

I suspect this has already been resolved over time, so I'm closing this for now. If anyone is still running into issue, we can always reopen it.
