### ISSUE TITLE
I am using flutter image gallery plugin that fetches all the images of gallery but the issue occurs in android and ios is that when I load big image in grid view it does not load it but when I load small image it loads it.

### ISSUE THREAD

**Issue by ubaidsuhail** [flutter/flutter#53481]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ubaidsuhail** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.24.1)
[√] Connected device (1 available)

**Comment by ubaidsuhail** [comment]
I am stuck in this problem from couple of days so please help me if anyone has any solution.

**Comment by VladyslavBondarenko** [comment]
Hi @ubaidsuhail 
[Image_gallery](https://pub.dev/packages/image_gallery) is a 3rd party plugin, consider to open the issue in [the plugin's repository](https://github.com/flutter-devs/image_gallery/issues) or use another plugin instead.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ubaidsuhail** [comment]
No I don't think so it is a plugin issue because plugin show all the images
path .May be the issue is in grid view which can not handle big images

**Comment by VladyslavBondarenko** [comment]
@ubaidsuhail 
I tried 

<details>
 <summary>with that code</summary>

```
 import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GridView.count(
        crossAxisCount: 3,
        children: <Widget>[
          Image.asset('assets/img3.jpg'),
          Image.network(
              'http://wallpapersquad.net/pics/73-mac-os-sierra-color-splash-purple-wallpaper.jpg')
        ],
      ),
    );
  }
}
```

</details>

It loads [the image](http://wallpapersquad.net/pics/73-mac-os-sierra-color-splash-purple-wallpaper.jpg), although it's 6 MB and 5120 × 2880.
Tried with Android 10 emulator and iOS 13.4 simulator.

Could you provide code sample to reproduce your case without using 3rd party plugin? (together with images, if it's an issue with using from assets but not from network)

**Comment by ubaidsuhail** [comment]
I am basically fetching a file from gallery.Image.file is used .There are
lot of images that are fetching and small images are uploading but big
images are not
