### ISSUE TITLE
[proposal] First party Bluetooth support

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#53493]
I worked now a year with Bluetooth on flutter and used [flutter_blue](https://pub.dev/packages/flutter_blue) and [flutter_bluetooth_serial](https://pub.dev/packages/flutter_bluetooth_serial). flutter_blue is stale for quite a while and getting it to run on both platforms is close to a nightmare. flutter_bluetooth_serial supports only Bluetooth classic and only on Android. Because Bluetooth is such an important interface flutter should make it top priority to supply a high-quality package to boost the acceptance of flutter.

Summary:
Flutter should supply a Bluetooth package which supports:
- IOS and Android, Linux, Windows, MAC 
- Classic and BLE
- Good examples which run out of the Box with the latest stable release

**Comment by iapicca** [comment]
Hi @ride4sun 
while no first party plugin is currently available and
you don't find the current solutions available in the ecosystem satisfactory
please consider writing [platform specific](https://flutter.dev/docs/development/platform-integration/platform-channels) code that address your needs
Thank you

**Comment by ride4sun** [comment]
> Hi @ride4sun
> while no first-party plugin is currently available and
> you don't find the current solutions available in the ecosystem satisfactory
> please consider writing [platform specific](https://flutter.dev/docs/development/platform-integration/platform-channels) code that address your needs
> Thank you

Flutter provides many plugins like Camera etc. etc. but not for Bluetooth. Bluetooth has quite a bit of complexity. If a developer wants to support Bluetooth on both platforms he has to deal with technologies BLE/Classic. On top of the two platforms IOS/Android. I don't think it is very practical and for sure very timeconsuming. 

I also wondering how to handle Bluetooth on Windows/Linux/Mac. 

On top of all that some important Bluetooth libs are not well supported.:
https://github.com/pauldemarco/flutter_blue/issues/510

**Comment by ajayrathode** [comment]
Having proper support for the Bluetooth is great. I agree with @ride4sun . It is cumbersome to redo for platforms.

**Comment by marianhlavac** [comment]
In the meanwhile — for desperate people, like me, looking for working BLE functionality in Flutter, a few other Flutter packages emerged, some of them are flutter_blue forks, some of them are a complete rewrite. _Haven't tried any of them yet_, but it might be useful for someone:

* https://pub.dev/packages/flutter_reactive_ble
* https://pub.dev/packages/bluetooth
* https://pub.dev/packages/flutter_ble_lib

**Comment by ride4sun** [comment]
I tried  **flutter_bluetooth_serial** which works only with Bluetooth classic and on only on Android and **flutter_ble_lib** which works only on BLE but on Android and IOS.
I wrote an abstraction layer on top of those libraries and it works but it was a major pain in the rear especially because these platforms are not well maintained and there were many defects and quite often no responses to fix them.  There should be for sure a way better support for such a complex technology like Bluetooth is.

flutter_blue was by the way not working for me.

**Comment by ammaratef45** [comment]
I totally agree, I'm working on BLE code currently and it's so much work and many differences, having support for it would be super useful

**Comment by sbis04** [comment]
Bluetooth integration in Flutter using Platform Channel requires advanced knowledge in all three domains Flutter, Android and iOS, and I believe it is very difficult to pull off this individually. Also, Bluetooth is something which should also be accessible to amateur Flutter developers as well, but the current situation is not at all positive in that direction.

Personally, I have been involved with Bluetooth integration with Flutter for a pretty long time, used [flutter_bluetooth_serial](https://pub.dev/packages/flutter_bluetooth_serial) previously but its only supported for Android platform. Though [flutter_blue](https://pub.dev/packages/flutter_blue) supports both Android and iOS platform, but it comes with some caveats and limitations.

Seeing the situation of Bluetooth support for Flutter, I had written some articles which would help some beginners to get started (though I had used the `flutter_bluetooth_serial` package for that which only supports **Android**):

* [Flutter: Adding Bluetooth Functionality](https://medium.com/flutter-community/flutter-adding-bluetooth-functionality-1b9715ccc698) (initial one - pretty old)
* [Flutter: Creating an IoT based app to interact with any home electrical equipment](https://medium.com/flutter-community/flutter-creating-an-iot-based-app-to-interact-with-any-home-electrical-equipment-36d510b2478) (updated and improved version with latest plugin)

I have created one version of app, using a combination of both `flutter_bluetooth_serial ` & `flutter_blue ` plugin, with some additions in the native side using the platform channel, but this took a lot of effort and I am not in a situation to provide it as free, here's a summary to that: [Connect](https://www.souvikbiswas.com/connect).

Though the situation of Bluetooth support has improved a bit with a lot of community created plugins, but a first party Flutter Bluetooth plugin would be awesome. That being said, I would also suggest that we might take the good features of some of the community created plugins, try to incorporate the features they are lacking and submit PRs to those, that would be a good start for solving this issue for the time being.

**Comment by ride4sun** [comment]
> Though the situation of Bluetooth support has improved a bit with a lot of community created plugins, but a first party **Flutter Bluetooth plugin** would be awesome. That being said, I would also suggest that we might take the good features of some of the community created plugins, try to incorporate the features they are lacking and submit PRs to those, that would be a good start for solving this issue for the time being.

Yes, that could improve the situation but that also would mean that these packages are actively developed and that the developer accepts PR's. My experience is that they are often created to solve an immediate need and then left as is without much maintenance.  I wasted so much time on getting Bluetooth to reliable to work besides the Hello World app it is not even funny amymore.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, reflecting the expectation that this is not something that the Flutter team plans to implement.

In particular, on this point:

> Bluetooth integration in Flutter using Platform Channel requires advanced knowledge in all three domains Flutter, Android and iOS

I would argue that what it requires is not advanced Android and iOS knowledge, but significant knowledge of Bluetooth specifically. The Flutter team has no particular expertise in that area, so is not any better positioned to build such a plugin than the community.
