### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by bhouaoui** [flutter/flutter#53495]
hello !
im new in flutter so i have a problem when i start my app

this is the code 

import 'package:flutter/material.dart';

void main() => runApp(MaterialApp());

class MyFlutterApp extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
        title: "First App",
        home: Scaffold(
          appBar: AppBar(
              title: Text("Flutter app")
          ),
          body: Material(
            color: Colors.lightBlueAccent,
            child: Center(
              child: Text(
                "Hello World",
                textDirection: TextDirection.ltr,
                style: TextStyle(color: Colors.white, fontSize: 30),
              )
            )
          )
        )
    );
  }
}

and i receive those messages 

Performing hot restart...
Syncing files to device SM G920F...
Restarted application in 7 699ms.
I/flutter (12968): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12968): The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
I/flutter (12968): Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.
I/flutter (12968): Generators for routes are searched for in the following order:
I/flutter (12968):  1. For the "/" route, the "home" property, if non-null, is used.
I/flutter (12968):  2. Otherwise, the "routes" table is used, if it has an entry for the route.
I/flutter (12968):  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
I/flutter (12968): handled by "home" and "routes".
I/flutter (12968):  4. Finally if all else fails onUnknownRoute is called.
I/flutter (12968): Unfortunately, onUnknownRoute was not set.
I/flutter (12968): 
I/flutter (12968): The relevant error-causing widget was:
I/flutter (12968):   MaterialApp file:///C:/Users/admin/AndroidStudioProjects/flutter_app/lib/main.dart:3:23

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
