### ISSUE TITLE
get value from a class and use in other classes

### ISSUE THREAD

**Issue by Mehrbod2002** [flutter/flutter#53504]
Hello have good time,
i have coding problem , how can we use a object in a class and use it other classes ,
for example i made a class for register user in flutter app , and use it with controller and i want to use this controller in my another page with another class , it seems it cant 
i use firestore and i tried 
Firestore,intance.collection ...
but cant work and i want to use my register page objects and write in my user profile...

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by Mehrbod2002** [comment]
> Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

Why always you do this beside try to answer and another participate ? 
Just paste this code always 
It is not fair , if you don’t know better get out of this topic not try to close every time
