### ISSUE TITLE
How to ship iOS apps using flutter frontend vs. C/C++ backend to App Store?

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#53505]
## Goal

New to dart/flutter, I'm building an iOS app using flutter for frontend, and C/C++ for backend. AFAIK, they have to interoperate through FFI. I intend to submit it to iOS App Store.

I've been working on this for a while and only now do I realize that the FFI constraints that I'm not sure of could sabotage my project.

## Problems

The [Dart FFI sample on accessing C-struct](https://github.com/dart-lang/samples/tree/master/ffi/structs) works on macOS through dynamic linking for language binding. Now dynamic linking is [technically possible on iOS](https://stackoverflow.com/questions/48209855/xcode-9-no-option-to-create-dylib-project-ios), however, it's unclear to me how to ship an iOS app based on this architecture to AppStore, because dynamic linking is not allowed according to [Apple Guidelines](https://developer.apple.com/app-store/review/guidelines/) Section 2.5.2. 

> 2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the Application completely viewable and editable by the user.

Quite a few SO posts confirm this problem, such as:

 - https://stackoverflow.com/questions/7187649/can-i-use-dynamic-libraryshared-object-in-my-iphone-app
 - https://stackoverflow.com/questions/26504617/will-appstore-reviewers-allow-us-to-use-dynamic-library-in-ios8

## Questions

 - Does this say that I could never ship an app using this architecture to App Store?
 - Is it possible that I static link my C/C++ code into a single binary of a flutter app? Take Unity as an example, [their iOS plugin system wraps the plugin into the final native app](https://docs.unity3d.com/Manual/PluginsForIOS.html). If flutter has a similar mechanism, how?

**Comment by dcharkes** [comment]
You can use static linking: https://flutter.dev/docs/development/platform-integration/c-interop.

**Comment by iapicca** [comment]
Hi @kakyoism 
I see you SO [question](https://stackoverflow.com/questions/60910090/dart-flutter-how-to-ship-ios-apps-using-flutter-frontend-vs-c-c-backend-to-a) has been answered as well.

Please see https://flutter.dev/community for resources and asking questions like this.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
