### ISSUE TITLE
flutter consuming too much cpu

### ISSUE THREAD

**Issue by aoguz1** [flutter/flutter#53507]
hi, it consumes a lot of cpu while running my app , please help 

I'm on the stable channel

<img width="1275" alt="Ekran Resmi 2020-03-29 10 24 42" src="https://user-images.githubusercontent.com/34376691/77843643-cf52ab00-71a7-11ea-8998-82e053efc69a.png">

**Comment by jans-y** [comment]
It helps for me to completely stop current run and build it again. This is a long term issues from my experience.

I didn't notice such problem with Android emulator and therefore I am using it while running on my laptop battery.

**Comment by aoguz1** [comment]
when did i switch to another channel the problem is over , now  I'm on the stable channel .

I had this problem after the  MacOS Catalina and xcode updates on the stable channel

**Comment by iapicca** [comment]
Hi @aoguz1 
if I understand correctly you are experiencing the issue on `stable` channel,
but it appears to be fixed on `beta` and above, is that correct?
Thank you

**Comment by aoguz1** [comment]
yes I'm working on ` master` channel right now. I'm not having problems right now , but when I have problems when I switch on stable channel.

**Comment by chinmaygarde** [comment]
Flutter on simulators uses the software backend for rendering. This should not be the case on devices where the GPU is used. There are efforts to use Metal backend on simulators as well which are underway in https://github.com/flutter/flutter/issues/52358. Closing this issue as it is a symptom of a problem that will be fixed when the linked issue is addressed.
