### ISSUE TITLE
Flutter Workflow Error : Method not found 'BlocConsumer'

### ISSUE THREAD

**Issue by r0hnx** [flutter/flutter#53509]
```bash
Build and Release apk / Build APK
failed 5 minutes ago in 2m 58s
Search logs
  Set up job3s
  Run actions/checkout@v12s
  Run actions/setup-java@v17s
  Run subosito/flutter-action@v11m 9s
  Run flutter pub get16s
  Run flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi1m 21s
##[error]Process completed with exit code 1.
Run flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
Initializing gradle...                                              6.4s
Resolving dependencies...                                          53.2s
Running Gradle task 'assembleRelease'...                        


Compiler message:

lib/ui/coronaHome.dart:41:16: Error: Method not found: 'BlocConsumer'.

        child: BlocConsumer < CoronaBloc, CoronaState > (

               ^^^^^^^^^^^^

lib/ui/coronaHome.dart:41:16: Error: The method 'BlocConsumer' isn't defined for the class '_CoronaHomeState'.

 - '_CoronaHomeState' is from 'package:covid19/ui/coronaHome.dart' ('lib/ui/coronaHome.dart').

Try correcting the name to the name of an existing method, or defining a method named 'BlocConsumer'.

        child: BlocConsumer < CoronaBloc, CoronaState > (

               ^^^^^^^^^^^^
Compiler terminated unexpectedly.

Running Gradle task 'assembleRelease'...                           18.0s
Gradle task assembleRelease failed with exit code 1
##[error]Process completed with exit code 1.
 Create a Release APK0s
  Complete job
```

**Comment by iapicca** [comment]
Hi @r0hnx 
[flutter_bloc](https://pub.dev/packages/flutter_bloc) is a third party plugin
you may want to open an issue in the dedicated [github](https://github.com/felangel/bloc/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by r0hnx** [comment]
@iapicca I don't think the problem is flutter_bloc. The CI goes like this.

​on​: ​push​
​name​: ​Build and Release apk​
​jobs​:
  ​build​:
    ​name​: ​Build APK​
    ​runs-on​: ​ubuntu-latest​
    ​steps​:
    - ​uses​: ​actions/checkout@v1​
    - ​uses​: ​actions/setup-java@v1​
      ​with​:
        ​java-version​: ​'​12.x​'​
    - ​uses​: ​subosito/flutter-action@v1​
      ​with​:
        ​flutter-version​: ​'​1.9.1+hotfix.6​'​
    - ​run​: ​flutter pub get​
    - ​run​: ​flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi​
    - ​name​: ​Create a Release APK​
      ​uses​: ​ncipollo/release-action@v1​
      ​with​:
        ​artifacts​: ​"​build/app/outputs/apk/debug/*.apk​"​
        ​token​: ​${{ secrets.TOKEN }}

**Comment by r0hnx** [comment]
This change in my main.yml file seemed to fix the error

steps:
- uses: actions/checkout@v1
- uses: actions/setup-java@v1
  with:
    java-version: '12.x'
- uses: subosito/flutter-action@v1
  with:
    channel: 'stable' # or: 'dev' or 'beta'
- run: flutter pub get
- run: flutter test
- run: flutter build apk

**Comment by iapicca** [comment]
Hi @r0hnx 
I'm glad that you fix the error
thank you for letting me know
