### ISSUE TITLE
Just not able to run it at all.. 

### ISSUE THREAD

**Issue by VedantaServer** [flutter/flutter#53517]
## Steps to Reproduce
Update Android with everthing latest, SDK tools and everything else and then run Flutter Doctor to find this problem below...Spent the whole day just to setup things but nothing happened.

I am using windows 7 with Visual Studio Code.. If provide some help and assistance to get started on it..

D:\Research\Flutter\hello_world\hello_world>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
CreateProcessW failed 740
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.1.7600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.39.2)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      C:\Users\Rajesh\AppData\Local\Android\Sdk\platform-tools\adb.exe

**Comment by jonahwilliams** [comment]
Have you followed the instructions at https://flutter.dev/docs/get-started/install/windows ? The doctor message says that the Android SDK is not setup correctly

**Comment by VladyslavBondarenko** [comment]
@VedantaServer 
I hope you've solved the problem by

> check your Android SDK installation and ANDROID_HOME environment variable

Closing since long time without an answer

**Comment by VedantaServer** [comment]
Yes.. thank you

Regards,
Vedanta Tech Support Team
http://www.vedantaschoolerp.com - Resolve to support!!!
91-9899252291
Please like on Facebook http://www.facebook.com/vedantaerp for regular
updates.

Stop waiting for things to happen, go out and make them happen!!
