### ISSUE TITLE
Screen-flashing issue when switching apps in Android

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/flutter#53512]
I am facing screen-flashing kinda issue when switching between my flutter app and other apps, here is how it looks like:

screen video sample[ is this link ](https://imgur.com/a/U9le08x)as video for showing in best resolution 

I'm running the app in release mode, and I tested it in other phone, still the problem persist. 
in this sample code i don't have any database, future or etc

`flutter doctor -v` output:

```
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.15.17 at C:\flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\software\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = G:\software\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.40.0)
    • VS Code at C:\Users\mahdi\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • WAS LX1A • 2XJDU17C14006203 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment]
Hi @MahdiPishguy 
I see there's an open [issue](https://github.com/flutter/flutter/issues/52471) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by iapicca** [comment]
Hi @MahdiPishguy 
I see there's an open [issue](https://github.com/flutter/flutter/issues/34864
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
