### ISSUE TITLE
Flutter Increasing code cache capacity to 256KB with 

### ISSUE THREAD

**Issue by razanalsallumi** [flutter/flutter#53513]
I have this problem at run time in flutter :
![Screen Shot 2020-03-29 at 1 51 00 PM](https://user-images.githubusercontent.com/46599059/77847265-8e1cc400-71c4-11ea-8b49-414b6b73daa7.png)

my code: 
import 'package:chef/cart/splash.dart';
import 'package:chef/user_side/componets/tool/tool_item.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';

class CarttPage extends StatefulWidget {

  @override
  _CarttPage createState() => _CarttPage();
}

class _CarttPage extends State<CarttPage> {

  returnTotal(){
    DatabaseReference itemsRef = FirebaseDatabase.instance.reference().child("orders");
    itemsRef.once().then((DataSnapshot snap){

      var KEYS = snap.value.keys;
      var DATA = snap.value;

      itemsListCart.clear();

      for (var individualKey in KEYS){

        Price items= new Price
          (

          int.parse (DATA [individualKey]['price']),

        );
        itemsListCart.add(items);
      }
      setState(() {
        print('Length: $itemsList.length');
      });

    });

    double totalAmount = 0;
    for (int i =0; i < itemsListCart.length; i ++){
      totalAmount = totalAmount + itemsListCart[i].price ;
    }
    return totalAmount.toStringAsFixed(2);

  }
  List <Price> itemsListCart = [];
  List <Items> itemsList = [];
  DatabaseReference itemsRef = FirebaseDatabase.instance.reference().child("orders");
  @override
  void initState() {

    super.initState();

    itemsRef.once().then((DataSnapshot snap){

      var KEYS = snap.value.keys;
      var DATA = snap.value;
      itemsList.clear();

      for (var individualKey in KEYS){

        Items items= new Items
          (

          DATA [individualKey]['description'].toString(),
          DATA [individualKey]['image'].toString(),
          DATA [individualKey]['name'].toString(),
          DATA [individualKey]['price'].toString(),

        );
        itemsList.add(items);
      }
      setState(() {
        print('Length: $itemsList.length');
      });

    });

  }
  deleteMessage(name) {
    itemsRef.child('orders').child('name').remove();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(

        title: new Text ('My Cart '),
        backgroundColor: Colors.lightGreen,
      ),

      body: new Container(
        child: itemsList.length ==0 ? new Text('No avalibale'): new ListView.builder
          (
          itemCount: itemsList.length,
          itemBuilder: (_,index){
            return ItemUI(itemsList[index].image,
                itemsList[index].name,itemsList[index].price);
          },
        ),
      ),
      floatingActionButton:FloatingActionButton.extended(
        onPressed: ( ) async {

          Navigator.push(context, MaterialPageRoute(
              builder: (context) => new SplashPage()));
        },
        label: Text('Check Out '),
        backgroundColor: Colors.lightGreen,

      ) ,
      bottomNavigationBar: BottomAppBar(
        child: Text("${returnTotal()}", style: TextStyle(
          fontSize: 30,
          fontWeight: FontWeight.w800,

        ),),
        shape: CircularNotchedRectangle(),
        notchMargin: 10,

      ),
    );
  }
  var _firebaseRefPrice = FirebaseDatabase().reference().child('orders');
  sendPrice( double price) {
    _firebaseRefPrice.push().set({

      "price": (price as double),

    });
    totalPrice(price);
  }
    totalPrice (double price ){
    price += price;
    return price;
  }

  Widget ItemUI (String image, String name, String price){

    return new Container(
      padding: EdgeInsets.all(10),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[

       Image.network(
            "${image}",
            width: 100.0, height: 100.0,

          ),

          Text(
            "${name}",
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w800,
            ),
            textAlign: TextAlign.left,
          ),
          Text(
            "${price}",
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w800,
            ),
            textAlign: TextAlign.left,
          ),

          Text(
            "${price} SR",
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w300,
            ),
            textAlign: TextAlign.left,
          ),

          IconButton(
            icon: Icon(Icons.delete_forever),
            color: Colors.redAccent,
              onPressed: () {
                SplashPage();
              }
          ),

        ],

      ),

    );

  }

}

class Price {
  int price;

  Price(this.price );

}

**Comment by jonahwilliams** [comment]
This is not a bug, just Android being chatty
