### ISSUE TITLE
Gallery, Shrine: initial load of shrine should not shrink size of app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5352]
Open gallery, turn on slow-mo animations. Tap into shrine.

Notice how the height of the app bar shrinks a bit. However, the contents of the app bar (title, back button) stay in place.

Expected behavior is for a fixed size app bar during the initial load into Shrine.

**Comment by sethladd** [comment]
Admittedly, this effect is hard to notice when running at full speed. But, maybe reducing work here is a good thing.

**Comment by abarth** [comment]
This behavior is correct and will make more sense once we cross-fade the app bars.  The app bar starts out the size of the app bar on the previous page and animates to the new size.  If the old app bar was there fading out, you won't want the app bar to jump to the new size immediately.

**Comment by sethladd** [comment]
Ah, makes sense. Thanks!
