### ISSUE TITLE
[sentry] immutable Contexts API difficult to use

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#53522]
[sentry](https://pub.dev/packages/sentry) v3.0.1

I'm trying to use the newly introduced `Contexts`, and looks like all fields are `final`. This makes collecting `Device` info a little cumbersome, since some data may come from `device_info` plugin and is split into Android and iOS code, other comes from `Window` and is dynamic.

I.e. I can't easily split the code collecting this information into blocks, because all values have to be provided to a single constructor call:

```dart
final deviceContext = Device(
  // here's where complexity is coming from: too much Elvis.
  name: isAndroid ? android.name : isIos? ios.name : null,
  // a few lines like the one above

  // now some shared parameters, too
  resolution: '${window.height}x${window.width}',
  ...
)
```

What I want instead is

```
// set shared parameters first
final deviceContext = Device(resolution: ...)
if (isAndroid) {
  deviceContext..name = android.name
    ..model = android.model
    ...
} else if (isIos) ...
```

Alternatively, if `Device` must be immutable, a copy constructor with a list of optional updates would work, too.

**Comment by marandaneto** [comment]
@dotdoom if using https://pub.dev/packages/sentry_flutter Device context is added automatically for Android and iOS, you'd not need to bother about that.

**Comment by dotdoom** [comment]
@marandaneto thanks, this package is new (couple months?) and I'm still looking into what it's missing.

**Comment by marandaneto** [comment]
yeah, it's GA for a month or so, but the new API allows you to copy using `copyWith` and replace the instance with the new object as they are immutable.

https://docs.sentry.io/platforms/flutter/enriching-events/context/

**Comment by bruno-garcia** [comment]
This has been out since verson 4.0.0
Version 5.0.0 includes Null Safety now too.
