### ISSUE TITLE
Flutter for Web. Unable to obtain cookie from response header

### ISSUE THREAD

**Issue by SeasonLeee** [flutter/flutter#53524]
## Steps to Reproduce

By using http package `http 0.12.0+4` to create a simple http.get from server

Trying to get the 'set-cookie' from the response header

But nothing we can obtain...

**Expected results:** 

It's available to get 'set-cookie' from response header on Android.

**Actual results:** 

When I switch to web edition, no more cookie...

(because I was doing a test demo at my desktop at work, so I can't provide any screenshot at the moment, might fill in later...)

**Comment by jonahwilliams** [comment]
You might have better luck filling an issue https://github.com/dart-lang/http . FWIW I do not believe you can set arbitrary headers from the browser in any language

**Comment by SeasonLeee** [comment]
@jonahwilliams Yes, you are right! In my last demo I made some mistakes... sorry for the wrong issue...
