### ISSUE TITLE
[sentry] screenDensity has to be a floating point number

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#53521]
[sentry](https://pub.dev/packages/sentry) v3.0.1

Right now when I try to use `Device` context `screenDensity` parameter, I get the following error on sentry.io:

```
There was 1 error encountered while processing this event
contexts.device.screen_density: Discarded invalid value
```

Reason | expected a floating point number
-- | --
Value | 2.625

**Comment by Zazo032** [comment]
You should post those issues on the plugins repo: https://github.com/flutter/sentry
