### ISSUE TITLE
Flutter  pub get taking long time with OS Error 

### ISSUE THREAD

**Issue by mamunur34** [flutter/flutter#53536]
I am using all the latest versions of flutter dart SDK and packages. For 2 days I am facing the error: 
`OS Error: The semaphore timeout period has expired.
, errno = 121, address = storage.googleapis.com, port = 3318`

The internet connection is very good. I have changed the provider for testing. Googled many of the answers and it seems this error has arisen newly. 

When we add anything in dependency it requires the pub to get command, it runs for 15 minutes and brings with that error. 

For testing I have created a brand new project, and here is the yaml file : 
`name: flutterapptest
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
`
Any idea?

**Comment by jonahwilliams** [comment]
You might have better luck filling an issue here: https://github.com/dart-lang/pub/issues
