### ISSUE TITLE
Render PlatformViews without VirtualDisplay

### ISSUE THREAD

**Issue by t-artikov** [flutter/flutter#53533]
Flutter currently uses VirtualDisplay to render PlatformViews to textures and compose it with UI.
This approach seems to have significant overhead and leads to poor performance (https://github.com/flutter/flutter/issues/53532).

Instead, I tried to put Android View under transparent FlutterView, and it gives better result.
https://github.com/t-artikov/flutter_two_surfaces_test

In this case, Android View is not integrated into the widget hierarchy, it is placed below or above the Flutter surface, but when it is acceptable, this approach is preferred.
I suggest adding an option to PlatformView that enables this mode.

**Comment by mklim** [comment]
Not sure if any work is being done on this currently, but we have looked into trying to move away from Virtual Displays in the past. See [Android Platform Views](https://github.com/flutter/flutter/wiki/Android-Platform-Views#are-there-any-alternatives) for some more context.

**Comment by t-artikov** [comment]
Thanks!
Shouldn't the Flutter team implement this approach, despite the lack of rendering synchronization (https://flutter.dev/go/nshc)? Low performance of VirtualDisplay is a more significant problem, IMHO.

**Comment by t-artikov** [comment]
https://github.com/flutter/flutter/issues/53989 seems to be a blocker of this approach.

**Comment by rs5173** [comment]
I think this is a tryable method.

1. Declare a FlutterWidget, when it is created, create a NativeView with the same position and size on the native side, and let it float on the FlutterView
2. When the size or position of FlutterWidget changes, notify NativeView to make the same change
3. Before Flutter opens a new page, replace FlutterView with a screenshot of NativeView, and temporarily hide NativeView, then display NativeView after returning
4. Before the current page is closed, replace FlutterView with a screenshot of NativeView, hide and destroy NativeView

**Comment by MagicPoulp** [comment]
Perhaps that the Hybrid composition added in Flutter 1.20 solves this problem?
Or did you find that a transparent FlutterView offers better performance?

**Comment by t-artikov** [comment]
@MagicPoulp 
Thanks! It is useful to know that the situation is opposite on some devices.
I have tried the hybrid composition and found its performance not perfect too.
See https://github.com/flutter/flutter/issues/62303 for more info.

**Comment by MagicPoulp** [comment]
I answered in the other ticket.

**Comment by johnmccutchan** [comment]
Android Platform Views support rendering without VirtualDisplay or Hybrid Composition now.

Closing this out.
