### ISSUE TITLE
Gallery, Shrine: I can make the app bar spin

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5353]
You have to be fast, or, turn on slow-mo animations.

If you have slow-mo animations turned on, you can tap into shrine. Then, tap back. As soon as you see the word "Shrine" emerge, tap on it, before the shrine app finishes transitioning off screen.

You will see the app bar spin.

If you are fast enough, you can trigger this even with slow-mo turned off.

**Comment by sethladd** [comment]
Video in action: https://youtu.be/jhuJD4rAwHY

**Comment by Hixie** [comment]
That's the hero logic not knowing where to put the toolbar.

**Comment by Hixie** [comment]
Are we putting a key on the toolbar or something?

**Comment by sethladd** [comment]
> Are we putting a key on the toolbar or something?

@HansMuller might know?

**Comment by eseidelGoogle** [comment]
Repro'd just now.  That's totally a delightful detail, not a bug, right? :D

**Comment by HansMuller** [comment]
It's a delightful artifact of the current Hero system and the fact that the AppBar is currently a Hero. Upcoming changes in Heroes and AppBars may require restoring this behavior as an easter egg.

**Comment by HansMuller** [comment]
This delightful code path doesn't exist anymore, see https://github.com/flutter/flutter/pull/8112
