### ISSUE TITLE
Image resources introduced by project Flutter cannot be previewed on the left.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53544]
Image resources introduced by project Flutter cannot be previewed on the left.
Here's the Android project:
![图片](https://user-images.githubusercontent.com/58280808/77866562-2e76f500-7266-11ea-810d-d819979ef0d0.png)

**Comment by TahaTesser** [comment]
Hi @gionchat 
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter)
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it. 
Thank you for your understanding
