### ISSUE TITLE
Inner Shadow

### ISSUE THREAD

**Issue by shallx** [flutter/flutter#53548]
#31059  Use case

While trying to develop Neumorphic design, I did not find inner shadow feature in BoxShadow(). Without it, complex neumorphic design is not possible.
## Proposal

Can u guys add InnerShadow in BoxShadow() property?(Shadow Inside). This feature should come with built in library feature. Painting an InnerShadow from scratch is time consuming and not worthwhile.

**Comment by iapicca** [comment]
Hi @shallx 
I see there's an open [issue](https://github.com/flutter/flutter/issues/52999) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
