### ISSUE TITLE
`flutter build --release` includes JIT-related files on macOS (off a dirty build folder)

### ISSUE THREAD

**Issue by filleduchaos** [flutter/flutter#53546]
I am not sure if this is the case on other desktop platforms, but if you build a release version of a Flutter app for macOS without cleaning the build directory first, a couple of JIT-specific files (`kernel_blob.bin` and `isolate_snapshot_data`) are included in the release `.app` (bloating it by about ~30MB in a minimal app)

## Steps to Reproduce

```bash
$ flutter create bug && cd bug
$ flutter run -d macos # you can quit after the application launches
$ flutter build macos --release
```
Inspect the .app file at `bug/build/macos/Build/Products/Release/bug`

**Expected results:** `bug` should be ~35MB (the size you get from a clean build)

**Actual results:** `bug` is ~65MB, and further inspection reveals `Contents/Frameworks/App.framework/.../flutter_assets/isolate_snapshot_data` and `Contents/Frameworks/App.framework/.../flutter_assets/kernel_blob.bin` within `bug`

<details>
  <summary>Logs</summary>

```bash
$ flutter doctor -v

[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.16.3 at /Users/filleduchaos/flutter
    • Framework revision be3a4b37b3 (3 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)
...
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1
...

• No issues found!
```
</details>

**Comment by filleduchaos** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
Thanks @filleduchaos 

The problem is that the dependency tracking doesn't work when multiple builds output to the same folder. Since Gradle otherwise handles this on the Android side of things I let my guard down a bit

The solution here is to compare the output folder with the complete known set of outputs from the build, and surgically remove any stragglers. 

(For subsequent builds of the same configuration, this already happens)
