### ISSUE TITLE
Difficult to tell what version of Dart we embed into engine from `flutter --version`

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5355]
We'd like to report the version of Dart we embed into the engine when the user runs `flutter --version`.

**Comment by sethladd** [comment]
cc @pq

**Comment by Hixie** [comment]
We should be able to get this by running a short Dart program in the host sky_shell (same thing used by `flutter test`).

**Comment by pq** [comment]
@Hixie 👍 

Now we just have to decide if this is actually what we want. 😄 

Here's the kind of output we can get by accessing `Platform.version` from within a Dart app run in `sky_shell`:
```
1.19.0-edge.cfdd6ee5cc6a7af56ead91190af8f8dcc33e82ea
```

@sethladd : is this useful?

Here's how version info incorporating it might look:

```
[~/src/git/clones/flutter] (master) $ flutter --version
Flutter on channel master (from git@github.com:pq/flutter.git)
Framework revision 529c25caa8 (18 hours ago); engine revision 1493032690
Last commit on framework: 2016-08-11 16:51:46
Flutter tools using Dart version 1.19.0-dev.5.0
Flutter engine using Dart version 1.19.0-edge.cfdd6ee5cc6a7af56ead91190af8f8dcc33e82ea
```

**Comment by sethladd** [comment]
> is this useful?

It's better than nothing. But the number doesn't mean much to developers, because they can't correlate that to some release of Dart (there's no changelog for a git hash).

Going back to the problem we're trying to solve: how can a user know if a certain thing/feature from Dart is available in their Flutter app?

The developer previously didn't have an easy way to find out what version of Dart is in their Flutter. With your PR, they have a bit of info that can help them.

Output lgtm

**Comment by chinmaygarde** [comment]
That string is obtained from this template https://github.com/dart-lang/sdk/blob/master/runtime/vm/version_in.cc#L30.

Flutter's build instantiates that. We can put anything we want in there and it will appear as part of `Platform.version`.

**Comment by pq** [comment]
@devoncarew does your latest tweak address this?

**Comment by devoncarew** [comment]
It doesn't. It didn't sound like the commit hash of the engine would be super useful to developers. I don't think they think about the engine being versioned separately from flutter - they probably think of it as one unit.

Perhaps maintaining a changelog would help here? Or some changes to what a release of flutter means?

**Comment by pq** [comment]
👍 

@sethladd : what would be your ideal here?

**Comment by sethladd** [comment]
Perhaps instead of asking "Does Flutter's copy of Dart have feature X", the right question is actually "Does Flutter have feature X".

@pq in the meantime, it should be sufficient to print `1.19.0-edge.cfdd6ee5cc6a7af56ead91190af8f8dcc33e82ea` for a version of Dart embedded into the engine. That gives people who are looking for a hint a sufficient hint.

**Comment by Hixie** [comment]
Today we output:
```
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 68ebf64525 (2 hours ago) • 2017-01-30 21:17:29
Engine • revision 9de4d1530b
Tools • Dart 1.22.0-dev.9.1
```

I think it would be fine to add the Dart version to the Engine line, but it doesn't seem particularly critical since it'll just duplicate the engine hash. I suggest we close this as is.

**Comment by sethladd** [comment]
Curious, why would the Dart version embedded into the engine have the same hash as the engine?

**Comment by chinmaygarde** [comment]
The engine and Dart versions are distinct. Currently, there isn't a way to
tell the Dart version associated with the engine without looking at the
DEPS for the engine at a it's particular version. But I am sure we can
embed this information in all builds of the engine and make it accessible
via a command line flag and via observatory.

**Comment by Hixie** [comment]
@sethladd Each version of the engine has a specific version of Dart associated with it (as listed in the DEPS file). If you change the version of Dart, then it forcibly changes the version of the engine (assuming you're building something that got committed). We could show the version of Dart as well, if we are worried about people running custom builds, but then they could also be running hacked versions of Dart, and this won't help detect that...

@chinmaygarde Platform.version already surfaces this right? So we could just use that as suggested above, if we want to show something.

**Comment by sethladd** [comment]
Showing:

`Engine • revision 9de4d1530b (Dart 1.19.0-edge.cfdd6ee5cc6a7af56ead91190af8f8dcc33e82ea)`

Should be sufficient. It answers the question, "what version of Dart is the engine using?" in a way that someone can take that info and cross-reference with Dart.

**Comment by eseidelGoogle** [comment]
I tried to see if we could just read it from Platform.version inside sky_shell, no dice:
```
eseidel@eseidel-macbookpro /src/flutter %./bin/cache/artifacts/engine/darwin-x64/sky_shell foo.dart                                                       [/src/flutter]
2017-02-03 09:59:10.598 sky_shell[82100:9354196] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
eseidel@eseidel-macbookpro /src/flutter %cat foo.dart                                                                                                     [/src/flutter]
import 'dart:io';
void main() {
  print(Platform.version);
}
```

**Comment by Hixie** [comment]
It's not clear that we truly need this. Closing for now. If anyone still needs this, please submit a PR that does it. :-)
