### ISSUE TITLE
Request: Add option to not open keyboard on TextField focus

### ISSUE THREAD

**Issue by jaimyu** [flutter/flutter#53556]

**Comment by iapicca** [comment]
Hi @jaimyu 
This [issue](https://github.com/flutter/flutter/issues/16863) seems to address and resolve the case you described.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by jaimyu** [comment]
> Hi @jaimyu
> This [issue](https://github.com/flutter/flutter/issues/16863) seems to address and resolve the case you described.
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

 I need it to get focus when tapped but not open a keyboard.
