### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#53559]
There are a bunch of other issues for this error but all are closed with no solution.

My Flutter app has recently started having this error when trying to create an iOS release build. I believe this is related to adding more dependencies.

## Steps to Reproduce

1. Build Flutter app for iOS in release mode
2. The build fails with the error: 

```
 error: unable to spawn process '/bin/sh' (Argument list too long) (in target 'Runner' from project 'Runner')
```

**Comment by TahaTesser** [comment]
Hi @athornz 
can you please provide your `flutter doctor -v` and `flutter build ios --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by athornz** [comment]
Unfortunately, this is not the kind of issue where a small sample will reproduce. It seems to happen when projects get quite large with many dependencies.

I have managed to find a fix that doesn’t seem to break anything else - in xcode under build settings -> header search paths, delete all the header search paths.

**Comment by iapicca** [comment]
Hi @athornz 
I'm glad that you fixed the issue,
thank you for letting us know

**Comment by athornz** [comment]
I don't believe this should be closed. The fix is a work around and others
will come across the same issue.

**Comment by iapicca** [comment]
Hi @athornz 
I've reopened the issue for now
to be actable it would be useful if you could post the info requested [above](https://github.com/flutter/flutter/issues/53559#issuecomment-605841061)
thank you

**Comment by mockturtl** [comment]
related: https://github.com/flutter/flutter/issues/48623

**Comment by mockturtl** [comment]
> I have managed to find a fix that doesn’t seem to break anything else - in xcode under build settings -> header search paths, delete all the header search paths.

for me:

lexical or preprocessor issue: Firebase/Firebase.h file not found
parse issue: could not build module firebase_ml_vision

**Comment by SergeShkurko** [comment]
For me a similar problem appears due to https://github.com/FirebaseExtended/flutterfire/issues/2296

**Comment by SergeShkurko** [comment]
@mockturtl try it: https://github.com/FirebaseExtended/flutterfire/issues/2084#issuecomment-592465770

**Comment by Strain-solutions** [comment]
Hi - I encountered this today.  Exactly the same error on a validation build.

Flutter Doctor -v shows no errors anywhere.

```
iMac:ios nick$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.17.5 at /Users/nick/developer/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nick/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Nokia 2 3  • PT99621AA1A42004328                      • android-arm • Android 10 (API 29)
    • Mr stewart • 840b6fd36ec66427ead47b6b8c2866da05815934 • ios         • iOS 12.0
    • iPhone 8   • 6D72C7B9-E698-400A-8CCA-81ED13C97781     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
```


I can't post all of `flutter build ios --verbose` as its pages long and my terminal output runs out of space.  The fail at the end however is

   PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/nick/Library/Developer/Xcode/DerivedData/Runner-chvsqtctwwmqhbasyzpvwahktrlf/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Script-E1CDAB5B4A11AA07312CAE7A.sh (in target 'Runner' from project 'Runner')
                            cd /Users/nick/AndroidStudioProjects/jitabug/ios
                            /bin/sh -c /Users/nick/Library/Developer/Xcode/DerivedData/Runner-chvsqtctwwmqhbasyzpvwahktrlf/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Script-E1CDAB5B4A11AA07312CAE7A.sh
                        error: unable to spawn process '/bin/sh' (Argument list too long) (in target 'Runner' from project 'Runner')


However in Xcode I can see build settings -> header search paths and there are 3 listed but there is no obvious way to delete them?

any help appreciated.

**Comment by Strain-solutions** [comment]
Update to the above building using legacy settings in Xcode fixed it for me without any other modifications.  My app included firestore, and apparently this is a good solution for those situations.

https://stackoverflow.com/questions/53226087/error-unable-to-spawn-process-argument-list-too-long-in-xcode-build

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
