### ISSUE TITLE
Can't change shape of BottomSheet when using Scaffold

### ISSUE THREAD

**Issue by yolofy** [flutter/flutter#53563]
## Steps to Reproduce
```
...
 var bottomSheetWidget =  BottomSheet(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(10.0)),
        ),

      onClosing: () {},
      builder: (context) =>
          ReportSheet(
            model: model,
            feedback: onDialogFeedback,
            ),
      );

 return Scaffold(
              body: bodyWidget,
              bottomNavigationBar: bottomNavigation,
              bottomSheet: bottomSheetWidget
              ));
...
```

**Expected results:**
Rounded corners

**Actual results:** 
Angular corners

**Analysis**
Scaffold creates it's own BottomSheet even if you use the bottomSheet property. When using this property, the background can't be set. It can only be set when using the showBottomSheet function. 

Calls _buildBottomSheet without background:
https://github.com/flutter/flutter/blob/e4a61dfdea8dc55e6665abefb00be9575de4d06c/packages/flutter/lib/src/material/scaffold.dart#L1797-L1808

Calls _buildBottomSheet with background:
https://github.com/flutter/flutter/blob/e4a61dfdea8dc55e6665abefb00be9575de4d06c/packages/flutter/lib/src/material/scaffold.dart#L2028-L2037

**Comment by TahaTesser** [comment]
Hi @yolofy 
### Check out this code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var bottomSheetWidget = BottomSheet(
      backgroundColor: Colors.blue[300],
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(10.0)),
      ),
      onClosing: () {},
      builder: (context) => Container(
        height: 200,
      ),
    );

    return Scaffold(
      bottomSheet: bottomSheetWidget,
      body: Center(
          child: RaisedButton(
        child: Text('showBottomSheet'),
        onPressed: () {
          _newTaskModalBottomSheet(context);
        },
      )),
      floatingActionButton: new FloatingActionButton(
        onPressed: () {},
        child: new Icon(Icons.add),
      ),
    );
  }

  void _newTaskModalBottomSheet(context) {
    showModalBottomSheet(
        context: context,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(10.0)),
        ),
        builder: (BuildContext bc) {
          return Container(
            child: new Wrap(
              children: <Widget>[
                new ListTile(
                    leading: new Icon(Icons.music_note),
                    title: new Text('Music'),
                    onTap: () => {}),
                new ListTile(
                  leading: new Icon(Icons.videocam),
                  title: new Text('Video'),
                  onTap: () => {},
                ),
              ],
            ),
          );
        });
  }
}
```

it does produce rounded corner when using both options
 Does this solves your issue?

if not, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by JPGarCar** [comment]
I seem to have a similar issue, but with the showModalBottomSheet() function. I am trying to set round borders but I get regular sharp corners. Code is as follows: 

`GestureDetector(
                        onTap: () {
                          showModalBottomSheet(
                              context: context,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.vertical(
                                  top: Radius.circular(20),
                                ),
                              ),
                              builder: (context) {
                                return NewUserScreen();
                              });
                        },`

and 

`Container(
      padding: EdgeInsets.only(top: 10, right: 10, left: 10, bottom: 20),
      color: k_whiteColor,
      child: Column(
        children: [
          Row(
            children: [
              Text(
                'Regresar',
                style: TextStyle(
                  color: k_redColor,
                ),
              )
            ],
          )
        ],
      ),
    );`

Flutter doctor gives me an all good status, no errors at all.
