### ISSUE TITLE
Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.

### ISSUE THREAD

**Issue by bineanzhou** [flutter/flutter#53574]
启动报错 (launch error)

```
Installing build/app/outputs/apk/app.apk...
E/flutter ( 2799): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
E/flutter ( 2799): [ERROR:flutter/shell/common/engine.cc(198)] Could not prepare to run the isolate.
E/flutter ( 2799): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate.
E/flutter ( 2799): [ERROR:flutter/shell/common/shell.cc(437)] Could not launch engine with configuration.
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/zhoubin/work/flutter/sdk/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

**Comment by VladyslavBondarenko** [comment]
Hi @bineanzhou 
are you experiencing this with the same project https://github.com/flutter/flutter/issues/53333?

**Comment by bineanzhou** [comment]
> Hi @bineanzhou
> are you experiencing this with the same project #53333?

yes

**Comment by xster** [comment]
Any reproduction steps for this issue?

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
