### ISSUE TITLE
how can use native android code with flutter

### ISSUE THREAD

**Issue by walide67** [flutter/flutter#53575]
i want to creat a forground service to track user location for i get [ kotlin native code from github](https://github.com/Rostyk/LocationTrackingWhenForceKilled) and i want to setup it in my flutter project 
can you tell me please for the steps 
note : i triying with all flutter plugins but not working

**Comment by VladyslavBondarenko** [comment]
Hi @walide67 
Take a look at [AndroidView](https://api.flutter.dev/flutter/widgets/AndroidView-class.html), https://github.com/flutter/flutter/wiki/Android-Platform-Views and other docs you can find.
Please see https://flutter.dev/community for resources and asking questions like this.
Closing, as this isn't an issue with Flutter,
Thank you
