### ISSUE TITLE
Flutter giving wrong error message!

### ISSUE THREAD

**Issue by ShardulNalegave** [flutter/flutter#53578]
Hi, I just created a new Flutter Web project and saw this weird error.

I had a variable called `primaryColor` of type `MaterialColor`. I set the value of my theme's `primaryColor` to the variable `primaryColor`.
Then I got the following error:-

````
Expected a value of type `MaterialColor`, but got one of type `Color`
````

What makes this weird is that my variable was already of type `MaterialColor`!
After some help from VS Code I saw that the property `primaryColor` on `ThemeData` actually requires a value of type `Color`.

So, the error actually should be:-
````
Expected a value of type `Color`, but got one of type `MaterialColor`
````

And after I changed my variable's type the error went out!
I know this is not a big bug but it might get very confusing for beginners.

**Comment by ShardulNalegave** [comment]
The complete code:-

### `main.dart` file
````dart


// Imports
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:project_server/Home.dart';
import 'package:project_server/utils.dart';

// Main function
void main() { ... }

// Application Class
class Application extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Project Server',
      theme: ThemeData(
        primaryColor: primaryColor,
        accentColor: accentColor,
        textTheme: GoogleFonts.montserratTextTheme(
          Theme.of(context).textTheme
        )
      ),
      debugShowCheckedModeBanner: false,
      home: HomePage()
    );
  }

}

````

### `utils.dart` file
````dart


// Imports
import 'package:flutter/material.dart';

// Colors
final Color accentColor = Colors.teal[800];
final Color primaryColor = Colors.white;
final Color textColor = Colors.grey[900];

````

### `Home.dart` file
Consists on Home Page code. No use of `Color` or `MaterialColor` here.

**Comment by VladyslavBondarenko** [comment]
Hi @ShardulNalegave 
what flutter version do you use?
I can't see the error 
<details>
 <summary>with your code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(Application());

class Application extends StatelessWidget {

  final Color accentColor = Colors.teal[800];
  final Color primaryColor = Colors.white;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Project Server',
        theme: ThemeData(
            primaryColor: primaryColor,
            accentColor: accentColor,
        ),
        debugShowCheckedModeBanner: false,
        home: Container(),
    );
  }
}
```

</details>

And when I try to change `final Color primaryColor = Colors.white;` to `final MaterialColor primaryColor = Colors.white;` I have
```
Unhandled Exception: type 'Color' is not a subtype of type 'MaterialColor'
```

**Comment by ShardulNalegave** [comment]
Hi,
My flutter version is **1.15.17**

**Check the following screenshots,**
In the first one the variables have type `Color` and in the second one the variables have type `MaterialColor`. The error is displayed after changing the code.

![Screenshot 30-03-2020 11 09 12 PM](https://user-images.githubusercontent.com/32868624/77944040-d8dd2f80-72db-11ea-805f-891981819173.png)
![Screenshot 30-03-2020 11 10 39 PM](https://user-images.githubusercontent.com/32868624/77944047-db3f8980-72db-11ea-96f7-794e0e551861.png)

**Comment by mhmdanas** [comment]
Try changing this:
```dart
final MaterialColor accentColor = Colors.teal[800];
final MaterialColor primaryColor = Colors.white;
final MaterialColor textColor = Colors.grey[900];
```
to this:
```dart
final Color accentColor = Colors.teal[800];
final Color primaryColor = Colors.white;
final Color textColor = Colors.grey[900];
```
BTW the code in the screenshot is different from the one you gave.

**Comment by mhmdanas** [comment]
I think I understand the problem. You declare the variables `accentColor`, `primaryColor`, and `textColor` to be of type `MaterialColor`, but then you assign them values of type `Color. I think this is the right behavior.

**Comment by ShardulNalegave** [comment]
Hi!
Thanks for helping @mhmdanas, I get the problem now.
An issue of depending too much on VS Code.
