### ISSUE TITLE
Wish for a systematic way to test Flutter against Android pre-releases

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#53582]
Any Android release (both major releases, but even security bulletins) may break parts of Flutter (especially as we're taking Android to its edge on some aspects).

It would be useful to have some system in place which makes sure Flutter tests are passing on Android release candidates, so that we can flag issues early enough.

cc @xster

**Comment by jmagman** [comment]
Related to https://github.com/flutter/flutter/issues/8697

**Comment by xster** [comment]
It's the same issue. Let's just merge it.

**Comment by jmagman** [comment]
Might be useful to split it out by platform since they likely wouldn't be done at the same time, but I'll let infra do that as needed.
