### ISSUE TITLE
web: trailing png "icon" color change doesn't appear to work for web using black png

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#53580]
I'm on flutter version:

```
JustinMac:build jeltoft$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.14.6 18G3020, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)

• No issues found!
```

And this code below works great in the app to show my icon as white.  But it shows original black when I build for web.   Note that I figured maybe just setting icon color wouldn't work in web so then I tried the ColorFiltered() as well.  But for the app i ONLY needed to set the icon color to white.  

Note that I created this icon from an svg with this web site.

https://fluttericon.com/

 Is this a known issue?

```
                  child: Card(
                      child: ListTile(
                    onTap: () => commissionRoom(id, parentId),
                    onLongPress: () {
                      _showPopupMenuRoom(id, parentId);
                    },
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: <Widget>[
                        ColorFiltered(
                          colorFilter: ColorFilter.mode(Colors.white, BlendMode.modulate),
                          child: Image(
                              image: _myLogo, color: Colors.white, width: 70.0),   // <<=== problem is with this icon being shown black, not white in web.  works fine in app
                        ),
                        kIsWeb == true
                            ? GestureDetector(
                                onTap: () => _showPopupMenuRoom(
                                    id, parentId,
                                   ),
                                child: Transform.scale(
                                    scale: 1.3,
                                    child: Icon(
                                      Icons.edit,
                                      color: colorizedMenuColor,
                                    )))
                            : Container(width: 0),
                      ],
                    ),
                    title: Text(                 
                            "name here",
                        style: _getOnlineStatus(parentId) == null
                            ? Theme.of(context).textTheme.button
                            : Theme.of(context)
                                .textTheme
                                .button
                                .copyWith(color: Colors.red[300])),
                    subtitle:
                        //null,
                        Text(" some text for subtitle",
                      style: TextStyle(fontSize: 15, color: lightGreyMenuColor),
                    ),
                  ))),
```

**Comment by VladyslavBondarenko** [comment]
Hi @jdeltoft 
why don't you load your icon from `.ttf` as IconData to use it for Icon widget?
could you share how do you load `_myLogo`? in what format?
could you provide `flutter run -d chrome --verbose`

**Comment by jdeltoft** [comment]
Oh man!  so sorry.  I thought this was an icon since I'm using it in the trailing spot.  but it's a PNG:

`    final _myLogo = AssetImage('assets/myimage.png');
`
Still the same issue though. The image shows white for me (the png is a black outline of a logo converted from an svg by the way) in apps, but on the web it shows original black.

Should I change the title of this issue or open a new one?

**Comment by VladyslavBondarenko** [comment]
@jdeltoft 
Could you create complete minimal reproducible code sample with using `NetworkImage` to show your case? And maybe to attach screenshot to compare web and mobile

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
