### ISSUE TITLE
SERIOUS ISSUE!! When ever I try to Build the app it builds the app not with the modified code 

### ISSUE THREAD

**Issue by sagarkhurana00786** [flutter/flutter#53588]
The issue is that
Let's say When I open Visual Studio Code I opened it with some code Which I **coded earlier** and **after writing some code** in that project When I try to build the Project it Builds the project not with the modified one but with the code which is available when I open the project. But When I do hot reload it fixes and even sometimes crashes.
Please help me I'm facing this issue for a very long time but now I'm frustrated.
Thanks

**Comment by guptamanas1998** [comment]
I used to face a similar problem, a temporary workaround is to use `flutter clean`. 
Updating the IDE worked for me.

**Comment by jonahwilliams** [comment]
@sagarkhurana00786 please follow the issue template as a guideline when filling a bug. To help we need to know at a minimum:

1. `flutter doctor -v`

2. verbose logs `flutter run -v ...` from a run where old code was used.

**Comment by sagarkhurana00786** [comment]
ok sorry 
Just a second

**Comment by sagarkhurana00786** [comment]
@jonahwilliams here is the output of `flutter doctor -v`

`PS C:\Users\Sagar Khurana\FlutterProjects\expenses_app> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at D:\Flutter\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Sagar Khurana\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\IntelliJ\IntelliJ IDEA Community Edition 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Sagar Khurana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Redmi 4 • 559790357cf4 • android-arm64 • Android 7.1.2 (API 25)
    • Redmi 8 • ad4810d10506 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.`

**Comment by jonahwilliams** [comment]
Okay, the issue here is caused by a bug in our dependency processing code when running in directories with spaces in them. This is fixed on both beta and dev, and can be worked around by moving to a directory without a space in it.

**Comment by sagarkhurana00786** [comment]
@jonahwilliams Really Thanks Sir for helping Now working Perfectly Fine
Now my `flutter doctor --verbose` output
`PS D:\FlutterProjects\expenses_app> flutter doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at D:\Flutter\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\AndroidSDKComponentSetup
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\AndroidSDKComponentSetup
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\SagarKhurana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Redmi 4 • 559790357cf4 • android-arm64 • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.`

**Comment by sagarkhurana00786** [comment]
@jonahwilliams 
Hello Sir, I'm a 18 years having a experience in Android development of 1+ Year Knows Java, Kotlin and Dart. As these days Dlutter is in Demand So I'm learning it.
I also wanted to work at Google like you.
I know that I need Great knowledge for DS ALGO and other Software book knowledge.
But How Google can recognize me.
Thanks Sir
