### ISSUE TITLE
[gen_l10n] Handle newline characters in messages

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#53583]
Currently what ends up happening is ARB messages with "backslash-n" generates code that does not compile. There is an assert that throws when the message contains a ~~"backslash-n"~~ newline character, but this does not get triggered when the tool is run without asserts enabled.

We should be able to get from `"fooBar": "foo\nbar"` in the arb file to `String get fooBar => 'foo\nbar'`. 

*Edited to fix misconception about assert statement

**Comment by HansMuller** [comment]
> There is an assert that throws when the message contains "backslash-n"
Currently we assert if the string contains a newline, not if it contains a backslash followed by an n.  In other words currently we assert:
```dart
 assert(!value.contains('\n');
```
which makes sense, since JSON values can't contain newlines.  We don't want to assert that the value doesn't contain "backslash-n":
```dart
 assert(!value.contains('\\n')
```
