### ISSUE TITLE
[animations] OpenContainer Error: The getter 'isInTree' was called on null.

### ISSUE THREAD

**Issue by suztomo** [flutter/flutter#53599]
Fork of https://github.com/flutter/flutter/issues/51397 , for my observation of OpenContainer error.

Minimum reproducible project: https://github.com/suztomo/flutter-animations-opencontainer-error

I use ListView and OpenContainer. When I delete the last element upon closing the OpenContainer, Flutter shows the following errors:

```
...
════════ (7) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree
The relevant error-causing widget was: 
  MaterialApp file:///Users/suztomo/Documents/opencontainer_deletion/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by animation library ═════════════════════════════════════════════════
The setter 'placeholderSize=' was called on null.
Receiver: null
Tried calling: placeholderSize=null
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I change the list before closing the OpenContainer.

```
              RaisedButton(
                  child: Text('Delete'),
                  onPressed: () {
                    _parentState.removeItem(_itemId);
                    closeContainer();
                  })
```
https://github.com/suztomo/flutter-animations-opencontainer-error/blob/master/lib/main.dart#L78

# Video

[![Screencapture of the OpenContainer Error](https://img.youtube.com/vi/zykVq2BT_Ao/0.jpg)](https://www.youtube.com/watch?v=zykVq2BT_Ao)

# Flutter Doctor

```
~/Documents/opencontainer_deletion $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
[✓] VS Code
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by suztomo** [comment]
@goderbauer I created this issue as per https://github.com/flutter/flutter/issues/51397#issuecomment-606132989. Let me know if you need more information. I appreciate if you can confirm whether you are able to reproduce the issue in https://github.com/suztomo/flutter-animations-opencontainer-error

**Comment by enricobenedos** [comment]
I've the exactly same problem when I delete the last item of a list that is using `OpenContainer`

**Comment by ksankumar** [comment]
> I've the exactly same problem when I delete the last item of a list that is using `OpenContainer`

Me too facing same issue

**Comment by goderbauer** [comment]
This was fixed by https://github.com/flutter/packages/pull/126.

**Comment by suztomo** [comment]
@goderbauer Thank you!

**Comment by edmbn** [comment]
Hello everyone, sorry for asking here but I think it is related. I'm using openContainer inside an item created from a streamBuilder. Page is opened well but, if the stream changes and the item which had the openContainer is removed, when I go back I get this error: "Looking up a deactivated widget's ancestor is unsafe". Do you know what can happen? Thank you!
