### ISSUE TITLE
Google and Facebook auth working in debug mode but not in release mode.

### ISSUE THREAD

**Issue by AlexGFX** [flutter/flutter#53592]
I use:
>  google_sign_in: ^4.1.4
> flutter_facebook_login: ^3.0.0

to authenticate my users.
Everything works perfect on my emulator, no errors.
I built my app using "flutter build apk".
When I tap the facebook or the google button on my built app, on a physical device, to run the methods that are handling the auth, nothing happens. It's like those buttons have no onTap method.

I found the same issue here: https://stackoverflow.com/questions/60682173/flutter-facebook-login-popup-or-webview-is-not-opening-on-released-apk-on-androi

**Comment by EngDjango** [comment]
did you add the SHA-1 fingerprint of the release-apk to firebase and facebook?

**Comment by Ahmadre** [comment]
exactly. Check your app store adminboard and extract the sha-fingerprint and add it to your facebook and google auth admin pages

**Comment by VladyslavBondarenko** [comment]
@AlexGFX 
does it solve the problem?

**Comment by VladyslavBondarenko** [comment]
@AlexGFX 
I hope it's solved. Closing since long time without an response

**Comment by encinas008** [comment]
I solved adding
<uses-permission android:name="android.permission.INTERNET" /> 
outside the application tag in your AndroidManifest.xml

**Comment by Puspharaj** [comment]
What about flutter web applications?
