### ISSUE TITLE
[in_app_purchase 0.3.1+2] How can use isAcknowledged ?

### ISSUE THREAD

**Issue by bilaloz** [flutter/flutter#53606]
I couldn't see anything about it in the document
I have to make changes to the code. Doesn't take any action on the sample code ? 
If I have to do, how can I do after the payment is completed.

Flutter's in_app_purchase plugin has been updated to version 0.3.0, migrating the Google Play Library to 2.0.3.
According to the Google Play Library v2, all purchases have to be acknowledged within 3 days (or 5 minutes in the case of test orders) or they will be canceled automatically.
In the latest commit of in_app_purchase, a method called acknowledgePurchase is added to the BillingClient class. However, the current documented way of making an in-app purchase is via InAppPurchaseConnection.instance which does not provide any method to acknowledge a purchase.

Thank you.

**Comment by bilaloz** [comment]
@agordeev

**Comment by fracon** [comment]
@bilaloz I pass through something like you, my subscription purchases were expiring 5 minutes after purchase in the sandbox environment, so after some research, I realize that after all purchases (iOS present in documentation and Android not present in documentation) you need to call completePurchase method. Now all my purchases in Android devices are working great. I hope this helps you.

**Comment by bilaloz** [comment]
@fracon thank you for answer. Is this code enough for me ?
![image](https://user-images.githubusercontent.com/25391443/78175281-48315b80-7463-11ea-9ab4-b432ee995cab.png)

**Comment by fracon** [comment]
@bilaloz I don't know if pendingCompletPurchase is working, for now, I think there is an open issue about this. A different approach is use the purchase status, when purchase status is purchased you call completePurchase. Just remember in iOS, as documentation said, you must use completePurchase for status error too.

**Comment by matthew-carroll** [comment]
The following is visible on the README for the IAP plugin:

```
Complete a purchase
The InAppPurchaseConnection.purchaseUpdatedStream will send purchase updates after you initiate the purchase flow using InAppPurchaseConnection.buyConsumable or InAppPurchaseConnection.buyNonConsumable. After delivering the content to the user, you need to call InAppPurchaseConnection.completePurchase to tell the GooglePlay and AppStore that the purchase has been finished.

WARNING! Failure to call InAppPurchaseConnection.completePurchase and get a successful response within 3 days of the purchase will result a refund.
```

Is this sufficient documentation to satisfy this ticket?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dark-chocolate** [comment]
Does `InAppPurchase.instance.completePurchase` guarantee that the `PurchaseWrapper.isAcknowledged` is `true`?
If no, then how can one confirm if the purchase was acknowledged (on Android)?
