### ISSUE TITLE
Automatically dump the frame when the performance is bad

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#53602]
Previously, we had `--dump-skp-on-shader-compilation` to dump a frame in `skp` format when there's a shader compilation which almost certainly means a big jank (30ms - 300ms a frame).

It would be useful if we can extend that function more broadly: if we ever detected a frame build or rasterization time to be very slow (e.g., 32ms+), dump the frame in PNG/skp automatically. This would help us debug performance issues. Jason from "customer: dream (g3)" originally brought up this demand because some frame mysteriously takes hundreds of milliseconds to build/rasterize.

**Comment by jacob314** [comment]
Fyi @kenzieschmoll

**Comment by jmagman** [comment]
@liyuqian Is this tracking work for the tool to do?

**Comment by liyuqian** [comment]
@jmagman : This will be a collaboration between the engine team and the tool team (or someone who's familiar with both can do this solo). I can implement the engine part.

**Comment by jonahwilliams** [comment]
I don't think the tool has any knowledge about what a bad frame is. We'd likely need the framework to track this information somehow, right?

**Comment by liyuqian** [comment]
The tool only needs to expose a flag in `flutter run` or `flutter drive` commands, and then send that flag to engine. The engine knows what the bad frame is, and can dump the frames. The tool may also need to call some service protocols (will be added) to retrieve the dumped frames from mobile devices to host machines.

**Comment by fzyzcjy** [comment]
Hi, is there any updates after 2 years? Thanks!

**Comment by zanderso** [comment]
@fzyzcjy please see https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs.

We'd like to build up functionality like this in Impeller around the [archivist](https://github.com/flutter/engine/tree/main/impeller/archivist), but the work to enter preview on Android is taking priority.

**Comment by fzyzcjy** [comment]
@zanderso Thank you for the update and replies in my PR! I apologize for sending the "is there an update" and explicitly minimized my post. However, without my question and your reply, I really do not know there is this interesting progress ;)

**Comment by jonahwilliams** [comment]
This isn't something we're going to add, as there are far too many reasons a frame could be missed and only a few are helped with a frame dump
