### ISSUE TITLE
[LUCI Bot] Update Windows Bots for Web Engine

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#53615]
The current Windows bots (e.g. flutter-try-win10-us-central1-c-10-c0t1) aren't able to open Blink, which seems to require desktop session (or display).

I believe we need to turn on the [Display device](https://cloud.google.com/compute/docs/instances/enable-instance-virtual-display) for these bots in order to open Blink and IE11. As the doc says: "If applications on your VM instances require a display device, but do not require the full power or cost of a GPU, you can configure your instances to use a virtual display device."

Related issue: https://github.com/flutter/flutter/issues/51427

/cc @nturgut @godofredoc @yjbanov

**Comment by nturgut** [comment]
Can we return the exiting bots and use this one for example (this is the one I'm using for testing for a while):[ the link to bot](https://pantheon.corp.google.com/compute/instances?project=flutter-dashboard&instancessize=50&instancesquery=%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22wutong-windows-experiment-2_5C_22_22_2C_22s_22_3Atrue%257D%255D)?
Also some additional bots with the same configuration (I don't know how many required).

Thanks!

**Comment by digiter** [comment]
@nturgut The one which you experimented has different machine image than the existing LUCI windows bots. It's hard to change the machine image. And I believe that's unnecessary, I think turning on display device should be able to fix the issue.

We can add more bots, but let's fix the tests first.

**Comment by digiter** [comment]
@godofredoc Can I try turning on display device on existing bots? If yes, do you know the procedure to do that safely?

**Comment by nturgut** [comment]
Hi, @digiter @godofredoc is there an update on the Windows bots?

Cheers,

Nurhan

**Comment by godofredoc** [comment]
The windows image is owned by chromium team and we don't have access to it. I'd also discourage you from enabling displays and GPUs to all the windows bots because it will increase the cost substantially.

My recommendation is to create a new windows image in collaboration with the fuchsia infra foundation team and create only the necessary bots for this use case. Then we can add a new dimension to the web engine builders to use only those bots.

**Comment by digiter** [comment]
@godofredoc I think the problem is caused by not having displays, why would creating a new windows image help that?

**Comment by godofredoc** [comment]
For windows bots you also need to consider the currently available windows version. Flutter bots are using Windows 10 version 1703 which I don't think is available anymore.

Additionally adding displays will use more CPU/memory that is not required for all the bots.

**Comment by digiter** [comment]
@nturgut How can I reproduce the problem? Can you add a test script that 1) prints the browsers currently installed and 2) simply opens Blink or IE11 as a sanity check?

**Comment by nturgut** [comment]
The easiest method (that will make sure we can use the bot can windows unit tests) can be tested after the recipe run. Therefore we can make sure flutter engine already exists in LUCI bot.

- go to engine\src\flutter\lib\web_ui\
- run these two commands in order
(1) ..\..\..\out\host_debug_unopt\dart-sdk\bin\pub.bat get
(1) ..\..\..\out\host_debug_unopt\dart-sdk\bin\pub.bat run test -p ie test\alarm_clock_test.dart

the final line of the output should be "All tests passed!" this shows us the luci bot is capable of running unit tests for internet explorer.

**Comment by nturgut** [comment]
@digiter is there an ETA for the windows bots update?

**Comment by digiter** [comment]
@godofredoc Is there a playbook for creating new windows image?

**Comment by godofredoc** [comment]
@keyonghan can you please help us with some initial instructions based on you experience setting up the windows device lab machines?

**Comment by keyonghan** [comment]
`flutter-team -> Infrastructure -> Device Lab -> Windows Host` should be up-to-date, showing how we add a new Windows host to devcelab.

**Comment by digiter** [comment]
This is for LUCI bots, not devicelab.

**Comment by godofredoc** [comment]
There is no playbook we have been using chromium images, we'll need to reach out to the chromium operations team to get that information.

**Comment by yjbanov** [comment]
Closing for now. We've been running Chrome and Edge on LUCI successfully for some time. If there's a specific need to reconfigure the bots, let's open a new issue.
