### ISSUE TITLE
Gallery: fast fling on home will result in tap

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5361]
On iOS, open the gallery. Then, fling as fast as you can on the home screen. I can very frequently trigger a tap and open a view.

On a fast fling, we shouldn't trigger a tap, instead we should just fling the home contents quickly.

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
Probably related to https://github.com/flutter/flutter/issues/4958. I bet we're not getting enough data points to do a velocity estimation (or maybe not even enough data points to consider doing it). @chinmaygarde, do you know how many events we're getting from iOS? On Android we get a lot more events than we do frames; should we be getting more events on iOS than we're getting?

**Comment by sethladd** [comment]
I'm happy to do some testing on iOS and Android. Maybe we're doing the right thing and I'm just tapping more than flinging.

**Comment by chinmaygarde** [comment]
> do you know how many events we're getting from iOS?

I verified that the platform implementation forwards all pointer events as they arrive. There is no coalescing. Also, I verified there are no iOS gesture recognizers in the way.

**Comment by Hixie** [comment]
Thanks. Does iOS send multiple events per frame like Android?

**Comment by Hixie** [comment]
Ok, I can confirm that the problem is what I suspected above. On Android, I get about 13 events in the 100ms window when I do a fling. On iOS I get about 7.

**Comment by Hixie** [comment]
@eseidelGoogle says (in https://github.com/flutter/flutter/issues/4737):

> iOS will coallese touches, you can get the individual ones with [UIEvent coalescedTouchesForTouch:] I'm told:
>
> http://flexmonkey.blogspot.de/2015/09/advanced-touch-handling-in-ios9.html

**Comment by Hixie** [comment]
cc @xster who has worked on similar things before.

**Comment by xster** [comment]
I'm gonna tentatively suggest this is fixed (32ms of touch+drag used to be still interpreted as a touch). Please reopen if it re-occurs.

**Comment by Hixie** [comment]
Closing per last comment.
