### ISSUE TITLE
No sound on iOS using video VideoPlayerController.file(file path)

### ISSUE THREAD

**Issue by shckim** [flutter/flutter#53624]
Hi, 
thanks for this great API.

I working on a project and initialize VideoPlayerController.file().
It work fine on android, but on iOS, the video is played but no sound.

It there any issue on play from file on iOS?

**Comment by TahaTesser** [comment]
Hi @shckim 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by shckim** [comment]
@ Taha Tesser


> Hi @shckim
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Hi, really thanks for reply. Your are my savior. 

I’m not possible to upload flutter doctor -v` and `flutter run --verbose` right now, but I will as soon as possible. Maybe tomorrow. 

Meanwhile, what I did is just use video player package and played mp4 after download and save it in app directory and played it with videoplayercontroller.file(). 

I did it in my code, but it did not work so I did it with minimum code like sample with not asset or network but just file. 

It works pretty well on android asset, network, file and iOS asset, network, but only for iOS file there is no sound but just video. 

I tried various version of this package and chewie. 

I think if you try with any code on iOS video player file, you maybe able to reproduce it. 

If not, it would be so good. I will upload my doctor and verbose as soon as possible.

**Comment by shckim** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale ko-KR)
    • Flutter version 1.12.13+hotfix.8 at /Users/sehokim/development/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sehokim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • CharliPhone • 00008020-001634C02E28002E • ios • iOS 13.4

• No issues found!


I think I found why... I think the sound of the video I played does not support iOS. Thanks!
