### ISSUE TITLE
Building from Visual Studio triggers a modal dialog

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53626]
Every build throws a "The solution 'Runner' has been modified outside the environment" modal. We need to pin down which generated file(s) are causing this and make them smarter about only re-writing when something changes, as it's made the IDE-based workflow much more annoying.

**Comment by gspencergoog** [comment]
cc @loic-sharma 

@stuartmorgan  is this still an issue? (Desktop Triage)

**Comment by stuartmorgan** [comment]
Probably; I never worked on fixing it. Although this probably predates the switch to CMake; it may be impossible to fix now in our current design.

**Comment by loic-sharma** [comment]
@stuartmorgan I wasn't able to reproduce this on VS 17.x. Are these the correct steps:

1. Open `./build/windows/my_app.sln` in Visual Studio
2. Set `my_app` as the start up project
3. Run `Build solution`
4. Run `Start debugging` to launch the app

If so, I think we can close this.

**Comment by stuartmorgan** [comment]
Oh right, I was misremembering and thought it was about command-line builds messing with the IDE.

So this was almost certainly *fixed* by switching to CMake, where we're no longer rebuilding sub-parts of the project in the re-entrant build.
