### ISSUE TITLE
Text Widget:  Chinese characters and English characters Mixed, text truncation error

### ISSUE THREAD

**Issue by aeronxie** [flutter/flutter#53629]
Chinese and English are separated ...

code：
```
Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(width:50,height:50,color:Colors.black45),
            Expanded(child:
              Text('文字文字文字kjhgfdrtyuiknbvfkjhgfdfgh',
                textAlign: TextAlign.left,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              )
            ),
            Container(width:200,height:50,color:Colors.red)
          ]
        )
```

![WX20200331-134957](https://user-images.githubusercontent.com/9351800/77991482-90af2300-7356-11ea-95e0-ee4ffe63fada.png)

The effect I want is  like  '文字文字文字kjhgfdrtyuik...'

**Comment by TahaTesser** [comment]
Hi @aeronxie 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by aeronxie** [comment]
> Hi @aeronxie
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Thank you

[✓] Flutter (Channel stable, v1.9.1+hotfix.3, on Mac OS X 10.15.3
    19D76, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.3-pre.19 at
      /Users/xxxx/Documents/xxxxx/flutter
    • Framework revision e83019d6b5 (3 weeks ago), 2020-03-11 10:38:24 +0800
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xiefei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPhone    • 35069717859f806534b172c7766d311813bfbf15 • ios • iOS 13.4
    • iPhone 11 • 99CA9D89-714A-42C5-ABCE-B6086AFEABFF     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

**Comment by TahaTesser** [comment]
Issue still exist on

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body:
              Center(
                child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
            Container(width: 50, height: 50, color: Colors.black45),
            Expanded(
                  child: Text(
                '文字文字文字kjhgfdrtyuiknbvfkjhgfdfgh',
                textAlign: TextAlign.left,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
            )),
            Container(width: 200, height: 50, color: Colors.red)
          ]),
              )),
    );
  }
}
```

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

When using `maxLines: 1`

![flutter_03](https://user-images.githubusercontent.com/48603081/78020577-543bf100-736f-11ea-8292-e0bcd5649e76.png)


When using `maxLines: 2`

![flutter_04](https://user-images.githubusercontent.com/48603081/78020614-6322a380-736f-11ea-9af0-603fcc2ac2c2.png)

**Comment by jason-simmons** [comment]
The Flutter text renderer does word wrap before applying the ellipsis.  So the English text is being wrapped to the second line.

Unicode word joiner characters can be used to tell the line breaker to not wrap words at a given position:
Text(`'文\u2060字\u2060文\u2060字\u2060文\u2060字\u2060kjhgfdrtyuiknbvfkjhgfdfgh')`

**Comment by lionoggo** [comment]
> Unicode单词连接符可用于告诉换行器不要在给定位置包装单词：

It's work. But this seems cumbersome.Engineers must be very clear about what they want to display.However, in most cases, this is unpredictable.

Is it possible to fix the problem in sdk?

**Comment by lionoggo** [comment]
> The Flutter text renderer does word wrap before applying the ellipsis. So the English text is being wrapped to the second line.
> 
> Unicode word joiner characters can be used to tell the line breaker to not wrap words at a given position:
> Text(`'文\u2060字\u2060文\u2060字\u2060文\u2060字\u2060kjhgfdrtyuiknbvfkjhgfdfgh')`

It's work. But this seems cumbersome.Engineers must be very clear about what they want to display.However, in most cases, this is unpredictable.

Is it possible to fix the problem in sdk?

**Comment by goderbauer** [comment]
The general issue for this problem is at https://github.com/flutter/flutter/issues/18761. I am going to close this as a duplicate.
