### ISSUE TITLE
video_player ios PlatformException(VideoError, Failed to load video: 操作停止, null)

### ISSUE THREAD

**Issue by xuwankang** [flutter/flutter#53636]
Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G4032, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/iosappjingda/Documents/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iosappjingda/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

video_player :0.10.8+1 

cant play video on ios,but android(http & https) is ok,
i had set 
`<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>`
but it showed PlatformException(VideoError, Failed to load video: 操作停止, null)

**Comment by TahaTesser** [comment]
Hi @xuwankang 

Are you sure you're proper video link?
```
 PlatformException(VideoError, Failed to load video: 操作停止, null)
```
This doesn't look like a link 

can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jerryzhoujw** [comment]
I have see this similar error, which is caused by `the video url can't verified in server`.

In my case that's because video token which have different encrypt result in iOS and Android, if this is the same case for you, just check the encrypt lib or function you use.

**Comment by xuwankang** [comment]
@TahaTesser 

you can try

`import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoScreen extends StatefulWidget {
  final String videoUrl;
  final String thumbnailUrl;
  VideoScreen({
    Key key,
    this.videoUrl,
    this.thumbnailUrl,
  }) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    return VideoScreenState();
  }
}

/// 入口页状态
class VideoScreenState extends State<VideoScreen> {
  VideoPlayerController _videoPlayerController;
  @override
  void initState() {
    super.initState();
    _videoPlayerController = VideoPlayerController.network('http://home.jingda.cn/api/imageView/profile/file/2020/03/24/3c11a4da31f01d67c16922166e285cbb.mp4')
      ..initialize().then((_) {
        print('&*&*&*&*&*&');
        setState(() {});
        _videoPlayerController.play();
      }).catchError((e) {
        print(e);
      });
  }

  @override
  void dispose() {
    if (_videoPlayerController.value.initialized) {
      _videoPlayerController.pause();
      _videoPlayerController.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _videoPlayerController.value.initialized
        ? AspectRatio(
            aspectRatio: _videoPlayerController.value.aspectRatio,
            child: VideoPlayer(_videoPlayerController),
          )
        : Container();
  }
}
`

**Comment by xuwankang** [comment]
its our server's problem,fixed it already
