### ISSUE TITLE
Can I customize or combine the flutter commands?

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#53640]
Can I customize or combine the flutter commands?

**Comment by 2534290808** [comment]
For example, I want to customize a `flutter build myapk` command that performs some custom commands before the `flutter build apk`

**Comment by TahaTesser** [comment]
Hi @2534290808 
Unfortunately, you cannot customize apk to myapk but you can combine flutter commands like this
`flutter build apk && flutter build appbundle`
This will build apk and appbundle  with single line of command 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
