### ISSUE TITLE
PaginatedDataTable ignore showCheckboxColumn

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter#53654]
Hi,

The `PaginatedDataTable` has a `showCheckboxColumn` parameter to display or not the checkbox for selectable rows. But the paremeter is not used ! It should be passed to  the `DataTable` children where the implementation is written

**Comment by VladyslavBondarenko** [comment]
@bkonyi 
was this line removed accidentally or intentionally?
https://github.com/flutter/flutter/commit/d907a2622907df5c059b6bcd12f8bf99b9564b93#diff-243d50d685c9399394efa4693f2ac703L473

**Comment by bkonyi** [comment]
That was removed unintentionally (as I had actually just added the showCheckboxColumn around the same time as that PR), so it should be added back.
