### ISSUE TITLE
[web] Using Clipboard when embedded in an iFrame throws PlatformException  

### ISSUE THREAD

**Issue by treeder** [flutter/flutter#53651]
## Steps to Reproduce

The following works fine as a standalone app at it's own URL:

```dart
child: InkWell(
              child: Text("some text"),
              onTap: () async {
                try {
                  await Clipboard.setData(
                      ClipboardData(text: "123"));
                  Scaffold.of(context).showSnackBar(SnackBar(
                    content: new Text("Copied to Clipboard"),
                  ));
                } on PlatformException catch (err) {
                  // from JS console: copy is not successful Disabled in this document by Feature Policy.
                  print("Can't copy data to clipboard, clipboard disabled? $err");
                } catch (err) {
                  print("caught some error using clipboard: $err");
                }
              },
            )));
```

When the exact same app is embedded in an iFrame, you'll see a message that is printed to the console from somewhere else:

```
copy is not successful Disabled in this document by Feature Policy.
```

Then the PlatformException message above:

```
Can't copy data to clipboard, clipboard disabled? PlatformException(copy_fail, Clipboard.setData failed, null)
```

I've looked around for how to set this Feature Policy properly, but I can't find anywhere that references anything to do with copying and pasting or clipboard. Also the page containing the iframe hasn't set any restrictions on the policies. 

Feature Policy references:

* https://developers.google.com/web/updates/2018/06/feature-policy
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/feature_policy/feature_policy.cc?l=138&rcl=ab90b51c5b60de15054a32b0bd18e4839536a1c9

**Expected results:** 

Expect the copy to work like normal.

**Actual results:** 

Throws an exception.

**Comment by yjbanov** [comment]
This looks like a browser security restriction. Is there anything on the Flutter side we can do to help?

/cc @nturgut

**Comment by ditman** [comment]
Maybe related? https://github.com/w3c/webappsec-feature-policy/issues/322

**Comment by nturgut** [comment]
The clipboard api security restrictions: https://developers.google.com/web/updates/2018/03/clipboardapi In summary:

**_As with many new APIs, navigator.clipboard is only supported for pages served over HTTPS. To help prevent abuse, clipboard access is only allowed when a page is the active tab. Pages in active tabs can write to the clipboard without requesting permission, but reading from the clipboard always requires permission._**

Can you please try to use https iframe?
