### ISSUE TITLE
Seperation on yaml library depends of platform

### ISSUE THREAD

**Issue by 3rsin3rgul** [flutter/flutter#53652]
Hello,
I would like to ask something related library installations. Because I could not find answer for it.
Is it possible to install different libraries for different platforms.
Example;

#If iOS
  cupertino_icons: ^0.1.2
#if Android
  #NOTHING!

**Comment by jonahwilliams** [comment]
We have no plans to support this feature. For pub related questions you can follow up at dart-sdk/pub
