### ISSUE TITLE
how to run integration tests with flutter app(some code implement by java/objectC)

### ISSUE THREAD

**Issue by NanYeYe** [flutter/flutter#53653]
if i use **flutter_driver**  to run integration tests，but some app code is implemented by java/objectC, can **flutter_driver** achieve this purpose?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
