### ISSUE TITLE
Regression in color_filter_and_fade_perf__timeline_summary 90th_percentile_frame_build_time_millis & 99th_percentile_frame_build_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53659]
Looks like this engine roll:

![Screen Shot 2020-03-31 at 7 48 29 AM](https://user-images.githubusercontent.com/1435716/78040255-08b02580-7324-11ea-94cd-5405b905e1b2.png)

**Comment by liyuqian** [comment]
The number has gone down. Rebased those benchmarks as they do have a wider distribution since the beginning.

<img width="275" alt="Screen Shot 2020-03-31 at 4 20 32 PM" src="https://user-images.githubusercontent.com/22987568/78083876-9ebb6e80-736b-11ea-8ce1-87b826ecbe61.png">
