### ISSUE TITLE
Upgrade pinned dependency on package_config to support null safety

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#53665]
The new Dart null safety feature (https://github.com/dart-lang/language/issues/110) relies on changes to how the Dart language version is calculated, which in turn involves changes to the package_config. 

Currently the dependency on package_config is pinned, and doesn't update when running the usual package upgrade command:

```
$ flutter update-packages --force-upgrade
Upgrading packages...
WARNING: the following packages use hard-coded version constraints:
  - flutter_gallery_assets: 0.1.9+2
  - mockito: ^4.1.0
  - vm_service_client: 0.2.6+2
  - video_player: 0.10.6
  - package_config: 1.9.1
```
For null safety to work correctly, we need package_config upgrade to version `1.9.3` or later.

**Comment by mit-mit** [comment]
cc @lrhn to confirm that 1.9.3 is the needed version

**Comment by jonahwilliams** [comment]
I think this is tracked by https://github.com/flutter/flutter/issues/51951 too. The issue I was having is that it is not clear what path we should pass to other tooling (dart2js, frontend_server). When we use package_config to resolve this, I don't know which file we selected

**Comment by lrhn** [comment]
1.9.2 is probably sufficient, 1.9.3 is a bugfix (but do include it!)
