### ISSUE TITLE
Completions for a list of widgets should not be parameterized

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#53664]
## Use case

The reccomended completion for widgets with a `children` parameter is list literal with a parameterized type (`<Widget>[]`).

This isn't necessary because the generic type for the list can be inferred.

## Example
Getting a completion for `children` in this snippet recommends `<Widget>[]`:

```dart
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column();
  }
}
```

<img width="365" alt="Screen Shot 2020-03-31 at 8 49 17 AM" src="https://user-images.githubusercontent.com/1145719/78047029-b7f0fa80-732c-11ea-991f-18c807295960.png">

The most common way to write this is:

```dart
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text("foo"),
        Text("baz"),
      ],
    );
  }
}
```
## Proposal

Omit the generic type parameter, so the completion becomes `[]`.

**Comment by goderbauer** [comment]
Are these autocompletion hints generated by the IDE or the dartanalyzer? This should probably be filed as a bug on one of those components.

/cc @devoncarew
