### ISSUE TITLE
Enable null safety for package:flutter & sky_engine

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#53662]
Tracking issue for enabling null safety (https://github.com/dart-lang/language/issues/110) in `package:flutter`

**Comment by aliyazdi75** [comment]
Is `sky_engine` using non-nullable feature?
I've tried to run `flutter pub run build_runner watch` and I've got an error like `flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.`
and due to https://github.com/flutter/flutter/issues/40490 I couldn't add this feature.
What should I do to run `build_runner`?

**Comment by aliyazdi75** [comment]
> Is `sky_engine` using non-nullable feature?
> I've tried to run `flutter pub run build_runner watch` and I've got an error like `flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.`
> and due to #40490 I couldn't add this feature.
> What should I do to run `build_runner`?

It's been resolved by adding 
```
dependency_overrides:
  analyzer: 0.39.14
```
in `pubspec.yaml`

**Comment by franklinyow** [comment]
@mit-mit Do we still need this item for TP2?

**Comment by mit-mit** [comment]
We need the framework, but it looks like that might be tracked in https://github.com/dart-lang/sdk/issues/40146 and not here. So perhaps this bug can be closed as a duplicate, @leafpetersen ?

**Comment by flukejones** [comment]
@mit-mit  Please leave this issue open until the referred issue is closed. Most people won't be looking for information on this part of flutter in the dart repo, and in fact "Flutter framework null safety migration" sounds like it should be in the flutter repo altogether.

I do kind of wish issues relating to flutter would stop being put in dart repo.

**Comment by franklinyow** [comment]
@mit-mit @leafpetersen  I think we can close this, agree?

**Comment by mit-mit** [comment]
I think so; but note that we're now blocked on #59879

**Comment by franklinyow** [comment]
closing
