### ISSUE TITLE
How to implement Dart code obfuscation for Flutter Plugin?

### ISSUE THREAD

**Issue by ren-gh** [flutter/flutter#53663]
From URL: https://www.flutterchina.club/developing-packages.md

请问如何实现 Flutter Plugin 的 Dart 代码混淆？

**Comment by TahaTesser** [comment]
Hi @ren-gh 
Translated your question to English 
```
How to implement Dart code obfuscation for Flutter Plugin?
```

Please if comment below, if the  translation isn't right.

**Comment by jonahwilliams** [comment]
If you are asking whether it is possible to obfuscate the native platform side, there should be existing documentation and Flutter methodology is no different.

Its not possible to obfuscate the Dart side/plugin code, which must be distributed as source. Nor does pub supported closed source packages.

It is possible to obfuscate the final app through https://flutter.dev/docs/deployment/obfuscate

**Comment by ren-gh** [comment]
Thanks every one very much!
I want to realize the encryption of dart code to ensure the security of our code.
My English is not good, please forgive me!
