### ISSUE TITLE
flutter version on Podfile.lock is not the same with the project

### ISSUE THREAD

**Issue by atilkan** [flutter/flutter#53673]
I have flutter version v1.16.3 
But in Podfile.lock it shows  
```
PODS:
  - Flutter (1.0.0)
```
I had newer  version even when i setup the project. Is this a problem to be fixed?

**Comment by jmagman** [comment]
This is expected.  The Flutter framework isn't downloaded from CocoaPods; it's copied from your installed Flutter SDK.  So it's hard-coded to 1.0 since there's no version resolution for CocoaPods to handle.  If you see actual issues related to this, pleas let us know!
