### ISSUE TITLE
DateTime bug when subtracting a month on march 31st

### ISSUE THREAD

**Issue by Fernandomr88** [flutter/flutter#53671]
So I have this code to subtract a month using DateTime.

```
   String _getMonthName({int fator}) {
    DateTime today = new DateTime.now();
    if (fator != null) {
      today = new DateTime(today.year, today.month + fator, today.day);
    }
    String mes = DateFormat("MMMM", "pt_BR").format(today);
    return '${mes[0].toUpperCase()}${mes.substring(1)}';
   }
```

Check that today is correct:
![image](https://user-images.githubusercontent.com/14304128/78056475-922f1a00-735b-11ea-95c2-a539d55b29b6.png)

**Then, with _factor of -1_ month, after using 'month -1' instead of going go february 28th or 29th, depending of the year, I go to march 02..check the image:**

![image](https://user-images.githubusercontent.com/14304128/78056747-fe118280-735b-11ea-9c5c-a8b1a4b0e953.png)

DateTime should be able to deal with this. I'm using a third party package to handle it instead (Jiffy)

**Comment by LongCatIsLooong** [comment]
This behavior makes sense to me (although I can't find relevant documentation). The invalid date `2020-02-31` was converted to a valid one `2020-03-02`. Try 2020-03-00 if you want to get that last day of February.

**Comment by Fernandomr88** [comment]
> This behavior makes sense to me (although I can't find relevant documentation). The invalid date `2020-02-31` was converted to a valid one `2020-03-02`. Try 2020-03-00 if you want to get that last day of February.

When I subtract one month from a Date object, it seems logical to me that I'll get the corresponding date of last month. I didn't subtract 30 days, but 1 month.

It isn't very logical to get a Date from March, minus a month, and get March back...

**Comment by VladyslavBondarenko** [comment]
Hi @Fernandomr88 
Please open the proposal in [the dart repository](https://github.com/dart-lang/sdk/issues),
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
