### ISSUE TITLE
Android Compiled Code as Dynamic Feature Module to reduce apk Updatable Size

### ISSUE THREAD

**Issue by canewsin** [flutter/flutter#53672]
Google Play Store can make file by file patching for updates, and split apks if we seperate flutter.so and app.so into two modules, since flutter.so is always unchanged unless flutter SDK update, this will save app furthur update size, since only app.so only need to be updated.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/51522
\cc @xster

**Comment by canewsin** [comment]
> See https://github.com/flutter/flutter/issues/51522
> \cc @xster 

It's about asset modules, my issue is libapp.so file to seperate module, which can be updated by filebyfile patching support by Google Playstore.

**Comment by xster** [comment]
Merging this into https://github.com/flutter/flutter/issues/57617
