### ISSUE TITLE
Remove unused NDK lookup and doctor validator

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53684]
Tool is looking in `<android-sdk>/ndk-bundle`, but SDK manager is installing in `<android-sdk>/ndk`

https://github.com/flutter/flutter/blob/df90bb5fd64e2066594151b9e311d45cd687a80c/packages/flutter_tools/lib/src/android/android_sdk.dart#L133

[Docs say](https://developer.android.com/studio/projects/install-ndk#default-version):
> Android Studio installs all versions of the NDK in the android-sdk/ndk/ directory.

> Note: If you have an NDK installed in the ndk-bundle folder, it appears in the list with the label NDK. If you are using Android Gradle plugin 3.5.0 or later, you can select this checkbox or clear it. Clearing the checkbox uninstalls the NDK, freeing up disk space, and causes the checkbox to disappear from the list. If you uninstall the legacy NDK, remove the ndk.dir value, which is now deprecated, from your projects' local.properties files.

**Comment by jmagman** [comment]
The history of that doc shows the "legacy NDK" note was present in the first version in July 2019...

**Comment by jmagman** [comment]
This has really atrophied, there's no `source.properties` or `arm-linux-androideabi-gcc` anymore.

**Comment by jmagman** [comment]
@jason-simmons Can I kill all the NDK code with extreme prejudice?  It doesn't appear to be used anywhere but in doctor as of https://github.com/flutter/flutter/pull/33611/files#diff-77d60a41797d03aa9a7de0c742b17ef1L290

**Comment by jonahwilliams** [comment]
As far as I know we don't need the NDK for anything

**Comment by jmagman** [comment]
@jason-simmons agreed.
