### ISSUE TITLE
New release tag format (e.g. "1.17.0-dev.0.0") not detected by flutter tool

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#53688]
I suspect this is because we use a regex on git tags in the flutter tool to detect tagged releases, which the new tag does not match.

```
~/git/flutter$ flutter doctor -v
[✓] Flutter (Channel master, v1.16.4-pre.46, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.16.4-pre.46 at /Users/fujino/git/flutter
    • Framework revision 730a440fd5 (12 minutes ago), 2020-03-31 16:26:01 -0400
    • Engine revision 6b09714a2c
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 11d6bc6055)
```

```
~/git/flutter$ git tag | grep 'dev'
1.17.0-dev.0.0
```

*UPDATE*: The problem code is:
```dart
    return parse(_runGit('git describe --match v*.*.* --first-parent --long --tags', processUtils, workingDirectory));
```

**Comment by christopherfujino** [comment]
@tvolkert did you use the `roll_dev.dart` script (or its internal wrapper) to publish this?

**Comment by christopherfujino** [comment]
Hmm, I'm guessing this was a manual tag

**Comment by tvolkert** [comment]
Yep, manual tag. (for now - gonna update scripts after I've documented all the changes to the publishing)

**Comment by zanderso** [comment]
/cc @jonahwilliams 

I don't know if this is one, but I wanted to note that we need to be careful of places where the tool needs to be able to handle both the old and the new version string formats.

**Comment by jonahwilliams** [comment]
Could we tag the releases with both naming schemes for now, until the update percolates everywhere? Alternatively, we need to wait up for the tool fix for now

**Comment by tvolkert** [comment]
I'm gonna wait for the tool fix and mark 1.17.0-dev.0.0 as bad, since it's only on dev for now.

**Comment by tvolkert** [comment]
FYI, I'm going to publish another dev release that still contains this bug despite it being TODAY, to at least ensure that our dev build is signed on MacOS.

**Comment by christopherfujino** [comment]
> FYI, I'm going to publish another dev release that still contains this bug despite it being TODAY, to at least ensure that our dev build is signed on MacOS.

SGTM

**Comment by zanderso** [comment]
Thanks, Chris!

**Comment by pcsosinski** [comment]
also need #54217 for CP
