### ISSUE TITLE
Flutter Add 2 App [iOS] On the second time launching, accessibility not working and can't do any action

### ISSUE THREAD

**Issue by shihchanghsiungsonos** [flutter/flutter#53681]
1. Our page has two line texts and one button.
2. Launching our page and VoiceOver works as expected. The first line text is highlighted and VoiceOver speaks the text correctly.
3. Tap to select the button, double tap to action on the button to close the Flutter page. Our page also supports tap to outside of the page to close the page.
4. Launch the same page again.

Expected:
VoiceOver works as expected and behaves the same as the first time the page is launched.

Actual:
1. The page is launched, no item is highlighted and VoiceOver does not speak any item.
2. Can't tap to select the button.

Note:
Still can close the page by selecting the top status bar item, like time and battery, then double tap on screen.

**Comment by dannyvalentesonos** [comment]
@dnfield This bug is very similar to https://github.com/flutter/flutter/issues/31139#issuecomment-547152445

Basically, we have a FlutterViewController that we present in a modal fashion. Then, in Flutter, the user could close the view, causing the platform FlutterViewController to get dismissed.

Launching a new FlutterViewController afterwards then causes the bug @shihchanghsiungsonos is describing here. It would take some time to create a sample app for this. I've done that in Android for the bug I just linked, but if it is really needed for this bug on iOS, I'll try and build one soon. Please let me know.

**Comment by gaaclarke** [comment]
Can you add the output of `flutter doctor -v` please?

**Comment by dannyvalentesonos** [comment]
danny.valente$ flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.12.13+hotfix.6 at /Users/danny.valente/Library/flutter/1.12.13+hotfix.6-beta
    • Framework revision 18cd7a3601 (4 months ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by dannyvalentesonos** [comment]
danny.valente$ flutter doctor -v
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.16.2 at /Users/danny.valente/Library/flutter/1.16.2-dev
    • Framework revision 58cad787d8 (8 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by gaaclarke** [comment]
I was able to reproduce it with:
```
[✓] Flutter (Channel master, v1.16.4-pre.34, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.16.4-pre.34 at /Users/aaclarke/dev/flutter
    • Framework revision a2d62df3ee (16 hours ago), 2020-03-30 21:51:48 -0700
    • Engine revision 10887c2abe
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 e21c435300)
```

It can only be reproduced if you turn on VoiceOver and never turn it off.  If you turn it off and on while the Flutter view is visible, VoiceOver will work correctly.

**Comment by dannyvalentesonos** [comment]
I'm glad you can repro @gaaclarke.
I'm curious. Do you have a sample app where you can dismiss the FlutterView and open it again? Or did you find a different set of repro steps?

**Comment by gaaclarke** [comment]
Yea, I made one months ago and just keep it around with the default Flutter project.  When you press a button it pops the FlutterViewController onto the UINavigationController.

**Comment by dnfield** [comment]
It's likely that we're just not resetting the a11y bridge state on detachment - we had to do something similar for Android.

**Comment by dnfield** [comment]
i.e. https://github.com/flutter/engine/pull/14142

**Comment by gaaclarke** [comment]
### 1
`Shell::OnEngineUpdateSemantics` and `AccessibilityBridge::UpdateSemantics` are called before the view controller is first presented.  The second time the view controller is presented, it isn't called.

---
### 2
UpdateSemantics appears to be triggered by Dart:
```
#0	0x00000001028d3264 in flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) at /Users/aaclarke/dev/engine/src/flutter/shell/common/shell.cc:987
#1	0x00000001028d35c0 in non-virtual thunk to flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) ()
#2	0x0000000102896a3c in flutter::Engine::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) at /Users/aaclarke/dev/engine/src/flutter/shell/common/engine.cc:453
#3	0x0000000102863c74 in flutter::RuntimeController::UpdateSemantics(flutter::SemanticsUpdate*) at /Users/aaclarke/dev/engine/src/flutter/runtime/runtime_controller.cc:297
#4	0x000000010282a26c in flutter::(anonymous namespace)::UpdateSemantics(_Dart_NativeArguments*) at /Users/aaclarke/dev/engine/src/flutter/lib/ui/window/window.cc:49
#5	0x0000000103ea7058 in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) at /Users/aaclarke/dev/engine/src/third_party/dart/runtime/vm/native_entry.cc:215
...
#25	0x0000000103e44414 in dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) at /Users/aaclarke/dev/engine/src/third_party/dart/runtime/vm/dart_entry.cc:190
#26	0x0000000103e44024 in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) at /Users/aaclarke/dev/engine/src/third_party/dart/runtime/vm/dart_entry.cc:168
#27	0x0000000103ee2294 in dart::Library::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const at /Users/aaclarke/dev/engine/src/third_party/dart/runtime/vm/object.cc:12281
#28	0x00000001041cfa60 in ::Dart_Invoke(Dart_Handle, Dart_Handle, int, Dart_Handle *) at /Users/aaclarke/dev/engine/src/third_party/dart/runtime/vm/dart_api_impl.cc:4615
#29	0x000000010393bd34 in tonic::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>) at /Users/aaclarke/dev/engine/src/flutter/third_party/tonic/logging/dart_invoke.cc:16
#30	0x0000000102829550 in flutter::Window::BeginFrame(fml::TimePoint) at /Users/aaclarke/dev/engine/src/flutter/lib/ui/window/window.cc:353
#31	0x0000000102863420 in flutter::RuntimeController::BeginFrame(fml::TimePoint) at /Users/aaclarke/dev/engine/src/flutter/runtime/runtime_controller.cc:208
#32	0x0000000102894fcc in flutter::Engine::BeginFrame(fml::TimePoint) at /Users/aaclarke/dev/engine/src/flutter/shell/common/engine.cc:224
#33	0x00000001028d2b14 in flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint) at /Users/aaclarke/dev/engine/src/flutter/shell/common/shell.cc:938
#34	0x00000001028d2b50 in non-virtual thunk to flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint) ()
#35	0x000000010287b8e8 in flutter::Animator::BeginFrame(fml::TimePoint, fml::TimePoint) at /Users/aaclarke/dev/engine/src/flutter/shell/common/animator.cc:142
#36	0x0000000102890f08 in flutter::Animator::AwaitVSync()::$_3::operator()(fml::TimePoint, fml::TimePoint) const at /Users/aaclarke/dev/engine/src/flutter/shell/common/animator.cc:242
#37	0x0000000102890e10 in decltype(std::__1::forward<flutter::Animator::AwaitVSync()::$_3&>(fp)(std::__1::forward<fml::TimePoint>(fp0), std::__1::forward<fml::TimePoint>(fp0))) std::__1::__invoke<flutter::Animator::AwaitVSync()::$_3&, fml::TimePoint, fml::TimePoint>(flutter::Animator::AwaitVSync()::$_3&, fml::TimePoint&&, fml::TimePoint&&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/type_traits:4350
#38	0x0000000102890d48 in void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::Animator::AwaitVSync()::$_3&, fml::TimePoint, fml::TimePoint>(flutter::Animator::AwaitVSync()::$_3&, fml::TimePoint&&, fml::TimePoint&&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/__functional_base:349
#39	0x000000010288f8f0 in std::__1::__function::__func<flutter::Animator::AwaitVSync()::$_3, std::__1::allocator<flutter::Animator::AwaitVSync()::$_3>, void (fml::TimePoint, fml::TimePoint)>::operator()(fml::TimePoint&&, fml::TimePoint&&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1572
#40	0x00000001026ba8bc in std::__1::function<void (fml::TimePoint, fml::TimePoint)>::operator()(fml::TimePoint, fml::TimePoint) const at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1923
#41	0x00000001029528d0 in flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0::operator()() const at /Users/aaclarke/dev/engine/src/flutter/shell/common/vsync_waiter.cc:128
#42	0x0000000102952714 in decltype(std::__1::forward<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0&>(fp)()) std::__1::__invoke<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/type_traits:4350
#43	0x00000001029526c8 in void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0&) at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/__functional_base:349
#44	0x000000010295114c in std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0>, void ()>::operator()() at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1572
#45	0x000000010271e840 in std::__1::function<void ()>::operator()() const at /Users/aaclarke/dev/engine/src/buildtools/mac-x64/clang/include/c++/v1/functional:1923
#46	0x0000000102736acc in fml::MessageLoopImpl::FlushTasks(fml::FlushType) at /Users/aaclarke/dev/engine/src/flutter/fml/message_loop_impl.cc:127
#47	0x0000000102736900 in fml::MessageLoopImpl::RunExpiredTasksNow() at /Users/aaclarke/dev/engine/src/flutter/fml/message_loop_impl.cc:137
#48	0x000000010274fbf4 in fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) at /Users/aaclarke/dev/engine/src/flutter/fml/platform/darwin/message_loop_darwin.mm:75
```

---
### 3
Turning off and on VoiceOver seems to work because it triggers `-[FlutterViewController onAccessibilityStatusChanged:]` and `PlatformViewIOS::SetSemanticsEnabled`

---
### 4
```
  FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] flutterEngine];
  FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
  [self pushViewController:flutterViewController animated:YES];
```
Should trigger a new update semantics because it has a new `AccessibilityBridge`, but of course that isn't happening.  It is almost certainly required to reuse the engine to reproduce the bug.

---
### 5
View did appear attempts to update the semantics:
```
#0	0x0000000100a5567c in flutter::Shell::OnPlatformViewSetSemanticsEnabled(bool) at /Users/aaclarke/dev/engine/src/flutter/shell/common/shell.cc:833
#1	0x0000000100a31e58 in flutter::PlatformView::SetSemanticsEnabled(bool) at /Users/aaclarke/dev/engine/src/flutter/shell/common/platform_view.cc:52
#2	0x0000000100851f84 in flutter::PlatformViewIOS::SetSemanticsEnabled(bool) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/platform_view_ios.mm:126
#3	0x0000000100812cb8 in ::-[FlutterViewController onAccessibilityStatusChanged:](NSNotification *) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:1046
#4	0x000000010080f718 in ::-[FlutterViewController viewDidAppear:](BOOL) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:600
```

Something is silently gobbling up our attempts though.

Ultimately that call leads to calling back into Dart:
```
void Window::UpdateSemanticsEnabled(bool enabled) {
  std::shared_ptr<tonic::DartState> dart_state = library_.dart_state().lock();
  if (!dart_state)
    return;
  tonic::DartState::Scope scope(dart_state);

  tonic::LogIfError(tonic::DartInvokeField(
      library_.value(), "_updateSemanticsEnabled", {tonic::ToDart(enabled)}));
}
```

**Comment by gaaclarke** [comment]
https://github.com/flutter/flutter/blob/210f4d83136a2eae773bda471db90ac27676f662/packages/flutter/lib/src/semantics/semantics.dart#L2610

```
 void sendSemanticsUpdate() {
    if (_dirtyNodes.isEmpty)
      return;
    ...
```

This code in the framework seems to silently gobble up our call to update semantics

**Comment by xster** [comment]
@goderbauer may have some context on the framework implementation

**Comment by dannyvalentesonos** [comment]
@gaaclarke @dnfield I just noticed that after the FlutterViewController is dismissed, Voice Over is just completely broken in the native app as well. Do you think your fix will fix that, or should that be logged as a separate issue?

**Comment by dannyvalentesonos** [comment]
Looks like it was because the app crashed and the debugger was stopped on the crash. I've been getting a lot of random crashes when using Voice Over. Are there any known crashes that have been logged?

**Comment by gaaclarke** [comment]
@dannyvalentesonos 
> Do you think your fix will fix that, or should that be logged as a separate issue?

Yep, will be fixed there.

> Are there any known crashes that have been logged?

None that I know of or saw in testing this bug.  Please file an issue if you find something.
