### ISSUE TITLE
Gallery: sometimes, on Android, the word "Demos" is half-way under the app bar on launch

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5368]
Running on 5X, built with --release.

Sometimes, not always, on a fresh start, I see this:

![screen shot 2016-08-12 at 11 23 33 am](https://cloud.githubusercontent.com/assets/5479/17632816/3934c0be-607f-11e6-8491-dcf456cef0c3.png)

Notice that the word "Demos" is half-way under the app bar.

Scrolling up and down doesn't fix it. Tapping into a vignette and then tapping back will fix it.

**Comment by abarth** [comment]
I've seen this too.  It appears to be some sort of race condition during startup.

**Comment by HansMuller** [comment]
This looks like a consequence of MediaQuery.of(context).padding.top returning zero

**Comment by abarth** [comment]
Maybe we don't initialize the padding early enough?  I would have expected the layout to update when the padding changes to its final value...  Is there a missing dependency with the scaffold's custom layout somehow?

**Comment by abarth** [comment]
```
  @override
  bool shouldRelayout(_ScaffoldLayout oldDelegate) {
    return padding != oldDelegate.padding;
  }
```

That looks right...

**Comment by HansMuller** [comment]
Maybe it is possible for Engine::OnViewportMetricsChanged() to have been called after the scaffold has looked up the window padding  as well as not triggering a rebuild?

Note also: So far I haven't been able to reproduce the problem and verify that the source is in fact the window padding being zero. This may all be idle speculation.

**Comment by sethladd** [comment]
Another user stopped by my desk today and pointed this out :)

**Comment by jason-simmons** [comment]
I can reproduce this easily on the Android emulator

**Comment by HansMuller** [comment]
Jason and I just sorted this out.

When running on the Android emulator and occasionally when running Android native, MediaQuery.of(context).padding.top is zero when it's called at Widget initState() time. Calling it at build() time instead appears to consistently return the status bar's actual height.
