### ISSUE TITLE
[web] Add capability to run chrome on android unit tests to felt

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#53693]
Add capability to run chrome on android unit tests to felt.

In order this issue to resolve we should also address [web_drivers](https://github.com/flutter/web_installers/tree/master/packages/web_drivers) features: https://github.com/flutter/flutter/issues/53692

**Comment by yjbanov** [comment]
We decided to unschedule running on mobile emulators for now. They turned out to be too flaky.
