### ISSUE TITLE
Dart's http has fixes since the last time we copied http into Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5370]
Looks like there's been some updates to the http library that we copied into Flutter: https://github.com/dart-lang/http/commits/master

It appears that we haven't rolled those updates in? https://github.com/flutter/flutter/commits/master/packages/flutter/lib/src/http

Doesn't look critical (not blocking our current users AFAIK) but something we probably want to do at some point.

**Comment by sethladd** [comment]
I believe @chinmaygarde addressed this?

**Comment by chinmaygarde** [comment]
We are going to start using dart-lang/http directly. There seems to be some progress on removing their use of mirrors.

**Comment by sethladd** [comment]
> There seems to be some progress on removing their use of mirrors.

Oh, cool! Is there a PR? I couldn't find one.

**Comment by sethladd** [comment]
@chinmaygarde is fixing this as we speak :)

**Comment by chinmaygarde** [comment]
Yes. This is fixed and the patches have landed.
