### ISSUE TITLE
devicelab/test/run_test.dart is flaky

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#53707]
This a fresh reporting of #5901 - when it was closed it recommended opening a new issue to discuss if it resurfaced.

In doing a skip audit, I have found this is still broken.

Here is the associated skip:
https://github.com/flutter/flutter/blob/ad07c4041a966415ab96ebe4ee174ee43093c233/dev/devicelab/test/run_test.dart#L56

And here are some logs, it appears to either fail or hang  depending on the platform:

https://cirrus-ci.com/task/6551240146419712

https://cirrus-ci.com/task/5145431382425600

**Comment by yjbanov** [comment]
Nope, not fixed yet (context: https://github.com/flutter/flutter/pull/54618)

**Comment by yjbanov** [comment]
I will unassign for now because I'm not setup to test this on Windows. I may come back to this later when I have access to a Windows machine. In the meantime, if anyone else is interested in taking a crack at this, by all means.

**Comment by godofredoc** [comment]
closing as obsolete please reopen if you find the issue again.

**Comment by Piinks** [comment]
The test is still skipped, should we un-skip the test and make sure it's not flaky before closing this?

**Comment by godofredoc** [comment]
Sounds good, I was going through the list of bugs in the technical debt project and closing the ones that haven't had any updates in months.

**Comment by godofredoc** [comment]
@keyonghan something to track as part of the flakiness effort?

**Comment by keyonghan** [comment]
> @keyonghan something to track as part of the flakiness effort?

This is a real unit test flake which has been marked as `skipped`. I believe the action here is to dig and fix the flake.

**Comment by godofredoc** [comment]
@Hixie should we start deleting all the tests that have been skipped for over a year?

**Comment by Hixie** [comment]
We should probably consider them on a case-by-case basis (in general this is why I'm a bit reluctant to just disable tests that are flaky rather than either deleting them right away or considering their failure to be a P1-level issue, all it's doing is pushing the problem down the road).

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/136295 removes this test.

**Comment by Hixie** [comment]
new fix (actually fixes the test): https://github.com/flutter/flutter/pull/139122
