### ISSUE TITLE
Missing documentation on FlutterApplicationLifeCycleDelegate in Swift

### ISSUE THREAD

**Issue by Schoonology** [flutter/flutter#53709]
It appears as if there is some missing documentation on how to conform to the `FlutterApplicationLifeCycleDelegate` protocol from Swift. Namely, I was trying to integrate the `_:didFinishLaunchingWithOptions:` hook.

Is this expected? Where should that documentation live?

More details (and places I looked figuring this out):

- _Writing custom platform-specific code_: https://flutter.dev/docs/development/platform-integration/platform-channels?tab=ios-channel-swift-tab
- _Developing packages & plugins_: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm
- Protocol documentation: https://api.flutter.dev/objcdoc/Protocols/FlutterApplicationLifeCycleDelegate.html#/c:objc(pl)FlutterApplicationLifeCycleDelegate(im)application:didFinishLaunchingWithOptions:
- First-party plugins, none of which appear to be written in Swift: https://github.com/flutter/plugins/tree/master/packages

**Comment by jmagman** [comment]
Swift documentation has been added.
