### ISSUE TITLE
Dashboard release branches should show LUCI task results for that branch, not prod

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53716]
Release branches show LUCI tasks for prod instead of the relevant branch.

**Comment by jmagman** [comment]
Related to https://github.com/flutter/flutter/issues/51807
\cc @CaseyHillers

**Comment by christopherfujino** [comment]
FYI the way LUCI determines which builder group to use via a regex against the git refs in the `flutter/infra` config: https://github.com/flutter/infra/blob/master/config/main.star#L20

```python
HOTFIX_REFS = 'refs/heads/v.+hotfixes'
```

**Comment by CaseyHillers** [comment]
Since everything is now standardized in the ci.yaml, this should be do-able (previously it was non-trivial to get the builders for a branch)

**Comment by CaseyHillers** [comment]
Closing as the Cocoon scheduler migration is complete.

Starting for releases after 3.3, this will be complete (granted we may CP these changes into 3.3)
