### ISSUE TITLE
When a new branch is detected in branch_regexps.txt, cocoon should add the most recent commit to the datastore, regardless of commit date

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53711]
Cocoon only adds commits from the last hour to the datastore.  However, it would be great if any new branch detected from [branch_regexps.txt](https://github.com/flutter/cocoon/blob/master/app_dart/dev/branch_regexps.txt) automatically added the most recent commit to the datastore and kicked off all devicelab tests.  The top of tree may be older than an hour when the branch is moved to point at that commit.

**Comment by tvolkert** [comment]
Ideally, the commits for a release branch would contain the commit on master where the branch was initiated, then any subsequent commits on the branch (not on master).
