### ISSUE TITLE
[salt] Config user limits on testbeds

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#53719]
To avoid problems like unable to create processes, we need to update salt state to config user limits on our testbeds, including both devicelab machines and LUCI bots.

The chrome LUCI bots have been using these numbers: maxproc=2500 and maxfiles=16384.

**Comment by godofredoc** [comment]
This is already done for the try machines but we need to add it either to the provisioning instructions or to salt.

These are the commands we need to run:

```
sudo defaults write /com.apple.xpc.launchd.limits maxproc -int 2500
sudo defaults write /com.apple.xpc.launchd.limits maxfiles -int 16384
sudo chmod 644 /com.apple.xpc.launchd.limits.plist
sudo SetFile -a V /com.apple.xpc.launchd.limits.plist
```

**Comment by godofredoc** [comment]
This was affecting mac-try machines that have been deprecated. closing as obsolete.
