### ISSUE TITLE
Dashboard branches should be captured in the URL, make it sharable, refresh should use last selected branch

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53714]
I wanted to share the devicelab test results for a particular branch, but the URL is just https://flutter-dashboard.appspot.com/#/build which defaults to master.
When I'm looking at a branch and hit refresh, it also returns to the master branch.

**Comment by jmagman** [comment]
\cc @CaseyHillers

**Comment by keyonghan** [comment]
It would be nice to enable that also for the performance dashboard.
