### ISSUE TITLE
Could we either exclude the profile build or cherry-pick debug and release when using Flutter Module?

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#53726]
We attach Flutter as a module to an existing application by consuming frameworks build by commands:

```
flutter build ios-framework --xcframework --no-universal
flutter build aar
```

Questions:
- Could we either exclude the profile build or cherry-pick debug and release?
It takes about 155 seconds to build profile on Android and 150 seconds on iOS, we would benefit by dropping these times.

- Why does shared preferences also contain shared_preferences_macos and shared_preferences_web?

I'm using the most recent beta (Flutter 1.15.17 • channel beta)
Shared Preferences: 0.5.6+1

Kind regards
Chris

**Comment by xster** [comment]
See `flutter build ios-framework -h` or `flutter build aar -h` to pick the builds you want to include. 

Could you let us know where you looked for documentation first? Could help us make sure we put clearer documentation in places people most expect. 

Shared preferences seems like an unrelated question. @amirh for whether there are public documentation for how the federated plugins work.

**Comment by chris-rutkowski** [comment]
```
flutter build ios-framework --xcframework --no-universal --no-profile
flutter build aar --no-profile
```
did the job. **Thank you!**
I swear I checked the documentation before and these options were not there, maybe they were added most recent beta.

However, if you can give me the answer related. to web and macOS folders that would be great.

**Comment by jmagman** [comment]
You can always run a command with the `-h` to see what flags are available.
```
flutter build ios-framework  -h
...
    --[no-]profile                                Whether to produce a framework for the profile build configuration. By default, all build configurations are built.
                                                  (defaults to on)
```
So:
```
flutter build ios-framework --xcframework --no-universal --no-profile
```

**Comment by jmagman** [comment]
> However, if you can give me the answer related. to web and macOS folders that would be great.

It means the plugin can be used in a Flutter web or macOS app.  See https://github.com/flutter/plugins/pull/2344, for example.

**Comment by chris-rutkowski** [comment]
@jmagman 

> It means the plugin can be used in a Flutter web or macOS app. See flutter/plugins#2344, for example.

It can, but it is not - the application is only for iOS and Android. And when I delete these folders it cannot build the AAR.

**Comment by jmagman** [comment]
@chris-rutkowski Can you file a new issue for just that, and we'll direct it to the plugins team?

**Comment by chris-rutkowski** [comment]
@jmagman done: https://github.com/flutter/flutter/issues/55145
