### ISSUE TITLE
Formatting big numbers throughout the flutter app

### ISSUE THREAD

**Issue by jatinpnd8055** [flutter/flutter#53732]
I have an app in which the numerical values can be very big in some cases. So, it is not possible to put the big value in the container without disturbing the shape of the app. I want something like a property, which can be enable in the theme data of the app, and when I set that property to true, the big numbers of the whole app get converted to their short forms. Like 1,000,000 would get converted to 1M or 1million, (like in YouTube). By default, if I enable this property from the theme data of the app, then all the text widgets must use this property and any big text like 1,000 would get converted to 1k.
But there should also be a property for every individual text widgets to set that property to true or false.
Please, I request you to add this feature either as a package or as an update to flutter.

**Comment by TahaTesser** [comment]
Hi @jatinpnd8055 

You can achieve this by formatting your number string using `intl` package

Check out this code sample, this will format 1000000 to 1M 

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final _formattedNumber = NumberFormat.compact().format(1000000);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Formatted Number is $_formattedNumber'), 
          ),
        ),
      ),
    );
  }
}
```

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
