### ISSUE TITLE
How to prevent tapgesturerecognizer double click events

### ISSUE THREAD

**Issue by terminatorx** [flutter/flutter#53730]
```
TextSpan(
          text: 'click',
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              print("6666");
            },
        );
```
When I double-click, the tap event can also be triggered。How to stop it？

**Comment by TahaTesser** [comment]
Looking [TapGestureRecognize](https://api.flutter.dev/flutter/gestures/TapGestureRecognizer-class.html), there is no double tap

**Comment by dkwingsmt** [comment]
It might be pretty hard. Just for information, do you mean the 2nd tap should not be triggered if it’s too close to the first tap, or the first tap should not be triggered either if it’s followed closely by another tap? Also what’s your use case?

**Comment by terminatorx** [comment]
I hope the click event will not be triggered when double clicking. Is there any way to achieve this

**Comment by terminatorx** [comment]
@TahaTesser But when you double-click, the tap event will also be triggered

**Comment by terminatorx** [comment]
@TahaTesser 
```
GestureDetector(
      child: Text("click"),
      onTap: (){
        print("88899");
      },
      onDoubleTap: (){
      },
    )
```
Gesturedetector can prevent the tap event from being triggered when double clicking by adding the ondoubletap event.
But how does tapgesturerecognizer stop this.
