### ISSUE TITLE
How to control gesture priorities between the SingleChildScrollView and pan gesture(GestureDetector)?

### ISSUE THREAD

**Issue by guolingege** [flutter/flutter#53737]
The following is my sample code, I want to let **only one** of the widgets GestureDetector and SingleChildScrollView works in some conditions. How can I control it?
I know the property `behavior: HitTestBehavior.opaque` works, but it conflicts with my needs: I want to judge when the finger touches on the screen. The UI design is next following: 
```
    final s = SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(),
          GestureDetector(
            child: Container(child: Image.network('......')),
            onPanDown: (details) {
              if (_isAroundTheControlPoint) { /// some condition
                /// let the `GestureDetector` work
              } else {
                /// let the `SingleChildScrollView` scroll
              }
            },
            onPanUpdate: (details) {
              /// todo
            },
            onPanEnd: (details) {
              /// todo
            },
          ),
          Container(),
        ],
      ),
    );
```
<img width="892" alt="WX20200401-155443@2x" src="https://user-images.githubusercontent.com/13193905/78112692-29b26c80-7431-11ea-967e-287017065a30.png">

1. when the finger touches within the red circle, let the `GestureDetector` works;
2. when the finger touches within the blue area, let the `SingleChildScrollView` works;
3. when the finger touches within the green circle and pans horizontally, let the `GestureDetector` works;
4.when the finger touches within the green circle and pans vertically, let the `SingleChildScrollView` works.

**Comment by dkwingsmt** [comment]
Will it work if the green area is wrapped in a GestureDetector with horizontal drag, and is _stacked_ by the red areas with pan?

**Comment by guolingege** [comment]
```
> Will it work if the green area is wrapped in a GestureDetector with horizontal drag, and is _stacked_ by the red areas that are wrapped in GestureDetectors with pan?
```

In fact, the whole image is contained by the GestureDetector(the Image is child of the GestureDetector), and I judge the touch location by the coordinate. The sample code is:
```
  onPanDown: (details) {
    final offset = details.localPosition;
    Rect rect = ...;/// the black area's rect
    List<Rect> controlPointRects = ...;/// the red area's rects
    if (rect.contains(offset)) {
      bool flag = false;
      for (final rect2 in controlPointRects) {
        if (rect2.contains(offset)) {
          flag = true;
          break;
        }
      }
      if (flag) {
        /// let the`GestureDetector` works
      } else {
        /// let the`SingleChildScrollView` works
      }
    } else {
      /// let the`SingleChildScrollView` works
    }
  }
```

**Comment by dkwingsmt** [comment]
I'm not sure if there's simpler way, but in this case I would recommend handling recognizers manually. An example can be found at [_CupertinoSwitchState](https://github.com/flutter/flutter/blob/87cbddddd85aabc4aff1218f6a78f8bde397cc40/packages/flutter/lib/src/cupertino/switch.dart#L142)).

- At `initState`, create gesture recognizers as needed, and assign callbacks.
- At `dispose`, dispose recognizers.
- At `handleEvent`, call recognizers' `addPointer` if the `event` satisfies the constraints.

**Comment by guolingege** [comment]
> I'm not sure if there's simpler way, but in this case I would recommend handling recognizers manually. An example can be found at [_CupertinoSwitchState](https://github.com/flutter/flutter/blob/87cbddddd85aabc4aff1218f6a78f8bde397cc40/packages/flutter/lib/src/cupertino/switch.dart#L142).
> 
> * At `initState`, create gesture recognizers as needed, and assign callbacks.
> * At `dispose`, dispose recognizers.
> * At `handleEvent`, call recognizers' `addPointer` if the `event` satisfies the constraints.
> 
> This is also how `GestureDetector` works (although it handles them at the render object level and uses factories to generate recognizer instances).

I have resolved it by CustomPainter's hitTest and switch the SingleChildScrollView's physics property between AlwaysScrollableScrollPhysics and NeverScrollableScrollPhysics.

I guess there is a better way to resolve it, which will looks more scientific.

**Comment by markusaksli-nc** [comment]
Closing as solved, not sure how the documentation could be improved here.
