### ISSUE TITLE
Flutter TabBarView auto height based on content

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#53743]
my code looks like this:

    final tabBarPagesView = Container(
      child: Padding(
        child: TabBarView(
          children: [
            _buildTabPage1(),
            _buildTabPage2(),
            _buildTabPage3(),
          ],
        ),
        padding: EdgeInsets.all(GLOBAL_PADDING),
      ),
      height: 700, //this is not FIXED, dynamic
    );

but I don't want to set height to 700, because inside it is a ListView with Containers, Columns and so on.

Also when I not set I got an error. 

Any way to set the height to my inner content height?

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
Can you please explain in detail?
What's the use case of having `TabBarView` height based on content?
Thank you

**Comment by klaszlo8207** [comment]
Yes, I have a Sliver and I have a TabBarView in the middle of the screen with 2 tabs and widgets.
The widgets ara Listviews so a long widget. I want to create tabbars with listview with full height. 

So I don't want to scroll in the listview with fixed height.

Thanks

**Comment by klaszlo8207** [comment]
my Listview have

        physics: const NeverScrollableScrollPhysics(),
        shrinkWrap: true,

this values

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
Please check out this [answer](https://stackoverflow.com/a/57383014)
Thank you

**Comment by klaszlo8207** [comment]
It is working when only one item in the Container:

    return tabBarPagesView;

but not if I do this:

    return Column(
      children: <Widget>[
        buildPlaceHolder(10),
        header,
        tabBarView,
        //tabBarPagesView, -> this kill
      ],
    )

WTF?!

**Comment by klaszlo8207** [comment]
So maybe Column break the tabbar height somehow? Why? 
I tried what you linked, but with no luck. These are after all

**Comment by klaszlo8207** [comment]
Now it is working, I had to refactor all my code, thanks :)
