### ISSUE TITLE
image_picker, invalid target architecture when trying to run on simulator with iOS 13.4

### ISSUE THREAD

**Issue by shaun0203** [flutter/flutter#53740]
This is the error I get when trying to run on iPhone 11, iOS 13.4;

    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

**Comment by VladyslavBondarenko** [comment]
Hi @shaun0203 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/51395
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
