### ISSUE TITLE
Library asset path creation failed: FileSystemException: Creation failed 

### ISSUE THREAD

**Issue by tomrozb** [flutter/flutter#53756]
## Steps to Reproduce

1. Flutter imported in native android app as a module
2. Make some changes in native app
3. Every 10th build fails with given error, then have to clear Flutter to make it work

**Actual results:** 

```
> Task :flutter:compileFlutterBuildDebug
Target debug_android_application failed: FileSystemException: Creation failed, path = '/xyz/flutter_module/.android/Flutter/build/intermediates/flutter/debug/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out/flutter_assets/.android/Flutter/build/intermediates/library_assets/debug/out' (OS Error: File name too long, errno = 63)
build failed.

> Task :flutter:compileFlutterBuildDebug FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/x/flutter-sdk/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':flutter:compileFlutterBuildDebug'.
> Process 'command '/x/flutter-sdk/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
1 actionable task: 1 executed
```

Seems that there's something wrong with the generated path?

The module was created with `flutter create flutter_module`

```

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)
```

</details>

**Comment by xster** [comment]
Seems like some symbolic linking in the gradle scripts gone awry. Is this reproducible on freshly created projects or is there some specific repro steps?

**Comment by tomrozb** [comment]
The only symlink that I have is related to google-services.json file. 

It resides in 
`module/.android/app`
and points to 
`google-services.json -> ../../../app/google-services.json`

It doesn't happen on a freshly created one. I can copy google-services file there and check if that still occurs.

**Comment by xster** [comment]
Seems possible. Our gradle probably needs some loop detection if that's the case.

**Comment by tomrozb** [comment]
@xster removed the symlink to google-services.json but this still happens. I have no idea what's the root cause of this. Any ideas?

**Comment by xster** [comment]
Could be our flutter.gradle script. Can you describe your project arrangements a bit? i.e. the folder structure between your host project and your Flutter module (and any simlinking that happens anywhere). Sounds like a bug.

**Comment by jonahwilliams** [comment]
Sounds like https://github.com/flutter/flutter/issues/45075

**Comment by jonahwilliams** [comment]
This can be caused by hosting assets in the project root instead of in an asset directory.

**Comment by tomrozb** [comment]
@jonahwilliams I've checked #45057 and my assets are in the `/assets` in the project root.

I've just changed the asset definition in `pubspec.yaml` from:
```
flutter:
  assets:
    - ic_verified.svg
```
to:
```
flutter:
  assets:
    - assets/ic_verified.svg 
```

Both imports work. If the first one causes mentioned problem shouldn't it throw an error before compiling the app?
