### ISSUE TITLE
InputDecoration. Possibility to show hintText when unfocused and labelText is set

### ISSUE THREAD

**Issue by cedricgrothues** [flutter/flutter#53753]
## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Example(),
    );
  }
}

class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextFormField(
          decoration: InputDecoration(
            floatingLabelBehavior: FloatingLabelBehavior.always,
            labelText: 'This is the labelText',
            hintText: 'Hello, World!',
          ),
        ),
      ),
    );
  }
}
```

**Expected results:**
* If the FloatingLabelBehavior is .always the hintText should not disappear and look similar to this:
![IMG_0658](https://user-images.githubusercontent.com/34948511/78149688-90865480-7436-11ea-864e-c786cf164756.jpg)

**Actual results:**
* hintText disappears, leaving a blank space.
![IMG_0660](https://user-images.githubusercontent.com/34948511/78149667-89f7dd00-7436-11ea-9e80-63952b9303a4.jpg)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.4 19E266, locale en-DE)
    • Flutter version 1.16.4-pre.33 at /Users/cedricgrothues/flutter
    • Framework revision aee9e94c21 (2 days ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cedricgrothues/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    ✗ Android SDK file not found: /Users/cedricgrothues/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (4 available)            
    • Cedric’s iPhone • 00008030-001218E421F0802E • ios            • iOS 13.4
    • macOS           • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome          • chrome                    • web-javascript • Google Chrome 80.0.3987.149
    • Web Server      • web-server                • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @cedricgrothues 
What I see `hintText` is hidden without dependency on `floatingLabelBehavior`.
It persists and is on the place of `labelText` when focused, when `labelText` is not set. 
But when `labelText` is set, `hintText` is shown only when focused.
Probably it's a documentation issue and this should be written here https://api.flutter.dev/flutter/material/InputDecoration/hintText.html

**Comment by cedricgrothues** [comment]
Ah, ok! Is there a way to show the `hintText` even if it's unfocused and `labelText` is set?

**Comment by kjgasser** [comment]
This would be really helpful for my team! We have been struggling with this as an issue

**Comment by SiddharthVermaS** [comment]
We can simply use floatingLabelBehavior: FloatingLabelBehavior.never and assign the same text to labelText and hintText.

```
TextField(               
                  decoration: InputDecoration(     
                    labelText: 'Email',
                    hintText: 'Email',
                    floatingLabelBehavior: FloatingLabelBehavior.never,
                  ),
 );`
```

**Comment by AbanoubNassem** [comment]
is there any way to always show both the label and the hint ?

**Comment by VladyslavBondarenko** [comment]
@AbanoubNassem 
the fix is already in master and dev

**Comment by abuanwar072** [comment]
> @AbanoubNassem
> the fix is already in master and dev

Thank you so much

**Comment by abuanwar072** [comment]
@VladyslavBondarenko 
thank you so much

**Comment by AbanoubNassem** [comment]
> @AbanoubNassem
> the fix is already in master and dev

yes , I can confirm that, it's now working perfectly , thank you.

**Comment by HectorLobatoSilva** [comment]
i have the same issue on android, i see on ios i'ts work, but in android don't

**Comment by justinmc** [comment]
@HectorLobatoSilva If you're still seeing this on the master channel, could you open a new issue with a minimal app to reproduce it?

**Comment by HectorLobatoSilva** [comment]
I upgrade to the last flutter version and run flutter doctor, it's work know, thank you

**Comment by DipakSkywave** [comment]
Can we update hinttext?

Code 👍 

decoration: InputDecoration(
          hintText: titleHint.toString(),
          border: InputBorder.none,
          fillColor: Colors.white,
          contentPadding:
              EdgeInsets.symmetric(horizontal: 10.0, vertical: 10.0),
        ),
