### ISSUE TITLE
UI issue with alignment inside a dialog

### ISSUE THREAD

**Issue by CripyIce** [flutter/flutter#53750]
I'm having UI issues with the following code:
```dart
showDialog(
    context: context,
    child: Material(
      color: Colors.white,
      child: Container(
        child: Stack(
          children: <Widget>[
            Align(
              alignment: Alignment.topRight,
              child: IconButton(
                icon: Icon(
                  CustomIcons.closer_01,
                  color: Colors.black54,
                  size: 64.0,
                ),
                onPressed: () {},
              ),
            ),
            Column(
              children: <Widget>[],
            )
          ],
        ),
      ),
    ));
```

Which give me this result:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-01 at 16 07 08](https://user-images.githubusercontent.com/26387823/78140593-ee18a200-7432-11ea-9200-6d590d337cf4.png)

When unwrapping `Icon` from `IconButton` it works great.

**Edit - Ripple effect also has an issue:**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-01 at 16 09 22](https://user-images.githubusercontent.com/26387823/78140791-39cb4b80-7433-11ea-8e5e-b8b89e61cddb.png)

flutter doctor:
```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.43.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)
```

**Comment by VladyslavBondarenko** [comment]
Hi @CripyIce 
Use `iconSize` property of `IconButton` instead of `Icon.size`. This should solve your problem.
Read this doc https://api.flutter.dev/flutter/material/IconButton/iconSize.html
Closing since this is not an issue,
If you disagree please write in the comments and I will reopen it.
Thank you
