### ISSUE TITLE
[VoiceOver] Random Semantics nodes are selected when the widget tree changes

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#53755]
With the following code:

```
class SemanticsHomePage extends StatefulWidget {
  _SemanticsHomePageState createState() => _SemanticsHomePageState();
}

class _SemanticsHomePageState extends State<SemanticsHomePage> {

  Widget _tree1;
  Widget _tree2;

  int _currentTree = 0;

  void _buildTrees() {
    _tree1 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Text("Test 1", style: TextStyle(fontSize: 50)),
        Text("Test 2", style: TextStyle(fontSize: 50)),
        Text("Test 3", style: TextStyle(fontSize: 50)),
        FlatButton(child: Text("Change", style: TextStyle(fontSize: 20)), onPressed: () {
          setState(() {
            _currentTree = (_currentTree + 1) % 2;
          });
        })
      ],
    );
    _tree2 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        FlatButton(child: Text("Change", style: TextStyle(fontSize: 20)), onPressed: () {
          setState(() {
            _currentTree = (_currentTree + 1) % 2;
          });
        }),
        Text("Test 4", style: TextStyle(fontSize: 50)),
        Text("Test 5", style: TextStyle(fontSize: 50)),
        Text("Test 6", style: TextStyle(fontSize: 50)),
        Text("Test 7", style: TextStyle(fontSize: 50)),
        Text("Test 8", style: TextStyle(fontSize: 50)),
      ],
    );
  }

  @override
  void initState() {
    _buildTrees();

    super.initState();
  }

  @override
  void didUpdateWidget(SemanticsHomePage oldWidget) {
    _buildTrees();

    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        body: Center(
            child: _currentTree == 0 ? _tree1 : _tree2
        )
    );
  }
}
```

Tapping the "Change" button causes any random element to get selected by Voice Over after the tree changes.

This prevents anyone from writing an application that can transition widgets in and out of the tree and have accessibility behave properly. 

I have tried using a Semantics widget with the scopesNode and namesNode set to true, and provide a label placed above each subtree, but that doesn't work. It works the first time the sub tree is shown, but subsequent transitions no longer work. The scopesNode documentation says that the node should be selected automatically when a new scopesNode is inserted into the tree, but this does not work in the example above.

Is there a bug in Flutter, or is there something I need to do that I haven't tried yet?

**Comment by dannyvalentesonos** [comment]
danny.valente$ flutter doctor -v
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.16.2 at /Users/danny.valente/Library/flutter/1.16.2-dev
    • Framework revision 58cad787d8 (9 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by dannyvalentesonos** [comment]
@dnfield Here's another. Any suggestions on this one?

**Comment by dannyvalentesonos** [comment]
[semantics_issue.mov.zip](https://github.com/flutter/flutter/files/4415895/semantics_issue.mov.zip)

**Comment by TahaTesser** [comment]
Issue exist on
```
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.4 19E266, locale
    en-GB)
    • Flutter version 1.16.4-pre.33 at /Users/taha/Code/flutter_dev
    • Framework revision aee9e94c21 (33 hours ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

**Comment by dannyvalentesonos** [comment]
Thanks @TahaTesser. What is the behavior on Android? Does it select the first widget of the new sub tree?

**Comment by dannyvalentesonos** [comment]
I just tested with pushing a new route onto the navigator and the same issue exists there.

**Comment by dnfield** [comment]
I have a vague memory that we need to pump a frame for this to work - @goderbauer do you know what's going on here?

**Comment by dannyvalentesonos** [comment]
@goderbauer If you're interested, I modified my code from above a little to push a new route onto the navigation stack to prove that VoiceOver accessibility is broken in this case. A random node (or one close to what was previously selected...) is selected after a new route is pushed

```
class SemanticsHomePage extends StatefulWidget {
  const SemanticsHomePage({
    this.tree = 0
  });

  final int tree;

  _SemanticsHomePageState createState() => _SemanticsHomePageState();
}

class _SemanticsHomePageState extends State<SemanticsHomePage> {

  Widget _tree1;
  Widget _tree2;

  int _currentTree = 0;

  void _buildTrees() {
    _tree1 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Text("Test 1", style: TextStyle(fontSize: 50)),
        Text("Test 2", style: TextStyle(fontSize: 50)),
        Text("Test 3", style: TextStyle(fontSize: 50)),
        FlatButton(child: Text("Change", style: TextStyle(fontSize: 20)), onPressed: () {
          setState(() {
            _currentTree = (_currentTree + 1) % 2;
          });
        }),
        if (widget.tree == 0)
          FlatButton(child: Text("Open", style: TextStyle(fontSize: 20)), onPressed: () {
            Navigator.of(context).push(PageRouteBuilder(pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
              return SemanticsHomePage(tree: 1);
            }));
          })
      ],
    );
    _tree2 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        FlatButton(child: Text("Change", style: TextStyle(fontSize: 20)), onPressed: () {
          setState(() {
            _currentTree = (_currentTree + 1) % 2;
          });
        }),
        Text("Test 4", style: TextStyle(fontSize: 50)),
        Text("Test 5", style: TextStyle(fontSize: 50)),
        Text("Test 6", style: TextStyle(fontSize: 50)),
        Text("Test 7", style: TextStyle(fontSize: 50)),
        Text("Test 8", style: TextStyle(fontSize: 50)),
        if (widget.tree == 1)
          FlatButton(child: Text("Close", style: TextStyle(fontSize: 20)), onPressed: () {
            Navigator.of(context).pop();
          })
      ],
    );
  }

  @override
  void initState() {
    _buildTrees();
    _currentTree = widget.tree;

    super.initState();
  }

  @override
  void didUpdateWidget(SemanticsHomePage oldWidget) {
    _buildTrees();

    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        body: Center(
            child: _currentTree == 0 ? _tree1 : _tree2
        )
    );
  }
}
```

**Comment by dannyvalentesonos** [comment]
What is interesting @goderbauer @dnfield is if I change the PageRouteBuilder to be a MaterialPageRoute, then the first widget on the new page is selected.

**Comment by goderbauer** [comment]
(I haven't read all the comments in this thread, but) the first example can be fixed by using a key:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: Scaffold(body: SemanticsHomePage())));
}

class SemanticsHomePage extends StatefulWidget {
  _SemanticsHomePageState createState() => _SemanticsHomePageState();
}

class _SemanticsHomePageState extends State<SemanticsHomePage> {
  Widget _tree1;
  Widget _tree2;
  Key foo = UniqueKey(); /// <--- this is new

  int _currentTree = 0;

  void _buildTrees() {
    _tree1 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Text("Test 1", style: TextStyle(fontSize: 50)),
        Text("Test 2", style: TextStyle(fontSize: 50)),
        Text("Test 3", style: TextStyle(fontSize: 50)),
        FlatButton(
          key: foo,   /// <--- this is new
          child: Text("Change", style: TextStyle(fontSize: 20)),
          onPressed: () {
            setState(() {
              _currentTree = (_currentTree + 1) % 2;
            });
          },
        )
      ],
    );
    _tree2 = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        FlatButton(
          key: foo, /// <--- this is new
          child: Text("Change", style: TextStyle(fontSize: 20)),
          onPressed: () {
            setState(() {
              _currentTree = (_currentTree + 1) % 2;
            });
          },
        ),
        Text("Test 4", style: TextStyle(fontSize: 50)),
        Text("Test 5", style: TextStyle(fontSize: 50)),
        Text("Test 6", style: TextStyle(fontSize: 50)),
        Text("Test 7", style: TextStyle(fontSize: 50)),
        Text("Test 8", style: TextStyle(fontSize: 50)),
      ],
    );
  }

  @override
  void initState() {
    _buildTrees();

    super.initState();
  }

  @override
  void didUpdateWidget(SemanticsHomePage oldWidget) {
    _buildTrees();

    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: _currentTree == 0 ? _tree1 : _tree2));
  }
}
```

This key causes Flutter to re-use the same semantics node for both buttons and thus keeping its a11y focus.

**Comment by goderbauer** [comment]
The scopesRoute doesn't work as used because you are replacing a `Semantics(scopesRoute: true, ...)` with another `Semantics(scopesRoute: true, ...)`. That's just a no-op as the configuration of the tree hasn't changed.

**Comment by dannyvalentesonos** [comment]
@goderbauer That is not what I want. I am using a button in this example to be able to continually update the widget tree, but each update potentially has completely new elements. The first element of the new tree should be chosen, or something less random.

Also, I had thought of the Semantics widget replacing another Semantics widget issue as well, and so I had it updating the tree where it would replace an entirely different widget and it still was not working as expected.

**Comment by dannyvalentesonos** [comment]
Because of the way our actual application code is written, using a Semantics widget with `scopesRoute: true` works well because we add the new sub tree before removing the old one, so it actually works.
But it would be something an app developer would expect should work when replacing one sub tree with another.

**Comment by goderbauer** [comment]
Can you describe how you would like it to behave? The a11y guidance I have been getting from our a11y experts is that you should never manually move the a11y focus and always have the a11y service (TalkBack/VoiceOver) figure out where focus should go. The only exception is when a new route is pushed, in that case focus goes to the first element on screen.

If you modify screen content like in your example, my expectation would be that focus stays with whatever element caused the content change to retain the user's context.

**Comment by dannyvalentesonos** [comment]
I can agree with you on your expectation. I'm building something quite complex that replaces the entire view with new contents. The old contents fly off, while the new come in, and in the process, even the widget that caused the update flies out. Luckily, I add the new content in a Stack while the old flies out and the new flies in, so surrounding each subtree with a Semantics widget that has `scopesRoute: true` works, because the new one is added, and after an animation duration, the old is removed. So this will be good enough for me, and given the complexity, I guess it makes sense that the application developer has the responsibility of making something sophisticated to handle something like I'm trying to. I'd assume that using a Key on the semantics widgets would also give the same effect if swapping them out with each other all during the same frame.

Thanks again

**Comment by goderbauer** [comment]
@dannyvalentesonos Is there anything left to do on this issue? Or should we close it?

**Comment by dannyvalentesonos** [comment]
I'd say we can close. I've got things working pretty well now. Thanks.
