### ISSUE TITLE
Metal related improvements & regressions

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#53768]
Since https://github.com/flutter/engine/pull/17431 and https://github.com/flutter/flutter/pull/53739, we observed the following improvements and regressions:

<img width="1670" alt="Screen Shot 2020-04-01 at 10 47 26 AM" src="https://user-images.githubusercontent.com/22987568/78169596-83517180-7406-11ea-9c18-a62c26f33351.png">

flutter_gallery_ios__transition_perf
- average_frame_rasterizer_time_millis improved from 6ms to 4ms.
- 90th_percentile_frame_rasterizer_time_millis improved from 16ms to 3.7ms probably due to the fix of https://github.com/flutter/flutter/issues/51809
- 99th_percentile_frame_rasterizer_time_millis regressed from 30ms to 60ms

**Comment by liyuqian** [comment]
@chinmaygarde : is the 99th percentile regression known?

**Comment by tvolkert** [comment]
Should this block a roll (be marked as TODAY)?  Are we going to re-baseline, or are there real regressions here?

**Comment by liyuqian** [comment]
While 90th percentile is just some scheduling issue, the average and 99th percentile should be real improvements and regressions that users can observe.

The question here is whether we shall accept that trade-off. @chinmaygarde has mentioned that the 99th percentile is probably due to shader compilations. He said that if it's confirmed, then we'll remove TODAY label, accept the trade-off and push forward by making Metal as our default backend on iOS.

**Comment by chinmaygarde** [comment]
> Should this block a roll?

No.

> Are we going to re-baseline, or are there real regressions here?

I am confirming if it is the shader warmup and adding traces right now but this is likely a re-baseline. Also [related to this issue](https://github.com/flutter/flutter/issues/53763#issuecomment-607478932).

**Comment by chinmaygarde** [comment]
Confirmed. I also wired up the SkSL-only Metal shader cache and added additional tracing to Skia so this should only happen once (but that hit is measured in these benchmarks).

**Comment by chinmaygarde** [comment]
Rebaselined.

**Comment by liyuqian** [comment]
As we can now measure the CPU/GPU usages on iOS, I did some more experiments to compare Metal and GL to see how much https://github.com/flutter/flutter/issues/51809 affected our average frame rasterizer time.

As expected, in gallery transitions, the CPU percentage improved only 21.21% while the average frame rasterizer time improves 57.14%. So https://github.com/flutter/flutter/issues/5180 seems to be contributing quite a lot and Metal fixed it.

Surprisingly however, in complex_layout_scroll and tiles_scroll, GL has faster average frame build and rasterizer time, but significantly worse CPU usages. @chinmaygarde @flar @iskakaushik : any idea how that could happen?

|   | metal | gl | change (gl/metal - 1) |
| --- | ---: | ---: | ---: |
|  gallery_transitions worst_frame_rasterizer_time_millis | 109.790 | 69.914 | -36.32% |
|  gallery_transitions average_frame_rasterizer_time_millis | 5.244 | 8.241 | 57.14% |
|  gallery_transitions average_frame_build_time_millis | 1.267 | 1.704 | 34.53% |
|  gallery_transitions average_cpu_usage | 23.431 | 28.401 | 21.21% |
|  gallery_transitions average_gpu_usage | 9.730 | 10.716 | 10.13% |
|   |  |  |  |
|  complex_layout_scroll_perf worst_frame_rasterizer_time_millis | 21.532 | 15.560 | -27.74% |
|  complex_layout_scroll_perf average_frame_rasterizer_time_millis | 2.057 | 2.002 | -2.66% |
|  complex_layout_scroll_perf average_frame_build_time_millis | 0.883 | 0.727 | -17.69% |
|  complex_layout_scroll_perf average_cpu_usage | 11.828 | 24.065 | 103.46% |
|  complex_layout_scroll_perf average_gpu_usage | 6.442 | 7.163 | 11.19% |
|   |  |  |  |
|  tile_scroll_perf worst_frame_rasterizer_time_millis | 9.271 | 8.077 | -12.88% |
|  tile_scroll_perf average_frame_rasterizer_time_millis | 2.077 | 1.836 | -11.63% |
|  tile_scroll_perf average_frame_build_time_millis | 1.359 | 1.037 | -23.71% |
|  tile_scroll_perf average_cpu_usage | 22.091 | 34.851 | 57.76% |
|  tile_scroll_perf average_gpu_usage | 5.698 | 5.977 | 4.90% |
