### ISSUE TITLE
Regression in platform_views_scroll_perf_ios__timeline_summary worst_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53763]
May be https://github.com/flutter/flutter/pull/53676. 

<img width="268" alt="Screen Shot 2020-04-01 at 9 53 52 AM" src="https://user-images.githubusercontent.com/1435716/78164527-b859c600-73fe-11ea-84c4-ea8c9a60ffda.png">

cc @blasten @liyuqian  @chinmaygarde

**Comment by liyuqian** [comment]
The regression does seem to start on that metal PR.

A related question to @chinmaygarde : do you know if we have any performance test plan to make sure that metal's performance is good enough for launch?

**Comment by blasten** [comment]
This is on by default now after https://github.com/flutter/engine/pull/17431.  @chinmaygarde let me know if you prefer to rebase. It looks like this is the only benchmark that got affected.

**Comment by chinmaygarde** [comment]
> do you know if we have any performance test plan to make sure that metal's performance is good enough for launch?

The average and 90th percentile scores should be better across the board ([and as confirmed here](https://github.com/flutter/flutter/issues/53768#issue-592097485)). The 99th percentile is susceptible to how expensive it is to warm up some shaders and I have seen some variance there. I do want to me sure that whats happening here though.

I did not realize the unobstructed-platform-views and Metal stuff was in one roll though. Figuring out if the shader warmup hypothesis is correct. If so, rebaselining the 99th percentile stuff for improvements across the board on 90th and average is fine.

**Comment by blasten** [comment]
> I did not realize the unobstructed-platform-views and Metal stuff was in one roll though. Figuring out if the shader warmup hypothesis is correct.

sg. Let me know what you find out.

**Comment by blasten** [comment]
Based on https://github.com/flutter/flutter/issues/53768#issuecomment-607552587, I rebaselined  this benchmark.
