### ISSUE TITLE
Allow configuration of the flutter crash reporting logic

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#53766]
Internal: b/137028157

Currently this writes out a file to the local filesystem and produces github metadata. This logic should be configurable so that the google3 client can direct developers that get crashes to buganizer and ensure that the crash report is written somewhere accessible.

fyi @jmagman  @jamesderlin

**Comment by jamesderlin** [comment]
@jonahwilliams Did you have a plan for this?  What I'm thinking is just:

1. Merge `_informUserOfCrash` (and helper functions it depends on) into the existing `CrashReportSender` class and expose it as a public method. (Possibly rename the class to just `CrashReporter` too.)
2. Add an entry for `CrashReportSender` to `AppContext`.

**Comment by jonahwilliams** [comment]
@jamesderlin that seems like a reasonable plan on its own. Is this something you're interested in working on?

**Comment by jamesderlin** [comment]
Sure.
