### ISSUE TITLE
After upgrade xcode 11.4 even simple app is created with flutter create won't work crashed

### ISSUE THREAD

**Issue by nikhil19rathore99** [flutter/flutter#53760]
![Screenshot 2020-04-01 at 8 45 33 PM](https://user-images.githubusercontent.com/32436513/78157430-93e10680-745d-11ea-8776-ca945b768109.png)
![Screenshot 2020-04-01 at 8 45 43 PM](https://user-images.githubusercontent.com/32436513/78157446-980d2400-745d-11ea-8557-4a2dc7afbbcf.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @nikhil19rathore99 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by nikhil19rathore99** [comment]
![Screenshot 2020-04-02 at 12 03 03 PM](https://user-images.githubusercontent.com/32436513/78217550-f2e46100-74d9-11ea-9355-0dba20eb2ddd.png)


> Hi @nikhil19rathore99
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

**Comment by nikhil19rathore99** [comment]
> Hi @nikhil19rathore99
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Solved !! after using flutter upgrade 
it fixed Thanks for you concern
