### ISSUE TITLE
Flutter FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by laxminarayannsharma** [flutter/flutter#53774]
Running "flutter pub get" in sample...                              2.1s
Launching lib\main.dart on RMX1801 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
com/sun/xml/bind/v2/model/annotation/AnnotationReader
> com.sun.xml.bind.v2.model.annotation.AnnotationReader

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         5.6s
Exception: Gradle task assembleDebug failed with exit code 1

Z:\SECOND PART\Flutter Project's\Cource 1\sample>flutter doctor -v
[√] Flutter (Channel master, v1.16.4-pre.69, on Microsoft Windows [Version 10.0.18363.592], locale en-IN)
    • Flutter version 1.16.4-pre.69 at Z:\Running Data\Program Files\Flutter\flutter
    • Framework revision 19e7db585d (53 minutes ago), 2020-04-01 11:16:01 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at Z:\Running Data\Program Files\Android\Windows\SdkWindows
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = Z:\Running Data\Program Files\Android\Windows\SdkWindows
    • Java binary at: Z:\Running Data\Program Files\Android\Windows\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at Z:\Running Data\Program Files\Android\Windows\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • RMX1801 • 57c28195 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment]
This crash is not related to flutter. I recommend re-running with `--verbose` to see what Android platform or gradle dependency is having an issue
