### ISSUE TITLE
[web] Flutter gallery app does not open in Firefox

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#53786]
The gallery app in the [current master](https://github.com/flutter/gallery) does not work as well as the sample gallery in the link:   https://flutter.github.io/gallery/#/ 

Other simpler examples works in Firefox both in debug/release modes.

**Comment by mdebbar** [comment]
The issue is happening in all modes (debug, profile, release). It's because of a regex feature that isn't supported in Firefox.

I filed an issue in dart sdk: https://github.com/dart-lang/sdk/issues/41327
