### ISSUE TITLE
[web]: flutter run not working in VSCODE

### ISSUE THREAD

**Issue by sambitraze** [flutter/flutter#53780]
I just used the official documentation to install flutter web . aftwr successfully upgrading the flutter when i opened and created a new project using vscode  and ran it using flutter run -d Chrome .. at first it showed syncing files to chrome den its showed that it took 30 sec to sync then i got blank white screen in localhost tab of chrome . When i created a new flutter project using andriod studio and ran it ... it worked nicely . 

PS: i was using vscode for all my flutter non web projects

**Comment by GaspardMerten** [comment]
Is it working if you run it from the terminal?

**Comment by VladyslavBondarenko** [comment]
@sambitraze when opening with VSC can you see errors in browser console?

**Comment by sambitraze** [comment]
yup i do run all flutter projects using the terminal only .. but as i
stated above it gets suck at syncing files then blanbk screen.
i enabled devtools in vscode then projects made using andriod studio is
runnng now in vscode but the projects created using vscode r stillstuck at
syncing files

**Comment by sambitraze** [comment]
no errors
 .. but as i stated above it gets suck at syncing files then blanbk screen.
i enabled devtools in vscode then projects made using andriod studio is
runnng now in vscode but the projects created using vscode r stillstuck at
syncing files

**Comment by sambitraze** [comment]
> @sambitraze when opening with VSC can you see errors in browser console?

yup i do run all flutter projects using the terminal only .. but as i
stated above it gets suck at syncing files then blanbk screen.
i enabled devtools in vscode then projects made using andriod studio is
runnng now in vscode but the projects created using vscode r stillstuck at
syncing files

**Comment by sambitraze** [comment]
> @sambitraze when opening with VSC can you see errors in browser console?

no errors
 .. but as i stated above it gets suck at syncing files then blanbk screen.
i enabled devtools in vscode then projects made using andriod studio is
runnng now in vscode but the projects created using vscode r stillstuck at
syncing files

**Comment by sambitraze** [comment]
> @sambitraze Is it working if you run it from the terminal (/powershell/cmd)?

My terminal output after this i get a whote bl;ank screen

PS E:\web\webo> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
20,173ms (!)

**Comment by GaspardMerten** [comment]
And what does the JS console says in chrome?

**Comment by VladyslavBondarenko** [comment]
@sambitraze could you provide your `flutter doctor -v` and `flutter run -d chrome --verbose`?

**Comment by sambitraze** [comment]
> And what does the JS console says in chrome?

Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by sambitraze** [comment]
flutter doctor -v

C:\Users\SAMBITRAZE>flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)
    • Flutter version 1.15.17 at C:\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\SAMBITRAZE\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\SAMBITRAZE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!







PS E:\Flutter-Web\flutter_app> flutter run -d chrome --verbose
[  +27 ms] Waiting to be able to obtain lock of Flutter binary artifacts directory:     
C:\flutter\bin\cache\lockfile
[ +240 ms] Waiting for another flutter command to release the startup lock...
[+1517 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +146 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[   +1 ms] executing: [C:\flutter/] git fetch https://github.com/flutter/flutter.git
--tags
[+3098 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[   +1 ms] From https://github.com/flutter/flutter
            * branch                HEAD       -> FETCH_HEAD
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +73 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.15.17-0-g2294d75bf
[  +12 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +128 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,       
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.      
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping      
update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping    
update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping    
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping   
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping   
update.
[  +46 ms] executing:
C:\Users\SAMBITRAZE\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +45 ms] Exit code 0 from:
C:\Users\SAMBITRAZE\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
[  +27 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,        
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.  
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[  +22 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping    
update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping    
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping   
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping   
update.
[ +382 ms] Generating
E:\Flutter-Web\flutter_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +147 ms] Launching lib\main.dart on Chrome in debug mode...
[  +76 ms] Serving DevTools at http://127.0.0.1:52907

[   +8 ms] Updating assets
[ +142 ms] Syncing files to device Chrome...
[  +70 ms] Generating
E:\Flutter-Web\flutter_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +67 ms] <- reset
[  +13 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc        
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\SAMBIT~1\AppData\Local\Temp\flutter_tool.6036db51-74e6-11ea-b917-c465162df35f\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json    
--packages E:\Flutter-Web\flutter_app\.packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\SAMBIT~1\AppData\Local\Temp\flutter_tools.6036db52-74e6-11ea-b917-c465162df35f 
--filesystem-scheme org-dartlang-app --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +55 ms] <- compile org-dartlang-app:///web_entrypoint.dart
[+19302 ms] Syncing files to device Chrome... (completed in 19,495ms, longer than
expected)
[   +3 ms] Synced 20.7MB.
[   +1 ms] <- accept
[ +341 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:52931/devtools/browser/b8fd73d9-dd72-47fd-9223-80704850f277

**Comment by yoR-rihsihS** [comment]
im also having the same problem...

**Comment by VladyslavBondarenko** [comment]
@sambitraze 
could you check is it the same when using dev channel?

**Comment by yoR-rihsihS** [comment]
the problem is same but im on beta channel

**Comment by sambitraze** [comment]
> @sambitraze
> could you check is it the same when using dev channel?

i tried just now with dev it worked but i will try it for few more projevts to see if its still starts to bug in between
within 2 3 days dont close the issue

**Comment by sambitraze** [comment]
> the problem is same but im on beta channel

switch to dev channel its working fine in dev
