### ISSUE TITLE
[devicelab][LUCI] Prototype devicelab to LUCI migration

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#53789]
Enabling testbeds as LUCI bots
- [x] Provision 1 linux/android bot
- [x] Provision 1 mac/android bot
- [x] Provision 1 mac/iOS bot
- [x] Enable code signing on the swarming user
- [x] Enable using secrets with cloudkms or secret manager in the recipe
- [ ] Provision 1 windows/android bot
- [x] Add the bots to luci.flutter.staging pool by corp domain name or IP address
- [x] Update bot_config.py to report required dimensions
- [x] Update bot_config.py to report device healthiness

Creating a recipe that runs devicelab tests
- [x] Create a recipe that runs a specific devicelab test
- [x] Make the recipe reads manifest.yaml and be able to run all tests in staging
- [x] Add a handler that receives benchmark data
- [x] Modify cocoon agent to upload benchmark data

Evaluating the efficiency
- [ ] Devicelab test execution time.
- [ ] The time to complete a "row" (all devicelab tests of a commit).

**Comment by digiter** [comment]
Provisioned
* a linux/android bot: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-8
* a mac/android bot: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-22
* a mac/ios bot: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9

**Comment by godofredoc** [comment]
All the tasks outlined here are now complete.
