### ISSUE TITLE
`flutter generate` behavior should be clarified

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#53794]
Running `flutter generate` (in a project that uses `build_runner`) prints:

```
$ flutter generate
generating build script...                                         33.3s
starting build daemon...                                            1.1s
$
```
I think that this is a bit confusing because it tells me that it started a daemon but didn't mention anything about stopping it.  Is it still running and doing codegen automatically when files change? (I believe that the answer is no, the build daemon is not still running.)

It'd be clearer if we did one of:
* Print "starting build" instead, avoiding "daemon".
* Print a message when the build daemon is stopped.
* Offer a mechanism to have a persistent build daemon, like `pub run build_runner watch`.

Additionally, it seems weird on the surface that "generating build script" takes so long. `flutter generate` prints "generating build script", but it's actually doing a lot more under the hood (e.g. building a snapshot file) that it's not reporting.  In comparison, `pub run build_runner build` provides a better breakdown:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 458ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 14.1s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 872ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 1 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 5ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.8s elapsed, 0/4 actions completed.
[INFO] Generating SDK summary completed, took 4.8s

[INFO] 5.9s elapsed, 0/4 actions completed.
[INFO] 7.0s elapsed, 1/4 actions completed.
[INFO] 11.0s elapsed, 2/4 actions completed.
[INFO] 12.1s elapsed, 2/4 actions completed.
[INFO] 17.8s elapsed, 3/4 actions completed.
[INFO] 19.0s elapsed, 4/4 actions completed.
[INFO] Running build completed, took 19.1s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 57ms

[INFO] Succeeded after 19.1s with 2 outputs (9 actions)
```
But also note that an initial `pub run build_runner build` takes me ~20s but an initial `flutter generate` consistently takes me >30s.  I'm not sure what's causing the >10s discrepancy. (`flutter -v generate` doesn't offer much insight; after printing `Running "flutter pub get" in flutter_tool...` there's a 30s gap with no output.)

(I'm currently at 19e7db585.)

**Comment by jonahwilliams** [comment]
Superseded by https://github.com/flutter/flutter/issues/61508
