### ISSUE TITLE
IconButton doc link point to the wrong website

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#53792]
The `IconButton` docs have a link on *touch target size* to: https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size. But this URL doesn't exists anymore, so it redirects to: https://material.io/design/layout/understanding-layout.html#usage, which doesn't have any information regarding *touch target size*.

The new link that informs about *touch target size* is this one: https://material.io/design/layout/spacing-methods.html#touch-targets

**Comment by VladyslavBondarenko** [comment]
Closing since https://github.com/flutter/flutter/pull/53793 is merged
