### ISSUE TITLE
The method validate was called on null

### ISSUE THREAD

**Issue by KvngAlka** [flutter/flutter#53796]
I/SurfaceView(16837): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{205ab00 V.E...... ......I. 0,0-720,1206}
I/SurfaceView(16837): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{205ab00 V.E...... ......I. 0,0-720,1206}
E/flutter (16837): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'validate' was called on null.
E/flutter (16837): Receiver: null
E/flutter (16837): Tried calling: validate()
E/flutter (16837): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (16837): #1      _SignUpState.build.<anonymous closure> (package:i2i_tradehood/Screens/Authentication/sign_up.dart:121:48)
E/flutter (16837): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (16837): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (16837): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16837): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (16837): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (16837): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (16837): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (16837): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (16837): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16837): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16837): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16837): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16837): #14     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (16837): #15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (16837): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (16837): #17     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (16837): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (16837):

**Comment by jonahwilliams** [comment]
This is a bug in your code, see the stack trace that points directly to `i2i_tradehood/Screens/Authentication/sign_up.dart`:

E/flutter (16837): #1 _SignUpState.build. (package:i2i_tradehood/Screens/Authentication/sign_up.dart:121:48)

Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
