### ISSUE TITLE
Should customer tests be allowed to have a version constraint on Flutter?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#53801]
The gallery customer test package haas a version constraint on Flutter. Its fairly loose, however the are a number of scenarios where it could break through no fault of the PR author:

1. Gallery updates minimum version constraint: If a contributor is working from a sufficiently old base that despite pulling master, their version is something like `PRIOR_VERSION+LARGE_COMMIT#`. User has to recreate PR to fix

2. Flutter updates a major version. ToT is broken until the customer test is broken.

The version numbers on master are somewhat arbitrary anyway. I understand why applications would use them, but we should avoid scenarios where there is nothing a contributor can do to green the tree - or where they need to recreate a PR from scratch to massage the version number.

@Hixie

**Comment by jonahwilliams** [comment]
For reference: https://github.com/flutter/gallery/blob/master/pubspec.yaml#L8

**Comment by Hixie** [comment]
Not sure I understand #1.
#2 is valid, though mostly only because we don't rev version numbers via PR.

When #2 happens I would just disable the tests and work with the test author to fix their project so they can be re-enabled. We can certainly update the documentation to recommend not pinning the version number, but unless we have a way to verify it, some will slip through.

**Comment by jonahwilliams** [comment]
The way we do version approximations on master, the version of flutter in a PR will always be fixed at some # pre/post the last dev release. So if I start working on a PR when flutter is at 1.2.3, a month later even if I've pulled the latest flutter into my PR I'll still be at `1.2.3-post.<large number>`. The fix (that I've figured out, not really knowing git) is to checkout a new branch and merge the PR into that branch.

I could see this being confusing for new or occasional contributors

**Comment by jonahwilliams** [comment]
For a specific example, I've been working on https://github.com/flutter/flutter/pull/52180 for about a month. The reported flutter version in that PR has drifted pretty significantly, and now the customer testing shard is failing due to the version issue. My only solution requires me to recreate the PR
