### ISSUE TITLE
[web] Include favicon.ico file to the web build 

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#53807]
Use the app icon to generate the favicon.ico

**Comment by nateshmbhat** [comment]
@jonahwilliams

**Comment by jonahwilliams** [comment]
The web templates already have a favicon.png. Nothing stops you from adding your own favicon if you want ico format, though all major browsers support png favicon (https://caniuse.com/#feat=link-icon-png)

**Comment by nateshmbhat** [comment]
Issue is that even the favicon.png file is not added to the build folder when I build it.

**Comment by nateshmbhat** [comment]
sorry my bad :( 
it works :)
