### ISSUE TITLE
flutter problem access server

### ISSUE THREAD

**Issue by kardotinambunan12** [flutter/flutter#53806]
I bought a multi vendor fluxstore application 1.6.5. if you have heard.
first I tried using the defauld fluxstore server and it worked.
The problem arises when I change the defauld server connection with the server that I have. I think there is someone who gives input on what I will do next

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
