### ISSUE TITLE
Intergration test disabled textfield

### ISSUE THREAD

**Issue by niktses** [flutter/flutter#53815]
Intergration test does not press the gesture detector if textformField (textField?) is disabled; like textformfield consumes the event.

I use it more or less like that:

          GestureDetector(
            key: ValueKey("key"),
            behavior: HitTestBehavior.translucent,
            onTap: onTap,
            child: Container(
              child: TextFormField(
                enabled: false,
              ),
            ),
          ),

and during test:

final button = find.byValueKey("key");
    await driver.waitFor(button);
    await driver.tap(button);

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @niktses 

It does fail when `TextFormField` when enable is false and pass when `enabled: true` 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: GestureDetector(
            key: ValueKey("key"),
            behavior: HitTestBehavior.translucent,
            onTap: () {
              print('onTap');
            },
            child: Container(
              child: TextFormField(
                enabled: false,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

### app.dart
```
import 'package:flutter_driver/driver_extension.dart';
import 'package:dev_flutter/main.dart' as app;

void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();

  // Call the `main()` function of the app, or call `runApp` with
  // any widget you are interested in testing.
  app.main();
}
```


### app_test.dart
```
// Imports the Flutter Driver API.
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('App', () {
    final button = find.byValueKey("key");

    FlutterDriver driver;
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('test disabled textfield', () async {
      await driver.waitFor(button);
      await driver.tap(button);
    });
  });
}
```

Thank you for your contribution

**Comment by HansMuller** [comment]
This is working as intended, see https://api.flutter.dev/flutter/material/TextField/onTap.html

**Comment by niktses** [comment]
The onTap on TextField does not disable the textfield. If i set it like that the selection works, the keyboard opens, and on top of that onTap is called. That is not what i want. I want to have the textfield disabled and used only as a ui element for consistency with the rest of the app. I want only the onTap method to be called that is why i disabled it and wrapped it with the GestureDetector. If i set both enabled = false and onTap on Textfield, onTap does not work.

My code works fine when used normally. The problem appears only in intergration testing where tap is not recognized.
