### ISSUE TITLE
SUGGESTION based on https://deno.land by Ryan Dahl

### ISSUE THREAD

**Issue by cindRoberta** [flutter/flutter#53811]
how about you eliminated pubspec.yaml, turning local downloaded repositories centralized as on Deno? I recommend using deno and get inspired on the runtime practicalities and organization

the Flutter runtime is consuming a lot of RAM e not deallocating when closed

**Comment by jonahwilliams** [comment]
I don't really think this has anything to do with Flutter, which uses Dart and not JavaScript/TypeScript.

**Comment by cindRoberta** [comment]
> I don't really think this has anything to do with Flutter, which uses Dart and not JavaScript/TypeScript.

Flutter too manages packages, I dont know if over a layer of pub, anyway, I suggest keeping an eye on Deno, it's the next revolution on package management and safety
