### ISSUE TITLE
Stack should either loosen or tighten constraints, not pass them through

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#5381]
Today, Stack passes its constraints through to its children, which has confused a number of people.  Instead, the Stack should loosen its constraints by default but probably have an option to tighten them instead.

We might want to change the default alignment for stack at the same time.  Currently we default to a top-left alignment but we should probably default to a center alignment.

/cc @Hixie @apwilson

**Comment by eseidelGoogle** [comment]
Does this need to be included in api stability?

**Comment by abarth** [comment]
Yes.  We won't be able to change the layout rules for Stack once we declare API stability.

**Comment by Hixie** [comment]
I tried doing this, but ran into https://github.com/flutter/flutter/issues/9408.
