### ISSUE TITLE
Flutter navigation issue

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#53812]
Can someone explain why  `efeioi` not printing when it is back from pageE?

**Page A**

```
Navigator.pushNamed(context, PageB.ROUTE).then((onValue) {
               print("efeioi");
              });
```
**Page B**

```
  Navigator.of(context)
              .pushReplacementNamed(PageC.ROUTE, arguments: onValue);
```
**PageC**

```
 Navigator.pushNamed(context, PageD.ROUTE,
                                        arguments: onValue);
```
**PageD**

`    Navigator.pop(context);  // back to Page C`

**Page C**

   ```
Navigator.pushNamed(context, PageE.ROUTE,
                                        arguments: onValue);
```
**Page E**

` Navigator.of(context).popUntil(ModalRoute.withName(PageA.ROUTE));`

**Comment by chunhtai** [comment]
This should be asked in stackoverflow. If you think there is bug in the framework, please provide a complete reproducible example and outline the steps to reproduce.

**Comment by tony123S** [comment]
@chunhtai 

I have created a new repo for this 

https://github.com/tony123S/navigation

Please have a look. Thank,

**Comment by tony123S** [comment]
@chunhtai But when it back from E, the value is not printing.

**Comment by chunhtai** [comment]
When you called 
'''Navigator.of(context)
              .pushReplacementNamed(PageC.ROUTE, arguments: onValue);'''

The PageB is replaced by PageC and is no longer in the route history. When you call popUntil, it will not re-complete the PageB because it was already removed

**Comment by tony123S** [comment]
@chunhtai  thanks.

Not sure is this consider bug ?

https://github.com/flutter/flutter/issues/54124
