### ISSUE TITLE
TextStyle of Text: when i set height: 1.1 for Text line gap, it is lower than nothing to set 

### ISSUE THREAD

**Issue by a530148758** [flutter/flutter#53817]
**Flutter version: 1.12.13+hotfix.8**

**Set the height: 1.1**
`Text("Didn't find something you like?",style: TextStyle(height: 1.1)`
![2171585820046_ pic](https://user-images.githubusercontent.com/25213944/78233672-a8c6a400-7508-11ea-9ca1-1bd4fd6f3629.jpg)

**Set noting for height**
`Text("Didn't find something you like?")`
![2191585820326_ pic](https://user-images.githubusercontent.com/25213944/78233776-d3b0f800-7508-11ea-8afb-1fbfe8b4d7e4.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @a530148758 
It's said in doc about this https://api.flutter.dev/flutter/painting/TextStyle-class.html
in the 'Line height' paragraph:
`For most fonts, setting height to 1.0 is not the same as omitting or setting height to null.`
Closing, as this isn't an issue,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by a530148758** [comment]
I mean if set height: 1.1, there should be a small line spacing between each line, right? but no.  it is normal on flutter 1.7.8 and 1.9.1
