### ISSUE TITLE
[web] Image.network rotates image from firebase storage

### ISSUE THREAD

**Issue by Alic94** [flutter/flutter#53820]
Hello there,
I have the problem, that Image.network (and NetworkImage) displays an image from firebase rotated in the webapp. But if I open the same url in a browser, the orientation is correct.
I could observe, that the orientation in safari mobile is correct, too.

So it seems there is an issue with the exif file of the image depending on the browser the webapp runs in.

Screenshot webap: https://i.stack.imgur.com/7m5vo.jpg

Screenshot Url in new tab in the browser: https://i.stack.imgur.com/b5Hjo.jpg

Can somebody help me?

My Code:

```
import 'package:flutter/material.dart';
import 'package:firebase/firebase.dart' as fb;
import 'dart:js' as js;

class NetworkImageError extends StatefulWidget {
  @override
  _NetworkImageErrorState createState() => _NetworkImageErrorState();
}

class _NetworkImageErrorState extends State<NetworkImageError> {
  String DownloadUrl='https://upload.wikimedia.org/wikipedia/commons/a/ad/Placeholder_no_text.svg'; //Placeholder

  GetURL()async{
    var _DownloadURL = await fb
        .storage()
        .refFromURL('gs://myBucket')
        .child('Pb_0000.png')
        .getDownloadURL();
    setState(() {
      DownloadUrl=_DownloadURL.toString();
    });
  }

  @override
  void initState(){
    GetURL();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: GestureDetector(
            onTap: (){
              js.context.callMethod("open", [DownloadUrl]);
            },
            child: Image.network(DownloadUrl)),
      ),
    );
  }
}
```
Flutter doctor
```
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.17763.1098], locale de-DE)
    • Flutter version 1.15.17 at C:\Users\dalic\Documents\Apps\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\dalic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.43.2)
    • VS Code at C:\Users\dalic\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.162
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

**Comment by VladyslavBondarenko** [comment]
Hi @Alic94 
does it happen when `flutter run -d chrome`? or with other browsers/devices?
does it happen with other images?
Could you share the `DownloadUrl` to check?
I can't reproduce it.

**Comment by Alic94** [comment]
Hi @VladyslavBondarenko 
the orientation is wrong when` flutter run -d chrome` and on the android browser (chrome or Samsung Internet).
It is only on safari mobile correct.

To reproduce just use the following code:
```
import 'package:flutter/material.dart';
import 'dart:js' as js;

class NetworkImageError extends StatefulWidget {
  @override
  _NetworkImageErrorState createState() => _NetworkImageErrorState();
}

class _NetworkImageErrorState extends State<NetworkImageError> {
  String DownloadUrl='https://firebasestorage.googleapis.com/v0/b/k1ckstart.appspot.com/o/Pb_0000.png?alt=media&token=8abc4d58-989a-4890-8d0b-e216076337f7'; //Placeholder

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: GestureDetector(
            onTap: (){
              js.context.callMethod("open", [DownloadUrl]);
            },
            child: Image.network(DownloadUrl)),
      ),
    );
  }
}
```
If you tap on the image, a new tab opens and displays the image with correct orientation, although the same URL is used.

**Comment by Alic94** [comment]
Is there a workaround to display the image from the URL correctly? 

Or do I have to wait (months) and see if this one is gonna be fixed?

**Comment by VladyslavBondarenko** [comment]
@Alic94 
before it's fixed, as workaround you can use https://api.flutter.dev/flutter/widgets/Transform/Transform.rotate.html or https://api.flutter.dev/flutter/widgets/RotatedBox-class.html
to rotate the Image

**Comment by Alic94** [comment]
@VladyslavBondarenko 
Is this really a workaround? 
It would be necessary to know, that EVERY picture has to be rotated the same. So for Safari Mobile it would cause a wrong orientation, that has been correct before.

Or am I wrong?

**Comment by VladyslavBondarenko** [comment]
Persists with current master `1.21.0-6.0.pre.41`

https://flimg.netlify.app/#/

Reproduced with Mi Browser on Redmi Note 7 Android 9 (API 28).

<details>
 <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/17024977/88672338-03a38d00-d0f0-11ea-9b58-6bb49dfd4fbe.png)

</details>

The image is shown correctly (vertically) with Chrome on the same Android and Safari on iOS 13.6 device.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.41, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.41 at /Users/nevercode/dev/flutter
    • Framework revision 39fa00201d (3 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (5 available)            
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by SeanOThomas** [comment]
I'm seeing this issue on latest stable `3.0.2 ` for Chrome only.

**Comment by OleFriedrich** [comment]
> I'm seeing this issue on latest stable `3.0.2 ` for Chrome only.

https://github.com/flutter/flutter/issues/106342 we created an issue for this, is this the behavior you are experiencing?

**Comment by SeanOThomas** [comment]
@OleFriedrich Ah yes, #106342 looks like the same issue.

**Comment by vikivyas** [comment]
Hi... I am getting this problem after flutter sdk updated by me (I regret of doing it). Please find my please find my observations to the problem. "this mainly happens with image are not square."

**Comment by darshankawar** [comment]
Verified this issue by running [firebase_storage plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example/lib) on web platform. Uploaded a local file as shown below which was stored properly in the backend:

1. Image uploaded:

<img width="359" alt="Screenshot 2023-01-04 at 4 49 58 PM" src="https://user-images.githubusercontent.com/67046386/210550720-40e62021-590a-4943-ae3a-52582bbdeec2.png">

2. Above image was uploaded in the backend:

<img width="305" alt="Screenshot 2023-01-04 at 5 31 07 PM" src="https://user-images.githubusercontent.com/67046386/210550836-7cc62d75-1ec2-44ff-8868-b395208015ee.png">

3. Running the plugin example and then retrieving the download url:

https://firebasestorage.googleapis.com/v0/b/triage-79c7c.appspot.com/o/playground%2Fsome-image.jpg?alt=media&token=3d7016f4-86e4-4f7b-95be-2fa334953cb4  shows the image in correct orientation, ie, the image is not rotated ( you can access this url directly which shows the correct oriented image)

<img width="611" alt="Screenshot 2023-01-04 at 5 34 07 PM" src="https://user-images.githubusercontent.com/67046386/210551363-03f1e3d3-759f-44b1-8b05-db0c9a0c79d8.png">

@Alic94 and everyone who faced this issue, please try above and see if you still get the originally reported behavior or it is working as expected at your end.
