### ISSUE TITLE
[Share] Why am i not able to add image in the share plugin?

### ISSUE THREAD

**Issue by maheshkumar2150** [flutter/flutter#53825]
There are few share plugins for flutter. Most of them are not up to date.
This **Share plugin** is maintained by flutter and very easy to use.

I want to share text along with an image to invite friends.
But Share plugin is limited and unable to send image.

Can you please consider to add this feature in Share plugin?

**Comment by VladyslavBondarenko** [comment]
Hi @maheshkumar2150 
Please follow up on https://github.com/flutter/flutter/issues/9817, https://github.com/flutter/flutter/issues/19607, https://github.com/flutter/flutter/issues/36894
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by maheshkumar2150** [comment]
I just checked those links sir.
I am really disappointed. Such a beautiful framework which lacks an important feature.
Many flutter developers have already requested this feature.

I have half finished flutter and disappointed to see that there is no good plugin for image sharing.
Have to drop this project from flutter and move to react

But i got motivated myself and learning android from udacity :-)

Thank you sir.
No need to open. It has been discussed already and your team is not convinced.
