### ISSUE TITLE
[VoiceOver] Using a PageView with children that have a Semantics widget with explicitChildNodes set to true crashes on page view scrolling

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#53827]
When using a PageView with VoiceOver turned on, and the children are wrapped by Semantic widgets that have explicitChildNodes set to true, scrolling causes a crash almost every time.

The following code reproduces this consistently after scrolling left and right:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: SemanticsPageViewHomePage(),
    );
  }
}

class SemanticsPageViewHomePage extends StatefulWidget {
  const SemanticsPageViewHomePage();

  _SemanticsPageViewHomePageState createState() => _SemanticsPageViewHomePageState();
}

class _SemanticsPageViewHomePageState extends State<SemanticsPageViewHomePage> {

  List<Widget> _children = [];

  Widget _buildPage() {
    return Semantics(
      explicitChildNodes: true,
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text("test 1"),
            Text("test 2")
          ],
        ),
      ),
    );
  }

  void _buildChildren() {
    _children.clear();
    _children.add(_buildPage());
    _children.add(_buildPage());
    _children.add(_buildPage());
  }

  @override
  void initState() {
    _buildChildren();

    super.initState();
  }

  @override
  void didUpdateWidget(SemanticsPageViewHomePage oldWidget) {
    _buildChildren();

    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        body: Column(
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Expanded(
              child: PageView(
                children: _children,
              ),
            ),
            Container(
              color: Colors.red,
              height: 60
            )
          ],
        )
    );
  }
}
```

I am testing on an iPhone 6 running iOS 12.

**Comment by dannyvalentesonos** [comment]
flutter doctor -v
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.16.2 at /Users/danny.valente/Library/flutter/1.16.2-dev
    • Framework revision 58cad787d8 (10 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by VladyslavBondarenko** [comment]
Checked, it doesn't crash with Android TalkBack (but does with iOS VoiceOver)

**Comment by dannyvalentesonos** [comment]
Another very easy way to reproduce this is with the Add2App experience, when closing the flutter view using VoiceOver on a widget that is in the view. Doing so causes an instant crash with the following output:

[FlutterSemanticsObject accessibilityContainer]: message sent to deallocated instance 0x1517384c0

I'm pretty sure these crashes are related. If you don't think so, I can log this one separately.

**Comment by goderbauer** [comment]
Does it log any kind of message for the crash reported in your first post? Can you paste that into the bug here?

**Comment by goderbauer** [comment]
Tagging this engine since

```
[FlutterSemanticsObject accessibilityContainer]: message sent to deallocated instance 0x1517384c0
```

looks like a crash in the native a11y bridge.

**Comment by dannyvalentesonos** [comment]
No, when running the Flutter app, it just crashes and I don't see any log anywhere. I never use a Flultter app, so if there's a way for me to get logs that I'm not doing, let me know. Thanks.

**Comment by dannyvalentesonos** [comment]
@goderbauer Should I log the second crash (from Add2App experience) separately? That one is much much more critical for us and blocks our testing.

**Comment by goderbauer** [comment]
Probably worthwhile to file a separate issue for that one.

**Comment by gaaclarke** [comment]
@dannyvalentesonos {meta} Thanks for the report.  Please provide full reproduction code when filing issues.  It's less ambiguous and saves me from having to figure out the example before I tackle the issue =)

I was able to reproduce it.  I'll update the sample code.  I typically had to scroll right then left to get it (use 3 fingers when in VoiceOver):
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001b2c86090 in objc_msgSend ()
#1	0x0000000104b6ab88 in ::-[SemanticsObject globalRect]() at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm:369
#2	0x0000000104b6a970 in ::-[SemanticsObject accessibilityFrame]() at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm:363
#3	0x00000001be323d1c in -[NSObject(AXPrivCategory) _iosAccessibilityAttributeValue:] ()
...
#15	0x00000001b6fe863c in UIApplicationMain ()
#16	0x0000000104734dfc in main at /Users/aaclarke/dev/flutter-examples/pageview_crash/ios/Runner/AppDelegate.swift:5
#17	0x00000001b2d64360 in start ()
```
```
  - (CGRect)globalRect {
    SkMatrix44 globalTransform = [self node].transform;
    for (SemanticsObject* parent = [self parent]; parent; parent = parent.parent) {
->    globalTransform = parent.node.transform * globalTransform;
    }
  ...
```
```
(lldb) p parent
(SemanticsObject *) $0 = 0x000000010c0b1370
(lldb) p parent.node
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.
```

**Comment by gaaclarke** [comment]
Run with Zombies Objects:
```
2020-04-02 17:50:40.744260-0700 Runner[9324:2877392] *** -[FlutterSemanticsObject node]: message sent to deallocated instance 0x121eb1fb0
```

Weird that I'm seeing something different than the original report.

**Comment by gaaclarke** [comment]
SemanticsObject holds on to its [parent](https://github.com/flutter/engine/blob/abc72933e70c3695b10580ae157c1321d912ba65/shell/platform/darwin/ios/framework/Source/accessibility_bridge.h#L46:L46) weakly.  In it's dealloc method it [attempts to nil out](https://github.com/flutter/engine/blob/abc72933e70c3695b10580ae157c1321d912ba65/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L199:L199) its children's references to itself.

We could be:
1) removing a child from a parent, but not clearing out the parent property
2) setting the child's parent as an already dealloced object

**Comment by dannyvalentesonos** [comment]
> @dannyvalentesonos {meta} Thanks for the report. Please provide full reproduction code when filing issues. It's less ambiguous and saves me from having to figure out the example before I tackle the issue =)
> 
> I was able to reproduce it. I'll update the sample code. I typically had to scroll right then left to get it (use 3 fingers when in VoiceOver):
> 
> ```
> Thread 1 Queue : com.apple.main-thread (serial)
> #0	0x00000001b2c86090 in objc_msgSend ()
> #1	0x0000000104b6ab88 in ::-[SemanticsObject globalRect]() at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm:369
> #2	0x0000000104b6a970 in ::-[SemanticsObject accessibilityFrame]() at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm:363
> #3	0x00000001be323d1c in -[NSObject(AXPrivCategory) _iosAccessibilityAttributeValue:] ()
> ...
> #15	0x00000001b6fe863c in UIApplicationMain ()
> #16	0x0000000104734dfc in main at /Users/aaclarke/dev/flutter-examples/pageview_crash/ios/Runner/AppDelegate.swift:5
> #17	0x00000001b2d64360 in start ()
> ```
> 
> ```
>   - (CGRect)globalRect {
>     SkMatrix44 globalTransform = [self node].transform;
>     for (SemanticsObject* parent = [self parent]; parent; parent = parent.parent) {
> ->    globalTransform = parent.node.transform * globalTransform;
>     }
>   ...
> ```
> 
> ```
> (lldb) p parent
> (SemanticsObject *) $0 = 0x000000010c0b1370
> (lldb) p parent.node
> error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
> The process has been returned to the state before expression evaluation.
> ```

@gaaclarke I am so sorry. I just noticed I pasted the wrong code. I do apologize for that. I'm going edit the post with the correct code.

**Comment by dannyvalentesonos** [comment]
Actually,  that is the code. Running that code with nothing else reproduces the issue. I'm not sure what was ambiguous?

**Comment by gaaclarke** [comment]
> Actually, that is the code. Running that code with nothing else reproduces the issue. I'm not sure what was ambiguous?

Thanks, I already edited it for you to be a complete example.  A complete example has a `main` and all the required `import`s.  I'm not sure why sometimes people omit those, takes half a second to paste them, takes minutes to recreate them.

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/17499.  Fixes the bug.  I'm going to spend some time trying to make this code a bit cleaner and safer.
