### ISSUE TITLE
CameraController.value.isTakingPicture is always true

### ISSUE THREAD

**Issue by vodemn** [flutter/flutter#53828]
## Steps to Reproduce

1. Navigate to https://pub.dev/packages/camera#-example-tab-.
2. Run the example application
3. Take a picture multiple times

**Expected results:** Taking picture on tap

**Actual results:** Unable to take a picture, because controller.value.isTakingPicture is always true. As a result, exif data from an image is null, which makes my app unable to functionate properly

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter_stable
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vadim\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\vadim\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\vadim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Redmi 5 Plus • 28d268180005 • android-arm64 • Android 9 (API 28)

• No issues found!

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @vodemn 
can you please provide your `flutter run --verbose` and print `controller.value.isTakingPicture` while taking pictures from your device and also can you please try other devices, maybe if it MIUI specfic?

I tried to reproduce on Samsung Galaxy M30, no issues
Thank you

**Comment by vodemn** [comment]
I'm running Resurrection Remix ROM, android 9.0.
I've tested on other devices (1+1, 1+5, 1+5T) and it works properly.

**Comment by TahaTesser** [comment]
Hi @vodemn 
if it works on regular Android distribution then it's not an issue
This could be because of changes made in Custom ROM
if you disagree please write in the comments and I will reopen it
 Thank you
