### ISSUE TITLE
[add-to-app] Document what CocoaPods does to embed Flutter App in a native app? And How Flutter app embeds into Native Android App?

### ISSUE THREAD

**Issue by m-zaink** [flutter/flutter#53821]
'm trying to understanding how the whole process of add-to-app in flutter works.

As to how frameworks are generated and how they're added.

Although my primary intention is to learn about how it does in iOS, I would appreciate if you explain for both Android and iOS.

**Comment by jmagman** [comment]
Did you read https://flutter.dev/docs/development/add-to-app/android/project-setup and https://flutter.dev/docs/development/add-to-app/ios/project-setup?  Is there something specific that needs expanding on in those docs?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
