### ISSUE TITLE
Regression in flutter_gallery_ios32__transition_perf worst_frame_rasterizer_time_millis, 99th_percentile_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53832]
Looks like maybe this engine roll.

![Screen Shot 2020-04-02 at 9 28 13 AM](https://user-images.githubusercontent.com/1435716/78273914-4b106880-74c4-11ea-86af-88d0f76cb4cf.png)

cc @gw280 (this week's engine sheriff) and @liyuqian

**Comment by kf6gpe** [comment]
Forgot the relevant PR. It's https://github.com/flutter/flutter/pull/53403. Thanks to @tvolkert for the prodding! :)

**Comment by liyuqian** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/53581. Issue #53581 previously didn't have the regression label and that's probably why we missed it and created this duplicate issue?

**Comment by tvolkert** [comment]
Yep, looks like a dup - closing.

**Comment by kf6gpe** [comment]
This looks like it's regressed again, although it may be returning to pre-regression numbers after the most recent commit. See for example 99th_percentile_frame_rasterizer_time_millis and worst_frame_rasterizer_time_millis. 
![Screen Shot 2020-05-15 at 9 14 02 AM](https://user-images.githubusercontent.com/1435716/82072350-72924d80-968c-11ea-8556-c821c7d5733a.png)

If it's not a lab issue, it looks like it started with https://github.com/flutter/flutter/pull/57252.

**Comment by kf6gpe** [comment]
Whoops --- this is the dup issue. I'll file this where it belongs.
