### ISSUE TITLE
Scramble PIN 

### ISSUE THREAD

**Issue by r4v3r23** [flutter/flutter#53836]
this app has a PIN entry and I would like for the numbers to scramble themselves everytime I enter the app. how can i do this?

lock_screen.dart:

https://github.com/InvertedX/sentinelx/blob/3ec5db42f45aeecca7511772bf623d7ceff2563b/lib/screens/Lock/lock_screen.dart

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
