### ISSUE TITLE
Video Player Plugin installing error :  Connection terminated during handshake

### ISSUE THREAD

**Issue by ShohidulProgrammer** [flutter/flutter#53839]
when I added the Video Player Plugin it shows the error: 
Connection terminated during handshake
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

**Comment by iapicca** [comment]
Hi @ShohidulProgrammer 
can you please provide your `flutter doctor -v` 
and your `flutter pub get --verbose`
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
