### ISSUE TITLE
Provide a way to disable unobstructed platform views in the iOS embedding

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#53841]
Add an embedding flag that allows to disable unobstructed platform views. This way, the new behavior can be easily disabled without reverting the changes in the engine.

**Comment by chinmaygarde** [comment]
Please reconsider this. We have added flags in the past that were meant to be temporary but have been in the tree for years. Adding additional flags also makes it easy to sneak in changes into the tree that will trip presubmits and tests both in the tree and downstream. If this happens long enough, the change becomes progressively more unwieldy and removing the flag harder to remove.

I don't want to block progress on an absolutely critical use case though. If the flag is necessary, please elucidate the use-case (with clear exit criteria) and let's evaluate them as a team.

**Comment by pcsosinski** [comment]
what's the status on this?  if we want to put something in for 1.17 we need it soon.

**Comment by chinmaygarde** [comment]
In the linked PR, Amir mentioned that hotfixes were a viable option. I'd go for that instead of causing churn in the public API.

**Comment by pcsosinski** [comment]
@amirh @blasten can we close this issue as obsolete based on Chinmay's comment?

**Comment by blasten** [comment]
Sounds good

**Comment by pcsosinski** [comment]
removing CP label as this is obsolete
