### ISSUE TITLE
Flutter Web: TextFormField OR InputDecoration using an RTL language (e.g. Hebrew) is getting stuck after trying to erase after space character

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#53842]
TextFormField OR InputDecoration (Tried both) with RTL language is getting stuck after trying to erase after space character.

Reproduce: use TextFormField and write in Hebrew.
Type for instance "שלום עולם". hit backspace all the way. result: the word "שלום" was not deleted because of the space.

**Comment by iapicca** [comment]
Hi @mikron123 
can you please provide your `flutter doctor -v` ,
and if possible a reproducible minimal code sample.
Thank you

possibly related to https://github.com/flutter/flutter/issues/47745

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
