### ISSUE TITLE
google_sign_in: auto-publish API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5385]
We should probably update http://flutter.github.io/google_sign_in/ manually. It would be super cool to automate the publishing of that site.

Our users are finding these sites and asking questions about them :)

**Comment by mit-mit** [comment]
I'm triaging all plugin bugs, and I don't understand that what this one covers. The link 403's. Can you elaborate?

**Comment by eseidelGoogle** [comment]
This was a plugin we wrote on the old mojo plugin architecture for login using google_sign_in.  When we write a new one, we'll need it documented somewhere, but we can have a new bug for that.
