### ISSUE TITLE
[Android Add2App] Crash when trying to create a flutter fragment with RenderMode.texture

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#53857]
When trying to create a Flutter fragment with RenderMode.texture, I get a crash at launch of the flutter view.

From code inspection, I found this in FlutterView.java

```
private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterSurfaceView flutterSurfaceView) {
    super(context, attrs);

    this.flutterSurfaceView = flutterSurfaceView;
    this.renderSurface = flutterSurfaceView;

    init();
  }

  private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterSurfaceView;

    init();
  }
```

In the second constructor, the second line should be this instead:
```
this.renderSurface = flutterTextureView;
```

**Comment by dannyvalentesonos** [comment]
@matthew-carroll @dnfield

**Comment by dannyvalentesonos** [comment]
flutter doctor -v
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.16.2 at /Users/danny.valente/Library/flutter/1.16.2-dev
    • Framework revision 58cad787d8 (10 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by dnfield** [comment]
We.. need a test covering this :\

**Comment by dannyvalentesonos** [comment]
@dnfield Seeing this is in the engine, it's really hard for us to work around this, and we can't seem to get any Talkback borders showing without using a texture view. Any idea when this could possibly get worked on?

Thanks

**Comment by dnfield** [comment]
I have a fix for it.

**Comment by dnfield** [comment]
We unfortunately had a test that would have caughtt his, but it was disabled :(

**Comment by dannyvalentesonos** [comment]
Thanks @dnfield . Can I switch to master and get this fix now? Or do I need to wait for the new engine to land in the Flutter master channel?

**Comment by dnfield** [comment]
This will still have to roll into the framework - which should happen sometime in the next few hours/dayish.  

If you know how to build your own engine, the patch is pretty trivial to apply locally as well.

You can follow the builds for this patch here: https://ci.chromium.org/p/flutter/g/engine/console (it's currently building).  Once all those boxes are green, @engine-flutter-autoroll will end up opening a PR to roll it into the framework.

**Comment by dannyvalentesonos** [comment]
Thanks @dnfield. I'll check it out tomorrow.
