### ISSUE TITLE
can't create new project

### ISSUE THREAD

**Issue by vmonjetmapp** [flutter/flutter#53860]
## Steps to Reproduce

1. install flutter
2. create new project with command
flutter create holarectangulo

## Logs

flutter create holarectangulo
Creating project holarectangulo... androidx: true
  holarectangulo/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  holarectangulo/ios/Runner/Info.plist (created)
  holarectangulo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  holarectangulo/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  holarectangulo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  holarectangulo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  holarectangulo/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  holarectangulo/ios/Runner/Base.lproj/Main.storyboard (created)
  holarectangulo/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  holarectangulo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  holarectangulo/ios/Flutter/Debug.xcconfig (created)
  holarectangulo/ios/Flutter/Release.xcconfig (created)
  holarectangulo/ios/Flutter/AppFrameworkInfo.plist (created)
  holarectangulo/ios/.gitignore (created)
  holarectangulo/test/widget_test.dart (created)
  holarectangulo/holarectangulo.iml (created)
  holarectangulo/.gitignore (created)
  holarectangulo/.metadata (created)
  holarectangulo/android/app/src/profile/AndroidManifest.xml (created)
  holarectangulo/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  holarectangulo/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  holarectangulo/android/app/src/main/res/drawable/launch_background.xml (created)
  holarectangulo/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  holarectangulo/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  holarectangulo/android/app/src/main/res/values/styles.xml (created)
  holarectangulo/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  holarectangulo/android/app/src/main/AndroidManifest.xml (created)
  holarectangulo/android/app/src/debug/AndroidManifest.xml (created)
  holarectangulo/android/gradle/wrapper/gradle-wrapper.properties (created)
  holarectangulo/android/gradle.properties (created)
  holarectangulo/android/.gitignore (created)
  holarectangulo/android/settings.gradle (created)
  holarectangulo/android/app/build.gradle (created)
  holarectangulo/android/app/src/main/kotlin/com/example/holarectangulo/MainActivity.kt (created)
  holarectangulo/android/build.gradle (created)
  holarectangulo/android/holarectangulo_android.iml (created)
  holarectangulo/pubspec.yaml (created)
  holarectangulo/README.md (created)
  holarectangulo/ios/Runner/Runner-Bridging-Header.h (created)
  holarectangulo/ios/Runner/AppDelegate.swift (created)
  holarectangulo/ios/Runner.xcodeproj/project.pbxproj (created)
  holarectangulo/lib/main.dart (created)
  holarectangulo/.idea/runConfigurations/main_dart.xml (created)
  holarectangulo/.idea/libraries/Flutter_for_Android.xml (created)
  holarectangulo/.idea/libraries/Dart_SDK.xml (created)
  holarectangulo/.idea/libraries/KotlinJavaRuntime.xml (created)
  holarectangulo/.idea/modules.xml (created)
  holarectangulo/.idea/workspace.xml (created)
Got TLS error trying to find package cupertino_icons at https://dartlang-pub-dev.appspot.com/.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in holarectangulo...
Got socket error trying to find package cupertino_icons at https://dartlang-pub-dev.appspot.com/.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

i hava tried this.

```
```

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale es-CL)
    • Flutter version 1.12.13+hotfix.9 at /Users/evilvito/opt/flutter
    • Framework revision f139b11009 (3 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/evilvito/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/evilvito/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6015.53

[!] VS Code (version 1.40.0)
    • VS Code at /Users/evilvito/Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```
```

**Comment by timsneath** [comment]
Looks like your machine was temporarily having difficulty accessing our package server at https://dartlang-pub-dev.appspot.com/. If. you're in China, you may want to visit this page: https://flutter.dev/community/china. 

Otherwise, please check whether you're able to reach the URL above from this machine or whether you are having other internet connectivity issues.

Thank you for using Flutter!

**Comment by vmonjetmapp** [comment]
it was an ISP DNS problem. with the pandemia problem. thanks for the quick response. regards
