### ISSUE TITLE
[VoiceOver - Add2App] Crash when closing FlutterView using widget in the flutter view

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#53862]
When using Add2App on iOS with Voice Over turned on, if a widget is used to close the view (using Voice Over), the app crashes. The output shows:

```
[FlutterSemanticsObject accessibilityContainer]: message sent to deallocated instance 0x1517384c0
```

**Comment by dannyvalentesonos** [comment]
@goderbauer @gaaclarke  Looks like https://github.com/flutter/engine/pull/17499 also fixed this one too. I think we can close this bug.

**Comment by goderbauer** [comment]
Thanks for getting back to this one. Closing per comment above.
