### ISSUE TITLE
flutter_webview does not adjust size within parent window

### ISSUE THREAD

**Issue by pradgc** [flutter/flutter#53861]
Hi There,

I am facing this issue in api-29 device only; till 28, it's working fine. I have placed my webview within an AspectRation. It loads fine initially. But when I change the aspectRation value dynamically, the webview stays same size, not filling the parent.
![Screenshot_1585855375](https://user-images.githubusercontent.com/60124286/78324499-7a8da680-7592-11ea-8353-a2a2769663d1.png)
![Screenshot_1585855389](https://user-images.githubusercontent.com/60124286/78324503-7f525a80-7592-11ea-9b7f-7380f58619b1.png)

Please help.

**Comment by iapicca** [comment]
Hi @pradgc 
can you please provide your `flutter doctor -v` , 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@pradgc 
I'm trying the simplest code sample 

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: WebView(
          initialUrl: 'https://github.com/flutter/flutter/issues/53861',
        ),
      ),
    );
  }
}
```

With `webview_flutter: ^0.3.20` `dev v1.18.0-8.0.pre` on Android 10 (API 29) (emulator)
WebView is redrawn on rotate.

I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
