### ISSUE TITLE
Pixelated icon rendering on Windows Desktop

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#53872]
Using something like `Icon(Icons.star)` on Windows is rendering very pixelated compared to the other platforms.

Here's Linux left, and Window right, and then enlarged:
![Photoshop_2020-04-02_13-33-56](https://user-images.githubusercontent.com/736973/78294012-d3a00080-74e6-11ea-9d63-4dc1c7f20d14.png)

**Comment by clarkezone** [comment]
What DPI is your monitor running at?

**Comment by esDotDev** [comment]
I have 2 monitors, both are running at native resolution. 1920x1080 and 2560x1080, the icons look the same on both.

**Comment by stuartmorgan** [comment]
How does this compare to the material icons font rendering in Chrome (in a standard web page, not a Flutter for web project) on the same machine?

**Comment by esDotDev** [comment]
Huh... it is the same. @24px the icons render perfectly, at 20px, they are pixelated (?)
![image](https://user-images.githubusercontent.com/736973/78310829-466fa280-750c-11ea-9145-c2b6d5eb7f56.png)

**Comment by gskinnerTeamPrivate** [comment]
Sounds like this is a known issue with Material Icons, sorry for the noise. 
https://github.com/google/material-design-icons/issues/648#issuecomment-361393151

**Comment by esDotDev** [comment]
Sounds like this is a known issue with Material Icons, sorry for the noise.
google/material-design-icons#648 (comment)
