### ISSUE TITLE
`flutter create` could generate an app with trailing commas

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5387]
With trailing commas, the dart formatter retains formatting of complex build methods. (See https://github.com/flutter/flutter/wiki/Early-Access%3A-Auto-Formatting)

We should add trailing commas to the "starter app" generated by `flutter create` so our users can then run the formatter (likely, through their editor).

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/flutter/pull/5493

**Comment by sethladd** [comment]
Thanks!
