### ISSUE TITLE
iOS build fails "No code signature found" when multiple code signing identities have the same name

### ISSUE THREAD

**Issue by taz1208** [flutter/flutter#53891]
I followed this doc manually 'https://flutter.dev/docs/development/ios-project-migration'
So Emulator bug fixed but real device not build.
my error snippet "No code signature not found."

I saw #23068, #24343, and https://stackoverflow.com/questions/38371044/ios-app-testing-app-installation-failed-no-code-signature-found

I tried all of solutions but not solved my problems.

Currently I go back to the beginning.

my flutter doctor -v is

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-KR)
    • Flutter version 1.12.13+hotfix.9 at /Users/me/Documents/flutter
    • Framework revision f139b11009 (3 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • SM G930S          • 192.168.0.41:1208                        • android-arm64 • Android 8.0.0 (API 26)
    • iPhone (2)   • 8c31aa273b6603f4b4b70f2c6e2 • ios           • iOS 12.4.5
    • iPhone 11 Pro Max • 44F03B10-DD41-4658-B9D4-7CC57EE46360     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @taz1208 
can you please provide your `flutter run --verbose` 
on physical device
Thank you

**Comment by taz1208** [comment]
all of thme? @iapicca
It's finished build but It too long text :(
Then currently physical device work but emulator is not working
If I follow that offical doc. emulator is working but physical device not working

**Comment by iapicca** [comment]
Hi again @taz1208 
if it's to long to be pasted in a comment 
please attach it as txt file
Thank you

**Comment by IhwanID** [comment]
> All of that? @iapicca
> It's finished build but It too long text :(
> Then currently physical device work but emulator is not working
> If I follow that offical doc. emulator is working but physical device not working

same issue but my emulator work and physical not working :(

**Comment by DanielZanchi** [comment]
I have this same issue: here's the `flutter run --verbose` log 
[LOG.txt](https://github.com/flutter/flutter/files/4431783/LOG.txt)

**Comment by taz1208** [comment]
I can't attach `flutter run --verbose` because security policy of my company,
but It still buggy :( @iapicca

**Comment by taz1208** [comment]
Currently I don't followed doc.
Then emulator log snippet is
```

Xcode build done.                                           13.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    error: Building for iOS Simulator, but the linked and embedded framework 'App.framework' was built for iOS. (in target 'Runner' from project 'Runner')
```

**Comment by MobiliteDev** [comment]
I have exactly the same error as @taz1208 .

I have created a new project on Flutter,a nd added some dependancies:
- emulator not working 
- physical device is working

If you follow the [migration guide](https://flutter.dev/docs/development/ios-project-migration):
- emulator is working
- physical device is NOT working

Based on 
- physical Device iPhone 8 updated to iOs 13.4
-  iOS emultaor iPhone 8 13.4
- XCode 11.4
- last flutter SDK stable version

` [ !! ] Error 0xe800801c: No code signature found.
AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[   +3 ms] Could not install build/ios/iphoneos/Runner.app on 78c0f84a4d79a9af1755ac1081ff2d9916133d39.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace`

**Comment by DanielZanchi** [comment]
exact same message 

> I have exactly the same error as @taz1208 .
> 
> I have created a new project on Flutter,a nd added some dependancies:
> 
> * emulator not working
> * physical device is working
> 
> If you follow the [migration guide](https://flutter.dev/docs/development/ios-project-migration):
> 
> * emulator is working
> * physical device is NOT working
> 
> Based on
> 
> * physical Device iPhone 8 updated to iOs 13.4
> * iOS emultaor iPhone 8 13.4
> * XCode 11.4
> * last flutter SDK stable version
> 
> ` [ !! ] Error 0xe800801c: No code signature found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0) [ +3 ms] Could not install build/ios/iphoneos/Runner.app on 78c0f84a4d79a9af1755ac1081ff2d9916133d39. [ ] Try launching Xcode and selecting "Product > Run" to fix the problem: [ ] open ios/Runner.xcworkspace`

**Comment by MO-James** [comment]
I'm getting the same problem. Switching to the beta branch has resolved it.

**Comment by iapicca** [comment]
Hi  all
does switching to beta as suggested by @MO-James solve the issue in your case as well?
Thank you for the logs @DanielZanchi

**Comment by MobiliteDev** [comment]
Hi,
I've just switched to beta branch.
First I had this error on XCode`Error: Could not find included file 'Generated.xcconfig' in search paths` => resolved with a `flutter build ios`on VSCode.

Next,I came back to XCode and made a Run... All is Good ! On emulator AND physical device.

Thank you so much @MO-James 

Hope we will have soon a fix on stable channel.

**Comment by taz1208** [comment]
I don't solved problem 
my log is 
```
flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    2294d75bf..d3ed9ec94  beta           -> origin/beta
git:    d14a301e4..727552e5c  dev            -> origin/dev
git:  * [new branch]          flutter-1.17-candidate.2 -> origin/flutter-1.17-candidate.2
git:  * [new branch]          flutter-1.17-candidate.3 -> origin/flutter-1.17-candidate.3
git:  * [new branch]          flutter-1.17-candidate.4 -> origin/flutter-1.17-candidate.4
git:  * [new branch]          flutter-1.17-candidate.5 -> origin/flutter-1.17-candidate.5
git:  * [new branch]          flutter-1.18-candidate.0 -> origin/flutter-1.18-candidate.0
git:  * [new branch]          flutter-1.18-candidate.1 -> origin/flutter-1.18-candidate.1
git:  * [new branch]          flutter-1.18-candidate.2 -> origin/flutter-1.18-candidate.2
git:  * [new branch]          flutter-1.18-candidate.3 -> origin/flutter-1.18-candidate.3
git:    19e7db585..ccb4f737e  master         -> origin/master
git:  * [new tag]             1.17.0-dev.2.0 -> 1.17.0-dev.2.0
git:  * [new tag]             1.17.0-dev.3.1 -> 1.17.0-dev.3.1
git:  * [new tag]             1.17.0-dev.4.0 -> 1.17.0-dev.4.0
git:  * [new tag]             1.17.0-dev.5.0 -> 1.17.0-dev.5.0
git:  * [new tag]             1.18.0-dev.0.0 -> 1.18.0-dev.0.0
git:  * [new tag]             1.18.0-dev.1.0 -> 1.18.0-dev.1.0
git:  * [new tag]             1.18.0-dev.2.0 -> 1.18.0-dev.2.0
git:  * [new tag]             1.17.0-dev.3.0 -> 1.17.0-dev.3.0
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.

~/Documents/workspace_flutter/myapp master* 6s
❯ flutter build ios
 
Building kr.cop.myapp$(BUNDLE_SUFFIX) for device (ios-release)...
Your Xcode project requires migration. See https://flutter.dev/docs/development/ios-project-migration for details.
```

**Comment by taz1208** [comment]
I can't resolve my problem that way :(
My log is 
```
 flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    2294d75bf..d3ed9ec94  beta           -> origin/beta
git:    d14a301e4..727552e5c  dev            -> origin/dev
git:  * [new branch]          flutter-1.17-candidate.2 -> origin/flutter-1.17-candidate.2
git:  * [new branch]          flutter-1.17-candidate.3 -> origin/flutter-1.17-candidate.3
git:  * [new branch]          flutter-1.17-candidate.4 -> origin/flutter-1.17-candidate.4
git:  * [new branch]          flutter-1.17-candidate.5 -> origin/flutter-1.17-candidate.5
git:  * [new branch]          flutter-1.18-candidate.0 -> origin/flutter-1.18-candidate.0
git:  * [new branch]          flutter-1.18-candidate.1 -> origin/flutter-1.18-candidate.1
git:  * [new branch]          flutter-1.18-candidate.2 -> origin/flutter-1.18-candidate.2
git:  * [new branch]          flutter-1.18-candidate.3 -> origin/flutter-1.18-candidate.3
git:    19e7db585..ccb4f737e  master         -> origin/master
git:  * [new tag]             1.17.0-dev.2.0 -> 1.17.0-dev.2.0
git:  * [new tag]             1.17.0-dev.3.1 -> 1.17.0-dev.3.1
git:  * [new tag]             1.17.0-dev.4.0 -> 1.17.0-dev.4.0
git:  * [new tag]             1.17.0-dev.5.0 -> 1.17.0-dev.5.0
git:  * [new tag]             1.18.0-dev.0.0 -> 1.18.0-dev.0.0
git:  * [new tag]             1.18.0-dev.1.0 -> 1.18.0-dev.1.0
git:  * [new tag]             1.18.0-dev.2.0 -> 1.18.0-dev.2.0
git:  * [new tag]             1.17.0-dev.3.0 -> 1.17.0-dev.3.0
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.

~/Documents/workspace_flutter/myapp master* 6s
❯ flutter build ios
 
Building kr.cop.myapp$(BUNDLE_SUFFIX) for device (ios-release)...
Your Xcode project requires migration. See https://flutter.dev/docs/development/ios-project-migration for details.
```

**Comment by taz1208** [comment]
When I reChange to stable channel
I saw that log on physical device
https://github.com/flutter/flutter/issues/53891#issuecomment-609604584
but  emulator is well work..
I confuse this situation..

**Comment by taz1208** [comment]
Now, I came back first state.
- physical device work,
- emulator not work,
- migration not followed.

beta channel is not solution at my case.

**Comment by taz1208** [comment]
Finally, I found solution in my case

1. switch beta channel
2. follow migration manually
3. flutter clean.

It's well work both of emulator and device.
but when  I change channel stable,  it again problem :(

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/52736#issuecomment-605316364
> You should be able to switch between stable and master if your thin phase has:
> 
> ```
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
> ```
> 
> I fixed a bug in https://github.com/flutter/flutter/pull/51453/files#r384290691 (in [v1.15.4](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos)) where signing wasn't working for me because the script used to guess the signing identifier based on the name, but on my machine the name was ambiguous. I fixed the code to use the identifier instead.

@taz1208 Does the output of `security find-identity -p codesigning -v ` show multiple code signing identities with the same name, but with different identifiers?  That's the issue I was hitting...

**Comment by jmagman** [comment]
Or @MobiliteDev or @DanielZanchi or @IhwanID or anyone hitting this.

**Comment by taz1208** [comment]
You're right, my mac set several identities @jmagman 
It seems that reason of my problem

**Comment by jmagman** [comment]
The fix is in v1.15.4 (currently master, dev, and beta channels) and will be in the next stable.  For now, the workaround is to remove the other code signing identities with the same name.
```
$ security find-identity -p codesigning -v
  1) E3B0C44298FC1C149AFBF4C8996FB92427AE41E4 "iPhone Developer: YOU (ABC123)"
  2) 5FD924625F6AB16A19CC9807C7C506AE1813490E "iPhone Developer: YOU (ABC123)"
...
```
Then delete the duplicate:
```
$ security delete-identity -Z E3B0C44298FC1C149AFBF4C8996FB92427AE41E4
```

**Comment by MobiliteDev** [comment]
> Or @MobiliteDev or @DanielZanchi or @IhwanID or anyone hitting this.

Hi, yes, I have this too
![image](https://user-images.githubusercontent.com/54275508/79575987-e4de3500-80c2-11ea-88a6-d1db68289468.png)

I will delete the duplicate

**Comment by david-shortman** [comment]
Your solution worked for me. Thanks!

**Comment by yuanzhiying** [comment]
After remove the other code signing identities with the same name, it works!

**Comment by JonathanGuo** [comment]
@jmagman Thanks! You saved my day! This is the exactly same issue I've had.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/51453 is now available in latest stable.  Closing.
