### ISSUE TITLE
【video_player iOS】Can't pause the video when calling, and can hear the video sound during the call

### ISSUE THREAD

**Issue by xienas** [flutter/flutter#53906]
## Steps to Reproduce

**Expected results:** 
video_player 0.10.8 + 1
I want to pause the video while I'm on the phone and I can't hear the video sound

**Actual results:** 
Video sound can still be heard when the video is not paused and the phone is answered

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @xienas 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

I have just tested using official sample, during call it pauses the video on iPhone XR
Thank you

**Comment by xienas** [comment]
> Hi @xienas
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> 
> I have just tested using official sample, during call it pauses the video on iPhone XR
> Thank you

Thanks, I found the problem.But I want to have a multiple playback function.

**Comment by TahaTesser** [comment]
Hi @xienas 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
if you've a feature request, please create a new issue
Thank you
