### ISSUE TITLE
Flutter 1.12.13+hotfix.8 : Problem with R8 shrinker and plugin flutter_inappwebview

### ISSUE THREAD

**Issue by arnaudelub** [flutter/flutter#53909]
## Environment

**Flutter version: Flutter 1.12.13+hotfix.8
**Plugin version: Master branch  

## Description

**Expected behavior:** 
initialOptions should be set when running in release mode

**Current behavior:** 
options.crossplatform.useShouldOverrideUrlLoading = null even if set to true in the initialOptions.

## Steps to reproduce

1. set minifyEnabled true in android/app/build.gradle:
```gradle
buildTypes {
  release {
    minifyEnabled true
  }
}
```
in the inappwebview widget add in initialOptions:
```dart
useShouldOverrideUrlLoading: true,
````
and  add :
```dart
shouldOverrideUrlLoading: (InAppWebViewController controller,
             ShouldOverrideUrlLoadingRequest request) async {
           print("Override available: ${request.url}");
          return ShouldOverrideUrlLoadingAction.ALLOW;
},
```
2. Then run flutter run --release
3. shouldOverrideUrlLoading will never been called because useShouldOverrideUrlLoading is null

### If minifyEnabled is set to false, it works as expected

Same issue when using :
- flutter build appbundle
Using:
flutter build appbundle --no-shrink solves the problem, seems like R8 is messing with something.
doc: [flutter.dev](https://flutter.dev/docs/deployment/android#r8)

```term
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G3020, locale en-ES)
    • Flutter version 1.12.13+hotfix.9 at /Users/arnaud/dev/flutter
    • Framework revision f139b11009 (4 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/arnaud/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/arnaud/Library/Android/sdk
    • Java binary at: /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Redmi Note 8 Pro          • jjkrdyir8l4s8ls4 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

I've open an issue also on the github project of the plugin, but i'm not sure if the error is from R8 or the plugin himself: [plugin  issue#315](https://github.com/pichillilorenzo/flutter_inappwebview/issues/315)

**Comment by TahaTesser** [comment]
Hi @arnaudelub 
This is 3rd party plugin and  you've already raised the issue on their[github](https://github.com/pichillilorenzo/flutter_inappwebview/issues/315)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by arnaudelub** [comment]
well, as the issue occurs only when minification is used, yes, i disagree, the third party plugin is working fine.
There are the same probabilities that the issue is coming from flutter as from the plugin in my opinion.
Thank you for your help

**Comment by TahaTesser** [comment]
Hi @arnaudelub 
R8 is [enabled by default](https://flutter.dev/docs/deployment/android#r8) and  you don't need to add 
`minifyEnabled true`

if you're experiencing this issue without third party plugin and without adding`minifyEnabled true`, please comment below and i will reopen it 
Thank you

**Comment by arnaudelub** [comment]
i know it's enabled by default, that's why i said in the issue that flutter build appbundle --no-shrink   can be used as workaround
