### ISSUE TITLE
Add option to have a title in DatePicker and TimePicker

### ISSUE THREAD

**Issue by bakua** [flutter/flutter#53905]
## Use case

Hello, it would help to improve our apps' UX if it would be possible to add a title date and time dialogs.

## Proposal

For inspiration:

![image](https://user-images.githubusercontent.com/494667/78332377-372e3a80-7588-11ea-90ed-bf50d59e0a4e.png)

**Comment by HansMuller** [comment]
CC @darrenaustin @rami-a

**Comment by rami-a** [comment]
Not _exactly_ a title but the new design for date pickers allows you to specify the "help text" that appears along the top. Also I am currently working on an update to time pickers to allow for similar help text. See the below, the "select date" text can be customized.

![DatePickerM2](https://user-images.githubusercontent.com/19588/75818324-8432ad00-5d4d-11ea-9633-d322b1d34b5b.gif)

**Comment by rami-a** [comment]
Hello, @bakua I just submitted #59191 and you can now set helpText for the time picker as well. Closing this as fixed :)
