### ISSUE TITLE
Não consigo fazer registrar as informações no hasura pelo flutter

### ISSUE THREAD

**Issue by ncrgamer** [flutter/flutter#53900]
Com isso dito no título, eu não sou capaz de registrar dados no hasura, ou erro aparece
*[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'PlatformException' is not a subtype of type 'String'*

Código do repositório: Código do repositório
:

import  'pacote: firebase_auth / firebase_auth.dart' ;
import  'pacote: flutter_modular / flutter_modular.dart' ;
import  'pacote: hasura_connect / hasura_connect.dart' ;
import  'package: searchdogs / app / shared / users_model.dart' ;

classe  CadastroRepository  estende  Disposable {
   static  const  String url =  "https://searchdog.herokuapp.com/v1/graphql" ;

   HasuraConnect final connect =  HasuraConnect (url);
  final  FirebaseAuth _firebaseAuth =  FirebaseAuth. instância;

  Futuro  cadastroWithEmail ( String email, String senha) assíncrono {
     try {
       AuthResult resultado =  aguardar _firebaseAuth. createUserWithEmailAndPassword (
          email : email, senha : senha);
      Usuário FirebaseUser = result.user;
      retornar user.uid;
    } captura (e) {
       return e;
    }
  }

  Futuro  registerOnHasura ( String email, String senha, String name, String image, String endereco, String telefone) async {
     String uid =  aguarda  cadastroWithEmail (email, senha);

    Cordas mutação =  "" " 
        mutação MyMutation { 
      insert_users (objetos: {imagem: "$ imagem ", uid: "$ uid ", name: "$ name ", endereco: "$ endereco ", telefone:" $ telefone }) 
          affected_rows 
    }     
    "" " ;

    var data =  aguardar conexão. mutação (mutação);  

    retornar  UsersModel . fromJson (dados);
    
    }

  @override 
  void  dispose () {
     // TODO: implementar descarte
  }
}
Codigo do controller:

Código do driver:

import  'pacote: flutter / cupertino.dart' ;
import  'pacote: flutter / material.dart' ;
import  'pacote: mobx / mobx.dart' ;
import  'package: searchdogs / app / modules / cadastro / repository / cadastro_repository.dart' ;
parte  'cadastro_controller.g.dart' ;

classe  CadastroController  =  _CadastroBase  com  _ $ CadastroController ;

 classe  abstrata _CadastroBase  com  loja {
    CadastroRepository repositório;
  @observable 
  String email =  "" ;

  @observable 
  String senha =  "" ;

  @observable 
  String name =  "" ;

  @observable  
  String image =  "" ;

   @observable  
  String endereco =  "" ;

   @observable  
  String telefone =  "" ;

  @action 
  void  setEmailC ( String _email) => email = _email;

  @action 
  void  setSenhaC ( String _senha) => senha = _senha;

  @action 
  void  setNameC ( String _name) => name = _name;
 
  @action 
  void  setTelefoneC ( String _telefone) => telefone = _telefone;

  @action 
  void  setEnderecoC ( String _endereco) => endereco = _endereco;

   
  @action   
  Futuro  cadastro ( contexto BuildContext ) assíncrono {
    repositório. registerOnHasura (email, senha, nome, imagem, endereco, telefone);
  }

_CadastroBase ( este repositório);
  
}

**Comment by iapicca** [comment]
Hi @ncrgamer 
please do not open intentional duplicate of your issues
you may comment in your previous [issue](https://github.com/flutter/flutter/issues/53892)

closing this as duplicate
thank you
