### ISSUE TITLE
iOS system images or system icons

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5390]
We should have a way to get a ui.Image for a given image name on iOS:

https://developer.apple.com/ios/human-interface-guidelines/graphics/system-icons/
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/clm/UIImage/imageNamed

@chinmaygarde @tvolkert 

Once we have an API to get a ui.Image for a given OS-provided image name, I can hook this up to the framework.

This is a prereq for https://github.com/flutter/flutter/issues/4955.

**Comment by chinmaygarde** [comment]
There is no way to get handles to images that the UIKit framework uses internally (available as a public API). We will have to bring in our own. `-[UIImage imageNamed:]` only gives access to images the developer has added to their own application bundle.

**Comment by sethladd** [comment]
We'll want to use iOS icons for Share and Location (and probably others) for fidelity.

**Comment by eseidel** [comment]
Presumably one could get the share icon using: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/index.html#//apple_ref/occ/instm/UIBarButtonItem/backgroundImageForState:style:barMetrics: on an "action item" (which is the share button).

**Comment by xster** [comment]
It's not possible to get to the system icons in iOS but bundling cupertino_icons package should solve this now.

**Comment by jkmathew** [comment]
As of iOS 13 release, it is possible to get system provided images 
With UIKit `UIImage(systemName: )` and with SwiftUI `Image(systemName: )`.

Hope with this new addition, cupertino_icons can be replaced by something new.
