### ISSUE TITLE
Enable null safety for flutter_test

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#53908]
To enable testing of packages that use null safety, the following package dependencies of package:flutter_test need to be migrated. These dependencies are the additional dependencies flutter_test has over the [dependencies of regular package:test](https://github.com/dart-lang/sdk/issues/41171):

- [ ] ~archive~ (not needed after https://github.com/flutter/flutter/pull/54144)
- [ ] ~args~, (not transitively imported)
- [x] clock (assuming [this](https://github.com/flutter/flutter/pull/54125) lands)
- [ ] ~convert~ (not needed after https://github.com/flutter/flutter/pull/54144)
- [ ] ~crypto~ (not needed after https://github.com/flutter/flutter/pull/54144)
- [x] fake_async (assuming [this](https://github.com/flutter/flutter/pull/54125) lands)
- [ ] ~image~ (not needed after https://github.com/flutter/flutter/pull/54144)
- [ ] ~petitparser~ (not needed after https://github.com/flutter/flutter/pull/54144)
- [ ] ~quiver~ (not needed after https://github.com/flutter/flutter/pull/54125)
- [x] typed_data, @munificent  
- [x] vector_math, @kevmoo 
- [ ] ~xml~ (not needed after https://github.com/flutter/flutter/pull/54144)

**Comment by kevmoo** [comment]
See the updated sheet, @mit-mit 

args isn't needed. @jakemac53 is looking to extract the quiver dependencies so we can avoid migrating it!

**Comment by mit-mit** [comment]
Can we consider maintaining the bugs? Not everyone working on null safety has access to the docs.

**Comment by jakemac53** [comment]
Lets please only have one place, if we want to migrate to github issues that is fine, or we can make the spreadsheet public? Or we can have a list of issues that need to be updated in the sheet?

**Comment by kevmoo** [comment]
Adding issues to the sheet sounds like a great idea.

**Comment by jakemac53** [comment]
The sheet is still likely to get out of date then, but 🤷‍♂

**Comment by kevmoo** [comment]
We don't have the ability to link everything together w/ ZenHub, so a sheet
is still our best option

**Comment by munificent** [comment]
typed_data is migrated and ready to go: https://github.com/dart-lang/typed_data/tree/null_safety

**Comment by pcsosinski** [comment]
is there work left to do?  the non crossed out items all seem to be checked off?

**Comment by goderbauer** [comment]
@pcsosinski as per https://github.com/flutter/flutter/issues/62886 my understanding is that we still need to

 *  migrate flutter_goldens/flutter_goldens_client,
 * migrate the actual code of flutter_test

**Comment by goderbauer** [comment]
A PR to migrate flutter_test to NNBD is here: #66663.

Submitting it is blocked on migrating `Tooltip` and `Card` from the material lib to NNBD, which is underway.

**Comment by mit-mit** [comment]
👍
