### ISSUE TITLE
keyboard not showing in flutter gallery

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5391]
Text fields demo. I can't get the keyboard to come up at all.

**Comment by sethladd** [comment]
How would we write a test to catch this next time?

Also, does this happen on iOS and/or Android?

**Comment by Hixie** [comment]
I saw it on Android.

@yjbanov may have to help us in testing this end-to-end.

**Comment by sethladd** [comment]
Yeah, we might want some end-to-end tests for the keyboard. cc @mpcomplete

**Comment by Hixie** [comment]
we're hitting `impl == null` and `!ctrl.isBound` in `KeyboardProxy.show()`.

**Comment by Hixie** [comment]
Closing in favour of https://github.com/flutter/flutter/issues/5408
