### ISSUE TITLE
Swift Compiler Error: Editor place holder in source file

### ISSUE THREAD

**Issue by Samoun15** [flutter/flutter#53915]
I'm facing a Swift Compiler Error in my app, I am using xcode 11.4. My App used to build fine before now I'm completely lost, I don't know what exactly happened. I've been looking for a fix for the last 3 days with no success, even tried to run it under previous xcode versions.

Any help will be much appreciated.

I get the following compile error:
![Swift Compiler Error](https://user-images.githubusercontent.com/61712983/78358524-3d81de00-75ab-11ea-8326-aaf1f0f9d7b6.png)

**Comment by VladyslavBondarenko** [comment]
Hi @Samoun15 
Please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem

Please don't post screenshots of text where is not necessary, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
