### ISSUE TITLE
Request: simple example for reading/writing a file

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5392]
We've been asked "How do I store state?" a few times. I don't think we have an example of this, complete with finding out what directory we can store files into, and examples of the dart:io classes required.

Even a code snippet would be helpful here. Doesn't necessarily have to be a full example app. But, something we can link to for the mailing list, etc.

Thanks!

**Comment by eseidelGoogle** [comment]
The fitness example used to have an example of dart:io code reading/writing json from disk using paths from PathProvider, but we deleted it.  As Seth notes, this is a common request.

**Comment by eseidelGoogle** [comment]
Old code using the predecessor to PathProvider:
https://github.com/flutter/flutter/blob/c7d71d8ab1b7eea58e7741cde9e65d96ff36f308/examples/fitness/lib/user_data.dart#L24
The io bits should be the same though.
