### ISSUE TITLE
Regression in complex_layout_scroll_perf__memory diff-median

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53929]
I should have caught this earlier, but it's noisy, as most of the memory ones are, and I assumed the spikes were in the noise. Today I checked the history, and there's a clear jump around https://github.com/flutter/flutter/pull/52431, which while still in the green, pushed the benchmark so it started going over on a regular basis.

![Screen Shot 2020-04-03 at 9 14 02 AM](https://user-images.githubusercontent.com/1435716/78382299-7ca03700-758b-11ea-9b2b-61725ebc4bf5.png)

I think the problem here with noisy benchmarks is that short of checking the long-term history of each one, which I think is too time consuming for me to do my sweeps every morning, it's possible to miss a commit because the window is small. This will get better when we bring the new dashboard online and this is automated.

I'm not applying a `TODAY` label because
  * We've lived with it
  * It's still within the green about half of the time.

cc @liyuqian

**Comment by dnfield** [comment]
There's a pretty clear regression since that engine roll, but that roll itself locally shows a small _decrease_ in memory usage.  Will continue bisecting to see if there's any culprit we can identify.

**Comment by dnfield** [comment]
I am unable to consistently reproduce this regression.  I tried doing a bisect, and a commit that was initially bad is then good on a rerun - despite the fact that we run the application multiple times. I think we should just rebaseline this benchmark.

**Comment by dnfield** [comment]
Rebaselined.
