### ISSUE TITLE
How can I specify port for flutter run for web

### ISSUE THREAD

**Issue by mahmoudajawad** [flutter/flutter#53920]
I tried using all three ports arguments of `flutter run` but the port keeps getting assigned randomly. My use case is using dart/flutter from docker container meaning I need to specify port to use so I can expose it and be able to access it from local machine.

**Comment by TahaTesser** [comment]
Hi @mahmoudajawad 

You can execute this command with your port number `flutter run -d chrome --web-port=8989` 
for example
this will host on `http://localhost:8989/#/`

if the problem still persist, can you please provide your `flutter doctor -v` and `flutter run -d chrome --web-port=8989 --verbose`? 

Thank you

**Comment by mahmoudajawad** [comment]
Thanks, @TahaTesser. This definitely answers the question. However, although I'm able to `curl localhost:PORT_HERE` from docker and getting the expected response, accessing the port from local machine is being denied. Is there any other property that might be causing the debugging server to deny non-localhost (to docker container in this case) access?

**Comment by TahaTesser** [comment]
Hi @mahmoudajawad 
As far as i know, you cannot

**Comment by mahmoudajawad** [comment]
If anyone come across this looking for the same it's worth noting you can use the following on web-enabled project to access it from any host:
```
flutter run --web-port PORT --web-hostname 0.0.0.0
```
