### ISSUE TITLE
flutter_socket_io : My event triggers, my JSON is OK, but the message is not sent

### ISSUE THREAD

**Issue by Yowims** [flutter/flutter#53927]
Hi!

I have a problem using flutter_socket_io. My event triggers, my message is OK, all seems to be OK, but the message is not published.

Here is my log : 

    D/FlutterSocketIoPlugin: FlutterSocketIoPlugin(22753): onMethodCall: socketSendMessage - domain: 
    <MY_URL> - with namespace: /
    D/FlutterSocketIoPlugin: TOTAL SOCKETS: (22753): 1
    D/FlutterSocketIoPlugin: SocketIO(22753): socket id: <MY_URL> is connected: true
    D/FlutterSocketIoPlugin: sendMessage(22753): Event: chat.sendMessage - with message: {"chat": "5da02fec8216246456198e19", "sender": {"id": "5c014a1d43b6804ed7b642b1", "username": "Yowims", "image": {"url": "<IMAGE_URL>"}}, "state": "send", "message": "zahtrz", "sendDate": "2020-04-03T17:04:58.203404"}
    D/FlutterSocketIoPlugin: FlutterSocketIoPlugin(22753): onMethodCall: socketSendMessage - domain: 
    <MY_URL> - with namespace: /
    D/FlutterSocketIoPlugin: TOTAL SOCKETS: (22753): 1
    D/FlutterSocketIoPlugin: SocketIO(22753): socket id: <MY_URL> is connected: true
    D/FlutterSocketIoPlugin: sendMessage(22753): Event: chat.receiveMessage - with message: {"chat": "5da02fec8216246456198e19", "sender": {"id": "5c014a1d43b6804ed7b642b1", "username": "Yowims", "image": {"url": "<IMAGE_URL>"}}, "state": "send", "message": "zahtrz", "sendDate": "2020-04-03T17:04:58.203404"}

Here are the methods I call :

    SocketIO socketIO;
      _connectSocket() { 
      socketIO = SocketIOManager().createSocketIO(wsAdd, "/"); 
      socketIO.init(); 
      _subscribes();
      socketIO.connect();
    }

    _subscribes() { 
      if (socketIO != null) { 
        socketIO.subscribe('chat.sendMessage', _onSendChatMessage);
        socketIO.subscribe("chat.receiveMessage", _onReceiveChatMessage); 
      } 
    }

    void _onReceiveChatMessage(dynamic message) { 
      print("--- Message reçu! Actualisation... ---");
      _getMessagesByChatId(chatStateId);
    }

    void _onSendChatMessage(String msg) async { 
      if (socketIO != null) { 
        Map<String,dynamic> chatUser = ({
          '"id"': '"${user.id}"',
          '"username"': '"${user.username}"',
          '"image"': {
            '"url"':'"${user.image.url}"'
          }
        });
        String currentDate = DateTime.now().toIso8601String();

        Map<String,dynamic> thisJson = {
          '"chat"': '"${this.chatStateId}"',
          '"sender"': chatUser,
          '"state"': '"send"',
          '"message"': '"$msg"',
          '"sendDate"': '"$currentDate"'
        };

        socketIO.sendMessage("chat.sendMessage", thisJson.toString());
        socketIO.sendMessage("chat.receiveMessage", thisJson.toString());
        sendController.clear();
      }
    }

My formating is quite gross, but I have to do it like this otherwise my program doesn't add quotes at the right spots.

And here is the widget where I call the method to send my message :

    SizedBox(
      width: 50,
      child: FlatButton(
        child: Icon(Icons.send),
        onPressed: (){
          _onSendChatMessage(sendController.text);
        },
      ),
    )

## Flutter analyze

```
Analyzing my_solution...

   info - Unused import: 'package:my_solution/Models/Login.dart' - lib\Models\Chat.dart:1:8 - unused_import
   info - This function has a return type of 'DoNothingAction', but doesn't end with a return statement -
          lib\fragments\ChatFragment.dart:53:32 - missing_return
   info - This function has a return type of 'DoNothingAction', but doesn't end with a return statement -
          lib\fragments\ChatFragment.dart:81:32 - missing_return
   info - Unused import: 'package:my_solution/Models/Chat.dart' - lib\pages\ChatViewPage.dart:10:8 - unused_import
   info - The value of the local variable 'livresLus' isn't used - lib\pages\UserProfilePage.dart:169:9 -
          unused_local_variable

5 issues found. (ran in 13.2s)
```

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.16.4-pre.88, on Microsoft Windows [version 10.0.17763.1039], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code
[√] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @Yowims 
For issue related to the 3rd party plugin [flutter_socket_io](https://pub.dev/packages/flutter_socket_io) you may want to open an issue in the dedicated [github](https://github.com/WinkMeter/flutter_socket_io/issues).

if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by Yowims** [comment]
@TahaTesser thanks for replying ^^ I'll post my issue there.

For those who found this issue, here is the link for the new question :
(https://github.com/WinkMeter/flutter_socket_io/issues/45)[https://github.com/WinkMeter/flutter_socket_io/issues/45]
