### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by juniorsistemasufms** [flutter/flutter#53926]
Performing hot reload...
Syncing files to device SM G973F...
I/flutter ( 2217): usuário não logado
Reloaded 0 of 877 libraries in 170ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#a64b7](dirty, state: NavigatorState#308e7(tickers: tracking 0 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3803 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/lourivaljunior/Library/Mobile%20Documents/com~apple~CloudDocs/programas/mobile/flutter/FSJT_APP_2020/example/lib/wings/generic/main.dart:51:16
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:3803:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by TahaTesser** [comment]
Hi @juniorsistemasufms 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by juniorsistemasufms** [comment]
/Users/lourivaljunior/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.16.4-pre.69, on Mac OS X 10.14.6 18G1012, locale en-BR)
    • Flutter version 1.16.4-pre.69 at /Users/lourivaljunior/flutter
    • Framework revision 19e7db585d (2 days ago), 2020-04-01 11:16:01 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lourivaljunior/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/lourivaljunior/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G973F • RQ8M20LMPTJ • android-arm64 • Android 10 (API 29)

• No issues found!
Process finished with exit code 0

**Comment by TahaTesser** [comment]
Hi @juniorsistemasufms 
can you please provide your `flutter run --verbose` from root of your project? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @juniorsistemasufms 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
