### ISSUE TITLE
Discrepancy in updating translations in regenerating Material and Cupertino translations from scratch

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#53934]
There is some logic that isn't consistent when arb files are regenerated for our Material and Cupertino localizations. This seems to cause arb files to be generated differently when arb files are created from scratch vs when updating pre-existing arb files using the internal system.

First seen in https://github.com/flutter/flutter/pull/53880, when the Norwegian translation for `remainingTextFieldCharacterCountZero` originally showed 'TBD', but did not appear at all when regenerated from scratch.  It also regenerated some strings in alphabetical order when they weren't before.

There's a pointer in `gen_missing_localizations.dart` that says to manually add a new message for each arb file manually with a 'TBD' string. This manual step might be necessary when generating new strings so that there is some placeholder before the translation teams can process these new messages. However, we might want to improve the logic for updating pre-existing arb files.

cc/ @HansMuller

**Comment by Hixie** [comment]
@HansMuller I'm going to close this on the assumption that this got resolved in the intervening years, either by being fixed, or by process changes, or by being insufficiently important for us to actually worry about it. Let me know if I'm wrong.

**Comment by HansMuller** [comment]
Sounds reasonable, thanks for closing.
