### ISSUE TITLE
Crashes on some Android devices due to image_picker

### ISSUE THREAD

**Issue by talhazzani** [flutter/flutter#53938]
## Steps to Reproduce

plugin : image_picker 0.6.4

flutter version:1.12.13+hotfix.8 

Can't reproduce the issue , the plugin is working perfectly for me However I have found recent crashes on Firebase due to 

ImagePickerDelegate.java line 153
io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile

and 

ImagePickerDelegate.java line 162
io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile

the devices were:

 Device: Honor 7A   Android version : 8.1.0
 Device: HUAWEI Y5 Prime 2018   Android version : 8.1.0
 Device: HUAWEI Y5 Prime 2018   Android version : 8.1.0

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2345, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.**********/com.**********.MainActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.**********/files/Pictures/ebfc873b-ff33-4cd9-9336-20871a6436677949658798937887451.jpg
android.app.ActivityThread.deliverResults (ActivityThread.java:4564)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4608)
android.app.ActivityThread.-wrap19 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1832)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:6861)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
```

```
Caused by java.lang.IllegalArgumentException
Failed to find configured root that contains /storage/emulated/0/Android/data/**********/files/Pictures/3d9ebf38-3431-45c6-85e7-622da6f59baa1351802199868734808.jpg
androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile (FileProvider.java:739)
androidx.core.content.FileProvider.getUriForFile (FileProvider.java:418)
io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile (ImagePickerDelegate.java:153)
io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent (ImagePickerDelegate.java:350)
io.flutter.plugins.imagepicker.ImagePickerDelegate.onRequestPermissionsResult (ImagePickerDelegate.java:410)
io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult (FlutterPluginRegistry.java:194)
io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult (FlutterActivityDelegate.java:126)
io.flutter.app.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:137)
android.app.Activity.dispatchRequestPermissionsResult (Activity.java:7546)
android.app.Activity.dispatchActivityResult (Activity.java:7397)
android.app.ActivityThread.deliverResults (ActivityThread.java:4560)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4608)
android.app.ActivityThread.-wrap19 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1832)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:6861)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
```

```
```

</details>

I hope this is enough information to tackle down the issue 

BR

**Comment by iapicca** [comment]
Hi @talhazzani 

is the issue you are describing occurring in production environment?

can you please provide your `flutter doctor -v` , 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by talhazzani** [comment]
Hi @iapicca 

Thanks for your reply and yes it's in production , 

flutter doctor -v
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-SA)
    • Flutter version 1.12.13+hotfix.8 at /Users/####/downloads/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/####/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.`

pubspec.yaml

`
name: ###
description: ####

version: 2.0.0+12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_barcode_scanner: ^0.1.7
  flutter_staggered_grid_view: any
  google_maps_flutter: ^0.5.25+2
  location: ^3.0.1
  provider: ^3.1.0+1
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  intl: ^0.16.0
  url_launcher: ^5.4.2
  rflutter_alert: ^1.0.3
  json_annotation: ^2.0.0
  flutter_datetime_picker: ^1.3.4
  sliding_up_panel: ^0.3.6
  flutter_svg: ^0.17.3+1
  image_picker: ^0.6.4
  package_info: ^0.4.0+16
  firebase_crashlytics: ^0.1.3+2
  device_info: ^0.4.2+1
  mask_text_input_formatter: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  intl_translation: ^0.17.7




module:
  androidX: true

flutter:
  uses-material-design: true

  assets:.......
`
Sample code:

Future getImage(ImageTypes imageType) async {
  var image = await ImagePicker.pickImage(
      source: ImageSource.camera, maxHeight: 840, maxWidth: 680);
//then use image for my needs


I hope this enough to debug the problem

**Comment by Inf0rmatix** [comment]
maybe relates to https://github.com/flutter/flutter/issues/55558? See my comment there

**Comment by talhazzani** [comment]
Thanks @IInf0rmatix , most likely your comment is valid in my case will close this
