### ISSUE TITLE
Possible regression in microbenchmarks_ios stock_animation_subsequent_frame_average

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53930]
It's noisy, but could be around https://github.com/flutter/flutter/pull/53757. 

![Screen Shot 2020-04-03 at 9 21 36 AM](https://user-images.githubusercontent.com/1435716/78383068-a60d9280-758c-11ea-809f-521d2c50d993.png)

**Comment by tvolkert** [comment]
Looks like it's been slowly creeping up over several months.  Rebaselined.
