### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by razu-shaikh** [flutter/flutter#53932]
connection terminated during handshake
pub get failed (server unavailable).....attempting retry 1 in 1 second...." from bangladesh

**Comment by VladyslavBondarenko** [comment]
Hi @razu-shaikh 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/dart-lang/pub/issues/2288
You can try https://github.com/dart-lang/pub/issues/2288#issuecomment-607721988
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
