### ISSUE TITLE
geeting an error[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Error while fetching data

### ISSUE THREAD

**Issue by jagadeesh1813** [flutter/flutter#53947]
import 'dart:core';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'forgotp.dart';
import 'package:http/http.dart' as http;

class login extends StatefulWidget{
  final Future<Post> post;

  login({Key key, this.post}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return new loginstate();
  }

}
class Post {
  final String emailId;
  final String password;

  Post({this.emailId, this.password, });

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      emailId: json['emailId'],
      password: json['password'],
    );
  }

  Map toMap() {
    var map = new Map<String, dynamic>();
    map["emailId"] = emailId;
    map["password"] = password;
    return map;
  }
}

Future<Post> createPost(String url, {Map body}) async {
  return http.post(url, body: body).then((http.Response response) {
    final int statusCode = response.statusCode;

    if (statusCode < 200 || statusCode > 400 || json == null) {
      throw new Exception("Error while fetching data");
    }
    return Post.fromJson(json.decode(response.body));
  });
}

class loginstate extends State<login>{

  static final CREATE_POST_URL = 'https://console.nebeskie.com/api/login';
  final TextEditingController _userController = new TextEditingController();
  final TextEditingController _passwordController = new TextEditingController();
  @override
  Widget build(BuildContext context) {
    return new Scaffold(

      body:

      new Container(
        child: new ListView(
          children: <Widget>[
            new Padding(padding:
            const EdgeInsets.all(20.0)),
                Container(
                  alignment: Alignment.topRight,
                  margin: const EdgeInsets.only(left: 38.0,right: 38.0,),
                  child: new InkWell(
                    child: new Text("Forgot Password",style: new TextStyle(
                      color: Colors.black,
                      fontSize: 17.0,
                    ),),
                    onTap: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context)=>fp()));
                    },
                  ),
                ),

            new Padding(padding: 
            const EdgeInsets.all(24.0)),
            Container(
              margin: const EdgeInsets.only(left: 38.0),
              child: new Row(
                children: <Widget>[
                new Text("Sign In",style: new TextStyle(
                    color: Colors.black,
                    fontSize: 24.4,
                    fontWeight: FontWeight.w400
                  ),)

                ],

              ),
            ),
            new Padding(padding:
            const EdgeInsets.all(54.0)),
            //form
            new Container(
              alignment: Alignment.center,
              margin: const EdgeInsets.only(left: 38.0,right: 38.0,),
              height: 280.0,
              width: 380.0,
              child: new ListView(

                children: <Widget>[
                  new TextField(
                    controller: _userController,
                    decoration: new InputDecoration(
                      hintText: 'Your Email',

                    ),
                  ),
                  new TextField(
                    controller: _passwordController,
                    decoration: new InputDecoration(
                        hintText: 'Password',

                    ),

                  ),
                  new Padding(padding: EdgeInsets.all(10.5)),
                  new Center(
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,

                      children: <Widget>[
                        new Container(

                          width:280,
                          height: 50,
                          child: new RaisedButton(onPressed: () async {
                            Post newPost = new Post(
                                 emailId: _userController.text, password: _passwordController.text);
                            Post p = await createPost(CREATE_POST_URL,
                                body: newPost.toMap());
                          },

                          color: Colors.black,
                            child:  new Text("Sign In",
                            style: new TextStyle(
                              color: Colors.white,
                              fontSize: 17.0,
                            ),
                            ),
                          ),
                        ),

                      ],
                    ),
                  )
                ],
              ),

            ),

          ],
        ),
      ),
    );
  }

}

**Comment by jagadeesh1813** [comment]
help me out

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by jagadeesh1813** [comment]
y i am facing it

> Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

y i am facing it
