### ISSUE TITLE
"Apply Code Changes" for Android doesn't work because AssetManifest.json is changed every build

### ISSUE THREAD

**Issue by tomrozb** [flutter/flutter#53946]
There's a nice feature in Android Studio to apply code changes without restarting Android app. I have Flutter embedded as a module and I use is a FlutterActivity.

Every time I make single line change in Android related XML, apply code changes can't do its work because of this error:

```
04/03 21:47:53: Applying code changes to 'app' on 8.0 720p.
Changes were not applied.
Modifying resources requires an activity restart.
Resource 'assets/flutter_assets/AssetManifest.json' was modified.
Apply changes and restart activity
```

This happens only for Android projects with Flutter. 

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

**Comment by jonahwilliams** [comment]
The `flutter.gradle` plugin should not be modifying asset files unnecessarily. We'd likely need more information about the workflow you're using - are you running a specific flutter command or Gradle task?

**Comment by tomrozb** [comment]
Turns out it's related to https://github.com/flutter/flutter/issues/53756

Basically you even if you have the assets in `/assets` directory in the project root, you have to import it like this:

```
assets:
   - assets/some-asset.png
```

If you don't provide the directory in the asset path the reported issue occurs.
