### ISSUE TITLE
Camera recording problem on SAMSUNG android 8.x and 9.x devices on S7, J5, J7J6, J8, etc.

### ISSUE THREAD

**Issue by dtobaldi** [flutter/flutter#53941]
Recording videos on SAMSUNG devices (EJ S7, J6, J7, J8) does not work. For example when I try to play a recorded video:

- On S7, J7 devices: first the audio is played with a frozen image, and then when the audio ends the video starts but without no sound.

- On S7, J7 devices: Only audio is played with a frozen image, and video is never played.

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 6.3.9600], locale es-AR)
    • Flutter version 1.12.13+hotfix.9 at D:\Users\Cristian\Dropbox\Java\flutter
    • Framework revision f139b11009 (4 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Cristian\AppData\Local\Android\Sdk
    • Java binary at: D:\Users\Cristian\Dropbox\Java\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Users\Cristian\Dropbox\Java\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.0

[√] Connected device (1 available)
    • SM J710MN • 52033821fc1c83f3 • android-arm • Android 8.1.0 (API 27)

**Comment by mhbdev** [comment]
I have an issue like that on my Samsung J7 Prime (SM-G610F) and when I try to replay the video that is saved player shows the time something like this 43:21:10 and video is not playing.
I am using camera plugin example

**Comment by ccamba** [comment]
I have the same issue and only by rebooting the device can I record normally.

**Comment by mhbdev** [comment]
> I have the same issue and only by rebooting the device can I record normally.

are you testing on a real device?

**Comment by dtobaldi** [comment]
yes, @mhbdev  I tested on real devices.

**Comment by mhbdev** [comment]
@dtobaldi Taht's really odd :| I tried to reboot my device and well It's working but what happened? Idk.
and one more thing : after I did reboot my phone I ran the application in profile mode (--profile) and that works normally :(

**Comment by ccamba** [comment]
@mhbdev In order to replicate, reboot a device while connected to USB. Run the sample (https://pub.dev/packages/camera#-example-tab-). All should be ok. Then, disconnect the device, let it go into deep sleep (screen off, no movement for 5 minutes), and try again. The issue will appear once the device has gone into deep sleep.

**Comment by ccamba** [comment]
@mhbdev I found a solution for our needs which is to take photos and record videos natively without using the camera plugin. You can use the https://pub.dev/packages/image_picker plugin that fulfills this function like a charm.

**Comment by iapicca** [comment]
Hi @dtobaldi 
does @ccamba [solution](https://github.com/flutter/flutter/issues/53941#issuecomment-608887075) works for you?
If the issue persists your `flutter run --verbose`,
your `pubspec.yaml` and a reproducible minimal code sample.
Thank you

**Comment by dtobaldi** [comment]
Cristian proposes to use "packages / image_picker" instead of "/ packages / camera". The bug has not been fixed.

I Attach verbose and code files.

Regard

[verbose.txt](https://github.com/flutter/flutter/files/4438535/verbose.txt)
[code.txt](https://github.com/flutter/flutter/files/4438536/code.txt)

**Comment by perracolabs** [comment]
Some users reported the same issue on Samsung J6 devices (SM-J600G, j6lte, API 28). 
Two different users sent me corrupted sample videos, and after inspecting them I found out that the first frame has an exaggerating large delta duration time.

So, with an incorrect delta time, it makes the impression that the video is frozen, when is actually just showing in screen the first frame as per its defined delta duration time, which for corrupted videos is tremendously long.

To fix these samples, I replaced the delta time of the first frame with the value from the second frame (it seems that only the first frame is affected). Then the video plays correctly as expected.
But this is not a proper solution, as it means to have to check every video and repackage it if affected, as I couldn't find a way to fix it in-place. So the operation requires to create a new video file, copy the contents of the original with the correct delta time, and finally replace the original file with the fixed one.

The proper solution would be to find out how the MediaRecorder API computes delta times, and why in some scenarios for the affected devices produces an invalid value for the first frame.

My only guess is that if by any chance the MediaRecorder implementation uses the System.nanoTime clock, then I read in some StackOverflow posts that this system clock gives sometimes a bizarre value when coming back from a device deep-sleep. If that was the real issue then the only real solution would be that Samsung fixes its implementation. But is only a guess as I don’t know how the MediaRecorder API computes delta times.

**Comment by darshankawar** [comment]
Revisiting this issue, @dtobaldi, I tried the camera plugin example using Samsung S10 device with latest versions and was able to record video without any issues. 
Can you recheck your scenario on same device you highlighted in original description, using latest plugin version and framework version to see if the behavior you reported still persist or not ?
