### ISSUE TITLE
Exception when using TextFormField while changing the theme

### ISSUE THREAD

**Issue by mploigt** [flutter/flutter#53948]
## Steps to Reproduce

1. clone https://github.com/mploigt/flutter_text_field_bug_with_provider
2. run the project in simulator
3. type something in the "email" field
4. click into the password field
5. click the switch in the top right corner.

(video of bug is included in the above repo)

**Expected results:** 
No thrown exeption

**Actual results:** 
Exception "Duplicate GlobalKey detected in widget tree." trown

<details>
  <summary>Logs</summary>

```
see:
run_verbose.txt
analyze.txt
doctor.txt
```

```
```
</details>

[analyze.txt](https://github.com/flutter/flutter/files/4429715/analyze.txt)
[doctor.txt](https://github.com/flutter/flutter/files/4429716/doctor.txt)
[run_verbose.txt](https://github.com/flutter/flutter/files/4429717/run_verbose.txt)

**Comment by mploigt** [comment]
This bug has noting to do with using a ChangeNotifierProvider. The demo repo now has a branch without using it and the same error appears.

**Comment by LongCatIsLooong** [comment]
This should be fixed on master and beta already. Could you try switching to master and see if the problem persists?

**Comment by mploigt** [comment]
Yes. I'm now using Flutter 1.15.17 beta and the problem is gone. Thanks for the quick help!
