### ISSUE TITLE
how flutter map in for widget

### ISSUE THREAD

**Issue by farukx** [flutter/flutter#53953]
my json=

```
{
  "result": {
    "name": "json1",
      "pages": [{
          "zones": [{
              "title": "title1"
           },
           {
              "title": "title2"
           }],
           "id": 4
       },
       {
          "zones": [{
            "title": "title3"
          },
          {
            "title": "title4"
          }],
          "id": 12
       }],
       "creatorUserName": "admin",
       "id": 2
    }
}
```
futurebuilder code

```
List post = snapshot.data["result"]["pages"];
return new Stack(
              children: post.where((val) => val["id"] == 4).map((post) {
                for (var item in post['zones']) {
                print("title "+ item['title']);
                  Container(
                    child: Text(item["title"]),
                  ); //Container
                }
              }).toList(),
); //Stack

```
Error code: Stack's children must not contain any null values, but a null value was found at index 0 enter image description here
<img width="1271" alt="myerror" src="https://user-images.githubusercontent.com/55917247/78404841-e9591700-7607-11ea-84cd-195b0040e907.png">

help how can to build an algorithms

if get id = 4 zones -> Text(title1), Text(title2),

else id empty zones -> Text(title1), Text(title2), zones -> Text(title3), Text(title4),

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
