### ISSUE TITLE
Add support for cookie management

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#5396]
Currently Flutter developers have to manage cookies manually.

Flutter should add a management class (perhaps similar to Android's CookieManager) to its network service APIs, to make this process easier.

**Comment by pmzakula** [comment]
This would be a great feature to add.  I think it will make things easier.

**Comment by eseidelGoogle** [comment]
I just asked in https://gitter.im/dart-lang/TALK-general.  I'm really surprised Dart doesn't already have a package for this?

**Comment by sethladd** [comment]
What exactly are the use cases? It may be that the browser's API for cookies was sufficient, and thus no Dart library appeared.

This issue is kind of vague. Can we get more specifics, or consider closing?

**Comment by sethladd** [comment]
@krisgiesing what problem(s) did you run into?

**Comment by krisgiesing** [comment]
I wrote this in response to a thread on flutter-dev@googlegroups.com called "Http Request Session Handling" on Aug. 15, 2016. I can't find the flutter-dev group now, did it get renamed or something?

@Hixie wrote in that thread: "Currently you have to manage your own cookies, unfortunately. You're right that we should have this baked into our networking library. We're still trying to figure out exactly how we want our networking library to work (we don't like the current situation where we have two redundant libraries, for instance)."

**Comment by Hixie** [comment]
At the time we were going to have our own HTTP library, but now we're deferring to the Dart ecosystem. So this is probably WONTFIX.

**Comment by eseidelGoogle** [comment]
@krisgiesing here is the topic: https://groups.google.com/d/topic/flutter-dev/nXtVXyg3FsU/discussion

**Comment by krisgiesing** [comment]
Ah yes, I was not looking at google groups in the correct organization view. Sigh.

**Comment by krisgiesing** [comment]
Is the dart ecosystem going to address this issue? Do we have an issue in another project we can link to from here?

**Comment by eseidelGoogle** [comment]
My understanding from @nex3 over gitter is that package:http is this package.  Certainly https://www.dartdocs.org/documentation/http/0.11.3%2B9/http/Client-class.html appears to be for doing multiple-requests across a session.  Unclear how exactly one does cookie management in package:http, but I'm certainly not the expert there.

**Comment by nex3** [comment]
It's more that `http` is *designed to be* this package—it's not quite there yet, including in terms of cookie support. @donny-dont is working on a major refactor to make it act more like Shelf, at which point adding proper cookie support will be easier.

**Comment by DrMabuse23** [comment]
but that means we cant handle a JSESSIONID?

**Comment by asinel** [comment]
There is still no possibility to handle cookies?

**Comment by pmzakula** [comment]
I believe you have to handle them manually @asinel

**Comment by eseidelGoogle** [comment]
@nex3 where can one learn more about @donny-dont's refactor or if that's still the right path for us?

**Comment by eseidelGoogle** [comment]
This might be the package:http bug about cookies? https://github.com/dart-lang/http/issues/20  I'm not sure.

**Comment by donny-dont** [comment]
@eseidel its basically `shelf`. You can look at the master branch to get an idea on what's going on.

**Comment by eseidelGoogle** [comment]
@donny-dont I'm not sure how https://github.com/dart-lang/shelf/tree/master/lib relates to the client-side uses of package:http?  Am I looking in the right place?

**Comment by donny-dont** [comment]
@eseidel sorry I assumed familiarity with `shelf` there. The `http` refactor turns the library into a middleware based library. So in this case someone would create a cookie middleware which would populate some kind of cookie jar implementation in dart which would grab from the jar on a request and populate the jar on a response.

I don't personally have plans to write such a middleware but its something that should be doable for flutter apps.

**Comment by nex3** [comment]
Cookies are tricky because they poke a difficult corner case of HTTP headers:

* The vast majority of headers can only be specified one time.
* Some headers can be specified multiple times, but they're required by spec to be combinable into a single comma-separated header.
* ...*except for cookies*. The `Set-Cookie` header may appear multiple times in a response header, and it may not be folded into a single header.

We want to make it easy to work with headers in the 90% case in which they act like a normal `Map`, with one value for each key. We also want to normalize multi-value headers that are specified as comma-separated versus appearing multiple times, so the user doesn't have to care about that distinction. We *also* want to make it possible to read and write cookies. And on top of all that, we want to use a consistent API between `http` and `shelf`.

A year ago, I started working with @rwrozelle to figure this out. Unfortunately, their implementation stalled out with the question of what sort of type should be used to represent headers. They submitted a `MultiMap` CL to the `collection` package (https://github.com/dart-lang/collection/pull/47), but @lrhn was opposed to having `MultiMap<K, V>` implement `Map<K, V>` and we never really moved forward from there.

**Comment by markmclaren2** [comment]
The lack of support for cookies in Flutter is a pretty major deficiency in my opinion.  Isn't it a pretty common use case for mobile apps to 'log in' to the server and receive a session id by cookie?

For others with the same problem - here is the workaround I used:
https://stackoverflow.com/questions/52241089/how-do-i-make-an-http-request-using-cookies-on-flutter

**Comment by zoechi** [comment]
@markmclaren2 It isn't difficult to handle such a cookie yourself.

**Comment by Iarly** [comment]
> The lack of support for cookies in Flutter is a pretty major deficiency in my opinion. Isn't it a pretty common use case for mobile apps to 'log in' to the server and receive a session id by cookie?
> 
> For others with the same problem - here is the workaround I used:
> https://stackoverflow.com/questions/52241089/how-do-i-make-an-http-request-using-cookies-on-flutter

I'm very upset that Flutter doesn't have cookie support. I'm looking for a workaround too, but this workaround doesn't work for me. In my case the request's header has two or more "Set-cookie"... :(

**Comment by iarly** [comment]
> The lack of support for cookies in Flutter is a pretty major deficiency in my opinion. Isn't it a pretty common use case for mobile apps to 'log in' to the server and receive a session id by cookie?
> 
> For others with the same problem - here is the workaround I used:
> https://stackoverflow.com/questions/52241089/how-do-i-make-an-http-request-using-cookies-on-flutter

I'm very upset that Flutter doesn't have cookie support. I think is very common this use case.

I'm looking for a workaround too, but in my case my server returns two or more 'Set-cookies'. So I have improved this workaround with the possibility to receive multiple 'Set-cookies' and multiple cookies.

https://stackoverflow.com/questions/52241089/how-do-i-make-an-http-request-using-cookies-on-flutter/53991733#53991733

**Comment by eseidelGoogle** [comment]
https://github.com/dart-lang/http/issues/20 is the right bug to bring these issues up on.

I agree that package:http should support cookies.  I'll bring it up when I next talk to the relevant engineers.

**Comment by hoaquo** [comment]
I make a http POST and it returns 303 with some cookies, default implementation for the next redirect ignores cookies( while it should takes them for redirecting) and then I never get the expected result.

Is there any workaround for this problem or should I wait for new feature?

**Comment by dylanbr19** [comment]
I'm still a little lost on the Dio approach @hoaquo , are you able to expand a little more?

**Comment by awafL** [comment]
I'm a bit late for the party, but I am facing the same trouble. However, I am dealing with Laravel, where the amount of cookies that it requires is much bigger. To manage 6 cookies by hand is quite tedious and since there are so many libraries that make the effort to support them, why not merge http and, for example, dio? Are there any limitations to the http library preventing this from happening?

**Comment by trungbq1712** [comment]
> > At the time we were going to have our own HTTP library, but now we're deferring to the Dart ecosystem. So this is probably WONTFIX.
> 
> How about this progress? About 3yrs

i have same issue,how to solve if coding with dart

**Comment by Mickey-A-Mouse** [comment]
Hah, 4 years! Still no response.. I really wondered that this issue is still alive

**Comment by NamPNQ** [comment]
@Mickey-A-Mouse You can look at this https://pub.dev/packages/cookie_jar

**Comment by Mickey-A-Mouse** [comment]
> @Mickey-A-Mouse You can look at this https://pub.dev/packages/cookie_jar

Hello!)) Could you provide some sample code about how to implement this library in project with http library? Please, I really stacked with this now(even more, I asked about this integration in [here ](https://stackoverflow.com/questions/64294999/http-with-cookie-jar-libraries-flutter))

**Comment by Mickey-A-Mouse** [comment]
> @Mickey-A-Mouse You can look at this https://pub.dev/packages/cookie_jar

I've achieved my goal by using a dio library))
