### ISSUE TITLE
[tool] [proposal] Allow only accepted char to be typed

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#53961]
Please force the command line to not accept any letter typed from the developer except the letters are supported during 'flutter run' is active .....

my example: i using EN/AR keyboard , if i press r/R to make hot reload and i forget to convert to the EN before pressing it force me to completely close my app and re-run the command 'flutter run' again .. , be cause the command line has received 'ق' letter instead of R letter , and will not accept any letter from me until i do what i did above .. , so please make the command line reject any letter except what u support , thanks.

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/49621
