### ISSUE TITLE
Extract browser automation code into a standalone package

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#53965]
The Web Engine, benchmarks, and Flutter Tools all need to be able to manipulate browsers. Currently each maintains its own copy of code that does this. Opening this issue to discuss the possibility of merging all this logic into a common package.

Questions to consider:

- Where should the package live? One candidate is https://github.com/flutter/web_installers.
- What's the scope and API surface of the package? Although multiple places need this functionality, they have different scope. For example, Flutter Tools and benchmarks only require Chrome support.  However, the Web Engine requires all browsers. If we merge, we will end up with an API surface that must satisfy the union of requirement. Does it mean, for example, that we will have to implement API for benchmarks that doesn't work on Firefox, or works on Firefox but we don't use it?
- How are dependencies on the package managed? Should it be on pub? Should it be a git dependency? Should it be an SDK dependency?

/cc @nturgut @jonahwilliams

**Comment by nturgut** [comment]
>* Where should the package live? One candidate is https://github.com/flutter/web_installers.

Yes I think web installers is the right place.

> * What's the scope and API surface of the package? Although multiple places need this functionality, they have different scope. For example, Flutter Tools and benchmarks only require Chrome support.  However, the Web Engine requires all browsers. If we merge, we will end up with an API surface that must satisfy the union of requirement. Does it mean, for example, that we will have to implement API for benchmarks that doesn't work on Firefox, or works on Firefox but we don't use it?

I think Chrome is the most urgent one, since we also have a mission of making sure that unit tests and integration tests are using the same chrome. Also the correct chrome driver is used.

> * How are dependencies on the package managed? Should it be on pub? Should it be a git dependency? Should it be an SDK dependency?

I don't have a preference. Now we are using git reference from pubspec files. It works for us. In my opinion, these are not useful libraries to external developers unlike flutter test or flutter drive. Therefore a pub package might not be necessary.

**Comment by yjbanov** [comment]
This is no longer interesting.
