### ISSUE TITLE
When I used the path_provider plugin for my flutter application, I encountered some problems

### ISSUE THREAD

**Issue by lxjmaster** [flutter/flutter#53977]
When I imported the path_provider plugin in the pubspec.yaml file, my flutter application failed to compile and threw the following error.

```bash
Launching lib\main.dart on Xiaomi in debug mode...

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':path_provider_macos'.

Could not resolve all dependencies for configuration ':path_provider_macos:classpath'.
   Could not load module metadata from C:\Users\37950.DESKTOP-SM4KBUP\.gradle\caches\modules-2\metadata-2.71\descriptors\com.android.tools.analytics-library\shared\26.2.1\fc7e8eef251519086b6ee9788cba4dd2\descriptor.bin
Could not get unknown property 'android' for project ':path_provider_macos' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

And my environment configuration information is as follows.

```console
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at F:\flutter
    • Framework revision f139b11009 (4 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:\flutter
    • Java binary at: F:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at F:\AndroidStudio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Xiaomi • 192.168.59.101:5555 • android-x86 • Android 9 (API 28)
```

Can you help me solve this problem?thank you!!!

**Comment by arashAndroid** [comment]
I have the same issues, no fixes yet?

**Comment by lxjmaster** [comment]
> I have the same issues, no fixes yet?

Has not been solved, and i do not know why there is such a mistake.

**Comment by iapicca** [comment]
Hi @lxjmaster 
thanks for your `flutter doctor -v` ;

can you please provide your full `flutter run --verbose`,
your `pubspec.yaml` and a reproducible minimal code sample.
Thank you

**Comment by arashAndroid** [comment]
I have found a solution for this.

**Comment by arashAndroid** [comment]
I have found a solution.
Go to your FlutterSDK folder, then go to `\.pub-cache\hosted\pub.dartlang.org\`
Then delete path_provider_macos-0.0.4

**Comment by lxjmaster** [comment]
> Hi @lxjmaster
> thanks for your `flutter doctor -v` ;
> 
> can you please provide your full `flutter run --verbose`,
> your `pubspec.yaml` and a reproducible minimal code sample.
> Thank you
@iapicca Of Course.

Running the flutter run --verbose command gives the following results

-------------------------------------------------------------------------
[  +33 ms] executing: [F:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +105 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +1 ms] executing: [F:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +6 ms] executing: [F:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [F:\flutter\] git ls-remote --get-url origin
[  +56 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] executing: [F:\flutter\] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +444 ms] executing: F:\sdk\platform-tools\adb.exe devices -l
[  +41 ms] Exit code 0 from: F:\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           192.168.59.101:5555    device product:vbox86p model:Xiaomi device:vbox86p transport_id:3
[  +19 ms] F:\sdk\platform-tools\adb.exe -s 192.168.59.101:5555 shell getprop
[ +107 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Found plugin connectivity at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity-0.4.8+2\
[  +10 ms] Found plugin connectivity_macos at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_macos-0.1.0+2\
[  +41 ms] Found plugin path_provider at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider-1.6.5\
[   +2 ms] Found plugin path_provider_macos at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_macos-0.0.4\
[ +164 ms] Found plugin connectivity at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity-0.4.8+2\
[   +4 ms] Found plugin connectivity_macos at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_macos-0.1.0+2\
[  +35 ms] Found plugin path_provider at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider-1.6.5\
[   +6 ms] Found plugin path_provider_macos at F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_macos-0.0.4\
[ +119 ms] Generating F:\FlutterApps\ssc\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +69 ms] ro.hardware = vbox86
[   +1 ms] ro.build.characteristics = nosdcard
[ +165 ms] Launching lib\main.dart on Xiaomi in debug mode...
[  +44 ms] executing: F:\sdk\build-tools\28.0.3\aapt dump xmltree F:\FlutterApps\ssc\build\app\outputs\apk\app.apk
AndroidManifest.xml
[  +62 ms] Exit code 0 from: F:\sdk\build-tools\28.0.3\aapt dump xmltree F:\FlutterApps\ssc\build\app\outputs\apk\app.apk
AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.ssc" (Raw: "com.example.ssc")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw:
                 "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.ACCESS_WIFI_STATE" (Raw: "android.permission.ACCESS_WIFI_STATE")   
               E: application (line=24)
                 A: android:label(0x01010001)="ssc" (Raw: "ssc")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=30)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.ssc.MainActivity" (Raw: "com.example.ssc.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=37)
                     E: action (line=38)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=40)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")     
                 E: meta-data (line=47)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +49 ms] executing: F:\sdk\platform-tools\adb.exe -s 192.168.59.101:5555 shell -x logcat -v time -t 1
[  +83 ms] Exit code 0 from: F:\sdk\platform-tools\adb.exe -s 192.168.59.101:5555 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           04-06 05:40:40.256 I/system_server(  346): The ClassLoaderContext is a special shared library.
[  +15 ms] executing: F:\sdk\platform-tools\adb.exe version
[   +2 ms] executing: F:\sdk\platform-tools\adb.exe -s 192.168.59.101:5555 logcat -v time -T 04-06 05:40:40.256
[  +69 ms] Android Debug Bridge version 1.0.41
           Version 28.0.3-5475833
           Installed as F:\sdk\platform-tools\adb.exe
[   +5 ms] executing: F:\sdk\platform-tools\adb.exe start-server
[ +108 ms] Building APK
[  +38 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from F:\FlutterApps\ssc\android\gradlew.bat.
[  +18 ms] executing: F:\AndroidStudio\jre\bin\java -version
[ +311 ms] Exit code 0 from: F:\AndroidStudio\jre\bin\java -version
[   +3 ms] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
           OpenJDK 64-Bit Server VM (build 25.152-b01, mixed mode)
[   +8 ms] executing: [F:\FlutterApps\ssc\android\] F:\FlutterApps\ssc\android\gradlew.bat -Pverbose=true
-Ptarget=F:\FlutterApps\ssc\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[+4603 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +1 ms] A problem occurred configuring project ':path_provider_macos'.
[  +33 ms] > Could not resolve all dependencies for configuration ':path_provider_macos:classpath'.
[  +15 ms]    > Could not load module metadata from
C:\Users\37950.DESKTOP-SM4KBUP\.gradle\caches\modules-2\metadata-2.71\descriptors\com.android.tools\annotations\26.2.1\fc7e8eef251519086b6ee9788cba4dd2\descriptor.bin
[  +49 ms] > Could not get unknown property 'android' for project ':path_provider_macos' of type org.gradle.api.Project.
[   +9 ms] * Try:
[  +38 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with  
--scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 4s
[ +221 ms] Running Gradle task 'assembleDebug'... (completed in 5.3s)
[  +11 ms] "flutter run" took 7,226ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
--------------------------------------------------------------------------------


And my pubspec.yaml file looks like this.
-----------------------------------------------------------------------------
name: ssc
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  path_provider: ^1.4.5
  path: ^1.6.4

  connectivity: ^0.4.8+2

  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
------------------------------------------------------------------

My main.dart is as follows

import 'package:flutter/material.dart';
// import 'package:ssc/utils.dart';
import 'dart:io';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "ssc",
      home: HomePage(),
    );
  }
}



class HomePage extends StatefulWidget {

  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  List data = List<String>();
  FocusNode _horizontalFocusNode;
  FocusNode _verticalFocusNode;
  TextEditingController _horizontalController;
  TextEditingController _verticalController;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _horizontalFocusNode = FocusNode();
    _verticalFocusNode = FocusNode();
    _horizontalController = TextEditingController();
    _verticalController = TextEditingController();
    // 初始化
    // myinit();
    // readfile();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text("ssc")
      ),
      body: Container(
        padding: EdgeInsets.only(top: 20.0),
        child: Column(
          children: <Widget>[
            Row(
              children: <Widget>[
                Column(
                  children: <Widget>[
                    ConstrainedBox(
                      constraints: BoxConstraints(
                        maxHeight: 25,
                        maxWidth: 200
                      ),
                      child: TextField(
                        focusNode: _horizontalFocusNode,
                        controller: _horizontalController,
                        decoration: InputDecoration(
                          border: OutlineInputBorder(),
                          icon: Text("搜索横："),
                        ),
                      ),
                    ),
                    ConstrainedBox(
                      constraints: BoxConstraints(
                        maxHeight: 25,
                        maxWidth: 200
                      ),
                      child: TextField(
                        focusNode: _verticalFocusNode,
                        controller: _verticalController,
                        decoration: InputDecoration(
                          border: OutlineInputBorder(),
                          icon: Text("搜索纵："),
                        ),
                      ),
                    ),
                  ]
                ),
                Container(
                  child: OutlineButton(
                    child: Text("搜索"),
                    onPressed: (){},
                  )
                )
              ],
            ),
            Expanded(
              child: ListView.builder(
                itemCount: 1,
                itemBuilder: (BuildContext context, int index) {
                  return Row(
                    children: <Widget>[
                      Text("234"),
                      Text("345")
                    ],
                  );
                }
              )
            )
          ],
        ),
      )
    );
  }

  // readfile() async {
  //   File file = await getLocalFile();
  //   List text = await file.readAsLines();
  //   data = text;
  // }

}

**Comment by lxjmaster** [comment]
> I have found a solution.
> Go to your FlutterSDK folder, then go to `\.pub-cache\hosted\pub.dartlang.org\`
> Then delete path_provider_macos-0.0.4
> Then run the app.
> This fixed the problem for me

@arashAndroid 
I tried this method, but I don't have the path_provider_macos folder

**Comment by lxjmaster** [comment]
> > I have found a solution.
> > Go to your FlutterSDK folder, then go to `\.pub-cache\hosted\pub.dartlang.org\`
> > Then delete path_provider_macos-0.0.4
> > Then run the app.
> > This fixed the problem for me
> 
> @arashAndroid
> I tried this method, but I don't have the path_provider_macos folder

@arashAndroid @iapicca 

Surprisingly, this method works but my path_provider_macos document is not in the directory `\.pub-cache\hosted\pub.dartlang.org\`
Instead, it is in the directory `\.pub-cache\hosted\pub.flutter-io.cn\`
So the effective solution is to remove the path_provider_macos-0.0.4 folder.

Thank you very much.

**Comment by iapicca** [comment]
Hi @lxjmaster 
I'm glad that you solved the issue
thank you for letting me know
