### ISSUE TITLE
Android license status unknown.I am haveing problem with it can help me to reslove the problem.

### ISSUE THREAD

**Issue by Kawshik00khan** [flutter/flutter#53976]
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.719], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\shown\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.0

[√] Connected device (1 available)
    • M1 • 0123456789ABCDEF • android-arm • Android 5.0 (API 21)

! Doctor found issues in 1 category.

**Comment by aditya305** [comment]
The solution is very simple. Follow these steps.

1.  Open **Android Studio** 
2. Open **Configure**
3. Open **SDK Manager**
4. In bottom untick the **Hide Obsolete Package**
5. Now in **SDK Tools** select **Android SDK Tool (Obsolete)** and click **Apply** install the package  
6. Open a **command prompt** and run **flutter doctor**
7. then run **flutter doctor --android-licenses**

**Comment by aditya305** [comment]
or refer to this Link
[robbinespu.gitlab.io/blog/2020/03/03/flutter-issue-fixed-android-license-status-unknown-on-windows/](url)

**Comment by Kawshik00khan** [comment]
@aditya305 I have done that but it`s say :  C:\Users\shown>flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
C:\Android\tools\bin\sdkmanager --update



C:\Users\shown>C:\Android\tools\bin\sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more.
Now what should i do??

**Comment by Kawshik00khan** [comment]
@aditya305 can i download java8 or java 12 and uninstall java 14??

**Comment by iapicca** [comment]
Hi @Kawshik00khan 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
