### ISSUE TITLE
flutter upgrade not working

### ISSUE THREAD

**Issue by Reshad-Hasan** [flutter/flutter#53994]
## Steps to Reproduce

1. add
 dependencies:
  http: ^0.12.0+4 
in pubspec.yaml file
2. run flutter pub get
3. run flutter upgrade

## Logs

I was trying to add scoped_model and http package but got a version error. that's why I tried upgrade flutter. but when it tries to download Dart SDK it can not do it with BITS.

flutter doctor -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At D:\flutter\bin\internal\update_dart_sdk.ps1:68 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Error: Unable to update Dart SDK. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At D:\flutter\bin\internal\update_dart_sdk.ps1:68 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Error: Unable to update Dart SDK. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
Terminate batch job (Y/N)? Y

I have checked:
1. BITS was running
2. dependencies of BITS such as RPC was also running

**Comment by timsneath** [comment]
This looks like a network error. Are you able to access this URL?https://storage.googleapis.com/flutter_infra/flutter/af51afceb8886cc11e25047523c4e0c7e1f5d408/dart-sdk-windows-x64.zip

If so, please try again. If not, please check your internet connection.

Thanks for using Flutter!

**Comment by Reshad-Hasan** [comment]
I can not access this URL.
But my internet connection is working fine for everything else. what should I do?

**Comment by Reshad-Hasan** [comment]
Issue fixed. after using a vpn it worked. but I don't know why it did not work before. My guess is that 
shared IP does not work in the dart server. I hope you would fix it because a lot of ISP provide shared IP
