### ISSUE TITLE
.gradle folder increases every run debug

### ISSUE THREAD

**Issue by kacasoft** [flutter/flutter#53996]
Hello guys.,
please your advice, i have trouble each time running flutter debug.

Every time I run or debug, the .gradle folder will be created as shown below.

Well, the problem is, the folder always increases in size every time I debug. Of course this is a problem as I experienced, suddenly my hard drive is full, and after I check it turns out that the .gradle folder reaches 30GB in size, and when I try to run debug again the size continues to increase ..

Are there any settings for this problem ??

Please advise.
sorry for my bad english.[
![92489660_10216370671090712_7069491279880519680_o](https://user-images.githubusercontent.com/8125038/78454247-76b07000-76c9-11ea-9a0f-4bad027688b8.jpg)

**Comment by iapicca** [comment]
HI @kacasoft 
30gb of cache for gradle is unusual 
could you please provide your `flutter doctor -v`?
thank you

**Comment by kacasoft** [comment]
@iapicca sorry for long update.

> If I understand correctly the cache increases every run,
even without changes, is that correct?

yes alright...increase size every run.

i think flutter too much download when running debug.

below flutter doctor -v

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\Master\Flutter
    • Framework revision f139b11009 (9 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\tools
    • Java binary at: C:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Acer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jonahwilliams** [comment]
This is the intended functionality of Gradle and not something flutter can change. See also https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache for information on how to clear this cache
