### ISSUE TITLE
Standalone embedder initialization failed: Error determining current directory: Operation not permitted

### ISSUE THREAD

**Issue by churchevent** [flutter/flutter#54005]
I am getting this error when I tried to build the flutter iOS project in Xcode
Standalone embedder initialization failed: Error determining current directory: Operation not permitted

## Steps to Reproduce

1. Run `flutter create churchevents`.
2. cd to church events and run 'flutter run'  to make sure the app runs in debug mode
3. use Xcode (11.3.1)  to open the iOS project ../churchevents/ios/Runner.xcworkspace
4. In Xcode change the Runner Target bundle identifier to 'com.outafire.churchevents'
5. in Xcode click the menu Product/Build
The build alway failed with the same message. I tried Xcode 11.4 - same result.
I also tried running the command 'pod degenerate runner.xcodeproj' then run 'pod install', but same error.
I also ran 'flutter clean' and from Xcode I click on the menu 'Product/Clean Build Folder' then tried the build again, but it failed. 
I am expecting a successful release build, but I always get that same error.
<details>
  <summary>Logs</summary>
here is the log from 'flutter build ios --release -v'
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios --release -v

## exception

_Exception: Exception: Source directory "/tmp/Runner.dst/Applications/Runner.app" does not exist, nothing to copy

```
#0      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:79:5)
#1      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:558:7)
<asynchronous suspension>
#2      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:80:43)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at /Users/carlton/tools/flutter
    [32m•[39m Framework revision f139b11009 (5 days ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at /Users/carlton/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C505
    [32m•[39m CocoaPods version 1.9.1

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[32m[✓][39m VS Code (version 1.43.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.9.0

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```
FROM Xcode Error log

    /bin/sh -c /Users/carlton/Library/Developer/Xcode/DerivedData/Runner-cjhgzdyvgdocfpacsknvjdqyoncu/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh

**Standalone embedder initialization failed: Error determining current directory: Operation not permitted**

Failed to package /Users/carlton/Desktop/development/churchevent.
**Command PhaseScriptExecution failed with a nonzero exit code**
<img width="1440" alt="iOSBuildError" src="https://user-images.githubusercontent.com/62756529/78457823-12ff5600-767b-11ea-9cd6-e9349b1b164d.png">

</details>

**Comment by churchevent** [comment]
I added the second line to the BuildPhase Run Script section.  This fixed the build error.
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build  
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

**Comment by churchevent** [comment]
Now when I tried to run it from Xcode, I got the following errors:
2020-04-04 15:52:01.981032-0400 Runner[40099:2628242] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2020-04-04 15:52:02.126001-0400 Runner[40099:2629993] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
2020-04-04 15:52:02.126762-0400 Runner[40099:2629993] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
2020-04-04 15:52:02.202538-0400 Runner[40099:2630003] flutter: Observatory listening on http://127.0.0.1:53048/4ZbipDTdiUM=/

**Comment by iapicca** [comment]
Hi @churchevent 
I see you have another [issue](https://github.com/flutter/flutter/issues/54053) open
that seems to address the same app and the same error

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by churchevent** [comment]
Ok. But the 'Flutter Build ios' command and xcode build are performing different compilation giving different messages.

⁣Get BlueMail for Android ​

**Comment by iapicca** [comment]
Hi again @churchevent 

I apologise if I missed something,
the only difference I perceive is this issue referencing to the latest `stable`
while the linked issue references to `master` making it more actable.

The error in the log look the same to me.

Please add any relevant information 
that I might have missed to the issue linked above
to avoid keeping open multiple issue on the same problem.
Thank you
