### ISSUE TITLE
Dart DevTools exited with code 255 Flutter VS Code

### ISSUE THREAD

**Issue by sagarkhurana00786** [flutter/flutter#54008]
When I try to open Dart DevTools in VS CODE. Shows error that "Dart DevTools exited with code 255".
Here is my `flutter doctor -v` output

```
PS D:\FlutterProjects\expenses_app> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\Flutter\flutter
    • Framework revision f139b11009 (5 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\AndroidSDKComponentSetup
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\AndroidSDKComponentSetup
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\SagarKhurana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM J200G                  • 320136c19c48b45b • android-arm   • Android 5.1.1 (API 22)
    • Redmi 8                   • ad4810d10506     • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

Thanks

**Comment by VladyslavBondarenko** [comment]
Hi @sagarkhurana00786 
Can you see the same error when running [DevTools from command line](https://dart.dev/tools/dart-devtools)?

```
flutter pub global activate devtools
flutter pub global run devtools
```

**Comment by sagarkhurana00786** [comment]
@VladyslavBondarenko thanks for showing your concern
the output of `flutter pub global activate devtools`

PS D:\FlutterProjects\expenses_app> flutter pub global activate devtools
Package devtools is currently active at version 0.2.3.
Resolving dependencies...
+ args 1.6.0
+ async 2.4.1
+ browser_launcher 0.1.5
+ charcode 1.1.3        
+ collection 1.14.12    
+ convert 2.1.1
+ crypto 2.1.4
+ devtools 0.2.3 (0.2.4-dev.1 available)       
+ devtools_server 0.2.3 (0.2.4-dev.1 available)
+ devtools_shared 0.2.3 (0.2.4-dev.1 available)
+ http 0.12.0+4
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.1.8
+ mime 0.9.6+3
+ path 1.6.4
+ pedantic 1.9.0
+ shelf 0.7.5
+ shelf_static 0.2.8
+ source_span 1.7.0
+ sse 3.2.1
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ usage 3.4.1
+ uuid 2.0.4
+ vm_service 3.0.0+1 (4.0.0 available)
+ webkit_inspection_protocol 0.5.0+1
Precompiling executables...
Precompiled devtools:bin\devtools.
Installed executable devtools.
Warning: Pub installs executables into D:\Flutter\flutter\.pub-cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated devtools 0.2.3.
PS D:\FlutterProjects\expenses_app> 

and output of `flutter pub global run devtools`

PS D:\FlutterProjects\expenses_app> flutter pub global run devtools
Serving DevTools at http://127.0.0.1:9100

In **flutter pub global run devtools** it wont show anything beyond **Serving DevTools at http://127.0.0.1:9100**
Please help 
Thanks

**Comment by iapicca** [comment]
Hi @sagarkhurana00786 
now that you successfully activated devtools
did you try launching it from vscode as described in the [docs](https://flutter.dev/docs/development/tools/devtools/vscode)?
Thank you

**Comment by sagarkhurana00786** [comment]
@iapicca on following **docs** still getting same error code 225
I still don't know where are the problem and whats the problem
Thanks

**Comment by VladyslavBondarenko** [comment]
@sagarkhurana00786 
if you run your app from terminal, you can see such log
```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available
at: http://127.0.0.1:60230/J7_wS_YhTuo=/
```
Run in another terminal `flutter pub global run devtools` and then open `http://127.0.0.1:9100` 

enter in the `Connect to a running app` field address of your running app `http://127.0.0.1:60230/J7_wS_YhTuo=/`

can you see `exited with code 255` error now?
or only when opening DevTools from VS Code?

**Comment by sagarkhurana00786** [comment]
@VladyslavBondarenko 
Now in this process, I'm not facing any issue after putting my flutter app URL then immediately I'm connected to Dart Dev tools.
But Why it is showing error When I try to open it from VS Code
Thanks, Everyone

**Comment by VladyslavBondarenko** [comment]
@sagarkhurana00786 
It may be not the issue with Flutter,
please create an issue in the [Dart extension repository](https://github.com/Dart-Code/Dart-Code) and link there current one.
Closing this for now, comment if it turned out that it's not only problem with VS Code extension and I'll reopen

**Comment by sagarkhurana00786** [comment]
@VladyslavBondarenko Okay Then I create an issue on that 
Thanks 👍
