### ISSUE TITLE
[certificate] Renew publishing certificate to deploy the flutter gallery app

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#54016]
Error: "Your certificate '7NT48M7VVR.cer' is not valid, please check end date and renew it if necessary" from https://cirrus-ci.com/task/5601766490243072?command=main#L74

We need to renew the certificate stored in a private github repo using fastlane. 

/cc @xster who set it up in the first place.

**Comment by digiter** [comment]
The cert is still not working: https://cirrus-ci.com/task/5084165720768512

**Comment by digiter** [comment]
This is fixed.

**Comment by pcsosinski** [comment]
@digiter is there anything that needs to be CP'd to the 1.17 branch?

**Comment by digiter** [comment]
@pcsosinski Yes, we can cherry pick https://github.com/flutter/flutter/pull/54248 to "flutter-1.17-candidate.5", to make the "deploy_gallery-macos" passes on the tip of tree.

**Comment by pcsosinski** [comment]
we're on flutter-1.17.candidate.3 as our 1.17 branch

**Comment by digiter** [comment]
The flutter-1.17.candidate.3 seems fine. Anyway if you see error about renewal on deploy_gallery-macos, you can apply #54248 to fix it.

**Comment by pcsosinski** [comment]
removing CP: 1.17 label as we branched prior to the disable going in (candidate.3)
