### ISSUE TITLE
deploy_gallery-macos certificate appears to have expired

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#54017]
Build is consistently red on the `deploy_gallery-macos` shard.

https://cirrus-ci.com/task/5601766490243072

```
[17:25:04]: fastlane finished with errors
[!] Your certificate '7NT48M7VVR.cer' is not valid, please check end date and renew it if necessary
```

**Comment by digiter** [comment]
This is duplicated of https://github.com/flutter/flutter/issues/54016
