### ISSUE TITLE
iframe consumes pointer events from widgets appearing on top

### ISSUE THREAD

**Issue by AngusPei** [flutter/flutter#54027]
## Steps to Reproduce

```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  // ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory('someViewType', (int viewId) {
    final wrapper = DivElement();
    final div = IFrameElement()
        ..width = '640'
        ..height = '360'
        ..src = 'https://www.youtube.com/embed/IyFZznAk69U'
        ..style.border = 'none';
    wrapper.append(div);
    return wrapper;
  });
 
  runApp(MaterialApp(home: HomeScreen()));
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(child: Container(color:Colors.yellow, child: RaisedButton(
      onPressed:()=>debugPrint("123123")
      ))),
      body:  SizedBox(
      width: 640,
      height: 360,
      child: HtmlWidget(),
    ),
      floatingActionButton: Builder(builder: (context) {
        return FloatingActionButton(
          child: Icon(Icons.menu, color: Colors.white),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      }),
    );
  }
}

class HtmlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'someViewType');
  }
}

class HtmlHelloWorldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'hello-world-html');
  }
}
```

**Actual results:** 
![image](https://user-images.githubusercontent.com/4378435/78465789-8d3be300-772c-11ea-8ae2-7ad7846786d2.png)

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.16.4-pre.50, on Mac OS X 10.15.4 19E266, locale
    zh-Hans-US)
    • Flutter version 1.16.4-pre.50 at /Users/angus/flutter
    • Framework revision d14a301e41 (4 days ago), 2020-03-31 19:14:22 -0400
    • Engine revision fc5b44c901
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 e8c4aed700)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by AngusPei** [comment]
I need help badly

**Comment by AngusPei** [comment]
The only solution 

```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  // ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory('someViewType', (int viewId) {
    final wrapper = DivElement()
      ..style.width = '100%'
      ..style.height = '100%';
    
    final div = DivElement()
      ..contentEditable = 'true'
      ..style.width = '100%'
      ..style.color = "red"
      ..style.backgroundColor = 'red'
      ..style.height = '100%';
    wrapper.append(div);
    return wrapper;
  });

  runApp(MaterialApp(home: HomeScreen()));
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(
          child: Container(
              color: Colors.yellow,
              child: RaisedButton(onPressed: () => debugPrint("123123")))),
      body: SizedBox(
        width: 640,
        height: 360,
        child: HtmlWidget(),
      ),
      floatingActionButton: Builder(builder: (context) {
        return FloatingActionButton(
          child: Icon(Icons.menu, color: Colors.white),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      }),
    );
  }
}

class HtmlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'someViewType');
  }
}

```

**Comment by iapicca** [comment]
Hi @AngusPei 
I tested with the current latest master the code from your last post 

[screenshot](https://user-images.githubusercontent.com/45637986/78551235-0a8b5480-780e-11ea-8434-005a7d60f48a.png)

logs where clean building, but got some exception running

```bash
[ +295 ms] Debug service listening on ws://127.0.0.1:51731/e09Z_3mhTT0=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+1291 ms] ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════

[  +11 ms] The following StateError was thrown during a platform message response callback:

[        ] Bad state: Future already completed

[   +1 ms] When the exception was thrown, this was the stack:

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49  throw_

[        ] dart-sdk/lib/async/future_impl.dart 42:79                                     complete

[        ] packages/flutter/src/services/binding.dart 177:18                             <fn>

[        ] dart-sdk/lib/async/zone.dart 1374:10                                          runUnaryGuarded

[        ] lib/_engine/engine/window.dart 331:23                                         <fn>

[        ] lib/_engine/engine/window.dart 488:17                                         <fn>

[        ] dart-sdk/lib/async/zone.dart 1439:54                                          runUnary

[        ] dart-sdk/lib/async/future_impl.dart 141:18                                    handleValue

[        ] dart-sdk/lib/async/future_impl.dart 682:44                                    handleValueCallback

[        ] dart-sdk/lib/async/future_impl.dart 711:32                                    _propagateToListeners

[   +7 ms] dart-sdk/lib/async/future_impl.dart 516:7                                     [_complete]

[        ] dart-sdk/lib/async/future.dart 315:15                                         <fn>

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 50:19       internalCallback

[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

[+164919 ms] Application finished.
[  +54 ms] Stopped debug service on ws://127.0.0.1:51731

[  +34 ms] Failed to clean up temp directory: /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.wBGvDs
[   +1 ms] "flutter run" took 216,764ms.
```

```console
[✓] Flutter (Channel master, v1.18.1-pre.15, on Mac OS X 10.15.4 19E266, locale en-EE)
    • Flutter version 1.18.1-pre.15 at /Users/nevercode/development/flutter_master
    • Framework revision 17079f26b5 (6 hours ago), 2020-04-06 01:21:01 -0400
    • Engine revision 9b8dcc7ecf
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 05103dfe5a)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by AngusPei** [comment]
@iapicca 
There is no problem with the current version
![image](https://user-images.githubusercontent.com/4378435/78552750-a2069c80-783a-11ea-8e26-550ab215d6a7.png)

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale
    zh-Hans-US)
    • Flutter version 1.18.0 at /Users/angus/flutter
    • Framework revision 14f3a36aba (2 days ago), 2020-04-03 17:06:01 -0700
    • Engine revision 09bc1fc45e
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by AngusPei** [comment]
@iapicca 1.18.0-pre.04 DIV Click invalid

**Comment by skypu3** [comment]
I also had similar issue on beta Flutter version 1.17.0, and also happened on newest master channel.
The icon button can't fire any event on Stack widget with HtmlElementView
```
class _BroadcastViewState extends State<BroadcastView> {
  @override
  void didChangeDependencies() {
    final IFrameElement iframeElement = IFrameElement();
    iframeElement.height = MediaQuery.of(context).size.height.toString();
    iframeElement.width = MediaQuery.of(context).size.width.toString();
    iframeElement.src =
        '/assets/index.html';
    iframeElement.style.border = 'none';
    iframeElement.id = 'iframe';
    // ignore:undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      BroadcastView.createViewId,
      (int viewId) => iframeElement,
    );
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView(
      viewType: BroadcastView.createViewId,
    );
  }
}
```
```
class BroadcastScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          BroadcastView("2e3a4751cc05489083db0316f44e47f5", "channel01"),
          Positioned.fill(
            child: Align(
              alignment: Alignment.bottomRight,
              child: RawMaterialButton(
                onPressed: () {
                  print('clicked');
                },
                child: new Icon(
                  Icons.live_tv,
                  color: Colors.white,
                  size: 25.0,
                ),
                shape: new CircleBorder(),
                elevation: 2.0,
                fillColor: Theme.of(context).primaryColor,
                padding: const EdgeInsets.all(15.0),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

**Comment by AngusPei** [comment]
What is the deadline?

**Comment by AngusPei** [comment]
Grade is underestimated, IFrame tags are common in web development.
In fact, I prefer to support the interaction of nested subpages through the webview_flutter plugin, so that we can use a set of source code to achieve multi-platform support.

**Comment by AngusPei** [comment]
It’s at least P3, because I don’t have an alternative solution, which is no different from a crash.

**Comment by AngusPei** [comment]
**Add dart html library, unlike Flutter.**

**Comment by yjbanov** [comment]
Added the framework label because the framework should tell the engine if there's a region on top of the iframe that should capture pointer events before iframe swallows them. I have a proposal here: https://docs.google.com/document/d/1GUAx3aqdtEoaBMTNpsS1-i59QZlwTi6vUCASbaanPCo

**Comment by yjbanov** [comment]
Bumped the priority as we're hearing this concern repeatedly (e.g. see the duplicate issue reports).

**Comment by yjbanov** [comment]
@AngusPei 

> It’s at least P3, because I don’t have an alternative solution, which is no different from a crash.

You should be able to work around the issue by putting a platform view in the drawer that covers the entire drawer (e.g. an empty `<div>` that stretches horizontally and vertically to cover all the available space). This way the platform view will intercept pointer events before they reach the iframe. As long as the interceptor platform view does not itself contain an iframe Flutter will be able to process the pointer events.

**Comment by carloshwa** [comment]
If a dialog is showing over the iframe, clicks on the dialog will also be consumed by the iframe. Also, if I have any Flutter widgets (like a `Button`) showing over an iframe, clicks on that widget will also get passed to the iframe. That workaround won't work for these cases.

**Comment by yjbanov** [comment]
@carloshwa You are correct, and we should provide a more complete fix for this. Drawers, dialogs, pop-up menus, and other widgets that are known to appear on top of other content should take precedence over iframes by default. Having said that, `Button` (as well as checkbox, text, slider, and most other widgets) is an example of a widget that typically does not appear on top, but rather pushes other widgets aside (e.g. using `Column`, `Row`, `Flex`, `Grid` and other layout). Such widgets should not be aware of iframes. Instead, a container that causes these widgets to be painted on top (e.g. a dialog) would be responsible for redirecting pointer events to the framework.

**Comment by SethKitchen** [comment]
> # Workaround
> @AngusPei
> 
> > It’s at least P3, because I don’t have an alternative solution, which is no different from a crash.
> 
> You should be able to work around the issue by putting a platform view in the drawer that covers the entire drawer (e.g. an empty `<div>` that stretches horizontally and vertically to cover all the available space). This way the platform view will intercept pointer events before they reach the iframe. As long as the interceptor platform view does not itself contain an iframe Flutter will be able to process the pointer events.

Can you give a code example -- I don't follow

**Comment by geriby23** [comment]
Is there any update regarding this issue?

**Comment by adnandogar** [comment]
Just because of this issue, We have to switch complete app to native web framework.
iframe overlap preload navigation drawer and that becomes unresponsive.

any idea if any js code trick can we use inside targeted iframe server to rearrange stack?

**Comment by carloshwa** [comment]
Is this being worked on? This bug makes Google Maps integration in a web app largely unusable.

**Comment by ditman** [comment]
I'm currently working in a new widget that can be used to wrap interactive elements that are going to end up on top of an HtmlViewElement to prevent clicks from "going through".

This is probably a sufficient workaround until the framework supports this natively. If you have a `RaisedButton(...)` Stacked on top of a video player / iframe, you can replace it by:

```dart
MouseClickBoundary(
  clickable: true,
  child: RaisedButton(...),
),
```

and it should work as expected! (Clicks being handled by the RaisedButton, and not passed through to the video player / iframe underneath.

**Comment by joaquini** [comment]
> I'm currently working in a new widget that can be used to wrap interactive elements that are going to end up on top of an HtmlViewElement to prevent clicks from "going through".
> 
> This is probably a sufficient workaround until the framework supports this natively. If you have a `RaisedButton(...)` Stacked on top of a video player / iframe, you can replace it by:
> 
> ```dart
> MouseClickBoundary(
>   clickable: true,
>   child: RaisedButton(...),
> ),
> ```
> 
> and it should work as expected! (Clicks being handled by the RaisedButton, and not passed through to the video player / iframe underneath.

@ditman is that widget available somewhere? 😯

**Comment by ditman** [comment]
> @ditman is that widget available somewhere? 😯

@joaquini while doing an example for it, I stumbled upon issue #71888, so I had to stop and try to find a minimal repro which took a while. I'll push what I have to my repo so the widget can be used from a git dependency until it lands in pub.dev!

**Comment by ditman** [comment]
I've pushed my changes here:

https://github.com/ditman/flutter-packages/tree/web-click-boundary/packages/web_mouse_click_boundary

It might be depended on like so:

```yaml
web_mouse_click_boundary:
  git:
    git: https://github.com/ditman/flutter-packages.git
    ref: web-click-boundary
    path: packages/web_mouse_click_boundary
```

(Check the example for the usage)

All feedback is welcome, I'll try to write some tests for it next!

**Comment by carloshwa** [comment]
@ditman Thanks for the work on this! One use case that still affects me is scroll gesture events get passed to the underlying iframe.

Example:
My app has a Google Maps widget, and a Nav Drawer open over it. If I scroll the list in the drawer using my touchpad's scroll gesture, it also zooms in / out the underlying Google Map.

**Comment by ditman** [comment]
@carloshwa have you used the widget above as the root element of your drawer? I have to say, so far I've only tested click events. Scroll events may be handled differently :/

**Comment by carloshwa** [comment]
@ditman That actually worked! I wasn't sure where to put the widget to make it work with the drawer.

Next case I'm having trouble with is `PopupMenuButton`. If I wrap it with `MouseClickBoundary`, the button itself does not pass events to the iframe, but when the popup menu is open, clicks on the menu do get passed through.

**Comment by daveMcelf** [comment]
@ditman thank you. I tried wrapping that over Horizontal Listview and that work really well, so I guess scrolling is also fine.

**Comment by chunhunghan** [comment]
@ditman, it works really well. Thank you very much.

code snippet

	 drawer: MouseClickBoundary(
			clickable: true,
			child: Drawer(
			  child: ListView(
			  
	 ...
	 floatingActionButton: MouseClickBoundary(
			clickable: true,
			child: FloatingActionButton( 

full code

	import 'package:flutter/material.dart';
	import 'dart:ui' as ui;
	import 'dart:html' as html;
	import 'package:web_mouse_click_boundary/web_mouse_click_boundary.dart';

	void main() {
	  runApp(MyApp());
	}

	class MyApp extends StatelessWidget {
	  @override
	  Widget build(BuildContext context) {
		return MaterialApp(
		  title: 'Flutter Demo',
		  home: MyHomePage(),
		);
	  }
	}

	class MyHomePage extends StatefulWidget {
	  @override
	  _MyHomePageState createState() => _MyHomePageState();
	}

	class _MyHomePageState extends State<MyHomePage> {
	  bool _isDrawerOpen = false;
	  double _drawerWidth = 304.0;

	  @override
	  Widget build(BuildContext context) {
		return Scaffold(
		  appBar: AppBar(
			title: Text("Drawer Example"),
		  ),
		  drawer: MouseClickBoundary(
			clickable: true,
			child: Drawer(
			  child: ListView(
				padding: EdgeInsets.zero,
				children: <Widget>[
				  DrawerHeader(
					child: Text('Drawer Header'),
					decoration: BoxDecoration(
					  color: Colors.blue,
					),
				  ),
				  ListTile(
					title: Text('Item 1'),
					onTap: () {
					  print("click");
					},
				  ),
				  ListTile(
					title: Text('Item 2'),
					onTap: () {
					  print("click");
					},
				  ),
				],
			  ),
			),
		  ),
		  body: Iframe(),
		  floatingActionButton: MouseClickBoundary(
			clickable: true,
			child: FloatingActionButton(
			  onPressed: () {
				print("click");
			  },
			  tooltip: 'Increment',
			  child: Icon(Icons.add),
			),
		  ),
		);
	  }
	}

	class Iframe extends StatelessWidget {
	  Iframe() {
		// ignore: undefined_prefixed_name
		ui.platformViewRegistry.registerViewFactory('iframe', (int viewId) {
		  var iframe = html.IFrameElement();
		  iframe.src = 'https://flutter.dev';
		  return iframe;
		});
	  }
	  @override
	  Widget build(BuildContext context) {
		return Container(
			width: MediaQuery.of(context).size.width,
			height: MediaQuery.of(context).size.height,
			child: HtmlElementView(viewType: 'iframe'));
	  }
	}

	class SecondRoute extends StatelessWidget {
	  @override
	  Widget build(BuildContext context) {
		return Scaffold(
			appBar: AppBar(
			  title: Text("route test"),
			),
			body: Text("SecondRoute"));
	  }
	}

**Comment by ditman** [comment]
@carloshwa Maybe my code does not behave properly in all cases, as you can see it's pretty "generic". For some specific problems, I think it'd be best that we create a separate issue where you can share some snippets of code where the issue is reproducible (without a full app).

I'll try to have this reviewed and merged ASAP, I'm writing some tests for it.

(For everybody, there's a "debug" parameter that should make the boundary visible (red, with 50% opacity), I find it useful when used as the background of a layout element, to see what's really covered/not covered, in buttons, not so much because often the boundary is exactly the same size as the button!)

**Comment by carloshwa** [comment]
This is great progress so far, thanks @ditman !

**Comment by ditman** [comment]
We've just discovered a bug in the flutter web engine that will make the "clickable" property obsolete; I'll remove it from the codebase soon.

**Comment by ditman** [comment]
The fix mentioned above has rolled to flutter master, so I have removed the "clickable" property from the widget.

The framework should be smart enough to handle the mouse cursor properly. Remember that you can set the cursor property on your HtmlElementViews manually, if needed, like so:

```dart
html.Element htmlElement = html.VideoElement()
  ...
  ..style.cursor = 'auto'
  ...;
```

**Comment by ditman** [comment]
As suggested by a teammate, I've renamed the widget to `PointerInterceptor`, and changed it's package name; here's the new pubspec.yaml config:

```
web_pointer_interceptor:
  git:
    git: https://github.com/ditman/flutter-packages.git
    ref: web-click-boundary
    path: packages/web_pointer_interceptor
```

**Comment by ditman** [comment]
This is now a package: https://pub.dev/packages/pointer_interceptor

Thanks everybody for the feedback, I'm closing this issue.

**Comment by DannyJoinedApps** [comment]
@ditman Do you currently own a house? Can I buy you a house? Maybe a private jet? This is the best package any one has ever made for any language in any universe. Its more helpful to the world than the corona virus vaccine, it sings better than pavarotti, Darwin's book's contained less useful info and it's influence will make einstein look like an idiot.

Seriously. It works and the bug has been making me look useless and this works, and it works, and the bug was terrible and this fixes it, and it works.

**Comment by ditman** [comment]
LOL thanks @DannyJoinedApps, you made my day :P

**Comment by ThalapathySiva** [comment]
@ditman  Hi, first of all thanks for that wonderful package, I am facing some issue, I have 3 HTMLElement view in a screen, and above having DropDownButton the first issue if i wrap PointerInterceptor with dropdown its not working, and then i wrapped PointerInterceptor with child of the DropDownMenuItem there it works as excepted, so the second issue is if i have enabled only one html view its working smoothly if i have enabled all the three views, then i open the dropdown, the page got blinking continuously any idea about this ?

**Comment by ditman** [comment]
@ThalapathySiva thanks for the kind words!

It is hard to diagnose an issue just with a few descriptions of a sentence, but it might be related to this:

https://github.com/flutter/flutter/issues/71888

Can you confirm it looks similar (and follow #71888) for updates?

**Comment by ThalapathySiva** [comment]
@ditman  Thanks for reply, I think its kinda related to that, here i will attach mine.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/35165669/110890584-5136d800-8316-11eb-8ea9-0204d8cafdc9.gif)

I have added Pointer Interceptor for dropdownItem text so its just behaving like this even though i didn't hover my mouse. And in my console i am keep on getting  "Flutter: restoring WebGL context".

**Comment by ditman** [comment]
@ThalapathySiva a quick workaround may be to attempt to build/run your app with `--web-renderer html` command-line option? It may flicker less.

The flickering that people usually report in flutter web is that HtmlElementViews "reload" (if they contain an iframe, or a text editor, or a video player or similar), not the surrounding flutter UI.

The flickering that you're seeing here, however, looks like a new bug. If you can provide a small example app that displays the problems that you're seeing, we'd appreciate a new bug report for the platform-web canvaskit renderer. You can [start reporting a new issue here](https://github.com/flutter/flutter/issues/new/choose)!

Thanks for reaching out!

**Comment by ThalapathySiva** [comment]
@ditman  Sure, can you have any idea about this issue  [#78294](https://github.com/flutter/flutter/issues/78294).Thank you
