### ISSUE TITLE
Outlined TextField floating label is too low

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#54028]
internal b/153030038

The floating label for the outlined TextField widget is too low and doesn't match Material design, please see https://dartpad.dev/bf25d5a76c0bc8a318d5f83ff375bbf6 for the reproduction case.

Marking as critical as it is causing the app to fail MD review.

**Comment by jibraniqbal666** [comment]
so I just read all the contributing guides anyone who can help me I wanna pick up the list issue and fix it?

**Comment by HansMuller** [comment]
In the image below Flutter's input field is on the left, and the illustration from https://material.io/components/text-fields is on the right. It's clear that the label is a little too low relatively to the outline.

![label_offset](https://user-images.githubusercontent.com/1377460/78614224-dbcba900-7822-11ea-991a-aa3ebad93259.png)

Adjusting where the floating label's origin goes a little appears to fix the problem. I've added the red horizontal line to make it clearer that the widget and the spec are laid out in the same way:

![updated](https://user-images.githubusercontent.com/1377460/78615947-af665b80-7827-11ea-9d06-ca8780aaf007.png)

Unfortunately, this change is likely to break many golden image tests. Will check to see what the damage would be now.

**Comment by HansMuller** [comment]
Not surprisingly, this change breaks 100s of golden image tests.
