### ISSUE TITLE
Cannot Build after upgrading

### ISSUE THREAD

**Issue by wilson0506** [flutter/flutter#54031]
Has followed the migration, but still cannot build for ios. Tried google and all methods not help fixing the issue.

CodeSign /Users/myUser/flutterApp/flutterExample/flutterExample/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
    cd /Users/myUser/flutterApp/flutterExample/flutterExample/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/myUser/flutterApp/flutterExample/flutterExample/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp=none /Users/myUser/flutterApp/flutterExample/flutterExample/build/ios/Debug-iphonesimulator/Runner.app

/Users/myUser/flutterApp/flutterExample/flutterExample/build/ios/Debug-iphonesimulator/Runner.app: resource fork, Finder information, or similar detritus not allowed
Command CodeSign failed with a nonzero exit code

https://flutter.dev/docs/development/ios-project-migration

XCode Version: 11.4 for IOS 13.4
Flutter Doctor:
flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-HK)
    • Flutter version 1.12.13+hotfix.9 at /Users/myuser/flutter
    • Framework revision f139b11009 (5 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/myuser/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/myuser/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • 6BB233AA-74B3-44F7-90FF-93984A2F73FB • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.

**Comment by aditya305** [comment]
for the android toolchain issue 
refer this 
[robbinespu.gitlab.io/blog/2020/03/03/flutter-issue-fixed-android-license-status-unknown-on-windows/](url)

**Comment by aditya305** [comment]
first, check the code then try shifting to flutter channel to beta the run project.

**Comment by TahaTesser** [comment]
Hi @wilson0506 
Please take a look at this [comment](https://github.com/flutter/flutter/issues/28077#issuecomment-464464228)

As the comment suggest,  it's not a Flutter issue
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
