### ISSUE TITLE
android cmdlines-tools

### ISSUE THREAD

**Issue by Kaushik699** [flutter/flutter#54033]
In latest android studio cmdlines-tools package is present and last one has android sdk tools package.

**Comment by codermihirpaldhikar** [comment]
@Kaushik699 can you please elaborate on your issue?

**Comment by iapicca** [comment]
Hi @Kaushik699 
I'm not sure what you are describing is an issue with flutter 
or a feature request.

Please describe in details the issue or the proposal.
Thank you

**Comment by Kaushik699** [comment]
@codermihirpadhikar I'm using flutter without android studio. At the time of the flutter doctor command it showing errors as 
**Android sdkmanager tool not found (C:\Android\tools\bin\sdkmanager). Try re-installing or updating your Android SDK, visit https://flutter.dev/setup/#android-setup for detailed instructions.**
I refer this documentation:-
**https://medium.com/@quicky316/install-flutter-sdk-on-windows-without-android-studio-102fdf567ce4**

**Comment by codermihirpaldhikar** [comment]
@Kaushik699 for developing the apps for android, you need to install Android SDK which comes with the Android Studio. You need to install Android Studio.

Check this out:
https://flutter.dev/docs/get-started/install/windows#install-android-studio

Let me know if you have any problems

**Comment by TahaTesser** [comment]
Hi @Kaushik699 
Please follow this [Windows install
](https://flutter.dev/docs/get-started/install/windows) guide?
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
