### ISSUE TITLE
Gallery's launcher icon on iOS needs more padding around edges

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5404]
Looking at the rest of the iOS launcher icons, it appears that the Flutter launcher icon for iOS is too close to the edge.

I found a template here with the grid: https://appicontemplate.com/ios7/ and another here: http://www.pixelmatortemplates.com/template/freebie-ios7-app-icon-grid-system-0/ and https://designcode.io/iosdesign-guidelines (scroll down to App Icons)

From https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/ :

```
iPhone 6s Plus, iPhone 6 Plus	180px by 180px
iPhone 6s, iPhone 6, iPhone SE	120px by 120px
iPad Pro	167px by 167px
iPad, iPad mini	152px by 152px
```

The large icon is used by the App Store.

```
Large Icon Size	1024px by 1024px
```

See also scaling factors: https://developer.apple.com/ios/human-interface-guidelines/graphics/image-size-and-resolution/

Here's an array of launcher icons. You can see the Flutter launcher icon is very close to the edges, compared to the rest of the icons.

![screen shot 2016-08-15 at 12 04 24 pm](https://cloud.githubusercontent.com/assets/5479/17675868/8a42757e-62e0-11e6-91bb-682dced0c7f4.png)

**Comment by eseidelGoogle** [comment]
I just used https://github.com/flutter/identity-assets/tree/master/assets/logo_square.  Would be easy to add some padding in Preview.app. :)

**Comment by sethladd** [comment]
New icons: https://github.com/flutter/identity-assets/tree/master/assets/Flutter-Launcher-Icons/ios
