### ISSUE TITLE
It appears that the downloaded file is corrupt; please try again. 

### ISSUE THREAD

**Issue by lucas404x** [flutter/flutter#54054]
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200M  100  200M    0     0   498k      0  0:06:52  0:06:52 --:--:--  516k
/opt/flutter/bin/internal/update_dart_sdk.sh: line 86: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by TahaTesser** [comment]
Hi @lucas404x 
can you please provide your `flutter doctor -v'?
Make sure you have proper internet connection and try again
Thank you

**Comment by lucas404x** [comment]
Hi @TahaTesser

I solved :)

I used this article for to solve: [https://flutter.dev/community/china](URL)

(I'm sorry my English)
