### ISSUE TITLE
Flutter tool fails to properly reinitialize itself

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#5406]
flutter$ git clean -fdx
flutter$ cd examples/flutter_gallery
flutter/examples/flutter_gallery$ flutter run

```
Downloading Dart SDK 1.19.0-dev.5.0...
######################################################################## 100.0%
Building flutter tool...
Running 'pub get' in flutter_gallery...                  
Could not find package sky_engine at "../../bin/cache/pkg/sky_engine".
Depended on by:
- flutter 0.0.21 
```

**Comment by eseidelGoogle** [comment]
`flutter upgrade` will solve this.  But this has come up before.  @abarth was walking someone through this in the gitter the other day.

**Comment by Hixie** [comment]
`flutter doctor` is all you need to fix that one

**Comment by Hixie** [comment]
This is the same as https://github.com/flutter/flutter/issues/5269
