### ISSUE TITLE
Nothing happens after clinking the gmail account in pop up window

### ISSUE THREAD

**Issue by pjjy** [flutter/flutter#54068]
Nothing happens after clinking the gmail account in pop up window. After i click the gmail account in a pop up window nothing happens.

**Comment by TahaTesser** [comment]
Hi @pjjy 
Are you referring `google_sign_in` package?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by pjjy** [comment]
![Screenshot_20200406-155104_Google_Play_services 1](https://user-images.githubusercontent.com/56106322/78535429-59d58300-7816-11ea-9556-53e9922c3610.jpg)
it took couple of minutes loading like in the picture

**Comment by TahaTesser** [comment]
Hi @pjjy 
Make sure you've proper internet connection speed
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @pjjy 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
