### ISSUE TITLE
Snapshot data of FutureBuilder is always null (doesn't show any error)

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#54061]
## Steps to Reproduce
1. 
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(
        child: FutureBuilder<List<int>>(
          future: _getList(),
          builder: (context, snapshot) {
            print(snapshot.connectionState);
            print(snapshot.data?.length);
            return Container();
          },
        ),
      ),
    );
  }

  Future<List<int>> _getList() async {
    return [0, 1, 2].map((e) => e - 1)/*.toList()*/;
  }
}
```
2.
`flutter run`

**Expected results:** 
I/flutter ( 8316): ConnectionState.waiting
I/flutter ( 8316): null
I/flutter ( 8316): ConnectionState.done
I/flutter ( 8316): 3

**Actual results:** 
I/flutter ( 8316): ConnectionState.waiting
I/flutter ( 8316): null
I/flutter ( 8316): ConnectionState.done
I/flutter ( 8316): null

## Details
Flutter doesn't show any error about Iterable being returned instead of List, analyzer also doesn't show any warnings. I found the problem after hours of debugging. Adding a simple toList solves the problem.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by MohiuddinM** [comment]
@jonahwilliams this is not a question. It is a bug where FutureBuilder fails without providing any error
