### ISSUE TITLE
Block's scrollableKey parameter is a leaky abstraction.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5407]
While I understand why you'd want this parameter I feel like there must be a better way to do this than through an extra parameter to Block.

Perhaps a function on Block's state (if it has one)?  Or on the Block itself (seems less ideal)?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/5281 will make this moot.

**Comment by abarth** [comment]
Fixed.  ListView and friends now take a ScrollController, which is a non-leaky abstraction for controlling the scroll offset.
