### ISSUE TITLE
Checking Dart SDK version and BITS service failed, retrying with WebRequest

### ISSUE THREAD

**Issue by smamran** [flutter/flutter#54078]
Flutter Doctor fails Checking and Downloading dart sdk using BITS Service and WebRequest
![image](https://user-images.githubusercontent.com/2453604/78543246-37456900-781a-11ea-90b7-bc98a7b1bf51.png)

**Comment by TahaTesser** [comment]
Hi @smamran 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by smamran** [comment]
![image](https://user-images.githubusercontent.com/2453604/78555420-ce1c2080-782e-11ea-8526-aa5effe958dc.png)

**Comment by TahaTesser** [comment]
Hi @smamran 
Please take a look at this [comment](https://github.com/flutter/flutter/issues/27276#issuecomment-458830351) 
Thank you

**Comment by smamran** [comment]
I also tried solution given [here.](https://github.com/flutter/flutter/issues/27276#issuecomment-458830351) but nothing happened.

**Comment by iapicca** [comment]
Hi @smamran 
could you please double check that the [system requirements](https://flutter.dev/docs/get-started/install/windows#system-requirements) are met?
Thank you

**Comment by smamran** [comment]
[System Requirements met.](https://flutter.dev/docs/get-started/install/windows#system-requirements)

PS C:\Users\amran> (Get-Host).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752

PS C:\Users\amran> git --version
git version 2.26.0.windows.1

**Comment by shahriarz** [comment]
Windows 10, 64 bit.
D:\flutter\bin

But unable to run flutter doctor...
![Screenshot_1](https://user-images.githubusercontent.com/45015223/80160302-16895b80-85ef-11ea-8d51-090962c33cfa.png)

**Comment by smamran** [comment]
https://storage.googleapis.com can't be reached from bangladesh. I solved this issue using a vpn.
https://protonvpn.com/

**Comment by shahriarz** [comment]
> https://storage.googleapis.com can't be reached from bangladesh. I solved this issue using a vpn.
> https://protonvpn.com/

thanks! though the BITS service failed, it worked with webRequest. anyway, do you have any idea why googleapis cannot be reached from bangladesh?

**Comment by cyberlobster** [comment]
same in Iran!
I had to use a vpn to fix this issue,too.

**Comment by NahiyanBasmeh** [comment]
Using VPN solved my problem as well.
