### ISSUE TITLE
App with MDM (mobile device management) is showing black screen when screen capture restriction is enabled

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#54084]
I am new to flutter app development. I have developed a WebView (webview_flutter) app. It is in corporate level, so we have deployed the app into play store with MDM (mobile device management). The MDM has screen capturing restriction rule. When i open the app, mobile screen is showing with black color.

**Comment by VladyslavBondarenko** [comment]
Hi @csk544 
could you provide your `flutter doctor -v`?
do you mean you can see black screen before the first screen appears?
are you experiencing this with different devices?

**Comment by csk544** [comment]
Hi @VladyslavBondarenko 

Thank you for your response. 

The application is running, but everything behind the black screen. When i randomly touch on the mobile screen, based on the elements present on the screen, events are triggering like: Keyboard appearing, button click actions etc..
We are experiencing the same behavior in different devices.

The application is working fine with connected device and public play store. If there is a screen capture restriction enabled in the MDM then the black screen is displaying.

**Comment by VladyslavBondarenko** [comment]
@csk544 
what MDM do you use?
is it happening with Android or iOS or both platforms?

**Comment by csk544** [comment]
@VladyslavBondarenko 
We are using VMWare Airwatch MDM. It is happening for both Android and IOS.

**Comment by VladyslavBondarenko** [comment]
@csk544 
could you try does `screen capture restriction` from MDM works properly with native apps, created not via flutter?

**Comment by csk544** [comment]
@VladyslavBondarenko 
Yes, I have verified with both Android native and React native apps, and they are working fine with screen capture restrictions.

**Comment by hoseyneil** [comment]
Was there any resolution for this?

**Comment by jonahwilliams** [comment]
Without any repro there was no way for us to fix this.
