### ISSUE TITLE
Keyboard doesn't work in --hot reload mode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5408]
@johnmccutchan 

Steps to reproduce:
* flutter gallery, "text fields" demo, tap a field. In --hot you get nothing. In normal mode you get a keyboard.

The failure is we're hitting is `impl == null` and `!ctrl.isBound` in `KeyboardProxy.show()` in the mojom.

**Comment by johnmccutchan** [comment]
https://github.com/flutter/engine/pull/2944 fixes Android

**Comment by johnmccutchan** [comment]
https://github.com/flutter/engine/pull/2949 fixes iOS
