### ISSUE TITLE
analyzer_benchmark mega_gallery_watch_maximum regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54094]
Looks like it's slowly inching up. First may be around https://github.com/flutter/engine/pull/17445, but it's hard to tell.
![Screen Shot 2020-04-06 at 7 55 56 AM](https://user-images.githubusercontent.com/1435716/78572249-12ca9c00-77dc-11ea-88c3-aadb6822723c.png)

**Comment by tvolkert** [comment]
Looks like it was likely https://github.com/flutter/flutter/pull/53467.  I'll rebaseline.
