### ISSUE TITLE
Deprecate force_luci_builders.sh and support re-triggering builds from cocoon

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#54107]
Right now the [`force_luci_builders.sh`](https://github.com/flutter/engine/blob/master/tools/luci/force_luci_build.sh) script will trigger the engine builders for the prod group, but hotfix branches use a seperate builder group. We should deprecate this script and instead support triggering manual LUCI builds from cocoon.

**Comment by digiter** [comment]
Triage: let's deprecate force_luci_builders and put the functionality to LUCI dashboard.

**Comment by christopherfujino** [comment]
@digiter sgtm, shall I update this issue to track that?

**Comment by digiter** [comment]
Yes, please.

**Comment by godofredoc** [comment]
The file does not exist anymore.
