### ISSUE TITLE
Nearly all web_benchmarks_html benchmarks have regressed

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54101]
Clear regression around https://github.com/flutter/flutter/pull/53969. Looks like an issue with the tests; can we rebaseline?

![Screen Shot 2020-04-06 at 8 49 20 AM](https://user-images.githubusercontent.com/1435716/78577848-8b812680-77e3-11ea-9d7d-34460693cc1e.png)

**Comment by yjbanov** [comment]
I removed the TODAY label. We've been tweaking the benchmark harness. It is highly unlikely to be a real regression.

**Comment by yjbanov** [comment]
#54122 didn't work. Reopened.
