### ISSUE TITLE
platform_views_scroll_perf_ios__timeline_summary average_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54100]
Difficult to find a specific culprit, as it's noisy and creeping up. Perhaps around https://github.com/flutter/flutter/pull/53538?

![Screen Shot 2020-04-06 at 8 43 39 AM](https://user-images.githubusercontent.com/1435716/78577308-bcad2700-77e2-11ea-9c66-44e2dc09eb3e.png)

**Comment by blasten** [comment]
I just re-baselined this benchmark to account for the noise.
