### ISSUE TITLE
Easy to build but complex raster frames produce stale app state

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#54117]
The current rasterizer pipeline implementation limits the throughput of UI thread. We have a fixed pipeline depth and UI thread stops producing frames when we have reached the said depth. This results in increased lag.

More information at go/flutter-pipeline-improvements

**Comment by iskakaushik** [comment]
I'm working on producing an example application that will highlight this issue.

**Comment by zanderso** [comment]
It looks like https://github.com/flutter/engine/pull/18901 was reverted. Is this also blocked on https://github.com/flutter/flutter/issues/27609 ?

**Comment by iskakaushik** [comment]
@zanderso yup. I've also pushed the milestone so I can land this slightly risky change after 1.21.

**Comment by liyuqian** [comment]
@iskakaushik : is this still on track of an October milestone?

**Comment by liyuqian** [comment]
Ping from performance triage... @iskakaushik November is coming, any update to the milestone or other aspects of this issue?

**Comment by zanderso** [comment]
This issue has a more up-to-date treatment in the work items for Impeller. Closing as obsolete.
