### ISSUE TITLE
[Flutter module in iOS app] Building for iOS Simulator, but the linked and embedded framework 'App.framework' was built for iOS.

### ISSUE THREAD

**Issue by mbaleczny** [flutter/flutter#54138]
## Steps to Reproduce

Similar to issue https://github.com/flutter/flutter/issues/50568 but regards flutter module imported into an existing iOS native application.

1. Create a plain single page iOS application.
2. Follow the instructions [here](https://flutter.dev/docs/development/add-to-app/ios/project-setup) for creating flutter module and importing it into the iOS app created in step 1.
3. Try to build iOS project.

When using option B with `--xcframework --no-universal` error message is `While building for iOS Simulator, no library for this platform was found in 'App.xcframework'.`

**flutter doctor -v**

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.18.0 at /Users/user/development/flutter
    • Framework revision 14f3a36aba (3 days ago), 2020-04-03 17:06:01 -0700
    • Engine revision 09bc1fc45e
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)
...
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
....
[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 9056AB1A-B0F1-4E98-8DF2-603A7FD5410A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.163
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by danspano** [comment]
Hi @mbaleczny 
Xcode 11.4 made some changes to the way frameworks are linked. New projects created with your version of flutter should support 11.4, alternatively you can try manually migrating your Xcode project using the guide here: https://flutter.dev/docs/development/ios-project-migration

I was able to manually upgrade my project using these steps and the issue was resolved.

**Comment by VladyslavBondarenko** [comment]
@mbaleczny does it help?

**Comment by aburcheri** [comment]
@danspano Should everything be removed in Other Linker Flags or should '$(inherited) -framework Flutter' be added ?

**Comment by mbaleczny** [comment]
> @mbaleczny does it help?

No, it did not. 

It looks like XCode 11.4 migration guide https://flutter.dev/docs/development/ios-project-migration is for flutter project, not flutter module. Tried to make use of it as much as possible, though.

Did anybody follow steps to reproduce?

**Comment by danspano** [comment]
> @danspano Should everything be removed in Other Linker Flags or should '$(inherited) -framework Flutter' be added ?

@aburcheri you may have other existing linker flags. It's fine to leave these, just make sure '$(inherited) -framework Flutter' are in the list. I already had these in my linker flags along with some others, so I didn't need to add them again.

**Comment by DTrafford** [comment]
> Hi @mbaleczny
> Xcode 11.4 made some changes to the way frameworks are linked. New projects created with your version of flutter should support 11.4, alternatively you can try manually migrating your Xcode project using the guide here: https://flutter.dev/docs/development/ios-project-migration
> 
> I was able to manually upgrade my project using these steps and the issue was resolved.

This worked for me

**Comment by minhthong095** [comment]
i used `flutter build ios-framework` and met similar issue.

**Comment by mbaleczny** [comment]
I solved my issue. It was quite simple - I followed the tip instruction on the bottom of the section [Embed the frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks) 🤦 
I created PR to flutter website repo with minor changes so the solution to this will be more obvious for others.

@minhthong095 I can see that you don't have CocoaPods installed. Try to run `sudo gem install cocoapods` in the `<project_dir>/.ios` or `<project_dir>/ios/` (if it's a flutter module project or regular flutter project respectively).

If this helps you I think we can close this issue. 
Thank you, everyone!

**Comment by DTrafford** [comment]
> I solved my issue. It was quite simple - I followed the tip instruction on the bottom of the section [Embed the frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks) 🤦
> I created PR to flutter website repo with minor changes so the solution to this will be more obvious for others.
> 
> @minhthong095 I can see that you don't have CocoaPods installed. Try to run `sudo gem install cocoapods` in the `<project_dir>/.ios` or `<project_dir>/ios/` (if it's a flutter module project or regular flutter project respectively).
> 
> If this helps you I think we can close this issue.
> Thank you, everyone!

Just to be 100% clear, running install cocoa pods in the project directory will fix the need to follow the guide:

https://flutter.dev/docs/development/ios-project-migration

And it should run fine automatically?

**Comment by mbaleczny** [comment]
No. Please, see my updated answer above. 
I was referring to @minhthong095 's issue. 

Again, the solution to my issue is the following tip on the bottom of the section [Embed the frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks). The reason why it works is that iOS Simulator needs Debug version of the Flutter framework.

**Comment by VladyslavBondarenko** [comment]
@mbaleczny 
I'm glad that it's solved,
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
