### ISSUE TITLE
[flutter pub upgrade]  Git error. Command: git rev-list --max-count=1 android-x                

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#54166]
I've been using flutter for many months but not in the last few weeks.
Today when I returned to it I wanted to do a flutter pub upgrade.

However I'm getting an error:

```shell
flutter pub upgrade
Git error. Command: git rev-list --max-count=1 android-x                
fatal: ambiguous argument 'android-x': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:                   
'git <command> [<revision>...] -- [<file>...]'                          
pub upgrade failed (server unavailable) -- attempting retry 1 in 1 second...
```

I've eventually tracked this down to a dependency that was using a git ref: dependency. 
The ref: had been deleted from the git project.

The problem was that flutter pub upgrade gave me no hint that it was a problem with package. I assumed it was a problem with flutter.

So we need to improve errors when pulling packages so that at the very least the fact that it was a problem pulling a package and then which package caused the problem will make this type of error easier to diagnose.

I've spent a chunk of the morning trying to pull this problem apart.

**Comment by TahaTesser** [comment]
Hi @bsutton 
Could you please provide your `flutter doctor -v`?
Thank you

**Comment by TahaTesser** [comment]
Could be related [#54166](https://github.com/flutter/flutter/issues/54166)

**Comment by bsutton** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/bsutton/apps/flutter
    • Framework revision f139b11009 (7 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bsutton/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bsutton/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/bsutton/apps/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by jmagman** [comment]
Please re-file this issue with [pub](https://github.com/dart-lang/pub/issues). Flutter tooling doesn't have any control of that message.  See https://github.com/dart-lang/pub/blob/72686563e767f8a359e48a267a2c323953a6a0ef/lib/src/git.dart#L31.

**Comment by bsutton** [comment]
submitted here: 
https://github.com/dart-lang/pub/issues/2441
