### ISSUE TITLE
IconData icon preview broken on VS Code

### ISSUE THREAD

**Issue by Srini-B** [flutter/flutter#54162]
Hi, I'm using stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720] and VS Code (version 1.43.2). The IntelliSense preview of icons has a broken image. I tried using the beta channel v1.15.17. both have the same problem. preview works fine on android studio tho

![1](https://user-images.githubusercontent.com/22414119/78625776-9783eb80-78aa-11ea-88cf-5470bb23a890.png)
![2](https://user-images.githubusercontent.com/22414119/78625782-994daf00-78aa-11ea-9bad-fe1709e38033.png)

**Comment by TahaTesser** [comment]
Hi @Srini-B 
This is VS Code extension, not an issue with Flutter itself
Please raise your issue on their [GitHub](https://github.com/Dart-Code/Dart-Code/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by tapizquent** [comment]
@Srini-B Did you end up opening an issue with VSCode? I am having the same issue.

**Comment by Srini-B** [comment]
Just update your dart plugin on VSCode to v3.9.1. 
ref: [link](https://github.com/Dart-Code/Dart-Code/issues/2333#issuecomment-609642035)
