### ISSUE TITLE
Flutter needs to help developers list of supported/unsupported phones/gpus

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5416]
Currently we don't provide developers with a list of supported hardware they can configure their Android and iOS store listings with.

The closest we have is:
https://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on

Much of this will be based on what GPUs we know flutter can run well on.  For that we will likely need some help from Skia.

**Comment by eseidelGoogle** [comment]
My understanding is @chinmaygarde is willing to take a stab at creating an initial file.  The goal here is simply managing expectations.  Make it possible for us to explain to our users that X device is known to not work with Flutter.

**Comment by eseidelGoogle** [comment]
Unity appears to not actually provide an official list (and some sites complain that their Android device support is far from complete):
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=supported+devices+unity

Donno.

**Comment by Hixie** [comment]
Moving to m4 since this doesn't fit any of our current priorities.

**Comment by Hixie** [comment]
Would be nice if `flutter doctor` could recognize devices and report them as known good vs known bad, too.

**Comment by zoechi** [comment]
Related to #11402

**Comment by jonahwilliams** [comment]
we should pretty much support everything. We document things like API level on the website. Adding this to the tooling is unlikely to happen, as the existing gradle machinery will fail with min/target sdk information.
