### ISSUE TITLE
Flutter engine crashed (SIGSEGV) on GPU thread calling PlatformViewAndroid::CreateRenderingSurface()

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#54167]
It seems the engine try creating rendering surface and calling  `AndroidSurfaceGL::GLContextMakeCurrent()` but unfortunately the `onscreen_context_` was null due to `eglCreateWindowSurface` fails, see 
[shell/platform/android/android_surface_gl.cc:100](https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/android_surface_gl.cc#L100), [shell/platform/android/android_surface_gl.cc:109](https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/android_surface_gl.cc#L109), and [PlatformViewAndroid::NotifyCreated()](https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/platform_view_android.cc#L44).

backtrace:

<details>
  <summary>1.gpu SIGSEGV(SEGV_MAPERR) </summary>

<pre>
********** Crash dump: **********
#00 0x00133c3e /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
fml::RefPtr<flutter::AndroidContextGL>::operator->() const
    ../../flutter/fml/memory/ref_ptr.h:0:12
flutter::AndroidSurfaceGL::GLContextMakeCurrent()
    ../../flutter/shell/platform/android/android_surface_gl.cc:109:0
#01 0x003af65b /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
flutter::GPUSurfaceGL::GPUSurfaceGL(flutter::GPUSurfaceGLDelegate*, bool)
    ../../flutter/shell/gpu/gpu_surface_gl.cc:42:19
#02 0x00133cdb /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
std::__1::__unique_if<flutter::GPUSurfaceGL>::__unique_single std::__1::make_unique<flutter::GPUSurfaceGL, flutter::AndroidSurfaceGL*, bool>(flutter::AndroidSurfaceGL*&&, bool&&)
    ../../third_party/libcxx/include/memory:3003:32
flutter::AndroidSurfaceGL::CreateGPUSurface()
    ../../flutter/shell/platform/android/android_surface_gl.cc:59:0
#03 0x00133f15 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
non-virtual thunk to flutter::AndroidSurfaceGL::CreateGPUSurface()
    ../../flutter/shell/platform/android/android_surface_gl.cc:0:0
#04 0x0013b0b3 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
flutter::PlatformViewAndroid::CreateRenderingSurface()
    ../../flutter/shell/platform/android/platform_view_android.cc:391:28
#05 0x001681b9 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
flutter::PlatformView::NotifyCreated()::$_0::operator()() const
    ../../flutter/shell/common/platform_view.cc:73:34
decltype(std::__1::forward<flutter::PlatformView::NotifyCreated()::$_0&>(fp)()) std::__1::__invoke<flutter::PlatformView::NotifyCreated()::$_0&>(flutter::PlatformView::NotifyCreated()::$_0&)
    ../../third_party/libcxx/include/type_traits:3530:0
void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::PlatformView::NotifyCreated()::$_0&>(flutter::PlatformView::NotifyCreated()::$_0&)
    ../../third_party/libcxx/include/__functional_base:348:0
std::__1::__function::__alloc_func<flutter::PlatformView::NotifyCreated()::$_0, std::__1::allocator<flutter::PlatformView::NotifyCreated()::$_0>, void ()>::operator()()
    ../../third_party/libcxx/include/functional:1533:0
std::__1::__function::__func<flutter::PlatformView::NotifyCreated()::$_0, std::__1::allocator<flutter::PlatformView::NotifyCreated()::$_0>, void ()>::operator()()
    ../../third_party/libcxx/include/functional:1707:0
#06 0x0014678d /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
std::__1::function<void ()>::operator()() const
    ../../third_party/libcxx/include/functional:2419:12
fml::MessageLoopImpl::FlushTasks(fml::FlushType)
    ../../flutter/fml/message_loop_impl.cc:123:0
fml::MessageLoopImpl::RunExpiredTasksNow()
    ../../flutter/fml/message_loop_impl.cc:133:0
#07 0x001484c1 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
fml::MessageLoopAndroid::OnEventFired()
    ../../flutter/fml/platform/android/message_loop_android.cc:92:5
fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::operator()(int, int, void*) const
    ../../flutter/fml/platform/android/message_loop_android.cc:42:0
fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::__invoke(int, int, void*)
    ../../flutter/fml/platform/android/message_loop_android.cc:40:0
#08 0x0000fccd /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+632) [armeabi-v7a::3ce239b524f0fec8f8496e47d7358de4]
#09 0x0000f9d3 /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26) [armeabi-v7a::3ce239b524f0fec8f8496e47d7358de4]
#10 0x0000c6b5 /system/lib/libandroid.so (ALooper_pollOnce+56) [armeabi-v7a::477cea91c9479647f5eddb27bbf07189]
#11 0x00148599 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
fml::MessageLoopAndroid::Run()
    ../../flutter/fml/platform/android/message_loop_android.cc:68:18
#12 0x00145b17 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
fml::MessageLoopImpl::DoRun()
    ../../flutter/fml/message_loop_impl.cc:92:3
fml::MessageLoop::Run()
    ../../flutter/fml/message_loop.cc:49:0
#13 0x001474d9 /data/app/com.bilibili.comic-K6FPBLH-bxa1TioYtEcBnA==/lib/arm/libflutter.so 
fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const
    ../../flutter/fml/thread.cc:34:10
decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0&&)
    ../../third_party/libcxx/include/type_traits:3530:0
void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>)
    ../../third_party/libcxx/include/thread:341:0
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)
    ../../third_party/libcxx/include/thread:351:0
#14 0x0007342d /system/lib/libc.so (_ZL15__pthread_startPv+22) [armeabi-v7a::21cd61a810457179735b887fd6c4043c]
#15 0x0001e0e1 /system/lib/libc.so (__start_thread+22) [armeabi-v7a::21cd61a810457179735b887fd6c4043c]
</pre>
</details>

Logcat:

```
04-07 11:26:16.736 25329 25329 D HMSAgent: onStarted:com.bilibili.comic.home.view.FlutterMainActivity@42c4b56
04-07 11:26:16.740 25329 25329 D HMSAgent: onResumed:com.bilibili.comic.home.view.FlutterMainActivity@42c4b56
04-07 11:26:16.763 25329 25540 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
04-07 11:26:16.766 25329 25506 E libEGL : eglCreateWindowSurface: native_window_api_connect (win=0xb27b7808) failed (0xffffffed) (already connected to another API?)
04-07 11:26:16.766 25329 25506 E libEGL : eglCreateWindowSurface:814 error 3003 (EGL_BAD_ALLOC)
```

```
04-07 08:02:02.330 27908 28344 I OpenGLRenderer: Initialized EGL, version 1.4
04-07 08:02:02.330 27908 28344 D OpenGLRenderer: Swap behavior 2
04-07 08:02:02.332 27908 27908 W FlutterView: Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
04-07 08:02:02.335 27908 28185 I flutter : main() executed
04-07 08:02:02.342 27908 28185 I flutter : [Beta] push MaterialPageRoute<dynamic>-/
04-07 08:02:02.479 27908 28187 E libEGL : eglCreateWindowSurface: native_window_api_connect (win=0xcb99a808) failed (0xffffffed) (already connected to another API?)
04-07 08:02:02.479 27908 28187 E libEGL : eglCreateWindowSurface:720 error 3003 (EGL_BAD_ALLOC)
```

The issue was reported by users of my app and it's hard to reproduce it.

Flutter version:
```
Flutter 1.12.13+hotfix.9
Framework  f139b11009
Engine  af51afceb8
```

Crashed phones:

- Huawei P6-C00
- Huawei P6-T00
- Huawei JKM-AL00b
- VIVO V1914A
- VIVO V1831A
- VIVO X21I A
- REDMI NOTE 7

Android versions: 9, 8.1.0, 8.0.0  ...

**Comment by yy1300326388** [comment]
@yrom  你这个问题基本就是这个原因了 https://github.com/flutter/flutter/issues/47804

**Comment by yrom** [comment]
@yy1300326388 These two are totally different.

**Comment by xster** [comment]
cc @gaaclarke

**Comment by gaaclarke** [comment]
How is this app using Flutter?  Is this is a Flutter module?  Does it make sense why you might have a FlutterView that doesn't have an attached FlutterEngine?

What is happening when this crash happens, is this at app launching?

Did this happen 100% of the time for the customer, or sporadically?

[This SO article](https://stackoverflow.com/a/54237856) makes it sound like maybe app lifecycle isn't being managed correctly.  When trying to reproduce the bug I recommend backgrounding and foregrounding the app and putting the device to sleep to see if you can reproduce. it.

**Comment by yrom** [comment]
@gaaclarke 
Flutter is embedded to my app through a module, following the [add-to-app (use-a-cached-flutterengine) guide](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-3-optional-use-a-cached-flutterengine).

This crash is not 100%, and about 1% of customers have crashed 1.2 times on average up to now.

I investegate the logs from customer, some of them occur on FlutterActivity resumed but has not been fully drawn before. The activity stack is NativeActivity-> FlutterActivity. FlutterActivity lifecycle is: created -> resumed -> (imediatly) paused  -> (after few seconds) -> resumed. 

In this case, the lifecycle of the engine seems to be messed up.

Some of them occur when FlutterActivity starts. The activity stack is NativeActivity-> FlutterActivity. FlutterActivity lifecycle is: created -> resumed.

In this case, this crash is incredible because the engine was created for the first time.

I will try to reproduce it as much as possible.

**Comment by zoeyfan** [comment]
@yrom, @zsunkun 
I know both of you encountered this issue? For us to look into this further, would you both please help supply repro steps? Thanks!

**Comment by zsunkun** [comment]
@zoeyfan I don't know how to reproduce it yet, I will try to find a way to reproduce it

**Comment by xster** [comment]
@zoeyfan does our customer: bytedance have any repro steps for this issue?

**Comment by zoeyfan** [comment]
@xster, unfortunately not yet. @zsunkun is from bytedance, he indicated in the last comment that he is working on a repro.

**Comment by yrom** [comment]
I highly suspect that it is caused by the FlutterEngine being asynchronously attached to FlutterView.

```java FlutterActivityAndFragmentDelegate.java
void onStart() {
    ...
    new Handler().post(new Runnable() {
      @Override
      public void run() {
        Log.v(TAG, "Attaching FlutterEngine to FlutterView.");
        flutterView.attachToFlutterEngine(flutterEngine);

        doInitialFlutterViewRun();
      }
    });
}
```
See https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L290-L298


Activity lifecycle:
```
2020-04-23 22:19:05 .flutter.ui.FlutterPageActivity onCreated
2020-04-23 22:19:05 .flutter.ui.FlutterPageActivity onResumed
2020-04-23 22:19:06 .flutter.ui.FlutterPageActivity onPaused
2020-04-23 22:19:08 .flutter.ui.FlutterPageActivity onResumed
2020-04-23 22:19:08 .flutter.ui.FlutterPageActivity onPaused
```

Stacktrace of main thread:
```
1 io.flutter.embedding.engine.FlutterJNI.nativeSurfaceCreated(Native Method)
2 io.flutter.embedding.engine.FlutterJNI.void onSurfaceCreated(android.view.Surface)(bm:3)
3 io.flutter.embedding.engine.renderer.FlutterRenderer.void startRenderingToSurface(android.view.Surface)(bm:16)
4 io.flutter.embedding.android.FlutterSurfaceView.void connectSurfaceToRenderer()(bm:3)
5 io.flutter.embedding.android.FlutterSurfaceView.void attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)(bm:14)
6 io.flutter.embedding.android.FlutterView.void attachToFlutterEngine(io.flutter.embedding.engine.FlutterEngine)(bm:17)
7 io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2.void run()(bm:3)
8 android.os.Handler.handleCallback(Handler.java:907)
9 android.os.Handler.dispatchMessage(Handler.java:105)
10 android.os.Looper.loop(Looper.java:216)
11 android.app.ActivityThread.main(ActivityThread.java:7625)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Logcat:
```
04-23 22:19:05.308 10888 10888 D HMSAgent: onCreated:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:06.161 10888 10888 D HMSAgent: onPaused:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:07.986 10888 10888 D HMSAgent: onStopped:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:08.075 10888 10888 D HMSAgent: onStarted:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:08.134 10888 10888 D HMSAgent: onResumed:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:08.294 10888 10888 D HMSAgent: onPaused:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:08.378 10888 10888 D HMSAgent: onStopped:com.bilibili.comic.bilicomic.flutter.ui.FlutterPageActivity@6b76ef6
04-23 22:19:08.400 10888 11100 E libEGL : eglCreateWindowSurface: native_window_api_connect (win=0xcd14e008) failed (0xffffffed) (already connected to another API?)
04-23 22:19:08.400 10888 11100 E libEGL : eglCreateWindowSurface:814 error 3003 (EGL_BAD_ALLOC)
```

**Comment by xster** [comment]
Ah, that's a very sensible guess since that code doesn't look very defensive. Do you have any way of testing a newer version since the suspected code is now no longer present? https://github.com/flutter/engine/pull/16527

**Comment by yrom** [comment]
I'll try that patch on my local engine to release the next version of my app. It may take some days to verify whether the crash still exists. Hope the guess is correct..

**Comment by zoeyfan** [comment]
Connected with the customer who indicated that it may take a while for them to repro. Set expectation that this issue may be auto closed if no response is received, but they are welcome to reopen any time if a repro is identified.

**Comment by yrom** [comment]
Good news. After applying flutter/engine#16527, this crash no longer appers in new version of my APP. I think this issue has been resolved after that PR.

**Comment by xster** [comment]
Excellent. Glad to hear. Thanks for testing!
