### ISSUE TITLE
WebView select boxes drop down dialogs are throwing on some tablets

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#54164]
The failing codepath is only active on tablets, I was only able to reproduce the crash on Android Things.

Repro steps, load a web page with a drop-down select box (like: `https://loc.gov`) on a tablet running Android Things, and tap the drop down.

The following exception is thrown:

```
04-06 02:00:58.035  3336  3336 E AndroidRuntime: FATAL EXCEPTION: main
04-06 02:00:58.035  3336  3336 E AndroidRuntime: Process: com.example.flutter_app, PID: 3336
04-06 02:00:58.035  3336  3336 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.DropDownListView.setSelection(int)' on a null object reference
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.ListPopupWindow.show(ListPopupWindow.java:697)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at org.chromium.ui.DropdownPopupWindow.show(DropdownPopupWindow.java:31)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at org.chromium.ui.DropdownPopupWindow$1.onLayoutChange(DropdownPopupWindow.java:4)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19677)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.AbsoluteLayout.onLayout(AbsoluteLayout.java:123)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 02:00:58.035  3336  3336 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
```

Note: I'm assigning April milestone as this is when `customer: dream` want it by, though at this point I'm still investigating and before we root cause the issue I have no real estimate for how involved is the fix.

b/152465158

**Comment by amirh** [comment]
This only happens with Android WebView versions older than 67.0.3367.0 (prior to Chromium commit [afb450](https://source.chromium.org/chromium/chromium/src/+/afb450fc02dfef4995a87c62b82d6cc0ed27be84?originalUrl=https%2F%2F:%2F%2F%2F%2Fcs.chromium.org%2F)).

Before [afb450](https://source.chromium.org/chromium/chromium/src/+/afb450fc02dfef4995a87c62b82d6cc0ed27be84?originalUrl=https%2F%2F:%2F%2F%2F%2Fcs.chromium.org%2F), on tablets Chromium used a `ListPopupWindow` to show select drop downs. `ListPoupWindow` is using `DropDownListView` which internally is using a [ListDropDownWindow](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/DropDownListView.java#28), which partially hijacks view focus (most importantly it [overrides isFocused](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/DropDownListView.java#337) to return true, which causes `requestChildFocus` to be invoked [here](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/view/ViewGroup.java#4970)) .

With Android WebView versions prior to [afb450](https://source.chromium.org/chromium/chromium/src/+/afb450fc02dfef4995a87c62b82d6cc0ed27be84?originalUrl=https%2F%2F:%2F%2F%2F%2Fcs.chromium.org%2F), the following sequence happens when a select drop down is shown:

1. WebView is calling`ListPopupWindow#show`
1. [buildDropDown](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/ListPopupWindow.java#613) is invoked, which sets `mDropDownList` to a `DropDownListView`.
1. [`showAsDropDown` is invoked](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/ListPopupWindow.java#695) - resulting in `mDropDownList` being added to the window and is also synchronously performing the following sequence:
    1. WebView's focus change listener is loosing focus (as mDropDownList got it)
    1. WebView is hiding all popups (as it lost focus)
    1. WebView's [`SelectPopupDropDown#hide`](https://source.chromium.org/chromium/chromium/src/+/master:content/public/android/java/src/org/chromium/content/browser/input/SelectPopupDropdown.java;l=79;drc=c4070b691ec0b1ce6a523ed1c2f26d08afa2110d?originalUrl=https:%2F%2Fcs.chromium.org%2F) is invoked.
    1. [`DropDownPopupWindow#dismiss`](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/ListPopupWindow.java#716) is invoked setting `mDropDownList` to null.
1. [`mDropDownList#setSelection`](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/ListPopupWindow.java#697) is invoked and is throwing a NullPointerException (as we just set `mDropDownList` to null).

This is an unfortunate case where a combination of grey area behaviors by Flutter, Chromium, and Android, each work on their own, crash when they are combined together.

This crash should not be popular as it requires a combination of an old Chromium version (vast majority of devices have a newer webview than `67.0.3367.0`) and a tablet (on non tablets Chromium is using an AlertDialog for select elements).

I can imagine a workaround in the form of preventing the webview's focus lost listener from being invoked in this specific case, though I'm not super excited to land such a hack. I'm currently working with `customer: dream` to see whether they can increase their minimal webview version requirement.

**Comment by amirh** [comment]
We need to workaround as `customer: dream` can't rely on a recent enough Android WebView.

I tried this as a workaround (in our `WebView` subclass):

```java
  @Override
  protected void onFocusChanged(boolean focused, int direction, Rect previouslyFocusedRect) {
    if (isCalledFromListPopupWindowShow() && !focused) {
      return;
    }
    super.onFocusChanged(focused, direction, previouslyFocusedRect);
  }

  private boolean isCalledFromListPopupWindowShow() {
    StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
    for (int i = 0; i < stackTraceElements.length; i++) {
      if (stackTraceElements[i].getClassName().equals(ListPopupWindow.class.getCanonicalName())
              && stackTraceElements[i].getMethodName().equals("show")) {
        return true;
      }
    }
    return false;
  }


```

Extremely hacky. But seems to work. I'm actually considering landing this given that I know for sure that with the current implementations of `ListPopupWindow` and `WebView` if we let this call go through the app will crash (I'd gate this on an Android version so we won't drop calls if `ListPopupWindow` changes, and also on a webview version). Theoretically there could be some visual difference caused by this workaround (the webview will visually present as focused where it previously didn't), but with these old webview versions I don't see any other choice (the alternative would be to let it crash). FWIW I couldn't easily find an example where it actually appears different than the native WebView, and also on newer WebView versions they migrated off the "focus hijacking" trick so the behavior with the workaround should be more similar to the newer webviews anyway.

## Difficulty testing this

### Integration test
This is the kind of fix that would normally make most sense to test with an integration test, though integration testing this is going to have a significant overhead (as non of the available emulator images use an old enough webview to have this bug, it will probably require us to set up our own emulator image which is not a business I want to get into), and probably puts `customer: dream`'s the launch at risk.

### Unit testing
This is not really trivial to test, you would normally want to confirm whether `WebView#onFocusChanged` was or was not called, typically by injecting the `WebView` implementation and then in the test replacing it with a mock, however this class `extends WebView` so we can't replace it with a testing implementation when under test.

Something we can do is instrument our overridden `onFocusChanged` and add a public API for observing when the call was propagated to the superclass, though this provides a partial test coverage (e.g nothing tests that the report that `onFocusChanged` was propagated to the superclass is correct) and costs in a public API.

### Testing exemption?
Flutter's testing policy has been recently formalized as: no code lands without a test, on extreme cases a testing exemption should be approved by @Hixie.

I think this is a case where our limited ability to unit test, and the high cost of putting together an integration test harness (both bootstraping and ongoing maintenance of an emulator image with an outdated Android webview), in addition with the low and temporary return (the vast majority of webviews out there don't have this issue, and AT are likely to upgrade soon as well) calls for a test exemption. @Hixie do you approve?

**Comment by Hixie** [comment]
can you unit test isCalledFromListPopupWindowShow() in some way? e.g. pass it a stack trace known to be relevant, and one known not to be, and verify that it handles them correctly?

anyway, LGTM either way.
