### ISSUE TITLE
Android sdkmanager tool not found (C:\Users\Mr\AppData\Local\Android\sdk\tools\bin\sdkmanager). Try re-installing or updating your Android SDK

### ISSUE THREAD

**Issue by NeverGiveUpToStudy** [flutter/flutter#54170]
![image](https://user-images.githubusercontent.com/34360186/78634246-1f331f80-78d6-11ea-86b5-216e56a28e92.png)

**Comment by TahaTesser** [comment]
Hi @NeverGiveUpToStudy 
After selecting SDK tools, you have to click apply to be able to install
Please follow this [comment](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
