### ISSUE TITLE
Drawer asset missing in hot mode from Atom?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5417]
![simulator screen shot aug 15 2016 9 02 18 pm](https://cloud.githubusercontent.com/assets/11857803/17687638/9d732cf6-632b-11e6-9271-118c2429a80f.png)

flutter doctor                                                    [/src/flutter]
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 89ed930429 (5 hours ago), engine revision fe509b0d96

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35

3dda6290893e8f6698afd10ae5275b7342668e5d is the latest flutter/flutter commit I'm on, I have one local commit.

FYI @johnmccutchan

**Comment by eseidelGoogle** [comment]
This happens from the command-line `flutter run --hot` as well.

**Comment by abarth** [comment]
Maybe we're not getting the font configuration right somehow?

**Comment by abarth** [comment]
(for the icon font)

**Comment by eseidelGoogle** [comment]
This is a recent regression to --hot mode.   Last week I demoed using d7fb51a551d43f2f93cf5e4436adb60efb1daa35 and things worked fine.

**Comment by Hixie** [comment]
I can no longer repro this on trunk, so I'm closing this.
