### ISSUE TITLE
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 621 pos 14: 'file != null': is not true.

### ISSUE THREAD

**Issue by razorabhu1995** [flutter/flutter#54172]
I have used `image_picker` plugin here. When I select the image such error occurs. Is it plugin error or am I doing something wrong?

code to pick image from gallery:
`    var image = await ImagePicker.pickImage(source:source);
`

**Comment by TahaTesser** [comment]
Hi @razorabhu1995 
You're most likely providing null value  
Please try the official `image_picker`[example](https://pub.dev/packages/image_picker#-example-tab-)
can you please provide your `flutter doctor -v` and `flutter run --verbose` running the this example above?
Thank you

**Comment by TahaTesser** [comment]
Hi @razorabhu1995 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
