### ISSUE TITLE
Some input files use unchecked or unsafe operations. Recompile with -Xlint:unchecked for details.

### ISSUE THREAD

**Issue by vijay0021** [flutter/flutter#54173]
E:\flutter\new\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: error: cannot find symbol
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
                                                         ^
  symbol:   class FlutterAndroidLifecyclePlugin
  location: package io.flutter.plugins.flutter_plugin_android_lifecycle
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by TahaTesser** [comment]
Hi @vijay0021 
can you please provide your `flutter doctor -v` and `flutter build apk --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by vijay0021** [comment]
@TahaTesser

**Comment by vijay0021** [comment]
hello @TahaTesser 

I am new in flutter, I dont know how to solve the issues in flutter.
Thank you

E:\flutter\new\vtrack\vtrack>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (8 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bijay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • LS 5020 • 0123456789ABCDEF • android-arm64 • Android 5.1 (API 22)

• No issues found!


E:\flutter\new\vtrack\vtrack>flutter build apk --verbose
[  +25 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +64 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +6 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\
[   +8 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.25+3\
[ +120 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\
[   +6 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.25+3\
[  +61 ms] Generating E:\flutter\new\vtrack\vtrack\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +68 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[   +1 ms] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[   +1 ms]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from E:\flutter\new\vtrack\vtrack\android\gradlew.bat.
[  +14 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +111 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +3 ms] executing: [E:\flutter\new\vtrack\vtrack\android\] E:\flutter\new\vtrack\vtrack\android\gradlew.bat -Pverbose=true -Ptarget=lib\main.dart
-Ptrack-widget-creation=true -Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[+85810 ms] > Task :app:compileFlutterBuildRelease
[   +2 ms] [  +21 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +72 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] [        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +62 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.9-0-gf139b1100
[        ] [   +6 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\flutter\] git ls-remote --get-url origin
[   +1 ms] [  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +103 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[   +1 ms] [  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +92 ms] Initializing file store
[   +1 ms] [  +56 ms] kernel_snapshot: Starting due to {}
[   +2 ms] [  +13 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk_product/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=true --bytecode-options=source-positions --aot --tfa --packages E:\flutter\new\vtrack\vtrack\.packages --output-dill
E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\app.dill --depfile
E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\kernel_snapshot.d package:vtrack/main.dart
[+12954 ms] [+13691 ms] kernel_snapshot: Complete
[+1299 ms] [+1258 ms] invalidated build due to missing files: C:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot
[   +1 ms] [   +1 ms] aot_android_asset_bundle: Starting due to {}
[  +99 ms] [ +121 ms] invalidated build due to missing files: C:\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot
[   +1 ms] [  +10 ms] invalidated build due to missing files: C:\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x64\gen_snapshot
[  +97 ms] [  +42 ms] aot_android_asset_bundle: Complete
[ +401 ms] [ +469 ms] android_aot_release_android-arm: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.inputMissing}
[   +1 ms] [   +9 ms] executing: C:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\armeabi-v7a\app.so --strip
--no-sim-use-hardfp --no-use-integer-division E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\app.dill
[   +1 ms] [   +2 ms] android_aot_release_android-arm64: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.inputMissing}
[  +96 ms] [   +4 ms] executing: C:\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\arm64-v8a\app.so --strip
E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\app.dill
[   +2 ms] [   +1 ms] android_aot_release_android-x64: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.inputMissing}
[   +1 ms] [   +3 ms] executing: C:\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\x86_64\app.so --strip
E:\flutter\new\vtrack\vtrack\.dart_tool\flutter_build\664e7bf8acb552a9f2fc99a55025bcdb\app.dill
[+12796 ms] [+12808 ms] android_aot_release_android-arm64: Complete
[  +99 ms] [  +94 ms] android_aot_bundle_release_android-arm64: Starting due to {InvalidatedReason.inputChanged}
[   +1 ms] [   +5 ms] android_aot_bundle_release_android-arm64: Complete
[ +498 ms] [ +515 ms] android_aot_release_android-arm: Complete
[   +1 ms] [   +9 ms] android_aot_release_android-x64: Complete
[ +100 ms] [  +79 ms] android_aot_bundle_release_android-x64: Starting due to {InvalidatedReason.inputChanged}
[   +1 ms] [   +4 ms] android_aot_bundle_release_android-x64: Complete
[   +1 ms] [  +69 ms] android_aot_bundle_release_android-arm: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +5 ms] android_aot_bundle_release_android-arm: Complete
[ +194 ms] [ +140 ms] _composite: Starting due to {}
[   +1 ms] [        ] _composite: Complete
[        ] [   +1 ms] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [  +12 ms] "flutter assemble" took 29,650ms.
[+1295 ms] > Task :app:packLibsflutterBuildRelease
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[  +99 ms] > Task :app:extractProguardFiles
[   +1 ms] > Task :app:preReleaseBuild
[   +1 ms] > Task :flutter_plugin_android_lifecycle:preBuild UP-TO-DATE
[   +1 ms] > Task :flutter_plugin_android_lifecycle:preReleaseBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileReleaseAidl NO-SOURCE
[        ] > Task :google_maps_flutter:preBuild UP-TO-DATE
[        ] > Task :google_maps_flutter:preReleaseBuild UP-TO-DATE
[        ] > Task :google_maps_flutter:compileReleaseAidl NO-SOURCE
[        ] > Task :app:compileReleaseAidl NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:packageReleaseRenderscript NO-SOURCE
[        ] > Task :google_maps_flutter:packageReleaseRenderscript NO-SOURCE
[        ] > Task :app:compileReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :app:checkReleaseManifest
[        ] > Task :app:generateReleaseBuildConfig
[   +1 ms] > Task :flutter_plugin_android_lifecycle:checkReleaseManifest
[  +86 ms] > Task :flutter_plugin_android_lifecycle:compileReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :flutter_plugin_android_lifecycle:generateReleaseBuildConfig
[   +1 ms] > Task :flutter_plugin_android_lifecycle:generateReleaseResValues
[        ] > Task :flutter_plugin_android_lifecycle:generateReleaseResources
[ +198 ms] > Task :flutter_plugin_android_lifecycle:packageReleaseResources
[ +101 ms] > Task :flutter_plugin_android_lifecycle:processReleaseManifest
[   +5 ms] > Task :google_maps_flutter:checkReleaseManifest
[        ] > Task :google_maps_flutter:generateReleaseBuildConfig
[   +1 ms] > Task :google_maps_flutter:compileReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :flutter_plugin_android_lifecycle:parseReleaseLibraryResources
[  +90 ms] > Task :flutter_plugin_android_lifecycle:javaPreCompileRelease
[        ] > Task :google_maps_flutter:generateReleaseResValues
[        ] > Task :google_maps_flutter:generateReleaseResources
[        ] > Task :google_maps_flutter:packageReleaseResources
[        ] > Task :app:cleanMergeReleaseAssets UP-TO-DATE
[        ] > Task :google_maps_flutter:parseReleaseLibraryResources
[        ] > Task :app:mergeReleaseShaders
[  +96 ms] > Task :app:compileReleaseShaders
[   +1 ms] > Task :app:generateReleaseAssets
[   +1 ms] > Task :flutter_plugin_android_lifecycle:mergeReleaseShaders
[        ] > Task :flutter_plugin_android_lifecycle:compileReleaseShaders
[        ] > Task :flutter_plugin_android_lifecycle:generateReleaseAssets
[        ] > Task :flutter_plugin_android_lifecycle:packageReleaseAssets
[        ] > Task :google_maps_flutter:mergeReleaseShaders
[        ] > Task :google_maps_flutter:compileReleaseShaders
[        ] > Task :google_maps_flutter:generateReleaseAssets
[   +1 ms] > Task :google_maps_flutter:packageReleaseAssets
[        ] > Task :app:mergeReleaseAssets
[        ] > Task :app:copyFlutterAssetsRelease
[  +92 ms] > Task :app:mainApkListPersistenceRelease
[   +1 ms] > Task :flutter_plugin_android_lifecycle:generateReleaseRFile
[ +497 ms] > Task :flutter_plugin_android_lifecycle:compileReleaseJavaWithJavac
[   +1 ms] > Task :google_maps_flutter:processReleaseManifest
[   +1 ms] > Task :flutter_plugin_android_lifecycle:bundleLibCompileRelease
[  +97 ms] > Task :app:generateReleaseResValues
[        ] > Task :app:generateReleaseResources
[+1898 ms] > Task :app:createReleaseCompatibleScreenManifests
[ +100 ms] > Task :app:processReleaseManifest
[   +1 ms] > Task :google_maps_flutter:javaPreCompileRelease
[ +698 ms] > Task :app:mergeReleaseResources
[   +1 ms] > Task :google_maps_flutter:generateReleaseRFile
[ +397 ms] > Task :google_maps_flutter:compileReleaseJavaWithJavac
[   +2 ms] Note: Some input files use unchecked or unsafe operations.
[   +2 ms] Note: Recompile with -Xlint:unchecked for details.
[ +496 ms] > Task :app:processReleaseResources
[   +1 ms] > Task :google_maps_flutter:bundleLibCompileRelease
[ +698 ms] > Task :app:prepareLintJar
[   +1 ms] > Task :app:validateSigningRelease
[        ] > Task :app:signingConfigWriterRelease
[        ] > Task :google_maps_flutter:prepareLintJarForPublish
[        ] > Task :app:javaPreCompileRelease
[ +595 ms] > Task :app:compileReleaseJavaWithJavac FAILED
[   +1 ms] E:\flutter\new\vtrack\vtrack\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: error: cannot find symbol
[   +1 ms] 
io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_
android_lifecycle.FlutterAndroidLifecyclePlugin"));
[   +1 ms]                                                          ^
[        ]   symbol:   class FlutterAndroidLifecyclePlugin
[        ]   location: package io.flutter.plugins.flutter_plugin_android_lifecycle
[        ] 1 error
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileReleaseJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 2m 1s
[   +1 ms] > Task :flutter_plugin_android_lifecycle:prepareLintJarForPublish
[   +1 ms] 49 actionable tasks: 48 executed, 1 up-to-date
[ +360 ms] Running Gradle task 'assembleRelease'... (completed in 122.6s, longer than expected)
[   +5 ms] "flutter apk" took 1,23,106ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by TahaTesser** [comment]
Hi @vijay0021 
Can you please try `flutter pub upgrade` from root of your app then build apk?
Thank you

**Comment by vijay0021** [comment]
Hello @TahaTesser 

I have done it as you said but nothing happened..

E:\flutter\new\vtrack\vtrack>flutter pub upgrade
Running "flutter pub upgrade" in vtrack...                         17.1s

I got this error whenever I add  **google_maps_flutter: ^0.5.25+3** on **pubspec.yaml** and run the project.


<------pubspec.yaml ---------->

name: vtrack
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.25+3
  intl: ^0.16.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tbsl_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by vijay0021** [comment]
Hello @TahaTesser 

I have done it as you said but nothing happened..

E:\flutter\new\vtrack\vtrack>flutter pub upgrade
Running "flutter pub upgrade" in vtrack...                         17.1s

I got this error whenever I add  **google_maps_flutter: ^0.5.25+3** on **pubspec.yaml** and run the project.


<------pubspec.yaml ---------->

name: vtrack
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.25+3
  intl: ^0.16.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tbsl_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by TahaTesser** [comment]
Hi @vijay0021 
I just created new project and tested `google_maps_flutter: ^0.5.25+3` and found no issues on latest stable 

Make sure you've proper spaces 
<img width="812" alt="Screenshot 2020-04-08 at 1 12 26 PM" src="https://user-images.githubusercontent.com/48603081/78757742-9df19080-799a-11ea-88c6-3617368ff618.png">

Thank you

**Comment by vijay0021** [comment]
Hi @TahaTesser 
I am still facing this issue.. In the first time compilation when I remove google_map_flutter dependency then it is working fine without any issue.. after first time compilation when I uncomment google_map_flutter then it is also working.. but if I don't remove google_map_flutter dependency for the first time compilation then it shows me this..... 

Launching lib\main.dart on LS 5020 in debug mode...
Running Gradle task 'assembleDebug'...
E:\flutter\new\vtrack\vtrack\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: error: cannot find symbol
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
                                                         ^
  symbol:   class FlutterAndroidLifecyclePlugin
  location: package io.flutter.plugins.flutter_plugin_android_lifecycle
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1


Thank you

**Comment by TechSatya** [comment]
@vijay0021 Why did you close this issue? Did you find any solution?

I'm also facing the same issue, but with a different package "flutter_sodium" and "webview_flutter".

`Note: Some input files use unchecked or unsafe operations.      
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /Users/mac/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sodium-0.0.11/android/src/main/java/com/firstfloorsoftware/fluttersodium/FlutterSodiumPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/mac/Library/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.22+1/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

Can anyone help please?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by MBanawa** [comment]
running flutter pub upgrade after running flutter upgrade fixed it

**Comment by vijay0021** [comment]
i had deleted the flutter package and download another one then setup it correctly.. that fixed my issue

**Comment by MattPurland** [comment]
> running flutter pub upgrade after running flutter upgrade fixed it

This did it for me, many thanks!
