### ISSUE TITLE
Atom hot reload gets confused after stopping app with debugger stop button

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5418]
If you press the "stop" button while a hot-reload app is running from Atom, the app stops and the log says:
`Application finished.`

But then if you hit the start/play command-R button again you just get:
```
No files to remove.
No files to update.
```

I would expect it start the app again on the device.

FYI @johnmccutchan @devoncarew

**Comment by eseidelGoogle** [comment]
The stop button I'm referring to is the one in the debugger:
<img width="322" alt="screen shot 2016-08-15 at 9 06 37 pm" src="https://cloud.githubusercontent.com/assets/11857803/17687691/315cdd72-632c-11e6-809d-2ac7cdfcd533.png">

The one just above the logs seems to do the right thing.

**Comment by eseidelGoogle** [comment]
3dda629 is the latest flutter/flutter commit I'm on, I have one local commit.  Same as what I pasted in #5417.

**Comment by devoncarew** [comment]
I think the issue here is that stop is not fully stopping the process - Atom still thinks the app is running (I think this can be addressed in flutter_tools).
