### ISSUE TITLE
Webview webview_flutter on Android TV app remote controller d-pad navigation

### ISSUE THREAD

**Issue by andraskende** [flutter/flutter#54186]
Hello,

I'm trying to write a flutter app for Android TV.

The webview_flutter doesn't seem to work with d-pad on Android TV.

It loads the webpage but tab navigation is not working..

I tried on stackoverflow but no response, also only a few flutter TV questions there.

Thanks,
Andras

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.18.1-pre.4, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.18.1-pre.4 at /Users/andras/development/flutter
    • Framework revision 8f7327f83a (9 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andras/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/andras/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • SHIELD Android TV • 192.168.2.187:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi, @andraskende, can you please confirm if the issue persists on the latest flutter and webview versions?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
