### ISSUE TITLE
Add a wifi direct plugin

### ISSUE THREAD

**Issue by NoamDev** [flutter/flutter#54182]
## Use case

I want to create p2p communication over wifi.
There's already a question about it in stacloverflow, https://stackoverflow.com/questions/60384981/flutter-wifi-direct.

## Proposal

Add a plugin interface for [Android's WifiP2pManager](https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pManager).

Maybe there's an IOS equivalent library too.

**Comment by stuartmorgan** [comment]
This is a niche use case; it would be a great opportunity for a third-party package, but not something that the Flutter team would build and maintain.
