### ISSUE TITLE
Error in Flutter App while implementing youtube player

### ISSUE THREAD

**Issue by jansaidashaik** [flutter/flutter#54183]
Please find the below error and help me

Compiler message:
../lib/youtube_player.dart:1175:31: Error: No named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(isInitialRoute: false),
                              ^^^^^^^^^^^^^^
/C:/CreativeWork/flutter/packages/flutter/lib/src/widgets/navigator.dart:419:9: Context: Found this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Circular dependency between the following tasks:
:youtube_player:generateDebugRFile
\--- :youtube_player:generateDebugRFile (*)

(*) - details omitted (listed previously)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\Sateesh Reddy\Downloads\sarbagyastha-youtube_player-v3.1.1-11-g1850147\sarbagyastha-youtube_player-1850147\android\build.gradle' line: 2

* What went wrong:
Could not get unknown property 'ANDROIDX_WARNING' for project ':youtube_player' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TahaTesser** [comment]
Hi @jansaidashaik 
For issue related to the 3rd party plugin [youtube_player](https://pub.dev/packages/youtube_player) you may want to open an issue in the dedicated [github](https://github.com/sarbagyastha/youtube_player/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
