### ISSUE TITLE
[Bug][Flutter Web] PaintingContext.pushClipPath does not work

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#54187]
I am extending a class from RenderBox and overriding its `void paint(PaintingContext context, Offset offset)` function.

I need to clip an area and draw using `context.pushClipPath`. But its not working on web (Works perfectly on Android and iOS).

My clip path is like this:

```
Path _getDimClipPath() {
final size = Size(300, 500);
final rect = Rect.fromLTWH(20.0, 20.0, 100, 100);

return Path()
  ..addRect(rect)
  ..addRect(Rect.fromLTWH(0.0, 0.0, size.width, size.height))
  ..fillType = PathFillType.evenOdd;
}
```
The expected result is to fill a rectangle of size 300x500 and have a rectangular hole of size 100x100 in the middle.

I am using the master channel, latest commit:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.18.1-pre.4, on Microsoft Windows [Version 10.0.18363.752], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.43.2)
[√] Connected device (2 available)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @xclud 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/49534
I'm closing the current one as duplicate.
If you disagree and your case is different please write in the comments and I will reopen it.
Thank you
