### ISSUE TITLE
Creating an instance of Path inside an isolate fail

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#54190]
Apply to all flutter versions.

```
 static int tryThis(int v) {
    final path = Path();
    return v;
  }

compute(tryThis, 42)
```

=> Fail with `Unhandled Exception: Exception: error: native function 'Path_constructor' (1 arguments) cannot be found`

Path use a native impl. _does it mean you can't create any instance that rely on native impl in isolate_ ?

Looks like a Skia graphical context is required by the native implementation and not found in a new isolate. Yet I need to do intensive work inside my isolate to not block the main UI thread, is there any solution to this ?

Thank you

**Comment by PixelToast** [comment]
see: #10647

I suggest only passing the information required to construct the path (e.g. a list of offsets) rather than sending a Path object directly.

**Comment by Solido** [comment]
I understand the suggestion but 2 points:

First I don't only need Path, it means I need to reimplement all required classes

Also does it fail because it require a Skia context or because it is native ?

We must be able to wrap a Isolate to the graphic context to compute complexe rendering.

I'm not looking for a hack since I work on a lot of generative art. Working in the main Isolate is NOT the way to make thing effective. 

I was expecting isolate to avoid using FFI.
