### ISSUE TITLE
flutter_windows_v1.12.13+hotfix.9-stable logging on every tap or when changing screens

### ISSUE THREAD

**Issue by RaiAnsar** [flutter/flutter#54196]
Refering to issue [#50892](https://github.com/flutter/flutter/issues/50892), [christopherfujino](https://github.com/christopherfujino) closed the issue saying:

> So, the accessibility warning was a bug that was fixed in version 13.0, unfortunately, after the latest stable was cut.
> 
> The reason this was only seen after hotfix 8 was release, was because there was a separate regression that was over-aggressively filtering logs, which was obscuring legitimate logs (such as app crashes and this accessibility warning). Hotfix 8 removed this log filtering, thus surfacing the accessibility warning.
> 
> We apologize for regressing the user experience in this way on the stable channel. This warning message has been fixed on the beta, dev, and master channels, and will be removed from the next **stable** release.

But even after latest release this issue hasn't been fixed as I', still getting this error on every single tap.
I've tried `flutter pub cache repair` and `flutter clean` but can't see any difference.
### Here's a screenshot:
![image](https://user-images.githubusercontent.com/35567562/78681295-fe82be00-7905-11ea-92e1-4b921c003550.png)

**Comment by MichaelSowah** [comment]
Exactly and it's pretty annoying when you debugging...I actually also raised an issue on this a couple of days ago and see the response I also get

**Comment by VladyslavBondarenko** [comment]
Hi @RaiAnsar 
https://github.com/flutter/flutter/issues/50892#issuecomment-593615696
> will be removed from the next stable release

did you mean any new stable release, even hotfix? or new stable release which will be 1.13.0 or higher?

**Comment by RaiAnsar** [comment]
> Hi @RaiAnsar
> [#50892 (comment)](https://github.com/flutter/flutter/issues/50892#issuecomment-593615696)
> 
> > will be removed from the next stable release
> 
> did you mean any new stable release, even hotfix? or new stable release which will be 1.13.0 or higher?

I meant the last hotfix which seems to be reducing it but not completely solving it.
This issue has been opened since December 3 #45928, but maintainers keep closing it without completely solving it.

**Comment by RaiAnsar** [comment]
> Exactly and it's pretty annoying when you debugging...I actually also raised an issue on this a couple of days ago and see the response I also get

Closing without solving the issue is multiple developers to open the same issue again.

**Comment by RaiAnsar** [comment]
Thanks to @eseidelGoogle for suggesting temporary solution of moving to beta channel on issue #50892 :

> The easiest workaround for now is to just use `flutter channel beta` to switch to the beta channel where we have resolved this bug. Thanks!

And after testing I can confirm that this issue has been resolved in beta release. And thanks to @pcsosinski  for mentioning that  **beta**  is capable of production release so I'll be closing it here,  hoping that issue will be solved in next `Stable release` as well.
