### ISSUE TITLE
Need "Expo"-like wrapper app to run Flutter code on physical devices.

### ISSUE THREAD

**Issue by pratiklodha** [flutter/flutter#54191]
Hi! 
To run code onto the physical devices ReactNative uses the "Expo" mobile app that acts as a wrapper to see live changes during development. There is no need to install Android Studio and/or Xcode. (We just need to install Expo cli).

**We need a similar wrapper (mobile app) which will enhance the Flutter developer experience.**

**Comment by jonahwilliams** [comment]
This would definitely be a super useful feature, at least for development. If you think this is important @pratiklodha I'd encourage you to get others to thumbs up the issue so it can be prioritized

**Comment by pratiklodha** [comment]
@jonahwilliams we already know this would be a super useful feature tool. You can use use your power and position to prioritise it😉. Not everything should be math-based. Moreover, I don't have any close community members to whom I could approach to upvote this feature. Hope you understand 😃

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/29021
