### ISSUE TITLE
color_filter_and_fade_perf__timeline_summary average_frame_build_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54205]
Slight jump at https://github.com/flutter/flutter/pull/54148; stronger signal at the skia roll https://github.com/flutter/flutter/pull/54156.

![Screen Shot 2020-04-07 at 9 45 29 AM](https://user-images.githubusercontent.com/1435716/78696638-8e981780-78b4-11ea-8ecd-75ccbdcf248d.png)

**Comment by tvolkert** [comment]
Isn't this a dup of https://github.com/flutter/flutter/issues/54095?

**Comment by tvolkert** [comment]
@liyuqian @jason-simmons @iskakaushik

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/issues/54095 involved rasterizer time - this one is about frame build time.  However, the frame build times on this benchmark have been rather noisy so I'm not sure if there is still a clear trend here.

**Comment by Hixie** [comment]
This is just a noisy benchmark, it was misbaselined at the start. Fixed on the dashboard.
