### ISSUE TITLE
I would like to retrieve random data from Firebase database.

### ISSUE THREAD

**Issue by androiddev123123** [flutter/flutter#54210]
Hi,

I would like to learn how to retrieve a random data from firebase database after the request of unique user.

User will send me his/her information after that request I would like to fetch a random inquiry from firebase database and show in the home page of the unique user.

Could you please share a code example for my request?

Thanks in advance for your kind support!!!

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
