### ISSUE TITLE
App looses changes made after the device is disconnected .Why is it?

### ISSUE THREAD

**Issue by harishpadmanabh-HP** [flutter/flutter#54224]
I am making an app in flutter . In the progress, I m hot restarting the app and its working fine. But ,
When i disconnect phone from system and again open the APP, the app shows the very stage of the build and not showing the further changes made in project. why is happening?

**Comment by jonahwilliams** [comment]
Hot reload cannot modify the APK/IPA of an application, so once the debug connection is closed and the app restarts, the original changes that are kept in memory are lost. If you want to install the latest changes you need to rebuild the app

**Comment by harishpadmanabh-HP** [comment]
thanks alot
