### ISSUE TITLE
Android Studio freezes with flutter when changing files

### ISSUE THREAD

**Issue by Elsrougy** [flutter/flutter#54222]
I had flutter with android studio for a while now and everything is working great until one day in any flutter project when I try to open any file android studio freezes for few minutes. For example, if I was in the main.dart file and then switched/opened another file the freezing occurs, and that happens in any file not just main. This freezing doesn't happen with normal android studio projects only with flutter

it's worth mentioning that in android studio plugins it always says can't load marketplace and to check the connection but I don't know when did that started and if it is related or not.

Also flutter analyze is taking a long time with no output. I tried reinstalling flutter, reinstalling android studio, reinstalling flutter (stable and beta), installing android studio beta instead of stable and nothing happened still the same problem

attached is idea.log and threadDumps-freeze that android studio generates.

```
flutter doctor -v output:
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at E:\src\flutter
    • Framework revision f139b11009 (8 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android Studio
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```
[logs.zip](https://github.com/flutter/flutter/files/4446727/logs.zip)

**Comment by iapicca** [comment]
Hi @Elsrougy  
in general the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues),
but give the fact that `flutter analyze` doesn't seem responsive yours might not be the case.

Does `flutter analyze` freeze running it from terminal as well?
Could you please with the latest `dev channel` ?
thank you

**Comment by jas0nchen** [comment]
I met the same problem, and my solution is change the plugin. My current plugin version is :
Flutter: 44.0.2
Dart: 192.7761

**Comment by jmagman** [comment]
It looks like the survey results are being [read on the main thread](https://github.com/flutter/flutter-intellij/blob/a88784769ade1897f45bff5aa4b06c1e31af594a/src/io/flutter/survey/FlutterSurveyService.java#L56)?  
```
	at java.net.URL.openStream(URL.java:1068)
	at io.flutter.survey.FlutterSurveyService.readString(FlutterSurveyService.java:71)
	at io.flutter.survey.FlutterSurveyService.fetchSurveyContent(FlutterSurveyService.java:59)
	at io.flutter.survey.FlutterSurveyService.getLatestSurveyContent(FlutterSurveyService.java:50)
	at io.flutter.survey.FlutterSurveyNotifications.checkForDisplaySurvey(FlutterSurveyNotifications.java:76)
	at io.flutter.survey.FlutterSurveyNotifications.access$000(FlutterSurveyNotifications.java:31)
```

And "can't load marketplace and to check the connection" makes me think some connection issue.

Can you file a new issue with https://github.com/flutter/flutter-intellij/issues/new, and include this info and that log dump?  I can't transfer it...

**Comment by Elsrougy** [comment]
So I tried a VPN and everything worked fine since then! but when I switch off the VPN the plugins marketplace doesn't load but everything else is OK. I have no idea what's that but maybe it's related to ISPs in my country doing DPI and blocking and throttling random services. I will just try the VPN when that happens again.

@jmagman @jas0nchen @iapicca 
Sorry for bothering you all and thank you for taking from your time trying to help me.

**Comment by jmagman** [comment]
> So I tried a VPN and everything worked fine since then! but when I switch off the VPN the plugins marketplace doesn't load but everything else is OK. I have no idea what's that but maybe it's related to ISPs in my country doing DPI and blocking and throttling random services. I will just try the VPN when that happens again.
> 
> @jmagman @jas0nchen @iapicca
> Sorry for bothering you all and thank you for taking from your time trying to help me.

Networking issues shouldn't make Android Studio freeze.  You definitely hit a real issue, and thank you for taking the time to report it!  I copied this issue to https://github.com/flutter/flutter-intellij/issues/4471, you can follow along over there!

**Comment by pq** [comment]
Hey @Elsrougy.  Sorry for the hassle.  As @jmagman mentioned this is a real bug.  I'll add some more context to  flutter/flutter-intellij#4471.
