### ISSUE TITLE
Clipboard does not work in Flutter Windows

### ISSUE THREAD

**Issue by TheCGDF** [flutter/flutter#54226]
## Steps to Reproduce

1. `Clipboard.setData(ClipboardData(text: "abc"));`

2. Paste in notepad or somewhere else.

Or:

1. Copy something form notepad or somewhere else.

2. Paste it in Flutter TextField

**Expected results:** 
Paste/Copy

**Actual results:** 
Flutter's clipboard works individually with Windows system. It cannot copy something to Windows clipboard. And when trying copy some from Windows to Flutter TextField, only garbled pasted.
![gen_pass_Gsb4vlr64v](https://user-images.githubusercontent.com/17256673/78716007-2ea77c80-7959-11ea-8123-9343d897c61f.jpg)

<details>
  <summary>Logs</summary>

```
flutter analyze
Analyzing gen_pass...
No issues found! (ran in 1.7s)
```

```
flutter doctor -v
[√] Flutter (Channel master, v1.18.0, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.18.0 at D:\Software\flutter
    • Framework revision 8f7327f83a (18 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Software\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Software\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.5.0)
    • Visual Studio at D:\Software\VS2019
    • Visual Studio Enterprise 2019 version 16.5.29911.84

[√] Android Studio (version 3.6)
    • Android Studio at D:\Software\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.1039]
    • Web Server • web-server • web-javascript • Flutter Tools
```

</details>

**Comment by stuartmorgan** [comment]
I take it the text you are copying and pasting in that screenshot is not ASCII?

Looking at the code and the docs, we're using `CF_TEXT`, but passing UTF-8, which isn't correct. We should do a UTF-8/UTF-16 conversion and use `CF_UNICODETEXT` instead.

**Comment by TheCGDF** [comment]
> I take it the text you are copying and pasting in that screenshot is not ASCII?
> 
> Looking at the code and the docs, we're using `CF_TEXT`, but passing UTF-8, which isn't correct. We should do a UTF-8/UTF-16 conversion and use `CF_UNICODETEXT` instead.

Whatever I copied, when i paste it to Flutter TextField, it will always be a single garbled character.

**Comment by minhcasi** [comment]
I have the same problem on Window, please help to fix it!
