### ISSUE TITLE
Could not find a file named “pubspec.yaml” in “username/flutter/packages/flutter_web_plugins”

### ISSUE THREAD

**Issue by ehsanbigzad** [flutter/flutter#54237]
After changing flutter version from `v1.12.13+hotfix.9` to `v1.9.1+hotfix.6` I got the following error when running `flutter pub get`.

```
Could not find a file named "pubspec.yaml" in "/Users/username/flutter/packages/flutter_web_plugins".
Running "flutter pub get" in userna...                                   
pub get failed (66)
```

**Comment by TahaTesser** [comment]
Hi @ehsanbigzad 
can you please provide your `flutter doctor -v` and `flutter pub get --verbose`?
