### ISSUE TITLE
flutter run --debug timing out while waiting for the observatory

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#5424]
In the pending engine roll (engine commit 9878b58878abe7e9bfed3e316420efb5e2934d04) flutter run --debug times out:

20002 ms • Waiting for observatory port to be available...
   0 ms • Timed out while waiting for a debug connection.

On Android I don't see any logs from the observatory

**Comment by johnmccutchan** [comment]
Possible causes:

1) The service isolate isn't being started.
2) The print('Observatory listening on...') is not making it into the device log (and back to flutter_tools).

Nothing has changed here lately though.

**Comment by jason-simmons** [comment]
The observatory isn't detected by flutter_tools because print() calls from Dart weren't showing up in the Android log.
The log write (guarded by #ifdef OS_ANDROID) isn't happening because dart_runtime_hooks.cc wasn't including the new FTL version of the build config macros.
