### ISSUE TITLE
[Proposal] [Share] Add onSuccess Callback

### ISSUE THREAD

**Issue by RichieMcMullen** [flutter/flutter#54244]
Hi,

In regards to this plugin `https://github.com/flutter/plugins/tree/master/packages/share`

Is it possible to have some callbacks added, would be nice to fire a snackBar notification on share success.

Regards

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
