### ISSUE TITLE
flutter_svg

### ISSUE THREAD

**Issue by tjalilpour** [flutter/flutter#54252]
I want to add svg file in my project, and i used flutter_svg: ^0.17.3, my project show the svg but in fact my svg file has 2 colors but in project it shows just in one color!!!!!!!!

and source of svg file:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><defs><style>.fa-secondary{opacity:.4}</style></defs><path d="M208 80a128 128 0 1 1-90.51 37.49A127.15 127.15 0 0 1 208 80m0-80C93.12 0 0 93.12 0 208s93.12 208 208 208 208-93.12 208-208S322.88 0 208 0z" class="fa-secondary"/><path d="M504.9 476.7L476.6 505a23.9 23.9 0 0 1-33.9 0L343 405.3a24 24 0 0 1-7-17V372l36-36h16.3a24 24 0 0 1 17 7l99.7 99.7a24.11 24.11 0 0 1-.1 34z" class="fa-primary"/></svg>
`

**Comment by jonahwilliams** [comment]
Please file at https://github.com/dnfield/flutter_svg
