### ISSUE TITLE
image_picker touch pass through

### ISSUE THREAD

**Issue by zzzs123** [flutter/flutter#54251]
In a Flutter widget and present image_picker to take a photo, after shot and touch the photo, the touch event will be passed through UIImagePickerController. If there's a TextField in flutter under the UIImagePickerController, the keyboard will be presented.

**Comment by iapicca** [comment]
Hi @zzzs123 
can you please provide your `flutter doctor -v` , 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by zzzs123** [comment]
I've raised a PR about this issue, please take a look at it.
Please fix the problem regardless my PR.
https://github.com/flutter/plugins/pull/2640

**Comment by TahaTesser** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/39218
I see there's an open issue addressing the case you described.  
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
