### ISSUE TITLE
dart analysis report Target of URI doesn't exist: and get package can't success

### ISSUE THREAD

**Issue by zyzhangyu** [flutter/flutter#54264]
# This is my running environment

➜  IssueFlutter git:(master) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)

• No issues found!

# This is my error
<img width="931" alt="截屏2020-04-08下午4 43 20" src="https://user-images.githubusercontent.com/7490062/78763696-11ee6180-79b8-11ea-8c97-b2be33eff703.png">

# Solutions I have tried
1. Remove and reinstall Flutter
2.Remove and reinstall IDE
3.Delete flutter's cache
4.get package
5.Reset dart service

# strange things
My colleague just clicked on Pub get and all the problems disappeared! This problem has been bothering me for two days. I read a lot of information on the Internet and tried many methods, but still can't solve my problem!

# Similar problems
https://github.com/flutter/flutter/issues/49702

# the most important thing
Although the code analysis can not pass, but my flutter project can run successfully without task errors!

**Comment by iapicca** [comment]
Hi @zyzhangyu 
can you please provide your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Hi @zyzhangyu 
are you experiencing the issue only with Android Studio 
or with VS Code as well?
Could you please provide your `flutter analyze --verbose`
Thank you

**Comment by zyzhangyu** [comment]
> 嗨@zyzhangyu
> 您是否仅在Android Studio
> 或VS Code中遇到此问题？
> 您是否也遇到了最新的问题`dev channel`？
> 你能提供你的`flutter analyze --verbose`
> 谢谢吗



I have the same problem in IDEA, Android Studio, and VSCode. I reset my Mac os operating system this morning, and then reconfigured the development environment of FLutter. Now the compiler will not report the above error!
Because I reset the computer system, I couldn't provide flutter analyze --verbose at that time!

# Some things in my memory:
<img width="931" alt="5025323E-818A-4A52-8916-A1D55ADA8EB6" src="https://user-images.githubusercontent.com/7490062/78851892-86271480-7a4d-11ea-9b40-ccf446b8537d.png">


The reason for reporting problem 2 is because when importing problem 1, the corresponding dart file cannot be found.
The original import statement is like this, import 'package: issue / other_page.dart';
But modify it to: import 'other_page.dart';
Question 2 will disappear, do not know if this information will help!

And after I reinstalled the Mac OS system, the IDE and Flutter versions used are the same as before, which means that this should not be a Flutter issue, but the setting of my compiler or development environment!

I have no problem, you can close this Issue!

Thank you very much for your attention to this issue！

**Comment by iapicca** [comment]
Hi @zyzhangyu 
I'm glad that you fixed the issue,
thank you for letting me know
