### ISSUE TITLE
flutter run after flutter create on MacOS for iOS hangs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5427]
The first time I build an app, `flutter run` just seems to hang after giving some obscure error message (something from FlutterDynamicsServiceLoader.mm). Eventually though (after I have up waiting) it completes and everything is fine.

We should make it faster.

We should also give progress while it's doing whatever it's doing so that you don't time out while waiting.

Steps:
```
flutter create testapp
cd testapp
flutter run
```

**Comment by Hixie** [comment]
Actually I'm wrong. It's just hanging.

**Comment by drewwarren** [comment]
duplicate of #5398 
d2b3976110508016a9dbaf73d94145b2163a3b06 is the commit this started happening

**Comment by Hixie** [comment]
Thanks drew.
