### ISSUE TITLE
Android Add2App leaks the FlutterView

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#54275]
In Add2App, when closing a FlutterView by calling finish() on the activity that hosts the view, a leak is present. The offender is a method channel that we have in a long living delegate that we've created which is given the DartExecutor from the engine that we've created and cached. 

It seems that some the channel ends up having a reference to a TextInputPlugin instance which has a reference to the FlutterView which never gets released when the FlutterView is closed.

I'm attaching the screenshots of the leak.

**Comment by dannyvalentesonos** [comment]
![android_leak_page1](https://user-images.githubusercontent.com/40898687/78790535-ab981d80-797c-11ea-9156-12402743a655.png)
![android_leak_page2](https://user-images.githubusercontent.com/40898687/78790539-ad61e100-797c-11ea-9017-d8ef7a617c65.png)

**Comment by VladyslavBondarenko** [comment]
Hi @dannyvalentesonos 
could you please provide a minimal project to reproduce it?
and attach your `flutter doctor -v`

**Comment by xster** [comment]
Seems like this might be the same issue you reported before in https://github.com/flutter/flutter/issues/36898. Do you have a simple repro for this?

**Comment by xster** [comment]
Note to self: https://github.com/flutter/engine/pull/9288 possibly related

**Comment by dannyvalentesonos** [comment]
@VladyslavBondarenko @xster Sorry for the delay. I've been working on a simple repro. It's not easy to build these Add2App simple apps and takes time :)

I'm attaching the project.

@xster I don't think it's related. The reference seems different in this one.

Thanks!

**Comment by dannyvalentesonos** [comment]
[Add2AppTest.zip](https://github.com/flutter/flutter/files/4452900/Add2AppTest.zip)

**Comment by jason-simmons** [comment]
I was able to reproduce this with the provided app and capture a heap dump.

The `FlutterDelegate` object in the app is holding a reference to the `FlutterEngine`, which holds the `DartExecutor` and `DartMessenger`.   The `TextInputPlugin` is instantiated by the `FlutterView` and registers a method channel with the `DartMessenger`, and the channel's method handler holds references back to the plugin and `FlutterView`.

So it looks like the `FlutterView` needs to unregister the channel when the view is destroyed.

**Comment by xster** [comment]
Thanks for looking into it @jason-simmons. At a glance, it seems like we should have saved the anonymous `TextInputChannel.TextInputMethodHandler` the constructor created. I assume the whole FlutterActivityAndFragmentDelegate.onDestroyView->FluterView.detachFromFlutterEngine->TextInputPlugin.destroy plumbing works. The destroy is just not unregistering the method handler.
