### ISSUE TITLE
Should make sure we test --release and other configurations

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5428]
Given our experiences over the last couple of days, we need to make sure we smoketest the full matrix of ways to launch the app.

For a newly-created app with `flutter create` and for the existing gallery app:
- [x] Linux -> Android --debug --hot
- [ ] Linux -> Android --debug --no-hot
- [ ] Linux -> Android --profile
- [ ] Linux -> Android --release
- [x] Linux -> host (flutter test)
- [x] MacOS -> Android --debug --hot
- [ ] MacOS -> Android --debug --no-hot
- [x] MacOS -> Android --profile
- [ ] MacOS -> Android --release
- [ ] MacOS -> iOS --debug --hot
- [ ] MacOS -> iOS --debug --no-hot
- [x] MacOS -> iOS --profile
- [ ] MacOS -> iOS --release
- [x] MacOS -> host (flutter test)

**Comment by sethladd** [comment]
Thanks for writing this up. Should we also be proactive with the automated
emails when things break?

**Comment by Hixie** [comment]
In my ideal world we'd be proactive with automatic reverts. :-)

**Comment by yjbanov** [comment]
I checked off the ones we added recently (end-to-end hot reload mode and MacOS -> iOS --profile).

What would we like to test in `--release` mode and what tools would we like to use? We do not have the VM service in release mode, but we should be able to take a screenshot via `adb` and compare it with some golden version. Perhaps something similar can be done for iOS.

**Comment by Hixie** [comment]
Going to close this since we don't need a bug to track it. We're doing most of these now.
