### ISSUE TITLE
Add a Link widget with option to open url in same window

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#54281]
## Use case

Looks like when you use url_launcher to open an external URL in web, it defaults to opening it in a new tab. It would be great to have an option to choose to open it in the same tab, replacing the current content.

## Proposal

Add an option on `launch` to open in same tab instead of new tab when on Web.

**Comment by mdebbar** [comment]
We have plans to work on a `Link` widget that will have better support for the web. @ferhatb do you know if there's already an issue for that (I couldn't find it by searching)? If not, I will create one.

**Comment by jlubeck** [comment]
Awesome, looking forward to it!

**Comment by tugorez** [comment]
I think we can add a **web only** _target_ param on the [interface](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/lib/url_launcher.dart#L57) and use it [here](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L22) to address this behaviour. 
I would be happy to take a look if we decide to add this to _url_launcher_

**Comment by ditman** [comment]
Yep, @tugorez please create a new issue for the changes to `url_launcher` that is tagged with `plugins`, `p:url_launcher` and the correct tags. It might be a good interim solution until this `Link` widget exists, but let's not override this thread :)

(Link has other requirements, particularly around Semantics that aren't a thing in the `url_launcher` plugin).
