### ISSUE TITLE
Figure out why or if precacheImage works on Flutter for Web

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#54292]
See the discussion in https://github.com/flutter/flutter/pull/51656#issuecomment-610555698

**Comment by yjbanov** [comment]
Not sure if it makes sense for the HTML case, but it makes sense for CanvasKit

**Comment by yjbanov** [comment]
@hterkelsen feel free to adjust the milestone as you see fit. I optimistically chose near-term just to get it out of the triage queue.

**Comment by pedromassangocode** [comment]
Does this still a valid issue?

**Comment by yjbanov** [comment]
This should work already. Feel free to reopen or file a new issue if it doesn't.
