### ISSUE TITLE
device logs on iOS include old stuff (e.g. when you call flutter run)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5429]
Steps to reproduce:

``` bash
flutter run
w # to dump the widget tree
# wait for the widget tree to be done dumping
q # to quit
flutter run
```

Notice how the second `flutter run` dumps the end of the widget tree from the previous run.

**Comment by eseidelGoogle** [comment]
I was not able to repro this using an iOS simulator just now.
