### ISSUE TITLE
url_laucher opening Whatsapp screen crashes on IOS

### ISSUE THREAD

**Issue by Bonissauro** [flutter/flutter#54302]
I'm trying this way to redirect my app's users to a whatsapp screen offering a pre-typed text:

`String url = "https://api.whatsapp.com/send?phone=+5561999998877&text=HELLO, FRIEND";
launch(url);`

It works perfectly on Android opening Whatsapp with desired text, but crashes on IOS, with the error wich I just can't figure out:

"The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported"

Did somebody face the same situation?

pubspec.yaml
url_launcher: ^5.4.2

**Comment by iapicca** [comment]
Hi @Bonissauro 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by Bonissauro** [comment]
Hello!

Here is the "flutter doctor -v" response:

flutter doctor -v
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.4 19E266, locale pt-BR)
    • Flutter version 1.18.0-5.0.pre.46 at /Users/bonissauro/flutter
    • Framework revision 0d459f2326 (6 hours ago), 2020-04-08 21:32:25 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bonissauro/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.


Here's the reproducible code sample.

`
String url = "https://api.whatsapp.com/send?phone=+5561999998877&text=HELLO, FRIEND";

launch(url);

`


Behavior:

On Android, it opens WhatsApp app and offers a default text "HELLO, FRIEND".

On IOS, app crashes with the following message on Xcode 11.4 console:
"The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported"

**Comment by TahaTesser** [comment]
Hi @Bonissauro 

It works fine for me

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    );
  }
}

_launchURL() async {
  const url = 'https://api.whatsapp.com/send?phone=+5561999998877&text=HELLO';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (2 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92
    • Web Server • web-server • web-javascript • Flutter Tools
• No issues found!
taha@Tahas-MacBook-Pro AndroidStudioProjects % flutterd doctor -v
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (2 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server    • web-server                • web-javascript • Flutter Tools
• No issues found!
```

</details>


![flutter_04](https://user-images.githubusercontent.com/48603081/78913564-d54d6380-7aa6-11ea-890f-3f19efc1af5a.png)

**Comment by VladyslavBondarenko** [comment]
Hi @Bonissauro 
@TahaTesser said that he tried with his iPhone and it's working as intended with current dev and master channels.

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    );
  }
}
_launchURL() async {
  const url = 'https://api.whatsapp.com/send&phone=+5561999998877&text=HELLO';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}
```

</details>

What device and OS version do you have? can you check with different devices?

**Comment by Bonissauro** [comment]
@TahaTesser I've just figured out the problem: looks like I cant't use any pontuation or <CR> on the message (like ",", "\n" and so on). 

Try sending "Hello, friends!\nWhat can I do for you today?" and you will surely get the error too.

Infortunelly, that's what I need for the feature I'm trying do add to my app.

Is there a way to get that?

Any suggestion is welcome.

10x in advance

**Comment by Bonissauro** [comment]
@VladyslavBondarenko I tried on an 11 Pro, a XR and a 7. All and every on in latest IOS.

**Comment by Saifallak** [comment]
i have nearly the same problem.
when I use 
`final u = "https://api.whatsapp.com/send?phone=$numberl&text=السلام عليكم لدي استفسار عن ";`

it crashes. when there is arabic words

**Comment by Saifallak** [comment]
i solved it by 

```dart
  Future<void> _askOnWhatsApp(BuildContext context) async {
    final _product = context.read<ProductProvider>().product;

    final u =
        "https://api.whatsapp.com/send?phone=${AppSettings.WHATS_APP_NUMBER1}&text=السلام عليكم ... استفسر عن ${_product.webNo} ${_product.title} ${_product.shareLink}";

    final uri = Uri.encodeFull(u);
    if (await canLaunch(uri)) {
      try {
        await launch(uri);
      } catch (e, s) {
        Crashlytics.instance.recordError('Manuel Reporting Crash $e', s);
        showDialog(
          context: context,
          builder: (BuildContext context) => ErrorPopUp(
            message:
                'لم نتمكن من فتح الواتساب في جهازك، برجاء التأكد من تنصيبه او ارسل لنا استفسارك علي'
                '\n'
                '${AppSettings.WHATS_APP_NUMBER1}'
                '\n'
                'مع الرقم المرجعي للمنتج'
                '\n'
                '${_product.webNo}',
          ),
        );
      }
    } else {
      showDialog(
        context: context,
        builder: (BuildContext context) => ErrorPopUp(
          message:
              'لم نتمكن من فتح الواتساب في جهازك، برجاء التأكد من تنصيبه او ارسل لنا استفسارك علي'
              '\n'
              '${AppSettings.WHATS_APP_NUMBER1}'
              '\n'
              'مع الرقم المرجعي للمنتج'
              '\n'
              '${_product.webNo}',
        ),
      );
    }
  }
```

just use uri encode and everything works

**Comment by stuartmorgan** [comment]
None of the examples of "URL" strings given above are valid, which is why they don't work; they cannot be parsed into a URL. As noted in some comments above, if the URLs are properly encoded, there is no issue.

(Note that encoding the entire URL after construction is not the best option, and will not give desired results in all cases; it's much better to use a `Uri` constructor that will properly encode each component.)
