### ISSUE TITLE
[githubbot] LUCI reruns aren't picked up by Github

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#54308]
When a PR triggers a LUCI build and the build fails, it's possible to rerun the build from the UI ([example](https://ci.chromium.org/p/flutter/builders/try/Windows%20Host%20Engine/6069)).

### Expected
The PR should pick up the status of the rerun and become green if the rerun succeeds.

### Actual
The PR has no idea about the rerun and stays red.

This works fine on Cirrus. My guess is we need to send some signal to Github to indicate that the task is being rerun.

**Comment by digiter** [comment]
From @stuartmorgan "If a Cirrus run fails and I retry it, the new job shows up on the PR, and if it goes green, that replaces the previous red and the PR shows green.
AFAICT a LUCI retry doesn't change anything in the PR's presubmit list
It definitely wasn't showing up with a yellow dot while the retry was in progress like a Cirrus retry would have"

**Comment by godofredoc** [comment]
This requires a migration from the current github status APIs to the checks APIs or graphql.

**Comment by rmistry** [comment]
> This requires a migration from the current github status APIs to the checks APIs or graphql.

Is there an open bug about migrating to checks API (or graphql) ?

**Comment by godofredoc** [comment]
This is the bug tracking migration to checks api:

https://github.com/flutter/flutter/issues/56422

**Comment by mdebbar** [comment]
@godofredoc should we close this issue as a duplicate of https://github.com/flutter/flutter/issues/56422?

**Comment by godofredoc** [comment]
Closing this bug as duplicated. Please follow up progress in https://github.com/flutter/flutter/issues/56422
