### ISSUE TITLE
Text Truncation Position

### ISSUE THREAD

**Issue by digawp** [flutter/flutter#54316]
## Use case

I have a need to truncate a list of text in a position other than the end.

I have a list of masked bank account numbers, some of them can be quite long that it overflows. While I could specify `maxLines` to limit how far the Text wraps, in Flutter it'll always truncate the end of the Text. This is not ideal for my use case because let's say there are multiple entries from the same bank, then there's no way the user can distinguish them because the end is always truncated.

This feature is available on the native platforms - [`android:ellipsize`](https://developer.android.com/reference/android/widget/TextView#attr_android:ellipsize) in Android and in [`truncationMode`](https://developer.apple.com/documentation/quartzcore/catextlayer/1515296-truncationmode) in iOS.

Can we have this feature implemented on Flutter as well?

## Proposal

To have this implemented as part of the `Text` widget API.

```
Text(
  'Some very very long text that only differs by its ending hehe',
  truncationPosition: TruncationPosition.middle,
);
Text(
  'Some very very long text that only differs by its ending haha',
  truncationPosition: TruncationPosition.middle,
);
```
Or, it could be added into `TextOverflow` enum to avoid possible conflict between truncation position and the overflow mode (eg `visible` at the middle) like so:
```
enum TextOverflow {
  ...
  ellipsisMiddle,
  ellipsisStart,
}
```

**Comment by iapicca** [comment]
Hi @digawp 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45336
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by justinmc** [comment]
Sorry this is my fault since I asked @digawp to open this issue.  I wasn't aware of https://github.com/flutter/flutter/issues/45336 but it does look like it describes this problem.  I'll focus on that one.
