### ISSUE TITLE
Flutter web on mobile browser is not working

### ISSUE THREAD

**Issue by YoussefElsaygh** [flutter/flutter#54325]
### **Steps to reproduce:**
1)Run flutter config --enable-web.
2) flutter run -d chrome
3)inspect on chrome and toggle device toolbar
4)refresh the app

### **Expected result :**
everything works fine 
### **Actual result:**

Error below appears on the console and the app freeze

> errors.dart:146 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:423:12
> sanitizer != null
> is not true
>     at Object.throw_ [as throw] (errors.dart:195)
>     at Object.assertFailed (errors.dart:26)
>     at _engine._PointerAdapter.new.[_getSanitizer] (pointer_binding.dart:423)
>     at pointer_binding.dart:474
>     at pointer_binding.dart:440
>     at pointer_binding.dart:210

**Comment by YoussefElsaygh** [comment]
![image](https://user-images.githubusercontent.com/27302495/78844629-9536a400-7a06-11ea-8d6e-51340c3e941b.png)

**Comment by iapicca** [comment]
Hi @YoussefElsaygh 
can you please provide your `flutter doctor -v` 
Thank you

**Comment by YoussefElsaygh** [comment]
[√] Flutter (Channel master, v1.18.0-5.0.pre.38, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.18.0-5.0.pre.38 at D:\flutter
    • Framework revision 19ff596979 (13 hours ago), 2020-04-08 15:42:02 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\yalsayegh\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\yalsayegh\AppData\Local\Android\Sdk;
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\yalsayegh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server    • web-javascript • Flutter Tools

**Comment by YoussefElsaygh** [comment]
i inspected html tree and i found that tag <flt-semantic-placeholder> is making that problem when i removed it from dom everything worked fine
![image](https://user-images.githubusercontent.com/27302495/78906563-ce5f2a80-7a7f-11ea-8028-e6a98468e183.png)

**Comment by VladyslavBondarenko** [comment]
@YoussefElsaygh 
I'm trying with `master v1.18.0-5.0.pre.47`

<details>
 <summary>and default app</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

</details>

I can't see the error. Can you see it after upgrade?

**Comment by mdebbar** [comment]
> i inspected html tree and i found that tag is making that problem when i removed it from dom everything worked fine

You are absolutely right. Good find :)

This problem was introduced by my earlier PR: https://github.com/flutter/engine/pull/17495
And the fix was merged in this PR: https://github.com/flutter/engine/pull/17595

It's still not rolled into the framework yet, but I'm hoping it'll be rolled soon in this PR: https://github.com/flutter/flutter/pull/54373
