### ISSUE TITLE
Non-fat binary App.framework/App is not armv7.

### ISSUE THREAD

**Issue by SametSahin10** [flutter/flutter#54321]
## Steps to Reproduce
run `flutter build ios`

I'm getting this error while trying to produce a release build for iOS.

> Non-fat binary
    /Users/sametsahin/FlutterProjects/bonarego/build/ios/Release-iphoneos/Runner.app/Framew
    orks/App.framework/App is not armv7. Running lipo -info:
    Non-fat file:
    /Users/sametsahin/FlutterProjects/bonarego/build/ios/Release-iphoneos/Runner.app/Framew
    orks/App.framework/App is architecture: x86_64
    Command PhaseScriptExecution failed with a nonzero exit code

<details>
  <summary>Logs</summary>

Output of
> flutter run --verbose

Use this link to access since it's too long to paste here.
https://pastebin.pl/view/a53c369e

Output of
> flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-TR)
    • Flutter version 1.12.13+hotfix.9 at /Users/sametsahin/flutter
    • Framework revision f139b11009 (9 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sametsahin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 4EDA5453-647C-4C82-B282-6D9F5786FFCF • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

pubspec.yaml

> name: bonarego
> description: A new Flutter project.
> 
> version: 2.0.0+0
> 
> environment:
>   sdk: ">=2.1.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   http: ^0.12.0+4
>   flutter_gifimage: ^1.0.1
>   lottie: ^0.3.2
>   cupertino_icons: ^0.1.2
>   circular_bottom_navigation: ^1.0.1
>   google_maps_flutter: ^0.5.22+3
>   location_permissions: ^2.0.4+1
>   video_player: ^0.10.7
>   chewie: ^0.9.8+1
>   just_audio: ^0.1.0
>   carousel_slider: ^1.4.1
>   intro_slider: ^2.2.9
>   json_annotation: ^3.0.1
>   shared_preferences: ^0.5.6+1
>   form_field_validator: ^1.0.1
>   sqflite: ^1.2.1
>   path_provider: ^1.6.0
>   cached_network_image: ^2.0.0
>   url_launcher: ^5.4.2
>   flutter_html: ^0.11.1
>   connection_status_bar: ^1.1.2
>   firebase_analytics: ^5.0.11
>   firebase_crashlytics: ^0.1.3
>   flutter_icons: ^1.0.0+1
>   device_preview: ^0.4.2
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   build_runner: ^1.7.4
>   json_serializable: ^3.2.5
> 
> flutter:
>   uses-material-design: true
>   assets:
>     - assets/
>     - assets/images/
>     - assets/icons/
>     - assets/animations/
>   fonts:
>     - family: CustomIcons
>       fonts:
>         - asset: assets/fonts/CustomIcons.ttf
>     - family: VentiCF
>       fonts:
>         - asset: assets/fonts/VentiCF-Medium.ttf
>         - asset: assets/fonts/VentiCF-Bold.ttf
>           weight: 700

**Comment by TahaTesser** [comment]
Hi @SametSahin10 
can you please provide your `flutter doctor -v` and `flutter build ios --verbose`?
Also please take a look at this possible [solution](https://github.com/flutter/flutter/issues/12725#issuecomment-528718785)
Thank you

**Comment by SametSahin10** [comment]
Solved it by removing "Thin Binary Build Phase" according to [this](https://github.com/flutter/flutter/issues/12725#issuecomment-377191926) solution.

**Comment by TahaTesser** [comment]
Hi @SametSahin10 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
