### ISSUE TITLE
Where should i write the closing of my app ?

### ISSUE THREAD

**Issue by mariamalbarghouti** [flutter/flutter#54331]
if i have a ListView to show a data from sql .
1)where should i But this function to close database?
2)_Close function is enough to close it or i need to use async?? 
 

     void _Close(Database db)  {
         db.close();
      }

this is my Listview:
 

     ListView getStudentsList() {
        return ListView.builder(
            itemCount: count,
            itemBuilder: (BuildContext context, int position) {
              return Card(
                color: Colors.white,
                elevation: 2.0,
                child: ListTile(
                  leading: CircleAvatar(
                    backgroundColor: isPassed(this.studentsList[position].pass),
                    child: getIcon(this.studentsList[position].pass),
                  ),
                  title: Text(this.studentsList[position].name),
                  subtitle: Text(this.studentsList[position].description + " | " +
                      this.studentsList[position].date),
                  trailing:
                  GestureDetector(
                    child: Icon(Icons.delete, color: Colors.grey,),
                    onTap: () {
                      _delete(context, this.studentsList[position]);
                    },
                  )
                  ,
                  onTap: () {
                    navigateToStudent(this.studentsList[position], "Edit Student");
                  },
                ),
    
              );
            });
      }

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
