### ISSUE TITLE
fallback_discovery_tests are taking 10+ seconds to run

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54332]
Failure cases like `Selects mdns discovery if VM service connecton fails due to Sentinel` are really running the backoff time.

https://github.com/flutter/flutter/blob/77ea848c462eb0eafa9a01d76a678317d7470890/packages/flutter_tools/lib/src/ios/fallback_discovery.dart#L187

**Comment by jonahwilliams** [comment]
Ahh, this should be running with FakeAsync
