### ISSUE TITLE
How to fix setState after disposeError on a screen with a bottom navigation bar

### ISSUE THREAD

**Issue by boucoding** [flutter/flutter#54342]
## Steps to Reproduce

I am developing an app using flutter but I came up with a problem and I have tried to solve it for a week but no result, first I will describe my app hierarchy I have a stateful widget which returns bottom navigation bar and uses AutomaticKeepAliveChientMixin and page storage in order to save the states of the pages but nothing happened.

when I navigate between items and return to a specific page where I want to set state to update a variable based on socket.io listener in init state method I got an error called setState was called after dispose

My Problem is similar to this:
 https://stackoverflow.com/questions/55116042/how-to-fix-setstate-after-disposeerror-on-a-screen-with-a-tabbar

flutter run verbose:
```
[  +30 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +80 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags   
[ +109 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.12.13+hotfix.9-0-gf139b11009
[   +6 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +98 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +122 ms] executing: C:\Users\boood\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +39 ms] Exit code 0 from: C:\Users\boood\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[   +1 ms] List of devices attached
[   +9 ms] No supported devices connected.
[  +15 ms] "flutter run" took 243ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)    
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)    
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)      
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)    
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
flutter analyze:
```

No issues found! (ran in 2.5s)

```
flutter doctor -v
```

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720],
    locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (9 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\boood\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
```

**Comment by VladyslavBondarenko** [comment]
Hi @boucoding 
could you please provide a complete minimal code sample to reproduce your case?

**Comment by boucoding** [comment]
of what part? there is a stateful widget that has the bottom navigation bar and there are many screens inside. please tell me what you mean?

**Comment by VladyslavBondarenko** [comment]
I mean such complete code sample, that I can simply copy and run, minimal but enough for reproducing the error

**Comment by boucoding** [comment]
This is the full code of the stateful widget containing the bottom navigation bar :
`
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:joiny/provider/profiler.dart';
import 'package:joiny/screens/discover.dart';
import 'package:joiny/screens/news.dart';
import 'package:joiny/screens/profile.dart';
import 'package:joiny/theme/light_color.dart';
import 'package:provider/provider.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with AutomaticKeepAliveClientMixin {

  List<Widget> pages = [];

  var bottomNavigationBarCurrentIndex = 0;


  @override
  bool get wantKeepAlive => true;

  @override
  void initState() {
    super.initState();
    Future.delayed(Duration.zero, () {
      setState(() {
        pages = [
          Discover(
            key: PageStorageKey(
              'discover',
            ),
          ),
          News(
            key: PageStorageKey('news'),
          ),
          Scaffold(),
          Profile(
            key: PageStorageKey('profile'),
            user: Provider.of<Profiler>(context).currentUser,
          ),
        ];
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: pages[bottomNavigationBarCurrentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: bottomNavigationBarCurrentIndex,
        onTap: (index) {
          setState(() {
            this.bottomNavigationBarCurrentIndex = index;
          });
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(
              Icons.search,
              color: LightColor.purple,
            ),
            title: Text(
              'Discover',
              style: TextStyle(
                color: LightColor.purple,
              ),
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(
              Icons.event,
              color: LightColor.purple,
            ),
            title: Text(
              'News',
              style: TextStyle(
                color: LightColor.purple,
              ),
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(
              Icons.chat,
              color: LightColor.purple,
            ),
            title: Text(
              'Chat',
              style: TextStyle(
                color: LightColor.purple,
              ),
            ),
          ),
          BottomNavigationBarItem(
            icon: Icon(
              Icons.account_box,
              color: LightColor.purple,
            ),
            title: Text(
              'Profile',
              style: TextStyle(
                color: LightColor.purple,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

`

**Comment by VladyslavBondarenko** [comment]
@boucoding 
provide **complete** and **minimal** code sample, that I can simply copy and run.
without dependencies of your imports in the file.

Doesn't this workaround frow StackOverflow help you?
```
if(!mounted) return;
setState(() {
 _expiredTickets.add(ticket);            
});
```

**Comment by boucoding** [comment]
this isn't a solution it only prevents set state as my state is not mounted

**Comment by boucoding** [comment]
init state: 

```
@override
  void initState() {
    super.initState();
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      await getStories(context);
      if (Provider.of<PostsProvider>(context).posts == null ||
          Provider.of<PostsProvider>(context).posts.isEmpty) {
        await getPosts(context);
      }
    });
    IO.Socket socket = IO.io('$SERVER_URL', <String, dynamic>{
      'transports': ['websocket']
    });
    socket.connect();
    socket.on('posts', (d) {
      Map<String, dynamic> test = Map<String, dynamic>.from(d);


      var data = json.decode(test['data']);

      if (test['action'].toString() == 'add') {
        posts.add(data);
        setState((){});
      }
    });
    _editingController = TextEditingController();
  }
```

**Comment by VladyslavBondarenko** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by boucoding** [comment]
Thank you, I solved it finally.
