### ISSUE TITLE
TextTheme.button doc is misleading

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#54343]
The `TextTheme.button` documentation says:

```
  /// Used for text on [RaisedButton] and [FlatButton].
  final TextStyle button;
```

But RaisedButton actually uses: 
```
textStyle: theme.textTheme.button.copyWith(color: buttonTheme.getTextColor(this)),
```

So the color of the text on a raised button does not actually come from TextTheme.button but from ButtonTheme.getTextColor, which is misleading.

The documentation should be updated to point out that everything but the color of the text style is used or the text style should just be used as assumed.

## Related

* https://stackoverflow.com/questions/56517959/flutter-change-all-raised-button-text-color-in-theme

**Comment by christian-muertz** [comment]
This leaves me with the question of how to actually set a custom theme wide text color for raised buttons? ButtonTheme.getTextColor returns either button.textColor, black or white. So if a want to define the text color red for all my raised buttons, I have to set the textColor for every button.

**Comment by christian-muertz** [comment]
Duplicate of https://github.com/flutter/flutter/issues/19623

**Comment by christian-muertz** [comment]
Reopening to discuss what the point of `textStyle: theme.textTheme.button.copyWith(color: buttonTheme.getTextColor(this))` is.

@HansMuller To make it not a breaking change I would suggest adding a ButtomThemeData.textColor and use it for ButtonTheme.getTextColor if present. In addition to that the documentation of TextTheme.button should be updated to point out that the color is overridden by ButtonTheme.getTextColor.

**Comment by markusaksli-nc** [comment]
Closing this due to https://github.com/flutter/flutter/pull/59702 being merged.
