### ISSUE TITLE
[proposal] [triage] Add "Browser Specific" Label

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#54357]
Hi all,
some Flutter Web issues appear to be specific to the browser
(Safari, Internet Explorer, Samsung Browser ...);
a `browser specific` might help to identify and search those issues
Thank you

**Comment by yjbanov** [comment]
We've been successful at simply searching for "firefox" and "safari". Does it not work for you?

**Comment by iapicca** [comment]
Hi @yjbanov 
my personal experience searching by keyword in Github isn't always positive,
finding it not always accurate or reliable;
if the suggested label is not useful for the team I'll close this issue.
Thanks

**Comment by ferhatb** [comment]
@iapicca , reviewed proposal, everyone agrees. Please feel free to add "browser: safari" etc.. for common browser issues being reported. Please don't use icon, makes it hard to search.

**Comment by iapicca** [comment]
@ferhatb 
I've just created labels for `safari` `firefox` and `ie`
thank you
