### ISSUE TITLE
Transparent bottomNavigationBar in Scaffold

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#54353]
Please fix the issue, that the bottomNavigationBar Widget cannot be transparent. 
To easily simulate, add margin on that Widget > displayed as grey color. 

I tried to set all the color properties in the `Theme` with `Colors.transparent`, but none of them works, that this widget is rendered transparent.

```
return Scaffold(
  body: Container(
    color: Colors.blue,
  ),
  bottomNavigationBar: Container(
    height: 100.0,
    color: Colors.red,
    margin: const EdgeInsets.only(top: 50.0),
  ),
);
```

Output:
![IMG_1511](https://user-images.githubusercontent.com/40127061/78894576-951dbf00-7a6d-11ea-8d03-6f431e01b414.PNG)

Expected would be only red and blue (margin should be transparent).

Flutter stable, v1.12.13+hotfix.9

**Comment by Zazo032** [comment]
You may be looking to add a top padding rather than top margin. If you're using a top margin, that margin is indeed _transparent_ (white), because it's outside of the red `Container`.

**Comment by YAPPDEF** [comment]
@Zazo032 padding is not wanted as this part should be transparent. If I add a padding, the whole bottomNavigation part will be red.

Another example without padding/margin:
The white/grey part should be transparent > blue from the underlying background

```
return Scaffold(
  body: Container(
    color: Colors.blue,
  ),
  bottomNavigationBar: Stack(
    alignment: Alignment.bottomCenter,
    children: <Widget>[
      Container(
        height: 100.0,
        color: Colors.red,
      ),
      Container(
        width: 100,
        height: 100,
        color: Colors.green,
        margin: EdgeInsets.only(bottom: 40.0),
      ),
    ],
  ),
);
```

![IMG_D704EAD311BC-1](https://user-images.githubusercontent.com/40127061/78896320-98ff1080-7a70-11ea-8628-830ec2cd5bdb.jpeg)

**Comment by Zazo032** [comment]
That's because of `Scaffold`'s logic, imagine it's like a `Column`, and `body` is placed above `bottomNavigationBar`.

**Comment by VladyslavBondarenko** [comment]
@YAPPDEF 
setting `backgroundColor` of `Scaffold` isn't your case as well?
you want to have `bottomNavigationBar` overlaying above the `body`?

**Comment by Zazo032** [comment]
If you use [Flutter Inspector](https://flutter.dev/docs/development/tools/devtools/inspector) you'll perfectly see what I mean.

**Comment by YAPPDEF** [comment]
Yes, I see. So there's no possibility to have an overlapping part in the bottomNavigationBar as it's implemented like a column?

**Comment by Zazo032** [comment]
You could also try using [`extendBody`](https://api.flutter.dev/flutter/material/Scaffold/extendBody.html) property, depending on the result you're trying to achieve.

**Comment by YAPPDEF** [comment]
@Zazo032 thanks, but it's wanted that the content stops above the bottom navigation. 

I solved it now with a `Stack` around the `Scaffold` and a bottom navigation placeholder (height without margin) inside the `Scaffold`. And above the `Scaffold` the "real" bottom navigation with the overlapping button.
That results in the same as within the `Scaffold` but with the transparent space around the button. Also scrolling is as wanted now 👍
