### ISSUE TITLE
Error in handling project

### ISSUE THREAD

**Issue by Hussain-786** [flutter/flutter#54365]
"Gradle task assembleDebug failed with exit code -1" how can i solve this error which is terminating without giving proper message that what has happen.I followed each and every step in insallation of android studio with flutter, please help me in solving this problem.

**Comment by iapicca** [comment]
Hi @Hussain-786 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
