### ISSUE TITLE
 The following assertion was thrown building _FocusMarker(dirty):

### ISSUE THREAD

**Issue by H-Mongo** [flutter/flutter#54360]
I don't know what happened. After suspending the APP in the background for a long time, I entered the APP again. After hot loading, the console prompted the following information. I am confused

I/flutter (29136): The following assertion was thrown building _FocusMarker(dirty):
I/flutter (29136): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4838 pos 14: '() {
I/flutter (29136):         // check that it really is our descendant
I/flutter (29136):         Element ancestor = dependent._parent;
I/flutter (29136):         while (ancestor != this && ancestor != null)
I/flutter (29136):           ancestor = ancestor._parent;
I/flutter (29136):         return ancestor == this;
I/flutter (29136):       }()': is not true.
I/flutter (29136):
I/flutter (29136): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (29136): more information in this error message to help you determine and fix the underlying cause.
I/flutter (29136): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (29136):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (29136):
I/flutter (29136): The relevant error-causing widget was:
I/flutter (29136):   MaterialApp file:///E:/graduationDesign/project/app_mobile/bju_information_app/lib/main.dart:41:20

**Comment by VladyslavBondarenko** [comment]
Hi @H-Mongo 
can you reproduce it?
would be helpful if you could post a complete minimal reproducible code sample together with your `flutter doctor -v`

**Comment by H-Mongo** [comment]
Now that abnormal information has been closed. The reason for the closure is not clear. thank you for your help!
