### ISSUE TITLE
Regression in nearly all hot_mode_dev_cycle_macos_target__benchmark benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54368]
See, for example, hotReloadMillisecondsToFrame.

Clear jump at https://github.com/flutter/flutter/pull/54132.

![Screen Shot 2020-04-09 at 9 14 10 AM](https://user-images.githubusercontent.com/1435716/78916558-8372f200-7a42-11ea-97d7-927ad710e8e9.png)

**Comment by kf6gpe** [comment]
This includes the relevant smoke_catalina_hot_mode_dev_cycle_ios__benchmark benchmarks, too.

**Comment by jonahwilliams** [comment]
I can't reproduce any performance regression locally. This might just be an issue with benchmark mode, taking a look

**Comment by jonahwilliams** [comment]
This is fixed!  The issue was that we started measuring hot reload time before the hot restart was finished. Thanks for the heads up @kf6gpe
