### ISSUE TITLE
Across the application, the screens do not have a title

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#54375]
@gspencergoog

Is it possible to set "android:accessibilityPaneTitle" from a Flutter application?

Consider setting "[title]" as a title using android:accessibilityPaneTitle. 
Refer to Android 9 API: https://developer.android.com/about/versions/pie/android-9.0

**Comment by gaaclarke** [comment]
The engine never makes reference to `accessibilityPaneTitle`.  When reading through the documentation it looks like it is helpful when swapping a fragment for a fragment in android's APIs.  How would you see that working with Flutter?

I think what would be most helpful is to write up the code as you think it should work.

**Comment by TahaTesser** [comment]
Hi @gmoraja 
Do you have more information and code as requested by the above comment?https://github.com/flutter/flutter/issues/54375#issuecomment-645008381 
To better address, the issue, please provide the details 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
