### ISSUE TITLE
Update Android SDK from 28 to 29 in new plugins and project templates

### ISSUE THREAD

**Issue by boskokg** [flutter/flutter#54382]
Currently `compileSdkVersion` and `targetSdkVersion` are 28. 
Plugins and a new project should use 29.

**Comment by jmagman** [comment]
From duplicate https://github.com/flutter/flutter/issues/62295:
> Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.

**Comment by jmagman** [comment]
\cc @xster @jonahwilliams @blasten  I guess we should do this sooner rather than later?  Not sure what the testing matrix would look like.

**Comment by blasten** [comment]
+1. Let's bump the version.  The net effect is that plugins would be able to use Android 10 features. (note they can do this manually already).  For apps, it isn't much of a gain since Flutter app developers usually don't write Java/Kotlin code in the app itself.

**Comment by xster** [comment]
Yes we missed the timeline and should do it now. 

@RedBrogdon @filiph I think we should also broadcast that API 29 (or higher) is needed to build Flutter 

<img width="1109" alt="Screen Shot 2020-08-03 at 11 14 01 AM" src="https://user-images.githubusercontent.com/156888/89214012-e0a72c00-d57a-11ea-8664-b555586a0f4b.png">
 
Though most users should already be on 29 if they installed Android Studio this year.

**Comment by xster** [comment]
@RedBrogdon @filiph actually disregard please. Gradle 2.2+ actually automatically downloads and installs new Android SDKs when not installed manually on the machine via the SDK manager when the compileSdkVersion exceeds the installed versions.

**Comment by xster** [comment]
gradle doesn't always cleanly install 29 automatically. Reopening

**Comment by xster** [comment]
Good callout from @blasten 
We should also change https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L28 for a catch either way.
