### ISSUE TITLE
Show error messages for connected iOS physical devices with error messages

### ISSUE THREAD

**Issue by xster** [flutter/flutter#54388]
Consider showing the locked but connected iOS devices from `flutter devices` output as well. (error code -14 from xcdevice list). 

In terms of UI, it could, for instance, show:

```
2 connected devices:

iPad (locked)  • 00008027-000A78E02E85002E • ios        • iOS 13.4
macOS • macOS                     • darwin-x64 • Mac OS X 10.15.4 19E287
```

Ergonomically, it would be useful for users to not scratch heads 'debugging' the connectivity issue. Sometimes it's especially not obvious if the screen is already on, such as when browsing the recently taken photos from the camera pre-unlock or when the iPad is running sidecar. It's seemingly on but not unlocked into springboard.

**Comment by jmagman** [comment]
This would be helpful for all unavailable tethered iOS devices, not just locked ones.

**Comment by xster** [comment]
^

Let's just generalize this to xcdevice list results for physical devices that has a "error" key and just show the "description" and "recoverySuggestion" or some such.
