### ISSUE TITLE
Add internet permissions to macOS entitlements by default

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#54390]
I'm finding it very tedious every time I create a new project for macOS to search online for the snippet
 <key>com.apple.security.network.client</key><true/> , 

since I can't remember it. We have internet access by default on other platforms, why is macOS different?

**Comment by stuartmorgan** [comment]
> We have internet access by default on other platforms

This is not the case; see https://flutter.dev/docs/deployment/android#reviewing-the-app-manifest and https://flutter.dev/docs/development/data-and-backend/networking#android.

If "other platforms" means iOS, iOS has no such permission. If it means Windows and Linux, currently neither of them are sandboxed.

The point of sandboxes with permissions systems is that applications should request only what they use. Adding entitlements by default defeats that goal. This will be documented (#52902), but not changed.

**Comment by ThinkDigitalSoftware** [comment]
Well, I'm used to developing on android and iOS without needing the permission. Are we focusing on ease of development or some other goal? Is it possible to have it commented out and sit there as a placeholder? There are commented out values in many other places, even in the iOS code, like specifying the target platform version that are easy to uncomment should the need arise. This solves both our issues.

On Apr 9, 2020 4:07 PM, stuartmorgan <notifications@github.com> wrote:

Closed #54390<https://github.com/flutter/flutter/issues/54390>.

**Comment by stuartmorgan** [comment]
> Are we focusing on ease of development or some other goal?

Application sandboxes are for end-user security, not developer convenience.

> Is it possible to have it commented out and sit there as a placeholder?

I'm not aware of any explicitly supported comment format for plists.
