### ISSUE TITLE
[proposal] mark classes constructors as const

### ISSUE THREAD

**Issue by rapPayne** [flutter/flutter#54399]
When writing a new class, a developer cannot mark their constructor as const if the superclass from which they are deriving doesn't have a const constructor. Certain classes in flutter are not marked as const. They should be const by default.  

The more widgets that are marked as const, the more likely performance improvements during render/re-render.

**Comment by goderbauer** [comment]
I am going to close this one since it is very broad. If there are specific classes that should be const, but aren't please file separate issues.
