### ISSUE TITLE
Put a timeout around call to "adb shell getprop ro.product.cpu.abi"

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5439]
## Steps to Reproduce
1. Run the same android emulator as me
2. `flutter devices`
   Observe the command never completes after output "1 connected device:"

The command I use to run the emulator looks something like: `aswb-sdk/tools/emulator -netdelay none -netspeed full -avd Nexus_5_API_N`
## Logs and Crash Reports

```
flutter (master)$ adb devices
List of devices attached 
emulator-5554   device

flutter (master)$ adb devices -l
List of devices attached 
emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64

flutter (master)$ flutter devices
1 connected device:

^C <-- me killing the process after a minute
```
## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/drewwarren/flutter
    • Framework revision e62bcefb5a (15 minutes ago), 2016-08-16 14:33:35
    • Engine revision 44a77da98a
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/users/drewwarren/aswb-sdk
    • Platform android-N, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-128173541-128170350)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

**Comment by eseidelGoogle** [comment]
FYI @devoncarew @jason-simmons

**Comment by Hixie** [comment]
Can you run with -v? It will give more verbose output which might be helpful.

**Comment by eseidelGoogle** [comment]
Presumably if we removed the ^C handler we'd get a stack trace for where the hang happens.  I'm not sure if we have a flag to disable that.  @devoncarew would know.

**Comment by drewwarren** [comment]
```
flutter (master)$ flutter devices -v
   3 ms • /usr/local/google/users/drewwarren/aswb-sdk/platform-tools/adb devices -l
   0 ms • Exit code 0 from: /usr/local/google/users/drewwarren/aswb-sdk/platform-tools/adb devices -l
   2 ms • List of devices attached
          emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
   0 ms • 1 connected device:
```

**Comment by devoncarew** [comment]
We install an signal handler for flutter run - it wouldn't be active for this case.

It looks like we can find the device but we hang when trying to print out information about it. It could be somewhere like here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L91, where we're trying to query adb for more data when listing devices.

**Comment by devoncarew** [comment]
It looks like this is one of the shell commands we don't log when we execute it (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L65); we should  change that.

**Comment by devoncarew** [comment]
@drewwarren, can you run `adb shell getprop ro.product.cpu.abi` locally and see if that completes?

**Comment by drewwarren** [comment]
1 minute and `adb shell getprop ro.product.cpu.abi` has not complete

**Comment by Hixie** [comment]
We should time out and show a message if `adb` doesn't return promptly.

**Comment by zoechi** [comment]
This is done https://github.com/flutter/flutter/blob/8426910a19abc4ab081c58fd1a72c433353eaa31/packages/flutter_tools/lib/src/android/android_device.dart#L98
