### ISSUE TITLE
Deprecate make-host-app-editable command

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54408]
The use of the `make-host-app-editable` command has been discouraged in the docs in favor of the tool owning the [`.android`](https://flutter.dev/docs/development/add-to-app/android/project-setup#create-a-flutter-module) and [`.ios`](https://flutter.dev/docs/development/add-to-app/ios/project-setup#module-organization) directories.  Custom platform code should be written as plugins or in the host app.

It's also not well tested, and has caused compatibility issues like https://github.com/flutter/flutter/issues/51097.

See also:
https://github.com/flutter/flutter/issues/32989
https://github.com/flutter/flutter/issues/52496
https://github.com/flutter/website/pull/3926
https://github.com/flutter/flutter/issues/23956#issuecomment-567254225

**Comment by jmagman** [comment]
@xster Not sure if this needs to be tracked separately from https://github.com/flutter/flutter/issues/32989.

**Comment by xster** [comment]
Now that it's been about a quarter since it's out there and we haven't heard of any blocker issues related to this, I'd close https://github.com/flutter/flutter/issues/32989 with this and add some documentations around https://github.com/flutter/flutter/issues/52496 once we remove this.

**Comment by jmagman** [comment]
To be removed in https://github.com/flutter/flutter/issues/59220.
