### ISSUE TITLE
flutter webView在选择的时候异常退出

### ISSUE THREAD

**Issue by ciscolxh** [flutter/flutter#54421]
@kangwang1988 请教一个问题

> 在Android中弹一个select选择框就会报错退出  看了一下网上 说是做一个全局的Context实现刚试了一下还是一点就报错

Transated by @chunhtai :

> If there is a web page with the selection dropdown hosted in a webview widget, tries to open the selection dropdown in a webview widget will cause the app to crash. This happens in android devices.

# Examples
```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MediaQuery.removePadding(
          context: context,
          child: Column(
            children: <Widget>[
              TitleWidget(
                titleName: '数据分析',
              ),
              Expanded(
                   child: WebView(
                    initialUrl: 'http://start.luokes.com:3344/chart.html',
                    javascriptMode: JavascriptMode.unrestricted,
                   
                  ),
              )
            ],
          )),
    );
  }
```
# errorMsg
```
D/MotionRecognitionManager(17434): mSContextService = com.samsung.android.hardware.context.ISemContextService$Stub$Proxy@eb9e69
D/MotionRecognitionManager(17434): motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@ccca0ee
D/MotionRecognitionManager(17434): motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@ccca0ee
W/System.err(17434): java.lang.ClassCastException: $Proxy0 cannot be cast to android.view.WindowManagerImpl
W/System.err(17434):    at android.view.Window.setWindowManager(Window.java:748)
W/System.err(17434):    at android.view.Window.setWindowManager(Window.java:729)
W/System.err(17434):    at android.app.Dialog.<init>(Dialog.java:220)
W/System.err(17434):    at android.app.AlertDialog.<init>(AlertDialog.java:200)
W/System.err(17434):    at android.app.AlertDialog$Builder.create(AlertDialog.java:1103)
W/System.err(17434):    at org.chromium.content.browser.input.SelectPopupDialog.<init>(SelectPopupDialog.java:13)
W/System.err(17434):    at org.chromium.content.browser.ContentViewCoreImpl.showSelectPopup(ContentViewCoreImpl.java:540)
W/System.err(17434):    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(17434):    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err(17434):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(17434):    at android.os.Looper.loop(Looper.java:154)
W/System.err(17434):    at android.app.ActivityThread.main(ActivityThread.java:6682)
W/System.err(17434):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(17434):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
W/System.err(17434):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
F/chromium(17434): [FATAL:jni_android.cc(232)] Please include Java exception stack in crash report
F/google-breakpad(18270): -----BEGIN BREAKPAD MICRODUMP-----
F/google-breakpad(18270): V AndroidWebView:64.0.3282.137
F/google-breakpad(18270): O A arm 08 armv8l samsung/zeroltedv/zerolte:7.0/NRD90M/G925IDVU4FRD1:user/release-keys
F/google-breakpad(18270): P webview
F/google-breakpad(18270): R 00000006 SIGABRT 0000441A

```

**Comment by kangwang1988** [comment]
@ciscolxh 
Paste the result for `flutter doctor -v` please.

**Comment by ciscolxh** [comment]
Flutter (Channel master, v1.13.6-pre.40, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.13.6-pre.40 at /Users/macman/flutterSDK/flutter
    • Framework revision 43a8c24344 (3 months ago), 2019-12-29 12:28:57 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/macman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270

**Comment by kangwang1988** [comment]
@ciscolxh 
Can you try the latest master branch to verify if this issue still occurs?

**Comment by ciscolxh** [comment]
@kangwang1988 
[✓] Flutter (Channel master, v1.18.0-5.0.pre.57, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
Flutter version1.18.0-5.0.pre.57 is ok!  Thank You.

**Comment by pppshiwen** [comment]
Same question！都是坑。。。

**Comment by tlueder** [comment]
Duplicated? https://github.com/flutter/flutter/issues/25767

**Comment by ciscolxh** [comment]
Flutter version1.18.0-5.0.pre.57 is ok!
