### ISSUE TITLE
[ios] Info.plist does not contain CFBundleVersion

### ISSUE THREAD

**Issue by zzljob** [flutter/flutter#54427]
## Command
```console
flutter run
```

## Logs
```bash
ProcessException: ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion.
  Command: /usr/bin/xcrun simctl install 9A403314-88E2-495A-9182-AB09C2B85719 /Users/qiaobo/Workspace/hangtian/rfid_app/build/ios/iphonesimulator/Runner.app

#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:29)
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:451:31)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:351:15)
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:a
```

**Comment by Oklahomawhore** [comment]
problem seems  quite obvious :"Failed to install the requested applicationThe application's Info.plist does not contain CFBundleVersion."

**Comment by iapicca** [comment]
Hi @zzljob 
there are issues that might contain a possible solution for your case
https://github.com/flutter/flutter/issues/40623 
https://github.com/flutter/flutter/issues/42383 
https://github.com/flutter/flutter/issues/48895 
https://github.com/flutter/flutter/issues/53539
https://github.com/flutter/flutter/issues/54427

if those don't fix the problem
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Hi @zzljob 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
