### ISSUE TITLE
Reverse Pop Route 

### ISSUE THREAD

**Issue by sashvoncurtis** [flutter/flutter#54436]
Hi, 

So...
```Navigator.pop(context))``` goes back to the previous page, however once on that page is it possible to then go back (forwards to the page that .pop was called on)? Would imagine something like a .pull(context)ish is doable as the state tree keeps history.

Pulling back from a pop would be useful for flipping in between pages when the route is unknown.
Looked around for documentation, did not find any.

Thanks

**Comment by chunhtai** [comment]
There is no way to restore the popped page, the page is disposed and no longer in memory. You have to push a new route again. What is the use cases you are trying to do?

**Comment by sashvoncurtis** [comment]
Hi @chunhtai,
Trying to get the effect of a browser, for back and forward, to switch between views, via a back < and forward > button,  if I open a view I can go back but  once  back I cannot return to the previous view via a forward button.  Similar to the default AppBar leading but with a forward trailing.

Using this to navigate between views of charts, where once on a view a new view can be shown by tapping a chart. 

Tried a solution where a view would have a wild card route like /view/:id and then caching the route name using route at index -1 to go forward, but wildcards isn't apart of the core Navigator.

Currently building for Web/Mobile/Unix :)

**Comment by chunhtai** [comment]
We are in the middle of designing a new router widget for web which will also take care of the forward and backward button for web. I am still not sure if i completely understand your use case, couldn't you cache the previous route name after you hit the back button and then push a new route with that route name when user hit forward button?

**Comment by sashvoncurtis** [comment]
Caching works with pre-defined routes, where the route name is const, your suggestion would work.
But as routes cant be declared on the fly, a route with view/:id cannot be known before hand and therefore declared as a route.

Will keep trying. Thanks!

**Comment by chunhtai** [comment]
Maybe a little bit of example code can describe your use case better. I am not sure what do you mean by `a route with view/:id`

**Comment by chunhtai** [comment]
Closing this issue as inactive

**Comment by sashvoncurtis** [comment]
Ended up using a Flutter package called Fluro. Forgot about  this, sorry for bad issue hygiene :)
