### ISSUE TITLE
Add toString() method for device_info plugin

### ISSUE THREAD

**Issue by deadsoul44** [flutter/flutter#54430]
It can be useful to add a toString() and toStringShort() methods for device_info plugin. Instead of getting the fields one by one, we can use these methods for quick information about the device.

**Comment by iapicca** [comment]
Hi @deadsoul44 
please remember that from Dart 2.6 you can write your own extensions if you want to 

```dart
extension Stringify on DeviceInfoPlugin {
  String stringify() {
     /// TODO
  }
}

```

**Comment by TimmyGunawan123** [comment]
Game Trend Nowadays..
You can play this game in https://joker123gaming.co to fill your sparetime during this coronavirus pandemic.

**Comment by aap88-afk** [comment]
Revert of #

**Comment by aap88-afk** [comment]
add string future

**Comment by aap88-afk** [comment]
Need to

**Comment by femisco** [comment]
I'd like to take this one on @iapicca

**Comment by catfishcrawler** [comment]
``extension Stringify on DeviceInfoPlugin {
  String stringify() {
     /// TODO
  }
}

**Comment by bharat-1809** [comment]
Can I work on this issue?

**Comment by Sameerkash** [comment]
@stuartmorgan I'd like to work on this, would overriding the `toString()` method in `AndroidDeviceInfo` and `IosDeviceInfo` be a valid fix?

**Comment by stuartmorgan** [comment]
@Sameerkash See https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note

**Comment by Sameerkash** [comment]
> @Sameerkash See https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note

Got it, so flutter/plugins will not be supported once plus plugins are completely ready for all the issues ? 

Because the doc mentions, " transition users" 

In any case, is the implantation I mentioned valid ?

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
