### ISSUE TITLE
iOS release build is 360MB with plugin

### ISSUE THREAD

**Issue by andymrob** [flutter/flutter#54440]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)

When I create a template app using "flutter create" and build with "flutter build iOS" then the iOS app size is around 25 MB which seems ok. But all I have to do is add a plugin in pubspec.yaml, e.g. "shared_preferences: ^0.5.6" or "url_launcher: ^5.4.2", and the release build balloons to 360 MB.

The issue also happens with hotfix 9.

I wondered whether it might be this:
https://github.com/flutter/flutter/issues/51904
but that's why I'm using hotfix 8 which pre-dates the issue raised there.

It seems to me that it should be very easy to reproduce this. Any help would be appreciated.

**Comment by andymrob** [comment]
BTW I am talking about the size of build/ios/iphoneos/Runner.app

If I do this:
tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa
then the result is 162 MB which is still pretty ridiculous.

**Comment by iapicca** [comment]
Hi @andymrob 
please note this [answer](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077)
and the possible solutions from this [issue](https://github.com/flutter/flutter/issues/50850)
do these steps fix the issue?
Thank you

**Comment by andymrob** [comment]
Thank you, I think this does fix it (or rather, reveal it not to be a problem).
I've tried doing an ad-hoc distribution and look at the sizes of the many variant ipa files produced, which in fact are each in the region of 15MB uncompressed, 6MB compressed. Which is fine.

**Comment by TahaTesser** [comment]
Hi @andymrob 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
