### ISSUE TITLE
 Web app unresponsive - Canvas area exceeds the maximum limit  iOS only

### ISSUE THREAD

**Issue by elborto** [flutter/flutter#54451]
## Steps to Reproduce
[Warning] Canvas area exceeds the maximum limit (width * height > 16777216). (main.dart.js, line 15869)

1. Navigate to  https://groceryapp-272003.web.app on an iPhone. 
2. The app is unresponsive
3. the console provides a warning [Warning] Canvas area exceeds the maximum limit (width * height > 16777216). (main.dart.js, line 15869)
4.  I expect it to work as it does on safari desktop, or androud chrome, or at least give me an erro on where to debug

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @elborto

**Comment by TahaTesser** [comment]
Hi @elborto 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
