### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle__benchmark hotReloadMillisecondsToFrame & hotReloadMillisecondsToFrame above baseline

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54456]
After the fix to https://github.com/flutter/flutter/issues/54368 in https://github.com/flutter/flutter/pull/54374, these benchmarks remain slightly above the baseline. Should we re-baseline them?

![Screen Shot 2020-04-10 at 8 56 11 AM](https://user-images.githubusercontent.com/1435716/79004222-27bf6c00-7b09-11ea-88ad-96c68f3be102.png)

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
I tried to rebaseline the benchmarks. I don't think there is an actual regression here, just a gradual increase

**Comment by jonahwilliams** [comment]
I think the website is still cached, I'll wait a bit to make sure these are still green.

**Comment by jonahwilliams** [comment]
All of the benchmarks have been re-baselined
