### ISSUE TITLE
Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: SomePath\Android\Sdk\platform-tools\adb.exe

### ISSUE THREAD

**Issue by SatarupaC** [flutter/flutter#54469]
Hi Team,

I am completely new to the flutter( android) project , I just wanted to try out and faced the error.

Issues and to reproduce:

1) Followed the guide on my windows 8.1 the guide https://flutter.dev/docs/get-started/install/windows.
2) On running flutter doctor:

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: somePath\Android\Sdk\platform-tools\adb.exe

3)On running flutter doctor -v 

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: C:\Users\pitki\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

4) I could not further run main.dart after launching the project and  on running the emulator button on Android studio got error  " No connected devices found; please connect a device, or see flutter.dev/setup for getting started instructions"

Tried workaround / Solutions:

Although I have tried looking for similar issues like https://github.com/flutter/flutter/issues/30772 and other links I feel it is always a reference of some link where I could not track the solution.

Any help would be appreciated.

**Comment by EngDjango** [comment]
add the path of "Android SDK" you downloaded to "environment variables" as "ANDROID_HOME";
also inside the sdk there is 2 folders "platform-tools" and "tools" => add their paths to "Path" in "environment variables";

**Comment by SatarupaC** [comment]
@EngDjango  I tried adding the path in the system environment variable still no luck. I am still facing the same error.

**Comment by zhaqiezi** [comment]
I have the same error.  I have try to reinstall Android Studio,  but it's still unresolved.

**Comment by EngDjango** [comment]
Again, There is 3 paths to add in "environment variables" not just "ANDROID_HOME" only... did you add the 3 of them?

**Comment by SatarupaC** [comment]
Yes, I have added system env variables ANDROID_HOME  = path for android sdk and in the path variable I have added both path to tools and path to platform-tools

**Comment by TahaTesser** [comment]
Hi @SatarupaC 
Can you reinstall your platform-tools?
Thank you

**Comment by SatarupaC** [comment]
@TahaTesser  I tried reinstalling but sadly it didn't work.

But I tried something below it did work

1. https://developer.android.com/studio/releases/platform-tools. I tried all the platform checking the platform tool. Looks like adb.exe 28.02 and above  needed some package upgrade from windows and the below  does the job
https://www.microsoft.com/en-us/download/details.aspx?id=49081

Thanks, everyone for helping me out!

**Comment by pratikshady** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/55526536/87244808-b1ab0800-c45d-11ea-8ed3-d1fed36e49f0.png)

**Comment by krrishkhedia** [comment]
Please update your windows and try again. It worked for me.

**Comment by sumeshsheoran** [comment]
please check your adb file is missing at Android/sdk/platform-tools solution is to download new platform tools and replace with current one https://developer.android.com/studio/releases/platform-tools
