### ISSUE TITLE
Flutter 1.17.0 won't build applications for an iOS 10 iPadv4

### ISSUE THREAD

**Issue by sowens-csd** [flutter/flutter#54477]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Connect an iPad 4th gen device
3. Open the project in VSCode
4. click F5 to build / debug on the device

**Expected results:** 
Application running on the device 

**Actual results:** 
An error message in the Debug Console as shown in the log section below. The application does not deploy or start on the device. It can be built from Xcode by opening the workspace directly. 
<details>
  <summary>Logs</summary>

```
Unknown architecture armv7s, defaulting to arm64
Launching lib/main.dart on Demo’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3X949YE9K2
Xcode build done.                                           10.9s
Installing and launching...
2020-04-10 15:15:27.829 ios-deploy[17099:165540] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not run build/ios/iphoneos/Runner.app on 3f70b7ca007abd2574c73c471c83eb4b166b2717.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                         5.6s
Error launching application on Demo’s iPad.
Exited (sigterm)
```

```
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.17.0 at /Users/xxx/Documents/dev/flutter/sdk/flutter
    • Framework revision d3ed9ec945 (4 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

⡿Unknown architecture armv7s, defaulting to arm64
[✓] Connected device (4 available)
    • Demo’s iPad             • 3f70b7ca007abd2574c73c471c83eb4b166b2717 • ios            • iOS 10.3.3
    • iPad - Folktells - 12.2 • DFE6808D-9E39-4DD3-A7A3-F7BB0EA9C3DC     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • Chrome                  • chrome                                   • web-javascript • Google Chrome 80.0.3987.163
    • Web Server              • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @sowens-csd 
can you please provide your `flutter run --verbose` by connecting iOS 10 iPadv4? 
Thank you

**Comment by sowens-csd** [comment]
Attached, let me know if I can do anything else. 

[runVerbose.log](https://github.com/flutter/flutter/files/4481126/runVerbose.log)

**Comment by TahaTesser** [comment]
Hi @sowens-csd 
Can you please try running from Xcode? Open iOS folder of your project in Xcode and go to Product -> Run
Thanks

**Comment by sowens-csd** [comment]
Yes, that works. The application runs properly on the same iPad.

**Comment by TahaTesser** [comment]
Hi @sowens-csd 
That's great, applications needs load necessary dependencies thus need Xcode run. 
if you run from command again after this, it should launch the app 
Please try `flutter run --verbose` and provide if crash 
Thank you

**Comment by sowens-csd** [comment]
I can still reproduce after a successful Xcode build. This time I piped it into a log. That log is attached. The only thing that went to error out is this:

➜  armv7sbug flutter run --verbose -d xxxxx >  buildAfterXCode.log
[   +7 ms] Unknown architecture armv7s, defaulting to arm64
[ +353 ms] 2020-04-15 09:51:41.454 ios-deploy[46992:3588487] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[   +1 ms] Could not run build/ios/iphoneos/Runner.app on 3f70b7ca007abd2574c73c471c83eb4b166b2717.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Error launching application on Demo’s iPad 4.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[buildAfterXCode.log]
(https://github.com/flutter/flutter/files/4481589/buildAfterXCode.log)

**Comment by edsonboldrini** [comment]
I'm experiencing the same bug with my iPhone 5C iOS 10.3.3

```
Unknown architecture armv7s, defaulting to arm64
Launching lib/main.dart on Dersalis iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: BU5344RS6Z
Xcode build done.                                           187.9s
Installing and launching...
2020-05-08 12:35:38.027 ios-deploy[16898:154185] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not run build/ios/iphoneos/Runner.app on 6193c0bfd48dda65b83297d84329f7eb24cf354f.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```

Running in Xcode works properly, but not in vscode with debug.

**Comment by jmagman** [comment]
@edsonboldrini What's the output of `flutter doctor -v`?
https://github.com/flutter/flutter/pull/54989 is available in [1.18.0-6.0.pre](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos).

**Comment by edsonboldrini** [comment]
Here is:
![image](https://user-images.githubusercontent.com/31242886/81433298-b7712e00-913a-11ea-883f-5e80d0b382f2.png)

**Comment by jmagman** [comment]
Got it.  You're on 1.17.0.  https://github.com/flutter/flutter/pull/54989 is fixed on [1.18.0-6.0.pre](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), which is available on the master and dev channels.  The fix will work its way through beta and eventually stable.

**Comment by edsonboldrini** [comment]
Ok, Thanks for the help, I will change my channel to test.

**Comment by edsonboldrini** [comment]
Still now works :(
but the error changes...
```
Xcode build done.                                           555.5s
Installing and launching...
2020-05-08 22:15:59.460 ios-deploy[81628:732671] [ !! ] Error 0xe800002d: Could not send a message to the device. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not run build/ios/iphoneos/Runner.app on 6193c0bfd48dda65b83297d84329f7eb24cf354f.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                        45.2s
Error launching application on Dersalis iPhone.
Exited (sigterm)
```

**Comment by jmagman** [comment]
@edsonboldrini Looks like some other issue deploying to that device.  When you follow the instructions and Run in Xcode, do you see any errors?

**Comment by edsonboldrini** [comment]
No error when I try build using xcode

**Comment by jmagman** [comment]
I'm going to close this as I believe the `armv7s` issue is resolved and the app now builds.  Could you file a new issue for your "Could not send a message to the device" problem and completely fill out the template?

**Comment by edsonboldrini** [comment]
Yes I can!

**Comment by irineusturza** [comment]
Hello @edsonboldrini. Could you send me the link for your "Could not send a message to the device" issue?

I have the same problem.

Only when if i run in vscode or android studio.
Xcode build works ok.

Thanks in advance


`2020-06-22 14:44:47.939 ios-deploy[27150:4542408] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not run build/ios/iphoneos/Runner.app on 0901c81e500a5b84aa87082129e0b3328811b035.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace`

**Comment by irineusturza** [comment]
Sorry. @jmagman post fix my problem. 1.18.0-6.0.pre
Thank you all!

**Comment by CareF** [comment]
> Still now works :(
> @jmagman but the error changes...
> 
> ```
> Xcode build done.                                           555.5s
> Installing and launching...
> 2020-05-08 22:15:59.460 ios-deploy[81628:732671] [ !! ] Error 0xe800002d: Could not send a message to the device. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
> Could not run build/ios/iphoneos/Runner.app on 6193c0bfd48dda65b83297d84329f7eb24cf354f.
> Try launching Xcode and selecting "Product > Run" to fix the problem:
>   open ios/Runner.xcworkspace
> 
> Installing and launching...                                        45.2s
> Error launching application on Dersalis iPhone.
> Exited (sigterm)
> ```

For future readers who find here for similar error message, I solved this by restart the device and the computer.
