### ISSUE TITLE
Force local runs of devicelab tests to use `en_US` locale

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54475]
Devicelab tests fail locally if the terminal locale isn't set to `en_US` (`export LANG=en_US.UTF-8`).

Updated instructions in https://github.com/flutter/flutter/wiki/Running-and-writing-tests#running-device-lab-tests-locally but it would be better if the tests handled forcing the locale.
See https://github.com/flutter/flutter/pull/51126#issuecomment-612061218.

**Comment by christopherfujino** [comment]
Also, I didn't know about that wiki page, there are also instructions to running these in the README: https://github.com/flutter/flutter/tree/master/dev/devicelab.

**Comment by digiter** [comment]
Triage: there is a todo to add a health check.

**Comment by godofredoc** [comment]
@keyonghan seems like a good candidate for a health check

**Comment by jmagman** [comment]
I was suggesting the test runner itself add it instead of the CI environment needing to know anything about the required locale.

Something like
```dart
 environment: <String, String>{ 
  'LANG': 'en_US.UTF-8',
   if (deviceId != null) 
     DeviceIdEnvName: deviceId, 
 }, 
```
https://github.com/flutter/flutter/blob/78cbfbff4267643bb1913bc820f5ce8a3e591b40/dev/devicelab/lib/framework/runner.dart#L46-L49
