### ISSUE TITLE
Navigator.popAndPushNamed and Navigator.pushReplacementNamed should behave the same, but when using a Drawer widget to navigate, it behaves differently.

### ISSUE THREAD

**Issue by officer47p** [flutter/flutter#54487]
## The Problem:
Navigator.popAndPushNamed and Navigator.pushReplacementNamed should behave the same, the only difference based on documentation is the animation that they show, but when using a Drawer widget to navigate, they behave differently.

Let me explain it in a better way:

## Better Explanation:
I have 3 files in my lib folder:
**1. main.dart
2. home_screen.dart
3. second_screen.dart**

In the main.dart file I have my typical MaterialApp widget. Inside it, I have my routes and my initial route, the routes are "/" and "/second".
in the root route("/") I have a Scaffold with a drawer widget. in the Drawer Widget, I only have a RaisedButton which Navigates to the "/second" route using popAndPushNamed, and in the body of the scaffold, I have the same button which also navigates to the "/second" route using the same popAndPushNamed method.
When I tap on the button which is inside the body of the scaffold, it does what it supposed to does(poping the current route and pushing the given route to the stack) so when I go the second screen, I don't see the default back button in the app bar. **BUT**, when I tap on the button inside the drawer of the scaffold, It navigates to the "/second" route, but it doesn't pop the last route, so I can see the default back button in the app bar.

FYI, I don't have this problem using the pushReplacementNamed method, but I would love to have this bug fixed, or maybe somebody explains to me why I face this behavior.
 
You may also think that the Drawer is a route itself (which is true, and you can close it using the pop method). in that way, we should also have this problem with the pushReplacementNamed method. I mean when the drawer is open, the current route is the drawer, so pushReplacementNamed should remove it and add the new route, but it hasn't popped the "/" route so we still can see the default back button in the app bar, but this scenario doesn't happen.

### These are the containing code inside each of the files:
**1. main.dart**
```
import 'package:flutter/material.dart';

import './second_screen.dart';
import './home_Screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "My Cool App",
      initialRoute: "/",
      routes: {
        "/": (ctx) => HomeScreen(),
        "/second": (ctx) => SecondScreen(),
      },
    );
  }
}
```

**2. home_screen.dart**
```
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home Screen"),
      ),
      drawer: Drawer(
        child: SafeArea(
          child: Column(
            // crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text("Go To Second Screen"),
                onPressed: () {
                  Navigator.of(context).popAndPushNamed("/second");
                },
              ),
            ],
          ),
        ),
      ),
      body: Center(
        child: RaisedButton(
          child: Text("Go To Second Screen"),
          onPressed: () {
            Navigator.of(context).popAndPushNamed("/second");
            // Navigator.of(context).pushReplacementNamed("/second");
          },
        ),
      ),
    );
  }
}

```
**3. second_screen.dart**
```
import 'package:flutter/material.dart';

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
          child: RaisedButton(
        child: Text("Back To Home Screen"),
        onPressed: () {
          Navigator.of(context).pop();
        },
      )),
    );
  }
}

```
## Flutter Doctor Output:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.44.0)
[√] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @officer47p 
Th isn't issue at all, when navigate from `HomeScreen` to `SecondScreen` using `popAndPushNamed`, it pops the `HomeScreen` but when do it from drawer, it pops drawer (just like you can add simple `Navigator.pop`) and then it pushes to `SecondScreen` without popping  `HomeScreen` because `popAndPushNamed` was called inside drawer, it only popped the drawer and not `HomeScreen`

just like this
```
     drawer: Drawer(
        child: SafeArea(
          child: Column(
            // crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text("Close Drawer"),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          ),
        ),
      ),
```

Thank you

**Comment by officer47p** [comment]
Thank you, so what's the difference between the mechanisms of popAndPush and pushReplacement?
 I know that popAndPush pops the current route and pushes a new one, but isn't it the same way that pushReplacement would work?

**Comment by TahaTesser** [comment]
Hi @officer47p 
Please check this [article](https://medium.com/flutter-community/flutter-push-pop-push-1bb718b13c31) for more detail

<img width="693" alt="Screenshot 2020-04-21 at 5 06 33 PM" src="https://user-images.githubusercontent.com/48603081/79861753-81ba0e80-83f2-11ea-84f3-af6620f0eb33.png">


Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen i
Thank you
