### ISSUE TITLE
Create infra for temporarily whitelisting framework/test lints

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#54482]
A not infrequent source of roll blockages is improvements to linters. When these happen to be lints that we enforce in our analysis_options.yaml, they can uncover existing code with issues either in the framework or in user-contributed tests registered in the https://github.com/flutter/tests repo.

Blocking the engine to framework roll in such cases has a few problems:
* Puts the burden of fixing these issues on the person managing the roll
* May have high latency on landing fixes to user-contributed code registered in the flutter/tests repo
* No actual regression is being introduced by the roll, an existing issue is being uncovered

We should be able to deal with these issues in a more scalable way. One option would be an analysis whitelist wherein files can be registered as temporarily exempt from a particular lint. This allows the roll to proceed and the fixes can be sharded out into however many patches are necessary to get them all fixed. 

If we take this approach, we likely need the following additional test changes in order to ensure the list gets whittled down over time:
* A benchmark that tracks the number of files whitelisted. This benchmark should be permanently baselined at 0 and be red if it ever goes over 0. This could also be integrated as a signal in the tech debt benchmark, but it needs its own benchmark that'll immediately go red when files are in the list.
* The analysis test should fail if a whitelisted file has no applicable whitelisted lint in it.

**Comment by Hixie** [comment]
Would we be whitelisting files in the customer_testing shard?

**Comment by Hixie** [comment]
Proposal:
* Have a file in dev/customer_testing that enumerates lints to ignore. They should include the name of the .test file in question, the hash of the commit in that file, the file name, line number, column number, and lint code for each lint to ignore.
* Have the customer testing shard set an environment variable that points to this file
* Have the analyzer read the file if specified in an environment variable, and not fail when specified lints are found (but do fail if specified lints are missing!).

**Comment by godofredoc** [comment]
Obsolete
