### ISSUE TITLE
Automatically write SkSLs with --cache-sksl flag

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#54484]
Instead of asking developer to manually press "M" during a `flutter run`, sometimes it's more ergonomic to automatically write SkSLs by the end of `flutter run` or `flutter drive` when `--cache-sksl` is provided.

The new workflow also makes it less likely to receive an empty set of SkSLs as `--cache-sksl` is required.

The old workflow would still be useful if developers aren't sure how to trigger a shader compilation so they can do something and press "M" iteratively.

Finally, the new workflow makes it easier for CI tests since they don't have to simulate a "M" key press.

**Comment by liyuqian** [comment]
@jonahwilliams : how do you think about this?

**Comment by liyuqian** [comment]
Discussed with Jonah offline:
> Jonah: The drive command is not currently staffed.
> Yuqian: For now just supporting automatically writing on exit in `flutter run` is good enough to make a CI test. I have an experimental implementation which works with `d` (detach) but throws exception with `q` (quit). The implementation is simply adding the following after `runner.run`:
```
    if (cacheSkSL && runner.supportsWriteSkSL) {
      await runner.writeSkSL();
    }
```

**Comment by jonahwilliams** [comment]
I'm un-assigning myself because I'm not working on this immediately

**Comment by jonahwilliams** [comment]
This should be easier to do now that there is a service extension method to do so. @liyuqian is there any signal the tool can use to know that it is safe to call this method? That is, it will be guaranteed to return something?

**Comment by liyuqian** [comment]
Thanks @jonahwilliams ! I'm currently drowning in the engine sheriff duty... I'll try it after Tuesday once I'm no long the sheriff :)

**Comment by liyuqian** [comment]
@jonahwilliams : how about using the signal of quit (`q`) in `flutter run`, or the finish of `flutter drive` as a signal that SkSLs are ready to be pulled? It would be very rare if `flutter run --cache-sksl` or `flutter drive --cache-sksl` didn't have any SkSL shaders to be pulled by that time.
