### ISSUE TITLE
Viewing build logs should not require a @google.com address

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#54509]
When clicking a "OPEN LOG FOR ATTEMPT #X" button on the build dashboard, you are taken to the Google Cloud Console to view the logs. Unfortunately, it only allows contributors with @google.com addresses to view the logs.

"DOWNLOAD ALL LOGS" work though.

/cc @CaseyHillers

**Comment by digiter** [comment]
Triage: we probably will remove stackdriver logs in the future.

**Comment by godofredoc** [comment]
Closing as obsolete now the logs are available to anyone in luci tasks.
