### ISSUE TITLE
Clone ocmock for ios unit tests

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#54503]
relevant file //flutter/shell/platform/darwin/ios/BUILD.gn

We might not have to clone it on our own because it exists at https://chromium.googlesource.com/chromium/src/+/master/third_party/ocmock

That build file builds a source_set though and we need a static_library.  We might be able to make a static_library based on the source_set.

Optionally we can keep an external BUILD.gn if we put ocmock's in `//build/secondary/third_party/ocmock/BUILD.gn`.

**Comment by gaaclarke** [comment]
Unfortunately https://chromium.googlesource.com/chromium/src/+/master/third_party/ocmock isn't a repo, the repo is all the code for chromium.  There doesn't seem to be a way to just pull down a subdirectory in gclient while it seems hypothetically possible with git: https://stackoverflow.com/a/52269934

**Comment by xster** [comment]
ah I see. Ya, that makes it trickier. https://stackoverflow.com/a/60729017/167638 works too but yes, it takes away from the convenience of the option.
