### ISSUE TITLE
showDatePicker should take the "current date" as an argument

### ISSUE THREAD

**Issue by kazume** [flutter/flutter#54526]
When showing a DatePicker via the [showDatePicker function](https://api.flutter.dev/flutter/material/showDatePicker.html) it doesn't seem possible to influence the _current day_ (give it a different time zone for instance).

I'm in need of a DatePickerDialog that's completely handled in UTC (for aviation), ignoring the phone's current time zone.

Example:

My phone is set to CET and it's 07-APR-2020 00:30 CET, which without DST is 06-APR-2020 23:30 UTC. I've managed to show the currently selected date on the 6th by using the showDatePicker() function like this:

`showDatePicker(context: context, initialDate: DateTime.now().toUtc(), firstDate: DateTime.now().toUtc().subtract(Duration(days: 365)), lastDate: DateTime.now().toUtc().add(Duration(days: 90)));`

but the "current date" in the DayPicker is still in CET, demonstrated in this picture:

<img width="235" alt="SDP" src="https://user-images.githubusercontent.com/15020377/79038671-6e7d9680-7bdb-11ea-920f-ec953fd16ea2.png">

flutter doctor:
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-AT)
    • Flutter version 1.12.13+hotfix.9 at /Users/egon/Development/flutter
    • Framework revision f139b11009 (11 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/egon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 8 Plus             • CDFA08C8-A665-4EC3-9D19-20AED09E74F1 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone 11 Pro Max         • 0E1F51E2-A165-4F9D-8B11-99644661E773 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by kazume** [comment]
That was fast! :)
