### ISSUE TITLE
flutter: Another exception was thrown: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by citdevs** [flutter/flutter#54523]
**What happend with RangError:**

**1. My Model:**
class Sliderapi {
  int id;
  String text1;
  String text2;
  String text3;
  String img;
  String link;
  int del;
  String createdAt;
  String updatedAt;

  Sliderapi(
      {this.id,
        this.text1,
        this.text2,
        this.text3,
        this.img,
        this.link,
        this.del,
        this.createdAt,
        this.updatedAt});

  Sliderapi.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    text1 = json['text1'];
    text2 = json['text2'];
    text3 = json['text3'];
    img = json['img'];
    link = json['link'];
    del = json['del'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['text1'] = this.text1;
    data['text2'] = this.text2;
    data['text3'] = this.text3;
    data['img'] = this.img;
    data['link'] = this.link;
    data['del'] = this.del;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

**2. My View Page:**
  
List<ServiceApi> serviceapi = [];
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    loadSliderData();
  }

  loadSliderData() async{
    var url = "http://citgroup.la/api/slide";
    var response = await http.get(url);
    var jsonString = json.decode(response.body);

    setState(() {
      jsonString.forEach((sl){
        final slider = Sliderapi.fromJson(sl);
        sliderapi.add(slider);
      });
    });
  }

**3. My Widget:**

Widget carousel_slider = Container(
      child: CarouselSlider.builder(
        height: 200,
        autoPlay: true,
        enlargeCenterPage: true,
        itemCount: sliderapi.length,
        itemBuilder: (context, i) => Container(
          child: Card(
            child: Container(
              decoration: BoxDecoration(
              ),
              child: Image.network('http://citgroup.la/${sliderapi[i].img}'),
            ),
          ),
        ),
      ),
    );

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
