### ISSUE TITLE
[WEB] IOS doesn't respond to touch events in normal mode

### ISSUE THREAD

**Issue by oscarlindenbaum** [flutter/flutter#54537]
## Steps to Reproduce

Load Flutter application in web mode, visit page on ios. 
 
**Expected results:** Touch events to be responded to. Works on android

**Actual results:** Events won't register unless the user specifically requests the 'desktop' version of the page.

<details>
  <summary>Logs</summary>

Same logs as #54192
</details>

**Comment by kunit1** [comment]
I think this issue is fixed on the latest master. Try with the latest flutter master version

**Comment by oscarlindenbaum** [comment]
> I think this issue is fixed on the latest master. Try with the latest flutter master version
> 
> 

Ah that’s great, rebuilt and it works perfectly. What broke it?

**Comment by TahaTesser** [comment]
Hi @oscarlindenbaum 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
