### ISSUE TITLE
I keep getting the error of android toolchain and Android sdkmanager tool not found 

### ISSUE THREAD

**Issue by CodeKazuko** [flutter/flutter#54539]
I use 'flutter doctor' and it comes out with this error.

Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

Then I use 'flutter doctor --android-licenses' and I keep uninstalling and reinstalling android studio at least 5 times. Which sdk tools is actually necessary for flutter to work? Did I link the SDK wrongly?

Android sdkmanager tool not found (C:\Users\hille\AppData\Local\Android\sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

By the way, when I try to run my project, it cannot find runner in main.dart. What does it mean?

**Comment by tharindu96** [comment]
I have the same issue, it seems to be that flutter is looking for the sdkmanager at the wrong location.

Trying: D:\Softwares\Android\Sdk\tools\bin\sdkmanager
Actual Location: D:\Softwares\Android\Sdk\cmdline-tools\latest\bin\sdkmanager

Hope this helps!

**Comment by tharindu96** [comment]
> I have the same issue, it seems to be that flutter is looking for the sdkmanager at the wrong location.
> 
> Trying: D:\Softwares\Android\Sdk\tools\bin\sdkmanager
> Actual Location: D:\Softwares\Android\Sdk\cmdline-tools\latest\bin\sdkmanager
> 
> Hope this helps!

Actually found the solution, it's there on the [flutter installation](https://flutter.dev/docs/get-started/install/windows#install-android-studio) page.

**Comment by Stephyo** [comment]
I have the same issues.
When running android studio, go to config SDK Manager and uncheck hide Hide Obsolete Package below.

**Comment by CodeKazuko** [comment]
I already have that option.

**Comment by CodeKazuko** [comment]
I manage to fix it! Apparently SDK manager is also missing despite re-downloading so many times ==


If can't see SDK tools in your SDK manager in your Android Studio

Please download it manually from https://developer.android.com/studio
Open link and scroll the all way down until you see Command line tools only
Download Windows Zip if you're on Windows and extract this zip and paste the tools in your SDK 

Then open Android Studio and go to Android SDK >SDK Tool(second tab), uncheck obsolete packages and download Android SDK Tool(Obsolete). 

Thank you all for the help! XD
