### ISSUE TITLE
Can I run venila javascript or jquery in flutter mobile app

### ISSUE THREAD

**Issue by anandarch** [flutter/flutter#54549]

**Comment by anandarch** [comment]
$("#tbtxt1").val("Symptom Default Text");

$("#ddlWorkgroup").change(function() {
  alert( "Workgroup is changed." );
  $("#tbtxt1").val('Selected Workgroup: '+$("#ddlWorkgroup option:selected").text());
});

Something like this,

**Comment by jonahwilliams** [comment]
Flutter on mobile does not use JavaScript, so you cannot use JavaScript libraries.
