### ISSUE TITLE
Flutter: It looks like pub.dartlang.org is having some trouble.

### ISSUE THREAD

**Issue by Nurullah-Sadekin** [flutter/flutter#54544]
I am trying to add HTTP and html Dependency  But pub get isn't working properly ,
Massage Shown in the  Description.

![image](https://user-images.githubusercontent.com/60127268/79048382-90f4cb80-7c3e-11ea-9c1e-74e68586ec13.png)

**Comment by jonahwilliams** [comment]
Please file issues for pub at https://github.com/dart-lang/pub

**Comment by Nurullah-Sadekin** [comment]
Still Says command not found
