### ISSUE TITLE
[proposal] camera plugin to support flash on/off

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#54548]
camera plugin to support flash on/off

**Comment by iapicca** [comment]
Hi @kw2019ltd 
are the many third party plugins ([torch](https://pub.dev/packages/torch),[flashlight](https://pub.dev/packages/flashlight), [lamp](https://pub.dev/packages/lamp)...) not sufficient for your needs?
Thank you

**Comment by kw2019ltd** [comment]
those plugins has issues many users reported its working on some devices and some devices not.

we need solution from flutter team to support flash on camera plugin

**Comment by iapicca** [comment]
Hi @kw2019ltd 
as mentioned above 
there's an open [issue](https://github.com/flutter/flutter/issues/19845) addressing the case you described.
Please follow up on that issue.
Thank you
