### ISSUE TITLE
Tabs and Scrolling demo gets confused about its scroll position

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5454]
https://youtu.be/FTdueveNWWQ

@HansMuller 

flutter/flutter version a8369413e47c41ffcb7c1884cf9dfe40af027fa3

[✓] Flutter (on Mac OS, channel master) • Flutter at /src/flutter • Framework revision cc201f0b1a (12 days ago), 2016-08-05 09:06:32 • Engine revision 44a77da98a • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2) • Android SDK at /Users/eseidel/Library/Android/sdk • Platform android-23, build-tools 23.0.2 • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1) • XCode at /Applications/Xcode.app/Contents/Developer • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter • flutter plugin version 0.2.4 • dartlang plugin version 0.6.35

**Comment by HansMuller** [comment]
In addition to the gratuitous scrolling, one of the tab views is disappearing as you page left and right.  If you drag a little and let the tab settle back to where it was, the tab view disappears for good.
