### ISSUE TITLE
"zsh: operation not permitted: flutter"

### ISSUE THREAD

**Issue by atharvjairath** [flutter/flutter#54553]
## Steps to Reproduce

1. charged the terminal to zsh and made new zprofile  through touch 
2.then i used vim .zprofile and added this variable-  export PATH="$PATH:/Users/atharvjairath/Developer/flutter/bin"
3. Now when i run flutter i get this error "zsh: operation not permitted: flutter"

## Logs

```"zsh: operation not permitted: flutter"
```

```"zsh: operation not permitted: flutter"
```

**Comment by atharvjairath** [comment]
I have also tried it in "vim .zshrc" and bash_profile 
Please Help!!!!

**Comment by satvikpendem** [comment]
At the end of `~/.zshrc` did you add `export ~/.zprofile`? For some reason, sometimes `~/.zprofile` isn't automatically sourced.

**Comment by atharvjairath** [comment]
> At the end of `~/.zshrc` did you add `source ~/.zprofile`? For some reason, sometimes `~/.zprofile` isn't automatically sourced.

Can you elaborate?. Where do i need to add  source ~/.zprofile?  in Vim.zshrc?

**Comment by satvikpendem** [comment]
At the end of `~/.zshrc`

**Comment by atharvjairath** [comment]
> At the end of `~/.zshrc`

Tried. Same error. Could you look at this problem through TeamViewer and help a noob out XD, I actually want to learn flutter for a Hackathon. I require immediate assistance!
my Gmail: atharv.jairath@gmail.com
