### ISSUE TITLE
[web]: Text.maxLines property doesn't work

### ISSUE THREAD

**Issue by bb-ac** [flutter/flutter#54554]
```
Text( 
  "text",
   maxLines: 3,
  overflow: TextOverflow.ellipsis,
)
```

The code above produces 1 line of text in the browser (and 3 lines of text as expected on mobile devices)

**Comment by imeDevelopers** [comment]
i think you have to use TextField() to be able to edit the text, if you need const text you can use (\n) between the text to break the line .. , for example:

Text("My first Line\nMy Second Line");

**Comment by bb-ac** [comment]
@imeDevelopers I don't need to edit the text. I want the widget to use up to 3 lines to show long text

**Comment by xpsuper** [comment]
maxLines with out overflow will done, but when more than maxLines, the text widget view abnormal, the last line just view a half

**Comment by TahaTesser** [comment]
### Web

<img width="505" alt="Screenshot 2020-04-13 at 5 25 20 PM" src="https://user-images.githubusercontent.com/48603081/79118565-ea2e3d80-7dab-11ea-9c39-ae83e284f59a.png">

### Mobile

![flutter_01](https://user-images.githubusercontent.com/48603081/79118678-25c90780-7dac-11ea-85eb-1a24c8b9d5ad.png)

Relate to [#43206](https://github.com/flutter/flutter/issues/43206)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/taha/Code/flutter_beta
    • Framework revision d3ed9ec945 (7 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (3 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by imeDevelopers** [comment]
@bb-ac 
put it inside Container() or SizedBox() with (width) parameter and it should work fine ..

**Comment by mdebbar** [comment]
This is fixed behind an experimental flag. Please look at [this issue](https://github.com/flutter/flutter/issues/33523) for more details on how to enable the flag locally.
