### ISSUE TITLE
[MIGRATED PROJECT] Failed to find assets path for "Frameworks/App.framework/flutter_assets"

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#54558]
As per https://github.com/flutter/flutter/issues/52084#issuecomment-600768772, I checked the iOS project and confirmed that neither the App.framework nor the Flutter.framework are listed anywhere.

Still, the app fails to launch and I see the quoted message in the command line output.

Here is my doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-DE)
    • Flutter version 1.12.13+hotfix.9 at
      /Users/.../development/flutter
    • Framework revision f139b11009 (12 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
```

The app launches just fine when I switch to beta.

EDIT: I now also tried deleting the "ios" directory, run `flutter create .` on beta, switch back to stable and build again. Same behavior, app won't launch

**Comment by pojoba02** [comment]
Please any update on how to resolved this issue.

**Comment by brighthawk** [comment]
This helped me: [https://i.stack.imgur.com/LH5RX.png](https://i.stack.imgur.com/LH5RX.png)

**Comment by rajeevjaiswal** [comment]
Any update on this will be helpful

**Comment by rajeevjaiswal** [comment]
It is still giving the same error in flutter 1.1.17 stable version

**Comment by jmagman** [comment]
Sorry this one was lost in the shuffle.  It sounds like automatic migration that was supposed to do https://flutter.dev/docs/development/ios-project-migration failed.  Could you go through those steps and confirm this fixes your issue?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by Da-Vinci10** [comment]
So what we suppose do to solve it?!!!

**Comment by TahaTesser** [comment]
@Da-Vinci10 
Please check https://github.com/flutter/flutter/issues/54558#issuecomment-675764365
If you're still experiencing this, please file a new issue
