### ISSUE TITLE
iOS x firebase_Auth error with flutter runtime 

### ISSUE THREAD

**Issue by razanalsallumi** [flutter/flutter#54569]
I have this problem with drumming my flutter app using iOS emulator 
![Screen Shot 2020-04-12 at 3 21 38 AM](https://user-images.githubusercontent.com/46599059/79057691-bac4e700-7c6c-11ea-8101-e68628544394.png)

**Comment by TahaTesser** [comment]
Hi @razanalsallumi 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by razanalsallumi** [comment]
> Hi @razanalsallumi
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

I solved this problem with create new project and reconnected with firebase and copy everything in old project. At the end, I installed Pod files in iOS my project path. 

thank you

**Comment by TahaTesser** [comment]
Hi @razanalsallumi 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
