### ISSUE TITLE
Migrate existing android/settings.gradle to the new file.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#54566]
`android/settings.gradle` will be changed after https://github.com/flutter/flutter/pull/54407 is merged:

```diff
include ':app'

-def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
+def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
+def properties = new Properties()

-def plugins = new Properties()
-def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
-if (pluginsFile.exists()) {
-    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
-}
+assert localPropertiesFile.exists()
+localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

-plugins.each { name, path ->
-    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
-    include ":$name"
-    project(":$name").projectDir = pluginDirectory
-}
+def flutterSdkPath = properties.getProperty("flutter.sdk")
+assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
+apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

This could be handled by `flutter migrate` in https://github.com/flutter/flutter/issues/40460.

**Comment by Gustl22** [comment]
As migration by the tool is not planned we might need to upgrade it manually by prompting the user: https://github.com/Gustl22/flutter/tree/54566-settings-gradle-migration

**Comment by Gustl22** [comment]
This issue may is obsolete due to #135392 which covers this case. I doubt someone will implement another migration (than the manual docs), if we also don't plan to do this for more recent versions of `settings.gradle`.

**Comment by jmagman** [comment]
@reidbaker can this be closed then?

**Comment by bartekpacia** [comment]
I agree with @Gustl22, writing a migration tool to automatically migrate `.gradle` files in infeasible since these files basically contain executable code.

Such a tool would only work for the most basic apps that didn't edit their Android buildfiles.
