### ISSUE TITLE
[!] Your app isn't using AndroidX.     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

### ISSUE THREAD

**Issue by Ajay-GLC** [flutter/flutter#54572]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @Ajay-GLC 
Please follow this [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
