### ISSUE TITLE
Bots should test upgrade path

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5457]
Right now the bots seem to only test the clean install path.

We should make sure that the following two paths result in identical on-disk bits:
1. checkout the current master, build flutter gallery.
2. checkout the alpha branch, build flutter gallery, then checkout the master branch on top of it, and build flutter gallery.

**Comment by eseidelGoogle** [comment]
I'm not sure this is a very useful bug to track.  We don't yet have releases.
