### ISSUE TITLE
Swift plugin cannot use dependency that doesn't implement modules

### ISSUE THREAD

**Issue by mitchross** [flutter/flutter#54574]
## Steps to Reproduce

1. Create a Swift Flutter Plugin 
1.1 flutter create --template=plugin -i swift -a java hello 
2. Add a Objective-C based dependency in the podspec
<img width="843" alt="Screen Shot 2020-04-11 at 11 15 35 PM" src="https://user-images.githubusercontent.com/6330506/79059730-79700f80-7c4b-11ea-9a23-4457f2da1c16.png">
3. Import Objective-c dependency.
<img width="732" alt="Screen Shot 2020-04-11 at 11 24 19 PM" src="https://user-images.githubusercontent.com/6330506/79059744-a4f2fa00-7c4b-11ea-831d-c177f6722dae.png">
4.  [NOTE] Work around to make Objective-C plugin work.
<img width="463" alt="Screen Shot 2020-04-11 at 11 15 26 PM" src="https://user-images.githubusercontent.com/6330506/79059764-d2d83e80-7c4b-11ea-9dcd-bc80ebea6b8d.png">
<img width="890" alt="Screen Shot 2020-04-11 at 11 15 22 PM" src="https://user-images.githubusercontent.com/6330506/79059767-d5d32f00-7c4b-11ea-8604-eeaaff9cbbc5.png">
5. Create a new Flutter App. 
51. flutter create  swifttest
6. Add new Swift Plugin mentioned above as a dependency to pubspec.yaml
<img width="541" alt="Screen Shot 2020-04-11 at 11 26 46 PM" src="https://user-images.githubusercontent.com/6330506/79059836-91945e80-7c4c-11ea-80c0-807f82fbb500.png">
7. Try to run app
7.1 Flutter Run
8. Notice dependency is not found.
<img width="1031" alt="Screen Shot 2020-04-11 at 11 13 20 PM" src="https://user-images.githubusercontent.com/6330506/79059842-af61c380-7c4c-11ea-92b5-b7e04851afc0.png">
<img width="783" alt="Screen Shot 2020-04-11 at 11 35 14 PM" src="https://user-images.githubusercontent.com/6330506/79059870-28f9b180-7c4d-11ea-8869-594f02e1dab3.png">
<img width="742" alt="Screen Shot 2020-04-11 at 11 35 27 PM" src="https://user-images.githubusercontent.com/6330506/79059872-2ac37500-7c4d-11ea-89a1-6737a18a87c4.png">

## Logs
<img width="742" alt="Screen Shot 2020-04-11 at 11 35 27 PM" src="https://user-images.githubusercontent.com/6330506/79059872-2ac37500-7c4d-11ea-89a1-6737a18a87c4.png">

```
```

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E264b, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)

```
```

**Comment by mitchross** [comment]
@jmagman

**Comment by jmagman** [comment]
Can you explain what `[NOTE] Work around to make Objective-C plugin work.` means?  Did you manually edit the CocoaPods generated modulemap to point to that header?

Is https://github.com/mitchross/flutter_vlc_player/pull/1 where I can see an example?

**Comment by mitchross** [comment]
@jmagman Oh Wow thanks for replying! Yes https://github.com/mitchross/flutter_vlc_player/pull/1/files#diff-488d750fd65e47aed170ea717ed4ec38 here you can see module map.

So this PR/example works locally. If you run the example in the plugin it works. However, if you use it in a another flutter project it fails, because the "path" on the module map "doesnt exist". 

It seems like this concept would work, where you write a script to re-write the path/directory of the modulemap map, but that seems like extreme overkill.

What I've noticed is that if i use an Objective-C plugin template, everything works. Once I switch to an Swift based plugin, the headers are not found for the objective-c pod dependency. The only fix is the modulemap. Which, again works great in local but not once exported and used as a flutter plugin on a differnt project. 

Similar issue

-  https://stackoverflow.com/questions/54476458/how-to-use-objective-c-framework-in-a-swift-written-ios-part-of-a-flutter-plugin

**Comment by mitchross** [comment]
@jmagman 'Did you manually edit the CocoaPods generated modulemap to point to that header?" No I did not manually edit the generated modulemap. I had to manually add my own because if you use a swift project plugin template, you cant import objective-c pod.

**Comment by jmagman** [comment]
This isn't really a Flutter problem specifically, it's a Swift <-> Objective-C interop problem.  Swift pods _can_ declare Objective-C dependencies that correctly implement clang modules, which `MobileVLCKit` doesn't (as you know since you already tried to build one yourself):
```
MobileVLCKit.framework 

drwxr-xr-x  16 m  primarygroup         512 Apr 14 13:33 Headers
-rwxr-xr-x   1 m  primarygroup  1715586784 Apr 14 13:33 MobileVLCKit
```
So the "right" thing for them to do is to add a modulemap in their framework.  Which I realize doesn't help you at the moment.

It makes sense nothing other than your example can use your custom modulemap, this path doesn't exist for an arbitrary Flutter app:
```
header "../../../example/ios/Pods/MobileVLCKit/MobileVLCKit.framework/Headers/MobileVLCKit.h"
```

You're essentially hitting this problem: https://medium.com/@florentmorin/integrating-swift-framework-with-non-modular-libraries-d18098049e18, so you may need to import and use that framework in Objective-C code, then call your Objective-C method in your Swift interface.

Also I think you're missing this from your podspec so Objective-C Flutter apps can use your Swift plugin:
```
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.swift_version = '5.0'
```

I'm going to close this since there's nothing Flutter can really do to help you with this unfortunate scenario.  It's up to your plugin to import its dependencies, and dealing with an "include of non-modular header inside framework module" error is part of that.

**Comment by mitchross** [comment]
@jmagman Thank you for the detailed response!

**Comment by mitchross** [comment]
@jmagman would this hack work? https://gist.github.com/jonesd/f33250fd3ec5ddb599e6d412c808986c

**Comment by jmagman** [comment]
> @jmagman would this hack work? https://gist.github.com/jonesd/f33250fd3ec5ddb599e6d412c808986c

1. If your users run `flutter pub cache repair` does the modulemap still exist?
1. The Podfile doesn't need to declare a Swift version, each podspec should `s.swift_version`
1. Try `use_modular_headers!`
1. Don't tell your users to set these, they should be able to use latest Swift versions or have all the warnings on they want.
```
config.build_settings['SWIFT_VERSION'] = '4.2'
config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
```

Anyway I'm not a CocoaPods expert, and this isn't a Flutter issue.  You can ask more questsion on StackOverflow and create new feature requests with [CocoaPods](https://github.com/CocoaPods/CocoaPods/issues).

**Comment by mitchross** [comment]
Thanks, gonna ask VLC owners to fix -> https://code.videolan.org/videolan/VLCKit/-/issues/191#note_58161

logging for historical record in case someone else hits this path.
