### ISSUE TITLE
Flutter Web application extremaly slow on Mobile Chrome with ListView/Wrap widget

### ISSUE THREAD

**Issue by NickNevzorov** [flutter/flutter#54584]
When Wrap widget placed inside ListView on Mobile Chrome app extrimally slow scrolling and crashes

Test on Samsung s9 and s10. On Android or Destop Chrome working fine

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    List<Widget> result = [];

    for (int i = 0; i < 1; i++) {

      List<Widget> ps = [];
      for (int k = 0; k < 10; k++) {
          ps.add( Container(
                  padding: EdgeInsets.all(8.0),
                  child: Column(children: [
                    Icon(Icons.file_download),
                    Image.network("http://webshop.vsgroup.ua/assets/images/s9000.jpg"),
                  ])));
        }

      result.add(Wrap(children: ps));
    }

    return Scaffold(
      body: ListView(children: result),
    );
  }
}

```

if place widget directly into ListView without Wrap it working fine:
1. change ps.add to result.add
2. comment result.add(Wrap(children: ps));

Issure are on all branches

> C:\Flutter\flutter_scrollimages>flutter doctor -v
> [√] Flutter (Channel dev, v1.18.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
>     • Flutter version 1.18.0 at d:\android\flutter
>     • Framework revision 8f7327f83a (5 days ago), 2020-04-06 22:11:01 -0400
>     • Engine revision 49891e0653
>     • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at d:\android\sdk\
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = d:\android\sdk\
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
>     • Web Server • web-server • web-javascript • Flutter Tools
> 
> • No issues found!
>

**Comment by TahaTesser** [comment]
Issue exist 

dev channel -> https://musing-kalam-74f4c2.netlify.com/#/

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (6 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by ferhatb** [comment]
@yjbanov Verified that optimalCullRect is growing.

**Comment by yjbanov** [comment]
> @yjbanov Verified that optimalCullRect is growing.

I checked that https://github.com/flutter/engine/pull/17621 helps quite a bit.

However, I also see that this example causes 2D canvas allocations between images and text.

![canvas-sandwich](https://user-images.githubusercontent.com/211513/79263624-0a133f00-7e48-11ea-81af-6c1dfbc882e7.png)

We should also check why we end up on a `BitmapCanvas` at all. It seems like this should go straight to the `DomCanvas`.

**Comment by yjbanov** [comment]
I checked this again. https://github.com/flutter/engine/pull/17621 significantly reduced the amount of DOM we render (I only see a few images in any given frame), and https://github.com/flutter/engine/pull/17710 removed the unnecessary `<canvas>` allocations. While I don't have a S9 or a S10 to verify, but I'm assuming this should improve performance significantly. I'm therefore closing the issue, but if this use-case is still slow on S9 or S10, please feel free to reopen.
