### ISSUE TITLE
Can't access flutter:  flutter pub get error

### ISSUE THREAD

**Issue by ssakib005** [flutter/flutter#54595]
After adding new library to flutter dependency 

flutter pub get return 

Connection terminated during handshake
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Can any one tell me whats the issue.

Thanks

**Comment by VladyslavBondarenko** [comment]
Hi @ssakib005 
please follow up on https://github.com/dart-lang/pub/issues/2288, try https://github.com/dart-lang/pub/issues/2288#issuecomment-607721988
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by Tarikul711** [comment]
This is a country-specific problem. In some countries, you got this error like Bangladesh and some African countries. I got a solution to this problem, that is use VPN software when you want to get Packages. VPN software uses other country's IP addresses where this google service works perfectly, So you can easily download packages.
