### ISSUE TITLE
'dart:ui/window.dart': Failed assertion: line 284: '<optimized out>': is not true

### ISSUE THREAD

**Issue by manideepu0014** [flutter/flutter#54590]
```
The following assertion was thrown building LandingPage(dirty): 
I/flutter ( 7567): 'dart:ui/window.dart': Failed assertion: line 284: '<optimized out>': is not true. 
I/flutter ( 7567): 
I/flutter ( 7567): Either the assertion indicates an error in the framework itself, or we should provide substantially 
I/flutter ( 7567): more information in this error message to help you determine and fix the underlying cause.
```

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/dart-lang/sdk/issues/34586.

@manideepu0014 cold you provide a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the error?
and you `flutter doctor -v`

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.

**Comment by Domiynsbelhanda** [comment]
E/flutter ( 4131): Receiver: null
E/flutter ( 4131): Tried calling: uid
E/flutter ( 4131): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4131): #1      HelperMethods.getCurrentUserInfo (package:taxigo_user_app/helpers/helpermethods.dart:24:41)
E/flutter ( 4131): #2      main (package:taxigo_user_app/main.dart:24:17)
E/flutter ( 4131): <asynchronous suspension>
E/flutter ( 4131): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 4131): #4      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4131): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4131): #6      _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 4131): #7      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 4131): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 4131): #9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 4131): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
