### ISSUE TITLE
CheckBox Animation Missing

### ISSUE THREAD

**Issue by TimSchulzRC** [flutter/flutter#54591]
Why are there no animations for the checkboxes in my listview?
[https://github.com/TimSchulzRC/check_it](https://github.com/TimSchulzRC/check_it)

**Comment by TahaTesser** [comment]
Hi @TimSchulzRC 

can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem

Please try this, maybe you have custom implementation 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _value = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: ListView(
          children: <Widget>[
            Checkbox(
              value: _value,
              onChanged: (bool newValue) {
                setState(() {
                  _value = newValue;
                });
              },
            ),
            Checkbox(
              value: _value,
              onChanged: (bool newValue) {
                setState(() {
                  _value = newValue;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment]
Hi @TimSchulzRC 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
