### ISSUE TITLE
invalid active developer path, missing xcrun at

### ISSUE THREAD

**Issue by atharvjairath** [flutter/flutter#54593]
## Steps to Reproduce

1. Just added export   path in bash_profile.
2. ran` flutter --version ` got this error 
3. then ran flutter doctor

## Logs

```
```

```
[flutter_02.log](https://github.com/flutter/flutter/files/4466412/flutter_02.log)

```

**Comment by atharvjairath** [comment]
invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by VladyslavBondarenko** [comment]
Hi @atharvjairath 
please reattach the log file (you wrapped it in the code quotes, so plain text present instead of the file)

**Comment by atharvjairath** [comment]
@VladyslavBondarenko it did. Thanks for your help!
