### ISSUE TITLE
Clean up flutter repo SDK constraints

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#546]
I think we should just remove the SDK constraints (assuming the flutter tool itself doesn't depend on a particular SDK version) and make the flutter tool point out the likely issues if you try to analyze with an old version.

**Comment by Hixie** [comment]
-[ ] figure out the earliest SDK version that can run flutter, and set that as an SDK constraint.
-[ ] `flutter analyze` when SDK is <1.13: "The analyzer in the version of the Dart SDK you have installed does not support 'super' in mixins, which the Flutter framework uses. This will lead to spurious error messages. You should upgrade to the latest stable Dart SDK."

I think that's it.

**Comment by abarth** [comment]
We've just been upping the SDK constraint roughly in line with the vendored Dart SDK that we're using.  Now that we're vendoring the Dart SDK, I don't think it's worth maintaining compatibility with old Dart SDK versions.
