### ISSUE TITLE
My Dissmissible Listview is Lagging So Much in release mode and GPU frame is still on higher (above 60 frames/seconds).)

### ISSUE THREAD

**Issue by Tirth7545** [flutter/flutter#54609]
## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

**Comment by liyuqian** [comment]
@Tirth7545 : can you please provide more details about how to reproduce this issue? The title alone won't be informative enough for us to fix it. Here are some instructions of what info can help us:

> 1.  Please tell us exactly how to reproduce the problem you are running into.
> 2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.
> 3.  Switch flutter to master channel and run this app on a physical device
     using profile mode with Skia tracing enabled, as follows:
       flutter channel master
       flutter run --profile --trace-skia
     Then press ‘P’ to enable the performance overlay.
>     The bleeding edge master channel is encouraged here because Flutter is
>     constantly fixing bugs and improving its performance. Your problem in an
>     older Flutter version may have already been solved in the master channel.
> 4.  Record a video of the performance issue using another phone so we
     can have an intuitive understanding of what happened. Don’t use
     "adb screenrecord", as that affects the performance of the profile run.
> 5.  Open Observatory and save a timeline trace of the performance issue
     so we know which functions might be causing it. See "How to Collect
     and Read Timeline Traces" on this blog post:
       https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af03#a499
