### ISSUE TITLE
Build error "A problem occurred configuring root project 'audio'. > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable."

### ISSUE THREAD

**Issue by rpjayasekara** [flutter/flutter#54605]
I am having this error 
```
A problem occurred configuring root project 'audio'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```
only when I build the apk. When I run the app in emulator this error doesn't come.

**Comment by VladyslavBondarenko** [comment]
Hi @rpjayasekara 
could you provide your `flutter doctor -v`?
Is `sdk.dir` value set in `android/local.properties`?

**Comment by rpjayasekara** [comment]
`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/randika/Documents/Tools/Flutter/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/randika/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/randika/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/randika/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Users/randika/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
`

Yes its all set only the error comes building the apk file. I tried to build the app bundle and it also worked

**Comment by VladyslavBondarenko** [comment]
@rpjayasekara 
does [setting ANDROID_HOME environment variable](https://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x) help?

**Comment by rpjayasekara** [comment]
Nop tried it and it's not working

**Comment by djprawns** [comment]
I am facing the same issue when using a plugin in a flutter project. Any solution for this?

**Comment by am1994** [comment]
I faced some issue and i fixed it : 
1) go to plugin folder
2) open local.properties 
3) and set the sdk location for example "sdk.dir=/home/amina/Android/Sdk"

**Comment by amiruljack** [comment]
Same error

**Comment by willhaslett** [comment]
> I faced the same issue in flutter_downloader plugin and I fixed it :
> 
>     1. go to the plugin folder and open local.properties =>
>        (/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.4.4/android)
> 
>     2. set the SDK location for example "sdk.dir=/home/amina/Android/Sdk"

@am1994 will this not stop working when that package is upgraded, or any time the cache is replaced?

**Comment by am1994** [comment]
> > I faced the same issue in flutter_downloader plugin and I fixed it :
> > ```
> > 1. go to the plugin folder and open local.properties =>
> >    (/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.4.4/android)
> > 
> > 2. set the SDK location for example "sdk.dir=/home/amina/Android/Sdk"
> > ```
> 
> @am1994 will this not stop working when that package is upgraded, or any time the cache is replaced?

@willhaslett i don't know really, but if u want avoid this issue u can fork the package from github then make the changes and  get the package link from your repository to add it in pubspec.yaml.
note: u can't get the packages updates

**Comment by Awaisoop** [comment]
same issue still facing

**Comment by cntoss** [comment]
in my case fixed by updating     compileSdkVersion 29 from compileSdkVersion 28 in android\app\build.gradle

**Comment by micmdk** [comment]
updating gradle fixed it for me; https://stackoverflow.com/a/64741539/1840269

**Comment by botond-kopacz** [comment]
> updating gradle fixed it for me; https://stackoverflow.com/a/64741539/1840269

This solved for me, thanks!

**Comment by fnoceda** [comment]
Hi, same problem here, I try @am1994 solution but don't work for me, my actual gradle is classpath 'com.android.tools.build:gradle:4.1.0', I try downgrade to classpath 'com.android.tools.build:gradle:4.0.1' but don't work for me, mi compileSdkVersion is 30, hope help, tanks

**Comment by GaryQian** [comment]
Does upgrading to Android Gradle plugin 7.2.0 (android/build.gradle) and Gradle 7.5 (android/app/AndroidManifest.xml) fix this?
