### ISSUE TITLE
Unexpected value from nativeGetEnabledTags: 0

### ISSUE THREAD

**Issue by Saroglu** [flutter/flutter#54601]
Hi,
I tried  emulator and physical device(android) to run my app but results are same, it is "Unexpected value from nativeGetEnabledTags: 0". I changed body: in the scaffold as a Text widget then it worked.   
I decided to change my "ProductList" codes with my course codes. After that, same results were happened again. 
Thank you.
![flutter](https://user-images.githubusercontent.com/50512297/79073182-cad0db00-7ced-11ea-9448-aa8970dbec94.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @Saroglu 
can you please provide your `flutter doctor -v` 
And a minimal complete code sample to reproduce the problem

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
