### ISSUE TITLE
can't work with setState

### ISSUE THREAD

**Issue by AballahEhab** [flutter/flutter#54604]
hello 
I am using a method in the same class with the build method
and this method contains a drop-down button but it does not show the 
new value although I am using the set state method
how can I solve this
![image](https://user-images.githubusercontent.com/52103437/79073607-ce616380-7ce7-11ea-944a-ab6222cdc0e6.png)
 and this is where I called my function addNamedProperty which returns a widget

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
