### ISSUE TITLE
flutter version getting failed

### ISSUE THREAD

**Issue by Nurullah-Sadekin** [flutter/flutter#54610]
this is what shows when i am going in flutter page .
What is the problem how will i solve it ??
![image](https://user-images.githubusercontent.com/60127268/79076614-49913c80-7d1d-11ea-9dce-e85297c293f5.png)

**Comment by iapicca** [comment]
Hi @Nurullah-Sadekin 
the issue seems to be related to your internet connection
are you behind a proxy or a vpn?
thank you

https://github.com/flutter/flutter/issues/54611

**Comment by VladyslavBondarenko** [comment]
@Nurullah-Sadekin 
I hope you've solved the issue, closing,
Who faced it consider to try https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site and create a separate issue if it doesn't help
