### ISSUE TITLE
Unexpected value from nativeGetEnabledTags: 0

### ISSUE THREAD

**Issue by Saroglu** [flutter/flutter#54616]
Hi,
I tried emulator and physical device(android) to run my app but results are same, it is "Unexpected value from nativeGetEnabledTags: 0". I changed body: in the scaffold as a Text widget then it worked.
I decided to change my "ProductList" codes with my course codes. After that, same results were happened again.
Thank you.
![flutter](https://user-images.githubusercontent.com/50512297/79078510-87886380-7d11-11ea-887a-1357678476db.jpg)

**Comment by iapicca** [comment]
Hi @Saroglu 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Hi @Saroglu 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
