### ISSUE TITLE
[proposal] Easier Flutter Installation which installs everything needed similar to Visual Studio

### ISSUE THREAD

**Issue by fisforfaheem** [flutter/flutter#54614]
making things simple for new people will help a lot, cuz most people dont want too much linux kind of stuff....u know what i mean, just make things easier like it is easier for c# devleopment.

**Comment by fisforfaheem** [comment]
hope the people figure it out and change my mind to leave VS

**Comment by jmagman** [comment]
I'm going to throw this back to first-line triage to get more details.

**Comment by TahaTesser** [comment]
Hi @fisforfaheem 
Can you please add more detail on what process you wan to make simpler?
Thank you

**Comment by fisforfaheem** [comment]
I mean when we install the vs 2019 it is so easy and everything seems so
simple and all in one place, whereas with flutter development everything
seems modular and difficult and makes literally no sense and difficult to
even setup everything

**Comment by VladyslavBondarenko** [comment]
@fisforfaheem please describe more detailed and with examples what is difficult and what would you want to see in another way

**Comment by fisforfaheem** [comment]
Make it is easy to start developing apps using VS code, without the need of extra tools( they should be auto downloaded when we isntall the flutter extension) whings like android SDK flututer toolkit etc

**Comment by jonahwilliams** [comment]
It sounds like this issue is asking for installers? Visual Studio is pretty nice in that all you need to do  is click the right checkboxes and everything else gets setup for you. It would be nice if flutter had that sort of experience

**Comment by fisforfaheem** [comment]
Yes this is all i want :(

**Comment by christopherfujino** [comment]
Agreed this would be useful. This is already being track with https://github.com/flutter/flutter/issues/39939. I am going to close this issue as a duplicate, please follow that issue for updates.
