### ISSUE TITLE
[Windows] themeMode.system does not pick up on the Windows system theme

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#54612]
Steps to reproduce:
1. Create a new Flutter project on the master branch on a Windows 10 machine that supports toggling between light and dark theme
2. Add
```
darkTheme: ThemeData.dark(),
themeMode: ThemeMode.system,
```
to the `MaterialApp` and run the application
3. Observe that if you toggle the Windows theme between dark and light, the Flutter application will not reflect the theme change

Flutter doctor -v:
```
[√] Flutter (Channel master, v1.18.0-5.0.pre.96, on Microsoft Windows [Version 10.0.18363.752], locale en-US)
    • Flutter version 1.18.0-5.0.pre.96 at C:\flutter
    • Framework revision 7f56b53de4 (2 hours ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ReubenT\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29102.190

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7761

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\ReubenT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.0


Scanning for devices is taking a long time...-Terminate batch job (Y/N)? y

C:\Users\ReubenT\FlutterProjects\experiments\windows_theme_bug>flutter doctor -v
[√] Flutter (Channel master, v1.18.0-5.0.pre.96, on Microsoft Windows [Version 10.0.18363.752], locale en-US)
    • Flutter version 1.18.0-5.0.pre.96 at C:\flutter
    • Framework revision 7f56b53de4 (2 hours ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ReubenT\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29102.190

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7761

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\ReubenT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.0
```
(cannot include the devices section as it has been hanging indefinitely...O_O)

Windows version:
1909 build 18363.752

Most recent `flutter upgrade` was today.

**Comment by jonahwilliams** [comment]
It looks like the system theme API is not connected to the flutter window in https://github.com/flutter/engine/blob/master/shell/platform/windows/win32_flutter_window.cc

For comparison, in the macOS shell we can hook into a system notification that informs of us dark versus light mode: https://github.com/flutter/engine/blob/master/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm#L478

The actual API we need to connect to depends on the shell. Since the engine is currently written against the win32 APIs, we'll likely need something from there. With a bit of googling, I found this

https://github.com/ysc3839/win32-darkmode/blob/master/win32-darkmode/DarkMode.h

But I'm not sure if that is right solution.

**Comment by jonahwilliams** [comment]
I also found https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application , which suggests either poking into the registry or including winrt code

**Comment by GroovinChip** [comment]
On the subject of the win32 code, I found the following links which might be useful:

- https://blogs.windows.com/windowsdeveloper/2019/09/30/windows-10-winrt-api-packs-released/
- https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
- https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started

**Comment by stuartmorgan** [comment]
https://source.chromium.org/chromium/chromium/src/+/63e92830db63d5b7d03c245dda083cb4e7f33ea8 is Chromium's code for this, which uses the registry.

**Comment by GroovinChip** [comment]
> https://source.chromium.org/chromium/chromium/src/+/63e92830db63d5b7d03c245dda083cb4e7f33ea8 is Chromium's code for this, which uses the registry.

Seems like we have a problem importing `#include "base/win/registry.h"`:
```
error C1083:  Cannot open include file: 'base/win/registry.h': No such file or
directory [C:\Users\ReubenT\FlutterProjects\experiments\github_activity_feed_design\windows\Runner.vcxproj]
```
That's from doing `flutter run -d windows -v`

**Comment by stuartmorgan** [comment]
> Seems like we have a problem importing #include "base/win/registry.h"

That's a Chromium source file, so that's not surprising. That's equivalent to taking one Dart file from a complex Flutter project; non-package `import`s aren't going to work in that scenario either.

**Comment by GroovinChip** [comment]
Ah, my C++ inexperience is showing lol. The way it read it sounded like a Windows package

**Comment by GroovinChip** [comment]
https://github.com/GiovanniDicanio/WinReg might be of interest

**Comment by feliwir** [comment]
@GroovinChip i think there is missing an **L** at OpenKey call, like this:
```cpp
HKEY hKey = OpenKey(HKEY_LOCAL_MACHINE,L"SOFTWARE\\Microsoft\\SystemSettings\\SettingId");
```
and 
```c++
val1 = GetValue(hKey, L"SystemSettings_Personalize_Color_AppsUseLightTheme");
```
See https://docs.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings for the Visual C++ string conventions

**Comment by GroovinChip** [comment]
I haven't worked on this since my last comment, but thank you for sharing.

**Comment by feliwir** [comment]
@GroovinChip if you have a branch/ fork for this feature i could contribute the required the changes

**Comment by GroovinChip** [comment]
I don't, I'm sorry. Like I said, I stopped working on this months ago. I
reported all my efforts though.
