### ISSUE TITLE
Dart sdk isnt installing 

### ISSUE THREAD

**Issue by Nurullah-Sadekin** [flutter/flutter#54611]
My internet connection is alright But massage shows that . What is the problem 

![image](https://user-images.githubusercontent.com/60127268/79076666-d2a87380-7d1d-11ea-81fe-066133d44967.png)

**Comment by iapicca** [comment]
Hi @Nurullah-Sadekin 
I believe the cause of both  issue is the same,
please follow up [here](https://github.com/flutter/flutter/issues/54610)
Thank you
