### ISSUE TITLE
i'm new to programming and i get this when i try to run my app on my phone

### ISSUE THREAD

**Issue by Setsukoni** [flutter/flutter#54625]
i'm trying to make 2 images appear on my home tab but it just won't work, could you help me figure out what is wrong?

`D/FlutterView(24655): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@f43924b
D/mali_winsys(24655): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
V/InputMethodManager(24655): Starting input: tba=android.view.inputmethod.EditorInfo@e813703 nm : com.example.lojinhaflutter ic=null
I/InputMethodManager(24655): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(24655): Input channel constructed: fd=112
D/InputTransport(24655): Input channel destroyed: fd=108
I/art     (24655): Do partial code cache collection, code=23KB, data=31KB
I/art     (24655): After code cache collection, code=22KB, data=30KB
I/art     (24655): Increasing code cache capacity to 128KB
D/ViewRootImpl@3a831c2[MainActivity](24655): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=true -999342080} surfaceGenerationChanged=false
I/flutter (24655): 2
D/ViewRootImpl@3a831c2[MainActivity](24655): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@3a831c2[MainActivity](24655): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -999342080}
V/InputMethodManager(24655): Starting input: tba=android.view.inputmethod.EditorInfo@b198680 nm : com.example.lojinhaflutter ic=null
I/InputMethodManager(24655): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(24655): Input channel constructed: fd=110
D/InputTransport(24655): Input channel destroyed: fd=112
I/flutter (24655): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY`
╞═══════════════════════════════════════════════════════════
`I/flutter (24655): The following assertion was thrown building FutureBuilder<QuerySnapshot>(dirty, state:
I/flutter (24655): _FutureBuilderState<QuerySnapshot>#294eb):
I/flutter (24655): type 'String' is not a subtype of type 'int'
I/flutter (24655): 
I/flutter (24655): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24655): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24655): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24655):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24655): 
I/flutter (24655): The relevant error-causing widget was:
I/flutter (24655):   FutureBuilder<QuerySnapshot>
I/flutter (24655):   file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13
I/flutter (24655): 
I/flutter (24655): When the exception was thrown, this was the stack:
I/flutter (24655): #0      HomeTab.build.<anonymous closure>.<anonymous closure> (package:lojinhaflutter/tabs/home_tab.dart:59:66)
I/flutter (24655): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
I/flutter (24655): #2      ListIterable.toList (dart:_internal/iterable.dart:221:19)
I/flutter (24655): #3      HomeTab.build.<anonymous closure> (package:lojinhaflutter/tabs/home_tab.dart:61:27)
I/flutter (24655): #4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (24655): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (24655): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (24655): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (24655): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (24655): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (24655): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (24655): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (24655): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (24655): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (24655): #17     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (24655): #18     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (24655): (elided 3 frames from package dart:async)
I/flutter (24655): 
I/flutter (24655): `════════════════════════════════════════════════════════════════════════════════════════════════════
`I/flutter (24655): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (24655): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
E/AccessibilityBridge(24655): VirtualView node must not be the root node.
I/flutter (24655): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
Error -32000 received from application: Server error
I/flutter (24655): 2`

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
`The following assertion was thrown building FutureBuilder<QuerySnapshot>(dirty, state: _FutureBuilderState<QuerySnapshot>#294eb):
type 'String' is not a subtype of type 'int'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  FutureBuilder<QuerySnapshot> file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13
When the exception was thrown, this was the stack: 
#0      HomeTab.build.<anonymous closure>.<anonymous closure> (package:lojinhaflutter/tabs/home_tab.dart:59:66)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#2      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#3      HomeTab.build.<anonymous closure> (package:lojinhaflutter/tabs/home_tab.dart:61:27)
#4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart`)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
`'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
The relevant error-causing widget was: 
  FutureBuilder<QuerySnapshot> file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13`
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  CustomScrollView file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:26:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (11) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  HomeTab file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:14:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (12) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (13) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (14) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (15) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (16) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16: 'child == null || indexOf(child) > index': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (17) Exception caught by widgets library ══════════════════════════════════════════════════
A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (18) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (19) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (20) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (21) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (22) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (23) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (24) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (25) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/src/testeAprendizado/lojinha_flutter/lib/screens/home_screen.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (26) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  HomeScreen file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:17:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (27) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (28) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (29) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (30) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (31) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (32) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (33) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (34) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (35) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (36) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (37) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3949 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///C:/src/testeAprendizado/lojinha_flutter/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════
E/AccessibilityBridge(24655): VirtualView node must not be the root node.
I/flutter (24655): 2

════════ (38) Exception caught by widgets library ══════════════════════════════════════════════════
type 'String' is not a subtype of type 'int'
The relevant error-causing widget was: 
  FutureBuilder<QuerySnapshot> file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (39) Exception caught by widgets library ══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
The relevant error-causing widget was: 
  FutureBuilder<QuerySnapshot> file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (40) Exception caught by widgets library ══════════════════════════════════════════════════
A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
The relevant error-causing widget was: 
  FutureBuilder<QuerySnapshot> file:///C:/src/testeAprendizado/lojinha_flutter/lib/tabs/home_tab.dart:37:13
════════════════════════════════════════════════════════════════════════════════════════════════════

this is what appears when i try to run it

**Comment by meditat** [comment]
These kind of issues are made for SO,
Btw you are trying to pass somewhere a String variable where int var is required.

Since there is no code I can't not tell what to change.

**Comment by Setsukoni** [comment]
sorry i forgot to put my code, but here it is:

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:transparent_image/transparent_image.dart';

class HomeTab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    Widget _buildBodyBack() => Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
            colors: [
              Color.fromARGB(255, 218, 112, 214),
              Color.fromARGB(255, 70, 130, 180)
            ],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight
        ),
      ),
    );

    return Stack(
      children: <Widget>[
        _buildBodyBack(),
        CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              floating: true,
              snap:true,
              backgroundColor: Colors.transparent,
              elevation: 0.0,
              flexibleSpace: FlexibleSpaceBar(
                title: const Text("Novidades"),
              ),
            ),
            FutureBuilder<QuerySnapshot>(
                future: Firestore.instance
                    .collection("home").orderBy("pos").getDocuments(),
                builder: (context, snapshot){
                  if(!snapshot.hasData)
                    return SliverToBoxAdapter(
                      child: Container(
                        height: 200.0,
                        alignment: Alignment.center,
                        child: CircularProgressIndicator(
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                        ),
                      ),
                    );
                  else {
                    print(snapshot.data.documents.length);
                    return SliverStaggeredGrid.count(
                        crossAxisCount: 2,
                        mainAxisSpacing: 1.0,
                        crossAxisSpacing: 1.0,
                        staggeredTiles: snapshot.data.documents.map(
                                (doc){
                              return StaggeredTile.count(doc.data["x"], doc.data["y"]);
                            }
                        ).toList(),
                        children: snapshot.data.documents.map(
                                (doc){
                              return FadeInImage.memoryNetwork(
                                placeholder: kTransparentImage,
                                image: doc.data["image"],
                                fit: BoxFit.cover,);
                            }
                        ).toList()
                    );
                  }
                }
            )
          ],
        )
      ],
    );
  }
}`

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
