### ISSUE TITLE
animated_placeholder_perf 99th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54629]
Maybe this engine roll? https://github.com/flutter/flutter/pull/54409 I can't really tell.

But looking at the history, something's happened.
![Screenshot 2020-04-12 at 22 00 42](https://user-images.githubusercontent.com/1435716/79093419-1a70d000-7d09-11ea-9bdb-4302f2a75862.png)

**Comment by kf6gpe** [comment]
Looks like worst_frame_rasterizer_time_millis is affected too.

**Comment by mehmetf** [comment]
@kf6gpe who typically looks at these regressions?

This is already in Google branch and it has appeared in 1.18.0-dev.5.0 as well.

**Comment by kf6gpe** [comment]
I screen them daily. It looks like this edged up some slowly, and it's
noisy enough that it didn't cross the threshold for attention until last
night.


Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>

**Comment by liyuqian** [comment]
CC engine rotation sheriff today @cbracken and tomorrow @jason-simmons

**Comment by jason-simmons** [comment]
Tried to bisect this.  The benchmark results are inconsistent, but the most likely culprit appears to be:
    https://github.com/flutter/engine/commit/f6ca48943d0f5cd4360fd9593a73a9d9c938db56

@iskakaushik 

We recently had another benchmark regression involving a similar commit (https://github.com/flutter/flutter/issues/54095).  In that case the SceneDisplayLag event created a timeline record format that didn't match the expectations of the timeline parser in the benchmark scripts.

So it's possible that the additional ~10 ms added to the frame rasterizer metric is an artifact of the collection infrastructure and may not reflect that logging this event is taking that much time.

**Comment by jason-simmons** [comment]
The `SceneDisplayLag` event is still causing events in the timeline JSON to be generated out of order.

Attached a timeline trace from a run of the animated_placeholder_perf benchmark on the current master.  The first few `GPURasterizer::Draw` events in the timeline are:

Index | Phase | Timestamp
--- | --- | ---
1 | E | 358907052507
2 | B | 358907061563
3 | E | 358907097722
4 | B | 358907097795
5 | E | 358907078317

The first `GPURasterizer::Draw` event in the timeline is an end event (not the expected begin event).  And end event `#5` has a timestamp that comes before the corresponding begin event `#4`.

There is a `SceneDisplayLag` event between `GPURasterizer::Draw` begin event `#4` and end event `#5`.  That `SceneDisplayLag` event has a timestamp that is earlier than the event immediately preceding it in the JSON.

@iskakaushik I think we need to revert this again.  I don't know if there is a way to log this event safely unless the record's timestamp is the current time.


[animated_placeholder_perf.zip](https://github.com/flutter/flutter/files/4483277/animated_placeholder_perf.zip)

**Comment by iskakaushik** [comment]
Thanks for digging into this @jason-simmons . I will replace this event with an synchronous instantaneous event, just having the number of transitions missed. That way we will not have begin/end times.

I am removing the TODAY label, since this is not really a benchmark regression, but a tracing problem.

**Comment by flar** [comment]
I looked at a few events towards the beginning of @jason-simmons zip file and didn't see any out of order SceneDisplayLag events...?

**Comment by iskakaushik** [comment]
I had to revert this change. I'm trying to root-cause the problem in https://github.com/flutter/flutter/issues/54629#issuecomment-614227612

**Comment by kf6gpe** [comment]
Looks much better now --- closing. 
![Screen Shot 2020-05-11 at 2 41 59 PM](https://user-images.githubusercontent.com/1435716/81614911-9a846700-9395-11ea-8f27-faa2515efd25.png)
