### ISSUE TITLE
Symantec Endpoint protection Deletes Dart.exe file

### ISSUE THREAD

**Issue by soumyajit-ghosh** [flutter/flutter#54637]
\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,
operable program or batch file.
As a workaround you can restore the file from settings.

**Comment by TahaTesser** [comment]
Hi @soumyajit-ghosh 
Please explain the issue in detail
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by soumyajit-ghosh** [comment]
@TahaTesser It is related to installation. During scan, symantec endpoint protection deletes the dart.exe file from \bin\cache\dart-sdk\bin\dart.exe path. Thus no flutter commands work. Looks like it categories the exe file as quarantine.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/16008

Does it give any hints or logs about what makes it think it's a virus?

**Comment by prasadsunny1** [comment]
Like the code name of the virus, Symantec is detecting in this file.

**Comment by jonahwilliams** [comment]
dart.exe definitely does not contain a virus. As long as you are downloading it from flutter.dev, I would recommend adding the flutter SDK to any antivirus allowlist. This is not something we can fix or work around in Flutter.
