### ISSUE TITLE
dart and flutter runners should publish the observatory port via inspect

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54631]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=49938.

**Comment by zanderso** [comment]
Removing tool and engine since this work is in the runners/engine.

**Comment by iskakaushik** [comment]
After looking at https://github.com/dart-lang/sdk/blob/master/runtime/vm/service_isolate.h, @bkonyi is exploring exposing some of these methods via `dart_api.h` so the engine can register callbacks for hostname and port changes. Once this is done, I can patch the engine to record any updates with the inspect api.

Note that the Flutter tool will still rely on `hub` to get this information.

**Comment by zanderso** [comment]
I'm a bit confused. Why would the host and port change after startup? Currently, the host and port are written in the runner's /tmp here:

https://github.com/dart-lang/sdk/blob/f9816cdc35c3d8bbcdf3727abe2afbe719e0679b/sdk/lib/_internal/vm/bin/vmservice_server.dart#L458

And published to the hub here:

https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/runtime/dart/utils/vmservice_object.cc#L52

Why are new dart_api.h methods needed to publish the same info to inspect?

**Comment by iskakaushik** [comment]
@zanderso I did not realize that they were getting written to that location. As I understand it the observatory server could sometimes be lazily started (when the port isn't specified for example). In those cases, is there an event that I can listen on in the engine to know that the port information is available for me to be read?

**Comment by zanderso** [comment]
Service isolate startup has always been asynchronous. Clients of the service protocol on all platforms have traditionally handled this via polling. Even if the engine could register a callback with the VM in which the engine will publish the vm service address to inspect, will clients of the inspect API still have to poll anyway? Just trying to avoid adding `dart_api.h` APIs when it might not buy anything in the end.

**Comment by chaselatta** [comment]
This is being tracked via the upstream issue.
