### ISSUE TITLE
How to add User-Agent and Authorization for API?

### ISSUE THREAD

**Issue by Abelstuker** [flutter/flutter#54644]
I want to use the Spreadshop API. I have my API Key. I can find this in the documentation for the headers:
![tijdelijk1](https://user-images.githubusercontent.com/62062732/79111785-783eff80-7d7d-11ea-91ad-5539c748a16c.PNG)

But how can I implement that here?:
![Knipsel](https://user-images.githubusercontent.com/62062732/79111784-77a66900-7d7d-11ea-8469-52dad250b4ba.PNG)

Thanks in advance.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
