### ISSUE TITLE
Debug Drawing (and other toggles) not working in hot mode?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5464]
<img width="483" alt="screen shot 2016-08-17 at 11 36 49 am" src="https://cloud.githubusercontent.com/assets/11857803/17748579/f0c2e27c-646e-11e6-94b1-ff7b9782a533.png">

@devoncarew @johnmccutchan @Hixie 

I've not tried non-hot mode.    Using flutter/flutter@9bb9dc0b282deed3022e9c42c49425e51ae2cd05

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 7e7f5d21e3 (2 weeks ago), 2016-08-02 20:11:44
    • Engine revision 44a77da98a
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35
```

**Comment by devoncarew** [comment]
We could be sending messages to the wrong isolate.

**Comment by johnmccutchan** [comment]
The runner now keeps track of the current view which keeps track of the uiIsolate:

```currentView.uiIsolate.debugDraw...```

**Comment by devoncarew** [comment]
Atom talks to the cli tool for device notifications and for starting and stopping apps (and app output); it talks directly to the app for debugging and when sending the various flutter messages (like toggling debug drawing). It may be worth proxying the flutter messages through the flutter tool so it doesn't need to keep track of views in parallel.

**Comment by johnmccutchan** [comment]
@devoncarew That is my long term plan for how IDEs should communicate with flutter tools.

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-atom/dartlang/pull/1076
