### ISSUE TITLE
The flt-semantics-placeholder tag blocks touch input on iOS

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#54647]
On some iOS devices in Safari/Chrome (Flutter web), the `<flt-semantics-placeholder role="button" aria-label="Enable accessibility" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"></flt-semantics-placeholder>` blocks touch input.

A hack to prevent this is to add **display: none;** in the **style** attribute. I do this by calling a DOM manipulation helper right on the application start:

```
  import 'package:universal_html/html.dart' as html;

  static void hideSemanticsPlaceholder() {
    try {
      var s = html.window.document.getElementsByTagName('flt-semantics-placeholder');
      if(s != null && s.length > 0) {
        html.DivElement semanticsPlaceholder = s[0];
        semanticsPlaceholder.style.display = 'none';
      }
    } catch(error) {
      print(error.toString());
    }
  }
```

The tag becomes: `<flt-semantics-placeholder role="button" aria-label="Enable accessibility" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; display: none;"></flt-semantics-placeholder>`

Without this, the app looks like being unresponsive, although the hover event still works.

The flutter doctor output is bellow:

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E287, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
[✓] Connected device (4 available)
```

**Comment by VladyslavBondarenko** [comment]
Hi @Constans 
This is already fixed and should be in the framework soon https://github.com/flutter/flutter/issues/54325#issuecomment-611641999
Closing, if you disagree please write in the comments and I will reopen it
Thank you
