### ISSUE TITLE
[tool] [proposal] flutter upgrade should use hash-code / versioning system

### ISSUE THREAD

**Issue by alizera** [flutter/flutter#54656]
I'm using flutter from early versions and one painful difficulty is upgrading the SDK using `flutter upgrade`, it starts downloading all SDK files and after that starts downloading other building stuffs like `ios-release tools` and so one **while they might NOT be changed (or need to update)** and it takes a lot of time to finish downloading all stuffs (especially on slow connections (especially in Corona age)), I recommend using a hash-code or versioning system and if it is mandatory, download the files. Thanks for this magic project.

**Comment by jonahwilliams** [comment]
The engine artifacts have almost certainly changed on each roll. This is not likely to speed up downloading
