### ISSUE TITLE
Wrapping expanded on each item of a row not working with inkwell 

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#54653]
I have the following code snippet 

```
child: Row(
        mainAxisSize: MainAxisSize.max,
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: widget.items
            .map((item) => InkWell(
                  child: Expanded(child: buildIconItem(item)),
                  onTap: ()=>(),
                ))
            .toList(),
      );


This is my IconItem
Widget buildIconItem(IconButtonItem item) {
    Color color = item.disabled
        ? Colors.grey.shade400
        : item.selected
            ? Theme.of(context).accentColor
            : Theme.of(context).textTheme.caption.color;
    TextStyle textStyle = TextStyle(color: color);
    return Column(
      mainAxisSize: MainAxisSize.max,
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: <Widget>[
        ImageIcon(item.iconImage.image, size: 35, color: color),
        SizedBox(
          height: 6,
        ),
        Text(item.imageTitle, style: textStyle),
        SizedBox(
          height: 6,
        ),
        Visibility(child: Text(item.subTitle, style: textStyle),
          visible: item.subTitle != null,),
      ],
    );
  }

```

I expect each item to be expanded and between the ripple effect of one item to another item , there should not be any space left that doesn't show the ripple effect.

**Comment by iapicca** [comment]
Hi @nateshmbhat 
with this [sample code](https://gist.github.com/iapicca/fce39e2efa29ee787bf81feb26aad758)
the problem doesn't seem to be within the combination of  `row/column => expanded => row/column`
(although consider that using fixed size in expanded might cause overflow)

can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by nateshmbhat** [comment]
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.15.18-pre.1, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (3 available)

**Comment by TahaTesser** [comment]
Hi @nateshmbhat 
Does the code sample from [comment](https://github.com/flutter/flutter/issues/54653#issuecomment-612872924) solves your issue?

can you please provide your `flutter run --verbose` from root of your project?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by nateshmbhat** [comment]
Please see my SO question here : 
https://stackoverflow.com/questions/61187303/expanded-widget-not-working-with-inkwell-when-used-inside-a-row/61208689#61208689

It has better context.
The above code i provided itself is reproducible.

I needed to interchange inkwell and expanded.
We need a better documentation on expanded widget and example cases to handle things like this. Most people won't know that they have to do things in this specific way to get things working.

Many times it happens in a trial and error method and we need to avoid this.

**Comment by nateshmbhat** [comment]
Generally we expect this : 
+ Expanded will fully expand the row/column item.
+ wrapping an InkWell around expanded should make the whole expanded space also eligible for inkwell effect.

Since this doesn't work , looking through the doc should somehow mention things related to this..

**Comment by iapicca** [comment]
HI @nateshmbhat 
testing the [code above](https://github.com/flutter/flutter/issues/54653#issuecomment-612872924) with the latest master

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (11 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the inkwell ripple effect works properly on mobile, but fails on web (regression)
if the code sample doesn't represent the issue, please provide a complete minimal reproducible code sample
Thank you

**Comment by ferhatb** [comment]
Verified this works on latest master. Tested on Chrome both debug and release modes. Please reopen issue if you see otherwise.
