### ISSUE TITLE
[webview_flutter] plugin will display a frame with black when I relayout the height of the webview

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#54652]
I use the webview to display a static html, after I get the document height of the html, I need to relayout the height by call setState(), there is a black view during the new display comes, How to avoid this black view, 

I have went through the sdk of webview, when use the androidView to build it, flutter use the canvas to display the webview from platform by pictures?

Flutter related information:
Flutter 1.12.13+hotfix.5 channel stable
Dart 2.7

**Comment by TahaTesser** [comment]
Hi @ping996 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ping996** [comment]
WebView: 
dependencies:
  webview_flutter: ^0.3.19+9

Flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale zh_CN.utf8)
• Flutter version 1.12.13+hotfix.5 at /home/oppo/wuchuanping/mocha/maflutter_12_sdk/flutter
• Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
• Engine revision 2994f7e1e6
• Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /home/oppo/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: /home/oppo/android_studio/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✓] Android Studio (version 3.5)
• Android Studio at /home/oppo/android_studio/android-studio
• Flutter plugin version 41.1.2
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.35.1)
• VS Code at /usr/share/code
• Flutter extension version 3.2.0

[✓] Connected device (1 available)
• PCAM00 • 74f892cf • android-arm64 • Android 9 (API 28)

example code:

yoga.setHeight("200px");  //set a default value, if not, the andview will cause a exception.
//.........
static var reload = false;
WebView(
  key: GlobalKey(),
  initialUrl: htmlBody,     //it has encoded to utf-8 before
  javascriptMode: JavascripteMode.unrestricted,
  onPageStarted: (String url, String height) {
    //I used the yoga to layout, 
    yoga.setHeight(height);
    if(!reload) {
       setState((){}); 
       reload = true; 
   }    
)

I also has customed the android side of webview code to get the height of the current html body.
when the height from the callback of onPageStarted, then trigger a relayout of the current view, there will be a black view during the new view.

**Comment by ping996** [comment]
When I updated the static html file, I needs to call setState() to build the new layout because the content of html changed, the height is also changed, so the it will create another Webview.
