### ISSUE TITLE
Execution failed for task ':app:compileDebugKotlin'.

### ISSUE THREAD

**Issue by OmkarKhilari** [flutter/flutter#54662]
```bash
terimaut@terimaut-Inspiron-5558:~/Desktop/Samples/fun$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
e: /home/terimaut/Desktop/Samples/fun/android/app/src/main/kotlin/com/example/fun/MainActivity.kt: (1, 21): Package name must be a '.'-separated identifier list
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileDebugKotlin'.                    
> Compilation error. See log for more details                           
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 28s                                                  
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        90.2s
Gradle task assembleDebug failed with exit code 1
```

**Comment by OmkarKhilari** [comment]
My flutter is up to date with 0 issues.

**Comment by iapicca** [comment]
Hi @OmkarKhilari 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by OmkarKhilari** [comment]
@iapicca I had same issue on windows 10 so I installed ubuntu but the isuue still continued....
The issue is same for android studio as well as VS code...
Flutter Doctor::

terimaut@terimaut-Inspiron-5558:~$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.9 at /home/terimaut/Documents/FlutterSDK/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/terimaut/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/87/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/87/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
.....................................................


My pubspec.yaml

name: fun
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by TahaTesser** [comment]
Hi @OmkarKhilari 
can you please provide your `flutter run --verbose`?
Also please post your `build.gradle` from your Android folder
Thanks

**Comment by OmkarKhilari** [comment]
Hi @TahaTesser Hope you will find issue.My flutter is up to date with 0 issues.

My flutter run --verbose is
terimaut@terimaut-Inspiron-5558:~/Desktop/Samples/fun$ flutter run --verbose
[  +30 ms] executing: [/home/terimaut/Documents/FlutterSDK/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +153 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/home/terimaut/Documents/FlutterSDK/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +12 ms] executing: [/home/terimaut/Documents/FlutterSDK/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/terimaut/Documents/FlutterSDK/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +102 ms] executing: [/home/terimaut/Documents/FlutterSDK/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +139 ms] executing: /home/terimaut/Android/Sdk/platform-tools/adb devices -l
[  +21 ms] Exit code 0 from: /home/terimaut/Android/Sdk/platform-tools/adb devices -l
[   +4 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +52 ms] /home/terimaut/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +65 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +290 ms] Generating /home/terimaut/Desktop/Samples/fun/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +47 ms] ro.hardware = ranchu
[  +78 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +33 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +19 ms] executing: /home/terimaut/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +28 ms] Exit code 0 from: /home/terimaut/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           04-15 12:57:58.791 E/GnssHAL_GnssInterface( 1745): gnssSvStatusCb: b: input svInfo.flags is 8
[  +12 ms] executing: /home/terimaut/Android/Sdk/platform-tools/adb version
[   +1 ms] executing: /home/terimaut/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -T 04-15 12:57:58.791
[  +33 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/terimaut/Android/Sdk/platform-tools/adb
[   +4 ms] executing: /home/terimaut/Android/Sdk/platform-tools/adb start-server
[  +27 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from /home/terimaut/Desktop/Samples/fun/android/gradlew.
[  +24 ms] executing: /snap/android-studio/87/android-studio/jre/bin/java -version
[ +118 ms] Exit code 0 from: /snap/android-studio/87/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +5 ms] executing: [/home/terimaut/Desktop/Samples/fun/android/] /home/terimaut/Desktop/Samples/fun/android/gradlew -Pverbose=true
-Ptarget=/home/terimaut/Desktop/Samples/fun/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[ +816 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[        ]  - Incremental Groovy compilation
[        ]  - Groovy compile avoidance
[   +1 ms]  - Test fixtures for Java projects
[   +5 ms]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+1252 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +96 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +94 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[  +99 ms] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +199 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +99 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[  +99 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[+1698 ms] > Task :app:compileDebugKotlin FAILED
[   +1 ms] 16 actionable tasks: 4 executed, 12 up-to-date
[   +7 ms] e: /home/terimaut/Desktop/Samples/fun/android/app/src/main/kotlin/com/example/fun/MainActivity.kt: (1, 21): Package name must be a '.'-separated identifier list
[   +7 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[   +1 ms] * Try:
[   +4 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[ +390 ms] Running Gradle task 'assembleDebug'... (completed in 5.0s)
[   +6 ms] "flutter run" took 5,992ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)




build.gradle is-------------------

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by TahaTesser** [comment]
Could be related [#53070](https://github.com/flutter/flutter/issues/53070)

**Comment by jonahwilliams** [comment]
The error is pretty clear in the logs here:

```
/home/terimaut/Desktop/Samples/fun/android/app/src/main/kotlin/com/example/fun/MainActivity.kt: (1, 21): Package name must be a '.'-separated identifier list
```

If your package name is invalid, the kotlin compile will fail. Closing as this is not an issue with flutter

**Comment by kidussc** [comment]
i'm having problems like @MautKaFarishta 
please help

**Comment by MautKaFarishta** [comment]
@kidussc I had this issue on Windows so I installed ubuntu and the issue was still there I didn't changed anything my first demo app from flutter was not even working...It was showing same issue.But later I tried on different machine and the problem wasn't there I don't know what happened but I assumed this was my machine's fault.

**Comment by alexisenp** [comment]
Sorry for comenting closed and old post.
But im having the same problem.
How do you solve it ??

hope you have the answer, cant find a solution over internet.

im thinking to make a new project and copy and paste a more than year of coding :c

**Comment by Isuru01** [comment]
> @kidussc I had this issue on Windows so I installed ubuntu and the issue was still there I didn't changed anything my first demo app from flutter was not even working...It was showing same issue.But later I tried on different machine and the problem wasn't there I don't know what happened but I assumed this was my machine's fault.

How did you fix this I have the same issue?

**Comment by MautKaFarishta** [comment]
> > @kidussc I had this issue on Windows so I installed ubuntu and the issue was still there I didn't changed anything my first demo app from flutter was not even working...It was showing same issue.But later I tried on different machine and the problem wasn't there I don't know what happened but I assumed this was my machine's fault.
> 
> How did you fix this I have the same issue?

I was never able to solve this error till the end I had to try on a new machine.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by yassminemam** [comment]
Cloud you explain how did u solve this problem, please?
