### ISSUE TITLE
[request] Add lint to replace Container with SizedBox when possible

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#54672]
This could become a useful lint rule.
If `Container(width: ..., height: ..., child: ...)`, transform into `SizedBox(width: ..., height: ..., child: ...)`.

https://github.com/flutter/flutter/pull/54495

**Comment by HansMuller** [comment]
CC @a14n

**Comment by Zazo032** [comment]
I think you can use [`sized_box_for_whitespace`](https://github.com/dart-lang/linter/pull/2049) (probably only on newer versions of the sdk).

**Comment by bernaferrari** [comment]
oh! I would have never guessed that did it. Name is kind unintuitive but makes sense. Thanks.
