### ISSUE TITLE
[animations] Add a pointer in the README on how to properly add new issues targeted at the animations package

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#54671]
Since `flutter/packages` doesn't have its own issue-tracking, we should direct developers interested in filing issues on how to properly file issues under `flutter/flutter` and add the correct labels, such as `package` and `p: animations`.

**Comment by stuartmorgan** [comment]
> Since `flutter/packages` doesn't have its own issue-tracking, we should direct developers interested in filing issues on how to properly file issues under `flutter/flutter`

We now have the "View/report issues" link on pub.dev, so I'm going to consider this fixed.

> and add the correct labels, such as `package` and `p: animations`.

Only project members can add labels, so we can't tell people to do that.
