### ISSUE TITLE
Invalid `Podfile` file: no implicit conversion of nil into String. copied_flutter_dir = File.join(__dir__, 'Flutter')

### ISSUE THREAD

**Issue by lincbarr** [flutter/flutter#54675]
When attempting to run the iOS version of any app, I get the following errors on the console:

Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: no implicit conversion of nil into String.

     #  from /Users/JLB/Development/FlutterProjects/ShopApp/shop_app/ios/Podfile:41
     #  -------------------------------------------
     #  
     >    copied_flutter_dir = File.join(__dir__, 'Flutter')
     #    # copied_flutter_dir = File.join('.', 'Flutter')
     #  -------------------------------------------

    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `new'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:259:in `from_file'
    /Users/JLB/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:200:in `podfile'
    /Users/JLB/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Users/JLB/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
    /Users/JLB/.rvm/gems/ruby-2.1.2@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/JLB/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/JLB/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /Users/JLB/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
    /Users/JLB/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
    /Users/JLB/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    /Users/JLB/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

Error running pod install
Error launching application on iPhone 11.

The solution is to change line 41 in the Podfile _from:_

`copied_flutter_dir = File.join(__dir__, ‘Flutter’)`

_to:_

`copied_flutter_dir = File.join(‘.’, ‘Flutter’)`

Flutter version: 1.12.13+hotfix.9

Dart version: 2.7.2

**Comment by jmagman** [comment]
Can we get the output of `$ ruby -v`?

**Comment by g0rdan** [comment]
@lincbarr I have the same issue.
`ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin14.0]`
Apparently, it is not the latest version :)

**Comment by lincbarr** [comment]
Ruby:  ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

Mr. J. Lincoln Barr

j.lincoln.barr@gmail.com

**Comment by lincbarr** [comment]
I just updated ruby on my machines to ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]. I am working on a new project that currently does not have a podfile. When it does, I will get back to you with the results.
 
Mr. J. Lincoln Barr

j.lincoln.barr@gmail.com

**Comment by lincbarr** [comment]
The updated ruby solved the issue with the pod file.

Thank you!

— Lincoln Barr —


Mr. J. Lincoln Barr

j.lincoln.barr@gmail.com

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/59044/files#diff-9a4a61b0e60143d9364139b944b2d485R59.

**Comment by danielgchap** [comment]
SERIOUS WITH THIS GARBAGE!?!?!? Unreal. Flutter used to be so solid and you guys have seriously fucked it up as of late. Thank you so much.

**Comment by aboutmydreams** [comment]
> Fixed by https://github.com/flutter/flutter/pull/59044/files#diff-9a4a61b0e60143d9364139b944b2d485R59.

same problem in latest

**Comment by jmagman** [comment]
@aboutmydreams `File.join(__dir__` doesn't exist anywhere in master.  Can you file a new bug and completely fill out the template?

**Comment by jamesdhope** [comment]
Same problem here. 

Ruby is up to date. I've replaced File.join(__dir__ with File.join('.', 

Flutter run produces...

[!] Invalid `Podfile` file: no implicit conversion of nil into String.
 #  from /Users/james/boog projects/boog-webrtc-demo/flutter-webrtc-demo/ios/Podfile:55
 #  -------------------------------------------
 #      unless File.exist?(copied_framework_path)
 >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
 #      end
 #  -------------------------------------------

**Comment by jmagman** [comment]
@jamesdhope
>  `File.join(__dir__` doesn't exist anywhere in master. Can you file a new bug and completely fill out the template?

**Comment by terenceponce** [comment]
My computer was on Mojave and my Flutter app was successfully compiling back then. It accidentally upgraded to Big Sur and even with a fresh install, I am now getting this error. Why is this happening and has this been solved?

I tried running `pod install` on both Ruby 2.7.2 and 3.0.0 and it failed on both of them. Rbenv was used instead of the system ruby.

Is there a solution for this?

**Comment by jmagman** [comment]
@terenceponce Flutter uses the version of `pod` available in your `PATH`, however you install it.  There's some hints in https://guides.cocoapods.org/using/getting-started.html about how to install it with sudoless install.

If you think you have `pod` installed correctly on your `PATH` and you think this is an issue with Flutter tooling and not your CocoaPods installation:
 
> `File.join(__dir__` doesn't exist anywhere in master. Can you file a new bug and completely fill out the template?
