### ISSUE TITLE
[cocoon] Authorize agent failed

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#54677]
The authorize-agent API is broken at the moment.

<img width="1035" alt="Screen Shot 2020-04-13 at 11 39 49" src="https://user-images.githubusercontent.com/6259181/79149201-a58aae00-7d7b-11ea-9f8b-3e2863dd7eb7.png">

/cc @godofredoc @keyonghan @CaseyHillers

**Comment by godofredoc** [comment]
There are no logs suggesting this is happening at server side, can we get logs from the client side

**Comment by keyonghan** [comment]
Confirmed backend API works.

**Comment by keyonghan** [comment]
Yes. It is okay to change either side.
