### ISSUE TITLE
problem with  flutter doctor  [Oops; flutter has exited unexpectedly.]

### ISSUE THREAD

**Issue by khitermedachraf** [flutter/flutter#54684]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

[flutter_01.log](https://github.com/flutter/flutter/files/4471517/flutter_01.log)
```
```
ssd

**Comment by VladyslavBondarenko** [comment]
Hi @khitermedachraf 
do you have `where.exe` in your `C:\Windows\System32\`?
do you have `C:\Windows\System32\` path in your environment variables?
If no, adding this should help.
Related to https://github.com/flutter/flutter/issues/14887
Closing, comment please if this doesn't help and I'll reopen the issue.
Thank you

**Comment by khitermedachraf** [comment]
hey Bro thanks . i find the prog where.exe 
but what should i name the path : C:\Windows\System32\ ?

**Comment by VladyslavBondarenko** [comment]
@khitermedachraf 
In Environment Variables you have two list: User variables and System variables. Both of them have the variable Path, edit the Path variable in both lists with adding the new value `C:\Windows\System32\` to it, if it isn't there already

**Comment by khitermedachraf** [comment]
Yeahh thank you so much bro
It works Know
