### ISSUE TITLE
Update in-app-purchase documentation to let users completePurchase for Android

### ISSUE THREAD

**Issue by coolnalu** [flutter/flutter#54681]
The plugin is very helpful. However I've lost $$$ of revenue and frustrated users because the documentation tells me to only call `completePurchase` for iOS. As a result, many purchases on Google Play get refunded automatically after 3 days. 

![image](https://user-images.githubusercontent.com/319604/79151801-1f7d6000-7d99-11ea-918c-861437420ab0.png)

**Comment by VladyslavBondarenko** [comment]
Hi @coolnalu 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/51902 and thumb it up,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
