### ISSUE TITLE
Semantics focus lost after the focused widget is updated/removed

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#54695]
Internal bug: b/153847891

I managed to write a min reproduction case to demonstrate this bug on Android

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(title: 'Voiceover Bug', home: FirstRoute()));
}

class FirstRoute extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _FirstRoute();
}

class _FirstRoute extends State {
  bool _showSecondButton = true;

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('First Route')),
      body: Column(children: [
        RaisedButton(
          child: Text('Button 1'),
          onPressed: () => setState(() => _showSecondButton = true),
        ),
        Visibility(
          visible: _showSecondButton,
          child: RaisedButton(
            child: Text('Button 2'),
            onPressed: () => setState(() => _showSecondButton = false),
          ),
        ),
      ]),
    );
  }
}
```

Refer to the attachments for screen recordings. Note that this is only observed on Android but not iOS.

[See internal bug for attachments]

**Comment by HansMuller** [comment]
CC @goderbauer

**Comment by goderbauer** [comment]
I just looked at what Android does natively and it appears it behaves exactly like observed. When the currently focused a11y node disappears from the screen, nothing new receives a11y focus. 

I tested this in the notification drawer. There was a button to dismiss all "silent notifications". After activation the dismiss button disappeared and with that nothing was left with a11y focus.

**Comment by goderbauer** [comment]
I've reached out to @vick08 to get his take on whether this is expected behavior.

**Comment by goderbauer** [comment]
I've posted some videos on the internal issue showing that Android natively behaves like observed.

**Comment by goderbauer** [comment]
Based on the response to the internal bug I am marking this as "Declined Customer Request".
