### ISSUE TITLE
TapGestureRecognizer in text span not detect small words -- if it one or two characters

### ISSUE THREAD

**Issue by mahmoudatef925** [flutter/flutter#54690]

**Comment by VladyslavBondarenko** [comment]
Hi @mahmoudatef925 
I'm trying this code sample

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        backgroundColor: Colors.grey,
        body: Center(
          child: RichText(
            text: new TextSpan(text: 'Non touchable. ', children: [
              new TextSpan(
                text: 't',
                recognizer: new TapGestureRecognizer()..onTap = () => print('t onTap'),
              )
            ]),
          ),
        )
      ),
    );
  }
}
```

It's working when tapping on single 't'. Tried with `dev v1.18.0-dev.5.0` on Android 10 emulator and iOS 13.4 device.

Please provide your `flutter doctor -v`, code sample and on what platform are you experiencing this.

**Comment by mahmoudatef925** [comment]
Hi @VladyslavBondarenko thanks for your effort ,
i tried your sample it works fine but not with different styles , 
can you try this sample and provide me with solution
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Map<String, Color> chars = {
    "A": Colors.red,
    "B": Colors.blue,
    "V": Colors.purple,
    "W w": Colors.black,
    "G": Colors.green,
  };
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Center(
        child: RichText(
          textDirection: TextDirection.rtl,
          textAlign: TextAlign.center,
          text: TextSpan(children: [
            for (MapEntry<String, Color> char in chars.entries)
              TextSpan(
                text: char.key,
                style: TextStyle(color: char.value),
                recognizer: TapGestureRecognizer()
                  ..onTap = () => print('${char.key} onTap'),
              )
          ]),
        ),
      )),
    );
  }
}
---------------------------------------------------------------------
flutter doctor -v result 
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale
    en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Mahmoud\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.44.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by VladyslavBondarenko** [comment]
@mahmoudatef925 
Gestures recognised for all of the letters, checked on `stable, v1.12.13+hotfix.9` with 
```
Redmi Note 7              • 6345c469      • android-arm64 • Android 9 (API 28)
Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)
```
Are gestures not recognised for any of the letters? on for some of them?

**Comment by mahmoudatef925** [comment]
Some of them ,
this is my log on tap on each char
``I/flutter ( 5625): A onTap
I/flutter ( 5625): A onTap
I/flutter ( 5625): A onTap
I/flutter ( 5625): A onTap
I/flutter ( 5625): W w onTap
I/flutter ( 5625): W w onTap
I/flutter ( 5625): G onTap

**Comment by mahmoudatef925** [comment]
and this when i removed TextSpan style it works correctly

```I/flutter` ( 5997): A onTap
I/flutter ( 5997): B onTap
I/flutter ( 5997): V onTap
I/flutter ( 5997): W w onTap
I/flutter ( 5997): W w onTap
I/flutter ( 5997): G onTap

**Comment by mahmoudatef925** [comment]
Hi @VladyslavBondarenko 
any updates ?!

**Comment by mahmoudatef925** [comment]
Hi @VladyslavBondarenko
when i switched to master channel it works fine 
Flutter 1.14.7-pre.83 • channel master • github.com/flutter/flutter.git Framework • revision e10df3c1a6 (3 months ago) • 2020-02-01 11:23:01 +0800 Engine • revision e625e174c5 Tools • Dart 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)

**Comment by VladyslavBondarenko** [comment]
@mahmoudatef925 
Thanks for the input, closing as fixed
if you disagree please write in the comments and I will reopen it

**Comment by mahmoudatef925** [comment]
when it can pushed to stable channel ?
i have project depends on many packages after switched to master i get many problems in packages

**Comment by VladyslavBondarenko** [comment]
@mahmoudatef925 
I checked, it works with current beta, you may consider to use it.
It could be an option to pull only specific fix https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release, but then knowing of what commits are responsible for needed fix is needed

**Comment by mahmoudatef925** [comment]
thanks @VladyslavBondarenko
