### ISSUE TITLE
Delegates

### ISSUE THREAD

**Issue by lucas404x** [flutter/flutter#54701]
Hi, everybody. I'm starting with Flutter! I have a question: what are **delegates** in Flutter? I don't find anything by official documentation.

**Comment by jonahwilliams** [comment]
A delegate is a software engineering pattern, see also: https://en.wikipedia.org/wiki/Delegation_pattern

There is nothing special about delegates in flutter, they are just regular classes that implement a delegate pattern

**Comment by lucas404x** [comment]
thank you very much. I'm beginner haha
