### ISSUE TITLE
Cloning the repo in order to use Flutter means downloading all the diffs

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5471]
The current workflow when building Flutter apps means cloning the repo. The more we work on it, the more it will grow.

Maybe we should have a way of only keeping the contents of `HEAD` (and not the whole git history) in the future? (at least for the people who are not working on Flutter directly)

**Comment by abarth** [comment]
There's a `--depth` argument to `git clone` that does this for free.

**Comment by dragostis** [comment]
@abarth Yup! It might be a good idea to either add that to the docs.

**Comment by abarth** [comment]
We can add it to the docs at the point in time where it becomes a problem.

**Comment by dragostis** [comment]
@abarth Will we always have a dependency on git in order to build Flutter apps, though?

**Comment by abarth** [comment]
Forever is a long time.  The plan is to solve problems as they arise.  This is currently a non-problem, so we're not going to solve it.
