### ISSUE TITLE
Flutter Driver error when running key from widget

### ISSUE THREAD

**Issue by FredrickP** [flutter/flutter#54711]
I am trying to write an integration test for my flutter application. I have a custom widget which I am using to create a TextField with our custom widget. I have created a [gist](https://gist.github.com/FredrickP/ec3943fc65ba514474d6e2b8b043903d.js) for the widget if you want to have a look. But I am having some problem running integration test with this widget.

### Steps to Reproduce
As part of my integration test, I need to tap on this TDTextField and enter some text into it. When adding the widget to my application, I also add a key to it

```
Widget formInput(BuildContext context){
        this.txtEmail = new TDTextInput(
          key: Key('lgnEmail'),
          labelText: UserLanguage.stringCollections[lang]['labelEmail'],
          keyboardType: TextInputType.emailAddress,
          autofocus: false,
          focusNode: emailNode,
          errorText: emailError,
          controller: emailController,
          onChanged: (val){
            if(emailError != null){
              if(mounted){
                setState(() {
                  emailError = null;            
                });
              }
            }
          },
          hintText: UserLanguage.stringCollections[lang]['hintEmail'],
          autocorrect: false,
          containerMargin: const EdgeInsets.only(top: 20.0),
        );
```

Now, in my integration test, this is what I'm trying to do

`import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
void main() {

    group('Flutter Driver', () {
      FlutterDriver driver;
 
      setUpAll(() async{ 
        driver = await FlutterDriver.connect();
      });

      tearDownAll(() async {
        if (driver != null) {
          await driver.close();
        }
      });

      test('check flutter driver health', () async {
        Health health = await driver.checkHealth();
        print(health.status);
      });
  
      test('Flutter Driver' , () async{
        
        await driver.tap(find.byValueKey('fpEmail'));
        await driver.enterText('fredrick@tanamduit.com');
        await driver.waitFor(find.text('fredrick@tanamduit.com'));
        await driver.enterText('Success');
        await driver.waitForAbsent(find.text('fredrick@tanamduit.com'));
        print('Label email ForgotPassword success');
      }); 
    });
  
}`

And when I run it, this is the error that comes up.

>  DriverError: Failed to fulfil Tap due to remote error
  Original error: Bad state: The client closed with a pending request "ext.flutter.driver".

**Note**
This error only comes up when I use my custom widget. If I use a TextField this integration test passes.

### Logs
`00:06 +0: Flutter Driver check flutter driver health
HealthStatus.ok
00:06 +1: Flutter Driver Flutter Driver
[warning] FlutterDriver: tap message is taking a long time to complete...
I/flutter ( 6960):
I/flutter ( 6960):
I/flutter ( 6960): responseStatusCode 200
I/flutter ( 6960): {"list":[{"targetUrl":"https://id.tanamduit.com/promo-proteksi-dbd-gopay-banner","slideDuration":"5000","bannerName":"PromoBeli Proteksi DBD bonus Saldo GoPay!","bannerDescription":"Promo Beli Proteksi DBD bonus Saldo
GoPay!","desktopImg":"xxx","desktopLargeImg":"xxx","mobileLandscapeImg":"xxx","mobilePortraitImg":"xxx","tabletImg":"xxx","mobileAppImg":"https://id.tanamduit.com/wp-content/uploads/2020/04/promo-proteksi-dbd-gopay-banner-apps.png","mobileAppBigImg":"https://id.tanamduit.com/wp-content/uploads/2020/04/promo-proteksi-dbd-gopay-banner-apps.png"},{"targetUrl":"https://id.tanamduit.com/promo-investasi-bonus-proteksi-banner","slideDuration":"5000","bannerName":"Promo Investasi Bonus Proteksi Bebas Penyakit ","bannerDescription":"Promo Investasi Bonus Proteksi Bebas
Penyakit
I/flutter ( 6960):
","desktopImg":"xxx","desktopLargeImg":"xxx","mobileLandscapeImg":"xxx","mobilePortraitImg":"xxx","tabletImg":"xxx","mobileAppImg":"https://id.tanamduit.com/wp-content/uploads/2020/04/promo-investasi-bonus-proteksi-banner-apps.png","mobileAppBigImg":"https://id.tanamduit.com/wp-content/uploads/2020/04/promo-investasi-bonus-proteksi-banner-apps.png"},{"targetUrl":"https://id.tanamduit.com/perlindungan-terhadap-virus-corona-banner","slideDuration":"5000","bannerName":"Lindungi diri kamu dari Virus Corona","bannerDescription":"Virus Corona termasuk penyakit yang
dicover pada fitur Asuransi Proteksi Bebas Penyakit di
I/flutter ( 6960):
tanamduit!","desktopImg":"xxx","desktopLargeImg":"xxx","mobileLandscapeImg":"xxx","mobilePortraitImg":"xxx","tabletImg":"xxx","mobileAppImg":"https://id.tanamduit.com/wp-content/uploads/2020/02/perlindungan-terhadap-virus-corona-banner-apps.png","mobileAppBigImg":"https://id.tanamduit.com/wp-content/uploads/2020/02/perlindungan-terhadap-virus-corona-banner-apps.png"},{"targetUrl":"https://id.tanamduit.com/siap-lawan-dbd-banner","slideDuration":"5000","bannerName":"Musim hujan, bersiap lawan DBD","bannerDescription":"Tetap tenang di tengah wabah demam berdarah
dengan perlindungan Proteksi DBD di
tanamduit","desktopImg":"xxx","desktopLargeImg":"xxx","mobileLandscapeImg":"xxx","mobilePortraitImg":"xxx","tabletImg":"xxx","mobileAppImg":"https://id.tanamduit.com/wp-content/uploads/2020/03/siap-lawan-dbd-banner-apps.png","mobileAppBigImg":"https://id.tanamduit.com/wp-content/uploads/2020/03/siap-lawan-dbd-banner-apps.png"}],"numberOfRecords":4,"message":"Mobile Individual Banner
I/flutter ( 6960): List","status":1,"duration":8,"tenant":"tanamduit","success":"Mobile Individual Banner List"}
I/flutter ( 6960):
I/flutter ( 6960):
I/flutter ( 6960): responseStatusCode 200
I/flutter ( 6960): {"list":[{"title":"Apa itu Reksa Dana?","shortDesc":"Investasi paling kekinian. Pelajari tentang Reksa Dana di
sini!","imageUrl":"https://cdn.tanamduit.com/images/promo/newapp/reksadana.jpg","linkUrl":"https://id.tanamduit.com/reksa-dana"},{"title":"Apaitu SBN?","shortDesc":"Surat Berharga Negara? Apa itu? Pelajari mengenai SBN di
sini!","imageUrl":"https://cdn.tanamduit.com/images/promo/newapp/sbn.jpg","linkUrl":"https://id.tanamduit.com/sbn"},{"title":"Asuransi kini
hadir di tanamduit","shortDesc":"Sekarang kamu bisa proteksi diri kamu dengan asuransi di tanamduit. Pesan
sekarang!","imageUrl":"https://cdn.tanamduit.com/images/promo/newapp/asuransi.jpg","linkUrl":"https://id.tanamduit.com/asuransi"}],"numberOfRecords":3,"language":"id","type":"blogs","message":"Mobile Individual Content
List","status":1,"duration":4,"tenant":"tanamduit","success":"Mobile Individual Content List"}
I/flutter ( 6960):
I/flutter ( 6960):
I/flutter ( 6960): responseStatusCode 200
I/flutter ( 6960): {"periodType":"1d","performanceList":[{"formattedNavValue":"1,512.86","formattedNavAsOf":"13-04-2020","productType":"Pasar
Uang","productRiskLevel":"Rendah","formattedPerformance":"0.0774","periodType":"1d","formattedProductLaunchDate":"23-01-2009","productName":"Manulife Dana Kas
II","productImage":"https://cdn.tanamduit.com/images/product/MAN02.png","productCode":"MAN02MMCID086000"},{"formattedNavValue":"1,468.48","formattedNavAsOf":"13-04-2020","productType":"Pasar
Uang","productRiskLevel":"Rendah","formattedPerformance":"0.0722","periodType":"1d","formattedProductLaunchDate":"20-10-2014","productName":"Sucorinvest Money Market
Fund","productImage":"https://cdn.tanamduit.com/images/product/GAMA2.png","productCode":"GAMA2MMCMONEYM00"},{"formattedNavValue":"1,408.88","formattedNavAsOf":"13-04-2020","productType":"Pasar
Uang","productRiskLevel":"Rendah","formattedPerformance":"0.0717","periodType":"1d","formattedProductLaunchDate":"01-03-2004","productName":"Aberdeen Standard Indonesia Money Market
I/flutter ( 6960):
Fund","productImage":"https://cdn.tanamduit.com/images/product/RO002.png","productCode":"RO002MMCJKU13300"},{"formattedNavValue":"1,368.1","formattedNavAsOf":"13-04-2020","productType":"Pasar
Uang","productRiskLevel":"Rendah","formattedPerformance":"0.0658","periodType":"1d","formattedProductLaunchDate":"12-06-2015","productName":"Syailendra Dana
Kas","productImage":"https://cdn.tanamduit.com/images/product/SYA02.png","productCode":"SYA02MMCMMSDAK00"},{"formattedNavValue":"1,148.02","formattedNavAsOf":"13-04-2020","productType":"Pasar
Uang","productRiskLevel":"Rendah","formattedPerformance":"0.0650","periodType":"1d","formattedProductLaunchDate":"05-10-2017","productName":"Syailendra Sharia Money Market
Fund","productImage":"https://cdn.tanamduit.com/images/product/SYA02.png","productCode":"SYA02MMSMSSMMF00"}],"numberOfRecords":5,"message":"Fund Product List","status":1,"duration":5}
00:36 +1 -1: Flutter Driver Flutter Driver [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

00:37 +1 -1: Flutter Driver (tearDownAll)
00:37 +1 -1: Flutter Driver Flutter Driver [E]
  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1120:38)
  #4      _CustomZone.run (dart:async/zone.dart:1021:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:566:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #13     _rootRun (dart:async/zone.dart:1124:13)
  #14     _CustomZone.run (dart:async/zone.dart:1021:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

  package:flutter_driver/src/driver/driver.dart 426:7   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                     _Completer.completeError
  dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                          _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 86:23               _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 459:11  FlutterDriver.tap
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15      Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>

00:37 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Stopping application instance.
Driver tests failed: 255`

### Flutter Analyze
` info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:18:26 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:22:38 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:27:38 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:32:36 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:37:34 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:41:36 - close_sinks
   info - Close instances of `dart.core.Sink` - aliossflutter\lib\aliossflutter.dart:46:40 - close_sinks
   info - Don't import implementation files from another package -
          lib\View\Fragments\Dashboards\SummaryPortfolio\FragmentMFPerformance.dart:21:8 - implementation_imports

8 issues found. (ran in 35.7s)`

### Flutter doctor -v
`[√] Flutter (Channel unknown, v1.7.8, on Microsoft Windows [Version 10.0.17763.1098], locale en-ID)
    • Flutter version 1.7.8 at C:\flutter\flutter
    • Framework revision d51fd86cdb (10 months ago), 2019-06-21 22:31:55 -0400
    • Engine revision d004bcd4d6
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.21)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.1064

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows                   • Windows       • windows-x64    • Microsoft Windows [Version 10.0.17763.1098]
    • web                       • web           • web-javascript • Google Chrome 80.0.3987.163

• No issues found!`

**Comment by TahaTesser** [comment]
Hi @FredrickP 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem, gist link is broken and your code sample is incomplete 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
