### ISSUE TITLE
Github has no option to search for projects written in "Flutter"

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#54718]
More of an issue with github, but right now it has no option to search for projects written in Flutter.
![image](https://user-images.githubusercontent.com/283347/79189440-040a6780-7e22-11ea-9cb2-b9d5e406f009.png)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by stuartmorgan** [comment]
Flutter is a framework, rather than a language. The language for a Flutter project is Dart, which is in the list.
