### ISSUE TITLE
New way to download binary assets required by our repo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5472]
Requesting a new way (script, spec, tool integration, etc) to pull down binary assets required by the Flutter repo.

(This blocks https://github.com/flutter/flutter/issues/5404)

**Comment by sethladd** [comment]
cc @abarth @Hixie

**Comment by eseidelGoogle** [comment]
I'm not sure I understand what this is asking for.  It looks like the bug this was blocking got closed.  Speculatively closing.
