### ISSUE TITLE
SliverFillRemaining Widget creates overflow with TextFields

### ISSUE THREAD

**Issue by splangi** [flutter/flutter#54729]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Minimal reproducable MyApp class from the template. 
```
class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug demo',
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverFillRemaining(
              child: Column(
                children: <Widget>[
                  TextField(),
                  Container(
                    height: 400.0,
                  ),
                ],
              ),
              hasScrollBody: false,
            )
          ],
        ),
      ),
    );
  }
}
```
3. Click the textfield (opening the keyboard) and scroll down.

**Expected results:** 
I expect that the layout works without any overflowing 

**Actual results:** 
The layout overflows when the keyboard is open from the bottom. Adding more textfields will increase the overflow.  Removing textfields and replacing with a button that forces the keyboard open works as well. 
```
MaterialButton(onPressed: (){
                    SystemChannels.textInput.invokeMethod('TextInput.show');
                  }, child: Text("Open keyboard"),),
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E287, locale et-EE)
    • Flutter version 1.15.17 at /Users/siim/Binaries/flutter
    • Framework revision 2294d75bfa (6 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc2)
    • Android SDK at /Users/siim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = /Users/siim/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/siim/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • ONEPLUS A5010             • ec1cbc19      • android-arm64 • Android 9 (API
      28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10
      (API 29) (emulator)


```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @splangi 
you can write this way

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: MaterialApp(
        title: 'Bug demo',
        home: Scaffold(
          body: CustomScrollView(
            slivers: <Widget>[
              SliverList(
                delegate: SliverChildListDelegate([
                  TextField(),
                ]),
              ),
              SliverFillRemaining(
                child: Container(
                  height: 400.0,
                ),
                hasScrollBody: false,
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

is it what you want to achieve?

**Comment by splangi** [comment]
@VladyslavBondarenko Unfortunately this is not what I want to achieve. I have a working workaround for the issue already (I wrap the textfields inside fixed height containers, which resolves the issue), but it's a hack and SliverFillRemaining(hasScrollBody: false) should support any view as it's child, including textfields.

**Comment by VladyslavBondarenko** [comment]
I can't reproduce it with `stable v1.12.13+hotfix.9`, but can with `dev 1.18.0-dev.5.0` and `beta 1.17.0`

**Comment by Piinks** [comment]
Hey @splangi I have not been able to reproduce this. @VladyslavBondarenko also said above it hasn't been reproduced yet. Can you provide an image or further explanation of the bug you are experiencing? Thanks!

**Comment by VladyslavBondarenko** [comment]
@Piinks 
I mean this code sample is working fine with current stable, but when using current beta or dev channel, I can see the overflow.
(In the code sample I changed `height` to `600.0`, because 400 px fits between the TextField and keyboard for the screen size of my emulator/simulator).

Left one - `stable v1.12.13+hotfix.9`, right one - `dev v1.18.0-6.0.pre`
(I used iOS and Android to show, but the case doesn't depend on the platform)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/79962284-87663180-8490-11ea-838d-267de942b700.gif)

**Comment by VladyslavBondarenko** [comment]
@Piinks 
On the recording it's visible that the issue is related not to the keyboard, but to the TextField.
Left device - stable channel, no overflow with TextField.
Right device - dev channel, overflow with TextField, but not with another widget.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17024977/79968589-fe9fc380-8498-11ea-8496-00f5c6568187.gif)

**Comment by Piinks** [comment]
Ah! Thank you for clarifying! I will check this out again today.

**Comment by Piinks** [comment]
Quick update, this does appear to be an issue with TextField. SliverFillRemaining checks the intrinsic height before laying out its children. During that check in SFR, the TextField reports 43 pixels for intrinsic height, but then reports 48 pixels as being allocated in the RenderFlex while laying out. Resulting in the 5 pixel overlap.

**Comment by Piinks** [comment]
May be related to this change: https://github.com/flutter/flutter/pull/42449
Potentially related issue: https://github.com/flutter/flutter/issues/46160

I did find another workaround where wrapping the Container in an Expanded widget will prevent the overflow error from occurring.

I'm going to see about fixing the intrinsic sizing information reported by TextField. :)
