### ISSUE TITLE
OS Error: The system cannot find the file specified.

### ISSUE THREAD

**Issue by AjnasAskar** [flutter/flutter#54721]
While I trying to take release build, its showing error regarding OS.

Target android_aot_bundle_release_android-arm failed: FileSystemException: Cannot copy file to 'C:\Users\user\multi_delivery\build\app\intermediates\flutter\release\armeabi-v7a\app.so', path = 'C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\armeabi-v7a\app.so' (OS Error: The system cannot find the file specified.
, errno = 2)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\user\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by jonahwilliams** [comment]
Please include the output of flutter doctor -v . It would also be helpful if you could provide the full verbose logs from build APK/appbundle as well

**Comment by AjnasAskar** [comment]
> 
> 
> Please include the output of flutter doctor -v . It would also be helpful if you could provide the full verbose logs from build APK/appbundle as well

PS C:\Users\user\multi_delivery> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\Users\user\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\New folder1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\New folder1
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • SM G570F • 4200f387dc54349f • android-arm • Android 8.0.0 (API 26)

• No issues found!

**Comment by AjnasAskar** [comment]
S C:\Users\user\multi_delivery> flutter build apk --verbose
[  +97 ms] executing: [C:\Users\user\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2021 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +2 ms] executing: [C:\Users\user\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +959 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.9-0-gf139b1100
[  +26 ms] executing: [C:\Users\user\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +348 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Users\user\flutter\] git ls-remote --get-url origin
[ +200 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +457 ms] executing: [C:\Users\user\flutter\] git rev-parse --abbrev-ref HEAD
[ +305 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +247 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +74 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +84 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +374 ms] Found plugin firebase_analytics at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[  +83 ms] Found plugin firebase_messaging at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.13\
[ +298 ms] Found plugin flutter_inappbrowser at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappbrowser-1.2.2\[ +203 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\
[ +155 ms] Found plugin google_maps_flutter at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.25+3\
[  +24 ms] Found plugin location at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[ +260 ms] Found plugin path_provider at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
[  +14 ms] Found plugin path_provider_macos at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[ +135 ms] Found plugin shared_preferences at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[  +20 ms] Found plugin shared_preferences_macos at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[ +145 ms] Found plugin shared_preferences_web at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[ +152 ms] Found plugin sqflite at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[ +172 ms] Found plugin url_launcher at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\
[  +89 ms] Found plugin url_launcher_macos at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[ +109 ms] Found plugin url_launcher_web at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[ +431 ms] Found plugin firebase_analytics at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[   +6 ms] Found plugin firebase_messaging at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.13\
[ +150 ms] Found plugin flutter_inappbrowser at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappbrowser-1.2.2\[  +10 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\
[ +157 ms] Found plugin google_maps_flutter at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.25+3\
[ +317 ms] Found plugin location at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[ +137 ms] Found plugin path_provider at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
[ +134 ms] Found plugin path_provider_macos at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[  +16 ms] Found plugin shared_preferences at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[ +128 ms] Found plugin shared_preferences_macos at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +7 ms] Found plugin shared_preferences_web at
C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[ +156 ms] Found plugin sqflite at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[ +141 ms] Found plugin url_launcher at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\
[ +110 ms] Found plugin url_launcher_macos at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[   +7 ms] Found plugin url_launcher_web at C:\Users\user\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[ +512 ms] Generating C:\Users\user\multi_delivery\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +189 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[   +3 ms] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
[ +165 ms]     To generate an app bundle, run:
[   +1 ms]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[   +1 ms]         Learn more on: https://developer.android.com/guide/app-bundle
[ +317 ms]     To split the APKs per ABI, run:
[ +321 ms]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[ +161 ms]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[ +269 ms] Running Gradle task 'assembleRelease'...
[ +128 ms] gradle.properties already sets `android.enableR8`
[ +172 ms] Using gradle from C:\Users\user\multi_delivery\android\gradlew.bat.
[ +203 ms] executing: D:\New folder1\jre\bin\java -version
[ +961 ms] Exit code 0 from: D:\New folder1\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +8 ms] executing: [C:\Users\user\multi_delivery\android\] C:\Users\user\multi_delivery\android\gradlew.bat -Pverbose=true
-Ptarget=lib\main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64
assembleRelease
[+35702 ms] > Task :app:compileFlutterBuildRelease
[   +2 ms] [  +68 ms] executing: [C:\Users\user\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+3820 ms] [+3883 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] [   +2 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[ +161 ms] [        ] executing: [C:\Users\user\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +720 ms] [ +880 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] [        ] v1.12.13+hotfix.9-0-gf139b1100
[ +122 ms] [  +21 ms] executing: [C:\Users\user\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[+1388 ms] [+1488 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +2 ms] [        ] executing: [C:\Users\user\flutter\] git ls-remote --get-url origin
[ +189 ms] [ +231 ms] Exit code 0 from: git ls-remote --get-url origin
[ +125 ms] [        ] https://github.com/flutter/flutter.git
[ +268 ms] [ +363 ms] executing: [C:\Users\user\flutter\] git rev-parse --abbrev-ref HEAD
[ +907 ms] [ +946 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[ +181 ms] [  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +182 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +168 ms] [  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +174 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] [ +272 ms] Initializing file store
[ +295 ms] [  +96 ms] Done initializing file store
[+16874 ms] [+17473 ms] Skipping target: kernel_snapshot
[ +286 ms] [ +197 ms] invalidated build due to missing files:
C:\Users\user\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot
[+1210 ms] [+1280 ms] invalidated build due to missing files:
C:\Users\user\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot
[  +91 ms] [  +58 ms] invalidated build due to missing files:
C:\Users\user\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x64\gen_snapshot
[+2706 ms] [+2743 ms] Skipping target: aot_android_asset_bundle
[ +191 ms] [ +150 ms] android_aot_release_android-arm: Starting due to {InvalidatedReason.outputMissing,
InvalidatedReason.inputMissing}
[ +189 ms] [  +26 ms] executing: C:\Users\user\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot
--causal_async_stacks --deterministic --snapshot_kind=app-aot-elf
--elf=C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\armeabi-v7a\app.so --strip
--no-sim-use-hardfp --no-use-integer-division
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\app.dill
[ +644 ms] [  +14 ms] android_aot_release_android-x64: Starting due to {InvalidatedReason.outputMissing,
InvalidatedReason.inputMissing}
[ +595 ms] [  +14 ms] executing: C:\Users\user\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x64\gen_snapshot
--causal_async_stacks --deterministic --snapshot_kind=app-aot-elf
--elf=C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\x86_64\app.so --strip
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\app.dill
[   +8 ms] [   +2 ms] android_aot_release_android-arm64: Starting due to {InvalidatedReason.outputMissing,
InvalidatedReason.inputMissing}
[ +196 ms] [  +12 ms] executing: C:\Users\user\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot
--causal_async_stacks --deterministic --snapshot_kind=app-aot-elf
--elf=C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\arm64-v8a\app.so --strip
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\app.dill
[+69980 ms] [+71600 ms] android_aot_release_android-x64: Complete
[ +185 ms] [ +196 ms] invalidated build due to missing files:
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\x86_64\app.so
[   +3 ms] [        ] android_aot_bundle_release_android-x64: Starting due to {InvalidatedReason.inputMissing}
[ +696 ms] [ +656 ms] android_aot_release_android-arm64: Complete
[  +99 ms] [  +72 ms] invalidated build due to missing files:
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\arm64-v8a\app.so
[  +60 ms] [        ] android_aot_bundle_release_android-arm64: Starting due to {InvalidatedReason.inputMissing}
[ +547 ms] [ +651 ms] android_aot_release_android-arm: Complete
[  +90 ms] [  +91 ms] invalidated build due to missing files:
C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\armeabi-v7a\app.so
[  +75 ms] [        ] android_aot_bundle_release_android-arm: Starting due to {InvalidatedReason.inputMissing}
[   +6 ms] [   +2 ms] Persisting file store
[ +165 ms] [  +51 ms] Done persisting file store
[ +572 ms] [  +31 ms] Target android_aot_bundle_release_android-x64 failed: FileSystemException: Cannot copy file to
'C:\Users\user\multi_delivery\build\app\intermediates\flutter\release\x86_64\app.so', path =
'C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\x86_64\app.so' (OS Error: The system cannot 
find the file specified.
[ +166 ms] [ +459 ms] "flutter assemble" took 96,733ms.
[   +3 ms]            , errno = 2)
[   +2 ms] [   +4 ms] Target android_aot_bundle_release_android-arm64 failed: FileSystemException: Cannot copy file to
'C:\Users\user\multi_delivery\build\app\intermediates\flutter\release\arm64-v8a\app.so', path =
'C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\arm64-v8a\app.so' (OS Error: The system     
cannot find the file specified.
[ +472 ms]            , errno = 2)
[ +177 ms] [        ] Target android_aot_bundle_release_android-arm failed: FileSystemException: Cannot copy file to
'C:\Users\user\multi_delivery\build\app\intermediates\flutter\release\armeabi-v7a\app.so', path =
'C:\Users\user\multi_delivery\.dart_tool\flutter_build\e15b0a88e004778e8515954c43326224\armeabi-v7a\app.so' (OS Error: The system   
cannot find the file specified.
[ +638 ms]            , errno = 2)
[ +144 ms] build failed.
[ +144 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[ +119 ms] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:183:7)
[  +19 ms] <asynchronous suspension>
[ +227 ms] #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
[ +111 ms] <asynchronous suspension>
[ +182 ms] #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
[ +148 ms] <asynchronous suspension>
[ +116 ms] #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[   +9 ms] #5      _rootRun (dart:async/zone.dart:1126:13)
[   +2 ms] #6      _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] #7      _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #8      runZoned (dart:async/zone.dart:1465:12)
[ +244 ms] #9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[ +200 ms] #10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
[  +26 ms] #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[ +116 ms] #12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
[   +7 ms] <asynchronous suspension>
[   +2 ms] #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[   +1 ms] #14     _rootRun (dart:async/zone.dart:1126:13)
[   +1 ms] #15     _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] #16     _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #17     runZoned (dart:async/zone.dart:1465:12)
[ +222 ms] #18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[ +106 ms] #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
[  +18 ms] #20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[   +1 ms] #21     new Future.sync (dart:async/future.dart:224:31)
[   +1 ms] #22     CommandRunner.run (package:args/command_runner.dart:112:14)
[ +125 ms] #23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
[   +3 ms] #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
[   +1 ms] #25     _rootRun (dart:async/zone.dart:1126:13)
[   +1 ms] #26     _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] #27     _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #28     runZoned (dart:async/zone.dart:1502:12)
[ +169 ms] #29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
[   +5 ms] <asynchronous suspension>
[   +4 ms] #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[   +3 ms] #31     _rootRun (dart:async/zone.dart:1126:13)
[ +264 ms] #32     _CustomZone.run (dart:async/zone.dart:1023:19)
[ +136 ms] #33     _runZoned (dart:async/zone.dart:1518:10)
[ +121 ms] #34     runZoned (dart:async/zone.dart:1465:12)
[   +2 ms] #35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[   +2 ms] #36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
[   +1 ms] #37     run (package:flutter_tools/runner.dart:50:10)
[   +1 ms] #38     main (package:flutter_tools/executable.dart:65:9)
[   +1 ms] #39     main (file:///C:/Users/user/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[   +1 ms] #40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
[   +1 ms] #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[ +121 ms] > Task :app:compileFlutterBuildRelease FAILED
[+1566 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[   +1 ms] Script 'C:\Users\user\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
[ +133 ms] * What went wrong:
[ +133 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[ +112 ms] > Process 'command 'C:\Users\user\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +2 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with  
--scan to get full insights.
[ +288 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 2m 25s
[   +2 ms] 1 actionable task: 1 executed
[+1444 ms] Running Gradle task 'assembleRelease'... (completed in 149.6s, longer than expected)
[  +72 ms] "flutter apk" took 156,694ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by Ayobami-00** [comment]
I am currently facing this same issue. @AjnasAskar, were you able to solve it?

**Comment by radioactivehuman** [comment]
Error when reading '/C:/src/flutter/packages/flutter_tools/.packages': The system cannot find the file specified while installing flutter
