### ISSUE TITLE
CreateProcessW failed 193

### ISSUE THREAD

**Issue by Bob-skku** [flutter/flutter#54723]
### I can't run Pub get

I already did
**Run as administrator**
Go to C:\Program Files\Android\Android Studio\jre\bin\java.exe
Right click and click Run as administrator

**Access permission**
Go to C:\Program Files\Android\Android Studio\jre\bin\java.exe
Right click and go to properties
Go to the security section
Click system and edit the access permission make sure you gave it read/write/modify access.

Ignoring Sending Crash report Handshake error, My company blocked it

C:\src\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in flutter_app...                     CreateProcessW failed 5

Sending crash report to Google.
Crash report sender itself crashed: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
#0      IOClient.send (package:http/src/io_client.dart:33:23)
<asynchronous suspension>
#1      CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart:119:56)
#2      _handleToolError (package:flutter_tools/runner.dart:124:38)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#4      _handleToolError (package:flutter_tools/runner.dart:82:29)
#5      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
#6      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#7      _rootRunBinary (dart:async/zone.dart:1146:38)
#8      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#9      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#11     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#12     Future._completeError (dart:async/future_impl.dart:532:5)
#13     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#16     _rootRunBinary (dart:async/zone.dart:1146:38)
#17     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#18     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#20     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#21     Future._completeError (dart:async/future_impl.dart:532:5)
#22     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#23     AppContext.run (package:flutter_tools/src/base/context.dart)
#24     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#25     _rootRunBinary (dart:async/zone.dart:1146:38)
#26     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#27     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#28     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#29     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#30     Future._completeError (dart:async/future_impl.dart:532:5)
#31     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart)
#33     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#34     _rootRunBinary (dart:async/zone.dart:1146:38)
#35     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#36     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#37     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#38     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#39     Future._completeError (dart:async/future_impl.dart:532:5)
#40     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#41     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#42     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#43     _rootRunBinary (dart:async/zone.dart:1146:38)
#44     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#45     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#46     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#47     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#48     Future._completeError (dart:async/future_impl.dart:532:5)
#49     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#50     CommandRunner.runCommand (package:args/command_runner.dart)
#51     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#52     _rootRunBinary (dart:async/zone.dart:1146:38)
#53     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#54     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#55     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#56     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#57     Future._completeError (dart:async/future_impl.dart:532:5)
#58     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#59     AppContext.run (package:flutter_tools/src/base/context.dart)
#60     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#61     _rootRunBinary (dart:async/zone.dart:1146:38)
#62     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#63     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#64     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#65     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#66     Future._completeError (dart:async/future_impl.dart:532:5)
#67     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#68     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart)
#69     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#70     _rootRunBinary (dart:async/zone.dart:1146:38)
#71     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#72     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#73     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#74     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#75     Future._completeError (dart:async/future_impl.dart:532:5)
#76     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#77     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#78     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#79     _rootRunBinary (dart:async/zone.dart:1146:38)
#80     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#81     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#82     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#83     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#84     Future._completeError (dart:async/future_impl.dart:532:5)
#85     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#86     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart)
#87     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#88     _rootRunBinary (dart:async/zone.dart:1146:38)
#89     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#90     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#91     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#92     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#93     Future._completeError (dart:async/future_impl.dart:532:5)
#94     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#95     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart)
#96     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#97     _rootRunBinary (dart:async/zone.dart:1146:38)
#98     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#99     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#100    Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#101    Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#102    Future._completeError (dart:async/future_impl.dart:532:5)
#103    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#104    PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart)
#105    _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#106    _rootRunBinary (dart:async/zone.dart:1146:38)
#107    _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#108    _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#109    Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#110    Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#111    Future._completeError (dart:async/future_impl.dart:532:5)
#112    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#113    _DefaultPub.get (package:flutter_tools/src/dart/pub.dart)
#114    _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#115    _rootRunBinary (dart:async/zone.dart:1146:38)
#116    _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#117    _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#118    Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#119    Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#120    Future._completeError (dart:async/future_impl.dart:532:5)
#121    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#122    _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart)
#123    _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#124    _rootRunBinary (dart:async/zone.dart:1146:38)
#125    _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#126    _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#127    Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#128    Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#129    Future._completeError (dart:async/future_impl.dart:532:5)
#130    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#131    _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#132    _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#133    _rootRunBinary (dart:async/zone.dart:1146:38)
#134    _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#135    _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#136    Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#137    Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#138    Future._completeError (dart:async/future_impl.dart:532:5)
#139    Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#140    _rootRun (dart:async/zone.dart:1126:13)
#141    _CustomZone.run (dart:async/zone.dart:1023:19)
#142    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#143    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#144    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#145    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#146    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#147    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#148    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Oops; flutter has exited unexpectedly.
CreateProcessW failed 5
Crash report written to C:\Users\2069749\AndroidStudioProjects\androidSRC\flutter_app\flutter_27.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

**Comment by Bob-skku** [comment]
and flutter_27.log

I also can't run flutter doctor --android-licenses with same error message

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color pub get

## exception

ProcessException: ProcessException: 액세스가 거부되었습니다.

  Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile

```
#0      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:29)
<asynchronous suspension>
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:259:33)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:98:17)
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:11)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.832], locale ko-KR)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/2069749/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/2069749/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @Bob-skku 
Please check out this [solution](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)  for Android license status unknown
Could you please provide `flutter --no-color pub get --verbose`?
Thank you

**Comment by Bob-skku** [comment]
I solved that problem with re-install and set Path of JAVA. Thanks
