### ISSUE TITLE
cannot  cas't androidx.fragment.app.Fragment to io.flutter.embedding.android.Flutterfragment

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#54728]
After I introduced the flutter module in the native project,
When writing the following code

flutterFragment = (FlutterFragment) fragmentManager
                .findFragmentByTag(TAG_FLUTTER_FRAGMENT);

Prompt the following error
cannot  cas't androidx.fragment.app.Fragment to io.flutter.embedding.android.Flutterfragment

flutter -doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @haibowen 
Please follow this [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration)
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by haibowen** [comment]
> Hi @haibowen
> Please follow this [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration)
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Flutter doctor -v
:\AndroidStudioProjects\my_flutter>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at E:\flutter\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\haibo\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\haibo\AppData\Local\Android\Sdk
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • STF AL10 • CSX0217A21001282 • android-arm64 • Android 9 (API 28)

• No issues found!

example


 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Inflate a layout that has a container for your FlutterFragment. For
        // this example, assume that a FrameLayout exists with an ID of
        // R.id.fragment_container.
        setContentView(R.layout.my_activity_layout);

        // Get a reference to the Activity's FragmentManager to add a new
        // FlutterFragment, or find an existing one.
        FragmentManager fragmentManager = getSupportFragmentManager();

        // Attempt to find an existing FlutterFragment, in case this is not the
        // first time that onCreate() was run.
        flutterFragment = (FlutterFragment) fragmentManager
            .findFragmentByTag(TAG_FLUTTER_FRAGMENT);

        // Create and attach a FlutterFragment if one does not exist.
        if (flutterFragment == null) {
            flutterFragment = FlutterFragment.createDefault();

            fragmentManager
                .beginTransaction()
                .add(
                    R.id.fragment_container,
                    flutterFragment,
                    TAG_FLUTTER_FRAGMENT
                )
                .commit();
        }
    }

**Comment by TahaTesser** [comment]
Hi @haibowen 
Please follow [ Add Flutter Fragment](https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Fragment)  guide 
Make sure you've migrated to AndroidX
Thanks

**Comment by designDo** [comment]
I  have the same error.  I found the jar does not support androidX which is flutter-embedding-debug-1.0.0.jar . The project have also migrated to AndroidX. why ?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues
Thank you
