### ISSUE TITLE
Custom linker flags not being set in Xcode project

### ISSUE THREAD

**Issue by minenkod** [flutter/flutter#54734]
In my project I have -ObjC added to my other linker flags. When running "flutter build ios" the Generated.xconfig file does not have this added.

![image](https://user-images.githubusercontent.com/42996779/79211541-48a3fc00-7e3e-11ea-8d76-92243feed47a.png)

The only way I could get this to work is if I manually enter the -ObjC flag into the file and then run from xcode. 

![image](https://user-images.githubusercontent.com/42996779/79211699-7b4df480-7e3e-11ea-8239-c59109d96bc4.png)

This is not acceptable as this file gets overwritten on every build and my flag is removed. 

How could I tackle this?

**Comment by jmagman** [comment]
> In my project I have -ObjC added to my other linker flags

Is `-ObjC` in your project or Runner target?  I would have expected it to get `$(inherited)` in either case.

**Comment by minenkod** [comment]
Ive tried placing the flag in both runner and target but the result is the
same. Its just that none of the project settings get applied into the
xconfig file.

**Comment by jmagman** [comment]
> Ive tried placing the flag in both runner and target but the result is the same. Its just that none of the project settings get applied into the xconfig file.

Set your linker flags in your Runner target Xcode build settings, not in the Flutter-generated xcconfig file.  I just tested it and it worked.

![Screen Shot 2020-04-15 at 10 08 57 AM](https://user-images.githubusercontent.com/682784/79366571-45be0f80-7f01-11ea-8546-2953bdc6b1d7.png)

And the linker now is being passed the `-ObjC` flag

```
Ld /Users/m/Projects/flutter/examples/hello_world/build/ios/Debug-iphoneos/Runner.app/Runner normal arm64 (in target 'Runner' from project 'Runner')
    cd /Users/m/Projects/flutter/examples/hello_world/ios
    /Users/m/Applications/Xcode-11-4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios8.0 -isysroot ... -framework Flutter -framework Flutter -ObjC -Xlinker -dependency_info -Xlinker /Users/m/Projects/flutter/examples/hello_world/build/ios/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat ...
```

**Comment by minenkod** [comment]
> > Ive tried placing the flag in both runner and target but the result is the same. Its just that none of the project settings get applied into the xconfig file.
> 
> Set your linker flags in your Runner target Xcode build settings, not in the Flutter-generated xcconfig file. I just tested it and it worked.
> 
> ![Screen Shot 2020-04-15 at 10 08 57 AM](https://user-images.githubusercontent.com/682784/79366571-45be0f80-7f01-11ea-8546-2953bdc6b1d7.png)
> 
> And the linker now is being passed the `-ObjC` flag
> 
> ```
> Ld /Users/m/Projects/flutter/examples/hello_world/build/ios/Debug-iphoneos/Runner.app/Runner normal arm64 (in target 'Runner' from project 'Runner')
>     cd /Users/m/Projects/flutter/examples/hello_world/ios
>     /Users/m/Applications/Xcode-11-4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios8.0 -isysroot ... -framework Flutter -framework Flutter -ObjC -Xlinker -dependency_info -Xlinker /Users/m/Projects/flutter/examples/hello_world/build/ios/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat ...
> ```

If I then add an ObjC include library into the project, I would get a ton of unsuported archtecture errors like this: 
![image](https://user-images.githubusercontent.com/42996779/79549923-8c417480-808f-11ea-98f8-b0e168e0802d.png)

Only after adding an ObjC flag inside the Generated.xconfig do they go away

**Comment by minenkod** [comment]
Additionally when creating a project with "flutter create projectname" a Podfile is no where to be found

**Comment by jmagman** [comment]
> Additionally when creating a project with "flutter create projectname" a Podfile is no where to be found

The Podfile is generated when you add a plugin with iOS platform code.

> If I then add an ObjC include library into the project, I would get a ton of unsuported archtecture errors like this:

Can we get a project that reproduces?  It sounds like you have a target that is inheriting its build config from that xcconfig file and you need to add your linker flag into that target, but I can't really tell how you are adding "an ObjC include library into the project".  What library, how are you adding it?  (linking on an iOS SDK library, adding your own library target, etc)

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
