### ISSUE TITLE
Error while signing an app

### ISSUE THREAD

**Issue by AjnasAskar** [flutter/flutter#54739]
flutter build app --vebrose

[   +2 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:signingConfigWriterRelease'.
[   +1 ms] > Trailing char < > at index 36: D:\Capcee\multi_delivery_app\key.jks

**Comment by TahaTesser** [comment]
Hi @AjnasAskar 
This is  not a Flutter issue
Your key is missing character [Reference the keystore from the app
](https://flutter.dev/docs/deployment/android#reference-the-keystore-from-the-app)
Thank you

**Comment by VladyslavBondarenko** [comment]
@AjnasAskar 
I hope you've solved the issue, closing

**Comment by hellobody** [comment]
> flutter build app --vebrose
> 
> [ +2 ms] FAILURE: Build failed with an exception.
> [ +3 ms] * What went wrong:
> [ +1 ms] Execution failed for task ':app:signingConfigWriterRelease'.
> [ +1 ms] > Trailing char < > at index 36: D:\Capcee\multi_delivery_app\key.jks

Just remove space character from the end of this line: "D:\Capcee\multi_delivery_app\key.jks " in your key.properties file.
