### ISSUE TITLE
SharePlugin.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#54748]
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+6\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by VladyslavBondarenko** [comment]
Hi @kw2019ltd 
This isn't an error and just "deliberate and temporary" warning
Closing as duplicate of https://github.com/flutter/flutter/issues/47153
