### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by ysnklcky** [flutter/flutter#54740]
I developing ann app and i got below error but i dont know why.. I do not have any controller. Is it about CarouselSlider ? because, i look at error point, that shows "child: CarouselSlider" What can i do ? Please help me.

> ════════ Exception caught by widgets library ═══════════════════════════════════ ScrollController attached to multiple scroll views. 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12: '_positions.length == 1' The relevant error-causing widget was CarouselSlider

My Code;

```
List<String> images = new List();

  @override
  void initState() {
    Future.delayed(Duration(milliseconds: 0)).then((f) {
      setState(() {
        rightPaddingValue = 10;
      });
    });
    super.initState();
    images.add(mainImage);
    images.add(contentImage1);
    images.add(contentImage2);
    images.add(contentImage3);
    images.add(contentImage4);
  }



@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            backgroundColor: Colors.white70,
            expandedHeight: 270,
            flexibleSpace: FlexibleSpaceBar(
              background: Hero(
                tag: tag,
                child: CarouselSlider(
                  height: 400.0,                  
                  autoPlay: true,
                  enlargeCenterPage: true,
                  items: images.map((i) {
                    return Builder(
                      builder: (BuildContext context) {
                        return Container(
                          width: MediaQuery.of(context).size.width,
                          child: Image(
                            image: CachedNetworkImageProvider(i),
                            fit: BoxFit.cover,
                          ),
                        );
                      },
                    );
                  }).toList(),
                ),
              ),
            ),
...
```

**Comment by TahaTesser** [comment]
Hi @ysnklcky 
For issue related to the 3rd party plugin [carousel_slider](https://pub.dev/packages/carousel_slider) you may want to open an issue in the dedicated [github](https://github.com/serenader2014/flutter_carousel_slider/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
