### ISSUE TITLE
web_benchmarks_canvaskit draw_rect.canvaskit.drawFrameDuration.average, other web_benchmarks_canvaskit regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54759]
See also draw_rect.canvaskit.sceneBuildDuration.average, draw_rect.canvaskit.totalUiFrame.average, draw_rect.canvaskit.windowRenderDuration.average.

<img width="420" alt="Screen Shot 2020-04-14 at 9 23 21 AM" src="https://user-images.githubusercontent.com/1435716/79249089-9b2aeb80-7e31-11ea-8bcf-600ef7c98a07.png">

Hard to tell a culprit; the starting regression PRs look unrelated, and this metric is noisy. 

cc @yjbanov

**Comment by yjbanov** [comment]
Currently we don't have a way to deal with benchmarks that are so noisy. I rebaselined them. I'm working on a way to reduce noise in our benchmarks.
