### ISSUE TITLE
regression wrt flutter_tools use of the vm service protocol

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#54755]
We're seeing a few, serious, regressions wrt flutter tools, flutter run, and the vm service protocol. I bisected the issues to:

> commit 4851888864348524b4065e18cd6e2597f906fd8d
> [flutter_tools] Migrate to package:vm_service 4: trigonometric boogaloo (#54132)

The issues are:
- failures in our (DevTools) CI: https://travis-ci.org/github/flutter/devtools/jobs/672707154; 'Service has disappeared (112) from s0.flutterVersion()'
- after a flutter run, flutter tools can lose the connection to the running app, and exit back to the cli, even though the app continues to run
- when quitting on the command line (`q`), the app in the ios simulator continues to run
- DevTools tries to call the `flutterVersion` service extension registered by flutter_tools. However, we get an error back from the VM, as after registering the service extension, flutter tools then looses its connection to the VM (the service extension provider is no longer available). This causes other issues in the DevTools UI, including the hot reload and restart actions not being available.

I can repro this all locally and can test any fix. These issues are serious enough that we should fix as soon as possible or roll back the change.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
@devoncarew do you have repro instructions for "when quitting on the command line (q), the app in the ios simulator continues to run". I'm not able to repro this locally.

**Comment by devoncarew** [comment]
It looks like I'm not able to reproduce that in isolate (but I do recall seeing it a few times).

A repro for the general issue:
- start the iOS simulator
- from the command line, flutter run an app
- start devtools
- connect to the app from devtools using the url printed by flutter run
- flutter tools will exit to the command line; the app will continue running on the device, and devtools will be connected to the running app (w/ issues related to the flutter tools provided service extension - flutterVersion, reload, restart, ...)

**Comment by jonahwilliams** [comment]
It might be we have a bug in the handling of the additional vm service commands, that was either introduced by the change or was previously swallowed by the jsonrpc2 implementation. If its entirely unhandled, it would take down the VM service client and cause a disconnect before we could quit the app.

**Comment by jonahwilliams** [comment]
I'm going to keep looking into this today to see if there is an obvious fix. If not, I'll prepare a rollback

**Comment by devoncarew** [comment]
Thanks! Happy to try patches out locally.
