### ISSUE TITLE
google_sign_in_web on first interaction will trigger a popup alert in Firefox, but not in Chrome

### ISSUE THREAD

**Issue by eddie-at-work** [flutter/flutter#54768]
In Firefox or Safari, click the "sign in" button. This calls googleSignIn.signIn(), but triggers a popup warning banner. Have to click popup blocked warning to enable the showing of Google Sign In oauth screen.

After signing in, it doesn't detect the user change. Have to click "sign in" again, to bring up the oauth screen. It will sign in automatically and then it detects the user.

Note this only happens if clicking "sign in" is the first user interaction. By clicking "sign out" first (expected to do nothing since user isn't signed in yet), then clicking "sign in", it would not trigger the popup alert.

Works as expected in Chrome, click "sign in", popup shows up, enter credentials, and the user change detected in app.

Using: 
google_sign_in: ^4.1.0

Tested on:
Windows, Firefox 75.0
Windows, Chrome 81.0.4044.92
Mac, Firefox 75.0
Mac, Safari 13.0.4

index.html
```<!DOCTYPE html>
<html>
<head>
  <meta name="google-signin-client_id" content="XXXXXXXXXXXXXX.apps.googleusercontent.com">
  
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="google_web_sign_in_spike">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>

  <title>google_web_sign_in_spike</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

main.dart
```
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sign In Demo',
      home: MyHomePage(title: 'Sign In Demo'),
    );
  }
}

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  

  @override
  Widget build(BuildContext context) {
    return Container(
      
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GoogleSignIn _googleSignIn;
  GoogleSignInAccount _googleSignInAccount;
  
  @override
  void initState() {
    _googleSignIn = GoogleSignIn(
      scopes: ['https://www.googleapis.com/auth/contacts'],
      clientId:
          "XXXXXXXXXXXXXX.apps.googleusercontent.com");

    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {  
      setState(() {
        _googleSignInAccount = account;
      });
    });

    super.initState();
  }

  void _signIn() async {
    try {
      print("SignIn");
      GoogleSignInAccount account = await _googleSignIn.signIn();
      GoogleSignInAuthentication authentication = await account.authentication;

      print("Id: ${account?.id}");
      print("Display name: ${account?.displayName}");
      print("Email: ${account?.email}");
      print("AccessToken: ${authentication?.accessToken}");
    } catch (error) {
      print(error);
    }
  }

  void _signOut() async {
    print("SignOut");
    await _googleSignIn.signOut();
  }

  void _disconnect() async {
    print("Disconnect");
    await _googleSignIn.disconnect();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("Is signed in: ${_googleSignInAccount != null}"),
            Text("Signed in as: ${_googleSignInAccount?.email ?? ''}"),
            RaisedButton(
              onPressed: _signIn,
              child: Text("Sign In"),
            ),
            RaisedButton(
              onPressed: _signOut,
              child: Text("Sign Out"),
            ),
            RaisedButton(
              onPressed: _disconnect,
              child: Text("Disconnect"),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by ditman** [comment]
Thanks for the report, @eddie-at-work!

I have a PR in flight that might solve this issue: https://github.com/flutter/plugins/pull/2649, can you please check if it fixes this issue? If not, I'll get back to this once I merge it.

_(You should be able to `override_dependencies` to my git branch + path for google_sign_in_web, or clone locally my fork of the plugins repo and use it from a `path`, like in this [example](https://github.com/ditman/plugins/blob/connectivity-web/packages/connectivity/connectivity/example/pubspec.yaml#L9-L10))_

**Comment by eddie-at-work** [comment]
Hi @ditman , thanks for the quick response!

Sorry, but I'm still seeing this issue even with #2649

**Comment by ditman** [comment]
Thanks for taking a look, I'll revisit this one after 2649 lands!

**Comment by ditman** [comment]
@eddie-at-work can you give this app a shot and see if the popup is still blocked for you?

https://dit-sign-in-debug.web.app

It's just flutter's google_sign_in [example](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/lib/main.dart) app deployed to a hosting of my own. It doesn't do anything with your data, other than signing you in and looking at your contacts to tell you you know somebody.

(If you prefer to do this yourself, just try to deploy the example app I linked above to the hosting of your liking, after `flutter build web` to ensure it's a prod build)

**Comment by eddie-at-work** [comment]
🤔 Interesting

Just confirming that the popup alert on Firefox doesn't show up when I hit 
https://dit-sign-in-debug.web.app
and shows the oauth screen immediately as expected.

It doesn't look like I'm doing anything radically different/unexpected in my sample? For what it's worth, I'm also hosting it on a https server for testing

**Comment by ditman** [comment]
After a quick look at your code and the sample, the only two glaring differences are:

1. Not calling signInSilently on your init
2. Awaiting, and then using, the result of the call to signIn (instead of letting the auth change listener do it for you.

My gut is that 2. is tripping Firefox somehow, with an ontap handler that is too complex (I don't know if this is still a thing).

**Comment by eddie-at-work** [comment]
Just following up, adding the signInSilently() in init seemed to do the trick, maybe it counts as an initial interaction? (In the original test, noticed that interacting with other buttons first ie. clicking "sign out", before clicking "sign in" will not trigger the alert in Firefox)

Successful test uploaded here
https://dev.gskinner.com/flutter_google_signin2

In our production app, we're calling signInSilently() but it happens in a different place than the view with the sign in button. This helps sheds some light on the fix.

Thanks for looking into this!

**Comment by ditman** [comment]
Very odd, the code is very similar between [signIn and signInSilently](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L120-L133), I'm not sure how signInSilently helps (other than maybe trying to initialize the currentUser from the JS side?)

**Comment by ditman** [comment]
@eddie-at-work I'm going to close this one, I assume you got this to work?

> adding the signInSilently() in init seemed to do the trick

Feel free to reopen if this is still giving you trouble!
