### ISSUE TITLE
Flutter framework linker flag should only be set for iOS SDKs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54769]
Non-Flutter targets can use the FLUTTER_ build settings like `FLUTTER_BUILD_NAME` and `FLUTTER_BUILD_NUMBER` to keep version numbers in sync between executables.  The easiest way to do that is for targets to inherit from the Debug.xcconfig and Release.xcconfig base configurations.  However, https://github.com/flutter/flutter/pull/51453 introduced `OTHER_LDFLAGS=$(inherited) -framework Flutter`, so any target that does so would try to link on Flutter, even if the target does not use Flutter (and thus doesn't have Flutter in its search paths), or even is watchOS or tvOS.

One workaround is to conditionalize the build setting to the iOS SDK.  That doesn't help with non-Flutter iOS targets, but it would mean watchOS and tvOS could use the xcconfig.

Context: https://github.com/flutter/flutter/pull/54691#issuecomment-613145985

1. Change to `OTHER_LDFLAGS[sdk=iphone*]=$(inherited) -framework Flutter`.  
2. Remove `OTHER_LDFLAGS` from flutter_export_environment.sh since OTHER_LDFLAGS[sdk=iphone*]` is not a valid environment variable, and host apps already link on Flutter and don't need this linker flag.

**Comment by jmagman** [comment]
\cc @tauu

**Comment by jmagman** [comment]
I was thinking a `-weak_framework` wouldn't be so bad, that should work for non-Flutter targets, and I believe it would still correctly fail at compilation where using the symbols (instead of runtime) for the Flutter target if the Flutter framework is missing.

**Comment by jhsware** [comment]
A solution to this could be to generate a second file called `GeneralBuildVariables.xcconfig` that could be used by extensions and would only have the subset of required variables. (From #71262)
