### ISSUE TITLE
Leak within Vertices

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#54762]
Vertices, when used for dynamic batching such as particles, etc, that regenerate every frame eventually leads to a crash.

Reproduction:
```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'dart:typed_data';
import 'dart:ui' as ui;

void main() { runApp(App()); }

class App extends StatelessWidget
{
  @override Widget build(BuildContext context)
  {
    return MaterialApp(
      home: View(),
      showPerformanceOverlay: true,
      title: 'vertices'
    );
  }
}

class View extends StatefulWidget { @override ViewState createState() { return ViewState(); } }

class ViewState extends State<View> with TickerProviderStateMixin
{
  final ViewPainter _painter = ViewPainter();
  Ticker _ticker;

  @override void initState()
  {
    super.initState();
    _ticker = createTicker(_painter.update);
    _ticker.start();
  }

  @override void dispose()
  {
    _ticker.stop();
    _ticker.dispose();
    super.dispose();
  }

  @override Widget build(BuildContext context)
  {
    return CustomPaint(
      isComplex: false,
      painter: _painter,
      willChange: true
    );
  }
}

class ViewPainter extends ChangeNotifier implements CustomPainter
{
  static const int uint16max = 65535;
  static const double verticesMB = 1.44177;

  final Int32List colors = Int32List(uint16max);
  final Float32List coords = Float32List(uint16max * 2);
  final Uint16List indices = Uint16List(uint16max);
  final Float32List positions = Float32List(uint16max * 2);

  double memory = 0.0;
  List<ui.Vertices> vertices = [];

  ViewPainter()
  {
    colors[0] = Colors.red.value;
    colors[1] = Colors.green.value;
    colors[2] = Colors.blue.value;
    colors[3] = Colors.yellow.value;
    indices[1] = indices[3] = 1;
    indices[2] = indices[5] = 3;
    indices[4] = 2;
    positions[2] = positions[4] = positions[5] = positions[7] = 250.0;
  }

  void update(Duration timeStamp)
  {
    vertices.clear();
    for(int v = 0; v < 3; v++)
    {
      vertices.add(ui.Vertices.raw(ui.VertexMode.triangles, positions, textureCoordinates: coords, colors: colors, indices: indices));
      memory += verticesMB;
    }
    debugPrint('total vert memory allocated: ' + memory.toStringAsFixed(1));
    notifyListeners();
  }

  void paint(ui.Canvas canvas, ui.Size size)
  {
    canvas.drawColor(Colors.white, BlendMode.srcOver);
    for(int v = 0; v < vertices.length; v++)
      canvas.drawVertices(vertices[v], BlendMode.srcOver, Paint());
  }

  @override bool hitTest(Offset position) { return true; }
  @override bool shouldRebuildSemantics(CustomPainter previous) { return false; }
  @override bool shouldRepaint(CustomPainter previous) { return true; }
  @override get semanticsBuilder { return null; }
}
```

I have not had a chance to verify this through a local engine, but is it possible this line:

[sk_sp\<SkVertices\> vertices_;](https://github.com/flutter/engine/blob/e8d71b4d2ff02a7d83f2231b4cd2d0b33ed1f8eb/lib/ui/painting/vertices.h#L40)

should be:

flutter::SkiaGPUObject\<SkVertices\> vertices_;

so that it gets added to the unref queue?

Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.18.1-pre.11, on Microsoft Windows [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.44.0)
[√] Connected device (1 available)

• No issues found!

C:\Users\User>flutter doctor -v
[√] Flutter (Channel master, v1.18.1-pre.11, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.18.1-pre.11 at C:\flutter
    • Framework revision 2ce36f6199 (7 days ago), 2020-04-07 12:26:02 -0700
    • Engine revision 47f17a9ec3
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 275a76f2fc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • SM J727P • 20c0f2a5 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by cmkweber** [comment]
What is interesting is this receives OOM on android test device, but does not OOM on iphone test device, even after a long while. It does hiccup during collections though on iphone. I'm trying now to add dispose to Vertices in a local engine to see if providing an eager disposal will alleviate these larger collections and also prevent OOM on android. Example updated in original post to reach OOM faster. A full Vertices object is around 1.4mb so it makes sense to have a dispose method.

**Comment by cmkweber** [comment]
Adding a dispose to eagerly clear the dart wrapper failed to prevent OOM crashes on my android test device. Switching Vertices to use the unref queue seems more involved and non-trivial, and better suited for the engine authors. I think this is worth solving though and determining why vertices are not fully disposed of on android devices but are properly disposed on iOS. The reproducible in the original post should crash an android device after a minute or so.

**Comment by cmkweber** [comment]
@dnfield  - this may be related to [https://github.com/flutter/flutter/issues/58438](https://github.com/flutter/flutter/issues/58438)

**Comment by dnfield** [comment]
Probably different from that issue - that issue is about trying to get the GC to be more aggressive when collecting picture objects.  I can take a quick look at this.  Strange that it would be Android only though.

**Comment by dnfield** [comment]
I'm also not clear on why this would need to be using the unref queue - that's more about making sure the right thread is disposing things rather than making sure that the object is released.

**Comment by cmkweber** [comment]
Ah makes sense, I wasn't (and still not) super familiar with how the unref queue worked, I had just noticed that SkImages were added to the queue but not SkVertices. But your right, if they never move between threads then its probably unrelated to the queue. It was very odd that only Android was affected, but I wasn't able to determine anything that would cause that deviation.

**Comment by dnfield** [comment]
I think this might be because we're not overriding `GetApproximateSize` in Vetices, so the GC thinks it's tiny when it's not.

We have a slight problem here in that we have to report the size before we actually know it, but Dart is adding some new API to help make that better so we can fix it.

**Comment by dnfield** [comment]
On an iPhone, I'm seeing very large memory spikes, but it's under the threshhold of OOM killing the app - although on an old enough iPhone it would OOM.

**Comment by cmkweber** [comment]
Interesting, so it's eventually being collected and is not a leak, and the discrepancy is that the collection can occur before the iPhone OOMs but that collection doesn't occur before my Android OOMs. What I observed though is I really tried to get the iPhone to crash, I goosed the allocation count higher, much higher just to see if I could but it didn't OOM in my tests. Just struggled with collections.

**Comment by dnfield** [comment]
I have something that's fixing this locally, going to work on getting a test for it.

**Comment by dnfield** [comment]
I'm seeing memory hit 1.5gb occasionally on an iPhone 11. It would have to get up to around 2gb before it got killed.

**Comment by cmkweber** [comment]
Excellent, thanks for looking into this!

**Comment by dnfield** [comment]
Going forward, the right way to do this will be to call `vertices.dispose`.
