### ISSUE TITLE
problem while running main.dart file in debug mode

### ISSUE THREAD

**Issue by tanvibattu** [flutter/flutter#54760]
**flutter run**

output is as follows

Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2.2s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/FlutterActivity( 5756): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 5756): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 5756): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 5756): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 5756): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e9a9065
D/FlutterActivityAndFragmentDelegate( 5756): Executing Dart entrypoint: main, and sending initial route: /
Syncing files to device AOSP on IA Emulator...                          
 8,953ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:41645/psGlzMjEM9U=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:41645/psGlzMjEM9U=/
You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "t".
For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U" (for inverse hit test order).
To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
To simulate different operating systems, (defaultTargetPlatform), press "o".
To toggle the elevation checker, press "z".
To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
To save a screenshot to flutter.png, press "s".
To repeat this help message, press "h". To detach, press "d"; to quit, press "q".

Error -32601 received from application: Method not found
Application finished.

**output of flutter doctor  -v  is as follows**

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.9 at /home/tanvi/Documents/development/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tanvi/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/tanvi/Documents/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/tanvi/Documents/development/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @tanvibattu 
Please explain what the issue is
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
