### ISSUE TITLE
Some `felt` users experience ulimit issues on Mac

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#54770]
We are getting reports that some macOS configurations do not allow calling `ulimit -n 50000` and/or `ulimit -u 4096`. We should revise our strategy, perhaps only set them when possible and only when necessary (e.g. the limit may already be sufficient).

This might be a useful resource: https://superuser.com/questions/309106/strange-behaviour-with-ulimit-on-mac-os-x-10-6/309107#309107

/cc @ditman who dug up the superuser link
/cc @vsmenon who was affected by the issue
/cc @nturgut who owns the `ulimit` code

**Comment by ditman** [comment]
On my mac I can only `ulimit -n 1024`. It won't let me do anything past that.
