### ISSUE TITLE
TextFormField initialValue inline If does not warn about type mismatches

### ISSUE THREAD

**Issue by dupiesdupreez** [flutter/flutter#54778]
This is a pretty easy bug to reproduce.

The TextFormField does not warn about type mismatches as the initial value when using an If statement. 

The following statement correctly throws an error : "The argument type 'int' can't be assigned to the parameter type 'String'"
![image](https://user-images.githubusercontent.com/6910085/79270215-fe526780-7e9d-11ea-8d30-27067f04b052.png)

But, the following two statements does not show anything wrong.
![image](https://user-images.githubusercontent.com/6910085/79270347-4b363e00-7e9e-11ea-95c7-469126711625.png)

or the else inverse
![image](https://user-images.githubusercontent.com/6910085/79270363-525d4c00-7e9e-11ea-8d74-55ef0fd62426.png)

So as long as one of the parameters are a string, its fine with it. Needless to say, it throws an exception on run time.

Man this made me run around for an hour.

**Comment by TahaTesser** [comment]
### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final int x = 5;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextFormField(
            initialValue: x > 0 ? '0' : 5,
          ),
        ),
      ),
    );
  }
}

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (3 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by jason-simmons** [comment]
This is due to the design of the Dart language.  See https://github.com/dart-lang/sdk/issues/25368

The `implicit-casts` check in the Dart analyzer will warn about this.

**Comment by dupiesdupreez** [comment]
@jason-simmons  Problem is, it doesn't warn me about that

**Comment by jason-simmons** [comment]
Make sure that your project has an `analysis_options.yaml` file that enables the check.  Example:
```
analyzer:
  strong-mode:
    implicit-casts: false
```

Then run `flutter analyze`.  You should see a warning like this:
```
  error • The argument type 'Object' can't be assigned to the parameter type 'String' • lib/main.dart:107:27 •
         argument_type_not_assignable
```

**Comment by antoniosap** [comment]
not only, it don't refresh on popping

```
TextFormField(
controller: TextEditingController()..text = value,  // <-- refresh
initialValue: value, // <--  don't refresh
...
)
```

**Comment by pedromassango** [comment]
This is not a problem with the `TextFormField` as said above. I that this can be moved to Dart repository and be closed here.

**Comment by TahaTesser** [comment]
Hi @antoniosap 
This looks like different issue https://github.com/flutter/flutter/issues/54778#issuecomment-616095519 
please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Related to this https://github.com/flutter/flutter/issues/54778#issuecomment-614933939, please https://github.com/dart-lang/sdk/issues/25368
Closing f. If you disagree, please write in the comments and I will reopen it.
Thank you
