### ISSUE TITLE
`flutter run --trace-startup` hangs when unable to connect to observatory

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#5477]
## Steps to Reproduce
- Cause the observatory to fail to start. As of today `flutter run --trace-startup --profile` does the trick on both Android and iOS.
- Observe the stack trace about inability to acquire a debug connection.
- The process hangs.
## Logs and Crash Reports

[Log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci8wODkyZjZhNTAzMDdmYmVlMThiYTY3ZDkzZWQ4ZjgxM2I2ZWI0OTk3DAsSBFRhc2sYgICAgICAkAgM)

/cc @devoncarew @danrubel

**Comment by devoncarew** [comment]
@yjbanov, is this a regression? And, how much does this impact the testing bots?

**Comment by yjbanov** [comment]
> is this a regression?

I remember this to be a quick failure in the past, but I may be wrong.

> how much does this impact the testing bots?

It causes the test bots to wait for timeout rather than fail fast and move on to the next task. This is why our [build](https://flutter-dashboard.appspot.com/build.html) has been behind GitHub for the past several days. I reduced the timeout for the startup tasks to 2 minutes, which should help.

**Comment by yjbanov** [comment]
Haven't seen this in a while. Closing.
