### ISSUE TITLE
GoogleMaps Camera moves to incorrect new LagLng bounds

### ISSUE THREAD

**Issue by baku-apps** [flutter/flutter#54773]
## Steps to Reproduce
Using `google_maps_flutter` version `0.5.25+3`

GoogleMaps camera moves sometimes to wrong new LatLng bounds.

```
var newBounds = LatLngBounds(LatLng(14.5495323, 121.0247812), LatLng(14.5558649, 121.01741709999999))
var cameraUpdate = CameraUpdate.newLatLngBounds(newBounds, 0);
await controller.moveCamera(cameraUpdate);
```

return value of `CameraUpdate` returns correct bounds.

**Expected results:**
Camera moves to correct bounds:
`LatLngBounds(LatLng(14.5495323, 121.0247812), LatLng(14.5558649, 121.01741709999999))`

**Actual results:** 
Camera moves to bounds:
`LatLngBounds(LatLng(-46.0662660913044, -93.49594663828613), LatLng(62.86153794252336, -24.4618608802557))`

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bart_\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\bart_\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.1)
[√] VS Code (version 1.44.1)
    • VS Code at C:\Users\bart_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```
```

</details>

**Comment by imeDevelopers** [comment]
I have method that adjust the camera by check the lati and longi before make update camera to set the correct view to the user , i worked a lot for it , its not free sorry.

**Comment by TahaTesser** [comment]
Hi @baku-apps 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by baku-apps** [comment]
@TahaTesser, I will provide the requested data soon.

**Comment by TahaTesser** [comment]
Hi @baku-apps 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
