### ISSUE TITLE
Get iOS observatory URL and pre-VM connection logs from attached debugger

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54781]
The engine logs the observatory URL, but for a real iOS device [that log is no longer accessible from the attached host](https://github.com/flutter/flutter/issues/41133), so there's a series of mDNS/other fallbacks in place to try to detect and then guess this port.

`ios-deploy` uses lldb to launch the app on an iOS device, and could be configured to remain attached to read logs from the process, including the observatory logs, launch exceptions, or anything printed before the VM is connected.

**Comment by jmagman** [comment]
This solution could be a solution to:
https://github.com/flutter/flutter/issues/44717
https://github.com/flutter/flutter/issues/44718
https://github.com/flutter/flutter/issues/46705
https://github.com/flutter/flutter/issues/47224
https://github.com/flutter/flutter/issues/52729

It also could be a way to get the observatory port for wirelessly paired devices: https://github.com/flutter/flutter/issues/15072.

**Comment by jmagman** [comment]
From https://github.com/flutter/flutter/issues/44718#issuecomment-600371621:

I was able to read the observatory port log line with `ios-deploy` by attaching to lldb with `--debug` instead of `--justlaunch`
```
ios-deploy --id <device-id> --bundle build/ios/iphoneos/Runner.app --debug  
...
(lldb)     connect
(lldb)     run
success
2020-03-17 17:32:39.410811-0700 Runner[633:132633] flutter: Observatory listening on http://127.0.0.1:55084/kiP-Z29onwQ=/
```
Or install and launch just the debugserver with `--nolldb` and store that port somewhere:
```
ios-deploy --id <device-id> --bundle build/ios/iphoneos/Runner.app --nolldb
...
-------------------------
debugserver port: 57168
App path: /private/var/containers/Bundle/Application/666A4C8D-C54D-4C55-8594-1E1FE56406CD/Runner.app
```
Then later attach to that port with `--noinstall` (which launches if it's not already running):
```
ios-deploy --id <device-id> --bundle build/ios/iphoneos/Runner.app --noinstall --port 57168 
...
(lldb)     connect
(lldb)     run
success
2020-03-17 17:35:05.399716-0700 Runner[636:133192] flutter: Observatory listening on http://127.0.0.1:55427/ifXCFq2E91c=/
```
And even when it's running, I was able to print the observatory port for a standard app (the FlutterController wouldn't necessarily be the rootViewController for add-to-app) after interrupting the process (app would be briefly locked until resumed).
```
(lldb) process interrupt
Process 639 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00000001aa144198 libsystem_kernel.dylib`mach_msg_trap + 8
libsystem_kernel.dylib`mach_msg_trap:
->  0x1aa144198 <+8>: ret    

libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x1aa14419c <+0>: mov    x16, #-0x20
    0x1aa1441a0 <+4>: svc    #0x80
    0x1aa1441a4 <+8>: ret    
Target 0: (Runner) stopped.
(lldb)  po ((FlutterEngine *)[UIApplication.sharedApplication.keyWindow.rootViewController engine]).observatoryUrl.port
56889

(lldb) process continue
Process 639 resuming
```

**Comment by jmagman** [comment]
If it stays attached, would also resolve https://github.com/flutter/flutter/issues/39240

**Comment by Bloyal-it** [comment]
do you have any idea how can i attach the process of iOS device with visual studio code?
i found attach process from command palate and entered the localhost URL which has been generated using flutter run command. 
**Error connecting to the service protocol: failed to connect to http://localhost:1029**
