### ISSUE TITLE
[devicelab] Dismiss iOS system dialogs

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#54792]
The devicelab tests and benchmarks often suffer from iOS system dialogs, e.g. No SIM Card Installed, system update etc. In the past we must manually dismiss these dialogs.

Now we have found a way to do that remotely, by running a simple XCUITest, see https://github.com/digiter/infra-dialog. It takes a few seconds to run. 

We'd like to automate it as a cocoon health check, but the [xcodebuild command](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html) requires setting a destination. Does anyone know how to figure out the destination from the command line? /cc @jmagman @gaaclarke @christopherfujino @xster

**Comment by jmagman** [comment]
You can run `$ xcrun xcodebuild -project infra-dialog.xcodeproj -scheme infra-dialog -showdestinations` to see the destinations.  
```
	Available destinations for the "infra-dialog" scheme:
		{ platform:iOS, id:d83d5bc53967baa0ee18123ba8456254b2ab5418, name:Your iPhone }
```

Then you would do 
```
$ xcrun xcodebuild -project infra-dialog.xcodeproj -scheme infra-dialog -destination "id=d83d5bc53967baa0ee18123ba8456254b2ab5418" test

$ xcrun xcodebuild -project infra-dialog.xcodeproj -scheme infra-dialog -destination "name=Your iPhone" test
```

Unfortunately I don't know of way to target the first `platform:iOS` generically without parsing `-showdestinations` or the `instruments -s devices` output.

**Comment by digiter** [comment]
Bumping to P1 as this happens very frequently recently.

**Comment by gaaclarke** [comment]
`sed -n 's/^.*platform.*id:\([^\,]*\).*$/\1/p'`

Piping the  output of from jenn's command to this should give you `d83d5bc53967baa0ee18123ba8456254b2ab5418`.

**Comment by digiter** [comment]
Thanks @gaaclarke ! I found `idevice_id -l` could return the same result.

**Comment by digiter** [comment]
Related issues
* https://github.com/flutter/flutter/issues/62389
* https://github.com/flutter/flutter/issues/58501
* https://github.com/flutter/flutter/issues/58248
* https://github.com/flutter/flutter/issues/57323
* https://github.com/flutter/flutter/issues/53581
* https://github.com/flutter/flutter/issues/51574
* https://github.com/flutter/flutter/issues/50339

**Comment by digiter** [comment]
The fix has been deployed.
