### ISSUE TITLE
sky_engine reexports dart libraries that have missing _embedder.yaml mappings

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#54793]
@Hixie @stereotype441 

I first saw this while debugging dart-lang/dartdoc#2143.  The example I found is in `dart:html`, whose source code is copied directly from:   https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dart2js/html_dart2js.dart.  It reexports `promiseToFuture` from `dart:html_common`, which isn't available in sky_engine.

I do not understand how Flutter can possibly work under these conditions (Why are there no compilation errors?  Why are all analysis errors here always squelched?) but it clearly does.... so I'm filing this issue in part to ask:

1) Is this an actual problem (meaning, it is a bug that all of our tools seem to ignore this situation), or are situations like this considered "normal"?
2) If it isn't a problem, is ignoring this situation in tools the correct way to handle it?  Or should we be working around this in a different way?

For example, a combination of factors tend to result in dartdoc and the analyzer ignoring this under most circumstances and just silently hiding things.   You'll notice that in the documentation for `dart:html` at https://api.dart.dev/dev/2.8.0-dev.20.0/dart-html/dart-html-library.html includes `promiseToFuture`, but https://api.flutter.dev/flutter/dart-html/dart-html-library.html does not.

**Comment by jonahwilliams** [comment]
I believe the reason this works is because `sky_engine` isn't actually used by anything besides the analyzer and dartdocs. The actual platform code is already present in the platform dill file produced by the engine, and the supported dart libraries are defined in https://github.com/flutter/engine/blob/master/lib/snapshot/libraries.json

**Comment by jcollins-g** [comment]
@jonahwilliams @devoncarew That makes sense.  Though,  why is `dart:html`  available in sky_engine but not the platform file?

**Comment by jonahwilliams** [comment]
Flutter and Flutter for Web are different platforms with different available sets of dart SDK libraries. dart:html was added to sky engine because the web team wants web plugin authors to be able to get analysis results.

There is more context in https://github.com/flutter/flutter/issues/39998

**Comment by jcollins-g** [comment]
Thanks.  From reading this my general approach will be to continue to ignore and/or bypass analysis errors generated from sky_engine in dartdoc, and I'll follow up in #39998 if need be.
