### ISSUE TITLE
[web]: Custom font's not loaded unless installed on local system 

### ISSUE THREAD

**Issue by devlouie** [flutter/flutter#54795]
Running the app on firefox loads system font opposed to brand font that loads correctly in chrome. 

Link: https://bundyadmin.netlify.com/#/

**Environment:** 
OS X Catalina - Fresh re-install, Vanilla
Firefox Version 75.0

**Comment by devlouie** [comment]
*UPDATE* Custom fonts wont be loaded at all unless they are on the local system, as I installed a fresh install of Catalina and now all the web app fonts are native. Firefox is still a bit glitch-y though requiring a few refreshes before actually loading the web app in all its glory.

**Comment by TahaTesser** [comment]
Hi @devlouie 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @devlouie 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
