### ISSUE TITLE
flutter web dart_sdk.dart.getModuleLibraries error in browser console

### ISSUE THREAD

**Issue by perelin** [flutter/flutter#54794]
## Steps to Reproduce

1. create new project
2. update main.dart with content from below
3. run with flutter run --web-port=45441 --web-hostname=0.0.0.0
4. visit in browser
5. open browser error console

**Expected results:**
* the progress bar is working is advancing when filling out the form
* the welcome window appears when I click on submit

**Actual results:**
* progress bar does not move
* no welcome window appears

```
```

```

$ flutter analyze
Running "flutter pub get" in p2ftest...                             2.8s
Analyzing p2ftest...                                                    
   info • The method doesn't override an inherited method • lib/main.dart:46:8 • override_on_non_overriding_member
   info • 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The
          modern term is headline4. This feature was deprecated after v1.13.8. • lib/main.dart:58:16 •
          deprecated_member_use
   info • 'display3' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The
          modern term is headline2. This feature was deprecated after v1.13.8. • lib/main.dart:97:68 •
          deprecated_member_use
3 issues found. (ran in 11.6s)

```

```

$flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Linux, locale en_US)
    • Flutter version 1.17.0 at /home/coder/flutter
    • Framework revision d3ed9ec945 (8 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools
! Doctor found issues in 3 categories.

```

</details>

I started to checkout the flutter web app support. Following the tutorial [1] I encountered the following error in the browser console:

    TypeError: undefined is not an object (evaluating 'window.$requireLoader.getModuleLibraries = dart_sdk.dart.getModuleLibraries')
    
    Line: 16:22
    URL: http://rebalancr.net:45441/main_module.bootstrap.js
    Error: {}

None of the functionality of the tutorial works. E.g. progress bar and welcome window.

I`m using the latest beta build 

    $ flutter --version
    Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
    Framework • revision d3ed9ec945 (8 days ago) • 2020-04-06 14:07:34 -0700
    Engine • revision c9506cb8e9
    Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

Here my is my complete main.dart:

    import 'package:flutter/material.dart';
    
    void main() => runApp(LoginApp());
    
    class LoginApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          routes: {
            '/': (context) => LoginScreen(),
          },
        );
      }
    }
    
    class LoginScreen extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          backgroundColor: Colors.grey[200],
          body: Center(
            child: SizedBox(
              width: 400,
              child: Card(
                child: LoginForm(),
              ),
            ),
          ),
        );
      }
    }
    
    class LoginForm extends StatefulWidget {
      @override
      _LoginFormState createState() => _LoginFormState();
    }
    
    class _LoginFormState extends State<LoginForm> {
      final _firstNameTextController = TextEditingController();
      final _lastNameTextController = TextEditingController();
      final _usernameTextController = TextEditingController();
    
      double _formProgress = 0;
    
      @override
      void _showWelcomeScreen() {
        Navigator.of(context).pushNamed('/welcome');
      } 
      Widget build(BuildContext context) {
        return Form(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              LinearProgressIndicator(value: _formProgress),
              Text('Sign Up', style: Theme
                  .of(context)
                  .textTheme
                  .display1), // display1 changes to headline4 in 1.16
              Padding(
                padding: EdgeInsets.all(8.0),
                child: TextFormField(
                  controller: _firstNameTextController,
                  decoration: InputDecoration(hintText: 'First name'),
                ),
              ),
              Padding(
                padding: EdgeInsets.all(8.0),
                child: TextFormField(
                  controller: _lastNameTextController,
                  decoration: InputDecoration(hintText: 'Last name'),
                ),
              ),
              Padding(
                padding: EdgeInsets.all(8.0),
                child: TextFormField(
                  controller: _usernameTextController,
                  decoration: InputDecoration(hintText: 'Username'),
                ),
              ),
              FlatButton(
                color: Colors.blue,
                textColor: Colors.white,
                onPressed: _showWelcomeScreen,
                child: Text('Sign up'),
              ),
            ],
          ),
        );
      }
    }
    
    class WelcomeScreen extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: Center(
            child: Text('Welcome!', style: Theme.of(context).textTheme.display3),
          ),
        );
      }
    }

[1] https://flutter.dev/docs/get-started/codelab-web

I`m happy about any idea how to approach this.

Thanks!

**Comment by TahaTesser** [comment]
Hi @perelin 
Code Sample you provided has incomplete code compared to official sample

Please check [Complete Sample
](https://flutter.dev/docs/get-started/codelab-web#complete-sample) and paste in your editor and run it, no issues on `beta` or `dev`

Thank you

**Comment by perelin** [comment]
Hey @TahaTesser , thanks for the hint. The Complete sample code works just fine. So there seems to be an issue with either the web tutorial or my code (which was copy-pasted from the web tutorial). I`
ll try to figure out what is what and give and update here.

**Comment by perelin** [comment]
Found it. The "Write your first Flutter app on the web" (https://flutter.dev/docs/get-started/codelab-web) is missing some steps. 

1. To conclude "Step 1: Show the Welcome screen" one needs to add the route to '/welcome' to the LoginApp class build() method. 

2. The starter app code from the dart pad in "Step 0: Get the starter web app" is using the terminology "LoginApp/Screen/Form/XXX" but the rest of the tutorial uses "SignupApp/Screen/Form/XXX".

I reported it here https://github.com/flutter/website/issues/3974

**Comment by ph55** [comment]
> ```
> Uncaught TypeError: Cannot set property 'getModuleLibraries' of undefined
> ```

![image](https://user-images.githubusercontent.com/1386622/80586387-8cd9f380-8a1d-11ea-830c-e62b6fcf120a.png)

![image](https://user-images.githubusercontent.com/1386622/80586440-a418e100-8a1d-11ea-9c3c-c7a5b6540435.png)

Pull request that should fix the issue
https://github.com/flutter/flutter/pull/55085
