### ISSUE TITLE
Flutter not compatible with Dart 1.14-dev

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#548]
Running `flutter upgrade` after I installed the Dart 1.14-dev version, resulted in this error:

```
~/flutter/myapp $ flutter upgrade
Updating flutter tool...
Resolving dependencies... (1.1s) 
Package test has no versions that match >=0.12.5 <0.13.0 derived from:
- flutter_tools depends on version ^0.12.5
- mockito 0.10.1 depends on version >=0.12.0 <0.13.0
```

**Comment by abarth** [comment]
There is no version of the `test` package that is compatible with 1.14-dev: https://github.com/dart-lang/test/issues/360  Once a test package exists, then we can update to use that version.

**Comment by Hixie** [comment]
We just moved to stable instead. The latest `test` does work with 1.14-dev, but has other issues IIRC (the internal API changed again). I suggest we stay pinned to this version of test until we have reason to move.

**Comment by Hixie** [comment]
Though I guess if the Dart team is going to be doing work with Flutter we should fix this.

**Comment by sethladd** [comment]
A developer can use 1.14-dev to run `flutter init` and the project is initialized correctly. The test package dependency is now on 0.12.5+2
