### ISSUE TITLE
flutter drive command fails with WebDriverException when running the integration test

### ISSUE THREAD

**Issue by brainmobilizer** [flutter/flutter#54802]
I'm writing a flutter app and for integration testing, I've followed the [flutter tutorial](https://flutter.dev/docs/cookbook/testing/integration/introduction). 
I've written a very simple test to check the flutter driver's health status as follows:
```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Flutter app', () {
    FlutterDriver driver;
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null) {
        await driver.close();
      }
    });

    test('Check flutter driver health status', () async {
      final Health health = await driver.checkHealth();
      expect(health.status, HealthStatus.ok);
    });
  });
}
```
I've downloaded [chromedriver](https://chromedriver.chromium.org/downloads) and run the commands.
```
./chromedriver --port=4444
flutter drive --browser-name=chrome --release --driver-port=4444 --target=test_driver/app.dart
```
Testing works well with the iPhone Simulator & Android emulator.
However, on the web platform, testing fails with WebDriverException. 
I've checked chromedriver's status from `http://localhost:4444/status` and it obviously runs well.
`{"value":{"build":{"version":"81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Mac OS X","version":"10.15.3"},"ready":true}}`

Here's the crash report I've got.

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter drive --browser-name=chrome --release --driver-port=4444 --target=test_driver/app.dart
> 
> ## exception
> 
> WebDriverException: WebDriverException (null): unknown command: unknown command: wd/hub/session
> 
> ```
> #0      parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:85:9)
> #1      JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:26:21)
> #2      JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
> #3      SyncRequestClient.send (package:webdriver/src/common/request_client.dart:46:25)
> #4      createDriver (package:webdriver/sync_core.dart:63:26)
> #5      createDriver (package:webdriver/sync_io.dart:35:5)
> #6      _createDriver (package:flutter_tools/src/commands/drive.dart:441:10)
> #7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:182:16)
> <asynchronous suspension>
> #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:638:18)
> <asynchronous suspension>
> #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
> <asynchronous suspension>
> #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
> #11     _rootRun (dart:async/zone.dart:1126:13)
> #12     _CustomZone.run (dart:async/zone.dart:1023:19)
> #13     _runZoned (dart:async/zone.dart:1518:10)
> #14     runZoned (dart:async/zone.dart:1465:12)
> #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
> #17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> #18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
> <asynchronous suspension>
> #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
> #20     _rootRun (dart:async/zone.dart:1126:13)
> #21     _CustomZone.run (dart:async/zone.dart:1023:19)
> #22     _runZoned (dart:async/zone.dart:1518:10)
> #23     runZoned (dart:async/zone.dart:1465:12)
> #24     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
> #26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
> #27     new Future.sync (dart:async/future.dart:224:31)
> #28     CommandRunner.run (package:args/command_runner.dart:112:14)
> #29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
> #30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
> #31     _rootRun (dart:async/zone.dart:1126:13)
> #32     _CustomZone.run (dart:async/zone.dart:1023:19)
> #33     _runZoned (dart:async/zone.dart:1518:10)
> #34     runZoned (dart:async/zone.dart:1502:12)
> #35     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
> <asynchronous suspension>
> #36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
> #37     _rootRun (dart:async/zone.dart:1126:13)
> #38     _CustomZone.run (dart:async/zone.dart:1023:19)
> #39     _runZoned (dart:async/zone.dart:1518:10)
> #40     runZoned (dart:async/zone.dart:1465:12)
> #41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
> #42     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
> #43     run (package:flutter_tools/runner.dart:51:10)
> #44     main (package:flutter_tools/executable.dart:65:9)
> #45     main (file:///Users/iMac/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> #46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```
> 
> ## flutter doctor
> 
> ```
> [✓] Flutter (Channel unknown, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-US)
>     • Flutter version 1.14.6 at /Users/iMac/Development/flutter
>     • Framework revision fabeb2a16f (3 months ago), 2020-01-28 07:56:51 -0800
>     • Engine revision c4229bfbba
>     • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at /Users/iMac/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C504
>     • CocoaPods version 1.9.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.44.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.9.1
> 
> [✓] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92
>     • Web Server • web-server • web-javascript • Flutter Tools
> 
> • No issues found!
> ```
> 
I want to run integration tests on the web platform as well.
Please give me some help.
@jonahwilliams @angjieli @yjbanov @nturgut

FYI, I'm using `beta` channel of `v1.14.6`.

**Comment by angjieli** [comment]
Can you switch to the latest? That version might have some bug.

**Comment by brainmobilizer** [comment]
Thanks! It works. Now I'm using `beta` of `v.1.17.0` and it works well.
