### ISSUE TITLE
Flutter web view performance

### ISSUE THREAD

**Issue by codeomnitrix** [flutter/flutter#54810]
Hello,

I am using flutter web view in my app and its a crucial part of my app. However I have noticed that the webview page load is more than twice the original time it takes on the native app and mobile safari browser. I have been looking upon the webview performance optimization on ios, but couldn't find any. 

As mentioned here https://stackoverflow.com/questions/55587918/web-view-is-too-slow
It looks like webview is created everytime I navigate within the webview i.e. go to different page. Which adds upto the page load time. I couldn't really find out an option to use external state or Mutable webview.

**Comment by TahaTesser** [comment]
Hi @codeomnitrix 
Do you notice on multi devices? Android or iOS?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by codeomnitrix** [comment]
Hi @TahaTesser 
I notice this issue on ios device Iphone 7, Iphone XR and Iphone 11 Pro, I am not working on android device as of now.

`flutter doctor -v` Output
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/vinitt/Documents/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vinitt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```


Code snippet - 

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class AppPage extends StatefulWidget {
  final String _appTitle;
  final String _connectionString;
  AppPage(this._appTitle, this._connectionString);
  @override
  _AppPageState createState() =>
      _AppPageState(this._appTitle, this._connectionString);
}

class _AppPageState extends State<AppPage> {
  final String _appTitle;
  final String _connectionString;
  num _stackToView = 1;
  final _key = GlobalKey();
  _AppPageState(this._appTitle, this._connectionString);
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(middle: Text(_appTitle)),
      child: Container(
        child: SafeArea(
          child: IndexedStack(
            index: _stackToView,
            children: <Widget>[
              WebView(
                key: _key,
                javascriptMode: JavascriptMode.unrestricted,
                initialUrl: this._connectionString,
                onPageStarted: (value) => setState(() {
                  _stackToView = 1;
                }),
                onPageFinished: (value) => setState(() {
                  _stackToView = 0;
                }),
              ),
              Container(
                color: Color.fromRGBO(250, 250, 250, 1),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            ],
          ),
          top: true,
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @codeomnitrix 
Running code sample vs running official example, your code sample is slower maybe because you're doing something that resulting it be maybe `IndexedStack` and `setState`

I have tried official example in release mode on iPhone XR and it's loads fast

![RPReplay-Final1587022989](https://user-images.githubusercontent.com/48603081/79429269-f05b2e80-7fe4-11ea-91d0-72753d0e3ea2.gif)



Please try official `webview_flutter ` [example](https://pub.dev/packages/webview_flutter#-example-tab-) using `flutter run --release` 

Thank you

**Comment by codeomnitrix** [comment]
@TahaTesser I have removed the IndexedStack, it looks ok now. we can close the issue

**Comment by Nasrumink** [comment]
Hi All,
This is my first app I ever created.
I am facing the same issue on android.
`






import 'dart:async';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final Completer<WebViewController> _controller = Completer<WebViewController>();

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: WebView(
        initialUrl: "https://theonlineindia.co.in",
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller.complete(webViewController);
        },
      ),
    );
  }
}
`

Please guide.
