### ISSUE TITLE
Calling MethodChannel causes freeze/Not responding/Waiting/crashing 

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#54817]
I have a kotlin getStream.io APi code, and a flutter dart code that is calling that code via a MethodChannel. 

This is slow as hell and my UI freeze/Not responding/Waiting/crashing my app

I chose compute to handle this thing, but I got an exception

Unhandled Exception: Exception: error: native function 'Window_setNeedsReportTimings' (2 arguments) cannot be found

my code is:
```

Future<dynamic> addLike(Map map) async {
  WidgetsFlutterBinding.ensureInitialized();
  Map streamAccount = map["streamAccount"];
  String activityID = map["activityID"];
  String myUserId = map["myUserId"];
  return await _platform.invokeMethod<String>('addLike', {
    'user': streamAccount['user'],
    'token': streamAccount['feedToken'],
    'activityID': activityID,
    'extraUserID': myUserId,
  });
}
```

Any fix for this?

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
