### ISSUE TITLE
Flutter keyboard hides textfield in android but working fine in iOS

### ISSUE THREAD

**Issue by prtrigno** [flutter/flutter#54816]
Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        margin: EdgeInsets.all(0.0),
        decoration: BoxDecoration(
          image: DecorationImage(
              image: AssetImage("assets/images/background.png"),
              fit: BoxFit.fill),
        ),
        child: Stack(
          children: <Widget>[
            Center(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                child: signUpCardView,
              ),
            ),
            userLogin(bloc),
          ],
        ),
      ),
    );
  }

//Center card view
Widget get signUpCardView {
    return SingleChildScrollView(
          child: Card(
        color: Colors.white,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.symmetric(vertical: 30.0),
              child: Center(
                child: Column(
                  children: <Widget>[
                    Text(
                      "${AppTranslations.of(context).text("signUp")}",
                      style: TextStyle(
                        color: AppColors.BUTTON_SECONDARY_BACKGROUND_COLOR,
                        fontFamily: customFontFamily,
                        fontSize: 30.0,
                      ),
                    ),
                    SizedBox(
                      width: 50,
                      height: 20,
                      child: Divider(
                        thickness: 4.0,
                        color: AppColors.BUTTON_SECONDARY_BACKGROUND_COLOR,
                      ),
                    )
                  ],
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 0.0),
              child: nameField(bloc),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 0.0),
              child: mobileField(bloc),
            ),

**Comment by prtrigno** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
Hi @prtrigno 
Please post the text instead of screenshots.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by prtrigno** [comment]
Hi @VladyslavBondarenko 
I have replaces the image with code

**Comment by VladyslavBondarenko** [comment]
@prtrigno 
<details>
 <summary>I simplified and completed your code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Stack(
          children: [
            Center(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                child: signUpCardView,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

Widget get signUpCardView {
  return SingleChildScrollView(
    child: Card(
      child: Column(
        children: [
          Container(
            height: 500,
            child: Text('test'),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 0.0),
            child: TextField(),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 0.0),
            child: TextField(),
          ),
        ],
      ),
    ),
  );
}
```

</details>

does it reproduce your problem?

<details>
 <summary>What I see is that focused TextField isn't hidden by keyboard for both Android and iOS</summary>

![image](https://user-images.githubusercontent.com/17024977/79360420-91e27180-7f4c-11ea-8e73-c35fac4be096.png)

</details>

Tried with `dev v1.18.0-dev.5.0`.

Describe your problem or better attach screen recording, edit the code sample if needed

**Comment by prtrigno** [comment]
Finally resolved my issue. It was due to <item name="android:windowFullscreen">true</item> in styles.xml. But why is it so?

**Comment by VladyslavBondarenko** [comment]
@prtrigno 
follow up on the issue https://github.com/flutter/flutter/issues/51165
closing current one as duplicate
Thank you
