### ISSUE TITLE
A non-null String must be provided to a Text widget.

### ISSUE THREAD

**Issue by seadhant** [flutter/flutter#54819]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building LocationScreen(dirty, state: _LocationScreenState#85589):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  LocationScreen file:///C:/Users/sidha/Desktop/weather_app/lib/screens/loading_screen.dart:24:14
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:285:10)
#3      _LocationScreenState.build (package:weatherapp/screens/location_screen.dart:110:26)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by VladyslavBondarenko** [comment]
Hi @seadhant 
Take a look at https://github.com/flutter/flutter/issues/40214#issuecomment-530587931
Closing, as duplicate and not an issue with Flutter itself
Thank you
