### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by paulogalindo** [flutter/flutter#54822]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: O sistema não pode encontrar o arquivo especificado.
, errno = 2
(The system cannot find the file specified., errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:189:28)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#24     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.26, on Microsoft Windows [versÃ£o 10.0.19041.173], locale pt-BR)
    • Flutter version 1.18.0-6.0.pre.26 at C:\src\flutter\flutter
    • Framework revision 846e8fe812 (6 hours ago), 2020-04-15 03:21:14 +0200
    • Engine revision deef2663ac
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\paulo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29905.134

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\IntelliJ IDEA Community Edition 2019.3.2
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[✓] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • SM A305GT  • RQ8M40ECXMV • android-arm64  • Android 10 (API 29)
    • Windows    • Windows     • windows-x64    • Microsoft Windows [versÃ£o 10.0.19041.173]
    • Chrome     • chrome      • web-javascript • Google Chrome 81.0.4044.92
    • Web Server • web-server  • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by paulogalindo** [comment]
vscode insiders não está funcionando.

**Comment by VladyslavBondarenko** [comment]
Hi @paulogalindo 
Is it the project with build for Windows? (I see it in connected devices)
can you see the error when running `flutter create --ios-language swift --android-language kotlin bug` or only when destination is the current directory `.`?

**Comment by guidezpl** [comment]
I also got the same error. Steps to repo

1. Start with a non-windows project.
2. `flutter create .` adds windows file.
3.`flutter run` with a non-windows device (in my case, Chrome).
4. Delete windows directory.
5. Subsequent `flutter run`s with a non-windows device fail.

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=chrome lib/main.dart

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/plg/development/gallery/windows/Runner.sln' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Mac OS X 10.15.4 19E287, locale en-DE)
    • Flutter version 1.18.0-9.0.pre.14 at /Users/plg/development/flutter
    • Framework revision dd88b20435 (3 days ago), 2020-04-25 19:02:03 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/plg/Library/Android/sdk
    • Platform android-stable, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/plg/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
    • Pixel 3a   • 976AY0ZMV1 • android-arm64  • Android 10 (API 29)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
@guidezpl great,
I'm not sure it's the same, because the executed command there was `create` and the error was `cannot create`, not `cannot open`.
Just for case it would be good if you file a separate issue with your case

**Comment by guidezpl** [comment]
Filed https://github.com/flutter/flutter/issues/55958

**Comment by VladyslavBondarenko** [comment]
@paulogalindo 
please follow up on https://github.com/flutter/flutter/issues/40700,
closing current issue as a duplicate,
if you disagree please write in the comments and I will reopen it
