### ISSUE TITLE
cant download  flutter

### ISSUE THREAD

**Issue by NuaimanAshiq** [flutter/flutter#54824]
<img width="1440" alt="Screen Shot 2020-04-15 at 2 04 22 PM" src="https://user-images.githubusercontent.com/40488562/79313350-048a2780-7f22-11ea-8572-ea396ba8f106.png">

**Comment by VladyslavBondarenko** [comment]
Hi @NuaimanAshiq 
is firewall in country your case? https://flutter.dev/community/china
can you download from this link?
https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.9-stable.zip

**Comment by NuaimanAshiq** [comment]
> Hi @NuaimanAshiq
> is firewall in country your case? https://flutter.dev/community/china
> can you download from this link?
> https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.9-stable.zip

hello. but I am not from china....

**Comment by VladyslavBondarenko** [comment]
@NuaimanAshiq does using Mirrored URL help?

**Comment by TahaTesser** [comment]
Hi @NuaimanAshiq 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
