### ISSUE TITLE
Upload and download file with iCloud

### ISSUE THREAD

**Issue by TaiHK** [flutter/flutter#54826]
Flutter can upload and download file with iCloud ? 
With download can use the library below, but do not support upload.
https://pub.dev/packages/file_picker
https://pub.dev/packages/documents_picker

Is there any library that supports signing in with iCloud?

**Comment by stuartmorgan** [comment]
We have no plans to implement a first-party plugin specifically for iCloud; iOS certainly something a third party could build.
