### ISSUE TITLE
Application is crashing due to memory issues after using flutter_localizations dependency

### ISSUE THREAD

**Issue by Faisalkc4u** [flutter/flutter#54820]
I added the following dependencies in my flutter application
  flutter_localizations:
    sdk: flutter
After adding this dependency my app started crashing due to memory issues. 
The issue is reproducible in ios and android (Not in simulators) which is having 1GB RAM or less 
In Dart Dev Tools -> Memory 
It's showing as follow

![Screen Shot 2020-04-15 at 10 40 00 AM](https://user-images.githubusercontent.com/12441355/79306922-1c07e700-7f07-11ea-83e2-de92df895c52.png)

## Steps to Reproduce
1. Add the dependency
  flutter_localizations:
    sdk: flutter
2. set up flutter_localizations plugin
I'm using English and Arabic
```
MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      localizationsDelegates: [
        // ... app-specific localization delegate[s] here
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        AppLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en'), // English
        const Locale('ar'), // Arabic
      ],
.......
```

The logs are available [here](https://github.com/flutter/flutter/files/4479614/logs.txt)

**Comment by HansMuller** [comment]
The app is set up correctly. The code that loads the DateSymbols, https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/utils/date_localizations.dart, might be culprit.

@Faisalkc4u - can you add the output from `flutter doctor -v` to this issue's description?

**Comment by Faisalkc4u** [comment]
I have already attached` flutter doctor -v ` logs the  as a text file because it is large.

**Comment by jason-simmons** [comment]
The attached heap snapshot shows 92 instances of `DateSymbols` consuming 20kb of memory.  That seems normal.

To get a more complete view of memory usage, try going to the DevTools Memory settings and enabling all libraries (including Dart and Flutter) in the snapshot.  Or try looking at the allocation profile in the Dart Observatory.

**Comment by TahaTesser** [comment]
Hi @Faisalkc4u 
Are you still experiencing this issue? 

if yes, please provide more details asked above https://github.com/flutter/flutter/issues/54820#issuecomment-614986525


If yes, Can you please provide your `flutter doctor -v` with the latest version 
Thank you

**Comment by Faisalkc4u** [comment]
I'm not able to reproduce this issue in 
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (11 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by TahaTesser** [comment]
Hi @Faisalkc4u 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
