### ISSUE TITLE
The ADB  is too old; please install version 1.0.39 or later. 

### ISSUE THREAD

**Issue by chenchunming** [flutter/flutter#54838]
I first run flutter app。
error：
Launching lib/main.dart on ONEPLUS A3010 in debug mode...
The ADB at "/Users/chenchunming/Library/Android/sdk/platform-tools/adb" is too old; please install version 1.0.39 or later.
Error launching application on ONEPLUS A3010.

**Comment by VladyslavBondarenko** [comment]
Hi @chenchunming 
what version of adb do you have?
you can see it when launching `/Users/chenchunming/Library/Android/sdk/platform-tools/adb`. 
Are you using Android Studio? you may need to update `Android SDK Platform-Tools` in Preferences > Appearence & Behavior > System Settings > Android SDK > SDK Tools

**Comment by chenchunming** [comment]
my adb version is 1.0.41 
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as /Users/adt-bundle-mac-x86_64-20140702/sdk/platform-tools//adb

**Comment by VladyslavBondarenko** [comment]
@chenchunming 
provide please your `flutter doctor -v`

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by rishabhrastogi31** [comment]
Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\RISHABH\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\RISHABH\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\RISHABH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • G • G350RM04810601AR • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

**Comment by rishabhrastogi31** [comment]
> Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\Users\RISHABH\AppData\Local\Android\Sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-29, build-tools 29.0.3
> • ANDROID_HOME = C:\Users\RISHABH\AppData\Local\Android\Sdk
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> X Android license status unknown.
> Try re-installing or updating your Android SDK Manager.
> See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
> instructions.
> 
> [√] Android Studio (version 3.6)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.8052
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.45.1)
> • VS Code at C:\Users\RISHABH\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.10.1
> 
> [√] Connected device (1 available)
> • G • G350RM04810601AR • android-arm64 • Android 8.1.0 (API 27)
> 
> ! Doctor found issues in 1 category.

please provide fix as licenses cannot be accepted

**Comment by VladyslavBondarenko** [comment]
@rishabhrastogi31 take a look at https://github.com/flutter/flutter/issues/51670
