### ISSUE TITLE
[Material] Adapt BottomNavigationBarTile widget to screen size

### ISSUE THREAD

**Issue by jesusrp98** [flutter/flutter#54834]
## Use case

This feature will improve a native Material widget inside the Flutter framework.

Inside Material Desing's [bottom navigation](https://material.io/components/bottom-navigation/) component guide, it is specified that, if the current device is a mobile in landscape mode, or tablet (any widescreen device), each tile of this navigation bar should adapt itself to display the tab title right after the icon, not below it, as shown in the image below.

![imagen](https://user-images.githubusercontent.com/8961959/79327988-a5beb100-7f15-11ea-9975-39876901e711.png)

## Proposal

Make the `_BottomNavigationTile` widget aware of screen size, by using the `MediaQuery` class.

**Comment by Piinks** [comment]
I believe this was resolved by #87211
