### ISSUE TITLE
PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)

### ISSUE THREAD

**Issue by sumitrvi** [flutter/flutter#54835]
I'm facing google signin issue in ios .but it' working fine android.
Error:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
#3      MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
#4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#6      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:205:42)
#7      _SigninScreenState.socialLogin (package:down_beatflutterproject/screens/signinscreen.<…>

dependencies:
  google_maps_flutter: ^0.5.25+2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.0
  firebase_auth: ^0.15.5+3

flutter doctor -v
• Flutter version 1.12.13+hotfix.8 at /Users/theninehertz/Desktop/hybrid/sumit/fluttersdk/flutter
    • Framework revision 0b8abb4724 (9 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
   • Xcode at /Applications/Xcode 11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Please careful these steps from [iOS integration ](https://pub.dev/packages/google_sign_in#ios-integration) and make sure you've added proper CLIENT_ID in the step from [Google Cloud Platform API manager](https://console.developers.google.com/)
Thank you

**Comment by sumitrvi** [comment]
@did you mean client_id? but I've added reversed_client id to infop.list. i've these ids CLIENT_ID,REVERSED_CLIENT_ID,ANDROID_CLIENT_ID
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb2527140277504384</string>
			</array>
		</dict>
		<dict>
            		<key>CFBundleTypeRole</key>
            		<string>Editor</string>
            		 <key>CFBundleURLName</key>
                     <string>REVERSED_CLIENT_ID</string>
            		<key>CFBundleURLSchemes</key>
            		<array>
            			<string>reverse_client_idl</string>
            		</array>
            	</dict>
	</array>
Please check  and help me out this issue.

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
can you please provide your  `flutter run --verbose` while log in with google sign? 
Thank you

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
