### ISSUE TITLE
SliverPersistentHeader floating behavior is different when scrolled with mouse scroll-wheel than when dragging

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#54836]
## Steps to Reproduce

1. Open this [DartPad example](https://dartpad.dartlang.org/b115e68df5c9f1bdc2e7ed18586cc0dd)
2. Scroll down with your scroll-wheel - the red header gets hidden
3. Scroll up with scroll-wheel - the red header is hidden until the top of the CustomScrollView is reached
4. Scroll down by dragging list with mouse or finger - the red header gets hidden
5. Scroll up by dragging list with mouse or finger - the red header reappears

The expected behavior in my opinion should be the same for both kinds of scrolling. The red SliverPersistentHeader should reappear on scroll up with scroll-wheel.

The code is also available [as gist](https://gist.github.com/orestesgaolin/b115e68df5c9f1bdc2e7ed18586cc0dd)

## Logs

Example is run in DartPad based on Dart SDK 2.7.2

May be related to #40430

**Comment by yjbanov** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/54836. Please reopen if you believe it's different.

**Comment by Piinks** [comment]
> This looks like a duplicate of #54836. Please reopen if you believe it's different.

@yjbanov can you provide the issue number again? That number is this issue. :)

**Comment by orestesgaolin** [comment]
@Piinks I think @yjbanov meant this one #40430

**Comment by akmalviya03** [comment]
I'm also facing the same issue. I have tried every possible solution.
