### ISSUE TITLE
MediaQuery.of(context).padding can return EdgeInsets.zero

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#5483]
When running on the Android emulator and occasionally when running Android native, MediaQuery.of(context).padding.top is zero the first time it's called at Widget initState() time. Calling it later, e.g. at build() time instead appears to consistently return the status bar's actual height.

This came up on the gallery demo's home screen, see https://github.com/flutter/flutter/issues/5368

**Comment by eseidelGoogle** [comment]
This sounds related to https://github.com/flutter/flutter/issues/5259 ?

**Comment by Hixie** [comment]
In general MediaQuery.of() can return different values each time. That's why it's an InheritedWidget. Caching the value in initState is going to lead to bugs regardless.

**Comment by HansMuller** [comment]
The MediaQuery definitely didn't belong in initState(). 

On the other hand it seemed odd to report that the status bar's height was 0 and then ~25 later on, since the status bar is static. However I think the gist of this and #5259 is that developers need to deal with startup time zero-to-actual-value geometry changes.
