### ISSUE TITLE
Unable to find gradlew..

### ISSUE THREAD

**Issue by muthu-gokul** [flutter/flutter#54844]
I tried flutter run.but still the error exists.. gradlew.bat is not downloading.. but while running it shows downloading gradle wrapper

**Comment by VladyslavBondarenko** [comment]
Hi @muthu-gokul 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?

**Comment by muthu-gokul** [comment]
Target file verbose not found

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
