### ISSUE TITLE
web_benchmarks_html text_out_of_picture_bounds.html.totalUiFrame.average baseline looks low

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54849]
This is a newer benchmark, plus it doesn't have a lot of history --- I'm wondering if the baseline is correct.

<img width="353" alt="Screen Shot 2020-04-15 at 8 14 09 AM" src="https://user-images.githubusercontent.com/1435716/79354415-3afb7e80-7ef1-11ea-81da-87641fa60bb3.png">

**Comment by mehmetf** [comment]
Assigning to @yjbanov to take a look. From the trend, it does look like the baseline needs to be revisited.

**Comment by yjbanov** [comment]
Done. This benchmark should improve drastically when https://github.com/flutter/engine/commit/dd87e3f944cf8dd6829149f7a480cd2d1869a1bc rolls into the framework.
