### ISSUE TITLE
Flutter App is crashing on a certain page but only when I have the app released on Play Store. My build apk works fine.

### ISSUE THREAD

**Issue by RndmNub** [flutter/flutter#54841]
## Steps to Reproduce

A page crashes the entire app when it's fully loaded. But only on Play Store released app.

**Expected results:** 

No crash.

**Actual results:** 

Crash

<details>
  <summary>Logs</summary>

```
```

](url
![Screenshot_2020-04-15-18-09-16-219_com miui bugreport](https://user-images.githubusercontent.com/42836744/79338718-6b6d0800-7f45-11ea-887f-580a66b06287.jpg)
)

```
```

[✓] Flutter (Channel beta, v1.17.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.0 at /home/randomnoob/flutter
    • Framework revision d3ed9ec945 (9 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/randomnoob/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/randomnoob/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/randomnoob/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
</details>

**Comment by jason-simmons** [comment]
The app is crashing during handling of a message sent from the Dart code to the host Android app:
    https://github.com/flutter/engine/blob/master/shell/platform/android/platform_view_android_jni.cc#L76

The Java code in the host app is throwing an exception.  It's hard to tell what happened without the stack trace from the Java exception.

**Comment by leminhph** [comment]
The same thing happens with an iOS release build on Flutter **v1.17.0-dev.3.1**. Rolling back to **v1.15.17** works.

**Comment by chinmaygarde** [comment]
Without a stack trace or a reduced test case, it is unlikely we will be able to make any progress investigating this issue. Closing.
