### ISSUE TITLE
Cannot access 'android.arch.lifecycle.LifecycleOwner', incompatibility with Android Studio Kotlin plugin version 1.3.71

### ISSUE THREAD

**Issue by z-dmitri** [flutter/flutter#54843]
Issue still there for the last Flutter master/dev/beta:
https://github.com/flutter/flutter/issues/36160
https://youtrack.jetbrains.com/issue/KT-37355

to reproduce:
0. Setup IntelliJ IDEA according documentation
1. Create new Flutter project
2. Open MainActivity.kt file

You will see 'android.arch.lifecycle.LifecycleOwner' error

**Comment by VladyslavBondarenko** [comment]
Hi @z-dmitri 
Please follow up on https://github.com/flutter/flutter/issues/52077,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
