### ISSUE TITLE
Make `flutter build aot` accept command line arguments from `flutter build apk`

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#54846]
Could we make `flutter build aot` accept flags such as `--obfuscate` and `--split-debug-info`, similar to how `flutter build apk`.

**Comment by jonahwilliams** [comment]
`flutter build aot` needs to be deprecated and removed, as it is not used by anything besides the Dart benchmarks currently. Adding more features to it would be counter to that goal
