### ISSUE TITLE
GTK: Implement raw key events

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#54854]
The GTK embedding needs raw key event support. I'm not sure offhand if this will require a new keyboard mapping in the framework, or if the Linux mapping is toolkit-agnostic.

**Comment by robert-ancell** [comment]
I've done some previous work on this in https://github.com/robert-ancell/engine/tree/linux-shell-events, but have shelved the work for now to get the platform channels done first.

I mapped the GTK events to GLFW events as a hack, which worked for tab and escape (tested using a text input field). We'll have to make a new mapping in the engine or a more general mapping for a long term solution.

The shell side of this is just 1-2 days work to clean up the patch, the new framework mapping is probably a similar amount of time, depending on how familiar the dev is with that code.

**Comment by stuartmorgan** [comment]
Fixed by PR linked above.

(@robert-ancell FYI if you put "Fixes <link to issue here>" in the main PR description, rather than just a comment on it, GitHub will auto-close that issue when the PR lands. That should in turn auto-update the state in projects it's part of, like Linux Preview. So it reduces a bunch of bookkeeping.)
