### ISSUE TITLE
GTK: Implement basic flutter/platform system channel

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#54857]
The initial steps needed for GLFW parity in the GTK embedding are:
- [ ] `Clipboard.getData`/`setData`
- [ ] `SystemNavigator.pop`

**Comment by robert-ancell** [comment]
Once the platform channel support has landed, this is about a days work.

**Comment by robert-ancell** [comment]
I've finished https://github.com/flutter/engine/pull/18316 off so it now does the clipboard and application quit.
