### ISSUE TITLE
[flutter_tools] Intellij 2020 plugins not detected by doctor

### ISSUE THREAD

**Issue by fogelfish** [flutter/flutter#54867]
I'm hoping that the flutter team will take a look a this.  JetBrains took a look at it (https://youtrack.jetbrains.com/issue/WEB-44945) and closed that ticket with this comment: 

> "flutter doctor tool is not under JetBrains control, I'm afraid there's nothing we can do on the IDE end"

What steps will reproduce the issue?

1. install and use IDEA Ultimate 2020.1
2. install the Flutter and Dart plugins
3. run flutter doctor -v

What is the expected result?
flutter doctor should report that the flutter and dart plugins are installed.

What happens instead?
flutter doctor reports that the flutter and dart plugins are NOT installed.

I have successfully run flutter projects in iOS and Android emulators. I am using the stable channel of the Dart SDK and the beta channel of the Flutter SDK. I am using the most up-to-date flutter and dart IDE plugins. This is the same environment for which I was using IDEA Ultimate 2019.3. and this issue did not occur.  I can't be absolutely sure, but I think the problem arose once I started using 2020.1 but other factors may have come into play.

**Comment by TahaTesser** [comment]
Hi @fogelfish 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by fogelfish** [comment]
Hi @TahaTesser.  A couple preliminary notes: although flutter doctor is currently finding Chrome and Web Server only, IntelliJ does in fact have use of an iOS simulator and an Open Android Emulator (Pixel 2).  Also note: Android Studio has been crashing on startup but it has done that from the start, as soon as I installed it (had never used it before); I've reported this to Google.  However I don't think this relates to flutter's issue here, because I was having the same problem even when flutter doctor did report IntelliJ correctly.  (I'm running with up-to-date OS X Catalina.)

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/brianfogel/flutter/flutter
    • Framework revision d3ed9ec945 (11 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brianfogel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/brianfogel/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @fogelfish 
Can you switch to `master channel` and see if detects IDE plugins are installed or not?
Thank you

**Comment by fogelfish** [comment]
I switched to `master channel`, then ran `flutter upgrade`, and then `flutter doctor`.

Downloading android-arm-profile/darwin-x64 tools...                 1.6s
Downloading android-arm-release/darwin-x64 tools...                 1.3s
Downloading android-arm64-profile/darwin-x64 tools...               1.9s
Downloading android-arm64-release/darwin-x64 tools...               1.4s
Downloading android-x64-profile/darwin-x64 tools...                 1.6s
Downloading android-x64-release/darwin-x64 tools...                 1.4s
[✓] Flutter (Channel master, v1.18.0-6.0.pre.88, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.18.0-6.0.pre.88 at /Users/brianfogel/flutter/flutter
    • Framework revision 34895351be (24 minutes ago), 2020-04-20 09:21:15 -0700
    • Engine revision 7ae7ff4419
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 88876d5642)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brianfogel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/brianfogel/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (4 available)
    • sdk gphone x86 • emulator-5554                        • android-x86    • Android 10
      (API 29) (emulator)
    • iPhone 11 Pro  • E4A7AB1C-AA17-41F3-A8FA-CD7D032CD650 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome         • chrome                               • web-javascript • Google
      Chrome 80.0.3987.163
    • Web Server     • web-server                           • web-javascript • Flutter
      Tools

! Doctor found issues in 2 categories.

**Comment by CodeCooler** [comment]
I'm also seeing this behavior. In my case, I have both Android Studio and IntelliJ IDEA 2020 installed, and although I am able to use both IDEs to create/build/install Flutter apps, it appears Flutter Doctor simply refuses to believe that the plugins are installed in IDEA.

Output of `flutter doctor -v` follows:

**Comment by tanchao90** [comment]
I have the same problem. 
Test date:2020-04-26

```shell
~ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/myname/dev_config/flutter
    • Framework revision f139b11009 (4 周前), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by DavidLiedle** [comment]
I'm having the same issue. I dug in to the code a little to see where it looks like this is handled: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/intellij/intellij.dart#L43

**Comment by yanshouwang** [comment]
This happened on my company's computer, but works well on my personal computer...the only difference I have in mind is my company's computer is Windows To Go System

**Comment by yanshouwang** [comment]
I have solved this by reinstalled the Android Studio

**Comment by christopherfujino** [comment]
The root issue is that the tool does not account for having both Android Studio AND IntelliJ installed (or multiple versions of one or the other for that matter), and will just check the first one it comes across for the plugins.

**Comment by fogelfish** [comment]
@christopherfujino, I don't think that was the case before this issue cropped up: flutter doctor found the plugins in AS and IDEA (a clean bill of health, you might say).  To test your assertion I uninstalled Android Studio just now; I also upgraded the IDE and flutter because updates happened to be available; then I ran flutter doctor.

```
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
```
Where in the file system is flutter looking for these plugins?

**Comment by christopherfujino** [comment]
@fogelfish you're right, it looks like it may be hard-coded to check the Android Studio plugins path, even if we're in IntelliJ: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L129

**Comment by brachior** [comment]
Jetbrains changes the plugins directory since the 2020.x versions ([2019](https://www.jetbrains.com/help/idea/2019.3/tuning-the-ide.html#plugins-directory) - [2020](https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory))

* Windows:
  * from: `%HOMEPATH%\\.<product><version>\config\plugins`
  * to: `%APPDATA%\JetBrains\<product><version>\plugins`
* MacOS:
  * from: `~/Library/Application Support/<product><version>`
  * to: `~/Library/Application Support/JetBrains/<product><version>/plugins`
* Linux:
  * from: `~/.<product><version>/config/plugins`
  * to: `~/.local/share/JetBrains/<product><version>`

To fix the problem before a flutter update, I just created a symbolic link of my plugins directory:

```bash
ln -s /Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2020.1/plugins /Users/xxx/Library/Application\ Support/IntelliJIdea2020.1
```

```bash
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Users/xxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43
```

**Comment by fogelfish** [comment]
@brachior, thanks for sussing that out. That was it.

**Comment by DZadig** [comment]
@christopherfujino thank you for the link, but is this issue will be fixed in the next update ?

**Comment by christopherfujino** [comment]
> @christopherfujino thank you for the link, but is this issue will be fixed in the next update ?

I have not been able to get around to fixing this yet, but I would happily review a PR :)

**Comment by tanchao90** [comment]
> > @christopherfujino thank you for the link, but is this issue will be fixed in the next update ?
> 
> I have not been able to get around to fixing this yet, but I would happily review a PR :)

So when is it expected to be fixed?

**Comment by christopherfujino** [comment]
> So when is it expected to be fixed?

@tanchao Is this blocking your workflow? As far as I can tell, this is an annoyance, and it should be fixed, but is non-critical because the plugins are still functioning (if anyone is having problems actually using the plugins, this would be much more serious and we should file this separately).

**Comment by tanchao90** [comment]
> > So when is it expected to be fixed?
> 
> @tanchao Is this blocking your workflow? As far as I can tell, this is an annoyance, and it should be fixed, but is non-critical because the plugins are still functioning (if anyone is having problems actually using the plugins, this would be much more serious and we should file this separately).

No, not block. I have solved the problem by the solution that @brachior shared.

**Comment by Qwevo** [comment]
@tanchao90 can you point out the comment where @brachior  share his solution, please !

**Comment by amorenew** [comment]
I think it same issue
https://github.com/flutter/flutter/issues/36414

**Comment by tanchao90** [comment]
> @tanchao90 can you point out the comment where @brachior share his solution, please !

Here：https://github.com/flutter/flutter/issues/54867#issuecomment-623006370

**Comment by ericchuawc** [comment]
> Jetbrains changes the plugins directory since the 2020.x versions ([2019](https://www.jetbrains.com/help/idea/2019.3/tuning-the-ide.html#plugins-directory) - [2020](https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory))
> 
> * Windows:
>   
>   * from: `%HOMEPATH%\\.<product><version>\config\plugins`
>   * to: `%APPDATA%\JetBrains\<product><version>\plugins`
> * MacOS:
>   
>   * from: `~/Library/Application Support/<product><version>`
>   * to: `~/Library/Application Support/JetBrains/<product><version>/plugins`
> * Linux:
>   
>   * from: `~/.<product><version>/config/plugins`
>   * to: `~/.local/share/JetBrains/<product><version>`
> 
> To fix the problem before a flutter update, I just created a symbolic link of my plugins directory:
> 
> ```shell
> ln -s /Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2020.1/plugins /Users/xxx/Library/Application\ Support/IntelliJIdea2020.1
> ```
> 
> ```shell
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
>     • IntelliJ at /Users/xxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
>     • Flutter plugin version 45.1.3
>     • Dart plugin version 201.7223.43
> ```
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L918

this one works, savior :)

**Comment by christopherfujino** [comment]
This was fixed in master by https://github.com/flutter/flutter/pull/57963.

**Comment by andreobueno** [comment]
Thank you @brachior !!! It did the trick for me as well :)

**Comment by alsedev** [comment]
> > So when is it expected to be fixed?
> 
> @tanchao Is this blocking your workflow? As far as I can tell, this is an annoyance, and it should be fixed, but is non-critical because the plugins are still functioning (if anyone is having problems actually using the plugins, this would be much more serious and we should file this separately).

Hello @christopherfujino, in 2020.1.2 version of IntelliJ IDEA (Installed using Toolbox from JetBrains) the Flutter Plugin doesn't works as it should be in the "Flutter device selection" selector.  Some times it only shows a device icon, and only shows Simulator (no more), some times shows "Loading..." and shows Simulator and list Android Emulators options, and some times (less than the others) it works fine.  I have 2 real devices connected (iPhone 7 & Samsung Tablet) and Simulator opened and Emulator opened.  flutter devices command on terminal works fine, problems appears only on IntelliJ IDEA.

Reboot computer, uninstall & reinstall IntelliJ + Flutter Plugin is not working.
![Screen Shot 2020-06-11 at 10 28 00 AM](https://user-images.githubusercontent.com/53921739/84406083-a77fba80-abce-11ea-98b5-761db8e7d37d.png)

Note, I am on MacOS Catalina 10.15.5 on a MacBook Air, flutter master channel.

```
flutter --version
Flutter 1.20.0-1.0.pre.19 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 49dc9b1227 (71 minutes ago) • 2020-06-11 16:05:18 +0200
Engine • revision 965fbbed17
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

```
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on May 31, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Non-Bundled Plugins: org.jetbrains.kotlin, Dart, io.flutter
```

```
flutter devices
6 connected devices:

SM T113NU  • xxxxxxxxxxxxxxxxxxxxxxxxxxxx                         • android-arm    • Android
4.4.4 (API 19)
iPhone7       • xxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios            • iOS
13.5
iPhone 11  • 76F86870-719D-4327-9307-8A3FAD7D15F2     • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
macOS      • macOS                                    • darwin-x64     • Mac OS
X 10.15.5 19F101
Web Server • web-server                               • web-javascript • Flutter
Tools
Chrome     • chrome                                   • web-javascript • Google
Chrome 83.0.4103.97

``` 

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.19, on Mac OS X 10.15.5 19F101,
    locale en-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (6 available)

• No issues found!
```

**Comment by alsedev** [comment]
Problem still appears... I found a workaround: **delete .idea folder before** open the project with IntelliJ IDEA CE 2020.1.2.  I someone have same behavior with **"Flutter Device Selection"**.

**Comment by bruno-ortizgb** [comment]
> Jetbrains changes the plugins directory since the 2020.x versions ([2019](https://www.jetbrains.com/help/idea/2019.3/tuning-the-ide.html#plugins-directory) - [2020](https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory))
> 
> * Windows:
>   
>   * from: `%HOMEPATH%\\.<product><version>\config\plugins`
>   * to: `%APPDATA%\JetBrains\<product><version>\plugins`
> * MacOS:
>   
>   * from: `~/Library/Application Support/<product><version>`
>   * to: `~/Library/Application Support/JetBrains/<product><version>/plugins`
> * Linux:
>   
>   * from: `~/.<product><version>/config/plugins`
>   * to: `~/.local/share/JetBrains/<product><version>`
> 
> To fix the problem before a flutter update, I just created a symbolic link of my plugins directory:
> 
> ```shell
> ln -s /Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2020.1/plugins /Users/xxx/Library/Application\ Support/IntelliJIdea2020.1
> ```
> 
> ```shell
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
>     • IntelliJ at /Users/xxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
>     • Flutter plugin version 45.1.3
>     • Dart plugin version 201.7223.43
> ```
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L918

Apparently this workaround doesn't work for windows, i tried to create a Symlink using "mklink" but  flutter doctor would still not find my Intellij intallation. I tried with dev and master channels with no luck.  Any ideas?

**Comment by christopherfujino** [comment]
> > Jetbrains changes the plugins directory since the 2020.x versions ([2019](https://www.jetbrains.com/help/idea/2019.3/tuning-the-ide.html#plugins-directory) - [2020](https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory))
> > 
> > * Windows:
> >   
> >   * from: `%HOMEPATH%\\.<product><version>\config\plugins`
> >   * to: `%APPDATA%\JetBrains\<product><version>\plugins`
> > * MacOS:
> >   
> >   * from: `~/Library/Application Support/<product><version>`
> >   * to: `~/Library/Application Support/JetBrains/<product><version>/plugins`
> > * Linux:
> >   
> >   * from: `~/.<product><version>/config/plugins`
> >   * to: `~/.local/share/JetBrains/<product><version>`
> > 
> > To fix the problem before a flutter update, I just created a symbolic link of my plugins directory:
> > ```shell
> > ln -s /Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2020.1/plugins /Users/xxx/Library/Application\ Support/IntelliJIdea2020.1
> > ```
> > 
> > 
> > ```shell
> > [✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
> >     • IntelliJ at /Users/xxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
> >     • Flutter plugin version 45.1.3
> >     • Dart plugin version 201.7223.43
> > ```
> > 
> > 
> > https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L918
> 
> Apparently this workaround doesn't work for windows, i tried to create a Symlink using "mklink" but flutter doctor would still not find my Intellij installation. I tried with dev and master channels with no luck. Any ideas?

@bruno-ortizgb  This bug is admittedly annoying, but it should not actually affect the functionality of the Flutter SDK. IntelliJ should know where the plugins are located, and the flutter tool does not directly use them.

**Comment by jonahwilliams** [comment]
As part of https://github.com/flutter/flutter/issues/61246, we've decided to deprecate and remove the Intellij validators.

There are simply too many flavors/versions of intellij, and they are all on different release schedules. We're going to focus on updating doctor to focus on only actionable errors.

**Comment by skymansandy** [comment]
> The root issue is that the tool does not account for having both Android Studio AND IntelliJ installed (or multiple versions of one or the other for that matter), and will just check the first one it comes across for the plugins.

This worked for me. I also had IntelliJ installed. Installing plugins in there worked like a charm. Thanks!

**Comment by eeezae** [comment]
After execute `ln -s $HOME/Library/Application\ Support/JetBrains/IntelliJIdea2020.3/plugins $HOME/Library/Application\ Support/IntelliJIdea2020.3` still not found flutter or dart plugin.

`flutter doctor -v` returns

```
[!] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/username/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
```
