### ISSUE TITLE
App built twice at startup

### ISSUE THREAD

**Issue by ph55** [flutter/flutter#54866]
Please explain reason behind building app twice at startup.
Even following simple app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(Home());
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('home....');
    return Container();
  }
}
```

Without any state or variables will build twice and produce following output:

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 836ms.
flutter: home....
flutter: home....
```

**Comment by jonahwilliams** [comment]
Flutter does not guarantee `Widget.build` will be called the minimum number of times possible. You should structure your application in a way that assumes build will be called on every frame - anything less is an optimization.
