### ISSUE TITLE
Cannot create new project using Start a new Flutter project 

### ISSUE THREAD

**Issue by muthu-gokul** [flutter/flutter#54861]
After choosing flutter SDK and project location and when clicking finish. android studio stops.. heap space error

**Comment by muthu-gokul** [comment]
Error creating project.
Exhausted heap space, Trying to allocate 6442385440 bytes

**Comment by muthu-gokul** [comment]
Mother fuckers.will you reply or not..Then why the fuck you are telling us to report the issue..No response from your side

**Comment by TahaTesser** [comment]
Hi @muthu-gokul 
can you please provide your `flutter doctor -v` and `flutter create demo -v`? 
Thank you

**Comment by TahaTesser** [comment]
Hi @muthu-gokul 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
