### ISSUE TITLE
`submit-queue` failure details are a non-sequitor

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#54869]
**seen behavior:**
https://github.com/flutter/plugins/pull/2654 is currently failing in the `submit-queue`:
<img width="676" alt="Screen Shot 2020-04-15 at 10 25 53 AM" src="https://user-images.githubusercontent.com/30870216/79368060-acdcc380-7f03-11ea-847d-af63d12e7a4f.png">

If you click [`Details`](https://api.github.com/repos/flutter/plugins/check-suites/599131632/check-runs) for "submit-queue" it says;
```
{
  "message": "If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.",
  "documentation_url": "https://developer.github.com/v3/checks/runs/#list-check-runs-in-a-check-suite"
}
```

**expected behavior:**
I expect the details to state that the tree is red, ideally it would point to the commit that caused the tree to be red.  In this case it was a post-commit change so it's easy to get lost.

**Comment by digiter** [comment]
@fkorotkov Would you mind taking a look?

**Comment by fkorotkov** [comment]
Please create an issue here https://github.com/cirruslabs/gh-submit-queue and I will take a look.

**Comment by gaaclarke** [comment]
move to https://github.com/cirruslabs/gh-submit-queue/issues/6
