### ISSUE TITLE
[cocoon] Handlers using cache failing with: "Bad state: StreamSink is bound to a stream"

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#54863]
This is affecting:

* /api/refresh-chromebot-status
* /api/public/get-branches

Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl._controller (dart:io/io_sink.dart:238:7)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:158:5)
#2      _Socket.add (dart:io-patch/socket_patch.dart:1734:38)
#3      Connection.send (package:dartis/src/client/connection.dart:101:13)
#4      DispatcherBase.send (package:dartis/src/client/dispatcher.dart:29:17)
#5      _ClientDispatcher.dispatch (package:dartis/src/client/client.dart:199:5)
#6      Client.run (package:dartis/src/client/client.dart:171:50)
#7      ModuleBase.execute (package:dartis/src/command/module.dart:57:20)
#8      ModuleBase.run (package:dartis/src/command/module.dart:50:12)
#9      Commands.set (package:dartis/src/command/commands.dart:1195:12)
#10     RedisCacheProvider.set.<anonymous closure> (package:neat_cache/src/providers/redis.dart:149:35)
#11     RedisCacheProvider._withRedis (package:neat_cache/src/providers/redis.dart:115:22)
<asynchronous suspension>
#12     RedisCacheProvider.set (package:neat_cache/src/providers/redis.dart:149:7)
#13     _Entry.set (package:neat_cache/neat_cache.dart:194:30)
#14     CacheService.set (package:cocoon_service/src/service/cache_service.dart:96:26)
#15     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:82:13)
<asynchronous suspension>
#16     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:66:16)
<asynchronous suspension>
#17     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:66:16)
<asynchronous suspension>
#18     Config._getSingleValue (package:cocoon_service/src/datastore/cocoon_config.dart:54:47)
#19     Config.githubOAuthToken (package:cocoon_service/src/datastore/cocoon_config.dart:80:42)
#20     Config.createGitHubClient (package:cocoon_service/src/datastore/cocoon_config.dart:335:38)
#21     Config.createGithubService (package:cocoon_service/src/datastore/cocoon_config.dart:380:33)
#22     getBranches (package:cocoon_service/src/foundation/utils.dart:77:52)
#23     Config._getFlutterBranches.<anonymous closure> (package:cocoon_service/src/datastore/cocoon_config.dart:45:23)
#24     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:81:29)
<asynchronous suspension>
#25     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:66:16)
<asynchronous suspension>
#26     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:66:16)
<asynchronous suspension>
#27     Config._getFlutterBranches (package:cocoon_service/src/datastore/cocoon_config.dart:42:47)
#28     Config.flutterBranches (package:cocoon_service/src/datastore/cocoon_config.dart:76:47)
#29     RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:59:48)
<asynchronous suspension>
#30     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#36     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _runZoned (dart:async/zone.dart:1518:10)
#40     runZoned (dart:async/zone.dart:1465:12)
#41     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)
<asynchronous suspension>
#42     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:83:23)
#43     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#44     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#45     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#46     _rootRun (dart:async/zone.dart:1126:13)
#47     _CustomZone.run (dart:async/zone.dart:1023:19)
#48     _runZoned (dart:async/zone.dart:1518:10)
#49     runZoned (dart:async/zone.dart:1502:12)
#50     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#51     fork (package:gcloud/service_scope.dart:104:30)
#52     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#53     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#59     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#60     _StreamController._add (dart:async/stream_controller.dart:642:7)
#61     _StreamController.add (dart:async/stream_controller.dart:588:5)
#62     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#63     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#64     _rootRunUnary (dart:async/zone.dart:1134:38)
#65     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#69     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#70     _StreamController._add (dart:async/stream_controller.dart:642:7)
#71     _StreamController.add (dart:async/stream_controller.dart:588:5)
#72     _HttpParser._headersEnd (dart:_http/http_parser.dart:374:19)
#73     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#74     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#75     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#76     _rootRunUnary (dart:async/zone.dart:1134:38)
#77     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#78     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#79     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#80     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#81     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#82     _StreamController._add (dart:async/stream_controller.dart:642:7)
#83     _StreamController.add (dart:async/stream_controller.dart:588:5)
#84     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)
#85     _rootRunUnary (dart:async/zone.dart:1138:13)
#86     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#87     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#88     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#89     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#90     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#91     _StreamController._add (dart:async/stream_controller.dart:642:7)
#92     _StreamController.add (dart:async/stream_controller.dart:588:5)
#93     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#94     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#95     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#96     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#97     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#98     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by keyonghan** [comment]
This is a reproduce of https://github.com/flutter/flutter/issues/43762.
