### ISSUE TITLE
Switch Linux tooling from using GLFW to GTK

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#54860]
Once it's ready, we will flip over from GLFW to GTK, as we did for Windows. The tasks here are:
- [x] Burn down https://github.com/flutter/flutter/projects/142 so we have parity. (We don't necessarily need to hit zero on that list; some things there, like the resource context, aren't critical in the short term.)
- [x] Start uploading the GTK library (can be done in parallel; I'll do that shortly).
- [x] Make an initial Runner template that we're reasonably happy with (doesn't need to be stabilized; we can continue to iterate as we currently do with GLFW).
- [x] Update `flutter_tool` to download/install the new library.
- [x] Add the necessary requirements to the flutter/plugins Linux desktop Dockerfile so the switch doesn't break the builds there.
- [x] Update `flutter_tool` to use the new template.
- [x] Stop uploading the GLFW library.

/cc @robert-ancell

**Comment by stuartmorgan** [comment]
@robert-ancell From discussion today: the plugin template that needs to be ported is [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin/linux.tmpl/projectName_plugin.cc.tmpl). Rather than file a new bug, if you want to just drop the replacement for the method handler (what is currently lines 60-65) here as a comment, I can use that. All the boilerplate around it, the header, etc. I can trivially move over from an FDE plugin.

**Comment by robert-ancell** [comment]
@stuartmorgan do you mean this?

```c
struct utsname uname_data = {};
uname(&uname_data);
g_autofree gchar *version = g_strdup_printf("Linux %s", uname_data.version);
g_autoptr(FlValue) result = fl_value_new_string(version);
response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
```

**Comment by stuartmorgan** [comment]
All but recipe cleanup has landed; working on that now.

**Comment by stuartmorgan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/3741
