### ISSUE TITLE
Allow controls to remain focusable while in disabled state

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#54877]
Internal: b/154410718

For desktop platforms (including Web), it makes sense to exclude disabled controls from directional focus.

However, if directional keys are your main form of input, this leads to confusing situations. For example, if a button gets disabled when you activate it, focus will jump to a different control.

Having a parameter to allow focusable controls to maintain focus while in a disabled state would solve this.

cc @gspencergoog @HansMuller

**Comment by gspencergoog** [comment]
Actually, after discussing it with @goderbauer, I think I'm going to try and implement an InheritedWidget that sets the navigation mode for a subtree (much like Directionality does), as he suggested. Then we can use that to determine how to interpret arrow/DPAD keys differently in cases where the navigation mode is DPAD-based. I'll then use that as the switch instead of putting it in ThemeData.

**Comment by Hixie** [comment]
@gspencergoog What's the status of this one? Did we decide to add `tv` as a new target platform, or add properties to the relevant widgets, or...?

**Comment by gspencergoog** [comment]
@Hixie we are still in the process of deciding. Yesterday I sent Tim and Chris a message about it (and cc'd you).

**Comment by Hixie** [comment]
@gspencergoog Any updates?

**Comment by gspencergoog** [comment]
Yes, we've decided to support these directional navigation modes in Flutter.

I [have a PR](https://github.com/flutter/flutter/pull/54919) to implement this through a `MediaQueryData` attribute that can be set from the platform if the platform is a TV platform. We don't yet distinguish TV platforms, so for now users of this navigation mode will override it in their app with a `MediaQuery` widget.

I still need to get more information from the Material Design team about how this will affect some controls (slider, text fields), and whether or not a completely new widget state is needed or not (focused disabled), and what the colors/opacities for all controls would be in that state if so.
