### ISSUE TITLE
[dashboard] Ability to retry luci tasks from flutter-dashboard

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#54873]
This is an improvement over the general process that will minimize human errors when manually submitting code.

This will also be required for:

* Improvements on flutter repository security that will be implemented over the year.
* Branching and release processes.
* Migration of device lab to luci.
* Migration of engine and sdk to luci.

**Comment by godofredoc** [comment]
Keyong please add pointers to the files that need to be changed.

**Comment by keyonghan** [comment]
A new API is needed here to post check run for a given SHA.

**Comment by godofredoc** [comment]
We can refactor scheduleLuci and _buildsForRepositoryAndPr to luci.dart service class:

https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/github_webhook.dart#L234
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/github_webhook.dart#L186

I would also suggest to reuse reset_devicelab_task:
 https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/reset_devicelab_task.dart

We can rename it as reset_task  and if task is a luci task the use luci.dart service to retrigger the task. This way we can keep all the retry logic in a single handler and only enable the retry link for luci tasks.

**Comment by christopherfujino** [comment]
Will this include support for engine builds? @keyonghan

**Comment by godofredoc** [comment]
This will be implemented directly in the flutter dashboard. The workflow that will apply to all the supported repos will allow retries directly from the github ui. I'll open a different bug for that.

**Comment by christopherfujino** [comment]
> This will be implemented directly in the flutter dashboard. The workflow that will apply to all the supported repos will allow retries directly from the github ui. I'll open a different bug for that.

Thanks
