### ISSUE TITLE
Upgrade devicelab to Xcode 11.5

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54889]
Xcode 11.5 was released May 20.  Upgrade devicelab macs to newest version.
Do NOT upgrade the LUCI builders (need to stay on lowest supported for bitcode generation)

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/pull/54887 and https://flutter.dev/docs/development/ios-project-migration for examples of slightly different Xcode 11.4 behavior.

**Comment by jmagman** [comment]
\cc @digiter @keyonghan

**Comment by jmagman** [comment]
Changed to track Xcode 11.5, which requires macOS Catalina 10.15.2.

**Comment by ditman** [comment]
This is required to build versions of GoogleMaps pod 3.10+, and [for this cleanup ticket](https://github.com/flutter/flutter/issues/63530).

**Comment by godofredoc** [comment]
This is done, now devicelab and framework are using xcode 14.3
