### ISSUE TITLE
Always use the demo home page at the beginning

### ISSUE THREAD

**Issue by Blake4794** [flutter/flutter#54890]
Hey,

always when I run my Application it shows the Demo home page. After I do the Hot Reload is everything fine. 
The Issue is when I try to debug my App, I just can analyze the first screen, I guess. And the first screen is the Demo Home page. 

Another point is, I work with some students together and there worked everthing fine. I think I have maybe a problem with my Windows or IDE?

Operating system: WIN 10 Professional
IDE: Visual Studio Code

Hope you can help me.

Cheers
Thorleif

**Comment by Blake4794** [comment]
Hey there,

I found an solution by my self. I think my Issue was that I had the old Demo Homepage still in Cache and always when I run my Flutter App it still opens the old App. 
My Solution was to clean (Flutter clean) my whole Flutter Project and I think I cleared my cache too. 

I hope I can help other people.

Cheers
Thorleif

**Comment by TahaTesser** [comment]
Hi @Blake4794 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
