### ISSUE TITLE
[cocoon] We should rename the `devicelab` stage to `devicelab_android`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#54895]
When creating a new iOS devicelab test, it is easy to copy an android test and leave the stage as `devicelab` and assume it is correct (when the proper stage would be `devicelab_ios`). Here is [an example](https://github.com/flutter/flutter/pull/54893) of this mistake, but it happens often with new devicelab tests, I'm pretty sure I ran into this. To make it easier to write new devicelab tests, we should rename this stage from `devicelab` to `devicelab_android`.

Or better yet, re-think the entire `stage` + `required_agent_capabilities` settings, as it is confusing.

**Comment by godofredoc** [comment]
not sure what the stage was being used for, but seems like is not being used anymore in the luci devicelab. Should we close this bug?

**Comment by christopherfujino** [comment]
Yep, I'll close this as manifest.yaml is deprecated.
