### ISSUE TITLE
Why Flutter uses Dart?

### ISSUE THREAD

**Issue by MoaathJO** [flutter/flutter#54907]
Hi there,

Anyone knows why Google takes Dart in place to be the language used in Flutter?

I am new to Flutter and wondering about Dart being **single threaded Architecture**!!
i recently faced an issue regarding the threading related things and finding the "Compute" ,"Isolation", "Futures"  something not straight forward or little tricky, not like Java Multi-threading ...etc.

one big point that Flutter is awesome and powerful in creating cross-platform apps with unified UI. focusing in its own powered framework libraries that expands the experience to create animations.

if you know, please share your knowledge.

**Comment by jonahwilliams** [comment]
This is documented at https://flutter.dev/docs/resources/faq#why-did-flutter-choose-to-use-dart

In general, the issue tracker is for bugs and feature requests. Please keep FAQ and help to the mailing list or other community sites.
