### ISSUE TITLE
Observatory Server fails to Start

### ISSUE THREAD

**Issue by skdutta-ga** [flutter/flutter#54904]
I do not get hot reload feature when running _flutter run_. I see the following error:

[   +1 ms] Waiting for observatory port to be available...
[ +558 ms] D/FlutterActivity( 7833): Using the launch theme as normal theme.
[   +4 ms] D/FlutterActivityAndFragmentDelegate( 7833): Setting up FlutterEngine.
[  +28 ms] D/FlutterActivityAndFragmentDelegate( 7833): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this
FlutterFragment.
[ +546 ms] I/flutter ( 7833): Observatory server failed to start after 1 tries
---------------------------------------------------------

The complete verbose log follows:

Note that I tried this already: https://github.com/flutter/flutter/issues/47024#issuecomment-575526081

[verbose.txt](https://github.com/flutter/flutter/files/4484037/verbose.txt)

**Comment by jonahwilliams** [comment]
Does you application have [internet permission](https://developer.android.com/training/basics/network-ops/connecting)? If not, that would explain why dart is prevented from creating a server.

**Comment by skdutta-ga** [comment]
> Does you application have internet permission? If not, that would explain why dart is prevented from creating a server.

 I added the internet permission in Android/app/src/AndroidManifest.xml but it did not solve the issue.

**Comment by VladyslavBondarenko** [comment]
@skdutta-ga 
could you provide your `flutter doctor -v`?
does it happen with a new project?

**Comment by TahaTesser** [comment]
Hi @skdutta-ga 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
