### ISSUE TITLE
Cannot resolve symbol 'GradleException'. \android\app\build.gradle

### ISSUE THREAD

**Issue by PierreSchmits** [flutter/flutter#54939]
Started new Flutter project in Android Studio and did not change boiler plate code.
Project runs fine in emulator.
Created local GIT depository, selected all files and committed project.
I can explain/solve all errors in Code analysis EXCEPT for this one:

**Error:(11, 15) Cannot resolve symbol 'GradleException' (See image below)**

![Image 1](https://user-images.githubusercontent.com/38578090/79433867-c2480f80-8021-11ea-838a-e42ec1950025.jpg)

Local.properties file (See image below)
![Image 2](https://user-images.githubusercontent.com/38578090/79433877-c6742d00-8021-11ea-9cc8-1923582c22e3.jpg)

Flutter Doctor output (See Image below)
![image 3](https://user-images.githubusercontent.com/38578090/79433927-d2f88580-8021-11ea-8968-a682786a4242.jpg)

The same problem occurs in my customer project as well (same project settings).
I have been breaking my head for some time now but can't figure out what I am doing wrong?

Thanks for your help.

Pierre.

**Comment by VladyslavBondarenko** [comment]
Hi @PierreSchmits 
I'm not sure is it the solution or rather a workaround - https://github.com/flutter/flutter/issues/29608#issuecomment-528243662

**Comment by PierreSchmits** [comment]
Hi Vladyslav, Thank you very much for pointing me in this direction. I followed the process and the error is gone. You are right, it is probably a workaround but for now I will just add it to the project manually and hopefully it will be resolved in the future. Cheers, Pierre.
