### ISSUE TITLE
The Android app cannot load the Flutter control when playing the Release APK ,It's add Flutter existing Android App

### ISSUE THREAD

**Issue by tianzhiguo123** [flutter/flutter#54938]
![WeChat 圖片_20200416162827](https://user-images.githubusercontent.com/44284679/79433158-5ce32700-7fff-11ea-93c9-847967751ada.jpg)
![WeChat 圖片_202004161628271](https://user-images.githubusercontent.com/44284679/79433163-5e145400-7fff-11ea-8d20-add434f26b97.jpg)
It's good in debug mode

**Comment by TahaTesser** [comment]
Hi @tianzhiguo123 
can you please provide your `flutter doctor -v`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by tianzhiguo123** [comment]
> Hi @tianzhiguo123
> can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Thank you !This is a project of our company. Demo can't be reproduced

**Comment by iapicca** [comment]
Hi @tianzhiguo123 
I understand you cannot release the source code,
but could you please provide your `flutter doctor -v`, 
your `pubspec.yaml` and any available crash log
Thank you

**Comment by tianzhiguo123** [comment]
> Hi @tianzhiguo123
> I understand you cannot release the source code,
> but could you please provide your `flutter doctor -v`,
> your `pubspec.yaml` and any available crash log
> Thank you

ok

**Comment by tianzhiguo123** [comment]
> Hi @tianzhiguo123
> I understand you cannot release the source code,
> but could you please provide your `flutter doctor -v`,
> your `pubspec.yaml` and any available crash log
> Thank you

![502737085822963071](https://user-images.githubusercontent.com/44284679/79625409-a8aae300-815b-11ea-995a-b5add930f6ed.jpg)
![捕获](https://user-images.githubusercontent.com/44284679/79625413-ab0d3d00-815b-11ea-81a5-b5917b0f6b17.PNG)

**Comment by TahaTesser** [comment]
Hi @tianzhiguo123 
You need to provide information to better address the issue
Does this happen on emulator too? Did it occur on other physical devices?
Please provide complete `flutter doctor -v` and `flutter run --verbose` reproducing the crash or errors
To better address the issue, please a create separate minimal sample code that causes the issue
Thank you

**Comment by tianzhiguo123** [comment]
> @ tianzhiguo123，您好：
> 您需要提供信息以更好地解决此问题。
> 这是否也在模拟器上发生？它是否发生在其他物理设备上？
> 请提供完整`flutter doctor -v`和`flutter run --verbose`再现崩溃或错误，
> 为了更好地解决这个问题，请大家创建导致问题分开最小的示例代码
> 谢谢

no

**Comment by TahaTesser** [comment]
Hi @tianzhiguo123 
Can you please provide your `pubspec.yaml` from Flutter Module and `build.gradle` from Android folder? More information is needed to better address the issue
Thank you

**Comment by tianzhiguo123** [comment]
> Hi @tianzhiguo123
> Can you please provide your `pubspec.yaml` from Flutter Module and `build.gradle` from Android folder? More information is needed to better address the issue
> Thank you

![502737085822963071](https://user-images.githubusercontent.com/44284679/79727787-8366d200-831f-11ea-9d4e-1637bc87ba19.jpg)
![捕获](https://user-images.githubusercontent.com/44284679/79727794-85309580-831f-11ea-972e-5a50e2352b06.PNG)
only these,friend

**Comment by TahaTesser** [comment]
Hi @tianzhiguo123 
Can you please copy/paste the complete logs here?
Thank you

**Comment by TahaTesser** [comment]
Hi @tianzhiguo123 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
