### ISSUE TITLE
Add Map or other function for converting animationControllerValues

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#54942]
I have an AnimatedIcon that I want to add another animation to. I want to reuse the same controller for both animations, but the second one I want to move at half the speed/iteration. So if the controller's value is at 1.0, I want this animation to be at 0.5. If you imagine an AnimationController  was a Stream<double>, then this would be the equivalent of 
```dart
RotationTransition(
                        turns: animationController.map((double value)=> value /2),
                        child: AnimatedIcon( ....
```
and it would return be the same animationController for the most part, just with modified values.
I know it's a Listenable and not a Stream, so it's a little different, but you get the point.

**Comment by goderbauer** [comment]
You can do this by applying a Tween to the animation. The tween would start at 0.0 and end at 0.5, see also: https://master-api.flutter.dev/flutter/animation/Tween-class.html

**Comment by ThinkDigitalSoftware** [comment]
@goderbauer beautiful, thank you.
