### ISSUE TITLE
Why is programming to an interface not encouraged and/or enforced?

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#54949]
A big pain point when working with, and trying to make sense of the flutter repository is that this arguably basic principle of good software engineering is oftentimes not being applied.

### What do I mean by programming to an interface?

Here are three examples from the dart SDK that adhere to that principle.

[VmService](https://github.com/dart-lang/sdk/blob/master/pkg/vm_service/lib/src/vm_service.dart#L238-L1119)
[AnalysisContext](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/dart/analysis/analysis_context.dart)
[ContextBuilder](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/dart/analysis/context_builder.dart)

These all describe pure interfaces, without **any** implementation details. The benefit of that is not only that changes to implementations aren't breaking changes anymore since the Interface is the only thing that consumers should depend on, but those interfaces also provide a natural place for documentation. This would also clearly separate tests into black-box tests (testing against the interface) and white-box tests (testing the implementation). Also, it should not be understated that interfaces make it a lot easier to understand a new code-base which does increase the productivity of new developers.

Now, here are a few places in the flutter repo that would benefit from this practice in the long run.

[ResidentRunner](https://github.com/flutter/flutter/blob/b8bd09db210d2c6299555643af8db4b8ff3e8d92/packages/flutter_tools/lib/src/resident_runner.dart#L612-L1162)
[Xcode](https://github.com/flutter/flutter/blob/b8bd09db210d2c6299555643af8db4b8ff3e8d92/packages/flutter_tools/lib/src/macos/xcode.dart#L56-L553)
[EmulatorManager](https://github.com/flutter/flutter/blob/b8bd09db210d2c6299555643af8db4b8ff3e8d92/packages/flutter_tools/lib/src/emulator.dart#L21-L206)
[DeviceManager](https://github.com/flutter/flutter/blob/b8bd09db210d2c6299555643af8db4b8ff3e8d92/packages/flutter_tools/lib/src/device.dart#L67-L250)
(and many more: Device, Doctor, ProtocolDiscovery)

All the benefits described above also hold true here.

A concrete example and beneficiary of that would be ColdRunner/HotRunner. They both inherit from ResidentRunner and are very hard to reason about. Splitting ResidentRunner into an interface and a helper object/mixin would be a clear improvement and facilitate long-term maintenance.

### What do I expect to achieve with this issue?

1. I would very much like to see changes like these being implemented sometime in the future.
2. Not all contributors are aware of this technique. I've observed classes that started out as an interface but were then 'concretized' by some change that added an implementation detail to it. Contributors should be encouraged to prefer interfaces and concrete implementations for behavior-rich classes.

@jonahwilliams could you perhaps comment on that, do you disagree?

**Comment by jonahwilliams** [comment]
I don't disagree with updating many of these interfaces, but in practice we've found that trickier than you might think. For example, refactoring the resident runner was previously backed up on getting better tests written to prevent regressions. The better testing is currently backed up on swapping out the current vm_service implementation with the more testable `package:vm_service`.

In terms of refactoring, we're currently focused on removing the usage of Zone injected global variables: https://github.com/flutter/flutter/issues/47161 .
