### ISSUE TITLE
Web app freeze on startup on mobile OS

### ISSUE THREAD

**Issue by NickNevzorov** [flutter/flutter#54957]
When mobile app with scrollling start up on mobile device, it freezed on several seconds. For example:
1. App run
2. App show content
3. Scrolling will working after 3 seconds ago (On my Samsung S9)

On Iphone 8 (ios 13) app waiting about 2 minutes

Test on my Samsung s9 and s10. On Desktop Chrome working fine

Sample app: webshop.vsroup.ua/test/

Code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<Widget> result = [];

    for (int i = 0; i < 1; i++) {
      List<Widget> ps = [];
      for (int k = 0; k < 10; k++) {
        ps.add(Container(
            padding: EdgeInsets.all(8.0),
            child: Column(children: [
              Icon(Icons.file_download),
              Image.network("http://webshop.vsgroup.ua/assets/images/s9000.jpg"),
            ])));
      }

      result.addAll(ps);
    }

    return Scaffold(
        body: Container(
            padding: EdgeInsets.all(0.0),
            child: SingleChildScrollView(
                child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: result,
            ))));
  }
}

```

Issure are on all branches

> C:\Flutter\flutter_scrollimages>flutter doctor -v
> [√] Flutter (Channel dev, v1.18.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
> • Flutter version 1.18.0 at d:\android\flutter
> • Framework revision 8f7327f (5 days ago), 2020-04-06 22:11:01 -0400
> • Engine revision 49891e0653
> • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at d:\android\sdk
> • Platform android-29, build-tools 29.0.3
> • ANDROID_HOME = d:\android\sdk
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
> • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] Connected device (2 available)
> • Chrome • chrome • web-javascript • Google Chrome 80.0.3987.163
> • Web Server • web-server • web-javascript • Flutter Tools
> 
> • No issues found!

**Comment by TahaTesser** [comment]
Hi @NickNevzorov 

Testing your code sample on latest `dev` channel, found no issues with performance on iOS 13

Dev -> https://admiring-swanson-0b1dab.netlify.app/#/

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (4 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

Please upgrade by executing `fluter upgrade` and `flutter doctor -v` and trying running it
Thank you

**Comment by NickNevzorov** [comment]
Sorry, i was wrong. Always updated before the test, but then I forgot.

On last dev channel there no freeze on Android, please close an issure

Thank you for support!
