### ISSUE TITLE
Why require NSAllowsArbitraryLoads in video_player plugin?

### ISSUE THREAD

**Issue by sj1914** [flutter/flutter#54955]
I come from an iOS background and I'm a bit confused by this documentation in the video_player plugin:

<img width="750" alt="Screenshot 2020-04-16 at 14 19 52" src="https://user-images.githubusercontent.com/15637846/79460911-5fd51c00-7fed-11ea-9078-d228c85ebb9e.png">

I've only ever used this in development and never in production due to its security risks as per [apples guidelines](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads):

> Use this key with caution because it significantly reduces the security of your app. 

So I'm unsure why its required for use of this plugin and with no clear explanation as to why. It is unclear whether this is necessary for ALL links or just http ones but if the latter i think this should be made clearer in the docs as this is a worrying thing to be suggesting people do in production apps in my opinion. I am dubious to begin integrating this in to my app without knowing whether this is a dead set requirement or not! 

Thanks in advance!

**Comment by TahaTesser** [comment]
This could be commented, labelled as such
