### ISSUE TITLE
CocoaPods not installed or not in valid state

### ISSUE THREAD

**Issue by medlmd** [flutter/flutter#54962]
Hello I get this problem when I try to launch my app on android studio (on Mac ):

```
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
To re-install:
  sudo gem install cocoapods

Exception: CocoaPods not installed or not in valid state.
```

flutter doctor       
```
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-5.0.pre.89, on Mac OS X 10.15.4 19E287, locale en-TN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
```

**Comment by VladyslavBondarenko** [comment]
Hi @medlmd 
does the proposed command `sudo gem install cocoapods` help?

**Comment by medlmd** [comment]
i have tried it but i get the some problem

**Comment by dheeraj2dj** [comment]
`sudo gem install cocoapods` this worked for me. Although there were some issues (suggestions came up). Ran the following additionally (in same order):
- `sudo gem pristine ffi --version 1.12.2`
- `sudo gem pristine executable-hooks --version 1.6.0`
- `sudo gem pristine gem-wrappers --version 1.4.0`
- `sudo gem regenerate_binstubs`
- `sudo gem pristine --binstubs`

Hope this helps!

**Comment by VladyslavBondarenko** [comment]
@medlmd 
could you check workarounds from https://github.com/flutter/flutter/issues/14293?

**Comment by medlmd** [comment]
> `sudo gem install cocoapods` this worked for me. Although there were some issues (suggestions came up). Ran the following additionally (in same order):
> 
> * `sudo gem pristine ffi --version 1.12.2`
> * `sudo gem pristine executable-hooks --version 1.6.0`
> * `sudo gem pristine gem-wrappers --version 1.4.0`
> * `sudo gem regenerate_binstubs`
> * `sudo gem pristine --binstubs`
> 
> Hope this helps!
Hello, I get this
sudo gem pristine executable-hooks --version 1.6.0
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["executable-hooks"] = 1.6.0

**Comment by VladyslavBondarenko** [comment]
@medlmd 
doesn't it help https://github.com/flutter/flutter/issues/41291#issuecomment-535117317? 
(you can try with 1.9.0 version)

**Comment by medlmd** [comment]
the some probleme ☹️

**Comment by TahaTesser** [comment]
Hi @medlmd 
Does it happen after updating to newer master or Is it a fresh install?

**Comment by jmagman** [comment]
```
Woah! You appear to be trying to run flutter as root.
We strongly recommend running the flutter tool without superuser privileges.
```

If CocoaPods `pod` is set up on your path as your user, and you're running as root, it's probably not on your root `PATH`.  As the warning says, don't `sudo flutter`.

See [CocoaPods installation instructions](https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation).

1. Do you see the issue when you run `flutter doctor -v` without `sudo`?
2. What's the output of `gem list pod` without `sudo`?

**Comment by jrnelson333** [comment]
Same issue. I upgraded to the latest stable version, I then ran the app in debug mode on a physical device (no issues), ran the app in release mode of a physical device (no issues), and then attempted to run the app in debug mode on an iOS simulator.

**Comment by jmagman** [comment]
@jrnelson333 Can we get logs with the verbose `-v` flag?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by oakmad** [comment]
I'm encountering the same issue, with debug not running on the iOS simulator when flutter doctor checks out OK. If I find a solution I will post it here.

Error when running debug: 
`Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.`

Doctor output:
`▶ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-US)
    • Flutter version 1.17.1 at /Users/xxx/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Nokia 2 2     • xxxxxxx                  • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro • xxxxxx • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!`

**Comment by edgarfroes** [comment]
Just did what the @oakmad said above and it worked. In my case, it was the Dart plugin for VS Code that was awaiting for a restart to update, so I had to close and reopen VS Code, got the "Dart Code has been updated to 'xxx'" and I was able to debug on my device properly.

**Comment by zentby** [comment]
Very weird. It even complains after I upgraded the cocoapods:
![image](https://user-images.githubusercontent.com/4077259/83213911-760ef400-a1b7-11ea-885a-080abe2048cd.png)

**Comment by zentby** [comment]
it turns out that my path has the wrong version of gems.
![image](https://user-images.githubusercontent.com/4077259/83214478-c89ce000-a1b8-11ea-9bf5-a33be4b95f3e.png)
It was pointing to the 2.6.0 folder. After I switched to 2.7.0, problem solved.

**Comment by saleem359** [comment]
simples answer is this , actually this solution worked for me to open terminal by going through View -> Terminal -> write this command "sudo gem install cocoapods". and thats it

**Comment by qnub** [comment]
Nothing helps for me. cocoapods already installed, gem in PATH and i still can't run my app and see this error. But all works OK just yesterday! 😭

**Comment by wizlif** [comment]
I got the same issue running on Android Studio
```Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.
Error launching application on iPhone 11 Pro Max.
```

When i ran it directly from the terminal i got no issues, could be an android studio issue for me.

**Comment by gerryau** [comment]
I was able to solve this error by: closing Visual Studio and restarting my computer.

After that it was solved for me

**Comment by ThinkDigitalSoftware** [comment]
I was able to solve this by doing invalidate caches and restart on IntelliJ/ Android Studio

**Comment by ThinkDigitalSoftware** [comment]
> I'm in the exact same situation as @wizlif ...
> 
> @ThinkDigitalSoftware what do you mean by "invalidate caches"? `flutter clean`?

What ide do you use?

**Comment by ncuillery** [comment]
Android Studio

**Comment by ThinkDigitalSoftware** [comment]
@ncuillery 
<img width="423" alt="Screen Shot 2020-08-08 at 10 32 26 PM" src="https://user-images.githubusercontent.com/23037821/89725711-0f803080-d9c7-11ea-8f93-6b2c98e93297.png">

**Comment by bhagn** [comment]
I'm seeing the same issue as @wizlif 

Android Studio is unable to find the cocoapods installation

```
[!] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
```
But when `flutter doctor -v` is run on terminal, everything seems to be fine. 

Invalidate Caches/Restart didn't help.

**Comment by wizlif** [comment]
Try using `flutter run` outside Android Studio.

**Comment by bhagn** [comment]
I was able to get it to work by opening Android Studio directly from the terminal.

```
$ open /Applications/Android\ Studio.app 
```

This time it seemed to pick the `$PATH` variable properly and was able to find the cocoapods installation.

**Comment by gapgag55** [comment]
> @ncuillery
> <img alt="Screen Shot 2020-08-08 at 10 32 26 PM" width="423" src="https://user-images.githubusercontent.com/23037821/89725711-0f803080-d9c7-11ea-8f93-6b2c98e93297.png">

That's worked!

**Comment by netgfx** [comment]
I tried everything in this post but i still get the error:
```
✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale en-GR)
    • Flutter version 1.20.3 at /Users/mixalisdobekidis/SDK/flutter
    • Framework revision 216dee60c0 (6 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • 7L's iPhone (mobile) • 21a54e701c409f46af355cc927962aa6002a8798 • ios • iOS 13.6.1

! Doctor found issues in 2 categories.
```
when trying to compile for iOS I only get the error
```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

Exception: CocoaPods not installed or not in valid state.
```

When I build the App from XCode directly it works fine.

**Comment by shrhawk-entertainer** [comment]
ReInstalling the flutter extension on visual code fixed this

**Comment by AustrisC** [comment]
After longer investigation, I identified **two error-causing points**.

### Firstly,
Changing linker flags in `ios/Runner.xcodeproj/project.pbxproj `.
In Xcode, navigate to `Project Runner` -> `Build Settings` -> `Other Linker Flags` & change all the blob that there with:
```
$(inherited)
-framework
Flutter
```
<img width="857" alt="linker-flags" src="https://user-images.githubusercontent.com/12381652/94800132-d70c3a00-03ec-11eb-9083-8820149b540f.png">

### Secondly,
VS Code entry in my `PATH` variable was incorrect. After changing it accordingly to the documentation [here](https://code.visualstudio.com/docs/setup/mac) he error was no longer present.

**Comment by jmagman** [comment]
@AustrisC I'm sure the CocoaPods installation issue is with the `PATH`, not a missing linker flag.

You shouldn't need to add that flag manually, it's being inherited from Generated.xcconfig.
```
OTHER_LDFLAGS=$(inherited) -framework Flutter
```
Can you file a separate issue about that, completely fill out the template, and include your `ios/Runner.xcodeproj/project.pbxproj`? (unless you already know how your project was corrupted.

**Comment by jerryzhoujw** [comment]
reinstall `code` to `path` for vscode, fixed for me: [ref](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)

> Open the Command Palette (⇧⌘P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.
