### ISSUE TITLE
FlutterView  need support hot reload

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#5496]

**Comment by abarth** [comment]
We'll probably need to discover the flutter view so we can connect to observatory.

/cc @johnmccutchan @jason-simmons

**Comment by johnmccutchan** [comment]
I have been fleshing out the service protocol support for FlutterViews. Once we have the connection to the service protocol we can enumerate FlutterViews (on iOS and Android) and hot restart / reload applications within views. 

I don't think I have most of the context for this issue though.

**Comment by eseidelGoogle** [comment]
I'm pretty sure this works now, no?

**Comment by eseidelGoogle** [comment]
Speculatively closing.  If we don't have this, we'll definitely need it once we move off of SkyApplication/SkyActivity: https://github.com/flutter/flutter/issues/5489
