### ISSUE TITLE
[webview_flutter] loading URL with Authorization header

### ISSUE THREAD

**Issue by RauschDev** [flutter/flutter#54960]
I have a problem with my Flutter app.

I have a custom login-form. After login I make a login request (http.post username & password) and receive a JWT token. This works fine.

Now I would like to give the token to the webview as a header parameter (Header Authorization: Bearer $jwt). If this header is given, the server checks if the JWT token is valid, then responds with a 302 redirect to the user-backend, so the user is now logged in.

Unfortunately, the 302 redirect is not running. Everything works wonderfully in a normal browser. But not in the webview. Are there problems with 302 redirects in webviews? How can I solve the problem?

I'm testing with iOS. 

Dependencies in pubspec.yaml:
```yaml
dependencies:
  flutter:
      sdk: flutter
  webview_flutter: ^0.3.19+9
  http: ^0.12.0+4
  flutter_secure_storage: ^3.3.1+1
  local_auth: ^0.6.1+3
```

iOS-Settings in Info.plist
```yaml
<key>io.flutter.embedded_views_preview</key>
<true/>
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
  <key>NSAllowsArbitraryLoadsInWebContent</key>
  <true/>
</dict>
```

Webview
```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

const String URL = "https://mytestdomain.com";

class _WebViewState extends State <WebView>{
  final String jwt;
  _WebViewState(this.jwt);
  num _stackToView = 1;

  void _handleLoad(String value) {
    setState(() {
      _stackToView = 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: IndexedStack(
      index: _stackToView,
      children: [
        Column(
          children: <Widget>[
            Expanded(
                child: WebView(
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                Map<String, String> headers = {"Authorization": "Bearer " + jwt};
                webViewController.loadUrl(URL, headers: headers);
              },
              onPageFinished: _handleLoad,
            )),
          ],
        ),
        Container(
          color: Colors.white,
          child: Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ],
    ));
  }
}

class WebView extends StatefulWidget {
  final String jwt;
  WebView(this.jwt);
  
  @override
  createState() => _WebViewState(this.jwt);
}
```

I would really appreciate your help

Yours sincerely,
Marco

**Comment by VladyslavBondarenko** [comment]
It may be an issue not with 302 redirect itself,

<details>
 <summary>tried this code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: WebView(
          initialUrl: 'http://www.socengine.com/',
        ),
      ),
    );
  }
}
```

</details>

where `http://www.socengine.com/` redirects to `https://www.hugedomains.com/domain_profile.cfm?d=socengine&e=com`

**Comment by RauschDev** [comment]
Thank you very much for your quick response!

I made some additional tests now. You're absolutely right. The redirect works correctly. 

I have built something that gives me the current URL every second and the forwarding works. If I do not provide an "Authorization Bearer ..." header, the application will forward me, but to another page, not through the login process and finally to the user backend. In the output I could now see that this redirection is happening.

So the Problem is another than I first thought. The header is apparently not set correctly. 

Is the way I go the right way to set the authorization header in the GET request?

Or am I wrong?

I would be very happy if you could help me with the problem.

Best wishes,
Marco.

**Comment by RauschDev** [comment]
I don't want to be annoying, but the last answer was 2 weeks ago, so I want to address my problem again because I have not found any solution

Isn't there anyone who has a similar problem or who can help me find the right way to open a webpage with an authorization header in webview_flutter?

I would be very happy if you could help me with the problem.

Best wishes,
Marco.

**Comment by lebomb** [comment]
Marco, I also encountered this issue with a different library. The cause was flutter lowercasing the authorization and bearer values. I just answered a similar issue here:  https://stackoverflow.com/questions/59887514/headers-not-being-set-on-http-flutter/61988061#61988061

**Comment by stuartmorgan** [comment]
There's not enough information here for us to investigate; this hadn't been narrowed down to a specific Flutter issue, just that something involving an end-to-end flow with a server that we don't have access to isn't working.

If you can either make this down to a specific issue in Flutter, or can provide a test case that other people can reproduce with, please file a new issue.
