### ISSUE TITLE
build_benchmark_ios second_build_debug_millis benchmark creeping up; likely regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54974]
I'd been watching this benchmark for a couple days; it's now at the point where it's more red than green.

I don't see a good culprit here --- the immediate red benchmarks are all in unrelated things.

<img width="131" alt="Screen Shot 2020-04-16 at 9 23 15 AM" src="https://user-images.githubusercontent.com/1435716/79481118-ed9c1180-7fc3-11ea-8318-c820c26f368c.png">

Maybe it's time for rebaselining?

**Comment by jonahwilliams** [comment]
Rebaselined. Looks like it might have just been baselined too low, as the performance seems to be different across machines
