### ISSUE TITLE
Original shape is visible after applying ImageFilter.blur

### ISSUE THREAD

**Issue by denis-evteev** [flutter/flutter#54977]
After the blurring filter is applied, the original sharp shape of the underlying object (e.g. text) can still be (barely) visible:
![blur-demo](https://user-images.githubusercontent.com/3929460/79483057-63cb6300-801a-11ea-9c2c-1f85cbe818ff.png)

This doesn’t seem to be the case when running app in iOS Simulator or Android emulator — the objects are blurred completely there. On real devices, however, I can see this unexpected effect.

I’ve tested this on an iPhone 7 device running iOS 13.3 and on an Android SDK 23 device, both in debug and release modes.

Here’s the output of `flutter doctor`:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-UK)
    • Flutter version 1.12.13+hotfix.9 at /Users/denis/src/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/denis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 2A23637A-1609-4CD9-BD24-759E7F07CBB9     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.
```

Here’s a code sample I’ve used:
```
import 'dart:ui';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (_, __) => Scaffold(
        body: Stack(
          children: <Widget>[
            Center(child: Text('Test', textScaleFactor: 4.0)),
            BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
              child: Container(color: Colors.black.withOpacity(0.0)),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by iapicca** [comment]
Hi @denis-evteev 
I've just run your code 
with the latest stable with the following results
[physical](https://user-images.githubusercontent.com/45637986/79557315-03d0cd00-80ab-11ea-91b3-8982591f885b.png)
[emulator](https://user-images.githubusercontent.com/45637986/79557226-e00d8700-80aa-11ea-9622-aa412f0b1c97.png)

**Comment by denis-evteev** [comment]
Hi @iapicca 
As I mentioned, the issue seems to be reproducible only on physical devices. I did experience it on an iPhone 7 and on a Samsung Galaxy A5 device.

Here’s yet another screenshot from the former:
![IMG_DFE1565D393B-1](https://user-images.githubusercontent.com/3929460/79559961-557b5680-80af-11ea-83a5-a6d4f2d27425.jpeg)

**Comment by iapicca** [comment]
Hi again @denis-evteev 
you screenshot seems consistent with my results 
from both emulators and physical device linked in my previous post;
what is the source of the image in your original post ?
Thank you

**Comment by denis-evteev** [comment]
No, it is not consistent.

Here’s a 6x scaled part of my screenshot:
![Untitled-1](https://user-images.githubusercontent.com/3929460/79577718-cf223d00-80cd-11ea-8800-8c462d3465b3.png)

And here’s a 6x scaled part of your screenshot from Pixel 3a:
![Untitled-3](https://user-images.githubusercontent.com/3929460/79577759-e3fed080-80cd-11ea-8f5b-5947f2e945e6.png)

I hope that you can see the original sharp text on my screenshot, which is not visible on yours.

Re your question: my original image was simply a cropped screenshot from physical iPhone 7.

**Comment by denis-evteev** [comment]
Looks like the issue has been resolved in the latest stable release.
