### ISSUE TITLE
Cant set fillColor inside textInputDecoration

### ISSUE THREAD

**Issue by dupiesdupreez** [flutter/flutter#54986]
## Steps to Reproduce
Create a textInputDecorration and add a property fillColor: Colors.grey[100];
Will throw an error

![image](https://user-images.githubusercontent.com/6910085/79498364-739e7380-8029-11ea-94ca-331934819e7b.png)

**Expected results:** 

```
  decoration: textInputDecoration.copyWith(
                              hintText: 'Password',
                              labelText: 'Password',
                              prefixIcon: Icon(Icons.lock)),
                          obscureText: true,
                        ),
```
```
const textInputDecoration = InputDecoration(
  filled: true,
  fillColor: Colors.grey[100];
);

```
**Actual results:** 
Fill color throws an error when trying to add in gradient. Only way to fix it is to pass in as a parameter.
```

const textInputDecoration = InputDecoration(
  filled: true,
  fillColor: Colors.grey[100]; <-= Throws error
);
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
@dupiesdupreez 
do you mean `const variables must be initialized with a constant value` error?
`Colors.grey[100]` is not a const value, use `final textInputDecoration = ...`
is it the problem or I misunderstood?

**Comment by dupiesdupreez** [comment]
@VladyslavBondarenko 
I've made a video of the bug to help me explain it. 

Just a summary 
1. I can pass in a fillColor that is a gradient of a color (Colors.green[600])
2. I cannot directly use a gradient inside of my TextInputDecoration.

[Video Explaining the bug ](https://drive.google.com/file/d/1mGFdIKezLD5ysRq3zSsNCcthMQqwWMDZ/view?usp=sharing)

**Comment by VladyslavBondarenko** [comment]
@dupiesdupreez 
use `final textInputDecoration = ...` instead of `const textInputDecoration = ...` in your second file.
Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it
Thank you
