### ISSUE TITLE
Provide an option to update cache or not

### ISSUE THREAD

**Issue by nogipx** [flutter/flutter#54993]
## Use case
I created dockerfile for delivering app to the web. When I enable web feature with run 
`
flutter config --enable-web
`
caching update automatically triggered by that code
```dart
Future<FlutterCommandResult> verifyThenRunCommand(String commandPath) async {
    // Populate the cache. We call this before pub get below so that the
    // sky_engine package is available in the flutter cache for pub to find.
    if (shouldUpdateCache) {
      // First always update universal artifacts, as some of these (e.g.
      // idevice_id on macOS) are required to determine `requiredArtifacts`.
      await globals.cache.updateAll(<DevelopmentArtifact>{DevelopmentArtifact.universal});

      await globals.cache.updateAll(await requiredArtifacts);
    }
```

I suppose that option intended to be because of this getter 
```dart
abstract class FlutterCommand extends Command<void> {
 ...

 bool get shouldRunPub => _usesPubOption && boolArg('pub');

 bool get shouldUpdateCache => true;

 ...
}
```

## Proposal
I suggest to look at this feature because it will really increase deliver docker images to the host which can update cache by itself.

**Comment by nogipx** [comment]
Oh, that is abstract. Then config should override it. So, it seems easy feature

**Comment by jonahwilliams** [comment]
Its already being set to false:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/config.dart#L63

**Comment by nogipx** [comment]
Really is
Okay, then steps to reproduce

Here is my Dockerfile and if run it the Dart SDK will be downloaded
```Dockerfile
FROM ubuntu:20.04 as flutter
RUN echo "Adding flweb user" \
&&  useradd --system --uid 1000 --shell /bin/bash --create-home flweb \
&&  adduser flweb sudo
ENV FLUTTER_HOME=/home/flweb/flutter \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/flweb/flutter/bin:/home/flweb/flutter/bin/cache/dart-sdk/bin
RUN apt-get -qq update && apt-get -qq install -y git curl unzip \
&&  git clone -b master https://github.com/flutter/flutter ${FLUTTER_HOME} \
&&  chown --recursive flweb:flweb ${FLUTTER_HOME}

FROM flutter as base
WORKDIR /home/flweb/src
COPY --chown=flweb . /home/flweb/src
RUN flutter config --enable-web
EXPOSE 8080

FROM base as production-only-web
CMD flutter run -d web-server --release --web-port=8080 --web-hostname 0.0.0.0 --pub

FROM base as develop
CMD flutter run -d web-server --web-port=8080 --pub

```

**Comment by nogipx** [comment]
I'm sure sdk downloaded by trigger config command
(third row from top)

![Screenshot from 2020-04-17 01-26-48](https://user-images.githubusercontent.com/18379005/79512660-8e351480-804a-11ea-9ad0-96c156414192.png)

Is this a bug?

**Comment by jonahwilliams** [comment]
The dart SDK is downloaded by invoking flutter if it isn't present, you need to make sure `bin/cache` is up to date.

**Comment by nogipx** [comment]
Okay, got it
Thank you for quick response
I'm closing issue
