### ISSUE TITLE
type 'String' is not a subtype of type 'int

### ISSUE THREAD

**Issue by djobleymc** [flutter/flutter#54999]
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
//import 'package:fluttershare/models/user.dart';
import 'package:fluttershare/widgets/header.dart';
import 'package:fluttershare/widgets/progress.dart';
//import 'package:fluttershare/widgets/progress.dart';

final usersRef = Firestore.instance.collection('users');

class Timeline extends StatefulWidget {
  @override
  _TimelineState createState() => _TimelineState();
}

class _TimelineState extends State<Timeline> {

 // List <dynamic> users = [];

 

@override
void initState() { 
  
  //getUsers(); 
 // createUser();
  //getUserById();
  super.initState();
  
}

/*
createUser()async{

  await usersRef.document("0000").setData({
    
     "username" : "jeff",
     "postsCount": 0,
     "isAdmin" : false

  });
}
*/

/*
getUsers()async{

  final QuerySnapshot snapshot = await usersRef.getDocuments();
  
  setState(() {
    users = snapshot.documents;
  });

}
*/

/*
  getUserById() async {
    final String id = "0024";
    final DocumentSnapshot doc = await usersRef.document(id).get();
    print(doc.data);
    print(doc.documentID);
    print(doc.exists);
  }
*/

/*
getUsers(){

  usersRef.getDocuments().then((QuerySnapshot snapshot){

  snapshot.documents.forEach((DocumentSnapshot doc){

     print(doc.data);

  });

  });
}*/
  @override
  Widget build(context) {
    return Scaffold(
  
backgroundColor: Colors.white,
    //body: linearProgress(),

      appBar: header(context, isAppTitle: true),

        /*  
      body: FutureBuilder<QuerySnapshot>(
        future: usersRef.getDocuments(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return circularProgress();
          }
          final List<Text> children = snapshot.data.documents
              .map((doc) => Text(doc['username']))
              .toList();
          return Container(
            child: ListView(
              children: children,
            ),
          );
        },
      ),
     */
  
      body: StreamBuilder<QuerySnapshot>(
       // stream: usersRef.snapshots(),
stream: Firestore.instance.collection('users').snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return circularProgress();
          }

/*
          final List<Text> children = snapshot.data.documents
              .map((doc) => Text(doc['username']))
              .toList();
             
          return Container(
            child: ListView(
              children: children,
            ),
          ); */
   return Container(
            
             padding: EdgeInsets.all(32),
             child: Column(
               
              // mainAxisAlignment: MainAxisAlignment.start,
               //crossAxisAlignment: CrossAxisAlignment.center,

               children: <Widget>[

                   new ListView(
                
              children: snapshot.data.documents.map((DocumentSnapshot document){
                return new ListTile(
                  title: new Text(document['username']),
                  //subtitle: new Text(document['postsCount']),
                 
                );
              }).toList(),
            ),

             ],),
              
              );

        },
      ),

    );
  }
}

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
flutter: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#0cb2a):
flutter: A non-null String must be provided to a Text widget.
flutter: 'package:flutter/src/widgets/text.dart':
flutter: Failed assertion: line 285 pos 10: 'data != null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   StreamBuilder<QuerySnapshot>
flutter:   file:///Users/djobleymc/vs%20code/luachat/lib/pages/timeline.dart:109:13
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Text (package:flutter/src/widgets/text.dart:285:10)
flutter: #3      _TimelineState.build.<anonymous closure>.<anonymous closure> (package:fluttershare/pages/timeline.dart:142:30)
flutter: #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
flutter: #5      ListIterable.toList (dart:_internal/iterable.dart:221:19)
flutter: #6      _TimelineState.build.<anonymous closure> (package:fluttershare/pages/timeline.dart:146:18)
flutter: #7      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
flutter: #8      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
flutter: #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
flutter: #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
flutter: #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #21     _invoke (dart:ui/hooks.dart:259:10)
flutter: #22     _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
