### ISSUE TITLE
Flutter desktop  file_chooser  windows  Error

### ISSUE THREAD

**Issue by Slihao** [flutter/flutter#55004]
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: PlatformException(System error, Could not create dialog, -2147221008)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
#4      FileChooserChannelController.show (package:file_chooser/src/channel_controller.dart:149:34)
#5      showOpenPanel (package:file_chooser/src/utilities.dart:42:8)
#6      FileChooserTestWidget.build.<anonymous closure> (package:example_flutter/main.dart:329:23)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:855:36)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
#13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#24     _rootRunUnary (dart:async/zone.dart:1196:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#27     _invoke1 (dart:ui/hooks.dart:275:10)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by stuartmorgan** [comment]
Please don't cross-post bugs. You already filed this as https://github.com/google/flutter-desktop-embedding/issues/717
