### ISSUE TITLE
Text widget shows a wrong behaivor in IE11

### ISSUE THREAD

**Issue by sunslife** [flutter/flutter#55005]
I just want to show listview, it's a very simple listview using ListTitle.
The result is ok in Chrome, Safari, Firefox except in IE11 or Edge.
If you show a long text in Text widget as title or subTitle in ListTitle, and  when you narrow the window of IE11,  and before the width is the larger than or the same as text length, all is ok. But when the width is shorter than text length, title or subTitle will become 2 rows and take a very large space, that is to say, the whole window of IE11 will only show one item of ListView. 

**1、snapshot**
[1](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F01.png)
[2](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F02.png)
[3](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F03.png)
[4](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F04.png)
**2、flutter doctor -v**

```console
> [✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/sun/development/flutter
    • Framework revision d3ed9ec945 (10 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938) 

> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sun/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

> [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

> [✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

> [!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

> [✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

> [✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

```

**3、my code**
(1) article widget

```dart
import 'package:flutter/material.dart';

import 'entity/article.dart';

class ArticlesPage extends StatefulWidget {
  @override
  _ArticlesPageState createState() => _ArticlesPageState();
}

class _ArticlesPageState extends State<ArticlesPage>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  List<Article> articles = [
    Article(title: "00%sRGB屏幕！这款游戏本“等等党”值得期待",
        description: "联想在其官方微博@联想拯救者发布消息，2020款拯救者Y7000/R7000屏幕色彩和亮度表现全面提升，同时官方还表示“将开启游戏本的高色域普及风暴！”",
        picture:"images/01.jpg"),
    Article(title: "买QLC SSD=买垃圾？别冤枉好人！淘汰HDD就靠它了",
        description: "现在舆论都说QLC固态硬盘是垃圾，那么它真的是垃圾吗？今天就和大家讨论一下这个问题，毕竟现在大家都把QLC SSD视为洪水猛兽。",
        picture:"images/02.jpg"),
    Article(title: "曝Android超级恶意软件 重置仍可自动安装",
        description: "一款名为xHelper的Android超级恶意软件正在肆意传播。之所以定级为“超级”，原因在于用户一旦被xHelper感染，即便删除甚至恢复原厂设置，该病毒仍能在被感染的设备上重新安装。",
        picture:"images/03.jpg")
  ];

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      //appBar: AppBar(title: Text('Home'),),
      body: Padding(
        padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 8.0),
        child: ListView.separated(
          itemCount: articles.length,
          separatorBuilder: (context, index) {
            return Divider(
                indent: 8.0,
                endIndent: 8.0,
                thickness: 0.2,
                color: Colors.grey);
          },
          itemBuilder: (context, index) {
            return buildItem1(index);
          },
        ),
      ),
    );
  }

  Widget buildItem1(int index) {
    return ListTile(
        title: Container(
          color: Colors.amberAccent,
          child: Text(
            articles[index].title,
            overflow: TextOverflow.clip,
            style: TextStyle(
                color: index == 0 ? Colors.deepOrange : Colors.black),
          ),
        ),
        leading: Image.network(
          '${articles[index].picture}',
          width: 80,
          height: 60,
        ),
        subtitle: Container(
          color: Colors.black26,
          child: Text(
              articles[index].description,
              //maxLines: 4,
              overflow: TextOverflow.visible,
              textAlign: TextAlign.justify
          ),
        ),
        onTap: () => {}
    );
  }

}

```
(2)Article class
```
class Article {
  String description;
  String picture;
  String title;

  Article(
      {this.description,
        this.picture,
        this.title});

}
```

**4、how to repoduce**
It's easy, just build web application, and visit it using Microsoft IE 11. 
You can see the wrong behaivor the same as you narrow the width of the IE11 window.

**Comment by iapicca** [comment]
Hi @sunslife 
could you please provide the link to the static website you tested in screenshot above
thank you

**Comment by sunslife** [comment]
> Hi @sunslife
> could you please provide the link to the static website you tested in screenshot above
> thank you
> related to #53218

Thanks you for your quick reply!
I have upload the website in [https://sunslife.github.io](https://sunslife.github.io), You can see the result. Hope to hear good news.

**Comment by iapicca** [comment]
Hi again @sunslife 
thank you for the link

**Comment by sunslife** [comment]
I found another problem.  when I use "Web Server(Web)" selected from Android Studio as a web server, and use safari to browse the web app,  and when I narrow the width of the window of safari, all pictures whose links start with "http://localhost" are blinking. I entered the development mode of safari, I saw the response type of those pictures became "Content-Type: text/plain; charset=utf-8", so when I changed the size of safari window, safari reloaded those pictures again and again and made the pictures blinking again and again.

Here is the network info:

> 摘要
> URL: http://localhost:49549/images/02.jpg
> 状态: 304 Not Modified
> 来源: 内存缓存
> 地址: ::1.49549
> 初始化程序: 
> html_image_codec.dart:149
> 
> 请求
> GET /images/02.jpg HTTP/1.1
> Accept: image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5
> Cookie: _ga=GA1.1.685050703.1583800937
> Accept-Encoding: gzip, deflate
> If-None-Match: 2020-04-16T15:17:47.000/Users/sun/Desktop/FlutterDev/flutter_web_04/web/images/02.jpg
> Host: localhost:49549
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
> Accept-Language: zh-cn
> Referer: http://localhost:49549/
> Connection: keep-alive
> 
> 响应
> HTTP/1.1 304 Not Modified
> X-Content-Type-Options: nosniff
> Content-Type: text/plain; charset=utf-8
> Date: Sat, 18 Apr 2020 00:19:02 GMT
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> Content-Length: 0
> Server: dart:io with Shelf
 
The problem _only_ happens in safari browser when I use "Web Server(Web)" as a web server. There are some snapshot:
[13](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F13.png)
[14](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F14.png)
[15: some times you will see ...](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F15.png)
[16: some times you will see ...](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F16.png)

**Comment by sunslife** [comment]
> /cc @mdebbar

What's the meanings of " Goals milestone"? It means they "are worth fixing in the coming years"?
Although Chrome has a larger market share, Microsoft Windows has still an absolutely large market share in PC, that is to say ,  a very large numbers of users are using IE11 /Edge browsers.  If this basic problem cannot be solved as quick as possible, at least with a few months, HOW will we face those customs "in the recent years"? 

So please change the timeline. 

Thanks a lot.

**Comment by sunslife** [comment]
Today, I did more test about  the wrong behaivor of Text widget in Windows_10_LTS_1607 and Windows_10_LTS_1903. **The conclusion is that the wrong behaivor of Text widget appears in IE11of all windows versions**  ,while Edge browser worked well. 
I think there still many people use IE11, and I checked the market share in 2019, it is about 5%. This is a number that cannot be ignored

**Comment by sunslife** [comment]
If It's possible ,please let flutter web app can be run in IE9/10.

**Comment by TahaTesser** [comment]
@yjbanov 

https://trusting-villani-fa0e54.netlify.app/#/

Not able to reproduce this issue, beta, and master, both show a blank page on IE 11, same issue on canvaskit as well 
Is IE 11 still supported?

![image](https://user-images.githubusercontent.com/48603081/92005032-958e5d80-ed60-11ea-88ed-9d76dc4d0814.png)

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.39, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.39 at /Users/tahatesser/Code/flutter_master
    • Framework revision a8281e31af (18 hours ago), 2020-09-01 10:57:59 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPhone 11 (mobile)     • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 85.0.4183.83

• No issues found!


```

</details> 

![image (1)](https://user-images.githubusercontent.com/48603081/92005208-d25a5480-ed60-11ea-9c3e-ecf3a5433998.png)

**Comment by yjbanov** [comment]
IE11 is no longer supported
