### ISSUE TITLE
Cleanup dart:ui shim for web-only APIs in web plugins.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#55000]
Remove the dart:ui shim added in the following PR:

https://github.com/flutter/plugins/pull/3238

Once it [this issue](https://github.com/flutter/flutter/issues/41563) is fixed, and a similar one for `ui.webOnlyAssetManager`, and we port the plugin to the new API.

Affected plugins:

| File | sha1 |
|----|----|
| ./pointer_interceptor/lib/src/shim/dart_ui_fake.dart | 0092b02be711c63c6ffa1aebae5069852bbc235d |
| ./pointer_interceptor/example/lib/src/shim/dart_ui_fake.dart | 1ed1815d69a6987f96518ebeaa9352e88a4fb3fc |
| ./url_launcher/url_launcher_web/lib/src/shims/dart_ui_fake.dart | 687febac4003c469ffe3677dbb557a5c7b58e7ec |
| ./video_player/video_player_web/lib/src/shims/dart_ui_fake.dart<br /> ./google_maps_flutter/google_maps_flutter_web/lib/src/shims/dart_ui_fake.dart<br/> ./camera/camera_web/lib/src/shims/dart_ui_fake.dart <br /> ./webview_flutter/webview_flutter_web/lib/src/shims/dart_ui_fake.dart | 98447e1f42c2da109e05d13b6fdf5921fe11592f |

Updated list May 19th 2023: There's currently 4 variants of the dart_ui_fake.dart shim API with slight modifications that will need to be cleaned up. Fortunately the migration to `dart:web_ui` should be fairly simple once it rolls to `stable`.

**Comment by bselwe** [comment]
camera_web might also need to be ported.

**Comment by ditman** [comment]
Thanks @bselwe! I've added it to the list on top of this issue!

**Comment by ditman** [comment]
A fix for this is finally coming!!

https://github.com/flutter/engine/pull/41877
