### ISSUE TITLE
SEVERE: Flutter Team have even run their web apps in Microsoft browsers such as IE11 or Edge?!

### ISSUE THREAD

**Issue by sunslife** [flutter/flutter#55007]
### **Dear Flutter Team:**

First, Thanks you for your great work!

However, I found some interesting thing and want to ask you : Have you **### seriously** test your samples and make sure your samples can run properly in Microsoft IE11 or Edge?

I just run gallery sample in IE11, what you can do it very easily, Six same Error info showed in console as below:

> 无法找到在源映射 https://flutter.github.io/gallery/main.dart.js.map 中指定的 org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/async_patch.dart。

Please solve it.

Thanks again!

---------------
Another Test _1:  
(1) Result: Even a very simple counter created by AndroidStudio cannot be run correctly in IE11!!!
(2) code modified to show problem more clearly
```
import 'package:flutter/material.dart';
import 'package:flutterweb04/articles.dart';
import 'package:universal_html/prefer_universal/html.dart' as html;

import 'App.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),//ArticlesPage()//
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          color: Colors.amberAccent,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Container(
                color: Colors.blueAccent,
                child: Text(
                  'You have pushed the button this many times:', //**********
                ),
              ),
              Container(
                color: Colors.greenAccent,
                child: Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
(3) repcoduce problem 
The first snapshot from code upper is here:
[10](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F10.png)
You just modify the content in the line with "//**********" as below:
`'You have pushed the button this many times:\n', //**********`
_JUST CHANGE ONE LINE TO TWO LINES!_
You will see that:
[11](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F11.png)

That is to say If we have an article with multiple paragraphs or lines , and customers use IE or Edge to browse it , How can they bear it?!  Because you will see large blocks, not commonly paragraphs, will be showed before them. Let's see the next test below.

---------------
Another Test _2:  
(1) Code:
Just change code slightly, using tow Text widgets to show what happened.

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          color: Colors.amberAccent,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Container(
                color: Colors.blueAccent,
                child: Text(
                  'You have pushed the button this many times:\n',
                ),
              ),
              Container(
                color: Colors.blueAccent,
                child: Text(
                  'You have pushed the button this many times:\n',
                ),
              ),
              Container(
                color: Colors.greenAccent,
                child: Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
```
(2) snapshot:
[12](https://github.com/sunslife/flutter_error/blob/master/%E6%88%AA%E5%B1%8F12.png)

--------
Output from command "Flutter doctor -v" in my Mac:
> [✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/sun/development/flutter
    • Framework revision d3ed9ec945 (10 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938) 

> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sun/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

> [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

> [✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

> [!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

> [✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

> [✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by iapicca** [comment]
Hi @sunslife 
this issue seems related the same problem
you described in this other [issue](https://github.com/flutter/flutter/issues/55005)
please follow up on that issue 

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by sunslife** [comment]
Ok, I just do more test to check flutter web app in IE11. 
The result really surprised me.
