### ISSUE TITLE
Gallery, Buttons: open and close of Buttons misses frames on Nexus 5

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5501]
On a nexus 5: Open Gallery, tap into Buttons. Then tap back.

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17817042/2914c162-65f1-11e6-81ef-c900a996dba0.png)

On a Nexus 5X:

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17817122/acd4ff58-65f1-11e6-9957-c47434b89836.png)

Not sure what's happening here, but may make an interesting test case for us to follow-up on. The perf feel is pretty different on the two different hardwares, but of course, it's two different hardware :)

**Comment by guidezpl** [comment]
Closing as not reproducible. If you disagree, please file an issue at https://github.com/flutter/gallery.
