### ISSUE TITLE
TextField maxLength not working properly when when writing quickly

### ISSUE THREAD

**Issue by mo-ah-dawood** [flutter/flutter#55018]
Flutter version: 1.17.0
Channel: beta
when typing fast in textfield that has maxlength of 10 the last char i type is not ignored
so i got a string of 11  char
this what i did
```dart
TextField(
          maxLength: 10,
          onChanged: (v){
            print(v);
          },
        ),
```
**Expected results:** ignore last char

here is the output
![image](https://user-images.githubusercontent.com/31937782/79540991-5ac5aa80-8089-11ea-817a-c8e175abf26f.png)

**Comment by VladyslavBondarenko** [comment]
Hi @mo-ah-dawood 
with what device are you testing?
I tried with `beta 1.17.0` (with `dev v1.18.0-dev.5.0` and `v1.12.13+hotfix.9` as well) but can't reproduce it with Android 10 (API 29) (emulator) and iOS 13.4 device

**Comment by mo-ah-dawood** [comment]
> Hi @mo-ah-dawood
> with what device are you testing?
> I tried with `beta 1.17.0` (with `dev v1.18.0-dev.5.0` and `v1.12.13+hotfix.9` as well) but can't reproduce it with Android 10 (API 29) (emulator) and iOS 13.4 device

Galaxy a7 (2018)
Android 9

**Comment by mo-ah-dawood** [comment]
This is log from simple app  
![image](https://user-images.githubusercontent.com/31937782/79616428-56d76e00-8105-11ea-9559-ad9139f538e1.png)
```dart
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Material(
        child: Center(
          child: TextField(
            maxLength: 10,
            onChanged: (v) {
              print("\u001b[31m$v");
            },
          ),
        ),
      ),
    );
  }
```

**Comment by VladyslavBondarenko** [comment]
@mo-ah-dawood 
I managed to reproduce it with Redmi Note 7 (Android 9) when typing very fast. Not sure is it android issue or not, but I tried to type the same fast, but couldn't reproduce it with iPhone 7 (iOS 13.4).
Even if I can see the event of typing the 11th symbol, It isn't shown in the TextField.

Also I couldn't reproduce it with current dev channel `1.18.0-dev.5.0`. Can you?

**Comment by mo-ah-dawood** [comment]
yes the 11th symbol not visible but the value it self changed to 11 symbol
this cause some problems  as i see an input  and posting another one to http
this problem also appeared with me in project created with older version of flutter
so i will try to find more info a bout that and reply here if the issue persists with me

**Comment by VladyslavBondarenko** [comment]
I can't reproduce it with current dev `1.19.0-1.0.pre`. 
Seems to be fixed.
@mo-ah-dawood comment please if this is not so and I'll reopen

**Comment by mo-ah-dawood** [comment]
Yes i think it fixed thanks

**Comment by trantan97** [comment]
Another bug:
when i set maxlength = 3,
input something like "12345"
i get "123" but when click delete on keyboard I have to press 5 times
`                    TextField(
                      maxLength: 3,
                      onChanged: (value) {
                        print(value);
                      },
                    )`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

**Comment by JobMoll** [comment]
> when i set maxlength = 3,
> input something like "12345"
> i get "123" but when click delete on keyboard I have to press 5 times
> ` TextField( maxLength: 3, onChanged: (value) { print(value); }, )`
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [√] Android Studio (version 4.0)
> [√] Connected device (1 available)
> 
> • No issues found!

Got the exact same issue here indeed i'm on flutter 1.22.2
