### ISSUE TITLE
[flutter_tools] Add a space between URL and period

### ISSUE THREAD

**Issue by MizukiSonoko** [flutter/flutter#55017]
## Use case
I am developing flutter application. and I face this warning as follows: 

```shell
$ flutter run
 
Launching lib/main.dart on Pixel 4 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on
    https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...                                  
(This is taking an unexpectedly long time.)       ⡿
```
But I think this URL is invalid because it contains `.`.

## Proposal

How about adding a space between URL and period?
https://github.com/flutter/flutter/blob/e092dcfa22cef503cfdceea67e45c49c0aa8062d/packages/flutter_tools/lib/src/android/gradle.dart#L250

https://github.com/flutter/flutter/blob/03c566768b6baf32b5631e212e48cea2f20b0d0d/packages/flutter_tools/test/general.shard/android/gradle_errors_test.dart#L326
and more. 

- Before
```
https://goo.gl/CP92wY.
```
- After 
```
https://goo.gl/CP92wY .
```

Regards

**Comment by TahaTesser** [comment]
Hi @MizukiSonoko 
Does it cause issues when selecting the link?

**Comment by MizukiSonoko** [comment]
Yes
In VSCode,  we can not access this URL by clicking.
I understand  VS Code is an official editor tool on Flutter, so this error is not good

<img src="https://user-images.githubusercontent.com/6281583/79634698-29db9780-81a7-11ea-9876-557b8cb0a997.png" width="300" />

<img src="https://user-images.githubusercontent.com/6281583/79634767-99518700-81a7-11ea-9d24-10edea21cd71.png" width="500" />

**Comment by jonahwilliams** [comment]
Thanks for the bug report @MizukiSonoko , sorry for the delay in getting it fixed
