### ISSUE TITLE
CompositedTransformFollower shows when Target is scrolled out of view

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#55016]
When using CompositedTransformFollower in a list, and scrolling the list upwards, the Follower continues to render as the Target is no longer in the visible bounds:
http://screens.gskinner.com/shawn/2020-04-17_00-29-27.mp4

**Comment by TahaTesser** [comment]
Hi @esDotDev 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by esDotDev** [comment]
I don't have time at the moment, but I can return later. I'm on the very latest master.

_Psuedocode:_
- Column
   -- Container
   -- List
      --- Row w/ CompositedTransformTarget

If the row shows an overlay, and is scrolled behind the Container, the overlay is still shown.

**Comment by TahaTesser** [comment]
Hi @esDotDev 
It would better to have a minimal sample code to better address the issue
Please provide when it when you get time
Thank you

**Comment by goderbauer** [comment]
Setting https://master-api.flutter.dev/flutter/widgets/CompositedTransformFollower/showWhenUnlinked.html to false should fix the problem. Have you tried that?

**Comment by esDotDev** [comment]
I have, it works when the Target leave the viewport, but it doesn't work when the target goes out of bounds in the list (but is still in bounds in the app), like the video shows.

I still intend to get  your a code sample, just swamped at the moment.

**Comment by TahaTesser** [comment]
Hi @esDotDev 
Do you the code sample please?
Thank you

**Comment by esDotDev** [comment]
I will still post a sample, but I posted a literal video guys. At some point you either want to fix bugs or you don't.

**Comment by TahaTesser** [comment]
Hi @esDotDev i
I have tried to create code sample based on your description and video but it's not coming same as your video
In order to exactly reproduce the issue, if you code provide some code sample or point to this class if it exist in official repository, it will be really helpful to us 
Thank you

**Comment by esDotDev** [comment]
Yes, will do, sorry for the delay on this. You can close for now if you want and I can post if/when I can provide a code sample.

**Comment by TahaTesser** [comment]
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
