### ISSUE TITLE
Arrow key navigation in text with surrogate pairs is very broken

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#55014]
The current arrow key handling in the desktop embeddings doesn't handle surrogate pairs, and while trying to fix it I encountered a bunch of weird issues. After some debugging, I figured out that with my local changes the embedding was doing the right thing (hopping two code units when encountering a surrogate pair), but the framework's arrow key processing was not, and sending back offsets in the middle of the pair (due to the ongoing issue of the two sources of truth fighting each other).

Looking at editable.dart, it appears that there's no attempt to handle surrogate pairs, or any other higher level rune-based logic; it's just using hard-coded deltas of 1.

/cc @gspencergoog Did I miss something, or is there really no handling of this? I thought there had been fixes for iOS and Android at some point to avoid things like deleting half of an emoji, but I'm not seeing that in framework code. Maybe it was just for backspace, which the framework doesn't handle?

**Comment by gspencergoog** [comment]
There really is no handling of this.  When I redid the framework editing code, that was one of the things that I was going to fix (it was like that before I started too), but at the time we were in the middle of talking to the Dart team about support for grapheme clusters, so we were going to wait for the outcome of that discussion.  Now we have the Character package, and @justinmc is taking a look at how we can use that. I'm not sure if he's planning on fixing this though: I think the plan was to fix it when we switch to one source of truth.

**Comment by stuartmorgan** [comment]
Okay. I think we should just turn off the single-index arrow key handling in the framework on desktop until then, because the experience right now is pretty bad. I have working code for Windows and Linux already to skip over surrogate pairs ready to go, and macOS should be pretty easy to fix with Cocoa APIs, so that's a fast solution to a better interim state.

**Comment by stuartmorgan** [comment]
Per discussion today, I'll add simple surrogate pair handling (explicitly **not** trying to handle all the complexities of grapheme clusters in general, which is a larger task already in discussion) to arrow keys in the framework for now, rather than disabling it.
