### ISSUE TITLE
[shared_preferences] MissingPluginException

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#55015]
I using workmanager plugin (https://pub.dev/packages/workmanager) in my project. Before that, I need to do platform setup.

For android setup, I follow the upgrade guide instruction(https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

**MainActivity.kt**

```
package com.xxx

import io.flutter.embedding.android.FlutterActivity;

class MainActivity: FlutterActivity() {

}
```

**manifest.xml**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.xxx">

    <uses-permission android:name="android.permission.INTERNET" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application android:label="xxx" android:usesCleartextTraffic="true" android:icon="@mipmap/ic_launcher">

        <meta-data android:name="flutterEmbedding" android:value="2" />

        <activity android:name="io.flutter.embedding.android.FlutterActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>

            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
        </activity>
    </application>
</manifest>
```
But my project stuck at splash screen and here the errors:
`
OUTPUT TERMINAL PROBLEMS 530 DEBUG CONSOLE E/flutter (26453): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Comment by iapicca** [comment]
Hi @tony123S 
if you are using the latest stable you might not need to follow the [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) docs.

I noticed that you open an issue in the package [github](https://github.com/vrtdev/flutter_workmanager/issues/160), that is the correct approach for the issue with said package.

The error you provided points at an issue with [shared_preferences](https://pub.dev/packages/shared_preferences) implementation
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by tony123S** [comment]
Before I use workmanager and upgrade to 1.12, everything works fine. But this issue arise once I upgrade the version in order to use workmanager.

But my app now crashed once the sharedPrefrences get called in splashScreen. (I believe  it is  not related with workmanager in this stage).

**splash_screen**
```

class SplashScreen extends StatefulWidget {
       
  @override
  _SplashScreenState createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();

    Timer(Duration(seconds: 3), () => checkIsLogin());
  }

  Future checkIsLogin() async {
    MySharedPreferences().getUser().then((onValue) {     // call sharedPrefrences
      if (onValue.token == null) {
               .......
      } else {
             ...
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
               ......
  )}
}


```

**Comment by tony123S** [comment]
**Command flutter doctor -v**

> 
> xxx@xxx-Inspiron-14-3467:~/xxxx$ flutter doctor -v
> Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package.
> The repository from which the 'flutter' tool is currently executing will be used instead.
>   running Flutter tool: /home/seng/Desktop/flutter_linux_v1.12.13+hotfix.5-stable/flutter
>   previous reference  : /home/seng/flutter_linux_v1.5.4-hotfix.2-stable.tar (1)/flutter
> This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the
> expected version (run 'flutter --version' to see which flutter is on your path).
> 
> 
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.12.13+hotfix.5 at /home/seng/Desktop/flutter_linux_v1.12.13+hotfix.5-stable/flutter
>     • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> 
>  
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /home/seng/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.37.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.4.1
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> ! Doctor found issues in 1 category.


**flutter run --verbose**

> 
>  +21 ms] <- compile package:xxx/main.dart
> [+3311 ms] E/flutter (29079): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No
> implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> [        ] E/flutter (29079): #0      MySharedPreferences.getUser (package:xxx/repository/model/shared_preferences.dart:39:31)
> [        ] E/flutter (29079): <asynchronous suspension>
> [        ] E/flutter (29079): #1      _SplashScreenState.checkIsLogin (package:xxx/ui/splash_screen.dart:22:27)
> [        ] E/flutter (29079): #2      _SplashScreenState.initState.<anonymous closure> (package:xxx/ui/splash_screen.dart:18:39)
> [        ] E/flutter (29079): #3      _rootRun (dart:async/zone.dart:1122:38)
> [        ] E/flutter (29079): #4      _CustomZone.run (dart:async/zone.dart:1023:19)
> [        ] E/flutter (29079): #5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
> [        ] E/flutter (29079): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
> [        ] E/flutter (29079): #7      _rootRun (dart:async/zone.dart:1126:13)
> [        ] E/flutter (29079): #8      _CustomZone.run (dart:async/zone.dart:1023:19)
> [        ] E/flutter (29079): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
> [        ] E/flutter (29079): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> [        ] E/flutter (29079): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
> [        ] E/flutter (29079): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
> [        ] E/flutter (29079): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> [        ] E/flutter (29079): 
> [+6330 ms] Updating files
> [+1084 ms] DevFS: Sync finished
> [   +2 ms] Syncing files to device Android SDK built for x86... (complete

**Comment by tony123S** [comment]
Flutter version

> 
> Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 27321ebbad (4 months ago) • 2019-12-10 18:15:01 -0800
> Engine • revision 2994f7e1e6
> Tools • Dart 2.7.0

**Comment by tony123S** [comment]
**main.dart**

```
void main() {
  runApp(MyApp());
}

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
            ......
          break;
      }
    } catch (e) {
      print(e.toString());
    }
    return Future.value(true);
  });
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
        providers: globalProviders,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'xxx,
          theme: ThemeData(
            accentIconTheme: const IconThemeData.fallback().copyWith(
              color: Colors.white,
            ),
            primaryTextTheme: TextTheme(title: TextStyle(color: Colors.white)),
            primarySwatch: Colors.orange,
            primaryIconTheme: const IconThemeData.fallback().copyWith(
              color: Colors.white,
            ),
          ),
          localizationsDelegates: [
            const LocalizationDelegate(),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate
          ],
          supportedLocales: [
            const Locale('en', ''),
            const Locale('zh', ''),
          ],
          onGenerateRoute: Router.generateRoute,
          initialRoute: SplashScreen.ROUTE,
        ));
  }
}

```
You can find my splashScreen code above. The error pointed to ` final prefs = await SharedPreferences.getInstance();`

**Comment by iapicca** [comment]
Hi again @tony123S 
could you please run `flutter upgrade --force`
also please provide your `pubspec.yaml`
and your full `flutter run --verbose`
if it's too lengthy you may attach it as txt file
Thank you

**Comment by tony123S** [comment]
I have run flutter upgrade --force.

This is pubspec.yaml

https://pastebin.com/Yc5B0Rku

**Comment by tony123S** [comment]
And this is `flutter run --verbose` .

https://pastebin.com/CNUvfKX6

**Comment by tony123S** [comment]
ok, issue solved after I add `SharedPreferences.setMockInitialValues({});
before  `final prefs = await SharedPreferences.getInstance();`, but I get `MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)` now..I

**Comment by tony123S** [comment]
I have deleted  `MainActivity.kt` and this is `GeneratedPluginRegistrant.java`. 
```
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      io.flutter.plugins.connectivity.ConnectivityPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.connectivity.ConnectivityPlugin"));
      io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      com.bluechilli.flutteruploader.FlutterUploaderPlugin.registerWith(shimPluginRegistry.registrarFor("com.bluechilli.flutteruploader.FlutterUploaderPlugin"));
      com.flutter_webview_plugin.FlutterWebviewPlugin.registerWith(shimPluginRegistry.registrarFor("com.flutter_webview_plugin.FlutterWebviewPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
      io.flutter.plugins.imagepickersaver.ImagePickerSaverPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.imagepickersaver.ImagePickerSaverPlugin"));
    flutterEngine.getPlugins().add(new com.crazecoder.openfile.OpenFilePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
      net.touchcapture.qr.flutterqr.FlutterQrPlugin.registerWith(shimPluginRegistry.registrarFor("net.touchcapture.qr.flutterqr.FlutterQrPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    flutterEngine.getPlugins().add(new be.tramckrijte.workmanager.WorkmanagerPlugin());
  }
}

```

All the plugin are in this file, so what is missing here? :(

**Comment by windows7lake** [comment]
It's fatal isuue, pls fixed it soon, thanks.

**Comment by tony123S** [comment]
@windows7lake 

There are something wrong with the documentation. You can try with this

1. Don't remove your `.MainActivity.kt`, instead remove your `.App` class.

**MainActivity.kt**

```
package your_package_name

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity 
import io.flutter.embedding.engine.FlutterEngine    
import io.flutter.plugins.GeneratedPluginRegistrant 

class MainActivity: FlutterActivity() { 
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {    
        GeneratedPluginRegistrant.registerWith(flutterEngine);  
    }   
}
```

**AndroidManifest.xml**
```

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="your_package_name">

    <uses-permission android:name="android.permission.INTERNET" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application android:label="xxx" android:usesCleartextTraffic="true" android:icon="@mipmap/ic_launcher">
        <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <!-- <meta-data android:name="io.flutter.app.android.SplashScreenUntilFirstFrame" android:value="true" /> -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>

            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />

        </activity>

        <meta-data android:name="flutterEmbedding" android:value="2" />

    </application>
</manifest>
```
**styles.xml**
```

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>

    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
    <item name="android:windowBackground">@drawable/launch_background</item>
</style>
</resources>

```

**Comment by windows7lake** [comment]
@tony123S  Thanks for your methods. But with this way, some plugins will be invoked twicce. And I found that it may caused by `GeneratedPluginRegistrant.registerWith(flutterEngine)`. It seems to have injected the plugin twicce.

**Comment by tony123S** [comment]
How you know it invoked twice?

**Comment by windows7lake** [comment]
> How you know it invoked twice?

I had wrote a own plugin, and the method of plugin will be invoked twice. I only the function one times in my project.

**Comment by night-wielder** [comment]
Still having this problem.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
