### ISSUE TITLE
[PROPOSAL, NAMING CONVENTION] Redundancy in Opacity Widget opacity property

### ISSUE THREAD

**Issue by angelhdz** [flutter/flutter#55020]
## Use case
```dart
Opacity(
  double opacity
)
```

## Proposal
```dart
Opacity(
  double value
)
```

I propose changing the **opacity** property of the Opacity widget to **value** or something better, because it's redundant:

> "The opacity of the Opacity Widget".

I searched in the Issues and in Google but didn't find any discussion about this.

Thank you for the great job!

**Comment by goderbauer** [comment]
Changing this doesn't seem to add any value.

**Comment by angelhdz** [comment]
> Changing this doesn't seem to add any value.

So, avoiding **REDUNDANCY** is not of value for you???

Who was the one who came up with the idea of naming it Opacity(opacity) and Padding(padding)???

You mean Opacity value and Padding value. **Opacity's opacity** and **Padding's padding** is a 
non-sense.
