### ISSUE TITLE
Gallery: App Bar shadows disappear when transitioning between home and components

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5502]
Open Gallery. Scroll up to collapse the app bar. Tap a component (e.g. Cards).

Notice the shadow on the app bar disappears, the transition into cards completes, and then the shadow reappears.

Tested on a Nexus 5 and 5X.

**Comment by sethladd** [comment]
I can make a movie if you like. Please let me know if you don't see this happening.

**Comment by eseidelGoogle** [comment]
iirc @abarth told me this is the same root cause as https://github.com/flutter/flutter/issues/5231 which we just need to reduce for Skia.

**Comment by chinmaygarde** [comment]
Duplicate of https://github.com/flutter/flutter/issues/5231. Raster cache not accounting for the shadow.
