### ISSUE TITLE
unable to run application

### ISSUE THREAD

**Issue by vipul8815** [flutter/flutter#55021]
Compiler message:
../../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:15:9: Error: The superclass,
'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DatePickerTheme({                                               
        ^^^^^^^^^^^^^^^                                                 
                                                                        
Compiler message:                                                       
../../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:15:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DatePickerTheme({                                               
        ^^^^^^^^^^^^^^^                                                 
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/vipul/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/home/vipul/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 53s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        54.6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by atharvaj77** [comment]
Please update Flutter to latest version and try again

**Comment by VladyslavBondarenko** [comment]
Hi @vipul8815 
please follow up on https://github.com/Realank/flutter_datetime_picker/issues/128
Closing as duplicate and as issue with a 3rd party plugin
