### ISSUE TITLE
Bottom navigation bar & state of page

### ISSUE THREAD

**Issue by abaert** [flutter/flutter#55028]
Hi, I have a listView with a bunch of cryptocurrencies. When I click on one cryptocurrency it opens a new page with all the cryptocurrency details. On this page I have an icon that when clicked it add the cryptocurrency to another listView on another page. 
But this doesn't works because when navigating from page to page with my bottom navigation bar, the state of each page is "deleted" so I can't create my new listView. It's probably due to the state of the page ?? 
my code is quite big, if somebody can help me with this I can send the code
Thank you very much,

**Comment by enricobenedos** [comment]
Hi @abaert, can you please provide us a reproducible and simplified sample of your code?
Normally there are two main option to navigate between pages using `BottomNavigationBar`:

- `PageView` widget that doesn't maintain any state when switching between pages
- `IndexedStack` widget that preload all children pages at first startup and maintain them states

Try to use [IndexedStack](https://api.flutter.dev/flutter/widgets/IndexedStack-class.html) and, if I correctly understand your question, you will be able to maintain states when navigating using `BottomNavigationBar`
