### ISSUE TITLE
Android TV RaisedButton focusColor doesn't work correctly with keyboard arrow keys / dpad

### ISSUE THREAD

**Issue by andraskende** [flutter/flutter#55037]
Android TV RaisedButton focusColor doesn't work correctly with keyboard arrow keys / dpad

here is a simple example app, please run on AVD TV simulator  to reproduce the issue..

- keyboard left / right arrow keys works on all items but first item (a) focusColor will not change even though widget is focused...

- after pressing keyboard up / down keys a few times focusColor becomes unreliable...

I tried with stable and master branch.

thanks !
Andras

    import 'package:flutter/material.dart';

    void main() {
      runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: ListItems(),
        );
      }
    }

    class ListItems extends StatefulWidget {
      @override
      _ListItemsState createState() => _ListItemsState();
    }

    class _ListItemsState extends State<ListItems> {
      List<String> litems = [
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g'
      ];

      var focusedbox = '';

      @override
      Widget build(BuildContext context) {

        return Scaffold(
          body: Container(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                    height: 100.0,
                    child: Text(
                      focusedbox,
                      style: TextStyle(
                        color: Colors.blue,
                        fontSize: 80,
                      ),
                    )),
                Container(
                  height: 50.0,
                  child: ListView.builder(
                    itemCount: litems.length,
                    scrollDirection: Axis.horizontal,
                    itemBuilder: (BuildContext context, int index) {
                      return Focus(
                        onFocusChange: (bool focusgained) {
                          if (focusgained) {
                            setState(() {
                              focusedbox = litems[index];
                            });
                          }
                        },
                        child: Container(
                          height: 100,
                          padding: EdgeInsets.all(10.0),
                          child: RaisedButton(
                            // autofocus: true,
                            clipBehavior: Clip.antiAlias,
                            focusColor: Colors.red,
                            onPressed: () {
                              setState(() {
                                focusedbox = litems[index];
                              });
                            },
                            child: Text(litems[index]),
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        );
      }
    }

-

    andras:apptv3 andras$ flutter doctor -v
    [✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G4032, locale en-US)
        • Flutter version 1.12.13+hotfix.9 at /Users/andras/development/flutter
        • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
        • Engine revision af51afceb8
        • Dart version 2.7.2

    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
        • Android SDK at /Users/andras/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-29, build-tools 29.0.2
        • ANDROID_HOME = /Users/andras/Library/Android/sdk
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 11.3.1, Build version 11C504
        • CocoaPods version 1.8.4

    [✓] Android Studio (version 3.6)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 45.0.1
        • Dart plugin version 192.7761
        • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

    [✓] VS Code (version 1.44.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.9.1

    [✓] Connected device (1 available)
        • sdk google atv x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

    • No issues found!

<img width="788" alt="Screen Shot 2020-04-17 at 4 59 19 AM" src="https://user-images.githubusercontent.com/23754/79567012-4f15bc00-8068-11ea-9775-3051e288004e.png">

<img width="792" alt="Screen Shot 2020-04-17 at 4 59 25 AM" src="https://user-images.githubusercontent.com/23754/79567017-50df7f80-8068-11ea-9331-b06397b7bd29.png">

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
You're creating a separate `Focus` widget that isn't part of the button, and it is receiving focus, and the button isn't focused when that happens, since your new `Focus` widget's focus node is an ancestor of it.

If you add `canRequestFocus: false` to the `Focus` widget you create, it will work as you expect.
