### ISSUE TITLE
Gallery, Scrollable tabs: Open and Close miss frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5503]
Many of the component demos open and close quickly. Something about Scrollable Tabs is missing frames more than many of the other component demos:

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/17819017/e87cd2d4-65fa-11e6-90b0-16c1920d3cc7.png)

**Comment by Hixie** [comment]
cc @eseidel We don't have anyone to work on this right now.

**Comment by eseidelGoogle** [comment]
I expect this will fall out of @cbracken's investigation of missed_frame_rasterizer_budget_count.

**Comment by Hixie** [comment]
This is probably a specific case of https://github.com/flutter/flutter/issues/813.

**Comment by cbracken** [comment]
For tracking purposes, closing as dupe of the Gallery tracking bug for first-frame animation jank #5363, which is a specific case of #813.
