### ISSUE TITLE
Dismissible should have onDragStart and onDragEnd events to prevent re-rendering the tree while user is dragging it

### ISSUE THREAD

**Issue by ramtinq** [flutter/flutter#55041]
The Dismissible widget should have onDragStart and onDragEnd events, to prevent any odd behavior like setState() being called by an async function while user is interacting (dragging) with the dismissible. Such case will result the dismissible jumping back to its initial position while user was dragging it. If there were  methods like onDragStart and onDragEnd, we could use a flag to prevent such odd behaviors while the user is dragging the dismissible.

Using a GestureDetector inside the Dismissible will not help either, since calling methods like onHorizontalDragStart will block dismissible's normal behavior (it will not drag at all!).

Steps to reproduce such odd behavior:
- create a ListView with Dismissible children, where dismissing an item from it will call an async http call to an api to load another item into the list, and after each item is loaded, call setState() so that the new item becomes visible in the tree.
- Try dismissing a few items rapidly, now if you start dragging another item, it will jump back to its initial position if any of the previous async functions have been finished (since it calls setState to make the new item visible).

a simple pair of onDragStart and onDragEnd for the Dismissible widget would simply make us able to prevent any setState() calls while the Dismissible is being dragged, deferring it to either onDismissed or onDragEnd ("dismissing cancelled).

**Comment by TahaTesser** [comment]
Hi @ramtinq 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @ramtinq 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
