### ISSUE TITLE
Material TextSelectionToolbar does not match modern Android UI

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#55049]
Hi,

Flutter is great! But one weakness I have found is text input controls don't match the native user experience in Android. I can see how this is going to be hard to handle because the material style has changed over time. But, I wanted to report it so it can be tracked and hopefully enhanced in a future release of Flutter.

## Steps to Reproduce

1. Add a TextField widget to a simple app.
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(),
      ),
    );
  }
```
2. Select some text and look at the style of the controls:
<img width="639" alt="Screen Shot 2020-04-17 at 12 38 59 PM" src="https://user-images.githubusercontent.com/9597207/79592781-85732b80-80a8-11ea-93d9-de43b4822127.png">

3. Compare this to the actual system UI in Android 29, notice the square vs rounded corners:
<img width="638" alt="Screen Shot 2020-04-17 at 12 37 14 PM" src="https://user-images.githubusercontent.com/9597207/79592882-a76cae00-80a8-11ea-93ce-ee8bcc27531d.png">

<details>
  <summary>(No logs needed)</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/andrewcoutts/Projects/flutter
    • Framework revision d3ed9ec945 (11 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrewcoutts/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/andrewcoutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • Pixel 4                      • 9A311FFAZ00C03                           • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 64 • emulator-5554                            • android-x64   • Android 10 (API 29) (emulator)
    • xFF0C 8                      • d7cab5675167dcdab847995b631648e5c309e1d3 • ios           • iOS 13.3.1
    • iPhone 11 Pro Max            • 75ADC4C9-577F-468A-B5D9-66C1E8634C7A     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

**Comment by lukepighetti** [comment]
This problem is very apparent on iOS and the question of native text inputs in Flutter using platform views keeps coming up in internal conversations.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I agree, this is on my list of things to fix about the selection menu on Android.

@lukepighetti What differences are you referring to with the iOS text selection menu?

I thought there was another issue about this but I couldn't find it if so, by the way.

**Comment by lukepighetti** [comment]
For starters, no tooltip corrections, and the actual tap behavior is not up to date.
