### ISSUE TITLE
Mouse Hover Support

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5504]
We will need to the gesture detector to handle mouseover/mouseout for Fuchsia runtime.

**Comment by abarth** [comment]
Let's talk about this in person.  There are specific reasons we've picked the pointer event model that we have today.

**Comment by Hixie** [comment]
The pointer model does support hover events (though they aren't implemented currently), but supporting hover _gestures_ is intentionally not possible since it has a high performance cost (you have to hit test on every movement). Happy to talk more in person though.

**Comment by abarth** [comment]
Yeah, I think it would be helpful to understand the specific use case so we can look for a solution that avoids the performance problems associated with the traditional mouseover/mouseout events.

**Comment by dvdwasibi** [comment]
Sounds good, will chat in person.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/757

**Comment by goderbauer** [comment]
See also: https://github.com/flutter/flutter/issues/757
