### ISSUE TITLE
Online emulator for both Iphone and Android

### ISSUE THREAD

**Issue by wwmyers** [flutter/flutter#55045]
This feature request is probably for Apple and Google, but I figured I'd ask anyways.

I was thinking since Flutter can build native apps for both Iphone and Android, why not setup an online emulator for developers to test out their apps online, so the developer isn't forced to buy an expensive product just to test a device for an app. Also the developer wouldn't have to download Android Studio or Xcode just to test their apps if they prefer a different editor like Vscode, Vim, or Jetbrains....., the emulator would be online for all to use.

If this feature isn't possible, then maybe contact the appropriate people at Apple and Google to request an online emulator for developers. I think this would save tons of developers a huge headache.

Thanks :)

**Comment by iapicca** [comment]
Hi @wwmyers 
your suggestion for what looks like a  "free online emulator service"
doesn't seem something specific to flutter or
related to flutter framework.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
