### ISSUE TITLE
Canvas paint order lost due to missing z-index

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#55058]
It seems we lost the `z-index` again and therefore back to the original paint order bug.

Here's the bug:

![paint order bug](https://user-images.githubusercontent.com/211513/79606157-05e45d00-80a6-11ea-85d5-8f460f3dfc86.png)

Here's what's in the HTML:

![canvas no z-order](https://user-images.githubusercontent.com/211513/79606205-15fc3c80-80a6-11ea-8033-998a4016c693.png)

**Comment by ferhatb** [comment]
Note: The zIndex = '-1' code path regressed. Need test to prevent this in the future.
