### ISSUE TITLE
Multiple blinking cursors Web app

### ISSUE THREAD

**Issue by phackwer** [flutter/flutter#55053]
## Steps to Reproduce

1 - Create 2 TextFormField assigning FocusNodes to each
2 - Get the currentNode and call "unfocus()"
3 - Get the secondNode and call "requestFocus()"

**Expected results:** 

You should see the cursor going from one field to the other

**Actual results:** 

You see 2 blinking cursors (although focus really is on the second text input)

This probably happens because that blinking cursor is not the actual cursor from the browser

**Comment by VladyslavBondarenko** [comment]
Hi @phackwer 
could you provide your `flutter doctor -v` and a minimal code sample to reproduce the problem?
I can't see described behaviour with `dev 1.18.0-dev.5.0` 

<details>
 <summary>and that code sample</summary>

```
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  FocusNode focusNode1 = FocusNode();
  FocusNode focusNode2 = FocusNode();

  @override
  Widget build(BuildContext context) {

    Timer timer = new Timer(new Duration(seconds: 1), () {
      focusNode1.requestFocus();
    });

    Timer timer2 = new Timer(new Duration(seconds: 5), () {
      focusNode1.unfocus();
      focusNode2.requestFocus();
      print('test');
    });

    return SafeArea(
      child: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextFormField(
              focusNode: focusNode1,
            ),
            TextFormField(
              focusNode: focusNode2,
            ),
          ],
        )
      ),
    );
  }
}
```

</details>

**Comment by phackwer** [comment]
I've been away for 2 weeks on a different project. I will get you how this was done tomorrow morning. Cheers.

**Comment by TahaTesser** [comment]
Hi @phackwer 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
