### ISSUE TITLE
Provide documentation for the Skia SKP file format.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#55052]
[_flutter.screenshotSkp](https://github.com/flutter/flutter/wiki/Engine-specific-Service-Protocol-extensions#get-screenshot-of-view-as-skia-picture-_flutterscreenshotskp) provides a way to get a skia SKP screenshot of a Flutter view. I was not able to find any public documentation about how to interpret that data. 
There is a skia debugger online, but I'd like to work with that file directly.

Can anybody more familiar with that topic provide a link to relevant material?

Thanks.

**Comment by chinmaygarde** [comment]
The SKP file format is not stable (though it doesn't change too often) or documented. It depends on on Skia internals and must be used with the debugger available at https://debugger.skia.org/ which is also tied to a specific Skia version (mentioned in the top left).

I have asked to Skia folks to confirm if this is feasible/planned.

**Comment by mikerreed** [comment]
If the file is still compatible with your local copy of Skia, you can turn it back into a picture via

SkPicture::MakeFromData() or MakeFromStream()

**Comment by mikerreed** [comment]
... if it is not, those methods will return nullptr

**Comment by modulovalue** [comment]
@mikerreed thank you for the hint, but I'm looking/asking for a versioned specification of the file format, so that tools that don't have direct access to the skia engine can interpret its contents.

**Comment by chinmaygarde** [comment]
As stated earlier, the SKP format is not meant to be stable and is tied to Skia internals. The Skia team currently has no intentions of supporting tools outside of Skia from working with this internal format. Closing this as wont-fix.
