### ISSUE TITLE
Input should assert that ancestor is Form when Formfields are used.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5505]
This should work similarly to the way `Material`-using widgets assert the fact that one of their parents is `Material`.

**Comment by mpcomplete** [comment]
Similarly, we should improve the error case when you use an Input without a Form and don't update the InputValue you provide, e.g.  `new Input(value: null, ...)` . When you do this, typing into the text field gives you weird graphical artifacts.

**Comment by mpcomplete** [comment]
We should also assert the only one of `value` and `formField` are specified.

**Comment by edelvalle** [comment]
Also there is another interesting bug, example:

if you have a form like this one

```
body: new Form(
  child: new Block(
    children: <Widget>[
      new Input(
        hintText: 'youremail@somewhere.com',
        labelText: 'User name',
        autofocus: true,
        value: new InputValue(text: this._username),
        formField: new FormField<String>(
          setter:  (String val) {
            this._username = val;
          }
        )
      ),
    ]
  )
)
```
I'm using InputValue to set the initial value of this Input and then this causes a constant re-render, and I can see the setter being called continuously.

**Comment by edelvalle** [comment]
Oh, no... this re-render thing that makes sense... then how do it set an initial value for an input?

**Comment by mpcomplete** [comment]
Looks like there's no way to set an initial value while having a formField. That's another bug.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/6322 fixes all the above.

**Comment by mpcomplete** [comment]
Going to close this in favor of #6097 .
