### ISSUE TITLE
Gallery: not clear it's a preview for first-time user

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5506]
When first-time users install and open the app, it's not clear we're a preview. Deep in the About Flutter, we say we're a "Q3 Preview", which is great, but too far into the app to correctly set expectations.

I like the wording "preview", as it hints at more awesome to come.

Can we fit the word _preview_ into the title somehow, in the app bar? That would be the most obvious place, imo.

I'm happy to try a few options with my local copy, but open to ideas for how to indicate preview to users when they open the app.

**Comment by sethladd** [comment]
Adding "(preview)" is too long for a Nexus 5.

Options:

* `Gallery (preview)` which isn't great because we miss the name Flutter
* `Flutter Gallery\n(preview)` which isn't great because the minimized app bar can't handle two-line text
* Use an image ?

**Comment by eseidelGoogle** [comment]
Customer: fast adds a banner to their app to show it's using fake data.  I'm not sure we'd want to banner the app, but we could banner the Icon to say "beta" or "alpha"?  Donno.

**Comment by sethladd** [comment]
Ribbon would be cool, too. I'd put it on the right, so it doesn't interfere with the hamburger icon.

@HansMuller your call, should we do a ribbon or add "(preview)" to the app bar title?

**Comment by HansMuller** [comment]
I tried making the a preview label that was aligned with the background. It's not good. A ribbon like the "slow mode" ribbon seems like a better idea. 

![screenshot](https://cloud.githubusercontent.com/assets/1377460/17824881/68f6e260-6619-11e6-8482-6269ae48bb13.png)

**Comment by sethladd** [comment]
Ribbon it is! :)

Though, bonus points for getting Preview in there all rotated.

**Comment by HansMuller** [comment]
Assuming that this is OK, we'll need a way to configure the ribbon when the app is built.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/17900439/37910cca-6914-11e6-9e07-613b64085db3.png)

**Comment by sethladd** [comment]
Nice!

Curious, why would we configure this ribbon when the app is built? Wouldn't we leave it there until it's no longer preview? :)

**Comment by HansMuller** [comment]
Yes, you are correct. In checked mode, we'll still display the "slow mode" ribbon, otherwise we'll display "preview".

**Comment by sethladd** [comment]
sgtm

Does the text scale to the screensize? That is, will the entire word "PREVIEW" show up on an iPod Touch, Nexus 5, 5X, and 6P?

(happy to test, but maybe we know if it will/should scale?)

**Comment by sethladd** [comment]
Thank you!
