### ISSUE TITLE
Slow response when dragging a Slider on Web

### ISSUE THREAD

**Issue by marinatrajk** [flutter/flutter#55067]
I'm experiencing very slow response when dragging an opacity control slider on Web:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9975218/79615374-9cc60f00-80d0-11ea-90ef-8139fba04add.gif)

```
class OpacityControlSlider extends StatelessWidget {
  const OpacityControlSlider({
    Key key,
    @required AmpStoryElement element,
  })  : _element = element,
        super(key: key);

  final AmpStoryElement _element;

  @override
  Widget build(BuildContext context) {
    final _value = _element?.opacity ?? 1;
    return Container(
      height: 40,
      child: Row(
        children: <Widget>[
          ActionPaneLabel(
            label: I18n.of(context).propertiesOpacity,
          ),
          Container(
            width: 190,
            child: Slider(
              activeColor: UIColors.lightRoyalBlue,
              value: _value,
              onChanged: (val) {
                final _model = Provider.of<StoryModel>(context, listen: false);
                _model.editElement(_element.copyWith(opacity: val));
              },
            ),
          ),
        ],
      ),
    );
  }
}
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-6.0.pre.70, on Mac OS X 10.15.3 19D76, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by VladyslavBondarenko** [comment]
complete reproducible code sample

https://codepen.io/vladbond/pen/ZEbppoj

**Comment by ferhatb** [comment]
@marinatrajk, performance at development time is not comparable to a release build using flutter build web. Are you seeing the same issue in a release build?

We might still be able to improve development time performance but it will still be lower than production code.

**Comment by ferhatb** [comment]
Workaround: please use RepaintBoundary(child: Slider.
In the example the slider constantly repaints the full app.

**Comment by ferhatb** [comment]
Verified that on latest master the sample in --release is 60fps. Please place the widget into a repaintboundary if other parts of your app are being repainted and causing the slowness.
