### ISSUE TITLE
[Dark Theme] applyElevationOverlayColor flag sometimes applies in light themes

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#55060]
When setting `ThemeData.applyElevationOverlayColor` to true, some widgets are unexpectedly receiving the overlay even in light theme.

Regular `Material` widgets do not receive the overlay, but some widgets like `RaisedButton` and `FloatingActionButton` do. 

![giphy](https://user-images.githubusercontent.com/4229329/79607564-66cd5e80-80c1-11ea-9eaf-74a51ab8db7e.gif)

The two buttons on the right should not be getting darker. 

## Steps to Reproduce

Reproducible example app:

```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.light().copyWith(applyElevationOverlayColor: true),
      home: Body(),
    );
  }
}

class Body extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BodyState();
}

class BodyState extends State<Body> {
  double elevation = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Elevation:'),
            SizedBox(
              width: 200,
              child: Slider(
                value: elevation,
                onChanged: (value) => setState(() {
                  elevation = value;
                }),
                min: 0,
                max: 20,
              ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(
                  width: 80,
                  height: 40,
                  child: Material(
                    elevation: elevation,
                    child: Center(child: Text('Material')),
                  ),
                ),
                FloatingActionButton(
                  backgroundColor: Colors.white,
                  onPressed: () {},
                  elevation: elevation,
                  child: Center(
                    child: Text('FAB', style: TextStyle(color: Colors.blue)),
                  ),
                ),
                RaisedButton(
                  color: Colors.white,
                  onPressed: () {},
                  elevation: elevation,
                  child: Center(
                    child: Text(
                      'RaisedButton',
                      style: TextStyle(color: Colors.blue),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by johnsonmh** [comment]
Update: A better demonstration is if you set the `color:` on all the widgets to `Theme.of(context).colorScheme.surface`, which is the only color surface that the elevation overlay is applied to. 

Making that change reveals that `Material` widgets also add the overlay.

I believe we should change this conditional: https://github.com/flutter/flutter/blob/f139b11009aeb8ed2a3a3aa8b0066e482709dde3/packages/flutter/lib/src/material/elevation_overlay.dart#L37

To also include a check for `Theme.of(context).brightness == Brightness.dark`, since the overlay is only supposed to be apply in dark themes.

**Comment by darrenaustin** [comment]
Actually this is by design. The `applyElevationOverlayColor` was a switch to turn the overlay on or off. It was up to the apps to turn it on if they wanted it for dark themes.

That said, given this confusion and thinking about possibly getting rid of this flag in the future, it might be good to tie it to the dark theme directly as you mentioned above.  I'll put together a PR to do this shortly.

BTW, I think I didn't have it keyed to elevation > 0 because the elevation is animated and not handling it for 0 would cause pops in color when changing the elevation.

**Comment by johnsonmh** [comment]
Ah I see, yes I misread the documentation. 

I think it would be preferable to incorporate the brightness check into the overlay itself, since applying the overlay in light theme is not what this is intended for.

It's also kind of a hassle to get the desired behavior as is, because when you're creating a `ThemeData`, you don't necessarily know what the `brightness` is (because you can't get the `Theme.of(context).brightness` when you're making a `ThemeData`).
