### ISSUE TITLE
countering error

### ISSUE THREAD

**Issue by okpisajnr** [flutter/flutter#55087]
after running flutter upgrade, i found a error
ever since even flutter doctor isnt working
please i need help. 
![Screenshot (275)](https://user-images.githubusercontent.com/48180555/79629001-c0736e80-813d-11ea-8311-5c47c5d1d3a1.png)

**Comment by jonahwilliams** [comment]
The error indicates that there is a bug executing a bash script, but the screenshot you've posted shows windows? Can you confirm that you are running flutter in a normal windows environment? Or are you using the windows linux subsystem?

**Comment by VladyslavBondarenko** [comment]
@okpisajnr 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Comment by okpisajnr** [comment]
Issue resolved.
Warm regards
