### ISSUE TITLE
AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed

### ISSUE THREAD

**Issue by syge** [flutter/flutter#55089]
AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed

**Comment by iapicca** [comment]
Hi @syge 
can you please provide your `flutter doctor -v` , 
your [android] => [gradle] => `build.gradle`,
and your `pubspec.yaml` 
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
