### ISSUE TITLE
[team] LUCI production builders should never re-upload package that has already been uploaded

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#55082]
When I landed https://github.com/flutter/infra/pull/96, I created 3 new gitiles pollers for the packages, dev, beta, and stable. These new pollers instantly triggered builds for the tip of each branch. I think because of a race condition, the beta release for all 3 platforms was not updated (on windows, only the stable release date was updated).

Re-generating the packages caused the checksums to change. The checksum of a zip archive is dependent on timestamps https://tanzu.vmware.com/content/blog/barriers-to-deterministic-reproducible-zip-files. Changing the checksums broke a [third-party package manager](https://aur.archlinux.org/packages/flutter/) distributing the pre-built Flutter. In the future, [we will be checksumming](https://github.com/flutter/flutter/issues/38980) these artifacts in the flutter tool proper, so we cannot change these checksums. Once a particular revision of the engine is built, **we should not re-build it**.

Checklist:
- [ ] Ensure packaging builders do not re-upload packages to cloud storage for a commit where packages already exist
- [x] Ensure engine builders do not re-upload packages to cloud storage for a commit where packages already exist https://flutter-review.googlesource.com/c/recipes/+/5040
- [x] Ensure only the latest commit triggers a packaging build when commits are pushed to a release branch https://github.com/flutter/infra/pull/150
- [x] Ensure CIPD packages are not re-published https://flutter-review.googlesource.com/c/recipes/+/4345

**UPDATE**

A related issue, since July, a push to a release branch results in each new commit triggering a packaging build. The good news: in the `flutter.py` recipe we grab the HEAD of the release branch, so no matter the commit that triggered the build, we were grabbing the correct release commit. The bad news: this means we build, package, and upload the same release n times (where n is the number of commits since the last release).

Possible solutions:

1. remove the `max_batch_size` attribute from the packaging builders, it's currently set to 1 (or build each commit), but will default to 1000. This will ensure we don't waste any LUCI resources.
1. Update the recipe to have more validations before running the prepare_package.dart script. Currently the only check we have is that git_ref is one of the release branches. We could also add the following additional checks:
  a. That the triggering commit is the same as the tip of the branch.
  b. That the output directory in cloud storage does not already exist. This would ensure we never re-upload an existing package, changing the checksum in the process.

**UPDATE 2**

We should do the same for the engine, never upload binaries to a engine hash we already uploaded.

**Comment by littlepine** [comment]
Excuse me, I am using Arch Linux and got the problem on verifying the checksum of flutter 1.12.13+hotfix.9-stable.
I would like to know if I can just work around by changing the correct chceksum?

If so, where can I get the correct checksums?

Thank you very much~~

**Comment by christopherfujino** [comment]
> Excuse me, I am using Arch Linux to install flutter through AUR and got the problem on verifying the checksum of flutter 1.12.13+hotfix.9-stable.
> I would like to know if I can just work around by changing the correct chceksum?
> 
> If so, where can I get the correct checksums?
> 
> Thank you very much~~

@littlepine You can curl the tarball here https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.9-stable.tar.xz and then sha256sum it yourself :)

**Comment by zanderso** [comment]
@christopherfujino Could you give an update on why this was escalated to P0? I'll give this a July milestone based on the priority, but feel free to correct it if I'm mistaken. Thanks!

**Comment by christopherfujino** [comment]
> @christopherfujino Could you give an update on why this was escalated to P0? I'll give this a July milestone based on the priority, but feel free to correct it if I'm mistaken. Thanks!

For example, because of this the framework tree just became red again. This issue means that a green engine build can retroactively become bad.

**Comment by pcsosinski** [comment]
how are we doing on this?

**Comment by christopherfujino** [comment]
> how are we doing on this?

I have a fix, just working on getting unit tests to pass https://flutter-review.googlesource.com/c/recipes/+/4940

**Comment by christopherfujino** [comment]
Updating the milestone as we're into august, and I'm reverting my latest attempt. https://flutter-review.googlesource.com/c/recipes/+/5121

**Comment by christopherfujino** [comment]
Closing this with https://flutter-review.googlesource.com/c/recipes/+/5141

**Comment by christopherfujino** [comment]
Actually, re-opening this as a P3 because we still haven't safeguarded the packaging builders. However, this is less damaging (the only thing I know that it breaks is the checksum of the zip files, which some downstream package managers validate), and less likely to be re-triggered (it happened when I added new builders).

**Comment by christopherfujino** [comment]
Everything is done on this issue except for safe-guarding the uploading of packages (which is less critical as it just changes checksums). Moving the milestone as I wasn't able to get to it this month.

**Comment by christopherfujino** [comment]
Currently WIP
