### ISSUE TITLE
TextField - "obscureText: true" is broken 

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#55081]
Simple TextField with obscureText: true, is completely broken in flutter master branch code.
I could not see characters entered in the text filed and the cursor moving.

Works on android but not on iOS.
 
Example:

```
TextField(
        obscureText: true,
        decoration: InputDecoration(
          labelText: 'Password',
        ),
      )

```

$: flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-6.0.pre.79, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
$:

**Comment by UrAvgDeveloper** [comment]
Same here

**Comment by jmolins** [comment]
Same here.

But it is not completely broken.

If I do `obscureText: false`, write something or bring up the keyboard (with CMD K), then change to `obscureText: true` and do a Hot Restart it works. I'm able to hide or show the keyboard.

But if I do a fresh compile it does not work. And I'm not able to show the keyboard with CMD K either.

It might have something to do with showing the keyboard o with connecting with the keyboard.

**Comment by ochmist** [comment]
I am seeing the same behavior as well @jmolins

**Comment by imeDevelopers** [comment]
hi guys ..

try to add `onEditingCompleted: `parameter ..
and `enabled: true ,` parameter
and `readOnly: false,`

**Comment by kmusham** [comment]
For now I switched to a previous dev channel for old version and works fine.
Here is the version the issue is not reproducible.
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale en-US)

**Comment by johnrufusj** [comment]
I am seeing the same behavior. Only on IOS.

**Comment by marcianobandeira** [comment]
i have same problem in ios.. master channel

**Comment by marcianobandeira** [comment]
> hi guys ..
> 
> try to add `onEditingCompleted: `parameter ..
> and `enabled: true ,` parameter
> and `readOnly: false,`

does not work

**Comment by emrekaranfil** [comment]
I have same problem in iOS (master channel)
