### ISSUE TITLE
Web users may be accidentally using the less useful web-server device

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55084]
`flutter run -d` supports partial matching of device name, so running `flutter run -d web` will match `web-server` if it is enabled. `web` was the old name of the `chrome` device, so users following outdated documentation will end up running a version of flutter that does not support hot restart without refreshing.

We should consider hiding the web-server device, similarly to how the flutter-tester is hidden.

fyi @mdebbar @yjbanov

**Comment by jonahwilliams** [comment]
Also @DanTup

**Comment by DanTup** [comment]
If we hide it, we'd need some special handling in VS Code to add it back (or a flag). If the concern is only people typing "-d web", could we add "web" as an alias for the Chrome device? (or just change the web servers id?)

**Comment by yjbanov** [comment]
The tool pring "Launching _____ on Web Server", so it's probably not a big source of surprise. I'll put it in stretch goals as a potential improvement. Have you seen any reports of confusion from users?

**Comment by jonahwilliams** [comment]
Yeah, I've dealt with a few issues that amounts to "why can't web-server do everything that chrome device does" or "why doesn't dart support debugging when I run -d web like I found on this old article". It is understandably confusing, and I'm not likely to make any improvements to the web-server device in the near future.
