### ISSUE TITLE
Error on loading big file image into FittedBox

### ISSUE THREAD

**Issue by arutkayb** [flutter/flutter#55093]
I'm using Android studio.

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

Error:

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 313 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  FittedBox file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:64:58
When the exception was thrown, this was the stack: 
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:313:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2296:26)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#5      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
...
The following RenderObject was being processed when the exception was fired: RenderFittedBox#c25f6 relayoutBoundary=up24 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight (can use size)
...  constraints: BoxConstraints(w=40.7, 0.0<=h<=Infinity)
...  size: MISSING
...  fit: fitWidth
...  alignment: center
...  textDirection: ltr
RenderObject: RenderFittedBox#c25f6 relayoutBoundary=up24 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight (can use size)
  constraints: BoxConstraints(w=40.7, 0.0<=h<=Infinity)
  size: MISSING
  fit: fitWidth
  alignment: center
  textDirection: ltr
...  child: RenderFlex#0ff7d relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: Size(0.0, 0.0)
...    direction: vertical
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    verticalDirection: down
...    child 1: RenderSemanticsAnnotations#51850 relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(0.0, 0.0)
...      child: RenderImage#41377 relayoutBoundary=up27 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(0.0, 0.0)
...        image: null
...        fit: contain
...        alignment: center
...        invertColors: false
...        filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderFittedBox#c25f6 relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Row file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:61:30
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderFlex#0f8dd relayoutBoundary=up23 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ClipRRect file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:57:28
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderClipRRect#775f5 relayoutBoundary=up22 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Container file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:55:19
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#06ea2 relayoutBoundary=up21 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Row file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:49:14
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderFlex#0fd5e relayoutBoundary=up20 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Container file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:39:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#90e02 relayoutBoundary=up19 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Container file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:39:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderDecoratedBox#f4eaf relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  GestureDetector file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:31:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPointerListener#76ba7 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  GestureDetector file:///Users/rutkay/workspace/Intimassy/intimassy/lib/common/component/intimassy_card.dart:31:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#368a4 relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:119:30
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (11) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderFlex#d9446 relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (12) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: _RenderSingleChildViewport#0c9d6 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (13) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderIgnorePointer#58806 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (14) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#2c6d6 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (15) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderPointerListener#758b0 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (16) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#87e29 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (17) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderPointerListener#32e68 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (18) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: _RenderScrollSemantics#9e03c relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:148:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (19) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: _RenderSingleChildViewport#0c9d6 relayoutBoundary=up14 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (20) Exception caught by scheduler library ════════════════════════════════════════════════
Updated layout information required for RenderPadding#8c3c8 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2549 pos 12: '!_needsLayout'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (21) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: _RenderScrollSemantics#9e03c relayoutBoundary=up8
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:148:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (22) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: _RenderSingleChildViewport#0c9d6 relayoutBoundary=up14 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SingleChildScrollView file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:118:36
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (23) Exception caught by rendering library ════════════════════════════════════════════════
'package:flutter/src/rendering/object.dart': Failed assertion: line 1651 pos 12: '!_debugDoingThisLayout': is not true.
The relevant error-causing widget was: 
  Column file:///Users/rutkay/workspace/Intimassy/intimassy/lib/ui/entry_dashboard/overview/entry_overview.dart:148:24
════════════════════════════════════════════════════════════════════════════════════════════════════

Case:
When I try to load an image previously saved into the application directory by 

```
final String path = (await getApplicationDocumentsDirectory()).path;
    String newPath = '$path/' + DateTime.now().millisecondsSinceEpoch.toString()+ extension(image.path);

    File res =  await image.copy(newPath);
```

Also, there is a flicker on the loading image with Image.file() widget. It seems to be resized from size 0 to the widget size. I think the issue is caused by this flicker on the initial loading phase.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
