### ISSUE TITLE
If set io.flutter.embedded_views_preview to true, can't run flutter project normally

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#55099]
## Steps to Reproduce

set io.flutter.embedded_views_preview to true in Info.plist

```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Expected results:** 
run normally in iphone 

**Actual results:** 
run normally in iOS Simulator, shows a black screen in my iphone. but it can show other widgets except embedded views when I delete  io.flutter.embedded_views_preview.

<details>
  <summary>Logs</summary>

no logs, don't throws any exceptions.

```
[✓] Flutter (Channel master, v1.9.1-pre.58, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)

```

</details>

**Comment by AndrewPricee** [comment]
have you added the following:

<key>NSAppTransportSecurity</key>
	<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	</dict>

**Comment by AndrewPricee** [comment]
Try adding the following:

`<key>NSAppTransportSecurity</key>
	<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	</dict>`

**Comment by VladyslavBondarenko** [comment]
Thanks @AndrewPricee 

@longdw do you have this in your `Info.plist`? 
Please note that current stable flutter version is `v1.12.13+hotfix.9`.
Could you check are you experiencing this with the last stable or other later version from another channel?
If yes, could you provide a minimal complete code sample to reproduce it?

**Comment by longdw** [comment]
Thanks @AndrewPricee @VladyslavBondarenko 
I have this in Info.plish.
I switch branch to 1.9.1+hotfix.6 and solve this problem.
