### ISSUE TITLE
Received image from picker that was not requested

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#55097]
This plugin worked perfectly before I upgrade follow this [guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

After upgraded, this plugin crashed my app after image is selected.

**Error**

> D/EGL_emulation(21100): eglMakeCurrent: 0xe3485ea0: ver 2 0 (tinfo 0xe3483f30)
> D/FlutterView(21100): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@96a74e4
> D/AndroidRuntime(21100): Shutting down VM
> E/AndroidRuntime(21100): FATAL EXCEPTION: main
> E/AndroidRuntime(21100): Process: com.xxx, PID: 21100
> E/AndroidRuntime(21100): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/360/ORIGINAL/NONE/444714965 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F360/ORIGINAL/NONE/444714965} }} to activity {com.xxx/com.xxx.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
> E/AndroidRuntime(21100):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
> E/AndroidRuntime(21100):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
> E/AndroidRuntime(21100):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
> E/AndroidRuntime(21100):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)

**Comment by tony123S** [comment]
Found out the problem,.With the latest version of Flutter on stable channel 1.12.13+hotfix.9, we can't use plugin `image_picker` and `image_picker_saver` together.

**Comment by Combatwombat77** [comment]
Did you find a fix for this? I've been having this problem as well and figured out what it was but i have no idea how to fix it because i need both packages or at least both functions

**Comment by tony123S** [comment]
@Combatwombat77  Unfortunately, no. You can write a method to save image to your local device instead of using `image_picker_saver ` plugin.

**Comment by Combatwombat77** [comment]
> @Combatwombat77  Unfortunately, no. You can write a method to save image to your local device instead of using `image_picker_saver ` plugin.

Thanks. I appreciate it.

**Comment by Combatwombat77** [comment]
> @Combatwombat77  Unfortunately, no. You can write a method to save image to your local device instead of using `image_picker_saver ` plugin.

Thanks. I appreciate it.

**Comment by tony123S** [comment]
You're welcome.

**Comment by Combatwombat77** [comment]
> @Combatwombat77  Unfortunately, no. You can write a method to save image to your local device instead of using `image_picker_saver ` plugin.

Is there a way I can get in contact with you for help on this ? Or do you have a reference I can follow?

**Comment by tony123S** [comment]
You can try this

```Future<String> _createFileFromString(String imagePath) async {
    Uint8List bytes = base64Decode(base64);
    String dir = (await getApplicationDocumentsDirectory()).path;
    File file = File(
        "$dir/" + DateTime.now().millisecondsSinceEpoch.toString() + ".png");
    await file.writeAsBytes(bytes);
    return file.path;
  }```

**Comment by Combatwombat77** [comment]
> You can try this
> 
> ```
>     Uint8List bytes = base64Decode(base64);
>     String dir = (await getApplicationDocumentsDirectory()).path;
>     File file = File(
>         "$dir/" + DateTime.now().millisecondsSinceEpoch.toString() + ".png");
>     await file.writeAsBytes(bytes);
>     return file.path;
>   }```
> ```

Thanks again.
