### ISSUE TITLE
The flutter Daemon has terminated

### ISSUE THREAD

**Issue by hamadiSimba** [flutter/flutter#55104]
I tried to review all information about this problem in previous Comments, but I think it was not clear what was a problem and how can it be fixed! bellow there are some images I bind it together
![terminal](https://user-images.githubusercontent.com/63913859/79639984-b1b9a580-8197-11ea-878b-1261d6736423.PNG)

Here is my log file!
[log-6666.txt](https://github.com/flutter/flutter/files/4496744/log-6666.txt)
I will appreciate your help please!!!!

**Comment by iapicca** [comment]
Hi @hamadiSimba 
can you please provide your `flutter doctor -v` , 
and your `flutter run --verbose`
Thank you

**Comment by TahaTesser** [comment]
Hi @hamadiSimba 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
