### ISSUE TITLE
Unable to load asset flutter error

### ISSUE THREAD

**Issue by satyamraj123** [flutter/flutter#55102]
When i installed my application for first time then this error was thrown-

Launching lib\main.dart on Android SDK built for x86 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(28506): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(28506): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(28506): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(28506): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(28506): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@2fba2465
D/FlutterActivityAndFragmentDelegate(28506): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation(28506): eglMakeCurrent: 0xae834e80: ver 2 0 (tinfo 0xae839400)
I/flutter (28506): Offset(237.7, 768.3)
I/flutter (28506): home to gps
**E/flutter (28506): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/Sad emoji.flr**
E/flutter (28506): #0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:221
E/flutter (28506): <asynchronous suspension>
E/flutter (28506): #1      AssetFlare.load 
package:flare_flutter/provider/asset_flare.dart:26
E/flutter (28506): #2      FlareCacheAsset.load 
package:flare_flutter/flare_cache_asset.dart:30
E/flutter (28506): #3      Cache.getAsset 
package:flare_flutter/cache.dart:58
E/flutter (28506): #4      cachedActor 
package:flare_flutter/flare_cache.dart:27
E/flutter (28506): #5      FlareRenderBox.loadFlare 
package:flare_flutter/flare_render_box.dart:308
E/flutter (28506): #6      FlareActorRenderObject.coldLoad 
package:flare_flutter/flare_actor.dart:389
E/flutter (28506): #7      FlareRenderBox.load 
package:flare_flutter/flare_render_box.dart:258
E/flutter (28506): #8      FlareRenderBox.attach 
package:flare_flutter/flare_render_box.dart:104
E/flutter (28506): #9      AbstractNode.adoptChild 
package:flutter/…/foundation/node.dart:132
E/flutter (28506): #10     RenderObject.adoptChild 
package:flutter/…/rendering/object.dart:1238
E/flutter (28506): #11     RenderObjectWithChildMixin.child= 
package:flutter/…/rendering/object.dart:2905
E/flutter (28506): #12     SingleChildRenderObjectElement.insertChildRenderObject 
package:flutter/…/widgets/framework.dart:5460
package:flutter/…/rendering/object.dart:2905
E/flutter (28506): #12     SingleChildRenderObjectElement.insertChildRenderObject 
package:flutter/…/widgets/framework.dart:5460
E/flutter (28506): #13     RenderObjectElement.attachRenderObject 
package:flutter/…/widgets/framework.dart:5295
E/flutter (28506): #14     RenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5058
E/flutter (28506): #15     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #16     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #17     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5445
E/flutter (28506): #18     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #19     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #20     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter (28506): #21     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter (28506): #22     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter (28506): #23     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter (28506): #24     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #25     MultiChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5551
E/flutter (28506): #26     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #27     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #28     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5445
E/flutter (28506): #29     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #30     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #31     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5445
E/flutter (28506): #32     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #33     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #34     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5445
E/flutter (28506): #35     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #36     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #37     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5445
package:flutter/…/widgets/framework.dart:5445
E/flutter (28506): #38     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #39     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter (28506): #40     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter (28506): #41     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter (28506): #42     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter (28506): #43     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter (28506): #44     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter (28506): #45     Element.updateChild (package:flutter/src/widgets/framework.dar

And this was the result-

![Screenshot (40)](https://user-images.githubusercontent.com/57063364/79639029-89857300-81a6-11ea-8a94-5a5872a1b4ab.png)

Then I restarted the application(ctrl+shift+f5 in VSCode) the and then it works-

![Screenshot (41)](https://user-images.githubusercontent.com/57063364/79639060-c5b8d380-81a6-11ea-8c25-688814bcb708.png)

This is pubspec.yaml file-

    flutter:
     uses-material-design: true
     assets:
       - assets/ 
       - assets/splash_screen.flr
       - assets/Success Check.flr
       - assets/nav.flr
       - assets/gps loco.flr
       - assets/Sad emoji.flr
       - assets/Arrow.flr
       - assets/loader-ready.flr
       - assets/switch_daytime.flr

This problem occur in all devices whenever I install or reopen this application.
I also tried flutter clean tool in android studio code, but same problem still there.
I also created fresh project several times but same problem.
In few fresh projects , my other assets like splash screen are unable to load but that sad emoji asset was fixed.
Due to this error Im unable to launch my application, 
Please help me out.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
