### ISSUE TITLE
dart sdk install problem

### ISSUE THREAD

**Issue by Abirhosen** [flutter/flutter#55118]
i can't install dart sdk ..all time its shows connection with the server could not be established

**Comment by imeDevelopers** [comment]
please provide `flutter doctor -v` results

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
