### ISSUE TITLE
[in_app_purchase] Plugin requires login before app starts loading

### ISSUE THREAD

**Issue by haxorone** [flutter/flutter#55113]
## History
During the early stages of implementing in app purchase using this plugin, I was having trouble understanding some of the flows. Particularly, on IOS I had an early dev bug where I would make a test purchase with a sandbox user, NOT complete the purchase, delete the user because you can only use those IOS sandbox users to purchase these things once, and then start the process over. This has me in a state where I have a stream of old, pending, non-completed upgrade products that are still in queue, but used by sandbox users that no longer exist.

When I start my app, I get a flood of these bad orders come in. I have reached out to apple to see if they can resolve this issue from their end by removing some backend data associated with these now-deleted sandbox users. It has been a few weeks with no movement on it, but from the last couple emails, I am hopeful this will be resolved soon.

The bug that lead to this situation in my code has already been resolved. I now complete every order.

During the process of realizing this bug, I was constantly faced with this other issue, which is the topic of my question. Basically, since the introduction of this original bug in my code, every time I start the app, when I am developing it in Android Studio (or running it manually in xCode), I am faced with this dumb 'apple login' modal when I start my app that says 'Sign-in Required. Enter the password for .' (yes, the username is blank).

Since the introduction of this bug, and since discovering that it was a bug on my end, I have been faced with this login modal on app start, while developing it. Until recently, I believed this to be a side-effect of my original bug, and have just been dealing with it by canceling the login modal until it stops popping up.

A couple days ago however, one of my users (who does develop his own apps) of my now in-production app reached out and said that every time they load my app up, they are faced with a login modal to their full apple account (not a sandbox account like in my case, but their full, actual apple account). He said it reminds him of the box he gets when he has to login to make a purchase. Based on the screenshot he sent me, I tend to agree with that assessment. He said that he has not made any purchases in the app, which I can verify by seeing in my apple dashboard that no in-app-purchases have transpired.

Based on that, I now believe this login modal issue to be unrelated to my earlier bug. To that end, I started debugging a bit with breakpoints and logging. As it turns out, this login modal actually loads before ANY of my app code actually runs, at least the app code I have written in flutter. I can verify this by putting a breakpoint inside the very very very top of the `main()` function. The login modal pops a few seconds before the execution reaches my breakpoint.

With all this given information, I am now kind of stuck. I am not really sure where to go from here. My knowledge of the life-cycle of the app prior to loading my flutter code, is pretty limited, and I am reaching out to see if there is any suggestions that anyone here may have to either resolve this issue completely, or to at least point me in the right direction so I can further track it down to a root cause.

## Steps to Reproduce

Because of my pre-existing circumstance, I feel like these will be less helpful than they typically are, but I will do my best to provide a step by step of my understanding of how to get where I am:

1. on ios, create a sandbox user
2. run your app with in_app_purchase installed and configured
2a. make sure that the app has a flaw in it where it receives the orders, issues the benefit of the order, but does not complete the order
3. make a purchase using that sandbox user
3a. make sure you have a way to see that you would have completed the order, but did not
4. close your app
5. delete the sandbox user
5a. also log out of the sandbox user on your device
6. run your app again
7. observe that you are now faced with a login modal for either a non-usernamed user or the old sandbox user you used to make the purchase
7a. also observe that you are given pending orders in the code

__ I do not have more details about the other user's 'setup' steps on how he was able to reproduce the login modal. From what I understand via our conversations, he simply installed the app, started playing, and this started happening. Also worth noting, I have not heard any similar things from other iOS users, mostly because I do not have any direct contact with them. __

**Expected results:**

I expect that the user is not prompted to login until they make a new purchase. I do understand that the user's previous purchase is being processed, and I do also understand that in order to process that order, the user must login. Despite that knowledge, I can say with 100% certainty that the user is being required to login before I initiate a check of their past orders in my code. It is happening before my app's flutter code even starts running.

My expectation is that the user is not required to login until they trigger something in my app that specifically requires a login, like loading their previous orders via code I wrote, or purchasing a new product.

**Actual results:**

I see that the login modal for apple is being popped before my flutter code runs at all. My `Runner/AppDelegate.swift` is vanilla with the addition of one line to initialize Firebase. I can see that if I put a breakpoint at the beginning of my `main()` flutter function, that the login modal pops up BEFORE that breakpoint is triggered.

<details>
  <summary>Logs</summary>

Attached in file form
[run.log](https://github.com/flutter/flutter/files/4496996/run.log)

Attached in file form
[analyze.log](https://github.com/flutter/flutter/files/4496999/analyze.log)

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/chris/flutter/latest-flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/chris/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_212-release"
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version openjdk version "1.8.0_212-release"

[✓] Connected device (2 available)
    • SM G965U1           • DEVICE_ID_REMOVED                         • android-arm64 • Android 10 (API 29)
    • Chris’s iPhone • DEVICE_ID_REMOVED • ios           • iOS 12.4.5

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @haxorone 
thanks for your `flutter doctor -v` 
and your logs look clean;
might depend from the implementation,
is it possible for you to provide a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @haxorone 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
