### ISSUE TITLE
How to add an animation each time  Widget build(BuildContext context) is called

### ISSUE THREAD

**Issue by Yirmerah** [flutter/flutter#55120]
Hi everyone,

Here my Widget build(BuildContext context):
@override
  Widget build(BuildContext context) {
    if (isAuth) {
      return buildAuthScreen();
    } else if (isRegister) {
      return buildRegisterUnAuthScreen();
    } else {
      return buildUnAuthScreen();
    }
  }
}

I wanted to know if there is way to called a animation each time my Widget build(BuildContext context) function is called and a new page is return, so that the new Page is return with an animation.
I already know, that there is a way to do it with Animation Page route, but i only want to display an animation when displaying a new buildScreen.

Thank you ,

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
