### ISSUE TITLE
Finished with error: Failed to bind web development server: SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 62968

### ISSUE THREAD

**Issue by jwngma** [flutter/flutter#55127]
I am getting this error when running my project on flutter web:
Launching lib\main.dart on Chrome in debug mode...
Finished with error: Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 62968

**Comment by TahaTesser** [comment]
Duplicate of [#53338](https://github.com/flutter/flutter/issues/53338)
