### ISSUE TITLE
[engine] Old PRs breaking fuchsia devices.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#55123]
Old PR older than a month are running presubmit tests with old versions of fuchsia/run_tests.sh scripts which break fuchsia devices. We may need to fetch/merge to avoid this problem.

This is an example:
 
https://github.com/flutter/engine/pull/17015

@stuartmorgan @Kurun-pan

**Comment by stuartmorgan** [comment]
Is there a general solution to this problem? We can push a merge to that specific PR, but anyone can submit PRs against any version.

E.g., if there is a know bad range of revisions that break devices, shouldn't the bot infrastructure blacklist them?

**Comment by godofredoc** [comment]
I haven't identified a way to prevent the problem but we are expecting any commits after https://github.com/flutter/engine/pull/17716/commits/c52ccd32211cc8b1fadc091f3ec59ae210dd71d8 not to have this problem anymore.

**Comment by digiter** [comment]
Triage: we haven't seen this happen for a while.
