### ISSUE TITLE
 Can't get new state in BlocListener due to localizations

### ISSUE THREAD

**Issue by don-prog** [flutter/flutter#55129]
Hello.
I have an application with [bloc package](https://github.com/felangel/bloc) and localizations. My app loads `SplashPage` until everything is ready, and after that it changes the page. All fine and obvious without localizations(without `supportedLocales`, `localizationsDelegates` and `localeResolutionCallback` in `MaterialApp`), but when it is turned on, a new state will not be received and the `SplashPage` will not change to the `FirstPage`.
Please check [minimal working example here.](https://github.com/don-prog/flutter_localization_bloc_bug)
What is the problem and how can I fix it?

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by don-prog** [comment]
@jonahwilliams why are you sure that this is not some kind of bug? Also, I already tried to ask question on SO and unfortunately I didn't get any result.
