### ISSUE TITLE
url_launcher forceSafariVC set to true does not work in iOS

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#55121]
## Steps to Reproduce

1. url_launcher version 5.4.2 (latest)
2. Call ```await launch(URL, forceSafariVC: true)```
3. It should open the URL in iOS Safari, instead, it opens in the app.

**Expected results:** 
It should open the URL link to the native Safari browser

**Actual results:** 
It opens the URL link inside the app

Sample Code:
```
String url = 'https://apple.com';
if (await canLaunch(url)) {
    await launch(url, forceSafariVC: true);
} else {
  throw 'Could not launch $url';
}
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/marco/Development/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/marco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • D9C04753-CBD3-43F7-8AD8-0F70963082E8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by imeDevelopers** [comment]
can you provide screenshot ?

**Comment by Sun3** [comment]
The first image shows the originating iOS app page being moved away as the in-app browser is starting to show:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-18 at 16 45 59](https://user-images.githubusercontent.com/4562374/79670936-5a660600-8194-11ea-863f-611a2f83cb86.png)

The second image shows the in-app browser with the page loaded:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-18 at 16 45 11](https://user-images.githubusercontent.com/4562374/79670946-6eaa0300-8194-11ea-946d-3f5d4646fbe2.png)

By using the ```await launch(URL, forceSafariVC: true)``` it should have opened the Safari browser outside of the app.

Thanks

**Comment by imeDevelopers** [comment]
Give us url example and your project package name ..

**Comment by Sun3** [comment]
This issue persist no matter which URL we use.

The following is the code we are using, you can substitute the URL with anyone you like. https://microsoft.com, https://google.com and so on. The flag ```forceSafariVC: true``` does not make a difference, it always opens in the app instead of launching the iOS device Safari browser. Apple does not allow to open up links inside app to any websites that might take donations, they require for the websites to open externally to the Safari browser ( or which other default browser the user has setup).

```
String url = 'https://apple.com';
if (await canLaunch(url)) {
    await launch(url, forceSafariVC: true);
} else {
  throw 'Could not launch $url';
}
```

Thank you

**Comment by Sun3** [comment]
It's all working, I was passing the value of ```true``` instead of ```false```

But what is weird, the default value is ```false``` and it was still not launching to Safari Browser, but once I forced the value to be ```forceSafariVC: false``` it worked.
