### ISSUE TITLE
How to track user journey in a single-page Flutter WEB app?

### ISSUE THREAD

**Issue by Leostina** [flutter/flutter#55137]
Hi
I am new to google analytics, want to track the user's movement in my single-page Flutter app. The app consists of 6 pages using PageView. Specifically, I want to know how long a user stays on each page and their mouse click-events / movements. I tried this https://pub.dev/packages/google_tag_manager but somehow no events are tracked in my analytics account (failed).

Here is how I implemented

```
import 'package:google_tag_manager/google_tag_manager.dart' as gtm;

class HomeView extends StatefulWidget {
...
}

class HomeViewState extends State<HomeView> with TickerProviderStateMixin  {
  ...
  Widget build(BuildContext context ) {
    homePageLanded();
    ...
  }
  void homePageLanded(){
    gtm.pushEvent('homeView-landed');
  }
}
```

The code above is how I tried to log the event of users land on the Homeview. Similarily I did the same to the other views.

This is the main structure of the site.

```
PageView(
    physics: physics,
    pageSnapping: true,
    scrollDirection: Axis.vertical,
    controller: _pageController,
    children: <Widget>[
        HomeView(utilities, _pageController),
        ViewTwo(utilities, _pageController),
        ViewThree(utilities, _pageController),
        ViewFour(utilities, _pageController),
        ViewFive(utilities, _pageController),
    ]
),
```

Are there any other steps required like setting up in Google Analytics?

Thank you in advance!!

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
