### ISSUE TITLE
Flutter maven repository (https://storage.googleapis.com/download.flutter.io) could be inaccessible in China

### ISSUE THREAD

**Issue by chenglu** [flutter/flutter#55134]
Hi Team:

The existing Flutter Maven repository: http://download.flutter.io or https://storage.googleapis.com/download.flutter.io couldn't be easily accessed in China now. I was wondering if there's any chance to migrate this Flutter Maven repository to google() since the maven.google.com is working for China, or using the `FLUTTER_STORAGE_BASE_URL` for instead? 

Thanks to @liudonghua123 for giving this feedback.
Cc/ @xster @InMatrix @zoeyfan.

Thanks!

**Comment by zoeyfan** [comment]
@chenglu thanks for filing this issue. I have a few follow up questions:
1. Would you be able to articulate what people are trying to accomplish with download.flutter.io? Basically, what part of the developer workflow is being blocked?
2. Is this a recent regression or it has been there for a long time?
3. How many customers are currently being blocked by this? Is there a temp workaround?

**Comment by xster** [comment]
Discussed offline. 
It's a problem now because https://storage.googleapis.com access behind GFW is finicky and our https://storage.googleapis.com/download.flutter.io access in Flutter tools and in add-to-app documentation isn't gated behind the existing pattern of using `FLUTTER_STORAGE_BASE_URL`. 

If access is decreasing, we should resolve this soon. There are 2 options:

1. Make Android engine maven access in https://storage.googleapis.com/download.flutter.io read FLUTTER_STORAGE_BASE_URL. For full-Flutter apps, this involves a new Flutter framework version to fix it. For add-to-app, it could be to simply edit the instructions for https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar to point out mirrors in China.
2. Upload Android engines to maven.google.com instead of our own cloud storage. But we'd have to migrate all existing users to the new URL. 

cc @blasten. I'm leaning towards option 1 unless I'm missing some pro/cons.

**Comment by xster** [comment]
oh just noticed @blasten mentioning that maven.google.com seems to be geared towards artifacts built within the google build system. Our engines are built on "external" chromium infrastructure. Which makes option 2 harder even.

**Comment by blasten** [comment]
I'm not sure what is special about `FLUTTER_STORAGE_BASE_URL`. How did `https://storage.googleapis.com/flutter_infra` become whitelisted? Is it possible that a different set of users are hitting a different set of whitelisted hosts/urls?

**Comment by xster** [comment]
`https://storage.googleapis.com/flutter_infra` is not whitelisted. 
We manually asked users to insert a replacement for it in https://flutter.dev/community/china which is then read by most places in the tools. I forgot about this 😅 and we didn't make our maven url account for this user toggle in the form of `FLUTTER_STORAGE_BASE_URL`. 

My understanding is that the GFW blocking is not 100% deterministic and is just blocking `https://storage.googleapis.com/` more recently, increasing the need for users to use a mirror such as via https://flutter.dev/community/china.

**Comment by chenglu** [comment]
Hi Zoey: The GCS services seem to be blocked recently, and it affects the services built on it: https://storage.googleapis.com/download.flutter.io and http://download.flutter.io, like @xster said.

The Flutter maven repository is the repository that developers were relying on to build Flutter engine about add-to-app, see [the document here](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar), @xster, please correct me if I got it wrong.

The Android developers who use the add-to-app solution to use flutter in their existing app will be affected, the temp workaround which I am doing right now is to add info in the flutter.cn docs site, suggested the developer use China mirror for instead.

@zoeyfan 

Thanks!

**Comment by xster** [comment]
Small correction: all Flutter developers on Android get their engine from http://download.flutter.io since 1.12.13 and https://storage.googleapis.com/download.flutter.io since 1.15.13

**Comment by blasten** [comment]
ah - that's good to know. I wasn't aware of https://flutter.dev/community/china.

GMaven doesn't require a migration. Although, I'm not sure if maven.google.com isn't blocked as well.

**Comment by xster** [comment]
@chenglu was saying that `maven.google.com` isn't blocked and is especially maintained in accordance with the content regulation. Good point on google maven migration since it's all pulled by the default template (I think you're saying). So the remaining challenge is uploading to gmaven from luci?

**Comment by chenglu** [comment]
@blasten @xster Please see the results from [this page](http://ping.chinaz.com/maven.google.com)--green means acess well, 
`maven.google.com` works well since the China users were going through the Google China DataCenters to accessing this service.

**Comment by blasten** [comment]
The alternative is to only upload beta releases to `maven.google.com` as part of that release process.  Unfortunately, it won't work for users on `master` due to infra limitations. For those on `master`, they can continue to use the cloud bucket. 

I think it's a tradeoff between convenience vs maintenance cost.

**Comment by liudonghua123** [comment]
@blasten Why not add FLUTTER_STORAGE_BASE_URL support for `<flutter_home>/packages/flutter_tools/gradle/flutter.gradle`, instead of hardcode `MAVEN_REPO`.

**Comment by blasten** [comment]
`FLUTTER_STORAGE_BASE_URL` is overloaded and I was told it was going to be deprecated.

**Comment by xster** [comment]
I may have missed another conversation but FLUTTER_STORAGE_BASE_URL should still be the primary way for China users to access our cache artifacts on storage.googleapis.com. 

Accounting for  FLUTTER_STORAGE_BASE_URL in our maven repository url is what I'm proposing in option 1. Manually uploading select engine builds to gmaven might be a bigger con than having people move to a framework which reads FLUTTER_STORAGE_BASE_URL for maven.

**Comment by chenglu** [comment]
> `FLUTTER_STORAGE_BASE_URL` is overloaded and I was told it was going to be deprecated.

@blasten: Oh, sorry to hear that, wish to have a smooth plan for doing so.

@liudonghua123: `<flutter_home>/packages/flutter_tools/gradle/flutter.gradle` is a static file, and it might not have the ability to read the System Environment ;-)

**Comment by liudonghua123** [comment]
@chenglu The `MAVEN_REPO` in `<flutter_home>/packages/flutter_tools/gradle/flutter.gradle` is `private static` indeed, but we only do the checking `FLUTTER_STORAGE_BASE_URL`  environement in the only usage places in `addFlutterDependencies`. 

Maybe the following changes will work.

![image](https://user-images.githubusercontent.com/2276718/79835419-47944100-83e1-11ea-9a55-106200ebb34a.png)

**Comment by liudonghua123** [comment]
Before the above changes, I upgrade flutter, build a previous project and failed with `io.flutter.x86_64-....` could not resolve. Then I tried again with these changes, then it was ok. I am using master channel of flutter and have set `FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn` env.

**Comment by xster** [comment]
discussed offline. Yes, what @liudonghua123 is describing is the agreed approach.

**Comment by xster** [comment]
Flutter tool should now pull the Android engine maven artifacts from your proxy now on master.

**Comment by liudonghua123** [comment]
Nice work, thanks! 😄

**Comment by chenglu** [comment]
👍

**Comment by xster** [comment]
@pcsosinski cherry-pick note: this was already not in 1.12 but AFAIU, the severity comes from the fact that it's increasingly harder to access storage.googleapis.com in China recently. 

This potentially affects all full-Flutter and add-to-app Android developers in China.

**Comment by pcsosinski** [comment]
@xster @chenglu which commits would we need for 1.17?

**Comment by pcsosinski** [comment]
@tvolkert fyi

**Comment by xster** [comment]
https://github.com/flutter/flutter/commit/f6b47a5f35c38547f2881ebc5bea1e9f5046d295
+
https://github.com/flutter/flutter/commit/793e6a48a1e679074da7f47813c138abb2f0a6f6

can be squashed

**Comment by pcsosinski** [comment]
CP decision 5/12/20: pick into 1.18 beta for now.

**Comment by tvolkert** [comment]
@pcsosinski have we seen any indication that the cherry-picks caused any issues in 1.18?

**Comment by pcsosinski** [comment]
not that I'm aware of.  @xster ?

**Comment by xster** [comment]
I haven't heard of any issues either. Though I would have also expected this issue to be upvoted through the roof if the great firewall clamped down more. I'd just keep this patch in 1.18. @chenglu can you keep us updated if this does become more severe in China for us to cherry pick into 1.17?

**Comment by chenglu** [comment]
@xster 
Sure, I will keep my eyes on the feedback from the China community. 
But from my perspective, I’d like to vote +1 to cherry-pick this into 1.17 since you know the network issues in China will always depending on the weather; it’s better to have the mirror here instead of hardcode it.

**Comment by pcsosinski** [comment]
decision made to not hotfix 1.17 for this.
