### ISSUE TITLE
Gradle crashes on flutter run for new projects

### ISSUE THREAD

**Issue by Alloco225** [flutter/flutter#55131]
Hello

Every time I create and run a new flutter project, gradle crashes :/

# Steps to Reproduce

1. Create a new flutter project
2. Run the project

**Actual results:** 

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 52s
[!] Gradle threw an error while trying to update itself. Retrying the update...

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

## This is what flutter doctor says 

```console
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [version 10.0.18362.657], locale fr-FR)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (10 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\NovemberAjax\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by imeDevelopers** [comment]
run command `flutter clean` ...

and i advice you to change your channel to master using this code `flutter channel master` ..

and then upgrade your flutter using this code `flutter upgrade` ...

and try again & let me know news ..

**Comment by iapicca** [comment]
Hi @Alloco225 
can you please run `flutter upgrade --force`
and provide your updated `flutter doctor -v` 
and your `flutter run --verbose` 
Thank you

**Comment by Alloco225** [comment]
Actually I deleted all the flutter and gradle installation folders in safe mode and reinstalled the whole thing, it fixed the issue.

**Comment by Alloco225** [comment]
The same problem is coming back..
I could run the project after I reinstalled everything but I just created a new project and gradle throws this error :



## Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)



## Flutter doctor :

[√] Flutter (Channel master, v1.18.0-6.0.pre.83, on Microsoft Windows [version 10.0.18362.657], locale fr-FR)
    • Flutter version 1.18.0-6.0.pre.83 at C:\src\flutter
    • Framework revision 8e5b575174 (23 hours ago), 2020-04-19 17:20:01 -0400
    • Engine revision 2b75c6d111
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 4814f000de)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\NovemberAjax\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Infinix X559C             • 027451079P000445 • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554    • android-x86 • Android 10 (API 29) (emulator)

**Comment by TahaTesser** [comment]
Hu @Alloco225 
Can you please check possible [solution](https://github.com/flutter/flutter/issues/51690#issuecomment-603988891)
Thank you

**Comment by Alloco225** [comment]
Hello @TahaTesser 
I checked the solution but I can't find the **gradle-wrapper.properties** file in any of my file system.

- C:\Users\{username}\.gradle\wrapper only has a "dists" folder containing "gradle-5.6.2-all"

- C:\Program Files\Android\Android Studio\plugins\gradle only has a "lib" folder containing "gradle-wrapper-5.2.1-sp1.jar"

I can't find the **gradle-wrapper.properties**

**Comment by Alloco225** [comment]
I downloaded the latest version of gradle 6.3 but can't get flutter or android studio to use it, it always downloads the 5.6.2 version causing the crash...

**Comment by imeDevelopers** [comment]
This file exist in you project folder inside android folder ..

**Comment by Alloco225** [comment]
Ok so i changed the gradle-wrapper.properties and after 10 long minutes assembleDebug finally compiled the apk but now the flutter commands do not respond.

When I type  flutter doctor -v in command line nothing happens..

**Comment by TahaTesser** [comment]
Hi @Alloco225 
Since application compiled and it takes time to load new gradle version, it depends on speed of the internet and disk speed of your computer. 
Up on testing ` flutter doctor -v` in terminal in Android Studio and system terminal, found no issue. It's also not related to gradle

given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by Alloco225** [comment]
Hello @TahaTesser 
The issue isn't solved. Changing the gradle distribution url worked in the project but it doesn't in new projects.
I tried flutter clean but nothing works..
Gradle crashes "while trying to update itself" on the new projects whether the distrution url is 5.6.2 or 5.6.3.

**This is error it throws :**

`Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 6s
[!] Gradle threw an error while trying to update itself. Retrying the update...

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform artifact 'aapt2-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860)' to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\NovemberAjax\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.FileNotFoundException: File does not exist: C:\Users\NovemberAjax\.gradle\caches\transforms-2\files-2.1\4b75d0e191b0ddd15d720775317f913a\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by Alloco225** [comment]
Thank you all for the precious help
