### ISSUE TITLE
Windows plugin demo or tutorial (or documentation)

### ISSUE THREAD

**Issue by softmarshmallow** [flutter/flutter#55143]
we can easily create plugins for ios(& mac) or android, but it is verry hard to find any reference how to make plugins for windows or linux.

i would love to contribute on flutter desktop ecosystem. but it seems impossible for me to start.
can i get any official document updates or tutorial for creating windows/linux plugins?

**Comment by stuartmorgan** [comment]
Formal documentation will come when the development is further along; the API isn't finalized yet, and neither platform has reached alpha yet.

In the meantime, the general approach is the same as for any other platform: `flutter create -t plugin your_plugin_name_here`, and then modify the code. The C++ API used by the template has header documentation, and the classes generally correspond to classes on other platforms so iOS and Android examples should be useful. You can also look at the Windows implementations in the flutter-desktop-embedding repository for more examples of using the APIs.

If you have specific problems with the APIs you can file issues about them, but closing this as not providing tutorials or other flutter.dev documentation of Windows and Linux plugin development is currently a deliberate choice.

**Comment by softmarshmallow** [comment]
thanks for the kind reply 😀
