### ISSUE TITLE
Back arrow hard to see with certain backgrounds

### ISSUE THREAD

**Issue by gbracha** [flutter/flutter#5514]
## Steps to Reproduce

Note: This isn't really a bug - more of a concern/issue

View the "Seared Sesame fish" recipe in the Pesto app.

Now, look for the back arrow to go back to the app's main screen. The arrow is hard to see, because it blends into the image behind it. The question is: is this simply a defect in the design of the app? What could the designer have done differently? Can they specify the arrow color vary so it stands out?
## Flutter Doctor

No need, the app works
## Logs and Crash Reports

None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by sethladd** [comment]
Thanks for the feedback!

I wonder if we can or should draw a shadow at the top, to ensure proper contrast?

**Comment by HansMuller** [comment]
Although I don't think it would make sense for the flexible space bar to do that by default, the Pesto app probably should draw a shadow.  The contacts demo does this, for the same reason.

**Comment by sethladd** [comment]
We have a gradient now.
