### ISSUE TITLE
C:\Users\lenovo>flutter doctor --android-licenses  Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli

### ISSUE THREAD

**Issue by Bhavna6m17** [flutter/flutter#55140]
`C:\Users\lenovo>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.17.0 at C:\src\flutter\flutter
    • Framework revision d3ed9ec945 (13 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Redmi 4 • 5e743cb7d240 • android-arm64 • Android 7.1.2 (API 25)`
I have installed androidsdktools(obsolete)
but i give error . please help me

**Comment by iapicca** [comment]
Hi @Bhavna6m17 
please try this [workaround](https://github.com/flutter/flutter/issues/51712#issuecomment-600318840)

I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
