### ISSUE TITLE
[flutter] is there any possible way to play sound on windows?

### ISSUE THREAD

**Issue by softmarshmallow** [flutter/flutter#55151]
is there any possible currently open way to play sound on windows.
literally i dont care which way. it just has to play simple sound, local/remote idk.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
