### ISSUE TITLE
type 'QuerySnapshot' is not a subtype of type 'DocumentSnapshot'

### ISSUE THREAD

**Issue by jorgecuello-montanez** [flutter/flutter#55159]
Soy nuevo en Flutter y estoy intentanto obtener los resultados de un documento de firestore, me marca esto "type 'QuerySnapshot' is not a subtype of type 'DocumentSnapshot'"

return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: StreamBuilder(
        stream: Firestore.instance.collection('requests_partners').document(user.uid).collection('requests_partners').snapshots(),
          builder: (context, snapshot){
          if(snapshot.hasError){
            return Text('Error ${snapshot.error}');
          }else{
            return Container(
              height: MediaQuery.of(context).size.height*0.2,
              width: MediaQuery.of(context).size.width*0.5,
              child: ListView.builder(
                padding: EdgeInsets.all(10.0),
                
                itemBuilder: (context, index){
                  final DocumentSnapshot doc = snapshot.data;
                  return Container(
                    height: MediaQuery.of(context).size.height*0.1,
                    width: MediaQuery.of(context).size.width * 0.5,
                    child: Card(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: <Widget>[
                            Row(
                              children: <Widget>[
                              Expanded(
                                    child: InkWell(
                                  child: Container(
                                    child: Text("${doc.data['send_uid']},"),
                                  height: 30.0,
                                  width: MediaQuery.of(context).size.height*0.1,
                                  )
                                ),
                              )
                            ],)
                          ],
                        ),
                      ),
                    ),
                  );
                }),
            );
              

          }
        }),
    );

Este el codigo que me marca el error

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
