### ISSUE TITLE
Development setup is very hard.   to run flutter  apps  becuse of  android-studio  incudes   emulator .  GenyMotion  Given emulator separate run  emulator for developer  it not easy  ways to do  in flutter  with virtual device geny-motion. not given  tutorials in flutter site.   why not we can write  in sublime or vscode  editor  fluttter  program  and  run virtual emulator. without android-studio.    why  should i download  amdroid-studo  heavy file .. it not able  run properly in linux  ubuto system ...  I am gettin build issue 

### ISSUE THREAD

**Issue by rsurendraidexcel** [flutter/flutter#55155]
android-studio bundle editor . it is huge file .. it not portable  in all device linux ubutu. i

i am getting issue build  flutter app in  vitual device geny motion ,  i hate android-studio included emualtor  very very heavy file while donloading edutor  its take full  night and days

![error](https://user-images.githubusercontent.com/7713535/79692930-95943200-8285-11ea-8a56-3b3b53214911.png)

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
