### ISSUE TITLE
"flutter run --release" and "flutter install" failed to install apk to cell phone

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#5515]
### Case 1

Just followed the doc

```
cd $FLUTTER_ROOT/examples/flutter_gallery
flutter upgrade
flutter run --release
```

**Result:** It will fail with error msg:

```
Error type 3
Error: Activity class {io.flutter.gallery/org.domokit.sky.shell.SkyActivity} does not exist.
Error running application on Letv X501.
```

The app is not installed in my phone.
### Case 2

Execute:

```
flutter build apk --release && flutter install
```

**Result:** The app is **_failed**_ to be installed in my phone too.
No error message. The apk file is built successfully. The output ends with the line "Installing app.apk to Letv X501...", where Letv X501 is my test cell phone.
### Case 3

If I copy the apk file from build directory to my cell phone manually and install the apk manually. The app can be installed and run successfully.
### Case 4

After the app is installed successfully in the test cell phone manually, execute `flutter run --release` again. The app can be triggered and open successfully in my phone.
## Flutter Doctor

$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/user/flutter
    • Framework revision 9a0a0d9903 (7 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 21.1.1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-21, build-tools 21.1.1
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[-] Atom - a lightweight development environment for Flutter
    • flutter plugin not installed; this adds Flutter specific functionality to Atom.
      Install the plugin from Atom or run 'apm install flutter'.
    • dartlang plugin not installed; this adds Dart specific functionality to Atom.
      Install the plugin from Atom or run 'apm install dartlang'.
## Logs and Crash Reports

```
$ adb devices
List of devices attached 
MFJ7OZBEY5VCUW6D    device
```

```
   0 ms • Built build/app.flx.
   4 ms • Starting bundle for Letv X501.
   0 ms • Letv X501 startBundle
1328 ms • /home/user/Android/Sdk/platform-tools/adb -s MFJ7OZBEY5VCUW6D push build/app.flx /data/local/tmp/dev.flx
   0 ms • Exit code 0 from: /home/user/Android/Sdk/platform-tools/adb -s MFJ7OZBEY5VCUW6D push build/app.flx /data/local/tmp/dev.flx
 647 ms • /home/user/Android/Sdk/platform-tools/adb -s MFJ7OZBEY5VCUW6D shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true io.flutter.gallery/org.domokit.sky.shell.SkyActivity
   0 ms • Exit code 0 from: /home/user/Android/Sdk/platform-tools/adb -s MFJ7OZBEY5VCUW6D shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true io.flutter.gallery/org.domokit.sky.shell.SkyActivity
   0 ms • Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=io.flutter.gallery/org.domokit.sky.shell.SkyActivity (has extras) }
          Error type 3
          Error: Activity class {io.flutter.gallery/org.domokit.sky.shell.SkyActivity} does not exist.
   0 ms • Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=io.flutter.gallery/org.domokit.sky.shell.SkyActivity (has extras) }
          Error type 3
          Error: Activity class {io.flutter.gallery/org.domokit.sky.shell.SkyActivity} does not exist.
   3 ms • Error running application on Letv X501.
   1 ms • 'flutter run' took 41825ms; exiting with code 2.
   0 ms • ensureAnalyticsSent: 251ms
```

**Comment by zoechi** [comment]
Is this a dup of #9253 (or vice versa)?

**Comment by sgon00** [comment]
I think this is similar to the bug #19640 I opened recently. I have 6 android mobiles and it's working fine on 2 of them. I am OK to use the two working ones for development. I think this is a bug belongs to gradle insead of flutter so I am closing it for now. Cheers.

**Comment by wbdsnx** [comment]
$ flutter build apk
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleRelease'...
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:1: Error: Variables must be declared using th'const', 'final', 'var' or a type name.
compiler message: Try adding the name of the type of the variable or the keyword 'var'.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message: ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:1: Error: Expected an identifier, but got 'mi
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message: ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:1: Error: Expected ';' after this.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message: ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:1: Error: Expected a declaration, but got 'mi
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message: ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:34: Error: Expected ';' after this.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:                                  ^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:74:5: Error: Expected ';' after this.
compiler message:     implements ChartStateBehavior {
compiler message:     ^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:74:16: Error: A function declaration needs an ex of parameters.
compiler message: Try adding a parameter list to the function declaration.
compiler message:     implements ChartStateBehavior {
compiler message:                ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_and_zoom_behavior.dart:63:36: Error: The type 'FlutterPanBehavan't be mixed in.
compiler message: class FlutterPanAndZoomBehavior<D> extends common.PanAndZoomBehavior<D>
compiler message:                                    ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:68:7: Error: The type 'FlutterPanBehaviorMixin' xed in.
compiler message: class FlutterPanBehavior<D> = common.PanBehavior<D>
compiler message:       ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_and_zoom_behavior.dart:64:10: Error: Type 'FlutterPanBehaviorMound.
compiler message:     with FlutterPanBehaviorMixin {}
compiler message:          ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:69:10: Error: Type 'FlutterPanBehaviorMixin' not
compiler message:     with FlutterPanBehaviorMixin;
compiler message:          ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:7: Error: 'FlutterPanBehaviorMixin' expects 0ents.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:       ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:56: Error: Type 'D' not found.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:                                                        ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:31: Error: 'D' isn't a type.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:                               ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:7: Error: 'FlutterPanBehaviorMixin' isn't a t
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:       ^^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:73:56: Error: 'D' isn't a type.
compiler message: mixin FlutterPanBehaviorMixin<D> on common.PanBehavior<D>
compiler message:                                                        ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:77:3: Error: Unexpected token 'set'.
compiler message:   set chartState(BaseChartState chartState) {
compiler message:   ^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:81:57: Error: Expected identifier, but got 'this
compiler message:     _flingAnimator = _chartState.getAnimationController(this);
compiler message:                                                         ^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:81:5: Error: Setter not found: '_flingAnimator'.
compiler message:     _flingAnimator = _chartState.getAnimationController(this);
compiler message:     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:82:33: Error: Getter not found: '_onFlingTick'.
compiler message:     _flingAnimator?.addListener(_onFlingTick);
compiler message:                                 ^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:82:5: Error: Getter not found: '_flingAnimator'.
compiler message:     _flingAnimator?.addListener(_onFlingTick);
compiler message:     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:85:23: Error: Can't declare '_flingAnimator' bec already used in this scope.
compiler message:   AnimationController _flingAnimator;
compiler message:                       ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:81:5: Error: Previous use of '_flingAnimator'.
compiler message:     _flingAnimator = _chartState.getAnimationController(this);
compiler message:     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:92:3: Error: Can't have modifier 'static' here.
compiler message: Try removing 'static'.
compiler message:   static const flingDistanceMultiplier = 0.15;
compiler message:   ^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:93:3: Error: Can't have modifier 'static' here.
compiler message: Try removing 'static'.
compiler message:   static const flingDeceleratorFactor = 1.0;
compiler message:   ^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:94:3: Error: Can't have modifier 'static' here.
compiler message: Try removing 'static'.
compiler message:   static const flingDurationMultiplier = 0.15;
compiler message:   ^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:95:3: Error: Can't have modifier 'static' here.
compiler message: Try removing 'static'.
compiler message:   static const minimumFlingVelocity = 300.0;
compiler message:   ^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:98:31: Error: 'D' isn't a type.
compiler message:   removeFrom(common.BaseChart<D> chart) {
compiler message:                               ^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:99:5: Error: Method not found: 'stopFlingAnimati
compiler message:     stopFlingAnimation();
compiler message:     ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:100:44: Error: Expected identifier, but got 'thi
compiler message:     _chartState.disposeAnimationController(this);
compiler message:                                            ^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:101:5: Error: Setter not found: '_flingAnimator'
compiler message:     _flingAnimator = null;
compiler message:     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:102:5: Error: Expected identifier, but got 'supe
compiler message:     super.removeFrom(chart);
compiler message:     ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:107:5: Error: Expected identifier, but got 'supe
compiler message:     super.onTapTest(chartPoint);
compiler message:     ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:109:5: Error: Method not found: 'stopFlingAnimat
compiler message:     stopFlingAnimation();
compiler message:     ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:117:9: Error: Getter not found: 'isPanning'.
compiler message:     if (isPanning) {
compiler message:         ^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:120:9: Error: Method not found: 'onPanEnd'.
compiler message:         onPanEnd();
compiler message:         ^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:124:7: Error: Method not found: '_startFling'.
compiler message:       _startFling(pixelsPerSec);
compiler message:       ^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:127:12: Error: Expected identifier, but got 'sup
compiler message:     return super.onDragEnd(localPosition, scale, pixelsPerSec);
compiler message:            ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:131:8: Error: Can't declare '_startFling' becausready used in this scope.
compiler message:   void _startFling(double pixelsPerSec) {
compiler message:        ^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:124:7: Error: Previous use of '_startFling'.
compiler message:       _startFling(pixelsPerSec);
compiler message:       ^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:132:24: Error: Getter not found: 'chart'.
compiler message:     final domainAxis = chart.domainAxis;
compiler message:                        ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:142:5: Error: Getter not found: '_flingAnimator'
compiler message:     _flingAnimator
compiler message:     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:154:8: Error: Can't declare '_onFlingTick' becaulready used in this scope.
compiler message:   void _onFlingTick() {
compiler message:        ^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:82:33: Error: Previous use of '_onFlingTick'.
compiler message:     _flingAnimator?.addListener(_onFlingTick);
compiler message:                                 ^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:159:21: Error: Getter not found: '_flingAnimator
compiler message:     final percent = _flingAnimator.value;
compiler message:                     ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:164:24: Error: Getter not found: 'chart'.
compiler message:     final domainAxis = chart.domainAxis;
compiler message:                        ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:168:24: Error: Getter not found: 'chart'.
compiler message:         drawAreaWidth: chart.drawAreaBounds.width);
compiler message:                        ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:171:7: Error: Method not found: 'stopFlingAnimat
compiler message:       stopFlingAnimation();
compiler message:       ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:172:7: Error: Method not found: 'onPanEnd'.
compiler message:       onPanEnd();
compiler message:       ^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:173:7: Error: Getter not found: 'chart'.
compiler message:       chart.redraw();
compiler message:       ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:175:7: Error: Getter not found: 'chart'.
compiler message:       chart.redraw(skipAnimation: true, skipLayout: true);
compiler message:       ^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:180:8: Error: Can't declare 'stopFlingAnimation' was already used in this scope.
compiler message:   void stopFlingAnimation() {
compiler message:        ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:99:5: Error: Previous use of 'stopFlingAnimation
compiler message:     stopFlingAnimation();
compiler message:     ^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_behavior.dart:183:7: Error: Getter not found: '_flingAnimator'
compiler message:       _flingAnimator?.stop();
compiler message:       ^^^^^^^^^^^^^^
compiler message: file:///D:/workspace/flutter_windows_v0.8.2-beta/flutter/.pub-cache/hosted/pub.flutter-s_flutter-0.5.0/lib/src/behaviors/zoom/pan_and_zoom_behavior.dart:1: Error: The superclass, '_FlutterPanAior&PanAndZoomBehavior&FlutterPanBehaviorMixin', has no unnamed constructor that takes no arguments.
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\workspace\flutter_windows_v0.8.2-beta\flutter\packages\flutter_tools\gradle\flutter.gradle' li

* What went wrong:
Execution failed for task ':app:flutterBuildRelease'.
> Process 'command 'D:\workspace\flutter_windows_v0.8.2-beta\flutter\bin\flutter.bat'' finished with non-alue 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ouith --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Gradle build failed: 1

**Comment by wbdsnx** [comment]
Can you help me?

**Comment by zoechi** [comment]
@wbdsnx looks like your Flutter version is outdated.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
