### ISSUE TITLE
Flutter Http Headers Have Inconsistent names

### ISSUE THREAD

**Issue by DenisBarzanov** [flutter/flutter#55163]
I have an app that makes requests here and there and it doesn't work both on Web and on Android, because the header names are inconsistent. I have to do name checks with the `??` operator.

```dart
final response = await _client.post(
  'http://100.115.92.198:8080/login',
  body: jsonEncode({
    'email': email,
    'password': password,
  }),
  headers: {HttpHeaders.contentTypeHeader: 'application/json'},
);

switch (response.statusCode) {
  case 200:
    final authToken = response.headers['authorization'];
    prefs.setString('authToken', authToken);
    userSubject.add(authToken.toUser());
    return;
  default:
    throw Exception('Unknown error');
}
```

## Web
![Screenshot 2020-04-19 at 23 04 02](https://user-images.githubusercontent.com/29101425/79698659-f8d89100-8292-11ea-9aaf-428ead71d2bf.png)

## Android 
![Screenshot 2020-04-19 at 23 04 57](https://user-images.githubusercontent.com/29101425/79698667-08f07080-8293-11ea-99b9-87ab05d6d408.png)

As you can see the names are inconsistent ("Authorization" vs "authorization").
On the web it used to work with "Authorization", but now it is not showing in the response headers either. 
It shows me 
## Web
![Screenshot 2020-04-19 at 23 24 51](https://user-images.githubusercontent.com/29101425/79699001-350cf100-8295-11ea-8c6a-2cbff9eedf27.png)

while in the network tab I have
## Web
![Screenshot 2020-04-19 at 23 25 14](https://user-images.githubusercontent.com/29101425/79699009-40601c80-8295-11ea-9e5b-2c795d9bfb06.png)

As you can see, there are a lot more response headers that I don't see in the map.

On Android on the other hand it is always "authorization" and it works.
Complete madness. This is strange, because I developed some of my app while compiling for the Web and when I switched to Android (dev experience) I started seeing this strange behavior.

**Comment by TahaTesser** [comment]
Hi @DenisBarzanov 
can you please provide your `flutter doctor -v`? Which version of `http` are you using?
Thank you

**Comment by DenisBarzanov** [comment]
### http package version
I am using the latest version of http (0.12.0+4). I have it left out blank: `http: `

### `flutter doctor -v`
```
[✓] Flutter (Channel dev, v1.18.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0 at /home/denisbarzanov2002/flutter
    • Framework revision 8f7327f83a (13 days ago), 2020-04-06
      22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 29.0.2)
    • Android SDK at /home/denisbarzanov2002/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/denisbarzanov2002/idea-IU-192.7142.36
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7402

[✓] VS Code (version 1.44.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome
      79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @DenisBarzanov 
Can you please upgrade to latest `master` channel and try again?
Thank you

**Comment by DenisBarzanov** [comment]
Tried it on `master`, same thing. I will try it on `beta` later. 
```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-6.0.pre.83 at /home/denisbarzanov2002/flutter
    • Framework revision 8e5b575174 (17 hours ago), 2020-04-19 17:20:01 -0400
    • Engine revision 2b75c6d111
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 4814f000de)
```

Still the same result. In the browser I see like 20 response headers and in the app I see just
```
{cache-control: no-cache, no-store, max-age=0, must-revalidate, content-length: 0, expires: 0, pragma: no-cache}
```

**Comment by TahaTesser** [comment]
Hi @DenisBarzanov 
This looks like http library dart issue, can you please raise this issue  on their [GitHub](https://github.com/dart-lang/sdk/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by DenisBarzanov** [comment]
Moved to [here](https://github.com/dart-lang/http/issues/409)
