### ISSUE TITLE
`SelectableText` should allow overriding 'EditableText.selectionControls`

### ISSUE THREAD

**Issue by stefanrusek** [flutter/flutter#55177]
## Use case

While copy/paste are often sufficient, many times we want to expose additionally functionality when selecting text. For example, an ebook app would expose the ability to highlight text.

## Proposal

`SelectableText` should have a `textSelectionControls` constructor parameter. If specified, it should be passed to the chile `EditableText` widget.

**Comment by justinmc** [comment]
This is now possible with https://github.com/flutter/flutter/pull/66785.
