### ISSUE TITLE
Middle slider doesn't work

### ISSUE THREAD

**Issue by gbracha** [flutter/flutter#5517]
## Steps to Reproduce

Check the the sliders in the gallery. On my Nexus 5X, the middle one is all grey and does nothing. Ic

## Flutter Doctor

No need, the app works

## Logs and Crash Reports

None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by gbracha** [comment]
If I've misunderstood and the middle slider is just an illustration, I apologize. But it's unclear at best.

**Comment by Hixie** [comment]
It's demonstrating that sliders can be disabled.

**Comment by eseidelGoogle** [comment]
It seems pretty reasonable to give the sliders labels.  @HansMuller could do something prettier, but this is what throwing 3 Text elements in there does:
![simulator screen shot aug 19 2016 2 27 03 pm](https://cloud.githubusercontent.com/assets/11857803/17824824/10e10934-6619-11e6-8a1c-c53c2ce04341.png)

**Comment by HansMuller** [comment]
No one should defer to me for good looking layouts, but I agree that labels would make this demo easier to understand.
