### ISSUE TITLE
PaginatedDataTable: Improved error message when rowsPerPage is not 10, 20 or 50.

### ISSUE THREAD

**Issue by fringefilmsoz** [flutter/flutter#55172]
Currently the following error message is thrown when rowsPerPage is not set to availableRowsPerPage:
```
The following assertion was thrown building PatientDataTable(dirty, state: _PatientDataTableState#d2ed0):
Assertion failed: 
..\…\material\paginated_data_table.dart:100
availableRowsPerPage != null && availableRowsPerPage.contains(rowsPerPage)
is not true
```

Proposed to update the error message to:
`rowsPerPage is set to a value that is in availableRowsPerPage. By default, rowsPerPage can only be 10, 20 or 50. You can create a custom set of allowed values by setting availableRowsPerPage`

**Comment by TahaTesser** [comment]
Hi @fringefilmsoz 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
