### ISSUE TITLE
Zipcode sorter for users

### ISSUE THREAD

**Issue by CameronRJohnson** [flutter/flutter#55182]
I am working on a online bardering project that sorts users based on there zipcode or city name and was wondering what the best way to do that would be? At the moment I have the users being sorted on a firebase database but I do not know what is most pratical and where to even start.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
