### ISSUE TITLE
Oops; flutter has exited unexpectedly: FileSystemException: (OS Error: Access is denied. , errno = 5).

### ISSUE THREAD

**Issue by beingbsal** [flutter/flutter#55186]
I am trying to create a project. It shows this error. Will be glad if someone help me?

**Comment by iapicca** [comment]
Hi @beingbsal 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50880) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
