### ISSUE TITLE
Request for richer snippet/example for Reading/Writing files

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5518]
Checking out the sample for reading and writing files, I see a call to runApp() twice. That first call isn't very obvious or ergonomic. https://flutter.io/reading-writing-files/

Have we thought about a more obvious thing to do here? *Must* we initialize the shell this way? Or, can we do "work" before runApp in a more obvious way?

Not sure how common this pattern is, but if we're showing it in docs, it's too easy to cargo cult. Not sure we want developers to use this pattern?

Thanks for any thoughts here.

**Comment by sethladd** [comment]
cc @Hixie for ideas?

**Comment by Hixie** [comment]
Woah, yeah, don't do that. You should just call the binding's initialisation function.
```
WidgetFlutterBinding.ensureInitialized();
```

**Comment by sethladd** [comment]
But why do I need that call in the first place, for the most common/simple case? :)

The examples I've seen before are just a single runApp() at the top. Maybe `ensureInitialized()` is a common thing to do, but if we can remove that for this example, Flutter then looks less ceremonial.

**Comment by Hixie** [comment]
All that's needed is that the bindings be initialised before you use them. PathProvider uses them. runApp() initialises them.

Dart doesn't have module initialisers, so there's no way for us to ensure they're initialised early. We don't want to initialise them on use because it's critical that all the mojo services we provide be registered at the same time as the whole mojo stack, otherwise we might have a race condition where we claim to not have a service then later register it, and at the time where one is used it doesn't know who else needs to be initialised. That's what the binding classes are all about.

**Comment by sethladd** [comment]
> Maybe we should just make these examples slightly more complicated and include a little Widget logic which does the reading/writing from initState or some such?

I'd love to show what we want nearly all of our developers to use in Real Life (tm).

Talked to @qchong , and we'd be happy to accept a snippet that shows something a bit more real.

Thank you!

**Comment by Hixie** [comment]
If you're reading stuff before the first runApp (which is possible) then the call to `WidgetFlutterBinding.ensureInitialized();` is appropriate.
If you're not doing this in `void main`, or you're doing it after the `runApp`, then you don't need it.
I'm not really sure what else to tell you. :-)

**Comment by sethladd** [comment]
Thanks for the advice! Sounds like we need to update the doc to talk about the `ensureInitialized()` for the case where the file I/O is performed before runApp(). Not sure what the trade-offs are for doing File I/O before runApp()? Would that slow down the first paints of the app?

**Comment by apwilson** [comment]
FWIW, if I were to do this I'd load the file after the second runApp call
and then set some state on the widget to display it.  Or do like Eric
suggested and do it in an encapsulating Widget if it actually effects the
UI (which in this case it does).

**Comment by qchong** [comment]
Thanks for the suggestions for improving this sample.
@collinjackson Collin: Can you please provide revised snippets to show file I/O Flutter?

**Comment by collinjackson** [comment]
Here's an example that is exactly like the template starter app except the number of button presses persists across relaunches of the app.

```
import 'dart:io';
import 'dart:async';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new FlutterDemo(),
    ),
  );
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  _FlutterDemoState createState() => new _FlutterDemoState();
}

class _FlutterDemoState extends State<FlutterDemo> {
  int _counter;

  @override
  void initState() {
    super.initState();
    _readCounter();
  }

  Future<File> _getLocalFile() async {
    String dir = (await PathProvider.getApplicationDocumentsDirectory()).path;
    String filename = "$dir/counter.txt";
    return new File(filename);
  }

  Future<Null> _readCounter() async {
    try {
      File file = await _getLocalFile();
      String contents = await file.readAsString();
      setState(() {
        _counter = int.parse(contents);
      });
    } on FileSystemException {
      setState(() {
        _counter = 0;
      });
    }
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
      _getLocalFile().then((File file) {
        file.writeAsStringSync("$_counter");
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Flutter Demo'),
      ),
      body: new Center(
        child: new Text('Button tapped $_counter time${ _counter == 1 ? '' : 's' }.'),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by sethladd** [comment]
Cool, thanks!

**Comment by papakay** [comment]
Hello, I followed the example in https://flutter.io/reading-writing-files/#example-of-reading-and-writing-to-a-file but the **import 'package:path_provider/path_provider.dart';** seems to be having issue. I got the error ``Target of URI doesn't exist``

Please how can i fix this.
