### ISSUE TITLE
Expose drop offset in DragTarget

### ISSUE THREAD

**Issue by monkeyswarm** [flutter/flutter#55184]
Internal: b/154002938

Use case: user drags a Draggable from one widget to another widget, and needs to know where within the latter widget's DragTarget the drop occurred. The former widget may not still be mounted at this point.

Request: expose the drop offset value on the DragTarget.

Right now, when a Draggable's 'feedback' is dropped on a DropTarget:
1) The drop target is asked whether to accept the Draggable.data via [onWillAccept], then calls [onAccept]
2) The Draggable, if it is still mounted, calls [onDragEnd] with the global drop position

My use case is to drag a Draggable from one widget, to a separate widget, and drop; we need to know the position within the DragTarget in order to align the post-drop child in the latter widget. 

I currently have a hacky workaround to do this: DragTarget.onAccept() stashes the Draggable.data in a temporary variable, and then Draggable.onDragEnd creates another variable (a tuple of the data and the position), and sets it as the value of a top-level ValueNotifier. Every single DragTarget will receive that notifier value and decide whether to complete the action with knowledge of a position. 

That hacky workaround breaks if the widget with the Draggable is no longer mounted, since Draggable.onDragEnd (with its payload of the drop offset) is never called. Since Draggable.onDragEnd is the only place where the drop offset is exposed, this is an issue.

A few possibilities come to mind
1) Modify Draggable.onDragEnd so that it will fire even if the widget is no longer mounted. In my cursory reading of drag_target.dart, I don't see a technical reason why the original widget must still be mounted in order for a caller to receive the offset data. 
So drag_target.dart line 399 is changed from
if (mounted && widget.onDragEnd != null) {
to
if ( widget.onDragEnd != null) {
This at least keeps my hack working, but I'd rather get a true fix, and remove our hack, by exposing the position on DragTarget.

2) Expose the drop offset to DragTarget as part of DragTarget.onAccept(). This is an API signature change (of typedef DragTargetAccept) from
void Function(T data) 
to
void Function(T data, Offset offset)
Since this is a breaking change, I'm assuming this is not preferred. (Or is there a way to make this a non-breaking change?)

3) Expose the drop offset to DragTarget as a new callback (e.g. DragTarget.onDropPosition(Offset) or DragTarget.onAcceptPosition(Offset))

Thanks!

**Comment by monkeyswarm** [comment]
FYI @mehmetf

**Comment by mehmetf** [comment]
@HansMuller @goderbauer Who would be the best person to look at this proposal? This file has not been modified for a long time :)

**Comment by goderbauer** [comment]
This sounds like a reasonable request.

Ideally, onAccept should probably accept some kind of a details object from which one can retrieved the data and the offset (giving us the flexibility to add more items to that object in the future if needed). Whether that's a breaking change is determined by our breaking change policy (https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes). Basically, we need to determine whether this is breaking any customer tests. 

PRs are definitely welcome.

**Comment by goderbauer** [comment]
Looks like there are ~4 usage of this within google that would have to be migrated to the new API. Alternatively, we could add a new callback (need to come up with a good name) that does what I described in the previous comment and can basically be used as a full replacement of the existing "onAccept".

**Comment by monkeyswarm** [comment]
Thanks, I'm happy to attempt a PR. Is there any further guidance between the two options you mention, i.e.

- Modifying onAccept to take a details object (which _is_ a breaking change)
- Adding a new callback to DragTarget with a details object, i.e.  "onDragTargetAcceptDetails"
  which would be something like
  
typedef DragTargetAcceptDetails = void Function(DragTargetDropDetails details);

(but yeah, the naming of the typedef method vs naming of the details object itself is kinda odd)

?

I'm leaning towards the latter but please let me know if anyone feels otherwise.
