### ISSUE TITLE
Update windows assemble to copy flutter_assets to data directory

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55188]
Currently the windows assemble/unpack builds (https://github.com/flutter/flutter/pull/55187/files) copy the flutter_assets to `build/flutter_assets`. A later step in the build will copy these to `$(OutputPath)/data/flutter_assets`.

The assemble step should be updated to copy to the right location, both to reduce the complexity of of any non-Dart scripts and so the dependency tracking works correctly.

**Comment by stuartmorgan** [comment]
I'm not sure that's "the right location" so much as "the location I picked for convenience". We need to decide what structure we want for the output—and this is somewhat interactive with how we think an an end-user installation of a Flutter app should look—before we move anything into the tool. Right now, everything is in the template, and we can easily change it; once part of the structure is controlled by the template and part of it by the tool, things get much more locked-in.

**Comment by stuartmorgan** [comment]
> so the dependency tracking works correctly

What's the concern here? Just an extra copy step?

**Comment by jonahwilliams** [comment]
From discussion offline, I want to avoid extra work and ensure we delete all outputs with rm -rf. However it seems like this will be a premature optimization, so I'll close it for now
