### ISSUE TITLE
Cupertino widgets blurred on https://flutter.github.io/gallery/#/ 

### ISSUE THREAD

**Issue by PeterPopelix** [flutter/flutter#55193]
I am writing an app using cupertino classes and use Firefox or Chrome browsers (Google Chrome Version 81.0.4044.113) to look at Cupertino examples but they are now dimmed,  why?
Couple of weeks ago I was able to look at them, not so anymore.

https://flutter.github.io/gallery/#/ 
![Screenshot 2020-04-20 at 09 36 52](https://user-images.githubusercontent.com/11142719/79726102-914e3000-82ea-11ea-8ea8-b404c64e3c15.png)

**Comment by TahaTesser** [comment]
`Version 81.0.4044.113 (Official Build) (64-bit)`

<img width="1437" alt="Screenshot 2020-04-20 at 2 17 25 PM" src="https://user-images.githubusercontent.com/48603081/79733028-21ec3680-8312-11ea-86d4-24adfa62466c.png">

**Comment by tvolkert** [comment]
Is this specific to web (not happening on mobile)?  @ferhatb

**Comment by ferhatb** [comment]
Chrome 81 changed how backdrop-filter CSS attribute renders, working on a fix.

**Comment by xster** [comment]
can we assign this issue to you @ferhatb?

**Comment by ferhatb** [comment]
landed in engine, waiting next roll into flutter
