### ISSUE TITLE
Modify the (range)slider tickmarks to show values

### ISSUE THREAD

**Issue by RomanJos** [flutter/flutter#55192]
It would be great to show the value instead of dots.
I tried to copy-paste the file inside src/material but I achieved nothing so far

**Comment by TahaTesser** [comment]
Hi @RomanJos 
can you please provide your `flutter doctor -v` ?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by RomanJos** [comment]
I mean I don't think it is relevent but here you go
 <details>
  <summary><code>flutter doctor -v</code></summary>

```
roman@roman-pc ~> flutter doctor -v
[✓] Flutter (Channel master, v1.18.0-6.0.pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-6.0.pre.83 at /home/roman/Documents/Github/flutter
    • Framework revision 8e5b575174 (16 hours ago), 2020-04-19 17:20:01 -0400
    • Engine revision 2b75c6d111
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 4814f000de)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/roman/Android/Sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions.

[!] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

And for the example its more of a feature request than an how to use the API but I didn't selected the good one

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by RomanJos** [comment]
I made a quick draft to show you what I want to achieve 
![image](https://user-images.githubusercontent.com/42180076/79984578-a8874c00-84a9-11ea-9f70-54d3e0ba9e61.png)

**Comment by HansMuller** [comment]
Have you considered creating a custom widget that does exactly what you want?

**Comment by RomanJos** [comment]
You overestimate me :smile: I tried but I quickly realised that I was missing some skills haha, I opened an issue on xlider's Github but so far no response

**Comment by RomanJos** [comment]
Do you have some idea on how I can achieve this ? Its the last thing remaining before finishing my project so I have no choice

**Comment by RomanJos** [comment]
See https://github.com/Ali-Azmoud/flutter_xlider/issues/54
