### ISSUE TITLE
Add an option or flag to RadioListTile and CheckBoxListTile to specify where the radio or checkbox needs to be placed

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#55190]
Right now , the RadioListTile puts the radio button at the leading end of the list tile.
There are many times where one would wanna put the radio button at the trailing end of the list tile.

<img width="249" alt="Screenshot 2020-04-13 at 9 38 53 AM" src="https://user-images.githubusercontent.com/23279926/79717944-90bc9600-82f8-11ea-9d4d-793f3035a4c9.png">

Consider the above design . This is a needed option to the RadioListTile. 

So we need a flag or option to specify where the Radio button or Checkbox (in CheckBoxListTile) needs to be placed.

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.15.18-pre.1, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Currently there is no option to specify or change location 
https://api.flutter.dev/flutter/material/RadioListTile-class.html
https://api.flutter.dev/flutter/material/CheckboxListTile-class.html

**Comment by AyushBherwani1998** [comment]
@nateshmbhat @TahaTesser there is `controlAffinity` property in both `RadioListTile` and `CheckboxListTile` to specify the position of the control and secondary widget.

For Example:

```dart
RadioListTile<String>(
          // ListTileControlAffinity.trailing will place the radio at the trailing
          controlAffinity: ListTileControlAffinity.trailing,
          title: const Text('Thomas Jefferson'),
          value: "Hey",
          groupValue: "newGroup",
          onChanged: (String value) {
            setState(() {
              print(value);
            });
          },
        )
```

For more information, check out [ListTileControlAffinity](https://api.flutter.dev/flutter/material/ListTileControlAffinity-class.html)

**Comment by AyushBherwani1998** [comment]
@TahaTesser I guess you can close the issue, since the properties already exist in the framework.
