### ISSUE TITLE
IconButton bad constructor design

### ISSUE THREAD

**Issue by hiwa-jalal** [flutter/flutter#55199]
i think the `IconButton()` constructor should just directly receive an icon as it's first positional argument 
just like `Text()` constructor because that's what it's name says it should not allow any other widget or make you type icon as a named parameter because it will make it useless as it will be just like `FlatButton()`, for example:

```
IconButton(icon: Icon(Icons.home), onPressed: () {})
FlatButton(child: Icon(Icons.home), onPressed: () {})
```
they both produce the same result.

**Comment by TahaTesser** [comment]
hi @hiwa-jalal 
`IconButton` can also take `Image` Widget not just `Icon` much like `FlatButton`
However having `icon` parameter makes it easier to read `icon` `IconButton`

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              IconButton(
                  icon: Image.network('https://i.imgur.com/QCNbOAo.png'),
                  onPressed: () {}),
              FlatButton(
                  child: Image.network('https://i.imgur.com/QCNbOAo.png'),
                  onPressed: () {}),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by hiwa-jalal** [comment]
but shouldn't FlatButton() be used for images and IconButton() be used specifically for just icons as it's name suggest!

**Comment by VladyslavBondarenko** [comment]
@hiwa-jalal 
> but shouldn't FlatButton() be used for images and IconButton() be used specifically for just icons as it's name suggest!

it would make sense if the only difference between FlatButton and IconButton was their child widget. But they are different, their properties don’t intersect completely.

Icon in IconButton isn’t the first positional argument because it’s not the only required property

Closing this proposal,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by hiwa-jalal** [comment]
okay got it, thanks.
