### ISSUE TITLE
I Dont know why the listview is not scrollable. Maybe the height or my code?

### ISSUE THREAD

**Issue by alifjkhan** [flutter/flutter#55195]
![Screenshot (218)](https://user-images.githubusercontent.com/57591457/79732013-a7c5ad00-8325-11ea-937d-f4d1e654bbe2.png)

**Comment by vishal-android-freak** [comment]
Use `LayoutBuilder()` instead of `MediaQuery`

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by alifjkhan** [comment]
thank you vishal because of you im done
