### ISSUE TITLE
[webview_flutter]can h5 use camera in android?

### ISSUE THREAD

**Issue by lameone1** [flutter/flutter#55205]
**_add_**
`<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
in AndroidManifest.xml ,but it's do not work

`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.4 18E227, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Applications/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zjamp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (4 available)
    • Redmi Note 3              • 2b5afc8d                                 • android-arm64 • Android 5.1.1 (API 22)
    • Android SDK built for x86 • emulator-5554                            • android-x86   • Android 8.1.0 (API 27) (emulator)
    • 测试6                       • 817bce2855bb37dc9fa7f276c398bc2efe3c0e60 • ios           • iOS 12.1.4
    • iPhone 8                  • F33096F1-3D52-4E3F-BDD0-EFFED3F28BAF     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!`

**Comment by VladyslavBondarenko** [comment]
Hi @lameone1 
could you describe what do you mean by `but it's do not work` (with minimal reproducible code sample and logs if related)? 
provide your `flutter doctor -v`

**Comment by TahaTesser** [comment]
Hi @lameone1 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
