### ISSUE TITLE
flutter symbolize is broken

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55214]
Without this there is no easy way to use --split-debug-info, though users can use the pub executable (native_stack_traces) directly.

FYI @pcsosinski  this might need a cherry pick

**Comment by pcsosinski** [comment]
when did it break?

**Comment by jonahwilliams** [comment]
always :(

**Comment by pcsosinski** [comment]
was it broken in 1.12 or is this newer?

**Comment by zanderso** [comment]
Crash logging first reports the error on master in 1.15.4-pre.82

**Comment by zanderso** [comment]
@jonahwilliams would the runtime type error have been introduced by a Dart SDK roll after your PR with the feature landed?

**Comment by jonahwilliams** [comment]
I have no idea, the error doesn't make a lot of sense to me. I could spend time bisecting today but I've already got a lot on my plate
