### ISSUE TITLE
Add to App with Platform Channels in Flutter 1.12

### ISSUE THREAD

**Issue by way2jatin** [flutter/flutter#55216]
Is it possible to use platform channels to pass data from the same native app which is being added using Add To App feature ? I know we can use platform channels using the native code embedded inside the flutter project. But i m facing issues doing the same from a native code base(Android & iOS) outside the flutter project. If it is possible, then please do share the working examples for the same. Thanks

**Comment by xster** [comment]
See samples at https://github.com/flutter/samples/tree/master/add_to_app
