### ISSUE TITLE
In reference to this issue, https://github.com/flutter/flutter/issues/52084

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#55227]
This #52084 issue still exist, it haven't be resolved with even "https://flutter.dev/docs/development/ios-project-migration" fix.

**Comment by stuartmorgan** [comment]
Per the last comment:
> Please file a new issue and completely fill out the template if you followed the migration instructions and are still seeing similar error messages.

Please file a new issue *and completely fill out the template* with details about how you are getting it, your version details, etc.
