### ISSUE TITLE
Make SVG file support built in to flutter

### ISSUE THREAD

**Issue by deyar4** [flutter/flutter#55229]
Please make SVG support built in to flutter because the packages that are available for SVG support have some problems in which you can only use SVG's like a widget and cannot be applied to certain areas of your application such as box Decoration images and etc... Thanks.

**Comment by goderbauer** [comment]
Duplicate of https://github.com/flutter/flutter/issues/15501, we currently have no plans to add this. I would suggest filing issues with the svg package if you find support lacking for the things you want to do.
