### ISSUE TITLE
frontend_server switching to package_config removed the ability to hot reload new packages

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55237]
Verified before https://github.com/flutter/flutter/commit/b7e30cfc26040df3fac1467ecb4efb8acc5ae49c

1. `flutter run` an example app.
2. Add a new dependency and `pub get`.
3. Import the new dependency and perform a hot reload
4. Error

```
Performing hot reload...                                                
Reloaded 0 of 341 libraries in 83ms.

                                                                        
Compiler message:
Error: Could not resolve the package 'rxdart' in 'package:rxdart/rxdart.dart'.
lib/main.dart:6:8: Error: Not found: 'package:rxdart/rxdart.dart'       
import 'package:rxdart/rxdart.dart';                                    
       ^                                                                
Performing hot reload...                                                
Try again after fixing the above error(s).

```

This is likely caused by the flutter_tool sending a .packages URI during invalidation while the frontend_server looks for a package_config.json URI invalidation.

**Comment by jonahwilliams** [comment]
Likely caused by https://github.com/dart-lang/sdk/commit/6746579d1bb3b2e76048c25e7131f2363bb6412a but I haven't bisected

The easiest fix is probably to switch to package_config, but the fact that the compiler may use a different config file than what is specified is a bit of a footgun. I will switch the tool to use package_config.json by default to see if the issue is resolved

**Comment by jonahwilliams** [comment]
Confirmed that if I change the default package path in the tool to .dart_tool/package_config.json this is resolved.

FYI @jakemac53

**Comment by jakemac53** [comment]
These are the specified semantics now - I agree its a bit weird that it reads a different file than what you explicitly specified but there are a lot of other benefits to it working this way. Basically, it makes things "just work" for all existing code that passes a `.packages` file.

**Comment by jakemac53** [comment]
We could consider some special case in frontend server to invalidate the `.dart_tool/package_config.json` file as well when you invalidate the `.packages` file?

**Comment by jonahwilliams** [comment]
Switching the default package path in the tool will likely fix this for most users. I almost have that ready to go, but if you want to take a swing at the frontend_server change I wouldn't complain
