### ISSUE TITLE
scroll hysteresis isn't quite right on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5524]
I was speaking with several iOS experts this evening and one pointed out that we treat some taps as scrolls differently from how iOS proper would.  Presumably there is a small-scroll value which we just need to change in our gesture recognizer.

To repro, try pressing a little hard or fat-fingered in the settings app vs. flutter gallery and notice how we treat more taps as scrolls than settings does.

FYI @Hixie

**Comment by abarth** [comment]
The value we use matches Android.  It's possible we should use a different value on iOS.

**Comment by Hixie** [comment]
I think this is the same as https://github.com/flutter/flutter/issues/4958 right?
I looked into it the other day but was unable to convince myself that this wasn't just a manifestation of https://github.com/flutter/flutter/issues/5361.

**Comment by eseidelGoogle** [comment]
It was probably this constant he was implying, but we'd have to test: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/constants.dart#L18

**Comment by xster** [comment]
If I understood the nature of this correctly (i.e. this is about movement thresholds for initiating scrolls, not distinguishing between moves and taps), then it's fixed in #12181 where we increased the scroll start threshold to match iOS which is higher than Android.
