### ISSUE TITLE
Can't enter text into obscured field on iOS simulator

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#55259]
Create a TextField with `obscuredText: true`.  On iOS, you won't be able to enter any text into the field.

I opened this issue after seeing discussion in an older closed issue, https://github.com/flutter/flutter/issues/27353.

**Comment by justinmc** [comment]
This seems to have been caused by this engine roll PR: https://github.com/flutter/flutter/pull/54997

@LongCatIsLooong Does this jump out at you as something that could be caused by Autofill?  I see that it was part of that engine roll, though it's not the only text related thing.

**Comment by LongCatIsLooong** [comment]
Does this happen on the tip of the tree? The latest engine roll should fix this.

**Comment by justinmc** [comment]
@LongCatIsLooong You're right, this doesn't happen in the latest master.  I must have been slightly out of date yesterday when I tried this.  I'll close it.
