### ISSUE TITLE
Programmatically open the toolbar on textfields

### ISSUE THREAD

**Issue by ciriousjoker** [flutter/flutter#55255]
## Use case

I want to immediately show the toolbar when focusing a text field. Also, I want to have different items in it depending on the content of the text field when being focused (paste when empty, copy/paste otherwise).

## Proposal

Expose showToolbar() of EditableText inside the TextEditingController.

___

Somewhat related to #48434

**Comment by Piinks** [comment]
I believe TextInputClient.showToolbar resolved this. Closing.
