### ISSUE TITLE
Flutter doctor -v keep reporting download fail

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#55254]
Just like you see in the screenshot, it never pass and keeps on retrying.

![image](https://user-images.githubusercontent.com/3827781/79811790-101a9a00-83cb-11ea-98a5-8fdcd7603698.png)

**Comment by TahaTesser** [comment]
Hi @PandaGeek1024 
Are you using private network or VPN? or make sure you've stable internet connection. Are you using Flutter China?
can you please provide your complete `flutter doctor -v`? 
Which flutter version you've installed on what platform?
Is it a fresh install or did you upgrade?
Thank you

**Comment by PandaGeek1024** [comment]
Im in nz. Somehow it fix itself now. All good
