### ISSUE TITLE
Flutter 1.12.13+hotfix.8 Crash

### ISSUE THREAD

**Issue by smallsao** [flutter/flutter#55261]
Hello,

When I use Flutter 1.12.13+hotfix.8 in My iOS App.
The App will crash with Flutter.

```
0	AppleMetalGLRenderer
GLRResourceList::addResource(GLRResource*) + 40
1	AppleMetalGLRenderer
GLDContextRec::addRenderPassResources() + 76
2	AppleMetalGLRenderer
GLDContextRec::addRenderPassResources() + 76
3	AppleMetalGLRenderer
gldClearFramebufferData + 224
4	GLEngine
_glClear_Exec + 548
5 GrContext::MakeGL(sk_sp<GrGLInterface const>, GrContextOptions const&) (in Flutter) (GrLegacyDirectContext.cpp:144)
6 GrCopyRenderTask::Make(GrSurfaceProxyView, SkIRect const&, GrSurfaceProxyView, SkIPoint const&, GrCaps const*) (in Flutter) (GrCopyRenderTask.cpp:43)
7 GrConvertPixels(GrImageInfo const&, void*, unsigned long, GrImageInfo const&, void const*, unsigned long, bool) (in Flutter) (GrDataUtils.cpp:416)
8 GrRenderTargetContext::drawFastShadow(GrClip const&, SkMatrix const&, SkPath const&, SkDrawShadowRec const&) (in Flutter) (GrRenderTargetContext.cpp:1200)
9 SkGpuDevice::drawBitmapRect(SkBitmap const&, SkRect const*, SkRect const&, SkPaint const&, SkCanvas::SrcRectConstraint) (in Flutter) (SkGpuDevice.cpp:1178)
10 bssl::tls13_server_handshake(bssl::SSL_HANDSHAKE*) (in Flutter) (tls13_server.cc:931)
11 std::__1::__function::__func<flutter::Shell::NotifyLowMemoryWarning() const::$_12, std::__1::allocator<flutter::Shell::NotifyLowMemoryWarning() const::$_12>, void ()>::~__func() (in Flutter) (functional:1482)
12 flutter::PlatformView::~PlatformView() (in Flutter) (platform_view.cc:25)
13 flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (in Flutter) (rasterizer.cc:281)
14 flutter::PlatformView::DispatchSemanticsAction(int, flutter::SemanticsAction, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >) (in Flutter) (platform_view.cc:48)
15 std::__1::__function::__func<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_32, std::__1::allocator<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_32>, void ()>::__clone() const (in Flutter) (functional:1528)
16 fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:120)
17 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (in Flutter) (thread:352)
18	CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
19	CoreFoundation
___CFRunLoopDoTimer + 864
```

How can I do?

**Comment by TahaTesser** [comment]
Hi @smallsao 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by smallsao** [comment]
> Hi @smallsao
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

flutter doctor:
[✓] Flutter (Channel unknown, v1.12.13+hotfix.800002, on Mac OS X 10.15.4 19E287, locale en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)

My iOS App is not a single flutter project,  This App is a native workspace Integrate a flutter project。
and I can't write a simple demo because a simple demo don't have this problem.

**Comment by TahaTesser** [comment]
Hi @smallsao 
Can you please provide your `pubspec.yaml` and sample code from your Flutter module?
Also to better address the issue, can you give us more detail when this crash occurs in your app? 
Thank you

**Comment by VladyslavBondarenko** [comment]
@smallsao 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Comment by huangshengjie123** [comment]
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on macOS 11.1 20C69, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[!] Xcode - develop for iOS and macOS       
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

**Comment by huangshengjie123** [comment]
AppleMetalGLRenderer | GLRResourceList::addResource(GLRResource*) + 40
-- | --
1 AppleMetalGLRenderer | GLDContextRec::addRenderPassResources() + 68
2 AppleMetalGLRenderer | GLDContextRec::addRenderPassResources() + 68
3 AppleMetalGLRenderer | gldClearFramebufferData + 224
4 GLEngine | _glClear_Exec + 452
5 Flutter | 0x0000000104118000 + 2005140
6 Flutter | 0x0000000104118000 + 1953608
7 Flutter | 0x0000000104118000 + 1955068
8 Flutter | 0x0000000104118000 + 2084716
9 Flutter | 0x0000000104118000 + 2546828
10 Flutter | 0x0000000104118000 + 4281636
11 Flutter | 0x0000000104118000 + 576184
12 Flutter | 0x0000000104118000 + 502000
13 Flutter | 0x0000000104118000 + 505508
14 Flutter | 0x0000000104118000 + 502704
15 Flutter | 0x0000000104118000 + 527232
16 Flutter | 0x0000000104118000 + 241496
17 Flutter | 0x0000000104118000 + 250332
18 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
19 CoreFoundation | ___CFRunLoopDoTimer + 1004
20 CoreFoundation | ___CFRunLoopDoTimers + 324
21 CoreFoundation | ___CFRunLoopRun + 1912
22 CoreFoundation | CFRunLoopRunSpecific + 572
23 Flutter | 0x0000000104118000 + 250040
24 Flutter | 0x0000000104118000 + 248004
25 libsystem_pthread.dylib | _pthread_start + 288

**Comment by TahaTesser** [comment]
@huangshengjie123 
This is almost a year old Flutter version, please upgrade to the latest `stable`
