### ISSUE TITLE
path_provider-1.6.5 not working with v1.12.13+hotfix.9

### ISSUE THREAD

**Issue by arashdeepsinghazad** [flutter/flutter#55271]
Note: /home/arashdeep/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.

**Comment by TahaTesser** [comment]
Hi @arashdeepsinghazad 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by arashdeepsinghazad** [comment]
problem solved by dedating the version of flutter

**Comment by VladyslavBondarenko** [comment]
@arashdeepsinghazad 
This isn't an error and just "deliberate and temporary" warning
Closing as duplicate of https://github.com/flutter/flutter/issues/47153
