### ISSUE TITLE
Observatory Timeline show nothing

### ISSUE THREAD

**Issue by 6a209** [flutter/flutter#55277]
Flutter doctor 

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 )
    • Flutter version 1.12.13+hotfix.9 at /usr/local/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

run this command:

**flutter run --profile --trace-skia** 

then open url (http://127.0.0.1:51381/CHvnAB6us9M=/)  on chrome 

timeline page show nothing like this
![image](https://s1.ax1x.com/2020/04/21/J8RJET.png)

chrome console show some error

Uncaught ReferenceError: tr is not defined
    at showLoadingOverlay (timeline.js:546)
    at onMessage (timeline_message_handler.js:24)

Uncaught ReferenceError: tr is not defined
    at updateTimeline (timeline.js:538)
    at populateTimeline (timeline.js:562)
    at onMessage (timeline_message_handler.js:29)

**Comment by TahaTesser** [comment]
Issue exist on  only `stable`, not produced on `beta`, `dev`

`flutter run --profile --trace-skia`

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/taha/Code/flutter_stable
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)
• No issues found!
```

</details>

Thank you for your contribution

**Comment by jonahwilliams** [comment]
Removing from tools designation since the observatory is a Dart SDK tool

**Comment by hallidev** [comment]
I'm on ```Flutter 1.17.0-3.2.pre • channel beta``` and I'm getting nothing in the Timeline in Dart DevTools or Dart Observatory on both Android and iOS in either Debug on emulators or Profile on real devices. The Timeline is just completely blank. This is a relatively new issue, but I can't pin down exactly when it broke as I don't use the Timeline that frequently.

Dart DevTools doesn't show any errors in the console window, but Dart Observatory shows 

```Uncaught ReferenceError: tr is not defined
    at showLoadingOverlay (timeline.js:546)
    at onMessage (timeline_message_handler.js:24)```

as mentioned originally in this issue.
