### ISSUE TITLE
Scroll offsets should be pixel aligned on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5527]
I was speaking with an iOS expert this evening and they commented that our scrolling looked blurry.  They claimed iOS pixel-aligns scroll offsets during scrolls, unclear if we do, but it seems like we don't.

Presumably easy to fix?  @Hixie

**Comment by abarth** [comment]
We do, but the math we use is dodgy and might have bugs.

**Comment by abarth** [comment]
Also, do you remember exactly which screen showed the problem?  We might have missed one somewhere.

**Comment by eseidelGoogle** [comment]
We were just looking at the gallery main demo list.

**Comment by Hixie** [comment]
This is not something I've heard anyone complain about recently, is it still an issue?
cc'ing iOS likely suspects: @xster @cbracken @chinmaygarde

**Comment by xster** [comment]
@eseidelGoogle can your expert contact divulge more about what the 'spec' is? Is it just never having offsets that are not whole units of physical pixels?

**Comment by eseidelGoogle** [comment]
Oh geez. This is ancient.  I can demo our Gallery in front of my iOS contacts and file new bugs if needed.
