### ISSUE TITLE
Flutter Doctor error

### ISSUE THREAD

**Issue by shahi5472** [flutter/flutter#55275]
## Steps to Reproduce

Downloading Dart SDK from Flutter engine c9506cb8e93e5e8879152ff5c948b175abb5b997...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/c9506cb8e93e5e8879152ff5c948b175abb5b997/dart-sdk-darwin-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @shahi5472 
can you please provide your `flutter doctor -v`?
If you're using Flutter China, please check https://flutter.dev/community/china and setup [Configuring Flutter to use a mirror site
](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) 
Thank you

**Comment by shahi5472** [comment]
Thank you for your help. I am solve this issue using VPN.

**Comment by TahaTesser** [comment]
Hi @shahi5472 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
