### ISSUE TITLE
Implement hybrid composition on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#55270]
This mode enables Android native views to be rendered as an independent `View` and composed along with Flutter UI.

Design doc: go/flutter-hybrid-composition

**Comment by SpajicM** [comment]
How will this be different from AndroidView?

**Comment by blasten** [comment]
Currently, `AndroidView` uses https://api.flutter.dev/flutter/dart-ui/SceneBuilder/addTexture.html downstream, while hybrid composition uses https://api.flutter.dev/flutter/dart-ui/SceneBuilder/addPlatformView.html.

**Comment by NoamDev** [comment]
The hybrid composition mechanism will still hold the platfrom view in a virtual display, right?
So the only difference is that it'll draw it on a different view, instead of drawing everything on the main flutter view. Am I right?

**Comment by chinmaygarde** [comment]
Triage: Updating the milestone to be more in line with other related work-items at the same priority.

**Comment by t-artikov** [comment]
Hi! Where can I read the design document?
https://flutter.dev/go/flutter-hybrid-composition is not working.

**Comment by blasten** [comment]
I will make sure that we make the design doc public!

**Comment by blasten** [comment]
Hybrid composition is feature completed now. The remaining tasks are driver tests, update benchmarks, etc...

**Comment by NoamDev** [comment]
> I will make sure that we make the design doc public!

@blasten great! Is it conplicated? It's just that I wouldn't want to bother people with questions about this bew approach. A public design doc would solve all that:)
Unless you're over your head of course, or that ot takes more time than just a few clicks.
Anyway, I really appreciate this new solution (from what I saw in the code), and I guess I'd appreciate it even more once I read the design doc:)

**Comment by simpzan** [comment]
@blasten can you publish the design doc of flutter-hybrid-composition please? Thanks!

**Comment by NoamDev** [comment]
@simpzan 
There's an issue tracking that: #61976
