### ISSUE TITLE
Persistent bottom sheet Failed assertion: 'value == target' and '_dismissedBottomSheets != null' is not true.

### ISSUE THREAD

**Issue by bit-garden** [flutter/flutter#5528]
## Steps to Reproduce
When dragging to close a persistent bottom sheet and you slowly swipe down, it periodically looses its target value. 

This is reproducible in the Gallery app too

## Flutter Doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/dakunesu/Downloads/dev/git/flutter/flutter
    • Framework revision 9a0a0d9903 (7 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /home/dakunesu/Downloads/dev_tools/android_sdk/android-sdk-linux
    • Platform android-24, build-tools 24.0.1
    • OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~12.04-b14)

## Logs and Crash Reports
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown while routing a pointer event:
I/flutter : 'package:flutter/src/material/scaffold.dart': Failed assertion: line 498: '_dismissedBottomSheets !=
I/flutter : null' is not true.
I/flutter : 
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      ScaffoldState.showBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:498)
I/flutter : #3      _PersistentBottomSheetState._handleStatusChange (package:flutter/src/material/scaffold.dart:822)
I/flutter : #4      Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:118)
I/flutter : #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:253)
I/flutter : #6      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:126)
I/flutter : #7      _BottomSheetState._handleDragUpdate (package:flutter/src/material/bottom_sheet.dart:103)
I/flutter : #8      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/drag.dart:189)
I/flutter : #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
I/flutter : #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
I/flutter : #11     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:133)
I/flutter : #12     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111)
I/flutter : #13     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92)
I/flutter : #14     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51)
I/flutter : #15     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44)
I/flutter : #16     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:43)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : 
I/flutter : Event:
I/flutter :   PointerMoveEvent(Point(323.3, 1039.6))
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter : Another exception was thrown: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 183: 'value == target' is not true.

**Comment by eseidelGoogle** [comment]
Probably @HansMuller or @Hixie are your peoples here.
