### ISSUE TITLE
Feature Request: Enable All FlutterDriver Functionalities on Web

### ISSUE THREAD

**Issue by pennzht** [flutter/flutter#55293]
## Use case

We already use FlutterDriver to carry out performance tests for Flutter on Android. See tests [in flutter](https://github.com/flutter/flutter/tree/master/dev/devicelab) and [in gallery](https://github.com/flutter/gallery/tree/master/test_driver).

An example is the [transitions_perf_test.dart](https://github.com/flutter/gallery/blob/master/test_driver/transitions_perf_test.dart) test for the new flutter gallery.
The test can be run on Android, but does not run as expected on Web. More specifically, it seems that:
* `driver.traceAction` does not return any frame building data;
* Scrolling on Web has a different effect from scrolling on Mobile;
* FlutterDriver uses its own widgets binding, different from `Recorder` in [macrobenchmarks](https://github.com/flutter/flutter/tree/master/dev/benchmarks/macrobenchmarks).

## Proposal

We should aim to make FlutterDriver tests work on Web, with minimal or no changes.
* `driver.traceAction` should collect the same metrics on Web as on Mobile;
* Scrolling should behave the same on Web and on Mobile;
* All FlutterDriver functionalities should be available on Web, so that FlutterDriver tests can be run on Web.

This would be extremely helpful to Flutter's cross-platform strength.

We understand that this is a complicated feature, and will most likely be broken down into many smaller tasks. I appreciate the efforts on making this happen!

**Comment by guidezpl** [comment]
I'll provide a bit more context on the scrolling behavior. It seems that the `driver.scrollUntilVisible` with an item in a nested listview (with the ancestor listview partly scrolled) doesn't behave as expected and the test gets stuck.

**Comment by darshankawar** [comment]
@pennzht 
Since integration_test [plugin](https://pub.dev/packages/integration_test) is now preferred approach for writing UI tests in favor of flutter driver and since the plugin supports running tests on [web](https://pub.dev/packages/integration_test#web), can you try the same and see if it helps to resolve your issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
