### ISSUE TITLE
Flexible size of Positioned widget

### ISSUE THREAD

**Issue by cuong1112035** [flutter/flutter#55298]
I have a Positioned widget with fix width in a Stack widget. I want the Positioned has the height base on the height of its child. 
I did search on stackoverflow but the answer is no. Are there any workaround to help me reach my wish?

**Comment by VladyslavBondarenko** [comment]
@cuong1112035 
Isn't it already like this?
https://codepen.io/vladbond/pen/BaoQLwK

could you modify the code sample and describe your case?

**Comment by cuong1112035** [comment]
After researching on unbounded and bounded widget. I figure out using Column widget as child of the Positioned widget cause of the issue. 
I resolved the issue by adding `mainAxisSize: MainAxisSize.min` inside the Column widget.
Thanks for your help and please help @VladyslavBondarenko
