### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1217 pos 12: '_debugLifecycleState == _StateLifecycle.ready': is not true.

### ISSUE THREAD

**Issue by afung2468** [flutter/flutter#55295]
When the exception was thrown, this was the stack: 
#2      State.dispose (package:flutter/src/widgets/framework.dart:1217:12)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
#5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
#6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
...

## Steps to Reproduce
Create an app with Screen A and Screen B. Screen A navigate to Screen B by calling "push". Screen B is a stateful widget. The "deactivate" function is modified to call "dispose" to clear it from memory so that when it is pushed again, a fresh copy will appear. When Back Button is tapped on Screen B, this exception will occur.

**Comment by VladyslavBondarenko** [comment]
Hi @afung2468 
could you provide your `flutter doctor -v` and a minimal complete code sample to reproduce the problem?

**Comment by afung2468** [comment]
Thanks for the reply.

 

After I put some print statements in lifecycle functions, I noticed that my app called “dispose” twice. So, I would like to cancel my bug report. The bug was in my app.

 

Thanks,

Andrew
