### ISSUE TITLE
Simulator builds fail for both iOS and Android after flutter upgrade - Error: The non-abstract class 'ChipsInputState' is missing implementations for these members: - TextInputClient.currentAutofillScope

### ISSUE THREAD

**Issue by ochmist** [flutter/flutter#55309]
Hello, I am on the master channel, and I just ran flutter upgrade today and everything broke. I tried downgrading but that did not work. I am using vscode. Here are my tool versions: 

```
Flutter 1.18.0-6.0.pre.106 • channel master • https://github.com/flutter/flutter.git
Framework • revision 84c84fb249 (15 hours ago) • 2020-04-20 21:35:01 -0400
Engine • revision 2bde4f0ae4
Tools • Dart 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
```

```
code build done.                                           19.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Compiler message:
    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.0/lib/src/chips_input.dart:64:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
     - TextInputClient.currentAutofillScope
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
```

**Comment by VladyslavBondarenko** [comment]
Hi @ochmist 
Please consider to create issue in the [flutter_chips_input repository](https://github.com/danvick/flutter_chips_input/issues)
Closing, as this may be an issue with the 3rd party plugin,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by MichaelKMalak** [comment]
I am facing the same problem. 
I executed `flutter upgrade` today and I only have [flutter_form_builder](https://pub.dev/packages/flutter_form_builder) as a dependency in `pubspec.yaml`.

@ochmist, please let me know if you solved the issue.

**Comment by JayPerfetto** [comment]
I am also experiencing this after running flutter upgrade today

**Comment by JayPerfetto** [comment]
I downgraded to flutter version 1.17.0 temporarily and am able to at least build my project, but it would be great if this issue can be addressed asap as it is a build-blocker

**Comment by ochmist** [comment]
> I was facing the same problem.
> I executed `flutter upgrade` today and I only have [flutter_form_builder](https://pub.dev/packages/flutter_form_builder) as a dependency in `pubspec.yaml`. I was at flutter's master channel.
> 
> @ochmist, you can switch to another flutter channel from the terminal: `flutter channel stable`. This might solve the issue temporarily for you.

Agreed. That is how I resolved it as well. I will reopen the bug under flutter_form_builder (it is also the only dependency that may use Chips Input in my project).

**Comment by ochmist** [comment]
> Hi @ochmist
> Please consider to create issue in the [flutter_chips_input repository](https://github.com/danvick/flutter_chips_input/issues)
> Closing, as this may be an issue with the 3rd party plugin,
> if you disagree please write in the comments and I will reopen it
> Thank you

Sorry for the noise. I will file it under the appropriate project.

**Comment by ochmist** [comment]
The new issue can be tracked [here](https://github.com/danvick/flutter_form_builder/issues/261).

**Comment by sageata** [comment]
As a solution, if you want to keep working on dev of master channels, add this to your pubspec dependencies:

flutter_chips_input: 1.9.0-dev.1

I know is a bit weird to add another dependency to your project, but it works for now :D
