### ISSUE TITLE
https://github.com/flutter/flutter/pull/49708 had a dramatic impact on a benchmark

### ISSUE THREAD

**Issue by flar** [flutter/flutter#55319]
The PR https://github.com/flutter/flutter/pull/49708 produced a change in the `flutter_gallery__transition_perf_with_semantics/delta_average_frame_build_time_millis` benchmark that tripled the time those frame build times take.

This impact was seen on 1/17/2020 when the original version of this fix landed under https://github.com/flutter/flutter/pull/48985
The benchmarks went back to their previous times when that PR was reverted on 1/27/2020 (see https://github.com/flutter/flutter/pull/49572)
The impact was again felt when the changes were re-landed on 1/29/2020 (see https://github.com/flutter/flutter/pull/49708)

**Comment by chinmaygarde** [comment]
Triage: @flar It was not clear from the description if the change was reverted for good. From your last comment on the re-land, you seemed to [indicate re-baselining](https://github.com/flutter/flutter/pull/49708#issuecomment-620194827). Just doing a quick triage pass over regressions so I haven't looked too deeply into details. Assigning P6 tentatively. Please feel free to change the priority as necessary. Thanks.

**Comment by chinmaygarde** [comment]
Triage: @flar It was not clear from the description if the change was reverted for good. From your last comment on the re-land, you seemed to [indicate re-baselining](https://github.com/flutter/flutter/pull/49708#issuecomment-620194827). Just doing a quick triage pass over regressions so I haven't looked too deeply into details. Assigning P6 tentatively. Please feel free to change the priority as necessary. Thanks.

**Comment by flar** [comment]
The benchmark in question was archived. I have no idea why.

I did not indicate re-baselining, I was asking the author (or @jonahwilliams) if they felt that rebaselining was appropriate. I never saw an answer to that question. Instead someone archived it. Who is responsible for this benchmark?

**Comment by liyuqian** [comment]
Noticed this issue in the performance triage. @jonahwilliams @clocksmith @flar : should we close this issue according to https://github.com/flutter/flutter/pull/49708#issuecomment-620194827 ?

**Comment by jonahwilliams** [comment]
I believe I commented on this (or a similar issue) elsewhere. TLDR: fractional translation had a bug, the benchmark should rebaselined

**Comment by liyuqian** [comment]
Rebaselined and closing.
