### ISSUE TITLE
Platform view tests in the scenario app should run on Android 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#55326]
Currently, these tests only run on iOS. https://github.com/flutter/engine/blob/master/testing/scenario_app/README.md#adding-a-new-scenario

These tests should also run on Android.

**Comment by blasten** [comment]
cc @dnfield  - I saw your comment on https://github.com/flutter/engine/pull/11319. Did you find any blockers?

**Comment by dnfield** [comment]
The tests are platform specific. Android variants need to be written. They also need somewhere to run.

**Comment by blasten** [comment]
That makes sense. Is it possible to run them on LUCI?  Do you know if espresso has a mechanism for scuba-like testing? I saw https://github.com/facebook/screenshot-tests-for-android

**Comment by dnfield** [comment]
I didn't dig in too much but it should be possible. for iOS I tried to avoid taking on too many third party deps

**Comment by blasten** [comment]
There are two parts to this issue:

- [x] Port the tests to Android (Done)
- [ ] Install the Android emulator on LUCI and enable the engine presubmit

@godofredoc would you mind owning the last item? I think it's fine to install it later when your team has free cycles.

**Comment by digiter** [comment]
Triage: not planned for Q2.

**Comment by blasten** [comment]
What about Q3?

**Comment by godofredoc** [comment]
We'll scope the work needed before the end of Q2 and if it doesn't require a lot of effort we can try to add support for android emulators this quarter if not we'll add to the Q3 okrs.

**Comment by dnfield** [comment]
As an alternative, what if we ran them on Firebase testlab?

We had to disable that because it was flaking due to python version differences (we think). It may be easier to get that working (and more desireable anyway, since we'd be exercising real device tests).

**Comment by blasten** [comment]
I haven't tried running the UI tests on Firebase testlab though.  Maybe it just works?

**Comment by dnfield** [comment]
It needs a little help - you probably want to try doing it as a gameloop test, and there needs to be some kind of communicatio nbetween the test harness and native side so you can throw if there's a failure.

**Comment by dnfield** [comment]
e.g. set up a method channel that you can have the java side listen on for when the test completes with the results.

**Comment by xster** [comment]
Running them on firebase testlab sounds very reasonable to me. Especially since we're not doing performance testing or anything specialized. I think that was the approach @collinjackson was taking as well but I'm not sure whether a wrapper harness to return the result was done.

**Comment by blasten** [comment]
Friendly ping @godofredoc @pcsosinski  - Could this be scoped for Q3?

**Comment by godofredoc** [comment]
We need more information to make this bug more actionable:

- [ ] Which version/versions of the android emulator are needed.
- [ ] Once the emulator is available in bot who is going to start/stop

**Comment by godofredoc** [comment]
@blasten can we use the infra office hours to discuss details?

**Comment by blasten** [comment]
> Which version/versions of the android emulator are needed.
* Nexus 5X - API level 29
* Nexus 5X - API level 28 or lower

> Once the emulator is available in bot who is going to start/stop the emulator

If the [emulator](https://developer.android.com/studio/run/emulator-commandline) tool is available in the `PATH`, then the script that runs the test can start and stop the emulator.

>  which are the test inputs/outputs? e.g. is it a single bash, dart script which exits with 0 on failure or something different?

single bash. This is the current script https://github.com/flutter/engine/blob/master/testing/scenario_app/build_and_run_android_tests.sh although it isn't run atm.

The output is exit with `0` on _success_.

**Comment by godofredoc** [comment]
Perfect, thanks for the information. Turns out that we already have a module to install android tools:

Links:
  * Luci api to install android-sdk: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/android_sdk/api.py
  * Example of how to use the module: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/android_sdk/examples/full.py#12

Seems like what we need is:

 * Create a new empty recipe.
 * Checkout engine and sdk using https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/repo_util/api.py
 * Run the build script
 * Run the test script
 * Test the recipe using led

Once we have some builds we can get a sense of what else will be needed.

**Comment by blasten** [comment]
The last CL to the add the luci recipe has been sent at https://flutter-review.googlesource.com/c/recipes/+/5520.

@godofredoc once submitted, could you own the item to add the presubmit check to flutter/engine?

**Comment by blasten** [comment]
The presubmit has been enabled!

**Comment by dnfield** [comment]
Nice!
