### ISSUE TITLE
Tween.evaluate breaks Law of Demeter

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5532]
Tween.evaluate should take a double and not an Animation.

**Comment by Hixie** [comment]
I believe you're looking for `Tween.lerp(t)`

**Comment by apwilson** [comment]
Yeah I ended up with that in my case but I think my case still stands: Tween.evaluate only takes an Animation to get the value out of it.  It thus should take a double or maybe even not exist at all o_O

**Comment by abarth** [comment]
Yeah, we should audit the callers to see if how it is used.  I was probably influenced too much by the early examples I looked at.

**Comment by Hixie** [comment]
cc @InMatrix

**Comment by Hixie** [comment]
If we're going to change this we should do it soon.

**Comment by Hixie** [comment]
I tried doing this but it's a lost cause. There's over 60 call sites just in the framework, if that's even slightly indicative of usage in the wild, it would break tons of customers.

**Comment by Hixie** [comment]
@InMatrix While looking at this I also looked at the related issue of having a way to do something like:
```dart
   Animation<double> animation = new AnimationController(); // or some other Animation<double>
   Tween<Color> colorTween = new Tween<Color>(begin: Colors.red, end: Colors.blue);
   Animation<Color> result = animation.chain(colorTween);
```

The problem is that the `Animation<T>` class doesn't know if `T` is `double`, and if it isn't, this "chain" method wouldn't be type-correct. It's the same reason Tween in general chains backwards rather than forwards -- it needs to be able to guarantee the type of the parent in the chain, and itself cannot guarantee its own type.

Still looking at what can be done with this, but nothing obvious comes to mind.

**Comment by InMatrix** [comment]
@Hixie Thanks for looking into this. I took a look at the source code, and it looks like AnimationController is always an Animation<double>. Can we give AnimationController a method called _makeAnimation_, which turns a given Animatable object into an Animation?

```dart
AnimationController controller = new AnimationController(); 
Animation<Color> colorAnimation = controller.makeAnimation(
    new Tween<Color> (begin: Colors.red, end: Colors.blue)
);
``` 
This is obviously a less general solution, but hopefully it works?

**Comment by Hixie** [comment]
If we're willing to limit this to `AnimationController`, rather than any `Animation<double>`, then that's more doable, yes.

**Comment by Hixie** [comment]
(BTW do we have a bug for this issue? I couldn't find one.)

**Comment by InMatrix** [comment]
No bug for this yet. It's on my todo list. I'll file one soon and move subsequent discussions there.

**Comment by InMatrix** [comment]
Filed: https://github.com/flutter/flutter/issues/14482

And I think it's sufficient to limit this to AnimationController. It's mainly for pointing users unfamiliar with the animation system to an easier starting point centered on the AnimationController.
