### ISSUE TITLE
Hello i m getting this error RangeError (index): Invalid value: Not in range 0..2, inclusive: 3

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#55339]
i have created country state city drop down but sometime it show this error .RangeError (index): Invalid value: Not in range 0..2, inclusive: 3
 
i have recorded a video here please see what's the issue i don't understand the error
https://drive.google.com/file/d/1swNSSCfpD142b0fih5s-OZTb90NoxBgX/view

**Comment by lynn** [comment]
Hi @atta1234, you should try [asking on StackOverflow](https://stackoverflow.com/questions/tagged/flutter) instead of here.

(When you create a new issue here asking for help, it will tell you:)

> Please don't file a GitHub issue for support requests. GitHub issues are for tracking defects in the product.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by atta1234** [comment]
> Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

i think is is issue ,the error is not clear
