### ISSUE TITLE
Share plugin support for WEB

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#55330]
## Use case
Since Flutter is growing on **web**, it will help to support the plugin Share.
https://pub.dev/packages/share 

## Proposal

Make Share plugin support WEB.

Here is the code in Dart from the documentation:
```
Future share([Map data]) {
  var data_dict = null;
  if (data != null) {
    data_dict = convertDartToNative_Dictionary(data);
  }
  return promiseToFuture(JS("", "#.share(#)", this, data_dict));
}
```
https://api.flutter.dev/flutter/dart-html/Navigator/share.html

Thanks.

**Comment by danielJus** [comment]
Wow this would be a lifesaver I've been trying to find a way to share things from my flutter web apps and have not found anything for it. I hope the flutter team develops something to fix this soon

**Comment by 18Roderick** [comment]
This will be really helpful for our project.

**Comment by luisq2007** [comment]
I'm looking for options for sharing on web too, i can't find anything like it,

**Comment by Cikey18** [comment]
+1...this would help me run my flutter app in web. Thank you Flutter team, you guys are awesome!!

**Comment by jonahwilliams** [comment]
FYI: https://caniuse.com/#feat=mdn-api_navigator_share

**Comment by joumduk** [comment]
before update




var shareData = {
 "title": 'MDN',
  "text": 'Learn web development on MDN!',
     "url": 'https://developer.mozilla.org',
};
window.navigator.share(shareData);


 we can use by code

**Comment by mehrdad78** [comment]
i cant understand that !
i want to share link in flutter web app.
what should i do now?

**Comment by Bilonik** [comment]
For now you have to write your own MethodChannel to Javascript

**Comment by Gershon17** [comment]
@Bilonik How do you go about that?

**Comment by lukelucas247** [comment]
Workaround:



```
import 'dart:html' as html;
import 'dart:js' as js;
import 'dart:typed_data';

import 'package:flutter/foundation.dart';

Future<void> share({
  @required Uint8List bytes,
  @required String filename,
  @required String mimetype,
}) async {
  if (!kIsWeb) {
    throw UnimplementedError('Share is only implemented on Web');
  }

  final blob = html.Blob(
    <Uint8List>[bytes],
    mimetype,
  );
  final url = html.Url.createObjectUrl(blob);
  final html.HtmlDocument doc = js.context['document'];
  final html.AnchorElement link = doc.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
}
```

**Comment by sidrao2006** [comment]
# Implementation
This feature can be easily implemented by using the `Web Share API`. With minimal JS interop, the plugin can be made more accessible and useful.

 # Useful links
[Web Share API - web.dev](https://web.dev/web-share/)
[Web Share API - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by csells** [comment]
I recommend looking at the Flutter Community's plus plugins here: http://plus.fluttercommunity.dev/

They've forked many of our core plugins, including share, and are actively adding support for multiple platforms. Over time, if the plus plugins continue to expand in functionality and maintain a high level of quality, we hope to formally turn these plugins over to the Flutter Community.

**Comment by Sammius** [comment]
> # Implementation
> This feature can be easily implemented by using the `Web Share API`. With minimal JS interop, the plugin can be made more accessible and useful.
> 
> # Useful links
> [Web Share API - web.dev](https://web.dev/web-share/)
> [Web Share API - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

Based on these links, browser support is so low that it's probably best not to do this for the Web at all.

[from the first link](https://web.dev/web-share/#capabilities-and-limitations):
>As of mid 2020, it is only available on Safari and on Android in Chromium forks. See MDN for details.

**Comment by steeling** [comment]
Just a note: having it available in safari means that it's available in any web browser on iOS no? That alone is a huge market since it hits many platforms (embedded browsers in many apps), including chrome on iOS.

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
