### ISSUE TITLE
Flutter  crash : _gpus_ReturnNotPermittedKillClient   in iOS 9.x Version 

### ISSUE THREAD

**Issue by WCrazyStone** [flutter/flutter#55347]
**crash detail :**

```bash
xcrun atos -o Flutter -l 0x00000001088a8000 -arch arm64
0x00000001088e48c4
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (in Flutter) (thread:352)


0x00000001088e50b8
fml::MessageLoopDarwin::Run() (in Flutter) (message_loop_darwin.mm:47)


0x00000001088e51dc
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)

0x00000001088e2f58
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:125)


0x00000001088f3ad4
std::__1::__function::__func<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)> const&)::$_1::operator()()::'lambda'()>, std::__1::allocator<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)> const&)::$_1::operator()()::'lambda'()> >, void ()>::operator()() (in Flutter) (functional:1757)

0x00000001088e4404
fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) (in Flutter) (sync_switch.cc:32)

0x00000001088f413c
std::__1::__function::__func<flutter::UploadRasterImage(sk_sp<SkImage>, fml::WeakPtr<flutter::IOManager>, fml::tracing::TraceFlow const&)::$_3, std::__1::allocator<flutter::UploadRasterImage(sk_sp<SkImage>, fml::WeakPtr<flutter::IOManager>, fml::tracing::TraceFlow const&)::$_3>, void ()>::operator()() (in Flutter) (functional:1651)


0x0000000108b1b264
SkImage::MakeCrossContextFromPixmap(GrContext*, SkPixmap const&, bool, bool) (in Flutter) (SkImage_Gpu.cpp:515)
```

**flutter doctor detail:**
Doctor summary (to see all details, run flutter doctor -v):
[```console
✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by WCrazyStone** [comment]
Thread 8 Crashed:
0   libGPUSupportMercury.dylib          0x0000000191849f08 _gpus_ReturnNotPermittedKillClient + 12
1   Flutter                             0x0000000108b0f264 0x000000010889c000 + 2568804
2   Flutter                             0x00000001088e813c 0x000000010889c000 + 311612
3   Flutter                             0x00000001088d8404 0x000000010889c000 + 246788
4   Flutter                             0x00000001088e7ad4 0x000000010889c000 + 309972
5   Flutter                             0x00000001088d6f58 0x000000010889c000 + 241496
6   Flutter                             0x00000001088d91dc 0x000000010889c000 + 250332
7   CoreFoundation                      0x00000001839315f4 ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
8   CoreFoundation                      0x0000000183931298 ___CFRunLoopDoTimer + 884
9   CoreFoundation                      0x000000018392e9ac ___CFRunLoopRun + 1520
10  CoreFoundation                      0x000000018385d680 _CFRunLoopRunSpecific + 384
11  Flutter                             0x00000001088d90b8 0x000000010889c000 + 250040
12  Flutter                             0x00000001088d88c4 0x000000010889c000 + 248004
13  libsystem_pthread.dylib             0x00000001835e3b28 __pthread_body + 156
14  libsystem_pthread.dylib             0x00000001835e3a8c __pthread_body + 0
15  libsystem_pthread.dylib             0x00000001835e1028 _thread_start + 4

**Comment by WCrazyStone** [comment]
Possibly the same question: 
https://github.com/flutter/flutter/issues/34914

**Comment by iapicca** [comment]
Hi @WCrazyStone 
I see there's an open [issue](https://github.com/flutter/flutter/issues/54363) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
