### ISSUE TITLE
Figure out how to handle hero animations during iOS back gestures

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5535]
In https://github.com/flutter/flutter/pull/5512 we ran into the issue that it's not at all clear how to handle hero animations between pages when you have an iOS-style transition, especially in the case of the touch-mediated back gesture.

Seth, could you reach out to the UX folk and figure out what it is they want? Sample hero animations are the toolbar cross-fades, images flying from a list to a full-bleed position, the floating action button moving to its new position, changing colour, and changing icon, etc.

**Comment by sethladd** [comment]
Great question. Will queue it up.

**Comment by sethladd** [comment]
Question has been sent to our friends in material team.

**Comment by sethladd** [comment]
Non-update: no response yet.

**Comment by sethladd** [comment]
I believe we have a solution that works fairly well, as demoed by/in the gallery. When back gesturing, we move the entire piece of material off the screen.

Talking to designers in material, they suggest that different pieces of material can move around and move up and down. For example, a piece of material can move "up", let its previous material transition away, and then it can move back down.

If we have more specific questions, we can go to office hours.
