### ISSUE TITLE
Default .gitignore ignores Podfile.lock

### ISSUE THREAD

**Issue by kkogut95** [flutter/flutter#55357]
Hi,

Recently building Flutter apps in CI that I use failed to create an iOs app. The reason was that I was using the default .gitignore from this repository, that ignores the `ios/Podfile.lock`. I did a little searching and found out, that this file should be added to the repository: https://github.com/flutter/flutter/issues/9299#issuecomment-295221934 

In that case, shouldn't the `!/ios/Podfile.lock` be added to the default .gitignore? I can, of course, create PR with that change, but I wanted to get your opinion first.

Thanks!

**Comment by jmagman** [comment]
The Podfile no longer has absolute paths in it, which was why https://github.com/flutter/flutter/issues/9299 was closed.  I'm going to re-open that one and close this as a duplicate.
Thanks for pointing it out!
