### ISSUE TITLE
The following assertion was thrown building UserResult(dirty):

### ISSUE THREAD

**Issue by bakhtkhilji23** [flutter/flutter#55361]
════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building UserResult(dirty):[39;49m
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'



**Comment by VladyslavBondarenko** [comment]
Hi @bakhtkhilji23 
Try https://github.com/flutter/flutter/issues/40214#issuecomment-530587931
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by bakhtkhilji23** [comment]
> Hi @bakhtkhilji23
> Try [#40214 (comment)](https://github.com/flutter/flutter/issues/40214#issuecomment-530587931)
> Closing, as this isn't an issue with Flutter itself,
> if you disagree please write in the comments and I will reopen it
> Thank you

Thanks @VladyslavBondarenko for responding,
this exception occurred when I have uninstalled the app from the emulator and when I rebuild my application the exception has thrown
