### ISSUE TITLE
Non-overflowing containers should not disable overscroll on iOS.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5537]
Right now if you have any scrollable widget on iOS that does not require any clipping, overscroll is desabled; it gets enabled only when the chid/children get bigger and require clipping. On iOS, scrolling should either always work (i.e. overscroll even if a list is short) or not be scrollable at all.

**Comment by eseidelGoogle** [comment]
Maybe this is the root cause of https://github.com/flutter/flutter/issues/5526?

**Comment by Hixie** [comment]
This isn't quite right. For example, a dialog box shouldn't overscroll if its children are fully visible, but should if they are not.

**Comment by abarth** [comment]
This issue is fixed, but we now have the reverse bug in some places.
