### ISSUE TITLE
[webview_flutter] SSL and Server Trust

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#55371]
I need to call an https page and proceed with any ssl error.

Does the plugin already have any properties to address this, or do I have to implement something in specific projects?

**Comment by TahaTesser** [comment]
Hi @mdmota 
I am not sure what you asking here but skipping SSL error is  not possible
Check this [comment](https://github.com/flutter/flutter/issues/36925#issuecomment-570320289)

Related to [#36925](https://github.com/flutter/flutter/issues/36925)

if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by mdmota** [comment]
I managed to solve it by overwriting the native code. FlutterWebViewClient.java

**Comment by SelanDeemantha** [comment]
hi @mdmota, Can you share how did you manage the ssl error checking
