### ISSUE TITLE
web_benchmarks_canvaskit build_material_checkbox.canvaskit.drawFrameDuration.outlierAverage regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55382]
Looks like https://github.com/flutter/flutter/pull/55160. It's been slowly climbing before that:

![Screen Shot 2020-04-22 at 9 10 34 AM](https://user-images.githubusercontent.com/1435716/80005981-241cd500-8479-11ea-8ac0-95ba931dcb08.png)

**Comment by yjbanov** [comment]
Looks like this was temporary noise. Also we're switching from outlierAverage to outlierRatio, so I'll archive all the past outlierAverage data.
