### ISSUE TITLE
ScenariosTests: -[AppLifecycleTests testFlutterViewControllerDetachingSendsApplicationLifecycle] is flakey

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#55387]
[fuchsia-linux-sdk-flutter-engine autoroller](https://autoroll.skia.org/r/fuchsia-linux-sdk-flutter-engine?tab=status) has failed a few times in the past 24 hours because of `ScenariosTests: -[AppLifecycleTests testFlutterViewControllerDetachingSendsApplicationLifecycle]`

example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8882312352591128592/+/steps/Scenario_App_Unit_Tests/0/stdout

**Comment by chinmaygarde** [comment]
This doesn't seem to be happening anymore. Closing.

**Comment by dnfield** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8874867261790459648/+/steps/Scenario_App_Integration_Tests/0/stdout

**Comment by cbracken** [comment]
This closed the tree today:
Build: https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6686

Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870048856606792720/+/steps/Scenario_App_Integration_Tests/0/stdout

**Comment by chinmaygarde** [comment]
From triage of user reported instances of presubmit failures:
* https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/9797
* https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/10081

**Comment by zanderso** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/40817
