### ISSUE TITLE
flutter_gallery_v2_web_compile_test Benchmarks need baselines

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55380]
flutter_gallery_v2_web_compile_test (new_gallery_dart2js_millis new_gallery_dart2js_size new_gallery_dart2js_size_gzip) all need baselines.

Is it sufficient to auto-baseline them?

![Screen Shot 2020-04-22 at 9 03 29 AM](https://user-images.githubusercontent.com/1435716/80005234-27fc2780-8478-11ea-919c-743b167899c0.png)

**Comment by jonahwilliams** [comment]
Removing from tools designation since this is a web benchmark

**Comment by yjbanov** [comment]
Done.
