### ISSUE TITLE
CanvasKit 0.12 -> 0.14 performance regression

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#55389]
The upgrade of CanvasKit from 0.12 to 0.14 (https://github.com/flutter/engine/pull/17849) regressed some of the benchmarks. Given that CanvasKit is experimental, instead of reverting the roll let's see if we can fix it in a future release.

![canvaskit-0 14-regression-4](https://user-images.githubusercontent.com/211513/80011567-e6bc4580-8480-11ea-86ec-49a6420c5279.png)

![canvaskit-0 14-regression-3](https://user-images.githubusercontent.com/211513/80011572-e91e9f80-8480-11ea-98e9-4ede09a90186.png)

![canvaskit-0 14-regression-2](https://user-images.githubusercontent.com/211513/80011579-eae86300-8480-11ea-884e-0c56a6910ed4.png)

![canvaskit-0 14-regression-1](https://user-images.githubusercontent.com/211513/80011586-ed4abd00-8480-11ea-9d59-f48f86c3c790.png)

/cc @dnfield @hterkelsen @kjlubick

**Comment by kjlubick** [comment]
Do we have any idea what calls to canvaskit got slower? i.e. what these benchmarks have in common?

One item on the changelog that I see that I am hoping is *not* the culprit is "We now compile/ship with Emscripten v1.39.6"

**Comment by yjbanov** [comment]
I haven't looked in-depth. The benchmarks indicate that one slow part is the one that calls `SkPictureRecorder.finishRecordingAsPicture` and `SkPictureRecorder.delete` (I'm not sure what the breakdown is as the benchmark measures them both).

**Comment by kf6gpe** [comment]
@yjbanov Any update on this? (Asking for Performance weekly triage).

**Comment by yjbanov** [comment]
Through various efforts our benchmark numbers have dropped drastically in the past few weeks. I consider this as fixed.
