### ISSUE TITLE
Flutter does not update the default build from command line on ios when using multiple flavors and schemes.

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#55395]
## Steps to Reproduce

1. Create a project with multiple flavors, and configure the ios schemes.
2. Running the command flutter build ios --flavor X will not change the default scheme for command line tools.

This results in wrong compilation properties.

By that, flutter says its compiling another package but its including the right certificate and bundle in to the app.

<img width="669" alt="Schermata 2020-04-22 alle 20 41 08" src="https://user-images.githubusercontent.com/45635090/80021127-5ca0cb00-84da-11ea-9ba4-9173c2caa9bf.png">

<details>
  <summary>Logs</summary>

```
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.17.0 at /Users/nicolas/dev/flutter_sdk/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/nicolas/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (3 available)
    • Chrome     • chrome       • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server   • web-javascript • Flutter Tools

```
</details>

**Comment by jmagman** [comment]
Your screenshot is showing build configurations, not schemes.  Can we get more exact reproduction steps, and preferably an example app that reproduces?

**Comment by nicolasvac** [comment]
Hi @jmagman. Yes, basically what happens is:
- By adding multiple schemes and build configurations, you have the ability to use the --flavor command.
- However, when launching flutter build ios --flavor A, this is what the console writes:
`Building com.XXXX.FLAVOR_B for device (ios-release)...` instead of flavor A.

By changing the option i've highlighted in the previous screenshot to the wanted flavor (in this case FLAVOR A), it correctly outputs:
`Building com.XXXX.FLAVOR_A for device (ios-release)...`

Now i can't tell if this actually changes something in the App or it is just a console-log bug, because my flavors are just for UX changes, like colors and assets.
