### ISSUE TITLE
Cocoapods not working

### ISSUE THREAD

**Issue by srburton** [flutter/flutter#55396]
I am trying for days a solution to this problem and I have not been successful yet. Could someone help me?

Note: I tried all the solutions above ...

![Screenshot_1](https://user-images.githubusercontent.com/15394508/80019784-6e6c7900-84ae-11ea-92dd-6b2931c5b6db.png)

- POD (COMMAND...)

![Screenshot_5](https://user-images.githubusercontent.com/15394508/80020598-af18c200-84af-11ea-8a8d-06432c33adc3.png)

![Screenshot_7](https://user-images.githubusercontent.com/15394508/80020609-b3dd7600-84af-11ea-89fb-891cbc4070e8.png)

- RUBY --VERSION

![Screenshot_8](https://user-images.githubusercontent.com/15394508/80020953-35cd9f00-84b0-11ea-846d-96bd3676e3d0.png)

- GEM LIST

![Screenshot_9](https://user-images.githubusercontent.com/15394508/80021101-6c0b1e80-84b0-11ea-86c5-c9ad4c9fa988.png)

- BREW LIST

![Screenshot_10](https://user-images.githubusercontent.com/15394508/80021255-9ceb5380-84b0-11ea-8671-b835dfd7b1d5.png)

- MAC VERSION - CATALINA

![Screenshot_2](https://user-images.githubusercontent.com/15394508/80020730-dcfe0680-84af-11ea-921a-d604c9be868d.png)

**Comment by srburton** [comment]
I found the problem after trying to correct another warning, I'm glad cocoapods worked now.

follow the warning

![Screenshot_11](https://user-images.githubusercontent.com/15394508/80027086-91505a80-84b9-11ea-8258-0b687dbe2ca8.png)

## Solution

![Screenshot_13](https://user-images.githubusercontent.com/15394508/80027102-99a89580-84b9-11ea-9741-4cea9514eaf3.png)

**Comment by can-lan** [comment]
Thanks
