### ISSUE TITLE
SystemChrome.setEnabledSystemUIOverlays won't work

### ISSUE THREAD

**Issue by skopcsa** [flutter/flutter#55397]
After I've updated my flutter SDK to latest, SystemChrome.setEnabledSystemUIOverlays stopped working (it used to hide the top and bottom bars but now they are back).

Is there any solution or workaround?

![image](https://user-images.githubusercontent.com/57302781/80023157-cc688300-84e5-11ea-86f9-78544687884c.png)

**Comment by VladyslavBondarenko** [comment]
Hi @skopcsa 
could you please provide your `flutter doctor -v` and post a minimal complete code sample to reproduce it?

**Comment by skopcsa** [comment]
Hello,

I just found the issue.
It seems like in the latest version, you weren't suppose to call "SystemChrome.setEnabledSystemUIOverlays([]);"before calling runApp (in main function).


Once I moved this to a my main statefull widget everything is fixed. 

I'll close the issue XD
