### ISSUE TITLE
Refactor dartdoc.dart for proper versioning

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#55409]
[TODO audit]

From original TODO : https://github.com/flutter/flutter/blob/72986f7bcf8b0a4f9566076f8500975e7ba8fdd7/dev/tools/dartdoc.dart#L53

> // TODO(dnfield): We should make DartDoc able to avoid emitting this. If we
  // use the real value here, every file will get marked as new instead of only
  // files that have otherwise changed. Instead, we replace it dynamically using
  // JavaScript so that fewer files get marked as changed.
  // https://github.com/dart-lang/dartdoc/issues/1982

https://github.com/dart-lang/dartdoc/issues/1982 was resolved by https://github.com/dart-lang/dartdoc/pull/2010

Regarding next actions here, per @dnfield 
> https://github.com/dart-lang/dartdoc/pull/2010/files added the ability to exclude the version in the footer info. I can no longer remember if it makes more sense to still do it this way or not - we would still want to inject the actual version number at runtime, but if we can make that dartdoc option work with that logic we can drop the ogic here that is forcing the version to initially appear as 0.0.0.

> This is all being done to prevent firebase from seeing us changing every single page of the docs on every single commit.

**Comment by dnfield** [comment]
I'm going to close this. What we have works, and it's not worth making a small and potentially erroneous change to end up doing the same thing.
