### ISSUE TITLE
`flutter version` fails to parse the v in new tags correctly

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#55421]
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue:

On the **Dev channel**, either Windows, Mac, or Linux, versions should start with a **v**. 

There is an issue when switching to a certain version and using the exact version name. For example:
`flutter version 1.18.0-dev.5.0`  will try to switch the version to **1.18.0-de.5.0**
Using `flutter version v1.18.0-dev.5.0` will switch to the correct version **1.18.0-dev.5.0**

I think the cause is that the **flutter version** command strips the first **v** that is found in the version tag.

This happens for the **Dev channel** starting with version tag **1.17.0-dev.0.0** 

This same issue appears on the latest published **Beta channel** version tag, **1.17.0-dev.3.1**.

**Comment by zanderso** [comment]
Users are warned against using this command, and it is expected that we'll remove it:

https://github.com/flutter/flutter/issues/53364

Given this, I'm removing the 'TODAY' label, but leaving this open in case @christopherfujino can identify a quick/easy fix.

**Comment by Constans** [comment]
I used `flutter version` from the **dev** channel to get back to a version that wasn't working with the packages I am using. 

In the latest version of **dev** it was complaining that the **flutter_localizations** package doesn't like **path** <1.7.0 and when setting the version of **path** to ^1.7.0 then said that **hive** and **hive_flutter** doesn't like **path ^1.7.0** (which may require an upgrade of the hive and hive_flutter packages)

I don't report issues with the latest releases on **dev** or **master** channels. Instead, if something breaks I go back one version, or more.

I tried `flutter downgrade` though it seems that only **master** and **beta** are able to **downgrade**. Maybe the **dev** channel will be too in the near future.

Anyway, the issue is that it strips that **v** letter from the wrong place. The solution would be to strip it only if it is at index 0.

**Comment by christopherfujino** [comment]
Reopening as the fix was reverted.

**Comment by danielnovograd** [comment]
Temporary workaround is to just add an extra `v` (e.g. `-devv`)

**Comment by pcsosinski** [comment]
removing CP label based on yesterday's conversation
