### ISSUE TITLE
Add onSecondaryTap to GestureDetector for consistent with onTap

### ISSUE THREAD

**Issue by Slihao** [flutter/flutter#55423]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
@gspencergoog Should we add a stock gesture detector for this?

**Comment by gspencergoog** [comment]
Well, there's already `onSecondaryTapDown`, which does this.  There is no `onSecondaryTap`, however, which might be good to add.

**Comment by stuartmorgan** [comment]
Oops, I totally missed the `*Secondary*` calls when looking at `GestureDetector`. Probably would be nice to add that version for consistency if nothing else though.

**Comment by gspencergoog** [comment]
Fixed by #55494
