### ISSUE TITLE
Flutter web dropdown not suggesting item when i type keyboard keys.

### ISSUE THREAD

**Issue by Dhana2513** [flutter/flutter#55438]
I used dropdown list in flutter web,
after opening dowpdown when I type any character on keyboard, it should suggest item based on typing characters.

**Comment by TahaTesser** [comment]
Hi @Dhana2513 
I am not sure just a dropdown list suppose to provide suggestion?  
can you please provide your `flutter doctor -v` and `flutter run -d Chrome --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jlubeck** [comment]
I came here to open this same issue.
On web, it is expected that when you are filling a form and there is a dropdown, that you can type and get the item that matches what you type.

I don't think this is a bug but a feature request.

**Comment by TahaTesser** [comment]
@jlubeck 
Thanks for clarifying

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/46824

**Comment by jlubeck** [comment]
@yjbanov why did you close this ticket? Not sure what you meant by "deduplicating", but this is definitely not a duplicate of that ticket
