### ISSUE TITLE
image_picker: ^0.6.5+2 error

### ISSUE THREAD

**Issue by 120011676** [flutter/flutter#55442]
E/flutter ( 5067): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter ( 5067): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5067): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 5067): <asynchronous suspension>
E/flutter ( 5067): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:85:40)

**Comment by TahaTesser** [comment]
Hi @120011676 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by 120011676** [comment]
Other code impact after study,closed
