### ISSUE TITLE
messy text issues

### ISSUE THREAD

**Issue by kerneltea** [flutter/flutter#55445]
My Flutter version is 1.15.22. I'm experiencing a weird issue and I think this should be reported to you.

The steps to replicate this issue are,
1. while I am on the renderbox page, and stay at this page for more than 10 seconds,
2. then I go back to the upper level - navigator.pop, and the texts on this page in the messy code format.
![image](https://user-images.githubusercontent.com/1260653/80076700-20737600-857f-11ea-9e38-edb8fa87be7c.png)

3. however, if I use TextPainter to input a line of random texts on the top left corner of renderbox, then on navigator.pop, the messy code issue disappeared. It seems to be a little weird. 
![image](https://user-images.githubusercontent.com/1260653/80076725-2a957480-857f-11ea-8ae5-df7e8baf35fb.png)

Could you please kindly help to check out what the issue is? Thanks!

Android and IOS have such problems
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: 1.15.22

**Comment by TahaTesser** [comment]
hI @kerneltea 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kerneltea** [comment]
@TahaTesser 
**flutter doctor -v**

[✓] Flutter (Channel unknown, v1.15.22, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.15.22 at /Users/kerneltea/dev/flutter
    • Framework revision 1606d87834 (5 weeks ago), 2020-03-16 00:36:01 -0400
    • Engine revision 6801b4dae7
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 7079c49b05)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kerneltea/Library/Android/sdk
    • Android NDK at /Users/kerneltea/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone • 4a5c5fa54a6dfd89d073b37664462ffdc284a529 • ios • iOS 12.4.3

**Comment by kerneltea** [comment]
@TahaTesser
**flutter run -verbose**

[Flutter run verbose log!! click here](https://raw.githubusercontent.com/kerneltea/public/master/flutterverbose.log)

**Comment by kerneltea** [comment]
![image](https://user-images.githubusercontent.com/1260653/80093809-c16e2b00-8597-11ea-916d-f9d0a83730a5.png)
then I go back to the upper level - navigator.pop, and the texts on this page in the messy code format.

![image](https://user-images.githubusercontent.com/1260653/80093904-ebbfe880-8597-11ea-8a30-fdbfcdd556cd.png)
if I use TextPainter to input a line of random texts on the top left corner of renderbox, then on navigator.pop, the messy code issue disappeared. It seems to be a little weird.

**Comment by TahaTesser** [comment]
Hi @kerneltea 
Please refrain from posting screenshots, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by CoderMing** [comment]
I got a same wrong in Linux platform.
![image](https://user-images.githubusercontent.com/25007676/80566866-7edca080-8a26-11ea-9849-e217a83a55e5.png)

When I triggered an animation, text seems got a wrong rendering result.

It seems to start appearing in early April.

```
[✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-9.0.pre.14 at /home/m/workspace/flutter
    • Framework revision dd88b20435 (3 days ago), 2020-04-25 19:02:03 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is
      localhost,127.0.0.1,127.0.0.0/8,::1,.oa.com,.qq.com,.mnet2.com,.tencent.com
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux
```

**Comment by TahaTesser** [comment]
Hi @kerneltea 
Without code sample  we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thank you
