### ISSUE TITLE
one error from TextPainter.didExceedMaxLines

### ISSUE THREAD

**Issue by yanghaoge** [flutter/flutter#55459]
Changing the system font size causes TextPainter.didExceedMaxLines return  error value;

Modify the system font is less than the standard font will cause under the condition of the text has fully displayed, TextPainter. DidExceedMaxLines tip was part of the text not shown completely

**Comment by TahaTesser** [comment]
Hi @yanghaoge 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by yanghaoge** [comment]
![flutterversion](https://user-images.githubusercontent.com/19761894/80189254-fab0a480-8644-11ea-932a-951b30c8523f.png)




    Widget getContent(BuildContext context,String contentStringText){
    int maxLines = 4;
    double fontSize = 18.0;
    return  Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        LayoutBuilder(builder: (context, size) {
          var span = TextSpan(
            text: contentStringText,
            style: TextStyle(fontSize: fontSize,color: Color(0xff666666),),
          );

          var tp = TextPainter(
            maxLines: maxLines,
            textAlign: TextAlign.left,
            textDirection: TextDirection.ltr,
            text: span,
          );
          tp.layout(maxWidth: size.maxWidth);
          var exceeded = tp.didExceedMaxLines;

          return Column(crossAxisAlignment: CrossAxisAlignment.start,children: <Widget>[

            Text.rich(
              span,
              maxLines: isShowAll ? 100 : 4,
            ),
            Offstage(
              offstage: !exceeded,
              child: InkWell(
                onTap: () {
                  setState(() {
                    isShowAll = !isShowAll;
                  });
                },
                child: Padding(
                  padding: const EdgeInsets.only(left: 0, top: 5.0),
                  child: Text(
                    isShowAll ? "hide" : "showAll",
                    style: TextStyle(
                      color: Color(0xfffc5751),
                      fontSize: 12,
                    ),
                  ),
                ),
              ),
            ),

          ]);
        }),
      ],
    );
  }


then changed the system fontSize Smaller
![changsize](https://user-images.githubusercontent.com/19761894/80189993-24b69680-8646-11ea-8cdc-8a1da8c5ea7e.jpg)

The text is displayed but tp.didExceedMaxLines returned true；
![show](https://user-images.githubusercontent.com/19761894/80190036-38fa9380-8646-11ea-895e-9e3464f69ba2.jpg)

@TahaTesser  Thank you for your reply!  
myphone: device product:LLD-AL20 model:LLD_AL20 device:HWLLD-H2 transport_id:5;
The problem also applies to other phones, such as the iphone 6splus。

**Comment by yanghaoge** [comment]
The text is already fully displayed on the screen,but tp.didExceedMaxLines returned an error value is "true"；

**Comment by TahaTesser** [comment]
Hi @yanghaoge 
`tp.didExceedMaxLines` correctly return boolean value on latest `dev` channel
```
I/flutter (31660): true
```
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (3 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools
• No issues found!
```

</details>

Can you please upgrade to latest `dev` channel and try again?

Thank you

**Comment by TahaTesser** [comment]
Hi @yanghaoge 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
