### ISSUE TITLE
IOS error google-maps-flutter

### ISSUE THREAD

**Issue by illiashvedov** [flutter/flutter#55456]
There was a problem on iOS. The map is opened with a separate screen, there are markers on it, by clicking on the maker a popup is displayed using the stack on top of the map, from this popup I switch to another screen, after returning to the map I’m on another marker, there is no such problem on the android. The onCameraMove function on the map returns new values ​​after returning to the map screen, what could be the problem? And did anyone have a similar situation?

**Comment by TahaTesser** [comment]
Hi @illiashvedov 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by illiashvedov** [comment]
Hi, @TahaTesser 

```
**flutter doctor -v**
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale ru-UA)
    • Flutter version 1.12.13+hotfix.9 at /Users/flutter/Documents/src/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/flutter/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Test X • b5d974b2dd81a8576f3b8ef7547ecca4fe50c1d0 • ios • iOS 13.3.1

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @illiashvedov 
We need more information  
can you please provide your  `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by illiashvedov** [comment]
Hi, @TahaTesser 
Yesterday I tried to recreate this problem on a new project, and to my regret, I was not able to do this. I can not provide the code in which this error is reproduced due to the fact that it is protected by NDA.

**Comment by TahaTesser** [comment]
Hi @illiashvedov 
You don't have to provide full source code but just a minimal sample code
Please use official [example](https://pub.dev/packages/google_maps_flutter#-example-tab-) and modify it and reproduce the issue, it would help us to understand the issue.
Thank you

**Comment by TahaTesser** [comment]
Hi @illiashvedov 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
