### ISSUE TITLE
Missing Frames In Gallery App

### ISSUE THREAD

**Issue by tjerkw** [flutter/flutter#5545]
In a lot of places in the gallery app i'm seeing missing frames. Expected animations to be smooth but this is not always the case.

## Steps to Reproduce

Goto Shrine, click on the sneakers, then press back: 26 fps.

(Also saw this in the pesto demo, and the dialog boxes animation seems slow (no hard data))

Device: Galaxy S6

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/tjerkw/dev/tools/flutter
    • Framework revision 9a0a0d9903 (11 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /Users/tjerkw/Library/Android/sdk
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_74-b02)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

## Logs and Crash Reports

See screenshot.
![flutter-slow-performance](https://cloud.githubusercontent.com/assets/818865/17885211/7819a204-691c-11e6-88e8-924db9205d65.png)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by sethladd** [comment]
Thanks for the report! We're still working on performance optimizations.

See also: https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22customer%3A+gallery%22+label%3A%22%E2%9A%A0+astounding+performance%22

Keep the feedback coming!

**Comment by sethladd** [comment]
Really appreciate the testing. I'm going to close this particular issue because we're tracking individual Shrine perf issues in other bugs. Definitely interested in how Flutter behaves on a variety of different devices.
