### ISSUE TITLE
Pub get flutter_test version solving failed

### ISSUE THREAD

**Issue by AlexPritchin** [flutter/flutter#55453]
Hello. I have an issue trying to add a package to my project. I want to add a path package of version 1.7.0. But when I run `flutter pub get` I'm getting this error.
`Because every version of flutter_test from sdk depends on path 1.6.4 and pressure_viewer depends on path ^1.7.0, flutter_test from sdk is forbidden.
So, because pressure_viewer depends on flutter_test any from sdk, version solving failed.`
I saw on GitHub that there is path 1.7.0 in pubspec.yaml of flutter_test. But on my pc there is path 1.6.4 in pubspec.yaml of flutter_test in flutter/packages folder. So I guess I should update flutter_test but running `flutter pub upgrade` and `flutter upgrade` doesn't update it. Of course I can downgrade to using path of 1.6.4 in my project but I want to use latest versions of all packages. I'm on stable channel of flutter and `flutter doctor` gives me green checkmarks for all options in list. So what should I do to update flutter_test?

**Comment by VladyslavBondarenko** [comment]
Hi @AlexPritchin 
you can switch to the dev channel (current is `v1.18.0-6.0.pre`). The path is updated in master and in dev already, but not yet in beta and stable.
Closing as fixed and there is no need to track the issue of updating `path` in `flutter_test`

**Comment by AlexPritchin** [comment]
Thank you.

**Comment by pratikbutani** [comment]
Have you checked [this article](https://pratikbutani.medium.com/flutter-2-upgrade-flutter-version-solving-failed-error-33ac1087cb6b)
