### ISSUE TITLE
Bug when wrap-widget compute intrinsic height

### ISSUE THREAD

**Issue by MbIXjkee** [flutter/flutter#55467]
I found a problem in framework. When wrap widget counting intrinsic height and width it not use space in check. When checking, the distance between the elements is not taken into count, but in the future it is added to the size. This leads to incorrect layout building. When the last element fits without a space, but causes an overflow with a space, the wrapper returns its height as for 1 line, but later on uses 2 for rendering.

**Comment by iapicca** [comment]
Hi @MbIXjkee 
can you please provide your `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you

**Comment by MbIXjkee** [comment]
Hi @iapicca 
it's flutter doctor

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287, locale ru-RU)
    • Flutter version 1.12.13+hotfix.8 at /Users/zotev/dev/sdk/flutter
    • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zotev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by MbIXjkee** [comment]
I found this bug on business project, and give you simple avatar of layout.

For reproduce this bug you can change space in wrap from 1000 to 0.
On 1000 value wrap count themself as found 1 row and return bad hight, that hight use intrinsic hight for calculate height and we got overflow.
If you change space to 0, space should not be used for calculate, and wrap should return correct value

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WrapBug(),
    );
  }
}

class WrapBug extends StatefulWidget {
  WrapBug({Key key}) : super(key: key);

  @override
  _WrapBugState createState() => _WrapBugState();
}

class _WrapBugState extends State<WrapBug> {
  final _list = <Widget>[];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("WRAP WRONG SAMPLE"),
      ),
      body: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) => ListView(
          children: <Widget>[
            ConstrainedBox(
              constraints: constraints.copyWith(
                minHeight: constraints.maxHeight,
                maxHeight: double.infinity,
              ),
              child: IntrinsicHeight(
                child: Column(
                  children: <Widget>[
                    Container(
                      color: Colors.red,
                      width: double.infinity,
                      height: 300,
                      child: Center(
                        child: Text("Some elements with some hight"),
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(top: 25, bottom: 8, left: 16.0, right: 16),
                      child: Wrap(
                        spacing: 1000,
                        runSpacing: 18,
                        children: [
                          ..._list,
                          InkWell(
                            onTap: _addElement,
                            child: Container(
                              width: 88,
                              height: 88,
                              color: Colors.teal,
                              child: Center(
                                child: Text("Tap"),
                              ),
                            ),
                          )
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _addElement() {
    setState(() {
      _list.add(
        Container(
          width: 88,
          height: 88,
          color: Colors.teal,
          child: Center(
            child: Text("Element ${_list.length}"),
          ),
        ),
      );
    });
  }
}

**Comment by MbIXjkee** [comment]
[main.dart.zip](https://github.com/flutter/flutter/files/4527853/main.dart.zip)

**Comment by iapicca** [comment]
Hi @MbIXjkee 
thanks for providing the code sample,
i'm copy pasting it from your file to make it easily accessible

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WrapBug(),
    );
  }
}

class WrapBug extends StatefulWidget {
  WrapBug({Key key}) : super(key: key);

  @override
  _WrapBugState createState() => _WrapBugState();
}

class _WrapBugState extends State<WrapBug> {
  final _list = <Widget>[];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("WRAP WRONG SAMPLE"),
      ),
      body: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) => ListView(
          children: <Widget>[
            ConstrainedBox(
              constraints: constraints.copyWith(
                minHeight: constraints.maxHeight,
                maxHeight: double.infinity,
              ),
              child: IntrinsicHeight(
                child: Column(
                  children: <Widget>[
                    Container(
                      color: Colors.red,
                      width: double.infinity,
                      height: 300,
                      child: Center(
                        child: Text("Some elements with some hight"),
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(top: 25, bottom: 8, left: 16.0, right: 16),
                      child: Wrap(
                        spacing: 1000,
                        runSpacing: 18,
                        children: [
                          ..._list,
                          InkWell(
                            onTap: _addElement,
                            child: Container(
                              width: 88,
                              height: 88,
                              color: Colors.teal,
                              child: Center(
                                child: Text("Tap"),
                              ),
                            ),
                          )
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _addElement() {
    setState(() {
      _list.add(
        Container(
          width: 88,
          height: 88,
          color: Colors.teal,
          child: Center(
            child: Text("Element ${_list.length}"),
          ),
        ),
      );
    });
  }
}
```

**Comment by MbIXjkee** [comment]
Thank you for help, @iapicca 
I could not find how to insert the right formatted code, so I attached the file

**Comment by MbIXjkee** [comment]
I fixed a mistake in the calculations in this pr https://github.com/flutter/flutter/pull/55469

**Comment by markusaksli-nc** [comment]
Closing as fixed as per https://github.com/flutter/flutter/issues/55467#issuecomment-618955984
