### ISSUE TITLE
new_gallery__transition_perf benchmarks need baselines

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55471]
Lots o' red there! :)

They look pretty stable -- if these numbers are about what we'd expect, let's set baselines here.

![Screen Shot 2020-04-23 at 9 21 25 AM](https://user-images.githubusercontent.com/1435716/80123516-d7ea9700-8543-11ea-8739-ed11039239ab.png)

**Comment by kf6gpe** [comment]
These benchmarks have been baselined, but are still red --- have they regressed, or do we need to reset the baselines again now that we have more data?

![Screen Shot 2020-05-11 at 8 55 28 AM](https://user-images.githubusercontent.com/1435716/81582701-2f22a100-9365-11ea-87f5-2ec6f7f032c4.png)

**Comment by liyuqian** [comment]
It's red because of https://github.com/flutter/flutter/issues/55471 . Its fix https://github.com/flutter/engine/pull/18255 had finally been rolled in https://github.com/flutter/flutter/commit/456d80b9ddd74b4b5ca3b77bbfb70ab0e05d3fa8 and I confirm that all metrics turned green.
