### ISSUE TITLE
Flutter Doctor: CocoaPods installed but not working.

### ISSUE THREAD

**Issue by dwicks99** [flutter/flutter#55473]
I'm trying to run Pod Setup after installing cocoapods and getting this error:

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:97:in `expand_path': user flutter doesn't exist (ArgumentError)

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:97:in `block in which'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:96:in `each'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:96:in `which'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:117:in `which!'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:143:in `capture_command'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:116:in `git_version'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:49:in `run'

	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'

	from /usr/local/bin/pod:22:in `load'

	from /usr/local/bin/pod:22:in `<main>'

I've googled the "user flutter doesn't exist (ArgumentError)" but not finding much help. Most of the comments say to reinstall cocoapods or do version 1.7.5. I continue to get the same error after reinstalling and trying various things. 

Any thoughts??

**Comment by iapicca** [comment]
Hi @dwicks99 
from the title I assume that you are encountering this error running `flutter doctor`,
could you please provide your `flutter doctor -v`?
Thank you

**Comment by TahaTesser** [comment]
Hi @dwicks99 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
