### ISSUE TITLE
Flutter app not working on real devices

### ISSUE THREAD

**Issue by rishabhshukla7** [flutter/flutter#55477]
Flutter app is not working on android device =>(it stops at the loading screen )
but very smoothly working on emulators => (but here it works fine)

**Comment by iapicca** [comment]
Hi @rishabhshukla7 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` (running the app on physical device)
and your `pubspec.yaml` 
Thank you

**Comment by VladyslavBondarenko** [comment]
@rishabhshukla7 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
