### ISSUE TITLE
Contributing instructions for changing flutter_tools

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5548]
Would be nice to write down somewhere what are the proper steps for making changes to flutter_tools.  Including things like running w/o a snapshot, running tests, etc.

See https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md for inspiration (honestly could probably use an update too).  This came up due to the recent addition of several contributors to the flutter_tools section of our code (internal and external).

Either a README.md in the flutter_tools package or a wiki article on flutter/flutter seem fine.  Just a place to put this stuff would be good.  I don't personally know the right steps for running flutter_tools w/o the snapshot for instance. :)

@devoncarew @danrubel @johnmccutchan

**Comment by zanderso** [comment]
Added more info in https://github.com/flutter/flutter/pull/36560
