### ISSUE TITLE
InkResponse causing repetitive paints

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#55488]
![ezgif-5-0a500503f021](https://user-images.githubusercontent.com/1261332/80141796-5fc1b700-85bf-11ea-8a60-71fd42c20f5e.gif)

flutter doctor

```
[√] Flutter (Channel master, v1.18.0-5.0.pre.89, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.18.0-5.0.pre.89 at M:\flutter
    • Framework revision 35ed1ccc9a (13 days ago), 2020-04-10 22:18:30 -0700
    • Engine revision d6c1398a3f
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 9e2c8ef000)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at E:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

repo to reproduce:
https://github.com/p30arena/flutter-inkresponse-custompainter-bug

**Comment by iapicca** [comment]
HI @p30arena 
I'm not sure the problem is with flutter or with your code
and I'm not entirely sure what is the desired behaviour
does this [code](https://dartpad.dev/306fcdb6dc5100dee54c12c1ead353bd) represent this issue?
Thank you

**Comment by p30arena** [comment]
Hi @iapicca 
Your code works correctly and does not represent this issue.

**Comment by p30arena** [comment]
Why the canvas repaints itself while the InkResponse is animating? :thinking: 
And why the shouldRepaint is only called when the setState is called?

**Comment by iapicca** [comment]
Hi again @p30arena 
I think the problem is the loop running in the canvas
that casts a random, nevertheless the behaviour is odd,
even hoovering over the button seems to trigger the rebuild
Thanks for submitting the issue

**Comment by goderbauer** [comment]
This is working as expected. The framework may call build/paint once per frame if it wanted to. That it doesn't is just an optimization.
