### ISSUE TITLE
[Community-related] Use Instantish for sharing/commenting on issues in Slack

### ISSUE THREAD

**Issue by marissamarym** [flutter/flutter#55495]
Hi 👋I'm Marissa, the founder of [Instantish](itsinstantish.com), which lets you do issue tracking (via GitHub issues) all in Slack.

Hope this is a good place to suggest this- we have a *free* version for public OSS Slack groups ([link](https://twitter.com/instantish/status/1228078258480017408)), which I think the Flutter community (fluttercommunity.slack.com) could use.

## Use case

In the Flutter Slack group, users have posted 29 links to issues in the past month.

The unfurled messages **don't update**, so you can't see if the issue was triaged or closed. There's also **no way to comment** on them through Slack.

## Proposal

Instantish is a Slack app that can be installed on the Flutter Slack group.

<img width="825" alt="Screen Shot 2020-04-23 at 1 25 03 PM" src="https://user-images.githubusercontent.com/1459660/80145952-e184f680-8565-11ea-9bd2-1a3b32aa0dc7.png">

It'll allow users to **reference** issues by typing `/issue <url>`.

And users can **comment on** the issue with a thread.

If the issue is closed or labels or milestones are added, the issue message will **automatically update**- keeping everyone on the same page!

Instantish for OSS is also used for other open-source communities like BotKit's ([link](https://github.com/howdyai/botkit)), which has 12k+ users.

Happy to set up/configure Instantish for Flutter's Slack. The early access is available at itsinstantish.com, but feel free to reach out at marissa@itsinstantish.com if this seems interesting!

**Comment by iapicca** [comment]
Hi @marissamarym 
your proposal doesn't seem to be aimed at flutter itself, first party plugin or documentation
I'd recommend to advance this proposal direct to its subject, [flutter community slack channel](https://fluttercommunity.dev/joinslack)

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
