### ISSUE TITLE
Google Maps API network problems cause app crashes

### ISSUE THREAD

**Issue by nmhernandez10** [flutter/flutter#55506]
Today (23 april 2020) Google Maps API failed during two hours. Then, every Android app based on google maps didn't show the map. However, Flutter apps crashed and closed instead of "showing a grey space where map should appear".

The error on Flutter development console was:

```E/Google Maps Android API(15536): Failed to load map. Error contacting Google servers. This is probably an authentication issue (but could be due to network errors).```

Then, app crashed.

I don't report Flutter doctor, and Flutter run verbose output here, because it's a network problem from google api which is not properly handled by google_maps_flutter package on Flutter Android Apps.

**Comment by cadrogui** [comment]
According to the Ray comment on https://outage.report/google-maps

> Clearing your app data on Android should fix the issue now.

works on android, tested by @cramirez1996, also i tested our app in iOS and works

regards.

**Comment by nmhernandez10** [comment]
It's not about how to solve this problem when it already happened, but google_maps_flutter should handle this problem in order to avoid crashes. Thanks a lot anyway.

**Comment by cadrogui** [comment]
Totally agree, meanwhile it’s a dirty fix 

Regards

**Comment by iapicca** [comment]
Hi @nmhernandez10 
from your statement
> I don't report Flutter doctor, and Flutter run verbose output here, because it's a network problem from google api which is not properly handled by google_maps_flutter package on Flutter Android Apps.

I understand you are not experiencing an issue with flutter itself or [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) plugin

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it;
possibly provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or a reproducible minimal code sample.
Thank you
