### ISSUE TITLE
Not clear how to identify, debug, and fix performance problems of Flutter apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5550]
https://flutter.io/debugging/#debugging-performance-problems is part of what we need.  We could split that out into a separate article.

Topics to cover:
1. Enabling the performance overlay.
2. `flutter trace` and Observatory timeline view.
3.  Link to Chromium or Android docs about interpreting trace files.
4. Explanation of what the gpu thread does vs. the main thread, which part is their code.
5.  How to add your own trace events from Dart.
6. Repaint Rainbow.

Probably others?  @abarth @Hixie

**Comment by eseidelGoogle** [comment]
@chinmaygarde tells me he's interested in moving this forward this quarter.

Also, https://github.com/fuchsia-mirror/sysui/blob/master/docs/performance.md is another related doc written by a user of Flutter.

**Comment by sethladd** [comment]
This was a top request from current Flutter customers, when asked what documentation they would most like to see.

**Comment by sethladd** [comment]
Moving out to M3, as "easily optimizing the performance of a Flutter app" is something we can do post-M2. Thanks for working on the doc!

**Comment by eseidelGoogle** [comment]
My understanding is @chinmaygarde has a partially complete doc, but has other higher priority things to do before completing such and likely won't get back to it for a while.

@chinmaygarde can you please share your partial doc with @LarkAscending and me and we can evaluate if there is something we could pull out of there to publish in the M3 timeframe (and then unassign the bug)? :)  Thanks!

**Comment by LarkAscending** [comment]
Would be great to have something, even if it's basic, soon. Then iterate as we get more data points...

**Comment by eseidelGoogle** [comment]
@lukef asked about this today for Posse.  I pointed him to https://dart-lang.github.io/observatory/ which at least documents the profiler we use, but not necessarily all the flutter-specific things we can do with it (like the `flutter trace` command, or how it's possible to add our own traces from Dart code.

**Comment by sethladd** [comment]
cc @mit-mit for developer experience

**Comment by Hixie** [comment]
@chinmaygarde I assume you won't have the bandwidth to write this.

@filiph @Sfshaza @LarkAscending Is this something that is on your radar?

**Comment by sethladd** [comment]
cc @mjohnsullivan

**Comment by eseidelGoogle** [comment]
@Sfshaza is actively working on a doc on this topic.

**Comment by xster** [comment]
Assuming this bug is done since it's on the website :)
Please reopen if there were still remaining tasks
