### ISSUE TITLE
[gen_l10n] Tool should output files that were read and written

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#55503]
This allows for developers and tools dependent on the `gen_l10n` workflow to verify which files were needed and created by the tool.

In particular, this would be helpful for Flutter tool integration of the `gen_l10n` workflow (see https://github.com/flutter/flutter/pull/55241/commits/277b2fd543855930dfcc94906a57c24569530f10), since the tool would currently have to makes guesses on whether or not gen_l10n needs to be rerun.

cc/ @HansMuller @jonahwilliams

**Comment by shihaohong** [comment]
@jonahwilliams I was thinking of making this feature optional so we do not generate too many unnecessary files for our users, but it has to be required in order for the incremental build system that we're using for the integration tool right?

**Comment by jonahwilliams** [comment]
Optional is fine, we would like specify the location where they are written into a hidden directory somewhere.

Without this, we need to guess the output files. I don't really want to do that because If I guess wrong then things don't rebuilt correcty
