### ISSUE TITLE
gtk+-3.0 Flutter Engine Linux embedder dep

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#55505]
Building from master, using these flags there is still a dependency on gtk+-3.0.  This pulls in a lot of unneeded things.

```./flutter/tools/gn --runtime-mode debug --embedder-for-target --full-dart-sdk --enable-fontconfig --target-os linux --linux-cpu arm --arm-float-abi hard --target-triple arm-linux-gnueabihf  --disable-desktop-embeddings```

Generates this:

```
| Command: python /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/git/src/build/config/linux/pkg-config.py -s /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot -a arm --system_libdir lib gtk+-3.0
| Returned 1.
| stderr:
| 
| Package gtk+-3.0 was not found in the pkg-config search path.
| Perhaps you should add the directory containing `gtk+-3.0.pc'
| to the PKG_CONFIG_PATH environment variable
| No package 'gtk+-3.0' found
```

**Comment by stuartmorgan** [comment]
That's unexpected. I'm not sure how adding `--disable-desktop-embeddings` removed the x11 dependency but not the GTK dependency for you, given that they are in the same file.

What target is still referencing those configs? Can you try removing all the configs in https://github.com/flutter/engine/blob/master/shell/platform/linux/config/BUILD.gn and see what breaks so we can find out what the reference is?

**Comment by jwinarske** [comment]
Resolved.  I didn't have `--disable-desktop-embeddings` set.
