### ISSUE TITLE
Append previous master runs to benchmark charts of released branches

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#55511]
With branching enabled, it is possible to view corresponding benchmarks charts of released branches.

However current charts show only the commits since branch point. 
![before](https://user-images.githubusercontent.com/54558023/80159935-22d6cf80-8581-11ea-9747-9ea3b5ca1f05.png)

It would be good to append earlier commits prior to the branch point.

**Comment by keyonghan** [comment]
PR: https://github.com/flutter/cocoon/pull/753 fixes this issue. With this PR, it looks like:
![Screen Shot 2020-04-23 at 4 37 23 PM](https://user-images.githubusercontent.com/54558023/80160337-3cc4e200-8582-11ea-9b30-6e78f79cd1d1.png)

Above chart is for flutter-1.18-candidate.5, which has only one commit (the one when branched out). This commit is located to the most right. Then earlier commits from master are appended to its left side.

**Comment by keyonghan** [comment]
@pcsosinski Does this look good to you, or any comments?
/cc @godofredoc @digiter

**Comment by pcsosinski** [comment]
thanks.  I'm assuming that subsequent cherrypicks onto the branch will be shown as well?   if so, looks great!

this may be a separate discussion, but we will need to figure out how to limit the branches shown at some point (ie 1.17-candidate.3 is the only 1.17 branch we really care about anymore)

**Comment by keyonghan** [comment]
Yes. All subsequent cherrypicks will be shown to the right side based on time. Then all prior master commits will be appended to the left side of these cherrypicks.

Created https://github.com/flutter/flutter/issues/55579 to track how to limit branches shown on dashboard.

**Comment by keyonghan** [comment]
@pcsosinski Sorry for the late! Please check the benchmark page, it now appends old master data to different branches. Please let me know if any questions.
