### ISSUE TITLE
FlutterViewController Crashed when viewWillAppear

### ISSUE THREAD

**Issue by windvip** [flutter/flutter#55526]
The application crashes when I do the following：
Current stack is：FlutterVC_1 -> NativeVC2 -> FlutterVC3。
Crashed when I back from NativeVC2 to FlutterVC_1 ,

more infomation：
![image](https://user-images.githubusercontent.com/11665737/80169368-cd99cd00-8617-11ea-8863-f33798409844.png)

crash Info in debug mode：
![image](https://user-images.githubusercontent.com/11665737/80169418-ed30f580-8617-11ea-8c73-c624ba97b132.png)

flutter doctor
```
[✓] Flutter (Channel stable/v1.12.13-hotfixes, v1.12.13+hotfix.9-pre.8, on Mac OS X 10.15.4 19E287, localezh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the onebeing used to invoke it.This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
       To re-install CocoaPods, run:sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available
```

@kangwang1988

**Comment by windvip** [comment]
Try this solution without modifying the engine：

@interface FlutterViewController ()
- (void)surfaceUpdated:(BOOL)appeared;
@end
````
@implementation YourFlutterViewController
- (void)surfaceUpdated:(BOOL)appeared {
	if (self.engine && self.engine.viewController == self) {
		[super surfaceUpdated:appeared];
	}
}

/// Update the correct VC to engine，then call update UI
- (void)viewDidAppear:(BOOL)animated {
	if(self.engine && self.engine.viewController != self) {
		[_engine.get() setViewController:self];
		[self surfaceUpdated:YES];
	}
	[super viewDidAppear:animated];
}
@end
````

**Comment by iapicca** [comment]
Hi @windvip 
can you please provide  a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @windvip 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
