### ISSUE TITLE
anyone can help me ? . the problem arises when I change the google-service.json file, and when i want to build there is no error but the build result doesn't appear

### ISSUE THREAD

**Issue by kardotinambunan12** [flutter/flutter#55524]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @kardotinambunan12 
what do you mean by
> the build result doesn't appear

provide your `flutter doctor -v` and describe more detailed the sequence of your actions

**Comment by VladyslavBondarenko** [comment]
@kardotinambunan12 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
