### ISSUE TITLE
Unable to debug and use hot reload while having two emulators running.

### ISSUE THREAD

**Issue by VishnuSivadasVS** [flutter/flutter#55534]
I was running the application using `flutter run -d <deviceid>` command, because i had 2 devices running. The application got installed and was running on the specified device, but i wasn't able to perform hot reload and other operations after that.

**Comment by VladyslavBondarenko** [comment]
Hi @VishnuSivadasVS 
provide please your `flutter doctor -v` and `flutter run -d <deviceid> --verbose`.
You can't use debug (with breakpoints) when running from the terminal.
To Hot reload or Hot restart press `r` or `R` in the terminal where your app is running, this should be in your log after app is installed

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```
