### ISSUE TITLE
Refactor Duration constants in Material.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5553]
We currently have 3 different `Duration` constants with the same value, two in `constants.dart` and one in `theme.dart`. Maybe it would be a better solution to have a default `kMaterialAnimation` (similar to the way the spec uses it) and use that in all cases until a new value arises.

**Comment by eseidelGoogle** [comment]
Is this still an issue worth tracking @HansMuller @Hixie?

**Comment by eseidelGoogle** [comment]
Unclear if this would need to be tagged with api-stability or just marked as "no milestone needed"

**Comment by Hixie** [comment]
This is more or less an artifact of how the spec is designed. I don't think it necessarily makes sense for there to be a single constant.
