### ISSUE TITLE
iOS Simulator missing

### ISSUE THREAD

**Issue by anoureddini** [flutter/flutter#55545]
I want Flutter to:
1) let me choose a default simulator
2) provide more control over device/simulator directly from Flutter SDK (instead of working with Runner in xCode)

Here's my problem:
xCode kept using up all my free space (~30GB). I deleted some stuff -mainly regarded to platforms and simulators. Then `flutter run ` would only run WatchOS instead of my good old iPhone 11 Pro Max. I couldn't bring the sim. back so I completely deleted xCode with all the config files and reinstalled. Still, VSCode runs only on my macOS darwin build (which I deliberately added to my env.) and WatchOS simulator which I never chose to work with! But instead this time, I am able to change my simulator in Simulator app. My iPhone sim. launches and I close WatchOS sim. and everything works fine. This simulator issue is eating me out and found no help in stackoverflow or anywhere else on the internet.

Thanks,
Amir

**Comment by VladyslavBondarenko** [comment]
Hi @anoureddini 
isn't this enough that you can launch simulator (type 'simulator' in the spotlight search) without launching xCode?

**Comment by VladyslavBondarenko** [comment]
@anoureddini 
Default simulator - simulator opened the last time. There is no need to always open simulator through Runner in xCode, closing, this seems to not be an issue.
if you disagree please write in the comments and I will reopen it
