### ISSUE TITLE
txt_unittests has some incompatibility test cases?

### ISSUE THREAD

**Issue by linkin-xiao** [flutter/flutter#55541]
I run txt_unittests in two linux machine , one can pass all the tests, and the other always meet a failed cases:

`../../flutter/third_party/txt/tests/paragraph_unittests.cc:3985: Failure
Expected equality of these values:
  boxes[0].rect.bottom()
    Which is: 73
  75
[  FAILED  ] ParagraphTest.GetRectsForRangeCenterParagraphNewlineCentered (44 ms)`   ;

and then,

although I knew maybe txt_unittests will meet some executable problem from this issue(https://github.com/flutter/flutter/issues/36296),  I also try to run it on mac, and I meet a different  failed cases:

`../../flutter/third_party/txt/tests/paragraph_unittests.cc:4501: Failure
Expected equality of these values:
  paragraph->records_[2].offset().x()
    Which is: 207.40625
  207.359375f
    Which is: 207.359375
../../flutter/third_party/txt/tests/paragraph_unittests.cc:4502: Failure
Expected equality of these values:
  paragraph->records_[3].offset().x()
    Which is: 230.91015625
  230.859375f
    Which is: 230.859375
../../flutter/third_party/txt/tests/paragraph_unittests.cc:4503: Failure
Expected equality of these values:
  paragraph->records_[4].offset().x()
    Which is: 253.40234375
  253.34765625f
    Which is: 253.34765625
[  FAILED  ] ParagraphTest.KernScaleParagraph (57 ms)` ,

so whether these txt_unittests has some  incompatibility problem in different machine, is the problem of skia?  And how to fix it?

**Comment by TahaTesser** [comment]
Hi @linkin-xiao 
can you please provide your `flutter doctor -v`?

**Comment by linkin-xiao** [comment]
@TahaTesser   I compile the engine by myself ,  commit is e1e6ced81d029258d449bdec2ba3cddca9c2ca0c

**Comment by pedromassangocode** [comment]
Hi @linkin-xiao 
Are you still facing this issue? If so, please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
