### ISSUE TITLE
Wrong string in RTL

### ISSUE THREAD

**Issue by mishatron** [flutter/flutter#55549]
I have an issue that when I try to get localized strings using RTL language, some strings are correct, some not.
1) " %s דווח על שינה " - wrong
2) "%s דו"ח סוכר " - correct

after Localization.of(context).getValue(first) first string is got as " דווח על שינה s%", but second is ok

**Comment by iapicca** [comment]
Hi @mishatron 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
