### ISSUE TITLE
Video not show after follow all steps in iOS 13

### ISSUE THREAD

**Issue by luckymehndiratta** [flutter/flutter#55553]
```bash
#Software: AppleCoreMedia/1.0.0.17C45 (iPhone; U; CPU OS 13_3 like Mac OS X; en_us)
#Date: 2020/04/24 18:13:04.004
#Fields: date time uri cs-guid s-ip s-ip-changes sc-count c-duration-downloaded c-start-time c-duration-watched bytes c-observed-bitrate sc-indicated-bitrate c-stalls c-frames-dropped c-startup-time c-overdue c-reason c-observed-min-bitrate c-observed-max-bitrate c-observed-bitrate-sd s-playback-type sc-wwan-count c-switch-bitrate
2020/04/24 18:11:30.030 http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4 128824B3-AFBE-4974-B8EF-BE7DFA5B0150 2404:6800:4002:806::2010 0 1 435.552 - - 32113012 4382863.144 589835.193 - - 1.111 - - - - - FILE 0 -
flutter: build Tab1
	path: satisfied (Path is satisfied), interface: en1

    "LocalDataTask <4CE3546F-C6B7-4CCF-86A7-3AE1902A8BF7>.<23>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4CE3546F-C6B7-4CCF-86A7-3AE1902A8BF7>.<23>, NSLocalizedDescription=cancelled}
	[C15.1 BBB7BCC2-0ECF-457C-98A4-B16F5F26877C 2405:204:122b:60dc:611d:3698:a7f1:9ccc.57095<->2404:6800:4002:806::2010.80/5228]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 59.851s, DNS @0.013s took 0.010s, TCP @0.026s took 0.131s
	bytes in/out: 32125519/730, packets in/out: 26600/2, rtt: 0.112s, retransmitted packets: 0, out-of-order packets: 1284

```

**Comment by iapicca** [comment]
Hi @luckymehndiratta 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by luckymehndiratta** [comment]
> Hi @luckymehndiratta
> can you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> and your `pubspec.yaml`
> or if possible a reproducible minimal code sample.
> Thank you

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/lucky/Documents/Flutter_SDK/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lucky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Users/lucky/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • E5AE42C2-481D-4F4E-9686-69E8E861A905 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!


![Screenshot 2020-04-24 at 8 38 28 PM](https://user-images.githubusercontent.com/58592267/80227652-905f2a80-866b-11ea-8e7f-06ad8cd6389b.png)

**Comment by TahaTesser** [comment]
Hi @luckymehndiratta 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @luckymehndiratta 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
