### ISSUE TITLE
Limit release branches shown on dashboard

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#55579]
Right now all release branches are shown on both build and benchmark dashboard. 

we will need to figure out how to limit the branches shown at some point (ie 1.17-candidate.3 is the only 1.17 branch we really care about anymore).

**Comment by keyonghan** [comment]
@pcsosinski Is it doable to delete those branches we do not care from the repo directly? Or we need to keep them there but just do not show them in the dashboard?

**Comment by pcsosinski** [comment]
we should keep them but not show them.
