### ISSUE TITLE
Flutter support to build iPadOS and watchOS apps

### ISSUE THREAD

**Issue by AfropunkTechnologist** [flutter/flutter#55580]

**Comment by iapicca** [comment]
HI @AfropunkTechnologist 
you can build for [apple watch]( https://github.com/flutter/flutter/issues/28901) (apple watch [docs](https://flutter.dev/docs/development/platform-integration/apple-watch))
and [iPad](https://github.com/flutter/flutter/issues/34719#issuecomment-504809958) right now.

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by AfropunkTechnologist** [comment]
Wasn’t tracking, appreciate it 👌🏾
