### ISSUE TITLE
Distorted fonts and icons, Android & iOS affecting multiple devices

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#55584]
I was just testing my production app (published on Android & iOS) and suddenly the font & icon rendering went crazy, I snapped a screenshot. After going back and then reopening the route that was buggy it was fixed.

![Screenshot_20200424-184018(1)](https://user-images.githubusercontent.com/298850/80241482-92b98880-865b-11ea-8645-402ad33b78b6.png)

I guess it's will be almost imposible to reproduce but I thought I should flag it to you guys nonetheless.

Thanks

**Comment by jimmyff** [comment]
This is what it should have looked like incase that helps:

![Screenshot_20200424-184527](https://user-images.githubusercontent.com/298850/80241695-f17f0200-865b-11ea-8eba-d24267c07a3f.png)

**Comment by iapicca** [comment]
Hi @jimmyff 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by jimmyff** [comment]
```
jimmypro-7:eurovision jimmyff$ flutter doctor -v
[✓] Flutter (Channel master, v1.15.23-pre.12, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.15.23-pre.12 at /Users/jimmyff/flutter-sdk
    • Framework revision 3fd6808b44 (8 weeks ago), 2020-03-16 22:21:01 -0400
    • Engine revision 2faadc71b6
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 810d85d4cf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Development/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

I can confirm this is on Android & iOS in development mode and in production. I have seen it on multiple devices.

here is a video showing it:
[videoplayback.mp4.zip](https://github.com/flutter/flutter/files/4634756/videoplayback.mp4.zip)


Here is a screenshot of it on production iPad build:
![2020-05-15](https://user-images.githubusercontent.com/298850/82057746-b2bcf480-96bb-11ea-93f2-3f1820472265.jpeg)

**Comment by iapicca** [comment]
Hi @jimmyff 
could you please run 
```console
flutter channel stable
flutter upgrade --force
```
if the issue persists
please provide the information listed [above](https://github.com/flutter/flutter/issues/55584#issuecomment-619880445)
Thank you

**Comment by jimmyff** [comment]
I can however as explained above this really isn't a very easy issue to reproduce. I've only seen this a few times in the many hours of using my app. I suggest this be assigned to someone with knowldge about the flutter rendering pipeline as this doesn't seem like a master branch defect.

**Comment by VladyslavBondarenko** [comment]
Looks similar to https://github.com/flutter/flutter/issues/55215, https://github.com/flutter/flutter/issues/55208

@jimmyff note that current master is `1.19.0-3.0.pre.13`. The used above master version was obsolete, earlier even than stable at that moment. 
Are you experiencing this with current dev or master channel?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
