### ISSUE TITLE
Let 'Enter' keystroke submit a form

### ISSUE THREAD

**Issue by Mateis** [flutter/flutter#55583]
I'd like to submit a form (or user input) when the user presses 'enter' on their computer keyboard. 

I've implemented a `Form `with `TextFormField()` and `RaisedButton.` The form submits when I click the button, yet it does not respond to enter. 

Submitting a webform hitting enter is expected user interaction behaviour - I've seen 3 test users try to press enter to submit the form (in this case a search action).

I read these posts and related: https://github.com/flutter/flutter/issues/35435
However, with the solutions provided there, the form also submits when the user clicks away focus. This is unexpected user interaction behavior

Are there any solutions to make only the enter button sumbit?

**Comment by yjbanov** [comment]
Removing the web label. This capability needs to be added at the framework level (/cc @goderbauer @HansMuller)

/cc @mdebbar who has a `RawKeyboard` workaround.

**Comment by pedromassangocode** [comment]
Hi @Mateis 
Sorry but it is not clear to me what this issue is about.

The text field bellow will call onFieldSubmitted if it is focused and you press "Enter" key on the keyboard.

```dart
TextFormField(
    decoration: InputDecoration(hintText: 'First name'),
    onFieldSubmitted:(value) {
        print(value);
    },
)
```

Is that what you were looking for?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Mateis** [comment]
> 
> 
> Hi @Mateis
> Sorry but it is not clear to me what this issue is about.
> 
> The text field bellow will call onFieldSubmitted if it is focused and you press "Enter" key on the keyboard. It works in a Form widget as well.
> 
> ```dart
> TextFormField(
>     decoration: InputDecoration(hintText: 'First name'),
>     onFieldSubmitted:(value) {
>         print(value);
>     },
> )
> ```
> 
> Is that what you were looking for?
> Thank you

Hey cool, this works.

```dart
submitForm() {
    if (_formKey.currentState.validate()) {

      print("the search query is " + myController.text);

      // Navigate to the results screen.
      Navigator.of(context).push(MaterialPageRoute(builder: (_) => SearchResults(myController.text)));
    }
  }

  @override
  Widget build(BuildContext context) {
    // Build a Form widget using the _formKey created above.
    return Form(
      key: _formKey,
      child: Container(
        constraints: BoxConstraints(maxWidth: 600),
        padding: EdgeInsets.all(8.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Expanded(
              child: TextFormField(
                controller: myController,
                validator: (value) {
                  if (value.isEmpty) {
                    return "Voer hier je zoekopdracht in.";
                  }
                  return null;
                },
                onFieldSubmitted:(value) {
                  submitForm();
                },
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
               child: RaisedButton(
                onPressed: () {
                  submitForm();
                },
                child: Text('Zoeken'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
