### ISSUE TITLE
Hide expression evaluation for web under a flag in beta as an experimental feature

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#55589]
Expression evaluation is an experimental feature that can cause crashes in the frontend server when there is mismatch of data between debugger and frontend server:

https://github.com/flutter/flutter/issues/54520

In other cases it can cause debugger errors to display traces with (not crashing): 

https://github.com/dart-lang/sdk/issues/41585

I've added a flag to control the feature, disabled by default until the feature becomes more stable: 
https://github.com/flutter/flutter/pull/55003.

Please consider cherry picking commit https://github.com/flutter/flutter/tree/aa549ff101d9afd57a8c6fba5870c235d09f644a into beta. 

## Steps to Reproduce

see https://github.com/flutter/flutter/issues/54520
see https://github.com/dart-lang/sdk/issues/41585

**Comment by jonahwilliams** [comment]
FYI @ferhatb @pcsosinski , should we cherry-pick this into beta?

**Comment by pcsosinski** [comment]
Dart locked for 2.8 stable already.  what impact will this have for 1.17 stable?  1.18 beta will be out in about a week as well

**Comment by jonahwilliams** [comment]
This only requires a change in the flutter tool to work around, right @annagrin ?

**Comment by annagrin** [comment]
Yes, the change is only in flutter, hiding the feature under a flag.

The impact for 1.17 stable,  @Jonah Williams <jonahwilliams@google.com>  -
is the whole web scenario disabled? If yes, only the 1.17 beta is affected
for users who would like to try using flutter web with a debugger. 1.18
has  the change (hiding under a flag and some other fixes) already.

Thanks,
Anna

**Comment by annagrin** [comment]
1.18 is out so the issue is no longer relevant.
