### ISSUE TITLE
Flutter filter listview

### ISSUE THREAD

**Issue by ravi2teja2016** [flutter/flutter#55595]
I am trying a filter a list of documents from a collection , one of a field in collection is Taskassignedto this field if equal to current user email .

i am trying to get data by using following code

  return await Firestore.instance.collection('Task').getDocuments();

i need to filter the collection where Taskassigned to is equal to current user email. Appreciate the help.tried this
  return await Firestore.instance.collection('Task').where('Taskassignedto',isequalto:email).getDocuments();

getting an error getter email isnt defined for the class FirebaseUser

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
