### ISSUE TITLE
Expose the characters package to Flutter users for better unicode handling

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#55593]
## Use case

[The characters package](https://pub.dev/packages/characters) was recently introduced to address Dart String's limitations of manipulating extended grapheme clusters (https://github.com/dart-lang/language/issues/34). However, it requires the user to get out of their way to look for it and add it to their Flutter projects. This barrier is likely to cause continued use of the String API in cases where the characters package ought to be used to avoid breaking emojis and non-English text. 

## Proposal

As part of a larger plan to make characters more readily available to writers of text manipulation code, the Flutter framework can export the characters package once it has integrated it into its internal implementation as described in the [TextField Characters Proposal](https://docs.google.com/document/d/1OOFW0PEZf0orBl445YXJ3nfjyKOqZdmeQ6KU3glUh7s/edit). The user-observable effect is that the extension `characters` will become visible when the user does an autocomplete on a String object in their Flutter project.

Alternatively, the Flutter starter app template can always import the characters package. The downside is that the package will only be made available within main.dart unless the user imports it in other files of their project. 

Cc: @justinmc

**Comment by justinmc** [comment]
The characters package has been added to Flutter in https://github.com/flutter/flutter/pull/59267 and will be used internally in https://github.com/flutter/flutter/pull/53381.  However, it won't be available to users without installing it in their app as usual.  I'll take a look at exporting it from Flutter and see what that would entail.
