### ISSUE TITLE
web_benchmarks_canvaskit bench_picture_recording.canvaskit.estimatePaintBounds.average regression

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#55597]
looks like the benchmark was enabled on 4/16 and went red on 4/21 with engine roll https://github.com/flutter/flutter/commit/5c5bb485a0db95fabc040253da42cd7d43cfac78

<img width="361" alt="Screen Shot 2020-04-24 at 1 13 28 PM" src="https://user-images.githubusercontent.com/59894980/80253057-65ee7c80-862d-11ea-9afa-9e8690501ad9.png">

**Comment by renyou** [comment]
@yjbanov Is this related to https://github.com/flutter/flutter/issues/55389?

**Comment by yjbanov** [comment]
> @yjbanov Is this related to #55389?

Yep, it's exactly that one. Deduplicating.
