### ISSUE TITLE
Running flutter_tools tests creates a C:\flutter_assets directory on Linux

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#55607]
On my Linux machine, I did:
1. `cd flutter/packages/flutter_tools`.
2. `../../bin/cache/dart-sdk/bin/pub run test test/general.shard`

Result:
There is now a `flutter/packages/flutter_tools/C:\flutter_assets/AssetManifest.json` file.

(Even if I were on Windows, creating a `C:\flutter_assets` directory seems a bit questionable.)

**Comment by jonahwilliams** [comment]
This is a leak in the test script that should be fixed by https://github.com/flutter/flutter/pull/55510
