### ISSUE TITLE
Flutter doctor says that I am missing Visual Studio but I have installed the exact versions

### ISSUE THREAD

**Issue by Noxware** [flutter/flutter#55603]
I have been trying to install flutter for desktop but flutter doctor says that I am missing Visual Studio even though I have even installed the exact version of the Windows 10 SDK.

flutter doctor -v output:

```
[√] Flutter (Channel master, v1.18.0-9.0.pre.6, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.18.0-9.0.pre.6 at C:\flutter
    • Framework revision 35edbe3d9d (6 hours ago), 2020-04-24 09:38:49 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Noxware\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including the following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        Windows 10 SDK (10.0.17763.0)

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\Noxware\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18363.778]

! Doctor found issues in 3 categories.
```

Screenshot:

![screenshot](https://user-images.githubusercontent.com/7684329/80261372-9dc2e780-8660-11ea-9117-74f477552e8f.png)

**Comment by stuartmorgan** [comment]
This isn't an SDK version mismatch issue; that message means the tool thinks you don't have VS at all.

What does running
```
.\vswhere -format json -utf8 -latest -prerelease -all
```
from `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\` print?

**Comment by Noxware** [comment]
```
C:\Users\Noxware>cd %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\

C:\Program Files (x86)\Microsoft Visual Studio\Installer>.\vswhere -format json -utf8 -latest -prerelease -all
[]
```

What does this output mean? Why is that list empty?

**Comment by stuartmorgan** [comment]
That means that according to the tool that comes with the VS installer, you don't have VS installed.

One other thing to try:
```
.\vswhere -format json -utf8 -latest -prerelease -all -products *
```
If that gives you a non-empty list, this is https://github.com/flutter/flutter/issues/39067.

**Comment by Noxware** [comment]
Yes, that gives me a non-empty list as you said, so that's the problem.

I installed the whole Visual Studio IDE and now everything works.

The output of flutter doctor was not clear about needing to install the complete IDE. You should add that to the flutter doctor's message as a quick fix until it can work without the complete IDE.

Thanks for the help, I will continue experimenting with flutter.

**Comment by z0rro2k** [comment]
hi all,
i started android studio, and i go to \file\settings
then i selected plugins, and i searched "flutter" and i click on install button. a warning is displayed asking you will need to install also the dart pluggin, i selected ok and i restarted android studio and now i don't have issues regard to missing pluggins


i hope this it can help
