### ISSUE TITLE
Allow platforms to save user input for future autofill 

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#55613]
Continuation of https://github.com/flutter/flutter/issues/13015.

Android and many web browsers save user input for future autofill, when a form is finalized. 

Android Documentation: https://developer.android.com/guide/topics/text/autofill-optimize#ensure

**Comment by HeebeLee** [comment]
Thank you for your efforts.
Will it be available in the first quarter of 2020?
We are all looking forward to it.

**Comment by ferhatb** [comment]
Note: Required for web implementation of autofill.

**Comment by nturgut** [comment]
Hi @LongCatIsLooong ,

Did you had time to have a look at this issue? Please let me know if there are any parts I can help.

**Comment by goderbauer** [comment]
Assigning to @LongCatIsLooong since you have a PR out for this.

**Comment by nakuzm** [comment]
Is autofill save now available for iOS and Android? If Yes, how to enable autofill save for iOS?

**Comment by LongCatIsLooong** [comment]
@nakuzm you should be able to manually trigger it by calling `TextInput.finishAutofillContext()` (or `TextInput.finishAutofillContext(shouldSave: false)` if you wish to create a new context without saving the current user input).

**Comment by shinayser** [comment]
> @nakuzm you should be able to manually trigger it by calling `TextInput.finishAutofillContext()` (or `TextInput.finishAutofillContext(shouldSave: false)` if you wish to create a new context without saving the current user input).

Those methods are not available for me and I just upgraded my flutter to stable 1.20.  What I am doing wrong?

**Comment by BirjuVachhani** [comment]
@shinayser The same goes for me... I too was not able to use those methods

**Comment by MichaelPSN** [comment]
> > @nakuzm you should be able to manually trigger it by calling `TextInput.finishAutofillContext()` (or `TextInput.finishAutofillContext(shouldSave: false)` if you wish to create a new context without saving the current user input).
> 
> Those methods are not available for me and I just upgraded my flutter to stable 1.20. What I am doing wrong?

Looks like it's been merged to `master`, not yet in `stable`. You'll need to switch channels if you require the Autofill save feature immediately

**Comment by LongCatIsLooong** [comment]
as MichaelPSN pointed out, this was merged recently so it's not part of the 1.20 release.

**Comment by shinayser** [comment]
I might be wrong, but since there is not way to save user input right now, there is no reason to reason to use autofill right now, right?
Or am I wrong?

**Comment by acoutts** [comment]
> I might be wrong, but since there is not way to save user input right now, there is no reason to reason to use autofill right now, right?
> 
> Or am I too noob? 

The sms code auto fill on iOS is really nice and works now. If you use an external password manager where you add an entry manually, that works too.

**Comment by LongCatIsLooong** [comment]
@nturgut I think we can close this one now that the web PR has been merged?

**Comment by nturgut** [comment]
> @nturgut I think we can close this one now that the web PR has been merged?

Yes, that is correct. Thanks for letting me know I closed the [web issue](https://github.com/flutter/flutter/issues/59378) but forgot about this one.
