### ISSUE TITLE
Add the ability to hide/unhide CupertinoTabBar

### ISSUE THREAD

**Issue by jibiel** [flutter/flutter#55611]
The original issue https://github.com/flutter/flutter/issues/24095 was closed recently due to lack of information so I wanted to elaborate a bit and hopefully get some answers.

<p float="left">
<img src="https://user-images.githubusercontent.com/519227/80262089-09bf4300-8695-11ea-8a1c-58938a112085.png" width="49%">

<img src="https://user-images.githubusercontent.com/519227/80262222-75091500-8695-11ea-8584-e9086738a91a.png" width="49%">
</p>

The "root" pages are organized like so:

```dart
return CupertinoTabScaffold(
  tabBar: CupertinoTabBar(
    items: const <BottomNavigationBarItem>[
      BottomNavigationBarItem(
        icon: Icon(CupertinoIcons.contacts),
        title: Text('Contacts'),
      ),
      // ...
    ],
  ),
  tabBuilder: (context, index) {
    switch (index) {
      case 0:
        return CupertinoTabView(
          builder: (context) {
            return CupertinoPageScaffold(
              navigationBar: CupertinoNavigationBar(
                middle: const Text('Contacts'),
              ),
              child: ContactsTab(),
            );
          },
          routes: Routes.all(),
        );
      // ...
```

Transition from one of the chat list items to the chat page:

```dart
return GestureDetector(
  onTap: () => Navigator.of(context).pushNamed(
    '/chat',
    arguments: // ...
  ),
  child: //...
);
```

As you can see, both pages have the navigation bar. The problem here is that user can be directed to the chat page from different locations of the app. For example, they can get from the contacts tab to the chat page in a similar way as described above. In this case, the "Contacts" icon will be active in the navigation bar while user sees the chat and logically expects to be located in the "Chats" section. Some cognitive dissonance rooted in the UX problem takes place.

**Desired behavior**

Navigation bar is hidden on pages like the chat page restricting user navigation options to the "Back" button and thus giving the impression of a more accurate correspondence between navigation bar state and the displayed page. Also some pages could use more available screen space and less UI elements to steal user focus.

**Suggestion**

Introduce `persistent` attribute to `CupertinoTabBar` or `CupertinoTabScaffold`:

* `persistent: false` hides navigation bar on transitions "beyond" pages listed in `tabBuilder`.
* `persistent: true` implements the current behavior.

**Examples**

You can find real-world examples in Telegram and WhatsApp apps: only "root" pages have bottom navigation bar (e.g. Contacts, Chats etc.) while their "child" pages have not.

Here is the relevant video demonstrating the idea:

https://telegram.org/blog/contacts-local-groups#add-people-nearby

(transition between the second and the third screens).

**Comment by ayvaroff** [comment]
@jibiel Maybe `Navigator.of(context, rootNavigator: true).push(...)` will help you? There is info in the doc

> /// To push a route above all tabs instead of inside the currently selected one
> /// (such as when showing a dialog on top of this scaffold), use
> /// `Navigator.of(rootNavigator: true)` from inside the [BuildContext] of a
> /// [CupertinoTabView].

**Comment by jibiel** [comment]
@ayvaroff Thanks! Reading the docs can do miracles. 😅

This solves the simple case described in my original post.

But I've realized now that the title and the description of the issue does not quite match.

This issue was opened as a continuation of #24095 where developers would like to be able to hide `CupertinoTabBar` on certain pages but still be able to unhide it on further pages (without going back), possibly, with transitions, like sliding the tab bar off the screen and back.

And judging by the reactions here and in #24095, it still may be a desirable feature. But since I don't have an actual use case for this feature at the moment, I'm closing this issue for now (with uneasy heart). 🙂

Feel free to comment or open a new issue with the specifics if unhiding a tab bar on further pages in crucial for you.
