### ISSUE TITLE
Mouse can't select text in a multi-line textfield

### ISSUE THREAD

**Issue by WG-Studios** [flutter/flutter#55627]
## Steps to Reproduce
Dartpad Example: [https://dartpad.dev/c377b45f28f1cd60f23c5ddef9c88524](https://dartpad.dev/c377b45f28f1cd60f23c5ddef9c88524)

1. Run `flutter create bug`.
2. Update the files as follows:
**main.dart:**
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  createState() => MyWidgetState();
}

class MyWidgetState extends State<MyWidget> {
  TextEditingController _cont1;
  TextEditingController _cont2;

  @override
  initState() {
    _cont1 = TextEditingController();
    _cont2 = TextEditingController();

    _cont1.text = 'Text selection works here';
    _cont2.text = 'Text selection does not work\nwhen text is multi-line.';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextField(controller: _cont1),
        TextField(controller: _cont2, maxLines: null),
      ],
    );
  }
}
```

3. On flutter web, I can not select text with the mouse on the multi-line text field.

**Expected results:**
![success](https://user-images.githubusercontent.com/12790662/80273127-40955900-8695-11ea-8bc4-3777ddabba20.gif)

**Actual results:** 
![fail](https://user-images.githubusercontent.com/12790662/80273132-44c17680-8695-11ea-9149-7b2436b86f48.gif)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by GenericSoft** [comment]
for multi-line text field, the issue comes out only when controller initialized with a text. It works fine when you don't provide initial text.

**Comment by iapicca** [comment]
Hi @WG-Studios 
the issue occurs in the latest master as well

```console
[✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-9.0.pre.14 at /Users/nevercode/development/flutter_master
    • Framework revision dd88b20435 (34 hours ago), 2020-04-25 19:02:03 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • Francesco’s iPhone • 42f545c80499280e43186687e3c51ad278ab2985 • ios            • iOS 12.4.4
    • iPhone 8           • D5F70F31-B488-4454-9539-320B5551D92A     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server         • web-server                               • web-javascript • Flutter Tools
    • Chrome             • chrome                                   • web-javascript • Google Chrome 81.0.4044.122

• No issues found!
```

possibly related to [cursor issue](https://github.com/flutter/flutter/issues/50033)
see also [proposal](https://github.com/flutter/flutter/issues/45841)
Thank you

**Comment by iapicca** [comment]
Hi all
testing gallery for a different [issue](https://github.com/flutter/flutter/issues/57791#issuecomment-632555789)
I noticed that the issue persist with the latest master
Thank you

**Comment by baobao1996mn** [comment]
I have the same problem when using on the Web. Are there any solutions? Thank you !
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.2 19C57,
    locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.46.0)
[✓] Connected device (2 available)
```

![image](https://user-images.githubusercontent.com/37337417/84600321-91118180-aea2-11ea-9077-d4e3a1849c49.png)

**Comment by javipacheco** [comment]
Same problem here

**Comment by tal412** [comment]
Having the same issue... In both English and Hebrew.

**Comment by hTopology** [comment]
Having the same issue

**Comment by javipacheco** [comment]
Looking at different threads, this problem persists since February and still has no solution

Any application that needs forms, these are all management applications, have this problem

I understand that Flutter web is in beta, but 5 months to fix such an important bug, seems to me a big mistake

I hope you understand those of us who have given Flutter Web a chance in our companies and that we are faced with a problem with our customers that we cannot solve

**Comment by RayRojasGit** [comment]
I have the same problem for spanish this needs a fix ASAP!!! My web app is used for editing descriptions of products, some descriptions come in many lines, this feature is crucial, it makes anything useless.

**Comment by cacianokroth** [comment]
I HAVE THE SAME PROBLEM, PLEASE ATTENTION HERE!

**Comment by ChristophKlamroth** [comment]
I'm having the same issue here. Seeing that there's no solution to this problem yet, would writing a JS plugin for a normal-behaved input field and using it instead of the Flutter text field be a viable solution? I'm looking for a temporary solution till this gets fixed.

**Comment by Buildex** [comment]
Same problem here.

**Comment by dnishimoto** [comment]
What version of flutter downgrade will reverse the mouse positioning problem?   I tried 1.15.18 and it did not solve the problem.   Is there additional steps to reverting back.   

git checkout v1.15.18   
flutter doctor
flutter build web

**Comment by ChristophKlamroth** [comment]
> I'm having the same issue here. Seeing that there's no solution to this problem yet, would writing a JS plugin for a normal-behaved input field and using it instead of the Flutter text field be a viable solution? I'm looking for a temporary solution till this gets fixed.

I ended up using a `HtmlElementView` to embed an `InputElement` (for single line text fields) and a `TextAreaElement` (for multiline text fields). For this I used `platformViewRegistry.registerViewFactory` from `dart:ui` (side note: I had to ignore the undefined_prefixed_name error that the dart analyser throws, because `platformViewRegister` is not available until compile time). It works just fine and I think it's a viable (temporary) solution that's not so hard to implement.

**Comment by dnishimoto** [comment]
as stated in the bug, if you use 
flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true 
the textformfield work as specified.

Copy the build files after running the command

**Comment by Buildex** [comment]
> as stated in the bug, if you use
> flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true
> the textformfield work as specified.
> 
> Copy the build files after running the command

can we make it work on vs code debug mode? like when pressing f5

**Comment by dnishimoto** [comment]
Use the command line then copy the build web files

**Comment by nemoryoliver** [comment]
Same issue here. Wishing for a solution soon

**Comment by dnishimoto** [comment]
use flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true as a work around.  It will compile your code for the web.  Don't use flutter build web.   copy the build -> web files

**Comment by johnpryan** [comment]
> Don't use flutter build web

It should also be okay to use `flutter build web` (e.g. `flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true`). Are you seeing an issue?

**Comment by sunjianan9900** [comment]
> as stated in the bug, if you use
> flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true
> the textformfield work as specified.
> 
> when running the command, you will see flutter compile the main.dart code. Yeah
> 
> Copy the build files after running the command

but it has more other problem with 'FLUTTER_WEB_USE_SKIA' model

**Comment by sunjianan9900** [comment]
`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true`
this can fix it

**Comment by johnpryan** [comment]
> but it has more other problem with 'FLUTTER_WEB_USE_SKIA' model

Can you provide more information on that?

**Comment by brunodiazu** [comment]
I have the same issue, I can't select text with the mouse on the multi-line text field

**Comment by iapicca** [comment]
testing the [code above](https://github.com/flutter/flutter/issues/55627#issue-606705521) with the latest master

<details><summary>logs</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.37 at /Users/nevercode/development/flutter_master
    • Framework revision 35e7005184 (2 days ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue still persists
thank you

**Comment by johnpryan** [comment]
I noticed this is working with TextField, but not EditableText:

<details>
<summary>Sample</sample>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  createState() => MyWidgetState();
}

class MyWidgetState extends State<MyWidget> {
  TextEditingController _cont1;
  TextEditingController _cont2;
  FocusNode _textFocusNode = FocusNode();

  @override
  initState() {
    _cont1 = TextEditingController();
    _cont2 = TextEditingController();

    _cont1.text = 'Text selection works here';
    _cont2.text = 'Text selection does not work\nwhen text is multi-line.';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextField(controller: _cont1),
        EditableText(
          controller: _cont2,
          focusNode: _textFocusNode,
          style: TextStyle(color: Colors.black, fontFamily: "Roboto Mono"),
          cursorColor: Colors.blue,
          backgroundCursorColor: Colors.grey,
          selectionColor: Colors.lightBlue,
          maxLines: 100,
        ),
      ],
    );
  }
}
```
</details>

**Comment by mdebbar** [comment]
@johnpryan `EditableText` provides very basic selection support. You can't double-tap or drag your mouse to select. It's the same on iOS and Android as well.

**Comment by DannyJoinedApps** [comment]
One extra detail: with just one extra line I find any text on that second line doesn't always render.
Contrasting:
--release --dart-define=FLUTTER_WEB_USE_SKIA=true
with the other suggestion of:
--release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true

The latter is NOT as good. The selection draws with jank, stutters especially as the mouse crosses line divides, also space characters aren't rendered, (and yes, I realise spaces are blank, so perhaps better to write that 'the cursor doesn't move') until a following character (one with shaded pixels) is drawn. So the former suggestion (the one repeatedly proffered in this trail), is much better. I have zero technical understanding of what either mean, I just needed a workaround quickly to tried both.

In case anyone at google reading this, exactly as someone wrote above, we all know web is in beta, but to get our companies to start adoption we have started building web interfaces. In my case they are internal, and a few bugs are fine but this is a pretty vital one, text entry is such a biggy in corporate apps.

**Comment by mdebbar** [comment]
@DannyJoinedApps please file an issue describing what you are seeing (screenshots would be nice to have). Also please make sure to upgrade to the latest master version. The issue of the cursor not moving should've been fixed last week.

**Comment by DannyJoinedApps** [comment]
@mdebbar Hi, sorry, really sorry, I should have checked. You are absolutely right - upgraded and all is fixed. Works perfectly :) Thank you!!
