### ISSUE TITLE
Cannot  using http.post 

### ISSUE THREAD

**Issue by dione24** [flutter/flutter#55621]
final response = await http.post(
      "http://172.0.0.1/login.php",
      body: {
        'login': controllerUser.text,
        'password': controllerPass.text,
      },
    );

    var datauser = convert.jsonDecode(response.body);

Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^
)

**Comment by BaderEddineOuaich** [comment]
Your client is expecting JSON data response, but the server is returning other format HTML, XML...
make sure the server returns valid JSON data.

**Comment by stuartmorgan** [comment]
This does not appear to be describing a bug in Flutter, so closing. See https://flutter.dev/community for general help resources.
