### ISSUE TITLE
VirtualView node must not be the root node.

### ISSUE THREAD

**Issue by lishaoshi** [flutter/flutter#55626]
E/AccessibilityBridge(32600): VirtualView node must not be the root node.
E/AccessibilityBridge(32600): VirtualView node must not be the root node.
![image](https://user-images.githubusercontent.com/31604612/80273058-b6370e80-8701-11ea-8f12-606b122b93ac.png)
![image](https://user-images.githubusercontent.com/31604612/80273065-c0590d00-8701-11ea-9f86-1e7865288ba4.png)
It will execute as long as it scrolls

**Comment by ishandeveloper** [comment]
Hey @lishaoshi ! I believe @eseidelGoogle has already mentioned a solution for this issue in this comment https://github.com/flutter/flutter/issues/50892#issuecomment-610516957

> We have another stable release coming soon. It's likely too close to that release for us to take the risk of trying to make a new hotfix including an engine release.
> Thanks for flagging and sorry for all the log spam. We're continuing to work on improving our release processes to catch bugs like this earlier.
> The easiest workaround for now is to just use flutter channel beta to switch to the beta channel where we have resolved this bug. Thanks!

**Comment by iapicca** [comment]
Hi @lishaoshi 
can you please provide your `flutter run --verbose` ,
your `pubspec.yaml` 
and a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as fixed https://github.com/flutter/flutter/issues/50892#issuecomment-593615696
