### ISSUE TITLE
flutter command finished with exit code 3 

### ISSUE THREAD

**Issue by onyxtm** [flutter/flutter#55633]
hi, i command pub get in terminal and terminal return **Process finished with exit code 3**

**Flutter** **Doctor**
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17134.1425], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] VS Code, 64-bit edition (version 1.43.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by onyxtm** [comment]
i got **Process finished with exit code 3** When i user pub get in android studio

**Comment by JoDeveloper** [comment]
It seems the problem in your `pubsc.yaml`

**Comment by onyxtm** [comment]
this happend for all action, flutter clean, docter ,...

**Comment by JoDeveloper** [comment]
> hi, i command pub get in terminal and terminal return **Process finished with exit code 3**
> 
> **Flutter** **Doctor**
> 
> ```
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17134.1425], locale en-US)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.6)
> [!] VS Code, 64-bit edition (version 1.43.2)
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
> ```

flutter doctor is good!

**Comment by iapicca** [comment]
Hi @onyxtm 
can you please provide 
your `flutter pub get --verbose` ,
and your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Hi @onyxtm 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
