### ISSUE TITLE
Can't use setState()

### ISSUE THREAD

**Issue by Joja81** [flutter/flutter#55635]
void main() => runApp(MyApp());
    
    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(title: 'Flutter Demo', home: FirstScreen());
      }
    }
    
    // ignore: must_be_immutable
    class FirstScreen extends MyApp {
      TextEditingController _textController = TextEditingController();
    
      String reply = "";
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text('First screen'),
          ),
          body: ListView(
            children: <Widget>[
              GestureDetector(
                child: Hero(
                  tag: 'image hero',
                  child: Image.asset('assets/dog.jpg'),
                ),
                onTap: () {
                  onPress(context);
                },
              ),
              TextField(
                controller: _textController,
              ),
              Text(
                reply,
              ),
            ],
          ),
        );
      }
    
      void onPress(BuildContext context) {
        @override
        String input = _textController.text;
    
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => SecondScreen(
              text: input,
            ),
          ),
        );
      }
    }
    
    class SecondScreen extends StatelessWidget {
      final String text;
      SecondScreen({Key key, @required this.text}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: GestureDetector(
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Hero(
                    tag: 'image hero',
                    child: Image.asset('assets/dog.jpg'),
                  ),
                  Text(text),
                ],
              ),
            ),
            onTap: () {
              Navigator.pop(context, "hello");
            },
          ),
        );
      }` 
I'm quite new to flutter and dart so sorry if this is a really basic problem. I am trying to learn how to move between pages and was sending variables between the two pages. I was trying to update a text box however I have been unable to use setState() in the onPress method. I just get an error asking if I want to create a new method.

**Comment by JoDeveloper** [comment]
You cant use `setState` in `StatelessWidget`

**Comment by KenanYusubov** [comment]
To use  `setState` you should extend StatefulWidget.

**Comment by JoDeveloper** [comment]
Just Use `StatefulWidget` instead of `StatelessWidget`

**Comment by Joja81** [comment]
Thanks
