### ISSUE TITLE
unable to create emulator in vscode

### ISSUE THREAD

**Issue by Prashant1102** [flutter/flutter#55646]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by Prashant1102** [comment]
When I am clicking on Flutter:Select Device it is showing me Invalid argument(s): Cannot find executable for null.

**Comment by jonahwilliams** [comment]
This sounds like your flutter is not configured on the path properly. I would recommend carefully following the instructions at https://flutter.dev/docs/get-started/install for your operating system
