### ISSUE TITLE
Finished with error: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by vishalrajbh** [flutter/flutter#55650]
Compiler message:
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:377:11: Error: No named parameter with the name 'overflow'.
          overflow: TextOverflow.ellipsis,
          ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:400:13: Error: No named parameter with the name 'overflow'.
            overflow: TextOverflow.ellipsis,
            ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:2093:9: Error: No named parameter with the name 'overflow'.
        overflow: TextOverflow.ellipsis,
        ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:2133:13: Error: No named parameter with the name 'overflow'.
            overflow: TextOverflow.ellipsis,
            ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:2231:11: Error: No named parameter with the name 'overflow'.
          overflow: TextOverflow.ellipsis,
          ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/material/tabs.dart:89:32: Error: No named parameter with the name 'softWrap'.
    return child ?? Text(text, softWrap: false, overflow: TextOverflow.fade);
                               ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/date_picker.dart:644:13: Error: No named parameter with the name 'semanticsLabel'.
            semanticsLabel: localizations.datePickerHourSemanticsLabel(hour),
            ^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/date_picker.dart:672:13: Error: No named parameter with the name 'semanticsLabel'.
            semanticsLabel: localizations.datePickerMinuteSemanticsLabel(minute),
            ^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/date_picker.dart:1433:15: Error: No named parameter with the name 'maxLines'.
              maxLines: 1,
              ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/date_picker.dart:1452:27: Error: No named parameter with the name 'softWrap'.
        child: Text(text, softWrap: false, maxLines: 1, overflow: TextOverflow.visible),
                          ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart:1399:7: Error: No named parameter with the name 'maxLines'.
      maxLines: 1,
      ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/text_field.dart:770:25: Error: No named parameter with the name 'maxLines'.
                        maxLines: widget.maxLines,
                        ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'textDirection' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:351:23: Context: 'textDirection' is defined here.
  final TextDirection textDirection;
                      ^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'locale' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:360:16: Context: 'locale' is defined here.
  final Locale locale;
               ^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'softWrap' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:365:14: Context: 'softWrap' is defined here.
  final bool softWrap;
             ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'overflow' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:368:22: Context: 'overflow' is defined here.
  final TextOverflow overflow;
                     ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'textScaleFactor' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:378:16: Context: 'textScaleFactor' is defined here.
  final double textScaleFactor;
               ^^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'maxLines' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:391:13: Context: 'maxLines' is defined here.
  final int maxLines;
            ^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:270:9: Error: Final field 'semanticsLabel' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  const Text(
        ^
/D:/flutter/packages/flutter/lib/src/widgets/text.dart:405:16: Context: 'semanticsLabel' is defined here.
  final String semanticsLabel;
               ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':flutter:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by jonahwilliams** [comment]
This is just a regular compilation error:

```
/D:/flutter/packages/flutter/lib/src/material/input_decorator.dart:377:11: Error: No named parameter with the name 'overflow'.
overflow: TextOverflow.ellipsis,
^^^^^^^^
```

Are you running a newer flutter app with an outdated flutter version? This could perhaps happen if the `flutter` on your path is different than you would expect.

Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by vishalrajbh** [comment]
im just started  using flutter and its working fine few hours ago im running default flutter first welcome
program.

**Comment by vishalrajbh** [comment]
Hey
 now its working fine delete my project  and create new project
