### ISSUE TITLE
Is there anyway to get nearby drivers and lat lng as an address in flutter

### ISSUE THREAD

**Issue by ishane96** [flutter/flutter#55655]
In my taxi app, I need to get the nearby drivers to customer and, retrieving lat lng as an address from firestore.

Thanks

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
