### ISSUE TITLE
How to filt a photo in stack's positioned?

### ISSUE THREAD

**Issue by mariamalbarghouti** [flutter/flutter#55656]
**i'm in need to make a photo fit the left side of the stack but i can not do so .
and also the text on the button can not be in the center .
i tried to wrap the text by center widget But no thing changed!**

***this is the code:***  

          Container _homeListView() {
            return Container(
                margin: EdgeInsetsDirectional.only(top: 0),
                child: LayoutBuilder(
                  builder: (context, constraints) => Stack(
                    fit: StackFit.expand,
                    // alignment: Alignment.center,
                    children: <Widget>[
                      Material(
                        color: Colors.white,
                      ),
                      Positioned(
                        left: 4,
                        top: 0,
                        child: SvgPicture.asset(
                          'assets/images/accessories.svg',
                          height: constraints.maxHeight * 0.5,
                          width: constraints.maxWidth * 0.8,
                        ),
                      ),
    Positioned(
                    top: ((constraints.maxHeight)-constraints.maxHeight * 0.4),
                    right:(((constraints.maxWidth)-(constraints.maxWidth * 0.7)) /2),
                    left:(((constraints.maxWidth)-(constraints.maxWidth * 0.7)) /2),
                    //left: 1,
                    // top:((constraints.maxHeight)-(constraints.maxHeight * 0.08)),
                    child: Container(
                      
                      height:  constraints.maxHeight * 0.13,
                      decoration: BoxDecoration(
                        
                          borderRadius: BorderRadius.all(Radius.circular(30)),
                          border:
                              Border.all(color: const Color(0xffe8e5e1), width: 1),
                          boxShadow: [
                            BoxShadow(
                                color: const Color(0x29000000),
                                offset: Offset(0, 3),
                                blurRadius: 6,
                                spreadRadius: 0)
                          ],
                          color: const Color(0xffffffff)),
                      
                        child: Text(
                          "Click here",
                       
                          textAlign: TextAlign.center,            
                          style: TextStyle(
                             fontSize: constraints.maxHeight * 0.08,
                            color: Color(0xff257864),
                          ),
                        ),
                      
                    ),
                  ),
                      
                    ],
                  ),
                ),
                );
          }

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
