### ISSUE TITLE
The flutter tool should surface the originating package when dependency's asset bundles have errors

### ISSUE THREAD

**Issue by dgurudot** [flutter/flutter#55657]
## Steps to Reproduce

1. Recently upgrade Xcode to latest version 11.4.1
2. Also did upgrade flutter and few packages

**Expected results:** 
App was working just a day before I did upgrade flutter and xcode.

**Actual results:** 

1. Don't see any images loaded from assets directory
2. Don't see any fonts getting used
3. No fontawesome icons loading

/Users/vwork/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/vwork/development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/vwork/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • VIPhone • 71abd87bd654537024591e3131cb4fd1ade326c6 • ios • iOS 13.3.1

• No issues found!
Process finished with exit code 0

</details>

**Comment by jonahwilliams** [comment]
Why do you think this is a bug with flutter?  If `packages/timezone/data/2019c.tzf` is not present you need to remove it from the asset list

**Comment by dgurudot** [comment]
Two reasons:

1. I never had this asset file in my app until flutter upgrade so all of a sudden this became a new requirement. I will read about it and try to find this file from internet and add it to assets.

2. My primary issue is that no assets are loading now in my app. This includes images, fonts and all my font awesome icons.

**Comment by dgurudot** [comment]
I tried to even switch to master channel but that didn't help. I still get the following:

Error detected in pubspec.yaml:
    No file or variants found for asset: packages/timezone/data/2019c.tzf.

    Target debug_ios_bundle_flutter_assets failed: Exception: Failed to bundle asset files.
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on VIPhone.

**Comment by dgurudot** [comment]
I had the following issue in past 
https://github.com/flutter/flutter/issues/52084
and used the following steps to resolve it
https://flutter.dev/docs/development/ios-project-migration

I am not sure if they are related but I thought to mention it here.

**Comment by jonahwilliams** [comment]
This error just indicates that you have an asset in your pubspec.yaml which doesn't exist. If you're not using the asset, remove it from the list

**Comment by dgurudot** [comment]
I don't even have this specific asset listed in pubspec.yaml . I will paste the pubspec.yaml shortly. 
Another interesting point is that same code is working for other developers. Sharing "flutter doctor -v" from two of them where it works.

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/an/tools/flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/an/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • EF65AC89-EF32-40A8-AE99-E86FC179BDA0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.


=============================

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.9 at /home/vab/dev/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/vab/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by dgurudot** [comment]
Sharing pubspec.yaml and you can notice that there is no timezone file listed here

name: XXXX
description: XXXX
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Extra packages
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  fluttertoast: ^4.0.1
  random_color: ^1.0.5
  font_awesome_flutter: ^8.8.1
  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  flutter_webview_plugin: ^0.3.11
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.7
  image_picker: ^0.6.5+2
  flutter_picker: ^1.1.3
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.5
  local_auth: ^0.6.2+1
  scoped_model: ^1.0.1
  auto_size_text: ^2.1.0
  logger: ^0.9.1
  rxdart: ^0.24.0
  transparent_image: ^1.0.0
  flutter_candlesticks: ^0.1.4
  flutter_custom_tabs: ^0.6.0
  web_socket_channel: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  rxdart_codemod: ^0.1.5
  jiffy: ^3.0.1
  pull_to_refresh: ^1.5.8
  flutter_circular_chart: ^0.1.0
  syncfusion_flutter_charts: ^18.1.45
  syncfusion_flutter_calendar: ^18.1.45-beta
  syncfusion_flutter_gauges: ^18.1.45
  syncfusion_flutter_core: ^18.1.45
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.5
  splashscreen: ^1.2.0
  google_sign_in: ^4.4.4
  cached_network_image: ^2.1.0+1
  device_info: ^0.4.2+2
  flutter_slidable: ^0.5.4
  device_ext_info: ^0.0.2
  flutter_device_type: ^0.2.0
  flutter_markdown: ^0.3.5
  vibration: ^1.2.4
  flutter_custom_clippers: ^1.1.1
  flutter_appavailability: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome/fa-regular-400.woff2
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf

**Comment by dgurudot** [comment]
BTW, my real issue is not the specific timezone asset file. My primary issue is that I have trouble loading any assets.
1. No images from assets directory works.
2. No fonts
3. FontAwesome also doesn't work

**Comment by dgurudot** [comment]
This issue is consistent on both Desktop and Laptop where I did upgrade for XCode and Android Studio (along with plugin). I tried the same code on android simulator as well and can see the same issue which makes me believe that it is related to Flutter or maybe Android Studio or some plugin.

**Comment by ekiny** [comment]
My app also started to throw the same error after I add "syncfusion_flutter_calendar: ^18.1.45-beta" library. I think we need ask this question to syncfusion.

**Comment by adityagautam98** [comment]
I faced the same problem today after running pub upgrade. I spent hours figuring out the problem. I have reverted back my changes by deleting the local repository and downloading it again from my gitHub repo. (Luckily I had pushed to my github repo very recently). I have also tried downgrading flutter version, but it didn't help.
I guess the problem is with some dependency(**most probably syncfusion**, as it was also present in my pubspec though I am not using it now) rather than flutter itself.

**Comment by adityagautam98** [comment]
> I faced the same problem today after running pub upgrade. I spent hours figuring out the problem. I have reverted back my changes by deleting the local repository and downloading it again from my gitHub repo. (Luckily I had pushed to my github repo very recently). I have also tried downgrading flutter version, but it didn't help.
> I guess the problem is with some dependency(**most probably syncfusion**, as it was also present in my pubspec though I am not using it now) rather than flutter itself.

Main problem is that the error message is very unclear. Check if error goes by removing syncfusion calendar related dependencies or try to revert back to the state before you ran pub upgrade.

**Comment by jonahwilliams** [comment]
It sounds like the bug for the tool is that we need to surface where missing assets are coming from better?

Looking at the syncfusion calendar repo, the pubspec inexplicably contains the lines:

```
flutter:
  assets:
    - packages/timezone/data/2019c.tzf
```

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/55701 will ensure that the package causing the missing asset error will be surfaced

**Comment by dgurudot** [comment]
Removing the sync fusion calendar fixed the issue.

Thx Jonah for tracking this issue. It was clearly bizarre and logs were misleading and not pointing to where is the issue.

Thx everyone for quick help to isolate this issue.

**Comment by dgurudot** [comment]
Syncfusion defects also opened

https://www.syncfusion.com/forums/153715/syncfusion-18-45-calendar-beta-has-serious-issue-and-affects-all-asset-loading

**Comment by lgomezm** [comment]
Here's a workaround:
Go to timezone-0.5.7 dependency directory:
`cd $FLUTTER/.pub-cache/hosted/pub.dartlang.org/timezone-0.5.7`
You might need to run `flutter pub get`. Then run:
`flutter pub run tool/get -s 2019c`

**Comment by rkg0612** [comment]
I'm also having this problem when I add this dependency `syncfusion_flutter_calendar 18.1.45-beta` in my project. I need it because of its functionality but to no avail I can't get it to work. A workaround I've tried is install the timezone file on my project manually and only then the project will run with no errors.

**Comment by Nijamudeen-Mohamed** [comment]
We have fixed this and it will be updated in https://pub.dev/packages/syncfusion_flutter_calendar shortly.

**Comment by rkg0612** [comment]
> We have fixed this and it will be updated in https://pub.dev/packages/syncfusion_flutter_calendar shortly.

Please keep us posted for the update. Our team really needs this plugin. Thank you!

**Comment by aTeamSolace** [comment]
@Nijamudeen-Mohamed  still this issue occured

**Error detected in pubspec.yaml:
No file or variants found for asset: packages/timezone/data/2019c.tzf.**

 [syncfusion_flutter_calendar: ^18.1.45-beta](https://pub.dev/packages/syncfusion_flutter_calendar#-readme-tab-)

due to this issue all icons and all asset images gives error

**Comment by Nijamudeen-Mohamed** [comment]
@aTeamSolace , We have fixed this, its in the testing phase. we will ensure all possible scenarios and update the package in https://pub.dev/packages/syncfusion_flutter_calendar before EOD today (28th Apr 2020). we appreciate all your patience.

**Comment by aTeamSolace** [comment]
@Nijamudeen-Mohamed 
 yes okay Thanks for informing

**Comment by Nijamudeen-Mohamed** [comment]
We have fixed the mentioned issue in the Flutter event calendar and included the issue fix in our latest weekly package. Kindly update the Flutter calendar package to the latest version https://pub.dev/packages/syncfusion_flutter_calendar **(18.1.46-beta)**. Also please find the changelog for the same. 
 
**Link:** https://pub.dev/packages/syncfusion_flutter_calendar#-changelog-tab- 

You can also contact us through our [support forum](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/incidents), or [feedback portal](https://www.syncfusion.com/feedback/flutter). We are always happy to assist you!
