### ISSUE TITLE
Open two photo albums or camera pages

### ISSUE THREAD

**Issue by zenghuixiang** [flutter/flutter#55660]
Var image = await imagepicker. pickImage(source: imagesource. gallery); In this function, I will open two albums or albums, specifically, when I install the app and open the camera or album for the first time, it will appear that I selected a picture, the first one disappeared, I will choose again. The version used is 0.6.5+2.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
