### ISSUE TITLE
Run executable in flutter

### ISSUE THREAD

**Issue by cristianonescu** [flutter/flutter#55678]
## Proposal
Is Flutter able to run a binary file with params that was generated from a cpp project?

**Comment by jonahwilliams** [comment]
Do you mean something like https://flutter.dev/docs/development/platform-integration/c-interop ?

Generally I think mobile applications are restricted from launching new processes.

**Comment by cristianonescu** [comment]
> Do you mean something like https://flutter.dev/docs/development/platform-integration/c-interop ?
> 
> Generally I think mobile applications are restricted from launching new processes.

Actually I have an OpenCV binary file that I have to execute with a parameter that expects a photo.
Is there a way to integrate a cpp binary? (I don't have acces to the source, just the binary)

**Comment by jonahwilliams** [comment]
This sounds more like a help/support request than a bug in flutter.

The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
