### ISSUE TITLE
Flutter  google_sign_in & firebase_auth: mysterious accesses!

### ISSUE THREAD

**Issue by nikkelberg** [flutter/flutter#55676]
Hi everyone!

In this day I have implemented a google sign in my flutter application with firebase, to try.
Today I opened the firebase authentication page and noticed multiple authentications to my application. Being a trial application and therefore no one has access, how is this possible?

This is the code,

```
import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:ride/api/domain/member.dart';
import 'package:ride/api/repository/member_repository.dart';
import 'package:ride/api/service/service_locator.dart';

class GoogleAuthService {
  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final _memberRepository = ServiceLocator().get<MemberRepository>();

  Future<void> googleSignIn() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    final FirebaseUser user =
        (await _auth.signInWithCredential(credential)).user;

    final names = user.displayName.split(' ');
    final firstName = names[0];
    final lastName = names.length > 1 ? names[1] : '';

    if (await _memberRepository.findByAuthUserId(user.uid) == null) {
      await _memberRepository
          .save(Member.create(user.uid, firstName, lastName, user.email));
    }
    print("signed in " + user.displayName);
  }

  void signOut() {
    _auth.signOut();
  }
}

```

Thanks in advance for your help in resolving this phantom menace!

**Comment by iapicca** [comment]
Hi @nikkelberg 
your seems to be an issue with firebase as a service rather than with google_sign_in plugin
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by Kretin1** [comment]
Google bots can create accounts when testing. For one update I got about 40 fake sign-ups from the bots. You can tell if they're test accounts because they don't sign up from within your app, so for me there's no corresponding user accounts in Firestore.
