### ISSUE TITLE
 When EditText has emoji, the maximum length of editable.dart will be abnormal length and cursor abnormality

### ISSUE THREAD

**Issue by Linsixu** [flutter/flutter#55670]
/***
*** my class example : maxlength = 15
***/

```
TextField(
                 controller: TextEditingController.fromValue(TextEditingValue(
                                  text: _txtController.text,
                                  selection: TextSelection.fromPosition(
                                      TextPosition(affinity: TextAffinity.downstream, offset:_txtController.text.length)))),
                 decoration: InputDecoration(
                           border: InputBorder.none,
                  ),
                 style: TextStyle(fontSize: 16),
                  inputFormatters: [
                                LengthLimitingTextInputFormatter(15),
                   ]
)
```

descrition: When the input box contains an emoticon, when 16 characters are input, the input box can still display the 16th character, and then the cursor moves to the 15th character position.

my hope：When the input box contains an emoticon, when 16 characters are input, the input box can still display 15 characters, and then the cursor moves to the 15th character position.

find：I find the source -（editable_text.dart） do not  deal with max length state. 
So I want to solve this bug only through the business layer to make logical judgments。

My Solution for suspension
1. add field to get maxLength number;
2. This is what I need for work;(this is my work need)

```
     final int selfMaxLength;
     final Function maxLengthCallBack;
     final TextEditingController myController;

    @override 
    void initState() {
    ……
    myController =  TextEditingController.fromValue(TextEditingValue(
                                  text: _txtController.text,
                                  selection: TextSelection.fromPosition(
                                      TextPosition(affinity: TextAffinity.downstream, offset:_txtController.text.length))));
    if (widget.controller.text.length == widget.selfMaxLength) {
       hasAlreadyMaxLength = true;
       lastMaxContent = widget.controller.text;
    } else {
      hasAlreadyMaxLength = false;
      lastMaxContent = "";
          }
    }
 
    @override
    Widget build(BuildContext context) {
          return Container(
                child: TextField(
                 controller: myController,
                 decoration: InputDecoration(
                           border: InputBorder.none,
                  ),
                 style: TextStyle(fontSize: 16),
                  inputFormatters: [
                                LengthLimitingTextInputFormatter(15),
                   ]，
                   onChanged: (String value) {
                    _actionMaxLengthState(value);
                  }
                 )
          )
    }

    void _resetSelection(String newText) {
     var sRunes = newText.runes;
     String result;
     for (int i = 0; i < sRunes.length; i++) {
         if (String.fromCharCodes(sRunes, 0, sRunes.length - i).length <= widget.selfMaxLength) {
         result = String.fromCharCodes(sRunes, 0, sRunes.length - i);
         break;
      }
    }
    TextSelection temp = myController.value.selection.copyWith(
      baseOffset: result.length,
      extentOffset: result.length,
    );
    TextRange fixRange = widget.controller.value.composing;
    if (widget.controller.value.composing.end > result.length) {
      fixRange = TextRange(start: fixRange.start, end: result.length);
    } 
    
    //composing is used iOS inputMethod
    myController.value = TextEditingValue(text: result, selection: temp, composing: fixRange);
    lastMaxContent = result;
    }

    void _initOldDataSelection(String newText) {
          TextSelection actualSelection = myController.value.selection;
          actualSelection = myController.value.selection.copyWith(
                  baseOffset: lastMaxContent.length,
                  extentOffset: lastMaxContent.length,
           );
    //ios: When TextRange is not -1, the next update will replace all the variable values ​​of start and end directly. When you are sure that the content is unchanged, please change them to -1
    TextRange fixRange = TextRange(start: -1, end: -1);
          myController.value = TextEditingValue(text: lastMaxContent, selection: actualSelection, composing: fixRange);
    }

    void _actionMaxLengthState(String newText) {
    if (newText.length >= widget.selfMaxLength) {
      if (maxLengthCallBack != null) maxLengthCallBack();
      if (hasAlreadyMaxLength) {
        _initOldDataSelection(newText);
      } else {
        hasAlreadyMaxLength = true;
        _resetSelection(newText);
      }
    } else {
      //For the controller's text setting, you must change the value or set the text directly, and the selection is the default value of -1.
      widget.controller.value = TextEditingValue(text: newText, selection: widget.controller.value.selection, composing: widget.controller.value.composing);
      hasAlreadyMaxLength = false;
      lastMaxContent = "";
      }
    }
```

Finally, I hope flutter Team can resovle this question.

**Comment by VladyslavBondarenko** [comment]
Hi @Linsixu 
Could you please provide your `flutter doctor -v` and screen recording to better understand the issue?
I tried with `dev v1.18.0-8.0.pre` and `LengthLimitingTextInputFormatter` seems to be working as intended

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by Linsixu** [comment]
> Hi @Linsixu
> Could you please provide your `flutter doctor -v` and screen recording to better understand the issue?
> I tried with `dev v1.18.0-8.0.pre` and `LengthLimitingTextInputFormatter` seems to be working as intended

my version is Flutter 1.12.13+hotfix.7 • channel

**Comment by Linsixu** [comment]
> Hi @Linsixu
> Could you please provide your `flutter doctor -v` and screen recording to better understand the issue?
> I tried with `dev v1.18.0-8.0.pre` and `LengthLimitingTextInputFormatter` seems to be working as intended

my version is  1.12.13+hotfix.7 • channel

**Comment by TahaTesser** [comment]
Hi @Linsixu 
Trying to reproduce the issue on latest `master` based on  code sample

it correctly shows one and 14 characters

![flutter_01](https://user-images.githubusercontent.com/48603081/80461220-90ed0f00-8952-11ea-8bfd-274be8347671.png)

Is there any way you can this more apparent without going to source code?
```
I find the source -（editable_text.dart） do not deal with max length state.
```

Thank you

**Comment by justinmc** [comment]
I believe this is related to https://github.com/flutter/flutter/pull/53381 and its related issues.

@TahaTesser Try using an emoji that uses multiple bytes like 👨‍👩‍👦.

**Comment by Linsixu** [comment]
> Hi @Linsixu
> Trying to reproduce the issue on latest `master` based on code sample
> 
> it correctly shows one and 14 characters
> 
> ![flutter_01](https://user-images.githubusercontent.com/48603081/80461220-90ed0f00-8952-11ea-8bfd-274be8347671.png)
> 
> Is there any way you can this more apparent without going to source code?
> 
> ```
> I find the source -（editable_text.dart） do not deal with max length state.
> ```
> 
> Thank you



But the total font length has exceeded 15 characters. And if you add the cursor attribute, you will find that the cursor moves one character abnormally.

**Comment by Linsixu** [comment]
> I believe this is related to #53381 and its related issues.
> 
> @TahaTesser Try using an emoji that uses multiple bytes like 👨‍👩‍👦.
