### ISSUE TITLE
Downloading Material fonts... Could not authenticate download server. You may be experiencing a man-in-the-middle attack,

### ISSUE THREAD

**Issue by Tareque2208** [flutter/flutter#55681]
Everything was working fine here. Somehow dart analyzer started terminated and I deleted `cache` folder from `flutter/bin` . Then I run `flutter doctor` and got this error. 

## Logs

PS G:\AsifVi\IQRA\App\iqra> flutter doctor
Downloading Material fonts...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/fonts/13ac995daa9dda0a6ba0a45f1fccc541e616a74c/fonts.zip

![80950333-7534ad80-8e17-11ea-93fb-57a88770555f](https://user-images.githubusercontent.com/16764227/81002449-100aa780-8e6b-11ea-88de-1afb005bfdfa.png)

**Comment by joekendal** [comment]
Can you run flutter doctor with -vvv

**Comment by iapicca** [comment]
Hi @Tareque2208 
could you please answer these questions
[1](https://github.com/flutter/flutter/issues/48030#issuecomment-570156563) [2](https://github.com/flutter/flutter/issues/48030#issuecomment-570243549)
also are you from china or bangladesh?
Thank you

**Comment by Tareque2208** [comment]
> Hi @Tareque2208
> could you please answer these questions [1](https://github.com/flutter/flutter/issues/48030#issuecomment-570156563), [2](https://github.com/flutter/flutter/issues/48030#issuecomment-570243549);
> also are you from china or bangladesh?
> Thank you

I couldn't solve it yet. Even I setup my pc thinking as of my pc got infected by virus. But, It hasn't worked yet. So, If you find out any solution please help me out here. Btw, I am from Bangladesh. I am trying to setup the china mirror today and will let you know the update. Thanks in advance.

**Comment by DanTup** [comment]
This came up earlier in the year for users in Bangladesh. There are some notes and potential workarounds noted in https://github.com/flutter/flutter/issues/48030.

**Comment by TahaTesser** [comment]
Hi @Tareque2208 
Can you please go over the [#48030](https://github.com/flutter/flutter/issues/48030) and try the workarounds mentioned.
Thank you

**Comment by VladyslavBondarenko** [comment]
@Tareque2208 
I hope you've solved the issue.
Could everyone who still has this problem try workaround in mentioned issue. If didn't help, please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
