### ISSUE TITLE
Execution failed for task ':app:minifyReleaseWithR8'.

### ISSUE THREAD

**Issue by MajidAlNuumani** [flutter/flutter#55680]
try build app using this command 

`flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi`

has problem to build it

```
* What went wrong:                                                      
Execution failed for task ':app:minifyReleaseWithR8'.                   
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
```

flutter doctor -v log

`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.12.13+hotfix.9 at /Users/majidalnuumani/Documents/development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/majidalnuumani/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/majidalnuumani/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Pixel 4 XL       • 9B191FFBA002R8                           • android-arm64 • Android 10 (API 29)

• No issues found!`

flutter verbose -v

**Comment by jonahwilliams** [comment]
If you examine the logs of `flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi -v` you'll should see what is causing the issue.

This is most likely not an issue with flutter, but I'll keep it open to confirm

**Comment by TahaTesser** [comment]
Hi @MajidAlNuumani 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
