### ISSUE TITLE
AlwaysScrollableScrollPhysics velocity !

### ISSUE THREAD

**Issue by NicolasCELLA** [flutter/flutter#55683]
Hello, when i use the AlwaysScrollableScrollPhysics on my listview (ios), the velocity scroll is very fast ! 

You can compare on this video between my application and after Instagram :

https://youtu.be/Ws8PCM_9DO4

How to render slower AlwaysScrollableScrollPhysics and keep the bouncing when a scroll on top ?

Thx for your help 😇

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
