### ISSUE TITLE
Debug the database and local storage.

### ISSUE THREAD

**Issue by duomoteng** [flutter/flutter#55688]
Hi, I am working on an app that saves some data on the sqlite and some file in the local storage. Is there a method to debug it from my computer?

I mean, I can see the file structure and the database from my computer, and I can open the file or edit it from my computer.

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
