### ISSUE TITLE
PlatformAssetBundle load does not care about extension capitalization

### ISSUE THREAD

**Issue by erf** [flutter/flutter#55697]
I did `await rootBundle.load(asset)` to load an image from asset and by accident gave it a wrong asset name where the extension was capitalized and noticed this still loaded the image asset. My asset was `myasset.png`, but i used `myasset.PNG`. Should this not throw an exception?

**Comment by TahaTesser** [comment]
Hi @erf 
After `.`, I believe `png` is same as `PNG`
Even in normal situation like if you rename `image.png` to `image.PNG`, it won't effect your image and it will still open 
Thank you

**Comment by erf** [comment]
@TahaTesser hmm, i would think Flutter would differentiate assets names on caps, but i guess not. Not really a problem, i just noticed it as i was caching on image name and there was a double entry, and i was curious as to how that happened.. btw, do you know if Flutter plans on doing cache for image assets?

**Comment by TahaTesser** [comment]
hI @erf 
Please check out [Work with cached images](https://flutter.dev/docs/cookbook/images/cached-images)

Regarding extension capitalization. Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by erf** [comment]
hi @TahaTesser 

I'm not caching a Image Widget, i'm caching a `ui.Image`.

This is happening in `PlatformAssetBundle.load` and i believe that is in a Flutter package.

Not sure what you mean by `.png` is the same as `.PNG`, of course the image is the same, but the filename is different. I would expect filenames would be case-sensitive, but i dont believe you have answered this properly.

Thank you

**Comment by TahaTesser** [comment]
Hi @erf 
Issue related, capatalizing extension doesn't make asset have wrong name. Unless you provide wrong filename, there is no issue. 

Regarding the caching issue, you can probably use [ImageCache](https://api.flutter.dev/flutter/painting/ImageCache-class.html) and also [ImageCache large images
](https://flutter.dev/docs/release/breaking-changes/imagecache-large-images)


Thank you

**Comment by erf** [comment]
Ok, thank you.

But do you know why `ui.Image`s arent caching when using `AssetBundle.load`, when `AssetBundle.loadString` is?

**Comment by TahaTesser** [comment]
Hi @erf 
Please check [AssetBundle.loadString api](https://api.flutter.dev/flutter/services/AssetBundle/loadString.html) and [AssetBundle.load api](https://api.flutter.dev/flutter/services/AssetBundle/load.html)

You can see in the `AssetBundle.loadString`, it decodes your data image

Hope this resolves your doubt

**Comment by erf** [comment]
@TahaTesser i'm now caching images the same way that `AssetBundle.loadString` is, thanks!
