### ISSUE TITLE
Random errors in iOS

### ISSUE THREAD

**Issue by mohisham** [flutter/flutter#55700]
I intermittently have build issues when I try to run on iOS.  Previously I would delete my "Pods" folder and Podfile.lock file, run `pod repo update` and `pod install`, and that would fix the issue.

However, I've now been stuck for 3 days on a build issue.  The only change I made was I upgraded a dependency in my pubspec.yaml file (`share` from 0.6.3+5 to 0.6.4).  

I have set the iOS deployment target to 11 in Xcode (in both Project and Target views)

I get the following error on trying to deploy to iOS simulator:
```
> Running pod install...
> Running Xcode build...
> Xcode build done.                                           213.3s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 


> Xcode's output:
> ↳
>     /Users/hmhm/AndroidStudioProjects/projectName/ios/Pods/Mantle/Mantle/extobjc/EXTRuntimeExtensions.m:749:12: warning: 'os_unfair_lock' is only available on iOS 10.0 or newer [-Wunguarded-availability]
>         static os_unfair_lock lock = OS_UNFAIR_LOCK_INIT;
>                ^~~~~~~~~~~~~~
>     In module 'Darwin' imported from /Users/hmhm/AndroidStudioProjects/projectName/ios/Pods/Mantle/Mantle/extobjc/EXTRuntimeExtensions.m:11:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/os/lock.h:79:3: note: 'os_unfair_lock' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
>     } os_unfair_lock, *os_unfair_lock_t;
>       ^
>     /Users/hmhm/AndroidStudioProjects/projectName/ios/Pods/Mantle/Mantle/extobjc/EXTRuntimeExtensions.m:749:12: note: enclose 'os_unfair_lock' in an @available check to silence this warning
>         static os_unfair_lock lock = OS_UNFAIR_LOCK_INIT;
>                ^~~~~~~~~~~~~~
>     /Users/hmhm/AndroidStudioProjects/projectName/ios/Pods/Mantle/Mantle/extobjc/EXTRuntimeExtensions.m:749:34: warning: 'os_unfair_lock' is only available on iOS 10.0 or newer [-Wunguarded-availability]
>         static os_unfair_lock lock = OS_UNFAIR_LOCK_INIT;
>                                      ^~~~~~~~~~~~~~~~~~~
>     In module 'Darwin' imported from /Users/hmhm/AndroidStudioProjects/projectName/ios/Pods/Mantle/Mantle/extobjc/EXTRuntimeExtensions.m:11:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/os/lock.h:83:31: note: expanded from macro 'OS_UNFAIR_LOCK_INIT'
>     #define OS_UNFAIR_LOCK_INIT ((os_unfair_lock){0})

.. and on and on ...!
```
Here is `flutter doctor` output:
```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CA)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)
> [!] IntelliJ IDEA Community Edition (version 2019.1.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
> [✓] VS Code (version 1.43.2)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
```
I've tried all of these:

1. Deleting Podfile.lock
2. `pod cache clean --all`
3. `rm -rf ~/Library/Caches/CocoaPods`
4. `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
5. `rm -rf Pods`
6. `pod deintegrate`
7. `pod setup`
8. `pod install`
9. Delete .flutter-plugins, .flutter-plugins-dependencies and pubspec.lock
10. `flutter clean`
11. `flutter pub cache repair`

Any other suggestions?

**Comment by mohisham** [comment]
I Just realized that my mac os x got updated (to 10.15.4) around the same time this problem started happening.  Could this be causing the issue?  Driving me mad, any help appreciated please!

**Comment by TahaTesser** [comment]
Hi @mohisham 
Can you try targeting 10.0+? 


```
'os_unfair_lock' is only available on iOS 10.0 or newer 
```

```
 note: 'os_unfair_lock' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
```

Doesn't look like Flutter issue to me

**Comment by mohisham** [comment]
Changing to 10.0 doesn't build at all.

Every time I build I'm getting a different error.  Until a few days ago I was not having this problem at all.  Here is what I am seeing now:

> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.m:22:
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/build/ios/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/PrivateHeaders/FBSDKErrorReport.h:20:
>     /Users/hmhm/AndroidStudioProjects/hoopo/build/ios/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/PrivateHeaders/FBSDKError.h:24:1: error: duplicate interface definition for class 'FBSDKError'
>     @interface FBSDKError : NSObject
>     ^
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.m:19:
>     /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.h:24:12: note: previous definition is here
>     @interface FBSDKError : NSObject
>                ^
>     1 error generated.
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:18:
>     /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/Private/GULReachabilityChecker.h:24:3: error: redefinition of enumerator 'kGULReachabilityUnknown'
>       kGULReachabilityUnknown,  ///< Have not yet checked or been notified whether host is reachable.
>       ^
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:17:
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker+Internal.h:17:
>     /Users/hmhm/AndroidStudioProjects/hoopo/build/ios/Debug-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULReachabilityChecker.h:24:3: note: previous definition is here
>       kGULReachabilityUnknown,  ///< Have not yet checked or been notified whether host is reachable.
>       ^
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:18:
>     /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/Private/GULReachabilityChecker.h:25:3: error: redefinition of enumerator 'kGULReachabilityNotReachable'
>       kGULReachabilityNotReachable,  ///< Host is not reachable.
>       ^
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:17:
>     In file included from /Users/hmhm/AndroidStudioProjects/hoopo/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker+Internal.h:17:
>     /Users/hmhm/AndroidStudioProjects/hoopo/build/ios/Debug-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULReachabilityChecker.h:25:3: note: previous definition is here
>       kGULReachabilityNotReachable,  ///< Host is not reachable.

**Comment by mohisham** [comment]
Changing to 10.0 doesn't build at all.

Every time I build I'm getting a different error. Until a few days ago I was not having this problem at all. Here is what I am seeing now:

Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.m:22:
In file included from /Users/hmhm/AndroidStudioProjects/myproject/build/ios/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/PrivateHeaders/FBSDKErrorReport.h:20:
/Users/hmhm/AndroidStudioProjects/myproject/build/ios/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/PrivateHeaders/FBSDKError.h:24:1: error: duplicate interface definition for class 'FBSDKError'
@interface FBSDKError : NSObject
^
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.m:19:
/Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKError.h:24:12: note: previous definition is here
@interface FBSDKError : NSObject
^
1 error generated.
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:18:
/Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/Private/GULReachabilityChecker.h:24:3: error: redefinition of enumerator 'kGULReachabilityUnknown'
kGULReachabilityUnknown, ///< Have not yet checked or been notified whether host is reachable.
^
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:17:
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker+Internal.h:17:
/Users/hmhm/AndroidStudioProjects/myproject/build/ios/Debug-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULReachabilityChecker.h:24:3: note: previous definition is here
kGULReachabilityUnknown, ///< Have not yet checked or been notified whether host is reachable.
^
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:18:
/Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/Private/GULReachabilityChecker.h:25:3: error: redefinition of enumerator 'kGULReachabilityNotReachable'
kGULReachabilityNotReachable, ///< Host is not reachable.
^
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker.m:17:
In file included from /Users/hmhm/AndroidStudioProjects/myproject/ios/Pods/GoogleUtilities/GoogleUtilities/Reachability/GULReachabilityChecker+Internal.h:17:
/Users/hmhm/AndroidStudioProjects/myproject/build/ios/Debug-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULReachabilityChecker.h:25:3: note: previous definition is here
kGULReachabilityNotReachable, ///< Host is not reachable

**Comment by TahaTesser** [comment]
Hi @mohisham 
can you please provide your `flutter doctor -v` with (verbose)  and `flutter run --verbose`? 
Also you downgrade to previous working version of `share` and see if it fixes the issue?
Thank you

**Comment by mohisham** [comment]
@TahaTesser you are a lifesaver!  I'm using the Square Payments flutter library.  And it has been working fine so far, but for some reason during the build one of the framework directories wasn't getting copied over.  I noticed this line in the verbose log:

`SquareInAppPaymentsSDK.framework/setup: No such file or directory`

I manually copied it from the `Pods` folder to the `build` folder, and it started working again.  I still don't get why this is happening.  Any idea why?  Like I've said earlier, the only thing I did was change a version of the share library.

Thank you so much once again, I didn't know about the --verbose flag (doh).

**Comment by mohisham** [comment]
@TahaTesser I spoke too soon.  I tried building again, and now I'm seeing some different errors.  Nothing simple like a missing file now:

> The following build commands failed:
>             	CompileC /Users/hmhm/Library/Developer/Xcode/DerivedData/Runner-fbovzjmpmcmhkxcflptsaepkuuqb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKAccessTokenCache.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching/FBSDKAccessTokenCache.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>             	CompileC /Users/hmhm/Library/Developer/Xcode/DerivedData/Runner-fbovzjmpmcmhkxcflptsaepkuuqb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKAppEvents.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Here is the entire log:

[verbose_run_saved.txt](https://github.com/flutter/flutter/files/4548125/verbose_run_saved.txt)

**Comment by mohisham** [comment]
Ok I think I figured it out.  I had added a build phase for Square Payments Framework, and somehow it got moved to before the copying phase.  Since the phases are draggable, I'm guessing I must have dragged it up a few places by mistake.  Anyway, thanks for your help, it works now.

**Comment by mbeloded** [comment]
in my case only re-creating a new flutter app and copy ios folder to the old flutter project helped to solve this issue. The second time per week, it's horrible.

**Comment by mohisham** [comment]
I have too many settings that would get destroyed if I do this.  How did you manage?
