### ISSUE TITLE
framework not found WebKit-ObjC

### ISSUE THREAD

**Issue by Mike333333** [flutter/flutter#55702]
I get this error when running Flutter build iOS. Flutter doctor is not showing any issues.

**Comment by TahaTesser** [comment]
Hi @Mike333333 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Mike333333** [comment]
I did copy the iOS folder from another project it is working now. Thanks “@TahaTesser
