### ISSUE TITLE
Unspecific errors on console

### ISSUE THREAD

**Issue by pnwanno** [flutter/flutter#55703]
When an error is thrown in the console, they are usually unspecific (almost and always off target). They better absent - Just tell us there an error, so that we can find it our way, instead of driving our attentions to things are very unrelated to the actual error - wasting productive time that could have been used for other things (maybe sleeping).

Maybe you should check the errors thrown by php or javascript - very specific. Now, I'm not talking about the line number of the error - what exactly is the error, if you can't say what line the error was encountered.
This should be looked into, as it is frustrating

**Comment by goderbauer** [comment]
Thanks for the feedback. However, this bug is not very actionable and I am going to close it. If you see specific error messages that are unhelpful please file bugs for those so we can improve them.
