### ISSUE TITLE
Document what's inside of a flutter APK

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5571]
In an effort to help explain what all the files are, and why we need them, we can document the high-level explanation and "tour" of what's inside of a Flutter APK.

@eseidelGoogle wrote up a great explanation here: https://github.com/flutter/flutter/issues/5567#issuecomment-242090496

I would avoid specific sizes in the explanation (because they will fluctuate), but certainly we can talk about what things are and why they are there and link to any issues we may be tracking.

**Comment by eseidelGoogle** [comment]
I think this might be nice but is likely very low priority.  We're about to move to using gradle, so hopefully our apk construction will be as transparent as any.

**Comment by sethladd** [comment]
Once we get rid of FLX files, I agree, we should be able to rely mostly on standard APK diagnostic tools.

**Comment by Hixie** [comment]
Ok, we've removed FLXes.
