### ISSUE TITLE
Generating build script fails w/"pubspec.yaml file has changed" when referring to generator with path

### ISSUE THREAD

**Issue by shawnlauzon** [flutter/flutter#55719]
I am trying to run a builder which I created locally and which I want to access via the `path` argument in builders. So I add it to `pubspec.yaml`:
```
builders:
  generate:
    path: /Users/shawn/Documents/Development/shamya/generate     
```

Then I run `flutter run` which runs my builder:

> PS C:\Users\shawn\Documents\Development\shamya\astraios> flutter run
> generating build script...                                         21.6s
> Error generating build_script snapshot: The pubspec.yaml file has changed since the pubspec.lock file
> was generated, please run "pub get" again.

Running `pub get` or `flutter pub get` does not solve the problem. When I replace my local generator with the json_widget by @jonahwilliams, I get further (but still fails with flutter/flutter#42003)

This might be related to dart-lang/sdk#39738 but the error is different.

> PS C:\Users\shawn\Documents\Development\shamya\astraios> flutter doctor -v
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale
>     en-US)
>     • Flutter version 1.12.13+hotfix.9 at C:\Users\shawn\Downloads\Applications\flutter
>     • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
>     • Engine revision af51afceb8
>     • Dart version 2.7.2
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\shawn\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.2)
>     • VS Code at C:\Users\shawn\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.9.1
> 
> [√] Connected device (1 available)
>     • moto e6 • ZY326MD34D • android-arm • Android 9 (API 28)
> 
> • No issues found!

**Comment by jonahwilliams** [comment]
Superseded by https://github.com/flutter/flutter/issues/61508
