### ISSUE TITLE
Add target (-t) to aar library build option

### ISSUE THREAD

**Issue by tal-mi** [flutter/flutter#55728]
Building an Android library with multiple configurations.

Target option (-t) is not available for "flutter build aar" process.
Therefore it is not possible to choose the entry point file as in all other build configurations.

**Comment by jmagman** [comment]
Huh
https://github.com/flutter/flutter/blob/dd88b20435c1eb9b837bb4aa8b0a84aa0825530d/packages/flutter_tools/lib/src/commands/build_aar.dart#L118

**Comment by jmagman** [comment]
I was hoping to just add a `usesTargetOption()` but
https://github.com/flutter/flutter/blob/dd88b20435c1eb9b837bb4aa8b0a84aa0825530d/packages/flutter_tools/lib/src/commands/build_aar.dart#L128-L133

to parse the project from `argResults.rest` is fighting with the target parsing:
https://github.com/flutter/flutter/blob/d53429cf0a7d76dce82e36255fd3dd0bf36dc988/packages/flutter_tools/lib/src/runner/flutter_command.dart#L226-L228

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/55281.
