### ISSUE TITLE
Pesto in dark theme: menu text has wrong color

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#5572]
![pesto dark bug](https://cloud.githubusercontent.com/assets/211513/17940239/13a8b978-69e3-11e6-8cf4-6dc336866df9.png)

/cc @sethladd @HansMuller

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by HansMuller** [comment]
Pesto's app bar includes a popup menu. Pesto's app bar is defined within a theme that differs from the one defined by the gallery app.

A popup menu is just a route that appears via Navigator.push().

If a popup menu inherits from a theme that differs from the one that its Navigator descends from we should use the popup menu's theme. Currently the Navigator's theme is used.

This is a symptom of a general problem. Inherited widgets defined below the Navigator don't affect routes that have been pushed by that Navigator.

**Comment by HansMuller** [comment]
I have a fix that corrects the inherited theme problem for popup menus. 

I'm going to try and create a general solution, since it could also apply to Heroes and their inherited state.

**Comment by sethladd** [comment]
@HansMuller is there an issue for the general solution, that I can link to this?
