### ISSUE TITLE
Cirrus fails to create iOS simulator

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#55743]
We're getting the following error when when running the `create_simulator_script` task:

```
xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-13-3 | xargs xcrun simctl boot
Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-13-3
Exit status: 161
```

Sample log: https://cirrus-ci.com/task/4920503179673600?command=create_simulator#L89

@fkorotkov do you have an idea what may be going on?

**Comment by fkorotkov** [comment]
Over the weekend `catalina-flutter` image alias got changed from `catalina-xcode-11.3.1-flutter` to `catalina-xcode-11.4.1-flutter` but I saw builds passing for `flutter/flutter` 🤔

**Comment by jmagman** [comment]
Xcode 11.4 `xcrun simctl create` made the runtime optional, it will default to latest.  So instead of parsing the list of runtimes and taking latest, you can just leave it off.

**Comment by jmagman** [comment]
I can take this.

**Comment by jmagman** [comment]
Never mind, @fkorotkov is already working on this https://github.com/flutter/plugins/pull/2710/files#diff-0f7067c31caedf7df2739c9b07efa122R114.

**Comment by amirh** [comment]
This was fixed by https://github.com/flutter/plugins/pull/2710
