### ISSUE TITLE
Need light-weight code editor especially for flutter development

### ISSUE THREAD

**Issue by pratiklodha** [flutter/flutter#55746]
Hi!
We are eagerly waiting for a light-weight code editor especially for developing flutter apps. Very soon Flutter will not only be used only for mobile development but for developing webapps and desktop apps as well. Flutter is going to change the entire development landscape. Moreover, Android Studio is only suitable for native development.
 
We need a desktop software "Flutter Studio" with the following features:
1. In-built simulators for all platforms (i.e. Android, iOS, Web, Desktop) without asking us to install Android Studio and/or XCode.
2. Third-party extensions support (similar to VS Code).
3. In-built terminal support.
4. This one too please -> https://github.com/flutter/flutter/issues/54191#issuecomment-610611673

**Comment by stuartmorgan** [comment]
> In-built simulators for all platforms

Writing a simulator/emulator for all target platforms would be an enormous amount of work, and would provide little benefit given that it would just duplicate work that's already being done by others.

> and/or XCode

You can't build iOS or macOS apps without Xcode. This isn't a limitation of Flutter tooling, it's how you get the necessary SDKs.

A new IDE is out of scope for the Flutter project. There are various third-party efforts underway to build custom IDEs for Flutter; perhaps one of those will meet your needs if the officially supported IDEs do not. (However, my comments above will apply to them as well.)
