### ISSUE TITLE
Travis build failing on dartfmt error, but no details

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#5575]
It doesn't seem to be clear from the log which line of the code is actually causing the error and it's not obvious by visual inspection.

## Steps to Reproduce

Created a PR (https://github.com/flutter/website/pull/267) for a change to flutter/website.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/quddusc/flutter/flutter
    • Framework revision 20b9750a73 (21 hours ago), 2016-08-23 16:17:36
    • Engine revision 28e9b3bc49
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /usr/local/google/home/quddusc/Android/Sdk
    • Platform android-24, build-tools 24.0.0
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-128173541-128170350)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35

## Logs and Crash Reports

Full output log is [here](https://travis-ci.org/flutter/website/builds/154841329).

Relevant lines from Travis log:

```
20 code snippets extracted.
Analyzing the extracted Dart libraries.
Analyzing 20 files...
No analyzer warnings! (ran in 11.5s)
Check formatting of the extracted Dart libraries.
There are formatting errors in the following files:
example/reading_writing_files_md_1.dart
The command "./tool/travis.sh" exited with 1.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by qchong** [comment]
@sethladd

**Comment by sethladd** [comment]
cc @a14n 

Thanks for the report @qchong !

**Comment by sethladd** [comment]
@a14n if you think there's more actionable info that we can print (other than the file which was unformatted), please reopen. Otherwise, we know which file needs formatting love so I'm going to close.

**Comment by a14n** [comment]
`dartfmt` outputs the name of files that changes after reformat. That's what is display in logs:

```
There are formatting errors in the following files:
example/reading_writing_files_md_1.dart
```

I just push [a branch](https://github.com/a14n/flutter.github.io/tree/display-format-error) where the output looks like:

```
There are formatting errors in the following files:

===== example/widgets_intro_md_1.dart =====
----- expected format -----
// Extracted from widgets-intro.md, line 28.
import 'package:flutter/material.dart';

void main() {
  runApp(new Center(child: new Text('Hello, world!')));
}
----- current format -----
// Extracted from widgets-intro.md, line 28.
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Center(child: new Text('Hello, world!')));
}
----- diff -----
5c5,6
<   runApp(new Center(child: new Text('Hello, world!')));
---
>   runApp(
>     new Center(child: new Text('Hello, world!')));
===== /end example/widgets_intro_md_1.dart =====
```

Let me know if that's better. So I'll make a PR.

**Comment by sethladd** [comment]
Wow, nice. Since you already have the branch, we'll be happy to take a PR. Thank you!

**Comment by a14n** [comment]
created: flutter/website#268
