### ISSUE TITLE
Android sdkmanager tool not found Flutter

### ISSUE THREAD

**Issue by Davidromerojimenez** [flutter/flutter#55755]
please help me, i cant run my flutter project 
i tried to instal the obsolete android SDK tools but it does not work

Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

**Comment by VladyslavBondarenko** [comment]
Hi @Davidromerojimenez 
Take a look at https://github.com/flutter/flutter/issues/51670#issuecomment-592943797
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
