### ISSUE TITLE
Rename the flutter gallery before shipping

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5576]
We should make sure the version of the gallery we ship doesn't look to Android to have any relationship with the version in the repo, otherwise people who have one installed will get a conflict when they try to play with the other.

**Comment by eseidelGoogle** [comment]
Specifically the identifier here:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/android/AndroidManifest.xml
and here:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/ios/Runner/Info.plist
Should not be the same as the identifier used in the published Flutter Gallery.  This allows members of the Flutter team to have the officially deployed version of Flutter installed on their phones at the same time as they also have an in-development copy.

I'm not 100% sure what the official bundle identifiers are for Android or iOS but @sethladd or @jason-simmons would know.

**Comment by sethladd** [comment]
Looks like this was fixed?

cc @jason-simmons

**Comment by jason-simmons** [comment]
I fixed it on Android.  I don't know if iOS also needs changes.

**Comment by sethladd** [comment]
Will find out later. :) Thanks for the update!
