### ISSUE TITLE
flutter version command strips 'v' character

### ISSUE THREAD

**Issue by danielnovograd** [flutter/flutter#55768]
## Steps to Reproduce

1. Run `flutter version 1.17.0-dev.3.1` in the CLI
2. Enter 'y' for yes and hit enter

I ran into this when I was trying to upgrade from 1.13.6 and then when I tried to downgrade from 1.17.0-3.2.pre
## Logs

```
flutter version 1.17.0-dev.3.1
╔══════════════════════════════════════════════════════════════════════════════╗
║ Warning: "flutter version" will leave the SDK in a detached HEAD state.      ║
║ If you are using the command to return to a previously installed SDK version ║
║ consider using the "flutter downgrade" command instead.                      ║
╚══════════════════════════════════════════════════════════════════════════════╝


Are you sure you want to proceed? [y|n]: y
There is no version: 1.17.0-de.3.1
Unable to checkout version branch for version 1.17.0-de.3.1: ProcessException: Process exited
abnormally:
error: pathspec '1.17.0-de.3.1' did not match any file(s) known to git
  Command: git checkout 1.17.0-de.3.1
```

Running `flutter version '1.17.0-devv.3.1` installs the intended version.

**Comment by christopherfujino** [comment]
Thanks for filing this @danielnovograd. This issue was already filed as [#55421](https://github.com/flutter/flutter/issues/55421), so I am closing this as a duplicate. Please follow that issue for updates (there's an open PR that fixes it). Thanks again!
