### ISSUE TITLE
Heroes don't respond to updates in the previousRoute while animating

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#5577]
This became obvious while working on the iOS back gesture. Heroes do not update their target destination during a transition. So, if the previousRoute is moving during a `pop` transition, the Hero's target should move, but instead the Hero animates to where the target was when the `pop` first started.

**Comment by eseidelGoogle** [comment]
@HansMuller is working on Heros v2 as we speak, which may include this.

**Comment by HansMuller** [comment]
New Heroes do track their destination during the animation. I will close this once I've got a test to prove the fix.
