### ISSUE TITLE
[web] Not allowed to load local resource

### ISSUE THREAD

**Issue by zeppelin-tt** [flutter/flutter#55779]
After some time, the flutter web stops running in chrome. The only thing that helps is the creation of a new project and the transfer of the entire code base there. But this is enough for several hours of active work ... The browser opens, but nothing happens then. Only a white screen.

I'm on a beta channel, but on the master everything happens exactly the same.

> C:\flutter_projects\disinsection>flutter run -d chrome -v
> [  +20 ms] executing: [c:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] 2a7bc389f28d83c581f7ddd4601588a22e12512e
> [        ] executing: [c:\dev\flutter/] git describe --match *.*.* --first-parent --long --tags
> [  +50 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
> [        ] 1.17.0-3.2.pre-0-g2a7bc389f
> [  +11 ms] executing: [c:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/beta
> [        ] executing: [c:\dev\flutter/] git ls-remote --get-url origin
> [  +39 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [  +98 ms] executing: [c:\dev\flutter/] git rev-parse --abbrev-ref HEAD
> [  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] beta
> [  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +18 ms] executing: C:\Users\maxim\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [  +34 ms] List of devices attached
> [   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +211 ms] Generating C:\flutter_projects\disinsection\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
> [  +94 ms] Launching lib\main.dart on Chrome in debug mode...
> [  +55 ms] Updating assets
> [ +103 ms] Syncing files to device Chrome...
> [  +65 ms] Generating C:\flutter_projects\disinsection\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
> [  +34 ms] <- reset
> [   +7 ms] c:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe c:\dev\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root c:\dev\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
> C:\Users\maxim\AppData\Local\Temp\flutter_tool.a6b0150e-88cf-11ea-ab0e-74d02b9624ce\app.dill --libraries-spec file:///c:/dev/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\flutter_projects\disinsection\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
> --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root C:\Users\maxim\AppData\Local\Temp\flutter_tools.a6b0150f-88cf-11ea-ab0e-74d02b9624ce --filesystem-scheme
> org-dartlang-app --initialize-from-dill build\cache.dill --platform file:///c:/dev/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
> [  +16 ms] <- compile org-dartlang-app:///web_entrypoint.dart
> [+9179 ms] Syncing files to device Chrome... (completed in 9 291ms, longer than expected)
> [   +1 ms] Synced 20.9MB.
> [   +1 ms] <- accept
> [ +161 ms] [CHROME]:
> [   +5 ms] [CHROME]:DevTools listening on ws://127.0.0.1:60676/devtools/browser/f9a21aea-bf88-4cd7-b19f-b9f26cc88c3a

> C:\flutter_projects\disinsection>flutter doctor -v
> [√] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18362.778], locale ru-RU)
>     • Flutter version 1.17.0-3.2.pre at c:\dev\flutter
>     • Framework revision 2a7bc389f2 (6 days ago), 2020-04-21 20:34:20 -0700
>     • Engine revision 4c8c31f591
>     • Dart version 2.8.0 (build 2.8.0-dev.20.10)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\maxim\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2019.3)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
>     • Flutter plugin version 45.1.2
>     • Dart plugin version 193.6494.35
> 
> [√] VS Code (version 1.39.1)
>     • VS Code at C:\Users\maxim\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.5.1
>

**Comment by VladyslavBondarenko** [comment]
Hi @zeppelin-tt 
so don't you have

```
[+9408 ms] Debug service listening on ws://127.0.0.1:58122/CB5kct3Wfio=

[ +293 ms] Debug service listening on ws://127.0.0.1:58122/CB5kct3Wfio=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
```

in your log after

`[ +5 ms] [CHROME]:DevTools listening on ws://127.0.0.1:60676/devtools/browser/f9a21aea-bf88-4cd7-b19f-b9f26cc88c3a` ?

Can you see any error in the browser console?

**Comment by zeppelin-tt** [comment]
No, I have nothing in the log after.

Here is my error in browser console:

> require.js:1961 Not allowed to load local resource: file:///C:/flutter_projects/project/lib/pages/home/components/header.dart
> req.load @ require.js:1961
> require.js:143 Uncaught Error: Script error for "C:/flutter_projects/project/lib/pages/home/components/header.dart", needed by: packages/disinsection/pages/home/main_page.dart
> http://requirejs.org/docs/errors.html#scripterror
>     at makeError (require.js:168)
>     at HTMLScriptElement.onScriptError (require.js:1738)

The most interesting thing is that just copying the entire code base into a new project helps. Temporarily.

**Comment by yjbanov** [comment]
Does the problem go away if you do `git clean -xdf` in your codebase (assuming you are using git; WARNING: this can undo uncommitted changes)?

**Comment by zeppelin-tt** [comment]
@yjbanov it helps me! Thx!

**Comment by rockingdice** [comment]
Warning: Don't do `git clean -xdf` if you don't know what it is!! It will remove all your files that are not under version control!!
