### ISSUE TITLE
No service of type BuildStateRegistry available in BuildTreeScopeServices.

### ISSUE THREAD

**Issue by jiharal** [flutter/flutter#55777]
![image](https://user-images.githubusercontent.com/21150538/80537707-b15aaf00-89ce-11ea-8a70-3af8ba6dc404.png)

Hi @VladyslavBondarenko.. here!

**Comment by VladyslavBondarenko** [comment]
Hi @jiharal 
could you provide your `flutter doctor -v` and `flutter run --verbose` (or the command that you are using, with `--verbose`)?

**Comment by jiharal** [comment]
`flutter run --verbose`

![image](https://user-images.githubusercontent.com/21150538/80538505-0fd45d00-89d0-11ea-8da9-850f83cbc55b.png)

**Comment by jiharal** [comment]
`flutter run --verbose`
![image](https://user-images.githubusercontent.com/21150538/80542795-e4ee0700-89d7-11ea-83d5-cdb1a5ca22b4.png)

**Comment by TahaTesser** [comment]
Hi @jiharal 
Please checkout this possible [solution](https://stackoverflow.com/a/54962965)
Make sue you have not modified package and `manifest.xml` 
Thank you

**Comment by jiharal** [comment]
this issue already fixed. after i upgrade my flutter and clean my cahce usign comman `flutter clean`
