### ISSUE TITLE
Update the `flutter create` pubspec.yaml template to use the google_fonts package

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#55776]
This section: https://github.com/flutter/flutter/blob/3c37db0520793a513eda481c3e020dbe9bd68d1c/packages/flutter_tools/templates/app/pubspec.yaml.tmpl#L74

should be modified to show how to more easily include fonts with the google_fonts package. It should still link to https://flutter.dev/docs/cookbook/design/fonts for advanced cases.

**Comment by bharat-1809** [comment]
Can I work on this issue?

**Comment by clocksmith** [comment]
@bharat-1809  Yes!

**Comment by bharat-1809** [comment]
> @bharat-1809 Yes!

Thanks. I'll start working on it

**Comment by bharat-1809** [comment]
Hi @clocksmith, I have opened a PR for this issue. [Please have a look.](https://github.com/flutter/flutter/pull/72981)

**Comment by stuartmorgan** [comment]
Closing given that the PR was not accepted.
