### ISSUE TITLE
how to use media MediaQueryData with padding

### ISSUE THREAD

**Issue by mariamalbarghouti** [flutter/flutter#55796]
how to add padding for a specific edge using media query
 Padding(
              padding: EdgeInsets.only(
                bottom:8.0,
                ),
),

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
