### ISSUE TITLE
where should i type constan variable file?

### ISSUE THREAD

**Issue by mariamalbarghouti** [flutter/flutter#55798]
=>wideget file
=>ui
=>model
=>utilities
or where should i save this file?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
