### ISSUE TITLE
flutter web using data_transformer.dart zlib

### ISSUE THREAD

**Issue by flowcharterappowner** [flutter/flutter#55804]
Error: Unsupported operation: _newZLibDeflateFilter

**Comment by flowcharterappowner** [comment]
Occurs when creating a pdf using the pdf package.
You start by creating a document object:

pdfDoc = pdfw.Document(
        theme: theme,
        deflate: zlib.encode
    );

etc.

**Comment by VladyslavBondarenko** [comment]
Hi @flowcharterappowner 
could you provide your `flutter doctor -v`, `flutter run --verbose` and a complete minimal code sample to reproduce the problem?

**Comment by TahaTesser** [comment]
Hi @flowcharterappowner 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by lsegal** [comment]
I believe you can reproduce this by running any sort of deflation operation from the web platform. Is zlib still not supported on Flutter web?
