### ISSUE TITLE
Animations run slowly and drop frames in debug mode

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#5581]
Talking with @Hixie I've heard that there are N squared algorithms validating layout in debug mode. It would be nice if animations played smoothly (-er) in debug mode.
- [] speedup the algorithms
- [] make some of the expensive checks optional
- [] some other idea

**Comment by johnmccutchan** [comment]
@HansMuller @sethladd

**Comment by eseidelGoogle** [comment]
This may be in part caused by https://github.com/flutter/flutter/issues/6135 at least if you're testing on emulators/simulators.

**Comment by Hixie** [comment]
This is way better than it was back when this bug was filed.
