### ISSUE TITLE
Module 'google_maps_flutter' not found

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#55814]
## Steps to Reproduce

1. On Xcode, select Product > Archive
2. Update the files as follows (private project): 
Pubspec.yaml: https://gist.github.com/andesappal/5d6141d89e2b73a4456e101c83abca0b
(This project was done by one other developer, so please, bear with me. There are many deps that aren't necessary, which are gradually being removed. But for now, I need to build an archive on Xcode and release the app on TestFlight as it is)

**Expected results:** 
I expected to produce a build archive

**Actual results:** 
![image](https://user-images.githubusercontent.com/54340176/80445127-e3461580-88e9-11ea-982e-7c3245838aec.png)

  **Logs**
`flutter run --verbose`: https://gist.github.com/andesappal/a70a664fd87105fe13fcc9020a836753

Dart analysis presents 632 hints, and 0 errors

`flutter doctor -v`: https://gist.github.com/andesappal/b724e0dee312708f95b4c593b54d0e9a

**Comment by VladyslavBondarenko** [comment]
Hi @andesappal 
isn't https://github.com/flutter/flutter/issues/43986#issuecomment-573171119 your case?
have you followed https://flutter.dev/docs/deployment/ios#create-a-build-archive?

**Comment by andesappal** [comment]
Hi @VladyslavBondarenko. Apparently this solved the issue https://github.com/flutter/flutter/issues/50568#issuecomment-584996079
Thanks for your help!
