### ISSUE TITLE
	Error creating project 				Oops; flutter has exited unexpectedly. 				Crash report written to C:\Users\Kathirvel\FlutterProjects\flutter_03.log; 				please let us know at https://github.com/flutter/flutter/issues.

### ISSUE THREAD

**Issue by kathir-6tz** [flutter/flutter#55824]
[flutter_03.log](https://github.com/flutter/flutter/files/4543880/flutter_03.log)
please help

**Comment by TahaTesser** [comment]
Hi @kathir-6tz 
Looks like you've very old version of Flutter installed
Please execute `flutter upgrade --force` to latest stable and execute `flutter doctor -v`
and try creating new project. 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
