### ISSUE TITLE
there is a problem with loading our login plage. 

### ISSUE THREAD

**Issue by prabuddhafernando** [flutter/flutter#55825]
When the exception was thrown, this was the stack: 
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3867:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1168:14)
#4      _SpinKitPouringHourglassState._repaint (package:flutter_spinkit/src/pouring_hour_glass.dart:76:27)
#5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124:19)
#6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:788:5)
...
The AnimationController notifying listeners was: AnimationController#d0999(▶ 0.420)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

this is happened after loading UI. but UI is perfectly loading.

**Comment by alexpavelm** [comment]
A TextField widget or the Animation Controller might cause that problem. Have you disposed all controllers in dispose?

**Comment by TahaTesser** [comment]
Hi @prabuddhafernando 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @prabuddhafernando 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
