### ISSUE TITLE
My screen goes black after I click back button at my emulator (#13251)

### ISSUE THREAD

**Issue by Azkuu** [flutter/flutter#55837]
**here is my error  debug console output**

D/FlutterActivity(12477): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(12477): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(12477): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(12477): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(12477): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8d8ad9d
D/FlutterActivityAndFragmentDelegate(12477): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation(12477): eglMakeCurrent: 0x9f294fc0: ver 3 0 (tinfo 0x9d8e1de0)

Here is my 'flutter doctor -v' result

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.10586], locale en-MY)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\L'Ordineatur\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\L'Ordineatur\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by TahaTesser** [comment]
hI @Azkuu 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Azkuu** [comment]
### here  is my code


> main.dart

`void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      builder: (ctx) => Products(),
      child: MaterialApp(
          title: 'MyShop',
          theme: ThemeData(
            primarySwatch: Colors.purple,
            accentColor: Colors.deepOrange,
            fontFamily: 'Lato',
          ),
          home: ProductsOverviewScreen(),
          routes: {
            ProductDetailsScreen.routeName: (ctx) => ProductDetailsScreen(),
          }),
    );
  }
}`

> products_detail_screem.dart 

`class ProductDetailsScreen extends StatelessWidget {
  static const routeName = '/product-detail';

  @override
  Widget build(BuildContext context) {
    final productId =
        ModalRoute.of(context).settings.arguments as String; // string is the id
    final loadedProduct = Provider.of<Products>(context)
        .items
        .firstWhere((prod) => prod.id == productId);
    return Scaffold(
      appBar: AppBar(
        title: Text(loadedProduct.title),
      ),
    );
  }
}

> products.dart 

`class Products with ChangeNotifier {
  List<Product> _items = [
    Product(
      id: 'p1',
      title: 'Red Shirt',
      description: 'A red shirt - it is pretty red!',
      price: 29.99,
      imageUrl:
          'https://cdn.pixabay.com/photo/2016/10/02/22/17/red-t-shirt-1710578_1280.jpg',
    ), ];

  List<Product> get items {
    return [..._items];
  }

  void addProduct() {
    notifyListeners();
  }
}
`

### here is --verbose

[  +42 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +108 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long
--tags
[  +65 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.9-0-gf139b1100
[  +26 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +2 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +405 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +282 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +221 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +24 ms] Exit code 0 from:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86 transport_id:3
[  +39 ms] C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s
emulator-5554 shell getprop
[ +108 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +478 ms] Generating
C:\Users\L'Ordineatur\kucing\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRe
gistrant.java
[  +81 ms] ro.hardware = ranchu
[  +88 ms] Using hardware rendering with device Android SDK built for x86. If you get
graphics
           artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +54 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +19 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
C:\Users\L'Ordineatur\kucing\build\app\outputs\apk\app.apk AndroidManifest.xml
[ +318 ms] Exit code 0 from:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
C:\Users\L'Ordineatur\kucing\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.kucing" (Raw: "com.example.kucing")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="kucing" (Raw: "kucing")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFa
                 ctory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.kucing.MainActivity" (Raw:
                   "com.example.kucing.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw:
                       "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +18 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell -x logcat -v time -t 1
[  +54 ms] Exit code 0 from:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           04-28 12:27:13.553 I/boot-pipe( 1413): done populating /dev/random
[   +9 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +2 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
logcat -v time -T 04-28 12:27:13.553
[  +71 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as
           C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +38 ms] Building APK
[  +30 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[  +25 ms] Using gradle from C:\Users\L'Ordineatur\kucing\android\gradlew.bat.
[  +28 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +213 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +6 ms] executing: [C:\Users\L'Ordineatur\kucing\android\]
C:\Users\L'Ordineatur\kucing\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\L'Ordineatur\kucing\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+4155 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[ +146 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +5 ms] > Task :app:preBuild UP-TO-DATE
[  +12 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +39 ms] > Task :app:compileDebugAidl NO-SOURCE
[  +20 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +7 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +621 ms] > Task :app:copyFlutterAssetsDebug
[ +134 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +41 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +6 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +12 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +49 ms] > Task :app:processDebugManifest UP-TO-DATE
[  +54 ms] > Task :app:processDebugResources UP-TO-DATE
[  +22 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +8 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +92 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +5 ms] > Task :app:compileDebugSources UP-TO-DATE
[ +290 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +75 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +106 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +53 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +16 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +10 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +9 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[  +26 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +7 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] Compatible side by side NDK version was not found.
[   +1 ms] > Task :app:packageDebug UP-TO-DATE
[   +1 ms] > Task :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 5s
[        ] 30 actionable tasks: 3 executed, 27 up-to-date
[ +366 ms] Running Gradle task 'assembleDebug'... (completed in 6.7s)
[ +172 ms] calculateSha: LocalDirectory:
'C:\Users\L'Ordineatur\kucing\build\app\outputs\apk'/app.apk
[ +102 ms] calculateSha: reading file took 99us
[ +707 ms] calculateSha: computing sha took 706us
[  +23 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +7 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
C:\Users\L'Ordineatur\kucing\build\app\outputs\apk\app.apk AndroidManifest.xml
[ +217 ms] Exit code 0 from:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
C:\Users\L'Ordineatur\kucing\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.kucing" (Raw: "com.example.kucing")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="kucing" (Raw: "kucing")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFa
                 ctory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.kucing.MainActivity" (Raw:
                   "com.example.kucing.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw:
                       "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +11 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +2 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell am force-stop com.example.kucing
[ +212 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell pm list packages com.example.kucing
[+1960 ms] package:com.example.kucing
[   +7 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell cat /data/local/tmp/sky.com.example.kucing.sha1
[  +99 ms] 74f3ac504954b934b3fc1d0f893264998ec38df9
[   +4 ms] Latest build already installed.
[   +1 ms] Android SDK built for x86 startApp
[   +6 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode
true --ez verify-entry-points true com.example.kucing/com.example.kucing.MainActivity
[ +187 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.example.kucing/.MainActivity (has extras) }
[   +3 ms] Waiting for observatory port to be available...
[ +863 ms] D/FlutterActivity(14036): Using the launch theme as normal theme.
[  +16 ms] D/FlutterActivityAndFragmentDelegate(14036): Setting up FlutterEngine.
[   +1 ms] D/FlutterActivityAndFragmentDelegate(14036): No preferred FlutterEngine was
provided. Creating a new FlutterEngine for this FlutterFragment.
[ +724 ms] D/FlutterActivityAndFragmentDelegate(14036): Attaching FlutterEngine to the
Activity that owns this Fragment.
[ +293 ms] D/FlutterView(14036): Attaching to a FlutterEngine:
io.flutter.embedding.engine.FlutterEngine@8d8ad9d
[  +92 ms] D/FlutterActivityAndFragmentDelegate(14036): Executing Dart entrypoint: main,
and sending initial route: /
[  +32 ms] Observatory URL on device: http://127.0.0.1:41564/2NTAPzCt1C0=/
[  +14 ms] executing:
C:\Users\L'Ordineatur\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
forward tcp:0 tcp:41564
[ +136 ms] 60258
[  +10 ms] Forwarded host port 60258 to device port 41564 for Observatory
[  +26 ms] Connecting to service protocol: http://127.0.0.1:60258/2NTAPzCt1C0=/
[+1560 ms] Successfully connected to service protocol: http://127.0.0.1:60258/2NTAPzCt1C0=/
[  +36 ms] Sending to VM service: getVM({})
[  +95 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: Virtual CPU,
operatingSystem: android, targetCPU: ia32, version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100)
on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 14036, startTime:
158...
[ +137 ms] Sending to VM service: getIsolate({isolateId: isolates/3514794450241475})
[  +23 ms] Sending to VM service: _flutter.listViews({})
[  +62 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id:
_flutterView/0x9c983390, isolate: {type: @Isolate, fixedId: true, id:
isolates/3514794450241475, name: main.dart$main-3514794450241475, number:
3514794450241475}}]}
[  +15 ms] DevFS: Creating new filesystem on the device (null)
[   +2 ms] Sending to VM service: _createDevFS({fsName: kucing})
[ +123 ms] Result: {type: Isolate, id: isolates/3514794450241475, name: main, number:
3514794450241475, _originNumber: 3514794450241475, startTime: 1588076871586, _heaps: {new:
{type: HeapSpace, name: new, vmName: Scavenger, collections: 2,
avgCollectionPeriodMillis...
[  +93 ms] Result: {type: FileSystem, name: kucing, uri:
file:///data/user/0/com.example.kucing/code_cache/kucingXBWDUM/kucing/}
[  +18 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.kucing/code_cache/kucingXBWDUM/kucing/)
[  +21 ms] Updating assets
[+1240 ms] Syncing files to device Android SDK built for x86...
[   +5 ms] Scanning asset files
[  +12 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[  +31 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\L'ORDI~1\AppData\Local\Temp\flutter_tool.a47d950d-894b-11ea-a235-e02a823090e0\app.
dill --packages C:\Users\L'Ordineatur\kucing\.packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initialize
rs,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
[  +13 ms] <- compile package:kucing/main.dart
[   +4 ms] D/EGL_emulation(14036): eglMakeCurrent: 0xa7130120: ver 3 0 (tinfo 0x9d8e95e0)
[+17492 ms] Updating files
[ +423 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Android SDK built for x86... (completed in 17,986ms,
longer than expected)
[   +1 ms] Synced 1.1MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +7 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id:
_flutterView/0x9c983390, isolate: {type: @Isolate, fixedId: true, id:
isolates/3514794450241475, name: main.dart$main-3514794450241475, number:r:
3514794450241475}}]}
[   +3 ms] <- accept
[        ] Connected to _flutterView/0x9c983390.

**Comment by Azkuu** [comment]
I fix the provider and it works fine. thank you bro
