### ISSUE TITLE
Making Https request from the flutter app

### ISSUE THREAD

**Issue by harishshet222** [flutter/flutter#55848]
I have my API's deployed in server and I can make either of HTTP, https requests to hit the APIs.
I've tested apis by making http requests. like  
```
String loginURL="https://<ip>/login/auth";
http.Response response = await http.post(loginURL,
          headers: {"Content-type": "application/json"},
          body: json.encode({"username": username, "password": password}));
```

If I done the http request I am getting the response with success code as 200

But when I tried to hit the same API which is deployed with https. I am getting the exception in the server not receiving any response. How to make a https request?

**Comment by TahaTesser** [comment]
Hi @harishshet222 
Looking at official [example](https://flutter.dev/docs/cookbook/networking/fetch-data), you don't need any extra step to call https. 
Make https works in your testing from server, using postman or similar tool

If the the persist, please raise your `http` issue, on their [GitHub](https://github.com/dart-lang/sdk/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
