### ISSUE TITLE
Motion Blur Animation When Scrolling, Rotating, Scaling Widgets

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#55842]
I have been using Google Flutter for a recent project. And was wondering if we can apply motion blur in the widget animation. It just makes animations more realistic and soothing. I couldn't find any resources available regarding this. Like animations done in [Framer](https://www.framer.com/).

Do you guys have suggestions on how to achieve this?

**Comment by TahaTesser** [comment]
Hi @SahajRana 
Do you think you need this motion blur in a listview r when you're scrolling?
Maybe it could be using [ScrollPhysics](https://api.flutter.dev/flutter/widgets/ScrollPhysics-class.html) api
Thank you

**Comment by SahajRana** [comment]
Hi @TahaTesser, thanks for the reply. I'm hoping to use it for simple animations as well like rotation, move, scale, etc. Is there any resource for it. CodePen has some example for it [Codepen1](https://codepen.io/igcorreia/pen/pJvOpL),  [Codepen2](https://codepen.io/damianmuti/pen/MvYPPa)

**Comment by p4-k4** [comment]
I'm surprised to have really only found @SahajRana's post of this subject, with pretty much no attention.

Motion blurred animations can give us creative freedom whilst also being able to provide a drastically enhanced user experience, in particular with fast moving animations.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Figure-Animation2.gif/400px-Figure-Animation2.gif)

My guess is that implementation needs to happen on the Engine itself (whether or not it's even possible currently) but then they might as well start building out a 2.5D camera while they're at it. That way it'd be possible for physics based lighting (thus shadows) and camera control. If we can manipulate exposure, we can manipulate shutter angle for motion blur or aperture for depth of field etc but now we're heading into Unreal Engine and Unity territory.

Might be a bit optimistic at this stage.

**Comment by ercantomac** [comment]
This subject needs more attention. We definitely need it. I think it could be done via shaders.

**Comment by jonahwilliams** [comment]
2D motion blur effects can be added via the existing gaussian blur shader, just blur in a single direction and rotate/transform the blur to match the vector of movement.
