### ISSUE TITLE
Take screenshot from io.flutter.embedding.android.flutterview 

### ISSUE THREAD

**Issue by AlekseyMak** [flutter/flutter#55854]
Hello, 

I want to programmatically take screenshots from my FlutterView in Android.

When it was **io.flutter.view.FlutterView** I just use `getBitmap()` 
But how can I make screenshot from  **io.flutter.embedding.android.FlutterView** ?

I tried following code but this does not work:

 ```
private fun getBitmapFromNewEmbeddedFlutterView(flutterView: io.flutter.embedding.android.FlutterView): Bitmap {
      val bitmap = Bitmap.createBitmap(
              flutterView.width,
              flutterView.height,
              Bitmap.Config.ARGB_8888
      )
      val canvas = Canvas(bitmap)
      flutterView.layout(
              0,
              0,
              flutterView.measuredWidth,
              flutterView.measuredHeight
      )
      flutterView.draw(canvas)
      return bitmap
  }
```

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by walterFeng** [comment]
hi @AlekseyMak，Have you found a solution?
