### ISSUE TITLE
Test StateError incorrect  error message 

### ISSUE THREAD

**Issue by kennethj** [flutter/flutter#55858]
https://github.com/flutter/flutter/blob/ffcf1db3ca74563910986a4a2f3675728d17c5ca/packages/flutter_test/lib/src/finders.dart#L308-L310

This error reads: 
> Semantics are not enabled. Make sure to call tester.enableSemantics() before using  this finder, and call dispose on its return value after.

However `tester.enableSemantics()` does not appear to exist. It appears to be referring to `tester.ensureSemantics()` and sure read:
> Semantics are not enabled. Make sure to call **tester.ensureSemantics()** before using  this finder, and call dispose on its return value after.

**Comment by TahaTesser** [comment]
Hi @kennethj 
Thank you for noticing this, [WidgetTester](https://api.flutter.dev/flutter/flutter_test/WidgetTester-class.html) definitely doesn't have `enableSemantics()`
