### ISSUE TITLE
AnimatedList and Listview.builder are reiterating over indexes

### ISSUE THREAD

**Issue by vitthal-inani** [flutter/flutter#55852]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
![Screenshot (28)](https://user-images.githubusercontent.com/44166227/80496761-4043d900-8987-11ea-9edc-59daf7a5b16c.png)

**Expected results:** 
It should only iterate once
**Actual results:** 
It iterates twice hence when deleting it gives error
<details>
  <summary>Logs</summary>

```
```

   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyApp.abc - lib\main.dart:7:7 - must_be_immutable
```
```

[√] Flutter (Channel master, 1.18.0-9.0.pre.38, on Microsoft Windows [Version 10.0.18363.778], locale en-IN)
    • Flutter version 1.18.0-9.0.pre.38 at C:\Extras\flutter
    • Framework revision ffcf1db3ca (13 hours ago), 2020-04-27 17:41:42 -0700
    • Engine revision 4bcfae82c7
    • Dart version 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Vitthal Inani\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\Vitthal Inani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```
```

</details>

**Comment by jonahwilliams** [comment]
Flutter does not guarantee `Widget.build` will be called the minimum number of times possible. You should structure your application in a way that assumes build will be called on every frame - anything less is an optimization.
