### ISSUE TITLE
MethodChannel doesn't register methodCallHandler on iOS

### ISSUE THREAD

**Issue by SunFoxx** [flutter/flutter#55860]
So, I having a bunch of plugins in my project, and one of them is self-written. I am trying to communicate with it via `MethodChannel` and it is working fine on android, and also successfully performing `invokeMethod` on both platforms. However, when it comes to performing `invokeMethod` from swift code to pass data into dart, Flutter side seems not to recognize previously registered with `setMethodCallHandler` handler from inside of it's `BinaryMessenger`. So, when I am successfully registering methodCallHandler for my plugin, `_DefaultBinaryMessenger` inside the `MethodChannel` having this static list of registered message handlers:
```
[flutter/system, flutter/lifecycle, flutter/keyevent, flutter/navigation, plugins.flutter.io/firebase_messaging, receive_sharing_intent/events-media, receive_sharing_intent/events-text, plugins.flutter.io/connectivity_status, flutter_voxeet, flutter_voxeet/event]
```
but when it is receiving binary message from native side of this particular plugin (flutter_voxeet) and trying to decode it and pass into the proper handler, it turns out that it is trying to reference this list of handlers
```
[flutter/system, flutter/lifecycle, flutter/keyevent, flutter/navigation, vn.hunghd/downloader_background]
```

it is different and not having a proper handler despite that `MethodChannel` using the only instance of `_DefaultBinaryMessenger` by default with a single static list of handlers. Can somebody explain what possibly can cause this behavior? Unfortunately, I can't share my code because of NDA, but swift initialization is pretty simple and doesn't have anything special
```
public static func register(with registrar: FlutterPluginRegistrar) {
        var channel: FlutterMethodChannel? = FlutterMethodChannel(
            name: "flutter_voxeet",
            binaryMessenger: registrar.messenger()
        )
        
        let instance = SwiftFlutterVoxeetPlugin()
        registrar.addMethodCallDelegate(instance, channel: channel!)
        
        let viewFactory = VoxeetViewFactory();
        registrar.register(viewFactory, withId: "VoxeetView")
    }
```
**Expected results:** 
I am expecting that messages from swift side are successfully passing into the proper handler on flutter's side

**Actual results:** 
I am receiving messages from swift and flutter recognizes them, but I can't handle them. Missing handler that has been registered previously is the only problem

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale ru-RU)
    • Flutter version 1.12.13+hotfix.9 at /Users/sunfoxx/Development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sunfoxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6494.35

```

</details>

**Comment by iapicca** [comment]
Hi @SunFoxx 
there is no need to share your production code,
but it would be useful if you could share
a reproducible minimal code sample
Thank you

**Comment by SunFoxx** [comment]
Resolved. The problem was in non-proper plugin initialization for `flutter_downloader` in `AppDelegate`
