### ISSUE TITLE
Error when call  a map item in flutter.

### ISSUE THREAD

**Issue by AllenRodger** [flutter/flutter#55868]
I can guarantee that the variable is a non-null string, but when I call it in the constructor, the program points it to be null
see the code:

-----file 1 : -----
import 'dart:core';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:treinos/page1.dart';
import 'package:path_provider/path_provider.dart';

Future<File> getFile() async {
  final directory = await getApplicationDocumentsDirectory();
  return File("${directory.path}/data.json");
}

Future<File> saveData() async {
  String data = json.encode(Lista);
  final file = await getFile();
  return file.writeAsString(data);
}

Future<String> readData() async {
  try{
    final file = await getFile();
    return file.readAsString();
  } catch(e){
    return null;
  }
}

void main(){
  runApp(MaterialApp(
      initialRoute: '/',
    routes: {'/':(context)=>Dashboard(),
              '/second': (context)=>Page1()},
  ));
}

class Dashboard extends StatefulWidget {

  @override
  _DashboardState createState() => _DashboardState();
}

class _DashboardState extends State<Dashboard> {

  createAlertDialog(BuildContext, context) {
    return showDialog(context: context, builder: (context) {
      return AlertDialog(
          title: Text('Produzido por:'),
          content: ListTile(leading: Icon(Icons.lightbulb_outline),
              title: Text('Allen Rodger')),
          actions: <Widget>[
            MaterialButton(elevation: 5.0,
                child: Text('Voltar'),
                onPressed: () {
                  Navigator.of(context).pop();
                })
          ]);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(leading: FlatButton(
            child: Icon(Icons.directions_run, color: Colors.white),
            onPressed: () {
              createAlertDialog(context, context);
            }),
            title: Text('Treinoz', style: TextStyle(color: Colors.white),),
            backgroundColor: Colors.deepPurple,
            centerTitle: true),
        floatingActionButton: FloatingActionButton(
            backgroundColor: Colors.deepPurpleAccent,
            child: Icon(Icons.add, color: Colors.white,),
            onPressed: () {
              Navigator.pushNamed(
                  context, '/second');
            }),
        body: ListView.builder(
            itemCount: Lista.length,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                leading: Icon(Icons.fitness_center, color: Colors.black,),
                title: Text(Lista[index]['title']),
                subtitle: Text(Lista[index]['informacao'])
              );
            }
        )
    );
  }
}

-----file2:-----
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:treinos/main.dart';
List<dynamic> Lista = [];
class Page1 extends StatelessWidget {
  final controladortreino = TextEditingController();
  final controladorinformacao = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(backgroundColor: Colors.white,
        appBar: AppBar(centerTitle: true, title: Text('Criar novos treinos:',style: TextStyle(color:Colors.white),),backgroundColor: Colors.deepPurple,),
        body:
        Column(
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Center(child:
              TextField(controller: controladortreino,decoration: InputDecoration(labelText: 'Novo Treino',labelStyle: TextStyle(color: Colors.black,fontSize: 30)),),),
            ),
            Center(child:
            TextField(controller: controladorinformacao,decoration: InputDecoration(labelText: 'Descrição',labelStyle: TextStyle(color: Colors.black,fontSize: 30)),)),
            RaisedButton(child: Text('CONFIRMAR'), onPressed: (){
              Lista.add({'title': controladortreino.text,'descricao': controladorinformacao.text});
              print('Lista[0][\'title\']:${Lista[0]['title']}');
              saveData();
              Navigator.pop(context);
            },)

          ],)

    );
  }
}
----error---
 Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building:
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:285:10)
#3      _DashboardState.build.<anonymous closure> (package:treinos/main.dart:84:27)
#4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#5      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#6      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:139:29)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
