### ISSUE TITLE
ViewPostIme pointer 0 when tap on screen

### ISSUE THREAD

**Issue by fabiojansenbr** [flutter/flutter#55861]
After upgrade my flutter version to 1.12.13+hotfix.9 , if im using physical device (Samsung a50), every time i touch the screen, im getting this messages on terminal:

D/ViewRootImpl@38eee14[MainActivity]( 7994): ViewPostIme pointer 0

followed by

D/ViewRootImpl@38eee14[MainActivity]( 7994): ViewPostIme pointer 1

Is this an error? bug? how to hide this?

**Comment by iapicca** [comment]
Hi @fabiojansenbr 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by fabiojansenbr** [comment]
Hi, this is flutter doctor -v

[√] Flutter (Channel unknown, v1.12.13+hotfix.9, on Microsoft Windows [versÃ£o 10.0.18363.815], locale pt-BR)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\fabio\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\fabio\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • SM A505GT • RQ8M60E1BYF • android-arm64 • Android 9 (API 28)

• No issues found!

This is the result of flutter run --verbose

[https://gist.github.com/fabiojansenbr/ab07ea47808d2677858d3280edc70c1a](url)

And this is the pubspec.yaml

[https://gist.github.com/fabiojansenbr/cba950fab749c239d8cfa1b50d2e4fa6](url)

I created a new clean project, as the messages occur in any project I create.

These messages are very disruptive during the execution of the application because it ends up hiding important console messages.

**Comment by iapicca** [comment]
Thank you @fabiojansenbr

**Comment by dbof10** [comment]
same issue, some of the views are not clickable

**Comment by ened** [comment]
@iapicca 

This issue can probably be closed, as some phones (in my case a Note 9) show this log message whenever you tap anywhere _in any app_ that is currently on screen.

Tested with "adb logcat | grep ViewPostIme".

**Comment by gauravsbagul** [comment]
I am having same issue, whenever I tap on screen 
`D/ViewRootImpl@b7ca724[MainActivity](29938): ViewPostIme pointer 0
D/ViewRootImpl@b7ca724[MainActivity](29938): ViewPostIme pointer 1`
 these two lines get printed, and my onTap function doesn't work, I tries InkWel, RaisedButton, GestureDetector all of these.

**Comment by ened** [comment]
onTap not working may be a case of a missing `onPressed` or `onTap` function handler, for example.

**Comment by gauravsbagul** [comment]
No thats not the case.. I have added onTap function handler, but its still not working.

**Comment by ened** [comment]
Please open a separate issue with reproduction case; please also check with Stackoverflow first.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Infinity97** [comment]
But is there a way to hide that message. It is just basically crowding the console. 
Please do mention if there is something we can do to hide it. 
I tried this stackoverflow answer did not work for me :-  [hide ViewPostIme pointer 0](https://stackoverflow.com/questions/56677628/how-do-i-hide-this-message-in-the-flutter-console-viewpostime-pointer-0)

Any help would be appreciated. Thanks

**Comment by baoxu** [comment]
> 我遇到同样的问题，每当我在屏幕上轻按
> `D/ViewRootImpl@b7ca724[MainActivity](29938): ViewPostIme pointer 0 D/ViewRootImpl@b7ca724[MainActivity](29938): ViewPostIme pointer 1`
> 这两行时，就会打印出来，而我的onTap函数不起作用，我会尝试使用InkWel，RaisedButton，GestureDetector来处理所有这些问题。

I had the same problem，these two lines get printed, and my onTap function doesn't work

**Comment by iapicca** [comment]
@baoxu @Infinity97 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by baoxu** [comment]
> @baoxu @Infinity97
> 
> > Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> > All system setups can be slightly different, so it's always better to open new issues and reference related issues.

[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on macOS 11.2.2 20D80 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-17.8.pre at /Users/baoxu/environment/flutter
    • Framework revision 044f2cf560 (2 weeks ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/baoxu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/baoxu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • SM G9550 (mobile)          • 98899a36504851524a                   • android-arm64 • Android 9 (API 28)
    • iPhone 12 Pro Max (mobile) • 89404628-9ECC-4FEC-BEB9-B4A29EFA755F • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!
Process finished with exit code 0


……
D/ViewRootImpl@1145213[MainActivity]( 5300): ViewPostIme pointer 0
D/ViewRootImpl@1145213[MainActivity]( 5300): ViewPostIme pointer 1
D/ViewRootImpl@1145213[MainActivity]( 5300): ViewPostIme pointer 0
D/ViewRootImpl@1145213[MainActivity]( 5300): ViewPostIme pointer 1
……

onTap function doesn't work

**Comment by iapicca** [comment]
> > @baoxu @Infinity97
> > > Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> > > All system setups can be slightly different, so it's always better to open new issues and reference related issues.
> 
> [✓] Flutter (Channel beta, 1.26.0-17.8.pre, on macOS 11.2.2 20D80 darwin-x64, locale zh-Hans-CN)
> • Flutter version 1.26.0-17.8.pre at /Users/baoxu/environment/flutter
> • Framework revision [044f2cf](https://github.com/flutter/flutter/commit/044f2cf5607a26f8818dab0f766400e85c52bdff) (2 weeks ago), 2021-02-24 13:02:05 -0800
> • Engine revision 042c82b02c
> • Dart version 2.12.0 (build 2.12.0-259.16.beta)
> • Pub download mirror https://pub.flutter-io.cn
> • Flutter download mirror https://storage.flutter-io.cn
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at /Users/baoxu/Library/Android/sdk
> • Platform android-29, build-tools 29.0.3
> • ANDROID_HOME = /Users/baoxu/Library/Android/sdk
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 12.4, Build version 12D4e
> • CocoaPods version 1.10.1
> 
> [✓] Android Studio (version 4.1)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/9212-flutter
> • Dart plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/6351-dart
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
> • IntelliJ at /Applications/IntelliJ IDEA.app
> • Flutter plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/9212-flutter
> • Dart plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] Connected device (2 available)
> • SM G9550 (mobile) • 98899a36504851524a • android-arm64 • Android 9 (API 28)
> • iPhone 12 Pro Max (mobile) • 89404628-9ECC-4FEC-BEB9-B4A29EFA755F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
> 
> • No issues found!
> Process finished with exit code 0
> 
> ……
> D/ViewRootImpl@1145213[MainActivity](5300): ViewPostIme pointer 0
> D/ViewRootImpl@1145213[MainActivity](5300): ViewPostIme pointer 1
> D/ViewRootImpl@1145213[MainActivity](5300): ViewPostIme pointer 0
> D/ViewRootImpl@1145213[MainActivity](5300): ViewPostIme pointer 1
> ……
> 
> onTap function doesn't work

@baoxu 
as mentioned [here](https://github.com/flutter/flutter/issues/55861#issuecomment-796664993) and [here](https://github.com/flutter/flutter/issues/55861#issuecomment-662421639)
### please file a new issue
