### ISSUE TITLE
license dialog is empty for flutter gallery

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#5587]
For the play store version of flutter gallery, the 'view licenses' dialog is empty. It opens but does not have any licenses listed.

@Hixie

**Comment by Hixie** [comment]
How is it built? Is the flutter tool invoked? Are there pub packages
around? What is the difference in how it is built? Does it with if you just
do `flutter build; flutter install`?

**Comment by eseidelGoogle** [comment]
The version built from the gallery is using Google's internal build system.  @tvolkert or @cbracken would know more.  Likely we just need to expand our flutter support in those internal build rules to include the LICENSE support.  We may wish to move this to the internal bug tracker.

**Comment by devoncarew** [comment]
Will close in favor of the internal bug tracker.

**Comment by eseidelGoogle** [comment]
Internal bug id is 31073633 for anyone playing along at home.
