### ISSUE TITLE
Flutter iOS project crashes on startup on physical device (works fine on simulator)

### ISSUE THREAD

**Issue by mdsaddam** [flutter/flutter#55883]
Created a new flutter project, followed official website 
https://flutter.dev/docs/get-started/install/macos

Project is working fine on iOS simulator but crashes on start on physical device.
Using Apple Developer account (Personal Team), not registered with Apple Developer Program.

Running from xcode shows following error message
`Thread 1: signal SIGABRT`

```
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/F009224C-7635-41F9-B6B6-FF3676451CA7/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/F009224C-7635-41F9-B6B6-FF3676451CA7/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/F009224C-7635-41F9-B6B6-FF3676451CA7/Runner.app/Frameworks/Flutter.framework/Flutter'

Message from debugger: Terminated due to signal 6

```

**Comment by aseef17** [comment]
This might be related to [#40998](https://github.com/flutter/flutter/issues/40998)

**Comment by mdsaddam** [comment]
@aseef17 It's a different issue (it's not similar to #40998)

First of all it's a new project there are no third party plugins integrated.
It's running on simulator only issue is running it on physical device.

Trying it on iPhone7, iOS 13.3

**Comment by iapicca** [comment]
Hi @mdsaddam 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` (on physical device)
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by aseef17** [comment]
> @aseef17 It's a different issue (it's not similar to #40998)
> 
> First of all it's a new project there are no third party plugins integrated.
> It's running on simulator only issue is running it on physical device.
> 
> Trying it on iPhone7, iOS 13.3

@mdsaddam Can you try upgrading to iOS 13.4 and try running the application?
There was an apple bug introduced in iOS 13.3.1, which you read about [Here](https://github.com/flutter/flutter/issues/49504#issuecomment-592767041)

If that doesn't fix the issue, if you can provide the code that is causing the crash, will be helpful to understand what's going wrong

**Comment by mdsaddam** [comment]
I updated iOS to 13.4.1 on iPhone 7 (physical device). Now it's working fine.

Now my concern is whether the release build will work on iOS 13.3 or not?

Btw thanks for your help guys.

**Comment by aseef17** [comment]
@mdsaddam 
If you’ve already distributed the application, it shouldn’t affect your customers. Neither will the new builds cause any problems on older iOS versions when you distribute it. 

Happy to help.
You can now go ahead and close the issue
