### ISSUE TITLE
Engine autoroller rolls to an old commit

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#55893]
With this autoroller PR https://github.com/flutter/flutter/pull/55888, there are the following problems:

1. The PR was opened 4/28/20, while the commit was authored 4/24/20
1. The description says it is rolling to 0c35a3417da7, while the actual diff in the commit is rolling to 4bcfae82c7c18460c1558cea52c993ebe4439a03 (which is the actual current upstream value)

**Comment by rmistry** [comment]
Looks like borenet@'s experiments were reverted a while back but weird that the autoroller still used a commit from back then. I'll try blowing away the checkout to see if it helps.

**Comment by rmistry** [comment]
How does https://github.com/flutter/flutter/pull/55898 look?

**Comment by christopherfujino** [comment]
> How does #55898 look?

That looks good to me

**Comment by rmistry** [comment]
Last few rolls look good and have landed.

**Comment by christopherfujino** [comment]
@rmistry thanks, it looks like blowing away the checkout fixed it. I'll optimistically close this issue :)
