### ISSUE TITLE
Consider sorting generated plugin file sources

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#55899]
Someone using Flutter on Linux recently saw ordering changes in their generated plugin files. Having churn in those files (given that they are checked in) is annoying, so we should explicitly sort the data used to generate those files.

I'm not sure how many platforms are currently relying on whatever the order in a hash iterator happens to be; I suspect it's likely all of them.

**Comment by jonahwilliams** [comment]
If its coming from a Dart map, by default these are order preserving, but the insertion order itself might be random. Sorting SGTM at any rate

**Comment by stuartmorgan** [comment]
I think what's actually happening based on further observation is that something earlier in the plugin system is sorting by path (I didn't track down where, but that's what unit testing suggested was happening), so the order of a plugin in the generated files depends on where it comes from. For the normal case that's not a big deal, but it's annoying when using path-based plugins (which is why we were seeing this in projects using FDE plugins).
