### ISSUE TITLE
[web] How to clip the content while changing width of the window?

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#55897]
Is it possible in flutter web to automatically hide (clip) the content of the whole page when user is changing height or width of the windows? In other words, let's say regarding width. I have this:
https://i.stack.imgur.com/eAQ2i.png

while I would like to have this:
https://i.stack.imgur.com/9aP0K.png

**Comment by TahaTesser** [comment]
Hi @mordivgor 
Can you please explain the reason to have clipped content? Give us some use cases 
Thank you

**Comment by mordivgor** [comment]
Hi @TahaTesser ,
the most reason is that I would not care about overflowing the widgets. If I am shortening the width, I need to care about all widgets - how they will behave if there is no space for them.
Another reason is that it is quite common behavior in web - for instance on "facebook.com", shortening the width starts removing the parts of the page (i.e. chat), but from some point it just starts hiding the concrete parts of the page. Similar behavior can be checked on:
- amazon.com
- linkeind.com
- yahoo.com

**Comment by yjbanov** [comment]
Someone on StackOverflow probably knows how to do this. I imagine it's something like using [OverflowBox](https://api.flutter.dev/flutter/widgets/OverflowBox-class.html) or a derivative of `Viewport`.
