### ISSUE TITLE
[cocoon] make whitelist of github users who do releases, have github bot ignore non-master PRs from them

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#55900]
For legitimate release PRs (such as [this](https://github.com/flutter/flutter/pull/55871)), the GitHub bot changes the merge target from the release candidate branch. This can complicate CI runs for legitimate releases, however. We should be able to whitelist users who do releases, and have the GitHub bot skip changing merge targets back to `master` for PRs authored by these users.

**Comment by digiter** [comment]
Triage: maybe need a dedicated github group that has the permissions on release branches with @kf6gpe @pcsosinski

**Comment by christopherfujino** [comment]
> Triage: maybe need a dedicated github group that has the permissions on release branches with @kf6gpe @pcsosinski

can cocoon read github group memeberships?

**Comment by christopherfujino** [comment]
we could also have the bot search PR description for the string "cherry-pick"
