### ISSUE TITLE
TextFormField with obscureText true,  typing text shows preview of the last typed character for a moment

### ISSUE THREAD

**Issue by amailtoamal** [flutter/flutter#55910]
I tried to create a password input field using **TextFormField** and with _obscureText_ property as _true_. It works well in Android and iOS, but in web it is previewing the last typed character instantly, where it is not supposed to do so. Fix this...

**Comment by iapicca** [comment]
Hi @amailtoamal 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample.
Thank you

**Comment by amailtoamal** [comment]
**`flutter doctor -v`**

[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.0-3.2.pre at /home/user1/Programs/flutter
    • Framework revision 2a7bc389f2 (8 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/user1/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/user1/Android/Sdk
    • Java binary at: /home/user1/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/user1/Programs/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Reproducible Code**

**`main.dart`**
```
import 'package:flutter/material.dart';

void main() {
  runApp(PwdField());
}

class PwdField extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: TextFormField(
          obscureText: true,
          decoration: InputDecoration(
            labelText: "Password",
            labelStyle: TextStyle(
              fontSize: 14,
            ),
            prefixIcon: Icon(Icons.lock),
            contentPadding: EdgeInsets.symmetric(
              vertical: 5,
            ),
            border: OutlineInputBorder(),
          ),
        ),
      ),
    );
  }
}

```

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/51218
