### ISSUE TITLE
FrameTiming, unclear docs, which reference points can consumers expect for the timestamps there?

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#55916]
See [FrameTiming](https://github.com/flutter/engine/blob/bd5234780ec2a94cf5644ba957f3dbf98c33c0eb/lib/ui/window.dart#L95-L97):

```dart
  /// This is a raw timestamp in microseconds from some epoch. The epoch in all
  /// [FrameTiming] is the same, but it may not match [DateTime]'s epoch.
  int timestampInMicroseconds(FramePhase phase) => _timestamps[phase.index];
```

It is not entirely clear to me what "some epoch" in conjunction with "but it may not match [DateTime]'s epoch" means. Can consumers get a DateTime object from these timestamps using DateTime.fromMicrosecondsSinceEpoch at all times? And if not, what epochs are being used here, and under which circumstances do these change?

These timestamps are exposed via Dart VM service extensions. Consumers need to know whether they can always expect Unix time or timeline time or something else.

**Comment by ameryzhu** [comment]
same question

**Comment by modulovalue** [comment]
I'm closing this issue as it's seemingly very low priority and I don't need it to be resolved anymore (although it would still be nice to have proper docs for things like that).
