### ISSUE TITLE
Widget snapshot not working on web

### ISSUE THREAD

**Issue by marinatrajk** [flutter/flutter#55923]
```
FutureBuilder<Uint8List>(
                future: _getImage(context),
                builder: (context, snapshot) {
                  final _bytes = snapshot?.data ?? [];
                  return Column(
                    children: <Widget>[
                      Container(
                        height: 400,
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Card(
                            child: !snapshot.hasData
                                ? Center(child: CircularProgressIndicator())
                                : Image.memory(_bytes),
                          ),
                        ),
                      ),
                      RaisedButton.icon(
                        label: Text('Save Image'),
                        icon: Icon(Icons.image),
                        onPressed: _bytes.isEmpty
                            ? null
                            : () {
                                if (kIsWeb) {
                                  saveFile('${page.id}.png',
                                      binaryData: _bytes);
                                } else if (Platform.isIOS ||
                                    Platform.isAndroid) {
                                  ImageGallerySaver.saveImage(
                                      Uint8List.fromList(_bytes));
                                  Scaffold.of(context).showSnackBar(SnackBar(
                                    content: Text('Image saved to gallery!'),
                                  ));
                                } else {
                                  saveFile('${page.id}.png',
                                      binaryData: _bytes);
                                }
                              },
                      ),
                    ],
                  );
                },
              ),
```

```
Future<Uint8List> _getImage(BuildContext context) async {
    await Future.delayed(Duration(seconds: 1));
    return Provider.of<StoryModel>(context, listen: false).captureImages();
  }
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-9.0.pre.45, on Mac OS X 10.15.4 19E287, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade:
sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by timsneath** [comment]
Thanks for the report, Marina -- can you elaborate on what you were expecting to see and what you're actually seeing?

**Comment by marinatrajk** [comment]
We are taking a snapshot of each page inside our tool and generating a png image from that. This is working on our Desktop and mobile apps, but not on the Web app. 

<img width="1920" alt="Screen Shot 2020-05-13 at 9 39 09 AM" src="https://user-images.githubusercontent.com/9975218/81819829-d33f5000-94fd-11ea-97d7-487c77fe399f.png">

**Comment by yjbanov** [comment]
It's hard to tell without seeing the source code, but it seems you are trying to convert widgets to images? If so, HTML does not support this. We can add this to CanvasKit, which will be able to rasterize everything except platform views.

Deduplicating with https://github.com/flutter/flutter/issues/42767

**Comment by deakjahn** [comment]
The HTML canvas actually does, `canvas.toBlob()`. But if it comes in CanvasKit, all right. Just come because it's badly needed (not necessarily for widgets for everybody, the canvas is used in many other scenarios).
