### ISSUE TITLE
Touchpad-scrolling on gallery.flutter.dev has wrong/non-existent scroll physics on pixelbook

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55924]
Not sure why.  Scrolling by touching the screen correctly has scroll physics.  However scrolling using the trackpad just immediately stops on my pixelbook. (Scrolling using the touchpad in Chrome itself correctly has physics.) 

80.0.3987.162 (Official Build) (64-bit)

User Agent:

Mozilla/5.0 (X11; CrOS x86_64 12739.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36

**Comment by kunit1** [comment]
Maybe related: [32120](https://github.com/flutter/flutter/issues/32120)

**Comment by stuartmorgan** [comment]
Currently trackpad scrolling is only implemented as scrollwheel-type scrolling (not gestural), so it's up to the embedding, not the framework, to handle physics. I.e., if there's momentum, the web embedding needs to continue to send discrete scroll events to the engine until the momentum dies off. That's how macOS currently works, for instance.

**Comment by yjbanov** [comment]
@mdebbar @ferhatb I recall some discussion about this. We were going to interpolate the scrollwheel events to produce better scroll physics or something along those line.

**Comment by guidezpl** [comment]
@esouthren I remember you said this was fixed on a Chromebook, were you able to confirm on a Pixelbook?

**Comment by esouthren** [comment]
> @esouthren I remember you said this was fixed on a Chromebook, were you able to confirm on a Pixelbook?

Confirmed - working as expected, on trackpad and screen. shall we close?

**Comment by guidezpl** [comment]
sure!
