### ISSUE TITLE
cupertino picker looks wrong on Web

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55927]
Looks like the magnification/zoom effect isn't working/implemented:

![image](https://user-images.githubusercontent.com/11857803/80557239-1be9fb80-898b-11ea-98e7-7a6cd78e1ef1.png)

**Comment by eseidelGoogle** [comment]
Actually, it's pretty close.  It's missing the haptic feedback (not sure if that's possible on the web) and the lines, but otherwise pretty close.

![image](https://user-images.githubusercontent.com/11857803/80557379-931f8f80-898b-11ea-9a36-58457a67cf4b.png)

![image](https://user-images.githubusercontent.com/11857803/80557394-a29ed880-898b-11ea-9cd7-1140f013baef.png)

**Comment by TahaTesser** [comment]
Also CupertinoPicker and CupertinoDatePicker don't play the ticker sound  [#37329](https://github.com/flutter/flutter/issues/37329), not sure this  is possible web or not

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/37329 as the magnification turned out to be fine. Feel free to reopen if you think otherwise.
