### ISSUE TITLE
gallery.flutter.dev PWA support does not work on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55925]
When you install gallery.flutter.dev as a PWA on iOS it still launches in Safari (with normal URL bar).

Supposedly one can do better:
https://superpwa.com/doc/test-pwa-ios-devices/

When I installed superpwa.com on iOS it does not end up with a URL bar.

**Comment by timsneath** [comment]
I _think_ this is working right -- the URL bar is controlled by the display setting in manifest.json, which for the gallery is set to minimal-ui and on the superpwa site is set to standalone. Would be interesting to revisit this for gallery and identify which is the "best" setting for PWAs like this.

**Comment by ferhatb** [comment]
The four display modes are : Standalone,Fullscreen,Minimal-UI,Browser.
Since Flutter Apps typically provide elements for in app navigation, the better default is to use standalone that removes the browser bar for navigation.

**Comment by ferhatb** [comment]
Both default template for 'flutter create' and the gallery app has been updated. Will be available on next deploy.
