### ISSUE TITLE
Move IOSExternalTexture variants into a host test harness.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#55926]
None of the Metal or OpenGL related iOS functionality is tied to the way in which the pixel buffers for the external textures are managed. However, due to legacy reasons, the logic is mostly duplicated. Moreover, a lot of undefined behavior on the OpenGL backend is now depended upon by plugins. This must be codified into a single implementation for handling external pixel buffers. This component does not have to depend on the the client rendering API and can therefore be tested in any of the host test harnesses (the Darwin unittests being a likely candidate).

**Comment by jmagman** [comment]
@chinmaygarde can this be closed?

**Comment by chinmaygarde** [comment]
Yeah, we just got rid of the OpenGL stuff.
