### ISSUE TITLE
[webview_flutter] html doesn't load on iOS

### ISSUE THREAD

**Issue by NickoftheSouth** [flutter/flutter#55932]
If you use the following to load html data;

```    
     WebView(
      initialUrl: 'data:text/html;base64,${base64Encode(const Utf8Encoder().convert(contentToUse))}',
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        webViewController.loadUrl('data:text/html;base64,${base64Encode(const Utf8Encoder().convert(contentToUse))}');
      },

    navigationDelegate: (NavigationRequest request) {
      launch(request.url);
      return NavigationDecision.prevent;
      if (request.url.startsWith('https://www.youtube.com/')) {
      print('blocking navigation to $request}');
      return NavigationDecision.prevent;
      }
      print('allowing navigation to $request');
      return NavigationDecision.navigate;
    },
    onPageStarted: (String url) {
      print('Page started loading: $url');
    },
    onPageFinished: (String url) {
      print('Page finished loading: $url');
    },
    gestureNavigationEnabled: true,
    )
```

It works perfectly on Android but fails to show anything on iOS.
Seen on iOS 12.4.5.

I think it would  be nice to have a parameter in WebView that you can pass in the html string.

**Comment by VladyslavBondarenko** [comment]
Hi @NickoftheSouth 
What version of webview_flutter are you using?
Could you provide your `flutter doctor -v`?
does it work this way on iOS? https://github.com/flutter/flutter/issues/42351#issuecomment-541836147

**Comment by pgainullin** [comment]
believe this might be the underlying issue here: https://github.com/flutter/flutter/issues/30256#issue-427323601. The workaround mentioned there worked for me in a similar context

**Comment by TahaTesser** [comment]
Hi @NickoftheSouth 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
