### ISSUE TITLE
Cupertino Slider shadows are too strong/harsh on the web

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55930]
Cupertino Slider shadows are too strong/harsh on the web
![image](https://user-images.githubusercontent.com/11857803/80557752-d62e3280-898c-11ea-80af-09dbc604d550.png)

Note the very soft shadow behind the slider:

![image](https://user-images.githubusercontent.com/11857803/80557849-1db4be80-898d-11ea-994a-87a2c17c36d1.png)

**Comment by yjbanov** [comment]
@ferhatb Checking. This  might be different. It seem Safari is not rendering a penumbra of the shadow at all. I only see the umbra.

**Comment by yjbanov** [comment]
Confirmed that this is a different issue. `CupertinoSlider` uses a blur `MaskFilter` on an `RRect` instead of a shadow. Safari does not support the `filter` property.
