### ISSUE TITLE
CupertinoTextField When users use the Sony mobile phone poboxPlux input method, they cannot input capital letters continuously

### ISSUE THREAD

**Issue by lidong-biubiubiu** [flutter/flutter#55942]

**Comment by TahaTesser** [comment]
Hi @lidong-biubiubiu 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by lidong-biubiubiu** [comment]
@TahaTesser thank you!
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale zh-Hans)
    • Flutter version 1.12.13+hotfix.8 at .../flutter
    • Framework revision 0b8abb4724 (3 months ago), 
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at .../Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = .../Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)


flutter run --verbose
[  +74 ms] executing: [.../flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +211 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [.../flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +258 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [.../flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [.../flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +96 ms] executing: [.../flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +15 ms] executing: sw_vers -productName
[  +41 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +27 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15
[        ] executing: sw_vers -buildVersion
[  +35 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19A583
[  +61 ms] executing: /usr/bin/xcode-select --print-path
[  +14 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[+1548 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.1
           Build version 11A1027
[  +97 ms] executing: .../Android/sdk/platform-tools/adb devices -l
[  +22 ms] Exit code 0 from: .../Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
[  +42 ms] executing: .../flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +249 ms] /usr/bin/xcrun simctl list --json devices
[ +467 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] .../Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +44 ms] ro.hardware = ranchu
[  +10 ms] AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[   +1 ms] iPhone 8 Plus       • F07891CF-C326-456D-8648-B5D6B683B7E0 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)
[  +21 ms] "flutter run" took 2,738ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


code:
@override
  Widget build(BuildContext context) {
    return Container(
      height: AppNumber.h_88,
      padding: EdgeInsets.symmetric(horizontal: AppNumber.w_24),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(AppNumber.w_8),
          color: widget.backgroundColor ?? AppColors.c_1F767680),
      child: Row(
        children: <Widget>[
          Expanded(
            child: CupertinoTextField(
              key: Key(widget.keyValue),
              controller: widget.controller,
              placeholder: widget.placeholder ?? '',
              placeholderStyle: widget.placeholderStyle ??
                  AppTextStyle.c_FFFFFFFF_40_s_30_w_300,
              style: widget.style ?? AppTextStyle.c_FFFFFFFF_60_s_30_w_300,
              decoration: BoxDecoration(
                  border: Border.all(width: 0, color: Colors.transparent)),
              keyboardType: widget.inputType,
              maxLines: 1,
              autofocus: widget.autofocus,
              maxLength: widget.maxLength,
              obscureText: widget.obscureText,
              textInputAction: widget.inputAction,
              clearButtonMode: _clearButtonMode,
              focusNode: widget.focusNode,
              onChanged: _onChanged,
              onEditingComplete: widget.onEditingComplete,
            ),
          )
        ],
      ),
    );
  }

**Comment by TahaTesser** [comment]
Hi @lidong-biubiubiu 
What is poboxPlux input method? 
Do you experience this issue on only Sony mobile? 
You sample is has lot of missing code,  post a minimal runnable code sample to reproduce the problem 
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
