### ISSUE TITLE
App version code in google play console is different from pubspec.yaml file

### ISSUE THREAD

**Issue by sathya4code** [flutter/flutter#55945]
Hi, For some security reason i am checking the app version and send it to backend. In my backend i have the version code like 5. But when i am reading the version code using package_info i am getting the version code like 1005, 2005 and 4005. How can i get the exact version code? Any idea?

I uploaded as splite APKs. In playstore console also showing like 1005, 2005 and 4005

Note: i cant use bundle. we don't have access for certificate file.

Can anyone please help me to solve this?

**Comment by iapicca** [comment]
Hi @sathya4code 
can you please provide your `flutter doctor -v` , 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

What version returns running `flutter run --release --verbose` ?
Thank you

**Comment by sathya4code** [comment]
Hi, Thank you.. I solved this issue using, Platform channel code. Got the version code using Google in app update.

**Comment by TahaTesser** [comment]
Hi @sathya4code 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
