### ISSUE TITLE
SocketException: OS Error: 信号灯超时时间已到

### ISSUE THREAD

**Issue by tianyingzhong** [flutter/flutter#55943]
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 57824
Oops; flutter has exited unexpectedly.
Crash report written to D:\Project\Flutter\flutter_module\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

**Comment by iapicca** [comment]
Hi @tianyingzhong 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

Also I see in the error you are reporting that a log file has been generated
`Crash report written to D:\Project\Flutter\flutter_module\flutter_04.log;`
could you please attach the file to your post
Thank you

**Comment by TahaTesser** [comment]
Hi @tianyingzhong 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
