### ISSUE TITLE
[image_picker] On iOS pickVideo(source: ImageSource.camera) returns video file in mono - even on stereo able device.

### ISSUE THREAD

**Issue by fideldonson** [flutter/flutter#55957]
We have created a pretty simple app to record video and upload the file to our server using `ImagePicker.pickVideo(source: ImageSource.camera)`. Everything works as expected except that on iOS the uploaded file is always mono - even on devices where the native Camera app records in stereo.

**Comment by iapicca** [comment]
Hi @fideldonson 
can you please provide your `flutter doctor -v` , 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by fideldonson** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-DK)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\denni\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\denni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by fideldonson** [comment]
pubspec.yaml:
name: waffle_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3
  http: ^0.12.0+4
  provider: ^4.0.4
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by fideldonson** [comment]
pubspec.yaml:
name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3
  http: ^0.12.0+4
  provider: ^4.0.4
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by fideldonson** [comment]
pubspec.yaml:
name: waffle_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3
  http: ^0.12.0+4
  provider: ^4.0.4
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by fideldonson** [comment]
I cant share a reproducible minimal code sample because the problem is only apparent once the video is uploaded to a server.

But here is the code in question:
`Future getVideo(String sceneID, bool doRecord) async{
    print("start recording");
    _sceneID = sceneID;

    var video;
    if(doRecord){
      video = await ImagePicker.pickVideo(source: ImageSource.camera);
    }else{
      video = await ImagePicker.pickVideo(source: ImageSource.gallery);
    }
    
    if(video == null) {
      print("no file selected");
    }else{
      print("file selected");
      _video = video;
      videoPath = _video.path;

      sendVideo();
    }
  }

 Future sendVideo() async{
    print("send video");
    String jspEndPoint = 'upload-ajax.jsp?id='+_sceneID+"&action=scenefileform";

    var request = http.MultipartRequest('POST', Uri.parse(jspEndPoint));
    request.files.add(
      await http.MultipartFile.fromPath(
        'video',
        _video.path
      )
    );
    var res = await request.send();
    print("finished status:");
    print(res.statusCode);
  }`

**Comment by fideldonson** [comment]
Since iOS 11 UIImagePickerController has the property videoExportPreset which can be set to AVAssetExportPresetPassthrough to get the original uncompressed and unmodified file... I suspect this is not set on the image_picker plugin. any help in pinpointing if this is the case would be greatly appreciated.

**Comment by fideldonson** [comment]
Looks like it would be a case of updating ios/Classes/FLTImagePickerPlugin.m line 100 with:
if (@available(iOS 11.0, *)) {
  _imagePickerController.videoExportPreset = AVAssetExportPresetPassthrough;
}

**Comment by TahaTesser** [comment]
Hi @fideldonson 
Is there any way to reproduce this issue while exporting to local storage or uploading to firebase_storage?
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
