### ISSUE TITLE
Updated master branch doesn't install "vector_math" Dart package by default

### ISSUE THREAD

**Issue by ZaJarv** [flutter/flutter#55954]
Hi!👋
So, i've created week ago my app with Flutter being on fresh master branch for this whole time, and it worked as expected.

Couple of days ago (27-28/04/2020) i've update master with latest changes, but cleared `pub-cache` folder before, so just to have new updated cache of Dart packages.

After that, when trying to start my App on iOS Emulator, realized, that it doesn't work, console throws bunch of exceptions, blaming that there are no `vector_math` package in cache installed.

With `flutter pub cache add vector_math` problem was solved, but it manual installation, is there are particular reason why this package was removed from initial, fresh flutter installation?🤔

And this behavior only with `master` and `dev` branches, on `stable` and `beta` this package still exists and everything working as expected

**Comment by iapicca** [comment]
Hi @ZaJarv 
it may have something to do with how the pub_cache folder was cleared
did you run `flutter pub cache repair` or what did you delete it manually
could you please provide the steps to reproduce this behaviour?
thank you

**Comment by ZaJarv** [comment]
Hey @iapicca 👋
It was classical `rm -rf` inside `pub-cache` directory.

I looked into my project, and there is dependency for `vector_math`: `vector_math:file:///Users/zajarv/.dev/pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/` in `.packages` file

When i created this project (couple of weeks ago) with help of Android Studio, Flutter was on `master` branch, and since then i updated Flutter with `flutter upgrade` multiple times and from time to time deleting content of `pub-cache` manually before upgrading flutter, so flutter always fills `pub-cache` directory with Dart packages.

But couple of days ago when i've done completely the same procedure, emptying `pub-cache` with `rm -rf` and then `flutter upgrade` my app could not start because there was no `vector_math` installed now😨

Repeating this procedure but being in `stable` or `beta` installs all required packages including `vector_math`. `master` and `dev` doesn't install this package.

I can install it manually of course, but still ineteresting why it's removed from default installation procedure and seems that list of packages differs between branches🧐

**Comment by mraleph** [comment]
> After that, when trying to start my App on iOS Emulator, realized, that it doesn't work, console throws bunch of exceptions, blaming that there are no vector_math package in cache installed.

@ZaJarv few questions:

1. Does your own code reference `vector_math`? or it is some other code?
2. If your code references `vector_math` - do you have `vector_math` dependency declared in your `pubspec.yaml`?
3. Why are you purging pub cache? You should not need to do that ever.

**Comment by ZaJarv** [comment]
@mraleph 

1. Seems not, since it very basic App with mostly layout widgets imported from `'package:flutter/material.dart';`

2. code not references `vector_math` so not references in `pubspec.yaml` too

3. No answer to this😄But i don't think that it relevant, sine Flutter when upgrades or after switching branches and with `flutter upgrade` anyway downloads dart packages

**Comment by ZaJarv** [comment]
Update.
With fresh installation of Flutter everything works as expected🤔
Steps:
- performed fresh installation of Flutter
- used branch - `master`
- checked `pub-cache` directory, `vector_math` package was not found
- opened Android Studio and created new Flutter project, checked dependencies in it, found `vector_math` as dependecy.
- checked `pub-cache` directory and found `vector_math` package with different timestamp than other packages, so it's possible that it was installed by Android Studio🤔

But not sure then, why earlier everything was okay when i changed branches to `stable` and `beta`🤷‍♀️

**Comment by ZaJarv** [comment]
Yeah, solved, this, and a few other packages installed by Android Studio when new project is created, just checked, sorry for disturbance guys🤦‍♀️
