### ISSUE TITLE
Slider value indicator overlay should consider the whole screen width when choosing its horizontal position

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#55963]
Now that the value indicator draws in the overlay, it only needs to be shifted left and right if it would be off the screen (not outside the bounds of the slider)

In this screenshot, it shifts to the right to contain it in the Slider bounds, but there is still room to the left, so it does not need to shift.
![Screen Shot 2020-04-28 at 5 46 51 PM](https://user-images.githubusercontent.com/591699/80617997-c48e6e80-8a10-11ea-9fa1-7981ef055249.png)

**Comment by JoseAlba** [comment]
Fixed https://github.com/flutter/flutter/pull/57327
