### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle__benchmark hotRestartMillisecondsToFrame regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55965]
Maybe the engine roll https://github.com/flutter/flutter/pull/55906 or https://github.com/flutter/flutter/pull/55919.

![Screen Shot 2020-04-29 at 9 08 42 AM](https://user-images.githubusercontent.com/1435716/80619087-0a3f3d00-89f9-11ea-9326-2eface61e900.png)

**Comment by liyuqian** [comment]
The benchmark went down today. To make the redness less flaky, I rebaselined the threshold and I'm going to close this now.
