### ISSUE TITLE
new_gallery__transition_perf worst_frame_build_time_millis needs a baseline.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#55964]
![Screen Shot 2020-04-29 at 9 06 13 AM](https://user-images.githubusercontent.com/1435716/80618821-bc2a3980-89f8-11ea-9eb8-da6626b20465.png)

**Comment by kf6gpe** [comment]
Looks like the baseline remains too low for this
![Screen Shot 2020-05-12 at 10 22 13 AM](https://user-images.githubusercontent.com/1435716/81725291-77f85980-943a-11ea-8f05-886abd3a7942.png)
 benchmarks:

**Comment by liyuqian** [comment]
The `worst_frame_build_time_millis` seems to be red from the beginning so our first baseline was bad. I've rebaselined it properly.

**Comment by liyuqian** [comment]
Closing as it's baselined.
