### ISSUE TITLE
[web]: <Failed to compile application>

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#55980]
I built a simple calculator app which works perfectly on android and IOS devices didn't work on chrome web  !

**Comment by yash-saini275** [comment]
what was the error shown?

**Comment by aseef17** [comment]
Hey @SAMYAK99 
I’ve noticed the flutter doesn’t real through error when you’re trying to build the application[WEB]. This happens a lot with me too. A good way to get your console to throw errors is try to build the flutter application. You can try flutter build web —release and it should then throw the errors in the console.

Some from the flutter team should check this out though.

Hope this helps

**Comment by SAMYAK99** [comment]
following is the error thrown when i used flutter build web

Target dart2js failed: Exception: lib/main.dart:1:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Error: Compilation failed.

**Comment by aseef17** [comment]
@SAMYAK99 
You cannot use FFI on Flutter Web
As suggested [Here](https://github.com/flutter/flutter/issues/43898), you can try to have a look at the JS interoperability [package](https://pub.dev/packages/js)

**Comment by SAMYAK99** [comment]
hey I just find out the solution by importing js dart package -
dependencies:
  js: ^0.6.0

**Comment by aseef17** [comment]
@SAMYAK99 
Please go ahead and close the issue.

**Comment by IsraelM17** [comment]
> Hey @SAMYAK99
> I’ve noticed the flutter doesn’t real through error when you’re trying to build the application[WEB]. This happens a lot with me too. A good way to get your console to throw errors is try to build the flutter application. You can try flutter build web —release and it should then throw the errors in the console.
> 
> Some from the flutter team should check this out though.
> 
> Hope this helps

I can see that I use two different packages for the same function. the console does not show this error, but with the flutter build web command, I could see why my application did not compile. Thanks for your help.
