### ISSUE TITLE
Can not install flutter in Mac Catalina properly

### ISSUE THREAD

**Issue by Shengli94132** [flutter/flutter#55986]
I just follow all steps from the course and can not install flutter with the log as attached
[flutter_07.log](https://github.com/flutter/flutter/files/4554656/flutter_07.log)

**Comment by jonahwilliams** [comment]
The error is:

```
Standard error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

This likely means that xcode is incorrectly configured.

**Comment by iapicca** [comment]
Hi @Shengli94132 
you may want to try this possible [solution](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a/254381#254381)
thank you

**Comment by khalidsharief** [comment]
Hi @iapicca it worked like magic, thanks million.

**Comment by TahaTesser** [comment]
Hi @Shengli94132 
Please @iapicca's  solution above
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
