### ISSUE TITLE
[web]: Gallery app fonts inconsistency 

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#55989]
On both iphone 11 Pro Max and iPhone X viewing the Gallery app in chrome, the fonts look different than they do in chrome desktop browser specifically for the cupertino alerts.

![97926](https://user-images.githubusercontent.com/56849473/80654873-2c08e600-8a32-11ea-948a-c3e9a4ba22ff.jpg)

**Comment by ferhatb** [comment]
Platform detection is working now. Tested on latest flutter.gallery.dev , clearing browser cache and reloading on iPhone11 Pro Max:

![Screen Shot 2020-05-13 at 1 47 02 PM](https://user-images.githubusercontent.com/5061034/81863543-448ffa80-9520-11ea-90c4-2d479e796c2c.png)

**Comment by ferhatb** [comment]
Correction, works in Safari. Fails on Chrome.
