### ISSUE TITLE
[video_player] package is giving me 403 response code

### ISSUE THREAD

**Issue by DeadlyMissile** [flutter/flutter#56004]
So I am using video_player to play an online video I got from a site but I get 403 response code. I can copy the link, paste it on my chrome on my phone and it will load the video. Any thoughts on why the error?

**Comment by VladyslavBondarenko** [comment]
Hi @DeadlyMissile 
can you please provide your `flutter doctor -v` and a minimal complete code sample to reproduce it (with the link used)?

**Comment by TahaTesser** [comment]
Hi @DeadlyMissile 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
