### ISSUE TITLE
[Windows] invoke TextInput.requestAutofill throw PlatformException

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#56007]
## Steps to Reproduce

1. I use `flutter_form_builder`, write some code like the following
```dart
FormBuilderTextField(
  attribute: "height",
  decoration: InputDecoration(
    labelText: "height",
    suffixIcon: IconButton(
      icon: Icon(Icons.screen_lock_portrait),
      onPressed: () {
        setState(() {
          _fbKey.currentState
              .setAttributeValue('height', '-1');
        });
      },
    ),
  ),
),
```
2. When I click the suffix icon, I got `Unhandled Exception: PlatformException(Bad Arguments, Method invoked without args, null)`. In the last a few call stack, I found the error code is around `_channel.invokeMethod<void>('TextInput.requestAutofill');`. See the following snapshot for details.

![image](https://user-images.githubusercontent.com/2276718/80672034-1e109f00-8ade-11ea-8fbe-3ea8c2321ef4.png)

**Expected results:** 
No exception throws.

**Actual results:** 

PlatformException throwed.

I searched the issues and found the similar https://github.com/flutter/flutter/issues/55653, However when I upgrade to the latest master channel. It still failed with exception shown above.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-9.0.pre.73, on Microsoft Windows [Version 10.0.18363.815], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
[✓] Android Studio (version 3.6)
[✓] VS Code, 64-bit edition (version 1.44.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @liudonghua123 
the engine fix https://github.com/flutter/engine/pull/17964 could be not yet rolled into master, please check again when this PR will be merged https://github.com/flutter/flutter/pull/56015

**Comment by stuartmorgan** [comment]
The last engine roll was 21 hours ago; the fix was only landed in the engine 11 hours ago.

Closing as a duplicate.
