### ISSUE TITLE
[cocoon] Dashboard is not updating retried luci tasks

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#56005]
If a luci task fails on prod schedulers, it can be retried using the buildbucket ui or bb command but the dashboard is not updating the new status.

The following image shows the retried tasks as green:

![image](https://user-images.githubusercontent.com/54371434/80668780-9a13d400-8a57-11ea-9060-b17907c968ad.png)

The flutter dashboard refreshed at the same time:

![image](https://user-images.githubusercontent.com/54371434/80668901-e5c67d80-8a57-11ea-8ce2-67599dff660e.png)

Links to tasks:
* [failing] https://ci.chromium.org/p/flutter/builders/prod/Linux/11926
* [passing] https://ci.chromium.org/p/flutter/builders/prod/Linux/11927

The correct behavior is if there are many results for the same commit then it should be ordered by time and show the status for the most recent one.

**Comment by godofredoc** [comment]
List of builds should be filtered to one build per branch and commit. If there is more than one build the one created more recently should be kept: https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/service/luci.dart#L92

Make getRecentBuilds to return a map to remove the second loop here: https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_chromebot_status.dart#L82

**Comment by keyonghan** [comment]
Updating logic is working well. The problem is that this rerun here missed `commitSha` and `ref`:
```
taskName: mac_bot, 
commitSha: unknown, ref: unknown, status: Succeeded, 
commitSha: bd6ccb606a11dacf7c72970a9d623e6b89668d70, ref: refs/heads/master, status: Failed
```
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_chromebot_status.dart#L85 needs that info to update luci status.

@godofredoc do you have any idea why those info was missing? Or can we have rerun with those info?

**Comment by godofredoc** [comment]
Reruns from the scheduler do not pass commit sha. They just run whatever is at head.

**Comment by godofredoc** [comment]
Rerun mac and windows with a hash, let's see if the status gets updated:
```
bb add -commit "https://chromium.googlesource.com/external/github.com/flutter/flutter/+/bd6ccb606a11dacf7c72970a9d623e6b89668d70" "flutter/prod/Mac"
bb add -commit "https://chromium.googlesource.com/external/github.com/flutter/flutter/+/bd6ccb606a11dacf7c72970a9d623e6b89668d70" "flutter/prod/Windows"
```

**Comment by keyonghan** [comment]
the updating process works as expected. Closing.
