### ISSUE TITLE
HostMessages.addJSONMessageHandler doesn't call my callback

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#5600]
I'm trying to activate the bluetooth of my phone with Flutter and some message passing to the host.

i have already a lot of message going from Flutter to Android and that work great !
But the part where i have some problem is when i need to catch a message that come from Android to Flutter.

In short addJSONMessageHandler doesn't call my callback function.
ps: i have tried with addMessageHandler and same problem the callback function is never call.

The host code send the message in the onActivityResult after the user answer to request Bluetooth (in my code but should be the same for other api)

**Comment by eseidelGoogle** [comment]
@jason-simmons would know.  Thanks for the bug!

**Comment by Kleak** [comment]
same problem for when i want to get notified if the bluetooth adapter state change (eg: on, off, turning on, turning off)

**Comment by a14n** [comment]
Have you tried to run `hello_services` with your current flutter version?

**Comment by Kleak** [comment]
oh i have found HostMessage.add*MessageHandler must be call in the main after runApp

**Comment by eseidelGoogle** [comment]
Does that resolve your issue?  And if so do we need to make additions to our docs on this feature to explain this: https://flutter.io/platform-services/ ?

**Comment by Kleak** [comment]
yep problem solved.
About the documentation maybe add that HostMessage must be used inside the main function and after runApp.

**Comment by sethladd** [comment]
cc @qchong can you help us add this note to our doc?

@Kleak thanks for giving it a shot and providing feedback!

**Comment by qchong** [comment]
@abarth @Hixie Can you shed some light on why the `HostMessage` class must be used inside the main function and after runApp, in order for message passing to work? 

Can the initial `addJSONMessageHandler()` call just take a `Null` callback object argument or does it actually have to attach to a handler that returns some real value before  `sendJSON()` can be invoked? 

I'm also wondering if it would be possible/desirable for Flutter to implicitly create a message handler for the app when a `HostMessage` object is first constructed.

**Comment by Hixie** [comment]
I'm not familiar with that code. @jason-simmons might know.

**Comment by jason-simmons** [comment]
HostMessages.addJSONMessageHandler (and other clients of Mojo services) can not be called until the MojoShell is set up by the ServicesBinding

You can use addJSONMessageHandler prior to runApp by calling WidgetsFlutterBinding.ensureInitialized() first.

This is rather obscure though.  The docs generally don't have much coverage of Flutter's usage of Mojo.

**Comment by qchong** [comment]
Thanks Jason! 

@Hixie @jason-simmons @devoncarew  What other Flutter framework classes are clients of Mojo services? Is there a way for the API doc generator to determine which Flutter methods/classes first require `WidgetsFlutterBinding.ensureInitialized()` to be called before being used for the first time, then add a note in that method's description?

Maybe something like: "You must call `runApp` or `WidgetsFlutterBinding.ensureInitialized() ` before using this API."

**Comment by eseidelGoogle** [comment]
Or potentially the APIs could throw and explain the error?  I know that mojo intentionally is silent about there being no listeners, but perhaps there is an assert we should be using at the binding layer to detect this failure case?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/1556 is the bug about how to improve this situation.
