### ISSUE TITLE
InputDecoration labelText is unnecessarily ellipsized from long prefixText

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#56008]
## Steps to Reproduce
See https://dartpad.dev/cfc5ac6bcce92be669c147981f5a97ec for a demonstration, but the main part is:

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          width: 300,
          height: 200,
          child: TextField(
            controller: _controller,
            decoration: const InputDecoration(
              prefixText: 'The five boxing wizards jump quickly:',
              labelText: 'My Label',
            ),
          ),
        ),
      ),
    );
  }
```

**Actual results:**
Even though `prefixText` and `labelText` never share the same space, it appears that `labelText` is truncated with an ellipsis if `prefixText` is sufficiently long, regardless of whether the `TextField` has focus.

**Expected results:** 
`labelText` truncation is independent of `prefixText`.

Internal bug is b/155349947.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I do see this in the dartpad and it seems to be incorrect.  This is probably a bug with how the available size for the label is calculated here: https://github.com/flutter/flutter/blob/28138ec5e3271ae35295a46bf2eeaf554eeb2535/packages/flutter/lib/src/material/input_decorator.dart#L953
