### ISSUE TITLE
i can not flutter run 

### ISSUE THREAD

**Issue by kamatasofthand** [flutter/flutter#56014]
Sending crash report to Google.
Crash report sent (report ID: e6ca3d928f59bf78)
Oops; flutter has exited unexpectedly.
 
Crash report written to /Users/longge/Desktop/flutterdemo/appdemo/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by iapicca** [comment]
Hi @kamatasofthand 
can you please provide your `flutter doctor -v`
and the log at the location indicated by the error
```bash
Crash report written to C:\Windows\System32\flutter_02.log;
```
Thank you

possibly related to https://github.com/flutter/flutter/issues/55865

**Comment by kamatasofthand** [comment]
longge@longgedeMacBook-Air app01 % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale zh-Hans)
    • Flutter version 1.12.13+hotfix.9 at /Applications/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/longge/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone (3) • 00008020-001949A61138002E • ios • iOS 13.3.1

! Doctor found issues in 1 category.

**Comment by kamatasofthand** [comment]
![image](https://user-images.githubusercontent.com/45869476/80677680-460afd00-8af4-11ea-91dc-05c0f536e06e.png)

**Comment by iapicca** [comment]
Hi @kamatasofthand 
could you please provide the logs mentioned [above](https://github.com/flutter/flutter/issues/56014#issuecomment-621630699)

also you may want to fix the error in the doctor
running `flutter doctor --android-licence` or
following the indications in this [issue](https://github.com/flutter/flutter/issues/51712)
Thank you
