### ISSUE TITLE
TextField keyboard issue run iOS

### ISSUE THREAD

**Issue by TinySungo** [flutter/flutter#56013]
when i run application on iOS :
TextField becomeFirstResponse, keyboard's backgroundColor is white, also show and dismiss

**Comment by iapicca** [comment]
Hi @TinySungo 
can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @TinySungo 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
