### ISSUE TITLE
Do action when user does not interact

### ISSUE THREAD

**Issue by khalid-al-shehri** [flutter/flutter#56016]
**My problem is as follows:** sometimes my users don't interact, or they do not do any event, so for secure them, I should log-out the user because the user has sensitive data.

Is there any function from flutter do the same thing? 

**Conclusion :** if the user open my application and keep the application open without any action or interact for any reason, I want of the application to count 5 min if no interacts from the user, the application should do some actions.

**What I tried :** I used timer but I want to ask does the timer is the best practice or not ?

I checked of AppLifecycleState, but it does not help in my case.
AppLifecycleState works if the application in background or open again.

Flutter doctor :
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by khalid-al-shehri** [comment]
@zoechi Could you help me here please

**Comment by aseef17** [comment]
@khalid-al-shehri 

From what i understand, your application communicates with a server to perform various tasks. So why not let the server handle this you can steam data from the network socket and listen for the conditional parameter to log the user out. 
Hope that helps

**Comment by khalid-al-shehri** [comment]
@aseef17 

Some of application's jobs do not need server, so I should handle it from my side.

**Comment by VladyslavBondarenko** [comment]
@khalid-al-shehri 
I'll attach your SO question here
https://stackoverflow.com/questions/61516671/do-action-when-user-does-not-interact

**Comment by VladyslavBondarenko** [comment]
@khalid-al-shehri 
please follow also on https://stackoverflow.com/questions/54999917/detect-when-user-is-not-interacting-the-app-in-flutter
I'm going to close, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it
