### ISSUE TITLE
Can we run flutter driver tests on BrowserStack or Saucelabs? 

### ISSUE THREAD

**Issue by varunatester** [flutter/flutter#56010]

**Comment by darshankawar** [comment]
This seems to be a very old issue and was left untracked. But to answer the question, flutter driver doesn't explicitly run on BrowserStack or Saucelabs, as it requires some kind of instrumentation tests using native app.

Moreover, `integration_test` is now recommended way to write automated / integrations tests for flutter app which supports running them on Firebase Test Lab.

I am going ahead and closing this as stale issue.  For more reference on it, check this issue: https://github.com/flutter/flutter/issues/7087
