### ISSUE TITLE
[web]: <After resolving all error only index.html is running main.dart not even called>

### ISSUE THREAD

**Issue by nil1613** [flutter/flutter#56025]
You must have a dependency on build_runner in pubspec.yaml.

```
pubspec.yaml
dev_dependencies:
build_runner: >=1.6.2 <2.0.0
```

You must have a dependency on build_web_compilers in pubspec.yaml.

```
pubspec.yaml
dev_dependencies:
build_web_compilers: >=2.6.1 <3.0.0
You have a dependency on cupertino_icons which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter_test which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78
```

I am getting above issue while running flutter web.
After adding build_runner and build_web_compilers dependencies

I am getting below errors

```
You have a dependency on cupertino_icons which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter_test which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
```

and after removing cupertino_icons,flutter and flutter_test from pubspec.Yaml file project is running but Its not included main.dat file only index.html is running then what is the use of Flutter Web
Can anyone suggest y this is happening ?

**Comment by VladyslavBondarenko** [comment]
@nil1613 
It's not a surprise that main.dart will not be running without `flutter` dependency.
You don't need to have `build_web_compilers` or `build_runner` dependencies to be able to run web, it's supported by default starting from the beta channel, see https://flutter.dev/docs/get-started/web.
Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it

**Comment by nil1613** [comment]
I have gone through the linkhttps://flutter.dev/docs/get-started/web. and 
I have removed build_web_compilers and build_runner dependencies
Now I am getting below errors


webdev could not run for this project.
You must have a dependency on `build_runner` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_runner: >=1.6.2 <2.0.0
You must have a dependency on `build_web_compilers` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_web_compilers: >=2.6.1 <3.0.0
You have a dependency on `cupertino_icons` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter_test` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78
_

Now what should i add or remove to run main.dart

**Comment by nil1613** [comment]
Below is my yaml file .Is something wrong with this ?

name: t1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by VladyslavBondarenko** [comment]
@nil1613 
have you run `flutter pub get` after editing `pubspec.yaml` and before running your app?

**Comment by nil1613** [comment]
Yes

**Comment by nil1613** [comment]
haven't found anything like .pub-cache

**Comment by nil1613** [comment]
Hi I am not able to build my website can anyone help
