### ISSUE TITLE
[DartPad of flutter] The NavigatorState.pop method return void in dart-pad.

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#56040]
I don't know if this problem is a flutter problem or a dartpad problem, so I post here too. The original: https://github.com/dart-lang/dart-pad/issues/1548

**Comment by iapicca** [comment]
Hi @CaiJingLong 
could you please provide a reproducible minimal code sample
Thank you

**Comment by CaiJingLong** [comment]
Hi, I know the reason, because dartpad uses master or dev API, but my code is copied from the stable branch.
