### ISSUE TITLE
add a property to change the thumb icon on a slider, thanks.

### ISSUE THREAD

**Issue by hiwa-jalal** [flutter/flutter#56043]

**Comment by VladyslavBondarenko** [comment]
@hiwa-jalal 
https://medium.com/flutter-community/flutter-sliders-demystified-4b3ea65879c
may be helpful

**Comment by hiwa-jalal** [comment]
thank you, and i already took a look at it, but i just wanted the flutter team to have a simple property that can change the slider thumb icon.

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
The Slider follows the Material guidelines for its default look and feel, but is left open to customize. It is certainly possible to achieve this Slider design with the current API, but it won't be built in as a property since it is not part of the material guidelines.
