### ISSUE TITLE
there is message that is dispalyed all the time when i am debugging my app

### ISSUE THREAD

**Issue by VivanVatsa** [flutter/flutter#56047]
THIS IS THE ERROR THAT I AM FACING AND THERE IS NO SOLUTION I CAN FIND ON THE INTERNET!!
PLEASE HELP.
WHAT TO DO???

--------------------------------------------------------------------
When the exception was thrown, this was the stack
#0      Quiz.build.<anonymous closure>.<anonymous closure> 
package:flutter_tuto/quiz.dart:21
#1      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
#2      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
#3      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#4      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#edfd9
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(205.4, 296.0)
    finalLocalPosition: Offset(205.4, 19.0)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
type 'List<String>' is not a subtype of type 'int' of 'score'

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by VivanVatsa** [comment]
thanks, appreciate ur help!
