### ISSUE TITLE
Gallery would like to integrate Google Feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5604]
Google Feedback is a great way to capture user feedback from apps in the wild. Eventually, we'd like the Gallery to add a way for users to provide feedback, directly from the app.

**Comment by eseidelGoogle** [comment]
This should be straightforward using the internal feedback plugin.  customer:fast is already doing this and @collinjackson would know more.

**Comment by sethladd** [comment]
Not required for our initial push (hence, not August) but yeah, would be great in a future version!

**Comment by collinjackson** [comment]
Looks straightforward, happy to take this

**Comment by eseidelGoogle** [comment]
If we do this, it will be internal-only, so I don't think we need a public bug to track.
