### ISSUE TITLE
Flutter web crashes when moving between two screens with different pixelRatio

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#56050]
Probably related to https://github.com/flutter/flutter/issues/41328 and https://github.com/flutter/engine/pull/17209 cc @ferhatb @yjbanov 

## Steps to Reproduce

⚠️  You need 2 screens to reproduce the exception

1. open a Flutter web app on a retina
2. move the window to the non-retina screen

**Expected** : nothing ( silently switching to the new screen resolution )

**Actual** : Exception 
```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY
╞═════════════════════════════════════════════════════════

[   +1 ms] The following assertion was thrown during a scheduler callback:

Assertion failed:

[   +6 ms]
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dar
t:111:16

matrix4[0] == window.devicePixelRatio &&

matrix4[5] == window.devicePixelRatio

is not true

When the exception was thrown, this was the stack:

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
216:49
throw_

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
26:3
assertFailed

[   +1 ms] lib/_engine/engine/surface/scene_builder.dart 112:33
pushTransform

packages/flutter/src/rendering/layer.dart 1648:26
addToScene

packages/flutter/src/rendering/layer.dart 803:5
buildScene

packages/flutter/src/rendering/view.dart 230:36
compositeFrame

packages/flutter/src/rendering/binding.dart 406:18
drawFrame

packages/flutter/src/widgets/binding.dart 865:13
drawFrame

packages/flutter/src/rendering/binding.dart 284:5
[_handlePersistentFrameCallback]

packages/flutter/src/scheduler/binding.dart 1074:15
[_invokeFrameCallback]

packages/flutter/src/scheduler/binding.dart 1013:9
handleDrawFrame

packages/flutter/src/scheduler/binding.dart 929:5
[_handleDrawFrame]

lib/_engine/engine/window.dart 578:13
_invoke

lib/_engine/engine/window.dart 222:5
invokeOnDrawFrame

lib/_engine/engine.dart 212:18
<fn>

```

```
octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-9.0.pre.73, on Mac OS X 10.15.4 19E287,
    locale fr-FR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.43.2)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by Constans** [comment]
Still happening in v. 1.19.0-0.0.pre with 2 monitors setup.
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale en-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by vlowe85** [comment]
Getting same, im on Flutter 1.19.0-4.2.pre

**Comment by jamesblasco** [comment]
Same when trying to create an image from a widget

```dart
RenderRepaintBoundary boundary = _key.currentContext.findRenderObject();
final image = await boundary.toImage(pixelRatio: pixelRatio);
```
      
It crashes with `pixelRatio` being` 1`, `window.devicePixelRatio`, or others I tried

Flutter 1.20.0-3.0.pre,  -d chrome

**Comment by nicholas-vella** [comment]
This issue is still happening on the latest version in master, running on Chrome
Flutter 1.21.0-10.0.pre.94 • channel master

The exception is thrown on the first rebuild after the window is moved to the new monitor.

**Comment by sergiocasero** [comment]
I can reproduce it on Flutter 1.23.0-18.1.pre • channel beta also

**Comment by PaulHalliday** [comment]
I can confirm that this happens to me with Flutter version 1.23.0-18.1.pre.

**Comment by Drkstr** [comment]
Is there a fix or workaround for this?

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 4.02 Rakshak Raghavan <notifications@github.com> kirjoitti:

**Comment by saaidaat** [comment]
Happens to me too, Flutter version 1.25.0-8.1.pre.

**Comment by ferhatb** [comment]
@Drkstr,@saaidaat  no fix yet, it will take a. bit more time to address this. If you build a release build, you won't see problem. The assertion only shows when you are developing (debug mode) and move app between monitors, thats why we marked P4 for now.

**Comment by jaripekkala** [comment]
This is no longer reproducible for us, after upgrading to Flutter version 2.0.0.

Instead of crashing, now it doesn't rebuild the the app (when pixelDensity changes) leaving the app zoomed in/out (depending on is it moved to or from retina). Resizing the browser window (usually) fixes the issue.

**Comment by yjbanov** [comment]
Closing as the crash is no longer reproducible. The remaining device-pixel ratio issue is tracked in https://github.com/flutter/flutter/issues/77605.
