### ISSUE TITLE
Dart type checking became more strict

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5605]
I have a function
```
double get packedPercent =>
      deadline.totalItems == 0 ? 0 : packedCount / deadline.totalItems;
```

This function used to work fine, even when deadline.totalItems was 0. Now it fails when a type error when deadline.totalItems is 0.

I'm guessing this is because I am returning an int 0 instead of a double 0.0.

I do not get any output from dart analysis related to this, even when using https://raw.githubusercontent.com/flutter/flutter/master/.analysis_options

```
StoreManager: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
StoreManager: The following assertion was thrown building _Deadline:
StoreManager: type 'int' is not a subtype of type 'double' of 'function result' where
StoreManager:   int is from dart:core
StoreManager:   double is from dart:core
StoreManager: Either the assertion indicates an error in the framework itself, or we should provide substantially
StoreManager: more information in this error message to help you determine and fix the underlying cause.
StoreManager: In either case, please report this assertion by filing a bug on GitHub:
StoreManager:   https://github.com/flutter/flutter/issues/new
StoreManager: When the exception was thrown, this was the stack:
StoreManager: #0      _Deadline.packedPercent (lib/routes/dashboard/deadlines.dart:74)
StoreManager: #1      _Deadline.packedPercentAndTimeLeft (lib/routes/dashboard/deadlines.dart:137)
StoreManager: #2      _Deadline.build (lib/routes/dashboard/deadlines.dart:93)
StoreManager: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2027)
StoreManager: #4      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1941)
StoreManager: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2013)
StoreManager: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2008)
StoreManager: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1584)
StoreManager: #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:2780)
StoreManager: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1584)
StoreManager: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:1461)
StoreManager: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2039)
StoreManager: #12     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1941)
...
```

**Comment by eseidelGoogle** [comment]
So this is a recent VM change, which was picked up in a flutter/engine roll.  Is this expected @a-siva?

**Comment by eseidelGoogle** [comment]
CC @pq since the analyzer doesn't warn about this?

**Comment by Hixie** [comment]
Does your .analysis_options file turn on all the type checking?
I'm pretty sure this has never worked before? We've asked for it to work for a while (it's on the Flutter team's "Dart wishlist"), so I'd be surprised if it did work before...

**Comment by pq** [comment]
cc @bwilkerson @jmesserly who may have better insight into the analysis side of things.

**Comment by bwilkerson** [comment]
Was this error produced by running the AOT compiler?

**Comment by jmesserly** [comment]
This is just a checked mode failure. This hasn't ever worked in Dart.

$ cat test.dart
```dart
double get packedPercent => 0;
main() { print(packedPercent); }
```
$ dartanalyzer test.dart
```
Analyzing [test.dart]...
[warning] The return type 'int' is not a 'double', as defined by the method 'packedPercent'. (test.dart, line 1, col 29)
1 warning found.
```
$ dartanalyzer --strong test.dart
```
Analyzing [test.dart]...
[error] The return type 'int' is not a 'double', as defined by the method 'packedPercent'. (test.dart, line 1, col 29)
1 error found.
```
$ dart -c test.dart
```
Unhandled exception:
type 'int' is not a subtype of type 'double' of 'function result' where
  int is from dart:core
  double is from dart:core

#0      packedPercent (test.dart:1:29)
#1      main (test.dart:2:16)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by drewwarren** [comment]
```
void main() {
  print(test(1));
  print(test(2));
  print(test(0));
}

double test(int a) => a == 0 ? 0 : 1 / a;
```

This currently runs on dartpad with no issues and no analyzer warnings. It will fail on the VM flutter uses.

CONSOLE
```
1
0.5
0
```

https://dartpad.dartlang.org/53bd8d3a960c49b0f8f22b80362aec13

**Comment by Hixie** [comment]
dart2js has limitations with respect to how closely it implements dart's rules about numbers, due to JS only having one number type.

**Comment by sethladd** [comment]
Not sure if analyzer knows what to do here, when ternary operator returns either int or double, and the function is marked to return a double. I'd expect an analyzer warning, regardless of later being compiled with dart2js.

cc @bwilkerson ?

**Comment by jmesserly** [comment]
They do not appear to have "checked mode" turned on in dartpad. So type annotations are more or less ignored.

> Not sure if analyzer knows what to do here, when ternary operator returns either int or double, and the function is marked to return a double. I'd expect an analyzer warning, regardless of later being compiled with dart2js.

@sethladd Analyzer knows exactly what to do. It concludes "num", which is then implicitly downcast to "double". All of our modes allow it, if you want to disable downcasts use the recently introduced (in 1.19) --no-implicit-casts flag of strong mode. See:

http://news.dartlang.org/2016/08/dart-119-improved-developer-experiences.html

**Comment by jmesserly** [comment]
Oops I should've linked to the changelog:
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#strong-mode

**Comment by sethladd** [comment]
@jmesserly kk, thanks! (all these modes and options and lints and features are making my head swim)

**Comment by drewwarren** [comment]
```
~$ dart --version
Dart VM version: 1.19.0-dev.5.0 (Wed Aug 10 09:29:58 2016) on "macos_x64"
~$ dartanalyzer --version
dartanalyzer version 1.19.0-dev.5.0~$ 
~$ cat test.dart 
void main() {
 print(test(2));
 print(test(0));
}

double test(int a) => a == 0 ? 0 : 1 / a;
~$ dartanalyzer test.dart 
Analyzing [test.dart]...
No issues found
~$ dartanalyzer --strong test.dart 
Analyzing [test.dart]...
No issues found
~$ dart test.dart 
0.5
0
~$ dart -c test.dart 
0.5
Unhandled exception:
type 'int' is not a subtype of type 'double' of 'function result' where
  int is from dart:core
  double is from dart:core

#0      test (file:///Users/drewwarren/test.dart:6:23)
#1      main (file:///Users/drewwarren/test.dart:3:8)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by jmesserly** [comment]
> @jmesserly kk, thanks! (all these modes and options and lints and features are making my head swim)

yeah no kidding!

If it helps to know, things will get better :). Strong mode will be "the only mode". Things like --no-implicit-casts are ways for us to gracefully introduce stricter checking we think is a good idea, and determine if it can be rolled into strong mode.

**Comment by sethladd** [comment]
Hi! How do we take action on this issue? Is this something for Flutter to do?

cc @floitschG

**Comment by drewwarren** [comment]
I guess this is more of a dart issue, but it was noticed in our application from a flutter engine roll.

The dart bug would be something like
```
double test(int a) => a == 0 ? 0 : 1 / a;
```
Should produce an error in dart analyzer but does not. Calling this function fails when running with `-c`.

**Comment by jmesserly** [comment]
Unfortunately in Dart1 this is not an error, but an implicit downcast :(
This is also true in strong mode, currently. We recently added `--no-implicit-casts` to help.

CC @leafpetersen

**Comment by leafpetersen** [comment]
Yes, this is on long list of small but annoying problems to fix.

https://github.com/dart-lang/sdk/issues/25368

**Comment by floitschG** [comment]
@sethladd: the code is bad since it tries to return an integer where a double was required. If it hasn't been updated yet, it should be.
Once that's done we can close the issue. Tracking of better warnings and detecting these kind of errors earlier is covered in other bugs (such as https://github.com/dart-lang/sdk/issues/25368).

**Comment by sethladd** [comment]
> it tries to return an integer where a double was required

Fair enough. I've asked @drewwarren if we can change the code to return `deadline.totalItems == 0.0 ? 0.0 : ...`

**Comment by sethladd** [comment]
The customer's code has been fixed. They would love if the analyzer can detect if one of the cases of the ternary returns an incorrect type. In the meantime, we can close this issue in favor of https://github.com/dart-lang/sdk/issues/25368
