### ISSUE TITLE
[web] missing library for Firefox for Linux Web Engine

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#56058]
Yesterday, I changed the LUCI recipe and started a local run using led, for testing Firefox on Linux:

https://chromium-swarm.appspot.com/task?d=true&id=4be189dc2fc46210

I received the following error ([logs](https://logs.chromium.org/logs/flutter/led/nurhan_google.com/124971809f3ee2ba61a8393ea4bcccae6d3561f7ffdc12201112170abdef0ebd/+/steps/felt_test/0/stdout)):

```
  Failed to run Firefox: Firefox failed with exit code 255.
  Standard output:
  XPCOMGlueLoad error for file /b/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/firefox/75.0/firefox/libxul.so:
  libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
  Couldn't load XPCOM.
```

When I queried shared object libraries for libxul.so for the Firefox version 75.0, this is the output:

```
>ldd libxul.so
	linux-vdso.so.1 (0x00007fff16321000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f75e4a97000)
	libmozsandbox.so => not found
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f75e4a56000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f75e4a4f000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f75e4a4a000)
	liblgpllibs.so => not found
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f75e48f8000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f75e48c5000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f75e4896000)
	libmozsqlite3.so => not found
	libssl3.so => /usr/lib/x86_64-linux-gnu/libssl3.so (0x00007f75e4838000)
	libmozgtk.so => not found
	libmozwayland.so => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f75e4831000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f75e4826000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f75e46e1000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f75e459f000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f75e4598000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f75e456e000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f75e4569000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f75e455c000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f75e4557000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f75e4542000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f75e4538000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f75e4526000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f75e4519000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f75e4359000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f75e429a000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f75e4254000)
	libdbus-glib-1.so.2 => /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 (0x00007f75e4228000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f75e41d5000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f75e4179000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f75e4054000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f75e402b000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f75e401b000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f75e3ff2000)
	libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f75e3fe6000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f75e3f9b000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f75e3e7b000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f75e3ca9000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f75e3ca4000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f75e3c89000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007f75e3c1e000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f75e3c19000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f75e3a40000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f75e3a26000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f75ec696000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f75e3a1f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f75e3a17000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f75e39de000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f75e39c1000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f75e3994000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f75e3989000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f75e38e1000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f75e38d7000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f75e3863000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f75e385d000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f75e3850000)
	libfribidi.so.0 => /usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f75e3834000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f75e378d000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f75e377e000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f75e371d000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f75e36f2000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f75e36d8000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f75e35d3000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f75e35c8000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f75e35a9000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f75e358f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f75e3565000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f75e3543000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f75e3426000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f75e341c000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f75e33c6000)
	libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f75e3334000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f75e3308000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f75e32e5000)

```

Looks like we need `libdbus-glib-1.so.2`  under driectory `/usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 `

**Comment by nturgut** [comment]
@godofredoc @digiter 

How can I check if `libdbus-glib-1.so.2` is in that location or install it if it is missing? I wasn't able to SSH into this machine. (I was able to SSH into device lab machines though, so this might be a permission issue).

**Comment by godofredoc** [comment]
@keyonghan  can you please take a look at one of the fuchsia Linux VMs and check if the library file is there?

If it is not there let's try to install manually and log the apt install command here to add it to the salt configs.

We may also need to log the VM id to retry with a led command before adding the dependency,

**Comment by digiter** [comment]
The library doesn't exist:
```
ls /usr/lib/x86_64-linux-gnu/libdbus*
ls: cannot access '/usr/lib/x86_64-linux-gnu/libdbus*': No such file or directory
```
I'm examining the firefox installation.

**Comment by digiter** [comment]
Currently web engine [manually](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/firefox_installer.dart) downloads firefox binary from [mozilla](https://download-installer.cdn.mozilla.net/pub/firefox/releases/75.0/linux-x86_64/en-US/). This approach works on the Cirrus image because Ubuntu (I guess) has firefox pre-installed, but fails on these LUCI try bots because Debian doesn't have the dependencies that firefox required.

A short term workaround is to install firefox by `sudo apt install firefox-esr`. That will, as a side effect, install all the required dependencies. However there's a risk that the dependencies may not be the correct versions that the target firefox installed by web engine wants.

The long term solution would be using a package manager. /cc @yjbanov

**Comment by digiter** [comment]
We have got a successful run with the workaround: https://chromium-swarm.appspot.com/task?id=4be5248c90bed910

**Comment by godofredoc** [comment]
I'd suggest to use a self contained binary instead of using apt install. There are two drawbacks on installing directly:

- We will be installing a dependency that is not required for all the bots.
- We won't be able to control the version of the browser.

**Comment by digiter** [comment]
Right, ideally self contained CIPD packages are the best, which fits naturally with LUCI and we can switch target firefox versions. Though that might be hard as firefox has a long list of dependencies:
```
The following NEW packages will be installed:
  firefox-esr i965-va-driver libavcodec57 libavutil55 libcrystalhd3 libdbus-glib-1-2 libgsm1 libjsoncpp1 libmp3lame0 libnuma1 libopus0 libshine3 libsnappy1v5 libsoxr0
  libspeex1 libstartup-notification0 libswresample2 libtheora0 libtwolame0 libva-drm1 libva-x11-1 libva1 libvdpau-va-gl1 libvdpau1 libvpx4 libwavpack1 libwebp6 libwebpmux2
  libx264-148 libx265-95 libxcb-util0 libxvidcore4 libzvbi-common libzvbi0 mesa-va-drivers mesa-vdpau-drivers va-driver-all vdpau-driver-all
```

There're other self contained approaches like FlatPak and Snappy. They may have limitations on features, e.g. native messaging and performance.

**Comment by digiter** [comment]
Defer to @nturgut and @yjbanov on which approach to take, in the mean time I just have installed firefox-esr and unblocked the recipe development.

**Comment by nturgut** [comment]
Thanks a lot for your help.

Our test code is configured to work on a locked version of a browser: https://github.com/flutter/engine/blob/master/lib/web_ui/dev/browser_lock.yaml

Also we can use `system` or `latest` parameters to use the installed system browser or to download and install the  latest version of a browser.

For now, I can change the felt code to use the existing firefox version. I think we can still also use our download/install/delete code as we were using in cirrus now the libraries are updated.

For the future, I think the best approach is the browser to be kept as a cipd package but we also have a way of updating the version time to time. If we call web_installers repo from the recipe and upload firefox to a cipd package I think that would be the ideal solution. (@yjbanov is working on a long term solution luci.dart which might help us to handle these type of dependencies better.)

We already have some reusable code in [webinstallers to download drivers](https://github.com/flutter/web_installers/tree/master/packages/web_drivers). We were already planning to add web browsers here. For example can we call such a command in the recipe and save the browser as a cipd package:
```
dart browser_installers browser=chrome version=72.0
```

**Comment by yjbanov** [comment]
@digiter @nturgut feel free to close if/when this is done.

**Comment by digiter** [comment]
> For example can we call such a command in the recipe and save the downloaded browser as a cipd package?

Like I said in https://github.com/flutter/flutter/issues/56058#issuecomment-622048741, I think it's non-trivial to create a self-contained CIPD package for Firefox as it has many dependencies.

@yjbanov Which approach do you think we should move forward with? Or do you have other suggestions?

**Comment by godofredoc** [comment]
Is is possible to use fixed versions of the firefox dependencies? the website binaries are not distribution specific and using different version can get broken very easily

**Comment by nturgut** [comment]
@godofredoc Using a fixed firefox version is ok for us, as long as we can change it once in a while (for example every quarter).

@digiter is there an ETA on the issue? Is there anything I can do to help?

**Comment by digiter** [comment]
The short term workaround has been submitted in http://tqr/203259. We are waiting for the deployment.

**Comment by yjbanov** [comment]
Ubuntu in a virtual box/docker might also work, if that makes things easier to update later.

**Comment by nturgut** [comment]
@digiter do you think we can retry again? Is there a way we can check if the fix is deployed?

**Comment by digiter** [comment]
We are waiting for Fuchsia infra team to deploy the change, tracking bug: http://fxb/51732. We can retry after the deployment.

**Comment by godofredoc** [comment]
@nturgut the changes to support firefox got deployed can you please retry your firefox tests?

**Comment by nturgut** [comment]
I'll resend the change for enabling firefox!

**Comment by nturgut** [comment]
I prepared the recipe change but I'm still getting the same library errors for running firefox:

https://chromium-swarm.appspot.com/task?id=4c2de4c8a2fae510
https://chromium-swarm.appspot.com/task?id=4c2dc774445c0210

**Comment by godofredoc** [comment]
I just pinged fuchsia infra team, they'll need to update the VMs. I'll update this bug when ready

**Comment by godofredoc** [comment]
Can we retry?

**Comment by digiter** [comment]
The deployment takes ~1 day, so we can retry today.

**Comment by digiter** [comment]
Actually, I will double check the bots and ping this thread when they are ready.

**Comment by nturgut** [comment]
@digiter I run another trial run today. I still got the same error: https://chromium-swarm.appspot.com/task?id=4c424ae4a7ec1410

**Comment by digiter** [comment]
This is blocked by http://fxb/51732.

**Comment by digiter** [comment]
The deployment is done, I have verified that. @nturgut can retry your change.

**Comment by nturgut** [comment]
Thanks! I tested it today, it works. I sent out the recipe change.

**Comment by nturgut** [comment]
Closing the issue, confirmed that firefox is working now with recipe change. The links for example runs and the recipe change: https://flutter-review.googlesource.com/c/recipes/+/2920
