### ISSUE TITLE
Add obfuscation option to flutter build aar also

### ISSUE THREAD

**Issue by xster** [flutter/flutter#56068]
https://github.com/flutter/flutter/pull/50509 missed build_aar :)

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
should build aar have this? What is it for?

**Comment by jonahwilliams** [comment]
i.e. I though aar was for producing testing artifacts, and the actual build would be done separately

**Comment by xster** [comment]
I meant the dart obfuscation flag you added (awesome feature btw) is equally useful for APKs as it is for AARs. It's an Android library. For library developers, that's sometimes the final shipping artifacts (to be consumed by other companies that they don't want to share "source" with).

**Comment by jonahwilliams** [comment]
Oh okay, I thought that was only for testing artifacts

**Comment by jonahwilliams** [comment]
The build_aar command would need to be refactored to get the buildInfo from the flutter command instead of manually constructing it. I don't have time to look at this right now, but I could advise someone else that wanted to take a look

**Comment by xster** [comment]
(I don't know what's the best way to test) but can't it just do https://github.com/flutter/flutter/pull/56069?

**Comment by jmagman** [comment]
I can look at this.

**Comment by jmagman** [comment]
Should plugins also be obfuscated?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L773-L775

**Comment by jonahwilliams** [comment]
Dart doesn't support any sort of separate compilation, so any plugin dart code would be compiled into libapp.so in the main AAR and obfuscated. I think (but @blasten would need to confirm) that this is only building the Java side of things
