### ISSUE TITLE
[web]: Image color fill not working

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#56071]
This is the basic use case we're trying to support:
Image.asset("assets/image.png", color: Colors.red)
Where image is pure white

Actual:
![Screen Shot 2020-04-30 at 12 38 45 PM](https://user-images.githubusercontent.com/56849473/80752162-e7d41f00-8adf-11ea-9e89-ba363ba0cca8.png)

Expected(with gray color):
<img width="109" alt="Screen Shot 2020-04-30 at 12 38 57 PM" src="https://user-images.githubusercontent.com/56849473/80752187-eefb2d00-8adf-11ea-9532-2f2c94535c71.png">

**Comment by yjbanov** [comment]
I only added `web_canvaskit` to see if we're wiring up the parameter. The problem might be limited to HTML only.

**Comment by mariamhas** [comment]
you're right i don't see this on the canvas-kit version of the app, its only with HTML

**Comment by yjbanov** [comment]
Thanks for checking. Removed canvaskit label.

**Comment by esDotDev** [comment]
At a lower level this is throwing an UnimplementedError: 
```
ColorFiltered(
    colorFilter: ColorFilter.mode(Colors.red, BlendMode.srcIn),
    child: Image.asset("assets/icons/icon-add.png"),
)
```

**Comment by ferhatb** [comment]
Workaround: create 2 versions of image.
Note: Might be possible by using webgl imagedata for non-network assets or SVG filters if major browsers support the filter.

**Comment by esDotDev** [comment]
Problem is we have like 8 themes we want to support. And this color-tinting implementation is already baked through the entire app in about 30 places. 

All images are local fwiw. We can switch to ColorFiltered() quickly if it makes it any easier.

**Comment by ferhatb** [comment]
@esDotDev @mariamhas : PR in flight, should land shortly in master.

Web, Native:
![Screen Shot 2020-05-03 at 11 17 59 AM](https://user-images.githubusercontent.com/5061034/80922202-4263ba00-8d30-11ea-9d23-caa3ae843b95.png)

**Comment by ferhatb** [comment]
Landed in master
