### ISSUE TITLE
DataTable should incorporate Theming

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#56079]
Following up on these two To-Dos:

https://github.com/flutter/flutter/blob/368da5bb5962db7be40439f416bd12176e2b3abf/packages/flutter/lib/src/material/data_table.dart#L546

https://github.com/flutter/flutter/blob/368da5bb5962db7be40439f416bd12176e2b3abf/packages/flutter/lib/src/material/data_table.dart#L599

By default the table's colors and text styles should be configured in terms of the Theme's colorScheme and textTheme. There shouldn't be brightness-specific code here or hardwired colors, etc. Additionally, there should be a DataTableTheme, so that one can configure the appearance of tables in general.

**Comment by n1k3sh** [comment]
@Piinks can you help with this feature request https://github.com/flutter/flutter/issues/49767

**Comment by Ahmadre** [comment]
### Before
![before](https://user-images.githubusercontent.com/18512224/86316071-272c0280-bc2c-11ea-8d86-2e455bb4d181.PNG)

### After
![after](https://user-images.githubusercontent.com/18512224/86316070-25fad580-bc2c-11ea-8167-216a5aa9f12a.PNG)

### Usage:
```dart
    return DataRow.byIndex(
      index: index,
      decoration: (index % 2) == 0 ? oddBoxDecoration : evenBoxDecoration,
```

### data_table.dart

*Iterating through rows*
```dart
final List<TableRow> tableRows = List<TableRow>.generate(
      rows.length + 1, // the +1 is for the header row
      (int index) {
        final rowDecoration = index > 0 && rows[index - 1].decoration != null
            ? rows[index - 1].decoration
            : _kUnselectedDecoration;

        return TableRow(
          key: index == 0 ? _headingRowKey : rows[index - 1].key,
          decoration: index > 0 && rows[index - 1].selected
              ? _kSelectedDecoration
              : rowDecoration,
          children: List<Widget>(tableColumns.length),
        );
      },
    );
```

I just added BoxDecoration to DataRow and DataRow.byIndex and that's it. Can't we integrate this at first?

**Comment by perclasson** [comment]
@Ahmadre Thanks for you contribution. I am currently working on this problem and you can find the [design doc](https://docs.google.com/document/d/1g0jfWkk3ezFZr35ObIjiHttjyXlNWh6pseidLWy7xcA/edit?usp=sharing) for this change here.

I see that you already got started on a PR as well. In the future, to avoid duplicate work in the future, you can see if an issue is assigned and if not assign it to yourself. :)

You can view my [in progress PR](https://github.com/flutter/flutter/pull/60764) of a similar change here, please let me know if you have any feedback as well.

**Comment by Ahmadre** [comment]
thanks @perclasson! I will track that pr

**Comment by giorgio79** [comment]
Thanks @perclasson 
With this update, will we be able to theme datatable rows like cards? :)

**Comment by perclasson** [comment]
@giorgio79 Not exactly, you can see the PR https://github.com/flutter/flutter/pull/64316 for what will be added!

**Comment by tsinis** [comment]
Just my two cents: DataTable does not respect font colors in CupertinoApp, when dark theme is used. Here is a simple code: 
https://dartpad.dev/501d270700d5544d2292d509b86f79af
DataTable should be Material independent IMHO.

**Comment by tsinis** [comment]
> > Just my two cents: DataTable does not respect font colors in CupertinoApp, when dark theme is used. Here is a simple code:
> 
> > https://dartpad.dev/501d270700d5544d2292d509b86f79af
> 
> > DataTable should be Material independent IMHO.
> 
> 
> 
> To solve your problem you can wrap the Material with `Theme(data: ThemeData.dark(), child: MyStatelessWidget())`.
> 
> 

Yep I know, but it's not perfect solution, when I have an app with dynamic theming and Material/Cupertino design switch...
