### ISSUE TITLE
Fix org.domokit.sky.shell.SkyApplication

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#5608]
## Steps to Reproduce

```
flutter create superduper
```

Look at `android/AndroidManifest.xml`. Notice the text that says:

```
    <application android:name="org.domokit.sky.shell.SkyApplication" android:label="superduper" android:icon="@mipmap/ic_launcher">
        <activity android:name="org.domokit.sky.shell.SkyActivity"
 ```

Since the flutter repo no longer has any relationship to domokit and the name Sky is no longer used, it's probably time to update the package name.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 852a00a17b (2 hours ago), 2016-08-25 14:23:13
    • Engine revision c4022b61fa
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-128173541-128170350)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.31

**Comment by eseidelGoogle** [comment]
We're very close to removing these entirely.  We're just waiting on one more internal customer to move off of them.  See https://github.com/flutter/flutter/issues/5489
