### ISSUE TITLE
TextField should incorporate Theming

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#56082]
Following up on an old To-Do regarding cursorColor:

https://github.com/flutter/flutter/blob/368da5bb5962db7be40439f416bd12176e2b3abf/packages/flutter/lib/src/material/theme_data.dart#L310

The Material spec doesn't provide specific guidance about the cursor color and the examples aren't entirely consistent - https://material.io/components/text-field. In most cases the examples use the primary or error color, depending on the TextField's stat. That said, the default is clearly wrong and shouldn't be specified here. We need a TextFieldTheme per flutter.dev/go/material-theme-system-updates (see "Component Theme Normalization") and, similarly, TextField should be responsible for computing the default cursor color.

**Comment by HansMuller** [comment]
It looks like the default cursor color should match the color of the InputDecorator's outline or underline. That stroke color can depend on the TextField's enabled/disabled/focused/error state.

Hoping to get an official ruling about this from the Material Design team.

CC @willlarche @johnsonmh

**Comment by johnsonmh** [comment]
@HansMuller I can confirm that the default color of the cursor should match the color of the outline or underline border!

**Comment by jpc-ae** [comment]
This seems related to #54776, as the outline/underline currently uses the same colors as material buttons.

**Comment by jpc-ae** [comment]
Here are some more issues that seem related: #37690, #26870 and #12681.

Regarding this TODO, my understanding is a new TextFieldStyle class should be implemented that includes cusorColor, along with separate widgets and themes for [the two styles of material text fields](https://material.io/components/text-fields): FilledTextField & FilledTextFieldTheme and OutlineTextField & OutlineTextFieldTheme, based on the [default](https://material.io/develop/android/components/text-fields/) and [Cupertino](https://material.io/develop/ios/components/textfields/) specs.

One additional note for any redesign is that the cursor should be drawn beneath the placeholder text (see issue #39466). Are PRs welcome on these (whether I should try working on them myself)?

**Comment by kw2019ltd** [comment]
when fix

**Comment by darrenaustin** [comment]
Between the new `TextSelectionTheme` and the `InputDecorationTheme`, I think most aspects of the text fields can be controlled by themes. Please open separate issues if something is missing.

**Comment by Piinks** [comment]
Closing per last comment, thanks @darrenaustin!
