### ISSUE TITLE
New version of Flutter causes unnecessary call to setState  after routing to new widget.

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#56087]
This one took me some time to figure out what is going on. There is no log error for this. I am using flutter-redux in my application with the redux lifecycle hooks. (I will file a bug report in the github for that package too if this change to the flutter engine is intentional). 

In my onDidChange lifecycle hook which mirrors Flutters didChangeDependencies lifecycle hook, I navigated to a new page once data in the new state was changed from false to true. This worked fine in previous versions of Flutter. However in the new one, it forces the new page into an infinite loop and breaks the app. 

After investigating why this is occurring and printing the value of the new state, I saw that not only does the new state return true in the widget in which I changed the state, but for some reason, when I navigate to another widget, I get the state updating for a second time returning true when that next widget loads. The only explanation I can come up with for this is: 

If there is an unnecessary rerender of the old widget while routing to the new widget because routing to a new widget should not effect the state changed in the old widget. 

I get the following logs while printing my state where the left is the old state and the right is the new state

flutter: false false               | Initial state of the application with original widget loaded. Old state and new state are false -- this is expected behavior as I did not change the state yet

flutter: false true                | After clicking button to change state in original widget. Old state is false and new state is true -- this is expected behavior as the state has successfully updated

flutter: true true                | After routing to new widget, a newer state is updated again from old widget causing infinite loop because the newer state is set to true. -- this is unexpected behavior as I only set the state to true in the previous widget

This only happened after updating to the new version of Flutter and was working fine just yesterday. My Flutter Doctor:

```
[✓] Flutter (Channel master, 1.18.0-9.0.pre.73, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.18.0-9.0.pre.73 at /Users/Khari/Documents/Dev_Projects/flutter
    • Framework revision bd6ccb606a (23 hours ago), 2020-04-29 16:31:42 -0700
    • Engine revision 2db3276573
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 726d3c7725)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/Khari/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/Khari/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Khari/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

 
[✓] Connected device (3 available)            
    • iPhone 11 Pro Max • FAFB4B6E-D712-4D1C-8A74-C5CFE4D56A54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server        • web-server                           • web-javascript • Flutter Tools
    • Chrome            • chrome                               • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

I will try and make a sample application with this error to prove that it is a problem in the Flutter Engine and not with the redux package. Unfortunately, because my application is so large, I can only describe the error coming from a redux lifecycle hook but my code in this hook has not changed for months and it worked with no problem.

**Comment by khari998** [comment]
Okay I can confirm there is no additional invocation from my onPressed button where the state is manipulated. I ran a print statement in my onPressed and only got it once.

When I ran a print statement in onDidChange and onWillChange from the flutter_redux package, I got an infinite loop after routing. So somehow the routing is causing an additional state update in redux. Still trying to identify the source of this error since I only updated state once in my original widget. I believe some change to the engine may be causing this but I cannot say for certain yet. I will reach out to the author of the package to see if it can be changed to work with the newest version of Flutter

**Comment by khari998** [comment]
Okay this boolean setting is for my login/logout logic. When I logout, I set the value to false. I tried testing my logic for setting the value to false and for some reason, when I print this value, it is set to false multiple times. So routing logic depends on manipulating the state value once and for some reason routing is causing the state to update multiple times, causing an insane amount of rerendering of the widget I'm routing to. 

If I were to guess, there was probably something done in the setState logic of the engine because redux calls that in setting its state and this probably caused the package to break which in turn caused my entire application to have ridiculous rerenders when I only update state one time on an OnPressed button click.

**Comment by jonahwilliams** [comment]
I don't quite know that this is URGENT, is it? 😄 

In general flutter does not guarantee that it will call build a minimum number of times. That said, we might be able to figure out if this is an easy fix, but that would require a sample that reproduces the issue

**Comment by khari998** [comment]
> I don't quite know that this is URGENT, is it? 😄
> 
> In general flutter does not guarantee that it will call build a minimum number of times. That said, we might be able to figure out if this is an easy fix, but that would require a sample that reproduces the issue

It may not be urgent. I just saw the new update give my application an infinite boot loop and thought this might be more of a widespread problem than it is. But this is definitely messing things up for the client I am building this for haha. 

I can confirm its not the redux package because I am using the same one that has been published from back in December. 

What is most likely the culprit is that setState is being called to update the state with the current values already in the state in whatever widgets access the state. Because its taking the same values and reinstantiating them.

I will work on making a sample app that reproduces this. I just need to determine if this is a problem because of how the redux package uses setState behind the scenes that is now incompatible with the new version of Flutter or if its a deeper problem within the Flutter engine itself

**Comment by jonahwilliams** [comment]
I hear you, crashing is never good! I just don't know how much we can help without a way to reproduce the issue. You can always use a prior version of flutter while you do this.

**Comment by khari998** [comment]
Okay I think I finally have an error to work with. For some reason I keep getting this back. Whenever I try routing to any named route in my app. 

As suspected before, for some reason, setState is being called whenever I route to another widget. Im not using redux lifecycle hooks to navigate now, I am simply doing a 

Navigator.of(context).pushNamed(Search.route);  within an onPressed function. 

I'll see if I have this problems in previous versions of Flutter. I was still experiencing issues when switching to previous versions before for some reason.

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3581 pos 12: '!_debugLocked':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

**Comment by khari998** [comment]
Okay so I'm currently getting this error on every previous version of Flutter which means its related to a file that is not erased when changing versions of Flutter. It seems like after the upgrade to the latest version, the broken code is still sticking around even when going all the way back to the latest stable version 1.16.3. 

All I'm doing is a simple route. I'm locked out of my application now. I'm going to see if I can reproduce this with a sample app because this is crazy.

**Comment by khari998** [comment]
Okay I'm closing this because I figured out a workaround. I'll open the task in a new issue because its unrelated to the Flutter update
