### ISSUE TITLE
Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli

### ISSUE THREAD

**Issue by atheistrepublic** [flutter/flutter#56117]
Hi i am trying to install flutter and getting an error when i type sdkmanager --list in the command prompt .I have added the environment variables correctly.I am attaching the screenshots that shows this problem and also the environment variables i am using and my directory structure.I am trying to install command line tools only and not android studio.How can i solve this error?
![Screenshot (5251)](https://user-images.githubusercontent.com/58817288/80802356-b1280280-8bcc-11ea-9fdf-46a41673512f.png)
![Screenshot (5252)](https://user-images.githubusercontent.com/58817288/80802359-b2f1c600-8bcc-11ea-876c-d92576c00c93.png)
![Screenshot (5253)](https://user-images.githubusercontent.com/58817288/80802365-b4bb8980-8bcc-11ea-8fe3-c32504414724.png)
![Screenshot (5254)](https://user-images.githubusercontent.com/58817288/80802367-b5542000-8bcc-11ea-90aa-13cf97d848ec.png)

**Comment by iapicca** [comment]
Hi @atheistrepublic 
please double check your configuration with the [docs](https://flutter.dev/docs/get-started/install/windows#update-your-path)
and provide your `flutter doctor -v ` (you may use `..\flutter\bin\flutter.bat`)
Thank you

**Comment by atheistrepublic** [comment]
In ubuntu i solved it by using older version of sdk tools.It seems there was some bug on newer version of command line tools zip file.

**Comment by iapicca** [comment]
HI @atheistrepublic 
did the solution you mentioned in your last message solved the issue?
If it didn't could you please provide the information mentioned [above](https://github.com/flutter/flutter/issues/56117#issuecomment-623377059)
Thank you

**Comment by iamvitaminx** [comment]
I got this issue also. Then I found [this](http://danlec.com/st4k#questions/27364963) solution. This is probably not a problem with the settings of Java or sdk tools.

> Solution:
Don't use the Windows' embedded unzip tool. Switch to another, like 7z.
The directory will then be referenced correctly, and you can run sdkmanager.bat without errors.

**Comment by shad-1** [comment]
Using 7zip instead worked for me. 
After unzipping, I ran `sdkmanager --android-licenses` in terminal and replied `y` to confirm every update.
