### ISSUE TITLE
iOS back gesture: shadows too strong when close to screen right

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5611]
In the below screenshots, check out the shadows when the view is about to exit screen right.

On iOS, the shadow is barely there when close to the right, but the shadow will darken as the view moves to the left. On Flutter, we see a consistent shadow strength.

Flutter: 

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/18011516/64986a76-6b6a-11e6-849f-533350d29b34.png)

iOS:

![_no_subject__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/18011548/85aec66a-6b6a-11e6-8026-f4d216be447f.png)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by Hixie** [comment]
The iOS behaviour here doesn't make sense. Based on that screenshot, it looks like the page being scrolled in is about to hit that switch!

**Comment by sethladd** [comment]
I just take the screenshots as I see 'em :)

**Comment by abarth** [comment]
Apple apps on iOS don't play by the material design rules for physicality.  We should either pick something that's consistent with material design (e.g., having the entering content floating above the existing content to avoid collisions) or ask the designers to help us get the effect correct w.r.t. adapting material concepts to iOS idioms.

**Comment by sethladd** [comment]
Yeah, good point. I'll close this for now.
