### ISSUE TITLE
MultiDex app has stopped.

### ISSUE THREAD

**Issue by emmanuel39hanks** [flutter/flutter#56112]
I am trying to create a Flutter Application.
i ran flutter create and i created a Flutter app, i added firebase dependencies and as soon as i did that the app crashed and gave out the MultiDex error
i enabled multidex

defaultConfig {
       ............
        multiDexEnabled true
    }

and implemented it as a dependency but the app this times builds and just crushes
implementation 'com.android.support:multidex:$multidex_version'

my flutter is working just fine and when i run flutter doctor -v

i get:

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.592], locale en-ZM)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\conrad\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = C:\Users\conrad\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\conrad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • SM G720N0 • 958f5534      • android-arm • Android 4.4.4 (API 19)
    • SM N971N  • emulator-5554 • android-x86 • Android 7.1.2 (API 25)

• No issues found!

Please i really need a solution.

**Comment by empratyush** [comment]
i think flutter uses  io.flutter.app.FlutterApplication as  android.app.Application i don't is it best possible way or not but try this create a class in your package and extend it FlutterApplication and than init multidex on on create just like in this

```
package com.your.packageName;

import io.flutter.app.FlutterApplication;

public class App extends FlutterApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        Multidex.install(this);
    }
}

```

also you have to edit your manifest application name tag just like this

```
  <application
        android:name="com.yourapp.packageName.App"
```

Hopefully it's help.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
