### ISSUE TITLE
I am getting this error even though my widget is inside the widget tree.Help me out please.

### ISSUE THREAD

**Issue by HItzz07** [flutter/flutter#56113]
The following assertion was thrown while handling a gesture:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
`Provider.of<TaskData>(context, listen: false);`

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: AddTaskScreen
```bash
package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate
```

**Comment by Khane1** [comment]
That's the same thing i'm experiencing could it be a problem with the update?

**Comment by Khane1** [comment]
Try making the listener =false

**Comment by HItzz07** [comment]
If i do so , then the functionality will not work .
Anyways i solved my problem just by using the older version of provider package , something 3.xx version.
Hope it helps

**Comment by iapicca** [comment]
Hi @HItzz07 
[provider](https://pub.dev/packages/provider) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/rrousselGit/provider/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
