### ISSUE TITLE
[fuchsia_ctl] Add pre-submit testing

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#56138]
To improve the stability of [fuchsia_ctl](https://github.com/flutter/packages/tree/master/packages/fuchsia_ctl), we plan to add pre-submit testing. We will add a new recipe that builds and uploads fuchsia_ctl CIPD package (without tagging), then triggers the [Linux Fuchsia](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia) builder to run with the new version of fuchsia_ctl CIPD package.

This is a sub task of FlutterFuchsiaImprovements.

**Comment by digiter** [comment]
The next step is adding a webhook (https://flutter-dashboard.appspot.com/api/github-webhook-pullrequest) to the https://github.com/flutter/packages repo.

@godofredoc can you help with that? I don't have the permission.

**Comment by godofredoc** [comment]
I don't have permissions to that repo we'll need to ask @kf6gpe for help.

**Comment by digiter** [comment]
@kf6gpe Hi Ray, could you help us add a webhook (https://flutter-dashboard.appspot.com/api/github-webhook-pullrequest) to the https://github.com/flutter/packages repo?

**Comment by godofredoc** [comment]
Ray helped us to update the webhook yesterday.

**Comment by digiter** [comment]
A successful run end to end: https://ci.chromium.org/p/flutter/builders/try/fuchsia_ctl/4
