### ISSUE TITLE
 Could not resolve all artifacts for configuration ':sqflite:classpath'.

### ISSUE THREAD

**Issue by Ayman-Tarig** [flutter/flutter#56169]
I download flutter sqflite package, when i try to run the app it gives the following error

```
* What went wrong:
A problem occurred configuring project ':sqflite'.
> Could not resolve all artifacts for configuration ':sqflite:classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.4.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.0/builder-3.4.0.jar
> Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

```

the output of `flutter doctor -v` is:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ayman\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\ayman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\ayman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.0

[√] Connected device (1 available)
    • TECNO WX3 • 02691097BC005862 • android-arm • Android 7.0 (API 24)

• No issues found!
```

My build.gradle file

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

What I already try:
1- add mavenCentral() to build.gradle
2- add maven { url "https://maven.google.com" } to build.gradle
3- flutter clean then flutter run -v
4- gradle cleanBuildCache then flutter run -v

none of the above works so i reset build.gradle to it's default.

**Comment by TahaTesser** [comment]
Hi @Ayman-Tarig 
For issue related to the 3rd party plugin [sqflite](https://pub.dev/packages/sqflitee) you may want to open an issue in the dedicated [github](https://github.com/tekartik/sqflite/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by Theeyecode** [comment]
I'm having the same issue too..

A problem occurred configuring project ':sqflite'.
> Could not resolve all artifacts for configuration ':sqflite:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.4.0.
     Required by:
         project :sqflite
      > Could not resolve com.android.tools.build:gradle:3.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.0/gradle-3.4.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.0/gradle-3.4.0.pom'.
               > dl.google.com
      > Could not resolve com.android.tools.build:gradle:3.4.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.0/gradle-3.4.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.0/gradle-3.4.0.pom'.
               > jcenter.bintray.com
> Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.

**Comment by besttahervaezi** [comment]
me too
> Could not resolve all artifacts for configuration ':sqflite:classpath'.
   > Could not find com.android.tools.build:gradle:4.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.1.0/gradle-4.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.1.0/gradle-4.1.0.jar
       - https://jcenter.bintray.com/com/android/tools/build/gradle/4.1.0/gradle-4.1.0.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/4.1.0/gradle-4.1.0.jar
     Required by:
         project :sqflite
> Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
