### ISSUE TITLE
LayoutBuilder is incompatible with GlobalKey reparenting right now

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5616]
Consider two LayoutBuilders each with a KeyedSubtree child which, in one frame, switch their keys around. (This isn't academic, heroes can trigger something similar during navigation.)

Right now, this will assert because one of the layout builders will try to modify the other layout builder's subtree at layout time when that second one not being laid out (though it is guaranteed that it won't have been laid out yet and is still dirty).

We should probably allow any dirty node to be modified, not just if it's currently being built.

**Comment by Hixie** [comment]
@abarth you might find this bug amusing.

**Comment by abarth** [comment]
I don't fully understand, but I can believe we get confused here.
