### ISSUE TITLE
TextField animation issue on IOS

### ISSUE THREAD

**Issue by kokocooler2020** [flutter/flutter#56175]
I put an TextField at the bottom of the screen, When I click it,  it will move directly to the position suitable for the InputMethod, No Animation, but the InputMethod has animation, so, there will be a blank space between the TextField and the InputMethod.

**Comment by kokocooler2020** [comment]
Until the InputMethod animation is completed.

**Comment by imeDevelopers** [comment]
@kokocooler2020 
Provide screen shot or some code ..

**Comment by TahaTesser** [comment]
Hi @kokocooler2020 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
