### ISSUE TITLE
buttonColor is invalid in ThemeData constructor

### ISSUE THREAD

**Issue by teaphy** [flutter/flutter#56171]
When using the ThemeData constructor to create a ThemeData instance, although the buttonColor is passed in, the parameter is not used in the constructor body, but takes the value of PrimarySwatch [600] or Colors.grey [300]. Is buttonColor an invalid parameter?

buttonColor ??= isDark ? primarySwatch[600] : Colors.grey[300];

**Comment by TahaTesser** [comment]
Hi 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by teaphy** [comment]
Thanks @TahaTesse.When I upgrade Flutter 1.17.0，I test again and see the resource code.I known buttonColor is just ussed for RaisedButton。It's perfectly worked.
