### ISSUE TITLE
Error while installing and running command prompt

### ISSUE THREAD

**Issue by PartapSBimrah** [flutter/flutter#56184]
I have an error while running the command line to check it install whether not. Then I got this error. Please let me know how to fix this. I mean to see the screenshot and check the **X** marked (Red). I have upgraded the Android studio and installed an emulator but I have a concern about the red marked issue in the screenshot. 
![Screenshot (160)](https://user-images.githubusercontent.com/39325207/80860279-3f12f480-8c84-11ea-9292-92f67bd7b38a.png)

**Comment by timsneath** [comment]
Have you followed the instructions in the yellow box here? 
https://flutter.dev/docs/get-started/install/windows#install-android-studio

**Comment by PartapSBimrah** [comment]
For your kind information I have already followed this instruction but as the result same. Now what I need to do

**Comment by timsneath** [comment]
Can you upload a screenshot of that dialog showing which versions you have installed? 

What does `flutter doctor --android-licenses` report?

**Comment by PartapSBimrah** [comment]
Hey, You can see the screenshot below. And nothing happens

![Screenshot (162)](https://user-images.githubusercontent.com/39325207/80915478-34358e00-8d70-11ea-8277-83e51c20249c.png)

**Comment by TahaTesser** [comment]
Hi @PartapSBimrah 
Can you please make your Android SDK tools installed properly in Android Studio? 
If not, Please check this [solutiom](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)
Thank you

**Comment by PartapSBimrah** [comment]
Brother, I have done all these things and installed the latest SDK and Studio as well. Also installed the Android SDK Tools (obsolete). But as a result same.

**Comment by iapicca** [comment]
Hi @PartapSBimrah 
given this [answer](https://github.com/flutter/flutter/pull/51980#issuecomment-606152832) you may want to run 
```console
flutter channel dev
flutter upgrade --force
```
let me know if the issue persist
Thank you

**Comment by PartapSBimrah** [comment]
It doesn't work you can see the screenshots below. If you have any solid solution then please let me know whether to wait till the solution.
![Screenshot (163)](https://user-images.githubusercontent.com/39325207/80973869-8e505500-8e3d-11ea-9bb5-debb135f0fd3.png)
![Screenshot (164)](https://user-images.githubusercontent.com/39325207/80973873-901a1880-8e3d-11ea-80e3-1f1820d0b742.png)

**Comment by TahaTesser** [comment]
Hi @PartapSBimrah 
I see that you have to switched `dev` channel and it is downloading files.
Can you please make sure you've Android SDK tools is installed from Android  Studio and  run `flutter doctor -v` and  accept  licenses using `flutter doctor --android-licenses` 
Thank you

**Comment by PartapSBimrah** [comment]
Leave this error you can't be sorted out. Please. You can close. But you didn't happy me due to this error.

**Comment by imeDevelopers** [comment]
The problem here is that you didn't accepted the android sdk agreements & terms , etc ..

Just open you android studio and try to install build tool and and android version and accept the agreements..  from android sdk , for example android api 28 ..

**Comment by iapicca** [comment]
Hi @PartapSBimrah 
you may want to follow this [solution](https://github.com/flutter/flutter/issues/56184#issuecomment-623401968) to fix the error in the doctor
Please refrain from posting pictures if not necessary.
Thank you

**Comment by PartapSBimrah** [comment]
@imeDevelopers I have already done that in Android Studio Now how many API I would need to install.

@iapicca okay I will do that

**Comment by PartapSBimrah** [comment]
I had been re-installed the Android Studio and Flutter plugin. Now everything is good and working fine. I want to close this issue.
