### ISSUE TITLE
Buffer swapping stall causes missed frames on Android.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5618]
Working on a more complex layout involving a `ClipOval` widget, I've noticed a bug where swapping buffers is stalled for ~28ms for a few frames.

I haven't yet minimized the input that causes the problem. What I currently know is that the issue only happens on Android.

![screen shot 2016-08-26 at 12 01 12 pm](https://cloud.githubusercontent.com/assets/4136413/18017128/d136c71c-6b84-11e6-9b7f-ec0d5f9e69b8.png)

**Comment by eseidelGoogle** [comment]
Is this on specific hardware?

**Comment by dragostis** [comment]
@eseidelGoogle The bug was present on both Adreno and Mali GPUS.

**Comment by sethladd** [comment]
Thanks for filing!

**Comment by Hixie** [comment]
Without more (e.g. code) this is not actionable.
