### ISSUE TITLE
Android_alarm_manager gets MissingPluginException when calling for platform channels in callback function

### ISSUE THREAD

**Issue by harsha-sira** [flutter/flutter#56186]
In my application, I want to call for platform-specific platform channels in the alarm manager callback function. but it gives me below exception

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method foregroundService on channel samples.flutter.io/service)`

but **platform channels works fine if I call directly**. But fails when calling in callback function

`flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /usr/lib/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/lib/jdk1.8.0_211/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)
```

Is there any limitation when calling platform channels inside the callback function?
Is there anything we need to change when calling platform channels inside callback?

Appreciate your help on this. 

Sample code I was working can be accessed [here](https://github.com/harsha-sira/flutter/tree/dev-java/flutter_java_version ) 

Found similar sort of question [here](https://stackoverflow.com/questions/57599044/calling-platform-specific-method-in-alarmmanager), but no answer for that one as well

**Comment by TahaTesser** [comment]
Hi @harsha-sira 
You cannot platform channel from another isolate yet  [#13937](https://github.com/flutter/flutter/issues/13937)
Closing as this isn't an issue with `android_alarm_manager`
Thank you
