### ISSUE TITLE
[web] HtmlElementView has no onPlatformViewCreated

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#56181]
`HtmlElementView` has no `onPlatformViewCreated` callback. This callback is primarily important to learn the `viewId` of the created view, for instance, to open the platform channel. The underlying code has its own callback in place but the call doesn't get propagated to the upper level.

**Comment by deakjahn** [comment]
I went on with my code and realized that the problem is deeper than just asking for a new feature. The fact the there is no callback on creation means that there is no place to call any initialization from. When I create a new `HtmlElementView`, it's still premature to call any initialization because the actual `PlatformViewLink` isn't yet created, it will only come later in the `build()`, thus I can't find it in the DOM yet at that moment. This practically makes it rather complicated to properly set up a `PlatformView` in Flutter Web.

**Comment by deakjahn** [comment]
The optimal solution would be as simple as:

    class HtmlElementView extends StatelessWidget {
      final String viewType;
      final PlatformViewCreatedCallback onPlatformViewCreated;
      final Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers;
      final dynamic creationParams;
      final MessageCodec<dynamic> creationParamsCodec;
    
      const HtmlElementView({Key key, @required this.viewType, this.onPlatformViewCreated, this.gestureRecognizers, this.creationParams, this.creationParamsCodec})
          : assert(viewType != null),
            assert(kIsWeb, 'HtmlElementView is only available on Flutter Web.'),
            super(key: key);
    
      @override
      Widget build(BuildContext context) => PlatformViewLink(
            viewType: viewType,
            onCreatePlatformView: _createHtmlElementView,
            surfaceFactory: (BuildContext context, PlatformViewController controller) => PlatformViewSurface(
              controller: controller,
              gestureRecognizers: gestureRecognizers,
              hitTestBehavior: PlatformViewHitTestBehavior.opaque,
            ),
          );
    
      _HtmlElementViewControllerEx _createHtmlElementView(PlatformViewCreationParams params) {
        final _HtmlElementViewControllerEx controller = _HtmlElementViewControllerEx(params.id, viewType);
        controller._initialize().then((_) {
          params.onPlatformViewCreated(params.id);
          onPlatformViewCreated(params.id); //!!!
        });
        return controller;
      }
    }

In addition to the extra fields that make it on par with `AndroidView` and `UIKitView`, this actually means a single line added, marked with `//!!!`.

**Comment by yjbanov** [comment]
@hterkelsen can you please triage this?

**Comment by deakjahn** [comment]
@hterkelsen It seems that something is worked on with this control (eg. PlatformViewController.clearFocus() changed to async). Couldn't this be possibly a time to check this out? It's just a simple callback providing feature parity with other platforms, nothing dangerous. :-)

**Comment by RaghuMudem** [comment]
Any solution for this, onPlatformViewCreated for HtmlElementView ?

**Comment by deakjahn** [comment]
I use a [custom type extended from the original one](https://github.com/deakjahn/flutter_dropzone/blob/master/flutter_dropzone_web/lib/html_element_view.dart) but it would be nice to finally see it implemented.

**Comment by LichKing-2234** [comment]
My PR has been merged #84095. Now HtmlElementView support onPlatformViewCreated callback.

**Comment by MrBirb** [comment]
@TahaTesser Looks like this can be closed?

**Comment by deakjahn** [comment]
@LichKing-2234 Is there any way to learn when it actually lands? Or do we need to check every time we upgrade Flutter?

**Comment by TahaTesser** [comment]
Hi everyone
Closing as thehttps://github.com/flutter/flutter/pull/84095 is landed

**Comment by LichKing-2234** [comment]
@deakjahn you should run `flutter channel master` before it is stable.

**Comment by deakjahn** [comment]
I certainly won't do that. I have plugins that rely on a workaround and I don't want to touch that before it goes into stable. I don't want to force my plugin users to unstable channels.

I guess it's trying it from time to time then...

**Comment by LichKing-2234** [comment]
@deakjahn Sure, you can use it after it is stable.
