### ISSUE TITLE
debugDumpApp() is broken in release mode

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#56199]
I just tried to use https://flutter.dev/docs/testing/code-debugging#widget-tree and it does not print anything other than the initial `WidgetsBinding` type:

```
I/flutter (30606): WidgetsFlutterBinding - RELEASE MODE
I/flutter (30606): 
```

To reproduce, just add `debugDumpApp()` call to the `incrementCounter` function in hello flutter application.

**Comment by mehmetf** [comment]
It seems it is working in debug mode. That typically changes the widget tree since extra tracing/debugging widgets are inserted. It would be good to make this work for release mode. The code indicates that it should.

**Comment by mehmetf** [comment]
Ah, this might be because we removed all `toString` functions from AOT. @dnfield

**Comment by dnfield** [comment]
I don't think that's on by default is it?

**Comment by mehmetf** [comment]
Yeah I was guessing if that was the cause but it is not. I turned it off in google3 and I still get no output from `debugDumpApp()`.

**Comment by jonahwilliams** [comment]
@mehmetf why are you calling debugDumpApp in release mode? This is usually wired up to a service extension callback which is also disabled in this mode.

IIRC disabled the diagnostics node code in release mode a few months/weeks ago because it saved a large % of code size

**Comment by dnfield** [comment]
Yes, that's the cause. Retaining all the diagnostics code for release leads to many large strings being left in the binary.

The debug* methods are not really meant for release mode

**Comment by mehmetf** [comment]
I have no important reason to call it in release mode. A minor reason is that complex apps typically insert additional widgets to their tree if running in debug mode (for extra tracing etc) so you don't  get the exact widget tree.

I filed this primarily because [documentation](https://flutter.dev/docs/testing/code-debugging#widget-tree) and code itself did not give any indication that this would fail in release mode.

Saving binary size is more important but we should update the message + documentation to make it clear.

**Comment by PerrchicK** [comment]
Hi fellows,
Just out of curiosity, is it possible to see / print / output the widgets tree in release mode? For analytics purposes as an example.

Or maybe there's another convention to do that.

Thanks!

**Comment by dnfield** [comment]
Not really. Much of the code needed to do that is shaken out for release builds to help keep them smaller and faster.

**Comment by PerrchicK** [comment]
Yeah, sounds totally legit.

Thanks!
