### ISSUE TITLE
image_picker retrieve lost data not working

### ISSUE THREAD

**Issue by Inf0rmatix** [flutter/flutter#56191]
## Steps to Reproduce

Nearly impossible to safely reproduce. We encountered the issue with one device, Samsung T515. 
1. Use ImagePicker to take a photo with the camera
2. Specify maxWidht and maxHeight 
3. Sometimes mainActivity of the app gets destroyed when camera is used. 
4. Retrieve lost picture method of the plugin works not always
5. Looking into the device app files, I observed that not all pictures have a scaled_name-here version. These are the ones the plugins fails to retrieve. I once had the same problem without the scaling too but as I said, could not reproduce it anymore sadly.

**Comment by TahaTesser** [comment]
Hi @Inf0rmatix 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Does it only occur with this one device?
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
