### ISSUE TITLE
IOS 13.4.1 not supported

### ISSUE THREAD

**Issue by abdulmoeed137** [flutter/flutter#56193]
Hello, I am having issues in iOS 13.4.1 as my app is showing blank screen. 
Other versions working prfect. 
Attached screen shot 
![5f08e72c-9509-49a1-a51a-56bcf1f619f5](https://user-images.githubusercontent.com/20435194/80865012-ec473600-8c9f-11ea-842d-1520d8317353.jpg)

**Comment by timsneath** [comment]
This is the response from Apple when an app is inoperable on their test framework. They test on iOS 13.4.1. Most likely, this is a bug in your code, I'm afraid. 

Flutter is tested on iOS 13.4.1 and we're not aware of any general issues of this nature. If you're able to reproduce an issue locally, please submit a new issue with a clean reproduction. Thanks for using Flutter!
