### ISSUE TITLE
DataTable docs: rows sorting confusion

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#56204]
Current [DataTable docs](https://api.flutter.dev/flutter/material/DataTable-class.html) may confuse people about sorting: [1](https://stackoverflow.com/questions/51434778/flutter-using-datatable-sorting-built-in-function), [2](https://stackoverflow.com/questions/61563024/sorting-column-values-in-flutter-datatable).

It might be cleaner to explicitly point that rows aren't sorted automatically when passing `sortColumnIndex`/`sortAscending` and should be sorted manually if needed, e.g. in StatefulWidget

**Comment by markusaksli-nc** [comment]
Closing since https://github.com/flutter/flutter/pull/61356 was merged. @Pragya007 For future reference you can write `Fixes #56204` in the "Related issues" section and GitHub will automatically close the issue you are fixing.
