### ISSUE TITLE
iOS back gesture, gallery, contacts: app bar appears before contact info slides in from right

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5620]
On iOS, open the Gallery, then tap into Contacts. Notice how the app bar pops into place and the contents below the image slide in from the right.

I'd expect the app bar and the contents to come in together, or motion together.

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by eseidelGoogle** [comment]
This is due to us having marked the app bar as a hero, which @abarth did in part to work around a different performance bug at the time iirc.

**Comment by mpcomplete** [comment]
To be clear, this instant appbar change happens on Android as well (though the slide-in is from below).

**Comment by Hixie** [comment]
This is fixed now, I believe.
