### ISSUE TITLE
I GOT ERROR The following assertion was thrown building: type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by toure5013** [flutter/flutter#56206]
Widget tacheUser(devoirs) {
    print(devoirs);
    Color color = Color(devoirs["color"] ?? 0xFF42A5F5);

    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: <Widget>[
        //SizedBox(width: 20,),
        //L'HEURE ICI
        ClipRRect(
          borderRadius: BorderRadius.circular(80.0),
          child: Text(
            "_debut",
            maxLines: 1,
            style: TextStyle(
                fontSize: 20.0, color: Colors.orange[100], letterSpacing: 5),
          ),
        ),
        ClipRRect(
          borderRadius: BorderRadius.circular(80.0),
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 15.0),
            child: tacheInfo(devoirs["title"], devoirs["description"], color),
          ),
        ),
        ClipRRect(
          borderRadius: BorderRadius.circular(80.0),
          child: Text(
            "_fin",
            maxLines: 1,
            style: TextStyle(
                fontSize: 20.0, color: Colors.red[200], letterSpacing: 5),
          ),
        ),
      ],
    );
  }
}

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by toure5013** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building:
type 'String' is not a subtype of type 'int' of 'index'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      _CalendarPageState.tacheUser (package:ilm/src/screens/calendar/calendar_page.dart:193:33)
#1      _CalendarPageState.build.<anonymous closure> (package:ilm/src/screens/calendar/calendar_page.dart:162:39)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#4      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:139:29)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4251): {"color":"Colors.teal","debut":9,"description":"DESCRIPTION 1......","fin":20,"jourDebut":"Lun","jourFin":"Mer","title":"TITRE 2"}

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'String' is not a subtype of type 'int' of 'index'
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 7 of 634 libraries in 942ms.
I/chatty  ( 4251): uid=10089(com.example.ilm) Thread-2 identical 4 lines
I/flutter ( 4251): {"color":"Colors.teal","debut":9,"description":"DESCRIPTION 1......","fin":20,"jourDebut":"Lun","jourFin":"Mer","title":"TITRE 2"}

**Comment by imeDevelopers** [comment]
@toure5013 

change
`{"color":"Colors.teal"` ...
to
`{"color": Colors.teal` ...

and

`Color color = Color(devoirs["color"] ?? 0xFF42A5F5);`
to
`Color color = devoirs["color"] ?? Color(0xFF42A5F5);`

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
