### ISSUE TITLE
some flutter build errors with fix ...

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#56208]
some errors:
```
Execution failed for task ':app:minifyReleaseWithR8'.
----------------------------------------------------------------------------
[+1299 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':screen_state:verifyReleaseResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]
C:\Users\USERNAME\.gradle\caches\transforms-2\files-2.1\96366b063e0c1dac8d3c608473f4a2e1\core-1.1.0\res\values\values.xml:142:5-173:
25: AAPT: error: resource android:attr/fontVariationSettings not found.
[   +1 ms]
C:\Users\USERNAME\.gradle\caches\transforms-2\files-2.1\96366b063e0c1dac8d3c608473f4a2e1\core-1.1.0\res\values\values.xml:142:5-173:
25: AAPT: error: resource android:attr/ttcIndex not found.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 9m 9s
[        ] 1153 actionable tasks: 162 executed, 991 up-to-date
[+2410 ms] Running Gradle task 'assembleRelease'... (completed in 553.2s, longer than expected)
[  +49 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to
solve the incompatibility.

---------------------------------------------------------------------------

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

             BUILD SUCCESSFUL in 2m 45s
             23 actionable tasks: 3 executed, 20 up-to-date

             src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt:116:36: warning: variable
             'totalDurationSeconds' initializer is redundant
                     var totalDurationSeconds = 0L
                                                ^
[   +3 ms] Running Gradle task 'assembleAarRelease'... (completed in 169.4s, longer than expected)

The plugin cloud_firestore could not be built due to the issue above.
----------------------------------------------------------------------------
```

my strategy to fix:
1. open your `Android/gradle.properties` file and make sure `android.enableR8=true` is exists ..
and it i will be better to sure that the content of the file is:

```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

2. inside your project file create `kill.bat` file and it's content will be:

```
taskkill /f /im dart.exe
taskkill /f /im java.exe
```

write kill in your terminal before you build your app ...

3. open your [notepad++](https://notepad-plus-plus.org/) ...

press CTRL+F , search in : `C:\Users\%USERNAME%\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org`

for `compileSdkVersion` and make sure to make the `compileSdkVersion and minSdkVersion and targetSdkVersion` for all plugins build.gradle file is the same `compileSdkVersion and minSdkVersion and targetSdkVersion` in your project `Android/app/build.gradle` file ..

![Capture](https://user-images.githubusercontent.com/63128477/80872926-55857400-8cb5-11ea-998c-6a10cc200f98.PNG)

![Capture](https://user-images.githubusercontent.com/63128477/80873211-312a9700-8cb7-11ea-9d07-206b4e64dc5a.PNG)

4. make sure to [Signing the app](https://flutter.dev/docs/deployment/android#signing-the-app) before you make your build ...

5. make sure you implement these plugins:

```
    implementation "com.android.support:multidex:1.0.0"
    implementation 'com.android.support:appcompat-v7:28.0.0'//29.0.2,28.0.3
    implementation "com.android.support:support-v4:28.0.0"
    implementation "com.android.support:support-fragment:28.0.0"
```
and if you use firestore ...

```
    implementation 'com.google.firebase:firebase-firestore:21.4.3'
    implementation 'com.google.firebase:firebase-firestore-ktx:21.4.3'
```

**Comment by Niccolohui** [comment]
hi, sorry, how about Mac os?

**Comment by imeDevelopers** [comment]
@Niccolohui 
Try to do the same , just ignore step number 2.

**Comment by Niccolohui** [comment]
@imeDevelopers  but I couldn't find the file AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org in mac os.

**Comment by imeDevelopers** [comment]
@Niccolohui
Try to find `pub.dartlang.org` folder in your computer , search for it .. and you will find your plugins in there ...

**Comment by iapicca** [comment]
Hi @Niccolohui
this issue seems more an explanation 
rather than a problem with flutter

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by msndvlpr** [comment]
@imeDevelopers your solution will not work because when you change `minSdkVersion`, c`ompileSdkVersion` and `targetSdkVersion` you have to choose a correct Gradle build tool version and change it therefore.

**Comment by pratikpparikh** [comment]
@msndvlpr do you have a suggestion to make it work with other version?

**Comment by braysonjohn148** [comment]
My issue was: the same, when i change to 5.6.4 another dependency fires an error.
Just add this to your android/gradle.property file.
```
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```
