### ISSUE TITLE
Why can't I able to reinstall flutter by downloading flutter SDK in my Windows 10 OS?

### ISSUE THREAD

**Issue by thealiflab** [flutter/flutter#56201]
I have been using flutter for one and a half year. 
But recently I messed up some code so that I need to uninstall the environment totally and about to try reinstallation but I failed. 

It showing this (failed) button and so that I'm unable to download the SDK file from flutter's official get-started page. I also tried to git clone the repository of stable SDK version but that also appeared error. 

![Problem-pic](https://user-images.githubusercontent.com/53125727/80870265-2aa41b80-8cc7-11ea-8766-be997ccdcbdc.png)

What should I do?

**Comment by timsneath** [comment]
Let's get you up and running again. Here's a direct link to the Windows stable SDK: 
https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.12.13+hotfix.9-stable.zip

We've seen this failure before, but it's very intermittent and hard to pin down. I'll link to the other examples when I find them. 

Hope the link above gets you working again. Thanks for using Flutter!

**Comment by thealiflab** [comment]
@timsneath  I used a VPN to solve this. I don't know why it's happening to me. When I first installed, it works perfectly fine for me. But now without a VPN, it doesn't allow me to download.


I found this post helpful: https://stackoverflow.com/questions/54775153/cant-download-flutter-download-button-fail
