### ISSUE TITLE
Add flutter to existing app : No installed package from pubspec get registered

### ISSUE THREAD

**Issue by carotkut94** [flutter/flutter#56214]
Added a flutter module in existing iOS app, 
and the module works fine when run standalone followed the guide, 

but when the app is ran inside the host, 
none of the packages installed from pubspec.yaml works

**Comment by carotkut94** [comment]
How do i register all my plugins when presenting a view controller with implicit engine?

https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#alternatively---create-a-flutterviewcontroller-with-an-implicit-flutterengine

**Comment by TahaTesser** [comment]
Hi @carotkut94 
can you please provide your `flutter doctor -v` and `pubspec.yaml` from your module? 
Also, to better address the issue, would be helpful if you could post a minimal code sample in a repository to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@carotkut94 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
