### ISSUE TITLE
Flutter Blue package is giving error when i  tap to the connect button and here is the error                                                          The following assertion was thrown building DeviceScreen(dirty): I/flutter (28997): type 'Future<dynamic>' is not a subtype of type '() => void' I/flutter (28997): Either the assertion indicates an error in the framework itself, or we should provide substantially

### ISSUE THREAD

**Issue by saqib556612** [flutter/flutter#56211]

**Comment by saqib556612** [comment]
![image](https://user-images.githubusercontent.com/55543388/80891549-2b947780-8cde-11ea-99c3-0d7644c96753.png)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
