### ISSUE TITLE
iOS back gesture: emerging view should be dark and then lighten as the old view is transitioned off

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5621]
Notice how the lightness of the back view/page is constant as the old view is transitioned off the screen. Looking at other iOS apps (from Google and Apple), the back/previous view is dark at the beginning and then lightens up as the previous view disappears.

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by mpcomplete** [comment]
Can you give an example app? I don't notice this effect in any of the apps I've tried (e.g. the Settings app).

**Comment by sethladd** [comment]
Sorry, I wasn't specific :(  try this: open Settings, tap Bluetooth. Then, slowly use the back gesture. Notice how "Bluetooth" is dark and then lightens as the user gestures left.

This is a very iOS-ism and something that doesn't affect muscle memory navigation (it's purely visual) so I don't think we need to emulate it.

(In the future, I'll try to ask myself "does the difference affect muscle memory and/or navigation?" before filing something I notice)

**Comment by mpcomplete** [comment]
You're talking about the text in the app bar, right? If so, that is something I was planning on trying.
