### ISSUE TITLE
How to register plugins using GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by carotkut94** [flutter/flutter#56217]
How do i register all my plugins when presenting a view controller with implicit engine?

https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#alternatively---create-a-flutterviewcontroller-with-an-implicit-flutterengine

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by carotkut94** [comment]
Isn't this is the lack of documentation?
