### ISSUE TITLE
Not able to get my local ip address: package get_ip 0.4.0

### ISSUE THREAD

**Issue by SwenWallnoefer** [flutter/flutter#56238]
Im trying to get the local ip address in a Flutter Web app. Searching the internet i came arround this package: get_ip 0.4.0 - it states it is working under web.

I have this function:

```
Future<void> initPlatformState() async {
    print("Test");
    String ipAddress;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      ipAddress = await GetIp.ipAddress;
    } on PlatformException {
      ipAddress = 'Failed to get ipAddress.';
    } on Exception {
      print("Exception");
    }

    print("Ip: $ipAddress");
  }
```
and i call it in initState of main.dart.

The console just has the output "Test", it does not output the ip or "Exception".

Has someone allready used this package? Would there be an other way for a web app to get the local ip?

(I'm using MacOS)

**Comment by iapicca** [comment]
Hi @SwenWallnoefer 
[get_ip](https://pub.dev/packages/get_ip) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/lotrofans/get_ip_flutter/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
