### ISSUE TITLE
Issue from website page 为您的Flutter应用程序添加交互

### ISSUE THREAD

**Issue by chenxq16** [flutter/flutter#56230]
From URL: https://www.flutterchina.club/tutorials/interactive/index.md

In this article , hyperlink is 404 for the sample 'flutter gallery' in section 4

**Comment by TahaTesser** [comment]
Hi @chenxq16 
This website is a community run website, it's not official. 
Closing, as this isn't an issue,
if you disagree please write in the comments and I will reopen it 
Thank you
