### ISSUE TITLE
Loading AssetManifest during widget tests

### ISSUE THREAD

**Issue by Mooibroek** [flutter/flutter#56242]
Im working on implementing widget tests with localizations, but every time i add a second test in 1 file, the second test hangs. After a lot of debugging I traced it down to loading something from the AssetBundle.

I also saw this issue (https://github.com/flutter/flutter/issues/12999) Perhaps it is related, don't have enough Flutter testing experience to really know.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a test
3. Paste in this piece of code 

``` dart
void main() {
  testWidgets("Load AssetManifest", (tester) async {
    var result = await rootBundle.loadString("AssetManifest.json");
    print(result);
  });

  testWidgets("Load AssetManifest", (tester) async {
    var result = await rootBundle.loadString("AssetManifest.json");
    print(result);
  });
}
```

**Expected results:** 
Both succeed and print the manifest in the console.

**Actual results:**
The first one succeeds and the second ons hangs. (When using a proper widget to test it says something like pumpAndSettle timed out.

**My flutter doctor output** 

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available
```

**Comment by TahaTesser** [comment]
Issue also reproducible on `dev`  and `beta`

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (10 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28)
      (emulator)
    • macOS               • macOS         • darwin-x64     • Mac OS X 10.15.4
      19E287
    • Web Server          • web-server    • web-javascript • Flutter Tools
    • Chrome              • chrome        • web-javascript • Google Chrome
      81.0.4044.129

• No issues found!
``` 

</details>

**Comment by chunhtai** [comment]
If you want to directly interact with async code, you will need to use test method directly because testWidget faked the async zone

```
void main() {
  test("Load AssetManifest", () async{
    TestWidgetsFlutterBinding.ensureInitialized();
    var result = await rootBundle.loadString("AssetManifest.json");
    print(result);
  });

  test("Load AssetManifest", () async{
    TestWidgetsFlutterBinding.ensureInitialized();
    var result = await rootBundle.loadString("AssetManifest.json");
    print(result);
  });
}
```

**Comment by Mooibroek** [comment]
This might work, but now i don't have access to the `WidgetTester` instance. And I cant add it myself because of the internal constructor. And the whole point is to properly to Widget tests with localizations :-)

![afbeelding](https://user-images.githubusercontent.com/7236283/81272879-6421b180-904e-11ea-888e-c87a9d6f2748.png)

The example given is a really really trimmed down example of the problem i'm having. The problem is actually in loading localizations that is accessing the `rootBundle.loadString("AssetManifest.json");`. First test works fine and second is failing.

**Comment by chunhtai** [comment]
you can try [runAsync](https://master-api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html) by putting the tester.pumpWidget in the callback and put several pump in there. Different app might require different set up, can you share a complete test example where i can paste into my ide and run to reproduce the issue?

**Comment by Mooibroek** [comment]
Hey there, I tried to make a proper example you can run. It probably has something to do with my limited knowledge of initiating the test propery. 

1. I created a new project (Flutter 1.17 stable) using `flutter create`
2. Added `flutter_translate:` to the pubspec
https://gist.github.com/Mooibroek/1ad72116289799a9592667c2e33c114c
3. Added this into the `widget_test.dart` file
https://gist.github.com/Mooibroek/5e9c5b15c74250928c3323dc1aaa69b9

(A zip of the complete sample project can be found here https://drive.google.com/file/d/1aQ4qxG1FGx8qg5s1S8tx3oJUBUAyeRC7/view?usp=sharing)

Im getting the following on the **first** test
```
The following assertion was thrown running a test:
Unable to load asset: AssetManifest.json
```

And the **second** test gives this error
```
The following assertion was thrown running a test:
pumpAndSettle timed out
```

**Comment by Mooibroek** [comment]
I tried the `runAsync` and that seems to work 👍 

```dart

void main() {
  testWidgets("Start with onboarding", (tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(AppLoader(env: testEnv()));
      await tester.pumpAndSettle();
    });

    final loginButton = find.byKey(ValueKey(Keys.onboarding));
    expect(loginButton, findsOneWidget);
  });

  testWidgets("Start with onboarding", (tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(AppLoader(env: testEnv()));
      await tester.pumpAndSettle();
    });

    final loginButton = find.byKey(ValueKey(Keys.onboarding));
    expect(loginButton, findsOneWidget);
  });
}
```

2 tests passed. Thanks for nudging me in the right direction!
