### ISSUE TITLE
Documentation typo: easy fix

### ISSUE THREAD

**Issue by msmolkin** [flutter/flutter#56251]
In several classes, including at least the [Column class](https://api.flutter.dev/flutter/widgets/Column-class.html), [Expanded class](https://api.flutter.dev/flutter/widgets/Expanded-class.html), and the [Flexible class](https://api.flutter.dev/flutter/widgets/Flexible-class.html), the wrong form of "its" is used.

Possible fix:

`sed -i {file} -e "s/it's flex value/its flex value/g" -e "s/it's middle child/its middle child/g"`

**Comment by JayTailor45** [comment]
Hi @iapicca I am interested to take it. I am new to this and currently reading CONTRIBUTING.md
Can you please guide me to for my first PR?

Thanks
