### ISSUE TITLE
image_picker not working on flutter latest version

### ISSUE THREAD

**Issue by sumujain1995** [flutter/flutter#56250]
Whenever on calling ImagePicker.pickImage method,  getting  `Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker`.

`Flutter doctor -v'
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.12.13+hotfix.7 at /Users/sumeetjain/Desktop/Purplle_Android_Upgrade/flutter
    • Framework revision 9f5ff2306b (3 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sumeetjain/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.0

[✓] Connected device (2 available)
    • SM M305F          • 52000217ca5486f1                     • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • A8BDB3E2-070F-4F53-ABD8-E9F1DC26AB07 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

```

Please note: addition of image_picker in `pubspec.yaml` gives the following warning

`image_picker : ^0.6.5+3
`
```
Running "flutter pub get" in flutter_module...                      0.9s
The plugin `flutter_plugin_android_lifecycle` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0

```

What am thinking is image_picker plugin is not getting register properly due to above warning, but i don't know how to resolve this if that is the issue..

please give some context on this issue

**Comment by DK15** [comment]
@sumujain1995 see if this helps : https://github.com/flutter/flutter/issues/52293 regarding the issue you are getting while trying to run `pub get`.
Otherwise, I was unable to replicate the error you mentioned (on Flutter Channel stable, v1.12.13+hotfix.8) while trying to open `camera` and `gallery` using the plugin.

**Comment by TahaTesser** [comment]
Hi @sumujain1995 
Can you please upgrade to latest `stable`  and try the running the official [example](https://pub.dev/packages/image_picker#-example-tab-) in a new project? 
if the problem persist, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by sumujain1995** [comment]
@TahaTesser i am on latest version on stable channel. Check the above flutter doctor output.

**Comment by TahaTesser** [comment]
Hi @sumujain1995 
Here i created quick made quick [example](https://github.com/TahaTesser/FlutterModoleImagePicker) repository, image_picker in Flutter module and it has no issues 

Your Flutter version is 3 months old, please upgrade to latest hotfix
```
Flutter 1.12.13+hotfix.9 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2
```

Thank you
