### ISSUE TITLE
hi,,i have a problem in my app .after login ,the home page doesn't show any in body but the appbar and bottom are visible,so when i reload the app all widgets are visible,i think the problem is about states but i,m note sure,some help please

### ISSUE THREAD

**Issue by cedos10** [flutter/flutter#56259]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
