### ISSUE TITLE
I am a new user Flutter. I found problem about android studio that it occur red error as picture. Everyone who know what happened.

### ISSUE THREAD

**Issue by Sukum99** [flutter/flutter#56265]
<img width="1653" alt="Screen Shot 2563-05-04 at 09 53 57" src="https://user-images.githubusercontent.com/56705941/80933286-46a1dd00-8ded-11ea-8ab6-9f7e93e59971.png">

**Comment by omishah** [comment]
Have you installed the ``Flutter Plugin`` for VS Code?

**Comment by iapicca** [comment]
Hi @Sukum99 
can you please provide your `flutter doctor -v` 
and your `pubspec.yaml` 
Thank you

**Comment by Sukum99** [comment]
Sorry, I uninstall Android studio and Flutter then reinstall again. It is solved

**Comment by VladyslavBondarenko** [comment]
@Sukum99 
Closing as solved
