### ISSUE TITLE
flutter doctor error: unable to find utility "xcdevice", not a developer tool or in PATH

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter#56270]
Version:
> macOS 10.15.4
> Xcode 11.3.1 (I also installed and uninstalled 11.4 and 11.5)
> Flutter 1.18.0-8.0.pre • channel dev

![image](https://user-images.githubusercontent.com/58068445/80943309-79fa6100-8e19-11ea-9fbe-ce26ca223143.png)

I'm pretty sure I executed:
> sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

Log:
```
Error executing simctl: 72
xcrun: error: Failed to determine realpath of
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdke
xportexport' (errno=No such file or directory)
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdkex
portexport -find simctl 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or
directory)
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH


xcrun: error: Failed to determine realpath of
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdke
xportexport' (errno=No such file or directory)
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdkex
portexport -find xcdevice 2> /dev/null' failed with exit code 16384: (null) (errno=No such file
or directory)
xcrun: error: unable to find utility "xcdevice", not a developer tool or in PATH
```
![image](https://user-images.githubusercontent.com/58068445/80943266-618a4680-8e19-11ea-8727-b92c52f4a1fb.png)

**Comment by sndrox** [comment]
This might be related somehow:
I discovered that attaching my iPad (iPad Pro - 13.4.1) Android Studio starts trying to communicate with the device but, something goes wrong in the background as quite rapidly (about 1 hour) the HD goes full and restarting I find a "Recovered files" folder in the bin full of : (A Document Being Saved By xcdevice) folders with copies of dyld_shared_cache_arm64 (1.7 GB). Disconnecting the ipad and/or shutting down Android Studio will end this ever-growing process.
![Schermata 2020-05-04 alle 11 23 49](https://user-images.githubusercontent.com/5555926/80952316-c59d1280-8df9-11ea-8bf8-d21e3cf51fcb.png)

**Comment by vvVenom** [comment]
> ![Schermata 2020-05-04 alle 11 23 49](https://user-images.githubusercontent.com/5555926/80952316-c59d1280-8df9-11ea-8bf8-d21e3cf51fcb.png)

Oh, sorry. I don't seem to have these files

**Comment by jmagman** [comment]
```
xcrun --find simctl
```
needs to return an existing path without errors.

Can you double-check it's pointed to the right place?  Please quit Xcode and run:
```
sudo xcode-select --switch /Applications/Xcode.app
sudo xcodebuild -runFirstLaunch
```

`flutter` tooling is shelling out to various Xcode command line tools, so until `xcrun` is happy with your Xcode installation, `flutter` won't be either.

**Comment by vvVenom** [comment]
> ```
> xcrun --find simctl
> ```

```
➜  ~ xcrun --find simctl
xcrun: error: Failed to determine realpath of '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdkexport' (errno=No such file or directory)
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdkexport -find simctl 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
```

**Comment by jmagman** [comment]
You have an Xcode installation problem and flutter isn't going to work until `xcrun` is fixed up.  
That output from `doctor` is pretty gross though with the interleaved errors, ideally you would just see the nice message under Xcode with the instructions to `-runFirstLaunch`

**Comment by vvVenom** [comment]
> You have an Xcode installation problem and flutter isn't going to work until `xcrun` is fixed up.
> That output from `doctor` is pretty gross though with the interleaved errors, ideally you would just see the nice message under Xcode with the instructions to `-runFirstLaunch`

😯, this is disturbing because I try to uninstall xcode and there are problems with reinstall

**Comment by sndrox** [comment]
Confirmed, my case was related only to xcode installation, nothing to do with flutter. Just solved from xcode side and now everything's ok. Sorry for the wrong post.

**Comment by vvVenom** [comment]
Oh, it sounds stupid. The reason for this problem is because I do n’t know when `export SDKROOT="$(xcrun --show-sdk-path)"` is configured in the .zshrc file. When I enter this command in the terminal, it prints out a non-existent directory, so I will Just change the environment variable to `export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`.

Now, I call the doctor:

![image](https://user-images.githubusercontent.com/58068445/81463799-f52f8e80-91ee-11ea-9ef8-5df5170d9763.png)

**Comment by seekcx** [comment]
> This might be related somehow:
> I discovered that attaching my iPad (iPad Pro - 13.4.1) Android Studio starts trying to communicate with the device but, something goes wrong in the background as quite rapidly (about 1 hour) the HD goes full and restarting I find a "Recovered files" folder in the bin full of : (A Document Being Saved By xcdevice) folders with copies of dyld_shared_cache_arm64 (1.7 GB). Disconnecting the ipad and/or shutting down Android Studio will end this ever-growing process.
> ![Schermata 2020-05-04 alle 11 23 49](https://user-images.githubusercontent.com/5555926/80952316-c59d1280-8df9-11ea-8bf8-d21e3cf51fcb.png)

I also encountered this problem and it is not working now. Do you have a good solution?

**Comment by sndrox** [comment]
Sure:
1) Remove Xcode.app
2) I also remove (renamed for the sake of security my user Library/Developer/Xcode
3) untrust your device
4) reinstall xcode
5) spawn xcode and open the "Devices" window
6) connect your device, you might see some errors below reporting an error, trust your device and wait, XCode will silently, in background, reinstall al missing files to proper read the device, might take a very long time but at the end everything went well and I could start Android Studio again with my devices attached.

Of course I close every other app, including Android Studio before doing this.

Good Luck,
Sandro

**Comment by seekcx** [comment]
@sndrox Thank you very much for your approach.

**Comment by benbdevd** [comment]
I also experienced my disk being filled up completely by "A Document Being Saved by xcdevice #" files upon attaching an iOS device.

For context, I installed Flutter on macOS 10.14, then upgraded to macOS 10.15, the latest Xcode, and the latest Flutter 1.17 using `flutter upgrade`.

Reinstalling Xcode did not fix the problem for me.
I think this was happening because I did not update cocoapods along with all of the other tools.
Regardless, I played it safe and 'reinstalled' Flutter as well as cocoapods.

These steps solved my problem:
- Delete Flutter framework directory
- [Uninstalled cocoapods completely](https://superuser.com/questions/686317/how-to-fully-uninstall-the-cocoapods-from-the-mac-machine)
- Clone Flutter repo from Github stable branch
- Run flutter doctor (make sure you still have it in your path)
- Install cocoapods when prompted with `sudo gem install cocoapods`
- Run `pod setup` as prompted after cocoapods finished installing

**Comment by jmagman** [comment]
@benbdevd @seekcx @sndrox The "A Document Being Saved By xcdevice" filling up your storage is unrelated to this Xcode installation issue where xcdevice just can't be found at all (and is likely unrelated to Flutter or CocoaPods since `xcdevice` is an Xcode command line tool and it just how Flutter is figuring out which devices are attached).  Please file a new issue and fill out the template and we can investigate further.

**Comment by bluemix** [comment]
I here from:
https://stackoverflow.com/questions/61903057/flutter-disk-full-error-a-document-being-saved-by-xcdevice

I am not connecting any iOS device, but still my storage being filled by `xcdevice`.

```
xcrun --find simctl
/Applications/Xcode.app/Contents/Developer/usr/bin/simctl
```

I don't think there is an error with my simulator path.

**Comment by mileusna** [comment]
I have the same issue. If fills my entire SSD, it takes 170GB of space and then the disk is full. It is cleans up by macOS restart. I test on iPhone8. I will try with XCode next time, but there is definitely some problem here.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F101, locale sr-Latn-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by jmagman** [comment]
@mileusna That's likely https://github.com/flutter/flutter/issues/56826.

**Comment by psimondk** [comment]
This is NOT just Xcode. Flutter does it with Android and Android Emulator and its bad, really bad.
Suggest to fix it soon

**Comment by jmagman** [comment]
@psimondk This GitHub issue is tracking the error `xcrun: error: unable to find utility "simctl", not a developer tool or in PATH` not generic Flutter performance issues.  The originator had an environment issue where `xcrun --show-sdk-path` was not returning anything valid.  Please file a new issue and completely fill out the template.

**Comment by psimondk** [comment]
> @psimondk This GitHub issue is tracking the error `xcrun: error: unable to find utility "simctl", not a developer tool or in PATH` not generic Flutter performance issues. The originator had an environment issue where `xcrun --show-sdk-path` was not returning anything valid. Please file a new issue and completely fill out the template.

Seems to be handled in https://github.com/flutter/flutter/issues/56826. Hope the fix solves the issue

**Comment by nkanellopoulos** [comment]
```$ xcrun --find simctl
/Applications/Xcode.app/Contents/Developer/usr/bin/simctl
```

I just deleted 200GB of Temp files...
