### ISSUE TITLE
"Color" and "Colors" should be "Colour" and "Colours"

### ISSUE THREAD

**Issue by lemmerelassal** [flutter/flutter#56273]
The English language is free but not open-source.

**Comment by Zazo032** [comment]
> Prefer US English spellings. For example, 'colorize', not 'colourise', and 'canceled', not 'cancelled'.

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#spell-words-in-identifiers-and-comments-correctly

**Comment by iapicca** [comment]
Hi @lemmerelassal 
I'm not a native English speaker both spellings are correct
or at least consistent with the usage in [material design](https://material.io/design/color/the-color-system.html#color-usage-and-palettes)
Thank you
