### ISSUE TITLE
`flutter run --profile` is mixing sources from different Dart revisions

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#5627]
(@fa8dc5f88bf4bc831adfbf25fb733d4f7e1a2006)

Running the Gallery app with `flutter run --profile`, produces

```Ignoring error posting over WebSocket.```

After fixing dart-lang/sdk#27172, one gets

```Ignoring error posting over WebSocket. Class '_WebSocketImpl' has no instance method 'addUtf8Text'.```

This use of `WebSocket.addUtf8Text` and its implementation were recently added in the same Dart commit, so flutter is somehow using a newer revision of the service library and an older version of the io library.

**Comment by eseidelGoogle** [comment]
Spoke with @rmacnak-google in person just now.  flutter/flutter and flutter/engine versions can skew.  Currently:
https://github.com/flutter/engine/blob/master/DEPS#L27
024501679241ba19e03d548db1b1b438e0dabc49
and:
https://github.com/flutter/flutter/blob/master/bin/cache/dart-sdk.version
1.19.0-dev.5.0
which is https://github.com/dart-lang/sdk/tree/1.19.0-dev.5.0

**Comment by eseidelGoogle** [comment]
Looks like engine is 2 days old and flutter/flutter is 16 days old.  All dart natives (e.g. those backing dart:io) get built into the engine binares from the flutter/engine dart sdk revision, and all dart sources are pulled from the flutter/flutter dart sdk version when gen_snapshot is run on the host.

**Comment by dragostis** [comment]
Any updates on this?

**Comment by jason-simmons** [comment]
This seems work as expected when I use a tip-of-tree locally built android_profile engine.  But I get the WebSocket.addUtf8Text error when I run an app using the latest engine downloaded from the build server.

Comparing the two engines I noticed something strange.  Running "strings gen_snapshot | grep addUtf8Text" on the locally built engine yields the declarations of addUtf8Text from WebSocket and WebSocketImpl.  But that code does not appear to be present in the gen_snapshot binary from the build server.

Maybe there is something wrong with the state of the build server, and it's grabbing the wrong version of the dart-sdk IO libraries while building gen_snapshot?

I just kicked off a full rebuild on the buildbot, and I'm curious to see if the rebuilt binaries look different.

**Comment by jason-simmons** [comment]
It looks like there is a missing dependency in the Dart build.  A recent update to websocket_impl.dart did not trigger a regeneration of dart/runtime/bin/io_gen.cc, which packages the core Dart IO libraries into gen_snapshot.

So incremental builds of gen_snapshot on the buildbot were including an older revision of websocket_impl.dart that did not contain WebSocket.addUtf8Text

The Dart team will look at the runtime/bin build file dependencies.

I've forced a clean rebuild on both buildbot servers.  When that completes we should be able to roll the resulting binaries over to the framework.

**Comment by a-siva** [comment]
Landed https://github.com/dart-lang/sdk/commit/780ef512159d3f4e6c06fe51bed72eebe863a82e to fix the dependency problem
