### ISSUE TITLE
Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/6.3/gradle-6.3.pom'

### ISSUE THREAD

**Issue by blessedthefirstone** [flutter/flutter#56279]
well , I'm trying to run my first app with flutter in android studio after i run the program it shows this error 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:6.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:6.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/6.3/gradle-6.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/6.3/gradle-6.3.pom'.
               > dl.google.com:443 failed to respond
      > Could not resolve com.android.tools.build:gradle:6.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/6.3/gradle-6.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/6.3/gradle-6.3.pom'.
               > jcenter.bintray.com:443 failed to respond
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
               > dl.google.com:443 failed to respond
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
               > jcenter.bintray.com:443 failed to respond
```

doesn't matter whether I try to run in command line with 
<< flutter run >>
or in android studio 
it gives the same error

the output of 'flutter doctor -v '

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17134.1425], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\win10\AppData\Local\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\win10\AppData\Local\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by blessedthefirstone** [comment]
I just made another flutter project but this time it gives back this error 

Exception in thread "main" java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2055)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by VladyslavBondarenko** [comment]
Hi @blessedthefirstone 
could you show your `/android/build.gradle` and `/android/gradle/wrapper/gradle-wrapper.properties` files? 
does it happen with default project created with `flutter create`?

**Comment by blessedthefirstone** [comment]
/android/build.gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
/android/gradle/wrapper/gradle-wrapper
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by VladyslavBondarenko** [comment]
Does adding `mavenCentral()` helps? https://github.com/flutter/flutter/issues/22470#issuecomment-426794850

Is being behind a firewall your case? https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?

**Comment by blessedthefirstone** [comment]
I have tried adding a mavenCentral ( )  in my flutter.gradle like this 
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }


located in C:\src\flutter\packages\flutter_tools\gradle
it doesn't work 
and my only firewall is ESET security witch i had turned off

**Comment by VladyslavBondarenko** [comment]
@blessedthefirstone 
I'll link your SO question here https://stackoverflow.com/questions/61601172/having-trouble-to-run-my-first-flutter-app

**Comment by blessedthefirstone** [comment]
if you can't get google resource like that simply follow the steps here 

1. Make sure your using a reliable VPN such as nordvpn , windscribe , ........
2.Try updating your flutter using `flutter update --force`
3.Create another project using `flutter create projectname `
4.Cd to projectname 
5.and **flutter run **
6.you will get another errors that make no sense then but it will solve this error specifically
