### ISSUE TITLE
flutter_platform.dart generates code with implicit casts

### ISSUE THREAD

**Issue by davidmorgan** [flutter/flutter#56283]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart generates code which does implicit casts in three places; two here

```
    final IsolateSpawnException error = IsolateSpawnException(message[0]);
    final Trace stackTrace =
        message[1] == null ? Trace(const <Frame>[]) : Trace.parse(message[1]);
```

and one here

```
      assert(x is String);
      return json.decode(x);
```

which is a problem because

 - It stops people adding `implicit-casts: false` to their analysis options; and
 - When NNBD lands, and is enabled, implicit casts will go away completely and these will be errors.

IIRC with Dart 1 there was a difference in behaviour between implicitly and explicitly casting, but with Dart 2 there isn't; adding the explicit cast should do exactly what we want. I'll send a PR to do that.

**Comment by davidmorgan** [comment]
I need to correct myself: while NNBD will prevent most implicit casts, it _won't_ affect this case, because it's a cast from dynamic.

So, let me add more detail around `implicit-casts: false`, since that's the remaining reason for the proposed change.

We have a Google internal customer using Flutter that wants to enforce `implicit-casts: false`. We can't easily do this when there is generated code that fails the check. Unlike with lints, we can't get around this by allowing specific failure codes, because they are the same as normal error codes but they get more scope when `implicit-casts: false` is enabled, e.g. `invalid_assignment`.

So, making the generated code compliant seems like the simplest path, if the Flutter team is happy with that.

**Comment by jonahwilliams** [comment]
@davidmorgan did your PR address the issue, or is there more work to do here?

**Comment by davidmorgan** [comment]
Yes, thanks :)
