### ISSUE TITLE
Flutter webview is backed by WKWebview in iOS. which is deprecated by Apple and they are not allowing to upload build 

### ISSUE THREAD

**Issue by jayeshpansheriya** [flutter/flutter#56281]
if anyone can help, i am using this pub for weview in flutter

https://github.com/flutter/plugins/tree/master/packages/webview_flutter

Which is backed by WKWebview in iOS. which is deprecated by Apple and they are not allowing to upload build 

Everyone who are using following packages might have same issue if they have tried uploading testflight build 
google sign in 
facebook sign in 
url launcher 
firebase auth

**Comment by AtiqGauri** [comment]
They haven't mentioned anywhere that it is deprecated.

https://developer.apple.com/documentation/webkit/wkwebview?changes=latest_minor

**Comment by TahaTesser** [comment]
Hi @jayeshpansheriya 
You probably mistaking `UIWebView ` with `WKWebView ` 
"we strongly encourage you to update to WKWebView, as soon as possible, for improved security and reliability. "[Reference](https://mobilefirstplatform.ibmcloud.com/blog/2020/01/27/Removal-of-UIWebview/)

Are you sure about the cause of rejection? Can you please more details?
Can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you
