### ISSUE TITLE
problem executing flutter 

### ISSUE THREAD

**Issue by khalidsharief** [flutter/flutter#56293]
(base) MacBooks-MBP:~ macbookpro$ flutter --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by iapicca** [comment]
Hi @khalidsharief 
I see there's an open [issue](https://github.com/flutter/flutter/issues/55986) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by khalidsharief** [comment]
Hi @iapicca thanks million

**Comment by iapicca** [comment]
I've just posted a possible solution there, please take a look
