### ISSUE TITLE
Regression in analyzer_benchmark flutter_repo_watch_maximum

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56297]
Looks like around https://github.com/flutter/flutter/pull/56091. If this is true and it's an additional test, we should rebaseline.

![Screen Shot 2020-05-04 at 8 40 24 AM](https://user-images.githubusercontent.com/1435716/80984596-ea39c000-8de2-11ea-8e59-c63beb672e3a.png)

**Comment by liyuqian** [comment]
@shihaohong : it seems that your PR #56091 made the tool a little slower. Is that tiny regression (100s to 101s) expected?

Also, https://github.com/flutter/flutter/commit/c32d1387ab9a6cba7a4f9849dce1d6df63f5a173 and https://github.com/flutter/flutter/commit/6dc1e83f121157b35e648cdf138d022a5e5d706b seems to be making it even slower. Now the benchmark is around 105s. CC @stereotype441 @jonahwilliams

**Comment by shihaohong** [comment]
@liyuqian It seems surprising to me, unless the analyzer runs `gen_localizations.dart` at some point and/or the additional test in `flutter_localizations` and either is slowing down the tool. I'll investigate to see.

**Comment by shihaohong** [comment]
I just checked `analyze.dart` and it does. Running `analyze.dart` calls `gen_localizations.dart` to make sure that there are no unintended diffs in localization files. The new behavior I added checks and encodes a file to prevent a crash involving Kannada script characters in the Flutter repo. Should we re-baseline?

**Comment by liyuqian** [comment]
CC @zanderso for whether we should rebaseline the Flutter tool performance.

**Comment by jonahwilliams** [comment]
This is not benchmarking analyze.dart, its benchmarking `flutter analyze`. Its highly unlikely that any of these PRs changed the performance

**Comment by zanderso** [comment]
If none of the Flutter commits in the suspect range could have affected the performance of the benchmark, were there any engine/Dart SDK rolls in the range that could have?

Separate question: Does our benchmarking setup really give us 3 significant digits of precision?

**Comment by liyuqian** [comment]
@jonahwilliams : does `flutter analyze` eventually execute https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart so that file can affect `flutter analyze`'s performance? AFAIK, the benchmark is measuring how long `flutter analyze` finishes.

**Comment by jonahwilliams** [comment]
IIRC this code is analyzing the flutter repo - so everytime we add more code it should regress a little bit more

**Comment by liyuqian** [comment]
I see. Please feel free to rebaseline the benchmark and close this issue if the regression just means that we added more code.

**Comment by zanderso** [comment]
Removing TODAY label since the resolution is to rebaseline.

**Comment by kf6gpe** [comment]
Is flutter_repo_batch_maximum related to this benchmark, too? It seems to have regressed slightly as well.

**Comment by kf6gpe** [comment]
Rebaselined.
