### ISSUE TITLE
Regression in cull_opacity_perf__timeline_summary 90th_percentile_frame_build_time_millis & other benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56298]
also affects the cull_opacity_perf__timeline_summary 90th_percentile_frame_rasterizer_time_millis, 90th_percentile_vsync_transitions_missed, 99th_percentile_vsync_transitions_missed, average_vsync_transitions_missed. 

Very clear signal at engine roll https://github.com/flutter/flutter/pull/56162.

![Screen Shot 2020-05-04 at 8 44 28 AM](https://user-images.githubusercontent.com/1435716/80985011-7cda5f00-8de3-11ea-9d59-1e6676d31b0c.png)

**Comment by kf6gpe** [comment]
Looks like flutter_gallery_ios32__transition_perf 90th_percentile_frame_rasterizer_time_millis is affected too.

**Comment by liyuqian** [comment]
I confirmed locally that the regression is caused by https://github.com/flutter/engine/commit/4e2973633d6b8e0bf0c26b33fa61254e09fd1384. Will revert that in the engine and wait for the engine roller to fix this regression.

**Comment by liyuqian** [comment]
The revert has been rolled in https://github.com/flutter/flutter/pull/56378
