### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by DavidSonNguyen** [flutter/flutter#56296]
**I use POST method**

`http.Response response = await http.post(
      getUri(api, queryParameters),
      headers: callHeader,
      body: body,
    );`

**With getUri**: 
`Uri getUri(String api, [Map<String, String> queryParameters]) {
    Uri uri = Uri.http(_baseUrl, api, queryParameters);
    Logger('url').log(uri.toString());
    return uri;
  }`

**Header:** {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiOTQ0OTJkM2YtMThiNi00MTY1LTliMTYtMmQ3Y2U5ODQ1MDNhIiwiRGlzcGxheU5hbWUiOiJOZ3V54buFbiBHaWFuZyBWxKkgU8ahbiIsImV4cCI6MTU4ODY4ODc1MH0.NH3ZPEcL6zvy6BshjkSvutrPc512TwEAK8Lxcx1LKNE"}

I call post method WITHOUT header, It worked. But when I add header, I got exception: 

**Connection closed before full header was received**

I tried on an emulator and real device with Android Q, P, O and iOS simulator

Note: GET method is OK.

flutter doctor:
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-VN)
    • Flutter version 1.12.13+hotfix.9 at /Users/davidsonnguyen/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/davidsonnguyen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 2 XL                • 712KPJP1162580 • android-arm64 • Android 10
      (API 29)
    • Android SDK built for x86 • emulator-5554  • android-x86   • Android 8.1.0
      (API 27) (emulator)

https://github.com/flutter/flutter/issues/32696

**Comment by DavidSonNguyen** [comment]
It can only work when the body is parsed from Map<String, String>

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
