### ISSUE TITLE
web_benchmarks_canvaskit bench_picture_recording.canvaskit.estimatePaintBounds.average regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56300]
Looks like this engine roll: https://github.com/flutter/flutter/pull/55351.

![Screen Shot 2020-05-04 at 8 49 02 AM](https://user-images.githubusercontent.com/1435716/80985468-1efa4700-8de4-11ea-9783-0c17beb0704f.png)

**Comment by liyuqian** [comment]
Chatted with @dnfield (who chatted with @yjbanov) offline. We believe that we can  remove the TODAY label as the canvaskit backend is still experimental.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/55389

**Comment by liyuqian** [comment]
Thanks Jason! Closing this duplicate in favor of #55389.
