### ISSUE TITLE
Downloading Dart SDK from Flutter engine is failed

### ISSUE THREAD

**Issue by jahidRatul** [flutter/flutter#56313]
I am facing problem to install Flutter sdk. And I am from Bangladesh.
![failed](https://user-images.githubusercontent.com/30231712/80999036-ca97ab80-8e65-11ea-9b34-0bb3e8131191.png)

 jahidratul@darkShadow:~$ flutter doctor
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:10 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/af51afceb8886cc11e25047523c4e0c7e1f5d408/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china

**Comment by VladyslavBondarenko** [comment]
@jahidRatul 
Bangladesh seems to be having a firewall as well.
Try https://flutter.dev/community/china. Mirrored urls should solve the problem, closing.
Comment please if it doesn't help and I'll reopen
