### ISSUE TITLE
navigator.pop() leaks an animation controller

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5631]
When you call `Navigator.pop()`, the `Navigator` gives up ownership of the `Route`, but the `Route` still has an active `AnimationController`.

**Comment by eseidelGoogle** [comment]
Leaks are just slow crashes.  Any known crasher will block some set of shippers.

**Comment by goderbauer** [comment]
After https://github.com/flutter/flutter/pull/42777 has been submitted, the number of active AnimationControllers before a push is the same as after a pop of the pushed route (after GC).
