### ISSUE TITLE
[gen_l10n] Move localizations tool to flutter/engine to support prebuilt snapshots

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#56321]
Currently the gen_l10n.dart tool will run from source in the Dart SDK. This is problematic because it necessitates a slower startup, and could break if the source tree is missing the .packages/package_config files. 

Instead it should be built in the engine and downloaded as a snapshot, similar to other dart tools that we depend on like the frontend_server and const_finder.

@shihaohong

**Comment by christopherfujino** [comment]
@shihaohong is this not gonna move into the flutter tool?

**Comment by shihaohong** [comment]
@christopherfujino Thanks for the reminder, this slipped my mind. I'll put this on my queue.

**Comment by jonahwilliams** [comment]
This was moved into the flutter tool, closing as obsolete
