### ISSUE TITLE
subtreeContext exception after pressing back button twice

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#5632]
Run Gallery in debug mode.  Enter Shrine, and click on one of the product tiles.  Press the Back button twice in quick succession.

This produces the exception below.

The same thing happens if I click on a recipe in Pesto and hit Back twice.

The bug is timing sensitive - I haven't seen it happen in profile mode

I/flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter : The null object does not have a getter 'subtreeContext'.
I/flutter : NoSuchMethodError: method not found: 'subtreeContext'
I/flutter : Receiver: null
I/flutter : Arguments: []
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter : #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:527)
I/flutter : #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:535)
I/flutter : #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:503)
I/flutter : #5      _beginFrame (file:///ssd2/sky/engine/src/flutter/lib/ui/hooks.dart:48)
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
I think I have a fix for that.

**Comment by Hixie** [comment]
Specifically https://github.com/flutter/flutter/pull/5633

**Comment by Hixie** [comment]
Boo, that doesn't actually fix it.

**Comment by Hixie** [comment]
Ok the problem here is subtly different. The problem here is that between scheduling the quest update and actually starting the heroes, we are handling a quest completion, which clears our variables and thus we lose track of what we're about to do.

**Comment by Hixie** [comment]
ok, actual fix is in that PR now
