### ISSUE TITLE
Warn if decoded image size is much larger than the displayed size

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#56332]
(_Splitting off from https://github.com/flutter/flutter/issues/48885#issuecomment-622027219_)

Currently if `cacheWidth` and `cacheHeight` are not specified, we decode and cache the image at its original size.  I've seen people being unaware of this and accidentally using much more memory than they expect.

Until using `ResizeImage` is default and opt-out, can we emit warnings or other diagnostics when the decoded image size turns out to be much larger than the displayed size? (We probably should do so only if `cacheWidth` and `cacheHeight` are omitted so that people can still explicitly choose to decode a larger image without warnings.)

**Comment by dnfield** [comment]
See also: https://github.com/flutter/flutter/issues/51584

I like this idea, but I'm wondering if it will end up being less helpful than intended.

- A developer sees this warning when using a small resolution phone, adds hard coded parameters, now the image looks bad on a higher resolution phone.
- A developer sees this warning and adds parameters, but finds that they have no way to determine the aspect ratio of the image to know how to keep it for a dynamically loaded image.
- A developer never sees this warning even though they're dynamically loading large images at runtime, e.g. via network requests. Or, they see it, but have no idea what to put since they don't know the size ahead of time (the image is from the wild, or it's coming from a poorly designed image resource service that doesn't allow you to only request the resolution appropriate for the device).

**Comment by dnfield** [comment]
Another way of tackling this problem is to provide better memory debugging and visualization tools for Flutter.

For example, if a developer can easily see memory usage while running the app, and ideally see what objects are retaining that memeory (e.g. which images are using a lot of memory), they could try to determine what ot do.

**Comment by jamesderlin** [comment]
Providing better memory debugging tools would be great, but people would need to know to look at memory usage in the first place.  They might be oblivious.

The warning perhaps could be restricted to cases where `width` and `height` are specified but not `cacheWidth` and `cacheHeight`. (Are `width`/`height` in logical units and `cacheWidth`/`cacheHeight` in pixels?  This perhaps is something else that could be clarified in the documentation.)

**Comment by dnfield** [comment]
I think I have an idea of how we could do this. At one point I was trying this with an assert but that's too strong. We could, however, provide a debug flag that users could set, and that we could have settable via the service protocol for devtools/IDE plugins. Then, if that flag is enabled, when we get the size for the render image, we could report an error if the render size is less than the size of the image (perhaps within a certain percentage, to avoid reporting differences of just a few pixels).

**Comment by dnfield** [comment]
This will still have the problems noted above, but at least if it's opt-in and off by default we can assume the developer is more aware of those.

**Comment by dnfield** [comment]
I landed a patch that enables this opt-in. I'm going to do some experiments with it once it rolls into g3 so I can see if it makes sense to clean up some callsites/enable it for tests.

**Comment by stepanov-standy** [comment]
Hi Team, really great idea and implementation, but I am a little bit confused. Am I right that image width/height parameters are in logical pixels, but cachedWidth/cachedHeight are in physical pixels? If so, then we compare different dimensions. I have tested this logic on my real device:
phone: Pixel 3a 
screen size (physical pixels): 1080x2220
screen size (logical pixels): 392x807
device pixel ratio: 2.75

I want to render a square image in 1-to-1 pixel quality. In other words I would like to render an image with size 1080x1080 physical pixels. To do so I calculate device screen physical size using the following code:

```
MediaQueryData mediaQuery = MediaQuery.of(context);
_screenWidthInPx = mediaQuery.size.width * mediaQuery.devicePixelRatio;
```

I use the following code to render an image:

```
Image.asset(
                                                  "assets/images/emptyava.webp",
                                                  fit: BoxFit.cover,
                                                  cacheWidth: _screenWidthInPx,
                                                  cacheHeight: _screenWidthInPx,
                                              )
```

As a result I see a pixel perfect image on the screen, but when I enable the flag:

`debugInvertOversizedImages = true;`

The image is inverted with the following warning message:
Image assets/images/emptyava.webp - Resized(1080×1080) has a display size of 392×392 but a decode size of 1080×1080...

When I provide cacheWidth/cacheHeight in logical pixels as it is suggested by the warning message (392x392) I see "pixelated" image. It looks like I ask flutter to resize my original 1080x1080 image to the size 392x392 and later stretch it to cover 1080px of the screen.

What Is wrong in my experiment and expectations?

**Comment by itschrono** [comment]
> @jamesderlin and @dnfield, really great idea and implementation, but I am a little bit confused. Am I right that image width/height parameters are in logical pixels, but cachedWidth/cachedHeight are in physical pixels? If so, then we compare different dimensions. I have tested this logic on my real device:
> phone: Pixel 3a
> screen size (physical pixels): 1080x2220
> screen size (logical pixels): 392x807
> device pixel ratio: 2.75
> 
> I want to render a square image in 1-to-1 pixel quality. In other words I would like to render an image with size 1080x1080 physical pixels. To do so I calculate device screen physical size using the following code:
> 
> ```
> MediaQueryData mediaQuery = MediaQuery.of(context);
> _screenWidthInPx = mediaQuery.size.width * mediaQuery.devicePixelRatio;
> ```
> 
> I use the following code to render an image:
> 
> ```
> Image.asset(
>                                                   "assets/images/emptyava.webp",
>                                                   fit: BoxFit.cover,
>                                                   cacheWidth: _screenWidthInPx,
>                                                   cacheHeight: _screenWidthInPx,
>                                               )
> ```
> 
> As a result I see a pixel perfect image on the screen, but when I enable the flag:
> 
> `debugInvertOversizedImages = true;`
> 
> The image is inverted with the following warning message:
> Image assets/images/emptyava.webp - Resized(1080×1080) has a display size of 392×392 but a decode size of 1080×1080...
> 
> When I provide cacheWidth/cacheHeight in logical pixels as it is suggested by the warning message (392x392) I see "pixelated" image. It looks like I ask flutter to resize my original 1080x1080 image to the size 392x392 and later stretch it to cover 1080px of the screen.
> 
> What Is wrong in my experiment and expectations?

Seems like it is not taking into account `devicePixelRatio`...

**Comment by JustChris** [comment]
I am currently facing the exakt same thing! Do you have any news on that? @stepanov-standy

**Comment by JustChris** [comment]
But the "problem" will remain.

If I am displaying an image based on the logical display size, it will be pixelated.

If I am displaying an image based on the native screen resolution of the device, it will use lots of memory and give me those warnings.

Right?

Am I doing something wrong? Is there another way to display images?
This must be a very common problem, right?

**Comment by stepanov-standy** [comment]
No, warning message is wrong and doesn't take into account devicePixelRatio. Just display an image base on the native screen resolution of the device.

**Comment by JustChris** [comment]
Thank you very much! That was the answer is was hoping for :)

**Comment by Hannnes1** [comment]
I have opened a new issue about the problem here: https://github.com/flutter/flutter/issues/87869

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/88309 should fix that.
