### ISSUE TITLE
I need to clean my flutter project ever run

### ISSUE THREAD

**Issue by plotrekpl** [flutter/flutter#56334]
Hi I have problem with flutter, for every time I have to tipe

 `flutter clean` command because without this my project doesn't rebuild.
`flutter doctor` - without any problems

This is the same situation https://github.com/flutter/flutter/issues/16604

I try the newest flutter sdk flutter_windows_v1.12.13+hotfix.9-stable.zip
And also older version, and this not fixed the problem

How to fix this problems? Any ideas?

**Comment by VladyslavBondarenko** [comment]
Hi @plotrekpl could you check if you are experiencing this with current dev version `v1.18.0-8.0.pre`? https://github.com/flutter/flutter/issues/16604#issuecomment-584471236

**Comment by plotrekpl** [comment]
@VladyslavBondarenko Thanks, current version works
