### ISSUE TITLE
Upgrading packages to the latest version

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#56348]
## Use case

Some package managers like yarn (https://classic.yarnpkg.com/en/docs/cli/upgrade/) has a `--latest` option

```
--latest : Ignores the version range specified in package.json. Instead, the version specified by the latest tag will be used (potentially upgrading the packages across major versions).
```

## Proposal

`flutter pub get --latest` : Ignores the version range specified in pubspec.yaml. Instead, the version specified by the latest tag will be used (potentially upgrading the packages across major versions).

**Comment by jmagman** [comment]
Can you re-file this issue against [pub](https://github.com/dart-lang/pub/issues)?  When they implement, `flutter` tooling can pass the flag along.

**Comment by imeDevelopers** [comment]
@sm2017 @jmagman

Just remove the version number , let the version parameter empty .. and the flutter will get the latest version ...
