### ISSUE TITLE
flutter web shows old application not updated application on web 

### ISSUE THREAD

**Issue by aTeamSolace** [flutter/flutter#56359]
flutter build web command is updating changes at local server, but not on dev server. When i fired build web command it will update changes and show proper application and expected output.
but when i fire it on dev server the application is update it shows old app . 
so on local server no issues but on dev server not properly work. 
i fired flutter clean also but still shows old app ??

**Comment by aTeamSolace** [comment]
here is my flutter doctor output on dev server

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by niklasbartsch** [comment]
Have you tried to add a version in your `index.html`?
Otherwise you have to delete your cache.

It should look like this:
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>to_cache_or_not_to_cache</title>
  </head>
  <body>
    <script src="main.dart.js?version=1" type="application/javascript"></script>
  </body>
</html>`

**Comment by VladyslavBondarenko** [comment]
Hi @aTeamSolace 
is `flutter build web` finished successfully on dev, right?
Is it matter of caching? Try refresh with "Empty cache and hard reload"

**Comment by Mravuri96** [comment]
I believe the issues here is, by default the "new" service worker gets in a waiting state, at least until the old service worker is no longer controlling the client. We either have to update it by force (Empty cache and hard reload), or by implementing the skipWaiting function. more here.  https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_the_waiting_phase

**Comment by aTeamSolace** [comment]
@VladyslavBondarenko thanks the issue is related to cache.
