### ISSUE TITLE
Xcode 

### ISSUE THREAD

**Issue by khalidsharief** [flutter/flutter#56356]
(base) MacBooks-MacBook-Pro:~ macbookpro$  sudo xcodebuild -runFirstLaunch
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by TahaTesser** [comment]
Hi @khalidsharief 
Please give us more details?
Can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by khalidsharief** [comment]
Hello @tahaTesser here you go 

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132,
    locale en-AE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices availablev

**Comment by TahaTesser** [comment]
Hi @khalidsharief 
You don't have proper Xcode setup, make you've Xcode dowloaded and run it first time 
and also please follow this [Install Xcode guide](https://flutter.dev/docs/get-started/install/macos#install-xcode) and follow further steps and run the commands 
Thank you

**Comment by VladyslavBondarenko** [comment]
@khalidsharief 
I hope it's fixed, closing.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of `flutter doctor -v`  please.
