### ISSUE TITLE
Feature Request - Importing Multiple Assets in pubspec.yaml

### ISSUE THREAD

**Issue by ritvij-saxena** [flutter/flutter#56369]
I have been using flutter for quite some time whenever I have to import some assets ("static" assets), I have to type a lot of lines in the pubspec.yaml file.
[https://flutter.dev/docs/development/ui/assets-and-images]

What I was thinking was it would be great if there was something like

Instead of this (in pubspec.yaml) =>
- assets:
      - assets/folder/image1.jpg
      - assets/folder/image1.jpg
      - assets/folder/image3.jpg
      - assets/folder/image4.jpg
      - assets/folder/imageN.jpg

It could be like =>
- assets:
      - assets/folder/*.jpg

All files with .jpg would be imported. Similar can be done for fonts as well.

Thank you!

**Comment by Zazo032** [comment]
You can add `assets/folder` and that will import all the files in that directory. If you have subdirectories, you'll have to import them the same way too.

**Comment by ritvij-saxena** [comment]
That works for me! Cool! Thank you so much! Suppose there is an image in that folder, do I access it as usual? 
Image.asset('assets/image1.png')

**Comment by Zazo032** [comment]
Yes, usage remains the same.

**Comment by ritvij-saxena** [comment]
Awesome!. Thanks a lot!
