### ISSUE TITLE
Because flutter_tools depends on sse 3.5.0 which doesn't match any versions, version solving failed

### ISSUE THREAD

**Issue by caolongcl** [flutter/flutter#56364]
## Steps to Reproduce

1. git clone -b master https://github.com/flutter/flutter.git
2. flutter doctor

## Logs

PS C:\Enter\dev\cgdev\workspace> flutter doctor -v
Building flutter tool...
Running pub upgrade...
Because flutter_tools depends on sse 3.5.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 2 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? Y

**Comment by hengsoheak** [comment]
I feeling flutter too much error than react native

**Comment by Abhishek01039** [comment]
run your terminal as an administrator if you are using windows then try flutter doctor -v

**Comment by VladyslavBondarenko** [comment]
@caolongcl 
does it happen with other channels (stable/dev/beta)?

**Comment by imeDevelopers** [comment]
Are you sure you installed android studio 3.5.0 or later ?

**Comment by caolongcl** [comment]
> run your terminal as an administrator if you are using windows then try flutter doctor -v
> if you have any anti-virus in your PC then stop it and try it again

Hi, I try like you say and I don't have any anti-virus in your PC except 'Windows Security', but show the same error.
![flutter_errors](https://user-images.githubusercontent.com/18400475/81184723-53882180-8fe3-11ea-92cb-02bee2c7bd49.jpg)
![flutter_errors1](https://user-images.githubusercontent.com/18400475/81184731-55ea7b80-8fe3-11ea-8d8a-3a2872144dbf.jpg)

**Comment by caolongcl** [comment]
> Are you sure you installed android studio 3.5.0 or later ?

Yes, I installed android studio 3.6.3

**Comment by caolongcl** [comment]
> @caolongcl
> does it happen with other channels (stable/dev/beta)?

I try the beta 1.17.0-3.4.pre and dev 1.18.0-10.0.pre, and no error, so maybe I should use the pre or dev channel for now

**Comment by iapicca** [comment]
Hi @caolongcl 
if I understand correctly you are not experiencing the issue in channel dev
could you please provide 
`flutter doctor - v `on dev channel
and if you feel like it
after that running 
```console
flutter chanel master
flutter upgrade --force --verbose
```
reporting the logs
thank you

**Comment by caolongcl** [comment]
> Hi @caolongcl
> if I understand correctly you are not experiencing the issue in channel dev
> could you please provide
> `flutter doctor - v `on dev channel
> and if you feel like it
> after that running
> 
> ```
> flutter chanel master
> flutter upgrade --force --verbose
> ```
> 
> reporting the logs
> thank you

Hi, below is log:

PS C:\Users\caolong> flutter doctor -v
[√] Flutter (Channel beta, v1.17.0-3.4.pre, on Microsoft Windows [Version 10.0.18363.815], locale zh-CN)
    • Flutter version 1.17.0-3.4.pre at C:\Enter\dev\cgdev\workspace\flutter
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\caolong\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\caolong\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

PS C:\Users\caolong> flutter channel master
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    e0c63cd35..9b7b9d795  dev             -> origin/dev
git:    e6b34c2b5..28c00980a  flutter-1.17-candidate.3 -> origin/flutter-1.17-candidate.3
git:  * [new branch]          flutter-1.18-candidate.8 -> origin/flutter-1.18-candidate.8
git:  * [new branch]          flutter-1.18-candidate.9 -> origin/flutter-1.18-candidate.9
git:    5db02b490..8568eda15  master          -> origin/master
git:  + f139b1100...e6b34c2b5 stable          -> origin/stable  (forced update)
git:  * [new tag]             1.17.0          -> 1.17.0
git:  * [new tag]             1.18.0-10.0.pre -> 1.18.0-10.0.pre
git:  * [new tag]             1.18.0-9.0.pre  -> 1.18.0-9.0.pre
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
git: Switched to a new branch 'master'
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

PS C:\Users\caolong> flutter upgrade --force --verbose
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 33d2367950154e7f8daf9ce9992a450016289a5f...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Because flutter_tools depends on sse 3.5.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
^CTerminate batch job (Y/N)? Y

**Comment by ctrysbita** [comment]
@caolongcl That is because you are using a pub mirror from flutter-io.cn or TUNA which contains outdated package. Switch to official pub should resolve the problem.

**Comment by wen-carl** [comment]
Same issue with channel master.

**Comment by VladyslavBondarenko** [comment]
@wen-carl with what master version are you experiencing this?
does it work with 
> I try the beta 1.17.0-3.4.pre and dev 1.18.0-10.0.pre, and no error

**Comment by wen-carl** [comment]
@VladyslavBondarenko 
I am sorry I don't know what version it is, because 'flutter --version' depends on 'Building flutter tool...', and after that log message is 'Because flutter_tools depends on sse 3.5.0 which doesn't match any versions,
  version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)';
I think it may be latest version, not sure. And now any commands can not work about 'flutter'.

**Comment by jmagman** [comment]
@caolongcl Are you using a mirror as @ctrysbita suggested?

**Comment by GavinHome** [comment]
I had the same issue on the main branch. I removed "FLUTTER_STORAGE_BASE_URL" and "PUB_HOSTED_URL" in the environment variables, and then ran the command "flutter doctor -v". It took a long time (many hours), but no response.

However, as long as they are set up, such problems will occur.

FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
PUB_HOSTED_URL:https://pub.flutter-io.cn

**Comment by timsneath** [comment]
@chenglu can you help here?

**Comment by chenglu** [comment]
on my way...

**Comment by zmtzawqlp** [comment]
> I had the same issue on the main branch. I removed "FLUTTER_STORAGE_BASE_URL" and "PUB_HOSTED_URL" in the environment variables, and then ran the command "flutter doctor -v". It took a long time (many hours), but no response.
> 
> However, as long as they are set up, such problems will occur.
> 
> FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
> PUB_HOSTED_URL:https://pub.flutter-io.cn

![image](https://user-images.githubusercontent.com/16477333/81461648-c9f17300-91df-11ea-865e-9a2e09a8bfa2.png)

It works at my side.

**Comment by GavinHome** [comment]
@zmtzawqlp @chenglu @jmagman @timsneath Thanks, it works now

**Comment by wen-carl** [comment]
@VladyslavBondarenko Thanks, it works now.

**Comment by jmagman** [comment]
@chenglu Thank you!  Closing.
