### ISSUE TITLE
Scrollaway appbar should not re-appear during overscroll bounce

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5636]
Easy to see in Contacts demo in Gallery.  Turn on "scrollaway" mode, and then scroll to the bottom, notice how the appbar disappears as you scroll down only to reappear when yous scroll bounce.

This presumably only occurs on iOS, due to the scroll bounce behavior.

https://youtu.be/epedZsspsO8

This doesn't need to block Gallery 1.0.

**Comment by Hixie** [comment]
Fixed.
