### ISSUE TITLE
[webview]How to change webview defalut language?

### ISSUE THREAD

**Issue by jet10000** [flutter/flutter#56361]
I build a app with webview , when I click upload image, display english menu. My iphone is chinese.  

How to change the default language for webview?

thanks.

**Comment by TahaTesser** [comment]
Testing `webview_flutter` with [Internationalizing Flutter apps
](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) does seem to be change language for `webview_flutter`

**Comment by Anirudhk07** [comment]
#56361 You can dynamically add webview and after that reinitialize your language to Chinese .This would resolve your issue.

**Comment by jet10000** [comment]
@Anirudhk07 
Can you give a demo? How to do it?

**Comment by yaostyle** [comment]
@jet10000 I hope I understand your question correctly -- that is you want to replace the default file `<input>` attribute in Chinese character, correct? 

I believe you can do a simple HTML/CSS hack to the `<input>` attribute from the remote HTML page instead. Then, users can tap on the custom file-input button from webview without issue.

**My example as following:**
1.) Hack your <input> attribute from remote page
![Screenshot from 2020-08-14 11-52-03](https://user-images.githubusercontent.com/14081948/90284523-f7753a80-de26-11ea-894a-c7ce2a44b30c.png)

**2.) Hide the default `<input> `via CSS**
![Screenshot from 2020-08-14 11-52-16](https://user-images.githubusercontent.com/14081948/90284621-14117280-de27-11ea-9ddb-d79bcfd103c5.png)

**Final result (default v.s. hacked):**
![result](https://user-images.githubusercontent.com/14081948/90285123-1e803c00-de28-11ea-93f2-ff7e5574471d.jpg)

**Comment by blasten** [comment]
This has been fixed in Flutter 1.22/ WebView 1.0 - use hybrid composition in the Flutter WebView plugin.

https://github.com/flutter/plugins/tree/master/packages/webview_flutter#using-hybrid-composition
