### ISSUE TITLE
Tabs seem too sensitive to flings.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5637]
Compare to say the bottom nav behavior of Google Photos on iOS (presumably it has tabs on Android, not sure).

Very low velocity flings are able to cause the tabs to change.

https://youtu.be/DBWjzYLEA2k

This does not need to block Gallery 1.0 imo.

**Comment by eseidelGoogle** [comment]
I wonder if this changes as part of the scrolling refactor or @HansMuller's recent tab rework.

**Comment by Hixie** [comment]
I think @xster or @collinjackson fixed this a while back. I'm going to close this; please reopen if you still see it.

**Comment by xster** [comment]
I didn't work on the tab physics. But tested it in the gallery. It's definitely a lot nicer than in the YouTube video. So leaving closed.
