### ISSUE TITLE
Engine scenario_app iOS golden images can only be generated from Emmanuel's Mac

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#56388]
Both @cyanglaz and I have tried to generate the golden images for https://github.com/flutter/engine/pull/17915. Although our locally generated images can pass the test locally, they fail in LUCI bots. It turns out that only images generated from @blasten 's Mac can let LUCI bots pass the test. According to Emmanuel, the golden images generated by me has no pixel difference with his images. But the test with my images somehow failed in his Mac and LUCI. This suggest that the pixel comparison in the test might be problematic.

**Comment by blasten** [comment]
Yes - the pixel comparison logic is boosted. Thanks for filing this

**Comment by krispypen** [comment]
https://github.com/flutter/flutter/issues/56383#issuecomment-627173845

**Comment by chinmaygarde** [comment]
The bus factor on this issue is worrying. @blasten Can we make this independent of the platform? Perhaps by making the rasterizer generate the screenshot?

**Comment by blasten** [comment]
@chinmaygarde rasterizer won't work unfortunately since the screenshots also need to contain the platform views.

**Comment by cyanglaz** [comment]
@chinmaygarde @blasten I have invested some time looking into making the rasterizer screenshot work with platform views. (on iOS) Maybe we should invest more on that. see https://github.com/flutter/flutter/issues/23435

**Comment by blasten** [comment]
Maybe if the external view embedder had a way to transform the native view into a texture, then we could replace the platform view layer with a texture layer. I imagine this works for free on Android if using virtual displays. 


In regard to the comparison logic, I had a local patch that fixes it. Currently, we expect the image metadata to be equal to the golden image. The metadata is host machine dependent. My patch does a diff and fails the test if a pixel differs.

**Comment by blasten** [comment]
This was fixed by @gaaclarke
