### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for E:\app\flutter_app\android\gradlew.bat.

### ISSUE THREAD

**Issue by Bhautik004** [flutter/flutter#56395]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=94e6ea91 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for E:\app\flutter_app\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-IN)
    • Flutter version 1.17.0-3.4.pre at C:\flutter
    • Framework revision e6b34c2b5c (3 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\2000b\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Redmi Note 7 Pro • 94e6ea91 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f

**Comment by iapicca** [comment]
Hi @Bhautik004 
can you please provide your full `flutter run --verbose` 
Thank you

**Comment by amikum1997** [comment]
$ flutter run --verbose
[  +17 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +177 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.0
           1.17.0-3.4.pre
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +81 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +50 ms] Downloading Gradle Wrapper...
[  +12 ms] Downloading: https://storage.googleapis.com/flutter_infra/gradle-wrapper/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz
[ +963 ms] Received response from server, collecting bytes...
[ +130 ms] Downloading Gradle Wrapper... (completed in 1.1s)
[  +82 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] List of devices attached
           5aee3bcc               device product:1951 model:vivo_1951 device:1951 transport_id:1
[   +6 ms] C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell getprop
[  +80 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +191 ms] Generating E:\PROJECTS\FLUTTER\abhilasha\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +32 ms] ro.hardware = qcom
[  +33 ms] Launching lib\main.dart on vivo 1951 in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\HP\AppData\Local\Temp\flutter_tool.0c6da4b4-948c-11ea-859a-a0605d4bfc4b\app.dill --packages E:\PROJECTS\FLUTTER\abhilasha\.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +14 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell -x logcat -v time -t 1
[ +224 ms] Exit code 0 from: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell -x logcat -v time -t 1
[        ] --------- beginning of main
           05-13 01:36:23.496 I/SDM     (  649): HWDeviceDRM::SetupAtomic: Disable DE for Non YUV
[   +5 ms] <- compile package:abhilasha/main.dart
[  +13 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +38 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +38 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +17 ms] C:\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat mode: 33279 rwxrwxrwx.
[        ] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat mode: 33279 rwxrwxrwx.
[        ] Using gradle from E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat.
[        ] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +157 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +4 ms] executing: [E:\PROJECTS\FLUTTER\abhilasha\android/] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\PROJECTS\FLUTTER\abhilasha\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[   +3 ms] Running Gradle task 'assembleDebug'... (completed in 0.2s)
[+5415 ms] "flutter run" took 7,670ms.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat.".
[+2336 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +77 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +14 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 10 days ago
A crash report has been written to E:\PROJECTS\FLUTTER\abhilasha\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/Jf8ow

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jf8y8

**Comment by iapicca** [comment]
Hi @Bhautik004 
I see there's an open [issue](https://github.com/flutter/flutter/issues/53790) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
