### ISSUE TITLE
Flutter wont start on iOS simulator for example app

### ISSUE THREAD

**Issue by matej-snivam** [flutter/flutter#5640]
## Steps to Reproduce

I try to start app after configuring flutter, and I get this output inside terminal

`Running lib/main.dart on iPhone 5s...
ondemandd: ondemandd is starting up...
ondemandd: ondemandd is starting up...
ondemandd: ondemandd is starting up...
ondemandd: ondemandd is starting up...
syslogd: ASL Sender Statistics
ondemandd: ondemandd is starting up...
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
`
## Flutter Doctor

`[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/matej/IdeaProjects/flutter/flutter
    • Framework revision 9a0a0d9903 (2 weeks ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /Users/matej/Library/Android/sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
`
## Logs and Crash Reports

[This](http://pastebin.com/YMXNMQCr) is paste from verbose mode, and I dont get any logs. Device is iPhone 5s simulator

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
Looks like this is on the alpha branch.  I believe we've had other reports of simulator not working there.  @danrubel or @chinmaygarde would you be willing to check?  It may be time to just remove alpha since we're not actively keeping it up to date with master.

**Comment by matej-snivam** [comment]
after I switch to master I get similar error

http://pastebin.com/yi8k6Vfb

**Comment by eseidelGoogle** [comment]
Thanks.  I don't see any errors in that output.  Which is likely itself an error in our tooling. :/

**Comment by eseidelGoogle** [comment]
One workaround is to open up ios/Runner.xcodeproj and run directly from XCode, but you shouldn't have to do that `flutter run` should work.

**Comment by matej-snivam** [comment]
This is without verbose mode

`Running lib/main.dart on iPhone 5s...
securityd:  SOSKeychainCopySavedAccountData Failed to load account: Error Domain=NSOSStatusErrorDomain Code=-25300 "Error (null) reading for service 'iCloud Keychain Account Meta-data'" UserInfo={NSDescription=Error (null) reading for service 'iCloud Keychain Account Meta-data'}
syslogd: Disabling module com.apple.securityd writes to /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/security.log following 6 failures (Operation Failed)
CloudKeychainProxy:  __45-[UbiqitousKVSProxy doEnsurePeerRegistration]_block_invoke <UB---e-C---> ensurePeerRegistration called, success ((null))
IDSKeychainSyncingProxy:  -[IDSKeychainSyncingProxy doSetIDSDeviceID:] Error Domain=com.apple.security.ids.error Code=-1 "IDSKeychainSyncingProxy could not retrieve device ID from keychain" UserInfo={NSLocalizedDescription=IDSKeychainSyncingProxy could not retrieve device ID from keychain}
securityd:  __SOSTransportMessageIDSGetIDSDeviceID_block_invoke Could not ask IDSKeychainSyncingProxy for Device ID: Error Domain=com.apple.security.ids.error Code=-1 "IDSKeychainSyncingProxy could not retrieve device ID from keychain" UserInfo={NSLocalizedDescription=IDSKeychainSyncingProxy could not retrieve device ID from keychain}
securityd:  __talkWithIDS_block_invoke_2 talkwithIDS callback error: Error Domain=com.apple.security.ids.error Code=-1 "IDSKeychainSyncingProxy could not retrieve device ID from keychain" UserInfo={NSLocalizedDescription=IDSKeychainSyncingProxy could not retrieve device ID from keychain}
healthd: (Error) MC: MobileContainerManager gave us a path we weren't expecting; file a radar against them
	Expected: /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
	Actual: /Users/matej/Library/Developer/CoreSimulator/Devices/48373847-81AB-42BF-A8D4-EEA0170151B2/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
	Overriding MCM with the one true path
healthd: PairedSync, Debugging at level 0 for console and level 0 for log files
healthd: Error: Could not create service from plist at path: file:///Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PairedSyncServices/com.apple.pairedsync.healthd.plist. Returning nil PSYSyncCoordinator for service name com.apple.pairedsync.healthd.  Please check that your plist exists and is in the correct format.
healthd: Error: failed to load bundle "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Health/Plugins/CompanionHealth.bundle": Error Domain=NSCocoaErrorDomain Code=4 "The bundle “CompanionHealth.bundle” couldn’t be loaded because its executable couldn’t be located." UserInfo={NSLocalizedFailureReason=The bundle’s executable couldn’t be located., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSBundlePath=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Health/Plugins/CompanionHealth.bundle, NSLocalizedDescription=The bundle “CompanionHealth.bundle” couldn’t be loaded because its executable couldn’t be located.}
suggestd: table drop: 101
suggestd: 2016-08-30 14:57:28.610+0530|67271|0x7f8572e10d60|EventKit: __44-[EKEventStore insertSuggestedEventCalendar]_block_invoke_3: Could not insert the Found in Mail calendar with error Error Domain=EKCADErrorDomain Code=1012 "(null)"
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
routined: Connection interrupted!
suggestd: Connection interrupted!
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
syslogd: ASL Sender Statistics
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
`

**Comment by brianegan** [comment]
+1... Been running on my Android Emulator and wanted to switch over to iOS to quickly try your integration testing solution, but using the alpha branch didn't work for me :(

**Comment by danrubel** [comment]
I connected a new iPod Touch, ran `flutter run -d ipod`, and it failed in a similar way.
This is what I did to get it working...
* `open ios/Runner.xcodeproj/` to open the flutter ios project in XCode
* enable developer mode in XCode
* sign in with my Apple Developer ID to get a signing cert
* update the app bundle identifier to start with `com.<my-apple-dev-id>.`
* delete libPods-*.a file in the Frameworks folder
* verify the developer app certificate on the connected ipod device

At this point, I can launch it from XCode and see it run on the iPod.
Next, I closed XCode and tried to run it from the command line...
```
$ flutter run -d ipod
Running lib/main.dart on iPod touch...
Could not find the built application bundle at build/ios/Release-iphoneos/Runner.app.
Error running application on iPod touch.

$ flutter run --debug -d ipod
Running lib/main.dart on iPod touch...
Could not find the built application bundle at build/ios/Release-iphoneos/Runner.app.
Error running application on iPod touch.
```
After some splunking into the build directory...
```
$ flutter build ios
$ cp -r build/ios/Debug-iphoneos/ build/ios/Release-iphoneos/
$ flutter run -d ipod
```
... and it worked.

I'm new to iOS development so some of the steps above may not be necessary, but this worked for me. Not yet sure why I had to copy `Debug-*` over to `Release-*`.

**Comment by eseidelGoogle** [comment]
CC @chinmaygarde.  `flutter run` should "just work".  And no amount of signing configuration should be necessary for simulators (but will be necessary for devices, sadly).

**Comment by devoncarew** [comment]
@danrubel, just to confirm, you have a copy of the iOS simulator running?

**Comment by danrubel** [comment]
Nope. It's probably in the docs or a tutorial somewhere and I just missed it. My opinion is that the flutter tool should have pointed that out and provided information about how I should go about installing / configuring it. Guess it's something I need to investigate and fix :-)
https://github.com/flutter/flutter/issues/5674

**Comment by devoncarew** [comment]
Yes, I think it's something that other users have hit as well.

**Comment by eseidelGoogle** [comment]
I'm not sure there is anything more to do here.  FYI @cbracken @xster (to see some of the historical trouble folks have had getting flutter run working with ios).

Happy to help diagnose newer flavors of this bug.  We now have several folks working on our iOS side of things and we believe our tooling to be much more stable.  Please file a new bug if you're still having trouble and i promise we'll resolve it much quicker this time. :/

**Comment by xster** [comment]
Should we interpret this as: for quality of life improvements, we can prompt the user to with an option to start an android or ios emulator for them if nothing is connected?

**Comment by abarth** [comment]
That sounds like a good idea.

**Comment by xster** [comment]
#7863

**Comment by nohrix** [comment]
I faced this challenge and it stalled my learning and development for 2 weeks. 
Luckily I have solved it. I carefully ensured that Flutter, Xcode were properly installed, then in the project terminal in Android Studio, I ran Flutter Clean. 

After that, I realised that the app installed on the iOS simulator and am able to run it. 

SO RUN Flutter Clean
