### ISSUE TITLE
flutter_tools crash might exit before reporting the crash

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#56406]
I noticed that in internal bug b/155482533, the flutter tool crashed but did not print the expected instructions for reporting the crash.  This occurs with the upstream tool too (and the behavior predates my recent change to move `_informUserOfCrash`).

## Steps to reproduce:
1. Apply a patch:
```patch
diff --git a/packages/flutter_tools/lib/src/resident_runner.dart b/packages/flutter_tools/lib/src/resident_runner.dart
index 0f328b2bf..1bea679fa 100644
--- a/packages/flutter_tools/lib/src/resident_runner.dart
+++ b/packages/flutter_tools/lib/src/resident_runner.dart
@@ -1481,6 +1481,8 @@ class TerminalHandler {
       case 'Z':
         await residentRunner.debugToggleDebugCheckElevationsEnabled();
         return true;
+      case '_':
+        throw Exception('Test exception');
     }
     return false;
   }
```

2. Go to some Flutter project (I'm using a Linux environment with an Android project and emulator), run `flutter run`, press `_` to force throwing an uncaught exception. (This is a simplification; you'll want to run the `flutter` tool from source.)

## Result:
```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available
at: http://127.0.0.1:40521/J48yQjaVv0M=/

Exception: Test exception
#0      TerminalHandler._commonTerminalInputHandler
(package:flutter_tools/src/resident_runner.dart:1485:9)
#1      TerminalHandler.processTerminalInput
(package:flutter_tools/src/resident_runner.dart:1500:13)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
...
#46     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
Application finished.

Oops; flutter has exited unexpectedly: "Exception: Test exception".
```

The expected messages about generating a crash report and reporting an issue on GitHub are missing.  The tool's exit code also is 0 instead of an expected non-zero.

I looked into this a bit, and it seems like the tool is going down the expected `_handleToolError` failure path.  However, it seems like the process abruptly exits prematurely before `_handleToolError` finishes.

**Comment by jamesderlin** [comment]
I looked into this a little more. `runner.run()` does:

```dart
    return await runZoned<Future<int>>(() async {
      try {
        await runner.run(args);
        return await _exit(0);
      } catch (error, stackTrace) {
        ...
        return await _handleToolError(...);
      }
    }, onError: (Object error, StackTrace stackTrace) async {
      ...
      await _handleToolError(...);
    });
```
When the exception is thrown, I observe it triggering `runZoned`'s `onError` handler instead of the inner `catch` block.  Even weirder, somehow execution continues in the `try` block. (I don't understand `Zone`s, and this makes no sense to me.) We then end up with concurrent calls to `_exit(0)` and `_handleToolError()`, and `_exit(0)` terminates the tool before `_handleToolError` finishes.

Checking if any of the error paths were triggered before calling `_exit(0)` does seem to fix this, but that's a gross hack.

**Comment by mehmetf** [comment]
That's really odd. I have been dealing with error zones in the context of dartdoc recently as well: https://github.com/dart-lang/dartdoc/pull/2209#issuecomment-629019645

In Dartdoc, a catch block inside the error zone works as expected (I just tried it) so I have no clue why the exception thrown in runner.run() is becoming an uncaught exception. It is very suspicious that try block continues executing. The only way I can imagine that happening is if the catch block itself is throwing an exception, which then becomes uncaught.

**Comment by jamesderlin** [comment]
I think I have a better understanding of what's going on now.  You can observe similar behavior with:

```dart
void main() {
  runZonedGuarded(
    () async {
      Timer(const Duration(seconds: 0), () {
        print('Throwing exception');
        throw Exception('An exception');
      });

      // Give the Timer time to fire.
      await Future<void>.delayed(const Duration(seconds: 1));
      print('Zone done');
    },
    (e, stackTrace) {
      print('runZoned onError');
    },
  );
}
```
The exception is not thrown directly by the `Zone` body; it's thrown by some other task processed by the event queue. (I'm not sure if I'm using the right terminology.) The exception triggers the error callback, but since the `Zone`'s body did not directly throw the exception, it keeps executing.  I'm not sure if that's the intended behavior; it seems a bit surprising but also doesn't seem unreasonable.

I don't think that there are any `Timer`s involved in this Flutter tool case, but I'm guessing there's something similar happening when the exception is thrown in response to a keyboard event.

I don't know if there's some good way of dealing with this, but maybe [the hack I suggested earlier](https://github.com/flutter/flutter/issues/56406#issuecomment-627107089) isn't so gross after all.

**Comment by jamesderlin** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/58474.
