### ISSUE TITLE
Integrate the Metal test harness into the shell/gpu on Darwin

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#56405]
Currently, there are no such tests in the engine.

@chinmaygarde

**Comment by chinmaygarde** [comment]
That's not entirely true. The [test harness is setup for Metal](https://github.com/flutter/engine/blob/master/testing/test_metal_surface.h) on the host but it needs to be integrated in to the shell/gpu target on Darwin.

**Comment by jonahwilliams** [comment]
Closing as out of date
