### ISSUE TITLE
Rerunning tests does not reflect new code 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#56403]
This was posted in [The dart lang issues repo](https://github.com/dart-lang/sdk/issues/40108) but they said to post it here. This is on 2 different flutter/dart versions.

Dart VM version: 2.8.0-dev.0.0.flutter-32ce9c7872 (Sat Jan 11 20:39:02 2020 +0000) on "macos_x64"

Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

 Often times, when I'm running Dart only tests (`tests` package, not `flutter_test`) in a Flutter application, I have to run a flutter clean or at least an rm -rf build in order for new changes in my code to be reflected in a new test.

It seems like code from the test is what fails to update, but code from the library being tested updates correctly

**Comment by ThinkDigitalSoftware** [comment]
This has been this way for years, I just worked around it, but now I can't get it to work reliably

**Comment by jensjoha** [comment]
@ThinkDigitalSoftware would it be possible for you to provide an example?

**Comment by ThinkDigitalSoftware** [comment]
I could, but it would be arbitrary. You want video or code?

**Comment by ThinkDigitalSoftware** [comment]
I don't think it's the incremental compiler. It happened again yesterday and this time it was before the first run for that file. It gave me a runtime error saying a method was missing parameters, as if it had taken a snapshot of the file while I was creating it  and ran that instance. The parameters were typed in by the time the tests ran the very first time. I believe I killed all the dart processes and ran it again and it worked.

**Comment by mraleph** [comment]
The video would be good, the code would be even better. 

Incremental compiler saves some state on the disk - so its state can carry over even if you kill all Dart processes. 

One other hypothesis I have is that there is some sort of race between application startup and flutter tools pushing new Kernel binaries to the device.

**Comment by ThinkDigitalSoftware** [comment]
Alright, I'll try to get around to that asap

**Comment by ThinkDigitalSoftware** [comment]
Sorry I've been lagging with providing examples. They seem to show up on a private project in which I'm not able to share the code.

**Comment by ThinkDigitalSoftware** [comment]
When running from the IDE, it often doesn't reflect new code. When running the same command from the terminal, I don't have the issue. And then it's gone from the IDE after running it from the terminal. The command I'm using is

```
flutter --no-color test --machine test/path_to_test_file.dart
```

**Comment by jensjoha** [comment]
Am I understanding you right, that this issue only happens through IntelliJ?
@mraleph who could know something about that?

**Comment by ThinkDigitalSoftware** [comment]
Yes, only on IntelliJ. I've been testing all day back and forth and got the same results every time. Old results on IntelliJ and always fresh results on the terminal and VS code

**Comment by mraleph** [comment]
@devoncarew Devon could you help us to loop relevant people in? Seems like IntelliJ has some sort of problem? (maybe there is a race between saving file and starting the test?)

**Comment by ThinkDigitalSoftware** [comment]
Even after the test would run and rerun, it would still have stale code. Also, when coding in vs code and switching to IntelliJ, IntelliJ would still be behind

**Comment by ThinkDigitalSoftware** [comment]
@mraleph it seems like you're right. There's no race though, it's just how IntelliJ works. It's because of the delay in saving that IntelliJ has, vs VS Code's autosave. Someone found the issue [here](https://github.com/flutter/flutter/issues/34382#issuecomment-628889061) and I was able to confirm.

**Comment by devoncarew** [comment]
Thanks @ThinkDigitalSoftware and @andrasferenczi for the investigation! I'm going to close this issue in favor of https://github.com/flutter/flutter/issues/34382 (since is sounds like they're duplicates), and will likely move the other issuer into the flutter/flutter-intellij repo.

**Comment by devoncarew** [comment]
(moved to https://github.com/flutter/flutter-intellij/issues/4548)

**Comment by ThinkDigitalSoftware** [comment]
Thank you as well
