### ISSUE TITLE
mainAxisAlignment for Row() and Column() are aligning non-visible widgets

### ISSUE THREAD

**Issue by daisoJS** [flutter/flutter#56423]
Some widgets within the Row() or Column() are hidden but still regarded as an object to align when the mainAxisAlignment is set to either of these values: 
- MainAxisAlignment.spaceAround 
- MainAxisAlignment.spaceBetween
- MainAxisAlignment.spaceEvenly

## Steps to Reproduce
Use the following code:
```dart
Container(            
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                InkWell(
                  splashColor: Colors.transparent,
                  onTap: (){},
                  child: Padding(
                    padding: EdgeInsets.all(4.0),
                    child: Icon(
                      Icons.delete,
                      size: 24.0,
                    ),
                  ),
                ),
                Visibility(
                  visible: false,
                  child: InkWell(
                    splashColor: Colors.transparent,
                    onTap: (){},
                    child: Padding(
                      padding: EdgeInsets.all(4.0),
                      child: Icon(
                        Icons.warning,
                        size: 24.0,
                        color: _errorColor,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
```

**Expected results:** 
![alignCenter](https://user-images.githubusercontent.com/64888422/81145543-0dae6780-8fa9-11ea-86cd-45f367b5d4ec.JPG)

**Actual results:** 
![spaceevenly](https://user-images.githubusercontent.com/64888422/81145577-1f900a80-8fa9-11ea-9478-03452d4ad971.JPG)

**Comment by TahaTesser** [comment]
Hi @daisoJS 

Check out this code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                InkWell(
                  splashColor: Colors.transparent,
                  onTap: () {},
                  child: Padding(
                    padding: EdgeInsets.all(4.0),
                    child: Icon(
                      Icons.delete,
                      size: 24.0,
                    ),
                  ),
                ),
                Visibility(
                  visible: false,
                  maintainInteractivity: false,
                  maintainSize: false,
                  maintainState: false,
                  child: InkWell(
                    splashColor: Colors.transparent,
                    onTap: () {},
                    child: Padding(
                      padding: EdgeInsets.all(4.0),
                      child: Icon(
                        Icons.warning,
                        size: 24.0,
                        color: Colors.red,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.17.0-3.4.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554             • android-x86    •
      Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios            •
      iOS 13.4.1
    • Chrome                    • chrome                    • web-javascript •
      Google Chrome 81.0.4044.138
    • Web Server                • web-server                • web-javascript •
      Flutter Tools

• No issues found!
``` 

</details>

**Comment by daisoJS** [comment]
Hi @TahaTesser, the suggested code still does not resolve the misbehavior. However, when I set the mainAxisAlignment attribute to MainAxisAlignment.center, the invisible icon (Icons.warning) does not get treated as an object for alignment. 

The comment text for the Visibility widget says it will be treated as a zero sized box by default 

> /// Whether to show or hide a child.
> ///
> /// By default, the [visible] property controls whether the [child] is included
> /// in the subtree or not; when it is not [visible], the [replacement] child
> /// (typically a zero-sized box) is included instead.
>

**Comment by azbuky** [comment]
Hi @daisoJS 

Visibility widget still participates in layout even if the replacement child is zero sized box. So when you space the Row evenly it counts as a child.
You should use an if statement in the collection literal instead of a Visibility widget.

For your sample code you would have something like this (warningIsVisible is a bool)
```
Container(
    child: Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: <Widget>[
        InkWell(
          splashColor: Colors.transparent,
          onTap: () {},
          child: Padding(
            padding: EdgeInsets.all(4.0),
            child: Icon(
              Icons.delete,
              size: 24.0,
            ),
          ),
        ),
        if (warningIsVisible)
          InkWell(
            splashColor: Colors.transparent,
            onTap: () {},
            child: Padding(
              padding: EdgeInsets.all(4.0),
              child: Icon(
                Icons.warning,
                size: 24.0,
                color: _errorColor,
              ),
            ),
          ),
      ],
    ),
  ),
```

**Comment by iapicca** [comment]
Hi @daisoJS 
it seems to me that @TahaTesser solution
does solve the misbehavior, 
[dartpad sample](https://dartpad.dev/968fa65e9d5f076c02fa4752198e1311)
could you please double check
Thank you

**Comment by azbuky** [comment]
@iapicca your dartpad sample is misleading as the Container size is the same size of the FlutterLogo widget so the row has no space left to space evenly. If you make the Visibility widget visible you get an overflow.

If you make the Container's width larger (like 180) the logo appears slightly to the right as @daisoJS noted. 

This happens because even though the Visibility widget is zero sized (it's child is not visible) it still remains as a child of the Row.

**Comment by daisoJS** [comment]
@iapicca I went to double check @TahaTesser solution in dartpad too and the problem is still there. In his solution, he is evenly spacing along the column main axis and I still see the Icon.delete staying at the top of the screen when Icon.warning is set to invisible. In my case, I am evenly spacing along the row main axis and there is the same behavior. By the way, thank you for formatting my code sample.

@azbuky your explanation makes sense and the code seem to work. I did some additional testing and confirmed that zero sized boxes such as empty Container() and SizedBox() also participates in the layout. 

It feels a little strange that while the zero sized boxes participates in .spaceAround/.spaceBetween/.spaceEvenly argument, they do not seem to participate in the .center argument. I would expect similar behavior (visible widget to stay in the same position when the other widget becomes invisible), but that is not the case. The zero size box is being ignored in MainAxisAlignment.center.

MainAxisAlignment.center (Both visible)
![visible](https://user-images.githubusercontent.com/64888422/81196350-820cf900-8ff1-11ea-861a-df43e6eeebc7.JPG)

MainAxisAlignment.center (One is not visible)
![invisible](https://user-images.githubusercontent.com/64888422/81196373-8802da00-8ff1-11ea-8516-c00b27401268.JPG)

**Comment by azbuky** [comment]
@daisoJS The zero sized box is not ignored in MainAxisAlignment.center. Check Flutter inspector, the sized box is there. Only that it has the size of zero so it takes no space in the layout but it is right next to the other child of the Row.

MaxAxisAligment.center groups all children in the center with no space between them. Space is added only before the first child and after the last one. In your case the Visibility widget does not add any space so the other icon is centered.

When you use MainAxisAlignment.spaceEvenly there is space before the first child and after the last one but also between children so even though the zero sized box does not take any space, there is space around it.

The [Understanding Constraints article](https://flutter.dev/docs/development/ui/layout/constraints) might explain it better then me.

**Comment by TahaTesser** [comment]
Updated my code comment above, i meant to use Row widget not column and  `MainAxisAlignment.spaceEvenly` does reproduce this issue 

Thank you for your contribution

**Comment by azbuky** [comment]
@TahaTesser 

I think this is expected behavior for a Visibility widget in a Row and not a bug. This issue should be closed. Better documentation for when to use (or not to use) the Visibility widget should be added though.

The [Visibility class](https://api.flutter.dev/flutter/widgets/Visibility-class.html) documentation states that the widget hides its child and not itself.
```
Whether to show or hide a child.
By default, the visible property controls whether the child is included in the 
subtree or not
...
Using this widget is not necessary to hide children. 
The simplest way to hide a child is just to not include it
...
```
