### ISSUE TITLE
Out or Ref parameters

### ISSUE THREAD

**Issue by NickNevzorov** [flutter/flutter#56427]
It would be great if we had the opportunity of out parameters.
For example:

```
void main() {

  int i = 1;
  void inc(int i) {  i++; };
  inc(i);
  print(i);

}
```

result: 1;

Proposal:

```
void main() {

  int i = 1;
  void inc(**ref** int i) {  i++; };
  inc(i);
  print(i);

}
```

result: 2

In many languages it supported. C++, Pascal, php. 
I known workaround, but this future will be a great extend of our platform!

**Comment by VladyslavBondarenko** [comment]
Hi @NickNevzorov 
Consider better to file the issue here https://github.com/dart-lang/language/issues,
Closing since not a Flutter specific
