### ISSUE TITLE
This is for google_maps_flutter package: Is there a feature to display a multipolygon in the Google Map?

### ISSUE THREAD

**Issue by djfunkd** [flutter/flutter#56437]

**Comment by TahaTesser** [comment]
Hi @djfunkd 
You mean something like [Polygon Arrays
](https://developers.google.com/maps/documentation/javascript/examples/polygon-arrays)?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
