### ISSUE TITLE
ReorderableListView() doesn't work inside SingleChildScrollView() or Column()!

### ISSUE THREAD

**Issue by SalehIA** [flutter/flutter#56448]
## Use case
Allow using ReorderableListView() inside a SingleChildScrollView() and Column() just like ListView().

## Proposal
Add shinkWrap: property to the ReorderableListView() widget. It could be an easy fix and it is much needed!

**Comment by VladyslavBondarenko** [comment]
Hi @SalehIA 
please follow up on https://github.com/flutter/flutter/issues/25789 and https://github.com/flutter/flutter/issues/45458
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
