### ISSUE TITLE
regression in animated_placeholder_perf average_frame_build_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56446]
Looks like https://github.com/flutter/flutter/pull/56378 is the culprit.
![Screen Shot 2020-05-06 at 7 52 00 AM](https://user-images.githubusercontent.com/1435716/81191968-7cba9a80-8f6e-11ea-93a2-31945cabb573.png)

**Comment by mehmetf** [comment]
@liyuqian @a-siva  FYI.

**Comment by jason-simmons** [comment]
This benchmark looks like it has had bimodal results for a few weeks (some runs with around 6ms average time per frame build, other runs closer to 7ms).

I just tried running it at master on a Moto G4 and got varying results for average_frame_build_time_millis: `[6.03, 5.91, 5.55, 6.21, 5.74]`

Has anyone looked into what is happening during the runs with longer frame build times?

**Comment by jason-simmons** [comment]
One thing I noticed is that runs of the benchmark with lower frame counts have higher average frame build times.

This benchmark involves rendering a grid of 100 animated GIF images.  The batching of animation updates into Flutter frames is somewhat arbitrary based on timing in the framework scheduler.

| average_build_time | frame_count | total_build_time |
|--------------------|-------------|------------------|
| 6.03 | 255 | 1537 |
| 5.91 | 270 | 1595 |
| 5.55 | 270 | 1498 |
| 6.21 | 252 | 1564 |
| 5.74 | 268 | 1538 |

So the overall time spent in the frame build phase does not vary much.  The difference in average_frame_build_time_millis may just represent the same amount of work being distributed over more or fewer frames.

**Comment by liyuqian** [comment]
Adding "framework" label as frame build time is mostly related with the Dart code in the framework (CC @goderbauer). Also CC @dnfield , the author of animated placeholder perf test.

**Comment by kf6gpe** [comment]
Looking again, it looks like that band of red has moved on, and was likely noise:

![Screen Shot 2020-05-07 at 1 02 16 PM](https://user-images.githubusercontent.com/1435716/81339447-11062980-9063-11ea-897b-7f96e37def80.png)


Closing.
