### ISSUE TITLE
Biometric Auth in flutter

### ISSUE THREAD

**Issue by renatoluismb** [flutter/flutter#56443]
In IOS is ok. FaceId is working. But in Android, the fingerprint is don't work. Error: I/flutter (19430): [BiometricType.fingerprint] I/flutter (19430): PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null). My code doesn't have MainActivity.java. Is embedding below

My AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.flutter.examples.test">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>

    <application android:label="AY">
        <activity android:name="io.flutter.embedding.android.FlutterActivity"
                  android:theme="@android:style/Theme.Black.NoTitleBar"
                  android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                  android:hardwareAccelerated="true"
                  android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
   <!-- Don't delete the meta-data below.
        This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by BLitzMe** [comment]
Have you tried explicitly calling the permissions within your native android code? this was a problem with a bluetooth app i was trying. Might be worth a try

**Comment by renatoluismb** [comment]
I didn't try ... could you help me how to do this?

**Comment by VladyslavBondarenko** [comment]
Hi @renatoluismb 
does it help https://github.com/flutter/flutter/issues/41119?

**Comment by renatoluismb** [comment]
my project does not have mainactivity .... how can I adapt it?

**Comment by VladyslavBondarenko** [comment]
@renatoluismb 
you can create a new project with `flutter create` and move your codebase there

**Comment by iLolz** [comment]
> Hi @renatoluismb
> does it help #41119?
> 
> **Edit**:
> Code sample there may be outdated.
> 
> Fingerprint auth works for me when I have such MainActivity.kt
> 
> ```
> package com.example.bug
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```

My project just show me a white screen and closes when I added that, have another suggestion?

**Comment by VladyslavBondarenko** [comment]
@iLolz what flutter version are you using and what can you see in logs when running with `--verbose`?

**Comment by renatoluismb** [comment]
flutter --version
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (6 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by VladyslavBondarenko** [comment]
@renatoluismb have you managed to get it work with https://github.com/flutter/flutter/issues/56443#issuecomment-625117187?

**Comment by renatoluismb** [comment]
doesn't work for me...

**Comment by VladyslavBondarenko** [comment]
@renatoluismb what the error do you have? could you describe what do you mean by "doesn't work"?

**Comment by jjvillavicencio** [comment]
Hello, start an application with Flutter 1.17 and when you replace FlutterActivity in the MainActivity with FlutterFragmentActivity, the application does not load the other plugins when compiling.

How should FlutterFragmentActivity be implemented in Flutter 1.17?

> Nueva estructura de Flutter MainActivity.kt
```
package com.clubdecompras.storesadm

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

**Comment by VladyslavBondarenko** [comment]
@jjvillavicencio ask the question at https://github.com/flutter/flutter/issues/41119,
@renatoluismb follow up on https://github.com/flutter/flutter/issues/41119,
I'm going to close the issue as duplicate, 
if you disagree please write in the comments and I will reopen it

**Comment by QtMonkey** [comment]
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }

Worked perfectly for my project (Android/iOS). Thank you very much.
