### ISSUE TITLE
after 1.17.0 stable release, stable branch is red on cirrus

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#56450]
Here is a link to the cirrus build: https://cirrus-ci.com/build/6257015297146880

### ~~firebase_test_lab_tests-linux~~
Known flake, passed on re-run.

### ~~customer_testing-windows~~
This failure is related to https://github.com/flutter/tests/pull/36 and https://github.com/flutter/tests/pull/37. An engine change caused golden tests to fail. This was fixed upstream by temporarily disabling the test in `flutter/test`, landing the engine roll, updating the customer test, and then re-enabling the test in `flutter/test`.

### ~~deploy_gallery-macos~~
Known failure that was fixed upstream by 28c0098, will be picked up in the next hotfix.

### ~~docker_build~~
Looks like a network disconnect, passed on re-run.

**Comment by pcsosinski** [comment]
deploy_gallery-macos is fixed on the flutter-1.17-candidate.3 already by https://github.com/flutter/flutter/commit/28c00980a017ff8942b88a1648a5b467fcddfa8c

**Comment by pcsosinski** [comment]
(but was not included in the stable push because it didn't go in our last beta push)

**Comment by christopherfujino** [comment]
> (but was not included in the stable push because it didn't go in our last beta push)

thanks, updated OP accordingly.

**Comment by christopherfujino** [comment]
Closing this as all issues were either flakes or expected breakages that were fixed upstream.
