### ISSUE TITLE
Is it Possible?? Fingerprint signup-login using mysqli

### ISSUE THREAD

**Issue by shsakir7** [flutter/flutter#56453]
##Is it Possible??
Instead of, Using As Usual Login(Username,pass) - Using Fingerprprint Login in #Flutter? and the Fingerprint Will come, when User got registered they will Give aa fingerprint.. and which can store in Mysql db,Not from Phone's Locks local fingerprint..
while login, matching the fingerprint from mysql db,user login will works.. 
Anyone Information pls....😊

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
