### ISSUE TITLE
Flutter 1.17 can't be integrated with Unity (1.12 version is fine)

### ISSUE THREAD

**Issue by skypu3** [flutter/flutter#56452]
My iOS flutter application is integrated with Unity, however I got the error message:
**ClassID 100000 (int) conflicts with that of another class (int). Please resolve the conflict.** 
(Filename:  Line: 263)
Then my app is crash on Unity.
My app is no issue on older stable version 1.12.
I also found beta and master channel version also can't work on unity integration.

Is it something conflict issue on Flutter with Unity ?

**Comment by skypu3** [comment]
I used the unity flutter plugin to integrate with Flutter app: 
https://github.com/snowballdigital/flutter-unity-view-widget

I found root cause that startUnity didn't be called, so it will init unity twice, then crash on RegisterAllClasses.
So I fixed the crash by
I fixed the issue by directly call start unity method on UnityAppController.mm. 
``` 
 [self startUnity:application];
 // [self performSelector: @selector(startUnity:) withObject: application afterDelay: 0];
```
Then add below before InitUnity inside dispatch_async on UnityUtils.mm
```
if (_isUnityReady) {
  completed();
  return;
}
``` 
It can resolve the crash issue.
But flutter ui can't show up on unity view with this code:
```
[_uView setUnityView: (UIView*)[GetAppController() unityView]];
```
So I do the basic UIView to do the test, the white native view will occupy whole screen without flutter ui on top. (I used Stack view add platform view and flutter widgets)
```
UIView *v1 = [UIView new];
CGFloat width = [UIScreen mainScreen].bounds.size.width;
CGFloat height = [UIScreen mainScreen].bounds.size.height;
v1.frame= CGRectMake(0, 0, width, height);
v1.backgroundColor = UIColor.whiteColor;
[_uView insertSubview:v1 atIndex:0];
```
So how do we show up flutter widgets on iOS flutter platformview?
It is normal on Flutter 1.12.

**Comment by VladyslavBondarenko** [comment]
@skypu3 
I'll link your issue from the plugin's repository here https://github.com/snowballdigital/flutter-unity-view-widget/issues/138

**Comment by BugSir** [comment]
https://github.com/flutter/flutter/issues/56660 it maby like this issues

**Comment by BugSir** [comment]
@skypu3  maby  the reason why flutter ui no work in platformview is here
https://github.com/flutter/flutter/issues/56660#issuecomment-626033300

**Comment by skypu3** [comment]
Yes, it is related to #56660, tested and it works. 
Thanks.

**Comment by Darkmax** [comment]
This resolve my crash issue, but also now I can't interact with unity view, even if is with ui inside unity.
Pleasy any resolution for this issue
