### ISSUE TITLE
Android OS bar doesn't contrast with logo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5645]
When switching apps in Android, the blue of the OS's app bar makes it hard to see the blue of the logo.

![unnamed_png](https://cloud.githubusercontent.com/assets/5479/18063712/fcbce598-6de0-11e6-9710-2b5f892ab758.png)

Suggestion from the designers is to use Grey 200 (#EEEEEE) for the bar.

**Comment by sethladd** [comment]
@jason-simmons @HansMuller is this easy to configure in some manifest?

**Comment by eseidelGoogle** [comment]
This used to be set by code called TaskDescription.  I think the widget is now called Title.  MaterialApp probably creates a title for you from the theme.  I searched briefly but didn't immediately find the code in question.  @tvolkert did the recent refactoring from TaskDescription to Title iirc?

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/system_chrome.dart#L62

**Comment by HansMuller** [comment]
Our Title class has a color parameter that DTRT, I will make it gray.  Or grey.
