### ISSUE TITLE
Unclear how to change colors of time picker(showTimePicker)

### ISSUE THREAD

**Issue by Gintasz** [flutter/flutter#56465]
At the moment it is very unclear how to change the colors of `showTimePicker`, e.g. the red handle color. Don't find answers even on google. Suggesting to document it more clearly or add appropriate arguments to showTimePicker for management of its colors.
![image](https://user-images.githubusercontent.com/6189625/81214451-8a106d00-8fe0-11ea-9583-abcb598ec044.png)

```
gintas-mac:domukpizzaapp gintas$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-10.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
gintas-mac:domukpizzaapp gintas$ 
```

**Comment by HansMuller** [comment]
CC @rami-a @darrenaustin

**Comment by rami-a** [comment]
Hi @Gintasz I'm currently working on a revamp of TimePicker to support better theming but it's still a WIP (hope to have it ready in the coming weeks). Currently, the [picker gets the red color](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/time_picker.dart#L1481) from your `ThemeData.accentColor`, so customizing that would change this. Hope this helps

**Comment by rami-a** [comment]
Hello @Gintasz, I just submitted #59191 that adds a time picker theme that allows you to customize the various colors, closing this now :)

**Comment by DriftingShadows** [comment]
@rami-a How does one change the button ('Cancel', 'OK') colours?

**Comment by rami-a** [comment]
Hello @DriftingShadows, the time picker uses the new TextButtons as of https://github.com/flutter/flutter/pull/61492 and the easiest way to change the color of those buttons is to specify a `textButtonTheme` on your `ThemeData`. Hope that helps.

**Comment by DriftingShadows** [comment]
> Hello @DriftingShadows, the time picker uses the new TextButtons as of #61492 and the easiest way to change the color of those buttons is to specify a `textButtonTheme` on your `ThemeData`. Hope that helps.

Thanks for that. I swear I'm on the latest flutter version (v1.20). TextButton isnt a widget for me (and as such textButtonTheme isnt a thing either). Am I doing something wrong?

**Comment by rami-a** [comment]
Ah I believe the `TextButton` change has not landed in stable yet, so then the TimePicker is using `FlatButton`s, which you can adjust the color of by using `ButtonTheme`. If you only want to change the TimePicker's button colors, you can use the `builder` param of [`showTimePicker`](https://api.flutter.dev/flutter/material/showTimePicker.html) and wrap the widget with a custom Theme.
