### ISSUE TITLE
Downloading Dart SDK from Flutter engine is failed

### ISSUE THREAD

**Issue by mdsakibulislamofficial** [flutter/flutter#56464]
**I cannot download flutter sdk form Bangladesh if i use vpn that time it work properly** 

![Screenshot from 2020-05-07 00-10-34](https://user-images.githubusercontent.com/45919558/81213091-b388c300-8ff7-11ea-912b-04286d4e9caf.png)

**Comment by TahaTesser** [comment]
Hi @mdsakibulislamofficial 
Looks like Flutter components may be being blocked in Bangladesh.
Please check this [comment](https://github.com/flutter/flutter/issues/48176#issuecomment-570890437)

You may need to need use VPN
if you disagree please write in the comments and I will reopen it 
Thank you
