### ISSUE TITLE
Images getting decoded in the engine causes native heap increase

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#56483]
There’s a brief time when the app pays dual allocation cost. The native heap is cleaned up typically in the next frame.

likely not a big deal because it would rare for apps not to schedule frames. However,  some degenerate cases may exist where an app is decoding an image while in the background.

/cc @cbracken @mehmetf

**Comment by chinmaygarde** [comment]
Some background on how this works: Textures for the images on the GPU are created using compressed buffers (PNG, JPEG, etc.) provided by the application. These compressed buffers need to be decompressed by the image codec before they may be transferred to the device (GPU). The image codec typically decompresses to a buffer on the host (the native heap) before the transfer to the device may be initiated. Once the transfer is done, the intermediate buffers are collected on the IO thread. There are opportunities to elide this intermediate buffer in newer rendering backends (and with codec support). The native heap increase around image decompression is around copying the compressed data out of the Dart VM managed heap, the intermediate decompressed image buffer on the host (which the engine may elide) and the decompressed buffer on the device. The heap increase will subside when the Dart VM collects the source compressed buffer, the engine collects its copy of that same compressed buffer, and, the engine collects the intermediate (possibly elided) uncompressed buffer. The device memory usage will subside when the application releases the texture.

> The native heap is cleaned up typically in the next frame.

This is inaccurate. The intermediate buffer is cleaned up on the IO thread immediate after the host to device transfer. **This is not tied to frame rendering in any way** and will happen regardless of whether there are frames being rendered.

> However, some degenerate cases may exist where an app is decoding an image while in the background.

As explained earlier, collection of the native buffers is not tied to frame rendering in any way. Images decoded in the background will get collected on the IO thread.

Closing as WAI.
