### ISSUE TITLE
Expose graphics memory usage information from engine

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#56486]
Internal: b/157468351

Scrolling the main page causes the graphics memory to jump to around 170M and the native heap to 50M. If the user settles the UI to a point where the list is full screen and the underlying layer is not visible, graphics memory is usually reduced to 100M whereas native heap remains at 50M.

/cc @mehmetf 

For now, we'll focus on the following sub-issues which would be 2 big chunks of graphics memory according to our experience and user studies.
- [ ] Improve image memory reporting from engine #59016
- [ ] Expose memory usage of picture/layer raster cache #56719

**Comment by mehmetf** [comment]
To be clear, scrolling itself isn't the issue here. There's a very specific case that customer: money is running into which is causing Graphics memory to fluctuate wildly. I don't have a simpler repro for this so likely the AI here is to emit better metrics from Flutter Engine on graphics usage so we can pinpoint what's going on.

**Comment by mehmetf** [comment]
Without this, debugging memory problems for large customers is incredibly difficult. Due to the memory pressure customer is facing, marking this as critical.

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/issues/31498 might be a related issue. CC @dnfield for ideas on exposing image related memory and CC @jason-simmons @GaryQian on exposing font related memory.

**Comment by dnfield** [comment]
I think we should do more to make this better, but has the customer tried using native debugging tools on the platform being developed?  e.g. Android Studio or Xcode?

**Comment by liyuqian** [comment]
I've also just created "Expose memory usage of picture/layer raster cache #56719"

**Comment by dnfield** [comment]
My understanding is that the customer is particularly concerned about iOS usage.

If the customer uses Xcode with LLDB attached, they can dump the memory hierarchy and view all the native/graphics memory in use. It may be possible to provide cross platform tooling for Flutter around this, but that will be a bigger, multi-team effort with devexp. 

@mehmetf - can we confirm that using Xcode is sufficient here for the customer and remove the critical label?

There are some pointers relevant to this in https://github.com/flutter/flutter/issues/55934

**Comment by mehmetf** [comment]
> The customer is particularly concerned about iOS usage.

No, they are primarily concerned about Android usage. The problem definition is platform agnostic but this is critical because of Android.

> It may be possible to provide cross platform tooling for Flutter around this, but that will be a bigger, multi-team effort with devexp.

Agreed. That's what this is tracking. Critical might not be the right tag for a bug of this scope. Feel free to segment this into smaller issues.

@devoncarew FYI

**Comment by mehmetf** [comment]
Devon was mentioning there might be smaller scope wins here such as exposing coarse grained memory allocation. Devon, given @dnfield 's interpretation above, do you think this can be sectioned into smaller goals?

**Comment by pcsosinski** [comment]
any thoughts @devoncarew?

**Comment by liyuqian** [comment]
I believe https://github.com/flutter/engine/pull/18706/ is also helping this. @dnfield can you please confirm?

**Comment by dnfield** [comment]
The referenced pull request will likely make things more confusing.

Right now, multiple objects can be referring to the same memory. In some cases, it's possible that some action on those objects could cause duplication of that memory, but not necessarily. The core problem that flutter/engine#18706 is trying to solve is that an `SkImage` may be refereced by several other objects, and we're not currently reporting it as part of the allocation that the VM sees for GC related decisions. This can mean that the VM thinks it does not need to run a GC when it really should, because it thinks a lot of the garbage objects are tiny when in fact they're holding references to larger chunks of memory.

I'm becoming more and more convinced that the right way to expose graphics memory usage is to just use native debugging tools, possible via integrating witht hem more fully in devtools.

**Comment by devoncarew** [comment]
> Devon was mentioning there might be smaller scope wins here such as exposing coarse grained memory allocation. Devon, given @dnfield 's interpretation above, do you think this can be sectioned into smaller goals?

Sorry, I missed this in my emails. Sounds like Dan's making progress on ensuing that sizes for some native objects are more accurate.

I think what might help here is a general runtime memory usage API and then task specific APIs.

The general memory usage API might return something like a number for each of:
- overall process usage
- dart heap usage
- compiled code size
- memory used by images
- skia specific sections; compiled shaders? font cache?

For each area, if it looked like it was consuming an unusual amount of memory, we could either built tooling to let the user examine that area, or, point them to the appropriate native tooling.

As an example of a task specific API, I have a WIP change to the flutter framework to expose detailed info about the image cache. It would let us build tooling for something like a live view of the image cache: https://drive.google.com/file/d/1RVYcovewSFlAsfceW3mCDepgc6xlyJZ1/view?usp=sharing

> I'm becoming more and more convinced that the right way to expose graphics memory usage is to just use native debugging tools, possible via integrating witht hem more fully in devtools.

For these, can we get raw overall usage numbers for the different types of memory? Even broad numbers may help the user understand the problem better, and let us know which tool to point them to.

**Comment by zanderso** [comment]
@liyuqian For triage, are you able to make progress on this based on the milestone you have set?

**Comment by liyuqian** [comment]
@zanderso yes, Dan and I are working on it. I've split it into 2 sub-issues and updated this issue's description accordingly.

**Comment by Hixie** [comment]
Can someone help me understand the prioritisation here? This bug is marked P2 but the two bugs it was split into are P5s. What work must be done to resolve the P2 aspect of this bug?

**Comment by liyuqian** [comment]
Raised those two bugs from P5 to P2 after discussing with Chinmay to clarify that those two bugs contribute to this high-priority issue.

**Comment by Hixie** [comment]
This is a metabug at this point; I'm going to move the priority down so that it doesn't come up each week in triage. Still tracking the other two actual bugs.

**Comment by zanderso** [comment]
@Hixie @mehmetf is this P2 or P3? Assuming P3 was correct based on @Hixie's comment.

**Comment by mehmetf** [comment]
The bug syncer changed it. I will update the internal one to p3 as well.

**Comment by kf6gpe** [comment]
By way of tracking, we're discussing reporting the following categories of data:

- [ ] Dart; 
- [ ] native (memory allocated by engine, Skia, and other C/C++ code) 
- [ ] graphics (memory allocated by GPU drivers, mainly driven by Skia); 
- [ ] Platform (e.g., memory allocated by Java code in Android or ObjC/Swift code in iOS).

I _think_ we have some of Platform done at this point, or perhaps all of it, via the observatory, along with Dart. Native work continues, as does graphics (thinking the render cache so far). Am I missing anything, @dnfield and @liyuqian?

**Comment by liyuqian** [comment]
I'm closing this as both of these are closed
- [x] Improve image memory reporting from engine #59016
- [x] Expose memory usage of picture/layer raster cache #56719

More related work can also be tracked through https://github.com/flutter/flutter/issues/56482

**Comment by devoncarew** [comment]
@liyuqian, you closed this issue, but it was tracking work for native, graphics, and platform. I don't think that's all complete? I.e., we don't have APIs to know what the Java heap is, other C++ memory, ... .

**Comment by liyuqian** [comment]
I closed it based on https://github.com/flutter/flutter/issues/56486#issue-613636933. I just created https://github.com/flutter/flutter/issues/70706 to track https://github.com/flutter/flutter/issues/56486#issuecomment-696390318.

**Comment by devoncarew** [comment]
Thanks!
