### ISSUE TITLE
Document expected behavior for APIs that expect a return type of Type?

### ISSUE THREAD

**Issue by znjameswu** [flutter/flutter#56500]
In Flutter 1.17.0, a [breaking change](https://github.com/flutter/flutter/pull/48541) was made to `ParentDataWdiget`. A new method `debugTypicalAncestorWidgetClass` requires users to override and return `Type` of its ancestor widget.

However, the ancestor could be a generic type, and Dart [does not support](https://github.com/dart-lang/sdk/issues/11923) generic type literals.

Since it is a relatively uncommon pattern in Flutter (AFAIK), and the [solution](https://stackoverflow.com/questions/52891537/how-to-get-generic-type) is tricky to get around this Dart limitation, it could be confusing whether the user should return with or without generic type arguments. So mentioning this in documentation for relevant APIs can be helpful.

**Comment by goderbauer** [comment]
Can you make a suggestion as to what you would like us to add to the documentation? Looking at it, it seems pretty clear. You're supposed to provide a widget type that's **typically** used. The one that's typically used would have a specific type, not a generic one.

**Comment by znjameswu** [comment]
Due to this Dart limitation, we need to manually create a `getType` function to retrieve the type (in this [answer](https://stackoverflow.com/questions/52891537/how-to-get-generic-type)). This workaround requires quite some serious Dart knowledge, primarily reified generics, for user (especially users from JS or Java background, whose generics use type erasure and have very different behavior). 

For future APIs designed in this pattern, it may be helpful to add a line of comment about the best solution for generic types, until this Dart limitation has been solved.

**Comment by Hixie** [comment]
`debugTypicalAncestorWidgetClass` is the only property or method I could find that returns a type where this might be an issue. I've added the following to the documentation:

```dart
  ///                                                                                                                                                                        
  /// ## Implementations                                                                                                                                                     
  ///                                                                                                                                                                        
  /// The returned type should be a subclass of `RenderObjectWidget`.                                                                                                        
  ///                                                                                                                                                                        
  /// ```dart                                                                                                                                                                
  ///   @override                                                                                                                                                            
  ///   Type get debugTypicalAncestorWidgetClass => FrogJar;                                                                                                                 
  /// ```                                                                                                                                                                    
  ///                                                                                                                                                                        
  /// If the "typical" parent is generic (`Foo<T>`), consider specifying either                                                                                              
  /// a typical type argument (e.g. `Foo<int>` if `int` is typically how the                                                                                                 
  /// type is specialized), or specifying the upper bound (e.g. `Foo<Object?>`).                                                                                             
```

(It's now possible to create a generic literal, FWIW.)
