### ISSUE TITLE
Improve Wiki Page: Obfuscating Dart Code

### ISSUE THREAD

**Issue by opalr** [flutter/flutter#56504]
This wiki page (https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code) explains how to obfuscate your code while building with versions of Flutter before 1.16.2 (when the --obfuscate option was added).

I'm on Flutter 1.12.13+hotfix.8 and I'm building for android, so I added
```
extra-gen-snapshot-options=--obfuscate
```
to <project>/android/gradle.properties, as the wiki describes.

Now I'm confused about if I need to use the --obfuscate option when running "flutter build appbundle" or if flutter build now does it by default. When I add the --obfuscate option, I get an eror:

```
Could not find an option named "obfuscate".
```

**Comment by jonahwilliams** [comment]
> Now I'm confused about if I need to use the --obfuscate option when running "flutter build appbundle" or if flutter build now does it by default. When I add the --obfuscate option, I get an eror:


The wiki clearly states that isn't required or supported.
