### ISSUE TITLE
Can't upgrade flutter to 1.17

### ISSUE THREAD

**Issue by emem365** [flutter/flutter#56517]
I have Flutter 1.12.13+hotfix.8 installed on my Windows 10 OS, and since I heard about the new 1.17 update I was trying to upgrade to it.  Naturally I tried running:
`flutter upgrade`
It gives me the following response:
```
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin
https://github.com/flutter/flutter' in D:\Android\flutter
```
I tried to follow through, manually adding the remote, but
`git remote add origin https://github.com/flutter/flutter`
says, 
`fatal: remote origin already exists.`

I am pretty sure I am currently on the stable channel as I never really switched channels.
I'll also link flutter doctor response here:
```

[√] Flutter (Channel unknown, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at D:\Android\flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android
    • Java binary at: D:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Help me figure out what I am doing wrong :/

**Comment by cv0cv0** [comment]
flutter channel stable
flutter upgrade --force

**Comment by emem365** [comment]
> flutter channel stable
> flutter upgrade --force

Tried this Didn't work.
But now i know why it didnt work. Turns out, the remote origin was set to some other link. Must've happened while I was working on some other project of mine. 
I removed that remote and added origin again set to https://github.com/flutter/flutter, This didnt ofcourse solve the problem yet, I'll checkout stable branch, clean, stash, and pull again. If there's anything else that needs to be done please drop a comment.
