### ISSUE TITLE
Flutter isAfter and isBefore not working properly.

### ISSUE THREAD

**Issue by vikramaroskar** [flutter/flutter#56529]
Output: 
```
I/flutter (12221): start is 2020-05-07 00:00:00.000
I/flutter (12221): end is 2020-05-07 23:59:00.000
I/flutter (12221): listtasks is [Instance of 'TaskItem', Instance of 'TaskItem']
I/flutter (12221): f.time 2020-05-06 20:18:04.000Z
I/flutter (12221): f.time 2020-05-06 20:18:04.000Z
```
TaskItem is a model having time as afield. of type DateTime.
I'm trying to filter out a List<TaskItem> based on time field using isAfter and isBefore.
However, for start and end on 7th may, I'm getting list filter of yesterday 6th May.

Here' the code chunk.

```
print('start is ${start.toString()}');
    print('end is ${end.toString()}');

    final List<TaskItem> listtasks = tasks
        .where((f) => (f.time.isAfter(start) && f.time.isBefore(end)))
        .toList();

    print('listtasks is $listtasks');
    listtasks.forEach((f) {
      print('f.time ${f.time.toString()}');
    });
```

**Comment by Moncader** [comment]
The final f.time looks like it's in UTC (the Z is on the end) while start and end isn't saying it's Z. So probably local time.
Depending on where you live in the world this result is correct.

**Comment by vikramaroskar** [comment]
Thanks @Moncader 
Silly mistake on my part. Closing this.

**Comment by mohamedbayoumy42** [comment]
how U solve it
