### ISSUE TITLE
[desktop]:linux Segmentation Fault after "GLFW error 65545: EGL: Failed to find suitable EGLConfig" on Buildroot Linux Distribution

### ISSUE THREAD

**Issue by nmcain** [flutter/flutter#56520]
I am trying to run the default demo app on a buildroot distribution, I compiled the file and copied the compiled files into the target directory and built the image. The app fails to run with `GLFW error 65545: EGL: Failed to find suitable EGLConfig` and then it segfaults and terminates. I have included every possible Xorg and Mesa driver, and all of the kernel graphics drivers, so it does not seem to be a graphics driver issue. 
![LDD output of compiled demo](https://user-images.githubusercontent.com/18690588/81263739-175dbc80-8ff5-11ea-96d2-87aa70263e34.jpg)
![glxinfo, opengl info, and flutter error](https://user-images.githubusercontent.com/18690588/81263746-1c227080-8ff5-11ea-83d6-f341cc2dc4f8.jpg)

**Comment by nmcain** [comment]
Is the non GLFW shell for the desktop embedder available to the public?

**Comment by TahaTesser** [comment]
Hi @nmcain 
I would like to reproduce this, can you please reproducible steps if the problem persists for you?
Thanks

**Comment by nmcain** [comment]
Oh, I forgot to close this issue😅. It seems to have been an isolated incident with the old GLFW embedder, because the new GTK one runs perfectly now.

**Comment by TahaTesser** [comment]
Hi @nmcain 
No worries, Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
