### ISSUE TITLE
CI is crashing with the new Flutter version 

### ISSUE THREAD

**Issue by DavidFD005** [flutter/flutter#56526]
We're having issues with our Pipeline in Azure DevOps (I don't know if it happens with other CI platforms)
It's crashing when it tries to download the **.zip** of latest version (**1.17.0**). And it seems to be the URL pattern for each release that has changed with the new release:

**v1.17.0**: ..../flutter_macos_**~~v~~**1.17.0-stable.zip

**v1.12.13+hotfix.9**: ..../flutter_macos_v1.12.13+hotfix.9-stable.zip

**v1.12.13+hotfix.8:** ..../flutter_macos_v1.12.13+hotfix.8-stable.zip

....

Has someone the same issue?

Thanks

**Comment by glofru** [comment]
Having same issue after upgrading 1.17.

Here's the details, need hotfix:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/33641238/81269244-56b5f880-9049-11ea-8ef8-f90ee6af6e47.png">

**Comment by brettbeostar** [comment]
looks like it's an issue with the DevOps extension and they are working on fix:
https://github.com/aloisdeniel/vsts-flutter-tasks/issues/46#issuecomment-624761829

**Comment by TahaTesser** [comment]
Hi @DavidFD005 
Looks like this isn't issue with Flutter but  DevOps extension
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by DavidFD005** [comment]
Thanks!
