### ISSUE TITLE
Licenses page scrollable adds or removes space after screen rotation

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#5652]
1) Run Gallery.  Go to the About dialog and click View Licenses.
2) Put the device in portrait mode and scroll down a few pages
3) Rotate the screen and scroll back up to the top.  There will be excess space at the top of the scrollable region before the license text starts.

The reverse will happen if the device is in landscape mode.  If you scroll the license page and then rotate back to portrait mode then the top of the scrollable region will be truncated, thus cutting off some of the license text.

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
Odd. Maybe the LazyBlock dead reckoning isn't updating the scroll behaviour?
cc @abarth

**Comment by eseidelGoogle** [comment]
I wonder if this could at all relate to https://github.com/flutter/flutter/issues/5135.  This may be resolved by Hixie's grand scrolling re-write he's landing now.

**Comment by goderbauer** [comment]
This doesn't reproduce anymore.
