### ISSUE TITLE
google maps flutter - all marker are not visible

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#56538]
Hi,
I am trying to display around 200 markers on Google Map. But only 40-50 markers are being displayed. Is there any limit on marker count?

**Comment by TahaTesser** [comment]
Hi @viratshukla 
Did you try another device or emulator?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by viratshukla** [comment]
Fixed it myself. Marker ID was not unique. Hence only unique markers were displayed.
