### ISSUE TITLE
iOS platformview didn't contain FlutterOverlayView on Flutter version 1.17, but 1.12 has it

### ISSUE THREAD

**Issue by skypu3** [flutter/flutter#56533]
Hi,

After I upgrade Flutter into 1.17, the flutter widgets can't show on top of platform view.
The platform view (unityWidget) is added into Stack with flutter widgets.
```dart
child: Stack(
  children: <Widget>[
     UnityWidget(),
     Positioned(
       child: Text('Test on PlatformView')
     ),
  ],)
```
Then I used the xcode layers debug and get:
![截圖 2020-05-07 下午4 10 03](https://user-images.githubusercontent.com/70039/81272192-c1822680-907f-11ea-8ffe-f8a7467123da.png)
It didn't contain FlutterOverlayView, so I can't see any flutter widgets on it.

However, this is Flutter 1.12 debug view:
![截圖 2020-05-07 下午3 41 42](https://user-images.githubusercontent.com/70039/81272453-17ef6500-9080-11ea-8b46-e7bfdd7b580c.png)
It can show flutter widgets on top of platform view.

So how can solve the issue, is it something I need to do on Flutter 1.17 ?
The issue is related to #56452, but without crash.

**Flutter doctor:**
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale
    zh-Hant-TW)
    • Flutter version 1.17.0 at /Users/felixchang/development/flutter1.17
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/felixchang/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Chang 的 iPhone • 00008030-000C2D561120802E • ios • iOS 13.3.1

• No issues found!

**Comment by artemsivcev** [comment]
Thats work pretty good at any stable channel

**Comment by scottlaw** [comment]
The same issue in 1.17.1.

**Comment by haoguo** [comment]
I embed unity on my flutter app too.
Workaround is do not create the UIView but to return the reference in view factory.
see here #56660

**Comment by TahaTesser** [comment]
Hi @skypu3 
Please check https://github.com/flutter/flutter/issues/59751,  whatever view is created behind platformview 
Please read  https://github.com/flutter/flutter/issues/59751#issuecomment-705852929
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
