### ISSUE TITLE
toString() returns different values for an object in release and debug mode.

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#56537]
Hi flutter team, 
As I was working on my flutter project. I came across this weird problem. 
While using,
```
BoxDecoration deco=BoxDecoration(color:Colors.white);
```
in debug mode.
```
print(deco.toString());  | [returns]>  BoxDecoration(color:Colors.white)
```
in release mode.
```
print(deco.toString());  | [returns]>  BoxDecoration
```
In release mode it just returns Object name.
My guess is it is due to toString() Diagnostic level. 

I tried `deco.toString(minLevel: DiagnosticLevel.fine);` but results are still the same.
How can we fix this?

**Comment by TahaTesser** [comment]
Issue does reproduce 


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final BoxDecoration deco = BoxDecoration(color: Colors.white);

  @override
  Widget build(BuildContext context) {
    print(deco.toString());

    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            decoration: deco,
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-12.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c2b7342ca4 (17 hours ago), 2020-05-06 23:16:03 +0800
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (5 available)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.4.1
    • iPhone 11     • B00B6F4E-B1CE-44F3-B81E-3EC6D639B008 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS         • macOS                                • darwin-x64     •
      Mac OS X 10.15.4 19E287
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 81.0.4044.138

• No issues found!


``` 

</details> 

Might be related [#56232](https://github.com/flutter/flutter/issues/56232)

**Comment by mraleph** [comment]
In release mode Flutter shows much less diagnostic information by design. This is done to reduce the code size. You can see it in the code:

```dart
  @override
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.info }) {
    String fullString;
    assert(() {
      fullString = toDiagnosticsNode(style: DiagnosticsTreeStyle.singleLine).toString(minLevel: minLevel);
      return true;
    }());
    return fullString ?? toStringShort();
  }
```

**Comment by SahajRana** [comment]
Hi @mraleph, @TahaTesser , Is there a way opt to have the same behavior across debugging and release mode? As this causes a false expectation of how code will work in release mode. and may cause unknown bugs for developers.

**Comment by mraleph** [comment]
Code should not expect or rely on a particular format of `toString` output. 

Though I am a bit surprised that documentation for `Diagnosticable.toString` and other related methods does not cover the difference between release and debug mode.

/cc @jason-simmons who did change a1aea2e4423af6136f651455b5f1d74363ce29c4

**Comment by dnfield** [comment]
This is by design.

We have altered the implementation of the Diagnostics related classes to avoid retaining lots of extra debugging information in release mode. You can still get this information in profile mode or debug mode.

The problem is that if we retain all that code (and lots and lots of strings), it takes up a substantial portion of the binary.

**Comment by mraleph** [comment]
@dnfield should not this behaviour be clearly documented in the API docs to prevent future issues like this? Right now there is nothing that mentions it anywhere in the documentation as far as I could see.

**Comment by dnfield** [comment]
I'll update some docs on this.

**Comment by dnfield** [comment]
Hah. I did document this already.

https://github.com/flutter/flutter/commit/4a60bee7c0361175abe9f71feb1a1b19b3558736#diff-6ccbd4ed2d70bfa90b733f860afcbea6R336-R337

I'm not sure where else I should document this to be honest. If anyone has suggestions we can re-open this again, or open a new bug about where to more visibly document it.

**Comment by mraleph** [comment]
@dnfield maybe on `toString` specifically? I see documentation on the `DiagnosticsNode`

```
/// In release mode, far less information is retained and some information may
/// not print at all.
```

But getting from `Diagnosticable.toString` to `DiagnosticsNode` requires few hops.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/56906
