### ISSUE TITLE
Source code was changed, but flutter run previous code.

### ISSUE THREAD

**Issue by honvidan** [flutter/flutter#56544]
Hi guys,
Since I upgrade to flutter 1.17. I use Android studio (macOS) develop new feature, source code was changed, but nothing changed when I run it. It used old code. How to fix this problem ?
Thanks!

**Comment by TahaTesser** [comment]
Hi @honvidan 
Where you using experiencing this issue? Android Studio or VS code? You sure changes are being saved? 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by honvidan** [comment]
Hi @TahaTesser 
I used Android Studio to develop Flutter apps. I also can't hot reload, always LOST connection from iOS simulator every saving file code. I just changed little like a text on screen and hot reload, restart or even rebuild but nothing changed on the app. This issue is NOT happend before version 1.12.

I also tested on android emulator. this issue does not happen

below is flutter doctor:

> honvidan@Dans-MacBook-Pro-2 house_map % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-VN)
    • Flutter version 1.17.0 at /Users/honvidan/flutter
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/honvidan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1
[✓] Connected device (1 available)
    • iPhone 11 Pro Max • D67CA381-DDB6-4240-826F-48B199756D8B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
• No issues found!

**Comment by Andy-Python-Programmer** [comment]
Hey @honvidan try running the command `flutter clean` In the cwd ( current working directory ) to clean the cache that might cause the emulator not run the respective app.

**Comment by honvidan** [comment]
Hi @Andy-Python-Programmer 
I also tried flutter clean.
I downgrade to flutter v1.12.13 hotfix 9. Everything is ok.

**Comment by jonahwilliams** [comment]
@Andy-Python-Programmer please do not suggest clean as a workaround for bug reports. This prevents us from being able to fix the issue and will contribute to lower quality flutter releases.

**Comment by jonahwilliams** [comment]
@honvidan to help we would need verbose logs from a `flutter run` where the changes didn't get saved or where it crashed unexpectedly.

**Comment by honvidan** [comment]
@jonahwilliams I could not give the logs because I have downgrade to flutter version 1.12.13 hot fix 9.
Thank you!
