### ISSUE TITLE
For loop does not work inside the widget 

### ISSUE THREAD

**Issue by momarip** [flutter/flutter#56540]
## Steps to Reproduce

1.I updated flutter to the latest version and my app is showing me an error in the "for" loop. What is the solution ?

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

![Capture](https://user-images.githubusercontent.com/52053276/81286906-5f123180-9051-11ea-9ff1-077bbc79be21.JPG)

**Comment by Anushi1998** [comment]
I can not see the logs somehow and neither there is any code attached.

My understanding is you need a list of Widget to include in some `children` property of some top-level widget. You can use `for loop` to generate a list of widgets and then include that list in the existing list (Can consider using spread  `...` operator)

**Comment by momarip** [comment]
@Anushi1998 Sorry, Here is the screen. After I tested again the application run but the error kept being there Any ideas why ?
