### ISSUE TITLE
Please add flutter_scroll_overlay as a manual test

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5654]
Chinmay: Please add  https://github.com/chinmaygarde/flutter_scroll_overlay to flutter/flutter as a manual test (or wherever @Hixie would like).  At some point we should work with @jason-simmons to add an Android version, but that can be a later pass.

**Comment by chinmaygarde** [comment]
@abarth suggested I put it into a separate repository. It is now hosted at https://github.com/flutter/scroll_overlay.

**Comment by eseidelGoogle** [comment]
Thanks for doing this!
