### ISSUE TITLE
flutter 1.17.0 Unhandled Exception: MissingPluginException(No implementation found for method currentUser on channel....

### ISSUE THREAD

**Issue by mitesh77** [flutter/flutter#56548]
when I add this code is working fine in flutter 1.12 after update 1.17.0 it is not working MethodChannel, even I try to create a new flutter project and check I found the same issue in new flutter 1.17.0.

  private val CHANNEL = "samples.flutter.dev/battery"

  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
      call, result ->
      // Note: this method is invoked on the main thread.
      // TODO
    }
  }

**Comment by inceptusp** [comment]
I was having this problem with the upgrade too... I solved it by writing ```super.configureFlutterEngine(flutterEngine)``` inside the configureFlutterEngine override...

Like this:

```
class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        //YOUR METHOD CHANNEL IMPLEMENTATION HERE
    }
}
```

**Comment by TahaTesser** [comment]
Hi @mitesh77 
Does the [solution](https://github.com/flutter/flutter/issues/56548#issuecomment-625239992) from above comments solves your issue?
Thank you

**Comment by mitesh77** [comment]
yes thanks, it works

**Comment by inceptusp** [comment]
They have to update the documentation and add this to "breaking changes" cause now we have to call super when overriding configureFlutterEngine...

**Comment by mitesh77** [comment]
> They have to update the documentation and add this to "breaking changes" cause now we have to call super when overriding configureFlutterEngine...

yes but how?

**Comment by jeffque** [comment]
@inceptusp and @mitesh77 , maybe you should open a new issue on https://github.com/flutter/website/ or just open a PR changing the [file about platform channel](https://github.com/flutter/website/blob/master/src/docs/development/platform-integration/platform-channels.md)

**Comment by michael-ottink** [comment]
If I do this I get the following error 

`W/FlutterEnginePluginRegistry(27907): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@e057cf7) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@273a764).`

**Comment by inceptusp** [comment]
> If I do this I get the following error
> 
> `W/FlutterEnginePluginRegistry(27907): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@e057cf7) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@273a764).`

Maybe you are using some plugin that was not updated to Flutter Embedding V2, 'cause, according to flutter api reference, the ```ShimPluginRegistry``` is a class that let old plugins use the new plugins API and embedding under the hood... You should verify what plugin is causing the issue...

**Comment by ManojDvs** [comment]
hi @michael-ottink did you solve this issue ?

**Comment by ManojDvs** [comment]
@inceptusp 
i have that super.config line in my code, but sometimes my webview gives me this error , " MissingPluginException(No implementation found for method loadUrl on channel plugins.flutter.io/webview_6) ". can you help me .

**Comment by mqhamdam** [comment]
I got the same issue using permission required plugins and Firestore.

**Comment by harshlohia** [comment]
> I was having this problem with the upgrade too... I solved it by writing `super.configureFlutterEngine(flutterEngine)` inside the configureFlutterEngine override...
> 
> Like this:
> 
> ```
> class MainActivity: FlutterActivity() {
> 
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         super.configureFlutterEngine(flutterEngine);
>         //YOUR METHOD CHANNEL IMPLEMENTATION HERE
>     }
> }
> ```

where do we supposed to add this code, because i am facing the same issue from last one week and still no luck?
