### ISSUE TITLE
Make iOS Scroll physics match UIScrollView

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5655]
Making our scroll physics match iOS should be possible now with Chinmay's demo:
https://github.com/chinmaygarde/flutter_scroll_overlay

When I last saw it we achieved the right velocity, but not the correct acceleration/deceleration curve.

I've asked @chinmaygarde to land the demo in flutter/flutter: https://github.com/flutter/flutter/issues/5654

**Comment by eseidelGoogle** [comment]
@HansMuller is this done now?

**Comment by HansMuller** [comment]
Yes!

Fixed in https://github.com/flutter/flutter/pull/6334
