### ISSUE TITLE
Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory

### ISSUE THREAD

**Issue by gourav-varma** [flutter/flutter#56557]
![fluttererror](https://user-images.githubusercontent.com/64647858/81307173-01580680-909e-11ea-9b8e-2bcdd49e755b.JPG)
that's the error message. it's been showing it since the upgrade.
![fe](https://user-images.githubusercontent.com/64647858/81307450-4f6d0a00-909e-11ea-91d3-d46b6f23b558.JPG)
that's my flutter doctor message.

please help.. thanks in advance

**Comment by VladyslavBondarenko** [comment]
Hi @gourav-varma 
could you provide `flutter run --verbose` log?

Please don't post screenshots of text, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by gourav-varma** [comment]
> Hi @gourav-varma
> could you provide `flutter run --verbose` log?
> 
> Please don't post screenshots of text, post the text instead.
> Screenshots are not searchable and it's not possible to copy-past text out of it.

Yeah, will keep that in mind from the next time.
I installed my previous version and its working now.
Thanks
