### ISSUE TITLE
[Web] How to use JS Charts In Flutter Web?

### ISSUE THREAD

**Issue by yk3372** [flutter/flutter#56562]
I want to use flutter develop my website.
But I don't know how to use the JS charts in Flutter Web.
I want to use the excellent and mature chart library such as Echarts/AntV.

Please help me, thanks!

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by liraku** [comment]
Have you found a solution?
I also want to use AntV in flutter
