### ISSUE TITLE
Error at spread-collections 

### ISSUE THREAD

**Issue by fbyucel** [flutter/flutter#56566]
```
This requires the 'spread-collections' experiment to be enabled.
Try enabling this experiment by adding it to the command line when compiling and running.dart(experiment_not_enabled)
```

> body: Column(children: [
>         Question(questions[index]['questionText']),
>         ...(questions[index]['answers'] as List<String>).map((answer) {
>           return Answer(_answerSelect, answer);
>         }).toList()
>       ]),
>     )

I have a problem when using ... keyword in list.
```
[√] Flutter: is fully installed. (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.17763.1158], locale tr-TR)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.3)
[√] Android Studio: is fully installed. (version 3.6)
[√] VS Code: is fully installed. (version 1.44.2)
[√] Connected device: is fully installed. (1 available)
```

**Comment by jonahwilliams** [comment]
Your dart language constraint is too low in your pubspec: bump it up to at least 2.6.0 and this warning should go away
