### ISSUE TITLE
Opt-in to download full Dart SDK

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#56573]
The Dart SDK that currently comes bundled with Flutter is missing some tools (e.g. `dart2native`). We'd like to opt-in to instead download a complete Dart SDK, maybe via `flutter config --download-complete-dart-sdk` (or some similar flag). This way, we won't have 2 different Dart SDKs for our tooling. Making this opt-in (disabled) by default won't make any difference for current users.

**Comment by jonahwilliams** [comment]
Rather than an opt in, which is going to add  more logic to the already fragile bash/batch scripts, we should simply include the full dart-sdk by default

**Comment by mit-mit** [comment]
Closing: master-channel builds have a functioning Dart SDK with a new unified `dart` tool in the `bin/` folder.

**Comment by Zazo032** [comment]
@mit-mit it's indeed functioning, but still missing some tools like `dart2native` as I said in the OP. Any possibility those can be bundled too?

**Comment by mit-mit** [comment]
Use `dart compile` instead.
