### ISSUE TITLE
macOS xcode project should move Framework linking to tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#56581]
See also https://github.com/flutter/flutter/pull/51453

> not because of the simulator thing (no macOS simulator) but instead so the tool script as total control of where the Flutter.framework is and doesn't need to copy it to a specific spot

From @jmagman

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/51453#issuecomment-591700311

> I think it may be a good idea to do the same pattern for macOS for the future-proofing xcframework / App.framework rename reasons I mentioned in the "Observations" section, and to remove the [`disable_input_output_paths` hack](https://github.com/flutter/flutter/issues/20685#issuecomment-497467651) in the macOS Podfile. However there's no immediate need to do this since Mac won't hit #50568 (there is no simulator, frameworks always have the x86 architectures, no thinning happens). I would defer to @stuartmorgan on the necessity and/or timing of that change.

**Comment by jmagman** [comment]
This will make arm macOS support easier.
