### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<PopupMenuEntry<Animals>>'

### ISSUE THREAD

**Issue by GitHub-Ashmar** [flutter/flutter#56585]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by tapizquent** [comment]
This issue says nothing. How did you run into this? Is there a way to reproduce it? Maybe show some code where we can see how to help

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
