### ISSUE TITLE
FlutFlutter 1.17 is live! - confusing related to web support

### ISSUE THREAD

**Issue by peterlauri** [flutter/flutter#56588]
1.17.0 is announced to be the last stable version. The 1.17.0 is same as the beta track. Beta includes web support, but it states in the Blog that "As our mobile support continues to mature while we bring the web closer to production quality". But Web is already there in the 1.17.0, so it is in "stable" mode, but not production ready. What is the real deal here?

**Comment by peterlauri** [comment]
Minor notes. I did swap to stable channel, and web support is gone. Going back to beta brings back web support. However, they refer to the same git commit. Strange. Confusing.

**Comment by stuartmorgan** [comment]
> so it is in "stable"

This is not the case, as you have discovered. See the "Note" box [here](https://flutter.dev/docs/get-started/web#requirements).
