### ISSUE TITLE
Migrate to Android 11 API for insets and UI visibility

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#56592]
Flutter currently uses a set of hacks and workarounds to determine visibility of onscreen keyboard and navbar when in fullscreen mode: https://github.com/flutter/engine/pull/18193

As of Android 11 (API 30), there now exists native ways of properly determining this behavior. We should migrate to targeting the latest SDK and implement the new API to avoid hacks in the future.

**Comment by xster** [comment]
Need to do https://github.com/flutter/flutter/issues/56597 first

**Comment by Zazo032** [comment]
Would this help with https://github.com/flutter/flutter/issues/34678 and https://github.com/flutter/flutter/issues/40974?

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/18339

The above PR is WIP and still using the preview 4 version of API 30. We should wait until the full android API 30 before considering landing it.
