### ISSUE TITLE
Support Android 11 display cutouts, waterfall

### ISSUE THREAD

**Issue by xster** [flutter/flutter#56599]
`DisplayCutout.getSafeInset…()` now returns screen safe areas like iOS

We can also follow the keyboard animation now with `setOnApplyWindowInsetsListener(new View.OnApplyWindowInsetsListener())`

~~We can also move the keyboard now with `getWindowInsetsController().controlWindowInsetsAnimation()` to support https://github.com/flutter/flutter/issues/57609 on Android~~

Need to do https://github.com/flutter/flutter/issues/56597 first~~

**Comment by xster** [comment]
Splitting keyboard synchronization to #62876

**Comment by xster** [comment]
The upstream API has been slightly updated. New doc https://developer.android.com/reference/android/view/DisplayCutout

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/20921 Implements merging DisplayCutouts into existing API.

**Comment by GaryQian** [comment]
I filed a new issue to track exposing the detailed rects https://github.com/flutter/flutter/issues/65088
