### ISSUE TITLE
[Add2App iOS] Flutter view takes much longer to load on a device for a debug build than before

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#56606]
When launching a Flutter view in an existing app, as of the latest versions of Flutter, it takes about 4-5 extra seconds before anything is actually rendered on the screen, after seeing logs printed from our route widget's build method.

I think this happens with native Flutter apps as well, seeing they just seem very long to launch (longer than before).

But in our case, we have timed about 4-5 seconds of dead time between the logs from our build method and the view actually rendering.

This was never the case before.

I've noticed this with `1.18.0-dev.3.0` and `1.18.0-11.0.pre`.

**Comment by dannyvalentesonos** [comment]
[✓] Flutter (Channel dev, 1.18.0-11.0.pre, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.18.0-11.0.pre at /Users/danny.valente/Library/flutter/1.18.0-11.0.pre-dev
    • Framework revision 8568eda15b (2 days ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

 
[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
can you please provide a reproducible minimal sample project.
Thank you

**Comment by dannyvalentesonos** [comment]
@iapicca I couldn't reproduce with a sample app, so I dug further into this, and it's something I changed in my application that is causing this. 
We can go ahead and close this.

Thanks.

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
thank you for letting me know
