### ISSUE TITLE
I install new version Flutter v1.17.0,  there is something wrong when I debug on ios.  And when I pod install my podfile,  int present "Installing Flutter (1.12.1309)", so I see there is something wrong. 

### ISSUE THREAD

**Issue by FallInLoveMyGod** [flutter/flutter#56629]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @FallInLoveMyGod 
Could you provide your `flutter doctor -v` and related logs? and describe what is wrong when debugging

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
