### ISSUE TITLE
Files Do Not Sync To My Android Device after App is Launched

### ISSUE THREAD

**Issue by atheistrepublic** [flutter/flutter#56637]
![Screenshot from 2020-05-08 12-21-29](https://user-images.githubusercontent.com/58817288/81383235-51ca7500-912d-11ea-857f-38f3aa6dfb86.png)
I have this issue that when i run flutter run everything works fine and the app launches correctly on my device but after launching the app the files do not sync to my device.I think this issue is related to adb logcat as when i type adb logcat in the terminal i get no output on the terminal but when i type adb shell -x logcat i get the correct output.I am using Ubuntu 18.04 and LG M700 .Also adv version is :
Android Debug Bridge version 1.0.41
Version 30.0.0-6374843
Installed as /usr/lib/android-sdk/platform-tools/adb

I am attatching the screenshot where you can see that after launching the app on device the
the sync files is not shown .It is stuck at "✓ Built build/app/outputs/apk/debug/app-debug.apk."
although the app is installedand launched on device correctly.
![Screenshot from 2020-05-08 11-43-37](https://user-images.githubusercontent.com/58817288/81376547-5f79fd80-9121-11ea-89a3-0753d646be29.png)
![Screenshot from 2020-05-08 11-46-44](https://user-images.githubusercontent.com/58817288/81376641-9cde8b00-9121-11ea-8fba-6bff4f576bee.png)

**Comment by VladyslavBondarenko** [comment]
Hi @atheistrepublic 
could you provide your `flutter doctor -v` and `flutter run --verbose log`?

Please don't post screenshots of text where is not necessary, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by atheistrepublic** [comment]
Ok so below i am providing the logs of flutter run --verbos and flutter doctor -v.I am attaching the log file for flutter run --verbose as you can see at the end it always says Waiting for observatory port to be available... and stuck at that point .Why is this happening?
1) flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.9 at /home/physics/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/lib/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.0

[✓] Connected device (1 available)
    • LG M700 • LGM70059f80c28 • android-arm • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
[log1.txt](https://github.com/flutter/flutter/files/4598253/log1.txt)

2) flutter run --verbose
[  +31 ms] executing: [/home/physics/flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/home/physics/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +11 ms] executing: [/home/physics/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/physics/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] executing: [/home/physics/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +126 ms] executing: /usr/lib/android-sdk/platform-tools/adb devices -l
[  +20 ms] Exit code 0 from: /usr/lib/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           LGM70059f80c28         device usb:1-1.2 product:mh_global_com
           model:LG_M700 device:mh transport_id:1
[  +39 ms] /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28 shell
getprop
[ +139 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +180 ms] Generating
/home/physics/Desktop/ALL/FLUTTERProjects/project1/android/app/src/main/java/io/
flutter/plugins/GeneratedPluginRegistrant.java
[  +32 ms] ro.hardware = mh
[        ] ro.build.characteristics = default
[  +71 ms] Launching lib/main.dart on LG M700 in debug mode...
[   +9 ms] executing: /usr/lib/android-sdk/build-tools/28.0.3/aapt dump xmltree
/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk/app.apk
AndroidManifest.xml
[  +16 ms] Exit code 0 from: /usr/lib/android-sdk/build-tools/28.0.3/aapt dump
xmltree
/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk/app.apk
AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.project1" (Raw: "com.example.project1")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="project1" (Raw: "project1")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication"
                 (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.project1.MainActivity"
                   (Raw: "com.example.project1.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +17 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell -x logcat -v time -t 1
[ +194 ms] Exit code 0 from: /usr/lib/android-sdk/platform-tools/adb -s
LGM70059f80c28 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           05-08 15:07:36.516 I/art     ( 6749): Starting a blocking GC Explicit
[  +15 ms] executing: /usr/lib/android-sdk/platform-tools/adb version
[   +1 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
logcat -v time -T 05-08 15:07:36.516
[  +34 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as /usr/lib/android-sdk/platform-tools/adb
[   +4 ms] executing: /usr/lib/android-sdk/platform-tools/adb start-server
[  +14 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from
/home/physics/Desktop/ALL/FLUTTERProjects/project1/android/gradlew.
[   +7 ms] executing:
[/home/physics/Desktop/ALL/FLUTTERProjects/project1/android/]
/home/physics/Desktop/ALL/FLUTTERProjects/project1/android/gradlew
-Pverbose=true
-Ptarget=/home/physics/Desktop/ALL/FLUTTERProjects/project1/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm assembleDebug
[+6169 ms] Starting a Gradle Daemon, 1 busy Daemon could not be reused, use
--status for details
[+25586 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +28 ms] executing: [/home/physics/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +1 ms] [        ] executing: [/home/physics/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[   +1 ms] [  +10 ms] Exit code 0 from: git describe --match v*.*.*
--first-parent --long --tags
[   +1 ms] [        ] v1.12.13+hotfix.9-0-gf139b1100
[        ] [  +13 ms] executing: [/home/physics/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[        ] [  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/physics/flutter/] git ls-remote
--get-url origin
[        ] [   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +71 ms] executing: [/home/physics/flutter/] git rev-parse
--abbrev-ref HEAD
[        ] [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +30 ms] Artifact Instance of 'AndroidMavenArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[   +1 ms] [ +156 ms] Initializing file store
[   +1 ms] [  +50 ms] Done initializing file store
[+3476 ms] [+4077 ms] kernel_snapshot: Starting due to
{InvalidatedReason.inputChanged}
[ +100 ms] [  +19 ms] /home/physics/flutter/bin/cache/dart-sdk/bin/dart
/home/physics/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.
snapshot --sdk-root
/home/physics/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field
-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --no-link-platform --packages
/home/physics/Desktop/ALL/FLUTTERProjects/project1/.packages --output-dill
/home/physics/Desktop/ALL/FLUTTERProjects/project1/.dart_tool/flutter_build/68a8
0a3b01ff59a50831d1b8b2326bb1/app.dill --depfile
/home/physics/Desktop/ALL/FLUTTERProjects/project1/.dart_tool/flutter_build/68a8
0a3b01ff59a50831d1b8b2326bb1/kernel_snapshot.d package:project1/main.dart
[+8499 ms] [+8538 ms] kernel_snapshot: Complete
[ +500 ms] [ +483 ms] invalidated build due to missing files:
/home/physics/Desktop/ALL/FLUTTERProjects/project1/assets/Calibre, Semibold.otf
[ +499 ms] [ +537 ms] debug_android_application: Starting due to
{InvalidatedReason.inputChanged, InvalidatedReason.outputMissing,
InvalidatedReason.inputMissing}
[ +999 ms] [ +979 ms] debug_android_application: Complete
[ +107 ms] [  +96 ms] Persisting file store
[        ] [  +10 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [  +14 ms] "flutter assemble" took 15,019ms.
[ +291 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[ +100 ms] > Task :app:checkDebugManifest UP-TO-DATE
[  +99 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +198 ms] > Task :app:cleanMergeDebugAssets
[ +100 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugAssets
[ +399 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +99 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +299 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +199 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[  +99 ms] > Task :app:processDebugResources UP-TO-DATE
[ +800 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[ +100 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +100 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[  +98 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +199 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +299 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[ +200 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[ +198 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[  +99 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[+4399 ms] > Task :app:packageDebug
[        ] > Task :app:assembleDebug
[ +102 ms] BUILD SUCCESSFUL in 54s
[   +1 ms] 30 actionable tasks: 5 executed, 25 up-to-date
[ +350 ms] Running Gradle task 'assembleDebug'... (completed in 54.9s)
[ +470 ms] calculateSha: LocalDirectory:
'/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk'/app.a
pk
[  +94 ms] calculateSha: reading file took 93us
[+1011 ms] calculateSha: computing sha took 1010us
[   +5 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +2 ms] executing: /usr/lib/android-sdk/build-tools/28.0.3/aapt dump xmltree
/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk/app.apk
AndroidManifest.xml
[  +22 ms] Exit code 0 from: /usr/lib/android-sdk/build-tools/28.0.3/aapt dump
xmltree
/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.project1" (Raw: "com.example.project1")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="project1" (Raw: "project1")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication"
                 (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.project1.MainActivity"
                   (Raw: "com.example.project1.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +3 ms] Stopping app 'app.apk' on LG M700.
[   +1 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell am force-stop com.example.project1
[+2242 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell pm list packages com.example.project1
[+1651 ms] package:com.example.project1
[   +5 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell cat /data/local/tmp/sky.com.example.project1.sha1
[  +56 ms] 03b6b1bccefada57aa6ca1905f975582ef34d40e
[   +2 ms] Installing APK.
[   +4 ms] executing: /usr/lib/android-sdk/platform-tools/adb version
[  +15 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as /usr/lib/android-sdk/platform-tools/adb
[   +1 ms] executing: /usr/lib/android-sdk/platform-tools/adb start-server
[  +14 ms] Installing build/app/outputs/apk/app.apk...
[   +1 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
install -t -r
/home/physics/Desktop/ALL/FLUTTERProjects/project1/build/app/outputs/apk/app.apk
[+10304 ms] Performing Streamed Install
                     Success
[   +1 ms] Installing build/app/outputs/apk/app.apk... (completed in 10.3s)
[   +4 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell echo -n 224d66d4f4ed219c237e7512c22996022e8309c9 >
/data/local/tmp/sky.com.example.project1.sha1
[  +81 ms] LG M700 startApp
[   +6 ms] executing: /usr/lib/android-sdk/platform-tools/adb -s LGM70059f80c28
shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true
com.example.project1/com.example.project1.MainActivity
[+1921 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.example.project1/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...

**Comment by VladyslavBondarenko** [comment]
@atheistrepublic 
is https://github.com/flutter/flutter/issues/33214#issuecomment-568733832 your case?

**Comment by atheistrepublic** [comment]
**No this is not my case.That is a completely different issue/case.**

**Comment by VladyslavBondarenko** [comment]
@atheistrepublic 
do you have another device to check if it works with it? or with emulator. 
Does it happen with any project? If no, can you provide a minimal reproducible project?

**Comment by atheistrepublic** [comment]
1) There seems to be something wrong with adb itself.It does not recognise any other devices except LG M700 which i am using.

2) Even if it recognises my LG M700 the adb logcat command does not work in terminal but only in shell which maybe the cause of No sync files.

3)adb was working before when i had not installed flutter and other tools .Before it was connecting to all the other devices and even mine and adb logcat command was also working in the terminal.
So i seems that there is some problem with adb and also yes it is happening for all projects on my device.No files sync for any of them.

**Comment by xster** [comment]
which `adb` is in your PATH? Try running `/usr/lib/android-sdk/platform-tools/adb` directly (since that's where flutter doctor is pointing). Otherwise it may be an issue with the Android SDK installation. Does it work in Android Studio?

**Comment by atheistrepublic** [comment]
No that doesn't work either.As you can see in the flutter doctor -v i am not using android studio.
1) adb logcat is only working in shell mode as can be seen in the screenshot attached below
2)Even the command **/usr/lib/android-sdk/platform-tools/adb logcat** does not work.

After the app is launched on device the terminal is stuck at 
**Waiting for observatory port to be available...**

**Comment by atheistrepublic** [comment]
I figured it out and solved the issue.This was happening because it seems adb version i was using had some bugs .So i downgraded platform-tools to 28.0.0 as was suggested in the post linked below:
https://superuser.com/questions/1357708/android-adb-logcat-works-only-on-shell/1357929#1357929

I am closing this issue as it has been solved.
