### ISSUE TITLE
[iOS] framework not found Flutter after upgrade Flutter stable version 1.17.0

### ISSUE THREAD

**Issue by dao-wkm** [flutter/flutter#56642]
## Steps to Reproduce

1. flutter upgrade (stable channel from 1.12.13+hotfix.9 to 1.17.0)
2. flutter pub get
3. flutter run --flavor development -t  lib/main_development.dart

## Logs

```
Running pod install...                                              6.2s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           19.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-05-08 14:11:56.691 xcodebuild[34825:277471]  DTDeviceKit: deviceType from 00008020-00166D842198003A was NULL
    2020-05-08 14:11:56.702 xcodebuild[34825:277471]  DTDeviceKit: deviceType from 00008006-00162B0E3647002E was NULL
    2020-05-08 14:12:07.919 XCBBuildService[34834:277678] Failed to remove:
    /Users/mac/Library/Developer/Xcode/DerivedData/Runner-cbjfnxiwnppywiclnxpxnaledqlr/Build/Intermediates.noindex/XCBuildData/e8302ca234024578636961d2dea6a107-manifest.xcbuild:
    unlink(/Users/mac/Library/Developer/Xcode/DerivedData/Runner-cbjfnxiwnppywiclnxpxnaledqlr/Build/Intermediates.noindex/XCBuildData/e8302ca234024578636961d2dea6a107-manifest.xcbuild): No such file or directory (2)
    2020-05-08 14:12:08.534 XCBBuildService[34834:277678] Failed to remove:
    /Users/mac/Library/Developer/Xcode/DerivedData/Runner-cbjfnxiwnppywiclnxpxnaledqlr/Build/Intermediates.noindex/XCBuildData/e8302ca234024578636961d2dea6a107-desc.xcbuild:
    unlink(/Users/mac/Library/Developer/Xcode/DerivedData/Runner-cbjfnxiwnppywiclnxpxnaledqlr/Build/Intermediates.noindex/XCBuildData/e8302ca234024578636961d2dea6a107-desc.xcbuild): No such file or directory (2)
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'FLAnimatedImage' from project 'Pods')
    warning: AssetsLibrary is deprecated. Consider migrating to Photos instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'DKPhotoGallery' from project 'Pods')
```

## flutter doctor -v

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-VN)
    • Flutter version 1.17.0 at /Users/mac/flutter/flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Dao Anh Le • 00008020-00166D842198003A • ios • iOS 13.4.1
```

## More Infomation
- Targets: Runner, OneSignalNotificationServiceExtension
- `flutter create && flutter pub get && flutter run` it work

## Tried to fix:
- `flutter clean`
- `rm -rf ios/Pods Podfile.lock`
- `pod install`
- `pod repo update && pod setup`
- `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
- XCode Clean Build Folder
- re-install flutter SDK
- reset my Macbook
- iOS migration XCode 11.4: https://flutter.dev/docs/development/ios-project-migration

**Comment by Martin-Alvarado-Void** [comment]
Same issue, also since i upgraded to  flutter 1.17.0

`
6 warnings generated.
    The path  does not exist
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Using build description from disk
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'FLAnimatedImage' from project 'Pods')
    warning: AssetsLibrary is deprecated. Consider migrating to Photos instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'DKPhotoGallery' from project 'Pods')
`

**Comment by JJzhu2020** [comment]
Related to https://github.com/flutter/flutter/issues/54571 and https://github.com/flutter/flutter/issues/56507

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/56479

**Comment by xster** [comment]
Possibly related to #56507. #54571 and #56479 aren't related.

**Comment by xster** [comment]
Sorry, #56507 isn't related either. 

@dao-wkm is this a flavor specific issue? i.e. does it work if you don't use the `--flavor` flag?

**Comment by jmagman** [comment]
> unlink(/Users/mac/Library/Developer/Xcode/DerivedData/Runner-cbjfnxiwnppywiclnxpxnaledqlr/Build/Intermediates.noindex/XCBuildData/e8302ca234024578636961d2dea6a107-desc.xcbuild): No such file or directory (2)

That looks like it's the bowels of Xcode's build system.  Does a `flutter clean` (to clean the Xcode workspace) fix it?  If not, try closing Xcode, deleting DerivedData (likely at ~/Library/Developer/Xcode/DerivedData), and then running again.

**Comment by jmagman** [comment]
> flutter clean

Oh you said you tried that, sorry I missed it.

Can you try deleting DerivedData though?

**Comment by jmagman** [comment]
> rm -rf ~/Library/Developer/Xcode/DerivedData/*

Okay sorry I see you tried that too.

**Comment by jmagman** [comment]
@Martin-Alvarado-Void I don't think you are hitting the same issue, looks like https://github.com/flutter/flutter/issues/56507.

**Comment by Martin-Alvarado-A** [comment]
> @Martin-Alvarado-Void I don't think you are hitting the same issue, looks like #56507.

Thanks i subscribed to it, hope there's a fix soon or steps to fix it.

**Comment by dao-wkm** [comment]
> Sorry, #56507 isn't related either.
> 
> @dao-wkm is this a flavor specific issue? i.e. does it work if you don't use the `--flavor` flag?

Flutter run also does not work.
But it works with `flutter create && flutter pub get && flutter run`

**Comment by jmagman** [comment]
Can we get the full `flutter run` output with the `--verbose` flag?  Can you also attach your `ios/Runner.xcodeproj/project.pbxproj`?
See https://github.com/flutter/flutter/issues/56507#issuecomment-631028894 for something similar that may be going on.

**Comment by TahaTesser** [comment]
Accidentally removed waiting label, i thought wait label was older than 21 days.

**Comment by dao-wkm** [comment]
I must admit that the problem is related to Configurations and Flavors.
If you face this problem, please create a new flutter project and compare it with your project

![Screen Shot 2020-07-14 at 09 28 45](https://user-images.githubusercontent.com/42726313/87374340-ea112a00-c5b4-11ea-809f-6ba5d831b72c.png)
![Screen Shot 2020-07-14 at 09 29 09](https://user-images.githubusercontent.com/42726313/87374353-ebdaed80-c5b4-11ea-9ef0-cd142f286a3b.png)
