### ISSUE TITLE
Error waiting for a debug connection: Bad state: No element Error launching application on V1936A.

### ISSUE THREAD

**Issue by 309791679** [flutter/flutter#56648]
```bash
Error waiting for a debug connection: Bad state: No element
Error launching application on V1936A.
```

flutter version
``` console
 Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at G:\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
```

android 10
ide Android Studio 3.6.2

Please answer me

**Comment by 309791679** [comment]
Real machine debugging  

No problem with the virtual machine

**Comment by iapicca** [comment]
Hi @309791679 
could you please run `flutter upgrade --force` and
provide your `flutter doctor -v` , 
and your `flutter run --verbose` 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
