### ISSUE TITLE
Would be nice to disable curves when a user gesture controls an AnimationController

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#5664]
I've run into this problem twice so far (with drawers and the ios back gesture). If you have a UI component that can both animate and be controlled via a drag, you run into problems if that animation has a curve applied to it. Any non-linear curve means there is no longer a 1:1 mapping between finger movements and the position of the component. The only solution is to remove all curves from the animation.

Maybe there could be a way to inform the AnimationController when a user gesture is in progress. During that time, all curves are disabled and the animation becomes linear. Though this might be overly simplistic - you'd really only want to disable curves on the animation that applies to the widget being dragged.

**Comment by Hixie** [comment]
How does Drawer deal with this?

**Comment by mpcomplete** [comment]
Drawer uses a linear curve always, but uses a physics-based spring simulation when animating without user gesture (as if you had flung it at a certain speed).

**Comment by Hixie** [comment]
I'm going to close this bug, we'll support this on an as-needed basis.
