### ISSUE TITLE
AppCenter builds failing for iOS

### ISSUE THREAD

**Issue by Bokriem** [flutter/flutter#56647]
Our last successful build was two days ago. Since our last successful build we have been getting the same build error:

```bash
Failed to find the latest git commit date: VersionCheckError: Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso

We get the build error on all our pipelines and with any commit, even commits that previously built successfully fails.

This is the output from AppCenter:

+ export PATH=/Users/runner/runners/2.166.4/work/1/s/flutter/bin:/Library/Frameworks/Mono.framework/Versions/4/bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools
+ PATH=/Users/runner/runners/2.166.4/work/1/s/flutter/bin:/Library/Frameworks/Mono.framework/Versions/4/bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools
+ flutter version 1.12.13+hotfix.9
Downloading Dart SDK from Flutter engine 540786dd51f112885a89792d678296b95e6622e5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 21  212M   21 46.3M    0     0  68.0M      0  0:00:03 --:--:--  0:00:03 67.9M
 74  212M   74  157M    0     0  93.9M      0  0:00:02  0:00:01  0:00:01 93.8M
100  212M  100  212M    0     0   101M      0  0:00:02  0:00:02 --:--:--  101M
Building flutter tool...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Downloading Material fonts...                                       0.4s
Downloading Gradle Wrapper...                                       0.0s
Downloading package sky_engine...                                   0.2s
Downloading flutter_patched_sdk tools...                            1.0s
Downloading flutter_patched_sdk_product tools...                    0.6s
Downloading darwin-x64 tools...                                     1.2s
Downloading libimobiledevice...                                     0.0s
Downloading usbmuxd...                                              0.0s
Downloading libplist...                                             0.0s
Downloading openssl...                                              0.1s
Downloading ios-deploy...                                           0.0s
Downloading darwin-x64/font-subset tools...                         0.2s
╔══════════════════════════════════════════════════════════════════════════════╗
║ Warning: "flutter version" will leave the SDK in a detached HEAD state.      ║
║ If you are using the command to return to a previously installed SDK version ║
║ consider using the "flutter downgrade" command instead.                      ║
╚══════════════════════════════════════════════════════════════════════════════╝

Switching Flutter to version 0.0.0-unknown

Downloading engine...
Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  200M    0   321    0     0   1059      0 55:11:38 --:--:-- 55:11:38  1055
 31  200M   31 63.9M    0     0  58.5M      0  0:00:03  0:00:01  0:00:02 58.5M
 58  200M   58  116M    0     0  55.8M      0  0:00:03  0:00:02  0:00:01 55.8M
 92  200M   92  185M    0     0  59.9M      0  0:00:03  0:00:03 --:--:-- 59.9M
100  200M  100  200M    0     0  61.0M      0  0:00:03  0:00:03 --:--:-- 61.0M
Building flutter tool...
Downloading Android Maven dependencies...                          20.1s
Downloading android-arm-profile/darwin-x64 tools...                 0.6s
Downloading android-arm-release/darwin-x64 tools...                 0.4s
Downloading android-arm64-profile/darwin-x64 tools...               0.3s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
Downloading android-x64-profile/darwin-x64 tools...                 0.3s
Downloading android-x64-release/darwin-x64 tools...                 0.3s
Downloading android-x86 tools...                                    0.9s
Downloading android-x64 tools...                                    0.8s
Downloading android-arm tools...                                    0.5s
Downloading android-arm-profile tools...                            0.3s
Downloading android-arm-release tools...                            0.3s
Downloading android-arm64 tools...                                  0.5s
Downloading android-arm64-profile tools...                          0.3s
Downloading android-arm64-release tools...                          0.3s
Downloading android-x64-profile tools...                            0.3s
Downloading android-x64-release tools...                            0.3s
Downloading android-x86-jit-release tools...                        0.4s
Downloading ios tools...                                            1.3s
Downloading ios-profile tools...                                    1.1s
Downloading ios-release tools...                                    5.0s
Downloading package sky_engine...                                   0.2s
Downloading common tools...                                         0.6s
Downloading common tools...                                         0.5s
Downloading darwin-x64 tools...                                     1.2s
Downloading ideviceinstaller...                                     0.0s
Downloading libzip...                                               0.0s

Failed to find the latest git commit date: VersionCheckError: Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard out: 1
Standard error: 
Returning 1970-01-01 00:00:00.000 instead.
Flutter 0.0.0-unknown • channel 1 • unknown source
Framework • revision f139b11009 (1) • 1970-01-01 00:00:00.000
Engine • revision af51afceb8
Tools • Dart 2.8.1
```

**Comment by iapicca** [comment]
Hi @Bokriem 
you are mentioning the crash involving `AppCenter`,
does the app build locally?
Could you please 
run `flutter upgrade --force` 
then provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

related to https://github.com/flutter/flutter/issues/56479

**Comment by Bokriem** [comment]
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/henknel/Development/flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/henknel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 2386932C-CDDB-4B0E-A94C-F33FF333CB40 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!

**Comment by Bokriem** [comment]
environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.9
  intl: 0.16.1
  chewie: 0.9.10
  sqflite: 1.3.0
  connectivity: 0.4.8+2
  url_launcher: 5.4.2
  launch_review: 2.0.0
  firebase_core: 0.4.4+3
  flutter_google_ad_manager: 0.10.1
  page_indicator: 0.3.0
  scroll_to_index: 1.0.6
  flutter_webview_plugin: 0.3.11
  firebase_storage: 3.1.5
  firebase_database: 3.1.3
  firebase_messaging: 6.0.13
  firebase_analytics: 5.0.11
  firebase_auth: 0.15.5+3
  firebase_dynamic_links: 0.5.0+11
  fluttertoast: 4.0.1
  google_sign_in: 4.4.1
  flutter_facebook_login: 3.0.0
  flutter_twitter_login:
    git: git://github.com/eudangeld/flutter_twitter_login.git
  shared_preferences: 0.5.6+3
  flutter_local_notifications: 1.4.0
  flutter_datetime_picker: 1.3.5
  catcher: 0.3.3
  provider: 3.2.0
  shimmer: 1.1.1
  flutter_youtube: 2.0.0
  timeago: 2.0.26
  cached_network_image: 2.0.0
  data_connection_checker: 0.3.4
  video_player: 0.10.8+1
  youtube_player_flutter: 6.1.0+4
  flutter_inappwebview: 2.1.0+1
  firebase_crashlytics: 0.1.3+3
  palette_generator: 0.2.2
  package_info: 0.4.0+16
  uni_links: 0.2.0
  app_settings: 3.0.1
  table_calendar: 2.2.3
  share: 0.6.3+6
  recase: 3.0.0
  rxdart: 0.23.1
  email_validator: 1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

**Comment by Bokriem** [comment]
@iapicca herewith the build log as requested
[log.txt](https://github.com/flutter/flutter/files/4598922/log.txt)

**Comment by xster** [comment]
Not clear what the specific issue is. The first and last post are pointing to entirely different things. 

Your first post is about a CI build issue. It's failing to use a git command to determine the time of the last git commit. This can happen if the local git cloned repo is corrupt. It depends on what your CI build script is (e.g. did you delete the .git folder?).

From the output, it looks like you cloned flutter version 1.12.13+hotfix.9 and then git checked out something else.

The last post is a failure to build a specific third party package that has a bug https://github.com/Realank/flutter_datetime_picker/issues/124. There's code in the package that extends `Diagnosticable` which has always been a mixin.

**Comment by xster** [comment]
Not related to #56479 which is a Dart compilation issue.

**Comment by Bokriem** [comment]
@xster thanks for the insight.

Just a quick one concerning your advise:

The issue is not with AppCenter exclusively, I reached out to the AppCenter team and they asked me to run the build locally using the same appcenter-post-clone script, I got the exact same error.

Our build script has not changed, and for the most part our script is boiler plate.

Regarding the output from AppCenter, we are indeed using flutter version 1.12.13+hotfix.9

Lastly, I would have to agree with you, the last post is not related we get the build failure/s when we upgrade flutter to version 1.17.0, I included it here because @iapicca had requested a verbose build log. The log was generated by the build process after I executed a force upgrade as advised.

We do not get these errors with flutter version 1.12.13+hotfix.9, hence our decision to stick with the working version. However, as stated before we are suddenly experiencing issues with flutter version 1.12.13+hotfix.9, we always had successful build until two days ago when it suddenly started failing on the git command.

For those in our team that has not upgrade flutter they seem to be able to run successful build, for the rest of the team that has upgraded we cannot produce successful build using the latest upgrade, even rolling back to flutter version 1.12.13+hotfix.9 after the upgrade does not work when you execute "flutter version 1.12.13+hotfix.9". The only way to fix the build issue is to download SDK v1.12.13+hotfix.9, and execute "flutter clean"

As I mentioned before, not much has changed in our project, the issue started out of the blue?

Here is our build script (some portions are redacted):

#!/usr/bin/env bash
#Place this script in project/ios/

#Fetch and update AppCenter build id for pubspec.yaml
PUBSPEC_YAML="$BUILD_REPOSITORY_LOCALPATH/pubspec.yaml"
DATESTAMP=$(date +"%y%m%d")
VERSION=`grep version $PUBSPEC_YAML`
VERSIONCODE=$DATESTAMP$APPCENTER_BUILD_ID
BUILD_VERSION=$VERSION+$VERSIONCODE
sed -i.bak "s/$VERSION/$BUILD_VERSION/" $PUBSPEC_YAML
rm -f $PUBSPEC.bak

gem install cocoapods --no-document

# fail if any command fails
set -e
# debug log
set -x

cd ..

[... redacted section ...]

inputJson="{${devJson}${testJson}${qasJson}${prdJson}}"

jq -n "${inputJson}" >assets/json/app_config.json

git clone -b stable https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH

flutter version 1.12.13+hotfix.9
flutter doctor

flutter build ios --release --no-codesign

**Comment by abbasaxx** [comment]
Hi 
I had same problem
just removed:

git clone -b stable https://github.com/flutter/flutter.git
export PATH=pwd/flutter/bin:$PATH

flutter version 1.12.13+hotfix.9



and replaced with:

git stable https://github.com/flutter/flutter.git
export PATH=pwd/flutter/bin:$PATH

flutter version 1.12.13+hotfix.8


and built ok!

**Comment by Bokriem** [comment]
> Hi
> I had same problem
> just removed: **-b stable**
> 
> I mean:
> git clone -b stable https://github.com/flutter/flutter.git
> export PATH=pwd/flutter/bin:$PATH
> 
> flutter version 1.12.13+hotfix.9
> 
> and replaced with:
> 
> git clone https://github.com/flutter/flutter.git
> export PATH=pwd/flutter/bin:$PATH
> 
> flutter version 1.12.13+hotfix.8
> 
> and built ok!

@abbasaxx thanks for the tip, it did not work for me though. I do not get the git command failure, now I only get the pub get failure.

**Comment by abbasaxx** [comment]
YES it is absolutely related!
because of getting first the stable version and then downgrade the version.

do another thing...

```
git clone  -b v1.12.13+hotfix.9 https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH
flutter doctor
```

I hope it fixes it , I tested and no error!!

**Comment by Bokriem** [comment]
> YES it is absolutely related!
> because of getting first the stable version and then downgrade the version.
> 
> do another thing...
> 
> ```
> git clone  -b v1.12.13+hotfix.9 https://github.com/flutter/flutter.git
> export PATH=`pwd`/flutter/bin:$PATH
> flutter doctor
> ```
> 
> I hope it fixes it , I tested and no error!!

@abbasaxx - Thank you kindly, you saved my bacon!

using "git clone  -b v1.12.13+hotfix.9 https://github.com/flutter/flutter.git" did the trick

**Comment by skylineproject** [comment]
Hey folks, this is still happening when using v1.17.0 and later. Downgrading and/or manual builds and uploads are fine for now, but are there any leads on what caused this regression so we aren't stuck using old versions of the flutter SDK forever? :) Thanks!

**Comment by mischaherbrand** [comment]
I'm facing the same issue with the following version: flutter version v1.9.1+hotfix.6

`#!/usr/bin/env bash
#Place this script in project/ios/

# fail if any command fails
set -e
# debug log
set -x

cd ..
git clone -b beta https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH

flutter channel stable
flutter version v1.9.1+hotfix.6
flutter doctor

echo "Installed flutter to `pwd`/flutter"

flutter build ios --release --no-codesign
`

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
