### ISSUE TITLE
Could not find sdklib.jar  when I create new project .... flutter 1.7

### ISSUE THREAD

**Issue by JoDeveloper** [flutter/flutter#56664]
```bash
* What went wrong:                                                      
A problem occurred configuring root project 'android'.                  
> Could not resolve all artifacts for configuration ':classpath'.       
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.5.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.5.0/lint-gradle-api-26.5.0.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.5.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.5.0/tracker-26.5.0.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.5.0).       
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.jar
```

**Comment by JoDeveloper** [comment]
> `Build file '/home/joe/Desktop/flutter-projects/new_missing/android/app/build.gradle' line: 26
> A problem occurred evaluating project ':app'.
> 
> > Could not resolve all artifacts for configuration 'classpath'.
> > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.5.0).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.5.0/lint-gradle-api-26.5.0.jar
> > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.5.0).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.5.0/tracker-26.5.0.jar
> > Could not find sdklib.jar (com.android.tools:sdklib:26.5.0).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.jar
> 
> `

**Comment by iapicca** [comment]
Hi @JoDeveloper 
it is possible that the issue depends from your internet connection
are you behind a proxy a vpn
or connecting from China or Bangladesh?
If not could you please provide 
your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by JoDeveloper** [comment]
@iapicca 

`flutter doctor                                                             
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!`

**Comment by JoDeveloper** [comment]
`flutter doctor -v`

`FAILURE: Build failed with an exception.
[   +5 ms] * Where:
[        ] Build file '/home/joe/Desktop/flutter-projects/missing_person/android/app/build.gradle' line: 26
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > Could not resolve all artifacts for configuration 'classpath'.
[        ]    > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.5.0).
[        ]      Searched in the following locations:
[        ]          https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.5.0/lint-gradle-api-26.5.0.jar
[        ]    > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.5.0).
[        ]      Searched in the following locations:
[        ]          https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.5.0/tracker-26.5.0.jar
[        ]    > Could not find sdklib.jar (com.android.tools:sdklib:26.5.0).
[        ]      Searched in the following locations:
[        ]          https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.jar
`

**Comment by JoDeveloper** [comment]
I'm connecting from Sudan && using a vpn
