### ISSUE TITLE
Allowing for redirects in navigation and guards

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#56671]
Flutter should allow for router guards and redirects especially for web as others do offer it. As of now there is not a way to redirect in flutter.

**Comment by iapicca** [comment]
Hi @rlee1990 
do the answers to this stackoverflow [question](https://stackoverflow.com/questions/51027858/route-guards-in-flutter)
solve the issue?
Thank you

**Comment by rlee1990** [comment]
@iapicca  I will give it a shot and see if it has the desired outcome.

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
