### ISSUE TITLE
Path FLUTTER_STORAGE_BASE_URL 在flutter master上面工作不友好

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#56678]
## Path FLUTTER_STORAGE_BASE_URL 在flutter master上面工作不友好

Windows 10.
• Flutter version 1.18.0-14.0.pre.21 at D:\Android\flutter
    • Framework revision da66a45e87 (7 hours ago), 2020-05-08 00:29:01 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6) 
1. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle
这个文件203行：
String hostedRepository = System.env.FLUTTER_STORAGE_BASE_URL ?: DEFAULT_MAVEN_HOST
        String repository = useLocalEngine()
            ? project.property('local-engine-repo')
            : "https://$hostedRepository/download.flutter.io"

配置在Path中的变量“FLUTTER_STORAGE_BASE_URL”值是 https://xxxxxxx 
例如https://flutter.dev/community/china中的示例
但是在Gradle编译构建中却出现了 https://https/storage.flutter-io.cn/xxxxx 的资源获取地址
比如
![image](https://user-images.githubusercontent.com/38732113/81419019-27ee6e00-9180-11ea-9b48-6c89006d3d77.png)
是的，今天更新 https://github.com/flutter/flutter/commit/f6b47a5f35c38547f2881ebc5bea1e9f5046d295 之前是没有上述问题的。

2. 若配置了FLUTTER_STORAGE_BASE_URL ，在Flutter Module 项目下 flutter build aar 的也是不友好的，因为storageUrl 值为https://xxxxxx 的url.
如：
String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?: "storage.googleapis.com"
repositories {
       maven {
        url "https://$storageUrl/download.flutter.io"
    }
}
建议修改：
String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?: "https://storage.googleapis.com"
repositories {
    maven {
        url "$storageUrl/download.flutter.io"
    }
}

3. 若配置FLUTTER_STORAGE_BASE_URL值为storage.flutter-io.cn ，flutter upgrade 等命令将无法正常工作。

 

```
```

```
```

```
```

**Comment by xster** [comment]
啊，谢谢指出问题
