### ISSUE TITLE
The scroll inertia feels wrong on android.

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#5667]
1)Open the the Pesto example in the Flutter Gallery. Do a fast swipe up.
2)Open Google+ and do the same.

They feel different.

Pesto slows down faster w.r.t. the rest of the system.

**Comment by sethladd** [comment]
thanks! Can you include the OS and version that you used to test?

**Comment by B3rn475** [comment]
**Device:** One Plus One
**Device Model:** A0001
**Android Version:** 6.0.1
**Cyanogen OS version:** 13.1.2-ZNH2KAS3P0-bacon
**CyanogenMod API level:** Elderberry (5)
**Flutter Gallery Version:** flutter_gallery-bv0002-rc000

**Comment by eseidelGoogle** [comment]
We're in the process of fixing iOS via https://github.com/flutter/flutter/issues/5655, but this can serve as the bug for tracking fixing Android.  We have a path to fixing this to feel perfect, but haven't finished all the work yet.  Thanks for the report!

**Comment by eseidelGoogle** [comment]
We could call this a dupe of https://github.com/flutter/flutter/issues/4707.

**Comment by dragostis** [comment]
I've noticed this too, but I've always thought that the scrolling in Pesto was supposed to be custom. 😝

**Comment by B3rn475** [comment]
Fixed in version flutter_gallery-bv0006-rc000

**Comment by sethladd** [comment]
Great to hear! :)

cc @HansMuller
