### ISSUE TITLE
Getting  Unresolved reference: annotation and Unresolved reference: NonNull while running Flutter app

### ISSUE THREAD

**Issue by AnanthanAn** [flutter/flutter#56686]
## Getting  Unresolved reference: annotation and Unresolved reference: NonNull while running Flutter app

Getting following error while running App

**Actual results:** e: C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\app\src\main\kotlin\com\ananthan\shoplite1\MainActivity.kt: (3, 24): Unresolved reference: annotation
e: C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\app\src\main\kotlin\com\ananthan\shoplite1\MainActivity.kt: (9, 42): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1

<details>
  <summary>Logs</summary>

 +27 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +94 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +288 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.17.0
           1.17.0-3.4.pre
[  +17 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +86 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +192 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] executing: C:\Sdk\platform-tools\adb.exe devices -l
[  +93 ms] List of devices attached
           3d74ecaa0106           device product:pine model:Redmi_7A device:pine transport_id:1
[  +20 ms] C:\Sdk\platform-tools\adb.exe -s 3d74ecaa0106 shell getprop
[ +197 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1451 ms] Generating C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +172 ms] ro.hardware = qcom
[ +118 ms] Launching lib\main.dart on Redmi 7A in debug mode...
[  +17 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Ananthan\AppData\Local\Temp\flutter_tool.4ec76a83-9148-11ea-81b8-f8b46ab81ec8\app.dill --packages C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +81 ms] executing: C:\Sdk\platform-tools\adb.exe -s 3d74ecaa0106 shell -x logcat -v time -t 1
[ +327 ms] Exit code 0 from: C:\Sdk\platform-tools\adb.exe -s 3d74ecaa0106 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           05-08 21:53:57.001 D/        (  682): readbrightness,out2:0.
[  +14 ms] <- compile package:shoplite1/main.dart
[  +25 ms] executing: C:\Sdk\platform-tools\adb.exe version
[  +38 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Sdk\platform-tools\adb.exe
[ +137 ms] executing: C:\Sdk\platform-tools\adb.exe start-server
[+2152 ms] Building APK
[  +60 ms] [!] Your app isn't using AndroidX.
[   +2 ms]     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
[  +35 ms] Running Gradle task 'assembleDebug'...
[  +12 ms] gradle.properties already sets `android.enableR8`
[  +21 ms] Using gradle from C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\gradlew.bat.
[   +4 ms] C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +22 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +268 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +10 ms] executing: [C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android/] C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm -Ptarget=C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+21343 ms] > Task :app:compileFlutterBuildDebug
[   +4 ms] [  +54 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [ +164 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [   +3 ms] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[   +2 ms] [   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[   +1 ms] [ +522 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] [        ] 1.17.0
[   +2 ms]            1.17.0-3.4.pre
[   +2 ms] [  +30 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +3 ms] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[   +2 ms] [  +90 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [ +249 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] [        ] stable
[   +5 ms] [  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] [  +25 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] [  +62 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [ +200 ms] Initializing file store
[   +5 ms] [ +132 ms] Done initializing file store
[+4699 ms] [+4638 ms] Skipping target: kernel_snapshot
[+5199 ms] [+5250 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +600 ms] [ +575 ms] debug_android_application: Complete
[   +2 ms] [  +53 ms] Persisting file store
[  +97 ms] [  +81 ms] Done persisting file store
[   +2 ms] [   +9 ms] build succeeded.
[  +95 ms] [  +87 ms] "flutter assemble" took 11,285ms.
[ +606 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +3 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +88 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +98 ms] > Task :app:checkDebugManifest UP-TO-DATE
[  +98 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +301 ms] > Task :app:cleanMergeDebugAssets
[   +4 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +95 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +4 ms] > Task :app:generateDebugAssets UP-TO-DATE
[+1095 ms] > Task :app:mergeDebugAssets
[+1699 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +295 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +195 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +301 ms] > Task :app:processDebugResources UP-TO-DATE
[+7098 ms] > Task :app:compileDebugKotlin FAILED
[   +9 ms] e: C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\app\src\main\kotlin\com\ananthan\shoplite1\MainActivity.kt: (3, 24): Unresolved reference: annotation
[   +8 ms] e: C:\Users\Ananthan\AndroidStudioProjects\expense_tracker\shop_lite1\android\app\src\main\kotlin\com\ananthan\shoplite1\MainActivity.kt: (9, 42): Unresolved reference: NonNull
[   +4 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +3 ms] Execution failed for task ':app:compileDebugKotlin'.
[   +3 ms] > Compilation error. See log for more details
[   +7 ms] * Try:
[   +3 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +5 ms] BUILD FAILED in 43s
[   +3 ms] 16 actionable tasks: 5 executed, 11 up-to-date
[ +860 ms] Running Gradle task 'assembleDebug'... (completed in 45.4s)
[  +16 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +8 ms] "flutter run" took 50,648ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```
```

```
```

[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\Ananthan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • Redmi 7A • 3d74ecaa0106 • android-arm • Android 9 (API 28)

• No issues found!

```
```

</details>

**Comment by jeffque** [comment]
As no code is provided, maybe you forget to import it?

Like the example at https://developer.android.com/studio/write/annotations#adding-nullness , it has a `import android.support.annotation.NonNull` statement

**Comment by AnanthanAn** [comment]
sorry, please find the code below.
`package com.ananthan.shoplite1

import android.support.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}`

**Comment by jeffque** [comment]
@AnanthanAn , reading the docs https://developer.android.com/studio/write/annotations I've found that you should add a dependency to have access to the classes inside `android.support.annotation`.

Inside your  `dependencies` in your `build.gradle`, you should add `com.android.support:support-annotations:28.0.0`, something like this:

```gradle
dependencies {
    implementation 'com.android.support:support-annotations:28.0.0'
}
```

Also, when reading the [JavaDoc for `android.support.annotation.NonNull`](https://developer.android.com/reference/android/support/annotation/NonNull), it says that AndroidX is preffered. It gives you a [migration guide](https://developer.android.com/jetpack/androidx/migrate). The `@NonNull` from AndroidX is `androidx.annotation.NonNull`.

Also, I think that modern Flutter template for `build.gradle` adds support for AndroidX by default. And I have no idea how to add it, I just got a project wth AndroidX configured and everything works for me.

**Comment by AnanthanAn** [comment]
@jeffque  Issue Resolved after ate it.dding Dependency. Thanks a lot for your help. Appreciate it.

**Comment by jeffque** [comment]
You're welcome

**Comment by yasasmi** [comment]
![Screenshot (1202)](https://user-images.githubusercontent.com/53207666/112730978-9552eb00-8f5a-11eb-8167-9f702e315b05.png)
Why I am getting this error and how can I solve this? any suggestions will be really great help. Thank you!
