### ISSUE TITLE
http response bodies are sometimes truncated

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5668]
Run the stocks example 10 times on the iOS simulator and you'll likely get a failure along the lines of:

```
ERROR:../../lib/tonic/logging/dart_error.
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
FormatException: Unterminated string (at line 466, character 11)
    "$146.
          ^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:477)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:501)
#4      StockDataFetcher._fetchNextChunk.<anonymous closure> (/Users/drewwarren/flutter/examples/stocks/lib/stock_data.dart:82:38)
#5      _RootZone.runUnary (dart:async/zone.dart:1404)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:667)
```

I get the failure about 40% of the time. I have only tested this on the iOS simulator.

```
✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision e0f6c0db84 (26 hours ago), 2016-08-29 12:17:34
    • Engine revision c4022b61fa
    • Tools Dart version 1.19.0-dev.5.0

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37
```

**Comment by sethladd** [comment]
Curious where Stocks demo gets its data from?

**Comment by drewwarren** [comment]
String _urlToFetch(int chunk) {
  return 'https://domokit.github.io/examples/stocks/data/stock_data_$chunk.json';
}

This is not isolated to stocks. I am seeing the same issue with http requests to my backend server.

**Comment by sethladd** [comment]
@Hixie I think you use stocks the most, are you able to repro this?

**Comment by eseidelGoogle** [comment]
Our network layers are also platform specific.  This is iOS:
https://github.com/flutter/engine/tree/master/services/ns_net
cc @chinmaygarde

**Comment by sethladd** [comment]
Ah, thanks. So, we're only seeing this behavior on iOS?

**Comment by chinmaygarde** [comment]
I think this is iOS only. It’s because we didn’t have a way to asynchronously flush data down the Mojo pipe in `url_loader_impl.mm`. We needed something like `data_pipe_flusher`. I wrote one and it seems to work fine. However, CoreFoundation seems to be collecting delegates on its own threads when there are network errors. This, along with restrictions in mojo w.r.t the tread on which its proxies need to be collected (along with the fact that it is extremely hard to reproduce the problem) is slowing me down.

**Comment by chinmaygarde** [comment]
A [number of concerns were raised](https://github.com/flutter/engine/pull/3008#discussion_r78233924) in the approach for [fixing](https://github.com/flutter/engine/pull/3008) this issue. We are deciding to settle on a single network interface. Since `dart:io` is now available on all platforms, we want to get rid of the Mojo network interface backing `package:flutter/http.dart`.

@drewwarren @sethladd: How difficult would the migration away from `flutter/http.dart` to `dart:io` be?

**Comment by drewwarren** [comment]
Low effort on our end to migrate to dart:io. Reading your comment it sounds like that is something we could currently do?

**Comment by sethladd** [comment]
> How difficult would the migration away from flutter/http.dart to dart:io be?

As @drewwarren mentions, should be fairly straight forward.

**Comment by chinmaygarde** [comment]
Doing the migration is something we would really like to get to as soon as possible. Right now, there are multiple platform specific networking implementations. Each with different runtime characteristics (thread per connection, buffering, etc.). All this when `dart:io` is a fully capable of providing the same functionality, is better tested, and, provides uniformity across platforms.

I want to do everything I can to make this transition as painless as possible. It will only get harder to deprecate as time moves on. I was thinking maybe we would need to have a `dart:io` backed `flutter/http.dart` to ease the transition but if the effort required to migrate is low, we can just pull the bandaid off quickly by removing `flutter/http.dart` in one roll. Either way, let me know.

**Comment by drewwarren** [comment]
I have verified using http with dart:io HttpClient works (at least on the iOS simulator)

The interface is a little more low level than desired. Creating a request with headers is pretty verbose. Getting the response body as a string is very verbose. There is additional overhead of making sure you drain the response stream properly.

package:http appears to have a more user friendly api, however it ends up using mirrors so cannot be used with flutter. Since flutter has a relationship with the dart team, the maintainers of package:http, would you mind seeing if they could provide a version without mirrors?

**Comment by chinmaygarde** [comment]
We'll investigate what need to be done to make `package:http` usable https://github.com/flutter/flutter/issues/5831.

**Comment by chinmaygarde** [comment]
I got rid of the use of mirrors from `package:http`. Its part of a forked package now https://github.com/chinmaygarde/flutter_http. I am planning on replacing the current `flutter/http.dart` with this version. So @drewwarren would probably not need to do anything.
