### ISSUE TITLE
Since updateing to androidx haveing too many errors/crashes

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#56692]
Hi since updating to androidx i have too many crashes.
My app version on google play has 100% crash-free and now only 70%.

a lot of error from different libraries, all of them have a common error 
"No implementation found for method"

i think there is problem with the registrar. 
Mainactivty used to have in on creating a line to register modules but now we have deleted it and letting flutter activity to handle it but something changed.

Don't ease with this report and throw the responsibility on other libraries, im pretty sure its something wrong here.

Thanks

Doctor all good. tried to delete, clear and all.  v1.12.13+hotfix.9

**Comment by iapicca** [comment]
Hi @dvird
could you please 
double check your project implements correctly [androidX migration]( https://flutter.dev/docs/development/androidx-migration)
and run `flutter upgrade --force`;
if the issue persists please provide 
your your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
