### ISSUE TITLE
Broken builds after flutter upgrade to 1.17 stable or dev

### ISSUE THREAD

**Issue by nicolasvahidzein** [flutter/flutter#56696]
Hello, i cannot build for ios now. It was fine before

/Users/nicolaszein/Desktop/Projects/Zandu/003/zandu/ios/Flutter/Debug.xcconfig Debug.xcconfig line 2: Unable to find included file "Generated.xcconfig"

I get 4 of these similar errors and i am stuck now.

How can i fix these errors please?

**Comment by YazeedAlKhalaf** [comment]
Hello @nicolasvahidzein 

The file it is looking for is a generated file. Try these and tell me what happens:

1. Run this command `flutter clean` in the project's directory then try building again.
2. Recreate the flutter project using this command `flutter create .` from inside the project's directory. If you have customized the organization URL, then run this command `flutter create --org ORG_URL .` instead with replacing the `ORG_URL` with the one used in the project

**Comment by pulstar** [comment]
Same problem here... After upgraded Flutter, I have a lot of errors. I have no idea how to solve this. Everything was working fine before the upgrade.

Compiler message:
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.6.1/lib/src/chips_input.dart:62:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/Program%20Files/flutter/packages/flutter/lib/src/services/text_input.dart:757:24: Context: 'TextInputClient.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
packs/insignia_layout/lib/src/simple_form.dart:1733:18: Error: The method 'BlockPicker' isn't defined for the class '_ColorSelectorState'.
 - '_ColorSelectorState' is from 'package:insignia_layout/src/simple_form.dart' ('packs/insignia_layout/lib/src/simple_form.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BlockPicker'.
      selector = BlockPicker(
                 ^^^^^^^^^^^
packs/insignia_layout/lib/src/simple_form.dart:1745:18: Error: The method 'MaterialPicker' isn't defined for the class '_ColorSelectorState'.
 - '_ColorSelectorState' is from 'package:insignia_layout/src/simple_form.dart' ('packs/insignia_layout/lib/src/simple_form.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MaterialPicker'.
      selector = MaterialPicker(
                 ^^^^^^^^^^^^^^

Compiler message:
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.6.1/lib/src/chips_input.dart:62:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/Program%20Files/flutter/packages/flutter/lib/src/services/text_input.dart:757:24: Context: 'TextInputClient.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
packs/insignia_layout/lib/src/simple_form.dart:1733:18: Error: The method 'BlockPicker' isn't defined for the class '_ColorSelectorState'.
 - '_ColorSelectorState' is from 'package:insignia_layout/src/simple_form.dart' ('packs/insignia_layout/lib/src/simple_form.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BlockPicker'.
      selector = BlockPicker(
                 ^^^^^^^^^^^
packs/insignia_layout/lib/src/simple_form.dart:1745:18: Error: The method 'MaterialPicker' isn't defined for the class '_ColorSelectorState'.
 - '_ColorSelectorState' is from 'package:insignia_layout/src/simple_form.dart' ('packs/insignia_layout/lib/src/simple_form.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MaterialPicker'.
      selector = MaterialPicker(
                 ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Program Files\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Program Files\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by nicolasvahidzein** [comment]
ok i will recreate the project and migrate over, this is a pain i have to say.

**Comment by timsneath** [comment]
@pulstar Your issue is unrelated to the original one. See https://flutter.dev/docs/release/breaking-changes/text-input-client-current-value for details of this breaking change in 1.17.

**Comment by nicolasvahidzein** [comment]
I had to recreate the project from SCRATCH, spent 12 hours on this. Insane.

**Comment by nicolasvahidzein** [comment]
Also for those using flutter use the override method since there is a conflict with path version 1.7.0

see: [https://github.com/hivedb/hive/issues/285](url)

**Comment by slabo** [comment]
> Hello @nicolasvahidzein
> 
> The file it is looking for is a generated file. Try these and tell me what happens:
> 
>     1. Run this command `flutter clean` in the project's directory then try building again.
> 
>     2. Recreate the flutter project using this command `flutter create .` from inside the project's directory. If you have customized the organization URL, then run this command `flutter create --org ORG_URL .` instead with replacing the `ORG_URL` with the one used in the project

thanks. this works for me. 
**flutter clean
flutter create --org com.someorg .**

**Comment by YazeedAlKhalaf** [comment]
@slabo That's Great To Hear

**Comment by nicolasvahidzein** [comment]
Thank you so much. I had wasted so much time with this i recreated the ios folder from flutter.

**Comment by erolasan** [comment]
**flutter clean
flutter build ios**
This worked for me, no need to recreate project.
