### ISSUE TITLE
Non-rectangular clips are slow on Android.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5669]
Oval clips and rounded rectangle clips are much faster on iOS than Android. Systrace currently shows stalls in swapping buffers which seems to mean that the GPU is too busy to do the swaps.

![d qq42efaqaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/4136413/18108879/554c6412-6ec3-11e6-909d-42d8513bbab6.png)

Capturing an SKP and rendering with the Skia tools takes around 4ms while our app is usually 30+ms.

@chinmaygarde

**Comment by eseidelGoogle** [comment]
Do we have an SKP to share with Skia?  @chinmaygarde and I brought this bug up with Skia at our meeting today.

**Comment by HansMuller** [comment]
> Capturing an SKP and rendering with the Skia tools takes around 4ms while our app is usually 30+ms.

I think Dragos felt that this problem was due to something on the Flutter side.

**Comment by eseidelGoogle** [comment]
Spoke with Skia and they suggested that this should be fast.  One recommendation was to make sure the clip was anti-aliased, since that path has been more optimized than non-antialiased clips.  If we have a reduction or can produce an SKP that is not fast then we can file a Skia bug.

**Comment by abarth** [comment]
Looks like we were not using anti-alias.  Will fix.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/6298

**Comment by abarth** [comment]
https://github.com/flutter/engine/pull/3124 for the engine as well

**Comment by eseidelGoogle** [comment]
I'm going to presume this is resolved based on the work above.
