### ISSUE TITLE
Floating action button should be positionable in the upper leftish

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#567]
I have widget (Icon + InkWell) that I position halfway outside of its parent using `Transform`. Widget is displayed correctly but the part of it that is outside of the parent does not receive onTap events. 

@abarth

**Comment by abarth** [comment]
Yes, this is a deep issue that we haven't fully sorted through.  I'd be interested in learning more about your use case here to help sort out what we should do.  Can I come by and look at your app tomorrow?

@Hixie

**Comment by aghassemi** [comment]
Sure, I can show you tomorrow. I do have a work-around for it as well. Actual FAB if set as the MaterialPage.FloatingActionButton, well transformed, still stays clickable ( Probably because its parent is the full view port ). Anyway, I can calculate, based on view port height, how much I need to move the default page FAB to be where I need it to be.

**Comment by abarth** [comment]
Are you trying to position the FAB similar to what's in this image?

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7S2NiZlNhcDUxSTA/patterns_actions_fab_content2.png

If so, we just need to teach the FAB how to be positioned there.  The FAB needs to float above the toolbar and the body in order for it to be at the proper elevation anyway.

**Comment by aghassemi** [comment]
Sort of, in my case I have an image instead if the toolbar on top.

**Comment by abarth** [comment]
@HansMuller was working on this, but I think he's taking a break to make tabs more awesome.

**Comment by sethladd** [comment]
Do we still plan to do this?

@HansMuller @Hixie

**Comment by HansMuller** [comment]
I think we should still do it although AFAIK we haven't had an app developer request it.

**Comment by Hixie** [comment]
We have no current customers requesting this. We will close it until we have demand. This should be relatively easy to do once we decide to do it.

**Comment by jerzykiler** [comment]
If a simple developer like me kindly requests this feature does that count as a "customer request" ? 
:-)

**Comment by mars-g** [comment]
I second this request. For my purpose, it feels more intuitive to have at the top right of the screen than the bottom right.

**Comment by HansMuller** [comment]
This can be done with the Scaffold's floationActionButtonLocation property and a custom FloatingActionButtonLocation class.

You should take a look at how the default locations are defined in packages/flutter/lib/src/material/floating_action_button_location.dart

**Comment by Hixie** [comment]
@jerzykiler It does. Turns out we've implemented this since then though, as @HansMuller says. :-)

**Comment by Hixie** [comment]
See https://docs.flutter.io/flutter/material/Scaffold/floatingActionButtonLocation.html
