### ISSUE TITLE
Missing flutter.yaml file leads to obscure error with flutter run --hot

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#5670]
The app below is just a Material version of examples/hello_world/lib/main.dart.

Running the app as follows leads to an obscure message about `dart:ui MojoServices.takeRootBundle() returned an invalid handle`. 

```
(cd examples/hello_world; rm -rf build; flutter run --hot --pid-file=/tmp/flutter.run.pid)
Building APK in debug mode (android-arm)...
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.5MB).
Launching loader on Nexus 5...
--------- beginning of main
Observatory listening on http://127.0.0.1:57220
Diagnostic server listening on http://127.0.0.1:50043
Updating assets...
Syncing files to device...
Scanning project files...
Scanning package files...
Scanning asset files...
Scanning for deleted files...
No files to remove.
Updating files...
Synced 4.3MB.
Connected to view '_flutterView/0xb49d1d00'.
Running lib/main.dart on Nexus 5...
I/flutter : [INFO:engine.cc(194)] Could not configure asset bundle at path: /data/data/io.flutter.examples.HelloWorld/cache/hello_worlddycsvl/build/flx
I/flutter : ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter : The following message was thrown while initialising the root bundle:
I/flutter : dart:ui MojoServices.takeRootBundle() returned an invalid handle.
I/flutter : This might happen if the Dart VM was restarted without restarting the underlying Flutter engine, or
I/flutter : if the Flutter framework's rootBundle object was first accessed after some other code called
I/flutter : takeRootBundle. The root bundle handle can only be obtained once in the lifetime of the Flutter
I/flutter : engine. Mojo handles cannot be shared.
I/flutter : The rootBundle object will be initialised with a NetworkAssetBundle instead of a MojoAssetBundle.
I/flutter : This may cause subsequent network errors.
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
Application running.
...
```

Here's the app. There is no flutter.yaml file.

```
import 'package:flutter/material.dart';

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Hello World')),
      body: new Center(child: new Text('Hello World'))
    );
  }
}

void main() {
  runApp(new MaterialApp(
    title: 'Hello World',
    home: new Demo()
  ));
}
```

**Comment by danrubel** [comment]
@eseidelGoogle Under what circumstances is a flutter.yaml file needed?

**Comment by eseidelGoogle** [comment]
I believe flutter.yaml is always expected for a flutter app.  Seems like `flutter` can just fail if it's missing?

**Comment by Hixie** [comment]
We should imply a default one if it's missing, IMHO.
I think it should be possible to run "flutter run" on a single dart file in
an otherwise empty directory and get something running on the device.

**Comment by eseidelGoogle** [comment]
@Hixie that feature was certainly nice earlier during development, but seems far out of line from how our customers are likely to use our product.  That said, I really rely on you and @abarth here, and if you feel strongly you need that feature we can make it work.  I suspect there would be a good amount of work to keep that working, especially as we move more towards hello_services everywhere and so I'd rather not do that work if you two don't feel it's essential to the product or your productivity.

**Comment by abarth** [comment]
IMHO, we should treat a missing flutter.yaml file the same as an empty flutter.yaml file and soldier on.  It just means `uses-material-design` will default to false and you won't get any assets in your bundle, etc.

Being able to `flutter run` a standalone Dart file is going to be trickier.  We could handle that by running `flutter create` in a temporary directory to make a skeleton Xcode project and such, but it's probably not going to be a good user experience...  I guess we could make `flutter run` inflate a `flutter create` project around the standalone dart file...

**Comment by Hixie** [comment]
Imho any missing file should just be implied from the template (without
actually creating it).

**Comment by Hixie** [comment]
(That follows from our tenet that the simplest hello world should be as close to the empty string as possible.)

**Comment by abarth** [comment]
> Imho any missing file should just be implied from the template (without actually creating it).

Yeah, the tricky part is we need to shell out to Xcode (and similar tools for Android) to actually make apps and those tools don't follow this philosophy.

**Comment by sethladd** [comment]
> IMHO, we should treat a missing flutter.yaml file the same as an empty flutter.yaml file and soldier on. 

Agreed. Convention over configuration. :)

**Comment by eseidelGoogle** [comment]
flutter.yaml is no longer a thing.
