### ISSUE TITLE
Incrementing 'y' in dev releases should be automated

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#56715]
Currently, incrementing the 'y' for dev releases is based on the beta roller informing the dev roller that they should increment 'y', and then the dev roller has to provide a command-line flag to the `roll_dev.dart` script.

We should have a system more reliable than "message the dev roller" to ensure the 'y' is incremented at correct time.

One possible solution would be for the script to detect when the current x.y family has been promoted to beta, and then suggest 'y' be incremented.

**Comment by pcsosinski** [comment]
forgive me

if beta:
BRANCH=flutter-1.19-candidate.4
xy=`echo $BRANCH | cut -d- -f2`
rev=`echo $BRANCH | cut -d. -f3`
prevm=`git tag -l "$xy.0-$rev*" | cut -d. -f4 | sort -nr | head -n1`
VERSION=$xy.0-$rev.$((prevm + 1)).pre
echo "set version to ${VERSION}"

**Comment by kf6gpe** [comment]
I'm assigning this to the infra team, as it feels infra-y and should have some team thinking about it. Who really owns the roll scripts?
