### ISSUE TITLE
RenderTransform doesn't honour the paint offset

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5671]
@apwilson noticed that if you have a Transform widget inside a Padding widget and the transform is just a scale, the horizontal alignment is off. Looks like _effectiveTransform isn't taking the offset into account when applying the alignment.

**Comment by eseidelGoogle** [comment]
Confirmed with @apwilson this is not affecting him currently, removing pink.

**Comment by Hixie** [comment]
I can no longer reproduce this.
