### ISSUE TITLE
Unable to implement pull to refresh action with the webview_flutter plugin

### ISSUE THREAD

**Issue by RedCuckoo** [flutter/flutter#56724]
I can't find any way to implement a pull to refresh action using official WebView plugin. 

What I have tried so far is a lot of stuff, I'll show where I ended up with.
I used RefreshIndicator() widget from the dart:material and SmartRefresher() from [pull_to_refresh package](https://pub.dev/packages/pull_to_refresh).

In the documentation of the pull_to_refresh says, that it works only for Scrollable Widgets. So does the RefreshIndicator (it works for vertical scroll). As the WebView isn't one of them, it's logical that we have to wrap it with such widget.

So I ended up with this structure. It uses streams, but it doesn't work with the setState() either.

<pre><code>
//MyWebView.dart
class MyWebView extends StatefulWidget {
  Completer<WebViewController> controller;
  StreamController<double> streamController;

  MyWebView(this.controller, this.streamController);

  @override
  _MyWebViewState createState() => _MyWebViewState();
}

class _MyWebViewState extends State<MyWebView> {
  @override
  Widget build(BuildContext context) {
    return WebView(
        initialUrl: "https://flutter.dev/",
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (contr) {
          widget.controller.complete(contr);
        },
        onPageFinished: (some) async {
          double height;
          widget.controller.future.then((value) {
            value
                .evaluateJavascript("document.documentElement.scrollHeight;")
                .then((String valueHeight) {
              height = double.parse(valueHeight);
              widget.streamController.add(height);
            });
          });
        });
  }
}

//main.dart
class _WebViewExampleState extends State<WebViewExample> {
  Completer<WebViewController> controller = Completer<WebViewController>();
  StreamController<double> streamController = StreamController<double>();
  double webViewHeight = 100;

  @override
  void initState() {
    super.initState();
    streamController.stream.listen((double value) {
      print(value);
      setState(() {
        webViewHeight = value;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Flutter WebView example'),
        ),
        body: RefreshIndicator(
          onRefresh: () => controller.future.then((webViewController) {
            webViewController.reload();
          }),
          child: ListView.builder(
            itemCount: 1,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                  title: Container(
                height: webViewHeight,
                child: MyWebView(controller, streamController),
              ));
            },
          ),
        ));
  }
}
</code></pre>

I gave up on this, because this piece **crashes my phone**(!) not only the app, my phone reboots. So consider this if you want to test. There is console output listed below. As I understand, [this concept](https://gist.github.com/PonnamKarthik/877a90917a576ecff613d5169680d02c) builds too big virtual display and can't show it. 

It is related to #35394, but I don't think it's a duplicated, because the minute you resolve for enabling scrolling with the snippet provided [here](https://stackoverflow.com/a/57150906/13442461). Then you are back to being unable to pull to refresh. _Its one or the other_.

I will just use a regular button for refresh as for now in my app. But I really want to resolve it and want to get some help and I will be open for further questions.

<details><summary>console output starting from big virtual display message</summary>
<pre>W/PlatformViewsController(13023): Creating a virtual display of size: [992, 21601] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2030].
W/ContentCatcher(13023): Failed to notify a WebView
E/WindowManager(13023): BadTokenException or InvalidDisplayException, clean up.
E/MethodChannel#flutter/platform_views(13023): Failed to handle method call
E/MethodChannel#flutter/platform_views(13023): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views(13023): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views(13023): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:80)
E/MethodChannel#flutter/platform_views(13023): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:7429)
E/MethodChannel#flutter/platform_views(13023): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:899)
E/MethodChannel#flutter/platform_views(13023): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
E/MethodChannel#flutter/platform_views(13023): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
E/MethodChannel#flutter/platform_views(13023): 	at android.app.Dialog.show(Dialog.java:329)
E/MethodChannel#flutter/platform_views(13023): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:161)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:191)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:120)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:65)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(13023): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#flutter/platform_views(13023): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(13023): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(13023): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter/platform_views(13023): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter/platform_views(13023): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(13023): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter/platform_views(13023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (13023): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, InputChannel is not initialized., null)
E/flutter (13023): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13023): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (13023): <asynchronous suspension>
E/flutter (13023): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (13023): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:552:41)
E/flutter (13023): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter (13023): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
E/flutter (13023): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter (13023): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
E/flutter (13023): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #13     _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:1371:9)
E/flutter (13023): #14     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1424:28)
E/flutter (13023): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
E/flutter (13023): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (13023): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #32     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:193:27)
E/flutter (13023): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #34     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:135:11)
E/flutter (13023): #35     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:375:11)
E/flutter (13023): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (13023): #37     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)
E/flutter (13023): #38     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1444:12)
E/flutter (13023): #39     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1353:20)
E/flutter (13023): #40     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
E/flutter (13023): #41     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
E/flutter (13023): #42     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
E/flutter (13023): #43     WidgetsBinding.drawFrame (package:f
W/Sensors (13023): sensorservice died [0x7c6463c180]
</pre></details>

<details><summary>flutter doctor -v</summary>
[√] Flutter (Channel master, 1.18.0-14.0.pre.22, on Microsoft Windows [Version 10.0.18363.778], locale uk-UA)
    • Flutter version 1.18.0-14.0.pre.22 at C:\flutter
    • Framework revision 3519bec6c4 (10 hours ago), 2020-05-08 00:34:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\momot\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\momot\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.5731

[!] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 5 • 43150aa4 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
</details>

**Comment by iapicca** [comment]
Hi @RedCuckoo 
[pull_to_refresh](https://pub.dev/packages/pull_to_refresh) is a 3rd party plugin
you may want to consider opening an issue in the dedicated [github](https://github.com/peng8350/flutter_pulltorefresh/issues);

given your statement

> In the documentation of the pull_to_refresh says, that it works only for Scrollable Widgets. So does the RefreshIndicator (it works for vertical scroll). As the WebView isn't one of them, it's logical that we have to wrap it with such widget.

is quite possible that this issue is in fact a duplicated of https://github.com/flutter/flutter/issues/35394.

Could you please provide a reproducible code sample that does not involve 3rd party plugins
Thank you

**Comment by RedCuckoo** [comment]
Hello, @iapicca 
Thank you for your time! I thought it through after your reply. In fact it is actually a duplicate of #35394

**Comment by bharathiselvan** [comment]
Hello.. Still I am unable to implement pull to refresh for WebView with  webview_flutter: ^1.0.7... I am trying to use WebView inside RefreshIndicator..

**Comment by iapicca** [comment]
@bharathiselvan 
this issue was closed more than 6 months ago and is not actively worked on
please file a new issue providing you `flutter doctor -v` and a minimal reproducible code sample
