### ISSUE TITLE
Performance regressions on new Flutter gallery

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#56722]
<img width="1666" alt="Screen Shot 2020-05-08 at 2 22 40 PM" src="https://user-images.githubusercontent.com/22987568/81451937-76791980-913a-11ea-8f0a-fe3a9c128b57.png">

The regressions started from the engine roll https://github.com/flutter/flutter/commit/7eff0a8725ef0a39bef9227304945821171ce01e

**Comment by liyuqian** [comment]
@a-siva : can you please help bisect and see which engine commit caused this regression?

**Comment by jason-simmons** [comment]
The regressions affect the rasterizer and are associated with the integral offset snapping change: https://github.com/flutter/engine/commit/28d99854a6469fb7890b64f23500fad5f3b2695c

**Comment by liyuqian** [comment]
Thank you very much @jason-simmons! I've uploaded https://github.com/flutter/engine/pull/18255 which I verified the fix locally.
