### ISSUE TITLE
[cocoon] Optimize query to retrieve timeseriesValue in /api/public/get_benchmarks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#56731]
To retrieve `timeseriesValue` in `/api/public/get_benchmarks`, current logic returns data since a specific timestamp for a branch. 

In that timestamp, `one hour` timeframe (https://github.com/flutter/cocoon/pull/753#discussion_r418626676) is added to guarantee all `timeseriesValues` belonging to `commits` are picked up.

However an optimization of this query is needed to avoid potential race condition (https://github.com/flutter/cocoon/pull/753#discussion_r420482089)

**Comment by godofredoc** [comment]
Obsolete: perfomance dashboard has been deprecated.
