### ISSUE TITLE
Keyboard overflows text fields

### ISSUE THREAD

**Issue by Skyost** [flutter/flutter#56734]
## Steps to Reproduce

1. Place a `TextField` anywhere in the widget tree.
2. Tap on it.

**Expected results:** 

The widget should resize (or add bottom padding) in order to make room for the keyboard.

**Actual results:** 

I can't see the text field because it's hidden by the keyboard. See :

<img src="https://user-images.githubusercontent.com/3882599/81458104-136a9f80-9199-11ea-8c4d-75e4cbbe50d8.gif" height="400">

<details>
<summary>Code</summary>

```dart
MaterialApp(
  title: 'App',
  home: Scaffold(
    body: SingleChildScrollView(
      child: Container(
        decoration: BoxDecoration(
          border: Border(
            top: BorderSide(color: Colors.red),
            bottom: BorderSide(color: Colors.red),
          ),
        ),
        margin: EdgeInsets.only(top: 500, bottom: 100),
        padding: EdgeInsets.only(top: 100, bottom: 100),
        child: TextField(),
      ),
    ),
    // resizetoavoidbottominset: false // Same with or without this one.
  ),
);

```
</details>

<details>
  <summary>Logs</summary>

```
No particular log.
```

```
> flutter analyze
Analyzing alcoolum...
No issues found! (ran in 12.3s)
```

```
> flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [version 10.0.17763.1158], locale fr-FR)
    • Flutter version 1.17.0 at D:\Hugo\Programmes\Flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at D:\Hugo\Programmes\Android\SDK
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = D:\Hugo\Programmes\Android\SDK
    • Java binary at: D:\Hugo\Programmes\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Hugo\Programmes\Android\Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by imeDevelopers** [comment]
@Skyost 
i think you should put the Scaffold() inside the SingleChildScrollView() ..

try it and tell me ..

**Comment by Skyost** [comment]
@imeDevelopers No, Scaffold should be the top MaterialApp widget.

**Comment by imeDevelopers** [comment]
@Skyos

Try to use stack() inside listview() instead of single child() ..

**Comment by Skyost** [comment]
@imeDevelopers Already done before. I was using the single child scroll view thing has it as been advised on SO for example.

**Comment by imeDevelopers** [comment]
I have solution for you , but dont know if you will accept ..

**Comment by imeDevelopers** [comment]
@Skyost
Put single child inside container and give the container a height ..

Make it equal to the scaffold height + 100 to give you the ability to scroll more than the singkechildscrollview accept ..

I think the code will be like:

`Mediaquery.of(context).scaffold.size.height+100(or 200)`

Put this code in the height paramter of the container ..

**Comment by Skyost** [comment]
@imeDevelopers But is this the intended behavior ? I don't think so personally.

**Comment by nemoryoliver** [comment]
You're not the only one. I believe the new flutter version has changed some behavior.. now my apps don't work properly. I'm currently trying to downgrade to an earlier version to confirm.

**Comment by Skyost** [comment]
@nemoryoliver Glad to see I'm not the only one 😄

Btw, I ran some tests yersteday (if anyone is interested) :
* I've tested on both Android 10 and Android Marshmallow for the same result.
* If I try to implement `WidgetsBindingObserver` in order to listen to `didChangeMetrics`, the method never gets called.

**Comment by nemoryoliver** [comment]
> @nemoryoliver Glad to see I'm not the only one 😄
> 
> Btw, I ran some tests yersteday (if anyone is interested) :
> 
> * I've tested on both Android 10 and Android Marshmallow for the same result.
> * If I try to implement `WidgetsBindingObserver` in order to listen to `didChangeMetrics`, the method never gets called.

have you tried again on previous flutter releases?

**Comment by Skyost** [comment]
@nemoryoliver I haven't downgraded my flutter version to test this bug but I have an app that worked well using flutter 1.12. With the only change of upgrading flutter (+ some minor changes like using the new material styles for text, ...), this bug is occurring.

**Comment by nemoryoliver** [comment]
Similar issue here https://github.com/flutter/flutter/issues/9471

**Comment by nemoryoliver** [comment]
> @nemoryoliver I haven't downgraded my flutter version to test this bug but I have an app that worked well using flutter 1.12. With the only change of upgrading flutter (+ some minor changes like using the new material styles for text, ...), this bug is occurring.

I am currently trying 1.12 hotfix.9 then I'll update here

**Comment by Skyost** [comment]
> my temporary solution: https://pub.dev/packages/keyboard_utils

That's really cool but eh, depending on a third party package just to fix a bug from the framework bother me a little bit personally.

**Comment by nemoryoliver** [comment]
> > my temporary solution: https://pub.dev/packages/keyboard_utils
> 
> That's seems really cool but eh, depending on a third party package just to fix a bug from the framework bothers me a little bit personally. And, as I see, it seems to be a bit buggy on iOS :
> 
> [IsaiasSantana/keyboard_utils#18](https://github.com/IsaiasSantana/keyboard_utils/issues/18)
> 
> Edit : Nevermind, it seems to be only a Swift version problem.

yeah, this plugin doesn't work on iOS. what's your fix?

**Comment by TahaTesser** [comment]
Hi @Skyost 
Not able to reproduce keyboard issue on latest `stable`channel

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        resizeToAvoidBottomInset: true,
        body: SingleChildScrollView(
          child: Container(
            decoration: BoxDecoration(
              border: Border(
                top: BorderSide(color: Colors.red),
                bottom: BorderSide(color: Colors.red),
              ),
            ),
            margin: EdgeInsets.only(top: 500, bottom: 100),
            padding: EdgeInsets.only(top: 100, bottom: 100),
            child: TextField(),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

![textfield](https://user-images.githubusercontent.com/48603081/81534899-74a39600-9386-11ea-824b-5034f266956d.gif)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • SM M305F                  • 32003c30dc19668f • android-arm64 • Android 10
      (API 29)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10
      (API 29) (emulator)

• No issues found!
``` 

</details> 

Please try this code sample
Thank you

**Comment by Skyost** [comment]
@TahaTesser In a first time when I tried your code it didn't work. So I was sure it was my fault and I found what caused this ; I was using :

`<style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar.Fullscreen">`

In order to disable system overlays. Now if I'm using :

`<style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">`

Then it works perfectly. Thanks !

**Comment by nemoryoliver** [comment]
> @TahaTesser In a first time when I tried your code it didn't work. So I was sure it was my fault and I found what caused this ; I was using :
> 
> `<style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar.Fullscreen">`
> 
> In order to disable system overlays. Now if I'm using :
> 
> `<style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">`
> 
> Then it works perfectly. Thanks !

What a great find. 👍 This was my culprit **<item name="android:windowFullscreen">true</item>**

This was added when I used the flutter_native_splash package to generate my splash screen.. Thank you so much!!!!

**Comment by pdivita** [comment]
Similar problem to me. Had to edit android/app/src/main/res/values/styles.xml and setting android:windowFullscreen from true to false
