### ISSUE TITLE
flutter tool provide hint when/how to install iOS simulator

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5674]
## Steps to Reproduce

* Clean install (no iOS simulator)
* `flutter create test-ios`
* `flutter run`

At this point it responds with `No connected devices.` which is correct but unhelpful. I would like it to hint that I could install the iOS simulator and point to docs explaining how to do so. Maybe `flutter doctor` should indicate that it is not installed / configured as well.

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/danrubel/work/git/flutter/flutter
    • Framework revision 83bf5d10c0 (21 hours ago), 2016-08-30 14:11:54
    • Engine revision c4022b61fa
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/danrubel/Library/Android/sdk
    • Platform android-23, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35
```

**Comment by eseidelGoogle** [comment]
iOS Simulator comes as part of XCode.  `open -a Simulator.app` should open it.  It also has a headless mode accessible via `symctl` which itself is sometimes not in the path so `xcrun symctl` is necessary to access it.  FYI @chinmaygarde
