### ISSUE TITLE
[Add2App iOS] xcode_backend.sh script doesn't strip bitcode for archive build, even if the project has bitcode disabled

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#56750]
In `xcode_backend.sh`, the function `EmbedFlutterFrameworks() {` has the following code:

```
if [[ "$ACTION" != "install" ]]; then
    # Strip bitcode from the destination unless archiving.
    RunCommand "${DT_TOOLCHAIN_DIR}"/usr/bin/bitcode_strip "${flutter_ios_engine_folder}/Flutter.framework/Flutter" -r -o "${xcode_frameworks_dir}/Flutter.framework/Flutter"
  fi
```

This means that even for a project that has bitcode disabled, the framework doesn't get bitcode stripped, and increases the size of the archive when it could be reduced.

Would it be possible to key off the xcode project bitcode setting to determine if we could strip bitcode, even for archive builds?

**Comment by dannyvalentesonos** [comment]
[✓] Flutter (Channel dev, 1.18.0-11.0.pre, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.18.0-11.0.pre at /Users/danny.valente/Library/flutter/1.18.0-11.0.pre-dev
    • Framework revision 8568eda15b (3 days ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

**Comment by dannyvalentesonos** [comment]
Looking at the environment variables set from Xcode during the execution of the script, I see:
` export ENABLE_BITCODE=NO`
I imagine the script could key off $ENABLE_BITCODE as well as $ACTION.

FYI @dnfield

**Comment by dannyvalentesonos** [comment]
@VladyslavBondarenko @dnfield We have create a PR with a suggestion for the fix.

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/57027, closing.
