### ISSUE TITLE
improve error message when multiple device name/id matches are found

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5675]
```
%flutter install
More than one device connected; please specify a device with the '-d <deviceId>' flag.

Eric's iPhone  • 245efaebda74df40169418839fff2a8368bcaae5 • ios
iPhone 6s Plus • EA9593DD-E35B-40BB-B848-3A7B22CC0A4F     • ios

%flutter install -d e
No device found with id 'e'.
```

This used to work, but maybe was intentionally changed?  @danrubel might know.  CC @devoncarew

**Comment by eseidelGoogle** [comment]
Maybe the message is just wrong and it's actually matching both devices?  The simulator device id also starts with E.  donno.

**Comment by danrubel** [comment]
Its matching the the 'E' in 'Eric' and the 'E' in the iPhone 6 id, so the tool does not know which device to target. I should improve the error message in this situation.
