### ISSUE TITLE
[web]: device chrome is not available in channel stable (v.1.17.0)

### ISSUE THREAD

**Issue by patmuk** [flutter/flutter#56758]
When switching to Channel stable, v1.17.0, there is no chrome device.
A terminal log says more than 1000 words ;)

>flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    8fbfe1cfb..a849daf28  dev                  -> origin/dev
git:  * [new branch]          flutter-1.19-candidate.0 -> origin/flutter-1.19-candidate.0
git:    7bce4d9fd..f5d2c8c77  master               -> origin/master
git:  * [new branch]          timsneath-api-readme -> origin/timsneath-api-readme
git:  * [new tag]             1.19.0-0.0.pre       -> 1.19.0-0.0.pre
git: Switched to branch 'beta'
git: Your branch is behind 'origin/beta' by 3 commits, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
> flutter devices
4 connected devices:

Android SDK built for x86 • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
iPhone 11 Pro             • 2EC07DCE-7642-4225-98D9-79F561F8C512 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
Chrome                    • chrome                               • web-javascript • Google Chrome 81.0.4044.138
Web Server                • web-server                           • web-javascript • Flutter Tools

> flutter channel stable
Switching to flutter channel 'stable'...
git: Switched to branch 'stable'
git: Your branch is up to date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
> flutter devices
Downloading Dart SDK from Flutter engine 540786dd51f112885a89792d678296b95e6622e5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  213M  100  213M    0     0  15.3M      0  0:00:13  0:00:13 --:--:-- 15.1M
Building flutter tool...
Downloading package sky_engine...                                   0.4s
Downloading flutter_patched_sdk tools...                            0.9s
Downloading flutter_patched_sdk_product tools...                    0.9s
Downloading darwin-x64 tools...                                     2.3s
Downloading darwin-x64/font-subset tools...                         0.4s
2 connected devices:

Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
iPhone 11 Pro             • 2EC07DCE-7642-4225-98D9-79F561F8C512 • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
> flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
> flutter devices
2 connected devices:

Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
iPhone 11 Pro             • 2EC07DCE-7642-4225-98D9-79F561F8C512 • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

----
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-CH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] VS Code (version 1.45.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by mrpvb-pvbk** [comment]
It's **beta**. Just use this commands:
```
$flutter channel beta
$flutter upgrade
$flutter create .
$flutter run -d chrome
```

**Comment by jonahwilliams** [comment]
Please read https://flutter.dev/web , web is not available on the stable release channel
