### ISSUE TITLE
People are confused by Performance Overlay data in Slow Mode

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5676]
Problem: it's easy to come to an incorrect conclusion or misleading conclusion when evaluating the performance of Flutter. The combination of Slow Mode (aka Dev Mode) and the ease at which someone can open the Performance Overlay while in Slow Mode, makes it easy to see perf charts that don't necessarily reflect useful data.

Goal: a development experience, or an evaluation experience, that shows meaningful info to the developer or drive-by evaluator.

Strawman proposal: disable the Performance Overlay feature in Slow Mode (this assumes that we'll always be missing frames in Slow Mode and that Perf Overlay doesn't really tell me something actionable...) but definitely open to ideas here.

**Comment by chinmaygarde** [comment]
When not running precompiled code, the performance overlay can display a warning label on the graph that indicates that the results may not be reliable.

**Comment by HansMuller** [comment]
I like the option of not showing it at all, since developers reporting performance problems have missed the "SLOW MODE" banner.

**Comment by eseidelGoogle** [comment]
I feel like someone mentioned the other day that we already show something in slow mode here?

**Comment by eseidelGoogle** [comment]
I just tested, and the perf overlay doesn't say anything special in slowmode.

**Comment by Hixie** [comment]
We can certainly hide the performance overlay option in the gallery in debug mode if that's what y'all want. Can you confirm that that is the goal here?

The alternative is adding more labels, but we already say "SLOW MODE" below the chart and it's not clear that there's really room for more labels.

**Comment by chinmaygarde** [comment]
Would appending `WARNING: DEBUG/SLOW BUILD.` to the engine and rasterizer labels suffice?

On a somewhat related note, I discovered that the performance overlay option in the Gallery Application on the Play Store is disabled. I am pretty sure that this option is enabled even in release builds on the Gallery in the Flutter repository. Have we manually disabled the same?

**Comment by kf6gpe** [comment]
I'm closing this per @Hixie's comment above and the fact that there's been no discussion on this issue in ~2 yrs.
