### ISSUE TITLE
Version solving failed after upgrade to Flutter 1.17.0 (Stable)

### ISSUE THREAD

**Issue by SSebigo** [flutter/flutter#56769]
I have an issue with hive_generator (v0.7.0+2) after upgrading Flutter to version 1.17.0 (Stable).

## pubspec.yaml
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.5
  dartz: ^0.9.0-dev.6
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  flare_flutter: ^2.0.3
  flutter_bloc: ^4.0.0
  flutter_icons: ^1.1.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.1
  google_sign_in: ^4.4.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  injectable: ^0.3.0
  logger: ^0.9.1
  package_info: ^0.4.0+16
  path_provider: ^1.6.7
  sailor: ^0.7.1
  stringprocess: ^1.0.10
  uuid: ^2.0.4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: ^0.7.4
  freezed: ^0.10.6
  hive_generator: ^0.7.0+2
  injectable_generator: ^0.3.4
  lint: ^1.1.1

## Error message
Because no versions of hive_generator match >0.7.0+2 <0.8.0 and hive_generator 0.7.0+2 depends on dartx ^0.2.0, hive_generator ^0.7.0+2 requires dartx ^0.2.0.

And because no versions of dartx match >0.2.0 <0.3.0, hive_generator ^0.7.0+2 requires dartx 0.2.0.

And because dartx 0.2.0 depends on quiver >=2.0.3 <2.1.0 and every version of flutter_test from sdk depends on quiver 2.1.3, hive_generator ^0.7.0+2 is incompatible with flutter_test from sdk.

So, because wine depends on both flutter_test any from sdk and hive_generator ^0.7.0+2, version solving failed.
pub get failed (1; So, because wine depends on both flutter_test any from sdk and hive_generator ^0.7.0+2, version solving failed.)
exit code 1

## Steps to reproduce
1. Add hive_generator: ^0.7.0+2 to your dev_dependencies in pubspec.yaml file
2. Upgrade Flutter version to 1.17.0 (Stable)

## flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [version 10.0.18363.778], locale fr-FR)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (7 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at C:\Users\\{my name}\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\\{my name}\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by timsneath** [comment]
Hi there, 

Unfortunately this is working as intended. Your packages are declaring incompatibility with each other. 

This page has more information on how to resolve this: https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution

**Comment by GuilhermeBerni** [comment]
hi

**Comment by zeynepbetul** [comment]
run flutter downgrade
