### ISSUE TITLE
Issue from website page 关于本站

### ISSUE THREAD

**Issue by yummyChina** [flutter/flutter#56772]
From URL: https://www.flutterchina.club/about.md
新手一枚，中文网上的demo源码都无法访问啊

**Comment by timsneath** [comment]
Hi, unfortunately we can't help with this page. It's not run by the Flutter team, but by a group of volunteers.

**Comment by Vadaski** [comment]
There's another great choice of the Flutter Document in Chinese which is always up-to-date: https://flutter.cn/docs @yummyChina

**Comment by yummyChina** [comment]
thank you very much
