### ISSUE TITLE
[Question] Catalina Mac OSX: flutter installation works but upon new zsh terminal not recognized?

### ISSUE THREAD

**Issue by scheung38** [flutter/flutter#56774]
in ~./zshrc:

export PATH="$PATH:Users/cheung/flutter/bin"

source ~./zshrc

~ flutter --version
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (7 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

but now opening another new terminal in Mac OSX

flutter --version
zsh: permission denied: flutter

???

**Comment by timsneath** [comment]
You probably need: 
```
export PATH="$PATH:/Users/cheung/flutter/bin"
```

(without the leading `/`, the latter path is relative, rather than absolute.)

**Comment by scheung38** [comment]
Thanks @timsneath i will check in morning
