### ISSUE TITLE
Crash when starting application on iOS

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#56781]
Crashlytics] Version 3.14.0 (144)
[Crashlytics:Crash:Reports] Packaged report with id '855595b2f2204d79af328549488fa60f' for submission
Configured the default Firebase app __FIRAPP_DEFAULT.
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e39ad9 -[NSException raise] + 9
	3   Runner                              0x0000000101e8cdab GADApplicationVerifyPublisherInitializedAnalyticsCorrectly + 414
	4   Runner                              0x0000000101e3b412 GADEnvironmentIsSupported + 766
	5   libdispatch.dylib                   0x00007fff51911951 _dispatch_call_block_and_rele<…>

**Comment by YazeedAlKhalaf** [comment]
My friend I have the same problem, how did you solve it?
