### ISSUE TITLE
Full screen dialogs should fly in from the bottom, even on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5678]
Full screen dialogs should use a from-the-bottom transition, even on iOS.

My understanding is that the pattern is that things with an X button fly in from below and things with a back button fly in from the right (and have back gesture support).

Gallery > Dialogs > Fullscreen is one example.

iOS itself seems a little confused about this, since:
Settings > Personal Hotspot > Wi-Fi Password
is a dialog-like feel on iOS (has a cancel button) yet flies in from the right (as part of a navigation control.

Uber's Settings fly up from the bottom and have an X.
Inbox's Settings fly up from the bottom and have an X.
Safari Bookmarks fly up from the bottom and have a Done.
Phone > Contacts > + (new contact) flies in from the bottom and has a Done.

Etc.

**Comment by eseidelGoogle** [comment]
@mpcomplete do we know at time of transition if the destination will have a back button?  Presumably not.  Not quite sure how we should distinguish automatically from these transition/route types.  @Hixie might know.

**Comment by mpcomplete** [comment]
I think we theoretically know that info - as in, we have the widget tree for both routes when we start the transition. We just need the right interface to be able to query whether that route's tree contains a back button or not.

**Comment by mpcomplete** [comment]
What about putting the transition type into RouteSettings?
