### ISSUE TITLE
Add a Gap Widget

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#56783]
@letsar has released a package called [gap](https://pub.dev/packages/gap). `Gap` adds gaps between children of Rows/Columns/Scrollables that adapt to the orientation of their parent widget.

It solves the common problem of adding a space between widgets in a clean and safe manner and therefore I'd like to propose that this or a similar widget should be added to the core framework. 

The current solutions to that problem, `SizedBox(width: x)` & `SizedBox(height: x)`, are neither intuitive nor safe in a sense that they have to be adjusted when the orientation of their parent widget changes.

Note: I've asked @letsar and he has no objections to this proposal. Perhaps he would like to submit a PR himself. This issue is only meant to solicit approval from the Flutter Team so that somebody can initiate the work on this.

@goderbauer

**Comment by timsneath** [comment]
Hi there, @modulovalue! This looks like a great package. 

Our general philosophy is to keep the framework small and encourage a package ecosystem just like this. This maximizes flexibility (e.g. being able to ship updates out of band of the main framework release). We do the same with our own packages too: for example, [animations](https://pub.dev/packages/animations).

I'm going to close this issue for now, but thank you so much for your suggestion (and for all the cool things you build with Flutter!)

**Comment by jamesblasco** [comment]
Hello! I agree that the framework should be kept small but not a reason to no consider it. But I think this is not just about a package and more about a way devs have been looking for adding spaces between widgets. And @letsar nailed it with his implementation. 

Flutter team is still evaluating and adding new widgets when they think they are important for its framework. So I hope this widget could be evaluated and have the chance to be decided if it is important or not.

I think a widget that can define a space between widgets in a Flex widget would bring a lot of benefits to the framework. Its implementation is straightforward and its use, in my opinion, a good practice. Let's see an example from the flutter framework:

https://github.com/flutter/flutter/blob/894fdea86088a3a6445dab76a8095f4887f05962/packages/flutter/test/widgets/sliver_constraints_test.dart#L15

```dart
const SliverGap(150),
```

`Spacer` is considered important to be inside the framework when it would be easily possible to add it yourself with `Expanded`. I find this new Widget quite similar.

I don't want to impose anything here and I hope my words don't reflect that 🙂. I just hope this this kind of Widget is given a chance, as I consider it important to have

To reflect this could be possible, I would put as an example my package [modal_bottom_sheet](https://github.com/jamesblasco/modal_bottom_sheet). The new iOS Sheet has been highly demanded by developers, even if my package solves the issue itself, it was offered to me to create a PR to integrate into the framework. https://github.com/flutter/flutter/issues/42560#issuecomment-687478131

**Comment by jamesblasco** [comment]
Out of topic 💙😅: 
I think it would be great to evaluate some core libraries for flutter just like dart ones https://dart.dev/guides/libraries. Therefore the framework would be more modularised but the people would trust this external package more.
```dart
import 'flutter:material';
import 'flutter:animations';
import 'flutter:cupertino';
```
