### ISSUE TITLE
[flutter_tools] Allow to define --dart-define from system environment variables or from .env

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter/flutter#56792]
## Use case

Flutter 1.17 added the ability to define compile-time variables, which is great.

But if you have a lot of variables that you want to use in Flutter application, `build` and `run` command could become quite long.

Especially if take into account that each compile-time variable definition should start with `--dart-define`.

## Proposal 1

Allow defining Map of Dart Defines, where keys will be used for `--dart-define` key, and values - `Platform.environment` keys.

### Example

```yaml
dart_defines:
  ENV: FLUTTER_APP_ENV
  APP_NAME: FLUTTER_APP_NAME
```

Which will be equal to
`flutter run --dart-define=ENV=$FLUTTER_APP_ENV --dart-define=APP_NAME=$FLUTTER_APP_NAME`

## Proposal 2

Allow to use `.env` as source for `--dart-define` key

### Example

```
ENV: SOME_ENV
APP_NAME: SOME_APP_NAME
```

Which will be equal to
`flutter run --dart-define=ENV=SOME_APP_ENV --dart-define=APP_NAME=SOME_APP_NAME`

**Comment by jonahwilliams** [comment]
I don't think we're going to add this. It should be fairly simple to write a script to populate a flutter run command with all the configuration that you need.

also you don't have to use SCREAMING_CAPS, you can use regular, non-screaming, identifiers.

**Comment by TatsuUkraine** [comment]
@jonahwilliams yeah, I understand that CAPS not necessarily, it was just an example)

**Comment by TatsuUkraine** [comment]
@jonahwilliams but overall, idea behind this suggestion is that compile time variable names could be longer actually, since I can assume that developers would like to add some sort of prefix/namespace to them, to avoid any name conflicts between custom and build in variables

**Comment by TatsuUkraine** [comment]
@jonahwilliams I updated proposal a little bit and added variant with `.env` file. It will also may simply dart define usage and probably it will be easier solution than config file. What you think?

**Comment by jonahwilliams** [comment]
I still don't want to do this in the tool. This is easily scriptable outside if the number of files is large.

**Comment by TatsuUkraine** [comment]
> I still don't want to do this in the tool. This is easily scriptable outside if the number of configs is large.

It is, but it's much more convenient to have .env file support, which a lot of different tools supports

**Comment by sigis151** [comment]
Having scripts outside tool would require custom IDE setup and might make some IDE tools inaccessible as you would need to launch custom scripts first to properly run the application

**Comment by d-silveira** [comment]
please reopen this, it is such a useful and simple request!

**Comment by dmacan23** [comment]
I know it is not the best solution, but I use [flutter_dotenv](https://pub.dev/packages/flutter_dotenv) package to achieve this. I've defined all of the environment variables in `.env`, `.env.prod`, `.env.staging` etc. and I'm passing the key for using `.env` through `--dart-define`. The only issue with this approach is that we bundle all of our `.env` files instead of just the one required by the selected environment.

**Comment by TatsuUkraine** [comment]
@dmacan23 not the best workaround actually, since in that way you exposing all your credentials to your VCS, also - all these env files needs to be part of assets in order to make this library work.

**Comment by dmacan23** [comment]
> @dmacan23 not the best workaround actually, since in that way you exposing all your credentials to your VCS, also - all these env files needs to be part of assets in order to make this library work.

I aggree completely. But until the devs decide to support it officially, I see no other way than setting a whole bunch of props in a command.

**Comment by TatsuUkraine** [comment]
@dmacan23 https://pub.dev/packages/flutter_config + https://pub.dev/packages/environment_config

**Comment by dmacan23** [comment]
@TatsuUkraine thanks. I'll look into those and apply them to my app!

**Comment by TatsuUkraine** [comment]
@dmacan23 np) you can read this [article](https://medium.com/@tatsu.ukraine/configure-your-flutter-environment-in-the-proper-way-b81782c79726) under the "Combine the best from both worlds" section there is an example with integration for CodeMagic

**Comment by TatsuUkraine** [comment]
@dmacan23 another possible way, which friend of mine is using, use environment_config for dart props, and dart-define for native layers props

**Comment by TatsuUkraine** [comment]
But my personal preference still - add support of .env files into flutter_tools

**Comment by UdaraWanasinghe** [comment]
Writing script is simple. But it requires manual configuration though. It is better if that feature is integrated into the Flutter tools.
`flutter run --dart-define-env=.env`
So that we can give `--dart-define-env=.env` in the additional arguments in build configurations.

**Comment by jeiea** [comment]
I want to use `--dart-define` [for build configuration](https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d), and tried integrating it to vscode `launch.json`.
```json
    {
      "name": "Debug build",
      "type": "dart",
      "request": "launch",
      "flutterMode": "debug",
      "args": ["--dart-define=SOME=THING"],
      "preLaunchTask": "build_runner watch"
    }
```
I couldn't find easy way to import `args` from the external file for cli build because launch.json is not scriptable with `dart` type.
If there's no plan to add more desirable way in the near future, how about reconsidering this issue?

**Comment by jeiea** [comment]
> I still don't want to do this in the tool. This is easily scriptable outside if the number of configs is large.

If it was easy, there might be a script for this purpose already. But I could not find one. I thought about why.
- Using script means you can't build the project by `flutter build`.
- Not always script is usable in ide, like the above.
What I say is using script is not easy. It's impossible or difficult according to the goal.

`--dart-define` is more attractive approach than others in that configuration is simpler. But this issue is the only obstacle to adoption.

Is there any other reason to refuse?

**Comment by caiangums** [comment]
Hey! I noticed that this still can be an issue and personally, I believe that `flutter` CLI could support sending a file for `dart-defines` values such as described here. As a suggestion, a good approach could be something like:
```sh
$ flutter run --dart-define-file=<filename>
```
and convention the file to be at the `.env` file format such as `KEY=value`.

If anyone still needs a solution here (and maybe even at #48707), I suggest using a version of [this gist](https://gist.github.com/caiangums/74047096f1e0d81b8c0c14feb6a5980f)
```sh
#!/bin/bash

FLUTTER_RUN="flutter run"

if [ ! -z "$1" ]
then
    SUPPLIED_ENV_FILE="$1"
    while IFS= read -r line
    do
      FLUTTER_RUN="$FLUTTER_RUN --dart-define=$line"

    done < "$SUPPLIED_ENV_FILE"
fi

source $FLUTTER_RUN
```

**Comment by triztian** [comment]
I actually just had to do this inside of `Make` which was a bit trickier considering make's syntax and context-rules:

```make
DEVICE=NONE
SECRETS_DEBUG=secrets.debug.env

run: $(SECRETS_DEBUG)
	$(eval tmp := $(shell mktemp))
	awk -F'=' '{ defines="--dart-define " $$1 "=" $$2 } END {print "flutter run -d $(DEVICE) " defines }' $< > $(tmp) && \
		cat $(tmp) && source "$(tmp)"
```

And I run it like so:

```bash
make DEVICE=<somedeviceid> run
```

The double `$$` escapes variables in the make context and the `cat` is to inspect the sources when its ran. My file is named `secrets.debug.env` and it can be changed in the make source or in command links`make SECRETS_DEBUG=.env DEVICE=<somedeviceid> run`

**Comment by zhengcan** [comment]
> I know it is not the best solution, but I use [flutter_dotenv](https://pub.dev/packages/flutter_dotenv) package to achieve this. I've defined all of the environment variables in `.env`, `.env.prod`, `.env.staging` etc. and I'm passing the key for using `.env` through `--dart-define`.

Some internal codes depend on environment variables. They won't depend on flutter_dotenv at all.
eg: https://github.com/dart-lang/sdk/issues/43769

**Comment by venkatd** [comment]
@jonahwilliams how does the Flutter team currently handle this? Would you mind pointing to the script they use? This has been a pain point for us, so if it's preferred not to make this an official Flutter feature, an alternative would be to share a best practice for it.
