### ISSUE TITLE
Drag to select calendar start/end day range

### ISSUE THREAD

**Issue by erf** [flutter/flutter#56799]
## Use case

I would like to select a start and end day range, by dragging from one day to another, or by tapping two days.

## Proposal

I would like to see an overview of all the days in a month or on a per week basis, where i can click and drag a start / end day range, or by tapping two days. The range would be visually highlighted.

Maybe add a new `DatePickerEntryMode` for this?

But since, `showDatePicker` only return a single `DateTime` there is perhaps need for a new API for this like `showDatePickerRange`, or `showDatePicker` could perhaps return a `Future<List<DateTime>>`.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by kunit1** [comment]
Is this what you're looking for?
[PR](https://github.com/flutter/flutter/pull/55939)

**Comment by erf** [comment]
@kunit1 awsome. i guess i can close this now.

**Comment by erf** [comment]
@darrenaustin i saw you implemented the date range picker, i like the look of it, do you know if we could use the same calendar to pick a single date? Also do you know if there are plans to add functionality to drag-select a range?

**Comment by darrenaustin** [comment]
> @darrenaustin i just testet the new range picker on master, i like the look of it, do you know if we could use the same calendar to pick a single date? 

While this picker is designed for selecting a date range, that date range can consist of only one date. You can tap a date to select it as the start of the range and then tap that same date again to select it as the end date. If you want to just select a single date, I would recommend `showDatePicker` as that is what it is designed for.

> Also do you know if there are plans to add functionality to drag-select a range on mobile?

It was definitely something we want to do, but haven't had the cycles to implement yet.

**Comment by erf** [comment]
@darrenaustin Thanks, i like how the material design for desktop selects ranges, perhaps it could be done for mobile also, by holding and dragging a range.
