### ISSUE TITLE
v1.12.13 or v1.17 build release APK get NoSuchMethodException error

### ISSUE THREAD

**Issue by liusilong** [flutter/flutter#56801]
## When I upgraded to 1.17, I encountered the following problems. 1.12.13 also has this problem.

https://stackoverflow.com/questions/61699344/flutter-build-release-apk-get-nosuchmethodexception-error

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
