### ISSUE TITLE
【Tabbar jitter occurs】When the tabbar slides, zooming in and out is not smooth, and jitter occurs

### ISSUE THREAD

**Issue by albertPu** [flutter/flutter#56807]
```dart
AppBar(
              centerTitle: false,
              automaticallyImplyLeading: false,
              actions: <Widget>[
                GestureDetector(
                  child: AppImage.asset(
                    Res.search,
                    width: 20,
                    margin: EdgeInsets.only(right: 20),
                  ),
                  onTap: () {},
                )
              ],
              elevation: 0,
              brightness: Brightness.light,
              backgroundColor: Colors.white,
              title: Container(
                margin: EdgeInsets.only(left: 0),
                width: Dims.MATCH_PARENT,
                alignment: Alignment.centerLeft,
                child: TabBar(
                  indicator: UnderlineTabIndicator(
                    insets: EdgeInsets.fromLTRB(12, 0, 12, 5),
                    borderSide: BorderSide(
                      width: 2,
                      color: ColorApp.Main,
                    ),
                  ),
                  controller: widget.controller,
                  //可以和TabBarView使用同一个TabController
                  tabs: widget.tabs,
                  isScrollable: true,
                  indicatorColor: ColorApp.Main,
                  indicatorWeight: 1,
                  indicatorSize: TabBarIndicatorSize.label,
                  labelColor: Colors.black,
                  labelStyle: TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold),
                  unselectedLabelColor: Colors.black,
                  unselectedLabelStyle: TextStyle(
                    fontSize: 14.0,
                  ),
                ),
              )),
        ),
        body: TabBarView(
            controller: widget.controller,
            children: widget.tabs
                .map((Tab tab) => Container(
                        child: Container(
                      color: Colors.white,
                      child: EasyRefresh(
                        header: ClassicalHeader(
                          infoColor: ColorApp.Color_Txte_1,
                          textColor: ColorApp.Color_Txte_1,
                        ),
                        footer: ClassicalFooter(
                          infoColor: ColorApp.Color_Txte_1,
                          textColor: ColorApp.Color_Txte_1,
                        ),
                        // ignore: missing_return
                        onRefresh: () {
                          _viewModel.refresh();
                        },
                        // ignore: missing_return
                        onLoad: () {
                          _viewModel.loadMore();
                        },
                        child: ListView.builder(
                          itemBuilder: (context, index) {
                            return getImageItem(_viewModel.imags[index]);
                          },
                          itemCount: _viewModel.imags.length,
                        ),
                      ),
                    )))
                .toList()),
      ),
    );
  }
```

**Comment by albertPu** [comment]
AppBar(
              centerTitle: false,
              automaticallyImplyLeading: false,
              actions: <Widget>[
                GestureDetector(
                  child: AppImage.asset(
                    Res.search,
                    width: 20,
                    margin: EdgeInsets.only(right: 20),
                  ),
                  onTap: () {},
                )
              ],
              elevation: 0,
              brightness: Brightness.light,
              backgroundColor: Colors.white,
              title: Container(
                margin: EdgeInsets.only(left: 0),
                width: Dims.MATCH_PARENT,
                alignment: Alignment.centerLeft,
                child: TabBar(
                  indicator: UnderlineTabIndicator(
                    insets: EdgeInsets.fromLTRB(12, 0, 12, 5),
                    borderSide: BorderSide(
                      width: 2,
                      color: ColorApp.Main,
                    ),
                  ),
                  controller: widget.controller,
                  //可以和TabBarView使用同一个TabController
                  tabs: widget.tabs,
                  isScrollable: true,
                  indicatorColor: ColorApp.Main,
                  indicatorWeight: 1,
                  indicatorSize: TabBarIndicatorSize.label,
                  labelColor: Colors.black,
                  labelStyle: TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold),
                  unselectedLabelColor: Colors.black,
                  unselectedLabelStyle: TextStyle(
                    fontSize: 14.0,
                  ),
                ),
              )),
        ),
        body: TabBarView(
            controller: widget.controller,
            children: widget.tabs
                .map((Tab tab) => Container(
                        child: Container(
                      color: Colors.white,
                      child: EasyRefresh(
                        header: ClassicalHeader(
                          infoColor: ColorApp.Color_Txte_1,
                          textColor: ColorApp.Color_Txte_1,
                        ),
                        footer: ClassicalFooter(
                          infoColor: ColorApp.Color_Txte_1,
                          textColor: ColorApp.Color_Txte_1,
                        ),
                        // ignore: missing_return
                        onRefresh: () {
                          _viewModel.refresh();
                        },
                        // ignore: missing_return
                        onLoad: () {
                          _viewModel.loadMore();
                        },
                        child: ListView.builder(
                          itemBuilder: (context, index) {
                            return getImageItem(_viewModel.imags[index]);
                          },
                          itemCount: _viewModel.imags.length,
                        ),
                      ),
                    )))
                .toList()),
      ),
    );
  }

**Comment by albertPu** [comment]
when silding,the text size from 18 px to 14 px,the text change not smooth,plases help

**Comment by iapicca** [comment]
Hi @albertPu 
I'm not sure how the `zoom` is implemented in your app;
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
