### ISSUE TITLE
Invalid Dynamic Link

### ISSUE THREAD

**Issue by jeanluc243** [flutter/flutter#56803]
```bash
$ flutter run --release
Launching lib/main.dart on SM G935F in release mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
...
```

**Flutter recomanded me to visit the following link : [https://goo.gl/CP92wY](https://goo.gl/CP92wY)**
but once you clicked on the link, that one doesn't work ...

*Requested URL (https://goo.gl/CP92wY.) must be a parseable URI, but possibly incomplete to be a DynamicLink.*

*If you are the developer of this app, ensure that your Dynamic Links domain is correctly configured and that the path component of this URL is valid.*

**Comment by joekendal** [comment]
The link is the same... and it works...
