### ISSUE TITLE
I stuck in the process of 'Assembling debug" after upgrading new version"1.17.0".

### ISSUE THREAD

**Issue by FengChendian** [flutter/flutter#56813]
Issue: After updating flutter to verison 1.17, there was a severe problem. When I tried to run the app and debug, it would always get stuck in the process of 'Assembling debug..'.And it seemed that some dependencies cannot be got . But after I had downgraded to flutter v1.12.13, all things went smoothly. So there might be something wrong with version 1.17. Can anyone help me?

PS: I am in China, and I have tried mirrors and proxy, however, none of them worked.

**Comment by Blast06** [comment]
im facing the same , i got stuck in installing app(vscode), and in android studio the app installs but it does not hot reload. Im gonna try downgrading to see if that works to me too

**Comment by VladyslavBondarenko** [comment]
Hi @FengChendian 
Could you provide your `flutter doctor -v` and `flutter run --verbose`?

Related to https://github.com/flutter/flutter/issues/56637, https://github.com/flutter/flutter/issues/56640

**Comment by Blast06** [comment]
Confirmed, i did exactly the same, and now everything is working right.

**Comment by FengChendian** [comment]
> 
> 
> Hi @FengChendian
> Could you provide your `flutter doctor -v` and `flutter run --verbose`?
> Does it happen with default app created via `flutter create` as well?
> 
> Related to #56637, #56640
Here is `flutter doctor -v` and` flutter run --verbose`.
I created this app via AndroidStudio with default settings. And there is no problem in v1.12.13.
[log.txt](https://github.com/flutter/flutter/files/4610105/log.txt)
![B)X6 CMK)Q37Q%L4P0X0MSJ](https://user-images.githubusercontent.com/37545115/81572291-9d06b100-93d5-11ea-9c42-544f7daa21d2.png)

**Comment by FengChendian** [comment]
> 
> 
> Confirmed, i did exactly the same, and now everything is working right.

I think new version has some mistakes. So I will use V1.12.13 until next version.

**Comment by VladyslavBondarenko** [comment]
@FengChendian 
Does it happen with default app on stable 1.17.0?
I can't reproduce it when running default app on windows with Redmi Note 7 Android 9 (API 28) and Android 10 (API 29) (emulator)

**Comment by xster** [comment]
This is the same issue as https://github.com/flutter/flutter/issues/55134. Please try on master. I will submit a request to cherry-pick into 1.17 but it's not guaranteed.

**Comment by FengChendian** [comment]
> @FengChendian 
> Does it happen with default app on stable 1.17.0?
> I can't reproduce it when running default app on windows with Redmi Note 7 Android 9 (API 28) and Android 10 (API 29) (emulator)

@VladyslavBondarenko 
I think it only happens in China because of connection to maven URL. There is the same issue as #55134. Thanks for  @xster
