### ISSUE TITLE
testing impossible

### ISSUE THREAD

**Issue by flowcharterappowner** [flutter/flutter#56819]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by flowcharterappowner** [comment]
1. flutter create a new project
2. right-click on the widget_test.dart
3. errors:

/Installed/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'

**Comment by TahaTesser** [comment]
Hi @flowcharterappowner 
Default test doesn't fail. if you're modifying it. Please sure you're not  importing the main.dart file in the test file if it imports dart:ui  [Reference](https://github.com/flutter/flutter/issues/27826#issuecomment-463086430)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
