### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.

### ISSUE THREAD

**Issue by saravananmnm** [flutter/flutter#56827]
```dart
@override
  Widget bind(BuildContext context, int index) {
    return Container(
        child: item.mOrderStatusId == StringConstant.ACPT
            ? getBidAcceptView(context)
            : getAwardedView(context));
  }

  Widget getAwardedView(BuildContext context) {
    return Stack(
      fit: StackFit.loose,
      children: <Widget>[
        getDetailsCard(context, item),
        getHeaderCard(context, item)
      ],
    );
  }

  Widget getBidAcceptView(BuildContext context) {
    return Stack(
      fit: StackFit.loose,
      children: <Widget>[getAucDetailsCard(context), getAucHeaderCard(context)],
    );
  }
```

**Comment by saravananmnm** [comment]
E/flutter ( 3704): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.
E/flutter ( 3704): Receiver: null
E/flutter ( 3704): Tried calling: focusScopeNode
E/flutter ( 3704): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 3704): #1      Route.didPush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:139:17)
E/flutter ( 3704): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 3704): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 3704): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 3704): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 3704): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 3704): #7      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 3704): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter ( 3704): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 3704): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 3704): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 3704): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 3704): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 3704): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by saravananmnm** [comment]
C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Genymotion • 192.168.215.101:5555 • android-x86 • Android 9 (API 28)

**Comment by saravananmnm** [comment]
from listing, when i call alert dialog above the listing it's throw the error. 
but without listing view it's working fine.
how can handle the alert dialog after call done from listing?
any solutions?

**Comment by iapicca** [comment]
Hi @saravananmnm 
could you please run `flutter upgrade --force`
and please provide your updated `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by saravananmnm** [comment]
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  http: ^0.12.0+1
  kiwi: ^0.1.0
  rxdart: ^0.23.1
  shared_preferences: ^0.5.1+1
  sembast: ^2.0.1+2
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.5.0
  jaguar_serializer:
  device_info: ^0.4.0+2
  imei_plugin: ^1.1.6
  permission_handler: ^4.3.0
  jaguar_retrofit: ^2.8.8
  loadmore: ^1.0.3
  url_launcher: ^5.1.3
  intl:
  tree_view:
  flutter_google_places:
  google_maps_webservice:
  geolocator:
  google_maps_flutter: ^0.5.21+2
  flutter_local_notifications:
  firebase_messaging:
  signature: ^2.0.0
  path_provider: ^1.6.5
  image_picker: ^0.6.1+4
  flutter_map: ^0.9.0
  flutter_native_timezone: ^1.0.4
  image:
  flutter_polyline_points: ^0.1.0
  path: ^1.6.4
  app_settings: ^3.0.1
  webview_flutter: ^0.3.21
  cached_network_image: ^2.2.0+1

dev_dependencies:
  build_runner:
  jaguar_retrofit_gen:
  jaguar_serializer_cli:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

**Comment by TahaTesser** [comment]
Hi @saravananmnm 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by saravananmnm** [comment]
`class TabView extends StatefulWidget {
  int Index;

  TabView({this.Index = 0});

  @override
  _TabViewState createState() => _TabViewState();
}

class _TabViewState extends State<TabView> {
  List<Widget> widgets = [];

  @override
  void initState() {
    widgets.add(AuctionListing());
    widgets.add(OrdersListing());
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: getTabs().length,
        initialIndex: widget.Index,
        child: Center(
            child: Scaffold(
                appBar: PreferredSize(
                    child: Container(
                      margin: EdgeInsets.only(left: 5.0, right: 5.0),
                      height: 50.0,
                      child: getTabbar(),
                    ),
                    preferredSize: new Size.fromHeight(50.0)),
                body: getTabBarView())));
  }

  Widget getTabbar() {
    return TabBar(
        labelColor: Colors.blue,
        unselectedLabelColor: const Color(0xffacb3bf),
        indicatorPadding: EdgeInsets.all(0.0),
        indicatorWeight: 4.0,
        labelPadding: EdgeInsets.only(left: 0.0, right: 0.0),
        indicator: ShapeDecoration(
            shape: UnderlineInputBorder(
                borderSide: BorderSide(
                    color: Colors.transparent,
                    width: 0,
                    style: BorderStyle.solid)),
            gradient: LinearGradient(colors: [
              ColourConstant.GRADIENT_1,
              ColourConstant.GRADIENT_2,
              ColourConstant.GRADIENT_3,
              ColourConstant.GRADIENT_4
            ])),
        tabs: getTabs());
  }

  Widget getTabBarView() {
    return Container(
      height: MediaQuery.of(context).size.height,
      alignment: Alignment.center,
      child: TabBarView(children: widgets,),
    );
  }

  List<Widget> getTabs() {
    return [
      Container(
        height: 52,
        alignment: Alignment.center,
        color: Colors.white,
        child: Text(
          StringConstant.Auction,
        ),
      ),
      Container(
        height: 52,
        alignment: Alignment.center,
        color: Colors.white,
        child: Text(
          StringConstant.Orders,
        ),
      ),
    ];
  }

}
`

**Comment by iapicca** [comment]
Hi @saravananmnm 
thank you for providing you `pubspeck.yaml`
as in my previous [answer](https://github.com/flutter/flutter/issues/56827#issuecomment-626653339)
I see you are running an older version of flutter stable
could you please upgrade to the most recent version,
also you code sample is not reproducible or minimal
depending from outside data 

```dart
  widgets.add(AuctionListing());
    widgets.add(OrdersListing());
```
does this [code sample ](https://dartpad.dev/21a14022a99d1f394678721ccfb1e51f)help?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ankitasuman009** [comment]
hi @saravananmnm i was having the same issue and then i found that i made an object but i didn't call its constructor. so may be 

    widgets.add(AuctionListing());
    widgets.add(OrdersListing());

in these lines you're calling a class function without using its object.
