### ISSUE TITLE
Crashing my Flutter Dev environment freequently(Using Windows OS with 8GB RAM)

### ISSUE THREAD

**Issue by kolluruprakash** [flutter/flutter#56825]
While trying to run my simple flutter application throwing the error in console of Android studio as below specified.
"Sending crash report to Google.
Crash report sent (report ID: a39c68ac91595b0e)"

-- Expecting quick response from your team on this issue pls.

Thank you.

**Comment by iapicca** [comment]
Hi @kolluruprakash 
are you experiencing this issue only using android studio 
or running your app from terminal or vs code as well?
If the former, following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

If the issue occurs with Vs Code and from terminal as well 
could you please provide your `flutter doctor -v` 
and your `flutter run --verbose` 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
