### ISSUE TITLE
Polylines always drawing the shortest path to the starting point

### ISSUE THREAD

**Issue by leonardoayres** [flutter/flutter#56833]
I'm facing a curious problem regarding Polylines on **google_maps_flutter** using the **google_map_polyline** package.

When i'm going for a walk and start the route (using the **Location** package to ensure updated coordinates) the polylines keep drawing without problem if the route is a straight line or get far away from the destination.

However, if my route try do go around back to the starting point, at some point, all the polyline drawn is redrawed considering my current point and the shortest path to the origin point, like if i've made another path (the shortest to my current point).

**Comment by VladyslavBondarenko** [comment]
Hi @leonardoayres 
Open the issue in the [google_map_polyline repository](https://github.com/Shark01/google_map_polyline/issues), 
Closing since from the description it seems to be not an issue with the google_maps_flutter.
If you disagree please write in the comments and I will reopen it
