### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by rakeshkathoju** [flutter/flutter#56837]
How to receive Shared data(Text,image,video.etc) from another application in to my flutter application which is being developed in android and iOS.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
