### ISSUE TITLE
How do I redirect the user to the HomePage if he was logged in before, using Flutter Redux?

### ISSUE THREAD

**Issue by saurabhpetkar** [flutter/flutter#56841]
I want to implement user authentication using redux.
My Steps:
1. check if the user info was stored locally or not using shared preferences. till then keep him at FlashScreenPage.
2. If the info is found, Redirect him to the HomePage()
3. If the info is not found, redirect him to LoginPage().

This is my root widget (main.dart)
```
import 'package:flutter/material.dart';
import 'package:flutter_ecommerce/pages/flash.dart';
import 'package:flutter_ecommerce/pages/login.dart';
import 'package:flutter_ecommerce/pages/register.dart';
import 'package:flutter_ecommerce/redux/actions.dart';
import 'package:flutter_ecommerce/redux/reducers.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:redux_thunk/redux_thunk.dart';
import 'package:redux/redux.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'models/app_state.dart';

//enum LogMode {loggedout, login, flashscreen}

void main() {
  final store = Store<AppState>(
    appReducer,
    initialState: AppState.initial(),
    middleware: [thunkMiddleware],
  );

  runApp(MyApp(store: store));
}

class MyApp extends StatefulWidget {
  final Store<AppState> store;

  const MyApp({Key key, this.store}) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  LogMode mode = LogMode.flash;

  @override
  void initState() {
    super.initState();
  }

 // void checkForUser() async {
  //   final prefs = await SharedPreferences.getInstance();
  //   var storedUser = prefs.getString('user');
  //   if (storedUser == null) {
  //     setState(() {
  //       mode = LogMode.logout;
  //     });
  //   } else {
  //     setState(() {
  //       mode = LogMode.loggedin;
  //     });
  //   }
  // }

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: widget.store,
      child: MaterialApp(
        title: 'Flutter Redux',
       
        routes: {
          '/': (BuildContext context) => mode == LogMode.flashscreen ? FlashscreenPage() : mode == LogMode.loggedout ? LoginPage() : HomePage();       //here lies the problem
          '/register': (BuildContext context) => RegisterPage(),
          '/home': (BuildContext context) => ProductsPage(),
        },
      ),
    );
  }
}
```
this is my store:
```
import 'dart:convert';
import 'package:flutter_ecommerce/models/user.dart';
import 'package:meta/meta.dart';

enum LogMode {loggedout, login, flashscreen}

@immutable
//you cant change the below class or its sub classes
class AppState {
  final User user;
  final LogMode mode;
  AppState({@required this.user, @required this.mode});

  factory AppState.initial(){
    return AppState(user: null, mode: LogMode.flashscreen);
  }
}
```
This is what I want to do.
As soon as the app restarts, the code should check if the user was logged in before or not using shared preferences. Since this task is an async process. I want to redirect the user to FlashScreenPage() which is a statelessWidget. After that async process gets completed, if the user had his info stored in the memory then I want him to be redirected to the HomePage else to LoginPage.

I achieved this using the checkForUser() method in my main.dart just by simple setState method.
But the problem is that I was unable to update the App Store (or state) of the App. i.e the user was logged in.
For doing that I would have to dispatch another action in the initState of the HomePage() to set the User info.
But that would cause another problem: Every time I will redirect to the HomePage(), the initState will  keep on changing the AppState unnecessarily. (running HomePage multiple times => means running its initState multiple times => means dispatching action to update Store multiple times)
How do I solve this?

my flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-10.0.pre, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
