### ISSUE TITLE
Gallery, Pesto: pesto icon in app bar jumps/janks on resize

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5684]
"On dynamic resize of toolbar, would be great if PESTO label faded during the resize animation, so that the icon could simply shrink rather than shrink but then (jump cut) expand"

**Comment by eseidelGoogle** [comment]
Is this the same as https://github.com/flutter/flutter/issues/5232?

**Comment by sethladd** [comment]
Don't think so. This is specifically about the icon. Notice how it jumps when it switches from icon+"Pesto" and just icon. We can do something much smoother here.

**Comment by eseidelGoogle** [comment]
Do you mean https://youtu.be/SK7OhV2MRUg ?

**Comment by sethladd** [comment]
Yup, the icon in the app bar "jumping" when resizing. Thanks for the video!

**Comment by mpcomplete** [comment]
I'm unclear how we want this to look. When we switch to the smaller logo, we drop the PESTO text, which affects the relative size of the leaf. Should the leaf remain the same size as the PESTO text fades out, leaving empty space below the leaf? Should the leaf remain the same size but reposition to the center of the logo box, leaving equal empty space above and below? Or should the leaf resize to fill the logo box (as it currently does)?

**Comment by sethladd** [comment]
There's an version of Pesto on the internal iOS distribution source. That shows one way this can go.

I'll try to make a video.

**Comment by dragostis** [comment]
@mpcomplete The way I see it, the leaf should grow, the size of the whole logo should grow even more to accommodate the text which should fade in a bit later in the animation so that it doesn't overlap the leaf.

**Comment by Hixie** [comment]
One way we could do it is to use the same style as we use for the Flutter logo animating between mark-only and stacked mode (bring out the gallery drawer, tap the logo, then long-press the logo, to see what I mean; you can redo the animation by just tapping it again).

**Comment by sethladd** [comment]
Did we come to a resolution for this? Looks like @dragostis has this assigned.

**Comment by sethladd** [comment]
we think maybe @mpcomplete is working on this?
