### ISSUE TITLE
Allow direct blurring of an Image

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#56846]
I would like to be able to blur an `Image`, including bitmaps with transparency, without altering any other areas of the UI.

The typical approach to blurring an image is to use a `BackdropFilter`, but a `BackdropFilter` impacts everything behind it, not just an `Image`.

Additionally, the common practice of using a `DecorationImage` for the purpose of blurring does not provide a `color` property for the bitmap the way that each `Image` widget does.

Lastly, when blurred, I would like the blur to be able to exceed the bounds of the `Image`. This is because the `Image` widget is often sized to exactly fit the bitmap in at least 1 dimension, which would result in cropping of the blur. This behavior could be an additional preference that is offered.

The API for this feature might look like:

```
Image.asset(
  'assets/some_image.png',
  color: Colors.red,
  filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
),
```

Or, if composition makes more sense for this behavior then perhaps an `ImageFilter` widget could be introduced:

```
ImageFilter(
  filter: ui.ImageFilter(sigmaX: 5, sigmaY: 5),
  child: Image.asset(...),
),
```

**Comment by flar** [comment]
The ImageFiltered widget already exists and does exactly what the second suggestion is requesting, just add an `ed` to the name of the widget.

**Comment by flar** [comment]
Fixed late last year by https://github.com/flutter/flutter/pull/47489
