### ISSUE TITLE
Floating label on InputDecoration is truncated even when it could fit

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#56848]
b/154950540

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox(
          width: 300,
          child: InputDecorator(
            decoration: InputDecoration(
              labelText: 'Long1 long2 long3 long4 long5 long6 text',
              border: OutlineInputBorder(
                borderSide: BorderSide(width: 1),
                borderRadius: BorderRadius.all(Radius.circular(4)),
              ),
            ),
            child: Text(''),
          ),
        ),
      ),
    );
  }
}
```

**Comment by mehmetf** [comment]
This might be a restriction in Material Design language. We are double checking.

**Comment by mehmetf** [comment]
@willlarche

**Comment by willlarche** [comment]
Speaking with Design.

**Comment by willlarche** [comment]
The X of the label should be max(standard padding, end of shaped corner). AKA, the start of the label is the start of the text field minus the standard padding (or the end of a shaped corner if larger). The point of the label at which to truncate should mirror that: the max width of the label should be the width of the whole text field minus the max(standard padding, end of shaped corner)*2.

**Comment by mehmetf** [comment]
Ack.

Seems like we have to fix this in the framework. Just a heads up that this issue might be bumped to critical soon. I am waiting for Mulligan to tell me whether they are failing Material review.
