### ISSUE TITLE
upgrade to 1.17.0, android package failed

### ISSUE THREAD

**Issue by Icyoung** [flutter/flutter#56857]
I can run my app, but I can't package in release. 
Many plugins appear error.
I tried to upgrade the version of the plugins And I solved the most problems.
The gradle version of my root is `gradle-5.6.4-all`.
I have to change the version of many plugins to solve them gradle error.
But I am wondering why the plugin's gradle is not passing from my root project.
flutter doctor:

```console
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F83c, locale
    zh-Hans-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio
[✓] Android Studio (version 3.6)
```

Hope to your answer. Thanks.

**Comment by iapicca** [comment]
Hi @Icyoung 
can you please provide 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by Icyoung** [comment]
> 嗨，@ Icyoung， 您
> 能否提供
> 您的`flutter run --verbose`，
> 您的`pubspec.yaml`
> 和可复制的最小代码示例。
> 谢谢
I have solve the problem. The errors might be caused by gradle version. Thanks for your reply.
