### ISSUE TITLE
Line Height For Text Field

### ISSUE THREAD

**Issue by nsjcorps** [flutter/flutter#56864]
## Use case

I am trying to create a paper styled Text Field as shown in the image below by overlaying my Text Field widget with some lines but I want to increase the line-height of the Text Field so it would look better. However, I didn't see anything on the docs that would enable me to do this.

![Answer](https://user-images.githubusercontent.com/35180217/81526378-55d5dd00-934f-11ea-848e-4edfd52336ec.png)

## Proposal

Flutter should add the ability to control the line-height of the TextField!

**Comment by MitchSRobinson** [comment]
Hi @jayndu , how did you solve this problem? I'm looking to implement a similar paper style text area but can't find anything in the docs that would help.

**Comment by jamesnicholls04** [comment]
> Hi @jayndu , how did you solve this problem? I'm looking to implement a similar paper style text area but can't find anything in the docs that would help.

Second this!

**Comment by jayndu** [comment]
Oh sure.

Here is a preview.

![Paper Text Field](https://res.cloudinary.com/codetensor/image/upload/v1612061560/example_ptnnon.gif)

I wrote a quick guide, with the source code. You can view it [here](https://jaycoding.tech/tutorials/guides/make-a-text-field-look-like-real-paper-i-fdziot)

**Comment by jayndu** [comment]
@MitchSRobinson @jamesnicholls04

**Comment by MitchSRobinson** [comment]
That's awesome, thanks and amazing quality tutorial!
