### ISSUE TITLE
[url_launcher] Add a web only `windowName` param

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#56867]
## Use case

[Browser APIs] allow users to open urls in multiple ways: 
 - same window
 - new window
 - new window with an specific name
 - an already existing window

Currently we don't provide mechanisms to specify those behaviors, instead we force users to open all urls always in a new tab.

## Proposal

To give users control about how they believe an specific url should be opened, my proposal is to add a new `windowName` web-only param to the `launch` method.

```dart
Future<bool> launch(
  String urlString, {
  bool forceSafariVC,
  bool forceWebView,
  bool enableJavaScript,
  bool enableDomStorage,
  bool universalLinksOnly,
  String windowName,
  Map<String, String> headers,
  Brightness statusBarBrightness,
})
```

That will be used by the [web implementation] like this
```dart
  html.WindowBase openNewWindow(String url, String windowName = '') {
    return _window.open(url, windowName);
  }
```
[Browser APIs]: https://developer.mozilla.org/en-US/docs/Web/API/Window/open
[web implementation]: https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L28

**Comment by tugorez** [comment]
cc @ditman

**Comment by tugorez** [comment]
https://github.com/flutter/flutter/issues/54281#issuecomment-616803870 is related

**Comment by ditman** [comment]
@tugorez: How will this interact with the current platform detection code?

**Comment by tugorez** [comment]
@ditman that's a great question. Thanks for asking.

IMHO we should give users total control in how to open their urls. In that sense I propose:

1. If provided, always use this `windowName` 
2. otherwise, use the default behavior https://github.com/flutter/flutter/issues/51461

**Comment by ditman** [comment]
Sounds good to me!

**Comment by ditman** [comment]
(Unassigning this unless we are actually working on it)

**Comment by ditman** [comment]
This has been implemented by @balvinderz, and published in the latest version of url_launcher:

* https://pub.dev/packages/url_launcher/changelog#551

The implementation follows @tugorez's [proposal](https://github.com/flutter/flutter/issues/56867#issuecomment-629363114).

The new parameter name is `webOnlyWindowName`.
