### ISSUE TITLE
Only install app's flutter engine once per version via play store

### ISSUE THREAD

**Issue by pepsighan** [flutter/flutter#56863]
## Use case

Currently flutter apps are large compared to pure-java apps as they don't ship any UI engine and such which flutter does. This can limit the use-case for the flutter to be only used in full-fledged apps. It does not allow much mobility in creating Instant Apps as the size constraint is hit.

## Proposal

I don't know if the proposal is practically possible. But here it goes:

For the purpose of deployment to play store, if the app were to be broken in two pieces:
1. Core - flutter engine
2. App - our app logic and resources

Whenever a user installs an app, the play store does this:
1. Check if the Core-part of the app has been installed (or has cache). This core may already have been downloaded due to installation of another flutter app.
2. If this is the first flutter app being installed with this particular version of the core, then download it for the first time only.
3. Download the app-part.
4. Install them.

What this means is that no two apps which are pinned on the same flutter engine will have to download the engine twice. The app download size will drastically reduce (by ~3.5MB).

Because play store and flutter are both owned by Google, this should be theoretically doable. But is it practical? Or is this needed?

**Comment by pedromassangocode** [comment]
Cc @HansMuller @Hixie

**Comment by Hixie** [comment]
This is an excellent idea. It's not really something we can do unless the Play store first implements that behavior, so I shall follow up with that team and close this bug for now.
