### ISSUE TITLE
Future is not a type error is happening after flutter upgrade to 1.17

### ISSUE THREAD

**Issue by Haidar0096** [flutter/flutter#56862]
## Steps to Reproduce

1. Create a new flutter project using usual steps in android studio

2.Create an abstract class as shown in the image that uses `dartz`  package and some other classes defined in the same project (which have no errors)

**Expected results:** 
Not seeing any errors like `Future is not a type` !!

**Actual results:** 

seeing  errors like `Future is not a type` !!

Results of `Flutter doctor -v`

```[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/haidar/dev/flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/haidar/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/haidar/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/haidar/dev/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

And here are 3 images to show you how the error begins to occur:

This one is before the error:
![Screenshot from 2020-05-11 06-24-10](https://user-images.githubusercontent.com/49842031/81521916-638c6200-9351-11ea-8f27-17d07a3bb830.png)

This one is when I start typing `Future`, here the error happens specifically when I press `Enter` to accept the IDE's suggestion
![Screenshot from 2020-05-11 06-24-45](https://user-images.githubusercontent.com/49842031/81521943-756e0500-9351-11ea-8011-e8d182bdfd4d.png)
and here is the error:
![Screenshot from 2020-05-11 06-25-18](https://user-images.githubusercontent.com/49842031/81521995-97678780-9351-11ea-87b0-ba2258ca4a97.png)

![Screenshot from 2020-05-11 06-14-43](https://user-images.githubusercontent.com/49842031/81522002-a3ebe000-9351-11ea-9461-03da9f9dc9d4.png)

**Comment by owenkealey** [comment]
Did you try restarting the editor? That worked for me

**Comment by iapicca** [comment]
Hi @Haidar0096 
if you are experiencing the problem with [dartz](https://pub.dev/packages/dartz) 
you may want to open an issue in the dedicated [github](https://github.com/spebbe/dartz/issues),

otherwise please provide a reproducible minimal code sample
that does not involve 3rd party packages.
Please refrain from posting pictures if not necessary.
THank you

**Comment by Haidar0096** [comment]
> Hi @Haidar0096
> if you are experiencing the problem with [dartz](https://pub.dev/packages/dartz)
> you may want to open an issue in the dedicated [github](https://github.com/spebbe/dartz/issues),
> 
> otherwise please provide a reproducible minimal code sample
> that does not involve 3rd party packages.
> Please refrain from posting pictures if not necessary.
> THank you

Hi,thanks for the response
No the problem is not with dartz
I created a new project, the flutter sample counter app,
and created a new class,
and when I try to create a field in that class using the word Future (as shown in the picture above),
the IDE stops autocompletion and all code becomes white colored as if it does not recognize the language anymore and as I said code completion stops working in all the IDE
I tried restaring the pc
reinstalling flutter 1.17
restarting the IDE
invalidate caches/restart
switching to other channels on 1,17
Nothing worked
So I reinstalled flutter 1.12 for now until this is fixed

Sorry if the problem is not reproducible but I don't know what should I provide more because I don't even know what is causing it

**Comment by TahaTesser** [comment]
Hi @Haidar0096 
Not able to reproduce this issue on stable on MacOS and Linux in Android Studio
Downgrading isn't a solution but if the problem persist please comment below and i will reopen the issue
Thank you

**Comment by Philngtn** [comment]
If you are running macOS, open Activity Monitor and terminate Dart (quite sure that it take up ~90% CPU). This disables the dart:async library and makes the fan run freaking loud

**Comment by raitonoberu** [comment]
Yes, I saw this error three times today. Process dart.exe loaded the CPU by 30%... The termination of the process helped every time.
Windows 10, Flutter (Channel beta, 1.25.0-8.1.pre)

**Comment by Philngtn** [comment]
If the termination does not help you, check the syntax, there is maybe a redundant } or ), which make the Future class disable.
