### ISSUE TITLE
[webview_flutter] handle permissions

### ISSUE THREAD

**Issue by samrat19** [flutter/flutter#56871]
I have a Website that asks User's Camera and Microphone permission but I can not achieve the feature with this Webview Plugin. Is there any way to do that?

**Comment by VladyslavBondarenko** [comment]
@samrat19 
does it help https://stackoverflow.com/questions/44180093/cant-access-camera-from-android-webview-chrome-frame-in-context-of-webrtc, 
https://stackoverflow.com/questions/38917751/webview-webrtc-not-working/?

**Comment by samrat19** [comment]
Do I need to use a platform channel for this?

**Comment by VladyslavBondarenko** [comment]
@samrat19 you can try https://pub.dev/packages/flutter_inappwebview

**Comment by zhou-zc** [comment]
when will it support handle permissions，I have a more urgent need

**Comment by nemoryoliver** [comment]
When? I thought this package is now stable... wish it would be implemented soon...

**Comment by mikymod** [comment]
any updates about this feature?

**Comment by programmo** [comment]
> any updates about this feature?

Hi I didn't understand if someone managed to get work in Ios and Android the permission to use camera inside the plugin ... 
Can someone clarify ? 
I didn't manage trying the solutions till now proposed ...
Thank you

**Comment by fre391** [comment]
would like to have this feature as well....Thank you so much

**Comment by firsttalk26** [comment]
@programmo  , I have the same issue.  I am unable to access camera.
@VladyslavBondarenko   , using flutter_inappwebview  I am unable to access camera 

I have done all the steps according to official documentation.  

Anyone please help me

**Comment by dbseitenfus** [comment]
Some update?

**Comment by g-jindal2001** [comment]
Any updates?

**Comment by hiloliddinj** [comment]
Any Updates?

**Comment by mbenci** [comment]
Any Updates?

**Comment by sdrhmn** [comment]
Any updates?

**Comment by singhpratham72** [comment]
Any updates?

**Comment by cool0305** [comment]
Any update?

**Comment by iamvikashh** [comment]
any update?

**Comment by bigyank** [comment]
Its been nearly 2023 and this simple feature doesn't exist till now

**Comment by sdrhmn** [comment]
Its clear google doesn't want webrtc vendors, and wants to sell its own products like zoom

**Comment by sunndog** [comment]
We converted our Android application to Flutter but this WebView integration has to stay native until this feature exists.  Is there any reason why this permissions issue isn't being addressed?

**Comment by sdrhmn** [comment]
I tried and tried and tried - my final conclusion - dump flutter. Google wants to promote its own video calling products and is not interested in letting others have the technical know how.

**Comment by FarukAyd** [comment]
same problem, no update :(

**Comment by sdrhmn** [comment]
Everyone at Google uses apple products and they do so very proudly! Google products are pure garbage, and the people who understand this the best are google employees!

**Comment by vantutrieu97** [comment]
I've been struggling with this bug for 2 days now :(((

**Comment by FarukAyd** [comment]
I used Inappview and it solved problem.

**Comment by vantutrieu97** [comment]
@FarukAyd  I also use the same library as you, but only works on android, iOS doesn't work, can you post your code here?

**Comment by FarukAyd** [comment]
> @FarukAyd I also use the same library as you, but only works on android, iOS doesn't work, can you post your code here?

I didn't try it in IOS just Android :(

**Comment by sdrhmn** [comment]
InAppView works on both iOS and Android, I had tried and it did work, but in my project I cannot use that package.

**Comment by vantutrieu97** [comment]
@sdrhmn It works with any url. However, in my case, I need to use the camera to take a photo; Android works fine, but iOS does not.

**Comment by sdrhmn** [comment]
@vantutrieu97 , those are the kinds of reasons why I am not using the package. I can't trust those packages to deploy in production. We have dumped flutter, its a nice piece of garbage!

**Comment by vantutrieu97** [comment]
@sdrhmn sad to hear your decision,  but it's really useful information

**Comment by dev07060** [comment]
> @FarukAyd I also use the same library as you, but only works on android, iOS doesn't work, can you post your code here?

maybe you should've add some options in info.plist to ask camera permission

**Comment by bigyank** [comment]
```flutter_inappwebview: ^6.0.0-beta.19```
I worked around this issue with the above-mentioned package. Works flawlessly with webRTC.
