### ISSUE TITLE
Why can't the flutter build aar be specific to parameters such as debug and release

### ISSUE THREAD

**Issue by caoyunxiao** [flutter/flutter#56878]
Why can't the flutter build aar be specific to parameters such as debug and release
For example, flutter builds aar-release

**Comment by TahaTesser** [comment]
Hi @caoyunxiao 
Please try this [solution](https://github.com/flutter/flutter/issues/47518#issuecomment-568038067)
Let us know if this answers your question
Thank you

**Comment by caoyunxiao** [comment]
Thanks


Caoyunxiao

On 05/11/2020 22:08, Taha Tesser wrote:

Hi @caoyunxiao
Please try this solution
Let us know if this answers your question
Thank you

**Comment by TahaTesser** [comment]
Hi. @caoyunxiao 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. T
hank you
