### ISSUE TITLE
didChangePlatformBrightness called multiple times flutter

### ISSUE THREAD

**Issue by Richa0305** [flutter/flutter#56879]
I am using didChangePlatformBrightness to get brightness light/dark. It works fine and I am able to update my theme every time brightness is updated. But this function is Called even when app goes in background and comes back again in foreground. I do store the old brightness and compare it with new one and if it is not same then only update my theme. But this function is being called multiple times and doesn't give correct brightness at once. Mostly its being called two times and first time it gives wrong brightness(this behaviour is random) and in last gives correct brightness.

```
@override
  void didChangePlatformBrightness() {
    var theme;
    setState(() {
      var brightness = WidgetsBinding.instance.window.platformBrightness; 
      if (brightness == Brightness.dark) {
        theme = Brightness.dark.toString();
      } else {
        theme = Brightness.light.toString();
      }
    });
    this.updateAppTheme(theme); // Called multiple times 
    super.didChangePlatformBrightness();
  }
```

In the end I do get correct brightness but since function is called multiple times my theme gets updated multiple times. Basically for every time my app goes in background and comes back in foreground my theme get updated. Which I don't want. Please help!

**Comment by iapicca** [comment]
Hi @Richa0305 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a more complete reproducible minimal code sample.
Thank you

**Comment by Richa0305** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F203, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/Richa/Desktop/Dev/flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Richa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 6C1D79FE-B68F-4F3C-97E6-15AE0AF2D420 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**Comment by Richa0305** [comment]
flutter run --verbose is very huge. I am able to get required result by providing a delay - 

@override
  void didChangePlatformBrightness() {
    setState(() {
      brightness = WidgetsBinding.instance.window.platformBrightness;
      Timer(Duration(milliseconds: 500), () {
        var theme;
        if (brightness == Brightness.dark) {
          theme = Brightness.dark.toString();
        } else {
          theme = Brightness.light.toString();
        }
        store.updateAppTheme(theme);
      });
    });
  }

**Comment by iapicca** [comment]
Hi @Richa0305 
I'm glad that you found a work around,
nevertheless your code sample is not reproducible
as isn't representative of your implementation;

also I'd recommend to run `flutter upgrade --force`
making sure that you are not experiencing bugs already fixed.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
