### ISSUE TITLE
Performance issues with PageStorageKey and ListView

### ISSUE THREAD

**Issue by kungfuslippers** [flutter/flutter#56886]
Seeing a similar issue to https://github.com/flutter/flutter/issues/41027

I have a TabBar which contains two ListViews - each with 250 items. I am using a PageStorageKey for each ListView to preserve the scroll position when switching between views.

If I switch between tabs initially when the scroll position hasn't changed much - say at the start of the list, switching between tabs is crisp and quick.

However, if I scroll to the end of each list and switch between the two tabs then there is a noticeable lag before the list is actually displayed.

Is there anything I can do to improve the performance here?

Code Snippet: https://gist.github.com/kungfuslippers/fcae96675fb76c10f7bb5051b66ed87e

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a849daf283 (3 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!


``` 

</details>

**Comment by kungfuslippers** [comment]
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G95, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.41.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by kungfuslippers** [comment]
Managed to resolve this.

When PageStorageKey is used, it has to lay out all of the children up until it reaches the scroll position.
The ListView has a property called itemExtent, which allows you to specify the ListView child's height. If the ListView children all have the same height setting this will considerably improve scroll performance and reduce the lag.

**Comment by jovi848** [comment]
Had I similar issue with a listview in a tab view with 9000 elements, I originally tried the PageStorageKey method however it froze the lower I got into the listview and switch between tabs, but turning my widget into a stateful and add using   @override
  bool get wantKeepAlive => true; did the trick now it runs smooth between switch tabs no matter how log i get in the list.

  `class _ContactListViewState extends State<ContactListView> with **AutomaticKeepAliveClientMixin<ContactListView>** {

  **@override
  bool get wantKeepAlive => true;**

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
        itemCount: widget.contacts == null ? 0 : widget.contacts.length,
        itemBuilder: (BuildContext context, int index) {
          return ContactListItem(
              onSelectContact: widget.onSelectContact, contact: widget.contacts[index]);
        });
  }
}`
