### ISSUE TITLE
Android toolchain error

### ISSUE THREAD

**Issue by kensuke-shimizu** [flutter/flutter#56882]
## error
flutter doctor -android-licenses
Could not find an option with short name "-a".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.

↑I can't get rid of the Android toolchain error.
What can I do to help?

## Mac OS
Catalina 10.15.4

## flutter doctor
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266,
    locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

flutter doctor -android-licenses
Could not find an option with short name "-a".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.

**Comment by TahaTesser** [comment]
Hi @kensuke-shimizu 
You're missing a `-` in command `flutter doctor --android-licenses`
Please execute `flutter doctor --android-licenses`


Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
