### ISSUE TITLE
Flutter:Localizations for app name in both android and IOs

### ISSUE THREAD

**Issue by praveen-francium** [flutter/flutter#56887]
@VladyslavBondarenko I can add localizations to change the texts in the app for android and ios but i dont know how to change the app name in android homescreen and IOS homescreen

**Comment by VladyslavBondarenko** [comment]
@praveen-francium 
Take a look at 'Localization of the App Title' paragraphs at https://www.gotut.net/flutter-dynamic-localization-tutorial/.
Closing since flutter_localizations isn't responsible for this,
if you disagree please write in the comments and I will reopen it
