### ISSUE TITLE
instead of sitting all the day coding i sit all the day fixing flutter problems !! , started to hate flutter guys even i have very very good application ..

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#56891]

**Comment by imeDevelopers** [comment]
where is google here ?!

**Comment by iapicca** [comment]
Hi @imeDevelopers 
this platform isn't meant for this kind of messages
closing

**Comment by imeDevelopers** [comment]
@iapicca
[This problem](https://github.com/flutter/flutter/issues/54557) makes me feel sick 🥴
