### ISSUE TITLE
With version flutter 1.17.0 Exhausted heap space, trying to allocate 8589934608 bytes, making my laptop stops responding

### ISSUE THREAD

**Issue by ShohidulProgrammer** [flutter/flutter#56903]
When I debug my app it says: Running Gradle task 'assembleDebug'...
after many time delay, it displays Exhausted heap space, trying to allocate 8589934608 bytes,
and making my laptop stops responding or hang the pc.

**Comment by soufi-43** [comment]
the same here .......... am struggling for over than a week and nothing found yet :(

**Comment by sampathbalivada** [comment]
Try executing
```
$ flutter clean
$ flutter create .
```
from your project directory.

**Comment by VladyslavBondarenko** [comment]
Hi @ShohidulProgrammer 
please follow up on https://github.com/flutter/flutter/issues/54420,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
