### ISSUE TITLE
Crash in SkCanvas.cpp - Line 617

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#56900]
We have 1 device that gets this crash very often. It's an iPhone X, running iOS 11.3.1.

No other device we have hits this crash, but we're not sure if we've had any other tests done an a different iPhone running iOS 11.3.1, so we're not sure if it's specific to the device, or the OS version or both.

It happens in a couple different flows of a pretty complicated app, so I cannot attach code, or even a sample app. But I do have the call stack:

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
std::__1::__function::__func<flutter::GPUSurfaceMetal::AcquireFrame(SkISize const&)::$_0, std::__1::allocator<flutter::GPUSurfaceMetal::AcquireFrame(SkISize const&)::$_0>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&)
```

```
0  Flutter                        0x104fe6678 std::__1::__function::__func<flutter::GPUSurfaceMetal::AcquireFrame(SkISize const&)::$_0, std::__1::allocator<flutter::GPUSurfaceMetal::AcquireFrame(SkISize const&)::$_0>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&) + 617 (SkCanvas.cpp:617)
1  Flutter                        0x104e94698 flutter::SurfaceFrame::~SurfaceFrame() + 1757 (functional:1757)
2  Flutter                        0x104e7fa2c flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) + 2339 (memory:2339)
3  Flutter                        0x104e8039c std::__1::__function::__func<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0, std::__1::allocator<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0>, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) + 268 (rasterizer.cc:268)
4  Flutter                        0x104e7fbcc flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) + 2649 (memory:2649)
5  Flutter                        0x104e862a0 std::__1::__function::__func<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_29, std::__1::allocator<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_29>, void ()>::operator()() + 104 (ref_ptr.h:104)
6  Flutter                        0x104bd8dd8 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 116 (ref_ptr.h:116)
7  Flutter                        0x104bdaa50 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 76 (message_loop_darwin.mm:76)
8  CoreFoundation                 0x184433aa8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
9  CoreFoundation                 0x18443376c __CFRunLoopDoTimer + 864
10 CoreFoundation                 0x184433010 __CFRunLoopDoTimers + 248
11 CoreFoundation                 0x184430b60 __CFRunLoopRun + 2168
12 CoreFoundation                 0x184350da8 CFRunLoopRunSpecific + 552
13 GraphicsServices               0x186333020 GSEventRunModal + 100
14 UIKit                          0x18e33178c UIApplicationMain + 236
```

**Comment by dannyvalentesonos** [comment]
[✓] Flutter (Channel dev, 1.18.0-11.0.pre, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.18.0-11.0.pre at /Users/danny.valente/Library/flutter/1.18.0-11.0.pre-dev
    • Framework revision 8568eda15b (6 days ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

**Comment by dannyvalentesonos** [comment]
Could this be a threading issue? Is the SurfaceFrame only ever accessed on the main thread? If it's also accessed on the gpu thread, then it could be setting submitted_ to false on another thread while the main thread is trying to submit again?

**Comment by dannyvalentesonos** [comment]
Interesting, after combing through all the code from that call stack using today's code in the master branch, everything looks like it's safe.
So I decided to check recent changes, and looks like this bug is fixed with #18154 based on my code inspection.
I'm going to use the latest dev release to verify and post back here.

**Comment by dannyvalentesonos** [comment]
Interesting, after combing through all the code from that call stack using today's code in the master branch, everything looks like it's safe.
So I decided to check recent changes, and looks like this bug is fixed with https://github.com/flutter/engine/pull/18154 based on my code inspection.
I'm going to use the latest dev release to verify and post back here.

**Comment by dannyvalentesonos** [comment]
Our crash does look to be fixed. I think we can close this.

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
