### ISSUE TITLE
flutter 1.17 doesn't recognize generated source (from 'flutter generate' command)

### ISSUE THREAD

**Issue by noelmansour** [flutter/flutter#56907]
## Steps to Reproduce

1. Follow steps found from the code generation wiki - https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter
2. Try running the app. There will be a compiler error.

This is a regression. It was working on flutter 1.12.13+hotfix.9

## Logs

```
Compiler message:
lib/main.dart:2:8: Error: Error when reading 'lib/example.dart': No such file or directory
import 'example.dart' as generated; // May not exist, it is okay!
       ^
lib/main.dart:57:13: Error: Method not found: 'GeneratedWidget'.
            generated.GeneratedWidget(),
            ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
```

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.17.0 at /Users/noel/dev/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Users/noel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/noel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android
      Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/noel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Reproduces with current dev ` 1.19.0-0.0.pre` as well.

**Comment by HansMuller** [comment]
CC @jonahwilliams

**Comment by jonahwilliams** [comment]
The fix is to always use build_to: source, but the example code hasn't been updated

**Comment by noelmansour** [comment]
@jonahwilliams Thanks for the response. Is there a reason that `build_to: cache` can't be used instead?

With `build_to: cache`, cleaning generated files is covered by `flutter clean`. With `build_to: source`, it is not. This makes cleaning the generated files slightly more cumbersome.

**Comment by jonahwilliams** [comment]
The support for automatic build to cache requiried changing the filesystem roots in the compiler, which turned out to break debugging in IDEs.

A better alternative is not to use builders and all and use build_runner directly. That is capable of cleaning from the source directory via pub run build_runner clean

**Comment by noelmansour** [comment]
Thanks for the quick response. I'll switch to using `build_runner`.

But do you mind clarifying your comment [here](https://github.com/flutter/flutter/issues/27141#issuecomment-487737904)? It seemed to suggest that `dev_dependencies` (where `build_runner` is added as a dependency) was being overloaded and that `builders` was going to deal with that overload.

**Comment by jonahwilliams** [comment]
Obsolete by https://github.com/flutter/flutter/issues/61508, was some more context on the removal of flutter generate. Specifically, I recommend using `pub run build_runner` instead, as this will have the best workflow going forward.
