### ISSUE TITLE
Regression in flutter_gallery__back_button_memory

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56904]
https://github.com/flutter/flutter/issues/54995 notes that it's flaky, so I'm not sure what to do with this one. 

Looks like either https://github.com/flutter/flutter/pull/56611 or https://github.com/flutter/flutter/pull/56689, but it's been slowly climbing for a while.

**Comment by chunhtai** [comment]
I remembered i have looked into this one before but cannot really figure out what has caused it https://github.com/flutter/flutter/issues/49753

**Comment by jason-simmons** [comment]
This benchmark is primarily intended to check whether the engine is leaking major objects after a series of app suspend/resume cycles.  Small changes in the results are typically not significant.

**Comment by chunhtai** [comment]
I seems like the flutter_gallery__back_button_memory start-max is constantly red. if the test is about memory leaking between the app suspend/resume cycles, should we re-baseline the flutter_gallery__back_button_memory start-max?

**Comment by Hixie** [comment]
Yes, please rebaseline if there is just a slow rise. We should also actively work on reducing the memory usage though.

**Comment by chunhtai** [comment]
re-baselined
