### ISSUE TITLE
[Desktop] Navigate back with mouse back button

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#56919]
## Use case

At the moment it is not possible to navigate back (`Navigator.pop()`) with a mouse back button on macOS, Windows and Linux. Flutter web is able handle the mouse back button 👍 

![image](https://user-images.githubusercontent.com/24459435/81587407-48543d80-93b7-11ea-9c11-bcfbfa72ecca.png)

## Proposal

If you press the mouse back button, Flutter should call `Navigator.pop()`

This question is: Should it also be possible to use the forward button?

**Comment by sampathbalivada** [comment]
Hey @AndroidNils, can you please specify any Native applications (Not built into the OS) which successfully implement the said behaviour? It would be nice to have a reference as Navigation on desktop applications is in most cases mapped to on-screen buttons of the application.

**Comment by AndroidNils** [comment]
@sampathbalivada Discord and Slack support mouse button navigation. You can undo and redo every navigation action (back and forward navigation).

**Comment by stuartmorgan** [comment]
> At the moment it is not possible to navigate back (Navigator.pop()) with a mouse back button on macOS, Windows and Linux.

Are you saying you're not able to detect those buttons with gesture handlers on any desktop platform? Sample code and what you're getting on macOS and Windows would be helpful. (For Linux, see https://github.com/flutter/flutter/issues/33220).

> If you press the mouse back button, Flutter should call `Navigator.pop()`

Generally speaking (maybe there are exceptions) mice don't have "back" and "forward" buttons, they have additional buttons that are subject to application-specific interpretation. For instance, the Win32 API names for those buttons (unless there's a driver doing something specific) would be XBUTTON1 and XBUTTON2. Determining their meaning is something that should be done at the application level, not the framework level.

**Comment by AndroidNils** [comment]
> Determining their meaning is something that should be done at the application level, not the framework level.
@stuartmorgan Ok, thanks for your explanation! I'm going to close this issue 👍

**Comment by sampathbalivada** [comment]
Just in case it helps in building something somewhere, Discord and Slack are built using Electron. They're essentially headless Chrome instances running as Applications. That might be the reason for the functionality being available.
