### ISSUE TITLE
DropdownButtonFormField is crashing app if value property contains a value that exist in the list of items

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#56929]
`DropdownButtonFormField `is crashing app if `value `property contains a value that exist in the list of items.

## Steps to Reproduce
1. Run the code bellow.
2. Tap the FloatingActionButton 10 times

**Expected results:** App does not crash

**Actual results:** App is crashing

Found in latest Flutter version: `1.17.0`

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<int> myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
  int currentNumber = 1;

  void _incrementCounter() {
    setState(() {
      _counter++;
      currentNumber = _counter;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            DropdownButtonFormField<int>(
              value: currentNumber,
              items: myList.map((int value) {
                print(value);
                return DropdownMenuItem<int>(
                  value: value,
                  child: Container(
                    width: 200,
                    child: Text(
                      value.toString(),
                    ),
                  ),
                );
              }).toList(),
              onChanged: (int newValue) {
                setState(() {
                  currentNumber = newValue;
                });
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by shihaohong** [comment]
Hi @pedromassango, this is expected, since none of the items passed into `DropdownButtonFormField.items` contain the `value` passed into `currentNumber`. An assert was introduced that prevents developers from passing in a value that isn't listed in `items`, since it does not make sense to select an item that isn't present in the dropdown items list.

I will close the issue for now, but feel free to reopen this issue if you think that this behavior is unwanted for any reason.

**Comment by pedromassango** [comment]
I understand. I thought the value passed in "value was mean to be a value that exist in the items so that the widget knows which one is selected by default!

I think of this as the Bottom navigation bar pattern: current Item (or currentIndex I don't remember the param name for now) is supposed to start with the index that will be selected by default, is that right?

**Comment by pedromassango** [comment]
I think I get you know. So it crash because "value is 10 and list does not have the element 10. Thanks
