### ISSUE TITLE
Add a ColorFilter widget

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5692]
I want to be able to turn a given widget into a certain color similar to how you can do this with Images.

**Comment by Hixie** [comment]
Probably means exposing SceneBuilder.pushColorFilter.
We should probably have a generic way to let you push a custom Layer, actually...

**Comment by eseidelGoogle** [comment]
@apwilson would kinda like to have this, but it's not high priority.

**Comment by sethladd** [comment]
Moving to M3 if not a high priority.

**Comment by Hixie** [comment]
We have pushColorFilter now, so this is just a matter of adding a widget. This should be relatively simple to do. It is not on our short-term priority list.

**Comment by jonahwilliams** [comment]
Took a look at this today and ran into the issue fixed in https://github.com/flutter/engine/pull/4782. Going to work on some M3 bugs in the meantime

**Comment by Patte1808** [comment]
Hey,

I'm not sure whether I understand the issue correct, but I wanted to dig a bit deeper into the Flutter rendering stuff and tried working on something like that.

Would my implementation of a `ColorFilterWidget` be sufficient for this issue, or is this issue about something else?

You can see [my implementation here](https://github.com/Patte1808/flutter_color_filter_widget/blob/master/lib/widget/color_filter_widget.dart)

I also [provided an example](https://github.com/Patte1808/flutter_color_filter_widget/blob/master/lib/main.dart) in case you're interested.

Had fun working on it, not sure how useful it is or whether it can solve this issue. :D

**Comment by lethehaiau** [comment]
I think SceneBuilder.pushColorFilter should receive colorfilter to support colorfilter.matrix

**Comment by dnfield** [comment]
@lethehaiau I've broken that out into #35415

**Comment by collinjackson** [comment]
I also wrote a `ColorFiltered` widget when investigating #35415 before I found this bug; it is similar to Patte1808's ColorFilterWidget. Here's the code for it in case it's useful to someone.

https://gist.github.com/collinjackson/49c77ab2f68275e68f12e481c52eefd0

**Comment by dnfield** [comment]
customer: octopod wants this.

**Comment by dnfield** [comment]
Thanks @collinjackson  - I independently arrived at very similar code, incorporated some similarities in the linked PR
