### ISSUE TITLE
my released app don't work like when i'm debugging 

### ISSUE THREAD

**Issue by dfourcfive** [flutter/flutter#56939]
### Hello flutter community

**I'm having an issues which can't find a solution for it 
my app is very simple which does call an  API 
it worked fine and as i expected when i was in the debugging mode
but when i tried the release mode it didn't work at all (the UI is there but no API calls)

i tried "flutter clean" after the releasing and got nothing**

**Comment by sampathbalivada** [comment]
If you're building for Android, check for internet permission. In debug mode, internet permission is added to your application. While building an application you need to add a permission to AndroidManifest.xml

```
<manifest xlmns:android...>
 ...
 <uses-permission android:name="android.permission.INTERNET" />
 <application ...
</manifest>

```

If this resolved your problem, consider closing the issue or add more details to better understand your problem.
