### ISSUE TITLE
Ternary operators not being formatted like they are in the widgets in VS Code

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#56948]
## Steps to Reproduce

I have a getter in my model, in model.dart that (intelliJ I guess) formats like this:
<img width="735" alt="Captura de pantalla 2020-05-11 a las 22 23 33" src="https://user-images.githubusercontent.com/25743901/81613304-1f8f7080-93d6-11ea-9c1a-5171827c5b50.png">
instead of like this:
<img width="393" alt="Captura de pantalla 2020-05-11 a las 22 29 12" src="https://user-images.githubusercontent.com/25743901/81613713-d8ee4600-93d6-11ea-94d7-52d3520404be.png">

**Expected results:** 
IntelliJ formats nested ternary operators well in my widgets. Like this example in my main_screen.dart
<img width="501" alt="Captura de pantalla 2020-05-11 a las 22 25 44" src="https://user-images.githubusercontent.com/25743901/81613424-5cf3fe00-93d6-11ea-8f5c-449e2d0e92f3.png">

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-0.0.pre at /Users/tomas/Developer/flutter
    • Framework revision 053c38818f (4 days ago), 2020-05-07 15:22:03 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • iPhone 11 Pro • A85E0A78-987E-41EA-9676-E33AC01D746D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server    • web-server                           • web-javascript • Flutter Tools
    • Chrome        • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @tomasbaran 
following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter)
the correct way to address the problem
is to open an issue on the dedicated [GitHub](https://github.com/Dart-Code/Dart-Code/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it. 
Thank you for your understanding
