### ISSUE TITLE
App no longer launches on Android after upgrade to v1.17.0

### ISSUE THREAD

**Issue by isaacdov2** [flutter/flutter#56940]
After upgrading to v.1.17.0 The Android version crashes at launch with the following error:

W/FlutterEnginePluginRegistry( 8540): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@54ce920) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@4410108)

I have not found any posts online helping resolve the issue.  

Thanks.

######
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at  /development/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

######## MainActivity.java
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;

public class MainActivity extends FlutterActivity {
    private FlutterEngine flutterEngine;

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        this.flutterEngine = flutterEngine;
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }

    private Map<String, String> sharedData = new HashMap();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this.flutterEngine);

        handleSendIntent(getIntent());

        new MethodChannel(getFlutterEngine().getDartExecutor().getBinaryMessenger(), "-------------").setMethodCallHandler(
                new MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        if (call.method.contentEquals("--------")) {
                            result.success(sharedData);
                            sharedData.clear();
                        }
                    }
                }
        );
    }

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        handleSendIntent(intent);
    }

    private void handleSendIntent(Intent intent) {
        String action = intent.getAction();
        String type = intent.getType();

        if (Intent.ACTION_SEND.equals(action) && type != null) {
            if ("text/plain".equals(type)) {
          
            }
        }
    }

}

## Logs

```
```

```
```

**Comment by mohdkhmais** [comment]
i am having the same in debug mode it works but in release mode Crash on start

**Comment by TahaTesser** [comment]
Hi @isaacdov2  @mohdkhmais 
You need to move you method channel code into `configureFlutterEngine`  from [Add an Android platform-specific implementation](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab#step-3-add-an-android-platform-specific-implementation), 

Don't forget to add `super.configureFlutterEngine(flutterEngine);` from [this comment](https://github.com/flutter/flutter/issues/56674#issuecomment-626561147)

```
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "samples.flutter.dev/battery";

  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
        .setMethodCallHandler(
          (call, result) -> {
            // Note: this method is invoked on the main thread.
            // TODO
          }
        );
  }
}

```
Let this follow this resolves your issue
I tried the official example to get battery level and it works  
Thank you

**Comment by isaacdov2** [comment]
Hi @TahaTesser @mohdkhmais 

Thanks for reaching out.  After a bit of trial and error I narrowed the issue down to calling 
GeneratedPluginRegistrant.registerWith( ) in both configureFlutterEngine and onCreate.
Calling GeneratedPluginRegistrant.registerWith( ) in both methods was not an issue in v1.12, but v1.17 throws an error.

FYI, calling super.configureFlutterEngine(flutterEngine) and GeneratedPluginRegistrant.registerWith( ) will generate the same error.
