### ISSUE TITLE
Fuchsia tests aren't being run on  the framework CI

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#56944]
Fuchsia tests aren't being run as part of post submits, for some reason they are failing with "Success: Infra Failure Result for None" which is causing them to show up as green in the dashboard. https://ci.chromium.org/p/flutter/builders/prod/Linux/12021 . https://chromium-swarm.appspot.com/task?id=4c15a16142982e10 is a failure though
the last "task UI", so I would expect this to show up as a failure at least.

The same thing seems to be going on in the engine builds as well
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/3679 for example. These haven't been running for a while.

Marking this as TODAY since we don't have any signal on whether things are broken on Fuchsia or not.

cc: @godofredoc , @gw280

**Comment by godofredoc** [comment]
The UI is fixed on this CL https://flutter-review.googlesource.com/c/recipes/+/2681

**Comment by gw280** [comment]
cc @arbreng, who was running into this earlier today.

**Comment by godofredoc** [comment]
A second CL I forgot to set the parameter: https://flutter-review.googlesource.com/c/recipes/+/2682

**Comment by godofredoc** [comment]
I'll need one more fix in the display_tasks module. When tasks are cancelled or killed the result is empty and the name of the step is None

**Comment by Hixie** [comment]
(assigned a milestone since this had an assignee but no milestone; please update it as appropriate.)

**Comment by Hixie** [comment]
(removing assignment since it's been in the Overdue milestone for a month)

**Comment by godofredoc** [comment]
obsolete.
