### ISSUE TITLE
plugin_tools expects iOS and Android in example

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#56953]
Currently `plugin_tools` tries to drive every example app unconditionally for iOS and Android. This means that a `*_macos`, `*_linux`, etc. federated plugin package needs to have `example/ios/*` and `example/android/*` even though it doesn't implement them, or tests will (pointlessly) fail. See https://github.com/flutter/plugins/pull/2589 for an example.

We should make the tooling check the (local, not app-facing) plugin's supported platforms for mobile as we do for desktop. We'll need to either retool the is-platform-x-supported check to understand the legacy `plugin:` section in `pubspec.yaml`, or ensure that all plugins in flutter/plugins are using the new schema (the latter may already be done, I'm not sure offhand if it was done comprehensively).

**Comment by stuartmorgan** [comment]
https://github.com/stuartmorgan/plugin_tools/pull/new/dont-require-ios-android-examples is the first half of a PR to fix it. It prevents building, but doesn't prevent driving, so won't work as-is. I haven't had time to dig into how to prevent the drive step from happening since the logic is less obvious there, so if someone is interested in taking on the second part they are welcome to take it over. (If not, I'm not sure when I'll be able to get back to this.)

**Comment by cyanglaz** [comment]
@stuartmorgan I'm planning to work on the drive part. The link points to a on merged PR, do you want to land your PR? Does it require something else to land first?

**Comment by cyanglaz** [comment]
Fixes on the tools are landed in https://github.com/flutter/plugin_tools/pull/102. Closing the issue.
