### ISSUE TITLE
Request for API docs for custom multi-child layouts

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5695]
(Filing on behalf of a user.)

"Suggest that Flutter's API docs for custom multi-child layouts mention layout IDs."

**Comment by sethladd** [comment]
cc @apwilson

**Comment by apwilson** [comment]
Right: https://docs.flutter.io/flutter/material/CustomMultiChildLayout-class.html Doesn't mention that it's children should/must/could be LayoutIds.
