### ISSUE TITLE
mylocationbuttonenabled set to true but no button

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#56967]
hi. 

mylocationbuttonenabled and mylocationenabled are true
but the mylocation button is not shown in the map

**Comment by TahaTesser** [comment]
Hi @chitgoks 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by chitgoks** [comment]
hi thank you for getting back. i am closing this issue.

it seems that the button will only appear if you accepted the permissions.

i was expecting the button to be always visible and show the permission once the user clicks on the button.
