### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/Oliver/Documents/ComputerScience/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by Kuro-Tatsu** [flutter/flutter#56970]
## Command
```
flutter assemble --output=/Users/Kuro_Tatsu/Documents/ComputerScience/Crossplatform/CreditReunion/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/Kuro_Tatsu/Documents/ComputerScience/Crossplatform/CreditReunion/lib/main_dev.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. flutter run --debug --flavor development -d iphone_11 -t lib/main_dev.dart
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/Kuro_Tatsu/Documents/ComputerScience/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale fr-RE)
    • Flutter version 1.17.0 at /Users/Kuro_Tatsu/Documents/ComputerScience/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kuro_tatsu/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/kuro_tatsu/Library/Android/sdk
    • Java binary at: /Applications/Programming/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Programming/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 9B67A02F-97B4-455F-88EF-4EBBEC0E27EC • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.11+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
### Plugins
cloud_firestore-0.13.5
cloud_firestore_web-0.1.1+2
connectivity-0.4.8+2
connectivity_macos-0.1.0+2
device_info-0.4.0+1
firebase_analytics-5.0.11
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_database-3.1.5
firebase_storage-3.1.5
flutter_plugin_android_lifecycle-1.0.7
google_maps_flutter-0.5.27+1
google_sign_in-4.4.4
google_sign_in_web-0.9.1
keyboard_visibility-0.5.6
libphonenumber-1.0.1
path_provider-1.6.7
path_provider_macos-0.0.4+1
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+7
shared_preferences_web-0.1.2+4
sqflite-1.3.0
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+2
webview_flutter-0.3.20+2

**Comment by TahaTesser** [comment]
Hi @Kuro-Tatsu 
Please take a look at this [solution](https://github.com/flutter/flutter/issues/45329#issuecomment-572683413)
if problem persist after trying the solution,  can you please provide your  `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Kuro-Tatsu** [comment]
Hi @TahaTesser, Thanks for your answer but this solution don't work for me. I don't have the executable gen_snapshot_x86_64 in the folder flutter/bin/cache/artifacts/engine/ios-release/ even after delete bin/cache and execute flutter doctor.

**Comment by TahaTesser** [comment]
Hi @Kuro-Tatsu 
Can you please provide complete verbose from your command?
By executing `flutter run --debug --flavor development -d iphone_11 -t lib/main_dev.dart --verbose`
Thank you

**Comment by Kuro-Tatsu** [comment]
Hi @TahaTesser
I upgraded flutter to 1.17.1 version. I deleted ios folder and recreate with `flutter create .`.
I added my config and move my Firebase folder for multiple flavors at the root of the project.
Today it run with flutter command and xcode. 
Thanks you for your help.

**Comment by TahaTesser** [comment]
Hi @Kuro-Tatsu 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
