### ISSUE TITLE
verision solving failed between flutter_driver and path 

### ISSUE THREAD

**Issue by prajwal27** [flutter/flutter#56978]
## Steps to Reproduce

1. Open flutter/examples/platform_channel
2. `flutter pub get`

## Logs
![issue](https://user-images.githubusercontent.com/31249460/81655609-fc0b0b00-9453-11ea-900d-3c32aaa85821.png)

## flutter doctor -v
![issue11](https://user-images.githubusercontent.com/31249460/81656038-52784980-9454-11ea-8ffb-d660bb21e486.png)

**Comment by TahaTesser** [comment]
Hi @prajwal27 
Please use `path 1.6.4` until other packages gets updated
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
