### ISSUE TITLE
Loaded Image.network memory is never released

### ISSUE THREAD

**Issue by ciscolxh** [flutter/flutter#56988]
在加载图片过程中，加载图片后内存一直不降低。
![image](https://user-images.githubusercontent.com/18440200/81670971-fe349000-947a-11ea-8033-8b56c4f295c8.png)
Dart Tool检查都在External中不释放，点GC无效。
@kangwang1988

**Comment by TahaTesser** [comment]
Dart Tool jiǎnchá dōu zài External zhōng bù shìfàng, diǎn GC wúxiào.
Translated description
Dart Tool checks are not released in External, and GC is invalid.

**Comment by ciscolxh** [comment]
Translated description is right
[✓] Flutter (Channel master, v1.18.0-6.0.pre.2, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.18.0-6.0.pre.2 at /Users/macman/flutterSDK/flutter
    • Framework revision 8892ba4bbc (4 weeks ago), 2020-04-12 21:35:01 -0400
    • Engine revision cc7d2857a9
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 8ef508ba36)

**Comment by ciscolxh** [comment]
**examples**
`
@override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: widget.count,
        crossAxisSpacing: 5,
        mainAxisSpacing: 5,
        childAspectRatio: 1,
      ),
      itemCount: (allImage.length ?? 0),
      itemBuilder: (BuildContext context, int index) {
        return Image.network(
          allImage[index],
          fit: BoxFit.cover,
          headers: {'Authorization': widget.header},
          key: ObjectKey(allImage[index]),
        );
      },
      shrinkWrap: true,
      physics: NeverScrollableScrollPhysics(),
      padding: EdgeInsets.only(top: 0),
    );
  }
`
This widget is ListView item.
If I browse more image
Dart Tool checks are not released in External, and GC is invalid.

**Comment by TahaTesser** [comment]
Not sure if this is an issue but when making changes in code and saving the code, External is stop working anymore. Dev tool have to be restarted to work it again

**Comment by ciscolxh** [comment]
I use Image.network (), the program external memory is not released until the program error

**Comment by TahaTesser** [comment]
Hi @ciscolxh 
Please answer the above [question](https://github.com/flutter/flutter/issues/56988#issuecomment-629528318)
Thank you

**Comment by ciscolxh** [comment]
loaded Image.network memory is never released

**Comment by TahaTesser** [comment]
There is a nweer issue with reproducible steps 
Closing in favor of https://github.com/flutter/flutter/issues/62107

**Comment by cimsunf0702** [comment]
Please see this: https://github.com/flutter/flutter/issues/62107#issuecomment-859990619
