### ISSUE TITLE
keyboard prediction text is not showing in webview_flutter ios.

### ISSUE THREAD

**Issue by uc-dve** [flutter/flutter#56982]
Predictive text is not showing in keyboard in ios webview it is working fine in android.
Please refer to following video link.
https://www.screencast.com/t/UGGahRneFSF

**Comment by TahaTesser** [comment]
Hi @uc-dve 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by uc-dve** [comment]
Thanks for your quick response.

**Flutter doctor -v**


[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/ucertify/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ucertify/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone 8 • F01E5554-E39F-447B-8BA3-4A2480C2025D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.


**Code Sample =>**

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Stack(
          fit: StackFit.expand,
          overflow: Overflow.clip,
          children: <Widget>[
            WebView(
              debuggingEnabled: true,
              initialUrl: "https://www.google.co.in",
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                _controller.complete(webViewController);
                _webviewController = webViewController;
                //  _webviewController.clearCache();
              },
              
              onPageStarted: (String url) {},
              onWebResourceError: (err) {
              //  UC.simpleDialog("On error", "${err.description }  ${err.errorCode}", null);
              },
              onPageFinished: (String url) {
                setState(() {
                  _isLoadingPage = false;
                });
              },
            ),
            _isLoadingPage
                ? Container(
                    alignment: FractionalOffset.center,
                    child: 
                      Container(
                          height: 200,
                          width: 200,
                          alignment: FractionalOffset.center,
                          child: CircularProgressIndicator(
                            backgroundColor: Colors.white,
                          ))
                  )
                : SizedBox(),
          ]),
      floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
      floatingActionButton: buildSpeedDial(),
    );
  }
```

**Comment by TahaTesser** [comment]
### iOS 
![Simulator Screen Shot - iPhone 11 - 2020-05-15 at 13 25 10](https://user-images.githubusercontent.com/48603081/82026005-be0a2300-96af-11ea-8b69-855b1a0703b4.png)


### Android

![Screenshot_1589528826](https://user-images.githubusercontent.com/48603081/82026025-c3676d80-96af-11ea-96bc-b2968b38d04a.png)
 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (4 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (5 available)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.4.1
    • iPhone 11     • B00B6F4E-B1CE-44F3-B81E-3EC6D639B008 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS         • macOS                                • darwin-x64     •
      Mac OS X 10.15.4 19E287
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 81.0.4044.138

• No issues found!
``` 

</details>

**Comment by cjamcu** [comment]
I have this error too. What is the solution ? . @TahaTesser  What version of webview_flutter you use ?

**Comment by TahaTesser** [comment]
Hu @uc-dve  @cjamcu 
Looking at it again, this is working as expected you don't see keyboard prediction in Safari when you search on Google.
![IMG_A76E25C81796-1](https://user-images.githubusercontent.com/48603081/105506462-15a56780-5cf0-11eb-9bbd-4bc4c7468d1c.jpeg)

Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
