### ISSUE TITLE
DropdownButtonFormField completele break after 1.17!!!

### ISSUE THREAD

**Issue by louia** [flutter/flutter#56983]
When you try to pass an instance to DropdownButtonFormField<...>, you canno't change the selected value of the DropdownButtonFormField by setstate in the code. 

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @louia 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by HansMuller** [comment]
@shihaohong - is this related to https://github.com/flutter/flutter/issues/56716?

**Comment by VladyslavBondarenko** [comment]
@louia 
please follow up on https://github.com/flutter/flutter/issues/56898, https://github.com/flutter/flutter/issues/56716,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it

**Comment by louia** [comment]
@VladyslavBondarenko Yes, exactly ! 
Thanks
