### ISSUE TITLE
Back button integration with 3rd party Android libraries?

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#5698]
Hello,

I have created a full dart material application based on the pesto sample. In this application, I push several statefulwidget, fullscreendialog, classic dialog and have a drawer in a scaffold.
When I navigate in the application, every thing works fine in Android, a push on the back button close the drawer, close a dialog or come back to the previous view as expected.

Then, I have added an Android activity with a flutter view to use a third party library. This activity do not override the onBackPressed method.

When I launch the application with this new "native" part, a press on the back button close the application and the expected behavior doesn't work any more.

Is there a way to keep the normal behavior even with the use of a native part in the application?

I have tried to override the onBackPressed method in the activity and send a message to the dart part with the flutterView but it's not very beautiful and some parts are tricky.

Thank you for your help!

Vincent

**Comment by eseidelGoogle** [comment]
@jason-simmons @Hixie

**Comment by jason-simmons** [comment]
If you call FlutterView.popRoute() on a press of the back button, then WidgetsBinding.handlePopRoute() will pop a route if one is on the navigation stack.  If the stack is empty, then it will call finishCurrentActivity() on the Flutter activity service, which will finish the current Android activity.

@hixie: is there any way to override handlePopRoute?

**Comment by Hixie** [comment]
I'm not sure I really understand the scenario here. Are we talking about going flutter->flutter->android and then hitting back? Or android->android->flutter and then hitting back?

**Comment by Hixie** [comment]
We can provide a hook that fires when we're about to call finish activity, which asks whether to actually do that, if that would help, assuming we're talking about the android->flutter case. In the flutter->android case I don't really understand the problem.

**Comment by lequem** [comment]
For my scenario, the call to FlutterView.popRoute() do the job. Thank you very much.
For the hook, I don't think it would be necessary in my case. 
Thank you again,

Vincent

**Comment by b-cancel** [comment]
I'm posting this here in case anyone out there finds this and wishes they would find a simple example
https://gist.github.com/b-cancel/0ca372017a25f0c120b14dfca3591aa5
