### ISSUE TITLE
[Feature request] Set min and max hour in CupertinoDatePicker

### ISSUE THREAD

**Issue by castrovictor** [flutter/flutter#56987]
## Use case

Currently, it is possible to set a min and max date in the [CupertinoDatePicker](https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html). The problem is it is not possible to set a min and max for the hour. The user case:
I have an app to handle events. I can set when the event starts and the deadline to join the event, which is obviously before the event starts. If I want to set the deadline the same day as the event starts, but few hours later, I can put a restriction on the date, bot not in the our. 
Therefore, it would be possible to set the deadline few hours later than the event starts. I can manually check it an display an error message, but not giving the option to set a wrong hour would be super helpful.

## Proposal

The same way to can set min and max date, being able to handle the exact hour. Right now, the picker does not handle hours. 

Hope it is clear, otherwise let me know and I will explain as better as possible. And thanks to Eric Seidel for [suggesting me to post a feature request](https://twitter.com/_eseidel/status/1259482389148954628?s=20), I had no idea about this section.

**Comment by castrovictor** [comment]
It seems to be implemented in the new version of Flutter. If anyone could confirm, apart from me, it would be great

**Comment by LongCatIsLooong** [comment]
`minimumDate` & `maximumDate` should work in `CupertinoDatePickerMode.time` mode now. The API docs are misleading. Opened https://github.com/flutter/flutter/pull/57534 to update the documentation.
