### ISSUE TITLE
Regression: Floating Action Button (FAB) notch margin does not show content of body on scroll

### ISSUE THREAD

**Issue by radeksvarz** [flutter/flutter#56985]
Regression of #17555 

Regression in [√] Flutter (Channel master, 1.19.0-1.0.pre.26, on Microsoft Windows [Version 10.0.18362.778], locale en-150)

when Scaffold's extendBody is set to true

![image](https://user-images.githubusercontent.com/6020891/81629022-74e17700-9402-11ea-9c72-7e2713a10145.png)

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
Thanks for the report. 

I am unable to reproduce the problem using the tip of master on macOS with the sample app below. Can you provide a sample test app that shows your issue? 

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MainApp());

class MainApp extends StatefulWidget {
  @override
  _MainAppState createState() => new _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Test',
      home: new Scaffold(
        body: new Container(
          color: Colors.purple,
        ),
        extendBody: true,
        bottomNavigationBar: new BottomAppBar(
          shape: CircularNotchedRectangle(),
          color: Colors.grey,
          child: new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(icon: Icon(Icons.menu), onPressed: () {},),
              IconButton(icon: Icon(Icons.search), onPressed: () {},),
            ],
          ),
        ),
        floatingActionButton: new FloatingActionButton(
          onPressed: null,
          child: new Icon(Icons.add),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      ),
    );
  }
}
```

**Comment by radeksvarz** [comment]
I just tested the sample in AS and the sample behaves correctly. 

Flutter (Channel master, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-150)

In fact analyzing my code I found that the root cause is when using SafeArea. Which I assume is the correct behavior. My apologies.

Here is the sample demonstrating "issue" when using SafeArea:

```
import 'package:flutter/material.dart';

void main() => runApp(new MainApp());

class MainApp extends StatefulWidget {
  @override
  _MainAppState createState() => new _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Test',
      home: new Scaffold(
        body: SafeArea(
          child: new Container(
            color: Colors.greenAccent,
          ),
        ),
        extendBody: true,
        bottomNavigationBar: new BottomAppBar(
          shape: CircularNotchedRectangle(),
          color: Colors.grey,
          child: new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(icon: Icon(Icons.menu), onPressed: () {},),
              IconButton(icon: Icon(Icons.search), onPressed: () {},),
            ],
          ),
        ),
        floatingActionButton: new FloatingActionButton(
          onPressed: null,
          child: new Icon(Icons.add),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      ),
    );
  }
}
```

**Comment by radeksvarz** [comment]
Info for others if dealing with the similar issue:

SafeArea nullifies the extendBody.

extendBody in fact extends the body behind the whole height of the bottomNavigationBar widget.

I.e. that in such case the longer body content will be effectively hidden under the BottomAppBar.

This also applies for the child of the SingleChildScrollView used for the scrollable body content.

The workaround is to add spacing Container at the end of the body's or SingleChildScrollView's child with the height of at least the BottomAppBar height.

The issue can be closed.

**Comment by lednhatkhanh** [comment]
@radeksvarz Do you have any example code on how to solve this with SafeArea? Thank you.
