### ISSUE TITLE
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE

### ISSUE THREAD

**Issue by satyam-11** [flutter/flutter#56993]
here i am unable to load images in my application 
kindly help asap
I have gone through the documentation a few times I couldn't find any problem so far 
I have also checked yamil.lint , it says its a valid yaml file

![imagecode](https://user-images.githubusercontent.com/45712147/81685806-d68ef900-9475-11ea-9b22-fc7c40a0ad24.png)
![yaml](https://user-images.githubusercontent.com/45712147/81685820-d7c02600-9475-11ea-806d-c0cfba2aa6e4.png)
![doctor](https://user-images.githubusercontent.com/45712147/81685828-d858bc80-9475-11ea-9292-9a0f23c50f96.png)
![error](https://user-images.githubusercontent.com/45712147/81685832-d8f15300-9475-11ea-9564-3e599f4facf0.png)

**Comment by Mantton** [comment]
- Completely stop then restart your application.

**Comment by satyam-11** [comment]
tried that as well
tried disconnecting the device 
tried flutter clean

**Comment by TahaTesser** [comment]
Hi @satyam-11 
Please refrain from posting screenshots if not necessary, code sample is better
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you
