### ISSUE TITLE
Build apk failed when update to v1.17

### ISSUE THREAD

**Issue by Airoyee** [flutter/flutter#56991]
Run flutter build apk --verbose when update to v1.17,cant get resource from gooleapis.com:443.
Error Log:
Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.80] failed: connect timed out

**Comment by TahaTesser** [comment]
Hi @Airoyee 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by yuefeng007** [comment]
```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.15063], locale zh-CN)
    • Flutter version 1.17.0 at E:\flutterSdk\flutter
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\as
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • PAAM00 • b069dad6 • android-arm64 • Android 9 (API 28)
```

**Comment by yuefeng007** [comment]
same question

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
