### ISSUE TITLE
Accuracy callback on flutter sensors library

### ISSUE THREAD

**Issue by mrhabibi** [flutter/flutter#56997]
## Use case

Hi there! So I used to develop an app in Android and I'm now building my first app in Flutter, my app depends on accelerometer feature so much, that's one of my app's main feature.

As we know, accelerometer sometimes isn't really accurate and Android has a callback to let user knows that the accelerometer isn't accurate by giving accuracy number.

But I couldn't find this callback in [this library](https://pub.dev/packages/sensors), and I looked into the code and found [this line](https://github.com/flutter/plugins/blob/master/packages/sensors/android/src/main/java/io/flutter/plugins/sensors/StreamHandlerImpl.java#L38). The accuracy callback is ignored.

I've looked for alternatives but I got no luck.

## Proposal

Could you guys connect that callback to dart code so I can use it and do calibration when the accuracy goes bad? Because my app depends on that feature.

Any help will be appreciated :)

**Comment by stuartmorgan** [comment]
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).
