### ISSUE TITLE
Underlying widget isn't rebuilt after popping upper widget

### ISSUE THREAD

**Issue by jaygajjar40** [flutter/flutter#56998]
I have a file which include static variables 

class UserHelper {
        static String companyName="";
}

before 1.17 widget based on that static variable was updating like

Page 1 :
Text(UserHelper.companyName); 

when i was changing value through diffrent page like 

Page 2:
UserHelper.companyName="Test1";

and then when i was going back i could show "Test1" updated value in widget but now its not working in flutter 1.17, updating value to static variable isnt updating in widget ui based on that static variable

**Comment by VladyslavBondarenko** [comment]
Hi @jaygajjar40 

Provide please complete minimal reproducible code sample.

<details>
 <summary>With this code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class UserHelper {
  static String companyName="initial button text";
}

class FirstRoute extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text("First route"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text(UserHelper.companyName),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            UserHelper.companyName = "updated button text";
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

I couldn't get UserHelper.companyName updated with `stable v1.12.13+hotfix.9` as well

**Comment by jaygajjar40** [comment]
your example code is completely similar just different is : i used named route and both page extends StatefullWidget.

**Comment by VladyslavBondarenko** [comment]
Reproduced. With `v1.12.13+hotfix.9` underlying widget is rebuilt when popping upper widget. With current stable/beta isn't.

<details>
 <summary>updated code sample, the only change - use stateful widgets for pages instead of stateless</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class UserHelper {
  static String companyName="initial button text";
}

class FirstRoute extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<FirstRoute> {
  @override
  Widget build(BuildContext context) {

    print(UserHelper.companyName);

    return Scaffold(
      appBar: AppBar(
        title: Text("First route"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text(UserHelper.companyName),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            UserHelper.companyName = "updated button text";
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

**Comment by chunhtai** [comment]
cc @goderbauer is this related to the prevent not opaque routes to rebuild pr?https://github.com/flutter/flutter/commit/bc5ea0a05af5af67489a04cf580e4658a8214982#diff-43a0ab35160384e354368d926a0a96b8

**Comment by goderbauer** [comment]
The current behavior is correct. A StatefulWidget should only rebuild when its state changes, which is indicated by a call to setState. In your example, you are changing the State of the widget (by modifying `UserHelper.companyName`, but you're not calling setState. The framework doesn't know that the state has changed and therefore will not rebuild the widget. 

In previous versions this my have worked on accident, because we were rebuilding the widget even if you didn't call setState. However, that was a bug.

I would suggest injecting an instance of UserHelper into the widget tree via an InheritedWidget [1] that will rebuild the dependent widgets whenever its content changes.

[1] https://master-api.flutter.dev/flutter/widgets/InheritedWidget-class.html

**Comment by jaygajjar40** [comment]
setState(() {  
  UserHelper.companyName="New data"
});
From SecondRoute 

isn't working

**Comment by VladyslavBondarenko** [comment]
@jaygajjar40 
does it meet your need https://flutter.dev/docs/cookbook/navigation/returning-data?

**Comment by chunhtai** [comment]
this is how you will do it with inheritedwidget
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(UserHelper(
    child: MaterialApp(
      title: 'Navigation Basics',
      home: FirstRoute(),
    )
  ));
}

class UserHelper extends StatefulWidget {
  UserHelper({Key key, this.child}): super(key: key);

  final Widget child;

  static UserHelperState of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<_UserHelperScope>().state;
  }

  @override
  State<StatefulWidget> createState() {
    return UserHelperState();
  }

}

class UserHelperState extends State<UserHelper> {

  String get companyName => _companyName;
  String _companyName = "initial button text";
  set companyName(String other) {
    if (_companyName != other) {
      setState(() {
        _companyName = other;
      });
    }
  }
  @override
  Widget build(BuildContext context) {
    return _UserHelperScope(companyName, this, widget.child);
  }
}

class _UserHelperScope extends InheritedWidget {
  _UserHelperScope(this.companyName ,this.state, Widget child): super(child: child);
  final String companyName;
  final UserHelperState state;
  @override
  bool updateShouldNotify(_UserHelperScope oldWidget) {
    return oldWidget.companyName != companyName;
  }
}

class FirstRoute extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<FirstRoute> {
  @override
  Widget build(BuildContext context) {

    print(UserHelper.of(context).companyName);

    return Scaffold(
      appBar: AppBar(
        title: Text("First route"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text(UserHelper.of(context).companyName),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            UserHelper.of(context).companyName = "updated button text";
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

**Comment by cypie92** [comment]
im having the same problem after upgrading to version 1.17, my app heavily depend on webservice call, everytime i push to new page and add a new product by calling webservice i will need to refresh my product list page after navigator.pop,
currently i fixing this with 
`InkWell(
                            onTap: () async {
                              await Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => AddProductPage(
                                  ),
                                ),
                              );
                              setState(() {});
                            },
child: Text('Add')
)`

but i dont want to add this code in every page, i have check the inheritedwidget which made the code more messy since it required a variable to notify for every page

**Comment by liyang1518** [comment]
hi  you method is not work

**Comment by jaygajjar40** [comment]
@liyang1518  
No, its working 


Suppose You have a static class 
---------------------------------------------------------------------------------------
class GameHelper {
        static int score=0;
}


Code For FirstScreePage
------------------------------------------------------------------
result = await Navigator.pushNamed( context, "/second_page" );
setState(() {
GameHelper.score=GameHelper.score;
});


here 
`setState(() {
GameHelper.score=GameHelper.score;
});` 
will work

So the point is ....
Before 1.17 :  Updating static variable(using setState) was also updating a widget based on that static variable regardless of any screen.
but After 1.17 flutter update 

You can do this either by using 
- InheritedWidget  (as suggested by https://github.com/flutter/flutter/issues/56998#issuecomment-628765617 )  
OR   
- By adding above boilerplate code ( i got that idea from https://github.com/flutter/flutter/issues/56998#issuecomment-628690931)

i don't know why that functionality was deprecated after 1.17, but it was easy to use and reliable.

Some are saying to avoid use of static variable based widget so if you find a proper and easy way instead of above specified to achieve this thing please comment that tutorial. :)

**Comment by liyang1518** [comment]
> @liyang1518
> No, its working
> 
> ## Suppose You have a static class
> class GameHelper {
> static int score=0;
> }
> 
> ## Code For FirstScreePage
> result = await Navigator.pushNamed( context, "/second_page" );
> setState(() {
> GameHelper.score=GameHelper.score;
> });
> 
> here
> `setState(() { GameHelper.score=GameHelper.score; });`
> will work
> 
> So the point is ....
> Before 1.17 : Updating static variable(using setState) was also updating a widget based on that static variable regardless of any screen.
> but After 1.17 flutter update
> 
> You can do this either by using
> 
> * InheritedWidget  (as suggested by [#56998 (comment)](https://github.com/flutter/flutter/issues/56998#issuecomment-628765617) )
>   OR
> * By adding above boilerplate code ( i got that idea from [#56998 (comment)](https://github.com/flutter/flutter/issues/56998#issuecomment-628690931))
> 
> i don't know why that functionality was deprecated after 1.17, but it was easy to use and reliable.
> 
> Some are saying to avoid use of static variable based widget so if you find a proper and easy way instead of above specified to achieve this thing please comment that tutorial. :)








flutter 1.17 I don’t think this update is very good, the intention is to not refresh the page when the page pops, to improve efficiency. However, in many cases, there will be many subpages nested in the main page, which needs to be refreshed when popping. The method you improve not only increases the coding complexity, but also damages performance. My suggestion is it not possible to provide a boolean parameter when popping and let the user choose whether to refresh?

**Comment by krisssgirl** [comment]
I agree with liyang1518's boolean suggestion; it would make the problem so much easier to solve
