### ISSUE TITLE
Flutter doctor. Android Studio appears twice

### ISSUE THREAD

**Issue by TheSmurf38** [flutter/flutter#56995]
## Steps to Reproduce

Flutter et Dart sont bien installés comme plugings dans Android Studio mais ne sont pas reconnus (Flutter and Dart are well installed as plugings in Android Studio but are not recognized)

1. Je ne parvient pas à faire fonctionner flutter sur android studio, est ce que quelqu'un sait résoudre ce problème? 
(I can't get flutter to work on android studio, does anyone know how to fix this?)
2. ...
3. ...

## Logs

```
```

```
C:\Users\lucas>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [version 10.0.18362.778], locale fr-FR)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (1 year, 3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\lucas\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 29.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Android Studio
    • Android Studio at /my/local/path/for/android/studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = /my/local/path/for/android/studio
    X Android Studio not found at /my/local/path/for/android/studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

C:\Users\lucas>
```

**Comment by VladyslavBondarenko** [comment]
Hi @TheSmurf38 
your flutter version is obsolete, current stable version is 1.17.0, consider to upgrade.
Are you experiencing the issue with current stable (or another channel)?

**Comment by TheSmurf38** [comment]
Apres avoir telecharger la nouvelle version de flutter, je rencontre toujours ce meme problème. Pour etre sûr j'ai desinstaller le
Plugin sur android studio > redemarre l'AD. Réinstaller a nouveaux les plugins Flutter et Dart > restart l'AD. Toujours le meme soucis quand je run Flutter Doctor..
Bientot 24h que je lis des tutos sur comment me sortir de ce problème je commence a devenir fou ...

**Comment by jmagman** [comment]
@TheSmurf38 Can we get the output of `flutter doctor -v` after your upgrade?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by abhikumar63** [comment]
C:\Users\KIIT>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
[√] VS Code (version 1.53.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.


I am getting this problem can someone help me?

**Comment by jmagman** [comment]
Multiple `system\.homes`? 
https://github.com/flutter/flutter/blob/74bd7b6f6db6433783a36f94d9e43173745187f4/packages/flutter_tools/lib/src/android/android_studio.dart#L279-L283

```
X android-studio-dir = C:\Program
```
And not handling the space in the path?

**Comment by darshankawar** [comment]
The latest master version has different code snippet as compared to above, as `android_studio.dart` must have gone through lot of updates. Below is the relevant links currently:


https://github.com/flutter/flutter/blob/0ad71e87279345086b84cdee083375748b007e59/packages/flutter_tools/lib/src/android/android_studio.dart#L364

https://github.com/flutter/flutter/blob/0ad71e87279345086b84cdee083375748b007e59/packages/flutter_tools/lib/src/android/android_studio.dart#L237

https://github.com/flutter/flutter/blob/0ad71e87279345086b84cdee083375748b007e59/packages/flutter_tools/lib/src/android/android_studio.dart#L392

/cc @jmagman
