### ISSUE TITLE
Doc Request: how to construct and style "rich text"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5700]
It wasn't obvious how to create a highly stylized text in Flutter. For example, _how would I_ **render this kind of** _**text**_?  (Imagine that last word used a different font :)

Even some snippets inside the docs of https://docs.flutter.io/flutter/widgets/RichText-class.html and https://docs.flutter.io/flutter/material/Text-class.html might be sufficient.

Thanks!

**Comment by sethladd** [comment]
cc @Hixie if there's a good, small example of some techniques, I'd be happy to send over a PR to add to the API docs.

**Comment by Hixie** [comment]
Some examples:
examples/layers/widgets/styled_text.dart
examples/stocks/lib/stock_symbol_viewer.dart

Also see https://github.com/flutter/flutter/pull/5708

**Comment by Hixie** [comment]
Dup of https://github.com/flutter/flutter/issues/6559
