### ISSUE TITLE
How will flutter handle new Apple hardware and technologies ?

### ISSUE THREAD

**Issue by amiver** [flutter/flutter#57002]
How will flutter handle new Apple hardware and technologies like **Cryptokit** for blockchain, Core NFC framework, CoreML, **Create ML**, ARkit, Reality Kit, Reality Composer, HealthKit, all kinds of sensors and **AI Chip**.

**Comment by stuartmorgan** [comment]
The general answer to this question is [platform channels](https://flutter.dev/docs/development/platform-integration/platform-channels). Any new technology can be used directly, without it needing to be integrated directly into Flutter.

Closing as there does not seem to be a specific request here beyond the general question.

**Comment by amiver** [comment]
Thanks @stuartmorgan Sorry, i am new to flutter, didn't knew about platform channels..
