### ISSUE TITLE
How to solve this warning 

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#57008]
Invalid depfile: C:\Users\StreamerX\FlutterProjects\flash_chat\.dart_tool\flutter_build\464bc8431e20dcc3d6379bd5442ba115\kernel_snapshot.d

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

Could you also include the contents of `kernel_snapshot.d` ?

**Comment by SAMYAK99** [comment]
On running flutter - v

[√] Flutter (Channel dev, 1.19.0-0.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.19.0-0.0.pre at C:\flutter
    • Framework revision a849daf283 (5 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\StreamerX\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\StreamerX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
