### ISSUE TITLE
Gallery, Shrine: "see also" items at bottom of "view item" don't react to taps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5701]
User tests showed that some people were confused that they couldn't tap the "see also" items at the bottom of the "view item" page.

![screenshot__sep_1__2016_9_29_40_am__-_sethladd_google_com_-_google_com_mail](https://cloud.githubusercontent.com/assets/5479/18175591/bc6f7080-7026-11e6-9b15-e07388c13eae.png)

**Comment by Hixie** [comment]
This is specific to the old gallery, so closing. We're not going to fix bugs in the old gallery itself now that it's just a benchmarking target.
