### ISSUE TITLE
flutter doctor --android-licenses throws

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#57017]
## Steps to Reproduce
Unsure how it came to this state.  It doesn't bother me too much because I primarily target the web platform, but just thought I'd share for visibility.  Is it the OpenJDK I'm using perhaps?

The interesting part is the exception thrown when I run ```flutter doctor --android-licenses```

Windows 10.

Happy to provide any other information.

## Logs
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17763.1158], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
PS C:\Users\dad> flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
```

```
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17763.1158], locale en-US)
    • Flutter version 1.17.0 at h:\dev\flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\dad\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: H:\Apps\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at H:\Apps\AndroidStudio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by iapicca** [comment]
Hi @prujohn 
I see there's an open [issue](https://github.com/flutter/flutter/issues/56778
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by azzazkhan** [comment]
I was also tackling the same issue for an entire day. I searched on StackOverflow, GitHub, Medium and other sites to find the solution to this problem but the thing that worked for me was uninstalling Java JDK version 14 and reinstalling JDK version 8.
I don't want anyone to go through the same issue so I'm posting the detailed solution that worked for me.

When I executed the `flutter doctor` command in my CMD, the doctor showed me these summaries.
![Flutter error -1](https://user-images.githubusercontent.com/25636920/86488535-c0692f00-bd7a-11ea-992c-74b7e575163c.png)

I tried to run `flutter doctor --android-licenses` and `sdkmanager --licenses` to accept the license agreement but after executing both threw the same exception.
![flutter-sdkmanager-exception](https://user-images.githubusercontent.com/25636920/86489286-4e461980-bd7d-11ea-9bf4-e194eb10c6bc.png)

I also tried to revert back my Java installation but that created a total mess for me.

These are the Android Studio SDKs that I've installed. I've read in many articles and threads that API level 29 **Android 10.0 (Q)** must be installed so I downloaded it and the physical device I've connected to is running Android 9 (Pie) so I've downloaded that as well.
![Annotation 2020-07-03 220905](https://user-images.githubusercontent.com/25636920/86488588-e8f12900-bd7a-11ea-9be1-a40bb5466d6b.png)

I've downloaded and installed these SDK tools.
![Annotation 2020-07-03 220834](https://user-images.githubusercontent.com/25636920/86488589-ea225600-bd7a-11ea-8512-d2e007fb3e55.png)

After that, I've uninstalled my Java JDK version 14 installation and installed JDK version 8 and set the `JAVA_HOME` and `PATH` environmental variables and restarted my PC.
By doing so the `flutter doctor` showed these summaries.
![Annotation 2020-07-03 220332](https://user-images.githubusercontent.com/25636920/86489758-cb25c300-bd7e-11ea-977b-5b16d1b8c69c.png)

After running `flutter doctor --android-licenses` it showed these summaries.
![Annotation 2020-07-03 220432](https://user-images.githubusercontent.com/25636920/86489942-3a031c00-bd7f-11ea-9fd0-1b4d492f53e2.png)

![Annotation 2020-07-03 220453](https://user-images.githubusercontent.com/25636920/86490137-cf061500-bd7f-11ea-9287-2a46f8be75a5.png)

All these steps worked for me.
![Annotation 2020-07-03 220954](https://user-images.githubusercontent.com/25636920/86490160-e513d580-bd7f-11ea-8ee1-6b6b459e4c62.png)

**Comment by ev-harsh** [comment]
I've just downloaded and installed Android SDK Command-line tools from Android SDK Manager. That works for me!!!!

**Comment by Aminakazim** [comment]
Works fine after SDK Command-line tools installation.

**Comment by chinmoyrp** [comment]
Just like @ev-harsh and @Aminakazim, installing Android SDK command-line tools worked for me as well. So try it before attempting a jdk reinstall.

**Comment by PranavViswanathan** [comment]
So you need to uninstall the previously installed jdk?

**Comment by harrymaurya05** [comment]
Works fine after SDK Command-line tools installation.
Thank you

**Comment by fin-k** [comment]
Installing SDK command-line tools works, thanks.

**Comment by Anuj1224** [comment]
Thanks, Worked Fine After Installing "Android SDK command-line tools"

**Comment by swarupbhanjachowdhury** [comment]
Works fine after SDK Command-line tools installation.
Thank you

But now showing android studio not installed

**Comment by dungvuquoc** [comment]
> I was also tackling the same issue for an entire day. I searched on StackOverflow, GitHub, Medium and other sites to find the solution to this problem but the thing that worked for me was uninstalling Java JDK version 14 and reinstalling JDK version 8.
> I don't want anyone to go through the same issue so I'm posting the detailed solution that worked for me.
> 
> When I executed the `flutter doctor` command in my CMD, the doctor showed me these summaries.
> ![Flutter error -1](https://user-images.githubusercontent.com/25636920/86488535-c0692f00-bd7a-11ea-992c-74b7e575163c.png)
> 
> I tried to run `flutter doctor --android-licenses` and `sdkmanager --licenses` to accept the license agreement but after executing both threw the same exception.
> ![flutter-sdkmanager-exception](https://user-images.githubusercontent.com/25636920/86489286-4e461980-bd7d-11ea-9bf4-e194eb10c6bc.png)
> 
> I also tried to revert back my Java installation but that created a total mess for me.
> 
> These are the Android Studio SDKs that I've installed. I've read in many articles and threads that API level 29 **Android 10.0 (Q)** must be installed so I downloaded it and the physical device I've connected to is running Android 9 (Pie) so I've downloaded that as well.
> ![Annotation 2020-07-03 220905](https://user-images.githubusercontent.com/25636920/86488588-e8f12900-bd7a-11ea-9be1-a40bb5466d6b.png)
> 
> I've downloaded and installed these SDK tools.
> ![Annotation 2020-07-03 220834](https://user-images.githubusercontent.com/25636920/86488589-ea225600-bd7a-11ea-8512-d2e007fb3e55.png)
> 
> After that, I've uninstalled my Java JDK version 14 installation and installed JDK version 8 and set the `JAVA_HOME` and `PATH` environmental variables and restarted my PC.
> By doing so the `flutter doctor` showed these summaries.
> ![Annotation 2020-07-03 220332](https://user-images.githubusercontent.com/25636920/86489758-cb25c300-bd7e-11ea-977b-5b16d1b8c69c.png)
> 
> After running `flutter doctor --android-licenses` it showed these summaries.
> ![Annotation 2020-07-03 220432](https://user-images.githubusercontent.com/25636920/86489942-3a031c00-bd7f-11ea-9fd0-1b4d492f53e2.png)
> 
> ![Annotation 2020-07-03 220453](https://user-images.githubusercontent.com/25636920/86490137-cf061500-bd7f-11ea-9287-2a46f8be75a5.png)
> 
> All these steps worked for me.
> ![Annotation 2020-07-03 220954](https://user-images.githubusercontent.com/25636920/86490160-e513d580-bd7f-11ea-8ee1-6b6b459e4c62.png)

so good, im success, thank you, bro

**Comment by dantheman213** [comment]
Reinstalling using screenshots above worked for me. Thanks.

**Comment by s-mirzaee** [comment]
> JDK version 8

I had that issue. I remove jdk 15 and replace jdk 8 then i can see flutter licenses. Thank you

**Comment by hite77** [comment]
Also used jenv to switch to java 1.8 and it worked.  Was java 11 or newer.

**Comment by peter-waine** [comment]
+1 command line tools

**Comment by istomyang** [comment]
Summary: If you use linux like Fedora without AS, here is list:
- [ ] export PATH="$PATH:/mnt/data/android/platform-tools"  [1]
- [ ] export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac))))) [2]
- [ ] export ANDROID_SDK_ROOT=/mnt/data/android [3]
- [ ] openjdk_1.8 is irreplaceable [4] 

[1] You must download [Andorid SDK Command-line tools] and set `$PATH`.
[2] If you install openjdk like: `sudo dnf install java-1.8.0-openjdk.x86_64`
[3] If you want Flutter to use a different installation of the Android SDK, you must set ....
[4] `sudo dnf install java-1.8.0-openjdk-devel`

**Comment by prspaulo** [comment]
Thank very much, after installing the SDK command line works fine.

**Comment by azzazkhan** [comment]
@DumberSoft Run `flutter doctor --android-licenses` and press `Y` to accept each license. After all, licenses are accepted this error will be resolved.

**Comment by toxic-bishop** [comment]
Installing Android SDK Command Line Tool work for me.

**Comment by wdvictor** [comment]
> I've just downloaded and installed Android SDK Command-line tools from Android SDK Manager. That works for me!!!!

It worked for me too.

**Comment by inexuscore** [comment]
Setting up a fresh dev environment on a MacBook Pro, yup it was the CLI Tools, why aren't they installed with Android Studio haha. Thank you very much.

**Comment by VFiee** [comment]
Works fine after SDK Command-line tools installation.
Thank you

**Comment by exerror14** [comment]
[[Solved] flutter doctor –android-licenses gives a java error](https://fluttercorner.com/flutter-doctor-android-licenses-gives-a-java-error/)

**Comment by mdrijwan** [comment]
beautiful! works fine after SDK Command-line tools installation 💯
