### ISSUE TITLE
[macOS] Textfields should support CMD (⌘) + Backspace and Control + Backspace

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#57015]
## Use case
Normally macOS-Apps (or desktop apps in generell) support CMD (⌘) + Backspace and Control + Backspace in Textfields.

## Proposal
CMD (⌘) + Backspace: Delete Line
Control + Backspace: Delete word left to the cursor

![MacOSTextfieldKeys](https://user-images.githubusercontent.com/24459435/81720529-d0e9e100-947e-11ea-8556-d55daec0c115.gif)

**Comment by stuartmorgan** [comment]
This is one of many `NSStandardKeyBindingMethods` that hasn't been wired up yet in `FlutterTextInputPlugin`. It probably doesn't make sense to implement this until we've decided how much of this kind of logic will live in the framework vs. the engine though.

**Comment by justinmc** [comment]
This can be done in the framework now that https://github.com/flutter/flutter/pull/75032 is merged.  A PR is currently underway: https://github.com/flutter/flutter/pull/77172

**Comment by gspencergoog** [comment]
Reopening, since this was reverted in #79674
