### ISSUE TITLE
Gallery, Time picker: Does not respect system settings for 12hr and 24hr clock

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5703]
The gallery's display of time (in the time picker, for example) does not seem to respect the user's setting of a 24hr display preference. If the user chooses 24hr display, Flutter continues to use the same time picker, and appears to continue to render times with 12hr.

Also, when a user has chosen a 24hr display, the time picker changes behavior/appearance:

Here's what Android does if a 24hr display is selected. When trying to manually set the time:

![screen shot 2016-09-01 at 9 41 54 am](https://cloud.githubusercontent.com/assets/5479/18175963/57e610d6-7028-11e6-83c6-ae707d668e59.png)

**Comment by sethladd** [comment]
Tested on Android. I assume we also don't respect the user pref on iOS, but haven't tested it.

**Comment by Hixie** [comment]
The time picker isn't localised in general.

**Comment by eseidelGoogle** [comment]
This is probably an easy fix, just some plumbing.

**Comment by eseidelGoogle** [comment]
@pytel87_twitter asked about this in gitter today.

**Comment by Hixie** [comment]
cc @yjbanov you did this, right?

**Comment by yjbanov** [comment]
Yep, it's done.
