### ISSUE TITLE
Requesting official SVGSupport in Flutter

### ISSUE THREAD

**Issue by vanshg395** [flutter/flutter#57032]
## Proposal

Currently, Flutter doesn't support official support for inserting SVG assets. That can be done using a package available on pub, but official support for such an important aspect will be really appreciated.

**Comment by iapicca** [comment]
Hi @vanshg395 
while there isn't a full first party support for svg as stated in this [issue](https://github.com/flutter/flutter/issues/1831#issue-133355369)
you might want to consider 3rd party [solutions](https://medium.com/flutter-community/using-svg-in-flutter-3dcf7b1dd713)
does this answer the issue?
Thank you

**Comment by vanshg395** [comment]
Hey @iapicca,

I totally agree third-party solutions are present, but they do not work on all platforms especially web, and importing a package for using such a basic feature is really annoying thats why an official support is requested. I hope the entire community will be happy with this support coming in future.

And off-course till the time this is added, we have no choice but to use 3rd party package

Thankyou

**Comment by iapicca** [comment]
Hi again @vanshg395 
I do not pretend to have the expertise to understand completely
the reasons behind the explanation in the link above,
but this support doesn't seem is going to happen

I'm closing the issue for now 
if you disagree please write in the comment and I'll reopen the issue
Thank you

**Comment by vanshg395** [comment]
@iapicca 

Hey, I want to reopen this issue. The point which I mentioned earlier has occurred now. The 3rd party package mentioned above to use svg support now has some bugs in the latest update.

Thus, I please request official support to use svgs in Flutter.

<img src="https://user-images.githubusercontent.com/34906419/85456476-9ebeb980-b5bc-11ea-8eb6-43166a502845.jpg" height="300" alt="error eg">

As you can see in the above screen shot, score has fallen greatly and health is now 0.

**Comment by iapicca** [comment]
HI @vanshg395 
please refer to the [issue](https://github.com/flutter/flutter/issues/1831#issue-133355369) linked [above](https://github.com/flutter/flutter/issues/57032#issuecomment-627803635)
Thank you
