### ISSUE TITLE
Video_player plugin. Add HTTP headers support like in Image.network

### ISSUE THREAD

**Issue by Olegas** [flutter/flutter#57049]
## Use case
My application is using video_player to show videos from a web site. Authentication is required to access media files.
With `Image.network` I can use `headers` argument and pass cookies or token. But `VideoPlayerController.network` does not have this ability

## Proposal
Add support of passing arbitrary HTTP headers to `VideoPlayerControler.network` constructor.

**Comment by jaysephjw** [comment]
Duplicate of #16466 :) 

@Olegas note the issue blocking $16466 should not prevent using cookies, just other types of headers. I am going to work on a PR for that.

**Comment by pedromassangocode** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/16466.
