### ISSUE TITLE
[customer: dream(g3)] Flutter memory usage investigation.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#57046]
Mirror issue for https://b.corp.google.com/issues/154912152. So far the Flutter team has been playing a consulting role, providing advice, while the upstream team is doing most of the troubleshooting. Filing here for tracking in case we need to do specific work around a leak.

We've asked for a minimal reproducible case if it turns out to be a general problem.

@chinmaygarde has been kind enough to provide some support on the upstream issue.

**Comment by chinmaygarde** [comment]
The title of this issue is incredibly leading. As it stands, the application seems to be holding onto too many references to expensive objects that cannot be collected. The profiling is around how to trace and collect those references. No leaks (unreachable references) have been identified.

**Comment by Hixie** [comment]
@chinmaygarde Please update the title if it's misleading. (In general, please update all issues to have accurate and useful titles.)

**Comment by chinmaygarde** [comment]
@kf6gpe I don't see this issue cross referenced internally. If I modify the title, will this throw off any book-keeping?

**Comment by kf6gpe** [comment]
The cross reference is through the link in the first comment. I was probably overzealous in what I removed from the subject to avoid leaking things from the upstream bug. I've tweaked the subject a bit; feel free to tweak further. As long as you don't edit the URL in the first comment, we'll be fine!

Thanks!

**Comment by kf6gpe** [comment]
Upstream team is working on a reproducible case. Still no action for the Flutter team, but we remain on-deck to provide support as needed.

**Comment by chinmaygarde** [comment]
I'm keeping an eye on the internal thread and will update this one if/when there is an AI for the Flutter team. In the meantime, I updated the title to better reflect status.

**Comment by kf6gpe** [comment]
Waiting for feedback from @chinmaygarde to a question on the internal tracker; I've reached out to him.

**Comment by kf6gpe** [comment]
Upstream issue appears to no longer be reproducible; some attempt at reproduction ongoing by Google team. We remain active on a consulting basis with this issue. Expect to close this within the next few days.

**Comment by chinmaygarde** [comment]
Update: There seems to be nothing for the Flutter team to do here.

**Comment by kf6gpe** [comment]
Flutter currently not blocking Google customer; downgrading and Chinmay will pick up if Google customer needs support.

**Comment by kf6gpe** [comment]
The upstream issue has been closed as works as intended. Closing.

**Comment by kf6gpe** [comment]
Upstream issue reopened. Not yet clear if the Flutter team needs to take action on this.

**Comment by chinmaygarde** [comment]
No. Nothing yet. I am responding to queries as they arrive.

**Comment by zanderso** [comment]
Since this issue is not currently actionable (beyond responding on the internal issue), I'm going to set this to "No milestone needed".

**Comment by kf6gpe** [comment]
Investigations by the Opal team suggest that this is related to the behavior of the memory manager they're using and their own integration code, rather than any behavior of the Dart VM or Flutter. Will reopen this issue if things prove otherwise.
