### ISSUE TITLE
[sdk] move fuchsia tests out of flutter recipe

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#57044]
Fuchsia tests should be running on its own builder. This will simplify disabling the builder when something starts failing without compromising all the other tests running on flutter.py recipe.

**Comment by godofredoc** [comment]
\cc @jmagman @iskakaushik

**Comment by CaseyHillers** [comment]
CL to fix the recipe at https://flutter-review.googlesource.com/c/recipes/+/5940

I'm looking into updating the test runner side now.

**Comment by CaseyHillers** [comment]
The recipe and test script seem to be working, but Flutter driver is timing out when looking for the device. It only gives a 1s timeout which is causing issues when there are several devices connected to the host [example task](https://chromium-swarm.appspot.com/task?id=4e5e5d6d8990b910).

**Comment by CaseyHillers** [comment]
I'm able to reproduce this error locally with only 1 Fuchsia device, so it shouldn't be an issue with the timeout.

**Comment by godofredoc** [comment]
obsolete
