### ISSUE TITLE
Finding references is not working reliably

### ISSUE THREAD

**Issue by andrasferenczi** [flutter/flutter#57054]
Issue is that I cannot traverse the code properly - jumping to usages and implementations is far from reliable.

### Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions.
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

Flutter doctor does not even know btw that I am using IntelliJ Ultimate 2020.1 with all latest plugins installed.

### Steps to reproduce issue

1) Open project in VSCode OR IntelliJ, does not matter
2) Go the file of let's say `CustomScrollView` (a file from the Flutter library I suppose) 
3) Try listing all implementations
4) Implementations are found - even from the Flutter library, which is great
5) Try listing them again
6) No implementation found or jump straight to the first class

This sounds like there is an issue with the Dart analysis server cache but I am no expert here. I just want to learn the Flutter environment by going through the code.

If I restart the editor, I can list implementations again.

I don't want to clear the cache before every reference lookup, please fix this.

---

Edit.:

Here is a gif to get an idea how it looks like:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17592224/81781494-7beab100-94f8-11ea-88ff-f8cdd36b5ad1.gif)

**Comment by iapicca** [comment]
Hi @andrasferenczi  
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Comment by andrasferenczi** [comment]
No, this is definitely **NOT** a problem with the Flutter plugin. I clearly mentioned that I am having the **same problem on VS Code** (see the first step) and yet you close this issue redirecting to a totally different place.

The IntelliJ plugin is a thin wrapper using the same code as the VS Code plugin (relying on the Dart analysis server as well). I have narrowed down the origin of the issue for you and yet you close this ticket...

So here is a gif from VS Code as well:

![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/17592224/81795807-d2fa8100-950c-11ea-9630-eb0e76cde03d.gif)

**Comment by devoncarew** [comment]
Since this appears in both the IntelliJ and VS Code plugins, this is best filed in dart-lang/sdk.

@andrasferenczi, re: https://github.com/flutter/flutter/issues/57054#issuecomment-627869141, please be respectful in your communications here. Francesco triaged this issue in good faith; please see our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) for Flutter's standards for discussion.

**Comment by andrasferenczi** [comment]
I felt I am putting in a lot of effort to explain my issues and the ticket got closed too suddenly. Sorry for the inappropriate tone of voice.

**Comment by andrasferenczi** [comment]
Took me long to figure out but the issue was that wrong folder was marked as project root.

**Comment by devoncarew** [comment]
@andrasferenczi, thanks for following up in investigating the issue! And, we do appreciate the bug reports - they help us know about problems and improve the product.
