### ISSUE TITLE
`Flutter run` should show logs even if the app crashed

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#57055]
https://github.com/FirebaseExtended/flutterfire/issues/2516 provides some context.

The current experience is:
1. A plugin may require some configuration (e.g. edit `AndroidManifest.xml`), which manifests as a runtime exception.
2. The app crashes right after launching it.
3. The tool keeps waiting for the observatory port.

I wonder if we can start the logcat stream much earlier, such that we can surface the exception.

cc @jonahwilliams

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/56943

**Comment by jonahwilliams** [comment]
This should be fixed on master, but if there are specific errors that aren't handled I can broaden the Regexp

**Comment by blasten** [comment]
I just confirmed that it fixed the issue!  iOS still needs something similar, right?

**Comment by jmagman** [comment]
That's already being tracked in https://github.com/flutter/flutter/issues/22536.

**Comment by blasten** [comment]
Cool. Thank you
