### ISSUE TITLE
Strange interaction between Stack and Column

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5706]
Code:
```dart
Future main() async {
  runApp(
    new Block(
      children: new List.generate(
        10,
        (int index) {
          return new Stack(
            children: [
              new Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  new Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: new Container(
                      width: 200.0,
                      height: 200.0,
                      decoration: new BoxDecoration(
                        backgroundColor: new Color(0xFFFFFF00),
                      ),
                    ),
                  ),
                  new Text('FOO'),
                ],
              ),
              new Container(),
            ],
          );
        },
      ),
    ),
  );
```

1. Running the above gives you a blank screen.
2. Removing the Container that's the second child of the stack fixes this, showing 10 yellow boxes with FOO underneath each (as expected).
3. Removing the Text (and not the second Container child of stack) results in one yellow box.  You can scroll that box but can never see the others.

The behaviour seems buggy to me.  I'd expect to see 10 yellow boxes with FOO underneath each regardless of there being other children of the Stack.  And I don't know why the Text makes things worse.

**Comment by Hixie** [comment]
What do you get if you dump the render tree?

**Comment by Hixie** [comment]
I believe we resolved this in person.
