### ISSUE TITLE
Shell:OnPlatformViewDestroyed not working with thread merging

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#57067]
The current implementation `Shell:OnPlatformViewDestroyed` is not compatible with thread merging.

For example on iOS, imagine an app contains a google map. When the map first shows up, the system alert view pops up for a location permission. The system alert view then triggers the [ApplicationWillResignActive](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L615), which triggers [Shell:OnPlatformViewDestroyed](https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L683) on the platform thread.
At the same time, the threads are about to merge on the raster thread because the google map view is about to show up at the next frame. If the merging thread happened after we check if the threads are merged [here](https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L726) (_We are not checking the thread merging now, which we also need to fix. But that's not the main issue here_), we will still post the task to the "raster_task_runner" [here](https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L738). And the posted task is actually going to run on the platform thread, because the threads are merged when the task started. It leads to a dead lock because the platform thread is still waiting for this posted task to release it.

**Comment by blasten** [comment]
From the offline conversation: @cyanglaz will share a design doc about this issue.

**Comment by chinmaygarde** [comment]
Triage: The linked pull request has been discussed and we have a way forward. It is still a WIP for now.

**Comment by chinmaygarde** [comment]
The PR is ready for review.
