### ISSUE TITLE
flutter widget layout generation & code generation not working

### ISSUE THREAD

**Issue by Akash4097** [flutter/flutter#57078]
After upgrade to latest version of flutter 1.17 i face the following problems:

The following problems i am facing in both android studio as well as in vs code. I tested on old as well on new project.
1: The flutter widget layout generation(click of alt+enter) is not working properly, sometime it appear and sometime its not appear but despite of its appearance it's not generated the widget code as it did in previous version of flutter.
**Note; this issue i face while the application is running.....**
2: The code generation(intellisense) for properties values of any widget is also not working, it provide the name of the property but when its come to the property value it doesn't work as it was.
This also facing while application is running......
 
here is my flutter doctor result:

```console
flutter doctor -v
[√] Flutter (Channel unknown, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Akash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Akash4097 
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues);

the following is the equivalent for the [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) : 
[github](https://github.com/Dart-Code/Dart-Code/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Comment by Akash4097** [comment]
Hello @iapicca 
i understand that but i face this issue as i upgrade to latest version of flutter and that's why i go back to previous version. But i'll also raise an issue on the respective github that you mentioned above.
Thanks for the help.

**Comment by iapicca** [comment]
Thank you @Akash4097 
https://github.com/flutter/flutter-intellij/issues/4543
