### ISSUE TITLE
How do you deal with floating point precision in dart?

### ISSUE THREAD

**Issue by leyan95** [flutter/flutter#57072]
Hi:
    How do you deal with floating-point precision in dart?
    code expression : `0.7 + 0.1`
    the console result: `0.7999999999999999`

**Comment by Andy-Python-Programmer** [comment]
Hi @leyan95 here is the method to implement floats in dart:
`void main() {
  List<double> list = [0.1, 0.7];
  double total = 0.0;

  list.forEach((item) {
    total = total + item;
  });
  print(total.toStringAsFixed(1));
}
`

**Comment by jonahwilliams** [comment]
You can read about floating point precision on the internet, for example https://floating-point-gui.de/formats/fp/ . This is not a unique feature of Dart or Flutter

The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by pedro-paz** [comment]
> Hi @leyan95 here is the method to implement floats in dart:
> 
> ```
> void main() {
>   List<double> list = [0.1, 0.7];
>   double total = 0.0;
> 
>   list.forEach((item) {
>     total = total + item;
>   });
>   print(total.toStringAsFixed(1));
> }
> ```
> 
> The console output will be:
> 
> ```
> 0.8
> ```

This aprouch is not consistent, how you will resolve the expression 0.2 + 0.1?

**Comment by pedro-paz** [comment]
> Hi @leyan95 here is the method to implement floats in dart:
> 
> ```
> void main() {
>   List<double> list = [0.1, 0.7];
>   double total = 0.0;
> 
>   list.forEach((item) {
>     total = total + item;
>   });
>   print(total.toStringAsFixed(1));
> }
> ```
> 
> The console output will be:
> 
> ```
> 0.8
> ```

This approach is not consistent, it is not possible to solve "0.2 + 0.1"  in this way
