### ISSUE TITLE
Flutter The system cannot find the path specified

### ISSUE THREAD

**Issue by ksaltik** [flutter/flutter#57079]
When I try to upgrade before 1 month ago there is one issue oen of the directory which one I don't remember at the moment try to renamed as .old. The upgrade process complains about not able to write the directory. I manually delete and create the directory and I able to solve the issue. 

For one month I don't use flutter. When I hear that new version of flutter and dart I try to upgrade it.

And I get the error when I try to run flutter upgrade 

The system cannot find the path specified

And I search google for a solution I can't find even here.

And I found the error. The earlier time when I try to upgrade the flutter C:\flutter\bin\cache\dart-sdk

the dart-sdk directory renamed to dart-sdk.old and the new one never created. I renamed the dart-sdk.old to dart-sdk and I able to run the flutter upgrade and completed without any problem.

**Comment by iapicca** [comment]
Hi @ksaltik 
please make sure that you added flutter to your `path`,
could you please provide your `flutter doctor -v` 
and your `flutter upgrade --force --verbose` 
Thank you

**Comment by ksaltik** [comment]
Hi @iapicca I already add the flutter path.

The reason why I open this issue is to provide a solution to problem people get. I think this is one of the reason people getting the error The system cannot find the path specified.

The dart-sdk path has been changed to dart-sdk.old and the new one not installed during upgrade. Just like in my situation.

I don't have any problem now thank you.....

**Comment by TahaTesser** [comment]
Hi @ksaltik 
Just tried `flutter upgrade --force` and ` dart-sdk `folder is created newer sdk version with no issues 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
