### ISSUE TITLE
slivergrid assertion error

### ISSUE THREAD

**Issue by dingowhiz** [flutter/flutter#57092]
not sure whether the error is related to the previous issue. Below is the code and error message:-
*** Flutter code ***

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import './product_item.dart';
import '../providers/products.dart';

class ProductsGrid extends StatelessWidget {
   final bool showFavs;
   
   ProductsGrid(this.showFavs);


  @override
  Widget build(BuildContext context) {
    final productsData = Provider.of<Products>(context);
    final products = showFavs ? productsData.favoriteItems : productsData.items;
    //listens for Products only

    return GridView.builder(
      padding: const EdgeInsets.all(10.0),
      itemCount: products.length,
      itemBuilder: (ctx, i) => ChangeNotifierProvider.value(
            //builder: (c) => products[i],
            value: products[i],
            child: ProductItem(
              //products[i].id, 
              //products[i].title, 
              //products[i].imageUrl,
            ),
      ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 10,
        crossAxisSpacing: 10, 
        childAspectRatio: 3/2,
      ),
    );
  }
}
```

*** Error ***
```bash
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (14680): The following assertion was thrown during performLayout():
I/flutter (14680): 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 161 pos 15:
I/flutter (14680): 'childMainAxisExtent != null && childMainAxisExtent >= 0': is not true.
I/flutter (14680):
I/flutter (14680): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14680): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14680): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14680):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14680):
I/flutter (14680): The relevant error-causing widget was:
I/flutter (14680):   GridView 
lib\widgets\products_grid.dart:19
I/flutter (14680):
I/flutter (14680): When the exception was thrown, this was the stack:
```

**Comment by dingowhiz** [comment]
ref : Issue # #33347

**Comment by iapicca** [comment]
Hi @dingowhiz 
the issue you mentioned above doesn't appear to be related to your case
since it doesn't involve `flutter_test` nor `Key()`;

can you please provide your `flutter doctor -v` 
and a `reproducible` minimal code sample
that doesn't depends from 3rd party plugins (like `provider`)
or external data
```dart
  final productsData = Provider.of<Products>(context);
  final products = showFavs ? productsData.favoriteItems : productsData.items;
```
Thank you

**Comment by dingowhiz** [comment]
thanks for the quick response. the error seems to point to the widget gridDelegate. please refer to the following ..

***Flutter doctor -v report***
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-SG)
    • Flutter version 1.17.0 at F:\Tech\Flutter
    • Framework revision e6b34c2b5c (12 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • MRD LX2 • RBU6R19305010414 • android-arm • Android 9 (API 28)

• No issues found!

***more codes below***
***products_overview_screen.dart***

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../widgets/badge.dart';
import '../widgets/products_grid.dart';
import '../widgets/app_drawer.dart';
import '../providers/cart.dart';
import '../screens/cart_screen.dart';

enum FilterOptions {
  Favorites,
  All,
}
class ProductsOverviewScreen extends StatefulWidget {
  @override
  _ProductsOverviewScreenState createState() => _ProductsOverviewScreenState();
}

class _ProductsOverviewScreenState extends State<ProductsOverviewScreen> {
  var _showOnlyFavorites = false;

  @override
  Widget build(BuildContext context) {
    //final productsContainer = Provider.of<Products>(context);
      return Scaffold(
        appBar: AppBar(
          title: Text('My Red Shirt Shop'),
          actions: <Widget>[
            PopupMenuButton(
              onSelected: (FilterOptions selectedValue) {
                setState(() {
                  if (selectedValue == FilterOptions.Favorites) {
                    _showOnlyFavorites = true;
                  } else {
                    _showOnlyFavorites = false;   
                  }        
                });
              },
              icon: Icon(
                Icons.more_vert,
              ),
          
              itemBuilder: (_) => [
                PopupMenuItem(
                  child: Text('Only Favorites'), 
                  value: FilterOptions.Favorites),
                PopupMenuItem(
                  child: Text('Show All'), 
                  value: FilterOptions.All
                ),
              ],
            ),
            Consumer<Cart>(
              builder: (_, cart, ch) => Badge(
                child: ch,
                value: cart.itemCount.toString(),
              ),
              child: IconButton(
                  icon: Icon(
                    Icons.shopping_cart,
                  ),
                  onPressed: () {
                    Navigator.of(context).pushNamed(CartScreen.routeName);
                    //navigates to cart screen
                  },
              ),
            )
          ],
        ),
        drawer: AppDrawer(),
      body: ProductsGrid(_showOnlyFavorites),
    );
  }
}

***product_item.dart***

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../screens/product_detail_screen.dart';
import '../providers/product.dart';
import '../providers/cart.dart';

class ProductItem extends StatelessWidget {
 // final String id;
  //final String title;
  //final String imageUrl;

  //ProductItem(this.id, this.title, this.imageUrl);  
  
  @override  
  Widget build(BuildContext context) {
    final product = Provider.of<Product>(context, listen: false);
    //, listen: false - not to listen to update, no rebuild
    final cart = Provider.of<Cart>(context, listen: false);

    
    return ClipRRect(
        borderRadius: BorderRadius.circular(10),
        child: GridTile(
          child: GestureDetector(
            onTap: () {
              Navigator.of(context).pushNamed(
                ProductDetailScreen.routeName, 
                arguments: product.id,
              );
            },
            child: Image.network(
              product.imageUrl,
              fit: BoxFit.cover,
            ),
          ),
          footer: GridTileBar(
            backgroundColor: Colors.black87,
            leading: Consumer<Product>(
              builder: (ctx, product, _) => IconButton(
              icon: Icon(product.isFavorite ? Icons.favorite : Icons.favorite_border,
              ),
              color: Theme.of(context).accentColor,
                onPressed: () {
                  product.toggleFavoriteStatus();
                }
              ),
              child: Text('Never changes!'),
              ),
            title: Text(
              product.title, 
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 8
              ),
            ),
            trailing: IconButton(
              icon: Icon(
                Icons.shopping_cart),
              onPressed: () {
                cart.addItem(product.id, product.price, product.title);
                Scaffold.of(context).hideCurrentSnackBar();
                Scaffold.of(context).showSnackBar(
                  SnackBar(
                    content: Text('Added item to cart'),
                    duration: Duration(seconds: 6),
                    action: SnackBarAction(label: 'Undo', onPressed: () {
                      cart.removeSingleItem(product.id);
                    },),
                  ),
                );
              }, 
              color: Theme.of(context).accentColor,
            ),
          ),
        ),
      );
   }
}

***main.dart***

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import './providers/cart.dart';
import './screens/products_overview_screen.dart';
import './screens/product_detail_screen.dart';
import './screens/cart_screen.dart';
import './screens/user_products_screen.dart';
import './providers/products.dart';
import './providers/orders.dart';
import './screens/orders_screen.dart';
import './screens/edit_product_screen.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
 @override 
 Widget build(BuildContext context) {
   return MultiProvider(
     providers: [
       ChangeNotifierProvider.value(
         value: Products(),
       ),
       ChangeNotifierProvider.value(
         value: Cart(),
         ),
       ChangeNotifierProvider.value(
         value: Orders(),
         
         ),

     ],
     child: MaterialApp(
            title: 'MyShop',
            theme: ThemeData(
              primarySwatch: Colors.purple,
              accentColor: Colors.deepOrange,
              fontFamily: 'Lato',
            ),
            home: ProductsOverviewScreen(),
            routes: {
              ProductDetailScreen.routeName: (ctx) => ProductDetailScreen(),
              CartScreen.routeName: (ctx) => CartScreen(),
              OrdersScreen.routeName: (ctx) => OrdersScreen(),
              UserProductsScreen.routeName: (ctx) => UserProductsScreen(),
              EditProductScreen.routeName: (ctx) => EditProductScreen(),
              //creates a new cart screen object
            }
          ),
    );
  }
}
class MyHomePage extends StatelessWidget {
  @override  
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Red Shirt Shop'),
      ),
      body: Center(
        child: Text('Let\'s build a mobile shop!'),
      ),
    );
  }
}

**Comment by iapicca** [comment]
Hi @dingowhiz 
as mentioned above, for the issue to be workable the code sample should be
minimal and reproducible as well as not depending from 3rd party plugins
does this [code sample ](https://dartpad.dev/1033d997ccc557f49616d637cc81f7f9)represent the issue you are describing?
Thank you

**Comment by dingowhiz** [comment]
Yes, correct.

**Comment by TahaTesser** [comment]
Hi @dingowhiz 
You agreed with the [comment](https://github.com/flutter/flutter/issues/57092#issuecomment-629067086), using the code sample, i am not able to reproduce any assertion on latest `stable` and `dev`

Can you try the provided code sample or provide a mnimal code sample that reproduce the issue?

Thank you

**Comment by dingowhiz** [comment]
Hi @TahaTesser, yes, I tested the sample code and it worked fine. I've added the Provider codes and it worked fine as well. Still couldn't pinpoint the root cause but would close this issue for now. Thanks.
