### ISSUE TITLE
Data Tables with Itembuilder features

### ISSUE THREAD

**Issue by n1k3sh** [flutter/flutter#57099]
Hello , I  am using big datatables on my app to show lots of columns and rows, since datatables preloads all data together thus reducing performance of my app . I need a table builder that loads data on demand and thus having a smooth usage . 

Some Other Features 

Highlighting .
When a cell is focused the whole row and column should be highlighted for better readability.

Fixed Headers
Fixed first column and headers for better usability of the table .

Search Functionality
Searching for the data within the cell and showing the whole row .

Bidirectional Scrolling 
Need to be able to scroll both directions together and not one direction at a time . 

Easing .
When user is scrolling and stops the table show ease to the nearest cell border , should not show a divided cell . 

I strongly feel that for business and other communities will need this sooner or later , since data will have to be presented in each industry , native apps are already using these features . Flutter Devs should plan for this soon .

**Comment by iapicca** [comment]
Hi @n1k3sh 
I see there's an open [issue](https://github.com/flutter/flutter/issues/49767) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by n1k3sh** [comment]
@iapicca I have no issues but i saw that post , but its been months and no update whether action has been taken on it ?

**Comment by iapicca** [comment]
Hi @n1k3sh 
at the moment the issue has no assignee or milestone,
feel free to submit a PR if you want to contribute with some features.
Thank you
