### ISSUE TITLE
[Sentry] Missing release version

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#57106]
## Steps to Reproduce

Simply setup Sentry like mentioned in the docs.

**Expected results:** Sentry should display release version on its console

**Actual results:** It displays n/a

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale pt-PT)
    • Flutter version 1.17.0 at /Users/miguelruivo/devtools/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1
```

**Comment by MisterJimson** [comment]
You need to pass in the release version when you create the `SentryClient`, in the `environmentAttributes` param.

**Comment by miguelpruivo** [comment]
@MisterJimson do you have an example? I can't really find where.

**Comment by MisterJimson** [comment]
![Screen Shot 2020-05-13 at 8 57 49 AM](https://user-images.githubusercontent.com/7351329/81815352-dfc0aa00-94f7-11ea-94e5-f0f41f0ce96f.png)

**Comment by TahaTesser** [comment]
Hi @MisterJimson 
Please let us know if the above [comment](https://github.com/flutter/flutter/issues/57106#issuecomment-627965851) solves your issue

can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by MisterJimson** [comment]
@TahaTesser I think you meant to tag @miguelpruivo

**Comment by miguelpruivo** [comment]
Yes it worked. Thank you!
