### ISSUE TITLE
flutter widget test: is there any way to write Data driven testcase

### ISSUE THREAD

**Issue by NanYeYe** [flutter/flutter#57103]
if i have two similar test（widget test case）, is there some way to simplify the test code, maybe like Data driven test（use such as python Decorator)?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
