### ISSUE TITLE
Navigator initialRoute documentation comments misleading

### ISSUE THREAD

**Issue by LordTerabyte** [flutter/flutter#57101]
The documentation comments above `initialRoute` inside the `Navigator` widget say
```dart
/// If this string contains any `/` characters, then the string is split on 
/// those characters and substrings from the start of the string up to each 
/// such character are, in turn, used as routes to push.
```
Which would seem to indicate that if I specify an initialRoute such as `foo/baz/123`, that the Navigator would push routes `foo`, `foo/baz` and `foo/baz/123` onto the stack. Yet, the only route that gets generated is the one for `foo/baz/123`, the entire thing.

This behavior made more sense after reading the code for `NavigatorState.initState`
```dart
String initialRouteName = widget.initialRoute ?? Navigator.defaultRouteName;
if (initialRouteName.startsWith('/') && initialRouteName.length > 1) {
  initialRouteName = initialRouteName.substring(1); // strip leading '/'
  assert(Navigator.defaultRouteName == '/');
  // ...
} else {
  // ...
```

**Comment by goderbauer** [comment]
@chunhtai assigning to you since you have a PR out to fix this.
