### ISSUE TITLE
The Flutter tool should use the same Fuchsia SDK version as the engine

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#57118]
The SDK version used by the engine can be found here:

https://github.com/flutter/engine/blob/2f8495a5e638fa9995f58b7fbbc39f00ac7e6a59/DEPS#L548-L587

And the `fuchsia/sdk/<platform>/meta/manifest.json` has a specific jiri build ID in it to help with fetching system images:

```json
{
  "arch": {
    "host": "x86_64-apple-darwin",
    "target": [
      "arm64",
      "x64"
    ]
  },
  "id": "0.20200505.2.1",
...
```

/cc @zanderso @jonahwilliams @gw280 @iskakaushik

**Comment by jonahwilliams** [comment]
This should be done as part of the engine auto-roller

**Comment by dnfield** [comment]
That's certainly an option. I wonder if it would be easier to just have the engine builders upload the information to a storage bucket the way we do with everything else, and the tool could then download a manifest it uses. It should be simple enough to fish out the SDK version and the JIRI build id on the builders.

Modifying the rollers may require help from Skia infra, and sometimes what seem like simple modifications don't really fit the architecture.

**Comment by jonahwilliams** [comment]
Uploading the manifest using the existing engine.version URL sounds reasonable too

**Comment by zanderso** [comment]
https://github.com/flutter/flutter/issues/46173 is marked done. How is this different?

**Comment by dnfield** [comment]
Ahhh. I think this is a duplicate then.  @jonahwilliams is there anything else to do for this?

**Comment by jonahwilliams** [comment]
The linked PR looks like it just bumped the version? https://github.com/flutter/flutter/pull/51569

**Comment by jonahwilliams** [comment]
Ahh nope
its working: https://github.com/flutter/flutter/pull/57109/files

**Comment by jonahwilliams** [comment]
I had no idea this was hooked up 🤷‍♂️

**Comment by dnfield** [comment]
I should have known, I was cc'd on all the work related to it haha.  Sorry about that!
