### ISSUE TITLE
Simple App Icon / App Name Changes

### ISSUE THREAD

**Issue by 34r7h** [flutter/flutter#57116]
Please provide a property line in pubspec.yaml to identify name and icon for the app. The app icon should take a vector image type, such as SVG, or large format PNG/JPG to then shrink for appropriate device and systems.

**Comment by TahaTesser** [comment]
Hi @34r7h 
Can you gives us more details to have these in `pubspec.yaml`? 
Thank you

**Comment by 34r7h** [comment]
Perhaps a property like

icon: images/logo.svg

or if a developer wants specificity,

icons:
    ios:  images/ios_logo.svg
    android:  images/android_logo.svg
    web:  images/web_logo.svg

that would do the same work as https://appicon.co/, to resize and define in
content or a manifest file, then slip the assets into the appropriate
folders for target devices and web.

**Comment by jonahwilliams** [comment]
This is not something that should be added to the flutter tooling.

Different platforms have widely different standards and requirements for application icons. Attempting to create a single property in the pubspec.yaml to describe all of them could only be done with a lowest common denominator approach, which is against Flutter's standards.

The responsibility for application icons should be left up to the platform projects.

**Comment by 34r7h** [comment]
This approach puts more responsibility on developers with little benefit.
Seems against the actual value proposition.
