### ISSUE TITLE
Gallery, Pesto: back button hard to see sometimes

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5711]
Open gallery, tap into Pesto, scroll down to Coconut rice, and tap into it. Notice how the user can't see the back icon in upper left.

![screen shot 2016-09-01 at 11 51 01 am](https://cloud.githubusercontent.com/assets/5479/18180141/5edb4d36-703a-11e6-94ca-ad84a10cde97.png)

If the image is dark, then the user can see the back arrow. If the image is light (as is the case with cococut rice), then the user can't see the back arrow.

Strawman solution: put a dark gradient at the top of every image, such that it provides a good contrast for the back arrow. But, of course, open to ideas.

**Comment by dragostis** [comment]
I would go for a simpler don't-use-iamges-with-light-backgrounds solution.

**Comment by Hixie** [comment]
I thought we had a gradient already. I'm sure I've seen code for it.

We should probably have a generic widget that you can stick anywhere you need one.

**Comment by sethladd** [comment]
We used to have a gradient there. Not sure what happened to it.

@dragostis works for me. But I do love coconut rice.

**Comment by dragostis** [comment]
I guess I would go for both solutions: a gradient would be great especially in places where you display images (like Google Photos), but I find it slicker without the gradient where possible.

**Comment by sethladd** [comment]
I assume that not everyone will be able to control their images :) so if we can show them how to put a gradient at the top of their image, let's do that.

Of course, if you can auto-detect the colors of the top of the image, and draw a back arrow with the appropriate contrast, that works, too :)
