### ISSUE TITLE
Custom Padding in PopupMenuButton

### ISSUE THREAD

**Issue by NidheeshMt** [flutter/flutter#57110]
Not able to configure padding in PopupMenuButton.  It is seems like it using the default values for vertical and horizontal paddings,
```
const double _kMenuCloseIntervalEnd = 2.0 / 3.0;
const double _kMenuHorizontalPadding = 16.0;
const double _kMenuDividerHeight = 16.0;
const double _kMenuMaxWidth = 5.0 * _kMenuWidthStep;
const double _kMenuMinWidth = 2.0 * _kMenuWidthStep;
const double _kMenuVerticalPadding = 8.0;
const double _kMenuWidthStep = 56.0;
const double _kMenuScreenPadding = 8.0;
```
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (11 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

**Comment by alsedev** [comment]
Hi @iapicca 
Is it possible to change _kMenuMaxWidth constant to allow a little bit more space for (foreign languages) longer sentences?
**NOTE**: I'd changed it to 
`const double _kMenuMaxWidth = 10.0 * _kMenuWidthStep;`
because I do need a larger font size for older people (users).
Thanks.

**Comment by alsedev** [comment]
@TahaTesser, thank you for adding "severe: new feature" label.  Any news?

**Comment by LucaIaconelli** [comment]
It would be fantastic to be able to change this value (_kMenuHorizontalPadding) so that you have the option to remove the padding.

**Comment by xJon** [comment]
Would be a useful feature.

**Comment by rydmike** [comment]
Plus one for this issue. 👍🏻 

I just searched for how to remove and change these as well and landed here. Particularly I wanted to get rid of of the top and bottom padding on the popup menu.

This use case example with a long press on a widget context menu, with rounded corners and slightly transparent background,  eg as a cut / copy / paste context menu. Would have looked much nicer and compacter without the extra padding on top and bottom. Being able to remove them would have enabled having the padding just a part of the the item height, so when selecting top and bottom items, the highlighte selection and splash would have included the rounded shape border, but nope, no can do, not with this widget.

![context_menu](https://user-images.githubusercontent.com/39990307/108738382-386bab80-753c-11eb-9059-bbc05d403d9e.gif)

Parameters like this should be part of `PopupMenuThemeData` and as properties in the Widget.
Material still does not always want to work with you, when you want a slightly different design. I know, back to making totally custom widgets or forking this one, just don't always have time for it, this will have to do for now, the look is acceptable for now for my use case, but it could have been even prettier.

Pity to see an issue like these open for this long, it was reported in May 2020.

cc: @HansMuller @mariamhas

**Comment by Moluram** [comment]
@pedromassangocode Hello! Can I take this issue?

**Comment by pedromassangocode** [comment]
Hi @Moluram  of course :)

I will assign it to you.
