### ISSUE TITLE
Bad characters with some unicodes flutter 1.12.13 with iOS 13

### ISSUE THREAD

**Issue by hesham91fci** [flutter/flutter#57115]
Currently I've working on a project, till iOS 12 it was stable starting from iOS 13 I noticed that bad characters are displayed replacing **some unicodes**, any help for the how to display it properly it would be appreciated, I've tried various font families but with no result, kindly find a sample code, and the screenshot for the result

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RichText(
              softWrap: true,
              textDirection: TextDirection.rtl,
              text: TextSpan(
                  style: TextStyle(
                    color: Colors.black,
                    fontWeight: FontWeight.w500,
                    fontSize: 20.0,
                  ),
                  children: [
                    TextSpan(
                        text: "\u{08f0}"
                    ),
                  ]
              ),
            ),
          ],
        ),
      ),
    );
  }
```
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-13 at 15 57 22](https://user-images.githubusercontent.com/4971507/81826567-377f0580-9538-11ea-8623-20aa200f486d.png)

**Comment by TahaTesser** [comment]
Please the thumbs up the mentioned issue
closing as duplicate https://github.com/flutter/flutter/issues/54529

**Comment by hesham91fci** [comment]
@TahaTesser 
Hopefully to find a fix for the original one :((
