### ISSUE TITLE
Using external JS libs in flutter application

### ISSUE THREAD

**Issue by roman-rr** [flutter/flutter#57121]
I'm looking for mobile framework for next application, but i need to be sure that UI allowing to add external js libs. 
For example https://github.com/nolimits4web/swiper or https://github.com/roman-rr/cupertino-pane
Is that possible with flutter to use JS libs inside ?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
