### ISSUE TITLE
How to reduce the size of Runner.app

### ISSUE THREAD

**Issue by wrjcs** [flutter/flutter#57122]
Hello every,
I build app for ios by using "flutter build ios" 
the result I got in ./build/ios/iphoneos/Runner.app, the size of the file is so large as 460M.
How could I reduce the file size?

Thanks.

**Comment by wrjcs** [comment]
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-FR)
    • Flutter version 1.17.0 at /Users/renjiewang/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

**Comment by TahaTesser** [comment]
Hi @wrjcs 
Please check out this [comment](https://github.com/flutter/flutter/issues/51068#issuecomment-588410024) and read [Measuring your app's size](https://flutter.dev/docs/perf/app-size#ios)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
