### ISSUE TITLE
[Cocoon] AngularDart application is failing to build

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#57137]
To deploy v399, I worked around this by just commenting out the function to build the angular dart app. But right now it's failing.

Can we just remove the whole thing at this point? AFAIK it's not being used.

/cc @CaseyHillers @digiter @keyonghan

**Comment by keyonghan** [comment]
The performance dashboard is still using angular dart: https://github.com/flutter/flutter/issues/45276

**Comment by digiter** [comment]
What's the error message from building AngularDart part?

**Comment by dnfield** [comment]
```
[SEVERE] build_web_compilers:sdk_js_copy on package:build_web_compilers/$lib$ (cached):

FileSystemException: Cannot open file, path = '/Users/dnfield/src/flutter/flutter/bin/cache/dart-sdk/lib/dev_compiler/amd/dart_sdk.js' (OS Error: No such file or directory, errno = 2)
```
In the past, I've been able to use the Flutter SDK's dart to do this - do I need Dart from elsewhere for it?

@jonahwilliams might know.

**Comment by jonahwilliams** [comment]
The fact that it worked with flutter's dart SDK was likely an accident. We don't test anything besides flutter web applications

**Comment by dnfield** [comment]
That was the problem.

**Comment by dnfield** [comment]
(I had to use a non-flutter dart sdk)
