### ISSUE TITLE
Gallery, Pesto: "Home" in drawer was confusing to some users

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5713]
(from user testing)

The "Home" item in Pesto's drawer was confusing. Did it mean "Gallery home" or "Pesto home" ?

One thing I noticed: the Home item isn't highlighted when the user is on the Pesto home. So there's no visual indication that they are at any place in the drawer nav.

One idea: remove the drawer entirely. It only shows up on the home of Pesto. The user could use the back button to get back to the Gallery home.

**Comment by sethladd** [comment]
Can we land the removal of the drawer?

With the new back gesture hotness, I want to use it all the time. Pesto breaks that with its drawer.

Thanks!

**Comment by sethladd** [comment]
When we remove the drawer, please also remove the Favorites feature. Which then lets us close out https://github.com/flutter/flutter/issues/5071

**Comment by sethladd** [comment]
cc @dragostis

**Comment by dragostis** [comment]
I'll update the PR. Are we removing the favorites logic?

**Comment by sethladd** [comment]
Yes, for now.
