### ISSUE TITLE
I dont  know why

### ISSUE THREAD

**Issue by Ahmed-ALshmre** [flutter/flutter#57148]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
D/FlutterActivity(12283): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(12283): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(12283): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(12283): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(12283): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@535466
D/FlutterActivityAndFragmentDelegate(12283): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:59426/8cMtpBvZaPo=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(12283): eglMakeCurrent: 0xa4ab2e20: ver 2 0 (tinfo 0x98be72a0)
W/DynamiteModule(12283): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(12283): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(12283): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/zygote  (12283): Background concurrent copying GC freed 17793(1089KB) AllocSpace objects, 10(360KB) LOS objects, 53% free, 1336KB/2MB, paused 3.311ms total 250.262ms
V/NativeCrypto(12283): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
D/NetworkSecurityConfig(12283): No Network Security Config specified, using platform default
I/ProviderInstaller(12283): Installed default security provider GmsCore_OpenSSL
I/flutter (12283): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12283): The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
I/flutter (12283): _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#4af34):
I/flutter (12283): There should be exactly one item with [DropdownButton]'s value: Select Category.
I/flutter (12283): Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
I/flutter (12283): 'package:flutter/src/material/dropdown.dart':
I/flutter (12283): Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
I/flutter (12283):               items.where((DropdownMenuItem<T> item) {
I/flutter (12283):                 return item.value == value;
I/flutter (12283):               }).length == 1'
I/flutter (12283): 
I/flutter (12283): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12283): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12283): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12283):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12283): 
I/flutter (12283): The relevant error-causing widget was:
I/flutter (12283):   StreamBuilder<QuerySnapshot> file:///G:/firebase/firebas/lib/admin/add_product.dart:171:14
I/flutter (12283): 
I/flutter (12283): When the exception was thrown, this was the stack:
I/flutter (12283): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:805:15)
I/flutter (12283): #3      _AddProductState._selectCategory.<anonymous closure> (package:firebas/admin/add_product.dart:181:22)
I/flutter (12283): #4      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (12283): #5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (12283): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (12283): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (12283): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12283): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (12283): #10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (12283): #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (12283): #12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (12283): #13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (12283): #14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (12283): #18     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (12283): #19     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (12283): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (12283): 
I/flutter (12283): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#4af34):
There should be exactly one item with [DropdownButton]'s value: Select Category. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  StreamBuilder<QuerySnapshot> file:///G:/firebase/firebas/lib/admin/add_product.dart:171:14
When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:805:15)
#3      _AddProductState._selectCategory.<anonymous closure> (package:firebas/admin/add_product.dart:181:22)
#4      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
#5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
