### ISSUE TITLE
[sdk] add flaky property to luci configs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#57155]
When there is a problem with one of the luci builders they block submitting PRs which is a big loss in productivity.

As an example a timing out fuchsia test blocked submission of PRs to the sdk for more than 24hours.

When we tried to mark the builder as flaky there were many blockers:

- [x] Builder configurations for the sdk live in cocoon instead of flutter.
- [x] A deployment of the cocoon application was needed to enable the change.
- [x] Adding/removing a builder was not documented anywhere.
- [x] Sdk builder is doing too many things and is really easy to get blocked when one of the several moving pieces failed.

**Comment by godofredoc** [comment]
\cc @jmagman @jonahwilliams

**Comment by christopherfujino** [comment]
Here's another example where this property would have re-opened the tree https://github.com/flutter/flutter/issues/58012

**Comment by godofredoc** [comment]
All the steps highlighted on this bug have already been addressed.
