### ISSUE TITLE
[image_picker] image picker pick video returns jpg format video

### ISSUE THREAD

**Issue by boucoding** [flutter/flutter#57156]
Hi,

I am using this plugin in order to pick images but when I try to pick a video from the gallery it returns the file in jpg format.

how to solve this?

Thanks,

**Comment by TahaTesser** [comment]
Definitely returns jpg for some reason when picking video
```
3:16
I/flutter ( 9269): Video Source ImageSource.gallery
I/flutter ( 9269): Video File File: '/data/user/0/com.nevercode.triage/cache/image_picker2978742146423458987.jpg'
```

Closing as duplicate of https://github.com/flutter/flutter/issues/52419

**Comment by gonzalodev92** [comment]
I have the same problem in android with the last version (image_picker: ^0.6.7+14) In ios works well.

**Comment by peterslight** [comment]
still picks as jpg in Android, been banging my head as to why videos weren't being uploaded to the server

**Comment by bulgarian-beast** [comment]
Same.
Tested on android device : 
_vid = await ImagePicker().getVideo(source: ImageSource.gallery); 
return a ".jpg" pickedFile

**Comment by TahaTesser** [comment]
The duplicate issue is still open  https://github.com/flutter/flutter/issues/52419
