### ISSUE TITLE
W/AnalyticsUserIDStore( 8905): initStore should have been called before calling setUserID

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#57153]
```
W/yy.yyyyyyy( 8905): Verification of void com.google.android.gms.internal.measurement.zzb.<clinit>() took 101.289ms
W/AnalyticsUserIDStore( 8905): initStore should have been called before calling setUserID
W/UserDataStore( 8905): initStore should have been called before calling setUserID
```

Seeing these errors after upgrading to the latest stable flutter....

**Comment by TahaTesser** [comment]
Hi @giorgio79 
You're probably using mobx? Error doesn't look like Flutter store issue
```
W/AnalyticsUserIDStore( 8905): initStore should have been called before calling setUserID

```

can you please provide your `flutter doctor -v` and `flutter run --verbose`? '
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
