### ISSUE TITLE
[web]: Web bugs

### ISSUE THREAD

**Issue by realrk69** [flutter/flutter#57168]
Issues:

1. After clicking on a web page made with flutter, moving the mouse up or down starts scrolling. After releasing the click, the scrolling still continues.

2. No hover effects or other effects inbuilt in buttons.

3. Web apps appear pixelated, blurry and do not change size according to screen estate.

4. No easy way of talking with web APIs like Bluetooth.

**Comment by stuartmorgan** [comment]
Please file individual issues for different bugs; we can't effectively track unrelated bugs in a single issue.
