### ISSUE TITLE
Overscrolling on Android shouldn't actually overscroll.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5717]
The way overscrolling is implemented right now is that it keeps track of the amount of overscrolling you did and then tries to revert à la iOS but without actually drawing the overscroll.

This is noticeable if you simply

```
onScroll: (double offset) {
  print(offset);
},
```

in a `Block`. Once you overscroll at the top, you will get negative values that will eventually converge back to 0.

```
I/flutter : 87.54362042236653
I/flutter : -48.32216257515597
I/flutter : -125.39115577233815
I/flutter : -137.06633320548207
I/flutter : -132.42527469133327
I/flutter : -114.41886073580588
I/flutter : -103.86404847843673
I/flutter : -93.34183842910332
I/flutter : -81.4272607368222
I/flutter : -64.92422268321576
I/flutter : -56.96995334572571
I/flutter : -43.72702686455987
I/flutter : -38.13252638214636
I/flutter : -33.16717724981637
I/flutter : -28.0020195842282
I/flutter : -21.777720032386235
I/flutter : -18.8907203944756
I/flutter : -16.30599860025159
I/flutter : -12.317142299822683
I/flutter : -10.670217812096068
I/flutter : -9.230066417868127
I/flutter : -7.915359458419071
I/flutter : -6.954333650169141
I/flutter : -6.022814620748058
I/flutter : -5.174660484117738
I/flutter : -4.468657968592085
I/flutter : -3.904625188416362
I/flutter : -3.3803005499945633
I/flutter : -2.926872251863483
I/flutter : -2.5319527198127716
I/flutter : -2.1936974405126164
I/flutter : -1.898607817229599
I/flutter : -1.6421397217979725
I/flutter : -1.4184404374201598
I/flutter : -1.2311495220122308
I/flutter : -1.066979879128746
I/flutter : -0.9224067161005122
I/flutter : -0.7997654387741359
I/flutter : -0.6921191302468485
I/flutter : -0.5985299112444221
I/flutter : -0.5181533599156825
I/flutter : -0.44817054422814373
I/flutter : -0.3867007144439571
I/flutter : -0.3358394356954059
I/flutter : 0.0
```

This behavior causes two perceivable issues:
- the invisible overscrolling logic causes missed taps because it believes that you are trying to stop a fling; a simple way to reproduce this is to oversroll up in a list and immediately tap an item
- as observed by @Hixie, scrolling in the opposite direction right after overscrolling on Android should begin scrolling right away, but since we're taking into account how much you're overscrolling, the behavior is similar to iOS; you can reproduce this by overscrolling a list, then immediately scroll in the opposite direction without lifting you finger which will make the `OverscrollIndicator` disappear but it will _not_ scroll

Fixing this will solve one of the cases where missed taps happen in the Gallery as per #5709.

**Comment by dragostis** [comment]
This also related to #5279.

**Comment by abarth** [comment]
Fixed.
