### ISSUE TITLE
TextFormField.onsave length limit error,When I type in special characters

### ISSUE THREAD

**Issue by SakurasDuck** [flutter/flutter#57177]
**flutter doctor**

[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.0)
[√] Connected device (1 available)

**my code**

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  String valueStr;

  GlobalKey<FormState> _formKey;

  void _incrementCounter() {
    var _form = _formKey.currentState;

    _form.save();
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
    _formKey = GlobalKey<FormState>();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Form(
        key: _formKey,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextFormField(
//                inputFormatters: [
//                  LengthLimitingTextInputFormatter(4),
//                ],
                maxLength: 4,
                onSaved: (value) {
                  setState(() {
                    valueStr = value;
                  });
                },
              ),
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter-------------${valueStr ?? ''}',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
``` 

</details> 

**result**

![image](https://user-images.githubusercontent.com/40283698/81881734-8160fd80-95c3-11ea-85eb-bcaac0122563.png)

**Comment by SakurasDuck** [comment]
![5666ebcd148586e3f451b5c4c958b3b](https://user-images.githubusercontent.com/40283698/81881893-ec123900-95c3-11ea-9ce2-84183041d904.jpg)

**Comment by TahaTesser** [comment]
Hi @SakurasDuck 
Not able to reproduce this issue using emulator or physical device 

![flutter_01](https://user-images.githubusercontent.com/48603081/81935312-1688e400-960e-11ea-9e0c-3f75653feaa6.png)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (35 hours ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (3 available)            
    • SM M305F                  • 32003c30dc19668f          • android-arm64 •
      Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554             • android-x86   •
      Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios           •
      iOS 13.4.1

• No issues found!

``` 

</details> 

Can you please list the device you using?
Can you please try reproducing it on emulator?
Thank you

**Comment by SakurasDuck** [comment]
@TahaTesser  Thank you, emulator is ok

flutter doctor -v

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
    • Flutter version 1.17.1 at D:\Tools\Android\flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Tools\Android\SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Tools\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\Pawn\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\Pawn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • VOG AL00 • MQS0219A17009076 • android-arm64 • Android 10 (API 29)

It also appears in
   • DUK AL20 • FFK0217923004323 • android-arm64 • Android 9 (API 28)
   • MI 9 SE • ccad64e • android-arm64 • Android 10 (API 29)

**Comment by SakurasDuck** [comment]
#61162
