### ISSUE TITLE
 Hello, I'm new to programming. I have a problem, can you help?

### ISSUE THREAD

**Issue by Berkant35** [flutter/flutter#57175]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Berkant35** [comment]
import 'dart:async';
import 'dart:convert';
import 'dart:core';

import 'dart:math';
import 'package:fenspeed/app/resultpage.dart';

import 'package:fenspeed/common_widget/social_login_Button.dart';
import 'package:fenspeed/models/question.dart';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class TestPage extends StatefulWidget with ChangeNotifier  {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<Question> gelenVerileriBunaGoreYaz;
  Stopwatch watch = Stopwatch();
  Timer timer;
  int dogruSayi = 0;
  int yanlisSayi = 0;
  int gecenSureDoubleDegeri;
  int kacinciSoru = 1;
  String gecenSure = ""; //ingilizcesi elapsed :)
  List cevapListesi = RandomSayiOlustur();
  int randomSayi = RandomSoruGetirenIndexWidget();
  @override
  void notifyListeners (){}
  @override
  void initState() {
    super.initState();
    startWatch();
    gelenVerileriBunaGoreYaz = [];
  }

  @override
  void dispose() {
    stopWatch();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: FutureBuilder(
            future: veriKaynaginiOku(),
            builder: (context, sonuc) {
              if (sonuc.hasData) {
                gelenVerileriBunaGoreYaz = sonuc.data;
                return ListView(
                  children: <Widget>[
                    Container(
                      height: 305,
                      width: 500,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                            begin: Alignment.bottomRight,
                            end: Alignment.topLeft,
                            colors: [
                              Theme.of(context).primaryColor,
                              Theme.of(context).primaryColorLight
                            ]),
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.start,
                        children: <Widget>[
                          SizedBox(
                            height: 25,
                          ),
                          Text(
                            "$kacinciSoru/20",
                            style: TextStyle(fontSize: 26),
                          ),
                          SizedBox(
                            height: 100,
                          ),
                          Center(
                            child: Text(
                              gelenVerileriBunaGoreYaz[randomSayi].question,
                              style: TextStyle(fontSize: 22),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      height: 305,
                      width: 500,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                            begin: Alignment.topRight,
                            end: Alignment.bottomLeft,
                            colors: [
                              Theme.of(context).primaryColor,
                              Theme.of(context).primaryColorLight
                            ]),
                      ),
                      child: Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            SocialLoginButton(
                              butttonText: "A-) " +
                                  gelenVerileriBunaGoreYaz[randomSayi]
                                      .randomAnswers[cevapListesi[0]],
                              elevation: 20,
                              onPressed: () {
                                setState(() {
                                  checkAnswer(
                                      randomSayi, cevapListesi, context);
                                  randomSayi = RandomSoruGetirenIndexWidget();
                                  cevapListesi = RandomSayiOlustur();
                                });
                              },
                              genislik: 300,
                              iconileBosluk: 2,
                            ),
                            SocialLoginButton(
                              butttonText: "B-) " +
                                  gelenVerileriBunaGoreYaz[randomSayi]
                                      .randomAnswers[cevapListesi[1]],
                              elevation: 20,
                              onPressed: () {
                                setState(() {
                                  checkAnswer2(
                                      randomSayi, cevapListesi, context);
                                  randomSayi = RandomSoruGetirenIndexWidget();
                                  cevapListesi = RandomSayiOlustur();
                                });
                              },
                              genislik: 300,
                              iconileBosluk: 2,
                            ),
                            SocialLoginButton(
                              butttonText: "C-) " +
                                  gelenVerileriBunaGoreYaz[randomSayi]
                                      .randomAnswers[cevapListesi[2]],
                              elevation: 20,
                              onPressed: () {
                                setState(() {
                                  checkAnswer3(
                                      randomSayi, cevapListesi, context);
                                  randomSayi = RandomSoruGetirenIndexWidget();
                                  cevapListesi = RandomSayiOlustur();
                                });
                              },
                              genislik: 300,
                              iconileBosluk: 2,
                            ),
                            SocialLoginButton(
                              butttonText: "D-) " +
                                  gelenVerileriBunaGoreYaz[randomSayi]
                                      .randomAnswers[cevapListesi[3]],
                              elevation: 20,
                              onPressed: () {
                                setState(() {
                                  checkAnswer4(
                                      randomSayi, cevapListesi, context);
                                  randomSayi = RandomSoruGetirenIndexWidget();
                                  cevapListesi = RandomSayiOlustur();
                                });
                              },
                              genislik: 300,
                              iconileBosluk: 2,
                            ),
                          ],
                        ),
                      ),
                    ),
                    Container(
                      height: 305,
                      width: 500,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                            begin: Alignment.bottomRight,
                            end: Alignment.topLeft,
                            colors: [
                              Theme.of(context).primaryColor,
                              Theme.of(context).primaryColorLight
                            ]),
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: <Widget>[
                          Text(
                            "Dogru Sayisi: " + dogruSayi.toString(),
                            style: TextStyle(color: Colors.white, fontSize: 18),
                          ),
                          SizedBox(
                            height: 10,
                          ),
                          Text(
                            "Yanlis Sayisi: " + yanlisSayi.toString(),
                            style: TextStyle(color: Colors.white, fontSize: 18),
                          ),
                          SizedBox(
                            height: 10,
                          ),
                          Text(
                            "Gecen Süre: " + gecenSure.toString(),
                            style: TextStyle(color: Colors.white, fontSize: 18),
                          ),
                        ],
                      ),
                    ),
                  ],
                );
              } else {
                return Center(
                  child: CircularProgressIndicator(),
                );
              }
            }),
      ),
    );
  }

  void checkAnswer4(int randomSayi, List cevapListesi, BuildContext context) {
    if (gelenVerileriBunaGoreYaz[randomSayi]
            .randomAnswers[cevapListesi[3]]
            .toString() ==
        gelenVerileriBunaGoreYaz[randomSayi].correctAnswers.toString()) {
      setState(() {
        dogruSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    } else {
      setState(() {
        yanlisSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    }
  }

  void checkAnswer3(int randomSayi, List cevapListesi, BuildContext context) {
    if (gelenVerileriBunaGoreYaz[randomSayi]
            .randomAnswers[cevapListesi[2]]
            .toString() ==
        gelenVerileriBunaGoreYaz[randomSayi].correctAnswers.toString()) {
      setState(() {
        dogruSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    } else {
      setState(() {
        yanlisSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    }
  }

  void checkAnswer2(int randomSayi, List cevapListesi, BuildContext context) {
    if (gelenVerileriBunaGoreYaz[randomSayi]
            .randomAnswers[cevapListesi[1]]
            .toString() ==
        gelenVerileriBunaGoreYaz[randomSayi].correctAnswers.toString()) {
      setState(() {
        dogruSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    } else {
      setState(() {
        yanlisSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    }
  }

  void checkAnswer(int randomSayi, List cevapListesi, BuildContext context) {
    if (gelenVerileriBunaGoreYaz[randomSayi]
            .randomAnswers[cevapListesi[0]]
            .toString() ==
        gelenVerileriBunaGoreYaz[randomSayi].correctAnswers.toString()) {
      setState(() {
        dogruSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    } else {
      setState(() {
        yanlisSayi++;
      });

      if (kacinciSoru == 20) {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ResultPage(
                dogruSayi, yanlisSayi, gecenSure, gecenSureDoubleDegeri)));
      } else {
        setState(() {
          kacinciSoru++;
        });
      }
    }
  }

  startWatch() {
    watch.start();
    timer = Timer.periodic(Duration(milliseconds: 1), _updateTime);
    // WidgetsBinding.instance.addPostFrameCallback((mounted) => setState(() { }));
    setState(() {
      setTime();
    });



  }

  stopWatch() {
    watch.stop();
    setTime();

  }

  resetWatch() {
    setTime();
  }

  Future veriKaynaginiOku() async {
    var gelenJson = await DefaultAssetBundle.of(context)
        .loadString("assets/data/questions.json");
    List<Question> sorularListesi = (json.decode(gelenJson) as List)
        .map((mapYapisi) => Question.fromJsonMap(mapYapisi))
        .toList();
    for (int i = 0; i < sorularListesi.length; i++);
    sorularListesi.toString();
    return sorularListesi;
  }

  static List RandomSayiOlustur() {
    List answerListIndex = [0, 1, 2, 3];
    final _randomIndex = Random();
    List cevaplarListesi = [];
    for (int i = 1; cevaplarListesi.length < 4; i++) {
      final answer1 = answerListIndex[_randomIndex.nextInt(4)];
      cevaplarListesi.add(answer1);
      answerListIndex.remove(answer1);
      final answer2 = answerListIndex[_randomIndex.nextInt(3)];
      cevaplarListesi.add(answer2);
      answerListIndex.remove(answer2);
      final answer3 = answerListIndex[_randomIndex.nextInt(2)];
      cevaplarListesi.add(answer3);
      answerListIndex.remove(answer3);
      final answer4 = answerListIndex[_randomIndex.nextInt(1)];
      cevaplarListesi.add(answer4);
      return cevaplarListesi.toList();
    }
  }

  static int RandomSoruGetirenIndexWidget() {
    final _randomSoruIndex = Random();
    final olusturulanRandomSayi = _randomSoruIndex.nextInt(19);
    return olusturulanRandomSayi;
  }

  // saniyeleri double degerine çeviriyoruz....

    setTime() {

          var timeSoFar = watch.elapsedMilliseconds;
          var gecenSureninIntHali = watch.elapsedMilliseconds.toInt();
          gecenSureDoubleDegeri = gecenSureninIntHali.toInt();
          setState(() {
            gecenSure = transformMilliSeconds(timeSoFar);
          });








  }

  transformMilliSeconds(int milliseconds) {
    int hundreds = (milliseconds / 10).truncate();
    int seconds = (hundreds / 100).truncate();
    int minutes = (seconds / 60).truncate();
    String minuteStr = (minutes % 60).toString().padLeft(2, '0');
    String secondsStr = (seconds % 60).toString().padLeft(2, '0');
    String horusStr = (hundreds % 60).toString().padLeft(2, '0');

    return "$minuteStr:$secondsStr:$horusStr";
  }

  Timer _updateTime(Timer timer) {
    setState(() {
      gecenSure = transformMilliSeconds(watch.elapsedMilliseconds);
    });




  }
}

**Comment by stuartmorgan** [comment]
Please see https://flutter.dev/community for general resources for open-ended questions and discussion. The issue tracker is specifically for bugs and feature requests.
