### ISSUE TITLE
Run stuck on `D/EGL_emulation(11219): eglMakeCurrent: 0xa450d500: ver 3 0 (tinfo 0x99df5d50)`

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#57179]
## Steps to Reproduce

Issue: I run the `main_app2.dart` and the console gets stuck on
```
Launching lib/main_app2.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Debug service listening on ws://127.0.0.1:54492/C8mZlfQcSh0=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(11219): eglMakeCurrent: 0xa450d500: ver 3 0 (tinfo 0x99df5d50)
```

`flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```

I don't know how to reproduce this issue. 

**Expected results:** 
I expected the app to just run

**Actual results:** 
White screen on Android emulator

<details>
  <summary>Logs</summary>

`flutter analyze` returns: https://gist.github.com/andesappal/c77f53454dc7766569a49eefa77dc104
(same 21 hints from Dart Analysis, they are not errors)
UPDATE May 21, 2020: all hints and errors corrected
</details>

**Comment by VladyslavBondarenko** [comment]
Hi @andesappal 
> I don't know how to reproduce this issue.

do you mean it happened only once?
are not you sure what steps you completed to meet the error or it doesn't reproduce when you are doing the same?

**Comment by andesappal** [comment]
Hi @VladyslavBondarenko, this issue is repeatedly and consistently happening, however, I can't share the code, and the project is so big I haven't been able to create a minimally working example. I am going through every file and re-writing anything that I see is incorrect. Can we leave this issue open until this Friday, and if it persists, we'll see what to do?

**Comment by VladyslavBondarenko** [comment]
@andesappal 
sure. Also it would be useful to know if it reproduces with another flutter version (for example current dev), or with other devices. And if you provide your `flutter run --verbose` log

**Comment by andesappal** [comment]
Hey @VladyslavBondarenko, thanks for the suggestions. I read through each file, corrected all hints (with zero errors), checked for any silent errors, and ran the project on the dev and stable channels, verbosely. 

`flutter run --verbose` on `flutter channel dev`: https://gist.github.com/andesappal/5461e9af2e38a54f84d2a283e6f43fa1
`flutter run --verbose` on `flutter channel stable`: https://gist.github.com/andesappal/a41222b976bcd32ada3cdb0fb7237b50

`main_app1.dart`: https://gist.github.com/andesappal/beaa16863221f450e0ae25846599faa3
`main_app2.dart`: https://gist.github.com/andesappal/a9e7d9af3be3e2e152cdae75934179c0

I can't find the hairy bug!

**Comment by andesappal** [comment]
Is there a more idiomatic way of having two `main` files?

**Comment by VladyslavBondarenko** [comment]
@andesappal 
default target file is `lib/main.dart` if you need to run another one use `-t` flag: 
`flutter run -t lib/main_app2.dart`.

> I can't find the hairy bug! 

Do you mean console is still stuck at `D/EGL_emulation(11219): eglMakeCurrent: 0xa450d500: ver 3 0 (tinfo 0x99df5d50)`?

**Comment by andesappal** [comment]
`flutter run -t lib/main_app2.dart --verbose` on `flutter channel dev`: https://gist.github.com/andesappal/370256a725c39b45d9e6449eddac9935

`flutter run -t lib/main_app2.dart --verbose` on `flutter channel stable`: https://gist.github.com/andesappal/6d50317e468bed9bafe24c7b090e238d

Yes, still stuck on `D/EGL_emulation(11219): eglMakeCurrent: 0xa450d500: ver 3 0 (tinfo 0x99df5d50)`

**Comment by andesappal** [comment]
For iOS, `run` gets stuck on `Xcode build`

**Comment by andesappal** [comment]
@VladyslavBondarenko do you think the issue might have to do with 
![image](https://user-images.githubusercontent.com/54340176/82514707-ce296480-9aec-11ea-89d3-ffc5c7ced5d0.png)

**Comment by andesappal** [comment]
@VladyslavBondarenko new information: With `flutter run --verbose` on `flutter channel beta` I get:
```
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for Android SDK built for x86 to report its views...
I/Choreographer(23685): Skipped 39 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(23685): eglMakeCurrent: 0xa11054e0: ver 3 0 (tinfo 0x8a268700)
Debug service listening on ws://127.0.0.1:54852/0u1NubCEh9Y=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(23685): eglMakeCurrent: 0xa8d62f00: ver 3 0 (tinfo 0xa8cbdbf0)
E/flutter (23685): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2611 pos 20: '_debugCurrentBuildTarget == context': is not true.
E/flutter (23685): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (23685): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (23685): #2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2611:20)
E/flutter (23685): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2615:12)
E/flutter (23685): #4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1044:13)
E/flutter (23685): #5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:925:7)
E/flutter (23685): #6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
E/flutter (23685): #7      _rootRun (dart:async/zone.dart:1180:38)
E/flutter (23685): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23685): #9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23685): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23685): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23685): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23685): #13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (23685): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23685): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (23685): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (23685): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23685): 
```

`flutter run -t lib/main_app2.dart --verbose` on `flutter channel beta`: https://gist.github.com/andesappal/91ed64568d3e9d86bd5f7f66f79898da

**Comment by andesappal** [comment]
What should I be looking for in `verbose`? I found 30 errors related to `"availabilityError" : "runtime profile not found",` wrt iOS devices, which shouldn't be a problem while running on the Android emulator, right? 

Then I also found 
```
[+13576 ms] E/flutter (23886): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2611
pos 20: '_debugCurrentBuildTarget == context': is not true.
[        ] E/flutter (23886): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
[        ] E/flutter (23886): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
```

`dart-timeline-2020-5-20.json`: https://drive.google.com/open?id=1qREXlraoUvF_RPBgbjB0Pk45UKKd-Vd8

`heap-profile.csv`: https://drive.google.com/open?id=1LQR1PKELaboJLRrMkJIyxY63gGNcQ00yMFJPhClJcY4

**Comment by andesappal** [comment]
@VladyslavBondarenko please help me find this bug, wherever it might be. It has brought me to a complete halt.

**Comment by VladyslavBondarenko** [comment]
@andesappal 
could you provide `flutter doctor -v` (with `-v` flag)?
are you experiencing the same with a new project?

**Comment by andesappal** [comment]
Hey @VladyslavBondarenko, `flutter doctor -v`:
```
Last login: Thu May 21 13:56:56 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
s-MBP:~ johnappleseed$ cd /Users/johnappleseed/AndroidStudioProjects/project 
s-MBP:project johnappleseed$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /Users/johnappleseed/development/flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/johnappleseed/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
s-MBP:project johnappleseed$ 
```
With a new project, I have no issues.

**Comment by andesappal** [comment]
I also separated all `main_app1.dart` associated directories into a new project, and it works. I am out of ideas for `main_app2.dart`.

**Comment by andesappal** [comment]
@VladyslavBondarenko a friend Felix A. helped me out. It was a circular reference and Google Maps issue. Thanks.
