### ISSUE TITLE
[Web] add HTTP headers support for NetworkImage

### ISSUE THREAD

**Issue by rakeshghasadiya** [flutter/flutter#57187]
Image loading on Android and iOS Application but in web version not working.

**Comment by VladyslavBondarenko** [comment]
Hi @rakeshghasadiya 
could you provide your `flutter doctor -v` and minimal complete reproducible code sample?

**Comment by rakeshghasadiya** [comment]
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.19.0-0.0.pre at /Users/rakesh/flutter
    • Framework revision a849daf283 (2 weeks ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rakesh/Documents/software/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/rakesh/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • iPad Air 2 • CD0906EB-032B-4F7C-A746-FD8ABB3680DE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!


Code Sample:


 
```
FadeInImage(
 fit: BoxFit.cover,
placeholder: AssetImage(Images.APP_LOGO),
image: getNetworkImage(
 url,
authKey),
width: documentCellSize,
 height: documentCellSize,)
```



```
NetworkImage getNetworkImage(String url,String authKey){
      Map<String, String> header = Map();
      header["Authorization"] = "$authKey";
      return NetworkImage(url,headers: header);
}
```

**Comment by rakeshghasadiya** [comment]
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.19.0-0.0.pre at /Users/rakesh/flutter
    • Framework revision a849daf283 (2 weeks ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rakesh/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/rakesh/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • iPad Air 2 • CD0906EB-032B-4F7C-A746-FD8ABB3680DE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!


Code Sample:


 
```
FadeInImage(
 fit: BoxFit.cover,
placeholder: AssetImage(Images.APP_LOGO),
image: getNetworkImage(
 url,
authKey),
width: documentCellSize,
 height: documentCellSize,)
```



```
NetworkImage getNetworkImage(String url,String authKey){
      Map<String, String> header = Map();
      header["Authorization"] = "$authKey";
      return NetworkImage(url,headers: header);
}
```

**Comment by TahaTesser** [comment]
Hi @rakeshghasadiya 
We don't have access the url and auth from your code so please provide `flutter run --verbose` with image loading
Thank you

**Comment by renefloor** [comment]
I was actually wondering why there wasn't an issue for this earlier. When making CachedNetworkImage for the web I found that NetworkImage just completely ignores the provided headers, so it has nothing to do with these specific headers.

It is even in the documentation that the headers are not used: https://api.flutter.dev/flutter/painting/NetworkImage/headers.html
"When running flutter on the web, headers are not used."

On desktop and mobile the image is downloaded using httpClient and then decoded. On web it is using an HtmlImageElement to load and show the image, however, that ImageElement doesn't have any support for headers.
The loading happens here: https://github.com/flutter/engine/blob/a0983d36f7bf2b4f45a5762ce40bb81d8a3f8f9f/lib/web_ui/lib/src/engine/html_image_codec.dart#L39

**Comment by TahaTesser** [comment]
@renefloor 
Does this look similar to this https://github.com/flutter/flutter/issues/39739?

**Comment by renefloor** [comment]
Not really
> Currently, the NetworkImage will create an http request, set headers, and use it.

For web it doesn't even set the headers and makes the request itself, it delegates it to ImageElement which doesn't have a possibility for headers. So before networkimage does the fetching itself it can't make it like #39739. 

It is about making web work like mobile, not adding new features.

**Comment by yjbanov** [comment]
A workaround is to implement a custom `ImageProvider` where you will have control over the network requests. Note, however, that on the Web this will require CORS handshake if you are loading images from another domain.

**Comment by renefloor** [comment]
@yjbanov that is exactly what I now did with CachedNetworkImage, but on the NetworkImage implementation the CORS handshake is not a problem? I guess 2 implementations might be better, one with and one without headers.

**Comment by lypborges** [comment]
When we build/run the app using `--web-renderer html` the headers are different if we use `--web-renderer canvaskit`.

For now we are building with html render as a workaround. But looks like the behavior should be the same.

**Comment by renefloor** [comment]
@lypborges the behaviour of html and canvaskit are different. In HTML the image is shown as <img> and the browser manages downloading and showing the image. In canvaskit the Flutter engine downloads the image with the build-in http client as it needs the draw the pixels itself. So with canvaskit you could manage the headers yourself, but with html the headers are set by the browser.

**Comment by Mateis** [comment]
> @lypborges the behaviour of html and canvaskit are different. In HTML the image is shown as and the browser manages downloading and showing the image. In canvaskit the Flutter engine downloads the image with the build-in http client as it needs the draw the pixels itself. So with canvaskit you could manage the headers yourself, but with html the headers are set by the browser.

Great, this insight made me solve the issue that the CORS image did load in my app on desktop web, but failed to load (error: 400 Headers required) using mobile web. 

I found out that the default render option uses html on mobile and canvaskit on desktop: https://flutter.dev/docs/development/tools/web-renderers

> The --web-renderer command line option takes one of three values, auto, html, or canvaskit.

    auto (default) - automatically chooses which renderer to use. This option chooses the HTML renderer when the app is running in a mobile browser, and CanvasKit renderer when the app is running in a desktop browser.
