### ISSUE TITLE
iOS status bar icons are invisible on Shrine.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5718]
Shrine makes the top icons (like time!!!) invisible on iOS until you scroll or select an item due to the background being white.

This might be an iOS bug, though. Need to look into it.

**Comment by eseidelGoogle** [comment]
How do other iOS applications handle this?

**Comment by dragostis** [comment]
@eseidelGoogle Text and icons changes to black. This happens on our app too, but only after something on the screen changes. (like a scroll) I'm seeing this on iOS 9.3.2.

**Comment by eseidelGoogle** [comment]
FYI @cbracken presumably this requires a bit more color coordination between our StatusBar class and the OS.

**Comment by markmooibroek** [comment]
Setting the Material primaryColor to white wil also make the statusbar inreadable in iOS.

Would be nice if we could set the statusbar text color to black. Doable on iOS and Android.

![simulator screen shot 13 may 2017 12 21 46](https://cloud.githubusercontent.com/assets/1412238/26024687/d2620e2a-37d6-11e7-8761-cad795c12870.png)

**Comment by abarth** [comment]
I believe this is triggered off `primaryColorBrightness` on the theme.  If you're using white, try setting this value to `Brightness.light` in your theme.

**Comment by abarth** [comment]
It would be neat if we set this automagically based on the color somehow.

**Comment by abarth** [comment]
I guess we could convert the primary color to HSV and then use a value threshold.
