### ISSUE TITLE
I have issue as described in details when press share button with share package  ^0.6.4+2

### ISSUE THREAD

**Issue by amir0f** [flutter/flutter#57197]
Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000035542d0 _UIActivityActionCellTitleLabel:0x7fb15b7601c0.height >= 22.6667   (active)>",
    "<NSLayoutConstraint:0x600003557ac0 V:|-(15)-[_UIActivityActionCellTitleLabel:0x7fb15b7601c0]   (active, names: '|':UIView:0x7fb15b76f4b0 )>",
    "<NSLayoutConstraint:0x600003557390 V:[_UIActivityActionCellTitleLabel:0x7fb15b7601c0]-(15)-|   (active, names: '|':UIView:0x7fb15b76f4b0 )>",
    "<NSLayoutConstraint:0x6000035500f0 'UIView-Encapsulated-Layout-Height' UIView:0x7fb15b76f4b0.height == 52   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000035542d0 _UIActivityActionCellTitleLabel:0x7fb15b7601c0.height >= 22.6667   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by amir0f** [comment]
The problem is with Iphone 11 pro.

**Comment by TahaTesser** [comment]
Hi @amir0f 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by amir0f** [comment]
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.14.6 18G4032, locale en-IQ)
    • Flutter version 1.15.17 at /Users/apple/Developer/flutter
    • Framework revision 2294d75bfa (2 months ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.2
    • Dart plugin version 191.7830

[✓] Connected device (3 available)
    • iPhone 11 Pro • CAD68E01-D022-4F32-A420-C76095F0A1E9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome        • chrome                               • web-javascript • Google
      Chrome 81.0.4044.138
    • Web Server    • web-server                           • web-javascript • Flutter
      Tools

• No issues found!

**Comment by amir0f** [comment]
import 'package:flutter/material.dart';
import 'package:share/share.dart';

class PostPage extends StatefulWidget {
  @override
  _PostPageState createState() => _PostPageState();
}

class _PostPageState extends State<PostPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: ListView(
        children: <Widget>[
          ListTile(
            title: Text('This is title!'),
            trailing: IconButton(
              icon: Icon(
                Icons.share,
              ),
              onPressed: () {
                Share.share('http://google.com');
              },
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by TahaTesser** [comment]
Hi @amir0f 
Running the code sample has no issue 

Can you please explain in detail about what you said in the detail?
 What is the issue is? How did you experience this?

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: PostPage(),
    );
  }
}

class PostPage extends StatefulWidget {
  @override
  _PostPageState createState() => _PostPageState();
}

class _PostPageState extends State {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: ListView(
        children: [
          ListTile(
            title: Text('This is title!'),
            trailing: IconButton(
              icon: Icon(
                Icons.share,
              ),
              onPressed: () {
                Share.share('http://google.com');
              },
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details> 

Thank you

**Comment by amir0f** [comment]
Hi @TahaTesser 
My code is as sent before, just simple code to show a share icon with link to website, when I press share on (simulator: Iphone 11 pro 13.3) in (Run tab) I get the following:
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
.
.
.
And rest of explanation as show in my first post.
I attach video to explain what happened.
https://drive.google.com/open?id=10rQX_laYujYPmK0czOV2uqyjbjTmnE8G

**Comment by amir0f** [comment]
Hi @TahaTesser 
Problem just solved by upgrading my flutter version to:
```
Flutter 1.18.0-11.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2738a1148b (2 days ago) • 2020-05-13 15:24:36 -0700
Engine • revision ef9215ceb2
Tools • Dart 2.9.0 (build 2.9.0-8.2.beta)
```
