### ISSUE TITLE
Canvas.drawCircle():  paint.isAntiAlias=false turns antialiasing ON

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5720]
![screenshot_20160901-145138](https://cloud.githubusercontent.com/assets/4136413/18185813/382eb852-7054-11e6-9b0f-8e0ebe3538a2.png)

**Comment by eseidelGoogle** [comment]
Is this always?  Or on a specific device/version. `flutter doctor` output might help. :)

**Comment by dragostis** [comment]
@eseidelGoogle Older version. Can't reproduce it right now because the buttons are not responsive. 😄

**Comment by HansMuller** [comment]
It looks like Skia has trouble rendering a circle with a very (very) large radius. We can just draw a straight line in this case.

**Comment by HansMuller** [comment]
The original screenshot is from a Samsung Galaxy S6.  The circle renders poorly but quite differently on an LG Nexus five.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/18219848/c116be8a-7121-11e6-9f98-b198202ab974.png)

**Comment by HansMuller** [comment]
After trying various mitigation strategies (just drawing a straight line is inadequate) I discovered that explicitly turning OFF antialiasing fixed the problem.  This implies (to me anyway) that we're inverting the SKIA antialiasing bit somewhere.

I will leave this bug open.

**Comment by Hixie** [comment]
Did you file a bug on Skia?

**Comment by eseidelGoogle** [comment]
@chinmaygarde  also was toggling antialiasing defaults for clips last week, unlikely, but possibly related.

**Comment by HansMuller** [comment]
I haven't filed a Skia bug yet, I wasn't able to reproduce the problem with https://fiddle.skia.org.  However I will file one.

**Comment by eseidelGoogle** [comment]
This seems pretty high priority if our antialiasing bit is getting flipped somewhere.  Thoughts @chinmaygarde or @Hixie?

**Comment by chinmaygarde** [comment]
Can you attach an SKP trace of the scene? That way we can be sure we are
not flipping the flag somewhere before rendering the picture.

**Comment by eseidelGoogle** [comment]
Outer is false, inner is true:
https://github.com/eseidelGoogle/flutter/commit/e152a8c9bbe678322f7ec2c294ff41d5cc1ff283

Looks like we have our bit flipped at the dart:ui layer or below.
![flutter_02](https://cloud.githubusercontent.com/assets/11857803/18524623/f8b3c888-7a6d-11e6-9e62-c90b943ce87c.png)

I tried getting an skp but couldn't: https://github.com/flutter/flutter/issues/5867

**Comment by HansMuller** [comment]
There doesn't seem to be a test case associated with this bug, so here we are:
```
class CirclePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final radius = 1000.0;
    final center = new Point(size.width / 2.0 - radius, size.height / 2.0);
    final Paint paint = new Paint()
      ..isAntiAlias = true
      ..strokeWidth = 1.0
      ..color = Colors.blue[500]
      ..style = PaintingStyle.stroke;
    canvas.drawCircle(center, radius, paint);
  }

  @override
  bool shouldRepaint(CirclePainter old) => false;
}

class CircleDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Circle')),
      body: new SizedBox.expand(
        child: new CustomPaint(painter: new CirclePainter())
      ),
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new CircleDemo()));
}
```

With `isAntiAlias: true` or just unspecified, since it's true by default, the result looks aliased:

![jaggy](https://cloud.githubusercontent.com/assets/1377460/20982964/8bb9cdce-bc6f-11e6-9c0f-215a638f0745.png)

With  `isAntiAlias: false`, antialiasing is turned on.

![smooth](https://cloud.githubusercontent.com/assets/1377460/20982990/a9cc7bd6-bc6f-11e6-9f95-bb4a720f20df.png)

**Comment by eseidelGoogle** [comment]
@chinmaygarde with the above, would you be willing to triage this further and pass to Skia if necessary?

**Comment by jason-simmons** [comment]
I can see this effect on a Nexus 4 with radius = 4000.0, strokeWidth = 12.0, and isAntiAlias = true.

The isAntiAlias flag seems to propagate down to Skia as expected.  GrRenderTargetContext::drawOval sees an SkPaint with isAntiAlias() turned on, and it goes through the should_apply_coverage_aa() code path with useHWAA = false.

The same drawing looks fine on a Nexus 9.

**Comment by eseidelGoogle** [comment]
If we believe this is skia, please file a bug at skbug.com (and link here) and we (or Chinmay) can track in our regular skia meetings.

**Comment by jason-simmons** [comment]
Filed a Skia issue: https://bugs.chromium.org/p/skia/issues/detail?id=6044

**Comment by jvanverth** [comment]
It looks like it could be Skia. If the math is being done in fp16, at radii of 1024 or greater we can only represent integers. which is not enough precision for the antialiasing calculations. Even at 512 to 1024 you're only getting 1/2 a pixel of precision. I'll see if setting the precision to highp for large radii will fix it.

**Comment by eseidelGoogle** [comment]
Looks like we currently disable antialiasing in two places:
https://github.com/flutter/flutter/search?q=isAntiAlias&type=Code&utf8=%E2%9C%93

**Comment by jvanverth** [comment]
https://skia-review.googlesource.com/c/6281/ should address most of the cases, except for some low-level mobile hardware and some MSAA.

**Comment by chinmaygarde** [comment]
This has been fixed and works as expected using an [updated version](https://gist.github.com/chinmaygarde/dec158c680b761ab7df0d161ef45da4e) of @HansMuller's gist.
