### ISSUE TITLE
Error 105 received from application: Isolate must be runnable

### ISSUE THREAD

**Issue by mscherer82** [flutter/flutter#57206]
Since v 1.17 I'm getting this error when I try to restart my app in the emulator. 

I'm able to run the app. When clicking "run" the first time the app is reloaded in the emulator. When clicking "run" a secont time the message "Error 105 received from application: Isolate must be runnable" appears. I'm using android studio.

Logs:
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Error 105 received from application: Isolate must be runnable
Restarted application in 2.352ms.
``` 

Doctor:

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale de-DE)
    • Flutter version 1.17.1 at C:\Users\Marc\flutter
    • Framework revision f7a6a7906b (34 hours ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Marc\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Marc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Marc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by VladyslavBondarenko** [comment]
Hi @mscherer82 
does this error reproduce on every hot-restart?
could you provide a minimal complete code sample to reproduce it?

**Comment by mscherer82** [comment]
Hi @VladyslavBondarenko ,
yes on every hot restart.  
I've created an empty project which worked fine. I've copied the pubspec and gradle files over and it still works fine. 
Do you have any suggestions how I can find out what causes this problem? It's very hard to continue with my work if I have to rebuild my app all the time.

**Comment by VladyslavBondarenko** [comment]
@mscherer82 
as an option you can try to remove one by one part of your project until the problem disappears, then add the last part back and try to remove something else.
Search among already filled issues if some of them are similar to your case (https://github.com/flutter/flutter/issues/34954, https://github.com/flutter/flutter/issues/26953 or other may be related).
And provide please your `flutter run -v` log (with `-v` flag there may be more details about the error).

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
