### ISSUE TITLE
Supporting Multi Touch on GestureDetector Widget

### ISSUE THREAD

**Issue by erickzanardo** [flutter/flutter#57211]
## Use case

GestureDetector is a very helpful widget, but it does not support using multi touch recognizers, I was wondering is there is a reason for that.

## Proposal

I have made a small test, I copied the code from the GestureDetector into our repository, added the MultiTap recognizer and its callbacks and it worked fine (you can see this [here](https://github.com/flame-engine/flame/blob/397f6379656e617700ffa86fc5b96266e6a8a69d/lib/game/gesture_detector.dart))

I am willing to submit a PR to address that, but I wanted to be sure if these recognizers can be included on this widget, or if they weren't included for any reason.

Thanks!

**Comment by TahaTesser** [comment]
Hi @erickzanardo 
Can you please take a look at this https://github.com/flutter/flutter/issues/11600 
Thank you

**Comment by erickzanardo** [comment]
Thanks for the response @TahaTesser 

I read the thread and was very informative, but it is still not clear to me if there is space to add the multi touch detectors inside `GestureDetector`, The `Listener` class is cool, but it is harder to use when comparing to the `GestureDetector`, and adding the multi touch to it seems quite simple to do. I will probably try to assemble a PR proposing that :)

**Comment by dkwingsmt** [comment]
Multi tap is designed to be an esoteric gesture and excluded from `GestureDetector`. We didn't want people accidentally using it without thinking about it closely. If you'd like to use it, you can still assign `MultiTapGestureRecognizer` to `RawGestureDetector` by following the code in gesture_detector.dart.

**Comment by erickzanardo** [comment]
> Multi tap is designed to be an esoteric gesture and excluded from `GestureDetector`. We didn't want people accidentally using it without thinking about it closely. If you'd like to use it, you can still assign `MultiTapGestureRecognizer` to `RawGestureDetector` by following the code in gesture_detector.dart.

Thanks for the Reply, that was exactly what I wanted to know, if this was intended, I will not bother to make a PR then. Thanks!
