### ISSUE TITLE
☂️ Provide a canonical mechanism for affecting UI from a non-UI action

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#57218]
Apps regularly want to respond to a stream of events that might be coming from non-UI related sources (such as network or platform channels). Common responses to such events might include:

- Navigating to a new page.
- Showing a dialog.
- Showing a snackbar.

Such events are typically not tied to the lifecycle of the "current page". The `BuildContext` of the code that invokes the action could be long gone when the action finally resolves. 

A few examples:

```dart
final value = await permissionPluginCall();
Navigator.of(context).pushNamed(‘xxx’);
```

```dart
try {
  final value = await someRpcCall();
} catch (e, st) {
  Scaffold.of(context).showSnackBar(...)
}
```

```dart
try {
  await someCode();
} catch (e, st) {
  ErrorDisplayWidget.of(context).handleException(...)
}
```

There are solutions around some of these problems such as [using NavigatorKey](https://www.filledstacks.com/post/navigate-without-build-context-in-flutter-using-a-navigation-service/) however, I have not seen a canonical way to grab a *valid* (aka current) context from _anywhere_ in the app.

The ideal outcome of this issue would be to have a pattern similar to `InheritedWidget.of(context)` which locates the current context for you. Something like `InheritedWidget.current`.

Workarounds I have seen are pretty terrible:
- Passing `BuildContext` around.
- Passing `State` around.
- Using APIs such as `context.findRenderObject().attached` to determine whether context is still valid.

**Comment by mehmetf** [comment]
I tried using `GlobalKey` to solve this at least for dialogs but even that does not work as expected.

```dart
Timer.periodic(const Duration(seconds: 5), (timer) {
      if (navigatorKey.currentState.mounted) {
        showDialog<void>(
          context: navigatorKey.currentContext,
          builder: (_) {
            return const Text('This is an annoying dialog');
          },
        );
      }
    });
```

If you try this, you are met with:

```
 Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.
```

which is surprising at first because I am using the NavigatorState's context.... Why can't it find the navigator? After all, I am able to push routes using the key....

Then a few seconds later, you realize that this is _Navigator's context_ whereas dialog needs to be generated in a widget which is descendant of Navigator. For people not familiar with Flutter's inherited widgets, this could lead to hours-long debugging session.

**Comment by HansMuller** [comment]
Here's a proposal for a new pair of widgets that address the problems raised in this issue. We've discussed how the widgets would be implemented, but the API sketch that follows primarily focuses on how the API would be used.

### Safely showing a Dialog

The following example method builds an app-specific dialog. It's static because the future support for restoring instance state when suspended apps are resumed on  Android, requires static Dialog builder methods. The context parameter will be below the dialog's navigator.

```dart
static Widget buildAlertDialog(BuildContext context) {
  return AlertDialog(
    title: Text('Hello World'),
    actions: <Widget>[
      FlatButton(
        child: Text('OK'),
        onPressed: () {
          Navigator.of(context).pop();
        },
      ),
    ],
  );
}
```

To safely show the dialog we'll need to find a "stable" BuildContext, i.e. one that's guaranteed to still be part of the Element tree when the dialog is shown. The new inherited `AppMessages` widget encapsulates such a BuildContext.  To show the dialog using AppMessages:

```dart
AppMessages.of(context).showDialog(builder: buildAlertDialog);
```

AppMessages will apply showDialog's builder parameter to a context that is below the MaterialApp's Navigator.

To show a dialog after an async operation has completed, use showDialogWhen():

```dart
AppMessages.of(context).showDialogWhen(builder: (BuildContext context) async {
  await someNetworkOperation();
  return buildAlertDialog(context);
});
```

### Safely showing SnackBars

In terms of API, the support for SnackBars is similar. The BuildContext passed to SnackBar building methods will be below the Scaffold. Given a example method that builds a SnackBar:

```dart
static SnackBar buildSnackBar(BuildContext context) {
  return SnackBar(
    content: Text('Hello World'),
  );
}
```

The ScaffoldMessages `showSnackBar` method makes its SnackBar appear on Scaffolds that are above the inherited ScaffoldMessages widget:

```dart
ScaffoldMessages.of(context).showSnackBar(builder: buildSnackBar);
```

To display a SnackBar when an async operation has completed, use `showSnackBarWhen`:

```dart
ScaffoldMessages.of(context).showSnackBarWhen(builder: (BuildContext context) async {
  await someNetworkOperation();
  return buildSnackBar(context);
});
```

The implementation of ScaffoldMessages is considerably different from AppMessages because the app may have many Scaffolds. All of the Scaffolds below the inherited ScaffoldMessages widget will show the SnackBar, although except in unusual situations, only one snack bar will be visible.

**Comment by mehmetf** [comment]
This API might not be well suited for the use cases described above.

In the case of:

```dart
try {
  final value = await someRpcCall();
} catch (e, st) {
  Scaffold.of(context).showSnackBar(...)
}
```

We don't want to show a snackbar *every time* so wrapping this in a `showSnackbarWhen` feels awkward. It feels like we are supposed to always return a snackbar widget; which isn't the case here.

Something like this would be ideal:

```dart
try {
  final value = await someRpcCall();
} catch (e, st) {
  AppMessages.of(context).showDialog(...);
}
```

but then isn't that the same problem as before?

May be we can have something like:

```dart
AppMessages.of(context).mayBeShowDialog(builder: (context) async {
  try {
    final value = await someRpcCall();
    return null;
  } catch (e, st) {
    return dialogBuilder(context);
  }
});
```

This doesn't feel like a friendly API since it is not readable (return null?). The ordering is also messed up (showDialog appears first but then it depends on the result of something that comes later).

I am also not clear how:

```dart
AppMessages.of(context).showDialogWhen(builder: (BuildContext context) async {
  await someNetworkOperation();
  return buildAlertDialog(context);
});
```

helps the current situation. If user navigates away from the page during `someNetworkOperation`, isn't that context invalid now? Is the callback being called with a different context that stays valid? If so, why could I not do:

```dart
final messageController = AppMessages.of(context);
try {
  final value = await someRpcCall();
} catch (e, st) {
  messageController.showDialog(...);
}
```

since AppMessages knows which context to use already?

**Comment by HansMuller** [comment]
The idea was that AppMessages.of(context) would return a AppMessagesController, which can safely be used later. Likewise for ScaffoldMessages.of(context). 

The showFooWhen() methods were supposed to be a convenience, but you're right that they're ill-suited to conditionally showing a message.

**Comment by mehmetf** [comment]
Yep. That works ergonomically. 

I would have preferred not to have to grab the `AppMessages` from context since its lifecycle is not tied to that context. I also fully expect apps to pass this object around. You can expect the code I have written above that initiates the RPC call to be buried 5 layers down some business logic and not having access to `State` or `Context`.

That's why a singleton AppMessages works best for this scenario. MaterialApp/WidgetsApp sets up such a singleton that can be accessed from anywhere in the app. When these alerts are being shown, context doesn't matter. 

I fully expect apps to do something like this:

```dart
// Top level fn
AppMessages get dialogController => _dialogController;

class MainApp {
  // some initialization code
  return MaterialApp(
      ...,
      builder: (context) {
         _dialogController = AppMessages.of(context);
         ...
      }
  );
}
```

Then everywhere else in the app just calls `dialogController.showDialog()`. Are we OK with that?

**Comment by HansMuller** [comment]
By default, the value of AppMessages.of(context) would have the same lifetime as the app. So if you create a global variable whose value is updated each time the app is rebuilt, and callers use the global variable rather than a stale value, then yes that will work.

Updating the value in the MaterialApp's builder callback wouldn't work though, since the AppMessages widget must be below the app's Navigator.

**Comment by mehmetf** [comment]
I assume `WidgetsApp` creates top-level Navigator. What would be the best place to set this global variable then?

**Comment by HansMuller** [comment]
The widget that builds the MaterialApp could also reset _dialogController.

**Comment by mehmetf** [comment]
A sample app that does that would go a long way :-).

**Comment by mehmetf** [comment]
Gentle ping. Do we have any progress here Hans? Your proposal looks good to me. We just need a couple of sample apps to demo the API.

**Comment by HansMuller** [comment]
Do we need both the snack bar and the dialog solution, or is this really just about showing dialogs?

**Comment by mehmetf** [comment]
It is OK to deliver Dialog first but we would need both. Apps use both of these patterns to communicate screen-independent messaging to users.

In fact, I would say snackbar is higher priority because if you want to display a status message out of context, you likely don't want it to be interrupting (like a Dialog).

**Comment by HansMuller** [comment]
I'm assuming that the proposal for dealing with Snackbars looked OK? The discussion has focused on dialogs so far.

**Comment by mehmetf** [comment]
The following should apply to Snackbar controller as well:

> By default, the value of AppMessages.of(context) would have the same lifetime as the app. So if you create a global variable whose value is updated each time the app is rebuilt, and callers use the global variable rather than a stale value, then yes that will work.

We should not expect people to keep track of Scaffold instances. The controller should be able to find the "current scaffold" somehow.

> Updating the value in the MaterialApp's builder callback wouldn't work though, since the AppMessages widget must be below the app's Navigator.

I assume this will be different as the controller should be instantiated below a Scaffold. That's fine.

**Comment by HansMuller** [comment]
> The implementation of ScaffoldMessages is considerably different from AppMessages because the app may have many Scaffolds. All of the Scaffolds below the inherited ScaffoldMessages widget will show the SnackBar, although except in unusual situations, only one snack bar will be visible.

**Comment by Piinks** [comment]
Had a chat with @HansMuller regarding this...
I would like to add the `MaterialBanner` into consideration for this as well, forming a unified notification palette that is available app-wide. This is from the MD spec:

![Screen Shot 2020-06-22 at 3 36 33 PM](https://user-images.githubusercontent.com/16964204/85341901-2d88e480-b49e-11ea-983a-923c7410ac24.png)

Visuals for reference:

#### Snackbar
- Would fall under the `ScaffoldMessages` api from discussion above.
![Screen Shot 2020-06-22 at 3 37 36 PM](https://user-images.githubusercontent.com/16964204/85342001-688b1800-b49e-11ea-9cd6-a3a95dd469b5.png)

#### Banner
- Needs updating to match material spec, should be incorporated into `Scaffold` for proper placement and animation - see https://github.com/flutter/flutter/issues/60024
- Would fall under the `ScaffoldMessages` api from discussion above once the `Scaffold` supports it.
![Screen Shot 2020-06-22 at 3 37 24 PM](https://user-images.githubusercontent.com/16964204/85342006-6e80f900-b49e-11ea-9356-a3e47a78970f.png)

#### Dialog
- Would fall under the `AppMessages` api from discussion above.
![Screen Shot 2020-06-22 at 3 37 44 PM](https://user-images.githubusercontent.com/16964204/85342027-75a80700-b49e-11ea-9066-36167be4de6b.png)

**Comment by Piinks** [comment]
I am experimenting with a couple of different designs for this, I'll link a design doc once I have it available.

After discussing with @HansMuller and @goderbauer and considering #60619,

- I am not going to pursue `ScaffoldMessenger` (or whatever it will be called) as a global singleton right now as suggested by @mehmetf above. We think the developer should retrieve the `ScaffoldMessenger` themselves.
- I am approaching **SnackBar**s first since mentioned above as first priority.
- regarding **Routes**, there is currently a way that you can achieve the described expectation above. Let me know if this does not meet your need:
```dart
NavigatorState rootNavigator = Navigator.of(context, rootNavigator: true);
final value = await permissionPluginCall();
rootNavigator.pushNamed(‘xxx’);
```
- regarding **Dialog**s, it may be that the right solution is to offer an API that allows developers to use the `Navigator` directly to push `Dialog`s. Right now, `showDialog` takes the _current_ context, which is what causes the problem in the use case described above. By using the `Navigator`, you can apply the same solution described in the preceding bullet to use the root navigator.

I've been putting together a design doc and sample app to illustrate and test all of these use cases, I'll share once I have those ready for review!

**Comment by mehmetf** [comment]
Thanks Kate!

As I mentioned in https://github.com/flutter/flutter/issues/57218#issuecomment-631541624, I am OK with this solution however the framework needs to advise apps on how to display dialogs or navigate to routes where there's no valid context or widget or state available. That is the crux of the problem. In other words:

```dart
NavigatorState rootNavigator = Navigator.of(context, rootNavigator: true);
final value = await permissionPluginCall();
rootNavigator.pushNamed(‘xxx’);
```

does not work because in complex applications, `permissionPluginCall` is not actually in the `State`. It is buried deep down in some model layer code. Moreover, 50 different widgets need to make the exact same call so usually call to model layer code is buried under some common layer code. Keeping track of context from the call site gets extremely tricky so apps start storing it and passing it around, which we all agree, is wrong.

So, we need to come up with a suggestion. For instance, would it be safe to store rootNavigator as part of global application context and pass it around?

**Comment by goderbauer** [comment]
> permissionPluginCall is not actually in the State. It is buried deep down in some model layer code.

It sounds like the pattern here is that people want to push dialogs directly from their model code. Instead, I would have expected that whenever `permissionPluginCall` returns it modifies the model with the result. Something that is in the widget tree (and hence has access to a valid context) would listen to that change and then update the UI accordingly.

**Comment by goderbauer** [comment]
The new Router will make that approach (adding/removing routes based on the current state of the app model) easier.

**Comment by Piinks** [comment]
@chunhtai mentioned in #60619 That you can also use the root navigator to handle showing dialogs safely when the context is no longer valid, so using the really simple example from earlier:
```dart
NavigatorState rootNavigator = Navigator.of(context, rootNavigator: true);
final GlobalKey<NavigatorState> rootNavigatorKey = GlobalKey();

final value = await permissionPluginCall();

// Routes
rootNavigator.pushNamed(‘xxx’); 
// Could also do:
rootNavigatorKey.currentState.pushNamed('xxx');

// Dialogs
showDialog(
  context: rootNavigatorKey.currentContext,
  builder: ...
);
```

**Comment by mehmetf** [comment]
> Something that is in the widget tree (and hence has access to a valid context) would listen to that change and then update the UI accordingly (e.g. show that new route).

This is difficult for users to implement for complex apps. I was hoping we could supply it as part of the framework (which is what this issue is about).

For dialog, for instance, the "model" is whatever is needed to show the dialog: title, body, buttons (and actions). I was hoping we could come up with a framework API that lets them do:

```
// This really just modifies some sort of Flutter "model" that is listened by some Flutter standard widget as part of `WidgetsApp`.
showDialog(title, body, buttons ...);
```

and we take care of listening for that change and displaying dialog.

The point is that context doesn't matter for these actions. They are not a reaction to user action. They might not even be owned by the current screen.

**Comment by mehmetf** [comment]
Here's an example of a confused Flutter beginner trying to figure out how to show snackbars when their data is loading: cl/319939082.

**Comment by Hixie** [comment]
This doesn't really seem like a P2. It's not really clear that it even makes sense as a framework feature... doesn't it depend entirely on what the application is like?

**Comment by mehmetf** [comment]
Given how frequently and quickly apps run into this and the type of bad patterns it encourages (see https://github.com/flutter/flutter/issues/57218#issue-618329979), I would keep the P2.

> It's not really clear that it even makes sense as a framework feature...

If it is feasible to make this a package, great! Perhaps we can brainstorm what that package should look like.

> doesn't it depend entirely on what the application is like?

Hopefully not. We have seen many bad patterns emerge when applications try to solve this on their own.

**Comment by Hixie** [comment]
Things you might want to do when your app receives some out-of-band message:
* Show a dialog
* Hide a dialog
* Show a snackbar
* Update some widget being shown on the screen, e.g. a progress bar, or list of files, or chat history, or a clock
* Navigate to a new route
* etc...

How can any meaningfully useful API cover all these use cases in a coherent manner?

I don't understand why this isn't just the same as reacting to _any_ change in app state.

**Comment by mehmetf** [comment]
Michael asked a similar question. I responded with https://github.com/flutter/flutter/issues/57218#issuecomment-652671562. 

We are not talking about all (re)actions here. In Flutter terms, these out of band actions are out of "current" context. Showing a dialog and showing a snackbar (common) and navigating to a new route (less common) are the only examples we have so far. Curiously, they all seem to follow the `SomeWidget.of(context).modifyUI()` type of API which is not the norm for Flutter. It almost feels imperative.

I will noodle on this a bit more and see if I can come up with a pattern that I am happy recommending to internal clients.

**Comment by Hixie** [comment]
navigating to a new route will soon no longer (need to be) be imperative, once Router lands. Dialogs are just routes.
Snackbars are tricky for various reasons but Kate has some work on changing how those work; I recommend commenting on her design doc if you have ideas for how to make that more manageable.

**Comment by mehmetf** [comment]
I had tried using `navigatorKey` and it had not worked before. I just tried again it now works as expected!! Perhaps an underlying bug got fixed in the past 2 months? @chunhtai @Piinks 

Let me know what you think of this pattern.

A simple dialog service class:

```dart
class DialogService {
  final GlobalKey<NavigatorState> navigatorKey;

  DialogService(this.navigatorKey);

  Future<T> show<T>(WidgetBuilder dialogBuilder) {
    assert(navigatorKey.currentState.mounted);
    return showDialog<T>(
      context: navigatorKey.currentContext,
      builder: dialogBuilder,
    );
  }
}
```

is instantiated as a service and injected:

```dart
void main() {
  // Create services.
  // Normally this would be injected to the app.
  _dialogService = DialogService(GlobalKey());
  runApp(MyApp());
}
```
then use the navigator key:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: _dialogService.navigatorKey,
      title: 'Flutter Demo',      ...
    );
  }
}
```

From anywhere in the app, inject `_dialogService` and call:

```dart
_dialogService.show((BuildContext context) {
  // Build dialog widget.
});
```

Instead of a dialog service, we can expose a NavigatorService but this is the basic idea.

**Comment by chunhtai** [comment]
The navigator key can be used after this pr https://github.com/flutter/flutter/pull/58259

**Comment by Hixie** [comment]
I'm still a little unclear as to what a solution here would look like or what would be sufficient to resolve this issue.

**Comment by goderbauer** [comment]
My understanding is that we are resolving the concrete case of the SnackBack with Kate's SnackbarMessanger work. The Navigator use case is already sorted out as pointed out by @chunhtai above.

**Comment by mehmetf** [comment]
Right. Perhaps a more focused issue can be filed to track Kate's work. If so, you can close this issue.

**Comment by Piinks** [comment]
Thanks @mehmetf! Filed:https://github.com/flutter/flutter/issues/62921
