### ISSUE TITLE
[Android] Supporting International Phonetic Alphabet

### ISSUE THREAD

**Issue by dodaithach** [flutter/flutter#57212]
## Use case

For dictionary apps, there's a need for displaying International Phonetic Alphabet (IPA) for each vocabulary. It seems like we cannot achieve it at the moment.

Here's a simple piece of code for my use case:
```
// ...
RichText(
  text: TextSpan(
    text: "ˌɪn.fɚˈmeɪ.ʃən",
      style: textTheme.bodyText1.copyWith(
        color: colorScheme.onSurface,
      ),
   ),
),
// ...
```

Outcome:
![Screenshot 2020-05-14 at 9 17 32 PM](https://user-images.githubusercontent.com/11256533/81939046-65437780-9628-11ea-8c73-1b4e675916f3.png)

## Proposal

I think this feature should be supported by the Flutter framework.

This is what we should be able to achieve.

![Screenshot_20200514-212027_TFlat Dictionary](https://user-images.githubusercontent.com/11256533/81940738-7d1bfb00-962a-11ea-8d8e-e2fb10849cd9.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @dodaithach 
what flutter version are you using?
With current dev `1.19.0-1.0.pre` I can see

I can see the symbols are rendered

iOS
![image](https://user-images.githubusercontent.com/17024977/81946912-9b70ff00-9608-11ea-811d-dbbe85eb2db9.png)

web
![image](https://user-images.githubusercontent.com/17024977/81947131-df640400-9608-11ea-89a5-412761846921.png)

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: RichText(
          text: TextSpan(
            text: "ˌɪn.fɚˈmeɪ.ʃən",
            style: TextStyle(
              color: Colors.black,
            )
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by dodaithach** [comment]
Hi @VladyslavBondarenko, the issue happened on Android. Here's the result of `flutter --version`.
```
Flutter 1.19.0-0.0.pre • channel unknown • unknown source
Framework • revision a849daf283 (7 days ago) • 2020-05-07 18:59:02 -0700
Engine • revision 3953c3ccd1
Tools • Dart 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)
```

**Comment by VladyslavBondarenko** [comment]
@dodaithach 
I tried with current dev and `1.19.0-1.0.pre` and stable `1.17.1`.
On Redmi Note 7 Android 9 (API 28) and Android 10 (API 29) (emulator) symbols are rendered correctly.
What device are you using? Are you experiencing this with the complete code sample from my previous comment?

**Comment by dodaithach** [comment]
I tried your code and it worked just fine. But when I applied a different style to it, it didn't work. This is how I built my widget.
```
final colorScheme = Theme.of(context).colorScheme;

final baseTextTheme = ThemeData.light().textTheme;
final textTheme = GoogleFonts.ralewayTextTheme(baseTextTheme.copyWith(
  headline6: baseTextTheme.headline6.copyWith(
    fontWeight: FontWeight.w600,
    fontSize: 20,
  ),
));
final textStyle = textTheme.headline6.copyWith(
  color: colorScheme.onSurface,
);

return Card(
  elevation: cardElevation,
  margin: EdgeInsets.zero,
  shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.all(mediumComponentCornerRadius)),
  color: colorScheme.surface,
  child: Padding(
    padding: const EdgeInsets.all(commonSpace),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.only(top: commonSpace),
          child: RichText(
            text: TextSpan(
              text: "ˌɪn.fɚˈmeɪ.ʃən",
              style: textStyle,
            ),
          ),
        ),
      ],
    ),
  ),
);
```
![Screenshot 2020-05-15 at 4 45 11 PM](https://user-images.githubusercontent.com/11256533/82030778-772a2680-96cb-11ea-8824-3e057d67ee78.png)

**Comment by VladyslavBondarenko** [comment]
@dodaithach 
You can see that most of the google fonts [don't support these characters](https://fonts.google.com/?preview.text=%CB%8C%C9%AAn.f%C9%9A%CB%88me%C9%AA.%CA%83%C9%99n&preview.text_type=custom), 
[and raleway font is among them](https://fonts.google.com/specimen/Raleway?preview.text=%CB%8C%C9%AAn.f%C9%9A%CB%88me%C9%AA.%CA%83%C9%99n&preview.text_type=custom).

From another side if you are still using google fonts, but with for example notoSerif - they are rendered correctly.
<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: RichText(
          text: TextSpan(
            text: "ˌɪn.fɚˈmeɪ.ʃən",
            style: GoogleFonts.notoSerif(
              textStyle: TextStyle(color: Colors.black),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

Closing since this is not an issue with flutter
