### ISSUE TITLE
urllauncher 5.4.7 WebViewActivity.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Abhijithsp** [flutter/flutter#57219]
Parameter format not correct -
Note: E:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.7\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.

Every time i try to debug mode also release mode,Just a warning,nothing on flutter doctor

**Comment by Zazo032** [comment]
I did some work around this on https://github.com/flutter/plugins/pull/2737

**Comment by Abhijithsp** [comment]
What should i do,update or manually edit it...?

**Comment by iapicca** [comment]
Hi @Abhijithsp 
I see there's an open [issue](https://github.com/flutter/flutter/issues/37616) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Abhijithsp** [comment]
I have no problem,it's the same problem,that comes with latest version too @iapicca
