### ISSUE TITLE
Proposal: New UI for Licenses Page.

### ISSUE THREAD

**Issue by TonicArtos** [flutter/flutter#57226]
@Hixie I am opening this issue as you suggested.

## Use case

#18281 raised the issue that the existing license page could be improved upon. Especially as the list of licenses has many versions of the same license repeated. In fact, the package **boringssl** has some 76 licenses referenced in the framework. This issue can make the license page *hard to navigate* to view licenses for other packages. The current design may also *appear broken to end users*.

## Proposal

Change to a package first navigation of the registered licenses. I suggest implementing this using a Master Detail Flow.

I have written and hosted an [example](https://tonicartos.github.io/mdflow-licenses-sample/) to show roughly how the new UI would look and behave. The screenshots below are from that example application.

I welcome feedback and I am happy to put in the work to see this through. If you will have me.

**Screenshot of page showing licensed packages (small to medium displays)**
![LicensedPackagesPage](https://user-images.githubusercontent.com/296142/81965647-ee6ba600-964a-11ea-9a66-b0e8fc860a9b.png)

**Screenshot of page showing licenses for selected package (small to medium displays)**
![LicensePage](https://user-images.githubusercontent.com/296142/81965720-10fdbf00-964b-11ea-9042-f7c4597249d0.png)

**Screenshot of master detail page showing licensed packages and licenses for selected package (large displays)**
![MasterDetailLicensesPage](https://user-images.githubusercontent.com/296142/81965732-13601900-964b-11ea-9e87-9c51da4711cb.png)

**Comment by Hixie** [comment]
This looks fantastic. Make it so!

(One minor nitpick, I'd remove the word "registered" from the list, just "1 license", "2 licenses", etc.)

**Comment by timsneath** [comment]
Yeah, I love it! I agree that this is a significant improvement over the current page.

**Comment by TonicArtos** [comment]
I am getting to work on this.

@Hixie As requested, I will remove the word "registered".

I do have a question. I have not found a Cupertino equivalent of the Material About dialogue or License page. Is this an oversight? Should I implement versions of these for the Cupertino package as well?

**Comment by Hixie** [comment]
That's definitely an oversight and I would welcome Cupertino versions. I recommend filing a separate bug so that we can track that separately.

**Comment by devmgs** [comment]
After watching [youtube channel link](https://www.youtube.com/watch?v=YFCSODyFxbE) i thought to use this for license but after using found that i had many references of the same package. So its completely useless.
I wish this view was available.

**Comment by jaumard** [comment]
Would be nice to have a generic widget like `LicenseContent()` that doesn't include material appBar, like this it can be reuse for Material, Cupertino or even other widgets library like Neumorphic.
