### ISSUE TITLE
Gallery example app crashes on launch, dependent dylib '@rpath/Flutter.framework/Flutter'

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#57225]
### Reproduction Steps:
Reproducing on master and stable.

Delete any previous versions of Flutter Gallery from the device.
```
$ cd dev/integration_tests/flutter_gallery
$ flutter clean 
$ git clean -dfX
$ rm -rf ~/Library/Developer/Xcode/DerivedData/*
$ flutter run --debug
```

App crashes on launch, `flutter` stuck on `Application launched on the device. Waiting for observatory port.`

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/Flutter.framework/Flutter' not found for '/private/var/containers/Bundle/Application/C582E1E9-F19B-4E9C-9C03-2F0CBA1132F7/Flutter Gallery.app/Flutter Gallery'. vm_copy() failure
Highlighted by Thread:  0
```

[Flutter Gallery  5-13-20, 6-45 PM.crash.log](https://github.com/flutter/flutter/files/4629982/Flutter.Gallery.5-13-20.6-45.PM.crash.log)

However, subsequent launches of the app (launching it manually on the phone) do not crash!

Flutter.framework is being copied to the normal `Flutter Gallery.app/Frameworks` spot.  `@rpath` looks correct:
```
$ otool -l build/ios/iphoneos/Flutter\ Gallery.app/Flutter\ Gallery
...
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/Flutter.framework/Flutter (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 14
...
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 28
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 29
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 30
```
[otool.log](https://github.com/flutter/flutter/files/4630059/otool.log)

It's getting copied during install:
```
[        ] [  7%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/ to device
[        ] [  7%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [  7%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[        ] [  7%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/icudtl.dat to device
[ +141 ms] [  8%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/Flutter to device
[ +805 ms] [ 13%] Copying /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/iphoneos/Flutter Gallery.app/Frameworks/Flutter.framework/Info.plist to device
```
[run.log](https://github.com/flutter/flutter/files/4630062/run.log) (this log is from trying to repro the driver test but a normal `flutter run` has the same install logs)

Device log when it crashes is complaining about a Bad file descriptor:
```
	default	19:40:29.639013-0700	debugserver	1 +0.000000 sec [04d1/0407]: Disabling breakpoints and watchpoints, and detaching from 1234.
	default	19:40:29.639192-0700	debugserver	2 +0.000091 sec [04d1/0407]: error: ::ptrace (request = PT_THUPDATE, pid = 0x04d2, tid = 0x4b03, signal = -1) err = Invalid argument (0x00000016)
	default	19:40:29.639238-0700	debugserver	3 +0.000358 sec [04d1/1907]: error: ::read ( -1, 0x16d7deb08, 1024 ) => -1 err = Bad file descriptor (0x00000009)
	default	19:40:29.639270-0700	debugserver	Exiting.
com.apple.runningboard	default	19:40:29.639746-0700	runningboardd	[executable<debugserver>:1233] Death sentinel fired!
com.apple.runningboard	default	19:40:29.640290-0700	runningboardd	[application<io.flutter.examples.gallery>:1234] Death sentinel fired!
com.apple.runningboard	default	19:40:29.643165-0700	runningboardd	XPC connection invalidated: [executable<debugserver>:1233]
```

It's reproducing on:
- flutter-devicelab-mac-11 Xcode 11.0/iPhone 4s 32-bit iOS 9.3.6 in the `flutter_gallery_ios32__transition_perf` test
- flutter-devicelab-mac-1 Xcode 11.3/iPhone 6s iOS 13.1.3 in the `flutter_gallery_ios__transition_perf` test
- On my machine Xcode 4 and Xcode 11.5 beta 2 iPhone 6s iOS 13.4.1.
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.21, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.19.0-2.0.pre.21 at /Users/m/Projects/flutter
    • Framework revision 7f400af35a (2 days ago), 2020-05-12 07:35:02 -0700
    • Engine revision 156970a248
    • Dart version 2.9.0 (build 2.9.0-8.0.dev 4e520824f5)

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Users/m/Applications/Xcode-11-5-beta2.app/Contents/Developer
    • Xcode 11.5, Build version 11N605f
    • CocoaPods version 1.9.0
```

**Comment by jmagman** [comment]
The biggest head-scratcher here is that it doesn't crash on the second launch.  So it is getting embedded to the right path, dyld is eventually happy, but just not when the debugger launches it?

**Comment by gaaclarke** [comment]
Are you sure the architecture of the library you are trying to load is correct?  Sometimes binaries are trimmed to just one architecture for debug builds.

**Comment by jmagman** [comment]
It repros in profile and release, and it wouldn't link at all during the host build if the architectures weren't correct.

**Comment by jmagman** [comment]
Faster reproduction steps:
```
$ flutter create test_link
$ cd test_link
```
Copy the [flutter_gallery's dependencies](https://github.com/flutter/flutter/blob/master/dev/integration_tests/flutter_gallery/pubspec.yaml#L7-L40) to the pubspect.yaml
```
$ flutter build ios --debug
```
Now, you can run this over and over to reproduce:
```
$ <flutter>/bin/cache/artifacts/ios-deploy/ios-deploy --id <device-id> --bundle build/ios/iphoneos/Runner.app --no-wifi --uninstall --justlaunch 
```

Notes:
1. I was able to reproduce this on v1.12.13-hotfixes, so this isn't a recent regression.
1. I ran the above `ios-deploy` command on my machine with the iPhone 6s and it crashed 4 of 20 times.
1. If I don't copy over the flutter_gallery's dependencies it never crashes.  So a fresh `flutter create` app doesn't crash.
1. `ios-deploy` with `--noninteractive` (launch debugger and wait) instead of `--justlaunch` (launch debugger and quit) also never crashes.
1. This manifests to the user as the tool being stuck waiting for the observatory if they don't notice that the app launched and immediately crashed since the tool doesn't have the capacity to capture crash logs at the moment.  So how many "discovery" issues are really just this?

My guess is that there's a race between the ios-deploy `AMDeviceSecureInstall` call being complete and all files being copied to their final location on disk on device.  I wasn't able to reproduce this without copying over the flutter_gallery dependencies, which makes me think it crossed some size threshold on my particular devices that made it start to manifest.
`flutter_gallery_ios32__transition_perf` may be particularly flaky because the older iPhone 4s has slower I/O.  I don't know why this started manifesting in the devicelab in the last week.

**Comment by jmagman** [comment]
The device sure thinks it's fully installed before the crash, so I don't know what's racing here.
```
default	21:00:55.679662-0700	installd	0x16b0d7000 -[MIInstaller performInstallationWithError:]: Install Successful for (Developer:com.example.testLink); Staging: 0.01s; Waiting: 0.00s; Preflight/Patch: 0.06s, Verifying: 0.65s; Overall: 0.82s
default	21:00:56.007736-0700	runningboardd	com.example.testLink:5:8:3:1:applicationsDidInstall <LSApplicationProxy: 0x1042960e0> com.example.testLink file:///private/var/containers/Bundle/Application/D3FB173A-A2E0-4150-8154-5E04E5A1E588/Runner.app/ <com.example.testLink <installed >:0>
...
default	21:01:03.896668-0700	debugserver	Got a connection, launched process /private/var/containers/Bundle/Application/D3FB173A-A2E0-4150-8154-5E04E5A1E588/Runner.app (pid = 886).
...
default	21:01:04.019418-0700	debugserver	3 +0.000380 sec [036d/1607]: error: ::read ( -1, 0x16f32eb08, 1024 ) => -1 err = Bad file descriptor (0x00000009)
com.apple.runningboard	default	21:01:04.019543-0700	runningboardd	[application<com.example.testLink>:886] Death sentinel fired!
```

**Comment by cristian1980** [comment]
Hello,

I am experiencing this issue too in a separate application. 
The application is crashing before Dart debugger can attach to it.
I am pretty new to flutter and working without debugger is causing me to waste a lot of time. XCode debugger is working when stating the application from XCode, but that does not work for Dart.
Similarly, subsequent launches of the app (launching it manually on the tablet) do not crash!

Thank you for any help!

I attached my crash log from the Device logger:

> Incident Identifier: 85681A9B-491D-41E1-9AE7-39204CF5179E
> CrashReporter Key:   955789e79948ef71afb44be03439184db7c3d819
> Hardware Model:      iPad7,11
> Process:             Runner [534]
> Path:                /private/var/containers/Bundle/Application/F7FBD9F5-7F66-4F45-A9F2-F012B1AACB62/Runner.app/Runner
> Identifier:          com.h.hhhhh
> Version:             1 (1.0.0)
> Code Type:           ARM-64 (Native)
> Role:                Foreground
> Parent Process:      launchd [1]
> Coalition:           com.h.hhhh [499]
> 
> 
> Date/Time:           2020-09-07 18:58:40.5357 +0300
> Launch Time:         2020-09-07 18:58:40.3469 +0300
> OS Version:          iPhone OS 13.7 (17H35)
> Release Type:        User
> Baseband Version:    n/a
> Report Version:      104
> 
> Exception Type:  EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note:  EXC_CORPSE_NOTIFY
> Termination Description: DYLD, dependent dylib '@rpath/Flutter.framework/Flutter' not found for '/private/var/containers/Bundle/Application/F7FBD9F5-7F66-4F45-A9F2-F012B1AACB62/Runner.app/Runner'. vm_copy() failure
> Highlighted by Thread:  0
> 
> Backtrace not available
> 
> Unknown thread crashed with ARM Thread State (64-bit):
>     x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f69d330   x3: 0x0000000000000097
>     x4: 0x000000016f69cf30   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
>     x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x6d76202e2772656e  x11: 0x20292879706f635f
>    x12: 0x6e75522f7070612e  x13: 0x6d76202e2772656e  x14: 0x20292879706f635f  x15: 0x006572756c696166
>    x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
>    x20: 0x000000016f69cf30  x21: 0x0000000000000097  x22: 0x000000016f69d330  x23: 0x0000000000000001
>    x24: 0x0000000000000006  x25: 0x000000010101c000  x26: 0x0000000000000001  x27: 0x000000010101c000
>    x28: 0x0000000000000000   fp: 0x000000016f69cf00   lr: 0x0000000101003ee8
>     sp: 0x000000016f69cec0   pc: 0x0000000100ffcf68 cpsr: 0x00000000
>    esr: 0x00000000  Address size fault
> 
> Binary images description not available
> 
> Error Formulating Crash Report:
> Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
> 
> EOF
>

**Comment by gaaclarke** [comment]
@cristian1980 It sounds like jenn suspects this may be an ios-deploy bug.  If that is the case you can always launch the app from `ios/Runner.xcodeproj` / `ios/Runner.xcworkspace` as a workaround, also this problem wouldn't affect your shipped apps.

I know there was talk recently of updating ios-deploy as part of fixing iOS 14 issues, so you might want to check the latest on the master channel to see if it is addressed.

**Comment by josh-burton** [comment]
Running into this one again today as well. The app runs fine via xcode but not from IntelliJ. No amount of cleaning the project etc makes any difference.

Have tried on beta, dev and master with the same result.

At the moment I'm unable to develop on this project as I can't launch from IntelliJ so no hot reloading etc. Can't attach to an app run from xcode since the IntelliJ Flutter plugin can't attach to flavors.

**Comment by gaaclarke** [comment]
> At the moment I'm unable to develop on this project as I can't launch from IntelliJ so no hot reloading etc. Can't attach to an app run from xcode since the IntelliJ Flutter plugin can't attach to flavors.

Jenn will know more of this when she gets back in the office but you can use the command line tools instead of the intellij plugin:
1) Launch the app from Xcode
1) `flutter attach` from the command line
1) edit the text in intelli j
1) from the command line press "r" to hot reload

**Comment by josh-burton** [comment]
Thanks, yeah that was going to be my approach today. I've narrowed down the issue to a [new dependency](https://github.com/markathomas/flutter_twilio_voice.git) I added recently. Removing that dependency fixes the problem.

**Comment by SteveAlexander** [comment]
I'm seeing this also, same behaviour on a physical iPad, same log error. I can reproduce it by making a new app from `flutter create`, and adding either `sensors` or `path_provider` as a dependency. So, I'm guessing it might be related to dependencies that use pods.

**Comment by liyuqian** [comment]
@jmagman @gaaclarke , I wonder if we shall increase the priority of this issue because I believe
- this happens on more apps than just Gallery (I suspect that it happens on almost all Flutter apps)
- this happens so frequently (not just 1st run) that I can hardly `flutter run` or `flutter drive` any iOS apps locally on iPhone 6s
- this happens frequently on our device lab and caused many tests to be flaky

Here are more details from my experience.

It happens very frequently when I test Gallery app or [complex_layout][] app locally with iPhone 6s (but not iPhone 4s). I can keep doing `flutter run` or `flutter drive` and it just keeps crashing.

From the command line, it just gets stuck with the following message while the app immediately disappears after launch
```
Installing and launching...
(This is taking an unexpectedly long time.)       ⣯
```

With `--verbose`, we'll see something like
```
[   +1 ms] executing: /Users/liyuqian/flutter/flutter/bin/cache/artifacts/usbmuxd/iproxy 57484:63131 --udid
2b398993d86f42b05511b330a89ae65289832852
[+1017 ms] Forwarded port ForwardedPort HOST:57484 to DEVICE:63131
[  +66 ms] HttpException: Connection closed before full header was received, uri = http://localhost:57484/ws
[+2013 ms] HttpException: , uri = http://localhost:57484/ws
[+2008 ms] HttpException: , uri = http://localhost:57484/ws
[+2011 ms] HttpException: , uri = http://localhost:57484/ws
[+2010 ms] HttpException: , uri = http://localhost:57484/ws
[+2004 ms] Failed to connect directly, falling back to mDNS
```

The `Failed to connect directly, falling back to mDNS` message is observed very frequently in flaky iOS device lab tests (as mentioned in [this comment][1]).

Finally, here's a crash log for a [complex_layout][] app `flutter run --profile` from Xcode

```
Incident Identifier: 7CE407AB-BEBD-4BB0-AADD-C51EF2A333EC
CrashReporter Key:   e1b06bdbb3a791e46454b77f27ef601c7ac64f57
Hardware Model:      iPhone8,1
Process:             Runner [1089]
Path:                /private/var/containers/Bundle/Application/E7E29C6F-0E1B-44AE-B207-67DDB11D0624/Runner.app/Runner
Identifier:          com.yourcompany.complexLayout
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.yourcompany.complexLayout [676]


Date/Time:           2020-09-17 19:38:06.1261 -0700
Launch Time:         2020-09-17 19:38:05.9172 -0700
OS Version:          iPhone OS 13.7 (17H35)
Release Type:        User
Baseband Version:    7.70.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/Flutter.framework/Flutter' not found for '/private/var/containers/Bundle/Application/E7E29C6F-0E1B-44AE-B207-67DDB11D0624/Runner.app/Runner'. vm_copy() failure
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fb41350   x3: 0x0000000000000097
    x4: 0x000000016fb40f50   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x6d76202e2772656e  x11: 0x20292879706f635f
   x12: 0x6e75522f7070612e  x13: 0x6d76202e2772656e  x14: 0x20292879706f635f  x15: 0x006572756c696166
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fb40f50  x21: 0x0000000000000097  x22: 0x000000016fb41350  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001005dc000  x26: 0x0000000000000001  x27: 0x00000001005dc000
   x28: 0x0000000000000000   fp: 0x000000016fb40f20   lr: 0x00000001005c3ee8
    sp: 0x000000016fb40ee0   pc: 0x00000001005bcf68 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF
```

CC @jonahwilliams @dnfield @xster @godofredoc

[1]: https://github.com/flutter/flutter/pull/64885#issuecomment-692262758
[complex_layout]: https://github.com/flutter/flutter/tree/master/dev/benchmarks/complex_layout

**Comment by zanderso** [comment]
@jmagman @gaaclarke How much does this affect the 1.22 beta?

**Comment by gaaclarke** [comment]
I checked the PRs that appear to have updated ios-deploy which is under suspicion of being the cause of the problem:
```
aaclarke-macbookpro2:flutter aaclarke$ git log bin/internal/ios-deploy.version
commit 020215bb4c9e8d4fbbc5522f9eeb469fa4727279
Author: Christopher Fujino <christopherfujino@gmail.com>
Date:   Wed Sep 2 18:35:05 2020 -0700

    Update ios-deploy (#65139)

commit 93ca301adca86b49b6acd0102449b7cb509a615e
Author: Christopher Fujino <christopherfujino@gmail.com>
Date:   Wed Jul 22 18:22:59 2020 -0700

    update ios-deploy (#61983)

commit 066cad21a6de8cfdb21e2d780349ac035b420784
Author: Christopher Fujino <christopherfujino@gmail.com>
Date:   Fri Sep 13 11:05:00 2019 -0700

    roll ios-deploy version to 2fbbee77ea2b3212959b9dddda816f59094cd7cd (#40398)

commit 102ab1e6d989de57019e0b1ee003ccb311ca3095
Author: Christopher Fujino <christopherfujino@gmail.com>
Date:   Mon Jul 15 09:22:29 2019 -0700

    Reland bundle ios deps (#36093)
    
    This updates the flutter tool cache to download binary files for ideviceinstaller, ios-deploy, libimobiledevice, and dynamically linked dependencies from Flutter's GCP bucket.
```

Those don't seem to match up with the reporting date of May for this bug.

**Comment by gaaclarke** [comment]
What @SteveAlexander sounds like like the most likely problem.  Cocoapods would be the one responsible for setting up the install_names and copying over the dynamic libraries.

**Comment by jmagman** [comment]
@zanderso I think this has been a source of flakes for a long time (reproduced on 1.12.13) and I see similar reports from 2014 https://forum.ionicframework.com/t/problem-running-ios/9179/4.  I suspect the increased flakiness is due to app size increasing.

**Comment by zanderso** [comment]
@jmagman if this issue isn't the source of the recent increase in flakiness on the dashboard, then I'm fine with dropping the priority on this back down, but the current flakiness is still P0. Is there a different issue we should be tracking that in? Maybe back to the one @jonahwilliams filed this morning?

**Comment by jmagman** [comment]
It's either fix this or reduce the size of the benchmarks (I'm guessing pushed over by `e2e`).  We can fix this I think.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/66092 should fix this, holding to see what post submit tests do.

**Comment by jmagman** [comment]
Looks good post-submit, closing.
@liyuqian @josh-burton @SteveAlexander would you mind testing this on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels)?

**Comment by SteveAlexander** [comment]
@jmagman Sure — result: crash

This is `flutter run` of a default app with added `sensors` package dependency, on latest master. I had erased the app on the iPad, so this was the first run on the iPad.

```text
$ flutter run
Running "flutter pub get" in testproject...                         0.3s
Launching lib/main.dart on Stephen’s iPad in debug mode...
Signing iOS app for device deployment using developer identity: "Apple Development: Stephen Alexander (xxx)"
Running pod install...                                              1.2s
Running Xcode build...
 └─Compiling, linking and signing...                        41.7s
Xcode build done.                                           55.8s
Installing and launching...
Failed to attach to the observatory.
Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.
For more information, see https://flutter.dev/docs/development/ios-14#debugging-flutter
Installing and launching...                                       130.9s (!)
Error launching application on Stephen’s iPad.
```

There was no pop-up. The app launched with a white screen that displayed  "In iOS 14+, Flutter application in debug mode can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode. Alternatively, build in profile or release modes to enable re-launching from the home screen."

Additionally, there is no request under "Settings > Privacy > Local Network" on the iPad.

On running a second time, the same thing happens.

From my point of view, this is worse than the situation on master yesterday, as yesterday I could run the app on second launch.

----
```text
$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.264, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.264 at /Users/steve/code/flutter
    • Framework revision 3e6863ab2b (6 hours ago), 2020-09-18 21:05:27 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1


[✓] Connected device (1 available)
    • Stephen’s iPad (mobile) • b0975f3aa3ebe98c71462a866b0356a629fc6aa3 • ios • iOS 14.0
    ! Error: Stephen’s iPad is busy: Copying cache files from device. Xcode will continue when Stephen’s iPad is finished. (code -10)

• No issues found!
```

**Comment by jmagman** [comment]
@SteveAlexander That looks like a different issue, but very bad and I'd like to track it down.  Between https://github.com/flutter/flutter/issues/65948 and your comment, your iPad upgraded to iOS 14.
Can you file a new issue with and attach the `flutter run -v` output (it's large, you can attach instead of pasting it)?  Please @ me there.

**Comment by liyuqian** [comment]
@jmagman : I tested 3 times locally and all of them pass. Thank you for the fix!
