### ISSUE TITLE
Document Skia.setResourceCacheMaxBytes better

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#57227]
It is unclear what `Skia.setResourceCacheMaxBytes` does, what it is useful for and when (if ever) it should be set. 

This is part of an effort to document best practices from perf: memory standpoint.

**Comment by chinmaygarde** [comment]
This is a completely hacky workaround for tweaking an internal engine subsystem and the side-effects are not intuitive and may be detrimental if used incorrectly. We should not be suggesting this as a solution to any issue.

**Comment by mehmetf** [comment]
There's no upstream issue for this. Only P2 and above get mandatory mirror issues. We also don't have any official documentation that suggests this. It has come up a couple of times in conversations but that's it. This issue can be closed once we have canonical documentation that helps users diagnose graphics memory problems (and that documentation should explain what this knob is for since it is [public API](https://api.flutter.dev/flutter/services/SystemChannels/skia-constant.html)).

**Comment by chinmaygarde** [comment]
> We also don't have any official documentation that suggests this.

By "this" you mean never suggesting this as a solution to any issue? Then, yeah, that makes sense as it should reduce confusion. It's unfortunate that this became a part of the public API. This used to be a setting the embedder had to set manually but the engine sets and updates this automatically now.

**Comment by jonahwilliams** [comment]
We're removing this as part of the public API and don't intend to document it.
