### ISSUE TITLE
Build Never Completing

### ISSUE THREAD

**Issue by scott2000** [flutter/flutter#5723]
## Steps to Reproduce

I tried running `flutter build ios` and it ran for over 3 hours before I had to cancel it. I just installed flutter on Mac OS 10.11.5 and tried building the template.
## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/scott/flutter
    • Framework revision 9a0a0d9903 (3 weeks ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /Users/scott/Library/Android/sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_05-b13)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```

**Comment by eseidelGoogle** [comment]
That sounds like a hang of some form.  I would recommend trying `flutter build ios -v` and pasting the output into a gist.github.com linked from this bug.

Most of the work for `flutter build ios` is actually done by XCode, so perhaps some call we made into xcode has hung?

**Comment by eseidelGoogle** [comment]
`flutter build ios` should take 30s to a minute depending on your hardware.

**Comment by scott2000** [comment]
This is the result of `flutter build ios -v`:
```
 213 ms • /usr/bin/defaults read /Users/scott/Dropbox/DartProjects/myapp/ios/Runner/Info CFBundleIdentifier
   0 ms • Exit code 0 from: /usr/bin/defaults read /Users/scott/Dropbox/DartProjects/myapp/ios/Runner/Info CFBundleIdentifier
   1 ms • com.yourcompany.myapp
   0 ms • Using engine artifacts dir: /Users/scott/flutter/bin/cache/artifacts/engine/ios-release
   1 ms • Building com.yourcompany.myapp for device (ios-release)...
   3 ms • Using engine artifacts dir: /Users/scott/flutter/bin/cache/artifacts/engine/ios-release
 141 ms • xcodebuild -version
   0 ms • Exit code 0 from: xcodebuild -version
   1 ms • Xcode 7.3.1
          Build version 7D1014
   3 ms • Trying to resolve native pub services.
  26 ms • Looking for YAML at 'flutter.yaml'
   0 ms • No services specified in the manifest
   0 ms • Found 0 service definition(s).
   0 ms • Copying service frameworks to '/Users/scott/Dropbox/DartProjects/myapp/ios/Frameworks'.
   6 ms • Creating service definitions manifest at 'ios/ServiceDefinitions.json'
```

**Comment by eseidelGoogle** [comment]
Yeah, definitely looks like it's hung on the xcodebuild step.  For example, here is output from my machine (xcodebuild takes 43s for me):
https://gist.github.com/eseidelGoogle/6aadd53fd4da7a2ddd172eb162538b86

You can try opening ios/Runner.xcodeproj and building directly from in xcode and see if that helps?

FYI @danrubel @chinmaygarde

**Comment by eseidelGoogle** [comment]
I don't think there is anything to do here w/o more information.  Please feel encouraged to file a new bug if you're still seeing things like this!
