### ISSUE TITLE
Upload GLFW profile/release builds for Linux

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#57248]
Required to unblock landing of profile/release mode build/run in the tool

**Comment by jonahwilliams** [comment]
@stuartmorgan I created this as a tracker so I can mark the tools PR as blocked by something

**Comment by stuartmorgan** [comment]
Sounds good. Coincidentally, I was just kicking off the test run of the new recipe :)

**Comment by stuartmorgan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/2901

**Comment by stuartmorgan** [comment]
This was fixed by the PR above; I forgot to close the issue.
