### ISSUE TITLE
Command new seems to be more idiomatic than create.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5724]
This is more of a question which might stem from a bit of bias, but to me it seems like `new` would be more idiomatic than `create` in our command line tool.

Some other tools use `init` like [git](https://git-scm.com/docs/git-init), [npm](https://docs.npmjs.com/cli/init), and [Bower](http://weaintplastic.github.io/web-development-field-guide/Development/Frontend_Development/Setting_up_your_project/Setup_Dependency_Managers/Bower/Initialize_Bower_on_a_new_Project.html), but this doesn't really fit our description.

`new` is used in [Rails](http://guides.rubyonrails.org/command_line.html), [Play](https://www.playframework.com/documentation/2.5.x/NewApplication), [Hanami](http://hanamirb.org/guides/getting-started/), [Cargo](http://doc.crates.io/guide.html), only to name a few. The only tool I know that uses `create` is [homebrew](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md).

**Comment by sethladd** [comment]
Thanks for the suggestion. The flutter tool help output is pretty good, seems like it's clear to users what to do. We don't yet have evidence that this is tripping up users in the wild, but something we should keep our eyes open for. We might even have most users run this command via the IDE's GUI in which case the name of the command might be hidden.

I'm inclined to leave it as "create" for now.

**Comment by dragostis** [comment]
The only reason why I thought about opening this question is because changing it after 1.0 would be a pain.

**Comment by Hixie** [comment]
We could always alias it if we need to change it.

**Comment by sethladd** [comment]
Good point.

I'm inclined to close this issue. We have some time before 1.0 so we can revisit if we get feedback from our early testers.
