### ISSUE TITLE
Cannot infer generic class when calling generic method from generic method

### ISSUE THREAD

**Issue by marcosmko** [flutter/flutter#57242]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Copy paste the following code inside `main.dart`
```dart
abstract class Bar {
}

class Foo extends Bar {
}

class SomeClass {
  T doSomething<T>() {
    return AnotherClass.doSomething();
  }
}

class AnotherClass {
  static T doSomething<T extends Bar>() {
    print(T);
    return null;
  }
}
```

3. Call 
```dart
Foo bar = SomeClass().doSomething();
```

**Expected results:** 
```I/flutter (16374): Foo```

**Actual results:** 
```I/flutter (16374): Null```

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

• No issues found!
```

</details>

It seems it works normally when I switch the 
```dart
static T doSomething<T extends Bar>() {
  print(T);
  return null;
}
```

for
```dart
static T doSomething<T>() {
  print(T);
  return null;
}
```

Is this the intended behaviour?

**Comment by iapicca** [comment]
Hi @marcosmko 
this issue seems to be related to dart language itself rather than Flutter framework
you might want to open an issue in the dedicated [github](https://github.com/dart-lang/sdk/issues)
Thank you

**Comment by marcosmko** [comment]
Okay, thanks!

This issue will be tracked at dart-lang/sdk#41909
