### ISSUE TITLE
Xcode build error: Module 'image_picker' not found

### ISSUE THREAD

**Issue by en-v** [flutter/flutter#57246]
When I build or archive my app in XCode (after: flutter build iOS --release):
```bash
#import "GeneratedPluginRegistrant.h"
#if __has_include(<image_picker/FLTImagePickerPlugin.h>)
#import <image_picker/FLTImagePickerPlugin.h>
#else 
**@import image_picker; <<<<<<<< ERROR: Module 'image_picker' not found**
#endif
```
dependencies:
`  image_picker: ^0.6.5+1`

flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/alexander/dev/libs/flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexander/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/alexander/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/alexander/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (1 available)            
    • envoi • 05ababad76243cda41b6e2b14f8d2ab5150eca6e • ios • iOS 13.4.1

• No issues found!
```

DOESN'T HELP ME:
```console
pods repo update
rm -rf ios/Pods ios/Podfile.lock
flutter clean
flutter run
```

But when I am running my app in debug mode - all is good.
Help me please!

**Comment by MurathanGoktas** [comment]
Did you try upgrading image_picker to v 0.6.6+1 ?

**Comment by en-v** [comment]
Yes. I used 0.6.6 first.

**Comment by iapicca** [comment]
Hi @en-v 
can you please upgrade the plugin to the latest version
and provide your `flutter run --release --verbose` 
Thank you

**Comment by en-v** [comment]
Sure! Plugin upgraded. 

`flutter run --release --verbose &>` [_RES.TXT](https://github.com/flutter/flutter/files/4634180/_RES.TXT)
This is huge log %) more than 3500 lines.
App launched normally.

After:
```
flutter clean
fluter build ios
```

Result: 
```
Xcode build done.                                           81.4s
Built /Users/alexander/dev/ecoapp/build/ios/iphoneos/Runner.app.
```

Then I open **Xcode** & launch **Product > Archive**   
`@import image_picker; [ Module 'image_picker' not found ]`

**Comment by en-v** [comment]
Hi @iapicca
What do you think about it?

**Comment by TahaTesser** [comment]
Not able to reproduce locally but since it was  mentioned archive with Product > Archive, labeled the issue

**Comment by en-v** [comment]
Hi!
I found how to solve this issue (fkn Xcode!!!!)

https://github.com/flutter/flutter/issues/43986#issuecomment-576942084

**Comment by Bhardwajraju** [comment]
apples-MacBook-Pro:ios apple$ pod install
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

**Comment by Bhardwajraju** [comment]
how to solve this . When i open the code xcode  Module image_picker' not found.

**Comment by Bhardwajraju** [comment]
export LANG=en_US.UTF-8
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
".profile" 1L, 24C
i have added this line in .profile

**Comment by Bhardwajraju** [comment]
/Users/apple/Downloads/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.20.3 at /Users/apple/Downloads/flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • BE83A7FA-6A4D-4AD7-9855-0A436B5789D9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
Process finished with exit code 0

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
