### ISSUE TITLE
Show full screen image 

### ISSUE THREAD

**Issue by grammystrano** [flutter/flutter#57254]
How can i show a fullscreen image that i get it from firebase storage when i clicked on it ???

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
