### ISSUE TITLE
Flutter problem ??

### ISSUE THREAD

**Issue by grammystrano** [flutter/flutter#57253]
When i run my app the android studio blocks and i cant do anything anymore even the cursor i cant deplace it. I should shut down the computer with the button and i restart it and the same problem still even i tried in visual studio same thing

**Comment by Vishvak365** [comment]
Perhaps this is an issue with your hardware. Check your Operating System's System monitor (Task Manager if on Windows) and check your hardware usage (mainly memory) and see if you are running out of memory.

**Comment by grammystrano** [comment]
> Perhaps this is an issue with your hardware. Check your Operating System's System monitor (Task Manager if on Windows) and check your hardware usage (mainly memory) and see if you are running out of memory.

Can u explain more

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
