### ISSUE TITLE
Use @factory for State.createState et al

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#57259]
We should put the @factory annotation on things like State.createState and RenderObjectWidget.createRenderObject and Widget.createElement et al.

cc @a14n @goderbauer

**Comment by a14n** [comment]
In #57299 I added `@factory` on every `create*` methods.

**Comment by a14n** [comment]
Closed via d42dcf2edd906b8bf58e39670d4d18bfb0da49e3
