### ISSUE TITLE
Status bar has disappeared after upgrading to version 1.17.1

### ISSUE THREAD

**Issue by pulstar** [flutter/flutter#57262]
## Steps to Reproduce

After upgrading Flutter to version 1.17.1, the status bar has disappeared and I am unable to enable it with the command below.

`
SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values)
`

**Comment by VladyslavBondarenko** [comment]
Hi @pulstar 
could you provide your `flutter doctor -v`, minimal complete reproducible code sample and a screenshots of the result with current and previous flutter version?

**Comment by pulstar** [comment]
I downgraded Flutter to the previous version, but the problem remain... I don't have any code to show here, because I didn't change anything. Maybe is some third party plugin I am using. I will try discover what is wrong then I post the results here.

![image](https://user-images.githubusercontent.com/1308392/82090952-e5bbb400-96cc-11ea-9620-6a31e00ab93f.png)

[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [versÃ£o 10.0.17763.1217], locale pt-BR)
    • Flutter version 1.17.0 at C:\Program Files\flutter
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] Connected device (1 available)
    • Vivo XI • PRUCHYWGG6HYSK4H • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by pulstar** [comment]
I found the culprit... Just after I have installed the Flutter Native Splash plug-in (https://pub.dev/packages/flutter_native_splash), Flutter also have upgraded then I think it was the cause. But this plugin made a change in styles.xml file, changing the fullscreen option to true:

```
flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color

```
