### ISSUE TITLE
Invalid header field name, with 128

### ISSUE THREAD

**Issue by nanophp** [flutter/flutter#57263]
Hi guys, I got a problem with the header. 
> Invalid header field name, with 128

I'm using an iOS simulator. And if I not mistaken iOS simulator works well with localhost, in general, I have an information emulator that cannot access the localhost. That's why I have a decision it is maybe a bug. 

When I use another header such as
```dart
headers: {
   HttpHeaders.contentTypeHeader: 'application/json'
},
```
After that, I got different errors like that.

> flutter: Bad state: Cannot set the body fields of a Request with content-type "application/json".

One important thing FYI, _when I use the JSON MOCK SERVER, it works very well_, after switching DOCKER environment I got the error. I would like to add other details. I also test my real back-end code which is works on the docker environment, **I test on the browser with fetch API, and also angular application works well**. _I think that there is not related to my back-end or such kind of CORS issues._

 ```dart
   Future<void> login(String email, String password) async {
    final String url = '$baseUrl/login';

    try {
      final http.Response response = await http.post(
        url,
        headers: <String, String>{
          HttpHeaders.contentTypeHeader: 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, String>{
          'email': email,
          'password': password,
          'device_name': 'apple',
        }),
      );

      final Login user = Login.fromJson(json.decode(response.body));

      _token = user.data.token;
      _email = email;

      final SharedPreferences sharedPreferences =
          await SharedPreferences.getInstance();
      final userData = json.encode({
        'token': _token,
        'email': _email,
      });
      sharedPreferences.setString('userData', userData);

      notifyListeners();
    } on HttpException {
      print('login service error.');
    } on SocketException {
      print('No internet connection or server shutdown.');
    } on FormatException {
      print('Bad response format.');
    } catch (exception) {
      throw exception;
    }
  }
```

**Comment by iapicca** [comment]
Hi @nanophp 
the issue you are describing seems to be caused by the ios simulator not reaching your localhost

Does your flutter app reach external websites ?

Does the issue occur on android emulator ?

if so could you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by nanophp** [comment]
> Hi @nanophp
> the issue you are describing seems to be caused by the ios simulator not reaching your localhost
> 
> Does your flutter app reach external websites ?
> 
> Does the issue occur on android emulator ?
> 
> if so could you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`,
> your `pubspec.yaml`
> and a reproducible minimal code sample.
> Thank you

Hi, there is no problem communication simulator to localhost, could you check please 

https://github.com/dart-lang/http/issues/416

**Comment by nanophp** [comment]
the issue still active on this link https://github.com/dart-lang/http/issues/416, please check the link.
