### ISSUE TITLE
Flutter web TextField onEditingComplete called textfield loses focus

### ISSUE THREAD

**Issue by coldstar96** [flutter/flutter#57278]
[Only on web]

According to the document, onSubmitted should be "[called when the user submits editable content (e.g., user presses the "done" button on the keyboard)](https://api.flutter.dev/flutter/material/TextField/onEditingComplete.html)" but it gets called whenever textfield loses focus. I need callback of user hitting "return" but I can't distinguish between losing focus vs hitting "return". Losing focus happens when clicking on outside of TextField OR navigating to different view (pretty common actions) .

One thing to mention, method names are bit confusing because _onEditingComplete_ is callback for "[user submits](https://api.flutter.dev/flutter/material/TextField/onSubmitted.html)" and _onSubmitted_ is when the user is done editing, which I interpret that as "losing focus"(doc also points to [EditableText.onSubmitted](https://api.flutter.dev/flutter/widgets/EditableText/onSubmitted.html) which shows example of switching focus). I think they should be flipped?

Could you please fix the issue as soon as possible with possible workaround in the mean time?

Thanks!

**Comment by dev-aentgs** [comment]
This codelab might help you [Write your first Flutter app on the web](https://flutter.dev/docs/get-started/codelab-web)

**Comment by iapicca** [comment]
Hi @coldstar96 
I see there's an open [issue](https://github.com/flutter/flutter/issues/49785) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
