### ISSUE TITLE
Dumping logs at the end of running tests is causing timeouts on Fuchsia

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#57273]
This issues is to create a better log collecting mechanism for it.

cc: @godofredoc

**Comment by iskakaushik** [comment]
This is causing ssh timeouts and failures like: https://chromium-swarm.appspot.com/task?id=4c2ecc5b9ffcfd10

**Comment by digiter** [comment]
Triage: may need to stream the logs to a file.

**Comment by godofredoc** [comment]
This is a problem with subprocess runs on dart with large outputs. To fix the problem we need to stream the content preferably to a file.

**Comment by kf6gpe** [comment]
@godofredoc @digiter Is this still on track for the June milestone?

**Comment by godofredoc** [comment]
Yes, I'll try to get it fixed before the end of the month.

**Comment by Hixie** [comment]
One more day!
