### ISSUE TITLE
FlutterView api  is not work when update to  Flutter 1.17.  the flutter event not work, eg: flutter button not work 

### ISSUE THREAD

**Issue by weichongchong** [flutter/flutter#57277]

**Comment by weichongchong** [comment]
Supplementary notes ： I use flutter as flutter module to my project, add a FlutterView into my activity, but the FlutterView is not work and  the api  flutterEngine.navigationChannel.pushRoute("home") is also not work well in Flutter 1.17

**Comment by VladyslavBondarenko** [comment]
Hi @weichongchong 
could you provide your `flutter doctor -v` and minimal reproducible project with description of expected and actual result?

**Comment by weichongchong** [comment]
Thank you for your response
flutter doctor -v

[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/wei/develop/flutter
    • Framework revision 5f21edf8b6 (2 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wei/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • PCNM00 • 16557c33 • android-arm64 • Android 9 (API 28)


I am sorry for can't provide the minproject ,because when I rebuild as a minproject( I create a demo) it is work well , but the sample  codes can't work at my company project .
 the follow are the main codes .  
`protected fun initFlutterFragment() {
        homeFlutterView = FlutterView(context)
        var lp = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT)
        fl_flutter_view.removeAllViews()
        fl_flutter_view.addView(homeFlutterView, lp)
        homeFlutterView?.attachToFlutterEngine(FlutterClient.instance.flutterHomeEngine)
    }
`
most important of all : the codes work very well on Flutter SDK v1.12.13+hotfix.8, but can't work on Flutte SDK 1.7, the flutter view not rendered   the Fragment  only show android native view.
so i want know what different between SDK1.2 and SDK1.7 on  view rendered.

when I use the api : FlutterFragment.withCachedEngine("flutterHomeEngine").build();  it can show flutter view ,but there another issue appear : I cannot use api: supportFragmentManager.beginTransaction().hide(flutterFragment) show(androidFragment), the flutterFragment cannot be hide. .But it woke use the api supportFragmentManager.beginTransaction().replace()........   
**BUT  everything work well on SDK v1.12.13+hotfix.8.

**Comment by weichongchong** [comment]
Today I. update flutter sdk to stable 1.17.3 these problems appear on minimal reproducible project.
there are two problem.
1.flutter view rendered  very slow. sometime the flutter view not be rendered.
2.the flutter button event not response . 

[demo.zip](https://github.com/flutter/flutter/files/4802757/demo.zip)
Please check minimal reproducible project. thanks

**Comment by weichongchong** [comment]
How is it going？

**Comment by xster** [comment]
I don't have a short answer unfortunately because the FlutterView integration API is only partially supported. It's fully functional but you need to do a lot of FYI to get FlutterView connected as you noticed, especially if you want to use your own Fragment as opposed to the FlutterFragment. Generally, see all the fragment callbacks that are passed to the FlutterView in https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java. You need to reproduce them all when you use your own fragment.

**Comment by xster** [comment]
There's a sample for this now https://github.com/flutter/samples/tree/master/add_to_app/android_view. You can follow #21847 for more progress but we're unlikely to make too much change on this now.
