### ISSUE TITLE
help me  ！！！    hasn't drawn some images and no text

### ISSUE THREAD

**Issue by jackTang11** [flutter/flutter#57282]
I do not get this all the time but if i wake the device from sleep after a period of time and resume the app then sometimes it is stuck in this state (like it hasn't drawn some images and no text)
ios release

 Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/jack/Documents/work/flutter/flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/jack/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

<img width="332" alt="WechatIMG788" src="https://user-images.githubusercontent.com/7345590/82013576-36231980-96ad-11ea-9f90-a0a96744dc71.png">
<img width="399" alt="WechatIMG791" src="https://user-images.githubusercontent.com/7345590/82013866-f6106680-96ad-11ea-83dc-3c41248ec99c.png">

**Comment by dev-aentgs** [comment]
Try checking flutter inspector in android studio.

**Comment by jackTang11** [comment]
> Try checking flutter inspector in android studio.

release ios

**Comment by iapicca** [comment]
Hi @jackTang11 
please follow up on the [issue](https://github.com/flutter/flutter/issues/57073) you opened before
closing as duplicate
Thank you
