### ISSUE TITLE
[FEATURE] Make google_maps_flutter package available for web

### ISSUE THREAD

**Issue by ramioooz** [flutter/flutter#57297]
## Use case
Hello flutter team,
I think I am speaking for many developers like my self when I say we wish for you to make your package [google_maps_flutter](https://pub.dev/packages/google_maps_flutter#-readme-tab-) available for the web. I am writing you this today, to make it as an **official request** for a the feature.

## Proposal
I know that you have plans to do it. but this has been delayed far more than expected, while it is a very essential feature. 
I am not an expert, but I think you have all the infrastructure, tools, and APIs available for the task. you just need to devote some time and effort into it.

Please keep it up... you are giving the world a wonderful framework, we have been longing for, for quite some time.

My regards,
Rami

**Comment by iapicca** [comment]
Hi @ramioooz 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45292) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by ramioooz** [comment]
I found this plugin, I think it can get the job done for now for those who want google maps on both mobile and the web :
[flutter_google_maps ](https://pub.dev/packages/flutter_google_maps)

I will give it a try, and I will keep an eye on the issue.
Thank you
