### ISSUE TITLE
Javascript instead of Dart

### ISSUE THREAD

**Issue by 34r7h** [flutter/flutter#57298]
## Proposal

I saw a rumour that flutter plans to support being written in other languages, such as Javascript. Obviously the javascript ecosystem has more developers but also more security risks, ntm some weird behaviors. Please inform us of any plans to write flutter apps in Javascript. 

My feature request is ambitious af, to build a JS transpiler to dart, making dart an intermediate representation language (ala Bosque from MS research) for flutter along with tooling to understand interpretive languages like JS or Python. While this request is certainly a lot of work, it will future-proof Dart as the compiler of choice for OS's like fuscia, as well as platform-specific applications.

At this point in time, it seems the wisest stack for cross platform compatibility includes vanilla JS, ReactNative, and Electron because the codebase differences are minimal and developer availability is high.

**Comment by iapicca** [comment]
Hi @34r7h 
please read this [documentation](https://flutter.dev/docs/resources/faq#why-did-flutter-choose-to-use-dart)
Thank you

**Comment by 34r7h** [comment]
Yes, I read this and understand. I'm not suggesting the removal of dart.
I'm suggesting to use dart as an intermediate representation language.
Please reopen the feature request and let's discuss.

**Comment by 34r7h** [comment]
Btw, I adjusted the title to better reflect the nature of this feature request. Thank you.
