### ISSUE TITLE
when I use the TextField in showDialog or overlay,some error happend;

### ISSUE THREAD

**Issue by VernierCaliper** [flutter/flutter#57293]
throw MissingPluginException('No implementation found for method $method on channel $name');

**Comment by liodali** [comment]
can you give us example of code to reproduce the error

**Comment by iapicca** [comment]
Hi @VernierCaliper 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
