### ISSUE TITLE
Flutter run -d chrome Issue

### ISSUE THREAD

**Issue by vishant-jaiswal** [flutter/flutter#57303]
whenever I am trying to run the project in web it is getting stuck in between 
![image](https://user-images.githubusercontent.com/26866152/82036036-04667e80-96be-11ea-83b4-5c51fe45ed72.png)

and following error appears in browser console.

![image](https://user-images.githubusercontent.com/26866152/82035703-81ddbf00-96bd-11ea-82ba-8ac636f95f0a.png)

sometime this error appears

![image](https://user-images.githubusercontent.com/26866152/82036111-1811e500-96be-11ea-924c-9732a4f61055.png)

![image](https://user-images.githubusercontent.com/26866152/82036510-9b333b00-96be-11ea-8374-64d6169e9a25.png)

but without changing anything if I do browser refresh it starts running fine then. with following terminal msg

![image](https://user-images.githubusercontent.com/26866152/82036281-5909f980-96be-11ea-9035-d2ccda202ba5.png)

Flutter Doctor summery
![image](https://user-images.githubusercontent.com/26866152/82035869-c2d5d380-96bd-11ea-888c-682644d65014.png)

Pubspec yaml dependencies i have:
![image](https://user-images.githubusercontent.com/26866152/82036627-bf8f1780-96be-11ea-8269-457fab376ad6.png)

and portion of my index.html file 

![image](https://user-images.githubusercontent.com/26866152/82036803-f6652d80-96be-11ea-82a6-96dc29dbab5a.png)
...
![image](https://user-images.githubusercontent.com/26866152/82036918-185eb000-96bf-11ea-8464-b4b8eb9fcee4.png)

**Comment by iapicca** [comment]
Hi @vishant-jaiswal 
for what I can see from the screenshots
the errors seems to be related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

if that's not the case
please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample 
(without 3rd party plugins)

Please refrain from posting pictures if not necessary.
Thank you

**Comment by vishant-jaiswal** [comment]
@iapicca thanks for the reply yes this is the issue with firebase plugin will raise the issue there. you can close this thread here.
