### ISSUE TITLE
Ability to use Navigator.popUntil without animation

### ISSUE THREAD

**Issue by viplavrawal** [flutter/flutter#57304]
## Use case
We want the user to have animation when he goes forward or backward in the navigation stack by using the UI or the physical buttons in the device.
But when we use the method Navigator.popUntil programmatically, animation should not show, or a different animation should show.

## Proposal
The method Navigator.popUntil should have an optional boolean parameter showAnimation where false can be passed. By this, popUntil would take the user to the first screen in the stack without showing any animations.

Flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87,
locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)
```

Please let me know if any more details are required.

**Comment by chunhtai** [comment]
We are in the middle of providing the router widget which you can choose how to transition off the screen using page api https://api.flutter.dev/flutter/widgets/Navigator/pages.html

We do not plan to update the imperative api

**Comment by sketcharsh** [comment]
This wokrs for me.

int count = 0;
                           
Navigator.of(context).pushAndRemoveUntil(
                PageRouteBuilder(
                   pageBuilder:
                       (context, animation1, animation2) =>
                 MembershipListScreen(),
                transitionDuration: Duration(seconds: 0),
                 ),
      (_) => count++ >= 3, //3 is count of your pages you want to pop
  );
