### ISSUE TITLE
Back screen widgets are being rebuild

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#57306]
Hi,
I have implemented Pagination. So when I move to the bottom of screen, an api is called to fetch more data. While fetching data, I moved to next screen. As soon as I moved to next screen, duplicated api called again. Since I am increasing Page number after the successful response. I get 2 duplicated response. Though I can manage to fix the issue by putting it in map, but back widget should be build like that.

**Comment by viratshukla** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (5 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Studio\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Studio\Sdk
    • Java binary at: C:\Users\80065124\Downloads\android-studio- 4.1 canary 5\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 2.3)
    • Android Studio at C:\Users\80065124\Downloads\android-studio 2.3.3\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\80065124\Downloads\android-studio-3.4.2\android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Android Studio (version 4.1)
    • Android Studio at C:\Users\80065124\Downloads\android-studio- 4.1 canary 5\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM M307F • RZ8MA05SQ4M • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @viratshukla 
are could you please run `flutter upgrade --force`

if the issue persists
please provide your updated `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
