### ISSUE TITLE
[web] Make app version/build available

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#57316]
## App version

App version should be available to the running program.

## Proposal

Make app version/build numbers and package name available somewhere, the most practical solution would be somewhere under `window`, probably among the `$dartVariables` set up at the start of `main_module.bootstrap.js` or similar.

The version number might be neded to be displayed in an About dialog or sent along with a log to facilitate tech support.

**Comment by TahaTesser** [comment]
Hi @deakjahn 
This should be solved by https://github.com/flutter/flutter/issues/46609 
You can already use `package_info` on mobile, web support isn't available yet
Does this answer your proposal?
Thank you

**Comment by deakjahn** [comment]
If it worked, it would. I don't actually need an external package, I do it with my own platform code. The problem is that there is no value stored on the web that could be read. Right now I simply modify it manually when I don't forget but that's hardly optimal. :-)

**Comment by yjbanov** [comment]
In order to implement https://github.com/flutter/flutter/issues/46609 we'll need the compiler output the version file somewhere, e.g. a `VERSION` file that can be accessed from within the app (e.g. like an asset). So I will categorize this issue as a request for the tool to produce this file.

/cc @jonahwilliams (maybe we do this already?)

**Comment by jonahwilliams** [comment]
We don't do this today, but it would be straightforward to add. But in what format/location?

**Comment by deakjahn** [comment]
May I suggest a JSON? That's rather easy to read with tools already at disposal.

**Comment by ditman** [comment]
It'd be great if this was written into the index.html file somehow, inside a `script` tag with a known ID or similar. That way we don't need an additional request to retrieve the info, but we can still load it easily when needed.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/3dde3e034c29fe75e418775a33f20b5d7b7322d3
