### ISSUE TITLE
Flutter Web - Rotated Box / Transform Causes Children To Be Invisible

### ISSUE THREAD

**Issue by genjm** [flutter/flutter#57314]
Afternoon,

Using a RotatedBox ( 3 quarter turns ) or a Transform ( 270 degrees ) results in the child widgets not being drawn in Flutter Web ( Chrome, MacOS ).

Alert Dialog & Raised Button are the best examples I've found so far, but obviously I've not tried *every* possible widget. 

With the following Alert Dialog code, if I hover over where the Cancel button would be drawn, it actually displays the title & body text properly, but not the button text:

`showDialog(
    context: context,
    builder: (BuildContext context) {
      return RotatedBox(
        quarterTurns: 3,
        child: AlertDialog(
          title: Text( "Clear Cache" ),
          content: Text( "Are you sure you want to clear the asset cache?\n\nIf you proceed then all the images stored in\nmemory will be deleted & need to be\nre-downloaded from the server?" ),
          actions: [                                  
            FlatButton(
              child: Text( "No" ),
              onPressed: ( () {
                Navigator.of( context ).pop();
              } ),
            ),
            FlatButton(
              child: Text( "Yes" ),
              onPressed: ( () {
                Navigator.of( context ).pop();
              } ),
            ),
          ],
        ),
      );
    }
  );`

The Floating Action button does it as well, but if you then resize the web page, that usually redraws the child correctly.

Flutter Doctor output:

[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.15.17 at /Users/jfurlough/Development/flutter
    • Framework revision 2294d75bfa (2 months ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by TahaTesser** [comment]
Hi @genjm 
Please upgrade to latest `dev` channel, this seems to be fixed in `dev` channel

<img width="478" alt="Screenshot 2020-05-15 at 8 43 24 PM" src="https://user-images.githubusercontent.com/48603081/82066482-1ad7fe80-96ed-11ea-8d43-ef1bb8ba6557.png">

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (4 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (3 available)            
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details> 

<img width="502" alt="Screenshot 2020-05-15 at 8 45 37 PM" src="https://user-images.githubusercontent.com/48603081/82066651-4fe45100-96ed-11ea-99cb-b9b2f43075f3.png">


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-11.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 2738a1148b (2 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (2 available)            
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

``` 

</details> 

if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by genjm** [comment]
Brilliant, that's done the trick.

Thank you.
