### ISSUE TITLE
Multiple Flutter Unix executables

### ISSUE THREAD

**Issue by Gideon357** [flutter/flutter#57313]
I was just cleaning up my Mac (MacBook Pro, late 2013, running macOS Catalina v 10.15.4), and noticed ~~seven~~ twelve copies of a Unix Executable named flutter, each between 394 and 68 megabytes. Why are there many of these? Are they different versions, or for different projects? Are they safe to delete? If so, shouldn't they be auto-deleted? Thanks for any help!

<html>
<head></head>
<details>
<summary>flutter doctor -v</summary>
<samp>
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/GideonGrinberg/Development/flutter
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/GideonGrinberg/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
</samp>
</details>
</html>

**Comment by zanderso** [comment]
What were the paths to these files?

**Comment by Gideon357** [comment]
@zanderso a number of these files are in the flutter directory itself, and the rest are in apps. It was silly of me not to check! Sorry to wastes your time! One observation I had is that these files are all the same size, so perhaps they are the same file. If so, would it be possible to share one throughout projects instead of creating so many? Sorry to bother you, and thanks for the help!
