### ISSUE TITLE
TextFormField autofill support

### ISSUE THREAD

**Issue by mmeyer-civic** [flutter/flutter#57312]
It looks like autofill support was just added to the master channel [13015](https://github.com/flutter/flutter/issues/13015)  It doesn't look like the autofill properties have been added to the TextFormField.  Specifically, the [autofillHints](https://master-api.flutter.dev/flutter/material/TextField/autofillHints.html) property does not exist on the TextFormField type.

**Comment by pedromassango** [comment]
This issue show a example https://github.com/flutter/flutter/issues/57320

**Comment by mmeyer-civic** [comment]
> This issue show a example #57320

This only works for the `TextField` not `TextFormField`

**Comment by HansMuller** [comment]
I'm closing this since #57332 has landed. Thanks for the report!
