### ISSUE TITLE
Autofill not showing hints

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#57320]
Not sure if I'm missing any additional required steps, but the following code doesn't show any autofill hints in my physical Android device.

## Steps to Reproduce

```dart
const AutofillGroup(
  child: TextField(
    autofillHints: <String>[
      AutofillHints.username,
      AutofillHints.name,
      AutofillHints.telephoneNumber,
      AutofillHints.postalCode,
      AutofillHints.addressCity,
      AutofillHints.creditCardNumber,
    ],
  ),
),
```

**Expected results:** Some hints shown, as there are many `autofillHints` provided

**Actual results:** No hints shown

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.71, on Microsoft Windows [VersiÃ³n 10.0.19041.264], locale es-ES)
    • Flutter version 1.19.0-2.0.pre.71 at C:\src\flutter
    • Framework revision 800e951160 (15 hours ago), 2020-05-14 20:47:01 -0400
    • Engine revision 50e55cf69e
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1-dev.5
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)


[✓] Connected device (3 available)
    • Pixel 3 XL • 192.168.1.33:5555 • android-arm64  • Android 10 (API 29)
    • Web Server • web-server        • web-javascript • Flutter Tools
    • Chrome     • chrome            • web-javascript • Google Chrome 81.0.4044.138
```

</details>

cc/ @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
Thanks for reporting this issue! By "hints not showing" you mean the autofill dropdown is not showing (i.e. autofill is not triggering on the `TextField`)? The same sample code seems to be working on my end (with a custom autofill service that autofills everything).
The autofill service has the final say about whether autofill should be triggered on a text field, so the one you're using probably doesn't support autofilling those hints.

**Comment by Zazo032** [comment]
I'm using Android (10)'s built-in autofill service (the one I always use). Maybe it's not supported? I didn't test on iOS, though.

**Comment by LongCatIsLooong** [comment]
So it does work in a native application using an `EditText`. I'll try to figure out what made the difference.

**Comment by LongCatIsLooong** [comment]
The google autofill also expects us to `setDimens` on the virtual child. Should be a quick one. Thanks again for catching this!

**Comment by chiragmittal19** [comment]
I'm still not able to get this working -

'''

    @override
    Widget build(BuildContext context) {

    return Form(
      key: _formKey,
      child: AutofillGroup(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
        
            TextFormField(
              decoration: InputDecoration(labelText: "Phone number / Email / Username",),
              textInputAction: TextInputAction.next,
              autofillHints: [AutofillHints.telephoneNumber, AutofillHints.email, AutofillHints.username],
              controller: _usernameController,
              validator: (value) => value.trim().isEmpty ? "Required" : null,
              onFieldSubmitted: (_) => FocusScope.of(context).nextFocus(),
            ),
        
            SizedBox(height: 8),
        
            TextFormField(
              decoration: InputDecoration(labelText: "Password",),
              obscureText: true,
              textInputAction: TextInputAction.done,
              autofillHints: [AutofillHints.password],
              controller: _passwordController,
              validator: (value) => value.isEmpty ? "Enter password" : null,
              onFieldSubmitted: (_) => _onSubmit(),
            ),
        
            SizedBox(height: 8),
        
            FlatButton(
              child: Text("Submit"),
              onPressed: _onSubmit,
            ),
      
          ],
        ),
      ),
    );
    }
'''

**Android 10
Flutter 1.19.0-4.2.pre • channel beta
Dart 2.9.0**

**Comment by LongCatIsLooong** [comment]
What's the autofill service you're using? (You should be able to find out in settings-> search for "autofill")

**Comment by jameswasher** [comment]
I'm using Google for autofill:
https://d.pr/i/ynrer6

On a native app my autofill looks like this:
https://d.pr/i/pBGBEQ

But in flutter on Android it looks like this and will not fill a password:
https://d.pr/i/0ypvlN

It works on iOS and Chrome.

**Comment by LongCatIsLooong** [comment]
@jameswasher it is probably because google autofill does not have the credentials for your app. From the looks of it, only the email autofill is happening. AFAIK the only way to add app credentials to google autofill using autofill save which has not been merged to master yet.

**Comment by chiragmittal19** [comment]
> What's the autofill service you're using? (You should be able to find out in settings-> search for "autofill")

I'm using Google for Autofill. But nothing is coming up. Maybe something is wrong with my code/setup/understanding. But I'm just following the examples and implementations by others.

**Comment by jdeltoft** [comment]
Hi, I'm trying to get email/password to fill in on a flutter app on Android.  The web code is 100% the same code as the app code by the way.   It works on chrome on this phone, and on chrome on my pc.  But the app itself has two things I'm trying to figure out:

1) in the app the email addresses it offers to autofill are two personal ones but how do I get other emails in that list (like my work email)?

2) on Android the email has auto fill options but the password doesn't.  Is that expected?

I'm on:

-------------------------------
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.14.6 18G6020, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!

-------------------------------

**Comment by LongCatIsLooong** [comment]
@jdeltoft I think saving user input autofill is part of the 1.20 release. 

For 1, the autofill service currently in use on your phone provides the autofill data. So maybe adding that email address in `System > Languages & input > Autofill serivce > Google" will help?
For 2, If you're using google autofill, try manually logging in and you should see a system prompt that says "save user input?" (If it doesn't, you can explicitly request the system to save by calling `TextInput.finishAutofillContext()`). Once the credentials are saved the dropdown menu should show up for password.

**Comment by jdeltoft** [comment]
@LongCatIsLooong Thanks for the fast response.  Ok, I had a lot to learn about google autofill service.  Thanks for pointing out the answer to (1).  I am still not sure if there is a way to add another email (not gmail) to my list of possible autofill emails on my google account, but I'll investigate.  

I used my work phone on android with the same app and it worked beautifully to offer to auto populate the password. Oddly, if the password is changed google isn't offering to save a new one.  So then I went to the google password manager and deleted the app entry.  Sure enough, I also don't get an offer to save it again.  I do call that finish function:

                    child: RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8.0)),
                      onPressed: _loginBtnEnabled
                          ? () {
                              // TODO: still not sure if this is fully working
                              TextInput.finishAutofillContext();

                              // close the keyboard
                              SystemChannels.textInput
                                  .invokeMethod('TextInput.hide');

                              if (_formKey.currentState.validate()) {
                                doLogin(_emailController.text,
                                    _passwordController.text);
                              }
                            }
                          : null,
                      child: setUpButtonChild(),
                    ),

   Any ideas what I might be doing that prevents it from offering to save the password?  the doLogin() function does bring up a dialog to pick from a list of accounts you want to use for that give login.  Is that dialog maybe blocking the save password?

**Comment by LongCatIsLooong** [comment]
@jdeltoft sorry I'm not sure why the save password dialog wouldn't show up again. Does terminating and relaunching the app help? 

It's unlikely that the dialog blocked the save password dialog, since it worked for the first time.

**Comment by jdeltoft** [comment]
@LongCatIsLooong Ok, I was reading through https://github.com/flutter/flutter/pull/58731 just to see if I was missing something.  Per your question, I've tried completely restarting and even reinstalling my app.  Nothing that I've seen triggers the save.  I'm honestly totally lost how the google password manager ever got an entry for my app.  That's exactly why I deleted it to see how it got in there.  I've tried on two android phones.  Samsung S9 and Moto Zoom One.  I'm just totally lost right now figuring out how to make the google password manager save to come up.  I have the call to TextInput.finishAutofillContext() from a button that is built in the same widget tree as the two text fields which are under an AutofillGroup().  Is there any thing I'm missing there to tell the system to bring up the save dialog?

**Comment by jdeltoft** [comment]
Ok, even more strange is while I test (currently on the Galaxy S9) I was able to get the "do you want to save" system message to come up a few times.  I clicked login but then dismissed the dialog to pick from the list of accounts and clicked login again.  But I now can't replicate that.  Nothing is changing in my code but the "save autofill" seems totally intermittent showing up or not.  Any logging in the system I can get that might help?  As I click on the username or password text fields, I also notice a "blip" where autofill is maybe going to show but doesn't since something is already filled in the text field?

**Comment by marcsanny** [comment]
@jdeltoft Hi, I get the same result. Did you managed to solve it?

**Comment by LongCatIsLooong** [comment]
@jdeltoft @marcsanny https://github.com/flutter/flutter/issues/69111 unfortunately there is a bug that makes it very difficult to bring up the save dialog on Android.

**Comment by jdeltoft** [comment]
@marcsanny I was not able to figure anything out yet with this.  I am happy it's working well on chrome for my app (I use the same for chrome/ios/android) and seems to sort of work on ios and android.  Not sure about the bug @LongCatIsLooong mentions.  Is there a link to that bug to see if it ever gets fixed?

**Comment by benjaminbisinger** [comment]
For those who still do not get any autofill options on Android:
What was missing for me is this migration https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects.
Notably, your MainActivity needs to extend io.flutter.embedding.android.FlutterActivity and not io.flutter.app.FlutterActivity.
Also, as already mentioned, you need to configure an AutoFill service in the system settings.

> it is probably because google autofill does not have the credentials for your app.

This was not the case for me (Android 11). If there are no credentials for this specific app it will just bring up the option to choose any of your stored credentials. This was also the case with LastPass and also on iOS.

> on Android the email has auto fill options but the password doesn't. Is that expected?

For me it is working on both fields as long as you didn't pick an autofill yet (fields are empty). Working sample code:

``` 
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
      title: Text("Login"),
    ),
    body: AutofillGroup(
        child: Column(
      children: [
        TextField(
          autofillHints: [AutofillHints.email],
          keyboardType: TextInputType.emailAddress,
        ),
        TextField(
          autofillHints: [AutofillHints.password],
          keyboardType: TextInputType.text,
        ),
      ],
    )));
```
Username instead of email should work similarly.

**Comment by aleslanik2** [comment]
Hi, i have very similary setup. And i see in LogCat, immediately after call 
`TextInput.finishAutofillContext(shouldSave: true);
`
 log 
`I: not showing save UI because fields failed validation" 
`
 IMHO this is a clue to our case.

**Comment by ErliSoares** [comment]
On Android I had the same problem, I had to make two changes:
1º: When completing the form I had to call `TextInput.finishAutofillContext (shouldSave: true);`
2º: I was not using the controller in TextFormField, I put the controller in the password and user field.
3º: When completing the form before changing the screen, the password in the controller `_senhaController.text = _bloc.senhaField.value;`

I didn't understand the reason, but only with these steps I managed to put to save the identification settings with the goole.

**Comment by RahmatAliMalik5** [comment]
The autofill was not working for me. Updating Flutter by following [this]( https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and then enabling the Google Auto Fill worked for me.
