### ISSUE TITLE
Devicelab android devices periodically run out of disk space

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#57325]
I believe the root cause of this is that when try to install an app to a device that already has a previous version of the app, it gets copied first to a temp directory where it will be tested for validity. In the course of normal devicelab operation, these (apparently) never get cleaned out. Possible action points:

1. Delete previous version of app before installing new one
2. Periodic reboot/tmp dir cleaning
3. Add available device disk space check to existing agent health check

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/39925
