### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark hotRestartMillisecondsToFrame regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#57323]
![Screen Shot 2020-05-15 at 9 20 34 AM](https://user-images.githubusercontent.com/1435716/82072954-593dd100-968d-11ea-9536-0ab74754d722.png)

Difficult to find one particular commit.

**Comment by zanderso** [comment]
Is this the same benchmark that @liyuqian rebaselined for https://github.com/flutter/flutter/issues/55965?

**Comment by liyuqian** [comment]
It's the same benchmark, but this time the regression seems to be much worse.

**Comment by zanderso** [comment]
Both of the "hot_mode_dev_cycle" benchmarks have turned red recently. @jonahwilliams could you take a look?

**Comment by jonahwilliams** [comment]
currently bisecting with 3 runs per commit. Will take a while

**Comment by jonahwilliams** [comment]
I can repro the regression, still finding culprit

**Comment by jonahwilliams** [comment]
It looks there were two regressions:

https://github.com/flutter/flutter/commit/97f6e279fa00

After: 772.3333333 avg | 34.53018004 std
Before: 695 avg | 13.45362405 std


Still looking for the second

**Comment by jonahwilliams** [comment]
The contained https://github.com/flutter/engine/pull/18276

**Comment by jonahwilliams** [comment]
Based on a cursor reading of the changes there, updates to the analyzer or release compiler are unlikely to have affected this benchmark. The most likely would be updates to the parser or CFE, which would be either:

> 2020-05-11 jensj@google.com [parser] Add ErrorToken for ignored (unmatched) end parenthesis, brackets etc
> 2020-05-11 jensj@google.com [CFE] Include _fe_analyzer_shared in tests

FYI @jensjoha

**Comment by jensjoha** [comment]
Neither of those changes should change anything for a benchmark. One only changes things with unbalanced parenthesis (i.e. source has errors); the other only enables some tests and makes some types explicit.

**Comment by zanderso** [comment]
I guess we'll have to do some local engine builds to bisect on the Dart SDK commits? If the --local-engine support in the tool isn't good enough to do that, we should improve the --local-engine support.

**Comment by Hixie** [comment]
@jonahwilliams Any updates? This is a P0 bug.

**Comment by jonahwilliams** [comment]
I am slowly bisecting the dart commits today to verify.

**Comment by jonahwilliams** [comment]
FWIW, I bisected it down a dart engine roll and found that to be a reasonable place to stop. @jensjoha followed and commented that he didn't think it was the commit I suspected, so I'm resuming bisecting

**Comment by jonahwilliams** [comment]
Continuing to bisect. It doesn't seem like the CFE change, looking at the vm/runtime change.

**Comment by jonahwilliams** [comment]
I bisected the dart engine commits:

156970a24 : 790.6666667 ms 
dart/a6d06b59ec4b : 734 ms 
[dart/7d253a5826f7fb3aab245fca16b77b181cc1fd86](https://dart.googlesource.com/sdk.git/+/7d253a5826f7fb3aab245fca16b77b181cc1fd86) : 775 ms
[dart/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6](https://dart.googlesource.com/sdk.git/+/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6) : 761 ms
[dart/64714f25967018880f71e1b63f244caa1d0a204c](https://dart.googlesource.com/sdk.git/+/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6):  764 ms

If I were to guess, I would say it _has_ to be 7d253a5, unless the Skia roll also caused a regression - which seems unlikely

Unfortunately for all of these the std deviation is in the 30s, which makes pinpointing the exact point difficult. Separately I discussed offline with @zanderso and we really need more finely-grained benchmarks here.

**Comment by jonahwilliams** [comment]
According to @zanderso , the regression might show up better if background compilation is disabled. This required two small diffs:

```
diff --git a/dev/devicelab/lib/tasks/hot_mode_tests.dart b/dev/devicelab/lib/tasks/hot_mode_tests.dart
index f1744bd45d..5aa64ecc79 100644
--- a/dev/devicelab/lib/tasks/hot_mode_tests.dart
+++ b/dev/devicelab/lib/tasks/hot_mode_tests.dart
@@ -25,7 +25,8 @@ TaskFunction createHotModeTest({String deviceIdOverride, Map<String, String> env
     final File benchmarkFile = file(path.join(_editedFlutterGalleryDir.path, 'hot_benchmark.json'));
     rm(benchmarkFile);
     final List<String> options = <String>[
-      '--hot', '-d', deviceIdOverride, '--benchmark', '--verbose', '--resident', '--output-dill', path.join('build', 'app.dill')
+      '--hot', '-d', deviceIdOverride, '--benchmark', '--verbose', '--resident', '--output-dill', path.join('build', 'app.dill'),
+      '--dart-flags=--no_background_compilation',
     ];
     int hotReloadCount = 0;
     Map<String, dynamic> twoReloadsData;
```

and

```
diff --git a/shell/common/switches.cc b/shell/common/switches.cc
index 0f0c7fc14..c02ae4671 100644
--- a/shell/common/switches.cc
+++ b/shell/common/switches.cc
@@ -43,6 +43,7 @@ struct SwitchDesc {
 static const std::string gDartFlagsWhitelist[] = {
     "--no-causal_async_stacks",
     "--lazy_async_stacks",
+    "--no_background_compilation",
 };
 // clang-format on
 
@@ -61,6 +62,7 @@ static const std::string gDartFlagsWhitelist[] = {
     "--trace-reload",
     "--trace-reload-verbose",
     "--write-service-info",
+    "--no_background_compilation",
 };
 // clang-format on
```


64714f25 : 834.75 | 77.090315 std deviation
a6d06b59ec: 801.5 | 12.81925635 std deviation

**Comment by jonahwilliams** [comment]
FYI @sstrickl 

@a-siva @zanderso @Hixie what is the path forward here?

**Comment by jonahwilliams** [comment]
So it seems like there was a regression between [dart/a6d06b59ec4b65fefa173a25458fde6f098a3510] and [dart/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6] of a couple ms. Most notably though, the standard deviation across multiple runs went up significantly. This can be seen in all of the results above, and in the benchmark numbers themselves.

There might have been secondary regressions, but the variation in the benchmark after that change is completely hiding it.

**Comment by zanderso** [comment]
To clarify/summarize a bit, the data that we have suggests that the change here https://dart.googlesource.com/sdk.git/+/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6, both regressed this benchmark (a little), but also caused the runtime to become much more variable, which is obscuring other reasons the benchmark might have regressed as part of the engine roll.

**Comment by a-siva** [comment]
The dart roll flutter/engine#18276 listed here is pretty old (almost 9 days old) and reverting the engine back to a version before that could be drastic.
If it is not obvious which dart CL caused it we can revert the following CLs
dart/7d253a5826f7fb3aab245fca16b77b181cc1fd86 : 775 ms
dart/96df1f9e6c9d67c1b4989e2fa24b19bcb5d5f6d6 : 761 ms
dart/64714f25967018880f71e1b63f244caa1d0a204c: 764 ms
on top of tree Dart and when that rolls in to the engine we can see if the regression is fixed.

**Comment by jonahwilliams** [comment]
I ran more iterations of each commit: the result is that there is no clear revert indicator where the regression could have happened.


  | AVG | STDDEV | AVG (No-background) | STDDEV (No-background)
-- | -- | -- | -- | --
4e52082 Deprecated DartType.isObject by Konstantin Shcheglov · 9 days ago |   |   |   |  
1120d64 Simplify InterfaceType.isDartXyz implementations. by Konstantin Shcheglov · 9 days ago |   |   |   |  
10172cd LSP Server: Forward overlay changes to plugins by Simon Binder · 9 days ago |   |   |   |  
96df1f9 [parser] Add ErrorToken for ignored (unmatched) end parenthesis, brackets etc by Jens Johansen · 9 days ago | 761 | 32 | 834 | 77
64714f2 [CFE] Include _fe_analyzer_shared in tests by Jens Johansen · 9 days ago | 764 | 31 | 798 | 55
3305642 [release] Add release notes for 2.8.2 by Alexander Thomas · 9 days ago | x | x | x | x
7d253a5 [vm/compiler] Allow SameAsFirstInput() in LocationSummary::set_out(). by Tess Strickland · 10 days ago | 775 | 24 | 803 | 39
a6d06b5 Reland "[vm] Mark snapshots that were compiled directly to ELF. | 757 | 31 | 801 | 12
a6d06b5 Reland "[vm] Mark snapshots that were compiled directly to ELF. (CLEAN) | 779 | 36 |   |  

Is it possible we changed some configuration/builder on LUCI instead?

**Comment by jonahwilliams** [comment]
At this point I assume that I messed something up when bisecting

**Comment by jonahwilliams** [comment]
Okay, I spent all morning rerunning a bunch of flutter/flutter commits. My conclusion is that there was no measurable regression. Any observed regression was the result of either a phone/laptop batter level getting too low, or just a statistical anomaly. I cannot get meaningfully different numbers from before the benchmark went red or from today.

Under normal, non-remote circumstances I would just go stare at the machine to see what is up. Maybe the phone is heating up, maybe there are some process leaks. Note that the regular hot restart benchmark regressed a _tiny_ bit, but likely not a detectable amount.

**Comment by zanderso** [comment]
@godofredoc, @digiter: @jonahwilliams is having trouble reproducing this regression locally. Is there any way for him to directly access the lab machine/device to perform the bisect there?

**Comment by godofredoc** [comment]
Yes, go/flutter-devicelab#accessing-via-ssh we need to kill the agent before bisecting and then restart it at the end.

**Comment by jonahwilliams** [comment]
thanks @godofredoc

**Comment by jonahwilliams** [comment]
I accessed the specific hardware and reran the benchmark at two commits (just once for now):

e92afc16b6445611b32fe19795768d16accd2c1d (HEAD)   1846ms
9d4b0cb84405d99e5d6814d4723e32be93fddded  (Before the regression, clearly green)             2395 ms

This looks like an issue with the hardware or the attached device.

**Comment by digiter** [comment]
@jonahwilliams You may want to take a screenshot of the attached device. Instructions at https://g3doc.corp.google.com/company/teams/flutter/devicelab/macos_host.md#attached-ios-device

**Comment by jonahwilliams** [comment]
It looks like something is wrong with either the attached device or host. As a short term solution, what do you think about disabling that device or re-baselining the benchmark and filling issue to track it down?

At any rate, we should remove the TODAY designation, but without a rebaseline it will just show up again.

**Comment by zanderso** [comment]
@digiter could you explain a bit what we could do with a screenshot?

**Comment by digiter** [comment]
@jonahwilliams I'm fine with either way, disabling host / device or disabling the test.

@zanderso To check whether the device has a system dialog or something.

**Comment by jonahwilliams** [comment]
@digiter noob question, how do I get the image off off the devicelab host :)

**Comment by digiter** [comment]
I usually `scp` the image to my machine or `vnc` to the host to view the image directly.

**Comment by jonahwilliams** [comment]
Assuming I don't have vnc setup correctly, do you have an example scp command saved somewhere?

**Comment by digiter** [comment]
I will share the command after a meeting.

**Comment by jonahwilliams** [comment]
I updated the baseline to 8000, since the test is not currently reliable.

**Comment by jonahwilliams** [comment]
Removing TODAY

**Comment by digiter** [comment]
An example: `scp -o "ProxyCommand ssh flutter@flutter-ssh-bridge-001.mtv.corp.google.com -W %h:%p"   flutter@192.168.1.x:~/Downloads/screen.png  ./screen.png`

**Comment by jonahwilliams** [comment]
Software update dialog is showing. Can we detect this automatically somehow?

**Comment by digiter** [comment]
Not yet. But we have a way to dismiss the dialog: clone the [infra-dialog repo](https://github.com/digiter/infra-dialog), open it with Xcode and run the XCUITest in it.

**Comment by zanderso** [comment]
@digiter is it expected that dismissing the dialog will restore the benchmark performance?

**Comment by digiter** [comment]
Likely, not 100% sure though.

**Comment by zanderso** [comment]
@digiter is dismissing the dialog in this situation already part of an infra playbook or documentation somewhere?

**Comment by digiter** [comment]
We documented common operations in the devicelab, e.g. https://g3doc.corp.google.com/company/teams/flutter/devicelab/macos_host.md#troubleshooting but not about benchmark regression.

**Comment by keyonghan** [comment]
@digiter Thanks for helping out.
@zanderso Dismissing the dialog should fix the regression. If not, please try rebooting. Months ago, rebooting helped bring benchmarks back.

**Comment by zanderso** [comment]
@digiter Cool thanks for the info. I've asked @kf6gpe to try to include that link in the future when reporting iOS benchmark regressions.

**Comment by a-siva** [comment]
@jonahwilliams thank you for the detailed analysis and investigation on this regression, this would have been a hard one for the Dart team to nail down if you had just concluded it was a Dart regression and passed it on to us.

**Comment by digiter** [comment]
Triage: please reopen if this occurs again.
