### ISSUE TITLE
Flutter not running on android and there are 2 Errors which I can't solve it?  Can anybody help me

### ISSUE THREAD

**Issue by rishabhshukla7** [flutter/flutter#57330]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.3.1/android/src/main/java/com/baseflow/geolocator/tasks/LocationUpdatesUsingLocationManagerTask.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.11/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Type com.google.firebase.iid.zzbb is referenced as an interface from `com.google.firebase.messaging.zzf`.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'firebase-messaging.aar (com.google.firebase:firebase-messaging:20.0.1)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/macky/.gradle/caches/transforms-2/files-2.1/f5d24118e2d32d6809cb9fe786fd2000/jetified-firebase-messaging-20.0.1-runtime.jar.
         > Error while dexing.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 46s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ma7mod7osam** [comment]
I have the same issue, anyone can help us ?

**Comment by pedromassango** [comment]
Cc> @TahaTesser

**Comment by rishabhshukla7** [comment]
> Cc> @TahaTesser

Cc means

**Comment by pedromassango** [comment]
> > Cc> @TahaTesser
> 
> Cc means

It means Carbon Copy. I'm just calling him to see this issue!

**Comment by grammystrano** [comment]
Same here

**Comment by grammystrano** [comment]
@zanderso come see ghis plz

**Comment by grammystrano** [comment]
Implement this ur builde gradle in app directory :


```
implementation 'com.google.firebase:firebase-messaging:20.1.7'
```

**Comment by pedromassango** [comment]
> D8: Type com.google.firebase.iid.zzbb is referenced as an interface from

This seems something to do with Firebase. @rishabhshukla7 are you using Firebase package?

**Comment by rishabhshukla7** [comment]
> > D8: Type com.google.firebase.iid.zzbb is referenced as an interface from
> 
> This seems something to do with Firebase. @rishabhshukla7 are you using Firebase package?

Yes bro I'm using it
But what does this problem means?

**Comment by pedromassango** [comment]
> But what does this problem means?

I have no idea.

Could you try @grammystrano's solution to see if it works for you?

**Comment by rishabhshukla7** [comment]
> Problem Solved !
> Implement this in ur builde gradle in app directory :
> 
> ```
> implementation 'com.google.firebase:firebase-messaging:20.1.7'
> ```

This works for me , Thank you so much
to all of you

**Comment by rishabhshukla7** [comment]
Running Gradle task 'assembleDebug'...
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.3.1/android/src/main/java/com/baseflow/geolocator/tasks/LocationUpdatesUsingLocationManagerTask.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/macky/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.11/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build/app/outputs/apk/debug/app-debug.apk.

**Comment by rishabhshukla7** [comment]
How to solve all this problem which flutter gave me

**Comment by VladyslavBondarenko** [comment]
@rishabhshukla7 
this is not an error, but simply warning. See https://stackoverflow.com/questions/56942236/flutter-plugin-inapppurchaseplugin-java-uses-unchecked-or-unsafe-operations
Closing

**Comment by zanderso** [comment]
@blasten is it expected that the plugins have the build warnings listed in https://github.com/flutter/flutter/issues/57330#issuecomment-632173664?

**Comment by putheng** [comment]
I have the same issues 

```
implementation 'com.google.firebase:firebase-messaging:20.1.7'
```
not work for me
