### ISSUE TITLE
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.

### ISSUE THREAD

**Issue by Jay-Tillu** [flutter/flutter#57342]
When I run the app for the first time on my new ubuntu 20.04 installation. It giving me this error.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
