### ISSUE TITLE
Error type 2 android.util.AndroidException: Can't connect to activity manager

### ISSUE THREAD

**Issue by per19** [flutter/flutter#5734]
## Flutter Doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/nb/flutter
    • Framework revision 9a0a0d9903 (3 weeks ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /home/nb/Android/Sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```
## Flutter devices

1 connected device:

sdk phone armv7 • emulator-5554 • android-arm
## Flutter run

```
Running lib/main.dart on sdk phone armv7...
--------- beginning of main
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
    at com.android.commands.am.Am.onRun(Am.java:298)
    at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
    at com.android.commands.am.Am.main(Am.java:99)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
Timed out while waiting for a debug connection.
Error running application on sdk phone armv7.
```

**Comment by eseidelGoogle** [comment]
android.util.AndroidException: Can't connect to activity manager; is the system running?
 is an error from `adb` itself.  I wonder if other adb commands were working with this.

`flutter run -v` might help us diagnose further. I would expect flutter to work on android arm simulators (as long as they have some sort of gpu emulation).

**Comment by per19** [comment]
with flutter run -v the emulator keeps crashing.

**Comment by eseidelGoogle** [comment]
Thank you very much for the report.  We've greatly improved our tooling since this was filed. Please give things a try again, and if they don't work we're happy to work with you to find a fix.  But for now I think I should close this particular bug.
