### ISSUE TITLE
Flutter Inspector Jump to Source not working after recent update

### ISSUE THREAD

**Issue by masthan8** [flutter/flutter#57358]
Hi, I am trying to use the flutter inspector and the jump to start is not working. Tried all the solutions availalbe on GIt and nothing happens to be a working solution

**Comment by TahaTesser** [comment]
Hi @masthan8 
Just tested Jump to Source and it has no issue on Android Studio or dev tools in VSC
Where you experiencing this issue?
can you please provide your `flutter doctor -v`? 
Thank you

**Comment by masthan8** [comment]
Hi, 

Just figured out the issue but it really weird as I have never experienced this before. It worked after moving the project to the android studio project folder where new projects are created by default. Is that how it is supposed to work because my last project was in a different drive it all worked fine, and this issues popped out of no where.

Thanks

**Comment by TahaTesser** [comment]
Hi @masthan8 
That's not how it is suppose to be and  i don't think location would influence this
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
