### ISSUE TITLE
i used fcm in mu flutter app but i face broblem

### ISSUE THREAD

**Issue by hisham79** [flutter/flutter#57354]
i used fcm in mu flutter app but i face broblem , The problem is that I cannot send more than three messages . There is a limit to the number of daily messages within the application but I do not know where it is ,,, and if i run app i found this in log

E/FlutterFcmService( 4047): Fatal: failed to find callback

Determine the number of messages based on the IP address where each IP address is allowed with messages

How do I delete this limit from the application?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
