### ISSUE TITLE
Widget get built twice

### ISSUE THREAD

**Issue by sanuzzi** [flutter/flutter#57353]
Can you reopen this issue? #33566 
Months ago there was another comment but the issue didn't reopened. And I just commented with another example. Can you take a look at it please?

**Comment by jonahwilliams** [comment]
Flutter does not guarantee `Widget.build` will be called the minimum number of times possible. You should structure your application in a way that assumes build will be called on every frame - anything less is an optimization.

**Comment by sanuzzi** [comment]
@jonahwilliams 
Build on every frame is the same mistake that Unity have had for years. Please don't do the same.
I would like you to really focus on this:

> Our other main goal is to improve Flutter's quality (...) and the development experience [(1)](https://github.com/flutter/flutter/wiki/Roadmap)

Also, your latest version mentions many performance improvements [(2)](https://medium.com/flutter/announcing-flutter-1-17-4182d8af7f8e), I think this issue is align with that, for next releases.

**Comment by omerasif57** [comment]
In my case it is effecting the animation. My widget tree is slightly complex and build is called more than twice (sometimes). I am a bit naive to flutter so will try to investigate and restructure my code.
My usecase involves theme switching (dark-light) with `timeDilation=3.0`. Animation plugin works fine with a simple example code.

Anyway, any advise would be appreciated.
