### ISSUE TITLE
did flutter methodchannel support return a List<Map<String, String>> value?

### ISSUE THREAD

**Issue by leagmain** [flutter/flutter#57363]
as title said, I wrote an plugin that return a List<Map<String, String>> value, but I can't get the result from my plugin, and there was no error.

Is any thing wrong?

How to implement the customized type returned by MethodChannel?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
