### ISSUE TITLE
How do I convert Kotlin source files to java

### ISSUE THREAD

**Issue by LOLIPOP-INTELLIGENCE** [flutter/flutter#57366]
Hi,
I am following several tutorials to learn flutter but all of the platform specific code is in Java, a language which I know. However when I created my flutter project, the default android source is in Kotlin, a language which I do not know. Therefore is there a way for me to convert my Kotlin files(Main activity) to java?

**Comment by azbuky** [comment]
Hi @LOLIPOP-INTELLIGENCE 

You can use the --android-language (-a for short) option to specify the langauge when you create your flutter project
```
flutter create --android-language java project_name
```

For  more details see
```
flutter help create
```

**Comment by LOLIPOP-INTELLIGENCE** [comment]
Hi @azbuky 

I have already created the project and have some dart files in it. Can I still change the language to Java?

**Comment by azbuky** [comment]
First you should make a backup of your project, just in case.

You can then delete the android folder inside your project and run flutter create again with the java option and you should be good to go.

**Comment by LOLIPOP-INTELLIGENCE** [comment]
Thanks @azbuky for your reply! I'll try it out and let you know if I encounter any other problems. Thanks!!!

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
