### ISSUE TITLE
How to call third party lib(.so file) with desktop app using flutter

### ISSUE THREAD

**Issue by hry625** [flutter/flutter#57377]
I am trying to writte a desktop app with third party lib(.so). I read the doc about dart:ffi, but I am wondering how can I do that with desktop app on linux. 

Thank you for your great help.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
