### ISSUE TITLE
In app purchase gives BillingResponse.itemAlreadyOwned without PurchaseStatus.purchased

### ISSUE THREAD

**Issue by don-prog** [flutter/flutter#57373]
I use [in_app_purchase Flutter plugin](https://github.com/flutter/plugins/tree/master/packages/in_app_purchase) for Android in app purchases in my Flutter application. 

I buy using `_iap.buyConsumable(purchaseParam: purchaseParam)`(so, `autoConsume = true`)
and connect using `_iap.purchaseUpdatedStream.listen` for incoming purchases. If purchase has `PurchaseStatus.purchased` status then I send it to the server and register this purchase. But if purchase has `PurchaseStatus.pending`(it's Google test "Slow test card. Declines after a few minutes") then I do nothing and wait for another `_iap` message, but no other message about this purchase comes, but I see in Google console that this purchase is declined. 

But this is not the main problem. Main problem is that if user tries to buy the same product after `pending` purchase message, the he can't buy it due to error `BillingResponse.itemAlreadyOwned`. So, it's stuck. 

I thought that I can call this function after each app restart:
```
final QueryPurchaseDetailsResponse response = await _iap.queryPastPurchases();

response.pastPurchases.forEach((pd) => _iap.consumePurchase(pd) );
```
this gives:

> Error consuming purchase with token. Response code: 8

After this user can buy the same item again.
But I'm not sure - is it safe scenario or just dirty fix for this issue?
Also, how can I correctly wait for this pending purchases?

**Comment by don-prog** [comment]
Now I can't even `consumePurchase` because it's pending (according to the app), but Google console shows it as cancelled.

**Comment by TahaTesser** [comment]
Hi @don-prog 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by liri2006** [comment]
@don-prog it seems that there is a bug in billing module itself:
- https://issuetracker.google.com/issues/149668311
- https://issuetracker.google.com/issues/73982566

**Comment by TahaTesser** [comment]
Hi @don-prog 
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
