### ISSUE TITLE
[web]: Undiscovered flutter web error. 

### ISSUE THREAD

**Issue by harshraj6982** [flutter/flutter#57383]
Guys I am facing a problem in flutter web. I am following this tutorial 
https://flutter-examples.com/flutter-online-user-login-using-php-mysql-api/
In this tutorial I learned how to make an app having login feature with PHP MySQL. I just copy paste all the code from the above link and it actually works same as given above in Android and ios perfectly but it doesn't work in flutter web. The problem in flutter web is, when I click on the login button the spinner only rotates and doesn't return anything. If the credentials are wrong then it must throw an error by showing alert dialog and if the password is right then it must navigates to profile screen which is not happening in flutter web. And also it is not throwing any kind of error. 

Currently I am in latest beta channel. And I have latest google chrome.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by harshraj6982** [comment]
Yes the whole point is that, there is a bug in flutter sdk 1.17.0 beta channel for the web support. 

import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
 
void main() => runApp(
  MaterialApp(
    home: MyApp(),
    )
  );
 
class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return MaterialApp(
  home: Scaffold(
      appBar: AppBar(title: Text('User Login Form')),
      body: Center(
        child: LoginUser()
        )
      )
    );
}
}
 
class LoginUser extends StatefulWidget {
 
LoginUserState createState() => LoginUserState();
 
}
 
class LoginUserState extends State {
 
  // For CircularProgressIndicator.
  bool visible = false ;
 
  // Getting value from TextField widget.
  final emailController = TextEditingController();
  final passwordController = TextEditingController();
 
Future userLogin() async{
 
  // Showing CircularProgressIndicator.
  setState(() {
  visible = true ; 
  });
  debugPrint("1");
  // Getting value from Controller
  String email = emailController.text;
  String password = passwordController.text;
  debugPrint("2");
  // SERVER LOGIN API URL
  var url = 'https://pilot-bulkhead.000webhostapp.com/login_user.php';
  debugPrint("3");
  // Store all data with Param Name.
  var data = {'email': email, 'password' : password};
  debugPrint("4");
  // Starting Web API Call.
  var response = await http.post(url, body: json.encode(data));
  debugPrint("5");
  // Getting Server response into variable.
  var message = jsonDecode(response.body);
  debugPrint("6");
  // If the Response Message is Matched.
  if(message == 'Login Matched')
  {
 
    // Hiding the CircularProgressIndicator.
      setState(() {
      visible = false; 
      });
    debugPrint("7");
    // Navigate to Profile Screen & Sending Email to Next Screen.
      Navigator.push(context,MaterialPageRoute(builder: (context) => ProfileScreen(email : emailController.text)));
  }else{
 
    // If Email or Password did not Matched.
    // Hiding the CircularProgressIndicator.
    setState(() {
      visible = false; 
      });
 
    // Showing Alert Dialog with Response JSON Message.
    showDialog(
    context: context,
    builder: (BuildContext context) {
      return AlertDialog(
        title: new Text(message),
        actions: <Widget>[
          FlatButton(
            child: new Text("OK"),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
        ],
      );
    },
    );
  }
 
}
 
@override
Widget build(BuildContext context) {
return Scaffold(
  body: SingleChildScrollView(
    child: Center(
    child: Column(
      children: <Widget>[
 
        Padding(
          padding: const EdgeInsets.all(12.0),
          child: Text('User Login Form', 
                  style: TextStyle(fontSize: 21))),
        Divider(),
        Container(
        width: 280,
        padding: EdgeInsets.all(10.0),
        child: TextField(
            controller: emailController,
            autocorrect: true,
            decoration: InputDecoration(hintText: 'Enter Your Email Here'),
          )
        ),
        Container(
        width: 280,
        padding: EdgeInsets.all(10.0),
        child: TextField(
            controller: passwordController,
            autocorrect: true,
            obscureText: true,
            decoration: InputDecoration(hintText: 'Enter Your Password Here'),
          )
        ),
 
        RaisedButton(
          onPressed: userLogin,
          color: Colors.green,
          textColor: Colors.white,
          padding: EdgeInsets.fromLTRB(9, 9, 9, 9),
          child: Text('Click Here To Login'),
        ),
 
        Visibility(
          visible: visible, 
          child: Container(
            margin: EdgeInsets.only(bottom: 30),
            child: CircularProgressIndicator()
            )
          ),
 
      ],
    ),
  )));
}
}
 
class ProfileScreen extends StatelessWidget {
 
// Creating String Var to Hold sent Email.  
final String email;
 
// Receiving Email using Constructor.
ProfileScreen({Key key, @required this.email}) : super(key: key);
 
// User Logout Function.
logout(BuildContext context){
 
  Navigator.pop(context);
 
}
 
@override
Widget build(BuildContext context) {
return MaterialApp(
  home: Scaffold(
      appBar: AppBar(title: Text('Profile Screen'),
      automaticallyImplyLeading: false),
      body: Center(
        child: Column(children: <Widget>[
 
          Container(
          width: 280,
          padding: EdgeInsets.all(10.0),
          child: Text('Email = ' + '\n' + email, 
                style: TextStyle(fontSize: 20))
            ),
 
          RaisedButton(
          onPressed: () {
            logout(context);
          },
          color: Colors.red,
          textColor: Colors.white,
          child: Text('Click Here To Logout'),
        ),
 
        ],)
        )
      )
    );
}
}

Flutter web is not executing   var response = await http.post(url, body: json.encode(data));  this line of code. I have added debugPrint after every line and I see in debug console it is printing from 1 to 4.

I run this project in Android and ios and this worked perfectly there. This problem only arises in flutter web.

**Comment by azbuky** [comment]
@harshraj6982 The http.post method uses the browsers XMLHttpRequest under the hood for Flutter web so it is subject to the browser's [Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). 

You are making a request to another domain then your origin domain (localhost presumably) and your login server does not seem to support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
