### ISSUE TITLE
I/flutter ( 3635):RenderStack object was given an infinite size during layout. How to position container inside stack

### ISSUE THREAD

**Issue by atheistrepublic** [flutter/flutter#57386]
I am trying to position a container inside a stack but keeps getting this exception.How can i position the container of given size inside the stack using lets say right:0,top:0?The code i am using is shown below:
    **return SizedBox.fromSize(
				size:Size.fromHeight(300.0),
				child:Container(
					decoration:BoxDecoration(**
										
						color:Color(0xFFF3F3F5),
					),
					child:ListView.builder(
					scrollDirection:Axis.horizontal,
					itemCount:3,
					physics:BouncingScrollPhysics(),
					itemBuilder:(BuildContext context,index){
						print(10);
						return Stack(
							children:<Widget>[
								Positioned(
								right:0,
								top:0,
								child:Container(
									margin:EdgeInsets.symmetric(horizontal:15.0),
									height:80,
									width:140,
									
									decoration:BoxDecoration(
										borderRadius:BorderRadius.circular(16.0),
										color:Color(0xFFDDE3F0),
									),
									
								),),
								
							],
						);
					}
				),
				),

			
		);
![Screenshot from 2020-05-16 20-39-36](https://user-images.githubusercontent.com/58817288/82123150-7241a180-97b5-11ea-9450-73dbe7b4f6dd.png)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
