### ISSUE TITLE
Home Page Running Twice after upgrade to Flutter 1.17.0 (and 1.17.1) from 1.12.13+hotfix.9

### ISSUE THREAD

**Issue by GrahamDi** [flutter/flutter#57381]
I have a simple routes table in main.dart as follows:
```
        routes: {
          "/": (context) =>
              !globals.isAuthenticated ? AuthPage() : UsersPage(),
          "/profile": (context) =>
              !globals.isAuthenticated ? AuthPage() : UserProfilePage(),
        },
```
The "/" route is entered when I start the app without an authenticated user and it navigates to the AuthPage correctly. In the AuthPage it then authenticates with Google or email/password and uses Navigator.pushReplacementNamed  (context, "/") to load the UsersPage correctly. All good so far. However, somehow the UsersPage gets terminated (dispose runs) and processing goes back through the routes table, loading the UsersPage a second time (initState and all, this is not a build method rerun).
This return to the routes table in main.dart is not initiated by any Navigator call. It appears to happen immediately after the very first cycle through the build method of the UsersPage ie. before the page starts to paint.

I also make use of onGeneratedRoute but this section is not involved in the behaviour I am seeing.

This behaviour did not happen in v1.12.13+hotfix.9 or earlier and there have been no code changes to the pages involved. If I downgrade from 1.17.1 to 1.12.13+hotfix.9, all works correctly again.

Any ideas? ....spent two days trying to work this out before going back to an earlier Flutter version.

Here is flutter doctor -v output for the version of flutter that it is NOT working on:

flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.19628.1], locale en-GB)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @GrahamDi 
This looks like expected behaviour, please read this [comment](https://github.com/flutter/flutter/issues/56663#issuecomment-627468368)
Also you can you please code [sample](https://github.com/flutter/flutter/issues/56663#issuecomment-625792551) and let me know if the reproduces same behaviour for you

Might be related to https://github.com/flutter/flutter/issues/56663#issuecomment-627468368

**Comment by GrahamDi** [comment]
@TahaTesser  I saw that post but don't think it is the same thing. I was in touch with a guy called Suzuki Tomohiro on Google Groups and here requested a video of the behaviour and simplified code. I can't post the MP4 video here...how can I get it to you?

Regarding the code, I have created a stripped down version of the main.dart and the Auth and Users (home) pages involved. There is probably more that would make sense to cut and paste here...again, how do you want to see it?

**Comment by GrahamDi** [comment]
Hi @TahaTesser ,

I think I have found the issue. 

In my code I use both a global variable and a listener on an rxdart userSubject to determine if a user is authenticated - of course, this is duplicate code and I intended to remove the rxdart userSubject, as I am ore comfortable with global variables, but I hadn't got around to it. In the code I sent you in main.dart, lines 173 thru 193 deal with these flags. Line 186 sets the listener and executes a setState when a value is emitted - the value is subscribed to userSubject in the authenticateWithEmail method at line 192 in users_db_logic.dart.
It seems to be that the setState called as a result of the listener firing is causing a second run through the routes: block in main.dart and reloading the users.dart home page. This did not happen in v1.12.13...
but does happen in v1.17.0/1.

You can test this behaviour by setting a timer to run a setState every 5 seconds at the end of the main.dart initState block ie. put this code
```
    Timer _timer = Timer.periodic(Duration(seconds: 5), (timer) {
      setState(() {});
    });

```
above line 195 in main.dart. You will then see that the home (users.dart) page is run again and again...

Please confirm my finding.

The question would then be, is it intended behaviour for a delayed setState call in main.dart to rerun the routes: block?

**Comment by TahaTesser** [comment]
Hi @GrahamDi 
Can you please provide a minimal code sample?
Thank you

**Comment by GrahamDi** [comment]
Minimal code sample in in the .zip file attached above.
Do you want me to cut and paste the whole lot as well?

**Comment by TahaTesser** [comment]
@GrahamDi 
It's not minimal, it's has lot of folders and classes and packages 
Minimal code sample and also no third party packages [like this](https://github.com/flutter/flutter/issues/56663#issuecomment-625792551)

Thank you

**Comment by GrahamDi** [comment]
@TahaTesser Sorry to be unhelpful, but I have spent three days on this already, which is all the time I can afford. I have found the problem in my code to my satisfaction and can fix it. 

Think it is now up to you guys to decide if this a 'real' issue in v1.17.0, as it didn't happen in earlier versions, and if it needs your further attention ie. is it expected behaviour or not. Thanks anyway.
