### ISSUE TITLE
Plese Help me Debug yellow fixes

### ISSUE THREAD

**Issue by Taparako** [flutter/flutter#57388]
Sorry about the language , I'm not fluent in English
I studied flutter in group Programming Thailand In the part about appbar advance
and I write same in video all charactor

In video is'n had a debug but I find it

issue in PreferredSize required

this is my code >>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('flutter'),
          leading: IconButton(
            icon: Icon(Icons.menu),
            onPressed: () {

            },
          ),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.search),
              onPressed: () {
                
              },
            ),
            IconButton(
              icon: Icon(Icons.more_vert), 
              onPressed: () {

              },
            )
          ],
          flexibleSpace: SafeArea(
            child: Icon(
              Icons.photo_camera,
              size: 75.0,
              color: Colors.white70
            ),
          ),
        ),
        bottomSheet: (
          PreferredSize(
            child: Container(
              color: Colors.blue,
              height: 50.0,
              child: Center(
                child: Text('Mybutton')
              )
            ),
          )
        ),
        body: null,
      )
    );
  }
}
```

Pls help me fix it Thk a lot,
![97090839_3206212929418239_2882626768827580416_o](https://user-images.githubusercontent.com/65457175/82124200-a9b94980-97c7-11ea-822f-f9c1da12024d.jpg)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
