### ISSUE TITLE
Flutter hot reload not working in Android studio 3.6.3

### ISSUE THREAD

**Issue by AndrewH2O** [flutter/flutter#57399]
similar to #40352 @zanderso requested open new issue

very simple app:
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home:Center(child: Text('hello  world'))));
}

1) change text in above code
2) click Lightening bolt (flutter hot reload)or saving the dart file
3) 'syncing files to device AOSP on IA Emulator  shows in console but the actual emulator doesn't change

flutter doctor says connected device 1 available
emulator (Nexus 5X api 28)  shows as AOSP on IA Emulator.
perform hot reload on save is checked under languages and frameworks.
running on windows 10 with latest updates

however clicking flutter hot restart does change text

**Comment by jonahwilliams** [comment]
See https://flutter.dev/docs/development/tools/hot-reload#recent-ui-change-is-excluded

Changes to `main` does not hot reload, because main is only run a single time during program start.

**Comment by AndrewH2O** [comment]
thx closing

**Comment by vishwajit76** [comment]
What is the solution for a hot reload?
