### ISSUE TITLE
IndexedStack building background view

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#57397]
Hi,

I'm dealing with a weird issue.
I'm using BottomAppBar and I want that when the user switches page the state will preserve, so I'm using IndexedStack.

the performance of inflation was really bad so I started to investigate why is it happening, and I discovered the although the widget is not the top one in IndexedStack it also building it in the background with all other widgets on the background.

Someone has any idea why?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by dvird** [comment]
I seem like a bug. I don't think its should like this

**Comment by YoussefGheith** [comment]
same issue with me using flutter 1.17.0

**Comment by dvird** [comment]
@jonahwilliams. ??

**Comment by dvird** [comment]
@jonahwilliams  please reopen it, its a bug. bad performance. i have 6 widgets in the stack and its building them when they on background
