### ISSUE TITLE
coding with VS Code and but I can't emulate the flutter app in real device (phone)

### ISSUE THREAD

**Issue by khitermedachraf** [flutter/flutter#57394]
0

coding with VS Code but i cant emulate the flutter app in real device (phone) and icant use emulator or Android Studio cuz RAM [the syntaxe error on VS Code]

The error is in the image below:
![flutter](https://user-images.githubusercontent.com/38400387/82128067-03157e80-97b0-11ea-991d-1b3c186beb65.png)

**Comment by khitermedachraf** [comment]
showing issues

**Comment by khitermedachraf** [comment]
i installed ANDROID STUDIO and I fix the problem with the device emulator . but its still tell me 
the ANDROID SDK LISCENCE is not found . you should update your SDK. but i did that many times .
so my pc is mindless

**Comment by gourav-varma** [comment]
I had the same problem when i first started flutter. You need to download some things in android studio. Can't remember what exactly but check out some flutter installation videos on youtube. 
Good luck!

**Comment by jonahwilliams** [comment]
For instructions on how to get setup with flutter, see https://flutter.dev/docs/get-started/install
