### ISSUE TITLE
Failed to find assets path for "Frameworks/App.framework/flutter_assets"

### ISSUE THREAD

**Issue by combi-35** [flutter/flutter#57395]
Flutter version 1.17.1
Xcode version 11.4.1

Today after I restarted my app I got:
```
Running pod install...                                              2,2s
Running Xcode build...
Xcode build done.                                           17,0s
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[VERBOSE-2:engine.cc(129)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(485)] Could not launch engine with configuration.

```
I searched and found [#52084](https://github.com/flutter/flutter/issues/52084) referring to [https://flutter.dev/docs/development/ios-project-migration](https://flutter.dev/docs/development/ios-project-migration), so I changed everthing to match the docs but still same error.

I also noticed that after every build (try) Pods_Runner.framework  in "Link Binary With Libraries" was back altough I removed it every time.
<img width="1545" alt="Bildschirmfoto 2020-05-16 um 21 08 04" src="https://user-images.githubusercontent.com/56366138/82128183-740d6400-97b9-11ea-8e63-ee9561745147.png">

Same error also on flutter v1.12.13+hotfix.9 with Xcode 11.3.1

I hope there is a solution for this, thanks.

**Expected results:** 
Running App
**Actual results:** 
Stuck with white Launch Screen

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale de-AT)
    • Flutter version 1.17.1 at /Users/lukas/Flutter/flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lukas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 973B6543-B763-4826-B6DC-4DE8CFB3FD71 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

**Comment by joniaiuser** [comment]
I'm seeing the same error here: https://github.com/flutter/flutter/issues/56507. I think during Build, the step where frameworks are added is somehow missing/skipping.

**Comment by iapicca** [comment]
Hi @combi-35 
I see there's an open [issue](https://github.com/flutter/flutter/issues/56507) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by jmagman** [comment]
@combi-35's Xcode project is at https://github.com/combi-35/debug/blob/master/project.pbxproj.

You shouldn't need to delete Pods_Runner.framework.  

Can you attach the output of `flutter run` with the `--verbose` flag?  It will be large.

**Comment by combi-35** [comment]
Thanks for reopening!
Here is the flutter run --verbose [output](https://github.com/combi-35/debug/blob/master/runoutput.txt)

**Comment by jmagman** [comment]
Well it deleted the App.framework
```
           ♦ rm -rf -- /Users/lukas/Activity/activity/ios/Flutter/App.framework
           ♦ rm -rf -- /Users/lukas/Activity/activity/ios/Flutter/Flutter.framework
```
Then skipped the `debug_universal_framework`?
```
           ♦ /Users/lukas/Flutter/flutter/bin/flutter --verbose assemble --output=/Users/lukas/Activity/activity/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation= -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= debug_ios_bundle_flutter_assets
           [+1810 ms] Skipping target: kernel_snapshot
           [   +7 ms] Skipping target: debug_universal_framework
           [ +190 ms] debug_ios_bundle_flutter_assets: Starting due to {InvalidatedReason.outputMissing}
           [ +281 ms] debug_ios_bundle_flutter_assets: Complete
           [ +351 ms] Persisting file store
           [  +25 ms] Done persisting file store
           [   +6 ms] build succeeded.
           [   +9 ms] "flutter assemble" took 2 845ms.
           Project /Users/lukas/Activity/activity/ios/.. built and packaged successfully.
```

**Comment by jmagman** [comment]
Should `App.framework/App` be an input to that build system target, @jonahwilliams?  If the binary isn't there (and we always delete it so it's never there) it should rebuild, right?

**Comment by jmagman** [comment]
Well that was removed in https://github.com/flutter/flutter/pull/56094/files#diff-0d00f38df3883291f23cee8074ac075dL59 but this is being reported on stable.

**Comment by combi-35** [comment]
So App.framework & Flutter.framework should be readded automatically? I initially deleted them referring to Step 2 [ios-project-migration](https://flutter.dev/docs/development/ios-project-migration)

**Comment by jmagman** [comment]
@combi-35 No, you were correct to remove it from your Xcode project per https://flutter.dev/docs/development/ios-project-migration.  The `flutter` tool should be creating the App.framework under the covers for you outside of Xcode and embedding it into your app, which is what I was referencing in that comment.

**Comment by jmagman** [comment]
After the failure does `/Users/lukas/Activity/activity/ios/Flutter/App.framework` exist?

**Comment by jmagman** [comment]
```
		97C147061CF9000F007C117D /* Debug */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = BDFEF0882516627289590C01 /* Pods-Runner.debug.xcconfig */;
```
Okay same as https://github.com/flutter/flutter/issues/56507 why is this not getting set to `Debug.xcconfig`...

**Comment by jmagman** [comment]
@combi-35 Do you remember how long ago you created this project?  Can you attach your project `.metadata` file?

**Comment by jmagman** [comment]
\cc @dnfield is this the error you've been seeing?

**Comment by dnfield** [comment]
Different one.

**Comment by combi-35** [comment]
After failure App.framework & Flutter.framework folders are back.
I think I created the project in Jan. 2020.

**.metadata:**
version:
  revision: 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
  channel: stable

project_type: app

**Comment by LiveLikeCounter** [comment]
I got the same error. I've tried every related StackOverflow solution to solve this, without result. Hereby the output of:
- Flutter doctor -v
- Flutter run -v
- project.pbxproj
- the .metadata file
in the gist: https://gist.github.com/LiveLikeCounter/562ad24437d6cce1ef19a79f1a081426

I hope it helps! I've I can test something, please let me know. We're unable to release our app for around 5 weeks now.

**Comment by jmagman** [comment]
@LiveLikeCounter You've got the same problem, your base configuration is `Pods-Runner.debug.xcconfig` instead of the `Debug.xcconfig` with the generated Flutter variables.
```
baseConfigurationReference = 91DF5C9EDAE4F09EFA2782B5 /* Pods-Runner.debug.xcconfig */;
```

I can't figure out how everyone got in that state.  See my attempts at reproducing this in https://github.com/flutter/flutter/issues/56507#issuecomment-631187387.

I'm going to re-duplicate this to https://github.com/flutter/flutter/issues/56507, it's the same issue.

**Comment by LiveLikeCounter** [comment]
@jmagman thanks for you response. I think it's quite frustrating for you as well.
I've changed the configuration as you said,, please see: https://gist.github.com/LiveLikeCounter/de4f1964e89c4ec98a51954fbd5444a1
But still the the same:
```shell
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[VERBOSE-2:engine.cc(129)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(485)] Could not launch engine with configuration.
```
One thing I wondered, in the /ios/Flutter/Debug.xsconfig I see the following:
```shell
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
#include "Generated.xcconfig"
```
Shouldn't that been changed too?

**Comment by ProFive** [comment]
The same error

> 2020-05-24 21:52:17.475594+0700 Runner[4798:1191967] [Accessibility] ********** Accessibility: Loading SpeakCorrections
2020-05-24 21:52:19.380390+0700 Runner[4798:1191754] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2020-05-24 21:52:19.396548+0700 Runner[4798:1191754] Metal API Validation Enabled
2020-05-24 21:52:19.564512+0700 Runner[4798:1191754] [VERBOSE-2:dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
2020-05-24 21:52:19.564786+0700 Runner[4798:1191754] [VERBOSE-2:dart_vm.cc(248)] Could not setup VM data to bootstrap the VM from.
2020-05-24 21:52:19.564959+0700 Runner[4798:1191754] [VERBOSE-2:dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
2020-05-24 21:52:19.565133+0700 Runner[4798:1191754] [VERBOSE-3:shell.cc(268)] Check failed: vm. Must be able to initialize the VM.
(lldb)
