### ISSUE TITLE
Porting Java and Objective-C to Flutter

### ISSUE THREAD

**Issue by realrk69** [flutter/flutter#57390]
Hi there,

My company develops BLE based IOT products for Industry 4.0. For the past few years, we've been developing both Android and iOS apps for our devices. In Android, we have a .aar library that decodes the information received from the BLE sensor and the equivalent for iOS. Knowing the vast majority of possibilities in Flutter, I'm interested in porting all future applications to it. Can this be done by re-using existing java and objective c code? In case I can do this, how would I call such functions? Is there a guide?

Also, we have binaries from our vendor (library.a and library.dll). Is it possible to decode our data using them instead of separate iOS and Android libraries?

**Comment by hayderux** [comment]
See

https://flutter.dev/docs/development/platform-integration/platform-channels

**Comment by realrk69** [comment]
Rather than rendering the content on the app itself. We're now using Django in the backend to do this. It helps keep the data secure and anyway the data has to back for analysis to the server. Thanks for your quick reply. This helped.
