### ISSUE TITLE
Flutter doesn't seem to run in Android Emulator x86/x86_64 or Genymotion w/ Marshmallow

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#574]
Using the new Android Studio 2.0, with fresh new emulators running a Nexus 5 Marshmallow, details:

```
Name: Nexus_5_API_23
CPU/ABI: Google APIs Intel Atom (x86)
Path: /Users/sethladd/.android/avd/Nexus_5_API_23.avd
Target: Google APIs (API level 23)
Skin: nexus_5
SD Card: 100M
Snapshot: no
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5
vm.heapSize: 64
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
tag.id: google_apis
hw.camera.back: none
hw.mainKeys: no
AvdId: Nexus_5_API_23
hw.camera.front: none
hw.lcd.density: 480
runtime.scalefactor: auto
avd.ini.displayname: Nexus 5 API 23
snapshot.present: no
hw.device.hash2: MD5:2fa0e16c8cceb7d385183284107c0c88
hw.ramSize: 1536
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 200M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

The emulator boots up, flutter notices that the emulator exists, and looks like it loads our SkyShell.apk:

```
flutter • lib/main.dart • ​
[myapp/] flutter start
Installing SkyShell.apk on device.
android: --------- beginning of main
android: --------- beginning of system
```

However, I never see the app on the emulator. I think I see a very quick flash of a red border around the inside of the emulator's device's screen. The flash appears near/at the end of the "installing skyshell" step. This flash is not consistent, though.

**Comment by sethladd** [comment]
FWIW I was able to get Flutter working genymotion, which is another emulator.

**Comment by abarth** [comment]
Does the emulator run Arm or Intel binaries?

**Comment by sethladd** [comment]
Sorry, I missed your question. From what I can tell, genymotion does not do any arm translation.

**Comment by sethladd** [comment]
Trying to de-dupe. Closing in favor of https://github.com/flutter/flutter/issues/490
