### ISSUE TITLE
Include key.properties in .gitignore by default

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#57401]
### Description
I know you state it in the documentation to keep it local but why shall we always add it manually to .gitignore when it can be done by default? It adds to the complexity by adding so many little things to remember, especially when it comes to sensitive data. 

### Suggestion
Better be safe by including it in the .gitignore by default. E.g. like this:

```
# Android Signing
android/key.properties
```

### Example
I tried to be cautious to keep it only locally but forgot since I'm only a human being. Now, too late, and it's out there on my Github. Shame, Flutter didn't prevent that when it could have :(

**Comment by jmagman** [comment]
https://flutter.dev/docs/deployment/android#reference-the-keystore-from-the-app

**Comment by jmagman** [comment]
Not sure what the right thing to do here is. Users may want to check this file into source control if they don't have a public repository.  May be unexpected to clone a fresh repository and immediately get a gradle build issue?

@blasten Do you know the preferred pattern here, or someone who would know?

**Comment by blasten** [comment]
Adding this entry to the project’s .gitignore is fine. In the meanwhile, you can add it to your global .gitignore.

**Comment by jmagman** [comment]
@blasten But you think this should automatically be done in the `flutter create` template `.gitignore` for all projects?

**Comment by blasten** [comment]
That's correct. That file contain private data.

**Comment by tomasbaran** [comment]
If anyone doesn't have a public or doesn't want to share his/her project, he can remove that file from the .gitignore. But we are talking about security and sensitive data here. I think Flutter should make sure that leaking private information doesn't happen by default.
