### ISSUE TITLE
'Source directory does not exist' building Linux with CMake 3.10

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#57409]
使用 flutter run -d linux 出现了下面的问题

Launching lib/main.dart on Linux in debug mode...
CMake Error: The source directory "/home/mi/hello/build/linux/debug" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Exception: Unable to generate build files

过程：
1, mkdir hello && cd hello
2, flutter create . && flutter pub get 
3, flutter  run -d linux 

flutter version:
[✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.19.0-2.0.pre.83 at /home/mi/flutter
    • Framework revision 8abf0a6d8c (5 小时前), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mi/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/mi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2

[✓] Android Studio (version 3.6)
    • Android Studio at /home/mi/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!

**Comment by stuartmorgan** [comment]
Apparently the `-S`/`-B` form of the command I used is not available in 3.10; I was looking at older docs when checking file format details, but didn't check the command invocation syntax. I'll need to switch it to making the build dir and setting that as the working directory.
