### ISSUE TITLE
NavigatorObserver.didPush called in reverse order when using Navigator.initialRoute

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#57407]
Since the `Navigator` refactoring, when using `Navigator.initialRoute`, observers are notified of the initial route components being pushed from the deepest route to the top (`/`), which is the opposite order from what one would expect and from the previous behavior. This breaks any code that updates state depending on the most recent route pushed.

## Steps to Reproduce

1. Run `flutter create navigator-didpush-bug`.
2. Update `main.dart` as follows: 

```
import 'dart:developer';

import 'package:flutter/material.dart';

class MyNavigatorObserver extends NavigatorObserver {
  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    log('didPush route=${route?.settings?.name} previousRoute=${previousRoute?.settings?.name}');
  }
}

void main() {
  runApp(MaterialApp(
    title: 'Navigator Bug Demo',
    initialRoute: '/second',
    routes: {
      '/': (context) => FirstScreen(),
      '/second': (context) => SecondScreen(),
    },
    navigatorObservers: [ MyNavigatorObserver() ],
  ));
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
    );
  }
}
```

**Expected results:**

As of Flutter v1.12.13+hotfix.5, and as expected, the observer is notified of the routes pushed in logical order, as if navigating from the top to the tip of the tree, with the last call to `didPush` being for the deepest route:

```
[log] didPush route=/ previousRoute=null
[log] didPush route=/second previousRoute=/
```

**Actual results:**

As of Flutter 1.17.1, the calls are in the wrong (reverse) order, with the last call being for the top-level route:

```
[log] didPush route=/second previousRoute=/
[log] didPush route=/ previousRoute=null
```

<details>

```
[✓] Flutter: is fully installed. (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3)
[✓] Android Studio: is fully installed. (version 3.5)
[!] IntelliJ IDEA Ultimate Edition: is partially installed; more components are available. (version 2020.1.1)
[✓] Connected device: is fully installed. (1 available)
```

</details>

**Comment by TahaTesser** [comment]
```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           22.1s
[38;5;244m[log] [39;49mdidPush route=/second previousRoute=/
[38;5;244m[log] [39;49mdidPush route=/ previousRoute=null

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (7 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F   • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11  • B00B6F4E-B1CE-44F3-B81E-3EC6D639B008 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details>

**Comment by chunhtai** [comment]
The initial routes are added simultaneously, there should not be an order of which gets added first. I am thinking we are misusing the didpush for initial routes, maybe it should not be called at all for initial route because they are not `pushed`

Back to your question, may i know what is your use case? What goal are you trying to achieve when listening to the route push?

**Comment by matthewlloyd** [comment]
The existing API and semantics are clearly defined. Both the pushing and the order of the pushing are specified. I refer you to the documentation of `defaultGenerateInitialRoutes`: https://api.flutter.dev/flutter/widgets/Navigator/defaultGenerateInitialRoutes.html

"If this string contains any / characters, then the string is split on those characters and substrings from the start of the string up to each such character are, **in turn, used as routes to push.**

For example, if the route /stocks/HOOLI was used as the initialRoute, then **the Navigator would push the following routes on startup**: /, /stocks, /stocks/HOOLI. This enables deep linking while allowing the application to maintain a predictable route history."

In my case, I am updating other parts of the UI based on the current route. I'm using `didPush` to be notified of any and all route changes, including the initial route change. I rely on the most recent call to `didPush` to tell me what the current route is.

For all use cases, I would expect the sequence of calls to `didPush` to be an accurate reflection of the state of the navigation stack, such that I should be able to reliably reconstruct the stack just by monitoring calls to `NavigationObserver`. I also expect the value of `previousRoute` in a call to `didPush` to be equal to the value of `route` from the previous call (unless there was a pop or replace in between, of course).

**Comment by chunhtai** [comment]
We should update the document on that one. It should say add instead of push. The different between them are: `push` implies route is added with transition animation and `add` implies  route is added without transition animation. The initial routes are the latter.

The announcement order might be a tricky problem. Before the refactor you can only process one route at a time (even with popUntil or pushAndReplacementUntil is just calling remove/pop multiple times), but now we have the ability to modify the entire history at once using page API. In the such case, we cannot really determine which order is correct. One idea may be we also announce the didpush from the bottom to top-most route, while the pop announce from top-most route to bottom.

But either way using the didpush to track the top-most route might be dangerous as you can push a route in the middle of route history using the pages api.

**Comment by matthewlloyd** [comment]
I see, thanks for the information. I was not aware of the new way the stack could be modified, i.e. using `add`, nor was I aware of the new pages API. I admit the new logic while powerful seems confusing because it breaks away from the basic computer science concept of a LIFO stack, from which elements can only be pushed or popped. However I do see why the team has redesigned things this way (I just read the design doc from January).

The Navigator 2.0 refactoring was billed as a breaking change only for code that uses push, pushAndRemoveUntil, pushNamed, pushNamedAndRemoveUntil,  pushReplacement, or pushReplacementNamed with routes that have isInitialRoute set to true. It seems in reality it is a breaking change for any app that uses `initialRoute` and `NavigatorObserver.didPush/Pop`. If the team's intention is to keep the new logic as is, perhaps an email to `flutter-announce` would be a good idea? I am probably not the only developer whose app is going to be silently broken by this change when upgrading to `1.17`. The change caused my app to enter a state where the Settings tab got stuck in a nested route, and I was lucky to catch it during my release testing process.

I like your idea of announcing the pushes and pops in an order that corresponds with what one would normally expect from a stack.

All I really need is a way to be notified as to what the current route is. It seems it's no longer possible to determine that reliably using the existing methods in `NavigatorObserver`, so it would be great to have a new method or API provided for that (e.g. `NavigatorObserver.didChangeLeafRoute(Route route)`, `NavigatorObserver.didChangeRouteStack(List<Route> routes)` or similar).
