### ISSUE TITLE
MediaQuery is not working well with AppBar

### ISSUE THREAD

**Issue by abduqodirov** [flutter/flutter#57405]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Create a Scaffold screen
3. Add AppBar to the Scaffold
4. Add container as child of Scaffold
5. Set the Container's height to MediaQuery.of(context).size.height
6. Subtract AppBars height from MediaQuery.of(context).size.height ( MediaQuery.of(context).size.height - myAppBar.preferredSize.height )

And the Container is still higher than device's screen because of AppBar. If I remove AppBar Container's height is equal to device's screen height

I want to get all the heihgt of screen with subtracting AppBar height

And the Container is still higher than device's screen because of AppBar.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TaimoorHassan** [comment]
The container should fill up the empty space when there's no height parameter passed. 
Use the following in build method in a widget and see if it helps
`
Widget build(BuildContext context) {
    var screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
      appBar: AppBar(
        title: Text("Height Test"),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return Container(
            child: Center(child: Column(children: [
              Text("Screen Height" + screenHeight.toString()),
              Text("Container Height" + constraints.maxHeight.toString()),
              Text("Appbar Heigh" + (screenHeight -  constraints.maxHeight).toString() )
            ],),),
            color: Colors.teal,
          );
        }
      ),
    );
`

**Comment by TaimoorHassan** [comment]
![image](https://user-images.githubusercontent.com/8298536/82137089-47476400-982e-11ea-80d9-4aeb6d0d2035.png)

This is how it should look.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
