### ISSUE TITLE
DownloadComplete listener on Image.Network

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#5741]
Hello,

The Image.network constructor is really nice but I don't find methods to listen if the download of the image is running, is failed or is complete.

The idea, is to show a placeholder like a progressIndicator widget while the image is loading and then hide it and replace it by the image once it is loaded.

Maybe using a Stack can do the job? or is there any other way to do that?

I am using Android to test.

Thank you,

Vincent

**Comment by brnndnn** [comment]
+1. I'm also looking for this functionality for the Image.asset constructor.

**Comment by lequem** [comment]
I have implemented this feature and created a test filte but I have a problem for one of my test.
I cannot figure out how to send a correct httpResponse to let the image_decoder.dart file decode correctly the image.
I have tryed many things.

Here is the code of the test:

`testWidgets('network image listener, loading success', (WidgetTester tester) async {

    NetworkImageLoadingListenerMock listener = new NetworkImageLoadingListenerMock();

    var headers= {'charset': 'utf-8', 'content-type': 'image/jpeg'};

    // Override the http client to send expected response.
    http.Client.clientOverride = () {
      return new http.MockClient((http.BaseRequest request) {
        return new Future<http.Response>.value(
          new http.Response("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==",
           200, request: request, headers: headers)
        );
      });
    };

    await tester.pumpWidget(
      new MaterialApp(
        home: new Material(
          child: new Builder(
            builder: (BuildContext context) {
              return new Center(
                child: new Image.network('fake_url3', networkImageLoadingListener: listener)
              );
            }
          )
        )
      )
    );

    await (listener.waitLoadingSuccessOrFailed());
    expect(listener.imageloadingsuccess, true);
    expect(listener.imageloadingfailed, false);
  });`

Any idea?
Vincent

**Comment by sethladd** [comment]
First off, thanks! Second, is there a link to your PR?

**Comment by lequem** [comment]
No! because I would like to complete this last test before sending the pull request!

**Comment by sethladd** [comment]
@lequem fair enough :)

**Comment by lequem** [comment]
About that, if you have a suggestion concerning my problem...
maybe @Hixie will have one.

**Comment by Hixie** [comment]
We don't currently expose a simple API to do that. You can fake it yourself right now by getting an AssetImage or NetworkImage and fetching the same image with the same image configuration, and then using that future (it'll be the same actual future on the back end).

Can you clarify what your use cases are so that I can design a better solution for you?

**Comment by sethladd** [comment]
> The idea, is to show a placeholder like a progressIndicator widget while the image is loading and then hide it and replace it by the image once it is loaded.

@Hixie does that work for a use case? Or do we need more info?

**Comment by Hixie** [comment]
More detail would be nice. For example, how do you want to handle errors loading the image, how do you want to handle server pushed images, how do you want to handle changing the image source later, how do you want to handle the network going away then coming back, etc.

**Comment by sethladd** [comment]
Great, thanks @Hixie .

@lequem thanks for the additional info!

**Comment by lequem** [comment]
Actually, I have just added a NetworkImageLoadingListener insterface that is called with the method success or failed depending on if the loading success or failed.

The mecanism to display a placeholder will come later or will just be implemented by users.

I have tested the error case and the call to failed method.
I have a problem to test the call to the success method because the image string contained in the mocked httpResponse is not correctly decoded by the native method "decodeImageFromList"

**Comment by Hixie** [comment]
We frequently upload pull requests that are just not ready to check in, I wouldn't worry about it. :-)

**Comment by nanowang** [comment]
FYI, I'm using `image = new Image.memory(await http.readBytes(imageUrl));` which works like a charm.

**Comment by eseidelGoogle** [comment]
@Hixie we've gotten more requests from this.  Should we move this up to sooner?

**Comment by Hixie** [comment]
Sure.

**Comment by sethladd** [comment]
Is Image.network too much magic? Feels like there's a bit of functionality in there that isn't exposed to users. What if we didn't have that constructor, and instead just offered ways to fetch from network (http package) and some methods to decode those bytes into a byte buffer?  (which I think already exists?)

**Comment by Hixie** [comment]
We can't remove it, that would be an API-breaking change and we've announced API stability.

**Comment by sethladd** [comment]
@lequem for now, consider Image.network a "convenience method". If you need more control, you can use our lower layers of the stack. For example, the suggestion to use the http package with Image.memory from https://github.com/flutter/flutter/issues/5741#issuecomment-302416605 is a good one. By using the http package, you should be able to better control and listen to HTTP lifecycle.

Hope that helps!

(going to leave this bug open so we remember to document this)

**Comment by ride4sun** [comment]
I am using this infrastructure in the moment and wonder how the intention of the Flutter team is to support these use cases. I agree with @sethladd I would like to have more control of all these use cases to do exactly what I want. This is what I am doing know with some description in-between what I am miss (or did not find yet ;) ). Also I have a hard time to understand the intention of the Image API's holistically. The documentation is rather thin in this area.

Use Cases
1 Upload Image into the db and show a progress indicator and Placeholder widget when doing so.
   - This is done in my code below with the BusyOverlay Widget which show a overlay and a progress indicator based on the state message.mediaIsUploading.
2. Download Image from Network with a reasonable retry strategy and error handling
   - I use NetworkImageWithRetry which has a build in retry to who the placeholder which is unfortunately a Image and not just a widget, which would be much more flexible because I could show a progress indicator etc. 
3. Error handling when Network or other problems. 
   - Its build in which no callbacks (or I didn't find them). For me a feature missing.  How do I recover from the Network coming back e.g.

This is what I am using:
 ```
   //customize the image fetch strategy a little.
    final _imageFetchStrategy = const FetchStrategyBuilder(
      maxAttempts: 10,
      timeout: const Duration(seconds: 60),
    )
        .build();

    return new Container(
        child: new BusyOverlay(
            width: message.mediaSize.x.toDouble(),
            height: message.mediaSize.y.toDouble(),

            // TODO(joerg) handle `isMediaUpoadFailed`
            isLoading: message.mediaIsUploading,
            borderRadius: const BorderRadius.all(const Radius.circular(25.0)),
            child: message.mediaIsUploading
                ? null
                : new FadeInImage(
                    placeholder: const AssetImage('assets/look1119x236-32.png'),
                    image: new NetworkImageWithRetry( fetchStrategy: _imageFetchStrategy,
                      message.mediaUrl.toString(),
                    ))));
  }
```

**Comment by Hixie** [comment]
This area is something we plan to work on, but it's not a priority for the next few months (we're focusing more on improving our UI widgets, performance, accessibiilty, and other such core features).

**Comment by Hixie** [comment]
I'm going to close this issue in favour of https://github.com/flutter/flutter/issues/9676 which is also requesting general improvements in this area in much the same way.
