### ISSUE TITLE
Stepper UX - controls per step, eg last step should be "Save" button

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#57419]
It is unclear to me from the docs, how one could have the last step with a save button?
https://api.flutter.dev/flutter/material/Stepper/controlsBuilder.html

**Comment by cpboyd** [comment]
@giorgio79 If you keep track of the current step (which you'll probably need to do in order to proceed past the first step), then you should be able to change the text within `controlsBuilder` dependent upon what step you're on.
