### ISSUE TITLE
Error building apk or app bundle

### ISSUE THREAD

**Issue by bryanus1** [flutter/flutter#57417]
I'm working on an application, but at the moment build the app this fails.

Console show this error:

![Screen Shot 2020-05-17 at 0 12 21](https://user-images.githubusercontent.com/34760958/82136481-2d793300-97d4-11ea-9500-877c664be52d.png)
![Screen Shot 2020-05-17 at 0 12 28](https://user-images.githubusercontent.com/34760958/82136482-2fdb8d00-97d4-11ea-89e3-d94b91b3aa8d.png)

Flutter doctor -v is:

![Screen Shot 2020-05-17 at 0 14 47](https://user-images.githubusercontent.com/34760958/82136498-4b469800-97d4-11ea-8a97-e0e795f29d5e.png)

Thanks your collaboration.

**Comment by TaimoorHassan** [comment]
it looks as if the error is originating from ur assets. can you check if the asset files are valid PNG files.

**Comment by bryanus1** [comment]
But i use images that flutter generate when create project

**Comment by TaimoorHassan** [comment]
try opening those images in a image viewer and verify that they are not corrupted

**Comment by bryanus1** [comment]
Change all images I try build again and everything works!! Thanks @TaimoorHassan
