### ISSUE TITLE
scrollOffset keep growing

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#5742]
Hello,

I am using the LazyBlock widget to display a list with different size children.
I have put a ScrollListener on it.

When I scroll to the bottom and then I keep scrolling down, the list do not move because I have reached the end of the list but the scrollOffet value keep growing.
When I want to scroll to the top, the list start moving when I have reached the limit of the bottom.

To workaround the problem, I have set a listener on the scrollEnd Event and set max value of the bottom when the scrollOffset is over this limit.

Do not hesitate if you need further informations,

Vincent

**Comment by eseidelGoogle** [comment]
CC @HansMuller @Hixie

**Comment by HansMuller** [comment]
Scrollable responds to a press-drag-release gesture by updating the scrollOffset, even if that causes overscrolling. By default, when the release event occurs the scrollOffset is animated back to the scrollable's beginning or end.  This behavior is defined by an inherited widget called ScrollConfiguration.

Widgets like OverScrollIndicator (the Android overscroll "glow") and RefreshIndicator depend on overscrolling. 

If you really don't want the LazyBlock to overscroll, you can wrap it in a custom ScrollConfiguration. Roughly like this:

```
class MyScrollConfigurationDelegate extends ScrollConfigurationDelegate {
  @override
  TargetPlatform get platform => defaultTargetPlatform;

  // Default is OverscrollWhenScrollableBehavior
  @override
  ExtentScrollBehavior createScrollBehavior() => new BoundedBehavior(platform: platform);

  @override
  bool updateShouldNotify(ScrollConfigurationDelegate old) => false;
}

  new ScrollConfiguration(
    delegate: new MyScrollConfigurationDelegate(),
    child: new LazyBlock(
     ...
    )
  )
```

**Comment by lequem** [comment]
Ok, thank you for your answer!
