### ISSUE TITLE
Typo in cupertino datepicker error

### ISSUE THREAD

**Issue by cadeo111** [flutter/flutter#57426]
There is a type where **equal** is spelled **euqal** in an error for the cupertino date picker

[here](https://github.com/flutter/flutter/blob/8abf0a6d8c0d94fc5a6a6761025fcf035870d8c0/packages/flutter/lib/src/cupertino/date_picker.dart#L274)
```dart
274:      'initial date ${this.initialDateTime} is not greater than or euqal to minimumDate $minimumDate',
```
[and here](https://github.com/flutter/flutter/blob/8abf0a6d8c0d94fc5a6a6761025fcf035870d8c0/packages/flutter/lib/src/cupertino/date_picker.dart#L278)
```dart
278:      'initial date ${this.initialDateTime} is not less than or euqal to maximumDate $maximumDate',
```

**Comment by Hattomo** [comment]
I'll fix this.

**Comment by VladyslavBondarenko** [comment]
Closing in respect to https://github.com/flutter/flutter/pull/57487
