### ISSUE TITLE
[web]: Http requests throw XMLHttpRequest error

### ISSUE THREAD

**Issue by harshraj6982** [flutter/flutter#57421]
```bash
Error: XMLHttpRequest error.
    dart:sdk_internal 118163:30                           get current
packages/http/src/browser_client.dart.lib.js 212:124  <fn>
dart:sdk_internal 35540:58                            runUnary
dart:sdk_internal 30956:29                            handleValue
dart:sdk_internal 31466:49                            handleValueCallback
dart:sdk_internal 31498:17                            _propagateToListeners
dart:sdk_internal 31348:25                            [_complete]
dart:sdk_internal 35874:24                            _cancelAndValue
dart:sdk_internal 18161:17                            <fn>
dart:sdk_internal 4978:16                             _checkAndCall
dart:sdk_internal 4983:17                             dcall
dart:sdk_internal 99467:93                            <fn>
    at Object.createErrorWithStack (http://localhost:49173/dart_sdk.js:4786:12)
    at Object._rethrow (http://localhost:49173/dart_sdk.js:35900:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49173/dart_sdk.js:35896:13)
    at Object._microtaskLoop (http://localhost:49173/dart_sdk.js:35756:13)
    at _startMicrotaskLoop (http://localhost:49173/dart_sdk.js:35762:13)
```

Facing this issue on flutter web only, works fine on flutter mobile.

**Comment by PixelToast** [comment]
Check the debug console in your browser for more details on why the http request failed

**Comment by iapicca** [comment]
Hi @PixelToast
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by harshraj6982** [comment]
I solved the issue

**Comment by bimsina** [comment]
@harshraj6982 please provide info on how the issue was solved before closing the issue.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by bimsina** [comment]
Here is the code that I'm trying to run :
`Map<String, dynamic> body = {
            'client_secret': _clientSecret,
            'source': "print'Hello World!'",
            'lang': 'PYTHON',
          };
          http
              .post('https://api.hackerearth.com/v3/code/run',
                  body: jsonEncode(body))
              .then((value) => print(value))
              .catchError((error) => print(error));`

Here is the error :
`Error: XMLHttpRequest error.
    dart:sdk_internal 123890:30                           get current
packages/http/src/browser_client.dart.lib.js 212:124  <fn>
dart:sdk_internal 36953:58                            runUnary
dart:sdk_internal 32045:29                            handleValue
dart:sdk_internal 32592:49                            handleValueCallback
dart:sdk_internal 32630:17                            _propagateToListeners
dart:sdk_internal 32464:25                            [_complete]
dart:sdk_internal 37363:24                            _cancelAndValue
dart:sdk_internal 18428:17                            <fn>`

Here's the o/p to `flutter doctor -v`
`[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.19.0-2.0.pre.143 at C:\src\flutter
    • Framework revision 9d58a87066 (4 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\timsi\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including the following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        Windows 10 SDK (10.0.17763.0)

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\timsi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.264]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61`

**Comment by harshraj6982** [comment]
Just enable cors it will not throw this kind of error. I just forget to enable cors in my backend.

**Comment by Liam-Kim** [comment]
hello I have same issue with flutter web. Could you let me know the solution in detail~?

**Comment by harshraj6982** [comment]
> hello I have same issue with flutter web. Could you let me know the solution in detail~?

Which backend you are using?

**Comment by harshraj6982** [comment]
Then you should contact firebase support.

**Comment by mhunchojack** [comment]
I have cors enabled in django but still getting same error, please help

**Comment by abumasum** [comment]
> Just enable cors it will not throw this kind of error. I just forget to enable cors in my backend.

I have got the same problem..can you show me how to enable cors?

**Comment by suragch** [comment]
See this Q&A for some help in enabling CORS:

https://stackoverflow.com/questions/60191683/xmlhttprequest-error-in-flutter-web-enabling-cors-aws-api-gateway

**Comment by michaeldwu** [comment]
@suragch I'm experiencing the same problem as well. I've taken a look at the link but it doesn't seem to be helpful for non-AWS backends. I'm currently using Google Cloud Platform's Compute Engine on the server side and can't figure out how to enable CORS like @abumasum too. Would really appreciate any advice or help you can give. Thanks!

**Comment by mracipayam** [comment]
I am using Xampp , it's working on mobile platforms but the web giving me this error. I tried everything in this conversation's mentions still giving the same error.

**Comment by mracipayam** [comment]
I am getting the same error with php api so i add the php code these lines ;
` header('Access-Control-Allow-Origin: *');

    header('Access-Control-Allow-Methods: GET, POST');

    header("Access-Control-Allow-Headers: X-Requested-With");`
There is no more error.

**Comment by SittiphanSittisak** [comment]
> I am getting the same error with php api so i add the php code these lines ;
> 
> `header('Access-Control-Allow-Origin: *');`
> `header('Access-Control-Allow-Methods: GET, POST');`
> ` header("Access-Control-Allow-Headers: X-Requested-With");`
> 
> There is no more error.It is enables CORS. I don't know what that is but i am gonna read the manual.

#Fixed Thank you so much. Did you read the manual? I suspect it too.

**Comment by SittiphanSittisak** [comment]
It's simple for using API. Browsers HTTP is usually reserved access data from other domains. We call this CORS. So we can't use API without permission from this domain. If you are the host of this domain, you can set by following this https://enable-cors.org/server.html. I hope it can help you all.

**Comment by mracipayam** [comment]
> It's simple for using API. Browsers HTTP is usually reserved access data from other domains. We call this CORS. So we can't use API without permission from this domain. If you are the host of this domain, you can set by following this https://enable-cors.org/server.html. I hope it can help you all.

Oh thank you! Very useful link.

**Comment by bilguungt** [comment]
> I solved the issue

ho do you resolve it

**Comment by exeptionerror** [comment]
All Possible Solution added [[Solved] IN Flutter Web getting ‘XMLHttpRequest’ error while making HTTP call](https://fluttercorner.com/flutter-web-getting-xmlhttprequest-error-while-making-http-call/)

**Comment by mracipayam** [comment]
Thanks for sending me.

28 Haz 2021 Pzt 09:06 tarihinde exeptionerror ***@***.***>
şunu yazdı:

**Comment by glennmichaelmejias** [comment]
edit both files

etc/apache2/apache2.conf
etc/apache2/httpd.conf

and add this to the end

Header set Access-Control-Allow-Origin "*"
