### ISSUE TITLE
FontFamily.cpp/FontCollection.cpp crash in first Google Play version built with Futter v1.17.1

### ISSUE THREAD

**Issue by insin** [flutter/flutter#57436]
I recently pushed a small update to an app after upgrading to Flutter v1.17.1 and it's crashing on startup, but only in the version installed from Google Play.

When I build a release APK locally from the same code, Flutter version and `pubspec.lock`, it runs as expected on a real device.

These are the logs from `adb logcat` with my phone connected via USB on trying to run the Google Play version:

<details>
<summary>Crash logs</summary>
<pre>05-17 20:06:51.816  8213  8230 E flutter : [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
05-17 20:06:51.816  8213  8230 E flutter :
05-17 20:06:51.816  8213  8230 F flutter : [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
05-17 20:06:51.816  8213  8230 W libc    : check core file limit, limited=1
05-17 20:06:51.816  8213  8230 I libc    : Set DISDUMPABLE SUCCESS
05-17 20:06:51.817  8213  8230 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8230 (1.ui), pid 8213 (script.timerapp)
05-17 20:06:51.868   384  1322 E SPRDHWComposer: SPRD_SR SprdHWComposer2::GET_ACTIVE_CONFIG[470] *outConfig:0
05-17 20:06:51.872   740   762 I ActivityManager: Displayed jbscript.timerapp/.MainActivity: +451ms
05-17 20:06:51.877   384  1322 D         : Gralloc Register  w:720, h:1520, f:0x1, usage:0xb00, ui64Stamp:118959, sSize:4378624, line = 2106
05-17 20:06:51.890  8253  8253 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
05-17 20:06:51.891   536   536 I /system/bin/tombstoned: received crash request for pid 8230
05-17 20:06:51.894  8253  8253 I crash_dump64: performing dump of process 8213 (target tid = 8230)
05-17 20:06:51.911  8253  8253 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 20:06:51.911  8253  8253 F DEBUG   : Native Crash TIME: 21063613
05-17 20:06:51.911  8253  8253 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 20:06:51.911  8253  8253 F DEBUG   : Build fingerprint: &lt;redacted&gt;
05-17 20:06:51.911  8253  8253 F DEBUG   : Revision: '0'
05-17 20:06:51.912  8253  8253 F DEBUG   : ABI: 'arm64'
05-17 20:06:51.912  8253  8253 F DEBUG   : pid: 8213, tid: 8230, name: 1.ui  >>> jbscript.timerapp <<<
05-17 20:06:51.912  8253  8253 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-17 20:06:51.912  8253  8253 F DEBUG   : Abort message: '[FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
05-17 20:06:51.912  8253  8253 F DEBUG   : '
05-17 20:06:51.912  8253  8253 F DEBUG   :     x0  0000000000000000  x1  0000000000002026  x2  0000000000000006  x3  0000000000000008
05-17 20:06:51.912  8253  8253 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0080000000000000
05-17 20:06:51.912  8253  8253 F DEBUG   :     x8  0000000000000083  x9  7e2ba25637a35dd6  x10 0000000000000000  x11 fffffffc7ffffbdf
05-17 20:06:51.912  8253  8253 F DEBUG   :     x12 0000000000000001  x13 0000000000000008  x14 ffffffffffffffff  x15 000051ab26c3f16c
05-17 20:06:51.912  8253  8253 F DEBUG   :     x16 00000077ae52f2c8  x17 00000077ae46d0d0  x18 0000000000000001  x19 0000000000002015
05-17 20:06:51.912  8253  8253 F DEBUG   :     x20 0000000000002026  x21 00000077146502a8  x22 00000077298e4280  x23 000000772057b5c0
05-17 20:06:51.912  8253  8253 F DEBUG   :     x24 00000077298e429c  x25 00000077298e42a0  x26 00000077298e4300  x27 00000077298e42e8
05-17 20:06:51.912  8253  8253 F DEBUG   :     x28 0000000000000000  x29 0000007714650290
05-17 20:06:51.912  8253  8253 F DEBUG   :     sp  0000007714650250  lr  00000077ae461bfc  pc  00000077ae461c24
05-17 20:06:51.914  8253  8253 F DEBUG   :
05-17 20:06:51.914  8253  8253 F DEBUG   : backtrace:
05-17 20:06:51.914  8253  8253 F DEBUG   :     #00 pc 0000000000021c24  /system/lib64/libc.so (abort+116)
05-17 20:06:51.914  8253  8253 F DEBUG   :     #01 pc 0000000000761058  /data/app/jbscript.timerapp-7S1l-KIS4EF-d8omJeM0HQ==/split_config.arm64_v8a.apk (offset 0x742000)
</summary>
</details>

The Google Play version is here: https://play.google.com/store/apps/details?id=jbscript.timerapp

These are all the changes made since the previous release: https://github.com/insin/tabata_timer/compare/v1.3.1...v1.4.0

Searching for the error messages in the crash logs, previously suggested fixes have been:

- removing spaces from asset names
- removing custom fonts
- ensuring `uses-material-design: true` is present under the `flutter:` block in `pubspec.yaml`

None of these apply in this case - the app doesn't have any custom fonts, doesn't even specify any font families and `uses-material-design: true` is already there.

<details>
  <summary><code>flutter doctor -v</code> output</summary>
<pre>[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-AU)
    • Flutter version 1.17.1 at C:\Users\Jonny\Programs\flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jonny\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.45.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
</pre>
</details>

**Comment by mouadFahsi** [comment]
@insin Hi I had a similar error in my build using flutter 1.17. I fixed it by running flutter clean before building again

**Comment by insin** [comment]
Thanks @mouadFahsi, that did the trick 👍 

I'd just been manually deleting `build/` manually before creating bundles, which clearly isn't enough.

**Comment by fellow7000** [comment]
Yesterday I ran into this issue as well. Flutter clean resolved it. I think, it should be better documented. Thanks for posting.
