### ISSUE TITLE
Flutter Eating HDD Space - MacOS Catalina 10.15.4

### ISSUE THREAD

**Issue by Kemael** [flutter/flutter#57438]
Debugging Flutter apps under Android Studio or VS Code increases hidden space size on MacOS until the system runs out of space on the hard drive, crashing the operating system. The bug is present on the Stable and Master releases of Flutter regardless of the IDE used.

This issue is not present when debugging Android Apps using Java.

The approximate size increases at a speed of nearly 1 Gb per 15 seconds and is writing on the disk under the 'launchd' process.

**Comment by lucas-sesti** [comment]
Yeah, i facing this issue too... any updates? My flutter using 300/400gb generating in /private/var, after start flutter... i don't know why

**Comment by Kemael** [comment]
I've got some good news and some bad news.

Good news is that I have solved the issue and the launchd process has stopped appearing entirely.

Bad news is that I had to reinstall my entire OS with a full drive wipe in order to achieve this and I reinstalled MacOS 10.15.3. 

I'm still unsure why this issue happened in the first place and why it was linked with running Flutter and why it was IDE agnostic but whatever conflict there was with the system on MacOS it's now gone. I'll wait for MacOS 10.15.5 before upgrading again.

**Comment by 2math** [comment]
Same here on each build the I'm out of storage.
latest macOS , latest studio and flutter

**Comment by AndrGolubkov** [comment]
Similar problem

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale ru-RU)
    • Flutter version 1.17.3 at ...
    • Framework revision b041144f83 (2 недели назад), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at ...
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • SM J730FM • 5200ad99fecd84bb                         • android-arm • Android 9 (API 28)
    • DrePhone  • 1e44d25e58b9c50a9f6c4814dd582efd870bf2e9 • ios         • iOS 13.5.1
    • iPhone SE • 1A00DB2D-4833-4414-BE0B-E40516B765F4     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

• No issues found!
Process finished with exit code 0

**Comment by ozantepe** [comment]
Same problem with launchd, when I run the flutter app it starts writing tremendous data to "other" disk space over time until there is not enough disk space left..

After a cold restart I found "Recovered Files" folder in my bin with a size of 173gb of temp files related to simulator and iOS devices..

Flutter version: 1.17.3

**Comment by REDTOMIC** [comment]
How to fix that ?

**Comment by Kemael** [comment]
The only way for me to resolve the issue was to format my drive and reinstall the operating system.

Apparently user ozantepe has also resolved the issue but upgrading flutter to version 1.17.4.

Apart from these two methods there has been no other solution reported so far.

**Comment by psimondk** [comment]
Can confirm that the latest rendition of Flutter i.e. Flutter 1.20.4 • channel stable does **not** solve the problem.
2-3 GB disappear every time I run a debug session with the Android Simulator. Rebooting brings it back, but really - come on!

**Comment by psimondk** [comment]
df -h before doing some lightweight assorted flutter/android testing: 16.4 GB
df -h after having stopped debugging after approx. 4 restarts and 20 reloads: 3.1 GB

It doesn't matter whether testing on a physical device or the Android Emulator

Environment
Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.5 19F101, locale en-DK)
Android toolchain - develop for Android devices (Android SDK version 29.0.3)

Is anyone from the Flutter team even reading this?

**Comment by gregsheen** [comment]
My Mac storage also becomes very full after using flutter, xcode and android studio simulators for a while.  Currently my storage is as in the image. 

Does anyone know what large files related to flutter I can safely delete? 

<img width="583" alt="Screenshot 2020-11-19 at 21 29 53" src="https://user-images.githubusercontent.com/64927090/99726408-5ee9f880-2aae-11eb-9b61-3e13ce55f0d5.png">

**Comment by jessmensa** [comment]
Any one found solution to this issue yet ??

**Comment by Kemael** [comment]
Hi there,

The only “solution” found to this date, as mentioned in the abovementioned 18th of May 2020 post, was a complete reinstall of the operating system.  A clean install of MacOS was necessary for preventing this issue of appearing entirely.

Hope this will help anyway.

Cheers,

**Comment by vendz** [comment]
Same issue for me still persisting. No one from flutter team is reading this even though this issue is active for more than 1 year. 

Hats off to flutter team
