### ISSUE TITLE
android_intent 0.3.7+2 dose not support importing contact data

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#57431]
android_intent 0.3.7+2 dose not support importing contact data

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kw2019ltd** [comment]
flutter doctor -v will not help.

iam asking why android_intent 0.3.7+2  dose not support importing contact data could be feature request.

**Comment by kw2019ltd** [comment]
any update @TahaTesser

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
I think was wrong, this could be a new feature

**Comment by kw2019ltd** [comment]
@TahaTesser any update

**Comment by stuartmorgan** [comment]
Closing as `android_intent` is deprecated in favor of [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).
