### ISSUE TITLE
Fido U2F or Security Key Support

### ISSUE THREAD

**Issue by luckycreationsindia** [flutter/flutter#57434]
## Use case

There is password-less login features but one thing that is missing in flutter is U2F/Security Key Support.

If this feature (package) is added it will help many who wants to migrate from Android/iOS to Flutter based app.

I tried using webview but due to security issues it's not supported.

It's possible to write separate code for Android (Kotlin/Java) and iOS (Swift) with libraries available but that's a lot of work and testing and will need seperate code for web or other version of app too.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
