### ISSUE TITLE
Build AOT call

### ISSUE THREAD

**Issue by owenkealey** [flutter/flutter#57444]
Hi,

I was following the guide here to obfuscate my app https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code

but I could not find the "build aot" call in xcode_backend.sh
<img width="589" alt="Screen Shot 2020-05-17 at 2 28 44 PM" src="https://user-images.githubusercontent.com/26207512/82156748-1295d580-984b-11ea-9874-3edadcee8467.png">

I am on version 1.17 of flutter.

**Comment by owenselles** [comment]
As of flutter 1.16.2, the information you linked to is out of date. If you are using Flutter 1.16.2 or later, please refer to [Obfuscating Dart code](https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code) on flutter.dev.

**Comment by jonahwilliams** [comment]
The official docs for this feature are https://flutter.dev/docs/deployment/obfuscate
