### ISSUE TITLE
Highlight of FlatButton does not have rounded corners

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5745]
As per the [MD Spec](https://material.google.com/components/buttons.html#buttons-flat-buttons), the `FlatButton`'s highlight should have it's corners rounded. This happens when the `FlatButton` has a `color` though.

![screenshot_2016-09-06-08-54-26](https://cloud.githubusercontent.com/assets/4136413/18283518/821946f2-741a-11e6-88e1-efd2f55fe086.png)
(Notice how the **CANCEL** button's corners differ from **CONTINUE**.)

**Comment by shitb** [comment]
RaiseButton has this problem too.

**Comment by zoechi** [comment]
Did #19569 fix this? 
Is this still an issue in recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
