### ISSUE TITLE
Android SDK file is not found?

### ISSUE THREAD

**Issue by imbichitra** [flutter/flutter#57470]
Hi developer i am new to flutter and there is some problem in running flutter doctor and i got bellow error.
```
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\bpradhan\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\bpradhan\AppData\Local\Android\Sdk
    X Android SDK file not found: C:\Users\bpradhan\AppData\Local\Android\Sdk\build-tools\29.0.3\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
```` 

i also have android studio and all my android project work fine there is also Android sdk installed .
please help to solve this.

**Comment by iapicca** [comment]
Hi @imbichitra 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by imbichitra** [comment]
I do not get any Android SDK Tool(Obsolete) in my android SDK Manager
