### ISSUE TITLE
Divider should support more options like LinearGradient

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#57492]
## Use case

Having more color-full and beautiful dividers, which are always treated as "static-grey-lines".

## Proposal

The Divider() class now supports the parameter color:, but it would be cool if it could support linearGradients too like Containers with BoxDecorations.
But also, shadows with BoxShadow() and so on. 

Example: 
`Divider(
    linearGradient: LinearGradient(),
    shadow: BoxShadow(),
)`

**Comment by VladyslavBondarenko** [comment]
@nicolasvac 
Divider follows the [Material guidelines](https://material.io/components/dividers) for its default look. You can create a custom widget for your needs

**Comment by nicolasvac** [comment]
@VladyslavBondarenko Is the Divider component obligated to follow material guidelines?

**Comment by VladyslavBondarenko** [comment]
@nicolasvac I'm not sure how much it is obligated, this is why I didn't close the issue and labeled correspondingly

**Comment by Hixie** [comment]
Yeah, Material library widgets just follow the material spec. Creating a custom divider is pretty straight-forward though! Or you can just use Container. :-)
