### ISSUE TITLE
Back button in upper left is hard to register taps (target too small?)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#575]
On one of our demo apps, the upper left back arrow is fairly hard to tap. Sometimes I get it right, but enough time it's acting like the tap wasn't registered.

Is this a known issue with our back button?

**Comment by sethladd** [comment]
cc @Hixie @collinjackson

**Comment by abarth** [comment]
Known issue.  We could paper over it pretty easily, but the real fix is to add the radial reaction.  If it's annoying, let me know and I'll paper over it.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/issues/82 is the issue for the real fix.

**Comment by sethladd** [comment]
It blocks our "caveat-free demo" but otherwise not blocked. Let's go for the real fix.

**Comment by sethladd** [comment]
Thanks for the fix!!
