### ISSUE TITLE
IntelliJ IDEA 2020.1.1 can't detect installed flutter and dart plugins

### ISSUE THREAD

**Issue by ericchuawc** [flutter/flutter#57501]
I have installed both flutter and dart plugins on IntelliJ IDEA 2020.1.1

I can create flutter projects inside IntelliJ IDEA 2020.1.1

But why flutter doctor -v will show me that both plugins aren't installed. This has been some time and still seeing it.

<img width="561" alt="Screenshot 2020-05-19 at 12 08 40 AM" src="https://user-images.githubusercontent.com/24249779/82235378-33524e00-9965-11ea-8041-2ee8b8e32064.png">

any help? thanks

**Comment by Abdusin** [comment]
@ericchuawc  did u download '[flutter](https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.1-stable.zip)' and Extract the zip file and place the contained flutter in the desired installation location for the Flutter SDK (for example, C:\src\flutter) ? ?

**Comment by christopherfujino** [comment]
@ericchuawc Thank you for filing this! This issues has already been filed, however, as https://github.com/flutter/flutter/issues/54867. I will close this issue as a duplicate. Please follow that issue for updates.
