### ISSUE TITLE
DropDown should be lazy

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5750]

**Comment by eseidelGoogle** [comment]
Is this changed at all by the grand scrolling refactor?

**Comment by abarth** [comment]
It will become much easier to fix but it's a separate problem.

**Comment by Hixie** [comment]
A strong fix to this is technically impossible, since we are shrink-wrapping the width.
I'm going to close this until we have an explicit use case, so that we can examine the actual requirements and solve a real problem.
