### ISSUE TITLE
flutter build apk.

### ISSUE THREAD

**Issue by ronyland** [flutter/flutter#57539]
FAILURE: Build failed with an exception.                                                                                                        
* What went wrong:                                                      
Execution failed for task ':app:validateSigningRelease'.                
> Keystore file '/Users//Desktop//flutter/my_app/android/app/<location of the key store file, e.g. /Users//key.jks>' not found for signing config 'release'.

**Comment by ronyland** [comment]
You must remove the '<' chars, it's only as sample data.
storePassword=yourpasswordhere
keyPassword=yourkeypasswordhere
keyAlias=youralias
storeFile=/your/path/key.jks

**Comment by VladyslavBondarenko** [comment]
@ronyland 
closing as solved
