### ISSUE TITLE
[Url_launcher] run code after browser close

### ISSUE THREAD

**Issue by greedyRoach** [flutter/flutter#57536]
## Use case
The app opens a url where the user does something in the app back-server, so when the process is done, the user returns to the app and the library (url_launcher) triggers a listener telling the app that the browser was closed, then the app does an additional action, like refreshing a credential

## Proposal
```
//this code only runs before web page opens
await launch(url);
//this code only runs after the web page was CLOSED (and not immediately like the current behaviour)
```

**Comment by VladyslavBondarenko** [comment]
Hi @greedyRoach 
it works, is https://github.com/flutter/flutter/issues/47271 your case?

**Comment by greedyRoach** [comment]
@VladyslavBondarenko hello there

i don't know, maybe i'm doing something wrong, what i have in my code is (i'm doing the test on android by the way):

```
if (await canLaunch(url)) {
  print('launched 1');
  await launch(url);
  print('launched 2');
} else {
  throw 'Could not launch $url';
}
```

but what this prints is

<img width="224" alt="Captura de Pantalla 2020-05-19 a la(s) 7 02 14" src="https://user-images.githubusercontent.com/57685250/82324132-c0fe5f80-999e-11ea-9ac6-41235a3e6463.png">

and it does it immediately after the browser is open, it isn't even waiting for the browser to load the url, what i was expecting is the console printing

```
launched 1
``` 

and after the browser is CLOSED print

```
launched 2
``` 

i found a workaround but is quite cumbersome
Achieved this through adding a "lifecyclehandler" on my widget

```
WidgetsBinding.instance.addObserver(LifecycleEventHandler());
```

firing an event

```
class LifecycleEventHandler extends WidgetsBindingObserver {

  LifecycleEventHandler();

  @override
  Future<Null> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        eventBus.fire(UserGoogleIntegration());
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
    }
  }
}

```

and listening to the event, assuming that when the widget is resumed the user has closes the launched browser

```
eventBus.on<UserGoogleIntegration>().listen((event) {
  //Do this assuming the browser was recently closed
});
```

sorry for the english, not my mother language 😛

**Comment by VladyslavBondarenko** [comment]
@greedyRoach oh, I see, I didn't check that launch returns the value immediately, not after closing launched app

**Comment by Poomulus** [comment]
If you are still looking for a way to do this I would recommend implementing [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) interface and listen for widget state changes. This will let you know if your app is in the background or foreground. So you can use the resumed case to run code after your return from the browser.

```
class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  AppLifecycleState _notification; 
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch(state){
      case AppLifecycleState.resumed:
        print("app in resumed");
        break;
      case AppLifecycleState.inactive:
        print("app in inactive");
        break;
      case AppLifecycleState.paused:
        print("app in paused");
        break;
      case AppLifecycleState.detached:
        print("app in detached");
        break;
    }
  }

  @override
  initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    ...
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```

**Comment by fluttercorner1** [comment]
Here Is Full Tutorial With Source Code [How to open a web browser (URL) from Flutter code?
](https://fluttercorner.com/how-to-open-a-web-browser-url-from-flutter-code/) that might be helpful for you

**Comment by Bonchoisland12** [comment]
Yes I knew that I’m gonna having issue Sent from Mail for Windows 10 From: fluttercorner1Sent: Sunday, November 29, 2020 8:58 AMTo: flutter/flutterCc: SubscribedSubject: Re: [flutter/flutter] [Url_launcher] run code after browser close (#57536) Here Is Full Tutorial With Source Code How to open a web browser (URL) from Flutter code?that might be helpful for you—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fabricio-godoi** [comment]
If someone needs some side solution that does not depend on changing some screen files, it could be accomplished with the following code:

```dart
        await ul.launch(YOUR_URL);

        /// Wait until the browser closes
        await Future.delayed(Duration(milliseconds: 100));
        while (WidgetsBinding.instance?.lifecycleState != AppLifecycleState.resumed) {
          await Future.delayed(Duration(milliseconds: 100));
        }
```

This approach is almost the same as @Poomulus pointed out (which should be the right answer for most cases), but this can be more versatile.

**Comment by fabricio-godoi** [comment]
@icecandy You are completly correct about it. If the time is not well tuned, then it can miss the event as well. I needed a simple solution for a problem I was having with Android launching a URL for a short time, and that has done the trick.

It is nice to know that are some other packages to do that as well. =)

**Comment by johnystecker** [comment]
Hello, is this issue/proposal going to be fixed? Or do we have to implement this hackish-way to detect when user comes back?
Thank you

> If someone needs some side solution that does not depend on changing some screen files, it could be accomplished with the following code:
> 
> ```dart
>         await ul.launch(YOUR_URL);
> 
>         /// Wait until the browser closes
>         await Future.delayed(Duration(milliseconds: 100));
>         while (WidgetsBinding.instance?.lifecycleState != AppLifecycleState.resumed) {
>           await Future.delayed(Duration(milliseconds: 100));
>         }
> ```
> 
> This approach is almost the same as @Poomulus pointed out (which should be the right answer for most cases), but this can be more versatile.

**Comment by stuartmorgan** [comment]
The plugin has no access to information about what happens after the URL is handed off to the system so closing as infeasible.
