### ISSUE TITLE
Documentation for LazyBlock should explain the use cases for LazyBlockBuilder vs LazyBlockChildren

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5753]
What @Hixie told me in chat:

> if you have a finite smallish list such that the Widgets would fit fine in memory on a device, then the children one is fine
> the builder one is for when getting those widgets might itself be expensive enough that you want to avoid it

This would be useful to have in the [`LazyBlock`](https://docs.flutter.io/flutter/widgets/LazyBlock-class.html) API docs.

**Comment by Hixie** [comment]
All those classes are gone now.
