### ISSUE TITLE
[webview_flutter] ntroducing the webview plugin, my app cannot obtain microphone permissions through the web

### ISSUE THREAD

**Issue by zhou-zc** [flutter/flutter#57546]
I have configured microphone permissions in AndroidManifest.xml
` 
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
<uses-permission android:name="android.permission.RECORD_AUDIO" />
`

**Comment by zhou-zc** [comment]
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

**Comment by zhou-zc** [comment]
` <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" />`

**Comment by VladyslavBondarenko** [comment]
Hi @zhou-zc
follow up on https://github.com/flutter/flutter/issues/56871,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it
