### ISSUE TITLE
Splash screen changing size on app start

### ISSUE THREAD

**Issue by jgadjetx** [flutter/flutter#57544]
Splash screen image changes size on app start

## Steps to Reproduce

1. edit launch_background.xml under android/app/src/main/res/drawable, delete unwanted 
comments then change  line :

`android:src=”@drawable/image` to your desired slash screen image

**Expected results:** 
Expected to see a crystal clear splash screen without the  "jump" effect. 

**Actual results:** 
The screen has a jumping effect, seem like the image changes size as the System app bar re-appears.

`flutter doctor -v` 

```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.30], locale en-ZA)
    • Flutter version 1.17.1 at C:\sdk\flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Oh\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\Oh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @jgadjetx 
I can't see a jumping effect when running on `Android 9 (API 28)` with `stable 1.17.1`.
Could you check if it happens with android emulator / device with another version?
And could you attach the screen recording of the jumping effect?

**Comment by mukunda-kn** [comment]
Its happening in my emulator running Android v9. But on a physical device (lenovo vibe p1a42 Android v6) I get a blank screen.

**Comment by AndrewCPU** [comment]
@mukunda-kn If you mean black screen when you say blank it could be related to #57541

**Comment by mukunda-kn** [comment]
> @mukunda-kn If you mean black screen when you say blank it could be related to #57541 

Im not sure its related to the mentioned issue. Honestly I haven't tried the steps to reproduce #57541.

**Comment by jgadjetx** [comment]
> 
> 
> Hi @jgadjetx
> I can't see a jumping effect when running on `Android 9 (API 28)` with `stable 1.17.1`.
> Could you check if it happens with android emulator / device with another version?
> And could you attach the screen recording of the jumping effect?

https://youtu.be/8tUUkP-IRy4

**Comment by VladyslavBondarenko** [comment]
@jgadjetx 
does it help https://github.com/flutter/flutter/issues/47634#issuecomment-576943498?

**Comment by jgadjetx** [comment]
> @jgadjetx
> does it help [#47634 (comment)](https://github.com/flutter/flutter/issues/47634#issuecomment-576943498)?

Perfect, solved my issue

Thank you. Closing issue now
