### ISSUE TITLE
Standalone embedder initialization failed: Error determining current directory: Operation not permitted

### ISSUE THREAD

**Issue by kris1919** [flutter/flutter#57552]
## Steps to Reproduce
1.use xcode,command+B to build ios  ->   failed
2.use flutter build ios  -> success
3.use flutter run on ios devices -> success

**Actual results:** 

```
Standalone embedder initialization failed: Error determining current directory: Operation not permitted

building file list ... rsync: link_stat "/Users/../ios/Flutter/App.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/krisyuhao/dev/flutter
    • Framework revision e6b34c2b5c (2 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/krisyuhao/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @kris1919 
for what iOS version are you building? could you try to build for device with lower iOS version or to update xCode?
https://forums.developer.apple.com/thread/128200#403102

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/57554

**Comment by kris1919** [comment]
Hi @VladyslavBondarenko 

I updated xcode to the latest version and still have problems
iOS devide version  12.4.5
```
Standalone embedder initialization failed: Error determining current directory: Operation not permitted

Command PhaseScriptExecution failed with a nonzero exit code

```


command line to build is ok
```
flutter build ios --release
Automatically signing iOS for device deployment using specified development team in Xcode 
Running pod install...                                              8.0s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        36.3s
Xcode build done.                                           204.5s
```

**Comment by VladyslavBondarenko** [comment]
@kris1919 could you provide `flutter build ios --release --verbose`?

**Comment by kris1919** [comment]
macOS  Operation not permitted!
1.restart and long press cmd+R ,enter protected mode
2.open terminal :  csrutil disable
3.restart

**Comment by miskayapp** [comment]
> macOS Operation not permitted!
> 1.restart and long press cmd+R ,enter protected mode
> 2.open terminal : csrutil disable
> 3.restart

did this solve the your problem?

**Comment by Jay-Zhang** [comment]
I solve this issue by changing Access setting:
1. Go to Menu System Preferences -> Security & Privacy.
2.Choose the Privacy Tab.
3.Select Full Disk Access item in left list.
4.Select Xcode in right list.

**Comment by nehamallama** [comment]
> I solve this issue by changing Access setting:
> 
> 1. Go to Menu System Preferences -> Security & Privacy.
>    2.Choose the Privacy Tab.
>    3.Select Full Disk Access item in left list.
>    4.Select Xcode in right list.

you are the goat i spent at least 8 hours on this.... thank you times a million

**Comment by DeveloperIglobal** [comment]
> I solve this issue by changing Access setting:
> 
> 1. Go to Menu System Preferences -> Security & Privacy.
>    2.Choose the Privacy Tab.
>    3.Select Full Disk Access item in left list.
>    4.Select Xcode in right list.

this is work for me

**Comment by hkodes** [comment]
Easy way to Fix this:

1. Go to Menu System Preferences -> Security & Privacy.
2.Choose the Privacy Tab.
3.Select Full Disk Access item in left list.
4.Select Xcode in right list.
