### ISSUE TITLE
Android build size is too large when Gradle upgraded to 3.6.3

### ISSUE THREAD

**Issue by tolg** [flutter/flutter#57550]
When I upgrade Gradle to 3.6.3 from 3.5.0，the build size of Android APK output file is up to 20.5MB. Before upgrade, it's only 8.4MB.
I use the "Analyze APK" tool to check the package detail:
In the APK file build by Gradle 3.6.3, libapp.so is size of 11.3MB, and libflutter.so is size of 8.4MB; 
In the APK file build by Gradle 3.5.0, libapp.so is size of 3.9MB, and libflutter.so is size of 3.7MB.
It's look like a Flutter problem. Or is there some config can reduce the build size?

Below is outputs of flutter doctor -v:

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/dongchao/development/flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dongchao/Library/Android/sdk
    • Platform android-R, build-tools 28.0.3
    • ANDROID_HOME = /Users/dongchao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • MI 8 SE • 1d2728c5 • android-arm64 • Android 9 (API 28)

**Comment by jason-simmons** [comment]
Tried to reproduce this with the current master but did not see a difference.

I build a Flutter default template app using Android Gradle plugin version 3.5.0 and with version 3.6.3.  Both builds produced similar sizes for the APK and the libflutter.so/libapp.so binaries.

**Comment by jonahwilliams** [comment]
Without a way to reproduce the issue on our end there is nothing for us to do here. I'm closing the issue for now, but feel free to re-open if you can provide a [minimal reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)
