### ISSUE TITLE
How to keep dart class name when i use flutter build apk --obfuscate?

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#57559]
How to keep class name when i use flutter build apk --obfuscate?

In flutter project, i use page runtimeType as route name!

**Comment by TahaTesser** [comment]
Hi @v7lin 
Please check [Obfuscating Dart code
](https://flutter.dev/docs/deployment/obfuscate#obfuscating-your-app) and [Obfuscating Dart Code for Android ](https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by v7lin** [comment]
> Hi @v7lin
> Please check [Obfuscating Dart code ](https://flutter.dev/docs/deployment/obfuscate#obfuscating-your-app) and [Obfuscating Dart Code for Android ](https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code)
> 
> Closing, as this isn't an issue with Flutter itself,
> if you disagree please write in the comments and I will reopen it
> Thank you

keep dart class, not keep java class

**Comment by a27919478** [comment]
I also have such problems, such as some dart bean conversion problems.
