### ISSUE TITLE
Allow Xcode archive builds to be run in Debug and Profile build mode for testing

### ISSUE THREAD

**Issue by mumenma** [flutter/flutter#57557]
We connected the Flutter module in native iOS App, and entered the test phase after the completion of development. 
In the test phase, we provide the  archive debug App for the tester with continuous integration, and provide some unique functions.
However, we found an error "Flutter archive builds must be run in Release mode". 
We want to know the reason .

**Comment by jmagman** [comment]
Developers archiving for App Store submission hit SO many issues with accidentally submitting a Debug version, which crashes on launch:
https://github.com/flutter/flutter/issues/12086
https://github.com/flutter/flutter/issues/37850
https://github.com/flutter/flutter/issues?q=label%3Aplatform-ios+label%3Atool+white+screen+is%3Aclosed

Which of course means your legitimate QA use case isn't possible, even though you know what you're doing.

I believe if you delete these lines from `<Flutter-SDJ>/packages/flutter_tools/bin/xcode_backend.sh` it may just work?
https://github.com/flutter/flutter/blob/bcc42901ad6bb3ec644be225b5f9cd998852e0ef/packages/flutter_tools/bin/xcode_backend.sh#L90-L101

Obviously editing Flutter out from under it isn't ideal.  I can't think of a good way from within Xcode to confirm "Are you SURE you want to archive in Debug?!"

**Comment by mumenma** [comment]
@jmagman 
Developers often use debug for develop. In my opinion, apps should not crash in debug with either Build or archive , we should find the crash reason, rather than close archive in debug. so we should Allow Xcode archive builds to be run in Debug and Profile build mode for testing.

**Comment by jmagman** [comment]
@mumenma I agree there should be a way.  I'm hoping we've fixed enough bugs related to the "accidental" debug archives that we can remove that check and `-1` exit.
