### ISSUE TITLE
[0x7FFB70BF6740] ANOMALY: meaningless REX prefix used

### ISSUE THREAD

**Issue by s3hengwu** [flutter/flutter#57565]
C:\src\flutter\bin\flutter.bat --no-color packages get
[0x7FFB70BF6740] ANOMALY: meaningless REX prefix used

**Comment by TahaTesser** [comment]
Hi @s3hengwu 
Please check this  [comment](https://github.com/flutter/flutter/issues/52645#issuecomment-602840321)
Please create an [issue against pub](https://github.com/dart-lang/pub/issues/new/choose) so they can take a look.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
