### ISSUE TITLE
Flutter iOS build deletes XCode base configuration reference

### ISSUE THREAD

**Issue by devjeff** [flutter/flutter#57567]
Flutter version: 1.17.1
XCode version: 11.4

## Steps to Reproduce
1. Open a Flutter application in Xcode on a macOS system, navigate to "Runner -> Info -> Configurations" and verify that the Debug and Release configurations have a corresponding base configuration set (Debug.xconfig and Release.xconfig), as displayed on the following screenshot:
![config_present](https://user-images.githubusercontent.com/49228590/82305589-1d24ac00-99be-11ea-945a-43677f28ede9.png)
2. Open the directory of a Flutter application using the terminal and execute the command "flutter build ios".
3. The file "project.pbxproj" gets modified by the Flutter build:
![project-file-diff](https://user-images.githubusercontent.com/49228590/82305702-46453c80-99be-11ea-9ab8-4118cc1684d4.png)
4. The base configuration reference is removed. If you look at the configuration in XCode now, you will see the following:
![config_deleted](https://user-images.githubusercontent.com/49228590/82305841-7ee51600-99be-11ea-88c1-96a9c328a0c1.png)
5. This leads to the problem that the version and build number fields are empty, as they are usually accessed via variables from the base configuration (which includes the Generated.xconfig file with the actual values):
![version-build-empty](https://user-images.githubusercontent.com/49228590/82306152-f5821380-99be-11ea-9630-4da20d91a024.png)

This behaviour prevents a successful startup of the app. With Flutter 1.12.13 everything works fine.

**Expected results:**
The Debug and Release base configurations shouldn't be touched by the Flutter build.

**Actual results:**
The Debug and Release base configurations are removed by the Flutter build.

**Comment by jmagman** [comment]
This was done intentionally with https://github.com/flutter/flutter/pull/54691.  The Runner project should have never had a base configuration, only the Target.  Additional targets (watch app, notifications, frameworks, etc) incorrectly inherited Flutter-intended build settings from the project.  The Target's base configuration should be Debug.xcconfig/Release.xcconfig, not Pod-Runner.debug as in your screen shot.  
![Screen Shot 2020-05-19 at 11 22 19 AM](https://user-images.githubusercontent.com/682784/82363702-0b91d300-99c3-11ea-8993-40e80018ee3e.png)


Did you change that manually at some point?  I don't think CocoaPods would re-set that and the default `flutter create` template before that migration was using Debug.xcconfig, etc.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/54769

**Comment by devjeff** [comment]
Hey, indeed this was the problem. Thank you very much for the references. I assume, that I manually changed the configuration by accident at some point.
