### ISSUE TITLE
VS Code IDE improvements

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#57573]
## 1. Improve Outline display in VS Code (add elements preview).
That's how outline looks in VS Code
![image](https://user-images.githubusercontent.com/12999702/82323112-42c2ad00-99e0-11ea-86bd-43c82b495cfa.png)
It's really hard to navigate here. You can't figure out: "What an icon? What a text?"
Much better how it looks in Android Studio:
![image](https://user-images.githubusercontent.com/12999702/82323319-8e755680-99e0-11ea-89f6-97672355b66f.png)

## 2. Add a "ladder" hierarchy display in editor
VS Code piece of code:
![image](https://user-images.githubusercontent.com/12999702/82323428-b49af680-99e0-11ea-8e9f-9d993a8560a0.png)
You can easily get lost here.

Android Studio piece of code:
![image](https://user-images.githubusercontent.com/12999702/82323476-c7adc680-99e0-11ea-871e-f9048835d38d.png)
Here is much easier to track the elements hierarchy.

Only because of these two features I'm stick to Android Studio despite it's heavier and overloaded with unneeded features.

**Comment by kunit1** [comment]
The second feature is already implemented in VS Code. You have to enable it in the plugin settings. Also, I believe the correct location for VS Code related issues is [https://github.com/Dart-Code/Dart-Code](DartCode)

**Comment by subzero911** [comment]
> The second feature is already implemented in VS Code. You have to enable it in the plugin settings. Also, I believe the correct location for VS Code related issues is [DartCode](https://github.com/Dart-Code/Dart-Code)

You're right, there is 'Preview Flutter UI Guides' setting I didn't know.
Still remains an issue about the first feature nevertheless.

**Comment by TahaTesser** [comment]
Hi @subzero911 
following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter)
the correct way to address the problem
is to open an issue on the dedicated [GitHub](https://github.com/Dart-Code/Dart-Code/issues)
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it. 
Thank you for your understanding
