### ISSUE TITLE
how can add customer font in webview

### ISSUE THREAD

**Issue by FeelSunshine** [flutter/flutter#57575]
some html has some customer fonts .
how can I add these customer fonts in webview.
I used css @font-face and put .ttf file in assets ,but can not find this .ttf file path ,it is not work.

**Comment by raslan1994** [comment]
I had a same scenario, my approach was

1. Get `Font` / `Image` data as `ByteData`
2. Make it as `Uri`
3. Set it on html (generate an html on the fly)

Hope following code snippet helps, make sure you have mentioned the right `mime type` when loading the font / image.
`Images` and `fonts` can’t be directly encoded in `utf-8` / `String` format. So we read as `ByteData` and make a `Uri` out of it.

```dart
String getFontUri(ByteData data, String mime) {
  final buffer = data.buffer;
  return Uri.dataFromBytes(
          buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
          mimeType: mime)
      .toString();
}

Future<String> addFontToHtml(
    String htmlContent, String fontAssetPath, String fontMime) async {
  final fontData = await rootBundle.load(fontAssetPath);
  final fontUri = getFontUri(fontData, fontMime).toString();
  final fontCss =
      '@font-face { font-family: customFont; src: url($fontUri); } * { font-family: customFont; }';
  return '<style>$fontCss</style>$htmlContent';
}

//generating html on the fly
String completeHtml = await addFontToHtml("<h1>Hello world </h1>",
    "assets/fonts/HKGrotesk/HKGrotesk-Regular.otf", "font/opentype");

//loading as Uri
Uri htmlUri = Uri.dataFromString(completeHtml,
        mimeType: 'text/html', encoding: Encoding.getByName('utf-8'))
    .toString();

//set it to web view when it ready
webController.loadUrl(htmlUri);

```

**Comment by FeelSunshine** [comment]
> 
> 
> I had a same scenario, my approach was
> 
>     1. Get `Font` / `Image` data as `ByteData`
> 
>     2. Make it as `Uri`
> 
>     3. Set it on html (generate an html on the fly)
> 
> 
> Hope following code snippet helps, make sure you have mentioned the right `mime type` when loading the font / image.
> `Images` and `fonts` can’t be directly encoded in `utf-8` / `String` format. So we read as `ByteData` and make a `Uri` out of it.
> 
> ```dart
> String getFontUri(ByteData data, String mime) {
>   final buffer = data.buffer;
>   return Uri.dataFromBytes(
>           buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
>           mimeType: mime)
>       .toString();
> }
> 
> Future<String> addFontToHtml(
>     String htmlContent, String fontAssetPath, String fontMime) async {
>   final fontData = await rootBundle.load(fontAssetPath);
>   final fontUri = getFontUri(fontData, fontMime).toString();
>   final fontCss =
>       '@font-face { font-family: customFont; src: url($fontUri); } * { font-family: customFont; }';
>   return '<style>$fontCss</style>$htmlContent';
> }
> 
> //generating html on the fly
> String completeHtml = await addFontToHtml("<h1>Hello world </h1>",
>     "assets/fonts/HKGrotesk/HKGrotesk-Regular.otf", "font/opentype");
> 
> //loading as Uri
> Uri htmlUri = Uri.dataFromString(completeHtml,
>         mimeType: 'text/html', encoding: Encoding.getByName('utf-8'))
>     .toString();
> 
> //set it to web view when it ready
> webController.loadUrl(htmlUri);
> ```



> 
> 
> I had a same scenario, my approach was
> 
>     1. Get `Font` / `Image` data as `ByteData`
> 
>     2. Make it as `Uri`
> 
>     3. Set it on html (generate an html on the fly)
> 
> 
> Hope following code snippet helps, make sure you have mentioned the right `mime type` when loading the font / image.
> `Images` and `fonts` can’t be directly encoded in `utf-8` / `String` format. So we read as `ByteData` and make a `Uri` out of it.
> 
> ```dart
> String getFontUri(ByteData data, String mime) {
>   final buffer = data.buffer;
>   return Uri.dataFromBytes(
>           buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
>           mimeType: mime)
>       .toString();
> }
> 
> Future<String> addFontToHtml(
>     String htmlContent, String fontAssetPath, String fontMime) async {
>   final fontData = await rootBundle.load(fontAssetPath);
>   final fontUri = getFontUri(fontData, fontMime).toString();
>   final fontCss =
>       '@font-face { font-family: customFont; src: url($fontUri); } * { font-family: customFont; }';
>   return '<style>$fontCss</style>$htmlContent';
> }
> 
> //generating html on the fly
> String completeHtml = await addFontToHtml("<h1>Hello world </h1>",
>     "assets/fonts/HKGrotesk/HKGrotesk-Regular.otf", "font/opentype");
> 
> //loading as Uri
> Uri htmlUri = Uri.dataFromString(completeHtml,
>         mimeType: 'text/html', encoding: Encoding.getByName('utf-8'))
>     .toString();
> 
> //set it to web view when it ready
> webController.loadUrl(htmlUri);
> ```

thank you for your reply

**Comment by rdunlocked18** [comment]
Hello can anyone tell me this thing ! i have marked an issue in my repo !  in Android Everything Works fine but in IOS things dont seem to be working . The data Being Parssed is in Hindi Unicode but i not parsing Properly colors and everything is but not actual HINDI content . Do i need to use Custom Font if Platform iOS . i have attached Link to Issue  @FeelSunshine @raslan1994 ! 


https://github.com/rdunlocked18/PrayasAcademyAp/issues/1
