### ISSUE TITLE
new_gallery__transition_perf worst_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#57586]
https://github.com/flutter/flutter/pull/57402 looks like the culprit.
![Screen Shot 2020-05-19 at 8 41 26 AM](https://user-images.githubusercontent.com/1435716/82347500-8b607300-99ac-11ea-9ea6-837e99202c13.png)

Before https://github.com/flutter/flutter/pull/57402, the benchmark is at ~230ms

**Comment by kf6gpe** [comment]
May be related to https://github.com/flutter/flutter/issues/57585.

**Comment by iskakaushik** [comment]
assigning to myself to bisect and identify the culprit.

**Comment by jason-simmons** [comment]
Bisected this on a Moto G4 and found that this started with https://github.com/google/skia/commit/11ad4ccfd421b19835e430ba5f9ac81c89674ae2 (similar to https://github.com/flutter/flutter/issues/57585)

**Comment by iskakaushik** [comment]
@bsalomon looks like this issue is a result of the same patch. This isn't a benchmark specialized for transitions like https://github.com/flutter/flutter/issues/57585 and represents a more real life scenario.

**Comment by bsalomon** [comment]
What's the command line for running this one? I think the closest device I have at my disposal right now is a Nexus 5, so not very close. I tried this:
`../../bin/cache/dart-sdk/bin/dart bin/run.dart --local-engine-src-path /home/bsalomon/src/engine/src/ --local-engine android_profile -t new_gallery__transition_perf`

and got the attached output. I saw the app launch and go through a bunch of screens but it doesn't seem like it produced the stats.
[output.txt](https://github.com/flutter/flutter/files/4664237/output.txt)

**Comment by jason-simmons** [comment]
This benchmark is flaky.  When I ran it I often saw the same error shown in your log:
`VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005`

If you run it repeatedly it should eventually run to completion and produce results.  I don't know if anyone has investigated why this benchmark script is unreliable.

**Comment by mehmetf** [comment]
Could we please get a status update for this?

**Comment by bsalomon** [comment]
I believe the performance impact is due to fixing a bug where we one of the passes in the separable blur filter wasn't doing as much work as it should have. However, I believe there is a possible optimization in the blur code that could more than offset this performance regression. It may take a couple of days to land this in Skia, though.

**Comment by kf6gpe** [comment]
@bsalomon Just checking --- has this landed in Skia yet? Thanks!

**Comment by bsalomon** [comment]
I have a WIP CL that should reduce the number of passes when downscaling
the blur input:
https://skia-review.googlesource.com/c/skia/+/292079

Hopefully will land today (and then has to roll into flutter)

**Comment by bsalomon** [comment]
It seems that the change has rolled into the engine, and the latest benchmark runs include it in their engine but performance hasn't been restored. I'll continue to investigate.

**Comment by kf6gpe** [comment]
After speaking with @bsalomon and @pcsosinski, downgrading to a `P3`, as we'd really like this, but it's not blocking the roll or a specific customer. It sounds like it may be two issues at play: a known increase in execution time due to a bug fix (originally the method under test was not correctly doing things and taking less time) and possibly another regression or room for a speedup to win back some of the performance lost.

**Comment by iskakaushik** [comment]
Given that, i'm not actively looking at this. Assigning to Brian.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/commit/cd7dfd0a0a60233de737cee8008fe4463acb6785 should help with the flakiness

**Comment by bsalomon** [comment]
Performance has improved but I can't tell if it's back to where it was or not. It's now at about 333ms. It looks like it was 384 when the bug was filed. What was it before the regression?

**Comment by kf6gpe** [comment]
Goal was 216ms, but it was weighing in at about 250ms. So we've still got a ways to go if we want to win back what we've lost. Knowing what I know from my chat with @bsalomon, I'm not sure how much more we'll get back here. Feel free to assign this back to me if rebaslining is the appropriate course of action here. Thanks!

**Comment by kf6gpe** [comment]
Any update on any further wins here, @bsalomon and @liyuqian? Should we rebaseline?

**Comment by liyuqian** [comment]
I think we should always rebaseline (I've just done it). That way, if a new regression occurs, we'll see a green-to-red transition in our dashboard again to notify us opening a new issue.

For this specific issue, I modified the description to clarify that before the regression of https://github.com/flutter/flutter/pull/57402 (which includes https://github.com/google/skia/commit/11ad4ccfd421b19835e430ba5f9ac81c89674ae2), the benchmark is at ~230 ms. @bsalomon : is there ongoing work to bring it back to that level?

**Comment by kf6gpe** [comment]
Rebaselined.

**Comment by kf6gpe** [comment]
Moreover, this has nearly settled at the old values, so I'll close this. @bsalomon feel free to comment and we can reopen as needed.

**Comment by liyuqian** [comment]
@kf6gpe : I think the old value is 230ms (before May 15th) while it is 330ms now?
