### ISSUE TITLE
backdrop_filter_perf__timeline_summary 99th_percentile_vsync_transitions_missed regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#57585]
Very clear signal at engine roll in https://github.com/flutter/flutter/pull/57402.
![Screen Shot 2020-05-19 at 8 38 49 AM](https://user-images.githubusercontent.com/1435716/82347184-2e64bd00-99ac-11ea-9a9e-a87010efdbb0.png)

**Comment by jason-simmons** [comment]
This changed with https://github.com/flutter/engine/commit/2494d1ca70750864d00d5fc1d79f53d20d1a7306

@iskakaushik

**Comment by iskakaushik** [comment]
@jason-simmons I don't think its that commit, since the original changed landed and got reverted in a narrow window, so any speedup we saw with that change should've been reverted too. I'll run a bisect to identify the culprit.

**Comment by iskakaushik** [comment]
assigning to myself to bisect and identify the culprit.

**Comment by iskakaushik** [comment]
![image](https://user-images.githubusercontent.com/1006071/82393316-e02ada80-99fa-11ea-9d1d-5a2a8ee44842.png)

Based on this the revert did make the performance worse, but I'd have expected it to go back to the baseline, but it looks like we've got worse.

**Comment by jason-simmons** [comment]
This benchmark also appears to be affected by https://github.com/google/skia/commit/11ad4ccfd421b19835e430ba5f9ac81c89674ae2 (which makes sense given that the benchmark involves blur filters)

@bsalomon @flar

**Comment by bsalomon** [comment]
I'll see if I can do anything about it. The old blur code was unfortunately cheating a bit in some cases and just not doing as much blurring work as it should have. That said I do have some pending perf improvements for some blur scenarios. So it may or may not be recoverable.

The title of that change is confusing. That was the third time the change landed (and finally stuck).

It looks like it briefly got faster before it got worse. Any idea what's happening there?

**Comment by jason-simmons** [comment]
This metric improved when https://github.com/flutter/engine/commit/2cdbc7f92793125d9312138877c05af6ad708683 landed.  The improvement was lost when that was reverted (https://github.com/flutter/engine/commit/2494d1ca70750864d00d5fc1d79f53d20d1a7306)

**Comment by bsalomon** [comment]
Ok so probably totally orthogonal to Skia blur changes.

**Comment by iskakaushik** [comment]
@bsalomon Once the change that @jason-simmons mentioned got reverted, we noticed that the performance didn't regress back to baseline but it regressed more than expected (as you see in the graph linked [here](https://github.com/flutter/flutter/issues/57585#issuecomment-631171882)). I think @jason-simmons suspects that this is because of the blur change in https://github.com/google/skia/commit/11ad4ccfd421b19835e430ba5f9ac81c89674ae2.

**Comment by bsalomon** [comment]
Thanks. I'm looking into whether the perf can be recovered without reintroducing the bug this fixed. I'm able to run the test on a device with my debug engine.

`flutter drive --local-engine-src-path /home/bsalomon/src/engine/src/ --local-engine=android_debug_arm64 test_driver/backdrop_filter_perf.dart`

Do I make a `--runtime-mode=profile` build and then run `flutter drive` with the `--profile` option to get the benchmark stats?

**Comment by bsalomon** [comment]
Both the old code and the new code will shrink the source of the blur if the blur sigma would produce a discrete kernel larger than is supported by the Gaussian blur shader. Both will perform the blur with a smaller sigma at the reduced src size and then blow that back up. The old code always reduced by some power of two. The new code reduces to approximately the largest size that is supported by the shader. That is probably a significant portion of the performance difference. We can probably go back to the old sizing decision with a little quality reduction compared to the current code.

**Comment by jason-simmons** [comment]
Do a `--runtime-mode=profile` build and then run the benchmark script with the `--local-engine` flag:
```
cd dev/devicelab
../../bin/cache/dart-sdk/bin/dart bin/run.dart --local-engine android_profile -t backdrop_filter_perf__timeline_summary
```

**Comment by iskakaushik** [comment]
For context, I've added this benchmark primarily to test the layer tree pipeline changes per: go/flutter-pipeline-improvements.

Given that we are seeing problems only with kernel sizes larger than the shader and that this benchmarks intent wasn't primarily to track blur performance. I'm okay with re-baselining this.

Removing the TODAY label while we figure out the next steps here.

**Comment by kf6gpe** [comment]
@iskakaushik any update on your investigation here? Thanks!

**Comment by liyuqian** [comment]
https://github.com/flutter/engine/pull/18901 should have been rolled but later reverted. @iskakaushik : is the July milestone still accurate considering this?

**Comment by iskakaushik** [comment]
@liyuqian , thanks for flagging this, i'll be assigning a conservative milestone this time.

**Comment by kf6gpe** [comment]
This has since gone green. Closing.

**Comment by flar** [comment]
It seems to be doing much better after https://github.com/flutter/flutter/commit/f379fbb7580eb050e96e26b8f24843d21d6bd803
