### ISSUE TITLE
Access to the path '..\flutter\bin\cache\dart-sdk' is denied

### ISSUE THREAD

**Issue by mrsahibsingh** [flutter/flutter#57580]
## Steps to Reproduce

1. Take pull of the latest stage branch.
2. Execute flutter doctor

## Logs

![Stage branch logs](https://user-images.githubusercontent.com/64500237/82338522-9f3ac200-9a0a-11ea-89a7-96110e2feba0.PNG)

![Error on Stage branch latest pull](https://user-images.githubusercontent.com/64500237/82338524-a06bef00-9a0a-11ea-8106-9a2a4c7471ff.PNG)

Last commit details: commit f7a6a7906be96d2288f5d63a5a54c515a6e987fe (HEAD -> stable, tag: 1.17.1, origin/stable, origin/flutter-1.17-candidate.3)
Author: Patrick Sosinski <sosinski@google.com>
Date:   Tue May 12 18:39:00 2020 -0700

**Comment by VladyslavBondarenko** [comment]
@mrsahibsingh 
Access denied. Try to install flutter in the directory that doesn't require privileges - not in the Program files. 
https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk
This should help, closing

**Comment by mrsahibsingh** [comment]
> @mrsahibsingh
> Access denied. Try to install flutter in the directory that doesn't require privileges - not in the Program files.
> https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk
> This should help, closing

Flutter is already installed and I'm able to use it with my head at commit 28c00980a
But when I take the latest pull and try to build It, It throws above error.

P.S -  The user have full access of installed directory.

**Comment by VladyslavBondarenko** [comment]
@mrsahibsingh 
if you are going to have flutter in Program Files - then grant needed files with needed permissions after pull

**Comment by mrsahibsingh** [comment]
This is just a drive name "Program File". My windows is installed in C drive, I've created a separate folder to store flutter project. Full Permission provide after latest pull, still facing same issue.

I've also tried reinstalling flutter sdk but still facing the same issue.

**Comment by jonahwilliams** [comment]
Whether or not the folder is the original program files, the root of any drive on windows will have access protection on it. Please install flutter to a user controlled directory such as documents.

**Comment by mrsahibsingh** [comment]
I've reinstalled flutter in root drive. 
My android device is connected and the SDK is also installed.
My whole setup was up and running, I just installed flutter in root directory and updated the environment variable path to the root directory flutter project location.
![flutter_stage_error](https://user-images.githubusercontent.com/17560961/82833653-41135080-9edc-11ea-9a6b-eb90f5650cb7.PNG)

I'm not sure If my issue and [this issue](https://github.com/flutter/flutter/issues/51712) are the same or not.

I tried all the solutions on StackOverflow related to this issue but still couldn't resolve this.

**Comment by M1Joe** [comment]
@VladyslavBondarenko  @jonahwilliams I'm experiencing the same issue, despite never having a problem upgrading previously.

**Comment by mrsahibsingh** [comment]
Once I completely removed the Flutter and Android Studio (With settings) from my system, I was able to make the flutter work after a fresh setup. But this shouldn't be the case, right?
I mean we possibly could not do a fresh setup every time this issue occurs.

**Comment by Ldev007** [comment]
A pretty easy workaround for me was to just close whichever program or software (IDE mostly, VS Code or Android Studio) is using dart.exe or dart-sdk. Basically, what I understood was that something was using dart-sdk in the backend and that wasn't letting a file belonging to the SDK folder to be renamed although it shouldn't have been happening.
