### ISSUE TITLE
CompositedTransformFollower should allow to position itself based on its child's size

### ISSUE THREAD

**Issue by nioncode** [flutter/flutter#57604]
I'm using `CompositedTransformTarget` and `CompositedTransformFollower` to display an `OverlayEntry`. The follower should be displayed on top of the target and centered horizontally on top of it. However, since `CompositedTransformFollower` only allows to position itself with a fixed offset, this is not achievable without hardcoding the width and height of the follower's child.

Is there any way at the moment to position the `CompositedTransformFollower` relative to the `CompositedTransformTarget`, i.e. how can I align its bottom to the top-center of the target in order to display it horizontally centered above the target, while maintaining interactivity (i.e. hit tests on the child should work)?

The only thing that would fix this in my opinion would be to add some kind of relative offsets to `CompositedTransformFollower` in order to position it relative to its own size (or rather the size of its child). 

Sample Code, which uses absolute values for positioning:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light),
      home: Scaffold(
        appBar: AppBar(title: Text('test')),
        body: Center(child: OverlayButton()),
      ),
    );
  }
}

class OverlayButton extends StatefulWidget {
  @override
  _OverlayButtonState createState() => _OverlayButtonState();
}

class _OverlayButtonState extends State<OverlayButton> {
  OverlayEntry _overlayEntry;
  final LayerLink _layerLink = LayerLink();
  bool _overlayIsShown = false;

  @override
  void dispose() {
    super.dispose();
    if (_overlayIsShown) {
      _hideOverlay();
    }
  }

  void _showOverlay() {
    if (_overlayIsShown) return;
    _overlayEntry = _createOverlayEntry();
    Overlay.of(context).insert(_overlayEntry);
    _overlayIsShown = true;
  }

  void _hideOverlay() {
    _overlayIsShown = false;
    _overlayEntry.remove();
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformTarget(
      link: _layerLink,
      child: RaisedButton(child: Text('Open Overlay'), onPressed: _showOverlay),
    );
  }

  OverlayEntry _createOverlayEntry() {
    RenderBox renderBox = context.findRenderObject();
    var anchorSize = renderBox.size;
    return OverlayEntry(builder: (context) {
      // TODO: dynamically use the correct child width / height for
      // positioning us correctly on top + centered on the anchor
      var childWidth = 200.0;
      var childHeight = 40.0;
      var childOffset =
          Offset(-(childWidth - anchorSize.width) / 2, -(childHeight));
      return Row(
        children: <Widget>[
          CompositedTransformFollower(
            link: _layerLink,
            offset: childOffset,
            child: RaisedButton(
              child: Text('close'),
              onPressed: _hideOverlay,
            ),
          ),
        ],
      );
    });
  }
}
```

I also asked this on SO [before](https://stackoverflow.com/questions/61623034/how-to-position-a-compositedtransformfollower-based-on-its-childs-size), but it seems like this is not possible at the moment without implementing our own follower based on `SingleChildRenderObjectWidget`.

**Comment by lauweijie** [comment]
#64930 was reverted in #65878.

Should we reopen this until #65884 lands?
