### ISSUE TITLE
Run setup and teardown of flutter_test in FakeAsync zone

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#57600]
In the implementation of https://api.flutter.dev/flutter/flutter_test/testWidgets.html, `test()` method runs in an outer zone (normal async) whereas `binding.runTest` might create an inner zone with fake async. 

This leads to very undesirable behavior when apps try to use normal test `setup`/`teardown` functions to initialize a framework that happens to rely on Future's.  Their tests start timing out since widgets cannot await Future's created in `setup` functions.

If we could run the entire `setup`/`test`/`teardown` sequence in the same zone, most of the surprising behavior would go away.

Example problematic code:

```dart
void main() {
  setUp(() {
     fs = MemoryFileSystem();
     // Some framework that depends on a file system
     // we pass a memory file system implementation that still
     // relies on Future's to work.
     someFramework.init(fs);
  });

  testWidgets('Sample test', (tester) async {
    await tester.pumpWidget(someWidget that uses someFramework);
    // The following hangs since widget awaits some operation on someFramework.
    await tester.pumpAndSettle();
  });
}
```

One workaround would be to move the setup to inside `testWidgets` but that goes against testing style guides and is error prone. Ideally `testWidgets` should just work well with package:test principles.

**Comment by mehmetf** [comment]
We have been writing a lot of articles about understanding async behavior in widget tests (such as https://medium.com/flutter/understanding-async-in-flutter-tests-a304a7604b3c). I feel like this change might make this simpler since one people understand FakeAsync, its rules apply to the *entire* test file rather than just `testWidgets` fn.

**Comment by mehmetf** [comment]
One caveat is that we would not be able to pass `WidgetTester` to setup function which would mean we cannot pump (if the setup required it). However, this is easily solvable via `pumpAndSettle` in each testWidgets function which is what most tests currently do anyway.

**Comment by jamesderlin** [comment]
I don't think rearranging the code will work the way you want.  The `Zone` where `test()` is called is *not* the `Zone` where its *callback* is invoked (see https://github.com/dart-lang/test/issues/1023).

**Comment by mehmetf** [comment]
Hopefully if FakeAsync is the parent zone of `test()`, it will propagate to all zones created for `setup()` and its callbacks.

Having said that, I am *quite* sure that it is not that simple. :-)

**Comment by jamesderlin** [comment]
`test()` callbacks currently can be invoked in `Zone`s that are not descended from the `Zone` where `test()` (or `setUp()`) was called.  Empirically it appears that they will be descended from the `Zone` where `test()` was *first* invoked, but relying on that seems questionable.

**Comment by mehmetf** [comment]
We definitely need a better contract between package:test and package:flutter_test. I was OK with `testWidgets` up till now because the only problem was that it had a sharp learning curve. However, the inability to interoperate with `group`, `setup`, `setupAll` is unacceptable IMO.  You should be able to mix `testWidgets` and `test` methods together and get sensible results. Either that or we should stop pretending people can use `package:test` constructions and provide complete implementations of commonly used test paradigms in `package:flutter_test`.

**Comment by mehmetf** [comment]
Looked into this a bit more.

Zone tree looks like this:

```
_CustomZone@495722280 [inside widget_tester test() callback]
  _CustomZone@629267482
    _CustomZone@783412751
      _CustomZone@721172351 [inside core test() callback; also inside setup();]
        _CustomZone@619865116
          _CustomZone@626736146
            _CustomZone@911453401
              _CustomZone@599318833
                _CustomZone@115979321
                  _CustomZone@546883079
                    _CustomZone@690238357 [inside testWidgets fn; attaching FakeSync here won't work]
                    _CustomZone@284985316
                      _CustomZone@920411218
                        _CustomZone@111637958
                          _CustomZone@632278600
                            _RootZone@230753058
```

- As James points out, the zone that `testWidgets` fn runs is a sibling of the zone that the rest of the test harness gets created, rather than the parent. Creating fake async there would not work.
- The widget_tester callback runs in a child zone that test harness creates; meaning if we could create a fake async zone there, things would work.
- Fake Async is only valid during the test.body() execution. After each test() completion it gets cleaned up. It gets created [here](https://github.com/flutter/flutter/blob/9d58a87066d1da98eb06826918e4b90cc76ae0ef/packages/flutter_test/lib/src/binding.dart#L1086-L1095) and gets cleaned up [here](https://github.com/flutter/flutter/blob/9d58a87066d1da98eb06826918e4b90cc76ae0ef/packages/flutter_test/lib/src/binding.dart#L1147-L1158). 

One potential solution is to create `setupWidgets` similar to `testWidgets` and register it to be run before widget_tester callback. This could lead to a cleaner lifecycle management for fake async. We could have a default "setup" which sets it up and a default "teardown" which cleans it up rather than using test_api's addTeardown() functionality.

Another, less involved, solution is to allow apps to pass setup fn as part of testWidgets() call. While this reduces the boilerplate, it is not that much better than apps simply defining a function that they call every time in the widget_tester test body. It is also error prone (e.g. you cannot name the function setup()).

**Comment by mehmetf** [comment]
https://github.com/flutter/flutter/pull/57894 out to introduce `setUpWidgets`. Moving the lifecycle of `FakeAsync` entirely out of `runTest` leads to complications since setup/teardown functions are optional. Therefore, I opted to initialize `FakeAsync` as needed. 

I also did not add a teardown function (yet) as the use case is rare.

**Comment by chunhtai** [comment]
I think it make sense to have setup and teardown to be in the same zone as testWdiget, but that means we probably need to recreate all the setup teardown methods in the flutter_test and encourage user to use these methods instead of the ones in test library.

I also curious about the use case where you want to create a future in setup to be completed during testWidget. I can't think of a good reason to create a test like that. Do you have a more specific example code that demonstrate the use case?

**Comment by chunhtai** [comment]
cc @jonahwilliams

**Comment by mehmetf** [comment]
Chun and I discussed this offline. There's a way to implement teardown as well but it would be a departure of how package:flutter_test delegates to package:test functionality. It relatively clean and small in scope, so I will modify the PR.

**Comment by mehmetf** [comment]
Update:

I got a chance to try out [Nate's PR](https://github.com/dart-lang/test/pull/1274) in google3.

Initial impression: This is going to be tricky if at all possible. Similar to his observation that timeout timer needs to run in the root zone, there are other conflicts between fake async and invoker's assumptions. For instance: You cannot do `await Future(() {})` in FakeAsync as it creates a 0-duration timer which never completes without the test code flushing the timer. Another example is the LocalTest's body. This one was more surprising. Turns out `await` itself creates a microtask which, again, gets stuck in FakeAsync unless someone flushes the queue. In other words, there are fundamental differences between fake async and normal test code on how you deal with Futures and Timers.

There are several options I could think of:

- package:test accounts for these fundamental differences and supports FakeAsync as a first-class test execution platform. This likely requires a completely new design. However, it has the advantage that we no longer have to fragment package:flutter_test and package:test. flutter_test would just provide additional widget functionality rather than trying to plug in fake async.

- providing a lot of hooks for flutter_tester to "drive" the test... This would strongly couple the two packages and at that point the division between the two seems arbitrary to me.

- similar to previous point but instead of driving it via hooks, create a periodic timer that flushes the microtasks in fake async until the test body is executed. This is more practical but it is quite hacky. It was the only way I could get the test to pass. Note that, even with this, "await Future()" needs to be removed unless we also want to resolve Timers.

- Don't touch package:test. Just expose setupWidgets and teardownWidgets much like we do testWidgets(). This was my second proposal but it leads to further fragmentation from package:test. something we said we are [not going to do](https://github.com/flutter/flutter/issues/52003#issuecomment-637654386). 

Nate is now exploring the option of solving this via https://github.com/dart-lang/test/issues/377. This seems closer to what we want. Just a wrapper function for all setup/test/teardown callbacks.

**Comment by mehmetf** [comment]
After several attempts to solve this problem at framework level, Nate and I decided that there's no good solution that works in all cases. Users still need to be aware of the differences between fake and real async zones. Instead, we opted to create a utility called `waitTill` for people having problems with flakiness.

Full Implementation (mostly comments):

```dart
/// Attempts to resolve the interplay between real and fake async zones until
/// widget tree is ready as indicated by [predicate].
///
/// If your test code depends on the result of a task that did not complete,
/// the most common symptom would be a hanging test as [FakeAsync] environment
/// is unable to resolve a future that was created in `runAsync`. If you
/// observe such behavior or flakiness, you have a number of options ordered by
/// desirability:
///
/// - Consider restructuring your code so you do not need `runAsync`. This is
///   the optimal solution as widget tests are designed to run in fake async
///   environment.
///
///.- Await all futures directly in the [callback] of runAsync such that when
///   runAsync is done, you are guaranteed to have a ready-to-test widget.
///
/// - Use this API to resolve all side effects and ensure widget is ready to
///   test.
///
/// For instance imagine you have a stateful widget, like so:
///
/// ```
/// class FooWidgetState extends State<FooWidget> {
///   final Completer _ready;
///
///   bool isReady() => _ready.isCompleted;
///
///   void resultOfSomeExpensiveOperation() {
///     setState(() => someConditionIsMet = true);
///     // The order of set state and _ready.complete doesn't matter.
///     // This widget might need an extra pump to be tested as setState
///     // schedules a new frame.
///     _ready.complete();
///   }
///
///   Widget build(BuildContext context) {
///     if (someConditionIsMet) {
///       // Build the actual widget
///     } else {
///       // Build an empty widget; we are not ready yet.
///     }
///   }
/// }
/// ```
///
/// You can then use this method in your test:
///
/// ```
/// testWidgets('..', (tester) async {
///   await tester.pumpWidget(FooWidget());
///   final fooWidgetState = tester.state<FooWidgetState>(find.byType(FooWidget));
///   await waitTill(tester, fooWidgetState.isReady);
///   expect(...);
/// });
/// ```
///
/// This function does not specify a timeout parameter on purpose because a
/// predicate that hangs is considered a bug and timeouts make it more
/// difficult to differentiate between bugs and flakes.
Future<void> waitTill(
  WidgetTester tester,
  bool Function() predicate,
) async {
  await tester.runAsync(() async {
    while (!predicate()) {
      await pumpEventQueue();
      await tester.pump();
    }
  });
}
```
