### ISSUE TITLE
flutter test --coverage generates empty lcov.info when using relative import paths

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#5761]
## Steps to Reproduce
- Create a new flutter project (`flutter create foo`).
- Add `flutter_test` as a dev_dependency in `pubspec.yaml`.
- Add `test/main_test.dart` file as below.

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import '../lib/main.dart';

void main() {
  testWidgets('foo', (WidgetTester tester) async {
    await tester.pumpWidget(new StatefulBuilder(
        builder: (BuildContext context, StateSetter setState) {
      return new MaterialApp(home: new FlutterDemo());
    }));
  });
}
```
- Run `flutter test --coverage`, which will generate an empty `lcov.info` file:

```
foo$ flutter test --coverage
00:00 +0: loading /<home>/Programming/temp/foo/test/main_test.dart    
Shell: Observatory listening on http://127.0.0.1:2986
Shell: Diagnostic server listening on http://127.0.0.1:33979
00:00 +1: All tests passed!                                                                        
Collecting coverage information...                   5.1s
foo$ ll coverage
total 8
drwxr-x--- 2 youngseokyoon eng 4096 Sep  7 14:57 ./
drwxr-x--- 8 youngseokyoon eng 4096 Sep  7 14:57 ../
-rw-r----- 1 youngseokyoon eng    0 Sep  7 14:57 lcov.info
foo$
```

The coverage report is produced correctly when using the package level import (`import 'package:foo/main.dart`) instead of relative path (`import '../lib/main.dart`).
## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/youngseokyoon/Programming/flutter
    • Framework revision e47a421e42 (5 hours ago), 2016-09-07 13:34:50
    • Engine revision dcb026188a
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/youngseokyoon/Android/Sdk
    • Platform android-24, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-131405950-131398047)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```

cc: @eseidelGoogle

**Comment by eseidelGoogle** [comment]
Relative import paths are not The Dart Way™, but we still shouldn't fail out silently.  @cbracken might have a hunch.  This is in the nice-to-fix-some-day category.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/coverage_collector.dart is likely the code in question.

**Comment by cbracken** [comment]
Definitely a bug, most likely in package:coverage; once I've repro'ed I'll update here with whether it's a bug there or in Flutter.

As @eseidelGoogle says, for better or for worse, the idiomatic way to import any Dart src under `lib/` (including from srcs outside of `lib` in the same package is:
```dart
import 'package:package_name/main.dart';
```
which should hopefully get you going again until we've got a fix in.

Thanks for reporting!

**Comment by yyoon** [comment]
Sure. Changing all the imports shouldn't be a big deal. Thanks :)

**Comment by eseidelGoogle** [comment]
I suspect this is a package:coverage bug and we should move there.  Speculatively closing in Flutter.

**Comment by neelu004** [comment]
how to read the coverage->Icov.info file when i have used the flutter test --coverage to generate code coverage report in flutter.
