### ISSUE TITLE
Migrate packages needed for flutter to null safety

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#57612]
packages

- [x] typed_data
- [x] vector_math
- [x] collection
- [x] meta

process

- [x] changes made to packages
- [x] merged back to master
- [x] SDK DEPs updated
- [x] synced to Google internal
- [x] published

Migrations have started for all of these, but we need to have a plan for getting tests passing and pre-release packages published

**Comment by franklinyow** [comment]
@kevmoo 
All packages are published, any work left?

**Comment by kevmoo** [comment]
Done! Huge props to @jakemac53 for making it happen!
