### ISSUE TITLE
type 'double' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by Mohamed21398** [flutter/flutter#57626]
Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:
type 'double' is not a subtype of type 'int'

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by kiaxseventh** [comment]
i have lot of model and json convert to model some times i have errors like this
`type 'double' is not a subtype of type 'int'`
it is not say which variable or which line of code have this problem and this vary bad becuse find error for which variable need long time 

are you have solution for this problem ?
