### ISSUE TITLE
Selecting TextField with keyboard from right to left not working

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#57636]
## Steps to Reproduce

1. Create a Flutter application using a `TextField`.
2. Run your application.
3. Enter text in the the field using the keyboard.
4. Holding shift down, press the left arrow key to select the end of the sentence.
5. Once text is selected, type replacement text.

**Expected results:**

Selected text is replaced with replacement text.

**Actual results:**

Text is not replaced, but instead appended. Selection is cleared.

What is occurring is Flutter is sending the shell an editing state where the selection extent is less than the selection base. This is explicitly disallowed in the engine in `shell/platform/common/cpp/text_input_model.cc`. Note that selecting with the mouse from right to left works and has selection base < selection extent. Tested on Linux, but this code is shared with Windows. Not sure if other shells behave the same.

An example `flutter/textinput` channel message received from Flutter:
```
{"method":"TextInput.setEditingState","args":{"text":"Hello World!","selectionBase":12,"selectionExtent":6,"selectionAffinity":"TextAffinity.downstream","selectionIsDirectional":false,"composingBase":-1,"composingExtent":-1}}
```

**Comment by stuartmorgan** [comment]
> This is explicitly disallowed in the engine in `shell/platform/common/cpp/text_input_model.cc`.

That's a bug in the C++ model. The TextSelection docs on the framework side [explicitly say that's valid](https://github.com/flutter/flutter/blob/3e63411256cc88afc48044aa5ea06c5c9c6a6846/packages/flutter/lib/src/services/text_editing.dart#L54).
