### ISSUE TITLE
Big IconButtons are clipped

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#5763]
```
import 'package:flutter/material.dart';

class BigIconButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Big IconButton')),
      body: new Center(
        // Does what you'd expect:
        // child: new Icon(Icons.android, size: 128.0)
        // Does not:
        child: new IconButton(
          icon: new Icon(Icons.android, size: 128.0),
          // reduntantly specifying 'size: 128.0' doesn't help 
          onPressed: () {}
        )
      )
    );
  }
}

void main() => runApp(new MaterialApp(home: new BigIconButton()));
```
![screenshot1](https://cloud.githubusercontent.com/assets/1377460/18331324/dd623f48-7512-11e6-902a-1d59ceeed26c.png)

**Comment by jason-simmons** [comment]
Took a quick look at this.  Looks like this change was introduced in:
    https://github.com/flutter/flutter/commit/77a1719cfb14334a9f8c652d632408c68c82feac

IconButton now has a constraint based on InkSplash.defaultRadius that doesn't take the icon's size into account.

@Hixie what is the best way to fix this?

**Comment by Hixie** [comment]
I guess we should use math.max on that constrained box so that if the icon is bigger than the splash radius then we constrain to the icon size or something. Or we could apply the max to the splash size so that big icons get bigger splashes (and thus also bigger constraints).
