### ISSUE TITLE
getting RenderFlex overflow errors even though my screen appears to render correctly

### ISSUE THREAD

**Issue by nicolasmunoz** [flutter/flutter#57635]
I'm using a StreamProvider to get data from FireStore and have followed multiple tutorials to get to where I am, and it's working correctly according to the UI but I get hundreds of errors while the UI builds, and then eventually it ends with "Another exception was thrown: A RenderFlex overflowed by 99234 pixels on the bottom." My guess is it's probably trying to render more items than I want it to  but I'm not sure why it would be doing that or where my issue is

Here is my main screen that's being rendered:

	import "package:uniq_flutter/index.dart";

	class RegisterPreferencesScreen extends StatefulWidget{
	  @override
	  _RegisterPreferencesScreenState createState() => _RegisterPreferencesScreenState();
	}

	class _RegisterPreferencesScreenState extends State<RegisterPreferencesScreen>{

	  final _db = PreferencesRepository();

	  @override
	  Widget build(BuildContext context){
		return Scaffold(
		  body: Column(
			children: <Widget>[
			  StreamProvider<List<PreferenceCategory>>.value(
				value: _db.getAllPreferenceCategories(),
				child: PreferenceCategoryList()
			  )
			]
		  )
		);
	  }
	}

	class PreferenceCategoryList extends StatefulWidget{
	  @override
	  _PreferenceCategoryListState createState() => _PreferenceCategoryListState();
	}

	class _PreferenceCategoryListState extends State<PreferenceCategoryList>{
	  final List<PreferenceCategory> selectedChoices = List();
	  
	  List<Widget> _buildCategoryList(List<PreferenceCategory> preferenceCategories){
		List<Widget> choices = List();
		preferenceCategories.forEach((item){
		  choices.add(Container(
			padding: const EdgeInsets.all(2.0),
			child: ChoiceChip(
			  label: Text(
				item.preferenceCategoryName,
				textScaleFactor: 1.2,
			  ),
			  labelPadding: EdgeInsets.fromLTRB(10, 5, 10, 5),
			  selected: selectedChoices.contains(item),
			  onSelected: (selected) {
				setState(() {
				  selectedChoices.contains(item)
					? selectedChoices.remove(item)
					: selectedChoices.add(item);
				});
			  },
			),
		  ));
		});

		return choices;
	  }

	  @override
	  Widget build(BuildContext context){
		final preferenceCategories = Provider.of<List<PreferenceCategory>>(context);
		return Wrap(
		  children: _buildCategoryList(preferenceCategories)
		);
	  }
	}

here is my repository which is fetching the data:

	class PreferencesRepository {
	  final Firestore _db = Firestore.instance;

	  Stream<List<PreferenceCategory>> getAllPreferenceCategories() {
		final categories = _db.collection("preference_category").snapshots().map((snap) {
		  return snap.documents.map((doc) => PreferenceCategory.fromFirestore(doc)).toList();
		});
		return categories;
	  }
	}

and this is my model:

	class PreferenceCategory{
	  final String preferenceCategoryId;
	  final String preferenceCategoryName;

	  PreferenceCategory({this.preferenceCategoryId,this.preferenceCategoryName});

	  factory PreferenceCategory.fromFirestore(DocumentSnapshot data){
		return PreferenceCategory(
		  preferenceCategoryId: data.documentID,
		  preferenceCategoryName: data.data["Name"] ?? ""
		);
	  }
	}

this is my final properly rendered display:
![image](https://user-images.githubusercontent.com/9328218/82404910-76c5be80-9a30-11ea-8384-45ff2f385cb4.png)

here are all the errors I'm receiving (this repeats for a while, so screenshotted top stack and bottom stack):
![image](https://user-images.githubusercontent.com/9328218/82404793-2c444200-9a30-11ea-9ce3-76ae0097aedf.png)
![image](https://user-images.githubusercontent.com/9328218/82404806-38300400-9a30-11ea-8203-ee92ef0c4dad.png)

**Comment by iapicca** [comment]
Hi @nicolasmunoz 
does  this possible [solution](https://github.com/flutter/flutter/issues/18448#issuecomment-595510313) solve the issue?

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>  MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Material(
    child: SingleChildScrollView(
      child: MyThreeOptions(),
    ),
  );
}

/// source [ChoiceChip] => [https://api.flutter.dev/flutter/material/ChoiceChip-class.html#material.ChoiceChip.1]
class MyThreeOptions extends StatefulWidget {
  @override
  _MyThreeOptionsState createState() => _MyThreeOptionsState();
}

class _MyThreeOptionsState extends State<MyThreeOptions> {
  int _value = 1;
  @override
  Widget build(BuildContext context) {
    return Wrap(
      children: List<Widget>.generate(
        3,
        (int index) {
          return ChoiceChip(
            label: Text('Item $index'),
            selected: _value == index,
            onSelected: (bool selected) {
              setState(() {
                _value = selected ? index : null;
              });
            },
          );
        },
      ).toList(),
    );
  }
}
```

</details>
thank you

**Comment by nicolasmunoz** [comment]
Tried using Expanded, SingleChildScrollView, and ConstrainedBox and still getting errors. I think everything may be caused by this initial error but not sure why it thinks there are null members in preferenceCategories.
![image](https://user-images.githubusercontent.com/9328218/82447458-54ef2a80-9a76-11ea-9feb-6acbc3f4bc38.png)

**Comment by iapicca** [comment]
Hi again @nicolasmunoz 
are you getting errors running the code sample?
Thank you

**Comment by nicolasmunoz** [comment]
The code sample works fine so it must be something relating to how I'm building my list of widgets using the foreach statement since that's mentioned in the error. Can you suggest a better way of implementing it?

**Comment by nicolasmunoz** [comment]
so i've messed around with it quite a bit today and I've stripped it to the bare minimum and I'm using a static list (preferenceFakeCategories) that I create instead of using my Stream Provider values, and this works!
		import 'package:flutter/material.dart';
		import 'package:provider/provider.dart';

		import 'package:uniq_flutter/index.dart';

		class RegisterPreferencesScreen extends StatefulWidget{
		  @override
		  _RegisterPreferencesScreenState createState() => _RegisterPreferencesScreenState();
		}

		class _RegisterPreferencesScreenState extends State<RegisterPreferencesScreen>{

		  final _db = PreferencesRepository();

		  @override
		  Widget build(BuildContext context){
			return Scaffold(
			  body: Column(
				mainAxisAlignment: MainAxisAlignment.spaceEvenly,
				crossAxisAlignment: CrossAxisAlignment.center,
				children: <Widget>[
				  StreamProvider<List<PreferenceCategory>>.value(
					value: _db.getAllPreferenceCategories(),
					child: Center(
					  child: PreferenceCategoryList()
					)
				  ),
				  FlatButton(
					child: Text('Next'),
					onPressed: (){},
				  )
				]
			  )
			);
		  }
		}

		class PreferenceCategoryList extends StatefulWidget{
		  @override
		  _PreferenceCategoryListState createState() => _PreferenceCategoryListState();
		}

		class _PreferenceCategoryListState extends State<PreferenceCategoryList>{
		  final List<PreferenceCategory> selectedChoices = List();

		  @override
		  Widget build(BuildContext context){
			//final preferenceCategories = Provider.of<List<PreferenceCategory>>(context);
			List<PreferenceCategory> preferenceFakeCategories = List();
			preferenceFakeCategories.add(PreferenceCategory(preferenceCategoryId: '1',preferenceCategoryName: 'Adventure'));
			preferenceFakeCategories.add(PreferenceCategory(preferenceCategoryId: '2',preferenceCategoryName: 'Shopping'));
			preferenceFakeCategories.add(PreferenceCategory(preferenceCategoryId: '3',preferenceCategoryName: 'Sightseeing'));
			return Column(
			  children: preferenceFakeCategories.map((category) {
				return FlatButton(
				  onPressed: (){},
				  color: Colors.blue,
				  textColor: Colors.white,
				  child: Text(category.preferenceCategoryName)
				);
			  }).toList()        
			);
		  }
		}

However, as soon as I decide to use the List<PreferenceCategory> from my Stream Provider it breaks down and I get the following error:
![image](https://user-images.githubusercontent.com/9328218/82504489-87764300-9ac9-11ea-81a7-83253e1f67cb.png)

As well as "Another exception was thrown: A RenderFlex overflowed by 99282 pixels on the bottom."

Since I'm starting to think it has something to do with my stream provider, here is my setup for my repository retrieving the data from FireStore:

	import 'package:cloud_firestore/cloud_firestore.dart';
	import 'package:uniq_flutter/index.dart';

	class PreferencesRepository {
	  final Firestore _db = Firestore.instance;

	  Stream<List<PreferenceCategory>> getAllPreferenceCategories() {
		final categories = _db.collection('preference_category').snapshots().map((snap) {
		  return snap.documents.map((doc) => PreferenceCategory.fromFirestore(doc)).toList();
		});
		return categories;
	  }
	}

and my model:
	import 'package:cloud_firestore/cloud_firestore.dart';

	class PreferenceCategory{
	  final String preferenceCategoryId;
	  final String preferenceCategoryName;

	  PreferenceCategory({this.preferenceCategoryId,this.preferenceCategoryName});

	  factory PreferenceCategory.fromFirestore(DocumentSnapshot data){
		return PreferenceCategory(
		  preferenceCategoryId: data.documentID,
		  preferenceCategoryName: data.data['Name'] ?? ''
		);
	  }
	}

please help, this is driving me crazy and I've spent days on this issue with no answers

**Comment by nicolasmunoz** [comment]
I got it, it was erroring because the screen was trying to build before the stream had yet passed any values so it couldn't do any operations on null. I simply had to pass an empty list to initialData on the StreamProvider
![image](https://user-images.githubusercontent.com/9328218/82513816-11caa100-9ae2-11ea-9e15-92912743c964.png)

closing this issue
