### ISSUE TITLE
Flutter fails to detect plugins  when Android Studio is installed via Toolbox

### ISSUE THREAD

**Issue by firephreek** [flutter/flutter#57642]
## Steps to Reproduce

1. Install Android Studio using Jetbrains Toolbox on Windows (untested Linux/Mac)
2. Install Flutter/Dart plugins
3. Run `flutter doctor -v`

Notes:  The 'system cannot find the path specified' may be an unrelated issue with the flutter.bat file.  Currently investigating.

## Logs

`flutter doctor -v`

```
The system cannot find the path specified.
The system cannot find the path specified.
Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
[√] Flutter (Channel stable, v1.17.1, on Windows, locale en-US)
    • Flutter version 1.17.1 at D:\dev\sdk\flutter
    • Framework revision f7a6a7906b (7 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\dev\sdk\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\dev\sdk\Android\sdk
    • Java binary at: C:\Users\Stryder\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Users\Stryder\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\Stryder\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6911.18
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by firephreek** [comment]
'The system cannot find the path specified.' messages are unrelated to this issue. Result of leftover 'AutoRun' values in registry from broken uninstall of unrelated application.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/47583

**Comment by christopherfujino** [comment]
@firephreek was this fixed by https://github.com/flutter/flutter/pull/57963/files? If not, I'm assuming it would be picked up by https://github.com/flutter/flutter/pull/58853 (which hasn't landed yet), is that correct?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by Butzlabben** [comment]
I am having the same issue here. I have both Android Studio (4.0.1) and IntelliJ Ultimate (2020.2) installed via Jetbrains Toolbox, however only Android Studio gets detected. I can reproduce this issue on my Windows machine.
Output from `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.20.1 at /opt/flutter
    • Framework revision 2ae34518b8 (vor 7 Tagen), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/daniel/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/daniel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /home/daniel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by Sanket-Kumbhare** [comment]
I was also having same problem:
Try this. It sloved my problem

flutter channel dev
flutter upgrade

**Comment by Smart123s** [comment]
> I was also having same problem:
> Try this. It sloved my problem
> 
> flutter channel dev
> flutter upgrade

I have switched to channel master and it has also solved the problem.
I am on Ubuntu 20.10 using the snap package for both Flutter and Android Studio.
Thanks for helping.

**Comment by felipeolliveira** [comment]
> I was also having same problem:
> Try this. It sloved my problem
> 
> flutter channel dev
> flutter upgrade

This also solved my problem. Thank you for helping! :smile:

**Comment by benibilme** [comment]
> I was also having same problem:
> Try this. It sloved my problem
> 
> flutter channel dev
> flutter upgrade

Solved my problem. Thank you.
