### ISSUE TITLE
Icons and images missing in latest flutter upgrade

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#5764]
## Steps to Reproduce

I recently upgraded flutter, and it looks like there's a bug in image/icon display. Flutter gallery runs (though there was an extra comma in line 19 of lib/gallery/app.dart that I had to remove for it to run), but all images are blank and all icons are displayed as question marks. It appears this may be a bug in image_resolution.dart.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/flutter
    • Framework revision 9a0a0d9903 (4 weeks ago), engine revision f8d80c4617
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38

## Logs and Crash Reports

flutter run lib/main.dart (debug) • flutter_gallery/
Running lib/main.dart on iPhone 6s...

CoreSimulatorBridge: Requesting installation of file:///Users/emshack/flutter/examples/flutter_gallery/ios/build/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.flutterGallery";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data";
	}
installd: 0x700000094000 -[MIClientConnection _doBackgroundInstallationForPath:withOptions:completion:]: Install of "/Users/emshack/flutter/examples/flutter_gallery/ios/build/Release-iphonesimulator/Runner.app" type Developer (LSInstallType = (null)) requested by CoreSimulatorBridge (pid 26020)
installd: 0x700000094000 MDMCreateDeltaDirectory: calling MDMDirectoryDiff with:
	state->old_bundle: /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Containers/Bundle/Application/34D4B96F-DE20-40FB-9D65-7DAB13A55557/Runner.app
	state->new_bundle: /Users/emshack/flutter/examples/flutter_gallery/ios/build/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Library/Caches/com.apple.mobile.installd.staging/temp.wIRlpM/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Library/Caches/com.apple.mobile.installd.staging/temp.wIRlpM/extracted
installd: 0x700000117000 __MDMDirectoryDiff_block_invoke37: calling writeDictToFile with: /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Library/Caches/com.apple.mobile.installd.staging/temp.wIRlpM/extracted/ManifestCache.plist
installd: 0x700000117000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Library/Caches/com.apple.mobile.installd.staging/temp.wIRlpM/extracted/ManifestCache.plist
installd: 0x700000094000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=com.yourcompany.flutterGallery; Version=1, ShortVersion=1.0>
installd: 0x700000094000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of com.yourcompany.flutterGallery from 1 (1.0) to 1 (1.0)
installd: 0x700000094000 -[MIInstallableBundle _refreshUUIDForContainer:withError:]: Data container for com.yourcompany.flutterGallery is now at /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Containers/Data/Application/79029BEA-5A8C-4A59-866A-149BA166F4BF
installd: 0x700000094000 -[MIContainer makeContainerLiveReplacingContainer:reason:withError:]: Made container live for com.yourcompany.flutterGallery at /Users/emshack/Library/Developer/CoreSimulator/Devices/C1E3EB06-AD47-46DC-AD56-9DB6A02312EB/data/Containers/Bundle/Application/E402EF89-46A8-44AC-AF0F-D733157F6366
installd: 0x700000094000 -[MIInstaller performInstallationWithError:]: Install Successful; Staging: 0.09s; Waiting: 0.00s; Preflight/Patch: 0.00s, Verifying: 0.00s; Overall: 0.13s
pkd: releasing plug-in hold A3886280-5FC8-4A66-9F35-6519774EBFEB at client's request
SpringBoard: Installed apps did change.
	Added: {(
	)}
	Removed: {(
	)}
	Modified: {(
	    "com.yourcompany.flutterGallery"
	)}
SpringBoard: throwing out icon because it isn't visible in the model : node=<SBApplicationIcon: 0x7f8be0c112a0; nodeID: "com.apple.camera"> com.apple.camera
SpringBoard: Reply Error: Connection interrupted
containermanagerd: 0x700000323000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
lsd: LaunchServices:(called by PID 26020) Identifiers file does not exist, creating file.
containermanagerd: 0x7000002a0000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
CoreSimulatorBridge: Requesting launch of com.yourcompany.flutterGallery with options: {
	    arguments =     (
	        "--flx=/Users/emshack/flutter/examples/flutter_gallery/build/app.flx",
	        "--dart-main=/Users/emshack/flutter/examples/flutter_gallery/lib/main.dart",
	        "--packages=/Users/emshack/flutter/examples/flutter_gallery/.packages",
	        "--enable-checked-mode",
	        "--start-paused",
	        "--observatory-port=8100"
	    );
	    environment =     {
	    };
	}

backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[99095]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[99095]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[99095]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[99095]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[99095]
assertion failed: 15G31 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.
Observatory listening on http://127.0.0.1:8100
[INFO:FlutterDynamicServiceLoader.mm(129)] Could not find the service definitions manifest. No custom services will be available.
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered

Application running.

[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
FormatException: Unexpected end of input (at character 1)
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:484)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:501)
#4      JsonCodec.decode (dart:convert/json.dart:127)
#5      AssetImage._manifestParser (package:flutter/src/services/image_resolution.dart:145:55)
#6      _RootZone.runUnary (dart:async/zone.dart:1404)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     _Future._complete (dart:async/future_impl.dart:467)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#12     CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:139:5)
#13     _RootZone.runUnary (dart:async/zone.dart:1404)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#17     _Future._completeWithValue (dart:async/future_impl.dart:477)
#18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following FormatException was thrown while resolving an image:
FormatException: Unexpected end of input (at character 1)
^
When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:484)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:501)
#4      JsonCodec.decode (dart:convert/json.dart:127)
#5      AssetImage._manifestParser (package:flutter/src/services/image_resolution.dart:145:55)
#12     CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:139:5)
(elided 14 frames from package dart:async)
Image provider: AssetImage(bundle: null, name:
packages/flutter_gallery_assets/appbar/appbar_background_layer0.png)
Image configuration: ImageConfiguration(bundle: MojoAssetBundle@892297282()devicePixelRatio:
2.0platform: ios)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: FormatException: Unexpected end of input (at character 1)

Another exception was thrown: FormatException: Unexpected end of input (at character 1)
Another exception was thrown: FormatException: Unexpected end of input (at character 1)
Another exception was thrown: FormatException: Unexpected end of input (at character 1)

routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

Debugging iPhone 6s
Flutter
Debug drawing	Repaint rainbow
Performance overlay	Slow animations
Isolate main.dart:main()running

EXECUTION
LIBRARIES
ISOLATES
BREAKPOINTS
No breakpoints
no errors1 processlib/main.dart1:1
LFUTF-8Dartalpha

**Comment by emshack** [comment]
FYI, I upgraded flutter again today, and am no longer having this issue.

**Comment by sethladd** [comment]
Thanks for the update!
