### ISSUE TITLE
Hot reload not working on Android Studio 3.6.3

### ISSUE THREAD

**Issue by vishwajit76** [flutter/flutter#57649]
I changed the code but reflation is not showing. also reloaded show 0 libraries. I press Ctl+S for saving the file + hot reload but not working.

Performing hot reload...
Syncing files to device Redmi 6A...
Reloaded 0 of 760 libraries in 665ms.

**Comment by TahaTesser** [comment]
Hi @vishwajit76 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Can you also try hot reload `r` press from `flutter run` and after saving changes and let me know if it works?
```
  +5 ms] Connected to _flutterView/0x789f727820.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
```
Thank you

**Comment by vishwajit76** [comment]
I found a solution [Link](https://github.com/Dart-Code/Dart-Code/issues/450#issuecomment-631344162).
