### ISSUE TITLE
When I perform a Hot Restart operation, any of my controls will execute build?

### ISSUE THREAD

**Issue by taohonghui** [flutter/flutter#57643]
The problem is the title

This is my code,I printed my log in my build and executed it twice when I was executing hot-restart, which is inconsistent with the situation when I recompiled and opened the app. I want to know why

`void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("app build");

    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
          body: Text('hello'),
        ));
  }
}`

**Comment by VladyslavBondarenko** [comment]
Hi @taohonghui ,
see https://github.com/flutter/flutter/issues/57353#issuecomment-629569076,
closing as duplicate,
if you disagree please write in the comments and I will reopen it
