### ISSUE TITLE
SharedPreferencesImpl java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#57652]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 27312 free bytes and 26KB until OOM, max allowed footprint 134217728, growth limit 134217728
       at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:84)
       at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:73)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:188)
       at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:730)
       at android.app.SharedPreferencesImpl.-wrap2()
       at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:599)
       at android.app.QueuedWork.processPendingWork(QueuedWork.java:258)
       at android.app.QueuedWork.-wrap0()
       at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

![image](https://user-images.githubusercontent.com/47334522/82421366-90472480-9a89-11ea-8c39-9f6e9077f130.png)

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Which version of `shared_preferences` you using? 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kw2019ltd** [comment]
hi  i am saving minimal data like boolean treu/false or string with small data.

**share: ^0.6.4+2**

**$ flutter doctor -v**
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/cirrus/sdks/flutter
    • Framework revision f7a6a7906b (33 hours ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 3 categories.

code:
```
import 'package:shared_preferences/shared_preferences.dart';
import 'package:twitter_app/firebase/fire_base.dart';

const String show_ads = 'show_ads';
const String twitter_url = 'twitter_url';
const String user_guide_url = 'user_guide_url';

class SharedPreferencesManager {
  static final SharedPreferencesManager _instance =
      SharedPreferencesManager._internal();

  SharedPreferences _sharedPreferences;
  String _locale;
  bool _showAds;
  String _twitter_url;
  String _user_guide_url;

  factory SharedPreferencesManager() => _instance;

  SharedPreferencesManager._internal();

  Future<void> initSharedPreferences() async {
    _sharedPreferences = await SharedPreferences.getInstance();
    _initLocale();
    _initShowAds();
    _initTwitterUrl();
    _initUserGuideUrl();
  }

  void _initLocale() {
    _locale = _sharedPreferences.getString('_locale') ?? 'en';
  }

  void setLocale(String local) {
    _locale = local;
    _sharedPreferences.setString('_locale', local);
  }

  void _initShowAds() {
    _showAds = _sharedPreferences.getBool(show_ads);
    if (_showAds == null) {
      _showAds = false;
      _sharedPreferences.setBool(show_ads, _showAds);
    }
  }

  void _initTwitterUrl() {
    _twitter_url = _sharedPreferences.getString(twitter_url);
    if (_twitter_url == null) {
      _twitter_url = twitter_downloader_url_default;
      _sharedPreferences.setString(twitter_url, _twitter_url);
    }
  }

  void _initUserGuideUrl() {
    _user_guide_url = _sharedPreferences.getString(user_guide_url);
    if (_user_guide_url == null) {
      _user_guide_url = user_guide_url_default;
      _sharedPreferences.setString(user_guide_url, _user_guide_url);
    }
  }

  Future<void> saveShowAds(bool value) async {
    await _sharedPreferences.setBool(show_ads, value);
  }

  Future<void> saveTwitterUrl(String value) async {
    _twitter_url = value;
    await _sharedPreferences.setString(twitter_url, _twitter_url);
  }

  Future<void> saveUserGuideUrl(String value) async {
    _user_guide_url = value;
    await _sharedPreferences.setString(user_guide_url, _user_guide_url);
  }

  String get local => _locale;

  bool get showAds => _showAds;

  String get twitterUrl => _twitter_url;

  String get userGuideUrl => _user_guide_url;
}

```

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Please remove third party package and provide dummy data string that reproduces the issue
Thank you

**Comment by kw2019ltd** [comment]
I can't repreduce it.

Its error occurred in user device

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
From the looks of it, this could be due to long strings, i can see you are storing urls and you might want to use sqlite for storing strings, SharedPreferences is not a good choice for storing data.  

if you think this strings are short, please reproducible sample with similar strings
if you disagree please write in the comments and I will reopen it 
Thank you
