### ISSUE TITLE
Is the onKey callback of the soft keyboard on android / ios not resolved?

### ISSUE THREAD

**Issue by zhangyc** [flutter/flutter#57666]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

zhangyc@zhangycs-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
</details>

**Comment by VladyslavBondarenko** [comment]
Hi @zhangyc 
provide your `flutter doctor -v` and reproducible code sample, logs if related. What do you mean by "not resolved"?

**Comment by zhangyc** [comment]
我采用另外的一种方法解决了。I solved it the other way.
Tnanks


On 05/20/2020 20:14, Vladyslav Bondarenko wrote:

Hi @zhangyc
provide your flutter doctor -v and reproducible code sample, logs if related. What do you mean by "not resolved"?
