### ISSUE TITLE
CocoaPods installed but not working

### ISSUE THREAD

**Issue by mynameisxuqiang** [flutter/flutter#57669]
```
Flutter 1.17.1 • channel flutter-1.17-candidate.3 •
https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (7 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
```

```
$:sudo flutter doctor
CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.

      To re-install CocoaPods, run:
        sudo gem install cocoapods
```

i can not fix it. cocoapods is ok in other place. please~~

**Comment by VladyslavBondarenko** [comment]
@mynameisxuqiang 
doesn't `sudo gem install cocoapods` help?
https://github.com/flutter/flutter/issues/53685#issuecomment-606981550

**Comment by mynameisxuqiang** [comment]
> @mynameisxuqiang
> doesn't `sudo gem install cocoapods` help?
> [#53685 (comment)](https://github.com/flutter/flutter/issues/53685#issuecomment-606981550)
> 
> (you don't need to run `flutter doctor` with sudo)

it dose not help~

**Comment by VladyslavBondarenko** [comment]
@mynameisxuqiang 
please follow up on https://github.com/flutter/flutter/issues/57433,
I'm closing the current one as duplicate

**Comment by mynameisxuqiang** [comment]
i installed the homebrew, it works.but i dose not know why!
