### ISSUE TITLE
Memory leak while cache FlutterEngine

### ISSUE THREAD

**Issue by zj565061763** [flutter/flutter#57661]
context can not be released when cache FlutterEngine in app.

leak:
FlutterEngine.accessibilityChannel -> AccessibilityBridge.accessibilityMessageHandler -> AccessibilityBridge.rootAccessibilityView -> Context

**Comment by iapicca** [comment]
Hi @zj565061763 
are you trying to implement [this](https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity#using-a-cached-flutterengine)?
Can you please provide your `flutter doctor -v` 
and more details about the difficulties you are encountering
Thank you

**Comment by zj565061763** [comment]
@iapicca 

### flutter doctor -v

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17763.1217], locale zh-CN)
    • Flutter version 1.17.1 at D:\soft\flutter\flutter_windows_1.17.1-stable\flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\zjun\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\soft\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\soft\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

### demo:
```java
public class App extends Application {
    public FlutterEngine flutterEngine;

    @Override
    public void onCreate() {
        super.onCreate();

        flutterEngine = new FlutterEngine(this);
        flutterEngine.getNavigationChannel().setInitialRoute("/");
        flutterEngine.getDartExecutor().executeDartEntrypoint(DartExecutor.DartEntrypoint.createDefault());

        FlutterEngineCache.getInstance().put("app", flutterEngine);
    }
}
```

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        findViewById(R.id.fl_container).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startActivity(new Intent(MainActivity.this, MyFlutterActivity.class));
            }
        });
    }
}
```

```java
public class MyFlutterActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_flutter);

        final FlutterFragment flutterFragment = FlutterFragment
                .withCachedEngine("app")
                .build();

        getSupportFragmentManager().beginTransaction()
                .replace(R.id.container, flutterFragment)
                .commit();
    }
}
```

### leak
┬───
│ GC Root: System class
│
├─ android.provider.FontsContract class
│    Leaking: NO (App↓ is not leaking and a class is never leaking)
│    ↓ static FontsContract.sContext
├─ com.sd.demo.androidflutter.App instance
│    Leaking: NO (Application is a singleton)
│    App does not wrap an activity context
│    ↓ App.flutterEngine
│          ~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.FlutterEngine instance
│    Leaking: UNKNOWN
│    ↓ FlutterEngine.dartExecutor
│                    ~~~~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartExecutor instance
│    Leaking: UNKNOWN
│    ↓ DartExecutor.dartMessenger
│                   ~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartMessenger instance
│    Leaking: UNKNOWN
│    ↓ DartMessenger.messageHandlers
│                    ~~~~~~~~~~~~~~~
├─ java.util.HashMap instance
│    Leaking: UNKNOWN
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    ↓ HashMap$Node[].[1]
│                     ~~~
├─ java.util.HashMap$Node instance
│    Leaking: UNKNOWN
│    ↓ HashMap$Node.value
│                   ~~~~~
├─ io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler instance
│    Leaking: UNKNOWN
│    ↓ MethodChannel$IncomingMethodCallHandler.handler
│                                              ~~~~~~~
├─ io.flutter.embedding.engine.systemchannels.TextInputChannel$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing io.flutter.plugin.common.MethodChannel$MethodCallHandler
│    ↓ TextInputChannel$1.this$0
│                         ~~~~~~
├─ io.flutter.embedding.engine.systemchannels.TextInputChannel instance
│    Leaking: UNKNOWN
│    ↓ TextInputChannel.textInputMethodHandler
│                       ~~~~~~~~~~~~~~~~~~~~~~
├─ io.flutter.plugin.editing.TextInputPlugin$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing io.flutter.embedding.engine.systemchannels.TextInputChannel$TextInputMethodHandler
│    ↓ TextInputPlugin$1.this$0
│                        ~~~~~~
├─ io.flutter.plugin.editing.TextInputPlugin instance
│    Leaking: UNKNOWN
│    ↓ TextInputPlugin.mView
│                      ~~~~~
├─ io.flutter.embedding.android.FlutterView instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of com.sd.demo.androidflutter.activity.MyFlutterActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    ↓ FlutterView.mContext
╰→ com.sd.demo.androidflutter.activity.MyFlutterActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.sd.demo.androidflutter.activity.MyFlutterActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = f981ab7a-929a-4ee0-803c-34bc5d1e06ac
​     watchDurationMillis = 5140
​     retainedDurationMillis = 134

METADATA

Build.VERSION.SDK_INT: 28
Build.MANUFACTURER: Google
LeakCanary version: 2.3
App process name: com.sd.demo.androidflutter
Analysis duration: 8844 ms
