### ISSUE TITLE
Cannot select 1 character in a textfield with a mouse/pointer

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#57677]
I have an issue selecting a single character with a pointer. It seems the selection only happens when the mouse is clicked and dragged across 2+ characters

**Comment by guidezpl** [comment]
Should be fixed by #37969, repurposing issue to be about selecting one character

**Comment by YeungKC** [comment]
@guidezpl  I can't reproduce this issue on the master branch, could you provide reproducible steps?

**Comment by guidezpl** [comment]
Nice, this was fixed. Closing
