### ISSUE TITLE
Flutter memory consumtion problem

### ISSUE THREAD

**Issue by valen1321** [flutter/flutter#57675]
Since the last update flutter memory usage raise to insane levels at least on my computer... i just update flutter framework recently..... 

screentshots below
![after](https://user-images.githubusercontent.com/50416240/82451947-a6021d00-9a7c-11ea-91a5-b4f8e901883c.jpg)
![before](https://user-images.githubusercontent.com/50416240/82451954-a8647700-9a7c-11ea-9d17-0280f7561b16.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @valen1321 
please follow up on https://github.com/flutter/flutter/issues/56569,
I'm closing the current one as duplicate
