### ISSUE TITLE
iOS 13.4.1 Blank Screen issue on Stable Channel

### ISSUE THREAD

**Issue by kemalturk** [flutter/flutter#57672]
In release build iOS 13.4.1 version showing blank screen. I have tested on iPhone 6 and Huawei P20 it's working normally. And i switched channel stable to master it works on 13.4.1 too.

**Comment by VladyslavBondarenko** [comment]
Hi @kemalturk 
please follow up on the issue https://github.com/flutter/flutter/issues/36247,
comment there about your case.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.

**Comment by jmagman** [comment]
Reopening per https://github.com/flutter/flutter/issues/36247#issuecomment-645527596 for further triage.

**Comment by VladyslavBondarenko** [comment]
@kemalturk 
could you provide your `flutter doctor -v`?
does the issue persist with current stable channel? 
if yes, can you see some crash logs when running from xcode? https://github.com/flutter/flutter/issues/36247#issuecomment-572151934

> And i switched channel stable to master it works on 13.4.1 too.

with what flutter version you aren't experiencing this?

**Comment by kemalturk** [comment]
@VladyslavBondarenko ok im gonna provide the output.

**Comment by kemalturk** [comment]
@VladyslavBondarenko I fixed my issue. It's about localeResolutionCallback.
My code was like that : 

```diff
      localeResolutionCallback: (locale, supportedLocales) {
        for(var supportedLocale in supportedLocales) {
-          if(supportedLocale.languageCode == locale.languageCode) {
            return supportedLocale;
          }
        }
        return supportedLocales.first;
      },
```

I changed member access with conditional member access operator.

```diff
      localeResolutionCallback: (locale, supportedLocales) {
        for(var supportedLocale in supportedLocales) {
+          if(supportedLocale?.languageCode == locale?.languageCode) {
            return supportedLocale;
          }
        }
        return supportedLocales.first;
      },
```

If i don't put this conditional operator it's working in debug mode normally but shows blank screen in release mode. I mean there is an issue at MaterialApp widget. Somehow supportedLocale.languageCode or locale.languageCode comes null when calling localeResolutionCallback. You guys need to look at this.

**Comment by kemalturk** [comment]
```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-TR)
    • Flutter version 1.17.4 at /Users/kemalturk/Development/flutter
    • Framework revision 1ad9baa8b9 (21 hours ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kemalturk/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Kemal iPhone’u • 9c7bd0d32c27bd3458b88fb7dd081a8a186f27e8 • ios • iOS 13.5.1
```

**Comment by pedromassangocode** [comment]
Hi @kemalturk 
Are you still facing this issue on latest `stable` channel?
