### ISSUE TITLE
Engine Preroll flow can lead to extra nested entries in the RasterCache

### ISSUE THREAD

**Issue by flar** [flutter/flutter#57680]
While working on fixing the cached child used in OpacityLayer (see https://github.com/flutter/engine/pull/17914) I discovered that the way we perform Preroll can lead to a parent caching an entire tree, but a child of that parent also caching its portion even though the child's cached entry will not be used during Paint.

The reason for this is that when a parent caches its subtree then we will not be recursing to the children during the Paint cycle, but we always recurse to the children on a Preroll cycle and the decision and actions to cache a layer are made during Preroll. Thus, the children always see a Preroll - and may decide to cache themselves at that point - even if they won't be Painted. There is no information currently passed down to indicate to them that they won't be eventually Painted.

While we might be able to avoid a Preroll recursion if the child layers were reused from a previous frame and have already done the Preroll processing, the actual role of Preroll in the rasterization process isn't well defined enough to understand the implications of avoiding a fresh preroll on every frame - for instance, the preroll actions might change due to CTM (easy to notice and account for) and changes in embedder status and whether we are rasterizing the frame for display or snapshot (both harder to account for).

A simpler solution may be to just null out the RasterCache when recursing to children if a given layer is planning on doing its own caching of the full subtree. We'd still need to investigate the implications of that change, though, as decisions about whether to cache a given layer are usually made after the Preroll recursion to the children so at the time when we pass the PrerollContext to the children, the decision to cache a given layer is still speculative at that point.

**Comment by flar** [comment]
As a data point, hacking in the "null out the RasterCache for the children" type of solution into my fix for the OpacityLayer benchmark fix improved the 99%/worst frame times about 10% and the average and 90% about 4-5%, but in that case the child was only doing picture caching which ended up not adding a cache entry because a picture is only cached when its entry is painted multiple times and the lack of recursion during Paint() meant that we were only saving the additional calls to `RasterCache::Prepare`. If the child in that benchmark contained a layer that was doing its own layer caching, then the savings would be greater. More benchmarking and testing is needed to see how much that could save.

**Comment by pedromassangocode** [comment]
I'm wondering if there have been some work around this issue in the last months

**Comment by flar** [comment]
This was fixed by https://github.com/flutter/engine/pull/31892
