### ISSUE TITLE
flutter all widgets on screen hides when keyboard appears

### ISSUE THREAD

**Issue by AmirAhmedDarrag** [flutter/flutter#57681]

**Comment by AirborneEagle** [comment]
@AmirAhmedDarrag 
Please provide:
- the minimum code to reproduce this.
- `flutter doctor -v` output
- any applicable stack traces

**Comment by TahaTesser** [comment]
Hi @AmirAhmedDarrag 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
