### ISSUE TITLE
High GPU consumption with Rive/Flare Animation 

### ISSUE THREAD

**Issue by jasonch99** [flutter/flutter#57686]
High GPU consumption when playing a Rive/Flare animation.
Tested on Google Nest hub device and saw GPU cost ~50-60%.
The recorded SKP showed lots of drawPath and clipPath.

Minimal reproduction app : [https://github.com/jasonch99/testRiveAnimation](https://github.com/jasonch99/testRiveAnimation)
The app simply loads and plays the animation.

<img width="353" alt="Screen Shot 2020-05-20 at 1 10 15 PM" src="https://user-images.githubusercontent.com/65674463/82492607-54b55600-9a9b-11ea-9103-13aea5a9e2dd.png">

**Comment by liyuqian** [comment]
How did you measure the GPU usage, @jasonch99 ? I'm having a little difficulty in finding an Android tool that can report the GPU usage.

**Comment by jasonch99** [comment]
The GPU usage I measured was on Nest Hub device with this command
cat /sys/class/mpgpu/utilization

I am not sure if there is anything similar on Android.

**Comment by zanderso** [comment]
@liyuqian is this issue actionable?

**Comment by liyuqian** [comment]
Yes, the Android team just told me how to measure GPU usage on Android. I'll take some time to investigate and perhaps schedule a meeting with Rive/Flare.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by liyuqian** [comment]
I ran `python $ANDROID_SDK_ROOT/platform-tools/systrace/systrace.py -t 10 freq` and checked the `gfx3d_clk_src` frequency on my Moto G4. The device has Adreno 405 GPU with a max frequency of 550MHz. The traced frequency is constantly above 400MHz as shown in the screeshot:
<img width="1472" alt="Screen Shot 2020-11-12 at 8 29 14 PM" src="https://user-images.githubusercontent.com/22987568/99028883-d9060480-2525-11eb-9667-b23712387535.png">

The frequency would be a good indicator of the GPU usage on Android. So the high usage not only happens on Nest Hub, but also on normal Android devices.

After checking with `flutter run ... --trace-skia`, I found that the frame rasterization time is constantly above 30ms. Two paths take more than 1ms/path to finish `SkCanvas::drawPath` call before even calling `SkCanvas::flush`.

<img width="1551" alt="Screen Shot 2020-11-12 at 8 34 20 PM" src="https://user-images.githubusercontent.com/22987568/99029115-7e20dd00-2526-11eb-9252-3fd4f6056e91.png">

I suspect it's related with the path that's either drawn with saveLayer blurs. See the attached SKP and its 14th draw op `DrawPath` when opened with https://debugger.skia.org
[flutter_02.skp.zip](https://github.com/flutter/flutter/files/5534771/flutter_02.skp.zip)

**Comment by liyuqian** [comment]
@jasonch99 : can you please check the GPU usage can be reduced by removing and tweaking some of those expensive paths in the Rive animation? If those path or effects can't be removed, maybe we need to loop in Skia or Rive team to figure out if there's any optimization to do. One possible optimization is to enable more raster cache on Rive paths (e.g., the blurred path seem to be static to me). CC @luigi-rosso who just discussed the raster cache with us yesterday about Jim's promising work on https://github.com/flutter/engine/pull/21943.

**Comment by jasonch99** [comment]
Is the expensive part the shadow here?
<img width="906" alt="Screen Shot 2020-11-13 at 11 46 29 AM" src="https://user-images.githubusercontent.com/65674463/99114599-e8c52d80-25a5-11eb-8364-97c5bd2ec6c9.png">

**Comment by liyuqian** [comment]
Yes, that's my guess.

**Comment by jasonch99** [comment]
I tested the same animation with no blur, it reduced the GPU cost.

**Comment by jasonch99** [comment]
We can remove the shadow blur for our animations.

liyuqian@, assigning this back to you to see if we want to implement the raster cache solution you mentioned earlier in case other animations may need it.

**Comment by zanderso** [comment]
I'm going to close this. It sounds like that current issue is resolved, and if we need to enable more raster caching of Rive paths, we can track that in a separate, new issue. Please feel free to reopen with further details if I'm mistaken.
