### ISSUE TITLE
Should detect the case where two widgets both write to the same storage identifier from the same subtree

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#577]
Reduced test case: https://gist.github.com/collinjackson/6a46f0b471a7a9a82c19

Scroll down, tap the purple square, then use the back button to return to the original page

**Comment by collinjackson** [comment]
![screen](https://cloud.githubusercontent.com/assets/394889/11381402/bf587bec-92b0-11e5-93da-f3e6a62f6fbb.png)

**Comment by collinjackson** [comment]
I figured out that the problem is that when there are nested Blocks, the inner Block gets the scroll position of the outer Block when the HeroController is trying to reconstruct the position of the hero element. We should traverse the whole tree and throw and error if we detect >1 element that matches the storage, asking the developer to add keys to the similar elements to disambiguate them.

**Comment by Hixie** [comment]
Should be easy enough to catch that.

**Comment by Hixie** [comment]
I'm unassigning this from me just because I'm not going to get to it before the a11y bug which may take a few days, and I don't want this to be a licked cookie. Happy to add this after though if nobody has gotten to it before then.

**Comment by Hixie** [comment]
I'm not really sure how to do this. You have to only look at widgets that actually store data; it doesn't matter if others conflict. But you can't just store a reference to the widget that stored the data because it might be different the next time it reads the data.

**Comment by sethladd** [comment]
Do we still plan to address this in the framework?

**Comment by Hixie** [comment]
Yes.

**Comment by Hixie** [comment]
@HansMuller can you have a look at this one? If you can think of an easy way to catch this today, go for it. Otherwise close it.

**Comment by HansMuller** [comment]
We're no long storing scroll offsets unless you add PageStorageKeys. So this sort of thing will not happen unless you're sloppy with the keys. In cases just like this, where no page storage keys were provided, scroll offsets will not collide.

It might be possible to detect cases where the developer has accidentally caused a collision by, for example, using the same PageStorageKey for more than one scrollable subtree.  So far, I don't think doing so is really needed.
