### ISSUE TITLE
FileTests in fml_tests are failing on Fuchsia

### ISSUE THREAD

**Issue by arbreng** [flutter/flutter#57709]
They are filtered out in run_tests.sh but fail when running fml_tests manually

**Comment by arbreng** [comment]
https://github.com/flutter/engine/pull/18320

**Comment by arbreng** [comment]
FileTest.CanTruncateAndWrite and FileTest.CreateDirectoryStructure are still filtered

**Comment by chinmaygarde** [comment]
@arbreng: These just bottom out to `ftruncate` calls. Can we investigate why this would be an issue on Fuchsia? This test is [still disabled](https://github.com/flutter/engine/blob/d21cfd90ad19cb5745ba8030e023bbb5f93fd0a8/testing/fuchsia/test_suites.yaml#L7).

**Comment by arbreng** [comment]
Filed https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=81676 so we can triage internally.  Closing this issue.
