### ISSUE TITLE
an annotation error in  engine/lib/ui/painting.dart

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#57706]
location:  engine/lib/ui/painting.dart : 2609

![image](https://user-images.githubusercontent.com/26687012/82510722-deb5fb00-9b3d-11ea-82d4-5d2a542629c0.png)

`ColorFilter.matrix` will return a type of `ColorFilter`, here is ColorMatrix. You can't  find  any class named with ColorMatrix. It maybe a little mistake.

**Comment by buf1024** [comment]
This is the comment of the source code, the comment part,
```dart
const ColorMatrix = ColorFilter.matrix...
..
```
that is to emphasize the return type is a **matrix**, and that **matrix** is use for `ColorFilter`.

so, I don't think this is an error, and it some what makes the commentary more clearly.

**Comment by toly1994328** [comment]
> This is the comment of the source code, the comment part,
> 
> ```dart
> const ColorMatrix = ColorFilter.matrix...
> ..
> ```
> 
> that is to emphasize the return type is a **matrix**, and that **matrix** is use for `ColorFilter`.
> 
> so, I don't think this is an error, and it some what makes the commentary more clearly.

Whatever, it’s a grammar mistakes. Developer can find another way to show this mean of matrix. Not here.

**Comment by pedromassangocode** [comment]
Can confirm that this was fixed by https://github.com/flutter/engine/pull/19905.
