### ISSUE TITLE
Floating SliverAppBar isn't working in conjunction with RefreshIndicator

### ISSUE THREAD

**Issue by sunyatax** [flutter/flutter#57700]
Hey all -- 

So, I've been trying to produce a feed that has a floating sliver appbar and enables me to only refresh the feed below the appbar (otherwise the UX feels clunky). I have either been able to **1)** wrap just the feed of content with a RefreshIndicator, but not have the sliver appbar float or **2)** Have the sliver appbar float, but wrap both the appbar and the feed in the RefreshIndicator. 

This is because in the 1st scenario, I'm using a NestedScrollView where the headerSliverBuilder holds the appbar and a CustomScrollView wrapped with the RefreshIndicator holds the feed. In the 2nd scenario, both the appbar and feed are under a CustomSrollView that is wrapped with a RefreshIndicator. Neither fully produce the desired result, but scenario one (pasted below) is closer to what I'm trying to build.

Ultimately, this may be an issue where I just have to wait this out as I'm aware the Flutter team is working on getting floating appbar working in a NestedScrollView #17518. However, I wonder if there is another way around this issue that I could use in the interim. For example, somehow enabling a direct child of the CustomScrollView to be some sort of refresh indicator? 

Would be great to hear people's recommendation on how to move forward. Cheers.

```
        return NestedScrollView(
          headerSliverBuilder: (context, innerBoxScrolled) => [
            // SliverPersistentHeader made into custom appbar with pinned
            // set to false and floating set to true
            AppBarWrapper(
              title: state is CollectivePopulated ? state.name : 'JUNTO',
            ),
          ],
          body: CollectiveFeedRefresh(
            child: CustomScrollView(
              slivers: <Widget>[
                // Empty SliverToBoxAdaptor is necessary, otherwise switching
                //  between single and two column layouts creates an issue.
                const SliverToBoxAdapter(),
                if (state is CollectivePopulated)
                  // Collective Feed (either single or two column layout)
                  CollectivePopulatedList(state),
                if (state is CollectivePopulated && state.loadingMore == true)
                  const ExpressionProgressIndicator(),
                if (state is CollectiveLoading)
                  const ExpressionProgressIndicator(),
                if (canFetch)
                  // pagination
                  SliverToBoxAdapter(
                    child: FetchMoreButton(
                      onPressed: () {
                        context.bloc<CollectiveBloc>().add(
                              FetchMoreCollective(),
                            );
                      },
                    ),
                  ),
              ],
            ),
          ),
        );
```

**Comment by TahaTesser** [comment]
Hi @sunyatax 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem, your code is not runnable  and incomplete 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
