### ISSUE TITLE
[e2e_macos] ci seems to ignore publish check for e2e_macos plugin

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#57717]
e2e_macos plugin has 2 warnings when I try to publish locally; however, the CI seems to ignore the warnings. We need to see why CI fails the warnings, and also to see if it is also ignored for other plugins.

**Comment by goderbauer** [comment]
@cyanglaz @dnfield Is this issue still relevant? Now that integration_test is part of the SDK there shouldn't be a reason to publish the package anymore? If this still is a problem, could you add some more context around what needs to happen to resolve it?
