### ISSUE TITLE
IOS Issue for Google_Sign_In plugin

### ISSUE THREAD

**Issue by Satish-Eruvaka** [flutter/flutter#57719]
For android it was working perfect, but for ios Aalways getting this issue even I attached GoogleService-Info.plist file to runner and add reversed client id to Info.plist file still not working.

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in google_sign_in(FLTGoogleSignInPlugin.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TahaTesser** [comment]
Hi @Satish-Eruvaka 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
