### ISSUE TITLE
R8 shrink causing flutter_local_notifications plugin to crash when a notification is added. 

### ISSUE THREAD

**Issue by nicomoshi** [flutter/flutter#57710]
I'm getting this backtrace from google play store crash report. The crash is being caused when a new notification is added to the device using `flutter_local_notifications: ^1.4.3` . I've checked with multiple devices and the crash happens in all of them. Since I kept having this issue only with releases, I decided to directly install the application with and without R8 shrinking. To my surprise, it works perfectly fine without R8 shrinking and with R8 it keeps having the same issue.

`
backtrace:
  #00  pc 0000000000081f74  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #01  pc 00000000002af4f4  /data/app/com.myapp-_RguYrAo3qp4Bt8ZtnQu5Q==/split_config.arm64_v8a.apk!libflutter.so (offset 0x6c3000)
`

I wonder if this is an issue caused by something I missed or just R8 incompatibility issues with flutter_local_notifications.

**Comment by TahaTesser** [comment]
Hi @nicomoshi 
For issue related to the 3rd party plugin [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) you may want to open an issue in the dedicated [GitHub](https://github.com/MaikuB/flutter_local_notifications/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by nicomoshi** [comment]
This is a problem with Flutter since R8 shrinking may not support flutter_local_notifications. I've read a claim that R8 will be compulsory in the future so they must fix this otherwise there will be issues.

**Comment by TahaTesser** [comment]
Hi @nicomoshi 
You can create issue o n their Github as mentioned above
