### ISSUE TITLE
Cleanup source-level ignores that work-around evolving language features

### ISSUE THREAD

**Issue by pq** [flutter/flutter#5771]
In the interest of integrating new Dart SDKs, we have had (and will continue to have) to make local changes to work around / accommodate evolving language features.  This issue tracks the effort to cleanup these ignores as the language continues to evolve and the need to use them is lessened by features or new idioms.

Analysis errors that are suppressed as work-arounds (or otherwise benefit from a revisit) should reference this issue like so:

```
Rectangle : growRectangle, // ignore: error_code, https://github.com/flutter/flutter/issues/5771
```

To help keep us honest, we'll add a count of ignored issues to `flutter analyze` (and possibly add it to the dashboard) [#5772].

References:
- PR where a lot of this conversation began: https://github.com/flutter/flutter/pull/5689
- Doc exploring language ideas:  [Flutter covariant callbacks](https://docs.google.com/a/google.com/document/d/1RqqM-UMp3WGygYZirHqpwW-nZJpbWw9IVf1UJy6kxZc/edit?usp=sharing)

**Comment by pq** [comment]
FYI @leafpetersen,@jmesserly

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this bug.  @pq  is this still something you want to track?

**Comment by pq** [comment]
Maybe not.  I think @Hixie is tracking this elsewhere.  Let's close.  These are only the tip of the iceberg anyway.
