### ISSUE TITLE
Camera plugin issue

### ISSUE THREAD

**Issue by Shelly2xl** [flutter/flutter#57715]
Hello ，today I use camera in the Flutter project, I added camera: ^ 0.5.8 + 1 in pubspec.yaml, then 
an error occurred ,/CameraPlugin.java:54: error: incompatible type: View cannot be converted to TextureRegistry registrar.view ());
The dart version used is 2.7.0. I don't know how it happened?

**Comment by TahaTesser** [comment]
Hi @Shelly2xl 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
