### ISSUE TITLE
Track number of ignored errors in source.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#5772]
Follow-on from #5771, we'd like a way to track source-level `ignore`s so that we can be sure and cycle back and clean them up.

A few thoughts on implementation.
- `flutter analyze` should report this number, and
- the dashboard should perhaps display it
- they could be collected by a `grep`, or
- as the result of a special `lint` (as we do for API docs)

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
I will help you write a test and add a card to the dashboard.

[Docs](https://github.com/flutter/flutter/tree/master/dev/devicelab#writing-tests), [Example](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/hot_mode_dev_cycle__benchmark.dart)

Please don't hesitate to ping me if you have any questions.

**Comment by eseidelGoogle** [comment]
I believe @Hixie added a metric which tracks ignores (in a dollar amount)? :)

**Comment by pq** [comment]
> I believe @Hixie added a metric which tracks ignores (in a dollar amount)? :)

I know.  It's hilarious.  In any event, this is a bit stale.  Closing.
