### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by khush706** [flutter/flutter#57739]
Hey
I want to use camera tools like
Flash
Tap To Focus
Brightness Exposure Control
In camera so how can I implement this
It's not in your camera plugin
And there is no other plugin in pub.dev 
Please help me 
Thanks & Regards
Khush Jain

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
