### ISSUE TITLE
SystemNavigator.pop() for iOS should Compatible with most apps

### ISSUE THREAD

**Issue by mumenma** [flutter/flutter#57734]
Calling SystemNavigator.pop() from your Dart code invokes the following iOS code:
```
UIViewController* viewController = [UIApplication sharedApplication].keyWindow.rootViewController;
  if ([viewController isKindOfClass:[UINavigationController class]]) {
    [((UINavigationController*)viewController) popViewControllerAnimated:NO];
}
```
But most of apps are more complex, there is also lack of the general structure of iOS itself: UITabBarController.
I think we should do like:
```
if (self.navigationController) {
     [self.navigationController popViewControllerAnimated:YES];
}
```

**Comment by iapicca** [comment]
Hi @mumenma 
I feel that yours is more a proposal or a feature request 
rather than a bug report, is that the case?

If so please provide more details about how this change would improve flutter 
and feel free to submit a PR if you feel to do so.

Thank you
