### ISSUE TITLE
How to access assets from an .a statically linked library

### ISSUE THREAD

**Issue by ericmcbride** [flutter/flutter#57742]
I am having issues using a Rust statically linked library that has a dependency on txt files.  I can access it fine using raw Dart, but once i try to use iOS in flutter it will not work.  The assets are in the pubspec.yaml, and in the xcode project, but I keep getting an error back from the statically linked file that the directory doesn't exist.  Any help would be appreciated.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
