### ISSUE TITLE
flutter_gallery_ios32__transition_perf test consistently failing with VMServiceFlutterDriver error

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#57756]
Full stack trace for the error is at: https://gist.github.com/iskakaushik/fef32af4d559ee0f5450ec65f07f6a16

```
2020-05-18T14:28:09.819332: stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
2020-05-18T14:28:09.819559: stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
```

This seems to be happening on slower/older devices, i.e, iPhone 4S in our dashboard and @jason-simmons'  Moto G4. (also referenced in https://github.com/flutter/flutter/issues/57586#issuecomment-632295090)

These tests started to become consistently red from consistently green starting: https://github.com/flutter/flutter/pull/57402

**Comment by jason-simmons** [comment]
I tried looking at some `Instance of '_WebSocketImpl' is closed with an unexpected code 1005` failures that I saw while running this benchmark on a Linux/Android setup.

The socket closure happened while the driver script was invoking `getVMTimeline`.  Downloading the timeline data was taking over 30 seconds.

On the device side, the VM service in the app process was successfully generating the timeline JSON and writing it to the socket as expected.  But it looked like the app process was being terminated by a SIGKILL before the driver script received all the data.  I don't know who is sending the SIGKILL.

**Comment by zanderso** [comment]
@jason-simmons Could the app be getting sent SIGKILL by the OS for some perceived misbehavior?

**Comment by zanderso** [comment]
It looks like the tree is closed on this flake again. I noted in chat that it became noticeably flakier after the engine roll here: https://github.com/flutter/flutter/commit/68073a098efbd5e717347a72bfffa6a69178dd99. Team velocity is affected by this issue, so I am bumping the priority to P1 and assigning @jason-simmons to investigate further.

/cc @godofredoc in case he has some hints about where the SIGKILL might be coming from.

@jason-simmons please assign back to me if you won't be able to get to this sometime this week. Thanks!

**Comment by zanderso** [comment]
Ah, sorry, it's `new_gallery__transition_perf` whose failure is currently closing the tree on this issue, which I guess we can possibly conclude is affecting multiple benchmarks.

**Comment by jonahwilliams** [comment]
I'm going to make an educated guess that Android itself is sending the SIGKILL, it has similar behavior if you attempt to send "a lot" of data over the VM Service or even through print. In the Flutter framework, the print wrapper throttles output for this reason: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/print.dart#L43

If this is the case, the solution is to add pagination to the timeline request somehow and download in chunks.

**Comment by jonahwilliams** [comment]
Either that, or some component in the Dart start is being overwhelmed and doing something similar

**Comment by zanderso** [comment]
@bkonyi Do you know where a good place would be to experiment with throttling the VM's response to a getVMTimeline VM service request?

**Comment by jason-simmons** [comment]
Looked some more at this benchmark.  I think the app process on the device is being killed because it is reaching a memory limit.  The payload of the `getVMTimeline` service RPC response is 110MB, and the app process' VmSize can approach 2GB while serializing the response.

The timeline chunking patch landed by @jonahwilliams reduces peak memory consumption and appears to make the benchmark much more likely to run to completion.

**Comment by zanderso** [comment]
@jason-simmons thanks for digging deeper, and thanks @jonahwilliams for the fix. Since neither flutter_gallery_ios32__transition_perf nor new_gallery__transition_perf has flaked since Jonah's change, I think we should leave the chunking in place, and remove the flaky mark from flutter_gallery_ios32__transition_perf.
