### ISSUE TITLE
Linux LUCI bots with display and GPU

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#57759]
Most of the integration tests and unit tests Flutter for Web team can work using headless mode Chrome. However for a small part of the tests we need screenshots and no-headless tests.

Can we add a set of Linux LUCI bots with display and GPU?

**Comment by jonahwilliams** [comment]
The service worker tests also need non-headless chrome. Currently these are manual tests

**Comment by godofredoc** [comment]
obsolete
