### ISSUE TITLE
VS Code/Flutter/Android - Keystore file not set for signing config release

### ISSUE THREAD

**Issue by Alcarsil** [flutter/flutter#57761]
## Steps to Reproduce

1. Run `flutter build apk` on VS Code. Or, 'flutter build apk --release'. Or even, 'fluttler build appbundle' there.

2. I've got the same problem:

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':app:validateSigningRelease'.

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 35s Running Gradle task 'assembleRelease'... Running Gradle task 'assembleRelease'... Done 36,0s Gradle task assembleRelease failed with exit code 1

3. I followed those steps to build apk on VS Code: https://flutter.dev/docs/deployment/android

**Expected results: My Flutter app is ok. I need an apk file to publish it on Google Play Store** 

**Actual results: Google Play Store only accepts release versions** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by snwagbata** [comment]
Hey there, please verify that you have followed these steps
https://flutter.dev/docs/deployment/android#create-a-keystore
https://flutter.dev/docs/deployment/android#reference-the-keystore-from-the-app
https://flutter.dev/docs/deployment/android#configure-signing-in-gradle

**Comment by Alcarsil** [comment]
Hey there, yes I've already followed those steps.

**Comment by snwagbata** [comment]
Please post your build.gradle at `<app dir>/android/app/build.gradle` and your key.properties file at `<app dir>/android/key.properties`.
Please ensure to obscure your password before posting.

**Comment by Alcarsil** [comment]
They are always there (??????)

**Comment by snwagbata** [comment]
I meant that you should post the code from those files here on GitHub

**Comment by TahaTesser** [comment]
Hi @snwagbata 
Just created a project

Added key.properties in ### flutter_app -> android -> key.properties
```
storePassword=20202020
keyPassword=20202020
keyAlias=alias
storeFile=key.jks
```

and added key.jks in flutter_app -> android -> app ->  key.jks

then `build.gradle` 
```

   def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }


android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.dev_flutter"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
   signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
}

```
and then execute `flutter build apk --release -v` and release apk is built with no issues

**Comment by Alcarsil** [comment]
The answer is Android Studio.

**Comment by harshadghanekar2000** [comment]
Not able to solve this issue. Please explain how to solve this ?

**Comment by djsimp** [comment]
I had this same issue. The solution for me was to move the keystore to a directory outside the project. Then the build command was able to find the keystore.
