### ISSUE TITLE
dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart fails

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#5776]
## Steps to Reproduce

Running layout_bench.dart with top of tree engine and framework on iOS in any mode.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/zra/flutter/flutter
    • Framework revision 99a9bbbe7c (3 hours ago), 2016-09-08 12:14:24
    • Engine revision d3ba01d8a4
    • Tools Dart version 1.19.0-dev.5.0

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

[✓] Connected devices
    • FlyPhone 6S Plus • 7205478da5afd4440c897e3a86a0933faa847f99 • ios

## Logs and Crash Reports

The following NoSuchMethodError was thrown during a scheduler callback:
The null object does not have a method 'markNeedsBuild'.

NoSuchMethodError: method not found: 'markNeedsBuild'
Receiver: null
Arguments: []

When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      State.setState (package:flutter/src/widgets/framework.dart:840)
#3      _TabBarState._layoutChanged.<anonymous closure> (package:flutter/src/material/tabs.dart:980)
#4      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:541)
#5      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:503)
#6      LiveTestWidgetsFlutterBinding.handleBeginFrame (package:flutter_test/src/binding.dart:605)
#7      _beginFrame (file:///Users/zra/flutter/flutter/bin/cache/pkg/sky_engine/dart_ui/hooks.dart:48)

**Comment by Hixie** [comment]
Weird. I'll take a look.
