### ISSUE TITLE
[tool][Android 7 ONLY] Android 7 devices stuck on "Waiting for observatory port to be available..."

### ISSUE THREAD

**Issue by snwagbata** [flutter/flutter#57766]
I've been experiencing this issue since 1.12 version of flutter and have tried suggestions such as `flutter clean`. Flutter run works correctly and installs app however it stops at "Waiting for observatory port to be available...". I decided to try running the app on a different device (Android 8.1) and flutter run works correctly and prints a link to the observatory debugger and profiler. 

I've looked at other issues on this such as #33214, however my AndroidManifest.xml and MainActivity.kt package name are not out of sync.

I saw other issues like: #51797, #51269 , which made me realize that the one thing these other issues had in common with mine was that we were all running our app on Android 7.

All these issues: #51269, #51797, keep getting marked as a duplicate of #33214 however no one is yet to realize the similarities of those issues were that the app was being run on Android 7.

## Steps to Reproduce

1. Run a flutter app on debug mode on any android 7 device
2. Run the same app on any later versions of Android

## Logs

flutter run on Android 7(API 24): https://pastebin.com/Q1Rb6y40

flutter run on Android 8.1: https://pastebin.com/0PPCUPaN

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\cn\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\cn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • LGMP260 • LGMP26015abdc78 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @snwagbata 
I think you are making a good point
as the issue specific for android 7 doesn't seem to be an isolated [case](https://github.com/flutter/flutter/issues/57783).
I'd like to keep the issue open 
to address the problem occurring specifically on android 7
Thank you for your contribution

**Comment by jamesdhope** [comment]
Similar issue - any further information on this please?

**Comment by snwagbata** [comment]
@iapicca I just updated Flutter to v 1.20.0 and it seems the issue has been fixed!

**Comment by iapicca** [comment]
Thanks @snwagbata
@TahaTesser can you please close the issue

**Comment by TahaTesser** [comment]
Thanks @iapicca  @snwagbata 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
