### ISSUE TITLE
[google_sign_in] [android] Getting the following error

### ISSUE THREAD

**Issue by pazhut** [flutter/flutter#57779]
Hi

i am getting the following error:
I/flutter (16640): event ClickedGoogleSignIn
I/flutter (16640): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (16640): <asynchronous suspension>
I/flutter (16640): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (16640): #2      MethodChannelGoogleSignIn.init (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:28:20)
I/flutter (16640): #3      GoogleSignIn._ensureInitialized (package:google_sign_in/google_sign_in.dart:249:62)
I/flutter (16640): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:231:11)
I/flutter (16640): #5      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:297:16)
I/flutter (16640): #6      _rootRunUnary (dart:async/zone.dart:1192:38)
I/flutter (16640): #7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
I/flutter (16640): #8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
I/flutter (16640): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
I/flutter (16640): #10     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
I/flutter (16640): #11     Future._addListener.<anonymous c

i am not sure why is this happening, i have two Android apps, one is working and the other not, i checked my Firebase setup and the Google API Outh consent, it seems to be OK and as i said one app is working and the other not

Thanks

**Comment by TahaTesser** [comment]
Hi @pazhut 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by pazhut** [comment]
Thanks for your reply, the problem got solved it was related issues in the
AndroidManifest.xml file, i will close the issue for now
