### ISSUE TITLE
"Invalid argument(s): Cannot find executable forflutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.".

### ISSUE THREAD

**Issue by nguyentrunghieutcu** [flutter/flutter#57772]
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.".
A crash report has been written to flutter_05.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/Jf23W

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jf23l

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by TahaTesser** [comment]
Hi @nguyentrunghieutcu 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@nguyentrunghieutcu 
please follow up on https://github.com/flutter/flutter/issues/57859, closing as duplicate,
If you disagree, please write in the comments and I will reopen it
