### ISSUE TITLE
What is the roadmap of FlutterForWindows ?

### ISSUE THREAD

**Issue by towik** [flutter/flutter#57794]
When will the release mode for windows be supported, is there a more specific time ? Do we have a confirmed timeline for FlutterForWindows's alpha release, beta release, stable release ?

**Comment by kangwang1988** [comment]
@csells

**Comment by Zazo032** [comment]
Release (and profile) modes for Windows are being added in https://github.com/flutter/flutter/pull/57749

More info can be found here:
- [Windows Preview](https://github.com/flutter/flutter/projects/37)
- [Windows Releasable](https://github.com/flutter/flutter/projects/55)

**Comment by csells** [comment]
We've made no public announcement about the release date for the Windows alpha. We're actively working on it.

**Comment by stuartmorgan** [comment]
Flutter's roadmap is at https://github.com/flutter/flutter/wiki/Roadmap

Closing as there is no issue or feature request to track here.
