### ISSUE TITLE
tester.enterText at specific position of TextInput without reset of previous input value

### ISSUE THREAD

**Issue by bionara** [flutter/flutter#57792]
Testing's enterText simply sets the text input's input to that passed in:

```
/// Simulates the user typing the given text.
  void enterText(String text) {
    assert(isRegistered);
    updateEditingValue(TextEditingValue(
      text: text,
    ));
  }
```

1. this doesn't simulate a user typing text - more like a "select all, paste to replace" job.

2. this makes it not possible to test the following cases:

"given I click at a given point in the input text string, I should be able to to add text there and check the value". This isn't possible to test:

```
final finderTextInput = find.byType(TextInput);
await tester.enterText(finderTextInput, 'helloworld');
// text is 'helloworld'
```

Then if I wanted to simulate the user clicking at pos 5 to add a space, adding a space, then check the output, I can't:

```
final finderTextInput = find.byType(TextInput);
controller.selection = TextSelection.collapsed(offset: 5);
await tester.enterText(finderTextInput, ' '); 
// text is ' ' but expected, after second textinput at pos 5, 'hello world'
```

Any way to achieve this in testing?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
