### ISSUE TITLE
Flutter_test from sdk is forbidden,because every version of flutter_test from sdk depends on image 2.1.12 which doesn't match any versions.

### ISSUE THREAD

**Issue by ismailnurudeen** [flutter/flutter#57804]
My projects were fine before upgrading to the recent release.
I know this issue has been closed before, here #46682 ... but it still exists in the latest version.
Although removing _flutter_test_ from dependencies solves the problem,but it causes issues in the _widget_test_ file.

```
dev_dependencies:
  flutter_test:
    sdk: flutter
```
## Steps to Reproduce

Just created a new flutter project in VSCode with _flutter v1.17.1_ and the issue occurs after running `pub get` or `flutter packages get`
## Logs

```
[openshelf] flutter.bat pub get
Running "flutter pub get" in openshelf...                       
Because every version of flutter_test from sdk depends on image 2.1.12 which doesn't match any versions, flutter_test from sdk is forbidden.

So, because openshelf depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because openshelf depends on flutter_test any from sdk, version solving failed.)
exit code 1

```

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\El Nuru\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\El Nuru\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment]
Hi @ismailnurudeen 
this issue should have been patched with the latest `dev`
it is possible that the fix reached the latest `beta` already;
could you please run
```console
flutter channel beta
flutter upgrade --force
```
if the issue persists
```console
flutter channel dev
flutter upgrade --force
```
Let me know if this solves the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by Rudra370** [comment]
> Hi @ismailnurudeen
> this issue should have been patched with the latest `dev`
> it is possible that the fix reached the latest `beta` already;
> could you please run
> 
> ```
> flutter channel beta
> flutter upgrade --force
> ```
> 
> if the issue persists
> 
> ```
> flutter channel dev
> flutter upgrade --force
> ```
> 
> Let me know if this solves the problem
> Thank you

tried this and got new error - 

PowerShell executable not found.
       Either pwsh.exe or PowerShell.exe must be in your PATH.
Setting VM flags failed: Unrecognized flags: disable-dart-dev

now even flutter command is not working

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by shinriyo** [comment]
how to check `flutter_test` version?
`flutter_driver` also
