### ISSUE TITLE
Why does my sdkmanager always vanish?

### ISSUE THREAD

**Issue by dinhan1192** [flutter/flutter#57808]
My problem is: Every time I run this: flutter doctor --android-licenses --verbose, I will receive this:

![image](https://user-images.githubusercontent.com/42635147/82674957-3d7a9200-9c6e-11ea-91b6-9e2996730c71.png)

And when I get into the tools\bin folder, the sdkmanager.bat will vanish, but in fact, it was there before I run that command.

Here is my flutter doctor:
![image](https://user-images.githubusercontent.com/42635147/82675161-9cd8a200-9c6e-11ea-99fb-ee937fabc51b.png)

Well, I think that .bat file also vanish when I run flutter doctor -v too .... 
Does it mean to vanish? ...
Hope you can help me with that because I really want to build an app for my niece!!!

**Comment by VladyslavBondarenko** [comment]
Hi @dinhan1192 
please follow up on https://github.com/flutter/flutter/issues/56628,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
