### ISSUE TITLE
Allow TextStyle.apply() to change FontSize

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#57817]
## Use case
I have code that's supposed to change the `textSize` of some elements via a `LayoutBuilder` when there isn't enough space to fully render the text. When doing that I only want to change the `textSize` but not the color, fontType and other properties, that are saved in `Theme.of()`. 

## Proposal

Add a textSize parameter to `TextStyle.apply()` that changes the textSize.

**Comment by iapicca** [comment]
Hi @ChristianKleineidam 
does [copyWith](https://api.flutter.dev/flutter/material/TextTheme/copyWith.html) fit your needs?
Thank you

**Comment by ChristianKleineidam** [comment]
Creating a copy of the whole TextTheme would be excessive for my needs. I do need it on the TextStyle level.

**Comment by TahaTesser** [comment]
This is probably missing by mistake so i am gonna label this

**Comment by goderbauer** [comment]
`TextStyle` is immutable by design. If you need to change anything contained in it you'll have to create a copy as has been suggested in earlier comments.

**Comment by ChristianKleineidam** [comment]
@goderbauer : Isn't the whole point of Apply to create a copy of the TextStyle? Why shouldn't it be able to create a copy with a different textSize?

**Comment by goderbauer** [comment]
By `fontSize` do you mean the `textSize` in the TextStyle class? https://master-api.flutter.dev/flutter/painting/TextStyle/fontSize.html

You can use the TextStyle's `copyWith` function to create a new TextStyle with just the `fontSize` changed: https://master-api.flutter.dev/flutter/painting/TextStyle/copyWith.html

Can you describe how that doesn't fit your needs?

**Comment by ChristianKleineidam** [comment]
Ah, I wasn't aware that TextStyle also has a copyWith function in addition to the apply function. It's unclear to me what the difference between copyWith() and apply() is in general, but that solves me case.
