### ISSUE TITLE
1.17 Cherrypick Request - Apple Watch Extension support

### ISSUE THREAD

**Issue by harryeakins** [flutter/flutter#57818]
# Problem
Dev teams building Flutter apps with corresponding Apple Watch apps are stuck with failing flutter builds and the lack of hot restart/reload with the latest stable.

A fix for this was merged here: https://github.com/flutter/flutter/pull/51126 which made it into 1.18.0-6.0.pre, but it's not available in the stable channel.

# Proposal
Looking at the Flutter cherrypick process (https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process), I think it's reasonable to request a cherrypick for 1.17.

## Impact criteria:
This is an issue on the stable channel, affecting any customer who has an Apple Watch extension and breaks developer flow with no easy workaround.

## Risk criteria:
> Is it a manual or automated merge?

The changes merge with no conflicts on top of 1.17.1

> How many lines of code, what areas of the stack is it touching?

There are < 50 lines of code changes in the flutter_tools package. There are no changes elsewhere except for additional tests.

> Testability of the cherrypick.

The changes are well tested with integration and unit tests

## Release timing
> How close is the next beta/stable release?

We are a couple of weeks out from the previous stable release, so probably 2.5-3 months away from the next release.

**Comment by harryeakins** [comment]
Note： 
There are two commits to cherry-pick: 
* 2a903ac76300f75b6c8ea439ee47c405f1e05382
* 10aa399e1211982775bf1a80869aaae8aa8f171e

**Comment by harryeakins** [comment]
Mentioning @tauu and @jmagman who were heavily involved in the development and approval of this fix.

**Comment by tauu** [comment]
Getting the commits into stable would indeed help. As the changes only affect apps containing a watch companion, I don't see any possible problems arising from a cherry pick.

**Comment by jmagman** [comment]
Adding the label, we'll see what the Cherrypick reviewers think.

**Comment by jmagman** [comment]
Both those cherry-picks are in the beta branch at the moment.

**Comment by harryeakins** [comment]
For reference, here's a fork with the commits applied to 1.17.1: https://github.com/harryeakins/flutter/commit/10aa399e1211982775bf1a80869aaae8aa8f171e

It's working fine for me.

**Comment by pcsosinski** [comment]
Rejected from a 1.17 hotfix as this doesn't address a regression or otherwise serious bug.  thanks.

**Comment by jonahwilliams** [comment]
Closing as this was rejected
