### ISSUE TITLE
Possible to close drawer on configuration toggle?

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#5781]
In the leafy app, we have a configuration inside a drawer. We want to close the drawer when the configuration is toggled. Is there anyway to achieve this?

**Comment by eseidelGoogle** [comment]
@HansMuller or @Hixie would know.

**Comment by Hixie** [comment]
Not sure I understand the situation, but ping me at the office and I'll see what I can do to help.

**Comment by vy0592** [comment]
Thanks! pop actually solves the problem

**Comment by DaveShuckerow** [comment]
route.pop is a non-obvious solution in this case -- opening the app drawer doesn't traditionally seem like an action that would change the app routing state.  Can we get clarification on why this is the case?

**Comment by Hixie** [comment]
Opening the drawer is very much a route. You can tell because hitting the back button on Android closes it. (It's an entry in a LocalHistoryRoute, to be precise.)

**Comment by Hixie** [comment]
but yes, we should document this better

**Comment by DaveShuckerow** [comment]
That's very interesting.  Our native Android app does not close its drawer with the back button, hence my previous comment.  Looking at other material apps, they are in agreement with you.

Thank you for the clarification!
