### ISSUE TITLE
Display warning/error when building android application with build number greater than allowed value

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#57815]
Hello everyone. I have setup a CI which uses the current timestamp since epoch as the build number. It was working just fine, until today. It stopped accepting the build-number. I suppose this is a problem at handling large integer values ? Btw, our app is actually blocked upon compiling (and we cannot go back as we already published several playstore and app-store versions).

## Steps to Reproduce

1. Run `flutter create bug`.
2. flutter build appbundle -t lib/main.dart --build-name=5.44.0 --build-number=1590170586079 --release --tree-shake-icons

**Expected results:** AppBundle or APK compiles

**Actual results:** 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/nicolas/dev/xxx/android/app/build.gradle' line: 42

* What went wrong:
A problem occurred evaluating project ':app'.
> For input string: "1590170586079"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 663ms
Running Gradle task 'bundleXXX'...
Running Gradle task 'bundleXXX'... Done                  1,4s
Gradle task bundleXXX failed with exit code 1
```

and line 42 is: 
```
versionCode flutterVersionCode.toInteger()
```

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.17.1 at /Users/nicolas/dev/flutter_sdk/flutter
    • Framework revision f7a6a7906b (10 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Users/nicolas/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 201.7223.99
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • ASUS Z00A • XXX • android-x86 • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```

</details>

**Comment by jonahwilliams** [comment]
See https://developer.android.com/studio/publish/versioning.html

> Warning: The greatest value Google Play allows for versionCode is 2100000000.

Unfortunately this is not something flutter can "fix" because it is a constraint from the Android Gradle configuration, and then from the Playstore. You may need to contact Google play store support or re-release your application under a different name, I'm not really sure because this is a bit out of my ballpark.

**Comment by nicolasvac** [comment]
@jonahwilliams Understood. 
Thank you for you reply. (y)
Maybe we could make this clear in the documentation? (Like “pay attention when using timestamps because there is a limit on how playstore and app-store will handle the build namers.”). Coming from a web background had me tought timestamp could be fine.

**Comment by nicolasvac** [comment]
@jonahwilliams Understood. 
Thank you for you reply. (y)
Maybe we could make this clear in the documentation? (Like “pay attention when using timestamps because there is a limit on how playstore and app-store will handle the build namers.”). Coming from a web background had me tought timestamp could be fine.

**Comment by jonahwilliams** [comment]
We should probably parse the build number and do some validation on our end. Instead of crashing in build.gradle, we could display an error message with more context and link to the android documentation

**Comment by nicolasvac** [comment]
Yeah, great idea.
Thanks for your work @jonahwilliams.
