### ISSUE TITLE
AOT engine upload locations

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#57823]
https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders tells only where the JIT compiled engines are uploaded. Could the document be updated to also include the AOT compiled engines?
(I suspect they are already uploaded https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L1402 https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L1389)

**Comment by stuartmorgan** [comment]
> I suspect they are already uploaded

They are not.

This is the same as https://github.com/flutter/flutter/issues/44577; I'm not sure why you filed this again.

**Comment by jld3103** [comment]
Sorry forgot about it
