### ISSUE TITLE
hot reload is disable show,i enable in flutter setting and restart IDE but they continuously show disable

### ISSUE THREAD

**Issue by junaidirshad098** [flutter/flutter#57822]

**Comment by TahaTesser** [comment]
Hi @junaidirshad098 
Which IDE you're using? Was hot reload disable by default? Did you run the project first?
can you please provide your `flutter doctor -v`?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
