### ISSUE TITLE
when using camera plugin to record video in ios, the first frame may be black 

### ISSUE THREAD

**Issue by leoxchang** [flutter/flutter#57831]
when using camera plugin to record video in ios, the audio is on,the first frame will be black.but when the audio is false，this time record video,and the first frame be black question will be gone.

**Comment by TahaTesser** [comment]
Hi @leoxchang 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by leoxchang** [comment]
```flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/qiezi999/Downloads/movie/flutter
    • Framework revision f139b11009 (8 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/qiezi999/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/qiezi999/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • “zhangxinlei”的 iPhone • 4d3e7f29e8ce9f965764c856c76ccb4ee031f302 • ios • iOS 13.5

! Doctor found issues in 1 category.
```

startVideoRecord
```
Future<String> startVideoRecording() async {
    if (!controller.value.isInitialized) {
      showInSnackBar('Error: select a camera first.');
      return null;
    }

    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/cache/movies';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${_uuid.v4()}.mp4';
    videoPath = filePath;

    if (controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }

    try {
      await controller.startVideoRecording(filePath);
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    return filePath;
  }
```
stopVideoRecord
```
Future<void> stopVideoRecording() async {
    if (!controller.value.isRecordingVideo) {
      return null;
    }
    try {
      await controller.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    File videoFile = File(videoPath);
    bool exists = await videoFile.exists();
    if (!exists) {
      return null;
    }
    Navigator.push(
        context,
        CameraPageRouteBuilder(VideoViewer(
          videoPath,
          getVideoPath: getVideoPath,
        )));
  }
```

**Comment by leoxchang** [comment]
```
pubspec.yaml

camera: ^0.5.8+2
```

**Comment by TahaTesser** [comment]
Hi @leoxchang 
Trying to reproduce this issue with official example with following dependencies
```
  camera: ^0.5.8+2
  path_provider: ^1.6.9
  video_player: ^0.10.11+1
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details> 

Trying multiple times  and there is no issue iPhone XR, ohy

**Comment by leoxchang** [comment]
I change the dependencies following yours,and I tried several times,the first frame may not be black,
but it will be darker than the normal frame.

This is my record video,you will see the start may be darter,and I cut the first frame.
[http://cdn.dev.jiazhangkj.com/flutter/a.mp4](url)

[http://cdn.dev.jiazhangkj.com/flutter/1.jpg](url)

**Comment by TahaTesser** [comment]
Hi @leoxchang 
This might IOS 13.5 as it's not stable yet, i am on 13.4.5 and i haven't notice such issue
Did you experience this issue with upgrade?
Thaak you

**Comment by leoxchang** [comment]
ok,I will try another IOS phone.Thank you!

**Comment by TahaTesser** [comment]
Hi @leoxchang 
I just realised i also have 13.5 on my iPhone but black frame issue isn't reproducible. 
```
  camera: ^0.5.8+2
  path_provider: ^1.6.9
  video_player: ^0.10.11+1
```

I  also notice, frame may get black when you switch mic on/off, maybe that's causing this for you? i have recorded right after turning mic on and there was still no black frame.

Please try code sample and write the steps to reproduce the issue so i can get same. results
Thank you

**Comment by leoxchang** [comment]
Hi @TahaTesser 
I just copy the example code from camera plugin, and I tried a few phones, the iphone8 recorded right, the iphone 7p and iphone 6sp have the same issue.
 I have recorded two video from iphone7p, one have mic on, one not.
here is two video:
audio off:
[http://cdn.dev.jiazhangkj.com/flutter/no_audio.mp4](url)
audio on:
[http://cdn.dev.jiazhangkj.com/flutter/audio.mp4](url)
you will see on "audio.mp4" at about 4 seconds,the video in the demo application at the bottom-right, When the video loops to the next time,There was a black splash screen. the "no_audio.mp4” has no problem.
the cut screen:
[http://cdn.dev.jiazhangkj.com/flutter/audio_frame.png](url)

I will try iphone xr and iphone 11 later.
Thank you

**Comment by leoxchang** [comment]
I tried on iphone x, iphone xr and iphone x max, all of them recorded right. this may happene under the iphone 8 devices.

**Comment by 1xiaocainiao** [comment]
same problem， iphone 6s plus, The problem leads to the use of video player to play, the first frame is also black, how to fix

**Comment by jpiabrantes** [comment]
Same issue on iPhone 6.

**Comment by robinwkurtz** [comment]
The same problem on an iPhone 7, I only seem to have the issue when audio is enabled

**Comment by Mozyra** [comment]
Any info? Same issue on iPhone 6 ios 12.4.

**Comment by LeGoffMael** [comment]
Same on Iphone 7 ios 14.2. 
camera: ^0.7.0+2 & flutter 1.22.6.

**Comment by zeroprofit** [comment]
Same iPhone 6s Plus, iOS 12.4
camera: 0.7.0+1, Flutter 1.24.0-10.1.pre

**Comment by the-old-one** [comment]
Same issue. iPhone X, iOS 14.4.2, 
camera: 0.8.1
Flutter 2.0.4

**Comment by francisfernandez28** [comment]
Same Issue: iPhone SE 2020, IOS 14.3
camera: ^0.7.0+2
Flutter version 1.22.5

Problem when enableAudio is true

**Comment by olegys** [comment]
Use _cameraController.prepareForVideoRecording()

Prepare the capture session for video recording.
Use of this method is optional, but it may be called for performance reasons on iOS.
Preparing audio can cause a minor delay in the CameraPreview view on iOS. If video recording is intended, calling this early eliminates this delay that would otherwise be experienced when video recording is started. This operation is a no-op on Android.

**Comment by calvingit** [comment]
I got a solution from [stackoverflow answers](https://stackoverflow.com/questions/44135223/record-video-with-avassetwriter-first-frames-are-black), cut the first 1/10s frames off. 

in [CameraPlugin.m](https://github.com/flutter/plugins/blob/master/packages/camera/camera/ios/Classes/CameraPlugin.m) , [line 830](https://github.com/flutter/plugins/blob/036fb33ae18bd6a1d2af29302f2124132ca10768/packages/camera/camera/ios/Classes/CameraPlugin.m#L830)

change:

```
_videoTimeOffset = CMTimeMake(0, 1);
_audioTimeOffset = CMTimeMake(0, 1);
```
to: 
```objective-c
_videoTimeOffset = CMTimeMakeWithSeconds(1, 10);
_audioTimeOffset = CMTimeMakeWithSeconds(1, 10);
```

**Comment by dmiedev** [comment]
> Use _cameraController.prepareForVideoRecording()
> 
> Prepare the capture session for video recording. Use of this method is optional, but it may be called for performance reasons on iOS. Preparing audio can cause a minor delay in the CameraPreview view on iOS. If video recording is intended, calling this early eliminates this delay that would otherwise be experienced when video recording is started. This operation is a no-op on Android.

May I ask please at which point this should be used?

**Comment by AlexV525** [comment]
cc @BeMacized

**Comment by olegys** [comment]
> > Use _cameraController.prepareForVideoRecording()
> > Prepare the capture session for video recording. Use of this method is optional, but it may be called for performance reasons on iOS. Preparing audio can cause a minor delay in the CameraPreview view on iOS. If video recording is intended, calling this early eliminates this delay that would otherwise be experienced when video recording is started. This operation is a no-op on Android.
> 
> @olegys May I ask please at which point this should be used?

After cameraController.initialize()

**Comment by AlexV525** [comment]
> After cameraController.initialize()

The black frame still exists at some time after it's been prepared, but most of them are only with the first recording.

**Comment by gyihasz** [comment]
We also have the black video start issue.

Now, I called ```cameraController.prepareForVideoRecording()``` after ```cameraController.initialize()``` and the performance is actually better, the video record starts more smoothly, but randomly, (2 out of 3) videos start with a black frame.

According to our tests, every iPhone model is affected from iPhone 6 up to iPhone 13.

**Comment by Tom3652** [comment]
Still reproductible with the ```camera: ^0.9.4+5``` and iOS version from 12.5.8 until 15.1 (all of my devices)

**Comment by Vlas1414** [comment]
Still does not work for me with the camera: ^0.9.4+5, iOS version 15.1.1, iPhone 13, flutter: 2.8.0

**Comment by thegamingninja** [comment]
This is also an issue for me with camera version `0.9.4+5` on iOS 15.0.2, iPad Pro 9.7inch (2016). 
Calling  `cameraController.prepareForVideoRecording()` directly after `cameraController.initialize()` causes the preview to immediately turn black and stay black, and calling it directly before `cameraController.startVideoRecording()` causes it to turn black just before recording, and stay black.

**Comment by thegamingninja** [comment]
Has there been an updates on this? I don't mean to sound demanding or impatient, but this is a major issue in a first party plugin, and there's no workarounds, or alternative plugins to use at the moment.

**Comment by Vlas1414** [comment]
Still does not work for me with the camera: ^0.9.4+10, iOS version 15.2.1, iPhone 13, flutter: 2.10.0

**Comment by rahulvyas** [comment]
I'm also having the same issue. I am only able to record videos on the first launch of the app. After this, all the recordings are black videos only.

**Comment by kapil4238** [comment]
What might be the cause of black frame ?
We probably want to startSession on a video buffer - if an audio buffer arrives first, with an earlier timestamp than the first video buffer, then you'll get blank or black initial frames.

What can be  the solution? 
I think first sample buffer being "sound" should be the problem. What I tried to do is to ignore the first sample buffer if it's sound. Wait until the first "video" sample buffer comes in and then do the AVAssetWriter startWriting thing. We may solve problem by doing this.


Can we check if it works like this ?

```
- (void)captureOutput:(AVCaptureOutput *)output
    didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer
           fromConnection:(AVCaptureConnection *)connection {
  if (output == _captureVideoOutput && connection.isVideoOrientationSupported) { //specifying condition for video sample
    CVPixelBufferRef newBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
    CFRetain(newBuffer);
    CVPixelBufferRef old = _latestPixelBuffer;
    while (!OSAtomicCompareAndSwapPtrBarrier(old, newBuffer, (void **)&_latestPixelBuffer)) {
      old = _latestPixelBuffer;
    }
    if (old != nil) {
      CFRelease(old);
    }
    if (_onFrameAvailable) {
      _onFrameAvailable();
    }
  }
  if (!CMSampleBufferDataIsReady(sampleBuffer)) {
    [_methodChannel invokeMethod:errorMethod
                       arguments:@"sample buffer is not ready. Skipping sample"];
    return;
  }
  if (_isStreamingImages) {
    if (_imageStreamHandler.eventSink) {
      CVPixelBufferRef pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
      CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);

      size_t imageWidth = CVPixelBufferGetWidth(pixelBuffer);
      size_t imageHeight = CVPixelBufferGetHeight(pixelBuffer);

      NSMutableArray *planes = [NSMutableArray array];

      const Boolean isPlanar = CVPixelBufferIsPlanar(pixelBuffer);
      size_t planeCount;
      if (isPlanar) {
        planeCount = CVPixelBufferGetPlaneCount(pixelBuffer);
      } else {
        planeCount = 1;
      }

      for (int i = 0; i < planeCount; i++) {
        void *planeAddress;
        size_t bytesPerRow;
        size_t height;
        size_t width;

        if (isPlanar) {
          planeAddress = CVPixelBufferGetBaseAddressOfPlane(pixelBuffer, i);
          bytesPerRow = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, i);
          height = CVPixelBufferGetHeightOfPlane(pixelBuffer, i);
          width = CVPixelBufferGetWidthOfPlane(pixelBuffer, i);
        } else {
          planeAddress = CVPixelBufferGetBaseAddress(pixelBuffer);
          bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer);
          height = CVPixelBufferGetHeight(pixelBuffer);
          width = CVPixelBufferGetWidth(pixelBuffer);
        }

        NSNumber *length = @(bytesPerRow * height);
        NSData *bytes = [NSData dataWithBytes:planeAddress length:length.unsignedIntegerValue];

        NSMutableDictionary *planeBuffer = [NSMutableDictionary dictionary];
        planeBuffer[@"bytesPerRow"] = @(bytesPerRow);
        planeBuffer[@"width"] = @(width);
        planeBuffer[@"height"] = @(height);
        planeBuffer[@"bytes"] = [FlutterStandardTypedData typedDataWithBytes:bytes];

        [planes addObject:planeBuffer];
      }

      NSMutableDictionary *imageBuffer = [NSMutableDictionary dictionary];
      imageBuffer[@"width"] = [NSNumber numberWithUnsignedLong:imageWidth];
      imageBuffer[@"height"] = [NSNumber numberWithUnsignedLong:imageHeight];
      imageBuffer[@"format"] = @(videoFormat);
      imageBuffer[@"planes"] = planes;
      imageBuffer[@"lensAperture"] = [NSNumber numberWithFloat:[_captureDevice lensAperture]];
      Float64 exposureDuration = CMTimeGetSeconds([_captureDevice exposureDuration]);
      Float64 nsExposureDuration = 1000000000 * exposureDuration;
      imageBuffer[@"sensorExposureTime"] = [NSNumber numberWithInt:nsExposureDuration];
      imageBuffer[@"sensorSensitivity"] = [NSNumber numberWithFloat:[_captureDevice ISO]];

      _imageStreamHandler.eventSink(imageBuffer);

      CVPixelBufferUnlockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    }
  }
  if (_isRecording && !_isRecordingPaused) {
    if (_videoWriter.status == AVAssetWriterStatusFailed) {
      [_methodChannel invokeMethod:errorMethod
                         arguments:[NSString stringWithFormat:@"%@", _videoWriter.error]];
      return;
    }

    CFRetain(sampleBuffer);
    CMTime currentSampleTime = CMSampleBufferGetPresentationTimeStamp(sampleBuffer);

    if (_videoWriter.status != AVAssetWriterStatusWriting && connection.isVideoOrientationSupported) { //specifying condition for video sample
      [_videoWriter startWriting];
      [_videoWriter startSessionAtSourceTime:currentSampleTime];
    }

    if (output == _captureVideoOutput) {
        _isVideoFrameAvailable=true; //making it true
      if (_videoIsDisconnected) {
        _videoIsDisconnected = NO;

        if (_videoTimeOffset.value == 0) {
          _videoTimeOffset = CMTimeSubtract(currentSampleTime, _lastVideoSampleTime);
        } else {
          CMTime offset = CMTimeSubtract(currentSampleTime, _lastVideoSampleTime);
          _videoTimeOffset = CMTimeAdd(_videoTimeOffset, offset);
        }

        return;
      }

      _lastVideoSampleTime = currentSampleTime;

      CVPixelBufferRef nextBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
      CMTime nextSampleTime = CMTimeSubtract(_lastVideoSampleTime, _videoTimeOffset);
      [_videoAdaptor appendPixelBuffer:nextBuffer withPresentationTime:nextSampleTime];
    } else {
        if(_isVideoFrameAvailable){
            CMTime dur = CMSampleBufferGetDuration(sampleBuffer);

            if (dur.value > 0) {
              currentSampleTime = CMTimeAdd(currentSampleTime, dur);
            }

            if (_audioIsDisconnected) {
              _audioIsDisconnected = NO;

              if (_audioTimeOffset.value == 0) {
                _audioTimeOffset = CMTimeSubtract(currentSampleTime, _lastAudioSampleTime);
              } else {
                CMTime offset = CMTimeSubtract(currentSampleTime, _lastAudioSampleTime);
                _audioTimeOffset = CMTimeAdd(_audioTimeOffset, offset);
              }

              return;
            }

            _lastAudioSampleTime = currentSampleTime;

            if (_audioTimeOffset.value != 0) {
              CFRelease(sampleBuffer);
              sampleBuffer = [self adjustTime:sampleBuffer by:_audioTimeOffset];
            }

            [self newAudioSample:sampleBuffer];
        }
    }

    CFRelease(sampleBuffer);
  }
}
```
In simple terms
```
 if connection.isVideoOrientationSupported {
        // Work with video sample is video
    } else {
        // Work with audio sample is audio
    }
```

What i have did is that first i took one bool variable 
@property(assign, nonatomic) BOOL isVideoFrameAvailable;

Then i used this variables in start of this methods 
- (void)startVideoRecordingWithResult:(FLTThreadSafeFlutterResult *)result {
    _isVideoFrameAvailable=false; **//assign false in this method**
    
- (void)stopVideoRecordingWithResult:(FLTThreadSafeFlutterResult *)result {
    _isVideoFrameAvailable=false;**//assign false in this method**
    
Now the first method (void)captureOutput i have put a condition _captureVideoOutput && connection.isVideoOrientationSupported which means if video frame will arrive then it will do the work.

**Comment by kapil4238** [comment]
> I got a solution from [stackoverflow answers](https://stackoverflow.com/questions/44135223/record-video-with-avassetwriter-first-frames-are-black), cut the first 1/10s frames off.
> 
> in [CameraPlugin.m](https://github.com/flutter/plugins/blob/master/packages/camera/camera/ios/Classes/CameraPlugin.m) , [line 830](https://github.com/flutter/plugins/blob/036fb33ae18bd6a1d2af29302f2124132ca10768/packages/camera/camera/ios/Classes/CameraPlugin.m#L830)
> 
> change:
> 
> ```
> _videoTimeOffset = CMTimeMake(0, 1);
> _audioTimeOffset = CMTimeMake(0, 1);
> ```
> 
> to:
> 
> ```objc
> _videoTimeOffset = CMTimeMakeWithSeconds(1, 10);
> _audioTimeOffset = CMTimeMakeWithSeconds(1, 10);
> ```

I should say if you follow this method then for most of recording some of your frames both audio and video will get cut. Think like even if your video capturing is okay but this will cut the video.It is good for some cases where you get the black frames but if your black frames in video container is for more amount of time than this will not work.

**Comment by s-inamori** [comment]
This is a workaround for not saving the black frame.
```
    if (firstTake && Platform.isIOS) {
      // Flag for first take
      firstTake = false;
      try {
        await cameraController.startVideoRecording();
        await Future.delayed(const Duration(milliseconds: 300));
        final file = await cameraController.stopVideoRecording();
        File(file.path).deleteSync();
        await cameraController.startVideoRecording();
      } on CameraException catch (e) {
        log(e.description!);
      }
      return;
    }
```

**Comment by Vlas1414** [comment]
> ### **What might be the cause of black frame ?**
> We probably want to startSession on a video buffer - if an audio buffer arrives first, with an earlier timestamp than the first video buffer, then you'll get blank or black initial frames.
> 
> ### **What can be the solution?**
> I think first sample buffer being "sound" should be the problem. What I tried to do is to ignore the first sample buffer if it's sound. Wait until the first "video" sample buffer comes in and then do the AVAssetWriter startWriting thing. We may solve problem by doing this.
> 
> ### **Can we check if it works like this ?**
> Camera 0.9.4+4
> 
> ```
> - (void)captureOutput:(AVCaptureOutput *)output
>     didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer
>            fromConnection:(AVCaptureConnection *)connection {
>   if (output == _captureVideoOutput && connection.isVideoOrientationSupported) { //specifying condition for video sample
>     CVPixelBufferRef newBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
>     CFRetain(newBuffer);
>     CVPixelBufferRef old = _latestPixelBuffer;
>     while (!OSAtomicCompareAndSwapPtrBarrier(old, newBuffer, (void **)&_latestPixelBuffer)) {
>       old = _latestPixelBuffer;
>     }
>     if (old != nil) {
>       CFRelease(old);
>     }
>     if (_onFrameAvailable) {
>       _onFrameAvailable();
>     }
>   }
>   if (!CMSampleBufferDataIsReady(sampleBuffer)) {
>     [_methodChannel invokeMethod:errorMethod
>                        arguments:@"sample buffer is not ready. Skipping sample"];
>     return;
>   }
>   if (_isStreamingImages) {
>     if (_imageStreamHandler.eventSink) {
>       CVPixelBufferRef pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
>       CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
> 
>       size_t imageWidth = CVPixelBufferGetWidth(pixelBuffer);
>       size_t imageHeight = CVPixelBufferGetHeight(pixelBuffer);
> 
>       NSMutableArray *planes = [NSMutableArray array];
> 
>       const Boolean isPlanar = CVPixelBufferIsPlanar(pixelBuffer);
>       size_t planeCount;
>       if (isPlanar) {
>         planeCount = CVPixelBufferGetPlaneCount(pixelBuffer);
>       } else {
>         planeCount = 1;
>       }
> 
>       for (int i = 0; i < planeCount; i++) {
>         void *planeAddress;
>         size_t bytesPerRow;
>         size_t height;
>         size_t width;
> 
>         if (isPlanar) {
>           planeAddress = CVPixelBufferGetBaseAddressOfPlane(pixelBuffer, i);
>           bytesPerRow = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, i);
>           height = CVPixelBufferGetHeightOfPlane(pixelBuffer, i);
>           width = CVPixelBufferGetWidthOfPlane(pixelBuffer, i);
>         } else {
>           planeAddress = CVPixelBufferGetBaseAddress(pixelBuffer);
>           bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer);
>           height = CVPixelBufferGetHeight(pixelBuffer);
>           width = CVPixelBufferGetWidth(pixelBuffer);
>         }
> 
>         NSNumber *length = @(bytesPerRow * height);
>         NSData *bytes = [NSData dataWithBytes:planeAddress length:length.unsignedIntegerValue];
> 
>         NSMutableDictionary *planeBuffer = [NSMutableDictionary dictionary];
>         planeBuffer[@"bytesPerRow"] = @(bytesPerRow);
>         planeBuffer[@"width"] = @(width);
>         planeBuffer[@"height"] = @(height);
>         planeBuffer[@"bytes"] = [FlutterStandardTypedData typedDataWithBytes:bytes];
> 
>         [planes addObject:planeBuffer];
>       }
> 
>       NSMutableDictionary *imageBuffer = [NSMutableDictionary dictionary];
>       imageBuffer[@"width"] = [NSNumber numberWithUnsignedLong:imageWidth];
>       imageBuffer[@"height"] = [NSNumber numberWithUnsignedLong:imageHeight];
>       imageBuffer[@"format"] = @(videoFormat);
>       imageBuffer[@"planes"] = planes;
>       imageBuffer[@"lensAperture"] = [NSNumber numberWithFloat:[_captureDevice lensAperture]];
>       Float64 exposureDuration = CMTimeGetSeconds([_captureDevice exposureDuration]);
>       Float64 nsExposureDuration = 1000000000 * exposureDuration;
>       imageBuffer[@"sensorExposureTime"] = [NSNumber numberWithInt:nsExposureDuration];
>       imageBuffer[@"sensorSensitivity"] = [NSNumber numberWithFloat:[_captureDevice ISO]];
> 
>       _imageStreamHandler.eventSink(imageBuffer);
> 
>       CVPixelBufferUnlockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
>     }
>   }
>   if (_isRecording && !_isRecordingPaused) {
>     if (_videoWriter.status == AVAssetWriterStatusFailed) {
>       [_methodChannel invokeMethod:errorMethod
>                          arguments:[NSString stringWithFormat:@"%@", _videoWriter.error]];
>       return;
>     }
> 
>     CFRetain(sampleBuffer);
>     CMTime currentSampleTime = CMSampleBufferGetPresentationTimeStamp(sampleBuffer);
> 
>     if (_videoWriter.status != AVAssetWriterStatusWriting && connection.isVideoOrientationSupported) { //specifying condition for video sample
>       [_videoWriter startWriting];
>       [_videoWriter startSessionAtSourceTime:currentSampleTime];
>     }
> 
>     if (output == _captureVideoOutput) {
>         _isVideoFrameAvailable=true; //making it true
>       if (_videoIsDisconnected) {
>         _videoIsDisconnected = NO;
> 
>         if (_videoTimeOffset.value == 0) {
>           _videoTimeOffset = CMTimeSubtract(currentSampleTime, _lastVideoSampleTime);
>         } else {
>           CMTime offset = CMTimeSubtract(currentSampleTime, _lastVideoSampleTime);
>           _videoTimeOffset = CMTimeAdd(_videoTimeOffset, offset);
>         }
> 
>         return;
>       }
> 
>       _lastVideoSampleTime = currentSampleTime;
> 
>       CVPixelBufferRef nextBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
>       CMTime nextSampleTime = CMTimeSubtract(_lastVideoSampleTime, _videoTimeOffset);
>       [_videoAdaptor appendPixelBuffer:nextBuffer withPresentationTime:nextSampleTime];
>     } else {
>         if(_isVideoFrameAvailable){
>             CMTime dur = CMSampleBufferGetDuration(sampleBuffer);
> 
>             if (dur.value > 0) {
>               currentSampleTime = CMTimeAdd(currentSampleTime, dur);
>             }
> 
>             if (_audioIsDisconnected) {
>               _audioIsDisconnected = NO;
> 
>               if (_audioTimeOffset.value == 0) {
>                 _audioTimeOffset = CMTimeSubtract(currentSampleTime, _lastAudioSampleTime);
>               } else {
>                 CMTime offset = CMTimeSubtract(currentSampleTime, _lastAudioSampleTime);
>                 _audioTimeOffset = CMTimeAdd(_audioTimeOffset, offset);
>               }
> 
>               return;
>             }
> 
>             _lastAudioSampleTime = currentSampleTime;
> 
>             if (_audioTimeOffset.value != 0) {
>               CFRelease(sampleBuffer);
>               sampleBuffer = [self adjustTime:sampleBuffer by:_audioTimeOffset];
>             }
> 
>             [self newAudioSample:sampleBuffer];
>         }
>     }
> 
>     CFRelease(sampleBuffer);
>   }
> }
> ```
> 
> In simple terms
> 
> ```
>  if connection.isVideoOrientationSupported {
>         // Work with video  if sample is video
>     } else {
>         // Work with audio if sample is audio
>     }
> ```
> 
> What i have did is that first i took one bool variable @Property(assign, nonatomic) BOOL isVideoFrameAvailable;
> 
> Then i used this variables in start of this methods
> 
> * (void)startVideoRecordingWithResult:(FLTThreadSafeFlutterResult *)result {
>   _isVideoFrameAvailable=false; **//assign false in this method**
> * (void)stopVideoRecordingWithResult:(FLTThreadSafeFlutterResult *)result {
>   _isVideoFrameAvailable=false;**//assign false in this method**
> 
> Now the first method (void)captureOutput i have put a condition _captureVideoOutput && connection.isVideoOrientationSupported which means if video frame will arrive then it will do the work.

It still doesn't work for me with the camera: ^0.9.7+1, iOS version 15.5, iPhone 13, flutter: 3.0.0
But it works with the @kapil4238 solution on ios, thank you!

**Comment by misos1** [comment]
Is there a plan to finally fix this? When I worked with videos on ios I just waited for the first video sample and ignored non-video samples till that. Then when the first video sample arrives, retrieve the first timestamp using `CMSampleBufferGetPresentationTimeStamp` and call `startSessionAtSourceTime` with that timestamp. Something like this:

```
- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection
...
...
...
	if(waiting_for_first_video_sample)
	{
		if(captureOutput != video_capture_output)return;
		CMTime first_timestamp = CMSampleBufferGetPresentationTimeStamp(sampleBuffer);
		[asset_writer startSessionAtSourceTime:first_timestamp];
		waiting_for_first_video_sample = false;
	}
```
