### ISSUE TITLE
AndroidAlarmManager add a schedule method

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#57856]
## Use case

As a developper I would like to be able to schedule events each day at a specific time.
In fact, I would start an isolate to download data.

Actually with AndroidAlarmManager.periodic I can only schedule events every 8hours for exemple and not every monday at 8pm or only monday and wednesday at 1am.

The startAt attributes inside periodic didn't help me for that. 

## Proposal

Add an extra attributes inside periodic or add a AndroidAlarmManager.schedule method :) ?

**Comment by cg021** [comment]
@EArminjon If you want to schedule a daily event at a specific time, the duration attribute can be set as `new Duration(hours:24, minutes:0, seconds:0);`. For weekly events, set startAt to a `DateTime` with the day and time that the alarm should go off each week.

**Comment by EArminjon** [comment]
@cg021 thx for your reply :)

 If I would start a job everyday at 1pm I can't use startAt because it's just for one date time, so I need copy/paste alarm call method 7 times ? (One call for one day)

The duration attributes start based on the actual  time. It just useful for a reminder or a stopwatch, I can't use it.

I didn't understand something :'( ?

**Comment by cg021** [comment]
I believe the duration attribute is used to set the interval between periodic requests, so wouldn't a duration of 24 hrs work for this? The plugin is calling `AlarmManager.setRepeating()`, and passes in duration as the intervalMillis value.

According to Android documentation, intervalMillis is the "interval in milliseconds between subsequent repeats of the alarm." 

I could be misunderstanding something, but my interpretation of this is that you should be able to set daily and weekly recurring alarms through durations of 24 hrs and 168 hours respectively.

**Comment by EArminjon** [comment]
Just for example, can you paste a simple use of this library to make daily alarm at 1pm ?

**Comment by cg021** [comment]
```
void main() async {
runApp(MaterialApp(home: App()));
}

 class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: RaisedButton(
            child: Text('Alarm'),
            onPressed: () {
              runAlarm();
            },
          ),
        ),
      ),
    );
  }

void runAlarm() {
  AndroidAlarmManager.periodic(
    const Duration(hours: 24),
    0,
    testAlarm,
    wakeup: true,
    startAt: DateTime.now(),
  ).then((val) => print(val));
}
static void testAlarm() {
  print("alarm");
}
```

**Comment by EArminjon** [comment]
Tell me if i'm wrong, so here you have created a periodic alarm which will start from (startTo) today and will be launch every 24 hours : so  first one tomorrow.

**Comment by EArminjon** [comment]
How launch alarm from a specific time ? Imagine that I open my app at 5pm and I want make a daily alarm at 1 pm. How did it ?

**Comment by cg021** [comment]
Yes, the DateTime.now() will cause the alarm to go off starting at the current time each day beginning now. If you want to schedule it for a different time, then you just need to pass in what time the alarm should go off by using the `DateTime` class in dart:core. Here's the documentation: https://api.dart.dev/stable/2.8.2/dart-core/DateTime-class.html.

**Comment by cg021** [comment]
I don't think the manager needs a schedule method, since it's already possible to schedule periodic timers. Closing this issue for now.
