### ISSUE TITLE
About Gradle and Android platform

### ISSUE THREAD

**Issue by dinhan1192** [flutter/flutter#57854]
Excuse me, 
I am new to Flutter, so when I install Flutter, I see that the Gradle version from distribution url is still 5.6.2 while the latest is 6.4.1.
The Kotlin is also not the latest, and the android platform has no sdk.
So do I have to update all of them to the latest or just leave them there ? And should I put the platform to 29 or 28 ? Or just leave it there ?
Thank you for your time !!!

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
