### ISSUE TITLE
[web] Canvas cannot be exported to bitmap

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#57853]
The problem was already mentioned in https://github.com/flutter/flutter/issues/57659 but I'm afraid it wouldn't get the required attention there. That bug was originally about resizing and the second bug is even much more serious.

## Steps to Reproduce

      final pictureRecorder = ui.PictureRecorder();
      final canvas = Canvas(pictureRecorder);
      canvas.draw... // any drawing operation
      final picture = pictureRecorder.endRecording();
      final exported = await picture.toImage(width, height); //!!! not working

results in the error below. Basically, the underlying HTML5 canvas variable seems to be `null` when the call is made.

[resize_repro.zip](https://github.com/flutter/flutter/files/4671873/resize_repro.zip)

**Expected results:**

No error.

**Actual results:**

```
TypeError: Cannot read property 'Symbol(dartx.toDataUrl)' of null
    at _engine._CanvasPool.new.toDataUrl (http://localhost:11103/dart_sdk.js:129211:28)
    at _engine.BitmapCanvas.new.toDataUrl (http://localhost:11103/dart_sdk.js:122112:32)
    at _engine.EnginePicture.new.toImage (http://localhost:11103/dart_sdk.js:136983:35)
```

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (10 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by iapicca** [comment]
HI @deakjahn 
I tried to refactor your code to get a better understanding,
but I feel I didn't go anywhere
(here's the [code](https://gist.github.com/iapicca/7e0ac228f5e8d2dbc413e23ac45e6c07) anyway
Tested with the latest master
I'm getting an undesired behaviour for the reduced
and no data for resized
Thank you

**Comment by deakjahn** [comment]
The repro was originally made for the other reported bug. There was a problem with resizing, too. When I made a secondary bug report with the bigger problem, I didn't create a new repro. So, what pertains to this is the third item.

    return await _pictureRecorder.endRecording().toImage(_width(), _height());

This gives an error for all my attempts, and by checking the source, this leads back to the wrapped `_canvas` of `CanvasPool` (if my memory serves right) being null when `toImage()` is called.

**Comment by deakjahn** [comment]
* There is no `ui.Image.toByteData()`, either in DomCanvas or CanvasKit. Both return unimplemented. Any image manipulation beyond simply displaying whatever you already have is currently impossible.

* There is no `Picture.toImage()`, so canvases cannot be converted into bitmaps. This means that there is no workaround for the above by drawing your image on a canvas and exporting that. Besides, drawing to the canvas would require somehow getting hold of the byte data of the image, and there is no toByteData(), as mentioned above.

**Comment by yjbanov** [comment]
We track this issue in the following two issues:

https://github.com/flutter/flutter/issues/42767 (CanvasKit)
https://github.com/flutter/flutter/issues/49857 (HTML)
