### ISSUE TITLE
 Camera: ^0.5.8+2 - Flutter app initializes forever

### ISSUE THREAD

**Issue by Alcarsil** [flutter/flutter#57869]
## Steps to Reproduce

1. Run `debug` on `VS Code`.
2. Update the files as follows:
My camera_helper.dart:

import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'app_helper.dart';
import 'tflite_helper.dart';

class CameraHelper {
  static CameraController camera;

  static bool isDetecting = false;

  static CameraLensDirection _direction = CameraLensDirection.back;

  static Future<void> initializeControllerFuture;

  static Future<CameraDescription> _getCamera(CameraLensDirection dir) async {
    return await availableCameras().then(
      (List<CameraDescription> cameras) => cameras.firstWhere(
        (CameraDescription camera) => camera.lensDirection == dir,
      ),
    );
  }

  static void initializeCamera() async {
    AppHelper.log("_initializeCamera", "Initializing camera..");

    camera = CameraController(
        await _getCamera(_direction),
        defaultTargetPlatform == TargetPlatform.iOS
            ? ResolutionPreset.low
            : ResolutionPreset.high,
        enableAudio: false);

    initializeControllerFuture = camera.initialize().then((value) {
      AppHelper.log(
          "_initializeCamera", "Camera initialized, starting camera stream..");

      camera.startImageStream((CameraImage image) {
        if (!TFLiteHelper.modelLoaded) return;

        if (isDetecting) return;

        isDetecting = true;

        try {
          TFLiteHelper.classifyImage(image);
        } catch (e) {
          print(e);
        }
      });
    });
  }
}

My detect_screen.dart:

import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:dermatestapp/helpers/app_helper.dart';
import 'package:dermatestapp/helpers/camera_helper.dart';
import 'package:dermatestapp/helpers/tflite_helper.dart';
import 'package:dermatestapp/models/result.dart';

class DetectScreen extends StatefulWidget {
  DetectScreen({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _DetectScreenPageState createState() => _DetectScreenPageState();
}

class _DetectScreenPageState extends State<DetectScreen>
    with TickerProviderStateMixin {
  AnimationController _colorAnimController;

  Animation _colorTween;

  List<Result> outputs;

  void initState() {
    super.initState();

    //Load TFLite Model

    TFLiteHelper.loadModel().then((value) {
      setState(() {
        TFLiteHelper.modelLoaded = true;
      });
    });

    //Initialize Camera

    CameraHelper.initializeCamera();

    //Setup Animation

    _setupAnimation();

    //Subscribe to TFLite's Classify events

    TFLiteHelper.tfLiteResultsController.stream.listen(
        (value) {
          value.forEach((element) {
            _colorAnimController.animateTo(element.confidence,
                curve: Curves.bounceIn, duration: Duration(milliseconds: 500));
          });

          //Set Results

          outputs = value;

          //Update results on screen

          setState(() {
            //Set bit to false to allow detection again

            CameraHelper.isDetecting = false;
          });
        },
        onDone: () {},
        onError: (error) {
          AppHelper.log("listen", error);
        });
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: FutureBuilder<void>(
        future: CameraHelper.initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.

            return Stack(
              children: <Widget>[
                CameraPreview(CameraHelper.camera),
                _buildResultsWidget(width, outputs)
              ],
            );
          } else {
            // Otherwise, display a loading indicator.

            return Center(child: CircularProgressIndicator());
          }
        },
      ),
    );
  }

  @override
  void dispose() {
    TFLiteHelper.disposeModel();

    CameraHelper.camera.dispose();

    AppHelper.log("dispose", "Clear resources.");

    super.dispose();
  }

  Widget _buildResultsWidget(double width, List<Result> outputs) {
    return Positioned.fill(
      child: Align(
        alignment: Alignment.bottomCenter,
        child: Container(
          height: 200.0,
          width: width,
          color: Colors.white,
          child: outputs != null && outputs.isNotEmpty
              ? ListView.builder(
                  itemCount: outputs.length,
                  shrinkWrap: true,
                  padding: const EdgeInsets.all(20.0),
                  itemBuilder: (BuildContext context, int index) {
                    return Column(
                      children: <Widget>[
                        Text(
                          outputs[index].label,
                          style: TextStyle(
                            color: _colorTween.value,
                            fontSize: 20.0,
                          ),
                        ),
                        AnimatedBuilder(
                            animation: _colorAnimController,
                            builder: (context, child) => LinearPercentIndicator(
                                  width: width * 0.88,
                                  lineHeight: 14.0,
                                  percent: outputs[index].confidence,
                                  progressColor: _colorTween.value,
                                )),
                        Text(
                          "${(outputs[index].confidence * 100.0).toStringAsFixed(2)} %",
                          style: TextStyle(
                            color: _colorTween.value,
                            fontSize: 16.0,
                          ),
                        ),
                      ],
                    );
                  })
              : Center(
                  child: Text("Wating for model to detect..",
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20.0,
                      ))),
        ),
      ),
    );
  }

  void _setupAnimation() {
    _colorAnimController =
        AnimationController(vsync: this, duration: Duration(milliseconds: 500));

    _colorTween = ColorTween(begin: Colors.green, end: Colors.red)
        .animate(_colorAnimController);
  }
}

3. 
Launching lib\main.dart on moto g 6 play in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for moto g 6 play to report its views...
Debug service listening on ws://127.0.0.1:62715/B1coqYkIE3I=/ws
Syncing files to device moto g 6 play...
I/flutter ( 5124): {loadModel} {Loading model..}
I/flutter ( 5124): {_initializeCamera} {Initializing camera..}
E/MethodChannel#tflite( 5124): Failed to handle method call
E/MethodChannel#tflite( 5124): java.lang.IllegalArgumentException: Unsupported value: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
E/MethodChannel#tflite( 5124): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
E/MethodChannel#tflite( 5124): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:69)
E/MethodChannel#tflite( 5124): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/MethodChannel#tflite( 5124): 	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:95)
E/MethodChannel#tflite( 5124): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#tflite( 5124): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#tflite( 5124): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#tflite( 5124): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#tflite( 5124): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#tflite( 5124): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#tflite( 5124): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/MethodChannel#tflite( 5124): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#tflite( 5124): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#tflite( 5124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
I/CameraManagerGlobal( 5124): Connecting to camera service
E/flutter ( 5124): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Unsupported value: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed, null)
E/flutter ( 5124): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5124): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 5124): <asynchronous suspension>
E/flutter ( 5124): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 5124): #3      Tflite.loadModel (package:tflite/tflite.dart:15:27)
E/flutter ( 5124): #4      TFLiteHelper.loadModel (package:dermatestapp/helpers/tflite_helper.dart:18:19)
E/flutter ( 5124): #5      _DetectScreenPageState.initState (package:dermatestapp/screens/detect_screen.dart:32:18)
E/flutter ( 5124): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4644:58)
E/flutter ( 5124): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 5124): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 5124): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 5124): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 5124): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 5124): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 5124): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 5124): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 5124): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 5124): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
E/flutter ( 5124): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 5124): #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 5124): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 5124): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 5124): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter ( 5124): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 5124): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 5124): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 5124): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 5124): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 5124): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 5124): #44     ComponentElement.performRebuild (package:fl
I/CameraManager( 5124): Using legacy camera HAL.
D/LegacyMotoModsHelper( 5124): No mod devie detected
I/CameraDeviceState( 5124): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0( 5124): Configure outputs: 2 surfaces configured.
D/Camera  ( 5124): app passed NULL surface
I/RequestThread-0( 5124): configureOutputs - set take picture size to 1280x720
I/CameraDeviceState( 5124): Legacy camera service transitioning to state IDLE
I/RequestQueue( 5124): Repeating capture request set.
W/LegacyRequestMapper( 5124): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper( 5124): Only received metering rectangles with weight 0.
W/LegacyRequestMapper( 5124): Only received metering rectangles with weight 0.
I/flutter ( 5124): {_initializeCamera} {Camera initialized, starting camera stream..}
I/RequestQueue( 5124): Repeating capture request cancelled.
I/CameraDeviceState( 5124): Legacy camera service transitioning to state CAPTURING
I/CameraDeviceState( 5124): Legacy camera service transitioning to state IDLE
I/CameraDeviceState( 5124): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0( 5124): Configure outputs: 2 surfaces configured.
D/Camera  ( 5124): app passed NULL surface
I/CameraDeviceState( 5124): Legacy camera service transitioning to state IDLE
I/RequestQueue( 5124): Repeating capture request set.
W/LegacyRequestMapper( 5124): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper( 5124): Only received metering rectangles with weight 0.
W/LegacyRequestMapper( 5124): Only received metering rectangles with weight 0.
I/CameraDeviceState( 5124): Legacy camera service transitioning to state CAPTURING
W/System  ( 5124): A resource failed to call release. 
I/il.dermatestap( 5124): Background concurrent copying GC freed 1274(157KB) AllocSpace objects, 15(15MB) LOS objects, 50% free, 9MB/19MB, paused 5.472ms total 52.307ms
I/il.dermatestap( 5124): Background concurrent copying GC freed 1461(144KB) AllocSpace objects, 15(15MB) LOS objects, 50% free, 9MB/19MB, paused 6.803ms total 76.816ms
I/il.dermatestap( 5124): Background concurrent copying GC freed 1296(144KB) AllocSpace objects, 13(13MB) LOS objects, 49% free, 10MB/21MB, paused 657us total 111.375ms
I/il.dermatestap( 5124): Waiting for a blocking GC ProfileSaver
I/il.dermatestap( 5124): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 27.175ms
I/il.dermatestap( 5124): Background concurrent copying GC freed 1528(144KB) AllocSpace objects, 14(14MB) LOS objects, 49% free, 10MB/21MB, paused 5.204ms total 58.222ms
I/il.dermatestap( 5124): Background concurrent copying GC freed 1528(144KB) AllocSpace objects, 16(16MB) LOS objects, 50% free, 16MB/33MB, paused 303us total 103.439ms
I/il.dermatestap( 5124): Background concurrent copying GC freed 1312(145KB) AllocSpace objects, 7(7MB) LOS objects, 49% free, 14MB/28MB, paused 4.454ms total 110.360ms

**Expected results: https://drive.google.com/open?id=1ExkareyDQEVAZWG5YpoWsrmeiBvjCRbd** 

**Actual results: https://drive.google.com/open?id=1WeQIywkHrzFKmcVE31hiyUvkXfMa9ugI** 

<details>
  <summary>flutter doctor -v: C:\Users\alcar\AndroidStudioProjects\derma_test_app\derma_test_app>flutter doctor -v
[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [versÃ£o 10.0.18363.836], locale pt-BR)
    • Flutter version 1.19.0-1.0.pre at C:\Users\alcar\flutter
    • Framework revision 456d80b9dd (12 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\alcar\AppData\Local\Android\Sdk
    • Platform android-R, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\alcar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\alcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available (I've already disconnected it)

! Doctor found issues in 1 category.
</summary>

```
```

```
```

.

```
```

</details>

**Comment by Alcarsil** [comment]
I've already solve it like https://stackoverflow.com/questions/27354141/disable-asset-compression-in-android-studio

**Comment by NgYewChun** [comment]
hi, I am facing similar problem, would you mind share your fix?
