### ISSUE TITLE
Unhandled exception: Invalid argument(s): Cannot find executable for git.

### ISSUE THREAD

**Issue by Bavon101** [flutter/flutter#57876]
## Steps to Reproduce

1. ...run flutter upgrade on master channel
2. ...
3. ...

## Logs

```
```

```
```

**Comment by nguyendinhthuc18** [comment]
I have this issue too. You just need to delete the pubspec.lock then re-open the tool.

**Comment by Bavon101** [comment]
Thanks, also updating the git executable directory works, it seem the
update shifts them to cmd folder.

{✓}

**Comment by iapicca** [comment]
Hi @Bavon101 
I see there's an open [issue](https://github.com/flutter/flutter/issues/57802) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by obed370** [comment]
I got the same error today. 
Just after finish to switch to the master channel, and after ran flutter upgrade i got it too.

**Comment by Bavon101** [comment]
Update the git executable directory, the update shifts them to cmd folder,
change the environment variables

{✓}

**Comment by Genderovic** [comment]
Hello friends, someone could tell me step by step the solution of this problem, I do not have so much knowledge in flutter and also I cannot find the GIT directory, most likely I do not have it installed. Thank.

**Comment by Bavon101** [comment]
Go to C directory, (C:\Program Files\Git\cmd) , that's if you're on
windows, copy the path and paste in in your environment variables path.
Restart the IDE and all should be working now.

{✓}

**Comment by Genderovic** [comment]
Hello, thanks for your answer, I did not get to try it, because I was forced to remove Flutter (C: \ src \ flutter) and re-download the Flutter SDK, I had no other options. Thank you very much for your help.

**Comment by Tmehmoo** [comment]
Set git path in environment variable . It was stupid mistake corrected by my student
