### ISSUE TITLE
[path_provider] getApplicationSupportDirectory in android i get /data/data/ instead of /data/

### ISSUE THREAD

**Issue by maheshkumar2150** [flutter/flutter#57870]
I want to take screenshot of a particular widget and store it in **getApplicationSupportDirectory**
When i use native code in android, I am using **getFilesDir()**

But it does not work as expected.

```dart
final dir= await getApplicationSupportDirectory();
print(dir.path);
```
**/data/user/0/com.myapp/files**

In android, 
```java
Log.d("Dir", String.valueOf(getFilesDir()));
```

**D/Dir: /data/user/0/com.myapp/files**

In android, log.d outputs the same location as it was printed in flutter.
But, When i try to access the file in android with native java code,

```bash
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
I/flutter (16569): PlatformException(error, Failed to find configured root that contains /data/data/com.myapp/files/pic.png, null)
D/ViewRootImpl(16569): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(16569): ViewPostImeInputStage processPointer 1
```

```dart
File file = new File(getFilesDir(), imageName);
```

This is how i tried to access the file in android.

Where does the /data/data/ comes from?

**Comment by iapicca** [comment]
Hi @maheshkumar2150 
can you please provide your `flutter doctor -v` , 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
