### ISSUE TITLE
How can I perform Visibility using if else statements?

### ISSUE THREAD

**Issue by iamsid47** [flutter/flutter#57897]
Actually, I am working on a project in which I want to use visibility. 
So, the thing is that whenever a user clicks the 'Connect' button, the text should change from "Connect" to "Disconnect." So, how can I do that here:

```
body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            NeumorphicButton(
              boxShape: NeumorphicBoxShape.circle(),
              padding: EdgeInsets.all(60.0),
              style: NeumorphicStyle(
                lightSource: LightSource.topLeft,
                shadowLightColor: Color(0xFF5ce1e6),
                intensity: 0.5,
                depth: 10,
                color: Color(0xFF090909),
                shape: NeumorphicShape.concave,
                border: NeumorphicBorder(
                  color: Color(0xFF090909),
                  width: 2.0,
                ),
              ),
              child: Visibility(
                visible: true,
                child: Text(
                  'Connect',
                  style: TextStyle(
                    fontSize: 26.0,
                    color: Color(0xFF5ce1e6),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

Note: I have just put a small part of the code so please don't comment regarding incomplete code. Also, I am using a stateful widget, just in case if needed.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
