### ISSUE TITLE
[SHARE] Share modal takes too long to appear con Android

### ISSUE THREAD

**Issue by clus90** [flutter/flutter#57899]
I installed the plugin, and on iOS works perfectly, but on Android it takes a long time for the modal to appear, this makes users tap the button repeatedly and after a while the modal shows up one on top of each other (depending on how many times users tap on the button)

This issue generates a poor user experience because I don't even have a way to show a loaging indicator while the share modal appears.

**Comment by CodeDude19** [comment]
If are you running this on an Android Emulator then make sure you are in **Profile Mode** or in Release Mode if you are connected to a Physical Device, as the perfomane varies drastically in Debug Mode

**Comment by clus90** [comment]
Hi @CodeDude19 !  Thanks for your reply. I even installed the release APK on my phone and is presenting the same behavior

**Comment by iapicca** [comment]
Hi @clus90 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
