### ISSUE TITLE
iOS emulator launch error

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#57893]
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPad Pro (12.9-inch) (4th generation).

**Comment by owenselles** [comment]
Can you give us more details like the full log and what tools/command you are using?

**Comment by owenselles** [comment]
Can you give us more details like the full log and what tools/command you are using?

**Comment by gurungsuraaj** [comment]
> Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
> Error launching application on iPad Pro (12.9-inch) (4th generation).

You need to open you project workspace file and rename DISPLAY NAME  to Runner as default.
If you want to change App display name then go to ios/ directory and change display name in infolist file.

**Comment by iapicca** [comment]
Hi @alex9153 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
