### ISSUE TITLE
Vuex like store 

### ISSUE THREAD

**Issue by shaked05** [flutter/flutter#57895]
## Proposal
Hey, so the feature i would like to have more [Vuex](https://vuex.vuejs.org/) store like for the state management. I know you are working on the redux flutter feature but i think there is some draw back when using flutter. 
I would like to have multiple store with the option to have inherited modules and having. This will help build it like [state](
https://vuex.vuejs.org/guide/state.html), [getters](https://vuex.vuejs.org/guide/getters.html), [action](https://vuex.vuejs.org/guide/actions.html) and [mutations](https://vuex.vuejs.org/guide/mutations.html)

**Comment by shaked05** [comment]
Adding the link to the state , getters mutations,  actions

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by shaked05** [comment]
Ho ok thx
