### ISSUE TITLE
in_app_purchase: PlatformException(storekit_duplicate_product_object when making an IOS non-consumable purchase

### ISSUE THREAD

**Issue by solnovus** [flutter/flutter#57903]
I'm using version 0.3.3+2 of the in_app_purchase package. It is working fine for Android, but when attempting to purchase a subscription on iOS I'm seeing the following error:

`
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manuelly using `completePurchase` to avoid edge cases., {applicationUsername: null, requestData: null, quantity: 1, productIdentifier: premium, simulatesAskToBuyInSandbox: null})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      SKPaymentQueueWrapper.addPayment (package:in_app_purchase/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:88:19)
#4      AppStoreConnection.buyNonConsumable (package:in_app_purchase/src/in_app_purchase/app_store_connection.dart:48:34)`

The code where I'm calling this just looks like this:

```
  Future<ProductDetails> getPremiumSubscription() async {
    const Set<String> _kIds = {'premium'};
    final ProductDetailsResponse response =
        await InAppPurchaseConnection.instance.queryProductDetails(_kIds);
    List<ProductDetails> products = response.productDetails;

    return products.isNotEmpty ? products.first : null;
  }

  Future<bool> upgradeToPremium() async {
    ProductDetails premiumSubscription = await getPremiumSubscription();

    if (premiumSubscription != null) {
      return await purchaseSubscription(premiumSubscription);
    } else {
      return false;
    }
  }

  Future<bool> purchaseSubscription(ProductDetails product) async {
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: product);

    return await InAppPurchaseConnection.instance
        .buyNonConsumable(purchaseParam: purchaseParam);
  }
```

**Comment by kaushaldeligence** [comment]
How did you solve this issue?

**Comment by AresVampire** [comment]
I am facing this issue too.

**Comment by HelloJunWei** [comment]
Hi here is my solution. it work for me. Please check.

https://github.com/flutter/flutter/issues/53534#issuecomment-645095503

**Comment by ziggycrane** [comment]
@HelloJunWei Did not work for me. SKPaymentQueue.default().transactions returns an empty array, but when trying to create a new transaction with the plugin I receive the same PlatformException(storekit_duplicate_product_object)

**Comment by t-cardozo** [comment]
This worked for me

https://github.com/flutter/flutter/issues/32759#issuecomment-620947340

If that doesn't work, add this package flutter_inapp_purchase

Call 
`FlutterInappPurchase.instance.clearTransactionIOS()`

this worked for me.. 

`  void addSubscription(ProductDetails productDetails) async {
    FlutterInappPurchase.instance.clearTransactionIOS().then((value) {
      PurchaseParam purchaseParam = PurchaseParam(
          productDetails: productDetails,
          applicationUserName: null,
          sandboxTesting: true);

      sleep(const Duration(seconds: 1));
      _connection.buyNonConsumable(purchaseParam: purchaseParam);
      // .then((value) => Navigator.pop(context));
    });
  }`

**Comment by HelloJunWei** [comment]
@ziggycrane Actually, I use [flutter_inapp_purchase](https://pub.dev/packages/flutter_inapp_purchase) this package now. It doesn't have this exception.

**Comment by ondev** [comment]
you must clean the pending transactions first:
`var paymentWrapper = SKPaymentQueueWrapper();
    var transactions = await paymentWrapper.transactions();
    transactions.forEach((transaction) async {
      await paymentWrapper.finishTransaction(transaction);
    });`

**Comment by mastahnish** [comment]
@ondev I tried your code but the `transaction` is always null. Should I corelate the paymentWrapper somehow with my `InAppPurchaseConnection`?

**Comment by shovelmn12** [comment]
Hi
I tried all methods above and nothing works....
how can i solve it ?
for some reason when debugging flutter_inapp_purchases works but not on appstore or testflight :|
and this plugin doesnt work on debug just give me the same error

**Comment by vishnukvmd** [comment]
Try doing the following:
```dart
InAppPurchaseConnection
    .instance.purchaseUpdatedStream
    .listen((event) async {
  for (final e in event) {
    if (e.pendingCompletePurchase) {
      await InAppPurchaseConnection.instance
          .completePurchase(PurchaseDetails(
        purchaseID: e.purchaseID,
        productID: e.productID,
        verificationData: e.verificationData,
        transactionDate: e.transactionDate,
        skPaymentTransaction: e.skPaymentTransaction,
        billingClientPurchase: e.billingClientPurchase,
      ));
    }
}
```

**Comment by shovelmn12** [comment]
I tried it, without creating a new instance, does it matter?
I also tried:
1. using flutter_inapp_purchases where they have clearIOSTransactions method
2. implementing clear transactions myself using dart SKTRansactionWrapper
3. adding swift code for clearing transactions

none of those helped me :|
its like for ios its not working at all

**Comment by hanyska** [comment]
@shovelmn12  You did it?

**Comment by vishnukvmd** [comment]
Another workaround is to use [flutter_inappp_purchase](https://pub.dev/packages/flutter_inapp_purchase).
```
if (Platform.isIOS && kDebugMode) {
      await FlutterInappPurchase.instance.initConnection;
      FlutterInappPurchase.instance.clearTransactionIOS();
}
```

**Comment by hanyska** [comment]
@vishnukvmd My app crashing when use your method. When you call this function?

**Comment by jeremiahlukus** [comment]
Kind of crazy the solution it to use another package to do this....

**Comment by shovelmn12** [comment]
https://github.com/flutter/flutter/issues/79788

still have a problem with the issue

**Comment by zgorawski** [comment]
What worked in my case (variation of @ondev answer):

```
    final paymentWrapper = SKPaymentQueueWrapper();
    final transactions = await paymentWrapper.transactions();
    await Future.forEach(transactions, (transaction) async {
      await paymentWrapper.finishTransaction(transaction);
    });
```

**Comment by TylerSustare** [comment]
The `finishTransaction` route never worked for me, unfortunately. 

I was about to switch to that other package when I tried in my initialization for `getProducts` and `getPurchases` this and it totally worked.

``` dart
  Future<void> _getPurchases() async {
    var response = await _iap.queryPastPurchases();
    this.purchases = response.pastPurchases;
    purchases.forEach((purchase) async {
      if (purchase.pendingCompletePurchase) {
        await InAppPurchaseConnection.instance.completePurchase(purchase);
      }
    });
  }
```

I don't know why the listener at my top level `runApp()` wasn't able to pick up on this, but when I did it right before trying to make a purchase I had enough context to complete the purchases.
