### ISSUE TITLE
running lastest version of flutter with older xcode 10.2

### ISSUE THREAD

**Issue by mohadel92** [flutter/flutter#57906]
hi,
i have : Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.4 18E226, locale en-EG)
and i would like to  run my flutter project on an older xcode(10.2)
is it possible to do such thing or do i have to update to xcode 11
right now i dont want to update my xcode to 11
thanks.

**Comment by TahaTesser** [comment]
Hi @mohadel92 
Only version might not be supported on lates `stable`, please upgrade
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by mohadel92** [comment]
Only what? I can't understand you
Thanks

**Comment by TahaTesser** [comment]
@mohadel92 
Updated the comment

**Comment by mohadel92** [comment]
Thanks
