### ISSUE TITLE
enable invariant_booleans analysis option

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5790]
Enable the **invariant_booleans** analysis option in the 2 flutter repo analysis option files and cleanup the generated warnings.

**Comment by jonahwilliams** [comment]
This lint is currently full of false positives.

context: https://github.com/dart-lang/linter/issues/811

**Comment by Hixie** [comment]
Closing because of https://github.com/dart-lang/linter/issues/811. I'll update the comment in the analysis_options.yaml file.
