### ISSUE TITLE
Too many flutter hot reloads exhausting heap space and disabling hot reload and restart

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#57910]
I have faced this issue too many times in android studio, when i try to too many hot reloads, it shows me this error `Exhausted heap space, trying to allocate 17179869200 bytes.` and then after i close the android studio and reopen it, the hot reload and hot restart buttons show disabled.

What i do to fix this issue:
->click on `File` menu and press `Invalidate Caches/Restart...`
-> in terminal, i add command `flutter clean`

After this, again hot reload and hot restart gets working again. \

Now this is too cumbersome to keep doing this as i thought hot reload should be unlimited and shouldn't fill up heap space.

I am using Android studio 3.6.3

My flutter doctor log output
```dart
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
@premingiet 
follow up on https://github.com/flutter/flutter/issues/54420 and check your case once it's fixed

**Comment by jmagman** [comment]
What device are you targeting?  Can we get the output of `flutter doctor -v`?

**Comment by premingiet** [comment]
`flutter doctor -v` output

```dart
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • E • G350RT058157000F • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by exaby73** [comment]
Hello @premingiet. I am unable to reproduce this issue. Since this is quite an old issue, I am closing it due to insufficient reproduction steps. If you disagree, please comment and we can re-open it. Thank you
