### ISSUE TITLE
enable literal_only_boolean_expressions analysis option

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5791]
Enable the **literal_only_boolean_expressions** analysis option in the 2 flutter repo analysis option files and cleanup the generated warnings.

**Comment by zoechi** [comment]
Blocked on https://github.com/dart-lang/linter/issues/453 (https://github.com/dart-lang/sdk/issues/34181)
See also  
 - https://github.com/flutter/flutter/blob/3184b7cb662bbe4287485b1cd2c2675325a7e4b3/analysis_options.yaml#L101
- https://github.com/flutter/flutter/blob/3184b7cb662bbe4287485b1cd2c2675325a7e4b3/packages/flutter/lib/analysis_options_user.yaml#L60

**Comment by pedromassangocode** [comment]
Still valid since the option mentioned above is still disabled in Flutter.

https://github.com/flutter/flutter/blob/9248fda41005ce0af2e522fabd0e9fedf2b3c863/analysis_options.yaml#L119

**Comment by h3y6e** [comment]
Hi team.
This option is still disabled now, but the false positives have been resolved by the [dart-lang/linter#3022](https://github.com/dart-lang/linter/pull/3022) created in 2021.
`literal_only_boolean_expressions` should be enabled, and code in some packages will need to be changed.

Can I work on this issue? I'm new to contributing to flutter/flutter but would like to try as I think a small fix is all I need.

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/flutter/commit/382ceb570703c81f5e8ced5d96fec7d2595cef0a
