### ISSUE TITLE
[Bug] Word Candidate Window is not in the right position when typing Chinese, in iPadOS with a physic keyboard

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#57914]
[Bug] Word Candidate Window is not in the right position when typing Chinese, in iPadOS with a physic keyboard.
I use the basic `TextField` setting, without modify anything. 
I have tested in iPad Pro (12.9-inch)(4th generation) with software verstion 13.4.1 and 
iPad (4th generation) with 12.1. The problem is still showing.

The candidate window should be at the bottom of the word that is typing. (Pic below)
![IMG_0077](https://user-images.githubusercontent.com/48649432/82777776-bbfb4d80-9e81-11ea-8d27-0215fa05eaeb.jpg)

However, actually, it is
![IMG_0078](https://user-images.githubusercontent.com/48649432/82777779-be5da780-9e81-11ea-9c31-e2990d17b9df.jpg)

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-AU)
    • Flutter version 1.17.1 at /Users/***/***/development/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by iapicca** [comment]
Hi @duomoteng 
Can you please provide your  a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Reproduced with current dev `1.20.0-0.0.pre` on iPad Pro (12.9-inch) (4th generation) iOS-13-5 (simulator). Choose Chinese, hide keyboard, Candidate window is shown on typing.

<img width="678" alt="Screenshot at Jun 17 14-34-08" src="https://user-images.githubusercontent.com/17024977/84893483-fb474380-b0a7-11ea-8cd8-8f709aee3555.png">


Simplest code sample

```
import 'package:flutter/material.dart';

void main() => runApp(
  MaterialApp(
    home: MyApp(),
  ),
);

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        body: Center(
            child: TextField(),
        ),
      ),
    );
  }
}
```

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • Nevercode’s iPhone                    • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • iPhone 11 Pro Max                     • 9F9AFD9B-7F22-468E-8096-B47E993E0619     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • iPad Pro (12.9-inch) (4th generation) • B34F14C5-50BE-4DD4-982C-C099C4B13F24     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS                                 • macOS                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server                            • web-server                               • web-javascript • Flutter Tools
    • Chrome                                • chrome                                   • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>

**Comment by CyrilHu** [comment]
Similar issues #102647 #9344

**Comment by goderbauer** [comment]
@cbracken I seem to remember that you did some work to position this tooltip properly. Is this fixed?

**Comment by cbracken** [comment]
I _thought_ that maybe @justinmc landed a fix for this at one point?

My recollection is that the positioning relies on code here:
https://github.com/flutter/engine/blob/b197788d963c183ac0477271c2153afb58c68b01/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1514-L1608

**Comment by cbracken** [comment]
Looks like the fix I was thinking of was landed by @LongCatIsLooong in https://github.com/flutter/flutter/issues/9344. My guess is this issue _should_ be closed by that patch.

There was an issue reported that suggests we're not returning a rect of the correct height during composing, but that's a separate (fine-tuning) issue: https://github.com/flutter/flutter/issues/102647

I left a comment at the bottom of that bug suggesting where I think the problem is. I think we can likely close this issue as fixed then resolve the positioning issue separately.

If anyone is still seeing this issue on either master or stable branch, please let us know and we can re-open.

**Comment by feimenggo** [comment]
> Looks like the fix I was thinking of was landed by @LongCatIsLooong in #9344. My guess is this issue _should_ be closed by that patch.
> 
> There was an issue reported that suggests we're not returning a rect of the correct height during composing, but that's a separate (fine-tuning) issue: #102647
> 
> I left a comment at the bottom of that bug suggesting where I think the problem is. I think we can likely close this issue as fixed then resolve the positioning issue separately.
> 
> If anyone is still seeing this issue on either master or stable branch, please let us know and we can re-open.

Simulator Screen Recording - iPad Pro (12.9-inch) (5th generation)

https://user-images.githubusercontent.com/12608693/188790603-a373f004-50b1-4197-b450-89763bd164e5.mp4

**Comment by feimenggo** [comment]
@cbracken I can't use the arrow keys on the keyboard to select words.

**Comment by cbracken** [comment]
@feimenggo just to verify; you've updated to the latest stable branch via `flutter upgrade` and are still unable to select from the candidates list via the arrow keys?

**Comment by cbracken** [comment]
@LongCatIsLooong seems there's still an issue (which may be specific to Chinese input). Perhaps we only fixed this on macOS?

**Comment by LongCatIsLooong** [comment]
macOS and iOS both implemented `firstRect` the same way. @feimenggo could you provide a minimal repro?

**Comment by feimenggo** [comment]
> macOS and iOS both implemented `firstRect` the same way. @feimenggo could you provide a minimal repro?


On Windows, using the Sougou pinyin IME to input Chinese has the same issue.

Download link: https://shurufa.sogou.com/

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const TextField(maxLines: null),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>

**Comment by cbracken** [comment]
> On Windows, using the Sougou pinyin IME to input Chinese has the same issue.

That's a known issue on Windows 7, but is completely unrelated in terms of implementation. It's tracked in this bug: https://github.com/flutter/flutter/issues/92050. If you have any additional detail, please feel free to add it there.

**Comment by feimenggo** [comment]
> > On Windows, using the Sougou pinyin IME to input Chinese has the same issue.
> 
> That's a known issue on Windows 7 (but should be fine on Windows 10-11), but is completely unrelated in terms of implementation. It's tracked in this bug: #92050. Please thumbs-up if it's affecting you, which helps us prioritise issues. If you have any additional detail, please feel free to add it on that bug.

There are also issues with Windows 10-11.

https://user-images.githubusercontent.com/12608693/189250361-dfcfe4d1-7f0d-4e7f-9f23-42f4da2711ee.mp4

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-19.0.pre.153, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability


<details>
<summary>Code sample</summary>
```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: SingleChildScrollView(
          child: Column(
            // Column is also a layout widget. It takes a list of children and
            // arranges them vertically. By default, it sizes itself to fit its
            // children horizontally, and tries to be as tall as its parent.
            //
            // Invoke "debug painting" (press "p" in the console, choose the
            // "Toggle Debug Paint" action from the Flutter Inspector in Android
            // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
            // to see the wireframe for each widget.
            //
            // Column has various properties to control how it sizes itself and
            // how it positions its children. Here we use mainAxisAlignment to
            // center the children vertically; the main axis here is the vertical
            // axis because Columns are vertical (the cross axis would be
            // horizontal).
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const TextField(maxLines: null),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```


</details>

**Comment by feimenggo** [comment]
> > > On Windows, using the Sougou pinyin IME to input Chinese has the same issue.
> > 
> > 
> > That's a known issue on Windows 7 (but should be fine on Windows 10-11), but is completely unrelated in terms of implementation. It's tracked in this bug: #92050. Please thumbs-up if it's affecting you, which helps us prioritise issues. If you have any additional detail, please feel free to add it on that bug.
> 
> There are also issues with Windows 10-11.
> 
>  20220909-085304-HD.mp4 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, 3.4.0-19.0.pre.153, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
> [✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Chrome - develop for the web
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
> [✓] Android Studio (version 2021.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability
> ```
> 
> Code sample


I occasionally encountered a throbbing problem using the Microsoft Pinyin IME.


https://user-images.githubusercontent.com/12608693/189253493-db898f66-18d8-4e7b-a1e7-5e4d5208e082.mp4


At 00:11 of the video:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/12608693/189253100-1767d1b8-0298-4d5e-b079-05c407fea8a0.png">

**Comment by feimenggo** [comment]
Using the QQ Pinyin IME, the throbbing problem is more frequent.


https://user-images.githubusercontent.com/12608693/189254395-4a3da8f7-331a-486e-8ea7-b8cfc1e12c5f.mp4

**Comment by cbracken** [comment]
@feimenggo please file a separate issues for Sogou on Windows or reply on the issue I pointed you to. This is off-topic for this bug.

**Comment by feimenggo** [comment]
Any updates for iPadOs or Windows?

**Comment by cbracken** [comment]
Please follow the relevant Windows or iPad issues for any updates.

**Comment by feimenggo** [comment]
Thank you, I updated to the latest version of the emulator, the issue still exists.

```
Flutter 3.4.0-28.0.pre.122 • channel master • https://github.com/flutter/flutter.git
Framework • revision 97e09c8a78 (2 hours ago) • 2022-09-23 09:43:20 +0800
Engine • revision a5489ce4f9
Tools • Dart 2.19.0 (build 2.19.0-229.0.dev) • DevTools 2.17.0
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-28.0.pre.122, on macOS 12.6 21G115 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```


https://user-images.githubusercontent.com/12608693/191890241-64c08ac0-ea10-4ad7-a123-b51da3d8e64d.mp4

**Comment by justinmc** [comment]
This bug does happen for me with a Japanese keyboard too!

https://user-images.githubusercontent.com/389558/192903905-d1504a6d-9662-453f-a6bc-5792841909f4.mov

**Comment by WithToken** [comment]
I improvised the problem
code：
```
[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(keyboardDidChangeFrame:)
                                                 name:UIKeyboardDidChangeFrameNotification
                                               object:nil];

- (void)keyboardDidChangeFrame:(NSNotification *)notification
{
    NSDictionary *userInfo = [notification userInfo];
    NSValue *value = [userInfo objectForKey:UIKeyboardFrameEndUserInfoKey];
    CGRect keyboardRect = [value CGRectValue];
    CGFloat height = keyboardRect.size.height;
    if (height < 150) {
        UIView *textField = [self findTextFieldInView:self.view];
        
        if (textField) {
            [self.timer invalidate];
            self.timer = nil;
            
            self.timer = [NSTimer scheduledTimerWithTimeInterval:0.2 repeats:YES block:^(NSTimer * _Nonnull timer) {
                textField.frame = CGRectMake(textField.frame.origin.x, 0, textField.frame.size.width, textField.frame.size.height);
            }];
        } else {
            [self.timer invalidate];
            self.timer = nil;
        }
    }
}

- (UIView *)findTextFieldInView:(UIView *)view
{
    for (UIView *subView in view.subviews) {
        if (strstr(object_getClassName(subView), "FlutterTextInputViewAccessibilityHider")) {
            return subView;
        } else {
            UIView *tempView = [self findTextFieldInView:subView];
            if (tempView) {
                return tempView;
            }
        }
    }
    return nil;
}
```

**Comment by justinmc** [comment]
@LongCatIsLooong Do you think there's any better solution than using timers like that? ^

**Comment by cbracken** [comment]
Are we sure this isn't a regression; I swear this was working at some point.

**Comment by feimenggo** [comment]
Any progress for the issuse?

**Comment by feimenggo** [comment]
> I'm adding this code that works for me. code：
> 
> ```
> [[NSNotificationCenter defaultCenter] addObserver:self
>                                              selector:@selector(keyboardDidChangeFrame:)
>                                                  name:UIKeyboardDidChangeFrameNotification
>                                                object:nil];
> 
> - (void)keyboardDidChangeFrame:(NSNotification *)notification
> {
>     NSDictionary *userInfo = [notification userInfo];
>     NSValue *value = [userInfo objectForKey:UIKeyboardFrameEndUserInfoKey];
>     CGRect keyboardRect = [value CGRectValue];
>     CGFloat height = keyboardRect.size.height;
>     if (height < 150) {
>         UIView *textField = [self findTextFieldInView:self.view];
>         
>         if (textField) {
>             [self.timer invalidate];
>             self.timer = nil;
>             
>             self.timer = [NSTimer scheduledTimerWithTimeInterval:0.2 repeats:YES block:^(NSTimer * _Nonnull timer) {
>                 textField.frame = CGRectMake(textField.frame.origin.x, 0, textField.frame.size.width, textField.frame.size.height);
>             }];
>         } else {
>             [self.timer invalidate];
>             self.timer = nil;
>         }
>     }
> }
> 
> - (UIView *)findTextFieldInView:(UIView *)view
> {
>     for (UIView *subView in view.subviews) {
>         if (strstr(object_getClassName(subView), "FlutterTextInputViewAccessibilityHider")) {
>             return subView;
>         } else {
>             UIView *tempView = [self findTextFieldInView:subView];
>             if (tempView) {
>                 return tempView;
>             }
>         }
>     }
>     return nil;
> }
> ```

@WithToken Hello, Where to add this code

**Comment by WithToken** [comment]
> 
FlutterViewController, XXFlutterViewController Subclass of FlutterViewController

**Comment by WithToken** [comment]
> 

FlutterViewController, XXFlutterViewController Subclass of FlutterViewController

**Comment by feimenggo** [comment]
@LongCatIsLooong    Hi, The previous problem has been fixed, but there is still a small issues. The coordinates entered the first time were wrong.

Screenshot:

<img width="405" alt="B08F9D88-BB97-462B-AB4C-AE343844AE92" src="https://user-images.githubusercontent.com/12608693/195221975-ce874784-6dbe-46f7-bd70-c1ab7dfdd445.png">

Video:

https://user-images.githubusercontent.com/12608693/195221765-ed4827bc-cc82-4d56-89e1-2845f43df8f1.mp4
