### ISSUE TITLE
[path_provider] build error

### ISSUE THREAD

**Issue by raygo0511** [flutter/flutter#57923]
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':path_provider:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':path_provider:debugCompileClasspath'.
   > Could not resolve project :path_provider_macos.
     Required by:
         project :path_provider
      > Unable to find a matching configuration of project :path_provider_macos:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug_QATDebug failed with exit code 1
```

**Comment by iapicca** [comment]
Hi @raygo0511 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
Thank you

**Comment by mokhosh** [comment]
I had the same problem with path provider. I created a new project and moved my lib folder over, now I'm getting this:
```
../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code
Dart snapshot generator failed with exit code -6
../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code
Dart snapshot generator failed with exit code -6
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mokhosh/Android/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/mokhosh/Android/flutter/bin/flutter'' finished with non-zero exit value 1
```

**Comment by iapicca** [comment]
Hi @mokhosh 
could you please provide the info listed [above](https://github.com/flutter/flutter/issues/57923#issuecomment-633463378)
Thank you

**Comment by shrutikateiosys** [comment]
Same issue ?

**Comment by cintadewiamelia** [comment]
i got same issue, how to solved?

**Comment by qxmmxi** [comment]
same issue：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by qxmmxi** [comment]
[  +37 ms] executing: [/Applications/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Applications/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +32 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +6 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Applications/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +9 ms] executing: sw_vers -productName
[  +31 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +22 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E266
[  +36 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +607 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.4
           Build version 11E146
[  +64 ms] executing: /Users/xixiaona/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/xixiaona/Library/Android/sdk/platform-tools/adb devices -l
[   +1 ms] List of devices attached
[  +15 ms] executing: /Applications/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +56 ms] /usr/bin/xcrun simctl list --json devices
[ +106 ms] No supported devices connected.
[  +11 ms] "flutter run" took 1,020ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by Libin2019** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not determine the dependencies of task ':path_provider:compileDebugAidl'.
> 
> > Could not resolve all task dependencies for configuration ':path_provider:debugCompileClasspath'.
> > Could not resolve project :path_provider_macos.
> > Required by:
> > project :path_provider
> > > Unable to find a matching configuration of project :path_provider_macos:
> > - None of the consumable configurations have attributes.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Finished with error: Gradle task assembleDebug_QATDebug failed with exit code 1

i have same problem , and you had solved it ?

**Comment by Libin2019** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not determine the dependencies of task ':path_provider:compileDebugAidl'.
> 
> > Could not resolve all task dependencies for configuration ':path_provider:debugCompileClasspath'.
> > Could not resolve project :path_provider_macos.
> > Required by:
> > project :path_provider
> > > Unable to find a matching configuration of project :path_provider_macos:
> > - None of the consumable configurations have attributes.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Finished with error: Gradle task assembleDebug_QATDebug failed with exit code 1

i have solved this problem , this is my solution : go to your Flutter sdk folder ,then go to \.pub-cache\hosted\pub.dartlang.org\ ,if there have a path_provider_macos-0.0.4 folder  ,delete it ,if no ,you try go \.pub-cache\hosted\pub.flutter-io.cn\ , and remove  path_provider_macos-0.0.4 folder

**Comment by nealwon** [comment]
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Could not determine the dependencies of task ':path_provider:compileDebugAidl'.
> > 
> > > Could not resolve all task dependencies for configuration ':path_provider:debugCompileClasspath'.
> > > Could not resolve project :path_provider_macos.
> > > Required by:
> > > project :path_provider
> > > > Unable to find a matching configuration of project :path_provider_macos:
> > > 
> > > 
> > > 
> > > * None of the consumable configurations have attributes.
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 3s
> > Finished with error: Gradle task assembleDebug_QATDebug failed with exit code 1
> 
> i have solved this problem , this is my solution : go to your Flutter sdk folder ,then go to .pub-cache\hosted\pub.dartlang.org\ ,if there have a path_provider_macos-0.0.4 folder ,delete it ,if no ,you try go .pub-cache\hosted\pub.flutter-io.cn\ , and remove path_provider_macos-0.0.4 folder

Thank U. This's very useful.

**Comment by iapicca** [comment]
Hi @qxmmxi 
could you please run `flutter upgrade --force`
if the issue persist please provide the info listed [above](https://github.com/flutter/flutter/issues/57923#issuecomment-633463378)
Thank you

**Comment by mokhosh** [comment]
In my case it was moor_ffi 0.6.0, and downgrading to 0.5.0 fixed the problem.
What made this so annoying was I didn't get an error for moor, the error message was for dart sdk!

**Comment by jessing** [comment]
Try the latest version of path_provider

**Comment by harpreetkaurbains** [comment]
> ```shell
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':path_provider:compileDebugAidl'.
> > Could not resolve all task dependencies for configuration ':path_provider:debugCompileClasspath'.
>    > Could not resolve project :path_provider_macos.
>      Required by:
>          project :path_provider
>       > Unable to find a matching configuration of project :path_provider_macos:
>           - None of the consumable configurations have attributes.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Finished with error: Gradle task assembleDebug_QATDebug failed with exit code 1
> ```



> Hi @raygo0511
> can you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`,
> your `pubspec.yaml`
> Thank you

I'm having same issue .can you please help me to resolve.

**Comment by fdh19979** [comment]
find flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_macos-0.0.4+3
delete all files

**Comment by harpreetkaurbains** [comment]
Thanks

**Comment by abhijitgawai** [comment]
The error I had was like @raygo0511 having both macos and linux errors, I have windows machine
Then i deleted file path_provider_macos-0.0.4+3

Now my error is 

`<ij_msg_gr>Project` resolve errors<ij_msg_gr><ij_nav>D:\sih\appproject\trail0\trail5\trail4\CourtCounter\build.gradle<ij_nav><i><b>root project 'CourtCounter': Unable to resolve additional project configuration.</b><eol>Details: org.apache.tools.ant.BuildException: Basedir D:\ABHI_D\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\android does not exist</i>`



What should be done now

**Comment by codeHarton** [comment]
I delete the flutter flod and rezip ,then it is run  ok

**Comment by iapicca** [comment]
Hi all
I see several workaround proposed,

you could provide
the info listed [above](https://github.com/flutter/flutter/issues/57923#issuecomment-633463378)
with a flutter version not lower than the latest stable
and the latest plugin version,
without that the issue is not workable

thank you

**Comment by alex7egli** [comment]
I had the same issue, followed the steps in this thread: https://github.com/flutter/flutter/issues/46807
Deleting the Pub Cache and re-running flutter run afterward worked. For me this was at: $USER_HOME$/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/

**Comment by rehnius** [comment]
I have the same issue. I fixed it running: flutter pub cache repair .
It works fine now.

**Comment by Princeigwe** [comment]
I tried all the given solutions here, even deleted the path_provider macos. It give a totally new different error.  So reinstalled flutter with snap, and made sure I ran the code with internet connection. Worked for me🙂
