### ISSUE TITLE
enable only_throw_errors analysis option

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5792]
Enable the **only_throw_errors** analysis option in the 2 flutter repo analysis option files and cleanup the generated warnings.

**Comment by zoechi** [comment]
See also  

- https://github.com/flutter/flutter/blob/3184b7cb662bbe4287485b1cd2c2675325a7e4b3/packages/flutter/lib/analysis_options_user.yaml#L63
- https://github.com/flutter/flutter/blob/3184b7cb662bbe4287485b1cd2c2675325a7e4b3/analysis_options.yaml#L108

**Comment by a14n** [comment]
Enabling this lint produces >250 lints from various places and it needs a good knowledge of all the code base to fix them all.

**Comment by kf6gpe** [comment]
Keeping this open as we perform some new triage.
