### ISSUE TITLE
Is it possible to set screen size as the physical screen size in e2e tests?

### ISSUE THREAD

**Issue by Eugenio-Bruno** [flutter/flutter#57927]
Hi,

I have an e2e test:

```
import 'package:e2e/e2e.dart';
void main() {
  E2EWidgetsFlutterBinding.ensureInitialized();
//...
}
```

The problem is that this test runs in a small piece of my device's screen. I'd like it to take up the whole screen of my device. I tried this with no luck:

`tester.binding.window.physicalSizeTestValue = Size(720.0, 1494.0);`

**Comment by VladyslavBondarenko** [comment]
Hi @Eugenio-Bruno 
please follow up on https://github.com/flutter/flutter/issues/12994,
I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it

**Comment by buntagonalprism** [comment]
For anyone else encountering this problem of the app looking very small and squished when running integration tests using the `e2e` package: none of the suggestions in #12994 fixed it for me, but they did help me stumble towards this solution which makes e2e tests fill the device screen:

```dart
void main() {
  final E2EWidgetsFlutterBinding binding = E2EWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    final Size logicalViewport = binding.window.physicalSize / binding.window.devicePixelRatio;
    binding.renderView.configuration = TestViewConfiguration(size: logicalViewport);
  });

  testWidgets('Some test', (WidgetTester tester) async {
    // test goes here...
  });
}
```
It seems that e2e tests by default do use the entire device screen space, but don't respect the device pixel ratio making everything very small. The logic in `setUp` above forces the test window to be the correct number of logical pixels for the screen size and density. The test framework then stretches those logical pixels to fill the available space on the device screen,  making everything the correct size.
