### ISSUE TITLE
Having trouble fetching data in background

### ISSUE THREAD

**Issue by nobimac** [flutter/flutter#57924]
Hello guys,
when i try to get data from SharedPreference when app is in background it does not gives me newly updated value.

**Comment by iapicca** [comment]
Hi @nobimac 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
