### ISSUE TITLE
enable unawaited_futures analysis option

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5793]
Enable the **unawaited_futures** analysis option in the 2 flutter repo analysis option files and cleanup the generated warnings.

**Comment by Hixie** [comment]
This might be WONTFIX. We rarely await futures and it's not clear it would make the code cleaner. Most of our futures are harmless to ignore (e.g. the ones from animation controllers), and most can never throw errors so awaiting them to catch the error doesn't really help.

**Comment by tvolkert** [comment]
FYI, recent updates to `package:test` have made this even less likely to provide any value -- https://github.com/dart-lang/test/pull/529#issuecomment-279109649

**Comment by danrubel** [comment]
Closing this as WONTFIX makes sense to me.
