### ISSUE TITLE
Crash in Crashlytics - android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#57936]
## Steps to Reproduce
Brand: samsung
Model: Galaxy A3
Orientation: Portrait
RAM free: 467.27 MB
Disk free: 717.11 MB
Version: 6.0.1
Orientation: Portrait
Rooted: No

Unfortunately, I don't have any steps. 
**Expected results:** 
The application can be used without crashes.

**Actual results:** 
Crash in crashlytics 
<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference
       at i.a.b.a.a.a.a()
       at i.a.b.a.a.a.a()
       at i.a.b.a.a.a$f.onFailure()
       at b.c.b.a.h.u.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```

</details>

**Comment by GyuriMajercsik** [comment]
Adding [crash.log] logs file: 
(https://github.com/flutter/flutter/files/4676819/com._issue_66334f4f17db8c4e6c16b0b5e4e797e7_crash_session_5ECA43A8011C00013EAAC581546CEFCF_DNE_0_v2.log)

**Comment by TahaTesser** [comment]
Hi @GyuriMajercsik 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by GyuriMajercsik** [comment]
Hi Taha, 

Thanks for taking a look into this. Unfortunately I can't provide with any steps or code sample since this crash was collected by Crashlytics. 

I'm attaching the requested files. Please let me know if I can assist you with anything. 
[flutter_doctor_verbose.txt](https://github.com/flutter/flutter/files/4677372/flutter_doctor_verbose.txt)
[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/4677373/flutter_run_verbose.txt)

Thank you, 
Gyuri

**Comment by GyuriMajercsik** [comment]
One more crash reported by Crashlytics: 

Brand: samsung
Model: Galaxy S5
Orientation: Portrait
RAM free: 396.59 MB
Disk free: 593.16 MB

Version: 6.0.1
Orientation: Portrait
Rooted: No

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference
       at i.a.b.a.a.a.a()
       at i.a.b.a.a.a.a()
       at i.a.b.a.a.a$f.onFailure()
       at b.c.b.a.h.u.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by luisbazan** [comment]
Hello guys,

Have you found any solution for this problem? I have a similar issue.

![image](https://user-images.githubusercontent.com/17059693/94754725-aa5a1300-0357-11eb-8ed8-f5759bcda6f0.png)
![image](https://user-images.githubusercontent.com/17059693/94754755-c5c51e00-0357-11eb-88e7-acf592314c06.png)
![image](https://user-images.githubusercontent.com/17059693/94754788-de353880-0357-11eb-92ab-5ef0a83bab76.png)

**Comment by chinmaygarde** [comment]
@luisbazan s stack trace seems to indicate a different issue to the OP. Would it be possible to deobfuscate the stack trace or provide a reduced test case? Without that, it is hard to make progress on this bug.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
