### ISSUE TITLE
[iap] Problem with restore purchases

### ISSUE THREAD

**Issue by enative** [flutter/flutter#57947]
After restore purchases:
```
final QueryPurchaseDetailsResponse response = await connection.queryPastPurchases();
  if (response.error != null) {
    return;
  }

  for (PurchaseDetails details in response.pastPurchases) {
    if (Platform.isIOS) {
      await connection.completePurchase(details);
    }
  }
```

its restored without errors, but when I reload app there a big list in ```handlePurchaseUpdates``` with old thansactions.
  I'm also ```completePurchase``` this items(without errors), but no result - Every reload app shows this list of old purchases

**Comment by enative** [comment]
This list of old transactions is cleared only when I run app with another plugin (flutter_in_app_purchase), after I'm switch plugin back (to in_app_purchase) and list disappears,
BUT if I press restore purchases this list shown again on every app start(

How fix this?

**Comment by TahaTesser** [comment]
Hi @enative 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
