### ISSUE TITLE
Let user choose source(Gallery or Camera)

### ISSUE THREAD

**Issue by alfavat** [flutter/flutter#57954]
hi
thanks for the great package.
I want to let the users to choose source (Gallery or Camera) and I don not want to show a modal to ask them which one they want to choose.
I want the app to ask users itself (I have seen that most of the time application asks if you want to pick image from gallery or do you want to get new image from camera).
is it possible?

**Comment by TahaTesser** [comment]
Hi @alfavat 
You can use `image_picker` official example,  user can choose between camera and gallery
https://pub.dev/packages/image_picker#-example-tab-

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
 Thank you
