### ISSUE TITLE
AlertDialog not working on larger screen sizes after upgrading to stable v1.17.1

### ISSUE THREAD

**Issue by MathiasSolling** [flutter/flutter#57967]
After upgrading flutter to the newest version all my AlertDialog's aren't working on normal to large screen sizes (Emulator as well as physical devices).

This does not happen on my second computer running flutter v1.12.13+hotfix.9.

Flutter doctor:

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

This is one of my widgets:

```
class ChangeUsernameDialog extends StatefulWidget {
  @override
  _ChangeUsernameDialogState createState() => _ChangeUsernameDialogState();
}

class _ChangeUsernameDialogState extends State<ChangeUsernameDialog> {
  String _newUsername = '';

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: Color(0xff0e0c28),
      title: CustomText(
        text: 'New username',
        fontSize: 16,
      ),
      content: StatefulBuilder(
          builder: (BuildContext context, StateSetter setState) {
        return Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            CustomTextFormField(
              onChanged: (val) {
                _newUsername = val;
              },
              validator: (val) =>
                  val.length >= 3 && val.length <= 16 ? val : null,
              minLength: 3,
              maxLength: 16,
              labelText: 'Username',
            ),
          ],
        );
      }),
      actions: <Widget>[
        FlatButton(
          child: CustomText(
            text: 'Cancel'.toUpperCase(),
            fontSize: 14,
          ),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        FlatButton(
          child: CustomText(
            text: 'Save'.toUpperCase(),
            fontSize: 14,
            textColor: Color(0xff31C9C9),
          ),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ],
    );
  }
}
```

Method to initialize this AlertDialog

```
GestureDetector(
                        child: Icon(
                          FontAwesomeIcons.edit,
                          color: Colors.white,
                          size: 12,
                        ),
                        onTap: () => showDialog(
                          context: context,
                          builder: (_) => ChangeUsernameDialog(),
                        ),
                      ),
```

This is the output

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The method 'copyWith' was called on null.
Receiver: null
Tried calling: copyWith(maxWidth: Infinity)

The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _RenderButtonBarRow.constraints (package:flutter/src/material/button_bar.dart:337:30)
#2      RenderObject.debugFillProperties (package:flutter/src/rendering/object.dart:2837:68)
#3      RenderBox.debugFillProperties (package:flutter/src/rendering/box.dart:2424:11)
#4      RenderFlex.debugFillProperties (package:flutter/src/rendering/flex.dart:1017:11)
...
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#bae64 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...  size: MISSING
RenderObject: _RenderInkFeatures#bae64 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
  size: MISSING
...  child: RenderIntrinsicWidth#fb25a relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...    size: MISSING
...    stepWidth: null
...    stepHeight: null
...    child: RenderFlex#7b9b0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: min
...      crossAxisAlignment: stretch
...      verticalDirection: down
...      child 1: RenderPadding#2145f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(24.0, 24.0, 24.0, 0.0)
...        textDirection: ltr
...        child: RenderSemanticsAnnotations#eadae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          semantic boundary
...          size: MISSING
...      child 2: RenderPadding#c295b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.loose
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(24.0, 20.0, 24.0, 24.0)
...        textDirection: ltr
...        child: RenderFlex#68d89 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: min
...          crossAxisAlignment: center
...          verticalDirection: down
...      child 3: RenderPadding#037f3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets.zero
...        textDirection: ltr
...        child: RenderPadding#187b5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          padding: EdgeInsets(4.0, 8.0, 4.0, 8.0)
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: _RenderInkFeatures#bae64 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#a9bd3 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#2bdf7 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 322 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
RenderBox was not laid out: RenderPhysicalShape#2bdf7 relayoutBoundary=up2
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  AlertDialog file:///D:/IdeaProjects/mg/lib/home/profile/change_username_dialog.dart:16:12
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1694:12)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1254:33)
#4      RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1873:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
...
The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#2bdf7 relayoutBoundary=up2
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...  size: MISSING
...  elevation: 24.0
...  color: Color(0xff0e0c28)
...  shadowColor: Color(0xff0e0c28)
...  clipper: ShapeBorderClipper
RenderObject: RenderPhysicalShape#2bdf7 relayoutBoundary=up2
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
  size: MISSING
  elevation: 24.0
  color: Color(0xff0e0c28)
  shadowColor: Color(0xff0e0c28)
  clipper: ShapeBorderClipper
...  child: RenderCustomPaint#a9bd3 relayoutBoundary=up3 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...    size: MISSING
...    child: _RenderInkFeatures#bae64 relayoutBoundary=up4 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...      size: MISSING
...      child: RenderIntrinsicWidth#fb25a relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=687.3)
...        size: MISSING
...        stepWidth: null
...        stepHeight: null
...        child: RenderFlex#7b9b0 NEEDS-LAYOUT NEEDS-PAINT
...          needs compositing
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: min
...          crossAxisAlignment: stretch
...          verticalDirection: down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The method 'copyWith' was called on null.
Receiver: null
Tried calling: copyWith(maxWidth: Infinity)
════════════════════════════════════════════════════════════════════════════════════════════════════

I have tried to wrap every single Widget inside a Container and add width & height without any luck. Again, This does not happen on my second computer running flutter v1.12.13+hotfix.9.

**Comment by TahaTesser** [comment]
Hi @MathiasSolling 
Looking at errors, sounds an issues with your code
Sample code you provided has missing code
If you think this is a Flutter issue, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by MathiasSolling** [comment]
@TahaTesser Did you see the code to reproduce I've given?

Also it works on some (smaller) screen sizes but breaks on large with given error.

**Comment by TahaTesser** [comment]
@MathiasSolling 
Your code is incomplete, and not workable by removing missing components 
Please a minimal code sample to reproduce the issue
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
