### ISSUE TITLE
The cache of main.dart.js for the Web version after you release a new version

### ISSUE THREAD

**Issue by ArtikUA** [flutter/flutter#57964]
## Use case
The problem is when you make a new version of the Flutter application with `flutter build web` command and upload it to a web-server then all the users who used the application have a previous cached main.dart.js  version on their devices, and usually, it won't be downloaded again after you click "Refresh" button if the browser (especially with Safari on iPhone).

## Proposal
The proposal is to have a hash of the build inside the name of the js bundle.
For example, instead of `main.dart.js`, we would have `main.dart.28eb5183cd91b813b08c80ab5d6f33e0.js` and it will be cached only until new release.

We already have a release hash number in `buildDir` variable while we build an application (we can observe it in `.dart_tool/flutter_build` folder) so we can use it.

**Comment by yjbanov** [comment]
@jonahwilliams I recall this being fixed. This is related to how service workers work or used to work.

**Comment by jonahwilliams** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/56786, but we haven't done a dev release in nearly 3 weeks so it is unsurprising that users are still hitting this case.

**Comment by hauketoenjes** [comment]
Hi, 

it seems like it is still not working on the master branch. The file is still named main.dart.js and the browser caches it until you delete the cache. Is there any workaround besides renaming the file on every release?

**Comment by sgehrman** [comment]
I don't see this working. Maybe I'm misunderstanding. I change my flutter web project, rebuild it and deploy it, but refreshing the browser doesn't get the new build. I have to clear the application data. How do I get this working automatically? Do I have to add a version in index.html for the js file?

I'm on the latest beta
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
[✓] Connected device (2 available)

**Comment by jonahwilliams** [comment]
Hi @sgehrman , could you file a new issue with more details - such as the contents of the network activity tab/application tab after you've deployed the new version - but before clearing the application data?

Its possible we might need more aggressive cache-busting params like: https://github.com/flutter/flutter/pull/62076

**Comment by azbuky** [comment]
@sgehrman Your problem might be with the service worker not activating after update. Check your Application tab in Chrome. A simple page refresh is likely not enough to switch to the new service worker.

@jonahwilliams Is there currently any way to force the service worker to activate without closing all related tabs?

**Comment by jeffaknine** [comment]
@jonahwilliams I'm having the same problem. Should I open a new issue?

**Comment by topilski** [comment]
Same issue, please fix it

**Comment by MihanixA** [comment]
the same problem

**Comment by sachemmark** [comment]
Same issue

**Comment by MalteMagnussen** [comment]
Same problem. 

Nexus 6P phone. 

Chrome browser. 

Caches for infinity. Have to manually clear cache. No user will do that, so they don't receive updates. What is the solution?

**Comment by RafaelTadeuSilva** [comment]
I had the same problem,

I found this answer [https://stackoverflow.com/a/61720981](https://stackoverflow.com/a/61720981)
and it worked for me, as a temporary fix.

edit your index.html, before building and change the version number, in this line
<script src="main.dart.js?version=1" type="application/javascript"></script>

**Comment by nikpozdnyakov** [comment]
I have a similar problem, writing the version in an index file is hardcode, we are waiting for a fix.

**Comment by MalteMagnussen** [comment]
> I have a similar problem, writing the version in an index file is hardcode, we are waiting for a fix.

@nikpozdnyakov 

So a temporary solution is to change version in the index HTML file?

**Comment by GyuriMajercsik** [comment]
Changing the version doesn't seem to solve the problem. A force refresh is still needed.

**Comment by nikpozdnyakov** [comment]
> Changing the version doesn't seem to solve the problem. A force refresh is still needed.

locally this solution helps, perhaps your webserver stores the page cache

**Comment by Bes79** [comment]
Same issue

**Comment by tazik561** [comment]
```
I found this answer https://stackoverflow.com/a/61720981
and it worked for me, as a temporary fix.

edit your index.html, before building and change the version number, in this line

<script src="main.dart.js?version=1" type="application/javascript"></script>
```

I tried this but it doesn't work and it loads old page again.

**Comment by BenPoell** [comment]
> ```
> I found this answer https://stackoverflow.com/a/61720981
> and it worked for me, as a temporary fix.
> 
> edit your index.html, before building and change the version number, in this line
> 
> <script src="main.dart.js?version=1" type="application/javascript"></script>
> ```
> 
> I tried this but it doesn't work and it loads old page again.

My environment is built up on Azure Stack. For me this workaround only works for a blob container with web-access. When deploying the build to an app service / web server it just doesn't recognize the change and the chache still stays the same.
Any ideas how to solve this?

**Comment by amritk** [comment]
Is this fixed yet? Still seems to be happening

**Comment by tazik561** [comment]
> > ```
> > I found this answer https://stackoverflow.com/a/61720981
> > and it worked for me, as a temporary fix.
> > 
> > edit your index.html, before building and change the version number, in this line
> > 
> > <script src="main.dart.js?version=1" type="application/javascript"></script>
> > ```
> > 
> > 
> > I tried this but it doesn't work and it loads old page again.
> 
> My environment is built up on Azure Stack. For me this workaround only works for a blob container with web-access. When deploying the build to an app service / web server it just doesn't recognize the change and the chache still stays the same.
> Any ideas how to solve this?

replace script part in index.html with this:
```
  <script>
    function _beginServiceWorkerUpdateFlow(registration) {
      if (
        window.confirm("New version of the app is available. Refresh now?") &&
        registration.waiting
      ) {
        // let waiting Service Worker know it should become active
        registration.waiting.postMessage("skipWaiting");
      }
    }
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker.register("flutter_service_worker.js").then(
          function (registration) {
            if (registration.waiting) {
              _beginServiceWorkerUpdateFlow(registration);
            }

            // detect Service Worker update available and wait for it to install
            registration.addEventListener("updatefound", () => {
              if (registration.installing) {
                // wait until the new Service worker is actually installed
                registration.installing.addEventListener(
                  "statechange",
                  () => {
                    if (registration.waiting) {
                      // if there's an existing Service Worker, show the prompt
                      if (navigator.serviceWorker.controller) {
                        _beginServiceWorkerUpdateFlow(registration);
                      } else {
                        // otherwise it's the first install, there is nothing to do
                        console.log(
                          "Service Worker initialized for the first time"
                        );
                      }
                    }
                  }
                );
              }
            });

            let refreshing = false;

            // detect controller change and refresh the page
            navigator.serviceWorker.addEventListener(
              "controllerchange",
              () => {
                if (!refreshing) {
                  window.location.reload(true);
                  refreshing = true;
                }
              }
            );
          },
          function (err) {
            // registration failed
            console.log("ServiceWorker registration failed: ", err);
          }
        );
      });
    }
  </script>
```
and check again..

**Comment by shubiour** [comment]
> I had the same problem,
> 
> I found this answer https://stackoverflow.com/a/61720981
> and it worked for me, as a temporary fix.
> 
> edit your index.html, before building and change the version number, in this line
> 
> <script src="main.dart.js?version=1" type="application/javascript"></script>

Yes, I have also solved this issue by adding this in index.html "main.dart.js?version=1"

**Comment by tazik561** [comment]
> > I had the same problem,
> > I found this answer https://stackoverflow.com/a/61720981
> > and it worked for me, as a temporary fix.
> > edit your index.html, before building and change the version number, in this line
> > <script src="main.dart.js?version=1" type="application/javascript"></script>
> 
> Yes, I have also solved this issue by adding this in index.html "main.dart.js?version=1"

It didn't work for me .
