### ISSUE TITLE
Gradient underline when textfield is selected

### ISSUE THREAD

**Issue by TMaxedCode** [flutter/flutter#57976]
## Use case
This would improve the appearance of a textfield

## Proposal
Allow users to display a linear gradient on the underline / border-bottom of a textfield when it is selected.

**Comment by TahaTesser** [comment]
Hi @TMaxedCode 
TextField follows material design guidelines and if you need some behaviour, you need to implement in your code , you can try custom decoration 
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it 
Thank you
