### ISSUE TITLE
TabBar docs missing how indicator behaves with Theme

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#57970]
The `TabBar` docs mention:

```dart
  /// If [indicator] is not null, then [indicatorWeight], [indicatorPadding], and
  /// [indicatorColor] are ignored.
```

But it fails to remind the user that an `indicator` can be provided into the App's theme using `TabBarTheme`, in that case the internal reference `_indicator` won't be null and `indicatorColor` and the others will be ignored. This brings confusion as the `TabBar` `indicator` property was indeed `null`, but the `TabBar` got an `indicator` from the App's `Theme`.

I suggest that the docs get updated to include this case or the behavior of the `TabBar` be updated to match its docs.

**Comment by PushkaraSharma** [comment]
I would like to take up this task and resolve it but I don't know where to start and I am not able to find the doc regarding this issue. Please help me out by linking me with the correct doc. Thanks in advance

**Comment by anisalibegic** [comment]
> I would like to take up this task and resolve it but I don't know where to start and I am not able to find the doc regarding this issue. Please help me out by linking me with the correct doc. Thanks in advance

It's right [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tabs.dart#L598)!
