### ISSUE TITLE
[web]: API call are not execute in Release build of Flutter web

### ISSUE THREAD

**Issue by GoyalSidhant** [flutter/flutter#57986]
Describe your issue and include the command you're running, flutter_web version, browser version
API call are not execute in Release build of Flutter web
Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-IN)

**Comment by TahaTesser** [comment]
Hi @GoyalSidhant 
can you please provide your `flutter doctor -v` and `flutter run --release -d Chrome`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
