### ISSUE TITLE
Test that we support multiple hero quests at a time

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5798]
For example, if you're going from page A to page B then B to C while the A to B transition is still ongoing, and there's a hero that exists on A and B but not C, we need the animation to "finish" on B and not be affected by the B to C transition.

Today we decide the hero doesn't have a home on C and we spin it away instead.

**Comment by eseidelGoogle** [comment]
This presumably should be assigned to @HansMuller?  I think he's working on this now.

**Comment by HansMuller** [comment]
I am and now it is.

**Comment by Hixie** [comment]
@HansMuller this is like the other one, done except for tests, right?
