### ISSUE TITLE
flutter pub get Got socket error trying to find package path at https://pub.flutter-io.cn.

### ISSUE THREAD

**Issue by xujr217** [flutter/flutter#57982]
flutter SDK flutter_windows_1.17.1-stable.zip 

flutter packages get
Running "flutter pub get" in test_app...
Got socket error trying to find package path at https://pub.flutter-io.cn.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in test_app...                    (This is taking an unexpectedly long time.)

**Comment by TahaTesser** [comment]
hI @xujr217 
You need do mirror site for pub from [Configuring Flutter to use a mirror site
](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) when using Flutter china

if the problem persist after configuration,  can you please provide your `flutter doctor -v` and `flutter pub get -v`? 
Thank you"

**Comment by xujr217** [comment]
@TahaTesser 
The reason is: firewall intercepts socket.

Thank you
