### ISSUE TITLE
appbundle release build is crashing on stable versions 1.17.0 and 1.17.1

### ISSUE THREAD

**Issue by abuzarsaddiqui** [flutter/flutter#57983]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by sinano1107** [comment]
I'm probably experiencing the same bug.

**Comment by sinano1107** [comment]
My app crashes when I launch apk with emulator

**Comment by TahaTesser** [comment]
Hi. @abuzarsaddiqui 
can you please provide your `flutter doctor -v` and `flutter run --release`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
