### ISSUE TITLE
Under the Container Define Row Error

### ISSUE THREAD

**Issue by pilojanmobile** [flutter/flutter#57995]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by helinanever** [comment]
Hi @pilojanmobile 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`. It would also help if you could explain the steps to reproduce the bug in detail
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as additional information isn't provided
