### ISSUE TITLE
Plugin error after flutter upgrade

### ISSUE THREAD

**Issue by borgelo** [flutter/flutter#57999]
## Steps to Reproduce

I have the same issue as described in #46807
I did a flutter upgrade and are now unable to build my project. 

- Unable to find a matching configuration of project :url_launcher_macos
- Unable to find a matching configuration of project :path_provider_macos
- Unable to find a matching configuration of project :shared_preferences_macos
- Unable to find a matching configuration of project :shared_preferences_web

url_launcher: 5.4.10
shared_preferences: ^0.5.7+3

<details>
  <summary>Logs</summary>

AILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:lintVitalProductionRelease'.
[        ] > Could not resolve all artifacts for configuration ':app:developmentDebugRuntimeClasspath'.
[        ]    > Could not resolve project :url_launcher_macos.
[        ]      Required by:
[        ]          project :app > project :url_launcher
[        ]       > Unable to find a matching configuration of project :url_launcher_macos:
[        ]           - None of the consumable configurations have attributes.
[        ]    > Could not resolve project :path_provider_macos.
[        ]      Required by:
[        ]          project :app > project :path_provider
[        ]       > Unable to find a matching configuration of project :path_provider_macos:
[        ]           - None of the consumable configurations have attributes.
[        ]    > Could not resolve project :shared_preferences_macos.
[        ]      Required by:
[        ]          project :app > project :shared_preferences
[        ]       > Unable to find a matching configuration of project :shared_preferences_macos:
[        ]           - None of the consumable configurations have attributes.
[        ]    > Could not resolve project :shared_preferences_web.
[        ]      Required by:
[        ]          project :app > project :shared_preferences
[        ]       > Unable to find a matching configuration of project :shared_preferences_web:
[        ]           - None of the consumable configurations have attributes.

flutter analyze:
No issues found! (ran in 7.0s)

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287, locale nb-NO)
    • Flutter version 1.12.13+hotfix.8 at /Applications/flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/borgelotre/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.8)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

</details>

**Comment by TahaTesser** [comment]
Hi. @borgelo 
Looks like you're using 4 months old `stable` channel 
Please upgrade to latest `Channel stable, v1.17.1` and try agaiin

If the problem persist after upgrade,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by borgelo** [comment]
Upgrading to v1.17.1 fixed it. Thank  you!
