### ISSUE TITLE
ImagePicker.pickVideo() in IOS 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff8062d200' 

### ISSUE THREAD

**Issue by ThalapathySiva** [flutter/flutter#57990]
After picking the video application crashed with this exception

Code : 
               
             File videoFile = await ImagePicker.pickVideo(source: ImageSource.gallery);
              if (videoFile != null) {
              if (videoFile.lengthSync() >= 100000000) {
               AppUtils.showToast("Video Can't be more than 100 mb");
              return;
              }
              PostMedia postMedia = PostMedia.base();

             postMedia.postMediaFile = videoFile;
            postMedia.mediaType = MediaType.video;

            final thumnbnailString = await VideoThumbnail.thumbnailFile(
            video: videoFile.path,
           imageFormat: ImageFormat.JPEG,
           maxHeight: 200,
          maxWidth:
           500, 
          quality: 25,
          );
         final file1 = File(thumnbnailString);
         Uint8List bytes = file1.readAsBytesSync();
         postMedia.videoThumnail = bytes;
         post.postMedias.add(postMedia);
         }

default	11:48:39.449737+0530	Runner	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff8062d200'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5ac34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e3e90c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e40bf8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00007fff259615bc -[NSURL(NSURL) initFileURLWithPath:] + 68
	6   Foundation                          0x00007fff25961f63 +[NSURL(NSURL) fileURLWithPath:] + 33
	7   video_thumbnail                     0x0000000109b5b5b8 -[VideoThumbnailPlugin handleMethodCall:result:] + 1880
	8   Flutter                             0x00000001<…>

flutter doctor - v : 
'[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.17.1 at /Users/tartlabs/bin/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tartlabs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • B15946A2-4958-41A4-B517-FE3815AF303D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!

flutter run --verbose : 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException',
reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff8062d200'
[        ] [DEVICE LOG] *** First throw call stack:
[        ] [DEVICE LOG] (
[        ] [DEVICE LOG]         0   CoreFoundation                      0x00007fff23e39f0e
__exceptionPreprocess + 350
[        ] [DEVICE LOG]         1   libobjc.A.dylib                     0x00007fff50ad79b2
objc_exception_throw + 48
[        ] [DEVICE LOG]         2   CoreFoundation                      0x00007fff23e5ac34
-[NSObject(NSObject) doesNotRecognizeSelector:] + 132
[        ] [DEVICE LOG]         3   CoreFoundation                      0x00007fff23e3e90c
___forwarding___ + 1436
[        ] [DEVICE LOG]         4   CoreFoundation                      0x00007fff23e40bf8
_CF_forwarding_prep_0 + 120
[        ] [DEVICE LOG]         5   Foundation                          0x00007fff259615bc
-[NSURL(NSURL) initFileURLWithPath:] + 68
[        ] [DEVICE LOG]         6   Foundation                          0x00007fff25961f63
+[NSURL(NSURL) fileURLWithPath:] + 33
[        ] [DEVICE LOG]         7   video_thumbnail                     0x000000010d4ad5b8
-[VideoThumbnailPlugin handleMethodCall:result:] + 1880
[        ] [DEVICE LOG]         8   Flutter                             0x00000001<…>
[   +2 ms] *** First throw call stack:
[        ] (
[        ]      0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess +
350
[        ]      1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
[        ]      2   CoreFoundation                      0x00007fff23e5ac34 -[NSObject(NSObject)
doesNotRecognizeSelector:] + 132
[        ]      3   CoreFoundation                      0x00007fff23e3e90c ___forwarding___ + 1436
[        ]      4   CoreFoundation                      0x00007fff23e40bf8 _CF_forwarding_prep_0 +
120
[        ]      5   Foundation                          0x00007fff259615bc -[NSURL(NSURL)
initFileURLWithPath:] + 68
[        ]      6   Foundation                          0x00007fff25961f63 +[NSURL(NSURL)
fileURLWithPath:] + 33
[        ]      7   video_thumbnail                     0x000000010d4ad5b8 -[VideoThumbnailPlugin
handleMethodCall:result:] + 1880
[        ]      8   Flutter                             0x00000001<…>
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future
not completed

**Comment by TahaTesser** [comment]
Hi @ThalapathySiva 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ThalapathySiva** [comment]
@TahaTesser  I have updated it! please see it

**Comment by TahaTesser** [comment]
Hi  @ThalapathySiva 
You're missing permission keys in your `info.plist`

Please add these in your `info.plist` by opening it as source code
```
    <key>NSCameraUsageDescription</key>
    <string>Used to demonstrate image picker plugin</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>Used to capture audio for image picker plugin</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Used to demonstrate image picker plugin</string>
```

Thank you

**Comment by ThalapathySiva** [comment]
![tempsnip](https://user-images.githubusercontent.com/35165669/82995327-12eb5900-a021-11ea-8e3c-8af3c176a1d6.png)


I have added already still error occurs !

**Comment by ThalapathySiva** [comment]
fixed, actually it was other plugin issue caused, Thanks

**Comment by abdullah432** [comment]
> caused

Which plugin?
