### ISSUE TITLE
Black screen when permission dialog show

### ISSUE THREAD

**Issue by daibao520** [flutter/flutter#58005]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2016.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X This install is older than the minimum recommended version of 2017.1.0.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

Android
steps
1 open a new flutter project
2 request permission and the permission dialog show
3 go to background and wait for 5 seconds
4 back to foreground
5 black screen show, some device may not show black screen but it creates another main activity and a new flutter engine attach with activity then there will be two flutter engine.

**Comment by iapicca** [comment]
Hi @daibao520 
I see there's an open [issue](https://github.com/flutter/flutter/issues/58002) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by daibao520** [comment]
@iapicca ok
