### ISSUE TITLE
Downloads from Archive page fail to run ("No such file or directory")

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#58003]
This came up in https://github.com/microsoft/vscode-dev-containers/issues/162#issuecomment-633937820 and I can repro here using the zip files for both Dev and Beta for macOS.

I downloaded the macOS zips from the Flutter archive page (Beta and Dev):

https://flutter.dev/docs/development/tools/sdk/releases?tab=macos

I unzipped and ran `../../bin/flutter run -v` from the `examples/hello_world` folders. They both fail with errors like this:

```
⣻[ +154 ms] 
                    Compiler message:
[   +1 ms] lib/main.dart:5:8: Error: Error when reading '/b/s/w/ir/k/archive/flutter/packages/flutter/lib/widgets.dart': No such file or directory
[        ] import 'package:flutter/widgets.dart';
[        ]        ^
[  +11 ms] lib/main.dart:12:16: Error: Method not found: 'Key'.
[        ]           key: Key('title'),
[        ]                ^^^
[        ] lib/main.dart:13:26: Error: Getter not found: 'TextDirection'.
[        ]           textDirection: TextDirection.ltr
[        ]                          ^^^^^^^^^^^^^
[        ] lib/main.dart:11:9: Error: Method not found: 'Text'.
[        ]         Text('Hello, world!',
[        ]         ^^^^
[        ] lib/main.dart:9:11: Error: Method not found: 'Center'.
[        ]     const Center(
[        ]           ^^^^^^
[        ] lib/main.dart:8:3: Error: Method not found: 'runApp'.
[        ]   runApp(
[        ]   ^^^^^^
```

The path in the error (`/b/s/w/ir/k/archive/flutter/packages/flutter/lib/widgets.dart`) comes from the `package_config.json` files. Running `flutter update-packages` resolves the issue.

As far as I can tell from the steps on the website, it should not be required to run `flutter update-packages` after extracting the archive version, it should just work first time? Running `flutter doctor` does not list any issues, nor fix the problem.

**Comment by jonahwilliams** [comment]
It looks like these uploads are including the .dart_tool/package_config.json file. We should probably remove this before uploading
