### ISSUE TITLE
maxLines property of TextPainter class is not calculated in web 

### ISSUE THREAD

**Issue by Dharanipalani** [flutter/flutter#58000]
I used the TextPainter class to draw the text and in which the maxLines property is not automatically calculated based on the number of lines on the web.

Code Snippet:

    void _drawText(Canvas canvas, String text, Offset point, ChartTextStyle style,
    [int angle]) {
      final Color color = style.color;
      final double fontSize = style.fontSize;
      final String fontFamily = style.fontFamily;
      final FontStyle fontStyle = style.fontStyle;
      final FontWeight fontWeight = style.fontWeight;
      final TextSpan span = TextSpan(
          text: text,
          style: TextStyle(
              color: color,
              fontSize: fontSize,
              fontFamily: fontFamily,
              fontStyle: fontStyle,
              fontWeight: fontWeight));
      final TextPainter tp = TextPainter(
          text: span,
          textDirection: TextDirection.ltr,
          textAlign: TextAlign.center);
      tp.layout();
      canvas.save();
      canvas.translate(point.dx, point.dy);
      Offset labelOffset = const Offset(0.0, 0.0);
      If (angle != null && angle > 0) {
        canvas.rotate(_degreeToRadian(angle));
        labelOffset = Offset(-tp.width / 2, -tp.height / 2);
      }
      tp.paint(canvas, labelOffset);
      canvas.restore();
    }

Web Screenshot:
![image](https://user-images.githubusercontent.com/19763272/82900874-ca796000-9f7a-11ea-8b6d-976440b97a9b.png)

Mobile Screenshot:
![image](https://user-images.githubusercontent.com/19763272/82901217-45db1180-9f7b-11ea-906e-217ebef3dac9.png)

**Comment by VladyslavBondarenko** [comment]
Hi @Dharanipalani 
does it work with FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT?
see https://github.com/flutter/flutter/issues/33523

**Comment by VladyslavBondarenko** [comment]
@Dharanipalani 
I hope you've solved the issue.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Comment by ashishkumart** [comment]
> @Dharanipalani
> I hope you've solved the issue.
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

Hi, Please check this [example ](https://www.developerlibs.com/2019/07/flutter-text-read-more-expand-feature.html)

I have used this. It uses the TextPainter with max line, but it is not working on Web.

Thanks for your help :)

**Comment by VladyslavBondarenko** [comment]
Hi @ashishkumart 
please file a new issue for this with filling out template
