### ISSUE TITLE
[TextField] value not live update when press delete key

### ISSUE THREAD

**Issue by peterlpt** [flutter/flutter#58006]
## Steps to Reproduce

1. Run `flutter create`.
2. Update main.dart as follows: (add a textField to children)

```dart
//...
children: <Widget>[
    Text(
      'You have pushed the button this many times:',
    ),
    TextField( // add a textField widget
    ),
    Text(
      '$_counter',
      style: Theme.of(context).textTheme.headline4,
    ),
  ],
//...
```

3. `flutter run`,  input something, and press delete key, then the value will not live update on some keyboard, just like this gif.

![image](https://github.com/peterlpt/peterlpt.github.io/blob/master/images/posts/flutter/textfield-issue-value-not-live-update.gif?raw=true)

4. this issue not exist in `Channel stable, 1.17`

<details>
  <summary>flutter doctor -v</summary>

$ flutter doctor -v
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.18.0-11.1.pre at /Users/peter/Data/flutter
    • Framework revision 2738a1148b (13 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Data/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peter/Data/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @peterlpt 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final _counter = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            TextField(// add a textField widget
                ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 


![20200526_202211](https://user-images.githubusercontent.com/48603081/82915753-c9522e00-9f8e-11ea-8514-bde8bd659fcf.gif)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5

• No issues found!

``` 

</details> 


Please try this code smaple
Thank you

**Comment by peterlpt** [comment]
Hi @TahaTesser 
yeah, I reproduce this issues on `Channel beta, 1.18.0-11.1.pre`, and cant on `Channel stable, v1.17.1`.

And not all keyboard(input method) can reproduce, I find this issues with [baidu keyboard](http://downapp.baidu.com/baiduinput/AndroidPhone/9.2.1.23/1/1000e/20200508100052/baiduinput_AndroidPhone_9-2-1-23_1000e.apk).
And, this may also be related to the Android system version, cause I can reproduce on the Android M device, but cant on the Android Q device, with the same input method.

**Comment by peterlpt** [comment]
channel stable & dev works fine:

<details>
<summary>flutter doctor -v (stable)</summary>

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/peter/Data/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Data/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peter/Data/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • MI NOTE LTE • e5af81b0 • android-arm • Android 6.0.1 (API 23)

</details>

<details>
<summary>flutter doctor -v (dev)</summary>

[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.19.0-1.0.pre at /Users/peter/Data/flutter
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Data/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peter/Data/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)            
    • MI NOTE LTE • e5af81b0   • android-arm    • Android 6.0.1 (API 23)
    • Web Server  • web-server • web-javascript • Flutter Tools
    • Chrome      • chrome     • web-javascript • Google Chrome 83.0.4103.61

</details>

channel beta has this issues:

<details>
<summary>flutter doctor -v (beta)</summary>
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
• Flutter version 1.18.0-11.1.pre at /Users/peter/Data/flutter
• Framework revision 2738a11 (13 days ago), 2020-05-13 15:24:36 -0700
• Engine revision ef9215ceb2
• Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/peter/Data/Android/sdk
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /Users/peter/Data/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
• All Android licenses accepted.
</details>

**Comment by TahaTesser** [comment]
Hi @peterlpt 
If it works on `dev` then it will get to `beta` channel eventually
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you"
