### ISSUE TITLE
Re-enable flaky "Mac Web Engine" Builder caused by timeout on the "felt test" step.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#58012]
This step times out after about 3 hours. The flakiness needs to be addressed and perhaps the timeout lowered. [An example is here](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/296).
![Capture](https://user-images.githubusercontent.com/44085/82920684-721b7180-9f2c-11ea-9659-c1d45b65c465.PNG)

**Comment by christopherfujino** [comment]
I disabled this test in https://github.com/flutter/cocoon/pull/782, we should re-enable once the flake is fixed.

**Comment by yjbanov** [comment]
Thank you @christopherfujino

**Comment by chinmaygarde** [comment]
Currently the tree is red because of this https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/328. @christopherfujino Can you confirm that all we need is a force push to get things going?

**Comment by christopherfujino** [comment]
> Currently the tree is red because of this https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/328. @christopherfujino Can you confirm that all we need is a force push to get things going?

@digiter since we're getting 500s from `luci_status.dart`, does that mean the "Mac Web Engine" luci job is still getting triggered?

**Comment by christopherfujino** [comment]
Ok, I also landed https://github.com/flutter/infra/pull/129. We should be good once it's propagated (I'll update here when that's happened)

**Comment by christopherfujino** [comment]
@chinmaygarde updated config propagated--"Mac Web Engine" should be disabled.

**Comment by chinmaygarde** [comment]
It still requires a force push to get things going again right?

**Comment by christopherfujino** [comment]
You mean to get past the red "luci-engine" task? Then yes :)

**Comment by chinmaygarde** [comment]
Yes. We need manual intervention to get past a flake.

**Comment by nturgut** [comment]
@christopherfujino I think due to the change I'm not able to trigger the these tests anymore using led. Unless I have access to led, I won't be able to test any fixes and fix this issue. I'm also not able to do other development related to Mac testing. 

/cc @godofredoc 

I'm getting an error: "User .... is not allowed to schedule tasks in the pool "luci.flutter.try", see pools.cfg"

Please let me know when you enable the bots. We can change the recipe and remove that step that created the flake as an alternative solution.

**Comment by nturgut** [comment]
@kf6gpe Thanks for adding labels!

I think this issue is higher priority. Flutter Web teams testing and development of test harnesses for Mac/Safari is fully stopped.

**Comment by nturgut** [comment]
@christopherfujino thanks for the cocoon changes. I'll try a few changes and update the issue.

**Comment by godofredoc** [comment]
1) You should be able to kill processes created by the same user without sudo.
2) This is a host configuration that needs to be applied through provisioning not at runtime.

For security reasons the user running tasks is not a sudoer. I'd recommend to remove all the sudo calls from the tool.

**Comment by nturgut** [comment]
As far as I know, we need password for `pkill`. I'll try to do it without password and let you know.

**Comment by nturgut** [comment]
(1) Looks like pkill works, I'll send a recipe change which kills open safari tabs and try to enable "Mac Web Engine" to see how much it helps with the timeout. 

(2) How can we change the host configurations for increasing the user limits?

**Comment by nturgut** [comment]
I enabled the tests, even though try bots tried are failing in many tests done before, looks like prod bots started failing now. I think this is the related issue: https://github.com/flutter/flutter/issues/58045

We should make sure all Safari version are the same on all bots and they are all 13.

**Comment by nturgut** [comment]
Still working on this, adding this PR to collect more info on the Safari installed on each bot: https://github.com/flutter/engine/pull/20123#discussion_r463165298

**Comment by nturgut** [comment]
@godofredoc Do we know when is the new machines arrive? In order to run web_engine.y only on those bots for MacOS shall I create a new pool in flutter/infra? https://github.com/flutter/infra/blob/1ef46a96c4ef97ff680240dde366879ef3709221/config/lib/common.star#L425

Or is there a way of filtering out bots by ids?
