### ISSUE TITLE
Tool to analyze app size

### ISSUE THREAD

**Issue by rahuldange09** [flutter/flutter#58028]
It would be great if flutter provides some tool to analyze app size. (Specifically for release builds)
Like how much size is used by pubs, assets, files.

As android studio has analyze apk option, which helps to identify assets but not other as it is at android level.

It would be grate if such option comes. Which will come extremely handy in optimizing app size.

**Comment by TahaTesser** [comment]
Hi @rahuldange09 
Each platform has different app sizes, you can optimise  app size according to the platform 
Please check out [Measuring your app's size](https://flutter.dev/docs/perf/app-size)

if you disagree please write in the comments and I will reopen it. 
Thank you"
