### ISSUE TITLE
Undefined name 'context'. Try correcting the name to one that is defined, or defining the name.

### ISSUE THREAD

**Issue by mucahitkmlay** [flutter/flutter#58026]
**### This is my code but i never change page . Error = Undefined name 'context'.
Try correcting the name to one that is defined, or defining the name.**

class EntryItem extends StatelessWidget {
  const EntryItem(this.entry);

  final Entry entry;

  Widget _buildTiles(Entry root) {
    if (root.children.isEmpty)
      return ListTile(
        title: Text(root.title, style: TextStyle(color: Colors.black)),
        trailing: Icon(
          Icons.keyboard_arrow_right,
          color: Colors.white,
        ),
        onTap: () {
          **### Navigator.of(context).pushNamedAndRemoveUntil('/gettingStarted', (route) => false)**
        },
        selected: true,
      );
    return ExpansionTile(
      key: PageStorageKey<Entry>(root),
      trailing: Icon(
        Icons.keyboard_arrow_right,
      ),
      title: Text(
        root.title,
        style: TextStyle(color: Color(0xFF2F6CE6)),
      ),
      children: root.children.map(_buildTiles).toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return _buildTiles(entry);
  }
}

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by mucahitkmlay** [comment]
okey thank you
