### ISSUE TITLE
Unable to copy text to clipboard + log spam from TextField when viewing Flutter App in Chrome Remote Desktop. 

### ISSUE THREAD

**Issue by ryanknauer** [flutter/flutter#58035]
## Steps to Reproduce

Part 1 (log spam)
1. Open a flutter application in Chrome Remote Desktop
2. Navigate to a visible TextField
Actual: The following log prints to the console and repeats with any interaction(focusing, typing):

[ERROR:third_party/flutter_engine/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Missing window error, Clipboard is not available in GLFW headless mode., null). NOTE: Full error copied below with stack trace. 

Expected: A single error log (ideally without a stack trace)

Part 2:

3. Attempt to copy text in the TextField (ctrl-shift-c)

Expected: Text copies to clipboard
Actual: Text does not copy to clipboard

Device: Linux (on physical device)
Application: Flutter Desktop App - Google Internal (contact me if more info needed).

<details>
  <summary>Logs</summary>

Full Error Log: 

[ERROR:third_party/flutter_engine/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Missing window error, Clipboard is not available in GLFW headless mode., null)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:435:18)
#3      Clipboard.getData (package:flutter/src/services/clipboard.dart:56:71)
#4      ClipboardStatusNotifier.update (package:flutter/src/widgets/text_selection.dart:1523:15)
#5      ClipboardStatusNotifier.addListener (package:flutter/src/widgets/text_selection.dart:1540:7)
#6      EditableTextState.initState (package:flutter/src/widgets/editable_text.dart:1205:23)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4649:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
#14     _RenderDecorationElement._mountChild (package:flutter/src/material/input_decorator.dart:1549:30)
#15     _RenderDecorationElement.mount (package:flutter/src/material/input_decorator.dart:1564:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)

```
```
Flutter Doctor: 

[✓] Flutter (Channel google3, on Linux, locale en_US.UTF-8)
    • Framework revision 9d58a87066 (4 days ago), 2020-05-22T00:00:00.000
    • Engine revision 9ce1e5c5c7
    • Dart version 7706afbcf5

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_181-google-v7-309648555-309648555)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

[✓] Google3 (on linux)
    • KVM enabled

```
```

</details>

**Comment by stuartmorgan** [comment]
> Clipboard is not available in GLFW headless mode

What you're describing shouldn't be headless mode. It sounds like I may have broken something in the refactoring to support headless.

**Comment by TimWhiting** [comment]
Note: for some reason, I had to run my app once with `flutter run -d Linux -v`, after upgrading to the latest master branch before this error went away. Probably some caching problem, since I hadn't changed my app at all. (Adding the verbose flag seems to have forced it to rebuild).

**Comment by stuartmorgan** [comment]
> Probably some caching problem

https://github.com/flutter/flutter/issues/58049
