### ISSUE TITLE
TabBar responding incorrectly to window resize. 

### ISSUE THREAD

**Issue by ryanknauer** [flutter/flutter#58036]
## Steps to Reproduce

1. Open flutter application containing a TabBar
2.  Navigate to the last tab in the TabBar
3. Expand the window

Expected: TabView expands normally 
Actual: TabView position moves off the screen to the left.

Device: Linux (on physical device)
Application: Flutter Desktop App - Google Internal (contact me if more info needed).

<details>
  <summary>Logs</summary>

No Error Logs Produced 

```
```
Flutter Doctor: 

[✓] Flutter (Channel google3, on Linux, locale en_US.UTF-8)
    • Framework revision 9d58a87066 (4 days ago), 2020-05-22T00:00:00.000
    • Engine revision 9ce1e5c5c7
    • Dart version 7706afbcf5

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_181-google-v7-309648555-309648555)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

[✓] Google3 (on linux)
    • KVM enabled

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @ryanknauer 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
