### ISSUE TITLE
Gallery: missing taps on drawer icon from homescreen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5804]
We seem to be missing taps when trying to open the drawer with the icon, in the Gallery, on Android.

**Comment by sethladd** [comment]
Maybe addressed by https://github.com/flutter/flutter/pull/5802 ? cc @HansMuller

**Comment by HansMuller** [comment]
Yes, I think that should fix this :-)

**Comment by HansMuller** [comment]
Fixed by #5802
