### ISSUE TITLE
MacOS bots have different versions of Safari

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#58045]
Safari bots have different version of Safari. For example this one has Safari12:
https://logs.chromium.org/logs/flutter/led/nurhan_google.com/5ba142ce8ddb0bb993e02fc3e87a4d1f59fef6ed24566442012512cf1b7106ab/+/steps/all_apps/0/stdout

This one runs 13.0.5: https://logs.chromium.org/logs/flutter/led/nurhan_google.com/51615689552253542b4f41b4619f630a5f44a93566811e888dbc261f38c518c0/+/steps/all_apps/0/stdout

Can we update all the Safari browsers to same version?

(note: Since 12 and 13 versions are drastically different on a few cases, I suspect this might also be the reasons of web unit tests are being flaky time to time.)

**Comment by nturgut** [comment]
@yjbanov suggested we can also blacklist some of the bots that has Safari12. Is it possible to blacklist bots when running tests?

**Comment by yjbanov** [comment]
Raising to P2 as this is blocking our ability to protect Web customers from regressions on Safari.

**Comment by yjbanov** [comment]
@godofredoc can we assign someone to work on this?

**Comment by godofredoc** [comment]
Versions of Safari are tied to system updates on Mac machines and there is no way to reliably ensure all of them will have the exact same version.

The best way to ensure builds are replicable and they all use the same version requires to bundle the safari binary as a cipd package that is downloaded and installed at the task execution time.

Have you tried to create a self contained binary for the safari browser?

**Comment by nturgut** [comment]
I see, so it is hard to keep versions all the same. When I did the initial investigations I couldn't find a way of installing safari separately. We can only download beta's or tech previews https://developer.apple.com/safari/download/ (which might also have their own issues)

One alternative can be using WebKit instead of Safari. @yjbanov  Shall we try to pursue that solution for Desktop browser testing.

**Comment by godofredoc** [comment]
Another possibility is to setup a couple mac machines in 1808 where web_engine team maintains the specific versions of safari required for testing and have full control of them.

**Comment by yjbanov** [comment]
Bumping this down to P3 so that the issue doesn't keep popping up during the critical issue triage, until we know what we want to do here. This is still high priority in general, as we are unable to test on Safari.

**Comment by yjbanov** [comment]
The WebKit idea is interesting. I'm not sure how close it is to Safari w.r.t. things we want to be able to test (rendering, clipboard, text editing, etc).

**Comment by yjbanov** [comment]
Custom machines in 1808 can work, but we'd want more than a couple, at least until we're unable to compile separately from running tests.

**Comment by nturgut** [comment]
I'll install a Webkit and try to see how autofill/clipboard features are similar to Safari (or different).

**Comment by godofredoc** [comment]
Thanks nturgut, if it works that will allow us to run web engine tests on all the existing and new macs without custom configurations.

**Comment by nturgut** [comment]
@godofredoc did you had a chance to try using 2 different pools for bots for Mac Web Engine tests? I'm assigning the issue to you, please let me know if there is anything I can help with. I'm leaving the issue unassigned for now.

**Comment by godofredoc** [comment]
You can try with one of the machines in this list: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&k=pool&s=id

They'll all have mac os 10.15 and the safari browser version will be consistent in all of them.
