### ISSUE TITLE
[Android integration/v2 embedded] plugins used by service (started in background when app is terminated)

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#58048]
## Steps to Reproduce

1. Create a static handler in your app that is called when your app is terminated. One example (that I'm using) is a background notification handler using firebase messaging. Although after few hours of googling I saw some other projects has it too.

2. Use a plugin inside the static handler of your app. Personally I need the `flutter_local_notifications` and the `shared_preferences` plugins.

3. When the callback is called, you'll get an exception (can be seen using `adb logcat`) about a missing plugin exception, such as this:

```
 MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

# Problem explained?

From what I can tell, the activity is registering the plugins.
However, when a static method is executed the activity doesn't start and the plugins aren't registered.

# Workaround

Currently the workaround is to register the plugins manually in the application (and not just the activity).  Since the `GeneratedPluginRegistrant` is using `FlutterEngine` (even though it only needs the `PluginRegistry`), we can't call the static method either, so more manual work needs to be done.
Here is what I have currently:

`MyApp.kt`:

```
package com.my.app;

import android.content.Context
import androidx.multidex.MultiDex
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import io.flutter.view.FlutterMain

class MyApp : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
        FlutterMain.startInitialization(this)
    }

    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        MultiDex.install(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
        FlutterLocalNotificationsPluginRegistrant.registerWith(registry)
    }
}
```

`MainActivity.kt`:
```
package com.my.app

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity(), PluginRegistry.PluginRegistrantCallback {
    override fun registerWith(registry: PluginRegistry) {
        FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
    }

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

p.s.
the `registerWith` part is needed for firebase cloud messaging and isn't relevant to this issue, but I left it anyway.

`FirebaseCloudMessagingPluginRegistrant.kt`:
```
package com.my.app

import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin

class FirebaseCloudMessagingPluginRegistrant {
    companion object {
        fun registerWith(registry: PluginRegistry) {
            if (alreadyRegisteredWith(registry)) {
                return;
            }
            FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
        }

        private fun alreadyRegisteredWith(registry: PluginRegistry): Boolean {
            val key = FirebaseCloudMessagingPluginRegistrant::class.java.name
            if (registry.hasPlugin(key)) {
                return true
            }
            registry.registrarFor(key)
            return false
        }
    }
}
```

# Actual question ?

The actual question is then - is there a better way to register plugins? should one even register all those plugins?

and even if not - perhaps there should be an easier way than to create such a 'Registrant' class for each plugin manually ?

# Details
<details>

```
Analyzing mbl2...
No issues found! (ran in 7.2s)
```

```

[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.19.0-1.0.pre at D:\dev\Flutter
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at D:/dev/Android/Sdk
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = D:/dev/Android/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.2
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.6668.156

[√] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server          • web-server    • web-javascript • Flutter Tools
    • Chrome              • chrome        • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @matanshukry 
When using `shared_preferences` with `firebase_messaging` to reproduce, the app fails to builds to run, might just me 

Can you please provide a reproducible code repository? and `flutter doctor -v`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
