### ISSUE TITLE
clarify docs on how Center Widget and TextAlign.center behave differently 

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5805]
We should make it clear in the docs for Center and the docs for text.textAlign/TextAlign that one centers the whole block, whereas the other centers every line in the block.

**Comment by TahaTesser** [comment]
This isn't mentioned yet in the docs

https://api.flutter.dev/flutter/widgets/Center-class.html
https://github.com/flutter/flutter/blob/1ad9baa8b99a2897c20f9e6e54d3b9b359ade314/packages/flutter/lib/src/widgets/basic.dart#L1849
https://api.flutter.dev/flutter/widgets/Text/textAlign.html
https://github.com/flutter/flutter/blob/1ad9baa8b99a2897c20f9e6e54d3b9b359ade314/packages/flutter/lib/src/widgets/text.dart#L357
