### ISSUE TITLE
[web][↑↓]Want to use [↑ ↓] to scroll the screen

### ISSUE THREAD

**Issue by nttd-jieyangxu** [flutter/flutter#58057]
i use flutter for web.
i also want to use [↑ ↓] to scroll the page i created just like any other network page on the chrome or IE.

**Comment by iapicca** [comment]
Hi @nttd-jieyangxu 
I see there's an open [issue](https://github.com/flutter/flutter/issues/43694) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by nttd-jieyangxu** [comment]
@iapicca thank you for confirm!
follow up on that issue →　that't ok!
