### ISSUE TITLE
FlutterView is not shown on Flutter 1.17

### ISSUE THREAD

**Issue by StephenZKCurry** [flutter/flutter#58054]
I use FlutterView to add a flutter page to  Android Activity，but the FlutterView is not shown on the screen.Before I updated Flutter to 1.17,it was ok.Has Flutter 1.17 changed something on FlutterView?

This is my code that add a FlutterView to Android ViewGroup:

FlutterEngine flutterEngine = new FlutterEngine(this);
flutterEngine.getNavigationChannel().setInitialRoute("route1");
flutterEngine.getDartExecutor().executeDartEntrypoint(
        DartExecutor.DartEntrypoint.createDefault()
);

FlutterView flutterView = new FlutterView(this);
FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(600, 800);
FrameLayout flContainer = findViewById(R.id.fl_container);
flContainer.addView(flutterView, lp);
flutterView.attachToFlutterEngine(flutterEngine);

**Comment by PreviousTlx** [comment]
I have the same issue!

**Comment by EdifierX** [comment]
I have the same issue!!

**Comment by EdifierX** [comment]
i find onFlutterUiDisplayed is not callback on flutter 1.17.1!!!
`FlutterView.addOnFirstFrameRenderedListener(this)`

**Comment by TahaTesser** [comment]
Hi @StephenZKCurry 
I can import `FlutterView` using `import io.flutter.embedding.android.FlutterView` on latest stable 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample including Complete `MainActivity` and `Manifest`
Thank you"

**Comment by EdifierX** [comment]
**flutter doctor -v** 
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/edison/flutter/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edison/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
**MainActivity:**
```
public class MainActivity extends AppCompatActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getWindow().setFormat(PixelFormat.TRANSLUCENT);
        ButterKnife.bind(this);
        initFragment(savedInstanceState);
    }

    private void initFragment(Bundle savedInstanceState) {
        if (savedInstanceState != null) {
            List<Fragment> fragmentList = getSupportFragmentManager().getFragments();
            for (Fragment fragment : fragmentList) {
                if (fragment instanceof DeviceListFragment) {
                    mDeviceFragment = fragment;
                }
                if (fragment instanceof ShopFragment) {
                    mShopFragment = fragment;
                }
                if (fragment instanceof MyFragment) {
                    mMyFragment = fragment;
                }
            }
        } else {
            mDeviceFragment = new DeviceListFragment();
            mShopFragment = new ShopFragment();
            mMyFragment = new MyFragment();
            FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
            fragmentTransaction.add(R.id.main_fl, mDeviceFragment);
            fragmentTransaction.add(R.id.main_fl, mShopFragment);
            fragmentTransaction.add(R.id.main_fl, mMyFragment);

            fragmentTransaction.setMaxLifecycle(mDeviceFragment, Lifecycle.State.RESUMED);
            fragmentTransaction.setMaxLifecycle(mShopFragment, Lifecycle.State.STARTED);
            fragmentTransaction.setMaxLifecycle(mMyFragment, Lifecycle.State.STARTED);

            fragmentTransaction.commit();
        }

        getSupportFragmentManager().beginTransaction()
                .show(mDeviceFragment)
                .hide(mWeightFragment)
                .hide(mSleepFragment)
                .hide(mShopFragment)
                .hide(mMyFragment)
                .commit();
    }

    @OnClick(R.id.shop_ll)
    void onClickShop(View view) {
        getSupportFragmentManager().beginTransaction().show(mShopFragment)
               .hide(mDeviceFragment)
                .hide(mMyFragment)
               .commit();
    }
}
```
**ShopFragment**
```
public class ShopFragment extends LazyFragment implements MethodChannel.MethodCallHandler, FlutterUiDisplayListener{

@BindView(R.id.shop_fl)
    FrameLayout mShopFl;

 private boolean isLoaded = false;
    protected Context mContext;
    private View rootView;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        this.mContext = context;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        if (rootView == null) {
            rootView = inflater.inflate(R.layout.fragment_shop, container, false);
        }
        return rootView;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(this, view);
    }

@Override
    public void onResume() {
        super.onResume();
        if (!isLoaded && !isHidden()) {
            lazyInit();
            isLoaded = true;
        }
    }

 @Override
    public void onDestroy() {
        super.onDestroy();
        isLoaded = false;
    }

 public void lazyInit() {
        mFlutterEngine = new FlutterEngine(mContext);
        mFlutterEngine.getNavigationChannel().setInitialRoute("/");
        mFlutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        FlutterEngineCache
                .getInstance()
                .put("flutter", mFlutterEngine);
        mFlutterView = new FlutterView(mContext);
        mFlutterView.attachToFlutterEngine(mFlutterEngine);
        mFlutterView.addOnFirstFrameRenderedListener(this);
        mShopFl.addView(mFlutterView);

        //MethodChannel
        mMethodChannel = new MethodChannel(mFlutterEngine.getDartExecutor(), METHOD_CHANNEL);
        mMethodChannel.setMethodCallHandler(this);
    }

@Override
    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        if (call.method.equals(METHOD_GET_USER_TOKEN)) {
        } else if (call.method.equals(METHOD_VISIBLE_BOTTOM_ACTION)) {
        } else {
            result.notImplemented();
        }
    }


@Override
    public void onFlutterUiDisplayed() {
        Log.i("xxx", "onFlutterUiDisplayed: ---->");
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                mShopFl.setVisibility(View.VISIBLE);
            }
        });
    }

    @Override
    public void onFlutterUiNoLongerDisplayed() {
        Log.i("xxx", "onFlutterUiNoLongerDisplayed: ---->");
    }
}
```
**Manifest:**
```
<application
        android:name=".application.MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:requestLegacyExternalStorage="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

<activity
            android:name=".ui.MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait" />
</application>
```
**style:**
```
<style name="BaseAppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowTranslucentStatus">false</item>
        <item name="android:windowTranslucentNavigation">false</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
    </style>

    <style name="AppTheme" parent="BaseAppTheme">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/theme_color_01</item>
        <item name="colorPrimaryDark">@color/theme_color_01</item>
    </style>
```

**Comment by StephenZKCurry** [comment]
> Hi @StephenZKCurry
> I can import `FlutterView` using `import io.flutter.embedding.android.FlutterView` on latest stable
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample including Complete `MainActivity` and `Manifest`
> Thank you"

**flutter doctor -v**
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.15063], locale zh-CN)
    ? Flutter version 1.18.0-11.1.pre at D:\flutter
    ? Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    ? Engine revision ef9215ceb2
    ? Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ? Android SDK at D:\sdk
    ? Platform android-R, build-tools 29.0.3
    ? Java binary at: D:\android-studio-4.0-Canary1\android-studio\jre\bin\java
    ? Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    ? Android Studio at D:\Android Studio
    ? Flutter plugin version 43.0.2
    ? Dart plugin version 192.7761
    ? Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Android Studio (version 4.0)
    ? Android Studio at D:\android-studio-4.0-Canary1\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    ? Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ? IntelliJ at D:\IntelliJ IDEA 2017.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    ? Dart plugin version 173.4700
    ? For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

**MainActivity.java**
package com.example.fluttertest;

import android.os.Bundle;
import android.widget.FrameLayout;

import androidx.appcompat.app.AppCompatActivity;

import io.flutter.embedding.android.FlutterView;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.dart.DartExecutor;

public class MainActivity extends AppCompatActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        FlutterEngine flutterEngine = new FlutterEngine(this);
        flutterEngine.getNavigationChannel().setInitialRoute("route1");
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );

        FlutterView flutterView = new FlutterView(this);
        FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(600, 800);
        FrameLayout flContainer = findViewById(R.id.fl_container);
        flContainer.addView(flutterView, lp);
        flutterView.attachToFlutterEngine(flutterEngine);
    }
}

**activity_main.xml**
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/fl_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>

**AndroidManifest.xml**
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.flutterinnative">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**style.xml**
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>

The initnitialRoute “route1” corresponds to a simple flutter page.

**Comment by jason-simmons** [comment]
I tried running the https://github.com/flutter/flutter/tree/master/examples/flutter_view sample using v1.17.1 of the framework.  The `FlutterView` rendered as expected.

I also added an `addOnFirstFrameRenderedListener` to the `FlutterView` and a call to `setInitialRoute` but did not notice any issues.

Does the `flutter_view` sample app work in your environment?

**Comment by StephenZKCurry** [comment]
> I tried running the https://github.com/flutter/flutter/tree/master/examples/flutter_view sample using v1.17.1 of the framework. The `FlutterView` rendered as expected.
> 
> I also added an `addOnFirstFrameRenderedListener` to the `FlutterView` and a call to `setInitialRoute` but did not notice any issues.
> 
> Does the `flutter_view` sample app work in your environment?

Thank you,I compared this sample with my project and finded that I missed `flutterEngine.getLifecycleChannel().appIsResumed()`,after I added this code in `onResume()` callback,the `FlutterView` was shown as expected.
I remember that in Flutter 1.12,the FlutterView can be shown on the screen without this code,but in the latest Flutter version,this code is necessary,maybe something changed on the FlutterView display process.

**Comment by StephenZKCurry** [comment]
@EdifierX You can try addind this code in `onResume()` callback.
···
flutterEngine.getLifecycleChannel().appIsResumed()
···

**Comment by EdifierX** [comment]
@StephenZKCurry OMG!!  it show. Thanks

**Comment by weichongchong** [comment]
I met same issue, and I add "flutterEngine.getLifecycleChannel().appIsResumed()" but not work.
