### ISSUE TITLE
Build apk wrong with video_player

### ISSUE THREAD

**Issue by cavanlee** [flutter/flutter#58067]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :video_player_web.                       
     Required by:                                                       
         project :app > project :video_player                           
      > Unable to find a matching configuration of project :video_player_web:
          - None of the consumable configurations have attributes.      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by TahaTesser** [comment]
Hi @cavanlee 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
