### ISSUE TITLE
flutter FFI plugin client app failed to build for Android

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#58063]
Using, flutter dev channel version, 

I was able to make a flutter ffi plugin run with the generated example project on iOS, but when doing so on Android, I seem to have JDK/gradle configuration issues, such as the following in my MainActivity.kt:

```sh
Check your module classpath for missing or conflicting dependencies
Error running 'libmynative': No JDK specified for module 'mynative_example_android'
Cannot access 'android.app.Activity' which is a supertype of 'com.my.app'. Check your module classpath or conflicting dependencies
```

How should I go about this?

I do have the following dependencies specified in my build.gradle for the Android example app

```java
dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
  implementation 'androidx.appcompat:appcompat:1.0.2'
  implementation 'androidx.core:core-ktx:1.0.2'
  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
  testImplementation 'junit:junit:4.12'
  androidTestImplementation 'androidx.test.ext:junit:1.1.0'
  androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
```

So I assume that the system will find the JDK for me. On the other hand, I built another kotlin/NDK Android project, with the same version of Android Studio 3.6.3, which runs perfectly. I basically copied most Gradle settings from there.

**Comment by dcharkes** [comment]
Can you please provide the command that you are running? And the output of `flutter doctor`?

**Comment by iapicca** [comment]
Hi @kakyoism 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
and a minimal reproducible code sample
also you may want to double-check the steps with the [documentation](https://flutter.dev/docs/development/platform-integration/c-interop#android);
if you do not wish to expose a closed source plugin
[this](https://github.com/dart-lang/samples/tree/master/ffi/hello_world) may be used as reference
Thank you

**Comment by kakyoism** [comment]
Thanks guys!

I've temporarily suppressed the errors so that they no longer block me, although I don't know exactly how.

Here is what I did:

I ran `flutter create .` under `example` folder and basically erased the Android portion of the plugin example project. And started from scratch. So far by only adding C++ files and CMakeLists.txt accordingly with some Gradle tweaks, I got the example app running without issues. 

Next I'll add the Kotlin code incrementally and see what happens.
Will keep you posted.

**Comment by TahaTesser** [comment]
Hi @kakyoism 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by kakyoism** [comment]
So I think I've got to the bottom of this problem.
The Kotlin issue was related to mainly Android ecosystem, not flutter. It was a nightmare for me though.

Just to leave tips to folks who may stumble upon this, the problem was a combination of AndroidX migration and Android Studio .idea folder not in sync with the migration. These StackOverflow questions may help:

https://stackoverflow.com/questions/34169562/unresolved-reference-kotlinx

https://stackoverflow.com/questions/57762145/cannot-access-androidx-lifecycle-lifecycleowner-what-is-the-meaning-of-error-in/62077558#62077558

https://stackoverflow.com/questions/57000915/error-adb-exited-with-exit-code-1-performing-streamed-install/62039726#62039726

https://stackoverflow.com/questions/59228006/create-method-channel-after-upgrading-flutter-can-not-resolve-method-getflutter/61003051#61003051

https://stackoverflow.com/questions/54008894/cannot-resolve-symbol-flutteractivity

**Comment by kakyoism** [comment]
> Hi @kakyoism
> given your last message I feel safe to close this issue,
> if you disagree please write in the comments
> and I will reopen it.
> Thank you

No problem. Thanks for the quick responses from you guys.
