### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by yanshouwang** [flutter/flutter#58075]
## Steps to Reproduce

1. create new project with VSCode
2. only the project folder is created and the output throws an error

## Logs

```
[security_center] flutter.bat create --ios-language swift --android-language kotlin .
Creating project ....
Running "flutter pub get" in flutter_tools...                   
Because flutter_tools depends on built_collection 4.3.2 which doesn't match any versions, version solving failed.
pub get failed (1; Because flutter_tools depends on built_collection 4.3.2 which doesn't match any versions, version solving failed.)
exit code 1
```

```
PS C:\Users\YSW> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by VisheshAtWork** [comment]
@yanshouwang Similar to [#20809](https://github.com/flutter/flutter/issues/20809) should be closed I think.

**Comment by yanshouwang** [comment]
So what's the right steps to use flutter in China? Very confused... it's too slow without the mirror

**Comment by VisheshAtWork** [comment]
Maybe going through this helps -> https://flutter.dev/community/china

**Comment by yanshouwang** [comment]
I know this, but I use the TUNA mirror instead the community mirror. As the above link talked, seems I shouldn't set the  PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL environment

**Comment by yanshouwang** [comment]
The mirror issue has been solved by the TUNA team
