### ISSUE TITLE
[image_picker] image is rotated after taking photos from camera

### ISSUE THREAD

**Issue by brizaldi** [flutter/flutter#58077]
this issue is the same as [35334](https://github.com/flutter/flutter/issues/35334), [45529](https://github.com/flutter/flutter/issues/45529), [37688](https://github.com/flutter/flutter/issues/37688), i don't know why are those marked as `closed` while the issue is still happening in the latest version.

tested on:
- Redmi Note 7 (Android 9.0)
- Redmi 8A (Android 9.0)

flutter doctor -v
```
[√] Flutter (Channel master, 1.19.0-2.0.pre.114, on Microsoft Windows [Version 10.0.18363.836], locale en-ID)
    • Flutter version 1.19.0-2.0.pre.114 at C:\Devkit\flutter
    • Framework revision 1cfd792a38 (8 days ago), 2020-05-18 18:18:16 -0500
    • Engine revision 4b1a70e6a2
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Devkit\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Devkit\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.1
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\Bahri Rizaldi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by helinanever** [comment]
Hi @brizaldi 
I see there's an accepted PR addressing the similar IOS issue the case you described.
Please take a look here [,](https://github.com/flutter/plugins/pull/1980)
For the shake of simplicity, please share the code snippet that you're facing the problem. 
and I will reproduce it for you.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
