### ISSUE TITLE
when I run "flutter run" is always still in "Installing and launching..."

### ISSUE THREAD

**Issue by jasonguiking** [flutter/flutter#58070]
What should I do in this case
![WechatIMG23](https://user-images.githubusercontent.com/3701536/82984360-9c505a80-a024-11ea-9339-659aaf8d67d1.jpeg)

![WechatIMG22](https://user-images.githubusercontent.com/3701536/82984114-0ddbd900-a024-11ea-9ef2-eaef12cb88ae.jpeg)

**Comment by VisheshAtWork** [comment]
@jasonguiking  Install the flutter and dart plugin before you run your app. Make sure there is no error while running flutter doctor.  Similar to [#11940](https://github.com/flutter/flutter/issues/11940).

**Comment by jasonguiking** [comment]
flutter sdk 1.9.1 have no such question, today I update flutter sdk to 1.12.13 it not worked

**Comment by iapicca** [comment]
Hi @jasonguiking 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide 
your updated `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal reproducible code sample.
Please refrain from posting pictures if not necessary.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
