### ISSUE TITLE
DynamicLibrary.open error:  Invalid argument(s): Failed to load dynamic library (126) 

### ISSUE THREAD

**Issue by fedorovmichael** [flutter/flutter#58079]
Hi, I have the some problem, 
windows 64bit
flutter --version
Flutter 1.19.0-2.0.pre.143 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9d58a87066 (4 days ago) • 2020-05-22 22:37:01 -0700
Engine • revision 9ce1e5c5c7
Tools • Dart 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

flutter doctor
[√] Flutter (Channel master, 1.19.0-2.0.pre.143, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

**I try to run on windows vm very simple code :**
```
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;

typedef hello_world_func = ffi.Void Function();
typedef HelloWorld = void Function();

void main() {
final dylib = 
  ffi.DynamicLibrary.open(Platform.script.resolve("build/windows/x64/Debug/Runner/hello.dll").path);
final HelloWorld hello = dylib.lookup<ffi.NativeFunction<hello_world_func>>('hello_world')
      .asFunction();
  // Call the function
  hello(); 
}

code of dll:
**file: hello.cpp**
#include <stdio.h>
#include "hello.h"

int main()
{
    hello_world();
    return 0;
}
void hello_world()
{
    printf("Hello World\n");
}
```

**file: hello.h**:
void hello_world();

the code of c++ compiled in visual studio community 2019 to hello.dll
in the flutter I put it to:
build/windows/x64/Debug/Runner/hello.dll

when I run it in vs code get error:
````
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)
#0       _open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      main package:hello1/main.dart:19
#3      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:247:25)
#4      _rootRun  (dart:async/zone.dart:1190:13)
#5      _CustomZone.run  (dart:async/zone.dart:1093:19)
#6      _runZoned  (dart:async/zone.dart:1630:10)
#7      runZonedGuarded  (dart:async/zone.dart:1618:12)
#8      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:239:5)
#9      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
#10     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by mkustermann** [comment]
@fedorovmichael

The code in 
```dart
final dylib = ffi.DynamicLibrary.open(
    Platform.script.resolve("build/windows/x64/Debug/Runner/hello.dll").path);
```
uses `Uri.path` which usually yields a path with forward slashes. 

Does it fix your problem if you change it to use `Uri.toFilePath({bool windows})`:
```
final dylib = ffi.DynamicLibrary.open(
    Platform.script.resolve("build/windows/x64/Debug/Runner/hello.dll").toFilePath());
```

?

**Comment by fedorovmichael** [comment]
Hi Martin,
thanks for quick answer it not resolve my problem, get this error:

Launching lib\main.dart on Windows in debug mode...
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (193)
[38;5;244m#0      _open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)[39;49m
[38;5;244m#1      new DynamicLibrary.open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)[39;49m
[38;5;248m#2      main[39;49m
[38;5;244m#3      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:247:25)[39;49m
[38;5;244m#4      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#5      _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#6      _runZoned  (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#7      runZonedGuarded  (dart:async/zone.dart:1618:12)[39;49m
[38;5;244m#8      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:239:5)[39;49m
[38;5;244m#9      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)[39;49m
[38;5;244m#10     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m

Thanks

**Comment by dcharkes** [comment]
Error code 193 is due to mixing and matching 32 bit with 64 bit. Most likely, you installed a 32 bit Dart SDK, and try to load a 64 bit shared library.

**Comment by fedorovmichael** [comment]
Hi Daco,

How I check what version of SDK installed ?

Thanks Michael

**Comment by dcharkes** [comment]
`dart --version`

**Comment by dcharkes** [comment]
(Issue with same error code https://github.com/dart-lang/samples/issues/53.)

**Comment by fedorovmichael** [comment]
Daco,

dart --version

I get result: 

Dart VM version: 2.9.0-10.0.dev.flutter-7706afbcf5 (be) (Tue May 19 12:10:20 2020 +0000) on "windows_x64"

this is 64bit or 32bit ?

thanks

**Comment by dcharkes** [comment]
That is 64 bit (windows_x64). Is your shared library (`hello.dll`) 32 bit?

**Comment by fedorovmichael** [comment]
Daco,

I rebuild my hello.dll, still get the same error: 

Launching lib\main.dart on Windows in debug mode...
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (193)
[38;5;244m#0      _open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)[39;49m
[38;5;244m#1      new DynamicLibrary.open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)[39;49m
[38;5;248m#2      main[39;49m
[38;5;244m#3      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:247:25)[39;49m
[38;5;244m#4      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#5      _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#6      _runZoned  (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#7      runZonedGuarded  (dart:async/zone.dart:1618:12)[39;49m
[38;5;244m#8      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:239:5)[39;49m
[38;5;244m#9      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)[39;49m
[38;5;244m#10     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m

**Comment by dcharkes** [comment]
Is your build building the dll for 32 or 64 bit? (https://www.google.com/search?q=dll+32+or+64+bit)

**Comment by fedorovmichael** [comment]
Daco, 
I try to do new file that return result string but in ffi not exists return type string:  typedef hello_world_func = ffi.Void Function(); 
what type I need to select ?

thanks

**Comment by dcharkes** [comment]
@fedorovmichael please open a new issue for a new question. Did your original problem get solved?

**Comment by fedorovmichael** [comment]
Hi Daco,

the original problem I didn't resolve, I created new dll 64bit:

C# code :
namespace hello_csharp
{
    public class Hello
    {
        public void hello_world()
        {
            Console.WriteLine("hello from c#");
        }
    }
}

flutter code:
import 'package:flutter/material.dart';
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;

typedef hello_world_func = ffi.Void Function();
typedef HelloWorld = void Function();

void main() {
   
  final dylib = ffi.DynamicLibrary.open(Platform.script.resolve("build/windows/x64/Debug/Runner/hello_csharp.dll").toFilePath());

 final HelloWorld hello = dylib
       .lookup<ffi.NativeFunction<hello_world_func>>('hello_world')
       .asFunction();

  // Call the function
  hello(); 
}

I get the error: 

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      main (package:hello1/main.dart:30:9)
#2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:247:25)
#3      _rootRun (dart:async/zone.dart:1190:13)
#4      _CustomZone.run (dart:async/zone.dart:1093:19)
#5      _runZoned (dart:async/zone.dart:1630:10)
#6      runZonedGuarded (dart:async/zone.dart:1618:12)
#7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:239:5)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

thanks

**Comment by dcharkes** [comment]
Well, you did resolve error with loading the library. The loading of the library now succeeds, but looking up the symbol doesn't.

Note that you are using C#, and `dart:ffi` is a C FFI. So you either need to write your file in C, or C++ with `extern "C"`, or use a C# equivalent of C++'s `extern "C"`. (A [quick search](https://www.google.com/search?q=c%23+export+function+as+c) reveals this is possible with C#, but not supported out of the box.)

Closing the issue, as the problems with loading the dynamic library itself are solved.
