### ISSUE TITLE
Deprecate & remove the Mojo based network stack.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#5808]
See discussion in https://github.com/flutter/engine/pull/3008#discussion_r78233924 for details. Boils down to the following points:
* Users have an alternative in the form of `dart:io`.
* Implementing the network service correctly on each platform is difficult to do if the interfaces don't allow us to control how data is read from the underlying socket.
* If we cant control how we read from the socket, we have to buffer data. For large requests, we have to manage OOM conditions or crash.

**Comment by chinmaygarde** [comment]
In chat, @Hixie explained that we may want to remove the current implementation and work with existing users to migrate to Dart IO. We could also provide `dart:io` backed implementations in `package:flutter/http.dart`.

**Comment by brianegan** [comment]
Not sure if you're interested in a user perspective, but I've written a quick fetch method using `dart:io` package, and while it's pretty cool to see the underlying technology as I learn Dart / Flutter (stream transformers, etc), I'm certain in a real app I'd end up writing my own HTTP-client abstraction around the raw `dart:io` functionality. And my guess would be I wouldn't be the only one!

Therefore, perhaps removing the `Mojo` part is a good idea, but I still think there's merit in an `http` client library that is a bit higher-level than raw `dart:io`.

**Comment by abarth** [comment]
> I still think there's merit in an http client library that is a bit higher-level than raw dart:io.

Yes.  The one we've been using is `package:http`.

**Comment by brianegan** [comment]
Perfect. Just wanted to add a tip of the hat for keeping `package:http` alive in a non-Mojo world as I wasn't sure what was meant by "work with existing users to migrate to Dart IO."

**Comment by abarth** [comment]
@chinmaygarde said he was going to drive this.
