### ISSUE TITLE
Able to run project on Web even on master channel

### ISSUE THREAD

**Issue by thecoffeehog** [flutter/flutter#58085]
According to [this doc](https://flutter.dev/docs/get-started/web), Web is supported only on **beta** channels.

**Sequence of operation**

Switched to the beta channel
Added web to config
Switched back to master (My other project started showing issues on the beta)
Ran app on Chrome since it was in the IDE device list (Probably because web was still in config)

### **Shouldn't "web"  be removed from config when the channel is updated? Or is this the right behaviour? Or should I remove web from config?**

**Running on iOS, Chrome and MacOS**

![image](https://user-images.githubusercontent.com/8275355/83003525-10dac780-a02c-11ea-95e5-d9d1033f9872.png)

**Android Studio Device List**

![image](https://user-images.githubusercontent.com/8275355/83002981-4fbc4d80-a02b-11ea-9df7-4177aa765462.png)

**Flutter doctor result follows**

[✓] Flutter (Channel master, 1.19.0-2.0.pre.145, on Mac OS X 10.15.4 19E287,
    locale en-IN)
    • Flutter version 1.19.0-2.0.pre.145 at /Users/uditchugh/Desktop/dev/flutter
    • Framework revision af9b6a6efa (17 hours ago), 2020-05-26 09:17:55 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/uditchugh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) • 002BD24C-24D4-491E-84CC-40FC39753716 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS                      • macOS                                •
      darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                 • web-server                           •
      web-javascript • Flutter Tools
    • Chrome                     • chrome                               •
      web-javascript • Google Chrome 81.0.4044.138

• No issues found!

**Comment by TahaTesser** [comment]
Hi @thecoffeehog 
Beta is supported on all channels except, if you don't want web config, you can delete web folder and whenever you want it back, you can regenerate web folder using `flutter create .`  It is recommend to use `beta` since it's more stable `dev` and `master`

I feel safe to close this issue, if you disagree please write in the comments
and I will reopen it. 
Thank you"
