### ISSUE TITLE
Textfield issue

### ISSUE THREAD

**Issue by EngDjango** [flutter/flutter#58099]
I LOVE flutter ... but I don't know what is going on with these TEXTFIELDs ... they are so misbehaving in every way ... especially with multilanguage input ... and the worst comes with languages that are in different directions ... and because of that I can't and will never publish my flutter apps 😩😭 ;

here is a code example
```
Container(
              padding: EdgeInsets.symmetric(horizontal: 5),
              child: TextField(
                decoration: InputDecoration(
                    labelText: "Title in the 'Search' list",
                    contentPadding: EdgeInsets.symmetric(horizontal: 5),
                    border: OutlineInputBorder()),
                maxLength: 140,
                textAlign: TextAlign.center,
                minLines: 1,
                maxLines: null,
              ),
            )
```
 using this TextField to write in Arabic with English is a nightmare;
plz try to fix it asap;
is there are any hacks for now or any alternatives to TextFields in flutter ?

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/47745
