### ISSUE TITLE
Flutter Web : Issue Regarding intergrating Firebase Database with Flutter web

### ISSUE THREAD

**Issue by mannnish** [flutter/flutter#58095]
so I wanted to make a website and hence I used flutter web, then deployed on firebase using commands like firebase init hosting and then deployed it. After that i ran it and compiled and deployed succesfully. But now i want to use the firebase database in my flutter web and i tried many methods and failed everytime. I created the webApp on firebase console too to get API Keys and AppID.
Some of the methods were -> 
1. copying the CDN snippet code to index.html
2. copying Automatic snippet code to index.html

Please explain the whole procedure instead of pasting snippets.

**Comment by SpajicM** [comment]
Which code snippet?
Firebase Database is not supported on Flutter yet.

**Comment by VladyslavBondarenko** [comment]
@mannnish 
yes, firebase_database doesn't support web yet.
Please see https://stackoverflow.com/questions/59670753/flutter-firebase-realtime-database-in-web.
Closing.
For future consider to file firebase-plugins related issues to the flutterfire repository https://github.com/FirebaseExtended/flutterfire/issues.

**Comment by mannnish** [comment]
> Which code snippet?
> Firebase Database is not supported on Flutter web yet.

i reffered to this documentation
https://firebase.google.com/docs/web/setup

**Comment by SpajicM** [comment]
@mannnish That's for JavaScript web projects, not Flutter web.

Flutter + Flutter stuff are at https://github.com/FirebaseExtended/flutterfire/blob/master/README.md
Realtime Database support for Web isn't there yet.
