### ISSUE TITLE
Rename Viewport "scrollDirection"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#581]
I've always thought of Viewport as a building block for scrollables, an internal implementation detail.
But it's actually useful in its own right, when you want to have something that overflows and is clipped, while still shrink-wrapping where possible.
In that role, though, "scrollDirection" is an odd name for "the direction in which to allow the contents to overflow". So we should probably rename it.

**Comment by abarth** [comment]
`overflowDirection` ?

**Comment by abarth** [comment]
Related to https://github.com/flutter/flutter/issues/151
