### ISSUE TITLE
Please change this !!!

### ISSUE THREAD

**Issue by M001T** [flutter/flutter#58100]
I would like to suggest an idea to improve the usability of the CLI flutter by 90%

Change the Print Widget Key, keep it away from the "R" key please, many developers accidentally click on the "T" key because it is next to each other

Another thing: Iapicca, I know you like to go on everyone's comment to say (Please share your flutter doctor) in that case stay away from my issue please

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/58101
