### ISSUE TITLE
Unexpected background shadow when <elided feature> is displayed

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#58102]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=52630. May not be a Flutter bug, filing so we have a mirror issue just in case we need to help investigate.

**Comment by sanjayc77** [comment]
I believe this is working as intended. Flutter is drawing a shadow for elevated surfaces. The elevation for Ask was 200, which resulted in a shadow that was cast widely around it. When I reduced it to 10, it was much more pleasant.

See https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=52630 which I marked as closed.

**Comment by kf6gpe** [comment]
Sweet! Thanks for closing the loop here, too! Closing.
