### ISSUE TITLE
Please work on windows desktop, 1 billion users cant wait anymore

### ISSUE THREAD

**Issue by fisforfaheem** [flutter/flutter#58107]
Flutter has a great chance at defeating Visual studio, if it can port IOS/Android flutter apps to DESKTOP, but it's more than a year and still nothing good news for it, Please update the support and focus

**Comment by Hixie** [comment]
@fisforfaheem Please see our code of conduct. https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

This kind of bug is not respectful of our development team.
