### ISSUE TITLE
Idea to improve the usability of the CLI flutter by 90%

### ISSUE THREAD

**Issue by M001T** [flutter/flutter#58101]
## Use case

I would like to suggest an idea to improve the usability of the CLI flutter by 90%

Change the Print Widget Key, keep it away from the "R" key please, many developers accidentally click on the "T" key because it is next to each other

## Proposal

Improve usability of the CLI flutter by 90%

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/33184
