### ISSUE TITLE
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7326b9) but could not find and invoke the GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by joshuakoh1** [flutter/flutter#58113]
## Steps to Reproduce

I had an issue for flutter_barcode_reader (https://github.com/mintware-de/flutter_barcode_reader/issues/244) which the dev pointed me to this:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Followed the instructions and replaced 
```
import android.os.Bundle
import io.flutter.plugins.GeneratedPluginRegistrant
import android.view.WindowManager.LayoutParams
import io.flutter.app.FlutterFragmentActivity
class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
    getWindow().addFlags(LayoutParams.FLAG_SECURE)
  }
}
```
with
```
import android.view.WindowManager.LayoutParams
import io.flutter.embedding.android.FlutterActivity
class MainActivity: FlutterActivity() {
}
```
Everything broke

## Logs

```
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7326b9) but could not find and invoke the GeneratedPluginRegistrant
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestService on channel lyokone/location)
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel plugins.flutter.io/firebase_messaging)
```

```
[√] Flutter (Channel stable, v1.17.1)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Platform android-29, build-tools 29.0.0
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
   android-arm64 • Android 10 (API 29)
```

**Comment by VladyslavBondarenko** [comment]
@joshuakoh1 
have you followed all the instructions in migrating doc?
does `flutter clean` help?
I can run [the default code sample](https://pub.dev/packages/barcode_scan#-example-tab-) in a new project with `dev 1.19.0-1.0.pre` on Android 9 (API 28)

**Comment by joshuakoh1** [comment]
Only the MainActivity edit was applicable to my app so that is the only change I made. 

Also, barcode scan was not the offending plugin after the change but I also never got to the stage where I managed to test the barcode scan as the other plugins started throwing no implementation errors on the same versions.

I've tried flutter clean, pub get, pub upgrade, flutter doctor. None of them throw errors.

**Comment by VladyslavBondarenko** [comment]
@joshuakoh1 could you try to use the plugin in a new project and if it works investigate what can be the difference with your current project?

**Comment by joshuakoh1** [comment]
Unfortunately I am not experienced enough to investigate the differences between my existing project and a new project. If you could point me to what exactly I should be comparing it would be appreciated.

**Comment by TurkiWalid** [comment]
I'm experiencing the same issue with Flutter 1.17.2, After adding some **platform channel method** the other installed plugins are no longer seen as implemented and i'm getting this message when running app. 

`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d07237a) but could not find and invoke the GeneratedPluginRegistrant.`

Also i'm getting this message as it is the first plugin call in the app.

`Unhandled Exception: MissingPluginException(No implementation found for method getNotificationAppLaunchDetails on channel dexterous.com/flutter/local_notifications)`

Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):

> - [√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.836], locale en-GB)
> - [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> - [√] Android Studio (version 3.6)
> - [√] IntelliJ IDEA Community Edition (version 2018.2)
> - [√] VS Code (version 1.45.1)
> - [√] VS Code, 64-bit edition (version 1.30.2)
> - [√] Connected device (1 available)

This is some code of my platform channel call.
```
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        //....
        MethodChannel mc = new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL);
        mc.setMethodCallHandler((call, result) -> {
            if (call.method.equals("someMethod")) {
                _result = result;
             //...
            }
        });
    }
```

**Comment by TurkiWalid** [comment]
> 
> 
> I'm experiencing the same issue with Flutter 1.17.2, After adding some **platform channel method** the other installed plugins are no longer seen as implemented and i'm getting this message when running app.
> 
> `Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d07237a) but could not find and invoke the GeneratedPluginRegistrant.`
> 
> Also i'm getting this message as it is the first plugin call in the app.
> 
> `Unhandled Exception: MissingPluginException(No implementation found for method getNotificationAppLaunchDetails on channel dexterous.com/flutter/local_notifications)`
> 
> Flutter doctor output
> Doctor summary (to see all details, run flutter doctor -v):
> 
> > * [√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.836], locale en-GB)
> > * [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> > * [√] Android Studio (version 3.6)
> > * [√] IntelliJ IDEA Community Edition (version 2018.2)
> > * [√] VS Code (version 1.45.1)
> > * [√] VS Code, 64-bit edition (version 1.30.2)
> > * [√] Connected device (1 available)
> 
> This is some code of my platform channel call.
> 
> ```
>     @Override
>     public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>         super.configureFlutterEngine(flutterEngine);
>         //....
>         MethodChannel mc = new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL);
>         mc.setMethodCallHandler((call, result) -> {
>             if (call.method.equals("someMethod")) {
>                 _result = result;
>              //...
>             }
>         });
>     }
> ```

Quick edit: I was able to fix this after adding 
```
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
```
and replacing the MainActivity as the docs [https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](url)

**Comment by VladyslavBondarenko** [comment]
@joshuakoh1 is your case the same?

**Comment by sanjeevsejwal** [comment]
I am Also Getting the same error but only in release version debug version is working perfectly no issues but in release version app get stuck at splash screen.

**Comment by jmagman** [comment]
\cc @xster is this a documentation issue?

**Comment by fhmarino** [comment]
Hi Guys!

I'm integrating my flutter application with a native library, to make its work I've used the MainActivity.kt overridden the method configureFlutterEngine, in this method, I configured a MethodChannel and EventChannel and both are working, but all other plugins that I use are not working anymore. I saw in my log this message when I initialize my app:

**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@66e8717) but could not find and invoke the GeneratedPluginRegistrant.**

And when I tried to call a functioning plugin, I've gotten **"MissingPluginException(No implementation found for method ..."** exception.

I've already configured my AndroidManifest and followed the https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects steps, but it's still doesn't working...

That's my MainActivity.kt


class MainActivity: FlutterActivity() {
    /**
     * List that contains bitmaps of biometric capture. It's the result that will be send in
     * the channel event
     * */
    private var fingerprintsInBytes: List<ByteArray> = ArrayList()

    /**
     * Channel used to call method to start biometric capture
     * */
    private val channel = "br.com.cpqd.govid_app/biometric_capture"

    /**
     * Object that starts the process of biometric capture, that's the class implemented by Griaule
     * */
    private val api = BCCFingerPhotoAPI()

    /**
     * Channel used to integrate the flutter application within this plugin
     * */
    private val BIOMETRIC_EVENT_CHANNEL = "br.com.cpqd.govid_app/biometric"

    /**
     * Action used when the biometric capture process gets completed
     * */
    private val ACTION_RESULT_COMPLETE = "br.com.cpqd.govid_app.actions/fingerprints-collected"

    /**
     * Method called when this Activity is created, it replaces the onCreated method
     * All the channels methods and events must be called here.
     *
     * @param flutterEngine context and configuration of current flutter application
     * */
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        EventChannel(flutterEngine.dartExecutor, BIOMETRIC_EVENT_CHANNEL).setStreamHandler(
                object : EventChannel.StreamHandler {
                    private var createBiometricCollectionReceiver: BroadcastReceiver? = null
                    override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {
                        createBiometricCollectionReceiver = events?.let { createBiometricCollectionReceiver(it) }

                        registerReceiver(createBiometricCollectionReceiver, IntentFilter(ACTION_RESULT_COMPLETE))
                    }

                    override fun onCancel(arguments: Any?) {
                        unregisterReceiver(createBiometricCollectionReceiver)
                        createBiometricCollectionReceiver = null
                    }
                }
        )

        val nativeMethod = MethodChannel(flutterEngine.dartExecutor, channel)
        nativeMethod.setMethodCallHandler { call, result ->

            println(call.method)
            when (call.method) {
                "startActivity" -> {
                    val config: MutableMap<String, Boolean> = ArrayMap()
                    config["left_hand"] = true
                    config["right_hand"] = true
                    config["show_tutorial"] = true
                    api.initializeCapture(this, this, 1, config)

                    result.success(true)
                }
            }
        }
    }

    /**
     * Method responsible to create the BroadCast receiver that will observer when an Intent with action
     * ACTION_RESULT_COMPLETE was received
     *
     * @param events object that contains methods to trigger events to flutter application using the
     * registered channel
     * */
    private fun createBiometricCollectionReceiver(events: EventChannel.EventSink): BroadcastReceiver? {
        return object : BroadcastReceiver() {
            override fun onReceive(context: Context?, intent: Intent) {
                if (intent.action == ACTION_RESULT_COMPLETE) {

                    val biometricResult = intent.getBooleanExtra("success", false)

                    when (biometricResult) {
                        true -> {
                            try {
                                if (fingerprintsInBytes.isNotEmpty()) {
                                    events.success(fingerprintsInBytes)
                                } else {
                                    throw Exception("")
                                }

                            } catch (e: java.lang.Exception) {
                                e.message?.let {
                                    Log.d("Error", it)
                                    events.error(it, null, null)
                                }
                            }
                        }
                        false -> {
                            Log.d("BROADCAST", "ERROR")
                            events.error("error during biometrics collection",
                                    null, null)
                        }
                    }
                }
            }
        }
    }


    /**
     * Method responsible to convert a list of Bitmap into a list of ByteArray.
     * It's necessary once a list of Bitmap isn't serializable, and therefore it's not possible to
     * send it as an event.
     *
     * @param fingerprints a list of Bitmap that contains the collection of biometric digital that was
     * collected during the process of method channel
     * */
    private fun convertBitmapToByteArray(fingerprints: List<Bitmap>) {
        fingerprints.forEach{
            val bmpStream = ByteArrayOutputStream()
            try {
                /* Serializing to a byte array */
                it.compress(Bitmap.CompressFormat.PNG, 100, bmpStream)

                /* Adding a fingerprint as compressed Bitmap */
                fingerprintsInBytes += bmpStream.toByteArray()

            } catch (e: java.lang.Exception) {
                throw e
            }
        }
    }

    /**
     * Method that is called when the process of Biometric capture is finished.
     *
     * It's responsible to prepare the result to be sent to Flutter application and trigger the
     * event of ACTION_RESULT_COMPLETE as well.
     *
     * @param requestCode code used during the request in the early of process
     * @param resultCode code that contains the result of the process, it's expected RESULT_OK
     * @param data the parameter that contains the Bitmaps of captured biometrics
     * */
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {
        super.onActivityResult(requestCode, resultCode, data)
        val intentResult = Intent(ACTION_RESULT_COMPLETE)
        var success = false
        if (requestCode == 1) {
            if (resultCode == RESULT_OK ) { //&& data.data != null) {
                try {
                    val fingerprints = ImageHelper.getFingerprints(
                            data.getIntExtra("left_fingers_num", 4),
                            data.getIntExtra("right_fingers_num", 4), context)

                    /* Converting the array of Bitmap in a serializable format to be passed as
                     * parameter into the events success method */
                    convertBitmapToByteArray(fingerprints)

                    success = true

                } catch (e: Exception) {
                    e.message?.let { Log.d("Exception", it) }

                }
            }

            intentResult.putExtra("success", success)
            sendBroadcast(intentResult)
        }
    }
}

flutter doctor

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

**Comment by VladyslavBondarenko** [comment]
@fhmarino 
consider to file a separate issue for this

**Comment by thongvo109** [comment]
I same issue

**Comment by thongvo109** [comment]
But the case use shared_preferences.

**Comment by sanekyy** [comment]
same issue with shared_preferences

**Comment by DustinJSilk** [comment]
I cannot seem to figure out this same error. It only shows up when building a release version for Android. This is my error:

```
W/FlutterActivity( 4109): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.a@680466b) but could not find and invoke the GeneratedPluginRegistrant.
E/flutter ( 4109): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

I've tried Flutter version 17 and the beta 19, neither work.

This is my Application.kt

```kotlin

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin

class Application : FlutterApplication(), PluginRegistrantCallback {

  override fun onCreate() {
    super.onCreate()
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  override fun registerWith(registry: PluginRegistry) {
    FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
    SharedPreferencesPlugin
            .registerWith(registry?.registrarFor(
        "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
  }
}

```

My MainActivity.kt is an empty class.
Anyone solved it?

**Comment by thongvo109** [comment]
To solve this problem I tried the way: 
Application.kt 
`import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}`
--------------
 edit  in gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

edit in build.gradle 
 `buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2' //-----> edit here 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
Did worked for me

**Comment by zhaiyunbin** [comment]
> 我似乎无法弄清楚这个错误。它仅在构建Android发行版时显示。这是我的错误：
> 
> ```
> W/FlutterActivity( 4109): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.a@680466b) but could not find and invoke the GeneratedPluginRegistrant.
> E/flutter ( 4109): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> ```
> 
> 我已经尝试了Flutter 17版和Beta 19版，但都没有用。
> 
> 这是我的Application.kt
> 
> ```kotlin
> 导入 io.flutter.app.FlutterApplication 
> 导入 io.flutter.plugin.common.PluginRegistry 
> 导入 io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback 
> 导入 io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService 
> 导入 io.flutter.plugins.sharedpreferencesShare
> 
> 类 应用程序 ： FlutterApplication（），PluginRegistrantCallback {
> 
>   重写 fun  onCreate（）{
>      super .onCreate（）
>      FlutterFirebaseMessagingService .setPluginRegistrant（this）;
>   }
> 
>   重写 fun  registerWith（注册表： PluginRegistry）{
>      FirebaseCloudMessagingPluginRegistrant .registerWith（registry）
>      SharedPreferencesPlugin
>             .registerWith（registry？.registrarFor（
>         “ io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin ”））；
>   }
> }
> ```
> 
> 我的MainActivity.kt是一个空类。
> 有人解决了吗？
clear cache, its resolve,  FlutterSDk dir cache.. rebuild project maybe resolve

**Comment by VladyslavBondarenko** [comment]
@DustinJSilk , @zhaiyunbin consider to file a separate issue to this, may be related to https://github.com/flutter/flutter/issues/54845 and be similar with https://github.com/flutter/flutter/issues/61226

**Comment by xBioDreadx** [comment]
same issue: W/FlutterActivity( 8459): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@bcc7596) but could not find and invoke the GeneratedPluginRegistrant
Im on latest stable flutter channel currently.

**Comment by otopba** [comment]
Same issue

**Comment by Trojan9** [comment]
same issue

**Comment by FarmaanElahi** [comment]
I was having the same issue because I forgot to add this piece of code in the FlutterActivity
```
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
``

**Comment by fikrirazzaq** [comment]
Change  `import io.flutter.app.FlutterActivity` to  `import io.flutter.embedding.android.FlutterActivity` works for me.

Full `MainActivity.kt`
```dart
import android.os.Bundle
import android.os.PersistableBundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
        GeneratedPluginRegistrant.registerWith(FlutterEngine(this))
    }
}

```

**Comment by xaospayne** [comment]
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />


WORKED FOR ME TOO !!!! :D

**Comment by xaospayne** [comment]
> I was having the same issue because I forgot to add this piece of code in the manifest for `MainActivity`
> 
> ```
> <meta-data
>     android:name="flutterEmbedding"
>     android:value="2" />
> ```

WORKED FOR ME TOOOO !!!! :D

**Comment by gysipos** [comment]
I have this issue s well after upgrading my project because it was advised so, since it's created before Flutter 1.2

**Comment by SalimliOrxan** [comment]
I had resolved this error by changing :
from    classpath 'com.android.tools.build:gradle:4.0.1'
to        classpath 'com.android.tools.build:gradle:3.5.0'

**Comment by vabym8** [comment]
W/FlutterActivity(24853): `Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@b0a6050) but could not find and invoke the GeneratedPluginRegistrant.`
Waiting for Android SDK built for x86 to report its views...
Debug service listening on ws://127.0.0.1:57203/cp0vM14IeQA=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(24853): eglMakeCurrent: 0xe6454100: ver 3 0 (tinfo 0xc6cc3450)
D/eglCodecCommon(24853): setVertexArrayObject: set vao to 0 (0) 1 0
I/Choreographer(24853): Skipped 70 frames!  The application may be doing too much work on its main thread.
D/FA      (24853): Connected to remote service
V/FA      (24853): Processing queued up service tasks: 4
D/EGL_emulation(24853): eglMakeCurrent: 0xf182a040: ver 3 0 (tinfo 0xde40fd00)
D/eglCodecCommon(24853): setVertexArrayObject: set vao to 0 (0) 1 0
E/flutter (24853): [**ERROR**:`flutter/lib/ui/ui_dart_state.cc(171)`] Unhandled Exception: `MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
E/flutter (24853): 
V/FA      (24853): Inactivity, disconnecting from the service
Application finished.

**Comment by richard457** [comment]
Any feedback on this, all proposed solutions such as flutter clean does not work, and to confirm this happen on all flutter channel even on the stable channel, it seems like flutter has mixed up something.

**Comment by appsailor** [comment]
I'm facing same issue as many reported especially with SharedPreference involved. I've wasted countless hours migrating and cleaning and whatnot. 
When I put this like in my main.dart, the android emulator works okay. But not sure if thats the right approach using a testing related method in the main.

    SharedPreferences.setMockInitialValues({});

P.S: Feels trying out the upcoming Jetpack Compose (and stable Swift UI for iOS) for one of my projects.

**Comment by matthewlloyd** [comment]
I'm running in to this issue also. It's very confusing that "could not find and invoke the GeneratedPluginRegistrant" is the only error message produced if any of the plugins throw an exception during initialization, and it would be much more user-friendly if the message was split into separate "could not find" and "failed to invoke" errors and the underlying exception itself was also reported.

**Comment by thongvo109** [comment]
I think to solve this problem. Everyone should update the new android studio version and create project with android new version.  It worked for me. Hope feedback of everyone. Thank you 

> ```kotlin
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
> 
>   override fun onCreate() {
>     super.onCreate()
>     FlutterFirebaseMessagingService.setPluginRegistrant(this);
>   }
> 
>   override fun registerWith(registry: PluginRegistry) {
>     FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
>     SharedPreferencesPlugin
>             .registerWith(registry?.registrarFor(
>         "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
>   }
> }
> ```

**Comment by christopher-natan** [comment]
Just sharing the experience and solution. It took me a day trying different approaches fixing the issue(s) but all failed. I ended up creating a new Flutter project using a stable channel and copy/paste my old app files to the new one. And now the app is working as well.

**Comment by thongvo109** [comment]
> Just sharing the experience and solution. It took me a day trying different approaches fixing the issue(s) but all failed. I ended up creating a new Flutter project using a stable channel and copy/paste my old app files to the new one. And now the app is working as well.


Confirmed.

**Comment by trezm** [comment]
Ditto, had to completely regenerate the project and copy files over. Would be great to have a more simple fix.

**Comment by JoorgeFerrari** [comment]
I regenerate the project using stable channel, and still can't get the app to run

**Comment by AlexandrGurenko** [comment]
If I run the application using `flutter run --release` - everything works fine
 but when using `flutter build apk --release` - and launch the application, then I get the message:
`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.a@73dda10) but could not find and invoke the GeneratedPluginRegistrant.` 
and 
`Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

What am I doing wrong?

**Comment by thongvo109** [comment]
> I regenerate the project using stable channel, and still can't get the app to run
You using Android studio version ?

**Comment by thongvo109** [comment]
> Ditto, had to completely regenerate the project and copy files over. Would be great to have a more simple fix.

You using Android Studio version ?

**Comment by thongvo109** [comment]
> If I run the application using `flutter run --release` - everything works fine
> but when using `flutter build apk --release` - and launch the application, then I get the message:
> `Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.a@73dda10) but could not find and invoke the GeneratedPluginRegistrant.`
> and
> `Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
> 
> What am I doing wrong?
> 
> flutter doctor -v
> 
> [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale ru)
> • Flutter version 1.20.4 at /Users/*******/Desktop/Projects/Frameworks/flutter
> • Framework revision [fba99f6](https://github.com/flutter/flutter/commit/fba99f6cf9a14512e461e3122c8ddfaa25394e89) (11 days ago), 2020-09-14 15:32:52 -0700
> • Engine revision d1bc06f032
> • Dart version 2.9.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
> • Android SDK at /Users/*******/Library/Android/sdk
> • Platform android-30, build-tools 30.0.1
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 12.0.1, Build version 12A7300
> • CocoaPods version 1.9.3
> 
> [✓] Android Studio (version 4.0)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 49.0.2
> • Dart plugin version 193.7547
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] Connected device (1 available)
> • LG H870DS (mobile) • LGH870DSc0364773 • android-arm64 • Android 8.0.0 (API 26)
> 
> • No issues found!

You can check version build.gradle of Android SDK, update version new and run again. I think it work. I did try.

**Comment by briankariuki** [comment]
Had same issue, running `flutter clean` worked for me

**Comment by jamesncl** [comment]
Same issue, but I only get it when running on emulator / AVD. On a real device, no error. I already have this in my manifest:

```
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```
I've `flutter clean`ed several times. Only affects android. Using flutter stable channel v1.20.4
