### ISSUE TITLE
Flutter FutureBuilder return null

### ISSUE THREAD

**Issue by marpacioglu** [flutter/flutter#58127]
when listing the data in my local database with FutureBuilder snapshot return null. I don't listing my data. when I check connection status it is waiting. when debugprint dbHelper.randevuListesiGetir() method, my data listing console screnn but not listening futurebuilder.

```
class _RandevularState extends State<Randevular> {
  DatabaseHelper dbHelper;
  List<Randevu> tumRandevular;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

      dbHelper=DatabaseHelper();
     tumRandevular=List<Randevu>();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future:dbHelper.randevuListesiGetir() ,
      builder: (context,AsyncSnapshot<List<Randevu>> snapshot){
        if(snapshot.connectionState==ConnectionState.done){
          tumRandevular=snapshot.data;
          print("data"+snapshot.data.toString());
        }else if(snapshot.connectionState==ConnectionState.waiting){
          print("waiting");
        }else{
          print("error");
        }

      },
    );
  }

}

```
![Ekran Alıntısı](https://user-images.githubusercontent.com/62361633/83076572-7a83c180-a07e-11ea-846b-c6f1d2e26b0f.JPG)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
