### ISSUE TITLE
How can enable maximize button on video from fb on android? Any idea how to resolve this?

### ISSUE THREAD

**Issue by sandrhymend** [flutter/flutter#58125]
I am looking for a solution how to resolve the issue for embedding fb live stream videos. Any idea how to resolve this?

My environment 
sdk: ">=2.5.0 <3.0.0"

Android 9.0 pie
webview_flutter 0.3.22+1

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
