### ISSUE TITLE
The set up guide defaults to the alpha channel, which is far behind the master

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#5812]
[The set up guide](https://flutter.io/setup/) defaults to the alpha channel, which is quite behind the master. As a result, developers might not get the latest patches.

**Comment by abarth** [comment]
@eseidelGoogle was talking about removing the alpha channel and just having folks use master.

**Comment by eseidelGoogle** [comment]
I made a proposal on our internal list, and saw no objections and at least one support.  @qchong can you take this on?  Once the docs are moved to master, we'll just announce and delete alpha.

**Comment by devoncarew** [comment]
Once `alpha` goes away, we should hide or remove the `channel` command. When we added it we had master, alpha, and codelab channels. With just one channel, we don't need the command exposed (/cc @danrubel).

**Comment by abarth** [comment]
The docs now point to `master` rather than `alpha`.
