### ISSUE TITLE
Flutter SDK Path

### ISSUE THREAD

**Issue by chris-morriss** [flutter/flutter#58129]
Hello - I'm using latest version of **Android Studio version 3.6.3** and **macOS Catalina 10.15.5**. 
I can't run Flutter app anymore, as it keeps giving an error! It states "Define location with flutter.sdk in the local.properties file." The errors are shown in the build.gradle file. This is the current path --> flutter.sdk=/Users/mrcmorriss/Desktop/App/flutter

## Steps to Reproduce

1. ..."Flutter SDK not found. Define location with flutter.sdk in the local.properties file."
2. ...**This is the error that I get when I try to run app - running :**

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mrcmorriss/Desktop/App/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 577

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Must provide Flutter source directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. These commands don't work in Terminal.

3. ...

## Logs

```
```

 /Users/mrcmorriss/Desktop/App/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/mrcmorriss/Desktop/App/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mrcmorriss/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mrcmorriss/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Pixel 3 • 8B5X13VEL • android-arm64 • Android 10 (API 29)

• No issues found!

```
```

**Comment by TahaTesser** [comment]
Hi @chris-morriss 
Go to flutter app > android >  local.properties

Proper update this file your correct Flutter SDK location, this can happened if you've moved your Fluter SDK

sdk_dir for Android SDK path
flutter_sdk for Flutter SDK path

```
sdk.dir=/Users/tahatesser/Code/sdk
flutter.sdk=/Users/tahatesser/Code/flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```

Thank you

**Comment by VladyslavBondarenko** [comment]
@chris-morriss 
I hope you've solved the issue, closing
