### ISSUE TITLE
[web]: `uses-material-design: false` leads to error message

### ISSUE THREAD

**Issue by juanitogan** [flutter/flutter#58132]
Channel beta, 1.18.0-11.1.pre

Running a web app built with:

```yaml
flutter:
  uses-material-design: false
```

Leads to this message in the Firefox console because, well, the font is not included in the build (and correctly not included):

```
Error while trying to load font family "MaterialIcons":
NetworkError: A network error occurred.  main.dart.js:12620:32
downloadable font: download failed
 (font-family: "MaterialIcons" style:normal weight:normal stretch:normal src index:0):
 bad URI or cross-site access not allowed source:
 file:///D:/AndroidStudioProjects/example/build/web/assets/fonts/MaterialIcons-Regular.ttf
```

Thus, something is trying to download a font that isn't needed.

Guessing this may be it:

`FontManifest.json` is generated regardless with this content:

```json
[{"family":"MaterialIcons","fonts":[{"asset":"fonts/MaterialIcons-Regular.ttf"}]}]
```

Delete the JSON file and the app fails to start.

**Workaround:** Reduce the JSON contents to `[]` and the app runs fine without any error messages.

**Comment by jonahwilliams** [comment]
I can't reproduce this on latest master or on 1.18.0-11.1.pre.

@juanitogan can you share a minimal example project that demonstrates the issue when it is either run or built?

**Comment by juanitogan** [comment]
I built the Pogo package example app found here:

https://github.com/juanitogan/pogo/tree/master/example

To make the app visible on a web build, comment out main.dart lines 7 and 8:

```dart
  await Screen.setFullScreen();
  await Screen.setPortrait();
```

They call some SystemChrome methods which seem to kill visibility of web apps.

You can also change the `pogo:` dependency from `path: ../pogo` to `^0.1.2` if you don't want to grab the who repo and instead just copy main.dart, pubspec.yaml, and the assets folder.
