### ISSUE TITLE
isolate service example crashes

### ISSUE THREAD

**Issue by eukreign** [flutter/flutter#5814]
When running the `services/isolate.dart` sample app on a Nexus 5X and clicking *Start* button it immediately crashes with the following output:

```
~/projects/flutter/examples/layers$ flutter run -t services/isolate.dart 
Running 'pub get' in layers...                       6.2s
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.7MB).
Running services/isolate.dart on Nexus 5X...
--------- beginning of main
Observatory listening on http://127.0.0.1:8102
Diagnostic server listening on http://127.0.0.1:8103
Application running.
Connected to view '_flutterView/0xf48196c0'.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
E/DartVM  : ../../dart/runtime/vm/object.h: 5455: error: Handle check failed: saw UnhandledException expected Instance
E/DartVM  : Dumping native stack trace for thread 3010
E/DartVM  :   [0xdae75f5d] Unknown symbol
E/DartVM  : -- End of DumpStackTrace
--------- beginning of crash
W/ActivityManager:   Force finishing activity io.flutter.examples.Layers/org.domokit.sky.shell.SkyActivity
W/ActivityManager:   Force finishing activity io.flutter.examples.Layers/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Duplicate finish request for ActivityRecord{7d0b96c u0 io.flutter.examples.Layers/org.domokit.sky.shell.SkyActivity t59 f}
Application finished.
```

Just in case, here is my `flutter doctor` output:

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/lex/projects/flutter
    • Framework revision b298bdc8c4 (26 hours ago), 2016-09-09 16:55:55
    • Engine revision a55fa1efb9
    • Tools Dart version 1.20.0-dev.1.0

[✓] Android toolchain - develop for Android devices (Android SDK 19.1.0)
    • Android SDK at /home/lex/projects/Android/Sdk
    • Platform android-19, build-tools 19.1.0
    • OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37

[✓] Connected devices
    • Nexus 5X • 00dd4847616ed5cd • android-arm
```

**Comment by eseidelGoogle** [comment]
@johnmccutchan @jason-simmons 

I don't think our current tests cover isolates.  Dart has a ton of VM tests which do cover isolates and we could wire up: https://github.com/dart-lang/sdk/tree/master/tests but don't yet.

**Comment by jason-simmons** [comment]
Confirmed.  Looks like this is still happening if I roll forward to the tip-of-tree Dart VM.

It's sensitive to the type of argument being passed to Isolate.spawn().  If I change the code to call Isolate.spawn(_calculate, null) instead of Isolate.spawn(_calculate, message), then it works.

**Comment by jason-simmons** [comment]
Native stack trace for the assert:
    dart::DynamicAssertionHelper::Fail(char const*, ...)
    dart::Instance::CheckedHandle(dart::Zone*, dart::RawObject*)
    DRT_HelperTypeCheck
    dart::DRT_TypeCheck(dart::NativeArguments)
    unknown

Message from the UnhandledException:
    Invalid argument(s): Invalid object found in message.
    null expected Instance
    Dumping native stack trace for thread a84
        [0xa3f42515] Unknown symbol
    -- End of DumpStackTrace

**Comment by rmacnak-google** [comment]
https://github.com/flutter/engine/commit/cd333e66ebf304b9b0ac7d0a4bae2ea16c4766fa

**Comment by a-siva** [comment]
Can this issue be closed with the fix that Ryan and Jason worked on?

**Comment by a-siva** [comment]
Ignore the comment.
