### ISSUE TITLE
i cant run my flutter application

### ISSUE THREAD

**Issue by zinwar1** [flutter/flutter#58147]
I wrote these lines of codes and there is no eror in visual studio and dartpad.dev/flutter but in both of them i can not debug it, i don't know why. Can someone help me please... here is the code

import 'package:flutter/material.dart'; 
import 'package:flutter/cupertino.dart';

void main(List<String> args) {   MaterialApp(
    title: 'zinwar',
    home:MyApp() ,   ); }

class MyApp extends StatefulWidget{   
@override   State<StatefulWidget> createState() {
    return MyAppState() ;   }

}

class MyAppState extends State<MyApp> {   
@override   Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.blue,
        actions: <Widget>[],
        leading: IconButton(
           onPressed: () {  },
          icon: Icon(Icons.arrow_back), 

      ),

      ),
      body: Center(
        child: Text('HELLO I AM ZINWARM NICE TO MEET YOU'),
      ),
    );   }

**Comment by SirusCodes** [comment]
You have to run app from main.
You can start from this....

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment]
Hi @zinwar1 

You're missing `runApp()`

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'zinwar',
      home: MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  @override
  State createState() {
    return MyAppState();
  }
}

class MyAppState extends State {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.blue,
        actions: [],
        leading: IconButton(
          onPressed: () {},
          icon: Icon(Icons.arrow_back),
        ),
      ),
      body: Center(
        child: Text('HELLO I AM ZINWARM NICE TO MEET YOU'),
      ),
    );
  }
}

``` 

</details> 


if you disagree please write in the comments
and I will reopen it. 
Thank you"
