### ISSUE TITLE
"Write your first Flutter app, part 1" codelab error

### ISSUE THREAD

**Issue by faridghar** [flutter/flutter#58143]
In step 4 of the "Write your first Flutter app, part 1" [codelab](https://flutter.dev/docs/get-started/codelab), there is an instruction to click "Packages get" in order to instal dependencies. This command has been renamed to "Pub get" and so this documentation should be updated to reflect this and avoid confusion (which I experienced).

**Comment by PushkaraSharma** [comment]
Hey, Faridghar, I'm working on this issue, and soon it will be fixed. Thank you.

**Comment by maheshmnj** [comment]
pull request has been merged should be fixed now https://github.com/flutter/website/pull/4189

**Comment by iassal** [comment]
@VladyslavBondarenko seems like this was fixed, good to close

**Comment by faridghar** [comment]
Look good, thanks.
