### ISSUE TITLE
ARM emulator keeps on crashing

### ISSUE THREAD

**Issue by per19** [flutter/flutter#5815]
## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/nb/flutter
    • Framework revision 9a0a0d9903 (4 weeks ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /home/nb/Android/Sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
## flutter run -v

  6 ms • /home/nb/Android/Sdk/platform-tools/adb devices -l
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb devices -l
  14 ms • List of devices attached
          emulator-5554          device product:sdk_phone_armv7 model:sdk_phone_armv7 device:generic
 523 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
   5 ms • Running build command.
   0 ms • APK up to date; skipping build step.
   2 ms • Stopping app 'app.apk' on sdk phone armv7.
   9 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.yourcompany.myfluttapp
   0 ms • Running install command.
   3 ms • /home/nb/Android/Sdk/platform-tools/adb version
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb version
   1 ms • Android Debug Bridge version 1.0.36
          Revision 8f855a3d9b35-android
   3 ms • /home/nb/Android/Sdk/platform-tools/adb start-server
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb start-server
37553 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 install -r build/app.apk
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 install -r build/app.apk
  36 ms • [  0%] /data/local/tmp/app.apk
          [  1%] /data/local/tmp/app.apk
          [  2%] /data/local/tmp/app.apk
          [  2%] /data/local/tmp/app.apk
          [  3%] /data/local/tmp/app.apk
          [  4%] /data/local/tmp/app.apk
          [  5%] /data/local/tmp/app.apk
          [  5%] /data/local/tmp/app.apk
          [  6%] /data/local/tmp/app.apk
          [  7%] /data/local/tmp/app.apk
          [  7%] /data/local/tmp/app.apk
          [  8%] /data/local/tmp/app.apk
          [  9%] /data/local/tmp/app.apk
          [ 10%] /data/local/tmp/app.apk
          [ 10%] /data/local/tmp/app.apk
          [ 11%] /data/local/tmp/app.apk
          [ 12%] /data/local/tmp/app.apk
          [ 12%] /data/local/tmp/app.apk
          [ 13%] /data/local/tmp/app.apk
          [ 14%] /data/local/tmp/app.apk
          [ 15%] /data/local/tmp/app.apk
          [ 15%] /data/local/tmp/app.apk
          [ 16%] /data/local/tmp/app.apk
          [ 17%] /data/local/tmp/app.apk
          [ 18%] /data/local/tmp/app.apk
          [ 18%] /data/local/tmp/app.apk
          [ 19%] /data/local/tmp/app.apk
          [ 20%] /data/local/tmp/app.apk
          [ 20%] /data/local/tmp/app.apk
          [ 21%] /data/local/tmp/app.apk
          [ 22%] /data/local/tmp/app.apk
          [ 23%] /data/local/tmp/app.apk
          [ 23%] /data/local/tmp/app.apk
          [ 24%] /data/local/tmp/app.apk
          [ 25%] /data/local/tmp/app.apk
          [ 25%] /data/local/tmp/app.apk
          [ 26%] /data/local/tmp/app.apk
          [ 27%] /data/local/tmp/app.apk
          [ 28%] /data/local/tmp/app.apk
          [ 28%] /data/local/tmp/app.apk
          [ 29%] /data/local/tmp/app.apk
          [ 30%] /data/local/tmp/app.apk
          [ 30%] /data/local/tmp/app.apk
          [ 31%] /data/local/tmp/app.apk
          [ 32%] /data/local/tmp/app.apk
          [ 33%] /data/local/tmp/app.apk
          [ 33%] /data/local/tmp/app.apk
          [ 34%] /data/local/tmp/app.apk
          [ 35%] /data/local/tmp/app.apk
          [ 36%] /data/local/tmp/app.apk
          [ 36%] /data/local/tmp/app.apk
          [ 37%] /data/local/tmp/app.apk
          [ 38%] /data/local/tmp/app.apk
          [ 38%] /data/local/tmp/app.apk
          [ 39%] /data/local/tmp/app.apk
          [ 40%] /data/local/tmp/app.apk
          [ 41%] /data/local/tmp/app.apk
          [ 41%] /data/local/tmp/app.apk
          [ 42%] /data/local/tmp/app.apk
          [ 43%] /data/local/tmp/app.apk
          [ 43%] /data/local/tmp/app.apk
          [ 44%] /data/local/tmp/app.apk
          [ 45%] /data/local/tmp/app.apk
          [ 46%] /data/local/tmp/app.apk
          [ 46%] /data/local/tmp/app.apk
          [ 47%] /data/local/tmp/app.apk
          [ 48%] /data/local/tmp/app.apk
          [ 48%] /data/local/tmp/app.apk
          [ 49%] /data/local/tmp/app.apk
          [ 50%] /data/local/tmp/app.apk
          [ 51%] /data/local/tmp/app.apk
          [ 51%] /data/local/tmp/app.apk
          [ 52%] /data/local/tmp/app.apk
          [ 53%] /data/local/tmp/app.apk
          [ 54%] /data/local/tmp/app.apk
          [ 54%] /data/local/tmp/app.apk
          [ 55%] /data/local/tmp/app.apk
          [ 56%] /data/local/tmp/app.apk
          [ 56%] /data/local/tmp/app.apk
          [ 57%] /data/local/tmp/app.apk
          [ 58%] /data/local/tmp/app.apk
          [ 59%] /data/local/tmp/app.apk
          [ 59%] /data/local/tmp/app.apk
          [ 60%] /data/local/tmp/app.apk
          [ 61%] /data/local/tmp/app.apk
          [ 61%] /data/local/tmp/app.apk
          [ 62%] /data/local/tmp/app.apk
          [ 63%] /data/local/tmp/app.apk
          [ 64%] /data/local/tmp/app.apk
          [ 64%] /data/local/tmp/app.apk
          [ 65%] /data/local/tmp/app.apk
          [ 66%] /data/local/tmp/app.apk
          [ 67%] /data/local/tmp/app.apk
          [ 67%] /data/local/tmp/app.apk
          [ 68%] /data/local/tmp/app.apk
          [ 69%] /data/local/tmp/app.apk
          [ 69%] /data/local/tmp/app.apk
          [ 70%] /data/local/tmp/app.apk
          [ 71%] /data/local/tmp/app.apk
          [ 72%] /data/local/tmp/app.apk
          [ 72%] /data/local/tmp/app.apk
          [ 73%] /data/local/tmp/app.apk
          [ 74%] /data/local/tmp/app.apk
          [ 74%] /data/local/tmp/app.apk
          [ 75%] /data/local/tmp/app.apk
          [ 76%] /data/local/tmp/app.apk
          [ 77%] /data/local/tmp/app.apk
          [ 77%] /data/local/tmp/app.apk
          [ 78%] /data/local/tmp/app.apk
          [ 79%] /data/local/tmp/app.apk
          [ 79%] /data/local/tmp/app.apk
          [ 80%] /data/local/tmp/app.apk
          [ 81%] /data/local/tmp/app.apk
          [ 82%] /data/local/tmp/app.apk
          [ 82%] /data/local/tmp/app.apk
          [ 83%] /data/local/tmp/app.apk
          [ 84%] /data/local/tmp/app.apk
          [ 85%] /data/local/tmp/app.apk
          [ 85%] /data/local/tmp/app.apk
          [ 86%] /data/local/tmp/app.apk
          [ 87%] /data/local/tmp/app.apk
          [ 87%] /data/local/tmp/app.apk
          [ 88%] /data/local/tmp/app.apk
          [ 89%] /data/local/tmp/app.apk
          [ 90%] /data/local/tmp/app.apk
          [ 90%] /data/local/tmp/app.apk
          [ 91%] /data/local/tmp/app.apk
          [ 92%] /data/local/tmp/app.apk
          [ 92%] /data/local/tmp/app.apk
          [ 93%] /data/local/tmp/app.apk
          [ 94%] /data/local/tmp/app.apk
          [ 95%] /data/local/tmp/app.apk
          [ 95%] /data/local/tmp/app.apk
          [ 96%] /data/local/tmp/app.apk
          [ 97%] /data/local/tmp/app.apk
          [ 97%] /data/local/tmp/app.apk
          [ 98%] /data/local/tmp/app.apk
          [ 99%] /data/local/tmp/app.apk
          [100%] /data/local/tmp/app.apk
            pkg: /data/local/tmp/app.apk
          Success
 119 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo -n b64eab958e6baf6bba9410a7769395158e0683de > /data/local/tmp/sky.com.yourcompany.myfluttapp.sha1
   4 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo -n b64eab958e6baf6bba9410a7769395158e0683de > /data/local/tmp/sky.com.yourcompany.myfluttapp.sha1
 188 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
   1 ms • --------- beginning of main
          09-11 23:24:54.035 I/AndroidRuntime( 1497): VM exiting with result code 0.
 362 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -g -T 09-11 23:24:54.035
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -g -T 09-11 23:24:54.035
   1 ms • main: ring buffer is 256Kb (247Kb consumed), max entry is 5120b, max payload is 4076b
          system: ring buffer is 256Kb (74Kb consumed), max entry is 5120b, max payload is 4076b
          crash: ring buffer is 256Kb (2Kb consumed), max entry is 5120b, max payload is 4076b
   0 ms • Running lib/main.dart on sdk phone armv7...
   0 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v tag -T 09-11 23:24:54.035
   4 ms • /home/nb/Android/Sdk/platform-tools/adb version
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb version
   0 ms • Android Debug Bridge version 1.0.36
          Revision 8f855a3d9b35-android
   4 ms • /home/nb/Android/Sdk/platform-tools/adb start-server
   4 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb start-server
 315 ms • /home/nb/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/nb/Desktop/myfluttapp/.packages --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --build-output=build/snapshot_blob.bin /home/nb/Desktop/myfluttapp/lib/main.dart
 401 ms • --------- beginning of main
 438 ms • Building build/app.flx
   7 ms • which zip
  22 ms • Encoding zip file to build/app.flx
 181 ms • zip -q /home/nb/Desktop/myfluttapp/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
   0 ms • Exit code 0 from: zip -q /home/nb/Desktop/myfluttapp/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
   0 ms • Built build/app.flx.
   2 ms • Starting bundle for sdk phone armv7.
   0 ms • sdk phone armv7 startBundle
 918 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 push build/app.flx /data/local/tmp/dev.flx
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 push build/app.flx /data/local/tmp/dev.flx
   0 ms • [  8%] /data/local/tmp/dev.flx
          [ 17%] /data/local/tmp/dev.flx
          [ 26%] /data/local/tmp/dev.flx
          [ 35%] /data/local/tmp/dev.flx
          [ 44%] /data/local/tmp/dev.flx
          [ 53%] /data/local/tmp/dev.flx
          [ 62%] /data/local/tmp/dev.flx
          [ 71%] /data/local/tmp/dev.flx
          [ 80%] /data/local/tmp/dev.flx
          [ 89%] /data/local/tmp/dev.flx
          [ 98%] /data/local/tmp/dev.flx
          [100%] /data/local/tmp/dev.flx
4738 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.yourcompany.myfluttapp/org.domokit.sky.shell.SkyActivity
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.yourcompany.myfluttapp/org.domokit.sky.shell.SkyActivity
   0 ms • Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=com.yourcompany.myfluttapp/org.domokit.sky.shell.SkyActivity (has extras) }
7012 ms • Waiting for observatory port to be available...
  21 ms • I/flutter : [INFO:GrGLUtil.cpp(211)] nullptr GLSL version string.
   8 ms • I/flutter : [INFO:../../flutter/sky/shell/gpu/direct/ganesh_canvas.cc(47)] Failed to setup GL context. Aborting.
   0 ms • I/flutter : [INFO:../../flutter/sky/shell/gpu/direct/ganesh_canvas.cc(48)] 
   0 ms • I/flutter :          Vendor: Google (Intel Open Source Technology Center)
   0 ms • I/flutter :        Renderer: Android Emulator OpenGL ES Translator (Mesa DRI Intel(R) Ivybridge Mobile )
   0 ms • I/flutter :         Version: 2.0 (3.0 ES
   0 ms • I/flutter :  Shader Version: Unknown
   0 ms • I/flutter :      Extensions: 18 Available
   0 ms • I/flutter :                  ANDROID_EMU_CHECKSUM_HELPER_v1
   0 ms • I/flutter :                  GL_EXT_debug_marker
   1 ms • I/flutter :                  GL_OES_EGL_image
   0 ms • I/flutter :                  GL_OES_EGL_image_external
   0 ms • I/flutter :                  GL_OES_compressed_ETC1_RGB8_texture
   0 ms • I/flutter :                  GL_OES_compressed_paletted_texture
   0 ms • I/flutter :                  GL_OES_depth24
   0 ms • I/flutter :                  GL_OES_depth32
   0 ms • I/flutter :                  GL_OES_depth_texture
   0 ms • I/flutter :                  GL_OES_element_index_uint
   0 ms • I/flutter :                  GL_OES_packed_depth_stencil
   0 ms • I/flutter :                  GL_OES_rgb8_rgba8
   0 ms • I/flutter :                  GL_OES_texture_float
   0 ms • I/flutter :                  GL_OES_texture_float_linear
   0 ms • I/flutter :                  GL_OES_texture_half_float
   0 ms • I/flutter :                  GL_OES_texture_half_float_linear
   0 ms • I/flutter :                  GL_OES_texture_npot
   0 ms • I/flutter :                  GL_OES_vertex_half_float
  29 ms • I/flutter : 
   0 ms • E/flutter : [ERROR:rasterizer_direct.cc(59)] Could not create the GL interface
   3 ms • E/flutter : [ERROR:rasterizer_direct.cc(67)] WARNING: Flutter will be unable to render to the display
7207 ms • I/flutter : [INFO:GrGLUtil.cpp(211)] nullptr GLSL version string.
   7 ms • observatory port = 44288
   6 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:8102 tcp:44288
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:8102 tcp:44288
   0 ms • Observatory listening on http://127.0.0.1:8102
   1 ms • diagnostic port = 56791
   4 ms • /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:8103 tcp:56791
   0 ms • Exit code 0 from: /home/nb/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:8103 tcp:56791
6478 ms • Diagnostic server listening on http://127.0.0.1:8103
7206 ms • Connected to service protocol on port 8102
   0 ms • E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] '/home/nb/Desktop/myfluttapp/lib/main.dart': error: line 27: unexpected token 'void'
   0 ms • E/flutter :   void _incrementCounter() {
   0 ms • E/flutter :   ^
   0 ms • E/DartVM  : ../../dart/runtime/vm/dart_api_impl.cc: 1456: error: Dart_SetStickyError expects the error to be an unhandled exception error.
   0 ms • E/DartVM  : Dumping native stack trace for thread 61f
   0 ms • E/DartVM  : Stack dump aborted because GetAndValidateIsolateStackBounds.
3245 ms • --------- beginning of crash

**Comment by eseidelGoogle** [comment]
It looks like you have an error in your dart code?

```
0 ms • E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] '/home/nb/Desktop/myfluttapp/lib/main.dart': error: line 27: unexpected token 'void'
```
I'm not sure that that's causing the crash, just noting.

**Comment by eseidelGoogle** [comment]
FYI @jason-simmons re: emulators and arm.

**Comment by eseidelGoogle** [comment]
Note also your flutter version is 4 weeks old.  I'd try a `flutter upgrade`.

**Comment by chinmaygarde** [comment]
Also, the GL context could not be setup. Is GPU acceleration in the emulator enabled?

**Comment by per19** [comment]
@eseidelGoogle  even after correcting the error the emulator still crashes and my flutter version is the latest.

**Comment by eseidelGoogle** [comment]
@chinmaygarde @abarth mentioned over chat the other day that we now have a software backend?  Should we use that in emulators (--debug only) when no gpu is found?  Maybe with some warning?

**Comment by per19** [comment]
@eseidelGoogle That's will be better. Is that ready yet?

**Comment by eseidelGoogle** [comment]
I'm going to close this in favor of https://github.com/flutter/flutter/issues/5839.  We're actually finally adding a software backend. :)  Starting initially for iOS simulators, but once that's working should be easy to expand to Android emulators which would solve this bug.
