### ISSUE TITLE
[url_launcher_macos]: URL Launcher fails on macOS only in release mode

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#58153]
I have an application that is using `url_launcher` to open a browser as part of a OAuth login dance in a macOS application. It works fine in debug mode, but fails silently in production.

Any suggestions on how to narrow this bug down?

/cc @csells See... I'm making progress on a codelab =)

**Comment by stuartmorgan** [comment]
What API call is failing, specifically? I assume one of `canLaunch` or `launch`, but which one? What does "fail" mean? Does it never return? Return incorrect information?

Without having either the source, or details about what's wrong, I don't really know how to help narrow this down.

**Comment by domesticmouse** [comment]
After a bunch of printf debugging, it turns out I needed to add server capability along side the client capability that I previously added. Le sigh.

**Comment by stuartmorgan** [comment]
It required the server entitlement to use url_launcher? That would be pretty surprising (and if true, something we need to document in the plugin). Is that what was happening, or did it turn out to be a different step that was failing?

**Comment by domesticmouse** [comment]
It was something I was doing in the button’s rap handler that was failing, and near as I could tell failing silently. I learned how to run the wrapped executable directly, and thus get access to standard out. Too long since I last did macOS desktop app development.
