### ISSUE TITLE
[add2app] iOS production crash 

### ISSUE THREAD

**Issue by cngaofei** [flutter/flutter#58161]
We use add-to-app development mode. 
I can't reproduce the crash. About one in 10000 iOS users will crash.
The crash stack is:

0 | Flutter | 0x0000000109c80644 auto fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>::operator()<>() const (memory:2617)
-- | -- | --
1 | Flutter | 0x0000000109c79a8c flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >) (shell.cc:633)
2 | Flutter | 0x0000000109c1bb94 -[FlutterViewController surfaceUpdated:] (platform_view.cc:77)
3 | TBClient | 0x0000000101f37f30 tbSurfaceUpdated (FLBFlutterViewContainer.m:0)
4 | TBClient | 0x0000000101f39774 -[FLBFlutterViewContainer viewDidAppear:] (FLBFlutterViewContainer.m:368)
5 | UIKit | 0x000000018ee38670 -[UIViewController _setViewAppearState:isAnimating:] + 852
6 | UIKit | 0x000000018ee38bdc -[UIViewController _endAppearanceTransition:] + 228
7 | UIKit | 0x000000018eedde74 -[UINavigationController navigationTransitionView:didEndTransition:fromView:toView:] + 1328
8 | UIKit | 0x000000018efa48b0 ___49-[UINavigationController _startCustomTransition:]_block_invoke + 252
9 | UIKit | 0x000000018ef30910 -[_UIViewControllerTransitionContext completeTransition:] + 116
10 | UIKit | 0x000000018f074c98 ___53-[_UINavigationParallaxTransition animateTransition:]_block_invoke.124 + 752
11 | UIKit | 0x000000018ee58240 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 764
12 | UIKit | 0x000000018ee57bb4 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 312
13 | UIKit | 0x000000018ee578c0 -[UIViewAnimationState animationDidStop:finished:] + 296
14 | UIKit | 0x000000018ee57960 -[UIViewAnimationState animationDidStop:finished:] + 456
15 | QuartzCore | 0x0000000189990e14 CA::Layer::run_animation_callbacks(void*) + 284
16 | libdispatch.dylib | 0x00000001852baa14 __dispatch_client_callout + 16
17 | libdispatch.dylib | 0x00000001852c7698 __dispatch_main_queue_callback_4CF$VARIANT$mp + 1016
18 | CoreFoundation | 0x00000001858e6544 ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
19 | CoreFoundation | 0x00000001858e4120 ___CFRunLoopRun + 2012
20 | CoreFoundation | 0x0000000185803e58 _CFRunLoopRunSpecific + 436
21 | GraphicsServices | 0x00000001876b0f84 _GSEventRunModal + 100
22 | UIKit | 0x000000018ee8367c _UIApplicationMain + 236
23 | TBClient | 0x00000001009152d0 main (main.m:25)
24 | libdyld.dylib | 0x000000018532056c _start + 4
Register | - | pc: 0x0000000109c80644 fp: 0x000000016f80a160 sp: 0x000000016f80a130 x0: 0x0000000000000000 x1: 0x0000000002dcc9c0 x2: 0x0000000000000000 x3: 0x000000000027c371 x4: 0x0000000000002060 x5: 0x0000000000000060 x6: 0x0000000000000000 x7: 0x0000000000000000 x8: 0x0000000000000000 x9: 0x0000020000000303 x10: 0x0000000000000200 x11: 0x0000000000000001 x12: 0x0000030000000300 x13: 0x0000000000000000 x14: 0x0000000000000303 x15: 0x0000000000000000 x16: 0x0000000185567b5c x17: 0x00000000ffffffff x18: 0xfffffff014c9925c x19: 0x0000000168396a40 x20: 0x00000001637890f0 x21: 0x000000016379a940 x22: 0x000000016379a9d8 x23: 0x000000016379a9d8 x24: 0x0000000000000000 x25: 0x00000001635a79c0 x26: 0x000000016f80a188 x27: 0x000000016379b200 x28: 0x0000000163b0ebf0 lr: 0x0000000109c80640 cpsr: 0x0000000060000000

## Steps to Reproduce

I can't reproduce it. About one in 10000 IOS users will crash.

**Expected results:** 
The engine source code is:
![111](https://user-images.githubusercontent.com/7983540/83132843-9174f300-a114-11ea-8e26-c24886530119.png)

![222](https://user-images.githubusercontent.com/7983540/83132859-95a11080-a114-11ea-9b56-885c17894e70.png)

I also want to know when the GPU the and platform threads are the same.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G4032, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

```

</details>

**Comment by TahaTesser** [comment]
Hi @cngaofei 
Please upgrade to latest `stable`, i noticed you're on old stable. 
Can you please provide `pubsepc.yaml`?
Thank you

**Comment by cngaofei** [comment]
@TahaTesser , thanks for your response.
 It's difficult to provide full quantity pubspeck.yaml, because we have developed many packages. I think the dependency associated with this comparison is flitter_ Boost, for the development of add to app mode.
We tend to be cautious about upgrading the SDK version, which has been running stably online for a long time. I have read the latest engine code, and this one should not be changed. I want to know about engine/src/flutter/shell/common/shell.cc line 585, When the GPU and platform threads are the same
![222](https://user-images.githubusercontent.com/7983540/83214282-c7f35200-a196-11ea-9070-83b2506cbd82.png)
Thank you

**Comment by jmagman** [comment]
@liyuqian I think you touched this recently?

**Comment by liyuqian** [comment]
I renamed `gpu_task` to `raster_task` but that shouldn't change any behaviors. @amirh wrote that `gpu_task()` line in https://github.com/flutter/engine/commit/629072277dc73e0628afab7ba7142f7d582996ad before my rename.

**Comment by cngaofei** [comment]
@amirh ,
By looking at the comments, I understand that it is to solve a deadlock problem. The root cause is that GPU thread is the same as platform thread. According to my general cognition, there are four related threads (platform, UI, GPU, IO) after engine is started, so can you explain when the platform thread of engine is the same as GPU thread, or what kind of design is expected?
Thanks！

**Comment by chinmaygarde** [comment]
If there is a platform view in the Flutter application, that can only be accessed on the Cocoa main thread. In such cases, platform and GPU task runners execute their tasks on the same thread. We may be handling that incorrectly in certain cases.

Is it possible to prepare a reduced test case for this? That would greatly help.

cc @cyanglaz as he has been taking a look at related subsystems.

**Comment by cngaofei** [comment]
@chinmaygarde ，thanks for your reply. 
I have been trying to reproduce, but I haven't found the recurrence step.
We use add2app mode to develop and share an engine instance globally.  I'm sure that we don't use other platform view but [FlutterView alloc]. All of them are drawn by flutter. 
When I open the flutter page, I will create a FluterViewController container, and then attach engine. When my FluterViewController container calls viewDidAppear, I manually call FluterViewController surfaceUpdated, and then[_ engine.get () platformView] -> NotifyCreated();->Shell::OnPlatformViewCreated->gpu_task () and then it crashes.

by quote,
"If there is a platform view in the Flutter application, that can only be accessed on the Cocoa main thread. In such cases, platform and GPU task runners execute their tasks on the same thread."
This means that when opening a FlutterViewController and initializing FultterView, both platform and GPU task runners execute their tasks on the platform thread. 
I'm curious to know how gputaskrunner works, such as
1. Initialization of gpu task runner;
2. When is the gpu task runner covered as platform task runner;
3. Whether to return to its own independent state after being overwritten as platform task runner

**Comment by cngaofei** [comment]
Sdk 1.17.5 is OK.
