### ISSUE TITLE
How to use vitool

### ISSUE THREAD

**Issue by Crazyx001** [flutter/flutter#58178]
Hi, I would like to know how can I generate an AnimatedIcon using vitool?

I am using VS Code

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by bdangvnt** [comment]
> Hi, I would like to know how can I generate an AnimatedIcon using vitool?
> 
> I am using VS Code

<script src="https://gist.github.com/bdangvnt/1b419729f2bfa46ce600c463a31d84be.js"></script>
