### ISSUE TITLE
[web] Detect browser 

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#58171]
## Use case

At the time, it looks like Flutter Web is not fully compatible for the Web, but the browser where it works the best is definitely Chrome. There are several issues on other browsers, specifically Microsoft browsers. I would like to show the users a warning when they are browsing my site on something other than Chrome so they can use the proper browser. I haven't found a way to detect this on Flutter. Even thought there is a way to detect iOS/Android/Web, once you are in Web you don't know which browser you are in.

## Proposal

Flutter should have a way to return which browser it is being ran. 

It would be awesome to do something like isChrome, isEdge, isFirefox, etc, although maintaining all the different browsers available might be a lot of effort, so at least there should be a method to get the Browser's UserAgent.

**Comment by iapicca** [comment]
Hi @jlubeck 
your proposal seems to be within the scope of [device_info](https://pub.dev/packages/device_info)
that at the moment isn't supported for web

(and required an inelegant 
`import '...'  if(dart.library.io)  'dart.library.io';`
 to don't break on web)

would you mind if I consider you proposal as "support device info for web"?
thank you

**Comment by jlubeck** [comment]
Of course @iapicca ! I tried searching for a package before opening the issue, but couldn't find one that worked on both mobile and web, so yes, that would be highly appreciated and probably worthy of closing this ticket

**Comment by jlubeck** [comment]
I wonder if people won't be confused though... Seems like your package returns phone model being used. Wouldn't people expect to get `Macbook Pro` or `HP Laptop` or whatever? Not even sure if that is possible though, but would be wise to document it properly. Or maybe just create a `BrowserInfo` ?

**Comment by iapicca** [comment]
Hi again @jlubeck 
you are making a good point
Thank you

**Comment by yjbanov** [comment]
Related https://github.com/flutter/flutter/issues/52108

**Comment by yjbanov** [comment]
There is an existing package https://pub.dev/packages/platform_detect that does this. You can use this package today using conditional imports. If conditional imports are not convenient to use, consider contributing to that package and enabling it on all Flutter platforms.

**Comment by jonbhanson** [comment]
A better choice as of today is [package_info_plus](https://pub.dev/packages/package_info_plus).
