### ISSUE TITLE
If multiple forms and form keys in single widget and in multiple steps, after first step, keypress of tab doesnt shift focus to next input field

### ISSUE THREAD

**Issue by bhaskar8088** [flutter/flutter#58173]
Hi,

To reduce application complexity(that is without using redux or message bus), I am building forms within single widget without making separate widget for each step. I am not using stepper widget though, using own logic.

When next is clicked, it will validate form for that step and move to next step using code I wrote.

When I press tab on my physical keyboard in desktop/chrome, it is moving to next input field without doing any kind of focusnode etc. But thats working only in step1, but in step2 it is not working.

But it is working again in any step if I follow this link https://codewithandrea.com/tips/2020-01-22-easily-move-focus-scope-node/ using focusscope.

May I know what I missed? 

Also, hope this process of multiple steps work in a single widget rather than multiple  widgets doesnt have any issues.

Also, since I am using custom steps(without separate widgets), I overrided back button using onwillpopup. Hope this is a proper way and hope it works all the time.

And to close window finally, I had to call below

```   
 back() async {
      if(step > 1) {
        setState(() {
         step = step - 1;
       });
      } else {
    // close
    return (await showDialog(
      context: context,
      builder: (context) => new AlertDialog(
        title: new Text('Are you sure?'),
        content: new Text('Do you want to close this form? All the data you typed will be lost.'),
        actions: <Widget>[
          new FlatButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: new Text('No'),
          ),
          new FlatButton(
            onPressed: () { 
              Navigator.of(context).pop(true);
              Navigator.of(context).pop(true);
             }, 
            child: new Text('Yes'),
          ),
        ],
      ),
    )) ?? false;    
  }
    }
```

If you observe, I am calling `Navigator.of(context).pop(true);` twice, only then it is working. Not sure the reason for it.

I am using flutter web in production, hope that doesnt break anything as flutter web is still in beta. Waiting for it to production ready but I am already in production :)

**Comment by iapicca** [comment]
Hi @bhaskar8088 
Can you please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
