### ISSUE TITLE
Create new flutter project fails from atom plugin, could not find an option names "out"

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#5818]
## Steps to Reproduce

Packages > Flutter > Create new Flutter Project
Set path

Error: 

Could not find an option named "out".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/lukechurch/GitRepos/flutter
    • Framework revision b298bdc8c4 (3 days ago), 2016-09-09 16:55:55
    • Engine revision a55fa1efb9
    • Tools Dart version 1.20.0-dev.1.0
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/lukechurch/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.6
[✓] Connected devices
    • None

I'm pretty sure that I've updated everything I can find to update :)

**Comment by devoncarew** [comment]
I think you're dartlang plugin is out of date - you're using `0.6.6`, and the latest is `0.6.38`. I'd make sure there's not an update available. If you had a development setup for the plugin, you'll need `apm uninstall` from the dartlang git dir, then reinstall in atom as normal.

Feel free to ping if you're still seeing issues -
