### ISSUE TITLE
[web]: Dotted line not rendering or renders faded on web

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#58182]
Using the https://pub.dev/packages/dotted_border plugin to create  a dotted line border in the app. 

With the HTML backend the dotted line renders but not completely. 
<img width="111" alt="Screen Shot 2020-05-26 at 5 07 30 PM" src="https://user-images.githubusercontent.com/56849473/83179443-eabe3180-a0d6-11ea-9d54-39acbe1087cc.png">

With Canvaskit the dotted line doesn't render at all.
<img width="118" alt="Screen Shot 2020-05-26 at 5 41 30 PM" src="https://user-images.githubusercontent.com/56849473/83179493-f9a4e400-a0d6-11ea-873b-a76455a764d2.png">

**Comment by yjbanov** [comment]
The HTML issue will be fixed as part of https://github.com/flutter/flutter/issues/57801.

**Comment by yjbanov** [comment]
I verified that https://github.com/flutter/engine/pull/18667 fixes this issue in CanvasKit. Let's track the HTML issue in https://github.com/flutter/flutter/issues/57801. Closing this one.

**Comment by mariamhas** [comment]
reopenning since @ferhatb believes the issue #57801 doesn't capture this issue for HTML properly and he will look into it further

**Comment by ferhatb** [comment]
Notes: Simple customer app scenario can be repro'd with:
RawMaterialButton(
              fillColor: Colors.transparent,
              highlightColor: Colors.orange.withOpacity(.1),
              shape: CircleBorder(),
              child:
                DottedBorder(
                  dashPattern: [3, 5],
                  color: Colors.black.withOpacity(0.7),
                  borderType: BorderType.Circle,
                  radius: Radius.circular(8),
                  child: SizedBox(width:64, height:64, child: Text('W')),
                ),
            ),

The CircleBorder clipping by RawMaterialButton is suspect.

**Comment by yjbanov** [comment]
This issue was labeled for canvaskit, which is fixed now. Since we want to use the same issue for HTML I will relabel it accordingly.

**Comment by mariamhas** [comment]
Definitely has to do with RawMaterialButton wrapping the dottedBorder, tried the repo code and the dotted line is fading. 

RawMaterialButton(
            fillColor: Colors.transparent,
            highlightColor: Colors.orange.withOpacity(.1),
            shape: CircleBorder(),
            child: DottedBorder(
              dashPattern: [3, 5],
              color: Colors.black.withOpacity(0.7),
              borderType: BorderType.Circle,
              radius: Radius.circular(8),
              child: SizedBox(
                width: 64,
                height: 64,
                child: Center(child: Text('W')),
<img width="222" alt="Screen Shot 2020-07-13 at 3 31 52 PM" src="https://user-images.githubusercontent.com/56849473/87360331-bdaace80-c51e-11ea-8af1-490fc1fef293.png">


If you remove the shape: CircleBorder, the fading is less but still there:
<img width="215" alt="Screen Shot 2020-07-13 at 3 34 52 PM" src="https://user-images.githubusercontent.com/56849473/87360383-ddda8d80-c51e-11ea-8fb8-d1826f386190.png">

But if you remove the RawMaterialButton, and only use dottedBorder, the border doesn't fade (this is how flokk.app does it and can't repo the fading border on that app anymore)
<img width="297" alt="Screen Shot 2020-07-13 at 3 36 53 PM" src="https://user-images.githubusercontent.com/56849473/87360422-f054c700-c51e-11ea-915f-f68429924488.png">

**Comment by ferhatb** [comment]
Tested using HTML backend on latest master.

![Screen Shot 2020-10-28 at 3 14 27 PM](https://user-images.githubusercontent.com/5061034/97503171-c8ed0300-1931-11eb-9144-19a625e4dac2.png)

Looks like it was addressed by clipping fixes.
