### ISSUE TITLE
Try measure GPU percentage using IOKit

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58197]
We previously tried using Instruments to get GPU percentage but it's using some private APIs and turns out to be not easily maintainable (https://github.com/flutter/flutter/issues/45435).

Recently, while Kaushik was exploring new profiling frameworks, we found that [IOKit was recently made public in 2017 and there seems to be some public  APIs there to get GPU percentages][1].

Specifically,
- https://github.com/rickytan/GPUUtilization is a nice example of how to use IOKit to get GPU percentages
- https://github.com/flutter/engine/pull/18516 is a nice example of how to integrate the measurement into Kaushik's profiling frameworks.

We should be able to combine those two to provide GPU measurements in tracing events. That should also allow DevTools to display GPU percentages, and solve our long-standing issue of re-enabling GPU percentage tests (https://github.com/flutter/flutter/issues/45435).

[1]: https://docs.google.com/document/d/1z_V69XzRct3vR7mBZ9tuuS1pZ_e7FQkuzbVJjXxMeaI/edit#bookmark=id.vz8q8s9luwr2.

**Comment by liyuqian** [comment]
CC @gaaclarke

**Comment by gaaclarke** [comment]
https://github.com/rickytan/GPUUtilization does not work on my device (metal with 13.4.1), but appears to work on simulator.  I suspect the name `sgx` doesn't match my device name.

**Comment by liyuqian** [comment]
Closing as this is done by https://github.com/flutter/engine/pull/18752
