### ISSUE TITLE
Flutter create issue link in Atom 404s

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#5819]
## Steps to Reproduce

Packages > Flutter > Send Feedback

Opens a browser window for 

https://github.com/flutter/atom-flutter/issues/new?body=Atom%201.10.2,%20flutter%20plugin%200.2.4,%20running%20on%20macos.

Which is a dead link.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/lukechurch/GitRepos/flutter
    • Framework revision b298bdc8c4 (3 days ago), 2016-09-09 16:55:55
    • Engine revision a55fa1efb9
    • Tools Dart version 1.20.0-dev.1.0
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/lukechurch/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.6
[✓] Connected devices
    • None

**Comment by devoncarew** [comment]
Fixed here: https://github.com/flutter/atom-flutter/commit/bbdb4e639abe166ad8c19a94c218f07a6c12c0b3, but we need to publish a new version of the plugin.

**Comment by devoncarew** [comment]
(published)
