### ISSUE TITLE
Flutter doctor with android studio 4.0

### ISSUE THREAD

**Issue by Nothing-Works** [flutter/flutter#58205]
![1](https://user-images.githubusercontent.com/18606648/83200975-9c716700-a198-11ea-9506-53c175a7a51c.PNG)
![2](https://user-images.githubusercontent.com/18606648/83200980-9ed3c100-a198-11ea-81df-de69e644ea2f.PNG)
I have all the plugins installed, but it's saying I am missing them. Does anyone have this problem?
This only happens after I upgrade to 4.0

**Comment by devmgs** [comment]
Its not compatible https://github.com/flutter/flutter-intellij/issues/4581

**Comment by iapicca** [comment]
Hi @Nothing-Works 
I see there's an open [issue](https://github.com/flutter/flutter-intellij/issues/4581) addressing the case you described (thank you @devmgs)
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
