### ISSUE TITLE
image_picker serious bug：native project textfeild's content will be lost after pickImg

### ISSUE THREAD

**Issue by fg2q1q3q** [flutter/flutter#58219]
The [image_picker](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker) package does not have any problems in pure flutter project, but in the native mixed project, if the page contains TextFeild, after the image is selected, the content entered by textfeild will be lost, which is a very serious bug.

Below is my environment
`Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git Framework • revision 0b8abb4724 (4 months ago) • 2020-02-11 11:44:36 -0800 Engine • revision e1e6ced81d Tools • Dart 2.7.0`

**Comment by TahaTesser** [comment]
Hi @fg2q1q3q 
Please upgrade to latest `stable` channel and try again 
If the problem persist with upgrade,  can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample from module
Thank you"

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
