### ISSUE TITLE
Replace an ugly white box created by ReorderableList widget on element drag with a normal shadow

### ISSUE THREAD

**Issue by limitedeternity** [flutter/flutter#58227]
## Proposal

Patch file: https://gist.github.com/limitedeternity/6cb5dfee161fc45e84c8d13933072760 (applies to reorderable_list.dart on master branch)

**Comment by limitedeternity** [comment]
Before:
![Screenshot_20200529-011158](https://user-images.githubusercontent.com/24318966/83247815-c6348900-a1ac-11ea-976e-54cfb5d59c66.png)
After:
![Screenshot_20200529-021839](https://user-images.githubusercontent.com/24318966/83247832-cd5b9700-a1ac-11ea-87fb-89490e9035b2.png)

**Comment by TahaTesser** [comment]
Hi @limitedeternity 
Looks like look a nice custom implementation but it doesn't  material  specs
matchhttps://material.io/components/lists#behavior otherwise feel free to create PR

if you disagree please write in the comments and I will reopen it. 
Thank you"

**Comment by braval** [comment]
Is there a way to control the drag shadow? or remove it?
