### ISSUE TITLE
web：   flutter create .   it not work

### ISSUE THREAD

**Issue by zhuyonghao** [flutter/flutter#58225]
![image](https://user-images.githubusercontent.com/18735317/83229301-4b726a80-a1ba-11ea-89b6-decf65536260.png)

it not work

**Comment by iapicca** [comment]
Hi @zhuyonghao 
it doesn't seem to be a flutter error,
could you please run locally
```bash
flutter channel beta
flutter upgrade --force
flutter create test
cd test
flutter config --enable-web
flutter create .
flutter run -d chrome --verbose
```
if the issue persist
please provide your `flutter doctor -v`
and any logs with error encountered following these steps
Thank you
