### ISSUE TITLE
[proposal to expose property] When using Chinese keyboard for input we can't tell whether it's a pre input state or an input state

### ISSUE THREAD

**Issue by Avanlanching** [flutter/flutter#58220]
I need to monitor the value of the 'TextField' to change the UI layout,but the keyboard on iOS was interrupted before it could input the complete Chinese.We can't tell whether it's a pre input state or an input state.help,help,help

**Comment by MrLittleStrong** [comment]
There is something different with Native TextField and flutter TextField in inputing Chinese using simplified Chinese Keyboard. 
Using Native Textfield, I can input a serials of pinyin of a sentence, while using flutter Textfield when I'm trying to input the second character's pinyin, the previous pinyin is forced to be unchangeable, so I can only input one character at a time.

**Comment by TahaTesser** [comment]
Hi @MrLittleStrong 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by Avanlanching** [comment]
I fine that google can know current input source was pre input or normal input. On TextField Source have multiple styles, normal and underline.

**Comment by TahaTesser** [comment]
Hi @Avanlanching 
Is this a feature request? You mentioned iOS interruption issue so that's why i asked code sample
Do you wanna know if the text input source pre-input or normal right/?
Thank you

**Comment by Avanlanching** [comment]
> Hi @Avanlanching
> Is this a feature request? You mentioned iOS interruption issue so that's why i asked code sample
> Do you wanna know if the text input source pre-input or normal right/?
> Thank you

No, I just want Google to provide a property，So that I can judge the status of my input. And I fine 'TextEdtingController' somthinge what 2 property, but then are private;
So I inherit it and rewrite it；
code: 

class MyTextEditController extends TextEditingController {
  TargetPlatform targetPlatform;
  var completeText = '';
  bool withComposing = false;
  CxyTextEditController();

  @override
  TextSpan buildTextSpan({TextStyle style , bool withComposing}) {
    if (!value.composing.isValid || !withComposing) {
      if (completeText != value.text) {
        completeText = value.text;
        WidgetsBinding.instance.addPostFrameCallback((_) {
          notifyListeners();
        });
      }
      return TextSpan(style: style, text: text);
    }

    String string = value.composing.textInside(value.text);
    if (string == null || string == '') {
      if (completeText != value.text) {
        completeText = value.text;
        WidgetsBinding.instance.addPostFrameCallback((_) {
          notifyListeners();
        });
      }
    }
    return super.buildTextSpan(style: style, withComposing: withComposing);
  }
}

**Comment by cbracken** [comment]
@Avanlanching I'm not sure I understand what behaviour you're seeing.

If you need access to the composing text region, you can get a hold of it via [TextEditingController.value](https://api.flutter.dev/flutter/widgets/TextEditingController/value.html) then [TextEditingValue.composing](https://api.flutter.dev/flutter/services/TextEditingValue/composing.html) to get the range covering the composing region.

Please add the following to the bug so we can reproduce this.
1. A code sample that allows us to reproduce this.
2. Detailed reproduction steps so we can verify this.
3. The output of `flutter doctor`.
4. Which device you're using and whether a custom keyboard is installed.

If you can capture a screen recording of this, even better.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 

This may be related to https://github.com/flutter/flutter/issues/67898.

We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
