### ISSUE TITLE
Add camera light sensor 

### ISSUE THREAD

**Issue by thanhbinh84** [flutter/flutter#58233]
## Use case
Ask users to increase light when taking a photo 

## Proposal
Currently there is a lib but for android only 
https://pub.dev/packages/light
For iOS, there is a solution with camera 
https://stackoverflow.com/questions/22753165/detecting-if-iphone-is-in-a-dark-room/22836060#22836060
We might combine these into current camera lib.

**Comment by iapicca** [comment]
Hi @thanhbinh84 
I see there's an open [issue](https://github.com/flutter/flutter/issues/31225) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
