### ISSUE TITLE
Create a new flutter project in Android Studio takes forever - solved

### ISSUE THREAD

**Issue by akk99** [flutter/flutter#58236]
I would like to provide a solution that has worked for me but is not mentioned yet, AFAICT. 

Flutter SDK in subfolder somewhere on D, and having set the new project to start, I went to have breakfast. One hour later, the creation of new project was still in progress. It suddenly occurred to me that my antivirus might be firewalling AS. I switched the firewall off, and within seconds, the creation of a new project was completed. 

Good luck .

**Comment by TahaTesser** [comment]
Hi @akk99 
Thank you but there is no need for this for a new issue for this
given your it's solved I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
