### ISSUE TITLE
Linux Fultter desktop - unable to run app from compiled executable, flutter run works

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#58239]
Flutter doctor output:

<pre><font color="#4D9A05">[✓]</font> Flutter (Channel master, 1.19.0-2.0.pre.193, on Linux, locale pl_PL.UTF-8)
<b>    </b><font color="#89E234"><b>•</b></font><b> Flutter version 1.19.0-2.0.pre.193 at /home/michal/android/flutter</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Framework revision fed18fc433 (3 hours ago), 2020-05-29 03:43:01 -0400</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Engine revision 17737e6fd4</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)</b>

<font color="#4D9A05">[✓]</font> Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc2)
<b>    </b><font color="#89E234"><b>•</b></font><b> Android SDK at /home/michal/Android/Sdk</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Platform android-29, build-tools 29.0.0-rc2</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> ANDROID_HOME = /home/michal/Android/Sdk</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Java binary at: /home/michal/android/studio/jre/bin/java</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_212-release-1586-b4-5784211)</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> All Android licenses accepted.</b>

<font color="#4D9A05">[✓]</font> Chrome - develop for the web
<b>    </b><font color="#89E234"><b>•</b></font><b> Chrome at google-chrome</b>

<font color="#4D9A05">[✓]</font> Linux toolchain - develop for Linux desktop
<b>    </b><font color="#89E234"><b>•</b></font><b> clang version 9.0.1-12</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> cmake version 3.16.3</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> ninja version 1.10.0</b>

<font color="#4D9A05">[✓]</font> Android Studio (version 3.6)
<b>    </b><font color="#89E234"><b>•</b></font><b> Android Studio at /home/michal/android/studio</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Flutter plugin version 45.1.1</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Dart plugin version 192.8052</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_212-release-1586-b4-5784211)</b>

<font color="#4D9A05">[✓]</font> VS Code (version 1.45.1)
<b>    </b><font color="#89E234"><b>•</b></font><b> VS Code at /usr/share/code</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Flutter extension version 3.8.1</b>

<font color="#4D9A05">[✓]</font> Connected device (4 available)
<b>    </b><font color="#89E234"><b>•</b></font><b> Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10</b>
<b>      (API 29) (emulator)</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Linux                        • Linux         • linux-x64      • Linux</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Web Server                   • web-server    • web-javascript • Flutter</b>
<b>      Tools</b>
<b>    </b><font color="#89E234"><b>•</b></font><b> Chrome                       • chrome        • web-javascript • Google</b>
<b>      Chrome 84.0.4147.21 dev</b>

<font color="#4D9A05">•</font> No issues found!</pre>

My app compiles succesfully and I am able to run it without any issues with `flutter run -d Linux`. However, that does not work when I try to run directly compiled executable, in this case I'm getting error message:

<pre>embedder.cc (781): &apos;FlutterEngineInitialize&apos; returned &apos;kInvalidArguments&apos;. Not running in AOT mode but could not resolve the kernel binary.
Failed to start Flutter engine: error 2
Failed to create window.
</pre>

Please advice what am I doing wrong, or confirm that's Flutter bug.

**Comment by stuartmorgan** [comment]
The raw build output isn't intended to be run, as explained [here](https://stackoverflow.com/a/62087380)
