### ISSUE TITLE
Image of library installed as pod is not displayed

### ISSUE THREAD

**Issue by zoyi-jin** [flutter/flutter#58232]
After pod init in flutter default project, I added a library that provides a screen.
This library is executable only in swift, has internal assets, and has its own controller.

As a result of the current verification, all functions work normally, but only the image of assets cannot be loaded.

When checked through the debugger,
```
UIImage (named: named, in: bundle, compatibleWith: nil)
```
is nil.

When it works in swift, it works normally.

**Expected results:** 
<img width="99" alt="image" src="https://user-images.githubusercontent.com/52900212/83240817-e5dfa780-a1d4-11ea-8f5e-400f3ccee536.png">

**Actual results:** 
<img width="121" alt="image" src="https://user-images.githubusercontent.com/52900212/83240559-897c8800-a1d4-11ea-9662-43a9720d092b.png">

<details>
  <summary>doctor</summary>

```console
flutter doctor -v



Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale ko-KR)
    • Flutter version 1.17.2 at /Users/kimjh/Documents/flutter
    • Framework revision 5f21edf8b6 (13 hours ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kimjh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 93D2DC6A-A3D1-4A72-BF79-2A4880E0C712 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)
```

</details>

**Comment by iapicca** [comment]
Hi @zoyi-jin 
are you using a [platform view](https://medium.com/@phoomparin/how-to-use-native-uis-in-flutter-with-swift-platform-view-8b4dc7f833d8) ?
Could you please provide a reproducible minimal code sample?
Thank you

possibly related to https://github.com/flutter/flutter/issues/33850
https://github.com/flutter/flutter/issues/16049

**Comment by zoyi-jin** [comment]
I solved it by modifying the library podspec.

existing :
`` `
s.resource_bundles = ...
`` `

change :
`` `
s.resource_bundles = ...
s.resources = ...
`` `

Thanks!

**Comment by tdc-w** [comment]
@zoyi-jin 
I have the same problem.
Do you set both resources and resource_bundles?
As you say, if adding resources, images of library is displayed. 

However, React Native app references the same iOS library, and an error occurs.
This error is cleared by using resource_bundles.
https://github.com/CocoaPods/CocoaPods/issues/8431

Is there another way without resources?

**Comment by yy1300326388** [comment]
@zoyi-jin  Can you provide some sample code? This is very important to me, I have been troubled by this problem for a long time, and I have very little iOS experience

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint fast_phone_login_aliyun.podspec' to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'fast_phone_login_aliyun'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'
  s.vendored_frameworks = 'ATAuthSDK.framework'
#  s.resources = ['ATAuthSDK.framework/ATAuthSDK.bundle/*.png']
  s.resource_bundles = { 'ATAuthSDK' => ['ATAuthSDK.framework/ATAuthSDK.bundle/*'] }
  s.resources = ['ATAuthSDK.framework/ATAuthSDK.bundle/*']

  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-lObjC','OTHER_LDFLAGS' => '-all_load','DEFINES_MODULE' => 'YES','EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
end

```
