### ISSUE TITLE
Cannot give the Container widget a white shade

### ISSUE THREAD

**Issue by flutternoob** [flutter/flutter#58235]
I cannot give the Container widget any white shade. If I set the backgroundColor property of the Scaffold widget to a shade of black (or transparent), only then is the white shade shown in the Container, although with some opacity. How to solve this problem?

Here is my code (code is included in the bug report as well):

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(),
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
            elevation: 10,
            backgroundColor: Colors.blue[900],
            title: Text('Demo App'),
            centerTitle: true,
          ),
          body: Center(child: Container(color: Colors.white10, width: 200, height: 200)),
        ),
      ),
    );
  }
}
```

**Expected results:**

White shade should be applied to the Container widget using its color property.

**Actual results:** 

White shade was not applied to the Container widget.

<details>
  <summary>Logs</summary>

Bug Report

[bug.zip](https://github.com/flutter/flutter/files/4701032/bug.zip)

Flutter Analyze Results

```
[  +18 ms] Analyzing doc_app... (completed in 83.9s)
[   +4 ms] No issues found! (ran in 84.0s)
[   +3 ms] "flutter analyze" took 91,235ms.
```

Flutter Doctor Results

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at c:\src\flutter
    • Framework revision f139b11009 (9 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Ankush\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] Connected device (1 available)
    • SM A205F • RZ8M92CX7PJ • android-arm64 • Android 9 (API 28)

• No issues found!

```

</details>

**Comment by Zazo032** [comment]
https://api.flutter.dev/flutter/material/Colors/white10-constant.html

`white10` means color white with 10% opacity. If `Scaffold`'s background is white, you'll see that still white as you have a 10% opacity white over a 100% opacity white. Try changing `Scaffold`'s `backgroundColor` property.

**Comment by flutternoob** [comment]
Thanks for the tip! I decided to wrap the Container in a Container and set the color property of the parent Container to black. That way I was able to change the child Container's color to any shade of white.

**Comment by Zazo032** [comment]
If you're going to only set the `color` property of a `Container`, try using `ColoredBox`.
