### ISSUE TITLE
Android SDK file not found after upgrading to Android Studio 4.0

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#58234]
After upgrading to AS 4.0, this is the output of `flutter doctor -v`:
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.193, on Microsoft Windows [VersiÃ³n 10.0.19041.264], locale es-ES)
    • Flutter version 1.19.0-2.0.pre.193 at C:\src\flutter
    • Framework revision fed18fc433 (85 minutes ago), 2020-05-29 03:43:01 -0400
    • Engine revision 17737e6fd4
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    ✗ Android SDK file not found: C:\Users\crist\AppData\Local\Android\sdk\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.4-dev.7
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.
```
The part where it says;
```
    ✗ Android SDK file not found: C:\Users\crist\AppData\Local\Android\sdk\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
```
My Android SDK wasn't changed, but that file it's looking for right now no longer exists. This is the outpud of `dir` on `platform-29` directory:
```
28/05/2020  20:57    <DIR>          .
28/05/2020  20:57    <DIR>          ..
28/05/2020  20:57    <DIR>          data
28/05/2020  20:57            30.605 framework.aidl
28/05/2020  20:57            17.835 package.xml
28/05/2020  20:57               209 sdk.properties
28/05/2020  20:57    <DIR>          skins
```

**Comment by Zazo032** [comment]
Screenshots of Android SDK Manager:

![image](https://user-images.githubusercontent.com/2807712/83243556-5c14e780-a19e-11ea-93ea-5cf57b0b2688.png)

![image](https://user-images.githubusercontent.com/2807712/83243614-764ec580-a19e-11ea-80cf-4faea08cf7b8.png)

**Comment by iapicca** [comment]
Hi @Zazo032 
I see there's an open [issue](https://github.com/flutter/flutter-intellij/issues/4581) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Zazo032** [comment]
Hi @iapicca 
This is not about Flutter's Android Studio plugin support, as you can see here: https://github.com/flutter/flutter-intellij/issues/4581#issuecomment-635866705
it's a false alarm, after upgrading to 4.0, the IDE will suggest you compatible versions of the plugins. This is about the flutter tool support, seems to be looking for a file that no longer exists.

**Comment by Zazo032** [comment]
@iapicca @TahaTesser https://github.com/flutter/flutter-intellij/issues/4581#issuecomment-635933675
