### ISSUE TITLE
flutter_gallery_ios__transition_perf 90th_percentile_frame_rasterizer_time_millis noisier, likely regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#58248]
![Screen Shot 2020-05-29 at 8 23 39 AM](https://user-images.githubusercontent.com/1435716/83276603-b8b7d880-a185-11ea-98c1-d909419e2a96.png)

Due to noise, it's difficult to determine a regression point.

cc @liyuqian

**Comment by liyuqian** [comment]
I tested 10 times locally with 0cca3c1d62095e8d94b9d13714f586b852e0be4b, and only saw 2 runs to have 16ms 90th percentile. This 20% probability is probably closer to those before the regression. Maybe this is another infra-related regression that we can only fix after getting back to our device lab physically? CC @godofredoc 

|  90th_percentile_frame_rasterizer_time_millis |
| --- |
|  3.05 |
|  7.925 |
|  2.942 |
|  3.692 |
|  2.886 |
|  2.506 |
|  3.026 |
|  16.468 |
|  16.188 |
|  6.93 |

**Comment by godofredoc** [comment]
What part of the triage can not be done remotely?

Now we do have instructions to reboot devices, collect screenshots or video.

https://g3doc.corp.google.com/company/teams/flutter/devicelab/macos_host.md#attached-ios-device

**Comment by kf6gpe** [comment]
@liyuqian Did you get a chance to follow @godofredoc's comments about collecting info from the lab devices to see if this was constrained to an issue in the lab?

**Comment by liyuqian** [comment]
Not yet. I'm pushing it to my queue and hopefully I can take some video screenshots this week to analyze it.

**Comment by liyuqian** [comment]
I confirmed that the the iPhones on our devicelab is having the "Software Update" dialog which interferes with our performance tests. The following screenshot is taken from flutter-devicelab-mac-2. Someone has to physically touch the iPhone screen to make that dialog go away.

![Screen Sharing Picture June 14, 2020 at 8 44 15 AM PDT](https://user-images.githubusercontent.com/22987568/84597852-7f38cb80-ae1b-11ea-8937-b60aebf7e335.png)

**Comment by godofredoc** [comment]
There is an automated test that can be run to dismiss the system dialogs. @digiter can you please share the link to the docs?

**Comment by digiter** [comment]
Please check out this doc: https://g3doc.corp.google.com/company/teams/flutter/devicelab/macos_host.md#attached-ios-device

**Comment by liyuqian** [comment]
@digiter : https://github.com/digiter/infra-dialog seems to require iOS 13 while  flutter-devicelab-mac-2 only has iOS 11 so I couldn't use it to close the dialog... Did I miss something?

**Comment by digiter** [comment]
Discussed offline, we can use the older Xcode on mac-2 to recreate the trivial XCUITest in https://github.com/digiter/infra-dialog.

**Comment by liyuqian** [comment]
The dialog has been closed using Tong's XCUITest. Let's see if the number will go down.

**Comment by liyuqian** [comment]
I feel that the chance of having red bars has reduced since July 10th when I closed the dialog on mac-2. Perhaps there are other iPhones in the device lab with the update dialog that are making some red bars. @digiter : what's the best way to sweep through all the iPhones and close all update dialogs?

**Comment by kf6gpe** [comment]
I'm closing this bug based on #54792, because the original regression seems not to be a real regression, and we have a way to close iOS system bugs now, and the desire to have a tool for bisection is followed in #62504. Feel free to reopen if I'm missing something.
