### ISSUE TITLE
Unplugging my phone does not kill `flutter run`

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5825]
I'm not sure, but I thought `flutter run` was resident as long as it was connected to an app on the phone.

If I unplug my phone, `flutter run --release` continues to sit there and be resident.

What is the lifecycle intention of `flutter run` and `flutter run --release` and its relationship to the app on the phone?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
@danrubel can you take a look?

**Comment by sethladd** [comment]
This is probably related to https://github.com/flutter/flutter/issues/5448 and https://github.com/flutter/flutter/issues/5185 and https://github.com/flutter/flutter/issues/4508 and https://github.com/flutter/flutter/issues/4497 and https://github.com/flutter/flutter/issues/4165

That is, looks like we might want to define some new semantics for the commands in our tools. :)

cc @mit-mit something you want to take a crack at?

**Comment by danrubel** [comment]
I tried `flutter run` with Android, with iOS, and with the simulator. If I unplugged the device or quit the simulator, the `flutter run` command properly terminated in each situation.

Can you give me more details on how I can repro this situation?
Were there exceptions?

**Comment by sethladd** [comment]
Try `flutter run --release`.

Apologies, I wasn't specific in the original description. Will update.

**Comment by danrubel** [comment]
Yes, apparently the `--release` flag changes the behavior.
