### ISSUE TITLE
DatePicker custom theme is not working after the latest update

### ISSUE THREAD

**Issue by PramodJoshi** [flutter/flutter#58254]
Date picker dialog theme color set to default blue color after the latest update. Code below for custom color was working fine until the update. Is this a bug? If not, i would appreciate any help on this.

```dart
return Theme(
          data: ThemeData.light().copyWith(
            primaryColor: THEME_COLOR, //Head background
            accentColor: THEME_COLOR, //Selection color
            dialogBackgroundColor: Colors.white, //Background color
          ),
          child: child,
        );
```

**Complete runnable to test:**

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.red,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Test',
            ),
            FlatButton(
                child: Text('Date picker', style: TextStyle(color: Colors.white)),
                color: Colors.red,
                onPressed: () {
                  selectDate(context);
                })
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<Null> selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2015, 8),
      lastDate: DateTime(2101),
      builder: (BuildContext context, Widget child) {
        return Theme(
          data: ThemeData.light().copyWith(
            primaryColor: Colors.red, //Head background
            accentColor: Colors.red, //selection color
            dialogBackgroundColor: Colors.white, //Background color
          ),
          child: child,
        );
      },
    );
  }
}
```

**Expected result (before update):**

<img width="305" alt="Screenshot_2020-05-07-15-46-07" src="https://user-images.githubusercontent.com/17320471/83284226-11956a00-a1a2-11ea-9690-a04b54c21261.png">

**Current result (after update):**

<img width="305" alt="Screen Shot 2020-05-29 at 11 28 17 AM" src="https://user-images.githubusercontent.com/17320471/83284340-283bc100-a1a2-11ea-87fe-116ff9cb82fa.png">

**Flutter doctor:**

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.17.1 at /Users/user/Applications/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by jason-simmons** [comment]
The date picker was recently redesigned (https://github.com/flutter/flutter/commit/142b526f1bbd1c9fb3a09bb2e79594184c0d031a)

@darrenaustin

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.214, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.214 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1d395c5e18 (19 hours ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
Thanks for the report. We updated the date picker to the latest Material Design which specified colors based on `ThemeData.colorScheme`. This is part of the effort to clean up the theme system and have widgets base everything on the color scheme (see [Theme System Updates](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.pub7jnop54q0) for more information on this). Specifically the header background color is taken from `ThemeData.colorScheme.primary`.

Sorry if this is caused you issues. There are a couple of ways to fix this, but they all boil down to providing a `ColorScheme` with the colors you want. in your example you can change the theme to:

```dart
builder: (BuildContext context, Widget child) {
  return Theme(
    data: ThemeData.light().copyWith(
      colorScheme: ColorScheme.light().copyWith(
        primary: Colors.red,
      ),
    ),
    child: child,
  );
}
```

You could also just use the `primarySwatch` param of the `ThemeData` constructor (like you did for the app's theme in the your example. That will also create a `ColorScheme` with the swatch color as primary.

**Comment by PramodJoshi** [comment]
@darrenaustin That worked! Thank you and everyone else for the quick responses. Keep up the great work.

**Comment by fluttercorner** [comment]
[How To Use Date Picker in Flutter](https://fluttercorner.com/how-to-use-date-picker-in-flutter/)

**Comment by 19it038-Shruti** [comment]
thank youu

**Comment by 19it038-Shruti** [comment]
That really helped me out. Thanks!

**Comment by SanthoshiSrimanthula9999** [comment]
Thanks it's worked for me.
