### ISSUE TITLE
Web - Pointer Hover Error

### ISSUE THREAD

**Issue by thesmartrenovation** [flutter/flutter#58260]
Hi, I'm using the following code to display the cursor in my web flutter applications:

```
extension HoverExtensions on Widget {
  // Get a regerence to the body of the view
  static final appContainer = html.window.document.getElementById('app-container');

  Widget get showCursorOnHover {
    return MouseRegion(
      child: this,
      // When the mouse enters the widget set the cursor to pointer
      onHover: (event) {
        appContainer.style.cursor = 'pointer';
      },
      // When it exits set it back to default
      onExit: (event) {
        appContainer.style.cursor = 'default';
      },
    );
  }
}
```

In previous versions it was displayed correctly using the following modifier in the widget:

`placeHolder(4).showCursorOnHover,`

Just like that: https://ibb.co/z6VzJLV

But in the last version in the master channel the pointer is not seen: https://ibb.co/dbhVxnS

Interestingly enough, you can only see it when used in a Raised Button Widget, in any other Widget it doesn't work. It used to work on any Widget.

See: https://ibb.co/RgkTkSB

```
Flutter Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-2.0.pre.195, on Microsoft Windows [VersiÃ³n 10.0.18363.836], locale es-CO)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by kunit1** [comment]
Latest version of flutter web on master has built in mouse pointer shape support, use that instead of the workaround above.

**Comment by thesmartrenovation** [comment]
> Latest version of flutter web on master has built in mouse pointer shape support, use that instead of the workaround above.

Can you be a little more specific about how I should implement it? I would appreciate it very much.

**Comment by kunit1** [comment]
Certain Widgets have a default mouse cursor defined such as buttons. Others have allow you to define your own. If you are building something custom and you want to control the mouse cursor you can do as follows:
```
MouseRegion(
          cursor: SystemMouseCursors.click,
          child: Container(
            height: 30,
            width: 30,
            color: Colors.red,
          ),
        ),
```
So in the above example you want the pointer to be the click finger shape when over the container. You can also use InkWell (instead of Mouse region) or a few other Widgets that had MouseCursor added as a property. Not all Mouse Cursor shapes are supported yet but the common ones are implemented. Hope that helps.

**Comment by thesmartrenovation** [comment]
> Certain Widgets have a default mouse cursor defined such as buttons. Others allow you to define your own. If you are building something custom and you want to control the mouse cursor you can do as follows:
> 
> ```
> MouseRegion(
>           cursor: SystemMouseCursors.click,
>           child: Container(
>             height: 30,
>             width: 30,
>             color: Colors.red,
>           ),
>         ),
> ```
> 
> So in the above example you want the pointer to be the click finger shape when over the container. You can also use InkWell (instead of Mouse region) or a few other Widgets that had MouseCursor added as a property. Not all Mouse Cursor shapes are supported yet but the common ones are implemented. Hope that helps.

My friend, thank you so much for your help. It's working perfectly as you say.

**Comment by arualana** [comment]
@thesmartrenovation which library to import for `SystemMouseCursors`
