### ISSUE TITLE
[l10n] fatal error when template-arb-file has multiple underscores

### ISSUE THREAD

**Issue by miguelcmedeiros** [flutter/flutter#58271]
## Steps to Reproduce

When the template-arb-file is something like `template_name_en.arb`, then an exception is thrown during build and the localisation class is not (re-)generated.

**Expected results:** 
Build succeeds and localisation class is generated

**Actual results:** 
```
fatal: Arb file for a fallback, name, does not exist, even though 
the following locale(s) exist: [name_en]. 
When locales specify a script code or country code, a 
base locale (without the script code or country code) should 
exist as the fallback. Please create a {fileName}_name.arb 
file.

Exception
```

<details>
  <summary>Logs</summary>

```
 % flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-2.0.pre.197, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.19.0-2.0.pre.197 at /Users/user/IdeaProjects/hue_blue/dev/flutter
    • Framework revision d9144bf8fc (2 hours ago), 2020-05-29 11:55:02 -0700
    • Engine revision c19459ab7d
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Platform android-R, build-tools 29.0.0-rc3
    • ANDROID_HOME = /Users/user/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.4 19E287

• No issues found!
```

</details>

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
This results from the tool's inference of the locale. It gets tricky writing logic that reads the filename. Currently, we just read everything that comes after the first underscore. This helps us grab everything including the language, country and script codes in situations like `app_en.arb` and `app_en_US.arb`, or `app_zh_Hant_TW`. 

However, as you can tell from running into this bug, that any filename with additional underscores as part of the arb file name becomes problematic (ie. `app_name_en.arb`). One immediate solution would be to replace the underscores with a dash `-`. Even spaces seem to work fine.

I'll try to see if there's a way to parse the filename in a more clever fashion.

**Comment by shihaohong** [comment]
Another issue is that this error is misleading, since it is currently assuming that `name` is a locale and `en` is the language or script code for the locale `name`. If we aren't able to fix the issue, we need to at least capture this error more gracefully. 

In the meantime, we should probably add something to the user guide to telling users to avoid having underscores in their arb filenames.
