### ISSUE TITLE
Mac Host Engine is flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58270]
It seems that "Mac Host Engine" becomes flaky for about a week.

ere's an example failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8879443466262624256/+/steps/Host_Tests_for_host_profile/0/stdout

First failure was spotted on Thu May 21 04:38:37 2020: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/5336

**Comment by liyuqian** [comment]
CC @chinmaygarde @dnfield @xster @cbracken @godofredoc

**Comment by godofredoc** [comment]
I noticed this happens when we run release branch builders. We need to add some logic to clobber cache before and after the run.

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/58516
