### ISSUE TITLE
Create a new kind of FlutterView that takes an ImageReader

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#58289]
This will be subtype of `android.view.View`. It takes an  instance of https://developer.android.com/reference/android/media/ImageReader in its constructor.  It overrides the `onDraw(Canvas canvas)`.  See go/flutter-android-sync for reference.

This view provides a `void acquireLatestImage()` method, which collects the latest image from the `ImageReader` and invalidates the view.  In `onDraw`, it draws the bitmap.

If API level >= 29.  Then it collects the hardware buffer from latest image. Otherwise, it gets the planes from the latest image and re-wires the texture into the `android.graphics.Bitmap`.

Example branch: https://github.com/blasten/engine/tree/hybrid

**Comment by blasten** [comment]
cc @bparrishMines

**Comment by NoamDev** [comment]
How are you going to get a surface from the platform view?

**Comment by blasten** [comment]
> How are you going to get a surface from the platform view?

There's no need to get a surface from a platform view. The surface is from this new View, which renders the Flutter UI.

**Comment by NoamDev** [comment]
But how do you create the ImageReader?

**Comment by blasten** [comment]
```java 
reader = ImageReader.newInstance(
      getWidth(),
      getHeight(),
      PixelFormat.RGBA_8888,
      2,
      android.hardware.HardwareBuffer.USAGE_GPU_SAMPLED_IMAGE | android.hardware.HardwareBuffer.USAGE_GPU_COLOR_OUTPUT);

// new FlutterImageView(context, reader);
// reader.getSurface()
```

**Comment by NoamDev** [comment]
Ok, but suppose you want to associate a view with this ImageReader, as part
of a platform view. Say, a TextView for simplicity.
How are you going to make sure that the textView will draw itself on this
ImageReader/Surface/kind of FlutterView?
Using a virtual display?
