### ISSUE TITLE
Methods must have an explicit list of parameters

### ISSUE THREAD

**Issue by CPstudy** [flutter/flutter#58287]
When using generic types like `List<T>`, `Future<T>`, these occur error:

> Methods must have an explicit list of parameters.
> Try adding a parameter list.

![스크린샷 2020-05-30 오전 1 41 38](https://user-images.githubusercontent.com/3941131/83315825-782b8e00-a25d-11ea-8cb3-76c9827d15d9.png)

Restarting Android Studio works fine, but when I try to use the generic type I get an error again.

I tried:

> - Upgrade Flutter
> - Upgrade Android Studio
> - Invalidate Cache/Restart
> - flutter clean
> - remove `/.dartServer/.analysis_drive`

flutter doctor:
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
```

**Comment by InitAlpha** [comment]
the same here

**Comment by ImKeon** [comment]
the same here..

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by hawkbee1** [comment]
switching from master channel to beta channel solved the issue for me : 

Have this issue on master channel 
```
Flutter 1.19.0-2.0.pre.214 • channel master • git@github.com:flutter/flutter.git
Framework • revision 1d395c5e18 (il y a 23 heures) • 2020-05-31 07:41:50 -0700
Engine • revision 923687f0e7
Tools • Dart 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)
```

Don't have the issue on beta channel
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/rbarbe/programes/flutter
    • Framework revision 2738a1148b (il y a 3 semaines), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)
```

**Comment by ImKeon** [comment]
> flutter doctor -v

[✓] Flutter (Channel unknown, v1.16.3, on Mac OS X 10.15.4 19E287, locale ko-KR)
    • Flutter version 1.16.3 at /Users/keonhwan/Library/flutter
    • Framework revision be3a4b37b3 (10주 전), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/keonhwan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by ImKeon** [comment]
I fix this issue
I tried 

- change flutter channel to stable and flutter update 

I'm really appreciated for your help! 
have a nice day :)

**Comment by ImKeon** [comment]
I tried 

- change flutter channel to stable and flutter update 

and i can fix it!
thank you and have a nice day :)

**Comment by aerosasi** [comment]
Thank

> I tried
> 
> * change flutter channel to stable and flutter update
> 
> and i can fix it!
> thank you and have a nice day :)

Thanks mate you saved me. This worked !!

**Comment by TahaTesser** [comment]
Hi @CPstudy 
This seems to be fixed in latest `Channel master, 1.19.0-4.0.pre.73 `
 If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by tmekfouldji** [comment]
Flutter upgrade worked for me as well in stable channel

**Comment by CPstudy** [comment]
Thank, I solved!

> change flutter channel to stable and flutter update

**Comment by Nailer** [comment]
This is still happening to me:

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.3 19D76, locale en-NO)
    • Flutter version 1.17.3 at /Users/[redacted]/projects/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/[redacted]/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by NullByte08** [comment]
No it didnt resolve the issue for me. I changed to stable channel and ran flutter upgrade. The issue still persists.

**Comment by TahaTesser** [comment]
@NullByte08 
Please try it on `dev` or `master` channel 
Thankyou

**Comment by chooito** [comment]
same for me, just changed to master channel and updated solved it.
thankyou

**Comment by mikeRozen** [comment]
Flutter upgrade on the stable channel solved the issue. (I am wondering what would I do if it doesn't? )

**Comment by ashoktallapelli** [comment]
> I fix this issue
> I tried
> 
> * change flutter channel to stable and flutter update
> 
> Thanks

**Comment by AntonLT** [comment]
If you have the problem try to reload dart analysis in your project
It helped me

**Comment by JasonHarambe** [comment]
flutter channel stable
flutter upgrade

**Comment by EmreKabali** [comment]
hi,

I executed commands ,
flutter channel stable
flutter upgrade

and I restarted VS code.
It helped me 
Thanks

**Comment by danallen88** [comment]
Appears to be broken in 1.26.0-1.0.pre.  I am forced to use the dev channel because Android Studio 4.1 is not compatible with the current stable channel due to this issue: https://github.com/flutter/flutter/issues/67986

`flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-US)
    • Flutter version 1.26.0-1.0.pre at /Users/dallen/dev/flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dallen/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/dallen/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • EE8071D5-EEB7-4079-9A97-27C225371E41
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!`

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by saaalik** [comment]
Facing th same issue here

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.746], locale en-IN)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (12 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Salik\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Salik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.41
```

**Comment by surenTheGreat** [comment]
I had a similar issue and I resolved it using getter method
