### ISSUE TITLE
Dynamic switch between FlutterSurfaceView/FlutterTextureView and FlutterImageView

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#58291]
This is a mechanism to switch to the `FlutterImageView` view if a platform view is involved in the current frame.  We will know if a platform view is involved if `onDisplayPlatformView` is called https://github.com/flutter/flutter/issues/58288, so that will be the place to kick off the switch.

**Comment by chinmaygarde** [comment]
This is one of a family of issue related to hybrid composition. The relevant patches have landed or are under review. @jason-simmons believes the work items are adequately reflected in the bug tracking system.
