### ISSUE TITLE
Dynamically run the rasterizer on platform thread on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#58292]
On Android, if a platform view is involved in the current frame, we need to run the rasterizer task runner in the platform thread. This is required to synchronize the Flutter UI to the Android view system.  iOS already does this, so the same approach can be used.

**Comment by t-artikov** [comment]
Hi!
Could it be an optional feature?
In some cases, synchronization is not required, but it can lead to poor performance.
Android itself does not use the UI thread for rendering, it has the separate RenderThread.

**Comment by blasten** [comment]
This is an optional feature. It shouldn't impact performance unless you explicitly opt in by using a plugin that uses this feature, and even then it automatically merges/unmerges the task runners when needed.
