### ISSUE TITLE
Android Studio's Flutter plugin can't find cocoapods, while terminal does

### ISSUE THREAD

**Issue by saidlp** [flutter/flutter#58297]
Hi!
there's been quite a bit written about Flutter not finding cocoapods already, but I didn't find anything on that specific problem:
When running Flutter doctor via Android Studio's Tools/Flutter/Flutter Doctor menu, the plugin complains that it can't find cocoapods, but when running "flutter doctor -v" directly via the terminal (in the same project directory), everything works as a charm...

Flutter doctor via Android Studio's Tools/Flutter/Flutter Doctor menu:
<img width="983" alt="Screenshot 2020-05-30 at 08 40 47" src="https://user-images.githubusercontent.com/9481856/83321642-46142f00-a251-11ea-9496-6e934828b8de.png">

"flutter doctor -v" directly via the terminal:
<img width="697" alt="Screenshot 2020-05-30 at 08 41 31" src="https://user-images.githubusercontent.com/9481856/83321648-5f1ce000-a251-11ea-8afc-215214e26d4f.png">

Any idea about what's going wrong here?

Best regards

**Comment by saidlp** [comment]
Well, it seems like the problem was that XCode and was using a different ruby version than the one used to install the pods. What I did to fix it was:
- install rvm to manage ruby versions
- then, as described in https://stackoverflow.com/q/15474902, I added the following lines to the Podfile file located inside my flutter project, in sub directory ios:
`source "$HOME/.rvm/scripts/rvm"
rvm use .
`
- restarted Android studio
- Flutter doctor  from Android's Studio Tools/Flutter/Flutter doctor finally ran errorless!

I tried to run the project in the emulator, and got some error messages due to the two lines I added in the Podfile file. Commented the lines out. And then my project did run fine.
Weird I had to comment this out to make it work, but it works, so I'll just leave it in peace for now!

**Comment by khun84** [comment]
@saidlp the one suggested by you doesnt work for me...i get an repo not found error. I ended up putting the similar code in the flutter executable file. Seems bad to change the flutter executable file, but that's my workaround for now until I can make it work using your fix.

```bash
# in flutter/sdk/bin/flutter

source "$HOME/.rvm/scripts/rvm" 
# Im have to use ruby 2.6 for all my flutter projects
rvm use 2.6.0
```
