### ISSUE TITLE
Simplify Firebase, Google login API

### ISSUE THREAD

**Issue by aasirmutwalli22** [flutter/flutter#58304]
It will be very easy if there is a solution for single firebase or google login api configuration on flutter, instead of separate configurations for each platform (like. android, ios, web)

**Comment by TahaTesser** [comment]
Hi @aasirmutwalli22 
Each platform has its own requirement and needs the setup to be done separately, I am not sure this would be possible.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you"
