### ISSUE TITLE
If I run or with "flutter run --verbose" command it's not showing anything. just my screen gets freezed

### ISSUE THREAD

**Issue by ShohidulProgrammer** [flutter/flutter#58307]
with flutter version 1.17.1, If I run or with "flutter run --verbose" command it's not showing anything. just my screen gets freeze.

**Comment by TahaTesser** [comment]
Hi @ShohidulProgrammer 
Can you please provide your `flutter doctor -v`?  Do you mean computer screen or mobile screen? 
Thank you

**Comment by ShohidulProgrammer** [comment]
Can't provide "flutter doctor -v" output coze my computer fully hang or freezed

**Comment by TahaTesser** [comment]
Hi @ShohidulProgrammer 
The problem might depend from your device, for the issue to be workable requires some information, closing the issue for now;
please comment with your flutter doctor -v and flutter run -v and I will reopen it
Thank you for understanding
