### ISSUE TITLE
video path contains  chinese charators

### ISSUE THREAD

**Issue by yizhangxyz** [flutter/flutter#58306]
if video path contains  chinese charators，the video controller will be initialize failed。

**Comment by yizhangxyz** [comment]
如果video路径包含中文，那么video controller初始化失败

**Comment by TahaTesser** [comment]
Hi @yizhangxyz 
Using official [example](https://pub.dev/packages/video_player#-example-tab-) with video path folder with chinese character. is very wroking

```
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/视频/Butterfly-209.mp4');

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize().then((_) => setState(() {}));
    _controller.play();
  }

  @overri
```

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
