### ISSUE TITLE
dart.exe from Flutter SDK is flagged as Malware by anti-virus program

### ISSUE THREAD

**Issue by abhidix** [flutter/flutter#58302]
Observed with flutter_windows_1.17.2-stable.zip
After extracting Flutter SDK and typing 'flutter doctor' on command prompt, dart.exe from path 'flutter\bin\cache\dart-sdk\bin' gets deleted and anti-virus software pops-up a message stating the file is recognized as malware and either gets deleted or quarantined.

Workaround:
Download latest Dart SDK from https://dart.dev/tools/sdk/archive. (I used 2.8.3 x64)
Extract it and replace the dart-sdk folder in flutter SDK location 'flutter\bin\cache'

Now running 'flutter doctor' executes properly and validates system. With files from Dart SDK repository there are no anti-virus warnings

**Comment by TahaTesser** [comment]
Hi @abhidix 
Can you please provide your `flutter doctor -v`? Which anti-virus program you're using?
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens and the output of `flutter doctor -v` please.

**Comment by selvakumardreams** [comment]
Cisco AMP for EndPoints, same issue getting Quarantined everytime. 
Detection Name:
W32.MAP.Ransomware.rwd
