### ISSUE TITLE
Investigate patching dart-lang/http to be Flutter compatible.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#5831]
Since we are deprecating the Mojo networking stack in Flutter, users will have to rely on `dart:io` directly. It [has been reported](https://github.com/flutter/flutter/issues/5668#issuecomment-246511855) that `dart:io` is quite a bit more low level than necessary for common use cases. [`dart-lang/http`](https://github.com/dart-lang/http) is a suitable wrapper around `dart:io` but is not compatible with Flutter because of its use of mirrors.

We should investigate strategies to make `dart-lang/http` usable from Flutter. Either by providing patches to the canonical repo or forking the same.

**Comment by abarth** [comment]
In the meantime, we can just re-host `package:flutter/http.dart` on top of `dart:io`.  It's already a fork of `dart-lang/http` code, so we can probably borrow their `dart:io` backend.

**Comment by chinmaygarde** [comment]
> In the meantime, we can just re-host package:flutter/http.dart on top of dart:io. It's already a fork of dart-lang/http code, so we can probably borrow their dart:io backend.

sgtm as an interim solution.

**Comment by sethladd** [comment]
We might also want to update our copy of http. See https://github.com/flutter/flutter/issues/5370

**Comment by abarth** [comment]
How about this for a plan:

- [ ] Remove mojo-specific entry points to `package:flutter/http.dart`
- [ ] Re-host `package:flutter/http.dart` on `dart:io`
- [ ] Either remove `package:flutter/http.dart` in favor of `package:http/http.dart` or update `package:flutter/http.dart`.

**Comment by collinjackson** [comment]
Does our dart:io do HTTPS properly yet?

**Comment by abarth** [comment]
I believe it does.  We should check that first before trying to migrate to it.

**Comment by chinmaygarde** [comment]
I know it works on iOS. Pretty sure Android is fine too. Will follow up with the Dart ninjas if not.

**Comment by chinmaygarde** [comment]
I forked `dart-lang/http.dart` and got rid of its use of mirrors and use `dart:io` directly: https://github.com/chinmaygarde/flutter_http. Seems to work fine. Patching our use of accessing data from an image pipe now.

**Comment by chinmaygarde** [comment]
This is being tracked in https://github.com/dart-lang/http/issues/1. Closing.
