### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3289 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by anatasyapriscillia** [flutter/flutter#58311]
//Here is my login.dart
import 'package:emonito/views/login/forgotPass.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.green,
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: GestureDetector(
          child: Text("hahahahahahha"),
          onTap: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => ForgotPassword()),
            );
          },
        ),
      ),
    );
  }
}

//When i click the text, it should go to forgotPassword.dart

//Here is my forgotPassword.dart

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class ForgotPassword extends StatefulWidget{
  @override
  _ForgotPasswordState createState() => _ForgotPasswordState();
}

class _ForgotPasswordState extends State<ForgotPassword> {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.black,
    );
  }
}

//But when i click the text, an error occurred
//Here is the debug console

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3289 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      NavigatorState.push 
package:flutter/…/widgets/navigator.dart:3289
#3      Navigator.push 
package:flutter/…/widgets/navigator.dart:1737
#4      _LoginState.build.<anonymous closure> 
package:emonito/…/login/login.dart:20
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#6      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#075d7
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(237.4, 56.0)
    finalLocalPosition: Offset(217.4, 36.0)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

//Here is my flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale id-ID)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

//note: I use VSCode.

**Comment by scortumee** [comment]
Hi, @anatasyapriscillia. How did you resolve this issue?
