### ISSUE TITLE
Add Navigator.popUntilAndPush / Navigator.popUntilAndPushNamed

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#58310]
## Use case

Hello everyone. Sometimes it happens that when a procedure ends, you wanna keep popping until the starting element of the procedure to reset the context and clean eventual pop made by the users that could potentially take it back on the procedure pages, and maybe push after a result page, or open a details page containing the description of what the user has just done. This is especially common in apps that support payments, orders, or reservations.

I find this a lack of the navigator and it makes those kind of procedures really tricky to do.

## Proposal

Add two new methods:
- popUntilAndPush(context, popUntilRoute, routeToPush) that will push a route after popUntil is complete
- popUntilAndPushNamed(context, popUntilRoute, routeToPush) that will push a named route after popUntil is complete.

**Comment by Isakdl** [comment]
That already exists but with another method name

```
Navigator.pushNamedAndRemoveUntil(context, newRouteName, (route) => false)
Navigator.pushAndRemoveUntil(context, newRoute, (route) => false)
```

**Comment by nicolasvac** [comment]
Oh, ok. Arent the names a bit misleading?

**Comment by Isakdl** [comment]
Maybe, but not really,. You are pushing the new view and then removing the old routes in the background.

**Comment by goderbauer** [comment]
Closing since this already exists as pointed out above.
