### ISSUE TITLE
Flutter SDK can not be downloaded from Bangladesh

### ISSUE THREAD

**Issue by ShohidulProgrammer** [flutter/flutter#58317]
![image](https://user-images.githubusercontent.com/27086494/83329814-5a861500-a2ad-11ea-90c1-cba78cf501b6.png)

**Comment by iapicca** [comment]
Hi @ShohidulProgrammer 
I see there's an [issue](https://github.com/flutter/flutter/issues/48176#issuecomment-570890437) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
