### ISSUE TITLE
Google maps throwing Offset.& exception on ios on some devices

### ISSUE THREAD

**Issue by Isakdl** [flutter/flutter#58321]
## Steps to Reproduce

I have my app in production and I am unable to reproduce this bug on my own device, however I have users unable to use the application. So far this problem have only occurred on ios and I was able to convince a user to be invited to testflight and try to locate the source of the error. 

The users the get gray screen of death , ie there is an exception in the app. After some trial and error and implementing Catcher (https://pub.dev/packages/catcher), I managed to locate the bug down to the google_maps_flutter package and with this crash log:

<img width="573" alt="Screenshot 2020-05-30 at 17 46 08" src="https://user-images.githubusercontent.com/7395515/83332797-7b466e80-a29d-11ea-89d3-ce5fb8c0f51c.png">

This log keeps getting thrown as well which causes this screen to reopen over and over so the user could not send the actual crash report to me.

If I include this code I get the crash, if I return an empty Container() from the same class instead of the GoogleMap the crash does not happen. This issue does not effect all my users or my own devices, but it do happen from some and is reproducible every time. 
```
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:flutter/material.dart';

class Map extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
          buildingsEnabled: false,
          indoorViewEnabled: true,
          tiltGesturesEnabled: false,
          myLocationEnabled: true,
          myLocationButtonEnabled: false,
          zoomControlsEnabled: false,
          compassEnabled: false,
          mapToolbarEnabled: false,
          onCameraMoveStarted: () {
          },
          mapType: MapType.normal,
          initialCameraPosition: CameraPosition(
            target: LatLng(0, 0),
            zoom: 11.0,
          ),
          onMapCreated: (GoogleMapController controller) {
          },
        );
      
  }
}
```

Now this is a critical problem since it prevents my users from using the app and very hard to debug since I'm unable to reproduce it. I'm not sure if the problem is within the google_maps library or not but it does seem like it is. I would appreciate any ideas or input on this problem.

<details>
  <summary>Logs</summary>

```
> flutter doctor
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-SE)
    • Flutter version 1.17.1 at /Users/isak/development/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/isak/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by Isakdl** [comment]
After some more debugging, I'm no longer sure it actually is the google maps plugin , but related to shared_preferences package. It crashes if the shared_preferences is used. Found this issue that appears to be the same problem: https://github.com/flutter/flutter/issues/48171 

However the suggested workaround did not work for me.

**Comment by darshankawar** [comment]
@Isakdl 
Are you still facing this issue using [latest](https://pub.dev/packages/google_maps_flutter/install) plugin version ? The plugin has gone through lot of updates since this issue was filed, so I suggest to try with latest plugin version and see if issue still persists or not.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
