### ISSUE TITLE
How Can I fix Manifest merger failed  Error

### ISSUE THREAD

**Issue by hawx99x** [flutter/flutter#58320]
Hi,I'm currently developing a flutter application,When I try to run my application this error occurs..

 Attribute application@label value=(clean_hands) from AndroidManifest.xml:10:9-36
        is also present at [com.intentfilter:android-permissions:0.1.8] AndroidManifest.xml:11:18-50 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-29:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(clean_hands) from AndroidManifest.xml:10:9-36
        is also present at [com.intentfilter:android-permissions:0.1.8] AndroidManifest.xml:11:18-50 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-29:19 to override.

How can I fix this please help...

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
