### ISSUE TITLE
"flutter test" does not run "pub get"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#58339]
If you "flutter upgrade" across several months, then immediately run "flutter test", you'll find things break in inexplicable ways, because we don't run "pub get" and so you'll have the wrong version of package:test et al.

**Comment by jmagman** [comment]
Did https://github.com/flutter/flutter/pull/3310 regress?

**Comment by Hixie** [comment]
Doesn't look like it based on the code, but that PR had no test, so maybe. :-)

The other option is that we do run `pub`, but that `pub` doesn't notice that the SDK itself has changed, and so doesn't do anything.

cc @devoncarew

**Comment by jonahwilliams** [comment]
I think we fixed this with https://github.com/flutter/flutter/commit/d8b6fa153a1ba065cbd4584141cbe8cc1350dc43#diff-04c58bcf01db77bc3935c69a88c1f6b1R404 - the pub logic did not account for updates to the flutter SDK itself
