### ISSUE TITLE
incompatible types: MainActivity cannot be converted to FlutterEngine         GeneratedPluginRegistrant.registerWith(this);

### ISSUE THREAD

**Issue by RollerFernandez** [flutter/flutter#58347]
Hello friends I have the following problem can you help me please I am working platform channel  incompatible types: MainActivity cannot be converted to FlutterEngine
        GeneratedPluginRegistrant.registerWith(this); (editado)

**Comment by TahaTesser** [comment]
Hi @RollerFernandez 

Please use this 
```
class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

Thank you

**Comment by databeat-io** [comment]
> Hi @RollerFernandez
> 
> Please use this
> 
> ```
> class MainActivity: FlutterActivity() {
> 
>     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>         super.configureFlutterEngine(flutterEngine)
>         GeneratedPluginRegistrant.registerWith(flutterEngine)
>     }
> }
> ```
> 
> Thank you

Hi Taha Tesser. Thank you for the response. I have also been facing the same issue but this did not work and got this error. 

cannot find symbol
    protected void onCreate(flutterEngine FlutterEngine) {
                            ^
  symbol:   class flutterEngine
  location: class MainActivity

Your help is much appreciated. Please let me know if you need any additional information and I'll be happy to share.

**Comment by TahaTesser** [comment]
@databeat-io 

Not inside onCreate, override `configureFlutterEngine` 
See my code above

**Comment by BalanaguYashwanth** [comment]
Remove this in manifest file 
 <meta-data
            android:name="flutterEmbedding"
            android:value="2" />


and run the project it wil work

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by georgeraveen** [comment]
> Remove the below code in manifest file
> 
> **meta-data android:name="flutterEmbedding" android:value="2"**
> 
> and run the project it wil work

I too had the above problem and this solution worked for me. but I have a doubt, what are the side effects will occur future of removing such code?

**Comment by thongvo109** [comment]
> Hi @RollerFernandez
> 
> Please use this
> 
> ```
> class MainActivity: FlutterActivity() {
> 
>     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>         super.configureFlutterEngine(flutterEngine)
>         GeneratedPluginRegistrant.registerWith(flutterEngine)
>     }
> }
> ```
> 
> Thank you

How about .Java ?

**Comment by galloperx** [comment]
> Remove the below code in manifest file
> 
> **meta-data android:name="flutterEmbedding" android:value="2"**
> 
> and run the project it wil work

I had a problem that nothing seemed to solve, but removing those lines did.
Can someone explain - why? What role these lines play anyway, why put them there in the first place and how removing them fixes issues with being able to override onMethodCall in MainActivity.java? Even though the file is still red with "errors", but everything works (even "errors")? To give some context - I just wanted to run some native Java code for my Flutter app. Pity the official docs only have a clear example in Kotlin..

**Comment by chornbe** [comment]
The comments in the manifest clearly state to NOT delete that line as it's necessary to run the generated plug in registrant code. 

Replacing the main activity class mentioned above did a fantastic job of crashing the app even sooner than when I can do it by choice sending it a push notification in FCM. 

In my case, I'm convinced these issues are completely based on compatibility/version collisions in deeply recessed library dependencies, and that leaves me in quite a hole. I literally do not have enough years left on my life to investigate and mitigate all these dependencies in some repeatable, documentable, scientific method. I have no choice but to start over on this project, copy in all my flutter files, comment out a few thousand lines of code, start adding in the libraries, slowly uncover features, and hope I find the issue before my customer starts knocking on my door. 

Or, do the damned thing in native iOS code, and hire out an Android coder who won't flunky it together in React Native (seriously, are there any native android developers left any more????)

**Comment by galloperx** [comment]
> The comments in the manifest clearly state to NOT delete that line as it's necessary to run the generated plug in registrant code.

Yeah well, somehow the project safely compiled for production without those lines. Funny thing is that while Android Studio keeps saying that it does not know what "FlutterActivity" is (in MainActivity.java), it compiles and runs fine. I got everything set up correctly in the IDE, the PATH and so on.
It also does know where "import io.flutter.plugins.GeneratedPluginRegistrant" (not the S) leads, but at the same time shows "import io.flutter.plugin.common.MethodChannel" as error (but still as I said, while manifest has that "fix" it all compiles with no errors).

**Comment by zommerberg** [comment]
How would we fix this for Java?

**Comment by arunjithrs** [comment]
You can use **this.getFlutterEngine()**

```
public class MainActivity extends FlutterActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        GeneratedPluginRegistrant.registerWith(this.getFlutterEngine());
    }
}

```

**Comment by chazgps** [comment]
> You can use **this.getFlutterEngine()**
> 
> ```
> public class MainActivity extends FlutterActivity {
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
> 
>         GeneratedPluginRegistrant.registerWith(this.getFlutterEngine());
>     }
> }
> ```

This worked for me ! Thank you very much !

**Comment by jd-debug** [comment]
Then I'm just getting 
` error: cannot find symbol
        GeneratedPluginRegistrant.registerWith(this.getFlutterEngine());
                                                   ^
  symbol: method getFlutterEngine()`

**Comment by chornbe** [comment]
Yeah, good luck. I started from scratch, and it *seems* to be working, even when I transplant line for line code. There's something deep in the bowels of generated code, or there's some wacky version dependency I never found. This is my last Flutter project, at least for the next few years until this platform stabilizes. There's far too much still in flux, and far, far, FAR too many open source developers who never learned the cardinal rule of never breaking an API/interface, or about things like basic regression testing. It's the Wild West all over again, and I'm busy trying to actually create solutions on reasonable time lines. 

I've done three other native IOS projects in the time it's taken me to get this ONE flutter applications running solidly after recent updates. 

Shame; it had such promise. But no singular driving force leading things. 

Look for it on killedbygoogle.com soon, I guess. :\

**Comment by Tsagaanbayr1** [comment]
If anyone can't find the perfect solution, check the project migration changes:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by mwawrusch** [comment]
> Yeah, good luck. I started from scratch, and it _seems_ to be working, even when I transplant line for line code. There's something deep in the bowels of generated code, or there's some wacky version dependency I never found. This is my last Flutter project, at least for the next few years until this platform stabilizes. There's far too much still in flux, and far, far, FAR too many open source developers who never learned the cardinal rule of never breaking an API/interface, or about things like basic regression testing. It's the Wild West all over again, and I'm busy trying to actually create solutions on reasonable time lines.
> 
> Shame; it had such promise. But no singular driving force leading things.
> 
> Look for it on killedbygoogle.com soon, I guess. :\

Lost a week of work so far with incompatibilities between 1.20.x and 1.22.x and a diverse set of plugins. No quality control whatsoever. It's 2020 - automated testing on github is so easy.

**Comment by chornbe** [comment]
I repeat for the umpteenth time, if this we developers would pay for our tools (like we all used to) and this tool was making money for whomever (like the tools all used to) we would demand better, we would get better, and the publishers would have solid products with good following. 

I know... I know... this isn't the place for this editorializing, but I've been doing this a long time, and I've never been so frustrated in my ~35 year career as I am since "embracing" (read as: forced to) open source development tools and platforms. :\

**Comment by MananKaur** [comment]
> Then I'm just getting
> ` error: cannot find symbol GeneratedPluginRegistrant.registerWith(this.getFlutterEngine()); ^ symbol: method getFlutterEngine()`

Did you find a solution for this ?

**Comment by punithraj14** [comment]
I am facing the compatibility issue 
Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on

**Comment by punithraj14** [comment]
Then I'm just getting
error: cannot find symbol GeneratedPluginRegistrant.registerWith(this.getFlutterEngine()); ^ symbol: method getFlutterEngine()

Did you find a solution for this ?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pratikpwr** [comment]
> > Remove the below code in manifest file
> > **meta-data android:name="flutterEmbedding" android:value="2"**
> > and run the project it wil work
> 
> I too had the above problem and this solution worked for me. but I have a doubt, what are the side effects will occur future of removing such code?

If you want to convert the project to android embedding v2 this line is added so the code in MainActivity.java must change to support v2. If you remove this line your project will be of v1. so it will be depricated. don't remove it.

**Comment by cool-id** [comment]
> Then I'm just getting
> error: cannot find symbol GeneratedPluginRegistrant.registerWith(this.getFlutterEngine()); ^ symbol: method getFlutterEngine()
> 
> Did you find a solution for this ?

Yes, instead of overriding onCreate(Bundle savedInstanceState), please Override void configureFlutterEngine(@NonNull FlutterEngine flutterEngine).

Something like

```
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
```

**Comment by codeholic-anmol** [comment]
I did this

**Comment by ankit332000** [comment]
> Remove the below code in manifest file
> 
> **meta-data android:name="flutterEmbedding" android:value="2"**
> 
> and run the project it wil work

but what is the reason when we delete it the app runs and on terminal it shows u are on older version of flutter even when i have run the flutter upgrade after switching the channel..
