### ISSUE TITLE
Textfield's Autofocus doesn't let keyboard to be dismissed by Navigator

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#58341]
## Description
When I use `autofocus: true `in my Textfield with a combination of` Navigator.push(context, SlideDownRoute(topPage: this.widget, bottomPage: Page2()));` where the animations are in stack: the keyboard is not being dismissed on a new page.

Not even hiding the keyboard by using `FocusScope.of(context).unfocus();` before Navigation comes in helps. Once navigation starts it will show up the keyboard again.

## Steps to Reproduce

<details>
  <summary>Minimal sample code to reproduce the issue</summary>
main.dart:

```
import 'package:experiment18/page2.dart';
import 'package:flutter/material.dart';
import 'slide_down_route.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: FirstPage(),
    );
  }
}

class FirstPage extends StatefulWidget {
  @override
  _FirstPageState createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Page'),
      ),
      body: Center(
          child: TextField(
        autofocus: true,
        onChanged: (_) {
          Navigator.push(context, SlideDownRoute(topPage: this.widget, bottomPage: Page2()));
          //Navigator.push(context, MaterialPageRoute(builder: (context) => Page2()));
        },
      )),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
    );
  }
}

```

slide_down_route.dart:

```
import 'package:flutter/material.dart';

class SlideDownRoute extends PageRouteBuilder {
  final Widget topPage;
  final Widget bottomPage;
  SlideDownRoute({this.bottomPage, this.topPage})
      : super(
          pageBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
          ) =>
              topPage,
          transitionsBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            Widget child,
          ) =>
              Stack(
            children: <Widget>[
              SlideTransition(
                position: new Tween<Offset>(
                  begin: const Offset(0.0, 0.0),
                  end: const Offset(0.0, 0.0),
                ).animate(animation),
                child: bottomPage,
              ),
              SlideTransition(
                position: new Tween<Offset>(
                  begin: const Offset(0.0, 0.0),
                  end: const Offset(0.0, 1.0),
                ).animate(CurvedAnimation(parent: animation, curve: Curves.easeInQuint)),
                child: topPage,
              ),
            ],
          ),
        );
}

```
</details>

1. Run flutter sample code from above

**Expected results:** 
Expected the keyboard to be dismissed.
**Actual results:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25743901/83342389-e0728200-a2e6-11ea-9cca-62ece54d7507.gif)

## When does the keyboard gets dismissed?

1. When I don't use autofocus
2. When I use only a simple one animation

   - e.g. default Navigator.push(context, MaterialPageRoute(builder:(context) => Page2())); instead

   - or when I remove/comment out these lines from slide_down_route.dart:

```
SlideTransition(
                position: new Tween<Offset>(
                  begin: const Offset(0.0, 0.0),
                  end: const Offset(0.0, 1.0),
                ).animate(CurvedAnimation(parent: animation, curve: Curves.easeInQuint)),
                child: topPage,
              ),
```
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.209, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-2.0.pre.209 at /Users/tomas/Development/flutter
    • Framework revision 54524a7f95 (22 hours ago), 2020-05-29 23:43:01 -0400
    • Engine revision 685699b351
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone     • 00008020-000415840E50003A            • ios            • iOS 13.5
    • iPhone 11  • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
May be related to https://github.com/flutter/flutter/issues/48158

**Comment by chunhtai** [comment]
This is expected, when you push the slide down route, you create another textfield because you pass this.widget into the slide down route. That textfield is persist in the new route and is acquiring the focus due to autofocus.
If you want to make the first page slide down when pushing a new page, you should build you own PageRouteBuilder and build the slide down animation based on secondaryAnimation of the route. The secondaryAnimation is animating when a route is exiting the screen.

**Comment by tomasbaran** [comment]
@chunhtai  Why am I passing this.widget into the slide down route? I was aware of that but couldn't find anywhere in the code that I'd pass it. How can I prevent that?

But if I call `FocusScope.of(context).unfocus(); ` before the navigation happens, why does it pass the `autofocus:true` then?

**Comment by chunhtai** [comment]
I meant this line.
```dart
Navigator.push(context, SlideDownRoute(topPage: this.widget, bottomPage: Page2()));
```
According to the code, it seems like you want to use the topPage to build exiting animation. If that is the case, you can instead use a PageRouteBuilder for the First page that animate the sliding based on secondaryAnimation.

We use widget to create elements and states. Even though you use the same widget, the textfield in the first route and the second route has different states and elements, and they are independent to each other. If you unfocus the textfield in the first route, it will not affect the textfield in the second route

**Comment by tomasbaran** [comment]
Aaa, I got you @chunhtai Thanks a lot, now I know how to fix it: by passing `autofocus: false` in here:

`SlideDownRoute(topPage: PasscodeScreen(defaultAutofocus: false),bottomPage: MenuScreen()));`

I just initialized it in FirstPage() like this:

```
class FirstPage extends StatefulWidget {
  final bool defaultAutofocus;
  PasscodeScreen({this.defaultAutofocus = true});
```

And then in my wished TextField use `defaultAutofocus`

And now it works as I expected it to.
