### ISSUE TITLE
[PageTransitionsBuilder] ZoomPageTransition causing widget rebuild three times

### ISSUE THREAD

**Issue by AlexVincent525** [flutter/flutter#58345]
There's a reproducible demo, try it with https://dartpad.cn/fb30323847b7e0aee6c61bdbecacd060 . It happens on all platforms.

## Steps to Reproduce

1. Create a `PageRouteBuilder` with `_ZoomPageTransition`.
2. Add log to `build` method inside new page.
3. Log printed 3 times total.

**Expected results:** Build only once.

**Actual results:** `Widget` built 3 times.

<details>
  <summary>Logs</summary>

```
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.363
I/flutter ( 7614): State's hashCode: 48367006
I/flutter ( 7614): build: 2020-05-31 12:33:48.365
I/flutter ( 7614): built times: 0
I/flutter ( 7614): built times: 1
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.414
I/flutter ( 7614): State's hashCode: 48367006
I/flutter ( 7614): build: 2020-05-31 12:33:48.422
I/flutter ( 7614): built times: 1
I/flutter ( 7614): built times: 2
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.454
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.467
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.480
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.494
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.507
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.521
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.534
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.548
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.564
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.588
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.602
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.615
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.628
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.643
I/flutter ( 7614): build transition: 2020-05-31 12:33:48.660
I/flutter ( 7614): State's hashCode: 48367006
I/flutter ( 7614): build: 2020-05-31 12:33:48.664
I/flutter ( 7614): built times: 2
I/flutter ( 7614): built times: 3
```

</details>

flutter doctor
```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by shihaohong** [comment]
Hi @AlexVincent525, what sort of issues does this behavior cause for your application?

**Comment by AlexVincent525** [comment]
After a short investigation, I found this case would cause the rebuild.

https://github.com/flutter/flutter/blob/1d395c5e187370f2838bb043d3b438029b484bfc/packages/flutter/lib/src/material/page_transitions_theme.dart#L267

If comment it out the build situation looks fine, still don't know what happened. The sequence of the `Container`, `SlideTransition`, `FadeTransition` has no affect on this.

**Comment by AlexVincent525** [comment]
> Hi @AlexVincent525, what sort of issues does this behavior cause for your application?

Hi, I just wondering why it would cause three times of build?

**Comment by shihaohong** [comment]
@AlexVincent525 The rebuild is occurring because the widget tree is changing shape due to the changes in transition. Notice that the widget tree could be modified based on whether the animation is moving forwards, backwards, or was interrupted:

```
forward / interrupted:
Container -> FadeTransition -> ScaleTransition -> child

reverse:
ScaleTransition -> FadeTransition -> child

other:
child (no intermediate transition widgets)
```

The reshaping of the widget tree in this manner triggers a new build of the page.

**Comment by AlexVincent525** [comment]
So I guess the reason why the shape changed twice (as I debugged) because the condition `widget.animation.status == AnimationStatus.forward` and `_transitionWasInterrupted` using OR (`||`) makes the widget tree update? Here they cause the last two `build`s.

**Comment by shihaohong** [comment]
We solved this problem recently [in the animations package](https://github.com/flutter/packages/pull/160/files#diff-2f96f560fc675e902d6548fa008cbc2eR154) and can port it over here. What that does is it nests the forward and reverse transition widgets so that the widget tree contains both transitions simultaneously, so the framework doesn't trigger a rebuild since the tree shape never changes.

**Comment by AlexVincent525** [comment]
> We solved this problem recently [in the animations package](https://github.com/flutter/packages/pull/160/files#diff-2f96f560fc675e902d6548fa008cbc2eR154) using the new DualTransitionBuilder and can port it over here.

That sounds perfect! I'll try to implement it at the same time.

**Comment by AlexVincent525** [comment]
@shihaohong I updated the build method, but the color of the container seems strange when animate. Am I missing something?

![image](https://user-images.githubusercontent.com/15884415/83485635-06ac4380-a4da-11ea-85ff-c0988fd30a21.png)

And there's few questions: Is that okay for importing the `animations` package into flutter? If not, should this transition be moved to the animations package?

**Comment by shihaohong** [comment]
@AlexVincent525 

We shouldn't import the animations package into flutter. I think what we would do is create a copy of `DualTransitionsBuilder` in `flutter/flutter`, probably best in `flutter/packages/flutter/lib/src/widgets`.

Could you clarify what you mean by the color of the container looking strange?

**Comment by AlexVincent525** [comment]
> Could you clarify what you mean by the color of the container looking strange?

It seems the color was animated first, then the scale transition. They don't animate at the same time, that's different from the origin one. I'll record a screen record tomorrow, it's too late for now :D

**Comment by chunhtai** [comment]
We do have some excessive build in route transition, there is a pr to fix it https://github.com/flutter/flutter/pull/58202

**Comment by AlexVincent525** [comment]
> there is a pr to fix it #58202

@chunhtai I tested it just now and it seems no enhance for this issue. I marked the core implement in the screenshot below.

![image](https://user-images.githubusercontent.com/15884415/83587250-34989300-a581-11ea-8dca-266df0a74f3c.png)

**Comment by AlexVincent525** [comment]
@shihaohong The difference were told in the comparison below, it's exciting that it did reduce the number of builds.

| DualTransitionBuilder | AnimatedBuilder |
| --------------------- | ----------------- |
| ![Kapture 2020-06-03 at 10 06 54](https://user-images.githubusercontent.com/15884415/83587765-6c540a80-a582-11ea-96ca-ca10b7513c2c.gif) | ![Kapture 2020-06-03 at 10 08 46](https://user-images.githubusercontent.com/15884415/83587840-95749b00-a582-11ea-8ee4-92ed9e7d2c82.gif) |

**Comment by AlexVincent525** [comment]
I think it might related to compatibility when there're two `DualTransitionBuilder` using at the same time. Haven't got enough time into it, I'll try to make it looks normal in these days.

**Comment by AlexVincent525** [comment]
That's definitely related to `reverseBuilder`. Still debugging with the builder.

**Comment by AlexVincent525** [comment]
But that's very simillar with `FadeThroughTransition` [in the animations package](https://github.com/flutter/packages/blob/master/packages/animations/lib/src/fade_through_transition.dart). See if it can provides some ideas tomorrow.

**Comment by AlexVincent525** [comment]
Facing a related issue: #39938 . When implement the `_reverseEndScreenScaleTransition` it runs the animation reversely, rather than fade out fast.

https://github.com/flutter/flutter/blob/1d395c5e187370f2838bb043d3b438029b484bfc/packages/flutter/lib/src/material/page_transitions_theme.dart#L167-L178

**Comment by AlexVincent525** [comment]
Closing this because the PR has merged.

**Comment by AlexVincent525** [comment]
Re-open because the PR has been reverted.

Is there any clue in your investigation? @shihaohong

**Comment by shihaohong** [comment]
From the investigation, it seems like it might be a problem with the test itself, but we are still trying to figure out if it's a problem with the test or the implementation of the PR

**Comment by AlexVincent525** [comment]
Oh the one last thing I forgot is that I saw someone updates the AUTHORS file during the PR, does it required something to be in there? Should I update it too? I just found out that I already merged two PRs into flutter. :P

**Comment by shihaohong** [comment]
@AlexVincent525 It's not required, but it allows you to claim credit that you contributed to the Flutter repo! Feel free to add your credentials on there if you'd like to be acknowledged on there :)
