### ISSUE TITLE
Enable single widget for NavigationRail destinations

### ISSUE THREAD

**Issue by yamarkz** [flutter/flutter#58367]
I'm using NavigationRail and NavigationRailDestination widgets.
Current implement of NavigationRail is not able to set single widget at destinations attribute, but It should be able to set, in hopes.

code comment [here](https://github.com/flutter/flutter/blob/82eeb94045d22d358e1969d09b8b68835498137f/packages/flutter/lib/src/material/navigation_rail.dart#L108) .
```
The value of [destinations] must be a list of one or more [NavigationRailDestination] values.
```

and problem assert code [here](https://github.com/flutter/flutter/blob/82eeb94045d22d358e1969d09b8b68835498137f/packages/flutter/lib/src/material/navigation_rail.dart#L145).

```
assert(destinations != null && destinations.length >= 2),
```

I want to set single child widget of NavigationRailDestination in NavigationRail.

**Comment by yamarkz** [comment]
@clocksmith  Would you like to review a fix for this issue?

**Comment by BLumia** [comment]
I believe there are actual use-cases for single destination or no destination, my use-case is provided in https://github.com/flutter/flutter/issues/104913. I submitted a patch that removed the hard limit https://github.com/flutter/flutter/pull/104914. Please let me know if you need any additional information. Thanks!

**Comment by busslina** [comment]
Same issue here

**Comment by busslina** [comment]
I have this situation (Copy pasted from Discord):

In `go_router`, can `StatefulShellRoute.indexedStack` `branches` be dynamically generated from a list of items?

If yes, there is the problem that `branches` number should be `>=2`, so when I have a list of zero or one item it will crash.

Any suggestion?

**Comment by sionzee** [comment]
For those looking for a workaround, you can try something like this:

```dart
getDestinations() {
  final list = someDynamicData.map((e) {
    return NavigationRailDestination(
      icon: const Icon(Icons.computer),
      selectedIcon: const Icon(Icons.computer),
      label: Text(e.someLabel),
    );
  }).toList();

  if (list.length < 2) {
    for (int i = list.length; i < 2; i++) {
      list.add(NavigationRailDestination(
        icon: const Icon(Icons.not_interested, color: Colors.transparent,),
        disabled: true,
        label: const Text(''),
      ));
    }
  }

  return list;
}
```

**Comment by WieFel** [comment]
I have the use case that I have a navigation rail with several items in the default case.
But for a user with a specific role, items are hidden, and he ends up having just 1 visible item. Then, the navigation rail crashes.
