### ISSUE TITLE
[web] Starting CanvasKit from IDE

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#58360]
Is there any insurmountable reason why CanvasKit can't be started from the IDE (Android Studio, Visual Code), practically by specifying the same `--dart-define=FLUTTER_WEB_USE_SKIA=true` as with release? I know it can be enabled from the console using `k` but there might be quite a few of us who prefer to launch our debug app directly from the IDE we're working in and not the console (both because the console requires constant cd-ing between the folders and hot restarts require constantly switching windows). Besides, using `k` means starting the app twice, which is a small nuisance, anyway.

If it can be done in any way, even if it means switching permanently to CanvasKit for a specific installation of Flutter, please, allow us to do so.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/60708
