### ISSUE TITLE
Expose SkRuntimeEffect to allow custom SkSL shaders and color filters.

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#58361]
In Skia milestone 81 `SkRuntimeEffect` and friends have been added which would allow custom SkSL shaders and color filters. From the discussions in https://bugs.chromium.org/p/skia/issues/detail?id=10274 it seems like there is already some prototype work going on but I could not find a related Flutter issue. 

Related: https://github.com/flutter/flutter/issues/30763

/cc @liyuqian @dnfield @chinmaygarde 

## Use case

This would for example allow adding `ColorFilter.cube` from a plugin. (See https://github.com/flutter/flutter/issues/55738).

## Proposal

Expose `SkRuntimeEffect` to allow custom SkSL shaders and color filters.

## Status

The first steps of this proposal are finished. This issue will be considered done when the API is complete and it works on Web, to whatever extent is possible.
https://github.com/flutter/flutter/projects/207

**Comment by cbenhagen** [comment]
This is already being worked on by @chriscraws:
https://flutter.dev/go/shaders
https://github.com/chriscraws/engine/tree/shader
https://github.com/chriscraws/ssir

@chriscraws please feel free to edit and take over this issue as you see fit. The design doc you mention to be looking for examples. Maybe https://github.com/flutter/flutter/issues/55738 would be a good fit?

**Comment by chriscraws** [comment]
Thanks for filing this @cbenhagen! #55738 looks like a great fit, I hadn't considered supporting 3d textures in the initial design

**Comment by willlarche** [comment]
@cbenhagen could you post some info on what you'd use it for? Will be good for us to know what the needs are.

**Comment by cbenhagen** [comment]
@willlarche my primary goal is to apply 3D lookup tables to videos. This is why I filed https://github.com/flutter/flutter/issues/55738. It would be awesome if this could serve as an example usage of runtime effects.

**Comment by willlarche** [comment]
Thank you!

**Comment by tomasdev** [comment]
@cbenhagen do you have a ballpark estimate what would the performance be like?

i.e., when using CI Filters in iOS, the composition can be used on videos and streams (applying the LUT doesn't take more than 1/60th of a second)

**Comment by cbenhagen** [comment]
@tomasdev I am the wrong person to ask as I will not be able to implement this. But I would expect applying LUTs to be pretty fast actually. Maybe @chriscraws can comment on this?

**Comment by chriscraws** [comment]
Hey @tomasdev - I'm not an iOS developer so I'm not exactly sure how this will compare specifically to CoreImage, but I can say that applying the LUT *should* be performant within 1/60th of a second, or 1/120th of a second on iPad. For realistic expectations though, it may be some time before we support this particular use-case and can provide benchmarks, 3d texture lookup will come after basic shader support is in place (and the timeline has stretched a bit there)

**Comment by jaween** [comment]
I would like to mention my use-case for custom fragment shaders, which mainly falls under the category of "rasterization techniques" as mentioned in the [design doc](https://flutter.dev/go/shaders).

It's a drawing app which requires rasterization of curves and shapes according to specific algorithms (pixel art). Currently to achieve this I am relying on a mixture of using the FFI to allocate buffers and rasterize curves and shapes in C++, as well as more expensive rasterization being done in Canvas/Skia which gets copied to the CPU to be blitted onto the buffers (using `Picture.toImage`() and `Image.toByteData`). Finally I use the `dart:ui` function `decodeImageFromPixels()` and a `CustomPainter` to render it back to the screen.

It would be great to do all the rasterization directly in fragment shaders instead, and be passing around `Picture` instances.
This would allow me to:
 * avoid the FFI/native buffers
 * avoid copying buffers from Canvas/Skia into Dart/C++ land
 * create more complex rasterization effects (dithering patterns, custom gradients, etc, useful in pixel art)
 * increase the base resolution of user generated artwork (currently limited due to the performance of `decodeImageFromPixels` for larger buffer sizes)

**Comment by creativecreatorormaybenot** [comment]
Hi @chriscraws, really appreciate the work. I am wondering, will there be examples (maybe good enough docs are sufficient) for how tu implement custom fragment shaders when this hits `master`?

From what I can tell #82906 will make use of it and it will probably serve as a usage example, so that might be good enough.

**Comment by chriscraws** [comment]
> Hi @chriscraws, really appreciate the work. I am wondering, will there be examples (maybe good enough docs are sufficient) for how tu implement custom fragment shaders when this hits `master`?
> 
> 
> 
> From what I can tell #82906 will make use of it and it will probably serve as a usage example, so that might be good enough.

Yes, I'm hoping to add useful examples. Ideally we can help demonstrate how to achieve the use cases listed above as well. As this is a very low-level feature, I'd like to release a library on pub that contains higher level widgets and classes for working with shaders from Dart - this was the original main goal but we're focused on getting the engine changes landed for now.

**Comment by maks** [comment]
Sorry I'm quite new to this area, but can I ask will this work allow for something along the lines of what is described in [this article using Skia shaders from Kotlin and Compose](https://www.pushing-pixels.org/2021/09/22/skia-shaders-in-compose-desktop.html) , especially the dynamic shader demos shown there ?

**Comment by creativecreatorormaybenot** [comment]
@clocksmith Is there a write-up on how to work with FragmentShader?

**Comment by youssefali424** [comment]
is FragmentShader added to any version flutter or only on git? and can we try it currently ?

**Comment by clocksmith** [comment]
Yes

> @clocksmith Is there a write-up on how to work with FragmentShader?

Not yet but stay tuned.

**Comment by clocksmith** [comment]
> is FragmentShader added to any version flutter or only on git? and can we try it currently ?

Yes, it can be tested on anything that uses dart:ui, see comment above

**Comment by youssefali424** [comment]
> > is FragmentShader added to any version flutter or only on git? and can we try it currently ?
> 
> Yes, it can be tested on anything that uses dart:ui, see comment above

Maybe you didn't get what I mean, it is currently on master branch but if I want to recommend it to my team I need to know if it will be added to any flutter version soon? or if it is currently on the beta version?

**Comment by chriscraws** [comment]
Update for those following this thread: it should now be possible to try out making shaders that use floats and `ImageShader` objects as inputs. There are currently a myriad of restrictions on the SPIR-V you can use, but these shouldn't be a blocker to implementing the use cases listed above so far.

[Here is the current `dart:ui` API](https://github.com/flutter/engine/blob/e8e350c65678b0e9488ebdd71b8a52004cb7e10e/lib/ui/painting.dart#L3754), and [here](https://github.com/flutter/engine/blob/e8e350c65678b0e9488ebdd71b8a52004cb7e10e/lib/spirv/README.md) is some documentation on the current limitations with SPIR-V. 

More work down the road:

- Benchmarking, and creating usage examples
- Adding support for control-flow and structs
- Adding CanvasKit-renderer support
- Adding html-renderer support
- Removing the 'beta' qualifier

Thanks everyone for your patience on this :)

**Comment by creativecreatorormaybenot** [comment]
@chriscraws That is awesome news! 💯 Thanks so much for the efforts on this ❤️ 

One question about the restrictions on the supported SPIR-V: once we start working with it, should we create issues for every unsupported operation or how should we handle tracking of that?

**Comment by chriscraws** [comment]
Hey @creativecreatorormaybenot , we want the supported SPIR-V API surface to be as minimal as possible to unlock primary use-cases - the hope right now is that most users will not need to use the API directly but instead via higher-level widgets. So, to answer your question, I think first we'd want to make sure that the unsupported operations are necessary for your use-case. I've gone ahead and created a higher-level issue where we can triage:

https://github.com/flutter/flutter/issues/93800

In the meantime, if people have questions about using the API in its current state, I'm far more reachable on discord, where I am epicycle#8164 and a member of both the Flutter server and the /r/FlutterDev server.

**Comment by cbenhagen** [comment]
@chriscraws thank you so much for your work on shaders! Is it already possible to use them to implement a [ColorFilter.cube](https://github.com/flutter/flutter/issues/55738) ?

**Comment by cbenhagen** [comment]
Created a sub issue to track the creation of a ColorFilter: https://github.com/flutter/flutter/issues/94235.

**Comment by slightfoot** [comment]
@clocksmith are you actively working on this? if not shall we unassign you?

**Comment by fzyzcjy** [comment]
Is there any updates? In addition, will it be supported on Impeller in the future when Impeller is stable?
