### ISSUE TITLE
[video_player] [android ] error playing HLS

### ISSUE THREAD

**Issue by mrsalar** [flutter/flutter#58375]
Hi
this is my problem when open link in video_player and  i got this error.
my link video is correct becuase it play in exo player native android.
![image](https://user-images.githubusercontent.com/21360339/83357827-16197880-a384-11ea-94b5-842b546540b4.png)

**Comment by iapicca** [comment]
Hi @mrsalar 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

ios https://github.com/flutter/flutter/issues/48670

**Comment by mrsalar** [comment]
> Hi @mrsalar
> Can you please provide your `flutter doctor -v`,
> your `flutter run --verbose`,
> your `pubspec.yaml`
> and a minimal reproducible code sample.
> Thank you
> 
> ios #48670

Hi

**Comment by mrsalar** [comment]
Hi @iapicca 
this is doctor _v
![tool](https://user-images.githubusercontent.com/21360339/83475344-66d3c300-a4a3-11ea-923f-db35da030272.PNG)
these are --verbose
![4444](https://user-images.githubusercontent.com/21360339/83475881-85868980-a4a4-11ea-9634-26491a05952e.PNG)
![111](https://user-images.githubusercontent.com/21360339/83475883-87504d00-a4a4-11ea-98cb-6987830c8bab.PNG)
![222](https://user-images.githubusercontent.com/21360339/83475884-87e8e380-a4a4-11ea-86c6-1d31d8b78df8.PNG)
![333](https://user-images.githubusercontent.com/21360339/83475886-88817a00-a4a4-11ea-934f-450baf8f93be.PNG)
this is pubspec.yaml
![5555](https://user-images.githubusercontent.com/21360339/83475924-9f27d100-a4a4-11ea-906d-44fa94121a2f.PNG)

and this is my code

**Comment by TahaTesser** [comment]
Hi @mrsalar 
Can you please try this [solution](https://github.com/flutter/flutter/issues/52831#issuecomment-600846578)?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
