### ISSUE TITLE
Help I can't solve this problem

### ISSUE THREAD

**Issue by jacazjx** [flutter/flutter#58374]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jacazjx** [comment]
The following assertion was thrown during performLayout():
Leading widget consumes entire tile width. Please use a sized widget.
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1353 pos 7: 'tileWidth != leadingSize.width'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
When the exception was thrown, this was the stack: 
#2      _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1353:7)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
...
The following RenderObject was being processed when the exception was fired: _RenderListTile#55017 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(16.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=Infinity)
...  size: MISSING
RenderObject: _RenderListTile#55017 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(16.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=Infinity)
  size: MISSING
...  leading: RenderPositionedBox#afe50 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=48.0)
...    size: Size(328.0, 48.0)
...    alignment: center
...    textDirection: ltr
...    widthFactor: expand
...    heightFactor: expand
...    child: RenderSemanticsAnnotations#d6750 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(146.0, 6.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=48.0)
...      size: Size(36.0, 36.0)
...      child: RenderConstrainedBox#d4259 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=48.0)
...        size: Size(36.0, 36.0)
...        additionalConstraints: BoxConstraints(36.0<=w<=Infinity, 36.0<=h<=Infinity)
...        child: RenderCustomPaint#5f327 relayoutBoundary=up11 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(36.0<=w<=328.0, 36.0<=h<=48.0)
...          size: Size(36.0, 36.0)
...  title: RenderParagraph#e605f NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    textAlign: start
...    textDirection: ltr
...    softWrap: wrapping at box width
...    overflow: clip
...    locale: en_US
...    maxLines: unlimited
...    text: TextSpan
...      debugLabel: (((englishLike subhead 2014).merge(blackMountainView subtitle1)).copyWith).merge(unknown)
...      inherit: false
...      color: Color(0xff121917)
...      family: Roboto
...      size: 17.0
...      weight: 300
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "沈阳航空航天大学图书馆"
...  subtitle: RenderParagraph#52dd2 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    textAlign: start
...    textDirection: ltr
...    softWrap: wrapping at box width
...    overflow: clip
...    locale: en_US
...    maxLines: unlimited
...    text: TextSpan
...      debugLabel: ((englishLike body1 2014).merge((blackMountainView bodyText2).merge(unknown))).copyWith
...      inherit: false
...      color: Color(0x8a000000)
...      family: Roboto
...      size: 12.0
...      weight: 600
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "拥有0个房间"
...  trailing: RenderFlex#a456a relayoutBoundary=up8 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=328.0, 0.0<=h<=48.0)
...    size: Size(328.0, 22.0)
...    direction: horizontal
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    textDirection: ltr
...    verticalDirection: down
...    child 1: RenderParagraph#ac01d relayoutBoundary=up9 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=48.0)
...      size: Size(51.0, 22.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: ((englishLike body1 2014).merge((blackMountainView bodyText2).merge(unknown))).merge(unknown)
...        inherit: false
...        color: Color(0xff121917)
...        family: Roboto
...        size: 17.0
...        weight: 300
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "沈阳市"
...    child 2: RenderSemanticsAnnotations#10365 relayoutBoundary=up9 NEEDS-PAINT
...      parentData: offset=Offset(51.0, 1.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=48.0)
...      size: Size(20.0, 20.0)
...      child: RenderImage#a06c1 relayoutBoundary=up10 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=48.0)
...        size: Size(20.0, 20.0)
...        image: [200×200]
...        width: 20.0
...        height: 20.0
...        color: MaterialColor(primary value: Color(0xff2196f3))
...        alignment: centerRight
...        invertColors: false
...        filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: _RenderListTile#55017 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27698): done

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#e90bd relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#bef49 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPointerListener#ca7c0 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#66a31 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderMouseRegion#d752e relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#c54de relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///D:/Apps/enjoyspace/lib/views/org_details.dart:151:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Trailing widget consumes entire tile width. Please use a sized widget.
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1357 pos 7: 'tileWidth != trailingSize.width'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: _RenderListTile#55017 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#e90bd relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#bef49 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPointerListener#ca7c0 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#66a31 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderMouseRegion#d752e relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListTile file:///D:/Apps/enjoyspace/lib/views/org_details.dart:153:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#c54de relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///D:/Apps/enjoyspace/lib/views/org_details.dart:151:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 416, http://192.168.0.103:60121/enjoyspace/api/file/download/res_pic/intro_3_1

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:95:9)
<asynchronous suspension>
#1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:48:14)
#2      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
#3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22)
...
Image provider: NetworkImage("http://192.168.0.103:60121/enjoyspace/api/file/download/res_pic/intro_3_1", scale: 1.0)
Image key: NetworkImage("http://192.168.0.103:60121/enjoyspace/api/file/download/res_pic/intro_3_1", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
I/InputTransport(27698): Fun_filterMotionEvent reportMoveEvent!
W/HiTouch_PressGestureDetector(27698): Touch pointer move a lot. The moving distance of X is:7.0, limit is:60The moving distance of Y is:70.0, limit is:60

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderIndexedSemantics#a2c7c relayoutBoundary=up2 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'

**Comment by jacazjx** [comment]
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:enjoyspace/models/Infomation.dart';
import 'package:enjoyspace/utils/Api.dart';
import 'package:enjoyspace/utils/HttpUtil.dart';
import 'package:enjoyspace/utils/style.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_swiper/flutter_swiper.dart';

class OrgDetails extends StatefulWidget {
  final OrgInformation orgInformation;

  const OrgDetails({Key key, this.orgInformation}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _OrgDetails();
  }
}

class _OrgDetails extends State<OrgDetails> {
  ScrollController _controller;
  bool _visible = true;
  int intoPicNum = 1;
  List<ResourceInformation> _listRes = List();
  List<RoomInformation> _listRoom = List();
  List<ResourceInformation> _list = List();

  _getResList() async {
    FormData formData =
        FormData.fromMap({"orgId": widget.orgInformation.orgId});
    await HttpUtil.doAskForList(Api.DO_RES_LIST, formData).then((l) {
      l.forEach((element) {
        ResourceInformation resourceInformation =
            ResourceInformation.fromJson(element);
        print(resourceInformation.toJson());
        _list.add(resourceInformation);
      });
      setState(() {
        _listRes = _list;
      });
    });
  }

//  _getRoomList() async {
//    var l = await HttpUtil.doAskForList(
//        Api.DO_ROOM_LIST, {"type": "Org", "id": widget.orgInformation.orgId});
//    l.forEach((element) {
//      RoomInformation roomInformation = RoomInformation.fromJson(element);
//      _list.add(roomInformation);
//    });
//    setState(() {
//      _listRoom = _list;
//    });
//  }

  _getGridItem(index) {
    var gridItems = [
      Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Image.asset(
            "images/institution.png",
            width: 50,
            height: 50,
          ),
          Text(
            "下属${widget.orgInformation.orgRoomRes == true ? "房间" : "资源"}数量：${widget.orgInformation.orgNumRes}",
            style: AppText.middleText,
          )
        ],
      ),
      Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Image.asset(
            "images/orgtype/${widget.orgInformation.orgType}.png",
            width: 50,
            height: 50,
          ),
          Text(
            "机构类型：${widget.orgInformation.orgType}",
            style: AppText.middleText,
          )
        ],
      ),
    ];
    return gridItems[index];
  }

  listRoomItem(index) {
    return GestureDetector(
      child: Column(
        children: <Widget>[
          ListTile(),
          Divider(
            height: 1,
          )
        ],
      ),
    );
  }

  Future _downPic(directory, prefix, id) async {
    return Image.network(
      Api.DO_DOWNLOAD_FILE + "$directory/${prefix}_${id}_1",
      width: 50,
      height: 50,
      fit: BoxFit.fill,
    );
  }

  Widget _buildFuture(BuildContext context, AsyncSnapshot snapshot) {
    switch (snapshot.connectionState) {
      case ConnectionState.waiting:
        print('正在加载');
        return Center(
          child: CircularProgressIndicator(),
        );
      case ConnectionState.done:
        print('done');
        if (snapshot.hasError){
          print("下载出错${snapshot.error}");
          return Image.asset(
            "images/picture.png",
            width: 50,
            height: 50,
            fit: BoxFit.fill,
          );
        }
        return snapshot.data;
      default:
        return Image.asset(
          "images/picture.png",
          width: 50,
          height: 50,
          fit: BoxFit.fill,
        );
    }
  }

  listResItem(index) {
    return GestureDetector(
        child: Container(
          height: 80,
          child: Column(
            children: <Widget>[
              ListTile(
                leading: FutureBuilder(
                  builder: _buildFuture,
                  future: _downPic("res_pic", "intro", _listRes[index].resId),
                ),
                title: Text(
              _listRes[index].resName,
              style: AppText.middleText,
            ),
            subtitle: Text("拥有${_listRes[index].resNumRoom}个房间"),
            dense: true,
            trailing: Row(
              children: <Widget>[
                Text(
                  _listRes[index].resLocation,
                  style: AppText.middleText,
                ),
                Image.asset(
                  "images/location.png",
                  width: 20,
                  height: 20,
                  color: Colors.blue,
                  alignment: Alignment.centerRight,
                ),
              ],
            ),
          ),
          Divider(
            height: 1,
          )
        ],
      ),
    ));
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = ScrollController();
//    widget.orgInformation.orgRoomRes ? _getRoomList() : _getResList();
    _getResList();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
        body: CustomScrollView(
      controller: _controller,
      physics: BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
      slivers: <Widget>[
        SliverAppBar(
          pinned: true,
          expandedHeight: 200,
          flexibleSpace: FlexibleSpaceBar(
            title: Text(widget.orgInformation.orgName),
            background: Container(
              height: 200.0,
              child: Swiper(
                itemBuilder: (context, index) {
                  return Image.asset(
                    "images/lake.jpg",
                    fit: BoxFit.fitWidth,
                  );
                },
                itemCount: intoPicNum,
                controller: SwiperController(),
                autoplay: true,
              ),
            ),
          ),
        ),
        new SliverToBoxAdapter(
          child: new Container(
            padding: EdgeInsets.fromLTRB(5, 5, 5, 0),
            child: Text(
              "简介",
              style: AppText.xLargeText,
            ),
          ),
        ),
        new SliverToBoxAdapter(
          child: Container(
            padding: EdgeInsets.fromLTRB(5, 5, 5, 10),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(
                  widget.orgInformation.orgDscb == null
                      ? "该机构什么也没写..."
                      : widget.orgInformation.orgDscb,
                  style: AppText.middleText,
                )
              ],
            ),
          ),
        ),
        SliverGrid(
          gridDelegate:
              SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
          delegate:
              SliverChildBuilderDelegate((BuildContext context, int index) {
            return _getGridItem(index);
          }, childCount: 2, addAutomaticKeepAlives: true),
        ),
        new SliverToBoxAdapter(
          child:Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                padding: EdgeInsets.fromLTRB(5, 5, 5, 0),
                child: Text(
                  "资源列表",
                  style: AppText.xLargeText,
                ),
              ),
              Divider(
                height: 1,
              )
            ],
          )
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate((content, index) {
            return listResItem(index);
          }, childCount: _listRes.length),
        ),
      ],
    ));
  }
}

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
