### ISSUE TITLE
Flutter Doctor Issue

### ISSUE THREAD

**Issue by v1hhug0** [flutter/flutter#58384]
Flutter doctor can't find my IntelliJ IDEA Ultimate Edition version 2020.1.1. When I run the command, it doesn't show the app. It only shows my VS Code and  my Android Studio.

![image](https://user-images.githubusercontent.com/43619073/83361175-be174d80-a354-11ea-9cd6-6a336c54405f.png)

**Comment by anik786** [comment]
I don't think flutter doctor looks for `IntelliJ IDEA`, unless I am mistaken.

**Comment by iapicca** [comment]
Hi @v1hhug0 
I see there's an open [issue](https://github.com/flutter/flutter/issues/54867#issuecomment-623006370) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
