### ISSUE TITLE
showDatePicker with DatePickerEntryMode.input does not work for Dutch locale

### ISSUE THREAD

**Issue by ozgurmacit** [flutter/flutter#58387]
## Steps to Reproduce

1. Use `showDatePicker` with `locale: Localizations.localeOf(context)`.
2. Set the phone language to English.
3. When you enter input mode in calendar widget you will notice how it uses "/" to separate month, day and year. When you try to change the value, you again use "/" and "mm/dd/yyyy" format.
4. Set the phone language to Dutch.
5. When you enter input mode in calendar widget you will notice it is shown in "dd-mm-yyyy" format which is good. When you clear and try to change the value it does not allow to use "-" instead forces to use "/". Also expected format is hinted as "mm/dd/yyyy". As a result you get "Invalid Format" error whatever you do. Apart from the functional error it is weird to have "Enter Date" and "Invalid Format" in Dutch locale. In short, the widget does not work with Dutch locale. Sure needs to be tested for others too.
6. Alternatively you can change the locale of the `showDatePicker` function manually.

```
ozgur@Ozgurs-MacBook-Pro tenere-mobile % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale en-TR)
    • Flutter version 1.17.2 at /Users/ozgur/Library/flutter
    • Framework revision 5f21edf8b6 (3 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ozgur/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ozgur/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 20579390-A4F6-49CD-921E-11A8BEE07246 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
ozgur@Ozgurs-MacBook-Pro tenere-mobile % 
```

</details>

**Comment by iapicca** [comment]
Hi @ozgurmacit 
Can you please provide a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@ozgurmacit 
please follow up on https://github.com/flutter/flutter/issues/55535,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it

**Comment by ozgurmacit** [comment]
Note for readers: Correct. This is a duplicate.
