### ISSUE TITLE
dart-ui Rect class incorrectly calculates if it 'contains' and Offset

### ISSUE THREAD

**Issue by mpeccorini** [flutter/flutter#58388]
The **contains** method in the **Rect** class is implemented like this:
`return offset.dx >= left && offset.dx < right && offset.dy >= top && offset.dy < bottom;`
This would be correct assuming 0 in the vertical axis to be at the top. However, **Rect** places the highest of the two "y" values in the **top** member (at least this is the behavior when using fromLTRB), so the comparison fails.

**Comment by iapicca** [comment]
Hi @mpeccorini 
could you please provide a minimal code sample
where [Rect](https://api.flutter.dev/flutter/dart-ui/Rect-class.html) [contains method](https://api.flutter.dev/flutter/dart-ui/Rect/contains.html) fails
Thank you

**Comment by mpeccorini** [comment]
Hi @iapicca ,

  I hope this snippet helps:

`import 'dart:ui';

void main(){
  Rect rect1 = new Rect.fromLTRB(0,0,2,2);
  Rect rect2 = new Rect.fromLTRB(0,2,2,0);
  Offset offset = new Offset(1,1);
  if (rect1.contains(offset)){
    print('rect1 contains offset when top < bottom');
  } else {
    print('rect1 does not contain offset when top > bottom');
  }

  if (rect2.contains(offset)){
    print('rect2 contains offset when top > bottom');
  } else {
    print('rect2 does not contain offset when top > bottom');
  }
}
  `
As you will see, the [contains](https://api.flutter.dev/flutter/dart-ui/Rect/contains.html) method works only when top < bottom. This is, at least, counter intuitive, perhaps Rect should make sure the values are correctly placed even if you pass them inverted.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by jason-simmons** [comment]
The dart:ui `Rect` class matches the design of Skia's `SkRect` class.

A rectangle where `bottom <= top` is considered to be empty (see https://github.com/google/skia/blob/master/include/core/SkRect.h#L558 and https://github.com/google/skia/blob/master/include/core/SkRect.h#L676)

**Comment by goderbauer** [comment]
What jason said is also documented on the Flutter side: https://master-api.flutter.dev/flutter/dart-ui/Rect/isEmpty.html

Since we are not likely to change this definition, I am going to close this issue.
