### ISSUE TITLE
Is web support planned for the webview plugin?

### ISSUE THREAD

**Issue by timosturm** [flutter/flutter#58382]
Is it planned that this https://pub.dev/packages/webview_flutter#-readme-tab- plugin will support flutter-web in the near future?

I am particularity  interested in tracking the url / location of the embedded website.

**Comment by iapicca** [comment]
Hi @timosturm 
I see there's an open [issue](https://github.com/flutter/flutter/issues/45295) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
