### ISSUE TITLE
--debug mode should know how to use software backend if no GPU is found

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5839]
--debug mode should know how to use software backend if no GPU is found

This would be for emulators.  But since I know of no way to distinguish between emulators and physical devices we would just limit this to --debug mode.

This was inspired by https://github.com/flutter/flutter/issues/5815.

Thoughts?  @jason-simmons @abarth @chinmaygarde?

**Comment by per19** [comment]
@eseidelGoogle what is the advantage of using the --debug flag. Would it identify the emulator even if not ARM.

**Comment by eseidelGoogle** [comment]
--debug is just one of our three supported configurations.  It is the default configuration and used during development.  The other two are --profile and --release.  --debug works on both emulators and devices, but only provide device-configurations for --profile and --release.

**Comment by chinmaygarde** [comment]
We should probably add a document detailing the steps to take to enable GPU acceleration when using the emulators. It seems to have become a lot easier recently. I doubt the application is usable with emulation overhead, rendering using the software backend and the pauses do to the JIT in debug mode with checked mode assertions enabled.

**Comment by eseidelGoogle** [comment]
According to http://stackoverflow.com/questions/15804365/is-there-any-way-to-get-gpu-information `adb shell dumpsys | grep GLES` might work to get GPU information?  We could have `flutter run` refuse to run on devices w/o a GPU?  It seems more reliable to detect the GPU or not from with the flutter engine however and report that back to `flutter run` in some useful way?  Thoughts @chinmaygarde or @danrubel?

**Comment by eseidelGoogle** [comment]
This is one possible resolution for https://github.com/flutter/flutter/issues/6135.

**Comment by Hixie** [comment]
It's not clear what it would mean to not have a GPU. I'm going to close this in favour of https://github.com/flutter/flutter/issues/13336 where we can discuss the long-term policy.
