### ISSUE TITLE
🐞: Flutter release builds won't install on AVDs

### ISSUE THREAD

**Issue by joe733** [flutter/flutter#58393]
## Steps to Reproduce

1. Created a [dummy app](https://github.com/joe733/iamrich)
2. Sign the app as mentioned in the steps [here](https://flutter.dev/docs/deployment/android).
3. Build the app. (I built it to `apk` instead of `app bundle`) _with_ `--split-per-abi` option.
4. Drag and drop the compatible `apk` to the AVD,

**Expected results:** 
The `apk` installs without a flaw.

**Actual results:** 
The install fails with the following info:

![](https://user-images.githubusercontent.com/38415384/77728126-db146500-7021-11ea-8977-cce0394738fe.png)

<details>
  <summary>Logs</summary>

```bash
joe  (e) base  ~  Downloads  adb install app.apk 
Performing Streamed Install
adb: failed to install covid.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

</details>

The release produces: `app.apk`, `app-arm64-v8a-release.apk`, `app-armeabi-v7a-release.apk`, and `app-x86_64-release.apk` but all of them produces the same error.

Here's my emulator info:

![photo_2020-06-01_07-57-34](https://user-images.githubusercontent.com/38415384/83370622-96b89300-a3dd-11ea-892d-633ae9ff625f.jpg) 

---

> I first posted this issue [here](https://github.com/ashishkhuraishy/CovidUpdates/issues/8) when I first tested their app. But same issue happens with my dummy app so I posted it here :)

**Comment by jonahwilliams** [comment]
Flutter does not support x86 release builds, see https://flutter.dev/docs/deployment/android
