### ISSUE TITLE
 The problem of H5 keyboard style in flutter's WebView

### ISSUE THREAD

**Issue by libo1223** [flutter/flutter#58394]
when i use “<input type='search' />”(h5) in android,the keyboard style will change,but in Flutter ， i can't see this change.what's worse，the keyboard style will flash once.
this style is i want to see.
![8DA7C4B831482705E9B816DE06A4DAA6](https://user-images.githubusercontent.com/43235811/83372115-f7a09500-a3f6-11ea-87fc-17d874079e5b.jpg)
but the webview appear this style.
![Uploading 74B40A73D48CD585460DE55F24BAB370.jpg…]()

**Comment by libo1223** [comment]
the h5 is `<input type='search' />`

**Comment by libo1223** [comment]
the keyboard style of the first pic is i want to see

**Comment by VladyslavBondarenko** [comment]
Hi @libo1223 
please follow up on https://github.com/flutter/flutter/issues/56515,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
