### ISSUE TITLE
Installing an external package

### ISSUE THREAD

**Issue by hook9** [flutter/flutter#58402]
I think a usage like "npm install" will be more interactive. It is not useful to set it directly in the yml file

like this: **flutter install <package name>**

**Comment by iapicca** [comment]
Hi @hook9 
yours seems more a hint to a possible third party tool
like [flutter-node](https://www.npmjs.com/package/flutter-node) (without this being any endorsement) 
rather than a feature request for a tooling system different by design
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by hook9** [comment]
It is not a compatibility package for the nodejs I mentioned. I mentioned downloading packages for Flutter

> Hi @hook9
> yours seems more a hint to a possible third party tool
> like [flutter-node](https://www.npmjs.com/package/flutter-node) (without this being any endorsement)
> rather than a feature request for a tooling system different by design
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments and I will reopen it.
> Thank you



> Hi @hook9
> yours seems more a hint to a possible third party tool
> like [flutter-node](https://www.npmjs.com/package/flutter-node) (without this being any endorsement)
> rather than a feature request for a tooling system different by design
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

It is not a compatibility package for the nodejs I mentioned. I mentioned downloading packages for Flutter

**Comment by iapicca** [comment]
Hi @hook9 
could you please describe the benefits of such approach in details,
Thank you

**Comment by hook9** [comment]
Does it make sense to manually update the yml file continuously when we want to install a package?
I mean, the packages are downloaded with the command and written to the yml file automatically

**Comment by jonahwilliams** [comment]
This should be filled here: https://github.com/dart-lang/pub

And not against flutter
