### ISSUE TITLE
TextInputFormatter doesn't work on Samsung device

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#58412]
b/157838715

Sample Code: https://gist.github.com/mehmetf/39ac869714d60df2920f688dffe203f2

When testing input field on Samsung device (e.g. Galaxy J7 Pro with Android 8.1.0, Samsung Galaxy note 8 with Android 8.1.0), can only enter at most 3 characters in the text field.

This works properly in Pixel device.

However, if change "keyboardType: TextInputType.number" to "keyboardType: TextInputType.phone", then it works properly in Samsung device as well (can enter 16 digits with proper space separator).

**Comment by HansMuller** [comment]
CC @GaryQian @justinmc 
Maybe this is related to (fixed?) issue https://github.com/flutter/flutter/issues/41005

**Comment by justinmc** [comment]
I tried this on an old S6 that I have lying around and I couldn't reproduce it on master.

It does seem similar to https://github.com/flutter/flutter/issues/41005.

**Comment by chunhtai** [comment]
I updated the priority according to the internal bug, feel free to change it if it is not appropriate

**Comment by markusaksli-nc** [comment]
Hi @mehmetf 
I cannot reproduce this issue either on the latest master `1.20.0-8.0.pre.125` with an SM G950F.
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.125, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.125 at C:\Development\flutter_master
    • Framework revision 9c4a5ef1ed (16 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

Can you confirm if the issue still persists?
Thank you

**Comment by mehmetf** [comment]
Closing as not reproducible.
