### ISSUE TITLE
A Flutter Docs Web-Page Not Responsive On Mobile Display Due To A Large Image

### ISSUE THREAD

**Issue by shantanuchak** [flutter/flutter#58419]
This flutter docs page https://flutter.dev/docs/get-started/install/windows in mobile view is breaking the responsiveness due to a large image under Android Setup > Install Android Studio > [Link](https://flutter.dev/assets/get-started/android/android-sdk-tools-7a3eaa161678e404dc0c570cc0f4921944a3413586bad47b5e1f585ddfefada0.png)

This could easily be fixed by adding this property to the image CSS
``width: 60vw``

Additionally updating the <a> would enable users to directly view the image, as that image might be hard to view on smaller viewports. This can be the HTML for that:

``<a href="https://flutter.dev/assets/get-started/android/android-sdk-tools-7a3eaa161678e404dc0c570cc0f4921944a3413586bad47b5e1f585ddfefada0.png" target="_blank"><img src="/assets/get-started/android/android-sdk-tools-7a3eaa161678e404dc0c570cc0f4921944a3413586bad47b5e1f585ddfefada0.png" integrity="sha256-ej6qFhZ45ATcDFcMwPSSGUSjQTWGutR7Xh9YXd/vraA=" crossorigin="anonymous"></a>``

**Comment by christopherfujino** [comment]
Thanks for filing this! The website actually has its own github repo where this should be probably be filed against https://github.com/flutter/website/issues

**Comment by shantanuchak** [comment]
It seems like Flutter Fixed it!
