### ISSUE TITLE
Create a flutter-infra-alert group for pool offline alert

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#58417]
Right now all flutter infra team will receive these alerts. It would be good to have a separate group, similar to the dashboard alert.

**Comment by keyonghan** [comment]
\cc @godofredoc @digiter

**Comment by godofredoc** [comment]
There is already a flutter-infra-alerts group that you can reuse. I just modified it to include the alerts from the backend.

**Comment by keyonghan** [comment]
Submitted a CL to reuse that. Thanks.
