### ISSUE TITLE
flutter create should make a gradle-based project for Android

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#5842]
When you run `flutter create`, you should get an Android project that uses gradle.  Most developers will eventually need to use gradle to integrate with third-party SDKs and to add their own Java code.  We should start them off in that mode so that the transition is smooth.

**Comment by eseidelGoogle** [comment]
@jakobr-google is doing exactly this as we speak.  I suspect we have a dupe of this somewhere.

**Comment by abarth** [comment]
Duplicate of #4796
