### ISSUE TITLE
[web] Anonymous define() in CanvasKit's JS

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#58428]
I know from https://github.com/dart-lang/sdk/issues/33979 that you don't necessarily intend to rely on RequiresJS in the future (although it's not clear whether this applies to CanvasKit or not). Your call, no problem with that. But as long as you do, please, fix the JS source to contain a standard AMD `define()`. The omission of the name now makes it impossible to use RequireJS (even if we bring our own copy) in Flutter Web/CanvasKit apps.

**Steps to Reproduce:**

1. Grab any Flutter Web app, or create a new one.
2. Copy [`require.js`](https://requirejs.org/docs/download.html) or [`almond.js`](https://github.com/requirejs/almond) to the assets dir.
3. Include a `<SCRIPT>` tag to it in `Index.html`.
4. Run with CanvasKit enabled.

**Actual results:**

Using `requireJS`:

    Uncaught Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }

Using `almond.js`:

    almond.js:414 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.js:414)
    at canvaskit.js:333

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by deakjahn** [comment]
Seems to me:

    if (typeof exports === 'object' && typeof module === 'object')
        module.exports = CanvasKitInit;
    else if (typeof define === 'function' && define['amd'])
        define("CanvasKitInit", [], function() { //<<<<<
            return CanvasKitInit;
        });
    else if (typeof exports === 'object')
        exports["CanvasKitInit"] = CanvasKitInit;

**Comment by TahaTesser** [comment]
Hi @deakjahn 
Adding `require.js` and index.html script doesn't throw `Uncaught Error` on latest `dev`

<img width="286" alt="Screenshot 2020-06-02 at 4 09 02 PM" src="https://user-images.githubusercontent.com/48603081/83510952-7d057180-a4eb-11ea-9a32-648223540213.png">

```
  <script src="assets/require.js"></script>
  <script src="main.dart.js" type="application/javascript"></script>
```

command
```
flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v
```


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by deakjahn** [comment]
Then you might need to actually call it. Well, a bit more source required. Add another .js, say, `example.js` and call `requirejs()` from it. Let's try a PDF viewer (although it doesn't make any difference what package you call):

    requirejs.config({
      baseUrl: 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200',
      paths: {
        'pdfjs-dist/build/pdf': 'pdf.min',
        'pdfjs-dist/build/pdf.worker': 'pdf.worker.min',
      }
    });
    
    requirejs(['pdfjs-dist/build/pdf', 'pdfjs-dist/build/pdf.worker'], function(pdfjsLib, pdfjsWorker) {
      console.log(pdfjsLib);
    });

Call both scripts from `Index.html`.

**Comment by deakjahn** [comment]
Bother. Trying to come up with a minimal repro. I actually saw it inside a plugin and right now, it doesn't want to manifest itself in a minimal app. I keep trying...

**Comment by deakjahn** [comment]
@TahaTesser What if I give you a full federated plugin whose `example` shows the problem rather than a minimal app? :-) I know it's less than ideal but, it seems to me, it must be somehow related to plugins. A plain app works all right.

**Comment by deakjahn** [comment]
I can see the same problem in three different plugins, so it shouldn't be something specific to this one.

Start the `example` in Web/CanvasKit.
![Annotation 2020-06-02 145541](https://user-images.githubusercontent.com/2234271/83522593-2e52da00-a4e1-11ea-8bbd-2ac1dc9700d2.png)

I couldn't yet find why it's only manifesting in a plugin. If you disregard the rest, it's the same as I described originally, the plugin registers itself and includes the two JS files (does it programmatically rather than manually adding to `Index.html`). `flutter_pdfview.js` inside the web plugin tries to use RequireJS to load the `pdf.js` library and result in the error message.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by deakjahn** [comment]
I cloned the `canvaskit.js` and `canvaskit.wasm` to my server and modified `engine/compositor/initialization.dart` to use that instead of the CDN-hosted one. With the modification above, I didn't see any error or regression. Not a definitive test, of course... :-)

**Comment by hterkelsen** [comment]
The anonymous AMD module is auto-generated code from Emscripten's `MODULARIZE` option. As far as I can tell there's no way to provide a name for a module generated this way.

Perhaps the best workaround will be to convince CanvasKit that `require` isn't defined on the window while it is loading by moving it somewhere else and restoring it after loading.

**Comment by hterkelsen** [comment]
Unfortunately hiding the 'define' function doesn't work because when we add the CanvasKit script to the DOM, `require.js` hasn't been loaded yet, but by the time CanvasKit executes, `require.js` has been loaded so it sees the `define` function. We probably need to build our own CanvasKit version without setting the `MODULARIZE` flag in order to fix this issue.

**Comment by hterkelsen** [comment]
@deakjahn You should be able to work around your issue by loading `require.js` with `defer`

**Comment by deakjahn** [comment]
@hterkelsen It doesn't look like _defer_ would change anything. I receive the same error message.
