### ISSUE TITLE
Slider reading issue with Voice Over

### ISSUE THREAD

**Issue by KrystinaH** [flutter/flutter#58427]
I need to have a fully accessible slider for a project and I can't read all the values of the slider with Voice Over more than one time.

## Steps to Reproduce

```
Slider(
  min: 0.0,
  max: widget.data == null || widget.data.length == 0 ? 1 : widget.data.length.toDouble() - 1,
  divisions: widget.data == null || widget.data.length == 0 ? 1 : widget.data.length - 1,
  label: _getPointerDate(activeDayIndex),
  value: activeDayIndex.toDouble(),
  onChanged: (value) {
    announce(FlutterI18n.translate(context, 'home.charts.dataDisplayedFor') + _getPointerDate(activeDayIndex), TextDirection.ltr);
    _updateCounts(value.toInt());
  },
)
```

1. Create a slider with at min, max and division equals to max. In my specific case, an async data  list set the max with its length and the slider represents a timeline (each value is a date).
2. Open Voice Over or XCode Accessibility inspector (the bug is on simulator and on physical devices)
3. Use the increment and decrement buttons (simulator) or up and down swipe navigation (physical device) to read the different values. If you get to the start (minimum value), you will be stuck here and won't be able to read the rest of the slider values.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.5 18F132, locale fr-CA)
    • Flutter version 1.17.0 at /Users/khamel/www/flutter
    • Framework revision e6b34c2b5c (il y a 4 semaines), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/khamel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @KrystinaH 
Can you please provide complete minimal complete reproducible code sample.

Thank you

**Comment by KrystinaH** [comment]
Hi @TahaTesser, I'm sorry for the delay. I figured out that it's a more specific problem than I thought, since I am not able to reproduce it with a simplified code. Unfortunately, I can't share the code I'm working on now, but I will let you know if I find something new about this.

Thank you for your time

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
