### ISSUE TITLE
Non-nullability unfork causing issues in the Fuchsia builder

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#58431]
This is currently happening on the dart CI engine builders.

Full logs at: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8878866180302852880/+/steps/build_fuchsia_debug_x64_flutter_shell_platform_fuchsia:fuchsia_fuchsia_tests/0/stdout

```
String _rawScript;
       ^^^^^^^^^^
Unhandled exception:
Crash when compiling dart:async/async_error.dart,
at character offset null:
RangeError (offset): Invalid value: Not in range 0..352, inclusive: 576
#0      RangeError.checkValueInInterval (dart:core/errors.dart:302:7)
#1      Source.getLocation (package:kernel/ast.dart:9080:16)
```

cc: @a-siva , @aam 

@yjbanov seems like we need to do some changes to the Fuchsia build targets to support NNBD?

**Comment by a-siva** [comment]
The following files
```
flutter/shell/platform/fuchsia/flutter/kernel/libraries.yaml
flutter/shell/platform/fuchsia/flutter/kernel/libraries.json
```
needs to be changed similar to
```
flutter/lib/snapshot/libraries.yaml
flutter/lib/snapshot/libraries.json
```
to point to files in 
`third_party/dart/sdk_nnbd` instead of `third_party/dart/sdk`
