### ISSUE TITLE
Report more of a Picture's actual size to the Dart VM

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#58438]
From @chinmaygarde 

`drawVertices` and `drawPoints` has vertex buffers whose sizes can be appreciable (IIRC stuff like flare uses it extensively).
`drawPath` can have custom paths that may be large. There are path iterator APIs that you can use to walk an count the verbs and points. You should probably memoize the size here too.

All arguments that can take a paint may have a shader set on them. These shaders can reference images. In the same vein, shaders in dart:ui should also reference the correct size.

One thing I'm not clear on is whether `approximateBytesUsed` on `SkPicture` accounts for any of these - for example, I know it does _not_ include image and font data, but it's not clear to me whether it includes vertex buffers or paths (I would expect it does include paths). At any rate, iterating paths for this purpose is probably more expensive than we want to be.

/cc @chinmaygarde @brianosman @mtklein @liyuqian  who may know

**Comment by mtklein** [comment]
In general when recording an SkPicture we're filling out structs from SkRecords.h and copying them into allocations provided by SkRecord.h.  Data pointed to by Optional or PODArray (defined in SkRecords.h) is allocated inline in the SkRecord and counted by approximateBytesUsed().  Any other indirect data, whether via an sk_sp, SkPath, effects on SkPaint, etc. is not counted.

So a quick scan looks like:
     - drawVertices()  - not counted
     - drawPath() - not counted
     - drawPoints() - counted
And yeah, no shader is counted for any method.

(I'm unclear why DrawPoints doesn't use a PODArray for its pts field to make its ownership clear.)

**Comment by dnfield** [comment]
@mtklein - it seems like `drawPoints` boils down to a `drawPath` on GPU backed pictures. 

I can verify with a SkiaFiddle that the adding more points adds to the approximateBytesUsed on the resultant SkPicture, but will that still be true for the GPU case? Am I even understanding that correctly? :)

**Comment by mtklein** [comment]
SkPictures just record SkCanvas commands, and are mostly* independent of the backends.

* Mostly, in that things like SkImages can be GrContext-specific, but nothing in SkPicture per-se cares.

**Comment by chinmaygarde** [comment]
@dnfield I am trying to figure out the priority for this. The linked issue seems to address part of this. If so, can we reduce the priority appropriately? Unless you are still working on this, in which case, lets leave it as-is.

**Comment by dnfield** [comment]
I think this is done. Closing.
