### ISSUE TITLE
Make Dart VM aware of growing size/weight of Canvas

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#58437]
For example, when we draw an image to a canvas, we should inform the VM that the canvas' allocation size is now higher to include the image.

We'll be able to do this once https://dart-review.googlesource.com/c/sdk/+/149245 lands

/cc @chinmaygarde @liyuqian @rmacnak-google

**Comment by chinmaygarde** [comment]
Does the framework hold references to Canvases directly very often? My expectation was that pictures were the long lived heavyweight objects.

**Comment by dnfield** [comment]
No, I think we can lower the priority on this until we have a user who needs it or some convincing evidence that it's needed.

**Comment by dnfield** [comment]
Now that we properly dispose Canvas/Picture objects this is not necessary.
