### ISSUE TITLE
Add Fuchsia console to the Flutter dashboard

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#58434]
We are now running Fuchsia post submits for each commit to the framework. These are run as part of the Fuchsia infra and the status can be seen at: <elided>.

These are currently failing, atyfto@google.com, @chaselatta , @iskakaushik  are working on fixing the failures and getting this builder to green.

These should be part of https://flutter-dashboard.appspot.com/#/build.

Per @godofredoc :

It is possible with a few changes in different places:

- Builbucket queries called from this handler https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
- Service account permissions to access the fuchsia bucket
- Some changes in the configs https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_github_commits.dart#L215

Mirror of fxb/53127

**Comment by kf6gpe** [comment]
Checking in, @iskakaushik --- is August still a realistic milestone here?

Thanks!

**Comment by kf6gpe** [comment]
Downgrading after chatting with Kaushik.

**Comment by iskakaushik** [comment]
This is blocked on work that is needed to be done by the Fuchsia infra team that is scheduled for Q3. Punting this till September.

**Comment by zanderso** [comment]
@iskakaushik Is this unblocked?

**Comment by iskakaushik** [comment]
I am not sure if it's a priority for us anymore. I'll leave it up-to @chaselatta to decide if he thinks this will still be needed and re-open if necessary.
