### ISSUE TITLE
Make ImageShaders update the allocation information when an image is set

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#58440]
the ImageShader class should update the VM with allocation information when an an image is actually set to it. 

Once we can do that, we should also report the size through to Canvas/Picture when the shader is actually applied there.

See also: https://github.com/flutter/flutter/issues/58438, https://github.com/flutter/engine/pull/18706

Blocked on: https://dart-review.googlesource.com/c/sdk/+/149245

/cc @rmacnak-google @chinmaygarde @liyuqian

**Comment by jonahwilliams** [comment]
We're moving away from specifying exact allocation size as it doesn't work great with the VM herustics
