### ISSUE TITLE
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds

### ISSUE THREAD

**Issue by osunkoyadavid** [flutter/flutter#58447]
I'm having this error: Waiting for 0 seconds, press CTRL+C to quit ... Running pub upgrade... The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297. Because flutter_tools requires SDK version >=2.2.2 <3.0.0, version solving failed. Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

**Comment by TahaTesser** [comment]
Hi @osunkoyadavid 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by osunkoyadavid** [comment]
Don't get it pls

**Comment by osunkoyadavid** [comment]
I need help please

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by osunkoyadavid** [comment]
Errr, thanks for your help, by the way, I'm running flutter apps already
