### ISSUE TITLE
App.framework not being generated.

### ISSUE THREAD

**Issue by bismarabia** [flutter/flutter#58441]
Despite all the issues opened regarding this issue, I couldn't get this folder to be generated.
I'm getting this error when running the app in simulator.

`Failed to find assets path for "Frameworks/App.framework/flutter_assets"`

which I know that the App.framework is missing. and that resulted in a blank screen.

I have read all the issues in this repo [#29974](https://github.com/flutter/flutter/issues/29974) and [#52084](https://github.com/flutter/flutter/issues/52084) also in SO. but no luck.
I have also followed the step in ios [migration guide](https://flutter.dev/docs/development/ios-project-migration). but also no luck.

![ios migration guide applied](https://www.evernote.com/l/ASIgRPKzHXtCbLI5YnVbVc6klwI4KiNnpP4B/image.png)
![ios migration guide applied](https://www.evernote.com/l/ASJspzNIBfBEx7RrPuj8XmWQIhB_0GreuI4B/image.png)

I tried deleting `Flutter.Framework` folder, run `pod install`, but again no luck.

Flutter doctor -v
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-TR)
    • Flutter version 1.18.0-11.1.pre at /Users/bisma/Desktop/Flutter/flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bisma/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio/Android Studio 4.1 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • D2DDFE8A-E9DE-4FEC-A31B-D5BA54D0111F • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 categories.
Process finished with exit code 0
```

I have been struggling with this for days, any help is appreciated.

**Comment by TahaTesser** [comment]
Hi @bismarabia 
Are you experiencing this same issue using a new project? 
Did you try it switching `dev` or `master` channel?

Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by bismarabia** [comment]
thanks for the reply @TahaTesser 
I'm using beta channel, I didn't switch to neither dev nor master.

I forget to mention in the question, that this started to happen after upgrading to the latest firebase plugins. mine are:
```
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.3+3
  firebase_remote_config: ^0.3.1
```

not sure tho if it's directly related to that.

**Comment by TahaTesser** [comment]
Hi @bismarabia 
Could try reproducing the issue without firebase packages?
Thank you

**Comment by bismarabia** [comment]
> Hi @bismarabia
> Could try reproducing the issue without firebase packages?
> Thank you

I did that (completely removed firebase plugins from pubspec.yaml/Podfile), run pub get, pod install/update, ..

but it still didn't work, the folder doesn't get generated.

**Comment by bismarabia** [comment]
What I did to overcome this error is 
- creating a brand new project and gave it the same name as my project.
- then started to copy the files one by one from git (the original project) to the that new created project.
- made sure that `flutter clean` and `flutter build ios` do generate the `App.framework` after each couple of steps.

Hope this helps to resolved such buggy issues.

thank you @TahaTesser for your help and consideration. feel free to close this issue.

**Comment by TahaTesser** [comment]
Hi @bismarabia 
Glad you resolved the issue
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by thanhhai08sk** [comment]
In my case, I need to uncheck the build flag:
![Uploading Screen Shot 2020-10-17 at 11.09.48 AM.png…]()
