### ISSUE TITLE
[cocoon] Create a handler that pushes benchmark to Metrics Center

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#58442]
Per discussion with @liyuqian we'd like to push the devicelab benchmark data to metrics center, which transfers the data to skia perf later. So that skia perf can be utilized to view the devicelab benchmark results.

We will need to integrate https://github.com/liyuqian/metrics_center with Cocoon backend. And add a cron job to push the data continuously.

This is part of the go/flutter-metrics-center effort.

**Comment by godofredoc** [comment]
Any reason this is marked as severe:performance?

**Comment by liyuqian** [comment]
In addition to performance related bugs, we also put "severe: performance" on issues that are related with performance tests. It does not signal the priority it has as we would not put P0/P1 or TODAY for this issue.

**Comment by digiter** [comment]
I have transferred 3 months of data from March to May this year to the FlutterCenter storage.

**Comment by CaseyHillers** [comment]
This is being done on /api/update-task-status calls
