### ISSUE TITLE
[cocoon] Have build dashboard expose what revision is currently deployed

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#58451]
For example, I landed https://github.com/flutter/cocoon/pull/786 on 5/29/2020, but upon returning to work on 6/1/2020, it appeared the change had not taken effect. I wanted to verify if my change had been deployed, but found there was no easy (and unprivileged) way to see what version of cocoon was currently deployed.

If the build dashboard showed the git revision that was currently running (for example, when navigating to "About Flutter Dashboard" in the menu), this would greatly help debugging.

**Comment by ditman** [comment]
cc @yjbanov I think we have a very recent feature request for this, that could be used to implement package_info as well.

Please, track this: https://github.com/flutter/flutter/issues/57316

**Comment by christopherfujino** [comment]
Thanks, closing this one!
