### ISSUE TITLE
Hot reload/restart not working again.

### ISSUE THREAD

**Issue by jamiejackherer** [flutter/flutter#58468]
So hot reload just stopped working. Having looked on google etc I found issue #49185 which is now closed. I was using the latest kernel on Arch Linux (Kernel 5.6.15.arch1-1) and had no issues until I updated my packages (notably Android NDK and Android Studio) but I use VSCode (Code-OSS version). 

I tried downgrading my kernel to 5.4.43-1-lts, problem still exists.
I tried changing to all different Flutter versions (I mainly use the master channel). 

Usually I can hot reload maybe once or twice, even 3 or 4 times and then it will hang there indefinitely. Its frustarting that issue #49185 was closed without a real explantion as to what happened or how it was fixed.... 

## Steps to Reproduce
Run a Flutter app.

This is the same as #49185 happening again. 
1. Build any flutter app
2. Run app via `flutter run` or with Android Studio or with VSCode
3. Try to hot reload/restart (works once or twice then hangs)

## Logs

```
Performing hot restart... (completed in 89,741ms, longer than expected) <-- it never completed, i exited
[  +19 ms] "flutter run" took 9,975,116ms.
the Dart compiler exited unexpectedly.
[  +49 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[  +28 ms] Failed to clean up temp directory: /tmp/flutter_tools.DFEIAG/flutter_tools.IMRUHO
[   +5 ms] Failed to clean up temp directory: /tmp/flutter_tools.DFEIAG/flutter_tools.IMRUHO
the Dart compiler exited unexpectedly.
[   +5 ms] Failed to clean up temp directory: /tmp/flutter_tools.DFEIAG/flutter_tools.IMRUHO
[   +2 ms] Application finished.
```
`flutter doctor -v`
```
[  +11 ms] executing: [/home/jamie/dev/dart/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d395c5e187370f2838bb043d3b438029b484bfc
[        ] executing: [/home/jamie/dev/dart/flutter/] git tag --contains HEAD
[ +306 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.19.0-2.0.pre
[  +16 ms] executing: [/home/jamie/dev/dart/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/jamie/dev/dart/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +93 ms] executing: [/home/jamie/dev/dart/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +73 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +82 ms] executing: [/home/jamie/dev/dart/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/home/jamie/dev/dart/flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+1785 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[        ] From https://github.com/flutter/flutter
            * branch                HEAD       -> FETCH_HEAD
[        ] executing: [/home/jamie/dev/dart/flutter/] git tag --contains HEAD
[ +228 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.19.0-2.0.pre
[   +3 ms] Doctor summary (to see all details, run flutter doctor -v):
[  +16 ms] executing: /opt/android-studio/jre/bin/java -version
[ +284 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[  +26 ms] executing: /opt/android-studio/jre/bin/java -version
[  +76 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[  +11 ms] executing: [/home/jamie/dev/dart/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 2 days ago
[  +18 ms] executing: /home/jamie/dev/dart/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +49 ms] Exit code 255 from:
/home/jamie/dev/dart/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +16 ms] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the VM version.                                                     

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[  +26 ms] java -version
[ +217 ms] executing: /home/jamie/Android/Sdk/platform-tools/adb devices -l
[  +35 ms] [✓] Flutter (Channel master, 1.19.0-2.0.pre, on Linux, locale en_GB.UTF-8)
⣽[ +127 ms] List of devices attached
⣻[  +85 ms] executing: /home/jamie/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
 
[+3505 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[   +6 ms] [✓] Chrome - develop for the web
[   +6 ms] [✓] Android Studio (version 4.0)
[   +2 ms] [✓] Connected device (2 available)
[        ] • No issues found!
[  +23 ms] "flutter doctor" took 6,718ms.
```

**Comment by jeansebastienZ** [comment]
Same problem again here .

Flutter doctor -v  :

> C:\src\flutter>flutter doctor -v
> [√] Flutter (Channel master, 1.19.0-3.0.pre.13, on Microsoft Windows [version 10.0.18362.836], locale fr-FR)
>     • Flutter version 1.19.0-3.0.pre.13 at C:\src\flutter
>     • Framework revision 6135091de9 (15 hours ago), 2020-06-01 17:17:03 -0700
>     • Engine revision e39301f23f
>     • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)
>

**Comment by shinayser** [comment]
This problem just started happening to me!

```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [versÃ£o 10.0.18363.836], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] Connected device (1 available)

• No issues found!

```

**Comment by jmagman** [comment]
Three things here:
Hot Reload:
```
the Dart compiler exited unexpectedly.
```
```
Failed to clean up temp directory
```
Doctor:
```
[  +49 ms] Exit code 255 from:
/home/jamie/dev/dart/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +16 ms] At least one input is required
```

**Comment by jamiejackherer** [comment]
So I dont know how exactly but this issue seemed to have fixed itself.. But its back again!! 

I can hot reload around 10 times and then it just starts hanging again..

Is anyone even reading these issues atm?

**Comment by mraleph** [comment]
> Its frustarting that issue #49185 was closed without a real explantion as to what happened or how it was fixed.

It was fixed by [this commit](https://dart-review.googlesource.com/c/sdk/+/136322). This information is in fact among the [comments](https://github.com/flutter/flutter/issues/49185#issuecomment-589801804) on #49185

> Is anyone even reading these issues atm?

Yes, but we need more information to be able to act on this. 

When you hit the hang next time please try the following:

- list all processes in the system and locate the pid of the hanging process (you need to be looking for a `dart` process which is running frontend server).
- attach `gdb` to it (via `gdb attach <pid>`), then print stack traces of all threads (`thread apply all bt`) and post this output here.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 3DRaven** [comment]
Hi, I have same problem. I'm not sure, but it is threads dump for one dart process
`
ps -A|grep dart
 219671 ?        00:06:01 dart
 219725 ?        00:00:03 dart
 219739 ?        00:01:43 dart
 478911 ?        00:00:07 dart
 478929 ?        00:00:04 dart
`
This is dump
`
sudo gdb attach 219671
[sudo] пароль для i3draven: 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: Нет такого файла или каталога.
Attaching to process 219671
[New LWP 219672]
[New LWP 219735]
[New LWP 219736]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffcd696c338) at ../sysdeps/nptl/futex-internal.h:183
183	../sysdeps/nptl/futex-internal.h: Нет такого файла или каталога.
(gdb) thread apply all bt

Thread 4 (Thread 0x7f84b04fe700 (LWP 219736)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f84940075b4) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f8494007560, cond=0x7f8494007588) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f8494007588, mutex=0x7f8494007560) at pthread_cond_wait.c:638
#3  0x0000000001a41105 in ?? ()
#4  0x0000000001ada4c7 in ?? ()
#5  0x0000000001ac8789 in ?? ()
#6  0x0000000001ac8a17 in ?? ()
#7  0x0000000001a40881 in ?? ()
#8  0x00007f84b367a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f84b3452293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f84b05ff700 (LWP 219735)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x26140b4) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x2614060, cond=0x2614088) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x2614088, mutex=0x2614060) at pthread_cond_wait.c:638
#3  0x0000000001a41105 in ?? ()
#4  0x0000000001ada4c7 in ?? ()
#5  0x0000000001ac8789 in ?? ()
#6  0x0000000001ac8a17 in ?? ()
#7  0x0000000001a40881 in ?? ()
#8  0x00007f84b367a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f84b3452293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 2 (Thread 0x7f84b1e26700 (LWP 219672)):
#0  0x00007f84b34525ce in epoll_wait (epfd=5, events=0x7f84b1e25e00, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00000000017dd2a8 in ?? ()
#2  0x00000000019009db in ?? ()
#3  0x00007f84b367a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f84b3452293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f84b332ec00 (LWP 219671)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffcd696c338) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7ffcd696c2e8, cond=0x7ffcd696c310) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7ffcd696c310, mutex=0x7ffcd696c2e8) at pthread_cond_wait.c:638
#3  0x0000000001a41105 in ?? ()
#4  0x0000000001ccfc1a in ?? ()
#5  0x00000000017d2ab4 in ?? ()
#6  0x00000000017d3b3e in ?? ()
#7  0x00000000017d48b6 in ?? ()
#8  0x00007f84b33570b3 in __libc_start_main (main=0x17d48b0, argc=5, argv=0x7ffcd696c658, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcd696c648) at ../csu/libc-start.c:308
#9  0x00000000017cd02a in _start ()
(gdb) 
`

**Comment by mraleph** [comment]
@3DRaven it is unlikely that you hit the same problem, because the problem was fixed. You might hit problem which has similar symptoms, but in that case you should file a separate bug and describe what you are seeing.
