### ISSUE TITLE
after use google_maps_flutter-0.5.28+1 app in ios not work

### ISSUE THREAD

**Issue by Ahmedtaha123** [flutter/flutter#58476]
i was use google_maps_flutter-0.5.27+1 and after 
i updated my macos to macos catalina 10.15.5 and xcode to xcode 11.5
and now i use flutter 1.17.2
i updated all my packages and update  google_maps_flutter to 0.5.28+1
and when i run my app in real ios ipad i get this error

      Launching lib/main.dart on iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 83YNLV6KMA
Running pod install...                                             36.8s
Xcode build done.                                           50.6s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-06-02 11:25:57.501 xcodebuild[33948:249015]  DTDeviceKit: deviceType from 4a5c1dc1e2024c618604a3b9f8f9d55e73592c5c was NULL
    2020-06-02 11:25:57.576 xcodebuild[33948:249009]  DTDeviceKit: deviceType from 4a5c1dc1e2024c618604a3b9f8f9d55e73592c5c was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    /users/dell/desktop/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.28+1/ios/Classes/FLTGoogleMapsPlugin.m:17:14: error: no visible @interface for 'NSObject<FlutterPluginRegistrar>' declares the selector 'registerViewFactory:withId:gestureRecognizersBlockingPolicy:'
      [registrar registerViewFactory:googleMapFactory
       ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.

Error launching application on iPad.
Exited (sigterm)


how to fix this error

**Comment by TahaTesser** [comment]
Hi @Ahmedtaha123 
Running the official with `google_maps_flutter: ^0.5.28+1` has no issue on  iOS

This issue is because of your provisioning profile, make sure team and provision profile is created while and try again 
Thank you

**Comment by Ahmedtaha123** [comment]
it works after i create new flutter project and moved all files to new project
