### ISSUE TITLE
Flutter Error JAVA HOME and sure java work

### ISSUE THREAD

**Issue by kartzhai** [flutter/flutter#58475]
i have flutter project that work well. but suddenly when i try to run it got error like below :

Running Gradle task 'assembleDebug'...

ERROR: JAVA_HOME is set to an invalid directory:

Please set the JAVA_HOME variable in your environment to match the location of your Java installation. Finished with error: Gradle task assembleDebug failed with exit code 1

i try to running other project and it run properly. only that one project error. i sure the java running well since a try another project and new project can be run.

please your advice.

## Steps to Reproduce

      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->

C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc>flutter run --verbose
[  +32 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +39 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +85 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +118 ms] executing: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +26 ms] Exit code 0 from: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           28889d220404           device product:mido model:Redmi_Note_4 device:mido transport_id:2
[  +18 ms] C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe -s 28889d220404 shell getprop
[  +95 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Found plugin flutter_bluetooth_basic at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_bluetooth_basic-0.1.5\
[  +24 ms] Found plugin image_picker_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker_saver-0.3.0\
[  +16 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[  +16 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +4 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +62 ms] Found plugin flutter_bluetooth_basic at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_bluetooth_basic-0.1.5\
[  +12 ms] Found plugin image_picker_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker_saver-0.3.0\
[   +7 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[   +7 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +53 ms] Generating C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +35 ms] ro.hardware = qcom
[  +61 ms] Launching lib\main.dart on Redmi Note 4 in debug mode...
[  +15 ms] executing: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe -s 28889d220404 shell -x logcat -v time -t 1
[  +98 ms] Exit code 0 from: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe -s 28889d220404 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           06-02 17:46:28.116 I/MSM-irqbalance(  859): Decided to move IRQ3 from CPU0 [P:0] to CPU4 [P:1] (banned)
[   +7 ms] executing: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +1 ms] executing: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe -s 28889d220404 logcat -v time -T 06-02 17:46:28.116
[  +32 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\kartz\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +24 ms] Building APK
[  +11 ms] [!] Your app isn't using AndroidX.
[        ]     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
[   +9 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc\android\gradlew.bat.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +122 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +3 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +5 ms] executing: [C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc\android\] C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc\android\gradlew.bat -Pverbose=true -Ptarget=C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[  +87 ms] ERROR: JAVA_HOME is set to an invalid directory: 
[   +2 ms] Please set the JAVA_HOME variable in your environment to match the
[        ] location of your Java installation.
[  +12 ms] Running Gradle task 'assembleDebug'... (completed in 0.2s)
[   +6 ms] "flutter run" took 1,160ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc>

```
```

C:\Users\kartz\OneDrive\Flutter Project\pos_project_bloc>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kartz\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\kartz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Redmi Note 4 • 28889d220404 • android-arm64 • Android 7.0 (API 24)

• No issues found!

</details>

**Comment by medric49** [comment]
Hello. I've noticed you closed the issue, please how did you solve it ? I have the same problem

**Comment by ZiaUrRahmam** [comment]
please mention how u solve it i am facing the same

**Comment by flutterq** [comment]
All Possible Working Solution Added Here [[Solved] ERROR: JAVA_HOME is not set and no ‘java’ command could be found in your flutter PATH. in flutter](https://fluttercorner.com/solved-error-java_home-is-not-set-and-no-java-command-could-be-found-in-your-flutter-path-in-flutter/)
