### ISSUE TITLE
Does shared_preferences provide support for EncryptedSharedPreferences?

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter#58470]
As Android comes up with the [EncryptedSharedPreferences](https://developer.android.com/topic/security/data#classes-in-library) concept for the security of app-level values.

### EncryptedSharedPreferences(Android):

- Wraps the SharedPreferences class and automatically encrypts keys and values using a two-scheme method:

- **Keys** are encrypted using a deterministic encryption algorithm such that the key can be encrypted and properly looked up.

- **Values** are encrypted using [AES-256 GCM](https://tools.ietf.org/html/rfc5116#section-5.2) and are non-deterministic.

So Does [shared_preferences](https://pub.dev/packages/shared_preferences) provides support for this security feature? If not then Is there any planning to add this feature in the future scope of this shared_preferences](https://pub.dev/packages/shared_preferences)?

**Comment by stuartmorgan** [comment]
Closing as out of scope; there's nothing comparable on any of the other platforms we support, so this would be best implemented as a separate, community plugin.
