### ISSUE TITLE
flutter deactivate ios push pop  do not execute

### ISSUE THREAD

**Issue by 120011676** [flutter/flutter#58485]
```shell
(base) say@SaylideMacBook-Pro qlink_flutter_app % flutter --version
Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (5 days ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3
```

Flitter life cycle is not good

push pop It is not intuitive to monitor alone

···dart
  @override
  void deactivate() {
    print('deactivate');
  }
```

**Comment by VladyslavBondarenko** [comment]
@120011676 
Consider to fill out [the issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=feature_request.md&title=) completely

**Comment by VladyslavBondarenko** [comment]
@120011676 
I hope you've solved the issue.
Closing as additional information isn't provided

**Comment by 120011676** [comment]
@VladyslavBondarenko 

flutter 监听返回页面 ,经常会用到这个方法:
``dart
  void deactivate() {
    super.deactivate();
    var bool = ModalRoute.of(context).isCurrent;
    if (bool) {
        print('处理返回页面操作');
    }
  }
```
但是这个方法发现在ios上不会执行 ,原因不详

![image](https://user-images.githubusercontent.com/1992933/86109132-9ef81100-baf6-11ea-9bc6-95725a21ff2f.png)

**Comment by VladyslavBondarenko** [comment]
@120011676 
with stable `1.17.1` and master `1.20.0-3.0.pre.100` I see the same behavior for iOS 13.5 simulator and Android 9 (API 28) device - deactivate function is called, but `ModalRoute.of(context).isCurrent` is already `false`. Is it the same for you?

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<FirstRoute> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  void deactivate() {
    print('deactivate');
    var bool = ModalRoute.of(context).isCurrent;
    print(bool);
    if (bool) {
      print('处理返回页面操作');
    }
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

Why do you need to check `ModalRoute.of(context).isCurrent`?

**Comment by 120011676** [comment]
@VladyslavBondarenko 
1.A page deactivate
2.B page deactivate
3.A  Navigator.push(B) 
4.A page deactivate no execute
5.B page Navigator.pop()
6.B page deactivate execute,A page deactivate no execute

I want to know A page Navigator.pop () is back

**Comment by VladyslavBondarenko** [comment]
@120011676 

<details>
 <summary>With this code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<FirstRoute> {

  @override
  void deactivate() {
    print('A deactivate');
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  void deactivate() {
    print('B deactivate');
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

I can see that on `3. A Navigator.push(B)` `4. A page deactivate no execute`, but `A deactivate` is executed when you are using `Navigator.pushNamed(B)`.

Is your issue different from https://github.com/flutter/flutter/issues/50147?

**Comment by 120011676** [comment]
@VladyslavBondarenko yes，#50147 The same problem

**Comment by VladyslavBondarenko** [comment]
@120011676 
Then I'm closing current one as duplicate, since https://github.com/flutter/flutter/issues/50147 is older and has more participants, follow up on it.
If you disagree please write in the comments and I will reopen it

**Comment by 120011676** [comment]
@VladyslavBondarenko good,ok

**Comment by 120011676** [comment]
@VladyslavBondarenko Now how do you know the page is back?

**Comment by VladyslavBondarenko** [comment]
@120011676 
you can use [RouteObserver](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html ) - https://medium.com/flutter-community/how-to-track-screen-transitions-in-flutter-with-routeobserver-733984a90dea

**Comment by 120011676** [comment]
@VladyslavBondarenko Good,tks
