### ISSUE TITLE
Add documentation/codelabs for custom widget/ui libraries

### ISSUE THREAD

**Issue by TheOtterlord** [flutter/flutter#58480]
## Use case

I wish to create my own ui library (like Material/Cupertino), but there is no documentation showing how these are created. I think that this would allow people to create amazing custom libraries implementing new ui design concepts and allow even more flexibility. 

## Proposal

Add documentation specific to creating a UI library including simple tutorials, codelabs, cookbooks, and examples.

**Comment by goderbauer** [comment]
/cc @sfshaza2 @RedBrogdon for thoughts

In general, to create a UI library, you would just create a bunch of custom widgets for which we have existing documentation. What are you missing?

**Comment by TheOtterlord** [comment]
More indepth stuff such as how the rendering works and tutorials to create complex widgets without expanding Material would be good.
