### ISSUE TITLE
 Your app isn't using AndroidX.     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

### ISSUE THREAD

**Issue by Melisa1-gif** [flutter/flutter#58487]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @Melisa1-gif 
Follow the steps on https://goo.gl/CP92wY (or create an app anew, it will use AndroidX by default)
Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it
