### ISSUE TITLE
Support latest Material Design Icons

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#58497]
Flutter does not seem to have the latest [icons from Material Design](https://material.io/resources/icons/?style=baseline) in `Icons`.

For example, the `Home` section is completely missing as well as `text_snippet` etc.

## Use case

The icon set seems to have been extended a fair bit and these additional icons should be included.

## Proposal

Update the Material Design icons font and the `Icons` class.

**Comment by VladyslavBondarenko** [comment]
Hi @creativecreatorormaybenot 
follow up on https://github.com/flutter/flutter/issues/27956,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
