### ISSUE TITLE
Use the iOS share icon when the app is running on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5849]
Problem: the default material share icon isn't familiar to iOS users. iOS has a different share icon, and by default today Flutter apps use the non-iOS share icon.

Proposed solution: use an iOS-friendly share icon, approved by our designers, when the Flutter app is running on iOS.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/5390 is related.

**Comment by eseidelGoogle** [comment]
I think I'm going to close this in lieu of https://github.com/flutter/flutter/issues/7111.
