### ISSUE TITLE
backdrop_filter_perf_ios__timeline_summary average_vsync_transitions_missed &  99th_percentile_vsync_transitions_missed & average_vsync_transitions_missed regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#58501]
All around this revert https://github.com/flutter/flutter/pull/58188 or the following commits. I don't see how the commit in question could have caused this, however. Perhaps it's this engine roll https://github.com/flutter/flutter/pull/58460, and the other increases are noise?

As these are small regressions, not labeling as P0, but still should be investigated.
![Screen Shot 2020-06-02 at 9 30 10 AM](https://user-images.githubusercontent.com/1435716/83545161-ac988780-a4b3-11ea-9e7d-2d21118c3cfb.png)
![Screen Shot 2020-06-02 at 9 29 59 AM](https://user-images.githubusercontent.com/1435716/83545165-ae624b00-a4b3-11ea-9b16-70646920443e.png)

**Comment by jonahwilliams** [comment]
I agree, doesn't seem like a tooling change could have affected a rendering benchmark. It's much more likely something is wrong with device or machine (native dialog?)

**Comment by kf6gpe** [comment]
These have recovered and are consistently within the baseline now, so I'm going to close this.
