### ISSUE TITLE
'attrib' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by KharcheNikhil** [flutter/flutter#58507]
## Steps to Reproduce

Create flutter project in Android Studio using flutter v1.17.2

**Expected results:** 
It should compile, and launch default "Flutter Demo Home Page"

**Actual results:** 
FAILURE: Build failed with an exception.

**Logs:**
```bash
'attrib' is not recognized as an internal or external command,
operable program or batch file.

FAILURE: Build failed with an exception.

* Where:

Script '~\flutter_windows_1.17.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 661

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Exception: Gradle task assembleDebug failed with exit code 1

```

Note: Checked `attrib` is recognised command from the command prompt.

**Comment by iapicca** [comment]
Hi @KharcheNikhil 
Can you please provide your `flutter doctor -v`
and your `flutter run --verbose` 
Thank you

**Comment by VladyslavBondarenko** [comment]
@KharcheNikhil 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
