### ISSUE TITLE
libtxt: Text layout engine does not round-trip intrinsic dimension precision

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5852]
Adding this code to text_painter's layout method (at the end) leads to the assert firing:

``` dart
    _paragraph.layout(new ui.ParagraphConstraints(width: _paragraph.maxIntrinsicWidth));
    assert(h == _paragraph.height);
```

**Comment by eseidelGoogle** [comment]
I'm not sure what the right milestone is for this.  This is a core bug in our text system which causes a bunch of workarounds in the framework right?

**Comment by Hixie** [comment]
A few, but not that many. This is something we should fix but it's not urgent.

**Comment by GaryQian** [comment]
This is caused by https://github.com/flutter/flutter/issues/31707,

@Rusino Things to keep in mind for SkParagraph

**Comment by chinmaygarde** [comment]
We don't use libTXT anymore.
