### ISSUE TITLE
[image_picker_for_web] Can't select some video file types (3gp, mp4, possibly others...)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#58532]
1. Compile the `example` app of the `image_picker` plugin for web. 
2. In Safari, try to pick a .mp4 file from your disk. It'll be grayed out.

It seems `video/*` is not enough as the value of the `accept` parameter for Safari (at least in the desktop version).

What's a sensible value for `accept` for Safari browsers?

Maybe related: https://github.com/flutter/flutter/issues/58527

**Comment by Makapre** [comment]
Created a PR at [flutter/plugins#3007](https://github.com/flutter/plugins/pull/3007).
It should solve the selecting issues when using safari.

**Comment by ditman** [comment]
Thanks @Makapre! I'll take a look!
