### ISSUE TITLE
[metrics_center] Productionize metrics center 

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#58542]
Per @liyuqian , once https://github.com/liyuqian/metrics_center is properly reviewed, add it to flutter/packages, publish on pub.dev.

**Comment by pedromassangocode** [comment]
Hi @digiter 
This package seems to be currently [available on pub.dev](https://pub.dev/packages/metrics_center), it misses some documentation but this seems unrelated to this issue.

Can you please confirm that this is now fixed?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
