### ISSUE TITLE
ListView.separated error

### ISSUE THREAD

**Issue by pilojanmobile** [flutter/flutter#58556]
## Steps to Reproduce

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Container(constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
When the exception was thrown, this was the stack: 
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:4901:16)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4560:14)
#4      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:4905:5)
#5      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:4949:5)
#6      ProxyElement.updated (package:flutter/src/widgets/framework.dart:4876:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4901 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
The relevant error-causing widget was: 
  Container file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:31:22
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 6 of 509 libraries in 3,876ms.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4977 pos 14: '_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///C:/Users/pc/Downloads/Documents/buzzarlkvenderpp/lib/Screens/ViewMoreDashboard.dart:22:22
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4977:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4979:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1944:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4560:14)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#f48e3 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 733.1, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 733.1, remainingCacheExtent: 983.1, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 1232.6, paintExtent: 733.1, maxPaintExtent: 1232.6, hasVisualOverflow: true, cacheExtent: 983.1)
...    scrollExtent: 1232.6
...    paintExtent: 733.1
...    maxPaintExtent: 1232.6
...    hasVisualOverflow: true
...    cacheExtent: 983.1
...  currently live children: 0 to 9
RenderObject: RenderSliverList#f48e3 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 733.1, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 733.1, remainingCacheExtent: 983.1, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 1232.6, paintExtent: 733.1, maxPaintExtent: 1232.6, hasVisualOverflow: true, cacheExtent: 983.1)
    scrollExtent: 1232.6
    paintExtent: 733.1
    maxPaintExtent: 1232.6
    hasVisualOverflow: true
    cacheExtent: 983.1
  currently live children: 0 to 9
...  child with index 0: RenderIndexedSemantics#a7573 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=0; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 100008.0)
...    index: 0
...    child: RenderRepaintBoundary#766f7 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#d8e60
...        engine layer: OffsetEngineLayer#3a57a
...        offset: Offset(0.0, 0.0)
...      size: Size(411.4, 100008.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPhysicalShape#22f68 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: PhysicalModelLayer#1faee
...          engine layer: PhysicalShapeEngineLayer#4fabc
...          elevation: 2.0
...          color: Color(0xfffafafa)
...        size: Size(411.4, 100008.0)
...        elevation: 2.0
...        color: Color(0xfffafafa)
...        shadowColor: Color(0xfffafafa)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#4a5f5 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 100008.0)
...  child with index 1: RenderRepaintBoundary#7ee1e relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=1; layoutOffset=150.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    layer: OffsetLayer#40b23
...      engine layer: OffsetEngineLayer#2b555
...      offset: Offset(0.0, 150.0)
...    size: Size(411.4, 16.0)
...    metrics: 0.0% useful (1 bad vs 0 good)
...    diagnosis: insufficient data to draw conclusion (less than five repaints)
...    child: RenderConstrainedBox#db37a relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 16.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=16.0)
...      child: RenderPositionedBox#45e0a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=16.0)
...        size: Size(411.4, 16.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderPadding#be63a relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 8.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=16.0)
...          size: Size(411.4, 0.0)
...          padding: EdgeInsets.zero
...          textDirection: ltr
...  child with index 2: RenderIndexedSemantics#d6e0f relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=2; layoutOffset=166.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 171.0)
...    index: 1
...    child: RenderRepaintBoundary#6ce00 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#493ba
...        engine layer: OffsetEngineLayer#01e50
...        offset: Offset(0.0, 166.0)
...      size: Size(411.4, 171.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPhysicalShape#eb164 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: PhysicalModelLayer#10887
...          engine layer: PhysicalShapeEngineLayer#6f72a
...          elevation: 2.0
...          color: Color(0xfffafafa)
...        size: Size(411.4, 171.0)
...        elevation: 2.0
...        color: Color(0xfffafafa)
...        shadowColor: Color(0xfffafafa)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#63e97 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 171.0)
...  child with index 3: RenderRepaintBoundary#b6a52 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=3; layoutOffset=337.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    layer: OffsetLayer#c9eae
...      engine layer: OffsetEngineLayer#a37d3
...      offset: Offset(0.0, 337.0)
...    size: Size(411.4, 16.0)
...    metrics: 0.0% useful (1 bad vs 0 good)
...    diagnosis: insufficient data to draw conclusion (less than five repaints)
...    child: RenderConstrainedBox#92e04 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 16.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=16.0)
...      child: RenderPositionedBox#e0463 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=16.0)
...        size: Size(411.4, 16.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderPadding#6b272 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 8.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=16.0)
...          size: Size(411.4, 0.0)
...          padding: EdgeInsets.zero
...          textDirection: ltr
...  child with index 4: RenderIndexedSemantics#9fccf relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=4; layoutOffset=353.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 171.0)
...    index: 2
...    child: RenderRepaintBoundary#7b8f0 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#89945
...        engine layer: OffsetEngineLayer#e9319
...        offset: Offset(0.0, 353.0)
...      size: Size(411.4, 171.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPhysicalShape#be502 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: PhysicalModelLayer#3c924
...          engine layer: PhysicalShapeEngineLayer#20647
...          elevation: 2.0
...          color: Color(0xfffafafa)
...        size: Size(411.4, 171.0)
...        elevation: 2.0
...        color: Color(0xfffafafa)
...        shadowColor: Color(0xfffafafa)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#3d0a3 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 171.0)
...  child with index 5: RenderRepaintBoundary#b43c1 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=5; layoutOffset=524.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    layer: OffsetLayer#f2b9a
...      engine layer: OffsetEngineLayer#5b332
...      offset: Offset(0.0, 524.0)
...    size: Size(411.4, 16.0)
...    metrics: 0.0% useful (1 bad vs 0 good)
...    diagnosis: insufficient data to draw conclusion (less than five repaints)
...    child: RenderConstrainedBox#8ba24 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 16.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=16.0)
...      child: RenderPositionedBox#7c149 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=16.0)
...        size: Size(411.4, 16.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderPadding#3c2e6 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 8.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=16.0)
...          size: Size(411.4, 0.0)
...          padding: EdgeInsets.zero
...          textDirection: ltr
...  child with index 6: RenderIndexedSemantics#e72fc relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=6; layoutOffset=540.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 150.0)
...    index: 3
...    child: RenderRepaintBoundary#deebd relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#66861
...        engine layer: OffsetEngineLayer#6a449
...        offset: Offset(0.0, 540.0)
...      size: Size(411.4, 150.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPhysicalShape#8267d relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: PhysicalModelLayer#4f871
...          engine layer: PhysicalShapeEngineLayer#4d642
...          elevation: 2.0
...          color: Color(0xfffafafa)
...        size: Size(411.4, 150.0)
...        elevation: 2.0
...        color: Color(0xfffafafa)
...        shadowColor: Color(0xfffafafa)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#bd341 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 150.0)
...  child with index 7: RenderRepaintBoundary#c054a relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=7; layoutOffset=690.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    layer: OffsetLayer#a5fa1
...      engine layer: OffsetEngineLayer#d92d0
...      offset: Offset(0.0, 690.0)
...    size: Size(411.4, 16.0)
...    metrics: 0.0% useful (1 bad vs 0 good)
...    diagnosis: insufficient data to draw conclusion (less than five repaints)
...    child: RenderConstrainedBox#7db85 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 16.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=16.0)
...      child: RenderPositionedBox#7940e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=16.0)
...        size: Size(411.4, 16.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderPadding#0f3fe relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 8.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=16.0)
...          size: Size(411.4, 0.0)
...          padding: EdgeInsets.zero
...          textDirection: ltr
...  child with index 8: RenderIndexedSemantics#6218a relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=8; layoutOffset=706.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 171.0)
...    index: 4
...    child: RenderRepaintBoundary#260da relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#8c273
...        engine layer: OffsetEngineLayer#ca3a8
...        offset: Offset(0.0, 706.0)
...      size: Size(411.4, 171.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPhysicalShape#b0efd relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: PhysicalModelLayer#6b7cf
...          engine layer: PhysicalShapeEngineLayer#177e8
...          elevation: 2.0
...          color: Color(0xfffafafa)
...        size: Size(411.4, 171.0)
...        elevation: 2.0
...        color: Color(0xfffafafa)
...        shadowColor: Color(0xfffafafa)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#06b12 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 171.0)
...  child with index 9: RenderRepaintBoundary#d44a0 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: index=9; layoutOffset=877.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    size: Size(411.4, 16.0)
...    usefulness ratio: no metrics collected yet (never painted)
...    child: RenderConstrainedBox#d5778 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 16.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=16.0)
...      child: RenderPositionedBox#755c6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=16.0)
...        size: Size(411.4, 16.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderPadding#b43c8 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 8.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=16.0)
...          size: Size(411.4, 0.0)
...          padding: EdgeInsets.zero
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

[√] Flutter (Channel master, v1.18.0-6.0.pre.26, on Microsoft Windows [Version 10.0.18362.836], locale en-SG)
    • Flutter version 1.18.0-6.0.pre.26 at C:\flutter
    • Framework revision 846e8fe812 (7 weeks ago), 2020-04-15 03:21:14 +0200
    • Engine revision deef2663ac
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at G:\sdk\sdk
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = G:\sdk\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```
```

</details>

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
