### ISSUE TITLE
[Linux] Warning messages output after closing Menubar window and clicking FAB

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#58561]
## Steps to Reproduce

This is a trivial problem.
I think it is better to fix menubar plugin. And I can send a PR, but would you fix this trivial issue?

1. $ git clone https://github.com/google/flutter-desktop-embedding.git
2. $ cd flutter-desktop-embedding/testbed
3. $ flutter run -d linux
4. Close menubar window.
5. Click FAB

**Expected results:** 

No warning messages.

**Actual results:** 

Warnings is output each time you click.

```
(testbed:20795): GLib-GObject-WARNING **: 21:11:03.990: invalid unclassed pointer in cast to 'GtkContainer'

(testbed:20795): Gtk-CRITICAL **: 21:11:03.990: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(testbed:20795): GLib-GObject-WARNING **: 21:11:03.990: invalid unclassed pointer in cast to 'GtkMenuShell'

(testbed:20795): Gtk-CRITICAL **: 21:11:03.990: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(testbed:20795): GLib-GObject-WARNING **: 21:11:03.994: invalid cast from 'GtkMenuItem' to 'GtkMenuShell'

(testbed:20795): Gtk-CRITICAL **: 21:11:03.995: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed
```

Thank you.

**Comment by stuartmorgan** [comment]
> git clone https://github.com/google/flutter-desktop-embedding.git

That repository—which is what the menubar plugin is from—is not part of the Flutter project, and has its own issue tracker. This is not the right place to file bugs about FDE plugins.

You can file an issue there if you like, but given that the separate window is a temporary hack that won't be necessary after the switch to a GTK embedding, minor improvements to the (terrible) experience it provides are not going to be a priority. It was implemented purely for experimentation with menus on Linux.

**Comment by HidenoriMatsubayashi** [comment]
@stuartmorgan 

Yes, I know you are in the works of switching to GTK.
I'm sorry. It won't happen again. From now on, I will ignore GLFW specific issues.
