### ISSUE TITLE
Hope that PageView has a parameter to control the speed of translate Animation

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#58576]
When swiping fast in PageView，the PageView will translate to next page or previous page. And it will have an animation .So I hope to get a parameter to control the  speed of translate animation...

**Comment by VladyslavBondarenko** [comment]
Hi @luckysmg 
please follow up on https://github.com/flutter/flutter/issues/55103,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
