### ISSUE TITLE
Image.asset will block UI thread when load large image

### ISSUE THREAD

**Issue by zljj0818** [flutter/flutter#58572]
If Image.asset load a large image(> 3MB),  it will block ui thread ~200ms in Pixel XL, when PlatformMessageResponseDart::Complete

**Comment by iapicca** [comment]
Hi @zljj0818 
Can you please describe the issue more in details
and provide your `flutter doctor -v`,
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Please refrain from posting pictures if not necessary.
Thank you

**Comment by zljj0818** [comment]
The root casue is std::vector has performance issue for large size.

**Comment by zljj0818** [comment]
@liyuqian

**Comment by liyuqian** [comment]
Thanks for reporting @zljj0818 ! Do you have a minimal Flutter app that I can use to quickly reproduce this issue, or do you have a trace that shows what happened on the UI thread?

**Comment by jason-simmons** [comment]
I tried measuring the `PlatformMessageResponseDart::Complete` UI thread task.  On a Moto G4 in profile mode using a 3.6MB asset the task ran in 30-40ms.

`PlatformMessageResponseDart` needs to copy the asset data into a buffer whose lifetime can be owned by Dart.

`PlatformMessageResponseDart` is creating a `std::vector` to hold the buffer:
    https://github.com/flutter/engine/blob/master/lib/ui/window/platform_message_response_dart.cc#L41

The `std::vector` data is being initialized during construction even though it is immediately overwritten.  We could save time by using a `malloc` buffer or having `Dart_NewTypedData` allocate the buffer.

**Comment by zljj0818** [comment]
@jason-simmons Yes, PlatformMessageResponseDart::Complete do not consume time, std::vector does, see my comment above.
You can just test std::vector(3600000).
I have fixed this, it will reduce to ~5ms  on Pixel XL

**Comment by zljj0818** [comment]
I will create a pull request

**Comment by zljj0818** [comment]
@jason-simmons  I have created pull request: https://github.com/flutter/engine/pull/18808
