### ISSUE TITLE
[Sentry] Documentation mismatch

### ISSUE THREAD

**Issue by Sp4Rx** [flutter/flutter#58575]
The sentry documentation [here](https://github.com/flutter/sentry#usage) says use `sentry: ">=4.0.0 <5.0.0"` which is not available yet.

And on the [pub.dev/sentry](https://pub.dev/packages/sentry#usage) it says use `sentry: ">=3.0.0 <4.0.0"`

Please update the documentation or release the updated version.

**Comment by Roshan13046** [comment]
> The sentry documentation [here](https://github.com/flutter/sentry#usage) says use `sentry: ">=4.0.0 <5.0.0"` which is not available yet.
> 
> And on the [pub.dev/sentry](https://pub.dev/packages/sentry#usage) it says use `sentry: ">=3.0.0 <4.0.0"`
> 
> Please update the documentation or release the updated version.

The versions are correctly mentioned in the pub.dev/sentry. This issue must be closed now.

**Comment by darshankawar** [comment]
I don't see the reference to use the sdk environment anywhere in https://pub.dev/packages/sentry/install or https://github.com/getsentry/sentry-dart#usage

Closing this as fixed. If anybody disagrees, write in comments and I'll reopen it.
