### ISSUE TITLE
Explicit policy for what platform are required for PullRequests of new features

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#58585]
At the moment neither the [style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) nor the [contributor guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) specify for which platforms a feature in a pull request has to be available to be merged. 

In https://github.com/flutter/plugins/pull/1400 it's argued that Android, iOS and web are all three required. If that's the official policy that should be stated in one of the linked documents so that developers don't get pull request denied for reasons of unstated policy.

If this isn't policy then the policy should be also explicitely say that pull requests that only implement some platforms like Android+iOS are welcome to encourage developers to contribute those. 

Given that the amount of features in Flutters plugins are at the moment it's weakest point I would prefer a policy that's welcoming of pull requests that implement a feature in Android + iOS and that doesn't require web, but in any case there should be an official policy.

**Comment by wanjm** [comment]
it is really strange that one feature is blocked by the platform support which is not released ;

**Comment by stuartmorgan** [comment]
We should define and document policy around this. Just to clarify for background/context though, having looked at the issue:

> In [flutter/plugins#1400](https://github.com/flutter/plugins/pull/1400) it's argued that Android, iOS and web are all three required.

1. The person making this argument was not a repository maintainer, so that just was an expression of one person's personal opinion, not a policy statement.
2. Their concern appears to have been that the PR *actively broke* web, not just that it didn't include web support.

> so that developers don't get pull request denied for reasons of unstated policy.

This did not actually happen.

**Comment by stuartmorgan** [comment]
I've added an initial writeup of what I expect the policy to be going forward: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#platform-support. As always, we'll update and adjust based on experience.
