### ISSUE TITLE
flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882, While building APK

### ISSUE THREAD

**Issue by z85510** [flutter/flutter#58583]
**When I'm trying to build apk I got some errors: `flutter build apk`** 

```
Dart snapshot generator failed with exit code -6                        
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/aref/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/aref/development/flutter/bin/flutter'' finished with non-zero exit value 1

```

**I've tried `flutter run --verbose` and there is no issue.
I've tried `flutter build apk --debug` and there is no issue.
I've tried `flutter build apk --target-platform android-arm` and there is no issue.**

line 882 in flutter.gradle : 
```

project.exec {
            executable flutterExecutable.absolutePath
            workingDir sourceDir
            if (localEngine != null) {
                args "--local-engine", localEngine
                args "--local-engine-src-path", localEngineSrcPath
            }
            if (verbose) {
                args "--verbose"
            } else {
                args "--quiet"
            }
            args "assemble"
            args "--depfile", "${intermediateDir}/flutter_build.d"
            args "--output", "${intermediateDir}"
            if (!fastStart || buildMode != "debug") {
                args "-dTargetFile=${targetPath}"
            } else {
                args "-dTargetFile=${Paths.get(flutterRoot.absolutePath, "examples", "splash", "lib", "main.dart")}"
            }
            args "-dTargetPlatform=android"
            args "-dBuildMode=${buildMode}"
            if (extraFrontEndOptions != null) {
                args "-dExtraFrontEndOptions=${extraFrontEndOptions}"
            }
            if (splitDebugInfo != null) {
                args "-dSplitDebugInfo=${splitDebugInfo}"
            }
            if (treeShakeIcons == true) {
                args "-dTreeShakeIcons=true"
            }
            if (dartObfuscation == true) {
                args "-dDartObfuscation=true"
            }
            if (dartDefines != null) {
                args "--DartDefines=${dartDefines}"
            }
            if (extraGenSnapshotOptions != null) {
                args "--ExtraGenSnapshotOptions=${extraGenSnapshotOptions}"
            }
            args ruleNames
        }
```
```

[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-IR)
    • Flutter version 1.17.2 at /Users/aref/development/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aref/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • ANDROID_HOME = /Users/aref/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Pixel 4 • 9B021FFAZ00AKZ • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by z85510** [comment]
I found the solution : 
[https://github.com/simolus3/moor/issues/581#issuecomment-631930517](url)

**Comment by trapeye** [comment]
I didn't use that moor_ffi, still get same error

**Comment by starboy2102** [comment]
> I found the solution :
> downgrade to `moor_ffi: ^0.5.0`

Elaborate this solution please

**Comment by neezystudio** [comment]
> I found the solution :
> downgrade to `moor_ffi: ^0.5.0`

please elaborate

**Comment by chaochaox1990** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)


* Where:
Script '/Users/limi/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/limi/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

**Comment by chaochaox1990** [comment]
I just upgrade from 1.12.13 to 1.17.5. same error

**Comment by DigaoParceiro** [comment]
A solution can be:

1. Go to your `flutter/packages` folder on your computer
2. Make a backup of the folder `flutter_tools` folder, rename it to any name you want
3. Download the [flutter_tools](https://github.com/flutter/flutter/tree/master/packages/flutter_tools) zip folder and unzip on the same `packages` directory
4. Try again, if worked, delete the renamed folder, if not, name it as `flutter_tools` again

**Comment by DigaoParceiro** [comment]
1. Go to your `flutter/packages` folder on your computer
2. Make a backup of `flutter_tools` folder, rename it to any name you want
3. Download the [flutter_tools](https://github.com/flutter/flutter/tree/master/packages/flutter_tools) zip folder and unzip on the same `packages` directory
4. Try again, if worked, delete the renamed folder of item 2, if not, name it as `flutter_tools` again

**Comment by z85510** [comment]
I got this error because of moor library and when I downgrade it the issue disappeared.
so I don't know exactly what's the problem with that version of the library but you can use the new version and there is no problem anymore

**Comment by victor1409** [comment]
@z85510 
Can you help me with the location of the directory to downgrade it, I can't do it, I have the same problem you had, thanks for your contribution

**Comment by amikof** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by victor1409** [comment]
@amikof 
what is that ?

**Comment by MaanasNair** [comment]
@victor1409 in the pubspec.yaml file, under dependencies, you can find moor_ffi, just change its version to ^0.5.0

**Comment by SilvesterLi** [comment]
I delete the build/app dictionary and the problem solved

**Comment by elinonga** [comment]
The error is caused by a library/package that you recently used... Just downgrade the version of that library/package and you'll be fine

**Comment by joy2012bd** [comment]
Same issue when build apk. I have used 10 libraries. Confused which library need to downgrade. Any suggestion?

**Comment by SilvesterLi** [comment]
> Same issue when build apk. I have used 10 libraries. Confused which library need to downgrade. Any suggestion?

try to delete the build/app folder, I think it will be helpful.

**Comment by multiarts** [comment]
Also check if you have any asset (image) with spaces in the name, eg: image a.jpg
It has to be image_a.jpg, here the error caused was due to that.

**Comment by joy2012bd** [comment]
> > Same issue when build apk. I have used 10 libraries. Confused which library need to downgrade. Any suggestion?
> 
> try to delete the build/app folder, I think it will be helpful.

I did that before posting comment. Not worked for me.

**Comment by joy2012bd** [comment]
> Also check if you have any asset (image) with spaces in the name, eg: image a.jpg
> It has to be image_a.jpg, here the error caused was due to that.

I have checked. There is no space in the image name.

**Comment by apps-transround** [comment]
Via **flutter build -v apk**    more meaningful messages come up.
For example they indicated that (since I use dynamic icon data) --no-tree-shake-icons should be added and 

  **flutter build -v apk --no-tree-shake-icons**

is working for me.

**Comment by MaanasNair** [comment]
@apps-transround <h3>oh!, Let me check..</h3>

**Comment by MaanasNair** [comment]
@apps-transround <h4>Yes, it really works.. For me it works, Thank you! 😉<h4>
