### ISSUE TITLE
Issues with image_picker library support for web

### ISSUE THREAD

**Issue by mayank-dhanawade** [flutter/flutter#58582]
In PR https://github.com/flutter/plugins/pull/2767 it is mentioned that it has been fixed for web but i do not see any code for web added in the library documentation. Is it really fixed? if so can someone provide me with examples of using it on web as well as mobile.

**Comment by TahaTesser** [comment]
Mentioned PR is closed for https://github.com/flutter/plugins/pull/2802 and it is still open
Please wait for it to be merged and new release of` image_picker` [Reference](https://github.com/flutter/plugins/pull/2767#issuecomment-635692940)

if you disagree please write in the comments and I will reopen it. 
Thank you
