### ISSUE TITLE
BorderRadius.circular() should be a const constructor

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#58595]
I multiple times tried adding const to BorderRadius.circular only to get an error. It's not clear to me why BorderRadius.circular can't be a const constructor.

```dart
  BorderRadius.circular( double radius) : this.all(
    Radius.circular(radius),
  );

```
Given that this.all and Radius.circular are both const constructors there should be a way for BorderRadius.circular to be too. I multiple times tried adding const to BorderRadius.circular only to get an error.

**Comment by Zazo032** [comment]
This method can't be `const` because `radius` isn't `const`:
https://github.com/flutter/flutter/pull/52309
https://github.com/flutter/flutter/pull/54654

**Comment by ChristianKleineidam** [comment]
It seems to me that radius is a double. Why can't a double be const?

**Comment by ChristianKleineidam** [comment]
const EdgeInsets.all(double value) for example can take a double and still be const.

**Comment by jonahwilliams** [comment]
You're certainly free to try for yourself! But it definitely still can't be const.

The reason is simply that a `const` constructor is not allowed to call arbitrary functions/constructors.  In this case, Radius.circular makes it non-const as does this.all
