### ISSUE TITLE
error running my app using my iphone6 in AndroidStudio

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#58601]
Cannot run my app using my iphone6 in AndroidStudio. But I can run my app using xcode. Any changes since feb 2020 or someting wrong on AndroidStudio. Any help please?

**Error:**
```
Launching lib/main.dart on Mobil iPhone’u in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ********
Running Xcode build...
Xcode build done.                                           24.8s
Could not find the built application bundle at build/ios/iphoneos/Runner.app.
Error launching application on Mobil iPhone’u.
```

**flutter doctor -v**
yazi-MBP ios % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-CY)
    • Flutter version 1.17.2 at /Users/********/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/********/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Mobil iPhone’u • 98e860*****c714 • ios • iOS 12.4.6

! Doctor found issues in 1 category.

**Comment by NTMS2017** [comment]
Also iphonesimulator failed. :(

```
Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...                                              2.7s
Running Xcode build...
Xcode build done.                                           77.4s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 11.
```

**Comment by TahaTesser** [comment]
Hi @NTMS2017 
Did your change app name in XCode displayname? It should be called Runner

<img width="666" alt="Screenshot 2020-06-04 at 2 10 15 PM" src="https://user-images.githubusercontent.com/48603081/83734810-22941e80-a66d-11ea-99a2-a6c3c7b79bee.png">

Please check this [solution](https://github.com/flutter/flutter/issues/41793#issuecomment-537609269)

Thank you

**Comment by NTMS2017** [comment]
Thanks @TahaTesser it worked. But after upgrading to new stable channel Channel stable, v1.17.3 I got another error. I post another issues for that. I am closing this now. Thanks
