### ISSUE TITLE
how to convert image captured with camera to base64 

### ISSUE THREAD

**Issue by obilove** [flutter/flutter#58608]
I want to convert image captured with camera to base64 but it seems am converting the image path and not the image itself, please help me.

  File file;
  final picker = ImagePicker();
  void _choose() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);
    file = File(pickedFile.path);
    if (file != null) {
      setState(() {
        base64Encode(file.readAsBytesSync());
        print(base64Encode(Image.file(file));
      });
    }
  }

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
