### ISSUE TITLE
TextFormField not rendered properly

### ISSUE THREAD

**Issue by bhaskar8088** [flutter/flutter#58609]
Hi,

This is for flutter web.

I am trying to render TextFormField and it renders weirdly sometimes, but sometimes it renders well.
It happened to me both in local (`flutter run -d chrome`) as well as after deployment/production.

One main observation is:

I have multiple steps and this kind of issue never appears for first steps. It appears for the phone only and rarely its happening for another field in another form too.

Wrong renders:

![wrong1](https://user-images.githubusercontent.com/8342120/83665040-7dcffd80-a5e8-11ea-9354-608532f0b563.png)
![wrong2](https://user-images.githubusercontent.com/8342120/83665044-7f012a80-a5e8-11ea-8b99-7588893e7ae0.png)
![wrong3](https://user-images.githubusercontent.com/8342120/83665045-7f012a80-a5e8-11ea-8ea2-b5d381768356.png)
![wrong4](https://user-images.githubusercontent.com/8342120/83665046-7f99c100-a5e8-11ea-91af-781e6e8bda1e.png)

Correct ones:

![correct1](https://user-images.githubusercontent.com/8342120/83665055-858fa200-a5e8-11ea-9273-b70f6cb0d025.png)
![correct2](https://user-images.githubusercontent.com/8342120/83665057-86c0cf00-a5e8-11ea-8f63-3bdc64718e56.png)

Flutter doctor -v:

[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_IN)
    • Flutter version 1.19.0-1.0.pre at /home/bhaskar/flutter
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/bhaskar/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/bhaskar/Android/Sdk
    • Java binary at: /home/bhaskar/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /home/bhaskar/Desktop/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @bhaskar8088 
Can you please upgrade to latest `dev` channel and try again?

`flutter channel dev`
`flutter upgrade`
`flutter doctor -v`

If the problem persist after upgrade, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you"

**Comment by bhaskar8088** [comment]
I think its because I am in dev channel. I think beta is more stable than dev. So, I will use beta for some time and let you know if I get any issues.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
