### ISSUE TITLE
InteractiveViewer builder constructor

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#58603]
Currently, InteractiveViewer has no built-in support for generating its content on-demand.  This makes it impractical to use for very large tables due to performance.  We should add a constructor similar to [ListView.builder](https://master-api.flutter.dev/flutter/widgets/ListView/ListView.builder.html).

**Comment by shatterball** [comment]
I would really love for InteractiveViewer to support builder constructor.

**Comment by caxerx** [comment]
Love this see this to be implement.

**Comment by justinmc** [comment]
Proposal: https://github.com/flutter/flutter/pull/77414

The builder signature currently looks like this: `(BuildContext context, Rect viewport)` where the viewport is post-transformation, relative to the child, so it can be easily used to check if some widget in the child's subtree is visible or not, if its position is known.  Would that work for what you guys are expecting @caxerx @shatterball?

**Comment by caxerx** [comment]
This seems work for me, thank you for the update!

**Comment by justinmc** [comment]
Done, though I changed the `Rect` to a `Quad` so that rotated viewports can be supported.

Note that this does no automatic optimization of the children out-of-the-box.  You'll be responsible for changing the content that you return from `builder` based on the viewport.
