### ISSUE TITLE
Missing tests for cocoon APIs

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#58613]
We have migrated all cocoon APIs from GO to dart, but tests are missing for some of these APIs, such as
`/api/get-authentication-status`
`/api/get-log`
`/api/push-engine-build-status-to-github`
`/api/vacuum-clean`
`/api/public/build-status`

**Comment by digiter** [comment]
Triage: ping to get up to date information.

**Comment by godofredoc** [comment]
\cc @keyonghan is this still true?

**Comment by godofredoc** [comment]
Most of these apis got deleted after the migration to luci. Closing as obsolete.
