### ISSUE TITLE
PlatformView prevents widgets behind it from receiving hover events

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#58616]
When a PlatformView is placed on top of another widget, say a button, the button won't receive hover events:

```dart
Stack(children: <Widget>[
  RaisedButton(
    onPressed() {
      print('onPressed'); // Taps are handled correctly.
    },
    child: Text('Hover or click'),
  ),
  Positioned.fill(child: MyPlatformView(...)),
])
```

Setting the `hitTestBehavior` of the PlatformView to `PlatformViewHitTestBehavior.transparent` didn't help.

Taps and other gestures are received by the button correctly. Hover is the only one that the button isn't receiving.

cc @dkwingsmt

**Comment by goderbauer** [comment]
This is probably because we explicitly set the cursor of a platform view to "uncontrolled" expecting that the PlatformView will be in charge of change the cursor to its liking: 

https://github.com/flutter/flutter/blob/82acf02d2c5397590b1d12161729dca6bb0e6d96/packages/flutter/lib/src/rendering/platform_view.dart#L798

**Comment by goderbauer** [comment]
If we don't do that, how would we avoid that the PlatformView and Flutter fight for who is allowed to control the cursor?

**Comment by mdebbar** [comment]
That's good to know @goderbauer!

However, the issue I'm seeing prevents all hover events from reaching the button, not only the cursor. So even `hoverColor` on the button doesn't work. Is that also expected?

I think it makes sense for the default to be `MouseCursor.uncontrolled`. Could we make it overridable though? In my case, I want flutter to keep control of the cursor. I already know how to tell flutter to keep control of gestures (by setting `hitTestBehavior` to `PlatformViewHitTestBehavior.transparent` on the platform view). So I think it's reasonable for hover behavior (and mouse cursor) to be overridable too.

**Comment by dkwingsmt** [comment]
I can make the cursor customizable if there's the demand.

(I'll let you discuss if we should really allow the platform view to be transparent in terms of mouse event)

**Comment by mdebbar** [comment]
I would argue that hover events should respect hit test transparency. When I set the hit test behavior to be transparent on the platform view, it felt really weird that the button behind wasn't receiving hover, but was receiving gestures (taps, etc).
