### ISSUE TITLE
[web] page keeps redrawing if BottomNavigationBar hovered

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#58614]
## Steps to Reproduce

[navbar_flicker.zip](https://github.com/flutter/flutter/files/4725084/navbar_flicker.zip)

1. Create any page with a `BottomNavigationBar`.
2. Run it in Web.
3. Move to the navbar area with the mouse.

**Expected results:**

Steady display.

**Actual results:**

The page keeps redrawing if we hover over the navbar.

<details>
  <summary>Doc</summary>

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by deakjahn** [comment]
It's not the `BottomNavigationBar` itself, it's *any* navbar in the bottom, so the problem will most likely be in the `Scaffold` itself. A [`CubertoBottomBar`](https://pub.dev/packages/cuberto_bottom_bar) does the same.

**Comment by TahaTesser** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48603081/83738248-ad771800-a671-11ea-8910-5cb4d8227f7d.gif)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (2 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by deakjahn** [comment]
@TahaTesser Taha, did you try the repro I sent? I'm not sure you can see the rebuild with a simple text even if it happens. A network loaded image is much more visible.

**Comment by TahaTesser** [comment]
@deakjahn 
In my testing, network image doesn't reload  on hover so i wanted to show repaint boundary on hover

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48603081/83764713-e5915180-a697-11ea-9b2d-753c9896587b.gif)

**Comment by deakjahn** [comment]
Dear me, one of them elusive errors? :-)) Shall I make a video, too?

**Comment by deakjahn** [comment]
![2020-06-04-16-43-07](https://user-images.githubusercontent.com/2234271/83772464-b1ac3100-a683-11ea-91e9-751a8e3cd879.gif)

**Comment by ferhatb** [comment]
@deakjahn , can you please try with latest master, thx!.

**Comment by deakjahn** [comment]
Is this available in the latest dev that I can download as a ready-made package?

**Comment by ferhatb** [comment]
@deakjahn , see https://github.com/flutter/flutter/issues/48373. The root cause is server side setup (caching). We have reduced the flicker by keeping DOM more stable which is available in dev as well.

**Comment by deakjahn** [comment]
Just to report back: it's fixed with the current beta, too. Thanks.

**Comment by deakjahn** [comment]
@ferhatb It was very nice while it lasted but now it's back. I can't tell whether that engine revision is due to a recent change, there is no timestamp, only for the framework.

[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.19.0-4.1.pre at E:\Android\flutter-beta
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

Still, the flickering is back.
