### ISSUE TITLE
Blacklist devices in tool

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#58623]
Use case: I have a Fuchsia device on my home network that is not set up for development and never meant to be used for development. Nevertheless, the tool finds it and sometimes gets confused about it. 

I'd like to tell the tool to ignore that device when considering what to do when I type `flutter run` without specifying a device.

/cc @jonahwilliams

**Comment by christopherfujino** [comment]
> I'd rather solve this by making fuchsia opt-in

I thought it was...

**Comment by jonahwilliams** [comment]
technically you've opted in once you have downloaded the artifacts, but it should be behind a flutter config

**Comment by dnfield** [comment]
But even if I've opted into Fuchsia, what happens when a Fuchsia developer has multiple devices at home on wifi, some of which she didn't even realize were Fuchsia devices?

**Comment by jonahwilliams** [comment]
But you're describing a bug in dev_finder, it shouldn't be identifying all of those devices as candidates for local development.

**Comment by dnfield** [comment]
Maybe. Dev_finder is basically just a glorified mDNS client. Maybe this has more to do with the particular device I have here locally. 

I could also imagine that it would be frustrating to blacklist a device and then forget you did so later. I'll close this.
