### ISSUE TITLE
[devicelab][desktop] Create virtual Windows desktop machines

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#58625]
See #54295 for context.

This is specifically for the Windows portion of step 1.

**Comment by stuartmorgan** [comment]
This should be able to use the same LUCI image that's being used for the `flutter/plugins` e2e Windows tests.

**Comment by stuartmorgan** [comment]
@godofredoc Test PR for running sharded tests of Windows builds (also includes macOS and Linux): https://github.com/flutter/flutter/pull/67072 It fails due to not having VS installed (see [doctor output](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867613348103605824/+/steps/flutter_doctor/0/stdout) and [build failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867613348103605824/+/steps/run_test.dart_for_build_tests_shard_and_subshard_1_last/0/stdout) with "Unable to find suitable Visual Studio toolchain.") Can we run this with the same image we're using for flutter/plugins e2e tests?

**Comment by godofredoc** [comment]
Recipe change: https://flutter-review.googlesource.com/c/recipes/+/7900

**Comment by godofredoc** [comment]
Here is a link to the windows build using #67072 https://chromium-swarm.appspot.com/task?id=4f6188c502109510

**Comment by godofredoc** [comment]
@stuartmorgan can we close this one?

**Comment by stuartmorgan** [comment]
Yes, the latest run of my Windows PR was green and shows it having successfully built gallery. Thanks!
