### ISSUE TITLE
[devicelab][desktop] Create virtual Linux desktop machines

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#58624]
See https://github.com/flutter/flutter/issues/54295 for context.

This is specifically for the Linux portion of step 1.

**Comment by stuartmorgan** [comment]
@digiter @godofredoc In the new LUCI world, what would be the process for getting a Linux image that has [the necessary requirements](https://flutter.dev/desktop#additional-linux-requirements)? I'm assuming it's no longer doing GCE VM configuration myself?

**Comment by stuartmorgan** [comment]
@godofredoc Following up from today's discussion, [this portion of the flutter/plugins Dockerfile](https://github.com/flutter/plugins/blob/master/.ci/Dockerfile-LinuxDesktop#L18-L23) is the set of things that we need in order to do Linux desktop builds. Could you start the process of getting those into our Linux LUCI configurations?

**Comment by stuartmorgan** [comment]
Test PR adding desktop builds of flutter_gallery to the sharded tests here: https://github.com/flutter/flutter/pull/67072. It gets all the way to trying to build for Linux and failing because CMake isn't available, so it should work to test bot configurations against.

**Comment by godofredoc** [comment]
PR to add the new dependencies to build_tests:

https://github.com/flutter/infra/pull/250

This also requires changes at the system level to install gtk libraries that will propagate with a ETA 10/26 end of the day.

**Comment by stuartmorgan** [comment]
Linux build_tests succeeded on https://github.com/flutter/flutter/pull/68658!
