### ISSUE TITLE
Trying to build for ios 11.0, but plugin recognizes 8.0 as deployment target

### ISSUE THREAD

**Issue by llullanqui** [flutter/flutter#58634]
Hi,
Me and my team are developing an app, and we're having some trouble when running the command `flutter build ios`. We use a package called [wmc_personalized_plugin](https://pub.dev/packages/wmc_personalized_plugin) made by an external vendor, and it, internally uses a swift package called 'AlamoFire'.

We run into this error:

```
Building com.example.proyectoPrueba for device (ios-release)...
Signing iOS app for device deployment using developer identity: "Apple Development: Jaime Vasquez (NWP7V4DS9A)"
Running pod install...                                              1.7s
Running Xcode build...                                                  
                                                   
Xcode build done.                                            3.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    warning: Multiple targets match implicit dependency for linker flags '-framework Reachability'. Consider adding an explicit dependency on the
    intended target to resolve this ambiguity. (in target 'Runner' from project 'Runner')
    warning: Multiple targets match implicit dependency for linker flags '-framework Reachability'. Consider adding an explicit dependency on the
    intended target to resolve this ambiguity. (in target 'Runner' from project 'Runner')
    /Library/Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/wmc_personalized_plugin-1.0.0/ios/Classes/ApiWmcModule.swift:10:8: error: compiling
    for iOS 8.0, but module 'Alamofire' has a minimum deployment target of iOS 10.0:
    /Users/jaimevasquez/Documents/bivi/proyecto_prueba/build/ios/Release-iphoneos/Alamofire/Alamofire.framework/Modules/Alamofire.swiftmodule/armv7-appl
    e-ios.swiftmodule
    import Alamofire
           ^
    /Library/Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/wmc_personalized_plugin-1.0.0/ios/Classes/ApiWmcModule.swift:10:8: error: compiling
    for iOS 8.0, but module 'Alamofire' has a minimum deployment target of iOS 10.0:
    /Users/jaimevasquez/Documents/bivi/proyecto_prueba/build/ios/Release-iphoneos/Alamofire/Alamofire.framework/Modules/Alamofire.swiftmodule/arm64-appl
    e-ios.swiftmodule
    import Alamofire
           ^
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

We already tried changing the deployment target to 11.0 in xcode, with no success.

## Steps to Reproduce

1. Run `flutter create proyecto_prueba`.
2. Update the files as follows:

pubspec.yaml:
![image](https://user-images.githubusercontent.com/25188721/83690869-25343c80-a5b7-11ea-8c64-1bd38f8d2c1c.png)

ios folder: change deployment target to 11.0

### flutter doctor -v output:

[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.1 19B88, locale en-EC)
    • Flutter version 1.17.2 at /Library/Frameworks/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jaimevasquez/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 8 • 19712EB5-3F7A-4926-9F6E-FB6066AF54E2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by stuartmorgan** [comment]
> We use a package called wmc_personalized_plugin made by an external vendor, and it, internally uses a swift package called 'AlamoFire'.

That plugin sets its deployment target to 8.0. A plugin that has a dependency on something with a minimum of 10.0 shouldn't be targeting 8.0. You'll need to resolve this with your vendor, as it's not a Flutter issue.
