### ISSUE TITLE
InteractiveViewer has a delay in recognizing a zoom gesture when wrapped in a GestureDetector

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#58636]
When starting a pinch-to-zoom gesture on an InteractiveViewer wrapped in a GestureDetector, there is a delay before anything happens, which causes a sort of jarring jump:

![jump](https://user-images.githubusercontent.com/389558/83671625-d8863c80-a589-11ea-91ee-6d5c328bd215.gif)

This is probably caused by weird interactions between the internal and external GestureDetectors in Flutter's gesture arena.  If the `onTap` callback is removed here, the bug doesn't happen.

```dart
import 'package:flutter/material.dart';
 
void main() {
  runApp(MyApp());
}
 
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Text field',
      home: Scaffold(
        body: Center(
          child: GestureDetector(
            onTap: () {},
            child: InteractiveViewer(
              child: Container(
                width: 300,
                height: 300,
                color: Colors.limeAccent,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-4.0.pre.47, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-4.0.pre.47 at /Users/tahatesser/Code/flutter_master
    • Framework revision 28138ec5e3 (6 hours ago), 2020-06-04 00:33:01 -0400
    • Engine revision 2608f2ee9f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 54adfeb93f)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by justinmc** [comment]
This same problem also manifests itself in the [InteractiveViewer gallery demo](https://github.com/flutter/gallery/blob/master/lib/demos/reference/transformations_demo.dart).  Dragging a piece that has been placed inside the InteractiveViewer has a delay before the drag is recognized.

I noticed that if I removed the GestureDetector inside of InteractiveViewer, then the delay was gone.

**Comment by dodatw** [comment]
I have similar issue, but I did not wrap in GestureDetector.
The zoom gesture has delay.

**Comment by lazylazyllama** [comment]
I think the real issue is, that in the interaktive Viewer is not the delay, which is normal as you need a small offset to detect that it infact is a zoom gesture that is performed right now.

It's the same in google fotos.

But the difference is, that in google fotos the zoom starts from 0 when it was detected, that a zoom gesture happening right now. 

The interactive viewer in comparison calculates the zoom from when the gesture started. So when we detect that the current gesture is a zoom gesture it will not start scaling from that point on, but start scaling from when we started touching the screen. So the offset will cause it to jump to a specific zoomed in / out state instead of just starting to zoom in / out from that point on

**Comment by dodatw** [comment]
Agree!. Is there any way that we can set zoom starts form 0 like Google photos ?

**Comment by justinmc** [comment]
@lazylazyllama That is a great observation!  I really appreciate you writing that out.  Let me know what you think of this PR if you get a chance: https://github.com/flutter/flutter/pull/71497

**Comment by lazylazyllama** [comment]
@justinmc that looks really good, glad I could help :)
