### ISSUE TITLE
Request: Release Hotfix with fix for compiler bug

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#58631]
## Use case

I want to use the package moor_ffi on version 0.6.0 on the stable version of flutter.

This package currently causes a compiler bug that is fixed in https://github.com/dart-lang/sdk/commit/6ab62add0d4b6b76e214134db883e84ef4a18edd .

See also https://github.com/dart-lang/sdk/issues/41971 and https://github.com/simolus3/moor/issues/581

~~On the master branch of flutter this is fixed, but on dev, beta and stable an older version of Dart is used, which still has this issue.~~ (Now all channels except stable contain the fix)

## Proposal

I would greatly appreciate it if a hotfix with the patch for the dart compiler was released.

**Comment by dcharkes** [comment]
(2nd half of the fix https://github.com/dart-lang/sdk/commit/10c5dd0f0663649c2098599e0248e84abf55f05c.)

cc @mraleph

**Comment by knaeckeKami** [comment]
I can confirm that the current beta and dev version fixed this. 
At the time I opened the issue, the fix has only been merged into the master branch.

It a hotfix into the stable channel also planned?

**Comment by pcsosinski** [comment]
we can review it, following https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Comment by pcsosinski** [comment]
@mraleph for hotfix thoughts

**Comment by mraleph** [comment]
I assess this fix a medium risk: because it is not a 1 line change, and there was a bug already found in the fix. On the other hand we have not seen any other issues stemming from this fix for almost 2 weeks now. 

There is no trivial workaround available for users and moor seems like a popular enough package. 

How does it look like from Flutter perspective? If you want the fix based on the information I have provided - I can file CP for Dart.

**Comment by mraleph** [comment]
> but on dev, beta and stable an older version of Dart is used, which still has this issue.

FWIW all channels except `stable` contain the fix:

```
fetching information for master
  engine at 965fbbed1776545ee681cb57f3fb1d0c2000bbcb
  dart is at 2b917f5b6a0e1524516f214c6d0df49f4abfd378
fetching information for dev
  engine at e8c13aa012c915c6a290d2a85950af67303e75f9
  dart is at 5c1376615ec688c749f204f4c994c6ce4a0bb8fb
fetching information for beta
  engine at 9a28c3bcf40ce64fee61e807ee3e1395fd6bd954
  dart is at 5815449a2935fd4a0a9505fa0f7ca562a53f2465
fetching information for stable
  engine at ee76268252c22f5c11e82a7b87423ca3982e51a7
  dart is at caebd6700d5ece73b5566b33ff1daecb91dac500
master: contains 10c5dd0f0663649c2098599e0248e84abf55f05c
dev: contains 10c5dd0f0663649c2098599e0248e84abf55f05c
beta: contains 10c5dd0f0663649c2098599e0248e84abf55f05c
stable: does not contain 10c5dd0f0663649c2098599e0248e84abf55f05c
```

**Comment by pcsosinski** [comment]
thanks @mraleph - removing hotfix: 1.17 label based on risk assessment, this will be in our next stable release.

**Comment by TaifRaoof** [comment]
this bug still appear when build ios on  Flutter (Channel stable, v1.17.5,) !!

**Comment by pcsosinski** [comment]
this bug will be fixed in the next stable release.  it is already fixed in beta and dev (and has been for some time.)
