### ISSUE TITLE
Build widget without widgets tree 

### ISSUE THREAD

**Issue by EthanGr** [flutter/flutter#58643]
i wanna make screen my some screens in the separate isolate, where i wanna something like MyWidget().build().toImage()

**Comment by EthanGr** [comment]
I wanna build my widgets tree without use it one some screen like 
MyWidget().build()

this widget will not use in widgets tree, but instead he will create own tree. It help me for create screenshot some screens(widgets) without showing the widget to the user and without add it to GLOBAL widgets tree

**Comment by pedromassangocode** [comment]
Hi @EthanGr 
How do you think this should work for your use-case?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
