### ISSUE TITLE
When I use Flutter's compiled Framework to import the project, the app gets stuck

### ISSUE THREAD

**Issue by CoderMaoWX** [flutter/flutter#58652]
When I use Flutter to develop my own functions, the Framework compiled into iOS is introduced into the native project. I found that when starting the project, the project is likely to be directly stuck on the startup screen. Terminating the application and repeating multiple attempts to terminate the application will not succeed, because when the program stops running, the relevant business code is not executed at the startup entrance of the application, and the console does not have any logs, just like the program process. Stop directly. I am a bit dazed. Sometimes during online development and debugging, the application stalls after the application is popped up, the mobile phone operating system freezes, and the mobile phone cannot be restarted. I must run out of battery to restart the phone. It is very confusing to use, how to change and analyze the reason?

**Comment by taimoorhassan-work** [comment]
This feels google-translated. please try to explain your problem in your own words (even if that's in your own language)

**Comment by TahaTesser** [comment]
Hi @CoderMaoWX 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
