### ISSUE TITLE
Giving "const asserts" a whirl

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5865]
We should be able to experiment with "const asserts". The Dart team would love our feedback.

For analyzer: https://github.com/dart-lang/sdk/issues/27142#issuecomment-243151182

tldr: "enableAssertInitializer is included in the language section of the analysis options file"

For VM: https://github.com/dart-lang/sdk/issues/24841#issuecomment-242043544

tldr: "use flag --assert-initializer."

Thanks!

**Comment by sethladd** [comment]
cc @Hixie @abarth

**Comment by sethladd** [comment]
cc @floitschG

**Comment by abarth** [comment]
This issue is in the "top customer requests" milestone.  Which customer has requested this?

**Comment by sethladd** [comment]
Mixed semantics for the Milestone. We wanted to give the Dart team feedback "ASAP", so this was put into the "sooner than later" milestone.

To help make this milestone's semantics more clear, I've moved it out. But, if we can, let's try this soonish and send feedback over.

**Comment by abarth** [comment]
I think the analyzer support might have a bug, which is making me unsure of the evaluation:

The analyzer allows this code:

```dart
  const MultiChildRenderObjectWidget({ Key key, this.children })
    : assert(children != null), assert(!children.any((Widget child) => child == null)), super(key: key);
```

But I would have expected it to be an error because https://gist.github.com/lrhn/45bdae95e017ebbf7a84bfbe26dffcae says "the expression in the assert must be a potentially compile-time constant expression".  Is this really supported?  If so, yay!  If not, it will be easier to evaluate after the bug is fixed.

**Comment by abarth** [comment]
https://github.com/abarth/flutter/commit/983be4ba7aea9395d99aafa63f63a3f80488d2b2 is my experiment so far.  The analyzer seems happy with all those changes, but I'm worried that not all the expressions in the asserts are potentially compile-time constant expression.

**Comment by eseidelGoogle** [comment]
CC @lrhn

**Comment by Hixie** [comment]
Does it run? I mean, if they're not compile-time expressions you'll presumably find out pretty quick if you try to violate the constraint at compile time and the compiler allows it.

Ideally the analyzer itself would evaluate the constants to see if they're true.

**Comment by sethladd** [comment]
cc @bwilkerson for analyzer question (https://github.com/flutter/flutter/issues/5865#issuecomment-247732333)

**Comment by abarth** [comment]
> Does it run?

I didn't hack up the engine yet to turn on the flag.

**Comment by lrhn** [comment]
Any progress?

**Comment by abarth** [comment]
@lrhn I never got an answer to my question above.  Would you expect this snippet of code to be allowed:

```dart
const MultiChildRenderObjectWidget({ Key key, this.children })
    : assert(children != null), assert(!children.any((Widget child) => child == null)), super(key: key);
```

The type of this.children is `List<Widget>`.  Specifically, I'm surprised that I can call the `any` function inside an `assert` in a `const` constructor.

**Comment by floitschG** [comment]
The `any` call is definitely not a compile-time constant, and the VM should complain when running checked mode.

The current implementation of the analyzer doesn't evaluate the expressions, yet.

**Comment by abarth** [comment]
> The current implementation of the analyzer doesn't evaluate the expressions, yet.

In that case, I'm not able to evaluate const asserts yet because the implementation isn't of sufficient quality to tell me whether a particular assert is allowed.

**Comment by lrhn** [comment]
On Thu, Oct 20, 2016 at 9:57 PM, Adam Barth <notifications@github.com>
wrote:

> @lrhn <https://github.com/lrhn> I never got an answer to my question
> above. Would you expect this snippet of code to be allowed:
>
> const MultiChildRenderObjectWidget({ Key key, this.children })    : assert(children != null), assert(!children.any((Widget child) => child == null)), super(key: key);
>
> The type of this.children is List<Widget>. Specifically, I'm surprised
> that I can call the any function inside an assert in a const constructor.
>
For the first assert, I'm not actually sure. The spec is ... indecisive.

A *potential constant expression *is one that is compile-time constant "if
all formal parameters of e’s immediately enclosing constant constructor
were treated as compile-time constants that were guaranteed to evaluate to
an integer, boolean or string value as required by their immediately
enclosing superexpression."
However `children == null` is only a compile-time constant expression if
`children` evaluates to a numeric, string, or boolean value or to null,
which I guess it doesn't.

Something can definitely slip through that spec hole: it's potentially
constant if it would be constant if children is int (which is true), but
children isn't int, so it's not actually constant, but that's not required
anywhere.

In any case, we should probably change the spec to only require one side of
`c1 == c2` to be null to allow the expression as compile-time constant, so
the expression is both potentially constant and actually constant.

Until then, you can use:

 ...: assert(!identical(children, null)), ...

which is a compile-time constant expression independent of `children` since
`identical` doesn't require specific types for the operands like `==` does.

The second assert is right out. It's not a potentially constant expression.
(The VM has some holes in its constant constructor evaluation that allows
non-constant computations to leak through, but that's a bug (
https://github.com/dart-lang/sdk/issues/392) and there are probably more
cases like it).

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by abarth** [comment]
Please let me know when there's some program I can run over my code to tell me whether my const asserts are allowed.  Until then, I'm not able to evaluate whether they're useful because I don't know what is allowed.

**Comment by sethladd** [comment]
I checked into the Dart SDK's issues. Sounds like there's a few things we can try?

From https://github.com/dart-lang/sdk/issues/27142

"As of https://codereview.chromium.org/2282233002/ the analyzer now accepts the new syntax if the flag enableAssertInitializer is included in the language section of the analysis options file."

From https://github.com/dart-lang/sdk/issues/24841#issuecomment-242043544

"I have landed an experimental implementation of assert in initializer lists, including const initializer lists, for the VM. It is guarded behind a flag --assert-initializer."

Are those sufficient to try this feature?

@abarth by "are allowed" above, did you mean "don't throw exceptions when evaluated" ?

**Comment by sethladd** [comment]
Chatted offline with @abarth . We're going to follow up on the Dart SDK's issue re: the analyzer's implementation of this feature. https://github.com/dart-lang/sdk/issues/27142

**Comment by sethladd** [comment]
Update for those following along. The analyzer should now check that "the expressions in an assert in the initializer list of a const constructor are all potentially const expressions".

We are waiting for a Dart SDK roll, in order to test this new feature again. Stand by...

**Comment by Hixie** [comment]
Will the analyzer actually check the assertions though? Because that's what would really be useful...

**Comment by bwilkerson** [comment]
No. At the moment it will only check that the expressions are potentially constant expressions.

**Comment by sethladd** [comment]
@Hixie the VM/compiler should check them at compile time, if I understand correctly. We need to pass a flag to the VM/compiler to enable this, though.

**Comment by pq** [comment]
Landed Dart SDK `1.21.0-dev.6.0` w/ 3edf44f .  I *think* you should be good to start experimenting?

**Comment by sethladd** [comment]
Thanks @pq ! Ball's in our court now.

**Comment by sethladd** [comment]
OK, did some testing.

The VM appears to evaluate asserts in const constructor initialization lists, at compile time, IF you use `--checked --assert-initializers`:

```
~/tmp $ cat const_asserts.dart 
class Foo {

  final List children;

  const Foo({ this.children })
    : assert(children != null); //, assert(!children.any((child) => child == null));

}

main() {
  new Foo(children: null);  // no failure

  const Foo(children: const []);  // no failure

  const Foo(children: null);  // failure
}
~/tmp $ dart --checked --assert-initializer const_asserts.dart 
Unhandled exception:
Unhandled exception:
'file:///Users/sethladd/tmp/const_asserts.dart': Failed assertion: line 6 pos 14: 'children != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
#2      Foo.Foo (file:///Users/sethladd/tmp/const_asserts.dart:6:14)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
'file:///Users/sethladd/tmp/const_asserts.dart': error: line 15 pos 9: error while evaluating const constructor
  const Foo(children: null);  // failure
        ^

#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Neat!

The formatter doesn't work, but maybe I'm doing it wrong:

```
~/tmp $ dartfmt --assert-initializers const_asserts.dart 
Could not find an option named "assert-initializers".

Usage: dartfmt [-n|-w] [files or directories...]

-h, --help                   Shows usage information.
    --version                Shows version information.
-l, --line-length            Wrap lines longer than this.
                             (defaults to "80")

-i, --indent                 Spaces of leading indentation.
                             (defaults to "0")

    --preserve               Selection to preserve, formatted as "start:length".
-n, --dry-run                Show which files would be modified but make no changes.
    --set-exit-if-changed    Return exit code 1 if there are any formatting changes.
-w, --overwrite              Overwrite input files with formatted output.
-m, --machine                Produce machine-readable JSON output.
    --profile                Display profile times after running.
    --follow-links           Follow links to files and directories.
                             If unset, links will be ignored.

-t, --transform              Unused flag for compability with the old formatter.
~/tmp $ dartfmt --version
0.2.13
```

Tracking at: https://github.com/dart-lang/dart_style/issues/522

The analyzer seems to work, if you turn on the feature in your .analysis_options file:

```
analyzer:
  language:
    enableAssertInitializer: true
```

and

```
~/tmp $ dartanalyzer const_asserts.dart 
Analyzing [const_asserts.dart]...
No issues found
```

And the analyzer tells the developer if they use a non-const expression in the asserts:

```
~/tmp $ dartanalyzer const_asserts.dart 
Analyzing [const_asserts.dart]...
[error] Initializer expressions in constant constructors must be constants. (/Users/sethladd/tmp/const_asserts.dart, line 6, col 41)
1 error found.
```

**Comment by bwilkerson** [comment]
@munificent My guess is that the formatter needs to be updated to respect the analysis options that impact parsing.

**Comment by sethladd** [comment]
ah, it's that it, then we're closer than I thought :)

**Comment by munificent** [comment]
Yeah, in dart_style, I need to re-apply [this patch](https://github.com/dart-lang/dart_style/commit/b5c94a86b43a5fe39470306595fd2d4675561e3e), which I [had to revert](https://github.com/dart-lang/dart_style/commit/12a34b1efc53a375e42cfd0a07b3c5badbcfcf70) because there was no public version of analyzer out that it worked with at the time.

**Comment by sethladd** [comment]
Branch for formatter is here: https://github.com/dart-lang/dart_style/tree/assert-in-initializers

To confirm, the Flutter team acknowledges that we are enabled to test this feature.

**Comment by munificent** [comment]
\o/

**Comment by sethladd** [comment]
@Hixie can begin the whirl.

**Comment by Hixie** [comment]
I have begun using this in some places. So far the main sadness is that the analyzer doesn't seem to actually check the asserts (the compiler still does).

**Comment by sethladd** [comment]
Tracking "phase two" over at https://github.com/dart-lang/sdk/issues/29268

**Comment by sethladd** [comment]
I'm understanding we gave this a whirl! Thanks to everyone that helped make it happen. Closing this for now, as Flutter is using this new language feature.

**Comment by munificent** [comment]
> this new language feature.

Wait wait wait. Just to be clear, this is *not* a new language feature. It is a *proposed* language feature *experiment*. We haven't committed to shipping it as part of the language as far as I know.

**Comment by sethladd** [comment]
I've updated my comment in https://github.com/flutter/flutter/issues/5865#issuecomment-291970735 to reflect that it's experimental and proposed. Thanks for the clarification.

**Comment by munificent** [comment]
OK, thanks. Just wanted to make sure.
