### ISSUE TITLE
centerSlice was used with a BoxFit that does not guarantee that the image is fully visible.

### ISSUE THREAD

**Issue by 308698093** [flutter/flutter#58651]
When I use centerSlice in DecorationImage, have  a problem:
centerSlice was used with a BoxFit that does not guarantee that the image is fully visible.

thanks.

**Comment by VladyslavBondarenko** [comment]
Hi @308698093 
could you provide a complete minimal reproducible code sample and your `flutter doctor -v`?

Related to https://github.com/flutter/flutter/issues/27827

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by mshenawy22** [comment]
Same problem here @TahaTesser @VladyslavBondarenko 
TO reprodue:
 child: Image.network(
                     "some image link",

                      centerSlice : Rect.fromCenter( center: Offset(1.0, 2.0), width: 4,height:4),
);

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 8kEatRadish** [comment]
Hi @308698093 
![image.png](https://i.loli.net/2021/04/21/ygnwMTKcIqbmlze.png)

S is the area that can be transformed. Make sure that the area of the material picture-S> the area of the actual display picture, so that centerSlice can work normally.

Hope it can help you.
