### ISSUE TITLE
A Document Being Saved By xcdevice * Takes up a lot of my disk

### ISSUE THREAD

**Issue by medz** [flutter/flutter#58663]
## Steps to Reproduce

1. install android studio 4
2. install flutter plugin
3. run app in Android phone

## Logs

```
```

![image](https://user-images.githubusercontent.com/5564821/83723107-b61b1e80-a670-11ea-9c9a-ad8fbba4778d.png)

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/seven/Desktop/work/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/seven/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • HUAWEI CAZ AL10 • XPUDU16C08014500 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by medz** [comment]
#56826 is a lot different from my situation. I did not run xcode and iOS compilation, but run and debug in Android studio 4. At first it filled up all my remaining 140GB, then after I uninstalled Android studio, the content was put into the recycle bin. The disk is back to normal. I re-installed Android studio4 to run native Android applications, this will not happen, and the flutter application will continue to appear this way.

**Comment by TahaTesser** [comment]
Hi @medz 
I see you're using `stable`, as mentioned by this [comment](https://github.com/flutter/flutter/issues/56826#issuecomment-637103336), switch to `master` channel and try again. 

steps the mentioned issue are these and not include xcode
```
Open Android Studio or VSCode，Make sure the flutter process is running.
Wait for the hard drive to become full.
Restart your computer.
Open the trash.
```

**Comment by awhitford** [comment]
Please note that this is still a problem.  I found this:  https://stackoverflow.com/questions/61903057/flutter-disk-full-error-a-document-being-saved-by-xcdevice

I just ran into this after plugging in my iOS Device into my Mac.  I have over 100 GB free, and it all gets eaten up.

**Comment by IhwanID** [comment]
found same problem.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
