### ISSUE TITLE
In_App_Purchase Cancelling Trial

### ISSUE THREAD

**Issue by Dfisch3r** [flutter/flutter#58677]
I tested the in_app_purchase plugin and bought one of my subscriptions (7 days free trial). 
After 4 days I canceled the subscription, but know the App doesn't recognize me anymore as subscription user. It should last 3 more days

Is this a common problem?

**Comment by royibernthal** [comment]
What's the problem exactly? Track the event via web hooks from google play / app store and do your business logic. The user should probably maintain his subscription benefits until you receive an expire notification from the web hook.

**Comment by Dfisch3r** [comment]
I found my problem. It accidentally deleted some code which was necessary. Sorry!
