### ISSUE TITLE
flutter skia --output-file foo.skp fails

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5867]
@chinmaygarde @danrubel 

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter skia --output-file false.skp

## exception

Connection closed before full header was received

```
package:http/src/io_client.dart 78                                IOClient.send.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:http/src/io_client.dart 84                                IOClient.send.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncErrorWrapperHelper
package:http/src/io_client.dart                                   IOClient.send
package:http/src/base_request.dart 116                            BaseRequest.send.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:http/src/base_request.dart                                BaseRequest.send
package:flutter_tools/src/commands/skia.dart 47                   SkiaCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/skia.dart                      SkiaCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 192         FlutterCommand._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 184                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 116         FlutterCommand.run
package:args/command_runner.dart 177                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 130                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 177  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 104                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 104                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 123  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>
```

## flutter doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision bddeada5b6 (4 weeks ago), 2016-08-15 16:10:57
    • Engine revision 9b320d8151
    • Tools Dart version 1.20.0-dev.1.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39

[✓] Connected devices
    • Nexus 5 • 07e401a0d00b3699 • android-arm
```

**Comment by danrubel** [comment]
I hooked up my Nexus 5X and tried the following:
```
examples/hello_world$ flutter run
```
then in a separate terminal
```
examples/hello_world$ flutter skia --output-file temp.skp
```
and it worked.

Based on the stacktrace above, it failed while making an http request
```
http.StreamedResponse skpResponse = await skpRequest.send();
```
Is there any way to get information about what happened in the engine when processing the request?

**Comment by eseidelGoogle** [comment]
Maybe the port wasn't correctly forwarded to my host?  I'm happy to try again.

**Comment by eseidelGoogle** [comment]
I was testing on a Nexus 5 at the time, I was attempting to produce and SKP for @chinmaygarde in https://github.com/flutter/flutter/issues/5867.
