### ISSUE TITLE
Error: RenderFlex children have non-zero flex but incoming height constraints are unbounded.

### ISSUE THREAD

**Issue by nxthaly** [flutter/flutter#58678]
Hi, I'm new with Flutter and I'm having this problem: **RenderFlex children have non-zero flex but incoming height constraints are unbounded.** I did look for ways to fix it but I can't, that's why I'm here. Hope you guys can help me out cause I'm stuck.

There's my code:

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:heyou/services/database.dart';

class FloatButtonMessagePage extends StatefulWidget {
  @override
  _FloatButtonMessagePageState createState() => _FloatButtonMessagePageState();
}

class _FloatButtonMessagePageState extends State<FloatButtonMessagePage> {

  DatabaseMethods databaseMethods = new DatabaseMethods();
  TextEditingController searchContactController = new TextEditingController();

  QuerySnapshot searchSnapshot;

  initiateSearch() {
    databaseMethods.getUserByUsername(searchContactController.text).then((val) {
      setState(() {
        searchSnapshot = val;
      });
    });
  }

  Widget searchList() {
    return searchSnapshot != null ? ListView.builder(
        shrinkWrap: true,
        itemCount: searchSnapshot.documents.length,
        itemBuilder: (context, index) {
          return SearchTile(
            userName: searchSnapshot.documents[index].data['name'],
            userEmail: searchSnapshot.documents[index].data['email'],
          );
        },
    ) : Container();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true, //CENTRALIZA O TÍTULO
        backgroundColor: Color(0xFF00acee),
        title: Text(
          'Contatos',
          style: TextStyle(
          fontSize: 28.0,
          color: Colors.white,
          ),
        ),
      ),
      
      body: Container(
        child: Column(
          children: <Widget>[
            Container(
              margin: EdgeInsets.only(top: 10.0, left: 8.0, right: 8.0),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.all(Radius.circular(60)),
                color: Color(0xFFE8E8E8),
              ),
              
              padding: EdgeInsets.symmetric(horizontal: 20.0, vertical: 5.0),
              child: Row(
                children: <Widget>[
                  Expanded(
                    child: TextField(
                      controller: searchContactController,
                      style: TextStyle(color: Colors.blueGrey,),
                      decoration: InputDecoration(
                        hintText: 'Quem você está procurando?',
                        hintStyle: TextStyle(
                          color: Colors.blueGrey,
                        ),
                        border: InputBorder.none,
                      ),
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      initiateSearch();
                    },
                    child: Container(
                      height: 40,
                      width: 40,
                      padding: EdgeInsets.all(12),
                      child: Image.asset(
                        'lib/images/search_icon.png',
                        height: 25,
                        width: 25,
                      ),
                      decoration: BoxDecoration(
                        color: Color(0xFF00acee),
                        borderRadius: BorderRadius.circular(40),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            searchList(),
          ],
        ),
      ),
    );
  }
}

class SearchTile extends StatelessWidget {

  final String userName;
  final String userEmail;
  SearchTile({this.userName, this.userEmail});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 26.0, vertical: 16.0),
      child: Row(
        children: <Widget>[
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget> [
              Text(
                userName,
                style: TextStyle(
                  color: Colors.blueGrey,
                  fontSize: 16,
                ),
              ),

              Text(
                userEmail,
                style: TextStyle(
                  color: Colors.blueGrey,
                  fontSize: 16,
                ),
              ),

              Spacer(),

              Container(
                padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
                child: Text('Message'),
                decoration: BoxDecoration(
                  color: Colors.blue,
                  borderRadius: BorderRadius.circular(30),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}`

Now, my debug console info:

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
RenderFlex children have non-zero flex but incoming height constraints are unbounded.

When a column is in a parent that does not provide a finite height constraint, for example if it is in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining space in the vertical direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child cannot simultaneously expand to fit its parent.

Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible children (using Flexible rather than Expanded). This will allow the flexible children to size themselves to less than the infinite remaining space they would otherwise be forced to take, and then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum constraints provided by the parent.

If this message did not help you determine the problem, consider using debugDumpRenderTree():
  https://flutter.dev/debugging/#rendering-layer
  http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
The affected RenderFlex is: RenderFlex#bf4c2 relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(unconstrained)
    size: MISSING
    direction: vertical
    mainAxisAlignment: start
    mainAxisSize: max
    crossAxisAlignment: start
    textDirection: ltr
    verticalDirection: down
    child 1: RenderParagraph#91a81 relayoutBoundary=up19 NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(61.0, 16.0)
        textAlign: start
        textDirection: ltr
        softWrap: wrapping at box width
        overflow: clip
        textScaleFactor: 0.9
        locale: en_US
        maxLines: unlimited
        text: TextSpan
            debugLabel: ((englishLike body1 2014).merge(blackMountainView bodyText2)).merge(unknown)
            inherit: false
            color: MaterialColor(primary value: Color(0xff607d8b))
            family: Roboto
            size: 16.0
            weight: 400
            baseline: alphabetic
            decoration: TextDecoration.none
            "juliamaria"
    child 2: RenderParagraph#4eb2d relayoutBoundary=up19 NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(103.0, 16.0)
        textAlign: start
        textDirection: ltr
        softWrap: wrapping at box width
        overflow: clip
        textScaleFactor: 0.9
        locale: en_US
        maxLines: unlimited
        text: TextSpan
            debugLabel: ((englishLike body1 2014).merge(blackMountainView bodyText2)).merge(unknown)
            inherit: false
            color: MaterialColor(primary value: Color(0xff607d8b))
            family: Roboto
            size: 16.0
            weight: 400
            baseline: alphabetic
            decoration: TextDecoration.none
            "julia@gmail.com"
    child 3: RenderConstrainedBox#b2530 NEEDS-LAYOUT NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=0.0, h=0.0)
    child 4: RenderDecoratedBox#a447e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
        constraints: MISSING
        size: MISSING
        decoration: BoxDecoration
            color: MaterialColor(primary value: Color(0xff2196f3))
            borderRadius: BorderRadius.circular(30.0)
        configuration: ImageConfiguration(bundle: PlatformAssetBundle#9ed22(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
        child: RenderPadding#3f36d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            padding: EdgeInsets(16.0, 8.0, 16.0, 8.0)
            textDirection: ltr
            child: RenderParagraph#04c2b NEEDS-LAYOUT NEEDS-PAINT
                parentData: offset=Offset(0.0, 0.0)
                constraints: MISSING
                size: MISSING
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                textScaleFactor: 0.9
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "Message"
The creator information is set to: Column ← Row ← Padding ← Container ← SearchTile ← RepaintBoundary ← IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ← SliverList ← ⋯

See also: https://flutter.dev/layout/

If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
The relevant error-causing widget was
    Column
When the exception was thrown, this was the stack
#0      RenderFlex.performLayout.<anonymous closure>
#1      RenderFlex.performLayout
#2      RenderObject.layout
#3      RenderFlex.performLayout
#4      RenderObject.layout
...
The following RenderObject was being processed when the exception was fired: RenderFlex#bf4c2 relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderFlex#bf4c2 relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(unconstrained)
    size: MISSING
    direction: vertical
    mainAxisAlignment: start
    mainAxisSize: max
    crossAxisAlignment: start
    textDirection: ltr
    verticalDirection: down
    child 1: RenderParagraph#91a81 relayoutBoundary=up19 NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(61.0, 16.0)
        textAlign: start
        textDirection: ltr
        softWrap: wrapping at box width
        overflow: clip
        textScaleFactor: 0.9
        locale: en_US
        maxLines: unlimited
        text: TextSpan
            debugLabel: ((englishLike body1 2014).merge(blackMountainView bodyText2)).merge(unknown)
            inherit: false
            color: MaterialColor(primary value: Color(0xff607d8b))
            family: Roboto
            size: 16.0
            weight: 400
            baseline: alphabetic
            decoration: TextDecoration.none
            "juliamaria"
    child 2: RenderParagraph#4eb2d relayoutBoundary=up19 NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(103.0, 16.0)
        textAlign: start
        textDirection: ltr
        softWrap: wrapping at box width
        overflow: clip
        textScaleFactor: 0.9
        locale: en_US
        maxLines: unlimited
        text: TextSpan
            debugLabel: ((englishLike body1 2014).merge(blackMountainView bodyText2)).merge(unknown)
            inherit: false
            color: MaterialColor(primary value: Color(0xff607d8b))
            family: Roboto
            size: 16.0
            weight: 400
            baseline: alphabetic
            decoration: TextDecoration.none
            "julia@gmail.com"
    child 3: RenderConstrainedBox#b2530 NEEDS-LAYOUT NEEDS-PAINT
        parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
        constraints: MISSING
        size: MISSING
        additionalConstraints: BoxConstraints(w=0.0, h=0.0)
    child 4: RenderDecoratedBox#a447e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
        constraints: MISSING
        size: MISSING
        decoration: BoxDecoration
            color: MaterialColor(primary value: Color(0xff2196f3))
            borderRadius: BorderRadius.circular(30.0)
        configuration: ImageConfiguration(bundle: PlatformAssetBundle#9ed22(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
        child: RenderPadding#3f36d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            padding: EdgeInsets(16.0, 8.0, 16.0, 8.0)
            textDirection: ltr
            child: RenderParagraph#04c2b NEEDS-LAYOUT NEEDS-PAINT
                parentData: offset=Offset(0.0, 0.0)
                constraints: MISSING
                size: MISSING
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                textScaleFactor: 0.9
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "Message"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#bf4c2 relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Row
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#799fe relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Container
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPadding#e02de relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#61b0d relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
The method 'debugAssertIsValid' was called on null.
Receiver: null
Tried calling: debugAssertIsValid()
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderShrinkWrappingViewport#87cde relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderIgnorePointer#0b477 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#4829b relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPointerListener#fa855 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#220cf relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPointerListener#83056 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: _RenderScrollSemantics#7d183 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#2daee relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#34921 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    ListView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#284f8 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Column
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#284f8 relayoutBoundary=up2 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Column
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#284f8 relayoutBoundary=up2 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Column
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#284f8 relayoutBoundary=up2 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was
    Column
════════════════════════════════════════════════════════════════════════════════

**Comment by flutterq** [comment]
All Possible working solution added [[Solved] RenderFlex children have non-zero flex but incoming height constraints are unbounded](https://fluttercorner.com/renderflex-children-have-non-zero-flex-but-incoming-height-constraints-are/)
