### ISSUE TITLE
BottomNavigationBar should not force more than one item

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#58689]
Please, change the assert to

    assert(items.length >= 1)

in the `BottomNavigationBar` constructor. It was OK earlier but with the newer [`BottomAppBar`](https://material.io/components/app-bars-bottom) design it became perfectly acceptable to have one icon on one side (eg. to the left) and a floating action button on the other (eg. to the right). You shouldn't force more than one button in the navbar any more.

**Comment by Zazo032** [comment]
If you're trying to add a `BottomAppBar`, you should use `BottomAppBar` instead of `BottomNavigationBar`. A `BottomNavigationBar` with less than 2 items makes no sense.

https://api.flutter.dev/flutter/material/BottomAppBar-class.html

```dart
Scaffold(
  bottomNavigationBar: BottomAppBar(
    color: Colors.white,
    child: bottomAppBarContents,
  ),
  floatingActionButton: FloatingActionButton(onPressed: null),
),
```

**Comment by deakjahn** [comment]
OK, I stand corrected. That's indeed what I'm trying to do but I didn't realize the `platform` package actually places a `BottomNavigationBar` *inside* the `BottomAppBar` for me and this is where the assert came from...
