### ISSUE TITLE
url_launcher Boolean for State

### ISSUE THREAD

**Issue by boyi01** [flutter/flutter#58699]
Hey,
i really like your url_launcher, i just miss on think, a function that provides the actual status, especially interessting when the usere closes the opend webpage withouth finshing the action, in my case:

I call a login page, in the background i can poll a adress that gives me feedback when the login was succesfull, the i close the with closeWebView(), but when the usere stops the Procces i have no idea how to catch that...

**Comment by iapicca** [comment]
Hi @boyi01 
I see there's an open [issue](https://github.com/flutter/flutter/issues/20034) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
