### ISSUE TITLE
[macOS] Save window size from last session

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#58697]
## Use case

If you change the window size of a Flutter macOS app, it will not be saved. The window size is everytime the same. Nearly all other programs starts with the window size from the last session.

![macOsSize_gif](https://user-images.githubusercontent.com/24459435/83792833-edeb8b80-a69b-11ea-9b24-edd38ab6b671.gif)

## Proposal
It would be nice, if Flutter macOS apps would start with the same window same as they had last session 👍

**Comment by stuartmorgan** [comment]
That's not a macOS behavior, it's an application behavior. Flutter apps that want to do this should do so, once https://github.com/flutter/flutter/issues/30736 is implemented.

**Comment by AndroidNils** [comment]
Ok, great!
