### ISSUE TITLE
Intermitent _ChunkedJsonParser.fail

### ISSUE THREAD

**Issue by mr-incredible** [flutter/flutter#58694]
I hate errors like this - intermittent!!!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

dart-lang/dart/dart: stable 2.8.4

===========================
I/flutter (31648): 1. WebClient:: 200 Response from: http://x.y.x.z:3000/api/query/ Content Length: 1589
E/flutter (31648): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unterminated string (at character 1234)
E/flutter (31648): ...4T09:08:50.000Z","quantity":1,"notes":"","partNo":"A6778","ta
E/flutter (31648):                                                                               ^
E/flutter (31648):
[38;5;244mE/flutter (31648): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1394:5)[39;49m
[38;5;244mE/flutter (31648): #1      _ChunkedJsonParser.close  (dart:convert-patch/convert_patch.dart:505:9)[39;49m
[38;5;244mE/flutter (31648): #2      _parseJson  (dart:convert-patch/convert_patch.dart:32:10)[39;49m
[38;5;244mE/flutter (31648): #3      JsonDecoder.convert  (dart:convert/json.dart:505:36)[39;49m
[38;5;244mE/flutter (31648): #4      JsonCodec.decode  (dart:convert/json.dart:153:41)[39;49m

**Comment by jonahwilliams** [comment]
Please file an issue at https://github.com/dart-lang/sdk instead of flutter/flutter

**Comment by mr-incredible** [comment]
OK, submiited under DART https://github.com/dart-lang/sdk/ so closing this issue in Flutter.

Thx
