### ISSUE TITLE
Scrollable press-drag-release gestures unconditionally fling

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#5870]
ScrollableState currently handles drag release events by starting a scroll offset animation, even when the corresponding fling gesture's velocity is below the threshold:

```
 void _handleDragEnd(DragEndDetails details) {
    final double scrollVelocity = pixelDeltaToScrollOffset(details.velocity.pixelsPerSecond);
    fling(scrollVelocity).then((Null _) {
      _endScroll(details: details);
    });
  }

  Future<Null> fling(double scrollVelocity) {
    if (scrollVelocity.abs() > kPixelScrollTolerance.velocity || !_controller.isAnimating)
      return _startToEndAnimation(scrollVelocity);
    return new Future<Null>.value();
  }
```

The `||  !_controller.isAnimating` expression causes the fling animation to be started even when the velocity is below threshold (unless there's scroll animation underway already).

**Comment by eseidelGoogle** [comment]
Curious how this manifests to the user?  Is this part of the ignored taps we seem to get?

**Comment by HansMuller** [comment]
Yes, it's one source of ignored taps.
