### ISSUE TITLE
Unable to debug flutter dart code in VS Code, Unverified Breakpoint error

### ISSUE THREAD

**Issue by mathr13** [flutter/flutter#58702]
When the code is not running, I can add breakpoint (round red circle), but as soon as it goes into debug mode, it turns into unverified breakpoint (grey hollow circle) and doesn't work at all. However, the same project works well on other systems. I've no idea what the problem is or what the solution would be. I've tried reinstalling flutter SDK numerous times, and have gone through a lot of links on SOF and GitHub regarding this, but none has been helpful enough.

Environment - VS Code, Flutter version: 1.17.2

For more details, please check SOF (I've shared "flutter doctor" and "launch.json" file there) - https://stackoverflow.com/questions/62201942/unable-to-debug-flutter-dart-code-in-vs-code-unverified-breakpoint-error

**Comment by iapicca** [comment]
Hi @mathr13 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51853) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
