### ISSUE TITLE
Cherry pick request for Gradle change

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#58717]
**Impact:** Users aren't able to build for Android if they import plugins with transitive dependencies such as:
* shared_preferences -> shared_preferences_web
* location -> location_web
* firebase_core -> firebase_core_web

**Fix:** https://github.com/flutter/flutter/pull/57907, which was checked in into master

cc @pcsosinski

**Comment by blasten** [comment]
I'm actually unable to repro this issue. I will reopen if something is clarified.

**Comment by igorakkerman** [comment]
@blasten Please see my reply in my PR:
https://github.com/flutter/flutter/pull/57907#discussion_r436297250

**Comment by pcsosinski** [comment]
@blasten I removed the CP label, please re-add if there's something we need for 1.17 here.
