### ISSUE TITLE
Expose the status of <elided> roller publicly

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#58718]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=53445&q=53445

assigned to atyfto@google.com

**Comment by kf6gpe** [comment]
Actively being worked on this week; latest upstream comments indicate further progress today.

**Comment by Hixie** [comment]
Assigning to Ray so he can chase.

**Comment by kf6gpe** [comment]
Still on  atyfto@google.com's radar as of today, but behind some higher-priority issues on the Fuchsia infra side.

**Comment by kf6gpe** [comment]
Downgrading to P3 after consultation with Anthony and others about priorities.

**Comment by kf6gpe** [comment]
Triage --- dropping priority; this is a planned-for-Q3 item, but not urgent.

**Comment by goderbauer** [comment]
infra: Do you know if this is a roller we still own?

**Comment by keyonghan** [comment]
This is obsolete.
