### ISSUE TITLE
Root widget ignores sizing

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#5872]
Example:
```
  runApp(new SizedBox(
    height: 50.0,
    child: new Container(decoration: new BoxDecoration(backgroundColor: Colors.green[500]), height: 50.0)
  ));
```

I would expect this to create a strip of green 50 pixels high. Instead, the whole screen is filled with green.

**Comment by Hixie** [comment]
The root widget passes down a tight constraint the size of the screen, so the height given to the sized box is ignored.

Wrap it in an Align or Center.

**Comment by mpcomplete** [comment]
Might be worth including this in the docs? It also seems strange that an Align breaks the sizing constraint.

**Comment by Hixie** [comment]
Yeah we should definitely document this better.

Align loosens the constraints because otherwise there would be nothing to align. That's basically the entire purpose of Align. :-)
