### ISSUE TITLE
Consider the lessons from the Jetpack Benchmark module in the devicelab

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#58730]
References:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/benchmark
https://developer.android.com/studio/profile/benchmark

There's some interesting ideas there. For example, for some microbenchmarks it might make sense for us to lock the cores; they have code that does that. They have a hack that they call "thermal throttling detection" but is really "consistent behavior detection" where they run a tiny benchmark occasionally and see if its performance is consistent, and if it isn't, they wait a bit to let the system settle before resuming the actual benchmark. We could do something similar to measure the health of our hosts and devices.

I wouldn't recommend using all their ideas. For example, in general I wouldn't recommend always locking the CPU scaling or forcing the system into special states because we really need to measure real-world performance and so we really want to know what our benchmarks are actually triggering in the real world, not in ideal locked-down conditions, even if that does mean a bit more noise in the data.

**Comment by Hixie** [comment]
cc @liyuqian

**Comment by Hixie** [comment]
This file in particular includes some interesting suggestions for how to lock the CPU scaling which would be useful for microbenchmarks:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-platform-dev-temp/benchmark/src/main/java/androidx/benchmark/AndroidBenchmarkRunner.kt

**Comment by liyuqian** [comment]
That's very helpful, thanks! Let me also attach some related resources for future reference
- [Performance testing of Flutter apps][1]. This article also discussed CPU scale locking.
- [Skia nanobench locks both CPU and GPU scaling, and disables unneeded CPU cores][2]

[1]: https://medium.com/flutter/performance-testing-of-flutter-apps-df7669bb7df7
[2]: https://github.com/google/skia/blob/e25b4472cdd9f09cd393c9c34651218507c9847b/infra/bots/recipe_modules/flavor/android.py#L135

As for the "more realistic" vs "less noisy" tradeoff, I think we can just run two copies of tests: 1 with locking, and 1 without locking. If one regressed, we can check the other to see whether it's related with locking or not.

**Comment by chinmaygarde** [comment]
We are aware of these techniques and we do core affinity update on Android as well. Beyond that, we have no plans to perform core pinning for benchmarks. But the lessons are noted.
