### ISSUE TITLE
Android uses different types of logical pixels for font sizes than for view layouts

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#5873]
https://developer.android.com/guide/topics/resources/more-resources.html#Dimension

In Android, view layout sizes are given in density-independent pixels (dp) while font sizes are given in scale-independent pixels (sp).  The difference between the two appears to be that sp are sensitive to accessibility settings for font size, while dp are not.

Does Flutter respect system accessibility settings like this when it's applying layout measurements to a view versus text?

**Comment by Hixie** [comment]
Not currently, but we certainly could.

**Comment by abarth** [comment]
After https://github.com/flutter/flutter/pull/5936, the default interpretation of a font size will be in `sp`.  We'll still need to wire up the conversion factor for sp to dp, which is https://github.com/flutter/flutter/issues/5085

**Comment by DaveShuckerow** [comment]
Nice going, guys!

![dicaprio](https://cloud.githubusercontent.com/assets/14947366/18679346/18517596-7f14-11e6-81e1-548dc7901061.gif)
