### ISSUE TITLE
Sliver/CustomScrollView have occasional floating point precision issues.

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#58745]
## Description 

![image](https://user-images.githubusercontent.com/14145407/83828969-6f7f0000-a714-11ea-84bb-15a77e7a7e47.png)

I try to add a print method into the sdk code, and breakpoint it.

https://github.com/flutter/flutter/blob/94b7ff241e6e5445b7f30215a777eb4971311797/packages/flutter/lib/src/rendering/sliver_list.dart#L294

Due to commercial projects, I can't open source this part of the code.

The main reason is that the internal item contains a GridView, and the GridView is `shrinkWrap: true`, so the GridView's height is double type. 

At present, I solved it by calculating the height of GridView and all other controls in this item and using ceilToDouble. But this calculation is complicated, so I think there should be a better solution to solve it.

---

Because of the assertion of floating-point precision, this problem will occur during the development process, causing all subsequent rendering processes to be terminated.
But because the assert does not terminate the rendering in the release, it may not cause problems in the release environment.

But in any case, I think this kind of problem may be flooded in the process of various SDKs, are there some effective solutions to avoid it?

## flutter doctor -v

<details>
[✓] Flutter (Channel unknown, v1.17.1, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Volumes/Evo512/sdk/flutter/fvm/1.17.0
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/cai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Volumes/Evo512/application/jetbrains/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/cai/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • MI 8       • b6ec3684   • android-arm64  • Android 10 (API 29)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
</details>

**Comment by iapicca** [comment]
Hi @CaiJingLong 
there's no need to share your production code,
but could you please provide a reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
