### ISSUE TITLE
update `flutter doctor` to show info about installed IDEs

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#5875]
`flutter doctor` currently checks for the existence of the atom plugin and prints out the installed version:

```
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39
```

We should change this check to be optional; if atom is not installed, change to not print anything. If it is, the text can remain as is - the version info.

/cc @danrubel

**Comment by danrubel** [comment]
If no IDE is installed, we could show ...
```
[ ] IDE support not installed. Supported IDEs include:
    • Atom - https://atom.io/
    • IntelliJ - https://www.jetbrains.com/idea/
```
We would only add IntelliJ to the list above when it is ready and remove Atom from the list sometime after that. If at least one IDE is installed then we only show information about the plugins for those installed IDEs similar to what is shown today for Atom.

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/flutter/flutter-intellij/issues/229
