### ISSUE TITLE
Unable to add '(...)' in apply from: "...flutter.gradle"

### ISSUE THREAD

**Issue by pueffl** [flutter/flutter#58753]
Well, this is a bug of the weird sort and honestly I have no idea, why it happens, but it should be easy to reproduce:

I was going to migrate my Gradle scripts to Kotlin an just did the following thing: I changed

`apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"`

to 

`apply(from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle")`

When I change this, I get:

**Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.**

As this is not a big problem when you know why you are gettin the exception, it is very hard to find if you don't know the cause of the problem and the bug is really weird, because the statement should be syntactically the same, so I think you are doing something weird like parsing gradle.build for a specific String somewhere???

**Comment by TahaTesser** [comment]
Hi @pueffl 
I can only see this 
```
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```
and changing this to, app works
```
apply(from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle")
```

adding this breaking this, app doesn't work 
```
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```

Did i miss something? I'm too familiar gradle scripts?


Thank you

**Comment by pueffl** [comment]
Sorry, I think this is my fault!

The build itself works fine. The exception occurs when you try to start the project. When you select main.dart and try to run/debug, the exception is shown before an assembly is created and the application never starts.

**Comment by TahaTesser** [comment]
Hi @pueffl 
Running with this, app works fine
```
apply(from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle")
```

<img width="988" alt="Screenshot 2020-06-08 at 1 06 19 PM" src="https://user-images.githubusercontent.com/48603081/84004324-fcca8a80-a988-11ea-96cf-b56820a7b39e.png">

but your  line it seems to have different root name so i changed to `flutterSdkPath` to match correct root without parentesis and still fails 

Notice new project loads `pp_plugin_loader.gradle` and not `flutter.gradle

```
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```
to 

```
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/flutter.gradle"
```
but it fails to run to run even without parentesis
```
Running "flutter pub get" in dev_flutter...                         0.4s
Launching lib/main.dart on SM M305F in debug mode...

FAILURE: Build failed with an exception.

* Where:
Script '/Users/tahatesser/Code/flutter_dev/packages/flutter_tools/gradle/flutter.gradle' line: 34

* What went wrong:
A problem occurred evaluating script.
> Could not find method android() for arguments [flutter_ejeojezq9jiez72lpwxrp9rie$_run_closure1@5be7c7b4] on settings 'android' of type org.gradle.initialization.DefaultSettings.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 797ms
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 2f7a59a8da (3 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by pueffl** [comment]
Hi!

This doesn't work for me. I get:

**Could not get unknown property 'flutterSdkPath' for project ':app' of type org.gradle.api.Project.**

when I build the project.

And why should I change it from 

`apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"`

Isn' that the 'official' line of code that is generated on every new flutter project?


C:\Development\Projects\eight\android>flutter doctor -v
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale de-AT)
    • Flutter version 1.17.2 at C:\Development\Tools\flutter
    • Framework revision 5f21edf8b6 (11 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Development\Tools\android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Development\Tools\android\sdk
    • Java binary at: C:\Development\Tools\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Development\Tools\studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Wolfgang Grossinger\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @pueffl 
Here is my `settings.gradle` on latest `Channel stable, v1.17.3,` on a new project

```
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

```

Can you please create a new project on latest stable and post your `settings.gradle` here?
Thank you

**Comment by pueffl** [comment]
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

Seems to be the same as yours

**Comment by TahaTesser** [comment]
Hi @pueffl 
Please try Adding `(.....)` from previous [comment](https://github.com/flutter/flutter/issues/58753#issuecomment-640426868) and let me know if this still causes 

`apply(from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle")`

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
