### ISSUE TITLE
`TextStyle` with existing height cannot be copied with `height=null`

### ISSUE THREAD

**Issue by daohoangson** [flutter/flutter#58765]
## Use case

If a `TextStyle` has some non-null height, it's impossible to make a copy with `height=null` because of this line:

```dart
      height: height ?? this.height,
```

## Proposal

Adding a new param in `TextStyle.copyWith` should work.

**Comment by daohoangson** [comment]
Another way to do this without introducing a new param: use a private constant as the default value for `height`. That way we can determine exactly whether the caller specified some value for `height` during copy. There is one downsize though, the method signature will have to replace `double? height` with `dynamic height = _default`.

**Comment by daohoangson** [comment]
`TextStyle.height` shouldn't be negative (it won't render anything), can we use a magic value of `-1` to reset the height to `null`? Better yet, we can do an `assert` for `TextStyle.new` to disallow negative value and in `TextStyle.copyWith`, any negative value will reset the height.

**Comment by LongCatIsLooong** [comment]
It's not only `copyWith` that is not working. The meaning of null is ambiguous in the TextStyle context:
1. it could mean the value should inherit from the parent span, or be overwritten when `TextStyle.merge` is called, is
2. the height multiplier is disabled. 

I think we should follow the TextStyle convention and assume 1, let null represent "inherited", and pick a magic value for represent "disabled".

**Comment by daohoangson** [comment]
>  let null represent "inherited", and pick a magic value for "disabled"

That would be great. Thank you.
