### ISSUE TITLE
image_picker PickedFile should have a "length" and "file name" method similar to File

### ISSUE THREAD

**Issue by 123cristen** [flutter/flutter#58764]
In the current image_picker implementation, the only way to get the size of the file is to read the bytes. This is inefficient and unnecessary for cases when the size is used as part of a confirmation dialogue before reading the file.

https://pub.dev/documentation/image_picker_platform_interface/latest/image_picker_platform_interface/PickedFile-class.html

https://api.dart.dev/stable/2.8.4/dart-io/File/length.html

**Comment by ditman** [comment]
Another user has also requested a "file name" getter here:

https://github.com/flutter/plugins/pull/2802#issuecomment-642360958

I think we can use this issue to add *both* attributes at the PickedFile at the same time.

**Comment by ingmferrer** [comment]
I need to know the file size before uploading to the server. Any solution for this?

**Comment by ditman** [comment]
This has been added to the XFile class on the `file_selector` plugin, coming soon.

At some point, it might be worth the effort to migrate image_picker to use XFile instead of PickedFile, what do you think?

**Comment by markgrancapal** [comment]
> This has been added to the XFile class on the `file_selector` plugin, coming soon.

@ditman is there an ETA on when will it be available? Thank you!

**Comment by ditman** [comment]
> > This has been added to the XFile class on the `file_selector` plugin, coming soon.
> 
> @ditman is there an ETA on when will it be available? Thank you!

@markgrancapal no ETA yet, it needs to be split to a separate package first, and then adopted on the image_picker plugin :)

**Comment by SupremNandalDev** [comment]
Any update on this?
One of our project is stuck at final stage just because we're unable to get the file extension... Any other package that could be useful for this?
Thanks in advance

**Comment by ditman** [comment]
This is happening, courtesy of @balvinderz [here](https://github.com/flutter/plugins/pull/3388?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE0NTIzNjY0ODY6MTI1NTU5NA%3D%3D).

**Comment by icecandy** [comment]
It would really also be super useful to be able to get the pixel dimensions of the picked file too. No idea if this is possible.

**Comment by ditman** [comment]
@icecandy the "PickedFile" (and the newest `cross_file`) are simply abstractions of the filesystem. They'll give you access to the Bytes of the selected file, and in cross_file some extra metadata. The cross_file will be shared across multiple packages (camera, image_picker, file_selector...), and there's no guarantees that it's always going to be an image.

In your app, however, once you have the bytes of the image, you can use something like [`package:image`](https://pub.dev/packages/image) to `decodeImage` and then get its width/height. Maybe you want to give that a shot!

**Comment by ManluZhang** [comment]
Hi there. I'm using image_picker on web recently. Everything works perfect except that I can't get the filename of the picked image. It would be really helpful if you guys added that to the plugin. 
Or any other ideas of getting the file name? Thanks in advance.

**Comment by ditman** [comment]
There is an incoming migration of the image_picker right now that will allow this feature to be implemented soon, keep an eye on this:

* https://github.com/flutter/plugins/pull/4072

Once that migration is done, we'll be able to slightly modify the plugin to remember the filename as it was on the users' disk.

**Comment by ayushin** [comment]
So that's in, will somebody update the image_picker?

**Comment by ditman** [comment]
@ayushin the migration is still in process, then it can be added (it's 3 PRs, really)

**Comment by MatteoRosina** [comment]
Hi @ditman and everyone, I see the PR has been merged. Can this issue proceed now?

**Comment by ditman** [comment]
This feature should now be available for Mobile devices, through the new XFile methods (see [XFile docs](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html) (see `.name` and `.length()`).

I'll keep this issue open for now, because for web, some extra code needs to be added to the plugin to store the selected file's name and length when creating the XFile in the browser.

**Comment by ditman** [comment]
Version 2.1.1 of `package:image_picker_for_web` should initialize the returned XFile objects with the name of the file on disk, its size, mimetype and creation date (all of them "if provided by the browser"). It also adds "multiple" picks.

Please, do give this a shot and see how it works for your apps!

Thanks @balvinderz for the contribution!

**Comment by balvinderz** [comment]
They are passing now lol

**Comment by ditman** [comment]
Published! https://pub.dev/packages/image_picker_for_web/changelog#211
