### ISSUE TITLE
[e2e] Make it easier for an e2e test to obtain the timeline

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#58789]
For example, flutter_driver has ways to obtain the timeline for a specific block of code. Package:e2e should offer similar functionality.

More generally, it should offer functionality to measure performance metrics over the course of an integration test.

**Comment by amreniouinnovent** [comment]
@dnfield I just wonder if there is a way to capture log data and export it to a file
I tried with flutter driver
```
Logger.root.onRecord.listen((record) {
  print('${record.level.name}: ${record.time}: ${record.message}');
});
```
But still, I can't capture logs
Any suggestions

**Comment by dnfield** [comment]
@amreniouinnovent please file a separate bug for that - this one is specifically about geting the timeline working more easily for e2e tests.

**Comment by amreniouinnovent** [comment]
@dnfield I just get confused what is the difference between [**flutter_test**, **flutter_driver**, **e2e**]?
Thank you for your support

**Comment by dnfield** [comment]
flutter_test is primarily for writing unit tests/widget tests of your code.

flutter_driver is an integration and performance benchmarking framework designed primarily for use by the Flutter team itself to test the framework.

e2e is meant for broader use to write integration tests for Flutter.

**Comment by CareF** [comment]
> flutter_test is primarily for writing unit tests/widget tests of your code.
> 
> flutter_driver is an integration and performance benchmarking framework designed primarily for use by the Flutter team itself to test the framework.
> 
> e2e is meant for broader use to write integration tests for Flutter.

Given this design for `WidgetTester` for unit test and `e2e` for broader use, does it make sense to not use `testWidget` and `WidgetTester` but something else like flutter/flutter#61511?

**Comment by amreniouinnovent** [comment]
@dnfield I have checked e2e documentation and I have googled it but I didn't understand it
