### ISSUE TITLE
[connectivity] Can't get wifiName on android

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#58797]
Hi all, I tried to run the getWifiName method in connectivity according the the instructions in the [flutter connectivity package page](https://pub.dev/packages/connectivity#-readme-tab-) but it returns null (connectivity: ^0.4.8+6).
Tested it on 2 devices running Mi 9T Pro (android 10) and OnePlus 3T (android 10 custom rom).
Tried again using the connectivity app from the plugins git [itself](https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity) but same result, wifi name is null.
Outer fields are filled correctly: Connection Status, Wifi BSSID, Wifi IP

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/51529
