### ISSUE TITLE
flutter/dart patched sdks should be bundled independent of aot/jit

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#58793]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=53418

**Comment by chaselatta** [comment]
This is needed to reduce the size of the fuchsia checkout. We should look at removing any duplicate build artifacts from being uploaded to CIPD.

**Comment by chaselatta** [comment]
Being tracked in upstream issue
