### ISSUE TITLE
SSL Pinning TlsException: Failure trusting builtin roots (OS Error:  	CERT_ALREADY_IN_HASH_TABLE

### ISSUE THREAD

**Issue by rakafajar** [flutter/flutter#58802]
I'm trying to practice SSL Pinning on flutter but there are errors, how to resolve errors like this ?, I have followed a few suggestions on github issuses

```
TlsException (TlsException: Failure trusting builtin roots (OS Error: 
	CERT_ALREADY_IN_HASH_TABLE(x509_lu.c:356), errno = 0))
```

```
  static const endpoint = '';
  var client = http.Client();

  HttpClient httpClient = new HttpClient();

  Future<Login> login(String email, String password, String fcmToken) async {
    ByteData data = await rootBundle.load('assets/raw/gd_intermediate.crt');
    SecurityContext context = SecurityContext.defaultContext;
    context.setTrustedCertificatesBytes(data.buffer.asUint8List());
    Map<String, String> headers = {"Content-type": "application/json"};

    String body =
        '{"email": "$email", "password": "$password", "fcm_token": "$fcmToken"}';

    var response = await client.post(
      '$endpoint/mobile/login',
      headers: headers,
      body: body,
    );

    return loginFromJson(response.body);
  }
```

```
Future<bool> addSelfSignedCertificate() async {
  ByteData data = await rootBundle.load('assets/raw/gd_intermediate.crt');
  SecurityContext context = SecurityContext.defaultContext;
  context.setTrustedCertificatesBytes(data.buffer.asUint8List());
  print("apa ini $data");
  print("ini juga $context");
  return true;
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  assert(
    await addSelfSignedCertificate(),
  );
  // ByteData data = await rootBundle.load('assets/raw/gd_intermediate.crt');
  // SecurityContext context = SecurityContext.defaultContext;
  // context.setTrustedCertificatesBytes(data.buffer.asUint8List());
  Stetho.initialize();
  initializeDateFormatting();
  runApp(
    App(),
  );
}
```

**Comment by rakafajar** [comment]
> /cc @zichangg

Is there something wrong with the code that I used?

**Comment by iapicca** [comment]
Hi @rakafajar 
could you please provide your `flutter doctor -v`
your code sample might be using 3rd party plugins like [flutter_stetho](https://pub.dev/packages/flutter_stetho),
if so could you please provide a complete and runnable minimal code sample 
without 3rd party plugins
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
