### ISSUE TITLE
Cannot command 'flutter' out of home directory -Debian

### ISSUE THREAD

**Issue by zubairpkv** [flutter/flutter#58805]
I'm using Linux (Deepin distro). I saved flutter folder in my home directory and edited .bashrc file appending `export PATH="$PATH:`pwd`/flutter/bin"`. I can command `flutter doctor` inside my home directory but other, there i get 'flutter command not found'

**Comment by iapicca** [comment]
Hi @zubairpkv 
could you please run 
```console
cd <random folder>
which flutter
```
if it does not show the path to `../flutter/bin/flutter`
please double-check the steps provided in the [docs](https://flutter.dev/docs/get-started/install/linux#update-your-path)
Thank you
