### ISSUE TITLE
Timeline summary should contain CPU/GPU and memory usage

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#58803]
as of [flutter.dev/go/engine-cpu-profiling](http://flutter.dev/go/engine-cpu-profiling), we collect the CPU and Memory usage. With work being done to collect GPU usage on iOS as well.

Relevant PRs:
1. CPU: https://github.com/flutter/engine/pull/18087
2. Memory: https://github.com/flutter/engine/pull/18516
3. GPU: https://github.com/flutter/engine/pull/18752

This issue is to track collecting and posting these as `avg`, `90th` and `99th` percentile metrics to the `timeline_summary.json` file.

cc: @liyuqian , @AlbertWang0116, @gaaclarke

**Comment by liyuqian** [comment]
It would be nice to also have them on Android!
