### ISSUE TITLE
Release branches should skip skia_gold tests, others only meant to pass on master

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#58814]
Certain CI tests, (e.g. skia_gold goldens tests) are currently set up with the assumption that they will be run pre/post submit against master. This means that they are almost certain to fail on release branches, where the code is between weeks and months old. It is important that CI for release branches are kept as green as possible, so that legitimate regressions are immediately identified.

Where possible, tests should be modified to accurately test older release code (e.g. https://github.com/flutter/flutter/issues/57062). This issue is specifically tracking skipping tests that would be either impossible or extremely difficult to support multiple release branches.

**Comment by christopherfujino** [comment]
Related https://github.com/flutter/flutter/issues/53371

**Comment by Piinks** [comment]
This should be pretty easy. We added some branching support for gold specifically in https://github.com/flutter/cocoon/pull/727. It'll be easy to tell from the base ref of the pr if gold should bother with it.

**Comment by Piinks** [comment]
https://github.com/flutter/cocoon/pull/800 should trim things down a bit. :)

**Comment by digiter** [comment]
Triage: what's remaining?

**Comment by Piinks** [comment]
Goldens are skipped on release branches, @christopherfujino what else should be skipped?

**Comment by christopherfujino** [comment]
> Goldens are skipped on release branches, @christopherfujino what else should be skipped?

Cool, I didn't realize we were skipping goldens on release branches, awesome. I'll close this now.
