### ISSUE TITLE
Error creating a new Flutter project in Android Studio.

### ISSUE THREAD

**Issue by Arisergio82** [flutter/flutter#58819]
When I try to create a new Flutter project in Android Studio 3.5.3, I get the following message:

Oops; flutter has exited unexpectedly: "Invalid argument(s): Invalid type for "path": null". A crash report has been written to D:\ProjetosFlutter\flutter_02.log.

[flutter_02.log](https://github.com/flutter/flutter/files/4738002/flutter_02.log)

This error does not happen when I create an Android Studio Project.

**Comment by tusharojha** [comment]
Similar issue #56811 is already open.

**Comment by Arisergio82** [comment]
> Similar issue #56811 is already open.

Sorry man, I didn't know about this. I saw the post you mentioned and it seems the same problem as mine. Should I close this one and wait for the other one? I did the update to Android Studio 4.0 and updated all plugins and sdk. The problem remains. I don't know what to do.

**Comment by tusharojha** [comment]
I think you have not set up environment variables correctly.
Checkout: https://flutter.dev/docs/get-started/install/windows#update-your-path

**Comment by Arisergio82** [comment]
> I think you have not set up environment variables correctly.
> Checkout: https://flutter.dev/docs/get-started/install/windows#update-your-path

I did, man.

![env](https://user-images.githubusercontent.com/66491296/83975299-8adf3c00-a8c9-11ea-8a9a-42833d8d802c.png)

**Comment by iapicca** [comment]
Hi @Arisergio82 
does the issue occur running from terminal
`flutter create example`
If so, could you provide the logs and your flutter doctor
Thank you

**Comment by Arisergio82** [comment]
> Hi @Arisergio82
> does the issue occur running from terminal
> `flutter create example`
> If so, could you provide the logs and your flutter doctor
> Thank you

Hi!
I I tried from terminal and received the same error message.
![env 2](https://user-images.githubusercontent.com/66491296/84060843-44561400-a993-11ea-9b0f-9289ecf60e09.png)
[flutter_02.log](https://github.com/flutter/flutter/files/4747504/flutter_02.log)

flutter doctor:
![env 3](https://user-images.githubusercontent.com/66491296/84060922-6354a600-a993-11ea-915d-1ca55417081e.png)

**Comment by TahaTesser** [comment]
Hi @Arisergio82 
You cannot created a new project in system32 path, it's a system folder
Please open terminal from desktop path and execute `flutter create example` and provide the logs
Thank you

**Comment by Arisergio82** [comment]
Hi all! I've taken some desperate measures. Uninstalled everything: Android Studio, Plugins, Flutter sdk.... All! So I downloaded the latest versions and installed again. Now everything is working!

**Comment by iapicca** [comment]
Hi @Arisergio82 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
