### ISSUE TITLE
flutter.jar for x86_64 in hello_services

### ISSUE THREAD

**Issue by miroslavolek** [flutter/flutter#5881]
Currently we are not able to use hello_services example in x86_64 emulators on Android, due missing flutter.jar in android-x64 directory.

**Comment by eseidelGoogle** [comment]
Yeah, we're uploading it for arm:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#120
but not for x86.  Simple oversight:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#102

@jason-simmons might be able to help.

also, are we only building for x86 on that bot and not x64?

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/dev/bots/README.md has instructions on how to make changes to those files.

**Comment by jakobr-google** [comment]
flutter.jar is now present in android-x86 and android-x64. Changes to the Gradle build to actually support x86 variants are tracked in other issues. Let's say #6136.
