### ISSUE TITLE
[web]: Text span text by default is red

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#58828]
By default text span text is red, seems odd for that to be the default style.

Using textSpan and flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true

code snippet:
```
Widget build(BuildContext context) {
    return MaterialApp(
      title: 'text sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('text sample'),
        ),
        body: Center(
          child: RichText(
            text: TextSpan(text: 'testing testing is this red by default'),
          ),
        ),
      ),
    );
```
Results:

<img width="1072" alt="Screen Shot 2020-06-05 at 1 58 42 PM" src="https://user-images.githubusercontent.com/56849473/83922141-af55df80-a734-11ea-866d-a30db08162e5.png">

[✓] Flutter (Channel master, 1.19.0-4.0.pre.81, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.19.0-4.0.pre.81 at /Users/mariamhas/Developer/flutter
    • Framework revision 5722adf11d (76 minutes ago), 2020-06-05 12:40:02 -0700
    • Engine revision e87a05fbba
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 62903873df)

**Comment by mariamhas** [comment]
seems for native ios the text doesn't even show up:
<img width="433" alt="Screen Shot 2020-06-05 at 2 31 25 PM" src="https://user-images.githubusercontent.com/56849473/83924324-3dcc6000-a739-11ea-86b0-b3e739e153e0.png">

**Comment by yjbanov** [comment]
This is happening when `FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=false` as well. This is working as intended. We intentionally use ridiculous font style when the app forgets to pick a style.

**Comment by tapizquent** [comment]
I understand the fact that it defaults to red when not set, but why doesn't it use the global theme color provided by theme in MaterialApp? I have been trying to change the font color of all the Text widgets with no luck.

Mainly, I've been trying to set the `TextTheme.apply(displayColor: Colors..., bodyColor: Colors..)` but that does not do anything.
