### ISSUE TITLE
Flutter CupertinoTabBar and CupertinoNavigationBar not blurring as well as native tab bar blur when scrolling  

### ISSUE THREAD

**Issue by Chimba123** [flutter/flutter#58835]
Just an observation I’d like to share. I was using my native iOS photos app & I noticed when you scroll, the bottom bar blurs nicely, it’s noticeable but not abusive & it’s glossy & well balanced. It’s pleasant it feels very ios 

When Flutter was early before Stable it had a good well balanced blur effect in the Cupertino bottom tab bar widgets and the top Navigation bar widgets for Cupertino but I have just realised they are kind of dimmed out now ....they are not as well balanced or glossy as the native iOS apps... 

It would be nice if they could be as similar/close to the native implementation they seem almost white & the blur is barely noticeable... 

I remember sometime back when I was starting out my Cupertino navigation bar was clearly blurry together with the Cupertino bottom bar when scrolling content so I changed the background to white for the top bar I have decided to revert to the old native iOS feel and removed the background color & just seen/realized  how barely noticeable the blur effect has become..

**Comment by TahaTesser** [comment]
Hi @Chimba123 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample.
Thank you

**Comment by Chimba123** [comment]
@TahaTesser 

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-ZM)
    • Flutter version 1.17.3 at /Users/apple/Desktop/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Chimba123** [comment]
@TahaTesser 
` Widget build(BuildContext context) {
    return Scaffold(
      body: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(
          inactiveColor: CupertinoColors.black,
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: GestureDetector(
                onLongPress: (){
                  _platformSpecificCodeRun();
                  //_buildNavigator1();

                },
                child: Icon(
                  Icons.language,
                  size: 22.0,
                ),
              ),
            ),
            BottomNavigationBarItem(
              icon: Icon(
                IconData(0xe900, fontFamily: 'user2'),
                size: 19.5,
              ),
            ),
            BottomNavigationBarItem(
              icon: GestureDetector(
                onLongPress: _buildNavigator2,
                child: Icon(
                  Icons.camera_alt,
                  size: 24.0,
                ),
              ),
            ),
            BottomNavigationBarItem(
              icon: Badge(
                badgeContent: Text(
                  '3',
                  style: TextStyle(color: Colors.white),
                ),
                child: Icon(
                  IconData(0xe900, fontFamily: 'np_bellCircle1'),
                  size: 21.5,
                ),
              ),
            ),
            BottomNavigationBarItem(
              icon: GestureDetector(
                onLongPress: _buildNavigator3,
                child: Icon(
                  Icons.monetization_on,
                  size: 23.0,
                ),
              ),
            )
          ],
        ),
        tabBuilder: (BuildContext context, int index) {
          return CupertinoTabView(
            builder: (BuildContext context) {
              var currentIndex = index;
              switch (index) {
                case 0:
                  return BlocProvider(
                    create: (context) => SocialsFeedBloc(
                        socialsRepository: widget.socialsRepository),
                    child: SocialsFeed(
                        currentIndex: currentIndex,
                        text:
                        "Flutter is Google’s mobile UI framework for crafting high-quality native interfaces on iOS and Android in record time. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source"),
                  );

                  break;
                case 1:
                  return ProfilePage(
                    markethubProfileRepository:widget.markethubProfileRepository,
                    socialsProfileRepository: widget.socialsProfileRepository,
                    videohubProfileRepository: widget.videohubProfileRepository,
                  );
                  break;
                case 2:
                  return BlocProvider(
                    create: (context)=>VideohubFeedBloc(videoHubRepository: widget.videoHubRepository),
                      child: VideoPlayerScreen(currentIndex: currentIndex)
                  );

                  break;
                case 3:
                  return Notifications();
                  break;
                case 4:
                  return MarketHubFeed(
                    currentIndex: currentIndex,
                  );


                  break;
              }
              return null;
            },
          );
        },
      ),
    );

  }

  _buildNavigator1() => Navigator.of(context).push(CupertinoPageRoute<void>(
      builder: (BuildContext context) => SocialsPosting()
  ));
  _buildNavigator2() => Navigator.of(context).push(CupertinoPageRoute<void>(
      builder: (BuildContext context) => VideoHubPosting()
  ));
  _buildNavigator3() => Navigator.of(context).push(CupertinoPageRoute<void>(
      builder: (BuildContext context) => MarketHubPosting()
  ));
}`

**Comment by TahaTesser** [comment]
Not as blurry as native BottomNavigationBar in Cupertino widget

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      theme: CupertinoThemeData(brightness: Brightness.dark),
      home: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(items: [
          BottomNavigationBarItem(icon: Icon(CupertinoIcons.heart)),
          BottomNavigationBarItem(icon: Icon(CupertinoIcons.heart)),
          BottomNavigationBarItem(icon: Icon(CupertinoIcons.heart))
        ]),
        tabBuilder: (BuildContext context, int index) {
          return CupertinoTabView(
            builder: (_) {
              return SingleChildScrollView(
                child: Column(
                  children: [
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                    Image.network('https://i.imgur.com/QCNbOAo.png',
                        height: 200),
                  ],
                ),
              );
            },
          );
        },
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-5.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-5.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c264b70ec3 (2 days ago), 2020-06-08 09:27:34 -0700
    • Engine revision c7f9725521
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.97

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment]
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3
    ! Device emulator-5554 is offline.

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.402 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2a188eeca3 (33 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>
