### ISSUE TITLE
Synthesize gesture events in hybrid mode on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#58837]
This is required to forward events to an `android.view.View` after the framework has decided that the platform view owns the events.

The logic used in virtual displays can be reused to achieve this behavior in hybrid mode.  Currently, this involves sending a message over a platform channel to the framework with the event metadata, then the framework forwards the event back to the platform.  Finally, the embedding replays the event in the target Android view.

**Comment by chinmaygarde** [comment]
@iskakaushik has context on the relevant subsystem and has agreed to investigate but will have limited availability this week.

**Comment by chinmaygarde** [comment]
I believe https://github.com/flutter/engine/pull/19484 is related to this effort. @iskakaushik Is that correct?

**Comment by iskakaushik** [comment]
@chinmaygarde yup. I've landed https://github.com/flutter/engine/pull/19427 and https://github.com/flutter/engine/pull/19482 which lay the ground work. https://github.com/flutter/engine/pull/19484 and adding tests should help us close this issue.

**Comment by iskakaushik** [comment]
fixed in https://github.com/flutter/flutter/pull/60930
