### ISSUE TITLE
[in_app_purchase] ProductDetails.title concatenate app title on product title

### ISSUE THREAD

**Issue by kazyamof** [flutter/flutter#58844]
I have created a managed product on Google Play, non consumable, and gave it the title: _"Remove Ads"._

In my app, I get it as a ProductDetails object to display in some view.

But the ProductDetails.title property, instead showing only my product title from Google Play "Remove Ads", is adding the app name inside parentheses, like: "_Remove Ads_ **(Super Alarm)**".
(where "Super Alarm" is the app name).

Is this by design? Would be better to have two distinct properties for product title and app title.

**Google Play:**
![image](https://user-images.githubusercontent.com/3179898/83933580-4a27db80-a780-11ea-9589-4ce6bb497cad.png)

**Retrieved from in_app_purchase package:**
![image](https://user-images.githubusercontent.com/3179898/83933490-58c1c300-a77f-11ea-988f-6ef0d090e781.png)

### flutter doctor -v:
[√] Flutter (Channel master, 1.19.0-4.0.pre.43, on Microsoft Windows [versÃ£o 10.0.19041.264], locale pt-BR)
    • Flutter version 1.19.0-4.0.pre.43 at C:\src\flutter
    • Framework revision 95edf28150 (2 days ago), 2020-06-03 17:41:15 -0700
    • Engine revision 859d892f1f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 54adfeb93f)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)    
    • Android SDK at C:\Users\samurai\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\samurai\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)       
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30128.74

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\samurai\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (4 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows                      • Windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.19041.264]
    • Web Server                   • web-server    • web-javascript • Flutter Tools
    • Chrome                       • chrome        • web-javascript • Google Chrome 83.0.4103.61

• No issues found!

**Comment by rahulraj64** [comment]
This is the default behavior of the Google InApp billing library. Not something related to Flutter itself.

**Comment by kazyamof** [comment]
Ok!
