### ISSUE TITLE
Unhandled Exception on path_provider plugin

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#58856]
In my app I create an invoice and show to screen. After upgrading to stable, v1.17.2 path_provider my part of the app is not working and giving me an error. Any idea?

**Error:**
Syncing files to device Android SDK built for x86...
Reloaded 0 of 1415 libraries in 449ms.
E/flutter (11008): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (11008): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (11008): <asynchronous suspension>
E/flutter (11008): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (11008): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (11008): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109:39)
E/flutter (11008): #4      _DekontPrintState._requestAppDocumentsDirectory (package:myapp_cep/ntms/dekont/dekont_print.dart:145:30)
E/flutter (11008): #5      _DekontPrintState._loadEverything (package:myapp_cep/ntms/dekont/dekont_print.dart:125:11)
E/flutter (11008): #6      _DekontPrintState.initState.<anonymous closure> (package:myapp_cep/ntms/dekont/dekont_print.dart:117:9)
E/flutter (11008): #7      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
E/flutter (11008): #8      _DekontPrintState.initState (package:myapp_cep/ntms/dekont/dekont_print.dart:94:7)
E/flutter (11008): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (11008): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (11008): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (11008): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (11008): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (11008): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (11008): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (11008): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (11008): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (11008): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (11008): #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (11008): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (11008): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (11008): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (11008): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (11008): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (11008): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (11008): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (11008): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (11008): #42     ComponentElement.perform

**Pub spec.yaml**
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.8+6
  flutter_spinkit: ^4.1.2+1
  decimal: ^0.3.5
  intl: ^0.16.0
  encrypt: 2.1.0
  image: ^2.1.4
  path_provider: ^1.6.10
  mailer: ^3.0.4
  flutter_slidable: ^0.4.9
  xml: ^3.5.0
  http: ^0.12.1
  page_transition: ^1.1.5
  flutter_swiper: ^1.1.6
  card_settings: ^1.9.3
  flutter_speed_dial: ^1.2.5
  drop_cap_text: ^1.0.7
  diacritic: ^0.1.1
  ntp: ^1.0.6
  flare_flutter: ^2.0.3
  flutter_datetime_picker: ^1.3.8
  flutter_screenutil: ^1.1.0
  flutter_picker: ^1.1.5
  package_info: ^0.4.1
  in_app_update: ^1.1.11
  upgrader: ^0.11.1
  dots_indicator: ^1.1.0

**flutter doctor -v**
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.2 at /Users/niyazitoros/flutter
    • Framework revision 5f21edf8b6 (9 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by NTMS2017** [comment]
I am using path_provider: ^1.6.0 this time and still get same error on Channel stable, v1.17.3.

**Error**
D/ViewRootImpl@aef6336[MainActivity](14624): ViewPostIme pointer 0
D/ViewRootImpl@aef6336[MainActivity](14624): ViewPostIme pointer 1
E/flutter (14624): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (14624): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (14624): <asynchronous suspension>
E/flutter (14624): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (14624): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (14624): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109:39)
E/flutter (14624): #4      _DekontPrintState._requestAppDocumentsDirectory (package:myapp_cep/ntms/dekont/dekont_print.dart:145:30)
E/flutter (14624): #5      _DekontPrintState._loadEverything (package:myapp_cep/ntms/dekont/dekont_print.dart:125:11)
E/flutter (14624): #6      _DekontPrintState.initState.<anonymous closure> (package:myapp_cep/ntms/dekont/dekont_print.dart:117:9)
E/flutter (14624): #7      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
E/flutter (14624): #8      _DekontPrintState.initState (package:myapp_cep/ntms/dekont/dekont_print.dart:94:7)
E/flutter (14624): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (14624): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (14624): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (14624): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (14624): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (14624): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (14624): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (14624): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (14624): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (14624): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (14624): #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (14624): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (14624): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (14624): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (14624): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (14624): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (14624): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (14624): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (14624): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (14624): #42     ComponentElement.perform


**flutter doctor -v**
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/niyazitoros/flutter
    • Framework revision b041144f83 (2 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

**Comment by iapicca** [comment]
Hi @NTMS2017 
I see there's an open [issue](https://github.com/flutter/flutter/issues/46679) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
