### ISSUE TITLE
Would be nice to have a way to validate layouts at many sizes

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5885]
I thought we had written this down somewhere but I don't see it.  This came out of a discussion with @Hixie and is a nice-to-have feature, but not anywhere on our near-term roadmap.  Filing as this came up in discussion with a customer the other day.  The goal is to answer the question of "what devices/screensizes does my app look bad on".

Should be straightforward with flutter to attempt laying out an app/route/widget at lots of different sizes and validate that no layout exceptions (red areas) are thrown. In the headless desktop sky_shell this would be very quick. Presumably there exists a list of known Android device screen sizes/densities somewhere on the web which should be straightforward to compile.

**Comment by Hixie** [comment]
This might catch Row/Column overflows, but I'm not sure it would really tell you if it's pretty or not.

**Comment by zoechi** [comment]
Golden tests might help here. Not sure about the sizes. I had quite a bit troubles setting screen sizes for tests.

**Comment by eseidelGoogle** [comment]
FYI @krisgiesing

**Comment by zoechi** [comment]
See also 
- https://stackoverflow.com/questions/53706569/how-to-test-flutter-widgets-on-different-screen-sizes
- https://github.com/flutter/flutter/issues/19181#issuecomment-417306782

**Comment by zoechi** [comment]
There is also #12944 about documentation

**Comment by zoechi** [comment]
I hope it's ok to close this as

**Comment by zoechi** [comment]
Duplicate of #12994
