### ISSUE TITLE
Android sdkmanager tool was found, but failed to run

### ISSUE THREAD

**Issue by IE7777** [flutter/flutter#58878]
I'm trying to use flutter on Android Studio. I have the flutter plugin installed on Android Studio and when i try to create a new flutter project it behaves normally, in the sense of it lets me write the project name, the flutter sdk path and so on. But when i click on finish absolutely nothing happens. I just see the Android Studio Welcome page where i can create new Projects. So i figured I'd see what flutter doctor -v has to say about it and it gives me these errors:
![C__WINDOWS_system32_cmd exe 6_5_2020 11_37_13 PM](https://user-images.githubusercontent.com/61663331/83953107-fd0a3f00-a83d-11ea-8ff7-0f79c79ded50.png)

So i try to find a solution by typing : flutter doctor --android-licenses but i get another error:
![C__WINDOWS_system32_cmd exe 6_5_2020 11_37_17 PM](https://user-images.githubusercontent.com/61663331/83953112-098e9780-a83e-11ea-9f0c-4d37ac0935b2.png)

And yes i have set the PATH variable and i have installed Android SDK Tools.
I went to the file specified that fails to run and tried to run it myself by clicking on it but i get the error: 
![bin 6_6_2020 9_40_50 PM](https://user-images.githubusercontent.com/61663331/83953178-68eca780-a83e-11ea-9e16-edad04a2a322.png)

I tried everything but nothing seems to do the job.

Any help would be appreciated.

**Comment by iapicca** [comment]
possibly related to 
https://github.com/flutter/flutter/issues/51712
https://github.com/flutter/flutter/issues/31116

**Comment by IE7777** [comment]
I just reset my whole PC. It worked. Do that as a last resort. But i have tried everything. I must’ve screwed up the path variables In a way.
