### ISSUE TITLE
Remove use of BundleUtilities in Linux build

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#58883]
When switching to CMake for the Linux desktop build I used `BundleUtilities` to create the relocatable folder, as it seemed like a straightforward and relatively error-proof way of getting all the dependent libraries. However, it has some undesirable properties:
- AFAICT there is no way to control where the libraries it copies end up, so they are all just next to the executable, instead of in a `libs` subfolder as the previous Make build structure used. While not a big deal, it makes for a messy folder.
- How it decides what to copy is something of a black box. In theory it doesn't copy system libraries, but how it decides what a system library is doesn't seem to be something we can control. If someone wanted to use any kind of sysroot, for instance, it would copy basically everything.

Since in general having a fully declarative build system works out better than having magical steps, I think using it was the wrong choice. We should instead explicitly declare the libraries we need, and copy them ourselves.

The necessary changes I'm aware of:
- Set the rpath, which `BundleUtilities` currently does for us. IIRC `CMAKE_INSTALL_RPATH` worked when I was first experimenting with different approaches, but if not we can do it directly in the build as we used to in the Makefile. (The unbundled version isn't launchable anyway, so the rpath of the unbundled copy of the binary doesn't matter.)
- Copy the Flutter library. Prior my adopting `BundleUtilities` I just had the path to the library as another variable exported to parent scope by `flutter/CMakeLists.txt` (it already exports a couple of things).
- Copy the plugin libraries, and do so in a way that allows plugins to add other libraries to that list and have them copied. (While I think in general things will work out better in the ecosystem if plugins statically link their non-system dependencies, that won't always be viable; e.g., a plugin wrapping a binary-only SDK library.) My preference for how to do that is to establish an "API" convention that each plugin exports something like `<plugin_name>_bundled_libraries` to parent scope, which is a list of absolute paths of libraries to copy (including the build product of the plugin itself), and then have the generated_plugins.cmake assemble that into a mega-list that it then exports in turn to its parent scope (the top-level CMake file), which uses it for copying.

A couple of notes on approaches that would be simpler, but that I don't want to use:
- Have plugin builds manipulate the mega-list directly, which would be trivial. This increases the chances that plugin authors will break things in hard-to-find ways. As a simple example, if plugin A accidentally *sets*, rather than appends to, the list, then it'll work fine in isolated testing, but when someone tries to build with plugin A and plugin B, the error will be that plugin *B*'s library is missing on launch, which will cause a lot of extra headache for users and other plugin authors. Having a policy that plugin build files should only make local changes, and export things up, will be much safer for the ecosystem. (Yes, people can still break things at the top level other ways, but I don't want to normalize things that can do that, like changing outside variables.)
- Having the copying done by an install directive in each plugin's build file (e.g., by providing a variable from the top level for a directory to copy into). My concern with this is that it puts more control about the actual behavior into the plugin build files, and once plugins are published we lose the ability to easily make any changes. The more we can have plugins export information about themselves rather than embed logic, the more flexibility we will have to make changes even after the ecosystem is established.

/cc @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
Thanks @stuartmorgan
