### ISSUE TITLE
Gallery: seeing a flash when starting on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5888]
The Gallery experiences a flashing when starting on Android. It's racey, and happens at different severities depending on hardware.

See also https://github.com/flutter/flutter/issues/5373#issuecomment-247203434

We'd like to ask for a way to mitigate the flash effect, in lieu of a complete solution. Up to us if we want to solve the whole thing once, or if the proposed solution below is sufficient.

We notice (via videos in the link above) that there is a draw of black. We're curious if the app (in this case, Gallery) has control over the very first color that Flutter draws. Can we change the black over to our shade of white?

**Comment by sethladd** [comment]
Please let us know if the request is something for us to do, or if we should just solve flashing all at once with a bigger change. Thanks!

**Comment by abarth** [comment]
Dup of #5373
