### ISSUE TITLE
Missing LICENSE file prevents service worker installation

### ISSUE THREAD

**Issue by thesmartrenovation** [flutter/flutter#58888]
Hello, 

In previous versions there was the possibility to install a web application in Google Chrome, as shown in the image:

![install](https://user-images.githubusercontent.com/57076657/83956583-50bc5e80-a825-11ea-878a-cf26c70043cc.png)

But in more recent versions compiling the same application, this option is no longer visible:

![recent](https://user-images.githubusercontent.com/57076657/83956597-6a5da600-a825-11ea-8262-3be88032d209.png)

Is there any way to activate this feature when compiling the application?

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-4.0.pre.92, on Microsoft Windows [VersiÃ³n 10.0.18363.836], locale es-CO)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by jonahwilliams** [comment]
I could not possibly begin to diagnose an issue from a screenshot of part of a browser. I would look in the https://developers.google.com/web/tools/chrome-devtools#application to see if there are any obvious errors and then ensure your application actually meets the standards for installation (has a manifest, served over https): https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by thesmartrenovation** [comment]
Look,

This is the application compiled with an earlier version of the SDK:

https://pedaleando.com.co/dashboard/#/

And this is THE SAME APPLICATION compiled with a more recent version:

https://pedaleando.com.co/prueba/

Can you tell me what changed? so it can't be installed now?

is the same application, just change the version of flutter used to compile. Both were compiled in the master channel, so, tell me.

**Comment by jonahwilliams** [comment]
Thanks, I can actually debug that. The request for LICENSE is missing since it was renamed to NOTICES

**Comment by jonahwilliams** [comment]
You can work around the issue by changing the lines that contains `assets/LICENSE: ...` to `assets/NOTICES`

**Comment by thesmartrenovation** [comment]
> You can work around the issue by changing the lines that contains `assets/LICENSE: ...` to `assets/NOTICES`

modifying the file flutter_service_worker.js?

**Comment by thesmartrenovation** [comment]
> You can work around the issue by changing the lines that contains `assets/LICENSE: ...` to `assets/NOTICES`

Yes, that's the thing, thank you very much. Will it be fixed in future versions?

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/58890 will fix it

**Comment by thesmartrenovation** [comment]
> > You can work around the issue by changing the lines that contains `assets/LICENSE: ...` to `assets/NOTICES`
> 
> Yes, that's the thing, thank you very much. Will it be fixed in future versions?

Thank you, so can I delete the test application?

**Comment by thesmartrenovation** [comment]
> #58890 will fix it

Thank you, so can I delete the test application?

**Comment by jonahwilliams** [comment]
yup! thank you
