### ISSUE TITLE
[pigeon] let there be hostApi, flutterApi annotation const fields

### ISSUE THREAD

**Issue by xster** [flutter/flutter#58894]
`@hostApi` would be easier to consume than `@HostApi()` since the construction arguments would likely be always empty. 

cc @gaaclarke

**Comment by gaaclarke** [comment]
I'm not sure it's always going to be empty in the future though and I'm concerned about having the 2 different ways being confusing.

**Comment by stuartmorgan** [comment]
Given the concern about future-proofing, and the limited difference, I don't think there's a compelling reason to change this.
