### ISSUE TITLE
MissingPluginException(No implementation found for method ... on channel ...)

### ISSUE THREAD

**Issue by ghostman2013** [flutter/flutter#58905]
I try to create a plugin for **Flutter** but after I renamed pre-created class stubs I met error:  
```
I/flutter (15723): MissingPluginException(No implementation found for method getAccounts on channel accountManager)
I/flutter (15723): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (15723): <asynchronous suspension>
I/flutter (15723): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (15723): #2      AccountManager.getAccounts (package:accountmanager/accountmanager.dart:35:37)
I/flutter (15723): #3      HomeWidget.fetchName (package:accountmanager_example/main.dart:20:43)
```
I tried to find an error in project configuration but seems all right, I tested it in the debugger on Dart side (I followed to native code and got error in native implemented function), on Android or iOS side **Flutter** calls method to register my plugin:  
```
override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    channel = MethodChannel(flutterPluginBinding.binaryMessenger, "accountManager")
    channel.setMethodCallHandler(this)
}
```
```
public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "accountManager", binaryMessenger: registrar.messenger())
    let instance = SwiftAccountManagerPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)
}
```

But when I call `_channel.invokeMethod()` **Flutter** doesn't call a method handler at the native side.

I've check many topic with similar problem but unfortunately, no-one helped.

Here is my repository [flutter-account-manager-plugin](https://github.com/ConteDevel/flutter-account-manager-plugin).

Where can the problem be?  

**P.S.** I asked on [StackOverflow.com](https://stackoverflow.com/questions/61978676/flutter-cannot-find-a-native-ios-implementation-of-method) but I didn't get answers.

**Comment by TahaTesser** [comment]
Hi @ghostman2013 
I just tried to reproduce the issue, create a new plugin, rename classes in Android or IOS, method channels still returns expected value on both platforms.

`flutter create --template plugin --platforms=ios,android  my_plugim`
then rename everything to `our_plugin`, no issues

[my_plugin.zip](https://github.com/flutter/flutter/files/5702777/my_plugin.zip)


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
