### ISSUE TITLE
fatal: bad config line 1 in file .git/config

### ISSUE THREAD

**Issue by 9jadev** [flutter/flutter#58912]
Hello World,

I'm fairly new to flutter I just started using it,

 but recently I started getting this error when I tried to run the app on my Andriod emulator.

> fatal: bad config line 1 in file .git/config
> Building flutter tool...
> Running pub upgrade...
> Could not resolve URL "https://pub.dartlang.org".
> Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
> Running pub upgrade...

Even when the app runs it takes a lot of time to start.

I have tried running flutter clean and flutter upgrade.

Thanks for your help.

**Comment by VladyslavBondarenko** [comment]
Hi @9jadev 
could you provide your `flutter doctor -v` and attach your `.git/config`?

**Comment by 9jadev** [comment]
Oh, thanks for your response,

But I already fixed it buy reinstalling flutter on my local pc.

**Comment by TahaTesser** [comment]
Hi @9jadev 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by sharmaVipin101** [comment]
@TahaTesser 
Iam also facing same issue (git: fatal: bad config line 1 in file .git/config)

I re-installed git and flutter sdk but still its there.

Attaching flutter doctor for more information

fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard out: 
Standard error: fatal: bad config line 1 in file .git/config

Returning 1970-01-01 05:30:00.000 instead.
[√] Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.18363.1198], locale en-IN)
    • Flutter version 0.0.0-unknown at C:\src\flutter
    • Framework revision  (), 1970-01-01 05:30:00.000
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\Dell\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • RMX1901 (mobile) • 560d8766   • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by LucasMGS** [comment]
i'm having this problem too.
Here is the flutter doctor -v:
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.18363.1256], locale pt-BR)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\lucas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\lucas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Redmi Note 9 Pro (mobile) • a0d5db1c • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by KholoudBatis** [comment]
I have the same error the android studio can not run and very slowly

**Comment by a7-SIP** [comment]
this seems like a flutter sdk problem, im getting the same when running any flutter commands from CLI

**Comment by KholoudBatis** [comment]
You must uninstall the Android studio than install againبتاريخ ٢٣‏/٠٣‏/٢٠٢١ ٧:٥٢ م، كتب a7-SIP ***@***.***>:
this seems like a flutter sdk problem, im getting the same when running any flutter commands from CLI
