### ISSUE TITLE
surface texture messages callbacks in the debug console

### ISSUE THREAD

**Issue by r4matero** [flutter/flutter#58926]
D/BufferQueueProducer(30619): [SurfaceTexture-0-30619-2](this:0x731dbcd000,id:2,api:1,p:388,c:30619) cancelBuffer: slot 1

is what get printed a million times on the debug console when I insert a map into the widget tree, 
Is there a way to silence this ?
![map_messages_callbacks](https://user-images.githubusercontent.com/57762327/83975009-e88b7c80-a8f9-11ea-9679-fc2e81016fe4.png)

**Comment by Roy-Matero** [comment]
it occurs when I user this dependency 
google_maps_flutter: ^0.5.28+1
and a GoogleMap() object

**Comment by VladyslavBondarenko** [comment]
Hi @r4matero 
could you provide your `flutter doctor -v` and a minimal complete reproducible code sample?

**Comment by r4matero** [comment]
flutter doctor -v 
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/roy/DevTools/flutter
    • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/roy/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/roy/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Note 7P • 192.168.0.139:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by r4matero** [comment]
Code 

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

**Comment by TahaTesser** [comment]
Hi @r4matero 
Testing your code sample on latest `stable`,  issue isn't reproducible 
Can you please try with again with `Channel stable, v1.17.3` on a new project? 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 

Thank you

**Comment by VladyslavBondarenko** [comment]
@r4matero 
I can't see the logs with stable 1.17.5 using google_maps_flutter 0.5.28+1 running on Redmi Note 7 Android 9 (API 28).
Are you still experiencing this? If yes, only with this device (if you have other to check)?
