### ISSUE TITLE
i can not Upgrade Flutter

### ISSUE THREAD

**Issue by a-aldosri1** [flutter/flutter#58922]
when i run "Flutter Upgrade" command i get this error:
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.

, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:881:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:312:15)
#2      _rootRunUnary (dart:async/zone.dart:1196:13)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#8      _StreamController._add (dart:async/stream_controller.dart:655:7)
#9      _StreamController.add (dart:async/stream_controller.dart:597:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:158:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:291:5)
#12     _StdSink.write (dart:io/stdio.dart:341:11)
#13     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dart:346:12)
#14     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#15     _rootRun (dart:async/zone.dart:1184:13)
#16     _CustomZone.run (dart:async/zone.dart:1077:19)
#17     _runZoned (dart:async/zone.dart:1619:10)
#18     runZonedGuarded (dart:async/zone.dart:1608:12)
#19     runZoned (dart:async/zone.dart:1536:12)
#20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#21     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:345:5)
#22     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:331:7)
#23     SummaryStatus._writeToStdOut (package:flutter_tools/src/base/logger.dart:821:49)
#24     SummaryStatus._printMessage (package:flutter_tools/src/base/logger.dart:825:5)
#25     SummaryStatus.start (package:flutter_tools/src/base/logger.dart:817:5)
#26     StdoutLogger.startProgress (package:flutter_tools/src/base/logger.dart:318:10)
#27     CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:606:46)
#28     CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#29     CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#30     CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:625:12)
#31     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:763:13)
#32     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#33     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
<asynchronous suspension>
#34     PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:140:27)
#35     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#36     _rootRunUnary (dart:async/zone.dart:1192:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#43     _rootRun (dart:async/zone.dart:1184:13)
#44     _CustomZone.run (dart:async/zone.dart:1077:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
exit code 255

My "flutter doctor" is ok:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @a-aldosri1 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by a-aldosri1** [comment]
Hi @iapicca 
this is my "flutter upgrade -f -v"

flutter upgrade -f -v
[  +10 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b041144f833e05cf463b8887fa12efdec9493488
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +254 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.3
[  +36 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +44 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +180 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.3
[   +3 ms] executing: [C:\src\flutter/] git fetch --tags
[+2730 ms] From https://github.com/flutter/flutter
                       7519c383f..746749244  master     -> origin/master
[   +1 ms] executing: [C:\src\flutter/] git rev-parse --verify @{u}
[  +35 ms] b041144f833e05cf463b8887fa12efdec9493488
[   +1 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +1 ms] Flutter is already up to date on channel stable
[   +1 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +35 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +1 ms] 4 days ago
[  +41 ms] Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
           Framework • revision b041144f83 (4 days ago) • 2020-06-04 09:26:11 -0700
           Engine • revision ee76268252
           Tools • Dart 2.8.4
[  +48 ms] "flutter upgrade" took 3,242ms.

thank you.

**Comment by iapicca** [comment]
Hi @a-aldosri1 
it seems that your flutter is in the latest version of stable channel
are you still encountering the issue?
thank you

**Comment by a-aldosri1** [comment]
@iapicca 
The problem is gone i don't know how but it's say that already been updated 4 days ago 
thank you so much
