### ISSUE TITLE
Flutter Beta Version 1.18.0-11.1.pre Bug in Flavor Project

### ISSUE THREAD

**Issue by wisnuwiry** [flutter/flutter#58921]
## Steps to Reproduce

Yesterday I used the stable version 1.12.13 Flutter. I created a Flavor project with firebase and the results were successful. And for some reason, I have to upgrade to Flutter beta with version 1.18. And when I restart the project, it doesn't work right away.

1. Run `flutter clean`.
2. Try update dependency
3. Run `flutter run -t lib/main.dart --flavor devDebug` for running flavor

**Expected results:** 
The application project runs as normal as in the previous stable version.

**Actual results:** 
Projects cannot be run either from debug mode or project build mode.

<details>
  <summary>Logs</summary>

```
$ flutter run -t lib/main.dart --flavor devDebug

Running Gradle task 'assembleDevDebugDebug'...                          
Running Gradle task 'assembleDevDebugDebug'... Done                30.8s
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under
/home/wisnusaputra/Documents/KodingWorks/magang/warung-second/build, but the tool couldn't find it.

```

```
No issues found! (ran in 27.9s)
```

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/wisnusaputra/Dev/flutter
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/wisnusaputra/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/wisnusaputra/Android/Sdk
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Redmi 4A   • 32d1dc7e7d54 • android-arm64  • Android 9 (API 28)
    • Web Server • web-server   • web-javascript • Flutter Tools
    • Chrome     • chrome       • web-javascript • Google Chrome 81.0.4044.129

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @wisnuwiry 
Can you please take a look at this https://github.com/flutter/flutter/issues/58296?
Do you the same flavor setup done?

If not,  
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
