### ISSUE TITLE
[IN_APP_PURCHASE] Purchase dialog not showing on iOS 13.4

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#58939]
This was closed.
https://github.com/flutter/flutter/issues/53534

The fix was to implement another library.
Totally unacceptable that it was closed and it's a major bug still!

_On a side note.
Many developers are butting their heads with Flutter at the moment the quality has drastically been reduced from last year._

**Comment by TahaTesser** [comment]
Hi @ollydixon 
i have reopened the issue, it was closed by bot for no response, yep i agree issues isn't fixed 
Thank you very much
