### ISSUE TITLE
We need a canonical way to do interactive label + button.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5893]
We have a few places in the gallery of this form:

* button + label (radio + label)
* label + button (dark/light theme picker)
* vertical content + button (expansion panels)
* etc.

We should probably have some kind of interactive widget that unifies these use cases.

@Hixie @HansMuller @abarth

**Comment by eseidelGoogle** [comment]
Currently in several of these we surprise the user by having the label not be clickable.

**Comment by Hixie** [comment]
This is a dupe of https://github.com/flutter/flutter/issues/254. :-)
