### ISSUE TITLE
Is it possible to reOpen "Add ability for DragTargets to receive pointer position updates. #10450"

### ISSUE THREAD

**Issue by sgorbyo** [flutter/flutter#58934]
## Use case

     I do need to place a draggable in the specific place it was dropped by the user. 

## Proposal
I found that a similar PR (Add ability for DragTargets to receive pointer position updates. #10450) was analysed and coded more than two years ago. Apparently it stopped due to the vacation period of the tester and never was delivered.
Is it possible to reopen it?

**Comment by TahaTesser** [comment]
Hi @sgorbyo 
Feel free to create a new PR and mention this PR in your PR

I feel safe to close this issue, if you disagree please write in the comments
and I will reopen it. 
Thank you
