### ISSUE TITLE
`OnDone` in `Stream`  is not called correctly.

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#58947]
Sample code
```dart
String _tempPath;
void testAsyncFile(String cachePath) async {
  int loadLen = 0;
  StreamController<Uint8List> sc = StreamController();
  cachePath = "$_tempPath/$cachePath";
  File cacheFile = File(cachePath);
  if (cacheFile.existsSync()) {
    print("Load local file：$cachePath");
    var stream = cacheFile.openRead();
    stream.listen((value) {
      loadLen += value.length;
      sc.sink.add(value);
    }, onDone: () {
      //print("onDone($cachePath)")
      print("onDone()");
      sc.close();
    });
  }
}

void _incrementCounter() {
  List<String> paths = [];
  paths.add("covers/cover-10.webp");
  paths.add("covers/cover-24.webp");
  paths.add("covers/cover-25.webp");
  paths.add("covers/cover-23.webp");
  paths.add("covers/cover-29.webp");
  paths.add("covers/cover-36.webp");
  for (var i = 0; i < paths.length; ++i) {
    testAsyncFile(paths[i]);
  }
}
```

When the `_incrementCounter` function is called, 6 files are loaded. To ensure that the file can be read correctly, `onDone` should be called 6 times, but the above code does not.

When I turned off this line of code `// print(" onDone($cachePath)")` comment, `onDone` was called 6 more times.

```shell
D:\Desktop\flutter_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)
```

**Comment by iKrupp** [comment]
Hi @Aaron009 
Could you give a simplified example without working with files so that others can play it too?
And perhaps you have chosen the wrong repository to report this problem. You should have written this in the repository ```dart-lang/sdk```

**Comment by Aaron009** [comment]
@iKrupp I don’t know how to simplify, or should I upload the complete project file to github?

Or, I changed to a file to load the file from the network, but I don’t know how to change it.

**Comment by iKrupp** [comment]
@Aaron009 
I redid your example a bit. Now he looks like this. And he works as he should.

Try it on DartPad:
https://dartpad.dartlang.org/7966bbc327ff0701595429d44c801602

**Comment by Aaron009** [comment]
@iKrupp 
I tested it and it didn't reproduce the problem. I created a new warehouse on github, you clone to see
https://github.com/Aaron009/flutter-bug.git

**Comment by Aaron009** [comment]
@iapicca Try this https://github.com/Aaron009/flutter-bug.git, it does not meet expectations. I posted a question to dart-lang.

**Comment by iapicca** [comment]
Hi again
as onDone works in both mine and @iKrupp samples
it's possible that the issue in your app depends from your implementation,
even assuming that this is not the case
as mentioned issue regarding streams should be addressed on Dart's github
Thank you
