### ISSUE TITLE
Use FlutterFragment in Android ViewPager, the FlutterFragment will be deformationed after touch and change the viewpager's page

### ISSUE THREAD

**Issue by shadownokill** [flutter/flutter#58949]
Use FlutterFragment in Android ViewPager, the FlutterFragment will be deformationed after touch and change the viewpager's page.

My English is not good, hope someone can understand me.
![x](https://user-images.githubusercontent.com/17847144/83990332-e2d67b00-a97b-11ea-937f-0faa542812c2.png)
![x1](https://user-images.githubusercontent.com/17847144/83990338-e5d16b80-a97b-11ea-944a-9af2544012da.png)

**Comment by TahaTesser** [comment]
Hi @shadownokill 
Can you please provide your `flutter doctor -v' and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as additional information isn't provided. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
