### ISSUE TITLE
 Floating action buttons don't respect SafeArea

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#58942]
b/158392371

When using a Scaffold, floatingActionButton: doesn't seem to respect the bottom SafeArea.

Full repro code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(title: Text('FloatingActionButton test')),
        body: SafeArea(
          child: Container(color: Colors.yellow),
        ),
        floatingActionButton: RaisedButton(
          onPressed: () {},
          child: Text('Press me'),
        ),
      ),
    );
  }
}
```

Result:
![image](https://user-images.githubusercontent.com/6687929/83982950-5f674c00-a8df-11ea-9a9c-38011c9b1d07.png)

The yellow area is the safe area, but it can clearly be seen that the RaisedButton goes into the safe area.

Wrapping the RaisedButton with a SafeArea widget doesn't change its position either.

Similar issue: https://github.com/flutter/flutter/issues/30105

**Comment by iKrupp** [comment]
Hi! It looks like the floating buttons are specifically ignored by the MediaQuery#padding value

I found this in Scaffold code (scaffold.dart file)
```
    _addIfNonNull(
      children,
      _FloatingActionButtonTransition(
        child: widget.floatingActionButton,
        fabMoveAnimation: _floatingActionButtonMoveController,
        fabMotionAnimator: _floatingActionButtonAnimator,
        geometryNotifier: _geometryNotifier,
        currentController: _floatingActionButtonVisibilityController,
      ),
      _ScaffoldSlot.floatingActionButton,
      removeLeftPadding: true,
      removeTopPadding: true,
      removeRightPadding: true,
      removeBottomPadding: true,
    );```


```  void _addIfNonNull(
    List<LayoutId> children,
    Widget child,
    Object childId, {
    @required bool removeLeftPadding,
    @required bool removeTopPadding,
    @required bool removeRightPadding,
    @required bool removeBottomPadding,
    bool removeBottomInset = false,
    bool maintainBottomViewPadding = false,
  }) {
    MediaQueryData data = MediaQuery.of(context).removePadding(
      removeLeft: removeLeftPadding,
      removeTop: removeTopPadding,
      removeRight: removeRightPadding,
      removeBottom: removeBottomPadding,
    );
    if (removeBottomInset)
      data = data.removeViewInsets(removeBottom: true);

    if (maintainBottomViewPadding && data.viewInsets.bottom != 0.0) {
      data = data.copyWith(
        padding: data.padding.copyWith(bottom: data.viewPadding.bottom)
      );
    }

    if (child != null) {
      children.add(
        LayoutId(
          id: childId,
          child: MediaQuery(data: data, child: child),
        ),
      );
    }
  }```


As a workaround you can try something like this:
```class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Builder(
        builder: (context) => Scaffold(
          appBar: AppBar(title: Text('FloatingActionButton test')),
          body: SafeArea(
            child: Container(
              color: Colors.yellow,
              child: TextField(),
            ),
          ),
          floatingActionButton: Padding(
            padding: MediaQuery.of(context).padding,
            child: RaisedButton(
              onPressed: () {},
              child: Text('Press me'),
            ),
          ),
        ),
      ),
    );
  }
}```
The point is to use a context that is above the button itself and SafeArea and the MediaQuery in which it is wrapped.

**Comment by Piinks** [comment]
I think we should determine how to apply potential SafeArea padding based on the FloatingActionButtonLocation - there are 18 of them I think, so I am guessing this will just require a large switch to figure out what sides we want to apply padding for each case.

**Comment by Piinks** [comment]
This looks like it will be a breaking change, bumping the milestone I just set to be super conservative.

**Comment by Piinks** [comment]
Also seems similar to https://github.com/material-components/material-components-ios/issues/7933

@willlarche can you advise on the Material specification? 

I have checked some native apps, like calendar, to see where the FAB lies on iOS, and it looks to me that this is WAI. https://github.com/material-components/material-components-ios/issues/7933 makes me think otherwise though..

**Comment by willlarche** [comment]
Querying designers and iOS team.

**Comment by Hixie** [comment]
> `math.max(mediaQuery.padding.bottom, mediaQuery.viewInsets.bottom)`

iirc that's mediaQuery.viewPadding, or something like that

**Comment by Piinks** [comment]
> > `math.max(mediaQuery.padding.bottom, mediaQuery.viewInsets.bottom)`
> 
> iirc that's mediaQuery.viewPadding, or something like that

Correct!

Update: I believe the `minInsets` of the `Scaffold` layout geometry are correct and don't need to be changed. I am going to add `minViewPadding` to the geometry to account for this instead in conjunction with the `minInsets`. Then I'll apply it to the FAB locations to ensure they are in safe areas by default. There are a lot of test cases for this, as the 18 different FAB locations are also affected by
 - app bars
- bottom navigation bars
- snackbars
- bottom sheets
- and for all of the above, the way these elements are laid out when resizeToAvoidBottomInsets is false

Still hammering out all of these test cases currently, I'll link the PRs when they are ready to roll!

Regarding the default FAB margin here (which is 16px), I think the latest consensus on the internal bug is to defer to the greatest where it makes sense, as in `math.max(kFABMargin, viewPadding)` Any thoughts on that are welcome! :)
