### ISSUE TITLE
Gaps between items in Column and ListView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#58951]
b/158072646

There are small gaps between consecutive items in Column / ListView / CustomScrollView.
When draw a black background behind a list / column of red tiles, there are some black gaps between items in the list / column. It is expected that the list should be all red with no gaps in between.

On mobile, the gaps are always visible. Happens on debug, profile and release build.
On dartpad.dev/flutter, the gaps are only visible at some scrollOffset.

Example code: https://dartpad.dev/5239567d3d7c2a0da8fb1dc1fdb5eb83
Attached screenshots are taken on dartpad and on Pixel 1.

![image](https://user-images.githubusercontent.com/6687929/83993491-6bb3cf00-a908-11ea-8260-38fa00d2a371.png)

**Comment by HansMuller** [comment]
This looks like a known problem with antialiasing and mapping from logical pixels to device pixels. There's an open issue for a documentation fix: #14288

More info about the problem can be found here:
https://github.com/flutter/flutter/issues/14288#issuecomment-361375791
https://github.com/flutter/flutter/issues/17084#issuecomment-385718108
https://github.com/flutter/flutter/issues/15035#issuecomment-370028740

**Comment by mehmetf** [comment]
This is great context. Thanks Hans.
