### ISSUE TITLE
Caret gets back to head unexpectedly, when third-party keyboards call insertText and setMarkedText.

### ISSUE THREAD

**Issue by justoneplanet** [flutter/flutter#58963]
### Environment

- iOS 13.4.1 (17E262)
- Model: iPod touch (7th generation)
- flutter TextField

## Steps to Reproduce

1. third-party keyboard calls [insertText](https://developer.apple.com/documentation/uikit/uikeyinput/1614543-inserttext) with "hoge".
2. third-party keyboard calls [setMarkedText](https://developer.apple.com/documentation/uikit/uitextdocumentproxy/3152923-setmarkedtext) with empty text.

**Expected results:**

The caret should be at the tail of text.

**Actual results:** 

The caret is always at the head of text.

**Additional information:**

After step 2, if the third-party keyboard calls [adjustTextPosition](https://developer.apple.com/documentation/uikit/uitextdocumentproxy/1618194-adjusttextposition) with -1 to move the caret left, the flutter app always crashes.

The crash log is as follows.

```
*** -[__NSCFString substringWithRange:]: Range {8, 18446744073709551615} out of bounds; string length 9. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
```

**Comment by TahaTesser** [comment]
Hi @justoneplanet 
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample.
Thank you

**Comment by justoneplanet** [comment]
@TahaTesser Sorry! I'm not a flutter app developer, but a keyboard app developer. I have debugged "Flutter Task Listing App" with following minimal project.

### For debug of the incorrect caret position

[iOSSampleKeyboard-flutter-incorrect-caret-position.zip](https://github.com/flutter/flutter/files/4750842/iOSSampleKeyboard-flutter-incorrect-caret-position.zip)

### For debug about crash on moving caret to the middle of brackets

[iOSSampleKeyboard-flutter-crash.zip](https://github.com/flutter/flutter/files/4751171/iOSSampleKeyboard-flutter-crash.zip)

**Comment by TahaTesser** [comment]
Hi @justoneplanet 
Does this reproduce only on iPod touch? Did you try iPhone? Which one 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
