### ISSUE TITLE
--dart-define values revert to values from a previous run when hot restarting

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#58976]
Originally raised at https://github.com/Dart-Code/Dart-Code/issues/2521 by @macabeus.

Create a Flutter app that prints this in `main()`:

```dart
const appEnv = String.fromEnvironment("APP_ENV");
print('Running with environment "$appEnv"');
```

Run the app with:

```
flutter run --dart-define=APP_ENV=staging
```

It will print:

```
flutter: Running with environment "staging"
```

Press `q` to quit, and rerun with:

```
flutter run --dart-define=APP_ENV=production
```

It will print:

```
flutter: Running with environment "production"
```

Now hot restart (`Shift`+`R`) and it will print:

```
flutter: Running with environment "staging"
```

It seems like it's using a stale value. Running `flutter clean` seems to fix this. It seems like something isn't being invalidated with the different `--dart-define` (though I'm not sure it works prior to a restart).

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/tahatesser/Code/flutter_master
    • Framework revision 7467492444 (7 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by jason-simmons** [comment]
The old `--dart-define` value is being stored in `build/cache.dill`, which contains a copy of the compilation results from the original run (see https://github.com/flutter/flutter/commit/f149eec31bfeb5b165cdd507397c657c8c876b56)

If no source file timestamps have changed, then it looks like the resident runner and the frontend server have no way to know that compile-time defines have changed.  The tool would need to track changes in the dart-define values and refresh the cache accordingly.

@jonahwilliams

**Comment by jonahwilliams** [comment]
Interesting, I would have assumed that the defines would invalidate the dill - but it seems like almost nothing does. This could be fixed by tracking the input values used when producing it.

**Comment by jonahwilliams** [comment]
This can be fixed by storing the cached dill in the generated artifact directory (currently only used for localization stamps). This uses a directory name generated from a hash of all build inputs, so it should correctly handle this case too.
