### ISSUE TITLE
Sometimes drawing paths leads to big squares being drawn

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5898]
I've seen this on Android Nexus 6. I've also seen this kind of thing in the perf overlay sometimes, which draws a path from C++. @chinmaygarde says he's seen that too.

![screenshot_20160915-154033](https://cloud.githubusercontent.com/assets/551196/18570038/a411778c-7b5b-11e6-9b58-be8a2e44fe42.png)

**Comment by chinmaygarde** [comment]
I believe this is device/GPU specific. Can you also paste the output of `adb shell dumpsys SurfaceFlinger` if you still have that device?

**Comment by Hixie** [comment]
[gpu.txt](https://github.com/flutter/flutter/files/475833/gpu.txt)

**Comment by eseidelGoogle** [comment]
@chinmaygarde do we need to loop in Skia folks or is this Flutter-side?

**Comment by chinmaygarde** [comment]
I am reasonably certain this is Skia and device specific. Though I need to prepare a reduced test case first.

**Comment by chinmaygarde** [comment]
Cannot reproduce this reliably for a reduced test case.

**Comment by eseidelGoogle** [comment]
Looks like this stalled.  Are we still seeing this?

**Comment by HansMuller** [comment]
We pulled this demo from the gallery some time ago.

**Comment by chinmaygarde** [comment]
I havent seen this issue in the latest builds on multiple devices. Closing this for now. Please reopen if we observe this again.
