### ISSUE TITLE
Get position of in-flight Draggables on a DragTarget

### ISSUE THREAD

**Issue by monkeyswarm** [flutter/flutter#58982]
I'd like to drag a `Draggable` to a `DragTarget`, and get position information while still being dragged (not yet dropped). This will be both for visual changes and business logic.

See the gif for clarification of what I'd like to do. The green area is a `DragTarget`. As the `Draggable` (or rather, the 'feedback' widget of the `Draggable`, aka a `_DragAvatar`) is within the `DragTarget`, I paint both within the `DragTarget` (the light blue square) and outside the `DragTarget` (the dark blue line).

This coordinate value is already tracked within `_DragAvatar`, so it is just a matter of piping it back to the `DragTarget`

![draggablehover](https://user-images.githubusercontent.com/1235083/84043601-5a47e280-a95b-11ea-8f31-3cf1521829ed.gif)

I see two possibilities, but am open to other designs.

1) The movement of `_DragAvatars` within a `DragTarget` trigger the builder, with a new parameter of in-motion offsets.

The signature of the builder would change, and the construction of [DragTarget] could signify whether to fire the builder on move, vs keep the existing behavior (only fire the builder on entry/exit)

eg:

`typedef DragTargetBuilder<T> = Widget Function(BuildContext context, List<T> candidateData, List<dynamic> rejectedData, List<Offset> candidateOffsets);`

- Pros: drawing within the [DragTarget] becomes simpler, since the [DragTarget] children are rebuilt on each move.

- Cons: breaking change to [DragTargetBuilder].

2_The movement of `_DragAvatars` fires a new optional callback on `DragTarget`, e.g. `onMove(T data, Offset offset).`

- Pros: no breaking change, no change to the builder logic.

- Cons: updating the drawing of children is a more awkward since it is not part of the rebuild. Instead, users would likely need to call another setState after the current build has finished, e.g.

```
DragTarget(builder: onMove:(_,offset)=> 
    SchedulerBinding.instance.addPostFrameCallback((_) => setState(()=>_offset = offset));
```

which means that paint updates are always a frame behind.

Open to suggestions, thanks!

**Comment by monkeyswarm** [comment]
Hi @mehmetf !

**Comment by mehmetf** [comment]
@HansMuller FYI

**Comment by kunit1** [comment]
This is a great feature to have. I would vote for approach 1.

**Comment by monkeyswarm** [comment]
@HansMuller any opinion on the proposals above? This is starting to block a Google project's feature development.

**Comment by monkeyswarm** [comment]
Another option, as per the suggestion in 
https://github.com/flutter/flutter/wiki/Tree-hygiene
"Rather than deploying the proposed change as one PR that immediately breaks existing code, adjust your PR so that it introduces the new functionality, API, behavior change, etc, in an opt-in fashion."

3) Add another builder method to DragTarget, which fires on hover/move.

This could either
3a) Fire a rebuild on both accept/reject AND hover/move. Users can use this new builder instead of the default one.
or
3b) Fire a rebuild only on hover/move. User would use a combination of both the default builder (for the accept/reject callbacks) and the new callback (for the hover/move) to rebuild.

**Comment by monkeyswarm** [comment]
Note that https://github.com/flutter/flutter/pull/60174 does a combination of the suggestions. It 
- adds a second builder, which rebuilds all the times which the normal builder does, and also rebuilds when draggables move. It vends DragTargetDetails (in order to get position info) instead of raw data.
- adds an onMove callback
