### ISSUE TITLE
line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory  ../ios/Flutter does not exist

### ISSUE THREAD

**Issue by hc2088** [flutter/flutter#58984]
1, 

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

error
line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory

2,  Add User-Defined Setting
FLUTTER_ROOT

error
../ios/Flutter does not exist

3, 
export FLUTTER_ROOT=/Users/xx/Documents/flutter
not work too!!

**Comment by dnfield** [comment]
Please include the output of `flutter doctor -v` and a minimal reproduction of this issue.  /cc @jmagman

**Comment by hc2088** [comment]
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/huchu/Documents/flutter
    • Framework revision 5f21edf8b6 (11 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/huchu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/huchu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 3AB7B31D-998B-4AEF-B0A2-AE0B26A8E490 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!

1->>
iOS :   NativeDemo
 podfile 

target 'NativeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


  # install_all_flutter_pods(flutter_application_path)
end


2-->>>
iOS NativeDemo
Run Script 
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

3->>
 
hc2088:day2 ss$ pwd
/Users/hc2088/Desktop/flutter/day2

hc2088:day2 hc2088$ ls -l
total 0
drwxr-xr-x  10 hc2088  staff  320 Jun  8 23:23 NativeApp
drwxr-xr-x  18 hc2088  staff  576 Jun  9 01:04 flutter_module

**Comment by hc2088** [comment]
1, ->


hc2088:day2 ss$ pwd
/Users/hc2088/Desktop/flutter/day2

hc2088:day2 hc2088$ ls -l
total 0
drwxr-xr-x  10 hc2088  staff  320 Jun  8 23:23 NativeApp
drwxr-xr-x  18 hc2088  staff  576 Jun  9 01:04 flutter_module


2, ->

NativeApp 
 Run Script 

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed



3, ->
 flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/hc2088/Documents/flutter
    • Framework revision 5f21edf8b6 (11 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hc2088/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/hc2088/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro Max • 3AB7B31D-998B-4AEF-B0A2-AE0B26A8E490 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!

**Comment by hc2088** [comment]
1, ->


hc2088:day2 ss$ pwd
/Users/hc2088/Desktop/flutter/day2

hc2088:day2 hc2088$ ls -l
total 0
drwxr-xr-x  10 hc2088  staff  320 Jun  8 23:23 NativeApp
drwxr-xr-x  18 hc2088  staff  576 Jun  9 01:04 flutter_module



2, ->
NativeApp
Podfile
```

target 'NativeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


  # install_all_flutter_pods(flutter_application_path)
end
```

3, ->

NativeApp 
 Run Script 

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed



4, ->
 flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/hc2088/Documents/flutter
    • Framework revision 5f21edf8b6 (11 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hc2088/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/hc2088/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro Max • 3AB7B31D-998B-4AEF-B0A2-AE0B26A8E490 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!

**Comment by jmagman** [comment]
```
NativeApp
Run Script

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
```
That's not correct.  Your native app does not need any build script phase added.  The module embedding is already handled by CocoaPods with the changes you made to your Podfile.  There's no reference to this script in the iOS add-to-app instructions.  https://flutter.dev/docs/development/add-to-app/ios/project-setup

Closing.
