### ISSUE TITLE
Web apps don't load on Windows Edge or IE

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#58991]
## Steps to Reproduce

1. Open either of the 2 browsers (Edge or IE)
2. Go to https://gallery.flutter.dev/#/
3. Nothing loads

**Expected results:** 
The gallery app loads or a default page showing the currently supported browsers & versions are displayed.

**Actual results:** 
For the gallery app, a black page displays/nothing happens.

I have a six months old app that never got to run on Edge/IE since I started it and throws the same type (not exactly the same) of JS error as the samples do (object misses property/property unsupported).

I've reported a similar [issue](https://github.com/flutter/flutter/issues/49786) in the past, and I never resolved it on my side. I dropped the attempts after the gallery worked and my app didn't. So I figured out I make some things within the app that translate in some JS code that crashes Edge/IE.

I always test Edge against all build, still, I had no luck until now.

Considering I had a hard time figuring out that the following piece of code crashes an entire web app when deployed, I considered Edge/IE a lost cause:

```
Map m = {'value': 1};
print(int.tryParse(m['value'])); // error in JS compiling
```

The above will crash because it seems you can't do a **tryParse** for an already int value. 
In my head, when you use a **tryParse**, you should be able to accept any type and try to cast it to the desired type. Identity implementation should be implied. :|

Please [find here the screenshot](https://shared-assets.adobe.com/link/6b058f08-a362-4e18-5289-48510b724ef2) with the line where the app crashes in Edge.

The exact stack trace for the Flutter Gallery app:
```
NoSuchMethodError: Unable to get property 'clear' of undefined or null reference (Error 5007)
at H.i (https://gallery.flutter.dev/main.dart.js:2528:1)
at P.aI0.prototype.$0 (https://gallery.flutter.dev/main.dart.js:41207:15) 
at P.b7f (https://gallery.flutter.dev/main.dart.js:4177:1) 
at P.b7E (https://gallery.flutter.dev/main.dart.js:4179:5) 
at P.aqU.prototype.$1 (https://gallery.flutter.dev/main.dart.js:40378:1) 
at H.baQ (https://gallery.flutter.dev/main.dart.js:2608:8) 
at Anonymous function (https://gallery.flutter.dev/main.dart.js:2616:44)
```

In my app:

```
NoSuchMethodError: Object doesn't support property or method 'getAllKeys' (Error 438) 
at H.c (https://myapp/main.dart.js?v=1.19.4&i=4:2257:1) 
at P.aiF.prototype.$0 (https://myapp/main.dart.js?v=1.19.4&i=4:30843:15) 
at P.aCq (https://myapp/main.dart.js?v=1.19.4&i=4:3828:1) 
at P.aCG (https://myapp/main.dart.js?v=1.19.4&i=4:3830:5) 
at P.aae.prototype.$1 (https://myapp/main.dart.js?v=1.19.4&i=4:29722:1) 
at H.aE4 (https://myapp/main.dart.js?v=1.19.4&i=4:2338:8) 
at Anonymous function (https://myapp/main.dart.js?v=1.19.4&i=4:2346:44)
```

This might be caused by some dart2js JS output incompatibilities on Edge/IE? 
The same apps run fine on other browsers: Chrome, Firefox, Opera, Safari...

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101, locale en-NL)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/constantins/development/flutter
    • Framework revision 7467492444 (9 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/constantins/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by ferhatb** [comment]
Update: Tested on Edge 44 with latest master.
A FontFace api exception is being thrown. After that app renders:
![Screen Shot 2020-06-19 at 8 53 02 PM](https://user-images.githubusercontent.com/5061034/85190786-9723ab80-b270-11ea-97b3-e8d2800c100f.png)

tryParse API takes a string as parameter. Passing a dynamic won't work. Please try:
```
Map m = {'value': 1};
print(int.tryParse(m['value'].toString())); // Should check for null too...
```

After fixing Font api exception will close issue.

**Comment by ferhatb** [comment]
Update: @Constans , verified that IE11.900.18362.0 is crashing on document.fonts.clear call by running on latest master and i see blank screen. Will fix shortly.

**Comment by Constans** [comment]
@ferhatb , it seems that this is broken again in the current build on Microsoft Edge. I suppose the error is new this time. :)

**Comment by Constans** [comment]
> NoSuchMethodError: Object doesn't support property or method 'getAllKeys' (Error 438)

It seems that this error is triggered by the [hive](https://github.com/hivedb/hive) package.

Still not [fixed](https://github.com/hivedb/hive/issues/357) at this point, but it may help others in tracking their issues.
