### ISSUE TITLE
Debug console asking for update Settings.gradle and Build don't end

### ISSUE THREAD

**Issue by odfigor** [flutter/flutter#58995]
I am trying to make a simple app and put ads using Flutter. I am following this tutorial: --> https://www.youtube.com/watch?v=PxYiLDuS3hk&feature=youtu.be&fbclid=IwAR1usDtvuPRKXN1plGoukxb08w-g6a3khoQo_wlTmCPGsgDUPCfys86t5I0

But when I tried to build the app, the terminal simply said

"Plugin project :firebase_core_web not found. Please update settings.gradle"

And build forever, without ending to compile. My Settings.gradle is this

// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"```

Searching StackOverflow, the programmers say to change my build.gradle to this
def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()

def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {

    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()

def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {

    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}```
But... The error still happens. Other programmers say to simply add this to file, but if I add, the app simply crashes. The error disappears from debug console, but the app doesn't open and the build doesn't end.

What do I need to do? Thankfully, Igor.

**Comment by darshankawar** [comment]
@odfigor 
Since this is an year old issue, not sure if you are still facing this issue or not. I suggest you to upgrade flutter version and plugins to latest and see if you still get the same error.
If yes, provide the latest details.

I am going ahead and closing this as stale issue since there doesn't seem to be any activity after you opened this issue. If you disagree, write in comments and I'll reopen it.
Thanks.
