### ISSUE TITLE
Deprecate flutter run --machine and flutter attach --machine in favor of daemon

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#59006]
The flutter daemon could have all of the functionality of both flutter attach --machine and flutter daemon --machine. This will require some work to refactor both run/attach and daemon, but eventually, this will allow us to remove most of the Zone level overrides and perform some much needed cleanup to run/attach.

The run and attach commands have too much undocumented and lightly-tested functionality. For example, downloading artifacts, running pub, spitting out logs, validating parameters. This logic should be collected and refactored into a layer outside of the `FlutterCommand` so that it can be easily shared across run/attach/daemon.

@devoncarew @DanTup

**Comment by DanTup** [comment]
Is the plan to make launching a separate JSON command used in a long-running daemon process, or will we still be able to run immediately from a command, and have the process terminate if the app closes?

I ask because the daemon use to have launch support too (I think I removed it?), but for VS code it will always be separate from the device daemon (the device daemon runs in the long-lived extension host, whereas the `run` process will live in the spawned-per-debug-session debug adapter).

**Comment by jonahwilliams** [comment]
We could support these via some specific `flutter daemon-run` or `flutter daemon-attach` if need be. Would it be feasible to have `flutter daemon` itself spawn this process? or does it need to be through the flutter command

**Comment by devoncarew** [comment]
I think this would be worth a broader conversation, and the current `flutter run --machine` mechanism is working well for IDEs.

**Comment by jonahwilliams** [comment]
At the very least, i would prefer to pull them into separate commands. The current structure is not working well for the tool, and doesn't really meet our own testing standards

**Comment by DanTup** [comment]
> Would it be feasible to have `flutter daemon` itself spawn this process? or does it need to be through the flutter command

We could have *a* daemon spawn it, but not easily have the same daemon process that's handling commands do it. The code that does the device management and the code that spawns a debug session are very separate in VS Code, and with https://github.com/Dart-Code/Dart-Code/issues/1876 will be running in separate processes entirely. Running the debug adapter in-process makes it easy to accidentally share state between debug sessions or leak memory past the end of a debug session. It's also easier to send signals/terminate a specific process if it's not responding, than if the process was needed for other things too.

And although not a specific goal, other editors can reuse the Dart-Code debug adapter (if they understand Debug Adapter Protocol) if it's standalone and not tied into the rest of the extension (some people already use this today, but there are some quirks/edge cases from it accidentally being quite coupled to the rest of the VS Code extension).

**Comment by jonahwilliams** [comment]
Okay, I definitely don't want to force any architecting of IDE code - mostly I just want to separate out the daemon code from the non-daemon code.

This could be done by giving some new command `flutter run-daemon` flutter attach-daemon` the exact same semantics of `flutter run --machine` but without the `if (machine) { do something entirely different }`

**Comment by DanTup** [comment]
To be clear - if I had to run via `flutter daemon` and then sending a JSON command, it wouldn't mean significant changes (for VS Code) - but I would spawn a second instance of the daemon to do it (to avoid significant changes and coupling the debug adapter with the editors device daemon). But, I do think it'd be better to not do that :-)

Having separate commands is a trivial change, ofc.

Though if the difference is all in stdin/stdout handling, I was wondering if this couldn't be handled inside the command with some interface/adapter (assuming the commands will become lightweight wrappers around some implementation classes):

```dart
final ioAdapter = isMachineMode ? JsonProtocolRunAdapter() : ConsoleRunAdapter();
flutterRunImpl(ioAdapter);
```

Those adapters having sinks for output text/progress (printing either json or raw text) and events/streams for incoming requests (json for one, keypresses for the other). I think we already handle the output something like this (NotifyingLogger?) but also for the incoming requests. I think right now there are two very separate code paths for machine/non-machine `run`, but probably there shouldn't be if there's no difference in behaviour, only in the input/output interfaces.

**Comment by DanTup** [comment]
> Though if the difference is all in stdin/stdout handling

Looks like there are more differences than I remembered, like handling of multiple devices when not running with `--machine`. Not sure if they're all deliberate though, or if some might be accidental as a result of there being two different code paths (eg. things like `isolate-filter` look like they might only work for non-machine?).

**Comment by devoncarew** [comment]
@jonahwilliams - I take your points wrt the testing of this functionality, and how the impl has drifted from the `flutter run` one.

Conceptually though, from the IDE perspective, this is just `flutter run`, with a different way to get the output of the process, and different ways to trigger actions (reload, ...). It's the toolable version of `flutter run`. I think we do want it tested, but other time we want to ensure that it stays tightly aligned with `flutter run`. Moving it into a different command - `flutter daemon` or other - would likely mean that the impl drifts further away from the CLI `flutter run` experience.

**Comment by jmagman** [comment]
I've seen issues like https://github.com/flutter/flutter/issues/54014 using `--machine` for various reasons.  We need to make sure we aren't yanking it without a good replacement and docs for our non-IDE customers.

**Comment by jonahwilliams** [comment]
Closing since we're not going to do this
