### ISSUE TITLE
[tool_crash] Unimplemented handling of missing static target

### ISSUE THREAD

**Issue by yyorulmaz** [flutter/flutter#59005]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CompileTimeError: Unimplemented handling of missing static target
```
#0      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#1      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#4      _rootRun (dart:async/zone.dart:1184:13)
#5      _CustomZone.run (dart:async/zone.dart:1077:19)
#6      _runZoned (dart:async/zone.dart:1619:10)
#7      runZoned (dart:async/zone.dart:1539:10)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _runZoned (dart:async/zone.dart:1619:10)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.836], locale tr-TR)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (4 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\yusuf\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\yusuf\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by mkustermann** [comment]
```
_CompileTimeError: Unimplemented handling of missing static target
```
Does this happen with hot reload?

The check was introduced in dart-lang/sdk@c3043367cd563c05659045d335f076ca7e1b32ff and is related to dart-lang/sdk@847a1275133685f615a0c354292ba3f8e4304999

/cc @rmacnak-google

**Comment by jamesblasco** [comment]
I am having the same problem while debugging with flutter run --d macos on hot reload. It happens too often that it becomes a bit annoying. I don't understand what it means the error or the concept 'static target'. It would be nice to have some info about this error so I can avoid it.

**Comment by jamesblasco** [comment]
Soo it apparently changing all path imports to package imports solve the problem
`import 'card.dart'; `->` import 'package:example/card.dart';`

**Comment by fluttercorner1** [comment]
Here is all possible solution added [Flutter: Unimplemented handling of missing static target](https://fluttercorner.com/flutter-unimplemented-handling-of-missing-static-target/)

**Comment by Tchisky** [comment]
I'm having the same issue. when i run a single widget test it passes when i run all tests in the same file it passes, but when i run all the tests in **project/test** folder 1 widget test produces this error and fails(it passed before). No clue why!

`The following _CompileTimeError was thrown building Widget-[<'swip-collect'>](dirty,
state: _WidgetState#17757):
Unimplemented handling of missing static target`

**Comment by jmagman** [comment]
From duplicate https://github.com/flutter/flutter/issues/122163#issuecomment-1910716933
> https://dart-review.googlesource.com/c/sdk/+/291055 was submitted to produce more detailed error message about the missing target and some code around this was also changed. 

If anyone sees this crash message again can you please file a new issue and completely fill out the template?  We'll take a look at it with the additional information.  Thanks!
