### ISSUE TITLE
[video_player] Unable to play m3u8 file from CloudFront

### ISSUE THREAD

**Issue by ericderegt** [flutter/flutter#59017]
I'm opening a new issue that is similar to [#52389](https://github.com/flutter/flutter/issues/52389). I'm trying to play a video using VideoPlayerController with a presigned URL from AWS [CloudFront](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/sign/#URLSigner.SignWithPolicy), but the video does not play.

Here is my code to play the video:

```
final videoURL = await repo.getVideoURL(videoPath);
videoController = VideoPlayerController.network(videoURL);
```

The presigned URL is in the form - https://xyz.cloudfront.net/video.m3u8?Policy=xyz&Key-Pair-Id=xyz.

#52389 was marked as a duplicate of [#26851](https://github.com/flutter/flutter/issues/26851), but I don't think it is the same issue. The issue I'm facing seems to be specific to a presigned URL as I've seen many examples that work with a public URL that ends in a m3u8 file extension.

Here is my `flutter doctor -v` output

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/ericderegt/development/flutter
    • Framework revision f139b11009 (2 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ericderegt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

```

**Comment by superciccio** [comment]
hello, how are the link inside the playlist.

do the point to cloudfront link ?

I had something similar with hls, so double check

**Comment by ericderegt** [comment]
If I run cURL against the signed URL, I get

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=2485109,AVERAGE-BANDWIDTH=2185626,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=480x640,FRAME-RATE=30.000
indextest.m3u8
```

If I cURL indextest.m3u8 it returns

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:3,
indextest_00001.ts
#EXTINF:3,
indextest_00002.ts
```

Is this what you are asking?

**Comment by superciccio** [comment]
yes. I do believe that you cannot use 'indextest_00002.ts' it needs to be the URL of the file.
cloudfront URL. try and see, that fixed my issue :)

**Comment by ericderegt** [comment]
This is a little off topic now if it's not a problem with video_player, but do you have any advice on how to implement that with CloudFront? Thank you!

**Comment by superciccio** [comment]
hello once again, is defo not a prob with video_player

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.010000,
https://firebasestorage.googleapis.com/v0/b/my-physio-191810.appspot.com/o/Functional%2Ffilename0.ts?alt=media&token=5da6dfd4-c6d5-4b8e-805a-a12af4af7fd1
#EXTINF:9.376000,
https://firebasestorage.googleapis.com/v0/b/my-physio-191810.appspot.com/o/Functional%2Ffilename1.ts?alt=media&token=007de40e-64de-4a49-abf8-1646d4f62018
#59068 `

you just need to adapt the link to your file.

1. upload all your files but not the playlist one
2. copy link of the file from cloudfront
3. edit the playlist with new link
4. and it should work, you can easily try in vlc os similar

**Comment by ericderegt** [comment]
Ok thank you, I will try that

**Comment by jhulzafer** [comment]
i need to play video, my player is screen fixed on load, i uses the video_player with m3u8
