### ISSUE TITLE
devicelab/test/run_test.dart is flaky

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5901]
[This test](https://github.com/flutter/flutter/blob/1ba1562293a6ae64531d8032f79fab7f2fb4ef38/dev/devicelab/test/run_test.dart#L36) is flaky.

```
00:03 +23 -1: run.dart script Exits with code 1 when fails to connect
  Expected: <1>
    Actual: <0>

  package:test             expect
  test/run_test.dart 37:7  main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async               _Completer.completeError
  test/run_test.dart 38:6  main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async               _asyncThenWrapperHelper
  test/run_test.dart       main.<fn>.<fn>
```

**Comment by eseidelGoogle** [comment]
CC @yjbanov

**Comment by yjbanov** [comment]
Thanks for catching it. I'll check it out.

**Comment by Hixie** [comment]
I'm marking this test as skip:true for now, in https://github.com/flutter/flutter/pull/5933.

**Comment by yjbanov** [comment]
This test might be flaky after all: https://travis-ci.org/flutter/flutter/builds/168685024. So far I've only seen it on Travis, not on any of my local machines, Linux or Mac. Reopening.

**Comment by eseidelGoogle** [comment]
@goderbauer and @yjbanov worked on deflaking tests a bunch recently.  Is this still an issue?

**Comment by Hixie** [comment]
I'm not really convinced this is flaky so much as just broken.

**Comment by godofredoc** [comment]
This bug has not been updated in over a year, closing it and we will open a new one if required.
