### ISSUE TITLE
all routes failed 

### ISSUE THREAD

**Issue by saadmohmed** [flutter/flutter#59033]
package:flutter/src/widgets/navigator.dart': Failed assertion: line 3803 pos 12: '!_debugLocked': is not true.

**Comment by TahaTesser** [comment]
Hi @saadmohmed 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by saadmohmed** [comment]
thank you @TahaTesser  problem solved by using this 
  SchedulerBinding.instance.addPostFrameCallback((_) {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (context) => Verfication(),
                      ),
                    );
                  });
