### ISSUE TITLE
Allow unit tests in platform/android/** C++ code

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59031]
Currently, unit tests are compiled with the host toolchain, which means that unit test targets cannot depend on the Android toolchain. However, JNI is a direct dependency of most of the C++ code under `platform/android/**`.   

The proposed solution is to have an interface and a concrete implementation.  This way, the JNI implementation can be "faked" in the unit test.

**Comment by blasten** [comment]
cc @xster

**Comment by xster** [comment]
The approach is pretty reasonable. There are still a bunch of other dependencies on the ndk that would be nice to remove to allow unit testing of most of the C++ classes.

- [ ] `<EGL/>` in android_context_gl, android_environment_gl.h
- [ ] `<GLES/>` android_external_texture_gl.cc, android_external_texture_gl.h, android_surface_gl.cc
- [ ] `<android/>` in apk_asset_provider.h, platform_view_android_jni_impl.cc
- [ ] `<dlfcn.h>` in platform_view_android_jni_impl.cc

**Comment by xster** [comment]
Another way that might not be a dead-end yet. Actually build the C++ classes with NDK dependencies using the NDK, but see if the NDK might be able to target the desktop host rather than Android devices https://developer.android.com/ndk/guides/other_build_systems.

**Comment by blasten** [comment]
I tried to achieve something similar. Unfortunately, the issue is that without the full environment, the call to those APIs need to be mocked. Also, these subpackages serve as a thin layer.  Therefore, the test ends up being something like:
```
test() {
   mock1
   mock2
   ///  ? assert that those APIs are called?
}
```

but those APIs are the wrappers/mockable interfaces, where implementations call the real API.

**Comment by jonahwilliams** [comment]
We have unit tests in android code now, we don't need an umbrella issue tracking adding more though.
