### ISSUE TITLE
\.android\Flutter\build\intermediates\flutter\profile\libs.jar (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by lishuliang28** [flutter/flutter#59042]
## Steps to Reproduce

I added the flutter to the existing project. Prompt when I pack  release。
Tips：\.android\Flutter\build\intermediates\flutter\profile\libs.jar (系统找不到指定的路径。)

Prompt: can't find lib under profile。

## Logs

```
```

```
```

**Comment by lishuliang28** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalAnzhiRelease'.
> Could not resolve all artifacts for configuration ':flutter:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\D\xiaoban_git\android\XbMobile\XbFlutter\.android\Flutter\build\intermediates\flutter\profile\libs.jar.
         > Failed to transform 'C:\D\xiaoban_git\android\XbMobile\XbFlutter\.android\Flutter\build\intermediates\flutter\profile\libs.jar' using Jetifier. Reason: FileNotFoundException, message: C:\D\xiaoban_git\android\XbMobile\XbFlutter\.android\Flutter\build\intermediates\flutter\profile\libs.jar (系统找不到指定的路径。). (Run with --stacktrace for more details.)
           Please file a bug at http://issuetracker.google.com/issues/new?component=460323.

**Comment by TahaTesser** [comment]
Hi @lishuliang28 
Can you please provide your `flutter doctor -v and a minimal complete reproducible code sample from flutter module and android native, which method of build you using?
Thank you

**Comment by lishuliang28** [comment]
Hello
1、flutter doctor -v
C:\D\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.836], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at C:\D\flutter\flutter
    • Framework revision f139b11009 (2 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Robust\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Robust\AppData\Local\Android\Sdk
    • Java binary at: C:\D\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\D\android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[!] VS Code (version 1.43.0)
    • VS Code at C:\Users\Robust\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0
2、The debug mode is fine. I'm going online now to pack the release. Is it necessary to pack the fluent first through native packaging? And then through native packaging?

**Comment by lishuliang28** [comment]
3、a minimal complete reproducible code sample
public class ActivityFlutter extends FlutterActivity {

    private static String TAG = ActivityFlutter.class.getSimpleName();


    public static NewMyEngineIntentBuilder withNewEngine(Class<? extends FlutterActivity> activityClass) {
        return new NewMyEngineIntentBuilder(activityClass);
    }


    //重写创建引擎方法
    public static class NewMyEngineIntentBuilder extends NewEngineIntentBuilder {

        protected NewMyEngineIntentBuilder(Class<? extends FlutterActivity> activityClass) {
            super(activityClass);
        }

    }

    public static void startActivity(Context context, String route) {


        Intent intent = ActivityFlutter
                .withNewEngine(ActivityFlutter.class)
                .initialRoute(route)
                .build(context);
        intent.putExtra("background_mode", "transparent");
        intent.putExtra("route", route);
        context.startActivity(intent);


    }

    private static final String Method_CHANNEL = "xb/native";
    private static final String Event_CHANNEL = "xb/native_post";


    private String route = "";



    EventChannel.EventSink curEvents;

    @Override
    public void configureFlutterEngine(FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        new EventChannel(flutterEngine.getDartExecutor(), Event_CHANNEL).setStreamHandler(
                new EventChannel.StreamHandler() {
                    @Override
                    public void onListen(Object arguments, EventChannel.EventSink events) {
                        curEvents = events;
                        if ("myinfos".equals(route)) {//个人信息
                            JSONObject jsonObject = new JSONObject();
                            try {
                                jsonObject.put("type", "0");
                                jsonObject.put("userId", BaseApplication.getInstance().getMshareutil().getUsertid());
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                            events.success(jsonObject.toString());
                        }

                    }

                    @Override
                    public void onCancel(Object arguments) {

                    }
                }
        );

        new MethodChannel(flutterEngine.getDartExecutor(), Method_CHANNEL).setMethodCallHandler(
                new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        if (call.method.equals("backToViewController")) {

                            result.success(true);
                            finish();
                        }  else {
                            result.notImplemented();
                        }
                    }
                }
        );
    }



   
}

**Comment by lishuliang28** [comment]
4、I want to package only abifilters' armeabi '. What should I do? Does the release do not support armeabi now?

**Comment by TahaTesser** [comment]
Hi @lishuliang28 
Please check [Integrate a Flutter module into your Android project](https://flutter.dev/docs/development/add-to-app/android/project-setup)

You can add 
```
android {
  //...
  defaultConfig {
    ndk {
      // Filter for architectures supported by Flutter.
      abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
    }
  }
}

```

Thank you

**Comment by lishuliang28** [comment]
Thank you。

**Comment by JamesGZM** [comment]
I switched gradle to 3.5.0
It's normal
