### ISSUE TITLE
[Feature Request] Add BuildContext to FormFieldValidator function

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#59059]
# Suggestion

I'm suggesting adding a `BuildContext` argument to the `FormFieldValidator` function. From what I can tell it's called in a place where the context exist, so it shouldn't be much of a problem

# Use Case/Reason

I've created a specialized type of `FormField`, `GenderFormField`, much like the `TextFormField`.

In it, I'm also providing a default validation, verifying a non-null result (it depends on the arguments provided in the constructor, but still).

If that is true, I'm providing a function to the `validator` argument in the form of a static function. Since it's static I can't access the context nor a locale, so I can't return locale-specific error strings.

Example code:
```
  GenderFormField({
    Key key,
    this.controller,
    Gender initialValue,
    bool enabled,
    FormFieldSetter<Gender> onSaved,
    bool autovalidate = false,
  }) : super(
          key: key,
          initialValue: controller != null ? controller.value : initialValue,
          onSaved: onSaved,
          autovalidate: autovalidate,
          enabled: enabled ?? true,
          validator: _defaultValidator,
          builder: (state) {
...
...
```

The default validator is a simple one, but currently it return constant strings rather than using the context and getting the locale and getting locale-specific strings.

# Current Solution

Currently as a solution I've created a static function to return the default validator,
and everywhere where I'm using the form field I'm calling it with
`validator: GenderFormField.createDefaultValidator(context),`

```
  static FormFieldValidator<Gender> createDefaultValidator(BuildContext context) {
    final locale = MyLocale.of(context);

    return (Gender value) {
      .. impl ...
    };
  }
```

**Comment by KevenMelo** [comment]
I'd like to work on this issue. Can I start implementing it?

**Comment by justinmc** [comment]
@KevenMelo Typically if the issue is unassigned you should go for it, but in this case there is a pull request open already: https://github.com/flutter/flutter/pull/157366

**Comment by justinmc** [comment]
After seeing the discussion in https://github.com/flutter/flutter/pull/157366 and playing around with this myself, I believe this should be closed and BuildContext should not be added to `validator`. I think that BuildContext is not inherently part of validation, and if you need it, it's easy to get. Adding BuildContext would cause breakages, bloat the API, and encourage the addition of BuildContext to many other APIs.

I've left some code below, including a new example of how to work around this if you have to extend FormField. If anyone disagrees feel free to leave a comment.

<details>

<summary>What I believe OP @matanshukry is doing</summary>

```dart
class DefaultValidatorGenderFormField extends FormField<Gender> {
  DefaultValidatorGenderFormField({
    super.key,
    required Gender value,
    required super.validator,
  }) : super(
    builder: (FormFieldState<Gender> state) {
      return Switch(
        onChanged: (bool nextValue) {
        },
        value: value == Gender.male,
      );
    },
  );

  static FormFieldValidator<Gender> createDefaultValidator(BuildContext context) {
    return (Gender? gender) {
      // Where this method gets passed in manually to validator each time.
      return null;
    };
  }
}

// Usage:
// DefaultValidatorGenderFormField(
//   validator: DefaultValidatorGenderFormField.createDefaultValidator(context),
// );

```

</details>

<details>

<summary>@natethegrate's suggestion</summary>

```dart
class NateGenderFormField extends StatelessWidget {
  const NateGenderFormField({
    super.key,
  });

  final Gender value = Gender.male;

  @override
  Widget build(BuildContext context) {
    return FormField<Gender>(
      validator: (Gender? gender) {
        // Here you have BuildContext available.
        return null;
      },
      builder: (FormFieldState<Gender> state) {
        return Switch(
          onChanged: (bool nextValue) {
          },
          value: value == Gender.male,
        );
      },
    );
  }
}

// Usage: NateGenderFormField(value: value);
```

</details>

<details>

<summary>Another option from me, if you have to extend FormField</summary>

```dart
class ContextGenderFormField extends FormField<Gender> {
  ContextGenderFormField({
    super.key,
    required Gender value,
    required BuildContext context,
  }) : super(
    validator: createDefaultValidator(context),
    builder: (FormFieldState<Gender> state) {
      return Switch(
        onChanged: (bool nextValue) {
        },
        value: value == Gender.male,
      );
    },
  );


  static FormFieldValidator<Gender> createDefaultValidator(BuildContext context) {
    return (Gender? gender) {
      return null;
    };
  }
}

// Usage:
// ContextGenderFormField(
//   context: context,
//   value: value,
// );
```

</details>
