### ISSUE TITLE
Can't do flutter run

### ISSUE THREAD

**Issue by Aaryam** [flutter/flutter#59052]
Whenever I try to enter run my app with flutter run, it throws an error message and doesn't run.

Result of flutter doctor -v:

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E266, locale en-IN)
    • Flutter version 1.17.1 at /Users/aaryanaaman/Downloads/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaryanaaman/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Aaryan’s iPhone • 37f68fd38897555f776b855921fdf1564ac918d2 • ios • iOS
      12.4.5

• No issues found!
aaryanaaman@Aaryans-iMac charcoal % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E266, locale en-IN)
    • Flutter version 1.17.1 at /Users/aaryanaaman/Downloads/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaryanaaman/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

 
[✓] Connected device (1 available)            
    • Aaryan’s iPhone • 37f68fd38897555f776b855921fdf1564ac918d2 • ios • iOS
      12.4.5

• No issues found!

Flutter version: 1.17.1

Error message:

ProcessException: Process timed out:
2020-06-09 11:15:46.450 xcodebuild[33970:431559]  DTDeviceKit: deviceType from
37f68fd38897555f776b855921fdf1564ac918d2 was NULL
2020-06-09 11:15:46.516 xcodebuild[33970:431686]  DTDeviceKit: deviceType from
37f68fd38897555f776b855921fdf1564ac918d2 was NULL
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet
  DEVELOPMENT_TEAM=DTVFKCJRRR -workspace Runner.xcworkspace -scheme Runner
  BUILD_DIR=/Users/aaryanaaman/Documents/Flutter Projects/charcoal/build/ios
  -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64
  SCRIPT_OUTPUT_STREAM_FILE=/var/folders/xv/m9v05f_55y134581tq8q0nch0000gn/T/flu
  tter_build_log_pipe.SbvwxL/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true
  COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

I used flutter clean, but it still didn't work, then I reinstalled the flutter sdk, it still didn't work.

**Comment by johnmelodyme** [comment]
Try Build it in xcode, and had you accept the Profile ?

**Comment by Aaryam** [comment]
I tried building it in Xcode, and it did work. But the problem is that I want to use Hot reload.

**Comment by Aaryam** [comment]
I just ran it again, after setting up a team in Xcode and building it in Xcode. Finally worked. Thank you!
