### ISSUE TITLE
Uploaded IPA to apple via Flutter platform return with Missing Purpose reject

### ISSUE THREAD

**Issue by Dorshitrit** [flutter/flutter#59054]
NSContactsUsageDescription, NSCalendarsUsageDescription, NSAppleMusicUsageDescription, NSMotionUsageDescription, NSSpeechRecognitionUsageDescription,Missing Push Notification Entitlement

I don't ask for this.
I don't use library that need permissions like that
dio moor_flutter provider intl alice encrypt flutter_launcher_icons

what should I do?

thanks

**Comment by rostopira** [comment]
Add this strings in Info.plist with text like "App doesn't use this permission" or any other text. As long as your app don't request this permissions Apple will accept your app.

**Comment by VladyslavBondarenko** [comment]
@Dorshitrit use this mentioned workaround or find which plugin which permissions requires and file an issue in the plugin's repository about this.
Closing since it seems to be not an issue with flutter,
if you disagree please write in the comments and I will reopen it
