### ISSUE TITLE
ERROR: export 'dart:ui' show Brightness; 

### ISSUE THREAD

**Issue by johnmelodyme** [flutter/flutter#59053]
https://github.com/flutter/flutter/blob/5e3e5a2a1a977c34b22f3709109fd237b5cab9c6/packages/flutter/lib/src/services/system_chrome.dart#L12

```
/C:/src/flutter_windows_1.17.3-stable/flutter/packages/flutter/lib/src/services/system_chrome.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Brightness;
```

**Comment by TahaTesser** [comment]
Hi @johnmelodyme 
Can you please provide your `flutter doctor -v`, your `flutter run --release --verbose` and your `pubspec.yaml`.
Thank you

**Comment by johnmelodyme** [comment]
``1`
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.836], locale en-MY)
    • Flutter version 1.17.3 at C:\src\flutter_windows_1.17.3-stable\flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\johnc\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\johnc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment]
Hi @johnmelodyme 
Can you please provide minimal complete reproducible code sample.
Thank you

**Comment by johnmelodyme** [comment]
```

import "package:encrypt/encrypt.dart" as Security;
import 'package:monjo/monjo_utilities/monjo_encryption/encryption_model/model/monjo_rsa.dart';
import "../monjo_utilities/monjo_encryption/helper/monjo_da_key.dart" as keyHelper;
import 'dart:math';
import 'dart:convert' show base64Url;

/// Aes Algorithm:
class monjo_aes {
  static keyHelper.monjo_da_key_helper __h = new keyHelper.monjo_da_key_helper();
  static var random = Random.secure();
  static var values = List<int>.generate(32, (i) => random.nextInt(256));
  static var dak = __h.dakey();

  // @ Method : Encryptin aes"
  void encrypt(String string, var iv) {
    int length = 16;
    iv = Security.IV.fromLength(length) as String;
    var thekey = Security.Key.fromUtf8(base64Url.encode(values).toString());
    var encryptor = Security.Encrypter(Security.AES(thekey));
  }
}


void main () {
//  print("Nothing Yet");
// test
monjo_aes mm = new monjo_aes();
mm.encrypt("", "");
}
```

**Comment by johnmelodyme** [comment]
> Hi @johnmelodyme
> Your code sample doesn't have `system_chrome` import
> Can you please provide minimal runnable complete reproducible code sample without using third patty packages
> Thank you

Probably Need to use other ```library```  it seems. Thank you
