### ISSUE TITLE
Hot key doesn't work in MacOS when I use Russian keyboard

### ISSUE THREAD

**Issue by Gorniv** [flutter/flutter#59065]
## Steps to Reproduce
I use TextFormField for edit text in https://github.com/doppio-dev/iXn/tree/develop

1. Copy text anywhere.
2. Set Russian keyboard lang in the system.(English is OK)
3. Set cursor to TextFormField
4. CMD+V

**Expected results:** text inserted

**Actual results:** nothing
<details>

```bash
[✓] Flutter (Channel master, 1.19.0-6.0.pre.27, on Mac OS X 10.15.5 19F101, locale en-RU)
    • Flutter version 1.19.0-6.0.pre.27 at /Users/gorniv/github/flutter
    • Framework revision 5e3e5a2a1a (11 hours ago), 2020-06-08 17:38:23 -0700
    • Engine revision 580ab9c3c5
    • Dart version 2.9.0 (build 2.9.0-13.0.dev df435c9235)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gorniv/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/gorniv/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/gorniv/Library/Android/sdk
    • Java binary at: /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio 4.0
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
```
</details>

**Comment by cbracken** [comment]
Unassigning myself, but I've got non-US keyboard that will make testing this more straightforward than for others on the team.

**Comment by maximkaloteq** [comment]
@eseidelGoogle I have the same issue. Any news about this issue?

**Comment by alexeylopukh** [comment]
@dkwingsmt I think this is a very high priority. Are there any predictions?

**Comment by alexeylopukh-aloteq** [comment]
@dkwingsmt hello, any updates for this issue? It will soon be a year since this issue is open.

**Comment by dkwingsmt** [comment]
Hi, sorry it's taken so long. I've analyzed this issue and, while I found it to be very complicated, understand that this problem basically makes Russian keyboard unusable.

I've prioritized this issue and I'm actively working on it right now. I've collected similar issues into a new one https://github.com/flutter/flutter/issues/100456 with some technical explanations, and have made some attempts. The current attempt is very close to succeeding, but I'm still rounding up some corners.

**Comment by dkwingsmt** [comment]
Update: As of the latest master, alphabetic hotkeys (such as Ctrl-C) should be usable on macOS desktop, and soon for Linux desktop after https://github.com/flutter/flutter/pull/102709 is merged. Web will take some significant effort though. We're still in discussion of how to best derive symbol hotkeys.

I'm closing this issue since it only mentions Russian. This does not mean I'm stopping work on other platforms. Please follow https://github.com/flutter/flutter/issues/100456 for tracking.
