### ISSUE TITLE
[Feature Request] TextField focus color not configurable

### ISSUE THREAD

**Issue by natintosh** [flutter/flutter#59060]
## Use case

Currently, I am unable to set `focusColor` for my `TextField`. Whenever I'm using a white primary colour, the focus colour of my `TextField` will be white and still can't set an alternative `focusColor` without setting up `InputBorder` such as `enableBorder`

```dart
ThemeData(
  primaryColor: const Color(0xFFFFFFFF),
  primaryColorLight: const Color(0xFFFFFFFF),
  primaryColorDark: const Color(0xFFDEDEDE),
  primaryColorBrightness: Brightness.light,
  primaryIconTheme: IconThemeData(color: const Color(0xFF000000)),
  accentColor: const Color(0xFF2196F3),
  accentColorBrightness: Brightness.light,
  accentIconTheme: IconThemeData(color: const Color(0xFFFFFFFF)),
  inputDecorationTheme: InputDecorationTheme(
  focusColor: Colors.blue,
  ),
);
```

<img src="https://user-images.githubusercontent.com/27495055/84128802-feec2200-aa38-11ea-9d39-ff0ad743f716.png" width="240" height="470" alt="Screenshot_1587652933"/>

Though an alternative solution like wrapping my `TextField` with a `Theme` widget with the `primaryColor` set my preferred colour for focus.

```dart
Theme(
  data: ThemeData(
    primaryColor: const Colors.blue,
    ),
  child: TextField(),
);
```

**Comment by piedcipher** [comment]
https://api.flutter.dev/flutter/material/InputDecoration/focusedBorder.html can be used for this.

focusColor regarding confusion has been cleared in the documentation. Closing this.
