### ISSUE TITLE
Pesto logo has inconsistent sharpness.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5906]
Due to the fact that we're now rendering Pesto logo's label as a `Text` widget, it different in sharpness to the linearly filtered image when its scaled up.

We should probably replace the asset with a higher resolution version.

**Comment by eseidelGoogle** [comment]
I'm not sure I understand this issue.  Have you hit this @sethladd?

**Comment by dragostis** [comment]
@eseidelGoogle The difference is very subtle but noticeable on higher resolution screens. Higher res Pesto logo should fix this.

![20161104_223236](https://cloud.githubusercontent.com/assets/4136413/20021564/0211715c-a2df-11e6-9c19-ec2598147e47.png)

**Comment by zoechi** [comment]
I assume this is stale.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/demos.dart#L530-L531
