### ISSUE TITLE
Issue publishing package to pub.dev

### ISSUE THREAD

**Issue by Kwasow** [flutter/flutter#59076]
Hi,
I wanted to publish an update to my package that I last developed around half a year ago, but I don't have access to the Google account I used back then anymore. I'm looking for an email address or something else, so I can contact the pub.dev team and resolve the issue somehow.

**Comment by TahaTesser** [comment]
Hi @Kwasow 
Please raise your issue pub.dev issue on their [GitHub](https://github.com/dart-lang/pub-dev/issues)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it
Thank you
