### ISSUE TITLE
[web]: Unavailability of draggable scrollbar

### ISSUE THREAD

**Issue by manishpandeyvp** [flutter/flutter#59079]
I always have to use my trackpad to scroll the page of my web app. I don’t know if there is an option for arrow key navigation and a draggable scrollbar for scrolling the page up and down.

**Comment by iapicca** [comment]
Hi @manishpandeyvp 
I see there's an open [issue](https://github.com/flutter/flutter/issues/40107) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

related to https://github.com/flutter/flutter/issues/43694
