### ISSUE TITLE
[cocoon] Sign in button on build page is unresponsive

### ISSUE THREAD

**Issue by helin24** [flutter/flutter#59086]
This page has a sign in button on the top right (when user is not signed in) but it doesn't seem to do anything: https://flutter-dashboard.appspot.com/#/build

As a workaround, we were able to sign in from the [benchmarks page](https://flutter-dashboard.appspot.com/benchmarks.html).

**Comment by CaseyHillers** [comment]
Here's some notes on debugging I did:

I can only reproduce this when a user comes in not signed in. If already signed in, I can log out, and sign back in just fine.

I updated Google sign in on Flutter from 4.2 to the latest version the issue still exists.

I tried disabling cocoon's call to silent sign in on the latest sign in version, and was able to use the sign in button.

\cc @ditman do you know if there's a way to work around this? Should Cocoon be wrapping silent sign in calls in a try catch? Source at https://github.com/flutter/cocoon/blob/master/app_flutter/lib/service/google_authentication.dart#L21

**Comment by ditman** [comment]
We have a couple of issues with the google_sign_in plugin; one of them is that it might be swallowing exceptions that should be surfaced (so they can be captured with try/catch). I haven't looked into those yet.

(Current most common culprits: 1) Incognito window with 3rd party cookies disabled, 2) the privacy badger extension)

**Comment by CaseyHillers** [comment]
I disabled the silent sign in on Cocoon for now. Locally, I had to do a hard refresh on the build dashboard to get this latest change. Additionally, I have seen a few instances where my Google chrome needed another refresh of the page to get the sign in button working.

**Comment by ditman** [comment]
@CaseyHillers that might be the serviceworker cache. Another way to defeat it, IIRC, is to do a refresh (that downloads the service worker), then closing and re-opening the browser window (that enables the latest one).

**Comment by CaseyHillers** [comment]
Hi all, i'm lowering the priority of this as I landed a mitigation PR for the dashboard.

Now you should always be able to sign in as the silent sign in function has been disabled. However, you always have to sign yourself in whenever you need to do any authenticated action on the dashboard.

If there's still issues where the sign in button is not working, please let me know here so I can look into it.

**Comment by ditman** [comment]
I've just posted a PR with some changes to the google sign in plugin that should make this issue more debuggable:

https://github.com/flutter/plugins/pull/2943

The new code should throw more predictable PlatformExceptions in the methods of the plugin, maybe applying the code may give more clues as to why sign in is not working as expected with cocoon.

**Comment by CaseyHillers** [comment]
Today i'm not able to use the sign in button when I load incognito. My normal chrome browser works.

```
Uncaught TypeError: s.gz8 is not a function
    at U2.$1 (google_sign_in_web.dart:113)
    at Object.atc (js_helper.dart:841)
    at Object.adA (core_patch.dart:83)
    at avL (js_patch.dart:541)
    at js_patch.dart:519
    at e.ko (cb=gapi.loaded_0:201)
    at ik (cb=gapi.loaded_0:204)
    at dk (cb=gapi.loaded_0:204)
    at _.Oj.nT (cb=gapi.loaded_0:204)
    at Nj (cb=gapi.loaded_0:196)
```

**Comment by ditman** [comment]
@CaseyHillers are you "Blocking third-party cookies" when in incognito mode? It might be a setting in the incognito new tab, or within the browser:

<img width="624" alt="Screen Shot 2020-09-10 at 2 15 26 PM" src="https://user-images.githubusercontent.com/1255594/92807873-199fa100-f370-11ea-8acb-661bbef7d743.png">

**Comment by CaseyHillers** [comment]
Thanks David, that seemed to be the issue. I did encounter the issue where I had to refresh the page again to get it working.

@a14n is your browser blocking 3rd party cookies?

**Comment by ditman** [comment]
I'll try to merge my "fix" ASAP so errors thrown by the JS SDK are not swallowed in the depths of some JS-Interop issue :) (which was my bad, btw :P)

**Comment by a14n** [comment]
My Chrome settings was _Blocking third-party cookies in incognito mode_. But I was not on incognito mode when the issue arised. Switching back and forth to _allow all cookies_ allowed me to sign in. And now that I reverted to _Blocking third-party cookies in incognito mode_ I am still able to logout/signin in normal mode. I really don't know what's happening :-/ but I'm now signed in \o/ Thanks.

**Comment by CaseyHillers** [comment]
One thing to try is doing a hard refresh of the page to load the latest assets, then a regular refresh for the service worker to take effect.

**Comment by ditman** [comment]
If you're at a point where you're thinking of doing a hard refresh to fix things, I'd recommend to visit the app with the Chrome DevTools open, not only to see if any errors are printed on the JS console (they might not very good currently) but also it lets you disable the network cache (Network panel) and update service workers (Application panel)

**Comment by CaseyHillers** [comment]
Increasing priority as now it's possible to handle these exceptions in the dashboard.

**Comment by CaseyHillers** [comment]
Closing this out as I haven't seen any reports of issues with the sign in flow (thank you @ditman for all your work on the plugin side!).

If you're still encountering issues, grab the error from dev tools console and paste it here.
