### ISSUE TITLE
Error libusbmuxd

### ISSUE THREAD

**Issue by n0rf3n** [flutter/flutter#59105]
Hi flutter

I'm installing and configuring flutter on a clean installation of Mac OS Catalina 10.15.5 and when I run the command "brew install --HEAD libimobiledevice" an error is generated with the libusbmuxd dependency, here are the steps and logs of the error, I hope you can help

## Steps to Reproduce

1. Install Mac OSx Catalina 10.15.5
2. Perform all the configuration steps of the flutter doctor command.
3. Execute the command "brew install --HEAD usbmuxd
4. Execute the command "brew link usbmuxd"
5. Execute the command "brew install --HEAD libimobiledevice" in this step generates the error.

## Logs

➜  ~ brew install --HEAD libimobiledevice
Updating Homebrew...
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/n0rf3n/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at bc32998 Bump version to 1.3.0 and update NEWS file according to actual releases
==> ./autogen.sh
Last 15 lines from /Users/n0rf3n/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh:
checking dynamic linker characteristics... darwin19.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusbmuxd-2.0 >= 2.0.2... no
configure: error: Package requirements (libusbmuxd-2.0 >= 2.0.2) were not met:

No package 'libusbmuxd-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libusbmuxd_CFLAGS
and libusbmuxd_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```
```

➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-CO)
    • Flutter version 1.17.3 at /Users/n0rf3n/Documents/FlutterSDK
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/n0rf3n/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 6120F39B-5F39-4AEF-8B57-88DEBEF7F3E2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @n0rf3n 
This doesn't look like an issue with Flutter itself
For issues related to libimobiledevice please raise the issue on their [GitHub](https://github.com/libimobiledevice/libimobiledevice/issues)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by aelam** [comment]
This is a new issue for libimobiledevice, it should be forward to that repo, this is an IMPORTANT one should be fixed soon
