### ISSUE TITLE
[pigeon] make sure the generated code is free of analyzer warnings

### ISSUE THREAD

**Issue by xster** [flutter/flutter#59116]
Since the user checks in the generated code, it could show up in their own code analysis. 

<img width="684" alt="Screen Shot 2020-06-09 at 5 50 51 PM" src="https://user-images.githubusercontent.com/156888/84214955-c3be1300-aa79-11ea-9ef4-b060ad7675d4.png">

**Comment by xster** [comment]
@GaryQian can you check this out too? It might already be solved though since Aaron added linter checks to the tests for Java.

**Comment by GaryQian** [comment]
@gaaclarke Is this still a problem with Pigeon?

**Comment by gaaclarke** [comment]
> @gaaclarke Is this still a problem with Pigeon?

There are probably still analyzer warnings.  There has been some steps that make this not as big of a deal.  Internally the code is generated, not checked in and we've added "generated" annotations which causes them to be treated different.

**Comment by stuartmorgan** [comment]
We should turn on warnings-as-errors in the integration test host plugin for all languages, which would cover most of this.
