### ISSUE TITLE
Do not match the previously installed version; ignoring

### ISSUE THREAD

**Issue by hyuntae0117** [flutter/flutter#59126]
hello

I have a question

How can i change my app (native) to whole flutter app?

I have released app on google playstore

and I am developing a same app using flutter

I don't want to use flutter module on native app 

but when i install on my device using vscode (same package name)

error message shown
[INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.freewheelin.pulley.debug signatures do not match the previously installed version; ignoring!]

Is there anything missing?

**Comment by julianbraasch** [comment]
Debug signing keys may differ. Try again in release mode and make sure that you are using the same keystore. Also, the build number of the new app must be greater than the old one.

**Comment by VladyslavBondarenko** [comment]
@hyuntae0117 
does it help? have you uninstalled your previous app before this?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
