### ISSUE TITLE
Flutter test execution speed depends on the order of tests

### ISSUE THREAD

**Issue by blbnv** [flutter/flutter#59139]
Hi,

Previously I've reported an issue with slow tests [#58242](https://github.com/flutter/flutter/issues/58242) which has been closed due to duplication of [#17130](https://github.com/flutter/flutter/issues/17130).

As I've investigated further, some test's execution speed with --coverage flag could depend on the test that runs before it.

So we have Test1 and Test2 and in two cases results are completely different:

**Scenario 1:**

1. Test1 (10 sec)
2. Test2 (10 sec)

**Scenario 2:**

1. Test2 (2 sec)
2. Test1 (10 sec)

Do you think it could be somehow related to [#17130](https://github.com/flutter/flutter/issues/17130)?

P.S. I am on the stable Flutter v1.17.2 and I am running tests with --coverage flag.

Thank you.

**Comment by jonahwilliams** [comment]
A bug report needs some method of reproducing the behavior document. There are many things that could be causing the behavior you are describing, including bugs within your own tests/code. I'm closing this issue as in-actionable.


(FYI @VladyslavBondarenko please do not pass through issues that have no repro cases)
