### ISSUE TITLE
Feature request: Provide a horizontal option for ListWheelScrollView

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#59146]
Please provide a horizontal scrolling option for https://api.flutter.dev/flutter/widgets/ListWheelScrollView-class.html

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/25074

**Comment by giorgio79** [comment]
Thanks! Also found this solution meanwhile https://pub.dev/packages/carousel_slider
