### ISSUE TITLE
I got an error when i'm trying to run... :( 12 times i uninstalled and install app. But same issues. Got same issue in Android studio and Visual code studio.

### ISSUE THREAD

**Issue by mdmahinurkhan** [flutter/flutter#59152]
```
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > dl.google.com
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > jcenter.bintray.com
   > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > dl.google.com
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > jcenter.bintray.com
   > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > dl.google.com
      > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_64_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by VladyslavBondarenko** [comment]
Hi @mdmahinurkhan 
it may be the case of using flutter behind a country firewall, does using https://flutter.dev/community/china help?

**Comment by MD-ARMAN-Shanto** [comment]
using vpn but facing the same issues.

**Comment by mdmahinurkhan** [comment]
> 
> 
> using vpn but facing the same issue.

Did you get a solution? I tried VPN also, but not working :( Let me know if you get solution in either way

**Comment by mdmahinurkhan** [comment]
Hey, I got solutions by downloading 28 versions of sdk and android phone. API version 28 and Android pie.

**Comment by Himanshunitrr** [comment]
I have the same issue and its been 2 days. Please help me

**Comment by mdmahinurkhan** [comment]
Sure, you'll select 28 API mobile virtual emulator and SDK. and SDK tool 28.0.3 and remove all update SDK versions, like 30 API levels.

**Comment by Himanshunitrr** [comment]
I did all this but still getting this error

**Comment by Himanshunitrr** [comment]
The error log is like

PS D:\Documents\LearnFlutter\awsome_app> flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
   > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         9.4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Himanshunitrr** [comment]
Please help me !! I dont want to waste my third day too

**Comment by mdmahinurkhan** [comment]
Can you reinstall by following my step, i hope it'll work for you!

**Comment by Himanshunitrr** [comment]
Problem solved. Deleted gradle cache and ran flutter precache

**Comment by mdmahinurkhan** [comment]
Ahh great! Now enjoy!!

**Comment by v7lin** [comment]
Here is my solution

android/build_compat.gradle
```gradle
String storageUrl = 'https://storage.flutter-io.cn' //System.getenv('FLUTTER_STORAGE_BASE_URL') ?: "https://storage.googleapis.com"

project.subprojects { p ->
    p.repositories {
        maven {
            url "$storageUrl/download.flutter.io"
        }
    }
}
```

android/build.gradle
```gradle
apply from: 'build_compat.gradle'
```
