### ISSUE TITLE
TextField shows old input after hot-restart

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#59150]
In a TextField when you type a text and you do  a hot-restart the TextField becomes empty but as son as the same TextField is focused the old text appears.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a TextField
3. Run the project and type something in the TextField
4. Do Hot-Restart
5. Tap the TextField 

**Expected results:** I expect the TextField to be empty.

**Actual results:** The old text is pasted in the TextField as soon as the TextField gains focus.

<details>
  <summary>Logs</summary>

```
I can't share any information related to this project. Also this is not required to reproduce the issue.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.45.1)
[!] Connected device

! Doctor found issues in 3 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @pedromassango 
please follow up on https://github.com/flutter/flutter/issues/42787,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
