### ISSUE TITLE
Main target's (Runner) pods are used in WatchKit

### ISSUE THREAD

**Issue by GenixPL** [flutter/flutter#59151]
I'm not sure whether it's a bug or just my lack of knowledge on how to handle pods, but when I add WatchKit to my Flutter project, build terminates with `Framework not found XYZ` error. 
[(Similar case)](https://github.com/flutter/flutter/issues/48880)

For me it seems that Runner's pods are copied to Watch Extension, which in some cases results in errors, because some frameworks are not available on WatchOS (e.g. CoreTelephony).

Minimal reproduction:
1. Create new Flutter project
2. Add `firebase_core` into `pubspec.yaml` and run `flutter pub get` or `flutter run` (Everything is fine so far, project is built and can run properly)
3. Open Xcode and add WatchKit into the app
4. Run project (build terminates with `Framework not found XYZ` error)

<img width="841" alt="Screenshot 2020-06-10 at 12 04 11" src="https://user-images.githubusercontent.com/24494656/84256966-ee10de80-ab14-11ea-99e9-c0a87bc9ee61.png">

There is also an interesting case when we don't have any dependencies specified in `pubspec.yaml`:
1. Create new Flutter project and run `flutter pub get` or `flutter run` (Everything is fine so far, project is built and can run properly)
2. Open Xcode and add WatchKit into the app
3. Run project (build terminates with `Framework not found Flutter` error)
4. Add `Flutter.framework` to watch extension's `Frameworks, Libraries, and Embedded Content`
5. Run project (build terminates with error `/Users/genix/Projects/minimal/ios/Runner.xcodeproj Building for watchOS Simulator, but the linked and embedded framework 'Flutter.framework' was built for iOS + iOS Simulator.`)
6. Remove `Flutter.framework` from watch extension
7. Run project (everything is fine and project can run properly)

Flutter doctor -v:

> [✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-PL)
>     • Flutter version 1.17.1 at /Users/genix/dev-tools/flutter
>     • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
>     • Engine revision 6bc433c6b6
>     • Dart version 2.8.2
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/genix/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.9.3
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.3.4)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 43.0.3
>     • Dart plugin version 193.6015.53
> 
> [✓] VS Code (version 1.45.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.11.0
> 
> [✓] Connected device (3 available)
>     • Apple Watch Series 5 - 44mm • 8744A704-98AF-4953-B0E8-DC5F1737EE93 • ios •
>       com.apple.CoreSimulator.SimRuntime.watchOS-6-2 (unsupported) (simulator)
>     • iPhone 11 Pro Max           • 68BA2E48-2FBC-4BC9-BFF2-A251D7750CB6 • ios •
>       com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
>     • iPhone SE (2nd generation)  • DF234B4F-FE91-4169-8DAF-A911B4435896 • ios •
>       com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
> 
> • No issues found!

**Comment by jmagman** [comment]
Is your _project's_ base configuration set to Debug.xcconfig and Release.xcconfig?  If so, your watchOS app is inheriting the Flutter build settings.  You can remove the base configuration and set just the Runner target to Debug.xcconfig and Release.xcconfig.

![Screen Shot 2020-04-13 at 11 57 12 AM](https://user-images.githubusercontent.com/682784/79163898-c57a9b80-7d94-11ea-8267-15e0c2324d7a.png)

This was migrated automatically in https://github.com/flutter/flutter/pull/54691, which is available on 1.18.0-6.0.pre in the [master, dev, and beta channels.](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos)

> Add Flutter.framework to watch extension's Frameworks, Libraries, and Embedded Content

You should be able to have a watch target in a Flutter project, but Flutter itself  isn't supported on watchOS, so you can't embed it.

**Comment by GenixPL** [comment]
Works! Thank you very much :)
