### ISSUE TITLE
I get a curl error when trying to run "flutter upgrade"

### ISSUE THREAD

**Issue by carlomigueldy** [flutter/flutter#59167]
## Steps to Reproduce

1. flutter upgrade
2. See error message
![image](https://user-images.githubusercontent.com/45052332/84287793-f26be480-ab72-11ea-95c3-546c09f50536.png)

**Comment by TahaTesser** [comment]
Hi @carlomigueldy 
Can you please provide your `flutter doctor -v`, your `flutter upgrade --verbose`
Thank you

**Comment by carlomigueldy** [comment]
Hello @TahaTesser  

I have fixed it already, it was only about Linux permissions. I just had to execute
`chmod -R 775 ~/flutter` and `chown -R $USER:www-data ~/flutter` and I was able to run the `flutter upgrade` command 

Thanks for the response

**Comment by TahaTesser** [comment]
Hi @carlomigueldy 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
