### ISSUE TITLE
show date time picker for Hebrew not displaying for date

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#59161]
hi,
show date time picker for Hebrew not displaying for date

when device is using auto rotate date is being cut with ... 
![image](https://user-images.githubusercontent.com/47334522/84271691-13ade000-ab35-11ea-8f0e-6806b9073dab.png)

while for regular display it working fine

![image](https://user-images.githubusercontent.com/47334522/84271921-64bdd400-ab35-11ea-9b88-bf4ac5a6ffc0.png)

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Tested your code sample on latest `dev` channel using hebrew system language, no issues

![ezgif com-resize](https://user-images.githubusercontent.com/48603081/84372303-8a5fe180-abf8-11ea-86d3-4437334c3d12.gif)

### Complete code sample



<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en'), // English
        const Locale('he'), // Hebrew
        const Locale.fromSubtags(
            languageCode: 'zh'), // Chinese *See Advanced Locales below*
        // ... other locales the app supports
      ],
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          await showDatePicker(
            context: context,
            helpText: 'בחירת תאריך',
            errorFormatText: 'פורמט לא חוקי',
            fieldLabelText: 'הזן תאריך',
            initialDate: DateTime.now(),
            firstDate: DateTime.now(),
            lastDate: DateTime.now(),
            textDirection: TextDirection.rtl,
            locale: Locale('he', 'IL'),
          );
        },
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-5.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-5.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c264b70ec3 (3 days ago), 2020-06-08 09:27:34 -0700
    • Engine revision c7f9725521
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details> 


Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample and also try another device if possible
Thank you

**Comment by kw2019ltd** [comment]
hi, same issue with you example , iam using One Plus 7T device.

 $ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.3 at /home/cirrus/sdks/flutter
    • Framework revision b041144f83 (3 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
    • All Android licenses accepted.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 2 categories.


![20200611_134545](https://user-images.githubusercontent.com/47334522/84376595-0acb1600-abea-11ea-86a2-2008b6f3cfa3.gif)

**Comment by darrenaustin** [comment]
This was fixed to show two lines in landscape for the header as part of the range picker PR: #55939. As @TahaTesser pointed out, this fix is in the dev channel. Unfortunately it has not yet made it to the beta or stable channels yet.
