### ISSUE TITLE
Hot reload takes too much of time with large project

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#59170]
In vscode hot Reload takes from the range of 20 to 26 seconds.
In Android studio the same project takes 7 to 9 seconds to finish.
This happened before 5months for a large project but after `flutter clean`  it will became normal (1 to 3 seconds),but from the 1.12.xx updates im facing the issue.
RAM was free arround 70% 
tried to set CPU priorities to low,but nothing solved the issue 

## Steps to Reproduce

1. Create or run a project 
2. Make some changes
3. Wait for it to reflect

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] VS Code, 64-bit edition
[√] Connected device (1 available)

• No issues found!

```
```

**Comment by TahaTesser** [comment]
Hi @rajeshjeshar 
Just tested on latest `Channel stable, v1.17.3,` and no issues with hot reload, it's fast using flutter extension `3.11.0` 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5.1

• No issues found!

``` 

</details> 

can you please upgrade to latest `stable`, vs code and  latest flutter extension for vscode

thank you

**Comment by rajeshjeshar** [comment]
@TahaTesser updated as u said but when the project is small (Eg Flutter default example counter),it takes less than 1second 839ms,but
when debugging larger projects it takes longer duration
`Reloaded 1 of 1125 libraries in 9,339ms.`

**Comment by TahaTesser** [comment]
Hi @rajeshjeshar 
Can you please provide your complete `flutter doctor -v` with `Channel stable, v1.17.3` ?
Thank you

**Comment by rajeshjeshar** [comment]
`Reloaded 100 of 1125 libraries in 7,827ms.`

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.0)
[√] VS Code, 64-bit edition
[√] Connected device (1 available)

• No issues found!
```

**Comment by rajeshjeshar** [comment]
Found the reason for long duration,its caused by triggering 8 bloc events at the time of homepage opening,also I have streamed the tabcontroller's current index value via some kind of features,once i changed my approach with paginated bloc triggering and removed the streaming process the hotreload time dropped to 3000 milliseconds,Its high but comparing to 21000 ms,its okay for me.This issue is completely caused by the code structure not by the sdk or other factors!

**Comment by TahaTesser** [comment]
@rajeshjeshar 
Thank you for confirmation

**Comment by johnwangwjq** [comment]
Sorry to break in: Me has the same slow-reload issue(flutter-v3.23.0). Could anybody share a hint on how to spot the bottle-neck?
