### ISSUE TITLE
Flutter Doctor should mention ANDROID_HOME when it can't find the android sdk as a possible reason why it can't find it

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5917]

**Comment by xster** [comment]
The current message says
```
[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
```

https://flutter.io/setup/#android-setup does mention ANDROID_HOME but not in a prominent way. We should surface it in the doctor message. Should also make sure setting up ANDROID_HOME is a prominent setup step on the website (it's very implicit when installing Android Studio on a mac for instance, the user might never notice).

**Comment by sethladd** [comment]
Good call. Let's add to https://github.com/flutter/flutter/issues/7971

**Comment by xster** [comment]
Note we do try to guess it by looking at
~/Android/Sdk
~/Library/Android/sdk
~/AppData/Local/Android/sdk

But if the user puts it anywhere else, we should message in doctor that we're looking for ANDROID_HOME

**Comment by lfo** [comment]
Further more in flutter doctor the message say "Android Studio / Android SDK not found". So, if you mention to specify the ANDROID_HOME, you can give a clue on where ANDROID_HOME should be targetted.
I have tried with 

- "ANDROID_HOME=~/softwares/android/sdk"  and it works. 
- "ANDROID_HOME=~/softwares/android"  and it works. 
- but "ANDROID_HOME=~/softwares/android-studio" not

**Comment by rconcrown** [comment]
On Windows ANDROID_SDK_ROOT nor ANDROID_HOME work!! 
(I couldn't try system environment, only user environment)

Only "flutter config --android-sdk Path/to/sdk" did help!

**Comment by xster** [comment]
Update, the current message does mention ANDROID_SDK_ROOT in the error message now in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/user_messages.dart#L77. 

As pointed out above, it might want to mention setting `flutter config --android-studio-dir` or `flutter config --android-sdk` instead since it can cover more cases.

**Comment by brucearctor** [comment]
Can this be closed?  Did:  https://github.com/flutter/flutter/pull/65964  address the issue?  @apwilson  - since you initially filed this ~ 6 years ago :-)

**Comment by christopherfujino** [comment]
Fixed in https://github.com/flutter/flutter/pull/65964
