### ISSUE TITLE
AppBar background colour incorrect, depends on elevation

### ISSUE THREAD

**Issue by johngithubby** [flutter/flutter#59178]
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        elevation: 0.0, // no shade
        backgroundColor: Color.fromRGBO(248, 248, 248, 0.82),
        textTheme: TextTheme(
            headline6: TextStyle(
                fontSize: 34,
                fontWeight: FontWeight.bold,
                color: Colors.black)),
      ),
      body: Center(
        child: Container(),
      ),
    );
  }
```

The app bar background colour will vary function of elevation. When the elevation is zero it has one colour, when the elevation is not zero, it has another colour. Is this on purpose? How am I supposed to have the same app bar colour in my app on screens that require there be no shadow from the app bar, and screens where a shadow is required?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.14.6 18G5033, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.45.1)

Thanks

**Comment by TahaTesser** [comment]
hI @johngithubby 

![flutter_01](https://user-images.githubusercontent.com/48603081/84376967-8edbc880-abff-11ea-9ded-f161b4860732.png)

![flutter_02](https://user-images.githubusercontent.com/48603081/84376976-91d6b900-abff-11ea-9441-de845657120e.png)

Does this look  like  your issue?

**Comment by johngithubby** [comment]
Yep, that's it. Is there an issue created already for this?

**Comment by cirediew** [comment]
This problem occurs because the appBar is wrapped in a `Material` which changes the colour depending on the elevation.

`Material.dart` in `build()` line 392 
```
color: ElevationOverlay.applyOverlay(context, backgroundColor, widget.elevation)
```

I ran into this problem when I set my widget below the appbar to be the same colour as the appBar.

**Comment by HansMuller** [comment]
Sorry about the slow response: this is indeed intentional, see https://github.com/flutter/flutter/pull/41864

When the overall theme is dark (when it's ColorScheme's brightness is dark) the color of Material widgets is changed a little to help the user sense the Material's elevation.
