### ISSUE TITLE
Flutter going to sleep and not responding

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [flutter/flutter#59174]
While switching between different versions of flutter (stable and beta), my terminal did not respond and it takes forever. Here's the output from my terminal

![Screenshot 2020-06-10 at 22 53 13](https://user-images.githubusercontent.com/52520071/84298785-4d9ad880-ab6d-11ea-89b9-3e840ad07ebd.png)

**Comment by TahaTesser** [comment]
Hi @Deepanshu-Rohilla 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by Deepanshu-Rohilla** [comment]
Ohh thank you @TahaTesser . Running `fluuter doctor -v` actually solved the problem. Sorry I forgot to take the screenshot. I immediately jumped to my project (due to excitement xD)...

**Comment by TahaTesser** [comment]
hi @Deepanshu-Rohilla 
No worries and it normal to take time when download full setup, when in doubt  `flutter doctor -v`  helps to check  flutter setup health  
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
