### ISSUE TITLE
Fix or suppress remaining Windows engine warnings

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#59199]
The Windows host engine build's stdout from a bot is currently about 125MB, and 1.6 million lines, because it has 250,000 warnings. This makes looking for errors—or even just loading it—quite painful.

Main categories:
- ~249,000: ~`specified path differs in case from file name on disk` [This](https://github.com/google/skia/blob/master/gn/BUILD.gn#L387) suggests this is a goma issue, and we just need to suppress the warning.~ [Fixed](https://github.com/flutter/buildroot/pull/375)
- ~900: ~`The POSIX name for this item is deprecated`. Almost all from Dart, mostly `strdup`. The fix is either to suppress them, or wrap them, as discussed in https://dart-review.googlesource.com/c/sdk/+/134781~ [Fixed](https://dart-review.googlesource.com/c/sdk/+/142704)
- ~150: ~`no newline at end of file`. All (or very close to all) from ANGLE. Ideally we should just fix that upstream.~ [Fixed](https://chromium-review.googlesource.com/c/angle/angle/+/2247486).

After that it's just about 20 miscellaneous warnings, mostly conversion warnings in Dart and ANGLE. It would be nice to fix them, but 20 warnings would be a lot better than 250,000

**Comment by stuartmorgan** [comment]
> conversion warnings in Dart and ANGLE

Now that Dart is working on adding a Windows clang-cl build, I expect they will fix the Dart parts of these.

**Comment by stuartmorgan** [comment]
I need to get the ANGLE roll done, then I'll take stock of what's left.

**Comment by stuartmorgan** [comment]
ANGLE roll is finally in. A bot build log is now a much more reasonable 6k lines and 500kb.

The remaining warnings from the run with the ANGLE fixes are:
```
../../flutter/third_party/tonic/filesystem\filesystem/file.h(24,22): warning: 'close' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details. [-Wdeprecated-declarations]
../../flutter/third_party/tonic/file_loader/file_loader.cc(56,5): warning: 'close' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details. [-Wdeprecated-declarations]
2 warnings generated.
../../flutter/third_party/tonic/filesystem\filesystem/file.h(24,22): warning: 'close' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details. [-Wdeprecated-declarations]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime/bin/gen_snapshot.cc(632,26): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
../../third_party/dart/runtime/bin/gen_snapshot.cc(641,15): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
2 warnings generated.
../../third_party/dart/runtime/bin/gen_snapshot.cc(632,26): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
../../third_party/dart/runtime/bin/gen_snapshot.cc(641,15): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
2 warnings generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
1 warning generated.
clang-cl: warning: unknown argument ignored in clang-cl: '-fvisibility=hidden' [-Wunknown-argument]
[3678/5929] CXX obj/third_party/harfbuzz/src/harfbuzz_sources.hb-warning.obj
clang-cl: warning: unknown argument ignored in clang-cl: '-fvisibility=hidden' [-Wunknown-argument]
client_wrapper_glfw_unittests.flutter_window_unittests.obj : warning LNK4217: locally defined symbol FlutterDesktopWindowSetSizeLimits imported in function "private: virtual void __cdecl flutter::FlutterWindowTest_SetSizeLimits_Test::TestBody(void)" (?TestBody@FlutterWindowTest_SetSizeLimits_Test@flutter@@EEAAXXZ)
client_wrapper_windows_unittests.flutter_view_unittests.obj : warning LNK4217: locally defined symbol FlutterDesktopViewGetHWND imported in function "private: virtual void __cdecl flutter::FlutterViewTest_HwndAccessPassesThrough_Test::TestBody(void)" (?TestBody@FlutterViewTest_HwndAccessPassesThrough_Test@flutter@@EEAAXXZ)
client_wrapper_windows_unittests.plugin_registrar_windows_unittests.obj : warning LNK4217: locally defined symbol FlutterDesktopRegistrarGetView imported in function "public: __cdecl flutter::PluginRegistrarWindows::PluginRegistrarWindows(struct FlutterDesktopPluginRegistrar *)" (??0PluginRegistrarWindows@flutter@@QEAA@PEAUFlutterDesktopPluginRegistrar@@@Z)
```

- Tonic is ours despite being in third_party, if I'm understanding correctly? If so we should use `_close` there.
- I've updated https://github.com/dart-lang/sdk/issues/40448 with the remaining Dart bugs.
- The harfbuzz thing is probably a mistake in our build configuration for `clang-cl`
- LNK4217 in the tests is a mistake in how the Windows embedding tests are handling import/export macros, which I should fix.

**Comment by stuartmorgan** [comment]
Removing assignment and milestone since the really important part of this is done; we should certainly still fix the last warnings, but it doesn't necessarily need to be a priority.

**Comment by stuartmorgan** [comment]
> After that it's just about 20 miscellaneous warning

I forgot that log was from an incremental build. I just did a clean, local, debug (not debug_unopt) build and had 656 warnings:
- 430 `unknown argument ignored in clang-cl: '-fvisibility=hidden' [-Wunknown-argument]` from third_party/icu
- 154 `instantiation of variable '[...]' required here, but no definition is available [-Wundefined-var-template]` in third_party/swiftshader/third_party/subzero
- 28 `The POSIX name for this item is deprecated.` for various functions, from third_party/tonic, third_party/swiftshader, and a few left in third_party/dart (as noted [here](https://github.com/dart-lang/sdk/issues/40448#issuecomment-666489167))
- 21 `no newline at end of file [-Wnewline-eof]` in third_party/swiftshader
-12 `implicit conversion from '[some form of int]' to 'float' changes value [...] [-Wimplicit-int-'float-conversion]` in third_party/angle, third_party/icu, and third_party/swiftshader
- 10 `warning: '#pragma optimize' is not supported [-Wignored-pragma-optimize]` in third_party/dart and third_party/icu
- 1 `result of comparison of constant 2305843009213693944 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]` in third_party/libpng

It looks like the main thing is to change the compilation settings we're using for icu and swiftshader.

**Comment by stuartmorgan** [comment]
Looks like we could fix at least the 430 by just rolling ICU forward: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/2250687

**Comment by cbracken** [comment]
```
../../third_party/dart/runtime\vm/compiler/asm_intrinsifier.h(37,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
```
https://dart-review.googlesource.com/c/sdk/+/162901

**Comment by stuartmorgan** [comment]
> It looks like the main thing is to change the compilation settings we're using for icu and swiftshader.

The build files for both are coming from the upstream repos, not our local buildroot, so changes will need to be upstreamed.

**Comment by cbracken** [comment]
Swiftshader is done in flutter/engine#32633

**Comment by cbracken** [comment]
libpng done in https://github.com/flutter/engine/pull/32688

**Comment by cbracken** [comment]
After https://github.com/flutter/engine/pull/32694 lands, ICU, tonic, and Dart are resolved. At this point libangle is the only remaining target with warning spam on Windows. It hasn't rolled in ~a year, so giving that a go first.

**Comment by cbracken** [comment]
As of https://github.com/flutter/engine/pull/32785 ANGLE is rolled and Win32 builds produce no warning output. Closing.

```
$ autoninja -C ../out/host_debug_unopt/
"C:\src\depot_tools\ninja.exe" -C ../out/host_debug_unopt/ -j 26
ninja: Entering directory `../out/host_debug_unopt/'
[5700/5700] STAMP obj/default.stamp
```
