### ISSUE TITLE
Duplicate DeviceDiscovery and Device classes in devicelab/framework/adb.dart and in flutter_tools

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#59190]
Currently devicelab tasks are using codes from `devicelab/framework/adb.dart` to get device info. The `DeviceDiscovery` and `Device` classes and their hesitance from `adb.dart` implements very similar methods and interfaces as in `flutter_tools/lib/src/device.dart`, with limited function and some TODOs. 
It's probably better to replace `adb.dart` with flutter_tools to have a more complete functionality for device control and to reduce the cost of maintenance.

**Comment by godofredoc** [comment]
obsolete.
