### ISSUE TITLE
Consider removing saveCompilationTrace

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#59205]
`dart:ui` exposes [saveCompilationTrace](https://api.flutter.dev/flutter/dart-ui/saveCompilationTrace.html), which, according to @jonahwilliams, is:

> completely unused (and unusable) by the framework so we should probably file a bug to remove it

Source: https://github.com/flutter/engine/pull/18933#discussion_r438408808

**Comment by pedromassangocode** [comment]
Still valid today!
