### ISSUE TITLE
Remove // ignore: unnecessary_null_comparison when null safety is on by default

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#59207]
https://github.com/flutter/engine/pull/18933 added temporary `// ignore: unnecessary_null_comparison` in places where we check non-nullable variables for null. These are there because temporarily Flutter will still run with null safety off by default, and so the `assert`s are the only way to validate non-nullness. When we flip that mode, however, we should clean up asserts along with `// ignore: unnecessary_null_comparison`.

/cc @jonahwilliams

**Comment by pedromassangocode** [comment]
What are the files where one can verify that this lint rule was not removed yet?

**Comment by TahaTesser** [comment]
cc: @goderbauer 
Could we remove this and clean up asserts in the framework? 

Thanks, @nilsreichardt  for pointing this out!

**Comment by goderbauer** [comment]
We can remove these once dart stops support non-null-safe mode, which should happen with Dart 3, see tracking issue here: https://github.com/dart-lang/sdk/issues/49530

**Comment by goderbauer** [comment]
This was fixed as part of https://github.com/flutter/flutter/issues/118837.
