### ISSUE TITLE
"You are using these overridden dependencies" when starting flutter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5921]
When you start flutter the first time you now get this warning:

```
Warning: You are using these overridden dependencies:
^[[35m! ^[[39m^[[1manalyzer^[[0m 0.29.0-alpha.0 from path ../../bin/cache/dart-sdk/lib/analyzer
```

This is a very confusing message for first-time users (or really anyone except those of us who are privy to the inner workings of the flutter tool) and so we shouldn't show that.

**Comment by abarth** [comment]
@pq @danrubel

**Comment by sethladd** [comment]
Good catch.

**Comment by pq** [comment]
Thanks.  Yeah, I noted that in the PR the other day (https://github.com/flutter/flutter/pull/5900) and have been playing with a clean way to suppress this.  Thanks for opening the issue and keeping me honest! (And sorry for not being more clear about this downside.)

**Comment by abarth** [comment]
This appears to be still happening.  Should we revert the change that added this message until we find a solution?

**Comment by pq** [comment]
Yeah.  We have a choice to make.  The way I see it, we can

1. back the change out and go back to the last published `analyzer` and with it back to the `1.20.0-dev.1.0` SDK (or deal with skew),
2. publish a new (`test` version constraint friendly) `analyzer` and update pubspecs accordingly,
3. embrace some level of `pub` error suppression, or
4. go back to calling out to a separate process for `flutter analyze` and live with analysis getting 2x+ slower

cc @bwilkerson on the feasibility of 2.
cc @danrubel for an update on longer term plans to decouple from the `analyzer` package.

**Comment by abarth** [comment]
It sounds like we should do (1) while we sort out the long term plan.

**Comment by bwilkerson** [comment]
I don't have a problem with publishing a new version of analyzer as long as it doesn't violate semver in any practical sense. But I do think we'd need to do some work to ensure that.

**Comment by pq** [comment]
> I don't have a problem with publishing a new version of analyzer as long as it doesn't violate semver in any practical sense. But I do think we'd need to do some work to ensure that.

@bwilkerson would you mind looking at this? `1.20.0-dev.1.0` was a loooong time ago.... ;)

**Comment by pq** [comment]
Whoops.  Scratch my request @bwilkerson.  I think we found away around needing another push (https://github.com/flutter/flutter/pull/5991).  Thanks all!

**Comment by abarth** [comment]
This issue appears to be fixed.
