### ISSUE TITLE
Adding tristate to CheckboxListTile

### ISSUE THREAD

**Issue by zenkog** [flutter/flutter#59225]
## Use case
Checkbox widget itself already has tristate condition but CheckboxListTile doesn't. 
Sometimes we use the checkboxes for building search filters / query within a data set. We need tristate where we can have: none, yes and no. 
I can easily do this with Checkbox, but CheckboxListTile makes it a whole lot prettier and building beautiful apps is what we wanna do right? 

## Proposal
Incorporating tristate into CheckboxListTile.

**Comment by VladyslavBondarenko** [comment]
Hi @zenkog 
It's already implemented in master channel. See https://github.com/flutter/flutter/pull/58154, 
https://master-api.flutter.dev/flutter/material/CheckboxListTile-class.html
