### ISSUE TITLE
[webview_flutter] Whether the webview can add the mixedContentMode property

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#59227]
[webview_flutter] Whether the webview can add the mixedContentMode property 😄

**Comment by TahaTesser** [comment]
hi @2534290808 
Looks like there is an there is open [pr](https://github.com/flutter/plugins/pull/2468)

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/43595
