### ISSUE TITLE
Set application ID for Linux apps

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#59234]
The current Linux shell doesn't set an [application ID](https://developer.gnome.org/gio/stable/GApplication.html#g-application-set-application-id). There should probably be an easy method to set this.

**Comment by stuartmorgan** [comment]
What is the ID used for?

**Comment by robert-ancell** [comment]
In short, the application ID uniquely identifies this application and is used for namespacing. In the case of the Linux shell, adding an application ID will cause the application to register on the session D-Bus, which can enable application uniqueness (attempting to launch a second time will just switch the first instance).

For more information see https://developer.gnome.org/ChooseApplicationID/.

**Comment by stuartmorgan** [comment]
Thanks, sounds like what we should probably do is have the template call `g_application_set_application_id` with a new template value that's the org + project name (see [Android](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L649) and [iOS](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L683) code; hopefully we can share one of them depending on the exact requirements on the string). That should be right in most cases, and people can change it if they want to.

**Comment by robert-ancell** [comment]
One case where we should be using the application ID is in the path_provider plugin. `getApplicationSupportDirectory()` returns `~/.local/share/${exe_name}/` which is *probably* safe to use, assuming that you've picked a name for your binary that is globally unique. It really should be `~/.local/share/${app_id}/` to be more safe. In current usage most projects use `~/.local/share/${project_name}/`, but I would say that's more historical than good practise.

**Comment by stuartmorgan** [comment]
Makes sense. We should do that ASAP since it's a breaking change at the installed-app level.

We can get the ID with FFI right? If not we'll need to rewrite the plugin...

**Comment by robert-ancell** [comment]
> Makes sense. We should do that ASAP since it's a breaking change at the installed-app level.
> 
> We can get the ID with FFI right? If not we'll need to rewrite the plugin...

We can get the ID with two function calls, [g_application_get_default()](https://developer.gnome.org/gio/stable/GApplication.html#g-application-get-default) and [g_application_get_application_id()](https://developer.gnome.org/gio/stable/GApplication.html#g-application-get-application-id), which should be accessible over FFI.

Is there a preference to use FFI or reimplement the plugin in C? It's probably a similar amount of work each way.

**Comment by robert-ancell** [comment]
I had a quick start on what it would be to update the path_provider plugin in C here:
https://github.com/robert-ancell/plugins/commit/749aaedb51582331ae8c9dea1beb3f64a8dc0067
