### ISSUE TITLE
Android Project add Flutter module throw MissingPluginException

### ISSUE THREAD

**Issue by liguobing** [flutter/flutter#59246]
I have a android project,then i add a flutter module to this project. android project's MainActivity like this:
```java
public class MainActivity extends FlutterActivity implements View.OnClickListener, MethodChannel.MethodCallHandler {

    private Button button;
    private MethodChannel channel;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        button = findViewById(R.id.button);
        button.setOnClickListener(this);

        GeneratedPluginRegistrant.registerWith(getFlutterEngine());
        channel = new MethodChannel(getFlutterEngine().getDartExecutor().getBinaryMessenger(),CHANNEL_NAME);
        channel.setMethodCallHandler(this);
    }

    @Override
    public void onClick(View v) {
        startActivity(
                FlutterActivity.withNewEngine().build(this)
        );
    }

    private static final String CHANNEL_NAME = "com.lixyz.androidwithflutter";

    @Override
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
        if ("startNativeActivity".equals(methodCall.method)) {
            Intent intent = new Intent(MainActivity.this, SecondActivity.class);
            startActivity(intent);
            result.success("");
        }
    }
}
```
In Flutter module,I have a button,press this button,start android project's SecondActivity. Flutter code like this:
```dart
class FlutterRoute extends StatefulWidget {
  FlutterRouteState createState() {
    return SecondRouteState();
  }
}

class FlutterRouteState extends State<FlutterRoute> {

  static const channel = MethodChannel("com.lixyz.androidwithflutter");

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(""),
      ),
      body: Container(
        color: Colors.lightGreenAccent,
        child: Center(
          child: Column(
            children: <Widget>[
              MaterialButton(
                color: Colors.redAccent,
                child: Text("to native Activity"),
                onPressed: () {
                  channel.invokeListMethod("startNativeActivity");
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
but,click Flutter'button,throw MissingPluginException,like this:
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startNativeActivity on channel com.lixyz.androidwithflutter)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
    #3      FlutterRouteState.build.<anonymous closure> (package:fluttermodule/FlutterRoute.dart:31:27)
     ......
My Flutter vierson : v1.17.0; what's happen,how i fix it? thank you!


```

**Comment by liguobing** [comment]
My Flutter vierson : Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.836], locale zh-CN)

**Comment by TahaTesser** [comment]
hi @liguobing 
testing your code sample, you have incorrect name, it should be package name/channel
 This
`private static final String CHANNEL_NAME = "com.lixyz.androidwithflutter";`
To
`private static final String CHANNEL_NAME = "com.lixyz.androidwithflutter/test";`

also same in flutter

thank you

**Comment by Aravindhan12** [comment]
Same issue for me. I'm trying to invoke a flutter method on click of  a button in native android  Second activity(new activity) and when the method is invoked I'm redirecting to a particular widget screen.Flutter method invoked successfully and redirected to a new screen but in the initstate() function of that screen I'm invoking a API call with internet connectivity check. When this line of code is executed I'm facing this error.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel plugins.flutter.io/connectivity)
E/flutter ( 7294): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 7294): <asynchronous suspension>
E/flutter ( 7294): #1      MethodChannelConnectivity.checkConnectivity (package:connectivity_platform_interface/src/method_channel_connectivity.dart:42:10)
E/flutter ( 7294): #2      Connectivity.checkConnectivity (package:connectivity/connectivity.dart:47:22)
E/flutter ( 7294): #3      isConnectivityAvailable (package:kalyan_matrimony/utils/app_utils.dart:872:50)
E/flutter ( 7294): #4      _BasePackageState._callMembershipDetailsApi (package:kalyan_matrimony/screens/payment/base_package.dart:55:16)
E/flutter ( 7294): #5      _BasePackageState.getMembershipDetailsFromAPI (package:kalyan_matrimony/screens/payment/base_package.dart:51:5)
E/flutter ( 7294): <asynchronous suspension>
E/flutter ( 7294): #6      _BasePackageState.initState (package:kalyan_matrimony/screens/payment/base_package.dart:39:5)
E/flutter ( 7294): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 7294): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 7294): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 7294): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 7294): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)

**Comment by TahaTesser** [comment]
@Aravindhan12 
Your error isn't related tot his issue, your is `connectivity` package 

@liguobing 
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
