### ISSUE TITLE
[web]: <Problem with GoogleSignIn>

### ISSUE THREAD

**Issue by bochigarcia** [flutter/flutter#59256]
Hello, I am experiencing a problem with Firebase and Google SignIn on the web:
- If I run my app from VSCode (http: // localhost: 61637) it cannot validate the domain in Firebase.
- If I run my app from the command line with "flutter run -d webserver --web-port=5000" then it works perfect, it logs in.
- If I generate the app with "flutter build web", I upload the app to a web server in a domain known  by Firebase, it doesn't work either.

The error in the two cases that does not work is always the same:

```
cb = gapi.loaded_0: 195 Uncaught PlatformException (google_sign_in, idpiframe_initialization_failed, Not a valid origin for the client: <localhost o dominio> has not been whitelisted for client ID <clientid>
```

Both localhost and the known domain are registered in the Firebase Authorized Domains of the app. I also comment that the registration and login by email works perfectly with Firebase.

Could it be that I'm missing configuring something? The strange thing is that in one case it works and in two it doesn't.

**Comment by bochigarcia** [comment]
Sorry I am using the following libraries:
  firebase_auth: ^ 0.15.4
  google_sign_in: ^ 4.0.4
The Flutter channel is beta

**Comment by VladyslavBondarenko** [comment]
Hi @bochigarcia 
does https://github.com/flutter/flutter/issues/33393#issuecomment-510395178 help? or do you mean authorised domains are already registered at https://console.developers.google.com/apis/credentials?

**Comment by bochigarcia** [comment]
Ah sorry, now it works. I understood that I had to add the domains in Authentication => Authorized domains.
So what use is that option?

**Comment by TahaTesser** [comment]
Hi @bochigarcia 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. You need to authorize non 8080 port for this. 
Thank you
