### ISSUE TITLE
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 22 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by w3farid** [flutter/flutter#59253]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
@w3farid make sure you pass url to the widget, closing since this is not an issue with flutter
