### ISSUE TITLE
Keyboard render issue on iOS

### ISSUE THREAD

**Issue by smallgirl** [flutter/flutter#59261]
all the flutter app i download from app has this problem ，such as 闲鱼 fun_flutter... i create a flutter page only use Text，it is has the same problem，while i create a native page ，it is not happened
![C175AB06-1C54-4C63-BFCF-1E56534D266A](https://user-images.githubusercontent.com/5234650/84393205-e3963800-ac2d-11ea-9773-2658f5820e60.gif)

**Comment by VladyslavBondarenko** [comment]
Hi @smallgirl 
could you provide your `flutter doctor -v`? with what device are you experiencing this?

**Comment by smallgirl** [comment]
happened on all the full screen iPhone，such as iPhone xs max，iPhonex ，iPhone 11...

**Comment by smallgirl** [comment]
@VladyslavBondarenko  it is same on 
https://github.com/flutter/flutter/issues/59165

**Comment by smallgirl** [comment]
@VladyslavBondarenko 
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G84, locale
zh-Hans-CN)
• Flutter version 1.17.0 at /Users/haitao/Library/Android/flutter
• Framework revision e6b34c2 (6 weeks ago), 2020-05-02 11:39:18 -0700
• Engine revision 540786dd51
• Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/haitao/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /Users/haitao/Library/Android/sdk
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)
! Some Android licenses not accepted. To resolve this, run: flutter doctor
--android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.2.1, Build version 11B500
• CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 46.0.1
• Dart plugin version 192.8052
• Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
• iPhone 11 Pro Max • E45BD60E-971E-43F3-9A4A-FBE06484AF67 • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:jianeryou/config/iconfont.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(),
      body: Container(
        child: Text(
          "We want to enable designers to deliver their full creative vision without being forced to water it down due to limitations of the underlying framework. Flutter's layered architecture gives you control over every pixel on the screen, and its powerful compositing capabilities let you overlay and animate graphics, video, text and controls without limitation. Flutter includes a full set of widgets that deliver pixel-perfect experiences on both iOS and Android.We want to enable designers to deliver their full creative vision without being forced to water it down due to limitations of the underlying framework. Flutter's layered architecture gives you control over every pixel on the screen, and its powerful compositing capabilities let you overlay and animate graphics, video, text and controls without limitation. Flutter includes a full set of widgets that deliver pixel-perfect experiences on both iOS and Android.We want to enable designers to deliver their full creative vision without being forced to water it down due to limitations of the underlying framework. Flutter's layered architecture gives you control over every pixel on the screen, and its powerful compositing capabilities let you overlay and animate graphics, video, text and controls without limitation. Flutter includes a full set of widgets that deliver pixel-perfect experiences on both iOS and Android.We want to enable designers to deliver their full creative vision without being forced to water it down due to limitations of the underlying framework. Flutter's layered architecture gives you control over every pixel on the screen, and its powerful compositing capabilities let you overlay and animate graphics, video, text and controls without limitation. Flutter includes a full set of widgets that deliver pixel-perfect experiences on both iOS and Android."
        ),
      ),
    );
  }
}

```
[
![DC86D109A2338A455116CAAAA6BF1A3E](https://user-images.githubusercontent.com/5234650/84454798-2d166f80-ac8e-11ea-91d5-c666de6c3b0a.gif)
](url)

**Comment by VladyslavBondarenko** [comment]
@smallgirl 
I see already open issue for the case, please follow up on https://github.com/flutter/flutter/issues/53565,
closing as duplicate
