### ISSUE TITLE
[cocoon] Bad state: No element /api/luci-status-handler

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#59270]
app engine has been hitting this error since last deployment.

2020-06-11 09:17:18.938 PDT
Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:150:5)
#1      Config.repoNameForBuilder (package:cocoon_service/src/datastore/cocoon_config.dart:392:38)
#2      LuciStatusHandler._setCompletedStatus (package:cocoon_service/src/request_handlers/luci_status.dart:213:46)
#3      LuciStatusHandler._rescheduleOrMarkCompleted (package:cocoon_service/src/request_handlers/luci_status.dart:122:11)
#4      LuciStatusHandler.post (package:cocoon_service/src/request_handlers/luci_status.dart:73:15)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#12     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:88:23)
<asynchronous suspension>
#13     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart)
#14     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)

**Comment by keyonghan** [comment]
\cc @godofredoc

**Comment by godofredoc** [comment]
We believe this is not affecting anybody and the failures are related to pubsub messages that are not cleaned up.

We are adding more logging to ensure our assumptions are correct.
