### ISSUE TITLE
[cocoon] github commits refresh api should consider the case of new release branch with multiple commits

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#59275]
When a new release branch is detected, `cocoon` chooses the latest commit and inserts it to datastore (https://github.com/flutter/cocoon/pull/734#discussion_r405195385). There is no problem if no following cherry pick commits between two consecutive github refresh API calls.

The cron job runs every minute, and cherry pick commits usually happen couple of days after first branched out. So the case where a new branch consists of cherry pick commits rarely happen. However, if the cocoon service is down for a long time (say couple of days for the worst case), that corner case does happen.

One possible solution:
When a new release branch is detected, we query top latest commits from new to old iteratively. For each commit, we check if it exists in `master` branch. If existing, that commit will be the one branched out from `master. All commits happen after that commit should be returned/inserted.

**Comment by godofredoc** [comment]
obsolete
