### ISSUE TITLE
_debugTypesAreRight should be more explicit.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5928]
`_debugTypesAreRight` should raise an exception that explains how the `State`'s type argument does not match with the `StatefulWidget` where it is used.

**Comment by eseidelGoogle** [comment]
Sounds like "no milestone necessary"?

**Comment by abarth** [comment]
Yes.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/6339 a while ago.
