### ISSUE TITLE
[web]: Child Widgets not updating state on parent Widget setState

### ISSUE THREAD

**Issue by digitalrbnz** [flutter/flutter#59299]
I have noticed that I have to leverage global keys to update state on chid widgets, which seems like it should happen via the parent setState function as long as the child widgets are instance of that build function.

I ended up having to manage this via stream listeners as Global keys became tedious pretty fast. Am I missing something or this is a bug?

Flutter 1.19.0-4.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision f994b76974 (2 days ago) • 2020-06-09 15:53:13 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)

**Comment by TahaTesser** [comment]
Hi @digitalrbnz 
Can you please provide and a minimal complete reproducible code sample.
Thank you

**Comment by digitalrbnz** [comment]
> Hi @digitalrbnz
> Can you please provide and a minimal complete reproducible code sample.
> Thank you

I have a positioned ListViewBuilder inside a Stack attempting to show a dynamic drop down across multiple tiles with different drop down values. This seems to work fine, except for the fact that the values don't seem to clear correctly when the list is updated with new values and refreshed on SetState.

ListView builder code

Positioned(
              top: 100,
              left: 100,
              width: 90,
              height: MediaQuery.of(context).size.height,
              child: ListView.builder(
                shrinkWrap: true,
                scrollDirection: Axis.vertical,
                itemCount: dropDownListValues.length,
                itemBuilder: (context, index) {
                  return Tile(
                    tileId: dropDownListValues[index],
                    isHeaderTile: false,
                    uuid: Uuid().v1(),
                  );
                },
              ),
            ),

Clear and update list based on which button is pressed.

  void _toggleDropDown(List valueList) {
    if (dropDownListValues.isEmpty) {
      setState(() {
        dropDownListValues = valueList;
      });
    } else {
      setState(() {
        dropDownListValues.clear();
      });
    }
  }
What I end up getting is the list extends based on the number of items in the drop down, but the values from the previous list carry across from the last list..

Example.

Drop Down list values

Dropdown list 1 = ['one', 'two']
Dropdown list 2 = ['two', 'three', 'four']
What I am seeing is

Dropdown list 1 = ['one', 'two']
Dropdown list 2 = ['one', 'two', 'four']
The if I click on list two drop down first I get the following

Dropdown list 1 = ['two', 'three']
Dropdown list 2 = ['two', 'three', 'four']

**Comment by TahaTesser** [comment]
Hi @digitalrbnz 
To better address the issue, please provide complete runnable code sample without missing code 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
