### ISSUE TITLE
Is it possible to make dart alternatively support space indent in case of the prolix brackets?

### ISSUE THREAD

**Issue by How-invin** [flutter/flutter#59297]
## Use case

Is it possible to make dart alternatively support space indent in case of the prolix brackets?

I think that an optional space indentation features in dart like python will help the flutter gain more readability and power. Like XML to Json.
Please forgive my poor English :) as a flutter and dart beginer.

**Comment by stuartmorgan** [comment]
Dart requests need to be made via https://github.com/dart-lang/language; Dart is a separate project from Flutter.
