### ISSUE TITLE
FractionalOffset doesn't make sense in alignment cases.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5930]
We should probably come up with a new class (`Alignment`?) that will be used in all cases where `FractionalOffset` is used to describe alignment, with all the statics (`topLeft`, `center`, etc.) transferred to the new type.

**Comment by dragostis** [comment]
This seems to be a rather huge change/break. `FractionalOffset` used as an alignment is very popular. There's also an inconsistency in some constructors whether the parameter should be named `align` or `alignment`.

@Hixie @abarth

**Comment by Hixie** [comment]
I guess what's really going on here is that we don't have a FractionalPoint.

I'm not entirely sold on the value of Point vs Offset so I'm probably not the best person to evaluate FractionalPoint vs FractionalOffset.

**Comment by abarth** [comment]
Ok, let's keep FractionalOffset as-is then.  I'm not sure the Point/Offset distinction has helped us avoid any actual bugs and probably isn't worth replicating here.
