### ISSUE TITLE
App launcher icon for Android not showing

### ISSUE THREAD

**Issue by Thirawat14** [flutter/flutter#59305]
### Description

The app launcher icon for iOS is working normally, however, the app launcher icon fails to display for Android. The application can still be accessed via Android Settings --> Apps, and registered as being installed.

I've checked the res folder and nothing seems to be out of the ordinary as the images were generated with Android Studio's Asset Studio.

<img width="332" alt="res-folder" src="https://user-images.githubusercontent.com/46079852/84466059-b3d54780-aca2-11ea-8555-0a232b5352d0.png">

![app-launcher-icon-missing](https://user-images.githubusercontent.com/46079852/84466069-b9329200-aca2-11ea-86eb-06ec5fae435b.gif)

### Version
> Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (4 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Comment by iapicca** [comment]
Hi @Thirawat14 
are referring to the `default` or `custom` launcher icons,
creating an launching a new project seems to work as intended;
could you please provide a 
a minimal complete reproducible code sample.
Thank you

**Comment by Thirawat14** [comment]
Hi @iapicca , I'm referring to `custom` launcher icon.

This is my pubspec.yaml
`name: chess_mobile
description: A new Flutter project.

version: 1.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  http:
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_svg:
  google_fonts:

  cupertino_icons: ^0.1.3
  pin_code_fields: ^3.0.1
  validators: ^2.0.0
  imei_plugin: ^1.1.6
  equatable: ^1.1.1
  pie_chart: ^3.1.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.1
  firebase_dynamic_links: ^0.5.1
  firebase_messaging: ^6.0.16
  provider: ^4.1.2
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.7+3
  corsac_jwt: ^0.2.2
  persistent_bottom_nav_bar: ^1.5.5
  shimmer: ^1.1.1
  pull_to_refresh: ^1.5.8

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

  bloc_test: ^5.1.0

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/fonts/

  fonts:
    - family: Chess
      fonts:
        - asset: lib/assets/fonts/chess.ttf
`

And this is some snippet from AndroidManifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tamada.chessMobile">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="chessMobile"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="false"
        android:fullBackupContent="false">`

Are there any specific files that you want me to refer to in relation to launcher icons?

**Comment by iapicca** [comment]
HI @Thirawat14 
i noticed in your yaml that you are using the 3rd party plugin [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons)
if these icons are generated with said plugin
please open an issue in the dedicated [github](https://github.com/fluttercommunity/flutter_launcher_icons/issues)

otherwise could you please provide a github repo with a minimal sample project
that does not use 3rd party plugins
Thank you

**Comment by Thirawat14** [comment]
Hi, @iapicca Thank you for pointing me out to the sub-forum for third party plugin. I'll close the issue in this forum. I'll look for answers in that forum since it seems like there are some other people facing similar issues. Thanks!

**Comment by patzu** [comment]
I also have this problem, could you solve this?

**Comment by MuhammadSufyanMalik** [comment]
Just Run Flutter Clean,
then Flutter Pub get,
after that you can launcher icon command, an error will be resolved.

**Comment by itxtoledo** [comment]
same issue here

**Comment by iapicca** [comment]
@itxtoledo 
this issue is more than 2 years old, 
if it's the same case I'd open an issue the dedicated [repo](https://github.com/flutter/flutter/issues/59305#issuecomment-643944472)

if you are encountering the issue without 3rd party plugins
I recommend to open a new issue with a minimal code sample and you flutter doctor
