### ISSUE TITLE
Target aot_assembly_release failed: Exception: Unsupported iOS arch name "i386"

### ISSUE THREAD

**Issue by huainanzi** [flutter/flutter#59315]
flutter 1.17.3
iPhone simulator 11 
I get this error.  iPhone simulator 11 is x86_64 arch.

**Comment by TahaTesser** [comment]
Hi @huainanzi 
Can you please provide your `flutter doctor -v` and what command are you using to run the app?  You can't run release mode on simulator 
Thank you

**Comment by huainanzi** [comment]
YES,I  can't run release mode on simulator.I  Now is OK

**Comment by TahaTesser** [comment]
Hi @huainanzi 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
