### ISSUE TITLE
[Feature Request] Add Warning Message when widget is Not Visible

### ISSUE THREAD

**Issue by katisari** [flutter/flutter#59311]
## Use case
Developers often run into problems with layout constrains, so, sometimes, not all widgets show up on the phone screen despite being in the code. Some of these problems do not cause errors, and developers can only detect the problem if what they thought vs what showed on screen is different. This can be harder to detect as an app becomes more complex.

## Proposal
It would be helpful to have a yellow text "Warning: [widgetName] is not shown on screen [widget's line number]" after running the app on the terminal and debugger above the lines where error messages are usually placed. This would make it clear to the user which widget they have to debug in order to fix the issue.

To replicate an example where a divider widget is not visible on the screen, reference: https://stackoverflow.com/questions/49088934/flutter-divider-widget-not-appearing

**Comment by goderbauer** [comment]
For most widgets we do show warnings if they overflow and the content doesn't fit on screen. Do you have a specific example where we are missing this warning?
