### ISSUE TITLE
[proposal] allow selection of which widget "resizeToAvoidBottomInset" 

### ISSUE THREAD

**Issue by Jan-pp** [flutter/flutter#59314]
I use `ScrollView`'s padding to show a toolbar while the content of the `ScrollView` can be seen blurred behind it. The padding makes sure the `ScrollView's` entire content can be seen above the toolbar.

However when I have a `TextField` and I focus it, the keyboard pops up and the `TextField` gets behind the blurred toolbar. Is it somehow possible to have it consider the padding as non-visible? I have the same problem with `Scrollable.ensureVisible()`.

Maybe there is a way to do this, but I can't find it. `SafeArea` doesn't work either, just clips it.

In the example below I put a blurred black box at the bottom, which is 150 high and I set the ScrollView's bottom padding to 150 as well. If the keyboard pops up I want the `TextField` to go above the black box.  As you can see it would also be nice if the `ScrollBar` respected the padding too:

![ezgif com-optimize-2](https://user-images.githubusercontent.com/56071132/84480198-78cc1780-ac94-11ea-853c-b967a4b2d7f1.gif)

```
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          Scrollbar(
            child: SingleChildScrollView(
              padding: EdgeInsets.only(bottom: 150),
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: [
                  Center(
                    child: Container(
                      height: 1000,
                    ),
                  ),
                  TextField(
                    textAlign: TextAlign.center,
                    decoration: InputDecoration(
                      hintText: "this is a text field",
                      fillColor: Colors.limeAccent,
                      filled: true,
                    ),
                  ),
                ],
              ),
            ),
          ),
          ClipRect(
            child: BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
              child: Container(
                height: 150,
                width: double.infinity,
                color: Colors.black45,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by iapicca** [comment]
Hi @Jan-pp 
I can see the use case of this,
I thought at this approach

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const Widget _home = MyHomePage();
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  static const double _fromBottom = 150;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Stack(
          children: <Widget>[
            Align(
              alignment: Alignment.topCenter,
              child: SingleChildScrollView(
                padding: const EdgeInsets.only(bottom: _fromBottom),
                child: Container(
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height * 2,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 80),
                    child: Center(
                      child: TextField(
                        decoration: const InputDecoration(
                          hintText: 'text field',
                          fillColor: Colors.limeAccent,
                          filled: true,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: ClipRect(
                child: Container(
                  height: _fromBottom,
                  width: MediaQuery.of(context).size.width,
                  color: Colors.black.withOpacity(.3),
                ),
              ),
            ),
          ],
        ),
        resizeToAvoidBottomInset: false,
      );
}
```

</details>

but prevent to resize both background and foreground
while it would be desirable to resize only the background
this [feature request](https://github.com/flutter/flutter/issues/57800) 
aims to have the opposite effect: 
avoid scaling the background while scaling the foreground

I believe an option to separate which widget scale and which doesn't 
would be desirable
Thank you

**Comment by Jan-pp** [comment]
Sorry I don't believe you understand what I am trying to explain. I do want both the black bar and the text field to move up with the keyboard. However I want the text field to move above the black bar, because it is blurred and will have buttons obstructing the view.

The black bar represents the padding of the scroll view. All I'm looking for is that when a text field is focussed it tries to stay clear of the padding area. It should treat it as invisible/obstructed.

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hey @Jan-pp thanks for filing this! :)

Have you considered using the `viewPadding` over the `padding`? When the keyboard presents itself, the `padding` is consumed by the `viewInsets`, and so it goes to zero, but I believe the `viewPadding` should maintain the value you were using in that case. 
`SafeArea` has an option to maintain the bottom `viewPadding` (`SafeArea.maintainBottomViewPadding`) in these cases when keyboards consume the `padding`. I was actually just recently considering we should do this by default the other day, as I ran into a similar issue https://github.com/flutter/flutter/issues/59204

The API docs have some in depth explanations and illustrations about `padding`, `viewPadding`, and `viewInsets` and how they are related. Let me know if this is helpful:

https://api.flutter.dev/flutter/widgets/SafeArea/maintainBottomViewPadding.html
https://api.flutter.dev/flutter/widgets/MediaQueryData-class.html

**Comment by Jan-pp** [comment]
Sorry the keyboard is not the problem but just an example that exposes the issue. I have a different example that doesn't involve the keyboard but `Scrollable.ensureVisible()` instead. When you push the button the lime widget should go above the black instead of below. The black bar is as big as the padding of the `ScrollView`, which should (optionally) be treated as invisible/obstructed/off-limits. Just imagine the black bar is a toolbar with buttons and stuff.

BTW the change of the topic title is not accurate in my opinion.

Result:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-13 at 10 29 02](https://user-images.githubusercontent.com/56071132/84564412-ba76c400-ad61-11ea-93e8-a9d0819addc5.png)

Desired:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-13 at 10 30 50](https://user-images.githubusercontent.com/56071132/84564415-bc408780-ad61-11ea-9c88-1c5ddb5b57b2.png)

```
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _limeKey = GlobalKey();
  final ScrollController _scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      body: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          Scrollbar(
            child: SingleChildScrollView(
              controller: _scrollController,
              padding: EdgeInsets.only(bottom: 200),
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Center(
                    child: Container(
                      height: 1500,
                    ),
                  ),
                  Material(
                    child: TextField(
                      key: _limeKey,
                      textAlign: TextAlign.center,
                      decoration: InputDecoration(
                        hintText: "some widget",
                        fillColor: Colors.limeAccent,
                        filled: true,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
          ClipRect(
            child: BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
              child: Container(
                height: 200,
                width: double.infinity,
                color: Colors.black45,
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _scrollController.jumpTo(0);
          Scrollable.ensureVisible(
            _limeKey.currentContext,
            alignmentPolicy: ScrollPositionAlignmentPolicy.keepVisibleAtEnd,
          );
        },
      ),
    );
  }
}

```

**Comment by Piinks** [comment]
This is a dupe, author confirmed: https://github.com/flutter/flutter/issues/60117#issuecomment-649431067
