### ISSUE TITLE
Why Android Alarm Manager not functioning properly in Flutter on Real device?

### ISSUE THREAD

**Issue by Chethansmash7** [flutter/flutter#59326]
My Android alarm manager,when it calls the callback function ,performs a important operation.

I have published an app on Play Store and I feel so horrible that this Android Alarm Manager actually not functioning properly on the real devices.I tried it on my Mom's and friends phone

When I ran the app on my device in the debug mode I tested it and it was really working fine.Like I tested it for 2 hours 2 times.Like I understand that 15 minutes or more is the optimum time required for the callback function to be triggered,it is only then this android alarm manager functions properly.I did make sure that the callback function is triggered no less than 15 minutes but still while running in the debug mode on my device(or u can say the emulator),there would be a difference of 10-20 seconds for the a callback function to be triggered but still on real devices it is not working properly.It is not calling the call back function only..

Anyone help me please...This is relly disappointing and pissing me off.

**Comment by iapicca** [comment]
Hi @Chethansmash7 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`
and a minimal complete reproducible code sample.
Thank you

**Comment by Chethansmash7** [comment]
> Hi @Chethansmash7
> Can you please provide your `flutter doctor -v`,
> your `flutter run --verbose`
> and a minimal complete reproducible code sample.
> Thank you

**Sure.........for flutter doctor -v**

E:\flutter_Apps\flutter_app__v2>flutter doctor -v
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is
currently executing will be used instead.
  running Flutter tool: C:\src\flutter
  previous reference  : C:\flutter\flutter\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see
which flutter is on your path).

[√] Flutter (Channel unknown, v1.12.13+hotfix.8, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\w8\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\w8\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.



<<<<<<<-------------------------------->>>>>>>>>>>>

For **flutter run --verbose**




E:\flutter_Apps\flutter_app_v2>flutter run --verbose
[  +50 ms] Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter'
tool is
           currently executing will be used instead.
             running Flutter tool: C:\src\flutter
             previous reference  : C:\flutter\flutter\flutter
           This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter
           --version' to see
           which flutter is on your path).

[  +22 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +37 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +10 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +25 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[ +155 ms] executing: C:\Users\w8\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +22 ms] Exit code 0 from: C:\Users\w8\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +16 ms] No supported devices connected.
[  +24 ms] "flutter run" took 241ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



E:\flutter_Apps\flutter_app_v2>

<<<<<<<<<<<<<<------------------------------->>>>>>>>>>

Code-

void callback()  {
  print("I am in the isolate");
  DateTime now = DateTime.now().toLocal();
  print("Date time:");
  print(now);
  Fluttertoast.showToast(
      msg:
          "*****************notification message**********************",
      toastLength: Toast.LENGTH_LONG,
      gravity: ToastGravity.BOTTOM,
      backgroundColor: Colors.black,
      textColor: Colors.red,
      fontSize: 16.0);


  print("last line of Isolate");
}

void alarm_managing_function(int t) async {
  await AndroidAlarmManager.initialize();
  await AndroidAlarmManager.periodic(Duration(seconds: t), 0, callback);
}


RaisedButton(
          onPressed: () {
            DatePicker.showPicker(context,
                showTitleActions: true,
                pickerModel:
                    CustomPicker(currentTime: DateTime.tryParse(_selectedTime)),
                onConfirm: (time) {
              setState(() {
                print(time);
                _selectedTime = DateFormat("mm-ss").format(time);
                FileUtils().saveToFile(_selectedTime);

                mm = _selectedTime.substring(0, 2);
                ss = _selectedTime.substring(3, 5);
                print(mm);
                print(ss);
                mmValue = int.parse(mm);
                ssValue = int.parse(ss);
                totalTimeInSec = mmValue * 60 + ssValue;
                print(totalTimeInSec);

                DateTime now = DateTime.now().toLocal();
                print("Start-->Date time:");
                print(now);
                 alarm_managing_function(totalTimeInSec);
              });
            }, locale: LocaleType.en);



<<--------------->>>>>>
**Explanation**

The alarm_managing_function function is called and with totalTimeInSec indicating the time at set by the user.The alarm managing function calls the callback() function which displayes the notification in the form of a toast

**Comment by Chethansmash7** [comment]
Guys any can help me?I need to fix this issue asap

**Comment by iapicca** [comment]
Hi @Chethansmash7 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, 
your `flutter run --verbose` (making sure that is actually running on a device)
and a minimal **reproducible** code sample.
Thank you

**Comment by Chethansmash7** [comment]
> flutter upgrade --force

Sure,please give me some time I will test it on 2 actual devices and let u know soon enough.Thanks for the response.....

**Comment by Chethansmash7** [comment]
> Hi @Chethansmash7
> Could you please run `flutter upgrade --force`.
> If the issue persists, please provide your updated `flutter doctor -v`,
> your `flutter run --verbose` (making sure that is actually running on a device)
> and a minimal **reproducible** code sample
> that doesn't involve 3rd party plugins
> Thank you

I have tested to on Samsung and Xiaomi phones.On Samsung phone it is working fine but on Xiaomi phones it is not working properly.Any idea as to why?

**Comment by iapicca** [comment]
Hi @Chethansmash7 
could you please provide the information listed [above](https://github.com/flutter/flutter/issues/59326#issuecomment-643946749)
thank you

**Comment by Chethansmash7** [comment]
> Hi @Chethansmash7
> could you please provide the information listed [above](https://github.com/flutter/flutter/issues/59326#issuecomment-643946749)
> thank you

Sure @iapicca 

Here it is:

E:\flutter_Apps\flutter_app_v2>flutter doctor -v
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is
currently executing will be used instead.
  running Flutter tool: C:\src\flutter
  previous reference  : C:\flutter\flutter\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see
which flutter is on your path).

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\w8\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\w8\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category


**And flutter run --verbose**


E:\flutter_Apps\flutter_app_v2>flutter run --verbose
[  +40 ms] Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter'
tool is
           currently executing will be used instead.
             running Flutter tool: C:\src\flutter
             previous reference  : C:\flutter\flutter\flutter
           This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter
           --version' to see
           which flutter is on your path).

[  +20 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b041144f833e05cf463b8887fa12efdec9493488
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +298 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.3
[  +19 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +130 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +52 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] executing: C:\Users\w8\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +56 ms] List of devices attached
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +101 ms] No supported devices connected.
[  +36 ms] "flutter run" took 346ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by iapicca** [comment]
Hi @Chethansmash7 
the error you are reporting might depend from your implementation rather than flutter itself
for the issue to be workable will be needed minimal complete reproducible code sample.
Also in the log you provided the app didn't run due to lack of connected device;
could you please provide a verbose representative of the situation
Thank you

**Comment by Chethansmash7** [comment]
> Hi @Chethansmash7
> the error you are reporting might depend from your implementation rather than flutter itself
> for the issue to be workable will be needed minimal complete reproducible code sample.
> Also in the log you provided the app didn't run due to lack of connected device;
> could you please provide a verbose representative of the situation
> Thank you

@iapicca 

With regards to the minimal complete reproducible code sample I have already furnished earlier.Please have a look at it.

Well the lack of connected device I feel has nothing to do with the log,because if connected it would just show the name of my mobile.Please correct me if I am wrong

**Comment by iapicca** [comment]
Hi @Chethansmash7 
for the issue to be workable it needs to be reproducible,
since the error occurs at runtime it will need a "runnable" minimal reproducible code sample,
(not production code or a snippet of a single function)
please provide the info required to investigate the issue,

without a device attached the app won't build, please provide valid logs.

Thank you

**Comment by Chethansmash7** [comment]
Well the problem with real device was that in the settings of the device.Under battery saver,the background process was in a restricted mode (which comes as default and recommended in most of the devices).When I ran the app after changing the settings in which the background process of an app would run without any restriction,it is working fine.

Thank u for all the help you gave me till now.

**Comment by iapicca** [comment]
I'm glad you fixed the issue
Thank you for letting me know

**Comment by Chethansmash7** [comment]
> I'm glad you fixed the issue
> Thank you for letting me know

Welcome
