### ISSUE TITLE
microbenchmarks stock_build_iteration and stock_layout regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59335]
🔍
![Screen Shot 2020-06-12 at 8 47 39 AM](https://user-images.githubusercontent.com/1435716/84521095-64365200-ac89-11ea-9768-f40be89ee03e.png)

Looks like this engine roll: https://github.com/flutter/flutter/pull/59222

**Comment by kf6gpe** [comment]
Looks like web_benchmarks_html text_canvas_cached_layout.html.layout.average is affected too.

**Comment by iskakaushik** [comment]
See notes at: https://github.com/flutter/engine/pull/18901#issue-431388702. I'm going to rebaseline the microbenchmarls. @kf6gpe could you please file a separate issue for the web benchmarks. I'm not sure what is going on there.

**Comment by iskakaushik** [comment]
I've rebaselined the microbenchmarks.
