### ISSUE TITLE
 launchd uses high disk volume > 10 GB in 5 minutes when debugging App on physical iOS device

### ISSUE THREAD

**Issue by DebugTheCode** [flutter/flutter#59331]
I'm using Android Studio.

Build: AI-193.6911.18.40.6453388, 202005012038,

AI-193.6911.18.40.6453388, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.5, screens 1680x1050, 3008x1692; Retina

When I launch my Flutter app on my iPhone 11 device, the program launchd of Mac OSX itself starts using a lot of Disk space. I've tested it with a physical Samsung S9 device: nothing wrong. Also tested in on a iOS SE 2nd gen Simulator, also nothing wrong.

## Version info

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F101, locale nl-NL)
    • Flutter version 1.17.1 at /Users/leviroelofsma/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/leviroelofsma/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/leviroelofsma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    • Device 213b8734c00b7ece is not authorized.
      You might need to check your device for an authorization dialog.
    • Error: Hobbykamer is not connected. Xcode will continue when Hobbykamer is connected. (code -13)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @devoncarew 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by devoncarew** [comment]
cc @DebugTheCode re: the above request

**Comment by DebugTheCode** [comment]
I'm sorry but I can't give a minimal complete reproducible code sample, the project is already too big for that.

pubspec.yaml:

```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  dbcrypt: ^1.0.0
  strings: ^0.1.2
  path: ^1.6.4
  uuid: ^2.0.4
  visibility_detector: ^0.1.5

  # Payments
  # stripe_sdk: ^2.8.1

  # Firebase
  firebase_messaging: ^6.0.13

  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.1.0
  # Value equality
  equatable: ^1.0.2
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  dio: ^3.0.9
  # Local cache
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6

  # Pickers and players
  file_picker: ^1.9.0
  photo: ^0.4.8
  image_picker: ^0.6.2
  flutter_image_compress: ^0.6.5+1
  video_player: ^0.10.11+1
  flutter_colorpicker: ^0.3.2
  mime: ^0.9.6+3
  flutter_ffmpeg: ^0.2.10
  presentation: ^0.0.10+1

  # Audio
  audioplayer: ^0.8.1

  # Fonts
  google_fonts: ^1.0.0

  # Sharing
  # esys_flutter_share: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/locale/i18n/en.json
    - lib/core/locale/i18n/nl.json
    - assets/images/links_placeholder.jpeg
    - assets/images/logo/logo_whitebg_nopadd.png
    - assets/images/logo/logo_transbg_padd.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf
          style: normal
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

[The response of `flutter run --verbose` was too big to copy all of it out of my terminal_.txt](https://github.com/flutter/flutter/files/4785773/The.response.of.flutter.run.--verbose.was.too.big.to.copy.all.of.it.out.of.my.terminal_.txt)

**Comment by TahaTesser** [comment]
Hi @DebugTheCode 
Please upgrade to latest `stable` channel and try again with try with a new project if the problem please provide your `flutter run --verbose`
Thank you

**Comment by kuhnroyal** [comment]
Could be related to https://github.com/flutter/flutter/issues/56826?

**Comment by DebugTheCode** [comment]
@kuhnroyal Yes, indeed. Thanks for linking the issue. Upgraded Flutter to 1.17.4 and it seem to be fixed.
