### ISSUE TITLE
Flutter not working after switching to Flutter channel master

### ISSUE THREAD

**Issue by chankalun** [flutter/flutter#59330]
## Steps to Reproduce

1. ... I was using Flutter v1.19 in the beta channel before, as I tried to use to Layout Explorer in the Flutter DevTools. It required me to switch to Flutter channel master.
2. ... I gave a command to switch to flutter channel master, and the installation went fine, I even checked if my devices were connected, and they were!
3. ... When I try to run my App, nothing happened.

## Logs

```
"flutter devices"
bash: flutter: command not found
"flutter --version"
bash: flutter: command not found
```

```
```

**Comment by iapicca** [comment]
Hi @chankalun 
Can you please run from your terminal
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by chankalun** [comment]
Hi, I have sorted this with setting my path in zsh :)
