### ISSUE TITLE
Pageview with listview inside Stack - one of them isn't working (scrolling) ?

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#59336]
This is my hierarchy:
```
- Stack
  - Pageview
  - Listview
    - TextFormField
```

However, in this case the `Pageview` isn't scrollable.
In my case each page in the `Pageview` host a full-sized image, so I can't put it after the `Listview` either.

The reason I need a `Listview` for the `TextFormField` is because it's positioned near the bottom edge of the page, so when focusing on the text field the keyboard opens, which makes the entire content a lot smaller (and I need a `Listview` so the user can scroll and see the content)

Is there any way to solve this? to allow both the `Pageview` and `Listview` to be `Scrollable` inside the `Stack` ?

**Comment by superciccio** [comment]
have you tried to put stack inside SingleChildScrollView ? without the listview ?

**Comment by matanshukry** [comment]
Tried it now, still failing:

```
I/flutter (30212): The following assertion was thrown during performResize():
I/flutter (30212): Horizontal viewport was given unbounded height.
I/flutter (30212): Viewports expand in the cross axis to fill their container and constrain their children to match
I/flutter (30212): their extent in the cross axis. In this case, a horizontal viewport was given an unlimited amount of
I/flutter (30212): vertical space in which to expand.
I/flutter (30212): 
I/flutter (30212): The relevant error-causing widget was:
I/flutter (30212):   PageView
```

**Comment by superciccio** [comment]
Try with expanded wrapping pageview or container with height: from mediaquery 

The solution is right you just have to fix this little one ;)

**Comment by matanshukry** [comment]
Wrapping the pageview with expanded:
```
I/flutter (30212): The following assertion was thrown while applying parent data.:
I/flutter (30212): Incorrect use of ParentDataWidget.
I/flutter (30212): The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
I/flutter (30212): RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.
I/flutter (30212): Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
I/flutter (30212): Expanded widgets are placed directly inside Flex widgets.
I/flutter (30212): The offending Expanded is currently placed inside a Stack widget.
I/flutter (30212): The ownership chain for the RenderObject that received the incompatible parent data was:
I/flutter (30212):   RepaintBoundary ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ←
I/flutter (30212): Scrollable ← NotificationListener<ScrollNotification> ← PageView ←
I/flutter (30212): NotificationListener<ScrollNotification> ← Expanded ← Stack ← _SingleChildViewport ← ⋯
```


And I thought using `MediaQuery` isn't recommended / a bad design?

**Comment by matanshukry** [comment]
I tried to use MediaQuery anyway, but it seems the size is somehow "too big" ?
I also tried to reduce the appbar height using:
`height: MediaQuery.of(context).size.height - appBarHeight`, but it's still a bit much (around 25 too much I'd say).

Am I missing anything else?

**Comment by superciccio** [comment]
```
return Scaffold(
        appBar: AppBar(
          title: Text('data'),
        ),
        body: SingleChildScrollView(
          child: ConstrainedBox(
            constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height),
            child: Stack(
                children: <Widget>[
                  PageView(children: [
                    Icon(Icons.ac_unit),
                     Icon(Icons.reply_all)
                  ],),
                  TextField()
                ],
             ),
           )
 ))
```


that should do

**Comment by matanshukry** [comment]
@superciccio Yeah the scroll part works, but like I said in my last comment it's too tall.
That is, instead of `TextField` like in your example I've pust a container with a blue color. And I can scroll past it.

It seems the `MediaQuery.of(context).size.height - appBar.preferredSize.height` include 24 extra pixels from somewhere ?

**Comment by superciccio** [comment]
can you create a gist in github so I can see your code, please

**Comment by matanshukry** [comment]
@superciccio so for the past 30m I've been trying to create a minimal replicable code, and I ended up finding the problem, although it might be a bug?

I've googled a bit before and many people says to also use `MediaQuery.of(context).padding`, specifically `.padding.top`, which should include status bar height (although I don't see any status bar in the emulator).

However, I tried that, but it didn't work. It seems `.padding` will return zero for all widgets except the "root", the one that creates the Scaffold.

Is there any logic behind this? or is this a bug?

**Comment by superciccio** [comment]
mmm do you have an app bar ?

if not I don't know, without seeing code.

**Comment by matanshukry** [comment]
Yeah I do.
And here is a sample code:

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyRoot(),
    );
  }
}

class MyRoot extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appBar = AppBar(title: const Text('My Title'));
    final mediaQuery = MediaQuery.of(context);
    return Scaffold(appBar: appBar, body: Column(children: [
        Text('Root: ${mediaQuery.padding.toString()}'),
        MyWidget(),
      ]));
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({Key key, this.appBarHeight}) : super(key: key);
  
  final double appBarHeight;
  
  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    return Text('Inside: ${mediaQuery.padding.toString()}');
  }
}

```

**Comment by superciccio** [comment]
so I read the docs and tried different things basically the padding you get which is 24 top is the status bar size in Android, ios might be different...

**Comment by matanshukry** [comment]
well I'm closing this issue since using it on the root is working, but if it is an intended behavior it should at least be documented; it was definitely a source for frustration for me.

And thanks for the help!
