### ISSUE TITLE
Add ability to use ElevationOverlay.applyOverlay() to add an elevation without adding a color

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#59359]
## Use case
There are scenarios where you need to have a ElevationOverlay in dark mode even though you don't have a shadow:

For example placing a AppBar above a TabBar. You need the Appbar to be brighter than black just like the TabBar, but you don't wan't the AppBar to draw a shadow on top of the TabBar.

## Proposal
Export ElevationOverlay.applyOverlay() from flutter/material so that we can use it in our projects.

**Comment by HansMuller** [comment]
CC @darrenaustin
