### ISSUE TITLE
Could not determine the dependencies of task ':app_settings:compileDebugAidl'. > Failed to find Platform SDK with path: platforms;android-R

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#59355]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
I just ran `flutter run` for android

**Expected results:** 

Application being debugged!

**Actual results:** 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

<details>
  <summary>Logs</summary>

```
```

```
yazee@Yazeed-AlKhalaf MINGW64 /y/code/my_projects/flutter_projects/split_it (master)
$ flutter analyze
Analyzing split_it...
No issues found! (ran in 30.4s)
```

```
yazee@Yazeed-AlKhalaf MINGW64 /y/code/my_projects/flutter_projects/split_it (master)
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.3 at Y:\extra\flutter
    • Framework revision b041144f83 (8 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at C:\Users\yazee\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.46.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by YazeedAlKhalaf** [comment]
PLEASE I NEED HELP, MY APP WAS WORKING AND IT IS IN THE PLAY STORE. HOW COME IT NOT DOESN'T?

**Comment by YazeedAlKhalaf** [comment]
@timsneath

**Comment by timsneath** [comment]
Looks like `Failed to find Platform SDK with path: platforms;android-R` might be the culprit :)

Do you have this installed? This is the SDK for Android 11 Beta 1...

**Comment by YazeedAlKhalaf** [comment]
I have discovered this now, thanks for your notice. The problem is that I am using android-R instead of 30 in `compileSdkVersion`. Since the Android Beta is released to the public now they changed naming and some packages still did not do the change, which broke my app. I had to change it manually with this code, hope it helps someone:
put this code in `android/build.gradle` at the end 😊🚀

```gradle
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    project.evaluationDependsOn(':app')

    afterEvaluate {project ->
        if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 30
            }
        }
    }
}
```

**Comment by mirackilic** [comment]
It didn't work for me

**Comment by mirackilic** [comment]
> I have discovered this now, thanks for your notice. The problem is that I am using android-R instead of 30 in `compileSdkVersion`. Since the Android Beta is released to the public now they changed naming and some packages still did not do the change, which broke my app. I had to change it manually with this code, hope it helps someone:
> put this code in `android/build.gradle` at the end 😊🚀
> 
> ```groovy-gradle
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> 
>     project.evaluationDependsOn(':app')
> 
>     afterEvaluate {project ->
>         if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
>             android {
>                 compileSdkVersion 30
>             }
>         }
>     }
> }
> ```

this didn't work for me

**Comment by trunghieuvn** [comment]
> I have discovered this now, thanks for your notice. The problem is that I am using android-R instead of 30 in `compileSdkVersion`. Since the Android Beta is released to the public now they changed naming and some packages still did not do the change, which broke my app. I had to change it manually with this code, hope it helps someone:
> put this code in `android/build.gradle` at the end 😊🚀
> 
> ```groovy-gradle
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> 
>     project.evaluationDependsOn(':app')
> 
>     afterEvaluate {project ->
>         if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
>             android {
>                 compileSdkVersion 30
>             }
>         }
>     }
> }
> ```

work for me, thank so much, 
guys can try

**Comment by jeffrysaputra97** [comment]
> > I have discovered this now, thanks for your notice. The problem is that I am using android-R instead of 30 in `compileSdkVersion`. Since the Android Beta is released to the public now they changed naming and some packages still did not do the change, which broke my app. I had to change it manually with this code, hope it helps someone:
> > put this code in `android/build.gradle` at the end 😊🚀
> > ```
> > subprojects {
> >     project.buildDir = "${rootProject.buildDir}/${project.name}"
> > 
> >     project.evaluationDependsOn(':app')
> > 
> >     afterEvaluate {project ->
> >         if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
> >             android {
> >                 compileSdkVersion 30
> >             }
> >         }
> >     }
> > }
> > ```
> 
> this didn't work for me

make sure to put that code in the project level build.gradle file (the ones in the android directory), not the app level build.gradle file (the ones in the app directory) because it solves my problem 
![image](https://user-images.githubusercontent.com/29313386/85267254-38904480-b49f-11ea-8a5f-21704200e0be.png)

**Comment by SSK9931** [comment]
Thank you very much its worked for me

**Comment by Ahmed-ALshmre** [comment]
it is not works
