### ISSUE TITLE
Build error during `felt_windows.bat build` with clean tree

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#59367]
Tree is clean.  I suspect the dart.exe may be in use when ninja is trying to overwrite it?

I've built using `ninja -C out/host_debug_unopt` just before this.  This is with flutter/engine@48d7091649fe975122ce30478f2fc71def298cd5.

```
C:\src\engine\src [master ↓18043 ↑348]> .\flutter\lib\web_ui\dev\felt_windows.bat build -w
"Running \`pub get\` in 'engine/src/flutter/web_sdk/web_engine_tester'"
Resolving dependencies...
Got dependencies!
"Running \`pub get\` in 'engine/src/flutter/lib/web_ui'"
Resolving dependencies...
Got dependencies!
Running gn...
Generating GN files in: out\host_debug_unopt
Generating Visual Studio projects took 290ms
Done. Made 686 targets from 237 files in 5544ms
Running ninja (with default ninja parallelization)...
ninja: Entering directory `C:\src\engine\src\out\host_debug_unopt'
[1/1] Regenerating ninja files
[48/172] COPY dart.exe dart-sdk/bin/dart.exe
FAILED: dart-sdk/bin/dart.exe
C:/Users/Study/Documents/chromium/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe gyp-win-tool recursive-mirror dart.exe dart-sdk/bin/dart.exe
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 105, in ExecRecursiveMirror
    os.unlink(dest)
WindowsError: [Error 5] Access is denied: 'dart-sdk/bin/dart.exe'
[52/167] LINK ./testing_unittests.exe                                  
```

**Comment by eseidel** [comment]
I dug a little bit into this the other day, but hadn't yet found the failing command.  If you have theories @stuartmorgan or @nturgut I'd certainly welcome them. :)  I'll keep debugging as I'm still not able to get a working web_ui hacking setup on windows and this seems like the next-most obvious error to tackle. :)

**Comment by eseidel** [comment]
Here is the log from my most recent felt_windows.bat build -w run in case it's useful: https://gist.github.com/eseidel/5827ed7110c10f2ad0181d396079f93e

**Comment by eseidel** [comment]
Oddly enough I think my manual ninja builds were running clean earlier today.  I think this indicates that the dart in question is in use (not yet sure by what).

**Comment by nturgut** [comment]
I will have a look into this, thanks for filing the issue @eseidel 

LUCI Tests are using this file to build Flutter for Web on Windows. (note: unit tests are not running now) Since latest PR is passing: https://ci.chromium.org/p/flutter/builders/try/Windows%20Web%20Engine/5492

I guess this is a local only issue.

**Comment by eseidel** [comment]
I believe the problem is that felt_windows.bat uses the dart.exe in host_debug_unopt to execute and then also as part of the build command tries to replace it.  My understanding is that on windows you can't overwrite a file while it's open for execution.  You can do some sort of dance whereby you move/rename the file and then write a new one.  But I think the real fix here is probably to have felt use a different version of the Dart SDK.

My understanding was the engine had some sort of bootstrapping SDK it used in scenarios like this?  @chinmaygarde would know.

**Comment by yjbanov** [comment]
We invoke ninja from the `.bat` file itself, so there shouldn't be any dart processes running. However, `dart.exe` may be used by something else.

**Comment by nturgut** [comment]
@eseidel sorry I only had time to look at this one today.

I wasn't able to produce the issue though the `dev\felt_windows.bat build --watch` worked for me with no warnings/errors. I run the command line with admin permission when building the engine. Can you please have another look when you have time?

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
