### ISSUE TITLE
[devicelab] Map all the devicelab devices to their corresponding PDU port

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#59373]
PDU IPs (Device lab uses 2 PDUs):

192.168.1.117
192.168.1.141

First we need to detect the bridge port to ensure we don't lose access to the internal ips pool.

* On a terminal ping the bridge ip
* On a second terminal connect to the PDUs and power cycle the ports
* Once it gets disconnected we found the correct port and PDU

After we identified the bridge port we can just power-off the ports and check which test beds get disconnected.

**Comment by digiter** [comment]
I will request emergency access then.

**Comment by godofredoc** [comment]
Any reason why not doing it remotely?

**Comment by digiter** [comment]
Oh, I see. I thought it must be done locally.

**Comment by digiter** [comment]
From Godofredo: port 17 is the one for the ssh bridge, but we don't know which PDU it belongs to, either 192.168.1.117 or 192.168.1.141.

**Comment by digiter** [comment]
For PDU 192.168.1.117:
- Port 1 connects to the KVM and network switch.
- Port 17 connects to the ssh bridge.

**Comment by digiter** [comment]
http://go/flutter-devicelab-hardware has been updated with the mapping.
