### ISSUE TITLE
ChromeDriverInstaller.install should return Future<void>

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#59376]
With non-nullability the analyzer is stricter about awaiting on `void`. `integration_tests_manager.dart` in the engine currently awaits ChromeDriverInstaller.install, which returns void. Instead, ChromeDriverInstaller.install should return Future<void> so we can await on it.

/cc @nturgut

**Comment by nturgut** [comment]
Thanks I'll let you know when I merge a fix to the web_installers.
