### ISSUE TITLE
flutter google maps is not working 

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#59389]
A problem occurred configuring project ':google_maps_flutter'.
> Could not resolve all artifacts for configuration ':google_maps_flutter:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.3.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar'.
         > Read timed out
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':google_maps_flutter' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by TahaTesser** [comment]
Hi @SAMYAK99 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample with `google_maps_flutter` version
Thank you

**Comment by VladyslavBondarenko** [comment]
@SAMYAK99 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template
