### ISSUE TITLE
timeline compilation failed below macOS 10.14

### ISSUE THREAD

**Issue by pangzhen** [flutter/flutter#59383]
signpost.h exists in macOS 10.14 or above, so compilation failed below macOS 10.14
[ https://dart-review.googlesource.com/c/sdk/+/151101 ](url)
[vm, timeline] Fix compilation failed below macOS 10.14 [NEW]

**Comment by pangzhen** [comment]
the latest version of gclient enables python3 , may be meets error:

Installing collected packages: setuptools, pip, wheel
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/zhen/.vpython-root/890490/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/zhen/.vpython-root/890490/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

add `export GCLIENT_PY3=0` in env var to fix error

**Comment by TahaTesser** [comment]
Hi @pangzhen 
Can you please provide your `flutter doctor -v"?
Thank you

**Comment by pangzhen** [comment]
https://dart-review.googlesource.com/c/sdk/+/152780
