### ISSUE TITLE
WebView to show "desktop view"

### ISSUE THREAD

**Issue by wiradikusuma** [flutter/flutter#59394]
## Use case

I want to display websites in "desktop view" in my _mobile_ app. Specifically, there's a hero widget showing websites in landscape/desktop mode.

https://pub.dev/packages/webview_flutter works, but "responsive design" websites automatically show mobile version, regardless of User Agent. I want to override this behavior.

## Proposal

A boolean property e.g. `desktopView`. When set to `true`, webview will open websites in desktop mode, something like https://stackoverflow.com/questions/14688030/setting-webview-to-view-desktop-site-and-not-mobile-site

**Comment by softmarshmallow** [comment]
Have you checked via [chrome debugger](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) and checked the actual user agent info that being received?

**Comment by wiradikusuma** [comment]
> Have you checked via [chrome debugger](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) and checked the actual user agent info that being received?

I will do that and update here. But does it even matter? Many websites don't even check user agent, they use Bootstrap to make it responsive. Bootstrap doesn't check user agent, it checks screen dimension.

**Comment by softmarshmallow** [comment]
> > Have you checked via [chrome debugger](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) and checked the actual user agent info that being received?
> 
> I will do that and update here. But does it even matter? Many websites don't even check user agent, they use Bootstrap to make it responsive. Bootstrap doesn't check user agent, it checks screen dimension.

well it worth checking. if nor UA or header does the magic, than theirs no other way for flutter or other mobile platforms for this isssue,
take a look at [Frame options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options). you may be able to fake screen size

**Comment by shibam123** [comment]
i also want the same solution any one please

**Comment by xOldeVx** [comment]
Any news??

**Comment by laurodarsh** [comment]
Looking for this solution yet

**Comment by Dev-Heisenberg** [comment]
**Use the flutter_webview_plugin like this**
[https://pub.dev/packages/flutter_webview_plugin](url)

> Make sure to add all plugin dependencies used by the plugin.

`  final flutterWebviewPlugin = FlutterWebviewPlugin();`
`@override
  void dispose() {
    flutterWebviewPlugin.dispose();
    super.dispose();
  }`
  `  @override
`
`
      
     
      WebviewScaffold(
        appBar: AppBar(
          title: Text('WebView Page'),
        ),
        url: "your url,
        userAgent: 'Fake',
        clearCookies: false,
        clearCache: false,
        hidden: true,
        appCacheEnabled: true,
        supportMultipleWindows: true,
      );`

**Comment by stuartmorgan** [comment]
Closing as out of scope; there is no "desktop" setting in the underlying webviews, and it's not even a well-defined concept (as mentioned above, different sites use different techniques to decide how to display their content). A variety of underlying webview settings are exposed that you can use to attempt to create this effect for your use case, and if there are specific settings from the OS webviews that aren't exposed but you need, please file an issues for the specific options.
