### ISSUE TITLE
Replace Whitelist/Blacklist input formatters

### ISSUE THREAD

**Issue by jmewes** [flutter/flutter#59399]
## Use case

In order to constrain values for text input widgets, there are the [WhitelistingTextInputFormatter](https://api.flutter.dev/flutter/services/WhitelistingTextInputFormatter-class.html) and [BlacklistingTextInputFormatter](https://api.flutter.dev/flutter/services/BlacklistingTextInputFormatter-class.html) classes.

## Proposal

Given that historically people were actually granted or denied access, depending whether the color of their skin was black or white, the terms "blacklist" and "whitelist" should be avoided in an attempt to weed out subconscious racism from everyday life.

So the proposal is to deprecate the classes "WhitelistingTextInputFormatter" and "BlacklistingTextInputFormatter" and replace them with feature equivalent classes using neutral terms.

Here are some ideas for an alternative naming:

WhitelistingTextInputFormatter
- MatchingTextInputFormatter
- PositiveTextInputFilter

BlacklistingTextInputFormatter
- BlockingTextInputFormatter
- NegativeTextInputFilter

## References

- https://medium.com/flutter/black-lives-matter-a8824c8cc245
- https://inews.co.uk/news/government-cyber-experts-blacklist-whitelist-racism-fears-424274
- https://www.reddit.com/r/AskHistorians/comments/866ynp/what_are_the_origins_of_the_words_blacklist_and/dw4ap11/

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/59099

**Comment by jmewes** [comment]
Closed as duplicate.
