### ISSUE TITLE
Image Picker always uses rear camera by default

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#59406]
## Steps to Reproduce

1. I am using the [ImagePicker v0.6.7+1][1] plugin to prompt the user to take a selfie with Flutter 
2. Connect real device Samsung Galaxy Note 8 Edge 
3. Run code:

     `await new ImagePicker().getImage(source: ImageSource.camera, preferredCameraDevice: CameraDevice.front);
`

    [√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.836], locale en-MU)

  [1]: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker

**Expected results:** 
Opens front camera by default.

**Actual results:** 
The above code opens the Rear camera by default instead of the front camera
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @tolotrasamuel 
please follow up on https://github.com/flutter/flutter/issues/55644,
closing as duplicate
