### ISSUE TITLE
No element gets focused when opening the app for the first time

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#59401]
b/158626304

On some devices such as Samsung Galaxy A8+, no element gets focused by the screen reader when the app is opened. This is reproducable using the "Flutter demo" example app.

This issue was also reported on Samsung A30. It does **not** happen on devices like Pixel 3 and Poco F1.

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by chunhtai** [comment]
I only have S7, but it seems to work fine. Do you think you can get a video recording that demonstrates the issue?

**Comment by chunhtai** [comment]
This seems like a native problem. I created a simple native android app, and the A8+ does not focus anything either.

**Comment by chunhtai** [comment]
I will close this issue since there is no actionable item in the flutter team
