### ISSUE TITLE
Move mock_canvas to flutter_test package

### ISSUE THREAD

**Issue by pingbird** [flutter/flutter#59413]
Many widget tests in the flutter package use `packages/flutter/test/rendering/mock_canvas.dart` as a convenient method of validating painting behaviors. This library is fully documented yet can't be imported externally.

I would like to use this library for some tests, without having to copy its implementation to my project.

## Proposal

The mock_canvas library should be moved to flutter_test, where it can be used from anywhere.

**Comment by jonahwilliams** [comment]
I think we could possibly break out that library, but we'd need to spend time to take a pass over the API and documentation
