### ISSUE TITLE
InteractiveViewer ignores scaleEnabled on web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#59411]
## Steps to Reproduce

1. Use `InteractiveViewer` in a Flutter web app.
2. Specify `scaleEnabled: false`.
3. Run the Flutter web app.
4. Use the mouse scroll wheel when the cursor is on the widget.
→ viewer zooms in, even though it should not

```dart
InteractiveViewer(
  scaleEnabled: false,
  minScale: 1,
  maxScale: 1,
  child: Text('text'),
)
```

@justinmc

**Comment by VladyslavBondarenko** [comment]
Checked with current beta `1.19.0-4.1.pre`, dev `1.20.0-0.0.pre`, master `1.20.0-1.0.pre.42` - with all of them `scaleEnabled: false` is ignored.
(`minScale: 1, maxScale: 1` prevents scaling)

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Thanks for reporting this!  Looks like a typo on my part when I was writing a method.  I'll put up a fix soon.
