### ISSUE TITLE
Remove master branch and references to the word such as master, slave, blacklist and whitelist.

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#59445]
Words such as master, slave, blacklist and whitelist are not suitable due to the deep history associated with racism.
They can be more accurate and precise than they are currently.

Golang team has already removed the use of those words in their code along with few others - https://www.reddit.com/r/golang/comments/gy9ylr/go_has_removed_all_uses_of_blacklistwhitelist_and/

There are other google projects which have done the same.

Here is a tweet from the github CEO - https://twitter.com/Una/status/1271180494944829441
Rust and python team is planning to do it as well.

There are many more projects moving to remove racism from the code. Would you please consider doing the same for flutter?

PS - Historical context for main - https://www.nakasendoway.com/the-japanese-family-system/

Please consider alternatives such as canary, develop or edge.

**Comment by skippetr** [comment]
Please close this racist issue and ban @ghost

**Comment by unmaskedd** [comment]
This is so dumb.

**Comment by mihairadulescu** [comment]
Dumbest thing ever.. this is not mature.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/59120 and https://github.com/flutter/flutter/pull/59484 are already in progress.

I'm not entirely clear on the problem with the word "master" in isolation (i.e. when not used in its colonial sense)? Can you elaborate?

**Comment by Hixie** [comment]
Since the original poster here has gone away, I am going to close this issue since we don't need it to track the work of continuing to apply our code of conduct.

**Comment by Hixie** [comment]
To close the loop on the master branch question, someone pointed me to https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html which seems like a compelling argument to rename "master". We'll add that to our list of things to do (it being a rather significant and disruptive change, it may take longer than other changes we are making here).
