### ISSUE TITLE
Cyclic Dependencies Issue in iOS from Add-To-App approach.

### ISSUE THREAD

**Issue by m-zaink** [flutter/flutter#59448]
Hey Flutter Team.
My company [Nuclei](https://gonuclei.com/) has recently made a shift towards Flutter. We are into developing plug-and-play module for our clients. So far, we have been developing frameworks in iOS to create plug-and-play modules that our client could integrate in their iOS applications.

Then we stumbled upon Flutter's `Add-To-App` approach. So we started building a module in Flutter that we could give out to our clients.

## Our tech set-up is as follows:
* We have a central framework (written in native iOS, swift), called `core` that contains all the reusable components that our other modules depend on.
* We have a bunch of other modules (let's say A, B, C, and D) that depend on `core`. Everytime our client wants to integrate, say B and C modules in their application, we give them B, C and `core` modules.
* Recently we started developing module E in Flutter and we are using method-channels where appropriate to communicate with our `core` framework. To support Flutter E, we have a base framework E built in native iOS that acts as a mediator between `core` and Flutter E.
It can be visualized as follows.

Flutter E
|
| ------
|
Native E --------> `core`

* Everything has worked so far. We are able to integrate Flutter seamlessly into our sample application that is supposed to behave like our client's application. 

## Issue we are facing
* Although everything works fine, we are running into cyclic dependencies issue the moment we integrate Flutter and App framework using option B from the [documentation](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode).
* This issue is raised whenever we build our application the second time. It doesn't occur on first run.
* Ironically, the cyclic dependency issue is occurring usually between `core` and one of A, B, C, or D frameworks. It doesn't occur between `core` and native-E framework.

So far we have totally enjoyed working with Flutter but without this issue solved, we aren't able to move any further with it. We really need help on this one.

Another close issue that we have currently is that we are not able to generate independent modules in Flutter. We are creating an umberalla framework to host a bunch of module that we intend to develop in Flutter.

**Comment by jmagman** [comment]
@m-zaink Sorry for the delay in getting back to you.  Can you give us more details of how the cyclic dependency is manifesting? Can you package `core` as a Flutter plugin instead of a module?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
