### ISSUE TITLE
Are there any working ways to make an HTTP call in flutter web?

### ISSUE THREAD

**Issue by antholeole** [flutter/flutter#59446]
http package and dart:io both have issues that result in `Unsupported operation: Platform._version occurred` and dio has an issue where no matter what, any call will have an XMLHttpError (even on a call to google.com, or some other site that is 100% setup with the correct CORS headers). Are there ANY packages / methods that will allow a successful http request? 

This is 100% blocking for me, unless someone knows anyway around this. Thanks.

**Comment by VladyslavBondarenko** [comment]
may be related to https://github.com/flutter/flutter/issues/39998,

@antholeole with what call do you have the problem when using http package?

**Comment by user97116** [comment]
Use this headers in any http libary like dio or http it worked for me!
```
headers: {
                "Access-Control-Allow-Credentials": true,
                "Access-Control-Allow-Headers":
                    "Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "GET, POST, PUT",
              },
```

**Comment by antholeole** [comment]
@VladyslavBondarenko Specifically, it's on a POST request with a body. GET's work fine, and bodyless posts also work fine.

 I'm planning on running my Flutter web project on the same URL as my API, so it's not going to be a huge issue, but the testing process is too slow to guess how a certain endpoint is going to interact with the flutter app, or praying that a json parses correctly.

**Comment by VladyslavBondarenko** [comment]
@antholeole 
> `any call will have an XMLHttpError (even on a call to google.com`

could you provide a minimal complete reproducible code sample for this?

and logs when running with `--verbose` and hitting the error `Unsupported operation: Platform._version occurred`

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
