### ISSUE TITLE
Vibration in local notifications

### ISSUE THREAD

**Issue by azharashiq178** [flutter/flutter#59450]
Hi
Is it possible to vibrate iphone when receiving local notification?

**Comment by softmarshmallow** [comment]
take a look at. https://pub.dev/packages/vibration
receiving notifications and vibrating on that event is two different topics.

p.s please use stackoverflow for development questions.

**Comment by azharashiq178** [comment]
No, i am asking when we receive local notification in native application then phone vibrates but in flutter it doesn't. I am asking about that.
