### ISSUE TITLE
flutter pug get return "Wrong full snapshot version,..." after Manually  Rolling Dart

### ISSUE THREAD

**Issue by mivanzhang** [flutter/flutter#59460]
## Steps to Reproduce

1. I had read https://github.com/flutter/flutter/wiki/Rolling-Dart for many times
2、I tried to use dart-sdk in $ENGINE_HOME/src/out/host_release/dart-sdk to replace origin dart-sdk, but I found sizes differs much, which dart-sdk I should use
3、

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

![image](https://user-images.githubusercontent.com/8842825/84644975-83a3d800-af32-11ea-9584-72903128dc75.png)

```
```

```
```

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.7-pre.15, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.7-pre.15 at /Users/zhangmeng/Desktop/code/flutter/kwai_flutter
    • Framework revision 9587ce3bd4 (28 minutes ago), 2020-06-15 17:29:12 +0800
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zhangmeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • PCLM10 • 27758289 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.



```

</details>

**Comment by iapicca** [comment]
Hi @mivanzhang 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`,
specify which [steps](https://github.com/flutter/flutter/wiki/Rolling-Dart#manually-rolling-the-version-of-dart-used-by-the-engine) did you complete 
and provide your `flutter pub get -v`
Please refrain from posting pictures if not necessary.
Thank you

**Comment by mivanzhang** [comment]
sorry ,I cannot run `flutter upgrade --force`, because my team need to stay in version 1.9.1, I cannot update my local flutter

My questions are:
1. I want to replace dart-sdk which my team had made some changes
2. when I  used dart-sdk in $ENGINE_HOME/src/out/host_release/dart-sdk to replace origin dart-sdk ,I got errors below
![image](https://user-images.githubusercontent.com/8842825/84649800-bd2c1180-af39-11ea-8691-eb3f1f6fb204.png)

what should I do to use customized dart-sdk?

**Comment by mivanzhang** [comment]
Is here anyone to help?

**Comment by TahaTesser** [comment]
Hi @mivanzhang 
Please try deleting `flutter/bin/cache` since your sdk needs to update with different sdk 
Please check this https://github.com/flutter/flutter/issues/16876#issuecomment-494335135
Thank you

**Comment by mivanzhang** [comment]
Thanks for all of you,I found the solution. The [wiki ](https://github.com/flutter/flutter/wiki/Rolling-Dart) is not designed for developer who are not googlers, so I should to analyse all  outputs of engine build to decide which I should use. later I will post a wiki to explain

**Comment by xster** [comment]
Yes, you may be the first person to actually test this wiki from a non-googler perspective. We should certainly attempt to make this wiki agnostic to google or not however. Please feel free to propose edits to this doc to make it universal. You can send us an edited fork or describe them in a github issue :)
