### ISSUE TITLE
new_gallery_ios__transition_perf 99th_percentile_vsync_transitions_missed regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59475]
First occurring at this roll --- https://github.com/flutter/flutter/pull/59222.

Doubled, but still green; now trending red.
![Screen Shot 2020-06-15 at 8 37 43 AM](https://user-images.githubusercontent.com/1435716/84677452-9642f080-aee3-11ea-90ee-0f37e4cba0e5.png)

average_vsync_transitions_missed appears affected, too:
![Screen Shot 2020-06-15 at 8 39 03 AM](https://user-images.githubusercontent.com/1435716/84677523-afe43800-aee3-11ea-973a-dd6e1dc251ae.png)

**Comment by iskakaushik** [comment]
Needs to be re-baselined, added notes here: https://github.com/flutter/engine/pull/18901#issue-431388702

**Comment by iskakaushik** [comment]
These have been rebaselined.
