### ISSUE TITLE
TextField pixel overflow when it doesn't fit // Expanded widget does not fill up entire space

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter#59470]
This is a weird issue. I have a custom "bottom-sheet-like" layout.
![image](https://user-images.githubusercontent.com/7407478/84662697-d6769300-af24-11ea-978f-0f7115743781.png)
Given the following:
![image](https://user-images.githubusercontent.com/7407478/84662793-f1490780-af24-11ea-831c-4042f826ce0f.png)
![2020-06-15_16-27-42](https://user-images.githubusercontent.com/7407478/84662979-366d3980-af25-11ea-8697-72fbeb0e2bb5.gif)
As you can see, the red area or the Placeholder() area resizes as the bottom-sheet expands/shrinks.
This red area includes the TextField. When the sheet shrinks, the TextField is squeezed out of existence, right? The issue is it throws this error:

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 26 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///C:/Users/saad4/Desktop/IdeaProjects/chacha/lib/ui/pages/search_page.dart:45:16
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#a369b OVERFLOWING
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=29.8)
...  size: Size(392.7, 29.8)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
```

And this is fine, the error is very descriptive. I have to wrap it in a Flexible widget, that's fine. So I did that and then got the first screenshot.
Let's compare with and without Flexible around the TextField:
WITHOUT Flexible: (pixel overflows when squeezed)
![image](https://user-images.githubusercontent.com/7407478/84663361-b85d6280-af25-11ea-9e44-7624c51d6125.png)
WITH Flexible AND with an Expanded() around the ListView below the TextField:
![image](https://user-images.githubusercontent.com/7407478/84663458-e478e380-af25-11ea-8496-77812cbe2e00.png)
WITH Flexible WITHOUT an Expanded() around the ListView below the TextField:
![image](https://user-images.githubusercontent.com/7407478/84663586-0ffbce00-af26-11ea-8d15-54de7844c03e.png)
```Vertical viewport was given unbounded height.```

The result we want is obviously the one without flexible. The Listview properly sizes itself to the maximum size, but for some reason, wrapping it in an Expanded truncates it and DOESN'T fill the entire available space, which is Expanded's whole job/purpose.

And yes, the Column is set to `mainAxisSize: MainAxisSize.max`, the column is filling the entire space, but the contents are not filling the entire thing. It seems when the Flexible exists in the Column, it does something to the rest of the widgets that makes them incorrectly resize. That or Expanded is not doing its job properly when a Flexible exists.

So really, we are presented with 2 problems. 
* TextField is the only widget that I know (probably all widgets that take text input, I'm not sure) is the only widget that throws pixel overflow when it's sized to something it doesn't like. 
* Flexible fixes the issue, but breaks sizing of Expanded widgets in the same list.

Here is a simplification of the issue:

```dart
Material(
        color: Theme.of(context).backgroundColor,
        child: Column(
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Flexible(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(8.0, 0.0, 8.0, 8.0),
                child: TextField(
                  focusNode: widget.focusNode,
                  controller: _searchController,
                  decoration: InputDecoration(
                      fillColor: Theme.of(context).accentColor,
                      hintText: 'Find Tracks',
                      prefixIcon: Icon(Icons.search),
                      suffixIcon: _searchController.text.isEmpty
                          ? null
                          : IconButton(
                              onPressed: () {
                                <omitted>
                              },
                              icon: Icon(Icons.clear),
                            )),
                  onEditingComplete: () {
                    <omitted>
                  },
                ),
              ),
            ),
            Container(color: Colors.blue),
          ],
        ),
      ),
```
This does NOT render a blue container.
Wrapping the Container with an Expanded does the the following:
![image](https://user-images.githubusercontent.com/7407478/84664610-7b926b00-af27-11ea-96e0-299ab5514d98.png)
I expected the blue container to fill the ENTIRE available space like the Placeholder() in the top screenshots.
Again, here is a `Flexible(child: Placeholder())` instead of a blue container:

![2020-06-15_16-45-47](https://user-images.githubusercontent.com/7407478/84664768-af6d9080-af27-11ea-8726-1b1c6209cfbe.gif)

Placing the blue container directly under the placeholder does not render the blue container.
![image](https://user-images.githubusercontent.com/7407478/84664864-d2984000-af27-11ea-8e08-356efa6e83af.png)
This is if we add an Expanded to the blue container.

![image](https://user-images.githubusercontent.com/7407478/84665031-0a9f8300-af28-11ea-9c46-a35fdb4ee9d7.png)
This is with the following inside the Column:
```dart
[
            Flexible(child: Placeholder()),

            Expanded(
                child: ListView(
              children: [
                Container(
                  height: 500,
                  color: Colors.green,
                  child: Placeholder(),
                ),
              ],
            )),
]
```
This is expected behavior! The green space is all scrollable.

Now the issue is when we give the first Flexible Placeholder a size like so.
```
            Flexible(child: Container(height: 100, child: Placeholder())),
```
We get this:
![image](https://user-images.githubusercontent.com/7407478/84665180-39b5f480-af28-11ea-82a0-3e3479eba4d8.png)
This is NOT expected behavior. We expect the green area to fill the whole thing. The Expanded around ListView is not doing it's job here for some reason.

I suspect this is what is happening with the TextField, because without the Flexible() around the first Placeholder, we get this:
![image](https://user-images.githubusercontent.com/7407478/84665354-6b2ec000-af28-11ea-83cb-24caf06b5b17.png)
Which is EXPECTED behavior
```dart
[
            Container(height: 100, child: Placeholder()),

            Expanded(
                child: ListView(
              children: [
                Container(
                  height: 500,
                  color: Colors.green,
                  child: Placeholder(),
                ),
              ],
            )),
]
```

<details>

```
flutter analyze
Analyzing chacha...

   info - The method doesn't override an inherited method - lib\logic\audioplayer\howler.dart:115:25 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\howler.dart:121:8 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\howler.dart:127:33 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\howler.dart:133:16 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\unsupported_player.dart:44:8 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\unsupported_player.dart:47:25 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\unsupported_player.dart:50:33 - override_on_non_overriding_member
   info - The method doesn't override an inherited method - lib\logic\audioplayer\unsupported_player.dart:53:16 - override_on_non_overriding_member
   info - The value of the local variable 'nbOfTracks' isn't used - lib\ui\import_dialogs.dart:94:35 - unused_local_variable
   info - The value of the local variable 'nbOfPlaylists' isn't used - lib\ui\import_dialogs.dart:181:35 - unused_local_variable
   info - The value of the local variable 'i' isn't used - lib\ui\pages\music_page.dart:176:9 - unused_local_variable
   info - The declaration '_SelectionBar' isn't referenced - lib\ui\pages\search_page.dart:67:7 - unused_element
   info - Don't import implementation files from another package - lib\ui\tile_widgets\tile.dart:10:8 - implementation_imports
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.minHeight, Tile.highlightHeight - lib\ui\tile_widgets\tile.dart:40:7 -
          must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.minHeight, Tile.highlightHeight - lib\ui\tile_widgets\tile_music.dart:24:7 -
          must_be_immutable
   info - The declaration '_printDuration' isn't referenced - lib\ui\tile_widgets\tile_playlist.dart:18:8 - unused_element
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.minHeight, Tile.highlightHeight - lib\ui\tile_widgets\tile_playlist.dart:31:7 -
          must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Tile.minHeight, Tile.highlightHeight - lib\ui\tile_widgets\tile_scored_music.dart:21:7 -
          must_be_immutable

18 issues found. (ran in 25.2s)

```

```
flutter doctor -v
[√] Flutter (Channel dev, 1.19.0-4.0.pre, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.19.0-4.0.pre at C:\flutter
    • Framework revision 2f7a59a8da (10 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\saad4\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\saad4\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\saad4\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

```

</details>

**Comment by SwissCheese5** [comment]
Here's the biggest most obvious example I can give:
https://stackoverflow.com/a/52904214/4327834
![image](https://user-images.githubusercontent.com/7407478/84691396-c1155f00-af4c-11ea-9d7c-8a5c6f9ab3d7.png)

Specifically:
![image](https://user-images.githubusercontent.com/7407478/84691432-cd99b780-af4c-11ea-8ebf-a155f979c293.png)
This is incorrect behavior. The expanded is supposed to cram the flexible to the edge, but the expanded is being limited.... for some reason. The flexible seems to want to make even space but that defeats the entire point of it's existence

**Comment by exaby73** [comment]
Hello. The `Expanded` and `Flexible` widgets both have a `flex` of 1 by default. So it makes sense that they both take half of the available space even though the child of the `Flexible` doesn't stretch to fill the parent's space.

A solution to this is to set the `flex` property of the `Flexible` to 0 or remove the `Flexible` widget altogether. If you disagree, you can comment and we can reopen this issue.
