### ISSUE TITLE
cant switch to channel beta

### ISSUE THREAD

**Issue by mikdhadc** [flutter/flutter#59485]
Cannot switch to flutter beta channel with the command 'flutter channel beta'

**Comment by TahaTesser** [comment]
Hi @mikdhadc 
Please switch to beta channel like this
`flutter channel beta`
`flutter upgrade`
`flutter doctor -v`

If the problem persist, Can you please provide your `flutter doctor -v` and `flutter channel beta -v`
Thank you

**Comment by mikdhadc** [comment]
@TahaTesser Thank You for your response.It is working now.

**Comment by xzghx** [comment]
> Hi @mikdhadc
> Please switch to beta channel like this
> `flutter channel beta`
> `flutter upgrade`
> `flutter doctor -v`
> 
> If the problem persist, Can you please provide your `flutter doctor -v` and `flutter channel beta -v`
> Thank you

Hi .I have the same problem.I can not switch to **beta** channel. I've copied my flutter sdk and named it sdk_flutter_web and changed my environment variable Path to this sdk to store my stable sdk unchanged.Also in android studio I reference to this copy. and this is the log:

```
F:\Projects\Flutter\Projects\flutter_web\test_web>flutter channel beta
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used
instead.
  running Flutter tool: C:\sdk_flutter_web\flutter
  previous reference  : C:\sdk_flutter\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

Switching to flutter channel 'beta'...
git: error: The following untracked working tree files would be overwritten by checkout:
git:    packages/flutter_tools/lib/src/base/platform.dart
git: Please move or remove them before you switch branches.
git: Aborting
Switching channels failed with error code 1.

F:\Projects\Flutter\Projects\flutter_web\test_web>flutter upgrade
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used
instead.
  running Flutter tool: C:\sdk_flutter_web\flutter
  previous reference  : C:\sdk_flutter\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

Flutter is already up to date on channel stable
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (7 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

F:\Projects\Flutter\Projects\flutter_web\test_web>flutter doctor -v
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used
instead.
  running Flutter tool: C:\sdk_flutter_web\flutter
  previous reference  : C:\sdk_flutter\flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.17.5 at C:\sdk_flutter_web\flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM E700H • 134cce44 • android-arm • Android 4.4.4 (API 19)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by minal2709** [comment]
Getting the same error:
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on Redmi Note 7S.

Response of flutter channel -v

`[ +144 ms] executing: [/home/dell/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8874f21e79d7ec66d0457c7ab338348e31b17f1d
[   +1 ms] executing: [/home/dell/flutter/] git tag --points-at HEAD
[  +18 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.3
[  +10 ms] executing: [/home/dell/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/dell/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/home/dell/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +36 ms] Flutter channels:
[   +2 ms] executing: [/home/dell/flutter/] git branch -r
[  +67 ms] * stable
[  +16 ms] "flutter channel" took 151ms.
[ +260 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0`

I want to use the beta channel. Kindly help.

**Comment by niltonjacintho** [comment]
I have the same problem!
Any kind of help?

**Comment by vilsonfreitaspacheco** [comment]
I had this same problem, resolved by reversing changes in the flutter branch
"git reset --hard HEAD"
