### ISSUE TITLE
Hello      _googleSignIn.signOut(); method working only when i m in same page

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#59499]
in my navigation page i have  added
import 'package:google_sign_in/google_sign_in.dart';
GoogleSignIn _googleSignIn = GoogleSignIn();
but it's not sigout the user until i restart the application
and my logout function
void logout() async{
     _googleSignIn.disconnect();
    var res = await Network().getData('/auth/logout');
    var body = json.decode(res.body);
    if(body['success']){
      SharedPreferences localStorage = await SharedPreferences.getInstance();
      localStorage.remove('user');
      localStorage.remove('token');

       setState(() {
        name = null;
        email = null;

      });
      Navigator.push(
          context,
          MaterialPageRoute(builder: (context)=>Login()));
    }
  }
}

**Comment by TahaTesser** [comment]
Hi @atta1234 

Please try this code sample, sign in and sign out works on same page and also new screen to match your code snippet

<details> 
<summary>Code Sample</summary> 

``` 

import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      setState(() {
        userName = value.displayName;
      });
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(iSignedIn ? userName : 'empty user name'),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut().then((value) {
              Navigator.push(
                  context, MaterialPageRoute(builder: (_) => SecondScreen()));
            });
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('You signed out!'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (6 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!

``` 

</details>

**Comment by atta1234** [comment]
> Hi @atta1234
> 
> Please try this code sample, sign in and sign out works on same page and also new screen to match your code snippet
> 
> Code Sample
> ```
> 
> import 'package:flutter/material.dart';
> import 'package:google_sign_in/google_sign_in.dart';
> 
> GoogleSignIn _googleSignIn = GoogleSignIn(
>   scopes: <String>[
>     'email',
>     'https://www.googleapis.com/auth/contacts.readonly',
>   ],
> );
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Material App',
>       theme: ThemeData.dark(),
>       home: Home(),
>     );
>   }
> }
> 
> class Home extends StatefulWidget {
>   @override
>   _HomeState createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
>   String userName;
>   bool iSignedIn = false;
>   GoogleSignInAccount _currentUser;
> 
>   @override
>   void initState() {
>     super.initState();
>     _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
>       setState(() {
>         _currentUser = account;
>       });
>       if (_currentUser != null) {
>         setState(() {
>           iSignedIn = true;
>           userName = account.displayName;
>         });
>       }
>     });
>     _googleSignIn.signInSilently().then((value) {
>       setState(() {
>         userName = value.displayName;
>       });
>     });
>   }
> 
>   Future<void> _handleSignIn() async {
>     try {
>       await _googleSignIn.signIn();
>     } catch (error) {
>       print(error);
>     }
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Material App Bar'),
>       ),
>       body: Center(
>         child: Container(
>           child: Text(iSignedIn ? userName : 'empty user name'),
>         ),
>       ),
>       floatingActionButton: FloatingActionButton.extended(
>         icon: Icon(Icons.add),
>         label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
>         onPressed: () {
>           if (!iSignedIn) {
>             _handleSignIn();
>           } else {
>             _googleSignIn.signOut().then((value) {
>               Navigator.push(
>                   context, MaterialPageRoute(builder: (_) => SecondScreen()));
>             });
>             setState(() {
>               iSignedIn = false;
>             });
>           }
>         },
>       ),
>     );
>   }
> }
> 
> class SecondScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Material App Bar'),
>       ),
>       body: Center(
>         child: Container(
>           child: Text('You signed out!'),
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         child: Icon(Icons.add),
>         onPressed: () {},
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor -v

Thanks for your reply,,,,,i have solved the issue i have called the sign out function inside handle sign in and it,,,so when it will check if user is not logout will logout him and will pop the email list for choosing account,,,,,,but what's the step for production ,,it will work or i have to do something else for production

**Comment by TahaTesser** [comment]
@atta1234 
i think you should have no problem in production if you have done proper setup for production app

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by atta1234** [comment]
> @atta1234
> i think you should have no problem in production if you have done proper setup for production app
> 
> given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
> Thank you

i have solved the issue, you can closed thank you for your time !
