### ISSUE TITLE
VERBOSE-2:transform_layer.cc(22)] TransformLayer is constructed with an invalid matrix.

### ISSUE THREAD

**Issue by marhyno** [flutter/flutter#59498]
I successfuly finished my android app. Now moving to the mac and Iphone, I managed to compile project and start debug mode but nothing is drawn on the screen except background and logo image. This is the error I get only when I run flutter run on mac. On Windows and Android is perfectly fine
`
[VERBOSE-2:transform_layer.cc(22)] TransformLayer is constructed with an invalid matrix.
[VERBOSE-2:transform_layer.cc(22)] TransformLayer is constructed with an invalid matrix.
[VERBOSE-2:transform_layer.cc(22)] TransformLayer is constructed with an invalid matrix.
`

Expected result (on android is okay)

![image](https://user-images.githubusercontent.com/26349385/84698886-db513c00-af50-11ea-805a-d8de81718714.png)

Result on Mac / Iphone

![image](https://user-images.githubusercontent.com/26349385/84698946-ee640c00-af50-11ea-9803-a43d6c4ff1bb.png)

`
[✓] Flutter (Channel master, 1.20.0-1.0.pre.47, on Mac OS X 10.15.4 19E2269, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.47 at /Users/smarcin/flutter
    • Framework revision c79de78237 (3 hours ago), 2020-06-15 19:35:07 +0300
    • Engine revision 801559ac4e
    • Dart version 2.9.0 (build 2.9.0-15.0.dev f043f9e5f6)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 6E91C8CC-1035-4131-A9A2-A24729C0BE39 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 2 categories.
`

**Comment by TahaTesser** [comment]
Hi @marhyno 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by marhyno** [comment]
[verbose.log](https://github.com/flutter/flutter/files/4789008/verbose.log)

verbose uploaded here and here is the code from the page on screenshots

`
import 'dart:convert';
import 'package:MyHorse.sk/screen/loading.dart';
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:MyHorse.sk/styles/styles.dart';
import 'package:MyHorse.sk/utils/validate.dart';
import 'package:MyHorse.sk/network_utils/api.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_auth_buttons/flutter_auth_buttons.dart';
import 'package:flutter_facebook_login/flutter_facebook_login.dart';
import 'package:http/http.dart' as http;
import 'package:google_sign_in/google_sign_in.dart';

class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  final _scaffoldKey = GlobalKey<ScaffoldState>();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final emailController =
      new TextEditingController(text: '');
  final passwordController = new TextEditingController(text: '');
  GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: [
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

  _showMsg(msg) {
    final snackBar = SnackBar(
      content: Text(msg),
      backgroundColor: Colors.red,
      action: SnackBarAction(
        label: 'Zatvoriť',
        textColor: Colors.white,
        onPressed: () {
          // Some code to undo the change!
        },
      ),
    );
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      resizeToAvoidBottomPadding: false,
      body: Container(
        padding: const EdgeInsets.fromLTRB(10.0, 0.0, 10.0, 0.0),
        decoration: BoxDecoration(
          color: Colors.black,
          image: DecorationImage(
            image: AssetImage("assets/images/login.jpg"),
            fit: BoxFit.cover,
            colorFilter: new ColorFilter.mode(
                Colors.black.withOpacity(0.8), BlendMode.dstATop),
          ),
        ),
        child: Center(
          child: Form(
            key: _formKey,
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  SizedBox(height: 40.0),
                  const Image(
                    image: AssetImage('assets/images/horseIconBig.png'),
                    width: 50,
                    height: 50,
                    color: Colors.white,
                    alignment: Alignment.center,
                  ),
                  SizedBox(height: 10.0),
                  Text(
                    'Prihlásiť sa do MyHorse.sk',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontStyle: FontStyle.normal,
                      color: Colors.white,
                      fontSize: 30.0,
                      shadows: [
                        Shadow(
                          blurRadius: 10.0,
                          color: Colors.black,
                          offset: Offset(3.0, 3.0),
                        ),
                      ],
                    ),
                  ),
                  SizedBox(height: 10.0),
                  TextFormField(
                      textCapitalization: TextCapitalization.none,
                      controller: emailController,
                      onChanged: (str) {
                        //need to implement debounce
                        emailController.value = TextEditingValue(
                            text: str.toLowerCase(),
                            selection: emailController.selection);
                      },
                      decoration: Styles.input
                          .copyWith(hintText: 'Email', labelText: 'Email'),
                      style: Styles.defaultStyle,
                      validator: (value) {
                        return Validate.requiredField(
                            value, 'Email je povinný.');
                      }),
                  SizedBox(height: 15.0),
                  TextFormField(
                      obscureText: true,
                      controller: passwordController,
                      decoration: Styles.input
                          .copyWith(hintText: 'Heslo', labelText: 'Heslo'),
                      style: Styles.defaultStyle,
                      validator: (value) {
                        return Validate.requiredField(
                            value, 'Heslo je povinné.');
                      }),
                  SizedBox(height: 15.0),
                  SizedBox(height: 20.0),
                  StyledFlatButton("Prihlásiť sa", onPressed: () {
                    if (_formKey.currentState.validate()) {
                      _formKey.currentState.save();
                      _login();
                    }
                  }),
                  SizedBox(height: 20.0),
                  FacebookSignInButton(
                      text: "Prihlásiť sa cez Facebook",
                      onPressed: () {
                        _facebookLogin();
                      }),
                  GoogleSignInButton(
                    text: "Prihlásiť sa cez Gmail",
                    onPressed: () {
                      _gmailSignIn();
                    },
                    darkMode: true, // default: false
                  ),
                  SizedBox(height: 20.0),
                  Center(
                    child: RichText(
                      text: TextSpan(
                        children: [
                          TextSpan(
                            text: "Ešte nemáte účet ? ",
                            style: Styles.p.copyWith(color: Colors.white),
                          ),
                          TextSpan(
                            text: 'Registrovať',
                            style: Styles.p.copyWith(
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                              shadows: [
                                Shadow(
                                  blurRadius: 10.0,
                                  color: Colors.black,
                                  offset: Offset(3.0, 3.0),
                                ),
                              ],
                            ),
                            recognizer: TapGestureRecognizer()
                              ..onTap = () => {
                                    Navigator.pushNamed(context, '/register'),
                                  },
                          ),
                        ],
                      ),
                    ),
                  ),
                  SizedBox(height: 15.0),
                  Center(
                    child: RichText(
                      text: TextSpan(
                          text: 'Zabudnuté heslo',
                          style: Styles.p.copyWith(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            shadows: [
                              Shadow(
                                blurRadius: 10.0,
                                color: Colors.black,
                                offset: Offset(3.0, 3.0),
                              ),
                            ],
                          ),
                          recognizer: TapGestureRecognizer()
                            ..onTap = () => {
                                  Navigator.pushNamed(
                                      context, '/resetPassword'),
                                }),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
`

**Comment by TahaTesser** [comment]
Hi @marhyno 
Your code is incomplete and uses third party 
Here i tried to reproduce create based on your code and removed the third party code and it has no issues rendering on ios

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Login(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  final _scaffoldKey = GlobalKey<ScaffoldState>();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final emailController = new TextEditingController(text: '');
  final passwordController = new TextEditingController(text: '');
//   GoogleSignIn _googleSignIn = GoogleSignIn(
//   scopes: [
//     'email',
//     'https://www.googleapis.com/auth/contacts.readonly',
//   ],
// );

  _showMsg(msg) {
    final snackBar = SnackBar(
      content: Text(msg),
      backgroundColor: Colors.red,
      action: SnackBarAction(
        label: 'Zatvoriť',
        textColor: Colors.white,
        onPressed: () {
          // Some code to undo the change!
        },
      ),
    );
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      resizeToAvoidBottomPadding: false,
      body: Container(
        padding: const EdgeInsets.fromLTRB(10.0, 0.0, 10.0, 0.0),
        decoration: BoxDecoration(
          color: Colors.black,
          image: DecorationImage(
            image: NetworkImage('https://i.imgur.com/c6fPETc.jpg'),
            fit: BoxFit.cover,
            colorFilter: new ColorFilter.mode(
                Colors.black.withOpacity(0.8), BlendMode.dstATop),
          ),
        ),
        child: Center(
          child: Form(
            key: _formKey,
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  SizedBox(height: 40.0),
                  const Image(
                    image: NetworkImage('https://i.imgur.com/c6fPETc.jpg'),
                    width: 50,
                    height: 50,
                    color: Colors.white,
                    alignment: Alignment.center,
                  ),
                  SizedBox(height: 10.0),
                  Text(
                    'Prihlásiť sa do MyHorse.sk',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontStyle: FontStyle.normal,
                      color: Colors.white,
                      fontSize: 30.0,
                      shadows: [
                        Shadow(
                          blurRadius: 10.0,
                          color: Colors.black,
                          offset: Offset(3.0, 3.0),
                        ),
                      ],
                    ),
                  ),
                  SizedBox(height: 10.0),
                  TextFormField(
                    textCapitalization: TextCapitalization.none,
                    controller: emailController,
                    decoration: InputDecoration(
                      labelText: "Enter Email",
                      fillColor: Colors.white,
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(25.0),
                        borderSide: BorderSide(
                          color: Colors.blue,
                        ),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(25.0),
                        borderSide: BorderSide(
                          color: Colors.red,
                          width: 2.0,
                        ),
                      ),
                    ),
                    onChanged: (str) {
                      //need to implement debounce
                      emailController.value = TextEditingValue(
                          text: str.toLowerCase(),
                          selection: emailController.selection);
                    },
                    // decoration: Styles.input
                    //     .copyWith(hintText: 'Email', labelText: 'Email'),
                    // style: Styles.defaultStyle,
                    // validator: (value) {
                    //   return Validate.requiredField(
                    //       value, 'Email je povinný.');
                  ),
                  SizedBox(height: 15.0),
                  TextFormField(
                      obscureText: true,
                      controller: passwordController,
                      decoration: InputDecoration(
                        labelText: "Enter Email",
                        fillColor: Colors.white,
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(25.0),
                          borderSide: BorderSide(
                            color: Colors.blue,
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(25.0),
                          borderSide: BorderSide(
                            color: Colors.red,
                            width: 2.0,
                          ),
                        ),
                      )
                      // decoration: Styles.input
                      //     .copyWith(hintText: 'Heslo', labelText: 'Heslo'),
                      // style: Styles.defaultStyle,
                      // validator: (value) {
                      //   return Validate.requiredField(
                      //       value, 'Heslo je povinné.');
                      // }
                      ),
                  SizedBox(height: 15.0),
                  SizedBox(height: 20.0),
                  // StyledFlatButton("Prihlásiť sa", onPressed: () {
                  //   if (_formKey.currentState.validate()) {
                  //     _formKey.currentState.save();
                  //     _login();
                  //   }
                  // }),
                  SizedBox(height: 20.0),
                  // FacebookSignInButton(
                  //     text: "Prihlásiť sa cez Facebook",
                  //     onPressed: () {
                  //       _facebookLogin();
                  //     }),
                  // GoogleSignInButton(
                  //   text: "Prihlásiť sa cez Gmail",
                  //   onPressed: () {
                  //     _gmailSignIn();
                  //   },
                  //   darkMode: true, // default: false
                  // ),
                  SizedBox(height: 20.0),
                  Center(
                    child: RichText(
                      text: TextSpan(
                        children: [
                          TextSpan(
                            text: "Ešte nemáte účet ? ",
                            style: TextStyle().copyWith(color: Colors.white),
                          ),
                          TextSpan(
                            text: 'Registrovať',
                            style: TextStyle().copyWith(
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                              shadows: [
                                Shadow(
                                  blurRadius: 10.0,
                                  color: Colors.black,
                                  offset: Offset(3.0, 3.0),
                                ),
                              ],
                            ),
                            recognizer: TapGestureRecognizer()
                              ..onTap = () => {
                                    Navigator.pushNamed(context, '/register'),
                                  },
                          ),
                        ],
                      ),
                    ),
                  ),
                  SizedBox(height: 15.0),
                  Center(
                    child: RichText(
                      text: TextSpan(
                          text: 'Zabudnuté heslo',
                          style: TextStyle().copyWith(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            shadows: [
                              Shadow(
                                blurRadius: 10.0,
                                color: Colors.black,
                                offset: Offset(3.0, 3.0),
                              ),
                            ],
                          ),
                          recognizer: TapGestureRecognizer()
                            ..onTap = () => {
                                  Navigator.pushNamed(
                                      context, '/resetPassword'),
                                }),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.81, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-1.0.pre.81 at /Users/tahatesser/Code/flutter_master
    • Framework revision e0ed12c73a (8 hours ago), 2020-06-16 16:53:04 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (6 available)            
    • SM M305F      • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.5.1
    • iPhone 11     • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS         • macOS                                • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 83.0.4103.97

• No issues found!

``` 

</details>

**Comment by marhyno** [comment]
Found solution, apparently I did not update flutter installation on my mac vm. 
After running `flutter upgrade` application started without any errors.

**Comment by qcks** [comment]
[My project ](https://github.com/qcks/flutter_screen_ratio_adapter)is reporting errors and black screens in release mode. But debug mode works fine.
2020-11-30 21:37:04.868 4061-4121/? E/flutter: [ERROR:flutter/flow/layers/transform_layer.cc(24)] TransformLayer is constructed with an invalid matrix.
2020-11-30 21:37:04.868 4061-4121/? E/flutter: [ERROR:flutter/flow/layers/transform_layer.cc(24)] TransformLayer is constructed with an invalid matrix.

**Comment by ali9653** [comment]
> [My project ](https://github.com/qcks/flutter_screen_ratio_adapter)is reporting errors and black screens in release mode. But debug mode works fine.
> 2020-11-30 21:37:04.868 4061-4121/? E/flutter: [ERROR:flutter/flow/layers/transform_layer.cc(24)] TransformLayer is constructed with an invalid matrix.
> 2020-11-30 21:37:04.868 4061-4121/? E/flutter: [ERROR:flutter/flow/layers/transform_layer.cc(24)] TransformLayer is constructed with an invalid matrix.

did you find any solution?
