### ISSUE TITLE
Update packaged libimobiledevice to latest

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#59506]
- [libimobiledevice 1.3.0](https://github.com/libimobiledevice/libimobiledevice/releases/tag/1.3.0)
- [libusbmuxd 2.0.2](https://github.com/libimobiledevice/libusbmuxd/releases/tag/2.0.2)
- [libplist 2.2.0](https://github.com/libimobiledevice/libplist/releases/tag/2.2.0)

Test newest versions with the tool. If all looks good, package it up and ship it.

Also fix https://github.com/flutter/flutter/issues/50299

**Comment by christopherfujino** [comment]
While I'm at it, I should remove the few references of ideviceinstaller from the codebase.

**Comment by jmagman** [comment]
> While I'm at it, I should remove the few references of ideviceinstaller from the codebase.

I can do that.

**Comment by christopherfujino** [comment]
> > While I'm at it, I should remove the few references of ideviceinstaller from the codebase.
> 
> I can do that.

SGTM, thanks

**Comment by jmagman** [comment]
`flutter run` (iproxy), `flutter install`, `flutter screenshot` are working on these new versions from my local testing.
