### ISSUE TITLE
Hard to find dropdown menu items in driver test

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#5951]
It seems like the when DropdownButton button is tapped, a dropdownroute with dropdownMenuItem was created.  The dropdownMenuItem is identical to the one in dropdownbutton. This prevents us performing driver test on selecting dropdownMenuItem as the key, values and text for the them are exactly the same. Is it possible to have a different key for the one in dropdownroute on button tapped?

**Comment by abarth** [comment]
Good point.  We should find a way to make that easier to find in a driver test.

**Comment by Hixie** [comment]
If this was with flutter_test, you could use `.first` on the finder (or `.last`). Maybe flutter_driver could implement that for its finders too. Similarly maybe we should implement predicates at that level. cc @yjbanov 

If you're tapping the menu item, you can also rely on the fact that they'll be in the same place on the screen, and just tap the one on the bottom, since we actually just do real dispatch and you'll end up hitting the one on the top.

**Comment by eseidelGoogle** [comment]
Was this related? https://github.com/flutter/flutter/commit/47666af54c44e907c6a0426cb88cde3355bd9106

**Comment by vy0592** [comment]
I think it's not related. The driver tests complains too many elements because there are two elements with same key and content in the page.

**Comment by jxmorris12** [comment]
I dealt with this issue as well today and it's quite confusing at first. The DropdownMenuItem that is a child of the DropdownButton is actually just hidden behind the visible item, so whenever you try and tap that one you actually just select whatever shows up in the center of the DropdownButton.

Even if this isn't changed in implementation of DropdownButton, some documentation would be helpful.

**Comment by dguralnick** [comment]
@Hixie  @eseidelGoogle 

Mulligan is also in need of some improvements here. The [flutter_driver finders](https://docs.flutter.io/flutter/flutter_driver/CommonFinders-class.html) are very limited making it difficult to find a single instance of any repeated widget. If the finders supported descendant, first, and last (as they do in [flutter_test](https://docs.flutter.io/flutter/flutter_test/CommonFinders-class.html)) this would become much easier.

As is, the only way to find one of a set of repeated elements is to assign a predictable unique key to the first element in the list. This often requires some hackery - we usually don't generate lists based on indices - happens in a callback that takes some renderable data type.

**Comment by yjbanov** [comment]
I thought I fixed this in https://github.com/flutter/flutter/pull/11767, but apparently I didn't. Does anyone have a small sample that has this issue. I'll take a look.

**Comment by yjbanov** [comment]
Or perhaps someone can spot a flaw in our test ([test app](https://github.com/flutter/flutter/blob/e43eab656d8e743630a8ff3ea25325bd80c45ae8/dev/integration_tests/ui/lib/driver.dart#L61), [driver script](https://github.com/flutter/flutter/blob/e43eab656d8e743630a8ff3ea25325bd80c45ae8/dev/integration_tests/ui/test_driver/driver_test.dart#L81))

**Comment by dguralnick** [comment]
Actually, I will file a separate issue for this request - was piggybacking on this because some of the discussion was related.

**Comment by yjbanov** [comment]
Cool. I'll assume that _this_ issue is fixed in #11767.

**Comment by baseten** [comment]
I am still having trouble doing this. There are still two instances of the DropDownMenuItem with the same keys in the widget tree. Has this been fixed and if so how can I be sure to find the correct one?

**Comment by baseten** [comment]
Solution appears to be to set the ValueKey on the child of the `DropdownMenuItem` eg. `Text` rather than the `DropdownMenuItem` itself.
