### ISSUE TITLE
Potentially inaccurate surrogate pair detection

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#59513]
@HansMuller [brought up](https://github.com/flutter/flutter/pull/53381#discussion_r440470378) that our _isUtf16Surrogate method in text_painter.dart is potentially inaccurate.  See the [Wikipedia definition of surrogate pair](https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF).

https://github.com/flutter/flutter/blob/248d746575b713da74144750527356a1c0095546/packages/flutter/lib/src/painting/text_painter.dart#L603

**Comment by lrhn** [comment]
The code is correct if the input is a UTF-16 code unit. The `& 0xF800` maps every integer in the range 0xD800 through 0xDFFF to 0xD800.

The only issue would be if the value was not in the range 0..0xFFFF. In that case use `& ~0x7FF` instead.

**Comment by justinmc** [comment]
Note to self: see also https://github.com/flutter/flutter/pull/53381#discussion_r441495677.
