### ISSUE TITLE
flutter build apk attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by zc10917** [flutter/flutter#59523]
## Steps to Reproduce

1. ...
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  transparent_image: ^0.1.0
  toast: ^0.1.3
  fluro: ^1.3.4
  android_intent: ^0.3.7+2
  connectivity: ^0.4.3+2
  dio: ^3.0.0
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.7+3
  cached_network_image: ^2.0.0
  flutter_statusbarcolor: ^0.2.0
  flutter_screenutil: ^1.0.2
  web_socket_channel: ^1.1.0
  logger: ^0.8.3
  sqflite: ^1.3.0
  floor: ^0.12.0
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  rxdart: 0.22.3
  pull_to_refresh: ^1.5.7
  flutter_image_compress: ^0.6.5+1
  image_picker: ^0.6.5
  multi_image_picker: ^4.6.6
  image_cropper: ^1.2.1
  sprintf: ^4.0.2
  permission_handler: ^5.0.0+hotfix.6
  fluwx: ^2.1.0
  webview_flutter: ^0.3.22+1
  flutter_alipay: ^1.0.0
  flutter_bugly: ^0.2.8
  package_info: ^0.4.1
  jpush_flutter: ^0.5.5
  flutter_growingio_track: ^2.6.4
  keyboard_visibility: ^0.5.6

build.gradle(app)
android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.**.***"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
}
2. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.46.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
3. ...

flutter build apk

AAPT: error: resource android:attr/ttcIndex not found.
AAPT: error: resource android:attr/fontVariationSettings not found.

**Comment by TahaTesser** [comment]
Hi @zc10917 
Can you please provide your `flutter build apk --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by zc10917** [comment]
I have found the reason. Some of my dependencies just do not compile target sdk 28. I just modify it, and it work out

**Comment by iapicca** [comment]
Hi @zc10917 
I'm glad to hear that,
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
