### ISSUE TITLE
Downgrading from master to stable, flutter run fails, Invalid `Podfile` file: cannot load such file - /flutter/packages/flutter_tools/bin/podhelper

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#59522]
https://github.com/flutter/flutter/pull/59044 moved the Podfile logic from the user's project to a new Ruby helper script in the tool.  If you generate a new project in master, the Podfile contains:
```ruby
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
```
If you downgrade to a version before #59044 landed, that file doesn't exist and you get the error:
```
Running pod install...                                              0.8s
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: cannot load such file --
    /Users/m/Projects/flutter/packages/flutter_tools/bin/podhelper.
```

**Comment by jmagman** [comment]
The generated Podfile should check if the file exists, and if not give a nice error message that a newer version of Flutter is required, or they should regenerate their Podfile on the older version of Flutter they would prefer to use.

**Comment by jmagman** [comment]
That script is present on master, and if you create a new project in master, it will import the new script.  And when you downgrade back to stable or beta or dev, the script won't be there, but your project won't be downgraded.  You can regenerate the file:
```
$ rm ios/Podfile
$ flutter build ios
```

**Comment by shinriyo** [comment]
how to install or download flutter/packages/flutter_tools/bin/podhelper?

**Comment by jmagman** [comment]
#59044 is on 1.20.0-2.0.pre, so [master and dev channels](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), at the moment.  Either stay on one of those channels and use the script, or on whatever channel you are on, regenerate your Podfile.  At some point #59044 will be in all channels.

> ```
> $ rm ios/Podfile
> $ flutter build ios
> ```
