### ISSUE TITLE
Ability to disable new flutter version check when don't want to upgrade 

### ISSUE THREAD

**Issue by LeiQiao** [flutter/flutter#59533]
everytime when I run flutter build command，it always checking new version first and print "A new version of Flutter is available! ", it tooks me lots time even build a simple js file

╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
 |   ╚════════════════════════════════════════════════════════════════════════════╝

Compiling lib/main.dart for the Web...                              3.5s

1. I am in chinese mainland using aliyun as a CI/CD server.
2. I had set PUB_HOSTED_URL / FLUTTER_STORAGE_BASE_URL to chinese repo.

**Comment by TahaTesser** [comment]
Hi @LeiQiao 
Is there any reason you don't want to upgrade?  I am not sure we can disable this check right now, couldn't find any solution for this
Thank you

**Comment by LeiQiao** [comment]
I had set up a automatic build and deploy server in aliyun, and had already set chinese repo, but It still tooks me almost 5mins to check upgrade.
Another reason why we donot want to check upgrade is we want to use specific version of flutter in CI/CD server same as our develop environment.
In developing we want to know the new feature of new flutter on time, and we can test it on our apps, after that we can safely upgrade our CI/CD server.

**Comment by christopherfujino** [comment]
@LeiQiao You can use the flag `--no-version-check` to override this check https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L82. I would recommend using that for all ci calls.

**Comment by LeiQiao** [comment]
awesome！thanks！！

**Comment by pedia** [comment]
```shell
alias flutter=flutter --no-version-check
```

This worked for me(lower speed).
