### ISSUE TITLE
Flutter web run failing

### ISSUE THREAD

**Issue by GadepalliAditya1998** [flutter/flutter#59532]
Hey, When I try to build flutter web project, it gives me this error as soon as the chrome opens during syncing the files.

It works in Windows, but not in ubuntu.

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from Dart debug extension at http://localhost:37807
ERROR - 2020-06-15 22:21:21.821633
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
createInjectedHandler.<fn>.<fn> (package:dwds/src/handlers/injected_handler.dart:35:39)

Flutter Logs:
`[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.1.pre at /home/laptop/Documents/flutter
    • Framework revision f994b76974 (6 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/laptop/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/laptop/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 4.0)
    • Android Studio at /home/laptop/Documents/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

! Doctor found issues in 1 category.`

**Comment by Daibaku9999** [comment]
Same here after upgrading new version 1.19 on beta channel.

**Comment by TahaTesser** [comment]
Hi @GadepalliAditya1998 @Daibaku9999 
Please try this [workaround](https://stackoverflow.com/a/61847858) 
Thank you

**Comment by Daibaku9999** [comment]
Worked for me thanks so much!!

**Comment by GadepalliAditya1998** [comment]
Ya worked for me too, Thank you so much and I am closing this issue. May be flutter team has to fix without any additional packages.
