### ISSUE TITLE
flutter view controller can't response click event after pop from native view controller

### ISSUE THREAD

**Issue by cer-cer** [flutter/flutter#59547]
## Steps to Reproduce

I used Android studio create a new flutter project. and do as below:
 1 Add a button in the flutter code , and present a native view controller when click by MethodChannel .
 2 In the native view controller i add a button . when click the native button then present a flutter view controller. 
 3 dismiss the flutter view controller and reset the FlutterEngineer's view controller.
 4 dismiss the native view controller.
  5 and then the root view controller(flutter view controller) can't response the click event.

The flutter engine shared by the view controller.

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.3 19D76, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)

</details>

1, FlutterViewController A's code:

Flutter code:
`
class MyHomePage extends StatefulWidget{
@override
  _MyHomePageState createState(){
    return _MyHomePageState();
  }
}

class _MyHomePageState extends State<MyHomePage>{
     static const MethodChannel methodChannel =
  MethodChannel('test.com');

  void getNativeValue() async {
            await methodChannel.invokeMethod('doTest');
    }
@override
  Widget build(BuildContext context) {
     return Button...;
}
`

Native:
    Use the ChannelMethod recv the flutter event and present a viewcontroller as below:
`
var engine: FlutterEngine?
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController;
    let  methodChannel = FlutterMethodChannel.init(name: "test.com", binaryMessenger: controller as! FlutterBinaryMessenger)
    controller.setFlutterViewDidRenderCallback {
        print(#function)
    }
    engine = controller.engine
    
    methodChannel.setMethodCallHandler {[weak self] (method, result) in
        if method.method == "doTest"{
            self?.doTest(methodName: method, result: result)
        }
    }
    
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func doTest(methodName: FlutterMethodCall, result: FlutterResult) {
        result("ok")
        
        let ty = TestViewController()
        window.rootViewController?.present(ty, animated: true, completion: nil)
    }
`

2, The native view controllers just a button the click event function as below :
` 
 @objc func gotoFlutter(){
        print(#function)
        
        let app = UIApplication.shared.delegate as! AppDelegate
        let vc = FlutterViewController.init(nibName: nil, bundle: nil)

         //**It seems that this line influence the engine.**
        app.engine!.viewController = vc
        
        let  methodChannel = FlutterMethodChannel.init(name: "test.com", binaryMessenger: vc as! FlutterBinaryMessenger)
        methodChannel.setMethodCallHandler { (method, result) in
            if method.method == "doClose" {
                result("ok")
                
                let app = UIApplication.shared.delegate as! AppDelegate
                if let rootVc = app.window?.rootViewController as? FlutterViewController, let engine = app.engine {
                     //It seems that this line influence the engine.
            engine.viewController = rootVc
        }
                vc.dismiss(animated: true, completion: nil)
            }
        }
        present(vc, animated: true, completion: nil)
        
    }
` 

Please help me, thanks~

**Comment by TahaTesser** [comment]
Hi @cer-cer 
Can you please provide and a complete reproducible minimal code sample including flutter and native code
Thank you

**Comment by cer-cer** [comment]
like:
1, The app launch by a FlutterViewController which has an engine. i get the engine when app launch finished.

let rootVc = windows.rootViewController as! FlutterViewController
let engine = rootVc.engine

2, 
let nativeVc = UIViewController.new()
rootVc.present(rootVc)

3, let otherNativeVc = FlutterViewController.init(engine: engine)
engine.viewController = otherNativeVc
nativeVc.present(otherVc)

then , the otherNativeVc can click, everything looks good.

4, 
engine.viewController = rootVc
otherNativeVc.dismiss()

5,
  nativeVc.dismiss()
and then ,the rootVc's button can't click.

**Comment by cer-cer** [comment]
It is very strange if i make the app in back-end, and then make it front-end.
The Flutter view controller can response click event.

so what else need i to do when use more FlutterViewController and single Flutter Engine ?

**Comment by cer-cer** [comment]
Oh,
it seems don't need to set the view controller of FlutterEngine when create new FlutterViewController.
it working~

**Comment by cer-cer** [comment]
I resolved it.
Due to the present view controller not full screen, so the viewWillApear isn't called cause.
Please close this bug.
Thanks.

**Comment by TahaTesser** [comment]
Hi @cer-cer 
Glad you resolve the issue! 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by imTamil** [comment]
@cer-cer I too ended with the same issue, could you please explain the solution in detail?

**Comment by cer-cer** [comment]
if you present a view controller, please make sure it present style is 
. modalPresentationStyle = UIModalPresentationFullScreen
The default value is UIModalPresentationAutomatic now.
