### ISSUE TITLE
[url_launcher] Content-Disposition and Content-Type header link failed.

### ISSUE THREAD

**Issue by louia** [flutter/flutter#59542]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. 

```
url ="https://test/index.php"

                              if (await canLaunch(url)) {
                                await launch(
                                    url,
                                );
                              } else {
                                throw 'Could not launch $url';
                              }
```

in index.php
```
    header('Content-Length: ' . $filesize);
// header("Content-Type: application/vnd.android.package-archive");
    header("Content-disposition: attachment;filename={$filename}");

    readfile($filename);
```

**Expected results:** 

Download on Chrome Android without the Content-Type header throw error. so with the Content-Type it work just fine.

But when  i reput the Content-Type chrome display a message like "Be aware the file can damage your phone...".

When in Flutter App i click to open the URL with Content-Type header in place (and with another tabs open), the page do not appear. but when i remove Content-Type header it go to the page but the dowload throw an error.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
\Hi @louia 
Can you please provide your `flutter doctor -v` your `flutter run --verbose`
Thank you

**Comment by louia** [comment]
```
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [version 10.0.18363.778], locale fr-FR)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (13 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\chovaneck\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\chovaneck\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • SM G950F • ce09171964933c0903 • android-arm64 • Android 9 (API 28)

```

**Comment by zidian257** [comment]
> ## Steps to Reproduce
> 1. Run `flutter create bug`.
> 2. Update the files as follows: ...
> 
> ```
> url ="https://test/index.php"
> 
>                               if (await canLaunch(url)) {
>                                 await launch(
>                                     url,
>                                 );
>                               } else {
>                                 throw 'Could not launch $url';
>                               }
> ```
> 
> in index.php
> 
> ```
>     header('Content-Length: ' . $filesize);
> // header("Content-Type: application/vnd.android.package-archive");
>     header("Content-disposition: attachment;filename={$filename}");
> 
>     readfile($filename);
> ```
> 
> **Expected results:**
> 
> Download on Chrome Android without the Content-Type header throw error. so with the Content-Type it work just fine.
> 
> But when i reput the Content-Type chrome display a message like "Be aware the file can damage your phone...".
> 
> When in Flutter App i click to open the URL with Content-Type header in place (and with another tabs open), the page do not appear. but when i remove Content-Type header it go to the page but the dowload throw an error.
> 
> **Actual results:**
> 
> Logs

On server side, I added Content-Type: application/octet-stream to bypass this bug, as from MDN https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#applicationoctet-stream, browser will treat http body as attachment.

**Comment by stuartmorgan** [comment]
Your sample code is only code fragments, do it's not clear what the repro steps are here. Can you provide a full working example?

Also, is this platform-specific?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
