### ISSUE TITLE
How do I know ListView Item is invisible in the screen?

### ISSUE THREAD

**Issue by paozhuanyinyu** [flutter/flutter#59551]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @paozhuanyinyu 
follow up on https://github.com/flutter/flutter/issues/19941. Closing as duplicate

See https://stackoverflow.com/questions/57011733/find-out-which-items-in-a-listview-are-visible.
See existing or open a new Stackoverflow question. You can also try to get help here https://www.reddit.com/r/flutterhelp/.
