### ISSUE TITLE
'Module 'path_provider' not found' error message when building in release mode

### ISSUE THREAD

**Issue by alicew104** [flutter/flutter#59564]
### **Problem:**

When building my flutter app in debug mode, it compiles with no problems, but when i build it in release mode, the build fails and xcode reports the error as `Module 'path_provider' not found`.
I think that when i run `flutter build ios` it's not generating all the necessary files, however there is no error message when running this command, it seemingly succeeds...  

### Output of flutter doctor:
![Screenshot 2020-06-16 at 15 57 11](https://user-images.githubusercontent.com/57001000/84792066-59fab780-afeb-11ea-8afc-f1aa7b3a5f4c.png)

(I'm not using intelliJ)

### The error message in xcode: 
![Screenshot 2020-06-16 at 16 00 52](https://user-images.githubusercontent.com/57001000/84792230-86163880-afeb-11ea-8cef-061da164751f.png)

### Contents of my Podfile:
``` 
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### The file view of my iOS folder in VSCode:
![Screenshot 2020-06-16 at 15 59 49 (1)](https://user-images.githubusercontent.com/57001000/84792982-71867000-afec-11ea-834b-6acb7d983741.png)

I've been opening xcode with the command 'open ios/Runner.xcworkspace/' 
I've tried rebooting xcode, and my whole computer multiple times and I've tried running pod install from the ios folder several times; I always get a success message. 
I'd really appreciate some advice as this is an issue that I've been stuck on for a couple of weeks!!

**Comment by iapicca** [comment]
Hi @alicew104 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, 
your `flutter run--release --verbose`,
your `pubspec.yaml`
and a minimal reproducible code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by virgule-xyz** [comment]
Same problem here, even after a clean up...

**Comment by iapicca** [comment]
Hi @virgule-xyz 
could you please provide the info listed [above](https://github.com/flutter/flutter/issues/59564#issuecomment-645197676)
Thank you

**Comment by alicew104** [comment]
Hi, I have managed to fix this issue by creating a new flutter project, copying over my code, deleting the `podfile` and the `podfile.lock` and then running `flutter clean`. I think that perhaps I had fiddled about with the project so much whilst trying to fix it that there were lots of issues. Thank you for your help :-)

**Comment by iapicca** [comment]
Hi @alicew104 
I'm glad that you fixed the issue,
thank you for letting me know

@virgule-xyz 
if following the steps provide by @alicew104 doesn't fix the issue for you
please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
Thank you

**Comment by virgule-xyz** [comment]
Ok I'll give you a feedback as soon as I try again :)
