### ISSUE TITLE
Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by chegmarco1989** [flutter/flutter#59567]
Bonjour.
I NEED YOUR HELP ABOUT PROBLEM TO BUID APK. PLEASE !!!

I have been trying since yesterday to build the **APK** of my FLUTTER Application to no avail (without any success). It becomes a headache for me.

r.bat build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
```bash
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
> Running Gradle task 'assembleRelease'...
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d
> Invalid depfile: C:\Users\ChegMarco\Desktop\dsqsdev\.dart_tool\flutter_build\4f0d6f64cf697123f8a8678d57109748\kernel_snapshot.d

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;
                          ^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
 #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:604:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:472:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:38:22)
#5      starter (package:flutter_frontend_server/server.dart:149:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 4s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     802,7s (!)
Gradle task assembleRelease failed with exit code 1
```

Below you have the results of the "flutter doctor" command in **ANDROID-STUDIO** and below the screenshots numbered from 1 to 4 of the compilation errors when I execute the "_**flutter build appbundle**_" command

HELP ME PLEASE SUCCEED THE "**APK**" COMPILATION OF MY APP.

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [version 10.0.18363.900], locale fr-CI)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ChegMarco\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.46.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by iapicca** [comment]
Hi @chegmarco1989 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide 
your updated `flutter doctor -v`,
your `flutter build appbundle --verbose` 
and a minimal reproducible code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by apmysore** [comment]
I am seeing the same error too. I tried executing the commands above and here are my outputs:

C:\Users\apmysore>flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\Users\apmysore\flutter
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\apmysore\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

C:\Users\apmysore>flutter build appbundle --verbose
[ +132 ms] executing: [C:\Users\apmysore\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +78 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] bbfbf1770cca2da7c82e887e4e4af910034800b6
[   +3 ms] executing: [C:\Users\apmysore\flutter/] git tag --contains HEAD
[ +243 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.20.2
[  +10 ms] executing: [C:\Users\apmysore\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [C:\Users\apmysore\flutter/] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +85 ms] executing: [C:\Users\apmysore\flutter/] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +63 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +45 ms] "flutter appbundle" took 119ms.
[  +28 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
           Do not run this command from the root of your git clone of Flutter.
[   +6 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:957:11)
           #1      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #5      _rootRun (dart:async/zone.dart:1190:13)
           #6      _CustomZone.run (dart:async/zone.dart:1093:19)
           #7      _runZoned (dart:async/zone.dart:1630:10)
           #8      runZoned (dart:async/zone.dart:1550:10)
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #12     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #13     _rootRunUnary (dart:async/zone.dart:1198:47)
           #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #21     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #22     _rootRunUnary (dart:async/zone.dart:1198:47)
           #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #29     _rootRun (dart:async/zone.dart:1190:13)
           #30     _CustomZone.run (dart:async/zone.dart:1093:19)
           #31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +263 ms] ensureAnalyticsSent: 258ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by FunlabStudio** [comment]
HELP HELP HELPPPPP


Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/AntDesign.ttf'. The parent directory may not exist, or the user does not have permis
sion to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/FontAwesome5_Regular.ttf'. The parent directory may not exist, or the user does not
have permission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/FontAwesome.ttf'. The parent directory may not exist, or the user does not have perm
ission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Feather.ttf'. The parent directory may not exist, or the user does not have permissi
on to create this file.



FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\wasiq\Downloads\flutter_windows_1.22.2-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\wasiq\Downloads\flutter_windows_1.22.2-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 1s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     183.9s
Gradle task assembleRelease failed with exit code 1
