### ISSUE TITLE
Create a template for web in the flutter create -t plugin command

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#59562]
The plugin template for `flutter create` is missing a template for web
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/plugin

In order to add web support with the new `add-platform` command, and to support creating plugin for web, we will need to add a template for web in the directory, as well as updating the pubspec.yaml in the directory to support web.

**Comment by cyanglaz** [comment]
cc @ditman

**Comment by ditman** [comment]
This looks like a good example of a plugin that has an implementation for web within the same package, instead of split in several packages: https://github.com/bratan/flutter_device_locale

**Comment by ditman** [comment]
This can be set to `true` for testing: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/template.dart#L112
