### ISSUE TITLE
Flutter does not provide intl.PropertyProvider to WebEngine

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59572]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=54042.

**Comment by kf6gpe** [comment]
We believe this is in the Fuchsia webview plugin; we'll keep this open while the upstream issue is open, but at present we don't think there's anything to do on the Flutter side.

**Comment by kf6gpe** [comment]
Decreasing priority.

**Comment by ddorwin** [comment]
This was fixed in Fuchsia and can be closed.

**Comment by kf6gpe** [comment]
Fixed upstream.
