### ISSUE TITLE
ReorderableListView triggering onReorder even when have a single item

### ISSUE THREAD

**Issue by AlbertoMonteiro** [flutter/flutter#59599]
# Description

When ReorderableListView just contains a single item and you try to reorder it, it trigger `onReorder` with oldIndex = 0 and newIndex = 1.
The list just contains one single element, so the index value 1 is invalid.

## Steps to Reproduce

1. Close this repository: https://github.com/AlbertoMonteiro/flutter_ReorderableListView_bug
2. Run the application and try to reorder the unique element.

**Expected results:** Do not trigger `onReorder` method

**Actual results:** `onReorder` being triggered with wrong values

<details>
  <summary>Logs</summary>

```
> flutter analyze
Analyzing bug...
No issues found! (ran in 5.2s)
```

```
> flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o 10.0.19041.329], locale pt-BR)
    • Flutter version 1.17.3 at C:\devtools\flutter
    • Framework revision b041144f83 (12 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\alberto_albuquerque\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.46.0)
    • VS Code at C:\Users\alberto_albuquerque\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @AlbertoMonteiro 
in the `ReorderableListView` the commets state
```console
Called when a list child is dropped into a new position to shuffle the underlying list.
This [ReorderableListView] calls [onReorder] after a list child is dropped into a new position.
```
the `onReorder` is in fact triggered when the only element in the list 
is dropped in a new position, therefore doesn't appear to be a bug.

I can imagine scenarios where the current behaviour could be desirable
(maybe adding an element if the to the list or else);

I'm not sure to understand what issue is trying to fix
and what inconvenience the current behaviour is causing.

Should I consider this issue a feature request?
Thank you

**Comment by AlbertoMonteiro** [comment]
If there is a single element in any collection, there is no way to change the order of this, since the element will be in same order no matter what.
So with the current behavior, this wrong `onReorder` call, send to the consumer an invalid array position, since `child[1]` does not exist and even worse throws an exception `Uncaught Error: RangeError (index): Index out of range: index should be less than 1: 1` 
To fix that I have to make a workaround to avoid this issue `if (oldIndex < newIndex) newIndex--;` and then I have oldIndex == newIndex, so I reordered the element in same position? This is not a state change, the position still the same. 
So if the state didn't change, why I have to trigger the `onReorder`? Just to run an unnecessary computation?

**Comment by iapicca** [comment]
Hi @perclasson I'm tagging you for visibility, 
I' don't know if you meant this [message](https://github.com/flutter/flutter/issues/24786#issuecomment-644964642) as a validation,
in any case please consider the points listed [above](https://github.com/flutter/flutter/issues/59599#issuecomment-645261909);
applying these changes might break some app.
Thank you
