### ISSUE TITLE
Why do we need to Copy a listeners list for Iterating?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#59601]
I found the following snippet of code:

https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/services/raw_keyboard.dart#L540

```dart
for (final ValueChanged<RawKeyEvent> listener in List<ValueChanged<RawKeyEvent>>.from(_listeners)) {
  if (_listeners.contains(listener)) {
    listener(event);
  }
}
```

I was wondering what the difference is between the two lists, i.e. why the condition is necessary 🤔

@gspencergoog I saw that you authored the code, maybe you have some insights? 🙂

**Comment by jonahwilliams** [comment]
because a Listener might need call an unsubscribe API, which would modify the list while an iteration is in process - throwing a ConcurrentModificationException

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams So the if-statement ensures that no listener is called that was removed in the callback of **another listener**?

In that case, `List.of` would be the better choice here, right?
