### ISSUE TITLE
BottomNavigationBar changes brightness when 'type' changes

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#59604]
I have a `BottomNavigationBar` with a few items in it. When the `BottomNavigationBar` has `type` `fixed`, the items are displayed as dark on a light background. When that same `BottomNavigationBar`'s `type` becomes `shifting`, all items suddenly become white on a light background.

Fixed example:
![Screen Shot 2020-06-16 at 2 53 43 PM](https://user-images.githubusercontent.com/7259036/84832405-0fc10880-afe2-11ea-8782-1b2f594cb86e.png)

Shifting example:
![Screen Shot 2020-06-16 at 2 53 54 PM](https://user-images.githubusercontent.com/7259036/84832414-1485bc80-afe2-11ea-8bc7-c92516c196fe.png)

Flutter version:

Flutter 1.20.0-0.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision d9653445f4 (7 days ago) • 2020-06-09 18:43:03 -0400
Engine • revision e8c13aa012
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

**Comment by HansMuller** [comment]
This is working as intended, however it _is_ a bit confusing.

**Comment by matthew-carroll** [comment]
Ah, I see. I'll go ahead and close the issue then. Thanks.
