### ISSUE TITLE
Proposal for making ChangeNotifier.notifyListeners O(N) instead of O(N^2)

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#59611]
Hello!

As stated by the documentation, ChangeNotifier is O(N) for adding/removing listeners and O(N^2) for dispatching notifications.

My understanding is that this is necessary because `notifyListeners` tries to support the case where listeners are added/removed while iterating through the listeners.

But I believe this could be simplified if instead of storing listeners in a `List`, they were stored in a `LinkedList`.

## The idea

Basically, the change is about transforming:

```dart
notifier.addListener(listener);
notifier.removeListener(listener);
```

into:

```dart
final removeListener = notifier.addListener(listener);
removeListener();
```

Where `addListener` is implemented this way:

```dart
class _ListenerEntry extends LinkedListEntry<_ListenerEntry> {
  _ListenerEntry(this.listener);
  final void Function() listener;
}

class ChangeNotifier {
  LinkedList<_ListenerEntry> _listeners = LinkedList();

  VoidCallback addListener(VoidCallback listener) {
    final entry = _ListenerEntry(listener);
    _listeners.add(entry);
    return entry.unlink;
  }

  void notifyListener() {
    // By manually iterating over the entries, if a listener adds or remove listeners
    // then the change will be effective immediately, without needing a `contains` call
    // and having to make a copy of the list.
    for (var entry = _listeners.first; entry != null; entry = entry.next) {
      entry.listener();
    }
  }
}
```

This removes the need for a copy & the contains call and makes adding/removing listeners O(1) + notifying listeners O(N), while preserving support for adding/removing listeners on the fly.

**Comment by HansMuller** [comment]
This is a nice change but it would require rewriting all of the code that uses ChangeNotifier (not just in Flutter of course, but _all_ the code).  For example all of the State subclasses that add and remove listeners would need to add state for the addListener() return values.

**Comment by rrousselGit** [comment]
Indeed, hence why I haven't made a PR

Although I would expect that most people who use Listenable/ChangeNotifier uses it through a widget like AnimatedBuilder or ChangeNotifierProvider

I've personally forked ValueNotifier a while ago to apply that pattern, so I don't need this myself.

**Comment by goderbauer** [comment]
It appears that this would change the behavior of the ChangeNotifier as well. Currently it is documented in https://master-api.flutter.dev/flutter/foundation/ChangeNotifier/notifyListeners.html:

> Listeners that are added during this iteration will not be visited.

This change would call these listeners, no? Is that intentional?

**Comment by rrousselGit** [comment]
Indeed. But this could still be done:

```dart
class _ListenerEntry extends LinkedListEntry<_ListenerEntry> {
  _ListenerEntry(this.listener);
  final void Function() listener;
}

class ChangeNotifier {
  LinkedList<_ListenerEntry> _listeners = LinkedList();
  // Keeps track of the first newly added listened inside notifyListeners
  // to stop the dispatching and not immediately execute new listeners
  _ListenerEntry _firstNewlyAddedEntry;

  VoidCallback addListener(VoidCallback listener) {
    final entry = _ListenerEntry(listener);
    _firstNewlyAddedEntry ??= entry;
    _listeners.add(entry);
    return () {
       // A listener was added during notification and immediately removed
       if (_firstNewlyAddedEntry == entry) _firstNewlyAddedEntry = entry.next;
       entry.unlink();
    };
  }

  void notifyListener() {
    // Execute all listeners added before notifyListeners
    _firstNewlyAddedEntry = null;

    for (var entry = _listeners.first; entry != _firstNewlyAddedEntry; entry = entry.next) {
      entry.listener();
    }
  }
}
```

**Comment by rrousselGit** [comment]
By the way, this change would fix the:

> Surprising behavior can result when reentrantly removing a listener (i.e. in response to a notification) that has been registered multiple times. See the discussion at removeListener.

as each addition has a unique entry.
It probably doesn't matter, but worth noting.

**Comment by rrousselGit** [comment]
@goderbauer @HansMuller is there any benchmark available about ChangeNotifier/ObserverList?

I'd like to test a way to introduce these changes without making it breaking

**Comment by goderbauer** [comment]
If we have a benchmark for this, it would be located here: https://github.com/flutter/flutter/tree/master/dev/benchmarks

**Comment by fredgrott** [comment]
This change would set Flutter as a more mature front-end framework in being somewhat better performant based on standard cs principles of the diff of List vs LinkedList that most 1st years cs students know! A least the ones that read Knuth's volumes

**Comment by goderbauer** [comment]
Looks like this has been implemented in https://github.com/flutter/flutter/pull/62330.
