### ISSUE TITLE
HostMessages API should allow native code to return error to Dart

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#5962]
https://docs.flutter.io/flutter/services/HostMessages-class.html

We can use the [Futures error handling](https://www.dartlang.org/articles/libraries/futures-and-error-handling) API for this. Throwing a native exception crashes the app (on Android), so it's not a good way of handling errors.

The HostMessages API should complete with an error if you send a message to native code and a handler isn't installed. (Right now on Android it completes with null and on iOS it never completes.)

**Comment by abarth** [comment]
I started on implementing this, but there are a bunch of choices and I'm not sure what's best for you.  If you have time, it would be useful to chat at my desk for a couple minutes to make sure I'm on the right track.

**Comment by abarth** [comment]
Refactoring complete.  Now we're in a good position to do make this happen.

**Comment by abarth** [comment]
When we make this change, we should make non-existent channels return errors to help folks debug when their plugin isn't configured correctly.

**Comment by mit-mit** [comment]
@abarth are you working on this?

**Comment by sethladd** [comment]
No more HostMessages (Hello, PlatformMessages!)... should we close this or rename the issue?

**Comment by abarth** [comment]
Platform messages can do this now.
