### ISSUE TITLE
[package_info]  buildNumber inconsistent on Honor devices 

### ISSUE THREAD

**Issue by liangju126** [flutter/flutter#59636]
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.19041.264], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

I create a new flutter application (demo) and set version: **1.0.0+1** in pubspec.yaml,
and when I run command "flutter run" print _packageInfo.buildNumber, the value was "1".

and when I use this command "flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi".

I copy app-arm64-v8a-release.apk to my mobile phone and open app
print _packageInfo.buildNumber value was "2001".
My mobile phone is Honor 10 Lite Android 10.

My question is How to keep this value consistent ?

**Comment by pedromassangocode** [comment]
Hi @liangju126 
Are you still facing this issue? If yes, could you please provide your `flutter doctor -v`?
Thank you

**Comment by liangju126** [comment]
> Hi @liangju126
> Are you still facing this issue? If yes, could you please provide your `flutter doctor -v`?
> Thank you

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale zh-CN)
    • Flutter version 1.22.6 at D:\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


This problem still exists

**Comment by stuartmorgan** [comment]
Closing as `package_info` is deprecated in favor of [`package_info_plus`](https://pub.dev/packages/package_info_plus).
