### ISSUE TITLE
Upgrade petitparser to version 3.0.0

### ISSUE THREAD

**Issue by Ragnaroek** [flutter/flutter#59648]
## Steps to Reproduce
Otherwise this prevents an upgrade of intl_translation to  version 0.17.10

**Expected results:** 
pub get works with the upgraded intl_translation version set

**Actual results:**
err message printed:
Because every version of flutter_test from sdk depends on petitparser 2.4.0 and intl_translation >=0.17.10 depends on petitparser ^3.0.0, flutter_test from sdk is incompatible with intl_translation >=0.17.10.
So, because nmww depends on both intl_translation ^0.17.10 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because nmww depends on both intl_translation ^0.17.10 and flutter_test any from sdk, version solving failed.)

**Comment by jonahwilliams** [comment]
flutter_test does not depend on petitparser: https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml

What version of flutter are you on?

**Comment by Ragnaroek** [comment]
This happens also on the stable release:

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (13 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by jonahwilliams** [comment]
flutter_test doesn't depend on either petitparser or crypto, can you provide the entire verbose error solve?

**Comment by Ragnaroek** [comment]
Didn't expect that :)
I will try to make a minimal example with a new flutter up and see if it happens there too to make it reproducable.

**Comment by jonahwilliams** [comment]
its possible there is a bug in the pub version solving, or at least the error message, so the logs will help

**Comment by Ragnaroek** [comment]
How can I get more detailed logs? I'm basically running pub get and it only gives me the error message above.

**Comment by jonahwilliams** [comment]
run with `-v`

**Comment by Ragnaroek** [comment]
This is the output of a verbose run:

https://pastebin.com/Tqy2d7qV

**Comment by jonahwilliams** [comment]
Thanks @Ragnaroek , it looks like the dependency is actually coming from `package:test` which is transitive thorugh `e2e/flutter_driver`.

**Comment by jonahwilliams** [comment]
No, I was mistaken - my bad. on the last stable package:test still depended on petitparser - I forgot that this dependency was removed.

**Comment by jonahwilliams** [comment]
So, in a sense it is upgraded because we no longer depend on it or crypto. :)

**Comment by Ragnaroek** [comment]
Don't get it. There was dependency? Did you upgrade it or remove it?

**Comment by TahaTesser** [comment]
@Ragnaroek 
`package:test` still depends  on `petitparser` on stable version, it is removed in later versions.
Since it's no longer in use in test package, we don't need to upgrade it 3..0.0 

given Jonah's message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
