### ISSUE TITLE
flutter -d web-server (or --debug) silently runs in release mode

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#59643]
@jonahwilliams tells me that -d web-server doesn't support debug.

However if you just run `flutter run -d web-server` (which you would expect to be debug mode) or even explicitly with `--debug` it says it's running debug:
[  +85 ms] Launching lib\main.dart on Web Server in debug mode...

But presumably doesn't?

I only learned this because I was compiling a local engine (host_debug_unopt) and trying to use it with -d web and my changes weren't showing up.

**Comment by eseidel** [comment]
I'm not sure this is valid.  I leave this to @jonahwilliams to decide.  Especially with https://github.com/flutter/flutter/issues/59646

**Comment by yjbanov** [comment]
I think we might be overloading the term "debug", which leads to confusion. There are actually two "debug" modes:

- Compile your code for debugging: we use the incremental compiler (a.k.a. DDC, faster compiles, slower output), we enable `assert`s, etc.
- Have a debugger connection established between the `flutter` command and the browser: this allows capturing `print` output and controlling the application/browser lifecycles.

`-d web-server` is a special kind of "device" that gives you _just_ a web server and nothing else. We compile the code in debug mode, but we don't have a connection between the `flutter` command and the browser (in fact, we don't even know what browser you are using, could be a browser on a different computer altogether).

Perhaps when running with `-d web-server` we could print a message that explains this, something like "When running with -d web-server console output is available in the browser's developer tools".
