### ISSUE TITLE
External plugin infrastructure

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#5964]
I've been working on plugins and sample code that use the HostMessages API (Google Sign-In, push messaging, etc.) but they rely on internal build infrastructure.

We should provide a way to build these plugins with the external build system so that they can be released on GitHub.

**Comment by collinjackson** [comment]
Assigning to me for now, but I probably won't get to it for another month so if anyone else wants it, please take.

**Comment by eseidelGoogle** [comment]
FYI @mit-mit.

**Comment by mit-mit** [comment]
@collinjackson I think we can close this now that we have other bugs tracking this use case?

**Comment by collinjackson** [comment]
agreed
