### ISSUE TITLE
flutter run -d web --local-engine silently uses host engine?

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#59646]
I have built my own engine host_debug_unopt and modified it to add a single print statment.

This is trying to run kevmoo/slide_puzzle@a23d035
using a build of flutter/engine@5c87c31 on windows.

```
 .\src\flutter\tools\gn --unoptimized --full-dart-sdk
ninja -C .\out\host_debug_unopt
```

I built with the VSCode 2019 toolchain (in case that matters).

If I try with --debug, or without any tag my print statement does not show up!
```
flutter run -d web --web-port 8080 --local-engine=host_debug_unopt --local-engine-src-path=c:\src\engine\src
```

However if I use --debug or --release it does.  @jonahwilliams

**Comment by jonahwilliams** [comment]
I recall from offline discussion (well online) that this wasn't actually the case. Please reopen If I'm misremembering
