### ISSUE TITLE
Upgrade crypto dependency to 2.1.5

### ISSUE THREAD

**Issue by Ragnaroek** [flutter/flutter#59647]
## Steps to Reproduce

It prevents us from upgrading grpc to version 2.1.4.
Following err message is given on pub get:

Because every version of flutter_test from sdk depends on crypto 2.1.4 and grpc >=2.2.0 depends on crypto ^2.1.5, flutter_test from sdk is incompatible with grpc >=2.2.0.
And because no versions of grpc match >=2.1.4 <2.2.0, flutter_test from sdk is incompatible with grpc >=2.1.4.
So, because nmww depends on both grpc ^2.1.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because nmww depends on both grpc ^2.1.4 and flutter_test any from sdk, version solving failed.)

**Expected results:** 
pub get works with the updated dep version

**Actual results:**
err message printed as shown above

**Comment by jonahwilliams** [comment]
flutter_test does not depend on crypto: https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml

What version of flutter are you on?

**Comment by Ragnaroek** [comment]
We are using the current stable release:
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (13 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Is this then a transitive dependency?

**Comment by iapicca** [comment]
Hi @Ragnaroek 
this [issue](https://github.com/flutter/flutter/issues/59648) is very similar to the current one
and likely to have the same cause

I'm closing this issue for now until the aforementioned isn't resolved
If you disagree, please write in the comments 
possibly providing your `flutter doctor -v` 
and the info requested [here](https://github.com/flutter/flutter/issues/59648#issuecomment-645180795)
and I will reopen it.
Thank you

**Comment by Ragnaroek** [comment]
I want to open that again, to check if this maybe has another cause as https://github.com/flutter/flutter/issues/59648#event-3457300615

verbose output of the error:
https://pastebin.com/Eizh0t9q

**Comment by iapicca** [comment]
Hi @Ragnaroek 
as @jonahwilliams mentioned [above](https://github.com/flutter/flutter/issues/59647#issuecomment-645170627) `flutter_test does not depend on crypto` 
there isn't much to be done on flutter side to solve the issue that might depend from your project.

You might want to follow the [docs](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted) for a possible corrupted installation, 
running  `flutter pub cache repair`
and making sure that your packages and plugins are up to date.

Closing, as this isn't an issue with Flutter itself. 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Ragnaroek** [comment]
Did run `flutter pub cache repair`, still says:

Because every version of flutter_test from sdk depends on crypto 2.1.4 and grpc >=2.2.0 depends on crypto ^2.1.5, flutter_test from sdk is incompatible with grpc >=2.2.0.
And because no versions of grpc match >=2.1.4 <2.2.0, flutter_test from sdk is incompatible with grpc >=2.1.4.
So, because nmww depends on both grpc ^2.1.4 and flutter_test any from sdk, version solving failed.

It explicitly says flutter_test in the error. So I think this is still flutter related (in some way)

**Comment by iapicca** [comment]
Hi @Ragnaroek 
did these [steps](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted) worked for you?
Thank you

**Comment by dumazy** [comment]
I'm having the same issue. Flutter 1.17.4 stable.
The steps mentioned above here did not solve this issue for me.

**Comment by Ragnaroek** [comment]
neither for me

**Comment by Ragnaroek** [comment]
For me also the flutter pub cache repair did not make a difference. Still the same error.

**Comment by jonahwilliams** [comment]
Like I mentioned previously, flutter no longer depends on package:crypto. For the current stable version you have to use the version of crypto in the constraints, or otherwise use a [dependency_override](https://dart.dev/tools/pub/dependencies#dependency-overrides) to specify the version you want
