### ISSUE TITLE
Notify No Internet Connectivity Flutter Web

### ISSUE THREAD

**Issue by imcoffeefreak** [flutter/flutter#59640]

**Comment by iapicca** [comment]
Hi @imcoffeefreak 
I'm not sure how the PWA 
could load itself (through internet) 
an notify (through internet) 
the lack internet connectivity?

Maybe I'm missing something, 
could you please provide more details to the issue?
Thank you

**Comment by imcoffeefreak** [comment]
@iapicca 
Yes, notification when there is no internet.
Couple of database sends the data, in flutter app we do have connectivity package. 
But what is the solution for flutter_web then?

**Comment by iapicca** [comment]
Given this [message](https://github.com/flutter/flutter/issues/46735#issuecomment-611773243)
Closing the issue
If you disagree, please write in the comments and I will reopen it.
Thank you

https://pub.dev/packages/experimental_connectivity_web
