### ISSUE TITLE
[video_player] not parsing urls correctly 

### ISSUE THREAD

**Issue by DeadlyMissile** [flutter/flutter#59653]
I have a url like so https%3A%2F%2F....

Using the video player plugin, this becomes https:/... missing one slash, which results to FileNotFoundException

**Comment by iapicca** [comment]
Hi @DeadlyMissile 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
