### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4138 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

### ISSUE THREAD

**Issue by Manoj1611** [flutter/flutter#59676]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @Manoj1611 
is your case different from https://github.com/flutter/flutter/issues?q=is%3Aissue+%27_debugLifecycleState+%21%3D+_ElementLifecycle.defunct%27%3A+is+not+true+?
if yes - please fill out the issue template and I'll reopen
