### ISSUE TITLE
Error -32000 received from application: Service protocol could not handle or find a handler for the requested method.

### ISSUE THREAD

**Issue by furkanvijapura** [flutter/flutter#59674]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

When i put hotereload, at that time throw this message ->
```
Error -32000 received from application: Service protocol could not handle or find a handler for the requested method.
Restarted application in 9,556ms.
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @furkanvijapura 
could you provide you `flutter doctor -v` and attach complete log here?
may be fixed by https://github.com/flutter/flutter/pull/53960

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by furkanvijapura** [comment]
flutter doctor -v
bash: flutter: command not found

**Comment by iapicca** [comment]
Hi @furkanvijapura 
please make sure you added flutter to your path following the [docs](https://flutter.dev/docs/get-started/install/windows#update-your-path) 

For the issue to be reproducible please provide
your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you
