### ISSUE TITLE
Plugin doesn't work on iOS 13.5.1

### ISSUE THREAD

**Issue by Umeshnig** [flutter/flutter#59682]
The plugin https://pub.dev/packages/share is working fine on Android and iOS 12.X versions however its not working with 13.4 and above. More importantly it doesn't work with 13.5.1 due to which appstore has rejected our latest build from being published.

**Comment by bierbaumtim** [comment]
What’s exactly does not work ?
I use the plugin in production app and sharing a simple link works perfectly on iOS 13.5.1.

**Comment by Neoxsam** [comment]
I just found a fix here that might help you @Umeshnig 

https://github.com/flutter/flutter/issues/44962#issuecomment-554932650

**Comment by VladyslavBondarenko** [comment]
Hi @Umeshnig 
are you using the last version `share: ^0.6.4+3`?
could you provide your `flutter doctor -v` and explain in details what does not work? attach logs, minimal code sample/project if related

**Comment by VladyslavBondarenko** [comment]
@Umeshnig 
Closing as additional information isn't provided
