### ISSUE TITLE
when I run my flutter web project in crome it gives me the below error. After debugging 2-3 times it resolves but when I restart vs code then I get that error again.

### ISSUE THREAD

**Issue by gauravsmishra** [flutter/flutter#59684]
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

**Comment by VladyslavBondarenko** [comment]
Hi @gauravsmishra 
follow up on https://github.com/flutter/flutter/issues/49482,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
