### ISSUE TITLE
How to add to the following list

### ISSUE THREAD

**Issue by niteesh1215** [flutter/flutter#59696]
_documentList.document = streamSnapshot.data.documents.toList();

Im fetching the documents from the firestore. How do i add a new element to the above list ?

I tried adding, however i'm getting the following error

**Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'DocumentSnapshot' of 'element'**

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
