### ISSUE TITLE
Factor out InkSplash and InkHighlight into their own file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5969]
...so that it's clear that this is an extensible API. Right now it's not clear that they are playing by the same rules as other extensions would have to.

**Comment by abarth** [comment]
I'm not sure what you have in mind here.  `Material` knows about `MaterialInkController`, which knows about `InkSplash` and `InkHighlight` and serves as a factory for `_InkSplash` and `_InkHighlight`.

Removing the "easy fix" label because the fix is not obvious (at least to me).

**Comment by Hixie** [comment]
It should be possible to implement other classes that print on Material, like InkSplash and InkHighlight.

MaterialController only knows about InkSplash and InkHighlight because that's where the factories are, but maybe we should move the factories to InkSplash and InkHighlight since other kinds of ink classes couldn't have their factories on MaterialController.
