### ISSUE TITLE
Hot Restart from Google's source code/build environment crashes component on <elided configuration & hardware>

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59699]
https://buganizer.corp.google.com/issues/159167220.

**Comment by jmagman** [comment]
> engine.cc(436)] Could not configure some native embedder bindings for a new root isolate.

**Comment by jonahwilliams** [comment]
Comment on the issue: fuchsia devices do not support hot restart. This is disabled in the flutter_tool, and would likely need to be disabled in google3 as well.
