### ISSUE TITLE
Provide a Link widget that works well on the web

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#59690]
Two design documents:

- https://flutter.dev/go/link-widget
- https://flutter.dev/go/link-widget-2

Three draft PRs showcasing the various approaches for implementing this:

- https://github.com/flutter/flutter/pull/57165
- https://github.com/flutter/engine/pull/18357
- https://github.com/flutter/plugins/pull/2813

**Comment by sahandevs** [comment]
No mentions about :visited state in css.

According to the https://developer.mozilla.org/en-US/docs/Web/CSS/:visited

It's impossible to detect if user visited the link via js because of user privacy.

@mdebbar any workarounds you have in mind?
