### ISSUE TITLE
[flutter_tools] `flutter upgrade` should validate upstream remote & warn if not `flutter/flutter`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#59697]
`flutter upgrade` will update the local git HEAD to whatever the HEAD is of the branch's configured upstream. If the upstream points to a fork, it will upgrade the repo to the HEAD of that fork. This is likely not what the user wants. We should check first if the configured upstream is `github.com/flutter/flutter`, and:

1. If `--force` is supplied, upgrade anyway
2. Else exit with a warning (and instructions to fix).

**Comment by jonahwilliams** [comment]
I would say warn normally, and maybe attempt it anyway if `-f` is passed?

**Comment by flar** [comment]
Also, perhaps not emit the big `Flutter upgrade is available` banner when in the constributor workflow as well. It's basically meaningless and means "you might want to fetch remote and rebase" rather than run `flutter upgrade`.

**Comment by flar** [comment]
The same comment would also apply to running `flutter upgrade` in a contributor workflow. It should mention that the proper way to track things in that instance is to fetch from upstream and rebase.

**Comment by christopherfujino** [comment]
> Also, perhaps not emit the big `Flutter upgrade is available` banner when in the constributor workflow as well. It's basically meaningless and means "you might want to fetch upstream and rebase" rather than run `flutter upgrade`.

I'd argue the banner probably isn't that helpful unless you're on a release branch.

**Comment by jmagman** [comment]
@christopherfujino can we forward duplicate to https://github.com/flutter/flutter/issues/78591?

**Comment by christopherfujino** [comment]
Yep, closing in favor of https://github.com/flutter/flutter/issues/78591
