### ISSUE TITLE
Hot Reload from Google3 causes redscreen on <elided configuration and hardware>

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59703]
https://b.corp.google.com/issues/159165121. Note that this and https://github.com/flutter/flutter/issues/59699 are unrelated, despite the similarities in subject.

**Comment by kf6gpe** [comment]
cc @iskakaushik

**Comment by kf6gpe** [comment]
Looks like memory is spiking in the indicated use case; Kaushik is working on bisecting a range of commits.

**Comment by kf6gpe** [comment]
Downgrading to `P2` while we attempt to reproduce this.

**Comment by chinmaygarde** [comment]
Triage: This is going to be fixed by a Dart roll.

**Comment by chinmaygarde** [comment]
Triage: @kf6gpe is seeking an update on whether the Dart roll fixed this.

**Comment by iskakaushik** [comment]
Dart roll containing https://github.com/dart-lang/sdk/commit/1a8190db493f8d09510a60568cc23bd1d04446c0 will help further the investigation and likely even fix this issue. David Murphy is leading the investigation on this. Let's wait for his test results.

**Comment by kf6gpe** [comment]
@iskakaushik Do you know the latest on this? (Checking in for critical issue triage). Thanks!

**Comment by iskakaushik** [comment]
David Murhpy @ Google is working on this. He mentioned that he has it working as of today. There were a couple of hoops to jump through to get it to work, but hot reload is now working for him. Given that there is a workaround, I propose that we continue to use this issue to figure out how we can make the experience better. David mentioned that there are potentially some areas of improvement in the tool. I've asked david to post more details here when he gets a chance.

Given this, I'm reducing the priority to a P3.

**Comment by chinmaygarde** [comment]
cc @dabhaid

**Comment by kf6gpe** [comment]
Update: Hot reload to emulator working. Not necessarily the elided configuration.

**Comment by dabhaid** [comment]
This particular issue was a result of a target mismatch: the target platform was being misidentified as linux, consequently the incremental build being pushed was for the wrong target. Coercing the platform fixes the issue on both emulator and elided configuration. The fix is mentioned in https://b.corp.google.com/issues/159165121, that bug is still open as the fix depends on a magic environment variable.
