### ISSUE TITLE
IOS Home screen app-icon has a black background when opening and closing a flutter app.

### ISSUE THREAD

**Issue by adeolaex** [flutter/flutter#59712]
I noticed that any flutter project whether new or old, has a black underlay whenever the app is launched or minimised on IOS. Haven't tested this out on android yet. I might be wrong and just seeing things because I do have pixel paranoia. :-)

I attached a slow mode representation of the issue.
![RPReplay_Final1592423228](https://user-images.githubusercontent.com/42682873/84952483-530a9c80-b0f2-11ea-96f4-8642d26e679b.gif)

## Steps to Reproduce

1. Run 'flutter create _project-name_' , using the stable version of Flutter as of the time of filing this issue.

2. Run  "flutter run -d _<device id>_" where the _device id_ is the id of a potential iOS simulator or a real iOS device. An example **flutter run -d 583ehbefbeiubfue434**

3. Navigate to the home screen and attempt to open the app. 

4. Repeat step 3 to notice it easily.

**Comment by VladyslavBondarenko** [comment]
Hi @adeolaex 
please follow up on https://github.com/flutter/flutter/issues/53154,
I'm closing the current one as duplicate

**Comment by adeolaex** [comment]
Hello @VladyslavBondarenko . Thank you very much for that info.
