### ISSUE TITLE
Flutter Web Hot Refresh Broken - :59527/dart_sdk.js:133084 Uncaught (in promise) TypeError: Cannot read property 'ensureFontsLoaded' of null

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#59718]
## Steps to Reproduce

`flutter upgrade` on master channel
run the default project
make a change and notice the page will entirely stall and you must manually refresh to see the change

I noticed this started happening after an upgrade 2-3 days ago.

```
:59527/dart_sdk.js:133084 Uncaught (in promise) TypeError: Cannot read property 'ensureFontsLoaded' of null
    at _initializePlatform (:59527/dart_sdk.js:133084)
    at _initializePlatform.next (<anonymous>)
    at :59527/dart_sdk.js:37106
    at _RootZone.runUnary (:59527/dart_sdk.js:36960)
    at _FutureListener.thenAwait.handleValue (:59527/dart_sdk.js:32047)
    at handleValueCallback (:59527/dart_sdk.js:32594)
    at Function._propagateToListeners (:59527/dart_sdk.js:32632)
    at _Future.new.[_completeWithValue] (:59527/dart_sdk.js:32475)
    at async._AsyncCallbackEntry.new.callback (:59527/dart_sdk.js:32497)
    at Object._microtaskLoop (:59527/dart_sdk.js:37221)
    at _startMicrotaskLoop (:59527/dart_sdk.js:37227)
    at :59527/dart_sdk.js:32849
```

```
[√] Flutter (Channel master, 1.20.0-1.0.pre.90, on Microsoft Windows [Version 10.0.17758.4], locale en-US)
    • Flutter version 1.20.0-1.0.pre.90 at C:\src\flutter
    • Framework revision 42e02d60d3 (5 hours ago), 2020-06-17 10:57:40 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Miche\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Miche\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

```

</details>

**Comment by guidezpl** [comment]
Reproed, @yjbanov I think this might have been https://github.com/flutter/engine/pull/19027

**Comment by VladyslavBondarenko** [comment]
Confirming that this doesn't happen with current dev `1.20.0-0.0.pre`

**Comment by kf6gpe** [comment]
Downgrading to `P1`, just because Flutter for Web is still in beta, but I'm working with the web team to get this fixed ASAP.

**Comment by jonahwilliams** [comment]
we can't release with this bug, bumping back to P0

**Comment by jonahwilliams** [comment]
@yjbanov

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/flutter/flutter/commit/bf9452064437a17c679fd294d94c4368cd36c2a5 (which upgraded various packages)

Not sure which package is causing this issue.

**Comment by jonahwilliams** [comment]
The likely candidates are `dwds` and `webkit_inspection_protocol`. fyi @grouma

**Comment by grouma** [comment]
I'll take a look shortly.

**Comment by jonahwilliams** [comment]
I can't repro at c550d04814fafd76852e0146573f4e0947d14a1e , so it might have been the engine roll actually

**Comment by jonahwilliams** [comment]
Oh wait, I need to actually change something 🤦

**Comment by jonahwilliams** [comment]
hitting a runtime error in the console:

initialization.dart
```
  // This needs to be after `webOnlyInitializeEngine` because that is where the
  // canvaskit script is added to the page.
  if (engine.experimentalUseSkia) {
    await engine.initializeSkia();
  }

  assetManager ??= const engine.AssetManager();
  await webOnlySetAssetManager(assetManager);
  if (engine.experimentalUseSkia) {
    await engine.skiaFontCollection.ensureFontsLoaded();
  } else {
    await _fontCollection.ensureFontsLoaded();
  }

  _webOnlyIsInitialized = true;
}
```

looks like _fontCollection is null here

**Comment by grouma** [comment]
This is the PR that broke it: https://github.com/dart-lang/webdev/pull/997/

Looks like there is a race condition on the Flutter Web side. Here is a PR that "fixes" the issue:
https://github.com/dart-lang/webdev/pull/1058

**Comment by vsmenon** [comment]
I'm hitting this now on an app.  It appears that, on a hot restart, `main` is invoked *before* the callback into the DDC runtime ([`hotRestart`](https://github.com/dart-lang/sdk/blob/d44457f79d087b52a0468609d44013e5fd9f09f0/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/runtime.dart#L197)) that clears fields.  

Did something change the order?

**Comment by grouma** [comment]
Just need to pull in the latest package:dwds and hot reloads should be fixed.

**Comment by jonahwilliams** [comment]
Currently blocked on landing this by a change in behavior in shelf server, and a change in stack trace formatting. 

https://github.com/flutter/flutter/pull/59832

Going to try pinning old shelf for now

**Comment by MichealReed** [comment]
Confirmed fixed. Thanks to all for the efforts here.
