### ISSUE TITLE
iOS crash on startup not caught by engine integration tests

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#59716]
An [upstream change](https://skia-review.googlesource.com/c/skia/+/295437) in Skia caused the empty font manager to be selected in the iOS embedder. This wasn't caught by:
* Skia tests ([issue](https://bugs.chromium.org/p/skia/issues/detail?id=10400))
* Engine tests (this issue)
* Framework presubmit (intentionally skipped due to current lack of infra)
and was only caught in devicelab tests after the engine rolled to the framework.

We should ensure we've got a test that catches crash/abort() on startup issues.

**Comment by jmagman** [comment]
I think our scenario tests would now catch this.
