### ISSUE TITLE
Swiping around on <elided applications> causes device to reboot

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59710]
https://b.corp.google.com/issues/158681375.

/cc @iskakaushik, who's helping investigate this.

**Comment by chinmaygarde** [comment]
Seeking clarification on the internal issue about ownership.

**Comment by kf6gpe** [comment]
Fuchsia team waiting for a couple of their CLs to roll through to see if that addresses the problem.

**Comment by kf6gpe** [comment]
Commented on the upstream issue --- it's not clear that this has an owner on the Fuchsia team yet; I pinged for status.

**Comment by kf6gpe** [comment]
Upstream issue suggests that this may not be as reproducible; more investigation by Fuchsia team needed. No action required on our part. Downgrading to a P3 until we know more.

**Comment by chinmaygarde** [comment]
This looks like an upstream issue.
