### ISSUE TITLE
Cocoapods 1.9.1, iOS app shows futter default logo

### ISSUE THREAD

**Issue by XinleZhou2018** [flutter/flutter#59725]
I am using Cocoapods v1.9.1, When  I run the iOS app. Sometimes The iOS app shows the Flutter default logo, Sometimes shows the icon what I set to this app.

**Comment by TahaTesser** [comment]
Hi @XinleZhou2018 
Please try with latest pod `1.9.3`
if the problem persist, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by VladyslavBondarenko** [comment]
@XinleZhou2018 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code/project, logs and the output of `flutter doctor -v` please
