### ISSUE TITLE
[Linux][GTK] Warning message after key press event

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#59724]
The warning message will be displayed if you press a key while the `TextField` widget is not in focus. No warning is displayed on macOS.

The cause is that Flutter Engine sends a message to `flutter/textInput` system channel every time a key event occurs. On the other hand, TextInput on Dart side does not open the channel unless the TextField has the focus.

```
** (testbed:61250): WARNING **: 17:05:22.197: Failed to call TextInputClient.updateEditingState: Requested method is not implemented
```

## Steps to Reproduce

1. Run a Flutter app (in debug mode)
2. Press a key

<details>
  <summary>Flutter SDK version</summary>

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.81, on Linux, locale ja_JP.UTF-8)
    • Flutter version 1.20.0-1.0.pre.81 at /opt/flutter
    • Framework revision e0ed12c73a (24 hours ago), 2020-06-16 16:53:04 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

</details>

Congratulations on switching to GTK!

**Comment by stuartmorgan** [comment]
@robert-ancell I assume this is what https://github.com/flutter/engine/pull/18990 fixed?

**Comment by robert-ancell** [comment]
> @robert-ancell I assume this is what [flutter/engine#18990](https://github.com/flutter/engine/pull/18990) fixed?

Yes, it should have.

**Comment by stuartmorgan** [comment]
Closing as fixed then.

@HidenoriMatsubayashi If you still see this after the engine has rolled past that commit, please comment and I can re-open.
