### ISSUE TITLE
MacOS bots to have more versions of IOS Simulator

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#59727]
The MacOS bots (I tested on prod bots) have 13.0 version of IOS Simulator: https://logs.chromium.org/logs/flutter/led/nurhan_google.com/d1a922bd71d6d3712741732fbf0851e36c64c9af17d4df2307538287047d6401/+/steps/simctl/0/stdout

We are planning to use these simulators for integration tests and unit tests.

In local machines we can add more IOS simulators by: Xcode > Preferences > Components and installing more components. How can we add more versions on LUCI bots?

**Comment by godofredoc** [comment]
I'd suggest to ask in the luci-users chat. I found the following but it doesn't talk about the simulators:

https://chromium.googlesource.com/infra/infra/+/refs/heads/master/go/src/infra/cmd/mac_toolchain/README.md

**Comment by godofredoc** [comment]
This is already solved and documented in go/flutter-infra-xcode
