### ISSUE TITLE
PluginRegistry.*Listener documentation clarification or automatic registration

### ISSUE THREAD

**Issue by ajunkala** [flutter/flutter#59729]
I am working on an in-house plugin. It implements both ActivityAware and PluginRegistry.NewIntentListener. When the activity attaches, ActivityAware is automatically added as a listener (io.flutter.embedding.engine.FlutterEnginePluginRegistry:add()). However PluginRegistry.NewIntentListener does not trigger the same automatic listening and there is no documentation to suggest it is necessary to explicitly add it as a listener.

My assumption is the PluginRegistry listeners are interfaces for the plugin and should be registered, but I can see the intention of it being a separate/anonymous class so possibly the documentation needs clarification on how to use these listeners. I also relied on a plugin using the old registration system as a guide since there was no documentation on how to use.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.900], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by darshankawar** [comment]
@ajunkala 
Can you confirm if this issue still exists on latest stable version (1.22.6) ? If so, can you provide a minimal reproducible code sample that shows the issue you described and where exactly the documentation lacks ?
Thanks

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
