### ISSUE TITLE
Can anyone please explain the return statement in this code??

### ISSUE THREAD

**Issue by Agrim1210** [flutter/flutter#59731]
import 'package:flutter/foundation.dart';
import 'package:GreatPlace/models/place.dart';

class GreatPlaces with ChangeNotifier{

List<Place> _items=[];
List<Place> get item{
  return[..._items];
}
}

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
