### ISSUE TITLE
iOS back gesture causes corruption and crash.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5973]
On iOS Gallery, do the following:

1. Go into slow animation mode.
2. Select any demo.
3. As the animation is about half-way through, try to do a back gesture. You'll notice how the who demo glitches.
4. After the demo disappears, select a demo again. This time, the demo will load from the right.
5. Dismiss it with a back gesture.
6. Select a demo and notice the crash.

Trace:

```
I/flutter : The following assertion was thrown during a scheduler callback:
I/flutter : 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 578 pos 12: '_from.subtreeContext
I/flutter : != null' is not true.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:578:12)
I/flutter : #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:608:15)
I/flutter : #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:551:9)
I/flutter : #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:48)
I/flutter : (elided 2 frames from class _AssertionError)
```

**Comment by dragostis** [comment]
@Hixie The crash only happens when you do a second back gesture. Everything seems to be fine if you use back button after the first back gesture.

**Comment by mpcomplete** [comment]
Got a fix, writing a test.
