### ISSUE TITLE
MacOS and Windows LUCI bots to have git command

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#59739]
One dependency for us to run the integration tests on the engine is to use this script to clone the correct version of flutter to the engine: https://github.com/flutter/engine/blob/master/tools/clone_flutter.sh

This script uses git commands to get the youngest framework PR older than the engine PR.

I tested git command on MacOS bots and its not installed: https://chromium-swarm.appspot.com/task?id=4c529de56c00b110 LOGS: https://logs.chromium.org/logs/flutter/led/nurhan_google.com/64b575ef3bf20ef267efa945501622b3beec4a030fc888a673b8171472294b9e/+/steps/felt_test_chrome/0/stdout

**Comment by godofredoc** [comment]
Any reason why we are not cloning at the recipe level? recipes are already cloning the repositories using git on mac machines.

**Comment by nturgut** [comment]
This script is trying to get the youngest framework PR older than the engine PR using the following code pieces:

```
# Get latest commit's time for the engine repo.
# Use date based on local time otherwise timezones might get mixed.
LATEST_COMMIT_TIME_ENGINE=`git log -1 --date=local --format="%cd"`
echo "Latest commit time on engine found as $LATEST_COMMIT_TIME_ENGINE"
```

```
# Clone the Flutter Framework.
git clone https://github.com/flutter/flutter.git
cd flutter

FRAMEWORK_BRANCH_NAME=`git branch | grep '*' | cut -d ' ' -f2`
```

Can I run the commands like `git log` or `git branch` on recipe level?

**Comment by godofredoc** [comment]
Yes you can the api has an execute method that passes all the parameters to the git binary in case the command does not have a method mapping.

**Comment by godofredoc** [comment]
Obsolete
