### ISSUE TITLE
Flutter web release mode white/blank screen issue

### ISSUE THREAD

**Issue by aditya305** [flutter/flutter#59744]
[√] Flutter: is fully installed. (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.3)
[√] Chrome - develop for the web: is fully installed.
[√] Android Studio: is fully installed. (version 4.0)
[√] VS Code: is fully installed. (version 1.46.0)
[√] Connected device: is fully installed. (2 available)

**Comment by VladyslavBondarenko** [comment]
Hi @aditya305 
could you provide logs when running your app with `--verbose`? 
can you see errors in browser console?
could you provide a minimal complete reproducible code sample?
