### ISSUE TITLE
Flutter mailer 3.0.4 recipient not receiving email

### ISSUE THREAD

**Issue by puggie03** [flutter/flutter#59746]
Hi,
I have implemented the below code and it was working fine, I could send an email and the recipient would receive it but now when I test the very same code, the recipient is not receiving the email but the email is sent successfully. Please somebody point me to what could be wrong.

emailSetup(String _name, String _phonenumber) async {
    String username = "xxxx@xxxx.com";
    String password = "xxxxxx";

    FirebaseUser user = await firebaseAuth.currentUser();
    final smtpServer = gmail(username, password);
    // Creating the Gmail server

    // Create our email message.
    final message = Message()
      ..from = Address(username)
      ..recipients.add(user.email) //recipent email (**this email is not receiving the email**)
      ..bccRecipients.add(Address(username)) //bcc Recipents emails 
      ..subject = 'Order ${DateTime.now()}' //subject of the email
      ..text = emailBody(_name, _phonenumber, user.email);

    try {
      final sendReport = await send(message, smtpServer);

      print('Message sent: ' + sendReport.toString());
      showDialog(
          context: context,
          builder: (BuildContext context) {
            return new AlertDialog(
              title: new Text("Success"),
              content: new Text("Your order has been placed"),
              actions: <Widget>[
                new MaterialButton(
                  onPressed: () {
                    Navigator.of(context).push(PageRouteBuilder(
                        opaque: false,
                        pageBuilder: (BuildContext context, _, __) =>
                            MainScreen()));
                  },
                  child: new Text("close"),
                )
              ],
            );
          });
      items.clear();
      orderPage.resetCartTotal();
      //print if the email is sent
    } on MailerException catch (e) {
      print('Message not sent. \n' +
          e.toString()); //print if the email is not sent
      showDialog(
          context: context,
          builder: (BuildContext context) {
            return new AlertDialog(
              title: new Text("Failed"),
              content: new Text("Please try again shortly"),
              actions: <Widget>[
                new MaterialButton(
                  onPressed: () {
                    Navigator.of(context).pop(context);
                  },
                  child: new Text("close"),
                )
              ],
            );
          });
    }
  }

**Comment by puggie03** [comment]
I just found the emails in the spam folder, any reason why they are suddenly going to spam?

**Comment by VladyslavBondarenko** [comment]
Hi @puggie03 
consider to open an issue in the plugin's repository https://github.com/kaisellgren/mailer/issues,
closing since this is not an issue with flutter itself,
If you disagree please write in the comments and I will reopen it

**Comment by cryogeni** [comment]
Hi @puggie03 

How did you manage to put a dialog alert right after print message send:?

I try to do the same to let the user know that it is working.
