### ISSUE TITLE
Flutter Widget test cannot emulate different screen size properly

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#59755]
## Steps to Reproduce

Before deploying my Flutter app, I wanted to test it on multiple screen sizes to check if there is any `Renderflex overflow` for smaller screens.

But I when first modified the screen size during widget testing to match the device I was using during the development, I realized that the widget test is throwing `Render overflow` errors already, even though it did not have such errors on the real device. So I asked this questions https://stackoverflow.com/questions/62444634/how-to-fix-a-renderflex-overflowed-by-72-pixels-on-the-right-in-flutter 

But I after further investigation and using Flutter golden feature test which snaps png out of widget tests, I narrowed down the problem to a discrepancy in **text size**. 

You can see clearly in the reproducible step below that the text during the widget text is **WAY BIGGER** (on the right) than the actual text in the real device (on the left).

The bigger text size during Widget test causes the `RenderFlex error` in my app.

#Steps to reproduce:

1. Now connect a real device and run this code with `flutter run`

`lib/main.dart`

    import 'package:flutter/material.dart';
    
    void main() {
      runApp(
        MaterialApp(
          home: TextScaleComparaison(),
        ),
      );
    }
    
    class TextScaleComparaison extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        final widget = Scaffold(
          body: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              final width = MediaQuery.of(context).size.width;
              final height = MediaQuery.of(context).size.height;
              final dpr = MediaQuery.of(context).devicePixelRatio;
              final textScale = MediaQuery.of(context).textScaleFactor;
              final vi = MediaQuery.of(context).viewInsets;
              final vip = MediaQuery.of(context).viewPadding;
              final font = DefaultTextStyle.of(context).style.fontFamily;
              print("width is $width and height is $height and dpi is $dpr txtScale is $textScale vi is $vi vip is $vip font is $font");
              return Center(child: Text("This cannot be that long!!"));
            },
          ),
        );
        return widget;
      }
    }

2. Check the logs and you should see device screen info:

For me I got :

`I/flutter (27450): width is 411.42857142857144 and height is 797.7142857142857 and dpi is 2.625 txtScale is 1.1 vi is EdgeInsets.zero vip is EdgeInsets(0.0, 24.0, 0.0, 0.0) font is Roboto`

Copy the screen `width` and `height` to and `textScale` and `devicePixelRatio` to the next step in the code below.

3. Edit the code below to add the above setting because we want to simulate this exact screensize in the test.  

`test/test.dart`

    import 'package:flutter/material.dart';
    import 'package:flutter_test/flutter_test.dart';
    import 'package:my_app/main.dart';
    void main() {
    
      testWidgets(
        "Emulate real screen size",
        (WidgetTester tester) async {
          // Adjust these to match your actual device screen specs
          final width = 414;
          final height = 846;
          tester.binding.window.devicePixelRatioTestValue = (2.625);
          tester.binding.window.textScaleFactorTestValue = (1.1);
          final dpi = tester.binding.window.devicePixelRatio;
          tester.binding.window.physicalSizeTestValue = Size(width * dpi, height * dpi);
          await tester.pumpWidget(
            MediaQuery(
              data: MediaQueryData(),
              child: MaterialApp(
                home: TextScaleComparaison(),
              ),
            ),
          );
          await expectLater(
            find.byType(TextScaleComparaison),
            matchesGoldenFile("text.png"),
          );
        },
      );
    }

Run `test.dart` with `flutter test --update-goldens test/test.dart`

This will create a png file at `test/text.png` 

Check the logs: For me it printed: 

`width is 414.0 and height is 846.0 and dpi is 2.625 txtScale is 1.1 vi is EdgeInsets.zero vip is EdgeInsets.zero font is Roboto`
 

# What I am missing ? Why can't the text show exactly the same as the real device?

**Expected results:** 

**Actual results:** 
 The text size should show exactly the same as the real device.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/OpEgJ.png

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @tolotrasamuel 
Thanks for very well explained issue, i can reproduce the issue

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (9 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.106

• No issues found!
``` 

</details>

**Comment by tolotrasamuel** [comment]
Solved https://stackoverflow.com/a/62460566/6727914
