### ISSUE TITLE
How to add iOS Custom Keyboard Extensions to Flutter

### ISSUE THREAD

**Issue by jimmyrogue** [flutter/flutter#59753]
I try to build an app with flutter and want add iOS extension custom keyboard into project
but I can't build success 
```
ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I dont know why ....... or any guide?

**Comment by TahaTesser** [comment]
Couldn't find any documentation for this and looks like something really nice to have in Flutter https://www.raywenderlich.com/49-custom-keyboard-extensions-getting-started

**Comment by jmagman** [comment]
This is probably fixed by https://github.com/flutter/flutter/pull/54691, @TahaTesser can you re-triage and get doctor, etc?

**Comment by jimmyrogue** [comment]
@TahaTesser thanks, about the error I solved by move flutter.framework and App.framework from another flutter example  /Flutter folder

**Comment by Adatype** [comment]
Hi @jimmyrogue, did you manage to run Flutter (including its UI) in iOS Keyboard Extension?

**Comment by jimmyrogue** [comment]
@Adatype  no I build keyboard with native code (swift) at last
