### ISSUE TITLE
[web]: <Website runs prefectly fine in debug mode but shows blank screen in release mode>

### ISSUE THREAD

**Issue by elaishane** [flutter/flutter#59752]
Describe your issue and include the command you're running, flutter_web version, browser version

My web app runs perfectly fine in debug mode but it shows blank screen in release mode.

command: flutter run -d chrome [Works fine]
command: flutter run -d chrome --release[shows blank screen]

**Comment by TahaTesser** [comment]
Hi @elaishane 
Can you please provide your `flutter doctor -v`, your `flutter run --release --verbose`, your `pubspec.yaml` and a minimal reproducible code sample.
Thank you
