### ISSUE TITLE
flutter build -d windows --no-sound-null-safety

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#59769]
I am trying to preview & adopt NNBD feature in my cross platform application.

I found that the command `flutter build -d windows --no-sound-null-safety` fails with 

![image](https://user-images.githubusercontent.com/18419515/85043098-a9c8b280-b194-11ea-973e-d708bbe48250.png)

But the command `flutter run -d windows --no-sound-null-safety` works fine.

Is it expected behavior?

**Comment by jonahwilliams** [comment]
Oversight on my part, should have it fixed shortly. Sorry for the trouble!

**Comment by roman-petrov** [comment]
@jonahwilliams , thank you!
