### ISSUE TITLE
Android dependency 'com.google.android.gms:play-services-tasks' has different version for the compile (17.0.0) and runtime (17.0.2) classpath.

### ISSUE THREAD

**Issue by jaiaswani10** [flutter/flutter#59768]
## Steps to Reproduce

I am facing issue while running flutter run.

**Expected results:**  app should run

**Actual results:** FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:preDebugBuild'.
[   +1 ms] > Android dependency 'com.google.android.gms:play-services-tasks' has different version for the compile (17.0.0) and runtime (17.0.2) classpath. Youshould manually set the same version via DependencyResolution

android/build.gradle
*********************************************************************************************************
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0'
        // classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.50'
    }

    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "27.1.1"
                }
                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }         
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
*********************************************************************************************************
android/app/build.gradle
*********************************************************************************************************
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
} else {
    throw new GradleException("key.properties file not found.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.xxx"
        minSdkVersion 20
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
   }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
             signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.android.gms:play-services-basement:17.0.2'
    implementation 'com.google.firebase:firebase-core:17.0.0'

}

√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.17763.1282], locale en-IN)
    • Flutter version 1.17.3 at E:\flutter\flutter-1.17.3
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\Softwares\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = F:\Softwares\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_201\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\ibirds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • POCO F1 • bf1fd699 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
HI @jaiaswani10 
Please upgrade to [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration) and make sure you at least `classpath 'com.android.tools.build:gradle:3.5.0'`  Check https://github.com/flutter/flutter/issues/39135#issuecomment-526161556 and try again then

Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by kevinkobori** [comment]
> HI @jaiaswani10
> Please upgrade to [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration) and make sure you at least `classpath 'com.android.tools.build:gradle:3.5.0'` Check [#39135 (comment)](https://github.com/flutter/flutter/issues/39135#issuecomment-526161556) and try again then
> 
> Thank you

WORKS FOR ME!
