### ISSUE TITLE
Flutter Engin Crash  On OnPlatformViewCreated

### ISSUE THREAD

**Issue by zhaojiewen** [flutter/flutter#59764]
## Steps to Reproduce
When Flutter Page jump to native page many times!  I got this error:

-----------------------------------------------
Flutter`auto fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>::operator()<>() const:

---------------------------------

**Expected results:** 
 show native page normal

**Actual results:**

crash

<details>
when other App jump to my App many time and  my app contain native page and flutter page ,
every time my app should show native page over flutter page, however ,when reducing this operation many times , it would crash

flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/xuhaiqing/Flutter_SDK/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xuhaiqing/Downloads/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xuhaiqing/Downloads/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • 币乎 iPhone 6sP • 42a6f0a714103d4d52d545d5996b0be60aa56728 • ios • iOS 13.3

• No issues found!

nalyzing DiagnosticReports...                                          
No issues found! (ran in 0.8s)

**Comment by TahaTesser** [comment]
Hi @zhaojiewen 
Can you please provide a  minimal reproducible code sample from Flutter and native and complete crash logs
Thank you

**Comment by VladyslavBondarenko** [comment]
@zhaojiewen 
Closing as additional information isn't provided. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible project, logs and the output of 'flutter doctor -v'  please.

**Comment by zw1924** [comment]
auto fml::internal::CopyableLambda<flutter::Shell::OnPlatformViewCreated(std::__1::unique_ptr<flutter::Surface, std::__1::default_delete<flutter::Surface> >)::$_8>::operator()<>() const (in Flutter) (make_copyable.h:24)

fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:129)

fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)

**Comment by zw1924** [comment]
This is part of the stack that my device fetched online, consistent with the report above
