### ISSUE TITLE
Exhausted heap space

### ISSUE THREAD

**Issue by abhi9045** [flutter/flutter#59772]
Exhausted heap space, trying to allocate 17179869200 bytes. Why its happen on a same app after start an app from scratch (not frequent) but hangs the whole system.

Steps to produce: I don't know.
![image](https://user-images.githubusercontent.com/39383758/85048277-beb33f00-b1b0-11ea-9c0a-045e6d5b4f4a.png)

**Comment by iapicca** [comment]
Hi @abhi9045 
I see there's an open [issue](https://github.com/flutter/flutter/issues/54927) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
