### ISSUE TITLE
improve default help page for new users

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#5977]
When a user types `flutter` with no arguments, show common actions first with more detailed information so that the new user can get started quickly...
```
Common actions:

flutter create <output directory>
    Create a new Flutter project in the specified directory.

flutter analyze [options] [<target>]
    Analyze Flutter project's Dart code.

flutter run [options]
    Run your Flutter application on an attached device
    or in an emulator.

... existing help output here ...
```

**Comment by sethladd** [comment]
Should we even show "flutter analyze", "flutter run", etc if you're not sitting in a Flutter project?

Should we show "flutter create" if you ARE sitting in a flutter project?

**Comment by eseidelGoogle** [comment]
This modality of the flutter tool has always confused me.  Does `git` or
other directory-sensitive two-level command runners like `flutter` do
anything particularly nice here?

**Comment by sethladd** [comment]
Sounds like you're advocating that we always show all commands/options, even if they aren't valid in a certain situation?

(sorry, I might misunderstand your comment?)

**Comment by dragostis** [comment]
I feel like behaving the same way is something desirable. Different behavior goes against muscle memory.

**Comment by sethladd** [comment]
Cool. Chatted with @dragostis and it does seem like the semantics of `flutter` and `flutter --help` should be "show me all the things I could ever do with this tool".
