### ISSUE TITLE
[web] Can't use `allowInterop` in flutter_web_plugins

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#59805]
This issue is a blocker for https://github.com/flutter/flutter/issues/33245

### Repro steps
1. Patch this [PR](https://github.com/flutter/engine/pull/19134) into the local engine repo.
2. Patch this [PR](https://github.com/flutter/flutter/pull/59797) into the local flutter repo.
3. In any app, add dependency on the local copy of `flutter_web_plugins` like this:
```yaml
flutter_web_plugins:
    path: ../flutter/packages/flutter_web_plugins
```
4. Use `flutter_web_plugins` in the app like so:

```dart
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() {
  setUrlStrategy(HashUrlStrategy());
  runApp(MyApp());
}
```
5. Run the app using the local engine repo:
```
flutter run -d web --local-engine=host_debug_unopt
```

### Error
```
TypeError: js.allowInterop is not a function
```
The error is thrown at [this line](https://github.com/flutter/flutter/blob/2c71b7b5dbffde2923ae0862acc039082c2e7458/packages/flutter_web_plugins/lib/src/js_url_strategy.dart#L41). The `js` is coming from `import 'dart:js' as js;`. I also tried `import 'package:js/js.dart' as js;` and got the same error.

**Comment by edy17** [comment]
This method seems to work
`import 'dart:js' as js;

void main() {
    js.context.callMethod('_flutter_web_set_location_strategy', [NavUtils.locationStrategy]);
  runApp(MyApp());
}
`

**Comment by edy17** [comment]
This method seems to work

### 

   ` js.context.callMethod('_flutter_web_set_location_strategy', [HashUrlStrategy()]);`

**Comment by edy17** [comment]
This method seems to work
 ```
import 'package:flutter_web_plugins/flutter_web_plugins.dart'; 
import 'dart:js' as js;

void main() {
     js.context.callMethod('_flutter_web_set_location_strategy', [HashUrlStrategy()]);
}
 ```

**Comment by edy17** [comment]
This method seems to work
 ```
import 'package:flutter_web_plugins/flutter_web_plugins.dart'; 
import 'dart:js' as js;

void main() {
     js.context.callMethod('_flutter_web_set_location_strategy', [HashUrlStrategy()]);
    runApp(MyApp());
}
 ```

**Comment by mikeesouth** [comment]
Not sure if this is related but I have a similar issue that is either same or a new (most likely related) issue.
I'm using Flutter for web with beta channel (Flutter 1.25.0-8.2.pre). I'm using the package `printing: 4.0.0` which imports the package `js` (currently js: ^0.6.1). Somehow I get `js: 0.6.3-nullsafety-3` into my project. The project runs fine but when I try to run `flutter test` I get this error:
```
flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3-nullsafety.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
```

If I go into that file (js.dart) and comment/remove this line:
```
export 'dart:js' show allowInterop, allowInteropCaptureThis;
```

Then flutter test works fine but if I try to run my app from VS Code, then I get this error: 
```
flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:45:14: Error: Method not found: 'allowInterop'.
    getPath: allowInterop(strategy.getPath),
             ^^^^^^^^^^^^
```

So I need to comment/remove the line in js.dart every time I want to run my tests and then change it back again when I want to run my app.

If anyone have a workaround or fix - please let me know.

**Comment by tjerkw** [comment]
I have a similar problem but different:

I am making a cross platform app, and on web it needs to call javascript in a certain scenario.

However, when building for android i get:

> ../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;

I tried doing condition imports to prevent this issue:

> 
import 'js_purchase.web.dart' if (dart.library.js) "js_purchase.native.dart";

But this doesn't work.

**Comment by tjerkw** [comment]
Ah conditional imports using `if (dart.library.io` did the trick:

`
import 'js_purchase.web.dart' if (dart.library.io) "js_purchase.native.dart";`

**Comment by yjbanov** [comment]
Seeing that the issue that this was blocking was fixed, I'll consider this as fixed.
