### ISSUE TITLE
move the calculator into //examples/calculator?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#5981]
It doesn't look like the calculator is available from the flutter_gallery app, but the source does live in //examples/flutter_gallery/lib/demo/calculator/. Should we move it into it's own directory in //examples? We use the calculator app in demos.

**Comment by sethladd** [comment]
Is anyone maintaining the calculator? If a new user tries to load it up, what would be their experience?

**Comment by abarth** [comment]
We should either:

1. Make the calculator a demo that we're proud to show (and then decide where we want to show it)
2. Decide to scrap it as a demo.

I'm currently leaning towards (1), which is #4535.  If we decide to scrap the calculator, we should do that by closing bug #4535.

**Comment by raveesh-me** [comment]
um.. can I get the code to the calculator example you guys were talking about?

**Comment by sethladd** [comment]
I think this is it: https://github.com/flutter/flutter/tree/master/examples/flutter_gallery/lib/demo/calculator

Hope that helps!
