### ISSUE TITLE
Remove Vulkan backend from the engine

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59823]
Based on @chinmaygarde comment:

> The SHELL_ENABLE_VULKAN stuff is now just maintenance burden. It's unlikely we are going to switch to Vulkan on Android anytime soon and this was primarily valuable when bringing up the Vulkan backend for Fuchsia. Now that is its standalone thing. Did you find it cumbersome to port this stuff? If so, can you file a bug for us to get rid of this backend? Its easy to revive later if needed.

**Comment by pedromassangocode** [comment]
Is there some way to verify that this was not fixed yet?

**Comment by chinmaygarde** [comment]
When we remove the backend, [`AndroidSurfaceVulkan`](https://github.com/flutter/engine/blob/d1a511743a224c39ea65513b2b868259c14a43e5/shell/platform/android/android_surface_vulkan.h) should go away.

**Comment by gnprice** [comment]
It looks like this was completed by https://github.com/flutter/engine/pull/28239 .

**Comment by chinmaygarde** [comment]
Yup. Though [everything old is new again](https://github.com/flutter/engine/pull/39905) and we are going to be Vulkan first with Impeller on Android.
