### ISSUE TITLE
Remove additional newline when printing on web

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#59820]
Printing on web is less readable than on other platforms due to the additional newline

<img width="455" alt="Screenshot 2020-06-19 at 03 03 14" src="https://user-images.githubusercontent.com/6655696/85086198-2fbb1c80-b1da-11ea-8a19-04a51011a836.png">
<img width="445" alt="Screenshot 2020-06-19 at 03 01 52" src="https://user-images.githubusercontent.com/6655696/85086202-321d7680-b1da-11ea-91fc-2e2664c5b749.png">
<img width="440" alt="Screenshot 2020-06-19 at 03 10 12" src="https://user-images.githubusercontent.com/6655696/85086279-6a24b980-b1da-11ea-8934-8d3e6b0e8478.png">

**Comment by jonahwilliams** [comment]
This might be an issue with the tool, but it does look like we're not including the newline:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart#L701

You could check if the lines already have an appended newline at that point

**Comment by guidezpl** [comment]
I don't think it's the tool, it looks good there. It only occurs in Android studio's run window, so perhaps a bug for flutter/intellij?

**Comment by jonahwilliams** [comment]
> , so perhaps a bug for flutter/intellij?

seems unlikely. This would be easy to validate by debugging the tool or running from the command line

**Comment by guidezpl** [comment]
From the command line, it's fine, both in and out of Android Studio, that rules out the tool, no?

**Comment by jonahwilliams** [comment]
only somewhat :) 

Android Studio is running the flutter app in "machine" mode, you can repro a similar setup with `flutter run -d chrome --machine"

**Comment by jonahwilliams** [comment]
if the logs in that format do not have the newline appended, then you were right - and its an Android Studio/Intellij issue

**Comment by guidezpl** [comment]
Ah thanks! I debugged this a littler further. The `message` from `_vmService` passed to ` globals.printStatus` has a \n byte at the end on web, whereas the `line` string in `resident_runner.dart` doesn't. When the --machine flag is used, `NotifyingLogger` is used, which prints `message` with the extra newline.

**Comment by jonahwilliams** [comment]
@grouma is this appending by dwds or chrome devtools? If so we should consider removing it to match the other platforms.

**Comment by grouma** [comment]
We append a newline to the console events we get from Chrome here: https://github.com/dart-lang/webdev/blob/4112b1be94563ee414b2fcaf362e2f4669a5c68d/dwds/lib/src/services/chrome_proxy_service.dart#L690

We do that to align with the `console.log` API. Otherwise the messages you see in the Dart DevTools console would not look appropriate.

**Comment by jonahwilliams** [comment]
Yes, it does make sense to eventually append a newline - but its being done in multiple places right now. What does the devtools console do for stdout/stderr from mobile/desktop flutter applications?

**Comment by grouma** [comment]
I assume Dart DevTools does not append a new line since it shows up as expected.

**Comment by guidezpl** [comment]
I'm now seeing triple newlines on the master channel in Android Studio with an iOS device

<img width="524" alt="Screenshot 2020-08-14 at 14 13 08" src="https://user-images.githubusercontent.com/6655696/90248117-555e4e00-de38-11ea-8317-e955e7e0a0a8.png">

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/63976
