### ISSUE TITLE
"Flutter Attach Hot Reload" does not take effect when modify files in ".pub-cache"

### ISSUE THREAD

**Issue by yumeTsukiiii** [flutter/flutter#59827]
1. Run `flutter attach`.
2. Update the files as follows:  files in ".pub-cache" and the project depends on these files... 
3. Press "r" to execute "hot reload", but 0 library reload...

I found some problems in "run_hot.dart", in function "findInvalidated"
```
      // Don't watch pub cache directories to speed things up a little.
      for (final Uri uri in urisToMonitor)
        if (_isNotInPubCache(uri)) uri,
```
This will cause the files in ".pub-cache" not to be updated. I want to know the reason for this, or why updating the file in ".pub-cache" will cause the speed to be much slower. 
If the speed does not slow down much, is it unnecessary to ignore these files?

**Comment by jonahwilliams** [comment]
We do not support modification of the files in the pub-cache, as these are meant to be consistently versioned and it measurably slows down file diffing on large projects. If you are finding yourself continually editing a pub-cache project, I would recommend cloning it locally and depending on it via a path dependency
