### ISSUE TITLE
error: AnimatedContainer uses curve: Curves.easeInOutBack and random margin

### ISSUE THREAD

**Issue by Lanch92** [flutter/flutter#59829]
The following assertion was thrown building 
```bash
AnimatedContainer(duration: 400ms, bg: BoxDecoration(color: Color(0x80b7b20e), borderRadius: BorderRadius.circular(50.2)), margin: EdgeInsets.all(2.9), dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedContainerState#33ed5(ticker active, bg: DecorationTween(BoxDecoration(color: Color(0x8975f154), borderRadius: BorderRadius.circular(15.6)) → BoxDecoration(color: Color(0x80b7b20e), borderRadius: BorderRadius.circular(50.2))), margin: EdgeInsetsGeometryTween(EdgeInsets.all(62.5) → EdgeInsets.all(2.9)))):
'package:flutter/src/widgets/container.dart': Failed assertion: line 315 pos 15: 'margin == null || margin.isNonNegative': is not true.
```

**Comment by iapicca** [comment]
Hi @Lanch92 
the issue might depend from your implementation;

can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
