### ISSUE TITLE
EmbeddedViewParams should provide the rect for the embedded view.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59821]
`EmbeddedViewParams` should remove `offsetPixels` since it's not useful, and instead compute the view rect based on the mutator stack.

This can be done by computing a matrix based on the mutator stack and then multiply it by the matrix [0, 0, width, height]. The final x, y, width, height should be the rect of the embedded view.

Also, this needs better documentation.

**Comment by cyanglaz** [comment]
We decided not to remove offsetPixels yet.
We also decided to add a method to calculate the bounding rect based on the mutator stack.
This method will not consider clipping for now.

**Comment by NoamDev** [comment]
If it's done, it should get closed I guess:)
