### ISSUE TITLE
I want to add alice inspector in my existing code for tracking network calls get and post.

### ISSUE THREAD

**Issue by jigarparmar21** [flutter/flutter#59831]

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by jigarparmar21** [comment]
> The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

Yes you are right, but i have not found the alice inspector solution, so i think Github would help me.
Help me if possible.
