### ISSUE TITLE
Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature.

### ISSUE THREAD

**Issue by IkhwanSI13** [flutter/flutter#59830]
I have run my apps at iOS, and all work as my expectation and I tried to archive to the App Store. But, I get this error in my email. I tried to look for it but only found this error in Xamarin and Xcode with old versions.

```
Dear Developer,

We identified one or more issues with a recent submission for TestFlight review for 
your app, "Apps Name" . Please correct the following issues, then upload again.

ITMS-90433: Invalid Swift Support - The file libswiftCore.dylib doesn’t have the 
correct code signature. Make sure you’re using the correct signature, rebuild your 
app using the current public (GM) version of Xcode, and resubmit it. Don’t just 
modify the code signature of libswiftCore.dylib.

Best regards,

The App Store Team
```

**My flutter doctor**:
```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-ID)
    • Flutter version 1.17.3 at /Users/cartenz/Soft/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cartenz/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

```

**Comment by brorhb** [comment]
Gonna have to +1 this. Just got this issue myself.
This is my `flutter doctor -v` results.
```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale nb-NO)
    • Flutter version 1.17.3 at /Users/bror/repos/tools/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bror/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    • Error: Bror (Testing) is not connected. Xcode will continue when Bror (Testing) is connected. (code -13)
```

**Comment by giandifra** [comment]
Same problem, my flutter doctor -v results:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F96,
    locale it-IT)
    • Flutter version 1.12.13+hotfix.9 at /Users/gm/flutter
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Volumes/Samsung_X5/Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.6494.35
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by blackcodefr** [comment]
Had the same issue with a fully native iOS app (that doesn't use Flutter at all). I simply cleaned the project, made a new build and that one went through without any issue. Seems like an Xcode / Apple bug.

**Comment by giandifra** [comment]
@blackcodefr it's true, i cleaned the project, rebuild and it's ok now.

**Comment by blackcodefr** [comment]
FYI. I made more builds afterwards and got the same error. Then sent 2 news builds (for the same bundle id) and didn't get it. Something weird is happening at Apple.

**Comment by jmagman** [comment]
I made a new non-Flutter Xcode project in 11.6 beta, set the iOS deployment to 9.0 to get the Swift libraries embedded, and libswiftCore.dylib is signed with my team identifier:
```
codesign -d -v /path/to.xcarchive/TestSwiftSigning.xcarchive/Products/Applications/TestSwiftSigning.app/Frameworks/libswiftCore.dylib 
Identifier=com.apple.dt.runtime.swiftCore
..
TeamIdentifier=<MyTeamID>
```

It looks the same as my Flutter app, except for the `Signed Time` timestamp.
```
$ codesign -d -v /path/to.xcarchive/Products/Applications/Runner.app/Frameworks/libswiftCore.dylib
..
Identifier=com.apple.dt.runtime.swiftCore
...
TeamIdentifier=<MyTeamID>
```
You can see your team identifier with:
```
$ security find-identity -p codesigning -v 
```

**Comment by kjawadDeveloper** [comment]
Any update?

**Comment by jmagman** [comment]
@kjawadDeveloper What's your `flutter doctor -v`? I was hoping this issue could be closed as a transient problem on an older version of Xcode.

**Comment by kjawadDeveloper** [comment]
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/jawad/fvm/versions/stable
    • Framework revision 9b2d32b605 (2 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jawad/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/jawad/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[!] Connected device
    ! No devices available

**Comment by dedvalson** [comment]
I am seeing this as well on Stable channel.

% flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Volumes/SanDisk/src/flutter
    • Framework revision b1395592de (5 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile)           • E1967B4E-B56D-4F7A-BC04-ADA66BD87A57 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPod touch (7th generation) (mobile) • D9BDF199-0798-4FD7-9C90-5BFF9C8F0B79 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google
      Chrome 89.0.4389.114

**Comment by lineker** [comment]
I have this message: This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
If open xcode and add /usr/lib/swift on BuildSettings -> Linking -> runpath search path, I'm able to deploy to simulator from xcode. If I try to do it from android studio it does not work. 

tried to flutter clean and rebuild = no good

**Comment by jmagman** [comment]
This was an Xcode issue, closing.
