### ISSUE TITLE
[Video_Player] Cannot be initialized twice on some Android devices.

### ISSUE THREAD

**Issue by SashaFarkas** [flutter/flutter#59833]
This is related https://github.com/google/ExoPlayer/issues/6168
Reproducing:
1. Initialize first VideoPlayerController with url.
2. Initialize second VideoPlayerController with same url (also works for local files).
3. Get error: Video player had error com.google.android.exoplayer2.ExoPlaybackException:
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 60.0], [-1, -1].

All the information about devices and logs can be found in related issue.

Issue has been opened for 1 year, and there is no solution yet. Please, pay your attention to this problem. It is really crucial, and compels developers to refactor their code to only fit player's needs (single controller in widget tree).

**Comment by iapicca** [comment]
Hi @SashaFarkas 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by SashaFarkas** [comment]
Bug is not reproducible on my devices. It's reported by testers.
`[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale ru-RU)
    • Flutter version 1.17.1 at /Users/macbook/development/flutter
    • Framework revision f7a6a7906b, 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

⣻Unable to find any JVMs matching version "1.8".                                                                                                                                                                                      [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 13.0.1+9)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
`
video_player: 0.10.11

I cannot provide the full pubspec.yaml

Reproducible example is 2 stateful widgets, each of them calls initialize method of its own controller in init state. Controllers shouldn't be disposed and can be placed  either in single widget tree or on different routes (Route with 1st widget -> push -> Route with 2nd widget).

I will provide code of minimal reproducible sample at the end of the day. (If it is still needed)

**Comment by SashaFarkas** [comment]
After I had made controller reusable (without reinitializing for the same url), everything became fine. But it is a terrible workaround. Managing the state of this controller (especially with AutomaticKeepAlive widgets and different volume on each route) is pain.

**Comment by iapicca** [comment]
Hi @SashaFarkas 
there's no need to provide your production code,
but the problem might depend from the implementation in your app
for the issue to be workable it will need a minimal reproducible code sample.
Thank you

**Comment by Dhua-v** [comment]
@iapicca Here is the complete reference 
[https://github.com/flutter/flutter/issues/61309](url)

thats the same issue. And many of the devs I know facing same issue with video_player.
Code is attached in this.

Thanks @iapicca

**Comment by Dhua-v** [comment]
https://github.com/flutter/flutter/issues/61309 this is a 100 percent  clear explanation  of the issue.

Pls refer this earliest.
