### ISSUE TITLE
Sogou input method for flutter

### ISSUE THREAD

**Issue by AlbertShen0211** [flutter/flutter#59845]
Operating environment: Huawei mobile Android 9.0 OS

Description: flutter app, inputting in textfield, pop up soft keyboard, click case letter switch on soft keyboard, the cursor in textfield will move to the beginning  of the textfield.

**Comment by iapicca** [comment]
Hi @AlbertShen0211 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by AlbertShen0211** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)
    • Flutter version 1.17.3 at D:\Flutter\flutter_windows_1.17.3-stable\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\spb16\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • ANDROID_HOME = C:\Users\spb16\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • VKY AL00 • WJX7N17905004130 • android-arm64 • Android 9 (API 28)

**Comment by iapicca** [comment]
Hi @AlbertShen0211 
thanksfor your doctor,
could you please provide the remaining information listed [above](https://github.com/flutter/flutter/issues/59845#issuecomment-646563566)
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
