### ISSUE TITLE
Gallery: opening and closing "About Flutter" misses lots of frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5984]
Open Gallery, open the drawer, then tap "About Flutter Gallery". Notice how the display of the box and the darkening of the background are not smooth. Then, close the box. Also seemingly missing frames.

Tested on a Nexus 5.

![screenshot_20160921-124540](https://cloud.githubusercontent.com/assets/5479/18726540/cf8423fe-7ff9-11e6-9e6a-9c69f25388c2.png)

The performance overlay shows results after opening and closing the About Flutter Gallery a few times.

**Comment by Hixie** [comment]
Opening the dialog definitely causes a spike still.

**Comment by guidezpl** [comment]
Closing as not reproducible. If you disagree, please file an issue at https://github.com/flutter/gallery.
