### ISSUE TITLE
Black square instead of keyboard while app is in multitasking screen

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#59863]
doctor: 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-RU)
• Flutter version 1.17.3 at /Users/DSurnin/flutter
• Framework revision b041144 (2 weeks ago), 2020-06-04 09:26:11 -0700
• Engine revision ee76268252
• Dart version 2.8.4

<img width="332" alt="Screenshot 2020-06-19 at 19 28 14" src="https://user-images.githubusercontent.com/42138594/85156680-1611e780-b263-11ea-918d-b76a7cbcd5be.png">

<img width="331" alt="Screenshot 2020-06-19 at 19 28 21" src="https://user-images.githubusercontent.com/42138594/85156671-114d3380-b263-11ea-9d27-55a42fb39506.png">

**Comment by iapicca** [comment]
Hi @Renesanse 
I do not experience with stock android (Pixel 3a)
[video](https://photos.app.goo.gl/gXcmjJN62ePxs8zE9)
are you experiencing this on specific devices?
Thank you

**Comment by Renesanse** [comment]
Hi @iapicca.
I found this using galaxy a10, a40, s10.

**Comment by iapicca** [comment]
Hi @Renesanse 
the issue reproduces on samsung devices
with the latest master
<details>
  <summary>screenshot</summary>

![Screenshot_20200622-150526_One UI Home](https://user-images.githubusercontent.com/45637986/85276241-29eb6280-b48a-11ea-8119-146d44d0794a.png)

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at /Users/nevercode/development/flutter_master
    • Framework revision 5995661777 (2 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a      • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

thank you for reporting this 
(and thanks @TahaTesser for reproing the issue)

**Comment by jmagman** [comment]
\cc @GaryQian who's the best person to look at this?

**Comment by darshankawar** [comment]
I verified this issue using latest master version and running a sample app on Pixel XL API 30 emulator and didn't observe the reported behavior.

<img width="435" alt="Screenshot 2023-04-18 at 6 12 35 PM" src="https://user-images.githubusercontent.com/67046386/232781090-a206b9f1-9534-4e4e-8884-a786eebd51b5.png">

Optimistically closing as fixed and not reproducible. If anybody disagrees, please file a new issue using template so that we can address it accordingly.
