### ISSUE TITLE
web_benchmarks_canvaskit text_out_of_picture_bounds regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59864]
Likely https://github.com/flutter/flutter/pull/59804. 
![Screen Shot 2020-06-19 at 9 28 01 AM](https://user-images.githubusercontent.com/1435716/85156664-3ca63300-b20f-11ea-9c00-b68694f804ec.png)

text_out_of_picture_bounds.canvaskit.totalUiFrame.average is also affected.

As canvaskit is still experimental, filing as P2 instead of a P0, but this is still a pretty large regression.  

cc @yjbanov

**Comment by yjbanov** [comment]
The fix for this has already rolled into the framework. Closing.
