### ISSUE TITLE
Embedded FlutterView and global coordinates in AccessibilityBridge

### ISSUE THREAD

**Issue by pjiang-google** [flutter/flutter#59872]
## Steps to Reproduce

We use Flutter at the view level -- a [FlutterView](https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterView.html) is embedded in an Android Activity. 

1. In a minimum repro case, the Flutter page contains a button widget.
2. Position the FlutterView in the middle of the screen (i.e., there is another view on top of the FlutterView) so that the y offset of the FlutterView is large enough (say larger than the Flutter button).
3. Use UIAutomator for instrumentation test.
4. Instruct UIAutomator to click on the Flutter button.

**Expected results:** 
The Flutter button is clicked.

**Actual results:**
UIAutomator clicks at the location above the center of the button by the y offset of the FlutterView.

This looks like Flutter's AccessibilityBridge doesn't take the location of the FlutterView into account when creating the AccessibilityNodeInfo for a Flutter widget. The origin of the rectangle of [BoundsInScreen](https://github.com/flutter/engine/blob/f5a4ea7d8321014269c83eea2f1b33224068f2da/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L661) seems to the top left corner of the FlutterView rather than the screen. As a result, the reported locations of Flutter widgets are off by the offset of the FlutterView.

**Comment by xster** [comment]
@GaryQian can you take a look at this one from a google user?
