### ISSUE TITLE
mobile/desktop engine might be missing some plumbing for sound-null-safety

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#59879]
Running with --enable-experiment=non-nullable and an agnostic mode dill, we can successfully compile a trivial program to sound null safety. Unfortunately, this fails at runtime with:

```
[VERBOSE-2:shell.cc(209)] Dart Error: error: Library 'package:hello_world/main.dart' was compiled with null safety (in strong mode) and it requires --null-safety option at runtime
```

I tried passing this flag via --dart-flags, but that did not change the messaging.

**Comment by jonahwilliams** [comment]
The API is Dart_DetectNullSafety

**Comment by jonahwilliams** [comment]
@a-siva You mentioned you were going to take a look at this?

**Comment by chinmaygarde** [comment]
Re-adjusted the milestone after consulting @kf6gpe. Assigning to myself as it seems @a-siva is swamped.

**Comment by jonahwilliams** [comment]
Removing tool designation as this only requires engine changes

**Comment by pcsosinski** [comment]
this is a blocker for running tests in sound mode - Chinmay do you have an estimate when in the month you can get to it?

**Comment by chinmaygarde** [comment]
At least two weeks. This week is for tacking blockers for next release and I am OOO next week.

**Comment by kf6gpe** [comment]
cc @kf6gpe

**Comment by kf6gpe** [comment]
@a-siva with @chinmaygarde being out next week after wrangling bug fixes this week, is this something that you can return to while he's out? Thanks!

**Comment by a-siva** [comment]
Sorry missed the comment

I could get back to it but can only start on it next week

**Comment by chinmaygarde** [comment]
@a-siva: Do you think you will be able to get to it this week? If not, happy to carry this to completion.

**Comment by chinmaygarde** [comment]
Spoke to Siva offline, I'll carry this to completion.

**Comment by chinmaygarde** [comment]
I wired up reading null-safety state from the snapshot before launching the isolate. However, it turns out, certain Dart native APIs behave differently with null-safety enabled in the snapshot. Numerous internal engine APIs need to be reworked to account for this. I am scoping out that work now. An example of the error:

```
[ RUN      ] DartIsolateTest.RootIsolateCreationAndShutdown
Dart Error: Cannot use legacy types with --sound-null-safety enabled. Use Dart_GetNullableType or Dart_GetNonNullableType instead.
[FATAL:flutter/lib/io/dart_io.cc(27)] Check failed: !LogIfError(embedder_config_type). 
[ERROR:flutter/fml/backtrace.cc(110)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fff68306808 abort
Frame 1: 0x1041885d4 fml::LogMessage::~LogMessage()
Frame 2: 0x104188633 fml::LogMessage::~LogMessage()
Frame 3: 0x105b66509 flutter::DartIO::InitForIsolate(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
Frame 4: 0x1040cf7ac flutter::DartIsolate::LoadLibraries()
Frame 5: 0x1040d2fbc flutter::DartIsolate::InitializeIsolate(std::__1::shared_ptr<flutter::DartIsolate>, _Dart_Isolate*, char**)
Frame 6: 0x1040cd8f5 flutter::DartIsolate::CreateDartIsolateGroup(std::__1::unique_ptr<std::__1::shared_ptr<flutter::DartIsolateGroupData>, std::__1::default_delete<std::__1::shared_ptr<flutter::DartIsolateGroupData> > >, std::__1::unique_ptr<std::__1::shared_ptr<flutter::DartIsolate>, std::__1::default_delete<std::__1::shared_ptr<flutter::DartIsolate> > >, Dart_IsolateFlags*, char**)
Frame 7: 0x1040cccfb flutter::DartIsolate::CreateRootIsolate(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, flutter::TaskRunners, std::__1::unique_ptr<flutter::PlatformConfiguration, std::__1::default_delete<flutter::PlatformConfiguration> >, fml::WeakPtr<flutter::SnapshotDelegate>, fml::WeakPtr<flutter::HintFreedDelegate>, fml::WeakPtr<flutter::IOManager>, fml::RefPtr<flutter::SkiaUnrefQueue>, fml::WeakPtr<flutter::ImageDecoder>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, flutter::DartIsolate::Flags, std::__1::function<void ()> const&, std::__1::function<void ()> const&)
Frame 8: 0x10408a11a flutter::testing::DartIsolateTest_RootIsolateCreationAndShutdown_Test::TestBody()
Frame 9: 0x10646a512 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 10: 0x106440c80 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 11: 0x106440b91 testing::Test::Run()
Frame 12: 0x1064419e5 testing::TestInfo::Run()
Frame 13: 0x106442b7a testing::TestSuite::Run()
Frame 14: 0x10644e3a3 testing::internal::UnitTestImpl::RunAllTests()
Frame 15: 0x106471352 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 16: 0x10644df13 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 17: 0x10644dd95 testing::UnitTest::Run()
Frame 18: 0x1041b53f3 RUN_ALL_TESTS()
Frame 19: 0x1041b52f9 main
Frame 20: 0x7fff68237cc9 start
```

**Comment by kf6gpe** [comment]
@a-siva, is there someone that can take a look at this with Chinmay?

Thanks!

**Comment by pcsosinski** [comment]
@chinmaygarde do you have an estimate of how much work this will be?  thanks

**Comment by zanderso** [comment]
@chinmaygarde and I met with @a-siva yesterday and got some clarification. @chinmaygarde mentioned that this should be done by the end of the week, and possibly earlier.

**Comment by chinmaygarde** [comment]
Update: I have the patch mostly done ([current progress on this branch](https://github.com/flutter/engine/compare/master...chinmaygarde:null_safety?expand=1)). This is taking longer than expected because we now have to delay runtime controller initialization (which owns the isolate) till after the kernel files are read (so we can detect null safety attributes from the kernel snapshot). This delay is causing races in tests that expect the isolate to be present as soon as the runtime controller is created. I now have to rework engine initialization and tests to not be susceptible to this race. The [original error](https://github.com/flutter/flutter/issues/59879#issue-642176148) and the [issue reported in my last update](https://github.com/flutter/flutter/issues/59879#issuecomment-693006906) have been addressed. Will post another update once the race is handled (hopefully the last issue in addressing sound null safety).

**Comment by chinmaygarde** [comment]
Update: I have addressed the races encountered in my last update. The Fuchsia embedder now needs to be updated to account for the the changes to isolate loading. This is straightforward and I should be able to send a patch for for review today.

**Comment by chinmaygarde** [comment]
I updated the milestone to be October but I expect this to land much sooner than the end of October.

**Comment by chinmaygarde** [comment]
EOD Update: A few unit-tests in AOT mode are still failing. Specifically, the ones where we launch the isolate with a missing main method and attempt to shut it down immediately. There seems to be a monitor in the VM that doesn't realize that the isolate wants to shutdown and it should not expect one to check in after launch. The message reads `"Attempt:13 waiting for isolate thisShouldNotExist to check in"`. Unclear if this is an issue I introduced with the reworking of the isolate launch of something in the VM. Will take a look at this with a fresh pair of eyes in the morning. Will provide daily updates till this issue is fixed.

**Comment by mit-mit** [comment]
I'm seeing a slightly different issue with `examples/hello_world` in todays master (`1.23.0-8.0.pre.167`, revision `f551178408`):

1. `cd examples/hello_world`
1. Edit `pubspec.yaml` to change `sdk: ">=2.7.0 <3.0.0"` to `sdk: ">=2.11.0-0.0 <3.0.0"`
1. `flutter run --enable-experiment=non-nullable --sound-null-safety -d and`

=>

```
mit-macbookpro4:hello_world mit$ flutter run --enable-experiment=non-nullable --sound-null-safety -d and
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        21.8s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 1.6s
E/flutter ( 6848): [ERROR:flutter/shell/common/shell.cc(210)] Dart Error: error: Library 'package:characters/characters.dart' was compiled with sound null safety (in strong mode) and it requires --sound-null-safety option at runtime
E/flutter ( 6848): [ERROR:flutter/shell/common/engine.cc(216)] Could not prepare to run the isolate.
E/flutter ( 6848): [ERROR:flutter/shell/common/engine.cc(155)] Engine not prepare and launch isolate.
E/flutter ( 6848): [ERROR:flutter/shell/common/shell.cc(493)] Could not launch engine with configuration.
Waiting for Android SDK built for x86 to report its views...          9ms
Syncing files to device Android SDK built for x86...               173ms

```

Is this the same underlying issue?

**Comment by chinmaygarde** [comment]
> Is this the same underlying issue?

Yes, this is the same issue. Specifying the flag to the isolate on startup requires updating the way in which the engine launches application instances as well as updating the usage of Dart native APIs. The challenges and current progress have been documented in my updates.

**Comment by mit-mit** [comment]
Any updates @chinmaygarde ?

**Comment by chinmaygarde** [comment]
I am running into issues updating the templates in Tonic to account for creating Dart lists of non-nullable types from our C++ containers. Stuck but Siva is providing guidance with debugging.

**Comment by Agondev** [comment]
> I'm seeing a slightly different issue with `examples/hello_world` in todays master (`1.23.0-8.0.pre.167`, revision `f551178408`):
> 
> 1. `cd examples/hello_world`
> 2. Edit `pubspec.yaml` to change `sdk: ">=2.7.0 <3.0.0"` to `sdk: ">=2.11.0-0.0 <3.0.0"`
> 3. `flutter run --enable-experiment=non-nullable --sound-null-safety -d and`
> 
> =>
> 
> ```
> mit-macbookpro4:hello_world mit$ flutter run --enable-experiment=non-nullable --sound-null-safety -d and
> Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling
> software rendering with "--enable-software-rendering".
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                        21.8s
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> Installing build/app/outputs/flutter-apk/app.apk...                 1.6s
> E/flutter ( 6848): [ERROR:flutter/shell/common/shell.cc(210)] Dart Error: error: Library 'package:characters/characters.dart' was compiled with sound null safety (in strong mode) and it requires --sound-null-safety option at runtime
> E/flutter ( 6848): [ERROR:flutter/shell/common/engine.cc(216)] Could not prepare to run the isolate.
> E/flutter ( 6848): [ERROR:flutter/shell/common/engine.cc(155)] Engine not prepare and launch isolate.
> E/flutter ( 6848): [ERROR:flutter/shell/common/shell.cc(493)] Could not launch engine with configuration.
> Waiting for Android SDK built for x86 to report its views...          9ms
> Syncing files to device Android SDK built for x86...               173ms
> ```
> 
> Is this the same underlying issue?

This error appeared for me when trying to run on an android emulator on the latest master with --enable-experiment=non-nullable. Same with windows (only with --verbose, otherwise failed silently). But worked on web.

Jonah Williams suggested to also use --no-sound-null-safety, and both android and windows booted up with no errors.

**Comment by mit-mit** [comment]
> Jonah Williams suggested to also use --no-sound-null-safety, and both android and windows booted up with no errors.

Yes, but the you are explicitly disabling sound null safety. This bug is about making sound null safety work.

**Comment by Agondev** [comment]
> > Jonah Williams suggested to also use --no-sound-null-safety, and both android and windows booted up with no errors.
> 
> Yes, but then you are explicitly disabling sound null safety. This bug is about making sound null safety work.

Thanks for the heads up. At this time this bug is outside of my scope of testing. I just needed to be able to execute an app with no regard for sound null safety. My above reply was meants for others in the same boat while we wait for a fix.

**Comment by chinmaygarde** [comment]
Update: Was running into issue with type conversion with Tonic that Siva helped figure out. Due to insufficient error handling in Tonic, conversion of lists of types without a default constructor were failing because some types (String in our case) didn't have a default constructor that could be used for the now necessary sentinel. I've reworked Tonic to account for this and the added error handling. I'm working on unit-tests for this (I've setup a test harness for this already, need to fill it out).

**Comment by pcsosinski** [comment]
blocked on https://github.com/dart-lang/sdk/issues/43810

**Comment by pennzht** [comment]
I have a few questions: 

1. After the above PR merges, will we be able to run a flutter app using `flutter run -d chrome --enable-experiment=non-nullable --sound-null-safety`?
2. After the above PR merges, will we be able to run flutter **tests** with sound null safety using `flutter test --enable-experiment=non-nullable --sound-null-safety`?

Thank you!
