### ISSUE TITLE
Keyboard hangs for Input widget in Android

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5987]
## Steps to Reproduce

When I type something with the Android keyboard, the keyboard hangs on the key press animation.

Code snippet:

``` dart
// newRecipient is a field inside a State that is connected to a StatefulWidget

// Text Changed Handler
void _handleInputChange(InputValue input) {
    setState(() {
      newRecipient = input.text;
    });
  }

// Text Input
new Input(
  onChanged: _handleInputChange,
  value: new InputValue(text: newRecipient),
)
```
## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/dayang/fuchsia/sysui/third_party/flutter
    • Framework revision 9109bb02b9 (6 days ago), 2016-09-15 09:15:11
    • Engine revision e9dd3e4e0d
    • Tools Dart version 1.20.0-dev.1.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39

[✓] Connected devices
    • Nexus 6P • 8XV5T15A23006055 • android-arm
## Logs and Crash Reports

E/ActivityManager: ANR in com.google.android.inputmethod.latin
E/ActivityManager: PID: 17724
E/ActivityManager: Reason: Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50000010 }
E/ActivityManager: Load: 0.0 / 0.0 / 0.0
E/ActivityManager: CPU usage from 11020ms to 0ms ago (2016-09-21 15:57:35.279 to 2016-09-21 15:57:46.299):
E/ActivityManager:   71% 900/system_server: 60% user + 11% kernel / faults: 5188 minor
E/ActivityManager:   62% 17724/com.google.android.inputmethod.latin: 53% user + 9.4% kernel / faults: 40406 minor
E/ActivityManager:   19% 4337/com.google.android.gms.persistent: 13% user + 6% kernel / faults: 2245 minor
E/ActivityManager:   8.8% 15886/adbd: 2.6% user + 6.2% kernel / faults: 4851 minor
E/ActivityManager:   8.7% 17635/org.domokit: 5.1% user + 3.5% kernel / faults: 187 minor
E/ActivityManager:   5.2% 356/logd: 1.9% user + 3.3% kernel / faults: 11 minor
E/ActivityManager:   4.8% 15146/android.process.acore: 2.6% user + 2.1% kernel / faults: 347 minor
E/ActivityManager:   3.6% 248/mmcqd/0: 0% user + 3.6% kernel
E/ActivityManager:   3.3% 17610/logcat: 1.6% user + 1.7% kernel
E/ActivityManager:   2.5% 8/rcu_preempt: 0% user + 2.5% kernel
E/ActivityManager:   1.6% 523/jbd2/dm-2-8: 0% user + 1.6% kernel
E/ActivityManager:   1.1% 3/ksoftirqd/0: 0% user + 1.1% kernel
E/ActivityManager:   1% 3880/com.android.phone: 0.5% user + 0.5% kernel / faults: 1 minor
E/ActivityManager:   0.9% 408/servicemanager: 0.2% user + 0.7% kernel
E/ActivityManager:   0.9% 500/dmcrypt_write: 0% user + 0.9% kernel
E/ActivityManager:   0.8% 12/ksoftirqd/1: 0% user + 0.8% kernel
E/ActivityManager:   0.8% 292/msm-core:sampli: 0% user + 0.8% kernel
E/ActivityManager:   0.8% 14746/kworker/u16:4: 0% user + 0.8% kernel
E/ActivityManager:   0.7% 16/ksoftirqd/2: 0% user + 0.7% kernel
E/ActivityManager:   0.6% 41/ksoftirqd/4: 0% user + 0.6% kernel
E/ActivityManager:   0.6% 239/cfinteractive: 0% user + 0.6% kernel
E/ActivityManager:   0.6% 17103/kworker/0:1: 0% user + 0.6% kernel
E/ActivityManager:   0.6% 17989/kworker/u17:6: 0% user + 0.6% kernel
E/ActivityManager:   0.5% 456/irq/215-fc38800: 0% user + 0.5% kernel
E/ActivityManager:   0.5% 3736/com.android.systemui: 0.2% user + 0.2% kernel / faults: 14 minor
E/ActivityManager:   0.5% 17183/kworker/u17:7: 0% user + 0.5% kernel
E/ActivityManager:   0.5% 17299/kworker/2:3: 0% user + 0.5% kernel
E/ActivityManager:   0.4% 17531/kworker/1:0: 0% user + 0.4% kernel
E/ActivityManager:   0.3% 20/ksoftirqd/3: 0% user + 0.3% kernel
E/ActivityManager:   0.3% 436/ksoftirqd/5: 0% user + 0.3% kernel
E/ActivityManager:   0.3% 17130/kworker/u17:5: 0% user + 0.3% kernel
E/ActivityManager:   0.2% 17853/kworker/u17:1: 0% user + 0.2% kernel
E/ActivityManager:   0.1% 35/kworker/u17:0: 0% user + 0.1% kernel
E/ActivityManager:   0.1% 51/system: 0% user + 0.1% kernel
E/ActivityManager:   0.1% 252/irq/224-spdm_bw: 0% user + 0.1% kernel
E/ActivityManager:   0.1% 409/surfaceflinger: 0% user + 0.1% kernel / faults: 1 minor
E/ActivityManager:   0.1% 16937/kworker/u17:2: 0% user + 0.1% kernel
E/ActivityManager:   0% 231/irq/216-tsens_i: 0% user + 0% kernel
E/ActivityManager:   0% 443/ksoftirqd/6: 0% user + 0% kernel
E/ActivityManager:   0% 543/oem_qmi_server: 0% user + 0% kernel / faults: 165 minor 36 major
E/ActivityManager:   0% 3749/wpa_supplicant: 0% user + 0% kernel
E/ActivityManager:   0% 4402/com.android.nfc: 0% user + 0% kernel / faults: 15 minor
E/ActivityManager:   0% 14974/android.process.media: 0% user + 0% kernel
E/ActivityManager:   0% 16947/kworker/u16:2: 0% user + 0% kernel
E/ActivityManager:   0% 17185/com.android.keychain: 0% user + 0% kernel
E/ActivityManager: 28% TOTAL: 18% user + 7.2% kernel + 1.8% iowait + 0.4% irq + 0.4% softirq
E/ActivityManager: CPU usage from 24478357ms to 24478357ms ago (1969-12-31 16:00:00.000 to 1969-12-31 16:00:00.000) with 0% awake:
E/ActivityManager: 0% TOTAL: 0% user + 0% kernel
W/ActivityManager: Scheduling restart of crashed service com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME in 1000ms

**Comment by dvdwasibi** [comment]
It is also important to note that the Flutter app does not crash and is fully functional.

**Comment by eseidelGoogle** [comment]
CC @jason-simmons @mpcomplete

**Comment by dvdwasibi** [comment]
Full code is here:
https://github.com/dvdwasibi/modules/blob/email_composer_to_input/packages/widgets/lib/email/editor_recipient_field_input.dart

**Comment by abarth** [comment]
```
  value: new InputValue(text: newRecipient),
```

What happens if you hold the entire input value you receive in the _handleInputChange callback and supply it here instead of extracting the text?  The other fields of the InputValue are important to the Input widget (e.g., they control the selection and editing state of the control).

**Comment by dvdwasibi** [comment]
@abarth that did the trick!

I'll write this up in my FlutterTips doc :)

**Comment by sethladd** [comment]
Is this something we should mention in the API docs for this widget?

**Comment by abarth** [comment]
> Is this something we should mention in the API docs for this widget?

Yes, definitely.

**Comment by dvdwasibi** [comment]
@sethladd 

Yes. Well actually, I think more importantly it might be very useful to have some quick code snippets showing the whole text input workflow within a `StatefulWidget`.

The FlutterChat example was taken down, so I was just doing stuff based on memory on how ReactNative text inputs work (which is pretty much the same pattern, minus the encapsulated `InputValue` object, which was also what got me).

Here is ReactNative's documentation on input:
https://facebook.github.io/react-native/docs/textinput.html

Input is a pretty vital "UI/functional atom" for most types of apps, so it's a key thing to focus on for documentation and examples.

**Comment by abarth** [comment]
> I think more importantly it might be very useful to have some quick code snippets showing the whole text input workflow within a StatefulWidget.

We can include that in the docs.  :)

**Comment by dvdwasibi** [comment]
@adam, I can work on putting the example in the docs if you have too much on your plate :)

**Comment by abarth** [comment]
Thanks!

**Comment by sethladd** [comment]
@dvdwasibi thanks! if you're going to add code snippets to the API docs (yay!) we might want to think about https://github.com/flutter/flutter/issues/5992

**Comment by dvdwasibi** [comment]
@sethladd, maybe we should think of putting the examples and explanations in the  Flutter website itself first (and maybe link to it from the Dart Docs)

![screen shot 2016-09-22 at 9 24 26 am](https://cloud.githubusercontent.com/assets/3635416/18756901/79c45d50-80a6-11e6-9459-e9ac4eedb88b.png)

Input is a "UI atom" that should be a first tier citizen that is exposed early on to users.

**Comment by sethladd** [comment]
sgtm. Let's file a new issue (maybe like "Document input"). We'd definitely accept a Markdown doc talking about our input system, and then you can link to it from the API docs. Good stuff!

**Comment by dvdwasibi** [comment]
Okay cool. There is more flexibility for formatting there too.

**Comment by abarth** [comment]
See also #6097

**Comment by eseidelGoogle** [comment]
Really hard to tell what to do with this bug.  I suspect we should either open a new one with a specific doc request or just close this as fixed?

**Comment by dvdwasibi** [comment]
This has been solved: the problem was that you should replace the whole InputValue on any change instead of just updating the text field of the InputValue.
