### ISSUE TITLE
Hell i m getting Exception has occurred. HandshakeException (HandshakeException: Connection terminated during handshake)

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#59878]
i m getting this error randomly
Exception has occurred.
HandshakeException (HandshakeException: Connection terminated during handshake)

PS C:\Users\Hello\Desktop\fffapp\fffdesign> flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.4 at C:\src\flutter
    • Framework revision 1ad9baa8b9 (2 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\Hello\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • SM A307FN          • RF8M91DA45J   • android-arm64 • Android 10 (API 29)
    • sdk gphone x86 arm • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)
• No issues found!

**Comment by TahaTesser** [comment]
Hi @atta1234 
Make sure you're not using private or restricted network, some firewall maybe blocking this
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Antonimo** [comment]
Im also getting HandshakeException, this was happening for me for over a year now with all the relevant stable releases of flutter. A workaround that I made is to re-run the request if this occurs. 
Notes from my tests:
- this happens only with servers hosted on amazon aws.
- the HandshakeException: "Connection terminated during handshake" osError: null
- the exactly the same script runs without errors on PC `dart test.dart`.
- HandshakeException happens periodically - same requests sometimes fail sometimes dont.
- HandshakeException happens to all requests at the same range of time: for about 1 seconds all the requests that made at around the same second get this error.
- HandshakeException happens more frequently when multiple different requests are made, but sometimes they all succeed without the error.
- making the same request repeatedly for a long time reproduces this error rarely, once every 10~30 seconds.
- Could not reproduce with postman
- Could not reproduce with http client app on phone (not dart)

**Comment by Maoration** [comment]
Same here... 
I coded a workaround for now as ~70% of requests do succeed, but I'm experiencing a log of the randomness @Antonimo has mentioned.

Would really love to hear any insights on the matter, and whether it's a known issue that is worked on.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
