### ISSUE TITLE
default web null-safety to --sound-null-safety and skip autodetection

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#59873]
Right now, the tool needs to configure the paths to the dill used by the frontend server for compilation, but doesn't know whether the app is going to be compiled in sound or unsound mode. The most straightforward solution would be to provide both dills and let the frontend_server decide.

EDIT:

With the vm using an agnostic dill, there should be no issues with null-safety detection. The web on the other hand requires separate dills and separate precompiled SDKs. In this case we should remove support for auto-detection and default to --sound-null-safety when the experiment is enabled. This will require the tool to choose the correct dill and serve the correct dart_sdk.js

**Comment by alexmarkov** [comment]
Note that VM/AOT uses a single agnostic platform dill file both in strong (sound) and weak (unsound) modes. So this might be needed only for the web.

**Comment by jonahwilliams** [comment]
We can build our mobile/desktop platform dill with ` "--nnbd-agnostic"` to work around this. For web, we will use the provided value of --sound-null-safety or --no-sound-null-safety instead of autodetection

**Comment by jonahwilliams** [comment]
Blocked by https://github.com/flutter/flutter/issues/59792
