### ISSUE TITLE
Decouple Input from Material Styling

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5989]
It is pretty common for a UI to have different "styled" text inputs based on use case and where that input sits in the UI.

Looking at the `Input` code, it seems that the underline color and active color are all based on  the ThemeData. It doesn't seem possible to have two inputs side by side that have different styles.

Furthermore, the underline bar is coupled with the text input. There might be situations where developers and designers want to have a custom affordance for focus, I would recommend an optional "onFocusCallback" that gives more flexibility.

**Comment by dvdwasibi** [comment]
Would you accept a patch for this?

**Comment by eseidelGoogle** [comment]
@Hixie or @mpcomplete are the right folks to talk to.

**Comment by dvdwasibi** [comment]
Talked to some devs & designers and it seems to be useful to have a base `Input` widget that is purely functional in terms of getting inputs and extend that with a `MaterialInput` widget that can carry the Material styling as implemented in the current input widget.

@jxson
@brnndnn

**Comment by abarth** [comment]
> Talked to some devs & designers and it seems to be useful to have a base Input widget that is purely functional in terms of getting inputs and extend that with a MaterialInput widget that can carry the Material styling as implemented in the current input widget.

Yes, RawInputLine is the base input widget.  It's possible the division of responsibility between the two widgets isn't ideal yet.

> It doesn't seem possible to have two inputs side by side that have different styles.

You can always create new Theme widgets for different subtrees.  However, I think the Input widget should expose properties to let you override the colors in the theme.

**Comment by eseidelGoogle** [comment]
@abarth (or @HansMuller?) recently refactored our Input layer.  Is this solved?

**Comment by dvdwasibi** [comment]
I think the InputField does a pretty good job of providing a visually un-opinionated Input widget.

I have an ongoing PR to add some more customization: https://github.com/flutter/flutter/pull/7942

**Comment by abarth** [comment]
Ok, let's close this as fixed.  If there's more specific things we want to do, we can handle those with separate issues.
