### ISSUE TITLE
Set minSdkVersion in plugins using platform views

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59894]
Plugins that use platform views on Android should set `minSdkVersion:  19` if using hybrid composition or `minSdkVersion:  20` if using virtual displays (as per https://github.com/flutter/flutter/issues/23728).

Otherwise, runtime exceptions will occur.  I noted we don't set the Sdk version in plugins like `WebView`: 
https://github.com/flutter/plugins/blob/bca1415bed81d19e6ad01db3ef50d417d91dfcd5/packages/webview_flutter/android/build.gradle#L28

cc @bparrishMines @cg021

**Comment by jonahwilliams** [comment]
Closing as done.
