### ISSUE TITLE
Create a web application using flutter but with a blank screen #40876

### ISSUE THREAD

**Issue by slompo** [flutter/flutter#59901]
Create a web application using flutter but with a blank screen #40876

_Originally posted by @yangxinliang in https://github.com/flutter/flutter/issues/40876#issuecomment-533436429_

Same problem already reported before.

flutter doctor -v
Downloading android-arm-profile/windows-x64 tools...                0,9s
Downloading android-arm-release/windows-x64 tools...                0,6s
Downloading android-arm64-profile/windows-x64 tools...              0,8s
Downloading android-arm64-release/windows-x64 tools...              0,7s
Downloading android-x64-profile/windows-x64 tools...                1,0s
Downloading android-x64-release/windows-x64 tools...                0,8s
[√] Flutter (Channel dev, 1.20.0-1.0.pre, on Microsoft Windows [versÃ£o 10.0.17134.1550], locale pt-BR)
    • Flutter version 1.20.0-1.0.pre at E:\Flutter\flutter
    • Framework revision f73f498da1 (33 hours ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Durval\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!

**Comment by slompo** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/2458817/85186765-3648a300-b271-11ea-91be-0dcb81525ca6.png)

**Comment by Qws** [comment]
What happens if you use `flutter run -d chrome --release ` ?

**Comment by iapicca** [comment]
Hi @slompo 
running the commands below with the latest master 
```console
flutter upgrade -f
flutter create test
cd create 
flutter run -d chrome
```

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at /Users/nevercode/development/flutter_master
    • Framework revision 5995661777 (2 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a      • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

the app runs as intended, 
could you please try the steps above
thank you

**Comment by slompo** [comment]
> flutter run -d chrome --release

This works perfectly.

Thanks.
