### ISSUE TITLE
Deallocate surfaces in unobstructed platform views

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59904]
iOS and Android don't deallocate surfaces. Instead, there's a surface limit.  However, it would be important to test with some customer scenarios to determinate a heuristic for deallocation.

One challenge is that creating new surfaces is relatively expensive, so this heuristic should minimize the need to re-create surfaces.

**Comment by jonahwilliams** [comment]
FYI @cbracken 

We now always deallocate down to 1.
