### ISSUE TITLE
Load all Network Images on Custom Splash Screen or Loading Screen.

### ISSUE THREAD

**Issue by mannnish** [flutter/flutter#59915]
i am using flutter web and  i want to load all network images to load on startup and till then show Loading Screen.
Please provide the code snippet :)

**Comment by davidsth** [comment]
This seems more appropriate for stackoverflow or with a simple google search. You shouldn't create issues for things like these.

**Comment by mannnish** [comment]
> This seems more appropriate for stackoverflow or with a simple google search. You shouldn't create issues for things like these.

the provided methods include using cacheNetworking packages but still the thing is I want them to load while showing Loading Screen and use them as some kind of Image variable.

**Comment by PixelToast** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by mannnish** [comment]
The discussion is moved to StackOverflow [here](https://stackoverflow.com/questions/62487074/flutter-load-all-network-images-on-custom-splash-screen-or-loading-screen?noredirect=1#comment110508160_62487074)

===Closed====
