### ISSUE TITLE
Add a controllable distance to the floating state of the SnackBar

### ISSUE THREAD

**Issue by HeebeLee** [flutter/flutter#59910]
The snackBar component is a very useful component, which I see in many Google applications. I found that Google's apps are a little higher than flutter's snackBar when they are in use. So I think when I use the snake bar, I can also have a position adjustment.

I tried to see the source code of snackBar, but I found that it could not simply implement my idea.

I have two expectations:
1. It can be the same as Google's app. I can control its distance from the bottom. (maybe just add a minimum parameter under "widget snapbar = safearea()").
2. It can be in the middle of the parent widget.

**Comment by pedromassangocode** [comment]
Hi @HeebeLee 
Unless this feature is already implemented on latest master channel. Can you please elaborate on this proposal? It is not clear what you really want the SnackBar API to have.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
