### ISSUE TITLE
Widget's global key is null after FutureBuilder

### ISSUE THREAD

**Issue by bobosette** [flutter/flutter#59916]
Hi everybody.  
I have to load some data with a futurebuilder in the body of the scaffold.  Inside the futurebuilder I have two widgets and one of the needs to manage the other so I used a global key. Normally without the futurebuilder  this work but inside the futurebuilder when I try to pass the state of a widget with the global key to the other widget that key is null!!!! Maybe there's a correlation with the futurebuilder??? 

Thanks

**Comment by iapicca** [comment]
Hi @bobosette 
Can you please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by bobosette** [comment]
I solved it thank u. Yesterday I understood the issue, there was problem
with my widget's tree!!

Il Lun 22 Giu 2020, 09:40 Francesco Iapicca <notifications@github.com> ha
scritto:

**Comment by TahaTesser** [comment]
Hi @bobosette 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by bobosette** [comment]
Yes don't worry

Il Gio 25 Giu 2020, 08:40 Taha Tesser <notifications@github.com> ha scritto:
