### ISSUE TITLE
Video player had error com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.example.flutter_app_instagram/cache/video

### ISSUE THREAD

**Issue by amirmhmdi** [flutter/flutter#59922]

**Comment by iapicca** [comment]
Hi @amirmhmdi 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and your `pubspec.yaml`. 
Thank you

**Comment by VladyslavBondarenko** [comment]
@amirmhmdi 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template
