### ISSUE TITLE
Try re-configuring heap memory

### ISSUE THREAD

**Issue by sikapoor** [flutter/flutter#59928]
Flutter run, clean, and doctor were super slow for me for a while until I discovered that I could increase my Android Studio's heap memory and fasten the process. Everything seems to be faster if not seamless now. Hope this helps anyone struggling with the same issue :)

**Comment by BrutalCoding** [comment]
This shouldn't be an open issue, sounds like something specific of Android Studio. Please close it @sikapoor.

**Comment by sikapoor** [comment]
@BrutalCoding yeah dude ofc. I am pretty new to the community, was just trying to help people in similar spots. Thanks for letting me know of the correct etiquette though!
