### ISSUE TITLE
Code snippets in API docs may become out of date

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5992]
Problem: code snippets in API docs are very useful, but may become out of date as the APIs are refactored/evolve.

On the website, we have a script that extracts code snippets from markdown docs and then analyzes the code. This catches many cases where the docs were out of date.

Perhaps we can do something similar with our API docs?

**Comment by eseidelGoogle** [comment]
This seems like a generally useful tool for Dart projects.  I thought we had made this work already (maybe I'm thinking of our website code?)

**Comment by sethladd** [comment]
@kwalrath what do we do for AngularDart api docs?

**Comment by kwalrath** [comment]
@chalin is implementing an `@source` scheme that should be applicable to other projects.

**Comment by sethladd** [comment]
Is it ready for other projects yet?

**Comment by kwalrath** [comment]
I don't think so. You can see https://github.com/dart-lang/angular2/pull/270 for the start of integration.

**Comment by chalin** [comment]
The updater tool we're currently trying out is at https://github.com/chalin/api_doc_updater
Let me know if this can help and/or whether changes to the tool would make is (more) useful.

**Comment by Hixie** [comment]
we do run the analyzer on the api docs now.

**Comment by chalin** [comment]
> Is it ready for other projects yet?

FYI, the tools are available for other repos now. /cc @filiph
