### ISSUE TITLE
After running flutter run 

### ISSUE THREAD

**Issue by Himanshunitrr** [flutter/flutter#59923]
## Steps to Reproduce

1. Run flutter run command

## Logs

PS D:\Documents\LearnFlutter\awsome_app> flutter run
Using hardware rendering with device sdk gphone x86 arm. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.
[Fatal Error] flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:7:6: Element type "gr" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/flutter_embedding_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Element type "gr" must be followed by either attribute specifications, ">" or "/>".
   > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.
      > Could not resolve io.flutter:x86_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/x86_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        14.4s
Exception: Gradle task assembleDebug failed with exit code 1

```
```

**Comment by Himanshunitrr** [comment]
Please help me, I am new to flutter

**Comment by Himanshunitrr** [comment]
Help me please !!!!!!!!!! Its been 2 days

**Comment by Chetan-Goyal** [comment]
@Himanshunitrr This problem is already solved here - #30573 .

**Comment by Himanshunitrr** [comment]
No the problem is different. But it is solved. One has to delete gradle cache and run flutter precache command

**Comment by Chetan-Goyal** [comment]
ok. Happy to hear that issue is solved.   :)

**Comment by joeyyy688** [comment]
Hello, @Himanshunitrr can you please tell me how you solved this problem
I seem to be going through the same problem as well #59923

**Comment by Himanshunitrr** [comment]
I have already told here:
https://github.com/flutter/flutter/issues/59923#issuecomment-647035782

**Comment by joeyyy688** [comment]
Where do I find the Gradle cache ?? 
Tried looking for it but couldn't find it

**Comment by Himanshunitrr** [comment]
Go to flutter folder than packages than flutter_tools and than to gradle. Than run the command
