### ISSUE TITLE
TextFormField crashes (Channel beta)

### ISSUE THREAD

**Issue by pbertsch** [flutter/flutter#59926]
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-MX)
    • Flutter version 1.19.0-4.1.pre at /Users/patrickbertsch/dev/flutter
    • Framework revision f994b76974 (11 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/patrickbertsch/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

Using a TextFormField with **maxLines = null** and **TextInputAction.newline** crashes. If I change it to **TextInputAction.unspecified** I get the result I want (creating a newline). It does not make a lot of sense.

What I expect:
Setting **maxLines = null** and **TextInputAction.newline** to work together 

**Test Code:**

```
class TestForm extends StatefulWidget {
  @override
  _TestFormState createState() => _TestFormState();
}

class _TestFormState extends State<TestForm> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Container(
        color: Colors.black38,
        padding: EdgeInsets.all(40),
        width: 400,
        height: 600,
        child: TextFormField(
          textInputAction: TextInputAction.newline,
          maxLines: null,
          maxLength: 150,
          style: TextStyle(color: Colors.white, fontSize: 20.0),
          keyboardType: TextInputType.text,
        ),
      ),
    );
  }
}` 
```

**Comment by pedromassango** [comment]
have you tried to follow the error message suggestion? it says: "Use keyboardType `TextInputType.multiline` when using `TextInputAction.newline` on a multiline".

I tested it and it fix the problem you're facing.

**Comment by pbertsch** [comment]
omg, I totally missed that.
