### ISSUE TITLE
Testing and sending feedback on @checked

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5993]
The Flutter SDK is currently ignoring the `strong_mode_invalid_method_override` error in its analysis_options. In an effort to create a strong-mode-clean codebase, which should help with size and performance of compiled code, and better maintainability, we are looking for solutions to the errors we ignore.

The Dart team has proposed `@checked` as a solution for `strong_mode_invalid_method_override`, and they would like us to test it in the Flutter SDK codebase. They would like feedback on the experience, by commenting on https://github.com/dart-lang/sdk/issues/25578

The Dart issue is https://github.com/dart-lang/sdk/issues/25578 and a description of this new feature is at https://github.com/dart-lang/sdk/issues/25578#issuecomment-247739528 (and https://github.com/dart-lang/sdk/commit/05e945d1c0f8ea8dd46ff98af2a959b482bc7008)

**Comment by sethladd** [comment]
cc @leafpetersen

**Comment by abarth** [comment]
It works!  We've removed strong_mode_invalid_method_override

**Comment by sethladd** [comment]
Great. Thanks :)
