### ISSUE TITLE
EGL context cannot be shared between threads

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#59930]
If context is current to some other thread, or if either draw or read are bound to contexts in another thread, an `EGL_BAD_ACCESS` error is generated.
https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglMakeCurrent.xhtml

This affects hybrid mode because the raster and the platform thread need to be merged. We might need to make a separate  EGL context for the platform thread.

**Comment by blasten** [comment]
This is required for https://github.com/flutter/flutter/issues/58291

**Comment by blasten** [comment]
We also need to determinate if the raster task queue is running on the platform thread to decide where to dispatch these messages: 

1. https://github.com/flutter/engine/blob/db4801c1e8895e10ebcbb394dbf66860e696a6a1/shell/platform/android/platform_view_android.cc#L127-L132

2. https://github.com/flutter/engine/blob/db4801c1e8895e10ebcbb394dbf66860e696a6a1/shell/platform/android/platform_view_android.cc#L94-L100

3. https://github.com/flutter/engine/blob/db4801c1e8895e10ebcbb394dbf66860e696a6a1/shell/platform/android/platform_view_android.cc#L112-L117

**Comment by blasten** [comment]
This is blocked as dynamic thread merging isn't ready. From @cyanglaz:

> deadlock in shell::OnPlatformViewDestroy

**Comment by cyanglaz** [comment]
https://github.com/flutter/flutter/issues/57067 is the issue blocking thread merging

**Comment by chinmaygarde** [comment]
This was cross referenced from https://github.com/flutter/flutter/issues/63585. Can this just be reworded to "Enable dynamic thread merging on Android." to better reflect the action item?

**Comment by blasten** [comment]
@chinmaygarde priority looks good. I will update this issue in a bit as I'm currently debugging this issue.

**Comment by blasten** [comment]
This issue is fixed by clearing the context before the context switch. For instance, in the raster thread before it is made current on the platform thread.  However, a single context switch appears to cause significant frame drops. I haven’t identified the cause.  

@cyanglaz  I initially thought that resetting the context on every frame was the cause, but I have verified that the slow down occurs after a single reset. So, it might not be related to the context reset. I’m still investigating.

**Comment by cyanglaz** [comment]
I haven't tried this yet but: does context switching without thread merging also cause performance issues?

**Comment by blasten** [comment]
> does context switching without thread merging also cause performance issues?

No
