### ISSUE TITLE
Null from current state

### ISSUE THREAD

**Issue by sjosegarcia** [flutter/flutter#59936]
I was wondering why there is an issue when I try to introduce validation to my fields. The error that I am getting is a `NoSuchMethodError`. When calling `key.currentState.validate()`, you can replace `key` with any of the key values.

  final _formKey = GlobalKey<FormState>();
  final _nameKey = GlobalKey<FormState>();
  final _emailKey = GlobalKey<FormState>();
  final _passwordKey = GlobalKey<FormState>();
  final _passwordConfirmKey = GlobalKey<FormState>();
  final _dobKey = GlobalKey<FormState>();
  final _fullNameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _passwordConfirmController = TextEditingController();
  final _dateOfBirthController = TextEditingController();

      Form(
        key: _formKey,
        autovalidate: false,
        child: Column(
          children: <Widget>[
            loginSignupTextForm(_nameKey, _fullNameController, "Name",
                hintText: "John Doe",
                prefixIcon: Icons.person,
                validator: validateName),
            SizedBox(height: 15.0),
            loginSignupTextForm(_emailKey, _emailController, "Email",
                autoValidate: false,
                hintText: "example@email.com",
                prefixIcon: Icons.email,
                suffixIcon: !_validEmailAddress ? Icon(Icons.error, color: Colors.white) : null,
                validator: validateEmail),

I am sorry about the formatting, cant seem to figure out why the line breaks do not work.
The method `loginSignupTextForm` builds a `TextFormField` and the keys do pass through.

**Comment by VladyslavBondarenko** [comment]
Hi @sjosegarcia 
could you provide your `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by sjosegarcia** [comment]
@VladyslavBondarenko Here is a copy of my code. After line 140 you will see another file. https://pastebin.com/uFGm10ky

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/steven/flutter
    • Framework revision 1ad9baa8b9 (5 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/steven/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by sjosegarcia** [comment]
Figured out the issue, I was passing the incorrect type to GlobalKey.
