### ISSUE TITLE
MySQL' is not recognized as an internal or external command, operable program or batch file. 'MySQL' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by shahrukhxx7** [flutter/flutter#59946]
i installed flutter sdk and i have inserted its path in enviornment variables.and while i try to start a new flutter project,i get this issue:MySQL' is not recognized as an internal or external command, operable program or batch file. 'MySQL' is not recognized as an internal or external command, operable program or batch file.
How to solve this
![a](https://user-images.githubusercontent.com/67228679/85225113-4afb7700-b3e8-11ea-91a3-c91fa6e3aa9c.JPG)

**Comment by VladyslavBondarenko** [comment]
Hi @shahrukhxx7 
does the error persist when running from cmd `flutter create bug`?
does https://github.com/flutter/flutter/issues/17907#issuecomment-392488907 help?

**Comment by VladyslavBondarenko** [comment]
@shahrukhxx7 
I hope you've solved the issue, closing since long time without an answer
