### ISSUE TITLE
Can we receive sms using url launcher

### ISSUE THREAD

**Issue by Abinavannagendran** [flutter/flutter#59943]

**Comment by Abinavannagendran** [comment]
I have 2 questions :
1).Can we receive sms using url launcher ? and How?
2). I want to send sms without user interaction. I used url launcher but using that library the sms is navigated to the messenger app. I want to send sms without navigating and once the button clicked the sms is supposed to be sen.
Can you suggest me some codes or topics?
Thank you sir.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
