### ISSUE TITLE
Testing and sending feedback for @virtual

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5994]
The Flutter SDK is currently ignoring the `strong_mode_invalid_field_override` error in its analysis_options. In an effort to create a strong-mode-clean codebase, which should help with size and performance of compiled code, and better maintainability, we are looking for solutions to the errors we ignore.

The Dart team has proposed `@virtual` as a solution for `strong_mode_invalid_field_override`, and they would like us to test it in the Flutter SDK codebase. They would like feedback on the experience, by commenting on https://github.com/dart-lang/sdk/issues/27384

The Dart issue for `@virtual` is https://github.com/dart-lang/sdk/issues/27384 and a description of this new feature is at https://github.com/dart-lang/sdk/commit/865e808f15035462e4647ee8be1e9a5161f67fd5

**Comment by sethladd** [comment]
cc @leafpetersen

**Comment by Hixie** [comment]
I tried this and put some feedback in the aforementioned bug. The analyzer doesn't yet have @virtual support as far as I can tell though.

https://github.com/flutter/flutter/compare/master...Hixie:5994-virtual

**Comment by sethladd** [comment]
Thanks for the quick turnaround! I'm going to close because testing complete! (if you feel like we need to take more action here, please reopen.)
