### ISSUE TITLE
Reading CSV file path during launch of App using intent in Flutter

### ISSUE THREAD

**Issue by server2245** [flutter/flutter#59941]
I want to open any CSV from my device's file manager but i am not finding any flutter's support for it. I have done androidmanifest changes and now CSV files launch my App but i cannot read the File path . Is this supported yet in flutter?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
