### ISSUE TITLE
Flutter Pub Get and Flutter.dev not working in Uzbekistan.

### ISSUE THREAD

**Issue by umidjonov** [flutter/flutter#59959]
Flutter Pub Get and Flutter.dev not working in Uzbekistan...
I tried many times flutter.dev but it worked only when I used Chrome Extensions such as VeePN and Winscribe.

I'm assuming that flutter pub get command is not working because of this

**Comment by VladyslavBondarenko** [comment]
Hi @umidjonov 
does using mirror sites help https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?

**Comment by umidjonov** [comment]
Hi @VladyslavBondarenko,
I've been using Flutter 1.17.3 on Ubuntu 20.04 and it kept asking for Upgrade...
But I switched to Windows 10 and simply reinstalled Flutter 1.17.4 and its "flutter pub get" is working just fine.

**Comment by VladyslavBondarenko** [comment]
@umidjonov 
then closing the issue. If you disagree please write in comments and I'll reopen
