### ISSUE TITLE
Flutter freezes when navigating to a widget tree with the Consumer Widget in it. Also stuck in hot reload/hot restart when attempting to restart the app.

### ISSUE THREAD

**Issue by PabloG6** [flutter/flutter#59956]
1. Download the project from [this](https://github.com/PabloG6/driving_app) git repository
2. Install the app and attempt to navigate between the screens by clicking on the top Text widget in the card on the bottom (15 DriveWay Aveneue)
3. The app freezes. If you comment out the `Expanded` widget that surrounds the `Consumer` widget in the `lib/places_search.dart`  file, the app works perfectly fine and navigates between both widgets seamlessly. 
4. Hot reload and Hot restart also stop working in their entirety.

**Expected results:** App should navigate between both screens without freezing

**Actual results:** App freezes.

**Comment by iapicca** [comment]
Hi @PabloG6 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a **minimal** complete reproducible code sample 
(not a production app)
Thank you

**Comment by PabloG6** [comment]
Closing this issue, unable to replicate it in an isolated situation.
