### ISSUE TITLE
Flutter app crash on run

### ISSUE THREAD

**Issue by acctgen1** [flutter/flutter#59957]
Launching lib\main.dart on X1S in debug mode...

Oops; flutter has exited unexpectedly: "FormatException: No ':' on line (at offset 9903)".
Running Gradle task 'assembleDebug'...
Target kernel_snapshot failed: FormatException: No ':' on line (at offset 9903)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\scr\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\scr\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
RunningChecking Android licenses is taking an unexpectedly long
Running Gradle task 'assembleDebug'... Done                        22.2s
A crash report has been written to
C:\Users\OBOUNCE\Desktop\samFlutterProjects\freshgentle\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JfN1t

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template.
Thank you!
https://git.io/JfN1q

**Comment by acctgen1** [comment]
Flutter doctor -v

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.19041.330], locale en-US)
    • Flutter version 1.17.3 at C:\scr\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\OBOUNCE\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\OBOUNCE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • X1S • S4FYHIS8PBBA49JB • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by mkiisoft** [comment]
have you checked this response? https://github.com/flutter/flutter/issues/12128#issuecomment-442306749

**Comment by Tonku** [comment]
Are you using svg ?

**Comment by acctgen1** [comment]
Okay thanks, I think problem resolved.
