### ISSUE TITLE
Feature request: Allow code to run on boot in a new file or method

### ISSUE THREAD

**Issue by NoudZandbergen** [flutter/flutter#59965]
## Use case
When you have code that you want to run at all time when the phone is on, except when the user forcibly closes the app.

### My case
I'm working on a social media app, and I need to be able to send and receive incoming packets on a socket.IO connection at all time. I think I can keep listening for packets while the app is open, but I'd like to be able to do it without needing the user to start the app every time and keep it open. Eventually I also want to add some feature like contact tracing with bluetooth (to keep location data anonymous from our servers and maintain privacy, so that will probably also have to use a background service. And this would be such a nice way of implementing it.

## Proposal
Allow the user to define a boot file that runs some code a little bit after the device boots, and keeps that running as a background service if it was defined. Or add a secondary method in the main file like void boot() instead of void main(). But I understand it might be hard to add a new entry point to files, and it's not really a clean thing to do maybe. It would be the easiest though. Don't isolate the code, run it in the same thread so you can easily make calls to an internal service. If isolated code is needed for performance, it can be started in there.

So either this:
```dart
// main.dart (whatever entry file you define)

// Some names available: onBoot, postBoot... You'll come up with something
void onBoot() {
// Background service code here
}

// Other app code and void main() here
```
Or like this
```dart
// boot.dart (File defined in a config file)

void main() {
// Background service code here
}
```

I kinda get that flutter is supposed to be a UI toolkit, but it's getting to a point where it can do many more things, which is awesome! Working with one singular codebase and being able to do anything with them is truly something we should have already. And I think if that's the direction flutter is going, which it should be, this needs to be one of the features!

**Comment by NZonGithub** [comment]
And I guess, also add a method for when the app is closed so that data can be saved beforehands. If anything is already in place for both selected features, please let me know!

**Comment by iapicca** [comment]
Hi @NZonGithub 
what you are describing sounds more like a permission handler
and I'm not sure that it should be a first party package,
but I definitely see such feature as desirable.
Thank you

**Comment by NZonGithub** [comment]
Hey @iapicca,
Thanks for your feedback!
I do think it would make sense to be a first party package. Maybe for dart instead of flutter though, as flutter is only meant for UI's if I'm correct? But running background code is very crucial for a lot of applications.

What would you recommend for me to do in order to take this further? I don't want to take the matter in my own hands, and I believe that flutter devs don't look at this issues tab that much, so is there a better place to approach them?

**Comment by stuartmorgan** [comment]
There is no way to do what you are describing on iOS. I'm not sure if that's true of Android as well; if it is possible there this seems like a use case best addressed with a third-party plugin.
