### ISSUE TITLE
[Camera] One back camera received instead of 3 with availableCameras() and iPhone 11 pro

### ISSUE THREAD

**Issue by iNima** [flutter/flutter#59964]
## Steps to Reproduce

1- Use the camera plugin on iPhone 11
2- Get the list of the available cameras with calling `availableCameras()`.
3- iPhone 11 has 3 back cameras (Standard, Tele, Ultra wide)

**Expected results:** receive 3 back cameras

**Actual results:** received 1 standard back camera
(It works correctly on Samsung S20 which has ultra-wide camera as well.)

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-AU)
    • Flutter version 1.17.1 at
      /Users/iNima/Projects/AssetOwl/SampleProjects/flutter
    • Framework revision f7a6a7906b (6 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/iNima/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/iNima/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Nima's iPhone • 

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @iNima 
what version of [camera](https://pub.dev/packages/camera) plugin are you using?
thank you

**Comment by iNima** [comment]
Hi @iapicca 
I'm using camera version 0.5.7+4
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by iNima** [comment]
Hi @TahaTesser ,

I tested it with the latest version of the camera plugin's example project, v0.8.1+7 on an iPhone 11 pro.
The `availableCameras()` still sends just two cameras, one back and one front.
I expect to receive at least two back cameras since iPhone 11 pro has 3 back lenses (Normal and ultra-wide).
This is the output:

![Screen Shot 2021-08-06 at 1 03 21 pm](https://user-images.githubusercontent.com/4446420/128450007-94ea1336-5e17-4f53-bdf2-f0f82590e27c.png)

**Comment by iNima** [comment]
I checked the iOS source code and it seems the in the camera plugin on iOS only `AVCaptureDeviceTypeBuiltInWideAngleCamera` has been set in the `discoverySessionWithDeviceTypes`.
(line 1360 of CameraPlugin.m)
But there are more types available such as:
```
AVCaptureDeviceTypeBuiltInDuoCamera
AVCaptureDeviceTypeBuiltInDualCamera
AVCaptureDeviceTypeBuiltInTripleCamera
AVCaptureDeviceTypeBuiltInTelephotoCamera
AVCaptureDeviceTypeBuiltInTrueDepthCamera
AVCaptureDeviceTypeBuiltInUltraWideCamera
```
