### ISSUE TITLE
Gallery's Contact demo's app bar gets stuck.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5997]
Steps to reproduce:
- Go to Contact.
- Select 'Toolbar scrolls away' from the drop-down menu.
- Scroll up such that the first mobile number is not visible, including the word "Mobile", but no more.
- Slowly scroll down until the app bar gets stuck briefly, as it's moving back down.

**Comment by sethladd** [comment]
Good find, thank you!

**Comment by eseidelGoogle** [comment]
Confirmed.  What a strange bug?  Maybe it has to do with padding on the list.  Also this may very well be fixed by @Hixie's grand scrolling refactor which is landing as we speak.

![demo mp4](https://cloud.githubusercontent.com/assets/11857803/22757135/88eb3f68-edfe-11e6-967c-7acf9e4cda36.gif)

**Comment by eseidelGoogle** [comment]
I've seen it get stuck at other offsets besides the one corresponding with the status bar.  It seems to depend on how far up you scroll it before scrolling back down as to which offset it will briefly pause at.

**Comment by Hixie** [comment]
Fixed.
