### ISSUE TITLE
Corrupt UI in Flutter app when launched in background by signal from Apple Watch

### ISSUE THREAD

**Issue by Henrik-glt** [flutter/flutter#59971]
## Problem
When Flutter app with a WKExtension (Apple Watch app) is started in background because of signal/message from app the UI in the Flutter app becomes corrupted.

Texts is not shown at all or shown partially.
The same goes for all widgets. 
Borders are shown, but content is not rendered at all or not rendered correctly.
The only widget that works when the app is in this "state" is images loaded from url.

Looks just as if flutter was interrupted while loading assets, fonts etc..

## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a WKExtension as described in the flutter guide: https://flutter.dev/docs/development/platform-integration/apple-watch
3. In the default InterfaceController that was created when adding the WKExtension: Override willActivate and send a message to phone. Doesn't matter what data you send, what matters is that the app on the phone will launch.
4. Install on phone and watch.
5. Force close the app on the phone, lock the screen and wait for ~20 seconds.
6. Start the app on the **Apple Watch** (this will send a message to phone and launch the app in background while screen is locked).
7. Wait another ~20 seconds.
8 Start the app on phone.

**Expected results:** 
Expected the UI to be rendered correctly.

**Actual results:** 
Texts and other widgets are only partially rendered (or not rendered at all)

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel unknown, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.17.3 at
      /Users/USER/Documents/Development/FLUTTER_SDK/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/USER/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • GLT iPhone 6s • d7d93ecfbb6f60e5fef474c5fdb5de0fbec6c550 • ios
      • iOS 13.4
    • Chrome        • chrome                                   • web-javascript
      • Google Chrome 83.0.4103.106
    • Web Server    • web-server                               • web-javascript
      • Flutter Tools
```

</details>

**Comment by iapicca** [comment]
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by Henrik-glt** [comment]
@iapicca Doesn't happen every time, but it seems to happen more frequent on less powerful devices like the iPhone 6s.
When force closing the app on an iPhone 6s, waiting for 20 seconds, starting the app on Apple Watch (which launches the app on phone in background), waiting another 20 seconds, the UI becomes corrupt ~50% on the iPhone 6s I'm testing with.

I've also tested with the current beta version (1.19.0-4.1.pre) with the same result.

**Comment by Hixie** [comment]
We believe this is the same issue as #57676.
