### ISSUE TITLE
omit_local_variable_types have been disable but still get warning Omit type annotations for local variables.

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#59973]
<img width="339" alt="Screen Shot 2020-06-22 at 4 53 58 PM" src="https://user-images.githubusercontent.com/52562340/85274405-169bbf80-b4a9-11ea-8955-149ebe4ed2d4.png">

<img width="626" alt="Screen Shot 2020-06-22 at 4 54 11 PM" src="https://user-images.githubusercontent.com/52562340/85274426-1e5b6400-b4a9-11ea-9d42-a9bb29f86ccc.png">

I was clicked on `Open documentation` and it show https://dart-lang.github.io/linter/lints/omit_local_variable_types.html

**Comment by iapicca** [comment]
Hi @tbm98 
could you please follow this same [procedure](https://github.com/flutter/flutter/issues/59976#issuecomment-647489827) 
thank you
