### ISSUE TITLE
dispose not call after hot restart

### ISSUE THREAD

**Issue by hokamc** [flutter/flutter#59983]
## Steps to Reproduce

1. create a statefulwidget and hot restart

**Expected results:** 

dispose is called to release resource

**Actual results:** 

dispose is not called

### Questions

1. Is there any way to call dispose?
2. if no, any hack trick I can use to release resources?

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @hokamc 
this is expected https://api.flutter.dev/flutter/widgets/SingleTickerProviderStateMixin/dispose.html.

Do you need to call dispose on hot restart, not on hot reload? on hot reload you can call dispose in [reassemble](https://api.flutter.dev/flutter/widgets/State/reassemble.html) function?

Related to https://github.com/flutter/flutter/issues/10437

**Comment by hokamc** [comment]
@VladyslavBondarenko 
I need to call dispose on hot restart. 

My problem is similar to him [https://github.com/flutter/flutter/issues/10437#issuecomment-641259368](url)

Any trick to solve it now?

**Comment by VladyslavBondarenko** [comment]
@hokamc 
then please follow up on the issue, closing as duplicate.
If you disagree write in the comments and I will reopen it
