### ISSUE TITLE
can't create flutter project

### ISSUE THREAD

**Issue by wuaitianya** [flutter/flutter#59984]
## Steps to Reproduce

1. hello, i have the problem to create flutter project on my mac(China). I have run 'flutter doctor',there is no error, but when i use android studio to create a new flutter project, it shows 'creating flutter project' then stuck, and the folder under the project path is empty.

2.I try to run 'flutter create project_name' in the terminal , it shows
```
Creating project project_name...
Because flutter_tools depends on node_preamble any which doesn't exist (could not find package node_preamble at https://pub.flutter-io.cn//国内用户需要设置), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```
 3.I am sure, the address 'https://pub.flutter-io.cn//国内用户需要设置' is available ,and the package node_preamble exist, but i don't  know the reason.

thank you

**Comment by iapicca** [comment]
Hi @wuaitianya 
could you please make sure you are following the steps described in the [docs](https://flutter.dev/community/china) 
and run 
```console
flutter upgrade -f
flutter create test -v
```
thank you

**Comment by YazeedAlKhalaf** [comment]
I guess you have to check your internet connection 😒

**Comment by wuaitianya** [comment]
> I guess you have to check your internet connection 😒

**Comment by wuaitianya** [comment]
> Hi @wuaitianya
> could you please make sure you are following the steps described in the [docs](https://flutter.dev/community/china)
> and run
> 
> ```
> flutter upgrade -f
> flutter create test -v
> ```
> 
> thank you

thank for your reply, i have solved this problem by reinstalling flutter SDK with terminal.
