### ISSUE TITLE
Increase size of AppBar leading property

### ISSUE THREAD

**Issue by perfoWorks** [flutter/flutter#59991]
New Feature for increasing size of app bar leading property.

I'm trying to add my custom text button into AppBar leading property. However when the text gets too long then it end up in multi lines. 

```
Scaffold(
      appBar: AppBar(
        centerTitle: true,
        leading: Text('Go back to'),
      ),
    )
```

We can make workaround to omit leading and add row into a title property but that makes centering title a nightmare.

```
Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: <Widget>[Text('go back to'), Text('My center title')],
        ),
      ),
    )
```

apparently leading width size is predefined to 56px. Can you make that size adjustable? I would add an image here but apparently that isn't possible here but the request should be obvious enough without images

**Comment by AyushBherwani1998** [comment]
@shihaohong wouldn't be adding the property to change the width of the leading break the Material specs for the `AppBar`? In my recent PR to customize `AppBar` height, I didn't change this
https://github.com/flutter/flutter/blob/401690a64f7780ca55c763ebf2e0b449b1180c2e/packages/flutter/lib/src/material/app_bar.dart#L524

to be the custom height of the toolbar, cause I thought it would break the specs. If it's allowed, I would like to send a PR to add `leadingWidth` property.

**Comment by shihaohong** [comment]
I think our goal with Flutter Material now is to basically adhere to the Material specs by default, but allow developers the option to customize in ways that do not keep with the spec if they so choose. However, I do believe that with adding API surfaces, we should be careful to not introduce confusing parameters. 

If we were to allow leadingWidth to be customizable and that causes disturbances to the positions of other widgets in the AppBar in ways that are hard to control, then exposing leadingWidth might not be worth it. On the other hand, if it's easy for developers to play around with the width values and organize everything within the AppBar, then go for it!

**Comment by AyushBherwani1998** [comment]
I think it makes sense to add `leadingWidth` and allow users to modify it according to their needs. I'll submit a PR soon.

**Comment by AyushBherwani1998** [comment]
@shihaohong should I add the `leadingWidth` for `SliverAppBar` too?

**Comment by shihaohong** [comment]
@AyushBherwani1998 It could be part of a second PR!
