### ISSUE TITLE
Unable to use ProfilingSummary to interpret Timeline summary with profiling data

### ISSUE THREAD

**Issue by AlbertWang0116** [flutter/flutter#60008]
https://github.com/flutter/flutter/issues/58803 has added the interpretation of timeline summary and we should be able to fetch CPU, GPU, Memory measurements from it.

Per it requires, firstly I need to filter timeline summary by category `flutter::profiling`,  but I end up getting nothing with this condition. In local debugging, I printed all the trace events, and I found profiling data appearing there. The category is `embedder` instead.

In [trace_event.cc](https://github.com/iskakaushik/engine/blob/55966/fml/trace_event.cc#L211-L220), I notice category was not picked up when generating trace event to the Dart land. I guess that's where `flutter::profiling` was dropped.

@iskakaushik

**Comment by chinmaygarde** [comment]
Triage: Is this something you are working on right now? If so, can you assign a priority and a customer label? Thanks.

**Comment by iskakaushik** [comment]
@rmacnak-google , currently we generate all our profiling events through `Dart_TimelineEvent`, would it be feasible to have an api in dart that lets an embedder specify a category? This will let us develop tooling based on categories of events. If you think that is a reasonable request, I'm happy to file an issue in the dart repo.

**Comment by rmacnak-google** [comment]
I believe the timeline machinery requires the set of categories to be a VM-build-time constant. Separate from the VM's own reasons, IIRC the underlying APIs for macOS and Fuchsia tracing require static strings for categories (so they don't need to copy).

**Comment by iskakaushik** [comment]
Thanks @rmacnak-google. @AlbertWang0116 given this, i'll tweak the driver to filter by the event names rather than the categories. Should be a reasonable workaround.
