### ISSUE TITLE
Flutter IDE, Its very own ONE 💙

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#60001]
# Use case

It would be great if a new project is added which is creating an IDE for Flutter. An IDE that is Flutter aimed would make it a lot more appealing to newcomers and even to experts. It will allow the Flutter community to be so great!

## Proposal

The IDE idea might be a little bit shady because of Apple regulations, but if the engineering team could take a look at it, that would be great. They might see the benefits of it!

**Comment by YazeedAlKhalaf** [comment]
@timsneath sorry for a lot of mentioning today just wanted your opinion 😊

**Comment by britannio** [comment]
Are you looking for a replacement for VSCode, Android Studio, Intellij etc? What shortcomings are you concerned about?

**Comment by YazeedAlKhalaf** [comment]
Exactly, a replacement for all of them.

Features in mind now:

• Ability to use drag and drop and sync with code. I know there are some solutions by the community for drag and drop but they are not mature enough to be used for production. I think having an IDE changes the game a lot.
• Ability to use multiple flutter versions, and manage them.
• etc...

**Comment by iapicca** [comment]
Hi @YazeedAlKhalaf 
this repo aims to improve flutter frameworks and its plugins,
your proposal doesn't seem to be aimed to improve flutter as a framework,
but to develop an entirely separate product dedicated to flutter.
Thank you

**Comment by YazeedAlKhalaf** [comment]
Hi @iapicca 

I was wondering if the Flutter team and community could work on something for Flutter, IDE.
Like Android Studio, RubyMine, PhpStorm, etc.. AKA IntelliJ Based IDE for Flutter.

I hope you can re open this issue

**Comment by timsneath** [comment]
We have no plans at present to create a whole new IDE for Flutter; Android
Studio provides everything that Flutter needs in terms of IntelliJ-based
IDEs.
