### ISSUE TITLE
Keeping track of flutter version for projects and downgrading flutter / dependencies

### ISSUE THREAD

**Issue by danafergan** [flutter/flutter#6000]
I've been working on an experimental project with collaborators using older versions of flutter. Since their source code is reliant on older versions of flutter and I have a current version, I spent a lot of time debugging and finding out why certain syntax wouldn't work on my machine (i.e. the change from window -> physicalWindow) and why we had different output from the same code.

I also couldn't find a good way to downgrade flutter because simply checking out an older version doesn't change the version (at least according to flutter doctor) and I couldn't downgrade all of the flutter dependencies.

What is the best practice for managing flutter version in a project, and is there a good way to change  versions?

**Comment by abarth** [comment]
> I also couldn't find a good way to downgrade flutter because simply checking out an older version doesn't change the version (at least according to flutter doctor) and I couldn't downgrade all of the flutter dependencies.

You should be able to downgrade all the dependencies.  If you use git to pull up an old version and then run `flutter packages get` in the project you're working on, that should properly downgrade all the dependencies.

> What is the best practice for managing flutter version in a project, and is there a good way to change versions?

The current way to manage the flutter version is to use some technology for managing git dependencies.  For example, you can use git submodules, repo, gclient, or a number of other tools that solve the problem of cloning git repositories at a particular revision.  You should be able to upgrade and downgrade the flutter version just by changing the git revision and running `flutter packages get` in the project that depends on Flutter.
