### ISSUE TITLE
Determine if the raster is running on the platform thread

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#60010]
Due to https://github.com/flutter/flutter/issues/59930, it's required to know if the raster task queue is running on the platform thread.  This needs to be accessed from `shell/platform/android/platform_view_android.cc`.

Possibly, this can be added to `TaskRunners`: https://github.com/flutter/engine/blob/db4801c1e8895e10ebcbb394dbf66860e696a6a1/common/task_runners.h#L15

Any thoughts? @iskakaushik @cyanglaz

**Comment by cyanglaz** [comment]
maybe https://github.com/flutter/engine/blob/master/fml/memory/task_runner_checker.h ?

**Comment by blasten** [comment]
oh - is that just `RunsOnTheSameThread(raster_queue_id, platform_queue_id)`?

**Comment by cyanglaz** [comment]
Yep.
Note that this method doesn't necessarily say the raster_queue is running on the platform thread. It rather says both of them are running on the same thread.
For example, if the platform_queue is running  on the raster_thread, this will return true as well.
However, we won't face this hypothetical scenario ever, just wanted to point out.

**Comment by blasten** [comment]
Closing as this is resolved.
