### ISSUE TITLE
FontManifest.json is inconsistently generated

### ISSUE THREAD

**Issue by coreysprague** [flutter/flutter#60012]
Our application consists of a large number of packages. One of our lower level packages defines our common theming, including fonts. There are intermediate packages that depend on this theming package. These intermediate packages may contain Golden tests where we have dynamically loaded fonts via the FontManifest, so that the Goldens appear with the correct font, rather than Ahem. 

Conceptually, the architecture might look something like this:

App
  |- HomeScreen Package _(uses font from Common Theming)_
  |---|- Common Theming Package (includes a custom font)

The HomeScreen package may contain specific widgets that use the custom font that it wishes to render via Golden tests.

What we have observed is that the FontManifest.json is only included in the unit_test_assets folder if the intermediate package includes one or more image assets. If it does not, then the FontManifest is not generated.

As a work-around, we have been including an empty images folder to force the manifest to be generated.

```yaml
assets:
  #empty folder to force FontManifest.json to be generated
  - images/
```

Note: this is only a problem in a testing context. In an application context, everything works as expected.

## Steps to Reproduce

1. Define a package A that includes a font in its pubspec.yaml
2. Depend on package A from a new package B
3. Do not add any additional assets to package B
4. build the package, for example using ```flutter test```
**Expected results:** 
that /build/unit_test_assets would contain a FontManifest.json file that references the font from package A

**Actual results:**
no /build/unit_test_assets folder is generated at all.

I have created a repo that demonstrates the issue:
https://github.com/coreysprague/flutter_font_manifest_issue

if you run flutter test in the package: 
*package_with_assets* with an empty images directory, the FontManifest.json is properly generated

if you run flutter test in the package *package_without_assets*, the unit_test_assets directory is not generated.

It is possible that we are mis-using the FontManifest.json file. Ultimately, the requirement we are trying to solve is to get our real fonts to appear in goldens in unit tests. Using the FontManifest.json file seemed like the most scalable way to dynamically load all of the fonts from packages that our code might depend on.  

Additionally, we did review the guidance about fonts, but I'm not sure the solution of duplicating/redeclaring the font definition in every pubspec.yaml scales for a larger application. https://flutter.dev/docs/cookbook/design/fonts#from-packages. The solution we use described at the beginning of this issue seems to work for all production cases (and mirrors how assets are treated). The only issue is this FontManifest.json quirk.

```sh
[✓] Flutter (Channel master, 1.20.0-1.0.pre.135, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-1.0.pre.135 at /Users/cosprague/Library/Code/flutter
    • Framework revision eaf9ff738a (82 minutes ago), 2020-06-22 11:53:54 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/cosprague/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available
```

**Comment by iapicca** [comment]
Hi @coreysprague 
from your assertion

> we did review the guidance about fonts, but I'm not sure the solution of duplicating/redeclaring the font definition in every pubspec.yaml scales for a larger application. https://flutter.dev/docs/cookbook/design/fonts#from-packages. The solution we use described at the beginning of this issue seems to work for all production cases (and mirrors how assets are treated). The only issue is this FontManifest.json quirk.

I'm understanding that the inconsistency is between 
the almost universal `assets-like approach` and the `FontManifest.json`
which, while undesirable, it seems to be consistent with the documentation,
is that correct?

If so, I'd like to hijack the issue as proposal / feature request.

Thank you for reporting this

**Comment by coreysprague** [comment]
@iapicca, I'm fine with it being a proposal / feature request.

I haven't seen the intent or purpose of FontManifest.json documented anywhere, so I can't say whether it is working as intended or not

**Comment by jmagman** [comment]
@dnfield @jonahwilliams

**Comment by dnfield** [comment]
Sounds like we don't normally generate the font manifest for tests, but we should be able to.

**Comment by MrBirb** [comment]
@pedromassangocode Pedro can you confirm if this [PR](https://github.com/flutter/flutter/pull/81341) fixes this?

**Comment by pedromassangocode** [comment]
It seems so. Thank you for the follow up :)

Closing as fixed by @erickzanardo in https://github.com/flutter/flutter/pull/81341.
