### ISSUE TITLE
multiple devicelab linux tests are red

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#60011]
Unclear whether this is a infrastructure issue or a bad commit. I reverted the last commit landed and more tests failed, which seems to imply infra issue.

@godofredoc

**Comment by jonahwilliams** [comment]
Seems to have been resolved? Marking as closed though I don't know the cause or fix

**Comment by godofredoc** [comment]
\cc @digiter 

From the logs it may have been related to bad checkouts. @digiter rebooted the machines and I haven't seen the failures after that.
