### ISSUE TITLE
[web][ios-safari] unskip pointer bindings test

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#60033]
17 methods were skipped to enable ios-safari unit testing, for this class.
https://github.com/flutter/engine/blob/master/lib/web_ui/test/engine/pointer_binding_test.dart

They were failing for ios-safari uni tests( iOS13.0, iPhone 11)

**Comment by nturgut** [comment]
For more details on the failures logs: https://logs.chromium.org/logs/flutter/led/nurhan_google.com/652cd2c26ba579ff4178a22163dc44ab5b722aacb796f3e9cc453cf9b20b9fb3/+/steps/felt_ios-safari_test/0/stdout

**Comment by pedromassangocode** [comment]
Still valid today as the skipped test cases does exist.

**Comment by yjbanov** [comment]
We moved all our Safari tests to macOS Safari. Our previous iOS testing approach has lead to severe flakiness and maintenance issues. We should try again, but for now this is not actionable as we're not skipping any tests on iOS.
