### ISSUE TITLE
Increase minimum supported iOS version from 8.0 to 9.0

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60035]
Xcode 14 dropped support for deploying to iOS 8.0.  Minimum supported version is 9.0.

Warning in Xcode:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```

Update template IPHONEOS_DEPLOYMENT_TARGET to 9.0.

**Comment by jmagman** [comment]
My iPhone 4s is running 9.3.6.

**Comment by EliasDeuss** [comment]
@jmagman would the only change need to be the MinimumOSVersion key in the flutter_tools template?

**Comment by jmagman** [comment]
From https://github.com/flutter/flutter/pull/61306#issuecomment-657696930
> Adopting 9.0 would require changing in more places, like all usages of `IPHONEOS_DEPLOYMENT_TARGET`, plugin podspec templates that set `s.platform = :ios, '8.0'` , auditing for `-miphoneos-version-min=8.0` and a bunch more places
> 
> We're evaluating how to address #60035 at the moment (whether we should drop 8.0 support or suppress the warning).

**Comment by xster** [comment]
Do we need a separate bug to track migrations for existing apps?

**Comment by jmagman** [comment]
> Do we need a separate bug to track migrations for existing apps?

https://github.com/flutter/flutter/issues/62880
