### ISSUE TITLE
[iOS] New iOS 14 CupertinoActivityIndicator

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#60047]
Looks like apple has changed the activity indicator. 

[iOS 13]
![cupertino-activity-indicator](https://user-images.githubusercontent.com/13773566/85353086-4dc79c00-b4bc-11ea-89d1-15f6ae7a8b2e.png)

[iOS 14]
![IMG_0184](https://user-images.githubusercontent.com/13773566/85353135-6afc6a80-b4bc-11ea-828f-6a51a8e869f3.jpeg)
(Gif)
![ezgif-6-9310c764117b](https://user-images.githubusercontent.com/13773566/85353330-cfb7c500-b4bc-11ea-9a41-776aaac8f0f6.gif)

**Comment by jmagman** [comment]
@justinmc Should this have been closed via https://github.com/flutter/flutter/pull/60179?

**Comment by ctrysbita** [comment]
If we have a new issue to track the deprecation, this can be closed.

**Comment by justinmc** [comment]
Thanks for calling that out, I knew we had a duplicate issue somewhere.
