### ISSUE TITLE
build_ios_framework_module_test fails with Xcode 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60043]
Xcode 12 decided to change the generated XCFrameworks iOS arm directory name from `armv7_arm64` to `arm64_armv7`.  Tests fail because directory not found.

https://github.com/flutter/flutter/blob/bfbb347682cb4b9b7980ed7c1a37d47b64546e5e/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L116

**Comment by onimeshc-iprogrammer** [comment]
How do we resolve this?

**Comment by jmagman** [comment]
@onimeshc-iprogrammer This issue is reporting a problem with a Flutter CI post submit test, and was resolved in June.  You should create a new issue and completely fill out the template so we can investigate your problem.
