### ISSUE TITLE
[devicelab] branch dashboard on retrying task state for hours

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#60056]
Some devicelab tasks running on 1.19 have been on a running state for several hours.

\cc @pcsosinski

**Comment by godofredoc** [comment]
- [ ] Task vacuum is not running on branches.
- [ ] There are no docs on how to re-trigger tasks

**Comment by pcsosinski** [comment]
looks like there are no more pending tasks, all have passed-flaky (for 1.19)

**Comment by godofredoc** [comment]
Vacuum cleaner resets tasks that are in progress for more than an hour back to new. https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/vacuum-clean.dart#L43 but the query for tasks has a hardcoded master branch name.

I manually reset the tasks to new from the datastore but it requires two queries and copy pasting values.

**Comment by keyonghan** [comment]
@godofredoc doc. on how to re-trigger task is listed at the end of https://github.com/flutter/flutter/tree/master/dev/devicelab#tasks

You want to move it to somewhere else?

**Comment by godofredoc** [comment]
I don't think those docs apply to this use case. When a task is already stuck in "in progress" state trying to retry it from the dashboard does not work.

**Comment by keyonghan** [comment]
doc done: cl/318105840
