### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by note8g2018** [flutter/flutter#60050]
I found a bug in flutter framework
```dart
SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.green,
        statusBarIconBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.green,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    );
```
this:
```dart
statusBarIconBrightness: Brightness.dark,
```
does not work, only work 
```dart
statusBarIconBrightness: Brightness.light, 
```
I test it in both my phone and Emulator. Both have Android version: 9
Flutter 1.17.4 • channel stable
Tools • Dart 2.8.4
Android API 28 Platform
***********************************
So when I expect it my Canon R5 to be receive as a gift from Google to find this bug? 😀

**Comment by iapicca** [comment]
Hi @note8g2018 
I see there's an open [issue](https://github.com/flutter/flutter/issues/59130) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
