### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by dotaofll** [flutter/flutter#60055]
# Error report

When i followed the instruction to build my first counter app with vscode.After running the "flutter run" command, an error occurred.

## Logs

The output from 'flutter run --verbose'.

    [  +22 ms] executing: [C:\flutter_windows_1.17.4-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
    [ +106 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
    [   +4 ms] 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
    [   +1 ms] executing: [C:\flutter_windows_1.17.4-stable\flutter/] git tag --contains HEAD
    [ +253 ms] Exit code 0 from: git tag --contains HEAD
    [   +1 ms] 1.17.4
    [  +11 ms] executing: [C:\flutter_windows_1.17.4-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
    [  +87 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
    [   +1 ms] origin/stable
    [        ] executing: [C:\flutter_windows_1.17.4-stable\flutter/] git ls-remote --get-url origin
    [  +83 ms] Exit code 0 from: git ls-remote --get-url origin
    [        ] https://github.com/flutter/flutter.git
    [ +134 ms] executing: [C:\flutter_windows_1.17.4-stable\flutter/] git rev-parse --abbrev-ref HEAD
    [  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
    [   +1 ms] stable
    [  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
    [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [  +29 ms] executing: C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
    [  +52 ms] List of devices attached
            emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:2
    [   +7 ms] C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
    [  +68 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
    [   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [ +530 ms] Generating C:\Users\dotaofll\workspace\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
    [  +37 ms] ro.hardware = ranchu
    [  +36 ms] Using hardware rendering with device sdk gphone x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
    [  +37 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
    [  +14 ms] C:\flutter_windows_1.17.4-stable\flutter\bin\cache\dart-sdk\bin\dart.exe
    C:\flutter_windows_1.17.4-stable\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
    C:\flutter_windows_1.17.4-stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
    -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\dotaofll\AppData\Local\Temp\flutter_tool.66b2126e-b503-11ea-882c-000ec6b80da3\app.dill --packages
    C:\Users\dotaofll\workspace\hello_world\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
    --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
    --track-widget-creation --filesystem-scheme org-dartlang-root
    [  +49 ms] executing: C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
    [  +80 ms] Exit code 0 from: C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
    [        ] --------- beginning of main
            06-23 03:41:21.556 I/MicroDetectionWorker( 2605): #onError(false)
    [  +34 ms] <- compile package:hello_world/main.dart
    [  +28 ms] executing: C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe version
    [  +98 ms] Android Debug Bridge version 1.0.41
            Version 30.0.3-6597393
            Installed as C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe
    [   +3 ms] executing: C:\Users\dotaofll\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
    [  +53 ms] Building APK
    [  +26 ms] Running Gradle task 'assembleDebug'...
    [  +21 ms] gradle.properties already sets `android.enableR8`
    [  +30 ms] Using gradle from C:\Users\dotaofll\workspace\hello_world\android\gradlew.bat.
    [   +7 ms] C:\Users\dotaofll\workspace\hello_world\android\gradlew.bat mode: 33279 rwxrwxrwx.
    [  +34 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
    [ +188 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
    [        ] openjdk version "1.8.0_242-release"
            OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
            OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
    [   +4 ms] executing: [C:\Users\dotaofll\workspace\hello_world\android/] C:\Users\dotaofll\workspace\hello_world\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-
    -Ptarget=C:\Users\dotaofll\workspace\hello_world\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
    [+1114 ms] Welcome to Gradle 5.6.2!
    [   +1 ms] Here are the highlights of this release:
    [   +1 ms]  - Incremental Groovy compilation
    [  +24 ms]  - Groovy compile avoidance
    [   +1 ms]  - Test fixtures for Java projects
    [   +1 ms]  - Manage plugin versions via settings script
    [   +1 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html
    [+225555 ms] FAILURE: Build failed with an exception.
    [   +3 ms] * What went wrong:
    [   +1 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
    [   +2 ms] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.     
    [   +1 ms]    > Could not resolve io.flutter:x86_64_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
    [        ]      Required by:
    [        ]          project :app
    [        ]       > Skipped due to earlier error
    [  +13 ms]       > Skipped due to earlier error
    [        ]       > Skipped due to earlier error
    [        ] * Try:
    [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    [        ] * Get more help at https://help.gradle.org
    [   +1 ms] BUILD FAILED in 3m 46s
    [ +396 ms] Running Gradle task 'assembleDebug'... (completed in 227.4s, longer than expected)
    [   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
    [   +2 ms] "flutter run" took 228,790ms.
    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
    #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
    <asynchronous suspension>
    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
    #3      _rootRunUnary (dart:async/zone.dart:1192:38)
    #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.d18)art:36:15)                                                           future_impl.dart:682:45)
    #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:32):13)
    #11     RunCommand.usageValues (package:flutter_tools/src/commands/ruart:36:15)n.dart)                                                              :13)
    #12     _rootRunUnary (dart:async/zone.dart:1192:38)                 n.dart)
    #13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)                                                                  18)
    #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)future_impl.dart:682:45)                                             :32)
    #16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)                                                                 art:36:15)
    #17     Future._completeWithValue (dart:async/future_impl.dart:526:5):13)
    #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
    #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
    #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
    #21     _rootRunUnary (dart:async/zone.dart:1192:38)
    #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
    #28     _rootRun (dart:async/zone.dart:1184:13)
    #29     _CustomZone.run (dart:async/zone.dart:1077:19)
    #30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5) `

Then i run ```flutter doctor -v```

```
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale zh-CN)
    • Flutter version 1.17.4 at C:\flutter_windows_1.17.4-stable\flutter
    • Framework revision 1ad9baa8b9 (5 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\dotaofll\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\dotaofll\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
How could i solve this bug?Thanks！

**Comment by peter1-pan** [comment]
I have the same bug, can it be solved? Thanks!!

**Comment by iapicca** [comment]
Hi @dotaofll 
I see there's an open [issue](https://github.com/flutter/flutter/issues/58974) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
