### ISSUE TITLE
A problem occurred evaluating root project 'device_info'.

### ISSUE THREAD

**Issue by Kalyanb447-github** [flutter/flutter#60063]
A problem occurred evaluating root project 'device_info'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\Users\kalyan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_info-0.4.2+4\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.6.4-all.zip

**Comment by iapicca** [comment]
Hi @Kalyanb447-github 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by wpJang** [comment]
I have a same problem here.

`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale ko-KR)
    • Flutter version 1.17.5 at /Users/test/Development/flutter/flutter-1.17
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/test/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/test/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • SM G955N • ce04171431bb981d0c                       • android-arm64 • Android 9 (API 28)
    • iPhone8  • c29bac64028f5d4517b6adf95df85d8fc4ac1158 • ios           • iOS 13.5.1

• No issues found!`

**Comment by iapicca** [comment]
Hi @Kalyanb447-github 
could you please provide the info listed [above](https://github.com/flutter/flutter/issues/60063#issuecomment-650025164)
thank you

**Comment by rguntha** [comment]
Any resoultion here?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
