### ISSUE TITLE
TextField calls onSubmitted unexpectedly

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#60074]
Hi, I think I met the problem with undesired submit using flutter web. My case is I have a _TextField_ used for search. When I type something in _TextField_ the cross icon is become visible in _suffixIcon_ (to clear). I **do not do** search and just click the cross icon _to clear_ entered input and _onSubmitted_ is called and search executed!!! But I don't need it! I **do not submit** the text input, I **cancel** it!!
I think this is bug!
P.S. Any ideas to work aroung this?

**Comment by iapicca** [comment]
Hi @bambinoua 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
