### ISSUE TITLE
When trying to compile my app on the flutter 1.17.4...crash!

### ISSUE THREAD

**Issue by leonardoayres** [flutter/flutter#60082]
The error reported:

```
Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path = 'E:\Projetos\ProppyApp.Flutter\.dart_tool\flutter_build\bf60ec93bdc9c98b94a5fa0a3e69d26b' (OS Error: Access is denied.
, errno = 5)".
```

My app was compiling without issues on Flutter 1.17.3.

Any ideas?!

**Comment by iapicca** [comment]
Hi @leonardoayres 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50880) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
