### ISSUE TITLE
Flutter project is not Working in xcode.

### ISSUE THREAD

**Issue by nihang0808** [flutter/flutter#60084]
<img width="1436" alt="Screenshot 2020-06-23 at 4 02 19 PM" src="https://user-images.githubusercontent.com/67319280/85394880-e289d280-b56c-11ea-95f9-bd58a008298e.png">
I tried run my flutter project on xcode but it shows error which shows that operation not permitted.

**Comment by iapicca** [comment]
Hi @nihang0808 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Please refrain from posting pictures if not necessary.
Thank you

**Comment by voonngee** [comment]
Having the same problem. any solution for this

**Comment by voonngee** [comment]
I have solved this by adding Xcode App enough rights to read / write files & folders in machine.

[https://stackoverflow.com/questions/62002151/futter-ios-run-script-xcode-backend-sh-operation-not-permitted/62024788#62024788?newreg=b422dcd3456e461faa54e9f8d6b56607](Follow this link)

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
