### ISSUE TITLE
My flutter web application is not running, I've tried everything.

### ISSUE THREAD

**Issue by jonathanjohn47** [flutter/flutter#60089]
From flutter MASTER, to BETA, to STABLE. I've shifted channels everywhere, but the error I always get while executing `flutter run -d chrome` is:
```
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
18,003ms (!)
Failed to compile application.

```
I've ran `flutter doctor` multiple times, upgraded flutter multiple times. Still the error persists.
Want to see my flutter doctor result? Here it is:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.20.0-1.0.pre.91, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] Connected device (4 available)

! Doctor found issues in 1 category.

```
Want to see my `flutter devices` reslult? Here it is:

```
POCO F1    • 488f7b1    • android-arm64  • Android 9 (API 28)
Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106
Edge       • edge       • web-javascript • Microsoft Edge 83.0.478.54

```

What shall I do?

**Comment by siddhant3030** [comment]
Can you show us what steps you've followed? also, are you on mac?

**Comment by jonathanjohn47** [comment]
I am on Windows.

**Comment by jonathanjohn47** [comment]
> Can you show us what steps you've followed? also, are you on mac?

I just created an app for android phone. But then I wanted to test it out on web after it was established well for android phone. I followed all the traditional steps of 
`flutter channel beta` 
`flutter configure --enable-web`
`flutter upgrade --force`
`flutter run -d chrome`
and it fails to run it on chrome.

I have tried on all other channels as well, not just beta.

**Comment by muj-programmer** [comment]
Could you provide the output of `flutter analyze`

**Comment by jonathanjohn47** [comment]
> Could you provide the output of `flutter analyze`

Ok. There was some weird `import dart.fft` in one of the dart files somewhere. I removed that and it made the connection. But now the problem is that the chrome is giving a blank white screen. I think it requires a different issue, so I'm going to close this now. Thanks for your help everyone.
