### ISSUE TITLE
Cursor blinking causes lots of missed frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6008]
Open Gallery, open the Performance Overlay, go into Expansion Panels. Open "Trip Name". Tap "Trip name" to put the cursor into the text field, which opens the keyboard.

Notice how we're drawing a lot, continually, and missing frames: (tested on a Nexus 5)

(What you see below is the result of just letting the app sit there. It's continually drawing frames.)

![screenshot_20160922-150924](https://cloud.githubusercontent.com/assets/5479/18767956/fdbf25e2-80d6-11e6-8cfd-b13ae85c60e9.png)

**Comment by sethladd** [comment]
cc @dragostis @mpcomplete

**Comment by dragostis** [comment]
I have similar missed frames in the text input demo, but it seems to be a bit worse here.

**Comment by chinmaygarde** [comment]
This is an issue the Skia team might be interested in. We need to give them an SKP of the problematic scene. Can you set the [`rasterizerThreshold`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/performance_overlay.dart#L76) on the [`PerfomanceOverlay`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/performance_overlay.dart#L23) to 3 and paste the trace to this ticket?

**Comment by dragostis** [comment]
@chinmaygarde Here's an SKP. 
[trace_2016-9-23_at_14.55.47.770.skp.zip](https://github.com/flutter/flutter/files/490755/trace_2016-9-23_at_14.55.47.770.skp.zip)

**Comment by abarth** [comment]
@jason-simmons and I looked at this in some detailed and decided it was due to CPU scaling.  The cursor blink frequency is low enough that the device goes into low-power mode and takes time to warm up.  There aren't any visual artifacts from this behavior because it wakes back up if you actually animate anything.

**Comment by sethladd** [comment]
Thanks for looking into this!

What's the advice we can give to developers when they see a perf chart like this, but it's not a big deal? The perf chart is misleading here. Not sure how to interpret it when it's a CPU scaling issue...

**Comment by Hixie** [comment]
It'd be interesting to see how native apps fare in this situation, in case we're missing some magic that the system cursor does.

cc @j9brown who might know.
