### ISSUE TITLE
UI will not update on back button click when a native screen is presented on top of flutter screen

### ISSUE THREAD

**Issue by gangadharashettypj** [flutter/flutter#60095]
**Steps to reproduce**
1. create a flutter app
2. integrate with native iOS using addToApp
3. open native screen
4. open flutter screen on top of native screen

5. now present the native screen and click back in the navigation bar

In the above flow we are unable to perform any actions and in some cases, we can perform action but UI will not get updated. In both cases, UI will be updated when we minimize and open again

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29191792/85435726-855e4300-b5a5-11ea-813c-428598025ab5.gif)

As shown above, the payment screen is presenting on top of the flutter screen, and the order detail screen is pushing, When we come back from the order detail screen, UI is not updating until I minimize and open it again.

**Comment by iapicca** [comment]
Hi @gangadharashettypj 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
