### ISSUE TITLE
CanvasKit crashing when calling Vertices.raw without colors

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#60101]
Calling `Vertices.raw` with `null` colors crashes.

Due to this line: https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/compositor/vertices.dart#L8

Colors should be optional for `Vertices.raw`, we are calling `.length` on the optional color array.

**Comment by MichealReed** [comment]
Could it be the root of https://github.com/flutter/flutter/issues/56938?

**Comment by hterkelsen** [comment]
Fixed in https://github.com/flutter/engine/pull/19172
