### ISSUE TITLE
microbenchmarks MatrixUtils_persp_transformPoint_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60106]
Not high enough yet to be a P0:

![Screen Shot 2020-06-23 at 9 42 39 AM](https://user-images.githubusercontent.com/1435716/85431097-ea7a5000-b535-11ea-8954-864a3c71256f.png)

https://github.com/flutter/flutter/pull/59818 may be the culprit.

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/411272691c28edb76ac77c6b2e99014ead00fc9a

@alexmarkov 

Interestingly I was only able to reproduce the increase in this benchmark's running time when building the engine and running the benchmark from a Mac.  On a Linux host I see the opposite effect - the Dart PR above yields a slight decrease in the benchmark metric.

**Comment by alexmarkov** [comment]
@jason-simmons Could you please add more details about this benchmark: how to run it and reproduce the regression, is it running on the host or on the device, what kind of device was used. If it runs on the device, then did you use the same device on your Linux and Mac hosts?

**Comment by jason-simmons** [comment]
It's a devicelab benchmark (see https://github.com/flutter/flutter/tree/master/dev/devicelab)

It's part of the `microbenchmarks` suite (https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/microbenchmarks.dart)

The task measured by the benchmark runs on the device.  I ran it on the reference Android device model used in the device lab (Moto G4).  However, the Mac and Linux runs used two different Moto G4 devices.

**Comment by alexmarkov** [comment]
Not sure I understand why it could be regressing on one device, but not on another similar device.

I looked at the differences in the ARM disassembly for the following methods which appear in the profile for this benchmark:
```
main
MatrixUtils.transformRect
MatrixUtils.transformPoint
IntegerImplementation._moduloFromInteger
IntegerImplementation.~/
```
They are the same modulo differences in object pool offsets.

There are minor differences in the order of compilation, which may cause different order of executable code of compiled functions in the AOT snapshot. Maybe that caused this regression, but this should be only visible on this kind of tight-loop tiny micro-benchmarks.

**Comment by alexmarkov** [comment]
I'm not sure what we can do about this regression. @mraleph @mkustermann any ideas?

**Comment by mraleph** [comment]
If we don't see any differences in the generated code then I suggest we just rebaseline the benchmark and close this issue.

**Comment by zanderso** [comment]
This was rebaselined.
