### ISSUE TITLE
Distribute engine as Flutter.xcframework

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60109]
Xcode 11 (minimum required version in Flutter) introduced the .xcframework for distributing frameworks for multiple platforms and architectures. At build time, the correct version of the framework is linked on.  An XCFramework is already being used for add-to-app with the `flutter build ios-framework --xcframework` flag.

As Apple is increasing the number of architectures available for each platform (Catalyst as iOS apps on macOS, arm64 macOS) having one bundle containing all available architectures would reduce logic for the tool.  Particularly, no more re-copying the framework into the project when platforms architecture changes (still needs to be done per build mode), and no more `lipo` to remove unused architectures.

As an additional bonus, Flutter.xcframework can be distributed as a Swift Package [as of Xcode 12](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages).  See https://github.com/flutter/flutter/issues/33850#issuecomment-647758430

With https://github.com/flutter/flutter/pull/51453 iOS linking and embedding logic has moved into the tool, so there won't be migration needed for existing projects.

- [x] Update LUCI recipes to create a Flutter.xcframework instead of a Flutter.framework.  Still need them separated for Debug, Profile, and Release.
- [ ] Flutter.podspec would need to change to `s.vendored_frameworks = 'Flutter.xcframework'`
- [ ] Minimum required CocoaPods version in the tool would become [1.9](https://blog.cocoapods.org/CocoaPods-1.9.0-beta/) to handle that vendored xcframework. https://github.com/flutter/flutter/pull/71170

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/36204 for App.xcframework (not dependencies, this work can be done while still generating App.framework).

https://github.com/flutter/flutter/issues/56581 is a dependency to do the same trick for FlutterMacOS.xcframework

**Comment by i-schuetz** [comment]
Just curious, why with Xcode 12 CocoaPods is still needed? What's missing to use only SPM?

**Comment by stuartmorgan** [comment]
> What's missing to use only SPM?

See https://github.com/flutter/flutter/issues/33850

**Comment by jmagman** [comment]
See https://github.com/jmagman/engine/blob/588d6a343bcb5423e89cab15556126416c490c6c/sky/tools/create_ios_framework.py#L71-L79
