### ISSUE TITLE
Oops; flutter has exited unexpectedly. Sending crash report to Google. Crash report sent (report ID: 11cabdb0256da3b3) Crash report written to C:\src\flutter\flutter_02.log; please let us know at https://github.com/flutter/flutter/issues. Process finished with exit code 1

### ISSUE THREAD

**Issue by balighalshamiri** [flutter/flutter#60123]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
@balighalshamiri  you have to post the actual crash repot. closing the issue, please re-file if you are willing to include it
