### ISSUE TITLE
InkWell for CustomPainter widget

### ISSUE THREAD

**Issue by beerline** [flutter/flutter#60143]
Hello, community!
My goal is to have splash on tap only on the red shape.

I draw shape with hole on the left side.
But wen i use `InWell` for getting splash effect on tap, splash color covered whole rectangle. 

I tried different customBorder, but still no result.
 
without splash
![Снимок экрана 2020-06-24 в 01 23 07](https://user-images.githubusercontent.com/7195911/85476795-52be4580-b5b9-11ea-98d7-e81034218e7f.png)

with splash
![Снимок экрана 2020-06-24 в 01 22 53](https://user-images.githubusercontent.com/7195911/85476802-56ea6300-b5b9-11ea-9397-e0ded499647a.png)

<details>
    <summary> example </summary>

    class BuyTicketButton extends StatelessWidget {
      final double cost;
      final Function onTap;

      const BuyTicketButton(this.cost, this.onTap, {Key key}) : super(key: key);

      @override
      Widget build(BuildContext context) {
        return CustomPaint(
          painter: _BuyTicketButtonPainter(context),
          child: SizedBox(
            width: 110,
            height: 36,
            child: InkWell(onTap: onTap,
              child: Align(
                alignment: Alignment.centerRight,
                child: Container(
                  padding: EdgeInsets.only(right: 8),
                  child: Text(
                    'Enter from \n ' + cost.toStringAsFixed(2) + '\$',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 12),
                  ),
                ),
              ),
            ),
          ),
        );
      }
    }

    class _BuyTicketButtonPainter extends CustomPainter {
      final BuildContext context;

      _BuyTicketButtonPainter(this.context);

      @override
      void paint(Canvas canvas, Size size) {
        var _paint = Paint()
          ..style = PaintingStyle.fill
          ..color = Theme
              .of(context)
              .colorScheme
              .secondary
              .withOpacity(0.7)
          ..strokeWidth = 1.0;
        var path = Path();
        path.moveTo(0, 0);
        path.lineTo(size.width, 0);

        path.lineTo(size.width, size.height);

        path.lineTo(0, size.height);

        double diameter = size.height / 3;
        double radius = diameter / 2;

        path.lineTo(0, diameter * 2);
        path.arcToPoint(
          Offset(0, diameter),
          radius: Radius.circular(radius),
          clockwise: false,
        );
        path.lineTo(0, 0);
        canvas.drawPath(path, _paint);
      }

      @override
      bool shouldRepaint(CustomPainter oldDelegate) {
        return false;
      }
    }

</details>

**Comment by iapicca** [comment]
HI @beerline 
[InkWell](https://api.flutter.dev/flutter/material/InkWell-class.html) is by definition

> A rectangular area of a Material that responds to touch.

nevertheless I see as desirable to be able to customize inkwell shape

Thank you

**Comment by HansMuller** [comment]
Have you tried including a parent Material widget that specifies the shape you want?

**Comment by beerline** [comment]
@HansMuller, hi! Thank you for advice!
Yes i tried.
If wrap Material around InWell then component have splash effect even without taping. 
Same behavior if wrap Material around CustomPaint

**Comment by haeseoklee** [comment]
@beerline @iapicca @HansMuller 

It's not a perfect solution, but here's how I did it.

I wrapped the example with a RawMaterialButton. 

Then I set a new shape for it. 

The new shape was defined through CustomBorder (class that inherits OutlinedBorder).

It can effectively limits the scope of the InkWell effect.

![ezgif-2-ae23b2714f27](https://user-images.githubusercontent.com/20268101/90337996-7209aa00-e021-11ea-994d-18636f115f79.gif)


<details><summary>example</summary>

```Dart
import 'package:flutter/material.dart';
import 'custom_border.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(body: Center(child: BuyTicketButton(100.0, ()=>{})))
    );
  }
}

class BuyTicketButton extends StatelessWidget {
  final double cost;
  final Function onTap;

  const BuyTicketButton(this.cost, this.onTap, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return RawMaterialButton(
      shape: CustomBorder(),   // Define the shape of RawMaterialButton with CustomBorder
      onPressed: () => {},
      child: SizedBox(
        width: 110.0,
        height: 36.0,
        child: CustomPaint(
          painter: _BuyTicketButtonPainter(context),
          child: Container(
            padding: EdgeInsets.only(right: 8),
            child: Text(
              'Enter from \n ' + cost.toStringAsFixed(2) + '\$',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 12),
            ),
          ),
        ),
      ),
    );
  }
}


class _BuyTicketButtonPainter extends CustomPainter {
  final BuildContext context;

  _BuyTicketButtonPainter(this.context);

  @override
  void paint(Canvas canvas, Size size) {
    var _paint = Paint()
      ..style = PaintingStyle.fill
      ..color = Theme
          .of(context)
          .colorScheme
          .secondary
          .withOpacity(0.7)
      ..strokeWidth = 1.0;
    var path = Path();
    path.moveTo(0, 0);
    path.lineTo(size.width, 0);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);

    double diameter = size.height / 3;
    double radius = diameter / 2;

    path.lineTo(0, diameter * 2);
    path.arcToPoint(
      Offset(0, diameter),
      radius: Radius.circular(radius),
      clockwise: false,
    );
    path.lineTo(0, 0);
    canvas.drawPath(path, _paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
</details>


<details><summary>solution</summary>

```Dart
import 'package:flutter/material.dart';


class CustomBorder extends OutlinedBorder {

  const CustomBorder({
    BorderSide side = BorderSide.none
  }) : assert(side != null), super(side: side);

  Path customBorderPath(Rect rect) {
    Path path = Path();
    path.moveTo(0, 0);
    path.lineTo(rect.width, 0);
    path.lineTo(rect.width, rect.height);
    path.lineTo(0, rect.height);

    double diameter = rect.height / 3;
    double radius = diameter / 2;

    path.lineTo(0, diameter * 2);
    path.arcToPoint(
      Offset(0, diameter),
      radius: Radius.circular(radius),
      clockwise: false,
    );
    path.lineTo(0, 0);
    return path;
  }


  @override
  OutlinedBorder copyWith({BorderSide side}) {
    return CustomBorder(side: side ?? this.side);
  }

  @override
  EdgeInsetsGeometry get dimensions => EdgeInsets.all(side.width);

  @override
  Path getInnerPath(Rect rect, {TextDirection textDirection}) {
    return customBorderPath(rect);
  }

  @override
  Path getOuterPath(Rect rect, {TextDirection textDirection}) {
    return customBorderPath(rect);
  }

  @override
  void paint(Canvas canvas, Rect rect, {TextDirection textDirection}) {
    switch (side.style) {
      case BorderStyle.none:
        break;
      case BorderStyle.solid:
        canvas.drawPath(customBorderPath(rect), Paint()
          ..style = PaintingStyle.stroke
          ..color = Colors.black
          ..strokeWidth = 1.0
        );
    }
  }

  @override
  ShapeBorder scale(double t) => CustomBorder(side: side.scale(t));

}
```
</details>

**Comment by beerline** [comment]
@haeseoklee, thank you for your solution! It is fits for me

**Comment by beerline** [comment]
this solution work because of opacity.
If using `PaintingStyle.fill` still no ink effect

**Comment by beerline** [comment]
Full correct solution.

Explanation:
We using `RawMaterialButton` with custom shape and path button's color to `RawMaterialButton.fillColor`.
And that it, `RawMaterialButton` handle with Ink effect. 

<details>
    <summary> example </summary>

```Dart

class BuyTicketButton extends StatelessWidget {
  final double cost;
  final Function onTap;
  final bool ticketIsPurchased;
  final String currency;

  const BuyTicketButton(
    this.cost,
    this.onTap, {
    Key key,
    this.ticketIsPurchased = false,
    this.currency,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return RawMaterialButton(
      shape: _CustomBorder(),
      onPressed: onTap,
      fillColor: Colors.blue,
      child: Align(
        alignment: Alignment.centerRight,
        child: Container(
          width: 88,
          height: 36,
          padding: EdgeInsets.only(right: 8, left: 12, top: 2, bottom: 2),
          child: Stack(
            children: [
              Row(
                children: [
                  Expanded(
                    child: Text(
                      ticketIsPurchased
                          ? 'Ticket purchased'
                          : 'Enter from ' + cost.toStringAsFixed(2) + '\$',
                      textAlign: TextAlign.center,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        fontSize: 12,
                        color: ticketIsPurchased
                            ? theme.colorScheme.primary
                            : theme.colorScheme.onPrimary,
                      ),
                    ),
                  ),
                ],
              ),
              ticketIsPurchased
                  ? Icon(
                      Icons.check,
                      color: theme.colorScheme.primary,
                      size: 14,
                    )
                  : Container()
            ],
          ),
        ),
      ),
    );
  }
}

Path _getButtonShape(double width, double height) {
  var path = Path();
  path.moveTo(0, 0);
  path.lineTo(width, 0);
  path.lineTo(width, height);
  path.lineTo(0, height);

  double diameter = height / 3;
  double radius = diameter / 2;

  path.lineTo(0, diameter * 2);
  path.arcToPoint(
    Offset(0, diameter),
    radius: Radius.circular(radius),
    clockwise: false,
  );
  path.lineTo(0, 0);

  return path;
}

class _CustomBorder extends OutlinedBorder {
  const _CustomBorder({BorderSide side = BorderSide.none})
      : assert(side != null),
        super(side: side);

  @override
  OutlinedBorder copyWith({BorderSide side}) {
    return _CustomBorder(side: side ?? this.side);
  }

  @override
  EdgeInsetsGeometry get dimensions => EdgeInsets.all(side.width);

  @override
  Path getInnerPath(Rect rect, {TextDirection textDirection}) {
    return _getButtonShape(rect.width, rect.height);
  }

  @override
  Path getOuterPath(Rect rect, {TextDirection textDirection}) {
    return _getButtonShape(rect.width, rect.height);
  }

  @override
  void paint(Canvas canvas, Rect rect, {TextDirection textDirection}) {
    switch (side.style) {
      case BorderStyle.none:
        break;
      case BorderStyle.solid:
        canvas.drawPath(
            _getButtonShape(rect.width, rect.height),
            Paint()
              ..style = PaintingStyle.stroke
              ..color = Colors.black
              ..strokeWidth = 1.0);
    }
  }

  @override
  ShapeBorder scale(double t) => _CustomBorder(side: side.scale(t));
}
```
</details>
