### ISSUE TITLE
Tap on a text field always places the cursor on word boundary

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#60148]
This happens on web (Mac Chrome browser) at least. But I suspect it's happening on `macOS` native as well (I couldn't get it to work locally). To reproduce:

1. Open https://gallery.flutter.dev/#/demo/text-field
1. Type a few words e.g. "hello world".
1. Tap in the middle of "hello".
1. Notice how the cursor is placed either at the beginning or at the end of "hello".

This behavior is working as intended because that's how iOS places the cursor in text fields. But the behavior is not desirable when using a mouse. Clicking with a mouse should place the cursor exactly where the click occurred, not at the word boundary.

A potential fix would be to change [this code](https://github.com/flutter/flutter/blob/37db92beeb97afb07ac8b316416a6033d013b69b/packages/flutter/lib/src/material/text_field.dart#L95) to check for device kind. If the tap is coming from a mouse, it shouldn't call `selectWordEdge()`.

**Comment by dkwingsmt** [comment]
Is it duplicate to https://github.com/flutter/flutter/issues/37969?

**Comment by mdebbar** [comment]
Ah yes it is. Thanks!
