### ISSUE TITLE
[dashboard] create a staging environment for flutter dashboard

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#60157]
Flutter dashboard has become complex enough that we can't keep pushing directly to prod anymore. Additionally testing several changes require to use production data and production service accounts  that can alter production data in unexpected ways.

We need to create two new projects: flutter-dashboard-dev to be used by devs to push version of non submitted source for validation and flutter-dashboard staging that will be automatically deployed after submitting PRs to cocoon project.

Staging versions can be automatically promoted to prod once per week or more frequently if required.

We can use the following technologies:

* Cloud build for auto deployments.
* Data workflows to migrate prod data to staging.
* Separate github accounts for the services to interact with.

**Comment by godofredoc** [comment]
- [ ] Create project
- [ ] Setup Cloud build for auto deployments.
- [ ] Separate github accounts for the services to interact with.

**Comment by keyonghan** [comment]
Mark `Setup Cloud build for auto deployments` as done.

What has been done:
- Auto-trigger build to `flutter-dashboard-stage` when new commits come in `cocoon/master`.
- version-92bdfcd in [`flutter-dashboard-stage` console](https://pantheon.corp.google.com/appengine/versions?project=flutter-dashboard-stage&serviceId=default) is the one triggered by commit 92bdfcd.

Here are some of my thoughts.
- Use `flutter-dashboard-stage` as the dev version for people to play with.
- Whenever we auto-build a new version to `flutter-dashboard-stage`, we also trigger to build a new version to `flutter-dashboard`. We can have this version in `flutter-dashboard` with a small portion of traffic, say 10%. It will act like the real staging version. If no issue found, then we switch all traffic to this version.

The reason for above proposal is:
- There does not seem to be a way to promote a build version from `flutter-dashboard-stage` project to `flutter-dashboard` project (namely cross different projects). 
- It does not seem to be possible to trigger a build to `flutter-dashboard` with an old commit. (trigger strategy in google cloud build is designed to support up-to-date build based on latest changes in a repo)

With the above said, the workflow is as follows:
- When a new commit comes, it triggers new builds for both `flutter-dashboard-stage` (with `promote` option) and `flutter-dashboard` (with 10% traffic option)
- Play around with `flutter-dashboard-stage` and monitor the 10% traffic of `flutter-dashboard` to detect/fix issues
- If the build is good, promote that version to 100% in `flutter-dashboard`.

**Comment by godofredoc** [comment]
We can define one more environment:

* prod = flutter-dashboard
* staging = flutter-dashboard-staging
* dev = flutter-dashboard-dev

prod will be the one serving our users, staging will be updated and promoted with every submitted change and dev can be used by anyone developing cocoon even with un-submitted changes.

We can also use a branching or tagging mechanism to trigger deployments to prod.

\cc @pcsosinski any suggestions for this workflow?

**Comment by pcsosinski** [comment]
thanks for working on this.

can you make a scenario for how would this staging model have worked with one of the issues we saw earlier in the week?

**Comment by godofredoc** [comment]
@keyonghan the last problem associated with flutter-dashboard release was related to devicelab tasks not getting triggered for a couple of days.

**Comment by keyonghan** [comment]
Using tag is a good idea! I have given it a try, and it seems to work by deploying an old commit.

One question for the staging env.: how shall we determine if a staging version is stable or not? I mean all API calls are still connecting to the prod env., and the staging version does not serve any traffic.

**Comment by CaseyHillers** [comment]
https://flutter-dashboard-dev.appspot.com/#/ is now deployed everytime a commit comes in from flutter/cocoon

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
