### ISSUE TITLE
camera flash and camera info

### ISSUE THREAD

**Issue by azadprajapat** [flutter/flutter#60165]
i need to use flash while capture which are not currently available in camera plugin and device camera info like focal length ,horizontal view angle and vertical view angles

**Comment by iapicca** [comment]
Hi @azadprajapat 
Please follow up on this [issue](https://github.com/flutter/flutter/issues/31225), I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you


https://github.com/flutter/flutter/issues/41785
