### ISSUE TITLE
Input is fragile.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#6016]
It's really easy to make `Input` crash. One without a value or a form crashes when text is selected, without providing any good error reporting.

There have been a few bugs opened the last few days that we should probably reference here.

What we're probably in need of is more asserts with error messages and more detailed documentation with examples.

(Feel free to edit my top-level comment with changes that might be necessary, check boxes, etc.)
- [Input should assert that ancestor is Form when Formfields are used.](https://github.com/flutter/flutter/issues/5505)
- [Input should asserts that either InputValue or FormField is used, not both.](https://github.com/flutter/flutter/issues/6017)
- [Input should either assert or document that InputValue needs to be persistent.](https://github.com/flutter/flutter/issues/6018)

**Comment by abarth** [comment]
See also #6097

**Comment by eseidelGoogle** [comment]
Input got re-written by @mpcomplete at the end of last year, this may be resolved?

**Comment by mpcomplete** [comment]
Yeah I think this and https://github.com/flutter/flutter/issues/6018 were resolved by replacing Input with TextField.
