### ISSUE TITLE
Input should either assert or document that InputValue needs to be persistent.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#6018]
It's currently not obvious that `InputValue`s need to be preserved in a state.

**Comment by abarth** [comment]
See also #6097

**Comment by Hixie** [comment]
I've improved this a bit, will do more in https://github.com/flutter/flutter/pull/6322.

**Comment by Hixie** [comment]
@mpcomplete Can you take a look at this one and see if there's anything more to do?

**Comment by mpcomplete** [comment]
I believe the Input() widget is still confusing. We display text as the user types it, so it can get out of sync with what the Input thinks is happening. For example, if you don't supply a `value`, the hint text will display underneath the user's typed text. If you supply a new InputValue without a selection, the cursor will fight with the user's input.

I'm not sure what the right solution is.

**Comment by eseidelGoogle** [comment]
@mpcomplete says this was resolved by replacing with TextField.
