### ISSUE TITLE
Text Overflow Ellipsis Text not support full option

### ISSUE THREAD

**Issue by beheobong** [flutter/flutter#60182]
![104709477_3233950240019686_5601680020334362655_n](https://user-images.githubusercontent.com/53457593/85517562-9781c500-b629-11ea-98ce-c5f8e05f9193.jpg)
I want show text the same image by native android. Can you support it?

**Comment by iapicca** [comment]
Hi @beheobong 
I see there's an open [issue](https://github.com/flutter/flutter/issues/59540) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
