### ISSUE TITLE
[widget testing] [web]error occurred when [dart:html] in the test source

### ISSUE THREAD

**Issue by nttd-jieyangxu** [flutter/flutter#60181]
From the Web FAQ ,i use the widget testing for web. 
however, when my test source used [dart:html](eg.window.sessionStorage), test result: compilation failed.
when i commentout the  [dart:html](eg.window.sessionStorage),test result : all tests passed!

i know that can't use 'shared_preferences' plugin for flutter_web,but can use localStorage/sessionStorage.

is  [dart:html]  supported  in test SDK ?
How do i test webAPP when  [dart:html] is imported?

※https://github.com/flutter/flutter/issues/35116

**Comment by nttd-jieyangxu** [comment]
pubspec.yaml:
 `dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: 4.1.1
  test_coverage: 0.4.0` 

flutter doctor:
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel flutter-1.19-candidate.1, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.836], locale ja-JP)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

testCode:
    [test.txt](https://github.com/flutter/flutter/files/4823862/test.txt)
test result:  
![failed](https://user-images.githubusercontent.com/62096778/85518073-770a3880-b632-11ea-8395-80e26d6cc26d.png)

![testOK](https://user-images.githubusercontent.com/62096778/85518069-7671a200-b632-11ea-9c65-31acefeb1116.png)

**Comment by iapicca** [comment]
Hi @nttd-jieyangxu 
are you experiencing the issue using [conditional import](https://github.com/flutter/flutter/issues/39998)?
Thank you

**Comment by nttd-jieyangxu** [comment]
import 'dart:html' into source, test that source  ,test failed!  >>> i think yes

**Comment by TahaTesser** [comment]
Hi @nttd-jieyangxu 
Please try targeting platform for web 
Execute `flutter test --platform chrome test/widget_test.dart ` and this passes the test with `import 'dart:html';` [Reference](https://stackoverflow.com/a/59307855)
Thank you

**Comment by nttd-jieyangxu** [comment]
@TahaTesser thank you very much. It didn't work for my case.　↓ 
![testFailedwithPF](https://user-images.githubusercontent.com/62096778/85935834-5d653b80-b927-11ea-914c-973ac85ccdd8.png)

**Comment by nttd-jieyangxu** [comment]
Windows 10: it is confirmed that "flutter test --platform chrome" does not work:
https://github.com/flutter/flutter/issues/44583

**Comment by iapicca** [comment]
Hi @nttd-jieyangxu 
thank's for finding the duplicate I failed to spot
Please follow up on that [issue](https://github.com/flutter/flutter/issues/44583), I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by nttd-jieyangxu** [comment]
i give up [dart:html]
i use [import 'package:universal_html/prefer_universal/html.dart']　test is successed.

※https://pub.dev/packages/universal_html
