### ISSUE TITLE
iOS iPhone XR webview_flutter scroll bar exception

### ISSUE THREAD

**Issue by Tecode** [flutter/flutter#60188]
## Steps to Reproduce

1. Open flutter webview page.
2. Play video and exit full screen, scroll view.

**Expected results:** 

![exception.gif](https://github.com/Tecode/dynamic_theme/blob/master/assets/preview/webview_bug.gif?raw=true)

**Actual results:** 
Scroll bar to the right.

## Info

**Flutter --version**

```bash

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (3 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

```

**My code**

```dart
WebView(
  initialUrl: 'https://www-pre.naoxuejia.com/questionsList/6',
  javascriptMode: JavascriptMode.unrestricted,
  onWebViewCreated: (WebViewController webViewController) {},
  javascriptChannels: <JavascriptChannel>[].toSet(),
  navigationDelegate: (NavigationRequest request) {
    return NavigationDecision.navigate;
    },
    onPageFinished: (String url) {},
  )
```

**iOS version**

```bash

Software version: 13.3.1
Model Name: iPhone XR

```

**webview_flutter**

```
0.3.15+1
```

**[Test url](https://www-pre.naoxuejia.com/questionsList/6)**

```html
https://www-pre.naoxuejia.com/questionsList/6
```

**Comment by iapicca** [comment]
Hi @Tecode  
this issue should be [fixed](https://github.com/flutter/flutter/issues/41592#issuecomment-573261075)
can you please update the plugin to the latest version. 
If the issue persists, please provide your updated `pubspec.yaml`, 
your `flutter run --verbose`, 
and a minimal reproducible code sample.
Thank you

**Comment by Tecode** [comment]
@iapicca  I solved this problem after upgrading the  webview_flutter plugin 0.3.22+1.
Thank you
