### ISSUE TITLE
Shadow bug on iPhone devices

### ISSUE THREAD

**Issue by AndriiHanets** [flutter/flutter#60180]
Trying to add shadows to container. Got some unexpected shadow artifacts only on real devices iPhone X, Xs, Xs max. Using iOS 13.4.1 and 13.5.1 got same behaviour. On simulators bug is not reproducing. Also tested in iPhone 8 and iPhone 11, everything is working properly. 

## Steps to Reproduce
 ```dart
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromRGBO(227, 237, 247, 1),
      body: Center(
        child: Container(
          margin: EdgeInsets.only(left: 30, right: 30),
          height: 50,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(9),
            color: Color.fromRGBO(227, 237, 247, 1),
            boxShadow: [
              BoxShadow(
                  spreadRadius: 0,
                  blurRadius: 4,
                  offset: Offset(4, 4),
                  color: Colors.black.withOpacity(0.16)),
              BoxShadow(
                  spreadRadius: 0,
                  blurRadius: 4,
                  offset: -Offset(4, 4),
                  color: Colors.white),
            ],
          ),
          child: Center(
            child: Text(
              'Test',
              style: TextStyle(
                  color: Colors.red, fontSize: 20, fontWeight: FontWeight.w700),
              textAlign: TextAlign.center,
            ),
          ),
        ),
      ),
    );
  }
```

**Expected results:** 

<a href="https://www.upload.ee/image/11920284/photo_2020-06-24_10-24-56.jpg"><img src="https://www.upload.ee/thumb/11920284/photo_2020-06-24_10-24-56.jpg" border="0" alt="photo_2020-06-24_10-24-56.jpg" /></a>

**Actual results:** 

<a href="https://www.upload.ee/image/11920282/photo_2020-06-24_10-19-39.jpg"><img src="https://www.upload.ee/thumb/11920282/photo_2020-06-24_10-19-39.jpg" border="0" alt="photo_2020-06-24_10-19-39.jpg" /></a>

**Comment by iapicca** [comment]
Hi @AndriiHanets 
Can you please provide your `flutter doctor -v`.
Thank you

**Comment by AndriiHanets** [comment]
Hi @iapicca

**Comment by AndriiHanets** [comment]
Hi @iapicca 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.184, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.184 at /Users/andriihanets/Development/flutter
    • Framework revision 61b93d25bb (6 hours ago), 2020-06-24 01:53:01 -0400
    • Engine revision 2a9fed87a7
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 6b630c3719)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andriihanets/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (2 available)            
    • Andrii’s iPhone • 00008030-000409D236C0802E            • ios • iOS 13.5.1
    • iPhone Xs       • C724B17C-6116-4E22-A86F-A57BEB66C105 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by TahaTesser** [comment]
Hi @AndriiHanets 

Just tried on latest master

![Simulator Screen Shot - iPhone 11 - 2020-06-25 at 15 58 39](https://user-images.githubusercontent.com/48603081/85703464-02e89700-b6fd-11ea-8020-69f494ae7c31.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromRGBO(227, 237, 247, 1),
      body: Center(
        child: Container(
          margin: EdgeInsets.only(left: 30, right: 30),
          height: 50,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(9),
            color: Color.fromRGBO(227, 237, 247, 1),
            boxShadow: [
              BoxShadow(
                  spreadRadius: 0,
                  blurRadius: 4,
                  offset: Offset(4, 4),
                  color: Colors.black.withOpacity(0.16)),
              BoxShadow(
                  spreadRadius: 0,
                  blurRadius: 4,
                  offset: -Offset(4, 4),
                  color: Colors.white),
            ],
          ),
          child: Center(
            child: Text(
              'Test',
              style: TextStyle(
                  color: Colors.red, fontSize: 20, fontWeight: FontWeight.w700),
              textAlign: TextAlign.center,
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.208, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-1.0.pre.208 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision c68758fab1 (6 hours ago), 2020-06-24 21:23:02 -0700
    • Engine revision 0c14126211
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • SM M305F      • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.5.1
    • iPhone 11     • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS desktop • macos                                • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details>

**Comment by AndriiHanets** [comment]
Reinstalling and updating flutter sdk fixed this issue
