### ISSUE TITLE
iOS 14 beta crash

### ISSUE THREAD

**Issue by kakanote** [flutter/flutter#60186]
ios14beta crash

ios14bata download link : https://www.ios14beta.com/ios-14-beta-download-direct-links-ipsw/

**Comment by didiao11300** [comment]
same question occoured

**Comment by kakanote** [comment]
Please help me resolve it

**Comment by iapicca** [comment]
Hi @didiao11300 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and your `pubspec.yaml`.
Thank you

**Comment by kakanote** [comment]
![image](https://user-images.githubusercontent.com/54585809/85550274-ff94d300-b64a-11ea-951a-7e154b9385d2.png)
@iapicca

**Comment by JohnSnooow** [comment]
i am facing same issue, Any solution

**Comment by HenryQuan** [comment]
I have similar issues on my device, iPhone 6s. However, it seems that only debug builds are crashing. I have an app installed in release mode and it is working fine. It was installed about 3 months ago. I haven't actually rebuilt any of them and they were all installed before the update.

**Comment by TahaTesser** [comment]
Hi @kakanote  @didiao11300  @JohnSnooow @HenryQuan 
Please upgrade to Xcode 12 for iOS 14 support 
https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes/

<img width="756" alt="Screenshot 2020-06-25 at 4 27 52 PM" src="https://user-images.githubusercontent.com/48603081/85707529-e64e5e00-b700-11ea-8111-d5a5214464b9.png">


Note: It's Xcode 12 isn't fully supported yet https://github.com/flutter/flutter/issues/60133
