### ISSUE TITLE
Syncing files to device (This is taking an unexpectedly long time.) 

### ISSUE THREAD

**Issue by humazed** [flutter/flutter#60192]
## Steps to Reproduce

1. install the lasted flutter stable
2. flutter create myapp
3.  cd myapp
4. flutter run
5. R

getting
`Performing hot restart... (This is taking an unexpectedly long time.)`

another error is happening on projects which is more complex than simple hello world application with some packages, I'm getting:
`Syncing files to device (This is taking an unexpectedly long time.) `

For some reason changing the name of the flutter SDK folder fixes it, I changed it from `flutter` to `_flutter`

here is the SOF question for reference:
https://stackoverflow.com/questions/62552355/syncing-files-to-device-this-is-taking-an-unexpectedly-long-time/62552356#62552356

```bash
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.17.4 at D:\AS\_flutter
    • Framework revision 1ad9baa8b9 (7 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\AS\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Users\Dell\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\Dell\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8405
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @humazed 
`This is taking an unexpectedly long time.` is not an error and I'd hardly consider it a warning
the build / rebuild time might depend from your machine performance among other settings,
also `r` and `R` are different operation with the latter being more expansive.
Could you please run `flutter run -v` from terminal and try both` hot reload` and `hot restart`
this should show if the operation takes unusually long.

Thank you

**Comment by humazed** [comment]
the hot restart takes on average 2.5 min, and it was taking before 1-2 seconds, so it's not related to my machine.

**Comment by TahaTesser** [comment]
Hi @humazed 
Are you experiencing same delay with hot reload as well?
https://github.com/flutter/flutter/issues/59170
Thank you

**Comment by humazed** [comment]
No, hot reload might be slow if there is a big code change, but it always happens with hot restart and cold start. and as I said it also happening with the counter application.

**Comment by TahaTesser** [comment]
Hi @humazed 
Can you please upgrade latest `dev` channel and try again?
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by Olivia2008** [comment]
Today i upgrade flutter version to the latest one, it still takes long time when i flutter run again. 
Seems is about gradle's problem. I don't know what i shoud do.

PS E:\projects\flutter_app\netease_news> **flutter doctor -v**
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...                                   1.9s
Downloading flutter_patched_sdk tools...                            7.8s
Downloading flutter_patched_sdk_product tools...                    8.0s
Downloading windows-x64 tools...                                   19.3s
Downloading windows-x64/font-subset tools...                        2.3s
Downloading android-arm-profile/windows-x64 tools...                1.3s
Downloading android-arm-release/windows-x64 tools...                1.2s
Downloading android-arm64-profile/windows-x64 tools...              1.6s
Downloading android-arm64-release/windows-x64 tools...              1.5s
Downloading android-x64-profile/windows-x64 tools...                1.7s
Downloading android-x64-release/windows-x64 tools...                1.9s
[√] Flutter (Channel dev, 1.20.0-2.0.pre, on Microsoft Windows [Version 10.0.18362.900], locale zh-CN)
    • Flutter version 1.20.0-2.0.pre at C:\Flutter
    • Framework revision 15a28159bc (8 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\wu\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\wu\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\wu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

PS E:\projects\flutter_app\netease_news> **flutter run**
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
(**This is taking an unexpectedly long time**.)       |
..................
Syncing files to device Android SDK built for x86...            **30,576ms** (!)

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by tim-teacher** [comment]
Have the same issue with last stable release..... Before everything was fine.

**Comment by tim-teacher** [comment]
this issue, is not resolved and should not be closed.

**Comment by iapicca** [comment]
@tim-teacher please note the [last answer](https://github.com/flutter/flutter/issues/60192#issuecomment-662513902)
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.
