### ISSUE TITLE
Flutter Easier If statement and more etc

### ISSUE THREAD

**Issue by filip123** [flutter/flutter#60191]
I would like an easier way to do if statement like this etc:

I would like to tag any widget like this

You see the Name:"", part that does not exist in dart that's the thing I want.

```dart
Text(
     "A Text",
    Name: "Text1",
),
```

And now that I have named the TextName property Text1 now I can do

```dart
FlatButton(
                color: Colors.red,
                child:  Text("Button" ),
                onPressed: () {
                if (Text1.Color == Colors.red)
                {
                  Text1.Color = Colors.green;
                 }
              ),
```

 like it is in C#     it would be so much easier than having to deal with the current stuff

**Comment by iapicca** [comment]
Hi @filip123 
I believe what you are trying to implement could be achievable in many ways
simply extending a class, implementing an abstract class (sort of interface from C# perspective) 
or with a mixin (that C# doesn't have);
changing how dart implements classes might seem a very big change,
but feel free to advance your proposal on [dart's githib repo](https://github.com/dart-lang/sdk/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
