### ISSUE TITLE
Flutter Web Twitter Sign In Failure: Error: MissingPluginException(No implementation found for method authorize on channel com.roughike/flutter_twitter_login)

### ISSUE THREAD

**Issue by AlraziBashir** [flutter/flutter#60201]
I am attempting to create a Twitter Sign In Button for my Flutter Web APP using the flutter_twitter plugin since the flutter_twitter_login is deprecated and contains many issues. 

Here is my error :
`Error: MissingPluginException(No implementation found for method authorize on channel
com.roughike/flutter_twitter_login)
    at Object.throw_ [as throw] (http://localhost:62884/dart_sdk.js:4463:11)
    at MethodChannel._invokeMethod
    (http://localhost:62884/packages/flutter/src/services/platform_channel.dart.lib.js:409:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:62884/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:62884/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:62884/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:62884/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:62884/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:62884/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62884/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:62884/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:62884/dart_sdk.js:37296:13)
    at http://localhost:62884/dart_sdk.js:32918:9`

This is the twitter login Button:
`import 'package:flutter/material.dart';
import 'package:flutter_twitter/flutter_twitter.dart';

class TwitterSignInButton extends StatelessWidget {
  void _signInTwitter() async {
    var twitterLogin = new TwitterLogin(
      consumerKey: 'DNgiahPDsqjROp8Ke',
      consumerSecret: 'mQU1gCPuOnrCrym431ltSP',
    );

    final TwitterLoginResult result = await twitterLogin.authorize();

    switch (result.status) {
      case TwitterLoginStatus.loggedIn:
        var session = result.session;
        print('successful sign in: ${session.username}');
//        _sendTokenAndSecretToServer(session.token, session.secret);
        break;
      case TwitterLoginStatus.cancelledByUser:
//        _showCancelMessage();
        print('cancelled by user');
        break;
      case TwitterLoginStatus.error:
        print(result.errorMessage);
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ClipRRect(
        borderRadius: BorderRadius.circular(5.0),
        child: Stack(
          children: [
            Container(
              height: 50,
              width: 410,
              child: RaisedButton(
                onPressed: _signInTwitter,
                elevation: 16,
                color: Colors.blue,
                shape: new RoundedRectangleBorder(
                    borderRadius: new BorderRadius.circular(6)),
                padding: EdgeInsets.all(4),
                child: Text(
                  'Continue With Twitter',
                  style: TextStyle(
                    fontSize: 16,
                    color: Colors.white,
                    letterSpacing: .5,
                    fontFamily: 'Montserrat Bold',
                  ),
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(13),
              child: Image.asset('assets/TwitterLogo.png'),
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by stuartmorgan** [comment]
Bugs and feature requests for plugins need to be reported to the authors of the plugin. You should file this at https://github.com/roughike/flutter_twitter_login

**Comment by AladMocu** [comment]
This issue still present today and that plugging is listed as requirement on the docs: https://firebase.flutter.dev/docs/auth/social#twitter .

**Comment by isauro-am** [comment]
I solved it using
1.- flutter clean
2.- flutter pub cache repair
and creating a new mobile emulator
works also for flutter_facebook_login: ^3.0.0
