### ISSUE TITLE
Installing a flutter apk on Pixel C w/ Nougat takes 40+ seconds

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6020]
```
12:32:28.701: 41499 ms • <redacted>/android-sdk-linux/platform-tools/adb -s <redacted> install -r build/app.apk
```

It used to take less than 10. (before I upgraded my device to Nougat).

**Comment by chinmaygarde** [comment]
What is the size of the APK being installed? I have been testing on Nougat for the past week and haven't seen any regression. Also, are you using the Android SDK in third_party or using your own?

**Comment by apwilson** [comment]
14.7MB

**Comment by apwilson** [comment]
My own sdk

**Comment by apwilson** [comment]
Where is this third party one?

**Comment by chinmaygarde** [comment]
Sorry. I assumed you were using the engine repository. In the engine, it is at `third_party/android_tools/sdk/platform-tools`. Currently, we use `Android Debug Bridge version 1.0.32`. Maybe we need to recommend updating the SDK if we think certain versions are slow for Nougat.

**Comment by apwilson** [comment]
What parts of an android sdk are needed to use flutter?  Just built/platform tools or does it need all those system images?

**Comment by chinmaygarde** [comment]
https://flutter.io/setup/#android-setup

We need the SDK as well as the tools for building the APK.

**Comment by chinmaygarde** [comment]
What does `adb version` version say on your machine?

**Comment by apwilson** [comment]
Android Debug Bridge version 1.0.36

**Comment by chinmaygarde** [comment]
Damn, thats actually newer than the one I am using. Lets try `export ADB_TRACE=all` and see where it is stuck/slow.

**Comment by apwilson** [comment]
Working with Chinmay offline we found his 6P was fine with my setup so it appears to be somethign specific about my Pixel C.

**Comment by apwilson** [comment]
fwiw, I discovered that if I uninstall the app before installing the new one this issue went away.

**Comment by eseidelGoogle** [comment]
@apwilson Doesn't `flutter run` uninstall for you?
