### ISSUE TITLE
Update android setup instructions to indicate how a user can use an existing android sdk for flutter

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6021]
Flutter doesn't need Android Studio
Flutter only needs the latest Android SDK and the latest build and platform tools.  No system images or anything else.

If ANDROID_HOME is set it'll use that.

**Comment by eseidelGoogle** [comment]
@qchong.  If I remember correctly, @abarth also has mentioned plans to change `flutter create` and `flutter build apk` on android to sit on top of gradel which might change this requirement?

**Comment by abarth** [comment]
Correct.  We plan to require bits from Android Studio in the future, which is why the instructions are written this way.
