### ISSUE TITLE
Fix top five flake devicelab tests to help unblock the tree

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#60217]
It is not uncommon that flutter tree gets closed due to flake tests failures. 

Over the past two months, flake tests percentage increased to over 5% for a couple of times, and May/June flake percentage (mean) doubled the number of Apr.
<img width="476" alt="Screen Shot 2020-06-24 at 10 32 28 AM" src="https://user-images.githubusercontent.com/54558023/85604370-18c76080-b606-11ea-9c1e-74b364dd4b5e.png">

It would help a lot if the team can help address the top flake tests. Top five are listed below (Number of Flake is based on same time period as the above chart: Apr 1 - Jun 24).
<img width="633" alt="Screen Shot 2020-06-24 at 10 32 59 AM" src="https://user-images.githubusercontent.com/54558023/85605036-b28f0d80-b606-11ea-9cb9-16d57a60d2a7.png">

**Comment by christopherfujino** [comment]
Cross referencing an issue I filed on `flutter_gallery_ios32__transition_perf` https://github.com/flutter/flutter/issues/60559

**Comment by keyonghan** [comment]
Related issue: https://github.com/flutter/flutter/issues/57754

**Comment by liyuqian** [comment]
@keyonghan : is there a link to the web page that shows the content of your screenshot above? I'm interested in knowing if those top 5 flaky issues get updated over time.

**Comment by keyonghan** [comment]
> @keyonghan : is there a link to the web page that shows the content of your screenshot above? I'm interested in knowing if those top 5 flaky issues get updated over time.

Here is the [dashboard](https://datastudio.google.com/c/reporting/1o_27AedMBxv-sa_HE78BMWff7uhPglj9/page/dwwAB). Yes, it refreshes over time.

**Comment by jmagman** [comment]
This is a moving target, the top 5 referenced in the description are no longer in the top 10 (for Nov 14-Jan 14, same time period as in description).

<img width="986" alt="Screen Shot 2021-01-15 at 3 15 52 PM" src="https://user-images.githubusercontent.com/682784/104787558-a5717180-5744-11eb-9370-60d567815cb4.png">



1. animated_placeholder was deleted with #74062
2. multi_widget_construction_perf__timeline_summary was deleted in #73986
3. Filed issue for fast_scroll_large_images__memory https://github.com/flutter/flutter/issues/74085
4. Most of the large_image_changer_perf_ios flakes I saw were https://github.com/flutter/flutter/issues/72144 (just fixed) but I also saw a few cases of https://github.com/flutter/flutter/issues/65413.
5. I see no large_image_changer_perf_android flakes in the last few weeks, so maybe that one is also already fixed.

**Comment by jmagman** [comment]
@keyonghan Can we close this now that we have a flaky test process?
