### ISSUE TITLE
`flutter create -t plugin` should not create no-op iOS folders in 1.20.0 stable release

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#60215]
When 1.20 releases, we should make `flutter create -t plugin` command not creating no-op iOS folders anymore.
Also, we will add a lower flutter SDK bound setting to 1.20.0 for all the newly created plugins. 

Ideally, we'd like to land this change to the 1.20.0 release branch as it goes out.

**Comment by jmagman** [comment]
Pending cherry pick at https://github.com/flutter/flutter/pull/62372

**Comment by pcsosinski** [comment]
@cyanglaz what's your plan for testing this once we have it on-branch (but before we release it as 1.20.0)?

**Comment by cyanglaz** [comment]
@pcsosinski 
We have unit tests covering the "removing no-op ios" folder bit.
For 1.20.0 lower constraint, we will need to add similar unit tests.

**Comment by cyanglaz** [comment]
Fixed by https://github.com/flutter/flutter/pull/62990
