### ISSUE TITLE
[flutter_tools] FileSystemUtils will use real FileSystem in test, not test override.

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#60220]
For example: https://github.com/flutter/flutter/pull/60172#pullrequestreview-436890237

**Comment by jonahwilliams** [comment]
One possible way this could happen is that the FsUtils is created outside of the overriding test zone and then passed to the class under test. Thus the override applies too late.

**Comment by christopherfujino** [comment]
> One possible way this could happen is that the FsUtils is created outside of the overriding test zone and then passed to the class under test. Thus the override applies too late.

Should we remove the constructor-time injection, then? Using globals would grab from the context at runtime, right?

**Comment by jonahwilliams** [comment]
> Should we remove the constructor-time injection

no way

**Comment by jonahwilliams** [comment]
The problem here is that the combination of Zones + laziness (final, statics) make our code difficult to understand. With constructor injection, the type can't change out from under us, though that doesn't necessarily help if the test still makes heavy usage of zones.

**Comment by jonahwilliams** [comment]
Fixed this particular case by removing the default implementation of FileSystemUtils
