### ISSUE TITLE
Flutter Project Causing Entire System To Lagg Severely. 

### ISSUE THREAD

**Issue by Inclemental-55** [flutter/flutter#60229]
## Steps to Reproduce

 I installed flutter SDK on my PC at work via android studio's "install flutter sdk" button, and booted a fresh flutter project inside of android studio 4.0. Immediately my entire system seems to freeze, as if there is a massive memory leak. It spends literal minutes "Analyzing". Anytime I boot a flutter project, the system comes to a halt, and again immediately solves itself if android studio is closed.

It's certainly not a system resources issue, I've been doing android studio development with java for months on this computer with no issues. Task Manager also shows no excessive memory or CPU usage.  

## Logs

flutter doctor -v:

[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.17763.1282], locale en-US)
    • Flutter version 1.19.0-4.1.pre at C:\flutter
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\timothy.bender\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • moto g 7 play • ZY326NQKG7 • android-arm • Android 9 (API 28)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @TimothyBender 
Please check your system resources when running the app and try switching to stable channel or dev channel
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
