### ISSUE TITLE
Cannot use back camera on iPhone 11  Error -11852

### ISSUE THREAD

**Issue by brxxxx** [flutter/flutter#60236]
I am unable to select the back facing camera on an iPhone 11. I am using camera version ^0.5.8+2

When I try to use the back camera I get the error:

`Error -11852 "Cannot use Back Camera"`

My code works on all other iPhones, only having this problem on iPhone 11.

Here is the output of availableCameras() and also some other device info that i collected using the device_info package.

![Image](https://user-images.githubusercontent.com/66548748/85624809-aa7daf00-b694-11ea-9b99-c6a1d9f23d14.jpeg)

**Comment by TahaTesser** [comment]
Hi @brxxxx 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

Are you experiencing same issue as https://github.com/flutter/flutter/issues/59964?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
