### ISSUE TITLE
Google Sign In Cannot Proceed In Flutter Web

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#60259]
Hi, i had worked before integrating Google Sign In in web frameworks. This is my first time trying to do it for Flutter Web.

Based on the instructions in https://pub.dev/packages/google_sign_in_web the only thing to add is a web client id as a meta tag in index.html of the web folder in the flutter project.

Once the web is deployed, and i enter the username, i get this message.

```
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

But i already added the localhost+port to the authorized domains. and yes, the port is fixed. 

In the rub tab, i see this one though:
Debug service listening on ws://127.0.0.1:49385/5PE6HwqyMFE=

Or Could it be the url that flutter generates is http://localhost:7357/#/ with a hash? I doubt it though but im out of ideas.

Thoughts?

**Comment by TahaTesser** [comment]
Hi @chitgoks 
Please execute `flutter run -d chrome --web-hostname localhost --web-port 7357` from root of your app then copy then local host address `http://localhost:7357/#/` (do not close launched chrome window, keep it open) and  run it from your chrome installed on your computer and you will be able login with no issues 

Chrome window launched by flutter isn't identified as secure but you can use same localhost while app is running, it will be easy to login from default browser

Thank you

**Comment by chitgoks** [comment]
thank you. i have confirmed it now works

**Comment by stefandevo** [comment]
@chitgoks @TahaTesser Could you explain how you got this to work?
I still have this issue.
I am running the `flutter run -d chrome --web-hostname localhost --web-port 7357` command from command line; this starts a Chrome browser window. In this window, I get the error.
If I start a new Chrome window, same applies.
In Safari I can continue, but need to debug stuff, and need the login data in the browser to continue, so Chrome is what I need to continue. Any suggestions?

**Comment by TahaTesser** [comment]
@chitgoks 
Have you whitelisted this localhost port  in your google console?

<img width="452" alt="Screenshot 2020-07-08 at 9 20 34 PM" src="https://user-images.githubusercontent.com/48603081/86941038-149c5680-c161-11ea-9fa1-22a5870868f8.png">


Please check [Web integration](https://pub.dev/packages/google_sign_in_web#web-integration)

**Comment by stefandevo** [comment]
Yes I certainly did; I can perfectly run this on localhost on my Safari browser without any problems.

**Comment by TahaTesser** [comment]
You need to keep localhost chrome window open and launch Chrome that you've installed your desktop and run same localhost

**Comment by stefandevo** [comment]
> launch Chrome that you've installed your computer and run same localhost

I am not sure what you mean by this. The chrome window starts from terminal or VSCode, ok, but then I launch a new Chrome window, but that gives me no difference (running in Mac Os btw)

**Comment by TahaTesser** [comment]
@stefandevo 
Not that one, it's default Chrome window that you normally use for browsing. I have tested it, no issues

**Comment by stefandevo** [comment]
What works is, close all browser windows, Open a new Chrome window, the start the debug session. Then I can use the Google Sign in the previous openen Chrome window. Of course debugging does not work, and the cookies/storage are written in the original window of course, not in the debug window. 
So basically I have same behavior as I have with a separate Safari window.

**Comment by TahaTesser** [comment]
@stefandevo 
Could you please create a new issues, maybe we need better documentation for debugging for `google_sign_in` on web 
Thank you

**Comment by josepaulodelacruz** [comment]
I Have this issue, no debug print statements are shown.

please reference me to the new issue created.

**Comment by chitgoks** [comment]
im not making a new issue since this is already solved. maybe the documentation does need to have some more info detailing this.

**Comment by stefandevo** [comment]
https://github.com/flutter/flutter/issues/61155

@chitgoks its not solved in my opinion.

**Comment by purplecandy** [comment]
The method mentioned did work but after that, I wasn't able to perform hot reload or restart
It keeps giving me this error. So basically either I first create the entire app assuming that what I have written is correct and we all know how that turns out or it's a complete dead end for now. 
```
Performing hot restart...                                              ⣻
Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure>
(package:dwds/src/handlers/dev_handler.dart:272:13)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#4      _BufferingStreamSubscription._sendData
(dart:async/stream_impl.dart:357:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#7      _PendingEvents.schedule.<anonymous closure>
(dart:async/stream_impl.dart:687:7)
#8      _rootRun (dart:async/zone.dart:1182:47)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by ammaratef45** [comment]
> --web-hostname localhost --web-port 7357

Don't you think this is an issue that needs to be solved? that would increase the development speed a little bit.

**Comment by diver2** [comment]
wow, I'm still stuck on this... this is bad code

**Comment by diver2** [comment]
I tried everything in this thread and others (I even changed the port to 7357 thinking it could be some magic), tried all the browsers, nothing.
Error during Google Sign In - Assertion failed: code !=null is not true
file:///Users/xxx/dev/flutter_beta/packages/flutter/lib/src/services/message_codec.dart:111:15

(means PlatformException comes, but code is null)

Google sign in works with firebase 7.3.2. So, I abandoned the plugin.
I also had problems with google sign in routine (without the web)

````
Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64,
    locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/xxxx/dev/flutter_beta
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/xxxx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM G920F (mobile)        • 06157df6c54bcd08          • android-arm64  •
      Android 7.0 (API 24)
    • xxxxx iPhone (mobile) • 00008030-001C090E1A43802E • ios            •
      iOS 13.6.1
    • Web Server (web)         • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)             • chrome                    • web-javascript •
      Google Chrome 86.0.4240.183
```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by stefandevo** [comment]
@TahaTesser It is all related to the specific Google account itself. Exact same works for other accounts; if I use it with my @gmail.com account, it does not work; if I use an account of my company (also google mail in the end) it works.
