### ISSUE TITLE
setState() called after dispose in fadeinimage

### ISSUE THREAD

**Issue by devakrishna33** [flutter/flutter#60268]
## Steps to Reproduce

`
ListView.builder(
           itemCount: articles.length,
            itemBuilder: (context, index) {
              final article = articles[index];
              return FadeInImage.assetNetwork(
                 image: article["image"]
                 placeholder: "assets/placeholder.jpg",
                 imageErrorBuilder: (_, __, ___) => Icon(Icons.error),
             );
           },
);
`
**Actual results:** 
When scrolling through the listview it causes the following error:
setState() called after dispose(): _ImageState#be7e8(lifecycle state: defunct, not mounted, stream: ImageStream#739ef(MultiFrameImageStreamCompleter#3107c, [1920×3417] @ 1.0x, 3 listeners), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)

And it shows the error icon, instead of images, the reason for the issue might be that the listview is unmounting the component but the setstate in fadeinimage is getting called, it would be great if someone could help me with this.

**Comment by devakrishna33** [comment]
For anyone facing similar issues use cached_network_image instead of fadeinimage

**Comment by VladyslavBondarenko** [comment]
Hi @devakrishna33 
could you provide your `flutter doctor -v` and a complete reproducible code sample?
I can't reproduce it with this code on current dev `1.20.0-1.0.pre`
<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: ListView.builder(
          itemCount: 3,
          itemBuilder: (context, index) {
            return FadeInImage.assetNetwork(
              placeholder: 'assets/flutter-logo.png',
              image: 'https://p.bigstockphoto.com/GeFvQkBbSLaMdpKXF1Zv_bigstock-Aerial-View-Of-Blue-Lakes-And--227291596.jpg',
              imageErrorBuilder: (_, __, ___) => Icon(Icons.error),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

**Comment by guyo13** [comment]
facing a similar issue, but error only happens after I hot restart the app.

**Comment by VladyslavBondarenko** [comment]
@guyo13 
I tried to do hot restarts with https://github.com/flutter/flutter/issues/60268#issuecomment-649517285, master `1.20.0-8.0.pre.125`, but can't reproduce.
what flutter version do you use? can you hit the error with mentioned code sample?

**Comment by guyo13** [comment]
Hi @VladyslavBondarenko 
I am using Flutter version 1.17.5 and Dart 2.8.4, my code has a similar usage to the example above.
I will post a more complete code sample hopefully this weekend if I make it.

Will also try with `1.20.0-8.0.pre.125` and post my result.

Thanks!

**Comment by guyo13** [comment]
I can confirm using flutter version `1.21.0-1.0.pre` and executing `flutter clean` before running, the error no longer occurs.
I also created a demo project - https://github.com/guyo13/flutter-FadeInImage-demo

If running with flutter version `1.17.5` the error occurs on both the demo project and my main project so it's probably an issue with that release. Make sure to run `flutter clean` if you previously ran the application with the older version of flutter, otherwise you will still get the error!

**Comment by imran-samed** [comment]
I have created new issue
add added more details ,Please check

https://github.com/flutter/flutter/issues/63456#issue-676597978
