### ISSUE TITLE
Changing code breaks Non-nullable on Hot reload / Hot restart. Error: Required named parameter '$creationLocationd_0dea112b090073317d4' must be provided

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#60269]
Trying to hot reload with null safety enabled, throws the following error when trying to hot reload or hot restart after a change in Flutter web:

```
Error: Required named parameter '$creationLocationd_0dea112b090073317d4' must be provided.
```

Even though in reality, the constructor is empty.

This error occurs for a few of my widgets, however, not for all of them (always the same ones):

```
Error: Required named parameter '$creationLocationd_0dea112b090073317d4' must be provided.
            const SomeWidget(),
                               ^
Context: Found this candidate, but the arguments don't match.
  const SomeWidget(Key? key}) : super(key: key);
        ^^^^^^^^^^^^^
```

## Steps to Reproduce

1. Run `flutter run --enable-experiment=non-nullable --no-sound-null-safety -d chrome`.
2. Hot reload
3. Or hot restart

Actually, I cannot rebuild the application at all before running `flutter clean`.

## Version

Flutter version is:

```
Channel master, 1.20.0-1.0.pre.208
```

**Comment by VladyslavBondarenko** [comment]
Hi @creativecreatorormaybenot 
I can't see the error when running the command with `master, 1.20.0-1.0.pre.208`.
Does it reproduce with any device? any app (with default counter)?
Could you provide your `flutter doctor -v`?

**Comment by creativecreatorormaybenot** [comment]
@VladyslavBondarenko It happens for me every time I change code and the error is printed for many constructors.

Note that I am using `({Key? key})` constructors for widgets to support null safety.

**Comment by VladyslavBondarenko** [comment]
@creativecreatorormaybenot 
<details>
 <summary>I tried with this code sample</summary>

```
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title = 'title'}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

</details>

With master `1.20.0-1.0.pre.208` and with current master `1.20.0-1.0.pre.222`, but I can't see the error (tried with `--verbose` as well).
Could you edit the code to reproduce it? or can you see the error with this code?

**Comment by creativecreatorormaybenot** [comment]
@VladyslavBondarenko It happens in a large proprietary, so it is hard to find a reproducible example.

I finally accomplished to create a reproducible example ❤ Really hope this can be addressed now. I am not sure what is required, but after making example apps for a while, I finally encounter the bug.

OK, here are the full steps to reproduce for me:

```
Flutter channel master, 1.20.0-1.0.pre.217, on Microsoft Windows
Dart version 2.9.0 (build 2.9.0-19.0.dev a9bef090e8)
```

## Steps

0. Android Studio → New Flutter Project → Flutter Application
0. Project name: `flutter_app`
0. Create `analysis_options.yaml`:

```yaml
analyzer:
  enable-experiment:
    - non-nullable
```

3. Add `sdk` constraint:

```yaml
environment:
  sdk: ">=2.9.0-19.0.dev <3.0.0"
```

4. Pub get
4. Rerun Dart analysis → make sure that `key` and `title` in the constructor are reported as errors (non-nullable)
4. Replace the content of `main.dart` with the following:

<details>

```dart
import 'package:flutter/material.dart';
import 'package:flutterapp/widgets/one.dart';
import 'package:flutterapp/widgets/two.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late bool _enabled;

  @override
  void initState() {
    super.initState();

    _enabled = false;
  }

  Future<void> _handleChange(bool value) async {
    setState(() {
      _enabled = value;
    });
  }

  Widget buildContent() {
    return InkWell(
      onTap: () => _handleChange(!_enabled),
      child: Padding(
        padding: const EdgeInsets.symmetric(
          vertical: 8,
          horizontal: 16,
        ),
        child: Row(
          children: [
            Text('Some'),
            Text('Text'),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            buildContent(),
            const Divider(
              thickness: 1,
              height: 1,
            ),
            Expanded(
              child: _enabled ? const One() : const Two(),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

7. Create three files in `lib/widgets`: `one.dart`, `two.dart`, and `three.dart` → fill them with the following three snippets:

<details>

### One

```dart
import 'package:flutter/material.dart';

class One extends StatelessWidget {
  const One({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DropdownButtonHideUnderline(
      child: DropdownButton<String>(
        value: '1',
        onChanged: (value) {
          Null;
        },
        items: [
          for (var i = 0; i < 7; i++)
            DropdownMenuItem(
              value: '$i',
              child: Text(
                i.toString().toUpperCase(),
                style: Theme.of(context).textTheme.bodyText1.copyWith(
                      color: Theme.of(context).toggleableActiveColor,
                      fontWeight: FontWeight.bold,
                    ),
              ),
            ),
        ],
      ),
    );
  }
}

```

### Two

```dart
import 'package:flutter/material.dart';
import 'package:flutterapp/widgets/one.dart';
import 'package:flutterapp/widgets/three.dart';

class Two extends StatelessWidget {
  const Two({Key? key}) : super(key: key);

  Future<void> _addDialog(BuildContext context) async {
    final String? result = await showDialog<String?>(
      context: context,
      useRootNavigator: false,
      builder: (context) {
        return SimpleDialog(
          children: [
            Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 8,
                  horizontal: 16,
                ),
                child: IconButton(
                  onPressed: Navigator.of(context).pop,
                  icon: const Icon(Icons.notifications_none),
                )),
          ],
        );
      },
    );

    if (result == null) return;
  }

  @override
  Widget build(BuildContext context) {
    return DragTarget<int>(
      onWillAccept: (data) {
        return true;
      },
      onAccept: (data) {
        return;
      },
      builder: (context, candidateData, rejectedData) {
        return InkWell(
          onTap: () => _addDialog(context),
          child: Stack(
            children: [
              const Three(),
              const ColoredBox(
                color: Colors.blueAccent,
              ),
              const One(),
            ],
          ),
        );
      },
    );
  }
}

```

### Three

```dart
import 'package:flutter/material.dart';

class Three extends StatefulWidget {
  const Three({
    Key? key,
    this.delay = const Duration(),
  }) : super(key: key);
  final Duration delay;

  @override
  State createState() => _ThreeState();
}

class _ThreeState extends State<Three> {
  late bool _entered = false;

  void _onEnter(_) {
    setState(() {
      _entered = true;
    });

    Future.delayed(widget.delay, () {
      setState(() {
        _entered = false;
      });
    });
  }

  void _onExit(_) {
    setState(() {
      _entered = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: _onEnter,
      onExit: _onExit,
      child: Text('... what is this widget tree $_entered'),
    );
  }
}

```

</details>

8. Run the following command: `flutter run --enable-experiment=non-nullable --no-sound-null-safety -d chrome`
8. Change the following lines with the ones following that (`main.dart` 42):

```dart
            Text('Some'),
            Text('Text'),
```

```dart
            Text('See'),
            Text('The'),
            Text('Bug'),
```

10. Hot reload
10. I see the following error:

<details>

```
lib/main.dart:64:42: Error: Required named parameter '$creationLocationd_0dea112b090073317d4' must be provided.
              child: _enabled ? const One() : const Two(),
                                         ^
lib/widgets/one.dart:4:9: Context: Found this candidate, but the arguments don't match.
  const One({Key? key}) : super(key: key);
        ^^^
lib/main.dart:64:56: Error: Required named parameter '$creationLocationd_0dea112b090073317d4' must be provided.
              child: _enabled ? const One() : const Two(),
                                                       ^
lib/widgets/two.dart:6:9: Context: Found this candidate, but the arguments don't match.
  const Two({Key? key}) : super(key: key);
        ^^^
Performing hot restart...                                           99ms
Try again after fixing the above error(s).
```

</details>

12. Cannot build the app until I run `flutter clean`.

**Comment by VladyslavBondarenko** [comment]
@creativecreatorormaybenot 
thanks for the reproducing steps!
I'm changing the title, because I'm experiencing this with Android 9 (API 28) and iOS 13.5 (simulator) as well. Tried with `master 1.20.0-3.0.pre.78`

**Comment by jensjoha** [comment]
> /cc @jensjoha - potentially seems like another interaction between widget location transformer and internal CFE state? CFE should not be able to see artificial parameters introduced by the transformer, unless its internal state is restored from the Kernel binary (which does not seem like a correct thing to do?).

I haven't looked into this (yet), but
* internal state _is_ restored from kernel binary, and it *is* the right thing to do. Other transformations for instance removes fields and replaces them with something else. If CFEs internal state doesn't reflect this we cannot produce correct code.
* even if we didn't do the above, we can initialize from a previous compiles dill file.

As I said, I haven't looked into the specifics here yet though.

/cc @johnniwinther who might also have input.

**Comment by mraleph** [comment]
> If CFEs internal state doesn't reflect this we cannot produce correct code.

Imagine:

```
class A {
  const A();
}
```

gets transformed into 

```
class A {
  final someArtificialField;
  A(this.someArtificialField);
}
```

this is a fine transformation as long as transformer also globally inserts a value into each constructor call. 

However if you restore CFE state from the dill which contains transformed code then users will starts seeing errors asking them to add missing value - which is not something they can, because `someArtificialField` was created by the transformer. 

I guess things can be made to work if you use named parameters and make sure that you use nullable types for those parameters (and don't make them required) - I guess you could say that the actual bug is in the widget transformer not respecting this requirement.

In some sense this just high-lights inherent leakiness of transformer abstraction.

**Comment by johnniwinther** [comment]
For this case it should be enough to change the type of the synthesized location parameter to `Location?` instead of `Location` - actually this is even necessary to make the transformed code valid since non-nullable named parameters must either have a default value (which is doesn't) or be required (which it isn't).

I'll update the transformer accordingly.

**Comment by creativecreatorormaybenot** [comment]
@johnniwinther So you know why this happens? Is it a trivial fix or will it take some time?

**Comment by johnniwinther** [comment]
I have a fix in the pipeline: https://dart-review.googlesource.com/c/sdk/+/153085

**Comment by creativecreatorormaybenot** [comment]
@johnniwinther Is there anything blocking the fix? I am just curious, no pressure 😄

**Comment by johnniwinther** [comment]
Waiting for a review from something knowledge of the widget transformer design. Summer time reviews are a bit slower than usual due to vacations.

**Comment by flukejones** [comment]
Just noticed that flutter widget tests break in a similar fashion, does this PR also fix this?

**Comment by flukejones** [comment]
Another note (sorry for extreme lack of detail, I'm trying to work to a deadline as well). The following causes the same errors:

```
class JteIcon extends StatelessWidget {
  const JteIcon({required this.path, this.size = 30, this.color});
```

While this doesn't:

```
class JteIcon extends StatelessWidget {
  JteIcon({required this.path, this.size = 30, this.color});
```

This is nested in another group of widgets.

**Comment by johnniwinther** [comment]
Hmm. I get the same error (prior to the fix) for both const and non-const constructors.

**Comment by flukejones** [comment]
Sorry about the lack of detail or any way to generate a repeatable case. I was trying to zip through a few things to get a build happen at that seemed to be one of the blockers - I didn't in any way test thoroughly.

Is there an easy way for me to get flutter using the dart master so I can check my cases a bit better with the fix?

**Comment by johnniwinther** [comment]
>  Is there an easy way for me to get flutter using the dart master so I can check my cases a bit better with the fix?

I actually don't know how to do that. @jonahwilliams do you how/if this can be done?

**Comment by jonahwilliams** [comment]
It looks like the last change rolled into the engine as https://github.com/flutter/engine/pull/19838 . I would expect this to roll into the framework some time today - you can always get to the latest flutter with `flutter channel master` and `flutter upgrade`.

If you want to build flutter with an arbitrary dart commit, you would need to follow the engine development guide in contributing.md. This is a bit more involved, so it might be easier to wait for it to roll in.

**Comment by flukejones** [comment]
Very cool, got the update now and it looks like all the issues I had were solved nicely :heart:

**Comment by jonahwilliams** [comment]
@creativecreatorormaybenot if you would confirm too I will mark this issue as fixed. Thanks for the fix @johnniwinther

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Yess, it works 🎉

This is such a time save; thanks @johnniwinther.
