### ISSUE TITLE
Flutter - Disk Full Error

### ISSUE THREAD

**Issue by anchalssquare** [flutter/flutter#60262]
I'm running into an issue where my macbook pro, with over 220G free, gets Disk Full Error after running Flutter for 3 to 4 hour or so. It increase the size the Other folder in mac by 100 or 200 mb every minute.

See the image : https://lh3.googleusercontent.com/-hDEKaptfk2U/XvH_y7xCw4I/AAAAAAAAApg/s5Ws_R-KN5IcfAm1Yrxvy_jA-N4PQ9K8ACK8BGAsYHg/s0/2020-06-23.jpg

I actually ran into this issue about a week ago. When the problem happens and the disk runs full, my system slows down so much I can hardly do a thing. To free up disk space and get operational again quickly, and just restart the laptop. It's a frustrating productivity killer.

    I am using the latest flutter
    flutter doctor reports everything as fine
    xcrun --find simctl is fine
    Using Android studio 3.6.3
    Latest patched Catalina 10.15.4

This morning I opened the Android Studio IDE with an ios device connected. I opened a get info window on my hard drive and left it open. Then I did nothing but watch the info window. No builds or anything. Over the course of a couple minutes, I watched 7 GB disappear.I shut down the IDE and the loss stopped.

I have set my iphone's auto-lock to never. So, my iphone is always awake during development.

Everything works fine when I am not using flutter.

**Comment by VladyslavBondarenko** [comment]
Hi @anchalssquare 
could you provide your `flutter doctor -v`?
is https://github.com/flutter/flutter/issues/56826 your case?

**Comment by anchalssquare** [comment]
After running flutter doctor -v 

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-IN)
    • Flutter version 1.17.1 at /Users/modern/Library/FlutterSdk/flutter
    • Framework revision f7a6a7906b (6 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/modern/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 740C7325-CB4E-4572-9A74-82A8EEBB7C6A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
```

Yes, #56826 is same the issue I am facing.

**Comment by VladyslavBondarenko** [comment]
@anchalssquare 
Upgrade to the current stable 1.17.4, it's fixed there.
Please comment if it's not so and I'll reopen

**Comment by anchalssquare** [comment]
I have updated it to current stable 1.17.4 but it is not fixed. As soon as I connected my iphone to android studio it starts filling the disk again.

**Comment by VladyslavBondarenko** [comment]
@jmagman tagging you to take a look, is something extra should be done after upgrade?

**Comment by jmagman** [comment]
What's filling your disk, exactly?  What directory is blowing up?  Does a reboot clear it out?

**Comment by zhangweiwei0326** [comment]
Also this problem, connected cell phones will appear, full hard disk will be occupied, after restarting the computer garbage station will have about 40 g of files.

**Comment by jmagman** [comment]
@zhangweiwei0326 
> What's filling your disk, exactly? What directory is blowing up?

**Comment by zhangweiwei0326** [comment]
> @zhangweiwei0326
> 
> > What's filling your disk, exactly? What directory is blowing up?
> 
> Also, what Flutter version are you on?

flutter 1.17.3

open xcode, Then the real machine debugging is normal.

**Comment by jmagman** [comment]
@zhangweiwei0326 the fix is in 1.17.4.

**Comment by TahaTesser** [comment]
@anchalssquare 
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by anchals333** [comment]
@jmagman and @TahaTesser  

Updating the flutter version didn't help me. I followed this answer: https://apple.stackexchange.com/questions/387634/temporary-dyld-shared-cache-taking-a-lot-of-space/387843#387843 and  the issue was fixed.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
