### ISSUE TITLE
Running Flutter in AOT mode for Embedded Devices

### ISSUE THREAD

**Issue by limbouser** [flutter/flutter#60276]
I am trying to run a Flutter application using @chinmaygarde flutter_wayland on Raspberry Pi(ARM) platform , I have used a modified version of the same (@jwinarske https://github.com/jwinarske/flutter_wayland/pull/1) which has included support for AOT builds. 

In order to create the necessary binaries, I created flutter-engine for both host(linux) and target(ARM) with                                       
    `--runtime-mode release` flags, generated app.dill and libapp.so The steps I used were : 
```
flutter-engine-host/src/out/host_debug_unopt/dart  \
          flutter-engine-host/src/out/host_debug_unopt/frontend_server.dart.snapshot \
          --sdk-root flutter-engine-host/out/host_debug_unopt/flutter_patched_sdk/  \
          --aot --tfa --target=flutter --output-dill build/linux_arm/app.dill lib/main.dart
```

```
`flutter-engine-arm/git-r0/git/src/out/linux_release_arm/clang_x64/gen_snapshot --deterministic  \
           --snapshot_kind=app-aot-elf --elf=libapp.so --strip app.dill`
```

This is ouput I get when I invoke gen_snapshot
`Dart VM version: 2.9.0-edge.flutter-a69cb6d (be) (Fri Apr 24 11:49:43 2020 +0000) on "linux_simarm"`

So I have libapp.so and app.dill generated now, so how should I run the flutter_wayland from now on, what all further changes do I need to make. Normally I used to run `flutter_wayland flutter_assets` with output of running `flutter build bundle` in app directory. How should I change the packaging of arguement passed to flutter_wayland?

**Comment by TahaTesser** [comment]
Added `will need additional triage` because the issue seems about modified version of `flutter_wayland`

**Comment by stuartmorgan** [comment]
Custom embedding AOT configuration is documented at https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode.

**Comment by limbouser** [comment]
Yh, I did go through the same but I was confused on what all arguments to pass to flutter_wayland instead of flutter_assets and that's why I raised the issue.

**Comment by stuartmorgan** [comment]
`flutter_wayland` isn't part of the Flutter project, so if your question is about `flutter_wayland` APIs rather than the embedder API, this project isn't the right place to file an issue.
