### ISSUE TITLE
TextFormField Toolbar has a weird border shadow

### ISSUE THREAD

**Issue by adeolaex** [flutter/flutter#60290]
This might be old but is there a reason why the toolbar has this weird border shadow ?

I attached two screenshots showing the toolbar on a native app(Gmail) and a flutter app with the same colour theme.

[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
• Flutter version 1.20.0-1.0.pre.132 at /Users/adeola/Downloads/flutter
• Framework revision 5995661 (5 days ago), 2020-06-19 16:15:58 -0700
• Engine revision 676cd566f7
• Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
• Android SDK at /Users/adeola/Library/Android/sdk
• Platform android-30, build-tools 30.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.5, Build version 11E608c
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 46.0.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
• iPhone • 7301a50cae9aaf2e903ef313e632bfed64bb3704 • ios • iOS 13.4

Steps to reproduce.
1. Create new flutter project
2.Place this minimal code in the main.dart
`import 'package:flutter/material.dart';`
`void main() {
  runApp(MyApp());
}`
`class MyApp extends StatelessWidget {`
`@override`
` Widget build(BuildContext context) {`
`return MaterialApp(`
` title: 'Flutter Demo',`
`home: Scaffold(`
`   backgroundColor: Color(0xFF17181A),`
`  body: Center(`
`    child: TextFormField(),`
` ),`
` ),`
` );`
`  }`
`}`

3. Run flutter run --release on a real IOS device as this only occurs on a real device and not a simulator.

![IMG_8904](https://user-images.githubusercontent.com/42682873/85752912-18b18880-b70c-11ea-8fe3-d6b30b5c7ccc.PNG)
![IMG_8906](https://user-images.githubusercontent.com/42682873/85752925-1a7b4c00-b70c-11ea-80ce-f86a9ec5c16f.PNG)

**Comment by adeolaex** [comment]
@justinmc

**Comment by VladyslavBondarenko** [comment]
Hi @adeolaex 
does it persist with current master `1.20.0-1.0.pre.208`?
can you see it on simulator or on iOS 13.5 device? 
I tried with iOS 13.5 simulator and can't see the border shadow with current beta, dev and master channels

**Comment by adeolaex** [comment]
Hey @VladyslavBondarenko . For some reason I also can't see it on a simulator but it's clear as day on a real device running 13.5.
I noticed it on flutter's master version `1.20.0-1.0.pre.132` , upgraded flutter and I can still see it on the current master `1.20.0-1.0.pre.208`

**Comment by VladyslavBondarenko** [comment]
I can't see the border shadow when running with current master `1.20.0-1.0.pre.220` and current beta `1.19.0-4.2.pre` on iPhone 7 iOS 13.5

**Comment by adeolaex** [comment]
> I can't see the border shadow when running with current master `1.20.0-1.0.pre.220` and current beta `1.19.0-4.2.pre` on iPhone 7 iOS 13.5

Interesting. I hope you added the back coloraturas `backgroundColor: Color(0xFF17181A),` to the app.
