### ISSUE TITLE
Hint text is not visible with FloatingLabelBehavior.always

### ISSUE THREAD

**Issue by BigBrosh** [flutter/flutter#60292]
@justinmc 
As mentioned in #30664 I'm expecting hint text to be visible with FloatingLabelBehavior.always and hintText provided

**Comment by justinmc** [comment]
Example app: https://dartpad.dartlang.org/ac99026caecbd2824f8ec57b7ce20da4

The hint is shown only when the field is focused, but I believe it should be shown either way.

**Comment by VladyslavBondarenko** [comment]
I didn't notice a duplicate - https://github.com/flutter/flutter/issues/53753 - needs to be closed as well when fixed

**Comment by justinmc** [comment]
Thanks!  I added that issue to the PR.
