### ISSUE TITLE
Deactivating Dismissable does not remove its backgrounds?

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6030]
When deactivating dismissable onDismissed, the background(a stateless widget) is left there. Is this the intended behavior for dismissable widget? Is there anyway to remove the background?

**Comment by abarth** [comment]
Would you be willing to edit the bug report to explain a bit more about the trouble you're running into?

**Comment by eseidelGoogle** [comment]
The bug report got edited (sadly Github does that silently).  I don't quite have context to answer, but @Hixie might.

**Comment by Hixie** [comment]
I'd have to see the code. This doesn't happen in the demo we have that uses dismissable.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/leave_behind_demo.dart  <--- is the demo @Hixie is talking about.

**Comment by Hixie** [comment]
This is not actionable without some code to look at. Please open a new bug if you would like us to take a look.
