### ISSUE TITLE
compute function with plugins that use native platform code

### ISSUE THREAD

**Issue by elmissouri16** [flutter/flutter#60307]
on the [documentation](https://flutter.dev/docs/cookbook/networking/background-parsing#4-move-this-work-to-a-separate-isolate) they are the only example of how to use compute with an only pure dart code, will be better if there also docs of how to use compute with platform native code,  I'm working on an app that's require some [video processing  ](https://pub.dev/packages/video_compress)  and its jank my Ui, I did some research  and I find nothing related to it, having docs for it will be great

**Comment by iapicca** [comment]
Hi @elmissouri16 
if I'm correct, `compute` is essentially syntactic sugar on `dart`'s `isolate` 
that requires the running function to be `top level` or `static`
I believe it's not meant for native code (kotlin can definitely run coroutines, swift not yet asaik)

for a possible feature request on dart isolates you may want to head to [dart's github repo](https://github.com/dart-lang/sdk/issues)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by elmissouri16** [comment]
@iapicca thanks for the reply , I understand , and what's is the approach to do such thing in flutter now if it supported

**Comment by iapicca** [comment]
Hi again @elmissouri16 
this is a good [example](https://youtu.be/qrFTt1NZed8) for [isolates](https://api.dart.dev/stable/2.8.4/dart-isolate/dart-isolate-library.html) 
[compute](https://api.flutter.dev/flutter/foundation/compute.html) is largely the same, just easier to use.
To achieve multithreading on native functions
you may want to look on sources external to Flutter ([ios](https://hackernoon.com/swift-multi-threading-using-gcd-for-beginners-2581b7aa21cb), [android](https://kotlinlang.org/docs/reference/native/concurrency.html))
thank you
