### ISSUE TITLE
How to get size of the drawn image in actual logical pixels?

### ISSUE THREAD

**Issue by mbostic** [flutter/flutter#60303]
I have posted a question [here](https://stackoverflow.com/questions/62554827/how-to-get-size-of-the-drawn-image-in-actual-logical-pixels), but got no response. Can you help me with this problem?

**Comment by iapicca** [comment]
Hi @mbostic 
This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
I see you already opened a SO question.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
