### ISSUE TITLE
AN HTTP REQUEST DOES NOT WORK WITH FLUTTER

### ISSUE THREAD

**Issue by mauriciocontrole** [flutter/flutter#60305]
I just want to do a request with GET in Flutter to my ASP .NET.

```dart
    try {
      //var uriResponse = await client.get('https://viacep.com.br/ws/04005020/json/'); // THIS WORK
      var uriResponse = await client.get('https://10.0.2.2:5001/WeatherForecast'); // THIS DON'T WORK
      print(uriResponse.body.toString());
    }


    finally {
      client.close();
    }

```

And I have this problem:

```bash
E/flutter (30329): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (30329): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

```

I tried this request GET with a browser and it's work perfectly, but not with Flutter.

Someone can hep, please ?

**Comment by iapicca** [comment]
Hi @mauriciocontrole 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50699) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
