### ISSUE TITLE
Document how to use SkSL-based shader warmup

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#60313]

**Comment by joniaiuser** [comment]
Hi @liyuqian , this may be a stupid question but I was wondering whether shaders have to be recompiled each time a new app is built? For example if between 2 versions of my app there was only very minimal changes to the code, do I still need to re-run shader compilation or can I use shaders generated from the previous build?

Thank you.

**Comment by liyuqian** [comment]
You can of course use the old ones: in the worst case they just don't accelerate your app, but they shouldn't cause any troubles.

However, we recommend writing some performance tests to
1. Verify if your current SkSL assets make your app fast enough, or if new SkSL assets need to be generated.
2. Automatically generate new SkSL assets whenever your app or Flutter updates.

Here's [an example][1] of how we did the test in the Flutter repo.

[1]: https://github.com/flutter/flutter/blob/51fa704642774c6b6ae64c91642b62801e233e1b/dev/devicelab/lib/tasks/perf_tests.dart#L118

**Comment by suztomo** [comment]
In the documentation, there's a section on the limitation on "newer iOS devices". The term "newer" is obscure. (Is my iPhone 2020 part of it?) I cannot tell whether I should try this document.

https://flutter.dev/docs/perf/rendering/shader#limitations-and-considerations

**Comment by yaminet1024** [comment]
@liyuqian  I want to know how to use --cache-sksl  and  build aar/ios-framework with --bundle-sksl-path on an existing app，It Jank heavy every time app reinstall , it's import for me thanks.

**Comment by subzero911** [comment]
Is it possible to write several driver tests, run all of them at once and capture several SkSL caches and add all of them into compiled app?

**Comment by ronytesler** [comment]
here: https://flutter.dev/docs/perf/rendering/shader you say: f there’s an urgent need for fixing shader compilation jank on newer iPhones, please leave feedback on Issue 61045, and we can help you turn on OpenGL for your app.
How can I leave a feedback on 61045 if the conversation is locked?
Is it still possible to "turn on OpenGL for my app"?
