### ISSUE TITLE
iOS performance

### ISSUE THREAD

**Issue by gprog** [flutter/flutter#60315]
first time building any screen is janking especially on low end devices 5s, 6 (on new devices too even iPhone x). but second time is normal and smoothing. and child of PageView/ListView. too.

**Comment by iapicca** [comment]
Hi @gprog 
please make sure that you are following [performances best practices](https://flutter.dev/docs/perf/rendering/best-practices) and [optimisation](https://youtu.be/vVg9It7cOfY) 
keeping in mind the substantial performance difference between `debug` and `release`.

If the issue persists please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by Ufuk94** [comment]
I think this is related to #32170. There is a solution that works for Android, but it doesn't work for iOS devices using Metal: https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up

I hope this gets fixed soon.

**Comment by YoussefGheith** [comment]
same for me 
even I’m  using iPhone 11 pro with release mode 
Same app works very smooth on android

**Comment by bluemix** [comment]
I am having the same performance issues on iOS. Ot works very smooth on Android, but there is noticible lag on iOS release builds

**Comment by adeolaex** [comment]
@bluemix Any iPhone with the A6 chip has Metal built in. Flutter just switched to Metal but the Skia engine only supports OpenGL. (for now hopefully).

**Comment by iapicca** [comment]
Hi @YoussefGheith, @bluemix and @adeolaex 
could you please provide your `flutter doctor -v`
and a minimal reproducible code sample

Thanks to @Ufuk94 for pointing this [issue](https://github.com/flutter/flutter/issues/32170)!

Does running your app with [--cache-sksl](https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up) improve your experience?
Thank you

**Comment by Ufuk94** [comment]
@iapicca 
> Does running your app with [--cache-sksl](https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up) improve your experience?

It helped a lot in my app. Here is a non-scientific comparison:

With shader warm-up: https://gfycat.com/scarydistincthart
And without: https://gfycat.com/perkyqueasygentoopenguin

Unfortunately this doesn't work with iOS and Metal, as mentioned in the documentation.

**Comment by adeolaex** [comment]
> Hi @YoussefGheith, @bluemix and @adeolaex
> could you please provide your `flutter doctor -v`
> and a minimal reproducible code sample
> 
> Thanks to @Ufuk94 for pointing this [issue](https://github.com/flutter/flutter/issues/32170)!
> 
> Does running your app with [--cache-sksl](https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up) improve your experience?
> Thank you

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.4 at /Users/adeola/Downloads/flutter
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/adeola/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.6, Build version 11N700h
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone • 7301a50cae9aaf2e903ef313e632bfed64bb3704 • ios • iOS 13.6

• No issues found!


Yes of course,  running an app with `--cache-sksl` helps alot on Android but not so much on IOS.

**Comment by YoussefGheith** [comment]
There you go :

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/youssefgheith/flutter
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by YoussefGheith** [comment]
Here is a code sample . noting fancy here . 
I’m  using Flutter Staggered Animations package to show Staggered list animation 
Most of the time the animation is laggy during the first run especially when reopening the app and later becomes more smoother
The Hero animations is bit laggy too.

`Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          const SizedBox(height: 100),
          const _Label(),
          const SizedBox(height: 20),
          Expanded(
            child: AnimationLimiter(
              child: ListView.builder(
                shrinkWrap: true,
                itemCount: options.length,
                itemBuilder: (BuildContext context, int index) {
                  return AnimationConfiguration.staggeredList(
                    duration: const Duration(milliseconds: 375),
                    position: index,
                    child: SlideAnimation(
                      horizontalOffset:  50,
                      child: FadeInAnimation(
                        child: Padding(
                          padding: const EdgeInsets.symmetric(
                              vertical: 20, horizontal: 20),
                          child: Material(
                            color: const Color(0xFF262626),
                            child: RadioListTile<CheckOutType>(
                              activeColor: Colors.greenAccent,
                              title: Text(
                                options[index],
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                  letterSpacing: 0.4,
                                ),
                                overflow: TextOverflow.ellipsis,
                              ),
                              groupValue: _selectedOption,
                              onChanged: (CheckOutType value) {
                                setState(() {
                                  _selectedOption = value;
                                });
                              },
                              value: CheckOutType.values[index],
                            ),
                          ),
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
          ),
        ],
      ),
    );
`

**Comment by bluemix** [comment]
```logs
[✓] Flutter (Channel master, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-3.0.pre at /Users/bluemix/flutter
    • Framework revision 61b93d25bb (12 days ago), 2020-06-24 01:53:01 -0400
    • Engine revision 2a9fed87a7
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 6b630c3719)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bluemix/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] Connected device (5 available)
    • HTC 10           • FA65LBN02816                             • android-arm64  • Android 8.0.0 (API 26)
    • blueMix’s iPhone • b728690ea736b79265dec3f4bf09eb57e516b516 • ios            • iOS 13.5.1
    • macOS desktop    • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server       • web-server                               • web-javascript • Flutter Tools
    • Chrome           • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 1 category.

```

> Does running your app with [--cache-sksl](https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up) improve your experience?

On iOS, It did not, no effects at all.
Thanks in advance.

**Comment by iapicca** [comment]
Hi @YoussefGheith @adeolaex @bluemix 
thank you for your doctor, 
as mentioned [above](https://github.com/flutter/flutter/issues/60315#issuecomment-654147733) could you please provide a reproducible minimal code sample
Thank you

**Comment by iapicca** [comment]
Hi @bluemix @YoussefGheith @adeolaex 
thank you for your doctor, as mentioned [above](https://github.com/flutter/flutter/issues/60315#issuecomment-651006800)
could you please provide a minimal **reproducible** code sample,
it should be runnable and not a snipped from production,
also please make sure that does not involve 3rd party plugin
and if contains 1st party packages please make sure it is the latest version.
Thank you

**Comment by vegidio** [comment]
I'm having the same problem. The same app is very smooth on Android but very slow on iOS.

**Comment by iapicca** [comment]
Hi @vegidio
can you please provide the information listed [above](https://github.com/flutter/flutter/issues/60315#issuecomment-651006800)
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 1232209** [comment]
same problem！

**Comment by 1232209** [comment]
Any one have new infomation?
