### ISSUE TITLE
spinning_mixed shows that spinner doesn't rotate when in a rotational transform

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6032]
offshoot from https://github.com/flutter/flutter/issues/406

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this bug?  Unclear if it should bare the regression keyword?

**Comment by chinmaygarde** [comment]
Is this still an issue? Not clear what needs to be done here.

**Comment by Hixie** [comment]
To see if it's still an issue, run the spinning_mixed demo and see if the spinner rotates.

**Comment by chinmaygarde** [comment]
> To see if it's still an issue, run the spinning_mixed demo and see if the spinner rotates.

It does. Closing.
