### ISSUE TITLE
Container has different shape with and without color property.

### ISSUE THREAD

**Issue by manyopensource** [flutter/flutter#60335]
In a way without the color (including Colors.transparent) it looks like that container doesn't even exist.

**Comment by HemilTheRebel** [comment]
Any code samples would be appreciated. Thanks

**Comment by manyopensource** [comment]
I will come up with some simple example - it's not only in my current project, it's always there, so maybe it's a feature!

**Comment by HemilTheRebel** [comment]
I am not quite sure I get you. If its there in your current project, how about a screenshot or a short video of emulator or recording of you phone explaining what you mean?

**Comment by manyopensource** [comment]
It's better if I won't expose any information about the project. And it's not hard to make another app that will explain the issue well.

**Comment by HemilTheRebel** [comment]
Whatever works for you

**Comment by iapicca** [comment]
Hi @manyopensource 
it seems to work fine

<details><summary>logs</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _colored = false;
  static const double _size = 200;

  @override
  Widget build(BuildContext context) => Scaffold(
    backgroundColor: const Color.fromRGBO(0, 0, 255, 1),
    body: Center(
      child: _colored
      ? Container(
        color: const Color.fromRGBO(255, 0, 0, 1),
        height: _size,
        width: _size,
      )
      : Container(
        decoration: BoxDecoration (border: Border.all(color: Colors.black, width: 1, style: BorderStyle.solid),),
        height: _size,
        width: _size,
      )
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: () => setState(() => _colored = ! _colored),
      child: Icon(Icons.swap_horiz),
    ),
  );
}
```

</details>

Can you please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by manyopensource** [comment]
@HemilTheRebel @iapicca 
one of the reproducible samples
https://gist.github.com/manyopensource/2c0b140fa768b255b35e2ee7dc912cde

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.4 at /home/kai/development/flutter
    • Framework revision 1ad9baa8b9 (9 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/kai/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @manyopensource 
please do not provide production code or with 3rd party plugin,
moreover I'm not quite sure what is the behaviour I should be able to observe in your sample
could you provide more detail
Thank you

**Comment by manyopensource** [comment]
@iapicca The container can be dragged as expected when it has the color property, but without the color the container shrinks I guess!

**Comment by HemilTheRebel** [comment]
I cant say for sure without a minimal example but try adding a height property to the container? I guess it should prevent shrinking of container

**Comment by manyopensource** [comment]
@HemilTheRebel The whole issue only because I wanted people know that there such unexpected behavior. I know how to fix it, so you might want to stop wasting your time here. Thanks! And the minimal example is above!

**Comment by iapicca** [comment]
HI @manyopensource 
as mentioned [above](https://github.com/flutter/flutter/issues/60335#issuecomment-650194315) for the issue to be workable needs a minimal reproducible code sample
(not production code or with 3rd party plugin)
Feel free to modify the [sample](https://github.com/flutter/flutter/issues/60335#issuecomment-650104697) I provided to better describe the situation you are encountering
Thank you

**Comment by VladyslavBondarenko** [comment]
@manyopensource 
Reproduces with current master `1.21.0-2.0.pre.94`.

With color set to `transparent`
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/88191412-162b4b80-cc44-11ea-9f36-64a9d3ce4fcc.gif)

Without set color property
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/17024977/88191634-538fd900-cc44-11ea-9452-3130c5f7c142.gif)

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyHomePage()));

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Offset position;

  @override
  void initState() {
    super.initState();
    position = Offset.zero;
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Container(
          width: double.infinity,
          height: double.infinity,
          color: Colors.yellow,
          child: Stack(
            overflow: Overflow.clip,
            children: <Widget>[
              Positioned(
                left: position.dx,
                top: position.dy,
                width: 200,
                height: 200,
                child: GestureDetector(
                  onPanUpdate: (details) {
                    setState(() {
                      position = Offset(position.dx + details.delta.dx,
                          position.dy + details.delta.dy);
                    });
                  },
                  child: Container(
//                    color: Colors.transparent,
                    child: Container(
                      child: Icon(Icons.accessibility),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.94, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.94 at /Users/nevercode/dev/flutter
    • Framework revision adc9dde3ba (15 hours ago), 2020-07-21 16:17:23 -0700
    • Engine revision 5a73d4dc25
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 55C8466B-5367-492B-8EFE-EC45D980571F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by manyopensource** [comment]
<details>
  <summary>code sample</summary>
  
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Offset position = Offset.zero;
  bool _colored = false;
  static const double _size = 200;

  @override
  Widget build(BuildContext context) => Scaffold(
    backgroundColor: const Color.fromRGBO(0, 0, 255, 1),
    body: Stack(
      children: <Widget>[
        Positioned(
          left: position.dx,
          top: position.dy,
          width: _size,
          height: _size,
          child: GestureDetector(
            onPanUpdate: (details) {
              setState(() {
                position = Offset(position.dx + details.delta.dx,
                                  position.dy + details.delta.dy);
              });
            },
            child: _colored
            ? Container(
              color: const Color.fromRGBO(255, 0, 0, 1),
              height: _size,
              width: _size,
              child: Icon(Icons.accessibility),
            )
            : Container(
              height: _size,
              width: _size,
              child: Icon(Icons.accessibility),
            )
          ),
        ),
      ],
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: () => setState(() => _colored = ! _colored),
      child: Icon(Icons.swap_horiz),
    ),
  );
}
```
  
</details>

**Comment by nate-thegrate** [comment]
Apologies for this late response!

I believe this is working as intended: a Container's hit test behavior depends on whether or not it builds a DecoratedBox.

Let me know if you have any further questions!
