### ISSUE TITLE
TextFormField doesn't scroll when keyboard shows (probably related to viewInsets.bottom not updated)

### ISSUE THREAD

**Issue by pdivita** [flutter/flutter#60348]
I'm using this very basic code for as part of a Form.
When I click on the TextFormField and the keyboard shows, I expect that the TextFormFields scrolls up, but it doesn't.

The weird thing is that the same code running on an old project, works as expected. Instead on a freshly created project it doesn't.
## Steps to Reproduce

```
  @override
  Widget build(BuildContext context) {
    final _keyboardBottomInset = MediaQuery.of(context).viewInsets.bottom;
    final _screenHeight = MediaQuery.of(context).size.height;
    print(
        "Bottom inset is -> $_keyboardBottomInset and height: $_screenHeight");

    return Scaffold(
        body: SingleChildScrollView(
            child: TextFormField(
      initialValue: 'eventday',
      minLines: 20,
      maxLines: 20,
    )));
  }
```

1. On a freshly created project, when the keyboard shows, the output is this: Bottom inset is -> 0.0 and height: 592.0
2. Same code on old project, print this: Bottom inset is -> 249.0 and height: 592.0

As you can see the value of viewInsets.bottom remains 0.0 even if the keyboard enters the screen

**Expected results:**
I expect that the TextFormField scrolls up

**Actual results:**
It doesn't scroll on a newly created project, but does on an old one

<details>
  <summary>Logs</summary>

 

```
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Versione 10.0.18363.836], locale it-IT)
    • Flutter version 1.17.4 at c:\dev\flutter
    • Framework revision 1ad9baa8b9 (9 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\dev\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\p.divita\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @pdivita 
this issue seems very similar to the [issue](https://github.com/flutter/flutter/issues/56039) is linked to 
the only difference in this case is the textfield being partially covered by the keyboard
**_only if_** the textfield line is visible, with the code below 
selecting numbers below the it seems to scroll as intended.

<details><summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
        body: SingleChildScrollView(
          child: Container(
            height: MediaQuery.of(context).size.height,
            child: Column(
              children: [
                Expanded(child: Container()),
                TextFormField(
                  initialValue: [for (int i = 0; i < 20; ++i) '$i'].join('\n'),
                  minLines: 20,
                  maxLines: 20,
                ),
              ],
            ),
          ),
        ),
      );
}
```

</details>

I'd consolidate this issue on https://github.com/flutter/flutter/issues/56039 for now
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pdivita** [comment]
Sorry but it continues to not scroll.
![untitled](https://user-images.githubusercontent.com/35732152/85854051-f83d0900-b7b3-11ea-9688-8b76793bfcfd.gif)

**Comment by iapicca** [comment]
Hi again @pdivita 
I cannot reproduce this behaviour ([video](https://photos.app.goo.gl/YYDDPdBPpuPZoaMr7))
are you experiencing this with the latest master?
thank you

**Comment by pdivita** [comment]
Ciao,
se sei su discord possiamo vedere insieme un attimo.

Piero Di Vita

Da: Francesco Iapicca <notifications@github.com>
Inviato: venerdì 26 giugno 2020 14:59
A: flutter/flutter <flutter@noreply.github.com>
Cc: Piero Di Vita <p.divita@therocks.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [flutter/flutter] TextFormField doesn't scroll when keyboard shows (probably related to viewInsets.bottom not updated) (#60348)


Hi again @pdivita<https://github.com/pdivita>
I cannot reproduce this behaviour (video<https://photos.app.goo.gl/YYDDPdBPpuPZoaMr7>)
are you experiencing this with the latest master?
thank you

**Comment by pdivita** [comment]
Ok I *finally* figured out what was going on.
The problem is related to [this bug](https://github.com/henriquearthur/flutter_native_splash/issues/39) of flutter_native_splash plugin.
The fix consist in going to `android/app/src/main/res/values/styles.xml` and remove the line `<item name="android:windowFullscreen">true</item>`

Not being in full screen mode means during the splash screen the status bar will be visible, but I don't care.

You can safely close, thanks for support.

**Comment by iapicca** [comment]
Hi @pdivita 
I'm glad that you fixed the issue
Thank you for letting me know
