### ISSUE TITLE
[video_player] a way to get the thumbnail from the video

### ISSUE THREAD

**Issue by markgrancapal** [flutter/flutter#60340]
I know there's couple of flutter plugin that does this for iOS and Android. But I'm developing an app for FLUTTER WEB, and I can't find a solution to this. If we initialized() video_player, it provides a thumbnail, but there's no way we can use that as BYTE DATA

**Comment by iapicca** [comment]
Hi @markgrancapal 
I see there's an open [issue](https://github.com/flutter/flutter/issues/27950
) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by markgrancapal** [comment]
> Hi @markgrancapal
> I see there's an open [issue](https://github.com/flutter/flutter/issues/27950) addressing the case you described.
> Please follow up on that issue, I'm closing the current one as duplicate.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

Oh great! thanks @iapicca
