### ISSUE TITLE
[in_app_purchase] Not able to buy anything on iOS, works on android 

### ISSUE THREAD

**Issue by Dfisch3r** [flutter/flutter#60344]
Hi,

I implemented the in_app_purchase plugin and it works perfectly for Android. Since it is one codebase it should then also work for iOs? In iOs the app gets the connection to the AppStore, but it doesn't do anything after the user clicks on "buy" (the inApp-Product-Name is the same as in GooglePlay, so that is not the issue).
The next problem is that I do not have a Mac, so I can not test the sandbox. But as already written, it should work with one code for both platforms?

Thanks for help!

**Comment by iapicca** [comment]
Hi @Dfisch3r 
I see there's an open [issue](https://github.com/flutter/flutter/issues/59763) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Dfisch3r** [comment]
I can not 100% relate to the other issue, because I am unable to test in Sandbox. 
But I can say it works perfectly for Android. 
Shoudn't it work for iOs too if Android works( vice versa)?

**Comment by iapicca** [comment]
Hi again @Dfisch3r 
Can you please provide your `flutter doctor -v`,
your `flutter run --verbose`,
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by Dfisch3r** [comment]
flutter doctor -v:
`[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale de-DE)
    • Flutter version 1.17.2 at C:\Users\danie\Documents\flutter
    • Framework revision 5f21edf8b6 (4 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\danie\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\danie\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\danie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

flutter run --verbose:
`[  +23 ms] executing: [C:\Users\danie\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +90 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5f21edf8b66e31a39133177319414395cc5b5f48
[   +1 ms] executing: [C:\Users\danie\Documents\flutter/] git tag --contains HEAD
[ +232 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.2
[  +13 ms] executing: [C:\Users\danie\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Users\danie\Documents\flutter/] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +111 ms] executing: [C:\Users\danie\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: C:\Users\danie\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +108 ms] List of devices attached
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +44 ms] No supported devices connected.
[   +9 ms] "flutter run" took 370ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///C:/Users/danie/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

pubspec.yaml:
`name: NameOfTheApp
description: DescriptionOfTheApp


version: 1.0.0+14
environment: 
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  [. . . . . ] #otherPlugins
  in_app_purchase: ^0.3.4+1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon_ios"
  image_path_android: "assets/images/Logo.png"
  image_path_ios: "assets/images/Logofull.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:     
  - assets/images/
  - google_fonts/`

Copying the Code example I found maybe a mistake. The user should be able to buy a subscription. This is a non-consumable product right? In my code I use "buy.consumable", but it works for Android.
Or does Apple and Android treat subscriptions differently? So for Android I have to use consumable and for iOs non-consumable?
Code Example ( UI-->Button--> calls  _buyProduct(_products[0]); / or  _buyProduct(_products[1]); ):
`import 'dart:async';

import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/gestures.dart';
import 'dart:io';
import 'package:in_app_purchase/in_app_purchase.dart';

double screenHeight;
double screenWidth;
String plattform;

final String plusID = 'plus';
final String premiumID = 'premium';

 /// Is the API available on the device
  bool _available = true;

  /// The In App Purchase plugin
  InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;

  /// Products for sale
  List<ProductDetails> _products = [];

  /// Past purchases
  List<PurchaseDetails> _purchases = [];

  /// Updates to purchases
  StreamSubscription _subscription;

class Premium extends StatefulWidget
{

  @override
  _PremiumState createState() => _PremiumState();
}

class _PremiumState extends State<Premium>
{  
 
  
    @override
    void initState() {
    _initialize();
    super.initState();
  }
  @override
  void dispose(){
  _subscription.cancel();
  super.dispose();
  }

  /// Initialize data
  void _initialize() async { // Check availability of In App Purchases
    _available = await _iap.isAvailable();

    if (_available) {
      print('available');
      await _getProducts();
      await _getPastPurchases();

      // Verify and deliver a purchase with your own business logic
      _verifyPurchase();
    
     // Listen to new purchases
      _subscription = _iap.purchaseUpdatedStream.listen((data) => setState(() {
        print('NEW PURCHASE');
        _purchases.addAll(data);
        _verifyPurchase();
      }));
  }
  else {print('not available');}
  }

    /// Purchase a product
  void _buyProduct(ProductDetails prod) {
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: prod);
    // _iap.buyNonConsumable(purchaseParam: purchaseParam);
    _iap.buyConsumable(purchaseParam: purchaseParam, autoConsume: false);
  }

  /// Get all products available for sale
  Future<void> _getProducts() async {
    Set<String> ids = Set.from([plusID,premiumID]); 
    ProductDetailsResponse response = await _iap.queryProductDetails(ids);

    setState(() { 
      _products = response.productDetails;
      print('getprod');
    });
  }

  /// Gets past purchases
  Future<void> _getPastPurchases() async {
    QueryPurchaseDetailsResponse response =
        await _iap.queryPastPurchases();

    for (PurchaseDetails purchase in response.pastPurchases) {
      if (Platform.isIOS) {
        InAppPurchaseConnection.instance.completePurchase(purchase);
      }
    }

    setState(() {
      _purchases = response.pastPurchases;
    });
  }

  /// Returns purchase of specific product ID
  PurchaseDetails _hasPurchased(String productID) {
    return _purchases.firstWhere( (purchase) => purchase.productID == productID, orElse: () => null);
  }

  /// Your own business logic to setup a consumable
  void _verifyPurchase() {
    PurchaseDetails purchase = _hasPurchased(plusID);
    if (purchase == null){ purchase = _hasPurchased(premiumID);}

    // TODO serverside verification & record consumable in the database
//Not Relevant for me because I use subscriptions

    if (purchase != null && purchase.status == PurchaseStatus.purchased) {
      _credits = 10;
    }
  }
`

**Comment by iapicca** [comment]
Hi @Dfisch3r 
thank you for providing your doctor and your yaml,
while for the log, please make sure that a device is attached

```bash
[  +44 ms] No supported devices connected.
[   +9 ms] "flutter run" took 370ms.
```

Please do not provide production code or a snippet of it,
but a minimal reproducible code sample that representative of your implementation
Thank you

**Comment by Dfisch3r** [comment]
Sorry, as you can tell I am new to these things. Here is a reproducible code sample:
<details><summary>code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:in_app_purchase/in_app_purchase.dart';
double screenWidth;

final String plusID = 'plus';
final String premiumID = 'premium';

 /// Is the API available on the device
  bool _available = true;

  /// The In App Purchase plugin
  InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;

  /// Products for sale
  List<ProductDetails> _products = [];

  /// Past purchases
  List<PurchaseDetails> _purchases = [];

  /// Updates to purchases
  StreamSubscription _subscription;

  /// Consumable credits the user can buy
  int _credits = 0;


class Github extends StatefulWidget
{

  @override
  _GithubState createState() => _GithubState();
}

class _GithubState extends State<Github>
{  
 
  
    @override
    void initState() {
    _initialize();
    super.initState();
  }
  @override
  void dispose(){
  _subscription.cancel();
  super.dispose();
  }

  /// Initialize data
  void _initialize() async { // Check availability of In App Purchases
    _available = await _iap.isAvailable();

    if (_available) {
      print('available');
      await _getProducts();
      await _getPastPurchases();

      // Verify and deliver a purchase with your own business logic
      _verifyPurchase();
    
     // Listen to new purchases
      _subscription = _iap.purchaseUpdatedStream.listen((data) => setState(() {
        print('NEW PURCHASE');
        _purchases.addAll(data);
        _verifyPurchase();
      }));
  }
  else {print('not available');}
  }

  /// Purchase a product
  void _buyProduct(ProductDetails prod) {
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: prod);
    // _iap.buyNonConsumable(purchaseParam: purchaseParam);
    _iap.buyConsumable(purchaseParam: purchaseParam, autoConsume: false);
  }

  /// Get all products available for sale
  Future<void> _getProducts() async {
    Set<String> ids = Set.from([plusID,premiumID]); //,premiumID
    ProductDetailsResponse response = await _iap.queryProductDetails(ids);

    setState(() { 
      _products = response.productDetails;
      print('getprod');
    });
  }

  /// Gets past purchases
  Future<void> _getPastPurchases() async {
    QueryPurchaseDetailsResponse response =
        await _iap.queryPastPurchases();

    for (PurchaseDetails purchase in response.pastPurchases) {
      if (Platform.isIOS) {
        InAppPurchaseConnection.instance.completePurchase(purchase);
      }
    }

    setState(() {
      _purchases = response.pastPurchases;
    });
  }

  /// Returns purchase of specific product ID
  PurchaseDetails _hasPurchased(String productID) {
    return _purchases.firstWhere( (purchase) => purchase.productID == productID, orElse: () => null);
  }

  /// Your own business logic to setup a consumable
  void _verifyPurchase() {
    PurchaseDetails purchase = _hasPurchased(plusID);
    if (purchase == null){ purchase = _hasPurchased(premiumID);}

    // TODO serverside verification & record consumable in the database

    if (purchase != null && purchase.status == PurchaseStatus.purchased) {
      _credits = 10;
    }
  }

/// Spend credits and consume purchase when they run pit
  void _spendCredits(PurchaseDetails purchase) async {
    
    /// Decrement credits
    setState(() { _credits--; });

    /// TODO update the state of the consumable to a backend database

    // Mark consumed when credits run out
    if (_credits == 0) {
      var res = await _iap.consumePurchase(purchase);
      await _getPastPurchases();
    }

  }

  @override
  Widget build(BuildContext context) {
     screenWidth = MediaQuery.of(context).size.width;
     return Scaffold
    (
      appBar: AppBar(
        automaticallyImplyLeading: true,
       
        iconTheme: Theme.of(context).iconTheme,
        leading: IconButton(icon:Icon(Icons.arrow_back, color: Theme.of(context).buttonColor,),
          onPressed:() =>  Navigator.pop(context, false),
        ),
        actions: <Widget>
        [
          Container
          (
            margin: EdgeInsets.only(right: screenWidth/25.7), 
            child: Row
            (
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget> 
              [
              
  
              ],
            ),
          )
        ],
      ),
  body:  new FlatButton(
              child: new Text("Click to buy"),
              onPressed: () {
               _buyProduct(_products[0]);
              },
            ));
  }
}

```

</details>

I run --verbose with device, but I am not able to get all the output because the terminal cutted the beginning. Only the output which is displayed is 37 pages long. I think this is to much to copy here. (I used quiet a lot plugins, I think this is why it is so long). Do you would like to see a specifc part of the output?

**Comment by TahaTesser** [comment]
Hi @Dfisch3r 
Please provide `flutter run -v -d <device_name>` with logs reproducing the `in_app_purchase`, you can drop all logs in a txt and comment here in the attachment. 
Thank you

**Comment by Dfisch3r** [comment]
Hi @TahaTesser 
Thanks for your reply! Unfortunately I am not able to reproduce the problem, because I have no Mac to test in Sandbox mode.
But I know that iOs doesn't work because my test users in TestFlight reported the problem and also I got the same feedback of Apple when I send the app through the review process.
(Btw: Is there a command to safe the logs into a .txt? Because my VS terminal doesn't allow to scroll all the way up to the first line if the output is to long)

**Comment by TahaTesser** [comment]
Hi @Dfisch3r 
Did you setup https://developer.apple.com/in-app-purchase/? How do you expect your code to be working on iOS without a Mac?
You can run it from the terminal and copy the logs
Thank you

**Comment by Dfisch3r** [comment]
Hi @TahaTesser
Flutter does the work for Android and iOs at the same time. The in_app_purchase plugin implements the inApp Purchases. With tools like Codemagic I am able to push the iOs Version to the AppStore, so there is now need to have a Mac for this.

Yes like I said, I am not able to copy everything from the terminal, because at some point the terminal cuts of the beginning of the output because it is to long (don't ask me why, but this depends on VS)

**Comment by iapicca** [comment]
Hi @Dfisch3r 
for the issue to be workable needs to be reproducible;
please follow up on the [duplicate](https://github.com/flutter/flutter/issues/60344#issuecomment-650096919).
Closing this issue as not reproducible,
if you disagree please provide the information requested above
and I will reopen it.
Thank you

**Comment by Dfisch3r** [comment]
Isn't it reproducible since you know my code and version numbers?

Also it might be helpful if you could tell me, if iOs payment works in your apps (with the newest in_app_purchase version). If not, we know that there is a general problem with the iOs payment. Otherwise, you might can share your code so that I can see what I did wrong. But since Android works, I think my code should be okay

**Comment by iapicca** [comment]
Hi @Dfisch3r 
the goal of this github repository is to improve flutter and it's plugins
reporting bugs and with feature requests;

the bug you are reporting **is known** and is being addressed in this [issue](https://github.com/flutter/flutter/issues/59763)
As you [stated](https://github.com/flutter/flutter/issues/60344#issuecomment-650101981)

> I can not 100% relate to the other issue, because I am unable to test in Sandbox.

but not being able to test a specific context doesn't imply a different behaviour.

If you experience a different behaviour please report it on the issue linked above
providing the appropriate logs.
Thank you

**Comment by Dfisch3r** [comment]
@Hixie since you asked for some code to the iOs in_app_purchase issue, here I posted my code.
I don't know if this is enough for you to test the issue, but (as you can see in this conversation above) I am not able to provide more stuff.

I really hope you can help to fix this issue! I think many users can't publish their apps if they are not able to implement the in_app_purchase
