### ISSUE TITLE
Stuck at syncing files to device Android SDK

### ISSUE THREAD

**Issue by MachariaK** [flutter/flutter#60352]
This is related to [#45473](https://github.com/flutter/flutter/issues/45473). There is a continuous loop with no results. The console output is "Syncing files to device Android SDK built for x86...".

`flutter doctor -v` outputs the following:

```
[√] Flutter (Channel master, 1.20.0-1.0.pre.206, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)
    • Flutter version 1.20.0-1.0.pre.206 at C:\flutter
    • Framework revision 5731be56e0 (34 hours ago), 2020-06-24 20:58:01 -0400
    • Engine revision 24d2143b98
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\tkari\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\tkari\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

**Comment by iapicca** [comment]
Hi @MachariaK 
could you please run from terminal (not from your IDE) 
and making sure you have a device attached
```console
flutter create test
cd test
flutter run -v
```
and provide the output of last command.
If the logs are too long, you may attach them as txt file.
Thank you

**Comment by MachariaK** [comment]
[ +174 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +104 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5731be56e04955093e1bf089ed7592abb81e2a89
[   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +314 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] executing: [C:\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +103 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[   +2 ms] 1.20.0-0.0.pre-206-g5731be56e0
[  +14 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/master
[   +1 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +93 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] master
[  +69 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +15 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +54 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +13 ms] C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +57 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +262 ms] Generating
D:\Developer\Mobile_Applications\new_test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +36 ms] ro.hardware = ranchu
[  +36 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +51 ms] Starting incremental build...
[ +223 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[  +15 ms] complete
[   +7 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +9 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\tkari\AppData\Local\Temp\flutter_tools.47ccf2c5\flutter_tool.8cc7ed30\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +23 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat
-v time -t 1
[  +56 ms] Exit code 0 from: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -t 1
[   +2 ms] --------- beginning of main
           06-26 14:52:40.144 E/GnssHAL_GnssInterface( 1775): gnssSvStatusCb: b: input svInfo.flags is 8
[   +3 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat
-v time -t 1
[  +50 ms] Exit code 0 from: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -t 1
[   +2 ms] --------- beginning of main
           06-26 14:52:40.144 E/GnssHAL_GnssInterface( 1775): gnssSvStatusCb: b: input svInfo.flags is 8
[  +18 ms] <- compile package:new_test_app/main.dart
[  +23 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +84 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +33 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +7 ms] Using gradle from D:\Developer\Mobile_Applications\new_test_app\android\gradlew.bat.
[   +2 ms] D:\Developer\Mobile_Applications\new_test_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +127 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +6 ms] executing: [D:\Developer\Mobile_Applications\new_test_app\android/]
D:\Developer\Mobile_Applications\new_test_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Developer\Mobile_Applications\new_test_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1891 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+15782 ms] > Task :app:compileFlutterBuildDebug
[   +7 ms] [ +180 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [ +122 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [        ] 5731be56e04955093e1bf089ed7592abb81e2a89
[   +4 ms] [   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +680 ms] [ +685 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] [   +1 ms] executing: [C:\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +198 ms] [ +208 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[   +2 ms] [        ] 1.20.0-0.0.pre-206-g5731be56e0
[   +3 ms] [  +12 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +94 ms] [  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/master
[   +3 ms] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[   +1 ms] [  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[  +89 ms] [ +110 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +100 ms] [  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] master
[  +97 ms] [  +79 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] [  +94 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +160 ms] [ +199 ms] Initializing file store
[   +2 ms] [  +26 ms] Skipping target: gen_localizations
[   +2 ms] [  +16 ms] kernel_snapshot: Starting due to {}
[  +96 ms] [  +55 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
D:\Developer\Mobile_Applications\new_test_app\.packages --output-dill
D:\Developer\Mobile_Applications\new_test_app\.dart_tool\flutter_build\9781af608e1464ddb785c904afb120fd\app.dill
--depfile
D:\Developer\Mobile_Applications\new_test_app\.dart_tool\flutter_build\9781af608e1464ddb785c904afb120fd\kernel_snapshot.d package:new_test_app/main.dart
[+16198 ms] [+16216 ms] kernel_snapshot: Complete
[+1099 ms] [+1116 ms] debug_android_application: Starting due to {}
[ +499 ms] [ +481 ms] debug_android_application: Complete
[+1038 ms] [ +989 ms] Persisting file store
[   +1 ms] [  +31 ms] Done persisting file store
[        ] [  +26 ms] build succeeded.
[  +60 ms] [  +32 ms] "flutter assemble" took 19,341ms.
[   +1 ms] [   +6 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +395 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[  +95 ms] > Task :app:generateDebugBuildConfig
[   +2 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +97 ms] > Task :app:mergeDebugShaders
[   +1 ms] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[        ] > Task :app:mergeDebugAssets
[ +398 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:mainApkListPersistenceDebug
[  +10 ms] > Task :app:generateDebugResValues
[   +1 ms] > Task :app:generateDebugResources
[+1985 ms] > Task :app:createDebugCompatibleScreenManifests
[ +398 ms] > Task :app:processDebugManifest
[ +101 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +899 ms] > Task :app:checkDebugDuplicateClasses
[ +199 ms] > Task :app:mergeDebugResources
[ +500 ms] > Task :app:processDebugResources
[+8600 ms] > Task :app:compileDebugKotlin
[  +99 ms] > Task :app:javaPreCompileDebug
[+2902 ms] > Task :app:compileDebugJavaWithJavac
[  +21 ms] > Task :app:compileDebugSources
[+1889 ms] > Task :app:transformClassesWithDexBuilderForDebug
[  +13 ms] > Task :app:validateSigningDebug
[  +12 ms] > Task :app:signingConfigWriterDebug
[ +261 ms] > Task :app:mergeDebugJavaResource
[   +4 ms] > Task :app:desugarDebugFileDependencies
[  +10 ms] > Task :app:mergeDebugJniLibFolders
[+2683 ms] > Task :app:mergeDebugNativeLibs
[ +800 ms] > Task :app:stripDebugDebugSymbols
[   +5 ms] Compatible side by side NDK version was not found.
[   +5 ms] Unable to strip library 'D:\Developer\Mobile_Applications\new_test_app\build\app\intermediates\merged_native_libs\debug\out\lib\x86\libflutter.so' due to missing strip tool for ABI 'X86'. Packaging it
as is.
[   +4 ms] Unable to strip library 'D:\Developer\Mobile_Applications\new_test_app\build\app\intermediates\merged_native_libs\debug\out\lib\x86_64\libflutter.so' due to missing strip tool for ABI 'X86_64'.
Packaging it as is.
[ +683 ms] > Task :app:mergeExtDexDebug
[ +998 ms] > Task :app:mergeDexDebug
[+4700 ms] > Task :app:packageDebug
[ +201 ms] > Task :app:assembleDebug
[  +99 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[   +3 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +9 ms] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] BUILD SUCCESSFUL in 1m 7s
[   +9 ms] 31 actionable tasks: 30 executed, 1 up-to-date
[ +579 ms] Running Gradle task 'assembleDebug'... (completed in 68.1s)
[ +101 ms] calculateSha: LocalDirectory: 'D:\Developer\Mobile_Applications\new_test_app\build\app\outputs\flutter-apk'/app.apk
[  +55 ms] calculateSha: reading file took 44us
[ +541 ms] calculateSha: computing sha took 537us
[ +920 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +86 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\build-tools\30.0.0\aapt dump xmltree D:\Developer\Mobile_Applications\new_test_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +74 ms] Exit code 0 from: C:\Users\tkari\AppData\Local\Android\sdk\build-tools\30.0.0\aapt dump xmltree D:\Developer\Mobile_Applications\new_test_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.new_test_app" (Raw: "com.example.new_test_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="new_test_app" (Raw: "new_test_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.new_test_app.MainActivity" (Raw: "com.example.new_test_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +18 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +3 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop com.example.new_test_app
[  +70 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages com.example.new_test_app
[  +64 ms] Installing APK.
[   +4 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +40 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +12 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +35 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +3 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r D:\Developer\Mobile_Applications\new_test_app\build\app\outputs\flutter-apk\app.apk
[+2181 ms] Performing Streamed Install
                    Success
[   +3 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 2.2s)
[   +9 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell echo -n 63544dc5d35e485dd1edafd9b82bf29aaa3c7e72 > /data/local/tmp/sky.com.example.new_test_app.sha1
[ +213 ms] Android SDK built for x86 startApp
[   +9 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.new_test_app/com.example.new_test_app.MainActivity
[ +561 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.new_test_app/.MainActivity (has extras) }
[   +3 ms] Waiting for observatory port to be available...
[+2342 ms] Observatory URL on device: http://127.0.0.1:45475/ZdrfhRiql5k=/
[   +4 ms] executing: C:\Users\tkari\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:45475
[  +45 ms] 54845
[   +2 ms] Forwarded host port 54845 to device port 45475 for Observatory
[  +17 ms] Caching compiled dill
[  +79 ms] Connecting to service protocol: http://127.0.0.1:54845/ZdrfhRiql5k=/
[ +735 ms] Successfully connected to service protocol: http://127.0.0.1:54845/ZdrfhRiql5k=/
[   +3 ms] Waiting for Android SDK built for x86 to report its views...
[  +21 ms] Waiting for Android SDK built for x86 to report its views... (completed in 14ms)
[  +24 ms] DevFS: Creating new filesystem on the device (null)
[  +43 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.new_test_app/code_cache/new_test_appYLBVGU/new_test_app/)
[   +4 ms] Updating assets
[ +184 ms] Syncing files to device Android SDK built for x86...
[   +5 ms] Scanning asset files
[  +11 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +9 ms] <- recompile package:new_test_app/main.dart e8c603ee-0a2f-406e-b465-1ec19042e22a
[   +1 ms] <- e8c603ee-0a2f-406e-b465-1ec19042e22a
[  +13 ms] D/EGL_emulation( 6158): eglMakeCurrent: 0xe1c07580: ver 3 1 (tinfo 0xc0014920)
[ +146 ms] Updating files
[ +264 ms] DevFS: Sync finished
[   +9 ms] Syncing files to device Android SDK built for x86... (completed in 460ms)
[   +1 ms] Synced 0.9MB.
[   +2 ms] <- accept
[  +14 ms] Connected to _flutterView/0xecd32210.
[   +2 ms] Flutter run key commands.
[  +13 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +3 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:54845/ZdrfhRiql5k=/

**Comment by iapicca** [comment]
Hi @MachariaK 
your logs look clean, did the app run as intended?
Is the issue occurring only on your IDE? 
Thank you

**Comment by MachariaK** [comment]
The problem was as a result of passing null to itemCount in ListView.builder.  Thank you @iapicca for your time.
