### ISSUE TITLE
Can't access flutter.dev from MacOS (Chrome, Safari) 

### ISSUE THREAD

**Issue by Abdugani-Temirbaev** [flutter/flutter#60355]
Cannot access flutter.dev and I do not have /etc/resolver folder ([folders and files in etc](https://i.stack.imgur.com/AX01Y.jpg))

P.S. I have read [this post](https://support.google.com/chrome/thread/2228098?hl=en&msgid=2228098) and [this one](https://support.google.com/chrome/thread/34438178?hl=en&msgid=34438178).

**Comment by VladyslavBondarenko** [comment]
Hi @Abdugani-Temirbaev 
what error do you have?
You can try with VPN.
https://flutter.dev/community/china may be useful if you are behind a firewall

**Comment by Abdugani-Temirbaev** [comment]
> Hi @Abdugani-Temirbaev
> what error do you have?
> You can try with VPN.
> https://flutter.dev/community/china may be useful if you are behind a firewall

I got [following error](https://i.stack.imgur.com/hwmIJ.png). And, I will try to use VPN

**Comment by VladyslavBondarenko** [comment]
Closing as solved with using VPN, 
@Abdugani-Temirbaev please comment if it's not so and I'll reopen

**Comment by Abdugani-Temirbaev** [comment]
> Closing as solved with using VPN,
> @Abdugani-Temirbaev please comment if it's not so and I'll reopen

Yes, using VPN helped, thank you.

But I have to reload 1-2 times, and the loading time of the web page is slow, maybe problem in VPN server.
