### ISSUE TITLE
Flutter text widget and grammarly

### ISSUE THREAD

**Issue by MariumHashmiBM** [flutter/flutter#60366]
## Steps to Reproduce

1. Install Grammarly plugin
2. Try to type in flutter text widget

**Expected results:** Proper typing

**Actual results:** types up to 2 characters only and then removes those 2 characters and start from beginning

Any published app has the same issue with grammarly plugin

**Comment by jobic10** [comment]
Let us see the code

> ## Steps to Reproduce
> 1. Install Grammarly plugin
> 2. Try to type in flutter text widget
> 
> **Expected results:** Proper typing
> 
> **Actual results:** types up to 2 characters only and then removes those 2 characters and start from beginning
> 
> Any published app has the same issue with grammarly plugin

**Comment by TahaTesser** [comment]
Hi @MariumHashmiBM 
I am not sure this is related to Flutter, please link the plugin you're using
If you think this is related to Flutter, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by VladyslavBondarenko** [comment]
@MariumHashmiBM 
Closing as additional information isn't provided
