### ISSUE TITLE
Execution failed for task ':app:cleanMergeDebugAssets'.

### ISSUE THREAD

**Issue by jesseframework** [flutter/flutter#60362]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cleanMergeDebugAssets'.
> Unable to delete directory 'C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\fonts
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\images
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\lang
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\cupertino_icons\assets
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\cupertino_icons
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\easy_localization\i18n
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\easy_localization
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\rflutter_alert\assets\images\2.0x
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\rflutter_alert\assets\images\3.0x
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\rflutter_alert\assets\images
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\rflutter_alert\assets
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages\rflutter_alert
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets\packages
    - C:\Users\jgray\source\repos\j3\build\app\intermediates\merged_assets\debug\out\flutter_assets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @jesseframework 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by VladyslavBondarenko** [comment]
@jesseframework 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template
