### ISSUE TITLE
write your first app error in docs

### ISSUE THREAD

**Issue by netskink** [flutter/flutter#60376]
This page here

https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

Fails to mention that you also need to delete the const keyword in the body section.  Otherwise it will not build.

```
body: Center(                                // delete const on this line should be noted.
          //child: Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
```

**Comment by imwithsam** [comment]
I ran into this issue as well. It would also help if the commented out 'Hello World' line had the `const`  left in it for consistency and to make it clearer that `Text(wordPair.asPascalCase)` should not have `const` in front of it.

i.e.
```
        body: Center(   // Remove const
          //child: const Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
        ),
```

**Comment by TahaTesser** [comment]
duplicate of  https://github.com/flutter/flutter/issues/53375
