### ISSUE TITLE
Programmatically open and close ExpansionTile Widget.

### ISSUE THREAD

**Issue by ritvij-saxena** [flutter/flutter#60387]
I was building a Card which would be placed at the bottom of the screen, ExpansionTile is the child of this widget. When I click this card, the showModalBottomSheet() is called in OnExpansionChanged, however, I don't know how to close it. An open and close feature would be nice.

code reference: https://gist.github.com/ritvij-saxena/4726b3a834b8aa4afb7305eda2c970da
Live demo: https://dartpad.dev/4726b3a834b8aa4afb7305eda2c970da

**Comment by TahaTesser** [comment]
Related to https://github.com/flutter/flutter/issues/7024 
Currently we only have `initiallyExpanded` which does it initially and there is no way to close `ExpansionTile` afterwards programmatically https://github.com/flutter/flutter/issues/7024#issuecomment-623007043

**Comment by ritvij-saxena** [comment]
Should I be looking forward to this feature in the near future?

**Comment by maksof-Hussain** [comment]
is there any way to close or open an ExpansionList in current version without loosing the animation?

**Comment by Nuytemans-Dieter** [comment]
Is there a design doc for this? I am willing to create a PR for this if it is a desired feature.

**Comment by Nuytemans-Dieter** [comment]
For those looking for a solution before this has been implemented in Flutter:
You can simply copy the code of [ExpansionTile](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/expansion_tile.dart) and make a few changes.
- I suggest renaming ExpansionTile and _ExpansionTileState to something else so the names don't cause confusion.
- Make the previous _ExpansionTileState public (because we'll need to use a GlobalKey<ExpansionTileState>)
- Add the method below. This will toggle the animation and state of ExpansionTileState when the new setting is different from the current one and changes nothing otherwise.

```
  void setExpanded(bool doExpand)
  {
    if ( doExpand != _isExpanded)
      _handleTap();      
  }
```

Now simply initialise ExpansionTile with a key and keep a reference to that key wherever you are using the Widget. Then you can call `key.currentState.doExpand(bool newExpandedState)` when needed. Or [click here](https://pastebin.pl/view/47238cde) to see my implementation.

The actual implementation in Flutter will probably differ though (as I don't believe they want to expose _ExpansionTileState).

**Comment by Mickey-A-Mouse** [comment]
Hello! Your link is broken.. Could you update it? Thanks)

**Comment by Mickey-A-Mouse** [comment]
> For those looking for a solution before this has been implemented in Flutter:
> You can simply copy the code of [ExpansionTile](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/expansion_tile.dart) and make a few changes.
> 
> * I suggest renaming ExpansionTile and _ExpansionTileState to something else so the names don't cause confusion.
> * Make the previous _ExpansionTileState public (because we'll need to use a GlobalKey)
> * Add the method below. This will toggle the animation and state of ExpansionTileState when the new setting is different from the current one and changes nothing otherwise.
> 
> ```
>   void setExpanded(bool doExpand)
>   {
>     if ( doExpand != _isExpanded)
>       _handleTap();      
>   }
> ```
> 
> Now simply initialise ExpansionTile with a key and keep a reference to that key wherever you are using the Widget. Then you can call `key.currentState.setExpanded(bool newExpandedState)` when needed. Or [click here](https://pastebin.pl/view/47238cde) to see my implementation.
> 
> The actual implementation in Flutter will probably differ though (as I don't believe they want to expose _ExpansionTileState).

Hello! Your link is broken.. Could you update it? Thanks)

**Comment by Nuytemans-Dieter** [comment]
> > For those looking for a solution before this has been implemented in Flutter:
> > You can simply copy the code of [ExpansionTile](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/expansion_tile.dart) and make a few changes.
> > 
> > * I suggest renaming ExpansionTile and _ExpansionTileState to something else so the names don't cause confusion.
> > * Make the previous _ExpansionTileState public (because we'll need to use a GlobalKey)
> > * Add the method below. This will toggle the animation and state of ExpansionTileState when the new setting is different from the current one and changes nothing otherwise.
> > 
> > ```
> >   void setExpanded(bool doExpand)
> >   {
> >     if ( doExpand != _isExpanded)
> >       _handleTap();      
> >   }
> > ```
> > 
> > 
> > Now simply initialise ExpansionTile with a key and keep a reference to that key wherever you are using the Widget. Then you can call `key.currentState.setExpanded(bool newExpandedState)` when needed. Or [click here](https://pastebin.pl/view/47238cde) to see my implementation.
> > The actual implementation in Flutter will probably differ though (as I don't believe they want to expose _ExpansionTileState).
> 
> Hello! Your link is broken.. Could you update it? Thanks)

Woops, my bad. Fixed it.

**Comment by caseycrogers** [comment]
FWIW, it's far far more elegant to use `ExpansionPanel` which supports programmatically expanding and collapsing rather than changing keys to force an `ExpansionTile` to be rebuilt (which breaks the expansion/collapse animations).

**Comment by mrtdeh** [comment]
its easy with this trick : 

1- open expantion_tile.dart 
2- in the state class and add this code :
```

  @override
  void didUpdateWidget(ExpansionTile oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.initiallyExpanded != widget.initiallyExpanded) {
      _handleTap();
    }
  }
```

and then you can use ```initiallyExpanded``` property as your own ```isExapnded``` and change it...!!

```
.
.
ExpansionTile(
        initiallyExpanded: _isExpanded,
.
.
```
and next :`
```
.
.
onPressed: () {
        print("hello");
        setState(() {
          _isExpanded = !_isExpanded;
        });
      },
.
.
```

remember restart your app for apply changes...
its worked for me.

**Comment by caseycrogers** [comment]
> its easy with this trick :
> 
> .
> .
> .
> 
> remember restart your app for apply changes... its worked for me.

Editing code from external libraries (such as Flutter), is HIGHLY discouraged.

When Flutter releases updates you're likely to get merge conflicts and/or the update will trample your local. Instead, you should make your changes a PR against `flutter/flutter` (of course adding tests and making sure your code is bug-free).

Contributing to flutter has a little bit of a learning curve but it's really not bad. See the [contributing guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).

**Comment by ousvat** [comment]
The best solution I think would be to make the `isExpanded` field public and if the user provide a value for it or is changing it, the controller should respond. Here is the method will work for this:

**Comment by kronkdark** [comment]
> its easy with this trick :
> 
> 1- open expantion_tile.dart 2- in the state class and add this code :
> 
> ```
> 
>   @override
>   void didUpdateWidget(ExpansionTile oldWidget) {
>     super.didUpdateWidget(oldWidget);
>     if (oldWidget.initiallyExpanded != widget.initiallyExpanded) {
>       _handleTap();
>     }
>   }
> ```
> 
> and then you can use `initiallyExpanded` property as your own `isExapnded` and change it...!!
> 
> ```
> .
> .
> ExpansionTile(
>         initiallyExpanded: _isExpanded,
> .
> .
> ```
> 
> and next :`
> 
> ```
> .
> .
> onPressed: () {
>         print("hello");
>         setState(() {
>           _isExpanded = !_isExpanded;
>         });
>       },
> .
> .
> ```
> 
> remember restart your app for apply changes... its worked for me.

MARVELLOUS, this works for me

**Comment by ChiPhanTlm** [comment]
```
@override
  void didUpdateWidget(AppExpansionTile oldWidget) {
    if (oldWidget.isExpanded != widget.isExpanded &&
        (_controller.status != AnimationStatus.forward ||
            _controller.status != AnimationStatus.reverse)) {
      if (widget.isExpanded) {
        _controller.forward().then((value) {
          setState(() {
            _isExpanded = widget.isExpanded;
          });
        });
      } else {
        _controller.reverse().then((value) {
          setState(() {
            _isExpanded = widget.isExpanded;
          });
        });
      }
    }
    super.didUpdateWidget(oldWidget);
  }

```
I custom the method base on other answers

**Comment by caseycrogers** [comment]
> I custom the method base on other answers

Lol guys you all should really stop doing this. Updates will trample and break your changes-don't get in the habit of editing external libraries. It's extremally brittle.

**Comment by glaceon2000** [comment]
It's been more than 2 years and nothing?

**Comment by Nuytemans-Dieter** [comment]
Some PRs have been made but all have been closed. [This comment](https://github.com/flutter/flutter/pull/95727#issuecomment-1011577173) in #95727 suggests a good approach though.

**Comment by Nuytemans-Dieter** [comment]
> It's been more than 2 years and nothing?

Some PRs have been made but all have been closed. [This comment](https://github.com/flutter/flutter/pull/95727#issuecomment-1011577173) in #95727 suggests a good approach though.

**Comment by TreyThomas93** [comment]
Solution: https://github.com/TreyThomas93/flutter-expansion-tile-demo

**Comment by globaltop126** [comment]
Hello @ritvij-saxena.
Did you solve this problem?
I got an issue like this.
I want your contact.
Thank you.
