### ISSUE TITLE
"Plugin project :url_launcher_web not found. Please update settings.gradle" in dev/benchmarks/macrobenchmarks

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#60389]
The current version of `dev/benchmarks/macrobenchmarks` gives warning message when compiling. 

```
Plugin project :url_launcher_web not found. Please update settings.gradle.
```

The `settings.gradle` is no difference with what we can get from `flutter create`.

**Comment by CareF** [comment]
cc @liyuqian @yjbanov

**Comment by iapicca** [comment]
possible [solution](https://github.com/flutter/flutter/issues/57777#issuecomment-632609059)
related to https://github.com/flutter/flutter/issues/46304

**Comment by CareF** [comment]
The problem is no longer there.
