### ISSUE TITLE
Flutter CodeLab 2 Issue

### ISSUE THREAD

**Issue by gypsicoder** [flutter/flutter#60380]
In the 2nd Codelab of flutter I think the codes are wrong in first box of 6th part ["Navigate to a new screen"].
the codes are as follows in the box:
```
class _RandomWordsState extends State<RandomWords> {
  ...
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Startup Name Generator'),
        actions: [              // NEW lines from here...
          IconButton(icon: Icon(Icons.list), onPressed: _pushSaved),
        ],                      // ... to here.
      ),
      home: RandomWords(),
    );
  }
  ...
}
```

But, I think it should be
```
class _RandomWordsState extends State<RandomWords> {
  ...
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Startup Name Generator'),
        actions: [              // NEW lines from here...
          IconButton(icon: Icon(Icons.list), onPressed: _pushSaved),
        ],                      // ... to here.
      ),
      body: _buildSuggestions(),
    );
  }
  ...
}
```

**Comment by TahaTesser** [comment]
Hi @gypsicoder 
I see it correctly showing  `_buildSuggestions` in `RandomWords`’s body  https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..%2Findex#5

**Comment by gypsicoder** [comment]
@TahaTesser yes, now it's showing correctly. But, when I posted the issue it wasn't there. That's why I posted. May be someone have updated. There is no track of updates. So, I can't prove that it's updated.

**Comment by gypsicoder** [comment]
As it seems okay now, I am closing the issue.
