### ISSUE TITLE
Update or ignore `ios/Flutter/Release.xcconfig` 

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#60390]
For example in current `dev/benchmarks/macrobenchmarks`, `flutter run` (even not on an iOS device)  will update `dev/benchmarks/macrobenchmarks/ios/Flutter/Release.xcconfig` and `ios/Flutter/Debug.xcconfig` with the following line: 

```
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
```
And also create `macos/Podfile` and `ios/Podfile` . Tested under Xcode 11.5. 

Should we add these file to `.gitignore` or update these files?

**Comment by CareF** [comment]
cc @gaaclarke @liyuqian

**Comment by gaaclarke** [comment]
This works fine for me:
```
flutter create counter
cd counter
git init
git add .
git commit -m "foo"
flutter run                # with ios device attached
flutter status             # nothing is displayed
```

flutter doctor:
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.43, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-3.0.pre.43 at /Users/aaclarke/dev/flutter
    • Framework revision 15913e5d73 (2 days ago), 2020-06-24 17:13:02 -0400
    • Engine revision 291dab6f17
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)
```

It's probably a requirement that you have a plugin too since I didn't seen a Podfile get created.

As the tool gets updated files like may change and the idea is that you just check them in.  I'd just check in the updated file.

**Comment by liyuqian** [comment]
@CareF : I've seen those `macos/Podfile` and `ios/Podfile` before, but today I can reproduce them by `flutter run` or `flutter drive` inside macrobenchmarks with either Android or iOS device. Maybe this is an issue that has been recently fixed?

**Comment by liyuqian** [comment]
Never mind, my local code was too old (~2 weeks old). I was able to reproduce it with 06d0cd514e40e7aadd6ef820c30ffc39db7db233 so this must be a new issue introduced recently.
