### ISSUE TITLE
The AnimationController animateWith must allow to change the direction

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#60419]
## Use case
I want to use my own spring simulation for fling animation of a widget

## Proposal

Allow us to have some control over the direction of the animation.

[Src link](https://github.com/flutter/flutter/blob/2962912d68fb72d6c9fd60f652e27f3593d692d6/packages/flutter/lib/src/animation/animation_controller.dart#L696)
```dart
/// From animation\animation_controller.dart
///
/// The [status] is always [AnimationStatus.forward] for the entire duration
/// of the simulation. --------- I mean - WHY is that?
  TickerFuture animateWith(Simulation simulation) {
    assert(
      _ticker != null,
      'AnimationController.animateWith() called after AnimationController.dispose()\n'
      'AnimationController methods should not be used after calling dispose.'
    );
    stop();
    _direction = _AnimationDirection.forward;
    return _startSimulation(simulation);
  }
```

**Comment by goderbauer** [comment]
Why do you need to be able to change the direction? What's the use case for this?

**Comment by nt4f04uNd** [comment]
@goderbauer I did provide the use case in the issue itself

**Comment by nt4f04uNd** [comment]
Just want to some more clarity: if the animation value goes from 1 to 0 - it's not the forward direction, that's the reverse, by terminology of Flutter framework itself. If the oppsite happens - the value is changing backwards, but the state is forwards - that's a huge and critical bug.

**Comment by pedromassangocode** [comment]
Hi @nt4f04uNd 
Is this still a valid issue? I just checked the source code and looks like the direction is now changed based on the `velocity`.
Thank you

**Comment by nt4f04uNd** [comment]
@pedromassangocode it's still valid, direction is still hardcoded
https://github.com/flutter/flutter/blob/5b0f69f961985b9a88111622386a25d4d0183988/packages/flutter/lib/src/animation/animation_controller.dart#L727-L736

you probably messed this up with `fling` method

also, i'll make another reference to the documentation
https://github.com/flutter/flutter/blob/c9cb43ce1aaaaf94e9998d1ba5b0a7c911f96733/packages/flutter/lib/src/animation/animation.dart#L13-L26

as you can see this method simply violates how `Animation` should work in flutter

**Comment by pedromassangocode** [comment]
> you probably messed this up with `fling` method

Definitely. Looks like this is still a valid proposal and an easy one :)

**Comment by Hixie** [comment]
There is no use case here. A use case is a high-level description of something you can't do today and an explanation of why you would want to do that.

**Comment by nt4f04uNd** [comment]
ok but i want to know why doesn't it behave like fling? or at least doesn't allow to change the direction manually? it's hard to come up with use case, but this would allow to run custom simulations with appropriate animation statuses - like fling does by default

**Comment by Hixie** [comment]
I'm not really sure what it would mean to change direction when using a Simulation? Can you elaborate?

**Comment by nt4f04uNd** [comment]
difference between animateWith and fling is that the former allows you to run any Simulation you want, and the latter one uses very common SpringSimulation and accepts SpringDescription as a parameter

they are doing pretty similar things, but there's inconsistency

while fling detects animation direction automatically based on the provided velocity value
https://github.com/flutter/flutter/blob/f49956598b2a44cedcb70bd8c4b6b7ef5dc54d43/packages/flutter/lib/src/animation/animation_controller.dart#L684-L686

animateWith in its turn rather hardcodes this value to be forward, so even if values goes from upperBound to lowerBound, it still will give `AnimationStatus.forward`
https://github.com/flutter/flutter/blob/f49956598b2a44cedcb70bd8c4b6b7ef5dc54d43/packages/flutter/lib/src/animation/animation_controller.dart#L725-L734

i'm proposing that the direction value wasn't hardcoded

i understand that Simulation might change the direction on its way (for example underDamped springs bounce), so perhaps there might be a better solution than providing a direction parameter to animateWith - for example auto detecting the direction while simulation is being applied to the controller

this change might also allow to unlock usage of underDamped springs in fling which is currently asserted to not be a case, because:
* the animation direction detection based of a velocity value would not work for such springs
* in most of the cases controller has bounds like 0.0 and 1.0, whilst the resulting animation in this case often gives values out of these bounds - this could be adressed via allowing flinging with such springs only if upperbound is infinity

https://github.com/flutter/flutter/blob/f49956598b2a44cedcb70bd8c4b6b7ef5dc54d43/packages/flutter/lib/src/animation/animation_controller.dart#L704-L708

**Comment by Hixie** [comment]
I guess the question I'm really asking is "why does it matter". If I were writing this API from scratch I probably wouldn't even include the "direction" feature in the version of the animation controller for simulations. Does it make sense to use the direction for these at all?

**Comment by nt4f04uNd** [comment]
from my perspective this would just make controller consistent for simulations. when i opened this issue, there were no springDescription parameter in fling and when i tried to use animateWith for SpringSimulation - it ended not handling AnimationStatus as i expected (and how it worked with fling) it would handle and messed the logic of the ui i built

**Comment by pedromassangocode** [comment]
> from my perspective this would just make controller consistent for simulations.

If you mean that this is causing an issue, could you provide a minimal code sample? I would be happy to verify it :)

**Comment by nt4f04uNd** [comment]
Something like that

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/physics.dart';

void main() async {
  runApp(
    MaterialApp(
      home:  App(),
    ),
  );
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> with SingleTickerProviderStateMixin {
  late AnimationController controller;
  bool up = false;

  @override
  void initState() { 
    super.initState();
    controller = AnimationController(vsync: this);
    controller.addStatusListener((status) {
      if (status == AnimationStatus.forward)
        up = true;
      else if (status == AnimationStatus.reverse)
        // Never executed. Controller listeners are unaware of the actual simulation diration.
        up = false;
    });
  }

  /// I could use up parameter for this instead - but because simulation is always forward,
  /// I have to use this flag.
  bool forward = true;
  void runSimulation() {
    final target = (forward ? 1.0 : 0.0);
    final velocity = (forward ? 1.0 : -1.0);
    final SpringSimulation simulation = SpringSimulation(SpringDescription.withDampingRatio(
        mass: 1.0,
        stiffness: 500.0,
        ratio: 1.0,
      ),
      0,
      target,
      velocity,
    );

    // With fling everithing works fine, while with `animateWith`
    // the image jumpt, because SlideTransition is not animated backwards.
  
    controller.animateWith(simulation);
    // controller.fling(velocity: velocity);
  
    forward = !forward;
  }

  @override
  Widget build(BuildContext context) {
    final slideTransition = Tween(
      begin: Offset(0.0, -1.0),
      end: Offset.zero,
    ).animate(controller);
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: const Text('run simulation'),
        onPressed: runSimulation,
      ),
      body: Align(
        alignment: Alignment.bottomCenter,
        child: AnimatedBuilder(
          animation: controller,
          builder: (context, child) {
            print(slideTransition.value);
            return SlideTransition(
            position: slideTransition,
            child: child,
          );
          },
          child: const RepaintBoundary(
            child: Image(
              image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg'),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by Hixie** [comment]
Consistency isn't really a compelling enough reason to change this IMHO. I'm going to close this for now since it's not obvious that this would improve the power of the API and changes like this have a risk of breaking people.
