### ISSUE TITLE
Very long pause with no feedback to dev when running on iPhone

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6042]
This takes over a minute:

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter -d i run --release
Running lib/main.dart on iPhone...
Application running.
```

I nearly Cmd-C'ed the CLI because it was taking so long, between "on iPhone..." and "Application running."

I wonder if we could put a spinner or some other feedback to let the developer know "We're working on it, stand by..." until the "Application running." output appears.

**Comment by sethladd** [comment]
cc @danrubel

**Comment by Hixie** [comment]
@goderbauer says we give better feedback now.
