### ISSUE TITLE
Issue from website page Release Android version of APP

### ISSUE THREAD

**Issue by RaySummer** [flutter/flutter#60425]
Issue from website page 发布Android版APP

From URL: https://www.flutterchina.club/android-release-build.md
执行flutter build apk后出现Task 'assembleAarRelease' not found in root project 'connectivity'. Some candidates are: 'assembleRelease'.错误。是什么原因导致的，该如何修复？项目兼容Android X 并且minSdkVersion是17的。

(Issue from website page Release Android version of APP

After executing flutter build apk, 

```
Task'assembleAarRelease' not found in root project'connectivity'. Some candidates are:'assembleRelease'. 
```

error. What caused it and how to fix it? The project is compatible with Android X and minSdkVersion is 17.)

**Comment by VladyslavBondarenko** [comment]
Hi @RaySummer 
could you provide your `flutter doctor -v` and your `flutter run --verbose` log?

**Comment by VladyslavBondarenko** [comment]
@RaySummer 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template
