### ISSUE TITLE
DevTools -> CallTree -> Expand/Collapse buttons work identically (gif)

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#60427]
In devtools call tree no matter what button you press (expand or collapse) the call tree collapses in both cases. See the gif animation

Flutter version does not matter
In 1.7.4 and in latest master branch from git it works identicaly
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/6721286/85923801-d8324600-b896-11ea-9766-9212d2b477e6.gif)

**Comment by iapicca** [comment]
Hi @vasilich6107  , 
to report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
