### ISSUE TITLE
Strange green box artifact on Nexus 6P when activating the Animation demo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6043]
On a Nexus 6P, in portrait or landscape, open gallery, and scroll down to Animation. Tap into Animation. Tap the floating-action-button to trigger the animation.

Notice the flashing green box artifact that flashes while the animation is running.

See it in action: https://www.youtube.com/watch?v=k6JBlc2ekdU

**Comment by eseidelGoogle** [comment]
There was another report of this.  @chinmaygarde believed it was likely gpu specific.  Just have to find the dupe.

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/5898
