### ISSUE TITLE
webview_flutter  problem

### ISSUE THREAD

**Issue by oliverchu** [flutter/flutter#60443]
I found that the Flutter plugin does not run smoothly on Android and iOS devices, and sometimes even stops responding. What is the reason?  Compared with another popular plugin, flutter_webview is too stuttering.

**Comment by darshankawar** [comment]
Hi @oliverchu,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you.

**Comment by VladyslavBondarenko** [comment]
@oliverchu 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template
