### ISSUE TITLE
FormatException: Unfinished UTF-8 octet sequence (at offset 1)

### ISSUE THREAD

**Issue by aaniish** [flutter/flutter#60440]
Exception caught by widgets library ═══════════════════════════════════
The following FormatException was thrown building SensorPage(dirty, state: _SensorPageState#0115a):
Unfinished UTF-8 octet sequence (at offset 1)

The relevant error-causing widget was
    SensorPage 
lib\pages\charts_page.dart:83
When the exception was thrown, this was the stack
#0      _Utf8Decoder.flush  (dart:convert/utf.dart:415:9)
#1      Utf8Decoder.convert  (dart:convert/utf.dart:330:13)
#2      Utf8Codec.decode  (dart:convert/utf.dart:61:56)
#3      _SensorPageState._dataParser 
package:project/pages/datadisplay_page.dart:34
#4      _SensorPageState.build 
package:project/pages/datadisplay_page.dart:64
...
════════════════════════════════════════════════════════════════════════════════

**Comment by VladyslavBondarenko** [comment]
Hi @aaniish 
could you provide your `flutter doctor -v` and a minimal complete reproducible code sample?

**Comment by VladyslavBondarenko** [comment]
@aaniish 
Closing as additional information isn't provided
