### ISSUE TITLE
CustomClipper.shouldReclip has unclear docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#60447]
"or any time that a new clip object is created with a new instance of the custom painter delegate class (which amounts to the same thing, because the latter is implemented in terms of the former)" doesn't make any sense to me.

**Comment by JuYeong0413** [comment]
It seems like `custom painter delegate class` should be changed to `custom clipper delegate class`, I think it's a small mistake while adapting custom painter docs in reclip description.
(noticed from [this comment](https://github.com/flutter/flutter/pull/6325#discussion_r83438145), and the CustomPainter.shouldRepaint docs is [here](https://github.com/flutter/flutter/blob/462b0ea76eca028a7776f60a20a05ebce30dfdbd/packages/flutter/lib/src/rendering/custom_paint.dart#L230))
