### ISSUE TITLE
Canvas.drawPoints() renders aliased lines incorrectly when stokeWidth is 1

### ISSUE THREAD

**Issue by jaween** [flutter/flutter#60452]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` as follows:
```dart
import 'dart:ui';

import 'package:flutter/material.dart' hide Image;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Image _image;

  @override
  void initState() {
    draw();
    super.initState();
  }

  void draw() async {
    final pictureRecorder = PictureRecorder();
    final canvas = Canvas(pictureRecorder);
    canvas.drawPoints(
      PointMode.points,
      List.generate(50, (i) => Offset(i.toDouble(), i.toDouble())),
      Paint()
        ..strokeWidth = 1
        ..isAntiAlias = false,
    );
    final picture = pictureRecorder.endRecording();
    final image = await picture.toImage(50, 50);
    setState(() => _image = image);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            width: 200,
            height: 200,
            color: Colors.black.withOpacity(0.1),
            child: CustomPaint(
              painter: MyCustomPainter(_image),
            ),
          ),
        ),
      ),
    );
  }
}

class MyCustomPainter extends CustomPainter {
  Image image;

  MyCustomPainter(this.image);

  @override
  void paint(Canvas canvas, Size size) {
    if (image != null) {
      final source =
          Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble());
      final destination = Offset.zero & size;
      canvas.drawImageRect(
        image,
        source,
        destination,
        Paint(),
      );
    }
  }

  @override
  bool shouldRepaint(MyCustomPainter oldDelegate) => true;
}
```
3. Run the app on an iOS device.
4. Observe that the rendering is not of a diagonal line.

**Expected results:** 
Rendering on an Android device:
<a href="https://user-images.githubusercontent.com/5057145/85936963-9d83e880-b93e-11ea-9798-7ce1c46e7b26.jpg"><img alt="Diagonal line rendering on Android" src="https://user-images.githubusercontent.com/5057145/85936963-9d83e880-b93e-11ea-9798-7ce1c46e7b26.jpg" width="300"></a>

**Actual results:** 
Rendering on an iPhone:
<a href="https://user-images.githubusercontent.com/5057145/85936970-aa084100-b93e-11ea-937c-84dd41274378.jpeg"><img alt="Diagonal line rendering on iPhone" src="https://user-images.githubusercontent.com/5057145/85936970-aa084100-b93e-11ea-937c-84dd41274378.jpeg" width="300"></a>

Extra information:
 * Has occurred on an iPhone 7 and iPad Air 2 on iOS 13.5.1
 * Has occurred on an iPhone X (I didn't get the version)
 * Rendering is incorrect when `stokeWidth` is `-1`, `0`, or `1`
 * Rendering is fixed when `stokeWidth` is `2`
 * Issue persists when using `canvas.drawRawPoints()`
 * Issue persists in profile mode
 * Issue persists when using `flutter run --enable-software-rendering`
 * My use case is user drawn pixel art using points and lines of 1 pixel thickness

<details>
  <summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.49, on Mac OS X 10.15.4 19E287, locale en-AU)
    • Flutter version 1.20.0-3.0.pre.49 at /opt/flutter
    • Framework revision 5731be56e0 (3 days ago), 2020-06-24 20:58:01 -0400
    • Engine revision 24d2143b98
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jaween/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (2 available)
    • SM A520F        • 5200676a4a815579                         • android-arm64 • Android 8.0.0 (API 26)
    • Jaween’s iPhone • 02669b794c29bb14a717a3d0987dc6c5c116d819 • ios           • iOS 13.5.1

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
Doesn't reproduce with iOS 13.5 simulator, but reproduces with iPhone 7 iOS 13.5 real device.
Tried with current master `1.20.0-3.0.pre.78`, dev `1.20.0-2.0.pre`, beta `1.19.0-4.2.pre`, stable `1.17.4`

**Comment by jason-simmons** [comment]
This regressed with the switch to Metal.

@chinmaygarde

**Comment by heathmill** [comment]
Opened https://bugs.chromium.org/p/skia/issues/detail?id=10658 to track on skia-side

**Comment by jvanverth** [comment]
Should be fixed by https://review.skia.org/314318.

**Comment by jaween** [comment]
Yes, on the Flutter `master` channel the rendering appears fixed now on iOS, it's nearly identical to the rendering on Android:
<a href="https://user-images.githubusercontent.com/5057145/92341018-8eb67080-f0fb-11ea-9744-dff810240924.png"><img alt="Diagonal line rendering correctly on iPhone" src="https://user-images.githubusercontent.com/5057145/92341018-8eb67080-f0fb-11ea-9744-dff810240924.png" width="300"></a>
This can be closed.
Thanks for your help.
