### ISSUE TITLE
Recusive copy while building app for IOS

### ISSUE THREAD

**Issue by patriarch** [flutter/flutter#60474]
Hello, since few day we can't compile our app on Ios, no problem on Android.

## Steps to Reproduce
1. Run your app on Ios simulator.
we tried with Legacy build and not
we tried flutter clean

**Expected results:** 
App working on the simulator

**Actual results:** 
Building error with recursive copy

<details>
  <summary>Logs</summary>

Launching lib/main.dart on XXXXX in debug mode...
Legacy build system detected, removing /Users/XXXX/AndroidStudioProjects/Appname/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXX
Running pod install...                                              4,7s
Running Xcode build...
Xcode build done.                                           37,8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    error: '/Users/XXXXX/AndroidStudioProjects/AppFolderName/build/ios/Debug-iphoneos/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app/Appname.app' is longer than filepath buffer size (1025). (in target 'Runner' from project 'Runner')
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

</details>

**Comment by TahaTesser** [comment]
Hi @patriarch 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by patriarch** [comment]
Hello,
Thanks for your quick answer.

Impossible for me to give you code sample as I don't know where the error come from .... 
If you need a specific part of the code or configuration I will share what I can


flutter doctor --verbose 
https://gist.github.com/patriarch/74170c2cb19c3153f9d89308890d9885


flutter run --verbose
https://gist.github.com/patriarch/5bf61e4d4db2601331d1faaa6dfeae70

**Comment by TahaTesser** [comment]
Hi @patriarch 
Your logs in the description doesn't match with logs you provided in the above
in the new logs gist, build has succeeded  but it's failing to launch on simulator
```
            [  +17 ms] debug_universal_framework: Complete
                        [   +3 ms] debug_ios_bundle_flutter_assets: Starting due to {}
                        [ +380 ms] debug_ios_bundle_flutter_assets: Complete
                        [+1024 ms] Persisting file store
                        [  +10 ms] Done persisting file store
                        [   +8 ms] build succeeded.
                        [  +13 ms] "flutter assemble" took 13 513ms.
                        Project /Users/username/AndroidStudioProjects/AppFloder bui
```

Please try with clean simulator, you can reset simulator and try. Also try to reproduce the issue mentioned in the description and provide complete `flutter run --verbose`, you can paste in txt file and drop attachment in the comment

For code sample, see if you can notice same with a new project if not, try to isolate code in your project that reproduces this issue 

Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
