### ISSUE TITLE
Android Studio: no devices connected needed to downgrade to v1.17.3

### ISSUE THREAD

**Issue by iustinpericica** [flutter/flutter#60473]
I had to downgrade to flutter v1.17.3 in order to be able to run flutter project from android studio ( no devices found error ). 
Maybe there's a bug with the current version, hope this can help you.
Thank you!

**Comment by jmagman** [comment]
Can we get the output of `flutter doctor -v` when you are reproducing it?
Do you have Xcode installed?

**Comment by VladyslavBondarenko** [comment]
@iustinpericica 
Closing as additional information isn't provided.
Could everyone who still has this problem please comment here with asked info or file a new issue with filling out template
