### ISSUE TITLE
In_App_Purchase PlatformException for Pending Purchases; unable to manually complete purchase...

### ISSUE THREAD

**Issue by Bmahecha123** [flutter/flutter#60475]
Good afternoon!
I'm implementing Flutter In App Purchase plugin and followed the example application/documentation to get it implemented.. 

Here I'm calling this method to make a purchase which results in the following PlatformException below..
<img width="603" alt="Screen Shot 2020-06-28 at 12 58 18 PM" src="https://user-images.githubusercontent.com/15313318/85953590-84c80280-b93f-11ea-823d-80fee311cc85.png">
<img width="1011" alt="Screen Shot 2020-06-28 at 12 57 58 PM" src="https://user-images.githubusercontent.com/15313318/85953587-82fe3f00-b93f-11ea-98ef-bbe28aca5308.png">
It says to manually complete the purchase however there is no way for me to do this since I never get access to the PurchaseDetails object required for this method here -> 
<img width="707" alt="Screen Shot 2020-06-28 at 1 03 58 PM" src="https://user-images.githubusercontent.com/15313318/85953638-dec8c800-b93f-11ea-9b5e-912368fec492.png">
I would expect my subscription to be triggered but that isn't happening either -> 
<img width="517" alt="Screen Shot 2020-06-28 at 1 05 27 PM" src="https://user-images.githubusercontent.com/15313318/85953664-1b94bf00-b940-11ea-82dd-43bf1e1eb0a0.png">

Any ideas? Thank you for your time!

Here's output of Flutter doctor ->
```[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.3 at /Users/bmahecha123/development/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bmahecha123/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.0.2
    • Dart plugin version 192.7761

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0```

**Comment by TahaTesser** [comment]
Hi @Bmahecha123 
Please refrain from posting screenshot of code sample,  provide code sample 
Can you please provide your `flutter run --verbose`, your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you

**Comment by VladyslavBondarenko** [comment]
@Bmahecha123 
please follow up on https://github.com/flutter/flutter/issues/60763, closing current one as duplicate, if you disagree please write in the comments with asked information and I will reopen it
