### ISSUE TITLE
Flutter analyze does not support fatal warnings

### ISSUE THREAD

**Issue by Pante** [flutter/flutter#60471]
## Use case

Currently the `flutter analyze` command currently does not support the `--fatal-warnings` flag that [dartanalyzer](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_cli#dartanalyzer) does. The flag will help weed out potential issues & code smells in a project, especially when used in a CI/CD environment that tests & builds Flutter projects.

## Proposal

It will be really nice if Flutter exposes a `--fatal-warnings` flag or something similar.

**Comment by Hixie** [comment]
Doesn't it already treat all warnings as fatal?

**Comment by Pante** [comment]
I think includemath's [PR](https://github.com/flutter/flutter/pull/61589) explains the issue really well.
