### ISSUE TITLE
[plugins/share] The share text is not being shown in the iOS share preview panel

### ISSUE THREAD

**Issue by gapspt** [flutter/flutter#60470]
This can be fixed by applying https://github.com/flutter/plugins/pull/2825

**Comment by TahaTesser** [comment]
Hi @gapspt 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by gapspt** [comment]
Hi @TahaTesser 
Is that really necessary? I've only created the issue to give visibility of a pull request I've already made. Flutter doctor and run will not give any interesting outputs whatsoever...

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/55061, closing as duplicate
