### ISSUE TITLE
CardStack dirty. '!_dirty': is not true.

### ISSUE THREAD

**Issue by cihatduyku** [flutter/flutter#60483]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4224 pos 12: '!_dirty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///Users/***/lib/main.dart:123:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4224:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
...
The element being rebuilt at the time was index 2 of 4: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#775f9
</details>

**Comment by iapicca** [comment]
Hi @cihatduyku 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@cihatduyku 
Closing as additional information isn't provided
