### ISSUE TITLE
Expansion panels: Can't tap radio labels in Location

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6048]
Open Gallery, open Expansion panels, open Location. Tap "Bahamas" or "Barbados".

Expected: the radio button changes selection when a label is tapped.

Actual: nothing happens.

Workaround: tap the radio button itself to change selection.

**Comment by sethladd** [comment]
cc @dragostis

**Comment by dragostis** [comment]
I haven't solved this one yet as I was betting on more elegant solution. (#254) We can either try to do a quick fix (surround the `Row`s with `InkWell`s) or try to implement this type of widget.

**Comment by Hixie** [comment]
We should switch this to use RadioTile.
