### ISSUE TITLE
after installing and using this m getting this issue

### ISSUE THREAD

**Issue by swarankargaurav1** [flutter/flutter#60499]
C:\flutter_sdk_stable\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by iapicca** [comment]
Hi @swarankargaurav1 
I see there's an open [issue](https://github.com/flutter/flutter/issues/44580) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
