### ISSUE TITLE
[web]: Flutter command not working in terminal in beta version for web developments

### ISSUE THREAD

**Issue by ngts-global** [flutter/flutter#60500]
Flutter command is not working even setting the PATH properly in mac machine. But same path is working in stable version but not in beta version. I am developing flutter web.

**Comment by ngts-global** [comment]
after running this command "flutter channel beta" it is not working.

**Comment by iapicca** [comment]
Hi @ngts-global 
to use flutter web your flutter channel needs to be `beta` or above;
making sure that you [updated your path](https://flutter.dev/docs/get-started/install/macos#update-your-path)
could you please run from terminal (not android studio or other IDEs)
```console
flutter channel beta
flutter upgrade -f
flutter create test
cd test
flutter run -d chrome -v
```
thank you

**Comment by ngts-global** [comment]
thank you for the response. I am developing both flutter web  & mobile from my mac. If I just install flutter and try mobile app(android) works fine. But after I "flutter channel beta" run this command , flutter is not getting recognized in terminal though the path is available in bash_profile. here is the output 

xxxxx:~$ **flutter --version**
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (12 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
xxxxx:~$ **flutter channel beta**
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    f994b7697..9b9b543d9  beta                   -> origin/beta
git:  + 4656a18fa...f42735ca4 dds_integration_take_2 -> origin/dds_integration_take_2  (forced update)
git:    d9653445f..15a28159b  dev                    -> origin/dev
git:  * [new branch]          experimental_skshaper  -> origin/experimental_skshaper
git:    f994b7697..9b9b543d9  flutter-1.19-candidate.4 -> origin/flutter-1.19-candidate.4
git:  * [new branch]          flutter-1.20-candidate.2 -> origin/flutter-1.20-candidate.2
git:    747fe345f..df98ad6b2  master                 -> origin/master
git:  * [new tag]             1.19.0-4.2.pre         -> 1.19.0-4.2.pre
git:  * [new tag]             1.20.0-1.0.pre         -> 1.20.0-1.0.pre
git:  * [new tag]             1.20.0-2.0.pre         -> 1.20.0-2.0.pre
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
xxxxx:~$ **flutter upgrade -f**
env: bash\r: No such file or directory
xxxxx:~$

**Comment by TahaTesser** [comment]
Hi @ngts-global 
After executing `flutter channel beta`, immediately execute `flutter upgrade --force` and then `flutter doctor -v`
if you mean `flutter upgrade --force isn't after `flutter channel beta` then provide complete logs for `flutter upgrade --force --verbose` with verbose added 

Also please check your path as mentioned by @iapicca 
Thank you

**Comment by VladyslavBondarenko** [comment]
@ngts-global 
I hope you've solved the issue.
Closing since long time without a response
