### ISSUE TITLE
Flutter not supported

### ISSUE THREAD

**Issue by sakshiigupta** [flutter/flutter#60510]
## Steps to Reproduce

1. ...open the terminal on android studio
2. ...type the command "flutter upgrade"
3. ...run the command
![Capture](https://user-images.githubusercontent.com/47752780/85994119-f3c35b00-ba14-11ea-912b-5d26579d8d70.PNG)

## Logs

```
```

```flutter is not recognised as an internal or external command
```

**Comment by abhishekUpmanyu** [comment]
Hi @sakshiigupta !
It seems like you haven't added Flutter to your path variables.
[These are the steps](https://flutter.dev/docs/get-started/install/windows#update-your-path) to fix your issue assuming that you're on windows (seems like that from the screenshot)

Trying restarting your PC after this

**Comment by VladyslavBondarenko** [comment]
@sakshiigupta 
I hope you've solved the issue, closing since long time without a response
