### ISSUE TITLE
AOT operation for Embedders

### ISSUE THREAD

**Issue by limbouser** [flutter/flutter#60518]
https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode 
I went through this document for running an app in AOT mode on Raspberry Pi(ARM). I have an embedder that operates in JIT and would like to change it to AOT.

https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode#generating-the-kernel-snapshot Here, the mentioned executable called `dart` is not present in my `linux_release_arm`(build) directory, same is the case with `frontend_server.dart.snapshot` 

How am I supposed to proceed to generate the necessary AOT napshots?

**Comment by TahaTesser** [comment]
Added `will need additional triage` since the user has questions after following the docs for custom engine embedding

**Comment by limbouser** [comment]
I have got a basic understanding on how to work with AOT builds, so closing.
