### ISSUE TITLE
[BUG] DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true

### ISSUE THREAD

**Issue by franferri** [flutter/flutter#60517]
Original post here: https://github.com/flutter/flutter/issues/60486, @iapicca user decided close it after stating some unrelated stuff. Some of the answers are work arounds but not solution yet to make flutter run tests in Android Studio out of the box after installing Flutter and Dart.

Problem (Reposted):

I have installed today in Android Studio the plugins Flutter and Dart. Last versions.

I was working for hours doing tests in my project and after the update suddenly I can't run the Flutter tests anymore, it keeps saying:

```
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
```

I'm using macOS last version with Flutter stable channel:

```
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (11 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
I have tried to add the DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true to the environment, export in a console and then start Android Studio with open -a... nothing works.
```

Either Flutter is rewriting the var or the build-in dart-sdk not picking it.

Since setting the variable as global don't work, nor in the terminal session before running Android Studio, nor Android Studio let you change anything in the dart plugin panel... I'm out of options

if anybody knows how to fix this please help.

Posted in stackoverflow too in a desperate attempt to get help: https://stackoverflow.com/questions/62629506/dart-vm-options-dsilent-observatory-true

**Comment by iapicca** [comment]
Hi @franferri 
please do not duplicate issues,
If you disagree, please write in the comments and I will reopen it.
