### ISSUE TITLE
web_benchmarks_html bench_mouse_region_grid_scroll regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60526]
Looks like it's the addition of benchmarks itself at https://github.com/flutter/flutter/pull/57576?

![Screen Shot 2020-06-29 at 9 12 45 AM](https://user-images.githubusercontent.com/1435716/86030015-c5c82180-b9e8-11ea-9556-ef46478700ff.png)

**Comment by kf6gpe** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/60310
