### ISSUE TITLE
How to achieve this menu using Flutter?

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#60524]
How to achieve this menu which I can customize. Thanks.

![image](https://user-images.githubusercontent.com/1920873/86025330-a66cdb00-ba60-11ea-8d88-d243bfe1c14a.png)

**Comment by PixelToast** [comment]
Hi @jims57

The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
