### ISSUE TITLE
Add --tree-shake-icons documentation to "Reducing app size" recommendations

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60541]
--tree-shake-icons has been available since v1.15.1.  If we consider it stable enough, add to "Reducing app size" [documentation](https://flutter.dev/docs/perf/app-size#reducing-app-size).

**Comment by jonahwilliams** [comment]
This is enabled by default on release builds, FWIW

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/56633 is in 1.19.0-1.0.pre.  I was remembering that the flag is hidden but present in current stable, unhidden with https://github.com/flutter/flutter/pull/56934 (1.19.0-2.0.pre, on beta).

The [kernel panic](https://github.com/flutter/flutter/pull/55417) fix didn't get cherry-picked to stable, the flag was just hidden on stable.  So never mind, we need to wait until that fix makes it to stable.  And at that point, it will be on by default.

Closing.
