### ISSUE TITLE
Devicelab agent mac18 has been non-pingable for days

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#60543]
For some reason, mac18 is not pingable for a while. A physical investigation is needed.

\cc @godofredoc

**Comment by godofredoc** [comment]
Machine was powered off. I just turned it on again and it should be back online.

@keyonghan can we power cycle it to ensure it comes back after a power cycle?

**Comment by keyonghan** [comment]
Confirmed it comes back after reboot.
