### ISSUE TITLE
Flutter hot reload/ restart not working on Powershell

### ISSUE THREAD

**Issue by siddharthsaini** [flutter/flutter#60542]
The terminal gets stuck here and does not respond to Hot Reload or Restart
![image](https://user-images.githubusercontent.com/53482124/86045230-eb950b00-ba68-11ea-8244-8623be054fd6.png)

Output to my flutter doctor -v below
flutter doctor -v
[√] Flutter (Channel master, 1.20.0-3.0.pre.87, on Microsoft Windows [Version 10.0.18362.900], locale
    en-IN)
    • Flutter version 1.20.0-3.0.pre.87 at D:\Program Files\flutter
    • Framework revision 163a09a535 (2 hours ago), 2020-06-29 10:19:43 -0700
    • Engine revision c332675a8c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Siddharth\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • RMX1801    • 4ee58095   • android-arm64  • Android 9 (API 28)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

**Comment by thatsenam** [comment]
Run`flutter clean` then run again.

**Comment by siddharthsaini** [comment]
Yeah. The problem got solved after turning USB Debugging off and then on.
