### ISSUE TITLE
flutter devices doesn't show my iPhone after upgrade to flutter 1.17.4

### ISSUE THREAD

**Issue by luis901101** [flutter/flutter#60556]
Currently I'm running stable flutter 1.17.4 and Xcode 11.3.1, and my iPhone has iOS 13.5.1. I'm aware that Xcode 11.3.1 doesn't allow to run apps in iOS 13.5.1; but before I upgraded flutter framework I was using stable v1.12.13-hotfix.8 and with that version I was able to list any iOS devices no matter the iOS version... with v1.12.13 I was not able to run apps to my iPhone with iOS 13.5.1 but at least I could install my app then run my app manually in my iPhone and simply use **Flutter Attach** to be able to debug my app... Right now with stable v1.17.4 I can not use **Flutter Attach** cause my iPhone doesn´t appear in the list of devices available...
Currently I can´t upgrade Xcode (in fact I would have to upgrade Mac OS too), so what can I do to get the same devices availability I had with v1.12.13 but using latest v1.17.4

**Comment by VladyslavBondarenko** [comment]
Hi @luis901101 
does it remain undetected after https://github.com/flutter/flutter/issues/41006#issuecomment-533748314?

**Comment by luis901101** [comment]
Hi, thanks for your answer. I just tried that and the result is the same...

> Error: Could not locate device support files. This iPhone 6s is running iOS 13.5.1 (17F80), which may not be supported by this version of Xcode. An updated version of Xcode may be found on the App Store or at developer.apple.com. (code 601)

It seems something changed in this 1.17.4 flutter version regarding devices listing. I really miss to be able to use Flutter Attach on iOS devices with upgraded versions...

**Comment by jmagman** [comment]
Yes, in v1.17.4 `flutter devices` requires Xcode to be installed and working. 
As a side note, you shouldn't need to upgrade Xcode, you just need to get the iOS 13.5.1 SDK on whatever old version of Xcode you're using.  You would download the latest Xcode 11 and copy the SDK from that one back to your old one.  There are guides online for how to do this.

Closing, Flutter requires Xcode for iOS development. https://flutter.dev/docs/get-started/install/macos#install-xcode

**Comment by luis901101** [comment]
Hmm... as I said in the first comment:

> **Currently I'm running stable flutter 1.17.4 and Xcode 11.3.1,**

I do have Xcode working... in fact I'm currently working but with another iDevice with an older version of iOS...

My specific problem is to avoid downloading Xcode... I'm working with a very slow metered internet connection which is almost impossible to download Xcode... that's why I asked for the very specific feature of Flutter Attach that I had available on flutter v1.12.13 with my iPhone running iOS 13.5.1

**Comment by jmagman** [comment]
> This iPhone 6s is running iOS 13.5.1 (17F80), which may not be supported by this version of Xcode.

That error message means that Xcode 11.3.1 doesn't have the 13.5.1 SDK, so it can't deploy to that device.  `flutter devices` now asks Xcode what devices are attached, and it doesn't know what to with your device running 13.5.1.

The [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-11_3_1-release-notes) say 11.3.1 supports iOS 13.3.  So you need to get the 13.5.1 SDK into Xcode 11.3.1.  If you Google around you'll find how to download the SDK and symlink it into the right spot.

**Comment by luis901101** [comment]
Ok ok. I will find the way to download xCode 11.5 and solve this.
 But I don’t understand what you say about Xcode can’t deploy to iOS 11.5.1 and flutter asking Xcode about devices attached...
Currently if I open my flutter project with Xcode I can see my iPhone in the list of devices to Run... and I can run the project to my iPhone only at the end of the build in the moment of start the app in the iPhone I get a Dialog from Xcode explaining what we know... but the app gets installed in the device...
I’m not saying I want to debug my app directly from build... I just say that with previous flutter stable version I was able to attach to the running app in my iPhone... so is the same Xcode, the same Mac OS, the same iPhone with the same version... the only change is the flutter version that seems to be doing something different when listing available devices...
Anyway thanks for your answers.

**Comment by jmagman** [comment]
The behavior change was introduced with https://github.com/flutter/flutter/pull/49854.

**Comment by luis901101** [comment]
Ok, makes sense.
Thanks again
