### ISSUE TITLE
Gallery, Scrollable tabs: Odd behavior and visuals when you switch between Icons&Text and Icons

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6055]
Open Gallery, either landscape or portrait. Either Android or iOS.

Go into Scrollable tabs. Swipe side to side. Then use the menu to choose Icons. Then swipe once.

I see the underline jump from nowhere (disappears off the screen) and then back to under the icon for the current tab.

Then, switch back to Icons & Text. Swipe left.

I see the underline jump to under the line, but above the text, and then animate to the left underneath the text.

Also, I got the underline into this state at least once:

![img_0004](https://cloud.githubusercontent.com/assets/5479/18818312/dcb60842-832a-11e6-8ed5-3dcd8b55a99b.PNG)

![img_0005](https://cloud.githubusercontent.com/assets/5479/18818313/e0454eaa-832a-11e6-96ab-c33e84bcea2f.PNG)

**Comment by eseidelGoogle** [comment]
I'm no longer able to reproduce.  @HansMuller recently re-wrote tabs and likely fixed this. :D
