### ISSUE TITLE
RefreshIndicator drag distance is to long

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#60557]
The drag distance of the RefreshIndicator is to long.

If you are used to the length of the RefreshIndicator drag distance of native android apps, it is very frustrating to fail attempting to refresh a flutter application as you have to drag down way further in flutter...

**Comment by darshankawar** [comment]
Hi @lazylazyllama,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample. You mentioned about the drag distance of native android apps, it would help if you could also provide what difference you see as compared to Flutter. Probably a video or gif would do.
Thank you

**Comment by lazylazyllama** [comment]
Okay, I'm very busy right now, but I'll try do come up with something in the next weeks :)

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
