### ISSUE TITLE
Allow users to opt out of default shortcuts

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#60566]
## Use case

A new default shortcut was recently introduced to Flutter, where the escape key dismisses modal routes (https://github.com/flutter/flutter/pull/59310). This didn't work for my project, so to get around this behavior, I defined my own shortcuts/actions logic that treats the escape key as a no-op. That works, but it feels a bit heavy-weight, and should Flutter change the default shortcuts in the future, there wouldn't be a great way for me to discover that logic was no longer necessary. Is there a different recommended best practice for how to do this? If not, it would be nice to have a lighter-weight way to disable individual default shortcuts/actions.

**Comment by gspencergoog** [comment]
In your `MaterialApp`/`CupertinoApp` constructor, you can supply a different default set of shortcuts by setting the `shortcuts` attribute. You can also get the default set of shortcuts that Flutter provides from `WidgetsApp.defaultShortcuts`, so you can either provide your own set of shortcuts to completely replace them, or you can filter the existing defaults.

For instance, if you only wanted tab to go to the next control, and no other shortcuts defined, do this at the top level of your app:

```dart
  Widget build(BuildContext context) {
    return MaterialApp(
      shortcuts: { LogicalKeySet(LogicalKeyboardKey.tab): const NextFocusIntent() },
      home: MyHomeWidget(),
    );
  }
```

If you wanted to have all of the default shortcuts except for the escape key, you could do this:

```dart
  Widget build(BuildContext context) {
    return MaterialApp(
      shortcuts: WidgetsApp.defaultShortcuts..removeWhere((LogicalKeySet key, Intent value){
        return key == LogicalKeySet(LogicalKeyboardKey.escape);
      }),
      home: MyHomeWidget(),
    );
  }
```

Please reopen if you have more questions.
