### ISSUE TITLE
showTimePicker() ability to set selectable intervals

### ISSUE THREAD

**Issue by Kayes-Islam** [flutter/flutter#60573]
My use case is that I want users to be able to select a time every quarter of an hour. Currently I see no way of achieving this using the showTimePicker(). It would be great to have an option to pass in a selectable interval. 

Note that there is also [this issue](https://github.com/flutter/flutter/issues/23717) which is potentially related, but I thought I'd raise a separate issue anyway.

**Comment by sh3rlock97** [comment]
+1 from me. It's a feature native widgets always offer and there's no method to create this function yourself without rebuilding the whole widget

**Comment by digarahayu** [comment]
+1 , I'm looking for this one, that features really useful.

**Comment by Fleximex** [comment]
This should really be addressed.

In the mean time I made this package which has a modified Time Picker in it.
You can pass the interval yourself (from 1 to 30).

https://pub.dev/packages/interval_time_picker

**Comment by jorwan** [comment]
You could try using this temporal solution using: [time_picker_widget](https://pub.dev/packages/time_picker_widget)

[![enter image description here][1]][1]

Copy the following code into this [DEMO](https://dartpad.dartlang.org/5c32e473c8c1c9687966453d0dcf42de?)
```dart
showCustomTimePicker(
    context: context,
    // It is a must if you provide selectableTimePredicate
    onFailValidation: (context) =>
        showMessage(context, 'Unavailable selection.'),
    initialTime: TimeOfDay(
        hour: _availableHours.first,
        minute: 0),
    selectableTimePredicate: (time) =>
        _availableHours.indexOf(time.hour) != -1 &&
        time.minute % 15 == 0).then(
    (time) =>
        setState(() => selectedTime = time?.format(context))),
```


  [1]: https://i.stack.imgur.com/SZEtC.png

**Comment by royabousamra** [comment]
This would be really helpful.

**Comment by dramcio** [comment]
Hello, any progress on this issue?

**Comment by msiviero** [comment]
I could use it. What are the steps for this to be taken into account? I can help somehow (maybe with a PR)?

**Comment by jorwan** [comment]
> I could use it. What are the steps for this to be taken into account? I can help somehow (maybe with a PR)?

@msiviero 
You could create you own version applying changes to the original flutter code and publishing it in pub.dev

that's what I did in the meantime here: 
https://pub.dev/packages/time_picker_widget

**Comment by msiviero** [comment]
> > I could use it. What are the steps for this to be taken into account? I can help somehow (maybe with a PR)?
> 
> @msiviero
> You could create you own version applying changes to the original flutter code and publishing it in pub.dev
> 
> that's what I did in the meantime here:
> https://pub.dev/packages/time_picker_widget

Of course. I'm actually doing it for now (can't use your package because of null safety). But I still think that this should be a feature in the core package. That's why I asked if somehow I could help land it

**Comment by jorwan** [comment]
> > > I could use it. What are the steps for this to be taken into account? I can help somehow (maybe with a PR)?
> > 
> > 
> > @msiviero
> > You could create you own version applying changes to the original flutter code and publishing it in pub.dev
> > that's what I did in the meantime here:
> > https://pub.dev/packages/time_picker_widget
> 
> Of course. I'm actually doing it for now (can't use your package because of null safety). But I still think that this should be a feature in the core package. That's why I asked if somehow I could help land it

Thanks for the feedback. It is now null safety.

**Comment by rami-a** [comment]
Hey folks,

As I mentioned in https://github.com/flutter/flutter/issues/23717, after speaking with designers on the Material team, it's been decided that limiting selection on the TimePicker is not something we want to support officially. We see the time picker UI as something similar to a slider, so having disabled values within that could become confusing.

My recommendation is to either handle the validation of the time after the user taps OK or to build something custom (using dropdowns or existing packages, which someone seems to have already created).

The Material team is in the early phases of designing/creating a more desktop appropriate time picker selection UI (that might involve dropdown-like behavior). Once that is in a more solidified state, it could be something we add to Flutter as a new widget.

That being said, I'm going to close out this issue. Thanks for all the feedback and important discussion!

**Comment by Kayes-Islam** [comment]
@rami-a although #23717 is another potential way to solve the issue, this issue is in fact different. 

>We see the time picker UI as something similar to a slider, so having disabled values within that could become confusing.

Similar to the `divisions` argument of the [Slider](https://api.flutter.dev/flutter/material/Slider/Slider.html) we are requesting an interval for the time picker. Request a reconsider and reopen.
