### ISSUE TITLE
Checking Dart SDK version... No executable found matching command "dotnet.."

### ISSUE THREAD

**Issue by zeyadsharo** [flutter/flutter#60581]
![image](https://user-images.githubusercontent.com/33178745/86095012-f75ced80-bab9-11ea-8aeb-dcec9c8852ae.png)

**Comment by TahaTesser** [comment]
Hi @zeyadsharo 
Which is version of the flutter you have installed? Can you please make sure flutter setup is located and please complete `flutter doctor -v` with verbose

I can notice your user directory `HELP TECH` but command only says `HELP`
Thank you

**Comment by zeyadsharo** [comment]
@TahaTesser 
some problem 
![image](https://user-images.githubusercontent.com/33178745/86114665-888c8e00-bad3-11ea-868f-7e2bc3964262.png)

**Comment by zeyadsharo** [comment]
i uninstall flutter and downloaded again
