### ISSUE TITLE
Rich text support in Push notification (Custom View)

### ISSUE THREAD

**Issue by rakeshh025** [flutter/flutter#60587]
## Use case

I want to see rich text content in Push notification (status bar notification). Currently it displays the html tag as such.

## Proposal

If there's way to provide custom view for displaying notification, it would be great.

**Comment by VladyslavBondarenko** [comment]
@rakeshh025 
you can try https://pub.dev/packages/flutter_local_notifications

**Comment by rakeshh025** [comment]
I'm using fcm for push notifications

**Comment by stuartmorgan** [comment]
The Firebase plugins have moved to https://github.com/firebaseextended/flutterfire so this will need to be re-filed there.
