### ISSUE TITLE
some devfs tests fail locally

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#6058]
I see a devfs test failure when run locally (cd packages/flutter_tools; dart test/devfs_test.dart):

```
devfs modify existing file on local file system
  Expected: true
    Actual: <false>

  package:test                                       expect
  test/devfs_test.dart 46:7                          main.<fn>.<fn>.<async>
  dart:async                                         _SyncCompleter.complete
  package:flutter_tools/src/devfs.dart 433:3         DevFS.update.<async>
  dart:async                                         _SyncCompleter.complete
  package:flutter_tools/src/devfs.dart 555:5         DevFS._scanDirectory.<async>
  ===== asynchronous gap ===========================
  dart:async                                         _Completer.completeError
  test/devfs_test.dart 47:6                          main.<fn>.<fn>.<async>
  dart:async                                         _SyncCompleter.complete
  package:flutter_tools/src/devfs.dart 433:3         DevFS.update.<async>
  dart:async                                         _SyncCompleter.complete
  package:flutter_tools/src/devfs.dart 555:5         DevFS._scanDirectory.<async>
  ===== asynchronous gap ===========================
  dart:async                                         _asyncThenWrapperHelper
  test/devfs_test.dart                               main.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 75:26  AppContext._run.<async>
  ===== asynchronous gap ===========================
  dart:async                                         Future.Future.microtask
  package:flutter_tools/src/base/context.dart        AppContext._run
  package:flutter_tools/src/base/context.dart 66:13  AppContext.runInZone.<fn>
  dart:async                                         runZoned
  package:flutter_tools/src/base/context.dart 65:12  AppContext.runInZone
  test/src/context.dart 68:24                        testUsingContext.<fn>
```

I think state from one test is interfered with that in another. It looks like the tests share a common  `MockDevFSOperations` object, and one test is clearing out the state (via `MockDevFSOperations.contains()`) that another depends on.

These tests should probably be reworked so that all test setup happens in a `setUp` method and there's no dependencies on tests running in a certain order.

/cc @johnmccutchan

**Comment by sethladd** [comment]
Is this still happening?

**Comment by johnmccutchan** [comment]
Assuming this is being run on a mac. This was a bug that only affected the unit test and @lukechurch fixed it recently.

**Comment by devoncarew** [comment]
> These tests should probably be reworked so that all test setup happens in a setUp method and there's no dependencies on tests running in a certain order.

This is still an issue - unless these tests have been re-written, they depend on running in a certain order. They should be changed so that they tests can run in any order, or some run and not others, without seeing failures.

**Comment by johnmccutchan** [comment]
`package:test` guarantees tests run in the order they are registered and these DevFS tests are specifically ordered. The DevFS tests could be trivially refactored to not depend on each other but that doesn't seem high priority. Maybe @lukechurch has cycles.

**Comment by devoncarew** [comment]
I'm not sure it has any such guarantee - @nex3 would know. You are able to run specific tests by name, which in this case, the tests would fail.

> The DevFS tests could be trivially refactored to not depend on each other

That would be great, and what this bug is tracking.

**Comment by nex3** [comment]
`test` doesn't provide any guarantee about test ordering. In practice currently we do run tests within a given suite in-order, but this could change in the future—for example, we've talked about splitting up large suites to run in parallel across multiple isolates.

In general, every test should be able to run in isolation from any other test. If you're not in a world where running each test individually succeeds, you're off the happy path and test may break you.

**Comment by Hixie** [comment]
@nex3 It would be good to make the test framework randomise the order, because otherwise people will assume the order is guaranteed regardless of what the documentation says.

**Comment by nex3** [comment]
I think that would cause more pain than it would be worth. I'm not interested in making people's tests more flaky just to prove a point.

**Comment by Hixie** [comment]
In that case, I am afraid the `test` package does guarantee the test execution order, whether you intended it to or not, because test suites now depend on that order and so it can't be changed without breaking them.

**Comment by eseidelGoogle** [comment]
FYI @tvolkert who is working on wiring up these flutter_tool tests in Google's internal test running system and may hit this.

**Comment by johnmccutchan** [comment]
@tvolkert has switched these tests over to the memory filesystem. Closing as old.
