### ISSUE TITLE
Possible bug in TimeOfDay

### ISSUE THREAD

**Issue by arielbh** [flutter/flutter#60592]
When the instance of TimesOfDay is initiated according to 24 hours clock with hour:0, minutes: X (doesn't matter), it should contain the value 12 in hourOfPeriod (which should correlate to 12 in 12 hours clock). Currently it still shows 0.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

**Comment by VladyslavBondarenko** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TimeOfDay time1 = TimeOfDay.fromDateTime(DateTime.parse('2018-10-20 00:30:00Z'));
  TimeOfDay time2 = TimeOfDay.fromDateTime(DateTime.parse('2018-10-20 12:30:00Z'));

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Column(
          children: [
            Text('${time1.hourOfPeriod.toString()} ${time1.period.toString()}'),
            Text('${time2.hourOfPeriod.toString()} ${time2.period.toString()}'),
          ],
        ),
      ),
    );
  }
}
```
Result:

```
0 DatePeriod.am
0 DatePeriod.pm
```

I'm not sure is it intended to be so when using hourOfPeriod alone, but with period 12 am and 12 pm [would look more correct](https://en.wikipedia.org/wiki/12-hour_clock) in the case. Tried with master `1.20.0-3.0.pre.100`

**Comment by HansMuller** [comment]
CC @darrenaustin 
If nothing else, we need to document what the 12/24 edge cases mean.

**Comment by arielbh** [comment]
Are we getting this fixed anytime soon?
