### ISSUE TITLE
Snackbar action button is not bold

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#6059]
The "UNDO" snack bar action button on the [spec site](https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-specs) is bold and right aligned. This does not match flutter...

Flutter snackbar:
<img width="336" alt="screen shot 2016-09-26 at 8 18 35 am" src="https://cloud.githubusercontent.com/assets/85351/18840067/355263d2-83c2-11e6-86c7-4307351802cf.png">
Flutter snackbar while being pressed:
<img width="327" alt="png-undo" src="https://cloud.githubusercontent.com/assets/85351/18840116/5657d094-83c2-11e6-82df-f3b8dcc2eda3.png">

bazel metadata version: f0d2f5c58a0d0910d325d0223ae13bb4c3b22719

**Comment by abarth** [comment]
I think we're getting the correct font weight.  The spec says "medium", which is just slightly heavier than normal (and not nearly as heavy as bold).  That appears to be what we're using.

(The position is clearly wrong--fixing.)

**Comment by drewwarren** [comment]
> I think we're getting the correct font weight. The spec says "medium", which is just slightly heavier than normal (and not nearly as heavy as bold). That appears to be what we're using.

The iPhone 5s screenshots linked in the bug definitely look thin compared to the spec site. The positioning is my biggest concern so glad to hear that is getting a quick fix.

**Comment by abarth** [comment]
> definitely look thin compared to the spec site

Yes, I agree the screen shot doesn't look right.  Maybe we're asking for medium but not actually getting it for some reason.

**Comment by abarth** [comment]
Re-opening for the boldness issue.

**Comment by drewwarren** [comment]
The font weight issue was related to me using an alternate build environment. Not an issue using flutter run.

**Comment by eseidelGoogle** [comment]
32116049 is the internal issue number for future reference.
