### ISSUE TITLE
$ flutter init not so happy on OSX

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#606]
brettmorgan@brettmorgan-macbookpro2 ~/dartlang-toys> flutter init -o my_app
Creating my_app...
my_app/.gitignore
my_app/pubspec.yaml
my_app/README.md
my_app/lib/main.dart

Running pub get...
Resolving dependencies...
+ flutter 0.0.19
+ sky_tools 0.0.38
Changed 2 dependencies!
Precompiling executables...
Loading source assets...
Precompiled flutter:flutter.
All done! To run your application:

  $ cd my_app
  $ flutter start --checked

brettmorgan@brettmorgan-macbookpro2 ~/dartlang-toys> cd my_app/
brettmorgan@brettmorgan-macbookpro2 ~/d/my_app> flutter start --checked
Invalid argument(s): join("packages/sky_tools/cache", "sky_engine", null, "Release", "darwin-x64"): part 2 was null, but part 3 was not.

Exception:
package:path/src/context.dart 572                               _validateArgList
package:path/src/context.dart 210                               Context.join
package:path/path.dart 225                                      join
package:sky_tools/src/artifacts.dart 205                        ArtifactStore._getCacheDirForArtifact
package:sky_tools/src/artifacts.dart 213                        ArtifactStore.getPath.<async>
dart:async                                                      _Completer.completeError
package:sky_tools/src/artifacts.dart 227                        ArtifactStore.getPath.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/artifacts.dart                            ArtifactStore.getPath
package:sky_tools/src/toolchain.dart 36                         _getCompilerPath.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/toolchain.dart                            _getCompilerPath
package:sky_tools/src/toolchain.dart 46                         Toolchain.forConfigs.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/toolchain.dart                            Toolchain.forConfigs
package:sky_tools/src/commands/flutter_command.dart 28          FlutterCommand.downloadToolchain.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/flutter_command.dart             FlutterCommand.downloadToolchain
package:sky_tools/src/commands/start.dart 48                    StartCommand.runInProject.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/start.dart                       StartCommand.runInProject
package:sky_tools/src/commands/flutter_command.dart 56          FlutterCommand.run.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 178                            CommandRunner.runCommand.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 131                            CommandRunner.runCommand
package:sky_tools/src/commands/flutter_command_runner.dart 108  FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                            CommandRunner.run.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 105                            CommandRunner.run
package:sky_tools/executable.dart 60                            main.<async>.<fn>.<async>
package:stack_trace                                             Chain.capture
package:sky_tools/executable.dart 59                            main.<async>

brettmorgan@brettmorgan-macbookpro2 ~/d/my_app> dart --version
Dart VM version: 1.13.0 (Wed Nov 18 12:15:29 2015) on "macos_x64"

**Comment by abarth** [comment]
Can you run `which flutter` ?

My guess is that you're using an old version of the `flutter` too.  Can you try `pub global deactivate flutter` and then follow the getting started steps from this page: http://flutter.io/getting-started/ ?

**Comment by domesticmouse** [comment]
On the money. Thanks!
