### ISSUE TITLE
multi_widget_construction_perf__timeline_summary benchmarks have all regressed

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60608]
Clear signal at https://github.com/flutter/flutter/pull/60412.

![Screen Shot 2020-06-30 at 8 25 13 AM](https://user-images.githubusercontent.com/1435716/86144986-3e8fb200-baab-11ea-94bb-5088de7d3c09.png)

Given that a change in tests is implicated, is this intended?

Given the magnitude of the regression (if that's what it is), I'm marking this a P0, but feel free to downgrade or rebaseline if my hunch is correct.

**Comment by liyuqian** [comment]
CC @CareF . Is the performance change expected, and reproducible locally on your Moto G4?

**Comment by CareF** [comment]
It is intended because #60412 fixed a bug causing half of the elements out of the page. I rebased it.
