### ISSUE TITLE
Gallery, Shrine, Tablet: Layout of Shrine home

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6060]
Shrine on a Nexus 9:

![screenshot_20160926-083646 1](https://cloud.githubusercontent.com/assets/5479/18840823/b4e398da-83c4-11e6-90bb-775b8f4f38dc.png)

**Comment by eseidelGoogle** [comment]
This is probably the same as https://github.com/flutter/flutter/issues/5135.

**Comment by eseidelGoogle** [comment]
Or the same as https://github.com/flutter/flutter/issues/5134.
