### ISSUE TITLE
Overscroll glow will jump if you move your finger horizontally

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6061]
Open the Gallery on Android, then scroll all the way to the bottom. Scroll up to trigger the overscroll glow, then move your finger horizontally. Notice how the overscroll glow will jump to the right, and then fade down.

Ideally, the glow will follow your finger.

To compare, open the Settings app on Android, and then scroll to the bottom. Trigger the glow, and move your finger horizontally. The glow will follow your finger.

See it in action: https://youtu.be/OrtUUWyFuoo

(note: this happens on any android device, not just a Nexus 9 like the video shows)

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by dragostis** [comment]
I'm pretty sure this is going to be solved as part of #5288.

**Comment by eseidelGoogle** [comment]
Related to https://github.com/flutter/flutter/issues/6709, but I no longer see this exact bug.  Closing.
