### ISSUE TITLE
Application won’t run the simulator

### ISSUE THREAD

**Issue by UnstoppableGeek1** [flutter/flutter#60620]
Right after I finished install flutter I went on vs cod and created a new flutter project. When I tried to run the main.dart file it ran on the iPhone 11 Pro Max simulator the first time and then when I tried to run it again it gave me an error saying it could not run the iOS simulator. Here is a picture of what it said. 

![image](https://user-images.githubusercontent.com/64677037/86162718-19f40400-bac4-11ea-80f8-8b7245d033d9.jpeg)

**Comment by iapicca** [comment]
Hi @UnstoppableGeek1 
Can you please provide your `flutter doctor -v` and  your `flutter run --verbose`
Thank you

**Comment by UnstoppableGeek1** [comment]
Here is the doctor 

![image](https://user-images.githubusercontent.com/64677037/86228542-5a469700-bb43-11ea-9e82-07958da5061e.jpeg)![image](https://user-images.githubusercontent.com/64677037/86228544-5a469700-bb43-11ea-9182-90b2e2255e1c.jpeg)

Here is the verbose 

![image](https://user-images.githubusercontent.com/64677037/86228650-7b0eec80-bb43-11ea-934d-7099224589d0.jpeg)![image](https://user-images.githubusercontent.com/64677037/86228652-7b0eec80-bb43-11ea-85d1-1d27b05b4951.jpeg)

**Comment by iapicca** [comment]
Hi @UnstoppableGeek1 
Can you please provide your full `flutter run --verbose`. 
If the logs are too long, you may attach them as txt file.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by UnstoppableGeek1** [comment]
here is the verbose when I ran.  It ran the standard flutter project but it still showed the error when I went to the project in vs code and tried to run it. 

[Untitled document.txt](https://github.com/flutter/flutter/files/4858979/Untitled.document.txt)

**Comment by iapicca** [comment]
Hi @UnstoppableGeek1 
your logs look clean, it seems that the app was closed willingly
```bash
[   +3 ms] Sending to VM service: ext.flutter.exit({isolateId:
isolates/2299201958813095})
```
are you experiencing the issue from terminal or android studio 
or only from vs code?
Thank you

**Comment by UnstoppableGeek1** [comment]
It is happening in both vs code and android studio and in the terminal and in both android studio and the terminal it is showing the same error as it did in vs code.

**Comment by UnstoppableGeek1** [comment]
Also when I am in vs code and I try to run it on an android device simulator like the pixel 3 xl it runs perfectly fine but when I switch to the Xcode simulator and run it on any device it shows the error that was in the original picture of this post.

**Comment by iapicca** [comment]
Hi @UnstoppableGeek1 
the logs you provided look clean, 
could you provide logs representative of the issue you are encountering
Thank you

**Comment by UnstoppableGeek1** [comment]
Here is the entire log for the issue when I ran it from the terminal but it is the same exact error in android studio and in visual studio code. 

lanceaddison@MacBook-Pro ~ % cd /Users/lanceaddison/Documents/wordpair_generator 
lanceaddison@MacBook-Pro wordpair_generator % flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         4.5s
Xcode build done.                                           12.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/lanceaddison/Documents/wordpair_generator/build/ios/Debug-iphonesimul
    ator/Runner.app: resource fork, Finder information, or similar detritus not
    allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by UnstoppableGeek1** [comment]
Were you able to figure out what the issue was?

**Comment by iapicca** [comment]
HI @UnstoppableGeek1 
could you please follow the step indicated in this [answer](https://groups.google.com/g/flutter-dev/c/Q4wvTD4hN_k/m/bqjNxNslBwAJ)
Thank you
