### ISSUE TITLE
Launch activity with strict mode policy in scenario app

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#60635]
The strict mode policy ensures that the engine doesn't read or write to disk in a typical Flutter app. https://github.com/flutter/engine/commit/dc93db5ab858c3812ed49aaf8f0df85422b6a7e1#diff-6c316cfa52e434f5c02f5921476fd3f8 added this policy. 
However, this policy affects all tests including those that take screenshot tests.  As a result, screenshot test cannot save the screenshot to disk.

A workaround could be to launch a separate activity that sets the policy, and then the test verifies that the app doesn't crash.

**Comment by blasten** [comment]
cc @jason-simmons

**Comment by pedromassangocode** [comment]
[triage]
Wondering if there have been done any work to fix this in the past months.

**Comment by dnfield** [comment]
I think to do this we'd need a separate app - unless it would be acceptable to launch the activity from the main activity using something like https://firebase.google.com/docs/test-lab/android/game-loop#label-loops

**Comment by jonahwilliams** [comment]
Moving to P3 as these ... tests aren't even working right now? Doesn't really feel like a good answer.
