### ISSUE TITLE
When scrolling page size changes: "exception was thrown: Build scheduled during frame."

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#6063]
## Steps to Reproduce

In the leafy app, some types of UI configuration changes affect the length of a scrolling page.  This will be triggered by a change in the state of some stateful widget.

When this happens in debug mode, the view freezes and the trace produces an error:
I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during performLayout():
I/flutter : Build scheduled during frame.
...
## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Framework revision fa52b456ec (14 hours ago), 2016-09-25 19:30:44
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
...

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39
## Logs and Crash Reports

Happy to leave full reports with you if you wood like me to.  I'm tracking this at b/31438182.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
This is blocking customer:leafy.  @Hixie

**Comment by Hixie** [comment]
If we need a quick hack to fix it @abarth or @HansMuller can probably just silence the assert somehow for now (I'm OOO today). I'm working on a longer-term fix but it'll take a while longer since it's tied up in the scrollable refactor.

**Comment by DaveShuckerow** [comment]
I think we can get by for now if the correct fix will be in within ~3-4 weeks.  If it'll take longer than that, then having a stopgap might be useful.

In terms of priority, I'm more concerned with #6096 than this issue because that's introducing failures that require restarting the app.

**Comment by eseidelGoogle** [comment]
@Hixie is on it.  customer: fast also reported this as one of their top issues today.

**Comment by Hixie** [comment]
Still working on the longer term fix, let me know if this becomes urgent and I'll just silence the assert temporarily.

**Comment by eseidelGoogle** [comment]
Spoke with @Hixie he says this will be fixed in a few weeks.  If this is critical and a workaround is needed before then, please let us know and we can help.  @DaveShuckerow @drewwarren

**Comment by drewwarren** [comment]
Our current target for a release build is at end of this month. This is critical and would need to be resolved/worked around before that release.

**Comment by Hixie** [comment]
Does the bug manifest in release builds?

**Comment by drewwarren** [comment]
I cannot replicate this bug in release builds. Only in slow mode. This does lower the severity to our team.

**Comment by Hixie** [comment]
there's a good chance https://github.com/flutter/flutter/pull/6310 will hide this on the short term anyway

**Comment by tvolkert** [comment]
Hixie, can you see if #6310 did in deed hide this?

**Comment by Hixie** [comment]
It should have, yes.

**Comment by Hixie** [comment]
I'm closing this on the basis that we believe it's been papered over.
