### ISSUE TITLE
Running debug on iOS 14 shows "would like to find and connect to devices on your local network" popup

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60634]
```
2020-06-30 12:52:54.237973-0700 Runner[580:228465] Metal API Validation Enabled
2020-06-30 12:52:54.382810-0700 Runner[580:228698] flutter: Observatory listening on http://127.0.0.1:50735/u2EjnBszARk=/
2020-06-30 12:52:54.676675-0700 Runner[580:228686] fopen failed for data file: errno = 2 (No such file or directory)
2020-06-30 12:52:54.676742-0700 Runner[580:228686] Errors found! Invalidating cache...
2020-06-30 12:52:54.764319-0700 Runner[580:228686] fopen failed for data file: errno = 2 (No such file or directory)
2020-06-30 12:52:54.764380-0700 Runner[580:228686] Errors found! Invalidating cache...
```
![flutter_02](https://user-images.githubusercontent.com/682784/86171289-57ab5980-bad1-11ea-9a2d-c800254844c4.png)
```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-2.0.pre, on macOS 10.16 20A4299v, locale en-US)
    • Flutter version 1.20.0-2.0.pre at /Users/surry/Projects/flutter
    • Framework revision 747fe345f1 (12 days ago), 2020-06-18 08:28:03 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode-11.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • iPad  • 00008027-001925360106802E • ios        • iOS 14.0
    • macOS • macOS                     • darwin-x64 • macOS 10.16 20A4299v

! Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment]
Guessing new permissions on iOS 14 for the observatory?

**Comment by jonahwilliams** [comment]
Seems likely to be the mDNS broadcasting of the VM Service URI

**Comment by jmagman** [comment]
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast available iOS 14, maybe that will fix it.
Unfortunately adding an entitlement file to the project as a migration is going to be pretty gross.

**Comment by jmagman** [comment]
>  Apps now trigger a prompt the first time they try to interact with the local network. Until permission is granted all local network communication is blocked. The prompt includes a usage description that you specify in your app's info.plist. Apps that haven't updated to iOS 14 will show default reason text. If you notice a prompt that you don't expect for your app, you might be using a third party framework that accesses the local network.

https://developer.apple.com/videos/play/wwdc2020/10110/

We can't prevent this notification, but we can have it tell the user it's related to the dart observatory by setting [NSLocalNetworkUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription?language=objc) in the Debug and Profile Info.plist.

**Comment by meowofficial** [comment]
> We can't prevent this notification, but we can have it tell the user it's related to the dart observatory by setting [NSLocalNetworkUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription?language=objc) in the Debug and Profile Info.plist.

What is going to happen with the app if the user refuses to allow this permission?

**Comment by jonahwilliams** [comment]
@meowofficial this does not affect production apps, only debug builds used by developers. If a developer does not want to allow mDNS then they cannot use hot reload.

**Comment by meowofficial** [comment]
Thanks for explanation!

**Comment by jmagman** [comment]
@xster how do we feel about this wording?
> Allow Flutter to attach to the Dart observatory (debug only). Your users will not see this prompt.

![flutter_01](https://user-images.githubusercontent.com/682784/91772194-3c280200-eb99-11ea-92e5-cf67432ca5da.png)

**Comment by xster** [comment]
How about "Allow Flutter tools on your computer to connect and debug your Flutter application. Will not appear on release builds". 

Since just "Flutter" might be ambiguous between meaning the app and the SDK. And "users" is a bit indirect in causation.

**Comment by jmagman** [comment]
Sounds better, what about adding "This prompt" subject to the second sentence?
> Allow Flutter tools on your computer to connect and debug your Flutter application. This prompt will not appear on release builds.

**Comment by xster** [comment]
If it fits ya, the clearer the better. I just wasn't sure what the character limit is :D

**Comment by KCWebmaster** [comment]
I had this happen on production. Any ideas?

**Comment by jmagman** [comment]
@KCWebmaster can you create a new issue and fill out the template and include more info?

**Comment by KCWebmaster** [comment]
@jmagman I have been testing and can only get it to replicate on our public guest network. Keeping the settings as disabled on the iPhone and switching to another network (open or secure) it works. I cannot figure out what it is about that network.
