### ISSUE TITLE
Hello i have issue with google sigin

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#60644]
I have used google singing package ,but i have issue with sh1,
when i create sh1 like this gradlew signingReport    then sign in   work but only on debug mode not in production,
but when i create sh1 for production like this,
C:\Users\Hello>keytool -list -v -keystore C:\Users\Hello\key.jks -alias key

and place the sh1 on firebase in google oath,, then i m getting error 10, null and the sigin not working,,,,please suggest what should i do for production to make run the google sign in

**Comment by iapicca** [comment]
Hi @atta1234 
Can you please provide your `flutter doctor -v`, 
your `flutter run --release -v`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by atta1234** [comment]
Hello instead of error 10 now it showing this 
I/flutter ( 7257): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
the email window pop successfully but when i select email then application paused with the above error,

but any how when i create sh1 in android studio in debug like gradlew Signing report and paste on fire base then it's working,
but that will not work in production,
so i have created key using flutter release guide, but when i create sh1 from that key like this
keytool -list -v -keystore C:\Users\Hello\key.jks -alias key   and store that sh1 on Firebase project, then that above error showing, so i think i have configure the project correctly on Firebase and google oath screen, etc, the issue is with release sh1


flutter doctor -v
```
PS C:\Users\Hello\Desktop\fffapp\fffdesign> flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.4 at C:\src\flutter
    • Framework revision 1ad9baa8b9 (13 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Hello\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • SM A307FN          • RF8M91DA45J   • android-arm64 • Android 10 (API 29)
    • sdk gphone x86 arm • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
PS C:\Users\Hello\Desktop\fffapp\fffdesign> 
```


```flutter run --release -v
 C:\Users\Hello\Desktop\fffapp\fffdesign> flutter run --release -v
[  +34 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +105 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +350 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.4
[  +18 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +153 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +80 ms] executing: C:\Users\Hello\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +83 ms] List of devices attached
           RF8M91DA45J            device product:a30sxx model:SM_A307FN device:a30s transport_id:6
           emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:1
[  +14 ms] C:\Users\Hello\AppData\Local\Android\sdk\platform-tools\adb.exe -s RF8M91DA45J shell getprop
[ +153 ms] C:\Users\Hello\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +75 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +91 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +8 ms] ro.hardware = exynos7904
[  +19 ms] ro.build.characteristics = phone
[   +6 ms] ro.hardware = ranchu
[  +27 ms] SM A307FN          • RF8M91DA45J   • android-arm64 • Android 10 (API 29)
[   +3 ms] sdk gphone x86 arm • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)
[  +68 ms] "flutter run" took 828ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

pubs.ymal
name: fffdesign
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.1
  flutter_typeahead: ^1.8.0
  transparent_image: ^1.0.0
  shared_preferences: ^0.5.7+3   
  uuid: ^2.0.4
  get: ^2.7.1
  flutter_country_picker: ^0.1.6
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
 
  flutter_launcher_icons: ^0.7.5
  flutter_braintree: ^0.5.3
 
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true









      

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by iapicca** [comment]
Hi @atta1234 
does this possible solutions [1](https://github.com/flutter/flutter/issues/56235#issuecomment-630951328) [2](https://stackoverflow.com/questions/47632035/google-sign-in-error-12500) work for you?
If doesn't could you please provide the logs actually running the app and attempting to sign in
`More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.`
and a reproducible code sample.
It is possible that the issue might not be related to google_sign_in plugin
Thank you



https://github.com/flutter/flutter/issues/33393
https://github.com/FirebaseExtended/flutterfire/issues/1094

**Comment by atta1234** [comment]
sir it works when i create sha1 like this gradlew signingReport,,,not sure wht it's not working with release key

**Comment by iapicca** [comment]
Hi again @atta1234 
if you already tried the proposed solutions from this [post](https://github.com/flutter/flutter/issues/60644#issuecomment-652320237) could you please provide the information listed in the same.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
