### ISSUE TITLE
[proposal] Enable more flexible theming by including a `CustomData` field in `ThemeData`

### ISSUE THREAD

**Issue by nojusr** [flutter/flutter#60643]
Anyone who has written an app that doesn't conform to flutter's theming semantics has had an issue where the `ThemeData` class doesn't support the colors they want to have or doesn't allow specific customization of widgets. Usually this can be worked around by writing a custom theme data class but then one would have to deal with state management and figuring out how to properly provide said class to any widgets that make use of it.

I suggest that `ThemeData` could allow for the developer to provide a `CustomData` object to it, which could be tailored specifically on a per-app basis. This probably sounds like a compromise because from the looks of it, `ThemeData` seems to be made to be a single class that is responsible for the whole theme of an app. Having another class attached to it probably defeats `ThemeData`'s purpose, but I argue that it's purpose is already defeated if it cannot provide the variables nessecary for a specific task.

Here's how I would imagine this working:
##
initialization:
```dart
import 'package:my_app/customThemeData.dart' ;


class App extends StatelessWidget {
  @override
  Widget build(context) {
    return MaterialApp(
      title: 'title',
      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: Color(0xFFFF0000);
        accentColor: Color(0xFF00FF00);
        customData: CustomThemeData(
          customColorVariable1: Color(0xFFFF00FF);
          customColorVariable2: Color(0xFF0000FF);
        ),
      )
    );  
  }
}
```

##
usage:
```dart
class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Theme.of(context).customData.customColorVariable1,
      child: Center(
        child: Text("Hello"),  
      ),
    ),
  }
}
```

I do see a couple of issues with doing this though:
* this change might reduce widget reusability by making it possible for widgets to be incompatible between apps
* this may make developers overuse `CustomData` to the point where proper use of `ThemeData` may be only found in official Flutter documentation

Overall though, if proper caution is given (in documentation) to never use this in libraries or any widget that the developer may want to use in another app, this change would be an elegant solution to the problem of developers not being able to extend `ThemeData`

**Comment by goderbauer** [comment]
You can just define your own InheritedWidget [1] that injects your CustomData object and makes it accessible to ancestors. 

[1] https://master-api.flutter.dev/flutter/widgets/InheritedWidget-class.html

**Comment by thedejifab** [comment]
The inherited approach suggested by @goderbauer works just fine. I think another explorable option is to use extension on your BuildContext @nojusr. Example below:

```
extension CustomTextThemeContext on BuildContext {
  bool get _isLight => Theme.of(this).brightness == Brightness.light;

  TextStyle get text18Medium => TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.w500,
   );
}
```

then you can call this from your widget using `context.text18Medium`

**Comment by Piinks** [comment]
This is now supported through ThemeExtension. See the API docs for a video and sample code: https://api.flutter.dev/flutter/material/ThemeExtension-class.html
