### ISSUE TITLE
Idon't know issues flutter

### ISSUE THREAD

**Issue by PitiDev** [flutter/flutter#60667]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Closing this, as no description / details provided about the issue. @PitiDev if you are facing an issue with Flutter, please provide details including `flutter doctor -v`, `flutter run --verbose`, steps to replicate and minimal reproducible code sample.
Thanks.
