### ISSUE TITLE
Error: ADB exited with exit code -15

### ISSUE THREAD

**Issue by hzr1140521792** [flutter/flutter#60663]
## Steps to Reproduce

1. I create a flutter project with vscode;
2.run flutter run;

## Logs

![image](https://user-images.githubusercontent.com/18465083/86199826-b2a28680-bb8d-11ea-992d-81a00dabdf29.png)

```
```

flutter doctor output
```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @hzr1140521792 
Can you please provide your `flutter run --verbose`
Please refrain from posting pictures if not necessary.
Thank you

**Comment by hzr1140521792** [comment]
hi@iapicca ,this is my flutter run --verbose, I just put the error line  where it starts

`[ +523 ms] Installing build/app/outputs/apk/app.apk... (completed in 0.5s)
[   +1 ms] Error: ADB exited with exit code -15
[   +1 ms] Warning: Failed to install APK.
[        ] Error launching application on sdk gphone x86.
[   +3 ms] "flutter run" took 34,365ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)`

**Comment by iapicca** [comment]
Hi @hzr1140521792 
could you please try this [approach](https://github.com/flutter/flutter/issues/55280#issuecomment-620837210)
Thank you

**Comment by hzr1140521792** [comment]
> Hi @hzr1140521792
> could you please try this [approach](https://github.com/flutter/flutter/issues/55280#issuecomment-620837210)
> Thank you

I Have tried it,but I didn't work

**Comment by hzr1140521792** [comment]
> > Hi @hzr1140521792
> > could you please try this [approach](https://github.com/flutter/flutter/issues/55280#issuecomment-620837210)
> > Thank you
> 
> I Have tried it,but I didn't work

I solved it with restart my computer,
Thank you very much!

**Comment by TahaTesser** [comment]
Hi @hzr1140521792  
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by jefftsai2050** [comment]
I have also met this issue. Restart mu computer does not work for me. Is this a popular issue?

**Comment by babylovelin** [comment]
I have met this issue too,Restart mu computer does not work for me.

**Comment by iapicca** [comment]
@jefftsai2050  @babylovelin 
 please try this [approach](https://github.com/flutter/flutter/issues/60663#issuecomment-652314230)
 if the issue persists I recommend to 
 file a new issue providing  your `flutter doctor -v`and  your `flutter run -v`

**Comment by babylovelin** [comment]
I resolved by Open permissions of Android studio on my mac ，privacy -> android studio

**Comment by babylovelin** [comment]
I resolved by Open permissions of Android studio on my mac ，privacy -> android studio ,but it does not always work well
