### ISSUE TITLE
RangeSlider has no property called "showValueIndicator"

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#60673]
Version:  **Flutter 1.17.5 • channel stable**

The RangeSlider docs given [here](https://pub.dev/documentation/flutter_range_slider/latest/flutter_range_slider/RangeSlider-class.html) describes a property called **showValueIndicator** for showing a label above the active thumb when the RangeSlider is active. But the RangeSlider constructor in the latest version has no such property.

**Comment by iapicca** [comment]
Hi @melwinlobo18 
your link leads to [flutter_range_slider](https://pub.dev/packages/flutter_range_slider) which is a 3rd party package
with it's own [github repo](https://github.com/boeledi/RangeSlider/issues)
not to be confused with the material design class [RangeSlider](https://api.flutter.dev/flutter/material/RangeSlider-class.html)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
