### ISSUE TITLE
Make FutureBuilder better!

### ISSUE THREAD

**Issue by hiwa-jalal** [flutter/flutter#60679]
FutureBuilder is one of most useful widget but we all know it's problem, as the FutureBuilder keep on calling future during each state re-build which is normal and understandable why it does this, but couldn't the Flutter team prevent this and make this better so we don't have to do all this boilerplate code like this:
```dart
 // inside State class
  Future someFuture;

  @override
  void initState() {
      super.initState();
      someFuture = _getFuture();
   }

_getFuture() async {
   return await DbProvider.db.someData();
}

 // inside build method
  FutureBuilder(
  future: someFuture,
  builder: .....)

```
so we can directly use it like this 
```dart
// inside build method
  FutureBuilder(
  future: DbProvider.db.someData(),
  builder: .....)
```

i mean [this](https://pub.dev/packages/enhanced_future_builder) package has already done it. so i don't see why it shouldn't be like that by default.

**Comment by VladyslavBondarenko** [comment]
Hi @hiwa-jalal 
can't you already do this? like in this example https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html#widgets.FutureBuilder.1
what is the difference with mentioned package?

**Comment by hiwa-jalal** [comment]
well as i said yes you could do that, but the difference in that package you can use the future method directly in the `FutureBuilder` without it being called for each state re-build.

**Comment by goderbauer** [comment]
I don't think that's a good idea. The way this is written, the call to `DbProvider.db.someData()` would still happen every build - the FutureBuilder would just ignore it. We could make it a callback that will only execute the first time the widget is build, but that would also give a pretty complicated API.

**Comment by hiwa-jalal** [comment]
@goderbauer yeah that make sense, i will close the issue now as the package didn't do what i thought it does.
