### ISSUE TITLE
support linux arm/aarch64 target platform

### ISSUE THREAD

**Issue by NO-ob** [flutter/flutter#60678]
## Use case

I built my flutter app for linux desktop using hover/go-flutter on x86, I wanted to try and get my app working on the pinephone but it's not possible as there are only x86 builds of flutter so it wont work on on arm/aarch64. I tried using the package build on the arch user repository but it seems to have a whole bunch of lib32 dependencies which are x86

## Proposal

To have arm builds of the flutter sdk availbable for download/use.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/53120
https://github.com/flutter/flutter/issues/60113
https://github.com/flutter/flutter/issues/60118



https://github.com/flutter/flutter/issues/60266

**Comment by christopherfujino** [comment]
I'm investigating host support for aarch64. cc @kenthinson

**Comment by christopherfujino** [comment]
@NO-ob I'm a little a confused, is your end goal to build your app for your pinephone, or to do flutter development from it?

In any case, I think target and host should be tracked separately, so I'm updating this to specifically track supporting linux arm as a flutter app target platform. For tracking host support, please see https://github.com/flutter/flutter/issues/56992.

**Comment by NO-ob** [comment]
> @NO-ob I'm a little a confused, is your end goal to build your app for your pinephone, or to do flutter development from it?
> 
> In any case, I think target and host should be tracked separately, so I'm updating this to specifically track supporting linux arm as a flutter app target platform. For tracking host support, please see #56992.

Host I think the people over at go-flutter said they needed arm engine files to get it working on arm https://github.com/go-flutter-desktop/go-flutter/issues/486 dart is already available on arm and so is go-flutter. It doesn't support cross compiling so the end goal is to build the app with go flutter on the pinephone for the pinephone

**Comment by christopherfujino** [comment]
> Host I think the people over at go-flutter said they needed arm engine files to get it working on arm [go-flutter-desktop/go-flutter#486](https://github.com/go-flutter-desktop/go-flutter/issues/486) dart is already available on arm and so is go-flutter. It doesn't support cross compiling so the end goal is to build the app with go flutter on the pinephone for the pinephone

Ahh, I see.

**Comment by christopherfujino** [comment]
x64 -> arm64 cross compile is blocked on https://github.com/flutter/flutter/issues/74929

**Comment by Iftach-Nevo** [comment]
Hi Chris, can a flutter app be built on MacOS and deployed to a Jetson Xavier NX target running Linux on arm64?

**Comment by HidenoriMatsubayashi** [comment]
>  can a flutter app be built on MacOS
No, you cannot do that. You need to use a Linux desktop.

**Comment by yangcheng** [comment]
> > can a flutter app be built on MacOS
> 
> No, you cannot do that. You need to use a Linux desktop.

is there documentation on how to do the cross compile?

**Comment by HidenoriMatsubayashi** [comment]
> is there documentation on how to do the cross compile?

You mean that cross-building for linux desktop on macOS?

**Comment by yangcheng** [comment]
> > is there documentation on how to do the cross compile?
> 
> You mean that cross-building for linux desktop on macOS?

I want to cross-build  a flutter app on an x86 machine to an embedded device running linux Arm

**Comment by HidenoriMatsubayashi** [comment]
Unfortunately, it isn't still supported. Please see https://github.com/flutter/flutter/issues/74929. (It's my task and I need to work on it. Sorry...)

**Comment by kwiatek91** [comment]
> 



> > can a flutter app be built on MacOS
> 
> No, you cannot do that. You need to use a Linux desktop.

You can build flutter app on MacOs for Linux desktop you just need to build on docker with linux image

**Comment by christopherfujino** [comment]
I am closing this issue as you can actually do Linux ARM64 desktop target builds if you run the Flutter SDK FROM a Linux ARM64 desktop machine. Note this is not documented on the website and we do not have pre-built downloads there; you need to clone the repository on the ARM64 device (the tooling was updated to detect the architecture it is being run on in https://github.com/flutter/flutter/pull/61221).

Cross-compile from an x64 host to ARM64 target is not currently possible and is being tracked in https://github.com/flutter/flutter/issues/74929.

> You can build flutter app on MacOs for Linux desktop you just need to build on docker with linux image

Yes, this is also an option, as Docker for desktop on macOS uses a Linux VM under the hood.

**Comment by kwiatek91** [comment]
> I am closing this issue as you can actually do Linux ARM64 desktop target builds if you run the Flutter SDK FROM a Linux ARM64 desktop machine. Note this is not documented on the website and we do not have pre-built downloads there; you need to clone the repository on the ARM64 device (the tooling was updated to detect the architecture it is being run on in #61221).
> 
> Cross-compile from an x64 host to ARM64 target is not currently possible and is being tracked in #74929.
> 
> > You can build flutter app on MacOs for Linux desktop you just need to build on docker with linux image
> 
> Yes, this is also an option, as Docker for desktop on macOS uses a Linux VM under the hood.

to be honest, I came here looking for help.
I am currently trying to build a flutter application on an ARM64 device (raspberry pi 4) but I am getting an error when building the release version. Unfortunately I am only able to build the --debug version. Could you please help?

```
Build process failed
[ +38 ms]
#0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1 _runBuild (package:flutter_tools/src/linux/build_linux.dart:185:5)
<asynchronous suspension>
#2 buildLinux (package:flutter_tools/src/linux/build_linux.dart:77:5)
<asynchronous suspension>
#3 BuildLinuxCommand.runCommand
(package:flutter_tools/src/commands/build_linux.dart:88:5)
<asynchronous suspension>
#4 FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#5 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6 CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#7 FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#8 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9 FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#10 run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#11 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12 main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

[ +186 ms] ensureAnalyticsSent: 162ms
[ +4 ms] Running shutdown hooks
[ +3 ms] Shutdown hooks complete
[ +3 ms] exiting with code 1
```
On a macos device with an M1 I can easily build an application using docker using flutter build linux. However using exactly the same docker image on a raspberry no longer works i get error during build.
On raspberry I also try native approach without docker, I added all libraries and tried to build the application natively but I get the same error.
