### ISSUE TITLE
Some flutter_tools tests using FakeAsync are always passing

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#60675]
There are some tests that use `FakeAsync.run()` that are not `await`ing the call, for example:

https://github.com/flutter/flutter/blob/0e735e4bca539c24cf22b8e4cd6d5340b9ae389a/packages/flutter_tools/test/general.shard/device_test.dart#L92-L95

It seems like this is resulted in the tests always passing immediately. For example adding `throw 'fail';` as the first line inside the callback does nothing - the test still passes.

I think these tests need `await` in front of the `FakeAsync().run`, however doing so right now causes them to hang - which I think is because the implementation uses `await` which queues a microtask but the queue is never flushed (since the code stops on the `await`).

Based on what @Hixie said, I think `flutter_test` is handling this by constantly pumping the microtask queue, however the flutter_tools tests don't run with flutter_test so don't have an equivilent. I think the relevant code in flutter_test is this bit:

https://github.com/flutter/flutter/blob/868c4d8ce0e890a3dff49cc306ee4ee8ebe8b088/packages/flutter_test/lib/src/binding.dart#L1128-L1146

cc @hixie @jonahwilliams

**Comment by DanTup** [comment]
For my tests, I just made a small loop that flushes the queue:

https://github.com/flutter/flutter/pull/55376/files#diff-1a0ff66910e803e1ddabc1968f7d9e8bR358-R371

I don't know if this may be suitable to use elsewhere too (it may also be worth having a lint or something to catch these - perhaps the existing unawaited futures one would work?).

**Comment by zanderso** [comment]
Bumping to P2 due to lost test coverage of currently unknown scope, and to force to surface in the next triage meeting to discuss.

**Comment by jonahwilliams** [comment]
FakeAsync cases are now updated where feasible and skips added for the existing failures. Since we can't regress further, I'm bumping to a P3

**Comment by zanderso** [comment]
What's the rough number of tests that are skipped?

**Comment by jonahwilliams** [comment]
5 test cases

**Comment by jonahwilliams** [comment]
3 test cases left

**Comment by jonahwilliams** [comment]
removing assignment because I will be OOO

**Comment by jonahwilliams** [comment]
One remaining test: https://github.com/flutter/flutter/blob/cbf885b74919bf4b0796cc216b8b80e6b3ccb266/packages/flutter_tools/test/general.shard/ios/ios_device_start_nonprebuilt_test.dart
