### ISSUE TITLE
[webview] Deprecated API Usage   New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability

### ISSUE THREAD

**Issue by azaman2204** [flutter/flutter#60687]
Hi @jayeshpansheriya 
You probably mistaking `UIWebView` with `WKWebView ` 
"we strongly encourage you to update to WKWebView, as soon as possible, for improved security and reliability. "[Reference](https://mobilefirstplatform.ibmcloud.com/blog/2020/01/27/Removal-of-UIWebview/)

Are you sure about the cause of rejection? Can you please more details?
Can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/56281#issuecomment-623441654_

I had the same issue today when upload to appstore as follow;
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Any resolution on this?

[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Mac OS X 10.15.5 19F101, locale en-SG)
    • Flutter version 1.19.0-4.2.pre at /Users/macbook/Development/flutter
    • Framework revision 9b9b543d92 (9 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (4th generation) • D19F029D-B726-4380-B821-1D08CA1000AD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
    • Web Server                            • web-server                           • web-javascript • Flutter Tools
    • Chrome                                • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

**Comment by TahaTesser** [comment]
Hi @azaman2204 
Can you please provide your `pubspec.yaml`?
Thank you

**Comment by azaman2204** [comment]
Hi Taha
Below is my pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_radio: ^0.1.8
  carousel_slider: ^2.1.0
  rflutter_alert: ^1.0.3
  url_launcher: ^5.4.7
  flutter_web_view: ^0.0.6
  firebase_messaging: ^6.0.15
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  audioplayers: ^0.15.1
  provider: ^4.1.2
  get_it: ^4.0.2
  webview_flutter: ^0.3.22+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  circular_bottom_navigation: ^1.0.1
  google_fonts: ^1.1.0
  libpray: ^0.2.0
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation:

**Comment by sakina1403** [comment]
Heyy @TahaTesser I am facing the same issue. How can we get the culprit plugin causing this? Is there any way to do so?

**Comment by magic-coding** [comment]
I'm getting the same error.

`ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.`

**Comment by magic-coding** [comment]
After i remove the `flutter_qr_bar_scanner: ^1.0.2` plugin the app accepted by Apple.
The issue caused by [https://github.com/contactlutforrahman/flutter_qr_bar_scanner](https://github.com/contactlutforrahman/flutter_qr_bar_scanner)

**Comment by congfandi** [comment]
i got this issue.. now i cant upload anything to the appstore.. please help to solved this issue

**Comment by magic-coding** [comment]
@congfandi please share your pubspec

**Comment by congfandi** [comment]
@magic-coding  here

```cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  flutter_image_compress: ^0.6.5+1
  provider: ^4.0.4
  cached_network_image: ^2.0.0
  flutter_html: ^0.11.1
  sqflite: ^1.3.0
  path_provider: ^1.5.1
  autocomplete_textfield: ^1.7.3
  overlay_support: ^1.0.3
  google_maps_flutter: ^0.5.26+4
  geocoder: ^0.2.1
  location: ^3.0.2
  flutter_web_view: ^0.0.6
  flutter_webview_plugin: ^0.3.11
  intl: ^0.16.1
  toast: ^0.1.5
  banner_view: ^1.1.2
  package_info: ^0.4.0+18
  open_appstore: ^1.0.2
  tutorial_coach_mark: ^0.3.0
  sentry: ^3.0.1
  device_info: ^0.4.2+4
  flutter_countdown_timer: ^1.0.0
  flutter_downloader: ^1.4.4
  barcode_widget: ^1.4.0
  whatsapp_unilink: ^1.0.0+1
  url_launcher: ^5.5.0
  firebase_messaging: ^6.0.16```

**Comment by endrelovas** [comment]
The way I found it was the following. I went to ~/.pub/cache/hosted/pub.datlang.org folder (there has to similar under windows as well) where I ran a full search to find files containing "UIWebView".

For me it was flutter_full_pdf_viewer causing the issue. Checked the repo and updated the version which did not use UIWebView anymore.

**Comment by congfandi** [comment]
guys, is there any way to resolve this issue ?

**Comment by endrelovas** [comment]
> guys, is there any way to resolve this issue ?

@congfandi 
Just do a full text search in your .pub cache folder for "UIWebView". It will list all your dependencies that might use it. Then consider replacing, removing, rewriting, upgrading those plugins. It really comes to that.

**Comment by congfandi** [comment]
> > guys, is there any way to resolve this issue ?
> 
> @congfandi
> Just do a full text search in your .pub cache folder for "UIWebView". It will list all your dependencies that might use it. Then consider replacing, removing, rewriting, upgrading those plugins. It really comes to that.

OK, I have been find the lib contains UIWebView and its found on web_view_plugin .. i remove that an replacing with another 1.. then appstore accept my App..

Thanks @endrelovas

**Comment by ChenPengHuang** [comment]
I has same problem， please help me

**Comment by mzyadatuba** [comment]
any solution ????

**Comment by JoeMan97** [comment]
We are facing this problem for almost 1 week. This is our case:

pubspec.yaml

**Comment by JoeMan97** [comment]
I got my solution, the problem was with the package flutter_conekta. 

And how I found the solution? Well, I went to xCode, selected the search tab on the left panel and searched UIWebView.

Hope this helps someone.

**Comment by stuartmorgan** [comment]
No plugins maintained by the Flutter team use UIWebView. Anyone experiencing this needs to find the third-party plugin causing this, as described above.

Closing, as there is no Flutter bug here.

**Comment by mohadel92** [comment]
> No plugins maintained by the Flutter team use UIWebView. Anyone experiencing this needs to find the third-party plugin causing this, as described above.
> 
> Closing, as there is no Flutter bug here.

how to find it please

**Comment by stuartmorgan** [comment]
You'll need to search the source of the plugins you are using.

**Comment by mohadel92** [comment]
from my personal experience 
i want to document that the issue of Deprecation UIWebView has no  direct relation with official `webview_flutter`
this happens because third party lib. implements older version of `webview_flutter` in my case was  `twitter_auth`, `flutter_html` and `flutter_twitter_login` on older version of flutter [ `1.22.6`in my case]
so removal of previously mention 3 packages was solution or upgrading to flutter 2 then updating these packages
