### ISSUE TITLE
iOS build break after cleaning: proj/example/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'myapp' not found

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#60680]
## Steps to Reproduce

- build a plugin project
- open iOS module in Xcode using Android Studio context menu `Flutter > Open iOS module in Xcode`
- configure provisioning to build and run in Xcode
- clean and rebuild
- got error 

```sh
proj/example/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'myapp' not found     
@import myapp;
```

- now if we build it from Android Studio, the build can still pass. `myapp.framework` can be found under `proj/example/build/ios/Debug-iphoneos`
- remove generated frameworks under `proj/example/build/ios/Debug-iphoneos`
- now we can no longer build iOS app from Android Studio or with `flutter build ios` from Terminal.. build fails with the same error as the issue title says

**Expected results:** 

App should be able to clean build from Xcode once boot-strapped from Android Studio.

**Actual results:** 

The project is irreversibly damaged for iOS.

<details>
  <summary>Logs</summary>

```
```

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.19.0-1.0.pre at /Applications/flutter
    • Framework revision 456d80b9dd (7 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Applications/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • ONEPLUS A6000   • dd2e267b                                 • android-arm64 • Android 10 (API 29)
    • MyiPhone • b06f169665fe7a20d2dfcc6ae06b02247e557d06 • ios           • iOS 13.5.1

• No issues found!
```

</details>

**Comment by kakyoism** [comment]
So I found a workaround, very ugly hack but works:

## Step 1

When flutter successfully builds iOS for the project for the first time, I have to preserve the following dependency frameworks 

- `proj/example/build/ios/Debug-iphoneos/myapp.framework`
- `proj/example/build/ios/Debug-iphoneos/Pod_Runner.framework`

source-control it, along with the `Release-iphoneos` version.


## Step 2
Clean then rebuild Runner in Xcode, to my surprise, flutter-generated Xcode project looks for the two framework as dependencies under

- `proj/example/ios/_build/Products/Debug-iphoneos`

which has been cleaned up. So I get the build break described in the issue.

## Step 3

Now manually copy or copy using a pre-build script those preserved frameworks to `proj/example/ios/_build/Products/Debug-iphoneos`.


## Step 4

Rebuild Runner and succeed.


## Bug??

IMHO, this sounds a bug on flutter side. The `_build` folder seems completely unnecessary. I didn't change the build product path of flutter-generated projects including `Pods` (`${SRCROOT}/../build`), which by design would place the dependency framework to `proj/example/build/ios/Debug-iphoneos`. Then how come Runner insists on finding the dependencies at the wrong places?

**Comment by jmagman** [comment]
> BTW, the whole time I've been using the Runner.xcworkspace, instead of .xcodeproj, as the CocoaPods convention demands.

That's why the module wasn't found, see https://github.com/flutter/flutter/issues/10770.

Build-clean-rebuild should work fine if you have the workspace open instead of the project.  Closing.

**Comment by kakyoism** [comment]
There is still one catch:

The build product were generated under 

```
flutterproj/example/ios/_build
```

But for some reason, after cleaning `Pods_Runner.framework` and `flutterproj.framework` are not copied to that folder from its original location. I had to manually copied them over to fix the build.

Is this a bug?

**Comment by jmagman** [comment]
A `flutter clean` in the example directory should delete the entire `build` directory, and a new `flutter run` or `flutter build` command should recreate that file structure.  The underlying Xcode command line calls are copying those frameworks around.
```
now if we build it from Android Studio, the build can still pass. myapp.framework can be found under proj/example/build/ios/Debug-iphoneos
remove generated frameworks under proj/example/build/ios/Debug-iphoneos
```
You're deleting individual frameworks out from under Xcode?  You should either be running `flutter clean` or cleaning from Xcode's workspace, not digging into Xcode's build cache and deleting files out from under it.
Can you give us more context about why you're doing it like that?

**Comment by kakyoism** [comment]
> A `flutter clean` in the example directory should delete the entire `build` directory, and a new `flutter run` or `flutter build` command should recreate that file structure. The underlying Xcode command line calls are copying those frameworks around.
> 
> ```
> now if we build it from Android Studio, the build can still pass. myapp.framework can be found under proj/example/build/ios/Debug-iphoneos
> remove generated frameworks under proj/example/build/ios/Debug-iphoneos
> ```
> 
> You're deleting individual frameworks out from under Xcode? You should either be running `flutter clean` or cleaning from Xcode's workspace, not digging into Xcode's build cache and deleting files out from under it.
> Can you give us more context about why you're doing it like that?

No I never mess around in the file system. I simply hit "Clean" in Xcode workspace and the frameworks just disappeared.

But it's suspicious that the folder path I quoted is named `_build` with a leading underscore. 

```sh
myapp/example/ios/_build
```
It's at the same level as the `proj/example/build`.

I checked my Xcode Runner project and couldn't find this pattern in any of the build product or intermediate folders, including all the paths in my Xcode global preference.

You didn't mention this folder either.



Is this specified by some flutter internal processes?

**Comment by jmagman** [comment]
I just created a new plugin on the beta channel, open ios/Runner.xcworkspace in Xcode, and have been building, cleaning, building with no issues.  I don't see an `ios/_build/` directory.

Nothing in flutter should be creating `_build` or adding anything in there to search paths.  CocoaPods is responsible for building and copying `Pods_Runner.framework` and `myapp.framework` and setting up the example app's search paths to point to the right place.  That's usually in in the `Pods` directory though.  If you're running from Xcode, it's going to put those products in whatever you have set up as your DerivedData directory.

Wondering if you have a relative DerivedData location set up in Xcode.

1. Can we get a screenshot of Xcode > Preferences > Locations
1. Screenshot of Xcode > Preferences > Locations > Derived Data > Advanced...
1. Open `ios/Runner.xcodeproj` (since that's what you had open when you originally reported).  
a. Screenshot of File > Project Settings... 
b. Screenshot of the Advanced... button
1. Open `ios/Runner.xcworkspace`.
a. Screenshot of File > Workspace Settings... 
b. Screenshot of the Advanced... button

**Comment by kakyoism** [comment]
Thanks for the pointers. Please see below.
> 2. Screenshot of Xcode > Preferences > Locations > Derived Data > Advanced...

So it's really here that the `_build` folder gets created and messed up the build process.

<img width="798" alt="Screen Shot 2020-07-31 at 11 47 45" src="https://user-images.githubusercontent.com/485051/88998017-abed6780-d323-11ea-81a0-cea13264fc62.png">


However, I just tried to restore it to the following setup

<img width="577" alt="Screen Shot 2020-07-31 at 11 48 50" src="https://user-images.githubusercontent.com/485051/88998077-d2ab9e00-d323-11ea-8c9e-09655713fc8d.png">


And the problem persisted: No dependency frameworks created under the Unique location

```sh
~/Library/Developer/Xcode/DerivedData/Runner-euyvxdrfpczplnckzankbvrifcpx/Build/Products/Debug-iphoneos
```

unless I copied an old copy there.


I'll attach the other settings you asked for below for diagnostics.
> Wondering if you have a relative DerivedData location set up in Xcode.
> 
> 1. Can we get a screenshot of Xcode > Preferences > Locations

<img width="912" alt="Screen Shot 2020-07-31 at 11 36 58" src="https://user-images.githubusercontent.com/485051/88998279-33d37180-d324-11ea-945e-c9439c9d04f9.png">


> 2. Screenshot of Xcode > Preferences > Locations > Derived Data > Advanced...

See above.

> 3. Open `ios/Runner.xcodeproj` (since that's what you had open when you originally reported).
>    a. Screenshot of File > Project Settings...

<img width="539" alt="Screen Shot 2020-07-31 at 11 53 03" src="https://user-images.githubusercontent.com/485051/88998368-6e3d0e80-d324-11ea-9d14-102caefc4d27.png">


>    b. Screenshot of the Advanced... button

<img width="517" alt="Screen Shot 2020-07-31 at 11 53 36" src="https://user-images.githubusercontent.com/485051/88998391-79903a00-d324-11ea-878b-6a78967e00e0.png">



> 4. Open `ios/Runner.xcworkspace`.
>    a. Screenshot of File > Workspace Settings...

<img width="534" alt="Screen Shot 2020-07-31 at 11 54 06" src="https://user-images.githubusercontent.com/485051/88998420-8b71dd00-d324-11ea-8628-dcc2923ae164.png">



>    b. Screenshot of the Advanced... button

<img width="520" alt="Screen Shot 2020-07-31 at 11 54 27" src="https://user-images.githubusercontent.com/485051/88998440-988ecc00-d324-11ea-92d9-448bde9ce415.png">

**Comment by jmagman** [comment]
Flutter doesn't care where you put your DerivedData when running from Xcode.  I even duplicated your `_build` scenario and it put the frameworks exactly where I expected them to be, and the app build fine because Xcode build setting `FRAMEWORK_SEARCH_PATHS` includes the `BUILT_PRODUCTS_DIR`.
```
$ ls -la test_build_dir/example/ios/_build/Runner/Build/Products/Debug-iphoneos/                     
total 0
drwxr-xr-x   6  primarygroup  192 Jul 31 10:25 .
drwxr-xr-x@  3  primarygroup   96 Jul 30 18:30 ..
drwxr-xr-x   6  primarygroup  192 Jul 31 10:25 Pods_Runner.framework
drwxr-xr-x  29  primarygroup  928 Jul 31 10:25 Runner.app
drwxr-xr-x   4  primarygroup  128 Jul 30 18:30 Runner.swiftmodule
drwxr-xr-x   3  primarygroup   96 Jul 30 18:30 test_build_dir
$la -la /test_build_dir/example/ios/_build/Runner/Build/Products/Debug-iphoneos/test_build_dir
total 0
drwxr-xr-x  3  primarygroup   96 Jul 30 18:30 .
drwxr-xr-x  6  primarygroup  192 Jul 31 10:25 ..
drwxr-xr-x  6  primarygroup  192 Jul 31 10:25 test_build_dir.framework
```

```
    export SYMROOT=/Users/m/Projects/test_build_dir/example/ios/_build/Runner/Build/Products
    export BUILT_PRODUCTS_DIR=/Users/m/Projects/test_build_dir/example/ios/_build/Runner/Build/Products/Debug-iphoneos
    export FRAMEWORK_SEARCH_PATHS="/Users/m/Projects/test_build_dir/example/ios/_build/Runner/Build/Products/Debug-iphoneos  \"/Users/m/Projects/test_build_dir/example/ios/_build/Runner/Build/Products/Debug-iphoneos/test_build_dir\" \"/Users/m/Projects/test_build_dir/example/ios/Pods/../Flutter\" /Users/m/Projects/test_build_dir/example/ios/Flutter"
```
I'm going to close this, it's an issue with how you have Xcode set up, not related to Flutter or CocoaPods tooling.
