### ISSUE TITLE
[proposal] [tool] Allow to set callbacks on a given task

### ISSUE THREAD

**Issue by achinverma** [flutter/flutter#60682]
I have an android project and in the Gradle, after assembleDebug, when the build is successfully created in the output directory, we will be notified with this callback.

```
gradle.buildFinished { 
  Date now = new Date() 
  println "\n ***** All completed @ $now ***"
}
```
Now, In Flutter, Is there any callback exist similar to above

`gradle.buildFinsihed{}`

method, when we run flutter build or flutter run command. Which tells me when the android apk is created with the apk directory path in the command line. I have done a lot of resarch on this but i am not able to find any solutions. Please anyone guide me.

**Comment by jonahwilliams** [comment]
This sort of functionality can be trivial scripted without the need for flutter specific affordances. For example, to run some command foo after a flutter build all you need is `flutter build apk && foo` or something similar on windows. This is not a feature we would currently consider adding to the tooling.

**Comment by achinverma** [comment]
@jonahwilliams , thanks for the reply.
is it possible to detect when the android apk is created in the flutter. I simply want to create a Gradle task that will email that apk to any user?

like in the android, we can use 
gradle.buildFinsihed{}
to detect when the build is created after that we can write any Gradle task, which will mail that apk to any user.
