### ISSUE TITLE
Another exception was thrown: Instance of 'DiagnosticsProperty<void>' 

### ISSUE THREAD

**Issue by akshaybenk** [flutter/flutter#60689]
The flutter release apk shows something went wrong screen for few of the devices below

Samsung a10(android 9)
redmi note 8(android 9)

After debugging the release mode apk, 
Another exception was thrown: Instance of 'DiagnosticsProperty<void>'  message was displayed in logcat
Not able to fix the issue because of very limited info

 flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/apple/flutter
    • Framework revision 8af6b2f038 (17 hours ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Mi A2 • 446eed9 • android-arm64 • Android 10 (API 29)

• No issues found!

packages used:
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  easy_localization: ^1.3.1
  dio: ^3.0.8
  shared_preferences: ^0.5.7+3
  grouped_buttons: ^1.0.4
  date_format: ^1.0.8
  package_info: ^0.4.0+13
  flutter_offline: ^0.3.0
  store_redirect: ^1.0.1
  fluttertoast: ^3.1.3
  shape_of_view: ^1.0.2
  shimmer: ^0.0.6
  custom_progress_dialog: ^1.0.3
  provider: ^4.0.4
  flutter_range_slider: ^1.4.0
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.1
  path_provider: ^1.6.5
  barcode_scan: ^2.0.1
  flutter_slidable: ^0.5.4
  url_launcher: ^5.4.1
  extended_image: ^0.8.0
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by Goolpe** [comment]
https://github.com/flutter/flutter/issues/53482#issuecomment-636750487
