### ISSUE TITLE
Add "centerTitle" option to the "AppBarTheme"

### ISSUE THREAD

**Issue by vargavince91** [flutter/flutter#60686]
## Use case

I'd like to center all app bar titles in my app, even on Android.

I know I could go through my app and add the `centerTitle: true` to every single `AppBar` in the app, but what if I forget to add it?

Alternatively, I could also wrap the app bar in a custom preferred size widget that accepts the same arguments that the original `AppBar` widget and passes down these arguments to the original `AppBar`, does except it makes all title centered. This is also suboptimal, as someone on the team might forget to use the "custom" app bar, resulting in a non-consistent user interface.

## Proposal

I'd like to be able to center all app bar's title via theming instead of having to explicitly set centering.

The `AppBarTheme` could accept a `centerTitle` parameter which would make all app bars centered in the theme's subtree.

**Comment by Goolpe** [comment]
https://github.com/flutter/flutter/pull/57736

**Comment by VladyslavBondarenko** [comment]
Thanks @Goolpe ,
Closing as already implemented, but not in stable yet.
https://master-api.flutter.dev/flutter/material/AppBarTheme/centerTitle.html
