### ISSUE TITLE
Could not download kotlin-compiler-embeddable.jar and Could not download guava.jar (com.google.guava:guava:22.0)

### ISSUE THREAD

**Issue by maninwindow** [flutter/flutter#60691]
# In China

## Error message

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.30)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.30/kotlin-compiler-embeddable-1.2.30.jar'.
         > Read timed out
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.30)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.30/kotlin-reflect-1.2.30.jar'.
         > Read timed out
   > Could not download guava.jar (com.google.guava:guava:22.0)
      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
Exception: Gradle task assembleDebug failed with exit code 1
```

## Flutter doctor message

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Linux, locale en_US.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.46.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @maninwindow 
does it persist and it's not an issue with internet connection?
are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?

Can you download  for example the jar file with [this first link from your log](https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.30/kotlin-compiler-embeddable-1.2.30.jar) if you try it in browser?

**Comment by maninwindow** [comment]
> Hi @maninwindow
> does it persist and it's not an issue with internet connection?
> are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?
> 
> Can you download for example the jar file with [this first link from your log](https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.30/kotlin-compiler-embeddable-1.2.30.jar) if you try it in browser?

Yes, I've set up that link in  `.bashrc`.
Somehow, it worked under other internet connections. 

Thanks

**Comment by VladyslavBondarenko** [comment]
@maninwindow 
it may be also https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall.
Glad to know, closing since solved,
If you disagree please write in the comments and I will reopen it
