### ISSUE TITLE
flutter analyze Future<Future> warning

### ISSUE THREAD

**Issue by dglinyanov** [flutter/flutter#607]
I've got several lines of code that `flutter analyze` treats as error:
```dart
new ImageResource(
                  get(config.testImage).then((Response resp) => decodeImageFromList(resp.bodyBytes)))
```
`flutter analyze` output:
```
[error] Type check failed: get(config.testImage).then((Response resp) => decodeImageFromList(resp.bodyBytes)) (Future<Future<Image>>) is not of type Future<Image> (/home/dmitry/Documents/fittinger-android/lib/main.dart, line 144, col 23)
[warning] The argument type 'Future<Future<Image>>' cannot be assigned to the parameter type 'Future<Image>' (/home/dmitry/Documents/fittinger-android/lib/main.dart, line 144, col 23)
```
If I syntactically change that code to:
```dart
new ImageResource(() async {
    Response resp = await get(config.testImage);
    return await decodeImageFromList(resp.bodyBytes);
}());
```
`flutter analyze` gives no errors or warnings. It is pretty strange behavior, because if I return Future<Image> from then() I should get Future<Image> again (and both variants work the same, as expected). BTW, I work in Atom and it does not show this warning.

**Comment by dglinyanov** [comment]
Another example:

    @override
    Future<ui.Image> loadImage() async {
        Response resp = await get(url);
        return decodeImageFromList(resp.bodyBytes);
    }

Fails with

[error] Type check failed: decodeImageFromList(resp.bodyBytes) (Future<Image>) is not of type Image (/home/dmitry/Documents/fittinger-android/lib/src/utils.dart, line 11, col 12)

An if I add `await` before `decodeImageFromList(resp.bodyBytes)` error disappears. Again, both variants work the same, as expected.

**Comment by abarth** [comment]
The errors are correct.  `decodeImageFromList` returns a `Future<ui.Image>`.  Marking your function `async` wraps whatever you return in a `Future`, so you'll be returning a `Future<Future<ui.Image>>`.  Adding the `await` unwraps the return value of `decodeImageFromList` into just a `ui.Image`.  Returning it from an `async` function re-wraps it into a `Future<ui.Image>`, as you've declared.

The reason you see these errors in `flutter analyze` and not in Atom is that we have more errors turned on in `flutter analyze`.  This error is pretty harmless because Futures keep resolving until they get to a non-Future, but it does introduce more polymorphism into your app, which is why we have the warning turned on.

**Comment by dglinyanov** [comment]
Okay, It still looks strange to me, but let such code style (perfectly
working) be a problem. But I really disagree on current behavior: Flutter
treats this code as an error. So flutter forces me to use `await` after
`return` if I declared return type as `Future<Object>`, declared function
body as `async` and try to return `Future<Object>` without `await`ing it,
even if normally Dart doesn't even warn me. Moreover, I cannot find in Dart
docs any tips on how to return Futures from `async`, not with `await` nor
without (it would be great if you could). Here is same example on dartpad
that also has no warnings: https://dartpad.dartlang.org/7d29db9b5aee508084cf,
so I guess it is not only Atom plugin opinion. So I suggest to change
current behavior to show a warning rather than an error.

2015-11-28 2:11 GMT+06:00 Adam Barth <notifications@github.com>:

**Comment by dglinyanov** [comment]
I guess I should go further with my suggestion - both dart2js and dart
analyzer use 'hints' to show developer that he can improve his code. So
this case looks more like hint than like even warning - something that can
improve code base and in the same time something you could safely ignore.

2015-11-28 18:40 GMT+06:00 Дмитрий Глинянов <gliv321@gmail.com>:

**Comment by abarth** [comment]
If you'd like to pursue this issue further, you should bring it up with the folks who work on the Dart analyzer.  All Flutter is doing is running the analyzer with a specific configuration:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart#L208

You're welcome to use a different analyzer configuration if you prefer.

**Comment by sethladd** [comment]
cc @leafpetersen is this related to strong mode?

**Comment by leafpetersen** [comment]
Yes, this is a known strong mode limitation.  On our radar to fix, but it's kind of an awkward corner case that requires some gymnastics to implement correctly.  It's coming up often enough that we should probably make sure it gets fixed soon.  See also: 

dart-lang/sdk#24540
dart-lang/sdk#25042
dart-lang/dev_compiler#316
dart-lang/dev_compiler#228

**Comment by leafpetersen** [comment]
I believe that this is fixed now, please let me know if there are still issues.

**Comment by abarth** [comment]
Thanks!

**Comment by Hixie** [comment]
Marking fixed per comments. Please don't hesitate to reopen if it's not.
