### ISSUE TITLE
[infra] Do CQ testing of packaging builders on recipe changes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#60706]
Recipes live here: https://flutter.googlesource.com/recipes
Packing builders are configured here: https://github.com/flutter/infra/blob/master/config/packaging_config.star

**Comment by CaseyHillers** [comment]
@christopherfujino

**Comment by christopherfujino** [comment]
The packaging script already has a dry-run flag: https://github.com/flutter/flutter/blob/master/dev/bots/prepare_package.dart#L772 to ensure we don't actually upload

**Comment by godofredoc** [comment]
\cc @sealesj related to the packaging work
