### ISSUE TITLE
A11y focus is lost when using TextField's helperText in combination with specific semantic structure

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#60701]
b/160293585

It looks like the accessibility focus is getting lost when using TextField's helperText in combination with certain semantics structure. The example below is synthetic just to demonstrate the bug. There are real reason why the application needs to use MergeSemantics etc.

Recording (internal) https://drive.google.com/file/d/17yA2-y51K2vf-hCnSEz6DHWOojV_vyBg/view

```dart
    Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Column(
        children: [
          MergeSemantics(
            child: Semantics(
              value: 'test 1',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 1'),
              ),
            ),
          ),
          MergeSemantics(
            child: Semantics(
              value: 'test 2',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 2'),
              ),
            ),
          ),
          MergeSemantics(
            child: Semantics(
              value: 'test 3',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 3'),
              ),
            ),
          ),
        ],
      ), 
    )
```

**Comment by pcsosinski** [comment]
this is a blocker

**Comment by chunhtai** [comment]
I can only reproduce on ios, seems like a platform specific problem

**Comment by chunhtai** [comment]
Investigated a bit, it seems like there is a bug in accessibility bridge in ios embedding, the accessibility tree after the focus traversal between textfield is in a weird shape. It may be because we do not update it correctly. I will dig into it more

**Comment by chunhtai** [comment]
It it interesting that it somehow sends an semantics update to remove the children of root semantics node which cause the semantics focus drop out of the app. still try to figure out why...

**Comment by chunhtai** [comment]
finished investigating, this issue is a side effect of a bigger problem.
In IOS we creates a accessibility tree and maintains the tree based on the sequence update from the framework.
The problem with that is the ios will shake off any semantics nodes that are not attach to the tree. This can happen with the merge semantics widget that it will detach its children from the its semantics node.

The problem is flutter still sends semantics update for those nodes that are not connected to the tree, and accessibility bridge in ios does not know how to handle those. I am still trying to come up with a solution.

**Comment by chunhtai** [comment]
ok so the issue is the semantics nodes underneath the mergesemantics widget keep sending update events which they shouldn't. I will put up a pr to fix it

**Comment by chunhtai** [comment]
internal bug drops to p2
