### ISSUE TITLE
platform_views_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis and 99th_percentile_vsync_transitions_missed regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60702]
99th_percentile_vsync_transitions_missed looks serious enough to warrant immediate investigation.

First sign at https://github.com/flutter/flutter/pull/60564, then a drop, then consistently red after https://github.com/flutter/flutter/pull/60490. Tentatively assigning to the engine team based on the first PR.

![Screen Shot 2020-07-01 at 9 12 00 AM](https://user-images.githubusercontent.com/1435716/86267045-f4760180-bb7a-11ea-8a98-275dee2445c5.png)

**Comment by zanderso** [comment]
#60490 is unrelated.

/cc @blasten @jason-simmons since this is a platform views benchmark, and https://github.com/flutter/engine/pull/19344 was related to platform views.

**Comment by blasten** [comment]
Yep, this is expected. I will remove the P0 level for now and rebase
