### ISSUE TITLE
TabBarView and ListTile no Gap

### ISSUE THREAD

**Issue by gfiury** [flutter/flutter#60728]
Hello guys,

I wrote an example of a TabBarView that has a ListView. The FIRST ListTile seems to have no space/gap from the Tab.

![Image First](https://user-images.githubusercontent.com/20029282/86304521-77cc3d00-bbe5-11ea-92f0-03e581ea9d52.png)

**Am I missing a property for the Tab and/or the ListTile?**

I prefer not adding a Column and some Box between both Widgets.

The example code

```
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  TabController _tabController;
  List<Tab> listTabs;

  int _nmbContacts = 10;

  List<String> _contacts = [];

  @override
  void initState() {
    super.initState();

    listTabs = [Tab(text: "Tab 0")];

    _tabController = TabController(vsync: this, length: listTabs.length);

    for (var i = 0; i < _nmbContacts; i++) {
      _contacts.add("Contact number $i");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          bottom: TabBar(
                  indicatorColor: Colors.white,
                  controller: _tabController,
                  tabs: listTabs,
                ),
        ),
        body: TabBarView(
            physics: NeverScrollableScrollPhysics(),
            controller: _tabController,
            children: [
              buildTab0(),
            ]));
  }

  Widget buildTab0() {
    return ListView.separated(
        itemCount: _contacts.length,
        separatorBuilder: (context, index) => Divider(),
        itemBuilder: buildContact);
  }

  Widget buildContact(context, index) {
    final contact = _contacts[index];

    return ListTile(
        title: Text(contact),
        leading: index % 2 == 0
            ? CircleAvatar(
                radius: 30,
                backgroundColor: Colors.transparent,
                backgroundImage: CachedNetworkImageProvider(
                  "https://www.seti.org/sites/default/files/styles/original/public/2019-09/Zork%20alien%20head%20PPR.jpg?itok=T7eTYzCZ",
                ))
            : CircleAvatar(
                radius: 30,
                foregroundColor: Colors.white,
                backgroundColor: Colors.blue,
                child: Icon(Icons.group),
              ));
  }
}
```

Regards,
William

**Comment by theneshofficial** [comment]
Hi @gfiury , you can wrap the ```ListView``` widget with ```Padding``` widget to get the desired padding.

**Comment by gfiury** [comment]
@theneshofficial thanks, that fixes it. I did not think about it.

I was wondering, this has nothing to do with the fact of using a `ListView` inside a Tab, because removing the Tab and using only the `AppBar` happens the same thing.

**So shouldn't the 'ListView' taking care of that space as a Widget?** **Is this the expected behavior?**

It is like the `Divder` Zero (first of all) or whatever you use as a `separatorBuilder` doesn't exits.

If you not use a separatorBuilder this is the result

![No divider](https://user-images.githubusercontent.com/20029282/86313128-c46e4300-bbfa-11ea-8e31-c162f600d8a9.png)

That is why I'm guessing that using a `separatorBuilder` you don't have first separator.

**Comment by theneshofficial** [comment]
Hi @gfiury , when you use ```ListView.separated``` , the ```separatorBuilder``` widget is added afterEnd of every item except for the last item. Since you are using ```Divider```, it comes with little padding out of the box. That's why you don't see this issue from 2nd item and onwards. ```ListView``` does not control the padding of each item it renders. Instead each item should have their own padding around them to display it constantly. It is expected behaviour for ```ListView```. I suggest you to add ```Padding``` for each item you render not to the ```ListView```.

**Comment by gfiury** [comment]
@theneshofficial got it.

Makes a lot of sense and it would be great if the `ListView` separated example from [here](https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html) mentions any of this or even an example using it with the `Padding`. 

For example the [layout](https://flutter.dev/docs/development/ui/layout) page is super detailed it is awesome all the examples it has.
