### ISSUE TITLE
carousel_slider Error on Multiple Finger Tap : Failed assertion: line 377 pos 12: '_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by precisionsmiles** [flutter/flutter#60737]
ISSUE:
-------
In carousel_slider, tapping simultaneously with more than one finer causes the Gesture Detector to crash and become non-responsive.

ERROR IN DEBUG CONSOLE:
--------------------------------

```
════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 377 pos 12: '_initialButtons == kPrimaryButton': is not true.

When the exception was thrown, this was the stack
#2      DragGestureRecognizer._checkStart 
package:flutter/…/gestures/monodrag.dart:377
#3      DragGestureRecognizer.acceptGesture 
package:flutter/…/gestures/monodrag.dart:308
#4      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
#5      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
#6      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
...

Event: PointerUpEvent#ea064(position: Offset(131.3, 311.7))
    position: Offset(131.3, 311.7)
Target: <WidgetsFlutterBinding>
══════════════════════════════════════════════════════════════════
```

CODE SNIPPET:
-----------------

```
import 'package:flutter/material.dart';
import 'package:carousel_slider/carousel_slider.dart';

Widget carouselSliderDemo() {
    return CarouselSlider.builder(
      itemCount: 5,
      options: CarouselOptions(
        autoPlay: false,
        enableInfiniteScroll: false,
        enlargeCenterPage: false,
        scrollDirection: Axis.horizontal,
        viewportFraction: 1.0,
      ),
      itemBuilder: (context, index) {
        return Container(
            child: Image.network(
              'https://images.pexels.com/photos/672657/pexels-photo-672657.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
              fit: BoxFit.cover,
              width: MediaQuery.of(context).size.width,
            ),
          );
     });
  }
```

Pubspec.yaml Dependency:
------------------------------
`carousel_slider: ^2.2.1`

**Comment by darshankawar** [comment]
Hi @precisionsmiles,
The plugin you mentioned `carousel_slider` seems to be a 3rd party plugin. I'd suggest you open this issue in their repo (https://github.com/serenader2014/flutter_carousel_slider/issues) and follow-up there.
Closing this, since this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thanks.

**Comment by ztigunes** [comment]
i have same issue and i do not use any other third party plugin. i just use tab bar. Are there any bug fix or workaround solution ? When i use tabbar like dummy user with two or three finger (gesture) it freeze all tab bar views.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 416 pos 12: '_initialButtons ==
flutter: kPrimaryButton': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter: https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2 DragGestureRecognizer._checkEnd
package:flutter/…/gestures/monodrag.dart:416
flutter: #3 DragGestureRecognizer.didStopTrackingLastPointer
package:flutter/…/gestures/monodrag.dart:358
flutter: #4 OneSequenceGestureRecognizer.stopTrackingPointer
package:flutter/…/gestures/recognizer.dart:343
flutter: #5 DragGestureRecognizer._giveUpPointer
package:flutter/…/gestures/monodrag.dart:367
flutter: #6 DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart:256
flutter: #7 PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:78

igunes@igunes ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TR)
• Flutter version 1.20.3 at /users/igunes/flutter
• Framework revision 216dee6 (13 days ago), 2020-09-01 12:24:47 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
• Android SDK at /Users/igunes/Library/Android/sdk
• Platform android-30, build-tools 30.0.0
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.7, Build version 11E801a
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.14.1

[✓] Connected device (1 available)
• Mustafa’s iPad (mobile) • ec9cc0171e4772f3dbca05f0c732828429310826 • ios •
iOS 13.5.1
