### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#60743]
Flutter requires the users locale to be reported to the engine. Implement this in the Linux shell.

**Comment by HidenoriMatsubayashi** [comment]
The reason for not closing this issue is if you plan to support dynamic system language changes after launching flutter app?

**Comment by robert-ancell** [comment]
This should be working now. Linux doesn't have a good method of doing dynamic system language changes, but if that could be added please open a new issue, thanks!

**Comment by HidenoriMatsubayashi** [comment]
> Linux doesn't have a good method of doing dynamic system language changes
Yes, I agree.
