### ISSUE TITLE
(This is taking an unexpectedly long time.) - only on ios

### ISSUE THREAD

**Issue by ocb-dev-04** [flutter/flutter#60754]
I am working with an application that uses firebase_auth, cloud_firestore for information management and user authentication.

It was working fine, but at the time I added firebase_storage on android it continued fine and works perfectly, but on ios it only tells me * (This is taking an unexpectedly long time.) * When running the pod install and it doesn't progress

**Comment by VladyslavBondarenko** [comment]
Hi @ocb-dev-04 
could you provide your `flutter doctor -v` and `flutter run --verbose` log (when running on iOS)?

**Comment by ocb-dev-04** [comment]
Of course, check it out here:

This is flutter doctor:
![Screen Shot 2020-07-02 at 2 41 25 PM](https://user-images.githubusercontent.com/42700726/86397727-5ebd9d80-bc72-11ea-8f9b-4085c30a2c23.png)

flutter run --verbose: command log is too long, copy everything here?

**Comment by VladyslavBondarenko** [comment]
@ocb-dev-04 you can copy here or attach as file, or post to github gist or somewhere and provide link to it

**Comment by ocb-dev-04** [comment]
**Well ... this is the log of * flutter run --verbose** 

[crash_ios.txt](https://github.com/flutter/flutter/files/4868761/crash_ios.txt)

**Comment by VladyslavBondarenko** [comment]
@ocb-dev-04 
does it persist after https://medium.com/@phongyewtong/how-to-fix-flutter-stuck-at-running-pod-install-when-run-578ad867774?

**Comment by ocb-dev-04** [comment]
Hey man, thank you very much, that medium article solved the problem. I had almost a week with him and to be honest I was tired of finding out on forums and so on. Thank you very much again man.

<img width="647" alt="Screen Shot 2020-07-03 at 6 29 45 AM" src="https://user-images.githubusercontent.com/42700726/86461175-93276d00-bcf7-11ea-848d-4f6169f7c99b.png">

Everything was executed perfectly.

**Comment by VladyslavBondarenko** [comment]
@ocb-dev-04 
glad to hear, closing as solved

**Comment by victor1409** [comment]
hello friend @ocb-dev-04  I have the same problem but I could not solve it with the forum mentioned by friend @VladyslavBondarenko , could you help me, with the procedure performed by you. 
I have exactly the same problem installing firebase for ios VScode hangs, 
Thanks in advance

**Comment by VladyslavBondarenko** [comment]
Hi @victor1409 consider to file a separate issue with filling out template and mentioning workaround that you tried
