### ISSUE TITLE
I have completely get the package of searchable_dropdown and add in my code, but while searching it dont show the data.

### ISSUE THREAD

**Issue by jigarparmar21** [flutter/flutter#60759]
Widget countryDropDown() {
    return Column(children: <Widget>[
      Container(
                 padding:EdgeInsets.only(left: 8.0, right: 8.0),
        height: 70.0,
        decoration: BoxDecoration(
            border: Border.all(), borderRadius: BorderRadius.circular(2.0)),
        child: DropdownButtonHideUnderline(
          child: new SearchableDropdown.single(
            isExpanded: true,
            hint: Text(Constants.getValueFromKey(
                "Admin.Address.SelectCountry", Constants.hashMap)),
            value: countryDropDownModel.currentValue,
            items: countryDropDownModel.dropDownItems,
            isCaseSensitiveSearch: true,
            onChanged: (value) async {
              visibleCountry = false;
              countryModel = value;
              await callApiForGetStates(countryModel.strValue.toString());
              setState(() {
                countryDropDownModel.currentValue = countryModel;
              });
            },
          ),
        ),
      ),
      Visibility(
          visible: visibleCountry,
          child: new SmallText(
            text: Constants.getValueFromKey(
                "Admin.Address.SelectCountry", Constants.hashMap),
            maxLine: 1,
            align: TextAlign.start,
            color: Colors.red,
          )),
    ]);
  }

**Comment by jigarparmar21** [comment]
![1593684299453](https://user-images.githubusercontent.com/59466922/86345790-a09e1200-bc79-11ea-87f4-cd8972de486c.JPEG)
![1593684299477](https://user-images.githubusercontent.com/59466922/86345794-a1cf3f00-bc79-11ea-9f67-a15c8de048f6.JPEG)

**Comment by jigarparmar21** [comment]
While searching it does not show the suggestion result.

**Comment by VladyslavBondarenko** [comment]
Hi @jigarparmar21 
please open the issue in the plugin's repository https://github.com/icemanbsi/searchable_dropdown/issues,
closing since it's not an issue with flutter itself
