### ISSUE TITLE
Getting random error as VMServiceFlutterDriver Instance of '_WebSocketImpl' is closed with an unexpected code 1005)" while running some BDD feature file in flutter automation

### ISSUE THREAD

**Issue by arjitkathuria** [flutter/flutter#60755]
I am using BDD library and flutter test for automation, while running some feature I get this random message as 

```
VMServiceFlutterDriver Instance of '_WebSocketImpl' is closed with an unexpected code 1005
```

and then It stopped execution of that feature and skipped rest of the scenarios and moved to next feature file.
 
It just skips the scenario without giving any error message.

Out of 10 times I get this issue at least 3 time looking for solution.

**Comment by VladyslavBondarenko** [comment]
Hi @arjitkathuria 
Could you provide your test log? what device are you using?

related to https://github.com/flutter/flutter/issues/57756

**Comment by arjitkathuria** [comment]
> Hi @arjitkathuria
> Could you provide your test log? what device are you using?
> 
> related to #57756
@VladyslavBondarenko 
I am using Simulator iphone 11 pro
iOS 13.3

**Comment by VladyslavBondarenko** [comment]
@arjitkathuria 
please attach full stack trace for the error

**Comment by bhavya-bst** [comment]
were you able to find any solution to this? I am also facing the same issue.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
