### ISSUE TITLE
it seems that the app stay in launch screen when i run widget test in device?

### ISSUE THREAD

**Issue by NanYeYe** [flutter/flutter#60761]
> To help debug widget tests, you can use the debugDumpApp() function to visualize the UI state of your test or simply **flutter run test/widget_test.dart** to see your test run in your preferred runtime environment such as a simulator or a device. During a flutter run session on a widget test, you can also interactively tap parts of the screen for the Flutter tool to print the suggested Finder.
___________________________________________
when i run test with command `flutter test test/widget_test.dart`, the test pass!
but when i use android device, and run test with command `flutter run test/widget_test.dart`, 
it seems that the app stay in launch screen and can not paint other widget, but the test is still pass.
how can i see view the widget tests in device?

**Comment by iapicca** [comment]
HI @NanYeYe 
for this type of test you may wan to look at [integration testing](https://flutter.dev/docs/cookbook/testing/integration/introduction)

Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
