### ISSUE TITLE
Artifacts on drawing cubic paths on canvas on Stable channel

### ISSUE THREAD

**Issue by umberto-sonnino** [flutter/flutter#60767]
After receiving reports on Flare-Flutter about some visible jagged edges displaying with our plugin (2d-inc/Flare-Flutter#253 and 2d-inc/Flare-Flutter#258, but also #57959), I've narrowed it down to a call to `canvas.drawPath()`. In fact, the problem doesn't seem to affect `canvas.drawCircle()`, but is only visible when drawing cubic Beziers with `canvas.drawPath()`.

[Here's](https://i.imgur.com/B7SXIPw.png) a screenshot of the red circle showing jagged edges, running the current Flutter Stable v1.17.5.
[This](https://i.imgur.com/A6BUtPf.png) is another screenshot, that is the expected result with smooth edges, as the same code runs fine in Flutter Dev v.1.20.0-2.0 pre.

It's been reported as showing up only on physical devices, and both screenshots are indeed from an iPad Mini 4 running iOS 13.5.1.

Both of these screenshots have been taken from the following app:

```dart
void main() => runApp(MyPaint());

class MyPaint extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              Expanded(
                child: CustomPaint(
                  foregroundPainter: MyPainter(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyPainter extends CustomPainter {
  Paint _paint = Paint();

  @override
  bool shouldRepaint(CustomPainter oldPainter) => false;

  @override
  void paint(Canvas canvas, Size size) {
    var radius = size.height / 2;
    var center = Offset(size.width / 2, size.height / 2);
    canvas.drawCircle(center, radius, _paint..color = Colors.blue[50]);

    canvas.save();
    canvas.translate(center.dx, center.dy);
    const double padding = 20;
    const arcConstant = 0.55;
    double h = radius - padding;
    double w = h;
    double aw = w * arcConstant;
    double ah = h * arcConstant;
    Path _path = Path()
      ..moveTo(0, h)
      ..cubicTo(aw, h, w, ah, w, 0)
      ..cubicTo(w, -ah, aw, -h, 0, -h)
      ..cubicTo(-aw, -h, -w, -ah, -w, 0)
      ..cubicTo(-w, ah, -aw, h, 0, h)
      ..close();
    canvas.drawPath(_path, _paint..color = Colors.red);
    canvas.restore();
  }
}
```

**Comment by VladyslavBondarenko** [comment]
Hi @umberto-sonnino 
could you check if it persist in beta?

**Comment by umberto-sonnino** [comment]
> Hi @umberto-sonnino
> could you check if it persist in beta?

It seems to be working fine in Beta

**Comment by VladyslavBondarenko** [comment]
@umberto-sonnino 
You can use another flutter channel, wait until the fix comes to stable or find fixing commit and cherry-pick it to your local flutter stable.
Closing, since there is then not need to track the issue.
If you disagree please write in the comments and I will reopen it
