### ISSUE TITLE
Android Studio not detecting connected iPhone 11

### ISSUE THREAD

**Issue by MichaelM97** [flutter/flutter#60772]
## Steps to Reproduce

1. Connect iPhone 11 to MacBook
2. Device is detected by `flutter doctor -v`, but not Android Studio

<img width="648" alt="Screenshot 2020-07-02 at 11 39 58" src="https://user-images.githubusercontent.com/22373058/86349433-0201b900-bc59-11ea-82c2-573622ad9252.png">

## Fix attempts

I have tried the following but none have worked:
* The fix listed in #41006
* `Invalidate Caches / Restart` in Android Studio
* Lock/Unlock device whilst it's connected
* Restarting my iPhone & MacBook
* Resetting my iPhone’s Privacy settings so that the “Trust this computer” dialog can be re-accepted

## Notes

* This device used to work as expected when connecting it to my MacBook for debugging, but has only just now stopped working
* When I connect the device to my MacBook the photos app is still able to access its data
* When connecting an old iPhone 6s, Android Studio is able to detect it and I can use it for debugging my application

## Logs

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.4 at /Users/michaelmccormick/development/flutter
    • Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/michaelmccormick/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

 
[✓] Connected device (1 available)            
    • iPhone • 00008030-000205923C90802E • ios • iOS 13.5.1

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @MichaelM97 
please follow up on https://github.com/flutter/flutter-intellij/issues/4642 and comment there if your case is different.
Check https://github.com/flutter/flutter-intellij/issues/4642#issuecomment-652621376, may be already fixed.
Closing as duplicate
