### ISSUE TITLE
Add generic typing to CheckboxListTile

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#60771]
## Use case
The radio list tile is defined like 

`class RadioListTile<T> extends StatelessWidget`

but checkbox counter part does not have a generic typing

`class CheckboxListTile extends StatelessWidget {`

## Proposal
Add generic typing to the `CheckboxListTile`

**Comment by pedromassangocode** [comment]
Hi @vasilich6107 
Those two widgets behave differently so I think the can't be compared. 

Can you please share your use case? the you shared is just a comparison not a valid expected use case.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
