### ISSUE TITLE
Flutter doctor --> no conneted devices and Android studio--> new flutter project -->flutter sdk path is not given

### ISSUE THREAD

**Issue by Senni765** [flutter/flutter#60778]
## Steps to Reproduce

1. flutter doctor --> cmd

2. Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[!] Connected device

! Doctor found issues in 1 category.

3. My problem is to solve the Point connected device.
I tryed a lot ,but nothing worked.
I hope anyone can help me:)

1.1 My next issue is. When I want to start my first flutter projekt in Android Studio, I get a error message after the steps in brackets .( File--> new--> new flutter Project--> Flutter Application--> next)
2.1 In the window "configure the new flutter aplication" I get the error message  "Flutter SDK path not given."
I tryed a lot but Nothing worked.
Hopfully anyone can help me;)

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @Senni765
You need to start emulator or connect physical  then `flutter doctor -v`, it should show connected devices or you can also execute `flutter devices to see connected devices`

For Android Studio, when you selected new flutter option,  in the second option click three dots to and locate your Flutter SDK on your computer

Hope this helps
Thank you

**Comment by Senni765** [comment]
Hi @TahaTesser ,

everything worked great.
Thank you for your help:)
