### ISSUE TITLE
Material App Title Property Styling

### ISSUE THREAD

**Issue by RYOKSEC** [flutter/flutter#60792]
the thing is Flutter title property in the Material App class can't be styled properly.
for example my app's theme is Colors.cyan but the app's name is showing in black while it should be white.
when i tried to style it i couldn't and it really needs styling especially its color you can try setting your app's main color to cyan and take a look about how the title is displayed in opened-processes tap 

Os : Android

Note : its not a bug or something its just something that have to be mentioned

**Comment by pedromassangocode** [comment]
Hi @RYOKSEC 
I may be wrong but I think you misunderstood the `MaterialApp.title property`, it is never used inside of your app but instead, it is used to represent your app's name outside of Flutter.

For more details, please see the docs:

![Screen Shot 2021-01-21 at 14 34 27](https://user-images.githubusercontent.com/67424416/105357917-c549df00-5bf5-11eb-9429-f701d0cf9c07.png)

Closing as this does not seems to be a valid Flutter issue.
Thank you
