### ISSUE TITLE
image_piker: 0.6.7+3 :  MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

### ISSUE THREAD

**Issue by gabrielluis21** [flutter/flutter#60793]
Hi, I'm using the image_picker plugin and every time I click the button this error message appears "MissingPluginException (No implementation found for method pickImage on channel plugins.flutter.io/image_picker)". I've tried another puglin like image_picker_gallery_camera and the same error message appears. And even when Source is the gallery

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.20.0-3.0.pre.126, on Microsoft Windows [version 10.0.18362.900], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.46.1)
[√] Connected device (4 available)

Is anyone with the same issue? Or know how to fix it?

**Comment by darshankawar** [comment]
Hi @gabrielluis21,  did you run `flutter pub get` after adding `image_picker` dependency and then imported the said file ? If so, please try to stop the execution, run `flutter clean` and then `flutter run`.

**Comment by gabrielluis21** [comment]
Hi @darshankawar I've done  flutter pub get after adding image_picker on dependency in pubspec.yml file and imported in my class. The error continues so I run the flutter clean in my project and then flutter pub get and finally flutter run.

Here the output: 

PS C:\Users\gabri\freelancer\jhoe\clinicadasmultas> flutter clean  
Deleting build...                                                5.637ms (!)
Deleting .dart_tool...                                           1.265ms
Deleting Generated.xcconfig...                                     168ms
Deleting flutter_export_environment.sh...                            1ms
PS C:\Users\gabri\freelancer\jhoe\clinicadasmultas> flutter pub get
Running "flutter pub get" in clinicadasmultas...                    5,4s
PS C:\Users\gabri\freelancer\jhoe\clinicadasmultas> flutter run    
Launching lib\main.dart on Lenovo K33b36 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_media-0.1.2\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleDebug'...                                                                                    
Running Gradle task 'assembleDebug'... Done                      1200,6s (!)
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                15,1s
W/FlutterActivity( 4395): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1531d58) but could not find and invoke the GeneratedPluginRegistrant.
Waiting for Lenovo K33b36 to report its views...                    14ms
Syncing files to device Lenovo K33b36...                                
13.525ms (!)

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Lenovo K33b36 is available at: http://127.0.0.1:7740/-4L1s-qvHOQ=/
I/flutter ( 4395): MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
I/flutter ( 4395): MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

**Comment by Crdzbird** [comment]
Hi @gabrielluis21 i just have the same issue as you, however maybe it's a configuration that you maybe forget.
Check in your Android manifest and see if your structure is the same as mine, also remember to add the permission tag

```

<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="formulario_bloc"
        requestLegacyExternalStorage="true"
        android:icon="@mipmap/ic_launcher">
```

and finally check inside your gradle.properties if the AndroidX and Jetifier are declared, if not replace all the content for this.

```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

and finally as @darshankawar said run the flutter clean and try to run it again.

I hope that this will work to you too :)

**Comment by gabrielluis21** [comment]
Hi @Crdzbird , thanks for the help. But the error persists.

In my AndroidManifest is configured like this:

`<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    

    <application requestLegacyExternalStorage="true"
        android:name="io.flutter.app.FlutterApplication"
        android:label="clinicadasmultas"
        android:icon="@mipmap/ic_launcher">`

In my gradle.properties is configured like this:

`org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true`

And I ran the Flutter Clean and Flutter run commands all day and the error persists.

**Comment by darshankawar** [comment]
Hi @gabrielluis21, please provide `flutter run --verbose`, `pubspec.yaml` and a minimal reproducible code sample. Also share if this is happening on Android or iOS.

**Comment by gabrielluis21** [comment]
Hi @darshankawar 

Here the output on `flutter run --verbose`

`[+15487 ms] Performing Streamed Install`
                    ` Success`
`[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 15,5s)`
`[   +2 ms] executing: C:\Users\gabri\AppData\Local\Android\sdk\platform-tools\adb.exe -s 42e0e45e shell echo -n`
`93d47692cf29090e465d16fdc9e587a10a4b82e6 > /data/local/tmp/sky.com.example.clinicadasmultas.sha1`
`[ +269 ms] Lenovo K33b36 startApp`
`[   +3 ms] executing: C:\Users\gabri\AppData\Local\Android\sdk\platform-tools\adb.exe -s 42e0e45e shell am start -a`
`android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez`      
`enable-checked-mode true --ez verify-entry-points true`
`com.example.clinicadasmultas/com.example.clinicadasmultas.MainActivity`
`[+1629 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.clinicadasmultas/.MainActivity`
`(has extras) }`
`[   +1 ms] Waiting for observatory port to be available...`
`[+1645 ms] W/FlutterActivity( 6342): Tried to automatically register plugins with FlutterEngine`
`(io.flutter.embedding.engine.FlutterEngine@49f23ad) but could not find and invoke the GeneratedPluginRegistrant.`
`[ +310 ms] Observatory URL on device: http://127.0.0.1:38145/lEt6Hy4g8v4=/`
`[   +2 ms] executing: C:\Users\gabri\AppData\Local\Android\sdk\platform-tools\adb.exe -s 42e0e45e forward tcp:0 tcp:38145`
`[ +364 ms] 48250`
`[   +1 ms] Forwarded host port 48250 to device port 38145 for Observatory`
`[   +8 ms] Caching compiled dill`
`[+1127 ms] Connecting to service protocol: http://127.0.0.1:48250/lEt6Hy4g8v4=/`
`[+1214 ms] Successfully connected to service protocol: http://127.0.0.1:48250/lEt6Hy4g8v4=/`
`[   +1 ms] Waiting for Lenovo K33b36 to report its views...`
`[  +25 ms] Waiting for Lenovo K33b36 to report its views... (completed in 15ms)`
`[  +26 ms] DevFS: Creating new filesystem on the device (null)`
`[ +102 ms] DevFS: Created new filesystem on the device`
`(file:///data/user/0/com.example.clinicadasmultas/code_cache/clinicadasmultasOOBKHZ/clinicadasmultas/)`
`[   +4 ms] Updating assets`
`[+3295 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more`
`information see #56466.`
`[   +9 ms] Syncing files to device Lenovo K33b36...`
`[   +2 ms] Scanning asset files`
`[   +5 ms] <- reset`
`[        ] Compiling dart to kernel with 0 updated files`
`[   +1 ms] <- recompile package:clinicadasmultas/main.dart 16ec1750-f91c-4b3c-a2d2-b9ea31531481`
`[        ] <- 16ec1750-f91c-4b3c-a2d2-b9ea31531481`
`[ +287 ms] Updating files`
`[+1240 ms] DevFS: Sync finished`
`[        ] Syncing files to device Lenovo K33b36... (completed in 1.538ms)`
`[  +31 ms] Synced 2.7MB.`
`[   +1 ms] <- accept`
`[   +6 ms] Connected to _flutterView/0xa7fe2410.`
`[   +6 ms] Flutter run key commands.`
`[   +2 ms] r Hot reload. ���🔥🔥🔥`
`[  +98 ms] R Hot restart.`
`[ +386 ms] h Repeat this help message.`
`[   +1 ms] d Detach (terminate "flutter run" but leave application running).`
`[   +1 ms] c Clear the screen`
`[   +2 ms] q Quit (terminate the application on the device).`
`[  +13 ms] An Observatory debugger and profiler on Lenovo K33b36 is available at: http://127.0.0.1:48250/lEt6Hy4g8v4=/`
`[+37625 ms] V/BoostFramework( 6342): mAcquireFunc method = public int`
`com.qualcomm.qti.Performance.perfLockAcquire(int,int[])`
`[  +34 ms] V/BoostFramework( 6342): mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()`
`[   +2 ms] V/BoostFramework( 6342): mAcquireTouchFunc method = public int`
`com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])`
`[   +1 ms] V/BoostFramework( 6342): mIOPStart method = public int`
`com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)`
`[   +1 ms] V/BoostFramework( 6342): mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()`
`[        ] V/BoostFramework( 6342): BoostFramework() : mPerf = com.qualcomm.qti.Performance@66cb248`
`[+2434 ms] I/flutter ( 6342): MissingPluginException(No implementation found for method pickImage on channel`
`plugins.flutter.io/image_picker)`


My pubspec.yml

`name: clinicadasmultas`
`description: A new Flutter project.`

`# The following line prevents the package from being accidentally published to`
`# pub.dev using `pub publish`. This is preferred for private packages.`
`publish_to: 'none' # Remove this line if you wish to publish to pub.dev`

`# The following defines the version and build number for your application.`
`# A version number is three numbers separated by dots, like 1.2.43`
`# followed by an optional build number separated by a +.`
`# Both the version and the builder number may be overridden in flutter`
`# build by specifying --build-name and --build-number, respectively.`
`# In Android, build-name is used as versionName while build-number used as versionCode.`
`# Read more about Android versioning at https://developer.android.com/studio/publish/versioning`
`# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.`
`# Read more about iOS versioning at`
`# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html`
`version: 1.0.0+1`

`environment:`
`  sdk: ">=2.7.0 <3.0.0" `

`dependencies:`
`  flutter:
`    sdk: flutter`


`  # The following adds the Cupertino Icons font to your application.`
`  # Use with the CupertinoIcons class for iOS style icons.`
`  cupertino_icons: ^0.1.3`
`  adhara_socket_io: ^0.4.2+1`
`  google_fonts: ^0.3.9`
` flutter_staggered_grid_view: ^0.2.7`
`  youtube_player_flutter: ^6.1.0+4`
`  dio: ^3.0.9`
`  edge_alert: ^0.0.1`
`  image_picker: ^0.6.7+3`
`  meet_network_image: ^0.1.2`
`  flutter_audio_recorder: ^0.5.5`
`  permission_handler: ^5.0.1+1`
`  flutter_facebook_login: ^3.0.0`
`  file_picker: ^1.12.0`
  

`dev_dependencies:`
`  flutter_test:`
 `   sdk: flutter`

`# For information on the generic Dart part of this file, see the`
`# following page: https://dart.dev/tools/pub/pubspec`

`# The following section is specific to Flutter.`
`flutter:`

`  # The following line ensures that the Material Icons font is`
`  # included with your application, so that you can use the icons in`
`  # the material Icons class.`
`  uses-material-design: true`

`  # To add assets to your application, add an assets section, like this:`
`  # assets:`
`  #   - images/a_dot_burr.jpeg`
`  #   - images/a_dot_ham.jpeg`
`  assets:`
`    - assets/images/`
`  # An image asset can refer to one or more resolution-specific "variants", see`
`  # https://flutter.dev/assets-and-images/#resolution-aware.`

`  # For details regarding adding assets from package dependencies, see`
`  # https://flutter.dev/assets-and-images/#from-packages`

`  # To add custom fonts to your application, add a fonts section here,`
`  # in this "flutter" section. Each entry in this list should have a`
`  # "family" key with the font family name, and a "fonts" key with a`
`  # list giving the asset and other descriptors for the font. For`
`  # example:`
`  # fonts:`
`  #   - family: Schyler`
`  #     fonts:`
`  #       - asset: fonts/Schyler-Regular.ttf`
`  #       - asset: fonts/Schyler-Italic.ttf`
`  #         style: italic`
`  #   - family: Trajan Pro`
`  #     fonts:`
`  #       - asset: fonts/TrajanPro.ttf`
`  #       - asset: fonts/TrajanPro_Bold.ttf`
`  #         weight: 700`
`  #`
`  # For details regarding fonts from package dependencies,`
`  # see https://flutter.dev/custom-fonts/#from-packages`

And a sample of my code:

`Future<void> tirarFoto() async {`
`    File image;`
`    final _picker = ImagePicker();`

`    PickedFile pickedImage = await _picker.getImage(source: ImageSource.camera);`

`    if (pickedImage == null) {`
`      setState(() {`
 `       photoURL = ' ';`
`      });`
`      return;`
`    }`
`    image = File(pickedImage.path);`

`    setState(() {`
`      photoURL = image.path;`
`    });`
 ` }`

**Comment by darshankawar** [comment]
Hi @gabrielluis21,
It seems the code sample you provided is incomplete and missing pieces of code. I tried to replicate this issue with latest version of `image_picker` and didn't see the error you are getting. I am able to open the `camera` and `gallery` and select images from it without any exceptions.

Can you try below code sample and see if you still experience the issue ?

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:image_picker/image_picker.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
//      localizationsDelegates: [
//        GlobalMaterialLocalizations.delegate
//      ],
//      supportedLocales: [
//        const Locale('sv'),
//     //   const Locale('fr')
//      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    const double _appBarHeight = 256.0;
    return Scaffold(
      body: Center(
        child: RaisedButton(
          child: Text('Tap'),
          onPressed: () {
            _showOptions(context);
          },
        )
      )
    );
  }

  Future<void> _showOptions(BuildContext context) {
    return showDialog(context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            content: new SingleChildScrollView(
              child: new ListBody(
                children: <Widget>[
                  GestureDetector(
                    child: new Text('Take a picture'),
                    onTap: openCamera,
                  ),
                  Padding(
                    padding: EdgeInsets.all(8.0),
                  ),
                ],
              ),
            ),
          );
        });
  }

  Future<File> openCamera() async {
    File _image;
    final picker = ImagePicker();

    final pickedFile = await picker.getImage(source: ImageSource.camera);
    print('PickedFile: ${pickedFile.toString()}');

    setState(() {
      _image = File(pickedFile.path);
    });
    if (_image != null) {
      return _image;
    }
    return null;
  }
}
```

</details>

<details>
<summary>log</summary>

```
Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for SM A260G to report its views...
Debug service listening on ws://127.0.0.1:56221/CWuXgt3iHHQ=/ws
Syncing files to device SM A260G...
I/OpenGLRenderer(29732): Initialized EGL, version 1.4
D/OpenGLRenderer(29732): Swap behavior 2
D/mali_winsys(29732): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(29732): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
W/libEGL  (29732): EGLNativeWindowType 0xd3dfe008 disconnect failed
I/OpenGLRenderer(29732): Initialized EGL, version 1.4
D/OpenGLRenderer(29732): Swap behavior 2
D/mali_winsys(29732): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(29732): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
I/flutter (29732): PickedFile: Instance of 'PickedFile'
W/libEGL  (29732): EGLNativeWindowType 0xe9063008 disconnect failed
```

</details>

**Comment by gabrielluis21** [comment]
Hi @darshankawar , I tested the code and worked.

Thank's for the help

**Comment by darshankawar** [comment]
Hi @gabrielluis21, 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by proismailshah** [comment]
I am getting this issue on web can anyone provide me some reference it is working on android but not working on web

**Comment by mohanedsayed** [comment]
i am having this issue and it not working with the emulator nor the device but it used to work before
