### ISSUE TITLE
MaterialPageRoute does not take a "completer"

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#608]
`MaterialPageRoute` extends `ModalRoute` but unlike `ModalRoute` it does not accept a `completer` in its constructor.

It would be great to be able to pass a completer to `MaterialPageRoute`  to know when it pops and get the result of the pop.

@Hixie @abarth

**Comment by abarth** [comment]
Seems related to _Full-screen dialogs_ in the material design spec:

https://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs

**Comment by Hixie** [comment]
Yeah there's no real reason why we couldn't expose this.
