### ISSUE TITLE
Invalid argument(s): Cannot find executable for android\gradlew.bat

### ISSUE THREAD

**Issue by chandupolu** [flutter/flutter#60807]
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for C:\chandu\New folder\MY PROJECTS\Flutter\sample\android\gradlew.bat.".
A crash report has been written to C:\chandu\New folder\MY PROJECTS\Flutter\sample\flutter_02.log.

and

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

**Comment by VladyslavBondarenko** [comment]
Hi @chandupolu 
does it persist after https://github.com/flutter/flutter/issues/51712#issuecomment-600394582?
could you attach the file `C:\chandu\New folder\MY PROJECTS\Flutter\sample\flutter_02.log`?
