### ISSUE TITLE
Flat Button does not adapt disabled properties

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [flutter/flutter#60805]
The flat button does not adapt the disabled properties if I specify `onPressed` as:
```
onPressed: (){
    someCondition ? someFunction : null,  //Assume that "someCondition" is False
    }
```

However, it adapts disabled properties in the following way
```
onPressed :null,
```

**Comment by Zazo032** [comment]
That's because you're specifying a function. The correct syntax for what you're looking for would be like this:

```dart
onPressed: someCondition ? someFunction : null,
```

Notice that, in your case, you're always passing a function to `onPressed` (`() {...}`).

**Comment by VladyslavBondarenko** [comment]
Thanks @Zazo032 ,
@Deepanshu-Rohilla closing since this is not an issue with flutter

**Comment by Deepanshu-Rohilla** [comment]
@VladyslavBondarenko Sure. I hope it would help people in future...
