### ISSUE TITLE
ListView respond to gestures when sliding up to minimize application

### ISSUE THREAD

**Issue by ldhlfzysys** [flutter/flutter#60803]
ListView use platformView as cell,When i sliding up to minimize application,The listview respond to gesture and scroll up.Does not appear when using non-platforview.

**Comment by iapicca** [comment]
Hi @ldhlfzysys 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by ldhlfzysys** [comment]
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F96, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/donghuan1/Desktop/flutter
    • Framework revision b041144f83 (4 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone • 5c473cd3e156236277e63bad79d95063eaa2f07a • ios • iOS 13.5.1

! Doctor found issues in 2 categories.

=====

SmartRefresher(
          enablePullDown: true,
          enablePullUp: true,
          header: refreshHeader(),
          footer: refreshFooter(),
          controller: _userRefreshControl,
          onRefresh: refreshUsers,
          onLoading: fetchUsersMore,
          primary: null,
          child: ListView.builder(
            controller: _controller,
            itemBuilder: (context, item) {
              return PlatformView(cardinfo: _status[item]);
            },
            itemCount: _status.length,
          ),
        )

**Comment by iapicca** [comment]
Hi @ldhlfzysys 
could you please provide a minimal reproducible code sample
(not a snippet from production code)
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
