### ISSUE TITLE
Issues with usb-c monitor

### ISSUE THREAD

**Issue by murataktasli** [flutter/flutter#60818]
I'm running Ubuntu 19.04 paired to two usb-c monitors and everytime I try to run anything related to flutter my screens turn black and won't turn back on again. 

I tried this same situation on my colleague which is using the same setup but running Ubuntu 20 and he is also getting the same results. Both screens turn off after running a simple command `flutter doctor`

**Comment by VladyslavBondarenko** [comment]
Hi @murataktasli 
could you provide your `flutter doctor -v`?

**Comment by murataktasli** [comment]
`Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.4 at /home/murat/Documents/flutter
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/murat/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)`

**Comment by jonahwilliams** [comment]
There is absolutely nothing in this issue we could use to diagnose any sort of issue. @murataktasli  there is a minimum amount of information requested in the issue template. Please re-file a bug including this information, in addition to any diagnostics that would lead you to believe that this is a problem with flutter and not a bug in your USB setup.
