### ISSUE TITLE
Getting error "Target of uri doesn't exists" Github CI

### ISSUE THREAD

**Issue by rymesaint** [flutter/flutter#60813]
## Steps to Reproduce

I'm trying to create CI at Gitlab with Docker and tried it using different environment(Linux) where my local environment is MacOS.
At first i thought that the problem was on docker because not getting path from .packages file or maybe because its not working on Gitlab.

Then i tried different CI at Github using Github Actions, here my config :
```
name: Flutter Analyze Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java Environment
        uses: actions/setup-java@v1
        with:
            java-version: '12.x'
    - name: Install flutter sdk
        uses: subosito/flutter-action@v1
        with:
            flutter-version: '1.17.5'
    - name: Install dependencies
      run: flutter pub get
    - name: Run analyze
      run: flutter analyze
```

And the error still happened when using linux system like this

```
error • Undefined class 'Gender' • lib/src/notifier/PersonalDataProvider.dart:219:3 • undefined_class
2928
  error • Undefined class 'Religion' • lib/src/notifier/PersonalDataProvider.dart:225:3 • undefined_class
2929
  error • Undefined class 'Nationality' • lib/src/notifier/PersonalDataProvider.dart:227:3 • undefined_class
2930
  error • Undefined class 'SpecialNeed' • lib/src/notifier/PersonalDataProvider.dart:228:3 • undefined_class
2931
  error • Undefined class 'Province' • lib/src/notifier/PersonalDataProvider.dart:229:3 • undefined_class
2932
  error • Undefined class 'City' • lib/src/notifier/PersonalDataProvider.dart:230:3 • undefined_class
2933
  error • Undefined class 'SubDistrict' • lib/src/notifier/PersonalDataProvider.dart:231:3 • undefined_class
2934
  error • Undefined class 'Village' • lib/src/notifier/PersonalDataProvider.dart:232:3 • undefined_class

error • Target of URI doesn't exist: 'package:***_mobile/src/Utils/ServerStatus.dart' • lib/src/utils/Network.dart:6:8 • uri_does_not_exist
3035
  error • The method 'ServerStatus' isn't defined for the type 'Network' • lib/src/utils/Network.dart:25:25 • undefined_method
3036
  error • The method 'ServerStatus' isn't defined for the type 'Network' • lib/src/utils/Network.dart:55:25 • undefined_method
3037

##[error]Process completed with exit code 1.
```

and when i tried with the same environment like my local which is MacOS, its fine no error. So i think maybe its because the flutter or because different environment.

**Comment by VladyslavBondarenko** [comment]
Hi @rymesaint 
Closing, as this doesn't look like an issue with Flutter itself. You can raise the issue in Gitlab CI or Github Actions repository.
If you disagree please write in comments and I'll reopen

**Comment by rymesaint** [comment]
@VladyslavBondarenko i've found the problem within my project, that i use the folder name with Uppercase and importing with that is not accepted by analyzer, so in linux the flutter doesn't accept the uppercase style but in macOS it accepting with no problem. Just want you to know that is it related to bug in flutter or not.

**Comment by fahjan** [comment]
@rymesaint 
flutter prefere to use lowercase filenames. 
see this 
https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores
