### ISSUE TITLE
package_info

### ISSUE THREAD

**Issue by klvnco** [flutter/flutter#60810]
PackageInfo packageInfo = await PackageInfo.fromPlatform();
String appName = packageInfo.appName;

this is returning Null on IOS

**Comment by VladyslavBondarenko** [comment]
Hi @klvnco 
set the value in your `ios/Runner/Info.plist` this way https://github.com/flutter/flutter/issues/42510#issuecomment-594275815,
follow up on the issue, I'm closing current one as duplicate
