### ISSUE TITLE
Why .xcworkspace generated for iOS?

### ISSUE THREAD

**Issue by i-schuetz** [flutter/flutter#60812]
Why exactly is the iOS project generated with an .xcworkspace? Working with native iOS, I've only needed it when working with CocoaPods (which seems to not be used here). From a quick look into the generated files, it was also not obvious.

Note: The question is specifically about generating `Runner.xcworkspace` additionally to the project (`Runner.xcodeproj`). regular non-CocoaPods iOS projects need usually only `Runner.xcodeproj`.

**Comment by stuartmorgan** [comment]
> I've only needed it when working with CocoaPods (which seems to not be used here).

Flutter does use CocoaPods; it's how plugins are managed.

**Comment by i-schuetz** [comment]
Okay, are there plans to migrate to SPM with Swift 5.3 (which support binaries)?
