### ISSUE TITLE
New Flutter Projekt Android Studio

### ISSUE THREAD

**Issue by Senni765** [flutter/flutter#60819]
## Steps to Reproduce

1. I open Android Studio.
2. I start a new flutter project
3. I finished it and get a error message of " Error creating Project:
                                                                     Could not find an Option named "androidx".
                                                                     Run `flutter -h´ (or flutter -h´) for available flutter commands and Options.
4. I tryed a lot, but I do not know what I did wrong.
    Hopefully anyone can help me;)

## Logs

```
```

```
```

**Comment by nitesh-kumar-sharma** [comment]
Have you tried to upgrade flutter to latest 
`flutter upgrade`

Also please share your logs.

**Comment by felixwortmann** [comment]
Do you have the current version of Android Studio installed?

**Comment by Senni765** [comment]
> Have you tried to upgrade flutter to latest
> flutter upgrade
> Also please share your logs.

Flutter is already up to date on channel stable
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (4 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by Senni765** [comment]
> Do you have the current version of Android Studio installed?
Yes , I have it.

**Comment by Senni765** [comment]
@nitesh-kumar-sharma @felixwortmann thanks for your help;)
I solved my Problem by my self.
