### ISSUE TITLE
Sign release files

### ISSUE THREAD

**Issue by countcretinos** [flutter/flutter#60827]
Please sign your releases files so they can be checked for integrity.

**Comment by TahaTesser** [comment]
Hi @countcretinos 
I am not sure what do you mean? Can you please give us more details to what you referring to? 
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
