### ISSUE TITLE
Textfield/CupertinoTextfield cursor position after changing TextEditingController's value is inconsistent on Android

### ISSUE THREAD

**Issue by vinnytwice** [flutter/flutter#60828]
I have a textfield connected to its `TextEditingController()`. Inside the `onChanged:` callback I perform a text manipulation to only allow for time input.
When running on iOS `CupertinoTextfield` is used and it behaves as expected, at every input cursor moves to the end so next digit is at the right position, so inputting 1000 will result in 10:00.
When running on web or Android `Material Textfield` is used instead, the problem is that text is displayed backward as the cursor stays at first position so inputting 1000 will result in 00:01 ..
I tried enabling `autofocus: true` , but doesn't help. I tried with `textDirection: TextDirection.ltr,` but didn't fixit either. I also tried a solution from another post here grabbing the controller selection and reapplying it on the checked text but it didn't help either.
As with CupertinoTextfield it all works es expected, could this be a bug in the material Textfield ?

This is the widget:

```
Expanded(
                        flex: 2,
                        child: kIsWeb
                            ? TextField(
                                keyboardType: TextInputType.numberWithOptions(),
                                textDirection: TextDirection.ltr,
                                autofocus: true,
                                controller: monMorOp,
                                onChanged: (value) {
                                  monMorOp.text = validateTimeFormat(value);
                                },
                              )
                            : Platform.isIOS
                                ? CupertinoTextField(
                                    keyboardType:
                                        TextInputType.numberWithOptions(),
                                    controller: monMorOp,
                                    onChanged: (value) {
                                      monMorOp.text = validateTimeFormat(value);
                                    },
                                  )
                                : TextField(
                                    keyboardType:
                                        TextInputType.numberWithOptions(),
                                    controller: monMorOp,
                                    onChanged: (value) {
                                      monMorOp.text = validateTimeFormat(value);
                                    },
                                  ),
                      ),
```

an this is the text checking method :

```
String validateTimeFormat(String value) {
    print('call back method called');
//    String numb = event.text;
    print('input text is $value');
    String cleanNumb = value.replaceAll(RegExp(':'), '').substring(0);
    print('cleaned input text is $cleanNumb');
    RegExp isDigit = RegExp(r'^[\d]{1,4}$'); // is digit 1 to 4 characters
//    RegExp isDigit = RegExp(r'^[\d]$'); // is digit
    RegExp input;
    String text;
    int lenght;
    String replaced;

    if (isDigit.hasMatch(cleanNumb)) {
      print('text is 1-4 digits');
      text = cleanNumb;
      lenght = text.length;
//      print('lenght is $lenght');

      if (lenght == 1) {
        // first digit
        //allow 0-2
        input = RegExp(r'^[0-2]$');
        input.hasMatch(text[0])
            ? print('text is : $text')
            : print('text is: not valid');
        return input.hasMatch(text[lenght - 1]) ? text : '';
      } else if (lenght == 2) {
        // second digit
        int first = int.parse(text[0]);
        print('firstDigit is $first');
        if (first == 008 || first == 1) {
          // allow 0-9
          input = RegExp(r'^[0-9]$');
          input.hasMatch(text[lenght - 1])
              ? print('text is : $text')
              : print('text is : ${text.substring(0, lenght - 1)}');
          return input.hasMatch(text[lenght - 1])
              ? text
              : text.substring(0, lenght - 1);
        } else {
          // allow 0-3
          input = RegExp(r'^[0-3]$');
          input.hasMatch(text[lenght - 1])
              ? print('text is : $text')
              : print('text is : ${text.substring(0, lenght - 1)}');
          return input.hasMatch(text[lenght - 1])
              ? text
              : text.substring(0, lenght - 1);
        }
      }
      if (lenght == 3) {
        //third digit
        // add : at lenght-1
        // allow 0-5
        input = RegExp(r'^[0-5]$');
        input.hasMatch(text[lenght - 1])
            ? replaced = text.replaceRange(2, lenght, ':${text.substring(2)}')
            : replaced = text.substring(0, lenght - 1);
        print('text is : $replaced');
        return replaced;
      }
      if (lenght == 4) {
        // fourth digit
        // allow 0-9
        input = RegExp(r'^[0-9]$');
        input.hasMatch(text[lenght - 1])
            ? replaced = text.replaceRange(2, lenght, ':${text.substring(2)}')
            : replaced = text.substring(0, lenght - 1);
        print('text is : $replaced');
        return replaced;
      }
    } else {
      // discard extra digit
      print('more than 4 digits');
      lenght = cleanNumb.length;
      replaced =
          cleanNumb.replaceRange(2, lenght, ':${cleanNumb.substring(2, 4)}');
      print('text is : $replaced');
      return replaced;
    }
  }
```

**Comment by felixwortmann** [comment]
Can you please provide the output of `flutter doctor`

**Comment by vinnytwice** [comment]
@felixwortmann Hi Felix her it is:

[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.13.6 17G65, locale it-IT)
    • Flutter version 1.12.13+hotfix.7 at /Users/vinnytwice/Developer/flutter
    • Framework revision 9f5ff2306b (5 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vinnytwice/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • iPhone Xʀ  • 9D478E89-80C3-4E1E-983D-97FBB2412429 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.116
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by felixwortmann** [comment]
First of all, your flutter channel being `unknown` does not look good. You also have an old flutter version. Maybe something is wrong with your install? You could try `flutter upgrade` to get to the current version or just reinstall flutter completely.

**Comment by vinnytwice** [comment]
The unknown is due to the downgrade I did as I'm on High Sierra and maximum Xcode version I can install on it is 10.2. I have another partition with Catalina which can't connect to the internet ( got some problem ) that's why I haven't tried yet. It might be already solved by some update as it's the case for localization.

If you have a chance to to test it for me it'd be awesome. To make it easier on you I can make a little repo .
Many thanks

**Comment by vinnytwice** [comment]
@felixwortmann 
Hi Felix the unknown is due to the downgrade I did as I'm on High Sierra and maximum Xcode version I can install on it is 10.2. I have another partition with Catalina which can't connect to the internet ( got some problem ) that's why I haven't tried yet. It might be already solved by some update as it's the case for localization.

If you have a chance to to test it for me it'd be awesome. To make it easier on you I can make a little repo .
Many thanks

**Comment by felixwortmann** [comment]
@vinnytwice 
I am not quite sure but maybe you can test it on [Codepen](https://codepen.io/)

**Comment by vinnytwice** [comment]
@felixwortmann I tested it on Codeine and the issue is still there. Here is the sample app I put together https://github.com/vinnytwice/material_textfield_issue_test.
First textfield shows the issue, second textfield time formatted value is displayed underneath .
Thank you very much for the help.

**Comment by felixwortmann** [comment]
@vinnytwice 
So I tested it and it does not work for me either. I found [this](https://stackoverflow.com/questions/56851701/how-to-set-cursor-position-at-the-end-of-the-value-in-flutter-in-textfield) Question on StackOverflow though. Maybe you can try around with that. It seems like there should be a solution.

**Comment by vinnytwice** [comment]
@felixwortmann well, it could be a workaround, but I do believe the both Textfield and CupertinoTextfield `onChanged:` callback should operate the same in order to deliver developers a true all in one solution as Flutter aims to be. If Thera are a ton of platform specific differences it kinda looses the point in using Flutter. So just for  to understand, this behavior is a bug in Material Textfield or it's indeed intended to behave like this and mine is just a feature request ?
Many thanks.

**Comment by felixwortmann** [comment]
@vinnytwice I do not know if it is a bug or just the expected behavior. Someone from the flutter team should definitely look into this.

**Comment by vinnytwice** [comment]
>Someone from the flutter team should definitely look into this.

@felixwortmann  Indeed someone should.

I tried various solutions from the suggested solutions at the link you provided ( many thanks!! ) and the only easy and effective way is 
`controller.selection = TextSelection.fromPosition(TextPosition(offset: controller.text.length));` which on CupertinoTextfield happens already.. 
I'm not closing this issue as I expect for the Flutter team to take a look at it, meanwhile the workaround works and I thing that even when Material Textfield works as they (IMO) work it won't brake the code ..
Many thanks again for the very precious help.
 
Workaround in use:
```
TextField(
                      keyboardType: TextInputType.numberWithOptions(),
                      textDirection: TextDirection.ltr,
                      controller: c2,
                      style: TextStyle(
                          color: Colors.black,
                          fontSize: 15,
                          fontWeight: FontWeight.w500),
                      onChanged: (value) {
                        setState(() {
                          
                          c2.text = validateTimeFormat(value);
                          c2.selection = TextSelection.fromPosition(
                              TextPosition(offset: c2.text.length));

                        });
                      },
                    )
```

**Comment by VladyslavBondarenko** [comment]
I see the difference is not between TextField and CupertinoTextField, but between Android/web and iOS.
If you try with Android/web - in both TextField and CupertinoTextField cursor will move to the beginning after changing controller's value. In iOS for both of them cursor will stay in the end after changing controller's value

I tried with current stable `1.17.5` and current master `1.20.0-3.0.pre.130`. 

<details>
 <summary>Code</summary>

```
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController c1 = TextEditingController();
  TextEditingController c2 = TextEditingController();
  String textfield2 = 'value';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            TextField(
              keyboardType: TextInputType.numberWithOptions(),
              controller: c1,
              onChanged: (value) {
                c1.text = validateTimeFormat(value);
              },
            ),
            CupertinoTextField(
              keyboardType: TextInputType.numberWithOptions(),
              controller: c2,
              onChanged: (value) {
                c2.text = validateTimeFormat(value);
              },
            ),
          ],
        ),
      ),
    );
  }

  String validateTimeFormat(String value) {
//    print('call back method called');
//    print('input text is $value');
    String cleanNumb = value.replaceAll(RegExp(':'), '').substring(0);
//    print('cleaned input text is $cleanNumb');
    RegExp isDigit = RegExp(r'^[\d]{1,4}$'); // is digit 1 to 4 characters
    RegExp input;
    String text;
    int lenght;
    String replaced;

    if (isDigit.hasMatch(cleanNumb)) {
//      print('text is 1-4 digits');
      text = cleanNumb;
      lenght = text.length;
//      print('lenght is $lenght');

      if (lenght == 1) {
        // first digit
        //allow 0-2
        input = RegExp(r'^[0-2]$');
//        input.hasMatch(text[0])
//            ? print('text is : $text')
//            : print('text is: not valid');
        return input.hasMatch(text[lenght - 1]) ? text : '';
      } else if (lenght == 2) {
        // second digit
        int first = int.parse(text[0]);
//        print('firstDigit is $first');
        if (first == 008 || first == 1) {
          // allow 0-9
          input = RegExp(r'^[0-9]$');
//          input.hasMatch(text[lenght - 1])
//              ? print('text is : $text')
//              : print('text is : ${text.substring(0, lenght - 1)}');
          return input.hasMatch(text[lenght - 1])
              ? text
              : text.substring(0, lenght - 1);
        } else {
          // allow 0-3
          input = RegExp(r'^[0-3]$');
//          input.hasMatch(text[lenght - 1])
//              ? print('text is : $text')
//              : print('text is : ${text.substring(0, lenght - 1)}');
          return input.hasMatch(text[lenght - 1])
              ? text
              : text.substring(0, lenght - 1);
        }
      }
      if (lenght == 3) {
        //third digit
        // add : at lenght-1
        // allow 0-5
        input = RegExp(r'^[0-5]$');
        input.hasMatch(text[lenght - 1])
            ? replaced = text.replaceRange(2, lenght, ':${text.substring(2)}')
            : replaced = text.substring(0, lenght - 1);
//        print('text is : $replaced');
        return replaced;
      }
      if (lenght == 4) {
        // fourth digit
        // allow 0-9
        input = RegExp(r'^[0-9]$');
        input.hasMatch(text[lenght - 1])
            ? replaced = text.replaceRange(2, lenght, ':${text.substring(2)}')
            : replaced = text.substring(0, lenght - 1);
//        print('text is : $replaced');
        return replaced;
      }
    } else {
      // discard extra digit
//      print('more than 4 digits');
      lenght = cleanNumb.length;
      replaced =
          cleanNumb.replaceRange(2, lenght, ':${cleanNumb.substring(2, 4)}');
//      print('text is : $replaced');
      return replaced;
    }
  }
}
```

</details>

**Comment by vinnytwice** [comment]
Hi @VladyslavBondarenko, thanks for pointing that out, I didn't realize it as my app switches widgets to show the the proper platform one, and I didn't try the sample app I linked above on the iPad so I hadn't noticed it. Also thanks for putting the modified code here in the question so it now has reproducible steps. I actually pushed a commit to include the workaround on the second material Textfield. 
So is it something related just to the web/Android framework and has to be fixed or it is just the way it is and we gotta live with it?

**Comment by vinnytwice** [comment]
Hi @VladyslavBondarenko after upgrading to Catalina, Android Studio 4.0 and latest beta channel, the workaround doesn't work anymore.. text gets scrambled in digit pairs.. I haven't tested yet the stable channel.. Is there any know problem with the beta channel? 

[✓] Flutter (Channel beta, 1.20.0-7.4.pre, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.20.0-7.4.pre at /Users/vinnytwice/Developer/flutter
    • Framework revision 916c3ac648 (6 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/vinnytwice/Library/Android/sdk
    • Platform android-29, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Volumes/ProjectsSSD/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!

**Comment by vinnytwice** [comment]
@VladyslavBondarenko ok.. checked on iPad and now workaround code is also needed on iOS after upgrading to Catalina/Android Studio 4.0, Xcode 11.5.. well.. at least now all platforms are aligned .. lol

**Comment by maheshmnj** [comment]
Hi @vinnytwice, I can confirm the output on android is inconsistent with the rest of the platforms as of latest master 3.6 and stable 3.3

https://user-images.githubusercontent.com/31410839/203381939-5f4335f2-b560-4e86-b7df-0cb7ba765913.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.8 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

cc: @justinmc

**Comment by justinmc** [comment]
As mentioned above in https://github.com/flutter/flutter/issues/60828#issuecomment-653879961, this can be solved by setting the selection on the TextEditingController in addition to the text.  This is probably the right solution here rather than making a change to Flutter.  The selection may be adjusted by the platform after the `.text` setter is used, and it might not be the same on each platform.
