### ISSUE TITLE
Flutter add to app Android - Issues

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#60822]
1) After call FlutterActivity and shows the flutter screen, How to call finish() on current Activity? It is not documented.
2) How do I use some subclasse of FlutterActivity?  It is also not documented.

I did something like this, is it ok? I could't find a way to do that using the FlutterActivity and the builder methods.

activity.startActivity(
            new Intent(activity, AppFlutterActivity.class)
                    .putExtra("cached_engine_id", ENGINE_ID)
                    .putExtra("destroy_engine_with_activity", false)
                    .putExtra("background_mode", FlutterActivityLaunchConfigs.BackgroundMode.opaque.name())
        );

3) Even after cache the flutter engine, I still see some blank screen after call flutter.

**Comment by TahaTesser** [comment]
Hi @rlecheta . 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample from native and flutter module
Thank you

**Comment by rlecheta** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-BR)
    • Flutter version 1.17.5 at /Users/rlecheta/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rlecheta/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/rlecheta/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @rlecheta 
Can you please provide complete reproducible minimal code sample from native and flutter module for your issue with " I still see some blank screen after call flutter." 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
