### ISSUE TITLE
Device orientation doesn't dispose in Splash Screen

### ISSUE THREAD

**Issue by AbirAhsan** [flutter/flutter#60839]
***I used custom device orientation on my splash screen (it's worked) and try to back it normal by use dispose(). But it doesn't work.***
***

> Here is my Code-

***

    import 'dart:async';
    import 'package:flutter/material.dart';
    import 'package:flutter/services.dart';
    import 'package:boimarket/widgets/exitpopup.dart';
    import 'package:boimarket/homepage.dart';
    
    class SplashScreen extends StatefulWidget {
      @override
      _SplashScreenState createState() => _SplashScreenState();
    }
    
    class _SplashScreenState extends State<SplashScreen> {
      @override
      void initState() {
        super.initState();
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.portraitDown,
          DeviceOrientation.portraitUp,
        ]);
    
        Timer(
            Duration(seconds: 3),
            () => Navigator.push(context,
                MaterialPageRoute(builder: (context) => ExitPopUp(Homepage()))));
      }
    
      @override
      dispose() {
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.portraitDown,
          DeviceOrientation.portraitUp,
          DeviceOrientation.landscapeRight,
          DeviceOrientation.landscapeLeft,
        ]);
        super.dispose();
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: SingleChildScrollView(
            child: Container(
              child: Text('Hello')
        );
      }
    }

> Flutter doctor
```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\abira>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\abira>
```

***Where is the problem? and How can I fix this?***

**Comment by chingyawhao** [comment]
Hi @AbirAhsan 
`Navigator.push` doesn't dispose the current route
I guess you wont expect your user to navigate from home screen back to your splash screen, maybe you can consider using this instead
```
Timer(
    Duration(seconds: 3),
    () => Navigator.pushAndRemoveUntil(context,
        MaterialPageRoute(builder: (context) => ExitPopUp(Homepage())),
        (route) => false
    )
);
```
This will dispose your splash screen route from the navigator stack

**Comment by VladyslavBondarenko** [comment]
Hi @AbirAhsan 
dispose is called when widget is removed from the tree permanently. This happens on pushReplacement or pushAndRemoveUntil for example, but not on push. In your case you would need to use deactivate function, but it will not be called on push as well - please follow up on the issue https://github.com/flutter/flutter/issues/50147.
I'm closing current one as duplicate,
if you disagree please write in the comments and I will reopen it
