### ISSUE TITLE
Horizontal scrolling with touchpad in Flutter Windows.

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#60835]
Hi Flutter team, 
I came across this problem, we can do vertical scrolling with touchpad gestures in flutter for windows app. But not the horizontal one. How can we achieve this?

**Comment by TahaTesser** [comment]
Hi @SahajRana 
You probably ned  list with horizontal direction if i am not missing from your description 
Can you please provide your `flutter doctor -v`  and a complete reproducible minimal code sample
Thank you

**Comment by SahajRana** [comment]
Hi @TahaTesser,
I meant horizontal scrolling with two-fingers gestures on the touchpad with a horizontal-list for Windows App. 
![976305-200](https://user-images.githubusercontent.com/16938202/86583965-cd1b9c00-bfa1-11ea-8b1b-e397bb22cd79.png)
