### ISSUE TITLE
Flutter SDK is not found specified location

### ISSUE THREAD

**Issue by aseel142** [flutter/flutter#60838]
![Desktop Screenshot 2020 07 04 - 21 29 19 75](https://user-images.githubusercontent.com/67839577/86518974-a98c1080-be3e-11ea-91ee-42691aedf5a5.png)

![Desktop Screenshot 2020 07 04 - 21 30 11 11](https://user-images.githubusercontent.com/67839577/86518984-c32d5800-be3e-11ea-9e01-a696b190e7e1.png)

I don't know what to do I have been trying for 3days  

I think I have done everything right

**Comment by MalakaDeSilva** [comment]
When you create a flutter project you shouldn't provide the flutter sdk path all the way upto "bin" folder. Use the path only to "flutter" folder. In your case I think the path would be "C:\src\flutter\flutter". 
Considering the flutter doctor output, I think you need to install android sdk too.
