### ISSUE TITLE
Can't build/archive iOS app - numerous unpredictable errors

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#60843]
I'm attempting to build and archive the iOS version of my app (I've already published the Android side to the Play Store). I can't seem to build/archive any of my flavors and I'm at a loss for how to debug this. Details are outlined below.

I have 3 flavors:
 - Dev
 - Staging
 - Production

These 3 flavors are reflected with schemes on the iOS side.

I'm **able** to build and run **all** flavors on my personal iPhone by using Android Studio and the standard play button.

I'm **sometimes able** to build and run from XCode directly. I spent hours last night unable to get a single build to run from XCode for any flavor. Today, after building and running every flavor from Android Studio, it seems that XCode can now build and run directly. But who knows how long until something breaks again. I get the impression that the Android Studio builds generated files that, once cleaned out, will return XCode to failure.

## Running from XCode
When I attempt to use the play button in XCode to build and run a flavor and it fails, I get a "Build Failed" error with the following details:

```
/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
I've seen this error mentioned in other issues. However, I didn't notice any actionable recommendations in those other tickets.

or, sometimes I get a complaint that the very first entry in my generated plugin registrant can't be found. For me, that happens to be cloud_functions, but I think it's an underlying search path and/or linking issue that is independent of that particular plugin.

I have not been able to figure out what difference in inputs causes the `PhaseScriptExecution failed` vs the failed linking in the generated plugin registrant.

## Building with Flutter CLI
I have attempted to use `flutter build`, too.

```
flutter build ios --flavor=Staging --release
```

Last night, the `flutter build ios` command failed for every flavor over dozens of attempts. Today, after building and running every flavor from Android Studio (using the play button), it appears that I am able to successfully execute the `flutter build ios` command. I have no idea what the act of running from Android Studio did to make the outcome change.

When the `flutter build ios` command was failing last night, no actionable output from provided. I tracked down the code that reported the error. I think it was in `build_ios.dart`. I added some tracing prints and found that the "diagnose" function was not outputting anything before the error was thrown. So I have no idea what actually failed. But, again, this failure occurred on all 3 flavors for many hours last night as I attempted to debug things.

## From `flutter build` to XCode `archive`

The immediate problem that I'm facing now is that after finally getting `flutter build ios` to execute without error, I go over to XCode and attempt to `Product > Archive` my `Staging` build for release. Immediately, XCode reports "Build Failed", even though I already ran a build with `flutter build ios`, and the error is once again:

```
/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

Here's a screenshot of my "Based on Configuration" settings:

![Screen Shot 2020-07-04 at 4 24 01 PM](https://user-images.githubusercontent.com/7259036/86522459-e9d59980-be12-11ea-8f18-a367f5efd667.png)

## Conclusion

I'd appreciate any help in getting this iOS app over the finish line in terms of building and archiving.

Beyond this immediate issue, I'd like to repeat what I've mentioned before, which is that the interaction between Flutter and iOS/XCode seems to very much be a black box of magic as compared to the more highly visible Gradle interactions for Android. I'm finding it nearly impossible to debug these connections. The fact that I get different results when running from Android Studio vs XCode is confusing and frustrating. The fact that running `flutter build ios` produces different results when, as far as I know, I haven't changed any configurations, is confusing and frustrating.

I'm sure that a big source of my issues are coming from flavors. But I think flavors are table stakes for production apps. Either all the other Flutter app shops out there know a lot about how to configure flavors and aren't saying anything, or there are probably a bunch of shops suffering with these issues. I would encourage the Flutter org to consider these configurations to be critical and relevant for everyday app development and to thoroughly guide developers through these configurations (CC @timsneath @csells @sfshaza2 ). I have offered before, and I'll offer again to donate some of my time to help publish such documentation, but I require those with the technical expertise to first help me understand the intricacies of how iOS apps, XCode, schemes, and flavors should be setup.

## Flutter Version

Flutter 1.20.0-0.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision d9653445f4 (4 weeks ago) • 2020-06-09 18:43:03 -0400
Engine • revision e8c13aa012
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

**Comment by matthew-carroll** [comment]
CC @xster @jmagman

**Comment by jmagman** [comment]
Your screenshot shows your base configurations are correct for your `Debug-` configurations but not Release or Profile.  They need to inherit the xcconfig (base configuration) that `#include`s the Flutter generated variables, like `FLUTTER_ROOT`, not from the Pod- one.
See https://github.com/flutter/flutter/issues/12749 and screenshot under #3 in https://github.com/flutter/flutter/issues/56507#issuecomment-631773721 TL;DR.

**Comment by matthew-carroll** [comment]
Thanks @jmagman - I don't appear to have `Profile-xxxx` or `Release-xxxx` variations in the dropdowns. Other than the `Debug-xxxx` variations you see in the screenshot, the only non-Pod variations that I have available are `Debug`, `Release`, and `Generated`. Any idea which step(s) I may have missed that would have generated those additional variations?

**Comment by matthew-carroll** [comment]
I created a `Release-Staging.xcconfig` with the following content:

```
#include "Pods/Target Support Files/Pods-Staging/Pods-Staging.release-staging.xcconfig"
#include "Generated.xcconfig"
```

I reconfigured the base configuration setting to use `Release-Staging`. This resolved the `xcode_backend.sh` issue related to the `FLUTTER_ROOT` configuration.

However, I now receive the other error that I mentioned in my original post, which is:

```
Parse issue
Module 'cloud_firestore' not found
```

That module happens to be the very first one in my `GeneratedPluginRegistrant.m` file.

I have confirmed that the Pods xcconfig referenced above does exist. I also located the following line in that xcconfig under `FRAMEWORK_SEARCH_PATHS`. A similar path exists under `HEADER_SEARCH_PATHS`, too:

```
"${PODS_CONFIGURATION_BUILD_DIR}/cloud_firestore"
```

Lastly, I don't know if it's related to this issue, but each of my schemes has a warning in XCode that states:

```
Release.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
```

I assume that warning isn't really a problem because none of the configurations use `Release.xcconfig` any more.

**Comment by jmagman** [comment]
```
Release.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
```
That's why it can't find `cloud_firestore`.  Is that path correct?  It's relative to `Release-Staging.xcconfig`.

**Comment by matthew-carroll** [comment]
If it's in relation to the location of the `.xcconfig` file then it should be:

```
#include "../Pods/Target Support Files/Pods-Staging/Pods-Staging.release-staging.xcconfig"
```

However, I tried that and still got the failure.

I have all the xcconfig's under the `ios/Flutter` directory.

I'm also finding that I can run `Product > Build` and it seems to complete without issue. But `Product > Archive` fails with the aforementioned error...just in case that sheds any light on the issue.

**Comment by jmagman** [comment]
> I'm also finding that I can run Product > Build and it seems to complete without issue. But Product > Archive fails with the aforementioned error...just in case that sheds any light on the issue.

That probably means Product > Build is building with a configuration that's set up correctly, and Product > Archive isn't.
Product > Scheme > Edit Scheme (Cmd+Shift+,) then the Run tab > Build Configuration is the one for `Build`

<img width="894" alt="Screen Shot 2020-07-06 at 5 49 24 PM" src="https://user-images.githubusercontent.com/682784/86678249-3a82f900-bfb1-11ea-8ede-c9ed888583e7.png">

Archive tab > Build Configuration is the one that's being used for `Archive`.
<img width="883" alt="Screen Shot 2020-07-06 at 5 49 59 PM" src="https://user-images.githubusercontent.com/682784/86678270-3fe04380-bfb1-11ea-8349-91f8cb176543.png">

You need to include both the Flutter `Generated.xcconfig` file to get the Flutter build configuration settings, and then CocoaPods `Pods-Runner.release.xcconfig` or whatever to get the right framework search paths for your plugins.

Hm I double checked some docs that confirm the `xcconfig` `#include` is supposed to be a path relative to the `xcconfig`, but then in a new Flutter project it's working, but relative to the project...
In `ios/Flutter/Debug.xcconfig`
```
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
#include "Generated.xcconfig"
```

**Comment by jmagman** [comment]
Anyway I'm sure it's supposed to be `Pods-Staging.release.xcconfig", nothing with `Runner` since that doesn't exist anymore.  `#include` the corresponding CocoaPods xcconfig paths and you should be good to go.

This is all under the "flavors docs for iOS suck" category, which is https://github.com/flutter/flutter/issues/57608.
There's no Flutter bugs to track here except for an existing documentation request.  Closing.

**Comment by matthew-carroll** [comment]
My supposedly "correct" debug-staging xcconfig configuration is:

```
#include "Pods/Target Support Files/Pods-Staging/Pods-Staging.debug-staging.xcconfig"
#include "Generated.xcconfig"
```

My supposedly "incorrect" release-staging xcconfig configuration is:

```
#include "Pods/Target Support Files/Pods-Staging/Pods-Staging.release-staging.xcconfig"
#include "Generated.xcconfig"
```

As you pointed out, the standard Flutter project uses paths like these. 

Changing to the path you suggested took me from 1 build error to 3 build errors.

Also, if I alter my scheme to use the `debug-staging` for Archive, it still fails with the same error, which suggests that it's not simply a correct debug config vs an incorrect release config.

It is unfortunate that this issue was aggressively closed.

For future reference, nothing here solved my issues and I continue to have a ship-blocking build failure that is jeopardizing my project. I continue to hope that issues like this move up the priority ladder for the team.

**Comment by jmagman** [comment]
You're hitting an issue with Xcode and CocoaPods way before the build phase is reentrantly calling into the Flutter tooling.  You can Google around for how to use CocoaPods (the plugin search path issue you're hitting), about and how to include paths into xcconfigs (you're not going to have a good time until that warning goes away), there are a million blog post about how build settings and build configurations work in Xcode, but it's just really confusing.

If you think this is bug in Flutter itself, or the way the template is generated, sharing your Xcode project (privately if you want) would be the most helpful and I can take a look.

Our docs are non-existant, and that's real issue.  We can keep discussing those docs at https://github.com/flutter/flutter/issues/57608 if you'd like.  We don't really need an open issue for every time our users are confused by flavors in iOS.

**Comment by matthew-carroll** [comment]
The only theory I have left with regard to this issue has to do with the "build" directory. So may be we can solve it here, and maybe it is at least related to the way Flutter is configured. The last time we discussed flavor support and I got something building in debug mode, it appeared that suddenly my ios builds were happening in the `ios/build/` directory rather than the root `build/` directory.

I noticed this because suddenly that whole directory was getting picked up by source control and I didn't know why. Simon Lightfoot mentioned that the `ios/build/` directory shouldn't be used at all.

After a little poking around, I'm thinking that what may be happening here is that part of Flutter expects all those Pod artifacts to exist in `build/`, which they do, but the build process is accessing `ios/build/` instead, which does not contain those artifacts.

I have no idea where Flutter configures the build system to choose a build directory. But here are a couple lines from my `Generated.xcconfig` that have me wondering...

```
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
```

The `SYMROOT` configuration seems to indicate that when this config is loaded, the working directory is `ios/`, which is why it goes up a directory so that it can access `build/ios`. But then if we look at `FLUTTER_BUILD_DIR` it just says `build`, which would seem to indicate that it wants to use the `ios/build/` directory, which is not the standard Flutter build directory.

Unfortunately, I opened another Flutter project and I see the same thing. So maybe that's not it. But it is definitely the case that I have a `build/` directory and a `ios/build/` directory. The top level directory has the Pod build artifacts under `ios/build/ios/`, e.g., headers, and the `ios/build/` directory does not. I just don't know where this configuration decision is being made, and I don't know if this is a Flutter decision or a Cocoa Pods decision...if you know that this is not a Flutter decision then I can go back to attempting to grok Cocoa Pods

**Comment by matthew-carroll** [comment]
Update: I decided to create a new Flutter project to see where things are going awry. Even in a new Flutter project, I'm able to build and run from Android Studio, I'm able to `Product > Build` from XCode, but `Product > Archive` in XCode fails with the same `Module XXXX not found`. 

I also tried this on `master`, where I was, and then I went to `Dev` and the issue still occurs.

With this new information, do you still think this is likely to be a pod-specific issue? If not, any idea where I should look next to debug this?

**Comment by jmagman** [comment]
Are you archiving from Runner.xcworkspace (and not Runner.xcodeproj)?

**Comment by matthew-carroll** [comment]
Nope, I opened Runner.xcodeproj...

Do you know of any command that I can run that would give me access to intermediate paths and other info that might help find the culprit?

**Comment by jmagman** [comment]
You need to be running from Runner.xcworkspace. See https://flutter.dev/docs/deployment/ios#create-a-build-archive.

**Comment by matthew-carroll** [comment]
Well....shame on me for not knowing about that guide...

![homer](https://user-images.githubusercontent.com/7259036/86746147-b308aa80-bfef-11ea-8957-0a13ef9cb7a4.gif)

I believe I now have an archive building. Still don't know what's up with those build directories, but I think things are working now :) Thanks for sticking with it.

**Comment by jmagman** [comment]
You shouldn't have a `ios/build/` directory, my guess is it's an artifact from the xcconfig not being set up and not pointing at the right `SYMROOT`.
