### ISSUE TITLE
[Camera] Camera preview (and photos taken) are zoomed in when using max resolution

### ISSUE THREAD

**Issue by aborzanovic** [flutter/flutter#60840]
## Steps to Reproduce

1. Run the [camera example app](https://github.com/flutter/plugins/tree/master/packages/camera/example)
2. But change the resolution preset from `ResolutionPreset.medium` to `ResolutionPreset.max`

(both images taken at the same distance, tested on iPhone SE 1st gen, camera plugin version 0.5.8+2)
**Expected results:** 
![IMG_7963](https://user-images.githubusercontent.com/10115976/86519475-53699e00-be3b-11ea-8b8f-6994e806ba87.PNG)

**Actual results:** 
![IMG_7956](https://user-images.githubusercontent.com/10115976/86519482-67ad9b00-be3b-11ea-80ee-1fb50ad907f6.PNG)

<details>
  <summary>doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by aborzanovic** [comment]
Found a fix for this.
Apparently if you want to take highest resolution pictures you should use `AVCaptureSessionPresetPhoto` instead of `AVCaptureSessionPresetHigh`.
But with `AVCaptureSessionPresetPhoto` you can't take videos.
So the solution for me was to declare a new `ResolutionPreset.photo` and use that for photos and `ResolutionPreset.max` for videos (and reinitialize camera controller when switching between photo and video modes).
I could make a quick PR to address this but I'm not sure this solution is good enough for everyone.

**Comment by 1996SEJR** [comment]
@aborzanovic I understand you are referring to ios, what would be the equivalent of the AVCaptureSessionPresetPhoto property in android?

**Comment by aborzanovic** [comment]
@1996SEJR I have no idea. I don't even know if Android has the same "zoom" issue.

**Comment by lts1610** [comment]
I have the same issue on Android (Samsung J5 Pro). Any solution?

**Comment by nekocode** [comment]
Related issue #58163
