### ISSUE TITLE
Image Picker fails to pick gallery images

### ISSUE THREAD

**Issue by naiksan-1020** [flutter/flutter#60850]
Hello, I am trying to pick image on my samsung s8 device. It works when i pick an image from 1st screen, If i select gallery from the drawer and try to pick image from there it comes back to the 1st screen and not to the flutter app screen.However I tried creating another project and tried the same, surprisingly it works. Please find attached images. 

(1st screen)
<img src="https://user-images.githubusercontent.com/65438617/86528483-f23adc80-bec5-11ea-935d-721127db0b3f.jpg" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />

(Gallery option)
<img src="https://user-images.githubusercontent.com/65438617/86528481-eea75580-bec5-11ea-8d02-92330a0e8a41.jpg" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />

**Comment by darshankawar** [comment]
Hi @naiksan-1020,
Can you please provide `flutter doctor -v`, `flutter run --verbose` and a minimal reproducible code sample ?

**Comment by SANSKARJAIN2** [comment]
Hi @naiksan-1020 
I also face the same issue.
This is a device-specific problem I guess and the same issue is also with the file picker.
It would be great if you could check it on any other device (having different specs/company) and update us.
Thank you

**Comment by naiksan-1020** [comment]
I face this issue for all devices. It works fine if I put image_picker in a new project. Funny. Please try and update. @SANSKARJAIN2

**Comment by darshankawar** [comment]
Hi @naiksan-1020,
Can you separate out the differences on the project you see the issue with the new project in which you don't see it ? There might be some plugins or dependency which might be causing that issue.
Can you please provide `flutter doctor -v`, a minimal reproducible code sample that shows the issue along with the devices on which you tried and seeing the issue.
Thanks.

**Comment by naiksan-1020** [comment]
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/username/libs/flutter
    • Framework revision b041144f83 (6 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

**Comment by darshankawar** [comment]
Hi @naiksan-1020,
Will also need a minimal complete reproducible code sample which shows the issue you are facing.
Thanks.

**Comment by TahaTesser** [comment]
HWithout additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
