### ISSUE TITLE
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable

### ISSUE THREAD

**Issue by cerenoyke** [flutter/flutter#60859]
Hello,

I'm getting this error when I call the flutter doctor in my cmd. I've tried everything I've seen on the web but it doesn't work. I reinstall it almost 10 times and nothing is changed. Please help me.

**Comment by shameemreza** [comment]
Did you set your environment variables path? If setup your environment variables path properly, then I will suggest you to downlaod the latest SDK tools and repalce it: https://developer.android.com/studio/releases/platform-tools

**Comment by cerenoyke** [comment]
I did and also I downloaded the latest SDK tools and replaced it. Doesnt work :(

**Comment by TahaTesser** [comment]
Hi @cerenoyke 
Can you please provide your `flutter doctor -v` and open `platform-tools` folder in your Android SDK and make sure it's not nested into another folder, when you `platform-tools` it should have all the files, there shouldn't another folder inside your `platform-tools` folder
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
