### ISSUE TITLE
Error:'Where is not recogized". while creating flutter app in android studio

### ISSUE THREAD

**Issue by salmanahamedg** [flutter/flutter#60864]
I got the this error: "where is not recognized as internal and external command,operable program or batch file" while creating Flutter testing app on android studio.

I did run "Flutter doctor" in cmd, I got no error here. And also I have installed flutter through plugins in android studio. Added the path for sdk tools properly.

But still I'm getting the above error.
Please help me!

![error](https://user-images.githubusercontent.com/45271898/86536175-27b1eb00-bf03-11ea-906c-a5725e3885ef.png)

**Comment by iapicca** [comment]
Hi @salmanahamedg 
given this [message](https://github.com/flutter/flutter/issues/36721#issuecomment-572767125) could you please make sure
that your set-up fulfils the [system requirements](https://flutter.dev/docs/get-started/install/windows#system-requirements);
after that please run from your terminal and with a device (physical or virtual) attached
```console
flutter upgrade -f
flutter doctor -v
flutter create test
cd test
flutter run -v
```
let me know if the issue persist
Thank you

**Comment by salmanahamedg** [comment]
When I typed the 3rd command , I got an error:
"Invalid project name: 'test' - this will conflict with Flutter package dependencies."
Thanks for help @iapicca 

My issue is still there. Please help me

**Comment by iapicca** [comment]
Hi @salmanahamedg 
my bad, I've updated the command,
please try again
Thank you

**Comment by SANSKARJAIN2** [comment]
This error also occurs if the path to the system32 folder is not present in the system environment variable.
you can directly add it by copy-pasting the path to system env. ('C:\Windows\System32' for my case this is the path and in most cases the path is same) 
alternatively, you can check the presence of system32 path by running 
where flutter
in the command line which will provide the path to you flutter installation directory

gen syntax for using where is 
where <search pattern>
(general syntax: where <search pattern> // By default, the search is done along the current directory and
    in the paths specified by the PATH environment variable.)

Hope this solves the issue.
Thank you

**Comment by salmanahamedg** [comment]
> Hi @salmanahamedg
> my bad, I've updated the command,
> please try again
> Thank you

**Comment by salmanahamedg** [comment]
Hi @iapicca 
It worked till the last line. After that I got this error:

"'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH."

**Comment by salmanahamedg** [comment]
@SANSKARJAIN2 
Still I'm getting error

Help appreciated.
Thank you

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by salmanahamedg** [comment]
Thank you so much @SANSKARJAIN2 
I didn't add C:\Windows\System32 path to env
It worked out
