### ISSUE TITLE
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)

### ISSUE THREAD

**Issue by amirmhmdi** [flutter/flutter#60860]
cache video player dosent play video from storage

**Comment by amirmhmdi** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/amir/development/flutter
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/amir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /home/amir/Downloads/android-studio-ide-191.5791312-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/amir/Downloads/android-studio-ide-191.5791312-linux/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • HTC One E9PLUS dual sim • LC5BSYH11913  • android-arm64 • Android 5.0.2 (API 21)
    • sdk gphone x86          • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!

**Comment by amirmhmdi** [comment]
flutter run --verbose


[  +20 ms] executing: [/home/amir/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/home/amir/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +8 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +5 ms] executing: [/home/amir/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/amir/development/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +36 ms] executing: [/home/amir/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +74 ms] executing: /home/amir/Android/Sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /home/amir/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           LC5BSYH11913           device usb:1-7 product:a55ml_dtul_htc_europe model:HTC_One_E9PLUS_dual_sim
           device:htc_a55ml_dtul transport_id:1
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm
           transport_id:3
[  +17 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d
all' to act on
           all devices.
[   +4 ms] /home/amir/Android/Sdk/platform-tools/adb -s LC5BSYH11913 shell getprop
[  +73 ms] ro.hardware = mt6795
[        ] ro.build.characteristics = default
[   +1 ms] /home/amir/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +18 ms] ro.hardware = ranchu
[   +1 ms] HTC One E9PLUS dual sim • LC5BSYH11913  • android-arm64 • Android 5.0.2 (API 21)
[        ] sdk gphone x86          • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)
[   +7 ms] "flutter run" took 211ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///home/amir/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by darshankawar** [comment]
Hi @amirmhmdi, by cache video player, are you referring to this plugin [cached_video_player](https://pub.dev/packages/cached_video_player) ?

**Comment by amirmhmdi** [comment]
@darshankawar no i just use this PR
video_player:
    git:
      url: https://github.com/sanekyy/plugins.git
      ref: caching
      path: packages/video_player/video_player

**Comment by amirmhmdi** [comment]
for network source work well but it dosen't work for read from File.
I used controller.network and pass local path to it instead of controller.file and now it work :?

**Comment by darshankawar** [comment]
@amirmhmdi so is it working for you now and resolves your original issue ?

**Comment by amirmhmdi** [comment]
@darshankawar  yes now it work

**Comment by darshankawar** [comment]
Hi @amirmhmdi,
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
