### ISSUE TITLE
Error in build while taking release APK

### ISSUE THREAD

**Issue by itzmejilson** [flutter/flutter#60868]
```bash
Running Gradle task 'assembleRelease'...
Setting VM flags failed: Unrecognized flags: obfuscate
Setting VM flags failed: Unrecognized flags: obfuscate
Setting VM flags failed: Unrecognized flags: obfuscate
Dart snapshot generator failed with exit code 255
Dart snapshot generator failed with exit code 255
Dart snapshot generator failed with exit code 255
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code 255
Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code 255
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code 255
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\FLUTTER\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\FLUTTER\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 5s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     127.1s (!)
Gradle task assembleRelease failed with exit code 1
```

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by JuYeong0413** [comment]
I think you accidently opened issues with no description with similar title.
https://github.com/flutter/flutter/issues/60867 and https://github.com/flutter/flutter/issues/60866 - how about closing these?

**Comment by iapicca** [comment]
Hi @itzmejilson 
given this [message](https://github.com/flutter/flutter/issues/57770#issuecomment-643959320) could you please try upgrading flutter to beta
```console
flutter channel beta
flutter upgrade -f 
```
if the issue persists could you please provide your updated `flutter doctor -v`, 
your `flutter build apk --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by attare026** [comment]
> flutter build apk --verbose

this not work for me I have already try and now again try to reinstall goto this guide line but face same error!

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by vaaniiaa** [comment]
@attare026  @iapicca 
Hello
I'm facing the same problem , could you resolve this issue finally?
Kindly let me know if there is any solution.
with regards
Aida

**Comment by vaaniiaa** [comment]
> @vaaniiaa
> please open a new issue providing your `flutter doctor -v`, your `flutter build apk -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

I resolved this issue and edited my above comment, thank you
