### ISSUE TITLE
[proposal] More granular FontWeight

### ISSUE THREAD

**Issue by mentoc3000** [flutter/flutter#60869]
Flutter is not currently able to make use of the weight control available to variable weight fonts. We are limited to weights of 100, 200, ..., 900 in [`FontWeight`](https://github.com/flutter/engine/blob/b341fd8397e30be2060a47c92298a2bd75e00b18/lib/ui/text.dart#L19). It would be very useful to access the intermediate weights, allowing finer control over typeface.

**Comment by davidmigloz** [comment]
Related to: https://github.com/flutter/flutter/issues/40457

**Comment by LongCatIsLooong** [comment]
duplicate of https://github.com/flutter/flutter/issues/33709
