### ISSUE TITLE
Probleme With Pedometer Plugin 1.2.0

### ISSUE THREAD

**Issue by HamzaAyada** [flutter/flutter#60875]
I tried to build an application to count the steps (via plugin "Pedometer 1.2.0"),
but I find a big problem during the generation of the application. when i use an smartphone (android 10, 9) it does not work but with smartphone (android 8, 7, 6) it works correctly. I have consult that the sensor is null. is there a solution to fix the sensor error in version 9,10 of android?

E/SensorManager( 1460): sensor is null

![107101277_721154055387201_7871996102427011058_n](https://user-images.githubusercontent.com/49845208/86545466-1e3a7a00-bf27-11ea-90d5-42e9ce2683e9.jpg)

**Comment by stuartmorgan** [comment]
https://pub.dev/packages/pedometer is not published by flutter.dev. You'll need to report this issue to the developer of that plugin.
