### ISSUE TITLE
Flutter warnings...

### ISSUE THREAD

**Issue by Smurfy007** [flutter/flutter#60881]
source value 7 is obsolete and will be removed in a future release

**Comment by iapicca** [comment]
Hi @Smurfy007 
Can you please provide your `flutter doctor -v`,
the full logs where this warning is shown
and your `pubspec.yaml`.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
