### ISSUE TITLE
local.properties not updated by flutter pub get

### ISSUE THREAD

**Issue by christophemacabiau** [flutter/flutter#60894]
The [documentation](https://flutter.dev/docs/deployment/android) states that
>After updating the version number in the pubspec file, run flutter pub get from the top of the project, or use the Pub get button in your IDE. This updates the versionName and versionCode in the local.properties file, which are later updated in the build.gradle file when you rebuild the Flutter app.

But it does not to work for versionCode/versionName
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
local.properties is updated already on build, but not on pub get (with current stable `1.17.5` and current master `1.20.0-3.0.pre.130`). I'm not sure whether it's intended behaviour and the issue is about documentation or not

**Comment by christophemacabiau** [comment]
same problem for ios

**Comment by kungfuslippers** [comment]
Same problem for me.

**Comment by Aravin** [comment]
yeah, not working as per flutter doc.

**Comment by Roshan13046** [comment]
> local.properties is updated already on build, but not on pub get (with current stable `1.17.5` and current master `1.20.0-3.0.pre.130`). I'm not sure whether it's intended behaviour and the issue is about documentation or not

I want to fix this issue.
only documentation changes are required here, isn't it?

**Comment by LosDanieloss** [comment]
If I may... It would be great if pub get would update local.properties as documentation states. Same goes for iOS name & build number. It'll allow us to know what we're going to build before running build itself which would be great.
