### ISSUE TITLE
Add gesture detector callbacks into Listview widget

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#60902]
## Use case

Most of the time we implement a ListView we want our items to receive a gesture detector like `onTap` or `onDoubleTap`, etc. Currently this can be easily achieved by using `ListView.build` and then wrap our item inside a `GestureDetector` widget (even thought we need to write one more widget for that) like this:
```dart
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      //...... other properties
      itemBuilder: (context, index) {
        return GestureDetector(
          onTap: () {
            // Handle tap for all items.
            Navigator.pushNamed(context, '/details', arguments: items[index]);
          },
          child: _MenuItem(items[index]),
        );
      },
    );
  }
```

But this is hard to achieve when we use the default `ListView` constructor:
```dart
  @override
  Widget build(BuildContext context) {
    return ListView(
      //....... other properties
      children: <Widget>[
        _MenuItem( MyItem(title: 'One')),
        _MenuItem( MyItem(title: 'Two')),
        _MenuItem( MyItem(title: 'Three')),
        _MenuItem( MyItem(title: 'Four')),
        _MenuItem( MyItem(title: 'Five')),
        _MenuItem( MyItem(title: 'Six')),
      ],
    );
  }
```

Now one need to setup `GestureDetector` for every item. There may be many other use cases maybe I'm just missing them right now.

## Proposal

My proposal is to have a built-in support for those events inside the `ListView` widget by providing gesture callbacks with the index of the pressed item.

I can send a PR once this is approved.

**Comment by goderbauer** [comment]
ListView is already pretty complicated as it is, I don't think we should be adding more stuff to it.

Flutter is composable, though. You can easily write a widget that wraps a ListView and provides the API you want.

**Comment by bihire** [comment]
Adding a `onHorizontalDrag` attributes on GestureDetecturer breaks the scrolling in the ListView.builder. how can I fix that @pedromassango
