### ISSUE TITLE
Reset RootViewController, enter the Flutter again and it will flash

### ISSUE THREAD

**Issue by pearl520922** [flutter/flutter#60906]
With the development of Native and Flutter, when the theme changes on the Settings page of the Flutter, notice the Native to reset the App and re-enter the Settings page, the page will flash. How to solve the flashing problem?

**Comment by VladyslavBondarenko** [comment]
Hi @pearl520922 
could you provide your `flutter doctor -v` and create a minimal reproducible project?
may be related to https://github.com/flutter/flutter/issues/60595

**Comment by pearl520922** [comment]
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/XX/Desktop/flutter
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/XX/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode11.5.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • iPhone SE • 7BCCAF9D-248E-4C54-8DEE-DFE0C19924D6 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)
    • iPhone XR • FE51C04D-C52F-4F01-B5B0-F782614DA43B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
@pearl520922 note that current stable flutter version is `1.17.5`.
could you provide a minimal reproducible project?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
