### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by AdrianoJPN** [flutter/flutter#60913]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by AdrianoJPN** [comment]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by darshankawar** [comment]
Hi @AdrianoJPN,
Your issue details seem to be incomplete.
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
