### ISSUE TITLE
Generate synthetic package for l10n.yaml

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#60914]
When provided with the config `synthetic: true`, will generate the source under `.dart_tool/flutter/flutter_gen` and update the package_config.json with the contents. `synthetic: true` could become opt-out instead of opt-in in the future, allowing a gradual migration from the old generation pattern.

fyi @shihaohong

**Comment by HansMuller** [comment]
NICE

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/61261
