### ISSUE TITLE
flutter driver should work with apps that use isolates

### ISSUE THREAD

**Issue by speaking-in-code** [flutter/flutter#60959]
## Use case

I would like to write a flutter driver test for an app that uses isolates. flutter driver is not compatible with these apps, since the isolates hang.

There are a lot of use cases for [apps that use isolates](https://flutter.dev/docs/development/packages-and-plugins/background-processes). I first encountered this when trying to use the [audio_service plugin](https://pub.dev/packages/audio_service), but the problem is quite general.

You can reproduce the problem with the small example in https://github.com/speaking-in-code/flutter-isolates

```
git clone https://github.com/speaking-in-code/flutter-isolates flutter-isolates
cd flutter-isolates/flutter_app
flutter drive --target test_driver/app.dart
```

The code for the app is in lib/main.dart. It starts an isolate, and waits for that isolate to send a message. The child isolate never runs, so the app hangs.

The app works correctly when started with flutter run

## Root Cause

The root cause of the issue is how the --start-paused flag is used and implemented.

flutter driver starts the app with the --start-paused flag
```
flutter run --start-paused test_driver/app.dart
```

On the device, the dart VM is then started with the [--pause_isolates_on_start](https://dart.dev/tools/dart-vm) flag.

Flutter driver then connects to the app on the device via the Observatory, and starts the first isolate.

All subsequent isolates, however, are still paused on start by the dart VM. Any functionality that relies on the isolates will fail.

## Proposal

I'm not sure how best to fix this.

One idea: modify flutter driver so that it watches for all new isolates started by the app, and unpauses them as soon as they are started. 

Another idea: eliminate the use of the --start-paused flag.

Another idea: Work with the Dart team to add a --pause_first_isolate equivalent that only pauses the first isolate, and not subsequent isolates like --pause_isolates_on_start.

Last resort: update flutter driver documentation to mention that integration testing apps that use isolates requires the use of the --use-existing-app flag to flutter drive. The approach I've used there:

```
flutter run --observatory-port 8888 --disable-service-auth-codes test_driver/main.dart
```

In another window, start the tests:
```
flutter drive --use-existing-app=http://127.0.0.1:8888/
```

## Other Details

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by darshankawar** [comment]
Related to [27429](https://github.com/flutter/flutter/issues/27429)

**Comment by darshankawar** [comment]
Hi @speaking-in-code,
I see there's an open issue addressing the case you described, [24703](https://github.com/flutter/flutter/issues/24703)
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
