### ISSUE TITLE
[Feature request] Extension method based widget API

### ISSUE THREAD

**Issue by handicraftsman** [flutter/flutter#60968]
# Use case

Currently flutter-based code is heavy to read, especially if you need to write a fancy component with advanced logic, and even splitting it into multiple ones doesn't solve that.

Flutter widgets introduce two or more levels of indentation in code, which can be often seen as an unnecessary burden, especially after seeing `if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program` quote from Linux style guide.

Here is a library which tries to solve this by implementing extension method wrappers for widget constructors: https://github.com/ReinBentdal/styled_widget .

## Proposal

It would be a nice idea to implement something like that in an autogenerated way where an additional tool scans code for widgets with, e.g. `@GenerateExtensionWrapper(name: "extMethodName")` metadata annotation.

This could allow generating exact same extension wrappers for people's custom widgets.

**Comment by goderbauer** [comment]
A code generate for this could live in an external package. We don't have plans to add something like this to the framework.
