### ISSUE TITLE
flutter.gradle is not exist

### ISSUE THREAD

**Issue by awarakhaki** [flutter/flutter#60961]
source\android\app\Users\minh\lib\flutter-stable\packages\flutter_tools\gradle\flutter.gradle' as it does not exist.

please tell me how to fix it?

**Comment by VladyslavBondarenko** [comment]
Hi @awarakhaki 
does https://github.com/flutter/flutter/issues/55619#issuecomment-624945046 help?
could you provide your `flutter doctor -v` and `flutter run --verbose log`?

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
