### ISSUE TITLE
Use  flutter screenshot to capture multiple frames at once 

### ISSUE THREAD

**Issue by fredlee12345678** [flutter/flutter#60964]
## Details

I used flutter sceenshot --type=skia --observatory-port to trace skpicture, but I can't only get one frame, I want to trace
some special frames, like the whole frames in 2-4 seconds, so what should I do?

**Comment by TahaTesser** [comment]
Hi @fredlee12345678 
Can you please describe why you need multiple frames? Also give us some use cases
Thank you

**Comment by fredlee12345678** [comment]
Hi @TahaTesser 
For example, I scroll the gridview from top to end very fast, and there will be some frozen frames because of gpu thread, but I am not sure which position will cause froze, maybe position 10, or position100 . So I need the whole frames to analyze which instructions to cause froze.

**Comment by jonahwilliams** [comment]
duplicate of https://github.com/flutter/flutter/issues/3496
