### ISSUE TITLE
flutter exited unexpectedly

### ISSUE THREAD

**Issue by Anag-coder** [flutter/flutter#60979]
Launching lib\main.dart on vivo 1951 in debug mode...
Running Gradle task 'assembleDebug'...

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for C:\Users\anagha\AndroidStudioProjects\quizzler-flutter\android\gradlew.bat.".
A crash report has been written to C:\Users\anagha\AndroidStudioProjects\quizzler-flutter\flutter_06.log

help me to fix this.thanks

**Comment by darshankawar** [comment]
Related to [53790](https://github.com/flutter/flutter/issues/53790)

**Comment by darshankawar** [comment]
Hi @Anag-coder,
I see there's an open issue addressing the case you described, [56975](https://github.com/flutter/flutter/issues/56975).
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Anag-coder** [comment]
Couldn't fix it
