### ISSUE TITLE
RenderBox was not laid out: RenderConstrainedBox#8bf0e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

### ISSUE THREAD

**Issue by aduonggm** [flutter/flutter#60970]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by YassineErrahim** [comment]
grtg

**Comment by darshankawar** [comment]
Hi @aduonggm,
Your issue details are incomplete. Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue you are getting ?
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
