### ISSUE TITLE
Let showDialog() and showModalBottomSheet() methods accept custom Navigator

### ISSUE THREAD

**Issue by denis-evteev** [flutter/flutter#60978]
In my application, I sometimes need to open dialogs or modal bottom sheets in a specific navigator. The `showDialog()` and `showModalBottomSheet()` methods only allow attaching a dialog or bottom sheet route to the current navigator or to the root one. Unfortunately, though, there is no way I can specify another navigator I’d like the widgets to be attached to.

It would be great if the above methods can accept a `NavigatorState` reference and use it to push the dialog or bottom sheet route to. For example:
```
Future<T> showModalBottomSheet<T>({
  @required BuildContext context,
  @required WidgetBuilder builder,
  Color backgroundColor,
  double elevation,
  ShapeBorder shape,
  Clip clipBehavior,
  Color barrierColor,
  bool isScrollControlled = false,
  NavigatorState navigator, // Add this argument
  bool useRootNavigator = false,
  bool isDismissible = true,
  bool enableDrag = true,
}) {}

Future<T> showGeneralDialog<T>({
  @required BuildContext context,
  @required RoutePageBuilder pageBuilder,
  bool barrierDismissible,
  String barrierLabel,
  Color barrierColor,
  Duration transitionDuration,
  RouteTransitionsBuilder transitionBuilder,
  NavigatorState navigator, // Add this argument
  bool useRootNavigator = true,
  RouteSettings routeSettings,
}) {}
```

**Comment by HansMuller** [comment]
You can provide a BuildContext parameter that's below the navigator you want. If you build these widgets with a GlobalKey, then `showFoo(context: myGlobalKey.currrentContext, ...)`.

**Comment by denis-evteev** [comment]
Thanks for your suggestion! It’s not a straightforward solution like the one I proposed, but it does solve the problem.

You can close this ticket if you’re not going to add the `navigator` argument. (I’m not sure now if that’ll be much better than specifying `context`.)

**Comment by HansMuller** [comment]
I'm going to close this issue for the now. @Piinks is working on a related issue, and although it doesn't address this specific problem, you might be interested in the PR. We'll update this issue with a pointer to the new  PR when it's makes its debut.

**Comment by denis-evteev** [comment]
Thinking about it again, I suppose that providing the `navigator` argument might nonetheless be a better solution, because it’s more likely that one has a `GlobalKey` referring to the navigator’s state than a `GlobalKey` referring to one of its child widgets. And besides, for your solution to work, the navigator in question _must_ have at least one widget beneath it, which is quite a strict requirement that might be difficult to fulfil.

**Comment by tomgilder** [comment]
Also got this issue, can you link to the PR/issue referred to above @HansMuller @Piinks?

**Comment by Piinks** [comment]
Hey @tomgilder there is a bunch of discussion in #57218, this comment in particular may be what you are looking for: https://github.com/flutter/flutter/issues/57218#issuecomment-652658250 :)
