### ISSUE TITLE
 Cannot resume sliding after activity onpause on Android

### ISSUE THREAD

**Issue by chengjianchao** [flutter/flutter#60976]
## Steps to Reproduce

1. scroll the tabBarView.
2. during scrolling，click menu-->show recent task
3. click flutter app，resume the app

**Expected results:scroll tabBarView normally

**Actual results:tabBarView can scroll,but can not drag end......

**Comment by VladyslavBondarenko** [comment]
Hi @chengjianchao 
could you provide your `flutter doctor -v` with a screen recording of the issue to understand what do you mean by 'drag end'?
And a complete minimal reproducible code sample if it doesn't reproduce with for example this one https://flutter.dev/docs/catalog/samples/tabbed-app-bar

**Comment by chengjianchao** [comment]
we use flutterboost....i find this problem caused by flutterboost，we will report this problem to flutterboost group，you can close this issue 。sorry。。。。。
