### ISSUE TITLE
ForceWebview parameter, when true, doesn´t download any document.

### ISSUE THREAD

**Issue by brunozanoelo** [flutter/flutter#60983]
I´ve spent hours to find one solution and I couldn´t find anything, in any plugin available.

Everytime that I click in one file on the internet, with the paramenter true, the app just don´t download the document, it seems to just don´t call anything in flutter, like nothing happened.

This is a **MUST HAVE** feature (**YES, IT IS**), and the only way that I could find to solve this problem and launch my App was to change the ForceWebView parameter to FALSE.

`class _FuncionalidadesPageState extends State<FuncionalidadesPage> {
  Future<void> _launchURLFuncionalidadeEscolida(String url) async {
    if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: true,
        forceWebView: false,
        enableJavaScript: true,
      );
    } else {
      throw 'Não foi Possível abrir o Serviço $url, verifique seu dispositivo ou contate seu Município.';
    }
  }`

Everything is updated, my packages and flutter.

**Comment by VladyslavBondarenko** [comment]
Hi @brunozanoelo 
please follow up on https://github.com/flutter/flutter/issues/39321,
may be related also to https://github.com/flutter/flutter/issues/48245.
This is not an issue with url_launcher, but issue with webview_flutter.
Closing as duplicate, if you disagree write in the comments and I will reopen it
