### ISSUE TITLE
Add footer Widget property to ReorderableListView

### ISSUE THREAD

**Issue by DebugTheCode** [flutter/flutter#60987]
## Use case

I would like to suggest the following: add a `header` like property, but instead being a non-reorderable top `Widget` in the list, a non-reorderable bottom `Widget` in the list.

## Proposal
So I propose to add a `footer` property to `ReorderableListView`

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/21195

**Comment by DebugTheCode** [comment]
@TahaTesser thanks, I was too fast. Sorry.
