### ISSUE TITLE
How make Row width the same as the widest for all other Rows

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#60980]
Hi,
I have a scenario that does not seem that complex but I am unable to get it to work.
I have a column that contains two rows:

The first row contains icons where you select an option on a scale say from 1 to 4.
The second row contains two text strings explaining the min and max value of the scale, say Sad vs Happy.
What I want to accomplish is that the labels on the second row are aligned to the far left and right of the row above.
I know I can put the Column in a fixed width Container and then use MainAxisSize.max on each Row but that would require me to compute the width of the Row with the Icons and that is not a viable option since the number of icons can change and their sizes as well.

Is there a good way to accomplish this? I tried Expanded on the Row, Align etc but none has provided a solution.

This is a minimal example of what I have so far:
```import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List iconList = [
    Icons.cloud,
    Icons.cloud_queue,
    Icons.wb_sunny,
    Icons.star,
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
      padding: const EdgeInsets.symmetric(vertical: 50.0, horizontal: 20.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text(
            'How do you feel today?',
          ),
          SizedBox(height: 24.0),
          Container(
            color: Colors.lightBlue[100],
            child: Column(
              children: <Widget>[
                Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: _buildIconBalls(),
                ),
                SizedBox(height: 8.0),
                Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('Min value'),
                      Text('Max value'),
                    ]),
              ],
            ),
          ),
        ],
      ),
    ));
  }

  List<Widget> _buildIconBalls() {
    return iconList
        .asMap()
        .map(
          (index, icon) => MapEntry(
              index,
              GestureDetector(
                onTap: () {},
                child: Container(
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: Colors.white,
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(12.0),
                    child: Icon(
                      icon,
                      size: 26,
                      color: Colors.black87,
                    ),
                  ),
                ),
              )),
        )
        .values
        .map((e) => [e, SizedBox(width: 15.0)])
        .expand((element) => element)
        .toList()
          ..removeLast();
  }
}
```

The result is this:
![column-issue](https://user-images.githubusercontent.com/48385990/86770952-c64c6200-c051-11ea-99c6-ca0baa7484d6.png)

But I want it to be like this:
![column-issue-correct](https://user-images.githubusercontent.com/48385990/86771018-d9f7c880-c051-11ea-907f-721c1327e0ea.png)

**Comment by TahaTesser** [comment]
i think this should be included into https://flutter.dev/docs/development/ui/layout

**Comment by ansolantz** [comment]
Hi @TahaTesser 
I am not able to find a solution for this specific issue there, are you thinking about a chapter in particular or did you mean that info could be added there?

My challenge is that I want to use:
mainAxisSize: MainAxisSize.min,
for the first Row and then have the second row adapt to the size of the first row so that the two labels are laid out with spaceBetween but respecting the size of the widest of the Rows in the column.

If the Column would use the full width it would not be an issue since both rows would span the whole width of the column but here the first Row should only use the space needed, hence the MainAxisSize.min.

**Comment by ansolantz** [comment]
Hi,
I found the solution, the here: [https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e](https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e) 
The `IntrinsicWidth()` did exactly what I wanted.

**Comment by TahaTesser** [comment]
Hi @ansolantz 
I have tried `IntrinsicWidth()` at first but this row wasn't getting any space in between
```  
   Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('Min value'),
                      Text('Max value'),
                    ]),
              ],
```

How do you solve that?
Please provide code sample, it might be worth adding to official doc itself 
Thank you

**Comment by ansolantz** [comment]
Hi @TahaTesser,

I wrapped it around the Column and it works fine with space between on the second row. 
Here is my code:

```
Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
      alignment: Alignment.center,
      padding: const EdgeInsets.symmetric(vertical: 50.0, horizontal: 20.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text(
            'How do you feel today?',
          ),
          SizedBox(height: 24.0),
          Container(
            color: Colors.lightBlue[100],
            child: IntrinsicWidth(
              child: Column(
                children: <Widget>[
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: _buildIconBalls(),
                  ),
                  SizedBox(height: 8.0),
                  Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text('Min value'),
                        Text('Max value'),
                      ]),
                ],
              ),
            ),
          ),
        ],
      ),
    ));
  }

```
