### ISSUE TITLE
Slight increase over time in flutter_gallery_v2_web_compile_test new_gallery_dart2js_size

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60994]
I rebaselined this last time, but I'm worried this continues to creep upward.

Currently affected by
![Screen Shot 2020-07-07 at 9 13 23 AM](https://user-images.githubusercontent.com/1435716/86810786-20d5c600-c032-11ea-8580-5065f6932000.png)
 engine roll https://github.com/flutter/flutter/pull/60742.

**Comment by kf6gpe** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Rebaselined.
