### ISSUE TITLE
Tab bar is not showing its child after rotate the screen to landscape mode in flutter application

### ISSUE THREAD

**Issue by Nishikant26** [flutter/flutter#61001]
I am implementing Tabbar in my application so I have started to learn from dart [documentation](https://flutter.dev/docs/cookbook/design/tabs).

I have tried to run the code provided in the documentation and it is working fine but when I rotate the screen to landscape mode the child of the tab is not displaying.

There are 3 tabs on the screen, go to the 3rd tab and rotate the screen to landscape mode, The tab view of the 3rd tab is not getting display but if I tap on anywhere on the screen then it is getting slide on the screen.

What should the issue that is causing it? Is this an issue with the flutter SDK or I am doing something wrong.

Screenshot for the reference -

[Tabs on portrait mode](https://i.stack.imgur.com/5uZwK.png)

[Tabs after landscape mode](https://i.stack.imgur.com/z2r0P.png)

[Content is getting displayed after taping on the screen](https://i.stack.imgur.com/KTMIQ.png)

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_GB.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Hi @Nishikant26,
I see there's an open issue addressing the case you described, [60288](https://github.com/flutter/flutter/issues/60288)
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
