### ISSUE TITLE
SliverMultiboxAdaptorElement (e.g. GridView) retains widgets it shouldn't

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#61006]
Specifically, the `_childWidget`s cache might not ever get cleared if the widget doesn't rebuild, and indefinitely hold on to child widgets even if they exceed the cache extent. This is a serious issue if the widget has any field on it that is expensive to hold, such as a large Uint8List for image or file data. Here's a simple case that is problematic:

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(
    MaterialApp(
      home: GridView.builder(
        addAutomaticKeepAlives: false,
        cacheExtent: 0,
        itemCount: 300,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          mainAxisSpacing: 3,
          crossAxisSpacing: 3,
        ),
        itemBuilder: (BuildContext context, int index) {
          return ExpensiveWidget(child: Text(index.toString()));
        },
      ),
    ),
  );
}

class ExpensiveWidget extends StatelessWidget {
  ExpensiveWidget({
    Key key,
    int size = 1000000,
    @required this.child,
  }) : _expensive = List<int>(size);

  final List<int> _expensive;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return SizedBox(height: 200, width: 200, child: child);
  }
}
```

/cc @chunhtai who is in the blame for this code and might have a quick idea for a fix. I suspect we need to take into acount the cacheExtent to make sure that we don't indefinitely grow the _childWidgets hashmap here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/sliver.dart#L1062

We clear it on performRebuild, but that rebuild might not happen when we want it to. We should probably trim it here: https://github.com/flutter/flutter/blob/2ab509943660c62281e7b48648c06b057e028c65/packages/flutter/lib/src/widgets/sliver.dart#L1136

**Comment by dnfield** [comment]
It's not really clear to me why we're caching widgets at all. They shoul dbe very cheap to build right?

**Comment by chunhtai** [comment]
It is probably for scrolling, the rebuild should not happen this much

**Comment by chunhtai** [comment]
can we keep a LRU Cache?

**Comment by dnfield** [comment]
We could, but how would we determine the size?

**Comment by mehmetf** [comment]
Could we give widgets an option to build a cheap version of themselves and then request the "heavy" version based on scroll speed? Fast scrolling photos apps often would render a "border" (no image) when user is scrolling really quickly then fill up as they slow down. This is tricky to get right and we probably need to make things configurable (such as how many heavy widgets do they want cached).

**Comment by dnfield** [comment]
@mehmetf - I don't think we should expect consumers of this widget to reason about that. It's not clear to me at all that we gain much performance wise by doing this caching - I'm proposing we remove it, and if someone finds a performance issue with that we can try to come up with an LRU type of caching that we'd have to expose up to callers.

**Comment by dnfield** [comment]
Benchmarks before and after for memory usage:

![image](https://user-images.githubusercontent.com/8620741/86998511-63e48600-c165-11ea-8021-a0ef7abfdde4.png)
