### ISSUE TITLE
Flutter analyze failing with url_launcher version mismatch

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#61032]
This seems to be happening in: https://github.com/flutter/flutter/pull/61013/checks?check_run_id=847241058

Also @jmagman saw it in: https://github.com/flutter/flutter/pull/61007/checks?check_run_id=847178285

This might have to do with gallery changes.

**Comment by Piinks** [comment]
Just saw this as well on https://github.com/flutter/flutter/pull/58640/checks?check_run_id=847292363

**Comment by Piinks** [comment]
Covered in more detail in https://github.com/flutter/flutter/issues/61044
