### ISSUE TITLE
The new flutter gallery has unpinned depdendencies, and macrobenchmarks depends on flutter gallery

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#61044]
See https://github.com/flutter/flutter/blob/fb57edcc80dbfc75e2f42e4fb52ff730c13c29c8/dev/benchmarks/macrobenchmarks/pubspec.yaml#L21-L24

And https://github.com/flutter/gallery/blob/8ec7fdb5d599f8fd085b1d18de6f24a765fd07af/pubspec.yaml#L9

Causes errors like: 
```
▌20:52:15▐ RUNNING: cd .; bin/flutter analyze --dartdocs --flutter-repo
Package "url_launcher" has conflicts:
  1 source wants "/root/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/lib":
    /tmp/flutter sdk/dev/benchmarks/macrobenchmarks/.packages
  1 source wants "/root/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.11/lib":
    /tmp/flutter sdk/dev/integration_tests/flutter_gallery/.packages
Make sure you have run "pub upgrade" in all the directories mentioned above.
```

When a plugin like url_launcher publishes a new version that the Flutter repo hasn't be rolled to yet.

I don't think we can fix this without removing the Gallery as a dependency on macrobenchmarks...

@yjbanov @jonahwilliams @zanderso

**Comment by dnfield** [comment]
We could try to run a roller for packages more regularly, but we'd still have some periods of time where autorollers created new commits that fail because of dependency mismatches.

**Comment by yjbanov** [comment]
Do you suggest that we pin the dependencies in Flutter Gallery?

**Comment by dnfield** [comment]
Yeah, and then we just have to roll those before rolling the flutter repo I guess.  That would fix it for now, although it makes rolling more complicated.

**Comment by dnfield** [comment]
We would also have to pin all the transitive deps of the gallery in gallery...

**Comment by yjbanov** [comment]
Yeah, I don't think it will work, for the reasons you are describing, not without some script/process that would keep gallery's and flutter's dependencies both pinned and in sync. What's wrong with treating the gallery like any other Dart package and relying on semantic versioning?

**Comment by yjbanov** [comment]
...and pub's ability to resole versions.

**Comment by dnfield** [comment]
Ahhh yeah, so I think another way of looking at this problem is that the update-packages script isn't getting the transitive deps of the gallery when it writes the pubspec of macrobenchmarks.  @jonahwilliams might have some good idea there as to why that is?  Otherwise we have to dig through the code.

**Comment by dnfield** [comment]
The bug is that we don't parse out git or file based dependencies properly in `update_packages.dart`.

That should be fixable.
