### ISSUE TITLE
OutlineButton missing materialTapTargetSize property in constructor

### ISSUE THREAD

**Issue by NoizyCr1cket** [flutter/flutter#61061]
## Use case

The OutlineButton's constructor doesn't allow for specifying a value for `materialTapTargetSize`, while other buttons do (RaisedButton, FlatButton, FloatingActionButton and MaterialButton).

## Proposal

Include materialTapTargetSize in the OutlineButton's constructor.

See comment here where this was intended to be included in a PR, but was not: https://github.com/flutter/flutter/pull/27575#issuecomment-461236100.

**Comment by md-weber** [comment]
I would like to work on this issue, and work on the missing value. @shihaohong @Piinks

**Comment by HansMuller** [comment]
Should be an easy fix, please submit a PR!

**Comment by md-weber** [comment]
The issue can be closed - Fix in https://github.com/flutter/flutter/pull/61086
