### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by kkishinn** [flutter/flutter#61065]
I am having a problem trying to request from flutter. I tested it in a new project and I tested both with the http package and with using the native request of flutter, I attach an example of the request that does not work for me.

```dart
var response = await http.post('https://live.decidir.com/api/v2/tokens', body: 
jsonEncode({
"card_number": "4507990000004905",
"card_expiration_month": "08",
"card_expiration_year": "20",
"security_code": "123",
"card_holder_name": "John Doe",
"card_holder_identification": {
"type": "dni",
"number": "25123456"
        }
      }),
      headers: {
"apikey": "e9cdb99fff374b5f91da4480c8dca741",
"Content-Type": "application/json",
"Cache-Control": "no-cache"
      }
    );
```

The same request in the dev environment of the same server does not give me this problem, only have this problem in production (live)

**Comment by kkishinn** [comment]
en postman, esta peticion funciona correctamente, en flutter no

**Comment by kkishinn** [comment]
In postman, this request works correctly, in flutter it does not

**Comment by maheshmnj** [comment]
can you please provide some info about your development environment and paste the output of ```flutter doctor -v```

**Comment by softmarshmallow** [comment]
we need more description. 
1. paste your request & response of postman
2. paste your request & response of flutter

status codes ect..

**Comment by SANSKARJAIN2** [comment]
Hi @kkishinn 
Did you provide internet access permission?
Thank you

**Comment by maheshmnj** [comment]
I tried runnng your example and I was able to get the response back as 
```{"message":"Invalid authentication credentials"}```
And as mentioned by @SANSKARJAIN2 
please check for internet permissions under android->app->src->main->AndroidManifest.xml

**Comment by softmarshmallow** [comment]
IF -> server's certificate issue
the host seems not trusted by android.
this can happen.

in same consequences, it will work on ios, if your code is correct.
you can provide CA certificate in your request or simply ask the api service provider about the certificates.


IF -> you just have wrong request without authentication on flutter proj. (missing header etc..)

not a flutter issue.

**Comment by iapicca** [comment]
Hi @kkishinn 
I believe the @softmarshmallow, @maheshmnj and @SANSKARJAIN2 
are probably right for your case, nevertheless
you may want to follow up on this [issue](https://github.com/flutter/flutter/issues/58676)
I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
