### ISSUE TITLE
[intl] Support for Cantonese languages

### ISSUE THREAD

**Issue by dgandhi17** [flutter/flutter#61068]
Support for Mandarin and Cantonese languages

**Comment by iapicca** [comment]
Hi @dgandhi17 
I'm not a linguist, but isn't Standard Chinese == Modern Standard Mandarin?
If so, isn't it already supported?
Thank you

**Comment by dgandhi17** [comment]
@iapicca I saw that but the other one I am not sure though. you know anyone who can confirm this thing?

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Both should already be supported in the Material and Cupertino libraries. For example, here is the [zh_HK translations](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/material_zh_HK.arb) and the [zh translations](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/material_zh.arb).

I'll close this issue for now, but please feel free to re-open if this isn't the case.
