### ISSUE TITLE
DatePicker field option optional, allow to provide date formate for InputField in DatePicker.

### ISSUE THREAD

**Issue by mangoliprasanna** [flutter/flutter#61074]
Hi 

Recenrtly i have upgraded the flutter version to v1.17 and observed the changes in DatePicker. I have also tried switchable field option which is really great. but it seems that the field option only accepts the date formate (mm/DD/yyyy). I didn't find any option to change the dateformate of that InputField. 

Also i did not find an option to disable the switch option and make the toggle button hidden.

![Screenshot 2020-07-08 at 1 08 03 PM](https://user-images.githubusercontent.com/28045898/86891191-10017f00-c11c-11ea-9a00-b44dc5dc0e93.png)

**Comment by darshankawar** [comment]
Hi @mangoliprasanna,
There's a similar open issue, [55535](https://github.com/flutter/flutter/issues/55535). Please follow-up there for updates.
I am closing this one as duplicate. If you disagree please write in the comments and I will reopen it.
