### ISSUE TITLE
Request Focus Node Issue

### ISSUE THREAD

**Issue by andrefedev** [flutter/flutter#61076]
Because it is not possible to use a requestFocus in a parent Widget and send it to a child Widget. The only way to get it to work is to initialize the \*\*LoginTextField\*\* widget in \*\*initState\*\*(), but if I want to change any state later that is passed to the child widget it ignores them.

I need to divide certain widgets into separate classes because they have complex logic and are very large, I don't want to end up with a huge class, so that's why I am using separate widgets in different files.

    class _LoginScreenState extends State<LoginScreen> {
      TextEditingController _textController;
      FocusNode _textFocusNode;
      bool _textIsEnabled;

      @override
      void initState() {
        super.initState();
        _textController = TextEditingController();
        _textFocusNode = FocusNode();
        _textIsEnabled = true;
      }

      @override
      void dispose() {
        _textController.dispose();
        _textFocusNode.dispose();
        super.dispose();
      }

      void _handleOnSubmit() {
        try {
          // logic...
        } catch (err) {
          // other logic..
          _textFocusNode.requestFocus(); // this not work
        }
      }

      @override
      Widget build(BuildContext context) {
        return Container(
          // .. other widgets
          child: Column(
            children: <Widget>[
              LoginTextField(
                textController: _textController,
                textFocusNode: _textFocusNode,
                isEnabled: _textIsEnabled,
              ),
              RaisedButton(
                child: Text('Send'),
                onPressed: _handleOnSubmit,
              )
            ],
          )
        );
      }
    }

    class LoginTextField extends StatefulWidget {
      final TextEditingController textController;
      final FocusNode textFocusNode;
      final bool isEnabled;

      LoginTextField({this.textController, this.textFocusNode, this.isEnabled});

      @override
      _LoginTextFieldState createState() => _LoginTextFieldState();
    }

    class _LoginTextFieldState extends State<LoginTextField> {
      @override
      Widget build(BuildContext context) {
        return TextField(
          controller: widget.textController,
          focusNode: widget.textFocusNode,
          enabled: widget.isEnabled,
          /// other logic...
        );
      }
    }

**Comment by VladyslavBondarenko** [comment]
@andrefedev 
are you sure error is thrown and that `_textFocusNode.requestFocus();` should be in catch block?

I tried and it's working when I move it out of catch block or when I throw an exception

```
void _handleOnSubmit() {
    try {
      throw("some error");
      // logic...
    } catch (err) {
      // other logic..
      _textFocusNode.requestFocus(); // this not work
    }
  }
```

**Comment by andrefedev** [comment]
@VladyslavBondarenko 
You're right I just created a clean project and it works for me. I'm going to look for the failure and what is causing it, I'll be back.

**Comment by VladyslavBondarenko** [comment]
@andrefedev 
if you are hitting some error with this, provide then complete minimal reproducible code sample and logs together with your `flutter doctor -v`
