### ISSUE TITLE
App name is Runner after flutter update

### ISSUE THREAD

**Issue by a43mrk** [flutter/flutter#61070]
Hello!
After i updated flutter the app name changed to runner :(
what can i do to fix?

**Comment by iapicca** [comment]
Hi @a43mrk 
Could you please provide more details about this issue,
did the app name changed in the `pubspec.yaml`?

Can you please provide your `flutter doctor -v` 
and your `pubspec.yaml`.
Thank you

**Comment by a43mrk** [comment]
thank you @iapicca!
Its solved. :)
