### ISSUE TITLE
Tooltip copy paste error when Max Fontsize in Settings in iOS Device

### ISSUE THREAD

**Issue by dung2212** [flutter/flutter#61084]
![IMG_0237](https://user-images.githubusercontent.com/8814434/86909094-c592f900-c141-11ea-85fc-b10713ebdbb7.PNG)
---------
![IMG_0239](https://user-images.githubusercontent.com/8814434/86909112-cb88da00-c141-11ea-8032-2957d5096b0a.jpg)
At iOS device. I settings the max TextSize. At Textfield I hold to display the tooltip copy paste. It broke the interface

**Comment by TahaTesser** [comment]
Hi @dung2212 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample. Please provide list of devices you're experiencing this issue on 
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
