### ISSUE TITLE
is:issue Invalid argument(s): Cannot find executable for C:\Users\Rakul\AndroidStudioProjects\test_app\android\gradlew.bat. 

### ISSUE THREAD

**Issue by rakulvm** [flutter/flutter#61088]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
Hi @rakulvm 
I see there's an open [issue](https://github.com/flutter/flutter/issues/56975) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
