### ISSUE TITLE
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)

### ISSUE THREAD

**Issue by pulkitnanda49** [flutter/flutter#61096]
```
E/flutter ( 7766): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)
[38;5;248mE/flutter ( 7766): #0      VideoPlayerApi.create[39;49m
E/flutter ( 7766): <asynchronous suspension>
[38;5;248mE/flutter ( 7766): #1      MethodChannelVideoPlayer.create[39;49m
[38;5;248mE/flutter ( 7766): #2      VideoPlayerController.initialize[39;49m
[38;5;248mE/flutter ( 7766): #3      _VideoItemTileState.setupVideo[39;49m
[38;5;248mE/flutter ( 7766): #4      _VideoItemTileState.initState[39;49m
[38;5;244mE/flutter ( 7766): #5      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #6      ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #7      Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #8      Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #9      SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #10     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #11     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #12     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #13     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #14     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #15     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 7766): #16     Element.rebuild[39;49m
[38;5;244mE/flutter ( 7766): #17     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #18     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #19     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #20     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #21     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 7766): #22     Element.rebuild[39;49m
[38;5;244mE/flutter ( 7766): #23     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #24     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #25     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #26     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #27     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 7766): #28     StatefulElement.performRebuild[39;49m
[38;5;244mE/flutter ( 7766): #29     Element.rebuild[39;49m
[38;5;244mE/flutter ( 7766): #30     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #31     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #32     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #33     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #34     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #35     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 7766): #36     Element.rebuild[39;49m
[38;5;244mE/flutter ( 7766): #37     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 7766): #38     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 7766): #39     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 7766): #40     Element.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #41     SliverMultiBoxAdaptorElement.updateChild[39;49m
[38;5;244mE/flutter ( 7766): #42     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 7766): #43     BuildOwner.buildScope[39;49m
E/flutter ( 7766): #44     SliverMultiBoxAdaptorElemen
```

Implemented video player in an another app it is working but not in this app.

Pls check and help.

**Comment by VladyslavBondarenko** [comment]
Hi @pulkitnanda49 
could you provide your `flutter doctor -v` and a minimal reproducible code sample/project?
specify used video_player version

**Comment by pulkitnanda49** [comment]
doctor statement
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version    
 
[√] Android toolchain - develop for Android devices (Android SDK       
    version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

• No issues found!

Code Used

`import 'package:flutter/material.dart';
import 'package:flutter_emoji/flutter_emoji.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:liquid_ui/liquid_ui.dart';
import 'package:news_app/widgets/list_reactions.dart';
import 'package:news_app/widgets/view_count.dart';
import 'package:video_player/video_player.dart';

class VideoItemTile extends StatefulWidget {
  @override
  _VideoItemTileState createState() => _VideoItemTileState();
}

class _VideoItemTileState extends State<VideoItemTile> {
  final parser = EmojiParser();
  VideoPlayerController _controller;
  Future<void> setupVideo() async {
    _controller = VideoPlayerController.network(
        'https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4');

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.setVolume(0);
    _controller.initialize().then((_) => setState(() {}));
  }

  @override
  void initState() {
    super.initState();
    setupVideo();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: EdgeInsets.all(10.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                CircleAvatar(
                  maxRadius: 12,
                  backgroundColor: Colors.cyan,
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                  child: LText(
                    '\l.h6.bold{Account Name}',
                  ),
                ),
                Text(
                  '3hr',
                  style: TextStyle(
                      color: Colors.grey,
                      fontSize: 15.0,
                      fontWeight: FontWeight.w400),
                ),
              ],
            ),
          ),
          // AspectRatio(
          //   aspectRatio: 16 / 9,
          //   // child: VideoPlayer(_controller),
          //   child: Image.asset('assets/images/a.jpg'),
          // ),
          Center(
            child: _controller.value.initialized
                ? AspectRatio(
                    aspectRatio: 16 / 9,
                    child: VideoPlayer(_controller),
                  )
                : Container(),
          ),
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 12.0, vertical: 15.0),
            child: Text(
              'CoronaVirus News Alert',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 22.0),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          Container(
            padding: EdgeInsets.symmetric(horizontal: 12.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                ViewCount(parser: parser),
                ListReactions(parser: parser),
              ],
            ),
          ),
          Divider(
            height: 22,
            thickness: 1.5,
          ),
          Container(
            padding: EdgeInsets.symmetric(vertical: 5.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Text(
                  parser.emojify('👍'),
                ),
                Icon(
                  FontAwesomeIcons.comment,
                  size: 16.0,
                ),
                Icon(
                  FontAwesomeIcons.shareSquare,
                  size: 16.0,
                ),
              ],
            ),
          ),
          Divider(
            height: 20.0,
            thickness: 2,
          ),
          // LIconButton(
          //   color: Colors.amber,
          //   icon: _controller.value.isPlaying
          //       ? Icon(Icons.pause)
          //       : Icon(Icons.play_arrow),
          //   onPressed: () {
          //     setState(() {
          //       _controller.value.isPlaying
          //           ? _controller.pause()
          //           : _controller.play();
          //     });
          //   },
          // )
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
`

**Comment by VladyslavBondarenko** [comment]
Hi @pulkitnanda49 
<details>
 <summary>I simplified a bit your code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MaterialApp(home: SafeArea(child: Scaffold(body: VideoItemTile()))));

class VideoItemTile extends StatefulWidget {
  @override
  _VideoItemTileState createState() => _VideoItemTileState();
}

class _VideoItemTileState extends State<VideoItemTile> {
  VideoPlayerController _controller;

  Future<void> setupVideo() async {
    _controller = VideoPlayerController.network(
        'https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4');

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.setVolume(0);
    _controller.initialize().then((_) => setState(() {}));
    _controller.play();
  }

  @override
  void initState() {
    super.initState();
    setupVideo();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
            child: _controller.value.initialized
                ? AspectRatio(
              aspectRatio: 16 / 9,
              child: VideoPlayer(_controller),
            )
                : Container(),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

</details>

And tried to run it on Redmi Note 7 Android 9 (API 28) and Android 10 (emulator), used video_player: ^0.10.11+2 with stable `1.17.5` and current master `1.20.0-3.0.pre.192`, but couldn't reproduce.

What plugin's version are you using? With what device are you experiencing the exception?

**Comment by pulkitnanda49** [comment]
I have tried in both android 9 Realme u1 and Android7(emulator), used video_player:">=0.10.y+x <2.0.0" and without defining any particular version also with stable 1.17.5 and master as well.

**Comment by VladyslavBondarenko** [comment]
@pulkitnanda49 
have you replaced y and x there by some numbers?
does it persist if you use `video_player: ^0.10.11+2`, `flutter pub get` and run?

**Comment by pulkitnanda49** [comment]
I tried using it but still receiving the same error on this project.

**Comment by VladyslavBondarenko** [comment]
@pulkitnanda49 
does it happen when using master channel as well?

**Comment by pulkitnanda49** [comment]
Yes

**Comment by pulkitnanda49** [comment]
Any suggestion on how can I implement it in this project

**Comment by Sese-Schneider** [comment]
@VladyslavBondarenko @pulkitnanda49 I could reproduce this issue with `video_player: '=>0.10.10' It looks like this got broken starting at `0.10.10`, as its working on `0.10.9`. 
I think there is a network import issue.

Tested on channel `stable`, `v1.17.x`, HST file.

**Comment by VladyslavBondarenko** [comment]
@Sese-Schneider could you provide link to the file with which you can reproduce the exception? does it persist with this code sample?

**Comment by Sese-Schneider** [comment]
@VladyslavBondarenko unfortunately I cannot provide the HST file as it's confidential, however, I also tested with the code above which gave me the same issue.

How can I help you troubleshooting it?

**Comment by VladyslavBondarenko** [comment]
@Sese-Schneider ok, never mind then about file. 
With what device/emulator are you experiencing this? May be device-specific. About emulators, I tried with Android 10.0 (API 29) and Android 7.0 (API 24). Could you check if it reproduces with video_player 0.10.11+2 and with current master version?

**Comment by Sese-Schneider** [comment]
@VladyslavBondarenko will do later 👍🏼

**Comment by Sese-Schneider** [comment]
@VladyslavBondarenko I found the bug!

### Reason:
> **The plugins module is not registered in the `GeneratedPluginRegistrant.java`. If the registration is missing, you get the said error!**

<details>E/flutter (19506): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)
E/flutter (19506): #0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:220:7)
E/flutter (19506): <asynchronous suspension>
E/flutter (19506): #1      MethodChannelVideoPlayer.init (package:video_player_platform_interface/method_channel_video_player.dart:20:17)
E/flutter (19506): #2      _videoPlayerPlatform (package:video_player/video_player.dart:23:5)
E/flutter (19506): #3      _videoPlayerPlatform (package:video_player/video_player.dart:20:27)
E/flutter (19506): #4      VideoPlayerController.initialize (package:video_player/video_player.dart:265:24)
E/flutter (19506): #5      _VideoItemTileState.setupVideo (package:app2/player.dart:20:17)
E/flutter (19506): #6      _VideoItemTileState.initState (package:app2/player.dart:28:5)
E/flutter (19506): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (19506): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #10     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
E/flutter (19506): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (19506): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
E/flutter (19506): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (19506): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (19506): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #45     Element.rebuild (package:f
E/flutter (19506): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)
E/flutter (19506): #0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:242:7)
E/flutter (19506): <asynchronous suspension>
E/flutter (19506): #1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42)
E/flutter (19506): #2      VideoPlayerController.initialize (package:video_player/video_player.dart:265:45)
E/flutter (19506): #3      _VideoItemTileState.setupVideo (package:app2/player.dart:20:17)
E/flutter (19506): #4      _VideoItemTileState.initState (package:app2/player.dart:28:5)
E/flutter (19506): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (19506): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
E/flutter (19506): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (19506): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
E/flutter (19506): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (19506): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (19506): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (19506): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (19506): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (19506): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (19506): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (19506): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (19506): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)</details>

### **How can this happen?**
I've filed a bug report about this yesterday! https://github.com/flutter/flutter/issues/61350

Basically, if you have an app, and an example sub-app, the generation for the `GeneratedPluginRegistrant` only happens on the "first" app, the example.
This leads to the plugin platform channel be not registered into the `GeneratedPluginRegistrant`. I tested this by disallowing write onto the file. Normally, flutter exits with exit code 1 if that happens, but if there are  2 apps with `flutter pub get`, nothing happens and the main registrant doesn't get edited!

### This is a bug which should be resolved ASAP
@VladyslavBondarenko could you maybe look into https://github.com/flutter/flutter/issues/61350 and bump the severity?

### Workaround
Delete every other sub-app in your directory, run `flutter pub get` and restore the deleted files from version control.
Now the plugin registrant should be updated with:
```
flutterEngine.getPlugins().add(new io.flutter.plugins.videoplayer.VideoPlayerPlugin());
```

**Comment by VladyslavBondarenko** [comment]
@pulkitnanda49 Thank you! I didn't get that it may be the cause

**Comment by Sese-Schneider** [comment]
@VladyslavBondarenko no problem! when do you think #61350 can be resolved?

**Comment by pulkitnanda49** [comment]
@VladyslavBondarenko @Sese-Schneider 
I found that video_player doesn't support m3u8 file it worked fine after clearing all cache and changing link for mp4 file.

**Comment by Sese-Schneider** [comment]
@pulkitnanda49 It does:

```
VideoPlayerController.network( 
      'https://cdn.example.com/manifests/file.m3u8', 
      formatHint: VideoFormat.hls, 
)
```

**Comment by prabhatt16** [comment]
3

**Comment by khanna007** [comment]
I tried to upgrade flutter to stable channel version 1.20.1 and stop all the task and run the code again this will work

**Comment by yostrokon** [comment]
Have similar troubles
in debug works fine, in release have same error
using flutter run --release works nice
using flutter build apk, install and run from device cause an exception mentioned in topic

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-BG)
    • Flutter version 1.20.4 at /Users/yourii/Development/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yourii/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • XT1068 (mobile) • ZX1D22NV6R • android-arm • Android 6.0 (API 23)

**Comment by HiroshiHorie** [comment]
Having the same issue here....

**Comment by yostrokon** [comment]
solved by downgrading gradle

**Comment by Skyggedans** [comment]
> solved by downgrading gradle

Can you name a version please?

**Comment by sobhan15** [comment]
> solved by downgrading gradle

same issue,
Which version has solved your problem?

**Comment by 4eug** [comment]
same old issue can't to find a solution

**Comment by sanicle** [comment]
> solved by downgrading gradle

I can't find a solution. How to solve this problem?

**Comment by dnfield** [comment]
This can happen if the plugin you're trying to use doesn't exist for the platform you're on, or if your build for the platform you're using failed to generate the registrant.

For example, I got here by googling this message after trying to use `video_player` on macos, which isn't supported.

**Comment by 4eug** [comment]
solved by running flutter run --verbose
