### ISSUE TITLE
`LiveTestWidgetsFlutterBinding` is not handling some `PointerEvent` correctly. 

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#61100]
```Dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Input PointerAddedEvent', (WidgetTester tester) async {
    await tester.pumpWidget(const MaterialApp(home: Text('Test')));
    await tester.pump();
    final TestGesture gesture = await tester.createGesture();
    await gesture.addPointer();
  });
}
```
https://dartpad.dev/902bb29d5ba7f0003593f6ada59cba32
(need to open console on dartpad to see the error message)

This test passes on a host machine, but if run it on a device, this assert will be violated: 

https://github.com/flutter/flutter/blob/f0e396710a8ad6af0942b2bcb805fd97d4f4765d/packages/flutter_test/lib/src/binding.dart#L1436

This is due to different treatment for the first `PointerAddedEvent` as the start of a gesture in `GestureBinding` (https://github.com/flutter/flutter/blob/f0e396710a8ad6af0942b2bcb805fd97d4f4765d/packages/flutter/lib/src/gestures/binding.dart#L174-L216) and in `LiveTestWidgetsFlutterBinding` (https://github.com/flutter/flutter/blob/f0e396710a8ad6af0942b2bcb805fd97d4f4765d/packages/flutter_test/lib/src/binding.dart#L1427-L1472)

Luckily we don't usually generate `PointerAddedEvent` using our tester APIs like `move` or `tap`, but when we want to simulate real world inputs, this event is there. 

-------
solving this issue is part of #60796, https://github.com/flutter/flutter/pull/60796/files#diff-1fc62c212be6fd3a5e10c523ea69cb28R1456

**Comment by CareF** [comment]
@liyuqian @dnfield This is the test case I meant last night.

**Comment by CareF** [comment]
Reopening this because `PointerHoverEvent` and `PointerRemovedEvent` look like possibly having same issue. I don't have a situation/example yet to see when these events are produced in real environment.

**Comment by liyuqian** [comment]
Alternatively, you can open a new issue when you can produce the `PointerHoverEvent ` and `PointerRemovedEvent` in the real environment, and just reference this issue. The title of this issue sounds like it's `PointerAddedEvent` only.
