### ISSUE TITLE
Increase in android_view_scroll_perf__timeline_summary 99th_percentile_frame_build_time_millis --- now mostly red

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61105]
First jump at https://github.com/flutter/flutter/pull/60320, where it was still green. Now red; assigning P3 due to small growth.

![Screen Shot 2020-07-08 at 9 35 15 AM](https://user-images.githubusercontent.com/1435716/86945812-5a740300-c0fe-11ea-8d67-592db7f3c0c3.png)

cc @bparrishMines, who originated the original CL.

I'm not sure if this is engine or framework --- it's in flutter/flutter, so I'm _guessing_ framework. Please reassign as needed.

**Comment by blasten** [comment]
This can be rebaselined

**Comment by goderbauer** [comment]
Rebased as per previous comment.
