### ISSUE TITLE
web_benchmarks_html bench_mouse_region_grid_hover.html.drawFrameDuration.outlierRatio regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61108]
Pretty clear signal at https://github.com/flutter/flutter/pull/59883, so maybe it's a test issue?
![Screen Shot 2020-07-08 at 9 47 28 AM](https://user-images.githubusercontent.com/1435716/86947001-0d912c00-c100-11ea-9a30-79665af04657.png)

**Comment by kf6gpe** [comment]
cc @yjbanov

**Comment by dkwingsmt** [comment]
I don't know if we really care about outlier ratio much. I was about to ask the reason why we even tracked this.

**Comment by HansMuller** [comment]
Remove the P0 label for now. If someone can answer Tong Mu's questions, https://github.com/flutter/flutter/issues/61108#issuecomment-655747260, it may be necessary to restore the P0 label.

CC @ferhatb @liyuqian

**Comment by yjbanov** [comment]
@dkwingsmt is correct. We collect outlierRatio but this metric is not stable enough for tracking. We mostly use it for qualitative analysis. I archived all the outlierRatio metrics I could fine.
