### ISSUE TITLE
A problem occurred configuring root project 'android'

### ISSUE THREAD

**Issue by cmdparkour** [flutter/flutter#61115]
A problem occurred configuring root project 'android'.
[   +1 ms] > Could not resolve all artifacts for configuration ':classpath'.
[   +1 ms]    > Could not resolve com.android.tools.build:gradle:3.5.0.
[   +1 ms]      Required by:
[   +1 ms]          project :
[   +1 ms]       > Could not resolve com.android.tools.build:gradle:3.5.0.
[   +1 ms]          > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[   +2 ms]             > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[   +1 ms]                > Connect to sdk.gdgshanghai.com:8000 [sdk.gdgshanghai.com/103.224.212.222] failed: Connection refused: connect
[   +1 ms]       > Could not resolve com.android.tools.build:gradle:3.5.0.
[   +1 ms]          > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[   +1 ms]             > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[   +5 ms]                > Connect to sdk.gdgshanghai.com:8000 [sdk.gdgshanghai.com/103.224.212.222] failed: Connection refused: connect
[   +2 ms]    > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
[   +1 ms]      Required by:
[        ]          project :
[        ]       > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
[        ]          > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
[   +1 ms]             > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
[   +1 ms]                > Connect to sdk.gdgshanghai.com:8000 [sdk.gdgshanghai.com/103.224.212.222] failed: Connection timed out: connect
[   +1 ms]       > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
[        ]          > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
[        ]             > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
[        ]                > Connect to sdk.gdgshanghai.com:8000 [sdk.gdgshanghai.com/103.224.212.222] failed: Connection refused: connect

**Comment by jonahwilliams** [comment]
This is a network error, and not an issue with flutter.

**Comment by ajeetv300** [comment]
Same Issue, there is no network issue

A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
