### ISSUE TITLE
Flutter app:mergeExtDexDebug Error 

### ISSUE THREAD

**Issue by DankTestAcc** [flutter/flutter#61121]
Someone please help me with this. I dont know if this is an issue or just something wrong with my system.
Any links to similar questions would be much appreciated.

**Steps to Reproduce**
Install Flutter in Windows 10 
Install Flutter SDK along with Dart SDK
Set up VS Code
Run the template app

**Expected results:**
Expected the default starter template to show up.

**Actual results:** 
Got Build Failed with Exception

<details>
  <summary>Logs</summary>

```  (This is what the log shows) > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\Paleolithic_Space\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.50\3d9cd3e1bc7b92e95f43d45be3bfbcf38e36ab87\kotlin-stdlib-common-1.3.50.jar.
         > Cannot parse result path string:  ```

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
No issues found! (ran in 198.8s)
```

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (8 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Paleolithic_Space\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.
[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.
[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Paleolithic_Space\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1
[√] Connected device (1 available)
    • SM A310F • 52033661b864b341 • android-arm • Android 7.0 (API 24)
! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
Hi @DankTestAcc,
Can you check `android/app/build.gradle` file and see what's the `minsdkversion` listed in it ?

**Comment by DankTestAcc** [comment]
@darshankawar 
defaultConfig {
        applicationId "com.example.numinator"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
Any idea?

**Comment by darshankawar** [comment]
Hi @DankTestAcc,
You are probably getting that error because you have `minSdkVersion` set to 16. If you are okay to bump it to 21, then hopefully you should not see the error. Otherwise, if you want to keep it to 16, then change following:

1.  Add `multiDexEnabled true` inside `defaultConfig`
2. Add `implementation 'com.android.support:multidex:1.0.3'` inside `dependencies`. (Note: see the latest version of this implementation and change accordingly).
3. Enable `android.enableJetifier=true` in `project/android/app/gradle.properties` file.

**Comment by DankTestAcc** [comment]
@darshankawar 
Oh God thank you so much, finally fixed it. Thank youu. I bumped minSdkVersion to 21 and then had to downgrade to Jdk 8. Its working as expected now. Again, thank you.
