### ISSUE TITLE
[webview_flutter] Add new entrypoint that uses hybrid composition on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#61133]
This is a feature request to support hybrid composition. The plan is to add a new Dart entrypoint that doesn't change the public API of the webview plugin, but internally uses this new mode.

Once this is done, we will ask folks to try it out, and we will learn from their experiences.

Issues solved by this:
1) https://github.com/flutter/flutter/issues/31243
1) https://github.com/flutter/flutter/issues/19418
1) https://github.com/flutter/flutter/issues/41089
1) https://github.com/flutter/flutter/issues/24585
1) https://github.com/flutter/flutter/issues/50716
1) https://github.com/flutter/flutter/issues/24584
1) https://github.com/flutter/flutter/issues/36478
1) https://github.com/flutter/flutter/issues/52211
1) https://github.com/flutter/flutter/issues/37989
1) https://github.com/flutter/flutter/issues/51254
1) https://github.com/flutter/flutter/issues/23728 (Support API level 19)
1) https://github.com/flutter/flutter/issues/50716
1) https://github.com/flutter/flutter/issues/51915
1) https://github.com/flutter/flutter/issues/61280
1) https://github.com/flutter/flutter/issues/55724
1) https://github.com/flutter/flutter/issues/56513
1) https://github.com/flutter/flutter/issues/56515
1) https://github.com/flutter/flutter/issues/61085
1) https://github.com/flutter/flutter/issues/62205
1) https://github.com/flutter/flutter/issues/62547
1) https://github.com/flutter/flutter/issues/58943
1) https://github.com/flutter/flutter/issues/56361
1) https://github.com/flutter/flutter/issues/42902
1) https://github.com/flutter/flutter/issues/40716
1) https://github.com/flutter/flutter/issues/39880
1) https://github.com/flutter/flutter/issues/37989
1) https://github.com/flutter/flutter/issues/27924

**Comment by ishowfun** [comment]
good news!

**Comment by tft456** [comment]
I hope it works

**Comment by blasten** [comment]
Potentially fixed by hybrid:

- https://github.com/flutter/flutter/issues/51915
- https://github.com/flutter/flutter/issues/50716

**Comment by blasten** [comment]
Potentially fixed by this:

- https://github.com/flutter/flutter/issues/51915
- https://github.com/flutter/flutter/issues/50716

**Comment by aaron-chu** [comment]
May I ask when this fix is going to release to the beta or stable channel? I rely on it for solving #41089. Thanks!

**Comment by blasten** [comment]
@aaron-chu It will be released to 1.20 stable.

**Comment by blasten** [comment]
@tvolkert this fixes pretty much all keyboard and a11y related issues.

**Comment by rahuldange09** [comment]
@fddsocool
https://github.com/flutter/plugins/pull/2883#issuecomment-686318528

How you tested it? Can you explain that how to test this.
I really cannot wait for fix of this issue, I have this issue in production app and that also with card, netbanking payment. I hope this keyboard issues in webview fixes soon.

**Comment by rahuldange09** [comment]
Hello @blasten,
Will it fix all issues related to web input field? On some manufactures phones like Oppo, Vivo which doesn't show input handle and mainly doesn't type anything at all on the web input fields like cvv, password fields. We have an e-commerce app which is used by 30k+ customers daily and in that some users faces this issue when doing **payment transaction** through an app which they are not able to do because of such webview issues on android.
Will this solve all such issues? And I hope it's on the priority and this fix will merge to stable as soon as possible.

Thank you

**Comment by chinmaygarde** [comment]
Per Ray, this should be fixed in 1.22. That is under verification right now.

**Comment by shenlanchenwei** [comment]
> 这是支持混合合成的功能请求。计划是添加一个新的Dart入口点，该入口点不会更改webview插件的公共API，但会在内部使用此新模式。
> 
> 完成此操作后，我们将要求人们尝试一下，我们将从他们的经验中学习。
> 
> 解决的问题：
> 
> 1. [＃19418](https://github.com/flutter/flutter/issues/19418)
> 2. [＃41089](https://github.com/flutter/flutter/issues/41089)
> 3. [＃24585](https://github.com/flutter/flutter/issues/24585)
> 4. [＃50716](https://github.com/flutter/flutter/issues/50716)
> 5. [＃24584](https://github.com/flutter/flutter/issues/24584)
> 6. [＃36478](https://github.com/flutter/flutter/issues/36478)
> 7. [＃52211](https://github.com/flutter/flutter/issues/52211)
> 8. [＃37989](https://github.com/flutter/flutter/issues/37989)
> 9. [＃51254](https://github.com/flutter/flutter/issues/51254)
> 10. [＃23728](https://github.com/flutter/flutter/issues/23728)（支持API级别19）
> 11. [＃50716](https://github.com/flutter/flutter/issues/50716)
> 12. [＃51915](https://github.com/flutter/flutter/issues/51915)
> 13. [＃61280](https://github.com/flutter/flutter/issues/61280)
> 14. [＃55724](https://github.com/flutter/flutter/issues/55724)
> 15. [＃56513](https://github.com/flutter/flutter/issues/56513)
> 16. [＃56515](https://github.com/flutter/flutter/issues/56515)
> 17. [＃61085](https://github.com/flutter/flutter/issues/61085)
> 18. [＃62205](https://github.com/flutter/flutter/issues/62205)
> 19. [＃62547](https://github.com/flutter/flutter/issues/62547)
> 20. [＃58943](https://github.com/flutter/flutter/issues/58943)
> 21. [＃56361](https://github.com/flutter/flutter/issues/56361)
> 22. [＃42902](https://github.com/flutter/flutter/issues/42902)
> 23. [＃40716](https://github.com/flutter/flutter/issues/40716)
> 24. [＃39880](https://github.com/flutter/flutter/issues/39880)
> 25. [＃37989](https://github.com/flutter/flutter/issues/37989)
> 26. [＃27924](https://github.com/flutter/flutter/issues/27924)

When the text box is empty, long press will display paste

**Comment by blasten** [comment]
@pcsosinski any news on the 1.22 release? The plugin PR is waiting on the branch cut, so it can be merged. 
cc @chinmaygarde

**Comment by blasten** [comment]
ETA for 1.22 is 9/28.

**Comment by pcsosinski** [comment]
is the only that has to happen to close this is for 1.22 to be stable and the PR be merged?

**Comment by blasten** [comment]
> is the only that has to happen to close this is for 1.22 to be stable and the PR be merged?

that's correct.

**Comment by bparrishMines** [comment]
Reopening since the PR was reverted: https://github.com/flutter/plugins/pull/3066

**Comment by Sunbreak** [comment]
> Reopening since the PR was reverted: [flutter/plugins#3066](https://github.com/flutter/plugins/pull/3066)

Is there any blocker issue? i.e. https://github.com/flutter/flutter/issues/66764

**Comment by shenlanchenwei** [comment]
any progress?

**Comment by tvolkert** [comment]
Re-application in https://github.com/flutter/plugins/pull/3067

**Comment by chinmaygarde** [comment]
@bparrishMines Can you update the milestone for this issue? The re-land has not landed.

**Comment by bparrishMines** [comment]
@blasten  @chinmaygarde Is Sept. 30 not the correct milestone?

**Comment by yexiaodong** [comment]
how to use choose file (input type file)?

**Comment by Sunbreak** [comment]
> how to use choose file (input type file)?

https://github.com/flutter/flutter/issues/27924

**Comment by yexiaodong** [comment]
> > how to use choose file (input type file)?
> 
> #27924
except #27924. how to uses hybrid composition?(#61133)

**Comment by Sunbreak** [comment]
PLEASE Google before you ask
![Screen Shot 2020-12-31 at 5 47 16 AM](https://user-images.githubusercontent.com/7928961/103382928-d8ecb300-4b2b-11eb-85c8-868cf4c0e0ba.png)
