### ISSUE TITLE
Android SDK file not found: C:\Users\ITSHOP\AppData\Local\Android\Sdk\platforms\android-30\android.jar.

### ISSUE THREAD

**Issue by kokysaad833** [flutter/flutter#61134]
I have tried to download it from android studio, but it didn't complete

C:\Users\ITSHOP>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.1550], locale ar-EG)
[!] Android toolchain - develop for Android devices (Android SDK 30.0.0)
    X Android SDK file not found: C:\Users\ITSHOP\AppData\Local\Android\Sdk\platforms\android-30\android.jar.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by VladyslavBondarenko** [comment]
Hi @kokysaad833 

> but it didn't complete

do you mean you didn't finish downloading or by this you mean that Android SDK still not found after finished downloading?
does `C:\Users\ITSHOP\AppData\Local\Android\Sdk\platforms\android-30\android.jar` exist?
you can set location by `flutter config --android-sdk <path-to-your-android-sdk-path>`

**Comment by kokysaad833** [comment]
Some tools of SDK not installed such as NDK side by side ,it said that no
package found.
The mentioned path is not exist , I did not find it
I have tried this command but nothing changes

**Comment by VladyslavBondarenko** [comment]
@kokysaad833 
could you upgrade to latest flutter version (if you use beta channel, current beta is `1.19.0-4.3.pre`) and provide your `flutter doctor -v`?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by abel432** [comment]
to fix this simply change your sdk location 

flutter config --android-sdk C:\Users\ITSHOPE\AppData\Local\Android\Sdk
