### ISSUE TITLE
camera  Take a picture

### ISSUE THREAD

**Issue by lushangdefeng55** [flutter/flutter#61144]
Taking pictures with the camera in flutter is much lower than the picture pixels taken with the system camera

**Comment by TahaTesser** [comment]
Hi @lushangdefeng55 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample and screenshots to compare `camera` package taken picture with system taken picture 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
