### ISSUE TITLE
[google_sign_in] Can't sign in using debug mode in Chrome

### ISSUE THREAD

**Issue by stefandevo** [flutter/flutter#61155]
If using the `google_sign_in` plugin for web is not working in debug mode in Chrome.
When you run through Chrome and try to sign in you get following message in Chrome:

```
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

A workaround is to start a new Window (on Mac) of Chrome before you start the debug session. After VSCode (or from terminal `flutter run -d chrome --web-hostname localhost --web-port 7357` starts the debug Chrome window, you can then copy the url into the previous opened Chrome Window. Then you can sign-in without the previous message blocking this but you are not in a debugging session (breakpoints etc doesn't work then).

But, the issue is that the plugin writes cookies and to local storage of the browser, but only in the 'non-debugging' Chrome browser. So you never can get past a debugging session in Chrome when you want to rely on the cookies (and thus the browser knowns you already signed in).

As I understand, Chrome is openen in a kind of debugging mode, but then the oAuth of Google Sign in sees this as an insecure session on localhost.

**Comment by yjbanov** [comment]
Have you tried `-d web-server`? We don't try to attach a debugger in this mode.

**Comment by stefandevo** [comment]
> Have you tried `-d web-server`? We don't try to attach a debugger in this mode.

I did, but I could not Chrome to work; Safari did work.

**Comment by rahulraj64** [comment]
I also have same problem. 
It's working with web-server (flutter run -d web-server --web-port=5000).
But not with chrome (flutter run -d chrome --web-port=5000)

**Comment by sbis04** [comment]
I am using the same method for using the `google_sign_in` package for the Flutter web, as stated by @stefandevo. But the problem is that no debug messages are being displayed in the **terminal** or the **IDE console** after running the localhost link from the default Chrome browser.

The only way to see the debug messages is by going in the **Inspect** mode of the Chrome browser and then selecting the **Console** tab.

Is there any solution to this currently?

**Comment by darkwolf91** [comment]
I am having the same issue.

In my case when i run using web-server works fine but there is no hot-restart whatsoever
when I run it with flutter run -d chrome it launches but shows "Browser is not secure" message and prevents me from logging in.

I am using Firebase Auth to log with Google Authentication. This only started after I performed flutter upgrade on an existing project which had no issues authenticating.

**Comment by Levi-Lesches** [comment]
Can confirm I get this issue too. Google already [announced](https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html) that they won't be allowing sketchy browser instances to log in (even if "enable less secure access" is on) so this makes sense. Unfortunately, as mentioned, by opening the tab in an existing window, debugging is lost.

I don't see the issue others are having with the web-server, but for me, using the web server gives me a host of other problems (see #54900)

**Comment by JojoGogo9** [comment]
I have the same issue, and it is a real blocker... This is not ideal, but to get around the lack of logging, you can use

import 'dart:js' as js;

..and then in your code..  

js.context.callMethod("alert", <String>["hello world"]);

-this makes a js pop up which you can use to log things at runtime..

**Comment by purplecandy** [comment]
Any update or a hack or something?
As long as the chrome instance is being launched with `--remote-debugging-port` flag there is no way to sign in.
It could have worked if just the standard web-server was able to connect with the dart debug extension. It fails to detect it as a dart app.

Running regular chrome or edge builds and copying the localhost URL the extension detects the dart observatory but then the Console goes into a bad-state maybe it's because now there are two processes trying to communicate with the observatory? I have no idea actually.

This is actually a severe issue Flutter has a strong point of having fast hot reload and if that doesn't work, especially with google services that have first-class support its kinda bummer.

```
Error from backend:
Error: Bad state: Not connected to an application.
Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure>  (package:dwds/src/handlers/dev_handler.dart:272:13)
#1      _rootRunUnary  (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
#3      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
#4      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)
#5      _DelayedData.perform  (dart:async/stream_impl.dart:611:14)
#6      _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:730:11)
#7      _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:687:7)
#8      _rootRun  (dart:async/zone.dart:1182:47)
#9      _CustomZone.run  (dart:async/zone.dart:1093:19)

```

**Comment by ditman** [comment]
I have just verified I can `flutter run -d chrome --web-port 7357`, then sign in on the example app of the `google_sign_in` plugin.

Can people please share what's the complete `flutter run` command that they're using?

Also, have you added `http://localhost:7357` as an "Authorized JavaScript origin" to the "OAuth 2.0 Client ID" you're using in `web/index.html`?

**Comment by stefandevo** [comment]
@ditman the issue is that Chrome OSX is not allowing you to login with Google Account.
When you run the app, you can hit the sign in button, you get the popup to enter your email account and upon next it gives you
![image](https://user-images.githubusercontent.com/1656051/91758161-d440de00-ebcf-11ea-8bbe-9a53cf4c6699.png)
So basically it is not possible to run your app in debug mode. When you copy/paste in a browser window you start yourself you can get through the login but you lose the debug feature.

**Comment by ditman** [comment]
Aha, Mac OS X, let me give that a shot. I was testing in Linux (and it does work in Linux).

**Comment by ditman** [comment]
@stefandevo it works on my (silly) testing app. My OAuth app is not verified, I'm not sure if that makes a difference (or if that's a process you have to go through).

<img width="1144" alt="Screen Shot 2020-08-31 at 12 33 56 PM" src="https://user-images.githubusercontent.com/1255594/91759347-5e645480-eb86-11ea-8cbb-446f56166bca.png">

**Comment by stefandevo** [comment]
My app is not verified either. I tested different scenarios and just like other persons above the issue seems to be Chrome itself that is not allowing the debug attachment. The app is running fine when the Chrome window is not started from the flutter command but you loose debugging.

**Comment by ditman** [comment]
I've reached out to the internal team that owns this feature, to see if there's any workaround at the framework level, and/or to know why my test account is not affected but your user accounts are. This is very odd.

@stefandevo do you have flutter devtools open when you attempt to sign in, or do you just run `flutter run -d chrome` and attempt to sign in into your app?

**Comment by stefandevo** [comment]
I tried it from vscode, android studio and from terminal as you mentioned. All the same issue.

**Comment by ditman** [comment]
@stefandevo did you have flutter devtools open, and connected to your app when you were getting the "deny" window, or were you just launching the app (no devtools) and attempting to sign in?

**Comment by stefandevo** [comment]
No just launching without dev tools open.

**Comment by ditman** [comment]
Thanks for all the answers! I've pinged the owners of this feature to see what can be done at the framework level to prevent this from happening!

**Comment by purplecandy** [comment]
Even electron apps faced same issue. Google will dent sign in request because the same error message. There the solution was a simple modification of User Agent before making the request, I tried to do the same from dev tools and it didn't work. I believe it's because we are specifically launching chrome instances with remote-debugging.

**Comment by ditman** [comment]
@purplecandy Electron apps are very different (even though the error surfaced in the same way). In this case we're using the stock Chrome, and not anything "embedded" anywhere. Spoofing the User Agent is not an option. In my email I mentioned this issue, and the remote debugging abilities; we'll see what can be done!

**Comment by ditman** [comment]
The owners of the feature have confirmed that the test account that I'm using may not have this feature enforced, and are asking me for some more details to help debug this issue. 

Could you please send me (dit at google dot com) an email with the following info:

* The email address that was blocked
* An approximate date + time of when you were blocked

I'll forward this info to the owners of feature so they can look at their logs and help us figure out why the requests were denied.

Thanks!

**Comment by ditman** [comment]
// ping @stefandevo @purplecandy @JojoGogo9 @Levi-Lesches, if you send me some extra info (see comment above) I can forward this to the owners and figure out exactly why the security issue is triggering, and maybe how to circumvent it.

Thanks!

**Comment by stefandevo** [comment]
@ditman hi I really don't think this is account related. It is the browser instance started through debugging that is marked as unsafe by the google sigin. I tried severall different accounts with same result. It starts by the fact that I don't get my list of saved accounts. I directly have to enter an email account. When I use it apart from the debugger session I can choose from my list.

**Comment by ditman** [comment]
@stefandevo I'm requesting the information that the owners of the feature are asking for so we can debug internally. It is definitely account related. My test account doesn't trigger this issue (never), for example.

**Comment by stefandevo** [comment]
@ditman Ok, cool ... I just used my account connected to pub.dev -> stefan.de.vogelaere@gmail.com just now 22:13 Belgium time.

**Comment by ditman** [comment]
@stefandevo I've forwarded the info to the team, thanks for your email! I've deleted your message to hopefully minimize the amount of spam you receive in that account :)

Thanks again!

**Comment by purplecandy** [comment]
@ditman I have forwarded my details to your email

**Comment by ditman** [comment]
@stefandevo are you using webdriver to automate sign-in?

**Comment by stefandevo** [comment]
> @stefandevo are you using webdriver to automate sign-in?

Not sure. I do use 1Password but am typing email and password manually (or copy paste). However in the meantime I tried with other google accounts and they do work within the same instance.

**Comment by ditman** [comment]
@stefandevo You'd be using webdriver if you were writing a test to automate sign-in or similar. I'll let them know about 1Password. Thanks!

**Comment by MattyBoy4444** [comment]
I am also having this issue.  I turned off MFA and turned on Less Secure apps and I still get the same message.

**Comment by Levi-Lesches** [comment]
I'm making an app for an organization. When using my personal account for testing (without setting the app to internal or anything), I was getting this error. However, once I tried signing in using my organization account, it worked. 

I guess the takeaway here is that even though there are settings for personal accounts to disable protection, Google will still take action against "shady sign-ins". However, there seems to be some sort of setting that a G Suite manager can disable. It also helps if the Google Cloud project is hosted under the organization, obviously.

**Comment by MattyBoy4444** [comment]
FYI, just to get past this issue so I can DEBUG, added GitHub Sign-In provider.  Voilà

I tried multiple logins I have and none worked.  I do not have a G-Suite login to try.

**Comment by ditman** [comment]
The protection is per-account, I've reached out to the team that owns this internally, and they've provided me with credentials that should fail every time so I can let them know when I attempted to log-in so they can check the logs. We'll figure this out :)

**Comment by jimmyff** [comment]
Just wanted to add this isn't Mac OSX specific. I'm seeing exactly the same behaviour on Windows 10.

**Comment by jimmyff** [comment]
@MattyBoy4444 
> FYI, just to get past this issue so I can DEBUG, added GitHub Sign-In provider. Voilà

What package are you using for github sign in on web? I just implemented `package:github_sign_in` but now I'm getting a flutter_webview_plugin error then I realised that pub says it doesn't support web.

(Sorry to be off topic but this seems like a viable workaround until google sign in on web is resolved.)

**Comment by MattyBoy4444** [comment]
> @MattyBoy4444
> 
> > FYI, just to get past this issue so I can DEBUG, added GitHub Sign-In provider. Voilà
> 
> What package are you using for github sign in on web? I just implemented `package:github_sign_in` but now I'm getting a flutter_webview_plugin error then I realised that pub says it doesn't support web.
> 
> (Sorry to be off topic but this seems like a viable workaround until google sign in on web is resolved.)

There is a GithubAuthProvider in package github_auth.  I am using that with signInWithPopup.

**Comment by ditman** [comment]
This is why the browser gets detected as "webdriver" when flutter starts in debug mode:

[`navigator.webdriver`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver)

I've asked for more information about next steps here.

**Comment by TahaTesser** [comment]
I can reproduce it, you cannot sign in to the chrome window that launches by Flutter
The only way to test this is using whitelisted localhost and execute `flutter run -d web-server --web-hostname localhost --web-port 7357 -v` and then launch the app in a normal chrome window, of course, can't debug this way


<details>
<summary>code sample</summary>

```dart
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:convert' show json;

import "package:http/http.dart" as http;
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount _currentUser;
  String _contactText;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        _handleGetContact();
      }
    });
    _googleSignIn.signInSilently();
  }

  Future<void> _handleGetContact() async {
    setState(() {
      _contactText = "Loading contact info...";
    });
    final http.Response response = await http.get(
      'https://people.googleapis.com/v1/people/me/connections'
      '?requestMask.includeField=person.names',
      headers: await _currentUser.authHeaders,
    );
    if (response.statusCode != 200) {
      setState(() {
        _contactText = "People API gave a ${response.statusCode} "
            "response. Check logs for details.";
      });
      print('People API ${response.statusCode} response: ${response.body}');
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {
        _contactText = "I see you know $namedContact!";
      } else {
        _contactText = "No contacts to display.";
      }
    });
  }

  String _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic> connections = data['connections'];
    final Map<String, dynamic> contact = connections?.firstWhere(
      (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic> name = contact['names'].firstWhere(
        (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    if (_currentUser != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            leading: GoogleUserCircleAvatar(
              identity: _currentUser,
            ),
            title: Text(_currentUser.displayName ?? ''),
            subtitle: Text(_currentUser.email ?? ''),
          ),
          const Text("Signed in successfully."),
          Text(_contactText ?? ''),
          RaisedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          RaisedButton(
            child: const Text('REFRESH'),
            onPressed: _handleGetContact,
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          RaisedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }
}

```

</details>
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.72, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.72 at /Users/tahatesser/Code/flutter_master
    • Framework revision bb3e64dae6 (9 hours ago), 2021-02-19 00:36:03 -0500
    • Engine revision c217d9d06e
    • Dart version 2.13.0 (build 2.13.0-46.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>

**Comment by Levi-Lesches** [comment]
@ditman anything from the team?

**Comment by grouma** [comment]
@ditman did you ever experiment with the [Dart Debug Extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm?hl=en)? Do the permissions required by the extension prevent sign in?

**Comment by ditman** [comment]
> @ditman did you ever experiment with the Dart Debug Extension? Do the permissions required by the extension prevent sign in?

@grouma no, I don't think I ended up doing it, I need to revisit this, but won't have time until the null-safety migration of the plugins ecosystem is complete :/

**Comment by jbryanh** [comment]
So there is no workaround?  I'd like to test Firebase Analytics, and following this [https://firebase.google.com/docs/analytics/debugview#web](https://firebase.google.com/docs/analytics/debugview#web) got me here.  So it's not possible to test Firebase Analytics with Flutter Web in debug mode?  Probably why it's not documented in FlutterFire yet?  Works, just can't debug test?

**Comment by Levi-Lesches** [comment]
There is a workaround -- two actually: 
1. Copy and paste the `localhost` URL into a Chrome tab you opened manually. This means after you press hot reload, you also need to manually refresh the page. 
2. Run in release mode: `flutter run --release web`

**Comment by darkwolf91** [comment]
Actually in my case it is back to normal...The only thing i did was reboot my VM recently

I suspect might be a specific Chrome version. What version are you using?
________________________________

**Comment by Levi-Lesches** [comment]
Well I haven't actually tested this in a while, so I don't know if that's too helpful. 

The problem isn't necessarily a specific Chrome version, it's Google's [safety feature](https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html). Although I've noticed this protection isn't implemented on my GSuite account, so add that to the list of workarounds. 

@ditman might have some word on an official plan/solution.

**Comment by grouma** [comment]
cc @jonahwilliams,  do we still support `-d web-server`? Should we support a DDC based mode that doesn't spawn Chrome? Maybe a `--no-debug` flag of sorts?

**Comment by jonahwilliams** [comment]
We do still support -d web-server, but it is hidden by default. If you specify it as a device ID, then it will run

**Comment by huycozy** [comment]
I can not reproduce this issue on latest `stable` and `master` channel. I can login successfully in debug mode without error.

- Run command:
> flutter run -d chrome --web-hostname localhost --web-port 7357

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/165935232-6685c89a-a826-4563-bbd4-6e8610d6c39c.mp4

</details>

<details>
<summary>Sample code (null-safety supported)</summary>

```dart
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:convert' show json;

import "package:http/http.dart" as http;
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount? _currentUser;
  late String _contactText;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        _handleGetContact();
      }
    });
    _googleSignIn.signInSilently();
  }

  Future<void> _handleGetContact() async {
    setState(() {
      _contactText = "Loading contact info...";
    });
    final http.Response response = await http.get(
    Uri.parse('https://people.googleapis.com/v1/people/me/connections'
        '?requestMask.includeField=person.names'),
      headers: await _currentUser?.authHeaders,
    );
    if (response.statusCode != 200) {
      setState(() {
        _contactText = "People API gave a ${response.statusCode} "
            "response. Check logs for details.";
      });
      print('People API ${response.statusCode} response: ${response.body}');
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String? namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {
        _contactText = "I see you know $namedContact!";
      } else {
        _contactText = "No contacts to display.";
      }
    });
  }

  String? _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic> connections = data['connections'];
    final Map<String, dynamic> contact = connections.firstWhere(
          (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic> name = contact['names'].firstWhere(
            (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    if (_currentUser != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            leading: GoogleUserCircleAvatar(
              identity: _currentUser!,
            ),
            title: Text(_currentUser!.displayName ?? ''),
            subtitle: Text(_currentUser!.email),
          ),
          const Text("Signed in successfully."),
          Text(_contactText),
          RaisedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          RaisedButton(
            child: const Text('REFRESH'),
            onPressed: _handleGetContact,
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          RaisedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.10.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.13.0-0.0.pre.808, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.13.0-0.0.pre.808 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2eed8cbf93 (4 hours ago), 2022-04-28 22:29:06 -0400
    • Engine revision dfdfe0b3b0
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by ditman** [comment]
@huycozy before marking this as fixed, please note that this limitation was per-account, as I discussed [here](https://github.com/flutter/flutter/issues/61155#issuecomment-700905111). Old gmail accounts may NOT have this protection enabled. Not sure what triggers that an account gets the configuration flipped.

**Comment by huycozy** [comment]
> @huycozy before marking this as fixed, please note that this limitation was per-account, as I discussed [here](https://github.com/flutter/flutter/issues/61155#issuecomment-700905111). Old gmail accounts may NOT have this protection enabled. Not sure what triggers that an account gets the configuration flipped.

@ditman: thank you. Based on your comment, I will keep this issue open until further investigation.

**Comment by ditman** [comment]
There's major changes to google sign in coming: https://github.com/flutter/flutter/issues/88084

**Comment by danagbemava-nc** [comment]
Hi @ditman, given that #88084 has been completed, is there anything else that remains to be done on this issue?

**Comment by ditman** [comment]
@danagbemava-nc thanks for bringing this up; I don't think this has anything actionable on our end; let's close this.

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/61155#issuecomment-2078275777
