### ISSUE TITLE
High CPU usage when idle during development

### ISSUE THREAD

**Issue by purezen** [flutter/flutter#61153]
I installed Flutter as per official documentation on my Windows 10 PC and I am able to generate the application.

However, the CPU usage even when the IDE ( Visual Studio Code ) is idle is very high.

![flutter cpu issue](https://user-images.githubusercontent.com/3036093/87027103-49102100-c1fa-11ea-9342-a50932288491.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @purezen 
by idle IDE do you mean that app is not running on your device? do you have emulator launched in the time?
if you are expecting lower CPU with running app could you check is it the same when you are running native android app?

**Comment by purezen** [comment]
> idle IDE do you mean that app is not running on your device?

Yes. Not compiling an app and not running one

> do you have emulator launched in the time?

No. Not even created a virtual device yet

I digged further and I found that the CPU utilization comes back to normal when the flutter and dart plugins are disabled.

**Comment by VladyslavBondarenko** [comment]
@purezen 
could you provide your `flutter doctor -v` and screenshots of Task Manager processes with expanded Visual Studio Code and (Android Studio if you using it) with enabled and disabled flutter and dart plugins?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
