### ISSUE TITLE
seekbar with preview, like you-tube

### ISSUE THREAD

**Issue by gowthamkrishnabj** [flutter/flutter#61159]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fandroidexample365.com%2Fcontent%2Fimages%2F2017%2F10%2FPreviewSeekBar.gif&imgrefurl=https%3A%2F%2Fandroidexample365.com%2Fa-seekbar-suited-for-showing-a-preview-of-something%2F&tbnid=np0f1bOFGkophM&vet=12ahUKEwjt5-jfhsDqAhWIkksFHSJUAl0QMygAegUIARCZAQ..i&docid=ph9rqnj48sVGiM&w=498&h=286&q=preview%20seekbar&ved=2ahUKEwjt5-jfhsDqAhWIkksFHSJUAl0QMygAegUIARCZAQ

**Comment by VladyslavBondarenko** [comment]
Hi @gowthamkrishnabj 
follow up on https://github.com/flutter/flutter/issues/33338,
closing current issue as duplicate
