### ISSUE TITLE
InsetPadding not working correctly in AlertDialog / Dialog

### ISSUE THREAD

**Issue by JagArt** [flutter/flutter#61154]
## Steps to Reproduce

The problem is that the indentation changes vertically, but not horizontally

1. I create a new application
2. I create a method
```
 _showDialog() {
    showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          insetPadding: EdgeInsets.all(0.0),
          content: Center(child: Text('asd')),
        );
      },
    );
  }

.....

floatingActionButton: FloatingActionButton(
        onPressed: _showDialog,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
```
3. I launch the application

**Expected results:** 
![Screenshot from 2020-07-09 12-28-44_2](https://user-images.githubusercontent.com/13090915/87025990-c4b2a380-c1e3-11ea-8a2d-e1cd55c6aeac.png)

**Actual results:** 
![Screenshot from 2020-07-09 12-28-44](https://user-images.githubusercontent.com/13090915/87025749-756c7300-c1e3-11ea-9e24-09ad784cd76c.png)

`flutter analyze` : 

Analyzing flutter_testapp...                                            
No issues found! (ran in 1.5s)

`flutter doctor -v`:

[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/mylaptop/android/flutter
    • Framework revision 8af6b2f038 (9 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/aloteq001/android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/aloteq001/android/sdk
    • Java binary at: /home/aloteq001/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/aloteq001/dev/android-studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
Reproduces with current master `1.20.0-3.0.pre.192`.
Tried with Android, iOS and web - only vertical padding is applied.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.192, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.192 at /Users/nevercode/dev/flutter
    • Framework revision a9ea825abf (7 hours ago), 2020-07-08 21:26:03 -0700
    • Engine revision 0ec6f6c3f2
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 06cb010247)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 9F9AFD9B-7F22-468E-8096-B47E993E0619 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```
</details>

**Comment by mkw8263** [comment]
@VladyslavBondarenko 
Please check the PR.

**Comment by BetaPundit** [comment]
Just wrap the child of AlertDialog() inside a **SizedBox()/Container()** with **width: MediaQuery.of(context).size.width**.
```
_showDialog() {
    showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          insetPadding: EdgeInsets.all(0.0),
          content: Center(
            child: SizedBox(
              width: MediaQuery.of(context).size.width,
              child: Text('asd')),
            ) ;
        );
      },
    );
  }
```

Reason:
The AlertDialog() is implemented using a ConstrainedBox() which depends upon its child to provide width. If the width of the child is less than 280, then the AlertDialog() sets its width to 280 as 280 is the minWidth set in the ConstrainedBox(). (You can check out dialog.dart file for more info)

Thus, you need a widget inside this ConstrainedBox() which is greater than or equal to the width of your screen if you want the **insetPadding** property to work properly.

**Comment by maheshmnj** [comment]
Hi @JagArt, I verified the issue on the latest master channel and I see the dialog is full screen covering the edges as expected.

<img src="https://user-images.githubusercontent.com/31410839/206630550-238b121e-a676-48e0-ae24-797ff4ae6881.png" width ="300"> 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: GoogleFonts.darkerGrotesque().fontFamily,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'This have FontFamily'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key,required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  _showDialog() {
    showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          insetPadding: const EdgeInsets.all(0.0),
          content: Center(
            child: SizedBox(
              width: MediaQuery.of(context).size.width,
              child: Text('asd')),
            )
        );
      },
    );
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showDialog,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details> 

Closing as fixed, Incase you still encounter the issue, Please feel free to write in the comments and we will reopen it.
