### ISSUE TITLE
Motion events are not getting dispatched to the virtual display

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#61169]
To repro this issue, use `flutter/flutter` ToT and run the Webview example app on Android. 

It's not clear why the `android_view` e2e test didn't catch this issue.

cc @iskakaushik

**Comment by cuiffo** [comment]
This seems to have come up again -- just using a barebones flutter app with just a WebView.

**Comment by pcsosinski** [comment]
do you have more details @cuiffo?  logs, version, etc

**Comment by blasten** [comment]
fwiw, this hasn't landed on `flutter/flutter` master yet.
