### ISSUE TITLE
some error in using TextFiled(),maxLength are not working well

### ISSUE THREAD

**Issue by SakurasDuck** [flutter/flutter#61162]
**screenshot**

![gifhome_590x1280_17s (1)](https://user-images.githubusercontent.com/40283698/87039575-e9c60700-c221-11ea-9214-c7641619a2f1.gif)

**this is my code:**

<details>
<pre>
<code>
class _MyHomePageState extends State<MyHomePage> {
  String valueStr;

  String _changeValue;
  String _textFiledChangeValue;

  GlobalKey<FormState> _formKey;

  void _incrementCounter() {
    final FormState _form = _formKey.currentState;
    _form.save();
  }

  @override
  void initState() {
    super.initState();
    _formKey = GlobalKey<FormState>();
    init();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Form(
        key: _formKey,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('TextFormField'),
              TextFormField(
                maxLength: 4,
                onSaved: (value) {
                  setState(() {
                    valueStr = value;
                  });
                },
                onChanged: (value) {
                  setState(() {
                    _changeValue = value;
                  });
                },
              ),
              Text(
                'onChange:${_changeValue ?? ''}------onSave:${valueStr ?? ''}',
                style: Theme.of(context).textTheme.headline4,
              ),
              const Text('TextField'),
              TextField(
                maxLength: 4,
                onChanged: (value) {
                  setState(() {
                    _textFiledChangeValue = value;
                  });
                },
              ),
              Text(
                'onChange:${_textFiledChangeValue ?? ''}',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
</code>
</pre>
</details>

**device :**
`[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)
    • Flutter version 1.17.5 at D:\Tools\Android\flutter
    • Framework revision 8af6b2f038 (9 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

    • VOG AL00 • MQS0219A17009076 • android-arm64 • Android 10 (API 29)

`

It's been bothering me for a long time,I need some help,thinks

**Comment by VladyslavBondarenko** [comment]
Hi @SakurasDuck 
it's already fixed, but the fix is not yet in stable. Consider to use current beta `1.19.0-4.3.pre` or any later version.
Closing
