### ISSUE TITLE
initState gets called on all routed widgets

### ISSUE THREAD

**Issue by eldarj** [flutter/flutter#61161]
I'm having an issue with routed widgets and all widgets' initState methods.
Is this a bug or I just assumed routed widgets would be initialized in a 'more lazy' fashion?

In my main.dart I return MaterialApp with some named routes e.g.
```
initialRoute: '/',
routes: {
          '/': (context) => LandingActivity(),
          '/profile': (context) => ProfileActivity(),
          '/shop': (context) => ShopActivity(),
        }
```

Each one of these are classes extending stateful widgets, with respective states overriding **initState()**
To sum up, this is what happens
- LandingActivity gets loaded as the initialRoute, initState gets executed and widget gets rendered on screen
- ProfileActivity's initState gets executed even if not navigated to (on application load)
- ShopActivity's initState gets executed even if not navigated to (on application load)

What I'd expect is that, LandingActivity would get laoded, rendered and it's initState would be called, but ProfileActivity'sand ShopActivity's initState methods wouldn't - I assumed these would be called when you initialize/render them ie. navigate to one of these.

Isn't this unintuitive, as well as careless about performance? Initializing all routed widgets' states doesn't sound like something sensible. If I'm not missing something and this works like expected, how would one avoid this?

**Comment by VladyslavBondarenko** [comment]
Hi @eldarj 
I tried with this code sample

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    initialRoute: '/',
    routes: {
      '/': (context) => FirstScreen(),
      '/second': (context) => SecondScreen(),
      '/third': (context) => ThirdScreen(),
    },
  ));
}

class FirstScreen extends StatefulWidget {
  @override
  _FirstScreenState createState() => _FirstScreenState();
}

class _FirstScreenState extends State<FirstScreen> {

  @override
  void initState() {
    print('initState FirstScreen');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print('build FirstScreen');
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Column(
        children: [
          RaisedButton(
            child: Text('Go to SecondScreen'),
            onPressed: () {
              Navigator.pushNamed(context, '/second');
            },
          ),
          RaisedButton(
            child: Text('Go to ThirdScreen'),
            onPressed: () {
              Navigator.pushNamed(context, '/third');
            },
          ),
        ],
      ),
    );
  }
}


class SecondScreen extends StatefulWidget {
  @override
  _SecondScreenState createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  @override
  void initState() {
    print('initState SecondScreen');
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    print('build SecondScreen');
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}

class ThirdScreen extends StatefulWidget {
  @override
  _ThirdScreenState createState() => _ThirdScreenState();
}

class _ThirdScreenState extends State<ThirdScreen> {
  @override
  void initState() {
    print('initState ThirdScreen');
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    print('build ThirdScreen');
    return Scaffold(
      appBar: AppBar(
        title: Text("Third Screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

With current stable `1.17.5` and master `1.20.0-3.0.pre.192` I can see only

```
I/flutter (30860): initState FirstScreen
I/flutter (30860): build FirstScreen
```

Other routes are initialised and built on opening.

Could you provide your `flutter doctor -v` and complete minimal reproducible code sample if your case is different?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
