### ISSUE TITLE
Can you please add plugin to run flutter in raspberry pi

### ISSUE THREAD

**Issue by don-k-jacob** [flutter/flutter#61192]
## Use case
It can be used in IOT devices and many other applications 

and current blog https://medium.com/flutter/flutter-on-raspberry-pi-mostly-from-scratch-2824c5e7dcb1

is little bit tough to understand and implement 

## Proposal

Add a plugin for it so that we could build many devices with flutter ui.

**Comment by darshankawar** [comment]
Hi @don-k-jacob,
Have you looked at [this](https://github.com/ardera/flutter-pi) plugin ? It looks like a light-weight Flutter Engine Embedder for Raspberry Pi.
If that doesn't suit your requirement, please elaborate on what exactly are you looking for in the plugin.
Also please note that, referring to the above plugin is not an endorsement of that plugin, but just to know if that helps to solve what you are looking for.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
