### ISSUE TITLE
Vertical Stepper should have scrollController field

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#61207]
## Use case

For other components that are intended to wrap `Scrollable` widgets, like [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html), it's necessary to specify the `scrollController`.

I'm currently using this to specify a `scrollController`, however, it adds an extra, otherwise unnecessary `SingleChildScrollView`:

```dart
             SingleChildScrollView(
                controller: scrollController,
                child: Stepper(
                  physics: ClampingScrollPhysics(),
                  ...
                ),
              ),
```

## Proposal

Ideally, it'd be nice to simply use this instead:

```dart
             Stepper(
                scrollController: scrollController,
                ...
             ),
```

**Comment by SwaroopSambhayya** [comment]
Hi @darshankawar can i contribute to this?

**Comment by darshankawar** [comment]
@SwaroopSambhayya Sure. You may checkout contributing guidelines https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
