### ISSUE TITLE
package:flutter/src/painting/text_style.dart': Failed assertion: line 1254 pos 14: 'decorationDescription.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by umakanth-pendyala** [flutter/flutter#61206]
```
════════ Exception caught by Flutter framework ═════════════════════════════════
'package:flutter/src/painting/text_style.dart': Failed assertion: line 1254 pos 14: 'decorationDescription.isNotEmpty': is not true.
════════════════════════════════════════════════════════════════════════════════
```

I am getting the following error how do I solve this

**Comment by TahaTesser** [comment]
Hi @umakanth-pendyala 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by umakanth-pendyala** [comment]
I'm sorry I didn't inform this, the issue is solved. I messed with the text decoration inside the app. Yeah but now it's all good.Thank you

**Comment by TahaTesser** [comment]
Hi @umakanth-pendyala 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by AleksandarSavic95** [comment]
If anyone still gets this issue, make sure you are setting at least one of these three: `decoration`, `decorationColor` or `decorationStyle` **if you are setting `decorationThickness`**.
DebugFillProperties of `TextStyle` checks this:
`if (decoration != null || decorationColor != null || decorationStyle != null || decorationThickness != null) {`
and then assumes that some of the mentioned three properties are not `null` ands them to `decorationDescription`.
Later on, an assertion is made that `decorationDescription` is not empty, but it will be empty if you only set `decorationThickness` (not any of the remaining three).
