### ISSUE TITLE
add keywords - for search engines

### ISSUE THREAD

**Issue by GauravPatni** [flutter/flutter#61210]
Dear All,

I am planning for Flutter Website for production. 
For that I wanted to know is there any way to **add keywords** or equivalent so **to help search engines** find the website efficiently.

Thanks,
Gaurav

**Comment by iapicca** [comment]
Hi @GauravPatni 
I see there's an open [issue](https://github.com/flutter/flutter/issues/46789) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
