### ISSUE TITLE
Different forward and reverse page route transition durations

### ISSUE THREAD

**Issue by exavolt** [flutter/flutter#61222]
## Use case

Custom page route transitions with different forward and reverse transition durations.

## Proposal

Allow specifying `reverseTransitionDuration` in `PageRouteBuilder<T>`. `TransitionRoute<T>` is already supporting it.

**Comment by goderbauer** [comment]
Feel free to send a PR to wire that up.

**Comment by arafaysaleem** [comment]
@goderbauer i have a PR ready to merge

**Comment by goderbauer** [comment]
Can you link to it?

**Comment by arafaysaleem** [comment]
I believe this is what you meant. It's a link to the commit on my fork

https://github.com/flutter/flutter/commit/9d22287813354cd704dbd8d859a2d1caf2e4f804

**Comment by arafaysaleem** [comment]
I believe this is what you were referring to. It's a link to the commit on my fork.

https://github.com/flutter/flutter/commit/3fd6f8e7e1369aac46b82a87100fd82223a610ef
