### ISSUE TITLE
97% CPU consumption by dart.exe

### ISSUE THREAD

**Issue by fxqy** [flutter/flutter#61224]
I use ‘ git clone -b dev https://github.com/flutter/flutter.git ’ install flutter
```
D:\Dev\flutter\flutter>flutter doctor
Building flutter tool...
Running pub upgrade...

```
![1111](https://user-images.githubusercontent.com/42601163/87143979-97e0b800-c2d9-11ea-9e0a-0789b27172f9.jpg)

**Comment by fxqy** [comment]
I can't go any further than that., the CPU is over.

![222](https://user-images.githubusercontent.com/42601163/87145797-7c2ae100-c2dc-11ea-87a8-ee6d2557a21c.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @fxqy 
could you attach screenshot of your 'Performance' tab of Task Manager?

**Comment by fxqy** [comment]
Why dart.exe takes up so much cpu time


![333](https://user-images.githubusercontent.com/42601163/87157703-362c4800-c2f1-11ea-8c04-7d3ecd57604c.jpg)
![444](https://user-images.githubusercontent.com/42601163/87157721-3af0fc00-c2f1-11ea-990d-a400aa97351c.jpg)

**Comment by VladyslavBondarenko** [comment]
@fxqy could you check if you are experiencing this with stable or master branch?

**Comment by fxqy** [comment]
Still the same, I'm a dev branch now, and I've tried the stable branch, and there's the same problem.

![20200710221456108](https://user-images.githubusercontent.com/42601163/87164029-cc18a080-c2fa-11ea-9b86-0b8e0d520910.jpg)

**Comment by zanderso** [comment]
I'm not able to reproduce this on master or dev. pub version solving does use a lot of CPU and takes many seconds, but it finishes. @fxqy Could you try deleting your pub cache (`C:\Users\...\AppData\Roaming\Pub`).

@jonahwilliams is there any way to get pub to give its verbose logs?

**Comment by jonahwilliams** [comment]
Nothing exposed in the upgrade script, though we could add an option for verbosity. I'd like to avoid parsing more command line options in the scripts if possible

**Comment by fxqy** [comment]
This morning I got the stable branch and emptied the 'C:\Users\Dong\AppData\Local\Pub\Cache'.
```
Dong@DESKTOP-JHQSG53 MINGW64 /d/Dev/flutter
$ git clone -b stable https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 247914 (delta 14), reused 3 (delta 2), pack-reused 247862
Receiving objects: 100% (247914/247914), 105.26 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (190414/190414), done.
Checking out files: 100% (4658/4658), done.

Dong@DESKTOP-JHQSG53 MINGW64 /d/Dev/flutter
$

```
```
D:\Dev\flutter\flutter>flutter doctor
Checking Dart SDK version...
'PowerShell.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: Unable to update Dart SDK. Retrying...

等待 0 秒，按 CTRL+C 退出 ...
Checking Dart SDK version...
'PowerShell.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: Unable to update Dart SDK. Retrying...

等待 0 秒，按 CTRL+C 退出 ...
Checking Dart SDK version...
'PowerShell.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: Unable to update Dart SDK. Retrying...

等待 3 秒，按 CTRL+C 退出 ...
终止批处理操作吗(Y/N)? y

D:\Dev\flutter\flutter>
```
There was a error with PowerShell, and I modified line 104 of the ‘flutter/bin/flutter.bat’ file to change the 'PowerShell' to 'pwsh'
Still unsuccessful, did I use ramdisk to cache temporary files to cause the problem? The cached ‘pub_*’ folders in ramdisk are empty!

![20200711111855240](https://user-images.githubusercontent.com/42601163/87215493-8fd05900-c369-11ea-9bc7-4bed79bd6ded.jpg)

**Comment by fxqy** [comment]
I restored the temporary file directory to the default settings and cleared the usercache and flutter, and it worked.
Thank you for helping me find the problem.
![aaa](https://user-images.githubusercontent.com/42601163/87215927-85b05980-c36d-11ea-9432-08e4571f2de9.jpg)
![bbb](https://user-images.githubusercontent.com/42601163/87215938-8cd76780-c36d-11ea-929b-7201afda0fc1.jpg)
