### ISSUE TITLE
`flutter format` doesn't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#61225]
`flutter format` has seized to work; it just prints a message suggesting `dart format`. 

## Steps to Reproduce

From current beta-channel:

```
$ flutter format
"flutter format" is deprecated and will be removed in a future release, use "dart format" instead.
Format Dart source code.

Usage: dart format [arguments]
-h, --help                        Print this usage information.
-n, --[no-]dry-run                Show which files would be modified but make no changes.
    --[no-]set-exit-if-changed    Return exit code 1 if there are any formatting changes.
-m, --[no-]machine                Produce machine-readable JSON output.
-l, --line-length                 Wrap lines longer than this length. Defaults to 80 characters.
                                  (defaults to "80")

Run "dart help" to see global options.
$
```

**Comment by mit-mit** [comment]
Looks like `flutter format .` still works.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/pull/57829.
@jonahwilliams for discussion.

**Comment by jmagman** [comment]
@mit-mit is using `dart format` instead causing an issue, or was this just an unexpected deprecation message?

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/61760

**Comment by mit-mit** [comment]
I was confused about the deprecation warning, and missed that I was calling the tool incorrectly.

**Comment by jmagman** [comment]
Gotcha.  The deprecation warning was removed with #58817 and #61760 is using `dartfmt`.
