### ISSUE TITLE
It is possible to add information to coverage using test drive?

### ISSUE THREAD

**Issue by nicolalandro** [flutter/flutter#61236]
It is possible to have an append of coverage by test drive? With ```flutter test --coverage``` we can generate a test coverage value.
It is possible to do ```flutter drive --coverage``` and append the results to other to have a more significat coverage level?

**Comment by TahaTesser** [comment]
Hi @nicolalandro 
Please check this https://stackoverflow.com/a/59739989
Closing as duplicate of https://github.com/flutter/flutter/issues/7474
