### ISSUE TITLE
image_picker on web app. 

### ISSUE THREAD

**Issue by vinnytwice** [flutter/flutter#61235]
I was using image_picker_web and image_picker but then image_picker_web throws `No podspec found for 'image_picker_web' in '.symlinks/plugins/image_picker_web/ios'` when running app on web, and as I see from this https://github.com/Ahmadre/image_picker_web/issues/11 image_picker is now supporting web but for what I see in the example on pub.dev it's not.
Now, while on iOS everything works as expected, when on web I can't get to pick an image. I only see the ImageSource.gallery as viable option but it won't open any selection popup. 

Is there a way to use it on web then?
Thank you very much.

```
Future<Uint8List> pickImage() async {
    Uint8List imageData;
    await picker.getImage(source: ImageSource.gallery).then((picked) async {
      imageData = await picked.readAsBytes();
    });

    return imageData;
  }
```

**Comment by TahaTesser** [comment]
Hi @vinnytwice 
You can check official first party [image_picker_for_web](https://pub.dev/packages/image_picker_for_web#-readme-tab-) package 

Please add following packages and using the official [example](https://pub.dev/packages/image_picker#-example-tab-)
```
  image_picker: ^0.6.7+4
  image_picker_for_web: ^0.1.0+1
```

<img width="320" alt="Screenshot 2020-07-13 at 2 42 23 PM" src="https://user-images.githubusercontent.com/48603081/87286928-18d8c300-c517-11ea-84b5-b21dc4fab79e.png">
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (2 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
```

</details> 
Thank you

**Comment by vinnytwice** [comment]
@TahaTesser Hi, and thank you. I'll surely try the web package dough I already written the web image picking not to use any package. 
Cheers.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
