### ISSUE TITLE
Error _targetCursorVisibility , EditableTextState

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#61233]
Launching lib\main.dart on Chrome in debug mode...
/C:/Program%20Files/Flutter/packages/flutter/lib/src/widgets/editable_text.dart:1985:5: Error: The setter 'i_targetCursorVisibility' isn't defined for the class 'EditableTextState'.
 - 'EditableTextState' is from 'package:flutter/src/widgets/editable_text.dart' ('/C:/Program%20Files/Flutter/packages/flutter/lib/src/widgets/editable_text.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'i_targetCursorVisibility'.
    i_targetCursorVisibility = !_targetCursorVisibility;
    ^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
Exited (1)

I don't know why this error occurs.

**Comment by VladyslavBondarenko** [comment]
@anandsubbu007 
looks like you have a typo - `i_targetCursorVisibility` instead of `_targetCursorVisibility`.
Closing since this is not an issue with flutter
