### ISSUE TITLE
ListItem doc should clarify behavior of the dense property

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#6124]
Feedback from usability study:
- **Issue:** The `dense` property on [`ListItem`](https://docs.flutter.io/flutter/material/ListItem-class.html) didn’t have any perceivable effect. It seems that the property mostly affects the font size.
  
  **Recommendation:** Clarify the effect of this property in the doc.

**Comment by sethladd** [comment]
Great, thanks for filing these! :)

**Comment by abarth** [comment]
Yes, it changes the font size and the height.  Probably we should inherit the property from the list instead of specifying it on each item.

**Comment by eseidelGoogle** [comment]
Looks like this was fixed "If dense is true then the overall height of this list item and the size of the DefaultTextStyles that wrap the title and subtitle widget are reduced."
