### ISSUE TITLE
Channel communications between plugin and main thread only works in one way

### ISSUE THREAD

**Issue by moda20** [flutter/flutter#61252]
## Details

I am having issues with my app as since updating to the flutter version 1.17.1 one of my plugins stopped working as intended. the plugin is an andorid only notification panel for music controls. 

After upgrading, I can still send commands to the plugin like switching the status of play and pause icon and changing the text on the notification panel but I can no longer receive any events from the buttons on the notifications. 

Since I am the one who made the plugin, I tried to run the example I did for the plugin and surprisingly it worked very fine which made me sure that the plugin works fine, but when integrated into my main app I realized that setting the callbackHandler of the channel in the plugin dart code doesn't work at all. 

I do set the callbackHandler `channel.setMethodCallHandler(_myUtilsHandler)`where _myUtilsHandler is the handler of events coming from the notification panel. I figured that the `_myUtilsHandler` is not being called at all when a new event is invoked via the channel from the java code and is returning a  `NOT_IMPLEMENTED`response which is weird since I have no code that returns that at all (in dart code), in fact, `_myUtilsHandler` will always return a successful response. 

My idea is there is a problem in the communications between the main thread in my app and my plugin but i never faced this problem before and I couldn't find a reason why the callback is not being called when it should, especially when it all works great in my plugin's example. 

Here is the plugin's repo: https://github.com/moda20/flutter_media_notification

Platform:**
**Target OS version/browser: Android 7**

**Comment by liyuqian** [comment]
This does not seem to be performance related. CC @amirh to see if the plugin team is interested in this.

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause The issue needs further investigation.

**Comment by moda20** [comment]
I was able to fix this issue by creating a "plugin enabled isolate" using flutter_isolate package and then using the problematic plugin there. I don't know why does this occur, my guess is there is somehow a cap on the number of active channels on the main thread because I do use multiple ReceivePorts
