### ISSUE TITLE
Add DDS support for Flutter Web

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#61259]
DDS requires SSE support before it can be enabled for Flutter Web applications.

**Comment by yjbanov** [comment]
Is there a status update for this? Is P3 still accurate priority for this issue?

**Comment by bkonyi** [comment]
There's a WIP at https://github.com/flutter/flutter/pull/65873. Still think P3 is accurate.

**Comment by bkonyi** [comment]
Support landed in https://github.com/dart-lang/webdev/pull/1095.
