### ISSUE TITLE
Clarify how to associate IconButton widgets with actions in an AppBar

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#6125]
Feedback fom usability study:
- **Issue:** User thought they needed to use the [Image](https://docs.flutter.io/flutter/material/Image-class.html) widget to display icons in the [AppBar](https://docs.flutter.io/flutter/material/AppBar-class.html).
  **Recommendation:** Explain what how add/use [IconButton](https://docs.flutter.io/flutter/material/IconButton-class.html) widgets in the doc of the AppBar widget.

**Comment by abarth** [comment]
Makes sense.
