### ISSUE TITLE
Background for dismissable widget overflows on Nexus 5x

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6127]
And this problem does not happen on 5, 6p or galaxy nexus screen.

Details are attached at: b/31798745

**Comment by eseidelGoogle** [comment]
From the screenshots attached to the internal bug, it appears to be a single-pixel of overflow as there end up with what looks like hairline red borders around the list item.

Does this repro with the dismissable in the Flutter Gallery?

**Comment by eseidelGoogle** [comment]
"Leave behind list items" is the name of the Demo in the flutter gallery.  FYI @HansMuller https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/leave_behind_demo.dart

**Comment by eseidelGoogle** [comment]
@Hixie this is the issue.  Supposedly is device-specific, relates to the fact that the device pixel ratio is different.

**Comment by Hixie** [comment]
Do we have a device that shows this on leave_behind_demo.dart?

**Comment by eseidelGoogle** [comment]
From the internal bug, it shows up in leafy's demo on a Nexus 5X but not a Nexus 5 or 6.  I've not yet tested leave_behind.

**Comment by eseidelGoogle** [comment]
I've passed a 5X to @Hixie for initial triage.

**Comment by Hixie** [comment]
We should clip the background so that we only paint it where it's visible that we're dismissing.
