### ISSUE TITLE
Request: Make flutter git upstream configurable from environment variable

### ISSUE THREAD

**Issue by TooYoungTooSimp** [flutter/flutter#61286]
## Steps to Reproduce

1. Install flutter
2. run flutter doctor
3. STUCKED

After some research, I modified `packages/flutter_tools/lib/src/version.dart` with [this patch](https://gist.github.com/TooYoungTooSimp/948082a32f4e4bf58943d2c61a157d96)

Clearly I'm living in China and connection to GitHub is awful.

In the taskmgr I can see a git-fetch-https exists with no move.

So I'm wondering if it's possible to make `const String _flutterGit = 'https://github.com/flutter/flutter.git';` environment variable configurable just like `PUB_HOSTED_URL` and `FLUTTER_STORAGE_BASE_URL`.

Maybe we can add a `FLUTTER_GIT_URL` or something which point to a local mirror to increase development experience.

CONTRIBUTING.md guide is too scary for me so I can't make a pr.

But I can provide my code here:

```dart
import 'base/platform.dart';
const String _flutterGit = platform.environment['FLUTTER_GIT_URL'] == null 
    ? 'https://github.com/flutter/flutter.git'
    : platform.environment['FLUTTER_GIT_URL'];
```
I'm not sure if it can works, but I think it's enough to express my idea.

**Comment by jmagman** [comment]
Interesting idea!  You already did a lot of the research, and we do take pull requests (please make sure to include tests!)

**Comment by christopherfujino** [comment]
This is a good idea. This could help us with integration tests too.

**Comment by TooYoungTooSimp** [comment]
I have made a pr #61513 .
The code itself works on my local pc.

**Comment by TooYoungTooSimp** [comment]
I'm sure I still have a lot to do but I don't know what to do now.....

**Comment by TooYoungTooSimp** [comment]
Except flutter-build, all other test passed.
To be honest, I don't know what is it and other prs have this problem too.

**Comment by christopherfujino** [comment]
> Except flutter-build, all other test passed.
> To be honest, I don't know what is it and other prs have this problem too.

I will comment on the PR
