### ISSUE TITLE
What is org/gradle/launcher/cli/DefaultCommandLineActionFactory

### ISSUE THREAD

**Issue by dhinesh-venkat** [flutter/flutter#61283]
**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

No issues found! (ran in 19.0s)

```
```

</details>

**Comment by rekire** [comment]
How should anybody help you if you don't add the stacktrace and no code which might cause that crash

**Comment by darshankawar** [comment]
Hi @dhinesh-venkat,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that throws this error ?
Thank you

**Comment by dhinesh-venkat** [comment]
Thanks for your response. I'll send the details in a minute

**Comment by dhinesh-venkat** [comment]
`PS E:\flutter\projects\hello_world> flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
    • Flutter version 1.17.1 at E:\flutter\flutter
    • Framework revision f7a6a7906b (9 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\svs\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\svs\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.0)
    • VS Code at C:\Users\svs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Redmi Note 5 Pro • 645ac20 • android-arm64 • Android 9 (API 28)

• No issues found!`




`PS E:\flutter\projects\hello_world> flutter run --verbose
[   +6 ms] Waiting to be able to obtain lock of Flutter binary artifacts directory: E:\flutter\flutter\bin\cache\lockfile
[  +10 ms] Waiting for another flutter command to release the startup lock...
[+57830 ms] executing: [E:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [E:\flutter\flutter/] git tag --contains HEAD
[ +194 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.1
           1.17.2
           1.17.3
           1.17.4
           1.17.5
[   +8 ms] executing: [E:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\flutter\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [E:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] executing: C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +38 ms] List of devices attached
           645ac20                device product:whyred model:Redmi_Note_5_Pro device:whyred transport_id:1
[   +6 ms] C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 645ac20 shell getprop
[ +165 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1121 ms] Generating E:\flutter\projects\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +48 ms] ro.hardware = qcom
[  +46 ms] Launching lib\main.dart on Redmi Note 5 Pro in debug mode...
[   +7 ms] E:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe E:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root E:\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\svs\AppData\Local\Temp\flutter_tool.0bd89490-c4ef-11ea-af69-020ce70b0102\app.dill       
--packages E:\flutter\projects\hello_world\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions      
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +48 ms] executing: C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 645ac20 shell -x logcat -v time -t 1
[ +229 ms] Exit code 0 from: C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 645ac20 shell -x logcat -v time -t 1
[   +3 ms] --------- beginning of main
           07-13 16:25:58.812 D/CompatibilityInfo( 2074): applicationScale - 1.0
[  +41 ms] <- compile package:hello_world/main.dart
[  +15 ms] executing: C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +23 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\svs\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +23 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[ +173 ms] Using gradle from E:\flutter\projects\hello_world\android\gradlew.bat.
[   +9 ms] E:\flutter\projects\hello_world\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +92 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +7 ms] executing: [E:\flutter\projects\hello_world\android/] E:\flutter\projects\hello_world\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=E:\flutter\projects\hello_world\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-rootassembleDebug
[+1524 ms] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[   +8 ms] org/gradle/launcher/cli/DefaultCommandLineActionFactory
[  +14 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +1 ms] * Get more help at https://help.gradle.org
[  +26 ms] Running Gradle task 'assembleDebug'... (completed in 1.9s)
[+4200 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 8,075ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)`

**Comment by darshankawar** [comment]
@dhinesh-venkat, will also need a minimal complete reproducible code sample that is causing this issue.

**Comment by dhinesh-venkat** [comment]
I just created the sample app using

`flutter create hello_world`

So, there is no special extra code.
Thanks

**Comment by darshankawar** [comment]
Hi @dhinesh-venkat,
I tried by creating a new Flutter app using `flutter create hello_world` on latest dev channel and was able to create and launch the app without any issues.
```

Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        48.7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 7.7s
Waiting for SM A260G to report its views...                         10ms
Syncing files to device SM A260G...                                515ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on SM A260G is available at: http://127.0.0.1:50174/iSZ6G6s6mgo=/
```

I'd suggest you run `flutter pub cache repair` and then `flutter run`.
If problem still persists, try to upgrade your Flutter version to latest stable or latest dev and see if you still experience the issue.
Thanks.

**Comment by dhinesh-venkat** [comment]
I'll definitely do that bro, Thanks

**Comment by dhinesh-venkat** [comment]
I have another question on implementation of an app, could you please provide me with solution?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
