### ISSUE TITLE
showSearch with rootNavigator

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#61288]
## Use case

I'm using multiple navigator and I want to `showSearch` in `rootNavigator`

**Comment by darshankawar** [comment]
Hi @tbm98,
Can you please elaborate more on what exactly your question / issue is ? Please provide an existing code sample of what you are trying to do and what are you looking to add / improve / enhance in the code using `rootNavigator`.

**Comment by tbm98** [comment]
When I call showSearch. It always show in navigator nearest. But i want to show search in root navigator, showSearch not support use rootNavigator right now

**Comment by chunhtai** [comment]
if you have the globalkey reference to the root navigator you can do `showSearch(rootNavKey.currentContext, delegate)`

**Comment by tbm98** [comment]
But I think it should has optional parameter to use root navigator similar
to showDialog

Vào 23:51, Th 2, 27 thg 7, 2020 chunhtai <notifications@github.com> đã viết:

**Comment by DanielJaramillo94** [comment]
You could find root context by yourself, in a similar fashion as happens when you set `rootNavigator: true` when you want to use root Navigator.
```
var rootContext =  context.findRootAncestorStateOfType<NavigatorState>().context;
showSearch(context: rootContext , delegate: YourSearchDelegateHere());
```

**Comment by tbm98** [comment]
it was done.
