### ISSUE TITLE
Scribble Handwriting Recognition support (iPadOS14)

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#61285]
iPadOS14 added Handwriting Recognition support so you can just hand write in a TextField and it will translate it to a string.

![apple_ipados-14_scribble_062220_inline jpg large_2x](https://user-images.githubusercontent.com/13773566/87219014-adbba080-c30c-11ea-9021-113156605cdf.jpg)

Here is the UIScribbleInteractionDelegate
 documentation link: https://developer.apple.com/documentation/uikit/uiscribbleinteractiondelegate 

Related issue: #38135

**Comment by softmarshmallow** [comment]
Duplicate of https://github.com/flutter/flutter/issues/61278
