### ISSUE TITLE
webview_flutter scroll feels sluggish on Android

### ISSUE THREAD

**Issue by AInoob** [flutter/flutter#61280]
Hi, so the demo (https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example) feels sluggish on Android. I tested 
flutter_webview_plugin (https://github.com/fluttercommunity/flutter_webview_plugin/tree/master/example) and it feels much faster. I also tested native Android webview, React Native webview, so I can confirm that it's webview_flutter specific issue.

So I did checked the code of flutter_webview_plugin, and it looks like it's just drawing native webview on top of flutter, which is why it's scrolling is smooth. So I think this is due to the fact that webview_flutter is using Platform Views. Can you please confirm this is the case? 

I don't think any additional information is needed, but if you do, please let me know and I can provide them.

- Did you ran on release mode?
Yes, I actually tested both emulator and release mode on my phone, both I could tell the difference between webview_flutter and all other webviews (which were smooth). 
- Can you provide minimum runnable code?
I just ran the example code, so it's the example code.

My app needs webview to load third party website, so it's not possible for me to reimplement website into Flutter. Currently my solution is similar to flutter_webview_plugin, where on Android I draw native views on top of flutter.

**Comment by darshankawar** [comment]
Hi @AInoob,
Please provide `flutter doctor -v`, devices (Android or iOS alongwith OS versions) info you experiencing this issue and if possible a video or gif that shows sluggishness.

**Comment by AInoob** [comment]
Hi @darshankawar ,

I will try to provide GIF in few hours. But again, I don't think this is a bug or anything, rather, this is just normal behavior for Platform Views (since flutter_webview_plugin is smooth and webview_flutter is not). If I have to guess, the sluggish comes from somewhere between latency between gesture and Platform Views, or Platform Views rendering.

[✓] Flutter (Channel master, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en)
    • Flutter version 1.20.0-2.0.pre at /Users/ainoob/Softwares/flutter
    • Framework revision 5995661777 (3 weeks ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ainoob/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/ainoob/Library/Android/sdk
    • Java binary at:
      /Users/ainoob/Library/Java/JavaVirtualMachines/corretto-1.8.0_252/Contents
      /Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.252.09.1 (build
      1.8.0_252-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.43

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 3BFA6E32-1A37-4DD3-AD99-8D3A63445804 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by AInoob** [comment]
@darshankawar ,

Hi, here is the video: https://photos.app.goo.gl/V8whB658WduGYKQD8

The first app is webview_flutter, and the second app is flutter_webview_plugin. The first one has more dropped frames than second one.

I also tested Chrome and Yandex browser, and both are behaving the same as flutter_webview_plugin. I am using OnePlug 5.
Please let me know if you need more information, but again, I don't think there is much else needed, because I think it's what PlatformView is about.

**Comment by AInoob** [comment]
@darshankawar ,

Hi, here is the video: https://photos.app.goo.gl/V8whB658WduGYKQD8

The first app is webview_flutter, and the second app is flutter_webview_plugin. The first one has more dropped frames than second one.

I also tested Chrome and Yandex browser, and both are behaving the same as flutter_webview_plugin. I am using OnePlus 5.
Please let me know if you need more information, but again, I don't think there is much else needed, because I think it's what PlatformView is about.

**Comment by darshankawar** [comment]
Related to [27180](https://github.com/flutter/flutter/issues/27180)

**Comment by darshankawar** [comment]
Hi @AInoob,
Thanks for providing more details. I tried to replicate the issue on latest dev channel but observed smooth scrolling. I tested on Android 8.1.0 and found no issues of sluggishness.

[61280.mp4.zip](https://github.com/flutter/flutter/files/4911549/61280.mp4.zip)

Per your earlier comment, you don't see this as a bug, so would you be okay to close this ticket ?

**Comment by AInoob** [comment]
Hi @darshankawar ,

I think the way you scroll cannot really tell much, try to scroll down a bit, then lift your finger, and let the web view scroll by itself due to the momentum.

Again, I have tested Chrome, Yandex browser, webview_flutter_plugin, even React Native, none of them show the same sluggish as flutter_webview. And I can confirm that I can clearly tell the difference between flutter_weebview and all others. 

What I want is to have flutter_webview plugin state in README or somewhere that it's not as smooth as other plugins. I chose Flutter for the smoothness, but flutter_webview is clearly not doing that.

If you think my observations are wrong, I am happy to provide more accurate data to show you that indeed flutter_webview is not as smooth as others. (webview_flutter_plugin, Native, React Native, Chrome, Yandex browser)

I think we all want Flutter to be butterly smooth, so please do not close this if you think it's smooth, because I am willing to give more data to prove my claim (I am thinking of using Android performance monitor or something (not familiar with Android TBH)).

**Comment by blasten** [comment]
@AInoob  https://github.com/flutter/flutter/issues/61133 fixes this issue and it works similar to the https://github.com/fluttercommunity/flutter_webview_plugin plugin. The native webview is added to the Android view hierarchy.

**Comment by AInoob** [comment]
> @AInoob  https://github.com/flutter/flutter/issues/61133 fixes this issue and it works similar to the https://github.com/fluttercommunity/flutter_webview_plugin plugin. The native webview is added to the Android view hierarchy. 

Thank you! 
I would definitely try out and let you know if it's working.

Will this support having list of web views in a horizontal scroll view? That is, having web view as a widget that can be moved by Flutter.

**Comment by blasten** [comment]
This has been fixed in Flutter 1.22/ WebView 1.0 - use hybrid composition in the Flutter WebView plugin.

https://github.com/flutter/plugins/tree/master/packages/webview_flutter#using-hybrid-composition
