### ISSUE TITLE
Android Studio does not have autocompletion for C++ code for a FFI plugin project

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#61291]
## Steps to Reproduce

Running Android Studio 4.0

1. Create a functional FFI plugin 
2. Try to code the C++ part in Android Studio
3. Include any C++ standard library and start using APIs such as thread

Result: 

- You must type in every single character for C++ code because there is autocompletion firing up from Android studio
- The autocompletion works fine for the Dart part of the plugin 

## Logs

```
```

```
```

**Comment by dcharkes** [comment]
Related issue and SO question w.r.t. C++ support in IDE when developing Flutter apps:

* https://github.com/dart-lang/ffi/issues/47
* https://stackoverflow.com/questions/62351258/debug-c-code-from-dart-package-using-dartffi

**Comment by TahaTesser** [comment]
Hi @kakyoism 
You can Android folder in Android Studio in a window and where it fully support C++ 
Please check above reply
Thank you

**Comment by kakyoism** [comment]
> Related issue and SO question w.r.t. C++ support in IDE when developing Flutter apps:
> 
> * [dart-lang/ffi#47](https://github.com/dart-lang/ffi/issues/47)
> * https://stackoverflow.com/questions/62351258/debug-c-code-from-dart-package-using-dartffi

Thanks. I'll give it a try. Yesterday I was trying to create an Android app configuration from the flutter project but didn't succeed.

So I guess this is the similar route to opening Xcode Runner from flutter and debug iOS code from Xcode.
