### ISSUE TITLE
CanvasKit: provide non-overloaded SkPath.arcTo methods

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#61305]
Currently CanvasKit's `SkPath.arcTo` is overloaded. The implementation dynamically destructures the argument list and decides which WASM version to call. There's actually two dynamic destructuring happening, one in `interface.js` and one in the Emscripten bindings (the `_arcTo` is also overloaded):

```javascript
  CanvasKit.SkPath.prototype.arcTo = function() {
    // takes 4, 5 or 7 args
    // - 5 x1, y1, x2, y2, radius
    // - 4 oval (as Rect), startAngle, sweepAngle, forceMoveTo
    // - 7 rx, ry, xAxisRotate, useSmallArc, isCCW, x, y
    var args = arguments;
    if (args.length === 5) {
      this._arcTo(args[0], args[1], args[2], args[3], args[4]);
    } else if (args.length === 4) {
      this._arcTo(args[0], args[1], args[2], args[3]);
    } else if (args.length === 7) {
      this._arcTo(args[0], args[1], args[2], !!args[3], !!args[4], args[5], args[6]);
    } else {
      throw 'Invalid args for arcTo. Expected 4, 5, or 7, got '+ args.length;
    }

    return this;
  };
```

This is slower than a direct call to the desired function, because JavaScript doesn't have static overloads this required dynamic dispatch. It also makes Dart-JS bindings awkward as there's no single method signature to bind to.

Instead CanvasKit should provide three specialized methods `arcTo` (takes 4 args; could be named something else for backwards-compatibility), `arcToPoint` (takes 7 args), and `arcToTangent` (takes 5 args). There would be no need for dynamic dispatch, and Dart-JS bindings would be trivial.

/cc @kjlubick

**Comment by kjlubick** [comment]
ack

**Comment by nhnifong** [comment]
I'll split it apart into the methods you described, deprecating the original.

**Comment by kjlubick** [comment]
@nhnifong this landed, right?

**Comment by nhnifong** [comment]
yes it has.

**Comment by yjbanov** [comment]
Thank you! I see the new methods and I'll move our code to the new ones.
