### ISSUE TITLE
defaultTargetPlatform on web thinks it's Android (on Linux & Windows)

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#61321]
defaultTargetPlatform returns TargetPlatform.android for web builds (on Linux & Windows)

There is already a closed ticket (#43633), but the related PR (https://github.com/flutter/flutter/pull/56081) fixed it only for macOS & iOS.

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/60271

**Comment by gspencergoog** [comment]
Actually a duplicate of #60271, because the theme gets its information from `defaultTargetPlatform`.
