### ISSUE TITLE
TapGestureRecognizer should support mouse states

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#61325]
Using a `RichText` with parts of the sentence clickable we can easily use `TapGestureRecognizer` in the `TextSpan` like so:

```
recognizer: TapGestureRecognizer()
                ..onTap = () {
                  Dialogs.openTermsAndConditions(context);
                },
```

Here is a copy paste example:

```
      RichText(
        textAlign: TextAlign.center,
        text: TextSpan(
          text: "This is some text that we will break line\n",
          children: [
            TextSpan(
              text: "clickable text ",
              style: const TextStyle(fontWeight: FontWeight.bold),
              recognizer: TapGestureRecognizer()
                ..onTap = () {
                  print("You have clicked on "clickable text");
                },
            ),
            const TextSpan(text: "cool right?"),
          ],
        ),
      )
```
The problem is that we don't get a mouse pointer effect on web as it doesn't use `MouseRegion`.

## Proposal

As we now have the different mouse states with the help of `MouseRegion` which is also part of things like `InkWell` and `RaisedButton` we should also have it for `TapGestureRecognizer` as there is no way of wrapping that in a `MouseRegion` as the `TextSpan` requires a `GestureRecognizer`.

**Comment by esDotDev** [comment]
This blocks us from giving that the "Selectable block of text with links in it" that Web users would expect, making the app feel a little out of place:
![image](https://user-images.githubusercontent.com/736973/110025740-03eeb100-7ced-11eb-8c6a-ef6beda6f3cf.png)

There's no good workaround right now, we either use rows and cols, and lose the selectable block, or have a selectable block, but lose cursors.

**Comment by kaboc** [comment]
It is currently impossible (or at least not easy) AFAIK to apply multiple gesture recognizers together to a single `TextSpan`, so I think either of below is necessary:

- Adding something like `MouseRegion` that can be used for `TextSpan`s (Does Robert's proposal mean this?)
- Adding `HoverGestureRecognizer` (as described in #33312) and also making it possible to use multiple gesture recognizers.

The latter would be great in that it'd also allow `TextSpan` to support `TapGestureRecognizer` and `LongPressGestureRecognizer` at the same time. Without it, I had to do a workaround like using only `TapGestureRecognizer` combined with `Timer` to check the length of a tap/click.

**Comment by kaboc** [comment]
I found how to use `MouseRegion` for hover effects over `TextSpan`s. See [here](https://github.com/flutter/flutter/issues/33312#issuecomment-791876182) for the GIF animation of its demo and the link to DartPad.

However, it was not very easy. I hope a better solution will be provide.

**Comment by pedromassangocode** [comment]
Hi @RobertBrunhage 
My mouse states you mean hover events? If yes, then I would like to merge this in https://github.com/flutter/flutter/issues/81159 as it is better describes the proposal.
Thank you

**Comment by RobertBrunhage** [comment]
Yep, sounds good!

**Comment by pedromassangocode** [comment]
Merging this in https://github.com/flutter/flutter/issues/81159.
Thank you
