### ISSUE TITLE
Make Flutter complete documentation available in downloadable PDF

### ISSUE THREAD

**Issue by CSELINGUA** [flutter/flutter#61335]
Please I need Flutter Full Documentation in PDF. I've made several searches but no luck!

**Comment by azeemgujjar** [comment]
yes agreed, we need this for offline use and quick search on single document

**Comment by Peacess** [comment]
the offline pdf doc is very important, so any process about it

**Comment by goderbauer** [comment]
@gspencergoog I seem to remember that we upload a ZIP somewhere of our docs that people could download for offline reading. It's not a PDF, but should fulfill this use case. Do we document this somewhere?

**Comment by gspencergoog** [comment]
Yes, we do have an HTML site zip file for the API docs:

stable: https://api.flutter.dev/offline/flutter.docs.zip
master: https://master-api.flutter.dev/offline/flutter.docs.zip

and the [Dash](https://kapeli.com/dash)/[Zeal](https://zealdocs.org/) XML config is here too, which you can probably also generate PDF files from:
stable: https://api.flutter.dev/offline/flutter.xml
master: https://master-api.flutter.dev/offline/flutter.xml

Ironically, no, it doesn't appear to be documented anywhere.
