### ISSUE TITLE
ReorderableListView doesn't detect mouse long press on static devices

### ISSUE THREAD

**Issue by dhianabli** [flutter/flutter#61330]
So I am using ReordableListView on a web project to be able to reorder ListTiles but the problem that the LongPress with the mouse to be able to drag the ListTiles is not detected with my static device through the Chrome browser. 

However, when I access my web project through a mobile device the LongPress is detected and I am able to reorder the ListTiles

I am looking for a solution or a fix for this case namely how to make ReordableListView detect when I want to drag the items with 
the static device and behave accordingly.

I didn't provide my flutter log for reproducing the issue since I am not sure if the Widget itself doesn't support the feature or because I did something wrong

**Comment by TahaTesser** [comment]
Hi @dhianabli 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
