### ISSUE TITLE
[iOS]  UiKitView will be rendered with borders.

### ISSUE THREAD

**Issue by ENUUI** [flutter/flutter#61340]
When I use UiKitView on iOS,  the UiKitView will be rendered with  borders.
Even, while the modal bottom sheet is showing, the borders are still there.
Strangely, when I take a screenshot or record screen, the borders will disappear!!

 Any UiKitView will be reproduced the problem.

Device: iPhone 8plus 
iOS: 13.5.1

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
```
</details>

Edited by @cyanglaz 
This seems to be device and OS specific and I'm putting up a list to keep track:
Check mark means validated and confirmed by a team member.

Reproducible devices:
- [x] iPhone 8 plus 14.6
- [ ] iPhone 8 plus 13.5.1
- [ ] iPhone 11 pro max
- [ ] iPhone 12 mini
- [ ] iPhone 12 pro

Not-reproducible devices:
- [x] iPhone 11
- [x] iPhone 12 pro max 14.4.2
- [x] iPhone 8 plus 14.6

**Comment by TahaTesser** [comment]
Hi @ENUUI 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample and screenshot of the borders 
Thank you

**Comment by ENUUI** [comment]
[EXAMPLE_CODE](https://github.com/ENUUI/uikitview_example)
There are not screenshots but photos, because UiKitViews in screenshots do not have any unexpected border.
And the borders will appear again after taking a screenshot or recording the screen.

![IMG_3579](https://user-images.githubusercontent.com/50231491/87381981-855fca80-c5c8-11ea-9559-57b791584f9e.JPG)
![IMG_3580](https://user-images.githubusercontent.com/50231491/87381988-8a247e80-c5c8-11ea-8dba-a3d1c437d10c.JPG)

**Comment by TahaTesser** [comment]
Hi @ENUUI 
Your code repository has missing code and unable to run. There is no `uikitview_example.dart` class and no native code for UIKitView
Please check your repository and make sure it has everything to reproduce the issue
Thank you

**Comment by ENUUI** [comment]
@TahaTesser 
So sorry! Please try again.

**Comment by TahaTesser** [comment]
I can run the code sample now but no borders on physical iPhone XR. This could be device specific, author has  on Device: iPhone 8plus
iOS: 13.5.1

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.5.1
    • iPhone 11 (mobile)     • C56E212F-BE8E-4766-8610-12CFADC797F0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.5 19F101
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10 (API
      29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5.1

• No issues found!

```

</details>

**Comment by ENUUI** [comment]
@TahaTesser 
I've tried `iPhone 8plus,  iPhone 11 and iPhone 11 Pro Max `,  only ` iPhone 11` is normal.
See photos of iPhone 11 Pro Max.

![IMG_3591 HEIC](https://user-images.githubusercontent.com/50231491/87531130-d7d1e180-c6c3-11ea-8484-608091ff3ed2.JPG)
![IMG_3592 HEIC](https://user-images.githubusercontent.com/50231491/87531144-ddc7c280-c6c3-11ea-9ebd-85fbaa59db87.JPG)


<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/admin/.flutter_code_source/stable/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • H的iPhone • 2c2b047d44debadd29c52ea0c1136b0a6d33658a • ios • iOS 13.5.1
```
</details>

**Comment by romanlytvyn** [comment]
I can confirm, same issue on the latest `dev` channel build, iOS only.
In my case `webview_flutter` and `google_maps_flutter` are affected.

See the screenshot of a google maps widget. The border is drawn on top of the button.
Also the line (embedding border?) in the bottom right corner of the map is not respecting clipping.
Same behavior for a webview.
![image](https://user-images.githubusercontent.com/4062852/87860508-4de17d00-c93e-11ea-9ea4-0b8d182b81c5.png)


```
Container(
  width: 200,
  height: 200,
  child: ClipRRect (
    clipBehavior: Clip.antiAliasWithSaveLayer,
    borderRadius: BorderRadius.circular(25),
    child: GoogleMap(
...
```

Additionally, notice the horizontal lines artifacts above and below the status bar icons.
![image](https://user-images.githubusercontent.com/4062852/87860530-82edcf80-c93e-11ea-9fb5-5131dd48c9c8.png)


iPhone XR, iOS 13.5.1

`flutter doctor -v`
```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F83c, locale
    en-DK)
    • Flutter version 1.21.0-1.0.pre at /Users/roman/development/flutter
    • Framework revision f25bd9c55c (4 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

**Comment by romanlytvyn** [comment]
Another issue, a "frost" `ImageBackdrop` filter page transition seems to have no effect on the embedded view, again, only on iOS.
As you can see, the map part on the right side is not blurred at all and map border is shown on top of the transparent page.
The original border issue is not reproducible on simulator while this one is.

Not sure, if it's related, @TahaTesser ?

![image](https://user-images.githubusercontent.com/4062852/87863166-9ad24d00-c958-11ea-830e-a530d6d98d36.png)

```
class TransitionBuilders {
  static Widget frostTransition(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return FrostTransition(
      animation: Tween<double>(begin: 0, end: 1).animate(animation),
      child: child,
    );
  }
}

class FrostTransition extends AnimatedWidget {
  final Widget child;
  final Animation<double> animation;

  FrostTransition({
    this.animation,
    this.child,
  }) : super(listenable: animation);

  @override
  Widget build(BuildContext context) {
    return BackdropFilter(
      filter: ImageFilter.blur(
        sigmaX: animation.value * 5,
        sigmaY: animation.value * 5,
      ),
      child: child,
    );
  }
}
```

Same hardware, flutter version as in my previous [comment](https://github.com/flutter/flutter/issues/61340#issuecomment-660531727).

**Comment by dvird** [comment]
@jmagman ?

**Comment by jmagman** [comment]
@dvird Please don't @ individual contributors.  I don't generally work on these kind of bugs.

**Comment by dvird** [comment]
What's about it? i think its much more important than the others because It's foundations. if ios native view does work it means a lot about flutter condition. i think you should promote it and take it more seriously

**Comment by jmagman** [comment]
Maybe this is framework?

**Comment by dvird** [comment]
?

**Comment by shanxus** [comment]
Any update on this? Found same issue on iPhone 12 mini and iPhone 12 pro.

**Comment by hyobbb** [comment]
When using google map it renders the white border. But when I do screenshot or frame recording it disappears like a magic. Happens on iphone 12 mini and pro max.

**Comment by TahaTesser** [comment]
It looks very circumstance dependent, I can't reproduce when I try to. 

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      // theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('PlatformView WebView'),
      ),
      body: Container(
        width: 300,
        height: 300,
        child: ClipRect(
          child: WebView(
            onWebViewCreated: (controller) {
              controller.loadUrl('https://flutter.dev/');
            },
          ),
        ),
      ),
    );
  }
}

typedef void WebViewCreatedCallback(WebViewController controller);

class WebView extends StatefulWidget {
  const WebView({
    Key key,
    this.onWebViewCreated,
  }) : super(key: key);

  final WebViewCreatedCallback onWebViewCreated;

  @override
  State<StatefulWidget> createState() => WebViewState();
}

class WebViewState extends State<WebView> {
  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
        viewType: 'webview',
        onPlatformViewCreated: _onPlatformViewCreated,
      );
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      return UiKitView(
        viewType: 'webview',
        onPlatformViewCreated: _onPlatformViewCreated,
      );
    }
    // TODO add other platforms
    return Text(
        '$defaultTargetPlatform is not yet supported by the map view plugin');
  }

  void _onPlatformViewCreated(int id) {
    if (widget.onWebViewCreated == null) {
      return;
    }
    widget.onWebViewCreated(new WebViewController(id));
  }
}

class WebViewController {
  WebViewController(int id) {
    this._channel = new MethodChannel('webview$id');
  }

  MethodChannel _channel;

  Future<void> loadUrl(String url) async {
    return _channel.invokeMethod('loadUrl', url);
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.156 at /Users/tahatesser/Code/flutter_master
    • Framework revision 45508985b1 (8 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by guopeng1994** [comment]
same problem on iphone8 plus IOS13.6

![image](https://user-images.githubusercontent.com/30316642/108697915-6e119400-753e-11eb-8965-a629e99a0dd9.png)

**Comment by wangliguang** [comment]
这个问题有最新消息了么

**Comment by wangxinnong** [comment]
Same issue here:
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (5 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**Comment by wangliguang** [comment]
尝试过各种方案都不行。无奈最终选择了如下取巧的方式。

1. 让WebView全屏展示。此时WebView的边框会和手机屏幕的边框重合，用户无感知

2. 通过注入js的方式给body增加需要的间距

I have tried all kinds of schemes. Reluctantly chose the following trickery.

1. Let the WebView display in full screen. At this time, the frame of the WebView will overlap with the frame of the phone screen, and the user has no perception

2. Add the required spacing to the body by injecting js

**Comment by zytabcd123** [comment]
![image](https://user-images.githubusercontent.com/11885452/118627515-5e80af00-b7fe-11eb-8ec9-8fe184f3e635.png)
iOS14以上系统启动App的时候清空背景色就能解决这个问题

**Comment by AnhJobChat** [comment]
@ENUUI  did you resolve this solution?

**Comment by jesteracer** [comment]
It also affects the https://github.com/googleads/googleads-mobile-flutter package (when using inline ads). And it is not consistant — sometimes there are borders, sometimes — no borders. Also it is hard to make a screenshot, since this borders are not captured by video screenshot or still. 

This issue will prevent us to monetize the app using admob :(

**Comment by naamapps** [comment]
Any news? this issue is really critical for UX.
A pixel bleed in a production application is a situation we all want to avoid.
Please help,
Thanks

**Comment by cyanglaz** [comment]
> ImageBackdrop

Backdrop filter on iOS platform view and Android hybrid composition platform view has not been implemented yet. Please follow https://github.com/flutter/flutter/issues/43902 and https://github.com/flutter/flutter/issues/58426 for more details :)

**Comment by davidgalarza** [comment]
Any update? I'm facing the same issue.

**Comment by kingiol** [comment]
On the latest flutter stable, same issue occured.

> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-CN)
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

**Comment by QuentinSc** [comment]
My app still not public because of this..

**Comment by Stoisss** [comment]
Our team is able to reproduce it only on iPhone 12 mini. On other devices, this issue does not occur. Are there any updates?

**Comment by cyanglaz** [comment]
Updates: I was able to repro in a iPhone 8 plus iOS 14.6

Initially I thought the issue might caused by 1 pixel off during layout. (For example, touchInterceptor is 1 pixel larger than it suppose to be)
I tried with assigning different colors to different views,(also explicitly setting borderWidth to all the views to 0) the border still shows gray. See:
<img width="618" alt="Screen Shot 2021-09-29 at 10 30 17 AM" src="https://user-images.githubusercontent.com/3756895/135319394-14f9e04d-6664-4991-919b-3a4f6843d01a.png">

Will continue investigate and post updates if I have some progression.

**Comment by qscr** [comment]
same issue..
please fix asap

**Comment by ozz-rjq** [comment]
having the same issue, tried with physical iphone xr

**Comment by naamapps** [comment]
@cyanglaz Do you have news about this?
Would be great if you can update on progress.
This issue is critical for production.
Thanks

**Comment by qscr** [comment]
Flutter Team, do u have any news about fix or some workaround?
Issue is critical for production, please fix asap

**Comment by cyanglaz** [comment]
I have been pulled to some other high priority work. So as now, there hasn't been any progress since my last comment. I (or someone else) will eventually circle back to this.

**Comment by raphaelvigee** [comment]
Since this issue is over a year old, has anyone found a workaround? (I tried wrapping with a ClipRect and other trickery without any success)

**Comment by X-Liang** [comment]
> I can run the code sample now but no borders on physical iPhone XR. This could be device specific, author has on Device: iPhone 8plus iOS: 13.5.1
> 
> flutter doctor -v
> flutter doctor -v
> Can you upgrade to latest `master` and try again Execute the follwing `flutter channel master` `flutter upgrade --force` `flutter doctor -v`
> 
> If the problem persist on latest `master`, please provide new `flutter doctor -v` with latest `master` Thank you

This may be due to the screen scale is 3

**Comment by X-Liang** [comment]
I try to found the problem point and found that: This line is show in the OverlayView which in the [OverlayView set frame](https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L615) and if it's parent [OverlayWrapper don't set clipToBounds property](https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L71) the line disappear

**Comment by JsouLiang** [comment]
> @TahaTesser [EXAMPLE_CODE](https://github.com/ENUUI/uikitview_example) There are not screenshots but photos, because UiKitViews in screenshots do not have any unexpected border. And the borders will appear again after taking a screenshot or recording the screen.
> 
> ![IMG_3579](https://user-images.githubusercontent.com/50231491/87381981-855fca80-c5c8-11ea-9559-57b791584f9e.JPG) ![IMG_3580](https://user-images.githubusercontent.com/50231491/87381988-8a247e80-c5c8-11ea-8dba-a3d1c437d10c.JPG)

I try your example, and delete the UIKIt View backgroundColor then the border disappear;
But I don't know why😂

**Comment by JsouLiang** [comment]
UIKitView is premultiplied alpha and flutter view may be straight alpha, and this issue is blend mode bug ?

**Comment by cyanglaz** [comment]
Update:
I have reduced the issue into a scenario where adding a UIView on top of FlutterView will reproduce the issue.
I also found that this issue only exists when using MetalLayer or EAGLLayer. CALayer doesn't have this issue.

@chinmaygarde Might have more thoughts on this.

**Comment by JsouLiang** [comment]
https://github.com/flutter/engine/pull/30664
I have a solution.

**Comment by JsouLiang** [comment]
> ![wecom-temp-7acb795c288140ead31946f44f5e3cf0](https://user-images.githubusercontent.com/15976038/149900057-f454cc57-e965-47cd-9cae-e38c69d24179.jpg) is there any solution？
flutter/engine#30664

**Comment by maoemao** [comment]
> 

this no iOS code，just webview page to flutter page

**Comment by JsouLiang** [comment]
@maoemao I know, this question is not cause of WebView page. The reason is iOS UIKitView

**Comment by jmagman** [comment]
https://github.com/flutter/engine/pull/30664 was reverted due to a performance issue https://github.com/flutter/engine/pull/31710

**Comment by amitrotner** [comment]
Any updates?

**Comment by amitrotner** [comment]
@cyanglaz  Do you have news about this?
This issue is critical for production.
Thanks

**Comment by Mizhek** [comment]
No updates? Issue is still present on 3.3.0.

**Comment by sarlow** [comment]
As a partial workaround for those running into this issue with flutter_webview, I found that setting `backgroundColor: Colors.transparent` on the WebView mostly resolved the issue in my case.

**Comment by Jeonguk-ninehire** [comment]
I just use @JsouLiang solution. Turned off viewOpaque property of FlutterViewController with MethodChannel when only unexpected border lines showed up. `backgroundColor: Colors.transparent` is cannot solve bottomSheet or overlay view case. 
@JsouLiang I know your solution has performance issue. Is this performance issue will affect after turn on viewOpaque property again or not?

**Comment by JsouLiang** [comment]
@Jeonguk-ninehire I think the GPU performance loss that has increased, The exact situation may need to see Xcode instrement's analysis

**Comment by nank1ro** [comment]
I don't know if this can solve your issues, but I was facing an issue very similar to this one where I render a native `UIView `and when displaying a Dialog on top of this `UIKitView` I saw some strange lines (borders) of that view.

In my case around the native iOS view I have a container with a border radius. Passing the same border radius to the native view seem to have solved this issue. Example of my code:
```dart
 late final args = <String, dynamic>{
   'borderRadius': borderRadius,
 };

/// view
UiKitView(
  creationParams: args,
  creationParamsCodec: const StandardMessageCodec(),
  ...
)
```
then on Swift in the `init` of the FlutterPlatformView:
```swift
// create the view before the super.init() call
_view = UIView() // any custom view can be used here, used UIView only for the example
super.init()
let params = args as! [String: Any]
let borderRadius = params["borderRadius"] as! Double
// these 3 lines seems fixing the issue (at least for me)
_view.isOpaque = false
_view.layer.cornerRadius = borderRadius
_view.layer.masksToBounds = true
```
Hope this can help!

**Comment by cyanglaz** [comment]
Un-assign myself as I'm not actively working on this.

**Comment by SAGARSURI** [comment]
Any update on this?

**Comment by danagbemava-nc** [comment]
I just tested the code from https://github.com/ENUUI/uikitview_example on my iPhone XS and I can't seem to reproduce the issue on the latest version of flutter stable. 

If anyone is still facing this issue, can you please provide the device you're seeing it on along with a complete minimal reproducible code sample so we can further investigate this? 

Thank you

<img src="https://github.com/flutter/flutter/assets/88313112/4091c647-f753-4690-8450-325db5544099" width="300" />
