### ISSUE TITLE
Can I write a flutter app for specific flutter version? 

### ISSUE THREAD

**Issue by mivanzhang** [flutter/flutter#61343]
can we add flutter sdk version in pubspec.yaml or somewhere ? Beacause My app  can only run on version 1.12.13, if someone whose flutter is above 1.12.13, he will get compile error。

My assumption look like this:

```dart
dependencies:
  flutter:
    sdk: flutter
    version: "1.12.1"

```
We can add version for flutter sdk

**Comment by PixelToast** [comment]
See https://dart.dev/tools/pub/dependencies
You can apply version constraints to the Flutter SDK like this:

```
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.0 <=1.12.13'
```

In the future, questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by mivanzhang** [comment]
Thank you very much,I
