### ISSUE TITLE
customize label balloon size for slider

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6134]
Is there anyway to adjust the balloon radius for slider according to the length of the label or let sliders take in fontsize/balloon size as parameter? It looks like currently the radius is pre-determined and the labels with long text can overflow.

**Comment by abarth** [comment]
The radius is predetermined.  We should add a way to customize it.

We could size it based on the label, but that might mean it would change size as the label changes, which wouldn't look very good.

**Comment by Hixie** [comment]
Should we size it based on the biggest possible label?

**Comment by abarth** [comment]
We don't know the set of possible labels because the client supplies only the current label when building the slider.

**Comment by mehmetf** [comment]
@vy0592 Are we still blocked on this? I thought we are not using "balloons" anymore. If we are not blocked, let's remove leafy tag.

**Comment by mehmetf** [comment]
Clarified with Vicky that we no longer need this.

**Comment by eseidelGoogle** [comment]
Looks like still no way to customize, so this is still valid:
https://docs.flutter.io/flutter/material/Slider-class.html

**Comment by gspencergoog** [comment]
This is now customizable with the rewrite of the slider for the latest Material Design spec.  You can write your own [SliderComponentShape](https://docs.flutter.io/flutter/material/SliderComponentShape-class.html) that does whatever you like.
