### ISSUE TITLE
Several routes are called on `onGenerateRoute` when refreshing Flutter Web app

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#61351]
# Description

When using named routes with a sub-path `/something/something-else`, if we reload the web page, we will have multiple calls to the `onGenerateRoute`

## Expected Result

When refreshing a Flutter Web app that uses named routes, if we are refreshing the route `/something/something-else` I expect that the `onGenerateRoute` only calls the builder for `/something/something-else`

## Actual Result

The `onGenerateRoute` calls both `/something` and `/something/something-else`:

## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.14.6 18G5033, locale en-PT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.46.0)
[✓] Connected device (2 available)

• No issues found!
```

## Example Repo:

You can clone the following repo: https://github.com/Vanethos/navigator-named-routes-issue

### Steps:
1. Run the app with `flutter run -d chrome`
2. Click on the floating action button so that it navigates to `/something/something-else`
3. Open dev-tools
4. Reload the page - as you can verify the logs, both routes are called

**Comment by chunhtai** [comment]
This is expected, the current navigator will build a stack of routes by default. If you don't want the such functionality, you can override [onGenerateInitialRoute](https://api.flutter.dev/flutter/material/MaterialApp/onGenerateInitialRoutes.html)

**Comment by Vanethos** [comment]
Hmm.. but where is the documentation regarding that @chunhtai ?

And I'll try to override the onGenerateInitialRoute and come back with the results, thanks!

**Comment by Vanethos** [comment]
Got it, was not reading the docs clearly.

A question: should this be added to the main Navigator's documentation page since this is now heavily used in Flutter Web?

**Comment by chunhtai** [comment]
We are working on a [router widget](https://github.com/flutter/flutter/pull/60299) and will eventually want people to migrate from navigator to the router once it is implemented. Our plan will be updating the documentation to use the router instead

**Comment by stuz5000** [comment]
> This is expected, the current navigator will build a stack of routes by default. If you don't want the such functionality, you can override [onGenerateInitialRoute](https://api.flutter.dev/flutter/material/MaterialApp/onGenerateInitialRoutes.html)

What's the rationale for the odd behavior of /a/b/c/d/e/f generating 6 onGenerateRoute calls?

**Comment by stuz5000** [comment]
Using:
```
      onGenerateInitialRoutes: (initialRoute)=>[onGenerateRoute(RouteSettings(name:initialRoute))],
```
is better, but still broken:

1. Run the example below.
2. Enter: ....`/#/home/1/2/3` in the browser bar.

Apps loads calls onGenerateRoute with `/home/1/2/3` twice instead of once.
(Although initState is called only once, which is a huge improvement).

Much better, but still broken.

```
import 'package:flutter/material.dart';

Route onGenerateRoute(RouteSettings settings) {
  int ncalls = 0;
  Widget builder_(BuildContext context) {
    ncalls++;
    print("[$ncalls] Building widget ${settings.name}");
    return Home(Uri.parse(settings.name));
  }

  return MaterialPageRoute<void>(
    builder: builder_, //(context) => path.builder(context, match),
    settings: settings,
  );
}

class Home extends StatefulWidget {
  Uri uri;  /// Determines content of page
  Home(this.uri, {Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState(){
    print("initState ${widget.uri}");
    super.initState();
  }

  @override
  void dispose(){
    super.dispose();
    print("dispose ${widget.uri}");
  }

  @override
  Widget build(BuildContext context) {
    Widget child = Text("home\n${widget.uri}");
    child = Center(child: child);
    child = Container(color: Colors.white, child: child);
    child = Scaffold(body: child);
    return child;
  }
}

//
//////////////////////////////////////////
//


void main() {
  runApp(MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Consultation Tagger',
      onGenerateInitialRoutes: (initialRoute)=>[onGenerateRoute(RouteSettings(name:initialRoute))],
      initialRoute:  "/home/1/2/3/4/5",
      onGenerateRoute: onGenerateRoute)
  );
}
```
