### ISSUE TITLE
Unable to run hello_services app on Android Emulator

### ISSUE THREAD

**Issue by jimmyshiau** [flutter/flutter#6136]
## Steps to Reproduce

Start a Android Emulator with Android studio 2.1.3
![screen shot 2016-09-29 at 5 24 23 pm](https://cloud.githubusercontent.com/assets/1056469/18948432/9b3d8d9e-8669-11e6-94e9-100887ba169d.png)

pick
Nexus 5X Android 6.0 x86_64 or x86

and run `flutter run -v` in  hello_services folder

```
  Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
   0 ms • Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
   0 ms • 'flutter run' took 23600ms; exiting with code 1.
```
## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 7f9c8c4b3e (13 hours ago), 2016-09-28 13:09:38
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /Users/jimmy/Library/Android/sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64

But I can run with real android device: Nexus 7 (2013) Android 4.4.4
which Android Emulator I can run with hello_services sample?

**Comment by eseidelGoogle** [comment]
I suspect hello_services gradle files are not configured for running x86. @jason-simmons or @danrubel might know.

**Comment by eseidelGoogle** [comment]
Possibly missing code here:
https://github.com/flutter/flutter/blob/master/examples/hello_services/android/buildSrc/src/main/groovy/FlutterPlugin.groovy#L56

**Comment by eseidelGoogle** [comment]
@jason-simmons does hello_services support multiple architectures?

**Comment by jason-simmons** [comment]
No, it only supports ARM.

We don't currently distribute the "flutter.jar" binary used by the Gradle plugin for any platform other than ARM.

**Comment by eseidelGoogle** [comment]
Rolling hello_services into the default `flutter create` flow and fixing issues like this is on our list for early next year.  Thanks for the report!

**Comment by kelpenstien** [comment]
It appears to be easy enough to take the flutter.jar from under flutter/bin/cache/artifacts/engine/android-arm-release, unjar it, create a new x86 directory under the lib (a sibling to armeabi-v7a). In the x86 directory copy the **libsky_shell.so**, which should exist under flutter/bin/cache/artifacts/engine/android-x86. Make sure you have the right .so lib (you want it to be ELF 32-bit, Intel 80386). jar it all back up.

Then under local.properties add another entry (this is used by the code that Eric was alluding to earlier) 
flutter.jar=/path/to/flutter/bin/cache/artifacts/engine/android-x86/flutter.jar 

flutter build clean
flutter run 

(all of the above assuming you are talking 32-bit Intel, ofcourse)


Then the sample worked  - well for the most part, but that will be a subject for a different post.

FYI- i use the www.android-x86.org build in virtualbox as my emulator - I've always felt that they perform better than real emulators, unless you need sensors, location, etc - and hence the need to try and get this running on x86.

**Comment by mit-mit** [comment]
@jakobr-google FYI
