### ISSUE TITLE
Keyboard Not Showing Up in TextField

### ISSUE THREAD

**Issue by cdunn612** [flutter/flutter#61365]
In my flutter application, the keyboard does not show up when I try and enter text. I had it working fine on Friday but I updated Flutter over the weekend. I was wondering if anyone else had this issue or if there is something wrong with my code. Thank you for the help!

**Comment by rameshwebo** [comment]
@cdunn612  Same issue here

**Comment by darshankawar** [comment]
Hi @cdunn612,
Please provide more information about the issue by sharing your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue you are facing. 
It will also help if you provide which flutter version was it working on before you upgraded along with the devices on which you are trying to run the app.
Thank you
