### ISSUE TITLE
Flutter should have a ScrollbarTheme

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#61362]
## Use case

Add options to customize the appearance of the Scrollbar widget.

Original feedback: https://github.com/flutter/website/issues/4306#issuecomment-656468600

## Proposal

Add options to allow customizing:

- width
- color
- rounded border

The scrollbar should also change color to white when a dark theme is used https://github.com/flutter/flutter/issues/61364

**Comment by HansMuller** [comment]
We may also need a ScrollbarTheme

**Comment by lazylazyllama** [comment]
Also the default width of the ScrollBar should not be 6.0 but rather be something like 4.0 to look more consistent with android. It also is way to bright in dark mode.

**Comment by salaryazdjerdi** [comment]
Also, would like an option to briefly show scrollbar when page is opened to show scrolling is possible. I see this in other apps i.e. gmail.

**Comment by Piinks** [comment]
Consolidating into https://github.com/flutter/flutter/issues/70866
