### ISSUE TITLE
How i can deploy my flutter web app to Windows or Centos server ?

### ISSUE THREAD

**Issue by Abdusin** [flutter/flutter#61374]
Hello, I create a web app with flutter. I want to run this on my windows server, how can I do this? I tried dhttpd but the stops when I turn off the console

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
