### ISSUE TITLE
launch my app 

### ISSUE THREAD

**Issue by rymarlz** [flutter/flutter#61378]
error to start my app: 
  
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/gonzalopizarro/Desktop/proyecto_servicemotos/clientesapp/build/ios/Debug-iphonesimulator/location_permissions/location_permissions.framework: replacing existing signature
    /Users/gonzalopizarro/Desktop/proyecto_servicemotos/clientesapp/build/ios/Debug-iphonesimulator/location_permissions/location_permissions.framework: resource fork, Finder information, or similar detritus not allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

**Comment by DotSyndicate** [comment]
Did you find any solution?
