### ISSUE TITLE
alias to imports path

### ISSUE THREAD

**Issue by naiadelima** [flutter/flutter#61379]
Create alias to imports path like Angular.
![image](https://user-images.githubusercontent.com/7058175/87346431-103cb880-c528-11ea-8a19-3f9886ff801b.png)

**Comment by TahaTesser** [comment]
Hi @naiadelima 
Please check this answer https://stackoverflow.com/a/53741850
You can import any class from your project with absolute import dart has 
Thank you

**Comment by jonahwilliams** [comment]
this is not supported by the dart language and not something we plan to add
