### ISSUE TITLE
Support tool/web integration tests on CI

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#61382]
The flutter tool has a number of web integration tests that do not run on CI due to high flakiness. Investigate moving this onto the existing web_integration shard and expanding coverage to parity with the tool/Vm integration tests.

**Comment by jonahwilliams** [comment]
Status: still doesn't work, even when isolated to linux: https://cirrus-ci.com/task/6120706800877568?command=main#L2

Might required LUCI

**Comment by jonahwilliams** [comment]
Based on the large number of build breakages and flakes in the last few weeks, I'm tentatively pushing this to Q4 since there is a good chance I will not get to it in time.

**Comment by jonahwilliams** [comment]
FYI @yjbanov

**Comment by godofredoc** [comment]
Web integration tests are now running on LUCI:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_integration_tests
