### ISSUE TITLE
[Material] Verify highlight and splash colors and update comments 

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#61380]
The comments in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L53 mention that the values may or may not be correct. The values need to be verified with the latest material spec, and then the comments can be updated.

**Comment by HansMuller** [comment]
Hopefully the default value for both colors will be derived from the ColorScheme.  And pay close attention to how these colors are used by InkRipple, the splash factory (not the default splash factory) that it's in-sync with the current Material Design spec.

**Comment by HansMuller** [comment]
These colors are now looked up in the ColorScheme and the defaults are configured with the M3 design tokens.
