### ISSUE TITLE
Missing docs for Flutter's contents for pubspec.yaml, what goes in there? etc

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6138]
I didn't find a canonical doc for flutter.yaml:
- where does the file live?
- what are all the options?

It's mentioned very briefly in the intro to widgets, and mentioned briefly in the assets doc. Would love a single canonical doc for that file.

Thanks!

**Comment by raju-bitter** [comment]
Since the content of flutter.yaml has been merged with pubspec.yaml, this issue should be renamed.
See https://github.com/flutter/flutter/issues/2343
E.g. "Missing docs for flutter specific content in pubspec.yaml".

**Comment by sethladd** [comment]
Thanks!

And, patches welcome :)

**Comment by eseidelGoogle** [comment]
Lots of comments now:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/pubspec.yaml.tmpl
