### ISSUE TITLE
[in_app_purchase] Request for a better Readme covering most common use cases

### ISSUE THREAD

**Issue by eldermao1** [flutter/flutter#61384]
Handling purchase updates is mentioned twice in the readme and I found this misleading, First in the "Initializing the plugin" section then in "Listening to purchase updates". Also, With so much information on how to make and handle purchases on each store, it can be confusing. Can we provide a standard and proven approach to have have in app purchases work flawlessly without diving into each store's documentation and trying to work out where each bit of code should be? eg. at app init, on the app's didChangeAppLifecycleState, etc... how should we acknoweldge pending purchases from past sessions or bought outside the App?

If there is a billing screen used as a paywall, what logic should be handled outside this screen and upon app init?

This isn't a problem (bug) with functionality, but a suggestion about accessibility instead. This library could be more accessible by being more clear about best practices for most common use cases.

**Comment by cyanglaz** [comment]
There is now a code lab that guides you through how to do basic purchase flow and more. https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#0

The README is also revised with more details.

I'm going to close this issue. If there are any specific topics that you think the documentation is lacking, please feel free to open another issue with details. Also, feel free to send us PRs to improve the documentation!  :)

**Comment by eldermao1** [comment]
Thank you, Chris! I will make sure to follow the codelab and the README for
the next App I build—this is golden! Also thanks for guiding me through my
first PR, if I come across other suggestions in writing, I'll make sure to
send them your way through a PR.

Cheers,
Mauricio
