### ISSUE TITLE
Need a plan for reporting Dart crashes

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#614]
Presumably we could integrate with existing Android Crash reporting:
https://developers.google.com/analytics/devguides/collection/android/v4/exceptions

Unclear what a solution is on iOS?

@johnmccutchan @Hixie

**Comment by Hixie** [comment]
We also need engine crash reporting.

**Comment by sethladd** [comment]
Firebase now has crash reporting: https://firebase.google.com/docs/crash/

**Comment by eseidelGoogle** [comment]
Now that we use AOT dart in release mode, this plan is likely the same as #4070, but we will also need to be sure we can explain to devs how to symbolicate AOT dart stack traces?  FYI @zanderso

**Comment by sethladd** [comment]
See also this related Gallery link: https://github.com/flutter/flutter/issues/4070

**Comment by mit-mit** [comment]
@eseidelGoogle, FYI I am going to untag this plugin as I don't think this is related to our plugin work.

**Comment by eseidelGoogle** [comment]
Support symbols in AOT code: https://github.com/flutter/flutter/issues/7918

**Comment by sethladd** [comment]
Do you mean "reporting a crash from Dart code running in a Flutter app on a device"?

I know @yjbanov is working on crash reporting for the flutter_tool, which I think is separate from this, but just clarifying.

**Comment by yjbanov** [comment]
A complete solution for Flutter applications would be something along these lines:

- Can report unhandled Dart exceptions and native crashes
- Supports iOS and Android
- Integrates with a publicly available crash reporting backend (Firebase, Crashlytics, etc)

What I worked on supports unhandled Dart exceptions only and the backend is private. So there's still quite a bit of work to do. I think this issue only calls for writing up a plan. Developing an actual solution would be a bigger project that should probably be broken down into multiple smaller issues.

**Comment by eseidelGoogle** [comment]
Assuming the existence of a class with Sender.sendReport method, here is some example code about how to catch Dart exceptions and report them:
```
void main() {
  FlutterError.onError = (FlutterErrorDetails details) {
    sender.sendReport(
      error: details.exception,
      stackTrace: details.stack,
    );
  };

  runZoned<Null>(() {
    // Errors from this call won't be caught by Flutter
    await server.getData();
    // Errors from MyApp constructor won't be caught by Flutter
    runApp(new MyApp());
  }, onError: (error, stackTrace) {
    sender.sendReport(
      error: error,
      stackTrace: stackTrace,
    );
  });
}
```

**Comment by yjbanov** [comment]
Might be worth noting in a comment above `FlutterError.onError` that these _will_ be caught by Flutter:

```dart
// The following handler will receive errors caught by Flutter
FlutterError.onError = (FlutterErrorDetails details) {
 ...
}
```

**Comment by eseidelGoogle** [comment]
@a-siva believes we have most (if not all) of the needed pieces from the runtime & compiler teams.  My understanding is @yjbanov is working on wiring up crash reporting for crashlytics as we speak, and likely will resolve this through that?

**Comment by sethladd** [comment]
We found our contacts in Crashlytics and we have a meeting scheduled for Wednesday. Hope to kick if off real soon!

**Comment by sethladd** [comment]
Should we de-dupe with https://github.com/flutter/flutter/issues/9592 ?

**Comment by yjbanov** [comment]
It's probably going to be hard to cover a complete crash reporting solution with one issue. That said, breaking down the tasks into issues requires some system, so I'm OK with deduping, and if we care to capture sufficient aspects of crash reporting, we could start a GitHub project and log multiple issues there.

**Comment by Hixie** [comment]
@yjbanov What more needs to happen for you to consider this bug closed?

**Comment by yjbanov** [comment]
I think we have an 80% solution, so I'm OK with closing and switching to an incremental enhancements mode.

For users who would like to start collecting crash reports from their app now, check out [package:sentry](https://pub.dartlang.org/packages/sentry).

**Comment by magick93** [comment]
> I think we have an 80% solution, so I'm OK with closing and switching to an incremental enhancements mode.

Where do I find information about the Crashlytics Flutter solution?

**Comment by yjbanov** [comment]
@magick93 this issue is about ability to report crashes in general. The Crashlytics issue is tracked here: https://github.com/flutter/flutter/issues/14765.
