### ISSUE TITLE
Implement faster single-widget hot reloads

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#61407]
### Background

The final stage of hot reload is the "Reassemble" stage, which forces an entirely fresh frame. Because all of the dart code has been de-optimized at this point, and since we're re-rendering the entire widget hierarchy, this can take from 100-300 ms on physical devices.

Speeding up reassemble can be done by making a more intelligent determination about what has changed, and performing a targeted invalidation of one or more Elements instead of an entire cold frame.

### Overview

The hot reload pipeline is roughly:

1. stat files in workspace to determine the change.
2. recompile with updated files
3. sync incremental dill to remote device
4. trigger hot reload of source files in VM
5. invoke reassemble service extension

 (2) is performed by the frontend_server, a secondary process spawned by the flutter tool. This leaves multiple milliseconds of downtime where the tool could perform a little extra work to determine what has changed.

Consider the following edit:

```dart
class Foo extends StatelessWidget {
  Widget build(BuildContext context) {
    return Text('hello, world');
  }
}
```

```dart
class Foo extends StatelessWidget {
  Widget build(BuildContext context) {
    return Text('hello, goodbye');
  }
}
```

Given that there is only a small change in the build method of the Foo widget, instead of a full reassemble, it would still be correct to mark all Element instances with a Foo widget (or Foo widget subclass) as dirty. This should be significantly faster than a full reassemble, as it leaves most of the widget hierarchy untouched.

Determining whether or not a widget has changed can be done by caching (subject to some size limits) the token streams from a previously invalidated dart library. When performing an invalidation a new token stream is compared to the old stream to determine a delta. If this delta lies entirely within the class body of something that extends StatelessWidget or State, then the fastReassemble can be performed in place of the normal reassemble.

### Performance

*A draft PR which implements a subset of this functionality is available at flutter/flutter/58256. NB: this requires flutter config --single-widget-reload-optimization to be enabled*

Based on the initial implementation above, which does not handle Widgets that are subclasses or State subclasses, changes to the build method of the _FlutterLogo class leads to roughly 32% faster hot reloads (422 ms to 286 ms). This is based on the average of 10 reloads on my local workstation, excluding the first two reloads for warm up time.

### Validation

To validate that the average developer experiences an improvement from this change, this feature will be developed under an experimental flag and then gradually rolled out.

**Comment by liamappelbe** [comment]
Hi @jonahwilliams. [This cl](https://dart-review.googlesource.com/c/sdk/+/162943) caused frontend_server_test to fail on windows. Logs are [here](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/12997/pkg/frontend_server/test/frontend_server_test).

**Comment by jonahwilliams** [comment]
Will take a look, looks like the file paths are probably wrong.
