### ISSUE TITLE
Can't TextTheme.apply() a new font weight

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6140]
I see apply() lets me change some things like font family and color, but doesn't appear to allow me to override the font weight.

Maybe that's by design?

I'm trying to override the default font with a "light" weight of a different font.

Thanks!

**Comment by sethladd** [comment]
By design. We don't have a lot of use cases where we want to apply a new weight across the entire app. Can reopen if we get more feedback here.

**Comment by abarth** [comment]
We could let you apply a "delta" to the font weight, which would move all the weighs down by some increment.

**Comment by Hixie** [comment]
Are we talking about https://docs.flutter.io/flutter/widgets/TextStyle/apply.html ? It does have a fontWeightDelta.

**Comment by sethladd** [comment]
Oh, thanks for pointing that out!
