### ISSUE TITLE
The plug-in project does not have an Android directory

### ISSUE THREAD

**Issue by MuZiLee** [flutter/flutter#61405]
## Steps to Reproduce

Either use commands or Packages created by Android Studio.There is no Android directory.
But there was no problem creating Project Flutter.
I tried to reinstall it but it still didn't work out.
Here is the error message when I created the plug-in.
![image](https://user-images.githubusercontent.com/7467318/87369266-ad443380-c5b2-11ea-8f89-66e10ee384aa.png)

## Logs

```
$ flutter create --org com.abc --template=plugin hello
Creating project hello...
The plugin project was generated without specifying the `--platforms` flag, no new platforms are added.
To add platforms, run `flutter create -t plugin --platforms <platforms> .` under the same
directory. You can also find detailed instructions on how to add platforms in the `pubspec.yaml` at
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms.


  hello\.gitignore (created)
  hello\.idea\libraries\Dart_SDK.xml (created)
  hello\.idea\modules.xml (created)
  hello\.idea\runConfigurations\example_lib_main_dart.xml (created)
  hello\.idea\workspace.xml (created)
  hello\.metadata (created)
  hello\CHANGELOG.md (created)
  hello\ios\Classes\HelloPlugin.h (created)
  hello\ios\Classes\HelloPlugin.m (created)
  hello\ios\Classes\SwiftHelloPlugin.swift (created)
  hello\ios\hello.podspec (created)
  hello\ios\.gitignore (created)
  hello\ios\Assets\.gitkeep (created)
  hello\lib\hello.dart (created)
  hello\LICENSE (created)
  hello\hello.iml (created)
  hello\pubspec.yaml (created)
  hello\README.md (created)
  hello\test\hello_test.dart (created)
Running "flutter pub get" in hello...                               0.7s
  hello\example\.gitignore (created)
  hello\example\.idea\libraries\Dart_SDK.xml (created)
  hello\example\.idea\libraries\KotlinJavaRuntime.xml (created)
  hello\example\.idea\modules.xml (created)
  hello\example\.idea\runConfigurations\main_dart.xml (created)
  hello\example\.idea\workspace.xml (created)
  hello\example\.metadata (created)
  hello\example\ios\Runner\AppDelegate.swift (created)
  hello\example\ios\Runner\Runner-Bridging-Header.h (created)
  hello\example\ios\Runner.xcodeproj\project.pbxproj (created)
  hello\example\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  hello\example\ios\.gitignore (created)
  hello\example\ios\Flutter\AppFrameworkInfo.plist (created)
  hello\example\ios\Flutter\Debug.xcconfig (created)
  hello\example\ios\Flutter\Release.xcconfig (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  hello\example\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  hello\example\ios\Runner\Base.lproj\Main.storyboard (created)
  hello\example\ios\Runner\Info.plist (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  hello\example\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  hello\example\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  hello\example\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  hello\example\lib\main.dart (created)
  hello\example\hello_example.iml (created)
  hello\example\pubspec.yaml (created)
  hello\example\README.md (created)
  hello\example\test\widget_test.dart (created)
Running "flutter pub get" in example...                             0.5s
Wrote 69 files.

All done!
[√] Flutter: is fully installed. (Channel master, 1.20.0-8.0.pre.57, on Microsoft Windows [Version 10.0.18362.900],
    locale zh-CN)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.1)
[√] Android Studio: is fully installed. (version 4.0)
[!] Connected device: is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd hello\example
  $ flutter run

Your application code is in hello\example\lib\main.dart.

Your plugin code is in hello\lib\hello.dart.

Host platform code is in the  directories under hello.
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.
```

```
$ flutter doctor -v
[√] Flutter (Channel master, 1.20.0-8.0.pre.57, on Microsoft Windows [Version 10.0.18362.900], locale zh-CN)
    • Flutter version 1.20.0-8.0.pre.57 at D:\flutter
    • Framework revision 8bd2e6585b (2 days ago), 2020-07-11 12:15:19 -0700
    • Engine revision 9b3e3410f0
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by MuZiLee** [comment]
[files img](https://github.com/MuZiLee/logimg/blob/master/20200714092056.png)

**Comment by TahaTesser** [comment]
### Channel master, 1.20.0-8.0.pre.75 & Channel dev, 1.20.0-7.1.pre

<img width="180" alt="Screenshot 2020-07-14 at 2 09 18 PM" src="https://user-images.githubusercontent.com/48603081/87404598-f8bf0780-c5db-11ea-860c-cb04216609be.png">

also executing `flutter create .` doesn't generate `android folder`

```
taha@Tahas-MacBook-Pro hello % flutterd create .
Recreating project ....
The plugin project was generated without specifying the `--platforms` flag, no
new platforms are added.
To add platforms, run `flutter create -t plugin --platforms <platforms> .` under
the same
directory. You can also find detailed instructions on how to add platforms in
the `pubspec.yaml` at
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#pl
ugin-platforms.


Wrote 0 files.

All done!
[✓] Flutter: is fully installed. (Channel dev, 1.20.0-7.1.pre, on Mac OS X
    10.15.5 19F101, locale en-GB)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.5)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.47.0)
[✓] Connected device: is fully installed. (5 available)

In order to run your application, type:

  $ cd example
  $ flutter run

Your application code is in example/lib/main.dart.

Your plugin code is in ./lib/hello.dart.

Host platform code is in the  directories under ..
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.
```

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.75, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-8.0.pre.75 at /Users/taha/Code/flutter_master
    • Framework revision bb3280885c (9 hours ago), 2020-07-13 16:28:27 -0700
    • Engine revision f10f172573
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 06cb010247)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript • Flutter
      Tools
    • Chrome (web)           • chrome                    • web-javascript • Google
      Chrome 83.0.4103.116

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details> 

### Channel beta, 1.19.0-4.3.pre

<img width="175" alt="Screenshot 2020-07-14 at 2 06 30 PM" src="https://user-images.githubusercontent.com/48603081/87404173-6fa7d080-c5db-11ea-8543-0d5bbd2f8171.png">


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-4.3.pre at /Users/taha/Code/flutter_beta
    • Framework revision 8fe7655ed2 (12 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
```

</details>

**Comment by MuZiLee** [comment]
Yes, my downgrade to 1.19 is actually normal

‘’‘
C:\Users\Administrator\Desktop>flutter create --template=package hello
Creating project hello...
  hello\.gitignore (created)
  hello\.idea\libraries\Dart_SDK.xml (created)
  hello\.idea\modules.xml (created)
  hello\.idea\workspace.xml (created)
  hello\.metadata (created)
  hello\CHANGELOG.md (created)
  hello\lib\hello.dart (created)
  hello\LICENSE (created)
  hello\hello.iml (created)
  hello\pubspec.yaml (created)
  hello\README.md (created)
  hello\test\hello_test.dart (created)
Running "flutter pub get" in hello...                               0.5s
Wrote 12 files.

All done!
Your package code is in hello\lib\hello.dart

C:\Users\Administrator\Desktop>flutter create --org com.example --template=plugin hello
Creating project hello...
  hello\.gitignore (created)
  hello\.idea\libraries\Dart_SDK.xml (created)
  hello\.idea\modules.xml (created)
  hello\.idea\runConfigurations\example_lib_main_dart.xml (created)
  hello\.idea\workspace.xml (created)
  hello\.metadata (created)
  hello\android\build.gradle (created)
  hello\android\hello_android.iml (created)
  hello\android\src\main\kotlin\com\example\hello\HelloPlugin.kt (created)
  hello\android\.gitignore (created)
  hello\android\gradle\wrapper\gradle-wrapper.properties (created)
  hello\android\gradle.properties (created)
  hello\android\settings.gradle (created)
  hello\android\src\main\AndroidManifest.xml (created)
  hello\CHANGELOG.md (created)
  hello\ios\Classes\HelloPlugin.h (created)
  hello\ios\Classes\HelloPlugin.m (created)
  hello\ios\Classes\SwiftHelloPlugin.swift (created)
  hello\ios\hello.podspec (created)
  hello\ios\.gitignore (created)
  hello\ios\Assets\.gitkeep (created)
  hello\lib\hello.dart (created)
  hello\LICENSE (created)
  hello\hello.iml (created)
  hello\pubspec.yaml (created)
  hello\README.md (created)
  hello\test\hello_test.dart (created)
Running "flutter pub get" in hello...                               0.5s
  hello\example\.gitignore (created)
  hello\example\.idea\libraries\Dart_SDK.xml (created)
  hello\example\.idea\libraries\KotlinJavaRuntime.xml (created)
  hello\example\.idea\modules.xml (created)
  hello\example\.idea\runConfigurations\main_dart.xml (created)
  hello\example\.idea\workspace.xml (created)
  hello\example\.metadata (created)
  hello\example\android\app\build.gradle (created)
  hello\example\android\app\src\main\kotlin\com\example\hello_example\MainActivity.kt (created)
  hello\example\android\build.gradle (created)
  hello\example\android\hello_example_android.iml (created)
  hello\example\android\.gitignore (created)
  hello\example\android\app\src\debug\AndroidManifest.xml (created)
  hello\example\android\app\src\main\AndroidManifest.xml (created)
  hello\example\android\app\src\main\res\drawable\launch_background.xml (created)
  hello\example\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  hello\example\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  hello\example\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  hello\example\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  hello\example\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  hello\example\android\app\src\main\res\values\styles.xml (created)
  hello\example\android\app\src\profile\AndroidManifest.xml (created)
  hello\example\android\gradle\wrapper\gradle-wrapper.properties (created)
  hello\example\android\gradle.properties (created)
  hello\example\android\settings.gradle (created)
  hello\example\ios\Runner\AppDelegate.swift (created)
  hello\example\ios\Runner\Runner-Bridging-Header.h (created)
  hello\example\ios\Runner.xcodeproj\project.pbxproj (created)
  hello\example\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  hello\example\ios\.gitignore (created)
  hello\example\ios\Flutter\AppFrameworkInfo.plist (created)
  hello\example\ios\Flutter\Debug.xcconfig (created)
  hello\example\ios\Flutter\Release.xcconfig (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  hello\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  hello\example\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  hello\example\ios\Runner\Base.lproj\Main.storyboard (created)
  hello\example\ios\Runner\Info.plist (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  hello\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  hello\example\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  hello\example\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  hello\example\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  hello\example\lib\main.dart (created)
  hello\example\hello_example.iml (created)
  hello\example\pubspec.yaml (created)
  hello\example\README.md (created)
  hello\example\test\widget_test.dart (created)
Running "flutter pub get" in example...                             0.5s
Wrote 98 files.

All done!
[√] Flutter: is fully installed. (Channel flutter-1.19-candidate.4, 1.19.0-4.3.pre, on Microsoft Windows [Version
    10.0.18362.900], locale zh-CN)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.1)
[√] Android Studio: is fully installed. (version 4.0)
[√] VS Code: is fully installed. (version 1.47.0)
[√] Connected device: is fully installed. (1 available)

In order to run your application, type:

  $ cd hello\example
  $ flutter run

Your application code is in hello\example\lib\main.dart.

Your plugin code is in hello\lib\hello.dart.

Host platform code is in the "android" and "ios" directories under hello.
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.

’‘’
Remember "flutter clean".

**Comment by jmagman** [comment]
You need to add the `--platforms` flag when you create.  The error message:
```
The plugin project was generated without specifying the `--platforms` flag, no
new platforms are added.
To add platforms, run `flutter create -t plugin --platforms <platforms> .` under
the same
directory. You can also find detailed instructions on how to add platforms in
the `pubspec.yaml` at
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#pl
ugin-platforms.
```
That the `ios` directory was created is a leftover from https://github.com/flutter/flutter/issues/60215.

@cyanglaz Can we update the https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-1-create-the-package-1 to document `--platforms` and what version the flag is available?

**Comment by cyanglaz** [comment]
@jmagman Will do

**Comment by jmagman** [comment]
New documentation available at https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-1-create-the-package-1.
