### ISSUE TITLE
CanvasKit.PathOp/MakePathFromOp not available

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#61403]
Our CanvasKit backend [uses](https://github.com/flutter/engine/blob/712f619737f1323fd2908b397aa8bd64fb2ccbe5/lib/web_ui/lib/src/engine/compositor/path.dart#L311) `CanvasKit.MakePathFromOp` to implement `Path.combine`. However, as of 0.16.2, neither `PathOp` nor `MakePathFromOp` are available in CanvasKit, resulting in errors:

```
NoSuchMethodError: method not found: 'get$Difference' on null
```

Options:

* Restore the API that were removed.
* See if `SkPathBuilder` provides an alternative approach (see this WIP: https://github.com/flutter/engine/compare/master...yjbanov:js-path-builder?expand=1)

/cc @kjlubick @hterkelsen

**Comment by kjlubick** [comment]
I believe this was removed from the NPM build because the pathop logic adds a non-trivial amount of code size. I'm happy to add this back in (I wasn't sure if it was being used).

If SkPathBuilder does work (note that it does not seem to support PathOps)
