### ISSUE TITLE
[web]: flutter build web command can set build version or generate different js for each build?

### ISSUE THREAD

**Issue by Panda210** [flutter/flutter#61409]
I want to generate different js for each [flutter build web] , then no need to clear cache.
Is there any document?

**Comment by TahaTesser** [comment]
Hi @Panda210 
You can specify version like this from [Caching in Flutter for Web](https://medium.com/flutter-community/caching-in-flutter-for-web-42b3ae0e348f) 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>to_cache_or_not_to_cache</title>
  </head>
  <body>
    <script src="main.dart.js?version=1" type="application/javascript"></script>
  </body>
</html>
```

This will allow to run web without clearing cache.
Hope this helps 
Thanks

**Comment by Panda210** [comment]
@TahaTesser   
`  <script>document.write("<script src='main.dart.js?timestamp=" + Date.now() + "' type='application/javascript'><\/script>");</script>`

**Comment by TahaTesser** [comment]
Hi @Panda210 
Can you please provide more details on this feature you need? Also give us some use cases 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
