### ISSUE TITLE
[video_player] Example implementation not working on iOS devices

### ISSUE THREAD

**Issue by Yke222** [flutter/flutter#61415]
By using the example implementation of the video_player for flutter (https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example, and compiling for the web, by trying to load the web page on an iOS device, the application keeps loading forever, both implementations (web stored asset and local asset) seem to exhibit the same behavior, while the same code runs fine on an Android device, loading both assets without any problem.

ANDROID SCREENS:

![android_2](https://user-images.githubusercontent.com/15067494/87380329-a1338400-c568-11ea-9518-3051077ddd90.jpg)

![android_1](https://user-images.githubusercontent.com/15067494/87380314-9bd63980-c568-11ea-97bc-81661bad7fa5.jpg)

Flutter doctor output:

[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.3.pre at /home/lvelloso/Downloads/fl/flutter
    • Framework revision 8fe7655ed2 (12 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/lvelloso/Android/Sdk/
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /home/user_directory/Android/Sdk
    • Java binary at: /home/lvelloso/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/lvelloso/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • moto g stylus • N2PZ050111 • android-arm64  • Android 10 (API 29)
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

Any help would be appreciated. Thank you.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by Yke222** [comment]
Here we have the following screenshots from iOS devices:

![ios_1](https://user-images.githubusercontent.com/15067494/87428318-8e48a000-c5b8-11ea-9684-e042acb35c1a.jpg)

------------------------------------------------------------- // ---------------------------------------------------------------

![ios_2](https://user-images.githubusercontent.com/15067494/87428430-b59f6d00-c5b8-11ea-9fb3-57c6488cd852.jpg)


Thanks.

**Comment by zeevgrim** [comment]
having the same issue 
any updates on this?

**Comment by Yke222** [comment]
Also this same behavior is registered on Firefox for android, the video keeps loading eternally.

**Comment by Yke222** [comment]
Any updates on this item?

**Comment by Yke222** [comment]
Hello @zeevgrim, for now the only way I was able to achieve the correct behavior is by using the following code:

https://github.com/Yke222/video-element/blob/master/lib/main.dart

Good luck.

**Comment by Gicminos** [comment]
I have the same problem. I do not think that @Yke222 workaround should hold off this issue to be solved.

I am really confused on why video_player infinite load on iOS while on Android works fine!

**Comment by maheshmnj** [comment]
Hi @Yke222,
Thanks for filing the issue, is this still valid?  I could see the example working fine in both IOS and Android with the latest plugin ```video_player: ^2.1.6``` on the latest stable channel. I would request you to upgrade to latest stable version  of flutter and verify the issue. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
