### ISSUE TITLE
[webview_flutter]click input in H5 page，H5 page will flash when keyboard show in Android

### ISSUE THREAD

**Issue by taoliuer** [flutter/flutter#61412]
## Steps to Reproduce

1. enter H5 page in Android.
2. click input in H5 page 
3. H5 page will flash when keyboard show

**Expected results:** H5 page won't flash when keyboard show in Android

**Actual results:** H5 page will flash when keyboard show in Android

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @taoliuer,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by taoliuer** [comment]
Hi @darshankawar 

flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [鐗堟湰 6.1.7601], locale zh-CN)
    • Flutter version 1.17.5 at D:\flutter
    • Framework revision 8af6b2f038 (13 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\program files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\program files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • JSN AL00a • 7XBRX18B09005173 • android-arm64 • Android 9 (API 28)

• No issues found!


reproducible code sample：

  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text("WebView"),
      ),
      body: WebView(
        initialUrl: "https://github.com/login",
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
  }

This problem may be only appears in Huawei：
Honor 8X and Huawei P20（reproduce）
One plus 5（not reproduce）

[issue_video.zip](https://github.com/flutter/flutter/files/4917256/issue_video.zip)

**Comment by darshankawar** [comment]
Hi @taoliuer,
I couldn't replicate this issue on Samsung devices I tried. May be as you said, it's specific to Huawei devices.
I see a similar open issue related to webview keyboard issues on Huawei devices, [61085](https://github.com/flutter/flutter/issues/61085).
Closing this as duplicate.  If you disagree, write in comment and I'll reopen it.
Thanks.

**Comment by ChorKiuYI** [comment]
@taoliuer Did you solve this problem,i have the same problem,when soft keyboard show or hide,the page will flash

**Comment by tryroach** [comment]
@taoliuer @ChorKiuYI I hava the same problem, Did you have any solutions , please share to me, thx!!!
