### ISSUE TITLE
How to implement the android.settings.WIFI_ADD_NETWORKS Intent

### ISSUE THREAD

**Issue by OmarACY** [flutter/flutter#61414]
How to implement the android.settings.WIFI_ADD_NETWORKS intent, 
I can't implement because the arguments needs to parceable list into android.provider.extra.WIFI_NETWORK_LIST and
i don't know how to use that, could you help me please

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
