### ISSUE TITLE
═══ Exception caught by rendering library ═════════════════════════════════════════════════════ The following assertion was thrown during paint(): 'package:flutter/src/material/material.dart': Failed assertion: line 609 pos 12: 'referenceBox.attached': is not true.

### ISSUE THREAD

**Issue by phoenixsachin** [flutter/flutter#61428]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @phoenixsachin, 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue you are facing ?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
