### ISSUE TITLE
I have to start the start again after adding a dependency.

### ISSUE THREAD

**Issue by DeVil2O** [flutter/flutter#61422]
When I add a dependency in the app I have to again run the command "flutter run". The app does not work fine on reload and restart.

**Comment by darshankawar** [comment]
Hi @DeVil2O,
Ideally when you add a dependency, you run `flutter pub get` that installs all the references of the plugin. Before you do that, you should first stop the app instance, run above command followed by `flutter run`. Once you have imported the said plugin in your main file then your app should behave properly on `hot reload` and `hot restart`.
You may also try to run `flutter pub repair cache` and then `flutter run`.

If the problem still persists, provide your `flutter doctor -v` and a minimal complete reproducible code sample along with the dependency that is causing this issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
