### ISSUE TITLE
[engine] New Embedding package - Differences in FlutterActivity and FlutterFragmentActivity 

### ISSUE THREAD

**Issue by awanishraj** [flutter/flutter#61429]
FlutterActivity and FlutterFragmentActivity are supposed to have the same functionality, but I noticed some differences related to plugin registration. Listing those below:

In [io.flutter.embedding.android.FlutterActivity.java](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java)

```java
@Override
public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
  registerPlugins(flutterEngine);
}
```

Whereas in [io.flutter.embedding.android.FlutterFragmentActivity.java](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java)

```java
@Override
public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
  // No-op. Hook for subclasses.
}
```

This leads to no plugin registration if FlutterActivity in simply replaced with FlutterFragmentActivity

**Comment by xster** [comment]
Dupe to https://github.com/flutter/flutter/issues/54386
