### ISSUE TITLE
Flutter Driver dependencies for meta should support the latest version of meta

### ISSUE THREAD

**Issue by ram231** [flutter/flutter#61427]
Flutter Driver depends on `meta: ^1.1.8` and the current version is `meta: ^1.2.2`.

**Steps to reproduce**
> pubspec.yaml
1. add `flutter_driver` sdk
2. add `meta:^1.2.2`
3. run flutter pub get

**Output**
```sh
Because every version of flutter_driver from sdk depends on meta 1.1.8 and flutter_example depends on meta ^1.2.2, flutter_driver from sdk is forbidden.

So, because flutter_example depends on flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because flutter_example depends on flutter_driver any from sdk, version solving failed.)
exit code 1

```

**Comment by jonahwilliams** [comment]
The latest versions of flutter use the latest versions of meta. If a dependency is updated after a stable release is cut, generally the next stable will have that dependency
