### ISSUE TITLE
[Flutter 1.17.5] Cannot integrate AAR into my Android project

### ISSUE THREAD

**Issue by caik13** [flutter/flutter#61432]
I follow the instructions in the document. [Add Flutter to existing app](https://flutter.dev/docs/development/add-to-app/android/project-setup)    

Step 1.   use command ```flutter create -t module --org com.example my_flutter```
Step 2.   create my Android project
Step 3.   set java 8
Step 4.   use Option A - Depend on the Android Archive (AAR)    

I found that AAR was integrated into the my Android project,And the compiler passed.    
But. When [add-flutter-fragment](https://flutter.cn/docs/development/add-to-app/android/add-flutter-fragment?tab=add-fragment-java-tab),     not found FlutterFragment.    
![image](https://user-images.githubusercontent.com/5214493/87406866-f072c680-c5f3-11ea-9a0f-b2a659b72edb.png)    

When I'm in the flutter-module project build apk, I found it in APK io.flutter.embedding. But not in AAR.    
Please help me, thank you!

**Comment by TahaTesser** [comment]
Hi @caik13 
Just tried to reproduce the issue, no problem when using `FlutterFragment`, make sure you to `FragmentActivity` and not `AppCompatActivity`

Please check the sample i have attached with module and android app

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10 (API
      29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5.1

• No issues found!

```

</details> 

[test_fragment.zip](https://github.com/flutter/flutter/files/4919697/test_fragment.zip)

**Comment by caik13** [comment]
@TahaTesser  Thank you very much. 
I tried it with your demo and it worked. Then I tried my own code again, and miraculously it worked.
It may be caused by a problem with my network
Thank you!
