### ISSUE TITLE
Request for a callback with information regarding the chosen share channel.

### ISSUE THREAD

**Issue by shaun0203** [flutter/flutter#61431]
## Use case

I would like to get the channel that was selected to share, back to the flutter application after using the share package call. 

Using mixpanel analytics, I need to report the app/channel that was used to share, in order for my client to understand how the users are sharing info with the app.

## Proposal

It would be handy to have the name of the app ie. 'Email', 'Whatsapp' etc, returned as a string, in a callback after sharing.

**Comment by TahaTesser** [comment]
Hi @shaun0203 
Can you please give us some reference that is already possible to do on Android and iOS? Some examples
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
