### ISSUE TITLE
Atom+Flutter cleaner error message 

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#6143]
## Steps to Reproduce
1. Setup a new project.
2. Hit run. 
3. Receive bacon.
4. Go for coffee. 
5. Come back. 
6. Don't notice it is still running.
7. Hit run.
8. Receive bacon... I mean.. "dart exception" error message in the top right that doesn't really make sense.
9. Hit run again.
10. Same error message.
11. Realize you're an idiot and hit stop.
12. Hit run again
13. Receive bacon!
## Flutter Doctor

super fresh install.
## What I would have liked

An good error message with "you're an idiot and it is already running", or some other notification like the run button being green (active)?

**Comment by cbracken** [comment]
@devoncarew @danrubel

**Comment by eseidelGoogle** [comment]
Atom is no longer our recommended editor.  The behavior in IntelliJ should be at least different now. :)  Closing.
