### ISSUE TITLE
Request: a flutter team official permission handler plugin

### ISSUE THREAD

**Issue by gkrawiec** [flutter/flutter#61444]
Managing permissions across all android and ios versions has become quite complex due to the variety of changes through each new version. There are a few pub.dev plugins but none work correctly or are maintained. Please provide an  official solution maintained by the flutter team.

**Comment by ened** [comment]
permission_handler is well maintained https://pub.dev/packages/permission_handler

**Comment by gkrawiec** [comment]
> permission_handler is well maintained https://pub.dev/packages/permission_handler

Nope, not anymore. Look at the issue list and the dates of PRs.

**Comment by stuartmorgan** [comment]
The plugin mentioned above appears to be actively developed based on recent commits, and is very popular based on pub.

Competing with a well-established, maintained plugin is not a good use of the Flutter team's limited resources, so this isn't a space we would get into.
