### ISSUE TITLE
[Android HUAWEI P30] TextField and the keyboard cannot pop up

### ISSUE THREAD

**Issue by wang409205743** [flutter/flutter#61446]
```
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (2 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

On the login page, switch textfield to get the focus in turn. the security keyboard pops up when the password type Textfield gets the focus. when you click other TextField and the keyboard cannot pop up

**Comment by wang409205743** [comment]
Need to click textfield again to pop up the keyboard

**Comment by TahaTesser** [comment]
Hi @wang409205743 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by wang409205743** [comment]
LSCNM598054:flutter_explam qxx2412$ flutter doctor -v 
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G5033, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/qxx2412/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at /Users/qxx2412/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
LSCNM598054:flutter_explam qxx2412$

**Comment by TahaTesser** [comment]
Hi @wang409205743 
Thanks for providing details, Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by wang409205743** [comment]
No example is needed, as long as there are multiple textfields in a page and one of the textfields sets obscureText to true.
 
like this:
 body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[

          TextField(
              autofocus: false,
              keyboardType: TextInputType.text,
            ),
            TextFormField(
              autofocus: false,
              obscureText: true,
            ),
          ],
        ),
      ),

**Comment by wang409205743** [comment]
I went to see the source code of Flutte and modified it 
as follows：

old:
void requestKeyboard() {
    if (_hasFocus) {
      _openInputConnection();
    } else {
      widget.focusNode.requestFocus();
    }
  }

new:

void requestKeyboard() {
    if (_hasFocus) {
      _openInputConnection();
    } else {
      widget.focusNode.requestFocus();
    _openInputConnection();
    }
  }

After the change, it will be normal，

**Comment by TahaTesser** [comment]
Issue isn't reproducible on Samsung 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (4 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by wang409205743** [comment]
@TahaTesser Yes, it's normal on Samsung and IOS，But HUAWEI's mobile phone performance is abnormal.I found that the password keyboard and ordinary keyboard are not the same in Huawei. 
So I guess when it is displayed as a password keyboard, clicking other textfields to get focus may not pop up a normal keyboard, and you need to click textfield again to respond _Openinputconnection() method to pop up keyboard.

**Comment by wang409205743** [comment]
@GaryQian Thanks for you help.

**Comment by GaryQian** [comment]
Looks like the problem here is that the the focus is not being shifted. If the focus is properly obtained, the _openInputConnection() call is automatically made, but it is not succeeding. Will need to investigate more, as simply calling _openInputConnection directly after requesting focus is not always safe as the focus would not have moved yet.

**Comment by wang409205743** [comment]
Thank you for your explanation, I wonder if this issue will be dealt with in future versions?

**Comment by wang409205743** [comment]
@GaryQian I add this code:

Listener(
              onPointerDown: (evnet){
                FocusScope.of(context).requestFocus(_phoneNumberFocus);
              },
              child:  TextField(
                autofocus: false,
                keyboardType: TextInputType.text,
                decoration: InputDecoration(suffix: Icon(Icons.search)),
                focusNode: _phoneNumberFocus,
              ),
            ),

it will be normal

**Comment by KouYiGuo** [comment]
The **TextField**'s behavior on Huawei mobile phone is strange. Sometimes the keyboard won't popup. And sometimes the keyboard type is not right. For example, I set the **TextField** keyboardType is ```TextInputType.number```, but it show me a text keyboard, wtf?
My colleague find a method to solve this. The solution is
1. release the textfield focus;
2. request the focus again later.

Here is our demo code.
```dart
import 'package:flutter/material.dart';
import 'package:xxxx/system_info.dart';

class SafeTextField extends StatelessWidget {
  final TextField textField;
  final FocusNode? focusNode;

  const SafeTextField({required this.textField, required this.focusNode})
      : super();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<bool>(
      future: _isHuawei(),
      builder: (ctx, snapshot) {
        if (snapshot.hasData) {
          if (snapshot.data!) {
            return _SafeTextField(textField: textField, focusNode: focusNode);
          }
        }
        return textField;
      },
    );
  }

  Future<bool> _isHuawei() async {
    final info = await SystemInfo().deviceInfo();
    return info.brand.toLowerCase() == 'huawei';
  }
}

class _SafeTextField extends StatefulWidget {
  final TextField textField;
  final FocusNode? focusNode;

  const _SafeTextField({required this.textField, required this.focusNode})
      : super();

  @override
  _SafeTextFieldState createState() => _SafeTextFieldState();
}

/// 华为手机上，偶有键盘首次无法唤起及键盘类型不对的情况
class _SafeTextFieldState extends State<_SafeTextField> {
  bool hasFocus = false;
  @override
  void initState() {
    widget.focusNode?.addListener(() {
      if (widget.focusNode!.hasFocus && !hasFocus) {
        hasFocus = false;
        if (WidgetsBinding.instance != null) {
          FocusScope.of(context).unfocus();
          WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
            hasFocus = true;
            FocusScope.of(context).requestFocus(widget.focusNode!);
          });
        }
      } else {
        hasFocus = false;
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    widget.focusNode?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.textField;
  }
}

```

**Comment by TahaTesser** [comment]
@KouYiGuo 
This issue i closed, can you please file a new issue

**Comment by KouYiGuo** [comment]
@TahaTesser
I think it's no need to file a new issue.
It's a problem of Huawei, perhaps they modify the standard android input behavior, whatever.
The TextField's strange behavior is reproducible on  Huawei device, if you could find one.

**Comment by franticn** [comment]
same issues in OPPO and VIVO mobile when enable security keyboard
