### ISSUE TITLE
How to get all the .pdf and the .epub files across the device storage in Flutter?

### ISSUE THREAD

**Issue by dhinesh-venkat** [flutter/flutter#61448]
I'm trying to create an epub reader app.

On the Homepage, I am trying to list the books with a Horizontal scroll view of the book covers.

For that, I need all the local pdf and epub files. How can I do that efficiently?

Thanks.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
