### ISSUE TITLE
Create a new Flutter Application

### ISSUE THREAD

**Issue by InspiredPrynce** [flutter/flutter#61453]
_**The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified.**_

This is what I get whenever i try creating a flutter project in **Android Studio Events**, it just redirects me to the home page.

**Comment by VladyslavBondarenko** [comment]
@InspiredPrynce 
it should be solved by adding flutter to your Path
https://flutter.dev/docs/get-started/install/windows#update-your-path
or https://flutter.dev/docs/get-started/install/macos#get-sdk
or https://flutter.dev/docs/get-started/install/linux#get-sdk
Please comment if it doesn't help

**Comment by InspiredPrynce** [comment]
@VladyslavBondarenko i added it in my path yet i keep getting same error

**Comment by VladyslavBondarenko** [comment]
@InspiredPrynce 
what platform are you on?
is the flutter command recognised in terminal?

**Comment by InspiredPrynce** [comment]
@VladyslavBondarenko am on windows...

I keep getting this when i run `flutter --dev`

_**The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified. Error: Unable to find git in your PATH.**_

I have added flutter to the path, and GIT is installed and running in the shell properly.

**Comment by YazeedAlKhalaf** [comment]
@InspiredPrynce 

Can you provide your platform, OS?
And also `flutter --dev` is not a command.


try:

1. `flutter doctor -v`

Can you provide the way you added flutter to PATH

**Comment by SANSKARJAIN2** [comment]
> @VladyslavBondarenko am on windows...
> 
> I keep getting this when i run `flutter --dev`
> 
> _**The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified. The system cannot find the path specified. Error: Unable to find git in your PATH.**_
> 
> I have added flutter to the path, and GIT is installed and running in the shell properly.

Hi @VladyslavBondarenko 

Can you check whether "where" command is present in your system path
you can do by either checking the system32 path in system Environment Variables or
run the following command
where flutter
1. If it does not return the flutter directory then flutter is not listed properly in the environment variables
2. if it returns an error then add the path of system32 in the system environment variables which will run this command
I hope this will solve your issue.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
