### ISSUE TITLE
RichText does not scale with Accessibility text size

### ISSUE THREAD

**Issue by jayabrown** [flutter/flutter#61452]
## Steps to Reproduce

Two previous issues have been filed, simply reopening here.

When the text scale is changed in Accessibility settings, `RichText` does not scale with the other text widgets.  Set the theme with just a color here to make sure it was picking up the right theme.

```
theme: ThemeData(
        textTheme: TextTheme(
          bodyText2: TextStyle(color: Colors.brown)
        )
      )
```

`Text("Here is some text. [Text]", style: Theme.of(context).textTheme.bodyText2),`
`RichText(text: TextSpan(text: "Here is some text. [RichText]", style: Theme.of(context).textTheme.bodyText2)),`
`Text.rich(TextSpan(text: "Here is some text. [Text.rich]", style: Theme.of(context).textTheme.bodyText2)),`

Original:
![Screen Shot 2020-07-14 at 10 26 53 AM](https://user-images.githubusercontent.com/3712265/87437598-8b4fae80-c5bc-11ea-8fa5-d7bbb4c7533e.png)
With Accessibility font size increased:
![Screen Shot 2020-07-14 at 10 28 42 AM](https://user-images.githubusercontent.com/3712265/87437842-cce05980-c5bc-11ea-9321-7bb7dfe9bab9.png)

I'm able to switch everything to `Text.rich` just fine, but it's unclear to me if this is intended behavior for `RichText`. 

Previous Issues: 
#14675 
#41549

Tested on iPhone 8, iPhone X, and Google Pixel 3. (Screenshots from Google Pixel 3)

```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.3.pre at /Users/xxx

/Documents/Flutter/flutter
    • Framework revision 8fe7655ed2 (13 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 8 • xxx • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
```

</details>

**Comment by jonahwilliams** [comment]
This is the intended behavior of RichText. It would be more accurately named something like "RawText", because it is not connected to anything by default, and should only be used when you want to do everything manually.

Text.rich is a reasonable approach for applications to use

**Comment by jayabrown** [comment]
Thanks for the clarification.
