### ISSUE TITLE
Flutter web tests are crashing Chrome, then timing out on CI builder

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#61462]
The Dart team's integration test builder for flutter/engine/dart tip-of-tree has started throwing an exception from Chrome, then timing out on all tests after that, taking 12 minutes to time out, which makes the builder take an extra half hour.

I'm not sure whether a change in our Chrome version is doing that, or some change in Flutter.
We need to get the web tests passing, to turn the builder green, and also to fix this time regression.

The builder is at https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux
and a failing build is at: https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux/11234

The step is "flutter test web_tests", and it takes 90 minutes when it fails due to this Chrome crash and timeouts, 60 minutes when passing.

I am just about to update the checked-in version of Chrome the Dart builders use to run tests.  I don't know if this will change
the version used by this builder, I can look into it.

However, a new, passing build has finished since I started writing this issue.  Is there a fix that has landed for this problem in that blamelist, or could this still be a flaky problem we need to fix?

```

02:34 +354 ~3: loading /b/s/w/ir/cache/builder/flutter/packages/flutter/test/cupertino/app_test.dart                                                                                                   [+16799 ms] Serving tests at http://localhost:36567/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A36567%2F36&debug=false
[  +99 ms] [CHROME]:Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

02:34 +354 ~3 -1: loading /b/s/w/ir/cache/builder/flutter/packages/flutter/test/cupertino/app_test.dart [E]                                                                                            
  Failed to load "/b/s/w/ir/cache/builder/flutter/packages/flutter/test/cupertino/app_test.dart":
  Unable to connect to Chrome debug port: 34483
   SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 34856
  package:flutter_tools/src/base/common.dart 14:3                throwToolExit
  package:flutter_tools/src/web/chrome.dart 302:9                ChromiumLauncher._connect
  ===== asynchronous gap ===========================
  dart:async/future.dart 279:46                                  new Future.error
  package:test_core/src/runner/loader.dart 246:26                Loader.loadFile.<fn>
```
<!-- Thank you for using Flutter!

**Comment by yjbanov** [comment]
I've seen this when we ask a single shard to run too many tests. That's why we implemented a sharding strategy. Perhaps it's time we increased the shard count for web tests.

@whesse How many shards does your builder split the web tests into? What happens if you add 2-4 more shards?

**Comment by whesse** [comment]
We are sharding into 8 shards, so the biggest ones are running around 1,000 tests.

I see that this is the default, and we would set "WEB_SHARD_COUNT" to something higher to fix this.
But one of the failures I see had this happening only after about 350 tests, so wouldn't we need to increase this number a lot?

I can do a test (a led run of a modified version of the recipe) to see how it works if I double the shard count.

**Comment by nturgut** [comment]
@whesse How are the results for the second run with more shards?

**Comment by whesse** [comment]
The test run was successful, with 16 shards rather than 8, and took about 5 minutes longer: 65 minutes instead of 60 minutes.
The CL to change the number of shards is https://dart-review.googlesource.com/c/recipes/+/154500, and it will be landed when approved.  The number of tests per shard went down from over 1000 to about 500, so that may help.

I also will change the version of Chrome from 81 to 84 in this CL, since I have just uploaded Chrome 84 to cipd.

**Comment by yjbanov** [comment]
> The test run was successful, with 16 shards rather than 8, and took about 5 minutes longer: 65 minutes instead of 60 minutes.

The shards are meant to run in parallel, so increasing the number should actually reduce the total run time. Do you run test shards serially?

**Comment by whesse** [comment]
Our triple-head flutter-engine builder runs on only one bot, so everything is serial.  It has an extremely long cycle time, but we haven't wanted to let it use up more of our pool of builders. Any changes to that would be a strategy decision about tradeoffs.  We have dealt with the long cycle times by supporting bisection runs.  We certainly can't run on every commit - that would take too many resources.

**Comment by nturgut** [comment]
@whesse Looks like there were successful web test runs. Shall I close this issue?

**Comment by whesse** [comment]
Yes.  The problem is that there were sporadic failures on the flutter web tests step, not that it failed every time.  But the failures seem to have disappeared.
