### ISSUE TITLE
Animated Gif are not restarted if the widget get redraw

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#61467]
The use case
Show an error page with an animated GIF.

The first time the GIF is loaded it work as expected.  But if you redraw the page...the GIF seems to be stuck on a frame.
No error message, no nothing.

So the WORKAROUND is to call evict()...but that's defeating the purpose of caching.
Image(image: new AssetImage("assets/images/ezgif.gif")..evict())

My guess is that is something related to the caching of the image !

**Comment by darshankawar** [comment]
Hi @wer-mathurin,
Can you please provide `flutter doctor -v`, a minimal complete reproducible code sample that shows the issue along with the sample gifs that you are using.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
