### ISSUE TITLE
Row MainAxisSize.min is getting ignored. MainAxisSize.max is enforced

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#61468]
## Steps to Reproduce

1. Run code below

```
import 'package:flutter/material.dart';

class RowInsideExpanded extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(
              width: 1.0,
            ),
          ),
          width: 200.0,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _buildChip('short'),
              SizedBox(
                height: 5,
              ),
              _buildChip('looooooooooooooooooooooongg'),
            ],
          ),
        ),
      ),
    );
  }

  _buildChip(String s) {
    return Row(
      children: [
        Container(
          color: Colors.red,
          width: 15,
          height: 15,
        ),
        Expanded(
          child: Container(
            color: Colors.greenAccent,
            child: Row(
              mainAxisSize: MainAxisSize.min, // this is ignored
              children: <Widget>[
                SizedBox(
                  width: 5.0,
                ),
                Flexible(
                  fit: FlexFit.loose,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 8.0),
                    child: Text(
                      s,
                      softWrap: false,
                      overflow: TextOverflow.fade,
                      style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold, fontSize: 16.0),
                    ),
                  ),
                ),
                SizedBox(
                  width: 5.0,
                ),
                Container(
                  decoration: BoxDecoration(
                    color: Colors.grey,
                    shape: BoxShape.circle,
                  ),
                  child: Icon(Icons.close),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
```

2. You can run it on Flutter DartPad

**Expected results:** 

The inner Row should wrap its content 
**Actual results:** 

The background color shows clearly that it tries to match the parent width instead even though     `mainAxisSize: MainAxisSize.min` is already set

![image](https://user-images.githubusercontent.com/29230303/87461901-275ed180-c620-11ea-8187-19899516fbb1.png)

<details>
  <summary>Logs</summary>

```
```

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18362.900], locale en-MU)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.43.2)
[√] Connected device (3 available)

```
```

</details>

**Comment by darshankawar** [comment]
Hi @tolotrasamuel,
Inside `_builtChip()` method I see that you have wrapped the concerned Row with `Expanded`.  This widget (Expanded) by default takes all the space as prescribed by it's child (Row in this case) and hence the `mainAxisSize:min` is ignored. 
If you replace `Expanded` with `Flexible`, then you'll see that the `Row` takes only the required space, as shown below:

![61468](https://user-images.githubusercontent.com/67046386/87514932-a7288280-c698-11ea-8aaa-af8d65ac4804.png)

**Comment by tolotrasamuel** [comment]
Thank you. This also helped me https://stackoverflow.com/questions/62901014/how-to-prevent-row-from-taking-all-available-width
