### ISSUE TITLE
Pick image error when app downloaded from Play Store

### ISSUE THREAD

**Issue by ValentineChisango** [flutter/flutter#61469]
I am using an ImagePicker in my app. When debugging on my phone, the ImagePicker works fine with no issues. However, once I publish the app and download it from the Play Store, I (and all users I have spoken to) keep getting this error:

> Pick image error: PlatformException(already_active, Image picker is already active, null)

I am using the following versions:
`image_picker: ^0.6.7+2`
`Flutter 1.17.2`
`Dart 2.8.3`

Has anyone experienced this before / does anyone know how I might resolve this error?

**Comment by darshankawar** [comment]
Related to [36529](https://github.com/flutter/flutter/issues/36529) and [19103](https://github.com/flutter/flutter/issues/19103)

**Comment by darshankawar** [comment]
Hi @ValentineChisango,
Can you try [this](https://github.com/flutter/flutter/issues/19103#issuecomment-412647536) solution and see if it works ?

**Comment by ValentineChisango** [comment]
I did all mode in Dart so my Android MainActivity is empty. Not sure how to try that solution unfortunately

**Comment by darshankawar** [comment]
Hi @ValentineChisango,
I see there's a similar open issue describing your case, [40339](https://github.com/flutter/flutter/issues/40339) and [this](https://github.com/flutter/flutter/issues/40339#issuecomment-531248197) comment looks similar to the one you are facing now. 
I'd suggest you follow-up there for updates on the issue.
I am going ahead and closing this as a duplicate.  If you disagree, write in the comments and I'll reopen.
Thanks.
