### ISSUE TITLE
time slot for book appointment 

### ISSUE THREAD

**Issue by Git-Mani** [flutter/flutter#61472]
how to create time slot for booking app?? user pick one of time from slot which suit him.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
