### ISSUE TITLE
unable to run on Android 6.0 after 7b77c0acedf708749b68304cc5f0ac469c9d7136

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#6149]
## Steps to Reproduce

Trying to run any application on Android 6.0 phone leads to 

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.yourcompany.microbenchmarks-2/lib/arm/libsky_shell.so"
```

Reverting 7b77c0acedf708749b68304cc5f0ac469c9d7136 and building a local engine fixes this issue.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel unknown)
    • Flutter at /usr/local/google/home/vegorov/src/flutter-clean/flutter
    • Framework revision 3b952d8456 (10 hours ago), 2016-09-29 22:47:20
    • Engine revision 71f2871f00
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/vegorov/tools/android-sdk-linux
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

[✓] Connected devices
    • Nexus 5X • 00bbd0419fc34dcd • android-arm
```

/cc @chinmaygarde

**Comment by abarth** [comment]
We saw a similar error on the buildbot, but I thought @chinmaygarde fixed the issue.

**Comment by chinmaygarde** [comment]
Looking into this now. `__aeabi_memcpy` should be required for ABI compliance. Digging through the Bionic sources, it seems to be available. But in the history of [`__aeabi.c`](https://github.com/android/platform_bionic/blob/master/libc/arch-arm/bionic/__aeabi.c) I did notice a reference to this [bug](https://android-review.googlesource.com/#/c/195350/) which is what we may be running into. Does this happen on Android M only? I have a couple of device but neither are on M. Upgrading one right.

**Comment by chinmaygarde** [comment]
Switching to NDK platform level 22 in https://github.com/flutter/buildroot/blob/5756632bcf0c7636c53c9d84cb62813cc97c92dd/build/config/android/config.gni#L97 will fix this issue.

**Comment by abarth** [comment]
I can repro.  Attempting @chinmaygarde 's suggested fix.

**Comment by abarth** [comment]
Seems to work.  Posting patch.

**Comment by yjbanov** [comment]
Reopening since this is only fixed in engine but not in this repo.

**Comment by yjbanov** [comment]
Undo auto-close again.

**Comment by yjbanov** [comment]
We're green again!
