### ISSUE TITLE
[web] Migrate web analysis tests from Cirrus to LUCI

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#61493]
PART1: Add script to run web_analysis.
PART2: Change LUCI recipe to run web_analysis checks 
PART3: Cleanup this step from Cirrus file.

**Comment by nturgut** [comment]
First step is here: https://github.com/flutter/engine/pull/19726

**Comment by yjbanov** [comment]
@nturgut I optimistically set the P3 label for this, but feel free to adjust accordingly.
