### ISSUE TITLE
Flat buttons are supposed to have a 48px high tap target

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#615]
https://www.google.com/design/spec/components/buttons.html#buttons-usage

Right now, we don't enforce the 6px top and bottom margins.
Also, we don't tap target in that region like the spec says we should.

**Comment by abarth** [comment]
Do you know how the slashes are supposed to work when you tap outside the visual bounds of the button?  Should the splash start at the closest point inside the button?  Should the splash originate from a point that's clipped by the button's visual bounds?  Should the splash be omitted?

**Comment by Hixie** [comment]
The spec doesn't say.

**Comment by abarth** [comment]
We should experiment with other implementations and/or ask the spec authors.  This issue is what blocked me from solving this problem before.

**Comment by Hixie** [comment]
I've sent a question to the material design team about this.

**Comment by sethladd** [comment]
Did we ever get an answer?

**Comment by Hixie** [comment]
We got several. Fundamentally there's no good answer because this is a non-physical interaction (tapping just outside the button triggering a button press). I think the best compromise between implementation complexity and quality of experience here is for the splash to start at the edge of the button nearest the actual tap point. It'll feel like you hit the button with the side of your finger and that's what triggered it.

**Comment by Hixie** [comment]
This is on our radar for the coming months.
