### ISSUE TITLE
The integer literal 9223372036854775807 can't be represented exactly in JavaScript, flutter build error

### ISSUE THREAD

**Issue by akshayru** [flutter/flutter#61500]
## Steps to Reproduce

1. run flutter build web
2. code try to compile and then throws below error.
```
Target dart2js failed: Exception: /C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-3.4.0+1/lib/src/X509Certificate/asn1_decoder.dart:163:25:
Error: The integer literal 922337203685477580 can't be represented exactly in JavaScript.
    int int64MaxValue = 922337203685477580;
                        ^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

## Logs

```
```

![image](https://user-images.githubusercontent.com/17482625/87488485-5b70cd00-c5f5-11ea-9d4b-fee6ee05403d.png)

```
```

**Comment by jonahwilliams** [comment]
This is not a bug with flutter see: https://api.dart.dev/stable/2.8.4/dart-core/int-class.html

> Note: When compiling to JavaScript, integers are restricted to values that can be represented exactly by double-precision floating point values. The available integer values include all integers between -2^53 and 2^53, and some integers with larger magnitude. That includes some integers larger than 2^63. The behavior of the operators and methods in the int class therefore sometimes differs between the Dart VM and Dart code compiled to JavaScript. For example, the bitwise operators truncate their operands to 32-bit integers when compiled to JavaScript.


You might try using a BigInt class: https://api.dart.dev/stable/2.8.4/dart-core/BigInt-class.html

**Comment by akshayru** [comment]
@jonahwilliams are you suggesting me to update flutter web file? This error is something in Flutter SDK Web folder not my project file.
