### ISSUE TITLE
A `testWidgets` alternative working for lower level compatibility 

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#61511]
Currently `testWidgets` is providing `WidgetTester` as the solution for driving the test. 

`WidgetTester` is a good infrastructure for unit test, but may have been too complicated and at a too high level for implementing all the tests we need. Meanwhile we have `LiveWidgetController` which is a minimal implementation for `WidgetController` and is used internally in `flutter_driver`. 

`WidgetController` may be a better interface for controlling the app on performance/integration test: 
- `WidgetController` is the base class, meaning the testing code will be able to run for all our current testing tools: `flutter_test`/`WidgetTester`, `flutter_drive`, `e2e` or even the real release app. This will be extremely helpful for running shader warmup on the user's device.
- This is feasible because extra features provided by `WidgetTester` and its test bindings, except for some convenience wrap of driving a test, are most likely not necessary, and sometimes even harmful (e.g. #60739) for performance test. 

One way to implement it is to provide a `testWidgets`  alternative, which restrict its callback to only use `WidgetController` rather than `WidgetTester`. Meanwhile, some wraps of driving the test provided by `WidgetTester` should not have difficulties promoted to `WidgetController`, e.g. `WidgetTester.ensureVisible`.

**Comment by CareF** [comment]
The idea credit to @liyuqian

**Comment by TahaTesser** [comment]
Sounds like proposal for alternative, added `proposal`

**Comment by CareF** [comment]
A demo https://github.com/CareF/flutter_perf_widget_demo 
@liyuqian @albertwang0116 @dnfield
