### ISSUE TITLE
Input issue when Webview contains TextField

### ISSUE THREAD

**Issue by liruibao** [flutter/flutter#61512]
When there is an edit box on the page, the keyboard pops up, select the number, the content is selected for the first time but there is no input on the screen, you can use the google homepage to test

**Comment by darshankawar** [comment]
Hi @liruibao,
Can you please specify which device are you trying on along with `flutter doctor -v` ?

**Comment by liruibao** [comment]
huawei p 40

Framework revision 37fc9eaabf (5 hours ago), 2020-07-20 16:34:05 +0800
    • Engine revision e683684044
    • Dart version 2.7.0



[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bytedance/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/bytedance/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.




[✓] Connected device (1 available)
    • ANA AN00 • VEG0220410003430 • android-arm64 • Android 10 (API 29)

**Comment by darshankawar** [comment]
Hi @liruibao,
I see there's similar open issue related to webview keyboard and input on Huawei devices, [61085](https://github.com/flutter/flutter/issues/61085).
I'd suggest you follow up there for updates. Closing this as duplicate. If you think otherwise, write in comments and I'll reopen.
Thanks.
