### ISSUE TITLE
codemagic:  File name too long (in target 'Runner' from project 'Runner'), when generating a debug iOS app

### ISSUE THREAD

**Issue by imabhishekkumar** [flutter/flutter#61526]
I tried to create a debug app for iOS for my project using codemagic. I'm getting this error.

**Actual results:** 
`error: make directory /Users/builder/clone/build/ios/Debug-iphoneos/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app: File name too long (in target 'Runner' from project 'Runner')
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description`

`

> [√] Flutter (Channel master, 1.20.0-8.0.pre.75, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
>     • Flutter version 1.20.0-8.0.pre.75 at C:\Flutter SDK\flutter
>     • Framework revision bb3280885c (34 hours ago), 2020-07-13 16:28:27 -0700
>     • Engine revision f10f172573
>     • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)
> 
>  
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\abhis\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 46.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.47.0)
>     • VS Code at C:\Users\abhis\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.12.2
> 
> [√] Connected device (2 available)
>     • Web Server (web) • web-server • web-javascript • Flutter Tools
>     • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116
> 
> ! Doctor found issues in 1 category

.`

</details>

**Comment by TahaTesser** [comment]
Hi @imabhishekkumar 
For Codemagic related issues, please join there [Slack](https://join.slack.com/t/codemagicio/shared_invite/enQtNzQyODExMTQyMDcwLTQ2NTJjODE3NTA2Njg3Y2ViYmZiNGE1MWMyYWNjY2I0MzRmM2M2YmZhOTE1YTc5YjNkMmI0MzQzZWU0MzA4OGM)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by marcoberetta96** [comment]
@TahaTesser same issue, but the Slack link is not available

**Comment by TahaTesser** [comment]
@marcoberetta96 
Updated the invite link https://github.com/flutter/flutter/issues/61526#issuecomment-658676152
