### ISSUE TITLE
Backspace in text input is broken

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#6152]
1. Go to the Text Fields demo in the Gallery app.
2. Type "hello world".
3. Position your cursor on the space (before or after).
4. Hit backspace.
5. See extra word appear.

Most likely an engine bug.

**Comment by mpcomplete** [comment]
This repros on my Nexus 5X, but not on my OnePlus One.

**Comment by mpcomplete** [comment]
One potentially important difference: on my Nexus 5X, when moving the cursor, the composing region is empty. However, on the OnePlus One, the composing region is set to the word under the cursor (by the system?). This might have something to do with why it only happens on the Nexus 5X.

**Comment by sethladd** [comment]
Same version of Android?

**Comment by mpcomplete** [comment]
OnePlus one: android 6.0.1 on canogen 13.1.2
Nexus 5X: android 7.0 on stock android OS
