### ISSUE TITLE
Multiple Flutters

### ISSUE THREAD

**Issue by zsunkun** [flutter/flutter#61524]
Hello, our team hopes to be able to use Flutter like ordinary Android View. If I directly use multiple Engines, I may face various problems such as high memory usage, so I need other solutions, I have seen this document:https://docs.google.com/document/d/1fdKRufqUzQvERcqNIUSq-GdabXc4k8VIsClzRElJ6KY/edit#, now I want to know how the program is going?

Thanks

**Comment by TahaTesser** [comment]
Hi @zsunkun 
We  probably don't need an ope issue for asking ETA on a project 
Please see https://flutter.dev/community for resources and asking questions like this,
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wanjm** [comment]
I don't think this should be closed, as the document said, the method 4 should be provided by flutter;
