### ISSUE TITLE
[Desktop] When will Windows go to alpha with mac OS and Linux

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#61541]
Just want this issue to be for updates on the Windows Status 
🚀

**Comment by VladyslavBondarenko** [comment]
Hi @YazeedAlKhalaf 
you can watch for updates here https://github.com/flutter/flutter/wiki/Desktop-shells or in projects on flutter github like https://github.com/flutter/flutter/projects?query=is%3Aopen+windows.
Closing since flutter issues in not the best place for such questions
