### ISSUE TITLE
http.post not working- Flutter

### ISSUE THREAD

**Issue by nunomonteiro123** [flutter/flutter#61542]
hey, 

Tested around diferent types of http.post methods with body and until now i couldt get it done... 
Im kinda new to Flutter so there might me some lines of code that dont look good. 

Function to get the value from the http url
```
Future createCaminhoWS(String idkey) async {
    try {
      final http.Response response = await http.post(
        'http://github.com', //url hided for obvious reasons.
        headers: <String, String>{
          'Content-Type': 'application/json',
        },
        body: jsonEncode(<String, String>{
          'idkey': idkey,
        }),
      );

      if (response.statusCode == 201) {
        // If the server did return a 201 CREATED response,
        // then parse the JSON.
        var result = json.decode(response.body);
      } else {
        // If the server did not return a 201 CREATED response,
        // then throw an exception.
        throw Exception('Failed to load CaminhoWS');
      }
    } catch (e) {
      return showDialog(
          context: context,
          builder: (context) {
            return AlertDialog(
              title: Text("Error on Application"),
              content: SingleChildScrollView(
                child: ListBody(
                  children: <Widget>[
                    Text('Error: $e'),
                  ],
                ),
              ),
              actions: <Widget>[
                MaterialButton(
                  child: Text('Ok'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            );
          });
    }
  }
```

**Comment by VladyslavBondarenko** [comment]
Hi @nunomonteiro123 
could you provide your `flutter doctor -v` and error logs or what do you mean by "not working"?

**Comment by nunomonteiro123** [comment]
> Hi @nunomonteiro123
> could you provide your `flutter doctor -v` and error logs or what do you mean by "not working"?

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale pt-PT)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\nunom\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.1)
    • VS Code at C:\Users\nunom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

-------------------------------------------------------

The problem is that this function is not returning the value idKey that i defined.
the status code i get is 200 and not 201 so i get the 'Failed to load CaminhoWS' Exception

**Comment by nunomonteiro123** [comment]
### Solved ✅

```
import 'package:http/http.dart' as http;

Map data = {'idkey1': 1};

String body = json.encode(data);

http.Response response = await http.post(
  url: 'https://example.com',
  headers: {"Content-Type": "application/json"},
  body: body,
);

return response;
```

**Comment by KidusThethird** [comment]
I faced the same problem... i wanted to send request to my api... it works form postman but not form my flutter app.... and i added this 

headers: {"Content-Type": "application/json"}

and it worked!!

refer this ..


import 'package:http/http.dart' as http;

Map data = {'idkey1': 1};

String body = json.encode(data);

http.Response response = await http.post(
  url: 'https://example.com',
  headers: {"Content-Type": "application/json"},
  body: body,
);

return response;
