### ISSUE TITLE
Android Add2App's MouseCursorPlugin leaks the FlutterView 

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#61558]
This leak is completely similar to #54275

The issue is the MouseCursorPlugin leaks the FlutterView. A similar fix to #54275 will be needed for this one too.

![android_mem_leak](https://user-images.githubusercontent.com/40898687/87575796-72b7c500-c69e-11ea-86f0-7de64e3ec05d.png)

[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.1.pre at /Users/danny.valente/Library/flutter/1.19.0-4.1.pre-beta
    • Framework revision f994b76974 (5 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by blasten** [comment]
cc @xster

**Comment by TahaTesser** [comment]
Hi @dannyvalentesonos 
Can you please provide a complete reproducible minimal code sample. If it is the same code sample from https://github.com/flutter/flutter/issues/54275#issuecomment-611202002 with modification, please provide.
Thank you

**Comment by dannyvalentesonos** [comment]
@TahaTesser The same app does repro the problem, but here's an updated version that builds out of the gate with the latest flutter tools.
[Add2AppTest.zip](https://github.com/flutter/flutter/files/4931475/Add2AppTest.zip)

**Comment by chinmaygarde** [comment]
cc @csells

**Comment by Hixie** [comment]
(no updates from the team yet, Jason is planning on looking at it this week)

**Comment by dannyvalentesonos** [comment]
@Hixie @xster Will this get into the 1.19 release? We'd like it to. Thanks!

**Comment by dannyvalentesonos** [comment]
Did this fix make it into the stable 1.20 release? I'm having trouble telling if it is from the commits in the branches.

**Comment by yrom** [comment]
@dannyvalentesonos I've tried 1.20.3, but this issue still exists.

**Comment by dannyvalentesonos** [comment]
I've verified it's fixed in 1.22. I think it only made it into 1.21 or 1.22.

**Comment by xster** [comment]
Correct. You can see the release tags in https://github.com/flutter/flutter/commit/f06ee8dd8d3aa06e89db64cfa862382b286a5fed.
