### ISSUE TITLE
Exception classes should `@keepToString`

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#61562]
We stripped the `toString()` methods in most classes in `package:flutter` and `dart:ui` to reduce size. We should add `@keepToString` to the toString methods in exception classes since they usually contain useful information for diagnosing errors.

**Comment by dnfield** [comment]
I wonder if we should just do this at the const_finder level. It seems like it will be brittle if we forget to add `@keepToString` to a new exception type. WDYT?

**Comment by chingjun** [comment]
That sgtm. Another alternative I can think of is to add a new lint for this.

**Comment by jonahwilliams** [comment]
Don't forget Error too 🧷

**Comment by chingjun** [comment]
This is now affecting our internal customer, see b/184696488

**Comment by dnfield** [comment]
Getting back to this because of discussion at #96430 - I had lost track of this. Trying to talk with @alexmarkov about how to handle this now that it lives in the Dart SDK

**Comment by dnfield** [comment]
https://dart-review.googlesource.com/c/sdk/+/227920 will fix this

**Comment by dnfield** [comment]
The linked Dart patch has been submitted and should roll through
