### ISSUE TITLE
Adding implementation for Android CPU/GPU/Memory profiling

### ISSUE THREAD

**Issue by AlbertWang0116** [flutter/flutter#61567]
We have CPU/GPU/Memory profiling for iOS, which was enabled through -

CPU: [flutter/engine#18087](https://github.com/flutter/engine/pull/18087)
GPU: [flutter/engine#18752](https://github.com/flutter/engine/pull/18516)
Memory: [flutter/engine#18516](https://github.com/flutter/engine/pull/18752)

With the same profilings available on Android, we will have consolidated way to measure Flutter app's performance through Flutter driver test.

@iskakaushik

**Comment by iskakaushik** [comment]
Albert was interested in knowing an ETA for this issue so he can make plans on updating the tracked benchmarks accordingly. Given that I will not be having time to tackle this in Q3, I'm not sure when I will be able to get to this. cc: @zanderso for help with prioritization.

**Comment by zanderso** [comment]
FYI @blasten We don't currently track CPU utilization on Android for benchmarks like [this one](https://flutter-flutter-perf.skia.org/e/?begin=1621526942&end=1621555092&keys=X004ec1c0b5dbc300448d8af0d4c8e889&num_commits=50&request_type=1&xbaroffset=24193). This came up in the context of https://github.com/flutter/flutter/issues/83113.

**Comment by zanderso** [comment]
Putting this on the list for Impeller since we'll need to be able to compare with benchmarks on memory footprint.

**Comment by jobehi** [comment]
Is there any roadmap for this please?
