### ISSUE TITLE
It takes two build frames for a new DragTarget to know it has a Draggable above it.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6157]

**Comment by abarth** [comment]
I'm not sure how this can happen from reading the code...

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this bug.  Do we believe this still to be an issue?

**Comment by eseidelGoogle** [comment]
@apwilson has worked around this is and this is not really an important issue for him.

It still happens to his knowledge, it just doesn't block him.  Removing customer:pink.

**Comment by abarth** [comment]
I'm going to close this issue as not actionable.
