### ISSUE TITLE
textformfield mouse navigation into text is lost after wrapping for multiline

### ISSUE THREAD

**Issue by dnishimoto** [flutter/flutter#61583]
After wrapping a word sequence in the textform field,  I lose the ability to use the mouse to reposition my cursor back within the content.

```
SizedBox _createInputWidget(int index) {
    return SizedBox(
      width:400,
      child:
      TextFormField(
      validator: (value) {
        return null;
      },
      style: TextStyle(
       fontSize: 14.0,
       height:2.0,
      color: Colors.black,
      ),
      maxLength: 1000,
      maxLines: 10,
      autocorrect: true,
      keyboardType: TextInputType.text,
      decoration: InputDecoration(
        fillColor: Colors.grey[100],
        filled: true,
        labelText: "Enter " + listItems[index].item+" Comment",
      ),
      initialValue: listItems[index].itemComments ??"",
      onChanged: (text) {
        if (this._current==null){
          DialogCaller.showRequiredFieldDialog(context, "Please select a xxx").then((value){});
        }
        setState(() {
          listItems[index].itemComments = text;
        });
      },
    ));
  }
```

**Comment by darshankawar** [comment]
Hi @dnishimoto,
Can you please provide a video / gif of the issue you are facing with respect to mobile app platform (Android / iOS)? Since you mentioned mouse navigation, not sure how we can navigate using that in mobile platform.
Thanks.

**Comment by HansMuller** [comment]
This issue is easy to reproduce using DartPad. 

CC @justinmc 

![input_issue](https://user-images.githubusercontent.com/1377460/87685462-451f5a00-c738-11ea-8ef1-77efd0dd8cc4.gif)

**Comment by justinmc** [comment]
This still exists in master and appears to be web-only.  I was able to reproduce it on master in Chrome but not on iOS.

**Comment by justinmc** [comment]
CC @nturgut.

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/60397

**Comment by sgehrman** [comment]
same issue.
