### ISSUE TITLE
video_player how to get the bufferPercent in initialize or buffering?

### ISSUE THREAD

**Issue by LemonBabyluo** [flutter/flutter#61592]
How to get buffer progress when video initialization and fast forward?  Please be sure to answer me, thank you！

**Comment by darshankawar** [comment]
Hi @LemonBabyluo,
I see there's a similar open issue which describes `isBuffering` always returns `false`, [](https://github.com/flutter/flutter/issues/28494) and a potential [solution](https://github.com/flutter/flutter/issues/28494#issuecomment-650086103) in the same ticket to get buffer percent.
I'd suggest you to follow-up in that ticket for updates.
I am going ahead and closing this issue as duplicate. If you disagree, please write in comments and I'll reopen.
Thanks.

**Comment by LemonBabyluo** [comment]
> Hi @LemonBabyluo,
> I see there's a similar open issue which describes `isBuffering` always returns `false`, [28494](https://github.com/flutter/flutter/issues/28494) and a potential [solution](https://github.com/flutter/flutter/issues/28494#issuecomment-650086103) in the same ticket to get buffer percent.
> I'd suggest you to follow-up in that ticket for updates.
> I am going ahead and closing this issue as duplicate. If you disagree, please write in comments and I'll reopen.
> Thanks.


Is there a way to get the progress of video initialization?
