### ISSUE TITLE
[nnbd] child != null "A null value was passed into a non-nullable parameter child" for AnimatedBuilder's

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#61591]
Have been running Flutter using NNBD for about a month now and never encountered any runtime null issues.

Master changes from today or yesterday have introduced this issue, which appears for almost every widget (I cannot further trace it, at least on Flutter Web it only shows framework traces):

```
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 213:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 32:5    nullFailed
internal
packages/flutter/src/widgets/transitions.dart 1182:19                         build
packages/flutter/src/widgets/transitions.dart 181:48                          build
```

The `AnimatedBuilder`s are set up normally:

```dart
AnimatedBuilder(
  animation: animation,
  builder: (context, child) {
    return Container();
  },
)
```

So this happens on latest `master` Flutter 1.20.0-8.0.pre.125. I am guessing that it was either of the two following commits that introduced this:

* #61188 by @a14n 
* #61114 by @jonahwilliams 

Before, running with `--enable-experiment=non-nullable --no-sound-null-safety` worked fine. Is there anything I need to do differently now?

**Comment by jonahwilliams** [comment]
perhaps we have a bug in some code that is using animated builder? @creativecreatorormaybenot could you attach a runnable example that repros this?

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Well, it happens with **any** `AnimatedBuilder`. 

I will try to be more detailed:

```dart
void main() {
  runApp(MaterialApp(
    home: AnimatedBuilder(
      animation: ValueNotifier(0),
      builder: (context, child) {
        return Container();
      },
    ),
  ));
}
```

This throws the error (`flutter run -d chrome --enable-experiment=non-nullable --no-sound-null-safety`):

![](https://i.imgur.com/MTffDiZ.png)

Changing `(context, child)` to `(context, Widget? child)` fixes it. (Flutter 1.20.0-8.0.pre.125)

**Comment by a14n** [comment]
I would say it is not related to the foundation migration to null safety. Could you try with the previous commit : 0a64b5b2713ae50c36821da7f97a9262f127968b and see if the failure happen?

**Comment by a14n** [comment]
It may also be related to cb7770b3a52288d10fe6d5c78a7fa878dc39acce (the commit after 0a64b5b). It could be worth to test against this commit.

**Comment by creativecreatorormaybenot** [comment]
@a14n Checking out `0a64b5b` fixes it. So I think it might be that `Widget` extends `DiagnosticableTree` and that is what you changed.

So `Widget*` does not work when the super type is a no-star type, rough guess.

**Comment by creativecreatorormaybenot** [comment]
@a14n Checking out `0a64b5b` fixes it. So I think it might be that `Widget` extends `DiagnosticableTree` and that is what you changed.

So `Widget*` does not work when the super type is a no-star type, rough guess.

**Comment by creativecreatorormaybenot** [comment]
@a14n Still there with `cb7770b`, so the assert change creates the error. `--no-null-assertions` fixes it.

**Comment by creativecreatorormaybenot** [comment]
I do not see how to disable these null assertions. I guessed `--no-null-assertions`, however, that does not exist an an option 🤔

**Comment by a14n** [comment]
Thanks for your help. It doestn't seem possible to disable null assertions so you need to stay on 0a64b5b or revert locally cb7770b.

**Comment by jonahwilliams** [comment]
To be clear - we're not going to disable --null-assertions, or support disabling it. This is either a bug in our code or a bug in null assertions that needs to be fixed

**Comment by jonahwilliams** [comment]
I cannot reproduce this on the latest master. @creativecreatorormaybenot can you provide a complete example?

**Comment by jonahwilliams** [comment]
Oh, I see - you've opted into null safety?

**Comment by jonahwilliams** [comment]
The fix is

```dart
AnimatedBuilder(
  animation: animation,
  builder: (context, Widget? child) {
    return Container();
  },
)
```

The `child` parameter is inferred as `Widget`, which fails when the null opted out library passes a `null` value. This is a super weird edge case

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Yes, I was aware of this the whole time. Was it not clear from what I wrote? 😶

But why do you close the issue - do you think this is a good way forward? There is no way to detect this issue before runtime; so I would call it a bug, at least somewhere. And also the inference is wrong, right?

**Comment by jonahwilliams** [comment]
@creativecreatorormaybenot this is a bug in your code. You are declaring a closure that must accept a non-nullable widget, and passing it to a place where a callback can provide you null.

this is an odd edge case, and you **really should not be opting into null safety before flutter has migrated!**. I cannot make that clear enough - you are going to constantly hit this edge cases because all of the migration logic and safe guards are designed around in order migration - that is non-null safe code depending on null-safe code, not the other way around.

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Right, I see. You are saying that this issue will disappear when the framework code is migrated, right?

I have no problem with edge cases like this - I was just not sure that this was really expected behavior.

**Comment by jonahwilliams** [comment]
Yes, once the AnimatedBuilder is migrated, the closure would be declared as providing `Widget?`. The type inference in the closure would then be correct, and the assert wouldn't be tripped.
