### ISSUE TITLE
Persistent footer buttons

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#616]
We should factor out the dialog bottom button logic into a generic "persistent footer button" concept, as per:

https://www.google.com/design/spec/components/buttons.html#buttons-usage

**Comment by Hixie** [comment]
- [ ] Raised buttons should assert that they are not in persistent footer sections.

**Comment by abarth** [comment]
We could add a `persistentFooter` slot to Scaffold.

**Comment by abarth** [comment]
This is https://docs.flutter.io/flutter/material/ButtonBar-class.html.  Still need the slot in scaffold.
