### ISSUE TITLE
Tab area scroll is too fast in Gallery Colors demo

### ISSUE THREAD

**Issue by bredov** [flutter/flutter#6160]
## Steps to Reproduce

In Gallery app open Colors demo. Swipe tab area and take finger off screen before animation stops.
Result: immediate scroll to the end (or beginning depending on swipe direction) of tab list.
Expected result: smooth scrolling with appropriate velocity.
## Flutter doctor

Gallery app from Play Market on Sony Xperia Z5 compact

**Comment by eseidelGoogle** [comment]
This can also be reproduced by making a small drag with your finger in a scrollable tab region but having the drag end off-screen.  @HansMuller

**Comment by HansMuller** [comment]
This is definitely a bug. Tab bar swipe gestures don't actually produce an animated "fling".

Note also: there be some confusion about the scroll velocity reported to Scrollable.fling(), passed to AnimationController.fling(), and defined by kPixelScrollTolerance.velocity. They are all supposed to be logical pixels per second.

**Comment by HansMuller** [comment]
This bug should be resolved along with https://github.com/flutter/flutter/issues/5637

**Comment by eseidelGoogle** [comment]
I'm no longer able to reproduce.  Looks like Hans' fix was successful. :)
