### ISSUE TITLE
TextField in RTL with multiline 

### ISSUE THREAD

**Issue by MahmoudMehisen** [flutter/flutter#61605]
I  have a problem with TextField when RTL can't remove or access the previous lines.
![ezgif-4-0243f09c50c1](https://user-images.githubusercontent.com/35047994/87662057-f25a9800-c761-11ea-8c64-30a3370b510e.gif)

**Comment by VladyslavBondarenko** [comment]
Hi @MahmoudMehisen 
could you provide your `flutter doctor -v`?
I tried with current master `1.20.0-8.0.pre.125` on iOS 13.5 simulator, but couldn't reproduce. Does it happen only with real device?

Provide a complete minimal reproducible code sample if this one works correctly

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          maxLines: 10,
          textDirection: TextDirection.rtl,
        ),
      ),
    );
  }
}
```

**Comment by MahmoudMehisen** [comment]
Hi @VladyslavBondarenko ,

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\mahmo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.1)
    • VS Code at C:\Users\mahmo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by GaryQian** [comment]
Can you try this on dev channel? This may have been fixed already by https://github.com/flutter/flutter/pull/59379 but is not yet in stable.

`flutter channel dev`
`flutter upgrade`

**Comment by MahmoudMehisen** [comment]
@GaryQian  it's work thanks.
