### ISSUE TITLE
cannot move ListView.builder() with AlertDialogwhen  TalkBack is enabled

### ISSUE THREAD

**Issue by yama3nomori** [flutter/flutter#61602]
Android 9 is no problem.
But Android 10 is freezed.

If I used on body of Scaffold(), it's no problem.

'flutter doctor -v' is following:

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale ja-JP)
    • Flutter version 1.18.0-11.1.pre at D:\Android\flutter
    • Framework revision 2738a1148b (9 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.47.1)
    • VS Code at C:\Users\nyama\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • Pixel 3 • 8AJX0TG49 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

Sample code is following:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

   _incrementCounter() {
    var link = [1, 10, 25, 50];
    showDialog<bool>(
  context: context,
  builder: (BuildContext context){
return AlertDialog(
  title: Text('select number'),
  content:          ListView.builder(
itemBuilder: (BuildContext context, int num){
    return Card(
      child: GestureDetector(
    child: Padding(
      child: Text(link[num].toString()),
      padding: EdgeInsets.all(20.0),
         ),
         onTap: (){
           setState((){
             _counter += link[num];
           });
           Navigator.of(context).pop(true);
         },
      ),
    );
},
    itemCount: link.length,
  ),
  actions: <Widget>[
    FloatingActionButton(
      tooltip: 'close',
      child: Icon(Icons.close),
      onPressed: () => Navigator.of(context).pop(true),
    ),
  ],
);
  }
    );  
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () { _incrementCounter (); },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by darshankawar** [comment]
Hi @yama3nomori,
When you say `cannot move ListView.builder()`, what do you mean exactly ? Does the AlertDialog show up when you tap on FAB or it doesn't show up when talkback is ON ? Can you elaborate on this ?

Also, I tried to replicate your code on Android 8.1.0 on which I was able to select the values from listview in alertDialog with talkback ON.
However, when I tried the same on Samsung s10, I was not able to see the alert dialog show up after tapping FAB even with talkback OFF and it gave me below error:

`RenderViewport does not support returning intrinsic dimensions.`.  

Below is full log from S10:

<details>
<summary>log</summary>

```
Performing hot restart...
Syncing files to device SM G975F...
Restarted application in 977ms.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderViewport does not support returning intrinsic dimensions.

Calculating the intrinsic dimensions would require instantiating every child of the viewport, which defeats the point of viewports being lazy.

If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that effect without implementing the intrinsic dimension API.

The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
When the exception was thrown, this was the stack: 
#0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:341:9)
#1      RenderViewportBase.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:355:6)
#2      RenderViewportBase.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:367:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1301:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
...
The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#91301 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(280.0<=w<=331.4, 0.0<=h<=730.7)
...  size: MISSING
...  stepWidth: null
...  stepHeight: null
RenderObject: RenderIntrinsicWidth#91301 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=331.4, 0.0<=h<=730.7)
  size: MISSING
  stepWidth: null
  stepHeight: null
...  child: RenderFlex#3acf9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    direction: vertical
...    mainAxisAlignment: start
...    mainAxisSize: min
...    crossAxisAlignment: stretch
...    verticalDirection: down
...    child 1: RenderPadding#4e500 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...      constraints: MISSING
...      size: MISSING
...      padding: EdgeInsets(24.0, 24.0, 24.0, 0.0)
...      textDirection: ltr
...      child: RenderSemanticsAnnotations#92b1d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        semantic boundary
...        size: MISSING
...        child: RenderParagraph#f87a7 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          textScaleFactor: 1.1
...          locale: en_US
...          maxLines: unlimited
...    child 2: RenderPadding#ab2bf NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.loose
...      constraints: MISSING
...      size: MISSING
...      padding: EdgeInsets(24.0, 20.0, 24.0, 24.0)
...      textDirection: ltr
...      child: RenderRepaintBoundary#4536c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        usefulness ratio: no metrics collected yet (never painted)
...        child: RenderCustomPaint#8644c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...    child 3: RenderPadding#3425c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...      constraints: MISSING
...      size: MISSING
...      padding: EdgeInsets.zero
...      textDirection: ltr
...      child: RenderPadding#5ae86 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(4.0, 8.0, 4.0, 8.0)
...        textDirection: ltr
...        child: _RenderButtonBarRow#911b5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          direction: horizontal
...          mainAxisAlignment: end
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderIntrinsicWidth#91301 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: _RenderInkFeatures#df275 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#d6ef5 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#11cf2 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 322 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#11cf2 relayoutBoundary=up2
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  AlertDialog file:///Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter_app_demo/lib/main1.dart:227:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Updated layout information required for RenderFlex#3acf9 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2594 pos 12: '!_needsLayout'
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

Also please elaborate more when you say `if I used on body of Scaffold(), it's no problem.`.
Thanks.

**Comment by yama3nomori** [comment]
HI, @darshankawar

Thanks for your comment.

It doesn't show up when talkback is ON.
But when ListView.builder() was useed on Scaffold(), ListView can make.

And both cases are no problem on less than Android 10.

**Comment by darshankawar** [comment]
@yama3nomori I am unable to replicate this on Android 10. When I tap on FAB, the alert dialog isn't showing up and throwing the error as mentioned in my previous comment. Are you getting any error in console something like below, when you try to tap on FAB ?

`RenderViewport does not support returning intrinsic dimensions.` 

When I moved the code inside `Scaffold`, I am seeing similar behavior, ie, alertdialog not showing up and throwing the `RenderViewport` error. 
Can you please confirm if you are too getting this error or no ?

**Comment by yama3nomori** [comment]
I got following console message:

Launching lib\main.dart on Pixel 3 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
W/Gralloc3(29011): mapper 3.x is not supported
E/libc    (29011): Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
W/RenderThread(29011): type=1400 audit(0.0:10971): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20926 scontext=u:r:untrusted_app_27:s0:c114,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
I/flutter (29011): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (29011): The following NoSuchMethodError was thrown during performLayout():
I/flutter (29011): The method 'copyWith' was called on null.
I/flutter (29011): Receiver: null
I/flutter (29011): Tried calling: copyWith(maxWidth: Infinity)
I/flutter (29011):
I/flutter (29011): The relevant error-causing widget was:
I/flutter (29011):   AlertDialog file:///C:/Users/nyama/OneDrive/APPS/vstest/lib/main.dart:84:8
I/flutter (29011):
I/flutter (29011): When the exception was thrown, this was the stack:
I/flutter (29011): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
I/flutter (29011): #1      _RenderButtonBarRow.constraints 
I/flutter (29011): #2      RenderObject.debugFillProperties 
I/flutter (29011): #3      RenderBox.debugFillProperties 
I/flutter (29011): #4      RenderFlex.debugFillProperties 
I/flutter (29011): #5      DiagnosticableNode.builder.<anonymous closure> 
I/flutter (29011): #6      DiagnosticableNode.builder 
I/flutter (29011): #7      DiagnosticableNode.style 
I/flutter (29011): #8      DiagnosticsNode.toString 
I/flutter (29011): #9      _StringBase._interpolate  (dart:core-patch/string_patch.dart:842:19)
I/flutter (29011): #10     TextTreeRenderer._debugRender.visitor 
I/flutter (29011): #11     TextTreeRenderer._debugRender.visitor 
I/flutter (29011): #12     TextTreeRenderer._debugRender.visitor 
I/flutter (29011): #13     TextTreeRenderer._debugRender.visitor 
I/flutter (29011): #14     TextTreeRenderer._debugRender.visitor 
I/flutter (29011): #15     TextTreeRenderer._debugRender 
I/flutter (29011): #16     TextTreeRenderer.render 
I/flutter (29011): #17     TextTreeRenderer._debugRender 
I/flutter (29011): #18     TextTreeRenderer.render 
I/flutter (29011): #19     FlutterError.dumpErrorToConsole 
I/flutter (29011): #20     FlutterError.onError.<anonymous closure> 
I/flutter (29011): #21     FlutterError.reportError 
I/flutter (29011): #22     RenderObject._debugReportException 
I/flutter (29011): #23     RenderObject.layout 
I/flutter (29011): #24     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #25     RenderObject.layout 
I/flutter (29011): #26     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #27     _RenderCustomClip.performLayout 
I/flutter (29011): #28     RenderObject.layout 
I/flutter (29011): #29     RenderConstrainedBox.performLayout 
I/flutter (29011): #30     RenderObject.layout 
I/flutter (29011): #31     RenderPositionedBox.performLayout 
I/flutter (29011): #32     RenderObject.layout 
I/flutter (29011): #33     RenderPadding.performLayout 
I/flutter (29011): #34     RenderObject.layout 
I/flutter (29011): #35     RenderPadding.performLayout 
I/flutter (29011): #36     RenderObject.layout 
I/flutter (29011): #37     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #38     RenderObject.layout 
I/flutter (29011): #39     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #40     RenderObject.layout 
I/flutter (29011): #41     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #42     RenderObject.layout 
I/flutter (29011): #43     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #44     RenderObject.layout 
I/flutter (29011): #45     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #46     RenderObject.layout 
I/flutter (29011): #47     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #48     RenderObject.layout 
I/flutter (29011): #49     RenderProxyBoxMixin.performLayout 
I/flutter (29011): #50     RenderOffstage.performLayout 
I/flutter (29011): #51     RenderObject.layout 
I/flutter (29011): #52     _RenderTheatre.performLayout 
I/flutter (29011): #53     RenderObject._layoutWithoutResize 
I/flutter (29011): #54     PipelineOwner.flushLayout 
I/flutter (29011): #55     RendererBinding.drawFrame 
I/flutter (29011): #56     WidgetsBinding.drawFrame 
I/flutter (29011): #57     RendererBinding._handlePersistentFrameCallback 
I/flutter (29011): #58     SchedulerBinding._invokeFrameCallback 
I/flutter (29011): #59     SchedulerBinding.handleDrawFrame 
I/flutter (29011): #60     SchedulerBinding._handleDrawFrame 
I/flutter (29011): #64     _invoke  (dart:ui/hooks.dart:277:10)
I/flutter (29011): #65     _drawFrame  (dart:ui/hooks.dart:235:3)
I/flutter (29011): (elided 3 frames from dart:async)
I/flutter (29011):
I/flutter (29011): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#04012 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (29011):   creator: CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ←
I/flutter (29011):     ConstrainedBox ← Center ← MediaQuery ← Padding ← AnimatedPadding ← Dialog ← AlertDialog ← ⋯
I/flutter (29011):   parentData: <none> (can use size)
I/flutter (29011):   constraints: BoxConstraints(280.0<=w<=312.7, 0.0<=h<=697.5)
I/flutter (29011):   size: MISSING
I/flutter (29011): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (29011):     child: _RenderInkFeatures#9e651 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):       child: RenderIntrinsicWidth#c8c20 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):         child: RenderFlex#038d7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):           child 1: RenderPadding#41e21 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):             child: RenderSemanticsAnnotations#33374 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):           child 2: RenderPadding#91563 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):             child: RenderRepaintBoundary#5ef7e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):           child 3: RenderPadding#3a4be NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011):             child: RenderPadding#edcb9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (29011): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#04012 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#c81fd relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29011): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 322 pos 12: 'child.hasSize': is not true.
I/flutter (29011): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#c81fd relayoutBoundary=up2
I/flutter (29011): Another exception was thrown: Updated layout information required for _RenderInkFeatures#9e651 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.

**Comment by darshankawar** [comment]
Hi @yama3nomori,
I again looked at your code and observed that the `Listview.builder` you are using  is causing the issue. A listview if specified expands to the maximum space. Since you are showing it inside `alert dialog` and it's dimensions are limited, hence the listview is unable to find max space and throws the error `RenderViewport does not support returning intrinsic dimensions.`.
In order to resolve this, just wrap `ListView.builder` with `Container` and provide custom dimensions as shown below:

```
return AlertDialog(
            title: Text('select number'),
            content:  Container(
              height: 300,
              width: 300,
              child: ListView.builder(
                itemBuilder: (BuildContext context, int num){
```
With this, I was able to see the alert dialog on Android 10 and with talkback ON, the alert dialog is opening and reading the items properly.  Attached is the video for your reference.

[61602.mp4.zip](https://github.com/flutter/flutter/files/4945832/61602.mp4.zip)

**Comment by yama3nomori** [comment]
Hi, @darshankawar

Thanks for your advice.

I tried to use Container() and could also see AlertDialog().
I'll try to make a code using this rule.
