### ISSUE TITLE
flutter_test needs patch on dev (maybe more): test_api >=0.2.18 is incompatible with flutter_test from sdk

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#61617]
I went over this with Simon, he confirmed the bug.

Short version:

- Create new app, by default you get test_api: 0.2.18
- Add the newest version of flutter_test (test: 1.15.3) to dev dependencies

Run pub get and this is the result:

Because test_api >=0.2.18 depends on matcher 0.12.9 and every version of flutter_test from sdk depends on matcher 0.12.8, test_api >=0.2.18 is incompatible with flutter_test from sdk.
So, because practicing_testing depends on both flutter_test any from sdk and test_api 0.2.18, version solving failed.
pub get failed (1; So, because practicing_testing depends on both flutter_test any from sdk and test_api 0.2.18, version solving failed.)

(I have no idea why the text below is formatted with strikeout, please ignore that)

I attempted to run pub deps and got all of this:

scott@scott-NH50-70RA:~/Flutter/Tutorials/practicing_testing$ flutter pub deps
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
scott@scott-NH50-70RA:~/Flutter/Tutorials/practicing_testing$ rm pubspec.lock
scott@scott-NH50-70RA:~/Flutter/Tutorials/practicing_testing$ flutter pub get
Because every version of flutter_test from sdk depends on test_api 0.2.17 and test >=1.15.3 depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3.
So, because practicing_testing depends on both test ^1.15.3 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in practicing_testing...
pub get failed (1; So, because practicing_testing depends on both test ^1.15.3 and flutter_test any from sdk, version solving
failed.)
scott@scott-NH50-70RA:~/Flutter/Tutorials/practicing_testing$ flutter pub deps
No pubspec.lock file found, please run "pub get" first.
pub finished with exit code 65

To get going again, I had to use a dependency override and set the test_api to 0.2.17:

dependency_overrides:
  test_api: 0.2.17

**Comment by goderbauer** [comment]
I am not sure what you mean by

> Add the newest version of flutter_test (test: 1.15.3) to dev dependencies

After `flutter create`, `flutter_test` is already listed under `dev_dependencies`. And you should always be using the `flutter_test` version that ships with the flutter sdk you use. You ensure this by making sure you pubspec.yaml includes the following:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
```

Do you have that in your pubspec.ymal? Does it work with that? Otherwise it would be good to see your pubspec to be able to reproduce this.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
