### ISSUE TITLE
how to use local canvaskit to build flutter web app?

### ISSUE THREAD

**Issue by yzg-github** [flutter/flutter#61610]
hi@yjbanov here i have three questions:
1.i want to build a flutter web app within canvaskit,then i set --dart-define=FLUTTER_WEB_USE_SKIA=true but it seems not work. how can i make sure the value --dart-define=FLUTTER_WEB_USE_SKIA=true has worked?
2.how can i build a flutter web app within local canvaskit ? i can't find any article about how to use local canvaskit. could you tell me the setps about using local canvaskit in a flutter web app?
3.how can i add someting new to canvaskit and compile it,is there any article about it?
thanks

**Comment by yjbanov** [comment]
To use a custom build of CanvasKit you can build a custom Flutter engine and point it to your build of CanvasKit by changing the URL here: https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/compositor/initialization.dart#L17. We will support it without having to build your own engine as part of https://github.com/flutter/flutter/issues/51424.

To add something new to CanvasKit you can clone Skia source code, change it and build CanvasKit WASM blog from it.

As for the `--dart-define=FLUTTER_WEB_USE_SKIA=true` not working, can you please provide more detail, such as the exact command you are running, how you determined that it's not working, as well as the output of `flutter doctor -v`.

**Comment by yzg-github** [comment]
hi@ yjbanov thaks a lot! 
but i still have some doubt
this is the cmd i used : flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true.
the part of the log of flutter coctor -v is : 
[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found! 
it seems no error

I'm not clear . the product  of building local CanvasKit  is a CanvasKit.wsam file ? when i use --dart-define=FLUTTER_WEB_USE_SKIA=true to build web app, is that means i'm using a CanvasKit.wsam file from server? 
i can't find the downloaded file of CanvasKit.wsam from the server in my local dir. so i can't  make sure the value --dart-define=FLUTTER_WEB_USE_SKIA=true has worked. is there an other way to confirm the value worked?

**Comment by yzg-github** [comment]
hi@ yjbanov 
i have complied the canvaskit.wasm,then How to apply it to flutter engine？Where can I find the corresponding information？
i have changed the url as this : const String canvasKitBaseUrl = './../../../../../../../third_party/skia/out/canvaskit_wasm_debug/'; 
What should i do next？

**Comment by yzg-github** [comment]
solved
