### ISSUE TITLE
Unhandled exception: FileSystemException: Cannot open file, path = '/home/kay/.flutter_tool_state' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by vimkaf** [flutter/flutter#61613]
## Steps to Reproduce
1. ...
2. ...
3. ...

After successful installation of the latest stable version of flutter i cant run any flutter command from my terminal. i cant run `flutter --version` and `flutter doctor`. I have setup the path correctly.
![Screenshot from 2020-07-16 13-29-50](https://user-images.githubusercontent.com/2923113/87671104-ad862f80-c768-11ea-9dbc-35463530f7d8.png)
![Screenshot from 2020-07-16 13-30-23](https://user-images.githubusercontent.com/2923113/87671108-af4ff300-c768-11ea-9e8d-a25b54a2e45f.png)
![Screenshot from 2020-07-16 13-31-20](https://user-images.githubusercontent.com/2923113/87671110-afe88980-c768-11ea-80c1-e85a4b18fc1c.png)

**Comment by darshankawar** [comment]
Hi @vimkaf,
I see there's a similar open issue describing your case, [59836](https://github.com/flutter/flutter/issues/59836).
I'd suggest you to follow-up there for updates on this issue.
I am going ahead and closing this as duplicate. If you disagree, please write in comments and I'll reopen.
Thanks.

**Comment by vimkaf** [comment]
My issue is different ... I can't run basic flutter commands without getting errors.

**Comment by vimkaf** [comment]
I finally solved this issue by running two commands
`sudo chmod -R a+rwx /home/kay`
`sudo chown kay `

I hope this helps someone that might have similar problems
