### ISSUE TITLE
Add a Material Design component catalog page

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#6161]
It is hard to map a UI mockup to widgets in Flutter, especially when the developer is not familiar with Material Design terms. The root page of [the Material library](https://docs.flutter.io/flutter/material/material-library.html) does not separate widgets implementing core Material components from other widgets, and its layout is not suitable for browsing. Per offline discussion with @qchong, it would be helpful to create a component catalog page on flutter.io to help mitigate this issue.

Specifically, components will be ordered alphabetically to match the Components section on [material.google.com](http://material.google.com). Each entry on the components page should include:
* Component name
* Component description
* A screenshot
* Name of the Flutter widget implementing the component
* Links to the widget’s API doc, source code, and usage examples

**Comment by eseidelGoogle** [comment]
We've had many requests for better organization of our widgets.  It's probably time. :)  @abarth or @Hixie would know if this is work is already schedule via some other issue.

**Comment by abarth** [comment]
Let's use this issue to schedule it.  I think the only question is when to do this.  If you think it's time, we can have a go at it.

**Comment by eseidelGoogle** [comment]
I think Milestone 2 is appropriate.  We'll have to sit down and prioritize this with our other documentation desires next quarter.

**Comment by sethladd** [comment]
This is great to see, and a huge win. Agree on milestone 2.

**Comment by sethladd** [comment]
Update: @qchong and @InMatrix have signed up to do this.

**Comment by qchong** [comment]
@sethladd This bug issue be for tracking the doc changes on flutter.io. Can you please create a separate issue for any changes needed for dartdoc generation?

**Comment by sethladd** [comment]
Hm, this looked like the issue to create a catalogue of MD components implemented by Flutter. Let's chat in person. I could be mistaken.

**Comment by sethladd** [comment]
Thanks @InMatrix and @qchong !
