### ISSUE TITLE
webview_flutter version 0.3.21 - On Android webview data is getting cached

### ISSUE THREAD

**Issue by rampal** [flutter/flutter#61616]
We are using webview_flutter version 0.3.21 in our application to load web page data. On Android device/emulator when visiting to webview page whatever data is shown same data is being shown if I logout and re-login with different user. Web view cache is not getting clear.

It is working perfectly fine on IOS devices/simulators but issue is coming on Android.

We tried following options but it did not work:
- In onWebViewCreated() method added
    webViewController.clearCache();

and even added clear cookies also but did not work
final cookieManager = CookieManager();
    cookieManager.clearCookies();

Can someone help  us on this?

Thanks,
Rampal

**Comment by VladyslavBondarenko** [comment]
Hi @rampal 
please follow up on https://github.com/flutter/flutter/issues/53122, closing as duplicate
