### ISSUE TITLE
 If I create an activity and use methodchannel, can flutter receive it?

### ISSUE THREAD

**Issue by libo1223** [flutter/flutter#61612]
I create an activity and use methodChannel, but i find that the result.success() didn't work. Flutter didn't receive the result.

**Comment by VladyslavBondarenko** [comment]
Hi @libo1223 
have you followed https://flutter.dev/docs/development/platform-integration/platform-channels?
could you provide your `flutter doctor -v` and minimal reproducible project?

**Comment by libo1223** [comment]
I don't think it is the problem of methodChannel. I use MethodChannel in MainActivity didn't have any trouble. 
So, i want to know the another activity which i created can use MethodChannel to Flutter?
In my view, flutter is work on the MainActivity, when the MainActivity is finish(), Does flutter can receive the message? Or i should to startActivity the MainActivity and post the message to flutter.

**Comment by pedromassangocode** [comment]
> So, i want to know the another activity which i created can use MethodChannel to Flutter?

Yes, any Activity can use method channel.

> In my view, flutter is work on the MainActivity, when the MainActivity is finish(), Does flutter can receive the message? Or i should to startActivity the MainActivity and post the message to flutter.

Not sure if I understood this correctly. @libo1223 can you clarify this?

**Comment by libo1223** [comment]
> > So, i want to know the another activity which i created can use MethodChannel to Flutter?
> 
> Yes, any Activity can use method channel.
> 
> > In my view, flutter is work on the MainActivity, when the MainActivity is finish(), Does flutter can receive the message? Or i should to startActivity the MainActivity and post the message to flutter.
> 
> Not sure if I understood this correctly. @libo1223 can you clarify this?

Sorry, it's my fault. Now i know how to use it.

**Comment by libo1223** [comment]
> > So, i want to know the another activity which i created can use MethodChannel to Flutter?
> 
> Yes, any Activity can use method channel.
> 
> > In my view, flutter is work on the MainActivity, when the MainActivity is finish(), Does flutter can receive the message? Or i should to startActivity the MainActivity and post the message to flutter.
> 
> Not sure if I understood this correctly. @libo1223 can you clarify this?

can you close this issue?
