### ISSUE TITLE
Change ChangeNotifier implementation

### ISSUE THREAD

**Issue by Afsar-Pasha** [flutter/flutter#61619]
Currently `ChangeNotifier` creates new `List` for every `notifyListeners()` also checks `_listeners.contains(listener)` for every listener, also `AnimationController` uses similar approach implemented in `AnimationLocalListenersMixin` which usually calls `notifyListeners()` every frame on animation.

Since dart is single threaded maybe we can implement it something similar to,

```dart
class _Listener {
  _Listener(this.callback);

  VoidCallback callback;
  bool isRemoved = false;
}

class ChangeNotifier implements Listenable {
  List<_Listener> _listeners = [];
  List<_Listener> _listenersAddedDuringNotify = [];

  bool isNotifying = false; // flag to prevent ConcurrentModificationError

  @override
  void addListener(VoidCallback listener) {
    if (isNotifying) {
      _listenersAddedDuringNotify.add(_Listener(listener));
    } else {
      _listeners.add(_Listener(listener));
    }
  }

  @override
  void removeListener(VoidCallback listener) {
    final index = _listeners.indexWhere((e) => e.callback == listener);
    if (index == -1) {
      return;
    }
    if (isNotifying) {
      _listeners[index].isRemoved = true;
    } else {
      _listeners.removeAt(index);
    }
  }

  void notifyListeners() {
    if (_listeners != null) {
      isNotifying = true;
      for (final listener in _listeners) {
        try {
          if (!listener.isRemoved) listener.callback();
        } catch (exception, stack) {
          // ...
        }
      }
      isNotifying = false;

      // Also below code can be made conditional by adding additional flag for remove
      // and checking isNotEmpty for add

      // Remove listeners which were removed during notifyListeners
      _listeners.removeWhere((e) => e.isRemoved);
      // Add listeners which were added during notifyListeners
      _listeners.addAll(_listenersAddedDuringNotify);

      // Clean _listenersAddedDuringNotify
      _listenersAddedDuringNotify.clear();
    }
  }
}
```

It does require creating a new object for every listener, but still looks faster than current implementation, or I missed something?

**Comment by TahaTesser** [comment]
Hi @Afsar-Pasha 
Can you explain in detail? what are the problems with existing implementation and it's not clear what you suggesting as better approach, what you propose? 
Thank you

**Comment by Afsar-Pasha** [comment]
> Currently `ChangeNotifier` creates new List for every `notifyListeners()` also checks `_listeners.contains(listener)` for every listener, also `AnimationController` uses similar approach implemented in `AnimationLocalListenersMixin` which usually calls `notifyListeners()` every frame on animation.

With this implementation we don't need to create a new `List` for every when `notifyListeners()` and check `_listeners.contains(listener)` for every listener, making it O(N) compared to O(N²) in current implementation.

**Comment by Afsar-Pasha** [comment]
Closing as duplicate of #71900.
