### ISSUE TITLE
Increase in Flutter memory usage

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61625]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=56281.

**Comment by kf6gpe** [comment]
This is reported to still be happening; working with a Fuchsia team member and @iskakaushik on determining what can be done.

**Comment by chinmaygarde** [comment]
Triage: It is still unclear if this is Flutter related because other application related changes were in the internally referenced patch delta.

**Comment by kf6gpe** [comment]
Upstream issue indicates that this issue is finding a home on the Fuchsia team after @iskakaushik has done some testing and has questions. Will leave open while we see if more action is needed by the Flutter team.

**Comment by zanderso** [comment]
Since this is waiting on an investigation by the Fuchsia team, I will change the milestone.

**Comment by chinmaygarde** [comment]
Triage: No change since the last update.

**Comment by kf6gpe** [comment]
Upstream issue resolved.
