### ISSUE TITLE
[engine] Scenario tests are flaky on flutter-try-mac-x machines

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#61620]
iOS tests were failing all the time for no apparent reason. We identified that mac machines provided by chromium were failing less frequently and limited the ios tests to run only on those machines.

Tests have been stable for a few days but we need to identify the reason all the macs in 1808 are failing the tasks.

Some examples of failing tasks:

* https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/5692
* https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/5691

**Comment by godofredoc** [comment]
This is a P1 because even though ios tests are now passing they are limited to use 1/3 of the existing capacity.

**Comment by digiter** [comment]
I will continue run the scenario test on try bots but ignore the result, and bring back the capacity. /cc @zanderso

**Comment by zanderso** [comment]
@digiter Do you mean ignore the result only if it's from one of the suspect machines? Or do you mean ignoring the result from all machines?

**Comment by digiter** [comment]
@zanderso Ignore the result only if it's from one of the suspect machines.

**Comment by godofredoc** [comment]
mac-try-10 was failing the tasks consistently is it possible to block it and experiment with that one only?

**Comment by digiter** [comment]
Created https://flutter-review.googlesource.com/c/recipes/+/4340.

**Comment by digiter** [comment]
Trying to see if deleting Xcode derived data helps the issue.

**Comment by digiter** [comment]
Deleting Xcode derived data doesn't help, going to try removing the cipd cache of Xcode.

**Comment by Hixie** [comment]
@digiter Any news? Also, please set the target milestone so that we can plan accordingly. Thanks!

**Comment by digiter** [comment]
Tried removing cache and Xcode derived data, didn't work. Next steps are
1. Move mac-10 to the staging pool.
2. Check Xcode related toos: xcrun, xcode-select.

**Comment by godofredoc** [comment]
@digiter can you please update the bug with the things you tried in mac-10 after moving it to the staging pool?

I ran a couple of tasks and they are passing:

https://chromium-swarm.appspot.com/task?id=4dda63b475c00610,

**Comment by digiter** [comment]
@godofredoc Before moving, I deleted the `/b/s/c`, `/b/s/cipd_cache/`, `/b/s/isolated_cache/` and a test build still fails. After moving to the staging pool, I did nothing.

**Comment by digiter** [comment]
Maybe recent commits fixed something, I'm testing the builder again with an old commit revision: https://chromium-swarm.appspot.com/task?id=4dfc992940c89f10

**Comment by digiter** [comment]
Godofredo suspects that there's a command installed via salt state.highstate: `xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`

**Comment by digiter** [comment]
From the latest 10 runs: 
- 2 with failure [link](https://logs.chromium.org/logs/flutter/led/wutong_google.com/420797a0ececc601d4ffade95b1f55b083868b1e8b369a00924f1a3a9fa808ee/+/u/Scenario_App_Integration_Tests/stdout)
- 1 with failure on installing Xcode [link](https://logs.chromium.org/logs/flutter/led/wutong_google.com/1b5866b597200dfcaebe147c6a44b1dd4b6925c8862d31f8956df9803148ac39/+/u/install_xcode/stdout)
- 1 with failure `build ios_debug_arm` [link](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/wutong_google.com/e69ac85d6f5e73caa19ea4aa90c4988243288e9d4bf2b366a07afd57a842feed/+/build.proto)
- 1 with failure `build ios_debug_arm` and bot died [link](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/wutong_google.com/d5b29094e4c4b7462891dafa197470e2ac5c1637b4e8eeccf479bd0a57a64838/+/build.proto)

**Comment by digiter** [comment]
Found the step before "Scenario App Integration Tests" has hidden test failures: https://github.com/flutter/flutter/issues/63742

**Comment by digiter** [comment]
I turned off salt minion and retried several times, there're still two failures: [link1](https://chromium-swarm.appspot.com/task?id=4e04346135cedc10), [link2](https://chromium-swarm.appspot.com/task?id=4e043402ba014610)

**Comment by digiter** [comment]
Increased the timeout in scenario and tried one more time: https://chromium-swarm.appspot.com/task?id=4e1cc0270da38b10

**Comment by godofredoc** [comment]
Any update on this bug?

**Comment by digiter** [comment]
I'm setting up a local engine develop environment to try the tests again.

**Comment by pcsosinski** [comment]
is this needed for 1.22?  if not, please move it to another milestone.

**Comment by digiter** [comment]
Moved to this month.

**Comment by digiter** [comment]
In local development environment, the test failed 5 times out of 10. 
- 3 times on `[PlatformViewGestureRecognizerTests testAccept]`
- 2 time on `[AppLifecycleTests testFlutterViewControllerDetachingSendsApplicationLifecycle]`

**Comment by digiter** [comment]
Added this to engine flake triage process for someone on the engine team to debug. Instructions for running the test:
```
ssh -o "ProxyCommand ssh flutter@flutter-ssh-bridge-001.mtv.corp.google.com -W %h:%p" \
  flutter@flutter-try-mac-10.mtv.corp.google.com

sudo su swarming

cd ~/Downloads/engine/src/flutter/testing/scenario_app/

./run_ios_tests.sh
```

**Comment by cbracken** [comment]
Hit a flake on this today:
Build: https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6739
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8869584553362955840/+/steps/Scenario_App_Integration_Tests/0/stdout
Failing test: `[AppLifecycleTests testFlutterViewControllerDetachingSendsApplicationLifecycle]`

**Comment by zanderso** [comment]
The Engine tree is closed on the flake in `testFlutterViewControllerDetachingSendsApplicationLifecycle`, so I am upping this to P0 and assigning @blasten.

**Comment by blasten** [comment]
This time the issue is 

```
[AppLifecycleTests testFlutterViewControllerDetachingSendsApplicationLifecycle] : failed - Expected lifecycle AppLifecycleState.inactive but instead received AppLifecycleState.resumed
```
This test was added by @chunhtai in https://github.com/flutter/engine/pull/13767 

 @gaaclarke, @xster or @dnfield any idea what could be going wrong?  https://github.com/flutter/flutter/issues/61620#issuecomment-686728250

**Comment by chunhtai** [comment]
It looks like the test sends an additional resume when flutter vc is destroyed, but i couldn't find out why. It is also weird that this does not fail 100% of time if something did go wrong when flutter vc was destroyed

**Comment by xster** [comment]
Gut feeling: I have some suspicion that it might come from a different instance of the Flutter VC. i.e. depending on how the tests are sequenced against the same UIApplication instance (and thus the same FlutterEngine and lifecycle channel instance), there might be some cross-talk issues.

**Comment by xster** [comment]
umm I don't think I was right on that last one. I couldn't get it to fail on repeat runs locally no matter what the order is. 

I think the solution is just to loosen the assertion orders a bit and not assert the transitions that are not the purpose of the test.

**Comment by blasten** [comment]
@xster it sounds like you have more context on this issue. I just reassign it to you.

**Comment by cbracken** [comment]
In https://github.com/flutter/engine/pull/21075, I've disabled the `testFlutterViewControllerDetachingSendsApplicationLifecycle` test since these flakes are impacting rolls from upstream teams like Skia/Dart/Fuchsia. Once the cause of the flake has been identified and fix this test should be re-enabled (that PR adds a TODO).

**Comment by cbracken** [comment]
When I landed the above, another test started failing (`testSettingInitialRoute`).

Landed flutter/engine#21080 which disables the Scenario app tests altogether so we can get the tree green again. Once we have any pending upstream rolls in, I'll send out a revert that looks at just disabling the initial route test and iterate from there until we have more data.

**Comment by cbracken** [comment]
Sent out https://github.com/flutter/engine/pull/21087 which attempts to re-enable most of the tests now that roll backlog has cleared in the engine.

**Comment by zanderso** [comment]
After #21087 there was a failure in `[FlutterViewControllerTest testFirstFrameCallback]`

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8869471306153752416/+/steps/Scenario_App_Integration_Tests/0/stdout?format=raw

**Comment by xster** [comment]
I've merged https://github.com/flutter/engine/pull/21088. On repeat runs on the try pool, FlutterViewControllerTest testFirstFrameCallback tends to fail right after an AppLifecycleTest (there was 1 that was not skipped on head) and my PR is meant to fix AppLifecycleTest. For some reason, doing a try run via `led` on my PR doesn't seem to actually use the content of my PR. Merged it to see its effect on head. 

We can revert if it doesn't work.

**Comment by xster** [comment]
After https://github.com/flutter/engine/pull/21088, the new flake is that if AppLifecycleTest is the first ever test to run in scenario app tests (I can't reproduce locally, only reproducible on LUCI), we get:

```
viewWillAppear
applicationBecameActive
applicationWillResignActive
applicationDidEnterBackground
applicationWillEnterForeground
applicationBecameActive
viewDidAppear
```

which causes the issue. The VC lifecycles are expected but the application lifecycles are totally inexplicable. I'm tempted to say a slightly newer version of the iOS 13 SDK might help @godofredoc

**Comment by cbracken** [comment]
The currrent state is that only the (three) ApplicationLifecycle Scenarios tests on iOS are disabled, the rest remain enabled, which seems to have got us to a mostly de-flaked state on master. Those were disabled in flutter/engine#21125. Once @xster has root-caused/fixed the issue we'll want to re-enable those.

@xster has a WIP patch at https://github.com/flutter/engine/pull/21107
