### ISSUE TITLE
Flutter requirements for code size tooling

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#61629]
We are adding code size tooling to DevTools that will allow a user to analyze AOT snapshots and APKs.

To generate a snapshot a user can run `flutter build aot --release --extra-gen-snapshot-options=--write-v8-snapshot-profile-to=./profile.json`. This output can be analyzed in DevTools with visualization tools @peterdjlee has built.

We also need to be able to generate an APK and include AOT snapshot information in the APK analysis. Peter has a [draft cl](https://github.com/flutter/flutter/pull/61626) to add a `--analyze` flag that will show the APK breakdown with the AOT data included when running `flutter build apk --analyze`. This CL also generates a json file that DevTools can use to visualize the APK / AOT data.

An APK will include multiple libapp.so files (where we inject the AOT snapshot data in the analysis output) for different platforms (`arm64-v8a`, `armeabi-v7a`, `x86_64`, **are there more?**). Therefore, we need to be able to generate an AOT snapshot for each of the platforms built in an APK. The `flutter build aot` command looks like it has the option flag `--target-platform-build=[android-arm, android-arm64, android-x86, android-x64]`, but it is unclear how those target platforms directly correlate to the platforms in the APK.

(1) From talking with @jonahwilliams, it appears that:
`--target-platform-build=android-arm =>  armeabi-v7a`
`--target-platform-build=android-arm64 => arm64-v8a`
`--target-platform-build=android-x64 => x86_64`
and 
`--target-platform-build=android-x86 => ??`

**We need some clarification / confirmation on this.**

(2) @jonahwilliams also said that `flutter build aot` is deprecated. **Is there a newer API we should be using that meets our requirements and use case? Should one be created?**

CC @jacob314

**Comment by jonahwilliams** [comment]
arm64-v8a, armeabi-v7a, x86_64 are the only android ABIs. For flutter build apk, you could also produce individual ABIs with the --target-platform=android-arm/android-arm64/android-x64 flags.

Do you specifically need a separate command to produce the AOT artifacts? or could --analyze be added to the existing build android/ios/macos/linux/windows commands

**Comment by jonahwilliams** [comment]
This is done and implemented
