### ISSUE TITLE
Flutter and Dart Plug-ins installed but flutter doctor reports they are not - flutter plugins working - doc wrong?

### ISSUE THREAD

**Issue by rlogwood** [flutter/flutter#61635]
### Flutter doctor reports Flutter and Dart plug-in's missing but they are present
Flutter seems to work fine in-spite of the reported error. I can successfully create and run applications made by `flutter create` and in Android Studio with `File->New->New Flutter Project`.

## Steps to Reproduce

Environment: Ubuntu 20.04 LTS, Android Studio 4.0.1, Latest Flutter/Dart Plug-ins

__Preform these steps on a Ubuntu 20.04 LTS machine__

1. Update to the latest version of Android Studio 4.0.1 using [JetBrains Toolbox App](https://www.jetbrains.com/toolbox-app/)

2. Install flutter via snap
```
sudo snap install flutter --classic
sudo snap install flutter-gallery
flutter channel dev
flutter upgrade
flutter config --enable-linux-desktop
```
3. Install the Android command line tools as outlined in my StackOverflow post:  [Installing Android SDK Command line tools](https://stackoverflow.com/a/62939933/960184)

4. Install the latest Flutter plug-in in Android Studio, this will automatically install the Dart plug-in. See my StackOverflow post for additional context: [Flutter Plugin not installed](https://stackoverflow.com/a/62939342/960184)

5. run `flutter doctor`
<pre><font color="#AA5500">[!]</font> Android Studio (version 4.0)
<b>    </b><font color="#AA0000"><b>✗</b></font><b> Flutter plugin not installed; this adds Flutter specific functionality.</b>
<b>    </b><font color="#AA0000"><b>✗</b></font><b> Dart plugin not installed; this adds Dart specific functionality.</b>
</pre>

## Logs

```
```

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.3.pre at /home/dever/snap/flutter/common/flutter
    • Framework revision 8fe7655ed2 (2 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/dever/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/dever/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 4.0)
    • Android Studio at /home/dever/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @rlogwood 
This is a known issue https://github.com/flutter/flutter/issues/54867 
Closing based on the https://github.com/flutter/flutter/issues/54867#issuecomment-658504774 and in favor of. https://github.com/flutter/flutter/issues/61246

If you disagree, please write in the comments and I will reopen it.
Thank you
