### ISSUE TITLE
No pubspec.yaml found

### ISSUE THREAD

**Issue by Rayyan2650** [flutter/flutter#61630]
when i write in terminal flutter run it say (Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.)     Please help
![helpme](https://user-images.githubusercontent.com/59572861/87700552-ec8ba380-c7af-11ea-91df-544544244e08.JPG)
![see my files](https://user-images.githubusercontent.com/59572861/87700746-44c2a580-c7b0-11ea-9611-33f80aa7b9ad.JPG)

**Comment by darshankawar** [comment]
Hi @Rayyan2650,
It seems you are trying to launch from the wrong folder. Just try to change directories in the terminal.
Do you see the `pubspec.yaml` file in the folder path also ?

**Comment by Rayyan2650** [comment]
your saying that the folder i open contain pubspec.yaml?  if that the question tha answer is yes

**Comment by darshankawar** [comment]
@Rayyan2650, so are you running `flutter run` from the folder which has that file ? Or Can you `cd` to that folder which contains `pubspec.yaml` and then try to run `flutter run` ?
