### ISSUE TITLE
Video Player plugin - Support HTTP cookies

### ISSUE THREAD

**Issue by jaysephjw** [flutter/flutter#61638]
It would be nice to support cookies for network video requests (HLS): 

```
new VideoPlayerController.network("https://example.com/test.mp4",
    cookies: [authCookie]}
)
```

Support for attaching headers in general (#16466) seems blocked on a missing iOS AVPlayer api. But AVPlayer allows attaching cookies.

## Use case

Stream video over the network (HLS) from servers that require cookie authentication.

**Comment by huypham41196** [comment]
You can add cookie via header like this 
```VideoPlayerController.network(
          [Video Url],
          httpHeaders: <String, String>{
            HttpHeaders.cookieHeader: [Your cookie]
})

**Comment by stuartmorgan** [comment]
Header support for Android was added; given that headers are a superset of the requested functionality here, closing.
