### ISSUE TITLE
Flutter not installable from China

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6165]
China seems to block access to Google Storage URLs, which are used when installing flutter. China does not block GitHub, fwiw. Some App Engine sites are not blocked in China (e.g. dartlang.org)

**Comment by InMatrix** [comment]
I just tried installing Flutter in China without VPN. It worked, though it took a really long time to download code from Github. I could also run the starter app in an iOS simulator in China.

![screen shot 2016-12-20 at 1 32 38 pm](https://cloud.githubusercontent.com/assets/348942/21339359/91c449e8-c6b9-11e6-9489-35091c5f004e.png)

**Comment by eseidelGoogle** [comment]
Speculatively pulling this into Milestone 3.  Unclear if we have to solve this ourselves or if someone will want to just mirror things for us.  Definitely other big issues (like https://github.com/flutter/flutter/issues/6939) to solve first. :)

**Comment by sethladd** [comment]
If this is true:

> I just tried installing Flutter in China without VPN. It worked

Then maybe we don't have to do anything? This was opened speculatively. @InMatrix confirmed he could install, while in China.

Going to close this now, but can reopen if/when someone runs into an issue.

**Comment by InMatrix** [comment]
It worked for me but it took probably 20 times longer than it would have been in the US. So it's still something we need to address eventually.

**Comment by Hixie** [comment]
We have several bugs on file for various reasons why setup is ridiculously slow if you don't have a good connection, so I think that's covered.
