### ISSUE TITLE
Flutter team should officially release GeoLocation plugin

### ISSUE THREAD

**Issue by azeemgujjar** [flutter/flutter#61653]
I saw few plugins on https://pub.dev/ for geolocation.
But none of them is stable or we can take risk to deploy on production application.
Even packages developers do not bother to update or reply on issues highlighted by community.
I search alot and not found a single stable plugin  which support foreground + background geolocation services and work like charm of different OS.

I believe this feature is very important for huge market of apps which are geolocation dependent, flutter should officially release this feature in its own repository.

**Comment by wolfc01** [comment]
Having multiple ways (or libraries) to do the same functionality is a "time bomb" for flutter, especially for this kind of standard functionality.

**Comment by idoroiengel** [comment]
I agree with @azeemgujjar 
This is a basic feature in today's standards, and should be part of the official Flutter sdk.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement. There are popular plugins covering this use case in the package ecosystem.
