### ISSUE TITLE
Failed to find assets path for "Frameworks/App.framework/flutter_assets"

### ISSUE THREAD

**Issue by gregsheen** [flutter/flutter#61669]
## Steps to Reproduce

1. Followed steps in this guide: https://flutter.dev/docs/development/ios-project-migration
2. Build app for ios with ```flutter build ios```
3. Run on iPhone simulator

**Expected results:** App running normally

**Actual results:** App freezing on splash screen

I have tried the following:

- Changing to master channel
- Running flutter upgrade
- Adding App.framework and Flutter.framework files back into xcode
- Deleting flutter from laptop and reinstalling

When I create a new flutter app and run it on ios simulator it works fine. I have read a few threads with similar/same issue reported, but the common solution is to change to ```master``` channel or follow the guide in step 1, but I have tried this with no luck.

When running in xcode or VSCode it throws this error:

```
Running Xcode build...                                                  
                                                   
Xcode build done.                                           135.2s
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[VERBOSE-2:engine.cc(134)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(486)] Could not launch engine with configuration.
```

I recently added Firebase Cloud Messaging to my app. It works fine on android.

I initially followed the guide in step 1 because when I ran app in VSCode it errored and suggested migrating my project using that guide. Now I have gone round in circles trying to fix it and can't get back to where I started. Any guidance will be really appreciated.

```flutter run --verbose``` is too long, find in attached file
[flutter run -verbose output.pdf](https://github.com/flutter/flutter/files/4934757/flutter.run.-verbose.output.pdf)

flutter analyze

```
Analyzing ios...                                                        
No issues found! (ran in 1.2s)
```

flutter doctor -v

```
Downloading android-arm-profile/darwin-x64 tools...                 1.0s
Downloading android-arm-release/darwin-x64 tools...                 0.7s
Downloading android-arm64-profile/darwin-x64 tools...               0.9s
Downloading android-arm64-release/darwin-x64 tools...               0.7s
Downloading android-x64-profile/darwin-x64 tools...                 0.6s
Downloading android-x64-release/darwin-x64 tools...                 0.9s
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/gregorysheen/Dev/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gregorysheen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (1 available)            
    • iPhone SE (2nd generation) • C1787BB9-C54C-4853-8C4F-8B6DF30C8DEA • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @gregsheen 
App.framework and Flutter.framework files are still in there in your as you run the app?  Please screenshot 
Can you make a backup of your project and delete `ios` folder and regenerate `ios` folder as follow `flutter create .` and try again?  [Reference issue ](https://github.com/flutter/flutter/issues/54558)
Thank you

**Comment by gregsheen** [comment]
These are my files in xcode

<img width="268" alt="Screenshot 2020-07-17 at 21 56 44" src="https://user-images.githubusercontent.com/64927090/87830169-6a1ae680-c878-11ea-9ee2-ba2ffa63ca2e.png">

**Comment by gregsheen** [comment]
@TahaTesser I deleted the ios folder and regenerated and it is working now! Thank you for the help. I am not sure what the problem was

**Comment by TahaTesser** [comment]
Hi @gregsheen 
Glade you resolved the issue, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
