### ISSUE TITLE
flutter_markdown isn't maintained

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6166]
As we're stabilizing our APIs, we might want to take a look at https://github.com/flutter/flutter/tree/master/packages/flutter_markdown For example, not sure if we're testing it.

Let's decide what we'd like to do with this library.

**Comment by HansMuller** [comment]
It's still used by the gallery demos that display code and it seems to have run afoul of https://github.com/flutter/flutter/pull/5609.

Tests exists for the markdown library however we should be testing the gallery's use of it.

**Comment by abarth** [comment]
I have a branch where I'm experimenting with cleaning up this library.
