### ISSUE TITLE
Gallery: show how to trigger/display a webview AND show docs for sections

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6167]
Was thinking we could show how to display a WebView in a Flutter app by using a WebView to display short docs/snippets/source for each of the demos. Many apps use the WebView to display Help text. We might even be able to link directly to the Github source file for the demo the user is looking at.

**Comment by jingweno** [comment]
I'm looking for integrating a webview into my app. How would I do that?

**Comment by eseidelGoogle** [comment]
Looks like someone has started a plugin to do full screen webviews: https://github.com/dart-flitter/flutter_webview_plugin

**Comment by guidezpl** [comment]
Closing as out of scope for gallery
