### ISSUE TITLE
Running Gradle task 'assembleDebug'... Forever!

### ISSUE THREAD

**Issue by K-Schaeffer** [flutter/flutter#61670]
I've downloaded android studio yesterday to start studying flutter, but i'm facing a very frustrating issue.
It just doesn't start at all, and every time I create a new flutter project and try to run, it shows an error that the task "Clean" already exists, once I fix that, I see another error in the kotlin version, once I fix that, my app just don't finish the "assembleDebug" at all.

## Steps to Reproduce

1. Create a sample flutter project
2. Run the app

## Logs

```
```

![image](https://user-images.githubusercontent.com/37464395/87730442-323f7080-c79e-11ea-8b79-2f447cc435df.png)
```
```

**Comment by K-Schaeffer** [comment]
I got confused and closed the wrong issue, actually this one is solved, and the other is active.

**Comment by VladyslavBondarenko** [comment]
Hi @K-Schaeffer
could you provide your `flutter run --verbose` log?

**Comment by K-Schaeffer** [comment]
I fixed it with this:
![image](https://user-images.githubusercontent.com/37464395/87792330-1ed1eb00-c81a-11ea-8d5b-e26cf844290b.png)

Then, I removed my Flutter install files, and downloaded the git version.
Now I'm facing another issue: https://github.com/flutter/flutter/issues/61688
