### ISSUE TITLE
Text widget to change its colour and fontSize without using TextStyle

### ISSUE THREAD

**Issue by happyharis** [flutter/flutter#61690]
## Use case

I believe new developers has benefitted from the readability of the 'out of the box' colour parameter in container. Therefore, I am proposing the same with the commonly used Text widget.

Colour changes in Container widget has been introduced as follows:

```dart
Container(color: Colors.red)

// Instead of
Container(decoration: BoxDecoration(color: Colors.red));
```

Is the reason for container out of the box colour parameter better readability and ease of understanding for new Flutter developers? Otherwise, what's the reason?

However, text widget has no colour parameter out of the box. To change a colour, you have to type an additional object.

```dart
Text('example', style: TextStyle(color: Colors.red));
```

## Proposal

Have the text widget to have a colour and fontSize parameters without using TextStyle. These two parameters I believe is the most used parameters in the Text widget.

```dart
// Before
Text('example', style: TextStyle(color: Colors.red, fontSize: 30));

// After
Text('example', color: Colors.red, fontSize: 30);
```

**Comment by Pragya007** [comment]
@darshankawar  I would like to work on this proposal, can you guide me a bit? TextStyle property should not change, only color and fontSize is to be added for Text, am I right?

**Comment by Piinks** [comment]
I am going to close this since it is very unlikely we will do this. I have added it to the list in https://github.com/flutter/flutter/issues/24722 where we keep track of API improvements that would be nice, but we are not likely to make.

**Comment by feinstein** [comment]
We could have both, and an assert that says "you can't define both, you need to choose only color or a TextStyle". I believe other widgets have mechanisms like this. 

Also the changes on Text should be very small, as we just need to create a TextStyle if a color was defined, and keep the same underlying code unchanged, just the constructor would be affected.
