### ISSUE TITLE
[desktop] Unable to run app on Windows 7

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#61703]
Latest Flutter version from master. Desktop app on Windows 10, compiled without issues and it works fine. However, I'm getting problems to make it working on Windows 7 x64. First run - it prompts missing VisualStudio runtime dll libraries. So I installed VisualStudio runtime (installer from Microsoft). Now it does not prompt for missing libraries, but it crashes at startup.

Not sure if that's Flutter or VisualStudio related. Can you clarify? Is there anything I could try to make app compatibile with Windows 7?

**Comment by TahaTesser** [comment]
Hi @giaur500 
Can you upgrade to latest `master` and try again?
Can you upgrade to dev and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

With upgrade if problem persist,  Can you please provide your `flutter doctor -v` your `flutter run --verbose -d <window device>` and a complete reproducible minimal code sample
Thank you

**Comment by stuartmorgan** [comment]
> Is there anything I could try to make app compatibile with Windows 7?

It's not clear why you believe the issue here is Windows 7; in general, Flutter apps will run on Windows 7.

Please provide any logging produced when running the application, and also the backtrace of the crash.

**Comment by giaur500** [comment]
I was suspecting some kind of incompatibility due to VS compiler flags, and Windows 10 SDK is used. I am not sure if my app produces any logs, I will check that and will post it here

**Comment by stuartmorgan** [comment]
> and Windows 10 SDK is used

Using the Windows 10 SDK doesn't make Windows 10 the minimum supported version.

**Comment by giaur500** [comment]
I am unable to debug anything actually. App immediately shows prompt that it has stopped working. The only information is what I can get from windows event viewer:

```
myapp.exe 
   0.0.0.0 
   5f100cdf 
   flutter_windows.dll 
   0.0.0.0 
   5f0f12fe 
   40000015 
   0000000000883bbb 
   b84 
   01d663f4adb245c3 
   C:\Users\qemu\Desktop\myapp\myapp.exe 
   C:\Users\qemu\Desktop\myapp\flutter_windows.dll 
   ebc0d663-cfe7-11ea-94bd-525400123456 
```

Is that enough info to determine what's wrong?

**Comment by stuartmorgan** [comment]
> I am unable to debug anything actually. App immediately shows prompt that it has stopped working.

I don't follow; why can't you run it under a debugger?

> Is that enough info to determine what's wrong?

No, we need a crash stack, and/or logging from building it with the console enabled (in case there is an error message logged at launch)

**Comment by giaur500** [comment]
Please advice how to run under debugger. No VisualStudio installed on Windows 7 machine, app has been compiled under Windows 10

**Comment by stuartmorgan** [comment]
If you don't have access to a debugger on that machine, you should be able to get a crash log, then symbolicate it on your build machine where you have symbols.

**Comment by giaur500** [comment]
Is that described anywhere how to do that? Sorry, I'm not very familiar with this stuff on Windows, I have only managed to compile using Flutter's build script

**Comment by stuartmorgan** [comment]
There's nothing Flutter-specific about the process; see https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps for instance for information about getting a crash dump. I don't have step-by-step instructions to point to offhand though.

**Comment by giaur500** [comment]
Thanks, I will try to figure it out

**Comment by giaur500** [comment]
Well, I tried to add corresponding registry values to collect crash dump, but still no dump created. For now, I have no time for any further actions. That's why I don't like Windows systems, nothing is straightforward there. I will post here when I get something useful.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by anandsubbu007** [comment]
I'm also facing this issue. I build the flutter sample project in windows 10.
when I try to run that app in windows 7 64bit (VirtualBox) it showing following error. 

I can't able to find a crash log for this appcrash

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	testing.exe
  Application Version:	1.0.0.0
  Application Timestamp:	5faf58d7
  Fault Module Name:	flutter_windows.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5f97d13e
  Exception Code:	40000015
  Exception Offset:	00000000008ae2fb
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0cc9
  Additional Information 2:	0cc9a80ddcb658055df6cc2ae0b32f41
  Additional Information 3:	6758
  Additional Information 4:	6758af2cbac136a0e6084674842c5f15

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by hamdikahloun** [comment]
Hi @anandsubbu007 @stuartmorgan 



## Steps to Reproduce



1. Run `flutter create bug`.
2. Run `flutter build windows`.
3. Start the application in Windows 7 X64 Clean Install (Other Machine)

**Expected results:** Application Start

**Actual results:** Crash

<details>
  <summary>Logs Machine Dev</summary>



```
flutter doctor -v
[√] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [version 10.0.19041.630], locale fr-FR)
    • Flutter version 1.23.0-18.0.pre at D:\fork\flutter
    • Framework revision 37ebe3d82a (5 weeks ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [version 10.0.19041.630]

! Doctor found issues in 1 category.
```

</details>

After Install this Update (KB2670838 and KB4019990) the app work fine : 

[Update for DirectX](https://www.microsoft.com/en-us/download/details.aspx?id=36805)
[Update for the d3dcompiler_47.dll](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4019990)

**Comment by anandsubbu007** [comment]
Hi, @hamdikahloun 
still facing the same issue. I installed (KB2670838 and KB4019990) Updates.

**Comment by giaur500** [comment]
As far as I know Skia does not use DirectX, so mentioned updates can't be related

**Comment by hamdikahloun** [comment]
- [Microsoft Visual C++ Redistributable Package](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

- [Platform update for windows 7 sp1](https://support.microsoft.com/en-us/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1)

- [Update for the d3dcompiler-47 DLL](https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows)

- Windows 7 X64 SP1

- VMware Workstation 15 Player

- VMware Tools (Drivers) Installed

Platform update only             |  Platform update and d3dcompiler-47
:-------------------------:|:-------------------------:
![KB2670838Only](https://user-images.githubusercontent.com/32666446/99653178-02102300-2a59-11eb-9fb6-a2a0042b9adc.gif) | ![KB2670838andKB2834140](https://user-images.githubusercontent.com/32666446/99653249-13f1c600-2a59-11eb-8226-02c2d31ed282.gif)

**Comment by giaur500** [comment]
I think this issue should be opened again. Perhaps somebody is able to capture full debug to track root cause of this issue, I gave up but as I can see, some people reproduced issue

**Comment by stuartmorgan** [comment]
There are many, many reasons a process can crash on launch on a specific machine; we have no way of knowing if any of the comments above are related to the original issue, or to each other. Lumping all of them together into one issue just makes it harder to track and investigate them.

@hamdikahloun If you have a specific reproducible crash-on-launch case, please file a new issue with details. @anandsubbu007, same applies for your issue.
