### ISSUE TITLE
can't access --dart-define arguments in dart code when run native project in root/android folder with Android Studio

### ISSUE THREAD

**Issue by elanpang** [flutter/flutter#61713]
I have read this article that about --dart-define 
[Flutter 1.17 — no more Flavors, no more iOS Schemas. Command argument that changes everything](https://medium.com/@tatsu.ukraine/configure-your-flutter-environment-in-the-proper-way-b81782c79726)

I notice that after running 'flutter run --dart-define=ENV=QA' to launch app on iOS device by Command-Line, in iOS folder a Generated.xcconfig will be generated in xcode project, so next time I can debug app with xcode directly  the app can get ENV value through Generated.xcconfig in dart code. 
like:
`static const appEnv = String.fromEnvironment('ENV', '');`

But after running 'flutter run --dart-define=ENV=QA' to launch app on android device by Command-Line, then use Android Studio to open the native project in android root/folder,  debug app directly, the app still can't get  ENV value, is there any way that let me can debug android app and pass dart-define into app? without vscode or commond-line  because I need to debug native code with Android Studio but the command argument is required in dart code.

**Comment by VladyslavBondarenko** [comment]
Reproduces with current master `1.21.0-2.0.pre.55`.
Used [the project](https://github.com/TatsuUkraine/flutter_define_example) from [mentioned article](https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d)

**Comment by jonahwilliams** [comment]
This is not a bug - If you want to run through gradle you still need to provide the project args that flutter run would use. You can see these by running `flutter run -v` - the verbose logs will include the exact command to run

**Comment by elanpang** [comment]
Thanks for your help, found a solution.

flutter run -v can show command details, so I found the android native command is:

gradlew -Pdart-defines=flutter.inspector.structuredErrors=true,ENV=qa

-P, --project-prop means set project property for the build script (e.g. -Pmyprop=myvalue).

Then open AndroidStudio > Preferences > Build... > Complier,

added -Pdart-defines=ENV=qa to ComandLineOptions

It works!
