### ISSUE TITLE
[sysui] make docs reports Flutter SDK is not avialable

### ISSUE THREAD

**Issue by shakeel** [flutter/flutter#6171]
## Steps to Reproduce
make docs in $src/fuchsia/sysui fails with the following errors, same results occur on Linux and MacOS

make docs
Makefile:55: [WARNING] Goma not installed. Install Goma to get faster distributed builds.
rm -rf interfaces/lib
cd .. && packages/gn/gen.py  -m sysui && buildtools/ninja -j32 -C out/debug-x86-64
Done. Made 141 targets from 34 files in 182ms
ninja: Entering directory `out/debug-x86-64'
[3/3] STAMP obj/packages/gn/default.stamp
mkdir interfaces/lib
ln -s /home/shakeel/fuchsia/out/debug-x86-64/gen/sysui/interfaces/dummy.mojom.dart interfaces/lib/dummy.mojom.dart
cd tools/generate_dart_doc && /home/shakeel/fuchsia/sysui/third_party/flutter/bin/cache/dart-sdk/bin/pub run bin/main.dart
Error running pub get from /tmp/sysuix2qH5s
stdout
------------------------
Resolving dependencies...
------------------------
stderr
------------------------
The Flutter SDK is not available.
Depended on by:
- armadillo 0.0.0

------------------------
make: *** [Makefile:89: docs] Error 69

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /home/shakeel/fuchsia/sysui/third_party/flutter
    • Framework revision 6cdab85d28 (4 days ago), 2016-09-29 10:19:15
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-24, build-tools 24.0.2
    • OpenJDK Runtime Environment (build 1.8.0_102-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 6 • ZX1G2258QV • android-arm

**Comment by eseidelGoogle** [comment]
You'll want to update your makefile to use `flutter packages get` instead of `pub get`
https://groups.google.com/forum/#!topic/flutter-dev/djiZKDpcyjE

**Comment by sethladd** [comment]
Thanks for the report! This looks like an issue with fuscia or sys ui. Can you file the issue over at fuchsia.atlassian.net ?

**Comment by sethladd** [comment]
Going to close this for now, but please keep the feedback coming!

**Comment by shakeel** [comment]
Thanks @sethladd the fuchsia.atlassian.net issue tracker is not yet opened to outsiders

**Comment by sethladd** [comment]
hm, asking about that now :) stand by!
