### ISSUE TITLE
google_sign_in, catch idpiframe_initialization_failed exception

### ISSUE THREAD

**Issue by Producer86** [flutter/flutter#61712]
Hi,

When the user has "Block third-party cookies" enabled in the browser I get "google_sign_in, idpiframe_initialization_failed, Cookies are not enabled in _the_ current environment." exception.
I would like to catch this so I can show a message asking the user to enable thrid-party cookies (of course would be more than happy to hear about workarounds).

```dart
try {
    _googleSignIn =
        GoogleSignIn(scopes: <String>['email', 'profile', 'openid']);
} catch (e) { ... }
```

Doesn't seem to cut it.

**Comment by VladyslavBondarenko** [comment]
Hi @Producer86 
please follow up on https://github.com/flutter/flutter/issues/59145, closing as duplicate
