### ISSUE TITLE
[flutter_wayland] 'keys.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by limbouser** [flutter/flutter#61711]
I am using an embedder to run my Flutter application, a modified version of flutter_wayland by @chinmaygarde . It has been modified slightly to include keyboard support too https://github.com/dwrobel/flutter_wayland Modified by @dwrobel . My app mainly depends on keyboard navigation using arrow keys.

I created the test application provide by flutter team https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html using the below command.
`flutter create --sample=services.LogicalKeyboardKey.1 mysample`
I tried two stable SDK versions and the result obtained is also mentioned. I create the flutter_assets using the SDK and run it using Engine-Embedder-Assets combination. The engine version is kept constant and is the latest stable 1.17.3. When the SDK version used is 1.12.13, the arrow key navigation is working fine and app has no issues. But when flutter_assets is created using SDK version 1.17.3, an exception is thrown. Exception is raised only for Left and Bottom arrows, Right and Up are working fine.

```
`flutter: The following assertion was thrown during a platform message callback:

flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty':

flutter: is not true.`
```

```
SDK Version                    Engine version                   Result
1.12.13                            1.17.3                            No exception
1.17.3                              1.17.3                            Exception is present
master                             master                          Exception is present

```
The fact that when SDK is 1.12.13, all key navigation is good proves that my embedder is okay. I guess this is an SDK related issue, but none of the apps has issues when it is run without the embedder. What is actually happening here?
Most probably this issue is a duplicate of #48442 I had to mention in detail the issues I'm having and when they were happening. I am kind of stuck due to this in my project. How can I solve this or is there any work-around? I can have only arrrow key navigation in my app.

**Comment by stuartmorgan** [comment]
> none of the apps has issues when it is run without the embedder.

If it only happens with your embedder, that points strongly to an issue with your embedder.

> What is actually happening here?

The most likely explanation is that your embedder is sending bad key information.

I'm going to close this as the evidence here is that this a problem with a third-party embedding, and thus out of scope for this bug system. If you can provide the exact data you are sending to the framework, and it's actually correct, I can re-open.

**Comment by limbouser** [comment]
> The fact that when SDK is 1.12.13, all key navigation is good proves that my embedder is okay

When I built applications using SDK of version 1.12.13, and ran it using the same embedder, it was working fine with all keys working properly.

>  provide the exact data you are sending to the framework, and it's actually correct,
I am not quite sure how to do this. Some help.

**Comment by stuartmorgan** [comment]
> > The fact that when SDK is 1.12.13, all key navigation is good proves that my embedder is okay
> 
> @stuartmorgan When I built applications using SDK of version 1.12.13, and ran it using the same embedder, it was working fine with all keys working properly.

Desktop support is explicitly not a stable API surface at this point, so this doesn't prove that the embedder is doing things correctly now. It's also possible that the embedder has always been incorrect and it just didn't hit an assertion before.

> Also has there been any changes to perform key mapping from the older version to latest?

I don't know offhand. If you'd like to pinpoint the exact revision range where it changed you could check the PRs in that range, but I think it would be much simpler to just check that the data being sent is correct.

> > provide the exact data you are sending to the framework, and it's actually correct,
> 
> I am not quite sure how to do this. Some help.

When you added key event support, than involved constructing key event structures and sending them on a system channel. What we need is the content of that structure for the key events that are asserting.
