### ISSUE TITLE
Breakpoints doesn't work on a specific file with Android Studio

### ISSUE THREAD

**Issue by haytham-c01** [flutter/flutter#61722]
Breakpoints inside a specific file aren't working while they were working fine on other files using Android Studio.
However, after hours of trying the breakpoints worked when I completely copied (ctrl+a, ctrl+c) all the code into a new file (I have even used the same name and location as the old file)?!

I have tried the following solutions on the old file and to no avail:
1- checked if the imports are correct
2- renamed the file
3- commented everything inside the file including the imports, and create a new simple widget from scratch

this is the second debugging problem, the previous one was because using double "//" in the package import while the app was working just fine with no complaints!

Expected results: Breakpoints to work
Actual results: Breakpoints not working

[auth.zip](https://github.com/flutter/flutter/files/4937942/auth.zip)

**Comment by VladyslavBondarenko** [comment]
Hi @haytham-c01 
could you provide your `flutter doctor -v`?
can you reproduce it again? is debugging with breakpoints in DevTools not working as well?

**Comment by haytham-c01** [comment]
@VladyslavBondarenko 

### Flutter Doctor

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Hayth\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Hayth\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Hayth\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

### To Reproduce
It is working now so I can't reproduce

### About DevTools
I didn't try debugging with DevTools

I am closing the issue since it is working now and I just wanted to report the problems with debugging
