### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by Oma-Kharis** [flutter/flutter#61728]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @Oma-Kharis 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50880) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Oma-Kharis** [comment]
Thanks, I have been able to sort that out. But now I can't use my phone as emulator, how do I go around that?
