### ISSUE TITLE
i got this error cloudfirestore

### ISSUE THREAD

**Issue by Sreejith93** [flutter/flutter#61724]
Note: E:\Andriod\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.7\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

i got this error

**Comment by YazeedAlKhalaf** [comment]
This is related to FlutterFire plugins. I guess you need to open the issue there

**Comment by VladyslavBondarenko** [comment]
Hi @Sreejith93 
if your issue about cloudfirestore, consider to open it in https://github.com/FirebaseExtended/flutterfire/issues with filling out template. Comment if it turns out to be an issue with flutter and I'll reopen
