### ISSUE TITLE
[desktop:windows] Adding Code Obfuscation

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#61727]
I would like to see code obfuscation for windows apps, in a way that even the `data` folder is not there. Like, make it a .dll or a way that makes it impossible to get any data from the app.

Now when I build a Windows app, it has the assets shown for the user. That is not good. It is better if the user can have no use of any files except the .exe which launches them and uses them.

And the `.dll` files in the directory of the `.exe` are making it so obvious the app is made with Flutter, which makes it easier for Reverse Engineers to reverse engineer it. I hope it becomes more secure

**Comment by VladyslavBondarenko** [comment]
https://flutter.dev/docs/deployment/obfuscate - not yet supported for Windows and Linux

**Comment by stuartmorgan** [comment]
You've requested a number of largely unrelated things, which we can't reasonably track in a single issue. This will specifically track the code obfuscation feature linked above.

Please file new individual issues for other aspects. First though, please read https://github.com/flutter/flutter/issues/57875 as there is some overlap, so my comments about what to include in those new issue will be relevant. Specifically, things that would need new issues:
- > in a way that even the data folder is not there

  This is unrelated to code obfuscation. However:

  > make it a .dll or a way that makes it impossible to get any data from the app

  If it's impossible to get data from the app, then your app can't run. If you have, e.g., an image or font resource, it must be possible to get that data, or your app can't use it. If you file a new request for this, please explain in more detail what exactly you want the behavior to be, and what use case it solves, as it seems to be an impossible request as described.
- > it has the assets shown for the user. That is not good.

  If you file this, please elaborate on why (again, with specific use cases). Apps commonly have external resources, and "not good" doesn't describe the actual concerns you have.
- > And the .dll files in the directory of the .exe are making it so obvious the app is made with Flutter, which makes it easier for Reverse Engineers to reverse engineer it.

  It's not at all clear to me how that follows; anyone with the expertise to reverse engineer a compiled binary is going to be able to easily determine if it's using a popular framework regardless of whether it's statically or dynamically linked. If this is a core motivation for your bundling requests, please include more details on exactly how you believe this would make an appreciable difference. "Make it impossible for someone to tell you're using Flutter" (or, frankly, even moderately difficult) is probably an impossible request as well.

- > I hope it becomes more secure

  If you have security issues to report, please file new issues for those as well and provide clear descriptions, ideally with sample attacks.

**Comment by jonahwilliams** [comment]
--obfuscate is supported by windows and linux, the documentation is out of date. Please see https://github.com/flutter/website/issues/4154 .

If we're using this issue to track --obfuscate only, I'm marking this as fixed
