### ISSUE TITLE
Need a way to disable horizontal scroll indicator with ScrollBar

### ISSUE THREAD

**Issue by ngminhduong** [flutter/flutter#61723]
I have a PageView inside CustomScrollView with parent is ScrollBar allow user scroll by vertical.
But I have issue with ScrollBar is also show for Horizontal for GridView. I want disable it.

This is demo for issue.
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Scrollbar(
        child: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: Container(
                height: 200,
                child: PageView(
                  children: <Widget>[
                    Container(
                      height: 200,
                      color: Colors.green,
                    ),
                    Container(
                      height: 200,
                      color: Colors.blue,
                    )
                  ],
                ),
              ),
            ),
            SliverToBoxAdapter(
              child: Container(
                height: 700,
                color: Colors.grey,
              ),
            )
          ],
        ),
      )
    );
  }
```

**Comment by VladyslavBondarenko** [comment]
Hi @ngminhduong 
please follow up on https://github.com/flutter/flutter/issues/61723,
closing current issue as duplicate,
as workaround you can [wrap your PageView in NotificationListener this way](https://github.com/flutter/flutter/issues/36474#issuecomment-513325171)

**Comment by akram-95** [comment]
![image](https://user-images.githubusercontent.com/55693316/126694880-1b10bad6-21f2-4209-9dea-988069e25bf5.png)
- [ ] Kjjj

**Comment by akram-95** [comment]
![image](https://user-images.githubusercontent.com/55693316/126694966-7b036678-b918-43a6-905b-fd64d08bfb6a.png)
