### ISSUE TITLE
Flutter Linux app doesn't work after building

### ISSUE THREAD

**Issue by sonuishaq67** [flutter/flutter#61730]
![Screenshot from 2020-07-17 20-04-47](https://user-images.githubusercontent.com/55189255/87798202-53b95e80-c869-11ea-894c-b426e3dd6046.png)
### is this a bug? or is it normal If yes how do i try an app after building it from android studio? 
@ianloic 
@anaisbetts 
@sgraham 
@gmoothart 
@sethladd

**Comment by stuartmorgan** [comment]
Your screenshot shows you trying to run the raw build output; that is just an intermediate build file and should not be used directly. You need to run the copy in "bundle" which has had the necessary post-processing done and has the assets in the correct relative locations.

**Comment by stuartmorgan** [comment]
Also, please don't spam random contributors when filing issues.
